### ISSUE TITLE
The region selector does not work after adding it to the customer account creation page

### ISSUE THREAD

**Issue by engcom-Charlie** [magento/magento2#30099] opened 2020-09-18 08:27 UTC
### Preconditions (*)

- Magento 2.4-develop
- Php 7.3

### Steps to reproduce (*)

1. Create custom module;
2. Create layout **_customer_account_create.xml_** in _{custom_module}/view/frontend/layout/_

```xml
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="1column" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="customer_form_register">
            <arguments>
                <argument name="show_address_fields" xsi:type="boolean">true</argument>
            </arguments>
        </referenceBlock>
    </body>
</page>
```

3. Flush cache;
4. Go to Storefront;
5. Go to **Create an Account** page;

### Expected result (*)

1. Region selector is available

### Actual result (*)

:heavy_multiplication_x: The region selector is broken
![image](https://user-images.githubusercontent.com/51680850/93574547-34da6400-f9a1-11ea-9236-1b4eee6b7e0f.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment] 2020-09-18 08:43
The issue is reproducible on a fresh 2.4-develop

Actual Result: :heavy_multiplication_x: The region selector is broken

![2020-09-18_11-40](https://user-images.githubusercontent.com/51679138/93576956-25a8e580-f9a4-11ea-8e64-c55eaef9a2ed.png)

**Comment by magento-engcom-team** [comment] 2020-09-18 08:44
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37746` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gaiterjones** [comment] 2020-12-23 16:51
For anyone who like me has just wasted 2 hours trying to figure out why registration isn't working on 2.4.1 the fix was posted by @klein0r in the [original issue ](https://github.com/magento/magento2/issues/30752)(which has been largely ignored)


_magento2/app/code/Magento/Customer/view/frontend/templates/form/register.phtml_

```
"regionJson": <?= /* @noEscape */ $regionJson ?>,
"defaultRegion": "<?= /* @noEscape */ $regionId ?>",
"countriesWithOptionalZip": <?= /* @noEscape */ $countriesWithOptionalZip ?>
```

**Comment by engcom-Alfa** [comment] 2021-11-26 06:49
There is a [GithubIssue](https://github.com/magento/magento2/issues/22841) already existing and the fix is duplicating to this current logged issue. There is a [PR in progress](https://github.com/magento/magento2/pull/27608) containing this fix. Hence as part of associated PR, will be following-up with that older issue only! Further, this ticket information will be commented in the PR as well. Hence closing this current issue!

Kindly follow-up this [Issue](https://github.com/magento/magento2/issues/22841) and [PR](https://github.com/magento/magento2/pull/27608).

In case of any clarifications, please feel free to comment here, so that we will re-open if required!

Thanks

**Closed as completed by engcom-Alfa** 2021-11-26 06:49 UTC
Labels: Issue: Ready for Work, Component: Customer, Area: Frontend, Issue: Confirmed, Issue: Format is valid, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P2, Priority: P3, Severity: S2, Severity: S4, Priority: P1, Severity: S1, Progress: done, Reported on 2.4.0
