### ISSUE TITLE
The bug of Ajax add to cart after the second time at the same page

### ISSUE THREAD

**Issue by GoogleYY** [magento/magento2#15580] opened 2018-05-29 16:21 UTC
### Preconditions

1. Win 7 / CentOS Linux release 7.4.1708
2. PHP Version 7.0.28
3.Magento ver. 2.2.4
4.Luma blank theme without sample data

### Steps to reproduce

1. Go to product detail page, click Add to Cart button
2. Wait for seconds and then click the Add to Cart button on the same page of step1

### Expected result

1. It should be two items in the shopping cart

### Actual result

1.Three items in the shopping cart

Further steps to reproduce
I've tried many times and found that after the second time the quantities always be double by the input form of qty.

![a](https://user-images.githubusercontent.com/18476328/40693508-4b7014ca-63ea-11e8-9114-81a1ad9c51bb.png)
![b](https://user-images.githubusercontent.com/18476328/40693522-5bba65c4-63ea-11e8-9e3a-2d036a4dcded.png)

**Comment by PaperDS** [comment] 2018-05-30 14:42
Magento 2.2.4
Customised Luma theme
Having same Issue here.

**Comment by RavindraSaini** [comment] 2018-06-01 10:42
having same issue here anyone have the solution ?

**Comment by joebusby** [comment] 2018-06-01 20:31
I had a customer call indicating they received double their large order.  Now, after verifying the problem I am going back through many orders and calling customers.  It appears this will be costly.  Ouch.  Something soon?  We are going to have to call every customer on orders with quantities over 1 (almost all new orders) until we have a fix.

**Comment by simonjanguapa** [comment] 2018-06-02 10:45
#mm18nl

**Comment by magento-engcom-team** [comment] 2018-06-02 10:46
@simonjanguapa thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by hostep** [comment] 2018-06-02 12:13
This sounds like a duplicate of https://github.com/magento/magento2/issues/15052 which has a pending PR to fix it: https://github.com/amzn/amazon-payments-magento-2-plugin/pull/227

Can the people who run into this problem try to disable the Amazon modules (Amazon_Core, Amazon_Login & Amazon_Payment) which come bundled with Magento 2.2.4, and report back if this fixes the issue? Thanks!

**Comment by simonjanguapa** [comment] 2018-06-02 12:58
It's a problem within the Amazon_Payment module.

They're creating a custom add-to-cart widget which fails to override the core one. The validate-product.js in the Catalog module creates 1 request; the Amazon_Payment one creates the second.

I believe the Amazon_Payment/js/catalog-add-to-cart.js is completely unnecessary... since the core is already handling validation and the click event.

**Comment by hostep** [comment] 2018-06-02 13:03
Ok thanks for acknowledging @simonjanguapa, let's close this issue and continue in https://github.com/magento/magento2/issues/15052 then.

**Closed as completed by hostep** 2018-06-02 13:03 UTC
Labels: Issue: Clear Description, Issue: Format is valid, help wanted

**Comment by GoogleYY** [comment] 2018-06-03 01:36
@simonjanguapa Hey nice guy, thank you for your constructive answer. After I commented  self.submitForm($(this)); and this._bindSubmit(); in vendor\amzn\amazon-pay-and-login-magento-2-module\src\Payment\view\frontend\web\js\catalog-add-to-cart.js the problem solved!
