### ISSUE TITLE
Error on refresh when creating new order in admin

### ISSUE THREAD

**Issue by zunsakai** [magento/magento2#36296] opened 2022-10-14 07:30 UTC
### Preconditions and environment

- Magento version: 2.4.5 (developer mode)
- PHP 8.1
- Mysql 8.0

### Steps to reproduce

1. Install new magento, no sample data, no custom module.
2. In the admin, create a new customer and a new store view
4. Create a new order in admin > Select the customer just created.
5. At the step select store view, refresh page (F5)

### Expected result

Display list store view

### Actual result

Show query error:
```
3 exception(s):
Exception #0 (Magento\Framework\DB\Adapter\TableNotFoundException): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento_db.catalog_category_product_index_store0' doesn't exist, query was: SELECT `main_table`.*, IFNULL(wishlist.name, 'Wish List') AS `wishlist_name` FROM `wishlist_item` AS `main_table`
 INNER JOIN `wishlist` ON main_table.wishlist_id = wishlist.wishlist_id
 INNER JOIN `catalog_category_product_index_store0` AS `cat_index` ON cat_index.product_id = main_table.product_id AND cat_index.category_id = '0' AND cat_index.visibility IN (3, 2, 4) WHERE (wishlist.customer_id = 1) AND (`main_table`.`store_id` IN('0'))
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-10-14 09:20
@magento give me 2.4.4 instance

**Comment by engcom-Bravo** [comment] 2022-10-14 12:50
Hi @kylepham103,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop and 2.4.5 instances and the issue is not reproducible on both the instances.No Error on refresh when creating new order in admin.Kindly refer screenshots.

Steps to reproduce
1.Install new magento, no sample data, no custom module.
2.In the admin, create a new customer and a new store view
3.Create a new order in admin > Select the customer just created.
4.At the step select store view, refresh page (F5)


<img width="1488" alt="Screenshot 2022-10-14 at 5 07 05 PM" src="https://user-images.githubusercontent.com/51680745/195850890-246e9360-05d8-45c8-a458-674b53ab6528.png">



<img width="1405" alt="Screenshot 2022-10-14 at 5 07 40 PM" src="https://user-images.githubusercontent.com/51680745/195850958-38063b4d-e4fe-42a4-80bb-e83124d6058c.png">

**Comment by engcom-Bravo** [comment] 2022-10-28 06:58
Hi @kylepham103,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.


Thanks.

**Closed as completed by engcom-Bravo** 2022-10-28 06:58 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.5
