### ISSUE TITLE
Double Credit Memo problem for paypal payflow order

### ISSUE THREAD

**Issue by claudioxu** [magento/magento2#35193] opened 2022-03-15 03:07 UTC
Hello,

We are facing the same problem with https://github.com/magento/magento2/issues/24149,  we are using 2.3.5-P1(CE), seems the problem still exists on 2.3.5.

Thanks,
Claudio

**Comment by claudioxu** [comment] 2022-03-15 03:15
@magento give me a patch for this

**Comment by claudioxu** [comment] 2022-03-15 03:17
@aredridel @jaywilliams @alepane21 @dthomas

**Comment by engcom-Delta** [comment] 2022-03-15 05:47
Hi @claudioxu ,
Thank you for raising an issue. Kindly provide more clear issue discerption, actual results and expected results and appropriate screenshots if required. 
Hence added 'Needs Update' label.

**Comment by claudioxu** [comment] 2022-03-15 06:59
There are two duplicated refund records, one is from online refund, another one is from offline, we just submit one online refund, but got an offline refund as well, which we expected  should be one online refund record.

![2022-03-15_14-54](https://user-images.githubusercontent.com/226139/158323181-a947f3ab-c2d1-49ff-bda2-be1d8344df94.png)
![2022-03-15_14-53](https://user-images.githubusercontent.com/226139/158323193-1f17eb0b-94e7-4794-90a7-b5c4593cb552.png)

**Comment by claudioxu** [comment] 2022-03-17 00:49
Hello,

any updates?

**Comment by engcom-Delta** [comment] 2022-03-21 11:37
Hi @claudioxu ,
We tried to reproduce the issue on Magento 2.4 Develop with local setup.In fact i am able to place offline refund successfully . there is no duplication issue .But we are not able to place online refund due to 'Refund' button is missing as below:

**Comment by claudioxu** [comment] 2022-03-22 08:43
Hello @engcom-Delta ,

Thanks for your updates. This just happened on PayPay Payflow orders, and we are using 2.3.5-P1(CE).



Claudio

**Comment by claudioxu** [comment] 2022-03-22 08:44
that's the same case with https://github.com/magento/magento2/issues/24149.

**Comment by claudioxu** [comment] 2022-03-31 01:08
Hello, 

any updates?

**Comment by claudioxu** [comment] 2022-04-12 01:10
Hello  @engcom-Delta,

any updates?

**Comment by wanghsingchuan** [comment] 2022-04-26 09:44
Same issue here!
Any solution?

But My operate was exactly opposite, here's my step:
First, I created offline refund.
Sec, Paypal admin panel refund.
Third, Magento duplicate a credit memo like First step.

**Comment by engcom-Delta** [comment] 2022-05-20 16:29
Hi @claudioxu ,
We have placed an order with PayPal PayFlow and but we are unable to find out online refunds. Kindly help me to reproduce it with clear steps.

Here are the screenshots for reference.
step1: Placed an order with PayPal PayFlow from FrontEnd

<img width="1275" alt="Screenshot 2022-05-20 at 9 08 07 PM" src="https://user-images.githubusercontent.com/51681379/169563241-2062b673-d801-4906-be78-33cde1e3bb17.png">
<img width="878" alt="Screenshot 2022-05-20 at 9 09 19 PM" src="https://user-images.githubusercontent.com/51681379/169563595-d17dcbe8-4186-40b6-b0c4-e57ec42800e9.png">


step2: offline refund from Admin Panel

<img width="1440" alt="Screenshot 2022-05-20 at 9 29 14 PM" src="https://user-images.githubusercontent.com/51681379/169567405-669c3084-6da0-46a6-9691-4bc70cb5dc10.png">

step3 : again perform online refund.

Observed that there is no duplication of credit memo created.
<img width="1440" alt="Screenshot 2022-05-20 at 9 29 14 PM" src="https://user-images.githubusercontent.com/51681379/169568259-9e4699f5-acd8-41a6-ae17-d7daa73eaa16.png">
<img width="1440" alt="Screenshot 2022-05-20 at 9 37 29 PM" src="https://user-images.githubusercontent.com/51681379/169568464-a1cd3583-bea9-4992-81ab-201e6d7046df.png">

**Comment by engcom-Delta** [comment] 2022-06-03 06:15
We have noticed that this issue has not been updated for a period of more than 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Closed as completed by engcom-Delta** 2022-06-03 06:15 UTC
Labels: Issue: needs update
