### ISSUE TITLE
I cannot find the Web Setup Wizard

### ISSUE THREAD

**Issue by zhiyicai** [magento/magento2#5419] opened 2016-07-02 16:48 UTC
I installed the magento 2.1.0
I cannot find the Web Setup Wizard

![123](https://cloud.githubusercontent.com/assets/13891311/16541518/8d1ccab0-4085-11e6-89d7-17bd67294914.PNG)

**Comment by commcad** [comment] 2016-07-03 17:52
Having the same issue here. Upgraded from 2.0.7 archive to 2.1.0 GA

Web Setup Wizard does not appear under System > Tools. It's gone, literally loll

I've tried to re-installed a clean Magento 2.1.0 GA installation but had the same results.

Ubuntu 16.04
NGINX 10
PHP 7.0.7 (using 3rd party PPA)
MariaDB
Redis 3

**Comment by pboisvert** [comment] 2016-07-04 17:24
@zhiyicai was this also an upgrade from 2.0.7 to 2.1 for your case?

**Comment by ghost** [comment] 2016-07-04 17:25
Is your Magento docroot the `pub` subdirectory?

**Comment by zhiyicai** [comment] 2016-07-04 17:37
@pboisvert 
Upgrade from 2.0.7 archive to 2.1.0 GA , Web Setup Wizard does not appear under System > Tools. It's gone
I've tried to re-installed a clean Magento 2.1.0 GA installation but had the same

**Comment by pboisvert** [comment] 2016-07-04 18:00
thanks for confirmation. Should help to troubleshoot this as an upgrade issue

**Comment by commcad** [comment] 2016-07-04 21:07
@xcomSteveJohnson 
1. Using: root $MAGE_ROOT/pub;
2. Copying my nginx environment below. Runs fully on TLS1.2 only over http2 (i.e. https only).
3. Haven't tried on Apache.

[deleted]

**Comment by ghost** [comment] 2016-07-04 21:54
@commcad Because `pub` and `setup` are at the same level, you won't be able to run the Web Setup Wizard if `pub` is your root. It's designed that way so that if you use `pub` as your docroot in production, no one can access the Web Setup Wizard.

Here's what we advise: "create another subdomain or docroot that uses the Magento installation directory as its root." 

If you've done that already, hopefully someone with more nginx expertise than I have can help you.

**Comment by commcad** [comment] 2016-07-05 05:30
@xcomSteveJohnson 
@pboisvert

Silly, didn't realized how well designed this Magento was - rather new to Magento, apologies.

Confirmed, it works beautifully when a sub domain is created using nginx > 
1. set $MAGE_MODE developer;
2. root $MAGE_ROOT/;
3. refresh page cache, redis flushall, logout/login

The Web Setup Wizard is now accessible and shows up as it used too in the admin backend under system > tools also 

Thanks Steve

**Comment by ghost** [comment] 2016-07-05 12:27
Glad it worked!

**Comment by andimov** [comment] 2016-08-04 07:52
@commcad
Thank you for reporting!
As I understand, we can close this issue?

**Comment by andimov** [comment] 2016-08-19 08:14
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Closed as completed by andimov** 2016-08-19 08:14 UTC
Labels: Progress: needs update
