### ISSUE TITLE
Sales Order invoice Update Qty's Button is misaligned

### ISSUE THREAD

**Issue by SyntaxKay** [magento/magento2#19796] opened 2018-12-15 07:13 UTC
### Preconditions (*)

1.Magento 2.2-develop
2.Magento 2.3-develop

### Steps to reproduce (*)

1.Login to backend-> Order -> View order 
2.Generate Invoice -> Items to Invoice -> Check Update Qty's Button

### Expected result (*)

1.https://prnt.sc/lv7z6n

### Actual result (*)

1.https://prnt.sc/lv7yxk

**Comment by magento-engcom-team** [comment] 2018-12-15 07:13
Hi @speedy008. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@speedy008 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-12-15 08:57
@dmytro-ch Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97176`, `MAGETWO-97177` were created

**Comment by magento-engcom-team** [comment] 2018-12-30 21:30
Hi @speedy008. Thank you for your report. 
The issue has been fixed in magento/magento2#19804 by @speedy008 in 2.2-develop branch
Related commit(s):
 - [7d7ff683134f0288cf80f4809ceab0906663923a](https://github.com/magento/magento2/commit/7d7ff683134f0288cf80f4809ceab0906663923a)
 - [539a558138344faffc48acff1948b7413b9c0602](https://github.com/magento/magento2/commit/539a558138344faffc48acff1948b7413b9c0602)

The fix will be available with the upcoming 2.2.8 release.

**Closed as completed by magento-engcom-team** 2018-12-30 21:30 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Backend

**Comment by sidolov** [comment] 2019-01-04 22:18
Hi @speedy008. Thank you for your report. 
The issue has been fixed in magento/magento2#19799 by @speedy008 in 2.3-develop branch
Related commit(s):
 - [e30a0805eae4e2fbc448435405bf399080847dfe](https://github.com/magento/magento2/commit/e30a0805eae4e2fbc448435405bf399080847dfe)
 - [8a3fa6157fe0d416303fb04270522db484870400](https://github.com/magento/magento2/commit/8a3fa6157fe0d416303fb04270522db484870400)

The fix will be available with the upcoming 2.3.1 release.
