### ISSUE TITLE
bad code refactoring causes loading section data after each request

### ISSUE THREAD

**Issue by vicobohdan** [magento/magento2#23208] opened 2019-06-11 13:21 UTC
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

1. After second and more page request 

### Expected result (*)

1. not load section data

### Actual result (*)

1. load section data

### Solution
change in file magento/module-checkout/view/frontend/web/js/view/minicart.js:106
from 
cartData().store_id !== window.checkout.storeId
to
cartData().storeId !== window.checkout.storeId

**Comment by EternalBobby** [comment] 2019-06-12 11:47
Hello @vicobohdan !Thank you for your report, but I can`t reproduce your issue

**Comment by vicobohdan** [comment] 2019-06-13 07:04
But I can reproduce on magento 2.3.1 "Vanilla", load section data again and again after each request.
in file magento/module-checkout/view/frontend/web/js/view/minicart.js:106
is undefined store_id variable used in if condition, causes that section data are loaded for each req., that is really bad, and if section data not changed it shouldn't load again
Pls reopen.

![Screenshot from 2019-06-13 08-43-02](https://user-images.githubusercontent.com/41510583/59410447-2aeaae00-8db9-11e9-97b8-16cf4dc580fc.png)

section data with variable storeId 
![Screenshot from 2019-06-13 08-46-18](https://user-images.githubusercontent.com/41510583/59410485-3f2eab00-8db9-11e9-8807-0d1dd00ae889.png)

and summary bad minicart.js with cartData().store_id variable that not exist, it has name storeId
![Screenshot from 2019-06-13 08-49-40](https://user-images.githubusercontent.com/41510583/59410602-87e66400-8db9-11e9-8a1a-2c6cbb7b8d49.png)

**Comment by hostep** [comment] 2019-06-14 18:31
Re-opening since @vicobohdan seems to have a point here.

I can reproduce this in 2.3.1 and the `2.3-develop` branch, but not in 2.3.0

This could be a possible regression introduced by [MAGETWO-96421 - Header Minicart, Shopping cart page and Checkout page show incorrect product name](https://github.com/magento/magento2/commit/c2500faf7d1e40d9dd5acada495f8a4a9d84dce8), I think.

@vicobohdan: do you want to create a Pull Request with your suggested change? I think it is correct.

**Comment by vicobohdan** [comment] 2019-06-15 09:54
I tried to push branch with fix but I got error
fatal: unable to access 'https://github.com/magento/magento2.git/': The requested URL returned error: 403

so pls fix someone...

**Comment by hostep** [comment] 2019-06-16 08:30
@vicobohdan: the correct way to send in a pull request is by first forking the magento2 repo to your own github account. Cloning that repo on your local. Setting up an upstream remote. Then on your local, create a new branch based on the `2.3-develop` branch from the upstream remote. Add a commit, and push that new branch to your own fork. And then you can create a PR using the Github interface.
More detailed step-by-step info over here: https://github.com/magento/magento2/wiki/Getting-Started

If this doesn't work for you for some reason, let me know and I'll see if I can create a PR for this.
But doing it yourself can be very useful as you'll then be able to send in other PR's if you find more bugs to fix 🙂

**Comment by vicobohdan** [comment] 2019-06-17 07:03
thanks for advice, pull request was created: https://github.com/magento/magento2/pull/23282

**Comment by engcom-Charlie** [comment] 2019-08-22 08:30
Hello @vicobohdan 
Check for the storeId has been removed, because we should clear customer data when the user changes the website instead of the store. I'm closing this issue as not relevant.
Thank you for your contribution!

**Closed as completed by engcom-Charlie** 2019-08-22 08:30 UTC
Labels: Issue: Format is valid
