### ISSUE TITLE
[2.1.0] Sometimes WYSIWYG editor does not show.

### ISSUE THREAD

**Issue by peec** [magento/magento2#6222] opened 2016-08-18 11:03 UTC
### Preconditions
1. PHP 7.0.3
2. Mysql 5.6
3. Latest chrome browser
4. Magento environment: Production 
5. JS / CSS minifcation and merging enabled.
### Steps to reproduce
1. Go into any page with a wysiwyg editor possiblity ( e.g. product edit page ).
2. See that sometimes it does not appear
3. Try clicking "Show editor". Nothing happens.
4. If you click the "Show/Hide editor" and do F5 refresh the page, suddenly the WYSIWYG editor shows.
### Expected result
1. When toggling between Show/Hide editor you should get the WYSIWYG editor.
### Actual result

Editor not showing (randomly) . Sometimes it does, sometimes not. A browser refresh might do so the editor opens..

**Comment by vivek201** [comment] 2016-08-18 16:10
This is not completely random.

## Steps to reproduce

### Method 1:
1. Go to `Content` > `Pages` in backend
2. Edit any page but while editing right click on the `Edit` link and open the link in a new page.
3. Wait for the page to be loaded before switching to the page.
4. The WYSIWYG editor will not be loaded

### Method 2:
1. Reload the page, but switch to another tab quickly.
2. Wait for the page to be loaded.
3. The WYSIWYG editor will not be loaded.

### Method 3:
1. Reload the page
2. Stay on the page until it is completely loaded.
3. The WYSIWYG editor will now be loaded.
4. For that tab, the WYSIWYG editor will be loaded even if we reload the page and switch to another tab.
5. Close that tab, and go through Method 1 for that same page, the WYSIWYG editor will not be loaded

I tested this using a fresh M2.1 installation without any customization or sample data.

**Comment by orbitrod** [comment] 2016-08-18 23:44
I have been having the same problem with the WYSIWYG as well on M2.0.7 and M2.1.   

Thanks @vivek201 for figuring out how to reproduce the problem.

**Comment by MomotenkoNatalia** [comment] 2016-08-26 12:52
Hi @peec! Thanks for reporting this! I have created an internal ticket to fix this issue - MAGETWO-57675. @vivek201 We are appreciate your help with detailed steps to reproduce!

**Comment by vivek201** [comment] 2016-08-26 13:13
@MomotenkoNatalia Thanks for the response! I was starting to wonder if this was an issue on just my system.

**Comment by ghost** [comment] 2016-09-12 18:54
I am seeing the same issue with 2.1.1. The WYSIWYG editor shows up after refreshing the page and staying on it until it fully loads again.

**Comment by SerhiyShkolyarenko** [comment] 2016-10-19 12:54
Fix is delivered to the develop branch. Closing the issue.
Issues for backporting to 2.0.x and 2.1.x branches are MAGETWO-59691 and MAGETWO-59688 correspondingly.

**Closed as completed by SerhiyShkolyarenko** 2016-10-19 12:54 UTC
Labels: Issue: Ready for Work, bug report, Component: Cms

**Comment by ewallkrishnaprakash** [comment] 2017-04-01 10:32
The mentioned commit was not working properly. Still i have face the issue after use the following commit.
https://github.com/magento/magento2/commit/3524943ac6544ee969480536ef6f0cd1a29b0b56 

I have check the js confilicts, required resources everything fine. But still I have face the issue.
Kindly any one suggest a proper solutions for this issue.

I have using magento 2.1.1
I have face this issue all browsers other then chrome.

Screen-shots: 
http://prnt.sc/er3dbz
http://prnt.sc/er3e39

**Comment by TiEul** [comment] 2017-04-03 12:51
I am also still experiencing this issue on Magento 2.1.5, are there any plans to merge this fix into the next minor 2.1.x release?

**Comment by conveydk** [comment] 2017-04-13 11:04
It's still an issue on 2.1.6. It's a nuisance these small issues aren't getting fixed quickly.

**Comment by jobsmartdesigner** [comment] 2017-06-01 17:58
I am having this issue as well and I created an issue, I am pretty new to magento so it would be helpful to have it fixed. At this point I am unable to update the product descriptions at all even when I out new info in and save the page, the new changes do not take effect and there is no editor no matter how long I wait. 
I also see that all the html tags are showing up in the description and none of the videos are showing either.
Someone PLEASE help!!
![screenshot 196](https://cloud.githubusercontent.com/assets/29125697/26693485/54a52ec6-46d2-11e7-8abc-22ff73e5da5c.png)

**Comment by magento-team** [comment] 2017-07-31 23:01
Internal ticket to track issue progress: MAGETWO-68903

**Comment by asfandsheraz** [comment] 2019-07-22 07:04
Hi #magento-team so I suppose that your (Internal ticket to track issue progress: MAGETWO-68903) is still under progress.???? It's been 3 years since this issue occurs.

**Comment by asfandsheraz** [comment] 2019-07-22 07:09
why this visibility: hidden; is here when I uncheck this then editor appears.
![image](https://user-images.githubusercontent.com/19729253/61612817-02d45180-ac79-11e9-95d7-70a17b2e7c09.png)


![image](https://user-images.githubusercontent.com/19729253/61613046-afaece80-ac79-11e9-8989-65bb414a5f1b.png)

**Comment by asfandsheraz** [comment] 2019-07-22 07:18
Well here is he solution if any one need. use this setting 
![FireShot Capture 004 - Configuration _ Settings _ Stores _ Magento Admin - www rabtstore pk](https://user-images.githubusercontent.com/19729253/61613450-cb66a480-ac7a-11e9-88ca-fb9cfb149be6.png)
