### ISSUE TITLE
[Qty | Bug]User is able to proceed with floating value(0.8, 1.7 etc...) of qty and price is displayed according to floating qty in magento default 

### ISSUE THREAD

**Issue by shrey126** [magento/magento2#27153] opened 2020-03-04 11:29 UTC
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. Open any E-commerce magneto website 
2. Navigate to PLP 
3. Add product into cart > Navigate to cart page 
4. Remove qty count > Hit Update cart button 
5. Observe that error message appears 
6. Change qty to floating(0.4, 1.3 etc...) > Click update cart 
7. Do proceed to checkout 

### Expected result (*)

1. If any user entered floating value in qty box then validation message should be appear and not able to proceed further 

### Actual result (*)

1. User is able to proceed with floating value in magento default

### Impact (*)
1. Price is getting changed according to the floating qty which should not be

**Comment by ajijshekh123** [comment] 2020-03-04 13:42
Hello @shrey126 ,
I have verified this issue in the default Magento 2.4 instance. Floating qty is updated and its subtotal is updated as per the default Magento functionality.
In the Product block, I have set ' Qty Uses Decimals > No' so why the system is accepted floating qty.

Thanks.

**Comment by magento-engcom-team** [comment] 2020-03-04 13:44
@ajijshekh123 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2020-03-04 13:46
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32139` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by maheshWebkul721** [comment] 2020-03-05 06:30
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-05 06:31
Hi @maheshWebkul721. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-03-05 06:31
Hi @maheshWebkul721, here is your [Magento instance](https://i-27153-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27153-2-4-develop.instances.magento-community.engineering/admin_7bb2](https://i-27153-2-4-develop.instances.magento-community.engineering/admin_7bb2)
Login: `21b7a6fe` Password: `d7da360cb3d3`
Instance will be terminated in up to 3 hours.

**Comment by duffner** [comment] 2020-03-07 15:43
Magento has a feature for decimal based inventory.  Please do not forget about this feature in addressing this ticket.

**Comment by niravkrish** [comment] 2020-03-21 10:53
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-21 10:53
Hi @niravkrish. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-03-21 10:54
Hi @niravkrish, here is your [Magento instance](https://i-27153-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27153-2-4-develop.instances.magento-community.engineering/admin_b4fb](https://i-27153-2-4-develop.instances.magento-community.engineering/admin_b4fb)
Login: `04d81c91` Password: `c4a42310efa5`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment] 2020-07-23 17:17
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-07-23 17:17
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-07-23 17:18
Hi @sdzhepa, here is your [Magento instance](https://i-27153-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27153-2-4-develop.instances.magento-community.engineering/admin_72d6](https://i-27153-2-4-develop.instances.magento-community.engineering/admin_72d6)
Login: `ef554e47` Password: `3e8ba187c91a`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment] 2020-07-23 17:29
Hello @shrey126
cc: @ajijshekh123

I am not able to reproduce this issue by steps from precondition on the latest `2.4-develop`

Probably the issue was already fixed or I missed some steps or preconditions.

Could you please confirm that issue is not actual anymore or provide additional details?

![issue_27153](https://user-images.githubusercontent.com/3409584/88318157-f0ec1b00-ccdf-11ea-80b8-87b13576545c.gif)

**Comment by sdzhepa** [comment] 2020-08-13 17:52
Closed as cannot reproduce

**Closed as completed by sdzhepa** 2020-08-13 17:52 UTC
Labels: Issue: Ready for Work, Component: Catalog, Component: Sales, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Issue:  Cannot Reproduce, Issue: Format is valid, Reproduced on 2.4.x
