### ISSUE TITLE
Restricting use of voucher codes to 1 timer per customer on Magento community edition v 2.1.7

### ISSUE THREAD

**Issue by brushbaby** [magento/magento2#12783] opened 2017-12-18 10:08 UTC
We have a voucher code designed for 10% off first order only  - it is under "Marketing" ->"cart price rules"  and there is an option to limit "uses per customer" to 1 , but this is enforced for Logged in customers only
Most of our customers choose to checkout as a "guest" so therefore they seem to have been able to use this voucher code multiple times.
Please advise how we resolve this, surely it must pick up their email address somewhere so we can see that they have used this code previously.

Please advise how this can be fixed so a coupon really is only 1 time use for ALL customers whether logged in or not.
Many Thanks
Sally Ann

**Comment by magento-engcom-team** [comment] 2017-12-18 12:05
@brushbaby, thank you for your report.
Your issue is duplicate of the issue [776](https://github.com/magento/magento2/issues/776).

**Closed as completed by magento-engcom-team** 2017-12-18 12:05 UTC
Labels: Issue: Format is not valid

**Comment by srenon** [comment] 2017-12-18 17:51
Since this core fix only seem to apply to M2.3 try https://github.com/magepal/coupon-limit-guest-checkout
