### ISSUE TITLE
Consumer product_action_attribute.update skips products in batch if previous product fails do to URL rewrite issue

### ISSUE THREAD

**Issue by ereztaiar** [magento/magento2#38895] opened 2024-07-02 10:49 UTC
### Preconditions and environment

- Magento version 2.4.5-p1
Products in batch jobs running processed by the product_action_attribute.update consumer being skipped if in that batch there is a product that cannot be rerwiten

The issue is with the url rewrite observer
magento/vendor/magento/module-catalog-url-rewrite/etc/events.xml
<event name="catalog_product_attribute_update_before">
        <observer name="process_url_rewrite_on_change_product_visibility" instance="Magento\CatalogUrlRewrite\Observer\ProcessUrlRewriteOnChangeProductVisibilityObserver"/>
    </event>
And the file 
magento/vendor/magento/module-catalog-url-rewrite/Model/Products/AdaptUrlRewritesToVisibilityAttribute.php  
The function 
```
/**
     * Process Url Rewrites according to the products visibility attribute
     *
     * @param array $productIds
     * @param int $visibility
     * @param int $storeId
     * @throws UrlAlreadyExistsException
     */
    public function execute(array $productIds, int $visibility, int $storeId): void
    {
        $products = $this->getProductsByIds($productIds, $storeId);

        /** @var Product $product */
        foreach ($products as $product) {
            if ($visibility == Visibility::VISIBILITY_NOT_VISIBLE) {
                $this->urlPersist->deleteByData(
                    [
                        UrlRewrite::ENTITY_ID => $product->getId(),
                        UrlRewrite::ENTITY_TYPE => ProductUrlRewriteGenerator::ENTITY_TYPE,
                        UrlRewrite::STORE_ID => $storeId,
                    ]
                );
            } elseif ($visibility !== Visibility::VISIBILITY_NOT_VISIBLE) {
                $product->setVisibility($visibility);
                $productUrlPath = $this->urlPathGenerator->getUrlPath($product);
                $productUrlRewrite = $this->urlRewriteGenerator->generate($product);
                $product->unsUrlPath();
                $product->setUrlPath($productUrlPath);

                try {
                    $this->urlPersist->replace($productUrlRewrite);
                } catch (UrlAlreadyExistsException $e) {
                    throw new UrlAlreadyExistsException(
                        __(
                            'Can not change the visibility of the product with SKU equals "%1". '
                            . 'URL key "%2" for specified store already exists.',
                            $product->getSku(),
                            $product->getUrlKey()
                        ),
                        $e,
                        $e->getCode(),
                        $e->getUrls()
                    );
                }
            }
        }
    }
```

### Steps to reproduce

1. go to Catalog > products
2. select batch of product
3. go to action select and chose update attributes
4. change the visibility attribute to "catalog, search"
5. save

Note: that a product in the batch of products selected needs to be on search or not visible and we change it to visible and that the product has a URL key that is in use on other product. When the product throws an exception all the product after it in the batch are ignored

Batch in this case is part of the batch loop ($serializedData) in the file 
magento/vendor/magento/module-catalog/Model/Attribute/Backend/Consumer.php

On the function
```
public function process(\Magento\AsynchronousOperations\Api\Data\OperationInterface $operation)
    {
        try {
            $serializedData = $operation->getSerializedData();
            $data = $this->serializer->unserialize($serializedData);
            $this->execute($data);
        }
         ...
}
```

### Expected result

A Error log for that one product and all the valid products gets proccessed

### Actual result

An error is thrown and the rest of the list is ignored

### Additional information

The return error for some of the products that prevent other products from being proccessed
<html>
<body>

1106 | Update product attributes | Can not change the visibility of the product with SKU equals "5002128G". URL key "ksa-rhch-vwirvtim-lhneh-ecmit-51-s-m" for specified store already exists.
-- | -- | --
1114 | Update product attributes | Can not change the visibility of the product with SKU equals "5001249". URL key "5001249" for specified store already exists.
1121 | Update product attributes | Can not change the visibility of the product with SKU equals "5004111". URL key "rvltvr-4-glglim-dv-wimvwi-em-ksa-cbe-ktvm" for specified store already exists.

</body>
</html>

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-07-10 10:45
Hi @ereztaiar,

Thanks for your reporting and collaboration.

We have verified the issue in latest 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

**Steps to reproduce**

- go to Catalog > products
- select batch of product
- go to action select and chose update attributes
- change the visibility attribute to "catalog, search"
- save



https://github.com/magento/magento2/assets/51680745/31041d68-eeeb-490d-bc4b-bbca6533601c



Mass update was successfully done.

Could you please elaborate the steps to reproduce and please let us know if we are missing anything.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-07-22 08:12
Hi @ereztaiar,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-22 08:12 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1
