### ISSUE TITLE
Wrong order ID: "5000000139". {"exception":"[object] (Exception(code: 0): Wrong order ID: \"5000000139\". at /var/www/html/src/vendor/magento/module-paypal/Model/Ipn.php:140

### ISSUE THREAD

**Issue by venky53** [magento/magento2#33367] opened 2021-06-28 06:15 UTC
When using paypal express integration as the payment method on Magento 2.2.9 a small number of orders fail after the payment has been taken by paypal. No order is registered in Magento, but paypal takes payment and sends a confirmation to both customer and store owner.

Looking in the logs the error which seems to be associated with these orders failing is:
main.CRITICAL: Wrong order ID: "5000000139". {"exception":"[object] (Exception(code: 0): Wrong order ID: \"5000000139\". at /var/www/html/src/vendor/magento/module-paypal/Model/Ipn.php:140)"}

### Preconditions (*)

1.Magento 2.2.9
2.Paypal Express Checkout set as Payment method.

### Steps to reproduce (*)

Customer Places Order
Directed to PayPal page and payment taken
Redirected to site, order fails and is not logged in Magento.

### Expected result (*)

Once payment has been taken and the customer has been redirected back to the site order is registered with magento.

### Actual result (*)

Payment is taken.
Paypal redirects to site and sends confirmation email with correct order number.
Order is not registered in magento.
Order ID skips failed order (next order number is incremented from failed order, orders list in backend has a gap where failed order would have been).

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

S1

- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround.

**Comment by engcom-November** [comment] 2021-06-28 12:30
Hi @venky53,
Verified the issue on Latest Magento version 2.4-develop and the issue is not reproducible.
**Steps performed:**
1. Magento Admin - Configured PayPal Express Checkout payment method
2. Front End - Added the Product to cart and checkout - Paid with PayPal Express Checkout. Order placed successfully responding with Order Number.
3. Admin -> Sales -> Order Grid -> Newly created Order is updated. 

Kindly do test on **latest Magento version** and let us know the reproducible steps if you are still facing the issue.
Thank you.

**Comment by venky53** [comment] 2021-06-28 12:38
Hi @engcom-November,

https://github.com/magento/magento2/issues/15427

can you fetch more information from the above url.

**Comment by engcom-November** [comment] 2021-06-28 12:50
Issue is not reproducible on 2.4-develop version. Can you please try on latest version and let us know if the issue is still reproducible.
Thanks.

**Comment by venky53** [comment] 2021-06-28 12:54
Hi @engcom-November,

Please let me know the cause for the issue in the version I have mentioned. So that we can rectify in our instance.

Thanks

**Comment by engcom-November** [comment] 2021-07-12 13:45
Hi @venky53,
Its recommended to verify the issues on Magento 2.4-develop branch only. Kindly upgrade your Magento version and check the payment. Closing this issue as order is registered as expected in Magento admin.
Thank you.

**Closed as completed by engcom-November** 2021-07-12 13:45 UTC
Labels: Issue:  Cannot Reproduce, Component: Paypal, Issue: ready for confirmation, Reported on 2.2.x

**Comment by achatpc** [comment] 2022-04-17 01:22
same issue on 2.4.3-p1
