### ISSUE TITLE
Error Sample data

### ISSUE THREAD

**Issue by vinhtrau** [magento/magento2#1617] opened 2015-08-05 06:22 UTC
This error has occurred when I install new magento2 with sample data.
I already run composer install/update.
<img width="991" alt="screen shot 2015-08-05 at 13 19 39" src="https://cloud.githubusercontent.com/assets/5369193/9079492/d91714e6-3b74-11e5-9b83-5c6c62a7b06d.png">
PHP Fatal error:  Call to undefined method Magento\Catalog\Model\Resource\Product\Interceptor::getWriteConnection() in /private/var/www/magento2/demo_source/app/code/Magento/SampleData/Module/Catalog/Setup/Product/Gallery.php on line 144

**Comment by mazhalai** [comment] 2015-08-05 21:34
This is a duplicate of 1610. Please use the master branch and not the develop branch.

**Comment by vpelipenko** [comment] 2015-08-06 10:50
Closed as duplicate.

**Closed by vpelipenko** 2015-08-06 10:50 UTC
Labels: bug, MX
