### ISSUE TITLE
M2.1 Marketing >> Reviews >> New Review - Sorting & Filters not functioning.

### ISSUE THREAD

**Issue by praful-rajput** [magento/magento2#5391] opened 2016-07-01 05:53 UTC
## Steps to reproduce
1. Install Magento from "Full Release with Sample Data (ZIP with sample data)" from official page.
2. Logged into admin panel
3. Go to Marketing >> Reviews 
4. Click on "New Review" button.
5. It's opening product list grid to select and review it.
6. Grid sorting & Filtering is not working. 
## Expected result
1. Sorting & Filter should be work over there.
## Actual result

1.Sorting & Filtering is not working.

**Comment by pboisvert** [comment] 2016-07-01 17:56
Not able to reproduce this issue on 2.1 build. 

Screenshot of Marketing > Reviews with default sort on created
![reviews-original](https://cloud.githubusercontent.com/assets/5807369/16529851/f858598c-3f79-11e6-8f9f-54a1a918459b.png)

Screenshot of Marketing > Reviews with sort by Nickname (shows different order--now alphabetical)
![review-sorted-nickname](https://cloud.githubusercontent.com/assets/5807369/16529859/00f195cc-3f7a-11e6-82dd-38287707d61a.png)

Screenshot of Marketing > Reviews using Filter with keyword on Reviews column
![reviews-filtered](https://cloud.githubusercontent.com/assets/5807369/16529862/0653fef6-3f7a-11e6-8181-ccef106e2894.png)

Was this a clean install or an upgrade from previous version? Any other info to provide to help track down the issue?

**Comment by praful-rajput** [comment] 2016-07-02 11:02
It was clean install.

Please do not hesitate to reach out with any additional questions or
concerns that you might have.

_Regards,_

_Praful Rajput_

**Comment by andimov** [comment] 2016-08-10 07:37
@vasuscoin 
Thank you for reporting!
I have reproduced it and created an internal ticket for this issue - MAGETWO-56742 and linked it to this one.

**Comment by slavvka** [comment] 2016-09-19 10:49
The fix has been fixed in 2.1 and will be released as a part of future path releases

**Closed as completed by slavvka** 2016-09-19 10:49 UTC
Labels: Issue: Ready for Work, bug report

**Comment by Ctucker9233** [comment] 2016-09-27 00:06
@slavvka If we need this fix now, where could we find it?

**Comment by slavvka** [comment] 2016-09-27 09:02
Please see b80bd55

**Comment by slavvka** [comment] 2016-09-27 09:09
@Ctucker9233, try to use the patch:

``` diff
Index: app/code/Magento/Catalog/Block/Adminhtml/Product/Grid.php
===================================================================
diff -u -N -r2d368d0134597257ef5697a4bcbb7f69f2aebed8 -rb80bd55e96f26b745f878169b7ab20af1a0a2a8c
--- app/code/Magento/Catalog/Block/Adminhtml/Product/Grid.php   (.../Grid.php)  (revision 2d368d0134597257ef5697a4bcbb7f69f2aebed8)
+++ app/code/Magento/Catalog/Block/Adminhtml/Product/Grid.php   (.../Grid.php)  (revision b80bd55e96f26b745f878169b7ab20af1a0a2a8c)
@@ -114,8 +114,6 @@
      */
     protected function _prepareCollection()
     {
-        parent::_prepareCollection();
-
         $store = $this->_getStore();
         $collection = $this->_productFactory->create()->getCollection()->addAttributeToSelect(
             'sku'
@@ -184,6 +182,9 @@
         $this->setCollection($collection);

         $this->getCollection()->addWebsiteNamesToResult();
+
+        parent::_prepareCollection();
+
         return $this;
     }
```

**Comment by Ctucker9233** [comment] 2016-10-11 16:23
@slavvka Forgive my noob question, but how do I use this patch? I am not using composer to update off of the github repo. Can I simply manually add the changes to the files?

**Comment by slavvka** [comment] 2016-10-12 15:14
@Ctucker9233 yes you can
