### ISSUE TITLE
main.CRITICAL: Exception: Warning: Use of undefined constant SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_IETF_NPUBBYTES

### ISSUE THREAD

**Issue by stephenstephen** [magento/magento2#36547] opened 2022-11-29 08:48 UTC
### Preconditions and environment

- Magento 2.4.5-p1
- Php 7.4.3
- Ubuntu Linux apache Xampp
- Sodium installed and enabled 

![Capture d’écran du 2022-11-29 11-30-30](https://user-images.githubusercontent.com/34239158/204481151-ede08697-d3b4-4418-ab5a-84b095084e11.png)

### Steps to reproduce

Error when execute /pub

![Capture d’écran du 2022-11-29 11-37-39](https://user-images.githubusercontent.com/34239158/204480960-9a4448de-e528-4435-bdf8-eaf1bad93ec3.png)

### Expected result

Default Pages and Admin Panel should display

### Actual result

[2022-11-29T04:42:15.775058+00:00] main.CRITICAL: Exception: Warning: Use of undefined constant SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_IETF_NPUBBYTES - assumed 'SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_IETF_NPUBBYTES' (this will throw an Error in a future version of PHP) in /opt/lampp/htdocs/edenred/vendor/magento/framework/Encryption/Adapter/SodiumChachaIetf.php on line 59 in /opt/lampp/htdocs/edenred/vendor/magento/framework/App/ErrorHandler.php:62

![image](https://user-images.githubusercontent.com/34239158/204481450-e1aa833f-5bcc-4bd9-8487-a661b4896e40.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by devchris79** [comment] 2022-11-29 14:30
You need PHP 8.1 for Magento 2.4.5:
https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html

**Comment by stephenstephen** [comment] 2022-11-29 15:10
@devchris79 
I went through php8.1 but the problem persists

![Capture d’écran du 2022-11-29 18-08-00](https://user-images.githubusercontent.com/34239158/204566202-e52a2d16-9ba1-4356-a8b3-e3eeca65ebd0.png)

![Capture d’écran du 2022-11-29 18-07-38](https://user-images.githubusercontent.com/34239158/204566241-90382990-ba71-44d0-821f-b6156606cfc5.png)

**Comment by engcom-November** [comment] 2022-11-29 17:58
Hi @stephenstephen ,
Thank you for reporting and collaboration. Verified the behavior by installing Magento 2.4.5-p1 project-community-edition and the issue is not reproducible with PHP 8.1. As per Magento [system requirements](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html), compatible/supported php version for magento 2.4.5-p1 is 8.1 and Adobe commerce requires ext-sodium mandatory php extension which is included in Magento devdocs.
With active PHP 8.1 version and sodium enabled, this issue is not reproducible
![image](https://user-images.githubusercontent.com/60198231/204606817-974b4215-6649-4100-a148-2d46b8cbe702.png)
![image](https://user-images.githubusercontent.com/60198231/204606891-443f067c-280c-4683-9453-23ce7895f1fa.png)
Kindly recheck the issue again on Magento instance setup as per system requirements and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by ihor-sviziev** [comment] 2022-12-08 11:37
@stephenstephen pls check the php version that run on the web server - it might be the case when you have different PHP versions / PHP modules enabled for cli and for web.
the easiest way - add `phpinfo();` to the very top of the /pub/index.php file

**Comment by engcom-November** [comment] 2022-12-13 12:17
Hi @stephenstephen ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-12-13 12:17 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
