### ISSUE TITLE
Unable to uninstall Authorizenet

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#26193] opened 2019-12-27 12:04 UTC
More malware unable to be removed.

### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Install Magento 2.3.3
2. Try to uninstall Authorizenet modules
3. Go to checkout

### Expected result (*)

Able to uninstall Authorizenet.

### Actual result (*)

Exception #0 (ReflectionException): Class Magento\Authorizenet\Model\Directpost does not exist

**Comment by engcom-Hotel** [comment] 2020-01-13 12:54
Hello @Zyles 
I am not able to reproduce this issue on a fresh Magento 2.4-develop.

**Testing scenario:**

1. Install Magento 2.4-develop
2. Disable Authorizenet modules
![image](https://user-images.githubusercontent.com/51681618/72257250-d0962200-3613-11ea-9dbf-66ab639041bf.png)
3. Go to checkout

**Result:**
I was able to place order:
![image](https://user-images.githubusercontent.com/51681618/72257227-c5db8d00-3613-11ea-9422-47ef6c282ac6.png)

So i have to close this issue as not reproducible on the Magento 2.4-develop(i can confirm only issues that reproducible on the 2.4-develop branch).

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Hotel** 2020-01-13 12:54 UTC
Labels: Issue: Format is valid

**Comment by Zyles** [comment] 2020-01-13 13:01
Disable != Uninstall

**Comment by engcom-Hotel** [comment] 2020-01-13 13:12
@Zyles 
i have deleted modules after disable and all works as expected:
![image](https://user-images.githubusercontent.com/51681618/72258551-0b4d8980-3617-11ea-934d-de20cc0bb089.png)

![image](https://user-images.githubusercontent.com/51681618/72258528-f96be680-3616-11ea-9a48-2e6760f4f708.png)
