### ISSUE TITLE
Unable to checkout with braintree in multishipping with disabled vault for card payments.

### ISSUE THREAD

**Issue by bosskar231** [magento/magento2#37615] opened 2023-06-14 19:17 UTC
### Summary

**Preconditions and environment**
Upon upgrading our production site from M2.4.3-p2 to M2.4.6 we discovered customers were unable to checkout multishipping via Credit Card using the Braintree Payments extension V4.5.0 bundled in to M2.4.6 The cause was found to be the Enable Vault for Card Payments disabled on the Braintree.

**Steps to reproduce**
Fresh Install of M2.4.6 in environment as above
Login to backend

Nav to Admin>Stores>Configure>Sales>Payment Methods
Select Merchant Country as United States and Save Config
Configure Braintree Payments (by GENE Commerce v4.5.0)
Enter known valid sandbox credentials for Merchant ID, Public Key, Private Key and Validate Credentials
Disable Card Payments = Yes and Save Config
Flush Magento Cache

On Frontend, successfully Sign In using Demo Customer Access credentials
Add any product to cart
Proceed to Checkout with multiple addresses
Shipping Method select Fixed Flat Rate
Payment Method select Credit Card
Enter Card # 4111 1111 1111 1111 Expiration: 12/2023 Security Code: 123
Click blue "Place Order" button on review order page
Observe "spinner" appears for a moment and then automatically redirects to
Payment page with the error as Order Page Error.

Expected result:
Order should placed successfully

Actual result:
Getting error like "Order place error"

### Examples

In previous Magento version 2.4.3-p1 Customer can place an multishipping order with the disabled vault for card payments option in braintree. But in latest 2.4.6 version . It seems they make it mandatory to enable the value for card payments option to make multishipping checkout.

### Proposed solution

With the new approach to enable the vault for card payments for multishipping it also affects the normal checkout flow .Braintree is storing credit card details for normal checkout and placing an order in admin. Is it possible to revert back or could you please provide a patch.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-06-15 11:59
Hi @bosskar231 ,

Thanks for contribution and collaboration !
Verified the issue in 2.4.6 magento instance and the issue is reproducible in 2.4.6 magento instance,Hence we are confirming the issue.

Preconditions:
magento version 2.4.6
PHP 8.1

Steps to reproduce:

- [ ] Install magento instance
- [ ] Setup Braintree Payment configuration in Backend 
- [ ] Disable Card Payments = Yes and Save Config
- [ ] Checkout through Multi-shipping  with credit card payment

Kindly refer the screenshots:
**2.4.3-p1**
<img width="1505" alt="Screenshot 2023-06-15 at 5 14 56 PM" src="https://github.com/magento/magento2/assets/60198592/9865a91c-177d-4ef6-b642-f05c000eec8d">
2.4.6 instance
<img width="1505" alt="Screenshot 2023-06-15 at 3 56 09 PM" src="https://github.com/magento/magento2/assets/60198592/42e778dc-4fce-4412-8acd-9f127804fedb">
<img width="1505" alt="Screenshot 2023-06-15 at 5 27 31 PM" src="https://github.com/magento/magento2/assets/60198592/435631f8-6b18-4045-b77f-deb63c393e8e">

Magento version 2.4.3-p1 Customer can place multi-shipping order with the disabled vault for card payments option in Braintree. But in latest 2.4.6 version . It seems  mandatory to enable the value for card payments option to make multi-shipping checkout.

**Comment by bosskar231** [comment] 2023-06-26 08:46
Hi,
Any update on this.

**Comment by bosskar231** [comment] 2023-08-10 06:34
Hi,
Any update on this. Can we get a patch.

**Comment by engcom-Bravo** [comment] 2024-12-24 04:37
Hi @bosskar231,

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-12-24 04:37 UTC
Labels: Issue: Confirmed, Component: Braintree, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Admin UI, Reported on 2.4.6
