### ISSUE TITLE
Region select doesn't apply default selected region id

### ISSUE THREAD

**Issue by HirokazuNishi** [magento/magento2#35247] opened 2022-03-30 06:50 UTC
On Magento2.4.4 or github latest version has new region-updater.js, but this script has serious bug. Region dropdown cannot set region by region_id on customer address edit page.

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Directory/view/frontend/web/js/region-updater.js
Line 112 compares defaultRegion and key but these 2 values type are not same.

### Preconditions (*)

1. Install vanilla Magento2.4.4 (or clone git repo)
2. Create customer account from frontend
3. Add customer address from frontend

### Steps to reproduce (*)

1. Log in to mypage
2. Access address book page
3. Show registered address edit page
4. Region dropdown isn't selected. 

### Expected result (*)

1. Region dropdown should be selected by region id data of customer address data.

### Actual result (*)

1. Region dropdown shows "Please select region, state or province"

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-03-30 11:20
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue with provided steps:
![image](https://user-images.githubusercontent.com/60198231/160822871-418ef7aa-2d69-418c-b1ec-2a2311d00aef.png)

![image](https://user-images.githubusercontent.com/60198231/160822825-4a5057e4-90cc-4dc9-92d7-8c4a39b9e6fa.png)
@HirokazuNishi kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any / address details used if the issue is still reproducible.
Thank you.

**Comment by HirokazuNishi** [comment] 2022-03-31 00:08
@engcom-November I could reproduce on 2.4.4 from composer install. Please see attached sc.

![mismatch-variable-type](https://user-images.githubusercontent.com/124136/160950624-71d9645c-95f4-41e4-9912-50f122f84771.png)
![region-not-selected](https://user-images.githubusercontent.com/124136/160950628-4a51fc29-347e-4743-98c4-8ecb7b550a3a.png)

**Comment by engcom-November** [comment] 2022-03-31 09:53
Hi @HirokazuNishi ,
Its recommended to verify issues on Magento 2.4-develop instance as it is having latest code base and upcoming 2.4.x release. kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any / address details used if the issue is still reproducible.
Thank you.

**Comment by hostep** [comment] 2022-03-31 10:21
@engcom-November: we've seen in the past that code for a freshly released Magento version is only merged in 2.4-develop a couple of weeks after the release, which means that the code in 2.4-develop currently is missing a bunch of code that's in 2.4.4.

So if people are reporting problems with Magento 2.4.4 in the next coming days or weeks, it's probably best not to test on 2.4-develop itself, because you can't be sure yet that the code from 2.4.4 is already merged in it.

@sdzhepa @sidolov: maybe you guys can explain this a bit better to the engcom squad people, how to handle such issue reports in the next couple of weeks until 2.4.4 code is merged in 2.4-develop?

**Comment by HirokazuNishi** [comment] 2022-04-04 05:59
@engcom-November @hostep: I checked some codes on my local env, and found some localization module caused this issue. Now it could fix on our side. Thanks and sorry to bother with you. Please close this ticket.

**Comment by engcom-November** [comment] 2022-04-06 07:45
Thanks for the update @HirokazuNishi , We are closing the issue.

**Closed as completed by engcom-November** 2022-04-06 07:45 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
