### ISSUE TITLE
Setup page is redireting  to /pub/setup instead of setup.

### ISSUE THREAD

**Issue by abhi-dev91** [magento/magento2#36694] opened 2023-01-03 04:44 UTC
### Preconditions and environment

- Magento version 2.4+
- Anything else that would help a developer reproduce the bug

While using Apache Web Server with mod_php, when we try to access the magento2 home page, it is redirecting to /pub/setup instead of /setup.

In this setup no need to do magento setup config or magento install using bin/magento setup install command, as this is occuring with redirection of setup page.

Note:- With Nginx, this configuration is working fine.

### Steps to reproduce

To reproduce this issue - 
One can download and run composer install in the root directory of Magento, and put that directory in DocumentRoot of apache.

### Expected result

One should get redirected to $URI/setup instead of $URI/pub/setup

### Actual result

One is getting redirected to $URI/pub/setup and facing a Error message as TOO MANY REDIRECTS.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-01-10 05:36
Hi @abhi-dev91 ,

We are trying to reproduce the issue in 2.4-develop instance,But we are not able to reproduce.
Magento version 2.4-develop
PHP 8.1
We installed Apache php server with mod_php and we are trying to access to Magento 2 home page the page is redirecting to pub/setup instead of setup.We are getting expected result.this issue is not reproducible.

Let us know if we missing anything!!!

Thanks!!!

**Comment by abhi-dev91** [comment] 2023-01-10 05:49
Hi @engcom-Dash,
Actually this issue I am facing is with magento version 2.4.3, could you please try reproducing it once. You can use this dockerfile to build the image.

`FROM php:7.4-apache
USER root
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions && install-php-extensions bcmath gd intl pdo_mysql soap sockets xsl zip && \
    install-php-extensions @composer
COPY . /var/www/html/
WORKDIR /var/www/html/
RUN composer install
RUN chown -R www-data:www-data /var/www/html/
RUN a2enmod rewrite
`

**Comment by abhi-dev91** [comment] 2023-01-10 06:10
Result - 
<img width="941" alt="image" src="https://user-images.githubusercontent.com/58635182/211474655-54f9c399-5f84-4b65-aca1-72b5068afcc3.png">


Expected Result - 

<img width="359" alt="image" src="https://user-images.githubusercontent.com/58635182/211474520-0e481eae-b55e-483b-866d-11c53c641fc1.png">

**Comment by engcom-Dash** [comment] 2023-01-11 15:10
@magneto give me 2.4-develop instance

**Comment by hostep** [comment] 2023-01-11 21:34
Magento removed the ability to use the web setup in version 2.4.0 and higher. See [the release notes for 2.4.0](https://experienceleague.adobe.com/docs/commerce-operations/release/notes/magento-open-source/2-4-0.html), this section:

> Deprecation and removal of the Web Set Up Wizard. You must use the command line to install or upgrade 2.4.0. See [Install Magento](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/advanced.html?lang=en).

Does that answer your question @abhi-dev91?

**Comment by engcom-Dash** [comment] 2023-01-12 04:05
Hi @abhi-dev91 ,

We are trying to reproduce the issue in 2.4-develop instance,We are not able to reproduce the issue...Kindly provide more information ...Kindly give some information in Steps to reproduce.

Thanks!!!

**Comment by abhi-dev91** [comment] 2023-01-14 11:44
To reproduce this issue just built the image using the above dockerfile and commands.

After building the image run the image and expose it. After exposing when you try to access this website it will redirect you to a page /pub/setup which doesn't exist in real.

Ideally it is trying to redirect it to /setup what it is not redirecting to that. (In nginx's case it is redirecting to /setup page)

**Comment by abhi-dev91** [comment] 2023-01-14 11:46
> Magento removed the ability to use the web setup in version 2.4.0 and higher. See [the release notes for 2.4.0](https://experienceleague.adobe.com/docs/commerce-operations/release/notes/magento-open-source/2-4-0.html#infrastructure-improvements), this section:
> 
> > Deprecation and removal of the Web Set Up Wizard. You must use the command line to install or upgrade 2.4.0. See [Install Magento](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/advanced.html?lang=en).
> 
> Does that answer your question @abhi-dev91?

Yes, hostep, but I don't want to do setup from UI. I just wanted to access that page only. So that once anyone access the website it gives them a page which asks for setup instead of infinite redirect

**Comment by engcom-Dash** [comment] 2023-02-10 14:21
Hi @abhi-dev91 ,

Thanks for you collaboration....

Request you to please let me know the steps you are following along with what is the use case you are trying to achieve here for my batter understanding your expectations.

Regards

**Comment by engcom-Dash** [comment] 2023-02-22 08:08
Hi @abhi-dev91 ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2023-02-22 08:08 UTC
Labels: Issue: needs update, Reported on 2.4.x
