### ISSUE TITLE
Magento Integration not activate

### ISSUE THREAD

**Issue by devefectus** [magento/magento2#35784] opened 2022-07-19 17:30 UTC
### Preconditions and environment

![image](https://user-images.githubusercontent.com/109619605/179812507-3233b717-673e-49e0-b1d3-d0271635132b.png)

-v Magento versão 2.4.4

### Steps to reproduce

Magento integration page

### Expected result

I can't activate the integration in my magento store

### Actual result

Integration 'soap api' has been submitted for activation.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2022-07-20 06:58
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-07-20 09:17
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-08-10 10:11
Hi @devefectus ,

We are trying to reproduce the issue but we are not able to reproduce....

For your reference i attached the screenshots below:
![Screenshot from 2022-08-09 19-23-42](https://user-images.githubusercontent.com/60198592/183875993-8812cfe9-0544-42df-8a78-29543330f485.png)


When we trying to activate two or more integrations it will be activate and we are not getting exact results.

Let us know if we are miss anything...

Thanks!!

**Comment by engcom-Dash** [comment] 2022-08-24 07:47
Hi @devefectus 
We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2022-08-24 07:47 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Area: Admin UI
