### ISSUE TITLE
There is no ability to pass store ID during getting CMS page/block by identity.

### ISSUE THREAD

**Issue by ytorbyk** [magento/magento2#6570] opened 2016-09-11 16:16 UTC
### Preconditions
1. There could be more then one CMS block/page with the same identity (for each store view).
### Expected result
1. There must be ability to get CMS block/page by identity for specific store view.
### Actual result

`\Magento\Cms\Api\PageRepositoryInterface::getById($pageId)`
`\Magento\Cms\Api\BlockRepositoryInterface::getById($blockId)`
1. Both methods return the first found item in DB with passed identity.

**Comment by davidalger** [comment] 2016-09-12 15:19
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by ytorbyk** [comment] 2016-09-12 15:25
@davidalger Magento 2 doesn't provide ability to get CMS block/page. Isn't it a bug?

**Comment by ytorbyk** [comment] 2016-09-13 08:01
Sorry, my bad. Poor explanation  

### Preconditions

Magento 2.1.1

### Steps to reproduce
1. Create at least two store views
2. Create CMS block for each of the store views with the same identity
3. Go to template/block (no matter which one)
4. Call \Magento\Cms\Api\BlockRepositoryInterface::getById($blockId) for retrieving CMS block

### Expected result
1. You have ability to get CMS block by identity for specific store ID

### Actual result
1. The interface method requires only identity and no ability to pass store ID
2. The method returns the first CMS block found in DB

**Comment by SerhiyShkolyarenko** [comment] 2016-09-13 08:22
reopened issue due to updated steps.

**Comment by veloraven** [comment] 2017-06-30 05:54
I'm closing this issue as it was fixed in #7218.
If you can still reproduce this issue, please create a new GitHub issue report.

**Comment by convenient** [comment] 2017-07-26 19:12
@veloraven this issue should not have been close IMO.

- this issue says you cannot load a specific cms block by identifier, when that identifier is shared between multiple store views. 
- #7218 affected **saving** of cms blocks allowing you greater control over the `store_id`
- Pending PR #7417 should fix this issue, and allow you to specify both a `store_id` and `identifier` combination to allow for granular **loading** of cms blocks.

Just for clarity 👍

**Comment by magento-team** [comment] 2017-08-01 01:09
Internal ticket to track issue progress: MAGETWO-66748

**Comment by ytorbyk** [comment] 2017-08-01 07:17
Thank you!
Can you please reopen this ticker as well?

**Comment by okorshenko** [comment] 2017-08-02 22:47
Hi @ytorbyk closing this issue as a duplicate of https://github.com/magento/magento2/issues/10414

**Closed as completed by okorshenko** 2017-08-02 22:47 UTC
Labels: Issue: Ready for Work, bug report, Component: Cms
