### ISSUE TITLE
Magento CLI 2.4.3-p3 Rest API Self Access denied using Customer Token

### ISSUE THREAD

**Issue by widianapw** [magento/magento2#38475] opened 2024-02-27 09:03 UTC
### Preconditions and environment

- Magento CLI 2.4.3-p3

### Steps to reproduce

1. Login customer by using http://example.test/rest/V1/integration/customer/token
2. Get the token from response no 1
3. Get current customer by using http://example.test/rest/V1/customers/me and with header Bearer token <token_from_no_2>

### Expected result

Should response the customer data

### Actual result

the response is:
```
{
    "message": "The consumer isn't authorized to access %resources.",
    "parameters": {
        "resources": "self"
    },
```

### Additional information

Im using Magento CLI 2.4.3-p3, 
already follow the docs instruction but its not working
docs: https://developer.adobe.com/commerce/webapi/get-started/authentication/gs-authentication-token/

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-02-28 09:37
Hi @widianapw,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Login customer by using http://example.test/rest/V1/integration/customer/token
- Get the token from response no 1
- Get current customer by using http://example.test/rest/V1/customers/me and with header Bearer token <token_from_no_2>

![Screenshot from 2024-02-28 11-55-31](https://github.com/magento/magento2/assets/51680745/9808ee38-9ee2-4ce3-9d1b-7a798a7b7a76)


We are able to get the customer response.

Kindly recheck the issue in Latest Magento 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-03-15 04:01
Hi @widianapw,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-03-15 04:01 UTC
Labels: Issue: needs update, Reported on 2.4.3-p3
