### ISSUE TITLE
Magento - Catalog Price Rules, Filter by SKU issues

### ISSUE THREAD

**Issue by claridgicus** [magento/magento2#7093] opened 2016-10-19 14:37 UTC
### Preconditions

1. 2.1.2
2. PHP 5.6
### Steps to reproduce

Created a catalog price rule in Magento and applied it to a specific product via SKU.

Please see attached screenshots.

Expected Result:
- Catalog price rule to be applied to selected product(s)
### Actual result

- Catalog price rule is not being applied to specified product(s)
- cant unselect or add more skus to existing filter

**Comment by veloraven** [comment] 2016-10-20 09:07
@claridgeandco thank you for your report.
Unfortunately I do not see your screenshot.
But your issue seems to be a duplicate of #6985

**Comment by Tjmstudios** [comment] 2016-10-23 22:22
@veloraven updating @claridgeandco issue with images.

![screen shot 2016-10-24 at 9 21 01 am](https://cloud.githubusercontent.com/assets/11372070/19629945/5ed7160c-99cb-11e6-956f-e8f4820fd5b4.png)
![screen shot 2016-10-24 at 9 21 31 am](https://cloud.githubusercontent.com/assets/11372070/19629944/5ed382f8-99cb-11e6-940e-c761f8d919fd.png)
![20 catalog price rule promotions marketing magento admin](https://cloud.githubusercontent.com/assets/11372070/19629943/5ed3350a-99cb-11e6-93be-67d5ea9e0c56.png)

**Comment by katmoon** [comment] 2016-11-01 14:12
Hi @claridgeandco 

Please try to set rule to 'SKU _is one of_ james test art, James Test Art'.
It looks like the problem is that the rule definition is not intuitive.

Thanks,
Kateryna.

**Comment by claridgicus** [comment] 2016-11-02 00:40
Hey Kat,

We tried this and its still not working,

We would also like to report (could be related) that this is affecting coupons without any preconditions.

**Comment by olysenko** [comment] 2016-11-24 11:13
Hi, @claridgeandco , I cannot reproduce this issue on fresh install Magento  ver. 2.1.2 in case if "SKU is one of james test art, James Test Art" selected as the conditions for the rule. Catalog rule with condition "SKU is one of" also works for several products. Of course reindex after rule was applied should be executed

**Comment by olysenko** [comment] 2016-11-24 11:31
When click on Open chooser the matched  products will be checkboxed. 
![conditions](https://cloud.githubusercontent.com/assets/8058039/20597052/2d4a2a06-b24a-11e6-8cdd-cc28c2c0da3a.png)

**Comment by vzabaznov** [comment] 2016-12-13 09:21
Hi @claridgeandco , closed as we don't receive update more than 2 week, feel free to write here/reopen or to open new issue

**Closed as completed by vzabaznov** 2016-12-13 09:21 UTC
Labels: bug report, Progress: needs update, Component: Tax

**Comment by jmtakahashi** [comment] 2017-02-21 03:25
@vzabaznov I have this same issue, when using the chooser, and it looks like this is the same issue #8215 and it looks like issue #7723 and fix #8246 is related as well.  

In issue #8215 a contributor is quoted as saying "As I know in magento you have no ability to create Catalog rule based on list of SKU. You can create rule only based Attribute Set or Category."  However, users can create Catalog Price Rules based on a selection of individual sku's.  It seems that #8246 fixed the issue of being able to select multiple items and then create an array, but no one responded to say if this fixed the particular issue of #8215 .  I don't know why @claridgeandco did not respond.  

On my installation of Magento 2.1.2 I can open the selector and select items.  However, after I save the rule, when I RE-OPEN the selector for SKU's, the previously selected items do not show as "selected" (with a checkbox), even when using the left filter and setting to "Yes".

Thanks, just trying to help clear this issue up.
