### ISSUE TITLE
Magento 2.1.2 cannot make Bundle Product for Downloadable Product

### ISSUE THREAD

**Issue by jurpro** [magento/magento2#7425] opened 2016-11-14 15:13 UTC
Hello. I'm using Magento CE 2.1.2 having trouble to make a BUNDLE PRODUCT for download product + simple product.

### Preconditions
1.  I need to make a simple product with bonus downloadable product. Such as CD + Bonus digital download.

### Steps to reproduce
1. Make a simple product. - Not visible indivually
2. Make a downloadable product  - Not visible indivually
3. Make a Bundle Product - Visible for catalog and search. 
4. on Bundle Product : Add Simple product as main product. 
5. on Bundle Product : Add downloadable product as a bonus.

### Expected result
1. A product with bundle simple product + Bonus download digital.

### Actual result
1. Only Simple products and Virtual products can be detected to make a BUNDLE product. 
2. Cannot add Downloadable product because cannot detected.
3. Bundle product for simple product and virtual product is success. 
4. For all downloadable product cannot detected so cannot make a bundle for downloadable product.
5. For Magento 2.1.1 I was successfully make a bundle product for simple product + Bonus downloadable product. But on Magento 2.1.2 cannot.

**Comment by olysenko** [comment] 2016-12-08 17:04
Hi, thank you for your report. I saw in the history of commits [Magento/Bundle/etc/product_types.xml](https://github.com/magento/magento2/blob/2.1/app/code/Magento/Bundle/etc/product_types.xml)  and notice that in allowedSelectionTypes node existed only simple and virtual  product types from the beginning of Magento2.  It means that downloadable products were not available for bundle option selection by default.
In case if I add the node 
<type name="downloadable" />
downloadable products became available for bundle selection. May be in Magento 2.1.1 you have this option. Closed as not a bug, but default behavior

**Closed as completed by olysenko** 2016-12-08 17:04 UTC
Labels: bug report, Component: Catalog

**Comment by jurpro** [comment] 2016-12-09 14:01
Hello @olysenko Could you please add download product for bundle option for next release? I really need this. Not a separate product
Thanks
