### ISSUE TITLE
Improve CLS on PDP 2.4.4

### ISSUE THREAD

**Issue by profRomanovski** [magento/magento2#35410] opened 2022-05-02 16:16 UTC
### Preconditions (*)
1. Magento 2.4.4
2. With or without Varnish

### Steps to reproduce (*)
1. Go to PDP
2. Run the Lighthouse test or go to https://pagespeed.web.dev/ and paste the URL for mobile 
3. Check CLS value

### Expected result (*)

1. CLS should be less than 0.1
2. After fixing the image shouldn't blink during page loading as in this fix:
https://github.com/magento/magento2/pull/33265
### Actual result (*)

1. CLS is more than 0.2
![image](https://user-images.githubusercontent.com/89356724/166270454-25a2607e-3a43-4883-b2b3-cc5bc188798f.png)

---
- [ ] Severity: **S4** _- Affects aesthetics, professional look, and feel, “quality” or “usability”._

**Comment by profRomanovski** [comment] 2022-05-02 16:17
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-05-04 09:54
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-05-04 10:29
Dear @profRomanovski,

Thanks for the contribution!

We have tried to reproduce the issue on Magento 2.4-develop branch and the issue is reproducible. We have also gone through the link mentioned about [the CLS](https://web.dev/cls/).

According to the article, the CLS value should not go beyond `0.1`, but in our case, it is `0.432`. Please have a look at the below screenshot for reference:
![image](https://user-images.githubusercontent.com/51681618/166664492-280bb01d-d482-45bf-837d-f9687b79cab6.png)

We have also compared it with the [PR fix](https://github.com/magento/magento2/pull/33265), mentioned in the main description and their CLS value is `0.038` which is as per standard. Please have a look at the below screenshot:

![image](https://user-images.githubusercontent.com/51681618/166664755-5e66a587-6d2d-481c-8b3d-1945a84fb232.png)

Hence confirming the issue.

Thanks

**Comment by profRomanovski** [comment] 2022-05-05 18:22
@magento give me 2.4-develop instance

**Comment by Pranav-242** [comment] 2022-05-31 06:00
@magento i;m working on it.

**Comment by profRomanovski** [comment] 2022-06-29 19:10
How it's going on?

**Comment by engcom-Hotel** [comment] 2022-06-30 10:16
@Pranav-242 Can you please provide us the Community PR link if you are working on this issue. Else, you may link the PR ticket to this issue.

Thanks in advance!

**Comment by profRomanovski** [comment] 2022-07-13 16:28
Have you got a solution for this issue?

**Comment by ihor-sviziev** [comment] 2023-10-23 10:43
The issue is fixed https://github.com/magento/magento2/pull/33265 (merged in https://github.com/magento/magento2/commit/b9f57bda3c44f4320f966a67c128075ae830ca42)

**Closed as completed by ihor-sviziev** 2023-10-23 10:43 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Severity: S3, Progress: done, Issue: ready for confirmation, Area: UI Framework, Reported on 2.4.4
