### ISSUE TITLE
No UpgradeScheme.php update for module-sales for 2.1.0

### ISSUE THREAD

**Issue by alexgoodey** [magento/magento2#5314] opened 2016-06-28 13:38 UTC
In the Magento 2.1.0 release there is an update to vendor/magento/module-sales/Setup/InstallSchema.php where the column base_grand_total is added to the sales_invoice_grid table. However there is no equivalent update to the file vendor/magento/module-sales/Setup/UpgradeSchema.php meaning that if you upgrade from a previous version (2.0.7 for example) the column is not added to the table resulting in errors in the admin interface.

**Comment by NadiyaS** [comment] 2016-07-01 10:52
Hi @alexgoodey ,
thanks for reporting this issue. It is already being tracked by MAGETWO-54787 ticket and fix will be delivered soon.
This issue will be closed as duplicate of #4785.

**Closed as completed by NadiyaS** 2016-07-01 10:52 UTC
