### ISSUE TITLE
Inconsistent location for plugins

### ISSUE THREAD

**Issue by ashsmith** [magento/magento2#2291] opened 2015-11-07 22:07 UTC
I have noticed in `app/code/Magento/CatalogUrlRewrite` the location where Plugins are kept is inconsistent between Blocks & Models.

So in the code below (from `app/code/Magento/CatalogUrlRewrite/etc/adminhtml/di.xml`) shows Plugins for Models stored in the Model directory, but then Blocks and Controller Plugins are kept in a Plugins directory within the root of the module.

``` xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    ...
    <type name="Magento\UrlRewrite\Model\StorageInterface">
        <plugin name="storage_plugin" type="Magento\CatalogUrlRewrite\Model\Category\Plugin\Storage"/>
    </type>
    <type name="Magento\Catalog\Block\Adminhtml\Category\Tab\Attributes">
        <plugin name="category_form_url_key_plugin" type="Magento\CatalogUrlRewrite\Plugin\Catalog\Block\Adminhtml\Category\Tab\Attributes"/>
    </type>
    ...
    <type name="Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper">
        <plugin name="product_save_rewrites_history_plugin" type="Magento\CatalogUrlRewrite\Plugin\Catalog\Controller\Adminhtml\Product\Initialization\Helper"/>
    </type>
</config>
```

Is there a reason behind this? Was it intentional?

**Comment by fooman** [comment] 2015-11-08 05:23
Just to add to the list - there are also cases where model plugins are directly in the module directory 

    <type name="Magento\Catalog\Model\Product\Action">
        <plugin name="price_plugin" type="Magento\CatalogRule\Plugin\Model\Product\Action"/>
    </type>

**Comment by davidalger** [comment] 2015-11-09 02:44
This is an inconsistency in the core which needs to be addressed. The proper location per documentation is in `<module>/Plugin/`

> `plugin type:` The name of a plug-in’s class or its virtual type. Use the following schema when you specify this element: \Plugin.

source: http://devdocs.magento.com/guides/v2.0/extension-dev-guide/plugins.html#plugin-declare

**Comment by fooman** [comment] 2015-11-09 03:08
@davidalger the doc you linked to is not following its own guideline either

    <?php
    namespace My\Module\Model\Product;
    class Plugin

**Comment by davidalger** [comment] 2015-11-09 16:38
@fooman Thanks for pointing that out. Seems the docs need some updating then too! :)

cc: @xcomSteveJohnson

**Comment by vkholoshenko** [comment] 2016-01-06 15:14
Internal ticket: MAGETWO-47664

**Comment by magento-engcom-team** [comment] 2017-10-26 08:00
@ashsmith, thank you for your report.
We've created internal ticket(s) MAGETWO-47664 to track progress on the issue.

**Comment by magento-engcom-team** [comment] 2019-01-30 13:41
Hi @SikailoISM. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-02-11 00:46
Hi @rvovnenko. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by rvovnenko** [comment] 2019-02-11 00:47
* @magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-11 00:47
Hi @rvovnenko. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-11 00:47
Hi @rvovnenko, here is your [Magento instance](https://i-2291-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-2291-2-3-develop.instances.magento-community.engineering/admin](https://i-2291-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by okorshenko** [comment] 2019-02-11 04:05
Please use this convention: https://devdocs.magento.com/guides/v2.3/extension-dev-guide/plugins.html

**Comment by sdzhepa** [comment] 2019-03-04 20:10
Hello @rvovnenko 

Thank you for participating and collaboration.

I want to ask are you still working on this issue?
Just want to put this issue into the correct column on "Community Dashboard". Is it free for development or it is in progress now?

**Comment by rvovnenko** [comment] 2019-03-06 03:48
Hi @sdzhepa ,
I am not working on this one.
The fix provided by @StevenGuapaBV is good enough, I think it was not accepted because @StevenGuapaBV was pushing it directly to magento2 instead of his own git.
In any case please put it back to development.

**Comment by akolpakovgor** [comment] 2019-04-13 09:04
#cdkyiv2019

**Comment by magento-engcom-team** [comment] 2019-04-13 09:04
@akolpakovgor thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by phaelfp** [comment] 2019-09-15 00:09
#mm19br

**Comment by magento-engcom-team** [comment] 2019-09-15 00:09
@phaelfp thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by kkorushkin** [comment] 2019-09-19 14:20
This issue needs to be closed since it's has fixed not reproducible anymore

**Comment by sdzhepa** [comment] 2019-09-19 15:48
Hello @kkorushkin 

Thank you for the update and collaboration!
I am closing this issue

**Closed by sdzhepa** 2019-09-19 15:48 UTC
Labels: Event: mm19br, Issue: Clear Description, Issue: Confirmed, Issue: Format is not valid, Issue: Ready for Work, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, bug report, good first issue, help wanted
