### ISSUE TITLE
Catalog Rule Product Index is not reindexing after save - "update on save" mode set

### ISSUE THREAD

**Issue by lucas-santos-chaordic** [magento/magento2#5770] opened 2016-07-22 21:50 UTC
### Preconditions

After editing a catalog rule, the rule is never applied, even the index mode for all the indexes are set to update on save. All the other indexes are workin as spected.

We also tested using a docker with a very clean instalation of version 2.1 and had the same issue
1. Running on AWS 
2. PHP7
3. NGINX and PHP FPM
4. Using RDS
### Steps to reproduce

It is easy to reproduce.
1. Set the indexes to update on save mode 
2. Create a new catalog Rule
3. Save and apply the rule 
4. You are going to receive a message saying that a reindex is required.
5. Go to the index page and see that the message is Reindex Required for an index using the update on save mode
### Expected result

The index should be up to date (ready)
### Actual result

the index is outdated

**Comment by brendanmckeown** [comment] 2016-07-24 02:35
Also seeing this problem only with the "Catalog Rule Product" index, following the same steps above.

**Comment by lucas-santos-chaordic** [comment] 2016-07-25 13:33
Yes... It only happens on "Catalog Rule Product" index. The others are working properly....

**Comment by smoskaluk** [comment] 2017-06-22 10:45
@lucas-santos-chaordic Unfortunally, I was not able to reproduce this problem. Can you affirm that this issue is relevant for latest Magento 2 release?

**Comment by tycreate** [comment] 2017-07-07 16:13
Currently Having the same issue
@smoskaluk @lucas-santos-chaordic @brendanmckeown 
Any solutions?

**Comment by magento-engcom-team** [comment] 2017-09-22 16:24
@lucas-santos-chaordic, thank you for your report.
We've created internal ticket(s) MAGETWO-76051 to track progress on the issue.

**Comment by thiagolima-bm** [comment] 2017-10-20 11:41
I'm working on it #SQUASHTOBERFEST

**Comment by okorshenko** [comment] 2017-10-24 16:14
Hi @thiagolima-bm could you please accept the invite on the GitHub?

**Comment by thiagolima-bm** [comment] 2017-11-03 10:59
@okobchenko done :)

**Comment by thiagolima-bm** [comment] 2018-02-14 17:27
@kokoc to this issue this also applies https://github.com/magento/magento2/pull/11580#issuecomment-342506544 ?

**Comment by thiagolima-bm** [comment] 2018-02-14 17:32
Duplicated https://github.com/magento/magento2/pull/11580

**Comment by r-bielawski** [comment] 2018-03-24 11:17
#distributed-cd

**Comment by magento-engcom-team** [comment] 2018-03-24 11:18
@r-bielawski thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment] 2018-04-13 07:02
@lucas-santos-chaordic Unfortunately we have to close this ticket now, as this seems to be an intended behavior at the moment.
Please refer to this comment for more information: https://github.com/magento/magento2/pull/11580#issuecomment-342506544

Thank you for collaboration.

**Closed as completed by magento-engcom-team** 2018-04-13 07:02 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid

**Comment by somnath12** [comment] 2018-04-24 12:10
If anybody facing any issue regarding magento indexing you may contact

**Comment by somnath12** [comment] 2018-04-24 12:12
If anybody facing any issue regarding magento indexing you may contact testdevelopworld@gmail.com

**Comment by charles-tychons** [comment] 2019-10-18 07:29
In my case, verified the cron_schuedule table, where many of the cron jobs are still in **pending** status. 

So I just back up that table data and truncated. 

The issue resolved and reindex worked "update on save" mode.

Using Magento 2.2.x
