### ISSUE TITLE
Product video not display ver. 2.1.4

### ISSUE THREAD

**Issue by AgenturSchroeder** [magento/magento2#8882] opened 2017-03-14 16:43 UTC
Hi,

there is still a bug with the Magento2 product video.

**Preconditions**

    Create product in the backend of Magento 2.1.4.
    Set a video in the product.
    Save it, clear the cache and look at the frontend.

**Steps to reproduce**

Same like Preconditions
    
**Expected result**

    There should be a video in the product on the frontpage.

**Actual result**

    Only a thumbnail and a image is shown.

The shop use a custom theme but i dont think that this is the problem because
i can't see a video in the luma theme too.
There is the same issue on a fresh install.

**Comment by dmitriyprime** [comment] 2017-06-29 15:54
Hi, @Hopfrosch . It's a duplicate of https://github.com/magento/magento2/issues/6360 . Internal ticket MAGETWO-57995 was created to fix it.

**Comment by korostii** [comment] 2017-06-29 16:06
@dmitriyprime, you're kidding, right?

This is an acknowledged issue: #6360
It's even included in the latest release notes: http://devdocs.magento.com/guides/v2.2/release-notes/release-notes-2-2-prerelease1-CE.html#breaking-issues

**Comment by veloraven** [comment] 2017-06-30 06:05
I'm closing this issue as duplicate.
However I added mention of this issue to the internal ticket for ver. 2.1 - MAGETWO-58515

**Closed as completed by veloraven** 2017-06-30 06:05 UTC
Labels: bug report, Component: Catalog
