### ISSUE TITLE
magento 2.3.1 price not showing when configurable product out of stock 

### ISSUE THREAD

**Issue by web-pro** [magento/magento2#24292] opened 2019-08-26 11:17 UTC
magento: 2.3.1
I am using this code $block->getProductPrice($_product)  on list.phtml for price.
when configurable product in-stock then price is showing but not showing price for out-of-stock.

@magento-team

**Comment by sdzhepa** [comment] 2019-09-11 20:58
Hello @web-pro and @engcom-Charlie 

It seems this behavior has been discussed multiple times on GitHub, forums etc
And additionally has been discussed with Magento Product Managers/Owners and was confirmed it is not a bug but expected behavior, this requirement covered by internal test case.

Please see for more details https://github.com/magento/magento2/issues/16069

**Comment by engcom-Charlie** [comment] 2019-09-12 06:00
@sdzhepa thanks for contributing! 
So i close this issue.

**Closed as completed by engcom-Charlie** 2019-09-12 06:00 UTC
Labels: Issue: Format is not valid
