### ISSUE TITLE
Custome Backend Multiselect Attribute is not saving

### ISSUE THREAD

**Issue by stepzerosolutions** [magento/magento2#4545] opened 2016-05-18 00:04 UTC
## Steps to reproduce
1. Create InstallData in module with following,

``` php
                $eavSetup->addAttribute(
                    \Magento\Catalog\Model\Product::ENTITY,
                    'groupcatalogavailability',
                    [
                        'type' => 'varchar',
                        'label' => 'Customer Group Visibility',
                        'input' => 'multiselect',
                        'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
                        'backend' => 'Stepzerosolutions\Groupcatalogvisibility\Model\Product\Attribute\Backend\Groupcatalogvisibility',
                        'input_renderer' => 'Stepzerosolutions\Groupcatalogvisibility\Block\Adminhtml\Product\Helper\Form\Groupcatalogvisibility',
                        'required' => false,
                        'sort_order' => 9,
                        'visible' => true,
                        'group' => 'General',
                    ]
                );  
```
1. Above code will generate Custom Attribute to collect Multiple Customer Groups So product can be visible base on this Group Selection
2. Input render script

``` php
namespace Stepzerosolutions\Groupcatalogvisibility\Block\Adminhtml\Product\Helper\Form;

use Magento\Customer\Model\ResourceModel\Group\Collection;
use Magento\Framework\AuthorizationInterface;

/**
 * Product form category field helper
 */
class Groupcatalogvisibility extends \Magento\Framework\Data\Form\Element\Multiselect
{
    /**
     * @var \Magento\Framework\View\LayoutInterface
     */
    protected $_layout;

    /**
     * Backend data
     *
     * @var \Magento\Backend\Helper\Data
     */
    protected $_backendData;

    /**
     * @var \Magento\Catalog\Model\ResourceModel\Category\CollectionFactory
     */
    protected $_collectionFactory;

    /**
     * @var \Magento\Framework\Json\EncoderInterface
     */
    protected $_jsonEncoder;

    /**
     * @var AuthorizationInterface
     */
    protected $authorization;
    protected $_logger;
    /**
     * @param \Magento\Framework\Data\Form\Element\Factory $factoryElement
     * @param \Magento\Framework\Data\Form\Element\CollectionFactory $factoryCollection
     * @param \Magento\Framework\Escaper $escaper
     * @param \Magento\Catalog\Model\ResourceModel\Category\CollectionFactory $collectionFactory
     * @param \Magento\Backend\Helper\Data $backendData
     * @param \Magento\Framework\View\LayoutInterface $layout
     * @param \Magento\Framework\Json\EncoderInterface $jsonEncoder
     * @param AuthorizationInterface $authorization
     * @param array $data
     */
    public function __construct(
        \Magento\Framework\Data\Form\Element\Factory $factoryElement,
        \Magento\Framework\Data\Form\Element\CollectionFactory $factoryCollection,
        \Magento\Framework\Escaper $escaper,
        \Magento\Customer\Model\ResourceModel\Group\CollectionFactory $collectionFactory,
        \Magento\Backend\Helper\Data $backendData,
        \Magento\Framework\View\LayoutInterface $layout,
        \Magento\Framework\Json\EncoderInterface $jsonEncoder,
        AuthorizationInterface $authorization,
        \Psr\Log\LoggerInterface $logger,
        array $data = []
    ) {
        $this->_jsonEncoder = $jsonEncoder;
        $this->_collectionFactory = $collectionFactory;
        $this->_backendData = $backendData;
        $this->authorization = $authorization;
        parent::__construct($factoryElement, $factoryCollection, $escaper, $data);
        $this->_layout = $layout;
        if (!$this->isAllowed()) {
            $this->setType('hidden');
            $this->addClass('hidden');
        }
        $this->_logger = $logger;
    }

    /**
     * Get values for select
     *
     * @return array
     */
    public function getValues()
    {
        $options = [];
        $values = $this->getValue();//die(var_dump($values));
        if (!is_array($values) && $values!=NULL ) {
            $values = explode(',', $values);
        }

        $collection = $this->_getGroupsCollection();
        if( $values==NULL ){
            $collection->addFieldToFilter( 'customer_group_id', array('null' => true ) );
        } else { 
            $collection->addFieldToFilter( 'customer_group_id', array('in' => $values ) );
        }
        foreach ($collection as $group) {
            $options[] = ['label' => $group->getCustomerGroupCode(), 'value' => $group->getCustomerGroupId()];
        }
        return $options;
    }

    /**
     * Get categories collection
     *
     * @return Collection
     */
    protected function _getGroupsCollection()
    {
        return $this->_collectionFactory->create();
    }

    /**
     * Attach category suggest widget initialization
     *
     * @return string
     */
    public function getAfterElementHtml()
    {
        if (!$this->isAllowed()) {
            return '';
        }
        $htmlId = $this->getHtmlId();
        $suggestPlaceholder = __('start typing customer group name');
        $selectorOptions = $this->_jsonEncoder->encode( $this->_getSelectorOptions() );
        $return = <<<HTML
    <input id="{$htmlId}-suggest" placeholder="$suggestPlaceholder" />
    <script>
        require(["jquery", "mage/mage"], function($){
            $('#{$htmlId}-suggest').mage('treeSuggest', {$selectorOptions});
        });
    </script>
HTML;
        return $return;
    }

    /**
     * Get selector options
     *
     * @return array
     */
    protected function _getSelectorOptions()
    {
        return [
            'source' => $this->_backendData->getUrl('groupcatalogvisibility/groups/suggestGroup'),
            'valueField' => '#' . $this->getHtmlId(),
            'className' => 'groupcatalogavailability-select',
            'multiselect' => true,
            'showAll' => true
        ];
    }

    /**
     * Whether permission is granted
     *
     * @return bool
     */
    protected function isAllowed()
    {
        return $this->authorization->isAllowed('Magento_Customer::group');
    }
}
```
1. In Magento Catalog Now I can select Multiple Customer Groups, and it's similar to Product Category selection (Up to This point it's working)
## Expected result
1. When I save the product it should save the Customer Groups in a string, same as category_ids attribute
## Actual result
1. Only save One Customer Group (First Item from the selection)

**Comment by katmoon** [comment] 2016-05-19 11:31
Hi @stepzerosolutions 

Currently there are known problems with multiselect attribute
Please see #4346 and #4312

**Comment by KrystynaKabannyk** [comment] 2016-06-23 16:41
Hello @stepzerosolutions, this issue has been fixed in the 2.1.0 Release, that's why I'm closing it. If you any questions or additional information regarding the issue feel free to reopen it or create a new one.

**Closed as completed by KrystynaKabannyk** 2016-06-23 16:41 UTC

**Comment by Styopchik** [comment] 2017-02-16 11:48
Issue still present in 2.1.3

**Comment by sinamiandashti** [comment] 2017-03-01 19:36
2.1.4 still happening

**Comment by sinamiandashti** [comment] 2017-03-01 19:36
@KrystynaKabannyk

**Comment by nkajic** [comment] 2017-05-26 10:01
Seems like duplicate of #6253 #6281 #6787
and that this is fixed by
https://github.com/nagno/magento2/commit/b380502570b92449326ab6ed50e6ce0359287240

**Comment by A-1A** [comment] 2018-06-19 08:18
I Found Solution after R&D On Magento database.
Login In your phpmyadmin
Go to your website database 
Open "eav_attribute" table
Find Your multiselect "attribute_id"
Edit Row
If "backend_model" Column blank then paste this **Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend**
And Also Please check this
https://magento.stackexchange.com/questions/224621/warning-array-filter-expects-parameter-1-to-be-array/230444#230444

**Comment by collinanderson** [comment] 2018-07-19 16:00
in addition to changing `backend_model`, I needed to change `backend_type` from `varchar` to `text`
