### ISSUE TITLE
Can't save Logo Image to Transactional Emails

### ISSUE THREAD

**Issue by bachlee89** [magento/magento2#6502] opened 2016-09-06 04:58 UTC
On the Magento version 2.1.0 and 2.1.1
I can't save Logo Image to Transactionsal Emails after upload from my local
Steps to reproduce
1. Go to Backend area : Content/Design/Configuration
2. Edit a Store View
3. Scroll to Transactional Emails
4. Click upload logo image then select a image from your computer

Expected result
- Logo image should be saved

Actual result

Image can't uploaded:
![image](https://cloud.githubusercontent.com/assets/5562316/18262170/50cb56da-7429-11e6-901e-3468e28bbc89.png)

Please solve. Thanks

**Comment by pboisvert** [comment] 2016-09-06 05:05
appears to be a duplicate of #6275  please reopen if truly a separate issue

**Closed as completed by pboisvert** 2016-09-06 05:05 UTC
Labels: Issue: Ready for Work

**Comment by magento-team** [comment] 2017-08-01 01:09
Internal ticket to track issue progress: MAGETWO-69062
