### ISSUE TITLE
Magento ver. 2.3.5-p1Invalid input datetime format of value '5/26/2020'

### ISSUE THREAD

**Issue by pacsylpz** [magento/magento2#28355] opened 2020-05-25 06:00 UTC
### Preconditions (*)

1. Magento ver. 2.3.5-p1
2. PHP 7.3
3. LOCALE ENGLISH:
![image](https://user-images.githubusercontent.com/63178850/82782875-f5e93700-9e22-11ea-83cc-89fa9406635a.png)

### Steps to reproduce (*)

1. I am trying to set product as new
2. not working it says: Invalid input datetime format of value '5/26/2020'

### Expected result (*)

1. I do expect for the product to be saved.

### Actual result (*)

1. [Screenshots, logs or description]

![image](https://user-images.githubusercontent.com/63178850/82782793-d3571e00-9e22-11ea-9a57-227ed41e52e6.png)

2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment] 2020-05-25 07:37
Hi @pacsylpz. 
Not able to reproduce on 2.3.5-p1 instance as provided steps by you.
Kindly refer below screenshots for same:
![image](https://user-images.githubusercontent.com/46617848/82789761-7e4df300-9e88-11ea-8889-ee7e537e3da8.png)

![image](https://user-images.githubusercontent.com/46617848/82789844-a2113900-9e88-11ea-9d8d-7beaa7a1eedb.png)

Kindly provide more detailed steps to reproduce this issue
Thanks !!

**Comment by pacsylpz** [comment] 2020-05-26 01:15
Hello, here is a recording I have made with the configuration I have:

https://drive.google.com/file/d/1bkPaDpABepiUexKaOBWp8LwQ-XfhV486/view

I have two websites under the same magento with different, domains:
![image](https://user-images.githubusercontent.com/63178850/82851136-6eec9b00-9ec4-11ea-8576-f7c5cab84bc4.png)

**Comment by pacsylpz** [comment] 2020-05-26 03:36
Dear @krishprakash :
I have an update:

I have changed this from ENGLISH TO ESPAÑOL and it works now!
I just wonder, WHY?

![image](https://user-images.githubusercontent.com/63178850/82857956-19ba8480-9ed8-11ea-9647-401a981141da.png)

**Comment by krishprakash** [comment] 2020-05-26 06:34
@pacsylpz. Great :+1:  Thank you !! then I 'm closing this as this is only a configuration problem

**Closed as completed by krishprakash** 2020-05-26 06:34 UTC
Labels: Issue: Format is valid, Reported on 2.3.5-p1
