### ISSUE TITLE
Infinite loading after 999 page was selected

### ISSUE THREAD

**Issue by lghelghe** [magento/magento2#38057] opened 2023-10-09 19:00 UTC
### Preconditions and environment

- Magento version 2.3.7 p4
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

log in
Changed to 999 per page
Few days later
Log in
infinite loading will never stop then show error popup
but no way to get out

### Expected result

either it gives me an option to change # per page, or way to reset all filters to default

### Actual result

infinite loading & error popup > no way to get out or stop

![image](https://github.com/magento/magento2/assets/143628070/7f896c3c-14b6-4b72-a5cf-e8b6a3587a17)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by lghelghe** [comment] 2023-10-18 13:36
I can't click /select anything as loading circle stays top of the menu which makes me impossible to select anything

**Comment by engcom-Dash** [comment] 2023-10-20 05:30
Hi @lghelghe . Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

![image](https://github.com/magento/magento2/assets/60198592/e6ca5608-af68-4207-b862-5b5f5575a990)


Can you please check if any third party modules causing the issue.

**Comment by lghelghe** [comment] 2023-10-25 13:44
disabled/removed all 3rd party extension, but still not working

**Comment by engcom-Dash** [comment] 2023-10-26 12:42
Hi @lghelghe Thank you for reporting and collaboration.
Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.
It is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.

**Comment by lghelghe** [comment] 2023-10-30 17:38
can you advise how i can try 2.4 develop version?

**Comment by engcom-Dash** [comment] 2023-10-31 06:30
Hi @lghelghe 
To try 2.4 develop version please request magento instance by using : "@magento give me 2.4-develop instance".
Once you get the instance you can try the scenario on that instance.

**Comment by lghelghe** [comment] 2023-11-03 15:24
@magento give me 2.4-develop instance

**Comment by lghelghe** [comment] 2023-11-03 15:25
@engcom-Dash, I can't access to 2.4 develop instance or the link above is broken/not accessible from my end

**Comment by lghelghe** [comment] 2023-11-03 15:35
@engcom-Dash, on 2.4 develop instance, I do not see the issue I'm having. So, can you advise how I can update to 2.4?

**Comment by engcom-Dash** [comment] 2023-11-06 10:30
Hi @lghelghe 
Thanks for collaboration and reporting.
You can use these below guides to upgrade to magento 2.4. 
For composer please use this guide - https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/implementation/perform-upgrade.html?lang=en

For develop instance use this guide - https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/developer/git-installs.html?lang=en

**Comment by engcom-Dash** [comment] 2023-11-20 06:38
Hi @lghelghe 

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2023-11-20 06:38 UTC
Labels: Issue: needs update, Reported on 2.3.7-p4
