### ISSUE TITLE
Error during saving product at storeview level 2.3.3.

### ISSUE THREAD

**Issue by LucasMDL** [magento/magento2#26304] opened 2020-01-08 08:13 UTC
### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)
1. Create an Dutch and German storeview
2. Set admin account locale to Dutch
3. Create a product with a fixed price
4. Edit this product and switch to German storeview
5. Make any modification to the product
6. Save the product

### Expected result (*)
1. Succesfull saving.

### Actual result (*)
1. Error showing up: 
`Notice: A non well formed numeric value encountered in /var/www/vhosts/development/drempelhulpen_com/vendor/magento/module-catalog/Model/ResourceModel/Product/Option.php on line 214`

In my case `$object->getPrice()` returns 0,00, but should return 0.00.

**Comment by shikhamis11** [comment] 2020-01-11 01:27
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-01-11 01:27
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-11 01:27
Hi @shikhamis11, here is your [Magento instance](https://i-26304-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26304-2-4-develop.instances.magento-community.engineering/admin](https://i-26304-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2020-01-27 12:20
Hi @LucasMDL !
thank you for reporting this issue .. I tried reproducing this issue but not able to reproduce this issue . 
Let me know If it requires additional steps to reproduce this issue. 
also Please share screen shots if you are able to reproduce this issue at develop instance

**Comment by filiprozenek** [comment] 2020-02-05 09:40
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment] 2020-02-05 09:40
Hi @filiprozenek. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment] 2020-02-05 09:41
Hi @filiprozenek, here is your [Magento instance](https://i-26304-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26304-2-3-3.instances.magento-community.engineering/admin_db43](https://i-26304-2-3-3.instances.magento-community.engineering/admin_db43)
Login: `6d889987` Password: `b59f3165b5ff`
Instance will be terminated in up to 3 hours.

**Comment by filiprozenek** [comment] 2020-02-05 10:06
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-05 10:07
Hi @filiprozenek. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-05 10:07
Hi @filiprozenek, here is your [Magento instance](https://i-26304-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26304-2-4-develop.instances.magento-community.engineering/admin_2508](https://i-26304-2-4-develop.instances.magento-community.engineering/admin_2508)
Login: `0020c45d` Password: `b182ab3a00ce`
Instance will be terminated in up to 3 hours.

**Comment by filiprozenek** [comment] 2020-02-05 10:27
I couldn't reproduce this bug on both _m.2.3.3_ & _m.2.4-develop_.

Regarding the issue's description: 
1. I have created NL & DE Store Views
2. I have set Locale to NL
3. I have created Simple, Confugurable & Bundle Products
4. I have edited above products for DE Store View

In all 3 cases I was given a proper/expected behaviour.

![a1](https://user-images.githubusercontent.com/60395699/73833433-47d16700-480a-11ea-930c-1cbb7dccc304.png)
![a2](https://user-images.githubusercontent.com/60395699/73833449-4c961b00-480a-11ea-9740-ef55b80a4549.png)
![a3](https://user-images.githubusercontent.com/60395699/73833462-50c23880-480a-11ea-891b-53ca2f9c473f.png)

I'm closing this issue. 
_> Cannot Reproduce_

Checked on:
MacBook Pro (Mid 2014) macOS Mojave ver. 10.14.6
Firefox Browser ver. 72.0.2 (64-bit)

**Closed as completed by filiprozenek** 2020-02-05 10:27 UTC
Labels: Issue: Format is valid, Reported on 2.3.3

**Comment by OvalMedia** [comment] 2022-05-19 10:19
I encountered the same issue on 2.4.3-p1.

It happened in a catalog_product_save_before (or after, does not matter) event. I wanted to do some calculations with the product price. The error appeared depending on the admin user's locale. While no error came up while using the english locale (US), it did so while using the german locale.

1. create a catalog_product_save_before event observer
2. in that observer try to do some calculation with the value of $product->getPrice()
3. set admin user locale to german
4. create product
5. set price to e.g. 123
6. save product

Expected result:

getPrice returns a valid float value (123.00) and calculation works fine

Actual result:

getPrice returns a string value formatted depending on the current user's locale:

US: 123.00
DE: 123,00

Although the getPrice function claims to return a float value it actually returns a string value.
