### ISSUE TITLE
Flyout cart not updating in https pages

### ISSUE THREAD

**Issue by sneha-sukumaran** [magento/magento2#7122] opened 2016-10-21 10:56 UTC
### Preconditions
1.  Magento 2.0.10
2. SSL Certificate
### Steps to reproduce
1. Install magento 2.0.10
2. Set https for base secure urls for frontend in admin
3. Goto frontend add a product to cart. Observe the minicart items and count. Count will be one and the product will be displayed in minicart
4. From mini cart click view/edit cart, this will take to cart page(which is https)
5. In cart page observe minicart item count.
### Expected result
1. Minicart Item Count should be 1. And should display the added item
### Actual result
1. Minicart item and count empty

This happens when a product is added from http page then https page doesn't display the updated minicart content. If loading the product detail page in https and adding to cart, then https pages will display correct minicart content, but http pages will not show correct minicart content

**Comment by orlangur** [comment] 2016-10-23 21:02
This seems to be fixed in `develop` but not delivered to 2.0/2.1 branches yet: https://github.com/magento/magento2/issues/6487#issuecomment-251943469 Fix seems to be easy to cherry-pick to me also.

**Comment by sneha-sukumaran** [comment] 2016-10-24 12:30
@orlangur Thanks for the reference. I did do the change as per reference. But count is not updating in reorder scenario. Any input on this?

**Comment by orlangur** [comment] 2016-10-24 14:41
@sdzhepa, please advice if you have some insight.

**Comment by sneha-sukumaran** [comment] 2016-10-25 04:37
@orlangur I found the fix for it. Looks like it is another bug from magento https://github.com/magento/magento2/issues/6121

**Comment by dthampy** [comment] 2016-11-07 19:41
@sneha-sukumaran , did you try the fix from #6121 and can you update if it resolved your issue?
Thanks.

**Comment by veloraven** [comment] 2016-11-28 13:47
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Closed as completed by veloraven** 2016-11-28 13:47 UTC
Labels: bug report, Progress: needs update, Component: Checkout

**Comment by sneha-sukumaran** [comment] 2017-01-19 06:05
No #6121 did not fix this issue. They are 2 different issues. This still occurs

**Comment by orlangur** [comment] 2017-02-15 11:57
Ping @maghamed :)
