### ISSUE TITLE
2.4.7-p1 incompatible with magento/extension-b2b

### ISSUE THREAD

**Issue by edwinljacobs** [magento/magento2#38858] opened 2024-06-21 09:16 UTC
### Preconditions and environment

magento/extension-b2b cannot be installed with magento/product-enterprise-edition:2.4.7-p1

This is due to the following composer error:
```
╰─$ composer update
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - magento/extension-b2b[1.4.0, ..., 1.4.2] require magento/framework >=103.0.6 <=103.0.7 -> satisfiable by magento/framework[103.0.6-beta1, ..., 103.0.7].
    - You can only install one version of a package, so only one of these can be installed: magento/framework[100.0.2, ..., 100.2.0-rc20, 101.0.0-rc21, ..., 101.0.12, 102.0.0, ..., 102.0.7-p3, 103.0.0-beta1, ..., 103.0.7-p1].
    - magento/product-community-edition 2.4.7-p1 requires magento/framework 103.0.7-p1 -> satisfiable by magento/framework[103.0.7-p1].
    - magento/product-enterprise-edition 2.4.7-p1 requires magento/product-community-edition 2.4.7-p1 -> satisfiable by magento/product-community-edition[2.4.7-p1].
    - Root composer.json requires magento/product-enterprise-edition 2.4.7-p1 -> satisfiable by magento/product-enterprise-edition[2.4.7-p1].
    - Root composer.json requires magento/extension-b2b ^1.4 -> satisfiable by magento/extension-b2b[1.4.0, 1.4.1, 1.4.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions
```

So in essence Enterprise needs community  which needs magento/framework 103.0.7-p1. magento/extension-b2b needs magento/framework: <= 103.0.7 So we cannot install. I suspect that its just a version constraint issue and there is no incompatibility but ofcourse I am not sure of that.

AS a workaround we can do: "magento/framework": "103.0.7-p1 as 103.0.7" in composer json but I personally am not a fan of this kind of manipulation. I posted this as well in the community forums but no response yet https://community.magento.com/t5/Magento-2-x-Technical-Issues/Commerce-2-4-7-p1-incompatible-with-magento-b2b-extension/m-p/557149#M21933. 

### Steps to reproduce

Stock 2.4.7-p1 commerce installation
composer require magento/extension-b2b should produce the error mentioned below and above.

### Expected result

Install magento/extension-b2b without errors

### Actual result

```
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - magento/extension-b2b[1.4.0, ..., 1.4.2] require magento/framework >=103.0.6 <=103.0.7 -> satisfiable by magento/framework[103.0.6-beta1, ..., 103.0.7].
    - You can only install one version of a package, so only one of these can be installed: magento/framework[100.0.2, ..., 100.2.0-rc20, 101.0.0-rc21, ..., 101.0.12, 102.0.0, ..., 102.0.7-p3, 103.0.0-beta1, ..., 103.0.7-p1].
    - magento/product-community-edition 2.4.7-p1 requires magento/framework 103.0.7-p1 -> satisfiable by magento/framework[103.0.7-p1].
    - magento/product-enterprise-edition 2.4.7-p1 requires magento/product-community-edition 2.4.7-p1 -> satisfiable by magento/product-community-edition[2.4.7-p1].
    - Root composer.json requires magento/product-enterprise-edition 2.4.7-p1 -> satisfiable by magento/product-enterprise-edition[2.4.7-p1].
    - Root composer.json requires magento/extension-b2b ^1.4 -> satisfiable by magento/extension-b2b[1.4.0, 1.4.1, 1.4.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by thomas-kl1** [comment] 2024-06-21 09:30
See Magento forum post: https://community.magento.com/t5/Magento-2-x-Technical-Issues/Commerce-2-4-7-p1-incompatible-with-magento-b2b-extension/m-p/557191

Quick workaround to use in your project's composer require section: 

`"magento/framework": "103.0.7-p1 as 103.0.7"`

**Comment by yaronish** [comment] 2024-06-21 14:34
In addition I just want to say that proposed workaround works for PHP 8.2 and doesn't work for PHP 8.3. 
```
www-data@c829a04f430e:/var/www/html$ composer require magento/extension-b2b:"^1.4.2" "magento/framework": "103.0.7-p1 as 103.0.7"
./composer.json has been updated
Running composer update magento/extension-b2b magento/framework
Loading composer repositories with package information                                                                                                       Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - magento/module-b2b[100.4.0, ..., 100.4.1] require php ~8.1.0||~8.2.0 -> your php version (8.3.7) does not satisfy that requirement.
    - magento/extension-b2b 1.4.2 requires magento/module-b2b 100.4.1 -> satisfiable by magento/module-b2b[100.4.1].
    - Root composer.json requires magento/extension-b2b ^1.4.2 -> satisfiable by magento/extension-b2b[1.4.2].
```

**Comment by thomas-kl1** [comment] 2024-06-21 21:23
Yes but it's a known issue that B2B is not compatible with php8.3

**Comment by engcom-Dash** [comment] 2024-07-16 12:53
Hi @edwinljacobs 

Thanks for reporting and collaboration.

Verified the issue on Magento 2.4.7-p1 but the issue is not reproducible.

We can install 2.4.7-p1 with b2b extension.

Steps to reproduce
Stock 2.4.7-p1 commerce installation
composer require magento/extension-b2b should produce the error mentioned below and above.

Please take a look at the screenshots I've attached. Let us know if we missed anything.

<img width="1440" alt="Screenshot 2024-07-16 at 4 25 37 PM" src="https://github.com/user-attachments/assets/c9655611-0e09-42b7-9849-63b86095ffd1">

<img width="1440" alt="Screenshot 2024-07-16 at 6 20 29 PM" src="https://github.com/user-attachments/assets/a2ce895b-f746-4de4-95d0-ffae1a9051c9">

**Comment by thomas-kl1** [comment] 2024-07-16 13:13
hello @engcom-Dash 

Yes it has been fixed with the latest b2b package release, so we can close this ticket.
However any idea when b2b is going to be fully compatible with php8.?

Regards,

**Comment by engcom-Dash** [comment] 2024-07-17 13:25
Hi @edwinljacobs 

We are closing the ticket as per the above comments.

Thanks

**Closed as completed by engcom-Dash** 2024-07-17 13:25 UTC
Labels: Issue: needs update, Reported on 2.4.7-p1

**Comment by lohoy** [comment] 2024-07-18 08:51
Hello,

I have this issue with PHP 8.3 on Magento 2.4.7-p1.

When the b2b will be compatible with php8.3 ? 
We are in migration to Magento 2.4.6-p6 to 2.4.7-p1 and this uncompatibility blocks our development.

Have a good day.

**Comment by leonhelmus** [comment] 2024-10-30 13:12
@engcom-Bravo I now see that the package is compatible with version 100.5.0, but i don't see that update on this page:
https://experienceleague.adobe.com/en/docs/commerce-admin/b2b/release-notes#b2b-v142-p1

Is it still in beta mode while it has a stable tag?

**Comment by thomas-kl1** [comment] 2024-10-30 13:38
@leonhelmus I was able to upgrade the package to 1.5.0 this morning, so communication will follow soon I guess :D Even some documentation link in the package are still not yet published
