### ISSUE TITLE
Uncaught SyntaxError: unexpected token: keyword 'const' when minifying javascript files with constants and backticks `

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#35476] opened 2022-05-14 13:00 UTC
### Preconditions (*)

Please check this line of code for example 
https://github.com/magento/magento2/blob/7e794ce4d191e52d9518e2b1c6f0a0c51e4567e3/lib/web/jquery/bootstrap/collapse.js#L35

1. Magento 2.4.4 

### Steps to reproduce (*)

1. Set the following config options
```
dev/js/merge_files - 1
dev/js/enable_js_bundling - 1
dev/js/minify_files - 1
```
2. Create a few orders
3. Deploy static files and visit the orders grid 
4.  Watch the javascript errors

### Expected result (*)

1. No javascript errors 

### Actual result (*)

```Uncaught SyntaxError: unexpected token: keyword 'const'[collapse.min.js:4:30](https://dev.safeblock.gr/static/version1652532411/adminhtml/Magento/backend/en_US/jquery/bootstrap/collapse.min.js)```

```
Uncaught SyntaxError: unexpected token: keyword 'const'
```

The minified javascript files become broken like this because there are no delimiters for each new line when backticks are used. 

```
define(["jquery","./util/index","./dom/data","./dom/event-handler","./dom/manipulator","./dom/selector-engine"],function($,Util,Data,EventHandler,Manipulator,SelectorEngine){'use strict';const defineJQueryPlugin=Util.defineJQueryPlugin;const executeAfterTransition=Util.executeAfterTransition;const getElement=Util.getElement;const getSelectorFromElement=Util.getSelectorFromElement;const getElementFromSelector=Util.getElementFromSelector;const reflow=Util.reflow;const typeCheckConfig=Util.typeCheckConfig;const VERSION='5.1.3'
const NAME='collapse'
const DATA_KEY='bs.collapse'
const EVENT_KEY=`.${DATA_KEY}`const DATA_API_KEY='.data-api'
const Default={toggle:true,parent:null}
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-05-17 05:33
Hi @ioweb-gr ,
Thank you for reporting and collaboration. However this issue is a duplicate of https://github.com/magento/magento2/issues/35325. We are closing this issue. Please move on to this ticket for latest updates/solutions.
Thank you.

**Closed as completed by engcom-November** 2022-05-17 05:33 UTC
Labels: duplicate, Issue: ready for confirmation, Reported on 2.4.4

**Comment by ssx** [comment] 2022-05-24 13:24
Patch: https://gist.github.com/ssx/275bc6c9674277ed8d26592235f1cc6b
