### ISSUE TITLE
Multiselect config option 'use default' check disappears upon saving in website scope if value is locked in config.php

### ISSUE THREAD

**Issue by dot319** [magento/magento2#26874] opened 2020-02-14 09:13 UTC
### Preconditions (*)

1. Magento 2.3.2
2. PHP 7.2

### Steps to reproduce (*)

1. Add a multiselect config option in adminhtml/system.xml in an existing section in a custom group
2. Lock a value for this config option in the default scope
3. Go to configuration in the adminpanel and find the multiselect option
4. Switch to a website scope
5. Note that the newly added config option is grayed out and the 'use default' check is checked and grayed out
6. Don't edit anything, only click save

### Expected result (*)

1. The new config entry is still grayed out
2. The 'use default' check is still checked and grayed out
3. No entry is saved to the core_config_table for this option for the selected scope

### Actual result (*)

1. The new config entry IS still grayed out
2. But the 'use default' check is unchecked
3. A row is added to the core_config_table for the selected scope for the multiselect option with value NULL

**Comment by dot319** [comment] 2020-02-14 09:16
@magento give me 2.3.2 instance

**Comment by magento-engcom-team** [comment] 2020-02-14 09:16
Hi @dot319. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by magento-engcom-team** [comment] 2020-02-14 09:16
Hi @dot319, here is your [Magento instance](https://i-26874-2-3-2.instances.magento-community.engineering).
Admin access: [https://i-26874-2-3-2.instances.magento-community.engineering/admin_4093](https://i-26874-2-3-2.instances.magento-community.engineering/admin_4093)
Login: `55362579` Password: `4fcd0cf4eb82`
Instance will be terminated in up to 3 hours.

**Comment by Zyles** [comment] 2020-02-27 19:09
Sounds like:

https://github.com/magento/magento2/issues/26484

https://github.com/magento/magento2/issues/9186

**Comment by engcom-Alfa** [comment] 2021-01-13 12:24
Duplicate of #26484

**Closed as completed by engcom-Alfa** 2021-01-13 12:24 UTC
Labels: Issue: ready for confirmation, Reported on 2.3.2
