### ISSUE TITLE
Alert Message On Product Page

### ISSUE THREAD

**Issue by soumyamol-mathew** [magento/magento2#26898] opened 2020-02-17 13:56 UTC
When adding a product from wishlist to cart, alert messages are displaying more than once.
The number of alert messages is equal to the number of custom options.
![image](https://user-images.githubusercontent.com/26896299/74659257-018ce800-51ba-11ea-8a1b-9c75b8c44e87.png)

### Preconditions (*)

1. Add products with custom options to the wishlist.
2. Add the product from wishlist to cart.

### Steps to reproduce (*)

1. Add the product from wishlist to cart.

### Expected result (*)

1. A single line of Alert message should get displayed.

### Actual result (*)

1. Alert messages are equal to the number of custom options. ( More than one alert message is displayed.)

**Comment by yvaliya4** [comment] 2020-02-18 03:38
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-18 03:39
Hi @yvaliya4. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-18 03:39
Hi @yvaliya4, here is your [Magento instance](https://i-26898-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26898-2-4-develop.instances.magento-community.engineering/admin_2261](https://i-26898-2-4-develop.instances.magento-community.engineering/admin_2261)
Login: `3cdb5966` Password: `91fb7dc08683`
Instance will be terminated in up to 3 hours.

**Comment by yvaliya4** [comment] 2020-02-18 04:06
Issue: Confirmed

**Comment by magento-engcom-team** [comment] 2020-02-18 05:39
@pawankparmar Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2020-02-18 05:46
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31605` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by eduard13** [comment] 2020-02-18 09:15
@soumyamol-mathew, looks like this was made intentionally, in order to display all the issues that are related to adding that product to the cart.

Here is the internal ticket MAGETWO-52011 where this behavior has been added.
Thank you.

**Comment by soumyamol-mathew** [comment] 2020-02-18 10:34
@eduard13, I know its a default behavior, but it looks terrible. Just a line of the message is enough to notify about the required fields.

**Comment by pawankparmar** [comment] 2020-02-19 02:47
@eduard13 , as this is done intentionally and as per your comment it is not a bug , should I work on this or not ?

Thank you

**Comment by soumyamol-mathew** [comment] 2020-02-19 04:13
@pawankparmar, yes, please. As it looks terrible, we actually need a solution for this.

**Comment by soumyamol-mathew** [comment] 2020-02-20 08:00
@pawankparmar, @eduard13, Any update on the issue??

**Comment by eduard13** [comment] 2020-02-20 08:24
Hi @pawankparmar, if you have any improvement to add here, just create a PR with your solution.
Thank you.

**Comment by soumyamol-mathew** [comment] 2020-02-24 09:20
Hi @pawankparmar, Any updates on the issue?

**Comment by engcom-Delta** [comment] 2024-05-28 12:57
Hi @soumyamol-mathew , 

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the attached screenshots.

Product added to wishlist

<img width="1440" alt="Screenshot 2024-05-28 at 6 21 56 PM" src="https://github.com/magento/magento2/assets/51681379/33ad0007-933a-41eb-807f-7b1f238fc971">

product with custom option added to wishlist

<img width="1437" alt="Screenshot 2024-05-28 at 6 22 03 PM" src="https://github.com/magento/magento2/assets/51681379/0c5e38fa-1cbe-40bb-aace-30ccd6783a4f">

wishlist products

<img width="1438" alt="Screenshot 2024-05-28 at 6 22 27 PM" src="https://github.com/magento/magento2/assets/51681379/59356951-a0db-4037-ac9f-8ebf4c18b8cd">

single line of Alert message is displaying

<img width="1438" alt="Screenshot 2024-05-28 at 6 22 38 PM" src="https://github.com/magento/magento2/assets/51681379/d3443a3e-d3ec-4530-984a-0ae2af4f4f0e">

products added to cart

<img width="1440" alt="Screenshot 2024-05-28 at 6 22 47 PM" src="https://github.com/magento/magento2/assets/51681379/52e79a1e-9405-4c0d-8990-1739e7611489">

Hence closing the issue.

**Closed as completed by engcom-Delta** 2024-05-28 12:57 UTC
Labels: Issue: Ready for Work, Component: Catalog, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Wishlist, Reproduced on 2.4.x, Priority: P3, Severity: S2, Triage: Done, Progress: done
