### ISSUE TITLE
Magento2 admin too slow after installed successfully 

### ISSUE THREAD

**Issue by inkxe-ramendra** [magento/magento2#3123] opened 2016-01-25 14:11 UTC
Dear dev team,
we installed magento2 in my localhost , it installed successfully but we are facing so many issues . 
1. Too much slow admin as well as frontend , it always showing loading on the browser when we change any one page to another page .
1. Unable to create product New Attribute to click New attribute button . when we clicked new attribute it not redirect to attribute page . 

please let me what issue on my localhost . we waiting your Answer .

**Comment by mazhalai** [comment] 2016-01-25 15:13
@ramendra88 re speed, have you checked out the following threads: #1726, #2999, #2824 and #2669

**Comment by giappv** [comment] 2016-01-28 23:00
After installing magento successfully, it has not installed static files so it takes time for a lot of 404 not found error.
I had to run this command

`php bin/magento setup:static-content:deploy`

so we will have the admin & frontend theme installed correctly.

**Comment by mazhalai** [comment] 2016-03-08 17:55
@inkxe-ramendra any update?

**Comment by GanchoDanailov** [comment] 2016-03-17 15:50
i have tried everything found on the web and sill painful loading... its not possible to do front end work with 30+ second reloading page

**Comment by mazhalai** [comment] 2016-03-23 14:29
@GanchoDanailov did you setup varnish?

**Comment by mazhalai** [comment] 2016-05-09 17:39
Closing as non responsive

**Closed as completed by mazhalai** 2016-05-09 17:39 UTC
Labels: Progress: needs update

**Comment by theskillwithin** [comment] 2016-05-17 02:43
deploying static content is not a solution to this, obviously local environment is meant for developing in so you have develop mode set and caching off.   It is painfully slow to develop in compared to magento 1.

**Comment by nikunj1990** [comment] 2016-05-17 13:58
its terribly slow on local host, did everything on php.in config, tried to apply manythings but at the ends it terribly slow.

**Comment by Windmagez** [comment] 2016-07-08 18:30
Indeed M2 is very slow on localhost, I have manage to lessen the sluggishness by increasing php memory limit, for test site it's recommended to set it into 2G from .htaccess file

**Comment by zeki893** [comment] 2016-07-18 04:39
wow setting memory_limit = 2g makes a world of difference

**Comment by eleorex** [comment] 2016-08-30 19:04
php_value memory_limit 2G 
makes my Magento2 admin to load much faster,

It was just loading and loading before and gives connection time out.

**Comment by twistedatrocity** [comment] 2017-02-23 03:18
I thought I would drop my experiences here for google since this came up in a search for me in trying to figure out my slowdown. Admin pages taking 30s - 1m to load in M2.1.4.

I had switched to developer mode to debug an extension. Afterward I switched back to production mode and it threw an error at the setup:static-content:deploy (this always has at least one error since clean install and it's always with a translation routine even though I have nothing needing it).

Doing a php bin/magento deploy:mode:status  said it was in production mode. However after much searching I had a hunch to try running the mode set again without compiling... e.g.  php bin/magento deploy:mode:set -s production

Boom everything fast again. So it appears it thought it was in production mode as evidenced by the status, however it really wasn't since it errored on the static content deploy and didn't fully complete the mode set command... yet managed to set the status. Pretty buggy if you ask me. But this fixed the issue with being super slow for me.

**Comment by orlangur** [comment] 2017-02-23 07:10
Hi @twistedatrocity,

> Admin pages taking 30s - 1m to load in M2.1.4

Are you using PHP 7? It is like x3 times faster than PHP 5.6 and I see no reason use the latter for development nowadays.

> Afterward I switched back to production mode and it threw an error

In such case it would be not superfluous to check current mode with `show` command. There is also `default` mode which may be pretty slow for initial requests.

**Comment by hmkaddoura** [comment] 2017-02-23 15:00
Hi I agree with @twistedatrocity ..

1. running php bin/magento deploy:mode:set -s production made it much faster than before.
2. I couldn't find the .htaccess to change

Now it is working as a charm

**Comment by SyedMuneebb** [comment] 2017-04-21 06:45
Magento 2 is not slow by default. To improve it speed and performance these steps are required: 

- Server and System Requirements
- Update Magento Version
- Enable Varnish Cache
- Configure Memcached
- Enable Flat Categories and Products
- Optimize Javascript and CSS
- Content Delivery Network
- Bug-Free Extensions
- Images Should be Fully Optimized

Source: [Why Magento 2 is slow?](https://magenticians.com/why-magento-2-is-slow/)

**Comment by MichalZabrocki** [comment] 2017-05-23 11:43
I had this problem after importing database from other server. Problem was that some triggers in database had set definer on other user then i set in Magento connection to database. I had this other user created but i decide to change this to default user. After that admin panel start to work as normal. 
That was weird because developer toolbar didn't show problem with db rather with layout

**Comment by TenGauge** [comment] 2017-08-23 01:37
Implementing production mode will let you take advantage of CSS and JavaScript merging and minifying which makes a truly drastic improvement to your stores performance.  Coupled with PHP7 w/ PHP-FPM Magento 2 absolutely flies.  

Follow this guide for easy and proper deployment of production mode: http://www.codealist.net/magento-2-moving-to-production-mode/

**Comment by ankit15681** [comment] 2018-11-20 15:57
Just access magento server via ssh and run following command 
php bin/magento deploy:mode:set -s production made
and your site will run much faster

**Comment by rbjns** [comment] 2018-12-18 16:00
Hello. Came across this issue which I had too. If you the issue is still not solved, check out this article https://onilab.com/blog/magento-admin-back-end-slow/
It's up-to-date and helped me a lot.

**Comment by sergiomendonca** [comment] 2018-12-21 20:00
Years later and magento 2 continues extremally slowly on localhost. Docker, varnish, Mac...
Nothing make magento 2 fast.

**Comment by DanielRuf** [comment] 2018-12-25 13:02
Plsase see the previous comments which provide solutions.

Also Xdebug and too few resources make it slow. See https://blackfire.io for a debugging solution.

**Comment by Amandamur8** [comment] 2021-06-24 12:51
Nowadays, eCommerce buyers are impatient. The loading speed of a website is a crucial component that search engines evaluate when ranking each web page. As a result, every Magento owner should track the store's performance. This is the basis for Magento performance improvement. Installing performance-enhancing extensions will increase the performance of your Magento shop. These will improve user experience and, as a result, sales.
[Mage Monkeys](https://www.magemonkeys.com/magento-performance-optimization-service/) will cover details about how to improve Magento performance and ensure that you don't miss any revenue due to high dropout levels or unsatisfied customer experience.

1. Latestt Version
2. Image Optimization
3. Enable Flat Catalog
4. Content Delivery Network
5. Utilize Caching
6. Fewer Extensions & Modules
7. Concatenate (merge) CSS and Javascript Files
8. Enable Magento Compilation
9. Choose Fast Web Hosting
10. Clean Up Magento Database & Logs
11. MySQL Configuration

**Comment by Abdulkadiragoliya** [comment] 2021-12-30 05:59
Please try increasing the max_session_size_admin and  max_session_size_storefront either from admin or by executing the below commands

bin/magento config:set system/security/max_session_size_admin 512000
bin/magento config:set system/security/max_session_size_storefront 512000
