### ISSUE TITLE
No option to disable the Google Shopping ads pop up

### ISSUE THREAD

**Issue by ghoshsweta** [magento/magento2#24944] opened 2019-10-09 12:44 UTC
### Preconditions (*)

No option to disable the Google Shopping ads pop up
Issue Present in Magento 2.3.3

### Steps to reproduce (*)
1. Login to magento admin panel on Chrome browser
2. Go to Marketing->Advertising Channels->Google Shopping ads

### Expected result (*)
1.Option to close this pop up should come

### Actual result (*)
1. No option to close the pop up
![image](https://user-images.githubusercontent.com/25763126/66482409-848d8b80-eac0-11e9-8854-f7b4689ce340.png)

**Comment by magento-engcom-team** [comment] 2019-10-10 10:03
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21681` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by madhu-ranosys** [comment] 2020-04-06 12:06
Is this the issue? As I have gone through this functionality and feature, Pop up does not show on firefox and other browsers also. As I have found that without configuring We can't proceed further First we need to configure with key and after that one another popup appears where we need to config google account and other configurations as well Then it proceeds further. 
Also, I found If We delete popup elements with the inspector Then Buttons and other elements settings do not work As I am assuming here that there is no close button for popups because they don't want to proceed further without configuration. Without configuring with popup configuration there is nothing to do further. So I don't think there is a need for a close button.
Please discuss with the team and let me know if there is a need for a close button on popup we can implement if needed.

**Comment by madhu-ranosys** [comment] 2020-04-08 05:53
Hi @swetacedcoss @magento-engcom-team 
Can you please update on the current state here?
Thank you!

**Comment by hostep** [comment] 2020-04-08 06:42
@madhu-ranosys: I think I read that Magento is discontinuing the google shopping ads module and it will no longer be included in Magento 2.3.5 and 2.4.0.
So this issue is most likely no longer valid. But let's wait until Magento 2.3.5 gets released  (should happen on 28 April) to see if that's true or not.

**Comment by madhu-ranosys** [comment] 2020-04-08 06:45
Ok, Thanks.

**Comment by rmanor1** [comment] 2020-10-06 15:35
Hello, this should probably be closed as we've deprecated the Google Shopping ads Channel, and the [service was shut down ](https://docs.magento.com/user-guide/sales-channels/google-eol.html)as of Apr 28th.

**Closed as completed** 2020-10-06 15:38 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Backend, Component: Google Shopping ads, Progress: done
