### ISSUE TITLE
The autoloader throws an exception on class_exists

### ISSUE THREAD

**Issue by sidolov** [magento/magento2#20773] opened 2019-01-29 17:36 UTC
### Summary (*)
The autoloader throws an exception on `class_exists`. That is clearly an unexpected behavior according to the documentation: http://php.net/manual/en/function.class-exists.php

This will cause issues when including third-party libraries that are not written for Magento. 

An autoloader that throws an exception is not [PSR-4](https://www.php-fig.org/psr/psr-4/) compliant

### Examples (*)
Run `class_exists('FooFactory')`. It should return `false` but an error is thrown instead. 

To reproduce the issue apply changes from the https://github.com/magento/magento2/pull/14085

Expected result: there is no error thrown
Actual result: autoloader throws an exception

@Vinai, @kandy, @orlangur I moved content from the https://github.com/magento/magento2/pull/14085 to current issue.  
### Proposed solution

**Comment by magento-engcom-team** [comment] 2019-01-29 17:36
Hi @sidolov. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sidolov do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-30 07:35
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-01-30 08:02
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97979`, `MAGETWO-97980` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-02-03 04:17
Hi @Vinai. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by Vinai** [comment] 2019-02-03 04:49
#mm19in

**Comment by magento-engcom-team** [comment] 2019-02-25 10:46
Hi @sidolov. Thank you for your report. 
The issue has been fixed in magento/magento2#20950 by @Vinai in 2.3-develop branch
Related commit(s):
 - [cab38a21087525b72add16910b6eccf7eb7e1b63](https://github.com/magento/magento2/commit/cab38a21087525b72add16910b6eccf7eb7e1b63)
 - [cfbf8c9e7422134f3419eaf719f4b0178075c844](https://github.com/magento/magento2/commit/cfbf8c9e7422134f3419eaf719f4b0178075c844)
 - [9d3bc1877c4d48eae2e0ef7e7acc33b617474ecc](https://github.com/magento/magento2/commit/9d3bc1877c4d48eae2e0ef7e7acc33b617474ecc)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-02-25 10:46 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Framework/Code, Event: mm19in

**Comment by magento-engcom-team** [comment] 2019-03-22 15:35
Hi @sidolov. Thank you for your report. 
The issue has been fixed in magento/magento2#21435 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [2e58ab6009c68ea1e4e0095897517c68273995f9](https://github.com/magento/magento2/commit/2e58ab6009c68ea1e4e0095897517c68273995f9)
 - [3de1647e51215ba933f007cab64e9483f2487c61](https://github.com/magento/magento2/commit/3de1647e51215ba933f007cab64e9483f2487c61)

The fix will be available with the upcoming 2.2.9 release.
