### ISSUE TITLE
AJAX Add To Cart  Is Not Working For Configurable Product In List page

### ISSUE THREAD

**Issue by sabarivenkatesankrish** [magento/magento2#10232] opened 2017-07-13 06:35 UTC
Hi all,

For newly created configurable products, the ajax add to cart is not working in list page. Instead it redirect to the product detail page. While checking about this, in run time the product object instance is having the field(Not a product attribute) name required_options. This field is set as 'true' for all the cases while creating and editing a product. If this field is enabled it will redirect to product detail page and if it is disabled the ajax cart url will be provided the button. So the product will add to the cart without redirecting itself. I don't know why this field is enabled even if we select all the options for the configurable product.

Preconditions:
1. Ubuntu 16.04
2. Magento 2.1.7

Steps to reproduce:
1. Create a configurable product with configurable options(virtual products).
2. In front end go to the category page which is having the created configurable product
3. Select configurable options(size, color...) and click Add to Cart button.

Expected result:
1. Should be added in to the cart without loading itself(AJAX).

Actual result:
1. It redirects to the product detail page and asks again to choose the options.

Any comments and suggestion would be appreciated.
Thanks,

**Comment by veloraven** [comment] 2017-07-25 11:38
@sabarivenkatesankrish thank you for your feedback.
But I'm closing this issue as a duplicate of #8470.

**Closed as completed by veloraven** 2017-07-25 11:38 UTC
