### ISSUE TITLE
Magento 2.3.1 installation gives 500 error

### ISSUE THREAD

**Issue by logicallimit** [magento/magento2#22972] opened 2019-05-22 10:54 UTC
Summary of the issue: 
On a new installation of Magento CE 2.3.1, I get 500 error when I access my development sub-domain.

Information on the environment:
OS Name: CentOS Linux release 7.6.1810 at Digital Ocean
Using Varnish Cache Server and Nginx Reverse Proxy

### Steps to reproduce (*):
1. Uploaded Magento 2.3.1 CE zipped file to development subdomain root
2. Extracted it
3. Accessed development subdomain URL in the browser
4. I get 500 error on the browser as below:
> Internal Server Error
> The server encountered an internal error or misconfiguration and was unable to complete your request.
5. If I remove entry `Options +FollowSymLinks` from default .htaccess file that came in the downloaded Magento CE 2.3.1 zipped package then the Magento installation screen shows up normally.

> [Wed May 22 10:49:26.533936 2019] [core:alert] [pid 21653:tid 140634820118272] [client 179.50.121.141:48721] /home/myadmin/dev.domainname.com/.htaccess: Option FollowSymLinks not allowed here

I researched a few places on internet and found people suggesting to use `Options +SymlinksIfOwnerMatch` instead of `Options +FollowSymLinks`

### Preconditions (*)
1. Apache version: Apache/2.4.39
2. PHP version: 7.2.18
3. MySQL version: 10.1.40-MariaDB
4. Magento 2.3.1 CE

### Expected result (*)
Following screen should be shown normally
![image](https://user-images.githubusercontent.com/7191368/58169105-8f7c8680-7cad-11e9-847d-2de1c24c93fc.png)

### Actual result (*)
Following error is shown on browser
![image](https://user-images.githubusercontent.com/7191368/58169156-b2a73600-7cad-11e9-8769-582d2ce188d8.png)

**Comment by williankeller** [comment] 2019-05-23 10:09
Hi @logicallimit
Could you share the error in your Apache logs? Otherwise, we can't understand the root cause of the error.

**Comment by logicallimit** [comment] 2019-05-23 11:56
@williankeller 

Following is the error log shown:

> [Wed May 22 10:49:26.533936 2019] [core:alert] [pid 21653:tid 140634820118272] [client 179.50.121.141:48721] /home/myadmin/dev.domainname.com/.htaccess: Option FollowSymLinks not allowed here

I researched a few places on internet and found people suggesting to use `Options +SymlinksIfOwnerMatch` instead of `Options +FollowSymLinks`

I found such a link although not related to Magento but to Drupal suggesting same.
[link](https://www.drupal.org/project/drupal/issues/1269780)

**Comment by williankeller** [comment] 2019-05-23 18:01
Hi @logicallimit, 
I did some research and this is not a Magento related issue and is not reproducible.
It's probably related with your CentOs server configuration.
Please make sure you have the right configuration under your virtual hosts, like:
```
<Directory /var/www/magento>
    Options FollowSymLinks
    AllowOverride All
    Order deny,allow
    Allow from all
</Directory>
```
You should keep using the `FollowSymLinks` for security reasons and also you can face some issues with the SEO rewrite, etc.

I'm closing this ticket since the research I did shows up that might be a server configuration.
You can reopen or create a new one.
Thanks.

**Closed as completed by williankeller** 2019-05-23 18:01 UTC
Labels: Progress: needs update, Issue: Clear Description, Issue: Format is valid
