### ISSUE TITLE
Magento2 Swatch change Image does not slide to first Image

### ISSUE THREAD

**Issue by matin73** [magento/magento2#23030] opened 2019-05-28 09:58 UTC
### Preconditions (*)
Magento 2.2.x and Magento 2.3.1
PHP 7.0

### Steps to reproduce (*)
Install Magento
Add some configurable products and swatches
Go to product detail page and click trough gallery
Now click on swatch-image (f.e. color)

### Expected result (*)
Gallery is loading images for color correctly and adding them on first position (method prepend)
Gallery should switch to first image because first image is starting swatch images

### Actual result (*)
Gallery is loading images for color correctly and adding them on first position (method prepend)
Gallery is not switching to first image as it was in older magento 2 versions

**Comment by matin73** [comment] 2019-05-28 09:59
@matin73 do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?

yes

**Comment by matin73** [comment] 2019-05-28 10:00
Solution: just add gallery.first(); in line 1253 in vendor/magento/module-swatches/view/frontend/web/js/swatch-renderer.js

`updateBaseImage: function (images, context, isInProductView) {
        var justAnImage = images[0],
            initialImages = this.options.mediaGalleryInitial,
            imagesToUpdate,
            gallery = context.find(this.options.mediaGallerySelector).data('gallery'),
            isInitial;

        if (isInProductView) {
            imagesToUpdate = images.length ? this._setImageType($.extend(true, [], images)) : [];
            isInitial = _.isEqual(imagesToUpdate, initialImages);

            if (this.options.gallerySwitchStrategy === 'prepend' && !isInitial) {
                imagesToUpdate = imagesToUpdate.concat(initialImages);
            }

            imagesToUpdate = this._setImageIndex(imagesToUpdate);

            if (!_.isUndefined(gallery)) {
                gallery.updateData(imagesToUpdate);
            }

            if (isInitial) {
                $(this.options.mediaGallerySelector).AddFotoramaVideoEvents();
            } else {
                $(this.options.mediaGallerySelector).AddFotoramaVideoEvents({
                    selectedOption: this.getProduct(),
                    dataMergeStrategy: this.options.gallerySwitchStrategy
                });
            }
            gallery.first();
        } else if (justAnImage && justAnImage.img) {
            context.find('.product-image-photo').attr('src', justAnImage.img);
        }
    },`

**Comment by Eayshwary** [comment] 2019-05-28 10:12
Yes Worked Finally, Thanks @matin73 , I was experiencing same issue in 2 magento versions , the image was not being updated on swatch option selection, but after putting gallery.first() in swatch-renderer.js , Its working (y)

**Comment by magento-engcom-team** [comment] 2019-05-28 11:07
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99844`, `MAGETWO-99845` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-05-31 14:18
Hi @matin73. Thank you for your report. 
The issue has been fixed in magento/magento2#23033 by @milindsingh in 2.3-develop branch
Related commit(s):
 - [27709457bb655f4e82b687b078ee80142b42354a](https://github.com/magento/magento2/commit/27709457bb655f4e82b687b078ee80142b42354a)

The fix will be available with the upcoming 2.3.3 release.

**Closed as completed by magento-engcom-team** 2019-05-31 14:18 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: ConfigurableProduct

**Comment by ljr95** [comment] 2019-08-26 06:11
Hello, thank you for your solution. I want to know what is the best solution to apply this correction before the release of 2.3.3?

Should I overload the file "swatch-renderer.js" if so how?
Where is it better to update the original file?

**Comment by matin73** [comment] 2019-08-26 06:27
copy js file to you theme:
app/design/frontend/Xxxx/yyyy/Magento_Swatches/web/js/swatch-renderer.js

**Comment by ljr95** [comment] 2019-08-26 14:38
Hello, thank you very much for your answer I just did what you told me but the problem does not seem to be fixed.

How can I make sure that this is the file that is overloaded that is active?

When i look in the html version of the page i can not find the file swatch-renderer.js, is this normal?

I specify that I have emptied all cache by CLI.

Thanks for your help

**Comment by matin73** [comment] 2019-08-26 14:51
swatch-renderer.js is loaded via script. have a look into webdeveloper tool of you browser to find swatch-renderer.js

**Comment by ljr95** [comment] 2019-08-26 16:18
Thanks a lot for your help, it was not the correct file that was loaded.
It was a mistake on my part because when I had the picture problem I changed the setting of the theme to use Luna to check that the problem was not a bug of my theme which is a child luna.

Now it is the right file but it does not contain the correction at line 1257 :-(
I do not understand yet I empty the cache of the browser and magento :
bin/magento cache:clean
bin/magento cache:flush
bin/magento setup:static-content:deploy -f
bin/magento indexer:reindex

When I look at the file directly on the server it is the correct one.
Do you have an idea?
Sorry I'm starting

**Comment by ljr95** [comment] 2019-08-27 10:22
The problem had been solved by doing:
php bin/magento setup:upgrade

Good practice question, when I will apply the 2.3.3 update that fixes this bug, is it recommended to delete the file in my custom theme?

thank you so much
