### ISSUE TITLE
Catalog page is stuck won't allow entry

### ISSUE THREAD

**Issue by PSLionz** [magento/magento2#33539] opened 2021-07-20 15:21 UTC
See the picture below. The Products - Catalog page is stuck trying to refresh. A filter was entered that has jammed the system. I click ok, but the icon continues to refresh, I cannot clear the filter or enter anything on the page. I have logged on/off, used a different browser but no luck. 

Any suggestions on how to clear the filter so I can get back to work is appreciated.

![image](https://user-images.githubusercontent.com/87713150/126350517-b993e009-85c6-4dda-bfe2-1cec28666e51.png)

**Comment by engcom-November** [comment] 2021-07-22 06:26
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible from our end.
**Steps performed:**
Admin -> Catalog ->Products -> Applied Filter by Name or SKU -> No issue: Page is loading as expected with filter applied
Refresh the page -> No issue: Page is loading with filter applied.
![image](https://user-images.githubusercontent.com/60198231/126597358-77ab06e1-c4e6-4fc8-be41-4152369281ab.png)
@PSLionz, We no more have the navigation - Products -> Catalog on Magento 2.4-develop branch (Current behavior: Catalog -> Products). Kindly recheck the issue on Latest Magento version/2.4-develop branch and provide missing steps if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2021-08-05 10:20
@PSLionz, We are closing this issue as there has been no latest update on the same.
Thank you

**Closed as completed by engcom-November** 2021-08-05 10:20 UTC
Labels: Component: Catalog, Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.3.2
