### ISSUE TITLE
Bug re-ordering when no buyRequest found in 2.4.4+

### ISSUE THREAD

**Issue by JamesFX2** [magento/magento2#36103] opened 2022-09-07 09:29 UTC
### Preconditions and environment

- Magento version 2.4.4
- Legacy orders where there is no buyRequest (M1)

### Steps to reproduce

1. Order via customer panel link by clicking a URL such as https://www.example.com/sales/order/reorder/order_id/418443/

### Expected result

1. Re-order process is successful. 

### Actual result

```
[2022-09-07T08:55:47.225975+00:00] main.CRITICAL: TypeError: Magento\Framework\DataObject::__construct(): Argument #1 ($data) must be of type array, null given, called in /home/cloudpanel/htdocs/www.chemist-4-u.com/releases/2022_09_07_4_25_31_branch_v2.4.4-3/vendor/magento/module-sales/Model/Reorder/OrderInfoBuyRequestGetter.php on line 65 and defined in /home/cloudpanel/htdocs/www.chemist-4-u.com/releases/2022_09_07_4_25_31_branch_v2.4.4-3/vendor/magento/framework/DataObject.php:39
Stack trace:
#0 /home/cloudpanel/htdocs/www.example.com/releases/2022_09_07_4_25_31_branch_v2.4.4-3/vendor/magento/module-sales/Model/Reorder/OrderInfoBuyRequestGetter.php(65): Magento\Framework\DataObject->__construct()
#1 /home/cloudpanel/htdocs/www.example.com/releases/2022_09_07_4_25_31_branch_v2.4.4-3/vendor/magento/module-sales/Model/Reorder/Reorder.php(255): Magento\Sales\Model\Reorder\OrderInfoBuyRequestGetter->getInfoBuyRequest()
#2 /home/cloudpanel/htdocs/www.example.com/releases/2022_09_07_4_25_31_branch_v2.4.4-3/vendor/magento/module-sales/Model/Reorder/Reorder.php(217): Magento\Sales\Model\Reorder\Reorder->addItemToCart()
#3 /home/cloudpanel/htdocs/www.example.com/releases/2022_09_07_4_25_31_branch_v2.4.4-3/vendor/magento/module-sales/Model/Reorder/Reorder.php(161): Magento\Sales\Model\Reorder\Reorder->addItemsToCart()
#4 /home/cloudpanel/htdocs/www.example.com/releases/2022_09_07_4_25_31_branch_v2.4.4-3/vendor/magento/module-sales/Controller/AbstractController/Reorder.php(87): Magento\Sales\Model\Reorder\Reorder->execute()
#5 /home/cloudpanel/htdocs/www.example.com/releases/2022_09_07_4_25_31_branch_v2.4.4-3/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Controller\AbstractController\Reorder->execute()
```

### Additional information

Issue is caused by https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Model/Reorder/OrderInfoBuyRequestGetter.php#L49

This needs to have a null coalesce.

```
$info = $orderItem->getProductOptionByCode('info_buyRequest') ?? [];
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by JamesFX2** [comment] 2022-09-07 09:29
It's possible this is a relic of data migration but I feel this should be addressed.

**Comment by engcom-Dash** [comment] 2022-09-13 08:24
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-09-13 08:52
Hi @JamesFX2 ,

We are trying to reproduce the issue in magento 2.4-develop instance.But we are not able to reproduce.

We can able to reorder successfully.

Screenshot:
![Screenshot from 2022-09-13 14-19-53](https://user-images.githubusercontent.com/60198592/189857169-4836bbae-faf0-4429-8255-98b8c9c8dea9.png)

Steps to reproduce:
1. Install Magento instance
2. Go to admin Panel
3. Process reorder
4. Successfully able to reorder .

Let us know if we Missing anything!!!

Thanks!!!

**Comment by engcom-Dash** [comment] 2022-09-14 07:56
Hi @JamesFX2 ,

Thanks for your contribution...

Are you using Custom script or Official script for the Migration process?...May be the issue with Migration From M1 to M2  as well  as this issue is not the Part of core magento.

Shall we close this issue???

Thanks

**Comment by JamesFX2** [comment] 2022-09-15 15:47
I think one of the M1 extensions we used modified product_options to use MEDIUMTEXT and when we used the official script, it truncated the field. We must have done something like UPDATE sales_order_item SET product_options = '' where length(product_options) =... to clear the invalid product options.

Yes, please close this issue.

**Comment by engcom-Dash** [comment] 2022-09-16 09:40
Hi @JamesFX2 ,

This Issue is not the part of Core Magento...So we are Closing the issue.

thanks!!!

**Closed as completed by engcom-Dash** 2022-09-16 09:40 UTC
Labels: Issue: needs update, Reported on 2.4.4

**Comment by monteshot** [comment] 2025-01-09 12:59
It also could be invoked by an incorrect plugin for 
Magento\Quote\Model\Quote\Item
![image](https://github.com/user-attachments/assets/d8a627ca-a497-480b-8efb-0b132ad7b01c)
(You MUST copy all options(at least info_buyRequest) from $result if you want to modify the return value of getProduct method)
