### ISSUE TITLE
[Severity: S1] Default consumer configurations prevents consumers running with Cron. 

### ISSUE THREAD

**Issue by tschirmer** [magento/magento2#35446] opened 2022-05-09 04:36 UTC
### Preconditions (*)
1. Install Magento 2.4.4

### Steps to reproduce (*)
1. install Magento, remove all reference to consumers from env.php and config.php

### Expected result (*)
1. All consumers should be run with cron.

### Actual result (*)
1. No consumers are run with cron.

According to documentation here: https://devdocs.magento.com/guides/v2.4/config-guide/mq/manage-message-queues.html

![image](https://user-images.githubusercontent.com/3872130/167340721-a4c73fe5-af0d-40b7-bdd9-6159ae7b9844.png)

consumers - An array of strings specifying which consumer(s) to run. An empty array runs all consumers.

but if we look at the consumers runner here:
https://github.com/magento/magento2/blob/0f9a056c8d83c4f319626b3e56ec52a533999f25/app/code/Magento/MessageQueue/Model/Cron/ConsumersRunner.php#L121

The default value for allowed consumers is an empty array. No consumers get run if the configuration is empty.

**Comment by tschirmer** [comment] 2022-05-09 10:01
I've continued to look through this code, and there is a line that's meant to achieve this:
https://github.com/magento/magento2/blob/0f9a056c8d83c4f319626b3e56ec52a533999f25/app/code/Magento/MessageQueue/Model/Cron/ConsumersRunner.php#L181

We've had an issue with inventory not marking the product out of stock after reaching 0 saleable qty. We've tracked it to the consumers not running, and until we added the consumer into the config.php / env.php the problem persisted. We're still experiencing the consumers not running unless explicitly specified on 2.4.4

**Comment by LucianMihalache** [comment] 2022-05-09 12:52
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment] 2022-07-20 12:57
Hello @tschirmer,

Thank you for reporting the issue.

We tried to reproduce it on Magento 2.4-dev but the issue is not reproducible.

Steps followed to reproduce issue:

1- Install the fresh Magento 2.4-dev instance.
2- Remove all reference to consumers from env.php and config.php
3- Place order of a product which has 1 quantity remaining.
4- Order is placed
5- Product becomes Out Of Stock after reaching 0

Would be helpful if you could provide the exact steps you followed with a screenshot like checking queues of consumers, any additional steps if you opted facing this issue etc so we can try to reproduce the same at our end.

**Comment by engcom-Echo** [comment] 2022-08-08 09:40
Hello @tschirmer,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Echo** 2022-08-08 09:40 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.4
