### ISSUE TITLE
Global-search icon misaligned 

### ISSUE THREAD

**Issue by SyntaxKay** [magento/magento2#18913] opened 2018-10-29 08:35 UTC
### Preconditions (*)

1.Global search 

### Steps to reproduce (*)

1.Login to admin panel 
2.click on global search

### Expected result (*)

1. ![expacted_result](https://user-images.githubusercontent.com/33230237/47638056-85653000-db83-11e8-9276-6d334a9e4c91.png)

### Actual result (*)

1. ![actual_result](https://user-images.githubusercontent.com/33230237/47637964-3e773a80-db83-11e8-8024-2d6c69750953.png)

**Comment by magento-engcom-team** [comment] 2018-10-29 08:35
Hi @speedy008. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@speedy008 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-10-29 17:20
Hi @speedy008. Thank you for your report. 
The issue has been fixed in magento/magento2#18917 by @speedy008 in 2.2-develop branch
Related commit(s):
 - [3cbc2555af0fda5af46a9c1e619d2ba090c826d2](https://github.com/magento/magento2/commit/3cbc2555af0fda5af46a9c1e619d2ba090c826d2)

The fix will be available with the upcoming 2.2.8 release.

**Closed as completed by magento-engcom-team** 2018-10-29 17:20 UTC
Labels: Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by sidolov** [comment] 2018-11-05 14:22
Hi @speedy008. Thank you for your report. 
The issue has been fixed in magento/magento2#18940 by @speedy008 in 2.3-develop branch
Related commit(s):
 - [b7513494fd58447c4418b4f3d29ea40944548ddb](https://github.com/magento/magento2/commit/b7513494fd58447c4418b4f3d29ea40944548ddb)

The fix will be available with the upcoming 2.3.1 release.
