### ISSUE TITLE
not able to add new category

### ISSUE THREAD

**Issue by akki20000** [magento/magento2#18910] opened 2018-10-28 13:12 UTC
i  have entered category name then also it throw validation error ie name is required .
![image](https://user-images.githubusercontent.com/22708048/47616311-1afbb380-dae1-11e8-8c33-e59e415d7726.png)

### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by magento-engcom-team** [comment] 2018-10-28 13:12
Hi @akki20000. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@akki20000 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by akki20000** [comment] 2018-10-28 13:17
my php version is 7.0.3 and i am using linux ( ubuntu 16 ) and magento version is 2.1.4

**Comment by magento-engcom-team** [comment] 2018-10-28 14:50
Hi @navarr. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by navarr** [comment] 2018-10-28 14:50
#squashtoberfest

**Comment by navarr** [comment] 2018-10-28 14:53
Hi @akki20000,

Magento 2.1 is End-of-Life and is no longer developed.  Can you recreate this issue on the latest version of 2.2 or 2.3?

**Comment by akki20000** [comment] 2018-10-29 02:46
hi navarr,
i have now installed  magento 2.2.5 and also php version  is 7.1    .   then also i am receiving same error .
what is your suggestion . which version of php and mageto2 should i install .

**Comment by vpodorozh** [comment] 2018-11-10 10:43
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment] 2018-11-10 10:43
Hi @vpodorozh. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment] 2018-11-10 10:43
Hi @vpodorozh, here is your [Magento instance](http://34.228.235.121/i-18910-2-2-5/).
Admin access: [http://34.228.235.121/i-18910-2-2-5//admin](http://34.228.235.121/i-18910-2-2-5//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by vpodorozh** [comment] 2018-11-10 10:52
@akki20000 and @navarr - I do see that this issue is not reproduced in Magneto 2.2.5 and also I have not reproduced on my local installation with 2.2.6 and older.
**I'm closing this issue.**
![peek 2018-11-10 12-49](https://user-images.githubusercontent.com/16047928/48300511-6a7dae80-e4e7-11e8-85c9-efd046bf2ea6.gif)

**Closed as completed** 2018-11-10 10:53 UTC
Labels: Progress: needs update, Issue: Format is valid, Event: squashtoberfest

**Comment by akki20000** [comment] 2018-11-10 11:07
Hi all,
I didn't face this issue in firefox.
But i always face issue if i try to add category or product im chrome
browser.
Anyways thanks for your support.
