### ISSUE TITLE
Magento Admin - ERROR: The "store_name" attribute name is invalid & The "website_name" attribute name is invalid

### ISSUE THREAD

**Issue by irshadsheikh3472** [magento/magento2#36721] opened 2023-01-10 12:55 UTC
### Summary

ERROR: Magento\Framework\Exception\LocalizedException: The "store_name" attribute name is invalid. Reset the name and try again. in /var/www/html/vendor/magento/module-eav/Model/Entity/Collection/AbstractCollection.php:1407

ERROR: Magento\Framework\Exception\LocalizedException: The "website_name" attribute name is invalid. Reset the name and try again. in /var/www/html/vendor/magento/module-eav/Model/Entity/Collection/AbstractCollection.php:1407

Magento version 2.4.4 & 2.4.5

**Steps to reproduce**

- Go to sales order
- Click create new order
- Filter by store name or website name

This results in hanging page and in logs I see the error.
<img width="1761" alt="Screenshot 2023-01-10 at 6 16 27 PM" src="https://user-images.githubusercontent.com/97082462/211556366-a07e41ed-2444-4aa2-b913-77dd3808391e.png">

### Examples

**Steps to reproduce**

- Go to sales order
- Click create new order
- Filter by store name or website name

This results in hanging page and in logs I see the error.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-01-10 13:57
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-01-10 14:22
Hi @irshadsheikh3472,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

1.Go to sales order
2.Click create new order
3.Filter by store name or website name.

There is no hanging in  page and no logs.


<img width="1446" alt="Screenshot 2023-01-10 at 7 49 49 PM" src="https://user-images.githubusercontent.com/51680745/211576185-3c40977d-5185-4be5-88c0-b604bc0486dd.png">




Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Kindly let us know if we missed anything.

Thanks.

**Comment by irshadsheikh3472** [comment] 2023-01-10 14:30
Hello @engcom-Bravo,

Can you please check this with version 2.4.4/2.4.5

Thanks.

**Comment by engcom-Bravo** [comment] 2023-01-11 14:07
Hi @irshadsheikh3472,

Thanks for your update.

it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.


We have also verified in both Magento 2.4.4/2.4.5 we are not able to reproduce the issue.

Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.


Thanks.

**Comment by swsavale** [comment] 2023-01-17 17:08
Hello @engcom-Bravo,

Attached is the screen recording of the issue. Worth noting that this issue is happening on enterprise edition 2.4.5-p1

**Steps to reproduce Error 1**
-  The "store_name" attribute name is invalid. Reset the name and try again.
1. Go to Sales > Orders
2. Click "Create New Order"
3. Apply filter on "**Signed-up Point**" column

**Steps to reproduce Error 2**
-  The "website_name" attribute name is invalid. Reset the name and try again.
1. Go to Sales > Orders
2. Click "Create New Order"
3. Apply filter on "**Website**" column

<img width="1441" alt="admin-order-36721" src="https://user-images.githubusercontent.com/49456668/212961603-bb9021a2-2c5e-4f80-b6a9-4aaf234b058f.png">


https://user-images.githubusercontent.com/49456668/212964993-f4a49d99-4f54-4e8f-8aab-fe34bec9ef31.mov


Thanks,
Swapnil

**Comment by swsavale** [comment] 2023-01-17 18:01
Solution: Looks like the issue has been addressed here https://github.com/magento/magento2/blob/d5af5e3362946851b0cd80503a9ea44e9e01ce1b/app/code/Magento/Sales/Model/ResourceModel/Order/Customer/Collection.php#L159-L188

**Comment by engcom-Bravo** [comment] 2023-01-18 12:13
Hi @swsavale @irshadsheikh3472 ,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance with EE edition and the issue is not reproducible.Kindly refer the screenshots.


<img width="1502" alt="Screenshot 2023-01-18 at 2 43 07 PM" src="https://user-images.githubusercontent.com/51680745/213168117-a7003b3f-0a2a-453b-8bec-64c7bc10dbff.png">



<img width="1512" alt="Screenshot 2023-01-18 at 2 43 27 PM" src="https://user-images.githubusercontent.com/51680745/213168152-d472e256-1bc6-4250-8923-89a8292c37c6.png">

 In Logs we are not getting any error.


<img width="1169" alt="Screenshot 2023-01-18 at 2 43 51 PM" src="https://user-images.githubusercontent.com/51680745/213168229-a6a05362-2f5b-466b-aeb2-67c421d3c85e.png">


Kindly recheck the behavior on Magento 2.4-develop instance with EE edition and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by swsavale** [comment] 2023-01-18 14:14
@engcom-Bravo as noted in above comment https://github.com/magento/magento2/issues/36721#issuecomment-1385818703 , I see the solution is available in 2.4-develop branch.

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Model/ResourceModel/Order/Customer/Collection.php

Thank you for your help.. we can close this!

**Comment by engcom-Bravo** [comment] 2023-01-19 08:53
Hi @swsavale,

Thanks for your quick response.

Kindly let us know if you are still facing any issue.


Thanks.

**Comment by engcom-Hotel** [comment] 2023-02-03 12:19
Dear @swsavale,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2023-02-03 12:19 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.4
