### ISSUE TITLE
Customer sent newsletter unsubscribe email when registering for a new account and newsletter confirmation is on

### ISSUE THREAD

**Issue by jammy-git** [magento/magento2#23729] opened 2019-07-16 14:13 UTC
### Preconditions (*)
1. Recreated with Magento versions 2.2.6, 2.2.9 and 2.3.2.
2. Using CentOS and PHP 7.1

### Steps to reproduce (*)
1. Go to the customer/account/create and sign up as a new customer.
2. Ensure the "Sign Up for Newsletter" checkbox IS ticked.
3. Click "Create an account".

### Expected result (*)
1. Customer receives two emails, 1 - the welcome email for registering a new account and 2 - the email for confirming their newsletter subscription
2. After confirming their subscription, the customer should then receive a third email to state that their subscription to the newsletter has been confirmed.

### Actual result (*)
1. Customers firstly receives an email to state that they have been successfully UNsubscribed from the newsletter.
2. Followed by the welcome email and the email with the newsletter confirmation link.

**Comment by jammy-git** [comment] 2019-07-16 14:18
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-16 14:18
Hi @jammy-git. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-16 14:19
Hi @jammy-git, here is your [Magento instance](https://i-23729-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23729-2-3-develop.instances.magento-community.engineering/admin](https://i-23729-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jammy-git** [comment] 2019-07-16 14:32
Tried to recreate the issue with the given Magento instance, however it seems that emails are not sent out with these instances?

**Comment by edenduong** [comment] 2019-07-16 22:49
@engcom-Charlie I can reproduce and resolved it in Pull Request: https://github.com/magento/magento2/pull/23737

**Comment by magento-engcom-team** [comment] 2019-07-16 22:51
@edenduong Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-08-20 20:38
Hi @jammy-git. Thank you for your report. 
The issue has been fixed in magento/magento2#23737 by @edenduong in 2.3-develop branch
Related commit(s):
 - [8604be9b3423be18038ef0c13b3830e5cc58b9d1](https://github.com/magento/magento2/commit/8604be9b3423be18038ef0c13b3830e5cc58b9d1)
 - [fc1687b0353c1f337b7f45c6977512f134590887](https://github.com/magento/magento2/commit/fc1687b0353c1f337b7f45c6977512f134590887)
 - [f25dfd334e1fed629430315181eb0bcd5e97f348](https://github.com/magento/magento2/commit/f25dfd334e1fed629430315181eb0bcd5e97f348)

The fix will be available with the upcoming 2.3.4 release.

**Comment by wittyvishwas** [comment] 2020-02-18 10:29
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-18 10:29
Hi @wittyvishwas. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by wittyvishwas** [comment] 2020-02-18 14:25
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-18 14:25
Hi @wittyvishwas. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by wittyvishwas** [comment] 2020-02-19 04:32
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-19 04:32
Hi @wittyvishwas. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by engcom-Alfa** [comment] 2020-02-19 13:52
Hi @jammy-git @wittyvishwas.
Unfortunately, we are not able to reproduce this issue on fresh 2.4 develop and 2.3.4-version.

**Actual Result:**
The customer receives two emails:
1. Welcome to  Website Store;
2. Newsletter subscription confirmation;
After confirmation, we received the third letter:
Newsletter subscription success

So, we have to close it.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-02-19 13:52 UTC
Labels: Component: Customer, Issue: Clear Description, Fixed in 2.3.x, Issue: Format is valid

**Comment by konarshankar07** [comment] 2020-03-23 12:25
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-23 12:25
Hi @konarshankar07. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by paul-gene** [comment] 2020-05-28 14:28
I am still getting this issue in 2.3.4

**Comment by LukasKiederle** [comment] 2020-06-03 14:33
I can also testify that in Magento 2.3.5 the bug was induced by #23737. Reverting the changes fixed it.
Thanks @paul-gene for the hint.

**Comment by paul-gene** [comment] 2020-06-03 14:35
@LukasKiederle I opened a ticket here, https://github.com/magento/magento2/issues/28419

Any idea how I can resolve for 2.3.4?

**Comment by LukasKiederle** [comment] 2020-06-03 14:44
I cannot really test it by myself now. My guess would be since reverting #23737 fixed it for 2.3.3 and 2.3.5 it fixes it also for 2.3.4?

**Comment by paul-gene** [comment] 2020-06-03 14:46
@LukasKiederle yes, but I can't simply revert the commit when I'm installing Magento via Composer. I'd need a patch file of the reversion...

**Comment by LukasKiederle** [comment] 2020-06-03 14:49
I created one myself. See the attached file
[revert.txt](https://github.com/magento/magento2/files/4724161/revert.txt)

**Comment by paul-gene** [comment] 2020-06-03 14:51
I tried reverting that single file manually, and I'm sure I encountered other issues. In my case, I'm dealing with the account confirmation as well

**Comment by LukasKiederle** [comment] 2020-06-03 14:57
When I apply the revert.txt file everything works fine. I can confirm the newsletter subscription as well as the customer registration.

**Comment by paul-gene** [comment] 2020-06-03 15:00
@LukasKiederle try enabling "Require Emails Confirmation" for customer accounts and re-testing.

**Comment by LukasKiederle** [comment] 2020-06-03 15:05
Customer Configuration -> Create Account Options -> Require Emails Confirmation is enabled in my Magento instance

**Comment by paul-gene** [comment] 2020-06-03 15:06
I'll try the revert patch on my end and report back

**Comment by sazo17** [comment] 2020-06-07 17:57
I applied the revert.txt in my magento 2.3.4 and it works, but when a client creates his account he enters it without needing to confirm it, in my store I have activated the account confirmation and the confirmation email if it arrives, but when creating the account the clients access directly to your profile without confirming it

**Comment by paul-gene** [comment] 2020-06-07 19:13
@sazo17 so the patch file doesn't work properly?

**Comment by sazo17** [comment] 2020-06-07 21:55
correct because if I check the box when creating an account, confirm the account, it does not wait for the client to confirm the account in their email

**Comment by paul-gene** [comment] 2020-06-08 08:00
@LukasKiederle seems that your patch might not be the solution?

**Comment by LukasKiederle** [comment] 2020-06-09 07:36
I will check again

**Comment by LukasKiederle** [comment] 2020-06-09 07:45
I can confirm the statement from @sazo17 . The revert.txt does not fix the problem completely. The customer doesn't have to confirm the email when account confirmation is activated.

**Comment by JAG007** [comment] 2020-07-03 19:18
This issue has not been ressoved.
I am using a clean copy of 2.3.5p1
It only happens if in Configuration > Customer Configuration > Create Account Options > Require Emails Confirmation is set to Yes

**Comment by ryanfern86goa** [comment] 2020-07-22 09:32
Hi @JAG007 

I'm facing the same issue on 2.3.4-p2

**Comment by chdzma** [comment] 2020-08-13 11:40
The bug still exists with 2.3.5. Any solution?

**Comment by shigawaka** [comment] 2020-09-01 07:03
Issue still exists in 2.3.5 p2

**Comment by lopezpaul** [comment] 2020-09-30 08:09
Create a new file  m2-hotfixes/newsletter.patch  with this content:

diff --git a/vendor/magento/module-customer/Controller/Account/CreatePost.php b/vendor/magento/module-customer/Controller/Account/CreatePost.php
index 7544e6d..9845791 100755
--- a/vendor/magento/module-customer/Controller/Account/CreatePost.php
+++ b/vendor/magento/module-customer/Controller/Account/CreatePost.php
@@ -358,18 +358,20 @@ class CreatePost extends AbstractAccount implements CsrfAwareActionInterface, Ht
             $redirectUrl = $this->session->getBeforeAuthUrl();
             $this->checkPasswordConfirmation($password, $confirmation);
 
-            $extensionAttributes = $customer->getExtensionAttributes();
-            $extensionAttributes->setIsSubscribed($this->getRequest()->getParam('is_subscribed', false));
-            $customer->setExtensionAttributes($extensionAttributes);
-
             $customer = $this->accountManagement
                 ->createAccount($customer, $password, $redirectUrl);
-
+            $confirmationStatus = $this->accountManagement->getConfirmationStatus($customer->getId());
+            $isSuscribed = $this->getRequest()->getParam('is_subscribed', false);
+            if($isSuscribed==1) {
+                $extensionAttributes = $customer->getExtensionAttributes();
+                $extensionAttributes->setIsSubscribed($isSuscribed);
+                $customer->setExtensionAttributes($extensionAttributes);
+                $this->customerRepository->save($customer);
+            }
             $this->_eventManager->dispatch(
                 'customer_register_success',
                 ['account_controller' => $this, 'customer' => $customer]
             );
-            $confirmationStatus = $this->accountManagement->getConfirmationStatus($customer->getId());
             if ($confirmationStatus === AccountManagementInterface::ACCOUNT_CONFIRMATION_REQUIRED) {
                 $this->messageManager->addComplexSuccessMessage(
                     'confirmAccountSuccessMessage',
@@ -392,6 +394,7 @@ class CreatePost extends AbstractAccount implements CsrfAwareActionInterface, Ht
                 }
                 $resultRedirect = $this->accountRedirect->getRedirect();
             }
+
             if ($this->getCookieManager()->getCookie('mage-cache-sessid')) {
                 $metadata = $this->getCookieMetadataFactory()->createCookieMetadata();
                 $metadata->setPath('/');

Run the following command to apply in your local environment
patch -p1 < m2-hotfixes/newsletter.patch
for cloud environments add this to your composer.json file, find your extra section and add 
        "composer-exit-on-patch-failure": true,
        "patches": {
            "magento/module-customer": {
                "Unsuscribe email: Customer sent newsletter unsubscribe email when registering for a new account": "m2-hotfixes/newsletter.patch"
            }
        }

**Comment by flamboy** [comment] 2021-01-26 15:55
I see the subscription model was totally refactored at 2.4.* 
For those guys who still receive unsubscribe email -> here diff from 2.3.4
[magento_module-newsletter.diff.txt](https://github.com/magento/magento2/files/5874444/magento_module-newsletter.diff.txt)

FYI: if `Configuration > Customer Configuration > Create Account Options > Require Emails Confirmation` is set to `Yes` then subscription email will come with `account_new_confirmed.html` email (after account confirmation)

**Comment by carylewis** [comment] 2021-02-12 19:39
We are seeing this error in 2.3.5p2 and applying the magento_module-newsletter.diff.txt patch did not resolve the issue.
