### ISSUE TITLE
IE11 - Checkbox does not work correctly when adding products to a new sales order through the admin site

### ISSUE THREAD

**Issue by david-gorecki** [magento/magento2#12855] opened 2017-12-21 21:57 UTC
### Preconditions
1. Magento 2 Opensource version 2.2.1
2. Specific to IE11 (have not checked other IE versions)

### Steps to reproduce
1. Open the Admin site using the IE11 browser and sign in
2. Click Sales > Orders in the left nav
3. Click Create New Order
4. Select a Customer (for the purposes of this example, I used the sample customer Veronica Costello)
5. On the "Select store" page, select the Default Store View
6. On the Create Order Page, click the Add Products button
7. Select the checkbox for any item
8. Issue Here - the quantity field should enable and the checkbox should display as "checked"; in IE11, it does not (it DOES when using Chrome).  Important note - if you click elsewhere on the row, the checkbox DOES get checked in IE, it only fails to get checked when you click on the actual checkbox itself.  

### Expected result
1. When you click the checkbox in IE, the following should occur:
a. The checkbox should become checked
b. The quantity field should be enabled
c. A value of 1 should populate in the quantity field

### Actual result
1. The quantity field is populated with a value of 1, but the checkbox is not selected and the quantity field does not enable:

![image](https://user-images.githubusercontent.com/32939674/34276488-9f088430-e66f-11e7-8620-f7522900926c.png)

**Comment by magento-engcom-team** [comment] 2017-12-26 13:41
@david-gorecki, thank you for your report.
We've created internal ticket(s) MAGETWO-86003 to track progress on the issue.

**Comment by magento-engcom-team** [comment] 2018-11-30 05:20
Hi @niravkrish. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by drpayyne** [comment] 2019-10-06 07:51
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-10-06 07:51
Hi @drpayyne. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-10-06 07:52
Hi @drpayyne, here is your [Magento instance](https://i-12855-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-12855-2-3-develop.instances.magento-community.engineering/admin](https://i-12855-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by drpayyne** [comment] 2019-10-06 08:41
@engcom-Alfa @engcom-Bravo This issue is reproducible on IE11 as reported. Although upon extensive inspection of the checkbox on IE11, FirefoxDev70, and Chromium77. This is what's happening on each major (apart from IE) browser.

- **IE11**
![Screenshot from 2019-10-06 14-00-31](https://user-images.githubusercontent.com/22623301/66266482-4df70d00-e843-11e9-99f0-a7017b520187.png)
Here, clicking outside the checkbox works but _not inside or on the immediate right_ since parent div extends from the left (where the input field resides), through the square box and to the immediate right.

- **FirefoxDev70**
![Screenshot from 2019-10-06 14-00-31](https://user-images.githubusercontent.com/22623301/66266377-f4421300-e841-11e9-89c9-0f007381b8e7.png)
Here, clicking outside the checkbox works, and inside too, but _only in the top left_ where the input element actually resides (highlighted in image)
- **Chromium77**
![Screenshot from 2019-10-06 14-05-11](https://user-images.githubusercontent.com/22623301/66266420-6b77a700-e842-11e9-89d9-d4cc7d56ff76.png)
Here, clicking outside the checkbox works, and inside too, but _not in the bottom and right edges_ where the input element actually ends and is absent (highlighted in image)


Considering the inspection and difference in browser implementation and sparse usage of IE11, is it worth it if I attempt to resolve this issue?

**Comment by engcom-Bravo** [comment] 2019-10-07 12:04
Hi, @drpayyne. If the issue exists, i.e. is reproducible we can not close it just because it rarely reveals itself. So if You could and wished to fix it that would be good. We would appreciate that. Thank You.

**Comment by magento-engcom-team** [comment] 2019-10-30 19:23
Hi @david-gorecki. Thank you for your report. 
The issue has been fixed in magento/magento2#24913 by @drpayyne in 2.3-develop branch
Related commit(s):
 - [94512cf73f1e2bd4652676565988d4c430b438ba](https://github.com/magento/magento2/commit/94512cf73f1e2bd4652676565988d4c430b438ba)

The fix will be available with the upcoming 2.3.4 release.

**Closed as completed by magento-engcom-team** 2019-10-30 19:23 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Admin
