### ISSUE TITLE
Number of address lines (street lines) in admin

### ISSUE THREAD

**Issue by Litiano** [magento/magento2#2450] opened 2015-11-20 20:38 UTC
Setting # 4 the number of address lines, but admin appear only 2 lines.
![street1](https://cloud.githubusercontent.com/assets/8152537/11311261/73c0f21e-8fad-11e5-994e-5ad7af9ccdef.JPG)
![street2](https://cloud.githubusercontent.com/assets/8152537/11311263/73c494a0-8fad-11e5-80ca-0a05c3a88297.JPG)

**Comment by sevos1984** [comment] 2015-12-25 10:42
Internal issue created with id MAGETWO-47376. Thanks for reporting.

**Comment by slavvka** [comment] 2016-02-04 11:46
Hi @Litiano, the fix has been delivered to mainline (see 4956b2a).

**Closed as completed by slavvka** 2016-02-04 11:46 UTC
Labels: bug report, Progress: accept

**Comment by mikebranderhorst** [comment] 2016-02-19 23:14
"Leave empty for default (2)"

After migrating, this field was empty for us in adminhtml. It should show 2 lines on frontend. Instead it shows no lines.

core_config_data customer/address/street_lines NULL

If the field is filled with a value, now it shows the correct lines.

"Valid range: 1-4"

If I use "5" as value, this is accepted (shouldn't) it also show 5 lines on frontend. Value "0" is also accepted and show no lines on frontend.

Now, there is no html5 not javascript validation on this field. I think adminhtml should validate on save and leave value empty if value is not valid 1-4.

**Comment by PascalBrouwers** [comment] 2016-08-30 13:02
@slavvka  Seems this bug is still present in magento 2.1.0
I set "Number of Lines in a Street Address" to 1, yet in the checkout is shows 2 lines.

**Comment by girishassudanizeon** [comment] 2017-04-20 16:04
I am using magento 2.1.5, the issue is i am not able to see the setting in magento to set the Number of Lines in street address.. Does any one encounter such issue?

**Comment by rodrigowebjump** [comment] 2017-05-09 17:38
Hi I also did not see anymore the option to set the number of lines in the admin.

Store->Configuration->Customer Configuration->Name and Address Options

**Comment by samgranger** [comment] 2017-08-04 14:39
I have also encountered the issue that 'Number of Lines in a Street Address' is missing.

It appears that in my case, this is due to being an Enterprise installation. The EE module 'Customer Custom Attributes' removes the street lines from the previously mentioned Customer Configuration.

For EE, this has moved to Stores => Attributes => Customer Address. You can find the Street attribute & modify the  Lines Count there. The current EE street line range is 2-20 compared to CE's range of 1-4.

To get around this issue, in case you only want 1 line in EE, you can set the following path value to 1 in core_config_data: customer/address/street_lines

**Comment by rodrigowebjump** [comment] 2017-08-07 13:42
Hi Sam,

Thanks for the information

**Comment by samgranger** [comment] 2017-08-07 21:00
Excuse me, but what I said was incorrect, the number of street lines can be edited in customer_eav_attribute - you can edit it to one there, in the multiline_column column (make sure you edit it for the correct attribute ID).

!!Please do this on a test environment and make sure everything is still working as intended before applying to live!!
