### ISSUE TITLE
async rest api product can't set some stock_item fields

### ISSUE THREAD

**Issue by scne** [magento/magento2#25953] opened 2019-12-08 19:34 UTC
### Preconditions
1. magento 2.3.1 CE
2. PHP 7.1.29
3. elasticsearch 5

### Steps to reproduce (*)
update product via REST API with a PUT request. Some `stock_item` settings never changed 

To reproduce this issue try to perform a PUT request with this body

```
{
	"product": {
		"sku": "product_code",
		"attribute_set_id": 4,
		"status": 1,
		"type_id": "simple",
		"visibility": 4,
		"extension_attributes": {
			"stock_item": {
				qty: 200,
                                is_in_stock: true,
                                is_qty_decimal: false,
                                enable_qty_increments:  true,
                                min_sale_qty:  20,
                               qty_increments: 20,
                               use_config_min_sale_qty: 0,
                               use_config_enable_qty_inc: false,
                               use_config_qty_increments: false,
			}
		}
	}
}
```

### Expected result (*)
Updating of stock item related to product sku via PUT request with **min_sale_qty** and **qty_increments** set up correctly.

### Actual result (*)

```
"stock_item": {
	"item_id": 99658,
	"product_id": 99704,
	"stock_id": 1,
	"qty": 200,
	"is_in_stock": true,
	"is_qty_decimal": false,
	"show_default_notification_message": false,
	"use_config_min_qty": true,
	"min_qty": 0,
	"use_config_min_sale_qty": 1,
	"min_sale_qty": 1,
	"use_config_max_sale_qty": true,
	"max_sale_qty": 10000,
	"use_config_backorders": true,
	"backorders": 1,
	"use_config_notify_stock_qty": true,
	"notify_stock_qty": 0,
	"use_config_qty_increments": true,
	"qty_increments": 1,
	"use_config_enable_qty_inc": true,
	"enable_qty_increments": true,
	"use_config_manage_stock": true,
	"manage_stock": true,
	"low_stock_date": null,
	"is_decimal_divided": false,
	"stock_status_changed_auto": 0
  }
}

```

**Comment by engcom-Echo** [comment] 2019-12-09 16:12
Hello @scne 

Thank you for your report and collaboration!
I am not able to reproduce this issue on the 2.4-develop branch by provided steps.

**Testing scenario:**

**Preconditions:**

1. PHP 7.2
2. Elasticsearch 6

**Steps to reproduce:**
1. Update product via REST API with a PUT request.  
`V1/products/<Product_SKU>`
2. Run the PUT request with this body
```
{
	"product": {
		"sku": "24-WG01",
		"attribute_set_id": 4,
		"status": 1,
		"type_id": "simple",
		"visibility": 4,
		"extension_attributes": {
			"stock_item": {
				"qty": 200,
                                "is_in_stock": true,
                                "is_qty_decimal": false,
                                "enable_qty_increments":  true,
                                "min_sale_qty":  50,
                               "qty_increments": 50,
                               "use_config_min_sale_qty": 0,
                               "use_config_enable_qty_inc": false,
                               "use_config_qty_increments": false
			}
		}
	}
}
```

**Result**
Updating of stock item related to product sku via PUT request with min_sale_qty and qty_increments set up correctly.
```
"stock_item":{
        "item_id": 53,
        "product_id": 49,
        "stock_id": 1,
        "qty": 200,
        "is_in_stock": true,
        "is_qty_decimal": false,
        "show_default_notification_message": false,
        "use_config_min_qty": true,
        "min_qty": 0,
        "use_config_min_sale_qty": 0,
        "min_sale_qty": 50,
        "use_config_max_sale_qty": true,
        "max_sale_qty": 10000,
        "use_config_backorders": true,
        "backorders": 0,
        "use_config_notify_stock_qty": true,
        "notify_stock_qty": 1,
        "use_config_qty_increments": false,
        "qty_increments": 50,
        "use_config_enable_qty_inc": false,
        "enable_qty_increments": true,
        "use_config_manage_stock": true,
        "manage_stock": true,
        "low_stock_date": null,
        "is_decimal_divided": false,
        "stock_status_changed_auto": 0
	}
```

So I have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Echo** 2019-12-09 16:12 UTC
Labels: Issue: Format is valid

**Comment by scne** [comment] 2019-12-09 22:00
The issue is related to the async request. Standard PUT request works also
in my scenario. Please can you consider to perform an async request in
order to evaluate this issue?

**Comment by engcom-Echo** [comment] 2019-12-10 10:36
Hello @scne 

I am not able to reproduce this issue on the 2.4-develop branch by provided steps.
**Steps to reproduce:**
1. Update product via REST API with a PUT request. `domain.com/rest/default/async/V1/products/Product_sku`
2. Run the PUT request with this body
```
{
	"product": {
		"sku": "Product",
		"attribute_set_id": 4,
		"status": 1,
		"type_id": "simple",
		"visibility": 4,
		"extension_attributes": {
			"stock_item": {
				"qty": 200,
                                "is_in_stock": true,
                                "is_qty_decimal": false,
                                "enable_qty_increments":  true,
                                "min_sale_qty":  10,
                               "qty_increments": 10,
                               "use_config_min_sale_qty": 0,
                               "use_config_enable_qty_inc": false,
                               "use_config_qty_increments": false
			}
		}
	}
}
```
**Result**
Updating of stock item related to product sku via PUT request with min_sale_qty and qty_increments set up correctly. Status: 202 Accepted
```
{
    "bulk_uuid": "some-uuid",
    "request_items":[
                                {
                                   "id": 0,
                                   "data_hash": "someHash",
                                    "status": "accepted"
                                }
                             ],
    "errors": false
}
```
The "cataloginventory_stock_item" table is updated correctly.
![Screenshot from 2019-12-10 12-08-05](https://user-images.githubusercontent.com/51681435/70520783-c087b000-1b46-11ea-887b-75f5956f4b09.png)
![Screenshot from 2019-12-10 12-08-17](https://user-images.githubusercontent.com/51681435/70520787-c2517380-1b46-11ea-85a4-ec115a61c892.png)
It is not possible to add an item to the cart if the selected quantity is less than 10.
![Screenshot from 2019-12-10 12-16-00](https://user-images.githubusercontent.com/51681435/70521234-89fe6500-1b47-11ea-90db-a553f4b44471.png)

Try to upgrade to the latest magento version.
Thank you!
