### ISSUE TITLE
Extending blockVariables removes existing entries

### ISSUE THREAD

**Issue by schmengler** [magento/magento2#31468] opened 2020-12-27 21:49 UTC
### Summary (*)

It is possible to add block variables to the templates using `di.xml`. Let's say I want to add a variable `$fishMarket`, similar as `$escaper` and `$block`, I can do the following:

```
    <type name="Magento\Framework\View\TemplateEngine\Php">
        <arguments>
            <argument name="blockVariables" xsi:type="array">
                <item name="fishMarket" xsi:type="object">Hamburg\FishMarket</item>
            </argument>
        </arguments>
    </type>
```

However, instead of adding the variable as item to the `blockVariables` array, this overrides the whole array, so that `$block`  and `$escaper` are not available anymore. It doesn't matter if I use `etc/di.xml` or `frontend/etc/di.xml`, the outcome is the same.

### Examples (*)

The Magento_Csp module faced the same issue and as a workaround re-adds the variables from the framework:

```
    <type name="Magento\Framework\View\TemplateEngine\Php">
        <arguments>
            <argument name="blockVariables" xsi:type="array">
                <item name="csp" xsi:type="object">Magento\Csp\Api\InlineUtilInterface\Proxy</item>
                <item name="secureRenderer" xsi:type="object">Magento\Framework\View\Helper\SecureHtmlRenderer\Proxy</item>
                <item name="escaper" xsi:type="object">Magento\Framework\Escaper</item>
            </argument>
        </arguments>
    </type>
```

Of course this is not a real solution, only one module can decide this way and we do not have the exensibility we are used to from Magento's XML configuration.

### Proposed solution

I don't know yet, why exactly this happens but it's obviously not intended. In other places, array arguments can be extended without problems, e.g. in `\Magento\Framework\Console\CommandList`.

So I propose to recognize this as a bug, find the cause and fix it.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by schmengler** [comment] 2020-12-27 21:51
Addition regarding "forces users to employ a workaround": The current workaround is to create a plugin on `Magento\Framework\View\TemplateEngine\Php::render()` instead of using DI configuration.

**Comment by engcom-Delta** [comment] 2021-01-27 20:57
Hi @schmengler thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Manual testing scenario:**

- Create custom module:
`Foo/Bar/etc/di.xml`
```
<type name="Magento\Framework\View\TemplateEngine\Php">
        <arguments>
            <argument name="blockVariables" xsi:type="array">
                <item name="fishMarket" xsi:type="object">Foo\Bar\Variable\Test</item>
            </argument>
        </arguments>
    </type>
```

- Set breakpoint in `__construct` method of  `\Magento\Framework\View\TemplateEngine\Php`
- Go to Home Page/Catalog Page
- Check debug

**Result:**
:heavy_check_mark: Custom variable is added into array. Magento variables are present in array
![image](https://user-images.githubusercontent.com/51681379/106041065-fe95b980-60e3-11eb-9686-344a90ef961a.png)

Are you able to reproduce this issue on 2.4-develop?

**Comment by schmengler** [comment] 2021-01-29 12:17
@engcom-Delta I can't test on 2.4-develop right now, will see how it is with 2.4.2. But if it works that means, the following lines in the core are redunant now: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Csp/etc/di.xml#L81-L82

@AlexMaxHorkun you might want to check this out

**Comment by schmengler** [comment] 2021-05-14 08:46
It still occurs on 2.4.2-p1 and the Magento_Csp module still contains the workaround on 2.4-develop

**Comment by engcom-Hotel** [comment] 2021-06-10 15:11
Hi @schmengler ,

We have tried to reproduce this issue in both Magento CLI 2.4.2-p1 and Magento CLI dev-2.4-develop but unable to reproduce this issue with below steps:

Step 1: Create a new module
Step 2: Create di.xml with blockVariables like below:
             <argument name="blockVariables" xsi:type="array">
                <item name="bravo" xsi:type="object">Learning\FirstUnit\Variable\Test</item>
            </argument>
Step 3: Run with xdebug with breakpoint on Php.php line number 48 ($this->blockVariables = $blockVariables;)

This is displaying all the variables. Please refer the screenshot.
<img width="728" alt="Screenshot 2021-06-10 at 8 15 32 PM" src="https://user-images.githubusercontent.com/51681618/121549961-ec317200-ca2b-11eb-9b29-48ee2e003eaa.png">

Please let us know if we missed anything.

**Comment by engcom-Hotel** [comment] 2021-06-24 06:19
Hi @schmengler 

I hope that your issue is resolved because we did not get any update on this since 14 days. Hence closing the ticket.

Please feel free to raise the new ticket if you have any other issue. We will be happy to work for you.

**Closed as completed by engcom-Hotel** 2021-06-24 06:19 UTC
Labels: Triage: Dev.Experience, Issue: needs update

**Comment by schmengler** [comment] 2021-06-24 07:50
@engcom-Hotel  Please don't just test in the constructor, test what actually is available in the template.

If it would work, this workaround in the CSP module would not be necessary: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Csp/etc/di.xml#L81-L82 - the fact it is still there proves my point.
