### ISSUE TITLE
Unable to see theme in my installtions

### ISSUE THREAD

**Issue by shahrukhkhan-web-designer** [magento/magento2#26805] opened 2020-02-11 04:08 UTC
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by shahrukh1998** [comment] 2020-02-11 04:14
NOt showing them in admin panel
when click on theme configuration it shows blank page or sometime err-response time
Unable to do find theme in content theme

**Comment by engcom-Alfa** [comment] 2020-02-12 08:23
Hi, @shahrukh1998. Thank you for your report.

Unfortunately, we are not able to reproduce the issue described in your [comment](https://github.com/magento/magento2/issues/26805#issuecomment-584471555) on clean 2.4-develop and 2.3.4 version. All works correctly.

**Actual Result:**
![screen2](https://user-images.githubusercontent.com/51679138/74316074-765abf00-4d81-11ea-831c-56f3b48a2a8c.gif)

So, we have to close it.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-02-12 08:23 UTC
Labels: Issue: Format is valid
