### ISSUE TITLE
Magento2 Impossible to update custom option value based on custom option SKU

### ISSUE THREAD

**Issue by parekhreena** [magento/magento2#23601] opened 2019-07-07 07:25 UTC
### Preconditions (*)
Magento 2.4-develop

### Steps to reproduce (*)
- Create product with Customizable Options:
- ![#23601IssueProduct](https://user-images.githubusercontent.com/51681379/61936983-87cfab80-af96-11e9-9042-e944ae310eaf.png)
- Check `option_type_id` in table `catalog_product_option_type_value`
- Export this product
- Edit in csv file custom options title and/or price
- Save scv file and import it
- Check `option_type_id` in table `catalog_product_option_type_value`
### Expected result (*)
Value `option_type_id` is not changed when row is updated
### Actual result (*)
`option_type_id` has new value for rows that were updated

**Note:** No visible impact in admin panel or storefront. There is contradiction behavior between edit custom option from admin panel and from import csv file: when custom option is edited from admin panel than `option_type_id` remain the same. More info in `Description` section

# Description
If a custom option has been assigned a unique SKU, and when a custom option import is done through core-magento to update label or price for instance using SKU as an identifier, Magento will try to import new custom option instead of existing one. This is happening because at the time of import, instead of fetching ID for existing SKU from catalog_product_option_type_value and updating values based on that ID, magento simply deletes all custom-options against that product and tries to import from CSV as new custom options. This also changes the id of custom options.

**Comment by engcom-Delta** [comment] 2019-07-26 08:22
**Steps to reproduce:**
- Create product with Customizable Options:
- ![#23601IssueProduct](https://user-images.githubusercontent.com/51681379/61936983-87cfab80-af96-11e9-9042-e944ae310eaf.png)
- Check `option_type_id` in table `catalog_product_option_type_value`
- Export this product
- Edit in csv file custom options title and/or price
- Save scv file and import it
- Check `option_type_id` in table `catalog_product_option_type_value`

:heavy_check_mark: **Expected result:**
Value `option_type_id` is not changed when row is updated
:x: **Actual result:**
`option_type_id` has new value for rows that were updated

**Comment by magento-engcom-team** [comment] 2019-07-26 08:23
@engcom-Delta Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-07-26 08:26
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18653` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magelogger** [comment] 2019-09-27 09:48
@magento I am working on it

**Comment by magento-engcom-team** [comment] 2020-06-25 10:41
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35452` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Echo** [comment] 2020-11-11 16:10
Hi, @parekhreena
During import for identification "Customizable Option Type" we using the title. The 'title' is a required field unlike "sku" which is why this field is used for comparе. We can't use 'option_type_id' on import file.

This issue can't reproduce if we not change the title. @engcom-Delta please check this case.

**Comment by engcom-Delta** [comment] 2020-11-12 11:20
@engcom-Echo issue is not reproducible if option's `price` or `sku` are changed. It is reproducible in case when option's `option_title` was changed

**Comment by engcom-Echo** [comment] 2020-12-02 08:17
Hi, @parekhreena thank you for your report.

When importing data from an external source, there is no possibility to define IDs. When you are exporting and then re-importing it, it sounds as the ID should be there and should be kept, but if importing data from an external source it is impossible.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for your collaboration.

**Closed as completed by engcom-Echo** 2020-12-02 08:17 UTC
Labels: Issue: Ready for Work, Component: ImportExport, Issue: Confirmed, Issue: Format is valid, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P2, Severity: S3, Progress: done, CD

**Comment by magento-engcom-team** [comment] 2020-12-02 08:20
Hi @parekhreena, @engcom-Echo. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-18653` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.2` release.
