### ISSUE TITLE
Can't create a new store view in admin 2.4.7-p2

### ISSUE THREAD

**Issue by eBusinessAtlantique** [magento/magento2#39171] opened 2024-09-14 12:25 UTC
### Preconditions and environment

- Magento version : 2.4.7-p2
- Fresh install of magento and basic settings to operate.
- a few modules already installed on other instances
- a PORTO theme latest version

### Steps to reproduce

Go to All stores in admin
Try to create a second store view.
Error message is : Something went wrong while scheduling operations.
And no store view is created.

### Expected result

The creation of the store view

### Actual result

Error message is : Something went wrong while scheduling operations.
And no store view is created.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by eBusinessAtlantique** [comment] 2024-09-14 12:26
@magento give me 2.4-develop instance

**Comment by eBusinessAtlantique** [comment] 2024-09-14 12:29
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-09-17 07:16
Hi @eBusinessAtlantique,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

We are able to create the storeview.

<img width="1434" alt="Screenshot 2024-09-17 at 11 57 56" src="https://github.com/user-attachments/assets/60a22600-9c5b-4833-b961-20dd1196624a">


Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible and also check if any third party modules causing this issue.

Thanks.

**Comment by eBusinessAtlantique** [comment] 2024-09-17 21:26
@magento give me 2.4-develop instance

**Comment by eBusinessAtlantique** [comment] 2024-09-18 22:14
> Hi @eBusinessAtlantique,
> 
> Thanks for your reporting and collaboration.
> 
> We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.
> 
> We are able to create the storeview.
> <img alt="Screenshot 2024-09-17 at 11 57 56" width="1434" src="https://private-user-images.githubusercontent.com/51680745/368033479-60a22600-9c5b-4833-b961-20dd1196624a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MDg2MjMsIm5iZiI6MTcyNjYwODMyMywicGF0aCI6Ii81MTY4MDc0NS8zNjgwMzM0NzktNjBhMjI2MDAtOWM1Yi00ODMzLWI5NjEtMjBkZDExOTY2MjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDIxMjUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxOTNjNzk5YWJlYjI1YjFmZTVjNjBkZGY0MTU3MGE4MTI3NDlmMTZhNjU1NDkzM2UyMjkzYjg4Zjg3MWZkZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fWjqoKX2MSafv-A56CAOhuXAI-kCgVWwekQMbTB1adU">
> 
> Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible and also check if any third party modules causing this issue.
> 
> Thanks.

Steps to reproduce is altered to :
Go to All stores in admin
**Create a new store (same website)**
Try to create a second store view.
Error message is : Something went wrong while scheduling operations.
And no store view is created.

**Comment by eBusinessAtlantique** [comment] 2024-09-18 22:15
https://github.com/magento give me 2.4-develop instancehttps://github.com/magento give me 2.4-develop instance

**Comment by eBusinessAtlantique** [comment] 2024-09-18 22:16
@magento give me 2.4-develop instance

**Comment by eBusinessAtlantique** [comment] 2024-09-18 22:22
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-09-19 07:23
Hi @eBusinessAtlantique,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.



https://github.com/user-attachments/assets/2b056d0e-8db2-4e26-90a7-080444783836





We are able to create the store view successfully.


Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible and also check if any third party modules causing this issue.

Thanks.

**Comment by eBusinessAtlantique** [comment] 2024-09-19 14:44
Thanks, good to see it works on out of the box Magento.
I will look for why it is not working on my version with modules. I will update this thread.
Best regards

**Comment by engcom-Bravo** [comment] 2024-09-20 06:15
Hi @eBusinessAtlantique,

Thanks for your update.
 
As per this comment https://github.com/magento/magento2/issues/39171#issuecomment-2361209229 we are closing this issue.since it is working fine in Latest 2.4-develop magento.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-09-20 06:15 UTC
Labels: Issue: needs update, Reported on 2.4.7-p2

**Comment by chrisastley** [comment] 2024-12-17 14:56
@eBusinessAtlantique did you find anything for this error? I have the same issue.

**Comment by eBusinessAtlantique** [comment] 2024-12-17 15:25
Do you have modules from mageplaza ? their reports module ?

**Comment by chrisastley** [comment] 2024-12-17 15:32
Yes. Reports Ultimate.

**Comment by eBusinessAtlantique** [comment] 2024-12-17 16:12
remove module
do your addition of store
require module
That should work.
