### ISSUE TITLE
AS ISO 3166, TW shoud be Taiwan, Province of China（中国台湾），Pls update it !

### ISSUE THREAD

**Issue by mugua** [magento/magento2#26985] opened 2020-02-23 15:27 UTC
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by hostep** [comment] 2020-02-24 11:13
Closing as a duplicate of https://github.com/magento/magento2/issues/24515

@mugua: if you have more information about this or if you don't agree with the statement over there, please continue the discussion in https://github.com/magento/magento2/issues/24515, thanks!

**Closed as completed by hostep** 2020-02-24 11:13 UTC
Labels: Issue: Format is valid

**Comment by MTheProgrammer** [comment] 2023-07-11 05:44
If Taiwan is a province of China, why doesn't Xi Jinping come to Taipei to eat hot pot?
