### ISSUE TITLE
350 or more configurations causes the product not to show on the category page

### ISSUE THREAD

**Issue by jamie-selesti** [magento/magento2#35765] opened 2022-07-13 12:49 UTC
### Preconditions and environment

- Magento version: 2.4.3-p2
- PHP 7.4

### Steps to reproduce

1. Create a configurable product with 350 or more configurations
2. Assign this product to a category
3. Ensure, all products are in stock, enabled and associated with the active website

### Expected result

1. The product to be shown on the relevant assigned category page

### Actual result

1. The product is not displayed on the category page

### Additional information

1. If I have 349 configurations the product is shown on the relevant assigned category page. The issue only happens when you have 350 or more configurations
2. The product is accessible if you go straight to the product URL. The issue is that it doesn't show on the category page

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by oneserv-heuser** [comment] 2022-07-15 08:01
For us, this is a real critical issue as we have several bigger config products.

Magento doesn't seem to be able anymore to handle huge configs, there was a time where problems arised with more than 3000 singles behind a config, but not with 350 or less (see https://github.com/magento/magento2/issues/35759, another issue with bigger configs)...

**Comment by engcom-November** [comment] 2022-07-18 12:02
Hi @jamie-selesti , Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue.
Configurable Product is getting displayed on Front end with 500+ options after reindexing and cache flush on the assigned category page.
![image](https://user-images.githubusercontent.com/60198231/179506789-03faaeae-37a6-40d9-be13-72286a04dc79.png)

![image](https://user-images.githubusercontent.com/60198231/179506732-b5880129-d026-4d6e-97df-960784f6ad38.png)
Can you please check the product on front-end after re index and clearing cache. Kindly elaborate/provide missing steps if the issue is still reproducible on 2.4-develop branch.
Thank you.

**Comment by engcom-November** [comment] 2022-07-18 12:15
Hi @jamie-selesti ,
Yes I did verified category page as well. Product is displayed on category page after reindex and cache flush:
![image](https://user-images.githubusercontent.com/60198231/179508962-e3e9c394-4e77-4481-8241-3779a6afadd1.png)
![image](https://user-images.githubusercontent.com/60198231/179508905-2e26994f-f9a8-4772-a2e2-e674ce87c1f5.png)

**Comment by oneserv-heuser** [comment] 2022-07-19 06:46
@magento give me 2.4-develop instance

**Comment by oneserv-heuser** [comment] 2022-07-19 07:17
@engcom-November I was able to reproduce the issue again on a vanilla magento 2.4-develop instance.
I just created a new configurable product with 168 options, so significantly less than 350, and even there the issue appears.
I added the config to multiple categories, invalidated all index, flushed the cache, the product still doesn't appear in any of the categories.

Magento knows that the product is assigned to the category because if I directly open the product the category the product is assigned to is marked as visited in the menu.
Also the filters are build correctly as you can see here:
![image](https://user-images.githubusercontent.com/53174153/179689862-65cfe95c-2404-4b5b-9c36-5981adc9584d.png)

**Comment by engcom-November** [comment] 2022-07-20 13:22
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-07-21 09:09
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-07-25 13:50
Hi @jamie-selesti ,
I verified the issue again on a fresh magento 2.4-develop vanila instance without any third party modules but still unable to reproduce the issue.
**Steps performed:**
1. Created Configurable product with 500 options
2. Assign category to the product from UI - Issue. Unable to assign
3. Assigned category to the product using POST rest API - rest/all/V1/categories/{id}/products - Success
4. Reindexed from terminal: php bin/magento indexer:reindex
5. Clear cahce: php bin/magento cache:flush
6. Front-end - Catalog search page of specific category - product displayed
![image](https://user-images.githubusercontent.com/60198231/180793155-38b0539d-2eac-40a3-a252-93e6ec8df39f.png)
![image](https://user-images.githubusercontent.com/60198231/180793218-78dfdd88-52e0-4d1c-aa84-026d0861523d.png)
Please confirm if you have followed the same above steps in 2.4-develop branch.
Thank you.

**Comment by oneserv-heuser** [comment] 2022-07-25 13:59
https://github.com/magento give me 2.4-develop instance

**Comment by oneserv-heuser** [comment] 2022-07-25 14:19
@engcom-November I see 2 differences in our attempts and your attempt to reproduct the bug:
You didn't create a new category and assigned the product to it and you only made the product configurable via one attribute.

Please create a configurable product which can be configured via atleast two different attributes and add it to an existing category. Then verify whether the issue occurs.
Then create a new category and also assign the configurable product to that category. Then verify again whether the issue occurs.

Thank you!

**Comment by engcom-Lima** [comment] 2022-07-27 06:18
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment] 2022-07-27 09:38
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment] 2022-07-27 11:45
Hi @jamie-selesti ,

I have tried to reproduce the issue in `2.4-develop`(on cloud instance as well) branch but issue is not reproducibile to me.

**Steps to reproduce:**

1. Created configurable product with more than 350+ options( 20 size options, 12 color options and 2 format options)
2. Assigned the category.
3. On frontend I have checked the category page.

**Expected result:** Product should be visible on the frontend on category page.
**Actual result:** Product is visible on the frontend on category page.
**Video link:** https://shared-assets.adobe.com/link/e16a87b9-b7b1-459f-7f80-b1a6b3688499
**Screenshots:**
![image](https://user-images.githubusercontent.com/60198022/181238644-5e9744d9-3e3b-4ea3-aecf-d69e9810244f.png)
![image](https://user-images.githubusercontent.com/60198022/181238676-3facf7df-d04a-4066-b4b8-70440c8cf010.png)
![image](https://user-images.githubusercontent.com/60198022/181238762-ea419fb8-a6a2-4e15-b8ad-8ab93b3a283e.png)

Let us know if something is missing from our side.

**Comment by oneserv-heuser** [comment] 2022-07-27 11:54
@engcom-Lima I also cant't reproduce the issue anymore. Maybe there was a commit in the meantime which fixed the issue (accidentially)?

**Comment by engcom-Lima** [comment] 2022-07-27 12:54
Hi @oneserv-heuser & @jamie-selesti ,

As the issue resolved in latest`2.4-develop` we are closing this issue. Kindly create new issue if you observe this issue in future
because waiting for 2.4.5 will take time.
Kindly create new issue if you observe this issue in future.


Thank you

**Closed as completed by engcom-Lima** 2022-07-27 12:54 UTC
Labels: Issue: needs update

**Comment by oneserv-heuser** [comment] 2022-08-16 13:02
https://github.com/magento give me 2.4-develop instance

**Comment by oneserv-heuser** [comment] 2022-08-16 13:04
@magento give me 2.4-develop instance
