### ISSUE TITLE
User role : Notifications error backend

### ISSUE THREAD

**Issue by versdivers** [magento/magento2#12784] opened 2017-12-18 10:10 UTC
When you disable a user roles his permissions to see notifications he gets an error on each page (backend)

### Preconditions
1.  Magento 2.2.1
2. PHP 7.0

### Steps to reproduce
1.  Add a second user to the backend
2.  deny permissions to see notifications
3.  Log in with that user

### Expected result
1.  No notifications like 'clear cache' message etc

### Actual result
1.  notification is not shown but an error is shown instead  (with no logs in Nginx or var folder) on every page

(sorry for the bad screenshot , it was send by a customer)

![image](https://user-images.githubusercontent.com/18028151/34100790-e9dcee94-e3e3-11e7-92a3-bdb7bfafe78f.png)

I solved this by giving him rights to 
![image](https://user-images.githubusercontent.com/18028151/34100810-f729f11e-e3e3-11e7-9295-ad6c34aa73e4.png)

But still the error should not be there.

**Comment by magento-engcom-team** [comment] 2017-12-18 13:40
@versdivers, thank you for your report.
The issue is already fixed in 2.2.2

**Closed as completed by magento-engcom-team** 2017-12-18 13:40 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Fixed in 2.2.x, Issue: Format is valid
