### ISSUE TITLE
Import function rejecting MacOS line endings

### ISSUE THREAD

**Issue by philcook** [magento/magento2#6393] opened 2016-08-30 09:54 UTC
### Preconditions
1. Magento 2.1
2. Apache 2.4
3. PHP 5.6
### Steps to reproduce
1. Take example product CSV from magento and change line endings to be MacOS format like attached [catalog_product.csv.zip](https://github.com/magento/magento2/files/444508/catalog_product.csv.zip)
2. Try to import with native magento imported
### Expected result
1. When end of row should act as end of product insert and move onto next row.
### Actual result
1. See last item of row and first item of next row is combined into one.

![magento2importfailmacos](https://cloud.githubusercontent.com/assets/2623518/18084702/18b2eecc-6ea0-11e6-9be9-2e5d1e3d424b.png)

**Comment by sevos1984** [comment] 2016-09-05 08:15
This is actually a php problem. You can fix this by adding 'php_value auto_detect_line_endings 1' into .htaccess file. Closing as not a bug.

**Closed as completed by sevos1984** 2016-09-05 08:15 UTC
Labels: bug report, Component: ImportExport

**Comment by philcook** [comment] 2016-09-05 10:14
@sevos1984 fair enough point here however the auto_detect_line_endings by default in PHP is 0 therefore many users are going to have this issue.
http://php.net/manual/en/filesystem.configuration.php

Can I therefore suggest it's added to the .htaccess file given with magento2 by default. This will solve the issue and not be an issue going forward.

I will do a PR for this shortly.
