### ISSUE TITLE
Admin dashboard order total incorrect on page load

### ISSUE THREAD

**Issue by devchris79** [magento/magento2#36199] opened 2022-09-26 09:46 UTC
### Preconditions and environment

Magento version 2.4.5,2.4-develop
PHP 8.1

1.Install Magento Instance.
2.Enable Admin dashboard Chart and use aggregated data
3.Create Orders for any product and do invoice and ship, because from completed orders we can get the Revenue.
4.Check Revenue for Today and 24hrs Timeline.
5.To see the Difference in Revenue we need to have Revenue for 24hrs and for Today(0 in my case).

### Steps to reproduce

On Page load of the admin dashboard it appears the total is for the last 24hrs and not the displayed today.

1.Open admin page - Enable the chart and use aggregated data.
2.check the Today Revenue.(Revenue should be today's revenue),it is adding 24hrs Revenue.
3.Change to 24 hrs Timeline and check Revenue.
4.Again change to Today it is adding today's revenue.(i.e, 0 in my case).
5.Reload page and again it is adding 24hrs Revenue.

### Expected result

Chart and total to be in sync reflecting today, like:
![image](https://user-images.githubusercontent.com/43850303/192245557-7a58ec77-4ca9-41d7-b876-a1834fbde9f1.png)

### Actual result

Chart correct (nothing), total wrong:
![image](https://user-images.githubusercontent.com/43850303/192245413-dc479699-294f-4097-a8ce-2177b2a82007.png)

### Additional information.

https://user-images.githubusercontent.com/51680745/193268743-f4e2b1e1-fddf-4080-aea6-80b9f0a17376.mov

### Additional information

Selecting another timeframe from the option box and then reverting to today gives the correct information.

The sql select for "Today":
`SELECT
	SUM(main_table.total_revenue_amount) AS revenue,
	SUM(main_table.total_tax_amount_actual) AS tax,
	SUM(main_table.total_shipping_amount_actual) AS shipping,
	SUM(orders_count) AS quantity
FROM sales_order_aggregated_created AS main_table
WHERE (period >= '2023-02-16 00:00:00' AND period <= '2023-02-16 23:59:59')
	AND (main_table.order_status NOT IN('Canceled'))
	AND (store_id = '0')`

And here the result without the SUM:
![screen05](https://user-images.githubusercontent.com/16879037/219363077-3a7bb482-0e15-43f7-8a52-4b00b80cd8a7.jpg)

The sql select for "Last 24 hours":
`SELECT
	SUM(main_table.total_revenue_amount) AS revenue,
	SUM(main_table.total_tax_amount_actual) AS tax,
	SUM(main_table.total_shipping_amount_actual) AS shipping,
	SUM(orders_count) AS quantity
FROM sales_order_aggregated_created AS main_table
WHERE (period >= '2023-02-15 11:58:12' AND period <= '2023-02-16 11:58:12')
	AND (main_table.order_status NOT IN('Canceled'))
	AND (store_id = '0')`

And here the result without the SUM:
![screen06](https://user-images.githubusercontent.com/16879037/219363183-a4ba4629-bc8d-49c1-ae87-28b645769d4c.jpg)

The result stay the same and so the total values. The problem is, that the field "period" in "sales_order_aggregated_created" is a date field and not datetime. The graph is also messed up because of this problem.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-09-26 11:14
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-09-26 12:30
Hi @devchris79,


Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop branch and 2.4.5 and the issue is not reproducible.Kindly refer the attached screenshot.



<img width="1378" alt="Screenshot 2022-09-26 at 5 38 10 PM" src="https://user-images.githubusercontent.com/51680745/192272492-86773a94-8f53-4efb-9fa4-1006835ac31c.png">



Please let us know we miss anything.


Thanks.

**Comment by devchris79** [comment] 2022-09-26 12:43
Hi @engcom-Bravo,

Was the order for vk kv within the last 24 hours? The issue shows for us when there is an order from the later part of the previous day that shouldn't be added to the total.
The strange thing is it works fine when the time selector is changed and reverted, it just appears on the page load.

**Comment by engcom-Bravo** [comment] 2022-09-27 11:31
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-09-27 12:47
Hi @devchris79,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop branch and 2.4.5 and the issue is not reproducible.Kindly refer the attached screenshot.



<img width="1322" alt="Screenshot 2022-09-27 at 6 12 51 PM" src="https://user-images.githubusercontent.com/51680745/192529502-7247cf67-7854-4a1d-b54b-1e2b9fb0c237.png">




<img width="866" alt="Screenshot 2022-09-27 at 6 13 57 PM" src="https://user-images.githubusercontent.com/51680745/192529601-3f4438c1-437f-4497-8d59-9d9f1975ac85.png">


Note:The amount will be added to chart after the order is completed(Invoiced and Shipped).


Please let us know we miss anything.

Thanks.

**Comment by devchris79** [comment] 2022-09-27 13:10
Hi @engcom-Bravo

The screenshot shows orders that have been placed in the "Today" time frame, and works fine (as I would have expected).

Issue is that orders appear to be added to the numerical totals that were within the last 24hrs time frame (when page is first loaded). If you had an order at say 10pm from the previous day it would be incorrectly added to the numerical total on the page loads, the graph appears correct though.

Here is another capture below, its adding an order to the totals from 8pm the previous day.

![image](https://user-images.githubusercontent.com/43850303/192534877-b714f876-ad14-4f8b-8b41-ac542c86d652.png)

**Comment by engcom-Bravo** [comment] 2022-09-29 11:55
Hi @devchris79,


Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop and 2.4.5 instances and the issue is reproducible on both the instances.Kindly refer the attached video.


Issue is that orders appear to be added to the numerical totals that were within the last 24hrs time .It works fine when the time selector is changed and reverted to Today Chart.



https://user-images.githubusercontent.com/51680745/193022031-4bf73f13-96b2-417c-af04-dceb300e572a.mov





Hence confirming the issue.


Thanks.

**Comment by quterorta** [comment] 2022-10-07 13:04
@magento I am working on this

**Comment by gexxx05** [comment] 2023-02-20 07:49
The problem is that if no period param is added to the request, the default param is taken.
And in this case it is `Period::PERIOD_24_HOURS`:
`$period = $this->getRequest()->getParam('period', Period::PERIOD_24_HOURS);`

Here is the commit that will fixes the issue:
https://github.com/magento/magento2/commit/dd769504d2a56e510b1632e8f1a5f42c9571af52

Hotifx:
Change
`$period = $this->getRequest()->getParam('period', Period::PERIOD_24_HOURS);`
to
`$period = $this->getRequest()->getParam('period', Period::PERIOD_TODAY);`
in File
app\code\Magento\Backend\Block\Dashboard\Totals.php

**Comment by engcom-Bravo** [comment] 2023-05-31 06:50
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-7698 by the internal team
Related commits: https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-1294&type=commits

Based on the Jira ticket, the target version is 2.4.7-beta1.

Thanks

**Closed as completed by engcom-Bravo** 2023-05-31 06:50 UTC
Labels: Issue: Confirmed, Component: Admin, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Admin UI, Reported on 2.4.5
