### ISSUE TITLE
ProductAlert Emails - Images broken/not showing in Stock and Price Alert emails

### ISSUE THREAD

**Issue by boardwalki** [magento/magento2#36340] opened 2022-10-20 16:35 UTC
### Preconditions (*)

1.  Magento ver. 2.4.5-p1
2. PHP 8

### Steps to reproduce (*)

1. Sign up for a "back in stock" notification on an item that is currently out of stock. 
2. Add stock in admin so item is now back in stock
3. Re-index catalog
4. Run stock alert cron
5. Check/view stock alert email that was sent

### Expected result (*)

1. email should show the product image next to the product name

### Actual result (*)

1. Broken image is shown next to the product name (for both stock alert and price alert emails)
2. This issue occurs on both Stock Alert and Price Alert emails

**Comment by engcom-Dash** [comment] 2022-10-21 08:00
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-10-21 17:41
Hi @boardwalki ,

We are trying to reproduce the issue in 2.4-develop branch...But we are not able to reproduce.
we are getting expected result as "email should show the product image next to the product name"
Steps we followed:
1.Create a simple product and enable back in stock
2.Place the order with all quantity so the product will be out of stock.
3.Again add the number of product in admin
4.we are getting expected result.

Let us know if we missing anything!

Thanks!!!

**Comment by boardwalki** [comment] 2022-10-21 17:54
Can you please provide a screenshot of the “back in stock” email you received that shows the image properly loaded.
Thank you,


--
John Strain
Boardwalk Interactive

**Comment by royalkaroma** [comment] 2022-10-22 22:05
Bonjour j ai magento 2.4.5 instaler avec php 8.1 
Le prix s affiche sans le symbole de money dans la page produit en dollar et j ai changer en franc suisse et lieux  de la boutique suisse le prix devient 0.00 chf 
J ait tester avec plusieurs versions de php 8 et 7.4 la même problème

**Comment by engcom-Dash** [comment] 2022-10-31 10:51
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-11-14 05:33
Hi @boardwalki ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2022-11-14 05:33 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1

**Comment by sprankhub** [comment] 2023-05-05 13:36
If I am not mistaken, this is fixed by https://github.com/magento/magento2/commit/b8f8ed5aafd283987c1d7f6a7a124966f4470d0d.

**Comment by sprajapat770** [comment] 2023-07-20 16:14
@engcom-Dash  here clearly steps are mentioned why are you waiting or checking order email??

that is basic after notifying product alert email you should either wait to receive email or manage catalog_product_alert cron job manually to receive fast email.

Sign up for a "back in stock" notification on an item that is currently out of stock.
Add stock in admin so item is now back in stock
Re-index catalog
Run stock alert cron
Check/view stock alert email that was sent

**Comment by engcom-Dash** [comment] 2023-07-21 09:18
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-07-21 11:52
Hi @sprajapat770 ,

Thank you for reporting and collaboration. This issue is a duplicate of https://github.com/magento/magento2/issues/35602 and has been confirmed here. We are closing this issue. Please move onto this ticket for latest updates/ solutions.
Thank you.

**Comment by hgati** [comment] 2023-09-23 02:25
> ### 전제조건(*)
> 1. 마젠토 버전 2.4.5-p1
> 2. PHP 8
> 
> ### 재현 단계(*)
> 1. 현재 품절된 품목에 대한 "재입고" 알림에 등록하세요.
> 2. 관리자에 재고를 추가하여 이제 품목이 다시 재고가 되도록 하세요.
> 3. 카탈로그 재인덱싱
> 4. 재고 알림 크론 실행
> 5. 발송된 재고 알림 이메일 확인/조회
> 
> ### 예상 결과 (*)
> 1. 이메일에는 제품 이름 옆에 제품 이미지가 표시되어야 합니다.
> 
> ### 실제 결과 (*)
> 1. 제품 이름 옆에 깨진 이미지가 표시됩니다(재고 알림 이메일과 가격 알림 이메일 모두에 해당).
> 2. 이 문제는 주식 알림 및 가격 알림 이메일 모두에서 발생합니다.

Me too.
This issue still persists on Magento 2.4.6 + PHP 8.2.

https://pasteboard.co/PYWoOzktpiO4.png

**Comment by hgati** [comment] 2023-09-24 01:13
On Magento 2.4.6
### _Great ~ Applying the Magento patch resolved the issue immediately. Thank you._ 

### Applied patches: ACSD-48366, ACSD-50336

![Magento2 ProductAlert Emails - Images broken/not showing in Stock and Price Alert emails : How to apply patches](https://gcdnb.pbrd.co/images/H8LZrQKSWH7L.png)

### Now, in the received email (price change notification email), the product images display correctly without any distortion.
![Magento2 ProductAlert Emails - Images broken/not showing in Stock and Price Alert emails : After applied patches](https://gcdnb.pbrd.co/images/oLnkG0pgPWWX.png)
