### ISSUE TITLE
Creditmemo Creation Error in 2.4.5: Please enter positive number in this field

### ISSUE THREAD

**Issue by Darkwolf81** [magento/magento2#36175] opened 2022-09-21 20:41 UTC
### Preconditions and environment

- Magento 2.4.5
- PHP 7.4.21 (Amazon AWS Elastic Beanstalk Platform, Nginx)

### Steps to reproduce

1. Create a creditmemo for any order
2. Error Message: Please enter positive number in this field

### Expected result

Creditmemo successfully created

### Actual result

Error Message: Please enter positive number in this field
In the input field, there is the formatted number with currency symbol instead only the number. That causes the error.

### Additional information

It is the same error from here, that was first in 2.4.3 and fixed in 2.4.4:
https://github.com/magento/magento2/issues/34182

Error is not reproducable on every system configuration. On my local development Server with Apache it workes fine.
When i use the file: vendor/magento/module-directory/Currency.php from Magento 2.4.4, it works again. There were changes that broke it again.

It maybe helpful to look into the other issue to reproduce the issue.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Darkwolf81** [comment] 2022-09-21 20:43
@magento give me 2.4-develop instance

**Comment by Darkwolf81** [comment] 2022-09-21 20:57
Hi, i cannot reproduce the error on the test Magento Instance. This has a system configuration, thats not affected by the error. The error in 2.4.3 could although not being reproduced on the Test Instance.

**Comment by engcom-November** [comment] 2022-09-22 11:18
Hi @Darkwolf81 ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop and Magento 2.4.5 open source versions as well but the issue is not reproducible.
As per the pre conditions mentioned by you, PHP 7.4 is not a supported version for Magento 2.4.5. Kindly check the Magento [System requirements](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html) for compatible softwares and its supported versions to use Magento.  Also check if the issue occured due to 3rd party extension / modules enabled and elaborate the steps / configuration details if you are still facing any issues.
Thank you.

**Comment by Darkwolf81** [comment] 2022-09-22 16:08
> Hi @Darkwolf81 , Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop and Magento 2.4.5 open source versions as well but the issue is not reproducible. As per the pre conditions mentioned by you, PHP 7.4 is not a supported version for Magento 2.4.5. Kindly check the Magento [System requirements](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html) for compatible softwares and its supported versions to use Magento. Also check if the issue occured due to 3rd party extension / modules enabled and elaborate the steps / configuration details if you are still facing any issues. Thank you.

Hello @engcom-November 
Magento 2.4.4 added compatibility with PHP 8.1, but it is no requirement. Fresh install of 2.4.5 is still possible. Current composer.json has the requirement:
```
"require": {
        "php": "~7.4.0||~8.1.0",
```
PHP 8.1 is although currently not available on Amazon AWS, so max 8.0 is possible to use.

Maybe other users can confirm the issue, too. I can only confirm that the error affected through changes in the file described in the issue.

Regards,
Andreas

**Comment by engcom-Hotel** [comment] 2022-12-13 06:53
Hello @Darkwolf81,

Thanks for the reporting and collaboration!

We have tried to reproduce the issue in the Magento 2.4.5 as well as the 2.4-develop branch but the issue is not reproducible for us. 
When we tried it with PHP 7.4 we are getting the following fatal error:

![PHP7 4 - Error](https://user-images.githubusercontent.com/51681618/207246649-a48e7a0d-c595-45f5-b1e2-6f916e2021e6.png)

and with PHP 8.1 we are able to create the credit memo:

![image](https://user-images.githubusercontent.com/51681618/207246730-656af4cc-5dbd-48b5-9669-c4f327a6693e.png)

please let us know if in any specific condition you are getting this error.

Thanks

**Comment by engcom-Hotel** [comment] 2022-12-27 05:31
Dear @Darkwolf81,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-12-27 05:31 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.5
