### ISSUE TITLE
Export not working for doorstep.market--neither CSV nor Excel

### ISSUE THREAD

**Issue by KevinMurphy2** [magento/magento2#30960] opened 2020-11-17 23:57 UTC
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment] 2020-11-20 13:02
Hi @KevinMurphy2 .
Unfortunately, we are not able to reproduce the issue on fresh 2.4-develop.
Export's functionality works as expected.

**Actual Result:** :heavy_check_mark: Export file was created

![2020-11-20_14-58](https://user-images.githubusercontent.com/51679138/99802875-22b3a800-2b41-11eb-88fe-4a380ffc0652.png)
The problem may be with additional modules related to exports.
So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-11-20 13:02 UTC
Labels: Issue: ready for confirmation, not-confirmed
