### ISSUE TITLE
V1/carts/{cartId}/billing-address parameter "useForShipping" never used

### ISSUE THREAD

**Issue by fitao** [magento/magento2#11333] opened 2017-10-10 10:41 UTC
### Preconditions

1. Magento EE 2.1.7
2. PHP 7.0.12
3. Mysql Ver 14.14 Distrib 5.6.33-79.0, for Linux (x86_64) using 6.2

### Steps to reproduce

1.  Send a request to the REST endpoint V1/carts/{cartId}/billing-address using the payload below
`{
  "address": {
    "id": 1,
    "region": "ee",
    "region_id": 1,
    "region_code": "eee",
    "country_id": "FR",
    "street": [
      "string"
    ],
    "company": "string",
    "telephone": "0145454545",
    "fax": "",
    "postcode": "75001",
    "city": "paris",
    "firstname": "string",
    "lastname": "string",
    "middlename": "",
    "prefix": "",
    "suffix": "",
    "vat_id": "",
    "customer_id": 1,
    "email": "test@test.fr",
    "same_as_billing": 1,
    "customer_address_id": 1,
    "save_in_address_book": 1,
    
    "extension_attributes": {
    },
    "custom_attributes": [
    
    ]
  },
  "useForShipping": true
}`

### Expected result

1. The address must be used for shipping, but it is not.

### Actual result

1. 
If you take a look, in the file <magento_dir>\vendor\magento\module-quote\Model\BillingAddressManagement.php, the function assign()" where argument '$useForShipping' is false by default, the quote is saved there and you have the '$saveHandler' which makes severals saving tasks.
The class <magento_dir>\vendor\magento\module-quote\Model\QuoteRepository\SaveHandler.php calls the instruction  "$this->billingAddressPersister->save($quote, $billingAddress);" without the argument '$useForShipping'. 
May be is the origin of my issue.

**Comment by magento-engcom-team** [comment] 2017-10-10 11:30
@fitao, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-10 11:30 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
