### ISSUE TITLE
Error in pulling currency exchange rates from Currency Converter API

### ISSUE THREAD

**Issue by Hailong** [magento/magento2#22468] opened 2019-04-23 16:05 UTC
### Preconditions (*)

Clean Magento 2.3.1 installation.

### Steps to reproduce (*)

1. Set store default currency to CAD, and add CAD and USD as allowed currencies.
2. Navigate to Stores -> Currency Rates
3. Select Currency Converter API as Import Service and click Import.

### Expected result (*)

Get the latest rates.

### Actual result (*)

Got following error:
`Notice: Undefined index: CAD_USD in /Users/hailong/dev/ttechtattoo/ttechtattoo_m2/vendor/magento/magento2ce/app/code/Magento/Directory/Model/Currency/Import/CurrencyConverterApi.php on line 91`

**Comment by krishprakash** [comment] 2019-04-23 16:28
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-04-23 16:28
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-23 16:28
Hi @krishprakash, here is your [Magento instance](https://i-22468-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22468-2-3-develop.instances.magento-community.engineering/admin](https://i-22468-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2019-04-23 16:46
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-04-23 16:46
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-23 16:47
Hi @krishprakash, here is your [Magento instance](https://i-22468-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22468-2-2-develop.instances.magento-community.engineering/admin](https://i-22468-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-04-23 16:54
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99363` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by orlangur** [comment] 2019-04-23 17:19
@krishprakash so what about `2.2-develop`?

**Comment by krishprakash** [comment] 2019-04-23 17:30
@orlangur 
There is no currency convertor API import service option available in 2.2 develop.
So the issue only in 2.3.x
Thanks.

**Comment by mikebox** [comment] 2019-05-04 09:52
I am working on this #dmcdindia1

**Comment by magento-engcom-team** [comment] 2019-05-04 09:52
@mikebox thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment] 2019-06-20 20:35
Hi @Hailong, @Hailong, @mikebox. 

Thank you for your report and collaboration!

The related internal Jira ticket `MAGETWO-99931` was closed as `non-reproducible` in `2.2.x`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by mrk-dzie** [comment] 2019-07-11 11:53
When will it be resolved and the fix pushed to Magento 2.3?

**Comment by Hailong** [comment] 2019-07-11 16:33
@mrk-dzie Here is the PR that fixing the problem, but I'm not sure when it will be able to merged into main.

**Comment by sidolov** [comment] 2019-08-16 20:19
Fixed in scope of https://github.com/magento/magento2/pull/24008

**Closed as completed by sidolov** 2019-08-16 20:19 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.2.x, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Admin, Event: dmcdindia1
