### ISSUE TITLE
Grouped products without children not shown and pagination broken

### ISSUE THREAD

**Issue by iphigenie** [magento/magento2#31828] opened 2021-01-25 14:36 UTC
Pagination gets calculated incorrectly when there are grouped products without children.

### Investigation

Upon further investigation I have found the following

1. when calculating the number of products to show, the system will count all grouped products that match, as it should
2. when building the pages, the system then skips the grouped products that do not have a child product

This causes inconsistent paging and results in some products not showing in the catalog listing, though they show fine on direct link. 

### Preconditions (*)

1. Magento 2 site, in my case 2.4
2. Use Grouped products 
3. have more grouped products than your page size
4. have a grouped product that does not currently have children assigned

### Steps to reproduce (*)

1. Go to catalog and look at pagination information

### Expected result (*)

1. Pagination should match the configuration and show the right number of products, including enabled matching grouped products without a child

example for 151 results and 48 page size: pg 1 is 1-48, pg 2 is 49-96, pg 3 is 97-144 etc

### Actual result (*)

1. Pagination does not match the configuration and there are gaps in the pages as the grouped products without children are, for some reason, skipped.

pg 1 is 1-48, pg 2 is 49-92, pg3 is 97-144

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

PS: Grouped products really don't get tested properly ever. This is getting painful. The test data should have more than 1 grouped product. CAN WE GET 20 grouped products in the test data, so they get tested properly instead of being missed so often?

-----------

note that an empty grouped product is a weird thing since grouped products are supposed to be a container for a selection of products (for me grouped products are placeholders for products that return regularly in new models - vintages of wine - with all the editorial and marketing content on the grouped, persisting across years) 
but **the handling should be consistent, i.e. either not counted and not shown, or counted and shown**. It should not be counted then not shown

**Comment by iphigenie** [comment] 2021-01-25 14:37
@magento give me 2.4-develop instance

**Comment by iphigenie** [comment] 2021-01-25 14:54
Reproduced in 2.4-develop

- created duplicate of "sprite yoga straps" in stock, enabled, but no simple products in it, named "emptry sprite yoga straps"
- made category "gear" show products
- refresh page, sort by name, first page is now 1-11 instead of 1-12

**Comment by magento-engcom-team** [comment] 2021-01-25 15:47
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40617` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by kevinboerland** [comment] 2021-04-12 06:53
Yes, this issue is still relevant.

**Comment by WebWeave** [comment] 2021-04-12 07:43
Any update on this issue from @magento-engcom-team ?

**Comment by mrtuvn** [comment] 2021-05-05 15:16
![Screenshot from 2021-05-05 22-15-08](https://user-images.githubusercontent.com/1908873/117165086-63e9fc80-adef-11eb-993f-3dca14251a3d.png)
Tested in my own setup
i have exactly 13 items totall for gear category
cc: @iphigenie

**Comment by iphigenie** [comment] 2021-05-07 09:10
> Re Tested in my own setup + 2.4-develop code github + sampledata
> i have exactly 13 items totall for gear category almost type is simple (More new items created manually by me) sorted by product name
> cc: @iphigenie Not sure this case meet same your scenario ? Maybe i'm miss something

My first notion is that an empty grouped product would not show a price, since it has no price of its own?

**Comment by iphigenie** [comment] 2021-05-07 09:14
@magento give me 2.4-develop instance

**Comment by iphigenie** [comment] 2021-05-25 14:08
@magento give me 2.4-develop instance

**Comment by Hexmage** [comment] 2023-12-18 13:30
This still seems to happen on 2.4.6, so whatever fix was in place never made it to a live version.

**Comment by Hexmage** [comment] 2023-12-18 14:04
What I tested was:
- move the "sprite yoga straps" to position -1 so its at the start of the category
- Set "Products per Page on Grid Allowed Values" and "Products per Page on Grid Default Value" to 5.
![Screenshot from 2023-12-18 14-24-04](https://github.com/magento/magento2/assets/22170051/b000aa74-781b-4b71-b49b-ca5a908ebf75)
Which results in 5 products per page with "Sprite Yoga Straps" in the first position.
Then remove all the simples from "Sprite Yoga Straps"
![Screenshot from 2023-12-18 15-00-57](https://github.com/magento/magento2/assets/22170051/614e06fc-bf73-4a77-b7a3-747af4385639)
This results in a first page with only 4 products and a total of only 10 visible products, while the pagination thinks there are 11.
The same happens with bundles.

**Comment by engcom-Delta** [comment] 2024-09-04 08:41
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment] 2024-09-05 11:07
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment] 2024-09-05 12:29
Hi @iphigenie  ,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop and the issue is not reproducible. Kindly refer the screenshots.

Steps to reproduce -

1. Install magento 2.4-develop
2. Create Multiple Group products
3. have more grouped products than your page size
4. have a grouped product that does not currently have children assigned
5. Set position for group products with child and without child
![image](https://github.com/user-attachments/assets/87473e8f-5752-44b3-8489-e2095d8f6d8f)
6. Clear cache and refresh frontend.
7. Observe group products without child are not displaying in frontend and it has not impacted the pagination position.
![image](https://github.com/user-attachments/assets/ed28a5a7-abf9-4061-847c-e172ff8111ad)
8. Now, remove child product of one group item and clear the cache
Product Name - "With Child Product 1"
9. Refresh the frontend page
![image](https://github.com/user-attachments/assets/af8b05e3-4e67-407c-8d76-a2396ae7b8e4)
Kindly recheck the issue on latest Magento 2.4-develop instance and Please let us know if you are still facing any issue.

Thanks.

**Closed as completed by engcom-Delta** 2024-09-05 12:29 UTC
Labels: Component: Catalog, Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Severity: S3, Progress: done

**Comment by iphigenie** [comment] 2025-08-06 10:54
I gave up but you are reproducing the issue in that post - the products aren't showing!
your screenshot does not show if the count of products is correct or wrong
