### ISSUE TITLE
Registered user couldnot place the order once cancel any order

### ISSUE THREAD

**Issue by Gowsalayadevi** [magento/magento2#12616] opened 2017-12-11 00:30 UTC
Hi,
The registered customer whose order has been cancelled due to wrong card details couldnot place any other orders.

### Preconditions

1. Magneto 1.9.3

### Steps to reproduce

1.  create a new user and log In
2.  Add a product in the cart
3.  Proceed to checkout
4. Select the credit card payment method and proceed
5.  Enter wrong card details.
6. The order will be cancelled due to wrong card details

### Expected result

1.  The customer would be able to place the order again with the correct card details

### Actual result

with the customer logging in could not proceed with any new orders. when you click the place order button, it loads and it is in same page.
I could see the exception as below:
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'FO27015' for key 'UNQ_SALES_FLAT_ORDER_INCREMENT_ID''
1. [Screenshot, logs]

**Comment by magento-engcom-team** [comment] 2017-12-11 07:44
@Gowsalayadevi , thank you for your report.
Could you please let us know if the issue is still actual for versions 2.1.10 and 2.2.1? Thank you.

**Comment by Gowsalayadevi** [comment] 2017-12-11 23:24
@magento-engcom-team . Thanks for your response.. I have actually fixed the issue.

**Comment by magento-engcom-team** [comment] 2017-12-13 06:57
@Gowsalayadevi We glad you found the solution to your problem. We are closing this issue, have a great day.

**Closed as completed by magento-engcom-team** 2017-12-13 06:57 UTC
Labels: Progress: needs update, Issue: Clear Description, Issue: Format is valid
