### ISSUE TITLE
Imported configurable products with multiple super attributes do not retain super attribute ordering

### ISSUE THREAD

**Issue by dimunation** [magento/magento2#6079] opened 2016-08-09 16:47 UTC
Imported configurable products with multiple configurable attributes do not retain the configurable attribute order after exporting and importing.  I'm unable to find a mechanism to control catalog_product_super_attribute position values using the CSV product import and export system, either through the configurable_variation_labels CSV field, or the ordering of the attributes within the configurable_variations CSV field. 
### Preconditions

Magento CE Version 2.0.7
### Steps to reproduce

1. Create at least two product attributes suitable for product configuration in a configurable product. 
2. Produts -> Catalog -> Add New Product.  Enter any required product data fields. 
3. Configurations -> Create Configurations
4. Select at least two product attributes.  Select "Next".
5. Change the order of the attributes by dragging the first attribute below the second. 
6. Select at least one attribute value for each attribute.  Select "Next".
7. Skip all bulk images, price, and quantity data.
8. Generate products and save the configurable product.
9. Export product data to CSV.
10. Delete the new configurable and virtual / simple products, re-index and clear cache.
11. Import the product data from step 9, re-index and clear cache.
### Expected result

1. Product super attribute order on the front-end product page should match the original product attribute order after export and import.
2. The catalog_product_super_attribute table should match the original position values for the previously created product after importing.
### Actual result

1. View front-end product page and note the attribute sort ordering does not match the order selected in step 5.
2. Examine catalog_product_super_attribute table and note that the position values do not match the original attribute positions defined when creating the product configurations.
3. In product export CSV, the configurable_variation_labels field does not affect the position of the super attributes for the imported products.

**Comment by sevos1984** [comment] 2016-09-12 15:34
Internal ticket created MAGETWO-58299. Thanks for reporting

**Comment by erik-augustin** [comment] 2016-09-28 07:23
configurable item with multiple text swatches shows with export only one text swatch at field configurable_variations,

**Comment by jarnail104** [comment] 2016-12-27 10:16
is this bug fixed?

**Comment by magicbunneh** [comment] 2017-02-06 17:02
Fix for this issue was merged:
- [magento2/develop](https://github.com/magento/magento2/tree/develop) - repo/branch
- [ca2ade1cb0cb043d5ef2c4590a516a0b9547a2ed](https://github.com/magento/magento2/commit/9536d0e47522611767b9e77a379d419e782a2b1a) - commit

**Comment by veloraven** [comment] 2017-06-20 12:16
This issue has already been fixed in develop branch.
It also was fixed for ver. 2.1 in scope of internal ticket - MAGETWO-63589. The fix will be available in one of the next releases.
Internal ticket for ver. 2.0 - MAGETWO-63590

**Comment by magento-engcom-team** [comment] 2017-09-20 22:30
@dimunation, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:30 UTC
Labels: Issue: Ready for Work, bug report, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
