### ISSUE TITLE
fix bug: It is not possible to complete a Magento Guest Order if it pays with PayPal

### ISSUE THREAD

**Issue by olgaIskra** [magento/magento2#24672] opened 2019-09-20 11:36 UTC
1. After PayPal was paid and returned to Magento, the process go in cycles  "Re-Ording" with an error: We can't save the address: empty e-mail.

2. The solution is to store guest data in a timely manner:
module-checkout/Model/GuestPaymentInformationManagement.php
public function savePaymentInformation(
        $cartId,
        $email,
        \Magento\Quote\Api\Data\PaymentInterface $paymentMethod,
        \Magento\Quote\Api\Data\AddressInterface $billingAddress = null
    ) {
    	$quoteIdMask = $this->quoteIdMaskFactory->create()->load($cartId, 'masked_id');
        /** @var Quote $quote */
        $quote = $this->cartRepository->getActive($quoteIdMask->getQuoteId());

        if ($billingAddress) {
        	$billingAddress->setEmail($email);
            $quote->removeAddress($quote->getBillingAddress()->getId());
            $quote->setBillingAddress($billingAddress);
            **$quote->setCustomerEmail($email);**
            $quote->setDataChanges(true);
            
        } else {
        	$quote->getBillingAddress()->setEmail($email);
        }
        **$this->cartRepository->save($quote);**
        $this->limitShippingCarrier($quote);
        **$this->cartRepository->save($quote);**
        
        $this->paymentMethodManagement->set($cartId, $paymentMethod);
        return true;
    }

**Comment by danci1973** [comment] 2019-09-23 07:14
I think this would be the correct patch for 2.3.0 (all credits to @olgaiskra):

```
--- clean/GuestPaymentInformationManagement.php   2019-09-20 14:25:56.696734848 +0200
+++ new/GuestPaymentInformationManagement.php      2019-09-23 08:48:37.286939940 +0200
@@ -137,6 +137,7 @@
         \Magento\Quote\Api\Data\PaymentInterface $paymentMethod,
         \Magento\Quote\Api\Data\AddressInterface $billingAddress = null
     ) {
+       //O Romanovskaja Agenda 20.09.2019 changed for Pay Pal Guest working
         $quoteIdMask = $this->quoteIdMaskFactory->create()->load($cartId, 'masked_id');
         /** @var Quote $quote */
         $quote = $this->cartRepository->getActive($quoteIdMask->getQuoteId());
@@ -145,12 +146,14 @@
             $billingAddress->setEmail($email);
             $quote->removeAddress($quote->getBillingAddress()->getId());
             $quote->setBillingAddress($billingAddress);
+            $quote->setCustomerEmail($email);
             $quote->setDataChanges(true);
         } else {
             $quote->getBillingAddress()->setEmail($email);
         }
         $this->limitShippingCarrier($quote);
-
+        $this->cartRepository->save($quote);
+        
         $this->paymentMethodManagement->set($cartId, $paymentMethod);
         return true;
     }
```

**Comment by engcom-Charlie** [comment] 2019-10-02 11:04
Hello @olgaIskra 
I can't reproduce this issue on a fresh Magento 2.3-develop.
**Manual testing scenario:**
1. Configure PayPal Express Checkout ( with Guest checkout)
2. Add product to cart
3. In mini cart press PayPal button
4. Place order 

**Actual result:**
Order is placed without any errors.
So i have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-10-02 11:04 UTC
Labels: Issue: Format is not valid

**Comment by olgaIskra** [comment] 2019-10-02 11:09
How make correct "Configure PayPal Express Checkout ( with Guest checkout)"?

**Comment by engcom-Charlie** [comment] 2019-10-02 11:19
@olgaIskra 
1. Fill all data 
![image](https://user-images.githubusercontent.com/51680850/66040155-6e5f5880-e51f-11e9-88c8-978941c3369d.png)
2. In 'Advanced settings' tab turn on Guest checkout 
![image](https://user-images.githubusercontent.com/51680850/66040263-af576d00-e51f-11e9-8975-0edf6ba4620f.png)
