### ISSUE TITLE
PHP Fatal error: Uncaught Error: Class "DOMDocument" not found in /home/bumbinguglies/public_html/vendor/magento/framework/Config/Dom.php:449Stack trac

### ISSUE THREAD

**Issue by georgittanchev** [magento/magento2#37614] opened 2023-06-14 18:43 UTC
### Preconditions and environment

- Magento version -> 2.3.5
- WHM (cPanel version 110)
- CloudLinux
- PHP 7.1

### Steps to reproduce

Install Magento via the command:
composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.3.5 magento2

Then:

bin/magento setup:install \
--base-url=http://bumbinguglies.com \
--db-host=localhost \
--db-name=bumbinguglies_magento \
--db-user=bumbinguglies_magento \
--db-password=aoNACCk2W1qQh9 \
--admin-firstname=admin \
--admin-lastname=admin \
--admin-email=admin@admin.com \
--admin-user=admin \
--admin-password=admin123 \
--language=en_US \
--currency=USD \
--timezone=America/Chicago \
--use-rewrites=1

Then the website doesn't load only 500 error is received and the error log shows 

[bumbinguglies@workhard public_html]$ tail -f error_log
#1 /home/bumbinguglies/public_html/vendor/magento/framework/ObjectManager/Config/Reader/Dom.php(70): Magento\Framework\Config\Dom->__construct()
#2 /home/bumbinguglies/public_html/vendor/magento/framework/Config/Reader/Filesystem.php(151): Magento\Framework\ObjectManager\Config\Reader\Dom->_createConfigMerger()
#3 /home/bumbinguglies/public_html/vendor/magento/framework/Config/Reader/Filesystem.php(132): Magento\Framework\Config\Reader\Filesystem->_readFiles()
#4 /home/bumbinguglies/public_html/vendor/magento/framework/App/ObjectManagerFactory.php(279): Magento\Framework\Config\Reader\Filesystem->read()
#5 /home/bumbinguglies/public_html/vendor/magento/framework/App/ObjectManagerFactory.php(140): Magento\Framework\App\ObjectManagerFactory->_loadPrimaryConfig()
#6 /home/bumbinguglies/public_html/vendor/magento/framework/App/Bootstrap.php(211): Magento\Framework\App\ObjectManagerFactory->create()
#7 /home/bumbinguglies/public_html/vendor/magento/framework/App/Bootstrap.php(126): Magento\Framework\App\Bootstrap->__construct()
#8 /home/bumbinguglies/public_html/index.php(36): Magento\Framework\App\Bootstrap::create()
#9 {main}
  thrown in /home/bumbinguglies/public_html/vendor/magento/framework/Config/Dom.php on line 449

### Expected result

To see the luma theme after the installation instead of a 500 error.

### Actual result

500 error:

-> https://prnt.sc/xNGesINRzwbW

PHP fatal error in error log

### Additional information

I am receiving the same error on 2.3.5 installed via Magento-CLI, composer install works fine, however, the error log provides the following output:

[14-Jun-2023 18:17:06 UTC] PHP Fatal error: Uncaught Error: Class "DOMDocument" not found in /home/bumbinguglies/public_html/vendor/magento/framework/Config/Dom.php:449Stack trace:
#0 /home/bumbinguglies/public_html/vendor/magento/framework/Config/Dom.php(116): Magento\Framework\Config\Dom->_initDom()https://github.com/magento/magento2/issues/1 /home/bumbinguglies/public_html/vendor/magento/framework/ObjectManager/Config/Reader/Dom.php(70): Magento\Framework\Config\Dom->__construct()https://github.com/magento/magento2/pull/2 /home/bumbinguglies/public_html/vendor/magento/framework/Config/Reader/Filesystem.php(151): Magento\Framework\ObjectManager\Config\Reader\Dom->_createConfigMerger()https://github.com/magento/magento2/pull/3 /home/bumbinguglies/public_html/vendor/magento/framework/Config/Reader/Filesystem.php(132): Magento\Framework\Config\Reader\Filesystem->_readFiles()https://github.com/magento/magento2/issues/4 /home/bumbinguglies/public_html/vendor/magento/framework/App/ObjectManagerFactory.php(279): Magento\Framework\Config\Reader\Filesystem->read()https://github.com/magento/magento2/issues/5 /home/bumbinguglies/public_html/vendor/magento/framework/App/ObjectManagerFactory.php(140): Magento\Framework\App\ObjectManagerFactory->_loadPrimaryConfig()https://github.com/magento/magento2/issues/6 /home/bumbinguglies/public_html/vendor/magento/framework/App/Bootstrap.php(211): Magento\Framework\App\ObjectManagerFactory->create()
https://github.com/magento/magento2/issues/7 /home/bumbinguglies/public_html/vendor/magento/framework/App/Bootstrap.php(126): Magento\Framework\App\Bootstrap->__construct()https://github.com/magento/magento2/issues/8 /home/bumbinguglies/public_html/index.php(36): Magento\Framework\App\Bootstrap::create()
https://github.com/magento/magento2/pull/9 {main} thrown in /home/bumbinguglies/public_html/vendor/magento/framework/Config/Dom.php on line 449

PHP extensions enabled:
[PHP Modules]
bcmath
clos_ssa
Core
ctype
date
dom
filter
ftp
hash
json
libxml
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
zlib

Magento is installed with the following command:
composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.3.5 magento2

It looks like the dom extension is completely installed on PHP 7.1, yet Magento 2.3.5 is looking for it for some reason as it is not there, what may the reason be for that?

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-06-15 12:12
Hi @georgittanchev ,

Thanks for collaboration and contribution !

verified the issue 2.4-develop instance and the issue is not reproducible.

Kindly refer the below screenshots:
<img width="1505" alt="Screenshot 2023-06-15 at 5 36 37 PM" src="https://github.com/magento/magento2/assets/60198592/0b32d4df-6f82-4e62-b6d9-9fdfac04d373">

Steps to reproduce:
I.install magento install using composer command
2.Verify Front-end  Luma theme working or not

We are getting luma theme after composer installation and issue is not reproducible.Kindly recheck the behaviour in 2.4-develop instance as well as kindly update your magento 2.3.5 with latest version and recheck  the behaviour.

Let us know if are missing anything!

Thanks!

**Comment by georgittanchev** [comment] 2023-06-15 17:16
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-06-19 10:44
Hi @georgittanchev ,

Thanks for Contribution and collaboration!

Currently we are using magento 2.4 in Mac OS version 12.6.5 and we are using 2.4-develop branch because this is the latest development branch, and it might be possible the issue you mentioned is already been resolve in this branch.

Please try to reproduce the issue in 2.4-develop or latest stable version.

Thanks!

**Comment by engcom-Dash** [comment] 2023-07-06 12:51
Hi @georgittanchev ,

Do you need Any further investigation in this issue,If it is kindly let me know.

Thanks!

**Comment by engcom-Dash** [comment] 2023-07-12 06:51
Hi @georgittanchev ,

As we are not able to get the latest update on the issue. We are closing the issue for now. Please feel free to reopen it or ask us to reopen.

Thanks

**Closed as completed by engcom-Dash** 2023-07-12 06:51 UTC
Labels: Issue: needs update, Reported on 2.3.5
