### ISSUE TITLE
Two error messages when configurable product is having low stock 

### ISSUE THREAD

**Issue by rpeddinti** [magento/magento2#5707] opened 2016-07-20 10:34 UTC
## Steps to reproduce

![low stock](https://cloud.githubusercontent.com/assets/17040177/16983613/3fd46cec-4e93-11e6-9d2f-b94e6deefabb.png)
1. Install Magento CE2.1 from magento.com
2. Add Configurable Product to the cart with higher qty .
## Expected result
1. Configurable product should display single error message.
## Actual result
1. Error message appears twice: "
   We don't have as many "Tiberius Gym Tank" as you requested.
   We don't have as many "Tiberius Gym Tank-XS-Yellow" as you requested.
   ".
2.  image is attached

**Comment by duhon** [comment] 2016-07-25 12:30
Thanks for reporting this issue.

We've created internal ticket MAGETWO-55910 to fix it.

**Comment by quyendam2612** [comment] 2016-08-12 03:37
@duhon any update on this issue? thanks

**Comment by gemscng** [comment] 2017-08-20 14:47
Any update about this issue? Also encounter this in 2.1.5

**Comment by magento-engcom-team** [comment] 2017-10-12 10:48
@rpeddinti, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-12 10:48 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid

**Comment by ajaivijay2000** [comment] 2018-03-02 12:16
Can you please specify pull request id?

**Comment by aabumuslimov** [comment] 2018-05-17 23:55
please check this commit https://github.com/magento/magento2ce/commit/976dbc76e110c7aa47178e5bcddf6320bac4ef43
