### ISSUE TITLE
Estimate shipping button on cart no longer present

### ISSUE THREAD

**Issue by wsagen** [magento/magento2#2629] opened 2015-12-07 15:03 UTC
I'm working against v2.0.0 of Magento2 and noticed the "Get a Quote" button is missing from the cart shipping block. This was obviously in Magento 1.x and part of merchant beta version, and has since disappeared. Is that "by design" and if so, are you replacing with other functionality to update rates when a customer enters an address?

**Comment by ishakhsuvarov** [comment] 2015-12-07 22:15
@wsagen In versions 2.0.0 and later this button is removed is "by design".
Shipping rates (if applicable) and estimated order totals are now updated automatically as you fill the estimation form. Entered data will also be transferred to the checkout address form, if the user chooses to proceed.

**Comment by ishakhsuvarov** [comment] 2016-03-04 08:42
@wsagen Closing this ticket. Please reopen if you have any additional questions on this topic.

**Closed as completed by ishakhsuvarov** 2016-03-04 08:42 UTC
