### ISSUE TITLE
Magento set product to out of stock even with the backorder.

### ISSUE THREAD

**Issue by mohammadbharmal** [magento/magento2#36106] opened 2022-09-07 11:15 UTC
### Preconditions and environment

- Magento 2.4.2-p1

### Steps to reproduce

**Step 1:-** Login into Magento admin

**Step 2:-** Go to Magento Admin >> Catalog >> Product >> Edit Product >> Set any product qty 0 and enable backorder for that product and click on the save button.

**Step 3:-** Check stock status of that product in the admin (it's will be in stock).

**Step 4:-** Go to Magento Admin >> System >> Data Transfer >> Import >> import data for the above changed product 

### Expected result

Imported product should be a in-stock with the backorder. 

### Actual result

It's changed product status to the out of stock if qty=0 even with the backorder. 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2022-09-14 06:06
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-09-14 07:05
Hi @mohammadbharmal ,

We are trying to reproduce the issue in 2.4-develop branch.But we are not able to reproduce the issue.
Imported product should be a in-stock with the backorder.

**Screenshots:**
![Screenshot from 2022-09-14 12-29-30](https://user-images.githubusercontent.com/60198592/190084394-2d118f56-66e9-4e8a-bf35-1be706875a9d.png)
![Screenshot from 2022-09-14 12-25-28](https://user-images.githubusercontent.com/60198592/190084415-99ac1653-a522-4e4f-b653-c9c760415226.png)
![Screenshot from 2022-09-14 12-23-30](https://user-images.githubusercontent.com/60198592/190084446-b8234376-8e84-4ec7-ae78-ef7eeabae383.png)


**Steps to Reproduce:**
1.Install Magento instance
2.Set the product Quantity
3.Enable the Back order
4.Import the data for the Product
5. Imported successfully

Let Us know if we Missing anything!!!

Thnaks!!!

**Comment by mohammadbharmal** [comment] 2022-09-14 08:14
Hello @engcom-Dash,

Thank you for work on this issue.

I'll try on the above instance and will back to you.

**Comment by engcom-Dash** [comment] 2022-10-19 12:18
Hi @mohammadbharmal ,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2022-10-19 12:18 UTC
Labels: Issue: needs update, Reported on 2.4.2-p1
