### ISSUE TITLE
Admin panel is not accessible after limited permissions set to at least one admin account

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#25881] opened 2019-12-02 21:55 UTC
### Preconditions (*)

Magento is installed

## Steps to reproduce (*)

- Login to admin panel
- Go to System->User Roles
- Create a new role:
- In Role Resources check only Media Gallery
![image](https://user-images.githubusercontent.com/2028541/69998457-3e97f580-154e-11ea-85d7-7d8efd8ecfbc.png)
- Create a new admin user account and assign the created role to it
- Log out from admin panel
- Log in to admin panel as a newly created user
- Log in to admin panel as an admin having full permissions

### Expected result (*)
The new admin user is logged into the admin panel.
Other admin accounts are not affected.

### Actual result (*)
User is redirected to frontend page with status code 404.
Admin panel is not available for other admins with full permissions
![image](https://user-images.githubusercontent.com/51681379/69808832-21cb8d00-11f1-11ea-85cd-bcf9be32aca3.png)

### Additional Info

The issue can be reproduced if admin user role includes only ACL resources that are not associated with page/menu item in the admin panel

**Comment by krishprakash** [comment] 2019-12-03 00:31
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-12-03 00:31
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-12-03 00:31
Hi @krishprakash, here is your [Magento instance](https://i-25881-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25881-2-3-develop.instances.magento-community.engineering/admin](https://i-25881-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2019-12-03 01:13
Hi @sivaschenko.
I'm not able to reproduce the issue on 2.3 develop instance as provided steps by you.
I followed the steps below to reproduce the issue:
1. Login to admin panel
2. System > User Roles > Created a new role with only Media gallery permission
3. Create new user and assigned newly created role
4. Logout from main admin
5. Login with newly created admin role
6. Open the private window and login with main admin which have full permission
Let me know if I missed anything
Thanks

**Comment by krishprakash** [comment] 2019-12-03 04:59
Reproduced in my local vanilla instance.
Can not access the main admin as described in issue description.

![image](https://user-images.githubusercontent.com/46617848/70021736-bb12ee80-15b7-11ea-9bd0-f298281f1b7c.png)

**Comment by magento-engcom-team** [comment] 2019-12-03 05:00
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29321` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment] 2020-01-17 18:12
Hi @sivaschenko. Thank you for your report. 
The issue has been fixed in magento/magento2#25909 by @edenduong in 2.4-develop branch
Related commit(s):
 - [da1daaeeb64f29d7f23bc71e63987ffbc7994099](https://github.com/magento/magento2/commit/da1daaeeb64f29d7f23bc71e63987ffbc7994099)
 - [1f12acfbf94dcfc4acaeba7f74e1b78596817213](https://github.com/magento/magento2/commit/1f12acfbf94dcfc4acaeba7f74e1b78596817213)
 - [78bf9c21793fec6b3903e59cd1d36a720dfdac29](https://github.com/magento/magento2/commit/78bf9c21793fec6b3903e59cd1d36a720dfdac29)
 - [b7bc81fc6a4b04c68546096dd07214d50e2aa40d](https://github.com/magento/magento2/commit/b7bc81fc6a4b04c68546096dd07214d50e2aa40d)
 - [957f056adde00167bbde548b23a3fb190aa72522](https://github.com/magento/magento2/commit/957f056adde00167bbde548b23a3fb190aa72522)
 - [034a0ed158d3a69da40a3afdee218c20fe33a0e8](https://github.com/magento/magento2/commit/034a0ed158d3a69da40a3afdee218c20fe33a0e8)
 - [da17c67bc68de7020d777a15aa4ff7f985f7300f](https://github.com/magento/magento2/commit/da17c67bc68de7020d777a15aa4ff7f985f7300f)
 - [468da78a555d0a4dad5c17c8ab5caf8466069bca](https://github.com/magento/magento2/commit/468da78a555d0a4dad5c17c8ab5caf8466069bca)
 - [eee523002beb81bb5935bb278c363559daac0f57](https://github.com/magento/magento2/commit/eee523002beb81bb5935bb278c363559daac0f57)
 - [f5db9f664bcc45f18adc54a2987970f27c2cb068](https://github.com/magento/magento2/commit/f5db9f664bcc45f18adc54a2987970f27c2cb068)
 - [f07d0e16df431412b70d4a06b06eecfe65c69ad9](https://github.com/magento/magento2/commit/f07d0e16df431412b70d4a06b06eecfe65c69ad9)

The fix will be available with the upcoming 2.4.0 release.

**Closed as completed by VladimirZaets** 2020-01-17 18:13 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Backend, Component: Acl, Fixed in 2.4.x
