### ISSUE TITLE
Configurable product children saleable issue this.products.length is always 1

### ISSUE THREAD

**Issue by ciancastillo** [magento/magento2#36479] opened 2022-11-15 06:35 UTC
### Preconditions and environment

- Magento 2.4.5-p1 deadstock
- PHP8.1-FPM
- NGINX
- Ubuntu 20

### Steps to reproduce

1. Create a configurable product
2. Make 1 child product out of stock (Make sure Stores->Configuration->Catalog->Inventory->Stock Options->Display Out of Stock Products->Yes)
3. Visit the product in store front
4. The out of stock product is showing as if it is available, no strike through.

### Expected result

The out of stock child product should be disabled and with strike-through

### Actual result

The out of stock product is showing as if it is available. Will confuse customers

### Additional information

![image](https://user-images.githubusercontent.com/4427871/201844758-1cf83bbc-59b9-45c2-bdf8-b7f895680a83.png)
`this.products.length` always return 1

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-11-15 10:11
Hi @ciancastillo,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**
1.Create a configurable product
2.Make 1 child product out of stock (Make sure Stores->Configuration->Catalog->Inventory->Stock Options->Display Out of Stock Products->Yes)
3.Visit the product in store front


<img width="1366" alt="Screenshot 2022-11-15 at 12 22 31 PM" src="https://user-images.githubusercontent.com/51680745/201892343-d1c6b21f-4782-4c4b-b3db-82c190d407c4.png">




<img width="1310" alt="Screenshot 2022-11-15 at 12 22 38 PM" src="https://user-images.githubusercontent.com/51680745/201892402-3b9dca63-11be-4d42-bd9f-ea8041129c3b.png">


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by APanteleychuk** [comment] 2022-11-16 13:48
@magento give me 2.4.4 instance

**Comment by ciancastillo** [comment] 2022-11-16 14:59
@magento give me 2.4.5-p1 instance

**Comment by engcom-Bravo** [comment] 2022-11-17 06:19
@magento give me 2.4.5 instance

**Comment by engcom-Bravo** [comment] 2022-11-17 06:41
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-17 10:53
Hi @ciancastillo,

Thanks for your Update.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.

<img width="1366" alt="Screenshot 2022-11-15 at 12 22 31 PM" src="https://user-images.githubusercontent.com/51680745/201892343-d1c6b21f-4782-4c4b-b3db-82c190d407c4.png">





<img width="1310" alt="Screenshot 2022-11-15 at 12 22 38 PM" src="https://user-images.githubusercontent.com/51680745/201892402-3b9dca63-11be-4d42-bd9f-ea8041129c3b.png">



It is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by subbu1993** [comment] 2022-11-23 20:35
@magento give me 2.4.3 instance

**Comment by engcom-Bravo** [comment] 2022-12-01 06:10
Hi @ciancastillo,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-12-01 06:10 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.5-p1
