### ISSUE TITLE
Unable to unserialize value. Magento 2.3.4 [new update]

### ISSUE THREAD

**Issue by amiyoghoshstar** [magento/magento2#26606] opened 2020-01-31 09:44 UTC
### Summary (*)

1. After upgrading Magento CE 2.3.3 to 2.3.4, I'm facing this issue.
2. The same issue happened in Magento CE 2.3.3 but I followed the answer to the stack exchange question and fixed it. Link : https://magento.stackexchange.com/questions/194010/magento-2-2-unable-to-unserialize-value 
3. Cannot able to create an account, login. Not able to check customers from admin dashboard

### Examples (*)

`function is_serialized($value, &$result = null)
    {
        // Bit of a give away this one
        if (!is_string($value))
        {
            return false;
        }
        // Serialized false, return true. unserialize() returns false on an
        // invalid string or it could return false if the string is serialized
        // false, eliminate that possibility.
        if ($value === 'b:0;')
        {
            $result = false;
            return true;
        }
        $length = strlen($value);
        $end    = '';
        switch ($value[0])
        {
            case 's':
                if ($value[$length - 2] !== '"')
                {
                    return false;
                }
            case 'b':
            case 'i':
            case 'd':
                // This looks odd but it is quicker than isset()ing
                $end .= ';';
            case 'a':
            case 'O':
                $end .= '}';
                if ($value[1] !== ':')
                {
                    return false;
                }
                switch ($value[2])
                {
                    case 0:
                    case 1:
                    case 2:
                    case 3:
                    case 4:
                    case 5:
                    case 6:
                    case 7:
                    case 8:
                    case 9:
                        break;
                    default:
                        return false;
                }
            case 'N':
                $end .= ';';
                if ($value[$length - 1] !== $end[0])
                {
                    return false;
                }
                break;
            default:
                return false;
        }
        if (($result = @unserialize($value)) === false)
        {
            $result = null;
            return false;
        }
        return true;
    }`
Added this code to `/vendor/magento/framework/Serialize/Serializer/Json.php`

**Comment by mrtuvn** [comment] 2020-02-01 02:04
@Amiyo-Ghosh if you used redis make sure check redis configuration your env.php in app/etc
You can re-config redis with commands below. This is recommended from magento
>bin/magento setup:config:set --session-save=redis --session-save-redis-host=redis --cache-backend-redis-db=0
>bin/magento setup:config:set --cache-backend=redis --cache-backend-redis-server=redis --cache-backend-redis-db=1

try clear cache and flush redis

**Comment by engcom-Alfa** [comment] 2020-02-11 14:02
Hi @Amiyo-Ghosh. Thank you for your report.
 Unfortunately, we are not able to reproduce this issue on fresh 2.4-develop and  2.3.4 instances.
Everything works correctly.
So, we have to close it.
Probably you are using Redis and need to clear the cache `redis-cli flushall`.
Hope this helps you.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-02-11 14:02 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is not valid, Triage: Dev.Experience, Reported on 2.3.3

**Comment by AndyJAllen** [comment] 2020-06-18 11:11
> 
> ### Summary (*)
> 
>     1. After upgrading Magento CE 2.3.3 to 2.3.4, I'm facing this issue.
> 
>     2. The same issue happened in Magento CE 2.3.3 but I followed the answer to the stack exchange question and fixed it. Link : https://magento.stackexchange.com/questions/194010/magento-2-2-unable-to-unserialize-value
> 
>     3. Cannot able to create an account, login. Not able to check customers from admin dashboard
> 
> 
> ### Examples (*)
> 
> `function is_serialized($value, &$result = null) { // Bit of a give away this one if (!is_string($value)) { return false; } // Serialized false, return true. unserialize() returns false on an // invalid string or it could return false if the string is serialized // false, eliminate that possibility. if ($value === 'b:0;') { $result = false; return true; } $length = strlen($value); $end = ''; switch ($value[0]) { case 's': if ($value[$length - 2] !== '"') { return false; } case 'b': case 'i': case 'd': // This looks odd but it is quicker than isset()ing $end .= ';'; case 'a': case 'O': $end .= '}'; if ($value[1] !== ':') { return false; } switch ($value[2]) { case 0: case 1: case 2: case 3: case 4: case 5: case 6: case 7: case 8: case 9: break; default: return false; } case 'N': $end .= ';'; if ($value[$length - 1] !== $end[0]) { return false; } break; default: return false; } if (($result = @unserialize($value)) === false) { $result = null; return false; } return true; }`
> Added this code to `/vendor/magento/framework/Serialize/Serializer/Json.php`

FYI using this method corrupts data in the order tables and you will experience new problems looking at historical data (from both back end and when logged in as customer to look at past order details). I had used that method through my 2.2.x upgrades because I also experienced a bunch of serialize problems; but then I had to create myself a php program to fix a bunch of encoding issues that were being stored.

**Comment by StruggleSnuggl3** [comment] 2020-07-31 16:04
I have a similar issue after upgrading from 2.3.5-p2 to 2.4;

I see I am running Redis Server 6.0.6; is this supported by Magento 2.4?

**Comment by StruggleSnuggl3** [comment] 2020-07-31 20:50
This is the error:

`1 exception(s):
Exception #0 (InvalidArgumentException): Unable to serialize value. Error: Malformed UTF-8 characters, possibly incorrectly encoded

Exception #0 (InvalidArgumentException): Unable to serialize value. Error: Malformed UTF-8 characters, possibly incorrectly encoded`

**Comment by tripathiprakash** [comment] 2020-08-18 08:01
> > ### Summary (*)
> > ```
> > 1. After upgrading Magento CE 2.3.3 to 2.3.4, I'm facing this issue.
> > 
> > 2. The same issue happened in Magento CE 2.3.3 but I followed the answer to the stack exchange question and fixed it. Link : https://magento.stackexchange.com/questions/194010/magento-2-2-unable-to-unserialize-value
> > 
> > 3. Cannot able to create an account, login. Not able to check customers from admin dashboard
> > ```
> > 
> > 
> > ### Examples (*)
> > `function is_serialized($value, &$result = null) { // Bit of a give away this one if (!is_string($value)) { return false; } // Serialized false, return true. unserialize() returns false on an // invalid string or it could return false if the string is serialized // false, eliminate that possibility. if ($value === 'b:0;') { $result = false; return true; } $length = strlen($value); $end = ''; switch ($value[0]) { case 's': if ($value[$length - 2] !== '"') { return false; } case 'b': case 'i': case 'd': // This looks odd but it is quicker than isset()ing $end .= ';'; case 'a': case 'O': $end .= '}'; if ($value[1] !== ':') { return false; } switch ($value[2]) { case 0: case 1: case 2: case 3: case 4: case 5: case 6: case 7: case 8: case 9: break; default: return false; } case 'N': $end .= ';'; if ($value[$length - 1] !== $end[0]) { return false; } break; default: return false; } if (($result = @unserialize($value)) === false) { $result = null; return false; } return true; }`
> > Added this code to `/vendor/magento/framework/Serialize/Serializer/Json.php`
> 
> FYI using this method corrupts data in the order tables and you will experience new problems looking at historical data (from both back end and when logged in as customer to look at past order details). I had used that method through my 2.2.x upgrades because I also experienced a bunch of serialize problems; but then I had to create myself a php program to fix a bunch of encoding issues that were being stored.

Hello,
I recently updated to Magento 2.3.5-p1 and I have this force serialize code but when I check my exception Log there are still error messages indicating Unable to unserialize value. You have mentioned that you created a program. Can you suggest how to solve this issue?

**Comment by uttam-dhameliya** [comment] 2020-10-08 14:34
Was facing the same issue, after even changing json.php code.. 

it got solved by just changing PHP version according to magento's  requirement.
thanks
