### ISSUE TITLE
_determineProductData Does not function properly for out of stock products

### ISSUE THREAD

**Issue by jlenzstaysafe** [magento/magento2#35482] opened 2022-05-16 14:42 UTC
### Preconditions (*)

1. Magento 2.4.3-p1

### Steps to reproduce (*)

1. Set Display Out of Stock Products = Yes
2. Call function Magento_Swatches::web/js/swatch-renderer.js -> _determineProductData()

### Expected result (*)

1. isInProductView should return false when on category page

### Actual result (*)

1. isInProductView returns true on category page because the selector "price-box.price-final_price" is looking for a price box which does not load for out of stock products: 
```
productId = this.element.parents('.product-item-details')
                    .find('.price-box.price-final_price').attr('data-product-id');
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2022-05-17 08:20
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-05-17 09:03
Hello @jlenzstaysafe,

Thanks for posting!

We have tried to reproduce the issue in Magento 2.4-develop branch but the issue is not able to reproduce. For us, for the out of stock products function `_determineProductData` is not calling. We have followed below steps to reproduce the issue:

### Steps
1. Marked 2 products as OOS i.e. `Montana Wind Jacket`, `Proteus Fitness Jackshirt `:
<img width="904" alt="image" src="https://user-images.githubusercontent.com/51681618/168770366-002abdc7-c4fb-4fa1-b7c8-f2616bf9447f.png">

2. Set breakpoint in line number `390` in file named `swatch-renderer.js`:
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/51681618/168770606-226b7c47-15f8-4f78-b98f-ec528e568537.png">

3. Refresh the page, and check if the function is calling for OOS products, The product id for both products are `420` and `436`, which are not visible in below screencast:

https://user-images.githubusercontent.com/51681618/168773413-575b08d4-a4be-4110-97ea-85012c86ac7e.mp4

Please let us know in case we have missed anything.

Thanks

**Comment by jlenzstaysafe** [comment] 2022-05-17 17:51
The function isn't called natively, but if you want to render swatches for out of stock products, it will be called.  Granted, this is a customization we're developing on our end, but I think the code should have better detection other than looking for a price box...  For example, adding a 'data-product-id' field to the parent <li> or something along those lines.  The current implementation feels a bit "hacky"

**Comment by engcom-Hotel** [comment] 2022-06-03 06:42
Dear @jlenzstaysafe,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-06-03 06:42 UTC
Labels: Triage: Dev.Experience, Issue: needs update
