### ISSUE TITLE
Admin configurable product edit: Notice: Undefined variable

### ISSUE THREAD

**Issue by farior** [magento/magento2#6378] opened 2016-08-29 13:09 UTC
Notice on configurable product edit after upgrade from 2.0.7 to 2.0.9
### Preconditions
1. Nginx 1.9.14
2. PHP 7.0.6
3. Magento 2.0.9
### Steps to reproduce
1. Go to admin > Products > Catalog
2. Click edit on configurable product
### Expected result
1. Product edit page should open without notices, warning, errors etc.
### Actual result
1. Notice: Undefined variable: websiteId in /var/www/vendor/magento/module-catalog/Model/ResourceModel/Product/Collection.php on line 2109

**Comment by NadiyaS** [comment] 2016-08-31 10:31
Hi @farior ,
we can not reproduce this bug. Can you provide more information to reproduce it (do you have some specified attributes for store, etc)
Thanks

**Comment by developer-lindner** [comment] 2016-08-31 12:24
@farior Update to 2.1.1 and report back or close this ticket.

**Comment by farior** [comment] 2016-09-01 11:09
@developer-lindner After upgrade to 2.1.1 problem has gone, so bug reproduces only in 2.0.9

**Comment by developer-lindner** [comment] 2016-09-01 11:24
@farior Then close this ticket...

**Comment by Gorkyman** [comment] 2016-09-01 19:44
Got the same error while migrating from 1.6.2.0 to 2.0.9. 

This issue is related to a function `public function addTierPriceData()` in `module-catalog/Model/ResourceModel/Product/Collection.php`. $websiteId is only declared in if condition. It seems like it can happen that attribute doesn't have a global scope and storeId is not set on the collection. It could be that this is already solved in 2.1.1 (haven't checked yet).

**Comment by NadiyaS** [comment] 2016-09-07 11:40
Hi @farior , @Gorkyman ,
the issue was reopened. 
Thank you for reporting it. Internal ticket MAGETWO-58139 was created

**Comment by TommyKolkman** [comment] 2016-09-16 12:33
Since I don't want to upgrade to 2.1.1 yet (too much bugs still), I want to know if there's a fix yet. @Gorkyman, do you have a quick fix maybe?

**Comment by Gorkyman** [comment] 2016-09-16 12:42
@TommyKolkman

```
public function addTierPriceData()
    {
        if ($this->getFlag('tier_price_added')) {
            return $this;
        }

        $tierPrices = [];
        $productIds = [];
        foreach ($this->getItems() as $item) {
            $productIds[] = $item->getId();
            $tierPrices[$item->getId()] = [];
        }
        if (!$productIds) {
            return $this;
        }

        /** @var $attribute \Magento\Catalog\Model\ResourceModel\Eav\Attribute */
        $attribute = $this->getAttribute('tier_price');
        $websiteId = 0;
        if (!$attribute->isScopeGlobal() && null !== $this->getStoreId()) {
            $websiteId = $this->_storeManager->getStore($this->getStoreId())->getWebsiteId();
        }

        $connection = $this->getConnection();
        $columns = [
            'price_id' => 'value_id',
            'website_id' => 'website_id',
            'all_groups' => 'all_groups',
            'cust_group' => 'customer_group_id',
            'price_qty' => 'qty',
            'price' => 'value',
            'product_id' => 'entity_id',
        ];
        $select = $connection->select()->from(
            $this->getTable('catalog_product_entity_tier_price'),
            $columns
        )->where(
            'entity_id IN(?)',
            $productIds
        )->order(
            ['entity_id', 'qty']
        );

        if ($websiteId == '0') {
            $select->where('website_id = ?', $websiteId);
        } else {
            $select->where('website_id IN(?)', ['0', $websiteId]);
        }

        foreach ($connection->fetchAll($select) as $row) {
            $tierPrices[$row['product_id']][] = [
                'website_id' => $row['website_id'],
                'cust_group' => $row['all_groups'] ? $this->_groupManagement->getAllCustomersGroup()->getId() : $row['cust_group'],
                'price_qty' => $row['price_qty'],
                'price' => $row['price'],
                'website_price' => $row['price'],
            ];
        }

        /* @var $backend \Magento\Catalog\Model\Product\Attribute\Backend\Tierprice */
        $backend = $attribute->getBackend();

        foreach ($this->getItems() as $item) {
            $data = $tierPrices[$item->getId()];
            if (!empty($data) && $websiteId) {
                $data = $backend->preparePriceData($data, $item->getTypeId(), $websiteId);
            }
            $item->setData('tier_price', $data);
        }

        $this->setFlag('tier_price_added', true);
        return $this;
    }
```

@NadiyaS This is already resolved in 2.1.1

**Comment by NadiyaS** [comment] 2016-09-16 12:58
Hi @Gorkyman ,
Yes, this issue does not exist in 2.1.1. Internal ticket MAGETWO-58139 was created for 2.0.x version.

**Comment by maghamed** [comment] 2017-03-01 16:54
we have the fix for current issue in our develop branch https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Model/ResourceModel/Product/Collection.php#L2120-L2124

**Comment by magento-engcom-team** [comment] 2017-10-10 08:30
@farior, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-10 08:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid
