### ISSUE TITLE
Not able to sync products cost using api /rest/V1/products/cost

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#28372] opened 2020-05-26 14:18 UTC
**Summary of the issue:** 
Not able to sync products cost using the api /rest/V1/products/cost
Followed the Documentations https://devdocs.magento.com/redoc/2.3/admin-rest-api.html#operation/catalogCostStorageV1UpdatePost

**Information on your environment :** 
Magento 2 Local environment. 

**Steps to reproduce :** 
A Configure the postman 
B Make an API call using the below details 
API : rest/V1/products/cost
Request : {"prices":[{"cost":100.0,"store_id":0,"sku":"Test Prdouct-104"}]}

**Expected Results:** 
[
  {
    "message": "string",
    "parameters": [
      "string"
    ],
    "extension_attributes": {}
  }
]
**Actual Result** 
[]

**Comment by sambath1293** [comment] 2020-05-27 15:33
Hi @webgility-amazonapi this is a duplicate of https://github.com/magento/magento2/issues/28374 so closing this bug.

**Closed as completed** 2020-05-27 15:34 UTC
Labels: duplicate, Issue: Format is not valid, Reported on 2.3.x
