### ISSUE TITLE
Samesite Cookie = Lax on 2.4.3-p1 for Payflow Pro

### ISSUE THREAD

**Issue by live4soccer7** [magento/magento2#34472] opened 2021-10-28 17:30 UTC
### Preconditions (*)

1. 2.4.3-p1
2. Production, not been able to reproduce in sandbox Payflow

### Steps to reproduce (*)

1. Checkout with CC payment in chrome based browser (Edge, Chrome, Brave) and cookie is set to LAX, Secure instead of None, Secure. This allows the redirect and response for the gateway to not work and the "spinner" is never ending because the requests can never finish. This leads to the customer not being able to check out.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2. The checkout should finish properly and the order should be placed

### Actual result (*)

1. [Screenshots, logs or description]
2. The check out can not finish and the order is not placed. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”.
![cookie_1](https://user-images.githubusercontent.com/62921422/139305630-3d07d774-18b7-4428-8688-cb8b13811ca8.png)
![cookie_2](https://user-images.githubusercontent.com/62921422/139305642-2835e9ed-75fb-4de5-b58c-a920882760e8.png)
_

**Comment by live4soccer7** [comment] 2021-10-29 21:14
For now, we have had to result in changing payment gateways since payflow pro doesn't work properly. I would still like to see this resolved though.

**Comment by ihor-sviziev** [comment] 2021-11-04 06:39
@sidolov FYI I set priority to P1 as this issue prevents placing an order using PayPal Payflow Pro

**Comment by live4soccer7** [comment] 2021-11-04 15:45
That's great to hear. I look forward to seeing the resolution. We have had to switch payment gateways until this is resolved.

**Comment by anki7d** [comment] 2022-04-07 11:26
Any Update on This Issue ?

**Comment by dchaykas** [comment] 2022-06-08 20:31
Is there an update here? Same behavior for another payment gateway using 2.4.3-p1.

**Comment by live4soccer7** [comment] 2022-06-08 20:41
No update. We had to switch payment gateways. You would think paypal would at least help resolve this bug since now we are not paying paypal any merchant processing fees because we switched to another vendor. A bit frustrating. It cost us a bunch of time and money.

**Comment by engcom-November** [comment] 2022-10-27 08:11
Hi @live4soccer7 ,
Thank you for reporting and collaboration. Unable to reproduce the issue on 2.4-develop instance in sandbox mode. We cannot able to test it in Production mode as its not recommended to verify. Kindly recheck on 2.4-develop instance with Sandbox mode and elaborate the steps so that it will help us to reproduce in developer environment to fix it further.
Thank you.

**Comment by engcom-November** [comment] 2022-11-11 07:38
Hi @live4soccer7 ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-11-11 07:38 UTC
Labels: Priority: P1, Severity: S0, Progress: done, Issue: ready for confirmation, Issue: needs update, Area: Payments, Reported on 2.4.3-p1
