### ISSUE TITLE
I search the fix for multishipping and virtual product

### ISSUE THREAD

**Issue by jdevosMagento** [magento/magento2#37033] opened 2023-03-08 13:44 UTC
### Summary

Hello,

I search a fix on the 2.3.6 in relation with : 

```
**Shipping**

You can now ship an order to multiple addresses if one of the ordered products is a virtual product. Previously, Magento successfully placed the order for the physical products, but the virtual product order was empty.
```

This is describe on the release note 2.3.6
https://devdocs.magento.com/guides/v2.3/release-notes/open-source-2-3-6.html

I have actually this issue on the 2.4.5 and I want to check that the fix is applied to our specific code.

Currently, if I have a quote with a virtual product and a physical product in multishipping, the virtual product disappears.

Thank you

### Examples

No example

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-03-09 06:09
@magento give me 2.4-develop instance

**Comment by jdevosMagento** [comment] 2023-03-09 08:51
Hello, i have fund this link in relation :
https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/troubleshooting/miscellaneous/magento-2.3.5-known-issue-virtual-product-multi-ship-orders.html?lang=en

But I still can't find the code that fixes this in 2.3.6

**Comment by engcom-Bravo** [comment] 2023-03-09 13:05
Hi @jdevosMagento,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

We are able to place the order with virtual and physical product with multishipping.

<img width="1451" alt="Screenshot 2023-03-09 at 12 07 17 PM" src="https://user-images.githubusercontent.com/51680745/224031635-3ba0fabf-97ad-4dc7-8c55-7470f8118559.png">



![Review-Order-Magento-Commerce](https://user-images.githubusercontent.com/51680745/224031684-b19c084e-565b-4f53-96a9-9f64099a3b56.png)


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-03-10 12:05
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-03-10 13:45
Hi @jdevosMagento,

Thanks for your update.

Please check the below PR https://github.com/magento/magento2/pull/29269 related to virtual products with multishipping.

Kindly check the below commit.

12ecf8a656837a0aa6c457250a49e8935243243a



Kindly let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-03-23 06:05
Hi @jdevosMagento,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-03-23 06:05 UTC
Labels: Issue: needs update, Reported on 2.4.5
