### ISSUE TITLE
Magento 2: Admin special price changes are not refreshing minicart immediately

### ISSUE THREAD

**Issue by shahankitb997** [magento/magento2#9043] opened 2017-03-29 07:08 UTC
### Preconditions

1. Using Magento 2.1.5 CE

### Steps to reproduce

1.  Add Product to Cart with it's original value.
2.  Apply Special Price for that product from Admin
3.  Mini cart is not reflecting with special price

![capture](https://cloud.githubusercontent.com/assets/20528998/24442628/82e6de24-1491-11e7-85af-47650fe127c7.png)

http://magento.stackexchange.com/questions/166641/magento-2-admin-price-changes-are-not-refreshing-minicart-immediately-till-chec

### Expected result

1.  In Mini Cart It should reflect 

### Actual result

1. Mini Cart shows Old Price Instead of Special Price

@magento-admin @magento-team

**Comment by korostii** [comment] 2017-03-30 09:20
Possible duplicate of #3625

**Comment by orlangur** [comment] 2017-03-30 09:40
It is supposed to work this way until push notifications from Admin side are implemented.

For instance, when you change name of user in Admin UI you will not see it in browser immediately.

**Comment by korostii** [comment] 2017-03-30 12:31
```
- Here, we made a teapot. Take and use it and be happy! 
- Okay... 
(time passes...) 
- Hey, it doesn't heat up to more than 90 degrees. How am I supposed to boil the water in it?
- Oh, you're just supposed to take it up the mountain Everest first. But that's just until the heating part gets fully implemented.
- ???
```

"It is supposed to work this way" sounds a bit exaggerated.
Wait, is there more stuff which is just "not implemented yet"? 
Is there a list, or a roadmap publicly available?
Also, when will the Magento2 be production-ready?

**Comment by orlangur** [comment] 2017-03-30 12:50
I believe it is production-ready already (but it is a bit off-topic...).

Here is an official response I can share with you: https://github.com/magento/magento2/issues/8579#issuecomment-280467726

Yeah, some visibility on such pain points would be really appreciated.

**Comment by magento-engcom-team** [comment] 2017-09-27 22:01
@shahankitb997, thank you for your report.
We've created internal ticket(s) MAGETWO-80200 to track progress on the issue.

**Comment by ishakhsuvarov** [comment] 2018-03-06 13:39
Hi @shahankitb997 
Thank you for the detailed report on the issue.
From the engineering perspective this issue is caused by the same thing as https://github.com/magento/magento2/issues/3625
I am closing this report now to simplify tracking.

**Closed as completed by ishakhsuvarov** 2018-03-06 13:39 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid
