### ISSUE TITLE
Toolbar is not align proper in mywishlist page in mobile view

### ISSUE THREAD

**Issue by cedarvinda** [magento/magento2#30432] opened 2020-10-10 11:08 UTC
**Description**
Toolbar is not align proper in MyWishlist page in mobile view

### Preconditions (*)
1. Magento2.4
2. php7.4

### Steps to reproduce (*)
1) open magento base url.
2) tab sign in on top right of screen.
3) enter email id and password to sign in your account.
4) go to my wishlist page and open mobile view.
5) check toolbar-amount and limiter design in mobile view (and compare with my orders page in mobiel view)

### Expected result (*)
![wishlist_solution_1](https://user-images.githubusercontent.com/26018716/95653506-d1160780-0b16-11eb-9c1e-e2c693766598.png)

### Actual result (*)
![wishlist_issue_1](https://user-images.githubusercontent.com/26018716/95653514-d83d1580-0b16-11eb-968a-37865fa9a222.png)

**Comment by cedarvinda** [comment] 2020-10-10 11:12
#dmcdindia2020

**Comment by magento-engcom-team** [comment] 2020-10-10 11:19
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38336` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by cedarvinda** [comment] 2020-10-10 11:19
I am working in this issue.

**Comment by engcom-Bravo** [comment] 2024-05-28 06:21
Hi @cedarvinda,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshot.

<img width="321" alt="Screenshot 2024-05-28 at 11 49 29" src="https://github.com/magento/magento2/assets/51680745/dc09854d-a5a2-4c89-92ed-b25a1c45ded5">


Toolbar is aligning properly in Mobileview.

Hence We are Closing this issue.

Thsnks.

**Closed as completed by engcom-Bravo** 2024-05-28 06:21 UTC
Labels: Issue: Ready for Work, Component: Customer, Issue: Clear Description, Issue: Confirmed, Area: Design/Frontend, Reproduced on 2.4.x, Severity: S4, Priority: P4, Progress: done, Event: dmcdindia2020, Reported on 2.4.0
