### ISSUE TITLE
Credit Memo - Wrong tax calculation!

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#10982] opened 2017-09-21 08:41 UTC
### Preconditions

1. Magento 2.1.7 via download 
2. Nginx, php7, varnish, redis

### Steps to reproduce

1. Create tax class for product with 19%
2. Create Shipping tax class with 19%
3. Order a product with shipping costs
4. create a credit memo of the product cost (with the shipping costs)

### Expected result

1. The credit memo (for the article only)  includes just the tax for the product - not the shipping tax of course

### Actual result

1. The credit memo includes also the shipping tax which is totally wrong as the shipping costs where not refunded. Screens attached.

I think there are 10-20 tickets reported nearly close to this one  - i am not shure why the magento team does not check all aspects of the credit memo to get rid of all bugs. Also this is worst case with payment methods like PayPal which refund the credit memo amount automatically - so this leads to serious problems in the accounting.

![1](https://user-images.githubusercontent.com/16196483/30686662-3c9dcd1c-9eb9-11e7-8ebc-4f2c05e92678.png)
![2](https://user-images.githubusercontent.com/16196483/30686663-3cdbe430-9eb9-11e7-9ed1-45440f4f81c0.png)

There is also a massive bug in the credit memo creation. The total amount does not change in the credit memo backend if you change the Adjustment Fee/ Refund at all - Using Safari for Mac. Could you pls also check this!

**Comment by andidhouse** [comment] 2017-09-21 09:27
This only happens sometimes - some refunds are ok - some have a calculation error.

I am also questioning why there are two ways to refund an order:

1. Create a credit memo over the order page directly
2. Create a credit memo over the invoice page

We realized this bugs only appeares on the credit creation when we do a credit memo over the invoice (which needs to be done to create an online refund).

Not shure why there are two ways?

**Comment by magento-engcom-team** [comment] 2017-10-20 10:10
@andidhouse, thank you for your report.
We've created internal ticket(s) MAGETWO-82400 to track progress on the issue.

**Comment by ste88** [comment] 2018-05-10 09:50
Hi, 
we have reproduced the problem only with the "online" credit memo created from the invoice page.
Offline credit memo works correctly.

Hope it is useful.

**Comment by ottosschweiz** [comment] 2018-06-20 06:14
Hello,

Has something happened since this issue was reported?
Or is there a known workaround to fix this problem?

It's just a really bad thing when those amounts are not correct on online credit memos.

Thank you

**Comment by vseager** [comment] 2018-10-05 09:09
A year since this issue was raised and still no resolution or known workaround?!

**Comment by kanduvisla** [comment] 2018-10-25 14:01
We just encountered this issue today in a Magento 2.2.6 shop which has been recently updaten from Magento 2.1.15. The order was placed in 2.1, but the credit memo was created in 2.2 (due to the passing of time).

We are unable to reproduce this issue on our dev-setup. Also, I cannot seem to find how you can create a credit memo from the invoice page. Is this feature removed in Magento 2.2?

**Comment by sdzhepa** [comment] 2019-04-30 19:54
Hello @andidhouse @ottosschweiz @vseager @kanduvisla 

Thank you for contribution and collaboration!

The corresponding internal tickets `MAGETWO-91769`, `MAGETWO-82400` were fixed and closed by Magento team

Delivered to `2.3-develop` branch and should be available with **2.3.1 release**
Please see details in the next commits:
- 6cc067a
- bb65b43
- 39dfb2b
- 408c135
- b7288e6
- 1238a5c

Delivered to `2.2-develop` branch and should be available with **2.2.8 release**
Please see details in the next commits:
- de3df20
- 303f06b

**Closed as completed by sdzhepa** 2019-04-30 19:54 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid
