### ISSUE TITLE
Stock filter ( quantity_and_stock_status ) is not displayed in layered navigation

### ISSUE THREAD

**Issue by hiren-aimsinfosoft** [magento/magento2#26172] opened 2019-12-24 11:47 UTC
### Preconditions (*)
1. Magento 2.4-develop
2. Display out of stock product in listing page

### Steps to reproduce (*)`
1. Configure `quantity_and_stock_status` attribute according https://docs.magento.com/user-guide/catalog/navigation-layered-filterable-attributes.html#step-1-set-up-the-attribute-properties
![image](https://user-images.githubusercontent.com/51681379/97003776-a2e7ed00-1544-11eb-880e-ac3803441e17.png)
![image](https://user-images.githubusercontent.com/51681379/97003682-73d17b80-1544-11eb-9a82-7b72d210910f.png)
2. Open any anchor category from the frontend 
3. Attribute `quantity_and_stock_status` is not present in layered navigation 

### Expected result (*)

1. Attribute `quantity_and_stock_status` is should be present in layered navigation or 'Use in Layered Navigation' option should be disabled for this attribute

### Actual result (*)
1. Attribute `quantity_and_stock_status` is not present in layered navigation 
![image](https://user-images.githubusercontent.com/51681379/97004264-7aacbe00-1545-11eb-97d9-30c16a74d41c.png)

**Comment by daweedco** [comment] 2020-03-27 12:19
I have the same issue

**Comment by wb-magma** [comment] 2020-04-01 11:51
I have the same issue

**Comment by sciola** [comment] 2020-04-06 12:41
I have the same issue

**Comment by daweedco** [comment] 2020-05-18 13:04
still no update ???

**Comment by magento-engcom-team** [comment] 2020-10-23 13:57
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38686` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Closed as completed** 2020-11-13 23:26 UTC
Labels: Area: Frontend, Issue: Confirmed, Area: Design/Frontend, Component: LayeredNavigation, Reproduced on 2.4.x, Priority: P1, Severity: S1, Progress: done

**Comment by markhyng** [comment] 2020-12-02 03:28
which version or PR fix this problem?

**Comment by markhyng** [comment] 2020-12-10 08:28
Hi @magento-engcom-team, any update?

**Comment by msyhr** [comment] 2021-01-22 16:05
@magento-engcom-team also interested

**Comment by sdzhepa** [comment] 2021-01-29 21:16
Updates for this issue:

This public issue report was closed by an automated system- bot which synchronized public and internal backlog.
It happened because internal ticket `MC-38686` was closed with _Wont Fix_ resolution
`MC-38686` has a huge thread of comments and discussions and linked tickets
Summary and main statements:
-	Functionality described in the issue and attribute(quantity_and_stock_status) related to Magento CatalogInventory module.
-	CatalogInventory module was marked as deprecated since 2.3.0 release.
-	Magento has a plan to remove CatalogInventory module in the nearest future
-	Functionality will be reviewed and migrated/reimplemented from legacy CatalogInventory to MSI(Multi-Source Inventory). 
-	Problem described in issue #26172 is not trivial and requires solid development in the module that will be removed. Magento does not have plans to work on it but instead, this functionality will be re-considered in the scope of migration tasks.

That's all information that I found and can share now.

**Comment by TheRealHunzik** [comment] 2021-04-26 07:42
I am facing this issue in Magento 2.3.4-p2 is there any solution?

**Comment by nordcomputer** [comment] 2021-07-23 09:03
I created an extension, that sets a newly created attribute "filter_stock" to simple products according to the stock status via cronjob - its not a perfect solution, but it may help somebody:
https://github.com/nordcomputer/magento2-stockfilter

**Comment by gfrey-namcopool** [comment] 2022-06-09 02:01
Any update on this?
