### ISSUE TITLE
Magento 2. 4.0_ Product File Import Error: We can't provide the upload settings right now.

### ISSUE THREAD

**Issue by Hollgr** [magento/magento2#33002] opened 2021-05-13 05:04 UTC
### Preconditions (*)

Hi There, I have zero development experience but our IT manager walked out so trying to solve some immediate problems.  Trying to upload import product cvs file, but when I go into import, there is a notice saying "We can't provide the upload settings right now."  Has anyone got any thoughts on what might be causing this? 

If I Ignore it and continue to try to upload the import file, it gives me the generic error "The File Was Not Uploaded" error. 
I have imported product using this method and template previously and work fine. 

Has anyone come accross this before?

The import file is a CSV
I have checked the max upload file limit 
I have checked all permissions are set to 777. 

1. using Magento version: 2.4.0

### Steps to reproduce (*)

1.log into magneto admin (developer mode) 
2.Opened System>Imports
3. Notification appears at top of page when loads.  

### Expected result (*)

1. Produts upload or update into catalogue
2.

### Actual result (*)

1. ![image](https://user-images.githubusercontent.com/84116488/118079753-11669c80-b3fc-11eb-862a-b0619bf6cc58.png)
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Oscar** [comment] 2021-05-13 13:12
Hi @Hollgr  ! Thank you for your report.
Unfortunately, we are not able to reproduce the issue. Looks like we miss some important preconditions, so may you please recheck and update description?

**Comment by engcom-Oscar** [comment] 2021-05-27 07:14
I have to close this ticket.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) if you are still facing this issue on the latest `2.4-develop` branch.
Thank you for collaboration.

**Closed as completed by engcom-Oscar** 2021-05-27 07:14 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
