### ISSUE TITLE
Magento 2.1.7 WishList button "Add all to cart" is not working

### ISSUE THREAD

**Issue by ymart** [magento/magento2#10385] opened 2017-07-31 18:28 UTC
### Preconditions

1. Login like customer
2. You must have items added to the wishlist

### Steps to reproduce

1. Logged like customer
2. Click "My Wishlist"
3. Click  "Add all to cart"

![wislist](https://user-images.githubusercontent.com/30602780/28791986-389218a8-75fc-11e7-99ea-fc563b42978c.png)

### Actual result

1. After clicking "Add all to cart", the page is left blank and the URL shows the following address: http://url_base/**wishlist/index/allcart/?qty[5]=1&qty[6]=1**

![white page](https://user-images.githubusercontent.com/30602780/28791923-ffaac6ca-75fb-11e7-8a9f-f4e6324396c6.png)

**Comment by korostii** [comment] 2017-08-01 12:49
If you are looking for some help or an advice regarding setup or development please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.
The issues which cannot be consistently reproduced on a clean installation of Magento 2 CE aren't likely to get resolved in here.
Thus if you are, in fact, reporting a technical issue, please try add as much information as possible, including the environment you use, 3rd party themes and modules installed (if any), preconditions, exact steps to follow and stack trace from browser console and even the custom code you're using. These raise the chances of the bug getting reproduced and acknowledged. 
If you don't provide enough information, it is likely that the issue will receive a "needs update" label and will get closed in a couple weeks.

**Comment by magento-engcom-team** [comment] 2017-09-26 22:00
@ymart, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Closed as completed by magento-engcom-team** 2017-09-26 22:00 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid
