### ISSUE TITLE
Filter in admin users grid in backend isn't being remembered

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#21824] opened 2019-03-18 14:38 UTC
### Preconditions (*)
1. Magento 2.2.7

### Steps to reproduce (*)
1. Go to Admin >> System >> Permissions >> All Users
2. Filter grid by "User Name", "First Name" or "Last Name"
3. Click to any admin user
4. Change any info and click to "Save User" button

### Expected result (*)
1. Grid should be filtered by params that your filled in step 2

### Actual result (*)
1. Grid filters was reset, you have to fill the again

Looks like quite similar issue https://github.com/magento/magento2/issues/21805 but for another grid

**Comment by magento-engcom-team** [comment] 2019-03-18 14:38
Hi @ihor-sviziev. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ihor-sviziev do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-03-18 15:38
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment] 2019-03-18 15:40
@ihor-sviziev yes this is similar to #21805. I think all admin grid must be converted to ui based grid and have features to remember previous selections.

**Comment by magento-engcom-team** [comment] 2019-03-18 15:43
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98763`, `MAGETWO-98764` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hostep** [comment] 2019-03-20 13:02
@shikhamis11: it looks like a fix is quite simple: https://github.com/magento/magento2/pull/21834

I wouldn't convert all the grids so they use that more complicated filtering thing like on the product grid, I kind of like the simplicity of the current filters for "simple" entities (like url rewrites and admin users).

**Comment by magento-engcom-team** [comment] 2019-04-15 20:40
Hi @ihor-sviziev. Thank you for your report. 
The issue has been fixed in magento/magento2#22128 by @jayankaghosh in 2.3-develop branch
Related commit(s):
 - [a56b9877a86235990c9dcb888c86a32cb251b8b3](https://github.com/magento/magento2/commit/a56b9877a86235990c9dcb888c86a32cb251b8b3)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-04-15 20:40 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Admin
