### ISSUE TITLE
Customers cannot add a product review in Magento 2.3 store

### ISSUE THREAD

**Issue by jessicana** [magento/magento2#19624] opened 2018-12-07 22:39 UTC
When the product review settings from the backend do not allow guests to write reviews, a customer has to register and sign in to write a review. When a customer signs in to write a review and is allowed by the site to write a review, the rating is unavailable, further, after navigating through the website by clicking on the website logo and then on the products page, for example, the customer sees a sign in/register and Welcome, [customer name]!  What should happen is that Register and Sign in should disappear when the customer is signed in. The customer should be redirected to the review tab with the fields to write a review.

See the image below:

![welcome](https://user-images.githubusercontent.com/7415824/49675591-c825fc00-fa8f-11e8-8dea-c35877020e2d.png)

### Preconditions (*)

1. Magento 2.3
2. PHP 7.1.22

### Steps to reproduce (*)

1. Register an account with the name David Testing
2. Click on the website logo
3. Navigate to write a review by clicking on a product and on: "Be the first to review this product"

### Expected result (*)

1. You should be able to write a review and add a rating to it.
2. The register/ sign in should disappear.
3. The review tab should be visible to the customer to add a review.
4. The sign in / register should disappear.

### Actual result (*)

1. Sometimes after I click on "Be the first to review this product", Magento redirects me to sign in to write a review while I am signed in. In the page header, it says: 
[Welcome, David Testing!  Sign In   Create an Account]
This is very strange. I added a picture.
![bug](https://user-images.githubusercontent.com/7415824/49675982-55b61b80-fa91-11e8-9c2d-d79df2d0cb4d.png)

2. In case the customer is lucky and is allowed by the site to write a review, the rating is unavailable.

**Comment by magento-engcom-team** [comment] 2018-12-07 22:39
Hi @jessicana. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jessicana do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-12-08 06:58
Hi @jignesh26. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by jignesh26** [comment] 2018-12-08 07:10
@jessicana Thanks for reporting this. 
But looks like it issue of configuration and cache. 
I have tired to reproduce this but reviews system is working fine. 
here i am adding some screen shot what i did and working find. 


1) Rating is unavailable
==> You need to add the rating visibility to shows the rating on the front.  Here i am attaching the image how to do that.  
Go to Stores -> Attributes -> Rating -> Select any one rating -> Rating Visibility select your website. 
Clear cache and rating will be on front. 

![screenshot from 2018-12-08 12-29-02](https://user-images.githubusercontent.com/21121564/49683104-74de9880-fae5-11e8-9f78-dbea94ab77e6.png)

2) Reviews are coming on the front after admin approve the reviews. 
Steps i followed:-
A) Disable reviews writing for guest. 
B) Create new customer 
C) Write Review and approve that review from admin
D) Your review will be on screen.
E) Check in private browser and review will be there and also ask to sign in to write new review. 


![screenshot from 2018-12-08 12-28-43](https://user-images.githubusercontent.com/21121564/49683128-da328980-fae5-11e8-8ac3-8bf0b3bef391.png)
![screenshot from 2018-12-08 12-28-32](https://user-images.githubusercontent.com/21121564/49683129-dacb2000-fae5-11e8-89f7-c2fddb2f30c5.png)
![2018-12-08-12-39-10 16 16 93](https://user-images.githubusercontent.com/21121564/49683178-5e850c80-fae6-11e8-80b6-c425c4430821.png)


Please feel free to reopen this if you think issue still persisting with your magento2 with your OS and further details. 

Thank you.

**Closed as completed by jignesh26** 2018-12-08 07:10 UTC
Labels: Issue: Format is valid
