### ISSUE TITLE
Magento 2.3.5-p1 - Guest - Login form of the checkout page is shown without any associating user account

### ISSUE THREAD

**Issue by vincentle89** [magento/magento2#29364] opened 2020-08-03 04:29 UTC
When I tried to place an order and populate an email address that hasn't been associating to any accounts in the system on the checkout page. After the checkout page is refreshed the checkout page, a login form is shown.
### Preconditions (*)

1. Magento version: 2.3.5

### Steps to reproduce (*)

1. Go to a demo page of version 2.3.5. Eg: http://139.162.47.20/magento235/ and add a product
2. Go to checkout and populate an email address that hasn't associated any accounts.
3. Focus on another field.
4. Refresh page.
Refer: https://drive.google.com/file/d/1aOmKQmHy89pAS0onmO9hycDSDWetdO1S/view
### Expected result (*)

1. A field password should be hidden like the previous version of Magento.

### Actual result (*)

1. A field password is shown after refreshing the page
![image](https://user-images.githubusercontent.com/49143689/89145947-6d061e80-d57c-11ea-8cc9-8039addbb244.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment] 2020-08-03 07:16
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-08-03 07:16
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-08-03 07:17
Hi @ajijshekh123, here is your [Magento instance](https://i-29364-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29364-2-4-develop.instances.magento-community.engineering/admin_0a69](https://i-29364-2-4-develop.instances.magento-community.engineering/admin_0a69)
Login: `8dffdf76` Password: `ae64d68af082`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2020-08-03 07:34
Hello @vincent-le89,
This issue is not reproduced in the Magento 2.4 Instance.
**PFA:**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24711761/89157205-c1fc6180-d589-11ea-860a-9b0d2fc15509.gif)

Thanks

**Comment by ajijshekh123** [comment] 2020-08-03 07:43
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment] 2020-08-03 07:43
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment] 2020-08-03 07:44
Hi @ajijshekh123, here is your [Magento instance](https://i-29364-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-29364-2-3-5-p1.instances.magento-community.engineering/admin_2142](https://i-29364-2-3-5-p1.instances.magento-community.engineering/admin_2142)
Login: `49cefce5` Password: `d935cab2898c`
Instance will be terminated in up to 3 hours.

**Comment by vincent-le89** [comment] 2020-08-03 07:49
Hi @ajijshekh123 

It doesn't exactly happen on version 2.4-develop but on 2.3.5-p1. I just made a test on https://i-29364-2-3-5-p1.instances.magento-community.engineering. It's a same result.
Thank you for supporting this ticket.

**Comment by ajijshekh123** [comment] 2020-08-03 07:49
Issue Reproduced on Magento  2.3.5-p1.

**Comment by magento-engcom-team** [comment] 2020-08-03 07:51
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36420` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ajijshekh123** [comment] 2020-08-03 07:52
@vincent-le89 - Please Update your version Magento 2.4 Instance. This issue is fixed on the latest Magento version.

**Comment by vincent-le89** [comment] 2020-08-03 08:02
@ajijshekh123, To be honest, I'm not able to convince my customer to easily updating the latest Magento version. Because it may consume effort if third-party extensions have errors or need time to verify totally site after upgrading version. Is there any chance to fix this issue without upgrading?

**Comment by ajijshekh123** [comment] 2020-08-03 08:14
@vincent-le89 - It may be available on Magento Github so you can R&D your issue and fix it.

**Comment by hostep** [comment] 2020-08-03 08:19
@vincent-le89: also check out https://github.com/magento/magento2/issues/26903 and https://github.com/magento/magento2/pull/27691, those seem to be related.

**Comment by vincent-le89** [comment] 2020-08-03 08:24
Thank you @ajijshekh123.
Hi @hostep : I will check two issues that you suggested. It is a good point to start R&D. ;)

**Comment by ajijshekh123** [comment] 2020-08-03 08:34
Welcome @vincent-le89, After verifying this issue please update me so I will close this issue.

**Comment by sdzhepa** [comment] 2020-08-17 20:05
Closed as Duplicate of https://github.com/magento/magento2/issues/26903

**Closed as completed by sdzhepa** 2020-08-17 20:05 UTC
Labels: Issue: Ready for Work, Component: Checkout, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Reproduced on 2.3.5p1, Reported on 2.3.5
