### ISSUE TITLE
GA4 not tracking value for orders over 1000

### ISSUE THREAD

**Issue by lumnn** [magento/magento2#37708] opened 2023-07-04 09:21 UTC
### Preconditions and environment

- Magento version 2.4.5

### Steps to reproduce

- Install https://addons.mozilla.org/en-US/firefox/addon/ga-debugger/ or https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna
- Locale set-up for GB or any other country that formats numbers with commas
- Navigate to DebugView in GA4
- Place an order for over 1000 (currency not relevant)
- See purchase event in DebugView missing value

### Expected result

purchase event to be tracked correctly with value

### Actual result

no value for puchase event

### Additional information

vendor/magento/module-google-gtag/Block/Ga.php lines 152, 159, 160, 161 uses number_format function that converts value into string, depending on the locale, numbers over 1000 may include commas (for example "1,000").

The string is incorrect documentation mentions it expects "number" - https://developers.google.com/tag-platform/gtagjs/reference/events#purchase

I believe similar thing may happen for tax or delivery over 1000

### Release note

- Fixed GA4 tracking for revenue of orders with value over 1000

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-08-09 12:49
Hi @lumnn,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**


- Install https://addons.mozilla.org/en-US/firefox/addon/ga-debugger/ or https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna
- Locale set-up for GB or any other country that formats numbers with commas
- Navigate to DebugView in GA4
- Place an order for over 1000 (currency not relevant)
- See purchase event in DebugView missing value



Purchase event tracking value correctly.Please let us know if you are missing anything.


<img width="806" alt="Screenshot 2023-08-09 at 1 10 31 PM" src="https://github.com/magento/magento2/assets/51680745/50ae5528-c9fe-4e01-8f21-8726d6d00911">



<img width="967" alt="Screenshot 2023-08-09 at 1 10 21 PM" src="https://github.com/magento/magento2/assets/51680745/34296292-03d5-4d45-8b46-76a7a27bf070">


Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-08-21 06:09
Hi @lumnn,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/37708#issuecomment-1671265927 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-08-29 06:07
Hi @lumnn,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.


Thanks.

**Closed as completed by engcom-Bravo** 2023-08-29 06:07 UTC
Labels: Priority: P2, Progress: done, Issue: ready for confirmation, Issue: needs update, Reported on 2.4.5

**Comment by ryanisn** [comment] 2025-01-22 15:44
Looks like the fix is only released in 2.4.8 which is not GA yet D:

**Comment by ryanisn** [comment] 2025-01-22 15:45
Is there a quality patch for this?
