### ISSUE TITLE
Cron jobs from disabled Magento_Analytics module is getting scheduled and returns an error

### ISSUE THREAD

**Issue by AartiJogiya** [magento/magento2#33440] opened 2021-07-08 10:55 UTC
### Description (*)
Magento_Analytics module has two cron jobs as mentioned below-

**Configurations defined in crontab.xml are as below:** 

- Job name: analytics_subscribe
  Instance - "Magento\Analytics\Cron\SignUp" 
  Method- "execute"

- Job name: analytics_collect_data
  Instance - "Magento\Analytics\Cron\CollectData" 
  Method- "execute"

**Cron expressions are stored in core_config_data table as mentioned below:**

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-b792d10d-7fff-1cc5-0175-e3f6075a485d"><div dir="ltr" style="margin-left:0pt;" align="left">

Job name | path | value
-- | -- | --
analytics_subscribe | crontab/default/jobs/analytics_collect_data/schedule/cron_expr | 0 * * * *
analytics_collect_data | crontab/default/jobs/analytics_collect_data/schedule/cron_expr | 00 02 * * *

</div></b>

When Magento_Analytics module is disabled, It will not get instance and method from crontab.xml but having cron expression stored in core_config_data table so Magento_Cron module is scheduling cron jobs which  returns “No callbacks found for cron job” error when job runs
Here if a module is disabled then it should not schedule any jobs of that module.

### Preconditions (*)

1. Magneto 2.4.2, 2.4-develop
2. In core_config_data table, make sure values are present for below paths:
    - crontab/default/jobs/analytics_subscribe/schedule/cron_expr
    - crontab/default/jobs/analytics_collect_data/schedule/cron_expr
3. Disabled Magento_Analytics module

### Steps to reproduce (*)

1. Setup and run Magento cron

### Expected result (*)

- analytics_subscribe and analytics_collect_data jobs should not be scheduled.

### Actual result (*)

- cron jobs are scheduled in cron_schedules table and shows below errors:
  - No callbacks found for cron job analytics_subscribe 
  - No callbacks found for cron job analytics_collect_data

### Workaround

Magento_Cron module is generating cron schedules by preparing an array object having job-name, instance, method and scheduleby following below process: 

- Reads crontab.xml file from all the enabled module and creates one array which will have job name, instance and method.
    - Related file paths: 
      - magento/module-cron/Model/Config/Reader/Xml.php
      - magento/module-cron/Model/Config/Converter/Xml.php
	
- Reads the database and fetches cron expression stored in core_config_data table and it creates array having job name and schedule.
    - Related file paths: 
      - magento/module-cron/Model/Config/Reader/Db.php
      - magento/module-cron/Model/Config/Converter/Db.php

These two arrays are getting merged using array_replace_recursive function which creates an array object and generates schedules to cron_schedules table.

Here, Magento_Analytics module is disabled so it will not get the first array having instance and method from crontab.xml. So it will only get second array having a job name and schedule from database and it generates cron schedule even if it doesn't have instance and method and therefore returns error "No callbacks found for cron job" from file: magento/module-cron/Observer/ProcessCronQueueObserver.php (function name- _runJob).

If module is disabled and not getting instance and method for cron job then it should not generate cron array object which will  prevent scheduling job.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment] 2021-08-17 12:57
Hi @AartiJogiya 

We tried to reproduce the issue on 2.4-develop but were not able to reproduce it.

Here is what we did:
1. We disabled Magento Analytics from Admin Panel: Stores > Configuration page under the General > Advanced Reporting tab.
2. We ran cron as suggested.
3. Checked cron_schedule table for any errors but couldn’t find any scheduled crons for cron jobs analytics_subscribe or analytics_collect_data.

So, in order to reproduce this on 2.4-develop, can you please check the above steps and let us know if you did things any differently or perhaps you can provide extra details for us to reproduce ?

**Comment by engcom-Lima** [comment] 2021-09-09 09:44
Closing this issue as there has been no update from the reporter on the same.

**Closed as completed by engcom-Lima** 2021-09-09 09:44 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update

**Comment by hostep** [comment] 2021-09-09 11:33
@engcom-Lima: I think the issue does exist, I've seen it happening with other modules as well.

Therefore, could you please try the following instead of what you tried before:
- Install Magento with Analytics module enabled
- Configure the cron settings for this module and verify that the following 2 entries exist in the `core_config_data` table as was explained in the OP:
    - crontab/default/jobs/analytics_subscribe/schedule/cron_expr
    - crontab/default/jobs/analytics_collect_data/schedule/cron_expr
- Run the cron a few times
- Now disable the Analytics module (by manipulating the `config.php` file or running `bin/magento module:disable ...`)
- Run the cron a few times again
- Investigate the `cron_schedule` table, it should not get new entries for those two analytics cronjobs after the module was disabled.
