### ISSUE TITLE
Required parameter depending from another is allways required

### ISSUE THREAD

**Issue by mvistas** [magento/magento2#4672] opened 2016-05-24 13:36 UTC
Hello all,

I create a widget where some parameters depends from other. This parameters are required.
For example:
`<parameter name="block_content_type" xsi:type="select" source_model="namespace\modulename\Model\Config\Source\Types" visible="true" sort_order="2" >
            <label translate="true">Text Block type</label>
        </parameter>`

`<parameter name="text" xsi:type="block" required="true" visible="true" sort_order="3">
            <label translate="true">Text</label>
            <depends>
                <parameter name="block_content_type" value="text" />
            </depends>
            <block class="namespace\modulename\Block\Adminhtml\Widget\TextField"/>
        </parameter>`

In this case, the parameter text only be visible if Text block has value = text.
If I choose another value for text block, this field is not visible. But when I submit my data I get the message that the text field is required.
I wan this field required if, the text block is text.

Depeding parameters can't be required?

**Comment by veloraven** [comment] 2016-11-01 16:32
@mvistas is this issue still actual?
If it is please describe detailed steps, actual result and expected result according to the template.
If it is not, please close it.
If it is more question than an issue please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) as GitHub issue tracker is intended for technical issues only.

**Comment by veloraven** [comment] 2016-11-16 07:43
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Closed as completed by veloraven** 2016-11-16 07:43 UTC
Labels: Progress: needs update
