### ISSUE TITLE
Possible incorrect variable in Sales Module code

### ISSUE THREAD

**Issue by feelinc** [magento/magento2#7642] opened 2016-12-01 07:48 UTC
### Preconditions
1. Magento version 2.1.2

### Steps to reproduce
1. \Magento\Sales\Block\Order\History.php

![selection_216](https://cloud.githubusercontent.com/assets/345562/20785813/cc2042de-b7d4-11e6-8635-431c5ea7ed0b.jpg)

As seen on the screenshot above, I'm not sure the correct "orderCollectionFactory" variable used, that checking of "null" and recreation from object manager is not required anymore.

**Comment by veloraven** [comment] 2016-12-01 08:08
@feelinc  thank you for your feedback.
Please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions as GitHub issue tracker is intended for technical issues only.

**Comment by feelinc** [comment] 2016-12-01 08:31
@veloraven regarding the steps to reproduce, actual result and expected result. Just need to open the file "Magento\Sales\Block\Order\History.php", and can be see the line number based on the screenshot provided.

I'm just think that the codes pointed by the red arrow on the screenshot need to be fixed, everything related with the usage of CollectionFactory and CollectionFactoryInterface.  Where I think just need to use the CollectionFactoryInterface directly in the constructor.

If you think I'm still unable to provide a good explanation, please delete this issue, thanks.

**Comment by magento-engcom-team** [comment] 2017-09-21 13:48
@feelinc Looks like this is an artifact of the refactoring aimed at increasing the extensibility of Magento.
The problem is that the incorrect dependency was provided in the constructor –  `Magento\Sales\Model\ResourceModel\Order\CollectionFactory` instead of `Magento\Sales\Model\ResourceModel\Order\CollectionFactoryInterface`. Providing an interface is always a better solution, as it allows third-parties to inject their own implementation in the class constructor just by configuring it in the `di.xml`.
Closing this ticket for now. Please let us know if you have any additional questions.

**Closed as completed by magento-engcom-team** 2017-09-21 13:48 UTC
Labels: bug report, Component: Sales, Issue: Format is not valid
