### ISSUE TITLE
Create an account when guest checkout is disabled redirects to customer dashboard

### ISSUE THREAD

**Issue by VincentMarmiesse** [magento/magento2#32741] opened 2021-04-14 09:26 UTC
### Preconditions (*)
1. Magento 2.4.2
2. Configuration Allow Guest Checkout : No
3. Configuration Redirect Customer to Account Dashboard after Logging in : No

### Steps to reproduce (*)
1. As a guest, add a product to cart
2. Go to shopping cart page and click on Proceed to checkout button
3. Click on Create an Account button
4. Create an account

### Expected result (*)
1. Customer should be redirected to checkout page as he previously clicked on Proceed to checkout

### Actual result (*)
1. Customer is redirected to his dashboard

### Linked issues
Issue #6015 looks similar but is when the user logs in.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by VincentMarmiesse** [comment] 2021-04-14 09:27
@magento give me 2.4-develop instance

**Comment by VincentMarmiesse** [comment] 2021-04-14 09:39
I confirm the issue on your vanilla Magento instance: when I click to Proceed to checkout and create an account, I am redirected to the dashboard.

**Comment by engcom-Oscar** [comment] 2021-04-14 13:49
Hi @VincentMarmiesse  ! Thank you for your report.
Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop by following steps from this ticket. Looks like we missing some precondition details. May you please recheck issue description and update it.

**Comment by VincentMarmiesse** [comment] 2021-04-14 14:35
@magento give me 2.4-develop instance

**Comment by VincentMarmiesse** [comment] 2021-04-14 14:46
Hi @engcom-Oscar,

Here are the steps I just did to reproduce the issue on the vanilla instance:
1. Log in to the back-office
2. Go to Stores > Configuration > Sales > Checkout > Checkout Options and set Allow Guest Checkout to No.
3. Refresh configuration cache
4. On the front, add any product to shopping cart
5. Go to shopping cart, click on Proceed to Checkout, then Create an Account
6. Create an account

After creating the account, I am redirected to the customer dashboard instead of the checkout.

**Comment by VincentMarmiesse** [comment] 2021-04-14 14:50
@engcom-Oscar here is a link to the video: https://www.awesomescreenshot.com/video/3380771?key=9d53c0138f2cf9d5ac0a904e8b3dbde9

**Comment by engcom-Oscar** [comment] 2021-04-15 08:34
Hi @VincentMarmiesse !
I locally installed latest 2.4-develop branch of Magento 2 and failed again to reproduce this issue. Here my video
https://www.awesomescreenshot.com/video/3391054?key=237630c69c66ed29b882e71600381601

**Comment by VincentMarmiesse** [comment] 2021-04-15 08:45
Hi @engcom-Oscar,

After seeing your video, I double checked and I found it works when you click on Proceed to checkout on the mini cart (like you did), but not from the shopping cart page (like I did).

Can you try these steps on a new session (private navigation for instance):
1. Add a product to cart
2. Go to shopping cart page
3. Click on Proceed to checkout button and create an account

Thank you!

**Comment by magento-engcom-team** [comment] 2021-05-28 08:57
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42490` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by yvaliya** [comment] 2021-06-01 16:55
@magento I'm working on it

**Comment by yvaliya** [comment] 2021-11-25 07:21
I guess this will be fixed by [this PR](https://github.com/magento/magento2/pull/24794)

**Comment by engcom-Bravo** [comment] 2024-06-25 04:33
Hi @VincentMarmiesse,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the attached video.


https://github.com/magento/magento2/assets/51680745/2835de00-7f13-48a4-b008-378849e5397f



Customer is redirecting to checkout page as he previously clicked on Proceed to checkout

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-25 04:33 UTC
Labels: Component: Checkout, Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Cart & Checkout
