### ISSUE TITLE
MagentoCE2.4.3-p1. Free Shipping Method not showing in backend

### ISSUE THREAD

**Issue by broeder** [magento/magento2#35094] opened 2022-02-13 09:02 UTC
### Preconditions (*)

1.MagentoCE2.4.3-p1
2.

### Steps to reproduce (*)

1.Settings on Back end : Stores / Sales / Delivery Method / Flat Rate / Set: Price= 5 and Maximum Price to Set Free=35. 
2.Create Order on **Back end**. Choose products so **total > 35.** Choose Delivery Method = Shipping.

### Expected result (*)

1. [Screenshots, logs or description]
2. Shipping costs should be free.

### Actual result (*)

1. [Screenshots, logs or description]
2.Shipping costs is 5

### Additional comments (*)
The issue is reproducible for the front end and back end as well with the same steps.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._
S2

**Comment by engcom-Lima** [comment] 2022-02-16 13:34
Hi @broeder

Thank you for reporting the issue.
We tried to reproduce the issue on Magento 2.4-develop branch but the issue is not reproducible.

Steps performed:
1. install a clean version of Magento version 2.4-develop
2. Go to configuration<sales<shipping methods<flatrate <set price = 5 and in **Free shipping** set **minimum order amount**=35
3. Create order on backend
4. Choose products so total > 35

**Result:**
Shipping costs is 5
![freeshipping](https://user-images.githubusercontent.com/60198022/154274861-87cb3120-d606-4a46-92f5-f9b2b9fcd768.png)

Please let me know if this is exactly what your issue was or if there is some more configuration required from my end. Will update accordingly.

Thanks

**Comment by broeder** [comment] 2022-02-17 07:15
Hello,
Total due should be = 36

Le mer. 16 févr. 2022 à 14:35, Faizan Shaikh ***@***.***> a
écrit :

**Comment by broeder** [comment] 2022-02-17 15:36
1. install a clean version of Magento version 2.4-develop
   2. Go to configuration<sales<shipping methods<flatrate <set price = 5
   and in *Free shipping* set *minimum order amount*=35
   3. Create order on *frontend*
   4. Choose products so total > 35
   Note: This should give the desired result.


Le mer. 16 févr. 2022 à 14:35, Faizan Shaikh ***@***.***> a
écrit :

**Comment by broeder** [comment] 2022-02-18 07:28
1. Precondition:
   2. install a clean version of Magento version 2.4-3-p1
   3. Steps:
   4. Go to configuration<sales<shipping methods<flatrate <set price = 5
   and in *Free shipping* set *minimum order amount*=35
   5. Create order on backend
   6. Choose products so total = 36
   7. Expected Results: Grand Total = 36
   8. Actual Results: Grand Total = 41

**Comment by engcom-November** [comment] 2022-02-21 13:36
hi @malan

Thank you for reporting the issue.

We verified the issue on Magento Commerce 2.4-develop branch and the issue is reproducible.

Steps performed:
install a clean version of Magento version 2.4-develop
Go to configuration<sales<shipping methods<flatrate <set price = 5 and in Free shipping set minimum order amount=35
Create order on backend
Choose products so total > 35
![image](https://user-images.githubusercontent.com/60198231/154965673-50599ca1-cfd2-43b4-95c8-b62837125897.png)

result:
Shipping costs is 5

**Comment by engcom-Hotel** [comment] 2022-02-22 12:23
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-02-22 12:24
@engcom-November As discussed in the triage meeting, please reverify if this issue occurs in the front end.

**Comment by engcom-Hotel** [comment] 2022-02-22 12:24
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-02-24 06:09
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-03-01 05:27
Hi @Malan

We tried to reproduce the issue again on Magento 2.4-develop branch but the issue is not reproducible.

**Steps performed:**
1: Install a clean version of Magento version 2.4-develop
2: Go to configuration -> sales -> shipping methods -> flatrate -> set price = 5 and in Free shipping set minimum order amount=35
3: Choose products so total > 35
4: Create order in backend as shown in screenshot
![image](https://user-images.githubusercontent.com/60198231/156110376-22788b4a-2ec3-435b-83b2-c49f39d4855a.png)
![image](https://user-images.githubusercontent.com/60198231/156110432-10318934-31b6-4735-b9b9-c28f1dd814d7.png)

5: Create order in frontend as shown in screenshot 
  ![image](https://user-images.githubusercontent.com/60198231/156110345-f579884f-0d5b-40a6-801a-ca1a6bc89478.png)

**Result:**
Shipping cost is free
User can able to select both the shipping Methods (Flat rate or Free Shipping) if product price is > 35 - **No issue**
Kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-03-14 11:31
Hi @broeder ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-03-14 11:31 UTC
Labels: Component: Shipping, Issue:  Cannot Reproduce, Progress: done, Issue: needs update, Area: Shipping, Reported on 2.4.3-p1
