### ISSUE TITLE
Estimate Shipping and Tax cart not showing excluded tax

### ISSUE THREAD

**Issue by JoostWan** [magento/magento2#6166] opened 2016-08-15 10:21 UTC
### Preconditions

1.  Magento 2.1
### Steps to reproduce

![schermafbeelding 2016-08-15 om 12 20 37](https://cloud.githubusercontent.com/assets/5435412/17661975/b274e1b0-62e2-11e6-82b2-eec427662431.png)
### Expected result

Both shipping price excluded tax
### Actual result

![schermafbeelding 2016-08-15 om 12 18 49](https://cloud.githubusercontent.com/assets/5435412/17661950/8f8db4ce-62e2-11e6-9100-2b7d4ea97e47.png)

**Comment by SerhiyShkolyarenko** [comment] 2016-09-05 10:18
@JoostWan could you please add more details here.
What is "Tax Class for Shipping"? which are Tax Calculation Settings?
Which tax zones/rates do you have? Which of them are enabled by tax rules?

**Comment by JoostWan** [comment] 2016-09-05 10:52
See the settings in the screenshots (Default Magento 2.1.1). The shipping price in the Estimate shipping and tax is tax included. But settings are "Showing excluded tax for shipping". The shipping price in the totals is correct (ex tax). 

![schermafbeelding 2016-09-05 om 12 51 10](https://cloud.githubusercontent.com/assets/5435412/18245780/711e06de-7367-11e6-9ba0-96a5811aaf0a.png)

![schermafbeelding 2016-09-05 om 12 46 26](https://cloud.githubusercontent.com/assets/5435412/18245691/f78545da-7366-11e6-851c-31a1b4b4cc59.png)
![schermafbeelding 2016-09-05 om 12 46 17](https://cloud.githubusercontent.com/assets/5435412/18245693/f7b47fe4-7366-11e6-9c37-a01480a474e4.png)

![schermafbeelding 2016-09-05 om 12 49 31](https://cloud.githubusercontent.com/assets/5435412/18245754/5171654c-7367-11e6-82d6-52e86d849bcd.png)

![schermafbeelding 2016-09-05 om 12 49 48](https://cloud.githubusercontent.com/assets/5435412/18245743/4353dc1a-7367-11e6-9e4d-01fbcb7f9168.png)

**Comment by SerhiyShkolyarenko** [comment] 2016-09-05 15:15
@JoostWan cannot reproduce the issue from clean installation. Setting from the screenshots are applied.
![tax for shipping](https://cloud.githubusercontent.com/assets/15108140/18251891/88995a5c-7394-11e6-88a1-6f266cd31efa.png)
Could you specify steps?

**Comment by SerhiyShkolyarenko** [comment] 2016-09-05 15:18
@JoostWan or do you mean you see $5.00 in shipping methods block, but $4.13 in totals block?

**Comment by JoostWan** [comment] 2016-09-05 15:25
Yes. Shipping price are set to show excluded tax. But shipping price in estimate block is included tax. Thats confusing customers because there a two different prices

**Comment by SerhiyShkolyarenko** [comment] 2016-09-05 15:54
Thank you for the report. We created internal issue MAGETWO-58059

**Comment by omiroshnichenko** [comment] 2017-05-25 09:09
Fix has been delivered to develop branch.

**Comment by veloraven** [comment] 2017-06-19 17:18
This issue was fixed for develop branch.
Closed.

**Closed as completed by veloraven** 2017-06-19 17:18 UTC
Labels: Issue: Ready for Work, bug report, Component: Tax

**Comment by korostii** [comment] 2017-06-20 08:59
Hi @veloraven,
The issue was reported on Magento 2.1. Please don't close the issue unless the fix is released for 2.1.x branch officially. Until the fix gets into a released version, this issue will persist for ordinary merchants. 

If there's some internal policy that says you should close the issue, could you guys at least put a milestone when you're closing the issue so that we see in which future version the fix is planned to be released

I'm seeing the "fixed for develop branch" message used by you ( @veloraven ) as an excuse to close an issue over and over again. After that, the issue seems to become forgotten about, for good. As if you don't care whether the issue is actually resolved for the users.

I've written about that multiple times. Do you not read the messages people address to you? Do I need to redirect this sentiment to @magento-team or @maksek or who-else in order for it to get some kind of response?

**Comment by Ctucker9233** [comment] 2017-08-26 20:01
@korostii Kudos. Though seeing as how @veloraven hasn't responded in almost three months, I doubt there is a real person behind the name tag. Seems like a programmed auto-response.
