### ISSUE TITLE
List of categories will not appear in creating the product process

### ISSUE THREAD

**Issue by Crustymd** [magento/magento2#869] opened 2014-12-24 14:32 UTC
SO if i type in here http://prntscr.com/5khezo

The name of the category or first 2 letterm the category will not appear, 

But if i type in "default" i see all teh subcategories of default root folder..

**Comment by maksek** [comment] 2015-01-08 22:06
Hi @Crustymd, we have checked and it works as expected. Have you had chance to install again and revalidate the issue?

**Comment by vpelipenko** [comment] 2015-01-29 13:31
Internal ticket: MAGETWO-32344

**Comment by vpelipenko** [comment] 2015-01-29 13:57
Described issue can't be reproduced. Closed, due to no response from contributor.

**Comment by kokoc** [comment] 2015-05-05 09:47
@Crustymd This issue is fixed in latest Magento version. List of categories now work as expected on your environment. Could you please verify?

**Comment by kokoc** [comment] 2015-05-20 12:00
@Crustymd since we haven't heard back from you, we'll proceed with closing this issue. If in case you do have any updates, feel free to reach out to us by submitting a new issue.

**Closed by kokoc** 2015-05-20 12:00 UTC
Labels: bug, MX, needs update
