### ISSUE TITLE
Customizable Options, when selected on the front end, they update the price of the UpSells and Related products.

### ISSUE THREAD

**Issue by janeblonde** [magento/magento2#7192] opened 2016-10-26 10:08 UTC
**Preconditions**
    Magento CE 2.1.0
    PHP  7.0.12
   MySQL Version mysqlnd 5.0.12-dev

Steps to reproduce

**Create a product**
1. add upsells for the products
2. added Related products
3. Add some customizations with prices (I added tickboxes)
4. Go to product page on front end
5. tick any option

**Expected Result**
The price of the product increases

**Actual Result**
The product price increases and so does the prices of all UpSells and Related Products.

**Discussion**
We've tested this on Porto by Smartwave and Luma

**Comment by veloraven** [comment] 2016-10-27 12:16
@janeblonde thank you for your report.
I'm closing this issue as duplicate of #4588

**Closed as completed by veloraven** 2016-10-27 12:16 UTC
