### ISSUE TITLE
How to display number of items count in minicart instead of cart.summary_count in magento2.0.6

### ISSUE THREAD

**Issue by KalaiarasanSeetharaman** [magento/magento2#6871] opened 2016-10-04 14:24 UTC
<span class="counter qty empty"
              data-bind="css: { empty: cart().summary_count == 0 }, blockLoader: isLoading">
            <span class="counter-number"></span>  
        </span>    

In this place how to display itemscount instead summary_count -> it returns total number of qty . I need to number of items in the cart .

**Comment by pboisvert** [comment] 2016-10-04 14:30
@KalaiarasanSeetharaman are you reporting an issue or asking a technical question? The "Issues" section of this GitHub is intended for reporting technical issue. If you are asking a "How to" question, the best place for that would be the [Magento Stack Exchange](http://magento.stackexchange.com/?tags=magento2) or the Community forums. 

If a coding issue please fill out the template with full system info and steps to reproduce.

**Comment by KalaiarasanSeetharaman** [comment] 2016-10-04 14:32
@pboisvert Thanks .

**Comment by veloraven** [comment] 2016-10-10 10:34
@KalaiarasanSeetharaman , I'm closing this issue as not a bug.
If you find out it to be a bug which needs fix, please feel free to create the new GitHub issue.

**Closed as completed by veloraven** 2016-10-10 10:34 UTC
