### ISSUE TITLE
Maximum shipping amount allowed to refund is: €0.00

### ISSUE THREAD

**Issue by brmor-mistermenuiserie** [magento/magento2#38134] opened 2023-10-30 15:58 UTC
### Preconditions and environment

Magento version : 2.4.6p3

### Steps to reproduce

1. cancel credit memo which refund all shipping fees
2. create a new credit memo with shipping fees refund

### Expected result

Credit memo is created and shipping fee refunded.

### Actual result

An error after create Credit memo
![image](https://github.com/magento/magento2/assets/103111614/798ab8a0-eb4f-4fb6-8b98-cde740f6e24b)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by brmor-mistermenuiserie** [comment] 2023-10-30 16:00
Fixed with this patch

[fix_credit_memo_shipping_amount.txt](https://github.com/magento/magento2/files/13207253/fix_credit_memo_shipping_amount.txt)

**Comment by engcom-Dash** [comment] 2023-10-31 10:20
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-10-31 13:49
Hi @brmor-mistermenuiserie 
Thanks for reporting and collaboration. 

> 1. cancel credit memo which refund all shipping fees

Can you please let us know if you are using any specific third party extensions or custom code inorder to perform the above step?

Thanks

**Comment by engcom-Bravo** [comment] 2023-11-14 06:03
Hi @brmor-mistermenuiserie,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38134#issuecomment-1787259540 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-11-20 06:03
Hi @brmor-mistermenuiserie,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-11-20 06:03 UTC
Labels: Issue: needs update, Reported on 2.4.6-p3
