### ISSUE TITLE
WebApi - OAuth Login: - HMAC-SHA1 not supported

### ISSUE THREAD

**Issue by manjeetrwm** [magento/magento2#35510] opened 2022-05-20 15:04 UTC
### Preconditions and environment

- Magento version: 2.4.4
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

Oauth client retuns:

{"message":"Signature method %1 is not supported","parameters":["HMAC-SHA1"]}

### Expected result

HMAC-SHA1 should be supported as per documentation.

 SIGNATURE_SHA1 is not supported in OauthInterface.php

### Actual result

{"message":"Signature method %1 is not supported","parameters":["HMAC-SHA1"]}

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by manjeetrwm** [comment] 2022-05-20 15:18
/**
     * Retrieve array of supported signature methods.
     *
     * @return string[]
     */
    public static function getSupportedSignatureMethods()
    {
        return [self::SIGNATURE_SHA256];
    }

**Comment by ssx** [comment] 2022-06-16 07:43
As you're probably aware, the docs were wrong. I PR'd a change to them yesterday which is now merged. They are updated now: https://developer.adobe.com/commerce/webapi/get-started/authentication/gs-authentication-oauth/

**Comment by gwharton** [comment] 2022-06-18 14:39
Apologies for butting in, but I have an integration that only uses SHA1. This has obviously stopped working since updating to 2.4.4 Are there any options for rolling back to support SHA1 in 2.4.4?

**Comment by ssx** [comment] 2022-06-20 07:10
@gwharton patch the file to revert to SHA1:

```patch

diff --git a/vendor/magento/framework/Oauth/Oauth.php b/vendor/magento/framework/Oauth/Oauth.php

--- a/vendor/magento/framework/Oauth/Oauth.php
+++ b/vendor/magento/framework/Oauth/Oauth.php
@@ -61,7 +61,7 @@ class Oauth implements OauthInterface
      */
     public static function getSupportedSignatureMethods()
     {
-        return [self::SIGNATURE_SHA256];
+        return [self::SIGNATURE_SHA1];
     }

     /**
@@ -142,7 +142,7 @@ class Oauth implements OauthInterface
     public function buildAuthorizationHeader(
         $params,
         $requestUrl,
-        $signatureMethod = self::SIGNATURE_SHA256,
+        $signatureMethod = self::SIGNATURE_SHA1,
         $httpMethod = 'POST'
     ) {
         $required = ["oauth_consumer_key", "oauth_consumer_secret", "oauth_token", "oauth_token_secret"];

```

**Comment by gwharton** [comment] 2022-06-20 10:35
Cheers for that. I can confirm that applying the patch does indeed revert the change back to SHA1.

**Comment by engcom-Lima** [comment] 2022-06-30 10:47
Hi @manjeetrwm 

Thanks for your contribution and collaboration.
Kindly provide description and steps to reproduce the issue.

**Closed as completed** 2022-07-12 11:31 UTC
Labels: non-issue, Reported on 2.4.4
