### ISSUE TITLE
Merged CSS file name generation

### ISSUE THREAD

**Issue by pmoreno1980** [magento/magento2#11354] opened 2017-10-10 18:08 UTC
Preconditions

Magento 2.1.7
PHP 7.0
Mysql 5.7
Attributes (attribute sets) with numeric codes

### Steps to reproduce
1. Store >> configuration > advanced > developer
2. Merge and minify CCS & JS
3. deleted static content & deploy the static content again

### Expected result
1. change the CCS merged file name

### Actual result
1. always the same file name , example <link  rel="stylesheet" type="text/css"  media="all" href="http://domain.com/pub/static/_cache/merged/f4ae032b4d845f97179714bb8f1806a7.min.css" />

Why the file name never change f4ae032b4d845f97179714bb8f1806a7.min.css ?

**Comment by paales** [comment] 2017-10-10 20:53
@pmoreno1980 Are you sure the contents of the file are actually changed, I believe the file name is based on the contents that are in the file. If the contents of the file change, the hash should change as well?

**Comment by pmoreno1980** [comment] 2017-10-10 21:08
I'm using a custom theme (porto for Magento 2), i changed some styles in the custom css file that is merged and minify. So supposedly if i change the content the file name should change?

thanks for you help

**Comment by orlangur** [comment] 2017-10-10 21:15
> Why the file name never change f4ae032b4d845f97179714bb8f1806a7.min.css ?

What's the problem with it? You can find it out from the code, in order to get immediate CSS file update you can enable Static Files Signature.

**Comment by scholtz** [comment] 2017-10-11 10:11
@orlangur .. Standard systems use to name minified css and js as hash of the content.. as described above.. If content changes, it is bug of css minifier (i dont know if in magento) or supply of css to that minifier (perhaps cached css before minifying)

The name of css or js file names are usually derived as hash of the content because the browsers can cache it properly and change it when developer makes a change.

If magento does not change minified name when it changes content it is clearly magento bug. Note that i have not investigated if I can replicate the issue.. i am just commenting on your statement.. i dont believe that this issue needs more update. It needs to be checked by magento developers.

**Comment by orlangur** [comment] 2017-10-11 10:42
Here is a PR with related logic but only in one place: https://github.com/magento/magento2/pull/10378/files Before change timestamp was used, probably the same happens in described scenario.

> because the browsers can cache it properly

As I mentioned, Sign Static Files feature is used to avoid browser caching issues.

> If magento does not change minified name when it changes content it is clearly magento bug.

Clearly not. If system works as intended it is not a bug. Marking for recheck by someone who is aware how it is supposed to work.

**Comment by pmoreno1980** [comment] 2017-10-11 14:30
@orlangur  the Sign Static Files change the path of the file (added the version) but doesn't change the name of the file. it's the same. I need to change the name of the file.

thanks for your help

**Comment by orlangur** [comment] 2017-10-11 14:40
Why do you need to change specifically a name? Yes, basically it changes URL, if in current implementation file name is not obtained as a hash of file content, such system behavior change is definitely a feature request.

**Comment by pmoreno1980** [comment] 2017-10-11 15:26
To force the browser visitors to read the new ccs file. I tested a lot and the static content version in the path it's not enough. The other solution maybe is adding the version in the file like ?v=1.2.3 but I don;t know how the merged min.css file is created.

**Comment by orlangur** [comment] 2017-10-11 15:30
Browsers cache URLs, not file paths.

> I tested a lot and the static content version in the path it's not enough.

Please provide more details how it can be observed.

**Comment by pmoreno1980** [comment] 2017-10-11 16:21
every time that I did a new deploy I have a new version in the URL of course. (fyi, yes i delete the static content before deploy), this is what I see in the source code

http://xxxxxxxxx.com/pub/static/version1507067651/_cache/merged/f4ae032b4d845f97179714bb8f1806a7.min.css
http://xxxxxxxxx.com/pub/static/version1507232359/_cache/merged/f4ae032b4d845f97179714bb8f1806a7.min.css
http://xxxxxxxxx.com/pub/static/version1507232880/_cache/merged/f4ae032b4d845f97179714bb8f1806a7.min.css
http://xxxxxxxxx.com/pub/static/version1507299443/_cache/merged/f4ae032b4d845f97179714bb8f1806a7.min.css

but as you can see the file has the same name always >f4ae032b4d845f97179714bb8f1806a7.min.css

**Comment by orlangur** [comment] 2017-10-11 16:25
Browser is caching full URL http://xxxxxxxxx.com/pub/static/version1507299443/_cache/merged/f4ae032b4d845f97179714bb8f1806a7.min.css, what is the exact problem?

**Comment by pmoreno1980** [comment] 2017-10-11 16:32
the problem is that i can see the new url path in the source code but i can't see the changes in the css, only i can see the changes after press Shift + F5.

make sense?

thanks for your help again

**Comment by orlangur** [comment] 2017-10-11 16:45
Any of
http://xxxxxxxxx.com/pub/static/version1507067651/_cache/merged/f4ae032b4d845f97179714bb8f1806a7.min.css
http://xxxxxxxxx.com/pub/static/version1507232359/_cache/merged/f4ae032b4d845f97179714bb8f1806a7.min.css
http://xxxxxxxxx.com/pub/static/version1507232880/_cache/merged/f4ae032b4d845f97179714bb8f1806a7.min.css
http://xxxxxxxxx.com/pub/static/version1507299443/_cache/merged/f4ae032b4d845f97179714bb8f1806a7.min.css
return the same content for you until you press Shift+F5? Did you enable Varnish?

**Comment by pmoreno1980** [comment] 2017-10-11 16:51
Yes, return the same content for you until i press Shift+F5? I'm not using Varnish

**Comment by magento-engcom-team** [comment] 2017-12-04 14:30
@pmoreno1980, thank you for your report.
We've created internal ticket(s) MAGETWO-84966 to track progress on the issue.

**Comment by sashas777** [comment] 2018-05-11 01:28
@pmoreno1980  @scholtz 

While PR getting approval and until it will be included into a release I made module only for Magento 2.2.x  but not more than version 2.2.4. 
Maybe it would help you as well: https://github.com/sashas777/merged-css-issue

Thanks

**Comment by magento-engcom-team** [comment] 2018-05-15 01:30
Hi @pmoreno1980. Thank you for your report. 
The issue has been fixed in magento/magento2#15144 by @sashas777 in 2.2-develop branch
Related commit(s):
 - [fd18240cca37c7ba2e1fed1a8caa35cca21f1049](https://github.com/magento/magento2/commit/fd18240cca37c7ba2e1fed1a8caa35cca21f1049)
 - [1336eeadfd5841db144d25a4e5cb1ae2e8479522](https://github.com/magento/magento2/commit/1336eeadfd5841db144d25a4e5cb1ae2e8479522)
 - [49a099f566243ded66bd5f2cf1244ab591529267](https://github.com/magento/magento2/commit/49a099f566243ded66bd5f2cf1244ab591529267)
 - [6ec1b972f72b9e38e2e4c06f4fdd83db8a0677c4](https://github.com/magento/magento2/commit/6ec1b972f72b9e38e2e4c06f4fdd83db8a0677c4)
 - [6db98dbc951b4740acf62955274b9a690a8b6aef](https://github.com/magento/magento2/commit/6db98dbc951b4740acf62955274b9a690a8b6aef)
 - [b3bb19bd053e5f2312fb8cbc80190f6ceb7de2ac](https://github.com/magento/magento2/commit/b3bb19bd053e5f2312fb8cbc80190f6ceb7de2ac)
 - [77b1179ba3da45a133a08b83b2595cc8a4b48161](https://github.com/magento/magento2/commit/77b1179ba3da45a133a08b83b2595cc8a4b48161)
 - [116ea3641673ddc6b35bcdd2fa9e8c90a68fab05](https://github.com/magento/magento2/commit/116ea3641673ddc6b35bcdd2fa9e8c90a68fab05)
 - [c4ba3ff7f745280e8c6f71bc83e18f7e2c7986b6](https://github.com/magento/magento2/commit/c4ba3ff7f745280e8c6f71bc83e18f7e2c7986b6)

The fix will be available with the upcoming 2.2.5 release.

**Closed as completed by magento-engcom-team** 2018-05-15 01:30 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, good first issue

**Comment by sidolov** [comment] 2018-07-12 17:44
Hi @pmoreno1980. Thank you for your report. 
The issue has been fixed in magento/magento2#16663 by @mageprince in 2.3-develop branch
Related commit(s):
 - [28167648ab16a1a8f18792420b33badbcc6423b6](https://github.com/magento/magento2/commit/28167648ab16a1a8f18792420b33badbcc6423b6)
 - [2d31c1d2dc7355bb9a31413cdc481e30d3d060f9](https://github.com/magento/magento2/commit/2d31c1d2dc7355bb9a31413cdc481e30d3d060f9)
 - [e7677e8c3381915fbc6f0f213b02781dea4b9b2d](https://github.com/magento/magento2/commit/e7677e8c3381915fbc6f0f213b02781dea4b9b2d)
 - [ca3c79c538465d4053b5eeffb79b21327d03a112](https://github.com/magento/magento2/commit/ca3c79c538465d4053b5eeffb79b21327d03a112)
 - [311f8ca9aa283d9bcd3ab45327db3363223094de](https://github.com/magento/magento2/commit/311f8ca9aa283d9bcd3ab45327db3363223094de)
 - [1782c54b76613323034eefda53ec85a4d4fa17ba](https://github.com/magento/magento2/commit/1782c54b76613323034eefda53ec85a4d4fa17ba)
 - [94e0e25d285781aa3bc7b8a02a0cc119e04fec8b](https://github.com/magento/magento2/commit/94e0e25d285781aa3bc7b8a02a0cc119e04fec8b)
 - [831e58c2ac596592548220d111491426b433c5e0](https://github.com/magento/magento2/commit/831e58c2ac596592548220d111491426b433c5e0)
 - [742ad8c6fac09a062a4dc5c99cd2e30ecc5a251a](https://github.com/magento/magento2/commit/742ad8c6fac09a062a4dc5c99cd2e30ecc5a251a)

The fix will be available with the upcoming 2.3.0 release.
