### ISSUE TITLE
Can't show attribute

### ISSUE THREAD

**Issue by Aartitops** [magento/magento2#6431] opened 2016-09-01 07:42 UTC
Hi,

I use configurable product with associated simple product and now i made one attribute and it is not showing into layered navigation filter into category page.

Actual result:-

![actual](https://cloud.githubusercontent.com/assets/20356638/18159263/88622e08-7045-11e6-8d45-b3bcbf54e882.png)

expected result:- 
Attribute should be showing there.
Thanks.

**Comment by veloraven** [comment] 2016-09-01 15:17
@Aartitops thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with detailed steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.

**Comment by voleye** [comment] 2016-09-22 09:33
Hi @Aartitops, could you please provide more details about attribute options:
- scope
- the value of setting "use in layered navigation" (this option has several posible values (show with no result, show with results - could you please check the behavior with different values?))
- does the attribute has values?

**Comment by andimov** [comment] 2016-09-27 09:41
@Aartitops 
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Closed as completed by andimov** 2016-09-27 09:41 UTC
Labels: Progress: needs update
