### ISSUE TITLE
Customer Login Block sets the title for the page when rendered

### ISSUE THREAD

**Issue by matthew-muscat** [magento/magento2#13982] opened 2018-03-07 00:34 UTC
The Customer Login Block, defined as `Magento\Customer\Block\Form\Login` currently has logic that would set the overall page title, which is unexpected behaviour.

It is assumed that the layout xml, or the controller, would be responsible for setting the page title, and that if the Customer Login Block was to be included in other areas of the Magento Site, that it would not affect the overall page title.

The logic that is causing this behaviour can be located at https://github.com/magento/magento2/blob/9c14af7a97bcf338662de365d2613c7ca9dbf8c6/app/code/Magento/Customer/Block/Form/Login.php#L55

### Preconditions
1. The block behaviour affects all current M2 versions (this issue is also present in M1)
2. The behaviour occurs when the block is rendered on a page other than the login page — ie: a custom page that includes the login block

### Steps to reproduce
1. Include the Customer Login Block within any other page of the Magento system
2. Verify that the page title has been updated to "Customer Login", based on the block being rendered.

**Example Situation where this may occur**
- The login block is added to a custom page — the login action is not the primary purpose of the page, but, due to the current block logic, the title of the page may be updated to "Customer Login"

### Expected result
1. The block should not be responsible for setting the overall page title, as the block's responsibilities only relate to rendering the contents of the block

### Actual result
1. The page title is updated to "Customer Login" whenever the login block is included on a page

### Proposed changes
1. Update the Customer Login Block to remove the references to setting the page title within the block
2. Update the Customer Login page layout to set the title via the layout XML
3. Determine if the Customer Login Block is used on any other pages and update the page title accordingly (as per item 2 above)

**Comment by magento-engcom-team** [comment] 2018-03-07 13:30
@matthew-muscat, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2019-01-24 13:30
Hi @lisovyievhenii. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-02-25 10:47
Hi @matthew-muscat. Thank you for your report. 
The issue has been fixed in magento/magento2#20583 by @lisovyievhenii in 2.3-develop branch
Related commit(s):
 - [122e5c2f61bd29fa6a329af2f23f4441a64b1ea9](https://github.com/magento/magento2/commit/122e5c2f61bd29fa6a329af2f23f4441a64b1ea9)
 - [93f1caa3623e711b6699107bb3dcb24e982eb750](https://github.com/magento/magento2/commit/93f1caa3623e711b6699107bb3dcb24e982eb750)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-02-25 10:47 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by magento-engcom-team** [comment] 2019-03-05 21:05
Hi @matthew-muscat. Thank you for your report. 
The issue has been fixed in magento/magento2#21434 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [cd9287867dbe0843614ef6ac9cf75da203505d82](https://github.com/magento/magento2/commit/cd9287867dbe0843614ef6ac9cf75da203505d82)
 - [f1de3406cd8cfb3454baef8a72ed2d2cc0d4f10e](https://github.com/magento/magento2/commit/f1de3406cd8cfb3454baef8a72ed2d2cc0d4f10e)

The fix will be available with the upcoming 2.2.9 release.
