### ISSUE TITLE
Empty Checkout Agreement Edit Form when Single Store Mode is enabled

### ISSUE THREAD

**Issue by RedEnzian** [magento/magento2#7822] opened 2016-12-15 14:29 UTC
### Preconditions

1. Fresh installed Magento 2.1.3
2. PHP 5.6.28

### Steps to reproduce

1. Fresh Installation of Magento 2.1.3
2. Goto Stores->Terms & Conditions
3. Add new Condition
4. Try to edit Condition (works)
5. Switch to Single Store Mode
6. Try to edit Condition (does not work)
7. Add new Condition
8. Try edit new condition (does not work)

### Expected result

1. Show the prefilled edit form for checkout agreements

### Actual result

1. When in Production Mode there is no form displayed when clicking edit on an existing agreement
2. When in development Mode, there is an exception displayed. Attached the exception to this issue
[magento_checkout_agreement_exception.txt](https://github.com/magento/magento2/files/654883/magento_checkout_agreement_exception.txt)

**Comment by miakusha** [comment] 2017-01-30 13:51
Hi @RedEnzian thank for report
We've created internal ticket MAGETWO-63840 to address this issue.

**Comment by gwharton** [comment] 2017-09-27 22:38
I see this error on Magento 2.2.0 when there is only one store/website. If I create multiple stores it works as expected.

**Comment by magento-engcom-team** [comment] 2017-10-03 15:30
@RedEnzian, thank you for your report.
We've created internal ticket(s) MAGETWO-63840, MAGETWO-80764 to track progress on the issue.

**Comment by gwharton** [comment] 2017-12-12 21:47
Still broken in 2.2.2

**Comment by RomaKis** [comment] 2018-01-03 15:09
Working on this.

**Comment by magento-engcom-team** [comment] 2018-04-28 14:30
Hi @RedEnzian. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1157 by @RomaKis in 2.2-develop branch
Related commit(s):
 - [a49f5247902684ed6c19f99285a7015ab4a2507c](https://github.com/magento/magento2/commit/a49f5247902684ed6c19f99285a7015ab4a2507c)
 - [e4353add8d0cbf628a8813bed5377baf700e57b9](https://github.com/magento/magento2/commit/e4353add8d0cbf628a8813bed5377baf700e57b9)

The fix will be available with the upcoming 2.2.5 release.

**Comment by gwharton** [comment] 2018-04-28 15:25
This is not fixed in 2.3-develop. Isn't there a procedure to follow to ensure that when bug fixes are committed to 2.2-develop, that they are also ported to 2.3-develop if required at the same time? Otherwise, when we all switch to 2.3.0 in "whenever it is released" time this bug will magically reappear?

**Comment by gwharton** [comment] 2018-05-08 04:09
@RomaKis can this be forward ported to 2.3-develop please otherwise it will rear its ugly head in the future.

**Comment by magento-engcom-team** [comment] 2018-05-08 09:54
Hi @gwharton 
We keep track of the `2.2-develop` Pull Requests and their ports to `2.3-develop`. It's unlikely that 2.3 will be released without the fix. Also, please feel free to submit a Pull Request with the fix, that would help a lot.

Thank you for collaboration.

**Closed as completed by magento-engcom-team** 2018-05-08 09:54 UTC
Labels: Issue: Ready for Work, bug report, Component: Checkout, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by gwharton** [comment] 2018-05-08 12:03
Brilliant, thanks @magento-engcom-team 
I just wasn't sure of the Back/Forward porting strategy and whether there was a process to sweep up PR's that needed forwardporting prior to 2.3 release.

**Comment by magento-engcom-team** [comment] 2018-05-12 16:31
Hi @RedEnzian. Thank you for your report. 
The issue has been fixed in magento/magento2#15063 by @gwharton in 2.3-develop branch
Related commit(s):
 - [d61fe1dd33e999a764a211194ee11f801db85ff6](https://github.com/magento/magento2/commit/d61fe1dd33e999a764a211194ee11f801db85ff6)
 - [9c4a26ff169fc5f0236955f214d1ed12e37c9633](https://github.com/magento/magento2/commit/9c4a26ff169fc5f0236955f214d1ed12e37c9633)
 - [76be1b97184931d1b2565a3357249b9a59a3383e](https://github.com/magento/magento2/commit/76be1b97184931d1b2565a3357249b9a59a3383e)

The fix will be available with the upcoming 2.3.0 release.

**Comment by onepack** [comment] 2018-10-29 22:58
My error is a bit different from the one posted by @RedEnzian.
I get a database error but the end result is the same. No option to edit an agreement document.

Magento 2.2.6
PHP 7.1.23
Sample data installed.
Single-store mode is off.
[agreement_bug.txt](https://github.com/magento/magento2/files/2527366/agreement_bug.txt)

**Comment by gwharton** [comment] 2018-10-29 23:13
@onepack, have you had a look at your database to check that table.

```
mysql> use dev_magento; describe checkout_agreement_store;
Database changed
+--------------+----------------------+------+-----+---------+-------+
| Field        | Type                 | Null | Key | Default | Extra |
+--------------+----------------------+------+-----+---------+-------+
| agreement_id | int(10) unsigned     | NO   | PRI | NULL    |       |
| store_id     | smallint(5) unsigned | NO   | PRI | NULL    |       |
+--------------+----------------------+------+-----+---------+-------+
2 rows in set (0.00 sec)

```

What happens if you run 

`use database_name; describe checkout_agreement_store;`

**Comment by onepack** [comment] 2018-10-30 10:17
@gwharton,
Thank you for your reply! Really appreciated.

I have the exact same outcome as above.
After googling a bit I found a stackexchange post with the same issue.
https://magento.stackexchange.com/questions/244961/checkout-agreement-store-doesnt-exist
I will have a look at that now.

**Comment by gwharton** [comment] 2018-10-30 10:29
Ahh right. Seems like something to do with database table prefixes. Does your test case have table prefixes. If so, please raise a new issue with steps to reproduce from a fresh magento install.

**Comment by onepack** [comment] 2018-10-30 10:36
Yes, I use prefixes for security purposes. I will check if this is indeed the source of this issue.

**Comment by onepack** [comment] 2018-10-30 10:49
I deployed the suggested change from stackexchange to the dev environment and this solved the bug. I can even see the added condition now in the grid that was not visible before. So yes this seems to be a prefix issue.

**Comment by gwharton** [comment] 2018-10-30 11:19
@onepack. 

Here is your issue https://github.com/magento/magento2/issues/18357

Here is the 2.3 PR https://github.com/magento/magento2/pull/18412

Here is the 2.2 PR https://github.com/magento/magento2/pull/18866

The 2.2 change has yet to be merged.
