### ISSUE TITLE
remove jQuery Migrate

### ISSUE THREAD

**Issue by DanielRuf** [magento/magento2#21406] opened 2019-02-22 11:53 UTC
### Preconditions (*)
jQuery Migrate should never be used in production as this is just meant to migrate from an older version to the used one (for which the Migrate version is).

https://github.com/magento/magento2/blob/2.3-develop/lib/web/jquery/jquery-migrate.js

See https://github.com/jquery/jquery-migrate/tree/1.x-stable#readme

The same applies to underscore, moment.js and other unnecessary libraries and scripts.

This is a big file and just for debugging purposes.

### Expected result (*)

1. jQuery Migrate should not be loaded
2.

### Actual result (*)

1. jQuery Migrate is loaded
2.

**Comment by magento-engcom-team** [comment] 2019-02-22 11:54
Hi @DanielRuf. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@DanielRuf do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ananth-iyer** [comment] 2019-02-23 06:23
@DanielRuf I see there is the production version of jQuery Migrate. On production mode, shouldn't it load production version jQuery Migrate?

**Comment by DanielRuf** [comment] 2019-02-23 08:07
I'm not sure if I completely understand your comment.

Why do we even need jQuery migrate? It is not meant to be used in websites in production. Also this and other libs are not the minified versions.

**Comment by magento-engcom-team** [comment] 2019-02-25 09:36
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-02-25 10:57
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98417`, `MAGETWO-98418` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hostep** [comment] 2020-12-23 21:26
This should still happen one day. See comments in https://github.com/magento/magento2/pull/25847, they contain interesting tidbits.

**Comment by markshust** [comment] 2021-07-23 13:07
What's the status of the related PR for this?

An additional note, the whole reason to include jquery-migrate is to notify us when jquery functions are deprecated. The following warning has been appearing in the browser console for a long time now, and has never been updated:

`jQuery.attrFn is deprecated`

**Comment by jordanvector** [comment] 2021-07-23 14:11
Theres currently an open PR for this very thing https://github.com/magento/magento2/pull/32364.  However it is still failing functional tests due to some functionality in the admin specifically around tax rates that needs jquery migrate for some reason

**Comment by markshust** [comment] 2021-07-23 15:41
@jordanvector do you know how we can resolve the issues? I tried pulling up the failed tests, but they are just timing out.

**Closed as completed** 2021-09-29 18:40 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Component: Framework/System, Event: cd-cologne19, Priority: P1, Severity: S3, Area: Perf/Frontend, Progress: done, Issue: On Hold

**Comment by markshust** [comment] 2021-09-29 18:46
@DanielRuf looks like this was closed because jQuery migrate is being updated. What's the link/number to the issue?

**Comment by DanielRuf** [comment] 2021-09-29 18:49
> @DanielRuf looks like this was closed because jQuery migrate is being updated. What's the link/number to the issue?

I do not know what the current status is. I've closed it due to inactivity.

**Comment by DanielRuf** [comment] 2021-09-29 18:49
> @DanielRuf looks like this was closed because jQuery migrate is being updated. What's the link/number to the issue?

@markshust I do not know what the current status is. I've closed it due to inactivity.

**Comment by markshust** [comment] 2021-09-29 18:53
This is a valid issue, it shouldn't be closed for no reason.

**Comment by lampenweltwma** [comment] 2024-04-12 10:06
Just tagging related change: https://github.com/magento/magento2/pull/36715

**Comment by DanielRuf** [comment] 2024-04-12 17:05
@lampenweltwma thanks for the link. And as always surprising, that there are more files changed (composer.lock with unrelated changes) than I would expect.
