### ISSUE TITLE
Backup tools not available after upgrade to 2.0.5

### ISSUE THREAD

**Issue by webspeaks** [magento/magento2#4481] opened 2016-05-12 18:09 UTC
## Steps to reproduce
1. Upgrade to 2.0.5.
2. Go to System -> Backups.
## Expected result
1. Backup grid should be visible
2. All three backup buttons should function
## Actual result
1. Backup grid not visible
   ![backupt-bug-1](https://cloud.githubusercontent.com/assets/1465109/15225152/b12aa494-189a-11e6-864f-c34fd89ec442.png)
2. Backup buttons giving error
   ![backupt-bug-2 png](https://cloud.githubusercontent.com/assets/1465109/15225156/b5d17752-189a-11e6-8f05-76c8c5f1e1af.jpg)

**Comment by mazhalai** [comment] 2016-05-12 18:52
Closing as duplicate of #3451

**Closed as completed by mazhalai** 2016-05-12 18:52 UTC
