### ISSUE TITLE
Facing issue in sorting when we created custom attribute in admin and use sort by to yes then result is not sorted.

### ISSUE THREAD

**Issue by sangeetavernost** [magento/magento2#37342] opened 2023-04-06 08:02 UTC
### Preconditions and environment

Magento 2 products: create a new attribute and set used sorting in product listing to yes.

    Prerequisite

        - Magento ver. 2.4.3-p1
        - PHP 7.4.33
        - ElasticSearch version - 7.17.7

### Steps to reproduce

Steps : 
        Create a magento product attribute

        Admin -> Stores -> Attributes (Product) -> Add new attribute -> Added basic details -> Used for Sorting in Product Listing (Yes)

        - Category page sorting not working (unexpected output)

One sample attribute we have attached in screenshot which we have created, so accordingly we have added value inside the products and try to sort ASC/DESC both formats but result is not coming properly.according to product attribute value.

### Expected result

Expected Result

       Sorting should work on category page, when we set any new attributes Used for Sorting in Product Listing (Yes) 

     Below reference link of similar issue we found on google aswell but not found any fixed solution for this.

         https://github.com/magento/magento2/issues/32522

        https://magento.stackexchange.com/questions/353019/custom-sorting-is-not-working-in-magento-2-4-3-p1

        https://magento.stackexchange.com/questions/356356/magento-product-listing-sort-by-not-working

### Actual result

Sorting should work when we create a new custom attribute to sort by but currently it's not working in Magento 2.4.3 P1 EE

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-04-10 13:47
HI @sangeetavernost,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

We have created custom attribute in admin as `Length`.

<img width="1394" alt="Screenshot 2023-04-10 at 1 51 10 PM" src="https://user-images.githubusercontent.com/51680745/230885182-49da9951-1ebb-4d12-a8e5-5bcdfd9abddd.png">


In frontend we are able to sort the product using custom attribute.

<img width="1436" alt="Screenshot 2023-04-10 at 4 01 32 PM" src="https://user-images.githubusercontent.com/51680745/230885241-65212a41-a6ee-4e1e-8870-472a971d3ae1.png">



Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-04-26 06:05
Hi @sangeetavernost,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-04-26 06:05 UTC
Labels: Issue: needs update, Reported on 2.4.3-p1
