### ISSUE TITLE
Magento 2.x Braintree autozooming Bug on iPhone

### ISSUE THREAD

**Issue by winterk80** [magento/magento2#12471] opened 2017-11-28 17:33 UTC
Braintree Magento 2.x Integration. Screen Auto zooms when attempting to enter data into in all input fields in credit card details, screen does not auto zoom out after the details are entered - user has to manually zoom out. This is being caused because text size is too small. 

Replicated on iPhone 5 and iPhone 7 plus ios 10.3.3 browser is mobile safari. Cannot be seen in an emulator you must use a real device with default iOS browser setting AND default font size settings. Please see attached images

<img width="1407" alt="iphone-screen shot 2017-10-09 at 10 36 23 am" src="https://user-images.githubusercontent.com/34070582/33334543-e14c7de4-d42f-11e7-88aa-0328623e9b03.png">

**Comment by winterk80** [comment] 2017-11-28 17:35
![iphone-img_2090](https://user-images.githubusercontent.com/34070582/33334626-24f3027a-d430-11e7-9bb7-fa04ae81092a.PNG)

**Comment by magento-engcom-team** [comment] 2017-11-29 09:19
@winterk80, thank you for your report.
The issue is already fixed in 2.2.1

**Closed as completed by magento-engcom-team** 2017-11-29 09:19 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Fixed in 2.2.x, Issue: Format is not valid

**Comment by winterk80** [comment] 2017-11-29 15:18
Is there a patch for 2.1.8?
