### ISSUE TITLE
Magento_Review: disable brakes product page in admin

### ISSUE THREAD

**Issue by friizu** [magento/magento2#6430] opened 2016-09-01 06:46 UTC
Disabled reviews under admin -> stores -> configuration-> advanced ->advanced

Expected to disable reviews from store

Bug: product page in admin brakes 
Message: Attention, Something went wrong.

Console:
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
.../admin/mui/index/render/?namespace=review_listing&isAjax=true

Product reviews tab is still there and can't load. Product cant be edited. 

This bug is new in 2.1.1 was ok earlier versions

**Comment by veloraven** [comment] 2016-09-01 15:15
@friizu please try to clear browser's cache and let us know if it will help.

**Comment by friizu** [comment] 2016-09-01 15:42
@veloraven - No it won't help (cleared browser cache, cleared page cache etc). Also all is ok if i enable it again. Seems like disable wont remove review tab on admin product page and cause module is disabled it can't load content to this tab. I suppose this tab should not be on admin product page at all after module itself is disabled.

**Comment by hostep** [comment] 2016-09-01 18:06
@friizu: this bug also existed in Magento 2.1.0 and was reported 4 or 5 times before. So please try to search for existing issues before creating a new one :)
Linking to the issue where all the other issues also get linked into: https://github.com/magento/magento2/issues/5323

**Comment by friizu** [comment] 2016-09-01 18:20
Hmm I did not had this issue in 2.1.0 I got this after update from 2.1.0 to 2.1.1

**Comment by southerncomputer** [comment] 2016-09-09 19:18
Magento 2.1.1 EE does not disable di or other /etc/*.xml changes when a module is disabled! this is insane that you have to physically remove the module from the source tree and setup_database version tracker table to fully disable a module!

Try it! disable a module with events.xml or di.xml and watch it get compiled in with setup:di:compile / setup:static-content:deploy and wreak havoc on the rest of the magento installation as weird bugs get introduced!

**Comment by oshmyheliuk** [comment] 2016-09-21 11:11
Hi @friizu
Did you disable whole Review module via "Web Setup Wizard" or just disable module output in Configuration -> Advanced -> Advanced ?

**Comment by friizu** [comment] 2016-09-21 11:15
I just disabled module output in admin configuration -> advanced -> advanced, cause i may need it later, i just wanted to hide that for first release of page.

**Comment by oshmyheliuk** [comment] 2016-09-21 12:15
We already have internal ticket MAGETWO-56794 for the same issue

**Comment by hostep** [comment] 2016-09-21 13:58
@oshmyheliuk: you can close this, like I already mentioned before this is a duplicate of: https://github.com/magento/magento2/issues/5323, right?

**Comment by oshmyheliuk** [comment] 2016-09-21 14:58
@hostep yes, it is a duplicate of #5323

**Closed as completed** 2016-09-22 08:18 UTC
Labels: Issue: Ready for Work, bug report
