### ISSUE TITLE
Quick code win: Change the setting `Add Store Code to Urls` from global setting to Store Name setting (1 lower in hierarchy)

### ISSUE THREAD

**Issue by seansan** [magento/magento2#6351] opened 2016-08-26 06:53 UTC
This is quick win for Github code and cannot be **lost** in the forums

Please see: https://github.com/magento/magento2/issues/1099

and: http://magento.stackexchange.com/questions/60686/multi-multistore-multiple-brands-multiple-languages-setting-store-view-code

**Comment by veloraven** [comment] 2016-08-29 08:07
@seansan thank you for your feedback.
As I can see from #1099 it could not be marked as bug as it works by design. 
However if you insist it to be a bug please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. Please, also provide the used Magento version.
But I'm sure it will be marked as Improvement again and closed. As there are no errors or failures in this functionality, it just was designed to work this way.

**Comment by seansan** [comment] 2016-08-29 08:24
The question is if we can change the design

And make it work better

This seems a quick win: because the funcctionality already exists .... only
yhe config value needs to bee applied 1 lever lower

So in short; one needs to discuss this in the DEV / Architect team

Use cases have been supplied, the case is clear, the advantages too ...

**Comment by magento-engcom-team** [comment] 2017-11-21 08:18
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

**Closed as completed** 2017-12-12 09:24 UTC
Labels: Issue: Format is not valid
