### ISSUE TITLE
No Admin Scope for Product Attribute text swatches

### ISSUE THREAD

**Issue by paales** [magento/magento2#5142] opened 2016-06-21 19:29 UTC
Version: 2.1-rc3

<img width="985" alt="schermafbeelding 2016-06-21 om 21 28 37" src="https://cloud.githubusercontent.com/assets/1244416/16243362/2cfcec64-37f7-11e6-873a-19d1b074234a.png">

There should be an extra field for a store_id=0 swatch text field.

**Comment by paales** [comment] 2016-06-22 08:44
To clarify: Left of the 'Admin' column there should be an additional Swatch column that should store the values in the eav_attribute_option_swatch table store_id=0

**Comment by antboiko** [comment] 2016-06-22 15:12
Hi @paales , internal ticket MAGETWO-54648 was created.

Thanks,
Anton.

**Comment by heldchen** [comment] 2016-09-08 10:22
hit by this as well, using 2.1.1 - why wasn't MAGETWO-54648 scheduled for the 2.1.1 release? this makes the configurable products pretty much unusable as `eav_attribute_option_swatch.value` is stored as `NULL` and then the affected swatches not shown in the frontend at all!

**Comment by otg-chris** [comment] 2016-11-11 00:39
It's still in Magento 2.1.2. Swatches created from Magento 2.0.x did not have this problem. I had to add rows in eav_attribute_option_swatch to get it to appear in the frontend.

**Comment by bh-ref** [comment] 2017-02-21 13:32
issue still present in 2.1.4, https://github.com/magento/magento2/commit/81d6abdf90a80a5ce69058c205ab25d87af1b992 did not land in this release

**Comment by magento-engcom-team** [comment] 2017-09-20 22:20
@paales, thank you for your report.
The issue is already fixed in 2.1.8

**Closed as completed by magento-engcom-team** 2017-09-20 22:20 UTC
Labels: Issue: Ready for Work, bug report, Fixed in 2.1.x, Issue: Format is not valid
