### ISSUE TITLE
Bulk detail of the product is shown when fetch in bulk in MAGENTO2 REST API

### ISSUE THREAD

**Issue by ashishdiff** [magento/magento2#16330] opened 2018-06-22 13:01 UTC
Preconditions
Magento 2
PHP 7
Steps to reproduce-
when i fetch the product with sku detail of extension_attribute is shown,
when i fetch in bulk detail is showing NULL in extension_attribute :[ ]

Expected result-
product should not show in detail of extension_attribute[ ],tier_price [ ]

Actual result-
product of the field is shown null for few field
extension_attribute[ ],tier_price[ ] 

Provide us the procedure to get detail of the product when fetch in bulk.

**Comment by magento-engcom-team** [comment] 2018-06-22 13:01
Hi @ashishdiff. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@ashishdiff do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment] 2018-07-04 11:41
@ashishdiff, thank you for your report. I'm closing this issue as duplicate of [16345](https://github.com/magento/magento2/issues/16345). If you'd like to update it, please reopen the issue.

**Closed as completed by engcom-backlog-nickolas** 2018-07-04 11:41 UTC
Labels: Issue: Format is valid
