### ISSUE TITLE
Mviews batching will group by ids, making some of the entity_ids be skipped by the update_all_mviews index

### ISSUE THREAD

**Issue by savlo** [magento/magento2#36086] opened 2022-09-05 10:36 UTC
### Preconditions and environment

- Magento version: 2.4.3-p2
- Anything else that would help a developer reproduce the bug
It requires a new version of mysql, since only that returns sorted entity_ids upon grouping them

### Steps to reproduce

1. Assign 3000 products with random entity_ids (or any other data that can trigger any mview trigger).
2. Run indexer that updates the mview statuses

### Expected result

All the products are parsed and updated one by one

### Actual result

Some products are skipped

### Additional information

The whole splitting by batches 1000 each, for the first time will sort them by entity id and will take from the first 3000, then will take from the next 2000, and then the last 1000 products, but in the first batch might be products that are in the second batch or third, skipping some in the end.

I have found a fix for it, by adding in the file Magento/Framework/Mview/View/ChangeLogBatchWalker.php one more restriction of this:
 ->where(
     'version_id <= ?',
     $fromVersionId + $batchSize
}

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment] 2022-09-10 17:57
I seem to remember there were a bunch of fixes done in Magento 2.4.4 around batching of indexer jobs. So maybe you can verify first on Magento 2.4.4 or 2.4.5 if the issue is still there? I believe the fix in 2.4.4 was both done in core magento as in the MSI module (in case its being used).

**Comment by engcom-Lima** [comment] 2022-10-03 11:41
Hi @savlo,

Thanks for your contribution and collaboration.

I have added 3000+ products in the Magento2 and ran the indexer command **` bin/magento indexer:reindex`** 

I was getting below message :
**`Catalog Search index is locked by another reindex process. Skipping.`** and from. category 1 to 4 products are displayed rest categories products is not getting displayed because of this.

**Screenshot:**

<img width="1182" alt="Screenshot 2022-10-03 at 4 36 05 PM" src="https://user-images.githubusercontent.com/60198022/193567420-0e2e1703-7469-4ea8-a4e3-748b71637665.png">

**Frontend:**
<img width="1350" alt="Screenshot 2022-10-03 at 4 35 51 PM" src="https://user-images.githubusercontent.com/60198022/193568287-0f874af7-6561-4200-b84f-4ca1a35c62ad.png">


Are you getting same error while running indexer command? Can you provide yours custom indexer?
Also,please test it in latest `2.4-develop` and let us know if you are facing any issue.

Thanks

**Comment by savlo** [comment] 2022-10-03 11:55
@engcom-Lima I did not use that indexer, I have used a custom one that is a bit harder to implement and had mviews with ids of millions as increment_id, but the issue should still happen for any of the mviews, since that way the batcher works it is the same

**Comment by hieudmg** [comment] 2022-10-05 09:07
I have this issue too. If you guys want to fix it just override the `ChangeLogBatchWalker` class and add  replace group statement with order:

`di.xml`
```
<?xml version="1.0" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Magento\Framework\Mview\View\ChangeLogBatchWalker"
                type="Vendor\Module\Mview\View\ChangeLogBatchWalker"/>
</config>
```

`ChangeLogBatchWalker.php`
```
<?php

namespace Vendor\Module\Mview\View;

use Magento\Framework\App\ResourceConnection;
use Magento\Framework\Mview\View\ChangeLogBatchWalkerInterface;
use Magento\Framework\Mview\View\ChangelogInterface;
use Magento\Framework\Mview\View\ChangelogTableNotExistsException;
use Magento\Framework\Phrase;

class ChangeLogBatchWalker implements ChangeLogBatchWalkerInterface
{
    /**
     * @var ResourceConnection
     */
    private ResourceConnection $resourceConnection;

    /**
     * @param ResourceConnection $resourceConnection
     */
    public function __construct(
        ResourceConnection $resourceConnection
    ) {
        $this->resourceConnection = $resourceConnection;
    }

    /**
     * @inheritdoc
     */
    public function walk(ChangelogInterface $changelog, int $fromVersionId, int $toVersion, int $batchSize)
    {
        $connection = $this->resourceConnection->getConnection();
        $changelogTableName = $this->resourceConnection->getTableName($changelog->getName());

        if (!$connection->isTableExists($changelogTableName)) {
            throw new ChangelogTableNotExistsException(new Phrase("Table %1 does not exist", [$changelogTableName]));
        }

        $select = $connection->select()->distinct(true)
            ->where(
                'version_id > ?',
                $fromVersionId
            )
            ->where(
                'version_id <= ?',
                $toVersion
            )
            ->order('version_id')
            ->limit($batchSize);

        $select->from($changelogTableName, [$changelog->getColumnName()]);

        return $connection->fetchCol($select);
    }
}
```

**Comment by hieudmg** [comment] 2022-10-05 09:18
I have this issue on 2.4.3-p1 too. I was banging my head for months not knowing why the index records was always missing. I can rest now.

**Comment by engcom-Lima** [comment] 2022-10-06 12:33
Hi @savlo ,

Thanks for your contribution and collaboration.

Can you provide me custom indexer that you have craeted ? It will be really helpful to me to reproduce the issue.

Thanks

**Comment by engcom-Lima** [comment] 2022-10-25 13:01
Hi @savlo ,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Lima** 2022-10-25 13:01 UTC
Labels: Issue: needs update, Reported on 2.4.3-p2
