### ISSUE TITLE
Unable to open the product from sidebar's Compare Products block

### ISSUE THREAD

**Issue by eduard13** [magento/magento2#21101] opened 2019-02-09 17:23 UTC
### Preconditions (*)

1. Magento 2.3-develop
2.

### Steps to reproduce (*)
1. Add a product to your Compare Products list
2. Check the sidebar for new added product for comparing
3. Click on the Product's name

### Expected result (*)
1. You are redirected to product's detail page
2. 

### Actual result (*)

1. It popups a removal confirmation
![xnip2019-02-09_19-21-32](https://user-images.githubusercontent.com/15868188/52523946-f0a0c100-2c9f-11e9-8bf2-c1767bbe438b.jpg)
2.

**Comment by magento-engcom-team** [comment] 2019-02-09 17:23
Hi @eduard13. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@eduard13 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by eduard13** [comment] 2019-02-09 17:26
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-09 17:26
Hi @eduard13. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-09 17:27
Hi @eduard13, here is your [Magento instance](https://i-21101-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21101-2-3-develop.instances.magento-community.engineering/admin](https://i-21101-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-02-09 18:11
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98184` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by shikhamis11** [comment] 2019-02-09 18:11
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-09 18:11
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-09 18:12
Hi @shikhamis11, here is your [Magento instance](https://i-21101-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21101-2-2-develop.instances.magento-community.engineering/admin](https://i-21101-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-02-14 20:54
Hi @eduard13. Thank you for your report. 
The issue has been fixed in magento/magento2#21102 by @eduard13 in 2.3-develop branch
Related commit(s):
 - [60e59a8240ea8a64553d72ebdd32c4009e7286bb](https://github.com/magento/magento2/commit/60e59a8240ea8a64553d72ebdd32c4009e7286bb)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment] 2019-02-15 14:45
Hi @eduard13. Thank you for your report. 
The issue has been fixed in magento/magento2#21238 by @eduard13 in 2.2-develop branch
Related commit(s):
 - [544d99c4a30f0e89604fd2ef78dc3c6f1edb96c7](https://github.com/magento/magento2/commit/544d99c4a30f0e89604fd2ef78dc3c6f1edb96c7)

The fix will be available with the upcoming 2.2.9 release.

**Comment by eduard13** [comment] 2020-03-26 10:34
Re-opening this issue, as being reproducible again. Looks like the root issue is caused by the following PR #25380.

**Comment by magento-engcom-team** [comment] 2020-03-26 10:40
@eduard13 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2020-03-26 10:42
:white_check_mark: Confirmed by @eduard13 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32813` were created

**Issue Available**: @eduard13, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by LucasCalazans** [comment] 2020-04-04 20:35
@magento-engcom-team give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-04 20:35
Hi @LucasCalazans. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-04 20:36
Hi @LucasCalazans, here is your [Magento instance](https://i-21101-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-21101-2-4-develop.instances.magento-community.engineering/admin_0c4e](https://i-21101-2-4-develop.instances.magento-community.engineering/admin_0c4e)
Login: `a288c2e0` Password: `e18b679b25d0`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2020-06-13 01:40
Hi @eduard13. Thank you for your report. 
The issue has been fixed in magento/magento2#27451 by @eduard13 in 2.4-develop branch
Related commit(s):
 - [11195fcf2c0b67ae150ed67efe1186acd6f64ca3](https://github.com/magento/magento2/commit/11195fcf2c0b67ae150ed67efe1186acd6f64ca3)
 - [3e18da8553e06c50a1967a1755e7e86ec6d914e1](https://github.com/magento/magento2/commit/3e18da8553e06c50a1967a1755e7e86ec6d914e1)
 - [48b57fd979696107814f4f0e77ecfb01fc919e33](https://github.com/magento/magento2/commit/48b57fd979696107814f4f0e77ecfb01fc919e33)
 - [cd5558082beda9d251059f6ef31a94554d50777d](https://github.com/magento/magento2/commit/cd5558082beda9d251059f6ef31a94554d50777d)
 - [244a46bd81f1c4b02a437f7aa1f4c0f362453148](https://github.com/magento/magento2/commit/244a46bd81f1c4b02a437f7aa1f4c0f362453148)
 - [95a2a09ef276b9537f761dc9cf34af7f38c89f3a](https://github.com/magento/magento2/commit/95a2a09ef276b9537f761dc9cf34af7f38c89f3a)
 - [221ef5997a27782549f3d8de3bdda9864fdb101b](https://github.com/magento/magento2/commit/221ef5997a27782549f3d8de3bdda9864fdb101b)
 - [a93a1055affc6b27841dd0d325ac665754c85940](https://github.com/magento/magento2/commit/a93a1055affc6b27841dd0d325ac665754c85940)
 - [044dc686a8f7b3cb92a34e8f3ec3c9a39032cde4](https://github.com/magento/magento2/commit/044dc686a8f7b3cb92a34e8f3ec3c9a39032cde4)
 - [435cc35031fb7107cb9e829c007800c04dba22a0](https://github.com/magento/magento2/commit/435cc35031fb7107cb9e829c007800c04dba22a0)

The fix will be available with the upcoming 2.4.1 release.

**Closed as completed by magento-engcom-team** 2020-06-13 01:40 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Confirmed, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Area: Design/Frontend, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P3, Severity: S2, Triage: Done
