### ISSUE TITLE
Customer page locks when requesting a password reset - for about 75% of customers....pls help if possible. v2.3.2

### ISSUE THREAD

**Issue by MarvinBay** [magento/magento2#32887] opened 2021-04-27 16:12 UTC
### Preconditions (*)

1.v2.3.2
2.Customer page

### Steps to reproduce (*)

1.Simply attempt a password reset
2.Generally, page indicates that the customer is online when they are not.

### Expected result (*)

1. [Screenshots, logs or description]Allow a password reset
2.

### Actual result (*)

1. [Screenshots, logs or description]Page and ALL of Magento functionality locks for 3-5 minutes, Returns to normal after this time but goal not reached. Password not reset.
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [*] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Oscar** [comment] 2021-05-05 11:37
@magento give me 2.4-develop instance

**Comment by engcom-Oscar** [comment] 2021-05-13 09:52
Hi @MarvinBay !
Unfortunately, we are not able to reproduce the issue because of lack of details in the ticket description.  So, we have to close this ticket.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch.
Thank you for collaboration.

**Closed as completed by engcom-Oscar** 2021-05-13 09:52 UTC
Labels: Issue: needs update
