### ISSUE TITLE
CMS block search doesn't do partial matches

### ISSUE THREAD

**Issue by simonworkhouse** [magento/magento2#17589] opened 2018-08-14 05:39 UTC
When searching for blocks in the admin panel under "Content/Blocks" no results are displayed for partial matches for either the block title or identifier.
Although title will match for whole word matches.

### Preconditions

1. Magento 2.2.5
2. PHP 7.1.20
3. MySQL 5.7.23

### Steps to reproduce

1. composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition {install dir}
2. cd {install dir}
3. ./bin/magento setup:install --backend-frontname=? --db-host=? --db-name=? --db-user=? --db-password=? --base-url=? --admin-user=? --admin-password=? --admin-email=? --admin-firstname=? --admin-lastname=?
4. Create a new block with the title "Some test block" and identifier "some_test_identifier" under "Content/Blocks" in the admin panel.
5. Use the search input on the "Content/Blocks" index page and search for either "bloc" or "test_identifier"

### Expected result

The test block that we created should be shown for both search queries

### Actual result

No blocks can be found with those search queries.

**Comment by magento-engcom-team** [comment] 2018-08-14 05:39
Hi @simonworkhouse. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@simonworkhouse do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment] 2018-08-14 12:44
Hello @simonworkhouse, thank you for your report. This issue already has been fixed in 2.2-develop, and will be available in upcoming 2.2.7 release.

**Closed as completed by engcom-backlog-nickolas** 2018-08-14 12:44 UTC
Labels: Component: Cms, Component: Search, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
