### ISSUE TITLE
Notice: Undefined index: {{table_name}} in /var/www/html/vendor/magento/framework/Setup/Declaration/Schema/Declaration/SchemaBuilder.php on line 354

### ISSUE THREAD

**Issue by BorisovskiP** [magento/magento2#35339] opened 2022-04-20 13:19 UTC
### Preconditions (*)
When one module with `db_schema` has a constraint on another module where the table is created via `Install/Upgrade Schema` it leads to the error mentioned in the title. 
This happens on  `Magento version 2.4.3-p2, 2.4.4`

### Steps to reproduce (*)
1. Require https://github.com/mageplaza/magento-2-blog
2. Run `bin/magento setup:upgrade`.
3. Create a module with this `db_schema.xml` file:
```

<?xml version="1.0" ?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:Setup/Declaration/Schema/etc/schema.xsd">
    <table name="test_mageplaza" comment="Test Mageplaza Blog Posts">
        <column name="project_id" xsi:type="int" nullable="false" identity="false" unsigned="true" comment="Project ID"/>
        <column name="post_id" xsi:type="int" padding="10" unsigned="true" nullable="false" comment="Post ID"/>
        <index referenceId="TEST_MAGEPLAZA_BLOG_POSTS_POST_ID" indexType="btree">
            <column name="post_id"/>
        </index>
        <constraint xsi:type="foreign" referenceId="FK_4D4A10A4534D098BDCCE6BC9C2CABAD7" table="test_mageplaza" column="project_id" referenceTable="test_project" referenceColumn="project_id" onDelete="CASCADE"/>
        <constraint xsi:type="foreign" referenceId="FK_FAF4B768352B9AD4307CC7AFD4E2932A" table="test_mageplaza" column="post_id" referenceTable="mageplaza_blog_post" referenceColumn="post_id" onDelete="CASCADE"/>
        <constraint xsi:type="primary" referenceId="PRIMARY">
            <column name="project_id"/>
            <column name="post_id"/>
        </constraint>
    </table>
</schema>

```
4.  Run `bin/magento setup:upgrade`.

### Expected result (*)
1.Setup upgrade runs without issues

### Actual result (*)
`Notice: Undefined index: mageplaza_blog_post in /var/www/html/vendor/magento/framework/Setup/Declaration/Schema/Declaration/SchemaBuilder.php on line 354`

Somehow Magento tries to apply the same foreign key if one module uses Install/Upgrade Schema and the other uses db_schema.xml

### Additional information to reproduce the issue
1. Create a directory under `app/code` called `Test/Module`.
2. Copy the contents from https://github.com/BorisovskiP/test-module to that directory.
3. Run `bin/magento setup:upgrade`

Expected result:

Both tables should be created

Actual result:

`Warning: Undefined array key "test_table" in /var/www/html/vendor/magento/framework/Setup/Declaration/Schema/Declaration/SchemaBuilder.php on line 354`

Tested on Magento 2.4.4, PHP 8.1.4

For PHP 7.4 the message is the one from the title of this issue. 

You can also test that if you comment out the contents of `db_schema.xml` and run `setup:upgrade` the `test_table` (defined in `\Test\Module\Setup\InstallSchema`) will be created, and once you revert the commented section and again run `setup:upgrade` the same error message will be thrown. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2022-04-25 11:03
Hello @BorisovskiP,

Thanks for the reporting and collaboration!

We have tried to reproduce the issue with the mentioned steps in both Magento 2.4-develop and 2.4.4 but for us we are getting the below errors, after running `setup:upgrade`:

### For 2.4-develop
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/51681618/165076260-b845ccdb-ae68-458c-9203-b9226042fcb0.png">

### For 2.4.4
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/51681618/165076695-a632b17d-5f72-49c8-9952-547e88a4fcb3.png">

Please update the reproduction steps, this will help us in moving further.

Thanks

**Comment by BorisovskiP** [comment] 2022-05-06 13:55
@engcom-Hotel ok lets try a different approach:

1. Create a directory under `app/code` called `Test/Module`.
2. Copy the contents from https://github.com/BorisovskiP/test-module to that directory.
3. Run `bin/magento setup:upgrade`

Expected result:

Both tables should be created

Actual result:

`Warning: Undefined array key "test_table" in /var/www/html/vendor/magento/framework/Setup/Declaration/Schema/Declaration/SchemaBuilder.php on line 354`

Tested on Magento 2.4.4, PHP 8.1.4

For PHP 7.4 the message is the one from the title of this issue. 

You can also test that if you comment out the contents of `db_schema.xml` and run `setup:upgrade` the `test_table` (defined in `\Test\Module\Setup\InstallSchema`) will be created, and once you revert the commented section and again run `setup:upgrade` the same error message will be thrown.

**Comment by engcom-Hotel** [comment] 2022-05-09 10:36
Hello @BorisovskiP,

Thanks for your reply!

We have tried to reproduce the issue in Magento 2.4-develop branch, with your latest comment. We are able to reproduce the issue. Please find attached the screenshot for reference:

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/51681618/167393230-8a147a75-40f5-4d36-bff8-0b5cb8ae1185.png">

I suggest you try [declarative schema](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/declarative-schema/), for this use case. Let us know in case we have missed anything.

Thanks

**Comment by BorisovskiP** [comment] 2022-05-10 07:58
Thanks for checking and confirming the issue @engcom-Hotel. 

Using `declarative schema` is the way to go, but there are still a lot of third party modules which use `Install/Upgrade Schema` and this issue prevents us from integrating these modules into Magento.

This incompatibility between `db_schema` and `Install/Upgrade Schema` means that in order for newly developed modules to be compatible with other third party modules that do not use `db_schema`, we would need to either write code which is compatible with their module (use `Install/Upgrade Schema` instead of `db_schema`) or talk with the developers of these modules and ask them to update their modules (which they may or may not do). 

Currently the only way i see of this working is either both modules use either `db_schema` or `Install/Upgrade Schema` which should not be the case.

**Comment by engcom-Hotel** [comment] 2022-05-12 06:47
Hello @BorisovskiP,

I agree with your point. The issue is reproducible by the given steps in the main description. Hence confirming the issue.

Thanks

**Comment by engcom-Hotel** [comment] 2022-11-24 12:59
Hello @BorisovskiP,

We had a discussion internally with the developers and we have come to the below conclusion:

Creating a table using InstallSchema.php and using its key to create a foreign key using db_schema.xml is not supported by Magento. Please refer devdocs link i.e., https://developer.adobe.com/commerce/php/development/components/declarative-schema/configuration/ 
  
<img width="665" alt="image" src="https://user-images.githubusercontent.com/51681618/203790281-d330314e-3748-45ae-b630-513055b8dfae.png">

To create a foreign key, both tables should be created using db_schema.xml and then create a foreign key accordingly. However, we are able to fix the issue but that's not an adequate fix as we fixed only the console error but couldn't create the foreign key it was meant for.  

So, the only way this works is that both modules use either db_schema or Install/Upgrade Schema. 

Thanks

**Comment by BorisovskiP** [comment] 2022-11-24 18:16
@sprankhub please check the last message from @engcom-Hotel

**Comment by sprankhub** [comment] 2022-12-04 21:19
@engcom-Hotel, thanks for the clarification. I like that this is now explicitly mentioned in the dev docs :)

**Comment by engcom-Hotel** [comment] 2022-12-05 07:14
Hello @sprankhub @BorisovskiP,

Thanks for the confirmation. We are closing this issue as the behavior is expected and mentioned in the devdocs.

Thanks

**Closed as completed by engcom-Hotel** 2022-12-05 07:14 UTC
Labels: Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P2, Progress: done, Issue: needs update, Area: Framework, Reported on 2.4.4

**Comment by magenizr** [comment] 2023-06-27 01:06
We ran into the same issue this morning on a local environment, but for table `wishlist`. Here is how it has been unlocked:

1. Edit `vendor/magento/framework/Setup/Declaration/Schema/Declaration/SchemaBuilder.php`
2. Find the line around `$referenceData['referenceTable'] = $this->tables[$referenceTableName];`
3. Add this line before

```
if (!isset($this->tables[$referenceTableName])) {
    continue;
}
```
4. Run `php bin/magento setup:upgrade` ( Should run through with no errors )
5. Edit `vendor/magento/framework/Setup/Declaration/Schema/Declaration/SchemaBuilder.php` again and remove the modification.
6. Run `php bin/magento setup:upgrade` again ( Should run through with no errors )
7. Table created as expected

```
MariaDB [magento]> describe wishlist;
+--------------+----------------------+------+-----+---------+----------------+
| Field        | Type                 | Null | Key | Default | Extra          |
+--------------+----------------------+------+-----+---------+----------------+
| wishlist_id  | int(10) unsigned     | NO   | PRI | NULL    | auto_increment |
| customer_id  | int(10) unsigned     | NO   | UNI | 0       |                |
| shared       | smallint(5) unsigned | NO   | MUL | 0       |                |
| sharing_code | varchar(32)          | YES  |     | NULL    |                |
| updated_at   | timestamp            | YES  |     | NULL    |                |
+--------------+----------------------+------+-----+---------+----------------+
5 rows in set (0.001 sec)
```

After this we stopped investigating it further.
