### ISSUE TITLE
Magento 2.3.5 Wrong date on PDF invoice

### ISSUE THREAD

**Issue by cristienache** [magento/magento2#28158] opened 2020-05-08 11:21 UTC
### Preconditions (*)
1. Magento 2.3.5

### Steps to reproduce (*)

1. Go to Sales>Invoices>View>Print PDF invoice

### Expected result (*)
1. Invoice date on PDF file should be 08/05/2020 (today's date)

### Actual result (*)
1. ![Capture](https://user-images.githubusercontent.com/33024764/81400950-2a23de80-9126-11ea-991e-09a67e3a1187.JPG)
2. Did all the steps shown on this issue: [#26675](https://github.com/magento/magento2/issues/26675) and the error I am given is:
`Could not apply patch! Skipping. The error was: Cannot apply patch patches/composer/267
01.diff

Installation failed, reverting ./composer.json to its original content.

                                                         
  [Exception]                                            
  Cannot apply patch 1.0 (patches/composer/26701.diff)! `

**Comment by sudheers-kensium** [comment] 2020-05-08 14:44
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-08 14:44
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-05-08 14:45
Hi @sudheers-kensium, here is your [Magento instance](https://i-28158-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28158-2-4-develop.instances.magento-community.engineering/admin_b819](https://i-28158-2-4-develop.instances.magento-community.engineering/admin_b819)
Login: `e15becae` Password: `62d29ac5550d`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment] 2020-05-08 15:26
@cristienache I have verified in Magento 2.4-develop instance, it is working fine. 

Are you able to reproduced on  Magento 2.4-develop instance?

![image](https://user-images.githubusercontent.com/50358141/81420281-64fd3500-916d-11ea-8658-54fbf475bdf6.png)

**Comment by cristienache** [comment] 2020-05-09 06:41
@sudheers-kensium the issue is on our live magento 2.3.5 website which was updated from 2.3

**Comment by StuartAnderton** [comment] 2020-05-11 09:24
Seeing this on 2.3.5-p1 with UK locale.

**Comment by Quazz** [comment] 2020-05-11 10:44
https://github.com/magento/magento2/pull/26701

That PR fixes it for 2.4, also works fine when you apply it to 2.3.5 in my experience.

**Comment by sudheers-kensium** [comment] 2020-05-11 10:57
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-11 10:58
Magento instance deployment temporary unavailable due to service maintenance.

**Comment by sudheers-kensium** [comment] 2020-05-11 14:14
I am able to reproduced in Magento 2.3.5-p1 .

![image](https://user-images.githubusercontent.com/50358141/81571643-d7fdea00-93bf-11ea-9873-fa6beef4a29f.png)

**Comment by magento-engcom-team** [comment] 2020-05-11 14:15
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34182` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gwharton** [comment] 2020-05-12 11:07
From the looks of it magento isnt backporting fixed issues into 2.3 anymore. You need to manually patch your install using the PR merged into 2.4-develop.

**Comment by CarmineDamore78** [comment] 2020-05-19 11:51
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment] 2020-05-19 11:51
Hi @CarmineDamore78. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by Ylmzef** [comment] 2020-05-20 10:47
Same issue on Magento ver. 2.3.4-p2

**Comment by gwharton** [comment] 2020-05-20 10:54
This has been fixed in 2.4-develop in PR #26701. The bug exists in all 2.3 releases at the moment. Magento has stopped us targetting backports into 2.3 branch so whether this gets fixed in 2.3 at all is up to Magento and out of the hands of the community.

**Comment by Ylmzef** [comment] 2020-05-21 03:59
Applied the patch https://github.com/magento/magento2/commit/2d31571f1bacd11aa2ec795180abf682e0e9aede.diff

It's now fixed!
thanks @gwharton

**Comment by JustICTNL** [comment] 2020-06-04 12:01
@Ylmzef how can I apply the patch to fix this issue?

**Comment by alecx15** [comment] 2020-07-15 14:21
How can we apply the patch to fix the issue?

**Comment by JustICTNL** [comment] 2020-07-15 15:40
@alecx15 

See topic: https://github.com/magento/magento2/issues/26675
And check my last comment like below.

I am using Magento 2.3.4

I have applied @edenduong' code to the file located in; /vendor/magento/framework/Stdlib/DateTime/Timezone.php (line 196)

###############

public function scopeDate($scope = null, $date = null, $includeTime = false)
{
$timezone = new \DateTimeZone(
$this->_scopeConfig->getValue($this->getDefaultTimezonePath(), $this->_scopeType, $scope)
);
switch (true) {
case (empty($date)):
$date = new \DateTime('now', $timezone);
break;
case ($date instanceof \DateTime):
case ($date instanceof \DateTimeImmutable):
$date = $date->setTimezone($timezone);
break;
default:
$date = new \DateTime(is_numeric($date) ? '@' . $date : $date);
$date->setTimezone($timezone);
break;
}

    if (!$includeTime) {
        $date->setTime(0, 0, 0);
    }

    return $date;
}
###################

This corects dates on invoices.
This works now for me. i updgraded to Magento 2.3.5-P1 and now it works.
FInd the file with command:
find . -name Timezone.php
Result: ./vendor/magento/framework/Stdlib/DateTime/Timezone.php

I changed above in ./vendor/magento/framework/Stdlib/DateTime/Timezone.php
And now it works :)

**Comment by alecx15** [comment] 2020-07-15 17:12
> @alecx15
> 
> See topic: #26675
> And check my last comment like below.
> 
> I am using Magento 2.3.4
> 
> I have applied @edenduong' code to the file located in; /vendor/magento/framework/Stdlib/DateTime/Timezone.php (line 196)
> 
> ###############
> 
> public function scopeDate($scope = null, $date = null, $includeTime = false)
> {
> $timezone = new \DateTimeZone(
> $this->_scopeConfig->getValue($this->getDefaultTimezonePath(), $this->_scopeType, $scope)
> );
> switch (true) {
> case (empty($date)):
> $date = new \DateTime('now', $timezone);
> break;
> case ($date instanceof \DateTime):
> case ($date instanceof \DateTimeImmutable):
> $date = $date->setTimezone($timezone);
> break;
> default:
> $date = new \DateTime(is_numeric($date) ? '@' . $date : $date);
> $date->setTimezone($timezone);
> break;
> }
> 
> ```
> if (!$includeTime) {
>     $date->setTime(0, 0, 0);
> }
> 
> return $date;
> ```
> 
> }
> ###################
> 
> This corects dates on invoices.
> This works now for me. i updgraded to Magento 2.3.5-P1 and now it works.
> FInd the file with command:
> find . -name Timezone.php
> Result: ./vendor/magento/framework/Stdlib/DateTime/Timezone.php
> 
> I changed above in ./vendor/magento/framework/Stdlib/DateTime/Timezone.php
> And now it works :)

Hi mate , thank you very much for your answer i already did that ... i have the same version 2.3.4 like you but still doesn't work!

I think it's because i didn't update to 2.3.5-P1 yet! Can you tell me how i can do the update?

Thanks

**Comment by engcom-Delta** [comment] 2020-08-20 06:44
@cristienache , thank you for your report. Issue is not reproducible on the latest 2.4-develop
![Peek 2020-08-20 09-38](https://user-images.githubusercontent.com/51681379/90725875-7f48c200-e2c9-11ea-8a06-73cff1dc1030.gif)

If you'd like to update the issue, please reopen it.

**Closed as completed by engcom-Delta** 2020-08-20 06:44 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Format is valid, Reproduced on 2.4.x, Reported on 2.3.5
