### ISSUE TITLE
Uppercase letters not allowed for --scope-code argument in the config:set command

### ISSUE THREAD

**Issue by dot319** [magento/magento2#30616] opened 2020-10-23 10:06 UTC
### Preconditions (*)

1. Magento 2.3.2-p2

### Steps to reproduce (*)

1. Create a website with a website code that contains uppercase letters (for example, Our_Website)
2. Try to set a configuration value by using the config:set command, for example: 
bin/magento config:set --lock-env web/unsecure/base_url 'https://www.ourwebsite.com/' --scope=website --scope-code=Our_Website

### Expected result (*)

1. The configuration is saved in the website scope for the indicated website

### Actual result (*)

1. An error message: "The scope code can include only lowercase letters (a-z), numbers (0-9) and underscores (_). Also, the first character must be a letter."

Note:
I understand if Magento doesn't want to work with website codes that contain uppercase letters. However, if that is the case, then it should not be possible to create a website with uppercase letters in the website code in the first place. So a solution would be to either allow upper-case letters in the --scope-code argument of the config:set command, or to not allow websites with uppercase letters in the website code.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dot319** [comment] 2020-10-23 10:08
The bug is related to console commands so I wont be able to reproduce the error in the Magento instance provided by the bot

**Comment by robolmos** [comment] 2020-10-29 21:41
Same issue here.

**Comment by robolmos** [comment] 2020-10-30 22:12
@dot319 Similar previously closed issue was just reopened: https://github.com/magento/magento2/issues/25668

**Comment by engcom-Alfa** [comment] 2020-11-09 14:17
Duplicate of #25668

**Closed as completed by engcom-Alfa** 2020-11-09 14:17 UTC
Labels: Event: MageCONF CD 2020, Reported on 2.3.2-p2
