### ISSUE TITLE
Price change when Locale changes to Serbian

### ISSUE THREAD

**Issue by danijelkusic** [magento/magento2#13230] opened 2018-01-16 21:44 UTC
### Preconditions

I have a multilingual magento. It's all in EURO currency. When "Locale" changes to Serbian (In Serbian Store View ), the price changes. Instead of e.g. € 441.16 be 0.441 €

### Expected result
The price should remain unchanged

Magento 2.2.2
PHP 7.1.13
SQL 5.5.32
System Linux

![serbian](https://user-images.githubusercontent.com/35351307/35013779-ba82fffc-fb0e-11e7-91ab-9e8234534d5c.jpg)
Photo attached

**Comment by magento-engcom-team** [comment] 2018-01-17 11:44
@danijelkusic, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by danijelkusic** [comment] 2018-01-17 11:51
It's nice, but is there anything I can do to fix the problem right now?

There is one more thing. When the interface language is set, there is Serbian (Cyrillic). That's fine, but there should be a Serbian (Latin) too

**Comment by MiodragB** [comment] 2018-03-02 16:36
I have the exact same issue. It would be nice to know ETA when it will be fixed? 
Also it would be really nice if we could know is there a some workaround or a quick fix for this?

Thanks

**Comment by engcom-Echo** [comment] 2019-12-12 09:21
Hello All

I am not able to reproduce this issue on the 2.4-develop branch by provided steps.

**Testing scenario:**
**Preconditions:**

1. The "Locale" is changed to Serbian. 
2. The "Currency" is changed to EURO

**Steps to reproduce:**

1. Go to frontend
**Result**
The price has not changed
![Screenshot_10](https://user-images.githubusercontent.com/51681435/70699143-594a3700-1cd1-11ea-9772-e7ed19daf08c.png)
![Screenshot_11](https://user-images.githubusercontent.com/51681435/70699151-5b13fa80-1cd1-11ea-99ab-27afe0d61014.png)
So I have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Echo** 2019-12-12 09:21 UTC
Labels: Issue: Format is not valid
