### ISSUE TITLE
Print Invoice - Arabic language not supported

### ISSUE THREAD

**Issue by sveralex** [magento/magento2#10822] opened 2017-09-08 13:19 UTC
### Preconditions

Print Invoice - Arabic language not supported ?
Please see attached PDF sample
[invoice2017-09-08_12-26-50.pdf](https://github.com/magento/magento2/files/1287963/invoice2017-09-08_12-26-50.pdf)

**Comment by orlangur** [comment] 2017-09-08 14:33
Possible workaround: https://github.com/magento/magento2/issues/7095#issuecomment-315722378

Closing as duplicate of https://github.com/magento/magento2/issues/9666

**Closed as completed by orlangur** 2017-09-08 14:33 UTC
Labels: bug report, duplicate
