### ISSUE TITLE
M2.1 "This is a required field" wrong position

### ISSUE THREAD

**Issue by kfaer** [magento/magento2#5569] opened 2016-07-10 20:51 UTC
the position of "This is a required field." message in configurable product is in wrong place
![this-is-required](https://cloud.githubusercontent.com/assets/8407530/16716021/8eb068b4-4701-11e6-846e-83f183e4d13a.PNG)

**Comment by JDavidVR** [comment] 2016-07-10 23:50
having same problem, weird in early version it was working well

**Comment by pboisvert** [comment] 2016-07-11 05:00
closing as this is a duplicate of #5428

**Closed as completed by pboisvert** 2016-07-11 05:00 UTC
