### ISSUE TITLE
Product search 'Something went wrong with processing the default view and we have restored the filter to its original state.'

### ISSUE THREAD

**Issue by kgarrettWY** [magento/magento2#38471] opened 2024-02-26 09:16 UTC
### Preconditions and environment

When searching for product code 'UHY0NAILD', I cannot exit the error loading screen and make new search or click into product page.
Have realised this is glitching as our main page on the website (the product should not be public on switched on)

### Steps to reproduce

1. Open catalog
2. Go to products
3. Search 'UHY0NAILD'
4. Search

### Expected result

It should load this item and allow the product page to be clicked

### Actual result

Error loading-' Something went wrong with processing the default view and we have restored the filter to its original state.'

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-02-27 06:40
Hi @kgarrettWY,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

![Screenshot from 2024-02-27 11-38-20](https://github.com/magento/magento2/assets/51680745/46dc1101-85aa-4701-b7a7-f607ef74957f)


We are able to load this item and allow the product page to be clicked.

Could you please refer this comment https://github.com/magento/magento2/issues/26515#issuecomment-802797711 it may resolves the issue and check the issue in Magento 2.4-develop instance.

Thanks.

**Comment by kgarrettWY** [comment] 2024-02-27 09:00
Morning Venkata,

Thanks for your help.

I searched for the code UHY0NAILD and now the page is stuck on the below.
When I click ‘ok’ it leaves the buffer/loading wheel and I cannot search any other products.

Please let me know if this can be fixed?

***@***.***

Many thanks,

Kitty Garrett
Customer Service Coordinator

William Yeoward
270 Kings Road
London
SW3 5AW
Tel +44 (0) 20 7349 7828
www.williamyeoward.com<http://www.williamyeoward.com/>

**Comment by engcom-Bravo** [comment] 2024-02-28 10:11
Hi @kgarrettWY,

Thanks for your update.

Kindly check the issue  if there are any third party modules installed which might be causing the issue.

Thanks.

**Comment by kgarrettWY** [comment] 2024-02-28 15:03
Hi Venkata,

How could I check for this please?

Kind regards,

Kitty Garrett
Customer Service Coordinator

William Yeoward
270 Kings Road
London
SW3 5AW
Tel +44 (0) 20 7349 7828
www.williamyeoward.com<http://www.williamyeoward.com/>

**Comment by engcom-Bravo** [comment] 2024-03-01 09:28
Hi @kgarrettWY,

Thanks for your update.

Please refer this comment https://github.com/magento/magento2/issues/26515#issuecomment-802797711 it may resolves your issue.

Thanks.

**Comment by kgarrettWY** [comment] 2024-03-01 13:20
Thank you for your help😊

Kitty Garrett
Customer Service Coordinator

William Yeoward
270 Kings Road
London
SW3 5AW
Tel +44 (0) 20 7349 7828
www.williamyeoward.com<http://www.williamyeoward.com/>

**Comment by engcom-Bravo** [comment] 2024-03-13 05:38
Hi @kgarrettWY,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-03-13 05:38 UTC
Labels: Issue: needs update, Reported on 2.4.x
