### ISSUE TITLE
Product Flat Indexer IFNULL on nullable datetime attributes fallbacks to global

### ISSUE THREAD

**Issue by vo1** [magento/magento2#35499] opened 2022-05-19 08:56 UTC
### Preconditions and environment

- Magento version 2.4.3, but I suppose happens on any.
When you have store/website datetime attribute with global value set by some API call, you cannot have scoped values properly loaded into flat data when they are set to null.
e.g.
Product.attribute.global = 2022-05-19T00:00:00
Product.attribute.store1 = 2022-05-22T00:00:00
Product.attribute.store2 = NULL (**cleared in backend with unchecked "Use default" saves as NULL value into database**)

Will work totally fine on product load or when flat index is disabled, but when product flat enabled results in:
catalog_product_flat_1 = 2022-05-22T00:00:00
catalog_product_flat_2 = 2022-05-19T00:00:00

### Steps to reproduce

1. Create new datetime attribute scoped to website or store.
2. Set its value on global level to some date, eg. 2022-05-19
3. Open store scope, uncheck "Use default" and clear value so it will be saved as NULL into database
4. Reindex product flat data.

### Expected result

Properly fall back to scoped value when attribute is empty for store/website scope

### Actual result

Product flat data for the entity on store will contain global value e.g. 2022-05-19 instead of NULL.

### Additional information

ELECT `et`.`row_id`,
       `et`.`entity_id`,
       Ifnull(st1.value, t1.value) AS `bestelbaar_vanaf`,
       Ifnull(st2.value, t2.value) AS `news_from_date`,
       Ifnull(st3.value, t3.value) AS `news_to_date`,
       Ifnull(st4.value, t4.value) AS `orderable_until`,
       Ifnull(st5.value, t5.value) AS `special_from_date`,
       Ifnull(st6.value, t6.value) AS `special_to_date`
FROM   `catalog_product_entity_tmp_indexer` AS `et`
       INNER JOIN `catalog_product_entity` AS `e`
               ON e.entity_id = et.entity_id
                  AND ( e.created_in <= '1556550000'
                        AND e.updated_in > '1556550000' )
       LEFT JOIN `catalog_product_entity_datetime` AS `t1`

### Release note

\Magento\Catalog\Model\Indexer\Product\Flat\TableBuilder::_fillTemporaryTable generates the IFNULL fallbacks.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-05-31 12:45
Hi @vo1 ,
Thank you for reporting and collaboration. Verified the issue on magento 2.4-develop branch but cannot able to reproduce the issue with provided steps.
Step 3: We cannot save by clearing the value to be saved as NULL as the attribute is a required/mandatory field.
![image](https://user-images.githubusercontent.com/60198231/171176100-b1ffb7b7-1ce8-41a8-86e9-f783b8ca1cd5.png)
Kindly recheck the issue again on Magento 2.4-develop branch as it is having latest code base / upcoming 2.4.x release and elaborate steps to reproduce if you are still facing issues.
Thank you.

**Comment by vo1** [comment] 2022-05-31 12:57
Hi.
Make it non-mandatory please and you will see.
Our Magento instance uses datetime attributes to show whether product is shared between websites: a real sales website and a demo website where you can order sample products. Both of those using same attribute, it is normal situation when on sales website product is being sold out as backorder but on samples you can order 1 of each directly. Nullable is needed for this to work and it works only when flat index is off.

**Comment by engcom-November** [comment] 2022-06-15 10:02
Hi @vo1 ,
We are closing this issue as there has been no latest update on the same. Kindly reopen/ create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-06-15 10:02 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update

**Comment by thampe** [comment] 2022-08-19 07:13
Hi,

could you reopen the issue? You can find the issue, if you take a look inside the implementation. 

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/Indexer/Product/Flat/TableBuilder.php#L333

```
SELECT `et`.`entity_id`, IFNULL(st1.value, t1.value) AS `description` FROM `catalog_product_entity_tmp_indexer` AS `et`
 INNER JOIN `catalog_product_entity` AS `e` ON e.entity_id = et.entity_id
 LEFT JOIN `catalog_product_entity_text` AS `t1` ON e.entity_id = t1.entity_id AND t1.attribute_id = 72 AND t1.store_id = 0
 LEFT JOIN `catalog_product_entity_text` AS `st1` ON e.entity_id = st1.entity_id AND st1.attribute_id = 72 AND st1.store_id = 1
...
```

The sql query clearly has an `IFNULL(st1.value, t1.value)` check and defaults to the value from the admin store if store value is `null`. Which is the case if you override it in the storeview with an empty value. So the described case ist a valid case, even if you can be not reproduce the issue directly.

Regarding your problem:

> Also as per Magento [devdocs](https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-index.html), catalog_product_flat is not listed in the supported indexers.
> Please check the supported indexers using bin/magento indexer:info

You need to enable the flat index, there is also a support doument for that: https://docs.magento.com/user-guide/catalog/catalog-flat.html

Thanks!

**Comment by thampe** [comment] 2022-10-04 08:54
Hi @engcom-November,

could you reopen the issue? Details you can find in my comment above.

Thanks.
