### ISSUE TITLE
Our stock quantities and salable quantities are not matching up

### ISSUE THREAD

**Issue by mlarsonbrianstoys** [magento/magento2#35225] opened 2022-03-24 14:23 UTC
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mlarsonbrianstoys** [comment] 2022-03-24 14:29
Not able to change the Salable/Default Stock. Can't really take pictures of the problem

**Comment by engcom-November** [comment] 2022-04-07 05:49
Hi @mlarsonbrianstoys ,
Thank you for reporting and collaboration. However we are not able to reproduce the issue on Magento 2.4-develop branch with provided steps. Kindly recheck the issue on Magento 2.4-develop branch as it is the upcoming 2.4.x release and elaborate steps to reproduce if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-04-21 06:00
Hi @mlarsonbrianstoys ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-04-21 06:00 UTC
Labels: Issue: needs update
