### ISSUE TITLE
redirect to cart does not work with simple products

### ISSUE THREAD

**Issue by skeutmeier** [magento/magento2#37603] opened 2023-06-12 13:11 UTC
### Preconditions and environment

Magento CE 2.4.6

When adding a simple product to cart, customer is not redirected to cart despite the setting "After Adding a Product Redirect to Shopping Cart" is enabled

### Steps to reproduce

Open a simple product in storefront
click "add to cart"

### Expected result

Product added to cart, customer redirected to cart

### Actual result

product added to cart, customer stays on product detail page

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by skeutmeier** [comment] 2023-06-12 13:12
@magento give me 2.4.6 instance

**Comment by skeutmeier** [comment] 2023-06-12 13:21
> Hi @skeutmeier, here is your Magento Instance: https://7c87ccd1b9d23a5daab8f0af0da7e8e3.instances-prod.magento-community.engineering Admin access: https://7c87ccd1b9d23a5daab8f0af0da7e8e3.instances-prod.magento-community.engineering/admin_e4ed Login: 820351e0 Password: 6650332d9d24

frontend does not work at all, only backend works.

unable to test
![Screenshot from 2023-06-12 15-21-32](https://github.com/magento/magento2/assets/73367887/635aebdd-b02f-4b33-a0c3-fb6052937b9a)

**Comment by engcom-Bravo** [comment] 2023-06-13 06:48
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-06-13 07:10
Hi @skeutmeier,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and Magento 2.4.6 instance and the issue is not reproducible.Kindly refer the attached video.


**Steps to reproduce**

- Open a simple product in storefront
- click "add to cart"


<img width="1188" alt="Screenshot 2023-06-13 at 12 33 44 PM" src="https://github.com/magento/magento2/assets/51680745/f5c711e4-31e8-4936-a0bc-6cc606e7f66b">


After adding the product we are able to redirect to cart successfully.

**Magento 2.4-develop instance**


https://github.com/magento/magento2/assets/51680745/3274ed38-323f-40e3-a58d-7e18ee3cdb5a



**Magento 2.4.6 Instance**


https://github.com/magento/magento2/assets/51680745/228db51f-da9d-4603-b3ab-a0f0cc46036a



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-06-27 06:16
HI @skeutmeier,

Please provide us latest update on this https://github.com/magento/magento2/issues/37603#issuecomment-1588679496 if you are able to reproduce the issue provide us steps to reproduce the issue.Please let us know if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-07-10 06:08
Hi @skeutmeier,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-07-10 06:08 UTC
Labels: Issue: needs update, Reported on 2.4.6
