### ISSUE TITLE
Miss item and total information in order (invoice, creditmemo) email when using email template

### ISSUE THREAD

**Issue by adamphh** [magento/magento2#30773] opened 2020-11-04 08:46 UTC
### Preconditions (*)

Magento Community 2.3.5

### Steps to reproduce (*)

1. Go to back-end
2. Select menu "Marketing / Email Templates"
3. Create a new email template
4. Select "New Order" option in "Load Default Template" section and load it (https://prnt.sc/vd4zj8)
5. Save email template
6. Go to Configuration >> Sales >> Sales Emails (https://prnt.sc/vd50zw)
7. Select the email template above in field "New Order Confirmation Template" and save it (https://prnt.sc/vd51a5)
8. Create a new order 
9. See the error (https://prnt.sc/vd50pi)

### Expected result (*)

1. Send the email with Item and total information
https://prnt.sc/vd52sj

### Actual result (*)

1. Missing item and total information in order (invoice, creditmemo) email
 https://prnt.sc/vd50pi

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment] 2020-11-04 11:54
Hi @adammagestore .
Unfortunately, we are not able to reproduce this issue on 2.4.1, and fresh 2.4-develop. 

**Manual testing scenario:**

1. Go to back-end
2. Go to "Marketing / Email Templates"
3. Create a new email template
4. Select "New Order" option in "Load Default Template" section and load it 
5. Save email template
6. Go to Configuration >> Sales >> Sales Emails;
7. Select the email template above in field "New Order Confirmation Template" and save it.
8. Create a new order

**Actual Result:** :heavy_check_mark:   The email with Item and total information

![Screenshot from 2020-11-04 13-14-42](https://user-images.githubusercontent.com/51679138/98108572-d90e6080-1ea4-11eb-9f50-7a749b9d7c82.png)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-11-04 11:54 UTC
Labels: not-confirmed
