### ISSUE TITLE
Shipping Estimator does not work on Internet Explorer 11

### ISSUE THREAD

**Issue by Jrb1x** [magento/magento2#7476] opened 2016-11-17 19:13 UTC
On the edit cart page, the shipping estimator does not work on IE 11.

### Preconditions

1. Magento 2.1, PHP7, MySQL 5.6.34

### Steps to reproduce

1. Add an item to the cart. Click edit cart from the minicart. Attempt to esimate shipping by putting in shipping information.

### Expected result

1. Shipping estimates should get returned like all other browsers.

### Actual result

1. The loading animation stays stuck and does not return shipping estimates.

**Comment by shankpunk** [comment] 2016-11-21 09:39
hi, look into this https://github.com/magento/magento2/issues/5358

**Comment by veloraven** [comment] 2016-11-24 12:17
I'm closing this issue as a duplicate of #7051

**Closed as completed by veloraven** 2016-11-24 12:17 UTC
