### ISSUE TITLE
Paypal Braintree - Stored Payment Methods page error when disabled Telephone field

### ISSUE THREAD

**Issue by khoimm92** [magento/magento2#38903] opened 2024-07-04 10:02 UTC
### Preconditions and environment

- Magento version 2.4.7-p1

### Steps to reproduce

- In Admin, disable Customer Telephone field by:
Store -> Configuration -> Customers -> Customer Configuration -> Name and Address Options -> set **Show Telephone** to **No**

From frontend:
- Customer login
- Navigate to **Stored Payment Methods** page from Sidebar

### Expected result

Can add a new Card.

### Actual result

There's an error on Console window, but the message is not clear:
![image](https://github.com/magento/magento2/assets/6015437/f7299315-90d1-46c8-83d6-ee5a340d4f75)

When clicking Add new Credit Card, there's no Address form, and infinitive loading once submitting, also a new error on Console window:
![image](https://github.com/magento/magento2/assets/6015437/25d2b9bf-b635-4789-a797-1f694ef720db)

### Additional information

Although the error message is not helpful, I've spotted the flaw code in:
`vendor/paypal/module-braintree-core/view/frontend/web/js/customer/modals/address-modal.js`
![image](https://github.com/magento/magento2/assets/6015437/8b7c19a8-95d3-43ee-902e-963ebf3b87d5)

> telephone: document.getElementById('telephone').value,
This line breaks the process of rendering Address form.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2024-07-09 10:08
Hi @khoimm92 

Thanks for reporting and collaboration.

Verified the issue on the Magento 2.4 dev instance and the issue is not reproducible.

Steps to reproduce
In Admin, disable the Customer Telephone field by:
Store -> Configuration -> Customers -> Customer Configuration -> Name and Address Options -> Set Show Telephone to No

Able to store the payment methods page when the telephone field is disabled.

Please take a look at the screenshots I've attached.

When the telephone field is disabled.

<img width="1440" alt="38903_1" src="https://github.com/magento/magento2/assets/60198592/578132dd-d40c-4ec1-91c1-daf1e5ad52f9">

On UI when new cards are added successfully.

<img width="1440" alt="38903_2" src="https://github.com/magento/magento2/assets/60198592/4b802707-cadb-426a-b1f1-b4c9d3291a86">

**Comment by engcom-Dash** [comment] 2024-07-23 05:38
Hi @khoimm92 

We have noticed that this issue has not been updated for a long time. Hence we assume this issue is fixed now, so we are closing it. Please feel free to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2024-07-23 05:38 UTC
Labels: Issue: needs update, Reported on 2.4.7-p1
