### ISSUE TITLE
Magento 2.4.4 JS-minification does not work "unexpected token const"

### ISSUE THREAD

**Issue by antonfries** [magento/magento2#35366] opened 2022-04-25 11:41 UTC
### Preconditions (*)
1. Magento 2.4.4

### Steps to reproduce (*)
1. Enable js-minification (Path dev/js/minify_files)
2. Enable production mode
3. Login into admin console, review javascript console for js errors

### Expected result (*)
No javascript errors

### Actual result (*)
![2022-04-25_12h34_52](https://user-images.githubusercontent.com/49792220/165072738-7ba27b33-284b-4b47-b684-ecf4dc039760.png)
![2022-04-25_12h35_03](https://user-images.githubusercontent.com/49792220/165072783-d6314de7-9da8-4214-a6ba-a9237a9f85a7.png)
If enabling dev/js/enable_js_bundling too, toggling menus in backend is not possible anymore (this is, how we discovered the bug):
![2022-04-25_13h39_23](https://user-images.githubusercontent.com/49792220/165081953-4b31c898-6345-4d11-92f8-c15e04812313.png)
---
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by engcom-November** [comment] 2022-04-25 13:30
Hi @antonfries ,
Thank you for reporting and collaboration. However this issue is a duplicate of https://github.com/magento/magento2/issues/35325. We are closing this issue. Please move on to this ticket for latest updates/solutions.
Thank you.

**Closed as completed by engcom-November** 2022-04-25 13:30 UTC
Labels: duplicate, Issue: ready for confirmation, Reported on 2.4.4

**Comment by ssx** [comment] 2022-05-24 13:24
Patch: https://gist.github.com/ssx/275bc6c9674277ed8d26592235f1cc6b

**Comment by writyou** [comment] 2022-06-04 01:14
There is still this problem, the admin menu does not work, in production mode

**Comment by steveberrill** [comment] 2022-07-06 19:38
Same, still error in production

**Comment by kevinvuilleminskazy** [comment] 2022-07-26 00:04
Same for me. patch no working

**Comment by davidduong90** [comment] 2022-09-06 08:08
> Same for me. patch no working

Do you try to upgrade, deploy and flush cache?

**Comment by davidandersson1** [comment] 2022-09-22 13:39
@ssx if you any idea, can you please tell me, how to apply this patch via composer.json??
https://gist.github.com/ssx/275bc6c9674277ed8d26592235f1cc6b

For example, if specific module patch then we can apply like
"extra": {
        "magento-force": "override",
        "composer-exit-on-patch-failure": true,
        "patches": {
            "magento/module-cache-invalidate": {
                "GH 8815: Varnish purge requests can overrun size limit": "patches/composer/github-issue-8815.patch"
            },
        }
    }
    
but here patch we have to apply inside lib directory so not getting me what could be the module name at place of "magento/module-cache-invalidate".

if anybody know, please help!

Thanks,
David

**Comment by writyou** [comment] 2022-09-22 13:52
After magento2.4.5 js is compressed, the production mode, the product cannot be saved, and the cms article cannot be saved

**Comment by antonfries** [comment] 2022-09-22 13:56
> @ssx if you any idea, can you please tell me, how to apply this patch via composer.json?? https://gist.github.com/ssx/275bc6c9674277ed8d26592235f1cc6b
> 
> For example, if specific module patch then we can apply like "extra": { "magento-force": "override", "composer-exit-on-patch-failure": true, "patches": { "magento/module-cache-invalidate": { "GH 8815: Varnish purge requests can overrun size limit": "patches/composer/github-issue-8815.patch" }, } }
> 
> but here patch we have to apply inside lib directory so not getting me what could be the module name at place of "magento/module-cache-invalidate".
> 
> if anybody know, please help!
> 
> Thanks, David

You have to use "magento/magento2-base" - after composer update/install the files getting copied to main directory, if missing

**Comment by davidandersson1** [comment] 2022-09-23 04:44
@antonfries thanks a lot for your reply and it's works perfectly.
