### ISSUE TITLE
Tax/VAT field configuration is not working on multistore Magento2

### ISSUE THREAD

**Issue by mariogobos** [magento/magento2#36100] opened 2022-09-07 05:53 UTC
### Preconditions and environment

- Magento version 2.4.4 
- Multi store version
- Migration from magento 1.7 to magento 2.3

### Steps to reproduce

For example for FR Website in Stores=>Configuration=>Customer=>Customer Configuration=> Name and Adress Options=> Show Tax/VAT Number=> No
Magento write correctly on database under customer_eav_attribute_website, attribute_id 15 (taxvat), website_id 3 (fr), is_required 0

### Expected result

After full cache refresh vat number is not required all works fine.

### Actual result

After full cache refresh vat number is not required but when i create a new customer, try to save old customer without vat or create quote for customer without vat doesn't work magento required vat.

### Triage and priority

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mariogobos** [comment] 2022-09-12 10:17
Hi, is very important to me to resolve the issue... In france and other countries vat is not required. Please help me. Thanks

**Comment by engcom-November** [comment] 2022-09-27 12:10
Hi @mariogobos ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop multi store instance but the issue is not reproducible.
Customer account is getting created as expected in all stores both with and without VAT number - No issue.
![image](https://user-images.githubusercontent.com/60198231/192521353-9265e83f-b9f7-489e-9526-6c01ce53ac44.png)
![image](https://user-images.githubusercontent.com/60198231/192522118-ac4a2267-1b4b-4167-82a0-423975032833.png)
![image](https://user-images.githubusercontent.com/60198231/192522622-3b4b2e03-4dfe-48bd-96d7-50a7da1e1985.png)
Kindly recheck the issue on Magento 2.4-develop instance as it is having latest code base and upcoming 2.4.x release and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-10-13 05:53
Hi @mariogobos ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-10-13 05:53 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.4
