### ISSUE TITLE
Chinese input in tinymce 4

### ISSUE THREAD

**Issue by Consumewithadele** [magento/magento2#24637] opened 2019-09-18 09:06 UTC
### Preconditions (*)

1. Magento CE 2.3.0, 2.3.2 & 2.3-develop
2. Problem exist with this language packs and more:
![image](https://user-images.githubusercontent.com/51680850/65322693-34ea2d00-dbb0-11e9-952c-db048a8353b8.png)

### Steps to reproduce (*)

1. Go to admin and open new product page.
2. Open content tab to see wysiwyg editor.
3. Switch keyboard to Chinese
4. Start type any Chinese text in wysiwyg editor.

### Expected result (*)

1. System autocomplete popup for Chinese should work as expected. 

### Actual result (*)

1. Looks like autocomplete popup for Chinese  looses focus, navigation within autocomplete doesn't work.

Additional notices:
problem caused by
lib/web/mage/adminhtml/wysiwyg/tiny_mce/tinymce4Adapter.js
fixRangeSelection: function (editor) {} . If I comment call of this function, CN input works well.

If I switch wysiwyg to tinymce 3 in magento system configuration, CN input works well.

Additional question.
fixRangeSelection: function (editor) {}
has comment:
        /**
         * Fix range selection placement when typing.  This fixes MAGETWO-84769
         * @param {Object} editor
         */

**Comment by engcom-Charlie** [comment] 2019-09-19 09:39
Hello @Consumewithadele !
We can't reproduce this issue on Magento 2.3.2 & 2.3-develop.

**Manual testing scenario:**

1. Go to admin and open new product page.
2. Open content tab to see wysiwyg editor.
3. Switch keyboard to Chinese
4. Start type any Chinese text in wysiwyg editor.

**Actual result:**
Two Chinese fonts works: 
![image](https://user-images.githubusercontent.com/51680850/65232763-60024d00-dada-11e9-8a94-1dbdf1556061.png)

![image](https://user-images.githubusercontent.com/51680850/65232593-1580d080-dada-11e9-8b54-20a8ff6917bf.png)

So i have to close this issue.
Thanks for your report!

**Comment by Consumewithadele** [comment] 2019-09-20 10:02
Hello, 
Could you share information about bug MAGETWO-84769 ?

Could you check attached video where you can see strange behaviour during CN input ?
[CN_input.mov.zip](https://github.com/magento/magento2/files/3635321/CN_input.mov.zip)

**Comment by engcom-Charlie** [comment] 2019-09-20 11:11
@Consumewithadele After watching your video i tested with another languages and i reproduced this issue. This problem exist with this packs:
![image](https://user-images.githubusercontent.com/51680850/65322693-34ea2d00-dbb0-11e9-952c-db048a8353b8.png)
So excuse me about closing this issue. 
Sorry but i can't share information about MAGETWO-84769.

**Comment by magento-engcom-team** [comment] 2019-09-20 11:14
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20293` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by HirokazuNishi** [comment] 2019-10-21 08:29
It's not only Chinese, but also Japanese.

**Comment by sidolov** [comment] 2019-10-21 14:24
Hi @HirokazuNishi , mentioned issue details: 

**Steps to reproduce:**
1. Insert a widget into the editor
2. Add text with no spaces
3. Insert another widget after text with no spaces

**Example:**
<widget>TEXT<widget>

**Expected result:**
widget gets inserted after the text and text is still editable

**Actual result:**
widget gets inserted before the text and text is no longer editable

**Comment by magento-engcom-team** [comment] 2020-03-12 04:25
Hi @Consumewithadele. Thank you for your report. 
The issue has been fixed in magento/magento2#25454 by @HirokazuNishi in 2.4-develop branch
Related commit(s):
 - [aff78240d43a648953131db03a9e18c588a8711d](https://github.com/magento/magento2/commit/aff78240d43a648953131db03a9e18c588a8711d)
 - [1546434bbb11828c6dd1960f325a01d2125ebdcc](https://github.com/magento/magento2/commit/1546434bbb11828c6dd1960f325a01d2125ebdcc)

The fix will be available with the upcoming 2.4.0 release.

**Closed as completed by magento-engcom-team** 2020-03-12 04:25 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Framework/Wysiwyg, Fixed in 2.4.x, Progress: done
