### ISSUE TITLE
PLP - Total count is not working when it exceeds 10,000

### ISSUE THREAD

**Issue by santhiya-nits** [magento/magento2#37556] opened 2023-05-29 07:58 UTC
### Preconditions and environment

 Magento version **- 2.4.5-P1**

**Path Name**: vendor/magento/module-catalog/Block/Product/ProductList/Toolbar.php
**Function Name**: getTotalNum()

The getTotalNum() function does not fetch more than 10,000 data.

### Steps to reproduce

 Magento version **- 2.4.5-P1**

**Path Name**: vendor/magento/module-catalog/Block/Product/ProductList/Toolbar.php
**Function Name**: getTotalNum()

The getTotalNum() function does not fetch more than 10,000 data.

### Expected result

Fetch the data more than 10,000

### Actual result

If the database contains more than 10,000 records.
It fetches only 10,000 items not more than that.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2023-05-29 09:46
Hello @santhiya-nits,

Thanks for the report and collaboration!

We have tried to reproduce the issue in the 2.4-develop branch but the issue is not reproducible for us. It might be possible the issue got resolved. 

We request you to please try to reproduce it in 2.4-develop and if the issue is reproducible for you then please let us know the proper steps to reproduce the issue.

Thanks

**Comment by santhiya-nits** [comment] 2023-05-29 11:46
Hi,

Step 1: I tried to call the function **getTotalNum**() from the vendor/magento/module-catalog/Block/Product/ProductList/Toolbar.php. It does not return more than 10,000 records.
Note: In my database contain more than 10,000 records

**Comment by MTheProgrammer** [comment] 2023-05-30 04:33
This might help:
https://github.com/magento/magento2/issues/8477#issuecomment-278637744

**Comment by engcom-Hotel** [comment] 2023-05-30 07:18
Hello @santhiya-nits,

Thanks for the reply!

@MTheProgrammer Thanks for that reference!

But it seems this is the expected behavior of Magento in order to maintain the performance of e-commerce. You can also customize the same from the below file:

https://github.com/magento/magento2/blob/567638657fd8709073a116f965909740de52175c/app/code/Magento/CatalogSearch/etc/search_request.xml#L1

Also please go through with the comment below:
https://github.com/magento/magento2/issues/8477#issuecomment-278637744

Thanks

**Comment by engcom-Hotel** [comment] 2023-06-12 11:02
Hello @santhiya-nits,

Have you got a chance to check this comment https://github.com/magento/magento2/issues/37556#issuecomment-1567896153?

Thanks

**Comment by engcom-Hotel** [comment] 2023-06-20 05:57
Hello @santhiya-nits,

We have noticed that this issue has not been updated. 

Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2023-06-20 05:57 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.5-p1

**Comment by santhiya-nits** [comment] 2023-06-20 12:31
Hi,

Based on the comment [#8477](https://github.com/magento/magento2/issues/8477#issuecomment-278637744).
I changed the value from 10,000 to 30,000. still it could not fetch data more than 10,000
