### ISSUE TITLE
after creating account in wallet system error is coming 

### ISSUE THREAD

**Issue by thaknaikshreya** [magento/magento2#34712] opened 2021-11-25 07:39 UTC
### Preconditions (*)

1. platform : ecommerce
2. mode : developer/production
3. magento version : 2.4.2

### Steps to reproduce (*)

1.wallet system > transfer amount to bank >customer sign up > account 
2.my account > account information

### Expected result (*)

1. Thank you for registering with Webkul Store.

2.You got 10 reward points on registration

### Actual result (*)

1. [[Screens
![error](https://user-images.githubusercontent.com/39938703/143399136-70bedbe1-91b0-47b7-a349-a2fbbcdb8de2.PNG)
hots,]([)) logs or [description]](url)
2. Bad request. One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

- [ ]

**Comment by ihor-sviziev** [comment] 2021-11-25 07:52
@thaknaikshreya,
It looks like the issue is coming from some 3rd party extension. Could you try to reproduce the issue on the empty Magento installation?

**Comment by engcom-Delta** [comment] 2021-12-09 10:55
We have noticed that this issue has not been updated for a period of 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh  ticket or reopen this ticket if you need more assistance on this.

**Closed as completed by engcom-Delta** 2021-12-09 10:55 UTC
Labels: Issue: needs update
