### ISSUE TITLE
[UI] The dropdown state doesn't change if the dropdown is expanded or not

### ISSUE THREAD

**Issue by eduard13** [magento/magento2#21196] opened 2019-02-13 16:02 UTC
### Preconditions (*)

1. Magento 2.3-develop, Magento 2.2-develop
2.

### Steps to reproduce (*)

1. Make sure you have several categories
2. Go to Admin panel
3. Open a Product Page
4. Expand the **Categories** field
5. Click on the Category icon to expand/unexpand
![xnip2019-02-13_18-05-00](https://user-images.githubusercontent.com/15868188/52725490-fe18bc80-2fb9-11e9-934a-c8d3a3b0f16e.jpg)

### Expected result (*)

1. The icon should be changed 

### Actual result (*)

1. The icon stays in the same state as it was
![xnip2019-02-13_18-07-30](https://user-images.githubusercontent.com/15868188/52725638-4637df00-2fba-11e9-8982-ec7ddf604e7a.jpg)

**Comment by magento-engcom-team** [comment] 2019-02-13 16:02
Hi @eduard13. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@eduard13 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-02-13 16:09
Hi @dmytro-ch. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-02-13 16:15
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98252`, `MAGETWO-98253` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by amol2jcommerce** [comment] 2019-02-14 04:24
* @magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-14 04:24
Hi @amol2jcommerce. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-14 04:24
Hi @amol2jcommerce, here is your [Magento instance](https://i-21196-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21196-2-2-develop.instances.magento-community.engineering/admin](https://i-21196-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-02-18 19:20
Hi @eduard13. Thank you for your report. 
The issue has been fixed in magento/magento2#21197 by @eduard13 in 2.3-develop branch
Related commit(s):
 - [90f6ad53585fb87aefd3b0fecf32fb03a9a3caef](https://github.com/magento/magento2/commit/90f6ad53585fb87aefd3b0fecf32fb03a9a3caef)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-02-18 19:20 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Progress: PR Created, Component: Ui

**Comment by magento-engcom-team** [comment] 2019-02-19 17:25
Hi @eduard13. Thank you for your report. 
The issue has been fixed in magento/magento2#21320 by @eduard13 in 2.2-develop branch
Related commit(s):
 - [1e4055d7e734be1cf69312a40147a68c5183e1bc](https://github.com/magento/magento2/commit/1e4055d7e734be1cf69312a40147a68c5183e1bc)

The fix will be available with the upcoming 2.2.9 release.
