### ISSUE TITLE
Region select field won't load in registration page

### ISSUE THREAD

**Issue by ghost** [magento/magento2#32128] opened 2021-02-12 06:39 UTC
### Preconditions (*)

1. Version 2.4.0

### Steps to reproduce (*)

1. Enable address fields in registration page using xml

File: customer_account_create.xml
```
<referenceBlock name="customer_form_register">
   <action method="setShowAddressFields">
       <argument name="show.address.fields" xsi:type="boolean">true</argument>
   </action>
</referenceBlock>
```
 

### Expected result (*)

1. Region select field load with options:
![expected](https://user-images.githubusercontent.com/1442836/107736654-5dad1e00-6ce1-11eb-9494-34caa7b06cdd.png)

### Actual result (*)

1. Region select field won't load:
![result](https://user-images.githubusercontent.com/1442836/107736748-8fbe8000-6ce1-11eb-82d5-2d67be912a00.png)

2. Chrome console ERROR:
Uncaught SyntaxError: Unexpected token $ in JSON at position 308
    at JSON.parse (<anonymous>)
    at getNodeData (scripts.js:87)
    at Array.map (<anonymous>)
    at scripts.js:117
    at apply (main.js:77)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2021-02-12 08:52
Hello @labofidea 

Thank you for your report.

This is actually a Duplicate of #30099 and there is already a created Pull Request fixing the issue https://github.com/magento/magento2/pull/31755

Please follow the updates on the PR.

We are closing this issue as Duplicate. Please feel free to comment or create a new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thank you.

**Closed as completed by engcom-Bravo** 2021-02-12 08:52 UTC
Labels: Issue: ready for confirmation, not-confirmed
