### ISSUE TITLE
Error deleting custom drop down options when more than 20

### ISSUE THREAD

**Issue by woakley** [magento/magento2#6711] opened 2016-09-22 16:05 UTC
Magento 2.1.1
### Steps to reproduce

Save a product with more than 20 custom options (so pagination of options occurs)
Reload product
Delete an option in the first 20 (on the first page)
### Expected result

Option should be deleted
### Actual result

Option appears to have been deleted and a blank option appears at the end of the first page (as 20th option)

The blank options that appear cannot be deleted and you cannot save the page as Title is a required field.

If you then go to the 2nd page of options and then back to the first page, the option that was deleted has been restored.

If you view the 2nd page of options before attempting to delete then the option is deleted as expected.

It's as if the 2nd page of options doesn't even exist until you view it? Are the remaining options loaded asynchronously?

**Comment by miakusha** [comment] 2016-09-26 12:42
Hi @woakley , thanks for report
We've created internal ticket MAGETWO-58956 to address this issue.

**Comment by kita85** [comment] 2017-01-11 17:38
Same thing is happening to me.

**Comment by PieterCappelle** [comment] 2017-04-04 06:53
Solutions or quick fix is to go through every page from every custom option. Than you can save the product without errors.

**Comment by magento-engcom-team** [comment] 2017-10-12 10:31
@woakley, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-12 10:31 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid

**Comment by PieterCappelle** [comment] 2017-10-12 10:44
@magento-engcom-team Which commit? Would need backport to 2.1 definitely.
