### ISSUE TITLE
Unable to add full description during product creation with page builder enabled

### ISSUE THREAD

**Issue by engcom-November** [magento/magento2#36188] opened 2022-09-23 11:34 UTC
### Preconditions and environment

2.4-develop
Page builder enabled

### Steps to reproduce

1. Login to admin and create new product
2. Expand Content - Full Description - Edit with Page builder
3. Drag and Drop any Layouts.  

### Expected result

Able to add the content

### Actual result

Unable to drag and drop any of the pagebuilder layouts and add content

https://user-images.githubusercontent.com/51680745/192518349-a9bd10bf-e4a1-487b-857f-bd92de3ecfef.mov

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-09-23 11:42
Hi @engcom-November,


Thank you for reporting and collaboration.Verified the issue on Magento 2.4-develop branch and the issue is reproducible.


Thanks.

**Comment by konarshankar07** [comment] 2022-09-30 07:04
@magento I am working on this

**Comment by engcom-November** [comment] 2022-10-03 07:05
@magento give me 2.4-develop instance

**Comment by hostep** [comment] 2022-10-13 19:42
@engcom-Bravo: what was the reason for closing this? Please always specify a reason when closing issues in the future, otherwise it's confusing the people who watch the ticket.

/cc @sdzhepa (this closing of issues without specifying a reason happens way too often over here, please talk to all people that do this so it no longer happens, thanks!)

**Comment by AshishKumarPundeer** [comment] 2022-10-26 12:59
@magento give me 2.4-develop instance

**Comment by AshishKumarPundeer** [comment] 2022-10-27 09:33
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-10-28 07:56
@magento give me 2.4-develop instance

**Comment by AshishKumarPundeer** [comment] 2022-10-28 14:14
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment] 2022-10-31 07:19
As @AshishKumarPundeer and other internal team
    - tried to reproduce in the `2.4-develop` Magento instance (Installed via Git clone), the issue is not reproducible at all.
    - tried to reproduce in the internal Magento cloud instance with the version `2.4.5`.
Only it is reproducible with the instance that is deployed via Github bot's `2.4-develop` instance.

We will not be able to debug as we don't have issue reproducible in our local instance and Github cloud instance code base doesn't support to install in our local.
On which note, it clarifies that, due to some of the internal installation procedures, we might be getting this issue!
Let's this set to `P3` as of now, and re pick up in case of more relevant observation found from different users!
Thanks!
cc: @engcom-Hotel @engcom-Bravo

**Comment by engcom-Bravo** [comment] 2024-08-09 07:05
Hi,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.We are able to drag the drop the elements like Row and Columns and able to add the content.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-08-09 07:05 UTC
Labels: Reproduced on 2.4.x, Priority: P3, Progress: done, Component: PageBuilder, Issue: needs update, Reported on 2.4.x, Area: Admin UI
