### ISSUE TITLE
Excess value in form field

### ISSUE THREAD

**Issue by Vladwww2015** [magento/magento2#14955] opened 2018-05-03 08:45 UTC
**Excess value in form field**
Magento\Bundle\Block\Adminhtml\Catalog\Product\Edit\Tab\Attributes\Extend -> getExtendedElement

### Preconditions

1. 2.2.1

### Steps to reproduce

![download](https://user-images.githubusercontent.com/20088319/39567263-19a062de-4ec7-11e8-93b2-73f836a39a89.jpeg)

**Comment by ArjenMiedema** [comment] 2018-05-03 09:43
I just checked the file in the Github repository in all branches and the issue is only available in the 2.0 branch. Since this is no longer developed, I don't know if this is something that needs to be solved. You mentioned the issue was there in 2.2.1, but it's not there anymore in a 2.2.x version after that, so maybe upgrading is the best thing you can do here.

You can check if yourself via these URLs:
* https://github.com/magento/magento2/blob/2.0/app/code/Magento/Bundle/Block/Adminhtml/Catalog/Product/Edit/Tab/Attributes/Extend.php
* https://github.com/magento/magento2/blob/2.1-develop/app/code/Magento/Bundle/Block/Adminhtml/Catalog/Product/Edit/Tab/Attributes/Extend.php
* https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Bundle/Block/Adminhtml/Catalog/Product/Edit/Tab/Attributes/Extend.php
* https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Bundle/Block/Adminhtml/Catalog/Product/Edit/Tab/Attributes/Extend.php

**Comment by ishakhsuvarov** [comment] 2018-05-26 07:47
Thank you for pointing out @ArjenMiedema 
I am closing this now per your comment.

**Closed as completed by ishakhsuvarov** 2018-05-26 07:47 UTC
Labels: up for grabs, Issue: Format is not valid
