### ISSUE TITLE
More options for language and currencies

### ISSUE THREAD

**Issue by bubach** [magento/magento2#1161] opened 2015-04-02 09:19 UTC
Need lots more features regarding languages and currencies between stores/shops. Right now you can be forced to duplicate whole translations and massive duplication for url-redirects based on language if you want to support the same language but inside different websites.  Also using USD/EUR/GBP with the same english translation can be a pain if you set up the websites/shops in certain ways.

**Comment by piotrekkaminski** [comment] 2015-08-13 21:57
I understand the problem of translations but can you @bubach provide more details/example for the claim related to currencies?

**Comment by FiveDigital** [comment] 2015-08-14 13:37
I think the problem ist that you have to setup a specific website for each currency when you dont't want to work with currency conversion. We once had a customer with this requirement, too an weren't able to realize this setup with Magento.

**Comment by piotrekkaminski** [comment] 2016-08-29 15:28
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/More-options-for-language-and-currencies/idi-p/45842).

**Closed by piotrekkaminski** 2016-08-29 15:28 UTC
Labels: feature request, moved_to_forums, PROD
