### ISSUE TITLE
Upgrade from 2.4.3-p1 to 2.4.3-p2 throws error Magento\Framework\Indexer\IndexMutexInterface not found running compile

### ISSUE THREAD

**Issue by JelleGe** [magento/magento2#35308] opened 2022-04-14 09:18 UTC
### Preconditions (*)
1. Magento 2.4.3-p1
2. PHP 7.4.163. 
3. Composer version 2.2.12
4. Development mode

### Steps to reproduce (*)
1. Followed all the steps from the Upgrade Commerce Guide (https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html) to upgrade from 2.4.3-p1 to 2.4.3-p2.
2. Run bin/magento setup:upgrade for the second time to be sure3. 
3. Run the compile command php bin/magento setup:di:compile and fetch the error on step 1/9 of compile.

### Expected result (*)
1. Successfully upgrade to 2.4.3-p2 and run the compile to set it back to production mode.

### Actual result (*)
1. We fetch an error on step 1/9 after running the php bin/magento setup:di:compile command. The error we get is `Interface 'Magento\Framework\Indexer\IndexMutexInterface' not found`. The entire error is:

`Repositories code generation... 1/9 [===>------------------------]  11% < 1 sec 112.0 MiBInterface 'Magento\Framework\Indexer\IndexMutexInterface' not found#0 /vendor/composer/ClassLoader.php(571): include()
#1 /vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Magento\\Indexer...')
#3 [internal function]: spl_autoload_call('Magento\\Indexer...')
#4 /setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists('Magento\\Indexer...')
#5 /setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass('Magento\\Indexer...', '/...')
#6 /setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract(Object(RecursiveIteratorIterator))
#7 /setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php(61): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList('/...')
#8 /setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation()
#9 /setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(216): Magento\Setup\Module\Di\App\Task\Manager->process(Object(Closure), Object(Closure))
#10 /vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DiCompileCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\DiCompileCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /bin/magento(23): Symfony\Component\Console\Application->run()
#16 {main}`

2. We can also not successfully complete the indexer:reindex command well. We fetch an error with the Category Products index. The error is Class Magento\Catalog\Model\Indexer\Category\Product\Interceptor does not exist

**Comment by achatpc** [comment] 2022-04-23 05:35
same issue on my side

**Comment by achatpc** [comment] 2022-04-23 08:30
hi,

I have to delete file: /vendor/magento/module-indexer/Model/IndexMutex.php
After, working...

**Comment by JelleGe** [comment] 2022-04-23 08:34
@achatpc Hmm, after that everything works well?

**Comment by achatpc** [comment] 2022-04-23 08:44
Yes, i you compare with magento source code 2.4.4 or 2.4.3-p2, this file dont exist.

**Comment by JelleGe** [comment] 2022-04-30 09:24
@achatpc When running a full index, we still get the following error, even after deleting the file: **Class Magento\Catalog\Model\Indexer\Category\Product\Interceptor does not exist**

How did you solve that?

**Comment by achatpc** [comment] 2022-04-30 10:50
> @achatpc Did you only delete that file? It does not work on our side, still the same issue.
> 
> When running a full index, we still get the following error, even after deleting the file: **Category Products index process error during indexation process: Class Magento\Catalog\Model\Indexer\Category\Product\Interceptor does not exist**
> 
> How did you solve that?

Try to setup:upgrade after flush all caches. Remember to flush opcache if you use it.

**Comment by JelleGe** [comment] 2022-04-30 10:56
@achatpc Thanks! That's what we already tried. We flushed all caches, run setup:upgrade (without issues). But sadly we still face the same issue running compile. **Class Magento\Framework\Indexer\IndexMutexInterface does not exist**

**Comment by JelleGe** [comment] 2022-04-30 11:50
Problem seems to be related to patch MDVA-4050_2.4.2-p1.patch all these changes should be revert. But it's sad to see that a upgrade from 2.4.3-p1 to 2.4.3-p2 is causing this issue

**Comment by engcom-November** [comment] 2022-06-15 11:41
Hi @JelleGe ,
Thank you for reporting and collaboration. Verified the issue by upgrading from 2.4.3-P1 Project community edition to 2.4.3-P2 but could not able to reproduce the issue.
For the error: "Category Products index process error during indexation process: Class Magento\Catalog\Model\Indexer\Category\Product\Interceptor does not exist" - please check your Apache/Nginx configuration and ownership and set permissions for your Magento folders and then after giving permission run indexer command :
> php bin/magento indexer:reindex
[Ref docs](https://devdocs.magento.com/guides/v2.4/install-gde/prereq/file-sys-perms-over.html)
https://devdocs.magento.com/guides/v2.4/config-guide/prod/prod_file-sys-perms.html
Kindly recheck and elaborate missing steps or any 3rd party extensions/modules is causing the issue.
Thank you.

**Comment by engcom-November** [comment] 2022-06-29 11:01
Hi @JelleGe 
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-06-29 11:01 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update

**Comment by shakil-codilar** [comment] 2023-01-05 18:56
@magento give me 2.4.3 magento instance

**Comment by shakil-codilar** [comment] 2023-01-05 18:58
Hi @magento provide me magento 2.4 instance

**Comment by shakil-codilar** [comment] 2023-01-05 18:59
@magento give me 2.4 -magento instance

**Comment by ingmarnet** [comment] 2023-05-17 14:32
I'm still facing the issue at 2.4.3-p3 con Commerce Edition.
