### ISSUE TITLE
Running setup:config:set can crash in certain situations, seems to be bug introduced in Magento 2.4.1

### ISSUE THREAD

**Issue by hostep** [magento/magento2#37409] opened 2023-04-21 11:51 UTC
### Preconditions and environment

- Magento version: 2.4.1-2.4.6, also current `2.4-develop` is impacted

### Steps to reproduce

1. Setup clean Magento and fully install it
2. Open the file `app/etc/env.php` and search for the correct db username in the `db/connection/default/username` path
3. Change the `app/etc/env.php` file and change the `db/connection/default/username` to a non-existing database user (using `wrong-user` in example below)
4. Run `bin/magento setup:config:set -n --db-user=xxx` (where you replace `xxx` with the correct database user you found in step 2)
5. Inspect the `app/etc/env.php` file afterwards to see if the username got updated correctly

### Expected result

```
$ bin/magento setup:config:set -n --db-user=xxx
We saved default values for these options: amqp-host, amqp-port, amqp-user, amqp-password, amqp-virtualhost, amqp-ssl, amqp-ssl-options, db-ssl-key, db-ssl-cert, db-ssl-ca, db-ssl-verify, allow-parallel-generation.

$ echo $?
0

$ grep 'username' app/etc/env.php
                'username' => 'xxx',
```

### Actual result

```
$ bin/magento setup:config:set -n --db-user=xxx
We saved default values for these options: amqp-host, amqp-port, amqp-user, amqp-password, amqp-virtualhost, amqp-ssl, amqp-ssl-options, db-ssl-key, db-ssl-cert, db-ssl-ca, db-ssl-verify, allow-parallel-generation.

In Abstract.php line 144:

  SQLSTATE[HY000] [1045] Access denied for user 'wrong-user'@'localhost' (using password: YES)


In Abstract.php line 128:

  SQLSTATE[HY000] [1045] Access denied for user 'wrong-user'@'localhost' (using password: YES)


$ echo $?
255

$ grep 'username' app/etc/env.php
                'username' => 'xxx',
```

### Additional information

We have a certain workflow where we expect to have a wrong db user in the `app/etc/env.php` file and expect it to be able to change it without errors using `bin/magento setup:config:set`

This used to work before Magento 2.4.1, but seems to have been broken ever since Magento 2.4.1, which is kind of annoying for us.

It looks like the config change does work in that command, but the updated configuration isn't being reloaded before it tries to do whatever it crashes on a bit later.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment] 2023-04-21 13:22
After a git bisecting session, it seems like the issue was introduced by commit: ec098d26e7735528beb8ef338b1eeb25eab3a1a1, now to figure out why exactly ...

**Comment by hostep** [comment] 2023-04-21 13:46
Okay, it has something to do with the class `Magento\MediaContentSynchronizationApi\Model\SynchronizerPool`.
It gets included through `Magento\MediaContentSynchronization\Console\Command\Synchronize` which includes `Magento\MediaContentSynchronizationApi\Api\SynchronizeInterface` which then includes `Magento\MediaContentSynchronizationApi\Model\SynchronizerPool`

Injecting a proxy of the `SynchronizeInterface` class into the console command using the `di.xml` file solves the issue after some quick testing:

```diff
diff --git a/app/code/Magento/MediaContentSynchronization/etc/di.xml b/app/code/Magento/MediaContentSynchronization/etc/di.xml
index d4615c15206..100f364b305 100644
--- a/app/code/Magento/MediaContentSynchronization/etc/di.xml
+++ b/app/code/Magento/MediaContentSynchronization/etc/di.xml
@@ -14,6 +14,11 @@
             </argument>
         </arguments>
     </type>
+    <type name="Magento\MediaContentSynchronization\Console\Command\Synchronize">
+        <arguments>
+            <argument name="synchronizeContent" xsi:type="object">Magento\MediaContentSynchronizationApi\Api\SynchronizeInterface\Proxy</argument>
+        </arguments>
+    </type>
     <type name="Magento\MediaGallerySynchronization\Model\Consume">
         <plugin name="synchronize_media_content"
                 type="Magento\MediaContentSynchronization\Plugin\SynchronizeMediaContent"/>
```

**Comment by hostep** [comment] 2023-04-21 14:06
Okay, it was due to yet another command to have been added that has the same problem.
A full fix for the `2.4-develop` branch is like so:

```diff
diff --git a/app/code/Magento/MediaContentSynchronization/etc/di.xml b/app/code/Magento/MediaContentSynchronization/etc/di.xml
index e5347f1a115..ed096340e70 100644
--- a/app/code/Magento/MediaContentSynchronization/etc/di.xml
+++ b/app/code/Magento/MediaContentSynchronization/etc/di.xml
@@ -15,6 +15,11 @@
             </argument>
         </arguments>
     </type>
+    <type name="Magento\MediaContentSynchronization\Console\Command\Synchronize">
+        <arguments>
+            <argument name="synchronizeContent" xsi:type="object">Magento\MediaContentSynchronizationApi\Api\SynchronizeInterface\Proxy</argument>
+        </arguments>
+    </type>
     <type name="Magento\MediaGallerySynchronization\Model\Consume">
         <plugin name="synchronize_media_content"
                 type="Magento\MediaContentSynchronization\Plugin\SynchronizeMediaContent"/>
diff --git a/app/code/Magento/MediaGallerySynchronization/etc/di.xml b/app/code/Magento/MediaGallerySynchronization/etc/di.xml
index 82bd1303eda..2d793825b89 100644
--- a/app/code/Magento/MediaGallerySynchronization/etc/di.xml
+++ b/app/code/Magento/MediaGallerySynchronization/etc/di.xml
@@ -47,6 +47,11 @@
             </argument>
         </arguments>
     </type>
+    <type name="Magento\MediaGallerySynchronization\Console\Command\Synchronize">
+        <arguments>
+            <argument name="synchronizeAssets" xsi:type="object">Magento\MediaGallerySynchronizationApi\Api\SynchronizeInterface\Proxy</argument>
+        </arguments>
+    </type>
     <type name="Magento\Framework\App\Config\Value">
         <plugin name="admin_system_config_adobe_stock_save_plugin" type="Magento\MediaGallerySynchronization\Plugin\MediaGallerySyncTrigger"/>
     </type>
```

I'll see if I can find some time next week for a PR ...

**Comment by engcom-November** [comment] 2023-04-27 06:11
Hi  @hostep 
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance with below steps followed and the issue is reproducible. Hence confirming the issue.
**Steps performed:**
1. Updated DB username in app/etc/env.php file with wrong user name manually. Ex: 'xxxy'
2. Run the command from cli with correct DB user name: `php bin/magento setup:config:set -n --db-user=global`
**Issue:**  SQLSTATE[HY000] [1698] Access denied for user 'xxxy'@'localhost' error message is displayed.
![image](https://user-images.githubusercontent.com/60198231/234774688-1b0110fe-c9f7-4a74-a6e0-d7120e3df122.png)

3. Run the below command again from cli with correct DB user name : `php bin/magento setup:config:set -n --db-user='global'`
**No issue:** No error displayed
![image](https://user-images.githubusercontent.com/60198231/234774617-783e5a1c-c27d-4c53-8bf8-5a8683d2c415.png)

4. Inspect env.php file again and check the db username - **Issue: Value is not updated**
![image](https://user-images.githubusercontent.com/60198231/234774538-b584a8ac-d322-446d-b5d5-fa208565acbc.png)

**Comment by ihor-sviziev** [comment] 2023-07-17 09:36
The issue was fixed in https://github.com/magento/magento2/commit/4095595b63a7ce48a7d3a6302395ff75478d3284 (changes from https://github.com/magento/magento2/pull/37424).
I'm closing this issue

**Closed as completed by ihor-sviziev** 2023-07-17 09:36 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Framework, Reported on 2.4.6
