### ISSUE TITLE
User not able to save the Visibility attribute with the option other than the Catalog, Search

### ISSUE THREAD

**Issue by sanketkk** [magento/magento2#38932] opened 2024-07-15 06:38 UTC
### Preconditions and environment

- Magento version 2.4.7 enterprise-edition

### Steps to reproduce

1.Login to Magento Admin with valid credentials.
2.Click on Stores>Under Attributes select Product
3.Search for the Attribute visibility
4.Under Manage options select the Not Visible Individually option and Save

### Expected result

User should be able to save the Visibility attribute with all the options

### Actual result

User not able to save the Visibility attribute with the option other than the Catalog, Search

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-07-17 07:18
Hi @sanketkk,

Thanks for your reporting and collaboration.

We have tried to reproduce the issue in Latest 2.4-develop with EE edition we are not able to proceed further.Could you please provide more information about the visibility and also provide screenshots.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-07-29 06:39
Hi @sanketkk,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-29 06:39 UTC
Labels: Issue: needs update, Reported on 2.4.7
