### ISSUE TITLE
2.4.2 A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.

### ISSUE THREAD

**Issue by joemstar** [magento/magento2#32231] opened 2021-02-19 17:53 UTC
### Preconditions (*)

1. Magento 2.4.2
2. MariaDb 10.4
3. php 7.4

### Steps to reproduce (*)

1. Upgrade from 2.4.1 to 2.4.2
2. Click "Insert Image" in my theme to Open image uploader and select an image to upload. Click "Add Selected"
3. This problem did not exist prior to upgrading.

### Expected result (*)

1. The image uploads

### Actual result (*)

1. I get this error: "A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later."

**Comment by engcom-Delta** [comment] 2021-02-22 15:24
Hi @joemstar thank you for your report. I'm not able to reproduce issue by steps you described on clean 2.4-develop and 2.4.2
**Manual testing scenario:**
- Install magento 2.4.1
- Upgrade to version 2.4.2
- Go to Catalog->Categories
- Click Insert/Edit Image icon in Content->Description(via wisiwyg)
- :heavy_check_mark: Image is successfully uploaded
- Click Content->Category Image->Upload button
- Choose image
:heavy_check_mark: Image is successfully uploaded
- Click Content->Category Image->Select from Gallery
- Select image
- Click Add Selected

**Result:**
:heavy_check_mark: Image is shown in Category Image
![Screenshot from 2021-02-22 17-19-57](https://user-images.githubusercontent.com/51681379/108728522-5af8c700-7532-11eb-9fe2-8fb25396ab4e.png)

Could you clarify on what page image uploading was failed?

**Comment by joemstar** [comment] 2021-02-22 15:42
I just tried your exact steps in my environment and it also worked without a problem. I am having the issue uploading to the brands page which is an extension provided by the company who made my theme. I will reach out to them to troubleshoot further. Thank you for your time.

**Comment by engcom-Delta** [comment] 2021-02-23 07:53
@joemstar seems like this related to your extension and we close this issue.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on clean `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Delta** 2021-02-23 07:53 UTC
Labels: Issue: needs update, not-confirmed

**Comment by st3phani** [comment] 2022-02-04 21:44
> ### Preconditions (*)
> 1. Magento 2.4.2
> 2. MariaDb 10.4
> 3. php 7.4
> 
> ### Steps to reproduce (*)
> 1. Upgrade from 2.4.1 to 2.4.2
> 2. Click "Insert Image" in my theme to Open image uploader and select an image to upload. Click "Add Selected"
> 3. This problem did not exist prior to upgrading.
> 
> ### Expected result (*)
> 1. The image uploads
> 
> ### Actual result (*)
> 1. I get this error: "A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later."

I have same error message in Magento Enterprise 2.4.2, when I want to change a product price.
