### ISSUE TITLE
[UnexpectedValueException] The checksum verification of the file failed (downloaded from https://repo.magento.com/archives/magento/module-braintree/magento-module-braintree-100.0.2.0.zip)  

### ISSUE THREAD

**Issue by cerebrumgit** [magento/magento2#2397] opened 2015-11-17 21:43 UTC
Hello good afternoon

Based on the following article

http://devdocs.magento.com/guides/v2.0/install-gde/prereq/integrator_install.html

I used the following command

composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition

View pictures as the displayed error

---
- Installing magento/module-braintree (100.0.2)
  Downloading: 100%         
  
  [UnexpectedValueException]  
  The checksum verification of the file failed (downloaded from https://repo.magento.com/archives/magento/module-braintree/magento-module-braintree-100.0.2.0.zip)  

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

---

![captura de tela de 2015-11-17 19 41 47](https://cloud.githubusercontent.com/assets/3661079/11225799/61867818-8d63-11e5-9cb0-59d803a3bc90.png)
![captura de tela de 2015-11-17 19 41 51](https://cloud.githubusercontent.com/assets/3661079/11225800/618f8908-8d63-11e5-97d7-fa9f5cbd727c.png)
![captura de tela de 2015-11-17 19 42 21](https://cloud.githubusercontent.com/assets/3661079/11225801/61957818-8d63-11e5-9e53-f6ea3b5dd6ad.png)

**Comment by buskamuza** [comment] 2015-11-17 21:47
Hi @cerebrumgit , could you, please, try to clean composer cache and re-run the command?

**Comment by cerebrumgit** [comment] 2015-11-17 23:07
Thank you, I run the following commands before creating the project and work

**Comment by michalbiarda** [comment] 2015-11-18 12:25
I have the same problem and clearing Composer cache doesn't help. What's more, after clearing cache the error ocurres for different modules. Once it was "magento/module-reports". The other time "magento/module-braintree" and then "magento/module-shipping" (which is downloaded before the previous two!).

**Comment by Madjag** [comment] 2015-11-18 15:32
Hi guys,
i have the same issue and clearing composer cache doesn't help for me too!!

**Comment by buskamuza** [comment] 2015-11-18 15:55
Hi all,

can you run the composer command with `-vvv` option and provide the output?
Also, could you, please, tell what size of zip files do you have, when it fails (if Composer preserves it in the cache). The zips can be found in `<composer_home>/cache/files/magento/<package>/`. `<composer_home>` is usually `~/.composer`.
Also which OS do you use for the installation?

**Comment by michalbiarda** [comment] 2015-11-18 16:22
I'm using Ubuntu server 14.04.3.
After fail the cache folder for problemaic package is empty (no ZIP file at all).
The output with `-vvv`:

```
  - Installing magento/module-sales (100.0.2)
Downloading https://repo.magento.com/archives/magento/module-sales/magento-module-sales-100.0.2.0.zip
    Downloading: 100%
Writing /home/mbiarda/.composer/cache/files/magento/module-sales/100.0.2.0-.zip into cache from /var/www/mage2/vendor/magento/module-sales/24377a5eee64cd6cdca091acab57420a.zip

Failed: [UnexpectedValueException] 0: The checksum verification of the file failed (downloaded from https://repo.magento.com/archives/magento/module-sales/magento-module-sales-100.0.2.0.zip)
Reading ./composer.json
Loading config file /home/mbiarda/.composer/config.json
Loading config file /home/mbiarda/.composer/auth.json
Loading config file ./composer.json
Failed to initialize global composer: Composer could not find the config file: /home/mbiarda/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section



  [UnexpectedValueException]
  The checksum verification of the file failed (downloaded from https://repo.magento.com/archives/magento/module-sales/magento-module-sales-100.0.2.0.zip)



Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Downloader/FileDownloader.php:163
 Composer\Downloader\FileDownloader->doDownload() at phar:///usr/local/bin/composer/src/Composer/Downloader/FileDownloader.php:88
 Composer\Downloader\FileDownloader->download() at phar:///usr/local/bin/composer/src/Composer/Downloader/ArchiveDownloader.php:35
 Composer\Downloader\ArchiveDownloader->download() at phar:///usr/local/bin/composer/src/Composer/Downloader/DownloadManager.php:199
 Composer\Downloader\DownloadManager->download() at phar:///usr/local/bin/composer/src/Composer/Installer/LibraryInstaller.php:159
 Composer\Installer\LibraryInstaller->installCode() at phar:///usr/local/bin/composer/src/Composer/Installer/LibraryInstaller.php:90
 Composer\Installer\LibraryInstaller->install() at /var/www/mage2/vendor/magento/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Installer.php:407
 MagentoHackathon\Composer\Magento\Installer->install() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:152
 Composer\Installer\InstallationManager->install() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:139
 Composer\Installer\InstallationManager->execute() at phar:///usr/local/bin/composer/src/Composer/Installer.php:603
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:232
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php:172
 Composer\Command\CreateProjectCommand->installProject() at phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php:130
 Composer\Command\CreateProjectCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:838
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:189
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:163
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:98
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:25
```

**Comment by buskamuza** [comment] 2015-11-18 21:32
@michalbiarda , thanks for the report.
Just in case, do you have the latest version of Composer?

Our suspicion for now is that the package is modified on the way from the repo server to Composer.
1. Are you in some corp or other network that can scan/modify incoming files?
2. Do you have anti-virus installed? Can it modify incoming files?
3. Do you know about any proxies on the way to your machine?
4. If you try old version of Magento (e.g., 2.0.0-rc2), does it have the same issue? It uses different repository with open access (http://packages.magento.com).
5. Can you, please, look at `~/.composer/cache/repo/https---repo.magento.com/packages.json` and see what is `shasum` for `magento-module-sales-100.0.2.0.zip`?

UPD: for question 4, don't specify `repository-url`, it should take it from default - packagist.org

**Comment by michalbiarda** [comment] 2015-11-19 13:29
Ad 0. Yes, I updated it just before installation.
Ad 1. No, I'm not.
Ad 2. It's almost clean development only Ubuntu, so I have nothing like that.
Ad 3. The Ubuntu lays in Virtualbox. Windows 8.1 is a host machine.
Ad 4. I tried `composer create-project magento/project-community-edition /var/www/mage2 2.0.0-rc2` after clearing cache and it also failed. This time on `magento_framework-100.0.1.zip`.
Ad 5. It's "ba33b4565dc8fb07199faacb2d2d5534bc89618c".

Please have in mind that the problem ocurres always with different file - some of them were OK in previous tries.

**Comment by willi13** [comment] 2016-02-03 17:50
Hi All,
did anybody solve this problem in the meantime? I'm trying to download/install magento 2.0.2 now since a few days on different devices, stand alone server setups on Ubuntu 15.10, (no emulation software nor Vagrant) without success. I always get -sooner or later- the "checksum verificaton error" after a varying number of loaded files. In addition, the loading is extremly slow. It takes minutes for one file, would be  hours for the complete packages. Clearing composer cache does not help. It's exactly like cerebrumgit  mentioned. "Composer diagnose" says: everthing ok.
Any new ideas and/or suggestions on this topic?

**Comment by michalbiarda** [comment] 2016-02-08 12:33
Hi,

The problem retured for me as well while trying to update to 2.0.2.

```
Analyzed 93231 rules to resolve dependencies
  - Installing magento/magento2-base (2.0.2)
Downloading https://repo.magento.com/archives/magento/magento2-base/magento-magento2-base-2.0.2.0.zip
    Downloading: 100%
Writing /home/mbiarda/.composer/cache/files/magento/magento2-base/2.0.2.0-.zip into cache from /var/www/mage2/vendor/magento/magento2-base/78632bd43bd6be2a964ef5f6e6181ce4.zip

Failed: [UnexpectedValueException] 0: The checksum verification of the file failed (downloaded from https://repo.magento.com/archives/magento/magento2-base/magento-magento2-base-2.0.2.0.zip)



  [UnexpectedValueException]
  The checksum verification of the file failed (downloaded from https://repo.magento.com/archives/magento/magento2-base/magento-magento2-base-2.0.2.0.zip)



Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Downloader/FileDownloader.php:163
 Composer\Downloader\FileDownloader->doDownload() at phar:///usr/local/bin/composer/src/Composer/Downloader/FileDownloader.php:88
 Composer\Downloader\FileDownloader->download() at phar:///usr/local/bin/composer/src/Composer/Downloader/ArchiveDownloader.php:35
 Composer\Downloader\ArchiveDownloader->download() at phar:///usr/local/bin/composer/src/Composer/Downloader/DownloadManager.php:199
 Composer\Downloader\DownloadManager->download() at phar:///usr/local/bin/composer/src/Composer/Installer/LibraryInstaller.php:175
 Composer\Installer\LibraryInstaller->installCode() at phar:///usr/local/bin/composer/src/Composer/Installer/LibraryInstaller.php:89
 Composer\Installer\LibraryInstaller->install() at /var/www/mage2/vendor/magento/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Installer.php:407
 MagentoHackathon\Composer\Magento\Installer->install() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:152
 Composer\Installer\InstallationManager->install() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:139
 Composer\Installer\InstallationManager->execute() at phar:///usr/local/bin/composer/src/Composer/Installer.php:604
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:232
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:143
 Composer\Command\UpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:841
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:167
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:98
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:25
```

**Comment by rudenko-maksym** [comment] 2016-02-08 18:51
I faced the "The checksum verification of file failed ..." during _composer install_

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty
```

**Comment by michalbiarda** [comment] 2016-02-17 22:38
Guys,

it turned out that for me the issue was related to network configuration in my office. A few of my colleagues that tried to install / update Magento 2 in the office, failed with similar errors. At home, on different network everything went pretty well.

**Comment by rum-neutralo** [comment] 2016-03-20 11:41
Same Problem. I try to install Magento2 with composer in VirtualBox: 
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty

Hostsystem is my MacBook

Workaround for me:
-> Removed the Directory "project-community-edition" several times; 
-> Do not Clear the cache (for faster install)
-> run install command again:
composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition

**Comment by vzabaznov** [comment] 2016-06-22 12:47
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment] 2016-07-14 08:10
Hi, @cerebrumgit thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.

**Closed as completed by vzabaznov** 2016-07-14 08:10 UTC
Labels: Progress: needs update
