### ISSUE TITLE
It is not possible to choose only width or height within the image property in the view.xml

### ISSUE THREAD

**Issue by Alainvdz99** [magento/magento2#31747] opened 2021-01-18 14:13 UTC
### Preconditions (*)

1. Magento version 2.3.6
2. Only add width or height in the image property of the view.xml file, not both

### Steps to reproduce (*)

1. Create a view.xml and add an image tag with id **product_base_image** and type **image** . within this image tag, add a width tag but **not** a height tag
2. Go to the frontend of the Magento shop and go to a PDP

### Expected result (*)

1. Webpage should load in and should show the product images

### Actual result (*)

1. Fatal error: Uncaught TypeError: Argument 2 passed to Magento\Catalog\Block\Product\ImageFactory::getRatio() must be of the type int, null given

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Alainvdz99** [comment] 2021-01-18 14:35
@magento I am working on this

**Comment by Alainvdz99** [comment] 2021-01-18 14:35
@magento add to contributors team

**Comment by Alainvdz99** [comment] 2021-01-18 14:36
@magento I am working on this

**Comment by engcom-Alfa** [comment] 2021-01-19 10:50
Hi @Alainvdz99.
Unfortunately, we are not able to reproduce the issue on fresh 2.4-develop. Everything works as expected.
 Looks like the problem has already been fixed by commit 806b4f9dfa63b5319fa3891c9bab911516b21747.

@Alainvdz99 Could you take a look?
Thanks!

**Comment by gabrieldagama** [comment] 2021-01-19 17:33
@engcom-Alfa If this issue is not reproducible, please also close the PR related to it https://github.com/magento/magento2/pull/31748

Thanks

**Comment by engcom-Alfa** [comment] 2021-02-02 11:11
Hi @Alainvdz99  we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Closed as completed by engcom-Alfa** 2021-02-02 11:11 UTC
Labels: Issue: needs update, not-confirmed, Reported on 2.3.6
