### ISSUE TITLE
Parameters from website configuration isn't applied to the corresponding store view

### ISSUE THREAD

**Issue by staradzinau** [magento/magento2#7943] opened 2016-12-23 06:30 UTC
### Preconditions

1. Install Magento ver. 2.1.3 CE with sample data
2. Set up at least one website with corresponding store and store view (in my case: **Main Website**, **Main Website store** and **Default store view**

### Steps to reproduce

1. Go to admin panel, open **Stores** -> **Settings** -> **Configuration**
2. Set config scope to **Default Config**
3. Go to **Catalog** -> **Catalog** -> **Product Reviews** section
4. Set parameter **Allow Guests to Write Reviews** to "Yes"
5. Change config scope to **Main Website**
6. Set parameter **Allow Guests to Write Reviews** to "No"
7. Navigate to storefront as a guest and open any product page with "Reviews" tab

### Expected result

1. Review submitting is enable for guest user

### Actual result

1. Review submitting is disabled for guest user

Config parameters for the corresponding store view contains default values and have no connection to the website parameters values

**Comment by sevos1984** [comment] 2016-12-23 15:45
Thanks for reporting, internal issue id MAGETWO-62648

**Comment by vishveskrish** [comment] 2016-12-27 05:45
Is there any fix for this issue ?

**Comment by alexstpp** [comment] 2016-12-28 11:34
Fixed here https://github.com/magento/magento2/blob/develop/app/code/Magento/Store/Model/Config/Processor/Fallback.php#L109

**Comment by erikhansen** [comment] 2016-12-28 17:18
I can confirm that changing the `vendor/magento/module-store/Model/Config/Processor/Fallback.php:171` file from 

```
$code = $website['website_id'];
```

to this:

```
$code = $website['code'];
```
fixes the issue for me.

**Comment by ericthehacker** [comment] 2016-12-28 22:24
A corollary of this issue is that, when a config field is overridden at a website level, any children store views which are set to "Use Website" for that field will return the default scope value, instead of the overridden website value.

**Comment by spyrule** [comment] 2016-12-29 05:58
Whats odd for me, is that my Callback.php is completely different than the one posted in the fix. Is the posted fix, mostly changed for dev reasons, because as far as I can tell in the sample fix, the 'code' doesn't actually exist in the stock file.

**Comment by alexstpp** [comment] 2016-12-29 07:04
Fix relevant for Magento 2.1.3

**Comment by korostii** [comment] 2017-01-06 09:14
Is there any chance bugfixes for such common yet simple bugs would get streamlined through frequent (more frequent than once per 6 months) patch version releases? 
For example, a 2.1.3.1 version containing just the fixes to bugs introduced in (supposedly stable) 2.1.3 would do just fine.

The thing is, for a project facing a launch in the next month, waiting half a year(or more? nobody really knows) for the next release, which just might introduce more new bugs than it fixes - is not really an option.
Running on the "develop" branch is obviously no solution neither: by definition, it should be less stable (right?)
That leaves us with trying to produce workarounds of various sorts for the most critical issues in the time given, including extending core methods via di (which reminds me: why would you ever declare a method private? it complicates extensibility and might force to duplicate whole class, as in [this very case](https://github.com/magento/magento2/blob/develop/app/code/Magento/Store/Model/Config/Processor/Fallback.php) there isn't really a way override just the getWebsiteConfig() ) just for the sake of including a one-line bugfix in a clean way.

It is hard to overrate the amounts of time to be potentially saved by something as simple and straightforward as bugfixing the core functionality in timely matter. 
It would also save you from having to process the duplicate issues appearing months after the buggy version get released.
Nevertheless, I am of course grateful of all the work you guys at Magento, Inc. do, I just wish that? organizationally, releasing the patches would improve.

Respectfully, a humble PHP developer.

**Comment by Ctucker9233** [comment] 2017-02-07 23:33
Was the fix included in 2.1.4?

**Comment by spyrule** [comment] 2017-02-08 01:22
Its not listed in the fix list on 2.1.4, so my guess is no.  

edit: I guess I missed it in the notes, ignore my comment.

**Comment by ebaschiera** [comment] 2017-02-08 07:55
I think it is, yes. See https://github.com/magento/magento2/blob/2.1.4/app/code/Magento/Store/Model/Config/Processor/Fallback.php#L174

**Comment by sammarcus** [comment] 2017-02-08 10:35
@Ctucker9233 yes! it's in the release notes 😄

**Comment by spyrule** [comment] 2017-02-10 16:44
@ebaschiera , whats totally weird for me, in my 2.1.3 installation, that file is nearly 100% different than the one in that link, yet that link is indicating a single line of code change. Is that fix for CE or EE ?

**Comment by KrystynaKabannyk** [comment] 2017-03-13 16:53
Closing the issue since it was fixed under MAGETWO-62648 for 2.1.4.

**Closed as completed by KrystynaKabannyk** 2017-03-13 16:53 UTC
Labels: Issue: Ready for Work, bug report
