### ISSUE TITLE
Admin product and category update or save redirect in dashboard

### ISSUE THREAD

**Issue by ansarhusain** [magento/magento2#36932] opened 2023-02-28 09:30 UTC
### Preconditions and environment

- Magento version : 2.4.5

Even i have increased max_input_vars very large size then still i am redirecting in dashboard.

Looks like here invalid form key issue.

### Steps to reproduce

1. Login in back end
2. catalog -> product
3. create new product or edit existing product 
4. update any config in back end then still redirect.

### Expected result

admin any action will redirect in dashboard.

### Actual result

It will redirect in dashboard.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ansarhusain** [comment] 2023-02-28 09:37
Here is exact result of issue

https://www.loom.com/share/cdfe22e328824513a42a428177416150

**Comment by ansarhusain** [comment] 2023-02-28 10:10
@engcom-Bravo please can i get any patches quick as its live site.

**Comment by engcom-Bravo** [comment] 2023-02-28 13:34
Hi @ansarhusain,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.


**Steps to reproduce**

- Login in back end
- catalog -> product
- create new product or edit existing product

We are able to edit and save the product.We are not going to admin dashboard.



https://user-images.githubusercontent.com/51680745/221868858-24aafa4a-7e39-40a7-8cb7-0cad51373811.mov







Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.





Thanks.

**Comment by engcom-Bravo** [comment] 2023-03-13 06:12
HI @ansarhusain,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-03-13 06:12 UTC
Labels: Issue: needs update, Reported on 2.4.5
