### ISSUE TITLE
Magento 2.3.3 doesn't support database ssl connection.

### ISSUE THREAD

**Issue by Jupagar77** [magento/magento2#27061] opened 2020-02-27 19:53 UTC
## Summary of the issue
I am trying to setup a magento instance using an external database server hosted on digital ocean using ssl,  if I try to connect via server console it works:

`mysql -u DIGITALOCEANUSER --host DIGITALOCEANHOST --port 25555 --ssl-mode=REQUIRED -p`

but from magento setup wizard is throwing this error: 

`SQLSTATE[HY000] [2002] No such file or directory`

since I can't configure that "--ssl-mode" flag or well I don't know how, I am using this value on the host:

`DIGITALOCEANHOST:25555/DATABASENAME?ssl-mode=REQUIRED`

I have tried several ways to send that ssl-mode flag but nothing works, it seems magento2 doesn't support ssl database connections.

## Information on your environment
**Magento:** 2.3.3
**PHP:** 7.2.24
**MYSQL:**  5.7.29

## Steps to reproduce
1. Install a clean magento2 project
2. On the database configurations section try to use an external database server using "ssl-mode" REQUIRED:

## Expected result:
The setup finishes properly.

## Actual result:
Getting error: SQLSTATE[HY000] [2002] No such file or directory

**Comment by hostep** [comment] 2020-02-27 20:18
@Jupagar77: please don't use all caps for an issue description, it doesn't look very polite.

Anyways, I'm going to close this as a duplicate of https://github.com/magento/magento2/issues/13561, this issue was fixed in Magento 2.3.4 by 
a [first attempt](https://github.com/magento/magento2/pull/18075) which got declined and then a [follow up attempt](https://github.com/magento/magento2/pull/25398) which was approved.

So upgrading Magento to version 2.3.4 should enable you to connect to mysql with SSL.
See the opening post of https://github.com/magento/magento2/pull/25398 for instructions about how to set it up.

**Closed as completed by hostep** 2020-02-27 20:18 UTC
Labels: Issue: Format is not valid, Triage: Dev.Experience, Reported on 2.3.3

**Comment by Jupagar77** [comment] 2020-02-27 20:59
Sorry about that @hostep, thanks for your fast assistance.
