### ISSUE TITLE
Not all Breadcrumbs are present on the product page if URL includes categories 

### ISSUE THREAD

**Issue by ilnytskyi** [magento/magento2#21011] opened 2019-02-06 09:38 UTC
Breadcrumbs do not work on product page if there is no referer
### Preconditions (*)

Magento 2.2.x
Magento 2.3

There is typo in uiComponent

### Steps to reproduce (*)

1. Open product page using direct link including category path
2. See there is no breadcrumbs just Home -> Product Page

### Expected result (*)

1. All Breadcrumbs are present on the product page

### Actual result (*)

1. Not all Breadcrumbs are present on the product page just Home -> Product Page

**Comment by magento-engcom-team** [comment] 2019-02-06 09:38
Hi @ilnytskyi. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ilnytskyi do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by shikhamis11** [comment] 2019-02-06 16:30
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-06 16:30
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-06 16:31
Hi @shikhamis11, here is your [Magento instance](https://i-21011-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21011-2-3-develop.instances.magento-community.engineering/admin](https://i-21011-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2019-02-06 16:55
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-06 16:55
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-06 16:56
Hi @shikhamis11, here is your [Magento instance](https://i-21011-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21011-2-2-develop.instances.magento-community.engineering/admin](https://i-21011-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2019-02-06 17:25
@ilnytskyi this issue seems present only on magento 2.2 develop instance and already fixed in 2.3-develop

**Comment by magento-engcom-team** [comment] 2019-02-06 17:26
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98130` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by swnsma** [comment] 2019-02-24 15:37
Fixed in #19781.

**Comment by swnsma** [comment] 2019-02-24 15:38
Fixed in 2.2: #19760.

**Closed as completed by swnsma** 2019-02-24 15:38 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Confirmed, Reproduced on 2.2.x, Fixed in 2.2.x, Issue: Format is valid
