### ISSUE TITLE
Elasticsearch attribute filter with pagination issue

### ISSUE THREAD

**Issue by santosh-gaggle** [magento/magento2#27989] opened 2020-04-25 15:52 UTC
**Elasticsearch attribute filter with pagination issue**

### Preconditions (*)
1. Magento 2.4-develop;
2. Sample Data;
2. Elasticsearch 6 +

### Steps to reproduce:

1. Go to Storefront;
2. Go to Men->Tops->Hoodies & Sweatshirts category (for example);
3. Go to the second **2** page;
4. On filter panel choose **black** from **Color** (for example);

**Actual result:**

:heavy_multiplication_x: After applying the filter, the products are not displayed

![Peek 2020-04-30 14-42](https://user-images.githubusercontent.com/51679138/80707947-79995780-8af3-11ea-9250-72dc51b4b2b3.gif)

5. :heavy_check_mark:  When deleting `p=2` from URL path, products are displayed

![Peek 2020-04-30 14-51](https://user-images.githubusercontent.com/51679138/80708017-9e8dca80-8af3-11ea-9af1-a01e882961a2.gif)

**Expected result:**

1. it should show the filtered products.
2.  if I am on the 2th page and  filtered any attribute then it should remove the pagination value from the URL or it should be managed with the product item count
3. after removing the pagination value from the URL  it's showing the 6 number of products

**Comment by santosh-gaggle** [comment] 2020-04-27 11:55
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-27 11:55
Hi @santosh-gaggle. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by engcom-Alfa** [comment] 2020-04-30 12:03
The issue is reproducible on fresh 2.4-develop

_**Preconditions:**_

Sample Data;
Elasticsearch 6+;

**Steps to Reproduce:**
1. Go to Storefront;
2. Go to Men->Tops->Hoodies & Sweatshirts category (for example);
3. Go to the second **2** page;
4. On filter panel choose **black** from **Color** (for example);

**Actual result:**
:heavy_multiplication_x: After applying the filter, the products are not displayed

![Peek 2020-04-30 14-42](https://user-images.githubusercontent.com/51679138/80707947-79995780-8af3-11ea-9250-72dc51b4b2b3.gif)

5. :heavy_check_mark:  When deleting `p=2` from URL path, products are displayed

![Peek 2020-04-30 14-51](https://user-images.githubusercontent.com/51679138/80708017-9e8dca80-8af3-11ea-9af1-a01e882961a2.gif)

**Comment by magento-engcom-team** [comment] 2020-04-30 12:14
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33873` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Alfa** [comment] 2020-04-30 13:14
#28015

**Comment by kaktusAtAdvox** [comment] 2020-06-03 15:44
@magento I am working on this

**Comment by kaktusAtAdvox** [comment] 2020-06-03 15:44
@magento I am working on this

**Closed as completed** 2020-06-09 19:33 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Confirmed, Issue: Format is valid, Component: Elasticsearch, Component: Filter, Reproduced on 2.4.x, Fixed in 2.4.x, Severity: S2, Progress: done, Reported on 2.4.0

**Comment by magento-engcom-team** [comment] 2021-02-16 16:01
Hi @santosh-gaggle. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-33873` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
