### ISSUE TITLE
Cannot remove products from category, infinite loop

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#23813] opened 2019-07-22 09:29 UTC
### Preconditions (*)

1. Magento 2 Commerce Edition 2.2.5
2. ElasticSearch used for frontend catalog
3. flat catalog disabled
4. Indexes updated on schedule

### Steps to reproduce (*)

1. Go to category page in admin 
2. Remove products from category by clicking "Unassign"
3. Save category

### Expected result (*)

1. Products removed from category

### Actual result (*)

1. Admin panel crashes 
2. https://snap-merixstudio.s3.amazonaws.com/m.glowacki/2019-07-01_13-52-40.mp4
3. Products are not removed from category

**Comment by engcom-Charlie** [comment] 2019-07-22 11:10
Hi @qsolutions-pl ! I have to close this issue because i can't reproduce it on 2.2-develop and 2.3-develop branches.
Thank you for contributing!

**Closed as completed by engcom-Charlie** 2019-07-22 11:10 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Admin
