### ISSUE TITLE
Magento 2.3 - CC Validation Issue with Mastercards

### ISSUE THREAD

**Issue by AndyJAllen** [magento/magento2#24113] opened 2019-08-12 15:07 UTC
### Preconditions (*)

1. Magento 2.3.1 & 2.3-develop
2. PayPal Payflow Pro 

### Steps to reproduce (*)

1.  There are valid Mastercard numbers that don't get validated correctly; despite it matching the Regex pattern correctly.

### Expected result (*)

1. Successfully recognizes mastercard
2. Allows user to check out

### Actual result (*)

1. Cant place order and receive message "Please enter a valid card type number."
2.
![image](https://user-images.githubusercontent.com/19735797/62868888-a3e88200-bce4-11e9-8239-53b22bce2dce.png)

```
{
            title: 'MasterCard',
            type: 'MC',
            pattern: '^(5[1-5][0-9]{2}|222[1-9]|22[3-9][0-9]|2[3-6][0-9]{2}|27[01][0-9]|2720)([0-9]{12})$',
            gaps: [4, 8, 12],
            lengths: [16],
            code: {
                name: 'CVC',
                size: 3
            }
        },
```

I ran 3 of our Mastercards through the Regex pattern; and all of them match, however, only the one that begins with 52* was successfully validated, and the other 2 that begin with 55* were not; despite matching the regex pattern when tested with https://regex101.com/

I'm wondering if there is something outside the scope of the regex pattern that is causing the validation to not pick up some Mastercard numbers.

**Comment by AndyJAllen** [comment] 2019-08-12 15:24
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-08-12 15:24
Hi @AndyJAllen. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-08-12 15:24
Hi @AndyJAllen, here is your [Magento instance](https://i-24113-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24113-2-3-develop.instances.magento-community.engineering/admin](https://i-24113-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AndyJAllen** [comment] 2019-08-12 15:39
I successfully replicated the issue on the vanilla instance. I turned on Paypal Payflow Pro, attempted to check out with with a multiple valid mastercard numbers, and experienced the problem. Only my mastercard beginning with 52* was recognized as a valid card, despite the others also matching the regex pattern and being 16 digits.

**Comment by AndyJAllen** [comment] 2019-08-12 16:25
How am I supposed to confirm the issue as requested by the assistant bot?

**Comment by magento-engcom-team** [comment] 2019-08-13 08:08
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19177` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Closed as completed** 2019-08-14 15:20 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Paypal

**Comment by hostep** [comment] 2019-08-15 15:30
@AndyJAllen: out of curiosity, why did you close the issue after it was confirmed?

*Update*: ah, you're probably considering this a duplicate of https://github.com/magento/magento2/issues/23707? Then everything is ok! 🙂

**Comment by AndyJAllen** [comment] 2019-08-16 20:09
> 
> 
> @AndyJAllen: out of curiosity, why did you close the issue after it was confirmed?
> 
> _Update_: ah, you're probably considering this a duplicate of #23707? Then everything is ok! 🙂

@hostep 
I'm embarrassed to admit two of my mastercards I tested with were altered accidentally in my encrypted excel document....the last digit got changed on each card somehow (hitting up/down arrows maybe)...although im still curious how they still matched the regex pattern and didnt work with the JS validation.

**Comment by 1coffeeman** [comment] 2020-05-27 19:26
I would appreciate understanding the fix?  We are experiencing similar issue with 2.2 on existing site that has been running for 4 yrs. Nothing has changed, but all of a sudden it will not take credit cards. We are using Braintree by PP.
