### ISSUE TITLE
Updated magento with latest version 2.4.7-p1 or 2.4.7-p2 getting issue

### ISSUE THREAD

**Issue by hemendrametawolf** [magento/magento2#39077] opened 2024-08-21 10:22 UTC
### Preconditions and environment

- Magento version 2.4.7-p1 or 2.4.7-p2 
- when open the website getting this issue Error: Call to a member function isGlobalScopeEnabled() on null in D:\htdocs\m24\vendor\magento\module-customer\view\frontend\templates\account\authentication-popup.phtml:26
after comment code in authentication-popup.phtml getting below error
-when open then frontend website getting this  Exception #0 (ReflectionException): Class "Auth" does not exist 

### Steps to reproduce

update magento with 2.4.7-p1 or 2.4.7-p2
run upgrade and compile command

### Expected result

frontend website should work without any error.

### Actual result

frontend showing error as 
![image](https://github.com/user-attachments/assets/68d46f61-7acd-4540-84ed-3470da5a0a87)
![image](https://github.com/user-attachments/assets/6ace2b4e-1a67-4285-978b-f350a3a8a969)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by snigam123** [comment] 2024-08-21 10:47
It appears to be a bug in magento.

In particular, \Magento\Customer\ViewModel\Customer\Auth class is missing from a block parameter declaration in default.xml in your theme. However, the error is thrown due to the classname being called instead of FQN in vendor/magento/module-customer/view/frontend/templates/js/customer-data.phtml on line 14

$auth = $block->getAuth() ?? ObjectManager::getInstance()->get(Auth::class);
The solution is to add the missing parameter to the block with name "customer.customer.data" making it as following:

<block name="customer.customer.data"  class="Magento\Customer\Block\CustomerData"
               template="Magento_Customer::js/customer-data.phtml">
            <arguments>
                <argument name="auth" xsi:type="object">Magento\Customer\ViewModel\Customer\Auth</argument>
                <argument name="json_serializer" xsi:type="object">Magento\Customer\ViewModel\Customer\JsonSerializer</argument>
                <argument name="cookie_settings" xsi:type="object">Magento\Customer\ViewModel\CookieSettings</argument>
            </arguments>
        </block>

**Comment by engcom-Delta** [comment] 2024-08-26 06:01
Hi @hemendrametawolf,

Thanks for your reporting and collaboration.
We have verified the issue in 2.4.7 to 2.4.7-p2 version, but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce**

1. Install 2.4.7 version
2. Upgrade to 2.4.7-p2 version
3. Run upgrade and compile command
![image](https://github.com/user-attachments/assets/811a266f-d896-4252-b3ef-438e0304c2b2)
![image](https://github.com/user-attachments/assets/444942b9-768a-4084-b69a-d9a89bf79c08)
5. Access Frontend and Admin
![image](https://github.com/user-attachments/assets/fe0a573c-f61a-4af0-8b74-2bb4f045b63f)
![image](https://github.com/user-attachments/assets/e2d63c57-61d6-44f5-884e-a9b42ecff846)
Please let us know if any other steps are needed to be performed.

Thanks.

**Comment by engcom-Delta** [comment] 2024-09-11 05:49
Hi @hemendrametawolf ,

We have noticed that this issue has not been updated since long time.
Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Delta** 2024-09-11 05:49 UTC
Labels: Issue: needs update, Reported on 2.4.7-p2
