### ISSUE TITLE
Adding video gallery item through API does not set extension attributes

### ISSUE THREAD

**Issue by bartlubbersen** [magento/magento2#7153] opened 2016-10-24 08:59 UTC
### Preconditions
1. Magento 2.1.2
2. PHP7
### Steps to reproduce

1. Go to swagger or call rest API through script
2. Try updating or creating a product with a video_url, video_title etc. with media type "external-video".
3. I used the following JSON:

```
{
  "product": {
    "sku": "SKU",
    "media_gallery_entries": [
        {
            "media_type": "external-video",
            "disabled": false,
            "label": "",
            "types": [],
            "content": {
                "type": "image/jpeg",
                "name": "FyL6smNEMiU.jpg",
                "base64_encoded_data": "encoded_image"
            },
            "extension_attributes": {
                "video_content": {
                    "media_type": "external-video",
                    "video_url": "https://youtu.be/FyL6smNEMiU",
                    "video_title": "Video title",
                    "video_description": "Video description"
                }
            }
        }
    ]
  },
  "saveOptions": true
}
```

Ofcourse I used a valid base64 encoded image as thumbnail and used a correct SKU.
### Expected result

Product should be created or updated with a valid video gallery item, which should have all necessary attributes filled like video_url and video_title.
### Actual result

The product is updated, however there is only a thumbnail image and no video attributes. If you will load the product through API you will get the item back with the right media_type but without attributes.
### Comment

I think it has something to do with the fact that the productRepository is handling the gallery entries by itself and is not yet processing any of the extension_attributes for gallery items.

**Comment by rafal-kos** [comment] 2016-11-18 12:18
I can confirm the issue. Example data 

```
$data = [
  'store_id' => 0,
  'entry' => [
      'id' => null,
      'media_type' => 'external-video',
      'position' => 10,
      'label' => 'TEST API',
      'types' => [],
      'disabled' => 0,
      'content' => [
          'base64_encoded_data' => base64_encode(file_get_contents('http://img.youtube.com/vi/axwE9q7llEQ/0.jpg')),
          'type' => 'image/jpeg',
          'name' => '0.jpg'
      ],
      'extension_attributes' => [
          'video_content' => [
              'media_type' => 'external-video',
              'video_provider' => '',
              'video_url' => 'https://www.youtube.com/watch?v=axwE9q7llEQ',
              'video_title' => 'keke',
              'video_description' => 'DESCRIPTION',
              'video_metadata' => ''
          ]
      ]
  ]
];
```

Image is saved but without any video content.

@bartlubbersen were you able to find some solution for that?

**Comment by bartlubbersen** [comment] 2016-11-28 15:22
@rafal-kos

I did spend some time on this issue trying to debug it, but in the end I couldn't find the cause. But I do know the issue still exists.

**Comment by olysenko** [comment] 2016-12-01 15:44
Hi, thank you for your report. Internal issue MAGETWO-61135 was  created

**Comment by bartlubbersen** [comment] 2017-01-19 12:40
Hi,

I did some more digging into this problem and found a sollution, I had to create a preference for the ProductRepository and a plugin for "Magento\Catalog\Model\Product\Gallery\Processor" to get it to work. So it should still be fixed by Magento, but maybe their developers or other people having the same problem van use it:

**ProductRepository:**
Replace in function processNewMediaGalleryEntry:
```
// Update additional fields that are still empty after addImage call
$this->getMediaGalleryProcessor()->updateImage(
    $product,
    $imageFileUri,
    [
        'label' => $newEntry['label'],
        'position' => $newEntry['position'],
        'disabled' => $newEntry['disabled'],
        'media_type' => $newEntry['media_type'],
    ]
);
```

With:
```
if (isset($newEntry['extension_attributes']['video_content'])){
    $newEntry = array_merge($newEntry['extension_attributes']['video_content'], $newEntry);
}

// Update additional fields that are still empty after addImage call
$this->getMediaGalleryProcessor()->updateImage(
    $product,
    $imageFileUri,
    $newEntry
);
```

**Processor**
Create a plugin with the following function:
```
public function aroundUpdateImage(
    Processor $subject,
    \Closure $proceed,
    \Magento\Catalog\Model\Product $product, 
    $file, 
    $data
) {
    $proceed($product, $file, $data);
    $fieldsMap = [
        'video_url' => 'video_url',
        'video_title' => 'video_title',
        'video_description' => 'video_description',
        'video_metadata' => 'video_metadata',
    ];
    
    $attrCode = $subject->getAttribute()->getAttributeCode();

    $mediaGalleryData = $product->getData($attrCode);
    
    if (!isset($mediaGalleryData['images']) || !is_array($mediaGalleryData['images'])) {
        return $this;
    }

    foreach ($mediaGalleryData['images'] as &$image) {
        if ($image['file'] == $file) {
            foreach ($fieldsMap as $mappedField => $realField) {
                if (isset($data[$mappedField])) {
                    $image[$realField] = $data[$mappedField];
                }
            }
        }
    }
    $product->setData($attrCode, $mediaGalleryData);
    
}
```

If you would prefer you could also create a preference for the Processor and just extend the $fieldsMap.
Hope it helps!

**Comment by cherreman** [comment] 2017-02-07 11:40
Any updates on this? We're running in to the same issue.

**Comment by Nicelabsrl** [comment] 2017-02-14 10:18
@bartlubbersen Could you give me the complete code and files for the plug-in Creation?
Thanks

**Comment by veloraven** [comment] 2017-06-20 12:23
This issue was fixed in develop branch.
It also was fixed for ver. 2.0 (internal ticket - MAGETWO-62587) and ver. 2.1 (MAGETWO-61135). Fixes will be available in one of the nearest releases.

**Comment by magento-engcom-team** [comment] 2017-09-13 19:24
The issue has been fixed in all release lines and delivered. Closing the issue

**Closed as completed by magento-engcom-team** 2017-09-13 19:24 UTC
Labels: Issue: Ready for Work, bug report, Component: Framework/Webapi, Issue: Format is valid

**Comment by eduard-kistner** [comment] 2017-10-13 10:14
Hi @magento-engcom-team ,

sadly i cannot validate that this issue is fixed in CE 2.1.9 although this [commit](https://github.com/magento/magento2/commit/82a2a6fb75896235b9be30816abb4b87cd82a740) seems to be the mentioned fix.

Tried it with swagger and catalogProductAttributeMediaGalleryManagementV1 with the following JSON:
`{
    "entry": {
        "media_type": "external-video",
        "disabled": false,
        "label": "Test-Video",
        "types": [],
        "position": 999,
        "content": {
            "type": "image/gif",
            "name": "test.gif",
            "base64_encoded_data": "R0lGODlhPQBEAPeoAJosM//AwO/AwHVYZ/z595kzAP/s7P+goOXMv8+fhw/v739/f+8PD98fH/8mJl+fn/9ZWb8/PzWlwv///6wWGbImAPgTEMImIN9gUFCEm/gDALULDN8PAD6atYdCTX9gUNKlj8wZAKUsAOzZz+UMAOsJAP/Z2ccMDA8PD/95eX5NWvsJCOVNQPtfX/8zM8+QePLl38MGBr8JCP+zs9myn/8GBqwpAP/GxgwJCPny78lzYLgjAJ8vAP9fX/+MjMUcAN8zM/9wcM8ZGcATEL+QePdZWf/29uc/P9cmJu9MTDImIN+/r7+/vz8/P8VNQGNugV8AAF9fX8swMNgTAFlDOICAgPNSUnNWSMQ5MBAQEJE3QPIGAM9AQMqGcG9vb6MhJsEdGM8vLx8fH98AANIWAMuQeL8fABkTEPPQ0OM5OSYdGFl5jo+Pj/+pqcsTE78wMFNGQLYmID4dGPvd3UBAQJmTkP+8vH9QUK+vr8ZWSHpzcJMmILdwcLOGcHRQUHxwcK9PT9DQ0O/v70w5MLypoG8wKOuwsP/g4P/Q0IcwKEswKMl8aJ9fX2xjdOtGRs/Pz+Dg4GImIP8gIH0sKEAwKKmTiKZ8aB/f39Wsl+LFt8dgUE9PT5x5aHBwcP+AgP+WltdgYMyZfyywz78AAAAAAAD///8AAP9mZv///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAAKgALAAAAAA9AEQAAAj/AFEJHEiwoMGDCBMqXMiwocAbBww4nEhxoYkUpzJGrMixogkfGUNqlNixJEIDB0SqHGmyJSojM1bKZOmyop0gM3Oe2liTISKMOoPy7GnwY9CjIYcSRYm0aVKSLmE6nfq05QycVLPuhDrxBlCtYJUqNAq2bNWEBj6ZXRuyxZyDRtqwnXvkhACDV+euTeJm1Ki7A73qNWtFiF+/gA95Gly2CJLDhwEHMOUAAuOpLYDEgBxZ4GRTlC1fDnpkM+fOqD6DDj1aZpITp0dtGCDhr+fVuCu3zlg49ijaokTZTo27uG7Gjn2P+hI8+PDPERoUB318bWbfAJ5sUNFcuGRTYUqV/3ogfXp1rWlMc6awJjiAAd2fm4ogXjz56aypOoIde4OE5u/F9x199dlXnnGiHZWEYbGpsAEA3QXYnHwEFliKAgswgJ8LPeiUXGwedCAKABACCN+EA1pYIIYaFlcDhytd51sGAJbo3onOpajiihlO92KHGaUXGwWjUBChjSPiWJuOO/LYIm4v1tXfE6J4gCSJEZ7YgRYUNrkji9P55sF/ogxw5ZkSqIDaZBV6aSGYq/lGZplndkckZ98xoICbTcIJGQAZcNmdmUc210hs35nCyJ58fgmIKX5RQGOZowxaZwYA+JaoKQwswGijBV4C6SiTUmpphMspJx9unX4KaimjDv9aaXOEBteBqmuuxgEHoLX6Kqx+yXqqBANsgCtit4FWQAEkrNbpq7HSOmtwag5w57GrmlJBASEU18ADjUYb3ADTinIttsgSB1oJFfA63bduimuqKB1keqwUhoCSK374wbujvOSu4QG6UvxBRydcpKsav++Ca6G8A6Pr1x2kVMyHwsVxUALDq/krnrhPSOzXG1lUTIoffqGR7Goi2MAxbv6O2kEG56I7CSlRsEFKFVyovDJoIRTg7sugNRDGqCJzJgcKE0ywc0ELm6KBCCJo8DIPFeCWNGcyqNFE06ToAfV0HBRgxsvLThHn1oddQMrXj5DyAQgjEHSAJMWZwS3HPxT/QMbabI/iBCliMLEJKX2EEkomBAUCxRi42VDADxyTYDVogV+wSChqmKxEKCDAYFDFj4OmwbY7bDGdBhtrnTQYOigeChUmc1K3QTnAUfEgGFgAWt88hKA6aCRIXhxnQ1yg3BCayK44EWdkUQcBByEQChFXfCB776aQsG0BIlQgQgE8qO26X1h8cEUep8ngRBnOy74E9QgRgEAC8SvOfQkh7FDBDmS43PmGoIiKUUEGkMEC/PJHgxw0xH74yx/3XnaYRJgMB8obxQW6kL9QYEJ0FIFgByfIL7/IQAlvQwEpnAC7DtLNJCKUoO/w45c44GwCXiAFB/OXAATQryUxdN4LfFiwgjCNYg+kYMIEFkCKDs6PKAIJouyGWMS1FSKJOMRB/BoIxYJIUXFUxNwoIkEKPAgCBZSQHQ1A2EWDfDEUVLyADj5AChSIQW6gu10bE/JG2VnCZGfo4R4d0sdQoBAHhPjhIB94v/wRoRKQWGRHgrhGSQJxCS+0pCZbEhAAOw=="
        },
        "extension_attributes": {
            "video_content": {
                "media_type": "external-video",
                "video_url": "https://youtu.be/FyL6smNEMiU",
                "video_title": "Video title",
                "video_description": "Video description"
            }
        }
    }
}`

Image gets set but nothing more, no Video data is set when i look at the product in admin backend.
Also this "fix" makes problems with programmatic media adding through 
`Magento\Catalog\Model\Product->addImageToMediaGallery` 
as the set data will get completely ignored then.
Maybe it was added during development to get rid of the error message from [here](https://github.com/magento/magento2/issues/6803) ?

 So maybe you can clarify if i am doing something wrong or if you missed to backport all changes?

**Comment by 0-Sony** [comment] 2018-08-21 16:02
Hi all,
I managed to add video programmatically using REST call.
My problem was that all data were recorded in database, but in backoffice, only thumbnail was visible , and other fields were empty.
I noticed that in database the data were set for store_id 1.
So to set this for store_id 0 , i used this call : 

`http://myawesomewebsite.com/rest/all/V1/products/{$sku}/media` 

Here is an exemple : 
```
$data = [
  'entry' => [
      'id' => null,
      'media_type' => 'external-video',
      'position' => 10,
      'label' => 'TEST API',
      'types' => ['image', 'small-image', 'thumbnail'],
      'disabled' => 0,
      'content' => [
          'base64_encoded_data' => base64_encode(file_get_contents('http://img.youtube.com/vi/axwE9q7llEQ/0.jpg')),
          'type' => 'image/jpeg',
          'name' => '0.jpg'
      ],
      'extension_attributes' => [
          'video_content' => [
              'media_type' => 'external-video',
              'video_provider' => '',
              'video_url' => 'https://www.youtube.com/watch?v=axwE9q7llEQ',
              'video_title' => 'keke',
              'video_description' => 'DESCRIPTION',
              'video_metadata' => ''
          ]
      ]
  ]
];

$ch = curl_init("http://myawesomewebsite.com/rest/all/V1/products/{$sku}/media");
            curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
            curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-Type: application/json", "Authorization: Bearer " . json_decode($token)));
            curl_exec($ch);
```

for `$token`, take a look on this link : https://inchoo.net/magento-2/magento-2-api/

Hope it helps

**Comment by sandeep570** [comment] 2018-12-12 12:36
@0-Sony I have used your solution but when i upload video then my custom image roles were deleted.Could you please help me out>

**Comment by 0-Sony** [comment] 2019-02-21 15:52
@sandeep570 Hi, do you mean that the images which are set before are deleted ? what about the video ? did the video upload well ?

**Comment by sandeep570** [comment] 2019-02-22 14:54
@0-Sony Hi, yes the images which were set before are deleted, I have created image roles and assigned the roles to particular images. When I use the Magento API to import video then sometimes videos are not assigning and for the product, images were deleted i mean particular roles were unassigned and in frontend we are missing those images for display purpose. I don't know why the video assignment creating issue for images. Could you please help me out ?
