### ISSUE TITLE
GraphQL Endpoint Error in Developer and Default Modes

### ISSUE THREAD

**Issue by jr-magento-dev** [magento/magento2#38368] opened 2024-01-20 16:23 UTC
## Summary of the issue

Magento is throwing error when hitting graphql endpoint with introspection query.

## Magento Version

Magento Community Edition2.4.6-p3

### Steps to reproduce

When sending a GraphQL request to the /graphql endpoint with the following payload:

```graphql
{
  __schema {
    types {
      kind
      name
      possibleTypes {
        name
      }
    }
  }
}
```

the following error is encountered in Developer and Default modes:

Error Message: `Missing required argument $subject of Magento\SalesGraphQlAux\Model\Resolver\SearchTerm.`
File: `vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php`
Line: `264`

Same endpoint and same codebase is giving successful response on production operation mode.

### Expected result

The success response on the below should be reachable in all environments, not only in production mode.

```json
{
    "data": {
        "__schema": {
            "types": [
                {
                    "kind": "OBJECT",
                    "name": "Query",
                    "possibleTypes": null
                },
                {
                    "kind": "SCALAR",
                    "name": "ID",
                    "possibleTypes": null
                },
                {
                    "kind": "SCALAR",
                    "name": "Boolean",
                    "possibleTypes": null
                },
                ....
                ....
                ....
                ....
                ....
                {
                    "kind": "OBJECT",
                    "name": "__EnumValue",
                    "possibleTypes": null
                },
                {
                    "kind": "OBJECT",
                    "name": "__Directive",
                    "possibleTypes": null
                },
                {
                    "kind": "ENUM",
                    "name": "__DirectiveLocation",
                    "possibleTypes": null
                }
            ]
        }
    }
}
```

### Actual result

```json
{
    "errors": [
        {
            "message": "Internal server error"
        }
    ]
}
```

### Additional information

Issue only occurs on developer and default modes. Endpoint is working as expected on production mode.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by jr-magento-dev** [comment] 2024-01-20 17:10
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-01-31 09:32
Hi @jr-magento-dev,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

When sending a GraphQL request to the /graphql endpoint with the following payload:

```
{
  __schema {
    types {
      kind
      name
      possibleTypes {
        name
      }
    }
  }
}
```




![Screenshot from 2024-01-31 12-18-39](https://github.com/magento/magento2/assets/51680745/1580051f-bffa-46b9-858e-408327532d3c)



![Screenshot from 2024-01-31 12-18-24](https://github.com/magento/magento2/assets/51680745/5895a80e-cea8-4509-9774-73616acaa10f)


We have enabled developer mode and we are not getting any error.

Kindly recheck the issue in Magento 2.4-develop instance and elaborate the steps if the issue is still reproducible.

Thanks.

**Comment by olgamchuk** [comment] 2024-02-09 18:08
Hi, having the same issue on Magento CE 2.4.6-p3, error repeats in development mode.

**Comment by engcom-Bravo** [comment] 2024-02-22 07:18
Hi @olgamchuk,

Thanks for your update.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Could you please verify the issue in Latest Magento 2.4-develop instance it might be possible issue got fixed in Magento 2.4-develop instance.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-02-26 05:48
Hi @jr-magento-dev,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Bravo** 2024-02-26 05:48 UTC
Labels: Issue: needs update, Reported on 2.4.x

**Comment by mtytula** [comment] 2024-02-29 12:33
I think this issue should be reopened
![image](https://github.com/magento/magento2/assets/36896606/646c71a7-5971-48e4-a636-414e31d12c9a)

What are those arguments - $subject and $result? After removing it the problem is gone

![image](https://github.com/magento/magento2/assets/36896606/9fc133ec-30bd-4580-9df6-e97ece5815bc)

**Comment by guilhermemap** [comment] 2024-07-19 18:23
same issue here, removing the first 2 arguments from the constructor in file vendor/magento/module-sales-graph-ql-aux/Model/Resolver/SearchTerm.php fixed it

**Comment by Reno-Axel** [comment] 2024-09-30 21:27
> same issue here, removing the first 2 arguments from the constructor in file vendor/magento/module-sales-graph-ql-aux/Model/Resolver/SearchTerm.php fixed it

Thank you
