### ISSUE TITLE
Debug layout file processing by print final merge layout xml ?

### ISSUE THREAD

**Issue by thienphucvx** [magento/magento2#10533] opened 2017-08-14 22:40 UTC
At some point, you want to print all loaded xml files to check whether your custom layout is working or not ?
In order to do that we can write a custom module like this to solve that problem:
+ We listen to an event “**layout_generate_blocks_after**” and get all loaded tree from that point.
+ Save all loaded tree to an xml file.

1/ We create a new directory Sample/Dev. Create Sample/Dev/registration.php to declare with Magento 
2 about our module directory.

`<?php

\Magento\Framework\Component\ComponentRegistrar::register(
    \Magento\Framework\Component\ComponentRegistrar::MODULE,
    'Sample_Dev',
    __DIR__
);`

2/ Create Sample/Dev/etc/module.xml : To let Magento 2 know about setup version of our module:

`<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="module.xsd">
    <module name="Sample_Dev" setup_version="1.0.0" schema_version="1.0.0" release_version="1.0.1">
    </module>
</config>`

3/ Create Sample/Dev/etc/frontend/events.xml. In this file, we will listen to event “layout_generate_blocks_after”

`<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">

    <event name="layout_generate_blocks_after">
        <observer name="thienphucvx_layout_generate_blocks_after" instance="Sample\Dev\Model\Layout" />
    </event>

</config>
`

4/ Create Sample/Dev/Model/Layout.php with the content as below

`<?php
namespace Sample\Dev\Model;
use Magento\Framework\Event\Observer;
use Magento\Framework\Event\ObserverInterface;
class Layout  implements ObserverInterface
{
    protected $_logger;
    public function __construct ( \Psr\Log\LoggerInterface $logger
    ) {
        $this->_logger = $logger;
    }

    public function execute(\Magento\Framework\Event\Observer $observer)
    {
        $xml = $observer->getEvent()->getLayout()->getXmlString();
        /*$this->_logger->debug($xml);*//*If you use it, check ouput string xml in var/debug.log*/
        $writer = new \Zend\Log\Writer\Stream(BP . '/var/log/layout_block.xml');
        $logger = new \Zend\Log\Logger();
        $logger->addWriter($writer);
        $logger->info($xml);
        return $this;
    }
}`

5/ Set up new module . In your home website directory. enter CMD command line:

– php bin/magento module:enable Sample_Dev

– php bin/magento setup:upgrade

6/ Refresh the page that you want to see xml file and check your handle xml file in **var/log/layout_block.xml** .

**I just wonder if we can have it as a default module in magento2 => So we can turn on/off to debug easily.**

Reference: 
https://magento.stackexchange.com/questions/97343/how-can-i-debug-layout-file-processing-in-magento-2/98078?noredirect=1#comment261437_98078

**Comment by orlangur** [comment] 2017-08-15 09:42
> At some point, you want to print all loaded xml files

Or just use xdebug. It allows to check state of any variable in action and not just try to guess what needs to be echoed/printed to file.

**Comment by thienphucvx** [comment] 2017-08-15 10:01
Hi Orlangur,
Actually, there are many ways to do it. My suggested solution is just one of the way to achieve it.

**Comment by orlangur** [comment] 2017-08-15 10:08
You don't need this, just learn to debug properly, without need for any hardcoded logging.

**Comment by convenient** [comment] 2017-08-15 10:16
I have had to use logging debugging like this before, and debugging like this does have its merit. For a lot of scenarios xdebug and object inspection is the usual debugging tool, but for others dumping to a log file has definitely saved me.

Saying that, I'd still probably roll this logging out bespoke as and when it's needed, as next time when you need to debug different merged xml your layout xml logger won't be useful. I'd never have thought of adding this kind of tool to the core.

**Comment by thienphucvx** [comment] 2017-08-15 10:23
Hi,
 As feedbacks from you guys. Looks like it's not needed to add to the core. So think I will close it.

**Comment by miguelbalparda** [comment] 2017-08-15 12:07
Whoa I thought this would be a really good addition as a bin/magento command.

**Comment by thienphucvx** [comment] 2017-08-15 12:30
Hi Miguelbalparda,
  Maybe we can copy and paste example code => it doestnot take much time.

**Comment by convenient** [comment] 2017-08-15 12:31
@miguelbalparda agree that it would be a good addition to the `bin/magento` command, it'd be similar to the `magerun config:dump` command.

You could have a have a lot of fun with the `config:dump` command when you start piping the result into xpath

eg
`magerun config:dump | xml sel -t -c "/config/global/full_page_cache"`

**Comment by thienphucvx** [comment] 2017-08-15 12:33
Now, I reopen it again... Let see the response from Magento

**Comment by miguelbalparda** [comment] 2017-08-15 12:36
You and I know MageRun @convenient but new devs coming here only know about bin/magento when they start, so adding this to the core might be wise no matter if it is already in MageRun. I used a similar approach in Magento 1 more times than I'd like to admit.

**Comment by convenient** [comment] 2017-08-15 12:37
Good point @miguelbalparda :)

**Comment by convenient** [comment] 2017-08-15 12:54
@thienphucvx if you want to have a go at implementing the `bin/magento` command yourself you can look at a PR I put together a few months back to port over another magerun1 command into the Magento2 core.

https://github.com/magento/magento2/pull/7982

**Comment by vherasymenko** [comment] 2017-08-15 14:13
@thienphucvx  Thank you for your report.
Please use the issue reporting [guidelines ](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)to report an issue. Include the steps required to reproduce, the actual result, and the expected result.

**Comment by magento-engcom-team** [comment] 2017-10-05 17:06
@thienphucvx we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Closed as completed by magento-engcom-team** 2017-10-05 17:06 UTC
Labels: Progress: needs update, Issue: Format is not valid

**Comment by torreytsui** [comment] 2018-06-26 11:30
Although this issue is closed already, I came across it and know that there is a workaround, so want to share it here.

Layout is cached by Magento. We can debug the layout by inspecting the layout cache.

To use this workaround:
- Make sure you're using filesystem cache (so, disable caches like redis cache)
- Load the page you want to debug with layout cache enabled
- In `var/cache/`, search for the dom or any keyword of a layout file that you are debugging

A hit or more will show you the layout cache of the current page being debugging.

![screen shot 2018-06-26 at 12 13 36](https://user-images.githubusercontent.com/945819/41908602-6d0dd916-793c-11e8-8417-4ece2cdfd670.png)

**Comment by LiamTrioTech** [comment] 2020-09-07 22:57
This would be very useful

**Comment by quickshiftin** [comment] 2020-09-14 17:19
The fact that there is no easy way to view the layout on any given page makes debugging the cryptic layout system even more tedious. The spirit of this feature should be understood by the core team, how about a simple way to dump the layout XML for any given page. After all we already have template path hints...

**Comment by LiamTrioTech** [comment] 2020-09-14 21:21
Those path hints are trash btw.
It should be on data attributes or html comments for each area and possibly chrome extension on the inspector.

**Comment by quickshiftin** [comment] 2020-09-15 13:29
Yup, template path hints are borderline useless. Just pointing out to the core team that there is a built-in debugging tool. Furthermore suggesting a similar simple tool (checkbox in the admin / flag we can set on the cli) to enable dump of layout xml on the frontend would be vastly more useful.

**Comment by AntonLee** [comment] 2020-10-05 22:41
There are third party modules attempting to solve the issue. I've found two:

- [nathanjosiah/magento2-layout-debugger](https://github.com/nathanjosiah/magento2-layout-debugger)
- [vpietri/magento2-developer-quickdevbar](https://github.com/vpietri/magento2-developer-quickdevbar)

**Comment by fd-sturniolo** [comment] 2021-09-23 11:11
To add to this, [Ho_Templatehints](https://github.com/ho-nl/magento2-Ho_Templatehints) is another module that lets you inspect layout via DevTools in a somewhat unobtrusive way.
