### ISSUE TITLE
[NOT READY] Available currencies need to contains currency name/title

### ISSUE THREAD

**Issue by codynguyen1** [magento/magento2#30600] opened 2020-10-22 08:04 UTC
*As a developer I want to show users the currency name instead of just currency code so that they can select it easier.*
![Screenshot at Oct 22 14-58-01](https://user-images.githubusercontent.com/16347586/96842686-89c53a80-1477-11eb-8fd7-b0c2e26b5bbf.png)
sample schema:
type Currency {
   available_currency: [ CurrencyOutput ]
}

type CurrencyOutput  {
value: String
title: String
symbol: String
}
### AC
* a
* b
### Approved Schema
* a

**Comment by khrystynastolbova** [comment] 2021-06-16 11:25
@magento I am working on this

**Comment by engcom-November** [comment] 2022-09-07 11:07
Hi @codynguyen1 , Thank you for reporting and collaboration. Verified the behavior on Magento 2.4-develop branch and is reproducible. As per Magento [devdocs](https://devdocs.magento.com/guides/v2.4/graphql/queries/directory-currency.html) Available currencies does not contain currency name/title but contain only codes. Hence considering this as feature request.

**Comment by engcom-Alfa** [comment] 2023-02-16 13:37
Hi All,

as per discussion with internal team confirming the jira

**Comment by engcom-November** [comment] 2023-03-21 07:40
Hi @engcom-Alfa ,
This issue is a feature request but not a bug. Hence removing Confirming label and moving it back to Feature request.
Thank you.

**Closed as completed** 2023-03-21 07:42 UTC
Labels: feature request, Component: CurrencySymbol, Component: GraphQL, Priority: P2, Project: GraphQL, Progress: done, Reported on 2.4.x, Area: Framework
