### ISSUE TITLE
Adding images or links to Wysiwyg inside widget returns an error

### ISSUE THREAD

**Issue by bart42functions** [magento/magento2#23334] opened 2019-06-20 07:28 UTC
### Preconditions (*)

1. Magento 2.3.1
2. Add a Wysiwyg element to a widget

app/code/{Vendor}/{Module}/etc/widget.xml
```xml
<parameter xsi:type="block" name="body_text" visible="true" sort_order="10">
          <label translate="true">Text</label>
         <block class="{Vendor}\{Module}\Block\Adminhtml\Widget\Type\Wysiwyg"/>
   </parameter>
```
app/code/{Vendor}/{Module}/Block/Adminhtml/Widget/Type/Wisiwyg
```php
<?php
namespace {Vendor}\{Module}\Block\Adminhtml\Widget\Type;
Class Wysiwyg extends \Magento\Backend\Block\Template
{
    /**
     * @var \Magento\Cms\Model\Wysiwyg\Config
     */
    protected $wysiwygConfig;
    /**
     * @var \Magento\Framework\Data\Form\Element\Factory
     */
    protected $factoryElement;
    /**
     * @param \Magento\Backend\Block\Template\Context $context
     * @param \Magento\Framework\Data\Form\Element\Factory $factoryElement
     * @param \Magento\Cms\Model\Wysiwyg\Config $wysiwygConfig
     * @param array $data
     */
    public function __construct(
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Framework\Data\Form\Element\Factory $factoryElement,
        \Magento\Cms\Model\Wysiwyg\Config $wysiwygConfig,
        $data = []
    ) {
        $this->factoryElement = $factoryElement;
        $this->wysiwygConfig = $wysiwygConfig;
        parent::__construct($context, $data);
    }
    /**
     * Prepare chooser element HTML
     *
     * @param \Magento\Framework\Data\Form\Element\AbstractElement $element Form Element
     * @return \Magento\Framework\Data\Form\Element\AbstractElement
     */
    public function prepareElementHtml(\Magento\Framework\Data\Form\Element\AbstractElement $element)
    {
        $editor = $this->factoryElement->create('editor', ['data' => $element->getData()])
            ->setLabel('')
            ->setForm($element->getForm())
            ->setWysiwyg(true)
            ->setConfig(
                $this->wysiwygConfig->getConfig([
                    'add_variables' => false,
                    'add_widgets' => false,
                    'add_images' => false
                ])
            );
        if ($element->getRequired()) {
            $editor->addClass('required-entry');
        }
        $element->setData('after_element_html', $editor->getElementHtml());
        $element->setValue(''); // Hides the additional label that gets added.
        return $element;
    }
}
```

### Steps to reproduce (*)

1. Create a new CMS Page
2. Add a custom widget to the page with at least one element that implements the Wysiwyg editor.
3. Add an image or hyperlink to this wysiwyg element and add the widget

### Expected result (*)

1. The widget gets correctly added to the CMS page

### Actual result (*)

1. The following error is thrown
![Screen Shot 2019-06-20 at 09 26 56](https://user-images.githubusercontent.com/30108844/59829388-9b577900-933d-11e9-84ff-c37bcd0d89e2.png)

**Comment by engcom-Charlie** [comment] 2019-06-20 10:49
Hello @bart42functions ! Thank you for your report . Can you provide more steps how to reproduce this issue ?

**Comment by hostep** [comment] 2019-06-20 19:43
Just cross-linking a 3rd party module which had a similar problem and got it fixed in the meanwhile: https://github.com/Magenerds/PageDesigner/issues/37 (not sure if this is helpful though)

**Comment by engcom-Charlie** [comment] 2019-06-21 08:40
Hello @bart42functions !
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.

**Closed as completed by engcom-Charlie** 2019-06-21 08:40 UTC
Labels: Issue: Format is valid
