### ISSUE TITLE
1 exception(s): Exception #0 (Exception): Warning: Undefined array key 0 in vendor/colinmollenhour/php-redis-session-abstract/src/Cm/RedisSession/Handler.php on line 515

### ISSUE THREAD

**Issue by xtremevision** [magento/magento2#38399] opened 2024-01-31 02:39 UTC
### Preconditions and environment

- Magento Open Source 2.4.6
- CentOS 7 x64
- httpd-2.4.58
- redis-3.2.12
- colinmollenhour/cache-backend-redis 1.17.1
- colinmollenhour/credis v1.16.0
- colinmollenhour/php-redis-session-abstract v1.5.4
- MariaDB 10.4.25
- Infinit theme from Themeforest

PHP 8.1.27 (cli) (built: Dec 19 2023 20:35:55) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.1.27, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.27, Copyright (c), by Zend Technologies
    with Xdebug v3.3.1, Copyright (c) 2002-2023, by Derick Rethans

### Steps to reproduce

1. Navigate to category pae
2. Add product to cart
3. Go to checkout 

### Expected result

No error message

### Actual result

- Checkout is broken. No shipping prices available and the order summary gets stuck loading.
- Refreshing the page fixes the checkout and the error does not show up anymore.

1 exception(s):
Exception #0 (Exception): Warning: Undefined array key 0 in /home/michael/www/xxxxxxxxxx/xxxxxxxxxx/vendor/colinmollenhour/php-redis-session-abstract/src/Cm/RedisSession/Handler.php on line 515

Exception #0 (Exception): Warning: Undefined array key 0 in /home/michael/www/xxxxxxxxx/xxxxxxxxx/vendor/colinmollenhour/php-redis-session-abstract/src/Cm/RedisSession/Handler.php on line 515
<pre>#1 Cm\RedisSession\Handler->read() called at [vendor/magento/framework/Session/SaveHandler/Redis.php:98]
#2 Magento\Framework\Session\SaveHandler\Redis->read() called at [vendor/magento/framework/Session/SaveHandler.php:212]
#3 Magento\Framework\Session\SaveHandler->callSafely() called at [vendor/magento/framework/Session/SaveHandler.php:125]
#4 Magento\Framework\Session\SaveHandler->read()
#5 session_start() called at [vendor/magento/framework/Session/SessionManager.php:186]
#6 Magento\Framework\Session\SessionManager->start() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#7 Magento\Framework\Session\Generic\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#8 Magento\Framework\Session\Generic\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#9 Magento\Framework\Session\Generic\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/Session/Generic/Interceptor.php:23]
#10 Magento\Framework\Session\Generic\Interceptor->start() called at [vendor/magento/framework/Session/SessionManager.php:123]
#11 Magento\Framework\Session\SessionManager->__construct() called at [generated/code/Magento/Framework/Session/Generic/Interceptor.php:14]
#12 Magento\Framework\Session\Generic\Interceptor->__construct() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121]
#13 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:108]
#14 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:150]
#15 Magento\Framework\ObjectManager\Factory\Compiled->get() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:79]
#16 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:150]
#17 Magento\Framework\ObjectManager\Factory\Compiled->get() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:79]
#18 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:150]
#19 Magento\Framework\ObjectManager\Factory\Compiled->get() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:79]
#20 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:150]
#21 Magento\Framework\ObjectManager\Factory\Compiled->get() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:125]
#22 Magento\Framework\ObjectManager\Factory\Compiled->parseArray() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:86]
#23 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:70]
#24 Magento\Framework\ObjectManager\ObjectManager->get() called at [vendor/magento/framework/App/FrontController.php:109]
#25 Magento\Framework\App\FrontController->__construct() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:14]
#26 Magento\Framework\App\FrontController\Interceptor->__construct() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121]
#27 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:108]
#28 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:70]
#29 Magento\Framework\ObjectManager\ObjectManager->get() called at [vendor/magento/framework/App/Http.php:115]
#30 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#31 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
</pre>

![image](https://github.com/magento/magento2/assets/6533394/2b0567da-d3f0-4224-90d4-7b6b7955d3cd)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by TheRealHunzik** [comment] 2024-01-31 04:33
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-01-31 07:20
Hi @xtremevision,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Navigate to category page
- Add product to cart
- Go to checkout

![Screenshot from 2024-01-31 11-41-45](https://github.com/magento/magento2/assets/51680745/056c2851-097b-4c16-8e18-c1729160c9b6)


![Screenshot from 2024-01-31 11-42-51](https://github.com/magento/magento2/assets/51680745/9e69d71c-4c8f-4fd7-826e-e743d6bf94c1)


We are able to see the shipping methods and able to place the order.

Kindly recheck the issue in Magento 2.4-develop instance and check if any third party modules causing the issue.

Thanks.

**Comment by xtremevision** [comment] 2024-01-31 14:03
Ok, I will test with Luma theme instead of the 3rd party theme, as well as by switching off custom modules / 3rd party modules.

**Comment by eldaly** [comment] 2024-02-01 10:59
Hi
i Have Same issue when i open multi products in one time
Exception #0 (Exception): Warning: Undefined array key 0 in /vendor/colinmollenhour/php-redis-session-abstract/src/Cm/RedisSession/Handler.php on line 515

**Comment by Amadeco** [comment] 2024-02-01 19:53
Good evening,
I see this issue also on Magento 2.4.6-p3, redis_version:7.2.4

> [2024-02-01T19:10:19.046017+00:00] main.ERROR: Warning: Undefined array key 0 in /home/amadeco/public_html/vendor/colinmollenhour/php-redis-session-abstract/src/Cm/RedisSession/Handler.php on line 515 [] []
> [2024-02-01T19:10:19.046802+00:00] main.CRITICAL: Warning: Undefined array key 0 in /home/amadeco/public_html/vendor/colinmollenhour/php-redis-session-abstract/src/Cm/RedisSession/Handler.php on line 515 [] []

**Comment by xtremevision** [comment] 2024-02-02 20:21
I noticed these messages today in var/log/system.log:

[2024-02-02T19:35:17.139662+00:00] main.WARNING: localhost|2475: Did not write session for ID b3f7mpdhrg0dmgkg8tlnb2uq8r: another process took the lock. /themelayoutpro/ajax/cmsblock/?block_identifier=unlimited-furniture-newsletter-popup [] []
[2024-02-02T19:35:18.689020+00:00] main.WARNING: localhost|2478: Did not write session for ID b3f7mpdhrg0dmgkg8tlnb2uq8r: another process took the lock. /customer/section/load/?sections=&_=1706902508672 [] []

Found this article: https://magento.stackexchange.com/questions/296730/redis-session-error-successfully-broke-lock-for-id-sess-ebfc12b22fa8c8e1fb81dca

I updated the values as per the accepted answer, but to be 100% safe I also created a dedicated redis instance for this site on port 6378.

So far, the checkout error has gone away, and the write session messages as well.

Could it be that I have too many sites accessing the same redis instance, albeit with different redis databases? Could it be another site is accessing the same database as this one effectively corrupting data?

**Comment by hostep** [comment] 2024-02-03 14:18
Hi @xtremevision

According to the comments on https://github.com/colinmollenhour/php-redis-session-abstract/commit/47a1df331c16b8ed3387102933eaeac2fd52f0e8, this seems to be a bug that existed in versions 1.5.3 and 1.5.4 of the `colinmollenhour/php-redis-session-abstract` package.
It should be fixed in version 1.5.5, could you try to update this package to the latest version and see if that solves it for you?

**Comment by engcom-Bravo** [comment] 2024-02-06 08:32
@hostep Thanks for your contribution and collaboration here.

Hi @xtremevision,

Thanks for your update.

Kindly refer this comment https://github.com/magento/magento2/issues/38399#issuecomment-1925339677 and please let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-02-08 05:45
Hi @xtremevision,

Thanks for your update.

As per this comment https://github.com/magento/magento2/issues/38399#issuecomment-1932107224 We are Closing this issue Please feel free to reopen the issue if you are still facing any issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-02-08 05:45 UTC
Labels: Issue: needs update, Reported on 2.4.6
