### ISSUE TITLE
Admin navigation and form submitting not working

### ISSUE THREAD

**Issue by vinniewhite** [magento/magento2#1038] opened 2015-02-12 10:57 UTC
Having just installed Magento 2 I am shocked that I cannot use the admin panel at all. Clicking on links in the navigation do not work, so I cannot get around without typing the urls in.

Once on a page, say the configuration page I cannot submit any forms. The buttons simply do not work.

**Comment by kokoc** [comment] 2015-02-12 11:03
@vinniewhite Thank you for reporting the issue.

Could you please share more details? Any information about 404 and 503 requests will be very useful.

**Comment by vinniewhite** [comment] 2015-02-12 11:35
Hi 

There are no errors that I can see, all the pages load and the .css and .js files are all loading too.

Maybe my logs will help:

[2015-02-12 11:33:39] main.CRITICAL: Invalid template file: '' [] []
[2015-02-12 11:34:02] main.CRITICAL: Broken reference: the 'page.bottom' element cannot be added as child to 'page.bottom.container', because the latter doesn't exist [] []
[2015-02-12 11:34:02] main.CRITICAL: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-02-12 11:34:02] main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-02-12 11:34:02] main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-02-12 11:34:02] main.CRITICAL: Broken reference: the 'store.settings.currency' tries to reorder itself towards 'store_language', but their parents are different: 'store.settings' and 'header.panel' respectively. [] []
[2015-02-12 11:34:09] main.CRITICAL: Broken reference: the 'page.bottom' element cannot be added as child to 'page.bottom.container', because the latter doesn't exist [] []
[2015-02-12 11:34:09] main.CRITICAL: Broken reference: the 'store.settings.currency' tries to reorder itself towards 'store_language', but their parents are different:

**Comment by ksultana** [comment] 2015-02-12 13:05
I'm having this problem too. Yesterday, I opened this on stackexchange. I think it's related. 

http://magento.stackexchange.com/questions/55341/magento-2-backend-errors

When I switch store view in the admin, I'm getting 404 errors as seen here: 

![image](https://cloud.githubusercontent.com/assets/10956143/6167879/22c9789c-b2c0-11e4-9838-bb0caf8a16ed.png)

**Comment by vinniewhite** [comment] 2015-02-12 17:19
Looking at the console I do seem to have issues with the jquery folder too!
![screen shot 2015-02-12 at 17 19 06](https://cloud.githubusercontent.com/assets/2504700/6172836/52a8aaea-b2db-11e4-8911-7d9d9325058d.png)

**Comment by orlangur** [comment] 2015-02-12 18:38
Seems to be duplicate of #1016.

Problem is that jquery files are not materialized into `/pub/static/` folder.

For me it happened after upgrade to PHP 5.6 in default mode.

**Comment by buskamuza** [comment] 2015-02-13 21:28
Internal ticket for #1016 - MAGETWO-34173

**Comment by snohe** [comment] 2015-03-03 23:27
Hi @vinniewhite, since this is a duplicate, we will go ahead and close this issue.  Please refer to #1016 for updates on this.

**Closed by snohe** 2015-03-03 23:27 UTC
Labels: acknowledged, bug, PS
