### ISSUE TITLE
Can't upgrade a fresh installation from 2.0.0 to 2.0.6

### ISSUE THREAD

**Issue by bch80** [magento/magento2#4603] opened 2016-05-20 11:48 UTC
## Steps to reproduce

`git clone https://github.com/magento/magento2.git
cd /var/www/magento2
composer install
composer update`
Install Magento
Edited composer.json and added:
`"magento/product-community-edition": "2.0.6",`
and changed version to:
`"version": "2.0.6",`
then:
`composer update`
## Expected result

Composer should now be upgrading my Magento
## Actual result

"Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magento/product-community-edition could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting"

**Comment by commcad** [comment] 2016-05-20 13:42
Not Magento Inc. affiliated here

and you are missing those .gitignore files. Ask me how I know loll

see: https://community.magento.com/t5/Version-Upgrades-for-2-x/Magento-2-0-Update-pending-on-upgrade-page/m-p/37275#U37275

**Comment by ghost** [comment] 2016-05-23 14:13
See also [Technical Bulletin](http://devdocs.magento.com/guides/v2.0/release-notes/tech_bull_201-upgrade.html).

**Comment by bch80** [comment] 2016-05-26 00:36
I deleted everything and re-installed it.
`git clone git@github.com:magento/magento2.git
git checkout tags/2.0.7 -b 2.0.7
`
I hope future updates won't be such a big headache.

**Comment by mazhalai** [comment] 2016-05-26 13:38
@Chris8080 upgrading while using git is a different workflow. All, you need to do is `git pull`, to get the latest version. GIt is recommended only for contributing developers. All others should either use the zip downloaded from magento.com or `composer create-project....`, then the scenario you described will work. 

Please read more about different use cases: http://devdocs.magento.com/guides/v2.0/install-gde/continue.html
How to upgrade if you are using git:http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/dev_update-magento.html
To upgrade via command line(not git based): http://devdocs.magento.com/guides/v2.0/comp-mgr/cli/cli-upgrade.html

Closing since this is not a bug.

**Closed as completed by mazhalai** 2016-05-26 13:38 UTC
