### ISSUE TITLE
Upgrading from Magento 2.3.4-p2 to 2.3.5 downgrades some packages

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#28091] opened 2020-05-03 21:05 UTC
### Preconditions (*)
1. Have Magento 2.3.4-p2 installed

### Steps to reproduce (*)
1. Upgrade Magento from version 2.3.4-p2 to 2.3.5.

### Expected result (*)
1. Packages should stay at the current version or be upgraded to the latest version which is 100.3.5

### Actual result (*)
1. Some packages are downgraded from version 100.3.4-p2 to 100.3.4 

```
Package operations: 6 installs, 225 updates, 2 removals
  - Removing guzzlehttp/streams (3.0.0)
Removing Guzzlehttp/Streams
  - Removing guzzlehttp/ringphp (1.1.1)
Removing Guzzlehttp/Ringphp
  - Installing laminas/laminas-dependency-plugin (1.0.3): Loading from cache
  - Updating amasty/module-mass-order-actions (1.5.7 => 1.5.8): Loading from cache
  - Updating amasty/module-cross-linking (1.1.2 => 1.1.3): Loading from cache
  - Updating amasty/module-xml-google-sitemap (1.5.0 => 1.5.1): Loading from cache
  - Updating amasty/module-unique-product-url (1.0.19 => 1.0.20): Loading from cache
  - Updating amasty/module-google-rich-snippets (1.4.6 => 1.4.7): Loading from cache
  - Updating amasty/module-seo-toolkit (1.16.9 => 1.16.13): Loading from cache
  - Updating amasty/ogrid (1.2.24 => 1.2.26): Loading from cache
  - Updating amasty/paction (1.1.12 => 1.1.13): Loading from cache
  - Updating amasty/pgrid (1.5.11 => 1.6.0): Loading from cache
  - Updating amasty/module-shop-by-base (2.13.4 => 2.13.5): Loading from cache
  - Updating amasty/shopby-seo (2.11.4 => 2.11.5): Loading from cache
  - Updating amasty/module-shop-by-brand (2.10.6 => 2.10.8): Loading from cache
  - Updating magento/module-store (101.0.4-p2 => 101.0.5): Loading from cache
  - Updating magento/module-user (101.1.4-p2 => 101.1.5): Loading from cache
  - Updating magento/module-backend (101.0.4-p2 => 101.0.5): Loading from cache
  - Updating magento/module-ui (101.1.4-p2 => 101.1.5): Loading from cache
  - Updating magento/module-cms (103.0.4-p2 => 103.0.5): Loading from cache
  - Downgrading magento/module-widget (101.1.4-p2 => 101.1.4): Loading from cache
  - Downgrading magento/module-variable (100.3.4-p2 => 100.3.4): Loading from cache
  - Updating magento/module-media-storage (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-theme (101.0.4-p2 => 101.0.5): Loading from cache
  - Updating magento/module-config (101.1.4-p2 => 101.1.5): Loading from cache
  - Updating laminas/laminas-diactoros (1.8.7 => 1.8.7p2): Loading from cache
  - Updating laminas/laminas-psr7bridge (0.2.2 => 0.2.2): Loading from cache
  - Updating laminas/laminas-filter (2.9.2 => 2.9.4): Loading from cache
  - Updating laminas/laminas-inputfilter (2.10.1 => 2.10.1): Loading from cache
  - Updating laminas/laminas-form (2.14.3 => 2.14.5): Loading from cache
  - Updating laminas/laminas-mvc (2.7.15 => 2.7.15): Loading from cache
  - Updating laminas/laminas-mime (2.7.2 => 2.7.4): Loading from cache
  - Updating laminas/laminas-mail (2.10.0 => 2.10.1): Loading from cache
  - Updating symfony/polyfill-php72 (v1.14.0 => v1.15.0): Loading from cache
  - Updating symfony/polyfill-intl-idn (v1.14.0 => v1.15.0): Loading from cache
  - Updating symfony/process (v4.1.12 => v4.4.8): Loading from cache
  - Installing symfony/polyfill-php73 (v1.15.0): Loading from cache
  - Updating symfony/console (v4.1.12 => v4.4.8): Loading from cache
  - Updating magento/framework (102.0.4-p2 => 102.0.5): Loading from cache
  - Updating magento/module-eav (102.0.4-p2 => 102.0.5): Loading from cache
  - Updating magento/module-email (101.0.4-p2 => 101.0.5): Loading from cache
  - Updating magento/module-developer (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-translation (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-security (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating laminas/laminas-session (2.9.1 => 2.9.3): Loading from cache
  - Updating laminas/laminas-db (2.11.0 => 2.11.3): Loading from cache
  - Updating magento/module-wishlist (101.1.4-p2 => 101.1.5-p1): Loading from cache
  - Updating magento/module-captcha (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-customer (102.0.4-p2 => 102.0.5): Loading from cache
  - Updating magento/module-sales (102.0.4-p2 => 102.0.5): Loading from cache
  - Updating magento/module-tax (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-shipping (100.3.4-p2 => 100.3.5): Loading from cache
  - Downgrading magento/module-sales-sequence (100.3.4-p2 => 100.3.4): Loading from cache
  - Downgrading magento/module-authorization (100.3.4-p2 => 100.3.4): Loading from cache
  - Updating magento/module-sales-rule (101.1.4-p2 => 101.1.5): Loading from cache
  - Updating magento/module-checkout (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-url-rewrite (101.1.4-p2 => 101.1.5): Loading from cache
  - Updating magento/module-payment (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-quote (101.1.4-p2 => 101.1.5): Loading from cache
  - Updating magento/module-directory (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-page-cache (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-catalog (103.0.4-p2 => 103.0.5): Loading from cache
  - Updating magento/module-product-alert (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-msrp (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-downloadable (100.3.4-p2 => 100.3.5): Loading from cache
  - Downgrading magento/module-gift-message (100.3.4-p2 => 100.3.4): Loading from cache
  - Updating magento/module-catalog-inventory (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-grouped-product (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-indexer (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-import-export (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-catalog-url-rewrite (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-catalog-import-export (101.0.4-p2 => 101.0.5): Loading from cache
  - Updating magento/module-rule (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-catalog-rule (101.1.4-p2 => 101.1.5): Loading from cache
  - Updating magento/framework-bulk (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-asynchronous-operations (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-newsletter (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-review (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-integration (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-reports (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-bundle (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-contact (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-cron (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-backup (100.3.4 => 100.3.5): Loading from cache
  - Updating amasty/shopby (2.13.7 => 2.14.1): Loading from cache
  - Updating amasty/smtp (1.1.11 => 1.1.12): Loading from cache
  - Updating amasty/sorting (2.8.4 => 2.8.6): Loading from cache
  - Updating anowave/ec (100.3.2 => 100.3.5): Loading from cache
  - Updating creaminternet/module-hotjar (1.0.5 => 1.0.6): Loading from cache
  - Updating creaminternet/module-navigation (1.0.9 => 1.2.3): Loading from cache
  - Updating creaminternet/module-svg-sprite (1.1.2 => 1.1.3): Loading from cache
  - Updating firebear/importexport (3.3.1 => 3.3.2): Loading from cache
  - Updating firebear/platform-m1 (1.0.8 => 1.1.0): Loading from cache
  - Updating magento/module-weee (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-configurable-product (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-checkout-agreements (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating fooman/pdfcore-m2 (18.3.2 => 18.4.1): Loading from cache
  - Updating fooman/pdfdesign-m2 (1.0.2 => 1.1.0): Loading from cache
  - Updating fooman/emailattachments-implementation-m2 (107.0.0 => 107.0.1): Loading from cache
  - Updating fooman/pdfcustomiser-implementation-m2 (115.2.0 => 115.4.1): Loading from cache
  - Updating fooman/pdfcustomiser-m2 (8.3.1 => 8.4.0)
  - Updating klarna/module-core (5.2.4 => 5.3.0): Loading from cache
  - Updating magento/module-vault (101.1.4-p2 => 101.1.5): Loading from cache
  - Updating magento/module-instant-purchase (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-paypal (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating klarna/module-base (7.1.0 => 7.1.1): Loading from cache
  - Updating klarna/module-backend (7.0.0 => 7.0.1): Loading from cache
  - Updating klarna/module-kco (8.1.2 => 8.1.3): Loading from cache
  - Updating klarna/module-kred (7.0.1 => 7.0.2): Loading from cache
  - Updating klarna/m2-checkout (8.2.0 => 8.2.1)
  - Updating temando/module-shipping (1.6.2 => 2.0.0)
  - Updating magento/module-adobe-stock-image-admin-ui (1.0.0 => 1.0.1): Loading from cache
  - Updating magento/module-media-gallery (100.3.0-p2 => 100.3.1): Loading from cache
  - Updating magento/adobe-stock-integration (1.0.0 => 1.0.1)
  - Updating magento/module-inventory-api (1.0.7 => 1.0.8): Loading from cache
    ...Module Magento_InventoryApi recognized as part of Magento Multi Source Inventory implementation
    ...Keep Magento_InventoryApi module disabled as in current configuration
  - Updating magento/module-inventory-source-deduction-api (1.0.7 => 1.0.8): Loading from cache
    ...Module Magento_InventorySourceDeductionApi recognized as part of Magento Multi Source Inventory implementation
    ...Keep Magento_InventorySourceDeductionApi module disabled as in current configuration
  - Updating magento/module-inventory-shipping-admin-ui (1.0.7 => 1.0.8): Loading from cache
    ...Module Magento_InventoryShippingAdminUi recognized as part of Magento Multi Source Inventory implementation
    ...Keep Magento_InventoryShippingAdminUi module disabled as in current configuration
  - Updating magento/module-inventory-shipping (1.0.7 => 1.0.8): Loading from cache
    ...Module Magento_InventoryShipping recognized as part of Magento Multi Source Inventory implementation
    ...Keep Magento_InventoryShipping module disabled as in current configuration
  - Updating magento/module-inventory (1.0.7 => 1.0.8): Loading from cache
    ...Module Magento_Inventory recognized as part of Magento Multi Source Inventory implementation
    ...Keep Magento_Inventory module disabled as in current configuration
  - Updating magento/module-inventory-admin-ui (1.0.7 => 1.0.8): Loading from cache
    ...Module Magento_InventoryAdminUi recognized as part of Magento Multi Source Inventory implementation
    ...Keep Magento_InventoryAdminUi module disabled as in current configuration
  - Updating magento/module-inventory-sales-admin-ui (1.0.7 => 1.0.8): Loading from cache
    ...Module Magento_InventorySalesAdminUi recognized as part of Magento Multi Source Inventory implementation
    ...Keep Magento_InventorySalesAdminUi module disabled as in current configuration
  - Updating magento/module-inventory-sales (1.0.7 => 1.0.8): Loading from cache
    ...Module Magento_InventorySales recognized as part of Magento Multi Source Inventory implementation
    ...Keep Magento_InventorySales module disabled as in current configuration
  - Updating magento/module-inventory-product-alert (1.0.7 => 1.0.8): Loading from cache
    ...Module Magento_InventoryProductAlert recognized as part of Magento Multi Source Inventory implementation
    ...Keep Magento_InventoryProductAlert module disabled as in current configuration
  - Updating magento/module-inventory-low-quantity-notification (1.0.7 => 1.0.8): Loading from cache
    ...Module Magento_InventoryLowQuantityNotification recognized as part of Magento Multi Source Inventory implementation
    ...Keep Magento_InventoryLowQuantityNotification module disabled as in current configuration
  - Updating magento/module-inventory-indexer (1.0.7 => 1.0.8): Loading from cache
    ...Module Magento_InventoryIndexer recognized as part of Magento Multi Source Inventory implementation
    ...Keep Magento_InventoryIndexer module disabled as in current configuration
  - Updating magento/module-inventory-import-export (1.0.7 => 1.0.8): Loading from cache
    ...Module Magento_InventoryImportExport recognized as part of Magento Multi Source Inventory implementation
    ...Keep Magento_InventoryImportExport module disabled as in current configuration
  - Updating magento/module-inventory-catalog-admin-ui (1.0.7 => 1.0.8): Loading from cache
    ...Module Magento_InventoryCatalogAdminUi recognized as part of Magento Multi Source Inventory implementation
    ...Keep Magento_InventoryCatalogAdminUi module disabled as in current configuration
  - Updating magento/module-inventory-grouped-product-admin-ui (1.0.7 => 1.0.8): Loading from cache
    ...Module Magento_InventoryGroupedProductAdminUi recognized as part of Magento Multi Source Inventory implementation
    ...Keep Magento_InventoryGroupedProductAdminUi module disabled as in current configuration
  - Updating magento/module-inventory-grouped-product (1.0.6 => 1.0.7): Loading from cache
    ...Module Magento_InventoryGroupedProduct recognized as part of Magento Multi Source Inventory implementation
    ...Keep Magento_InventoryGroupedProduct module disabled as in current configuration
  - Updating magento/module-inventory-catalog (1.0.7 => 1.0.8): Loading from cache
    ...Module Magento_InventoryCatalog recognized as part of Magento Multi Source Inventory implementation
    ...Keep Magento_InventoryCatalog module disabled as in current configuration
  - Updating magento/module-catalog-search (101.0.4-p2 => 101.0.5): Loading from cache
  - Updating magento/module-search (101.0.4-p2 => 101.0.5): Loading from cache
  - Updating magento/module-inventory-configurable-product (1.0.7 => 1.0.8): Loading from cache
    ...Module Magento_InventoryConfigurableProduct recognized as part of Magento Multi Source Inventory implementation
    ...Keep Magento_InventoryConfigurableProduct module disabled as in current configuration
  - Updating magento/inventory-composer-metapackage (1.1.4 => 1.1.5)
  - Updating msp/recaptcha (2.2.2 => 2.2.3): Loading from cache
  - Updating symfony/polyfill-php70 (v1.14.0 => v1.15.0): Loading from cache
  - Updating webmozart/assert (1.7.0 => 1.8.0): Loading from cache
  - Updating phpdocumentor/reflection-common (2.0.0 => 2.1.0): Loading from cache
  - Updating magento/module-analytics (100.3.4 => 100.3.5): Loading from cache
  - Updating yotpo/magento2-module-yotpo-reviews (3.0.1 => 3.1.0): Loading from cache
  - Updating yotpo/magento2-module-yotpo-reviews-bundle (3.0.1 => 3.1.0)
  - Updating vertex/module-tax (3.3.1 => 3.4.0): Loading from cache
  - Updating snowdog/theme-blank-sass (1.3.0 => 1.4.0): Loading from cache
  - Updating creaminternet/language-nl_nl (1.1.8 => 1.1.9): Loading from cache
  - Updating creaminternet/module-dutchshop (1.3.5 => 1.3.6): Loading from cache
  - Updating laminas/laminas-i18n (2.10.1 => 2.10.3): Loading from cache
  - Updating symfony/event-dispatcher (v4.3.11 => v4.4.8): Loading from cache
  - Updating magento/magento2-base (2.3.4-p2 => 2.3.5-p1): Loading from cache
  - Updating vertex/module-address-validation (1.0.1 => 1.1.0): Loading from cache
  - Updating vertex/product-magento-module (3.3.1 => 3.4.0)
  - Updating klarna/module-ordermanagement (5.0.7 => 5.0.8): Loading from cache
  - Updating klarna/module-kp (6.4.1 => 6.5.0): Loading from cache
  - Updating klarna/m2-payments (7.4.3 => 7.5.0)
  - Downgrading magento/module-send-friend (100.3.4-p2 => 100.3.4): Loading from cache
  - Updating dotmailer/dotmailer-magento2-extension (4.1.0 => 4.4.0): Loading from cache
  - Updating dotmailer/dotmailer-magento2-extension-chat (1.0.0 => 1.0.1): Loading from cache
  - Updating dotmailer/dotmailer-magento2-extension-package (4.1.0 => 4.4.0)
  - Updating amzn/amazon-pay-and-login-with-amazon-core-module (3.3.1 => 3.4.1): Loading from cache
  - Updating amzn/login-with-amazon-module (3.3.1 => 3.4.1): Loading from cache
  - Updating amzn/amazon-pay-module (3.3.1 => 3.4.1): Loading from cache
  - Updating amzn/amazon-pay-and-login-magento-2-module (3.3.1 => 3.4.1)
  - Installing magento/module-csp (100.3.0): Loading from cache
  - Updating magento/module-tinymce-3 (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/framework-message-queue (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/framework-amqp (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/theme-frontend-blank (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/theme-frontend-luma (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/theme-adminhtml-backend (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-catalog-graph-ql (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-webapi-async (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-graph-ql (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-usps (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-ups (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-swatches (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-swagger (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-sitemap (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-signifyd (100.3.4-p2 => 100.3.5): Loading from cache
  - Downgrading magento/module-release-notification (100.3.4-p2 => 100.3.4): Loading from cache
  - Updating magento/module-customer-graph-ql (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-quote-graph-ql (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-product-video (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-persistent (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-offline-shipping (100.3.4-p2 => 100.3.5): Loading from cache
  - Downgrading magento/module-new-relic-reporting (100.3.4-p2 => 100.3.4): Loading from cache
  - Downgrading magento/module-mysql-mq (100.3.4-p2 => 100.3.4): Loading from cache
  - Updating magento/module-multishipping (100.3.4 => 100.3.5): Loading from cache
  - Downgrading magento/module-message-queue (100.3.4-p2 => 100.3.4): Loading from cache
  - Updating magento/module-url-rewrite-graph-ql (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-swatches-graph-ql (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-configurable-product-graph-ql (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-catalog-url-rewrite-graph-ql (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-cookie (100.3.4 => 100.3.5): Loading from cache
  - Downgrading magento/module-google-optimizer (100.3.4-p2 => 100.3.4): Loading from cache
  - Updating magento/module-google-adwords (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-encryption-key (100.3.4 => 100.3.5): Loading from cache
  - Installing ezimuel/guzzlestreams (3.0.1): Loading from cache
  - Installing ezimuel/ringphp (1.1.2): Loading from cache
  - Updating elasticsearch/elasticsearch (v6.7.2 => v7.6.1): Loading from cache
  - Downgrading magento/module-advanced-search (100.3.4-p2 => 100.3.4): Loading from cache
  - Updating magento/module-elasticsearch (100.3.4 => 100.3.5): Loading from cache
  - Installing magento/module-elasticsearch-7 (100.3.0): Loading from cache
  - Updating magento/module-elasticsearch-6 (100.3.3 => 100.3.4): Loading from cache
  - Updating magento/module-downloadable-import-export (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-dhl (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-customer-import-export (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-currency-symbol (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-catalog-widget (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-catalog-rule-configurable (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-cardinal-commerce (100.3.1-p2 => 100.3.2): Loading from cache
  - Updating magento/module-braintree (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-braintree-graph-ql (100.3.1 => 100.3.2): Loading from cache
  - Updating magento/module-authorizenet-graph-ql (100.3.1 => 100.3.2): Loading from cache
  - Updating magento/module-authorizenet-acceptjs (100.3.3 => 100.3.4): Loading from cache
  - Updating magento/module-authorizenet (100.3.4 => 100.3.5): Loading from cache
  - Updating magento/module-admin-notification (100.3.4-p2 => 100.3.5): Loading from cache
  - Updating magento/module-admin-analytics (100.3.1-p2 => 100.3.2): Loading from cache
  - Updating laminas/laminas-feed (2.12.0 => 2.12.2): Loading from cache
  - Updating magento/product-community-edition (2.3.4-p2 => 2.3.5-p1)
  - Updating doctrine/annotations (v1.8.0 => 1.10.2): Loading from cache
  - Updating symfony/stopwatch (v4.4.5 => v4.4.8): Loading from cache
  - Updating firebase/php-jwt (v5.1.0 => v5.2.0): Loading from cache
  - Updating squizlabs/php_codesniffer (3.5.4 => 3.5.5): Loading from cache
  - Updating vlucas/phpdotenv (v2.6.1 => v2.6.4): Loading from cache
  - Updating symfony/config (v4.4.5 => v4.4.8): Loading from cache
  - Updating symfony/dependency-injection (v4.4.5 => v4.4.8): Loading from cache
  - Updating phpoption/phpoption (1.7.2 => 1.7.3): Loading from cache
  - Updating symfony/yaml (v3.4.38 => v3.4.40): Loading from cache
  - Updating symfony/mime (v5.0.5 => v5.0.8): Loading from cache
  - Updating symfony/http-foundation (v4.4.5 => v5.0.8): Loading from cache
  - Updating allure-framework/allure-php-api (1.1.7 => 1.1.8): Loading from cache
  - Updating symfony/dom-crawler (v4.4.5 => v4.4.8): Loading from cache
  - Updating symfony/browser-kit (v4.4.5 => v4.4.8): Loading from cache
  - Updating consolidation/self-update (1.1.5 => 1.2.0): Loading from cache
```

**Comment by hostep** [comment] 2020-05-04 18:32
We should probably close this as a duplicate of https://github.com/magento/magento2/issues/28037 ?

It was confirmed in [Slack](https://magentocommeng.slack.com/archives/CBSL1DF8B/p1588273922114000?thread_ts=1588261942.113900&cid=CBSL1DF8B) to be caused by a bug in the packaging of certain Magento versions. Magento is investigating it.

**Comment by ihor-sviziev** [comment] 2020-05-05 08:22
Duplicate of https://github.com/magento/magento2/issues/28037

**Closed as completed by ihor-sviziev** 2020-05-05 08:22 UTC
Labels: duplicate, Issue: Format is valid, Reported on 2.3.4-p2
