### ISSUE TITLE
Choose to create a shipping invoice at the same time from the invoices page, the following error message appears: "We cannot create an empty shipment." 

### ISSUE THREAD

**Issue by ghost** [magento/magento2#24562] opened 2019-09-12 05:45 UTC
### Preconditions (*)
1. Originally Magento CE 2.2.6.
2. I have upgraded from Magento CE 2.2.6 to Magento CE 2.2.9.

### Steps to reproduce (*)
1. Buy Simple Product that is tied to Configurable Products.
2. Select the respective order from the order list.
3. Click the Invoice button in the upper right corner of the order page.
4. Create a shipping invoice at the same time on the invoices page.

### Expected result (*)
1. An invoice is created.
2. Shipping invoice is created.
3. Order Status is updated to "Complete"

### Actual result (*)
1. The invoice was not created.
2. A shipping invoice was not created.
3. The invoice page displays the error message "We cannot create an empty shipment.".

### Actual result (*)
1. Purchasing a Simple Product tied to a Configurable Product causes problems.
2. If you purchase a Simple Product that is not tied to a Configurable Product, the process will succeed.
3. This error does not depend on the payment method

**Comment by engcom-Charlie** [comment] 2019-09-12 06:50
Hello @HironobuHiga 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.

We are closing this issue due to branch `2.2-develop` was closed and
> Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.

 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-09-12 06:50 UTC
Labels: Issue: Format is valid
