### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'clientWidth' of undefined" error message appears on New Media Gallery page

### ISSUE THREAD

**Issue by chalov-anton** [magento/magento2#30168] opened 2020-09-23 13:08 UTC
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. Log in Admin Panel and go to _Stores - Configuration - Advanced - System- Media Gallery_
2. Set **Enable Old Media Gallery** to **No.** 
3. **Save Config** and clear Magento cache
4. Log out from Admin
5. Generate _small profile_ for your instance
`php bin/magento setup:performance:generate-fixtures setup/performance-toolkit/profiles/ce/small.xml`
6. Perform Media Gallery synchronization
`php bin/magento media-gallery-sync`
7. Clear Magento cache 
`php bin/magento cache:clean`
8. Log in Admin Pannel 
9. Go to **Content - Media Gallery**

### Expected result (*)
Media Gallery is opened no error messages in dev console

### Actual result (*)
❌ _Uncaught TypeError: Cannot read property 'clientWidth' of undefined_

### Note
The bug is unstable, usually appeared on my system after _Sign Out/Sign In_ Magento Admin

The error "comes from" 'masanory.js'
![client_width](https://user-images.githubusercontent.com/45624059/94016417-c0dff780-fdb6-11ea-90c1-820463ed3f74.png)

**Comment by magento-engcom-team** [comment] 2020-09-23 13:24
:white_check_mark: Confirmed by @sivaschenko 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37871` were created

**Issue Available**: @sivaschenko, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by konarshankar07** [comment] 2020-09-24 04:52
@magento I'm working on this

**Comment by ihor-sviziev** [comment] 2021-01-06 13:44
I believe we still need to fix it

**Comment by ihor-sviziev** [comment] 2021-03-23 15:12
Please leave it open

**Comment by ihor-sviziev** [comment] 2021-06-08 05:02
Please keep it open.

**Comment by ihor-sviziev** [comment] 2021-06-08 05:04
@sdzhepa could you re-triage this issue? JS errors usually causing some not obvious issues. It's better to fix them.

**Comment by Hanhan1989** [comment] 2021-11-09 16:14
The problem still exists in Magento 2.4.2-p1.  The problem appears when you enable Page builder, and click on select from media Gallery button. See attached image please

![image](https://user-images.githubusercontent.com/11807165/140961761-00d3b382-8c5c-4f0a-b265-03c4a0a9d94b.png)

**Comment by benlau87** [comment] 2023-07-02 15:44
still exists in Magento 2.4.4 for me. Any solution?

**Comment by arielashri** [comment] 2023-08-27 13:31
i faced the same issue and this one occurs mainly in Google Chrome. On Firefox this is working as expected.

**Comment by blacksheep171** [comment] 2024-02-27 03:19
Do you know how I can fix this issue on Chrome?

**Comment by pod6wasjerks** [comment] 2024-04-18 12:58
Still exists in 2.4.6-p5

**Comment by engcom-Delta** [comment] 2024-08-07 13:23
Hi @chalov-anton ,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop and the issue is not reproducible. Kindly refer the screenshots.

**Steps to Reproduce**
1. Access Admin Panel.
2. Go to Stores - Configuration - Advanced - System- Media Gallery
3. Set Enable Old Media Gallery to No.
![image](https://github.com/user-attachments/assets/5c7bcc61-8b16-46a3-ab76-4c493af6edb8)
4. Save Config and Clear Cache
5. Logout from Admin
6. Generate small profile for your instance
php bin/magento setup:performance:generate-fixtures setup/performance-toolkit/profiles/ce/small.xml
![image](https://github.com/user-attachments/assets/8eda7681-89ac-42b0-866a-06002d14aa76)
7. Perform Media Gallery synchronization
php bin/magento media-gallery-sync
![image](https://github.com/user-attachments/assets/3a3f99d9-8d40-4008-ab57-2db452695f21)

8. Clear Magento cache
php bin/magento cache:clean
9. Log in Admin Pannel
10. Go to Content - Media Gallery
11. Manage Gallery 
![image](https://github.com/user-attachments/assets/cbd134b1-ec6e-4d06-ab52-028c1b5a5ede)
![image](https://github.com/user-attachments/assets/b92886bf-ed55-457d-9005-41dec5dde1fb)
![image](https://github.com/user-attachments/assets/cdf82750-740d-4dec-b675-79d5a11fc635)

Kindly recheck the issue on latest Magento 2.4-develop instance and Please let us know if you are still facing any issue.

Thanks.

**Closed as completed by engcom-Delta** 2024-08-07 13:23 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Issue: Format is valid, Component: Ui, Reproduced on 2.4.x, Priority: P3, Severity: S4, Project: ASI, Component: MediaGalleryUi, Progress: done
