### ISSUE TITLE
PNG with transparency resized to completely transparent image

### ISSUE THREAD

**Issue by Orstio** [magento/magento2#17450] opened 2018-08-08 17:04 UTC
### Preconditions

I've created this ticket again since it was indicated that it was fixed in 2.2.5, and it was not.

1. Upload a PNG image with a transparency. (Original image attached)
![americana steel front](https://user-images.githubusercontent.com/6753949/41509580-eaedb388-721b-11e8-966b-fffb529b2ea9.png)

2. All of the resized images are blank, completely filled with transparency. (resized image attached, YES there is an image there.)
![americana-steel-front_1_9](https://user-images.githubusercontent.com/6753949/41509588-16212fda-721c-11e8-8650-dc1cdd619072.png)

3. Environment:  PHP 7.1.17, Linux 3.10.0 #1 SMP Fri Apr 20 17:42:34 MSK 2018 x86_64

GD Support => enabled
GD headers Version => 2.2.5
GD library Version => 2.2.5
FreeType Support => enabled
FreeType Linkage => with freetype
FreeType Version => 2.4.11
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
libJPEG Version => 6b
PNG Support => enabled
libPNG Version => 1.5.13
WBMP Support => enabled
XPM Support => enabled
libXpm Version => 30411
XBM Support => enabled
WebP Support => enabled

Directive => Local Value => Master Value
gd.jpeg_ignore_warning => 1 => 1

Magento 2.2.5

### Steps to reproduce

1. Upload a catalog image with a transparency.
2. View the product on the frontend.

### Expected result

1. Image should be resized, and should look like the original but resized.  It should not be completely blank.

### Actual result

1. Resized image is completely filled with transparent pixels.

**Comment by magento-engcom-team** [comment] 2018-08-08 17:04
Hi @Orstio. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Orstio do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Orstio** [comment] 2018-08-08 17:07
Yes, it is reproducable on a vanilla Magento instance.

It is exactly the same as this:

https://github.com/magento/magento2/issues/16201

The issue was not actually fixed in 2.2.5 as indicated.

**Comment by engcom-backlog-nickolas** [comment] 2018-08-09 06:54
Hello @Orstio, thank you for your report. I cannot reproduce this issue.
![peek 2018-08-09 10-00](https://user-images.githubusercontent.com/40755810/43882961-3bbad09e-9bba-11e8-99d5-c57e86e76133.gif)

Could you please correct steps I did, or add more details?

**Comment by Orstio** [comment] 2018-08-09 13:44
Is it necessary to run bin/magento catalog:images:resize after adding images to a product?  I have certainly not been doing that.

**Comment by engcom-backlog-nickolas** [comment] 2018-08-09 14:01
@Orstio, no, it's not necessary, I did both, with and without resize. Results are the same.

**Comment by Orstio** [comment] 2018-08-09 15:18
Are there any differences in your test environment?



    Environment: PHP 7.1.17, Linux 3.10.0 #1 SMP Fri Apr 20 17:42:34 MSK 2018 x86_64

GD Support => enabled
GD headers Version => 2.2.5
GD library Version => 2.2.5
FreeType Support => enabled
FreeType Linkage => with freetype
FreeType Version => 2.4.11
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
libJPEG Version => 6b
PNG Support => enabled
libPNG Version => 1.5.13
WBMP Support => enabled
XPM Support => enabled
libXpm Version => 30411
XBM Support => enabled
WebP Support => enabled

Directive => Local Value => Master Value
gd.jpeg_ignore_warning => 1 => 1

**Comment by engcom-backlog-nickolas** [comment] 2018-08-09 15:54
@Orstio, here is mine:

`Environment: PHP 7.1.20, Linux 4.4.0-131-generic #1 SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 `

GD Support => enabled
GD headers Version => 2.2.5
GD library Version => 2.2.5
FreeType Support => enabled
FreeType Linkage => with freetype
FreeType Version => 2.6.1
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
libJPEG Version => 8
PNG Support => enabled
libPNG Version => 1.2.54
WBMP Support => enabled
XPM Support => enabled
libXpm Version => 30411
XBM Support => enabled
WebP Support => enabled

Directive => Local Value => Master Value
gd.jpeg_ignore_warning => 1 => 1

**Comment by Orstio** [comment] 2018-08-09 15:57
The only major difference I see is this one:

libPNG Version => 1.2.54

Let me see if I can downgrade libPNG and I'll get back to you.

**Comment by Orstio** [comment] 2018-08-09 16:49
Downgrading libpng does not appear to be an option.

Is there a way I can switch Magento to use ImageMagick instead of GD2?

**Comment by Orstio** [comment] 2018-08-09 16:52
Found it.  ImageMagick appears to work, while GD2 does not.

**Comment by engcom-backlog-nickolas** [comment] 2018-08-10 11:50
@Orstio, thanks for details. But, I've tested with GD2, In fact, I even have no 'Imagick' PHP extension installed.

**Comment by Orstio** [comment] 2018-08-10 13:38
Yes, I think it has to do with the libPNG version.  You're using 1.2, and I'm using 1.5

**Comment by engcom-backlog-nickolas** [comment] 2018-08-10 13:52
@Orstio, thank you for feedback. So, I'm closing this issue, as there is nothing to fix in magento, and Github is intended to core magento modules and components.
If you'd like to update it, please reopen the issue.

**Closed as completed by engcom-backlog-nickolas** 2018-08-10 13:52 UTC
Labels: non-issue, Issue: Format is valid

**Comment by wakar** [comment] 2019-04-19 14:05
We're also facing same problem....libPNG version is 1.5.13 and OS is Centos7.

Should we downgrade the version?

**Comment by Orstio** [comment] 2019-04-19 14:16
All I ended up doing was switching to ImageMagick instead of GD.  I think more and more people will face this issue as their servers upgrade the version of GD, and then it will be taken seriously and fixed, or everyone will just switch to using ImageMagick instead since it seems to work with Magento2.

**Comment by jonashrem** [comment] 2020-03-10 12:59
Still happening with libPNG 1.6.34

@engcom-backlog-nickolas what is the solution in your opinion? Switching to libPNG 1.2 is not an option in modern operating systems, so I think this needs to be fixed on magento side (or ImageMagick should be the default).
