### ISSUE TITLE
I have fixed indexer

### ISSUE THREAD

**Issue by kukulis** [magento/magento2#8698] opened 2017-02-27 18:39 UTC
Indexer did not took in to account products belonging to websites. I have fixed it, by editing AbstractEav class function _prepareRelationIndexSelect, by adding join with websites table:   
-> join (
            ['web'=>'catalog_product_website'], 'web.product_id = i.entity_id and web.website_id=cs.website_id', [] )

The whole code is:
    
```
 protected function _prepareRelationIndexSelect($parentIds = null)
    {
        $connection = $this->getConnection();
        $idxTable = $this->getIdxTable();
        $linkField = $this->getMetadataPool()->getMetadata(ProductInterface::class)->getLinkField();
        $select = $connection->select()->from(
            ['l' => $this->getTable('catalog_product_relation')],
            []
        )->joinLeft(
            ['e' => $this->getTable('catalog_product_entity')],
            'e.' . $linkField .' = l.parent_id',
            ['e.entity_id as parent_id']
        )->join(
            ['cs' => $this->getTable('store')],
            '',
            []
        )->join(
            ['i' => $idxTable],
            'l.child_id = i.entity_id AND cs.store_id = i.store_id',
            ['attribute_id', 'store_id', 'value']
        )-> join (
            ['web'=>'catalog_product_website'], 'web.product_id = i.entity_id and web.website_id=cs.website_id', [] // TODO parasyti magento supportui
        )->group(
            ['parent_id', 'i.attribute_id', 'i.store_id', 'i.value']
        );
        if ($parentIds !== null) {
            $select->where('e.entity_id IN(?)', $parentIds);
        }

        /**
         * Add additional external limitation
         */
        $this->_eventManager->dispatch(
            'prepare_catalog_product_index_select',
            [
                'select' => $select,
                'entity_field' => new \Zend_Db_Expr('l.parent_id'),
                'website_field' => new \Zend_Db_Expr('cs.website_id'),
                'store_field' => new \Zend_Db_Expr('cs.store_id')
            ]
        );

        return $select;
    }

```
I hope you will add this fix in to next magento release ( 2.1.5 ? )

**Comment by orlangur** [comment] 2017-02-27 20:47
Hi @kukulis, the best way to propose some code change is pull request submitting.

You can do it even directly from GitHub UI: https://github.com/magento/magento2/edit/develop/app/code/Magento/Catalog/Model/ResourceModel/Product/Indexer/Eav/AbstractEav.php

**Comment by aakimov** [comment] 2017-03-06 09:13
Hi @kukulis,

Thank you for your report.
First of all, as previous comment states, if you want to contribute your code please create a pull request for it.
Moreover, when you report an issue please provide description in the following form:
For instance:
**Preconditions**
1. Website is created;
2. Simple product is created and assigned to website;

**Steps to Reproduce:**
1. Try to reindex EAV attributes;

**Actual Result:**
- describe the current behavior (for instance some data is missing)

**Expected Result:**
- describe expected result (database table states etc)

This will help us to verify and check if it is really an issue.
Thank you in advance.

**Comment by kukulis** [comment] 2017-03-06 23:30
Preconditions.
1) Website is created is on a staging server still, so I will not provide its address. It has 5 magento "websites", but for the reproduction of the situation would be enough to have in mind two websites: A and B; each website has one store view: Va for A and Vb for B.
2) There is a size attribute. There is a configurable product X with 4 variations v1, v2, v3, v4. Each variation depends on size - s1, s2, s3, s4 respectively.  To a site A belongs variations v1, v2, v3; to site B belongs variations v2, v3, v4. ( Variations are simple/virtual products, that might be assigned to a particular website through magento admin, by editing each of simple/virtual product )

Lets say there is a category, where only one X product belongs. So in the frontend in the store view Va  we go to that category. We see the size filter in the left with values s1,s2, s3, s4, *instead* of only s1,s2,s3 *because* indexer, when creates attributes index, it assigns/copies configurable product attributes index from *all* websites, but it should *not*.  In the store view Vb, we see also size filter s1,s2,s3,s4, instead of only s2,s3,s4, because of the same reason.

About database table states. Its difficult to me to present particular tables states, but when I made that change, I posted in the previous message, and then called bin/magento indexer:reindex -  the problem has been *solved*:
In store view Va, in the size filter I see s1,s2,s3 and in the store view Vb is see size filter s2, s3, s4.

This is because that change I propose to do 
`-> join ( ['web'=>'catalog_product_website'], 'web.product_id = i.entity_id and web.website_id=cs.website_id', [] )
`
Will only copy attributes index values from variations to configurable products, regarding store view, which belongs to corresponding assigned websites.

**Comment by orlangur** [comment] 2017-10-21 17:26
@kukulis please change issue description according to https://github.com/magento/magento2/blob/2.2-develop/ISSUE_TEMPLATE.md (instead of adding it as a comment) and post a PR targeting `2.2-develop` with suggested changes if issue is relevant for `2.2`.

**Comment by magento-engcom-team** [comment] 2017-11-07 05:57
@kukulis, we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Closed as completed by magento-engcom-team** 2017-11-07 05:57 UTC
Labels: bug report, Progress: needs update, Issue: Format is not valid
