### ISSUE TITLE
Category image gets nulled after second save

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#26734] opened 2020-02-06 14:07 UTC
### Preconditions (*)

1. Magento Open Source
2. Versions: 2.2.10, 2.3.2, 2.3.3

### Steps to reproduce (*)

1. Create a category
2. Add an image to category image attribute
3. Save category 
4. Images is stored
5. Save categroy again

### Expected result (*)

1. attributes gets updated or nothing is changed (it depends on changes)

### Actual result (*)

1. Category image gets removed 

#### Note
This fully works in all EARLIER version of Magento 2.

**Comment by hostep** [comment] 2020-02-06 14:12
Thanks for the report @qsolutions-pl, but this has been reported already a few times before, please use the search functionality of Github before submitting a new issue so that we can prevent having multiple tickets for the same issue, thanks!

Closing as duplicate of https://github.com/magento/magento2/issues/25099

**Closed as completed by hostep** 2020-02-06 14:12 UTC
Labels: Issue: Format is valid, Reported on 2.3.2
