### ISSUE TITLE
Re-validate google reCAPTCHA if user response token expired

### ISSUE THREAD

**Issue by AartiJogiya** [magento/magento2#34469] opened 2021-10-28 12:54 UTC
Google reCAPTCHA has token restrictions that is user response token expires after two minutes and to create new token we need to re-run reCAPTCHA varification. Refer [Google reCAPTCHA document](https://developers.google.com/recaptcha/docs/verify#:~:text=status%20returns%20successful.-,Token%20Restrictions,re%2Drun%20the%20reCAPTCHA%20verification.). On the customer create account page, it should re-run the reCAPTCHA varification in case previous user response token is expired and should not generate an error "Can not resolve reCAPTCHA parameter"

### Preconditions (*)
1. magento 2.4.3, 2.4.3-p1
2. Configure google reCAPTCHA v2-invisible
3. Enable google reCAPTCHA on create new customer account form (Stores > Configuration > Security > Google reCAPTCHA Storefront. 

### Steps to reproduce (*)
1. Go to Create account page in storefront.
2. Fill the form using any existing users email.
3. Submit the form and it will show error message saying "There is already an account with this email address."
4. wait for at least two minutes without refreshing the page and then submit the form with keeping one required field empty.
5. Submit the form again

### Expected result (*)
It should validate reCAPTCHA and if the user response token is expired it should execute reCAPTCHA verification again. 

### Actual result (*)
It posts empty "g-recaptcha-response" value on form submit after reCAPTCHA user response token is expired and therefore logs exception "Can not resolve reCAPTCHA parameter." and also shows error notification saying "Something went wrong with reCAPTCHA. Please contact the store owner".

Error log in exception.log:
main.ERROR: Can not resolve reCAPTCHA parameter. {"exception":"[object] (Magento\\Framework\\Exception\\InputException(code: 0): Can not resolve reCAPTCHA parameter. at /var/www/public_html/vendor/magento/module-re-captcha-ui/Model/CaptchaResponseResolver.php:25)"} []
![create_new_account](https://user-images.githubusercontent.com/40287689/139251970-d733b848-64a8-408e-b1d0-9e83e762d502.png)

**Comment by engcom-Hotel** [comment] 2021-11-02 07:40
Hello @hoangoclan,

Please provide us the steps to reproduce the issue.

Thanks

**Comment by hoangoclan** [comment] 2021-11-03 13:17
Hi @engcom-Hotel ,
I see it appear in exception.log on the product, but I have not been able to reproduce it. I'm just trying to give everyone more information that this issue seems to appear in Magento 2.4.2, reCAPTCHA v3 Invisible on the storefront.

**Comment by Quentin-Sch** [comment] 2021-11-19 16:31
Same on my site. 
On 2 natives Magento 2.4.2 websites with same config
Random..

**Comment by hoangoclan** [comment] 2021-11-20 11:26
Hi @Quentin-Sch , cc @AartiJogiya , @engcom-Hotel 

I have investigated the cause of it.
In very slow internet conditions, the customer can submit the form before the recaptcha is downloaded and rendered. This results in the Recaptcha not being validated in the FO.

In my project, I have disabled the submit button by default and enabled it when the Recaptcha is ready.

Hope it is useful to you.

**Comment by engcom-Hotel** [comment] 2021-12-09 13:08
Hello @AartiJogiya

We have rechecked the issue, but still, we are unable to reproduce it.

@hoangoclan as per your comment, we have tried to reproduce the issue in the slow network by using **Throttling dropdown** in chrome browser and selecting **Slow 3G** option but still, we are unable to reproduce the issue. Please suggest the missing steps.

Thanks

**Comment by nmintcheva** [comment] 2021-12-15 18:30
Hello, I was able to reproduce it with the same exception.log error message as above. The steps I took on my local were to 1. enable reCaptcha v2 invisible and 2. try to submit a message through the contact form.

**Comment by engcom-Hotel** [comment] 2021-12-27 12:44
Hello @nmintcheva,

We have tried to reproduce [these](https://github.com/magento/magento2/issues/34469#issuecomment-995060150) steps as well but still, the issue is not reproducible for us.

Please tell us if we missed anything in order to reproduce the issue.

Thanks

**Comment by engcom-Hotel** [comment] 2022-01-10 05:52
Dear @AartiJogiya,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-01-10 05:52 UTC
Labels: Progress: needs update, Issue: needs update, Reported on 2.4.3-p1

**Comment by b2bdokter** [comment] 2022-01-11 18:27
I ran into this issue 

"Something went wrong with reCAPTCHA. Please contact the store owner." , 


to allow your self access to your backend follow these steps:

1. Run this ONE command from CLI 


`php bin/magento module:disable Magento_ReCaptchaAdminUi Magento_ReCaptchaCheckout Magento_ReCaptchaContact Magento_ReCaptchaCustomer Magento_ReCaptchaFrontendUi Magento_ReCaptchaMigration Magento_ReCaptchaNewsletter Magento_ReCaptchaPaypal Magento_ReCaptchaReview Magento_ReCaptchaSendFriend Magento_ReCaptchaUi Magento_ReCaptchaUser Magento_ReCaptchaValidation Magento_ReCaptchaValidationApi Magento_ReCaptchaVersion2Checkbox Magento_ReCaptchaVersion2Invisible Magento_ReCaptchaVersion3Invisible` 

2. THEN log into the backend , STAY logged in 

3. run below command to re enable captcha

php bin/magento module:enable Magento_ReCaptchaAdminUi Magento_ReCaptchaCheckout Magento_ReCaptchaContact Magento_ReCaptchaCustomer Magento_ReCaptchaFrontendUi Magento_ReCaptchaMigration Magento_ReCaptchaNewsletter Magento_ReCaptchaPaypal Magento_ReCaptchaReview Magento_ReCaptchaSendFriend Magento_ReCaptchaUi Magento_ReCaptchaUser Magento_ReCaptchaValidation Magento_ReCaptchaValidationApi Magento_ReCaptchaVersion2Checkbox Magento_ReCaptchaVersion2Invisible Magento_ReCaptchaVersion3Invisible


4. Navigate in the magento admin panel to STORE->CONFIGURATION->SECURITY and view all recaptcha enties, in my case the API key was not right. 


For more info feel free to contact me on github. 




`
