### ISSUE TITLE
componentGrid/sync 500 Internal Server error angular.min.js

### ISSUE THREAD

**Issue by hocomadvies** [magento/magento2#7032] opened 2016-10-15 14:22 UTC
Hi,

I experience a spinning wheel issue with a 2.0.9 install (through Installatron) when trying to sync the modules with the market place. 
I'm getting http://my_magento2.com/setup/index.php/componentGrid/sync 500 Internal Server error angular.min.js (line 77)

All settings are good for cronjobs and ownership, etc. (tests performed and not giving any errors)

Is there any chance to get that fixed? So I can use the sync option in the Component Manager? At the moment it is not possible to update/ upgrade to a higher version through the Installatron manager, the version 2.0.9 is the only available choice.

**Comment by shanevbg** [comment] 2016-10-15 14:42
This seems to be a duplicate of #6737 so it probably would still be an issue if you were to upgrade.
That said, if you can use the command line, these are the steps I take for a upgrade (other guides seem to miss some points).
Good Luck!
[First command is because Magento overwrites my .htaccess and I have to make sure the settings are correct after]

### DO A BACKUP!!!

`cp .htaccess htaccess.sav`
`sudo -H -u www-data bin/magento maintenance:enable`
`sudo -H -u www-data composer require magento/product-community-edition 2.1.2 --no-update`
`sudo -H -u www-data composer update`
`chmod +x /bin/magento`
`rm -rf var/cache/* var/page_cache/* var/generation/*`
`sudo -H -u www-data bin/magento setup:upgrade`
`sudo -H -u www-data bin/magento setup:di:compile`
`sudo -H -u www-data bin/magento setup:cron:run`
`sudo -H -u www-data bin/magento setup:cron:run`
`cp .htaccess htaccess.mag`
`cp htaccess.sav .htaccess`
`sudo -H -u www-data bin/magento maintenance:disable`

**Comment by hocomadvies** [comment] 2016-10-17 10:26
This is not a solution for my problem. Also I did not use Compose to install Magento2. Anyone with an solution which works for the problem mentioned?

**Comment by veloraven** [comment] 2016-10-18 13:44
@hocomadvies thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please also explain why do you think this issue not to be a duplicate of #6737.

**Comment by hocomadvies** [comment] 2016-10-22 10:02
Hi I decided to upgrade to a higher version on a other server (2.1.2) now the spinning wheel problem has gone. Only end up with other problems instead! So this can be closed and wait for #6737 to be solved

**Comment by veloraven** [comment] 2016-10-25 14:34
@hocomadvies thank you for update.
I'm closing this issue.

**Closed as completed by veloraven** 2016-10-25 14:34 UTC
Labels: Progress: needs update, Component: Setup
