### ISSUE TITLE
Backward compatibility has been lost on Magento\Catalog\Model\ProductRepository class

### ISSUE THREAD

**Issue by davidmolinacano** [magento/magento2#38669] opened 2024-04-26 10:38 UTC
### Summary

I've a module that have a ProductRepository class which extends from the core `Magento\Catalog\Model\ProductRepository` class. We were calling the parent::__construct passing the `Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper` class which was required before Magento 2.4.7 as the 2nd parameter of the constructor, but now it has been removed and the second parameter must be `Magento\Catalog\Api\Data\ProductSearchResultsInterfaceFactory` class instead, thus losing the backward compatibility.

### Examples

![image](https://github.com/magento/magento2/assets/128705267/a0b5860a-6e3a-4622-9fd5-7a6b715d2f7d)

(Tested on Magento 2.4.3 after having removed the initialization helper from the parent::__construct)

### Proposed solution

My proposal is to restore the `Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper` class as the second parameter. Although it's unused as you stated on the changelog, in my opinion it's required to guarantee the backward compatibility.

This bug can be reproduced by installing [our module](https://github.com/doofinder/doofinder-magento2) (version 0.13.13) on a Magento 2.4.7 and then executing a `bin/magento setup:di:compile`

### Release note

Release Line: 2.4.7

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment] 2024-04-26 12:23
Issue was caused by https://github.com/magento/magento2/pull/37868, which actually fixed a bug. Not sure if it will be easy to keep this fix and not break backwards compatibility.
The class is also not marked with `@api`, which means BC can be broken (even though we should really try to avoid it as much as we can)

Just my 2 cents, others are free to give their own opinions though 🙂

**Comment by davidmolinacano** [comment] 2024-04-26 13:34
Thank you very much for the explanation @hostep ! Unfortunately, if this fix cannot be reverted we would need a proper solution for our specific case, because we must keep BC in our module since most of our customers are still using versions lower than 2.4.7, but a few of them are currently using the 2.4.7 too. If someone has any proposal about this issue, I'll be glad to hear it (well, in this case to read it).

**Comment by davidmolinacano** [comment] 2024-04-26 13:54
Unfortunately it didn't work as expected. Even with this fix, the setup:di:compile was still complaining about this. But thank you very much for pointing it, just in case.

**Comment by engcom-Hotel** [comment] 2024-04-29 09:35
Hello @davidmolinacano,

Thanks for the report and collaboration!

By looking into the codebase we are confirming this issue. The changes are Backward incompatible.

Thanks

**Comment by davidmolinacano** [comment] 2024-04-30 11:24
Of course, I'm pasting here the results of the command:

```
# bin/magento setup:di:compile -vvv
Compilation was started.
Interception cache generation... 6/9 [==================>---------]  66% 40 secs 426.0 MiBErrors during compilation:
        Doofinder\Feed\Model\ProductRepository
                Incompatible argument type: Required type: \Magento\Catalog\Api\Data\ProductSearchResultsInterfaceFactory. Actual type: \Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper; File: 
/app/app/code/Doofinder/Feed/Model/ProductRepository.php

Total Errors Count: 1

In Log.php line 92:
                                           
  [Magento\Framework\Validator\Exception]  
  Error during compilation                 
                                           

Exception trace:
  at /app/setup/src/Magento/Setup/Module/Di/Compiler/Log/Log.php:92
 Magento\Setup\Module\Di\Compiler\Log\Log->report() at /app/setup/src/Magento/Setup/Module/Di/Code/Reader/Decorator/Interceptions.php:85
 Magento\Setup\Module\Di\Code\Reader\Decorator\Interceptions->getList() at /app/setup/src/Magento/Setup/Module/Di/App/Task/Operation/InterceptionCache.php:61
 Magento\Setup\Module\Di\App\Task\Operation\InterceptionCache->doOperation() at /app/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php:56
 Magento\Setup\Module\Di\App\Task\Manager->process() at /app/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php:209
 Magento\Setup\Console\Command\DiCompileCommand->execute() at /app/vendor/symfony/console/Command/Command.php:326
 Symfony\Component\Console\Command\Command->run() at /app/vendor/symfony/console/Application.php:1078
 Symfony\Component\Console\Application->doRunCommand() at /app/vendor/symfony/console/Application.php:324
 Symfony\Component\Console\Application->doRun() at /app/vendor/magento/framework/Console/Cli.php:118
 Magento\Framework\Console\Cli->doRun() at /app/vendor/symfony/console/Application.php:175
 Symfony\Component\Console\Application->run() at /app/bin/magento:23

setup:di:compile
```

![image](https://github.com/magento/magento2/assets/128705267/89ff3efc-6898-419a-9797-0c2aaff5ceec)

Even forcing the if with false (just in case) it only takes into account the first statement and ignore the second one:
```

if (false) {
            // Magento < 2.4.7
            parent::__construct(
                $productFactory,
                $initializationHelper,
                $searchResultsFactory,
                $collectionFactory,
                $searchCriteriaBuilder,
                $attributeRepository,
                $resourceModel,
                $linkInitializer,
                $linkTypeProvider,
                $storeManager,
                $filterBuilder,
                $metadataServiceInterface,
                $extensibleDataObjectConverter,
                $optionConverter,
                $fileSystem,
                $contentValidator,
                $contentFactory,
                $mimeTypeExtensionMap,
                $imageProcessor,
                $extensionAttributesJoinProcessor,
                $collectionProcessor,
                $serializer,
                $cacheLimit,
                $readExtensions
            );
        } else {
            // Magento >= 2.4.7
            parent::__construct(
                $productFactory,
                $searchResultsFactory,
                $collectionFactory,
                $searchCriteriaBuilder,
                $attributeRepository,
                $resourceModel,
                $linkInitializer,
                $linkTypeProvider,
                $storeManager,
                $filterBuilder,
                $metadataServiceInterface,
                $extensibleDataObjectConverter,
                $optionConverter,
                $fileSystem,
                $contentValidator,
                $contentFactory,
                $mimeTypeExtensionMap,
                $imageProcessor,
                $extensionAttributesJoinProcessor,
                $collectionProcessor,
                $serializer,
                $cacheLimit,
                $readExtensions
            );
        }
```

**Comment by ihor-sviziev** [comment] 2024-05-09 06:32
@sofia-doofinder, sorry, no updates
As to me, it looks like a bug in the Magento class validation.
I haven't had such issues. 
As workaround, you can do not override constructor and get needed dependencies from object manager. I think that's the only option then unless it's fixed

**Comment by TuVanDev** [comment] 2024-05-09 06:48
@davidmolinacano @sofia-doofinder @hostep @ihor-sviziev The approach of checking the current Magento version and serving the appropriate arguments of the parent method is working as expected.

I have reviewed the corresponding [commit](https://github.com/doofinder/doofinder-magento2/commit/7eb828b02e29f67fa13298b6ec01efdfc50c6885) on the Doofinder repository and tested it in my own environment. During testing, I encountered the following error:
```
Compilation was started.
Repositories code generation... 1/9 [===>------------------------]  11% < 1 sec 119.0 MiB
In ErrorHandler.php line 62:
                                                                                                                                                                                                           
  [Exception]                                                                                                                                                                                              
  Deprecated Functionality: Optional parameter $cacheLimit declared before required parameter $productMetadataInterface is implicitly treated as a required parameter in /var/www/html/vendor/doofinder/d  
  oofinder-magento2/Model/ProductRepository.php on line 65                                                                                                                                                 
                                                                                                                                                                                                           

Exception trace:
  at /var/www/html/vendor/magento/framework/App/ErrorHandler.php:62
 Magento\Framework\App\ErrorHandler->handler() at /var/www/html/vendor/composer/ClassLoader.php:571
 include() at /var/www/html/vendor/composer/ClassLoader.php:571
 Composer\Autoload\includeFile() at /var/www/html/vendor/composer/ClassLoader.php:428
 Composer\Autoload\ClassLoader->loadClass() at n/a:n/a
 class_exists() at /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:134
 Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass() at /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:117
 Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract() at /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:87
 Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList() at /var/www/html/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php:61
 Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation() at /var/www/html/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php:56
 Magento\Setup\Module\Di\App\Task\Manager->process() at /var/www/html/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php:209
 Magento\Setup\Console\Command\DiCompileCommand->execute() at /var/www/html/vendor/symfony/console/Command/Command.php:326
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/symfony/console/Application.php:1078
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Application.php:324
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/magento/framework/Console/Cli.php:118
 Magento\Framework\Console\Cli->doRun() at /var/www/html/vendor/symfony/console/Application.php:175
 Symfony\Component\Console\Application->run() at /var/www/html/bin/magento:23

setup:di:compile
```
You may observe that the error message has changed. The issue was resolved by placing the `$productMetadataInterface` param before the optional params.

I have submitted a pull request to the Doofinder repository to fix this issue. https://github.com/doofinder/doofinder-magento2/pull/317

@davidmolinacano This is my first time hearing about the Doofinder search feature, and it looks great. Keep up the good work!
There is an unused property, `stockRegistry`, in the `Doofinder\Feed\Model\ProductRepository` class. I recommend removing it to optimize your class.

**Comment by sofia-doofinder** [comment] 2024-05-09 10:06
Hello @TuVanDev I'm checking you PR but it didn't work, as @davidmolinacano said the if seems not work at all...

I'm using your branch, and I'm using magento 2.4.3, when I run the comman `setup:di:compile` I got the following error:
![image](https://github.com/magento/magento2/assets/92720455/92dc71bb-4069-4b21-8fce-449277f1d4c9)

So it is saying that expect as required type `\Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper`, however is getting `\Magento\Catalog\Api\Data\ProductSearchResultsInterfaceFactory` 

So it looks like is trying to load the if statment instead of access by the else, becuase is the first statment where is ignored the `initializationHelper`. So, looks like the `if (version_compare($productMetadataInterface->getVersion(), '2.4.7', '>='))` return true, what can't be due to I'm using 2.4.3
![image](https://github.com/magento/magento2/assets/92720455/ab98d96f-e047-43dd-a66b-c50e1dca6ea7)

The weired thing is that if I change the if to `if (false)` it still access by the first clausule beucase I receive the same error:
![image](https://github.com/magento/magento2/assets/92720455/44a3c013-bd4c-4f99-92cd-b504a7c23410)

seems that the if is not workingn as expected because always tries to load the first statment....

**Comment by ihor-sviziev** [comment] 2024-05-09 15:28
@TuVanDev @sofia-doofinder Can you try removing constructor override and try something like this instead?
https://github.com/magento/magento2/issues/30684#issuecomment-722602562

**Comment by sofia-doofinder** [comment] 2024-05-09 15:31
thank you @ihor-sviziev I'm going to check

**Comment by TuVanDev** [comment] 2024-05-10 07:15
Hi @sofia-doofinder , thanks for letting me know. I have reviewed the interception generation code and discovered that the `ConstructorIntegrity` validator class compares arguments between the current class and the parent class when a call `parent::__construct()` occurs.
- https://github.com/magento/magento2/blob/2.4.7/lib/internal/Magento/Framework/Code/Validator/ConstructorIntegrity.php#L88
- https://github.com/magento/magento2/blob/2.4.7/lib/internal/Magento/Framework/Code/Validator/ConstructorIntegrity.php#L85

As a result, the `if else` statements within the `__construct()` method were never reached while the `ConstructorIntegrity` class was validating class constructors.
Therefore, I have implemented @hostep 's solution, which involves removing the `__construct()` method and instantiating the necessary instances. I submitted another pull request to doofinder/doofinder-magento2 repository.

I have another solution, which is to rebuild your `ProductRepository` class based on the `Magento\Catalog\Model\ProductRepository` class without actually extending it. However, this approach has a drawback as it would involve manually implementing any changes made to the `Magento\Catalog\Model\ProductRepository `class into your own class whenever that file is updated.

**Comment by sofia-doofinder** [comment] 2024-05-14 10:18
@TuVanDev thank you for your PR, we've try to upload to magento market but the code sniffer fails with the following reason:

![image](https://github.com/magento/magento2/assets/92720455/19d0b6b6-f33c-480f-b7d4-6b8404dbe63e)

So we can't do on that way... any help please?

**Comment by TuVanDev** [comment] 2024-05-14 10:36
@sofia-doofinder In this case, your team can go with the approach I suggested previously https://github.com/magento/magento2/issues/38669#issuecomment-2104039336

> I have another solution, which is to rebuild your ProductRepository class based on the Magento\Catalog\Model\ProductRepository class without actually extending it. However, this approach has a drawback as it would involve manually implementing any changes made to the Magento\Catalog\Model\ProductRepository class into your own class whenever that file is updated.

Starting from Magento version 2.4.7, the class Magento\Catalog\Model\ProductRepository now includes the implementation of Magento\Framework\ObjectManager\ResetAfterRequestInterface.
- https://github.com/magento/magento2/blob/2.4.7/app/code/Magento/Catalog/Model/ProductRepository.php#L47
- https://github.com/magento/magento2/blob/2.4.6/app/code/Magento/Catalog/Model/ProductRepository.php#L44

To support both older Magento versions and Magento version 2.4.7+, you should avoid using this implementation. Therefore, your class should look like this:
```
<?php
declare(strict_types=1);

namespace Doofinder\Feed\Model;

class ProductRepository implements \Magento\Catalog\Api\ProductRepositoryInterface
{
    // More code goes here

    /**
     * Resets mutable state and/or resources in objects that need to be cleaned after a response has been sent.
     *
     * @return void
     */
    public function _resetState(): void
    {
        $this->instances = [];
        $this->instancesById = [];
    }
}
```

**Comment by engcom-Bravo** [comment] 2024-06-24 10:14
Hello,

Internal team has started to work on it

Thanks

**Comment by engcom-Bravo** [comment] 2024-06-28 05:46
Hi @davidmolinacano,

Thanks for your reporting and collaboration.

we have analysed the issue on the 2.4 develop and installed extension doofinder-magento2 for reproducing the issue. We have found that the issue is not reproducible. I have attached the screenshot for reference.


![Screenshot 2024-06-27 at 2 43 38 PM](https://github.com/magento/magento2/assets/51680745/152018d5-998f-40dd-8ec1-5651743346f2)


Thanks.

**Comment by TuVanDev** [comment] 2024-06-28 06:55
@engcom-Bravo this issue has been confirmed by @engcom-Hotel https://github.com/magento/magento2/issues/38669#issuecomment-2082279938.

The doofinder-magento2 module has resolved this issue by implement a workaround as per my suggestion at https://github.com/magento/magento2/issues/38669#issuecomment-2109859845

If you want to reproduce the issue with that module, you can install version 0.13.13, which didn't apply the fix.

**Comment by hostep** [comment] 2024-06-28 07:05
I still stand by my point from [my first comment](https://github.com/magento/magento2/issues/38669#issuecomment-2079283789), that we should just leave this be and don't attempt to fix this in core Magento.

**Comment by engcom-Bravo** [comment] 2024-06-28 07:19
Hi @davidmolinacano,

@hostep @TuVanDev Thanks for your contribution!!

As per this https://github.com/magento/magento2/issues/38669#issuecomment-2196186106 We are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-28 07:19 UTC
Labels: Issue: Confirmed, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P1, Progress: done, Issue: needs update, Area: Framework, Reported on 2.4.7
