### ISSUE TITLE
Trying update 2.0.7 to 2.1 with Web Setup Wizard

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#5235] opened 2016-06-24 15:43 UTC
## Steps to reproduce

Logged in admin and navigate to `System > Tools > Web Setup Wizard`
## Expected result

Open Web Setup Wizard to upgrade.
## Actual result

Redirected to `/setup/index.php/session/unlogin` with 401 status.

**Comment by andimov** [comment] 2016-07-04 17:02
@rbostan 
Thank you for reporting!
Looks like upgrade is already started.
This issue is still actual?

**Comment by cizgidekiadam** [comment] 2016-07-10 11:46
@andimov 
I have no success to upgrade. So made a clean install.
But at new install, problem still exists. Can not access Web Setup Wizard in 2.1

**Comment by ghost** [comment] 2016-07-10 13:05
Is your docroot `pub`? If so, then this is expected behavior. `pub` and `setup` are on the same level so that no one can run the Web Setup Wizard in production. (We recommend you set your Magento docroot to `pub` in production.)

To work around it, set your docroot to the Magento install dir and the wizard should work.

**Comment by cizgidekiadam** [comment] 2016-07-10 13:14
Docroot is not /pub. 

Also if it is, in 2.1, "The Web Setup Wizard now works when Magento is installed in /pub. [GITHUB-4159](https://github.com/magento/magento2/issues/4159)"

**Comment by ghost** [comment] 2016-07-10 22:24
Sorry, I didn't know that. What web server are you using?
Is the `setup` directory readable by the web server user?

**Comment by cizgidekiadam** [comment] 2016-07-15 09:34
/setup is readable and server is CentOS with apache

**Comment by NadiyaS** [comment] 2016-09-02 08:33
Hi @rbostan ,
seems like your session was expired or value of 'admin/security/session_lifetime' less than 60. To check this value go to Stores > Settings > Configuration > Advanced > Admin > Security > Admin Session Lifetime. Default value for session lifetime is 900.

**Comment by cizgidekiadam** [comment] 2016-09-08 14:39
Hi @NadiyaS 
I don't think so.
I have tried that right after the login. So it was not took 20secs.

But doesn't matter, I have made a clean install to 2.1 and update 2.1.1 via composer.
It is working fine now.

**Comment by NadiyaS** [comment] 2016-09-08 20:01
Ok, so I close this issue as not reproducible. Feel free to reopen it if you encounter with the same problem.

**Closed as completed by NadiyaS** 2016-09-08 20:01 UTC
Labels: bug report, Progress: needs update, Component: Setup
