### ISSUE TITLE
Currency rates not updated by crontab

### ISSUE THREAD

**Issue by jcourtei** [magento/magento2#18580] opened 2018-10-13 08:51 UTC
### Preconditions (*)

Version 2.2.6, probably since version 2.2.4 (Community Edition).

### Steps to reproduce (*)

Base store has only one allowed currency (EUR). So EUR is the base currency.
French store uses base store values.
English store has 4 allowed currencies (EUR, CAD, USD, GBP).
Crontab configured to update currency rates everyday.

### Expected result (*)

Currency rates should be updated everyday.

### Actual result (*)

Crontab only updates currency rate EUR to EUR (which is useless).

I found that this issue comes from Magento\Directory\Model\CurrencyConfig which was created in version 2.2.4, in function getConfigCurrencies :
`    public function getConfigCurrencies(string $path)
    {
       $result = $this->appState->getAreaCode() === Area::AREA_ADMINHTML
            ? $this->getConfigForAllStores($path)
            : $this->getConfigForCurrentStore($path);
        sort($result);
        return array_unique($result);
    }
`
Crontab should update currency rates like in admin panel, so the code should be :
`    public function getConfigCurrencies(string $path)
    {
        $result = $this->appState->getAreaCode() === Area::AREA_ADMINHTML
				|| $this->appState->getAreaCode() === Area::AREA_CRONTAB
            ? $this->getConfigForAllStores($path)
            : $this->getConfigForCurrentStore($path);
        sort($result);
        return array_unique($result);
    }
`

**Comment by magento-engcom-team** [comment] 2018-10-13 08:51
Hi @jcourtei. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jcourtei do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-10-31 18:21
Hi @denispapec. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2018-10-31 21:01
@denispapec Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96042`, `MAGETWO-96043` were created

**Comment by denispapec** [comment] 2018-10-31 21:36
Hi, 
fixes for both 2.2 and 2.3 release lines are ready for review.

**Comment by magento-engcom-team** [comment] 2019-02-12 17:40
Hi @jcourtei. Thank you for your report. 
The issue has been fixed in magento/magento2#18981 by @denispapec in 2.3-develop branch
Related commit(s):
 - [c0df2e42bdd4d30c1db58d62bfba2b2781531c27](https://github.com/magento/magento2/commit/c0df2e42bdd4d30c1db58d62bfba2b2781531c27)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2019-02-12 17:40 UTC
Labels: Issue: Ready for Work, Component: Cron, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Directory

**Comment by magento-engcom-team** [comment] 2019-04-15 15:20
Hi @jcourtei. Thank you for your report. 
The issue has been fixed in magento/magento2#18980 by @denispapec in 2.2-develop branch
Related commit(s):
 - [737f3963a541ee879ffa22739e81c5b4dc5e934e](https://github.com/magento/magento2/commit/737f3963a541ee879ffa22739e81c5b4dc5e934e)

The fix will be available with the upcoming 2.2.9 release.
