### ISSUE TITLE
Getting error on adding new review from admin panel

### ISSUE THREAD

**Issue by mohammadzakir** [magento/magento2#20122] opened 2019-01-08 13:13 UTC
### Preconditions (*)

1. Magento 2.3.0 with sample data
2. Php Version 7.2

### Steps to reproduce (*)

1. Login to admin panel
2. On left navigation goto Marketing-> User Content-> Reviews
3. Click New Review
4. Click any product for review

### Expected result (*)

1. No error msg should come

### Actual result (*)

1. Error message showing : A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.

![image](https://user-images.githubusercontent.com/43291220/50832778-3b63ac00-1375-11e9-9142-7a072ad77608.png)

**Comment by magento-engcom-team** [comment] 2019-01-08 13:13
Hi @mohammadzakir. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mohammadzakir do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-08 13:13
Hi @GovindaSharma. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-01-08 13:17
@GovindaSharma Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97491` were created

**Comment by milindsingh** [comment] 2019-01-11 07:46
#19623 already created.

**Closed as completed by milindsingh** 2019-01-11 07:46 UTC
Labels: Issue: Ready for Work, duplicate, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Review

**Comment by magento-engcom-team** [comment] 2019-01-29 03:48
Hi @mohammadzakir. Thank you for your report. 
The issue has been fixed in magento/magento2#20146 by @suneet64 in 2.3-develop branch
Related commit(s):
 - [da809e36e486ccaa02217b2b1b31df6a01745f93](https://github.com/magento/magento2/commit/da809e36e486ccaa02217b2b1b31df6a01745f93)
 - [130f1ae59221964dd6c74ebf0545828cbed9a583](https://github.com/magento/magento2/commit/130f1ae59221964dd6c74ebf0545828cbed9a583)
 - [eed3bc376b8afa124effb1870fd2ab20ac433b14](https://github.com/magento/magento2/commit/eed3bc376b8afa124effb1870fd2ab20ac433b14)

The fix will be available with the upcoming 2.3.1 release.
