### ISSUE TITLE
Duplicate Line Item for SKU on Order

### ISSUE THREAD

**Issue by Jedi88** [magento/magento2#30342] opened 2020-10-05 08:33 UTC
Magento 2.3.4 version

We are finding the same SKU appearing on a different line item on the sales/orders. This is causing issues with our integration and sales processing.

Behaviour - add SKU 1234 to cart then add 5679 to cart then add SKU 1234 to cart and checkout

We then see row 1 - 1234 , row 2 , 5679 , row 3 1234

**Comment by ecompleteClem** [comment] 2020-10-05 08:43
## Summary:

When adding configurable product variants to cart, some of these items are not being merged correctly as a single line item. This causes issues later down the line when submitting order / quote information to external webservices.

## Information on our environment:

Magento 2.3.5-p1, PHP 7.3, MySQL 5.7, NGINX, Apache. Digital Ocean Droplet. SalesLayer PIM + Extension installed and sync. 

## Steps to Reproduce

Create a configurable product with 3X Variants for Colour + Size. 

Add Variant 1 (Blue / Medium) to cart.
Add Variant 2 (Red / Small) to cart.
Add Variant 1 (Blue / Medium) to cart.

Variant 1 shows up twice in cart + order summary / quote + order objects.

Expected and Actual Results:

Variant 1 should show up with QTY 2 and not individual line items.

**Comment by krishprakash** [comment] 2020-10-10 06:34
#dmcdindia2020

**Comment by krishprakash** [comment] 2020-10-10 06:35
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment] 2020-10-10 07:51
Hi @Jedi88 @ecompleteClem , Not able to reproduce the issue as provided steps by you.

![image](https://user-images.githubusercontent.com/46617848/95648319-db72da00-0af3-11eb-8090-2213ceed642f.png)

![image](https://user-images.githubusercontent.com/46617848/95648333-ee85aa00-0af3-11eb-9d51-b5343a7f23df.png)

![image](https://user-images.githubusercontent.com/46617848/95648381-33a9dc00-0af4-11eb-883c-d23a752f4c69.png)

Feel free to reopen the issue if you confirm that issue is reproduce on 2.4-develop instance

Thanks!!

**Closed as completed by krishprakash** 2020-10-10 07:51 UTC
Labels: Issue:  Cannot Reproduce, Progress: done, Event: dmcdindia2020, Reported on 2.3.4

**Comment by afzelarshad13** [comment] 2023-04-09 20:42
> Magento 2.3.4 version
> 
> We are finding the same SKU appearing on a different line item on the sales/orders. This is causing issues with our integration and sales processing.
> 
> Behaviour - add SKU 1234 to cart then add 5679 to cart then add SKU 1234 to cart and checkout
> 
> We then see row 1 - 1234 , row 2 , 5679 , row 3 1234

where you able to identify the the issue, why this happens?
