### ISSUE TITLE
[Performance] Slow product edit page with big amount of custom options

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#29409] opened 2020-08-05 13:43 UTC
### Preconditions (*)
1. Magento 2.3.5-p2 or 2.4-develop

### Steps to reproduce (*)
1. Create simple product  OR  import following file:
[export_catalog_product_20200805_133448.zip](https://github.com/magento/magento2/files/5028739/export_catalog_product_20200805_133448.zip)
- Add 8 custom options, each of them with option type "Drop-Down", values - 12 month names (Jan - Dec)
![image](https://user-images.githubusercontent.com/1873745/89418561-e64a7080-d738-11ea-8278-369844312a5d.png)
![image](https://user-images.githubusercontent.com/1873745/89418655-0712c600-d739-11ea-86e2-eb5f42d455e5.png)
-  Save the product
2. Open "Cusomizable options" section

### Expected result (*)
1. Browser should load custom options quite fast, 1-2 seconds.

### Actual result (*)
1. Browser becomes really crazy with high CPU load, it loads just this section for at least **5 seconds** and whole page is quite slow during load.

Here is performance profile from Google Chrome extension: 
[Profile-20200805T162549.zip](https://github.com/magento/magento2/files/5028701/Profile-20200805T162549.zip)

### Use case
We would like to provide our customers an ability to customize amount and colors of stones on the product (up to 8 stones, in example each color named as month for simplicity of example).

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ihor-sviziev** [comment] 2020-09-04 06:20
Seems like following commit might also improve performance for the custom options: https://github.com/magento/magento2/commit/05fce8b29a33b047f7726e4b2a180811d44c7a6d
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-09-04 06:20
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-09-04 06:22
Hi @ihor-sviziev, here is your [Magento instance](https://i-29409-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29409-2-4-develop.instances.magento-community.engineering/admin_43de](https://i-29409-2-4-develop.instances.magento-community.engineering/admin_43de)
Login: `46f2383a` Password: `2877f23b4396`
Instance will be terminated in up to 3 hours.

**Comment by ihor-sviziev** [comment] 2020-09-04 06:30
Just checked - unfortunately it's not fixed the issue

**Comment by ihor-sviziev** [comment] 2021-01-29 04:59
Still actual

**Comment by magento-engcom-team** [comment] 2021-01-29 08:34
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40673` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ihor-sviziev** [comment] 2021-04-15 14:01
pls not close it

**Comment by ksenia-zlotin** [comment] 2021-04-26 13:40
Hello, is there an update on internal ticket MC-40673? I am looking for a solution too - experiencing performance issue in the admin panel for products with many checkbox / select custom options. Additional dependencies cause more slowness.

**Comment by ihor-sviziev** [comment] 2021-09-25 21:07
Keep it open

**Comment by onlinebizsoft** [comment] 2021-10-04 14:54
I have same problem. Magento backend is crazy slow. 
I also saw a very serious bug with customizable option price #34003 do you get the same @ihor-sviziev ?

**Comment by Silarn** [comment] 2022-07-21 23:03
I would like to also state that we have this issue with large bundle products, essentially configurable servers. Any improvement to the performance would be appreciated.

**Comment by pmonosolo** [comment] 2022-09-01 18:24
It it looks like it's a javascript loading error. The server itself (if looking at HTOP) does not get loaded. The problem is somewhere in the javascript listeners or something JS related.

The more options you add to Bundle Product for example, the longer the page takes to load. 

This definitely needs improvement. 

Also the Add Option listeners are not passive. Chrome complains:

"[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive."

**Comment by pmonosolo** [comment] 2022-09-01 18:24
@ihor-sviziev have you had any success fixing this issue?

**Comment by pmonosolo** [comment] 2022-09-01 18:45
3 minutes to render a page:

![image](https://user-images.githubusercontent.com/66754347/187988843-6caeeba1-c77a-4fa4-b661-4669c06c7606.png)


![image](https://user-images.githubusercontent.com/66754347/187988882-f091f8b3-559e-4677-b4c0-a3095b669f4e.png)

![image](https://user-images.githubusercontent.com/66754347/187988907-26c2e777-909e-461d-8ee0-ae8ae5720c78.png)

It looks like dom-observer.min.js is taking up the whole time:

![image](https://user-images.githubusercontent.com/66754347/187989222-e79239b1-4cfe-44fb-bd82-02a54a1d1aec.png)


formChangesLists is the biggest issue:
![image](https://user-images.githubusercontent.com/66754347/187989432-afbed111-a665-4412-843a-f8040e227ea6.png)


![image](https://user-images.githubusercontent.com/66754347/187989549-ec798d34-3ffc-4957-8b5d-28a8cbe4152a.png)

**Comment by ihor-sviziev** [comment] 2022-09-01 18:50
@pmonosolo, I don’t have any solution for this issue. But if you have it - please share

**Comment by pmonosolo** [comment] 2022-09-01 20:55
@ihor-sviziev 

Try this:
https://github.com/magento/magento2/issues/34158
https://stackoverflow.com/questions/60357083/does-not-use-passive-listeners-to-improve-scrolling-performance-lighthouse-repo

Put this code at the end of jquery.js before the return:
pub\static\adminhtml\Magento\backend\en_US\jquery.js

    jQuery.event.special.touchstart = {
        setup: function( _, ns, handle ) {
            this.addEventListener("touchstart", handle, { passive: !ns.includes("noPreventDefault") });
        }
    };
    jQuery.event.special.touchmove = {
        setup: function( _, ns, handle ) {
            this.addEventListener("touchmove", handle, { passive: !ns.includes("noPreventDefault") });
        }
    };
    jQuery.event.special.wheel = {
        setup: function( _, ns, handle ){
            this.addEventListener("wheel", handle, { passive: true });
        }
    };
    jQuery.event.special.mousewheel = {
        setup: function( _, ns, handle ){
            this.addEventListener("mousewheel", handle, { passive: true });
        }
    };


This seems to improve things.

**Comment by Nuranto** [comment] 2022-09-23 19:55
If someone is brave enough to dig in, I guess that a start would be to replace Array functions, especially in dom-observer.js

See https://leanylabs.com/blog/js-forEach-map-reduce-vs-for-for_of/

**Comment by mariogobos** [comment] 2022-11-18 09:35
Hello, i've same problem on my magento 2.4.4 my product have 1500 custom options and load time is 7sec. Do you have find a solution? Thanks a lot

**Comment by ihor-sviziev** [comment] 2023-05-08 15:01
@densen45, could you please create a Pull Request with your changes? So that we can run automated tests on top of them

**Comment by densen45** [comment] 2023-05-09 05:45
@magento I am working on this

**Closed as completed** 2023-10-20 13:42 UTC
Labels: Issue: Confirmed, Component: Ui, Reproduced on 2.4.x, Priority: P3, Severity: S3, Triage: Performance, Progress: done, Reported on 2.4.x, Reported on 2.3.5-p2, Area: Performance
