### ISSUE TITLE
Something went wrong with processing the default view and we have restored the filter to its original state

### ISSUE THREAD

**Issue by Autobadges** [magento/magento2#35814] opened 2022-07-26 01:23 UTC
### Preconditions and environment

- Magento version 2.3.4
When I log into admin panel > Product I get this error:

Something went wrong with processing the default view and we have restored the filter to its original state

And I cannot alter or view ANY products

### Steps to reproduce

Log in on backend
Go to products

### Expected result

I am able to alter current products

### Actual result

Something went wrong with processing the default view and we have restored the filter to its original state

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2022-07-27 06:46
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment] 2022-07-27 14:28
Hi @Autobadges ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue.
1.we can able to alter current products 

<img width="935" alt="50" src="https://user-images.githubusercontent.com/51681379/181272985-370fd140-0438-4249-9669-5f5bfcf60e15.png">

2. we can view all products

<img width="922" alt="51" src="https://user-images.githubusercontent.com/51681379/181273253-a5aa151d-5f0e-4155-807f-e3d489c94571.png">

Regards,

**Comment by Quazz** [comment] 2022-07-29 15:28
I actually find this can happen for certain thumbnails. In my case the offending function was located here: 

https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Image/Adapter/Gd2.php#L382

That problem is easily resolved by
`-            if ($transparentIndex >= 0) {
+            $palletSize = imagecolorstotal($imageResource);
+            if ($transparentIndex >= 0 && $transparentIndex < $palletSize) {`

If you have ImageMagick installed and the PHP Imagick extension then you can change the image adapter in admin settings to ImageMagick instead of GD2. Then you can see if this is the error plagueing you. (or you can check var/system.log of course)

**Comment by engcom-Bravo** [comment] 2022-08-09 06:58
Hi @Autobadges 

This is an intermittent issue which cannot be reproduced frequently on 2.4-develop branch. However  this has been confirmed [here:](https://github.com/magento/magento2/issues/35466)

 We are closing this issue as duplicate. Kindly move onto this issue for latest updates / solutions on the same

**Closed as completed by engcom-Bravo** 2022-08-09 06:58 UTC
Labels: duplicate, Issue: needs update
