### ISSUE TITLE
Magento 2.4.6 - create order page in admin - move items from shopping cart issue

### ISSUE THREAD

**Issue by integratornet** [magento/magento2#37538] opened 2023-05-24 22:48 UTC
### Preconditions and environment

- Magento version: Magento 2.4.6
![magento_move_items_from_cart_issue](https://github.com/magento/magento2/assets/134559191/4e4567cf-0151-472e-9dda-36ff8e67fd5d)

### Steps to reproduce

When creating an order in admin and you move an item from the shopping cart to the list of items to order, that item is not getting deleted from the cart.

**Steps to reproduce**

- Create an order from admin.
- Add products and move the products to SHOPPING CART
- Again move products to Order.
- Put the items back into the cart.

### Expected result

The item moved from shopping cart to the list of items to order should get deleted from the shopping cart.

### Actual result

The item is not getting deleted from the shopping cart.

### Additional information

https://github.com/magento/magento2/assets/51680745/15766270-0701-4067-9c0d-54508c6a2169

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-05-25 06:40
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-05-25 13:16
HI @integratornet,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

**Steps to reproduce**

When creating an order in admin and you move an item from the shopping cart to the list of items to order, that item is not getting deleted from the cart.


Product getting deleted when we click on **UPDATE CHANGES**.



https://github.com/magento/magento2/assets/51680745/30368e2d-6ef7-45ce-883a-36e7d6298a61



https://github.com/magento/magento2/assets/51680745/e54895e9-f860-47da-a411-0ff72422ccd8










Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-05-26 07:18
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-05-26 12:34
Hi @integratornet,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the attached video.

**Steps to reproduce**

1.Create an order from admin.
2.Add products and move the products to **SHOPPING CART**
3.Again move products to Order.
4.Put the items back into the cart.

After moving items back to shopping cart there are no items in the cart and when we try to create an order for same customer Items in the **SHOPPING CART** have doubled.

https://github.com/magento/magento2/assets/51680745/15766270-0701-4067-9c0d-54508c6a2169


Hence Confirming the issue.

Thanks.

**Comment by rostilos** [comment] 2023-05-27 16:49
@magento I am working on this

**Closed as completed** 2024-02-24 14:20 UTC
Labels: Issue: Confirmed, Component: Ui, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Order, Reported on 2.4.6
