### ISSUE TITLE
Upgrade to Magento 2.4.4: Customer not logged in automatically after click confirmation link

### ISSUE THREAD

**Issue by DeepShah2511** [magento/magento2#35776] opened 2022-07-17 07:08 UTC
### Preconditions and environment

- Magento version 2.4.4
- Upgrading from Magento v2.4.1 to v2.4.4.

### Steps to reproduce

1. go to customer/account/create link
2. created customer account successfully 
3. get confirmation email and click on confirmation link
4. go to customer/account/login page 
5. enter the email and password
6. giving "Invalid form key error" and stay on the login page

### Expected result

customer should successfully logged in after confirmation.

### Actual result

customer could not logged in to account and it will be redirected to the customer/account/login.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-07-19 12:23
Hi @DeepShah2511 ,
Thank you for reporting and collaboration. Verified the issue by upgrading from 2.4.1 project-community-edition to 2.4.4 and 2.4-develop branch as well but could not reproduce the issue with below steps performed:
1. Created customer account from both front-end and admin - customers page
2. New Account email triggered when created from front end as below:
![image](https://user-images.githubusercontent.com/60198231/179749239-de60159a-dbac-422d-85f4-749b0f0c7fad.png)

4. Clicked on the link and enter username, password - User logged in successfully and no errors displayed.
5. Below mail triggered when created from admin - reset password using below link and login - User logged in successfully and no error message displayed.
![image](https://user-images.githubusercontent.com/60198231/179749129-4ee8fb05-54ae-494b-87cd-2626899389e3.png)
Kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you

**Comment by DeepShah2511** [comment] 2022-07-21 06:08
Hi @engcom-November I want to say that in this issue sometimes customer can not logged in after registration so what is the causes for that issues in magento-2.4.4. because i am also facing that sometimes i have logged in using not strong password then also it will not successfully logged in to the account.

**Comment by engcom-November** [comment] 2022-07-26 12:30
Hi @DeepShah2511 ,
I verified the issue again on Magento 2.4.4 project-community-edition by setting medium password(Not a strong password) but still unable to reproduce the issue.
User is able to login from emails and able to reset password from password reset link as well.
User is able to login to UI from account sign in page as well.
Can you please check if any 3rd party extensions/modules enabled is causing this issue and also Magento [system requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) required for 2.4.4 and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-08-09 06:13
Hi @DeepShah2511 ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-08-09 06:13 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
