### ISSUE TITLE
magento 2.2.6 admin controller action show cache response for few seconds

### ISSUE THREAD

**Issue by vaseemishak** [magento/magento2#19065] opened 2018-11-05 10:55 UTC
I am wokring on dev environment ,All cache are disable and developer mode is On , when i hit by custme module action
i get desired page , but when i add var_dump() and die , the page still show old response , after resfreshing the page for about 5-6 times i get desired vardump ouput , same happen i removed my vardump the page still show vardump response , after few resfresh the desired output is shown.

After some friends suggestions i find that the page refreshing was nothing to do with admin action cache issue , thier was some time of cache period , mean if make changes and refresh page 20 times nothing happens , but if wait for 30 sec and refresh the page the desired output showup,

so is there any cache for specific time interval on admin actions etc ?
Note : all the cache are disabled

### Preconditions (*)
magento 2.2.6

### Steps to reproduce (*)
admin controller action response from cache , just do some changes var_dump etc

### Expected result (*)
when file changes new changes must be appeard

### Actual result (*)
Old response shows even after file changes.

**Comment by magento-engcom-team** [comment] 2018-11-05 10:56
Hi @vaseemisaac. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@vaseemisaac do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment] 2018-11-05 14:44
There is no cache used for admin area responses. Also, var_dumping is not a proper way of debug.

GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.

**Comment by magento-engcom-team** [comment] 2018-11-05 14:44
Hi @orlangur. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Closed as completed** 2018-11-05 14:44 UTC
Labels: Issue:  Cannot Reproduce, non-issue, Issue: Format is valid

**Comment by vaseemishak** [comment] 2019-01-16 13:19
my bad it was opcache which was enable on my dev encvireonment, after disabling is thier is no cache
