### ISSUE TITLE
Forgotten password link -> HTTP 500 error when you have added a new required phone such as phone number to the customer account

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#25465] opened 2019-11-04 15:24 UTC
### Preconditions (*)
1. Magento 2.3.3

### Steps to reproduce (*)
1. Make telephone number a required field in customer accounts
2. Goto forgotten password, enter your e-mail address of a customer who has not entered a phone number yet
3. When you receive the e-mail, click on the forgotten password link in the email
4. Land on magento with a 500 error page

### Expected result (*)
1. Customer able to reset their password

### Actual result (*)
1. HTTP 500 error (i.e. a crash)
2. See error:
```
2019/10/30 16:47:31 [error] 4144#4144: *2619971 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Magento\Eav\Model\Attribute\Data\Text::validateLength() must be of the type string, null given, called in /var/www/vhosts/xx-uk2/releases/20191029062907/vendor/magento/module-eav/Model/Attribute/Data/Text.php on line 80 and defined in /var/www/vhosts/xx-uk2/releases/20191029062907/vendor/magento/module-eav/Model/Attribute/Data/Text.php:141
Stack trace:
#0 /var/www/vhosts/xx-uk2/releases/20191029062907/vendor/magento/module-eav/Model/Attribute/Data/Text.php(80): Magento\Eav\Model\Attribute\Data\Text->validateLength(Object(Magento\Customer\Model\Attribute\Interceptor), NULL)
#1 /var/www/vhosts/xx-uk2/releases/20191029062907/vendor/magento/module-eav/Model/Validator/Attribute/Data.php(131): Magento\Eav\Model\Attribute\Data\Text->validateValue(NULL)
#2 /var/www/vhosts/xx-uk2/releases/20191029062907/vendor/magento/framework/Validator/Constraint.php(54): Magento\Eav\Model\Validator\Attribute\Data->isValid(Object(Magento\Customer\Model\" while reading response header from upstream, client: 127.0.0.1, server: xx.co.uk, request: "GET /customer/account/createPassword/?token=mB8rxC6lzPbuFPXIueoiVFERMw7hO6n7 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "www.xx.co.uk"
2019/10/30 16:49:13 [error] 4145#4145: *2620134 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Magento\Eav\Model\Attribute\Data\Text::validateLength() must be of the type string, null given, called in /var/www/vhosts/xx-uk2/releases/20191029062907/vendor/magento/module-eav/Model/Attribute/Data/Text.php on line 80 and defined in /var/www/vhosts/xx-uk2/releases/20191029062907/vendor/magento/module-eav/Model/Attribute/Data/Text.php:141
Stack trace:
#0 /var/www/vhosts/xx-uk2/releases/20191029062907/vendor/magento/module-eav/Model/Attribute/Data/Text.php(80): Magento\Eav\Model\Attribute\Data\Text->validateLength(Object(Magento\Customer\Model\Attribute\Interceptor), NULL)
#1 /var/www/vhosts/xx-uk2/releases/20191029062907/vendor/magento/module-eav/Model/Validator/Attribute/Data.php(131): Magento\Eav\Model\Attribute\Data\Text->validateValue(NULL)
#2 /var/www/vhosts/xx-uk2/releases/20191029062907/vendor/magento/framework/Validator/Constraint.php(54): Magento\Eav\Model\Validator\Attribute\Data->isValid(Object(Magento\Customer\Model\" while reading response header from upstream, client: 127.0.0.1, server: xx.co.uk, request: "GET /customer/account/createPassword/?token=mB8rxC6lzPbuFPXIueoiVFERMw7hO6n7 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "www.xx.co.uk
```

**Comment by engcom-Charlie** [comment] 2019-11-05 12:35
Hello @craigcarnell 

We are not able to reproduce this issue on the latest 2.3-develop branch & on 2.3.3(composer version) by provided steps.

**Testing scenario:**
**Case 1:**
1. From the Storefront, I have created a New Customer
2. In Admin Panel, I have set the Show Telephone to Required
![image](https://user-images.githubusercontent.com/51680850/68207526-ca624480-ffd7-11e9-9661-a1f27ead2777.png)
3. From the Storefront, i tried to recover the forgotten password
![image](https://user-images.githubusercontent.com/51680850/68207560-d948f700-ffd7-11e9-93c5-d0d43dd56732.png)
4. Opened the Set a new password link from email
**Result:**
Page opened without errors
![image](https://user-images.githubusercontent.com/51680850/68207627-fd0c3d00-ffd7-11e9-962d-c7f7a2bd6363.png)

**Case 2:**

1. In Admin Panel, I have set the Show Telephone to Required
2. From the Storefront, I have created a New Customer
3. Set Billing address & Shipping address (with phone number)
4. Go to database and delete telephone from `customer_address_entity` table
![image](https://user-images.githubusercontent.com/51680850/68207945-c71b8880-ffd8-11e9-8a7c-be2aaec68fe7.png)
5. From the Storefront, i tried to recover the forgotten password
![image](https://user-images.githubusercontent.com/51680850/68207560-d948f700-ffd7-11e9-93c5-d0d43dd56732.png)
6. Opened the Set a new password link from email
**Result:**
Page opened without errors
![image](https://user-images.githubusercontent.com/51680850/68207627-fd0c3d00-ffd7-11e9-962d-c7f7a2bd6363.png)

So i have to close this issue.
If you have any updates please re-open and update.

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-11-05 12:35 UTC
Labels: Issue: Format is valid
