### ISSUE TITLE
[2.3] Importing images doesn't work with links

### ISSUE THREAD

**Issue by RaphaelBronsveld** [magento/magento2#20348] opened 2019-01-16 16:12 UTC
### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.1.25

### Steps to reproduce (*)

1. Go to systems -> Data Transfer -> Import and select products.
2. Download sample file and just import this file. This should work fine. (Validation + import)
3. Add columns for images: base_image,small_image,thumbnail_image and a image for these columns. For example: i used this image https://laurentvandessel.be/wp-content/uploads/2014/03/placeholder-750x451.png
4. Validation works fine, import gives me `Imported resource (image) could not be downloaded from external resource due to timeout or access permissions in row(s): 1`.

### Expected result (*)

1. I expect no errors and images to be linked to the product. 

### Actual result (*)

1. ![screenshot 2019-01-16 at 16 50 20](https://user-images.githubusercontent.com/42035462/51260830-679fae00-19af-11e9-8ed6-ae81820dcad4.png)
2. Image isn't linked to product.

### Further Debugging (*)
Magento/CatalogImportExport/Model/Import/Uploader.php , I noticed some changes with how Magento handles file uploads. It seems that the variable $filePath is set twice (L: 184 & L:191), second time the filePath is set; it also uses the $filePath variable again.

- Value for $filePath (L: 184) (with example image I used above): pub/media/import/placeholder-750x451.png
- Value for $filePath (L:191) pub/media/import/placeholder-750x451.pngplaceholder-750x451.png

Image from the first value exists, second obviously doesn't. Function _setUploadFile will fail because it will throw an Exception because the image doesn't exist.

**Comment by magento-engcom-team** [comment] 2019-01-16 16:12
Hi @RaphaelBronsveld. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@RaphaelBronsveld do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-16 16:58
Hi @milindsingh. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by milindsingh** [comment] 2019-01-16 17:05
https://github.com/magento/magento2/pull/20127

**Closed as completed by milindsingh** 2019-01-16 17:05 UTC
Labels: Fixed in 2.3.x, Issue: Format is valid

**Comment by RaphaelBronsveld** [comment] 2019-01-17 09:14
Ah my bad. I tried several keywords to find an issue related to this, but couldn't find any. Thanks!

**Comment by marco7319** [comment] 2019-08-03 23:00
i have this problem wtih magento 2.3.2, it's possible ?

**Comment by VanArmenia** [comment] 2020-01-29 13:24
I also have this problem with 2.3.2
