### ISSUE TITLE
Asynchronous mail sending does not use store language, mails are sent in en_US instead

### ISSUE THREAD

**Issue by heldchen** [magento/magento2#6511] opened 2016-09-06 17:46 UTC
### Preconditions
1. ce 2.1.1
2. one store view, using locale de_DE with some german translations for the order confirmation mail. (the actual language is irrelevant as long as there are translations other than en_US so that the problem is shown)
### Steps to reproduce
1. enable asynchronous mail sending
2. create an order in the frontend
3. wait for next cron run and check the order confirmation mail
### Expected result
1. order confirmation mail is in the language de_DE
### Actual result
1. order confirmation mail is in the language en_US

when turning off asynchronous mail sending, the mail is sent in the correct language, in our case in german. asynchronous mail sending does not seem to be setting the app store context to the correct store.

**Comment by ktruehl** [comment] 2016-09-07 12:13
The problem is that when executing cron or running a command from the command line, the renderer is not set correctly on the `\Magento\Framework\Phrase`, i.e. the method `public static function setRenderer(RendererInterface $renderer)` is not called with the renderer as defined by the `di.xml` files.

Usually this is done by `Magento\Framework\App\Area` in the `protected function _initTranslate()` method.

Find attached a patch, that gets the area from the `AreaList` and calls the load method with the correct part parameter.

[load_translate_part_of_frontend_area_in_app_emulation-vendor_modulestore_model_app_emulation.diff.zip](https://github.com/magento/magento2/files/459025/load_translate_part_of_frontend_area_in_app_emulation-vendor_modulestore_model_app_emulation.diff.zip)

**Comment by heldchen** [comment] 2016-09-07 16:38
affected are as @ktruehl mentioned all mails generated by cron / from a command line function

**Comment by sevos1984** [comment] 2016-09-08 15:24
Thanks for reporting, internal ticket created MAGETWO-58198

**Comment by SchumacherFM** [comment] 2016-12-07 14:41
Same here

**Comment by mrfroasty** [comment] 2016-12-21 14:49
@ktruehl
Thanks!

**Comment by bh-ref** [comment] 2016-12-28 10:22
this issue seems still present in CE 2.1.3

**Comment by bh-ref** [comment] 2017-02-21 09:18
issue is still present in CE 2.1.4, but https://github.com/magento/magento2/pull/8413 will likely fix it in a future release.

**Comment by magento-engcom-team** [comment] 2017-09-21 10:10
@heldchen, thank you for your report.
The fix for this issue is already available in the develop branch and upcoming 2.2.0 release. See https://github.com/magento/magento2/pull/8413.

**Closed as completed by magento-engcom-team** 2017-09-21 10:10 UTC
Labels: Issue: Ready for Work, bug report, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
