### ISSUE TITLE
GraphQl customer order fatal error in Enterprise version

### ISSUE THREAD

**Issue by abdel-aouby** [magento/magento2#36682] opened 2022-12-29 16:01 UTC
### Preconditions and environment

- Magento version: Adobe Commerce ver. 2.4.4
- The issue is only in Enterprise version

### Steps to reproduce

1- create order with bundle product as an authentificated customer
2- use graphql customer order to retrieve data of the customer order
e.g:
`query CustomerOrder($order_id: String!) {
    customer{
        orders(filter: {
            number: {
                eq: $order_id
            }
        })
        {
            items {
                number
                items {
                ...on BundleOrderItem {
                    bundle_options {
                        label
                    }
                } 
                product_name
                product_sku
            }
        }
    }
    }
}`

### Expected result

order detail are retrieved

### Actual result

`[2022-12-29T15:18:44.588471+00:00] report.ERROR: implode(): Argument 2 ($array) must be of type ?array, string given

GraphQL (13:21)
12:                 ...on BundleOrderItem {
13:                     bundle_options {
                        ^
14:                         label
 [] []
`

### Additional information

The query work well in open-source Magento because there is a check before sending the variable to implode()
see: https://github.com/magento/magento2/blob/1c553ec1de9774c3eca4e94c815f11c9e70c50b8/app/code/Magento/BundleGraphQl/Model/Resolver/Order/Item/BundleOptions.php#L149

unlike Entreprise vesion there is no check
![image](https://user-images.githubusercontent.com/56534840/209978341-02eced14-af7e-43a1-9dfd-e310f8ce35d5.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-12-30 09:56
Hi @abdel-aouby,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance with EE edition and the issue is not reproducible.Kindly refer the screenshots.

Order details retrieved successfully for a Bundle Product.

<img width="1385" alt="Screenshot 2022-12-30 at 12 39 20 PM" src="https://user-images.githubusercontent.com/51680745/210057506-169319a4-2e45-46c3-8a3d-e7d3ef826020.png">



<img width="1426" alt="Screenshot 2022-12-30 at 12 56 40 PM" src="https://user-images.githubusercontent.com/51680745/210057517-778e7694-ee84-4817-8c29-349a88ac4b7c.png">


Kindly recheck the behavior on Magento 2.4-develop instance with EE edition and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by abdel-aouby** [comment] 2022-12-30 10:42
@magento give me 2.4-develop instance

**Comment by abdel-aouby** [comment] 2022-12-30 13:23
@engcom-Bravo I still could reproduce the issue with the same steps
here is the result and how the data are stored in DB
![image](https://user-images.githubusercontent.com/56534840/210074201-ff3a03dc-927c-4360-9b24-3868cb6fddbf.png)

![image](https://user-images.githubusercontent.com/56534840/210074723-3e82c08d-11d9-428c-a908-1139831c90f6.png)



could you please check how the data are stored in this column from your side
thanks

**Comment by engcom-Bravo** [comment] 2023-01-02 11:00
Hi @abdel-aouby,

Thanks for your update,

Verified the issue on Magento 2.4-develop instance with EE edition and the issue is not reproducible.Kindly refer the screenshots.

We are able to retrieve the order details.

<img width="1427" alt="Screenshot 2023-01-02 at 1 58 36 PM" src="https://user-images.githubusercontent.com/51680745/210222515-b7afb24d-a85d-403a-8b5c-3efe9e93c087.png">
<img width="1504" alt="Screenshot 2023-01-02 at 3 29 18 PM" src="https://user-images.githubusercontent.com/51680745/210222532-56db412b-4e97-4031-bca6-b01a28310dbc.png">



Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.


Thanks.

**Comment by abdel-aouby** [comment] 2023-01-02 12:17
Hi @engcom-Bravo 
I understand that you could not reproduce the issue from your side (i HONESTLY DON'T KNOW WHY), because I'm reproducing the issue in a clean **Adobe Commerce ver. 2.4.4 version** without any 3rd party extensions installed.
However, I could see that the `is_array` check has been added to the open-source version [2.4.5] 2.4.5-p1 a few months ago as a fix for the same exact issue I'm reporting here.
https://github.com/magento/magento2/commit/fdce4a4c21e68056d9938dd78317cefaaf23be91

Hence, it does make sense to have it similar in both versions.

**Comment by engcom-Bravo** [comment] 2023-01-03 08:34
Hi @abdel-aouby,

Thanks for your update.

it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.

Issue got fixed in Magento `2.4 develop` and Magento `2.4 develop` with Enterprise Edition.


Kindly recheck the behavior on Magento 2.4-develop instance with EE edition and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Closed as completed** 2023-01-16 06:06 UTC
Labels: Issue: needs update, Reported on 2.4.4
