### ISSUE TITLE
Tracked .gitignore file is overriden by composer! Magento 2.4.2-p1, 2.3.7

### ISSUE THREAD

**Issue by maciej-orba** [magento/magento2#32888] opened 2021-04-27 18:35 UTC
### Preconditions (*)
1. Magento 2.4.2-p1, 2.3.7 
1. Composer 2.0.11
1. PHP 7.4

### Steps to reproduce (*)
1. Create some empty directory for your workspace
1. `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition:2.4.2-p1 .` # or  2.3.7
1. `echo "/this/line/should/stay" >> .gitignore`
1. `git init`
1. `git add * && git add .*`
1. `git commit -m "Init"` # here w have file commited to repo
1. ` rm -rf vendor/*`
1. `composer install`
1. `git diff`

```
diff --git a/.gitignore b/.gitignore
index c144521..7092a56 100644
--- a/.gitignore
<ins></ins><ins> b/.gitignore
@@ -70,4 </ins>70,3 @@ atlassian*
 /generated/*
 !/generated/.htaccess
 .DS_Store
-/this/line/should/stay
```

Focus on last linie - my custom line was overriden
.gitignore is immportant file for many projects and should stay untouched if exists

### Expected result (*)
1. If .gitignore exists do not override it via composer

### Actual result (*)
1. .gitignore is overriden by every composer install run

**Edit: it affects also other files like .htaccess** 

## 
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- <x> Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
- < > Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
- < > Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
- < > Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
- < > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

**Comment by maciej-orba** [comment] 2021-04-28 11:49
Two additionals refs:

https://devdocs.magento.com/guides/v2.4/config-guide/prod/config-reference-gitignore.html

So, how to ignore custom objects?

https://devdocs.magento.com/guides/v2.4/config-guide/config/config-php.html

> As of the 2.2 release, the app/etc/config.php file is no longer an entry in the .gitignore file. This was done to facilitate pipeline deployment.

**Comment by magento-engcom-team** [comment] 2021-04-29 12:53
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42114` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hostep** [comment] 2021-04-29 19:41
Some additional information.

This is the same behavior now in 2.3.7 as how it worked in Magento 2.3.6 and earlier.
Only in Magento 2.3.6-p1 this behavior changed and a `.gitignore` file wasn't getting installed anymore.

However, there seems to be one very big difference, the `.gitignore` file that ships with Magento 2.3.7 also ignores `/app/etc/config.php` now, where in 2.3.6 it didn't. This sounds like a new bug.

@fascinosum: including you here, this sounds like something you might be interested in.

Also, this is most likely related to https://github.com/magento/magento2/issues/30507

**Comment by fascinosum** [comment] 2021-04-29 20:23
thank you, @hostep. @tpogrebniak could you look at this possible new behavior?

**Comment by maciej-orba** [comment] 2021-05-05 09:30
@hostep elier file was not overridden by composer install if currently exists. it may be connected with composer 2 usage. same as other map files (.htaccess, etc...).

**Comment by hostep** [comment] 2021-05-05 10:00
I've seen it happening as well as of lately, the overwriting of that file is not exactly the same behavior as before in Magento 2.3.6.

We have our own custom composer module that should overwrite the `.gitignore` file again on top of the default one that comes with Magento, but in 2.3.7 that seems to not be happening anymore or it could be that the sort order of when one module vs the other installs it (`magento2-base` vs our custom module) is now reversed. I haven't found the time yet to dig into this unfortunately.

It could indeed be a change in behavior caused by composer version 1 versus version 2 though, you could be right here, but somebody should double check this first.

**Comment by hostep** [comment] 2021-05-06 14:09
So here's my understanding of the issue, this has not been entirely researched but I think these are the basics:

Magento's https://github.com/magento/magento-composer-installer/ module has a feature to copy files outside of composer repository's to the project (they call this marshalling). In this case we are talking about a file called `.gitignore` inside the module `magento/magento2-base`

If I understand it correctly, the composer installer module compare the files it tries to copy from the previous version of a module to the current version it tries to install. If the file has not changed in between those 2 versions, it will not do anything (unless the file does not exists in the project). If the file did change in between those 2 versions, it will copy it again in the project.

So what happens here in a vanilla installation:
- The file `.gitignore` file in 2.3.6 is slightly different then the same file in 2.3.7 (that one line with `config.php` changed).
- The composer installer module detects this and overwrites the existing file users have in their project
- Before Magento 2.3.6, that `.gitignore` file has almost never changed, so people didn't ran into this

In our case, with our extra module, here is what happens:
- The file `.gitignore` file in 2.3.6 is slightly different then the same file in 2.3.7 (that one line with `config.php`).
- `magento/magento2-base` has a [hardcoded higher priority](https://github.com/magento/magento-composer-installer/blob/b9f929f718ef93ed61b6410bad85d40c37fd5ed3/src/MagentoHackathon/Composer/Magento/DeployManager.php#L35-L45) then all other modules, so its marshalling happens first
- So it overwrites the file in our project
- Our own module has a lower priority so in theory it should execute later, but since in our module that file did not change in between versions, it's not being executed

This is based on the behavior I'm seeing, I haven't actually debugged this, so it might not be 100% accurate.

There might be a solution in the magento composer installer module: if it detects one file that changed in one module, it should also still copy it for all other modules that want to copy the exact same file, even if it hasn't been changed in that particular module, while following the priorities of those modules.
But I'm not sure if that is possible.

This is just a braindump before I stop working today, will try to look into this again tomorrow.

**Comment by hostep** [comment] 2021-05-07 15:17
After having 15 minutes to try to investigate this problem yesterday, I had another 10 minutes today and I think my comments from yesterday make little sense anymore, because I can reproduce the problem without having to update any modules.
Simply removing the `vendor/magento/magento2-base` directory and running `composer install` already overwrites the `.gitignore` file where before it didn't do that I think.
I already determined that this happens both with composer v1 and v2, so my next steps would be to try various different versions of the `magento/magento-composer-installer` module, maybe one of those recent new versions caused a change in behavior.

But that will be for next week when I'll hopefully have more time...

**Comment by hostep** [comment] 2021-05-10 13:00
Okay, ignore all my ramblings above. None of them make sense because I was relying on my memory and started theorising instead of verifying some basic things first. Sorry about that!

Apparently the `.gitignore` file never got copied from the `magento2-base` package before Magento 2.3.7 / 2.4.2-p1
I incorrectly assumed this was the case, but it wasn't.

In Magento 2.3.7, for the first time in Magento2 history, the file `vendor/magento/magento2-base/composer.json` contains a reference to the `.gitignore` file in the marshalling config (`extra` > `map`)

I currently don't have a strong opinion if this needs to stay or not, but I think I would prefer to not see this file being overwritten since it's unexpected compared to previous versions of Magento.
I do however think it was a mistake in adding this change in a minor/patch release. If there is a strong desire to have this new behavior, it would have been better to introduce such a change in the next major version of Magento (2.5.0) as to not cause developers workflow to have to change in a minor/patch version.
Or maybe it could be implemented as a sample file as suggested in https://github.com/magento/magento2/issues/30507#issuecomment-716062888

We're going to work around this change by updating some of our workflow scripts.

**Comment by hostep** [comment] 2021-05-11 19:52
@maciej-orba: it could be that there is an official way to do this in the https://github.com/magento/magento-composer-installer module, by specifying something like this in your `composer.json` file:

```json
    "extra": {
        "magento-force": "override",
        "magento-deploy-ignore": {
            "*": [
                "/.gitignore"
            ]
        }
    }
```
or
```json
    "extra": {
        "magento-force": "override",
        "magento-deploy-ignore": {
            "magento/magento2-base": [
                "/.gitignore"
            ]
        }
    }
```

Source: https://github.com/magento/magento-composer-installer/pull/31 & https://github.com/magento/magento-composer-installer/blob/master/doc/Deploy.md#prevent-single-files-from-deploy

Not tested myself, but it sounds promising 🙂

**Comment by maciej-orba** [comment] 2021-05-11 20:09
Thanks!

**Comment by kassner** [comment] 2021-05-12 06:06
I've tested @hostep's first suggestion, works fine as a workaround.

```
    "extra": {
        "magento-force": "override",
        "magento-deploy-ignore": {
            "*": [
                "/.gitignore"
            ]
        }
    }```

Thanks @hostep!

**Comment by JosephLeedy** [comment] 2021-06-01 13:51
We've been using the solution that @hostep and @kassner suggested since 2.3 to prevent the `.editorconfig` file from being overwritten, but this broke as soon as we updated to 2.4.0. It also doesn't seem to work for the `.gitignore` file either, on 2.4.2-p1.

```    "extra": {
        "magento-force": "override",
        "magento-deploy-ignore": {
            "*": [
                "/.editorconfig",
                "/.gitignore"
            ]
        }
    }```

**Comment by edwinjacobs-pon** [comment] 2021-07-20 11:37
Not entirely sure if this is still an issue but in any case, this is in my opinion unwanted behaviour. The reason is quite simple, it is not the responsibility of magento to have any impact on a projects gitignore file. Simply because it is not knowable how the project looks like, sure you can provide a sample gitignore (.gitignore.sample or something like that) file to give developers a good starting point but there is no reason to modify it. 

With the current behaviour it could very well be that sensitive files end up in the repository because some developer didnt notice the gitignore file was changed by a composer install. This is very likely to happen because why should composer install change any file outside the vendor folder? If this happens magento gets the bad rep and rightfully so, in short it is not the responsibility of magento to do anything at all with the gitignore file. It is simply out of scope.

If it was up to me I would suggest removing the current behaviour.

**Comment by k4emic** [comment] 2022-03-17 10:00
Overriding the .gitignore file also affects the `auto-append-gitignore` option. 

I can't fully wrap my head around exactly why; my guess is that the magento2-base/.gitignore file is copied after the root .gitignore has been updated.

The auto-append-gitignore will append the copied filenames to your .gitignore file

```
$ cat .gitignore
# my casual .gitignore file
/.idea
/vendor
```

```
$ rm -r vendor/magento/magento2-base
$ composer install
```

```
$ cat .gitignore
# my casual .gitignore file
/.idea
/vendor
#magento/magento2-base
/.editorconfig
/.htaccess
/.htaccess.sample
/.php_cs.dist
...
```

But currently, the .gitignore file is simply being reset to the default contents of the the magento2-base/.gitignore contents.
Implementing the workaround pointed out above makes this behave as expected.

**Closed as completed** 2022-12-05 17:52 UTC
Labels: Component: Setup, Issue: Confirmed, Component: Composer, Reproduced on 2.4.x, Priority: P1, Progress: done, Area: Install & Administer

**Comment by hostep** [comment] 2023-01-02 15:23
Issue got closed as completed without any comments explaining why? Anybody any idea?

**Comment by nishant04412** [comment] 2023-01-05 06:31
This issue is fixed under JIRA: https://jira.corp.adobe.com/browse/ACPLTSRV-2224

PR Link: https://git.corp.adobe.com/magento-packaging/commerce-packaging/pull/163

**Comment by hostep** [comment] 2023-01-05 22:15
@nishant04412: thanks, but can you elaborate a bit? Both links are private which we can't see into.
Like how was this fixed? What can we expect and when?

**Comment by torhoehn** [comment] 2023-01-30 14:44
Am I right that the behaviour is the same for `pub/.htaccess`?

**Comment by hostep** [comment] 2023-01-30 14:52
@torhoehn: yes it is, but I think that is a good one, so people get the latest version and don't forget about looking for newly introduced changes with every Magento version.
This is a file that can be used in a production environment and can potentially contain security related fixes, so it's more important to be up2date with this file, then with developer-related file like the `.gitignore` file (for which everybody probably has it's own variant already specific for his own development workflow).

As for the `.gitignore` file, I can confirm that in Magento 2.4.6-beta1 it's no longer being overwritten, because it's missing an entry in the `vendor/magento/magento2-base/composer.json` file.

**Comment by torhoehn** [comment] 2023-02-02 20:00
@hostep Thank you for your detailed explanation. So I'll look for another way to implement Apache related changes.

**Comment by madalinignisca** [comment] 2023-04-11 07:32
> This issue is fixed under JIRA: https://jira.corp.adobe.com/browse/ACPLTSRV-2224
> 
> PR Link: https://git.corp.adobe.com/magento-packaging/commerce-packaging/pull/163

@nishant04412 it is not nice to share links to private things we can't access.

If you are a paid contributor with access to such private content, you should ask if needed permissions to share pieces of content that prove that fix is prepared.

**Comment by torhoehn** [comment] 2023-04-27 20:02
I just created a new project with Magento 2.4.6 and the `.gitignore` is missing completely.

@hostep Could you maybe confirm this?

**Comment by hostep** [comment] 2023-04-27 20:54
Yes that's correct, and that's a good thing I think. The `.gitignore` file that got delivered previously was not made for Magento projects, it was made for the github repo here. Everybody's structure is a little different, so everybody's `.gitignore` file will be slightly different and if composer would overwrite it each time, that would be annoying (and it was annoying).
