### ISSUE TITLE
Other custom option values are deleted after deletion of value from a custom option

### ISSUE THREAD

**Issue by Taral-Patoliya** [magento/magento2#10498] opened 2017-08-11 13:03 UTC
After applying the patches from the commits 
https://github.com/magento/magento2/commit/e2dc5d8b721600344697ed6cce87528c56cc4a1a and https://github.com/magento/magento2/commit/430d2ae6d8bde096160c45a6bfe3c2958774b500 related to the issue https://github.com/magento/magento2/issues/5931

We are facing another problem, when we have more then 1 custom options for a product, if we delete a value from one custom option, all the values from other custom options are getting deleted.

### Preconditions

1. Magento Version 2.1.X
2. Multiple Custom options with type (Select, multiple select, Radio Button, Check Box)

### Steps to reproduce

1.  Create a new product or edit existing product Add multiple Custom options having the type (Select, multiple select, Radio Button, Check Box)
2.  Save the Product
3. Open the product, delete one value from any custom option
4. save the product

### Expected result

1. It should save all the options without being recreated and having all the option values there.

### Actual result

1. Deletes all the options from other custom options
![1](https://user-images.githubusercontent.com/10272277/29214072-8981d86e-7ec3-11e7-8c4b-99f99a23bb2e.png)
![2](https://user-images.githubusercontent.com/10272277/29214078-8de59332-7ec3-11e7-9acc-46167ca05998.png)

**Comment by magento-engcom-team** [comment] 2017-09-19 08:11
We are closing this issue because we cannot reproduce this issue as described. If you have questions, please refer to a question and answer site, such as Stack Exchange and the Magento Forums, where Magento community members can quickly provide recommendations and advice.

**Closed as completed by magento-engcom-team** 2017-09-19 08:11 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid

**Comment by ashish-birlasoft** [comment] 2017-12-30 14:29
I'm facing exactly same issue.
after Upgrading from magento 2.1.0 to 2.1.10

**Comment by harithasdckap** [comment] 2018-01-04 08:28
Facing the same issue in Magento 2.2.1 version

**Comment by SahakTadevosyan** [comment] 2018-02-21 07:52
@magento-engcom-team 
I have the same issue in Magento 2.2.2 version in 2 different sites.

**Comment by xpedicion** [comment] 2018-02-22 10:38
I ran into the same issue on Magento 2.2.2 just now, as well.

**Comment by apapat** [comment] 2018-03-04 01:01
We have same issue on many magento 2.2.2 ... Please help ...

**Comment by xpedicion** [comment] 2018-03-04 01:23
I've found [commit ff42002](https://github.com/magento/magento2/commit/ff422002) to remedy the issue. This should help you. The foreach-line is missing the opening { bracket, though. Be wary of that.
