### ISSUE TITLE
Magento 2.1: Remove theme error "Unable to load theme by specified key: '5'"

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#5273] opened 2016-06-27 06:41 UTC
## Steps to reproduce
1. Install Magento 2.1 by download
2. Install custom theme by uploading it in app/design/frontend folder
3. update magento, clear all caches, compile, deploy etc.
4. Assign theme in backend
5. Remove theme by deleting the folder again and deleting theme entry in database table "theme"
## Expected result
1. Be able to switch back to normal magento theme in backend and frontend.
## Actual result
1. In backend when trying to assign the "luma" or "blank" theme the error:
   "Something went wrong while saving this configuration: Unable to load theme by specified key: '5'"
   appears. By default there is no theme chosen now. Also after saving the the dropdown is empty.
   2 In Frontend the error is shown:

"Unable to load theme by specified key: '5'"

Maybe our fault was to delete the theme first and not unassign it before in the backend. But how can we solve this now?

![3](https://cloud.githubusercontent.com/assets/16196483/16370804/deee54ea-3c42-11e6-80e7-51fffa20f4b3.png)
![2](https://cloud.githubusercontent.com/assets/16196483/16370806/df25e4d2-3c42-11e6-82f7-9d49f7378ec9.png)
![1](https://cloud.githubusercontent.com/assets/16196483/16370805/df2083fc-3c42-11e6-86a7-dfd733e1115a.png)

**Comment by Ctucker9233** [comment] 2016-06-27 23:28
I experienced this issue in version 2.0.7. I ended up having to adjust database value. So +1 for a permanent fix.

**Comment by veloraven** [comment] 2016-06-30 14:15
@andidhouse , please find description how to uninstall theme here: http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-theme-uninstall.html

If you still experience problems because of database corruption due to your previous actions, please refer to the [Community Forums](https://community.magento.com/) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

**Comment by vzabaznov** [comment] 2016-07-14 08:01
Hi, @andidhouse thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.

**Closed as completed by vzabaznov** 2016-07-14 08:01 UTC
Labels: Progress: needs update, Issue: Format is not valid

**Comment by zuber11** [comment] 2017-04-26 13:12
Please take a backup before applied any changes.
copy theme theme-frontend-luma from  vendor/magento/ and paste in app/design/frontend/mytheme. rename theme-frontend-luma as you want. open and edit registration.php and theme.xml as per wish.

Please note, this theme will just solve issue it will never play any role.

**Comment by travisdetert** [comment] 2017-10-12 01:45
This problem is laughable ridiculous, and inexcusable.  Why is this section of magento so pathetically fragile?

**Comment by korostii** [comment] 2017-12-04 13:45
It, kind of, is funny to see all that elaborate "them fallback" mechanics whilst it's not able to handle removal of a them as a whole.

I mean, if the data about selected\available themes is stored in the DB anyway, why not store the parent theme ID as well and why not implement a nice fail-switch here? Go figure.

**Comment by RicardoGalleguillos** [comment] 2018-02-13 17:55
Lo solucioné ejecutando la siguiente acción en magento 2.2.2:
1.- SELECT * FROM `core_config_data` WHERE core_config_data.value = '5'
data.value es el id del tema eliminado que arroja el error, deben cambiarlo por el id numero 2 (Magento/luma) en la columna path (design/theme/theme_id)
2.- php bin/magento indexer:reindex
3.- php bin/magento cache:flush

Mas rapido sería cambiar directamente en:
1.- SELECT * FROM `core_config_data` WHERE core_config_data.path = 'design/theme/theme_id'
cambiar design/theme/theme_id por el del tema que se encuentra en SELECT * FROM `theme`;
2.- php bin/magento indexer:reindex
3.- php bin/magento cache:flush

Suerte y saludos a los que aportan en la solución de problemas.

**Comment by seo99ita** [comment] 2018-02-25 22:42
@RicardoGalleguillos This solved the same problem.

**Comment by Arshad83** [comment] 2019-05-28 06:32
I was also facing the same issue when I was deleted my theme.
then I solved by deleting from the database table `core_config_data `

> select * from` core_config_data` where core_config_data.path='design/theme/theme_id';
> delete from `core_config_data` where core_config_data.value=5;

and then change default LUMA theme from id=5(mytheme) to id=2(luma)
>UPDATE `design_config_grid_flat` SET `theme_theme_id` = '2' WHERE `design_config_grid_flat`.`entity_id` = 2;

Finally 
> php bin/magento cache:flush
>rm -rf var/cache/* var/generated/*

**Comment by nittn** [comment] 2020-10-28 11:15
this problem is still there in Magento 2.3.4, and the solution form @RicardoGalleguillos and @Arshad83 works well.

if you forget to remove theme from Website/store/store view, products, category or wherever the theme can be applied, before you delete the theme, you can find the key problem anywhere from home page, product page, category page,

**Comment by huykon** [comment] 2021-02-25 02:35
I am facing with same problem although I deleted the custom theme_id in theme table then problem still on only category page. How can I update custom theme_id value for each category page or which table stored that? @RicardoGalleguillos @Arshad83

**Comment by khasruch** [comment] 2023-02-15 08:52
I fixed this issue, i updated the table **"design_config_grid_flat"** column  "theme_theme_id" value, here i attached screenshots: 


![Screenshot from 2023-02-15 14-49-59](https://user-images.githubusercontent.com/86234759/218979284-682b0d09-a765-4246-aa2b-add46f1b6ea7.png)
