### ISSUE TITLE
Issue with value set to 0 for int & smallint type fields. 

### ISSUE THREAD

**Issue by nishantjariwala** [magento/magento2#23268] opened 2019-06-14 13:45 UTC
Hi,
Here I've found an issue while saving blank field of database type int & small-int. It should be blank if I leave it blank but rather then it set that field value to 0.

### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Create field with int/smallint & set it's default value to **NULL** in database.
2. Add above field in any form.
3. Now, Leave it blank and save the form.
4. Here, It should be NULL but rather than it's storing as 0.
5. https://prnt.sc/o1ug19

### Expected result (*)

1. https://prnt.sc/o1ui35

### Actual result (*)

1. https://prnt.sc/o1ujfh

**Comment by magento-engcom-team** [comment] 2019-09-02 12:15
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19790` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment] 2020-10-22 17:00
Hi @nishantjariwala, thanks for reporting this issue.

Since such a fix would be backward incompatible and causing a lot of bugs on current extensions, it is not something we would have plans to fix.

**Closed as completed by gabrieldagama** 2020-10-22 17:00 UTC
Labels: Reproduced on 2.3.x, Component: DB, Triage: Dev.Experience, Progress: ready for dev
