### ISSUE TITLE
Cache Auto Flushing In Magento 2.4.5-p1

### ISSUE THREAD

**Issue by TheRealHunzik** [magento/magento2#36810] opened 2023-02-07 05:35 UTC
### Preconditions and environment

- Magento 2.3.5-p1 CE
- Local Installation or Hosted Magento Instance

### Steps to reproduce

- Login to Admin Dashboard
- Edit any Product
- Change Its Name or any other attribute
- Go to Store Front and Check PDP Page

### Expected result

-  Product Value Should not Change as Cache is Not Cleared Yet

### Actual result

- Changes are Reflecting on Store Front
- i have added `X-Magento-Cache-Debug` header in Response which is Showing `MISS` on Product Save

### Additional information

- i have checked by configuring vanish so issue is also there when vanish is configured

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2023-02-09 04:43
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2023-02-09 05:08
Hi @TheRealHunzik ,
Thank you for reporting and collaboration. Verified the behavior on Magento 2.4-develop instance and is reproducible but however this is the Magento feature but not a bug. Once a product is saved all of the pages on which that product appears will be cleared. No need to flush the cache. Kindly refer the Magento [docs,](https://docs.magento.com/user-guide/v2.3/system/cache-management.html) [full page cache](https://docs.magento.com/user-guide/v2.3/system/cache-full-page.html) for further understanding of the cache management.
Thank you.

**Comment by TheRealHunzik** [comment] 2023-02-20 06:49
https://github.com/magento give me 2.4.2 instance

**Comment by TheRealHunzik** [comment] 2023-02-20 06:50
@magento give me 2.4.2 instance

**Comment by TheRealHunzik** [comment] 2023-02-20 06:54
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2023-02-23 04:34
Hi @TheRealHunzik ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2023-02-23 04:34 UTC
Labels: Issue: needs update, Reported on 2.3.5-p1
