### ISSUE TITLE
Autoload error: Class XSLTProcessor does not exist

### ISSUE THREAD

**Issue by cerebrumbr** [magento/magento2#1309] opened 2015-05-26 20:55 UTC
See image below.

In beta10.

Generate this error.

Autoload error: Class XSLTProcessor does not exist

When I try execute this command ...

php -f bin/magento module:enable Apsense_hello

![captura de tela de 2015-05-26 17 18 41](https://cloud.githubusercontent.com/assets/2263217/7823167/0730140e-03d0-11e5-970b-9fc3462d4a9b.png)

**Comment by therouv** [comment] 2015-05-26 21:18
Hi @cerebrumbr ! 
`php-xsl` is a dependency now, you have to install the corresponding PHP module. See #1304

**Comment by mazhalai** [comment] 2015-05-27 14:01
@cerebrumbr thank you for reporting this issue. However, it is a duplicate of #1304, hence closing this ticket.

**Closed by mazhalai** 2015-05-27 14:01 UTC
