### ISSUE TITLE
Special Price cannot be removed for a single website/ store view

### ISSUE THREAD

**Issue by harleeniweb** [magento/magento2#37766] opened 2023-07-17 20:16 UTC
### Preconditions and environment

- Magento 2.4.6-p1 EE

### Steps to reproduce

1. Setup multiple websites.
2. Edit any product in admin panel assign it to all websites and set special price for it.
3. Now edit product for any one website and try to remove special price.

### Expected result

Special price for the product should be removed for that particular website.

### Actual result

It is set to "use default value" instead of removing special price.

### Additional information

Please find the screen recording of issue in version 2.4.6-p1
[special-price-issue.webm](https://github.com/magento/magento2/assets/79199454/8bedd608-b82e-4517-8571-a2073ab30207)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by harleeniweb** [comment] 2023-07-17 20:17
@magento give me 2.4-develop instance please

**Comment by harleeniweb** [comment] 2023-07-17 20:34
@magento I can now replicate the issue on your vanilla instance provided above , if you edit the product "24-MB01" and try to remove the special price from Test store view in there it is not letting you do that and keeps reverting it back to default value (i.e the price setup at default store view level)

**Comment by engcom-Bravo** [comment] 2023-07-18 10:53
Hi @harleeniweb,

Thank you for reporting and collaboration.

Similar issue has been confirmed here https://github.com/magento/magento2/issues/37579 we are closing this issue as a duplicate Kindly move onto this issue for latest updates / solutions on the same.

Thanks.

**Closed as completed by engcom-Bravo** 2023-07-18 10:53 UTC
Labels: duplicate, Issue: ready for confirmation, Reported on 2.4.6-p1

**Comment by raulsinapsis** [comment] 2024-07-16 08:09
This is still happening in 2.4.6-p4
Not sure if the mentioned commit could fix this, as it seems to involve only admin visualization, but the problem is the data in database

We can't setSpecialPrice(null) programmatically in a concrete website if that product has a special_price value in default scope
