### ISSUE TITLE
Editing store product programmatically gives data from default scope when field is NULL

### ISSUE THREAD

**Issue by redelschaap** [magento/magento2#9389] opened 2017-04-25 09:04 UTC
When editing a product programmatically using a store ID, data from non-global attributes are filled with data from the default scope when that field is empty/set to use the default value in the store scope. I would expect to have a mode where I can choose to leave those fields NULL instead of getting the default data.

### Preconditions
1. Using Magento 2.1.5

### Steps to reproduce
1. Load a product using `$product = $this->productRepository->getById(1, true, 1)` with `$editMode` enabled and optionally `$forceReload` enabled.

### Expected result
1. Get the product object where `$product->getData('attribute_code')` returns NULL when that field is empty/set to use the default value for that store.

### Actual result
1. `$product->getData('attribute_code')` returns the value of the default scope when that field is empty/set to use the default value for that store.

**Comment by korostii** [comment] 2017-04-25 12:48
The official flow is that currently the GitHub issue tracker is intended for tracking technical issues (read: "bugs") only. Suggested improvements and feature requests are expected to appear on the [Community Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests).

**Comment by redelschaap** [comment] 2017-04-26 06:23
So this is intended behaviour? If so, is there any way to reach what I need?

**Comment by korostii** [comment] 2017-04-26 11:02
Yes, I believe the logic was like that since good old Magento1 days. At least for the "set to use the default value in the store scope" part. 
I would still expect that leaving the field empty would work as you expected (just re-tested: weirdly enough, it seems to ignore that empty string and restore to "use default" after saving - IMHO this part might be considered a bug).

I'm not sure what you need, exactly. But, if the aim is to have an empty value for this attribute in store scope, the following workaround seems to work (for the description textarea, at the very least):
1) unset checkbox "Use Default Value"
2) put `" "` (one space)
3) save the product - Magento seems to trim the value, resulting in a `""` (an empty string).
Then you could then check the value using `empty()`

**Comment by redelschaap** [comment] 2017-05-04 16:12
I'm not talking about editing/saving a product using the backend, but programmatically, so using code only.

**Comment by korostii** [comment] 2017-05-04 17:44
To be honest, I'm not sure if there's a safe workaround, you might need to do some digging on your own here. I'd advise to start by checking whether issue #9434 explains what you're experiencing.
Good luck & sorry for not being able to help any further.

**Comment by redelschaap** [comment] 2017-05-04 19:31
Unfortunately not; it's not the flat table. But thanks for your time and effort!

**Comment by redelschaap** [comment] 2017-05-04 19:55
Actually this is a bug, just found these two issues: #8897 and #7879.

**Comment by magento-engcom-team** [comment] 2017-10-04 15:30
@redelschaap, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-04 15:30 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid

**Comment by koenner01** [comment] 2018-01-04 14:20
We are having this problem in 2.2.2, so no this issue was not 'already fixed in 2.2.0'
Can this please be picked up again..
 
This bug was also re-confirmed in 2.2.x and 2.3.x according to this issue https://github.com/magento/magento2/issues/7879
