### ISSUE TITLE
Magento calculates wrong value if there are multiple discounts

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#36799] opened 2023-02-02 16:25 UTC
### Preconditions and environment

- Magento version 2.4.4 (fresh installation)
- Also reproduced in a fresh 2.4.2

### Steps to reproduce

1. Create a cart rule which gives you 5% discount if you selected the shipping method free shipping
2. Create a cart rule which gives you 10% discount on everything

Note: Make sure that you disable "Discard subsequent rules" for both rules so that both rules will apply at the same time.

3. Buy something worth 100 €
4. Go to checkout and select the "Free Shipping" shipping method.
5. Look at the total sum.

### Expected result

It should give you a discount of 15% in total so you should have to pay 85 € for the 100€ product (before taxes).

Calculation:

100€ * 0,85 = 85€

### Actual result

![image](https://user-images.githubusercontent.com/16349349/216381873-8e4b4d9b-4ff4-4e53-9211-30946579a022.png)

Reason:

Magento does not calculate the total discount (5% + 10% = 15%), it calculates the discounts by row e.g.

100€ - 5% = 95€
95€ - 10% = 85,5€

So the customer has to pay more money than he actually should.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-02-06 10:13
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-02-09 07:36
@magento give me 2.4-develop instance

**Comment by Eddcapone** [comment] 2023-02-09 07:40
@engcom-Bravo I can shorten it up for you. The bug was already confirmed by magento support.

**Comment by engcom-Bravo** [comment] 2023-02-09 11:35
Hi @Eddcapone,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

1.Create a cart rule which gives you 5% discount if you selected the shipping method free shipping
2.Create a cart rule which gives you 10% discount on everything
Note: Make sure that you disable "Discard subsequent rules" for both rules so that both rules will apply at the same time.

3.Buy something worth 100 €
4.Go to checkout and select the "Free Shipping" shipping method.
5.Look at the total sum.


As per Magento cart price rule document https://docs.magento.com/user-guide/v2.3/marketing/price-rules-cart-create.html
when we are setting multiple cart price rules should be defined.

<img width="987" alt="Screenshot 2023-02-09 at 5 01 16 PM" src="https://user-images.githubusercontent.com/51680745/217801170-0a98b9d1-b1fa-4733-a1f2-7237181bf61a.png">


Cart price rules should have different priorties.

<img width="1056" alt="Screenshot 2023-02-09 at 5 02 21 PM" src="https://user-images.githubusercontent.com/51680745/217801401-077107ff-39fa-4877-a870-f8e0c6f853b5.png">


Based on the priority cart price rule should be applied.if we give priority 1 to 10% discount cart price rule it will apply first, after that 5% discount cart price rule will be applied.

Kindly go through with the above document and please let us know if you are still facing any issue.

Thanks.

**Comment by Eddcapone** [comment] 2023-02-13 08:20
@engcom-Bravo It seems like you don't understand the problem. The priority does not mather at all, the end result is wrong in all cases no mather what the priority is set to. As I mentioned before, I even reported that bug to magento support and they confirmed it already.

**Comment by engcom-Bravo** [comment] 2023-02-16 11:42
Hi @Eddcapone,

Thanks for your update.

It seems as an expected behaviour, as cart price rule(s) should apply one by one according to the priority. Still we are marking this issue On Hold to discuss with the PO on this issue. We will update you accordingly.

Thanks.

**Comment by Eddcapone** [comment] 2023-02-16 15:41
@engcom-Bravo I can't imagine that it is expected behaviour if the end result is wrong. Then there should at least be an option to change that behaviour.

**Comment by engcom-Bravo** [comment] 2023-04-03 14:49
Hi @Eddcapone,

We got reply from PO as follows :


The correct behaviour is when rules are applied by priority one after another, for example the correct amount after discount is

Based on First cart price rule it is giving 5% discount (100$-5$)=95$
Based on second cart price it is giving 10% discount (95$-9.5$)=85.5$


The calculation method expected by reporter is incorrect and could potentially result in excessive discount amounts in some cases.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-04-14 06:10
Hi @Eddcapone,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-04-14 06:10 UTC
Labels: Issue: needs update, Reported on 2.4.4

**Comment by Eddcapone** [comment] 2023-04-24 13:50
It is highely unlogical but we have to accept your decision and develop a workaround.
