### ISSUE TITLE
Huge frontend performance issues due to a plugin that adds the current category to the cache key of the topmenu

### ISSUE THREAD

**Issue by guvra** [magento/magento2#36837] opened 2023-02-09 16:02 UTC
### Preconditions and environment

- Magento version: >= 2.3.4

In Magento 2.3.4, the following plugin function was added: https://github.com/magento/magento2/commit/bd5b7c584de95da97200be47d6f63fd9eda372f7

It adds the current category to the cache key of the topmenu.
According to the release notes, this change was introduced to fix the following bug:

> Magento now highlights only the most recently selected category as expected on storefront pages that contain multiple categories. Previously, all selected category menus remained highlighted.

Adding the current category to the cache key of the topmenu **has an enormous impact on the frontend performance**.
After this change was introduced, the menu is recalculated on every category page...

This plugin needs to be removed, and replaced by a JavaScript component that handles the highlighting of the current category instead.

### Steps to reproduce

1. Flush `block_html` and `full_page` cache.
2. Navigate to storefront as a guest.
3. Go to any category.
4. Go to another category. The page will be slow to render because the cache of the menu is not shared between categories.

### Expected result

I expect the cache of the topmenu to be shared by all pages of the frontend store.
This is currently not the case (one cache per active category).

### Actual result

The topmenu generates a separate cache for each active category.

### Additional information

What needs to be done:

1. Remove the plugin that adds the current category to the cache key of the topmenu.
2. Either refactor the highlighting feature (must be managed by a JS component to bypass the full page cache), or completely remove it (this feature is useless).

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment] 2023-02-13 12:27
Hi @guvra 

Thanks for reporting the ticket.

as per retesting on 2.4.x Develop an instance that is ahead of all instances. the issue is not reproducible.
please find the attached video for reference.

**Video Attachment**

Uploading Issue #36837.Huge frontend performance issues due to a plugin that adds the current category to the cache key of the top menu· Issue #36837 · magento_magento2.mp4…

**Comment by guvra** [comment] 2023-02-13 13:10
@engcom-Alfa Hi,

The issue still exists on the develop branch, cf. https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Plugin/Block/Topmenu.php#L210

You won't reproduce it on a demo store, it doesn't have enough products/categories to be slow.
With a huge catalog, generating the menu requires hundreds of SQL queries (or even thousands in extreme cases), so having a separate cache key by category is a huge problem.

**Comment by engcom-Alfa** [comment] 2023-02-23 05:39
Hey @guvra 

Thanks for replying to my last comment.
Just for your information, we tested the issue on the 2.4.x develop instance only which is ahead of all develop or qa branches, so I request you if you can please share with us any log file for the scenario which you are performing, so it would more helpful for training for us internally with team.

Thanks

**Comment by engcom-Bravo** [comment] 2023-03-09 08:19
Hi @guvra,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by guvra** [comment] 2023-03-09 08:38
@engcom-Bravo You really need to forward this issue to a develop with technical knowledge of Magento, this issue has huge issues on the frontend performance, and you won't reproduce it on a demo store with very few products.

The description of the issue clearly explains where the problem is and how it could be solved.

There's even an easy fix which would be removing the plugin that messes up the cache and also remove the small CSS code that highlights the current category (this feature is useless).

**Comment by guvra** [comment] 2023-03-09 13:57
@engcom-Alfa @engcom-Bravo @engcom-Hotel @engcom-Charlie Anyone available to reopen this issue? It's locked on my end.

How to escalate this issue to the dev team?

**Comment by engcom-Bravo** [comment] 2023-03-09 14:10
Hi @guvra,

We are reopening this issue.

**Comment by guvra** [comment] 2023-11-09 08:45
For anyone wondering how to "fix" this, you can just add the following patch with [composer-patches](https://github.com/cweagans/composer-patches) to disable the faulty plugin:

```
--- Plugin/Block/Topmenu.php
+++ Plugin/Block/Topmenu.php
@@ -111,28 +111,6 @@
     }

     /**
-     * Add list of associated identities to the top menu block for caching purposes.
-     *
-     * @param \Magento\Theme\Block\Html\Topmenu $subject
-     * @return void
-     */
-    public function beforeGetIdentities(\Magento\Theme\Block\Html\Topmenu $subject)
-    {
-        $subject->addIdentity(Category::CACHE_TAG);
-        $rootId = $this->storeManager->getStore()->getRootCategoryId();
-        $storeId = $this->storeManager->getStore()->getId();
-        /** @var \Magento\Catalog\Model\ResourceModel\Category\Collection $collection */
-        $collection = $this->getCategoryTree($storeId, $rootId);
-        $mapping = [$rootId => $subject->getMenu()];  // use nodes stack to avoid recursion
-        foreach ($collection as $category) {
-            if (!isset($mapping[$category->getParentId()])) {
-                continue;
-            }
-            $subject->addIdentity(Category::CACHE_TAG . '_' . $category->getId());
-        }
-    }
-
-    /**
      * Get current Category from catalog layer
      *
      * @return \Magento\Catalog\Model\Category
@@ -196,22 +174,4 @@

         return $collection;
     }
-
-    /**
-     * Add active
-     *
-     * @param \Magento\Theme\Block\Html\Topmenu $subject
-     * @param string[] $result
-     * @return string[]
-     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
-     */
-    public function afterGetCacheKeyInfo(\Magento\Theme\Block\Html\Topmenu $subject, array $result)
-    {
-        $activeCategory = $this->getCurrentCategory();
-        if ($activeCategory) {
-            $result[] = Category::CACHE_TAG . '_' . $activeCategory->getId();
-        }
-
-        return $result;
-    }
 }
```

**Comment by engcom-Hotel** [comment] 2024-11-07 12:23
Hello @guvra,

It seems the said plugin has been removed from the latest development branch:

https://github.com/magento/magento2/blob/6acfd6aa744c905f7694f2cddd5b0add5bf202b7/app/code/Magento/Catalog/Plugin/Block/Topmenu.php#L62-L101

The Plugin `afterGetCacheKeyInfo` has been removed. Hence we are closing this issue. Please let us know if you are still facing this issue.

Thanks

**Closed as completed by engcom-Hotel** 2024-11-07 12:23 UTC
Labels: Triage: Dev.Experience, Component: RequireJs, Issue: needs update, Reported on 2.3.4, Area: Performance
