### ISSUE TITLE
Unable to assigne products to category (Unique constraint violation found)

### ISSUE THREAD

**Issue by dleno** [magento/magento2#27190] opened 2020-03-06 11:24 UTC
### Preconditions (*)

1. Magento CE 2.3.3-p1
2. Able to reproduce in previous versions of magento
3. Multistore setup

### Steps to reproduce (*)

1. Go to Product Edit Page and change the url key on store scope (for example test1)
2. Got to another product and change url key on default scope to exactly the same as you used in store scope for product from step 1
3. Go to category page and try to assigne products from step 1 and step 2

### Expected result (*)

1.Products assigned to category
2.

### Actual result (*)

1. [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/7083460/76078667-6b233980-5fa3-11ea-8306-b2f06d3b44fc.png)
2. Error stored in exception.log: 
PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'category/url-key' for key 'URL_REWRITE_REQUEST_PATH_STORE_ID'

**Comment by engcom-Bravo** [comment] 2020-03-16 11:15
Hello @dleno 

Thank you for your report.

Unfortunately, we are not able to reproduce the issue on a clean Magento 2.4-develop instance.

Can you please provide more information so that we could reproduce the issue and start working on it? 

Please, attach screenshots from your category settings, step 3, like this 
![ar](https://user-images.githubusercontent.com/51680745/76750827-8eaa6900-6787-11ea-9cd8-4d12320266b6.png)

Screenshots from the product settings where the _Sope_ and  _change url_ from step1, is displayed

Thank you in advance

**Comment by sudheers-kensium** [comment] 2020-05-13 10:54
Not able to reproduced on latest Magento instance. So i am closing this issue.

Feel free to reopen if you are facing the same issue on latest Magento instance.

**Closed as completed by sudheers-kensium** 2020-05-13 10:54 UTC
Labels: Issue: Format is valid, Reported on 2.3.3-p1
