### ISSUE TITLE
Payment model name is not provided in config!

### ISSUE THREAD

**Issue by Rohaty** [magento/magento2#33766] opened 2021-08-12 08:42 UTC
### Preconditions (*)

1.Magento Community edition version 2.4.3
2.Install Amasty reward_points extension (or other extension, where call function: getMethodInstance($code))

### Steps to reproduce (*)

1.Backend admin:  SALES-Orders
2.

### Expected result (*)

1.When in admin panel: SALES-Orders then shows Orders
2.
![image](https://user-images.githubusercontent.com/29813291/129164948-8203664b-9ee0-47ec-9397-c195922128f1.png)

### Actual result (*)

1. 
![image](https://user-images.githubusercontent.com/29813291/129166596-26ad7a04-a88d-4150-8c01-deb2edb57107.png)

2.This problem is caused by the paypal module, where <title> is missing in the <paypal_paylater> section of the etc/config.xml file. If I add e.g. <title> Paypal Paylater </title> to <paypal_paylater>, the error is no longer shown and everything is fine.

Can you fix this error in the code?

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment] 2021-08-12 14:02
in my opinions I think need fixes from amasty module first

**Comment by mrtuvn** [comment] 2021-08-12 14:45
If problem exist i think resolve this issue just need update missing parts to paypal module as your solutions! Can you create PR for this

**Comment by mrtuvn** [comment] 2021-08-13 14:21
assign to @rvanwilgen

**Comment by mrtuvn** [comment] 2021-08-13 14:22
@magento rvanwilgen working on this

**Comment by arjunadobe** [comment] 2021-08-15 10:39
This looks like a problem in the amasty module. 
Fix:
Add the below code in ur customer module config.xml
`<?xml version="1.0"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Store:etc/config.xsd">
    <default>
        <payment>
            <paypal_paylater>
                <title>Paypal PayLater</title>
            </paypal_paylater>
        </payment>
    </default>
</config>`

**Comment by mrtuvn** [comment] 2021-08-16 00:59
Hi @engcom-Alfa Can we able verify issue with module from amasty ? From the info of author i see module used Amasty_AdvancedConditions

**Comment by mrtuvn** [comment] 2021-08-16 08:38
@Rohaty I believe module that mentioned work for enterprise version case. Have you check in opensource version of magento ?

**Comment by Rohaty** [comment] 2021-08-16 12:40
Hi @mrtuvn, the solution I mentioned is done in open source magento.
The solution is exactly as stated by @arjunadobe, and the fix must be done in the module-paypal/etc/config.xml.

Amasty, since I bought the rewards module from them, has already sent me a patch, which consists only in the fact that they made the call to getMethodInstance () via try-catch.

In any case, each payment module should have <title> and I think also <model> to avoid errors.

**Comment by mpatel015** [comment] 2021-08-17 12:30
Thank you!
Patch suggested by @arjunadobe arjunadobe worked for me, Exact Patch https://patch-diff.githubusercontent.com/raw/magento/magento2/pull/33792.patch was not working so I re created it and it solved the problem.
Here is the patch I used
 vendor/magento/module-paypal/etc/config.xml | 1 +
 1 file changed, 1 insertion(+)

diff --git a/vendor/magento/module-paypal/etc/config.xml b/vendor/magento/module-paypal/etc/config.xml
index b9bd492..d948f81 100644
--- a/vendor/magento/module-paypal/etc/config.xml
+++ b/vendor/magento/module-paypal/etc/config.xml
@@ -188,6 +188,7 @@
                 <verify_peer>1</verify_peer>
             </hosted_pro>
             <paypal_paylater>
+                <title>Paypal PayLater</title>
                 <experience_active>0</experience_active>
                 <enabled>0</enabled>
                 <productpage_display>0</productpage_display>
--

**Comment by bgorski** [comment] 2021-08-21 14:05
The PayPal Pay Later title is not the real issue here - the logic for getting payment methods is faulty. I provided more detailed explanations here: https://github.com/magento/magento2/pull/33792#issuecomment-903119256
For this reason I closed a PR for this and asked for a different one. For the time being, please either use the patch provided above or - if you happen to work for a provider of any extension that has problems with this, please consider changing your logic to either use `\Magento\Payment\Api\PaymentMethodListInterface` to fetch your payment methods or provide a filter for the output of `\Magento\Payment\Helper\Data::getPaymentMethods()` similar to what `\Magento\Payment\Model\PaymentMethodList::getList($storeId)` has in order to remove data that doesn't correspond to actual payment methods.

**Comment by engcom-Hotel** [comment] 2022-01-14 09:16
Hello @Rohaty,

I have checked this issue in the fresh Magento 2.4-develop branch with `Paypal pay later` enable but for us, the issue is not reproducible, may be due to we do not have the Amasty reward points extension installed.

Please suggest to us other ways to reproduce the issue.

Thanks

**Comment by engcom-Hotel** [comment] 2022-01-28 05:58
Dear @Rohaty,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-01-28 05:58 UTC
Labels: Issue: needs update, Reported on 2.4.3

**Comment by caos989** [comment] 2022-10-05 06:57
I had the same problem when I activated Stripe. I'm also using Amasty.

Solution for me was to edit the file: vendor/stripe/module-payments/etc/config.xml

I added <title> in Line 7
            <rate_limiter>
                <title>Rate Limiter</title>
