### ISSUE TITLE
Magento 2.3 wysiwyg Upload pdf error

### ISSUE THREAD

**Issue by developer-vtnetzwelt** [magento/magento2#20216] opened 2019-01-11 11:49 UTC
### Preconditions (*)

As Magento have changed wysiwyg to tinyMCE4, now upload pdf/document is not working
1.  Magento version 2.3.0

### Steps to reproduce (*)

1. open any CMS page and edit the content of content using wysiwyg
2. Insert file button is missing to upload pdf images
3. now try to upload the pdf using insert image after changing allowed extensions in di.xml
### Expected result (*)

1. pdf file should be uploaded and link is added to cms page.

### Actual result (*)

1. pdf file is uploaded but giving unsupported file error. 
2. link to the pdf is also not correct, it is considering it still as image.

**Comment by magento-engcom-team** [comment] 2019-01-11 11:49
Hi @developer-vtnetzwelt. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@developer-vtnetzwelt do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-11 11:50
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by developer-vtnetzwelt** [comment] 2019-01-11 12:00
Hi @shikhamis11 

we are facing this issue, on fresh magento install of 2.3.0. 
create a custom page in cms pages and  try to upload the pdf in the new editor. First we don't have any option.
if we tried to change the allowed extensions of image then we face unsupported file issue.

**Comment by shikhamis11** [comment] 2019-01-11 12:46
@developer-vtnetzwelt the issue you are facing is basically due to your custom code for changing allowed types . 
and about missing option for adding documents yes right now there is only options for adding image in 
wysiwyg editor

**Comment by irajneeshgupta** [comment] 2019-01-11 16:06
Dublicate issue ref->#9850

**Closed as completed by irajneeshgupta** 2019-01-11 16:06 UTC
Labels: feature request, Issue: Clear Description, Issue: Format is valid
