### ISSUE TITLE
sales_order_item_save_commit_after & sales_order_save_commit_after events do not fire for guest checkout

### ISSUE THREAD

**Issue by navarr** [magento/magento2#23340] opened 2019-06-20 12:12 UTC
This is a recreation of issue #19034, which was processed w/r/t downloadable products not properly being linked.  The solution at that time was to modify the way downloadable products work, but it did not solve the underlying architectural issue that continues to result in these events not being thrown and thus causes issues for third party modules.  I know both AvaTax and Vertex, for example, have workarounds for this issue.

### Summary (*)
GuestPaymentInformationManagement opens two additional transactions prior to performing any of the actions in checkout.  Due to this, the AbstractDb's `commit` method never has a transactionLevel less than 2, so the commit callbacks are not processed.

### Preconditions (*)
1. Magento 2.3.x

### Steps to reproduce (*)

1. Create new observers for events `sales_order_item_save_commit_after` and `sales_order_save_commit_after`.
2. Complete checkout as guest user.

### Expected result (*)

1. Events have fired.
2. Observers have processed events.

### Actual result (*)

1. Events have not fired.

### Proposed solution (*)
Commit callbacks could be moved to the connection level where the transactions are actually created.

**Comment by magento-engcom-team** [comment] 2019-10-15 14:48
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21835` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mrodespin** [comment] 2019-10-27 11:42
I have been checking this issue and i founded that the problem is that events are been triggered with the following names instead the ones that are informed on the ticket
`sales_order_item_resource_save_commit_after `
`sales_order_resource_save_commit_after `

That is provoked because the **$_eventPrefix** is been declared on the following files:
`app/code/Magento/Sales/Model/ResourceModel/Order.php`
`app/code/Magento/Sales/Model/ResourceModel/Order/Item.php`

<img width="1252" alt="Captura de pantalla 2019-10-27 a las 12 35 07" src="https://user-images.githubusercontent.com/31536387/67634140-685b5e00-f8b8-11e9-95ef-42364f5ec757.png">

**Comment by mrodespin** [comment] 2019-10-27 12:01
After continue the debugging i am able to reproduce the events, as you can see on then images:

<img width="965" alt="Captura de pantalla 2019-10-27 a las 13 00 59" src="https://user-images.githubusercontent.com/31536387/67634264-d8b6af00-f8b9-11e9-9ae6-0cdbd96fdca8.png">

<img width="934" alt="Captura de pantalla 2019-10-27 a las 13 01 27" src="https://user-images.githubusercontent.com/31536387/67634274-e9672500-f8b9-11e9-8700-a5687f98bf62.png">

**Comment by mrodespin** [comment] 2019-10-27 12:12
This issue is not happening on magento 2.3 as you can see on the following captures

<img width="1178" alt="Captura de pantalla 2019-10-27 a las 13 12 23" src="https://user-images.githubusercontent.com/31536387/67634390-752d8100-f8bb-11e9-9e25-a40280ef572f.png">
<img width="1053" alt="Captura de pantalla 2019-10-27 a las 13 11 50" src="https://user-images.githubusercontent.com/31536387/67634391-752d8100-f8bb-11e9-906d-b0bbcc3e3aef.png">

**Comment by mrodespin** [comment] 2019-10-27 12:43
@magento I can't reproduce the error on 2.3 branch

**Closed as completed by mrodespin** 2019-10-27 12:43 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Framework/Code

**Comment by crankycyclops** [comment] 2019-11-26 19:59
I'm still seeing this issue on Magento 2.3.3.

**Comment by frno-morita** [comment] 2020-09-17 13:38
I'm not sure if it has been mentioned/tested, but this happens when you place the order as a `Guest` using the WebAPI to do so.
`POST <siteUrl>/V1/guest-carts/:cartId/payment-information`

```xml
<route url="/V1/guest-carts/:cartId/payment-information" method="POST">
    <service class="Magento\Checkout\Api\GuestPaymentInformationManagementInterface" method="savePaymentInformationAndPlaceOrder"/>
    <resources>
        <resource ref="anonymous" />
    </resources>
</route>
```

This never happens using the normal Magento Luma frontend base, but it happens if you do the `Guest` checkout flow using only the `WebAPI`.

@swnsma Mentions why this happens in the flow a bit more in detail in https://github.com/magento/magento2/issues/19034, but he might have failed to mention you trigger this case when using the `WebAPI` to create an order as a `Guest` user.
