### ISSUE TITLE
Magento sending incorrect transaction type to Paypal while creating invoice from admin

### ISSUE THREAD

**Issue by sreejith-cb** [magento/magento2#7394] opened 2016-11-10 13:47 UTC
We need Paypal delayed capture at the time of manually creating invoice from admin. We have set 'Authorization' payment action in admin Paypal Payflow Pro section.
From the debug log i have found that magento is sending the ‘trxtype’=> 'S' when invoicing the sale.
I was able to compare them to PayPal’s documentation and found that we are using the incorrect ‘trxtype’.  
The ‘trxtype’ is set to ‘S’ which is Sale, and would typically only be used as the only transaction. 
Because we do not instantly provide the product purchased right away we need to complete an Authorization (already in place) first, and then a Delayed Capture at the time of invoicing.  
We are needing to have the ‘trxtype’ populate ‘D’ when we invoice the sale. 
This will trigger a Delayed Capture and will only associate the payment to the authorization that we already have.

### Preconditions
1. Magento 2.1.0

### Steps to reproduce
1. Add product to cart from frontend.
2. Place the order
3. Login to admin
4. View the order
5. Click invoice button
6. Look at the request and response in debug.log for the order invoiced.

### Expected result
1. Magento should send a request to paypal for delayed capture with ‘trxtype’ D.

### Actual result
1. Magento is sending a request to paypal for sales with ‘trxtype’ S.
2. Below is the request and its response generated when the invoice is generated.

[2016-11-01 15:18:45] main.DEBUG: array (
  'request' => 
  array (
    'user' => '****',
    'vendor' => 'XXXXX',
    'partner' => 'XXXXX',
    'pwd' => '****',
    'verbosity' => 'MEDIUM',
    'BUTTONSOURCE' => 'Magento_Cart_Community',
    'tender' => 'C',
    'amt' => 79.959999999999994,
    'trxtype' => 'S',
    'origid' => 'AQ0AGGA38978',
    'ponum' => '7351',
    'custref' => 'XXX45',
    'invnum' => 'XXX45',
    'comment_1' => 'XXX45',
  ),
  'result' => 
  array (
    'result' => '0',
    'pnref' => 'AU0XXXXX',
    'respmsg' => 'Approved',
    'authcode' => '04XXXXX',
    'avsaddr' => 'Y',
    'avszip' => 'Y',
    'hostcode' => 'A',
    'procavs' => 'D',
    'proccvv2' => 'Y',
    'visacardlevel' => 'G1',
    'iavs' => 'N',
    'result_code' => '0',
  ),
) {"is_exception":false} []

**Comment by sreejith-cb** [comment] 2016-11-10 16:16
Why does magento 2.1 use paypal trxntype S instead of trxntype D while invoicing even when we are using Paypal 'Authorization' payment action for delayed capture? Is this a bug or is there a way we can switch this to D?

**Comment by YevSent** [comment] 2016-11-11 15:20
Hi @sreejith-cb, thanks for reporting. But I can't reproduce your issue. 
Now, to capture transaction we send `'trxtype' => 'D' (Delayed Capture), one exception is partial invoicing.
For example, you created order with two products.
1. You create and invoice for the first product -> `trxtype` will be `D`.
2. You create a second invoice for the second product -> `trxtype` will be `S`.

Could you specify more details? Do you use partial invoicing?

**Comment by sreejith-cb** [comment] 2016-11-14 14:22
We are not using partial invoicing. In our case magento does to send trxtype => D to paypal.
Only A and S seems to be transferred. Is there any other settings needs to be changed in magento admin or paypal inorder to send trxtype' => D. We are using magento 2.1.0

**Comment by YevSent** [comment] 2016-11-14 15:48
@sreejith-cb, this issue is already fixed (MAGETWO-59124) and will be available in Magento 2.1.3.

Closed as duplicate to https://github.com/magento/magento2/issues/6716 .

**Closed as completed by YevSent** 2016-11-14 15:48 UTC
Labels: bug report, Progress: needs update, Component: Payment
