### ISSUE TITLE
Some Translation not working in Safari browser Private Mode.

### ISSUE THREAD

**Issue by pareshe** [magento/magento2#7329] opened 2016-11-05 11:43 UTC
#  **Some Translation not Working in Safari Browser Private Mode**

## **Preconditions**

1) Open magento2 in safari browser private mode, in mac os/iPhone/iPad.

2) Add product to cart and check minicart .

Private mode safari -- http://www.awesomescreenshot.com/09b66b4z01
Normal mode safari -- http://www.awesomescreenshot.com/02866b4y67

3) Also same problem in www.website.com/checkout  - page.

## **Steps to reproduce**

1) Open magento2 in safari browser private mode, in mac os/iPhone/iPad.

2) Add product to cart and check minicart .

3) Also same problem in www.website.com/checkout  - page.

## **Actual and Expected result**

**_Actual:_**
"Go to Checkout","Qty","View and edit cart" etc. not translated.

**_Expected result:_**

"Go to Checkout","Qty","View and edit cart" etc. have to translate

## **Additional information**

Translation using Below method not working
1)<!-- ko i18n: 
2)data-bind="i18n:

**Comment by veloraven** [comment] 2016-11-09 12:09
@pareshe thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by pareshe** [comment] 2016-11-12 06:40
# **Some Translation not Working in Safari Browser Private Mode**

## **Magento version : 2.1.2**

## **Preconditions**

1) Open magento2 in safari browser private mode, in mac os/iPhone/iPad.

2) Add product to cart and check minicart .

Private mode safari -- http://www.awesomescreenshot.com/09b66b4z01
Normal mode safari -- http://www.awesomescreenshot.com/02866b4y67

3) Also same problem in www.website.com/checkout  - page.

## **Steps to reproduce**

1) Open magento2 in safari browser private mode, in mac os/iPhone/iPad.

2) Add product to cart and check minicart .

3) Also same problem in www.website.com/checkout  - page.

## **Actual and Expected result**

**_Actual:_**
"Go to Checkout","Qty","View and edit cart" etc. not translated.

**_Expected result:_**

"Go to Checkout","Qty","View and edit cart" etc. have to translate

## **Additional information**

Translation using Below method not working
1)<!-- ko i18n: 
2)data-bind="i18n:

**Comment by veloraven** [comment] 2016-11-16 09:19
@pareshe thank you for update.
Please specify exact Magento version you are running.

**Comment by pareshe** [comment] 2016-11-16 09:29
updated in issue. (Magento version : 2.1.2)

**Comment by Khaleel** [comment] 2016-12-18 10:59
Has anything to do with localStorage in Safari as sometimes my translations similar to the above work and sometimes they do not?

**Comment by naydav** [comment] 2017-02-03 15:00
Closed as a duplicate of #7942 (has the same initial problem with local storage)
Also, We've created internal ticket MAGETWO-63635 to address this issue.
Thanks

**Closed as completed by naydav** 2017-02-03 15:00 UTC
Labels: bug report, Component: Translation
