### ISSUE TITLE
Checkout Page Loading Issue

### ISSUE THREAD

**Issue by ia-gaurav** [magento/magento2#37320] opened 2023-03-31 12:28 UTC
### Preconditions and environment

Checkout page loading time is issue

### Steps to reproduce

Open Checkout Page after adding products to cart as Guest

### Expected result

Checkout field should be loaded instant 

### Actual result

Checkout form fields comes with delay of 5 seconds and it is noticeable in mobile

### Release note

2.4.1

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-03-31 13:18
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-03-31 13:52
Hi @ia-gaurav,


Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

**Steps to reproduce**

- Open Checkout Page after adding products to cart as Guest


https://user-images.githubusercontent.com/51680745/229138862-9a2d0046-d67b-4084-9252-57994ea9e814.mov




Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by ia-gaurav** [comment] 2023-03-31 19:36
@engcom-Bravo  as you can see in you video also , there is loader that take 2-3 seconds and in mobile it is sometime 4 - 6 seconds in 3 g mobile , form elements come with delay ,  want to show form element as soon page loads

**Comment by ia-gaurav** [comment] 2023-03-31 19:54
@engcom-Bravo  issue confirmed - goto network set mode as FAST 3G, it take around 5-10 seconds in mobile to show form 

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.04.01-01_20_50.webm](https://user-images.githubusercontent.com/63009790/229216730-fce9efb8-6787-48ce-a94d-e3f9285a031f.webm)

**Comment by engcom-Bravo** [comment] 2023-04-03 14:48
Hi @ia-gaurav,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

We have set mode as `FAST 3G` in network tab.


<img width="1432" alt="Screenshot 2023-04-03 at 6 45 36 PM" src="https://user-images.githubusercontent.com/51680745/229521527-7872d3a7-f966-4515-b778-ded8116111cc.png">




https://user-images.githubusercontent.com/51680745/229521553-9b5346f9-4a67-4c95-a2ea-a468608e712e.mov




Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.


Thanks.

**Comment by maghamed** [comment] 2023-04-03 17:53
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-04-04 10:37
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-04-04 14:47
Hi @ia-gaurav,

Thanks for your update.

We have set mode as FAST 3G in network tab.


Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

We have checked in Mobile.



https://user-images.githubusercontent.com/51680745/229775820-12bf35ee-01f6-4979-b5df-c13bc29fb209.mp4




https://user-images.githubusercontent.com/51680745/229776438-dfa103be-eee4-45bb-8962-7f3bed3b4d71.mov



Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.


it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.

Thanks

**Comment by engcom-Bravo** [comment] 2023-04-13 11:31
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-04-13 13:53
Hi @ia-gaurav,

Thanks for your update.

We have set mode as FAST 3G in network tab.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

We are getting checkout page for guest customer with 1-2 seconds.


https://user-images.githubusercontent.com/51680745/231752582-0fab345e-861c-4e0e-a48c-083100a55715.mov




Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-04-25 06:02
Hi @ia-gaurav,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-04-25 06:02 UTC
Labels: Issue: needs update, Reported on 2.4.1
