### ISSUE TITLE
S3 remote storage processes prefix setting incorrectly

### ISSUE THREAD

**Issue by speller** [magento/magento2#35056] opened 2022-02-03 12:22 UTC
### Steps to reproduce (*)

Configuration:
```php
    $env['system'] = [
        'default' => [
            'media_storage_configuration' => [
                'media_database' => 0,
            ],
        ],
    ];
    $env['remote_storage'] = [
        'driver' => 'aws-s3',
        'prefix' => 'prefix',
        'config' => [
            'bucket' => 'bucket',
            'region' => 'ap-northeast-1',
        ]
    ];
```

### Expected result (*)
The `AwsS3Factory::createConfigured()` method generates the following `$objectUrl` value:
```none
https://bucket.s3.ap-northeast-1.amazonaws.com/prefix/
```

### Actual result (*)
The `AwsS3Factory::createConfigured()` method generates the following `$objectUrl` value:
```none
https://bucket.s3.ap-northeast-1.amazonaws.comprefix/
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

The issue is in the following line: https://github.com/magento/magento2/blob/4cc763c416aba1c30cefede0074793d67f60051a/app/code/Magento/AwsS3/Driver/AwsS3Factory.php#L136 

It truncates slashes around prefix and joins the prefix to the URL without adding a slash before it. So even passing the `/prefix` value doesn't solve the issue producing a broken URL.

**Comment by speller** [comment] 2022-02-03 13:30
The following patch solves the issue:

```diff
diff --git a/Driver/AwsS3Factory.php b/Driver/AwsS3Factory.php
--- a/Driver/AwsS3Factory.php
+++ b/Driver/AwsS3Factory.php
@@ -131,3 +131,4 @@ public function createConfigured()
         );
-        $objectUrl = rtrim($client->getObjectUrl($config['bucket'], './'), '/') . trim($prefix, '\\/') . '/';
+        $trimmedPrefix = trim($prefix, '\\/');
+        $objectUrl = rtrim($client->getObjectUrl($config['bucket'], './'), '/') . ($trimmedPrefix ? '/' . $trimmedPrefix : '' ) . '/';
         return $this->objectManager->create(

```

**Comment by engcom-Hotel** [comment] 2022-03-15 11:28
Hello @speller,

We have tried to reproduce this issue in Magento 2.4-develop branch but for us, the issue is not reproducible. We have followed below steps:

1. Configure S3 in Magento by following this [article](https://devdocs.magento.com/guides/v2.4/config-guide/remote-storage/config-remote-storage-aws-s3.html).
2. Create a product from the admin panel with an image.
3. Verify that image has been synced with S3.
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/51681618/158368017-657208ea-b599-4296-b0ab-cf10625928a4.png">
4. Save the image and check frontend, product detail page:
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/51681618/158368185-35da539a-82f0-4f31-a0f7-887086931583.png">

Please let us know in case we have missed any steps in order to reproduce the issue.

Thanks

**Comment by speller** [comment] 2022-03-15 11:56
@engcom-Hotel Did you configure the prefix? What was its value? Do you see the issue in the code I've highlighted that the prefix value is concatenated to the bucket URL without the delimiter?

**Comment by engcom-Hotel** [comment] 2022-03-16 06:39
Hello @speller,

Yes, I have used the prefix. Please refer to the configuration below related to S3 from `env.php` file:
```
'remote_storage' => [
        'driver' => 'aws-s3',
        'prefix' => 'testprefix',
        'config' => [
            'bucket' => 'bucket',
            'region' => 'us-east-1'
        ]
    ],
```
Also checked the code. But the issue is still not reproducible for us. Please let us know in case we have missed anything.

Thanks

**Comment by speller** [comment] 2022-03-17 04:25
@engcom-Hotel Actually in my code I'm uploading a custom image. Maybe the flow is different in my case and in the sample you're using? In your case, is the `AwsS3Factory::createConfigured()` method used in the execution flow? Could you use a debugger, stop on the line I've mentioned and check how it works?
In my code, I'm using `Magento\MediaStorage\Model\File\UploaderFactory->create()->save()` and it was not working correctly.

**Comment by engcom-Hotel** [comment] 2022-03-21 10:40
Hello @speller,

Thanks for your response!

We have tried to debug the code and by looking into the code and debugging, the issue has been reproducible. Please have a look at the screenshot for reference:

![1](https://user-images.githubusercontent.com/51681618/159245136-63b1168d-ca07-4a77-8c00-9cb3095524c6.jpg)

But still, the functionality is working fine of uploading the images from Admin. Can you please suggest some other steps or your use case in order to reproduce the issue?

Thanks

**Comment by engcom-Hotel** [comment] 2022-04-04 06:16
Dear @speller,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-04-04 06:16 UTC
Labels: Triage: Dev.Experience, Issue: needs update

**Comment by MartynasKasp** [comment] 2022-04-06 07:44
@engcom-Hotel yes, image uploads are working fine with S3 bucket, but the issue occurs when trying to upload tablerates import file in "Sales / Delivery Methods / Table rates" section. It gives an error which says `"The "https://*.s3.eu-west-2.amazonaws.comuat/tmp/phpCWCyKY" file doesn't exist."` As you can see there is definitely a slash missing after `.com`
