### ISSUE TITLE
There is no minification of javascript UiComponents files which are injected by Layout Processor

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#35511] opened 2022-05-20 18:45 UTC
### Preconditions and environment

- Magento version: 2.4.3 / 2.4.4

### Steps to reproduce

1. Create a frontend `plugin` for checkout `Layout Processor` which will modify checkout structure and a new UiComponent to the checkout configuration / UiComponent configuration
```
<type name="Magento\Checkout\Block\Checkout\LayoutProcessor">
```
and add `afterProcess` plugin and add your uiComponent anywhere on the checkout page / fields / forns. 
```
public function afterProcess(
        LayoutProcessor $subject,
        array $jsLayout
    ): array {
[...]
}
```

2. Enable Javascript minification

- Enable production mode``

### Expected result

UiComponent javascript minified files are created and the browser can access them + they are rendered and processed.

### Actual result

404 error on minified js files related to UiCompoments

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2022-07-26 05:09
Hello @qsolutions-pl,

Thanks for the report and collaboration!

We have tried to reproduce the issue in Magento 2.4-develop branch and the issue seems reproducible for us via the below steps:

1. Created After Plugin for `Magento\Checkout\Block\Checkout\LayoutProcessor :: Process()` under `app/code/Magento/Checkout/etc/frontend/di.xml`.
2. Minifying JavaScript files:
`bin/magento config:set dev/js/minify_files 1`
3. Enable Production Mode:
`bin/magento deploy:mode:set production`
4. Go to Storefront, Add Product to Cart, go to Checkout Page, and given below error is reported:
![image](https://user-images.githubusercontent.com/51681618/180927895-3d42155e-2f79-4541-a652-b4027fb9a3ed.png)

Hence confirming the issue.

Thanks

**Comment by engcom-Hotel** [comment] 2024-10-10 12:00
Hello @jakwinkler,

It seems the issue is no longer reproducible in the latest development branch i.e. 2.4-develop. Please refer to the below screenshot for reference:

![image](https://github.com/user-attachments/assets/7a7a72cb-0572-4688-9764-12871dab6f16)

Hence we are closing this issue. Please let us know if you are still able to reproduce the issue in the latest development branch.

Thanks

**Closed as completed by engcom-Hotel** 2024-10-10 12:00 UTC
Labels: Issue: Confirmed, Component: Ui, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Framework
