### ISSUE TITLE
Product design option "Display Product Options In" does not affect layout

### ISSUE THREAD

**Issue by melaxon** [magento/magento2#20256] opened 2019-01-13 18:36 UTC
### Preconditions (*)

1. 2.3.0, 2.2.6, may be earlier versions as well
2. Fresh installation, Luma

### Steps to reproduce (*)

1. Install Magento and create a product of any type: simple, configurable, downloadable,...
2. Add some Customizable Options
3. Open the same product in frontend in 2 separate browser tabs to compare them
4. Change: Design -> "Display Product Options In" and save
5. Refresh one browser tab and compare with another tab

### Expected result (*)

1. The layout must be different

### Actual result (*)

1. The setting "Display Product Options In" will not change anything.

**Comment by magento-engcom-team** [comment] 2019-01-13 18:36
Hi @melaxon. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@melaxon do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [x] no

**Comment by melaxon** [comment] 2019-01-13 18:37
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment] 2019-01-13 18:38
Hi @melaxon. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment] 2019-01-13 18:38
Hi @melaxon, here is your [Magento instance](https://i-20256-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-20256-2-3-0.instances.magento-community.engineering/admin](https://i-20256-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-01-13 18:48
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment] 2019-01-13 19:05
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-01-13 19:05
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-01-13 19:05
Hi @shikhamis11, here is your [Magento instance](https://i-20256-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20256-2-3-develop.instances.magento-community.engineering/admin](https://i-20256-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2019-01-13 19:16
@melaxon I tried with test product with both the Design options . But at frontend the position of the custom options are same

**Comment by magento-engcom-team** [comment] 2019-01-13 19:18
@shikhamis11 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97607`, `MAGETWO-97608` were created

**Comment by melaxon** [comment] 2019-01-13 19:32
Actually I can remember that only on Magento1 this settings worked, but everytime "container2" was used (Product Info Column) because otherwise the options must be moved under the image. I cannot imagine this to look nice. So I suggest you remove this setting completely and I'm pretty sure the quality of Magento will not suffer. For those who wish another layout anyway there is always a choice to edit phtml file and/or play with css - not a big deal

**Comment by awviraj** [comment] 2019-01-28 08:34
If options are moved outside the product_addtocart_form, add to cart won't work.

**Comment by shachiarkatkar** [comment] 2019-02-03 05:13
I am working on this #mm19in

**Comment by magento-engcom-team** [comment] 2019-02-03 05:13
@shachiarkatkar thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment] 2019-02-03 05:14
Hi @shachiarkatkar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by shachiarkatkar** [comment] 2019-02-03 05:15
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-03 05:15
Hi @shachiarkatkar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-03 05:16
Hi @shachiarkatkar, here is your [Magento instance](https://i-20256-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20256-2-3-develop.instances.magento-community.engineering/admin](https://i-20256-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shachiarkatkar** [comment] 2019-02-03 10:18
In Magento 1, the position of custom options was differentiable in two containers (Container1 and Container 2)

1. Below Short Description(Container 1)
`<?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif;?>`
2. After the product image(Container 2)
` <div class="clearer"></div>
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>`
Please check following file:
app/design/frontend/base/default/template/catalog/product/view.phtml

In Magento 2 both, the conditions are working properly, but the HTML rendered is at the same place. 
Please check app/code/Magento/Catalog/view/frontend/templates/product/view/form.phtml
I tried to put different wrappers and on the wrappers were changed based on the option selected in the Design tab.

```
 <?php if ($_product->isSaleable() && $block->getOptionsContainer() == 'container1'):?>
                <div class="contaniner1"><?= $block->getChildChildHtml('options_container') ?></div>
            <?php endif;?>
        <?php endif; ?>

        <?php if ($_product->isSaleable() && $block->hasOptions() && $block->getOptionsContainer() == 'container2'):?>
            <div class="contaniner2"><?= $block->getChildChildHtml('options_container') ?></div>
        <?php endif;?>
```

Here are screenshots of the product page after adding containers:

Container 1:
![image](https://user-images.githubusercontent.com/2101412/52175442-e8411580-27c9-11e9-93f4-ceb76ab3693b.png)
Container 2:
![image](https://user-images.githubusercontent.com/2101412/52175436-d19abe80-27c9-11e9-8169-cfd37b22d1ad.png)


You can customize the changes in custom theme, the changes will be reflected correctly in the frontend. The condition works correctly.

**Comment by dmanners** [comment] 2019-05-07 14:54
Thank you @melaxon having looked at the detailed review done by @shachiarkatkar (https://github.com/magento/magento2/issues/20256#issuecomment-460039386) I will close this as the code is in fact switching containers but the default theme has no difference. If you feel this is still not correct please reach out so we can gather a bit more information.

**Closed as completed by dmanners** 2019-05-07 14:54 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Area: Design/Frontend, Event: mm19in

**Comment by JithinTerrificminds** [comment] 2022-01-19 08:20
Just in case if anyone needs : https://magento.stackexchange.com/a/352164/81418
