### ISSUE TITLE
Error when importing products via CSV file

### ISSUE THREAD

**Issue by eeeduuu** [magento/magento2#25951] opened 2019-12-08 13:20 UTC
1. Magento CE 2.3.3 without sample data is installed
2. He creates 2 websites (www.web1.com and www.web2.com)

Steps to reproduce
============
1. I generate a CSV file with the information of the products I want to import.
2. Following the instructions in the Magento documentation, I leave the column "website_id" empty because I want the products to be available at www.web1.com and www.web2.com.
3. The indications of Magento are as follows: **"For installations with multiple websites, identifies a specific website where the product is available. If blank, the product is available in all websites."**
4. When I import the CSV file I receive the following message: "Invalid value in Website columns (website does not exist?) in rows...".
5. I tried to remove the column in case there was any conflict with the "empty" value of the column, but the result was the same.

Expected result
==========
1. That the products be imported and that they be available for both websites (www.web1.com and www.web2.com).

Actual result
========
1. I include the spreadsheet with the import error output that Magento generates.
2. In the "CH" column of the spreadsheet you can see the description of the error indicated.

[1575808675_Tmp-ImportacioProductesExqlusives_error_report.xlsx](https://github.com/magento/magento2/files/3936253/1575808675_Tmp-ImportacioProductesExqlusives_error_report.xlsx)

**Comment by engcom-Echo** [comment] 2019-12-09 10:12
Hello @eeeduuu 

Thank you for your report and collaboration!
I am not able to reproduce this issue on the 2.4-develop branch by provided steps.

**Testing scenario:**

**Preconditions:**
1. Magento CE 2.4 without sample data is installed
2. Created 2 sites.
3. Products have been assigned to each site.

**Steps to reproduce:**

1. Generate a CSV file with the information of the products
2. Import previously generated the CSV file
![pro](https://user-images.githubusercontent.com/51681435/70425940-d760d080-1a7a-11ea-8eef-0528a41642d4.png)
![web1](https://user-images.githubusercontent.com/51681435/70425946-da5bc100-1a7a-11ea-8ff1-68855ad6c959.png)
**Result**
Import is successful. Products are available on both websites. No errors.
![import](https://user-images.githubusercontent.com/51681435/70425716-5b668880-1a7a-11ea-8203-ab7ce5c8084d.png)
![import1](https://user-images.githubusercontent.com/51681435/70425725-5e617900-1a7a-11ea-85d2-6b937d271a20.png)

So I have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Echo** 2019-12-09 10:12 UTC
Labels: Issue: Format is not valid
