### ISSUE TITLE
Show / hide editor is no working 

### ISSUE THREAD

**Issue by rzaragosin** [magento/magento2#22457] opened 2019-04-22 17:01 UTC
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description] 
![show-hide editor not working](https://user-images.githubusercontent.com/49878598/56513091-52cb3d00-64ff-11e9-9279-8b23241efc82.png)

2.
###

**Comment by krishprakash** [comment] 2019-04-22 17:17
Hi @rzaragosin. Thank you for your report.
Please explain the issue in proper issue format.
In which magento version you phase this issue ?
Explain in description

**Comment by rzaragosin** [comment] 2019-04-22 17:30
hi guys, thanks for your comments. 
I'm working in Magento 2.2.4
I'm not using any extension 
I tried in all the browser and didn't work either. I can edit any product, I just available to edit the price.

**Comment by krishprakash** [comment] 2019-04-22 18:03
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-04-22 18:03
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-22 18:04
Hi @krishprakash, here is your [Magento instance](https://i-22457-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22457-2-2-develop.instances.magento-community.engineering/admin](https://i-22457-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2019-04-22 18:31
Hi @rzaragosin. I'm not able to reproduce this issue.
Can you please explain with proper reproducible steps

**Comment by krishprakash** [comment] 2019-05-01 07:05
Hi @rzaragosin. Please follow issue reporting guideline to report an issue
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
Also please mention additional details about the issue

**Comment by krishprakash** [comment] 2019-05-06 06:28
Hi @rzaragosin. 
I'm closing this issue as not able to reproduce and still no any reproducible steps provided by you.
Feel free to reopen this ticket if you phase this issue on latest magento instance.
Thank you.

**Closed as completed by krishprakash** 2019-05-06 06:28 UTC
Labels: Progress: needs update, Issue:  Cannot Reproduce, Issue: Format is valid
