### ISSUE TITLE
Magento 2.4.2-p1 multi-attribute products and single-attribute products have an error at the checkout of the shopping cart

### ISSUE THREAD

**Issue by Skyfly2021** [magento/magento2#33153] opened 2021-06-05 07:59 UTC
### Preconditions (*)

1.Magento 2.4.2-p1
2.Php 7.4
3.mysql 8.0
4.centos 8.0

### Steps to reproduce (*)

1.When you first add multiple products without attributes to the shopping cart, and then add a product with multiple attributes (color, size, style, etc.) to the shopping cart, click on the checkout, and an error like the attached picture will appear. Add products in this order. There will be an error
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.![image](https://user-images.githubusercontent.com/53896477/120884387-856c1d00-c615-11eb-8544-eef9256ea086.png)
![image](https://user-images.githubusercontent.com/53896477/120884421-b9474280-c615-11eb-856e-ca6ea86eb45d.png)
Products without attributes
![image](https://user-images.githubusercontent.com/53896477/120884630-b4cf5980-c616-11eb-811e-155fc4787d94.png)
Multi-attribute products
![image](https://user-images.githubusercontent.com/53896477/120884651-dd575380-c616-11eb-90b3-aba22f5d5cac.png)

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment] 2021-06-09 08:24
Hi @yanhaiwen2019 
As per the first step, I have added simple products first and then added multi-attribute products. Hope it is correct.
Not able to reproduce the issue in 4.2-develop version.

https://user-images.githubusercontent.com/51679138/121319712-18fd6080-c92a-11eb-8a56-527c939e3d89.mp4

Kindly try reproducing in 4.2 latest and possibly share us the screen record of the reproducible steps.

**Comment by yanhaiwen2019** [comment] 2021-06-14 14:52
Hi:
   Please ensure that the multi-attribute products are ranked in the top1 position, you can try it on my website, www.ineffablegoods.com<http://www.ineffablegoods.com>
Ineffable Goods<http://www.ineffablegoods.com/>
Sell high-quality and low-cost products to improve the quality of life for everyone
www.ineffablegoods.com


________________________________
发件人: Manjunath ***@***.***>
发送时间: 2021年6月9日 16:24
收件人: magento/magento2 ***@***.***>
抄送: yanhaiwen2019 ***@***.***>; Mention ***@***.***>
主题: Re: [magento/magento2] Magento 2.4.2-p1 multi-attribute products and single-attribute products have an error at the checkout of the shopping cart (#33153)


Hi @yanhaiwen2019<https://github.com/yanhaiwen2019>
As per the first step, I have added simple products first and then added multi-attribute products. Hope it is correct.
Not able to reproduce the issue in 4.2-develop version.

https://user-images.githubusercontent.com/51679138/121319712-18fd6080-c92a-11eb-8a56-527c939e3d89.mp4

Kindly try reproducing in 4.2 latest and possibly share us the screen record of the reproducible steps.

―

**Comment by yanhaiwen2019** [comment] 2021-06-14 14:54
HI
[cid:f5f96935-40e3-466e-8cfc-9b84ff7aee29]
Please click the proceed to checkout button to get an error
________________________________
发件人: Manjunath ***@***.***>
发送时间: 2021年6月9日 16:24
收件人: magento/magento2 ***@***.***>
抄送: yanhaiwen2019 ***@***.***>; Mention ***@***.***>
主题: Re: [magento/magento2] Magento 2.4.2-p1 multi-attribute products and single-attribute products have an error at the checkout of the shopping cart (#33153)


Hi @yanhaiwen2019<https://github.com/yanhaiwen2019>
As per the first step, I have added simple products first and then added multi-attribute products. Hope it is correct.
Not able to reproduce the issue in 4.2-develop version.

https://user-images.githubusercontent.com/51679138/121319712-18fd6080-c92a-11eb-8a56-527c939e3d89.mp4

Kindly try reproducing in 4.2 latest and possibly share us the screen record of the reproducible steps.

―

**Comment by yanhaiwen2019** [comment] 2021-06-14 15:01
hi


Sent from my iPhone

On 14 Jun 2021, at 10:52 PM, yan haiwen ***@***.***> wrote:

﻿
Hi:
   Please ensure that the multi-attribute products are ranked in the top1 position, you can try it on my website, www.ineffablegoods.com<http://www.ineffablegoods.com>
Ineffable Goods<http://www.ineffablegoods.com/>
Sell high-quality and low-cost products to improve the quality of life for everyone
www.ineffablegoods.com


________________________________
发件人: Manjunath ***@***.***>
发送时间: 2021年6月9日 16:24
收件人: magento/magento2 ***@***.***>
抄送: yanhaiwen2019 ***@***.***>; Mention ***@***.***>
主题: Re: [magento/magento2] Magento 2.4.2-p1 multi-attribute products and single-attribute products have an error at the checkout of the shopping cart (#33153)


Hi @yanhaiwen2019<https://github.com/yanhaiwen2019>
As per the first step, I have added simple products first and then added multi-attribute products. Hope it is correct.
Not able to reproduce the issue in 4.2-develop version.

https://user-images.githubusercontent.com/51679138/121319712-18fd6080-c92a-11eb-8a56-527c939e3d89.mp4

Kindly try reproducing in 4.2 latest and possibly share us the screen record of the reproducible steps.

**Comment by engcom-Alfa** [comment] 2021-06-17 05:43
Hi @yanhaiwen2019 
Well, I should be able to reproduce the issue in the latest Magento version _2.4-develop_ in order to accept it and to fix it. Kindly help me with more and more detailed information about like what type of product you are trying to checkout and what is the sequence of product you are following in order to add to the cart etc.
Because as you said, I clicked on the "Proceed to Checkout" once after adding to cart", still not able to reproduce.
So, kindly do the needful.

To reproduce it in our Magento default environment, you may hit the command to the Magento's git bot like: "@magento give me 2.4-develop instance". [Here is the example](https://github.com/magento/magento2/issues/29248#issuecomment-856736154).
So, once after getting the instance prepared for you by bot, you can reproduce in that instance.
Once reproducing, please reply me the proper steps to reproduce (also the product names you have used in this instance).
Moreover, screen recording will help me us a lot in these kind of scenarios.

**Comment by yanhaiwen2019** [comment] 2021-06-17 07:54
Hi:
    I first add a single attribute product, and finally add a multi-attribute product, and click the "proceed to checkout" button. You must follow this order to make an error,
You can try it directly on this website (www.ineffablegoods.com).
________________________________
发件人: Manjunath ***@***.***>
发送时间: 2021年6月17日 13:43
收件人: magento/magento2 ***@***.***>
抄送: yanhaiwen2019 ***@***.***>; Mention ***@***.***>
主题: Re: [magento/magento2] Magento 2.4.2-p1 multi-attribute products and single-attribute products have an error at the checkout of the shopping cart (#33153)


Hi @yanhaiwen2019<https://github.com/yanhaiwen2019>
Well, I should be able to reproduce the issue in the latest Magento version 2.4-develop in order to accept it and to fix it. Kindly help me with more and more detailed information about like what type of product you are trying to checkout and what is the sequence of product you are following in order to add to the cart etc.
Because as you said, I clicked on the "Proceed to Checkout" once after adding to cart", still not able to reproduce.
So, kindly do the needful.

To reproduce it in our Magento default environment, you may hit the command to the Magento's git bot like: ***@***.***<https://github.com/magento> give me 2.4-develop instance". Here is the example<https://github.com/magento/magento2/issues/29248#issuecomment-856736154>.
So, once after getting the instance prepared for you by bot, you can reproduce in that instance.
Once reproducing, please reply me the proper steps to reproduce (also the product names you have used in this instance).
Moreover, screen recording will help me us a lot in these kind of scenarios.

―

**Comment by yanhaiwen2019** [comment] 2021-06-17 07:58
Hi
   On the website you gave, this problem does not exist. The problematic version is Magento 2.4.2-p1, and the previous version did not have this problem.
________________________________
发件人: Manjunath ***@***.***>
发送时间: 2021年6月17日 13:43
收件人: magento/magento2 ***@***.***>
抄送: yanhaiwen2019 ***@***.***>; Mention ***@***.***>
主题: Re: [magento/magento2] Magento 2.4.2-p1 multi-attribute products and single-attribute products have an error at the checkout of the shopping cart (#33153)


Hi @yanhaiwen2019<https://github.com/yanhaiwen2019>
Well, I should be able to reproduce the issue in the latest Magento version 2.4-develop in order to accept it and to fix it. Kindly help me with more and more detailed information about like what type of product you are trying to checkout and what is the sequence of product you are following in order to add to the cart etc.
Because as you said, I clicked on the "Proceed to Checkout" once after adding to cart", still not able to reproduce.
So, kindly do the needful.

To reproduce it in our Magento default environment, you may hit the command to the Magento's git bot like: ***@***.***<https://github.com/magento> give me 2.4-develop instance". Here is the example<https://github.com/magento/magento2/issues/29248#issuecomment-856736154>.
So, once after getting the instance prepared for you by bot, you can reproduce in that instance.
Once reproducing, please reply me the proper steps to reproduce (also the product names you have used in this instance).
Moreover, screen recording will help me us a lot in these kind of scenarios.

―

**Comment by engcom-Alfa** [comment] 2021-06-18 07:47
@magento give me 2.4.2-p1 instance

**Comment by engcom-Alfa** [comment] 2021-06-18 09:15
@Skyfly2021 
Though if there in issue in your application, in order to fix any issue in Magento code, the issue should be reproducible in Magento 2.4-develop version.
Well anyhow I have requested for 2.4.2-p1 version as well in my last comment and tried there. Still not able to reproduce it in 2.4.2-p1 version.
As you suggested, I have tried adding simple products first and  then configurable product. Below are the screenshots.

![image](https://user-images.githubusercontent.com/51679138/122537034-c9621780-d042-11eb-83e2-0564fb094a38.png)

![image](https://user-images.githubusercontent.com/51679138/122537127-df6fd800-d042-11eb-80a5-8787819f215c.png)

Clicked "Proceed to checkout" as well, and worked well without any issues.

You may access the above instance with the version 2.4.2-p1 version, and reproduce it please. If you are able to do so, then as requested in my previous comments- kindly give me detailed step by step procedure like: what is the product name you are going to add first and then which the second product name you are adding and so on.
Since it is a Magento instance, I can also access the same instance, I can repeat with the same product names.

**Comment by Skyfly2021** [comment] 2021-06-19 06:47
Hi:
   I uninstall the facebook plugin, and then composer update
This problem no longer appears, thank you very much for your patient reply.
________________________________
发件人: Manjunath ***@***.***>
发送时间: 2021年6月18日 17:15
收件人: magento/magento2 ***@***.***>
抄送: Skyfly ***@***.***>; Mention ***@***.***>
主题: Re: [magento/magento2] Magento 2.4.2-p1 multi-attribute products and single-attribute products have an error at the checkout of the shopping cart (#33153)


@Skyfly2021<https://github.com/Skyfly2021>
Though if there in issue in your application, in order to fix any issue in Magento code, the issue should be reproducible in Magento 2.4-develop version.
Well anyhow I have requested for 2.4.2-p1 version as well in my last comment and tried there. Still not able to reproduce it in 2.4.2-p1 version.
As you suggested, I have tried adding simple products first and then configurable product. Below are the screenshots.

[image]<https://user-images.githubusercontent.com/51679138/122537034-c9621780-d042-11eb-83e2-0564fb094a38.png>

[image]<https://user-images.githubusercontent.com/51679138/122537127-df6fd800-d042-11eb-80a5-8787819f215c.png>

Clicked "Proceed to checkout" as well, and worked well without any issues.

You may access the above instance with the version 2.4.2-p1 version, and reproduce it please. If you are able to do so, then as requested in my previous comments- kindly give me detailed step by step procedure like: what is the product name you are going to add first and then which the second product name you are adding and so on.
Since it is a Magento instance, I can also access the same instance, I can repeat with the same product names.

―

**Comment by engcom-Alfa** [comment] 2021-06-21 07:23
As the reporter found solution, there is no more existence of the reported issue. Hence closing this current issue.

Kindly upgrade to the latest version and for any Magento related issues, you may please report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings possibly.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).

**Closed as completed by engcom-Alfa** 2021-06-21 07:23 UTC
Labels: Issue: needs update, Reported on 2.4.2-p1
