### ISSUE TITLE
Can't use https://www.graphqlbin.com/v2/new

### ISSUE THREAD

**Issue by oefterdal** [magento/magento2#37192] opened 2023-03-11 08:28 UTC
### Preconditions and environment

- 2.4.5

### Steps to reproduce

Go to: https://www.graphqlbin.com/v2/new
Enter: https://venia.magento.com/graphql

### Expected result

Possibility to query the api

### Actual result

Nothing

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by oefterdal** [comment] 2023-03-11 08:28
@magento give me 2.4-develop instance

**Comment by oefterdal** [comment] 2023-03-12 08:23
https://github.com/magento give me 2.4-develop instance

**Comment by oefterdal** [comment] 2023-03-12 09:49
<img width="1412" alt="Screenshot 2023-03-12 at 10 49 27" src="https://user-images.githubusercontent.com/1254741/224537032-12c22baa-6aea-4a7d-823d-0f91b936359c.png">

**Comment by oefterdal** [comment] 2023-03-12 09:51
Here is https://venia.magento.com/graphql

<img width="1412" alt="Screenshot 2023-03-12 at 10 50 32" src="https://user-images.githubusercontent.com/1254741/224537086-2cafddc6-d6f8-439c-b78a-00ae41e9e3c1.png">

**Comment by oefterdal** [comment] 2023-03-12 09:52
Magento Instance: https://fc028b8b231b22afe95e6a723030f149.instances-prod.magento-community.engineering/

<img width="1412" alt="Screenshot 2023-03-12 at 10 52 10" src="https://user-images.githubusercontent.com/1254741/224537150-19d92059-b4df-4937-8c27-1305b2e6222e.png">

**Comment by engcom-Dash** [comment] 2023-03-13 10:25
Hi @oefterdal ,

Thank you for reporting this ticket,

For better understanding could please share more information about steps to reproduce, Because i am unable to access your venia link,Hence would require to know whether in which environment are you trying install venia(PWA).

Additionally require below details aparts from steps:
1.Magento 2.4.6 Base link on top of if you are installing PWA.
2.Environment details like DEV/QA/PROTECTION

Regards,

**Comment by oefterdal** [comment] 2023-03-13 15:38
Past https://fc028b8b231b22afe95e6a723030f149.instances-prod.magento-community.engineering/graphql into https://www.graphqlbin.com/v2/new

**Comment by fooman** [comment] 2023-03-14 04:07
@oefterdal the errors in the screenshot indicate that this is related to [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) errors. I don't see this as something that needs to be addressed - if you wish to run your own instance you can set the headers in such a way that one can use [https://www.graphqlbin.com](https://www.graphqlbin.com/v2/new).

**Comment by oefterdal** [comment] 2023-03-14 09:17
@fooman  thank you, which headers do we need to set and where do we set them on the instance?

**Comment by fooman** [comment] 2023-03-14 09:20
@oefterdal that depends on your server setup. It could be done in the Nginx config for example. Another approach is to use https://github.com/graycoreio/magento2-cors. I don't think the test instances under magento-community.engineering will see this added.

**Comment by oefterdal** [comment] 2023-03-15 09:45
@engcom-Dash  How come the the altair chrome extension work?

**Comment by engcom-November** [comment] 2023-03-17 03:52
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2023-03-17 04:09
Hi @oefterdal ,
Thank you for the response. Verified the behavior on Magento 2.4-develop instance ans is reproducible however this is not Magento related issue. `https://www.graphqlbin.com/v2/new` is not part of https://github.com/magento/magento2/ repository and community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension/owners(support).
Alternatively Graphql operations can be performed using POSTMAN or Altair GraphL client chrome extension which can be downloaded from [here](https://chrome.google.com/webstore/detail/altair-graphql-client/flnheeellpciglgpaodhkhmapeljopja?hl=en)
Once the extension is downloaded on chrome browser, its easy to run any graphql query. Please refer the below screenshot for the same.
![image](https://user-images.githubusercontent.com/60198231/225810355-803b675f-bac0-4e28-93d6-9b23f8a42f1f.png)
Please refer below screenshot of POSTMAN UI where graphql operations can be performed:
![image](https://user-images.githubusercontent.com/60198231/225810506-5968f83f-422f-45d9-9dea-b0516fcb31a9.png)

**Comment by engcom-Bravo** [comment] 2023-03-30 07:33
Hi @oefterdal,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-03-30 07:33 UTC
Labels: Issue: needs update, Reported on 2.4.5
