### ISSUE TITLE
Free Ground Shipping (UPS) Message appear on paid shipping

### ISSUE THREAD

**Issue by liquidia** [magento/magento2#34762] opened 2021-12-05 19:24 UTC
### Preconditions (*)

1. Magento Version 2.3.4

### Steps to reproduce (*)

1. Create a discount coupon 
2. Use UPS Shipping API/Option
3. Apply discount coupon on cart page
4. "Free ground Shipping on this item" appears in bracket; even product with paid shipping.

### Expected result (*)

1. "Free ground Shipping on this item" should not appear after applying discount coupon when product has a paid shipping option only.

### Actual result (*)

1. ![Screen Shot 2021-12-06 at 12 52 28 AM](https://user-images.githubusercontent.com/12976268/144760487-a48fd9be-a9cd-42d4-9aea-8eaf5ed01896.png)

---

Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by engcom-November** [comment] 2021-12-24 11:05
Verified the issue on Magento 2.4-develop branch but the issue is not reproducible in both Shopping Cart page and Checkout pages.
![image](https://user-images.githubusercontent.com/60198231/147347535-b4668bc4-a4a8-4e5b-ac19-bf209048a396.png)
![image](https://user-images.githubusercontent.com/60198231/147347553-a8479ef7-3079-440f-b990-bf9c411c2a6f.png)
@liquidia kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-01-07 05:52
Hi @liquidia ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed** 2022-01-07 05:52 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.3.4
