### ISSUE TITLE
Magento 2.3 - After migration from 1.9 to 2.3 vendor/magento files missing

### ISSUE THREAD

**Issue by Jeeva-Rathinam** [magento/magento2#30744] opened 2020-11-02 04:58 UTC
### Summary (*)

After migration from Magento 1.9.2.3 to Magento 2.3.4 most of the files missing from **vendor/magento.**

But all the files located under **app/code/Magento**

Is this safe, shall i run my Magento 2.3.4 in this situation?

What about my future version upgrade?
### Examples (*)

Files not available under **vendor/magento** instead of available at **app/code/magento**
### Proposed solution

Shall i proceed with this situation?

**Comment by ihor-sviziev** [comment] 2020-11-02 10:35
@Jeeva-Rathinam did you use composer based installation?
https://devdocs.magento.com/guides/v2.4/install-gde/composer.html

**Comment by Jeeva-Rathinam** [comment] 2020-11-04 04:25
@ihor-sviziev I am using Github Installation. May i know the guide version upgrade for GitHub installation?

**Comment by ihor-sviziev** [comment] 2020-11-04 07:10
Hi @Jeeva-Rathinam,
The github installation should be used only for contribution some changes to magento core. In case of your own project you should use composer based installation. If you don't have any customizations - I would recommend you just do clean install of magento using composer and move your media, configs, etc to this new installation. DB should be just the same

**Comment by Jeeva-Rathinam** [comment] 2020-11-05 12:19
For the last 6 months, our website running, around 500 ordered placed, 2000 customer registered and so many customizations done.  Shall we continue this kind of Magento, what are all the issue will face in the future, what about version upgrade? Thank you

**Comment by ihor-sviziev** [comment] 2020-11-05 12:25
@Jeeva-Rathinam basically if you'll install the same magento version as you had on github installation - you'll have the same code. The issue with github installation - it also contains not released changes that potentially could cause some issues for your website. 
I would strongly recommend you to switch to the composer based installation for production in order to have stable project. But please be careful and make sure you're not downgrading your magento.

Please review the following article when you should use different type of magento installations: https://devdocs.magento.com/guides/v2.4/install-gde/bk-install-guide.html

**Comment by ihor-sviziev** [comment] 2020-11-13 08:03
Hi @Jeeva-Rathinam,
I'm closing this issue as it caused by using github based installation that designed only for contributions and it's described in the docs.

**Closed as completed by ihor-sviziev** 2020-11-13 08:03 UTC
Labels: Triage: Dev.Experience, Issue: needs update
