### ISSUE TITLE
Admin Order Shipping Address Please Wait Loading on Every Field

### ISSUE THREAD

**Issue by trucatchtraps** [magento/magento2#16867] opened 2018-07-16 21:55 UTC
### Summary
New order in Admin Panel, edit Shipping Address, receive a Please Wait Loading icon for every field. Cannot tab through the fields to quickly fill them in while talking with customer. 

Same order, enter Credit Cart information, then edit Shipping Address, Credit Card information is removed.  

### Preconditions
1. Magento 2.2.3 (dev site is Magento 2.2.5 happening as well)
2. From what I understand it has been happening since Magento2 was launched
3. PHP 7.1.12
4. MySQL 5.0.12

### Steps to reproduce
1. Login to Admin Panel
2. Sales -> Orders
3. Create New Order
4. Create New Customer or Select Customer
5. Uncheck Same As Billing Address
6. Edit any field
7. Please Wait Loading icon appears 
8. You have to manually click on another field (no tabbing through the fields)

### Expected result
1. Cursor should remain in the field after editing

### Actual result
1. Cursor is removed, requiring you to manually select a field with the mouse again. (This requires quite a bit more time to process an order and very annoying)

### More Information
Every time a field is changed in the Shipping Address (this does not happen at all in the Billing Address) I am receiving 2 POST methods with 200 code. The requested url is ending with:

block/billing_method,shipping_address,totals,giftmessage,items,shipping_method,shipping_address?isAjax=true

**Comment by magento-engcom-team** [comment] 2018-07-16 21:55
Hi @trucatchtraps. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@trucatchtraps do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by trucatchtraps** [comment] 2018-07-17 15:23
Hi, this is my first issue I have mentioned. Do I need to do something for your post? Thanks!

**Comment by trucatchtraps** [comment] 2019-04-09 20:24
Do you have any updates on this topic? Been almost a year since the issue was started

**Comment by dhvanit121288** [comment] 2019-09-10 13:55
Have anyone find solution ? i am facing this issue in magento 2.2.4

**Comment by engcom-Bravo** [comment] 2020-01-03 13:49
Hello @trucatchtraps 
We are rechecking this issue on Magento 2.4-develop and are not able to reproduce it. Please see the attachment with our steps 
![shipping_address](https://user-images.githubusercontent.com/51680745/71726488-f0715d00-2e3f-11ea-909b-bebdd1eb7d7b.gif)
We have created a New Order, selected a Customer, Added a Product. After, we have unchecked the **Same as Billing Address** checkbox and further, used keyboard only

This is the behavior, we are experiencing with Billing Address form
![tab_new order](https://user-images.githubusercontent.com/51680745/71726572-2a426380-2e40-11ea-811f-eadcf203e876.gif)

Can you please confirm that you are experiencing the same issue on Magento 2.4-develop? 
If yes, can you please correct us, our steps, so we can also reproduce the issue? 

Thank you,
engcom-Bravo

**Comment by trucatchtraps** [comment] 2020-01-06 15:51
This issue was fixed quite a few versions ago. I can verify it is fixed on 2.2.8 and later at least

**Comment by engcom-Bravo** [comment] 2020-01-08 07:33
@trucatchtraps 
Thank you for your response.
We are closing this issue.

**Closed as completed by engcom-Bravo** 2020-01-08 07:33 UTC
Labels: Issue: Ready for Work, Progress: needs update, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Component: Ui
