### ISSUE TITLE
Close (X) not working when error come for qty

### ISSUE THREAD

**Issue by renard123** [magento/magento2#25433] opened 2019-11-01 13:29 UTC
Close (X) not working when error come for qty

### Preconditions (*)
Magento : 2.3.3

### Steps to reproduce (*)
1. Admin -> Catalog -> products
2. Add New Product
3. Advanced pricing 
4. Click on Add for Customer Group Price
5. Now click on close icon

### Expected result (*)
Pop up should be close

### Actual result (*)
Pop up does not close
![image](https://user-images.githubusercontent.com/50658701/68027368-2c6d3200-fcd8-11e9-88f3-1d2ea48f3342.png)

**Comment by krishprakash** [comment] 2019-11-01 13:30
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-01 13:30
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-01 13:30
Hi @krishprakash, here is your [Magento instance](https://i-25433-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25433-2-3-develop.instances.magento-community.engineering/admin](https://i-25433-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-11-01 13:34
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22682` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sudheer-gajjala** [comment] 2019-11-22 14:41
@krishprakash @magento-engcom-team this is not seems to be an issue, since we have a trash icon at the end of the row. User can click on trash icon and close the window.

**Comment by VladimirZaets** [comment] 2019-12-19 03:47
Hi @renard123. Thank you for your report. 
The issue has been fixed in magento/magento2#25759 by @Ashna-Jahan in 2.4-develop branch
Related commit(s):
 - [841bb75dfbb59a8971b0897b55a234923a2c30e5](https://github.com/magento/magento2/commit/841bb75dfbb59a8971b0897b55a234923a2c30e5)
 - [e2d6d58983a8a19d020dde8b2884c489d7939aef](https://github.com/magento/magento2/commit/e2d6d58983a8a19d020dde8b2884c489d7939aef)
 - [4c0f128c7ccd8bf1642f1ab870b4380ab0821c41](https://github.com/magento/magento2/commit/4c0f128c7ccd8bf1642f1ab870b4380ab0821c41)
 - [2bd319ba7865fb65d57a0ffdcd4745e33b9387b0](https://github.com/magento/magento2/commit/2bd319ba7865fb65d57a0ffdcd4745e33b9387b0)
 - [db5332e5d95a12c9b32ed0e3523655c8e24d7b1f](https://github.com/magento/magento2/commit/db5332e5d95a12c9b32ed0e3523655c8e24d7b1f)
 - [d904436ab74f88afb6102aff022fc206e7abd199](https://github.com/magento/magento2/commit/d904436ab74f88afb6102aff022fc206e7abd199)
 - [78cdd70586a7babfd78a571ac2b2454b017fbd73](https://github.com/magento/magento2/commit/78cdd70586a7babfd78a571ac2b2454b017fbd73)
 - [56d198d03f6fcc9f56da78cdad53023750a1a188](https://github.com/magento/magento2/commit/56d198d03f6fcc9f56da78cdad53023750a1a188)

The fix will be available with the upcoming 2.4.0 release.

**Closed as completed by VladimirZaets** 2019-12-19 03:47 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, partners-contribution, Component: Backend, Partner: i95Dev, Fixed in 2.4.x
