### ISSUE TITLE
2.3.2 - View Order -Exception occured during order load

### ISSUE THREAD

**Issue by davidlopes** [magento/magento2#28022] opened 2020-04-28 16:39 UTC
### Preconditions (*)

1. magento 2.3.2
2. php 7.2

### Steps to reproduce (*)

1. Create an order
2. Delete one or more products in that order
3. Try to view order details

### Expected result (*)

1. Overview of clicked order

### Actual result (*)

1. Order page reloads → Error Message appears: "Exception occurred during order load"
    Exception.log shows following error message:
report.CRITICAL: Notice: Undefined offset: 1 in /var/www/html/vendor/magento/module-rma/Model/ResourceModel/Item.php on line 343 {"exception":"[object] (Exception(code: 0): Notice: Undefined offset: 1 in /var/www/html/vendor/magento/module-rma/Model/ResourceModel/Item.php on line 343 at /var/www/html/vendor/magento/framework/App/ErrorHandler.php:61)"} []

**Comment by Vigneshmuthusamy** [comment] 2020-04-29 06:26
Hello @davidlopes , thanks for your contribution. Unfortunately, because of the fact that this is the EE feature and it is not reproducible here, I'm going to close it.

Worry not, I'm going to pass this issue and try to fix it for EE version and get back to you once it is fixed there.

**Closed as completed by Vigneshmuthusamy** 2020-04-29 06:26 UTC
Labels: Issue: Format is valid, Reported on 2.3.2
