### ISSUE TITLE
Newsletter mail is not been sending to subscribers in Magento 2.1.6

### ISSUE THREAD

**Issue by Magento-baby** [magento/magento2#10542] opened 2017-08-16 05:49 UTC
I'm using magento 2.1.6 .The Newsletter mail is not been sending to subscribers.
Have successfully added template to the queue.But the mail is not been sent to the subscribers even after the Queue Date start time.Im using Siteground as server and following Indian standard time.

![capture](https://user-images.githubusercontent.com/31057937/29348966-c67b5c04-8274-11e7-9f18-b76e3f47e8dd.PNG)

**Comment by vherasymenko** [comment] 2017-08-16 08:05
@Magento-baby Thank you for your report.
Please use the issue reporting [guidelines ](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)to report an issue. Include the steps required to reproduce, the actual result, and the expected result.

**Comment by orlangur** [comment] 2017-08-16 08:15
Did you [setup cron](http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-cron.html)?

**Comment by Magento-baby** [comment] 2017-08-16 12:16
I'm new to magento can you  help me to create cron job in my site.Siteground is the server im using.

**Comment by korostii** [comment] 2017-08-16 12:29
If you are looking for some help or an advice regarding setup or configuration please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") of Magento CE itself only.

**Comment by orlangur** [comment] 2017-08-16 12:43
@Magento-baby link I posted more or less cover all necessary information regarding cron setup. Agree with @korostii, if you didn't do any cron setup before system works as expected.

Please close this issue as we determined there is no bug and let's continue on Stack Exchange if something won't work according to manual.

**Comment by Magento-baby** [comment] 2017-08-17 04:02
Thanks everybody for spending  your valuable time for me.

**Closed as completed** 2017-08-17 04:03 UTC
Labels: bug report, Progress: needs update
