### ISSUE TITLE
fix undefined index path when using dev server php 7.3

### ISSUE THREAD

**Issue by r32rf** [magento/magento2#28843] opened 2020-06-23 06:19 UTC
### Summary (*)

change `phpserver/router.php:48`
`$route = parse_url(substr($_SERVER["REQUEST_URI"], 1), PHP_URL_PATH);`

### Expected result (*)

`$route = parse_url(substr($_SERVER["REQUEST_URI"], 1), PHP_URL_PATH);`

### Actual result (*)

1. `$route = parse_url(substr($_SERVER["REQUEST_URI"], 1))["path"];`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment] 2020-06-23 08:52
@engcom-Echo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2020-06-23 08:55
@engcom-Echo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2020-06-23 08:57
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35372` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment] 2020-06-24 15:00
Hello @r32rf  and @engcom-Echo 


Could you please provide more details about the issue?
- what the reason of such changes in steps to reproduce?
- How it impacts product or functionality?
- What functional flows are broken due to this issue?
- what is the business value?
- why expected result should be different?

**Comment by r32rf** [comment] 2020-06-25 06:28
@sdzhepa please read title of issue.

**Comment by r32rf** [comment] 2020-06-30 08:20
please close issue if you not interested in fix.

**Comment by VladimirZaets** [comment] 2020-07-21 17:42
Hi @r32rf. Thank you for collaboration. Unforchenetly, the description is not clear, we cannot understand the main idea of the issue. If it's the issue is important for you, please provide the detailed description.

**Closed as completed by VladimirZaets** 2020-07-21 17:42 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Issue: Format is not valid, Component: Other, Triage: Dev.Experience, Reproduced on 2.4.x, Severity: S4, Progress: done
