### ISSUE TITLE
Orders screen breaks

### ISSUE THREAD

**Issue by MattJOConNZ** [magento/magento2#38174] opened 2023-11-14 03:07 UTC
### Preconditions and environment

I went to orders screen in the magento 2 admin panel and one day randomly filtered the orders and since that day any time I load the orders screen it just says it cant load. I clear my browser cache and the orders load and appear but it will only show me up until order 000046 and nothing newer than that order, the second I do anything on the page like use a filter, click an order or what ever I get the same error

![crappy magento](https://github.com/magento/magento2/assets/150762755/9cf5c71d-defa-47f1-a39a-c3de498c444a)

Magento ver. 2.4.2-p2

### Steps to reproduce

Go to orders

### Expected result

all orders would load for me to view

### Actual result

error message and not loading any orders

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-11-14 07:19
Hi @MattJOConNZ,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**


- Go to orders

<img width="1457" alt="Screenshot 2023-11-14 at 11 37 39 AM" src="https://github.com/magento/magento2/assets/51680745/6e74aa00-7a8d-4d8e-97be-40ce4399ae3a">




Sometimes, this error can occur due to version upgrade. Check "catalog_product_entity" table in DB and verify if any Products have NULL as SKU value Run > SELECT * FROM catalog_product_entity WHERE sku IS NULL to check all product not have sku NULL, then update them. Another temporary fix is to clear "ui_bookmark table". > TRUNCATE ui_bookmark; Also make sure to clear cache and add necessary permission/rights.

Kindly recheck the issue on Magento 2.4-develop branch as it has the latest code base and provide missing steps to reproduce if you are still facing the issue.

 Thank you.

**Comment by engcom-Bravo** [comment] 2023-11-28 05:25
Hi @MattJOConNZ,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38174#issuecomment-1809662407 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-12-07 05:52
Hi @MattJOConNZ,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-12-07 05:52 UTC
Labels: Issue: needs update, Reported on 2.4.2-p2
