### ISSUE TITLE
From Admin Customer Edit can not associate customer to website when Config > Share Customer Accounts is set to Global

### ISSUE THREAD

**Issue by victortodoran** [magento/magento2#32310] opened 2021-02-28 13:20 UTC
### Preconditions (*)

1. Latest Magento release
2. Magento 2.4-develop

### Steps to reproduce (*)

1. Create a secondary website.
2. Associate a new store to website from 1.
3. Associate a new store view to store from 2.
4. Ensure Stores > Configuration > Customer > Customer Configuration > Account Sharing Options  is set to Global
5. Go to Admin > Customer > Edit > Account Information and try to change the customer-website association using the website from step 1.

### Expected result (*)

1. Customer-Website association is successfully saved

### Actual result (*)

1. Association fails with UI Error
 "The Store View selected for sending Welcome email from is not related to the customer's associated website."
 
![image](https://user-images.githubusercontent.com/25669334/109419702-6be48500-79d7-11eb-9011-1cfd962e8f3c.png)

### Additional notes 

1. The customer-website association can successfully be performed from the customer grid.
2. https://github.com/magento/magento2/issues/31457 looks related and also mentions something about emails. 
I though it might be a connection due to the error message mentioning emails.
3. The operation is successful when Config > Share Customer Accounts is set to Per Website.
4. https://github.com/magento/magento2/commit/d013abf276cb688657de42d0de6b82abd65cfd45#diff-a683d404817ed6efb4ffa2cc1cdf84e712421b435ff3f1b0e03a85c96c9bb3bfR13 might have something to do with it.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment] 2021-03-03 18:51
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41152` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2021-03-18 09:14
Hi @victortodoran, @engcom-Kilo. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-41152` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Closed as completed** 2021-03-18 09:13 UTC
Labels: Component: Customer, Issue: Confirmed, Issue:  Cannot Reproduce, Priority: P2, Severity: S3, Progress: done, Issue: ready for confirmation, Reported on 2.4.x

**Comment by joshdavenport** [comment] 2021-04-13 10:54
@magento give me 2.4-develop instance
