### ISSUE TITLE
In multi store views, text swatch fields are not displaying correctly in backend under Store view titles

### ISSUE THREAD

**Issue by GlobalOutsourcing** [magento/magento2#14107] opened 2018-03-14 21:09 UTC
### Preconditions
Magento 2.2.2 upgrade to Magento 2.2.3 through composer (Developer Mode) Magento Luma theme with no customization (Only 3rd party extensions)
CentOS Linux 7.4.1708 (Core)
PHP 7.0.28 FastCGI Application served by Apache
Plesk Onyx 17.5.3 Update #43
Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 core(s))
mysql Ver 15.1 Distrib 10.1.29-MariaDB

### Steps to reproduce
1. Setup multiple store views (14+)
1. Stores --> Attributes --> Product 
2. Properties --> Manage Swatch (Values of Your Attribute)
3. Fields to enter text under the Store view titles are not displaying correctly:

![2018-03-14_204957](https://user-images.githubusercontent.com/17181901/37430706-e243cd26-27ca-11e8-967e-03fddbb28a43.png)

4. Also, not clear where to enter the admin text for the Text swatch fields as Magento Admin does not register them, they have to be entered on the non-visible separator type of field: http://www.screencast.com/t/VSkVYDb469De
 
### Expected result
1. Setup multiple store views (14+)
2. Properties --> Manage Swatch (Values of Your Attribute)
3. Fields to enter text under the Store view titles display correctly and text fields under Admin are registered as per above screenshot and Store view text fields

### Actual result
1. Text Swatch fields not displaying correctly if many store views are setup: 
![2018-03-14_204957](https://user-images.githubusercontent.com/17181901/37431019-e8acc220-27cb-11e8-8b04-5f6648afe45e.png)

2. Admin text as watch field does not register input: http://www.screencast.com/t/VSkVYDb469De

**Comment by paragpadsumbiya** [comment] 2018-03-15 10:11
@GlobalOutsourcing same spacing issue is mentioned in comment in referenced issue when there are multiple store views .

**Comment by magento-engcom-team** [comment] 2018-03-15 13:46
@GlobalOutsourcing, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ishakhsuvarov** [comment] 2018-03-15 13:58
@GlobalOutsourcing Closing this report as duplicate of #13053.
Please continue tracking under that id.

Thank you for collaboration.

**Closed as completed by ishakhsuvarov** 2018-03-15 13:58 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid
