### ISSUE TITLE
Category filters returning empty results in shared catalogs

### ISSUE THREAD

**Issue by johannabg** [magento/magento2#34940] opened 2022-01-05 23:22 UTC
### Preconditions (*)

1. Magento v2.4.2-p1

### Steps to reproduce (*)

1. When logged into a shared catalog and using the top navigation to drill down to a product category I receive a "We can't find products matching the selection" message with empty results.

### Expected result (*)

1. Should see all products for the selected category when logged into a shared catalog

### Actual result (*)

1. Receive a message that states "We can't find products matching the selection" 
2. Magento is getting the first 12 products (using SKU default sorting) from the category without checking if those products are present in the corresponding shared catalog. If none of them are present, the category is going to be empty and we get the message: We can't find products matching the selection.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-01-07 05:50
Verified the issue on Magento 2.4-develop branch having B2B modules enabled but cannot able to reproduce the issue:
Steps performed:
Added products to Shared Catalog
Catalog - Shared Catalog - Set Pricing and Structure - Products Grid is loading as expected - No issue
@johannabg kindly recheck the issue on Magento 2.4-develop branch with B2B modules enabled and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-01-20 13:23
Hi @johannabg,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-01-20 13:23 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
