### ISSUE TITLE
Stock problem Inventory

### ISSUE THREAD

**Issue by ardianthaqit** [magento/magento2#36074] opened 2022-09-02 09:27 UTC
### Preconditions and environment

Magento ver. 2.4.0
PHP: PHP 7.4

### Steps to reproduce

Example: For a product, we added 2 on stock so in front it will show out of stock if we added 4 on stock it will show 2 on stock so the stock is always -2 or -3

### Expected result

Example: For a product, we added 2 on stock so in front it will show out of stock if we added 4 on stock it will show 2 on stock so the stock is always -2 or -3

### Actual result

Example: For a product, we added 2 on stock so in front it will show out of stock if we added 4 on stock it will show 2 on stock so the stock is always -2 or -3

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-09-22 03:18
Hi @ardianthaqit ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch with and without MSI(Inventory) enabled both and the issue is not reproducible in both the cases.
Product stock qty with 1 and 2 - stock status is in stock and able to add to cart from front end.
![image](https://user-images.githubusercontent.com/60198231/191650782-c662bac7-d6da-4731-836f-2392b5dfd19a.png)
Kindly check the magento [system requirements](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html) or if any 3rd party modules / extensions enabled is causing this issue. Please recheck the behavior on Magento 2.4-develop instance as it is having latest code base and upcoming 2.4.x release and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-10-06 05:57
Hi @ardianthaqit ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-10-06 05:57 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.0
