### ISSUE TITLE
Issue : Incorrect Data on Magento 2 Dashboard

### ISSUE THREAD

**Issue by nylanBCM** [magento/magento2#38841] opened 2024-06-19 05:20 UTC
### Preconditions and environment

- Magento 2 ver. 2.4.5-p3
- Go to the dashboard section

### Steps to reproduce

1. Log in to the Magento 2 admin dashboard.
2. Navigate to the dashboard section where sales data is displayed.
3. Observe the details beside the graph/chart.
4. The dashboard of my Magento 2 store is displaying incorrect data. 
5. While the graph/chart shows previous sales, the day, and the time correctly, the detailed information beside the graph is nonsensical and unrelated to the actual sales data.

![Mageto 2 Support](https://github.com/magento/magento2/assets/173225305/56364eb2-b328-4dff-a4d5-2ee896b18ea5)

### Expected result

The dashboard should accurately display, regarding of the actual sales :

1. Daily revenue
2. Tax
3. Shipping fees
4. Quantity of orders

### Actual result

The details beside the sales graph/chart are incorrect and do not reflect the actual sales data. And I don't understand how they even calculate the revenue below the graph.

### Release note

Could you please provide guidance or a fix to configure the dashboard to accurately display:

1. Daily revenue
2. Tax
3. Shipping fees
4. Quantity of orders

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2024-06-20 07:32
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2024-06-20 08:07
Hi @nylanBCM 

Thanks for reporting and collaboration.

Verified the issue on Magento 2.4 dev instance but the issue is not reproducible.

We are able to see the correct data on Magento 2 Dashboard

Steps to reproduce :

1. Log in to the Magento 2 admin dashboard.
2. Navigate to the dashboard section where sales data is displayed.
3. Observe the details beside the graph/chart.
4. The dashboard of my Magento 2 store is displaying incorrect data.
5. While the graph/chart shows previous sales, the day, and the time correctly, the detailed information beside the graph is nonsensical and unrelated to the actual sales data.
6. 

Please refer the attached screenshots.

Previous data:

<img width="1440" alt="38841_1" src="https://github.com/magento/magento2/assets/60198592/5f9a26c3-13d2-4db5-b33d-f8e028e3bd87">
<img width="1440" alt="38841_2" src="https://github.com/magento/magento2/assets/60198592/8ff56342-83d7-48ab-9e62-4e6b33ad0da0">

Date after new order is placed and order status is completed.

<img width="1440" alt="38841_3" src="https://github.com/magento/magento2/assets/60198592/51e7f7d7-43fc-4893-b08d-fff396351053">

**Comment by nylanBCM** [comment] 2024-06-21 03:15
Hi Susanna,

 

Thanks for your prompt response and for verifying the issue on the Magento 2.4 dev instance.

 

I appreciate your detailed steps to reproduce the issue. However, the problem we are encountering seems to persist on our end. Here's a summary of what we have observed:

 

1. Discrepancy in Sales Data for June 21 represented on the dashboard’s graph:

   - After a detailed review of the sales data, there appears to be a discrepancy of approximately $1800.09 - $1161.75 = $638.34 that is not reflected in the graph for this day.

   - This discrepancy is observed in the total sales amount displayed on the graph compared to the detailed sales report for that day.

 

2. Sales Calculation Adjustment Request :

   - Additionally, I would like to request an adjustment in how the revenue below the graph in orange is calculated.

   - Instead of a rolling 24-hour total, we need the sales to be calculated for the total of the day starting at 12:00 PM to be shown as “Revenue” below the graph.

 

To help with troubleshooting, I have attached screenshots of our dashboard illustrating the discrepancies observed:

- “Dashboard – Graph” -> go to magento -> dashboard -> look at the graph and the columns of today’s sales in the amount section of the graph.

- “Sales – Order’ -> Go to magento -> Sales -> Orders -> Calculate the amount of sales of the day.

 

Please let me know if you need any additional information or if there are specific steps we can take on our end to further diagnose the issue.

 

Thank you for your assistance. You can call me at 0423924921.

 

Best regards,

 

Nylan

**Comment by nylanBCM** [comment] 2024-06-24 00:46
I'm encountering an issue with the revenue calculation on my Magento 2.4.5-p3 dashboard. The displayed revenue for "today" does not accurately reflect sales from 12 AM to the current time, instead using an incorrect period, resulting in inaccurate daily revenue reporting. I've confirmed the timezone and locale settings are correct, but the problem persists. Could anyone advise on how to modify the code to ensure the correct time range is used for daily revenue calculations, or suggest any solutions or extensions that might help?

**Comment by engcom-Dash** [comment] 2024-07-29 12:47
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-09-23 06:31
Hi @nylanBCM,

Thanks for your update.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.It is recommended to verify the issues in Latest 2.4-develop instance.Hence we are closing the issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-09-23 06:31 UTC
Labels: Issue: needs update, Reported on 2.4.5-p3
