### ISSUE TITLE
favorite icon (A favicon) is missing in Magento 2.4.4 Adobe Commerce

### ISSUE THREAD

**Issue by shikhamis11** [magento/magento2#35493] opened 2022-05-18 06:12 UTC
Default favicon is missing in Magento 2.4.4 Adobe Commerce

### Preconditions (*)

1. Magento 2.4.4 Enterprise Edition

### Steps to reproduce (*)

1. Favicon is missing in Address Bar with default magento installation
2. No icon can be found at path `/static/frontend/Magento/luma/en_US/Magento_Enterprise/favicon.ico`
    `vendor/magento/module-enterprise/view/frontend/web/favicon.ico`

### Expected result (*)

![image](https://user-images.githubusercontent.com/25526037/168969329-5fcd9760-72d7-4cb2-b2a7-81ef72ce4e5b.png)

### Actual result (*)

Favicon is missing in Magento 2.4.4 Adobe Commerce after installation

![image](https://user-images.githubusercontent.com/25526037/168968816-b589bbca-78bd-4ce4-a4e9-8a750bdcae3f.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-05-18 08:13
Hi @shikhamis11 ,
Thank you for reporting and collaboration. Verified this issue on both Magento 2.4.4 and 2.4-develop with Enterprise edition modules enabled but could not able to reproduce the issue.
Favicon set in Admin - Content - Design - Configuration - Html head section is getting applied to all pages after clearing cache.
[Ref doc](https://docs.magento.com/user-guide/design/favicon.html)
![image](https://user-images.githubusercontent.com/60198231/168990761-7c6c5d13-b88e-45fd-9cb5-5bd894bfca08.png)
Kindly recheck the issue again on Magento 2.4-develop with enterprise edition and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by shikhamis11** [comment] 2022-05-18 08:18
@magento give me 2.4-develop instance with edition ee

**Comment by shikhamis11** [comment] 2022-05-18 08:30
@engcom-November Thank you for reviewing the issue. 
Please check for the default favicon. I have updated the issue description 

![image](https://user-images.githubusercontent.com/25526037/168993546-e7c97929-cdf3-4031-9cb0-62385ae0071a.png)

**Comment by engcom-November** [comment] 2022-05-18 09:07
Thanks for the update @shikhamis11,
Verified the issue again on new magento installation and default favicon is missing in both 2.4.4 community edition and 2.4-develop enterprise version. Hence confirming this issue.
 
![image](https://user-images.githubusercontent.com/60198231/169002306-46440b2d-40eb-4373-b9fb-d3ad64fc691f.png)

**Comment by Pranav-242** [comment] 2022-05-27 12:02
@magento i'm working on this

**Comment by asim-blueprintprep** [comment] 2022-08-03 14:06
I believe this also happens on cloud commerce:
2.4.2-p2:
frontend/Blueprint/bpp-corporate/en_US/Magento_Theme/favicon.ico

2.4.4:
frontend/Blueprint/blueprint/en_US/Magento_Enterprise/favicon.ico

It looks like it's changed where it looks for favicon from Magento_Theme to Magento_Enterprise?

**Comment by dineshkaswan5** [comment] 2022-08-03 16:46
@magento i'm working on this

**Comment by dineshkaswan5** [comment] 2022-08-03 16:46
@magento add to contributors team

**Comment by dineshkaswan5** [comment] 2022-08-03 16:52
@magento i'm working on this

**Comment by dineshkaswan5** [comment] 2022-08-03 16:53
@magento give me 2.4-develop instance

**Comment by DarthFly** [comment] 2022-08-19 13:23
The Enterprise version introduced a new favicon for admin, but the icon is located only in the "adminhtml" theme while the plugin that replaced the default icon is in the global scope. That's all.
`--- a/vendor/magento/module-enterprise/etc/adminhtml/di.xml
+++ b/vendor/magento/module-enterprise/etc/adminhtml/di.xml
@@ -9,4 +9,8 @@
     <type name="Magento\Backend\Block\Store\Switcher">
         <plugin name="entrprise_store_switcher_plugin" type="Magento\Enterprise\Model\Plugin\StoreSwitcher"/>
     </type>
+
+    <type name="Magento\Theme\Model\Favicon\Favicon">
+        <plugin name="enterprise_favicon" type="Magento\Enterprise\Model\Plugin\Favicon"/>
+    </type>
 </config>
--- a/vendor/magento/module-enterprise/etc/di.xml
+++ b/vendor/magento/module-enterprise/etc/di.xml
@@ -14,8 +14,5 @@
             </argument>
         </arguments>
     </type>
-    <type name="Magento\Theme\Model\Favicon\Favicon">
-        <plugin name="enterprise_favicon" type="Magento\Enterprise\Model\Plugin\Favicon"/>
-    </type>
     <preference for="Magento\Framework\App\ProductMetadataInterface" type="Magento\Enterprise\Model\ProductMetadata"/>
 </config>
`

**Comment by avattam06** [comment] 2022-08-31 15:01
@shikhamis11 Can you please add all the steps to reproduce the issue? Thanks

**Comment by shikhamis11** [comment] 2022-08-31 15:32
@magento give me 2.4-develop instance with edition ee

**Comment by shikhamis11** [comment] 2022-08-31 15:44
Hi @avattam06,
This issue is reproducible on Magento 2.4-develop instance with enterprise edition.
I have added a screenshot please check the default favicon is missing and 404 for its path in the console.
![image](https://user-images.githubusercontent.com/25526037/187720840-40483980-b430-4157-9a1a-81a05dd00e92.png)

**Comment by glo35082** [comment] 2022-09-05 15:14
Thanks for contributing; Our internal team is already onto it.

**Comment by engcom-Hotel** [comment] 2022-10-10 16:38
Hello,

The internal already fixed this issue and the code has been merged with the development branch of EE. We are unable to provide you the commit link as the commits are from the private repo. But the fix will be available from Magento 2.4.6 version.

Hence closing the issue.

Thanks

**Closed as completed by engcom-Hotel** 2022-10-10 16:38 UTC
Labels: Issue: Confirmed, Component: Ui, Reproduced on 2.4.x, Priority: P3, Progress: done, Area: Content, Reported on 2.4.4
