### ISSUE TITLE
my order always in Suspected Fraud

### ISSUE THREAD

**Issue by JKair** [magento/magento2#33333] opened 2021-06-24 09:22 UTC
### Preconditions (*)

1.Magento ver. 2.4.2
2.PHP 7.4.18 

### Steps to reproduce (*)

1.create a order
2.use paypal to pay
3.the order will be Suspected Fraud

### Expected result (*)

1. the order be `processing`

### Actual result (*)

1. the payment log
  ```
[2021-06-24 08:55:36] main.DEBUG: array (
  'url' => 'https://api-3t.sandbox.paypal.com/nvp',
  'SetExpressCheckout' => 
  array (
    'PAYMENTACTION' => 'Sale',
    'AMT' => '699.00',
    'CURRENCYCODE' => 'USD',
    'RETURNURL' => 'https://mydomain.com/paypal/express/return/',
    'CANCELURL' => 'https://mydomain.com/paypal/express/cancel/',
    'INVNUM' => '000001405',
    'SOLUTIONTYPE' => 'Mark',
    'GIROPAYCANCELURL' => 'https://mydomain.com/paypal/express/cancel/',
    'GIROPAYSUCCESSURL' => 'https://mydomain.com/checkout/onepage/success/',
    'BANKTXNPENDINGURL' => 'https://mydomain.com/checkout/onepage/success/',
    'SHIPPINGAMT' => '0.00',
    'ITEMAMT' => '699.00',
    'TAXAMT' => '0.00',
    'L_NUMBER0' => NULL,
    'L_NAME0' => 'Bizente TV Stand with 4 Drawers',
    'L_QTY0' => 1,
    'L_AMT0' => '699.00',
    'METHOD' => 'SetExpressCheckout',
    'VERSION' => '72.0',
    'USER' => '****',
    'PWD' => '****',
    'SIGNATURE' => '****',
    'BUTTONSOURCE' => 'Magento_2_Community',
  ),
  'response' => 
  array (
    'TOKEN' => 'EC-74F40567HK174480P',
    'TIMESTAMP' => '2021-06-24T08:55:36Z',
    'CORRELATIONID' => '661242d1e7442',
    'ACK' => 'Success',
    'VERSION' => '72.0',
    'BUILD' => '55740545',
  ),
) [] []
[2021-06-24 08:56:12] main.DEBUG: array (
  'url' => 'https://api-3t.sandbox.paypal.com/nvp',
  'GetExpressCheckoutDetails' => 
  array (
    'TOKEN' => 'EC-74F40567HK174480P',
    'METHOD' => 'GetExpressCheckoutDetails',
    'VERSION' => '72.0',
    'USER' => '****',
    'PWD' => '****',
    'SIGNATURE' => '****',
    'BUTTONSOURCE' => 'Magento_2_Community',
  ),
  'response' => 
  array (
    'TOKEN' => 'EC-74F40567HK174480P',
    'BILLINGAGREEMENTACCEPTEDSTATUS' => '0',
    'CHECKOUTSTATUS' => 'PaymentActionNotInitiated',
    'TIMESTAMP' => '2021-06-24T08:56:12Z',
    'CORRELATIONID' => 'cd8935fe87bb9',
    'ACK' => 'Success',
    'VERSION' => '72.0',
    'BUILD' => '55740545',
    'EMAIL' => 'customeremail@email.com',
    'PAYERID' => '4LN6DK5G2EEYY',
    'PAYERSTATUS' => 'verified',
    'FIRSTNAME' => 'John',
    'LASTNAME' => 'Doe',
    'COUNTRYCODE' => 'US',
    'SHIPTONAME' => 'John Doe',
    'SHIPTOSTREET' => '1 Main St',
    'SHIPTOCITY' => 'San Jose',
    'SHIPTOSTATE' => 'CA',
    'SHIPTOZIP' => '95131',
    'SHIPTOCOUNTRYCODE' => 'US',
    'SHIPTOCOUNTRYNAME' => 'United States',
    'ADDRESSSTATUS' => 'Confirmed',
    'CURRENCYCODE' => 'USD',
    'AMT' => '699.00',
    'ITEMAMT' => '699.00',
    'SHIPPINGAMT' => '0.00',
    'HANDLINGAMT' => '0.00',
    'TAXAMT' => '0.00',
    'INVNUM' => '000001405',
    'NOTIFYURL' => '    ',
    'INSURANCEAMT' => '0.00',
    'SHIPDISCAMT' => '0.00',
    'INSURANCEOPTIONOFFERED' => 'false',
    'L_NAME0' => 'Bizente TV Stand with 4 Drawers',
    'L_QTY0' => '1',
    'L_TAXAMT0' => '0.00',
    'L_AMT0' => '699.00',
    'PAYMENTREQUEST_0_CURRENCYCODE' => 'USD',
    'PAYMENTREQUEST_0_AMT' => '699.00',
    'PAYMENTREQUEST_0_ITEMAMT' => '699.00',
    'PAYMENTREQUEST_0_SHIPPINGAMT' => '0.00',
    'PAYMENTREQUEST_0_HANDLINGAMT' => '0.00',
    'PAYMENTREQUEST_0_TAXAMT' => '0.00',
    'PAYMENTREQUEST_0_INVNUM' => '000001405',
    'PAYMENTREQUEST_0_NOTIFYURL' => 'https://mydomain.com/paypal/ipn/',
    'PAYMENTREQUEST_0_INSURANCEAMT' => '0.00',
    'PAYMENTREQUEST_0_SHIPDISCAMT' => '0.00',
    'PAYMENTREQUEST_0_SELLERPAYPALACCOUNTID' => 'myemail@email.com',
    'PAYMENTREQUEST_0_INSURANCEOPTIONOFFERED' => 'false',
    'PAYMENTREQUEST_0_SHIPTONAME' => 'John Doe',
    'PAYMENTREQUEST_0_SHIPTOSTREET' => '1 Main St',
    'PAYMENTREQUEST_0_SHIPTOCITY' => 'San Jose',
    'PAYMENTREQUEST_0_SHIPTOSTATE' => 'CA',
    'PAYMENTREQUEST_0_SHIPTOZIP' => '95131',
    'PAYMENTREQUEST_0_SHIPTOCOUNTRYCODE' => 'US',
    'PAYMENTREQUEST_0_SHIPTOCOUNTRYNAME' => 'United States',
    'PAYMENTREQUEST_0_ADDRESSSTATUS' => 'Confirmed',
    'L_PAYMENTREQUEST_0_NAME0' => 'Bizente TV Stand with 4 Drawers',
    'L_PAYMENTREQUEST_0_QTY0' => '1',
    'L_PAYMENTREQUEST_0_TAXAMT0' => '0.00',
    'L_PAYMENTREQUEST_0_AMT0' => '699.00',
    'PAYMENTREQUESTINFO_0_ERRORCODE' => '0',
  ),
) [] []
[2021-06-24 08:56:28] main.DEBUG: array (
  'url' => 'https://api-3t.sandbox.paypal.com/nvp',
  'DoExpressCheckoutPayment' => 
  array (
    'TOKEN' => 'EC-74F40567HK174480P',
    'PAYERID' => '4LN6DK5G2EEYY',
    'PAYMENTACTION' => 'Sale',
    'AMT' => '699.00',
    'CURRENCYCODE' => 'USD',
    'BUTTONSOURCE' => 'Magento_2_Community',
    'NOTIFYURL' => 'https://mydomain.com/paypal/ipn/',
    'RETURNFMFDETAILS' => 1,
    'SHIPPINGAMT' => '0.00',
    'ITEMAMT' => '699.00',
    'TAXAMT' => '0.00',
    'L_NUMBER0' => NULL,
    'L_NAME0' => 'Bizente TV Stand with 4 Drawers',
    'L_QTY0' => 1,
    'L_AMT0' => '699.00',
    'BUSINESS' => NULL,
    'EMAIL' => 'customeremail@email.com',
    'FIRSTNAME' => 'John',
    'LASTNAME' => 'Doe',
    'MIDDLENAME' => NULL,
    'SALUTATION' => NULL,
    'SUFFIX' => NULL,
    'COUNTRYCODE' => 'US',
    'STATE' => 'CA',
    'CITY' => 'San Jose',
    'STREET' => '1 Main St',
    'ZIP' => '95131',
    'PHONENUM' => '',
    'SHIPTOCOUNTRYCODE' => 'US',
    'SHIPTOSTATE' => 'CA',
    'SHIPTOCITY' => 'San Jose',
    'SHIPTOSTREET' => '1 Main St',
    'SHIPTOZIP' => '95131',
    'SHIPTOPHONENUM' => '',
    'SHIPTOSTREET2' => '',
    'STREET2' => '',
    'SHIPTONAME' => 'John Doe',
    'ADDROVERRIDE' => 1,
    'METHOD' => 'DoExpressCheckoutPayment',
    'VERSION' => '72.0',
    'USER' => '****',
    'PWD' => '****',
    'SIGNATURE' => '****',
  ),
  'response' => 
  array (
    'TOKEN' => 'EC-74F40567HK174480P',
    'SUCCESSPAGEREDIRECTREQUESTED' => 'false',
    'TIMESTAMP' => '2021-06-24T08:56:28Z',
    'CORRELATIONID' => 'f15a0f98f13db',
    'ACK' => 'Success',
    'VERSION' => '72.0',
    'BUILD' => '55740545',
    'TRANSACTIONID' => '67R265146N972644X',
    'TRANSACTIONTYPE' => 'cart',
    'PAYMENTTYPE' => 'instant',
    'ORDERTIME' => '2021-06-24T08:56:27Z',
    'AMT' => '699.00',
    'FEEAMT' => '20.57',
    'TAXAMT' => '0.00',
    'CURRENCYCODE' => 'USD',
    'PAYMENTSTATUS' => 'Completed',
    'PENDINGREASON' => 'None',
    'REASONCODE' => 'None',
    'PROTECTIONELIGIBILITY' => 'Eligible',
    'INSURANCEOPTIONSELECTED' => 'false',
    'SHIPPINGOPTIONISDEFAULT' => 'false',
    'PAYMENTINFO_0_TRANSACTIONID' => '67R265146N972644X',
    'PAYMENTINFO_0_TRANSACTIONTYPE' => 'cart',
    'PAYMENTINFO_0_PAYMENTTYPE' => 'instant',
    'PAYMENTINFO_0_ORDERTIME' => '2021-06-24T08:56:27Z',
    'PAYMENTINFO_0_AMT' => '699.00',
    'PAYMENTINFO_0_FEEAMT' => '20.57',
    'PAYMENTINFO_0_TAXAMT' => '0.00',
    'PAYMENTINFO_0_CURRENCYCODE' => 'USD',
    'PAYMENTINFO_0_PAYMENTSTATUS' => 'Completed',
    'PAYMENTINFO_0_PENDINGREASON' => 'None',
    'PAYMENTINFO_0_REASONCODE' => 'None',
    'PAYMENTINFO_0_PROTECTIONELIGIBILITY' => 'Eligible',
    'PAYMENTINFO_0_PROTECTIONELIGIBILITYTYPE' => 'ItemNotReceivedEligible,UnauthorizedPaymentEligible',
    'PAYMENTINFO_0_SELLERPAYPALACCOUNTID' => 'myemail@email.com',
    'PAYMENTINFO_0_SECUREMERCHANTACCOUNTID' => 'TKE3GW7Y9AJ2S',
    'PAYMENTINFO_0_ERRORCODE' => '0',
    'PAYMENTINFO_0_ACK' => 'Success',
  ),
) [] []

  ```
2.It nerver let the order be `processing`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ 1 ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by JKair** [comment] 2021-06-24 09:35
![image](https://user-images.githubusercontent.com/5440088/123239991-7e4c7680-d512-11eb-933c-8ab0b51041be.png)
![image](https://user-images.githubusercontent.com/5440088/123240023-84daee00-d512-11eb-84a6-757d6e455680.png)

**Comment by JKair** [comment] 2021-06-24 10:48
All are usd.

**Comment by engcom-November** [comment] 2021-06-24 12:59
Hi @JKair,
Can you please provide detailed configuration to enable Paypal payment option in Admin - Create New Order page.
![image](https://user-images.githubusercontent.com/60198231/123265987-367d1d80-d519-11eb-9449-87d866a8fcfe.png)

**Note: This[ blog comment](https://magento.stackexchange.com/questions/281246/magento-2-no-payment-methods-in-admin-new-order) might help you**
Thank you.

**Comment by JKair** [comment] 2021-06-24 13:54
![image](https://user-images.githubusercontent.com/5440088/123275177-af3ea280-d536-11eb-9c80-dbdd931e3755.png)

**Comment by JKair** [comment] 2021-06-24 13:55
@engcom-November

**Comment by JKair** [comment] 2021-06-24 14:11
![image](https://user-images.githubusercontent.com/5440088/123277986-283ef980-d539-11eb-9055-5956ea2e33b8.png)

**Comment by JKair** [comment] 2021-06-25 05:11
The order `state` is processing and `status` is fraud

**Comment by engcom-November** [comment] 2021-06-28 11:55
@JKair,
As requested in the [last comment](https://github.com/magento/magento2/issues/33333#issuecomment-867616455), Can you please provide the configuration to enable **Paypal Express Checkout Payment** option in Admin - Create New Order page.
Thank you.

**Comment by JKair** [comment] 2021-06-30 06:13
![image](https://user-images.githubusercontent.com/5440088/123910636-53986d00-d9ad-11eb-90a3-d0489b4152e5.png)
@engcom-November

**Comment by JKair** [comment] 2021-06-30 06:16
@engcom-November
![image](https://user-images.githubusercontent.com/5440088/123910751-7aef3a00-d9ad-11eb-874d-956d23317c20.png)
I set it up according to the tutorial, but select option disappear,and the payment is same as front.

**Comment by JKair** [comment] 2021-06-30 06:16
@engcom-November 
I set it up according to the tutorial, but select option disappear,and the payment is same as front.

![image](https://user-images.githubusercontent.com/5440088/123910991-c99cd400-d9ad-11eb-9224-b4df02abe257.png)

**Comment by engcom-November** [comment] 2021-07-05 14:51
@JKair, I verified the issue on Magento version 2.4 and the issue is not reproducible to me.
**Steps performed:**
1. Configured PayPal Express Checkout Payment method from Admin (Stores -> Configuration -> Sales - > Payment Methods - PayPal Express Checkout)
2. Navigate to Front-end - Add a product to cart - Checkout
3. Make Payment using PayPal Express Checkout - **No issue - Order status is Processing**
4. Verify in Admin -> Sales - Orders -> View the Order created - Order status is "Processing" - **No issue**
![image](https://user-images.githubusercontent.com/60198231/124487828-c8fca700-ddcc-11eb-9b8d-8266148d989f.png)
![image](https://user-images.githubusercontent.com/60198231/124487876-d74ac300-ddcc-11eb-827e-bd43f5c27065.png)

5. Create new Order from Admin - Sales -> Orders -> Create New Order
6. Select Customer
7. Add Products
8. Verify Payment Information -> "PayPal Billing Agreement" payment option (enabled using PayPal Express Checkout configuration from Admin) is displayed with radio buttons to select the method, but **PayPal Express Checkout** payment option is not displayed which is default Magento behavior.
9. Select PayPal Billing Agreement option and submit the Order
**No Issue: Order status is "Processing"**
![image](https://user-images.githubusercontent.com/60198231/124487950-e7fb3900-ddcc-11eb-9906-0019b933d989.png)
![image](https://user-images.githubusercontent.com/60198231/124488167-2abd1100-ddcd-11eb-9c53-0e3f2388d9f5.png)
![image](https://user-images.githubusercontent.com/60198231/124488222-37da0000-ddcd-11eb-843a-8ac4fa326f38.png)
@JKair Can you please confirm if you are trying to pay using PayPal Express Checkout from Front-end or Backed Admin panel.
We are not able to reproduce the issue. Please provide the missing steps if any.
Thank you.

**Comment by JKair** [comment] 2021-07-06 11:17
I try to reproduce in test server, can't reproduce too, but it does not work in my production environment.
@engcom-November 
Does magento only review the amount of order fraud？

**Comment by engcom-November** [comment] 2021-07-08 13:32
@JKair 
Magento supports the following fraud protection solutions for Actions: Review, Deny and Flag
Please refer to this [link](https://docs.magento.com/user-guide/payment/paypal-fraud-management-filter.html)
Also, kindly check your PayPal Account configuration, re-verify the issue and let us know if the issue is still reproducible.
[Ref Link](https://docs.magento.com/user-guide/payment/paypal-express-checkout.html)
Thank you.

**Comment by JKair** [comment] 2021-07-12 03:22
I fix the bug.
Because the order fraud status is set as `default`,so when the order paid and it will be set the first default status `fraud`

**Comment by JKair** [comment] 2021-07-12 03:22
@engcom-November thanks for your help

**Comment by engcom-November** [comment] 2021-07-12 06:10
@JKair Thanks for your update. We are closing the ticket as your issue is resolved.
Thank you.

**Closed as completed by engcom-November** 2021-07-12 06:10 UTC
Labels: Issue:  Cannot Reproduce, Component: Paypal, Issue: needs update, Reported on 2.4.2
