### ISSUE TITLE
Google Analytics not getting conversion data from ecommerce.

### ISSUE THREAD

**Issue by wilsonssot** [magento/magento2#35305] opened 2022-04-13 21:10 UTC
### Preconditions (*)

1. Magento Comunity ver. 2.3.5-p2
2. Have a google analytics and google tag manager set up.

### Steps to reproduce (*)

1. Set up google api. Go to Stores->Settings->Configuration->Sales->Google Api-> Fill information, and enable Google Analytics and Google AdWords-> Save.
2. Surft the commerce, open products, add to cart, make orders.
3. Set up gtm scripts:
![image](https://user-images.githubusercontent.com/29804260/163271853-e8763970-9b4a-4b91-ad75-ee5ef5fcb1d8.png)
![image](https://user-images.githubusercontent.com/29804260/163271960-9533eade-4d76-4e0c-a372-1714f9d6e2ef.png)

### Expected result (*)

1. Information should pass to google Analytics.
2. You should be able to check conversion data in your google account.

### Actual result (*)

1. The conversion flow is incomplete. Only finished transaccions are being stored.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/29804260/163270341-80940b74-9047-4f5c-9adf-6671665848d2.png)
as you can see in this screenshot, we don't have add to cart, abandoned cart information.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by anvanza** [comment] 2022-04-14 08:43
Hi @wilsonssot , I think you're looking for Google Analytics **Enhanced Ecommerce**. 
This is a feature of Adobe Commerce. You could also install a 3rd party module.

https://docs.magento.com/user-guide/marketing/google-enhanced-ecommerce.html

Anyway, it's not included in the standard Analytics module.

**Comment by wilsonssot** [comment] 2022-04-14 16:37
Hello @anvanza , so is it possible to install 3rd party module to make it work? Or it won't never work for magento open source?

**Comment by anvanza** [comment] 2022-04-15 08:36
Hi @wilsonssot , Yes you could use a module. I don't think I should list those modules here; but try searching for "magento 2 enhanced ecommerce". 
I use a module in conjunction with Google Tag Manager and GA4. (since UA is already deprecated)

**Comment by JorisKok** [comment] 2022-06-27 14:07
@anvanza I have a similar issue. UA is receiving all custom events, but we want to track those as well via server side tagging, and they are not coming in. Events like add_to_cart are fully setup, working with UA and are not coming through for GA4. They are coming through when we use GTM Injector, which should indicate the if the GTM script is available it should work. 


We noticed that the magento code adds a `\u002` instead of a `-` character. We think this might be the issue, are you aware of other users having issues with this?

```
"*": {
--
  | "Magento_GoogleTagManager/js/google-tag-manager": {
  | "isCookieRestrictionModeEnabled": 0,
  | "currentWebsite": 1,
  | "cookieName": "user_allowed_save_cookie",
  | "gtmAccountId": "GTM\u002DXXXXXXX",
  | "storeCurrencyCode": "EUR",
  | "ordersData": []                    }
  | }
```

**Comment by engcom-November** [comment] 2022-11-25 13:05
Hi @wilsonssot ,
Thank you for reporting and collaboration. Verified the behavior on Magento 2.4-develop enterprise edition and add to cart event does not come by default in conversion data.
Only Purchase conversion is enabled by default.
add_to_cart event should be added and marked as conversion to track the same. Ref [docs](https://experienceleague.adobe.com/docs/commerce-admin/marketing/google-tools/google-universal-analytics.html#enhanced-ecommerce), [doc2](http://www.ganotes.com/track-add-cart-events-google-analytics-google-tag-manager/)
Default Reports Snapshot:
![image](https://user-images.githubusercontent.com/60198231/203991200-72a23dae-268f-4f7e-8af4-6f0a6c390648.png)
Kindly recheck the behavior on Magento 2.4-develop instance with enterprise edition with add_to_cart event setup for conversions and elaborate steps to reproduce if you are still facing any issues.
Thank you.

**Comment by engcom-November** [comment] 2022-12-08 10:43
Hi @wilsonssot ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-12-08 10:43 UTC
Labels: Issue: needs update
