### ISSUE TITLE
GraphQL resolve Method gives $args NULL

### ISSUE THREAD

**Issue by jignesh26** [magento/magento2#36773] opened 2023-01-24 16:22 UTC
### Preconditions and environment

I have to add new parameter in graphql of "query Products".
so I did in my custom module.
```
type products
{
new _attribute
}
```
but inside resolve I am not getting $args passed in query. it always empty.
can you help me if possible?
```
public function resolve(
    Field $field,
    $context,
    ResolveInfo $info,
    array $value = null,
    array $args = null
) 
```
why $args is null?

### Steps to reproduce

Create custom Module, 
Add new parameter for 
type Products Graphql

and try to get args

### Expected result

it should provide $args that is used along to filter query

### Actual result

$args is null.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2024-02-16 10:33
Hello @jignesh26,

Are you still facing this issue? Please let us know if the issue is still reproducible for you in the latest 2.4-develop branch.

Thanks

**Comment by engcom-Hotel** [comment] 2024-02-27 13:18
Dear @jignesh26,

We have noticed that this issue has not been updated for a period of long time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2024-02-27 13:18 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.x
