### ISSUE TITLE
re edit failed on configurable product

### ISSUE THREAD

**Issue by ps3z** [magento/magento2#9584] opened 2017-05-10 17:00 UTC
Problem
The following error message was return during Magento listing creation: "The value of attribute "Color" must be unique".

Cause
Attribute color was not configured correctly in Magento admin.

Solution
Login to Magento Admin;
Go to Catalog > Attributes > Manage Attributes;
Click on Color attribute;
Select No from the Unique Value drop-down menu;
Click on Save Attribute button.

### Actual result

1. [Screenshot, logs]
![image](https://cloud.githubusercontent.com/assets/28603946/25911174/8820caee-35bb-11e7-8f1b-308eda92e0f0.png)

error
The value of attribute "color" must be unique

re edit failed on configurable product, it shows like at above

**Comment by korostii** [comment] 2017-05-10 17:20
You probably have multiple simple products attached that happen to have the same value of attribute "color". Can be resolved by removing of them from the configurable product.

This is _not a bug_, such a behavior is to be expected.

**Comment by veloraven** [comment] 2017-06-22 12:54
@ps3z thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by magento-engcom-team** [comment] 2017-09-07 20:49
@ps3z we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Closed as completed by magento-engcom-team** 2017-09-07 20:49 UTC
Labels: Progress: needs update
