### ISSUE TITLE
Editing a configurable product from the cart doesn't select the previously selected swatch.

### ISSUE THREAD

**Issue by paales** [magento/magento2#5218] opened 2016-06-24 10:06 UTC
Magento 2.1.0

Possibly related #4440 but @tkacheva seems to have misunderstood the issue (?). Swatches are shown, but options aren't selected.
### Steps to reproduce
1. Create a configurable product with multiple colors and images on the simple.
2. Use the color as a color swatch
3. Add the variation to the cart.
   ![schermafbeelding 2016-06-24 om 12 02 15](https://cloud.githubusercontent.com/assets/1244416/16334809/85701c46-3a03-11e6-9147-1e6e8d059ac3.png)
4. Edit the product from your cart.
### Expected result

![schermafbeelding 2016-06-24 om 12 03 13](https://cloud.githubusercontent.com/assets/1244416/16334828/ad25fe0e-3a03-11e6-9920-67355fd672ae.png)
### Actual result

![schermafbeelding 2016-06-24 om 12 03 07](https://cloud.githubusercontent.com/assets/1244416/16334825/a5727c50-3a03-11e6-951f-71c02558f4d8.png)

**Comment by phuc128t** [comment] 2016-06-24 10:15
This issue reported many times but still not fixed in 2.1

**Comment by paales** [comment] 2016-06-24 10:29
@eric128 Could you maybe reference the other related issues, might make this issue more visible.

**Comment by paales** [comment] 2016-06-24 10:32
Found this one https://github.com/magento/magento2/issues/4684

**Comment by andimov** [comment] 2016-06-24 15:29
We already have a similar ticket MAGETWO-53459 in our internal backlog.

**Comment by paales** [comment] 2016-06-24 19:21
@andimov Thanks for the update, found out after finding the other bug!

**Comment by PierAlex** [comment] 2016-10-13 08:15
@andimov I got also this issue, in the minicart the preview image is the base preview image, not the one choosen. Eg. My base image is the white color, I select the black and add to cart, in the minicart my preview image is the White, Is this related to this open issue or have I to report a new issue?

@paales aren't you experiencing this problem?

PierAle

**Comment by paales** [comment] 2016-10-13 08:26
@PierAlex We're experiencing that as well, made some internal patch I believe to solve the issue, but can't remember exactly.

**Comment by PierAlex** [comment] 2016-10-13 08:49
@paales Do you pls remember where i have to look to fix this last problem? It will be very helpful.
Thanks in advance

**Comment by paales** [comment] 2016-10-13 08:50
@PierAlex I asked, eventually it was just a setting.. 😛

**Comment by magento-engcom-team** [comment] 2017-10-13 12:30
@paales, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-13 12:30 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid
