### ISSUE TITLE
Request: `cron:install` should install only crucial entry by default

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#26477] opened 2020-01-21 16:24 UTC
### Summary (*)
It is very common for developers to not read the [documentation](https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-cron.html). As a result - they install Cron Jobs with `bin/magento cron:install`. That way - they get 1 crucial entry (`cron:run`) and 2 redundant entries (`update/cron.php` and `setup:cron:run`) in the production environment.

### Examples (*)
```
$ bin/magento cron:install
$ crontab -l
#~ MAGENTO START c5f9e5ed71cceaabc4d4fd9b3e827a2b
* * * * * /usr/bin/php /var/www/html/magento2/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /var/www/html/magento2/var/log/magento.cron.log
* * * * * /usr/bin/php /var/www/html/magento2/update/cron.php >> /var/www/html/magento2/var/log/update.cron.log
* * * * * /usr/bin/php /var/www/html/magento2/bin/magento setup:cron:run >> /var/www/html/magento2/var/log/setup.cron.log
#~ MAGENTO END c5f9e5ed71cceaabc4d4fd9b3e827a2b
```

### Proposed solution
* Install only `cron:run` by default
* Add extra flag `--with-update` to install `update/cron.php`
* Add extra flag `--with-setup` to install `setup:cron:run`

### ACK
@PiotrSiejczuk

**Comment by hostep** [comment] 2020-01-21 18:46
I'm going to close this as a duplicate of https://github.com/magento/magento2/issues/24186
Feature request has already been handled in https://github.com/magento/magento2/pull/24187 and will be released in Magento 2.3.4 where you will be able to execute:
```
bin/magento cron:install --non-optional
```

Thanks! 🙂

**Closed as completed by hostep** 2020-01-21 18:47 UTC
Labels: Issue: Format is valid
