### ISSUE TITLE
Export csv orders from order grid in adminhtml

### ISSUE THREAD

**Issue by basselalaraaj** [magento/magento2#6291] opened 2016-08-23 13:18 UTC
### Preconditions
1. Magento develop branch
2. php 7 and mysql 5.6
### Steps to reproduce

1. Login as user with a different role than administrator with full rights to orders.
2. Go to order grid in adminhtml
3. No export button available for the orders.
### Expected result
1. A user with a role different than administrator with full rights to order grid in adminhtml should be able to export orders to csv.
### Actual result
1. No export button on the order grid in adminhtml.

**Comment by sevos1984** [comment] 2016-08-25 11:49
Hi! Please specify your magento version and attach screenshot of your user role permissions. Thanks.

**Comment by basselalaraaj** [comment] 2016-08-25 11:53
@sevos1984 
Magento develop branch (2.1.0)
![screen shot 2016-08-25 at 13 53 11](https://cloud.githubusercontent.com/assets/5745279/17968106/51a6cf10-6acb-11e6-9b31-b9e61e507606.png)

**Comment by sevos1984** [comment] 2016-08-25 13:40
This is not reproducible as well, try clearing cache and observe your magento logs for errors.

**Comment by basselalaraaj** [comment] 2016-08-26 07:14
@sevos1984 still reproducible, when trying to export i get this error.
The logs are not showing any errors.
are you testing with a user with a role different than administrator?
![screen shot 2016-08-26 at 08 55 23](https://cloud.githubusercontent.com/assets/5745279/17996799/567a4d46-6b6b-11e6-81e3-e30cf1009e73.png)

**Comment by sevos1984** [comment] 2016-08-26 09:32
Yes, I have restricted user role, with only permissions that are on screenshot. Could you please make a screenshot of all permissions on page?

**Comment by sevos1984** [comment] 2016-09-12 07:27
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-09-12 07:27 UTC
