### ISSUE TITLE
Purchase date on admin screen is always *:07:00

### ISSUE THREAD

**Issue by RocketmanLabs** [magento/magento2#5651] opened 2016-07-14 22:08 UTC
1. Go to the admin screen and view the first page of Orders.
2. Note that the date/time under the heading Purchase Date is always *:07:00
3. Time stamp appears correct in REST API return values ('created_at' attribute).

**Comment by pboisvert** [comment] 2016-07-14 22:11
Can you provide more info to troubleshoot such as which version you are using? How were the orders created? Was this an upgrade from a previous version? etc...

**Comment by RocketmanLabs** [comment] 2016-07-14 22:48
This is a recent upgrade to Magento 2.1.  The orders came in from people buying our stuff on the website.  Screen cap follows:
![magentoscreencap16-07-14](https://cloud.githubusercontent.com/assets/19786652/16858223/47551f6a-49da-11e6-8d42-04aa11d4d523.png)

**Comment by pboisvert** [comment] 2016-07-15 00:02
thanks--that should help narrow down the possible cause.

**Comment by Krapulat** [comment] 2016-07-22 08:44
I have the same problem.

**Comment by ghost** [comment] 2016-08-08 18:59
Same issue here as well. Using 2.1 CE.

**Comment by kennylawrence** [comment] 2016-08-08 20:59
same here
FYI I am using a database that was migrated from 1.9.2.2ce -> 2.1ce

**Comment by xaviermarchegay** [comment] 2016-08-11 12:29
The date format specified in the sales grid is wrong : https://github.com/magento/magento2/commit/81de258e374d387a60529001849478210fa78aab

Instead of displaying the minutes (mm), the month is displayed (MM).

The right format is MMM dd, YYYY, H:**mm**:**ss** A

edit: thanks @LucScu

**Comment by xmav** [comment] 2016-08-26 15:58
Hi @RocketmanLabs , thanks for reporting this issue. Internal ticket MAGETWO-53138 was created.

Best,
Maksym

**Comment by lucscu** [comment] 2016-09-07 06:55
@xaviermarchegay the correct format is
`<item name="dateFormat" xsi:type="string">MMM dd, YYYY, H:mm:ss A</item>`

**Comment by PascalBrouwers** [comment] 2016-10-19 13:01
I also have this on a clean install of Magento 2.1.2

**Comment by lucscu** [comment] 2016-10-28 10:32
@PascalBrouwers You have to look at the xml in question: if you see the old code the issue is still present.

**Comment by claridgicus** [comment] 2016-11-02 00:41
Hey guys, this timestamp issue is still featuring in 2.1.2 - is it going to be resolved in 2.1.3 or?

**Comment by bh-ref** [comment] 2016-12-28 10:05
the issue is still present in CE 2.1.3

**Comment by maximehuran** [comment] 2017-02-01 22:05
I confirm

**Comment by vrann** [comment] 2017-02-03 16:13
Fixed in #8336

**Closed as completed by vrann** 2017-02-03 16:13 UTC
Labels: Issue: Ready for Work, bug report, Component: Sales

**Comment by bh-ref** [comment] 2017-02-21 09:15
@vrann thank you for fixing it!

**Comment by devtinku** [comment] 2017-05-22 12:00
@LucScu  Your suggestion works if i change it in core file. How can i do the changes without touching core files.

I tried with below steps but its not worked ::
1. Copied sales_order_grid.xml to custom module
2. Cleared cache

**Comment by lucscu** [comment] 2017-06-27 08:48
@devtinku i suggest you to not lose your time on how to make this fix in a custom module. Keep it in the core file and add the file to git so you could see future update changes. Then wait for magento version with official fix, after this you could remove file from repo.

**Comment by magento-team** [comment] 2017-07-31 22:48
Internal ticket to track issue progress: MAGETWO-70771

**Comment by andidhouse** [comment] 2017-08-03 07:47
Shure @magento-team - this bug is one year old and now you create an internal ticket to track the progress of this? Wow - would you be so kind to think about fixing bugs instead of reporting hundreds of internal tickets without any bugfix?

**Comment by steverobbins** [comment] 2017-08-18 23:13
@magento-team Here's your weekly reminder that we're still waiting for this fix.

**Comment by kennylawrence** [comment] 2017-08-21 03:20
oh. my. gosh. how do you turn off tracking for bugs? this is embarassing.

**Comment by OZZlE** [comment] 2017-08-22 08:12
Still happens in 2.1.7....
