### ISSUE TITLE
Backand Payments could not be saved

### ISSUE THREAD

**Issue by Olek89** [magento/magento2#25562] opened 2019-11-11 19:09 UTC
### Preconditions (*)
1. Magento 2.3.3 after Upgrading from 2.3.2.
2. 7.2
2. Apache/2.4.25 (Debian)

### Steps to reproduce (*)

1. Click on Store -> Configuration ->  Custom -> Payment -> on clicking at the save button it`s only jumping to the top, but nothing saving

### Expected result (*)
there are no logs for it.
It still hanging on saveing, nothing doing there.

### Actual result (*)

First Click:
![image](https://user-images.githubusercontent.com/31250340/68613407-fa6d8400-04be-11ea-8011-e9447be2571b.png)
Second Click:
![image](https://user-images.githubusercontent.com/31250340/68613440-09543680-04bf-11ea-9bf7-0f6dc23bfa64.png)
Third Click:

![image](https://user-images.githubusercontent.com/31250340/68613458-12450800-04bf-11ea-951c-4b65800284b8.png)

But nothing happens or saving.

**Comment by Olek89** [comment] 2019-11-11 19:37
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment] 2019-11-11 19:37
Hi @Olek89. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment] 2019-11-11 19:38
Hi @Olek89, here is your [Magento instance](https://i-25562-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-25562-2-3-3.instances.magento-community.engineering/admin](https://i-25562-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Olek89** [comment] 2019-11-11 19:41
Thy, in these instance the error not happening, what could it be?

**Comment by ajijshekh123** [comment] 2019-11-12 04:49
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-12 04:49
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-12 04:49
Hi @ajijshekh123, here is your [Magento instance](https://i-25562-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25562-2-3-develop.instances.magento-community.engineering/admin](https://i-25562-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2019-11-12 05:00
@Olek89 - I have reviewed this issue in Default Magento 2.3 instance but I didn't found any Custom option on the configuration section. 
I think you are using a third party payment extension that's this issue you have to face.

@Olek89 - If you have found this issue again on your Magento instance. You can ask me the proper steps or send me details on which payment extension you are using or ask me to close this issue.

Thanks.

**Comment by Olek89** [comment] 2019-11-12 07:00
@ajijshekh123 thank you, i think i found the problem, because i am using an old PayPal Plus with PHP 7.2 thats no compatible, i have changed the php to 7.1 and its working, i will update thesse payment modul and will show if its work or not.

Thy.

**Comment by ajijshekh123** [comment] 2019-11-12 07:23
Okay @Olek89, No issue. You can update me whenever you have updated your payment module and verify the issue.

**Comment by Olek89** [comment] 2019-11-12 20:01
Thank you, now the backend works, but now i am hanging to place an order, its only like a spool, the ordermail is coming, but not in the shop the information, that the order has placed with this ID:

![image](https://user-images.githubusercontent.com/31250340/68706177-a1215580-058f-11ea-9e26-46077d9a8358.png)

**Comment by ajijshekh123** [comment] 2019-11-13 05:24
Hi @Olek89,

Which payment method you are using for a place the order? It may be any third party payment module issue that's why to hang your place order system.
Can you please verify this scenario on default Magento?

Thanks.

**Comment by Olek89** [comment] 2019-11-13 16:01
Hi @ajijshekh123,

i am using the payment modul from iways for paypal plus.

https://github.com/i-ways/magento2-paypal-plus

I can`t install it on the testinstance of magento2, sorry. :-(

**Comment by ajijshekh123** [comment] 2019-11-14 05:31
Hi @Olek89,
What can I do for you? 
Can I close this issue?
Please update me.

Thanks.

**Comment by ajijshekh123** [comment] 2019-11-15 04:55
@Olek89 - I think you are using third party extension that's why you may reproduce the issue.
@sdzhepa - Can you please help him?
@Olek89 - Please wait for the @sdzhepa response.

Thanks.

**Comment by sdzhepa** [comment] 2020-10-08 20:20
Sorry for the late response..missed the notification

Seems this issue is not actual now, we are not able to reproduce it with the latest code and magento versions

**Closed as completed by sdzhepa** 2020-10-08 20:20 UTC
Labels: Component: Config, Issue: Clear Description, Issue: Format is valid, Component: Store, Progress: done
