### ISSUE TITLE
Cannot create or update a credit memo through API

### ISSUE THREAD

**Issue by mattheo-geoffray** [magento/magento2#23728] opened 2019-07-16 13:45 UTC
### Preconditions (*)
1. Magento Open Source v2.3.1

### Steps to reproduce (*)
1. Create an order
2. Create an invoice
3. Create a credit memo (_not using API_)
4. Use `/V1/creditmemo` endpoint to update it with payload formated as in https://devdocs.magento.com/redoc/2.3/admin-rest-api.html#operation/salesCreditmemoRepositoryV1SavePost   
**Important** . `adjustment_positive` or `adjustment_negative` **MUST** be before `order_id` entry in the body request

### Expected result (*)
1. API return a code 200 and update the credit memo

### Actual result (*)
1. API return a code 400 with error `Please provide payment for the order.`

### Explications
- In `\Magento\Framework\Webapi\ServiceInputProcessor::_createFromArray` will create a new `\Magento\Sales\Api\Data\CreditmemoInterface` instance with data from the request body in order to be processed by `\Magento\Sales\Model\Order\CreditmemoRepository::save`  
- Magento use the `ClassReflection` to get setters and getters from `\Magento\Sales\Model\Order\Creditmemo`  
- In `\Magento\Framework\Webapi\ServiceInputProcessor::_createFromArray` it will call Credit Memo setter `setAdjustmentPositive` with `$object->{$setterName}($setterValue);`   
- In the setter `\Magento\Sales\Model\Order\Creditmemo::setAdjustmentPositive` it will call `\Magento\Sales\Model\Order\Creditmemo::getOrder`  which will use the `order_id`   
- Because of this logic and the order in the parameter the `order_id` will not be set yet and the `\Magento\Payment\Observer\SalesOrderBeforeSaveObserver::execute` can not found the linked order

#### Please provide payment for the order.
```
#0 /generated/code/Magento/Sales/Model/Order/CreditmemoRepository/Interceptor.php(50): Magento\Sales\Model\Order\CreditmemoRepository->save(Object(Magento\Sales\Model\Order\Creditmemo\Interceptor))
#1 [internal function]: Magento\Sales\Model\Order\CreditmemoRepository\Interceptor->save(Object(Magento\Sales\Model\Order\Creditmemo\Interceptor))
#2 /vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)
#3 /vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process(Object(Magento\Framework\Webapi\Rest\Request\Proxy))
#4 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#5 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)
#6 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#7 /generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(26): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)
#8 /framework/App/Http.php(136): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#10 /pub/index.php(40): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#11 {main}
```

**Comment by engcom-Bravo** [comment] 2019-07-17 08:00
Hi, @mattheo-geoffray ! I have to close this issue, because i can't reproduce this on vanilla 2.3-develop and 2.3.1 open source.
**Manual testing scenario:**
1.Create an order
2.Create an invoice
3.Create a credit memo (not using API)
4.Use /V1/creditmemo endpoint to update
**Important:** adjustment_positive or adjustment_negative MUST be before order_id entry in the body request
**Actual result:**
2.3-develop:
![23](https://user-images.githubusercontent.com/51680745/61357855-c15f3300-a881-11e9-9efb-1453d7f53e4f.png)
2.3.1 Open source:
![231](https://user-images.githubusercontent.com/51680745/61357881-ce7c2200-a881-11e9-9863-6f6774900d4e.png)

Maybe you have some additional instructions?

**Closed as completed by engcom-Bravo** 2019-07-17 08:00 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid

**Comment by stereoscope** [comment] 2019-12-13 14:04
I get the same exception message by using the soap-api in Magento v2.3.3
