### ISSUE TITLE
Wrong import rows processed when a previous import has only been validated

### ISSUE THREAD

**Issue by andrei-furnica** [magento/magento2#38490] opened 2024-03-05 17:49 UTC
### Preconditions and environment

- Magento version: 2.4.6-p3

### Steps to reproduce

1. go to System -> Import
2. select an import type (ex: Producsts)
3. select a file and click "Check Data". **do not click on the import button**
4. refresh the page
5. select a different import type (ex: Stock Sources)
6. select a file and click "Check Data"
7. click "Import"

### Expected result

The latest import is processed.

### Actual result

An error is thrown and the import is not processed.

![image](https://github.com/magento/magento2/assets/3817709/a125f567-0f31-48b2-b2c2-d15cdc52450f)

### Additional information

What seems to happens is:
- when the import data is checked (by clicking on "Check Data") one or more rows are added to the "importexport_importdata" table
- at the second import, when the "Import" button is clicked and the import is processed, the `\Magento\ImportExport\Model\ResourceModel\Import\Data::getIterator` method is called and is retrieving the rows from the `importexport_importdata` table, oldest first
- if any row returned by the said method contains a different value in the `entity` column than the one of the current import, the error from the screenshot is thrown
- the issue is fixed by itself after 24h since the first import. the old rows are deleted by the `\Magento\ImportExport\Model\ResourceModel\Import\Data::cleanProcessedBunches` method which is called when the import is processed.

- the issue was introduced in the 2.4.6 release. before that, all the rows existing in the `importexport_importdata` table were deleted when processing an import, but [this commit](https://github.com/magento/magento2/commit/41e557619eaeee58f1fb29e0da2cebb85cf4b000) replaced the call to `$this->_dataSourceModel->cleanBunches();` with a call to `$this->_dataSourceModel->cleanProcessedBunches();`

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment] 2024-03-05 18:41
This sounds similar to #37593, not sure if it's an exact duplicate though.

**Comment by andreifurrnica** [comment] 2024-03-05 20:29
@hostep indeed, it looks like it's the same issue but with different reproduction steps.

**Comment by engcom-Dash** [comment] 2024-03-06 09:59
Hi @andreifurrnica 

Thank you for reporting and collaboration.

Verified the issue in magento 2.4 dev instance but the issue is not reproducable.

The latest import is successfully processing.

Steps to reproduce :
go to System -> Import
select an import type (ex: Producsts)
select a file and click "Check Data". do not click on the import button
refresh the page
select a different import type (ex: Stock Sources)
select a file and click "Check Data"
click "Import"

Please refer the attached screen recording and let us know if we have missed anything.

https://github.com/magento/magento2/assets/60198592/0a202cc4-26b7-4f62-8230-c56a3db96eef

**Comment by andreifurrnica** [comment] 2024-03-06 10:11
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2024-03-19 06:50
Hi @andreifurrnica 

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2024-03-19 06:50 UTC
Labels: Issue: needs update, Reported on 2.4.6-p3

**Comment by GrassH** [comment] 2024-11-05 07:33
@magento give me 2.4-develop instance
