### ISSUE TITLE
Wishlist icon cut on Shopping cart page in mobile view

### ISSUE THREAD

**Issue by hitesh-wagento** [magento/magento2#17851] opened 2018-08-29 10:29 UTC
### Summary

Wishlist icon cut on Shopping cart page in mobile view.

### Preconditions
1. Magento 2x - This issue reproduce in all version.

### Steps to reproduce
1. Login in your frontend.
2. Add any product in Cart.
3. Go to Shopping cart.
4. Switch mobile view.

### Expected result

1. Wishlist icon should not cut in mobile view.

### Actual result

1. Wishlist icon cut in mobile view.

![wishlist-icon](https://user-images.githubusercontent.com/23443991/44782289-5c84e680-aba4-11e8-9bf0-026fcf8f5a2f.png)

**Comment by magento-engcom-team** [comment] 2018-08-29 10:29
Hi @hitesh-wagento. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@hitesh-wagento do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [x] no

**Comment by hitesh-wagento** [comment] 2018-08-29 10:29
I am working on this issue.

**Comment by osrecio** [comment] 2018-08-29 12:15
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2018-08-29 12:15
Hi @osrecio. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2018-08-29 12:16
Hi @osrecio, here is your [Magento instance](https://i-17851-2-2-develop.engcom.dev.magento.com).
Admin access: [https://i-17851-2-2-develop.engcom.dev.magento.com/admin](https://i-17851-2-2-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sidolov** [comment] 2018-09-04 10:02
Hi @hitesh-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#17877 by @hitesh-wagento in 2.2-develop branch
Related commit(s):
 - [2139fec9ea8062223203291cfc5bdab8aa2d38ff](https://github.com/magento/magento2/commit/2139fec9ea8062223203291cfc5bdab8aa2d38ff)

The fix will be available with the upcoming 2.2.7 release.

**Closed as completed by sidolov** 2018-09-04 10:02 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Area: Design/Frontend

**Comment by sidolov** [comment] 2018-09-05 14:37
Hi @hitesh-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#17912 by @hitesh-wagento in 2.1-develop branch
Related commit(s):
 - [9cc84815051f2f58b51bd78f7b4bcb97bbb5a936](https://github.com/magento/magento2/commit/9cc84815051f2f58b51bd78f7b4bcb97bbb5a936)

The fix will be available with the upcoming 2.1.16 release.

**Comment by ishakhsuvarov** [comment] 2018-09-11 10:18
Hi @hitesh-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#17911 by @hitesh-wagento in 2.3-develop branch
Related commit(s):
 - [f0b5ecc17cbfde45f37d7a09a285d99653740d05](https://github.com/magento/magento2/commit/f0b5ecc17cbfde45f37d7a09a285d99653740d05)

The fix will be available with the upcoming 2.3.0 release.
