### ISSUE TITLE
MagentoCE2.4.3: Coupon set to Uses per Customer = 1. Coupon can be used in multiple orders by the same customer.

### ISSUE THREAD

**Issue by broeder** [magento/magento2#35077] opened 2022-02-10 08:23 UTC
### Preconditions (*)

1.MagentoCE2.4.3
2.

### Steps to reproduce (*)

1.Marketing -> Cart Price Rule -> Select specific rule -> Select specific coupon code and then set value in Uses per coupon = 0 & Uses per Customer = 1. Action: 10% discount.
2.Log in Front End. Checkout using coupon code. 

### Expected result (*)

1. [Screenshots, logs or description]
2. Expected Result: Coupon is redeemed. Total price is reduced by 10%. WORKS ONLY ONCE PER CUSTOMER. NOT MULTIPLE TIMES.

### Actual result (*)

1. [Screenshots, logs or description]
2.Actual Result: Coupon is redeemed. Total price is reduced by 10%. WORKS MULTIPLE TIMES PER CUSTOMER.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._
S2

**Comment by engcom-Lima** [comment] 2022-02-11 13:10
Hi @malan

Thank you for reporting the issue.
We verified the issue on Magento 2.4-develop branch and the issue is reproducible.

Steps performed:
1. Install a clean version of Magento 2.4-develop
2. Create a new product
3. Go to **Marketing->Cart Price Rule->Select specific rule** , select specific coupon code and then set value in **Uses per coupon = 0** & **Uses per Customer = 1** **Action: 10% discount**.
4. Log in to the Front End and checkout using coupon code.

**Result:**
Coupon is redeemed. Total price is reduced by 10%. However same coupon works multiple times for the same customer

**Product 1**
![image](https://user-images.githubusercontent.com/60198022/153596860-7d555db5-6d6c-47b0-b26c-ca860d254be4.png)

**Product 2**
![image](https://user-images.githubusercontent.com/60198022/153597024-4dbbe298-7aa3-4990-889a-30eb44e9582b.png)

Based on this confirming the issue.
Thanks!

**Comment by korovitskyi** [comment] 2022-02-15 15:51
@magento I am working on this

**Comment by engcom-Alfa** [comment] 2022-03-08 09:49
Hi @broeder Thanks for your contribution here.
As per above comments and our further investigation on this reported issue, we have to have Rabbitmq installed and configured. So that you will not notice this issue as such.

1. Have Magento latest instance installed.
2. Have rabbitmq installed and with its account
3. Execute the Magento CLI command from Magento root directory: **bin/magento setup:config:set --amqp-host=_127.0.0.1_ --amqp-port=_5672_ --amqp-user=_guest_ --amqp-password=_guest_ --amqp-virtualhost=/** (Note- Here u have to change the parameter values according to your account)
4. Place an order with above mentioned coupon and tax as such.
5. Run this command too before placing next order - **bin/magento queue:consumers:start sales.rule.update.coupon.usage  &**
6. If you try to run place the order using same coupon code again with same customer login, you will notice the function working fine.

As off now, closing this issue; in case of any more clarifications, you may please re-open the same issue or create a fresh mentioning all the details appropriately.

@korovitskyi Thanks for your collaboration and suggestion on this here

Thanks

**Closed as completed by engcom-Alfa** 2022-03-08 09:49 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P1, Progress: done, Reported on 2.4.3, Area: Cart & Checkout

**Comment by Kishorchhugani** [comment] 2023-08-03 05:30
Hello @engcom-Alfa 

Any Answer on my comment?

**Comment by broeder** [comment] 2023-08-03 08:42
Hi,
Issue fixed with magento latest as of this writing.

Le jeu. 3 août 2023 à 06:30, Kishor Chhugani ***@***.***> a
écrit :

**Comment by Kishorchhugani** [comment] 2023-08-03 11:56
hi @broeder ,
What is the solution for current magento version 2.4.4

We do not want to upgrade latest.
