### ISSUE TITLE
magento modules adding to XML is overriding layout from override in theme

### ISSUE THREAD

**Issue by AndresInSpace** [magento/magento2#37148] opened 2023-03-09 07:47 UTC
### Preconditions and environment

M2.4.5p-1 

Native modules extending XML layouts by handle reference (eg, customer_account_create.xml) are including layout attribute and value that ends up overriding the value set in current theme layout extensions/overrides. 

Specifically, I have found
`vendor/magento/module-login-as-customer-assistance/view/frontend/layout/customer_account_create.xml`
`vendor/magento/module-newsletter/view/frontend/layout/customer_account_create.xml`
resetting to 1column page due to them having `layout="1column"` in the page tag

### Steps to reproduce

Setup custom theme, apply to site, myvendor/mycurrenttheme
Change page layout for a specific route via xml override, for the known example use:

`myvendor/mycurrenttheme/Magento_Customer/layout/override/base/customer_account_create.xml`
Change layout to 3column
`<page layout="3columns" ...`
Flush cache
Reload customer account create page

### Expected result

customer account create page should show using 3column layout

### Actual result

customer account create page shows still using 1column layout

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2023-03-21 10:15
Hello @AndresInSpace,

Thanks for the report and collaboration!

We have tried to reproduce this issue in Magento 2.4-develop branch but it seems the issue is not reproducible for us. In order to reproduce the issue, we have created a custom theme. You can find the same below:
[Magz.zip](https://github.com/magento/magento2/files/11027095/Magz.zip)

Please let us know in case we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2023-04-04 05:57
Dear @AndresInSpace,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2023-04-04 05:57 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.5-p1
