### ISSUE TITLE
Update phpstan/phpstan dependency to PHP 8 compatible version

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#31176] opened 2020-12-04 15:37 UTC
### Description (*)
Update phpstan/phpstan dependency version from ">=0.12.3 <=0.12.23" to ">=0.12.3 <=0.12.54"
Ensure composer install runs on PHP 7.4 and 8.0

**Comment by ihor-sviziev** [comment] 2020-12-17 20:46
Hi @sivaschenko,
This is duplicate of https://github.com/magento/magento2/pull/30581
That was approved in October, but still didn’t get any attention. Can we close this one and move forward original one?

**Closed as completed** 2021-01-27 18:12 UTC
Labels: Fixed in 2.4.x, Severity: S4, Priority: P4, Progress: done, Project: PHP8

**Comment by magento-engcom-team** [comment] 2021-03-12 15:51
Hi @sivaschenko, @hostep. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39645` was closed as `Complete`. 

The fix will be available with the upcoming `2.4.3` release.
