### ISSUE TITLE
graphql get groduct on second website

### ISSUE THREAD

**Issue by DeadDance202** [magento/magento2#37547] opened 2023-05-26 12:26 UTC
### Preconditions and environment

- Magento version 246
- php 8.2

### Steps to reproduce

1. create two websites with store views (use store code to switch between websites)
2. create product 
3. use this product ONLY on the second website
4.  create qraphql query (https://developer.adobe.com/commerce/webapi/graphql/usage/headers/)

```
{
  products(
    filter: { sku: { eq: "24-WB01" } }
  ) {
    items {
      name
      sku
    }
  }
}
```

### Expected result

```
{
  "data": {
    "products": {
      "items": [
        {
          "name": "Voyage Yoga Bag",
          "sku": "24-WB01"
        }
      ]
    }
  }
}
```

### Actual result

```
{
  "data": {
    "products": {
      "items": []
    }
  }
}
```

### Additional information

When we try to get the product, for example, from the Magento product repository with GraphQL queries, GraphQL tries to get the 'stock' parameter from the headers and cookies:
vendor/magento/module-store-graph-ql/Controller/HttpHeaderProcessor/StoreProcessor.php -> processHeaderValue
- $headerValue -> is empty
- $this->isAlreadySet() -> false
- $this->storeCookieManager->getStoreCodeFromCookie() -> return 'default' store

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-05-29 06:17
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-05-29 13:06
Hi @DeadDance202,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- create two websites with store views (use store code to switch between websites)
- create product
- use this product ONLY on the second website
- create qraphql query (https://developer.adobe.com/commerce/webapi/graphql/usage/headers/)


We are able to get the product details.Please check whether the product is assigned to second website.

<img width="1439" alt="Screenshot 2023-05-29 at 2 43 45 PM" src="https://github.com/magento/magento2/assets/51680745/f503dddc-70e0-4aff-9e5f-2b86841ff874">



<img width="637" alt="Screenshot 2023-05-29 at 2 43 35 PM" src="https://github.com/magento/magento2/assets/51680745/6563c1f9-333c-4e3c-abcb-6e8db7c10f85">


<img width="1319" alt="Screenshot 2023-05-29 at 2 43 29 PM" src="https://github.com/magento/magento2/assets/51680745/a6a1cea5-b6cd-4493-9bec-1127a5f0b0cb">



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-06-12 06:35
Hi @DeadDance202,

Please provide us latest update on this https://github.com/magento/magento2/issues/37547#issuecomment-1567118226 if you are able to reproduce the issue provide us steps to reproduce the issue.Please let us know if you are facing any issue.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-06-26 06:08
Hi @DeadDance202,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-06-26 06:08 UTC
Labels: Issue: needs update, Reported on 2.4.6
