### ISSUE TITLE
Unable to issue refund

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#29014] opened 2020-07-06 16:19 UTC
### Preconditions (*)

Magento 2.3.3

### Steps to reproduce (*)

1. Create order with two items
2. Invoice the order
3. Create credit memo, enter a sum in "Adjustment refund" box
4. Hit "Refund"

### Expected result (*)

Able to refund.

### Actual result (*)

The most money available to refund is XXX.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment] 2020-07-06 18:19
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-07-06 18:19
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-07-14 18:32
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35858` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by madhurajawat** [comment] 2020-07-16 05:51
@magento I am working on this

**Comment by madhurajawat** [comment] 2020-07-16 05:52
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-07-16 05:52
Hi @madhurajawat. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-07-16 05:53
Hi @madhurajawat, here is your [Magento instance](https://i-29014-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29014-2-4-develop.instances.magento-community.engineering/admin_6b39](https://i-29014-2-4-develop.instances.magento-community.engineering/admin_6b39)
Login: `83a17a2e` Password: `2d66b26d77d8`
Instance will be terminated in up to 3 hours.

**Comment by madhurajawat** [comment] 2020-07-16 06:32
@Zyles Can you please elaborate more step 3. Create credit memo, enter a sum in "Adjustment refund" box
What you are doing exactly in this step? If possible please share the screenshot

**Comment by ajijshekh123** [comment] 2020-07-17 19:06
Hi @sdzhepa & @madhurajawat,
In the Credit Memo section,  
Ex: My Grand Total is $8.07 and Enter the Adjustment Refund is $35.00 then Click on Update Totals button. It's working fine but Again click on the "Refund Offline" button. It is showing an error "The most money available to refund is $8.07.".

Thanks.

**Comment by sdzhepa** [comment] 2020-07-24 19:04
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-07-24 19:17
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-07-24 19:18
Hi @sdzhepa, here is your [Magento instance](https://i-29014-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29014-2-4-develop.instances.magento-community.engineering/admin_d53a](https://i-29014-2-4-develop.instances.magento-community.engineering/admin_d53a)
Login: `a0c20e20` Password: `d97b1e4914a0`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment] 2020-07-24 19:26
Hello @Zyles 
cc: @ajijshekh123

Thank you for your contribution and collaboration!

At first glance, it looks like a bug but after dig deeper,  and read the documentation I found it is expected behavior.

Quote from the [official documentation "Create a Credit Memo"](https://docs.magento.com/user-guide/sales/credit-memo-create.html)

> For Adjustment Refund, enter a value to be added to the total amount refunded as an additional refund that does not apply to any particular part of the order (shipping, items, or tax).
> 
> **The amount entered cannot raise the total refund higher than the paid amount.**

It means that "Adjustment Refund" cannot be used to return more money that was paid for all ordered items.
But it applicable in the case with a partial refund.

Example of a partial refund with "Adjustment Refund":

1. There is invoiced order with two items/products
-- Product1, price = $100
-- Product2, price = $50

2. But Customer desires to return Product1 because it e.g. damaged or wrong or etc.

3. Store Owner creates partial return/refund 
-- for one item - Product1  
-- and addition $25 as compensation, Adjustment Refund = 25

Total refund amount lest then total ordered amount.

So, if you need to return the amount bigger than all order total, "Adjustment Refund" is not applicable to such a case.
I cannot remember any other base Magento functionality that can satisfy this case but probably it already exists as a part of extension/customization of Marketplace

**Closed as completed by sdzhepa** 2020-07-24 19:26 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Admin, Reproduced on 2.4.x, Reported on 2.3.3

**Comment by vinhan2020** [comment] 2021-05-08 05:02
give me 2.4-develop instance
