### ISSUE TITLE
partially create invoice and refund not working proper in magento 2.2.2

### ISSUE THREAD

**Issue by doth-web-developer** [magento/magento2#18145] opened 2018-09-20 05:21 UTC
My Invoice is ok...
![image](https://user-images.githubusercontent.com/35019950/45797377-dbac9c80-bcc2-11e8-84ad-9b08848e86ac.png)

Then shows credit memo are different charge to invoice...
![image](https://user-images.githubusercontent.com/35019950/45797432-11ea1c00-bcc3-11e8-9f69-5ac799811001.png)

**Comment by magento-engcom-team** [comment] 2018-09-20 05:46
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by engcom-backlog-nazar** [comment] 2018-09-20 05:50
Hi @doth-web-developer this is acknowledged bug -> https://github.com/magento/magento2/issues/17367
If you like to update this, please reopen the issue with next steps:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

**Closed by engcom-backlog-nazar** 2018-09-20 05:51 UTC
Labels: G1 Failed
