### ISSUE TITLE
Upgrade 2.0.7 to 2.1

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#5234] opened 2016-06-24 15:40 UTC
## Steps to reproduce

Tried to update 2.1 with:
`composer require magento/product-community-edition 2.1.0 --no-update`
`composer update`
## Expected result

Updated to 2.1
## Actual result

Error Says `magento/product-community-edition 2.1.0 requires composer/composer 1.0.0-beta1 -> satisfiable by composer/composer[1.0.0-beta1] but these conflict with your requirements or minimum-stability.`

Current composer version is 
`Composer version 1.1.2`

I've tried to change required composer version with `>=`, at this time it said :
`magento/product-community-edition 2.1.0 requires braintree/braintree_php 3.7.0 -> satisfiable by braintree/braintree_php[3.7.0] but these conflict with your requirements or minimum-stability.`

Ideas ?

**Comment by andimov** [comment] 2016-06-24 15:59
@rbostan 
Thank you for reporting. Please,  attach, your composer.json file here.

**Comment by cizgidekiadam** [comment] 2016-06-24 16:36
[composer.json.txt](https://github.com/magento/magento2/files/332102/composer.json.txt)

**Comment by cizgidekiadam** [comment] 2016-06-25 06:22
Hi,
Is there any solution for me ?

**Comment by salgua** [comment] 2016-06-27 11:08
Hi,
same problem here.

**Comment by andimov** [comment] 2016-06-27 16:28
@rbostan 
Please check that you used composer for installing prev version.
The easiest way to tell is to see whether or not all Magento components are under app/code; if so, you cloned GitHub and your solutioin [here ](http://magento.stackexchange.com/questions/116173/magento2-upgrade-from-2-0-4-to-2-0-6). If Magento components are under vendor, you used Composer and you can try fix this issue throught apply MDVA-532.\* patch. 
Instruction here: [Technical Bulletin. Upgrade to Magento version 2.1](http://devdocs.magento.com/guides/v2.1/release-notes/tech_bull_21-upgrade.html)

**Comment by cizgidekiadam** [comment] 2016-07-07 04:45
Components in /vendor folder. I have checked out github first, then install components with `composer install`. All necessary patches applied. 

Problem may be about a previous composer self-update. Because, i tried a clean install and everything is fine.

**Comment by oserediuk** [comment] 2016-07-07 16:00
@rbostan Did you upgrade magento to version 2.1 after composer self-update?

**Comment by cizgidekiadam** [comment] 2016-07-10 11:49
@oserediuk I did self-update at v 2.0.7 before trying upgrade. Problem may be current composer version (1.1.2) greater than 2.1 upgrade dependent composer version (1.0.0-beta1)

**Comment by oserediuk** [comment] 2016-07-11 08:55
@rbostan , so can we close this issue?

**Comment by cizgidekiadam** [comment] 2016-07-15 09:35
@oserediuk as you wish. For 2.0.7 users with composer version higher then 2.1 depends, problem may be still exists.

**Comment by spencerthayer** [comment] 2016-07-26 02:47
Same problem here.

**Comment by shiftedreality** [comment] 2016-09-07 12:12
Hi @rbostan 

I was not able to reproduce this issue with 2.0.9 -> 2.1.1 flow.
Did `composer self-update` helped you?

**Comment by cizgidekiadam** [comment] 2016-09-08 14:31
Hi @shiftedreality 
I did made a clean install with 2.1 . So didn't resolve anything.
As i mention [above](https://github.com/magento/magento2/issues/5234#issuecomment-231584971), i did self-update 'before' trying upgrade. Don't know this cause a problem but may be. (2.1 requires composer 1.0.0-beta1 but while trying update, my composer version was 1.1.2)

You may close this issue.

**Closed as completed** 2016-10-04 09:04 UTC
Labels: bug report, Progress: needs update, Component: Setup

**Comment by tomnyson** [comment] 2017-03-29 00:29
I can not upgrade Magento version 2.0.7 to 2.1.5
how I can you upgrade success not interrupt while updating
