### ISSUE TITLE
DisabledProductOptionPostProcessor in BundleGraphQl removes products at the wrong time causing page-size errors.

### ISSUE THREAD

**Issue by damienwebdev** [magento/magento2#37238] opened 2023-03-18 16:12 UTC
### Preconditions and environment

- Magento version v2.4.1+

### Steps to reproduce

1. Add a bundle item to the system into any category.
2. Set the bundle to enabled and visible with a required radio option child with any number of selections.
3. Make all of those selections disabled
4. Reindex
5. Make a GraphQl query and set the `page_size` of the query for products to 12 products
6. See that the collection count is off-by-one and see that the page the bundle is on contains `11` products instead of `12` (assuming the page you view is a complete page of products (12)).

### Expected result

See the correct collection count (not off by 1).

### Actual result

Collection count is off-by-one (or more depending upon the number of bundles in this condition.

### Release note

The bug is in https://github.com/magento/magento2/commit/1360bee9522653422288f5929a74b5caff6cf29a#diff-1fb5b82c1738230a8651650465cc61a6662387e7d72c4e3900f93043735a6996

This should be a `CompositeCollectionProcessor` not a `CompositeCollectionPostProcessor` and it should instead modify the original sql query to ensure that the count is correct.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-03-20 06:52
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-03-21 07:16
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-03-21 14:30
Hi @damienwebdev,

Thanks for your update.


Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**


- Add a bundle item to the system into any category.
- Set the bundle to enabled and visible with a required radio option child with any number of selections.
- Make all of those selections disabled
- Reindex
- Make a GraphQl query and set the page_size of the query for products to 12 products
- See that the collection count is off-by-one and see that the page the bundle is on contains 11 products instead of 12 (assuming the page you view is a complete page of products (12)).

Created Bundle product with required radio option.

![Bundle-Products-Inventory-Catalog-Magento-Admin (2)](https://user-images.githubusercontent.com/51680745/226602658-b954a991-ccef-4874-99e4-f5d5f3a7da26.png)

We have disabled child products.


![Products-Inventory-Catalog-Magento-Admin (1)](https://user-images.githubusercontent.com/51680745/226608460-4d23e9a9-f038-48ca-9882-fdd6feab89be.png)


We have used below query :


```
{
  products(filter: { sku: { eq: "Bundle" } },pageSize: 12) {
    total_count
    items {
      uid
      name
      sku
      url_key
      stock_status
      new_from_date
      new_to_date
      special_price
      
      special_to_date
      __typename
      short_description {
        html
      }
      description {
        html
      }
      image {
        url
        label
      }
      small_image {
        url
        label
      }
      thumbnail {
        url
        label
      }
      swatch_image
      media_gallery {
        url
        label
      }
      ... on BundleProduct {
        dynamic_sku
        dynamic_price
        dynamic_weight
        price_view
        ship_bundle_items
        items {
          uid
          title
          sku
          type
          required
          position
          options {
            uid
            label
            quantity
            can_change_quantity
            price
            price_type
            is_default
            position
            product {
              uid
              name
              sku
              stock_status
              __typename
            }
          }
        }
      }
    }
  }
}
```
After disabling the products we got below response.

<img width="1450" alt="Screenshot 2023-03-21 at 4 39 06 PM" src="https://user-images.githubusercontent.com/51680745/226603131-27c67436-78b2-43e9-bb81-ae193336d45f.png">


Kindly let us know if we are missing anything.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-04-03 06:05
Hi @damienwebdev,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-04-03 06:05 UTC
Labels: Issue: needs update, Reported on 2.4.1
