### ISSUE TITLE
Missing required argument $batchSizeAdjusters of Magento\Catalog\Model\ResourceModel\Product\Indexer\Price\BatchSizeCalculator

### ISSUE THREAD

**Issue by bordeo** [magento/magento2#21854] opened 2019-03-20 12:27 UTC
### Preconditions (*)

1. Magento 2.3.0
2. Install magento clean
3. remove modules  module-bundle, module-configurable and module-grouped in composer.json 
```
"replace": {
  "magento/module-bundle": "*",
  "magento/module-grouped": "*",
  "magento/module-configurable":"*"
}
```

### Steps to reproduce (*)

1. run `bin/magento index:reindex catalog_product_price`

### Expected result (*)

![Screenshot 2019-03-20 at 13 21 17](https://user-images.githubusercontent.com/1566127/54683917-3492ab80-4b13-11e9-92c0-dd9d1f577d2e.png)

### Actual result (*)

![Screenshot 2019-03-20 at 13 21 24](https://user-images.githubusercontent.com/1566127/54683966-50964d00-4b13-11e9-8667-15ef073ccbcc.png)

**Comment by magento-engcom-team** [comment] 2019-03-20 12:27
Hi @bordeo. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@bordeo do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-03-20 12:44
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by orlangur** [comment] 2019-03-20 13:17
@bordeo,

> remove modules module-bundle

`Magento_Bundle` is not removeable yet AFAIR, what if you remove only `module-configurable` and `module-grouped`?

**Comment by bordeo** [comment] 2019-03-20 14:11
I removed module-bundle by removing also other modules because I don't need it.
It all works with the fixed I proposed magento/magento2#21858

Every of these three modules inject an array value:
**magento/module-grouped**
https://github.com/magento/magento2/blob/d976a2bb85c91d95b380378c30167f1240f23657/app/code/Magento/GroupedProduct/etc/di.xml#L96-L98

**magento/module-configurable**
https://github.com/magento/magento2/blob/d976a2bb85c91d95b380378c30167f1240f23657/app/code/Magento/ConfigurableProduct/etc/di.xml#L183-L185

**magento/module-bundle**
https://github.com/magento/magento2/blob/d976a2bb85c91d95b380378c30167f1240f23657/app/code/Magento/Bundle/etc/di.xml#L180-L182

Here my current replace to remove unuseful modules for my project
```
  "replace": {
    "magento/module-dhl": "*",
    "magento/module-fedex": "*",
    "magento/module-marketplace": "*",
    "magento/module-multishipping": "*",
    "magento/module-captcha": "*",
    "magento/module-persistent": "*",
    "magento/module-catalog-rule-configurable": "*",
    "magento/module-authorizenet": "*",
    "magento/module-google-adwords": "*",
    "magento/module-sample-data": "*",
    "magento/module-send-friend": "*",
    "magento/module-swagger": "*",
    "magento/module-swagger-webapi": "*",
    "magento/module-swagger-webapi-async": "*",
    "magento/module-swatches": "*",
    "magento/module-swatches-layered-navigation": "*",
    "magento/module-google-optimizer": "*",
    "magento/module-ups": "*",
    "magento/module-usps": "*",
    "magento/module-braintree": "*",
    "magento/module-signifyd": "*",
    "magento/module-release-notification": "*",
    "magento/module-amqp": "*",
    "magento/module-message-queue": "*",
    "magento/module-mysql-mq": "*",
    "magento/module-new-relic-reporting": "*",
    "magento/module-version": "*",
    "magento/module-analytics": "*",
    "magento/module-catalog-analytics": "*",
    "magento/module-customer-analytics": "*",
    "magento/module-quote-analytics": "*",
    "magento/module-review-analytics": "*",
    "magento/module-sales-analytics": "*",
    "magento/module-wishlist-analytics": "*",
    "magento/module-bundle-graph-ql": "*",
    "magento/module-catalog-graph-ql": "*",
    "magento/module-catalog-inventory-graph-ql": "*",
    "magento/module-catalog-url-rewrite-graph-ql": "*",
    "magento/module-cms-graph-ql": "*",
    "magento/module-cms-url-rewrite-graph-ql": "*",
    "magento/module-inventory-graph-ql": "*",
    "magento/module-configurable-import-export": "*",
    "magento/module-configurable-product": "*",
    "magento/module-configurable-product-graph-ql": "*",
    "magento/module-configurable-product-sales": "*",
    "magento/module-customer-graph-ql": "*",
    "magento/module-downloadable-graph-ql": "*",
    "magento/module-eav-graph-ql": "*",
    "magento/module-graph-ql": "*",
    "magento/module-grouped-product-graph-ql": "*",
    "magento/module-quote-graph-ql": "*",
    "magento/module-store-graph-ql": "*",
    "magento/module-swatches-graph-ql": "*",
    "magento/module-tax-graph-ql": "*",
    "magento/module-url-rewrite-graph-ql": "*",
    "magento/module-weee-graph-ql": "*",
    "magento/module-advanced-pricing-import-export": "*",
    "magento/module-bundle-import-export": "*",
    "magento/module-bundle": "*",
    "magento/module-downloadable": "*",
    "magento/module-customer-import-export": "*",
    "magento/module-downloadable-import-export": "*",
    "magento/module-grouped-import-export": "*",
    "magento/module-tax-import-export": "*",
    "magento/module-inventory": "*",
    "magento/module-inventory-admin-ui": "*",
    "magento/module-inventory-api": "*",
    "magento/module-inventory-bundle-product": "*",
    "magento/module-inventory-bundle-product-admin-ui": "*",
    "magento/module-inventory-cache": "*",
    "magento/module-inventory-catalog": "*",
    "magento/module-inventory-catalog-admin-ui": "*",
    "magento/module-inventory-catalog-api": "*",
    "magento/module-inventory-catalog-search": "*",
    "magento/module-inventory-configurable-product": "*",
    "magento/module-inventory-configurable-product-admin-ui": "*",
    "magento/module-inventory-configurable-product-indexer": "*",
    "magento/module-inventory-configuration": "*",
    "magento/module-inventory-configuration-api": "*",
    "magento/module-inventory-elasticsearch": "*",
    "magento/module-inventory-grouped-product": "*",
    "magento/module-inventory-grouped-product-admin-ui": "*",
    "magento/module-inventory-grouped-product-indexer": "*",
    "magento/module-inventory-import-export": "*",
    "magento/module-inventory-indexer": "*",
    "magento/module-inventory-low-quantity-notification": "*",
    "magento/module-inventory-low-quantity-notification-admin-ui": "*",
    "magento/module-inventory-low-quantity-notification-api": "*",
    "magento/module-inventory-multi-dimensional-indexer-api": "*",
    "magento/module-inventory-product-alert": "*",
    "magento/module-inventory-reservations": "*",
    "magento/module-inventory-reservations-api": "*",
    "magento/module-inventory-sales": "*",
    "magento/module-inventory-sales-admin-ui": "*",
    "magento/module-inventory-sales-api": "*",
    "magento/module-inventory-sales-frontend-ui": "*",
    "magento/module-inventory-shipping": "*",
    "magento/module-inventory-shipping-admin-ui": "*",
    "magento/module-inventory-source-deduction-api": "*",
    "magento/module-inventory-source-selection": "*",
    "magento/module-inventory-source-selection-api": "*",
    "magento/module-inventory-distance-based-source-selection": "*",
    "temando/module-shipping-m2": "*",
    "dotmailer/dotmailer-magento2-extension": "*",
    "magento/module-grouped-product": "*",
    "klarna/module-kp": "*",
    "klarna/module-ordermanagement": "*",
    "klarna/module-core": "*",
    "amzn/amazon-pay-sdk-php": "*",
    "amzn/amazon-pay-and-login-with-amazon-core-module": "*",
    "amzn/login-with-amazon-module": "*",
    "amzn/amazon-pay-module": "*",
    "vertex/module-tax": "*",
    "vertex/sdk": "*"
  }
```

**Comment by orlangur** [comment] 2019-03-20 16:08
@bordeo please answer my question - is the issue reproduced if you don't touch the bundle module?

**Comment by bordeo** [comment] 2019-03-20 17:09
No it is not reproduced.

**Comment by orlangur** [comment] 2019-03-20 22:55
@bordeo, ok, then there is nothing to fix here - `Magento_Bundle` is not supposed to be removed yet, unlike `Magento_ConfigurableProduct` or `Magento_GroupedProduct`.

**Closed as completed by orlangur** 2019-03-20 22:55 UTC
Labels: Progress: needs update, Issue: Clear Description, Issue: Format is valid, Component: Indexer
