### ISSUE TITLE
Right side border not show in category description block in my screen 1366X768

### ISSUE THREAD

**Issue by renard123** [magento/magento2#27573] opened 2020-04-04 12:08 UTC
Right side border not display in category description block in my screen 1366
 
### Preconditions (*)
Chrome: Version 80.0.3987.163 (Official Build) (32-bit)
OS: Windows 7
Screen Resolution: 1366 X 768
Magento 2.3.4

### Steps to reproduce (*)
Admin > Category > Edit any
Review the Description box

### Expected result (*)
It should show appropriate

### Actual result (*)
![image](https://user-images.githubusercontent.com/50658701/78450208-9c725080-769a-11ea-8426-8127602cf37a.png)

**Comment by krishprakash** [comment] 2020-04-04 12:10
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-04 12:10
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-04 12:11
Hi @krishprakash, here is your [Magento instance](https://i-27573-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27573-2-4-develop.instances.magento-community.engineering/admin_df4d](https://i-27573-2-4-develop.instances.magento-community.engineering/admin_df4d)
Login: `808caee6` Password: `a98f81b17c51`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2020-04-04 12:19
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33091` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krishprakash** [comment] 2020-04-04 12:19
Hi @renard123. Looks fine in my screen view but when I update the screen resolution with 1366 Yes seems border not showing so approve this as It should display proper in all screen resolution
Thanks !!

**Comment by sdzhepa** [comment] 2020-04-04 12:24
Hello @renard123 and @renard123 

Could you please provide an exact screen resolution in to the issue description?

![2020-04-04_7-22-19](https://user-images.githubusercontent.com/3409584/78450578-43c49880-7645-11ea-8958-b265541682bf.png)

**Comment by renard123** [comment] 2020-04-04 12:30
@sdzhepa Sure.
Chrome: Version 80.0.3987.163 (Official Build) (32-bit)
OS: Windows 7
Screen Resolution: 1366 X 768

**Comment by sdzhepa** [comment] 2020-07-27 19:58
Checked on the latest `2.4-develop`

![2020-07-27_14-56-57](https://user-images.githubusercontent.com/3409584/88586144-a3dab280-d019-11ea-89b1-16f3c006bc80.jpg)

**Comment by sdzhepa** [comment] 2020-07-30 19:58
Hello @renard123 

The issue has been reviewed and discussed during regular triage meeting with Product Managers.
Due to  
- is not a functional issue - it does not break any functionality
- It is just cosmetic correction 
- Magento officially does not support full mobile/tablet experience working with Admin Panel: https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements_browsers.html

was decided to close this issue, as a very low priority

**Closed as completed by sdzhepa** 2020-07-30 19:58 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Backend, Reproduced on 2.4.x, Event: Global-Contribution-Day, Triage: Ready for Triage, Reported on 2.3.4
