### ISSUE TITLE
Cart items with custom options always out of stock in PWA (GraphQl)

### ISSUE THREAD

**Issue by HalievDmitry** [magento/magento2#39065] opened 2024-08-19 21:32 UTC
### Preconditions and environment

- Magento version 2.4.7-p2
- GraphQl

### Steps to reproduce

1. create a new product with required custom option (any type) with 100 qty in stock.
2. add this product with the selected custom option to the cart (just 1 item)
3. go to cart page

### Expected result

Cart item is in stock, you can adjust the qty and proceed to checkout.

### Actual result

Cart item is out of stock and you need to remove it from your cart.

### Additional information

In `vendor/magento/module-inventory-graph-ql/Model/Resolver/StockStatusProvider.php:58` the `$product->getSku()` result passed to `AreProductsSalableInterface`. But the `getSku()` returns a combined cart item SKU (product sku + custom option sku, ex. **product1-customoption1**) instead of raw product SKU (ex. **product1**). Obviously we don't have a stock records for such combined SKUs.
Looks like `$product->getData('sku')` might be used here.
As a temporary fix I put a before plugin on `AreProductsSalableInterface` to "clear" the SKUs and avoid the similar bugs.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2024-09-02 11:07
Hi @HalievDmitry ,

Thanks for your reporting and collaboration.
We have verified the issue in latest 2.4-develop instance and issue is not reproducible . Kindly refer the screenshots.

**Steps to Reproduce :**

1. Install latest 2.4-develop instance.
2. create a new product with required custom option (any type) with 100 qty in stock.
3. add this product with the selected custom option to the cart (just 1 item)
![image](https://github.com/user-attachments/assets/780db281-d1b7-4e02-8391-59fad9374bf7)
4. go to cart page
![image](https://github.com/user-attachments/assets/715fbd6a-dbcb-428d-8309-214d27a6744f)
5. Update the Qty - 
![image](https://github.com/user-attachments/assets/b0814e43-4671-4360-908f-a52d073ec39f)
![image](https://github.com/user-attachments/assets/dc79c3b3-5210-474d-af96-1cb7dce09790)
Observe user is able to update the Qty
Please let us know if any other steps are needed to be performed.

Thanks.

**Comment by engcom-Delta** [comment] 2024-09-30 08:44
Hi @HalievDmitry ,

We have noticed that this issue has not been updated since long time.
Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Delta** 2024-09-30 08:44 UTC
Labels: Component: GraphQL, Issue: needs update, Area: Catalog, Reported on 2.4.7-p2
