### ISSUE TITLE
Unable to find extension attribute in Get Shipment API

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#38294] opened 2023-12-18 05:52 UTC
### Preconditions and environment

- Magento version - 2

### Steps to reproduce

-> Call Get Shipment api for Particular Order 
ex : http://php72.webgility.com/magento230_test/rest/V1/shipments?searchCriteria[filter_groups][0][filters][0][field]=order_id&searchCriteria[filter_groups][0][filters][0][value]=374

### Expected result

The API response should have "extension_attributes" node which contain "source_code" info.

### Actual result

The API does not have "extension_attributes" node which contain "source_code" info.
`{
    "items": [
        {
            "billing_address_id": 739,
            "created_at": "2023-12-15 12:06:33",
            "customer_id": 51,
            "email_sent": 1,
            "entity_id": 389,
            "increment_id": "000000350",
            "order_id": 374,
            "packages": "[]",
            "shipping_address_id": 738,
            "store_id": 1,
            "total_qty": 2,
            "updated_at": "2023-12-15 12:06:35",
            "items": [
                {
                    "entity_id": 312,
                    "name": "Levis_Boxers_Crepe_23",
                    "parent_id": 389,
                    "price": 2555,
                    "product_id": 1293,
                    "sku": "SKU_Levis_Boxers_Crepe_23",
                    "weight": 23,
                    "order_item_id": 462,
                    "qty": 2
                }
            ],
            "tracks": [
                {
                    "order_id": 374,
                    "created_at": "2023-12-15 12:06:33",
                    "entity_id": 186,
                    "parent_id": 389,
                    "updated_at": "2023-12-15 12:06:33",
                    "weight": null,
                    "qty": null,
                    "description": null,
                    "track_number": "Track370_0",
                    "title": "Magento2",
                    "carrier_code": "ups"
                }
            ],
            "comments": [
                {
                    "is_customer_notified": 1,
                    "parent_id": 389,
                    "comment": "369 item got shipped 1",
                    "is_visible_on_front": 1,
                    "created_at": "2023-12-15 12:06:33",
                    "entity_id": 189
                }
            ]
        },
        {
            "billing_address_id": 739,
            "created_at": "2023-12-15 12:06:37",
            "customer_id": 51,
            "email_sent": 1,
            "entity_id": 390,
            "increment_id": "000000351",
            "order_id": 374,
            "packages": "[]",
            "shipping_address_id": 738,
            "store_id": 1,
            "total_qty": 1,
            "updated_at": "2023-12-15 12:06:38",
            "items": [
                {
                    "entity_id": 313,
                    "name": "Levis_Boxers_Crepe_24",
                    "parent_id": 390,
                    "price": 256,
                    "product_id": 1294,
                    "sku": "SKU_Levis_Boxers_Crepe_24",
                    "weight": 5,
                    "order_item_id": 463,
                    "qty": 1
                }
            ],
            "tracks": [
                {
                    "order_id": 374,
                    "created_at": "2023-12-15 12:06:37",
                    "entity_id": 187,
                    "parent_id": 390,
                    "updated_at": "2023-12-15 12:06:37",
                    "weight": null,
                    "qty": null,
                    "description": null,
                    "track_number": "Track370_1",
                    "title": "Magento2",
                    "carrier_code": "fedex"
                }
            ],
            "comments": [
                {
                    "is_customer_notified": 1,
                    "parent_id": 390,
                    "comment": "369 item got shipped 2",
                    "is_visible_on_front": 1,
                    "created_at": "2023-12-15 12:06:37",
                    "entity_id": 190
                }
            ]
        }
    ],
    "search_criteria": {
        "filter_groups": [
            {
                "filters": [
                    {
                        "field": "order_id",
                        "value": "374",
                        "condition_type": "eq"
                    }
                ]
            }
        ]
    },
    "total_count": 2
}`

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-12-19 05:34
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-12-19 07:44
Hi @webgility-amazonapi,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

-> Call Get Shipment api for Particular Order


![https-ecd0794a97b04a4a70659e47f7e55789-instances-prod-magento-community-engineering-rest-V1-shipments-searchCriteria-filter_groups-0-filters-0-field-order_id-searchCriteria-filter_groups-0-filters-0-value-000000004-My-Workspace](https://github.com/magento/magento2/assets/51680745/1934e67c-60a7-4241-bd9b-5ad87e4f2e90)


The API response should having "extension_attributes" node which contain "source_code" info.


Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-01-02 05:51
Hi @webgility-amazonapi,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38294#issuecomment-1862268824 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-01-05 05:10
Hi @webgility-amazonapi,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-01-05 05:09 UTC
Labels: Issue: needs update, Reported on 2.4.x
