### ISSUE TITLE
Why https://www.magento.com redirect to https://business.adobe.com

### ISSUE THREAD

**Issue by vrkansagara** [magento/magento2#34834] opened 2021-12-17 07:54 UTC
issue :- **Why https://www.magento.com redirect to https://business.adobe.com**

Any strategic decision behind **Magento Open source** ? or Someone is playing !

**Comment by engcom-Hotel** [comment] 2021-12-17 09:56
Hello @vrkansagara,

The issue is not related with core Magento functionality. This board is using for collecting the issues occurs in Magento code modules. So we are closing this issue.

Thanks

**Closed as completed by engcom-Hotel** 2021-12-17 09:56 UTC
Labels: Issue: ready for confirmation

**Comment by vrkansagara** [comment] 2021-12-17 10:32
@engcom-Hotel Can you tell me the right place for raising this issue ?

**Comment by vrkansagara** [comment] 2021-12-17 10:33
Ping @m2-community-project re-open this issue.
