### ISSUE TITLE
Purchasing a downloadable product as guest then creating an account on the onepagesuccess step doesn't link product with account

### ISSUE THREAD

**Issue by crankycyclops** [magento/magento2#21702] opened 2019-03-12 04:46 UTC
Preconditions
Magento 2.2.7
PHP 7.1

Steps to reproduce

1. Enable guest purchasing of downloadable products (Catalog -> Catalog -> Dowloadable Product Options -> Disable Guest Checkout if Cart Contains Downloadable Items -> (Change it to NO))
2. Purchase a downloadable product via guest checkout
3. On the onepagesuccess step, create an account.
4. Login to that newly created account and view the list of purchased downloadable products

Expected result
New downloadable products should show up in my downloadable products section after using guest checkout and creating an account.

Actual result
The downloadable product does not show up in my downloadable products.

**Comment by magento-engcom-team** [comment] 2019-03-12 04:46
Hi @crankycyclops. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@crankycyclops do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by crankycyclops** [comment] 2019-03-12 04:47
This also appears to have been reported here (https://github.com/magento/magento2/issues/18441), but was later mysteriously closed by the person who opened the ticket.

**Comment by abdelkebir** [comment] 2019-03-12 06:31
Just to remember, by default Magento 2.3.0 will not allow users to order a downloadable product as guests unless you have changed that behavior from Magento admin panel under:

> Catalog -> Catalog -> Dowloadable Product Options -> Disable Guest Checkout if Cart Contains Downloadable Items  -> (Change it to NO)

I think you just need to include that to the reproduction steps.

**Comment by crankycyclops** [comment] 2019-03-12 06:37
> Just to remember, by default Magento 2.3.0 will not allow users to order a downloadable product as guests unless you have changed that behavior from Magento admin panel under:
> 
> > Catalog -> Catalog -> Dowloadable Product Options -> Disable Guest Checkout if Cart Contains Downloadable Items  -> (Change it to NO)
> 
> I think you just need to include that to the reproduction steps.

@abdelkebir, Good point. I just edited the steps to reproduce.

**Comment by magento-engcom-team** [comment] 2019-03-12 08:48
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-03-12 09:12
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98655`, `MAGETWO-98656` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by crankycyclops** [comment] 2019-03-12 22:42
I've just tested @Jitheesh's commit on my own Magento instance (2.2.7) and can confirm it's working. Hopefully this means the fix can be integrated into both 2.2 and 2.3.

**Comment by magento-engcom-team** [comment] 2019-04-23 12:25
Hi @crankycyclops. Thank you for your report. 
The issue has been fixed in magento/magento2#21711 by @Jitheesh in 2.3-develop branch
Related commit(s):
 - [fc1434b3465a855cb952aae8b63cc886d6c1cce0](https://github.com/magento/magento2/commit/fc1434b3465a855cb952aae8b63cc886d6c1cce0)
 - [8652bc88614875920ecb506c45dff777b2069701](https://github.com/magento/magento2/commit/8652bc88614875920ecb506c45dff777b2069701)
 - [95b1d531ae65d8976b852504e4c9fdc7ea6e97bb](https://github.com/magento/magento2/commit/95b1d531ae65d8976b852504e4c9fdc7ea6e97bb)
 - [0ade930796f0857030823dcce9c2bcb4a1a483bd](https://github.com/magento/magento2/commit/0ade930796f0857030823dcce9c2bcb4a1a483bd)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-04-23 12:25 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Downloadable
