### ISSUE TITLE
Invalid input datetime format of value '20‏/5‏/2009'

### ISSUE THREAD

**Issue by mpyasser** [magento/magento2#10773] opened 2017-09-05 10:48 UTC
When trying to edit or add products I get the above error message on that product page when I click Save changes. These errors happen when change page admin language Arabic AS and when back to English US it works.

### Preconditions:

1. Magento CE 2.1.8
2. PHP 7.0.22-0ubuntu0.16.04.1 (cli) (NTS)
3. Zend OPcache v7.0.22
4. Apache/2.4.18 (Ubuntu)
5. mysql 5.7.19
6. Ubuntu 16.04.1-x86_64 

### Steps to reproduce:

1. Accounting setting 
2. Choose language العربية المملكه العربيه السعودية
3. Save
4. Open back office on store
5. Open a product or add a new product
6. All stores view then choose Arabic
7. Click to save changes

### Expected result:

Product should save

### Actual result:

Error as subject line on product page = ' invalid input datetime format of value '52017/09''

http://prntscr.com/ghb50c
http://prntscr.com/ghb7g6

**Comment by TomashKhamlai** [comment] 2017-09-05 15:19
Duplicate of #10756

**Closed as completed by TomashKhamlai** 2017-09-05 15:19 UTC
Labels: bug report, duplicate
