### ISSUE TITLE
Help Center Widget

### ISSUE THREAD

**Issue by intheshallow** [magento/magento2#37627] opened 2023-06-16 17:35 UTC
### Preconditions and environment

- Magento version: 2.4.6

Ever since I noticed your help center widget, I can no longer edit Catalog - Categories. I am getting a constant loading animation. This is also happening on CMS - Blocks and CMS - Pages. At least those I can get working after a couple of refreshes, but still. I am noticing the same thing on several other sites I have as well. Is there a way to stop this thing? It's useless to me as it is.

### Steps to reproduce

1. Login to Admin
2. Try to navigate almost any page.
3. Watch a loading animation and nothing else.

### Expected result

The admin page should not get stuck in a constant loading animation.

### Actual result

![magento-issue-4](https://github.com/magento/magento2/assets/4449132/8cb027a7-9c8d-4213-b306-f824c48a42ab)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-06-16 17:57
@magento give me 2.4.6 instance

**Comment by deveshvarsani** [comment] 2023-06-17 07:33
Good Morning, We are experiencing the same issue whereby catagories can not be edited or created and the page just hangs. This all started when the help centre widget appeared, is there any inclination when a fixed will be released and how it can be applied?

**Comment by FrancescNS** [comment] 2023-06-17 07:37
Good morning, We are having the same issue in our admin, in any page, since the Help Center appeared. No buttons or links respond  at first click except the help center icon.  If you refresh the page it responds, but it is very annoying and inefficient.
Is there any way to disable or block it in the meantime? thanks!

**Comment by AmooAti** [comment] 2023-06-17 09:14
Good time, Since yesterday, we've been experiencing issues with clickable items like menus, etc. Also, pages are loading slowly.
Is there any way to disable it?

**Comment by fredden** [comment] 2023-06-17 11:26
This looks like a duplicate of https://github.com/magento/magento2/issues/37618. There are some suggestions for how to turn the module (or its functionality) off in that issue.

**Comment by deveshvarsani** [comment] 2023-06-17 11:52
Thanks mate, disabled and it's resolved the issue. Thanks mate

**Comment by Ahmet-Djedovic** [comment] 2023-06-17 14:41
It looks like the admin session size becomes too big when the help widget is there. Resulting in that you cant press anything, or that menus/dropdown dont load fully. 
For removing the help widget: @fredden his answer.

**Comment by engcom-Dash** [comment] 2023-06-19 09:42
Hi @intheshallow ,

This issue looks like Duplicate of [37618](https://github.com/magento/magento2/issues/37618)

Hence we are closing the issue.

**Closed as completed by engcom-Dash** 2023-06-19 09:42 UTC
Labels: duplicate, Issue: ready for confirmation, Reported on 2.4.6
