### ISSUE TITLE
Request does not match any route:

### ISSUE THREAD

**Issue by OlaviSau** [magento/magento2#4242] opened 2016-04-20 14:12 UTC
## Steps to reproduce

Exact:
1) Create an interface which uses `\Magento\Checkout\Api\PaymentInformationManagementInterface` in its methods(dependency injects it into the controller)
2) Call the method that uses `\Magento\Checkout\Api\PaymentInformationManagementInterface` 
## Expected result

After that if the checkout is used(or any checkout related api call)  it will error with `Request does not match any route`, ONCE
## Actual result

After that if the checkout is used(or any checkout related api call)  it will NOT error with `Request does not match any route`

I also checked if the routes themselves had anything to do with that, but changing the methodnames/path does not have an effect. Also deleting the generation folder + cache fixes the issue.

**Comment by aymone** [comment] 2016-05-06 12:54
+1 nginx, php7.0-fpm

**Comment by piotrekkaminski** [comment] 2016-05-24 01:01
@antonkril can you take a look?

**Comment by antonkril** [comment] 2016-05-24 15:18
Probably the issue is with changed constructor signature, but anyway proper error message should be reported.

**Comment by dkvashninbay** [comment] 2016-05-24 15:34
@OlaviSau If I understand you correctly, you've created interface and implementation for webApi, and added/modified existing webapi.xml routes.
If so, cache should be flushed on any change to webapi.xml, as webApi routes are computed once and are stored in cache.

**Comment by vipin-eglobeits** [comment] 2016-07-06 08:21
After I upgraded the site to Magento 2.1, sometimes when we select the shipping method I'm getting the error : **Request does not match any route** 
I also found a link with 404 page in the console area.

**Comment by vipin-eglobeits** [comment] 2016-07-12 08:22
Please refer the above issue in detail:
[https://github.com/magento/magento2/issues/5542](https://github.com/magento/magento2/issues/5542)

**Comment by vipin-eglobeits** [comment] 2016-07-13 12:44
Hi @dkvashninbay,
Could you please take a look at the issue #5542.

**Comment by veloraven** [comment] 2016-08-30 14:45
@OlaviSau is this issue still actual?
If it is please specify Magento version.  If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.
If it is not please close this issue.

**Comment by veloraven** [comment] 2016-09-27 12:37
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Closed as completed by veloraven** 2016-09-27 12:37 UTC
Labels: Progress: needs update
