### ISSUE TITLE
Magento_Tax "postcode is a required field" when upgrading from 2.1.9 to 2.2

### ISSUE THREAD

**Issue by friimaind** [magento/magento2#11095] opened 2017-09-27 14:45 UTC
### Preconditions
Magento 2.1.9 CE
PHP 7.0.22-0ubuntu0.17.04.1
MySQL 5.7.19-0ubuntu0.17.04.1

### Steps to reproduce
Upgrade Magento 2.1.9 to 2.2 CE with composer

> composer require magento/product-community-edition 2.2 --no-update
> composer update
> php -f bin/magento setup:upgrade

### Expected result
Magento 2.2 updated

### Actual result
php -f bin/magento setup:upgrade returns:

> ...
> Module 'Magento_Swatches':
> Module 'Magento_SwatchesLayeredNavigation':
> Module 'Magento_Tax':
> Upgrading data.. postcode is a required field.

**Comment by magento-engcom-team** [comment] 2017-09-28 14:30
@friimaind, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by rmendoza3** [comment] 2017-09-28 16:38
I am having the same issue. I am also trying to upgrade from 2.1.9 to 2.2.0. I run into a "postcode is a required field." error and the setup:upgrade dies. If I find anything out I will be sure to update it here.

**Comment by kervin** [comment] 2017-09-29 08:01
Same issue. @magento-engcom-team, create a tax rule without postcode first, then setup:upgrade.. seems obvious.

Test properly before saying "Can not reproduce"!

**Comment by JoostWan** [comment] 2017-09-29 22:11
Same issue here. To fix this check the table **tax_calculation_rate**. When the field tax_postcode is empty enter a * 

Then the upgrade will work.

**Comment by friimaind** [comment] 2017-10-02 10:14
Thanks @JoostWan , according to my database this query fixed the issue:

> UPDATE tax_calculation_rate SET tax_postcode = '*' WHERE tax_postcode IS NULL

**Comment by jwohlfeil** [comment] 2017-10-09 08:08
Same Problem here, JoostWan's and friimaind's tipps fixed it.

**Comment by lewisvoncken** [comment] 2017-10-20 14:01
@magento-engcom-team 
I can reproduce the issue and it is only when you have existing rules with tax_postcode NULL. Maybe I will provide a fix for this issue.

**Comment by lewisvoncken** [comment] 2017-10-23 16:57
@friimaind  I supplied a pull request for this issue.

**Comment by lewisvoncken** [comment] 2017-10-23 17:01
I'm working on it #SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment] 2017-10-27 14:22
@friimaind, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by orlangur** [comment] 2017-10-27 14:59
@magento-engcom-team did you try steps from https://github.com/magento/magento2/pull/11735? So basically you need to set `null` manually to mentioned field in database to recreate circumstances of bug report.

**Comment by orlangur** [comment] 2017-10-27 15:01
@lewisvoncken I don't see this issue was ever eligible for #SQUASHTOBERFEST

**Comment by TomashKhamlai** [comment] 2017-10-30 08:47
Reproduced

**Comment by lewisvoncken** [comment] 2017-10-30 08:50
@TomashKhamlai I also could reproduce and I have provided a fix in pull request #11735

**Comment by magento-team** [comment] 2017-10-31 21:08
Internal ticket to track issue progress: MAGETWO-82595

**Comment by okorshenko** [comment] 2017-11-01 02:57
The issue has been fixed and delivered to 2.2-develop branch. Will be available in 2.2.2 release

**Closed as completed by okorshenko** 2017-11-01 02:57 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid

**Comment by magento-engcom-team** [comment] 2017-11-22 08:30
@friimaind, thank you for your report.
The issue is already fixed in 2.2.2
