### ISSUE TITLE
Street fields in checkout don't have a label that's readable by a screenreader

### ISSUE THREAD

**Issue by TomFranssen** [magento/magento2#10893] opened 2017-09-15 07:28 UTC
### Preconditions
1. Standard Magento ver. 2.1.7 installation 

### Steps to reproduce
1. Add a product to your cart
2. Go to checkout

### Expected result

1. The labels should have a valid `<label>` element that is linked to the `<input>` field with a `for` attribute. My advice is to add linked <label> elements to all the address line fields so that screen readers can know what kind of fields the address fields are and thus increasing accessibility.
### Actual result
 The address lines input fields don't have a `<label>` element with a valid value. There is a `<span>` infront of it with the text 'Address'. This text however doesn't get recognised by screen readers.

If I test this on the default MAC screenreader (activated by CMD + F5) I get the feedback of: 'edit text blank'. In this situation the visually impaired user doesn't get feedback on what type of field it is.

**Comment by PieterCappelle** [comment] 2017-09-26 09:56
I'm working on it.

**Comment by patrikpihlstrom** [comment] 2017-10-06 06:41
I can take a look at this later today if nobody else has claimed it.

**Comment by mzeis** [comment] 2017-10-07 11:32
@patrikpihlstrom Looks like the issue is yours!
[Update] Sorry, can't assign you to the issue, your name is not available in the selection.

**Comment by okorshenko** [comment] 2017-10-09 16:19
Hi @patrikpihlstrom could you please accept the invitation on GitHub?

**Comment by bluemwhitew** [comment] 2017-10-11 17:00
Possibly related to #7428?

**Comment by magento-engcom-team** [comment] 2019-02-26 16:52
Hi @scottsb. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by scottsb** [comment] 2019-02-26 16:54
@patrikpihlstrom Since this hasn't been touched in two years, I'm assuming you didn't reach a solution. 😆Taking this to work on.

**Comment by patrikpihlstrom** [comment] 2019-02-27 09:25
@scottsb Go nuts!

**Comment by magento-engcom-team** [comment] 2019-03-30 21:00
Hi @TomFranssen. Thank you for your report. 
The issue has been fixed in magento/magento2#21484 by @scottsb in 2.3-develop branch
Related commit(s):
 - [e1fa2898da686fcad88d0478f0f7e610cc0c6ce6](https://github.com/magento/magento2/commit/e1fa2898da686fcad88d0478f0f7e610cc0c6ce6)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-30 21:00 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by magento-engcom-team** [comment] 2019-04-09 20:40
Hi @TomFranssen. Thank you for your report. 
The issue has been fixed in magento/magento2#22070 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [3e37244e8d1c6c529cfa5132b848b01fab6faf91](https://github.com/magento/magento2/commit/3e37244e8d1c6c529cfa5132b848b01fab6faf91)

The fix will be available with the upcoming 2.2.9 release.
