### ISSUE TITLE
Tax calculation in multistore environment

### ISSUE THREAD

**Issue by FreekVandeursen** [magento/magento2#23552] opened 2019-07-03 08:58 UTC
### Preconditions (*)
1. Magento >= 2.2.5

### Steps to reproduce (*)
1. Create store view store_2
2. Set Sales -> Tax -> Calculation settings -> Catalog Prices to "Including tax"
3. Set Sales -> Tax -> Price display settings -> Display product prices in catalog to "Including tax"
4. Create tax rules so that store_2 has different tax percentage than default store, e.g. 21% for default store and 19% for store_2
5. Create a product in backend with price 10
6. Visit the product in store_2

### Expected result (*)
1. Product price is 9.83 ( = 10 / 1.21 * 1.19)

### Actual result (*)
1. Product price is 10

### Analysis
This behavior seems to occur since a performance improvement in version 2.2.5 (see https://github.com/magento/magento2/issues/14941).

**Comment by FreekVandeursen** [comment] 2019-07-03 09:00
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-03 09:00
Hi @FreekVandeursen. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-03 09:01
Hi @FreekVandeursen, here is your [Magento instance](https://i-23552-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23552-2-3-develop.instances.magento-community.engineering/admin](https://i-23552-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-07-03 09:14
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17927` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Charlie** [comment] 2021-01-29 10:16
Hello @FreekVandeursen could you please clarify Step 4?
`Create tax rules so that store_2 has different tax percentage than default store, e.g. 21% for default store and 19% for store_2`
Thank you.

**Comment by sdzhepa** [comment] 2021-02-03 19:36
Hello @FreekVandeursen 
cc: @engcom-Charlie 

Could you please provide more information about https://github.com/magento/magento2/issues/23552#issuecomment-769714538 and update issue description?

At this moment we are not able to reproduce and confirm this issue. 
Without this information the issue cannot be processed and will be closed

**Comment by engcom-Charlie** [comment] 2021-02-15 08:59
Hello, @FreekVandeursen we are closing this issue due to inactivity.

Please feel free to comment, reopen or create a new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for your collaboration.

Thanks for your report!

**Comment by magento-engcom-team** [comment] 2021-02-15 09:00
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Charlie** 2021-02-15 08:59 UTC
Labels: Component: Tax, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue:  Cannot Reproduce, Priority: P2, Severity: S2, Progress: done, Issue: needs update
