### ISSUE TITLE
UpdateCouponUsages change. Why are you doing this?

### ISSUE THREAD

**Issue by chequille** [magento/magento2#31382] opened 2020-12-21 23:50 UTC
I know, that this is maybe not a bug, but in my point of view it is. Therefore, I am writting it here.
By the way, I am working with Magento 2.4.1

Because Magento does not care about a coupon code for let's say 50€ if the total cart value is only 30€ (Magento is reducing the total but is setting the coupon as used and the 20€ left are gone !!!!), I developed a module which checks the discountamount used for the order and does set the rest as new value for the coupon code. Of course the coupon code is set as well as not used, but now only for the rest of 20€. I made as well some entries in the OrderHistory (addCommentToStatusHistory) to let the customer know of the rest of the coupon code.
Everything worked perfectly in 2.3.5, but now, somebody thought there must be a change (do not know why???) and the UpdateCouponUsage is now working on the quote and not on the order and therefore, nothing is working anymore. There are two UpdateCouponUsage classes, one in Magento_SalesRules\Model\Coupon and one in Magento_SalesRules\Model\Coupon\Quote. The first one still uses in the execute function the order as subject as it was in 2.3.5, but the second one is using CartInterface quote.  WHY???????
And second question when is the first class used?

As a matter of facts, in the quote object, I cannot add a commentToStatusHistory, because this function is not available here.
Maybe I am wrong but if yes, let me know how to do it!
Finally, currently it lokks like I have to completly re-develop my module, but still not knowing whether everthing I did can be done on the quote.

What I really want to know (my last question for the moment) is the usage of these two UpdateCouponUsages classes and why there was this change?

Looking forward to hearing from you.

Regards,
Chequille

**Comment by dverkade** [comment] 2021-03-17 15:35
Ready for confirmation issues can't be closed automatically.

**Comment by engcom-Lima** [comment] 2021-09-10 05:43
Hi @chequille,

Since this issue was reported long back. I just wanted to check if your issue is resolved ?

If not, please update your description with more detailed following points:
1. Steps to reproduce.
2. Expected and Actual Results.

Also, please refer the below documentation having all info about Coupon Codes and update accordingly:
https://docs.magento.com/user-guide/marketing/price-rules-cart-coupon.html

**Comment by engcom-Lima** [comment] 2021-09-24 04:25
Hi @chequille,

We have noticed that this issue has not been updated for some time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Lima** 2021-09-24 04:25 UTC
Labels: Triage: Dev.Experience, Issue: needs update
