### ISSUE TITLE
Same product listed as separate items in shopping cart when added from grouped product page.

### ISSUE THREAD

**Issue by Hailong** [magento/magento2#24143] opened 2019-08-15 18:00 UTC
### Preconditions (*)

1. Magento 2.3.2

### Steps to reproduce (*)

1. Create a single test product.
2. Create a grouped product and add the previous single product as a sub product.
3. Go to the single product page, and add one product to the shopping cart.
4. Go to the grouped product page, and add one sub product to the shopping cart.
5. Check the shopping cart.

### Expected result (*)

1. The single product is listed in one line and with quantity value as two.

### Actual result (*)

1. The same single product is added as two separate items.

**Comment by magento-engcom-team** [comment] 2019-08-16 07:16
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19308` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sudheers-kensium** [comment] 2019-08-19 13:42
Hi @Hailong , 

This is Magento default behaviour not an issue.

When we add a product from grouped product parent id(grouped product id) and product type will save in quote_item_option table and from simple product view page parent id not exists in quote_item_option so due to this same single product is added as two separate items.

![image](https://user-images.githubusercontent.com/50358141/63270184-4b515000-c2b5-11e9-8031-6e3b6c012871.png)
![image](https://user-images.githubusercontent.com/50358141/63270191-4ee4d700-c2b5-11e9-936b-c3e218a676ca.png)

**Comment by Hailong** [comment] 2019-08-19 15:58
Hi @sudheers-kensium , thank you for digging out the details in code and db. While I still think if the customers can't tell any difference from the itemized list in the order, they would be confused.

My client (the site owner) reported it as an issue to me, since they think that's a problem in Magento. I have just added a plugin to change the default behaviour, but I'd prefer the team could review this behaviour, or we could add an option in the grouped product editing page.

Paste my plugin code snippet below for information:

```
    <type name="Magento\Quote\Model\Quote\Item">
        <plugin name="website_sitesettings_quote_item_plugin" type="WebSite\SiteSettings\Plugin\QuoteItem" sortOrder="1"/>
    </type>
```
```
<?php

namespace WebSite\SiteSettings\Plugin;

use Magento\Quote\Model\Quote\Item;

/**
 * QuoteItem
 */
class QuoteItem
{
    public function beforeCompareOptions(Item $item, $options1, $options2)
    {
        if (isset($options1['product_type'])) {
            unset($options1['product_type']);
        }

        if (isset($options2['product_type'])) {
            unset($options2['product_type']);
        }

        return [$options1, $options2];
    }
}

```

**Comment by engcom-Bravo** [comment] 2019-08-20 13:52
@sudheers-kensium, please take a look at the next image:
![context](https://user-images.githubusercontent.com/51680745/63352027-01c23d00-c369-11e9-92d4-561a685eb0fb.png)
There are three units of Conf-Red product in the cart shown as thee different items, they occupy three separate positions in the Cart. But each time this Conf-Red was added to the Cart with so to say  different context: as a Simple Product, as a Bundle Product and as a Configurable product. And from this point of view separate positions make sense. But the Grouped Product is added to the Cart only as separate other products it consists of. And so it's not correct when the customer sees totally the same product, having the same context in our terms and with that occupying separate positions in the Cart.

**Comment by sdzhepa** [comment] 2019-10-07 21:26
Hello @Hailong 
FYI: @engcom-Bravo @sudheers-kensium 

Thank you for contribution and collaboration!

This issue was investigated and discussed with Magento product manager and architect.
Were agreed with comments https://github.com/magento/magento2/issues/24143#issuecomment-522581292 and https://github.com/magento/magento2/issues/24143#issuecomment-523025006

It is expected(by design) behavior and Magento does not want to change it in the core code at this moment

**Closed as completed by sdzhepa** 2019-10-07 21:26 UTC
Labels: Issue: Ready for Work, Progress: needs update, Component: Catalog, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: GroupedProduct
