### ISSUE TITLE
Error in Magento 2.4.4 After Installed on Windows 10

### ISSUE THREAD

**Issue by marcelovillalta0** [magento/magento2#35474] opened 2022-05-13 19:11 UTC
Preconditions (*)
Magento 2.4.4
Php 8.1
Local Server XAMPP 

Steps to reproduce (*)
Download & install Magento 2.4.4 

Information (*)
When I want to enter the page for the first time, I get the 404 error.

![image](https://user-images.githubusercontent.com/99217156/168373677-e89b6186-f1f6-4eda-955f-beffe11152cb.png)

After trying some solutions provided by different internet forums I found this error:

`Error: Undefined constant "Magento\Framework\Encryption\Adapter\SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_IETF_NPUBBYTES" in C:\xampp_v1\htdocs\mitienda\vendor\magento\framework\Encryption\Adapter\SodiumChachaIetf.php:40
Stack trace:
#0 C:\xampp_v1\htdocs\mitienda\vendor\magento\framework\Encryption\Encryptor.php(399): Magento\Framework\Encryption\Adapter\SodiumChachaIetf->encrypt('a:3:{s:7:"defau...')
#1 C:\xampp_v1\htdocs\mitienda\vendor\magento\module-config\App\Config\Type\System.php(339): Magento\Framework\Encryption\Encryptor->encryptWithFastestAvailableAlgorithm('a:3:{s:7:"defau...')
#2 C:\xampp_v1\htdocs\mitienda\vendor\magento\framework\Cache\LockGuardedCacheLoader.php(137): Magento\Config\App\Config\Type\System->cacheData(Array)
#3 C:\xampp_v1\htdocs\mitienda\vendor\magento\module-config\App\Config\Type\System.php(281): Magento\Framework\Cache\LockGuardedCacheLoader->lockedLoadData('SYSTEM_CONFIG', Object(Closure), Object(Closure), Object(Closure))
#4 C:\xampp_v1\htdocs\mitienda\vendor\magento\module-config\App\Config\Type\System.php(207): Magento\Config\App\Config\Type\System->loadDefaultScopeData('default')
#5 C:\xampp_v1\htdocs\mitienda\vendor\magento\module-config\App\Config\Type\System.php(181): Magento\Config\App\Config\Type\System->getWithParts('default/admin/u...')
#6 C:\xampp_v1\htdocs\mitienda\vendor\magento\framework\App\Config.php(132): Magento\Config\App\Config\Type\System->get('default/admin/u...')
#7 C:\xampp_v1\htdocs\mitienda\vendor\magento\module-backend\App\Config.php(51): Magento\Framework\App\Config->get('system', 'default/admin/u...')
#8 C:\xampp_v1\htdocs\mitienda\vendor\magento\module-backend\App\Area\FrontNameResolver.php(109): Magento\Backend\App\Config->getValue('admin/url/use_c...')
#9 C:\xampp_v1\htdocs\mitienda\vendor\magento\module-backend\Helper\Data.php(209): Magento\Backend\App\Area\FrontNameResolver->getFrontName(false)
#10 C:\xampp_v1\htdocs\mitienda\vendor\magento\module-backend\App\Request\PathInfoProcessor.php(50): Magento\Backend\Helper\Data->getAreaFrontName()
#11 C:\xampp_v1\htdocs\mitienda\generated\code\Magento\Backend\App\Request\PathInfoProcessor\Proxy.php(95): Magento\Backend\App\Request\PathInfoProcessor->process(Object(Magento\Framework\App\Request\Http), '/')
#12 C:\xampp_v1\htdocs\mitienda\vendor\magento\framework\App\Request\Http.php(148): Magento\Backend\App\Request\PathInfoProcessor\Proxy->process(Object(Magento\Framework\App\Request\Http), '/')
#13 C:\xampp_v1\htdocs\mitienda\vendor\magento\framework\App\Request\Http.php(163): Magento\Framework\App\Request\Http->getOriginalPathInfo()
#14 C:\xampp_v1\htdocs\mitienda\vendor\magento\framework\App\Request\Http.php(213): Magento\Framework\App\Request\Http->getPathInfo()
#15 C:\xampp_v1\htdocs\mitienda\vendor\magento\framework\App\Http.php(111): Magento\Framework\App\Request\Http->getFrontName()
#16 C:\xampp_v1\htdocs\mitienda\generated\code\Magento\Framework\App\Http\Interceptor.php(23): Magento\Framework\App\Http->launch()
#17 C:\xampp_v1\htdocs\mitienda\vendor\magento\framework\App\Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#18 C:\xampp_v1\htdocs\mitienda\pub\index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#19 {main}`

Someone managed to solve this problem, it should be noted that I have tried the old versions of magento and they work correctly for me.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by nshekhada** [comment] 2022-06-29 11:30
This works for me works on Windows

Add "extension=sodium" to php.ini (no quotes)
Copy php/libsodium.dll to apache/bin/
Restart Apache

**Comment by engcom-Alfa** [comment] 2022-07-20 14:36
Hi @marcelovillalta0 
As suggested in above-comment, have to tried with settings updated? Is it working now?
If you haven't tried yet, please give a try.

If you tried and still getting an issue, kindly help us with all the step by step commands and settings you are following up during the installation. It will help us to reproduce and then to confirm the issue.

Thanks in advance!

Hi @gwharton & @nshekhada Thanks for your contribution & collaboration over here :)

**Comment by Finbayern** [comment] 2022-07-24 22:08
> @marcelovillalta0
> 
> To test whether sodium is working under PHP create a phpinfo.php file in your pub folder with contents
> 
> ```
> <?php
> phpinfo();
> ```
> 
> Browse to that file in your browser and check the php configuration contains the following section.
> 
> ![image](https://user-images.githubusercontent.com/30697781/180016801-565d3536-7663-4218-95ac-ef01ba75ed58.png)

I have the same issue as the OP and I suppose this is a dup of https://github.com/magento/magento2/issues/35419 as you wrote above.
I have the sodium installed and I see the exact same section as in your screenshot when I run the phpinfo, so sodium should be ok.
This error only happens with php 8.1 and switching back to php 7.4. fixes the issues, but obviously this is not the long term solution.

Running CentOS v7.9.2009 with MariaDB 10.5 & PHP 7.4/8.0/8.1 .

**Comment by Finbayern** [comment] 2022-08-05 12:26
> 

Correction!
Phpinfo showed that libsodium was installed for php 8.0 and 7.4, but for 8.1 it was not.
EA4 showed that the extension was installed for 8.1 too, thus it was clear that something was broken in the installation.
Therefore I removed it and re-installed it, now it shows up in the phpinfo as well.

This fixed the issue, so the culprit was the missing/broken installation of libsodium.

**Comment by engcom-Bravo** [comment] 2022-12-15 09:04
Thanks for your contribution @gwharton @Finbayern.

@marcelovillalta0 Kindly go through with this https://github.com/magento/magento2/issues/35474#issuecomment-1206388931 and please let us know if you are still facing an issues.

Thanks.

**Comment by engcom-Bravo** [comment] 2022-12-27 06:05
Hi @marcelovillalta0,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-12-27 06:05 UTC
Labels: Issue: needs update, Reported on 2.4.4
