### ISSUE TITLE
PHP Fatal error: Uncaught Error: Wrong parameters for Elasticsearch

### ISSUE THREAD

**Issue by deckside** [magento/magento2#24201] opened 2019-08-20 12:02 UTC
Summary of problem or feature request

After restart elasticserach service is not indexing.
Code snippet of problem

ubuntu@ip-172-31-11-28:/var/www/magento/bin$ sudo php magento indexer:reindex catalogsearch_fulltext
PHP Fatal error: Uncaught Error: Wrong parameters for Elasticsearch\Common\Exceptions\ServerErrorResponseException([string $message [, long $code [, Throwable $previous = NULL]]]) in /var/www/magento/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:666
Stack trace:
#0 /var/www/magento/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(666): Exception->__construct(NULL, 503)
#1 /var/www/magento/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(282): Elasticsearch\Connections\Connection->process5xxError(Array, Array, Array)
#2 /var/www/magento/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections{closure}(Array)
#3 /var/www/magento/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#4 /var/www/magento/vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Obj in /var/www/magento/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 666
ubuntu@ip-172-31-11-28:/var/www/magento/bin$
System details

{
"name" : "8a9Dhi6",
"cluster_name" : "elasticsearch",
"cluster_uuid" : "t8ox8lfkSaO5z3KGhFhiLg",
"version" : {
"number" : "5.6.12",
"build_hash" : "cfe3d9f",
"build_date" : "2018-09-10T20:12:43.732Z",
"build_snapshot" : false,
"lucene_version" : "6.6.1"
},
"tagline" : "You Know, for Search"

    Operating System
    Magento 2.2.6 CE
    PHP Version PHP 7.1.20-1+ubuntu16.04.1+deb.sury.org+1
    MSQL Version -mysql Ver 14.14 Distrib 5.7.27, for Linux (x86_64) using EditLine wrapper

**Comment by engcom-Charlie** [comment] 2019-08-21 07:58
Hello @deckside 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.

We are closing this issue due to branch 2.2-develop was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.
See Accepted pull requests and ported code for more details

If you still faced this issue on 2.3 please create a new Issue with all required details according to Issue reporting guidelines

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-08-21 07:58 UTC
Labels: Issue: Format is not valid
