### ISSUE TITLE
Double spaces in attribute options don't show in Catalog or front end

### ISSUE THREAD

**Issue by DaveSkirrow** [magento/magento2#27163] opened 2020-03-04 16:02 UTC
### Preconditions (*)

1. 2.3.4

### Steps to reproduce (*)

1.  Create an attribute and set it as a dropdown
2.  Add an option to the attribute with a double space (or multiple spaces in a row). eg.![2020-03-04_1552](https://user-images.githubusercontent.com/61794963/75898011-68a0d280-5e31-11ea-8a35-9ac70447d543.png)
3. Add attribute to attribute set 
4. Go to Catalog > Products and look at dropdown for the new attribute

### Expected result (*)

1.  I'd expect the option name in the dropdown in Catlog to have the same number of spaces as in the attribute

### Actual result (*)

1. All additional spaces are removed in catalog, leaving only 1

![2020-03-04_1554](https://user-images.githubusercontent.com/61794963/75897889-2d9e9f00-5e31-11ea-9842-f76b82b86577.png)

2. Back in the attribute settings the extra spaces remain

**Comment by DaveSkirrow** [comment] 2020-03-04 16:03
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-04 16:03
Hi @DaveSkirrow. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-03-04 16:04
Hi @DaveSkirrow, here is your [Magento instance](https://i-27163-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27163-2-4-develop.instances.magento-community.engineering/admin_b018](https://i-27163-2-4-develop.instances.magento-community.engineering/admin_b018)
Login: `36b813de` Password: `ea0cf1b39970`
Instance will be terminated in up to 3 hours.

**Comment by DaveSkirrow** [comment] 2020-03-04 16:25
I was able to reproduce the issue on vanilla Magento instance

**Comment by ajijshekh123** [comment] 2020-03-05 05:27
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-05 05:27
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-03-05 05:28
Hi @ajijshekh123, here is your [Magento instance](https://i-27163-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27163-2-4-develop.instances.magento-community.engineering/admin_2228](https://i-27163-2-4-develop.instances.magento-community.engineering/admin_2228)
Login: `2310c7da` Password: `e295716a0f63`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2020-03-05 06:01
Hello @DaveSkirrow,
I have verified this issue latest Magento 2.4 instance. But I can't able to reproduce this issue.
Please see attached screenshot:
![1](https://user-images.githubusercontent.com/24711761/75952440-c3d7d100-5ed4-11ea-9055-d5acba44e7c1.png)

![2](https://user-images.githubusercontent.com/24711761/75952444-c508fe00-5ed4-11ea-9973-d5b3bf73bda0.png)

![3](https://user-images.githubusercontent.com/24711761/75952448-c5a19480-5ed4-11ea-88db-8b29080bbd42.png)

Can you please update me on which version you have to verify this issue?
Please update your feedback here. 

Thanks.

**Comment by DaveSkirrow** [comment] 2020-03-05 08:13
Hi, thanks for the reply. 
Apologies, I think my first image was misleading. The vertical line was the cursor, not a pipe symbol. 

Please try to reproduce by typing the option name as follows. 
Press A
Press space bar 10 times 
Press B

So the option name has a character St the start and end with several spaces in between. 

I tested on the latest 2.4 instance

**Comment by ajijshekh123** [comment] 2020-03-05 08:42
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-05 08:43
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-03-05 08:43
Hi @ajijshekh123, here is your [Magento instance](https://i-27163-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27163-2-4-develop.instances.magento-community.engineering/admin_2d05](https://i-27163-2-4-develop.instances.magento-community.engineering/admin_2d05)
Login: `40d8e6df` Password: `123ce7cf7897`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2020-03-05 08:52
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32174` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Usik2203** [comment] 2020-03-09 13:50
I suppose that spaces  was trimmed by knockout in app/code/Magento/Ui/view/base/web/js/lib/knockout/bindings/optgroup.js : line 117 
`  ko.utils.setDomNodeChildrenFromArrayMapping(
                element,
                filteredArray,
                optionNodeFromArray,//eslint-disable-line no-use-before-define
                arrayToDomNodeChildrenOptions,
                callback
            );`

**Comment by vasilii-b** [comment] 2020-03-11 08:55
Hi @DaveSkirrow,
Thanks for filling in a new issue.
Could you please provide any use-cases?
Thank you!

**Comment by sdzhepa** [comment] 2020-06-15 20:45
Hello @DaveSkirrow

This issue has been reviewed during the Triage meeting with Magento Product Managers.
After discussion, we cannot consider it as a bug or any kind of unexpected behavior.

Considering it as an improvement of feature request, a business value still unclear.

Such improvement possibly could have some value for a very rare situation or for a specific merchant but not for all.

**Comment by magento-engcom-team** [comment] 2020-06-15 20:45
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-32174).

**Comment by magento-engcom-team** [comment] 2020-06-15 20:46
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-32174).

**Closed as completed by sdzhepa** 2020-06-15 20:45 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Admin, Reproduced on 2.4.x, Triage: Ready for Triage, Reported on 2.3.4

**Comment by magento-engcom-team** [comment] 2020-06-15 20:46
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-32174).

**Comment by magento-engcom-team** [comment] 2020-06-15 20:46
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-32174).

**Comment by magento-engcom-team** [comment] 2020-06-15 20:47
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-32174).

**Comment by magento-engcom-team** [comment] 2020-06-15 20:47
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-32174).

**Comment by cmkb03** [comment] 2025-01-20 18:50
Necro: This same issue was causing us issues with catalog search -- specifically, multiple spaces being condensed into single spaces when the index is generated.

@DaveSkirrow :: I'm fairly certain this is being caused by the magento\module-catalog-search\Model\Indexer\Fulltext\Action\DataProvider.php function filterAttributeValue which is called inside getAttributeValue and getAttributeOptionValue. In your case, the function may exist elsewhere, but the outcome is the same.
