### ISSUE TITLE
Not able to install magento 2.4.1 in my Mac  Please help with some documents

### ISSUE THREAD

**Issue by HIMANSHU-281** [magento/magento2#30620] opened 2020-10-23 13:31 UTC
### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment] 2020-10-24 01:35
No one can help you if you post the issue like this. Missing details, What current process you have and what exactly issue/error occur ?
I high recommended you check doc
https://devdocs.magento.com/guides/v2.4/install-gde/bk-install-guide.html
And for configuration setup
See user guide https://docs.magento.com/user-guide/

**Comment by ihor-sviziev** [comment] 2020-10-26 11:48
Hi @HIMANSHU-281,
As @mrtuvn requested - could you add additional info, What steps are you trying to do, what exact issue do you have? Unfortunately without this info we can't help you.

**Comment by HIMANSHU-281** [comment] 2020-10-26 11:56
Sure, I will add

Thanks and Regards,
Himanshu Kanyal
Senior Software Test Engineer
Ksolves - https://www.ksolves.com
Email - himanshu.kanyal@ksolves.com <priyanka.dahiya@ksolves.com>
Contact -8859888885

**Comment by ihor-sviziev** [comment] 2020-10-26 17:47
Duplicate of #30654 

I’m closing this issue

**Closed as completed by ihor-sviziev** 2020-10-26 17:47 UTC
Labels: duplicate, Triage: Dev.Experience, Event: MageCONF CD 2020
