### ISSUE TITLE
Mini Cart: Display Cart Summary - "Display item quantities" count not working as expected

### ISSUE THREAD

**Issue by duffner** [magento/magento2#14586] opened 2018-04-07 14:54 UTC
### Preconditions

1. Magento 2.2.3 
2. Magento Luma theme with Sample Data 

### Steps to reproduce

1. Set Sales -> Checkout -> My Cart Link -> Display item quantities
2. Add 1 item to the cart with qty of 1 
3. Add a second item to the cart of qty 2 

### Expected result

1. Cart Count in Header should state 3
2. Cart Count within Minicart should state 3 

### Actual result

1. Cart Count within Minicart states 2 

After review of logic, the count within the mini cart always performs "Display number of items in cart" regardless of Admin setting.  As a note: this is for the count within the Mini cart.  

I reproduced this issue on stock Magento 2.2.3 with Sample data, however, I forgot to take a screenshot.  Below is a screenshot of a recent project displaying the same issue. 

<img width="418" alt="display item quantities" src="https://user-images.githubusercontent.com/7387019/38456362-a4a3991a-3a49-11e8-8ddf-319023d6240e.png">

**Comment by engcom-backlog-nickolas** [comment] 2018-07-25 13:33
Hello @duffner, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by slavvka** [comment] 2018-12-04 21:52
Closing as not a bug. The settings `Set Sales -> Checkout -> My Cart Link` relates only to the number of items shown in the box near `LOGIN` link, i.e. the link which opens the cart

**Closed as completed by slavvka** 2018-12-04 21:52 UTC
Labels: Issue: Ready for Work, Component: Checkout, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid

**Comment by duffner** [comment] 2018-12-13 18:12
@slavvka, what you're saying is correct, however that's the bug.  The feature is not consistent as there are two locations for item cart count in the "mini cart" once in the header display, the other within the minicart itself.

**Comment by duffner** [comment] 2018-12-13 18:13
Please ask questions before "closing" if you do not understand.

**Comment by duffner** [comment] 2018-12-13 18:14
@slavvka  If it's not a bug, please answer the following question . "How can you have 5 items and 2 items in the cart at the same time?"  This makes absolutely no sense.

**Comment by tkacheva** [comment] 2018-12-13 21:13
@duffner thanks for catching that. In Luma theme we have "items" label hidden with CSS so didn't see the inconsistency. 
The correct behavior would be:

1. Replace the field label Sales -> Checkout -> My Cart Link -> **Display Cart Summary**  to **Cart Counter Shows**
![wewewe](https://user-images.githubusercontent.com/5603216/49968194-b6f34a00-feea-11e8-9f8e-4d88daee3eb4.png)
2. Update the labels inside the dropdown to be:
Number of products in cart
Total number of items in cart
![screen shot 2018-12-13 at 2 30 40 pm](https://user-images.githubusercontent.com/5603216/49967319-1bf97080-fee8-11e8-8b24-8b830a27b82d.png) 
3. Add logic that changes label in mini cart link:
if "Number of products in cart" selected the label is "products"
if "Total number of items in cart" selected the Lebel is "items"
![screen shot 2018-12-13 at 3 02 55 pm](https://user-images.githubusercontent.com/5603216/49967604-fcaf1300-fee8-11e8-891f-d21114c0ab57.png)
4. Replace "items" inside the mini cart with "products" as the setting above doesn't influence this counting. 
![ws](https://user-images.githubusercontent.com/5603216/49967763-6f1ff300-fee9-11e8-983e-2ce3a215638b.png)

**Comment by duffner** [comment] 2018-12-20 01:59
@tkacheva, thanks for providing the additional information!  I test off of base, not Luma, I guess I need to specify this in future tickets.  Once again, thank you

**Comment by Volvoxpl** [comment] 2019-03-22 11:08
Solution to problem described:
- Copy file vendor/magento/module-checkout/view/frontend/web/template/minicart/content.html to your template
- Change `<span class="count" text="getCartLineItemsCount()"/>` to `<span class="count" text="getCartParam('summary_count')"/>`

**Comment by harshvardhanmalpani** [comment] 2019-05-27 12:06
@Volvoxpl  I tried your recommendation, It says unable to process binding. getCartParam is not defined

Any thoughts?

###UPDATE

I was editing cart-items.html for checkout page, not minicart. But to fellow explorers who might want to show **total cart items in checkout area**, replace `getCartLineItemsCount` with `getItemsQty`
The involved js file is `vendor/magento/module-checkout/view/frontend/web/js/view/summary/cart-items.js`

here are my notes https://tutes.in/how-to-show-correct-item-count-in-magento-2-checkout-order-summary/

The method mentioned by @Volvoxpl works fine for minicart because it involves js 
`vendor/magento/module-checkout/view/frontend/web/js/view/minicart.js`
