### ISSUE TITLE
MySQL Error on Product Save

### ISSUE THREAD

**Issue by soumiktuban** [magento/magento2#36522] opened 2022-11-23 14:44 UTC
### Preconditions and environment

- Magento version: 2.4.5-p1
- MySQL version 8.0.29
- PHP 8.1.11

### Steps to reproduce

1. Admin -> Catalog -> Products -> Edit any Product (Which is associated with at least one website).
2. Now Uncheck all websites from "Product in Websites".
3. Change "Visibility" from Catalog Search to "Not Visible Individually".
4. Save

### Expected result

You saved the product.

### Actual result

Getting an error, looks like store_id is not properly constructed:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '))' at line 1, query was: DELETE `url_rewrite` FROM `url_rewrite` WHERE (`entity_id` IN ('1')) AND (`entity_type` IN ('product')) AND (`store_id` IN ())

### Additional information

![CoreIssue](https://user-images.githubusercontent.com/10050358/203574741-334e38d2-b028-47fe-a26c-ab73ea1c543c.JPG)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-11-24 06:20
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-24 12:36
Hi @soumiktuban,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**


1.Admin -> Catalog -> Products -> Edit any Product (Which is associated with at least one website).
2.Now Uncheck all websites from "Product in Websites".
3.Change "Visibility" from Catalog Search to "Not Visible Individually".
4.Save



<img width="1271" alt="Screenshot 2022-11-24 at 1 15 34 PM" src="https://user-images.githubusercontent.com/51680745/203785823-7dcae048-1057-4172-9001-4bc5d84daf30.png">



<img width="1138" alt="Screenshot 2022-11-24 at 1 15 40 PM" src="https://user-images.githubusercontent.com/51680745/203785877-aab50cc5-f279-495d-8eca-921b2c5adf51.png">



<img width="830" alt="Screenshot 2022-11-24 at 1 15 56 PM" src="https://user-images.githubusercontent.com/51680745/203785911-d041584f-0668-4472-87f0-bb9a145783f7.png">



Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks

**Comment by soumiktuban** [comment] 2022-11-24 12:44
Can I have your instance to verify the issue and if I can reproduce it?

**Comment by engcom-Bravo** [comment] 2022-11-25 11:20
Hi @soumiktuban,

Thanks for your update.

We have verified in our Local Instance Magento `2.4 develop` and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

1.Admin -> Catalog -> Products -> Edit any Product (Which is associated with at least one website).
2.Now Uncheck all websites from "Product in Websites".
3.Change "Visibility" from Catalog Search to "Not Visible Individually".
4.Save

After saving the product there is no change in **Product in Websites**. 


![iugwdfuH-Products-Inventory-Catalog-Magento-Admin](https://user-images.githubusercontent.com/51680745/203974284-366219a4-51f1-4d4b-a9c3-fac190c6f7a7.png)


Kindly check your System requirements.Magento 2.4.5 is supported for PHP 8.1.


https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html.


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by soumiktuban** [comment] 2022-11-25 13:26
Hi @engcom-Bravo 

Currently, I am using PHP 8.1. Still, I am able to replicate the issue. Kindly re-check the issue. Screenshot attached.

![image](https://user-images.githubusercontent.com/10050358/203995025-66f5bed2-4e32-4410-910e-d008cf76210e.png)

![image](https://user-images.githubusercontent.com/10050358/203995323-db8a0ff5-905b-41db-8da2-8d88a050a01d.png)

Thanks

**Comment by engcom-Bravo** [comment] 2022-11-28 11:53
Hi @soumiktuban.

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


We are using PHP 8.1

<img width="662" alt="Screenshot 2022-11-28 at 12 07 38 PM" src="https://user-images.githubusercontent.com/51680745/204271073-6a6ad38d-e1a1-4154-b40f-4c0533481fb3.png">

<img width="505" alt="Screenshot 2022-11-28 at 12 47 33 PM" src="https://user-images.githubusercontent.com/51680745/204271099-90c67198-1932-451c-a62c-6b2731caf3df.png">



![rbccgvbv-Products-Inventory-Catalog-Magento-Admin](https://user-images.githubusercontent.com/51680745/204271146-8b65cf1a-043a-4f8c-9d75-908c38c805b7.png)



Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.

Thanks.

**Comment by soumiktuban** [comment] 2022-11-29 11:08
Thanks for the response.

It looks like the below code changes fix the issue:
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php

![image](https://user-images.githubusercontent.com/10050358/204513357-2c17817a-fc84-4b80-bfff-cec57465e609.png)

Kindly let me know, what is the release version of the above code.

Thanks

**Comment by engcom-Bravo** [comment] 2022-11-30 09:20
Hi @soumiktuban,

Thanks for your update.

we have verified in magento `2.4 develop` branch.it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.

Please let us know if you are still any issue.

Thanks.

**Comment by soumiktuban** [comment] 2022-11-30 10:45
Hi @engcom-Bravo 

Thanks for the information.

Kindly share the release version of the above code fix and the estimated time to release. 

Thanks.

**Comment by engcom-Bravo** [comment] 2022-11-30 11:18
Hello @soumiktuban,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-2567 by the internal team.
Related commits: https://github.com/magento/magento2/search?q=AC-2567&type=commits

Based on the Jira ticket, the target version is 2.4.6

Thanks.

**Closed as completed by engcom-Bravo** 2022-11-30 11:18 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.5-p1
