### ISSUE TITLE
Issue with huge reindex time. Reindex optimization. 

### ISSUE THREAD

**Issue by AndreyChorniy** [magento/magento2#26403] opened 2020-01-15 16:09 UTC
### Preconditions (*)

1. Magento version 2.3.2-p2 & 2.4-develop
2. Above 900K of products
3. Added customization to `Magento\Framework\Mview\View` to decrease the count of entities per one indexer iteration to 1000. This is potential should decrease the time for reindex execution

### Steps to reproduce (*)

1. Change prices for 544771 products
2. Run command `php ./bin/magento indexer:status` You will see something like these 
![reindexIssue](https://user-images.githubusercontent.com/6145397/72440486-9a8ea480-37b1-11ea-8c7a-b67d787dd068.png)
3. Run reindex using the command `php ./bin/magento cron:run --group=index --bootstrap=standaloneProcessStarted=1`
4. Reindex working about 2 hrs and we get updated 1000 entities during this time. 

A lot of time take execution [this logic](https://github.com/magento/magento2/blob/cc053101852a601ac18b5214cbb717955b10cd03/app/code/Magento/CatalogRule/Model/Indexer/IndexBuilder.php#L419)

I have investigated [this method](https://github.com/magento/magento2/blob/cc053101852a601ac18b5214cbb717955b10cd03/app/code/Magento/CatalogRule/Model/Indexer/ReindexRuleGroupWebsite.php#L68) 
and log query:

`INSERT INTO `catalogrule_group_website` (`rule_id`, `customer_group_id`, `website_id`) SELECT DISTINCT  `catalogrule_product`.`rule_id`, `catalogrule_product`.`customer_group_id`, `catalogrule_product`.`website_id` FROM `catalogrule_product` WHERE (1578602213 >= from_time AND ((1578602213 <= to_time AND to_time > 0) OR to_time = 0)) ON DUPLICATE KEY UPDATE `rule_id` = VALUES(`rule_id`), `customer_group_id` = VALUES(`customer_group_id`), `website_id` = VALUES(`website_id`)` 

This query executed about 3000 times per one cron run for update 1000 entities. And each insert take about 2 seconds. So time for 3000 inserts takes about 1,5 hrs.

### Expected result (*)

Reindex work faster

### Actual result (*)

Reindex working about 2hrs and during this time we have updated only 1000 entities.

I appreciate any ideas here

**Comment by magento-engcom-team** [comment] 2020-01-17 10:32
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30509` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment] 2024-11-19 03:27
Hi @AndreyChorniy,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance with 1M products and the issue is not reproducible.Kindly refer the screenshots.

<img width="1391" alt="Screenshot 2024-11-12 at 13 54 58" src="https://github.com/user-attachments/assets/2569fe3c-0a88-4552-bd89-557eed651764">



<img width="1434" alt="Screenshot 2024-11-12 at 16 11 31" src="https://github.com/user-attachments/assets/54d65ec2-42d4-4ff0-9078-fb01d9f5aafc">

Reindex working faster.Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-11-19 03:27 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Indexer, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P2, Severity: S2, Triage: Performance, Progress: done, CD, Reported on 2.3.2-p2, Area: Performance
