### ISSUE TITLE
Uncaught Error: [object Object]

### ISSUE THREAD

**Issue by Aurinho97** [magento/magento2#34530] opened 2021-11-04 09:51 UTC
### Preconditions (*)

1. Magento 2.4.1

### Steps to reproduce (*)

1. Scenario performed in b2b
2. Mobile display using Firefox browser
3. Log in to account
4. Company account page displayed
5. Add product to cart
6. Go to checkout page
7. Make an order
8. When page starts to refresh, the console error occurs (Uncaught Error: [object Object])

### Expected result (*)

1. No error in console window.

### Actual result (*)

1. Error message in console: Uncaught Error: [object Object]

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2021-11-10 12:09
Dear @Aurinho97,

We have tried to reproduce this issue in Magento 2.4-develop with B2b installed, but for us, the issue is not reproducible. Please refer to the below-recorded video and let us know if we missed anything:

https://user-images.githubusercontent.com/51681618/141110396-7d5009ff-e31b-4a98-8f19-210ab8f8c112.mp4

Thanks

**Comment by engcom-Hotel** [comment] 2021-11-25 07:00
Dear @Aurinho97,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2021-11-25 07:00 UTC
Labels: Issue: needs update, Reported on 2.4.1
