### ISSUE TITLE
Issue in PDF files for Unicode (non-latn) languages

### ISSUE THREAD

**Issue by sIiiS** [magento/magento2#2766] opened 2015-12-19 19:48 UTC
In Magento 2 same as Magento 1.x we have issue with PDF files...
for example in invoices when we generate a PDF and open it, we see some non-understanding characters!!
Please solve it, this is very bad issue for us
An example attached for better understanding!
[packingslip2015-12-19_19-38-08.pdf](https://github.com/magento/magento2/files/67588/packingslip2015-12-19_19-38-08.pdf)

**Comment by orlangur** [comment] 2015-12-20 18:29
Did you try to use non-default font? From http://stackoverflow.com/questions/14379626/japanese-characters-on-magento-pdf it looks like a silver bullet suitable for all languages could not exist.

Does LinLibertin font https://github.com/magento/magento2/blob/077584c99ebb8007cad176c3b9a0144a05c259cd/app/code/Magento/Sales/Model/Order/Pdf/AbstractPdf.php#L854 contain characters used in your invoice at all?

**Comment by Pakkapao** [comment] 2015-12-21 05:40
This is similar to #1145

I'm currently using non-default font for my site. It would be great if Magento 2 could support all languages out of box.

**Comment by sIiiS** [comment] 2015-12-21 11:15
@orlangur I did test with non-default font, attached, please see... characters are visible but they are separate of together and this is another problem!
Tested with several fonts and in all of them the same

In my language, the letters of the word is not separate of them same as english, but in the sample you can see they are separate!

[packingslip2015-12-21_11-08-20.pdf](https://github.com/magento/magento2/files/68383/packingslip2015-12-21_11-08-20.pdf)

@adzminz your language is same as english for letters and words

**Comment by NadiyaS** [comment] 2016-06-02 10:07
This issue is closed as duplicate of #1145.

**Closed as completed by NadiyaS** 2016-06-02 10:07 UTC

**Comment by lics1217** [comment] 2024-11-08 06:54
I also encountered a similar problem when exporting Japanese pdf. I used the following two language packs to solve the problem。
* GenJyuuGothic-Regular.ttf
* GenJyuuGothic-Bold.ttf
