### ISSUE TITLE
Bundle qty is increased every quote save on 2.4.2-p2

### ISSUE THREAD

**Issue by stkorf** [magento/magento2#34179] opened 2021-09-28 12:40 UTC
### Preconditions (*)

1. Magento 2.4.2-p2
2. Create simple product (sku simple1)
3. Create bundle product (sku bundle1) with 2 options that contains simple1 product
![image](https://user-images.githubusercontent.com/15034002/135086584-d365a71d-4155-4234-8ac9-db557457d609.png)

### Steps to reproduce (*)

1. Go to frontend
2. Add bundle1 product to cart with selected simple1 in both options
3. Go to cart
**Expected:** 1 bundle product will be added
**Actual:** 4 bundle products are shown on cart page
4. Go to checkout
5. Fill address fields and go to payment 
**Expected:** 1 bundle product is shown in totals block
**Actual:** 16 bundle products are shown in totals block
![image](https://user-images.githubusercontent.com/15034002/135087920-f134bfe1-c49e-4644-8a58-a31789131143.png)

### Expected result (*)

1. Only 1 bundle product is shown on all checkout and cart pages

### Actual result (*)

1. Qty of bundle products is increased every save of quote

Looks like issue in https://github.com/magento/magento2/commit/dac067c9e8c056e5aedeba62cf3d58b10bc90d8e#diff-64f746135385baec0f5308d1c9686fe77ec87e806bf4f3aef821a26af90a7fd7 changes in app/code/Magento/CatalogInventory/Model/Quote/Item/QuantityValidator/Initializer/Option.php file. On 2.4.3 this issue isn't reproduced because vendor/magento/module-catalog-inventory/Model/StockStateProvider.php method checkQuoteItemQty was refactored
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2021-09-29 08:46
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible in all pages:
Bundle Product configuration:
![image](https://user-images.githubusercontent.com/60198231/135234715-d0291224-25a2-4559-9c83-53ba7c07b09d.png)

![image](https://user-images.githubusercontent.com/60198231/135234177-d194dca7-144c-4a14-a60c-5aa10501d54c.png)
No issue in Shopping Cart page and checkout pages
![image](https://user-images.githubusercontent.com/60198231/135234111-73614122-067f-4d4b-b687-9dea22c931a0.png)

![image](https://user-images.githubusercontent.com/60198231/135234074-2544f73f-c9cd-49d8-87dd-5cb4ee09312b.png)
No issue in Admin - Sales - Orders page
![image](https://user-images.githubusercontent.com/60198231/135234013-06fe73e7-5704-428f-9e7b-2be05cd559b1.png)

@stkorf , kindly recheck the issue on Magento 2.4-develop branch as it has the latest code base and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by stkorf** [comment] 2021-09-29 10:46
@engcom-November As I mentioned in description - this issue is reproduced on 2.4.2-p2. On 2.4-developer this issue isn't reproduced. 
As I understand, Magento is still supporting 2.4.3 version and is creating security patches. And looks like one of this patches has broken bundle products.

**Comment by engcom-Delta** [comment] 2021-10-07 13:59
This issue not reproduce on Magento 2.4 dev branch .Hence closing this for now.
Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Closed as completed by engcom-Delta** 2021-10-07 13:59 UTC
Labels: Issue:  Cannot Reproduce, Component: Bundle, Issue: needs update, Reported on 2.4.x, Area: Product

**Comment by jl-tric** [comment] 2022-02-17 10:38
This is still an issue on 2.4.3-p1.
Reverting the change in https://github.com/magento/magento2/commit/dac067c9e8c056e5aedeba62cf3d58b10bc90d8e#diff-64f746135385baec0f5308d1c9686fe77ec87e806bf4f3aef821a26af90a7fd7 Option.php fixes the issue.
