### ISSUE TITLE
Storeview not being saved in, "Send Welcome Email From" Select Field

### ISSUE THREAD

**Issue by crantron** [magento/magento2#6240] opened 2016-08-18 23:54 UTC
1.  Branch 2.1 
2. PHP 7
### Steps to reproduce
1. Change welcome email to the correct store view (in a multi store set up)
2. Save 
### Expected result

1. Should save selected option
### Actual result

1. Selects first item in select field list ( Chefstoys instead of Wingstop).

![screen shot 2016-08-18 at 4 52 33 pm](https://cloud.githubusercontent.com/assets/3859969/17794441/3f16a2c4-6564-11e6-8887-93a87ec17396.png)

![screen shot 2016-08-18 at 4 52 11 pm](https://cloud.githubusercontent.com/assets/3859969/17794448/4b05f710-6564-11e6-9072-04c79e2446a8.png)

**Comment by crantron** [comment] 2016-08-18 23:57
Confirmation emails are set to not required, I'm not sure if that is causing this behavior.

**Comment by sevos1984** [comment] 2016-08-26 09:04
Thanks for reporting. Internal ticket created MAGETWO-57204

**Comment by webdesk** [comment] 2017-03-08 13:47
I have faced the same issue and made the following changes to resolve it. 

File: module-customer/view/base/ui_component/customer_form.xml
Change: 

`<field name="sendemail_store_id">
   <argument name="data" xsi:type="array">
	   <item name="options" xsi:type="object">Magento\Store\Model\System\Store</item>
	   <item name="config" xsi:type="array">
		   <item name="label" xsi:type="string" translate="true">Send Welcome Email From</item>
		   <item name="dataType" xsi:type="string">number</item>
		   <item name="formElement" xsi:type="string">select</item>
		   <item name="source" xsi:type="string">customer</item>
           <item name="imports" xsi:type="array">
			   <item name="value" xsi:type="string">${ $.provider }:data.customer.store_id</item>
		   </item>
	   </item>
   </argument>
</field>`

**Comment by magento-engcom-team** [comment] 2017-09-20 22:31
@crantron, thank you for your report.
The issue is already fixed in 2.1.3

**Closed as completed by magento-engcom-team** 2017-09-20 22:31 UTC
Labels: Issue: Ready for Work, bug report, Fixed in 2.1.x, Issue: Format is not valid
