### ISSUE TITLE
Oracle Cloud - Layer 7 Bad Gateway

### ISSUE THREAD

**Issue by ishanrakitha** [magento/magento2#37314] opened 2023-03-30 07:24 UTC
### Summary

Hello Everyone,

We are using Oracle Cloud Infrastructure flexible load balancer and terminating SSL at the load balancer level. 

For HTTP or HTTPS listeners other then the home page and categories rest is showing 502 bad gateway including the admin backend. 

If we switch the listener to "TCP" everything is working as expected. 

**Traffic Flow: ** DNS -> Load Balancer -> Varnish -> Nginx -> PHP FPM

Please let me know if anyone has faced this issue. Appreciate your support in advance.

Thank you.

### Examples

We are using all default installations for Basic Magento 2 store.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2023-03-30 16:11
Hello @ishanrakitha,

On this board, we are handling the bugs related to Magento's core libraries. But after reading the description it seems that the issue is not related to any issue related to Magento core.

Hence I am closing this issue from here and request you to please use [Magento Stackexchange](https://magento.stackexchange.com/) for your query.

Thanks

**Closed as completed by engcom-Hotel** 2023-03-30 16:11 UTC
Labels: Triage: Dev.Experience, Issue: ready for confirmation, Reported on 2.4.x
