### ISSUE TITLE
Show message in reindex process when an index is skipped

### ISSUE THREAD

**Issue by klein0r** [magento/magento2#5492] opened 2016-07-06 09:56 UTC
## Steps to reproduce
1. Install Magento
2. Start reindexing a single index or full reindex process via console
3. Start another reindex process
## Expected result

Skipped index (already running / in progress) ...
## Actual result

Catalog Search index has been rebuilt successfully in 00:00:00

**Comment by veloraven** [comment] 2016-07-29 11:56
@klein0r thank you for your report.
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by andimov** [comment] 2016-08-15 14:28
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by klein0r** [comment] 2016-08-15 14:52
It has been tested with 2.0.7

**Comment by klein0r** [comment] 2016-08-15 14:56
@andimov Please reopen the issue

**Comment by ArthurTransoftgroup** [comment] 2017-07-03 12:12
@klein0r We've created internal ticket MAGETWO-70416 to address this issue.

**Comment by magento-engcom-team** [comment] 2017-10-13 07:44
@klein0r, thank you for your report.
We've created internal ticket(s) MAGETWO-70416 to track progress on the issue.

**Comment by gabrielqs-redstage** [comment] 2017-10-26 12:03
Hey there, I'm working on it. #SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment] 2018-12-26 21:30
Hi @milindsingh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-10-01 22:31
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Closed as completed by magento-engcom-team** 2019-10-01 22:31 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Issue: Format is not valid
