### ISSUE TITLE
checked out with terms and conditions using Paypal Payments Pro

### ISSUE THREAD

**Issue by shijiang** [magento/magento2#5186] opened 2016-06-23 14:09 UTC
## Steps to reproduce
1. Install Magento using composer to get from repo.magento, CE version 2.0.7.
2. Enable the Paypal Payments Pro (I tested with Authorize.net too).
3. Enable the terms and conditions when checkout
4. Create the terms and conditions
5. Check out with the terms and conditions
## Expected result
1. Place the order.
## Actual result
1. Can't proceed to finish the order.
2. Api Report: Fatal Error: 'Call to a member function getAgreementIds() on a non-object' in '{path to magento}magento2/vendor/magento/module-checkout-agreements/Model/Checkout/Plugin/Validation.php

**Comment by wert2all** [comment] 2016-06-23 14:12
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by shijiang** [comment] 2016-06-23 14:31
The version is CE 2.0.7.

**Comment by shijiang** [comment] 2016-06-23 14:41
I can get around with it by checking if **getExtensionAttributes()** is null in the function **beforeSavePaymentInformation()** in the **Validation.php** file

**Comment by alena-marchenko** [comment] 2016-06-30 12:50
Hi @shijiang 

Is this issue still reproducible for you on 2.1.0 version or on latest develop branch?

**Comment by vzabaznov** [comment] 2016-07-14 08:00
Hi, @shijiang  thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.

**Closed as completed by vzabaznov** 2016-07-14 08:00 UTC
Labels: Progress: needs update, Component: Payment
