### ISSUE TITLE
eMail-Template for orders: No order positions if template was not loaded from base template

### ISSUE THREAD

**Issue by 4ctobias** [magento/magento2#31014] opened 2020-11-23 11:47 UTC
### Preconditions (*)
1. Magento 2.4.0 - issue also exists in 2.3.x

### Steps to reproduce (*)
1. Create a new email template for orders
2. Do NOT load a base template
3. Copy the subject line and the template body into the respective fields when creating the template
4. Save the new template
5. Select the template to be used as order confirmation mail

### Expected result (*)
1. When an order mail is sent, the template should used correctly: The eMail should include the customers data and the ordered products and shipping information.

### Actual result (*)
1. The email sent just contains the billing information 
2. No shipping information and no products are included in the eMail.

![Bildschirmfoto 2020-11-23 um 12 44 13](https://user-images.githubusercontent.com/43742974/99958448-aeb81080-2d89-11eb-95cc-879c3c9cf9d0.png)

If I check the email_template table the field is_legacy is set to zero. If I change this value to 1 the order confirmation mail will be correct - the whole data ins rendered into the eMail.

**Comment by devcccc** [comment] 2020-11-23 12:05
@magento give me 2.4-develop instance

**Comment by devcccc** [comment] 2020-11-23 12:32
Unfortunately the test instance does not send emails - I didn't received a order confirmation mail, so its not possible to verify this issue with a test instance.

**Comment by IsmailYaman** [comment] 2020-11-23 13:05
Hi, I had the same problem with Magento 2.3.4. A temporary fix for this is to set in db table: email_template column is_legacy = 1 for the order template

**Comment by 4ctobias** [comment] 2020-11-23 13:07
Hi Ismail,

I did this is also in the table directly - but this should not a solution for our customers which normally do net get direct access to the database - as they might crash something if they start to edit the tables directly ;)

Best

Tobias

**Comment by engcom-Delta** [comment] 2020-11-25 07:59
Hi @4ctobias thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Manual testing scenario:**
- Go to Marketing->Emails Template
- Create a new email template for orders
- Do NOT load a base template
- Copy Template Subject and Template Content from default order confirmation template 
![image](https://user-images.githubusercontent.com/51681379/100198106-0da19500-2f04-11eb-8500-5fc1f207628d.png)
- Save the new template
- Select the template to be used as order confirmation mail
![image](https://user-images.githubusercontent.com/51681379/100198136-1d20de00-2f04-11eb-9e89-efba6033bc3b.png)
- Place order as registered customer 
- Check Order Confirmation emal

**Result:**
:heavy_check_mark: Email contains product data and customer data
![image](https://user-images.githubusercontent.com/51681379/100198439-8a347380-2f04-11eb-8c8c-8073589a3953.png)


Is there any steps I missed?

**Comment by engcom-Delta** [comment] 2020-12-29 14:08
@4ctobias we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Closed as completed by engcom-Delta** 2020-12-29 14:08 UTC
Labels: not-confirmed, Reported on 2.4.0
