### ISSUE TITLE
Configuration for /web/cookie/cookie_domain violates config hierarchy when specified in env.php

### ISSUE THREAD

**Issue by GamesmenJordan** [magento/magento2#35085] opened 2022-02-11 05:16 UTC
### Preconditions (*)
1. Magento 2.4.3
2. Environment must already be set up
3. Configure `/web/cookie/cookie_domain` in database to `.example.org`

**Assumptions**
1. Assumes correct `/web/cookie/cookie_domain` is domain is `.example.org`
2. Assumes Magento is accessible from `www.example.org`

### Steps to reproduce (*)
1. Modify config in database and set `/web/cookie/cookie_domain` to `.example.com` (incorrect value)
1. Modify `env.php` and set `/web/cookie/cookie_domain` to `.example.org` (correct value)
2. (Optionally?) Run `app:config:import` and to ensure configuration is valid and consistent
3. Observe that cookies are not correctly set using the domain as defined in `env.php` (no cookies are set)

### Expected result (*)
![image](https://user-images.githubusercontent.com/59077362/153540642-ae3a9418-3f57-4dbe-a5cd-c1f0e550c3b9.png)
1. According to the diagram provided in Magento 2 dev docs (https://devdocs.magento.com/guides/v2.4/config-guide/deployment/pipeline/technical-details.html) the value in `env.php` should supercede database (or `config.php`) configuration values
2. Cookies should be set using the `.example.org` domain

### Actual result (*)
1. No cookies are set until database configuration value for `/web/cookie/cookie_domain` is set to the correct domain

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2022-07-28 11:59
Hello @GamesmenJordan,

We have tried to reproduce the issue in Magento 2.4-develop branch but it seems that the issue is not reproducible for us. We have followed below steps in order to reproduce the issue:

Steps:
1. Edit `web/cookie/cookie_domain` with incorrect value, for us it is `.magento2ce9.org`.
2. Set the correct value in env.php file as below:
```
'web'   => [
        'cookie'    =>  [
            'cookie_domain' => '.magento2ce9.com'
        ]
    ]
```
3. Ran command `bin/magento app:config:import` & clear cache.
4. But we can see the cookies. Please refer to the below screenshot for reference:
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/51681618/181499584-4a01cd21-1180-4055-89e8-9509ae6c570d.png">

Please let us know in case we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2022-08-12 07:53
Dear @GamesmenJordan,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-08-12 07:53 UTC
Labels: Triage: Dev.Experience, Issue: needs update
