### ISSUE TITLE
Prices is not deleting for website after deselect that website

### ISSUE THREAD

**Issue by kumarsh178** [magento/magento2#35337] opened 2022-04-20 10:29 UTC
Step to reproduce:

Note:  Make the price website level first.

Step1> Create two websites with a different store.

Step2> Create a product with different prices for both websites and save after that deselect the second website for the product.

Step3> Export the product then you will see the prices of deleted website and even you will not see that deselect website in product edit page.

**Comment by engcom-November** [comment] 2022-04-22 11:36
Hi @kumarsh178 ,
Thank you for reporting and collaboration. Verified this on Magento 2.4-develop branch however this behavior seems to be expected behavior:
On setting the product to both the websites: "product_websites" column is updated with both website codes in exported file
On Setting a different price to other website and export - New row is create with price value of other website.
![image](https://user-images.githubusercontent.com/60198231/164706584-4e7f6544-dccc-4e34-9c93-8cf6ac69e1fd.png)

On deselecting the other website from Product edit page and exported - Website code is removed from "product_websites" column in exported file
![image](https://user-images.githubusercontent.com/60198231/164706703-67d6e95f-3239-45ac-8e23-c0666af8ad27.png)

Catalog - Products - Edit - User can still select other website and save. Previously saved different price is updated for other website
![image](https://user-images.githubusercontent.com/60198231/164706826-b3f6e82a-5a57-454a-ba3d-8e9cca15992b.png)

Kindly recheck the behavior on Magento 2.4-develop branch as it is having latest code base and provide your inputs on this.
Thank you.

**Comment by engcom-November** [comment] 2022-05-06 08:56
Hi @kumarsh178 ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-05-06 08:56 UTC
Labels: Issue: needs update
