### ISSUE TITLE
Tax calculation incorrect round up

### ISSUE THREAD

**Issue by Naberdz** [magento/magento2#26005] opened 2019-12-12 08:48 UTC
### Preconditions (*)

1.Magento 2.3.2
2.PHP 7.2

### Steps to reproduce (*)

1.Create an order with tax
2.

### Expected result (*)

1. tax applied to Subtotal should be correct
2.

### Actual result (*)

1. tax calculation is incorrect
2. we have order: with subtotal 80.64 apply 21% tax = 16.9344 ( rounded it should be 16.93) Magento gives us 16.94 this gives us 0.01 difference
3. this one is completely strange:
<img width="511" alt="Schermafbeelding 2019-12-12 om 09 42 30" src="https://user-images.githubusercontent.com/37579149/70696342-cbb41a80-1cc3-11ea-8a06-c7e3f7cefdee.png">
260-13=247*0,21=51.87 in Magento order it's 51.88

with this problem our invoice system ( we send order information to our invoice system )
this invoice remains as open since according to our system we have to repay customer 0.01 back
<img width="285" alt="Schermafbeelding 2019-12-12 om 09 47 13" src="https://user-images.githubusercontent.com/37579149/70696631-644a9a80-1cc4-11ea-9e1c-6bdc6be1958e.png">

**Comment by engcom-Echo** [comment] 2019-12-12 10:37
Hello @Naberdz 

Thank you for your report and collaboration!
I am not able to reproduce this issue on the 2.4-develop branch by provided steps.

**Testing scenario:**

**Preconditions:**

1. Tax rule created.
2. Cart price rule with coupon created.

**Steps to reproduce:**

1. Create an order with tax

**Result**
The tax applied to the Subtotal is correct
![Screenshot_12](https://user-images.githubusercontent.com/51681435/70705024-e4c8c580-1cdb-11ea-974a-57506bd2e15f.png)
![Screenshot_13](https://user-images.githubusercontent.com/51681435/70705080-07f37500-1cdc-11ea-9e6f-3fa1f3fdc0eb.png)

So I have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Echo** 2019-12-12 10:37 UTC
Labels: Issue: Format is valid

**Comment by Naberdz** [comment] 2019-12-12 10:45
really strange.. where is that 0.01 comes from then..
<img width="1111" alt="Schermafbeelding 2019-12-12 om 11 43 02" src="https://user-images.githubusercontent.com/37579149/70705616-a24fba80-1cd4-11ea-9658-3e4d11d050d4.png">

or was this bug only before 2.3.4 ?

can't update it to newer version due template restriction.
