### ISSUE TITLE
Magento (2.3.x) dependency causing fresh install error (the dependency contains a faulty constraint)

### ISSUE THREAD

**Issue by ninarosemary** [magento/magento2#26689] opened 2020-02-04 10:32 UTC
### Preconditions

1. Magento version 2.3.x
2. Composer version > 1.9.0

### Steps to reproduce
1. Create a new Magento 2.3.x project

### Expected result

1. A working Magento installation

### Actual result
I received the following error for both commands:

 "_Could not load package firebear/importexport in https://repo.magento.com [UnexpectedValueException] Could not parse version constraint 5.5.33 as ^5.2: Invalid version string "^5.2_".

### Workaround
After downgrading composer to version 1.8.6 I was able to install Magento again. I concluded that the newer versions of composer don't support the way the dependency constraint is defined in the firebear/importexport module, thus causing said error. Firebear depends on the tightenco/collect module. The dependency is defined in the magento packages.json as follows:

_tightenco\/collect":"5.5.33 as ^5.2"_

I'm surprised I have not found any bugreports regarding this issue. This not only happened to me but my colleaugues as well.

Thank you. 

Nina

**Comment by engcom-Hotel** [comment] 2020-02-06 12:02
Hello @ninarosemary 
I am not able to reproduce this issue with Composer v.1.9.0

**Testing scenario:**
1.Create a new Magento 2.3.4 project

**Result:**
Composer downloaded all the packages and I installed Magento 2.3.4:
![image](https://user-images.githubusercontent.com/51681618/73935340-fc41ba80-48e8-11ea-87b1-1ce9cb00a018.png)

So i have to close this issue.

Thanks for your report!

**Closed as completed by engcom-Hotel** 2020-02-06 12:02 UTC
Labels: Issue: Format is valid, Reported on 2.3.x

**Comment by ninarosemary** [comment] 2020-02-10 07:59
Hello @engcom-Hotel ,

As mentioned in the preconditions, a composer version is required **above** 1.9.0. Anything below this version does work with the packages.json.

Could you please try to reproduce this issue again?

**Comment by ainigma32** [comment] 2020-02-13 10:48
I am experiencing the exact same problem using composer 1.9.3
It looks like the version constraint that the good people of firebearstudio are using, has become invalid as of composer 1.9.2.
See #https://github.com/composer/composer/issues/8527#issuecomment-574552473

The [Magento docs](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html) mention that the latest stable version of composer should be used (at the moment that is 1.9.3) so as @ninarosemary asked: please retest using composer 1.9.3

At the moment I am using the https://repo-magento-mirror.fooman.co.nz as a workaround but I would prefer to use https://repo.magento.com

**Comment by hostep** [comment] 2020-02-13 11:04
So, since this seems to be a bug which was fixed in composer, this should remain closed as there is nothing in Magento which can fix this.

@ninarosemary, @ainigma32: please talk to the folks from firebear, they should fix this bug, Magento can't fix it and Composer won't fix it.

Thanks!

**Comment by hostep** [comment] 2020-02-13 11:07
@engcom-Hotel or @sdzhepa: can you talk to the people responsible for hosting the packages on repo.magento.com to search for that particular pattern where a range is being used as an alias, like `5.5.33 as ^5.2` in all packages on there?

And then to contact the maintainers of such packages, so they can fix that in a new version of their modules.

**Comment by ainigma32** [comment] 2020-02-13 11:44
Thanks @hostep

**Comment by nikolaevas** [comment] 2020-02-13 16:51
Hello @ninarosemary @ainigma32 @hostep,

We confirm that the problem is on our side. Few of our first module versions contain composer alias which is not working with composer 1.9.2. Now we trying to contact people responsible for marketplace so they can disable those versions. I will be back to you as soon as I get a response from the marketplace.

**Comment by TOIVI291** [comment] 2020-03-11 13:01
I also have this issue, is there any update on this?

**Comment by vinayshah** [comment] 2020-05-04 09:29
Hello ,

I tried to create a workaround without getting composer version downgraded. Maybe it can help 
[here](https://github.com/rapiddive/composer-version-constraint).

Thanks,
Vinay Shah
