### ISSUE TITLE
Issues saving CMS page assigned to Hierarchy

### ISSUE THREAD

**Issue by courtneyIndaba** [magento/magento2#10701] opened 2017-08-29 22:31 UTC
When saving a cms page that is assigned to the hierarchy, if you do not open the Hierarchy section, the cms page will be removed from the hierarchy. 

### Preconditions
1. Magento EE 2.1.8
2. PHP 7.0.15
3. MySQL 5.6.35

### Steps to reproduce
1.  Login to admin
2. Go to Content > Elements > Pages
3. Go to a cms page that is assigned to a Hierarchy
4. Without changing anything, save the CMS page (hierarchy section should be closed)
5. Go to CMS page on frontend > you will get a 404 page
6. Go back to the cms page in admin and review the Hierarchy section, you will see its been removed

### Expected result
1. Saving a CMS page assigned to a Hierarchy should not remove that page from the Hierarchy. 
2. You should not have to open the Hierarchy section of the cms page in order to successfully save the cms page

### Actual result
1. CMS page is removed from Hierarchy and page throws 404 on frontend

**Comment by korostii** [comment] 2017-08-31 13:20
Please note that Magento Commerce (formerly Enterprise Edition) issues can also be reported via the Support portal of your account (or via the Partner portal if you are a partner reporting on behalf of a merchant). 
That way, your issue should probably get acknowledged and solved faster. GitHub is intended for the Magento Open Source (formerly Community Edition) issue reports.

This also seems to be a duplicate of #9971. Please see that issue, there seems to be a temporary fix suggested in comments.

**Comment by magento-engcom-team** [comment] 2017-09-14 09:05
@courtneyIndaba, thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways: 
You can use the Support portal associated with your account or If you are a Partner reporting on behalf of a merchant, use the Partner portal. 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Closed as completed** 2017-09-15 10:10 UTC
Labels: bug report, Issue: Format is valid
