### ISSUE TITLE
Graphql API needs anonymous access protection

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#28567] opened 2020-06-05 14:02 UTC
**ISSUE:**
GraphQL Apis can't block for anonymous usage.

Merchant has restricted anonymous API access from the Admin but it can still query.

**STEPS TO REPLICATE:**
Post GraphQL as anoymous.
```
mutation {
  createCustomer(
    input: {
      firstname: "John"
      lastname: "Doe"
      email: "john.doe@example.com"
      password: "b1b2b3l@w+"
      is_subscribed: true
    }
  ) {
    customer {
      firstname
      lastname
      email
      is_subscribed
    }
  }
}
```

**ACTUAL RESULTS:**
Return body.

```
{
    "data": {
        "createCustomer": {
            "customer": {
                "firstname": "John",
                "lastname": "Doe",
                "email": "john.doe@example.com",
                "is_subscribed": true
            }
        }
    }
}
```

**EXPECTED RESULTS:**
Return 0

**NOTICE**

Is there a way I can stop this since I was recently informed by a Bounty Hunter that they could look up our customers doing a hit and miss query with the Customer Creation query available for Graphql and match it with publicly available email accounts an then run a rainbow table password guesser to login to the customers account.

**Comment by magento-engcom-team** [comment] 2020-06-16 11:12
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-34502).

**Comment by magento-engcom-team** [comment] 2020-06-16 11:13
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-34502).

**Comment by magento-engcom-team** [comment] 2020-06-16 11:13
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-34502).

**Comment by magento-engcom-team** [comment] 2020-06-16 11:14
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-34502).

**Comment by magento-engcom-team** [comment] 2020-06-16 11:14
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-34502).

**Comment by magento-engcom-team** [comment] 2020-06-16 11:15
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-34502).

**Comment by magento-engcom-team** [comment] 2020-06-16 14:45
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-34502).

**Comment by magento-engcom-team** [comment] 2020-06-16 14:45
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-34502).

**Comment by magento-engcom-team** [comment] 2020-06-16 14:46
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-34502).

**Comment by vkolesny** [comment] 2020-08-25 16:27
According to the Product Owner comments this issue is considered as Not a Bug, and escalated L3 issue was closed as Won't Fix as well (MC-34502):

**Product Owner's clarification:**
_Creating a customer is meant to be a public API so that a new customer can create an account without requiring authorization. Unfortunatelly there is nothing we can do it at the GraphQL layer.
It looks like this is by design behavior and we cannot make this API request anonymous since creating a customer is meant to be a public API so that a new customer can create an account without requiring authorization._

**Closed as completed by vkolesny** 2020-08-25 16:27 UTC
Labels: Issue: Format is not valid, Reproduced on 2.4.x, Priority: P1, Project: GraphQL, PAP
