### ISSUE TITLE
Field msrp_display_actual_price_type exported in non-importable format

### ISSUE THREAD

**Issue by YiffyToys** [magento/magento2#23921] opened 2019-07-27 13:35 UTC
### Preconditions (*)
1. Magento 2.3.2
2. Products present

### Steps to reproduce (*)
1. Export products.
2. import the downloaded CSV file as is

### Expected result (*)
Exported format should be accepted for import too.

### Actual result (*)

The field "msrp_display_actual_price_type" exports as the numerical value "4"
but in import requires the string value "Use config" and rejects the numerical value.

**Comment by engcom-Charlie** [comment] 2019-07-29 07:35
Hi @YiffyToys ! I can't reproduce this issue on fresh Magento 2.3-develop. 

**Manual testing scenario:**

1.Login to admin
2.Go to System->Export
3.Select "Entity Type" value = products and "Export File Format" value = CSV
4.Find "msrp_display_actual_price_type" and set value = "Use config"
5.Press "Continue" button and download a file
6.Open this file

**Actual result:**
![image](https://user-images.githubusercontent.com/51680850/62029846-56501d80-b1ec-11e9-9fe1-44396626667e.png)

So i close this issue.
If you have some updates please write it in answer.
Thank you for contributing!

**Closed as completed by engcom-Charlie** 2019-07-29 07:35 UTC
Labels: Component: ImportExport, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid

**Comment by YiffyToys** [comment] 2019-07-29 10:30
![Unbenannt](https://user-images.githubusercontent.com/52350973/62041611-59eba080-b1fc-11e9-9cc1-0b797ffbf249.PNG)

Reproducable on my 2.3.2 . I'll investigate. 
Can the ATmagento  -bot produce a 2.3.2 or just the -develop snapshots?

**Comment by engcom-Charlie** [comment] 2019-07-29 10:34
@YiffyToys bot can't do it but you can try to reproduce on magento 2.3-develop instance.
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-29 10:34
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-29 10:35
Hi @engcom-Charlie, here is your [Magento instance](https://i-23921-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23921-2-3-develop.instances.magento-community.engineering/admin](https://i-23921-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment] 2019-07-29 10:38
@YiffyToys use it please:
Admin access: https://i-23921-2-3-develop.instances.magento-community.engineering/admin
Login: admin Password: 123123q
Instance will be terminated in up to 3 hours.

**Comment by YiffyToys** [comment] 2019-07-29 10:53
Ok. I'll be able to try it tonight (in about 7-8 hours)

**Comment by engcom-Charlie** [comment] 2019-07-29 10:57
@YiffyToys , thats ok, but this instance will be terminated in up to 3 hours. But 
you can request another one when it will be convenient for you
