### ISSUE TITLE
addExpressionFieldToSelect with group by

### ISSUE THREAD

**Issue by tegos** [magento/magento2#10289] opened 2017-07-20 06:08 UTC
### Preconditions
1. Magento ver. 2.1.2
2. MySQL  5.6.35

### Steps to reproduce
1. Creating collection
2. using `->addExpressionFieldToSelect('g_total', 'SUM({{total}})', 'total');`
3. adding grouping `->getSelect()->group('group_id');`

### Expected result
example:
data in row 
total **83.3**

### Actual result
`["g_total"]=>   string(17) "83.30000305175781"`

**Comment by magento-engcom-team** [comment] 2017-09-21 11:58
@Tegos, thank you for your report.
We were not able to reproduce this issue by following the steps you provided.
Please, give detailed steps to reproduce: 
- what collection do you use (give all needed code for reproducing)? 
- what is your database filled up with?

Note: try to reproduce it on 2.1.9.

**Comment by tegos** [comment] 2017-09-21 14:41
Thank you very much.
But seems it is a problem MySQL not Magento.
Sorry for your time.

![2017-09-21_17-29-41](https://user-images.githubusercontent.com/7047662/30701790-d90a6a40-9ef3-11e7-9213-ba6e513fc0ae.png)

![2017-09-21_17-28-45](https://user-images.githubusercontent.com/7047662/30702079-9d53b848-9ef4-11e7-93da-64ea3d902144.png)

![2017-09-21_17-31-23](https://user-images.githubusercontent.com/7047662/30701792-d962d810-9ef3-11e7-86a7-b1f281e83312.png)

**Comment by tegos** [comment] 2017-09-21 14:43
![2017-09-21_17-42-42](https://user-images.githubusercontent.com/7047662/30702007-6e9d960e-9ef4-11e7-8a10-10a2010b0930.png)

**Comment by magento-engcom-team** [comment] 2017-09-21 14:46
@Tegos Closing this ticket per your comment.
Thank you.

**Closed as completed by magento-engcom-team** 2017-09-21 14:46 UTC
Labels: bug report, Progress: needs update, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid

**Comment by magento-engcom-team** [comment] 2017-09-21 19:06
@Tegos, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9
