### ISSUE TITLE
Merge CSS Causes Slow Admin 

### ISSUE THREAD

**Issue by gahinton** [magento/magento2#4710] opened 2016-05-25 20:01 UTC
If you enable Merge CSS, it drastically affects the performance of the Admin section. Without Merge CSS enabled, admin pages load in less than 1 second. With Merge CSS enabled, admin pages sometimes take 2+ minutes to load. The benefits of enabling are definitely not worth the inconveniences!

**Comment by piotrekkaminski** [comment] 2016-05-27 17:19
We are aware of this issue. Internal issue ID: MAGETWO-53223

**Comment by stevekem** [comment] 2016-05-28 01:42
https://github.com/magento/magento2/issues/4321

**Comment by liquidia** [comment] 2016-05-28 14:18
Please note its not only  admin but front end gets slow down too . i am running latest version 2.07

**Comment by andidhouse** [comment] 2016-05-29 10:21
i can confirm that merging css or / and javascript has destroyed our installation (2.0.7.) - tested twice.
After merging very slow front and backend and the system can't find the merged css and javascript files.

no way to turn this back i think... so for now: 
DO NOT USE THIS OPTIONS AS IT WILL MAYBE KILL YOUR INSTALLATION.

**Comment by pynej** [comment] 2016-06-03 19:39
Makes the frontend really slow as well.

**Comment by shiftedreality** [comment] 2016-06-09 07:50
Fix was merged to develop branch.
Closed.

**Comment by pynej** [comment] 2016-06-09 13:24
Also https://github.com/magento/magento2/issues/4321 was a dup.

Is there a commit I can reference for the changes so I can apply them to my site ahead of the next release.

**Comment by shiftedreality** [comment] 2016-06-10 09:06
Ah, it looks like internal M2 repository was not synchronized with public yet.
Reopened until fix is delivered to public magento/magento2

**Comment by shiftedreality** [comment] 2016-06-13 08:13
@pynej please check 64d7dfef8718ecb9be64807071360ac97f570862

**Comment by pynej** [comment] 2016-06-13 14:10
Yes, that fixes it for JS files.  The same result still happens(Single large 15MB file is generated) when enabling Enable Javascript Bundling though.  There is a separate issue for this but they may be related.

**Comment by shiftedreality** [comment] 2016-06-21 07:41
Yeap, you can open a new ticket for that issue if it still reproducible and was not tracked.
Closed.

**Closed as completed by shiftedreality** 2016-06-21 07:41 UTC
Labels: bug report
