### ISSUE TITLE
M 2.4.4: Error 'TypeError: $(...).filter(...).collapse is not a function' (in admin/backend > dev-tools console) - Cant save pages

### ISSUE THREAD

**Issue by FadedOut** [magento/magento2#35322] opened 2022-04-18 17:41 UTC
SOLUTION [HERE](https://github.com/magento/magento2/issues/35322#issuecomment-1101788078). Thanks to @emirajbbd for fix info! I patched the files if you'd prefer, [here](https://github.com/magento/magento2/issues/35322#issuecomment-1102068845).

### Preconditions (*)
1. Upgraded from 2.4.3-p1 to 2.4.4
2. PHP 8.1.4
3. Production Mode
4. No custom modifications to backend template/files

### Steps to reproduce (*)
1. I upgraded from 2.4.3-p1 and this issue did not exist [on 2.4.3-p1]. Not sure if the upgrade broke this
2. Browse any backend page (primarily pages with collapsible objects, like the configuration/settings page)
5. Check dev-tools>console

### Expected result (*)
1. No error in dev-tools (console log)
2. Pages load first time
3. Can save page/settings

### Actual result (*)
1. These errors shows in dev-tools>console on every admin page (except dashboard). 
2. Some pages are mostly broken in general (cannot click collapsible buttons or click save to save pages)
3. Also seems to affect some pages to not load first time around requiring a reload.
4. I think it's because of these errors

Error (from: /adminhtml/Magento/backend/en_US/js/theme.min.js)
```
Uncaught TypeError: $(...).filter(...).collapse is not a function
    at HTMLDivElement.<anonymous> (theme.min.js:8:3737)
    at Function.each (jquery.min.js:30:217)
    at theme.min.js:8:3609
    at Object.execCb (require.min.js:117:195)
    at Module.check (require.min.js:59:495)
    at Module.<anonymous> (require.min.js:76:35)
    at require.min.js:12:51
    at require.min.js:78:76
    at each (require.min.js:4:77)
    at Module.emit (require.min.js:78:40)
```
Related errors on every page in dev-tools>console (coming from:
/adminhtml/Magento/backend/en_US/jquery/bootstrap/tab.min.js
/adminhtml/Magento/backend/en_US/jquery/bootstrap/collapse.min.js)
```
Uncaught SyntaxError: Unexpected token 'const' (at tab.min.js:4:31)
Uncaught SyntaxError: Unexpected token 'const' (at collapse.min.js:4:31)
```

Received these errors on creating/editing [dropdown] attribute:
```
jQuery.Deferred exception: $(...).collapsable(...).collapse is not a function TypeError: $(...).collapsable(...).collapse is not a function
    at HTMLDocument.<anonymous> (.../adminhtml/Magento/backend/en_US/Magento_Swatches/js/product-attributes.min.js:12:536)
    at mightThrow (.../adminhtml/Magento/backend/en_US/jquery.min.js:238:18)
    at process (.../adminhtml/Magento/backend/en_US/jquery.min.js:240:89) undefined
```
```
Uncaught TypeError: $(...).collapsable(...).collapse is not a function
    at HTMLDocument.<anonymous> (product-attributes.min.js:12:536)
    at mightThrow (jquery.min.js:238:18)
    at process (jquery.min.js:240:89)
```

I've cleared cache (browser/all using Magento backend/running commands like "bin/magento cache:clean ; php bin/magento cache:flush ; rm -rf var/cache/* ; rm -rf var/page_cache/* ; rm -rf var/view_preprocessed/* ; rm -rf pub/static/* ; rm -rf generated/code/* ; rm -rf generated/metadata/*") I've also made sure to run "bin/magento setup:static-content:deploy". All checks out, but these errors persists in the dev-tools>console. I'm guessing it's from the JQuery 3.6 upgrade.

I don't know how to fix even if it's not happening on a clean install of M 2.4.4 (may not be happening on a clean 2.4.4). Anyone else have this issue or know how to fix? It's getting annoying not being able to save pages (like settings) or needing a reload to get them to actually load/show. This error did not exist on 2.4.3-p1 prior to upgrade.

TIA

EDIT: Edited to add more info/new info/new error codes to help narrow down problem (hopefully).
EDIT2: Added solution info/links to top of this report.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by FadedOut** [comment] 2022-04-18 17:43
@magento give me 2.4-develop instance

**Comment by Hanhan1989** [comment] 2022-04-18 18:49
I think that These errors are due to the minification of the collapse.js and tab.js files in the lib/web/jquery/bootstrap/ path. The temporary solution would be to exclude these two files from the minification。

**Comment by FadedOut** [comment] 2022-04-18 18:59
@Hanhan1989 Thank you for your response 🙂

I'm running in Production Mode (just updated OP with that info - I apologize for not mentioning that) which I believe there is no way to enable/disable minification (no developer setting in configuration)? Especially not sure how I would go about excluding those files only...

**Comment by Hanhan1989** [comment] 2022-04-18 19:03
@FadedOut I did this solution。

<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Store:etc/config.xsd">
    <default>
        <dev>
            <js>
                <minify_exclude>
                    <collapse>/jquery/bootstrap/collapse</collapse>
                    <tab>/jquery/bootstrap/tab</tab>
                </minify_exclude>
            </js>
        </dev>
    </default>
</config>

**Comment by Hanhan1989** [comment] 2022-04-18 19:05
@FadedOut My did the following solution: 

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Store:etc/config.xsd">
    <default>
        <dev>
            <js>
                <minify_exclude>
                    <collapse>/jquery/bootstrap/collapse</collapse>
                    <tab>/jquery/bootstrap/tab</tab>
                </minify_exclude>
            </js>
        </dev>
    </default>
</config>
```
This is the temporary solution.

**Comment by emirajbbd** [comment] 2022-04-18 21:36
diff --git a/lib/web/jquery/bootstrap/tab.js b/lib/web/jquery/bootstrap/tab.js
index 928f8de..9805d0b 100644
--- a/lib/web/jquery/bootstrap/tab.js
+++ b/lib/web/jquery/bootstrap/tab.js
@@ -28,14 +28,14 @@ define([
     const VERSION = '5.1.3'
     const NAME = 'tab'
     const DATA_KEY = 'bs.tab'
-    const EVENT_KEY = `.${DATA_KEY}`
+    const EVENT_KEY = `.${DATA_KEY}`;
     const DATA_API_KEY = '.data-api'

-    const EVENT_HIDE = `hide${EVENT_KEY}`
-    const EVENT_HIDDEN = `hidden${EVENT_KEY}`
-    const EVENT_SHOW = `show${EVENT_KEY}`
-    const EVENT_SHOWN = `shown${EVENT_KEY}`
-    const EVENT_CLICK_DATA_API = `click${EVENT_KEY}${DATA_API_KEY}`
+    const EVENT_HIDE = `hide${EVENT_KEY}`;
+    const EVENT_HIDDEN = `hidden${EVENT_KEY}`;
+    const EVENT_SHOW = `show${EVENT_KEY}`;
+    const EVENT_SHOWN = `shown${EVENT_KEY}`;
+    const EVENT_CLICK_DATA_API = `click${EVENT_KEY}${DATA_API_KEY}`;

     const CLASS_NAME_DROPDOWN_MENU = 'dropdown-menu'
     const CLASS_NAME_ACTIVE = 'active'


And

diff --git a/lib/web/jquery/bootstrap/collapse.js b/lib/web/jquery/bootstrap/collapse.js
index 95e28ce..2f3fbdb 100644
--- a/lib/web/jquery/bootstrap/collapse.js
+++ b/lib/web/jquery/bootstrap/collapse.js
@@ -32,7 +32,7 @@ define([
     const VERSION = '5.1.3'
     const NAME = 'collapse'
     const DATA_KEY = 'bs.collapse'
-    const EVENT_KEY = `.${DATA_KEY}`
+    const EVENT_KEY = `.${DATA_KEY}`;
     const DATA_API_KEY = '.data-api'

     const Default = {
@@ -45,17 +45,17 @@ define([
         parent: '(null|element)'
     }

-    const EVENT_SHOW = `show${EVENT_KEY}`
-    const EVENT_SHOWN = `shown${EVENT_KEY}`
-    const EVENT_HIDE = `hide${EVENT_KEY}`
-    const EVENT_HIDDEN = `hidden${EVENT_KEY}`
-    const EVENT_CLICK_DATA_API = `click${EVENT_KEY}${DATA_API_KEY}`
+    const EVENT_SHOW = `show${EVENT_KEY}`;
+    const EVENT_SHOWN = `shown${EVENT_KEY}`;
+    const EVENT_HIDE = `hide${EVENT_KEY}`;
+    const EVENT_HIDDEN = `hidden${EVENT_KEY}`;
+    const EVENT_CLICK_DATA_API = `click${EVENT_KEY}${DATA_API_KEY}`;

     const CLASS_NAME_SHOW = 'show'
     const CLASS_NAME_COLLAPSE = 'collapse'
     const CLASS_NAME_COLLAPSING = 'collapsing'
     const CLASS_NAME_COLLAPSED = 'collapsed'
-    const CLASS_NAME_DEEPER_CHILDREN = `:scope .${CLASS_NAME_COLLAPSE} .${CLASS_NAME_COLLAPSE}`
+    const CLASS_NAME_DEEPER_CHILDREN = `:scope .${CLASS_NAME_COLLAPSE} .${CLASS_NAME_COLLAPSE}`;
     const CLASS_NAME_HORIZONTAL = 'collapse-horizontal'

     const WIDTH = 'width'
@@ -204,7 +204,7 @@ define([
         }

         const capitalizedDimension = dimension[0].toUpperCase() + dimension.slice(1)
-        const scrollSize = `scroll${capitalizedDimension}`
+        const scrollSize = `scroll${capitalizedDimension}`;

         this._queueCallback(complete, this._element, true)
         this._element.style[dimension] = `${this._element[scrollSize]}px`
@@ -222,7 +222,7 @@ define([

         const dimension = this._getDimension()

-        this._element.style[dimension] = `${this._element.getBoundingClientRect()[dimension]}px`
+        this._element.style[dimension] = `${this._element.getBoundingClientRect()[dimension]}px`;

         reflow(this._element)



Fixed the issue for me.

**Comment by FadedOut** [comment] 2022-04-18 22:36
@Hanhan1989 Thank you for posting that info. Unfortunately, I might sound like a noob here but I'm not sure which module to place that into...seeing how it appears to be every part of the admin panel and not one specific module. Unless it is one specific module that controls all that?

@emirajbbd Woo thank you for that but unfortunately that is above my paygrade (so-to-speak) lol. I don't know how to do diff changes to magento files. Would there be any way to get the files already fixed/patched that I could just drop in for replacement? I realize that is usually probably not the correct process but I'm thinking they would get replaced on any consequential update anyway - so it shouldn't matter?

**Comment by VZeroCool** [comment] 2022-04-19 04:59
@magento give me 2.4-develop instance

**Comment by FadedOut** [comment] 2022-04-19 05:18
@emirajbbd I looked at your response better and decided to just take a look at the files. I was able to decipher it lol. I just manually edited the files.

MUCH appreciate the response. IT WORKED 😃! As you noted it fixed it for you, it seems to have fixed it for me as well. I no longer have those errors I mentioned in the OP and it seems the broken pages are now working as intended. Yay 👍

I will upload the files patched here, for any one else that runs into this problem. I assume just replacing them will be fine for now. Keeping the same filenames (you'd have to anyway) means they should get updated in the future with any 'composer update' so there should be no harm in simply replacing them. BUT I'd make a backup (like _old.js) first. 

I don't think I'll close this just yet, lets get the devs to see this fix first. @engcom-November 

FILES (make BACKUP of yours FIRST):
[collapse.zip](https://github.com/magento/magento2/files/8509996/collapse.zip) place here [/lib/web/jquery/bootstrap/]
[tab.zip](https://github.com/magento/magento2/files/8510006/tab.zip) place here [/lib/web/jquery/bootstrap/]


Thanks again @emirajbbd

**Comment by Hanhan1989** [comment] 2022-04-19 08:07
the issue is confirmed here https://github.com/magento/magento2/issues/35325

**Comment by engcom-November** [comment] 2022-04-19 12:07
Hi @FadedOut , Thank you for reporting and collaboration.
Verified the issue by upgrading from 2.4.3-p1 to 2.4.4 in production mode and PHP version: 8.1.4 and also on 2.4.4 new installation but cannot able to reproduce the issue. No error in console and all pages in admin are working.
Please check and confirm if this issue occurred due to configuring [JS bundling](https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/themes/js-bundling.html) as the similar console error is reported here https://github.com/magento/magento2/issues/35325 and confirmed.
Temporary work around would be to disable JS bundling from CLI to resolve this issue. 
`php bin/magento config:set dev/js/enable_js_bundling 0`
Please recheck and elaborate steps to reproduce if issue still exists or is a different issue from above.
Thank you.

**Comment by emirajbbd** [comment] 2022-04-19 15:41
@[engcom-November](https://github.com/engcom-November) it happens in production mode while you have Minify JavaScript Files on

**Comment by FadedOut** [comment] 2022-04-19 16:22
Hello @engcom-November 

I appreciate you inspecting this. @emirajbbd just pointed out the minify suggestion. This appears to be correct. It does not appear to be a problem with 'bundling' but with 'minification'. Following the dev guide [HERE](https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/themes/js-bundling.html) to enable/disable.

OP Errors SHOW:
```
'enable_js_bundling' => '0',
'minify_files' => '1',
'merge_files' => '0'

'static' => [
'sign' => '1'
]
```

 OP Errors GONE:
```
'enable_js_bundling' => '1',
'minify_files' => '0',
'merge_files' => '0'

'static' => [
'sign' => '1'
]
```

 OP Errors GONE:
```
'enable_js_bundling' => '0',
'minify_files' => '0',
'merge_files' => '1'

'static' => [
'sign' => '1'
]
```

**Comment by engcom-November** [comment] 2022-04-20 07:57
Thank you for the confirmation @FadedOut.
We are closing this issue as duplicate as its confirmed here: https://github.com/magento/magento2/issues/35325. Please move on to this ticket for latest updates/solutions.
Thank you.

**Closed as completed by engcom-November** 2022-04-20 07:57 UTC
Labels: duplicate, Issue: needs update, Reported on 2.4.4
