### ISSUE TITLE
Attribute default value data saving 

### ISSUE THREAD

**Issue by cedcommerce** [magento/magento2#4357] opened 2016-04-30 13:15 UTC
We have seen the eav structure used for storing the attributes value in magento 2. We are using different type of tables for storing the attribute value according to their data type.
But we noticed that like we have a product attribute "custom_attr" with default value like 'test'.
When we saved a product but did not set any value for the field "custom_attr" then we seen that in the table "catalog_product_entity_varchar"  for that product it is saving value 'NULL' for that attribute.
Here we did not find the reason why we are storing the data for that attribute as 'NULL'.
And if we have thousands of product and many attributes. Then there will be lots of entry in the database for 'NULL' values. And it will surely affect database performance.

**Comment by veloraven** [comment] 2016-11-01 15:01
@cedcommerce is this issue still actual?
If it is please describe detailed steps, actual result and expected result.
If it is not, please close it.
If it is more question than an issue please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) as GitHub issue tracker is intended for technical issues only.

**Comment by veloraven** [comment] 2016-11-23 08:11
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Closed as completed by veloraven** 2016-11-23 08:11 UTC
Labels: Progress: needs update
