### ISSUE TITLE
REST API - duplicate SKU in database

### ISSUE THREAD

**Issue by forcecodema** [magento/magento2#30893] opened 2020-11-12 09:07 UTC
### Preconditions (*)

1. Stock Magento 2.4.1 - no mods

### Steps to reproduce (*)

1. /rest/all/async/bulk/V1/products/ API call with one product payload
2. This is how I create payload - $item is the product from external system, $data_string is sent to endpoint
```
$product = [
	'product' => [
		'sku' => $item['catalog_no'],
		'name' => $item['name'],
		'type_id' => 'simple',
		'attribute_set_id' => 4,
		'price' => $item['final_gross_price'],
		'weight' => $item['weight'],
		'status' => 1,
		'visibility' => 1,
		'extension_attributes' => [
			'stock_item' => [
				'qty' => $item['stock'],
				'is_in_stock' => ($item['stock'] > 0)
			]
		],
		'custom_attributes' => [
			[
				'attribute_code' => 'description',
				'value' => $item['description']
			],
			[
				'attribute_code' => 'category_ids',
				'value' => [$item['category_id']]
			]
		]
	]
];

$payload = [$product];

$data_string = json_encode($payload);
```

### Expected result (*)

1. One product in catalog

### Actual result (*)

1. Duplicated SKU in catalog - two entries with the same SKU
2. Tried with (default) /rest/default/async/bulk/V1/products/ - same result

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dverkade** [comment] 2021-04-18 20:15
Posting a comment. Issues should not be automatically closed.

**Comment by engcom-Lima** [comment] 2021-06-07 14:06
Hi @forcecodema 

Unfortunately can't reproduce issue.

Please find the screenshot.
<img width="1054" alt="Screenshot 2021-06-07 at 6 38 48 PM" src="https://user-images.githubusercontent.com/60198022/121030943-8fce1880-c7c7-11eb-804a-eca81930933b.png">

Hence, closing this ticket. please feel free to raise the new ticket or reopen the existing ticket if you have any concern.

Thanks

**Closed as completed by engcom-Lima** 2021-06-07 14:06 UTC
Labels: Triage: Dev.Experience, Issue: ready for confirmation
