### ISSUE TITLE
Css file content can't read in pub after less compile

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#25545] opened 2019-11-10 04:40 UTC
I have my posted in magento.stackexchange.com
Here is the link for references
https://magento.stackexchange.com/questions/294982/css-cant-read-content-in-new-area-code-for-theme-deploy 
Basically i create new area code but can't deploy static  contents of less file

### Preconditions (*)

1. Local development used in dockerize
https://github.com/clean-docker/Magento2
2. Ubuntu 18.10
3. Magento 2.3.3 Open source
4. Sample data included (Optional)
5. Set Magento in developer mode
6. No symlink enabled
7. Server side compiling enabled
8. All files have write rights

### Steps to reproduce (*)

1. Create new area code (called vendors) instead adminhtml or frontend
followed guide here
https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/admin_theme_apply.html
2. Create new theme work with new areacode created with no parent inherritance
3. Create basics less styles there
4. Run deploy static-contents

### Expected result (*)

1. content should deploy successfull

### Actual result (*)

1 Got error with message can't read content of css file

**Comment by sudheers-kensium** [comment] 2019-11-11 09:58
@mrtuvn After static-contents deploy give permission to pub folder. 

Can I close this issue?

**Comment by mrtuvn** [comment] 2019-11-11 15:04
@sudheers-kensium i'm used account www-data for all commands so all issue related with permission is not a problem. I am sure pub have write permissions

**Comment by sudheers-kensium** [comment] 2019-11-12 08:25
@mrtuvn I am not able to reproduced in Magento 2.3.3 instance.

**Comment by mrtuvn** [comment] 2019-11-12 08:28
Seem problem not from magento . Just change some content of my less files and problem not happen again. **Some less file with empty selector declare rule got issue with compile**

**Closed as completed** 2019-11-12 08:48 UTC
Labels: Issue: Format is valid
