### ISSUE TITLE
Injection of an attribute on product recently view doesn't work

### ISSUE THREAD

**Issue by alexmtch** [magento/magento2#26463] opened 2020-01-20 15:38 UTC
### Summary
Hello, i followed this topic [https://magento.stackexchange.com/questions/278142/magento-2-add-new-attribute-delivery-time-to-recently-viewed-widget](url) to add a custom attribute but it doesn"t works.

### Information on your environment

Magento 2.3.3

### Steps to reproduce

Follow this [https://magento.stackexchange.com/questions/278142/magento-2-add-new-attribute-delivery-time-to-recently-viewed-widget](url) to add a custom attribute to recently viewed product widget. You'll se it doesn't works.

### Expected and actual results

Expected : Display of my attribute
Actual result : No display of my attribute

### Some research about the problem

After few search i found out a strange case. On the getParsedDataFromServer method from the vendor/magento/module-catalog/view/frontend/web/js/product/storage/data-storage.js file.

- Add "console.log(result[item.id]);" after result[item.id] = item;
- Add "console.log(result);" just before the return.

I see on chrome (71.0.3578.98) 2 set of different dump. On the first log, i got the correct datas. On the second it's slightly different. I got new added datas like "added_at" and my custom attribute on extension_attributes got removed. I just can't understand how this could happend by the way of the scope of the result variable.

I got not log on Firefox (72.0.1)

Do you have an idea if it's a bug or something else ?

**Comment by alexmtch** [comment] 2020-01-22 10:08
I updated the structure

**Comment by engcom-Hotel** [comment] 2020-01-30 12:44
Hello @alexmtch 

I used [this guide](https://magento.stackexchange.com/questions/278142/magento-2-add-new-attribute-delivery-time-to-recently-viewed-widget) for testing and i am not able to reproduce this issue on the latest Magento 2.4-develop.

**Result:**
I am able to add my custom attribute(SKU) to recently viewed widget: 
![1](https://user-images.githubusercontent.com/51681618/73450577-592ff480-436e-11ea-86a1-b1981b899810.png)
And it visible on frontend:
![image](https://user-images.githubusercontent.com/51681618/73450564-503f2300-436e-11ea-9feb-e3486a6db697.png)

So i have to close this issue as not reproducible.

Thanks for your report!

**Closed as completed by engcom-Hotel** 2020-01-30 12:44 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is not valid, Reported on 2.3.3
