### ISSUE TITLE
Navigation arrows zoomed fotorama disappear

### ISSUE THREAD

**Issue by luukschakenraad** [magento/magento2#18585] opened 2018-10-13 11:40 UTC
### Preconditions (*)
1. Magento 2.2.6
2. Magento sample data
3. Luma theme active

### Steps to reproduce (*)
1. Go to category Women -> Tops -> Jackets 
2. Open product "Olivia 1/4 Zip Light Jacket"
3. Click on the large product image on the left

### Expected result (*)
1. I expect to see navigation arrows
2. I expect them to stay visible when navigating through images
3. I expect the navigation arrows in the non-zoomed fotorama to stay visible after closing the zoomed fotorama 

### Actual result (*)
1. I do not see navigation arrows
2. After I click on a thumbnail, the navigation arrows become visible. After I click on a different thumbnail, they disappear again. And so on.
3. After closing the zoomed fotorama with no visible navigation arrows, they are also invisible on the non-zoomed fotorama.

**Comment by magento-engcom-team** [comment] 2018-10-13 11:41
Hi @luukschakenraad. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@luukschakenraad do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-10-17 13:35
Hi @luukschakenraad. Thank you for your report. 
The issue has been fixed in magento/magento2#18595 by @luukschakenraad in 2.2-develop branch
Related commit(s):
 - [ad09de9f80ff70a2bb4e6a22bce9eabeda40812b](https://github.com/magento/magento2/commit/ad09de9f80ff70a2bb4e6a22bce9eabeda40812b)
 - [e031bdc1007a980150635b2681880ac4475dd71a](https://github.com/magento/magento2/commit/e031bdc1007a980150635b2681880ac4475dd71a)

The fix will be available with the upcoming 2.2.8 release.

**Closed as completed by magento-engcom-team** 2018-10-17 13:35 UTC
Labels: Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by okorshenko** [comment] 2018-10-31 20:08
Hi @luukschakenraad. Thank you for your report. 
The issue has been fixed in magento/magento2#18590 by @luukschakenraad in 2.3-develop branch
Related commit(s):
 - [96507df2629a67616931f8aa404b5b2cf6f5440a](https://github.com/magento/magento2/commit/96507df2629a67616931f8aa404b5b2cf6f5440a)
 - [623a6b01330545582c3337813d803691faefef87](https://github.com/magento/magento2/commit/623a6b01330545582c3337813d803691faefef87)

The fix will be available with the upcoming 2.3.1 release.
