### ISSUE TITLE
Filtered results not saving

### ISSUE THREAD

**Issue by TalibSaifi003** [magento/magento2#38579] opened 2024-04-04 12:09 UTC
### Preconditions and environment

Hii
We are using Magento version 2.4.3-p1 enterprises edition
we are getting issues with filtering data at admin.
please check the loom video
https://www.loom.com/share/195011ba78784103b4ec9a5506482140?sid=6da5a7bc-5abe-4a82-8bd4-4248566da0e4

### Steps to reproduce

go to admin open the product page find any product through filter functionality then try to refresh the page

### Expected result

filter result should be show after refresh

### Actual result

all data is showing after refresh

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-04-05 05:36
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-04-05 06:36
Hi @TalibSaifi003,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.


**Steps to reproduce**


- go to admin open the product page find any product through filter functionality then try to refresh the page


https://github.com/magento/magento2/assets/51680745/438e91f2-8c9c-4b94-be1c-c8e0ead3df76


only filter result is showing after refresh.

Kindly check the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by TalibSaifi003** [comment] 2024-04-08 12:11
Hii @engcom-Bravo 
we are getting issues with 2.4.3-p1,2..4.3 can you please check once on a similar version?

Thanks

**Comment by engcom-Bravo** [comment] 2024-04-10 06:33
Hi @TalibSaifi003,

Thanks for your update.

It is recommended to verify the issues in Latest 2.4-develop instance and it might be issue has been fixed in Latest branch.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-04-16 05:09
Hi @TalibSaifi003,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-04-16 05:09 UTC
Labels: Issue: needs update, Reported on 2.4.3-p1
