### ISSUE TITLE
Name fields in customer register form appear to not be cached per website

### ISSUE THREAD

**Issue by Danielc3** [magento/magento2#12414] opened 2017-11-23 11:50 UTC
When changing the config field Show Prefix (customer/address/prefix_show) on a specific website scope I have noticed that it is necessary to clean the cache when changing between websites and viewing the customer register form. This would suggest that the Widget Name block is not uniquely cached per website - or a parent block. 

### Preconditions
1. Magento 2.2.1

### Steps to reproduce
1. Set up Magento with multiple websites.
2. On the default scope in Stores > Configuration ensure that Show Prefix is set to Opt.
2. Visit the non-default website in the Stores > Configuration and set Show Prefix to No.
3. On the store front go to the customer register page on the default website.
4. Now change website to the non-default one and view the customer register page.

### Expected result
1. We would expect when viewing the customer register page on the default website to see the Prefix field as an optional field, then when changing to the non-default website to not see it.

### Actual result
1. What we actually end up seeing is that the Prefix field is shown on both. However when clearing the cache on the non-default website it is then not shown.

**Updated on December 7, 2018:**
[actual result](https://user-images.githubusercontent.com/11827230/49648799-1a7b0480-fa1f-11e8-9ffd-983881e0f735.gif)

**Comment by magento-engcom-team** [comment] 2017-11-23 14:02
@Danielc3  ,thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation

**Comment by Danielc3** [comment] 2017-11-24 09:23
I have reproduced this on a clean installation of 2.2.1 prior to creating this ticket.

**Comment by magento-engcom-team** [comment] 2017-11-24 14:30
@Danielc3 , thanks for your response, this problem already fixed in develop.

**Comment by magento-engcom-team** [comment] 2017-11-24 14:34
@Danielc3 , thanks for your response, this problem already fixed in develop.

**Comment by maderlock** [comment] 2018-07-31 11:09
Please can you provide a reference to the pull request/changed code so that those of us on 2.2.x can figure out a fix for this?

**Comment by mustdobetter** [comment] 2018-08-21 14:46
@okorshenko, could you please point us in the right direction of the relevant pull request/changed code so we can fix this on our 2.2 install? Upgrading is not an option right now.

Many thanks.

**Comment by magento-engcom-team** [comment] 2018-11-16 15:01
Hi @TomashKhamlai. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2018-12-07 12:36
Hi @TomashKhamlai. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by TomashKhamlai** [comment] 2018-12-07 12:53
I will add this to the issue description.
![peek2](https://user-images.githubusercontent.com/11827230/49648799-1a7b0480-fa1f-11e8-9ffd-983881e0f735.gif)

**Comment by magento-engcom-team** [comment] 2018-12-07 12:58
@TomashKhamlai Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97010`, `MAGETWO-97011` were created

**Comment by magento-engcom-team** [comment] 2019-09-18 17:19
@Danielc3, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.3-develop` branch. Thank you for collaboration.

**Closed as completed by magento-engcom-team** 2019-09-18 17:19 UTC
Labels: Issue: Ready for Work, Component: Customer, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid
