### ISSUE TITLE
Product url key allowing space into url

### ISSUE THREAD

**Issue by sunilit42** [magento/magento2#26672] opened 2020-02-03 06:38 UTC
### Preconditions (*)

1. latest magento version
2. edit any product and add space into url key

### Steps to reproduce (*)

1. edit any product and add space into url key

### Expected result (*)

1. it should be give error msg your URL key is wrong or trim space from it

### Actual result (*)

1.  it is saving url key without any error message

**Comment by sunilit42** [comment] 2020-02-03 06:38
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment] 2020-02-03 06:39
Hi @sunilit42. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-03 06:39
Hi @sunilit42, here is your [Magento instance](https://i-26672-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26672-2-4-develop.instances.magento-community.engineering/admin_1a05](https://i-26672-2-4-develop.instances.magento-community.engineering/admin_1a05)
Login: `8e4435bd` Password: `15aafc0b363d`
Instance will be terminated in up to 3 hours.

**Comment by sunilit42** [comment] 2020-02-03 06:43
Screenshot of Proof:-
![image](https://user-images.githubusercontent.com/2923438/73631310-994ceb00-467e-11ea-98f0-9a6d5cff53e8.png)

**Comment by ajijshekh123** [comment] 2020-02-03 06:45
Wait @sunilit42 , Let me verify this issue and update it.

**Comment by sunilit42** [comment] 2020-02-03 06:46
@ajijshekh123  i already checked and verify it and i added a screenshot for the same.

**Comment by ajijshekh123** [comment] 2020-02-03 06:47
Hello @sunilit42 ,
The product is saved in the admin section but In Front end view Product URL is not open and Trim functionality is not applied.

Thanks.

**Comment by magento-engcom-team** [comment] 2020-02-03 06:48
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31014` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by bmitchell-ldg** [comment] 2020-02-14 15:00
It's this pull request that has caused it to allow spacing https://github.com/magento/magento2/commit/6f4f511822fbbcb743a7d4a8de6353d207d99429#diff-386b1042295a816ae69d1e2988756f82
The change to prepareProductUrlKey in \Magento\CatalogUrlRewrite\Model\ProductUrlPathGenerator
needs changing back to
protected function prepareProductUrlKey(Product $product)
    {
        $urlKey = (string)$product->getUrlKey();
        return $product->formatUrlKey($urlKey === '' || $urlKey === null ? $product->getName() : $urlKey);
    }

I created a preference to get around it for us.

**Comment by ramesh-durairajaram** [comment] 2020-02-14 15:53
@bmitchell-ldg , thanks for the support. Will fix this method.

**Comment by hostep** [comment] 2020-03-10 11:41
Let me close this as a duplicate of https://github.com/magento/magento2/issues/26499

**Closed as completed by hostep** 2020-03-10 11:41 UTC
Labels: Issue: Ready for Work, Component: CatalogUrlRewrite, Issue: Confirmed, Issue: Format is valid, Component: UrlRewrite, Component: Validator, Reproduced on 2.4.x
