### ISSUE TITLE
Incorrect position of grid header Design Configuration Grid

### ISSUE THREAD

**Issue by kate-kyzyma** [magento/magento2#20024] opened 2018-12-31 08:34 UTC
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Open the Design Configuration Grid: *Content -> Design -> Configuration*

### Expected result (*)

1. The grid header is displayed above the grid.
![screen shot 2018-12-31 at 10 18 51 am](https://user-images.githubusercontent.com/32304009/50556868-4b311f80-0ce7-11e9-848c-00b9ac6978bf.png)

### Actual result (*)

1. The grid header is displayed below the grid.
![screen shot 2018-12-31 at 10 17 12 am](https://user-images.githubusercontent.com/32304009/50556872-52f0c400-0ce7-11e9-850d-e8f5fba0ad99.png)

**Comment by magento-engcom-team** [comment] 2018-12-31 08:34
Hi @kate-kyzyma. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kate-kyzyma do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-12-31 08:34
Hi @dmytro-ch. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by dmytro-ch** [comment] 2018-12-31 08:34
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2018-12-31 08:34
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2018-12-31 08:35
Hi @dmytro-ch, here is your [Magento instance](https://i-20024-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20024-2-3-develop.instances.magento-community.engineering/admin](https://i-20024-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2018-12-31 08:37
@dmytro-ch Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97388` were created

**Comment by dmytro-ch** [comment] 2018-12-31 08:55
Please note, the issue is not reproducible in *2.2-develop* branch.

**Comment by shikhamis11** [comment] 2019-02-11 10:27
since this issue is fixed in 2.3-develop branch and also not reproducable at 2.2-develop I closing this

**Closed as completed by shikhamis11** 2019-02-11 10:27 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Ui
