### ISSUE TITLE
Redirct to cart after place order

### ISSUE THREAD

**Issue by yiukamsum** [magento/magento2#32739] opened 2021-04-13 15:32 UTC
### Preconditions (*)

1. Magento 2.4.2

### Steps to reproduce (*)

1. Add a product to the cart
2. Go to checkout
3. Go to second step (payments)
4. Before selecting a pament method, open coupon code to be aible to enter a coupon code
5. Than select a pament method.
6. Place Order

### Expected result (*)

1. Go to Success Page

### Actual result (*)

1. Redirected to Cart Page
![image](https://user-images.githubusercontent.com/13889428/114705677-8f327c00-9d5a-11eb-8dfb-97b098056efd.png)

### Debugging
1. In ```Magento\Checkout\Model\Session\SuccessValidator```
> $this->checkoutSession->getLastSuccessQuoteId()
> $this->checkoutSession->getLastQuoteId()
> $this->checkoutSession->getLastOrderId()
> They are always return ```NULL```
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by yiukamsum** [comment] 2021-04-13 15:33
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment] 2021-04-14 04:27
Hi @yiukamsum. Kindly provide more details/additional steps in which you face this issue.

**Comment by pemann** [comment] 2021-04-14 05:24
@magento give me 2.4-develop instance

**Comment by yiukamsum** [comment] 2021-04-14 12:44
> Hi @yiukamsum. Kindly provide more details/additional steps in which you face this issue.

I have updated the description. Please check it. Thanks for your help.

**Comment by krishprakash** [comment] 2021-04-21 09:31
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment] 2021-05-03 10:35
Hi @yiukamsum. Can you please confirm this issue by adding comment for magento instance as not able to replicate the issue provided steps by you

**Comment by Nuranto** [comment] 2021-06-04 10:31
Hello,

Having same issue here.
It seems linked to `ReindexQuoteInventoryObserver` observer (problem solved when removing it).

I will dig deeper, I'll let you know if I found more details.

**Comment by engcom-November** [comment] 2021-08-23 07:32
Hi @yiukamsum,
Issue is not reproducible on Magento 2.4-develop branch with provided steps for both Public User and Logged in User. Kindly recheck the issue on 2.4-develop branch and let us know the missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2021-09-06 05:45
Hi @yiukamsum ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-09-06 05:45 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.2

**Comment by ingmarnet** [comment] 2023-09-27 20:16
Still with 2.4.6-p2 version on every offline payment
