### ISSUE TITLE
Enable Merge CSS Files make adminl panel very slow

### ISSUE THREAD

**Issue by hungvt** [magento/magento2#5246] opened 2016-06-25 03:48 UTC
Hi,
After i set the option Merge CSS Files to yes the adminpanel runs very slow.

**Comment by hostep** [comment] 2016-06-25 17:59
This has been reported multiple times, please first try searching for an issue instead of creating a new one :)

Dupe of: https://github.com/magento/magento2/issues/4321

**Comment by pboisvert** [comment] 2016-06-25 22:17
closing as a duplicate.

**Closed as completed by pboisvert** 2016-06-25 22:17 UTC
Labels: Fixed in 2.3.x, Issue: Format is not valid

**Comment by magento-engcom-team** [comment] 2019-09-03 18:20
Hi @hungvt. Thank you for your report. 
The issue has been fixed in magento/magento2#24420 by @atwixfirster in 2.3-develop branch
Related commit(s):
 - [528c538a79a4928f3bd2c38d0e23f2220f6dbaef](https://github.com/magento/magento2/commit/528c538a79a4928f3bd2c38d0e23f2220f6dbaef)

The fix will be available with the upcoming 2.3.4 release.

**Comment by magento-engcom-team** [comment] 2019-09-07 16:10
Hi @hungvt. Thank you for your report. 
The issue has been fixed in magento/magento2#24489 by @atwixfirster in 2.3-develop branch
Related commit(s):
 - [e7fb5d79b9ca5559ffc987aed3748aec7bc4f377](https://github.com/magento/magento2/commit/e7fb5d79b9ca5559ffc987aed3748aec7bc4f377)

The fix will be available with the upcoming 2.3.4 release.
