### ISSUE TITLE
When importing catalog data, simple products become disassociated with configurables

### ISSUE THREAD

**Issue by pizzachip** [magento/magento2#6561] opened 2016-09-09 14:41 UTC
### Preconditions

Nginx
PHP 5.6
Magento 2.1.0
5400 skus in product catalog, mixture of simple and configurable

I have encountered this issue in multiple versions of Magento 2 and on multiple projects in each.
### Steps to reproduce
1. Create a large catalog (>2000skus) with configurable products
2. Create an upload file that just updates the price field (just the base price, not advanced)
3. Upload the price update file
4. Check your configurable products in the admin panel. You will find that products that had configurable items associated with them now have no associations.

Previously (2.0 version) when encountering this issue, we would see that the simple products associated with the configurables had lost attributes values. Once we restored those attribute values (either via upload or manually), the products reassociated to the confugurables.

Unfortunately, we have not found a way to predict the issue. 
### Expected result

1. When you upload a product file, you should not lose associations between simples and configurables.
### Actual result

1. You lose them.

**Comment by sevos1984** [comment] 2016-09-14 14:27
I have generated 8800 skus including 2000 configurable using setup:performance:generate-fixtures tool. Then exported and imported all products back with updated price and all is fine. Try updating to latest release version and allocating more memory to magento.

**Comment by sevos1984** [comment] 2016-09-29 12:43
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-09-29 12:43 UTC
Labels: bug report, Progress: needs update, Component: ImportExport
