### ISSUE TITLE
Magento 2.3.5p-1 and Elasticsearch 6.8.11 fielddata error

### ISSUE THREAD

**Issue by AleksandrPlotnikov** [magento/magento2#29439] opened 2020-08-07 16:03 UTC
### Preconditions (*)

1. Magento 2.3.5p-1
2. Elasticsearch 6.8.11

### Steps to reproduce (*)
1. Install magento using 
 `composer create-project --repository-url=https://repo.magento.com/ magento/project-enterprise-edition=2.3.5-p1`
2. install Elasticsearch 6.8.11

### Expected result (*)

Catalog Product page works well with updated_at sorting

### Actual result (*)

Catalog Product page throw an error 
`[{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [updated_at] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}]`

We have default sorting on the catalog by updated_at desc, if I remove this sorting all works well. Elasticsearch displays updated_at as 
`"updated_at" : {
            "type" : "text",
            "index" : false
  },`
So I am not sure why this is happening if updated_at is not indexed and obviously can not be set as fielddata=true.

Previous version o magento that we have was 2.3.0 (magento2ce, now we moved to the project-community-edition) with elasticsearch 5.6 and all works well with such config.

**Comment by hostep** [comment] 2020-08-12 15:39
We're running into a very similar problem with Magento OS 2.3.3 and ElasticSearch 6.8.11, but I haven't found the time and haven't got the knowledge yet to figure out what this is about.

@AleksandrPlotnikov: have you already found out more about this issue in the mean while?

**Comment by AleksandrPlotnikov** [comment] 2020-08-12 15:46
@hostep kind of. I`ve updated reindex mechanism to set updated_at as keyword field, included this field into indexed fields and also couple of files was overrided with old elasticsearch magento module, this is a workaround but works well with sorting. But I still dont understand why is was working on previous version.

**Comment by hostep** [comment] 2020-08-13 09:29
Okay, we've figured out the issue on our side, it's not really related to the problem mentioned here I think. But let me briefly explain it just in case other people run into similar problems:
- We have a custom product import which can also create attributes
- One attribute which was created had type "text" but also had the flag "is_filterable" set to "yes" (normally Magento backend doesn't allow this, but our custom import did allow this)
- ElasticSearch then threw one of two exceptions:
  * `Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [our_custom_attribute] in order to load field data by uninverting the inverted index. Note that this can use significant memory.`
  * `Fielddata is disabled on text fields by default. Set fielddata=true on [our_custom_attribute] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.` because of this.
- When removing the `is_filterterable` flag from the attribute, ElasticSearch no longer threw errors.

Sorry for the noise, hope you find a proper solution for date attributes being used in the sorting, I don't know if Magento's implementation of ElasticSearch supports that or not.

**Comment by rparsi-boxycharm** [comment] 2020-08-17 21:37
Just letting everyone know that I'm getting this same error with m2.3.5-p2 (enterprise/whatever the paid version is called) with ES 7.0

**Comment by JelleGe** [comment] 2020-11-09 08:55
Getting the same error on m2.4.1. Any solution to this error?

**Comment by rparsi-boxycharm** [comment] 2020-11-09 20:01
@JelleGe Depending on which ES version you're using, you need to create a "before" plugin on method `addFieldsMapping`, changing the ES field type to `keyword`.
In our case we made "after" plugin for `\Magento\Elasticsearch7\Model\Client\Elasticsearch`, so our `beforeAddFieldsMapping` looks like this
```
public function beforeAddFieldsMapping(
        Elasticsearch $subject,
        array $fields,
        string $index,
        string $entityType
    ) {
        if (!isset($fields['is_salable'])) {
            $fields['is_salable'] = [
                'type' => 'keyword'
            ];
        }

        return [$fields, $index, $entityType];
    }
```
You'll have to do this for any category or product attributes for which magento uses the wrong ES field type

**Comment by msyhr** [comment] 2020-12-21 20:46
> @JelleGe Depending on which ES version you're using, you need to create a "before" plugin on method `addFieldsMapping`, changing the ES field type to `keyword`.
> In our case we made "after" plugin for `\Magento\Elasticsearch7\Model\Client\Elasticsearch`, so our `beforeAddFieldsMapping` looks like this
> 
> ```
> public function beforeAddFieldsMapping(
>         Elasticsearch $subject,
>         array $fields,
>         string $index,
>         string $entityType
>     ) {
>         if (!isset($fields['is_salable'])) {
>             $fields['is_salable'] = [
>                 'type' => 'keyword'
>             ];
>         }
> 
>         return [$fields, $index, $entityType];
>     }
> ```
> 
> You'll have to do this for any category or product attributes for which magento uses the wrong ES field type

I can confirm this works, however in my instance the array key was already set. So the below code was needed instead of !isset (your results may vary)


`        if (array_key_exists('your_attribute', $fields)) {
            $fields['your_attribute] = [
                'type' => 'keyword'
            ];
        }`

**Comment by mlaurense** [comment] 2020-12-22 13:07
Thanks @rparsi-boxycharm and @msyhr for your input. I ended up combining both your additions to fix our issue. Complete example for the one's running into the same issue:
di.xml:
```
    <type name="Magento\Elasticsearch7\Model\Client\Elasticsearch">
        <plugin name="fix_elasticsearch_index" type="<Vendor>\<Module>\Plugin\Elasticsearch" sortOrder="1"/>
    </type>
```
Plugin/Elasticsearch.php:
```
<?php

namespace <Vendor>\<Module>\Plugin;

class Elasticsearch
{
    public function beforeAddFieldsMapping(
        \Magento\Elasticsearch7\Model\Client\Elasticsearch $subject,
        array $fields,
        string $index,
        string $entityType
    ) {
        $skip = [
            'image_label',
            'links_title',
            'samples_title',
            'small_image_label',
            'thumbnail_label',
        ];
        foreach ($skip as $field) {
            if (!isset($fields[$field]) || array_key_exists($field, $fields)) {
                $fields[$field] = [
                    'type' => 'keyword'
                ];
            }
        }

        return [$fields, $index, $entityType];
    }
}

**Comment by Vky0311** [comment] 2020-12-27 11:32
https://magento.stackexchange.com/a/328476/49310 is this the same issue? Sort by newest not working and giving the same error. Any solution?

**Comment by rparsi-boxycharm** [comment] 2020-12-29 15:58
@Vky0311 If you're using ES for category/product search and you're getting the same ES error indicated here, then I'd say `yes` same root issue

**Comment by Vky0311** [comment] 2020-12-29 17:05
Magento 2.4.1 - https://magento.stackexchange.com/a/328476/49310

`main.CRITICAL: {"error":{"root_cause":[{"type":"query_shard_exception","reason":"No mapping found for [e.created_at] in order to sort on","index_uuid":"bO3vW6icTryxTaYviwJFmA","index":"magento2_product_1_v82"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"magento2_product_1_v82","node":"YYnx_-CIRyOYDAqvIIU_BQ","reason":{"type":"query_shard_exception","reason":"No mapping found for [e.created_at] in order to sort on","index_uuid":"bO3vW6icTryxTaYviwJFmA","index":"magento2_product_1_v82"}}]},"status":400} {"exception":"[object] (Elasticsearch\\Common\\Exceptions\\BadRequest400Exception(code: 400): {\"error\":{\"root_cause\":[{\"type\":\"query_shard_exception\",\"reason\":\"No mapping found for [e.created_at] in order to sort on\",\"index_uuid\":\"bO3vW6icTryxTaYviwJFmA\",\"index\":\"magento2_product_1_v82\"}],\"type\":\"search_phase_execution_exception\",\"reason\":\"all shards failed\",\"phase\":\"query\",\"grouped\":true,\"failed_shards\":[{\"shard\":0,\"index\":\"magento2_product_1_v82\",\"node\":\"YYnx_-CIRyOYDAqvIIU_BQ\",\"reason\":{\"type\":\"query_shard_exception\",\"reason\":\"No mapping found for [e.created_at] in order to sort on\",\"index_uuid\":\"bO3vW6icTryxTaYviwJFmA\",\"index\":\"magento2_product_1_v82\"}}]},\"status\":400} at D:\\xampp\\htdocs\\ms241\\vendor\\elasticsearch\\elasticsearch\\src\\Elasticsearch\\Connections\\Connection.php:632)"} []`

$this->_collection->setOrder('price', 'asc'); works
`$this->_collection->setOrder('e.created_at', 'desc');` OR `$this->_collection->setOrder('created_at', 'desc');` giving above error
And not able to solve this using above solution. Let me know if anyone have a solution for this.

**Comment by rparsi-boxycharm** [comment] 2020-12-29 17:22
@Vky0311 That is a completely different error message.
```
"reason":"No mapping found for [e.created_at] in order to sort
```
Inspect the `magento2_product_1_v82` index in your ES; as the error message says you're missing a field mapping.
You would need to create a plugin for the same class as for this ticket, to add the custom mapping.

**Comment by dverkade** [comment] 2021-03-17 15:31
This issue can't be closed automatically as it still needs verification.

**Comment by dverkade** [comment] 2021-04-24 19:22
This issue is caused because a varchar / text field is set to be filerable in search. I've resolved this by running the following query, then flushing the cache and doing a reindex again. This solved the issue for me.

`UPDATE catalog_eav_attribute SET is_filterable_in_search = 0 WHERE attribute_id IN (SELECT attribute_id FROM eav_attribute WHERE entity_type_id = 4 AND backend_type = 'varchar')`

**Comment by engcom-Alfa** [comment] 2021-06-17 09:41
Hi @AleksandrPlotnikov 
Kindly follow the instructions provided in the [above comment](https://github.com/magento/magento2/issues/29439#issuecomment-826141391), assuming your issue has been solved.
If not kindly upgrade to the latest Magento version, and check if the problem is still existing. If so, kindly provide the details preconditions, steps to reproduce along with expected and actual results.

**Comment by AleksandrPlotnikov** [comment] 2021-06-17 11:51
hi @engcom-Alfa , the issue was resolved following my steps. thank you

**Comment by engcom-Alfa** [comment] 2021-06-18 10:11
Thanks for the update. Closing the issue

**Closed as completed by engcom-Alfa** 2021-06-18 10:11 UTC
Labels: Severity: S1, Issue: needs update, Reported on 2.3.5-p1

**Comment by adamphh** [comment] 2021-09-16 09:55
I got the same problem after upgrading from Magento 2.3.2 to 2.4.2. I tried the code of @mlaurense above but it's not working. I plugin function query() instead and it works for me.

di.xml:
```
<type name="Magento\Elasticsearch7\Model\Client\Elasticsearch">
      <plugin name="fix_elasticsearch_index" type="<Vendor>\<Module>\Plugin\Elasticsearch" sortOrder="1"/>
</type>
```

Plugin/Elasticsearch.php:
```
public function beforeQuery(
        \Magento\Elasticsearch7\Model\Client\Elasticsearch $subject,
        array $query
    ) {
        $skip = [
            'image_label_bucket',
            'links_title_bucket',
            'samples_title_bucket',
            'small_image_label_bucket',
            'thumbnail_label_bucket',
        ];
        if (isset($query['body']) && isset($query['body']['aggregations'])) {
            foreach ($skip as $key) {
                unset($query['body']['aggregations'][$key]);
            }
        }
        return [$query];
    }
```

**Comment by david-garcia-garcia** [comment] 2021-09-19 16:29
The actual right solution for this is to REBUILD you attributes using a different storage type (such as options). But, if you really need to keep things as they are, the solution proposed by @mlaurense is the way to go. Only that his code is **not a generic approach** and deals with specific hardcoded fields.

I did this to automatically deal with this:

`<?php

namespace MODULE\xx\Plugin\Magento\Framework;

class Elasticsearch
{
    /**
     * @var \Magento\Framework\Search\Request\Config
     */
    private $config;

    public function __construct(
        $options = [],
        $elasticsearchClient = null,
        $fieldsMappingPreprocessors = [],
        \Magento\Framework\Search\Request\Config $config
    )
    {
        $this->config = $config;
    }

    public function beforeAddFieldsMapping(
        \Magento\Elasticsearch7\Model\Client\Elasticsearch $subject,
        array $fields,
        string $index,
        string $entityType
    ) {
        $mappings = $this->config->get();

        foreach ($mappings as $configKey => $config) {
            foreach($config['aggregations'] as $aggregationKey => $aggregation) {
                if (array_key_exists('field', $aggregation)) {
                    $field = $aggregation['field'];
                    if (array_key_exists($field, $fields) && $fields[$field]['type'] === 'text') {
                        $fields[$field]['type'] = 'keyword';
                    }
                    if (array_key_exists($field . '_value', $fields) && $fields[$field . '_value']['type'] === 'text') {
                        $fields[$field]['type'] = 'keyword';
                    }
                }
            }
        }
    }
}
`

**Comment by simbatsuro** [comment] 2021-11-19 07:23
I found this [answer](https://magento.stackexchange.com/a/341418) helpful. SImilar to @dverkade's
