### ISSUE TITLE
Purchase order number different db sizes in quote_payment and order_payment tables

### ISSUE THREAD

**Issue by theodorhanu** [magento/magento2#32405] opened 2021-03-09 17:00 UTC
### Preconditions (*)
1. Magento 2.3 or 2.4

### Steps to reproduce (*)
1. Enable purchase order payment method 
2. add products to cart and proceed to checkout
3. Select purchase order payment method and fill  in purchase order field with a value containing more than 32 characters
4. Place the order

### Expected result (*)
The purchase order number value  saved in order_payment should contain all characters entered by customer when placing the order

### Actual result (*)
The purchase order number value saved in order_payment is truncated to max 32 chars.

---

The issue is in db_schema.xml of Quote and Sales modules.
In Quote/etc/db_schema.xml, the po_number( quote_payment table ) field is set to varchar(255), but in Sales/etc/db_schema.xml, the po_number  ( sales_order_payment table ) is set to varchar(32)

**Comment by magento-engcom-team** [comment] 2021-03-10 10:53
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41220` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment] 2024-07-15 06:38
Hi @theodorhanu,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="1055" alt="Screenshot 2024-07-15 at 12 06 54" src="https://github.com/user-attachments/assets/8ee5098b-0f4e-4a73-a03a-05526fb209bc">



The purchase order number value saved in order_payment containing all characters entered by customer when placing the order

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-15 06:38 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done, Component: PurchaseOrderNumber
