### ISSUE TITLE
Price not saved for different website/store.

### ISSUE THREAD

**Issue by BorisovskiP** [magento/magento2#35737] opened 2022-07-07 12:47 UTC
### Preconditions and environment

- Magento version 2.4.4
- PHP 7.4
- Multistore setup

### Steps to reproduce

1. Have two stores/websites (Default, Test)
2. Set the price of a product to 10$ in the default store.
3. Switch to the Test store
4. Set the price of the product to 11$ in the Test store
5. Save

### Expected result

Changes were successfully applied. Success message is shown when saving is complete and the prices in the Test store is 11$.

### Actual result

Success message is shown, but the price in the Test store is unchanged and the “Use Default” checkbox is still checked.

### Additional information

During `bin/magento config:set catalog/price/scope  1` ,`vendor/magento/module-catalog/Observer/SwitchPriceAttributeScopeOnConfigChange.php` (`admin_system_config_changed_section_catalog)` is never dispatched. If you set `catalog/price/scope  1` and then try to reproduce the issue, the price will never be changed. The price will only be correctly changed when you simply change an unimportant setting in the catalog section. Then the event will be called and the correct price will be set.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by TheRealHunzik** [comment] 2022-07-07 13:52
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment] 2022-07-13 11:59
Hi @BorisovskiP 

I have tried to reproduce the issue on `2.4-develop` branch but issue is not reproducible.

I have followed below steps:
1. Created two websites and two stores and there store views following this [document](https://devdocs.magento.com/guides/v2.4/config-guide/multi-site/ms_websites.html).
2. Go to stores >> configuration >> Catalog >> catalog >> Price and set Catalog Price Scope to Website level.
3. Clean the indexer, flush the cache and restarted apache & elasticsearch.
4. Go to product && change the scope & change the price in website 1 ,store 1,store view 1 and save.
5. Similarly change the price of website 2,store 1 and store view 1 and save it.
6. Check the price and use default check box by changing scope.

Kindly use PHP 8.1 as Magento 2.4 supports it, please refer [docs](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) and follow the step 2 given above. Please test in latest `2.4-develop` and inform us if you are facing any problem.

Thank You

**Comment by engcom-Lima** [comment] 2022-07-27 09:44
Hi @BorisovskiP  ,

We are closing this issue as there has been no latest update on the same. Kindly reopen/create new issue if you are still facing any issues.

Thank you

**Closed as completed by engcom-Lima** 2022-07-27 09:44 UTC
Labels: Issue: needs update

**Comment by vasilii-b** [comment] 2023-11-20 12:42
Still reproducible in 2.4.6-p3

**Comment by Aquive** [comment] 2024-06-04 08:31
I can confirm the issue is present in version 2.4.5-p6 too

**Comment by kestraly** [comment] 2025-06-25 10:43
You've enabled
Sales > Configuration > Catalog > Price > Per Website

However if you got to attributes in
Stores > Products

Search price, the price is still a Global attribute - So it won't let you save it

SELECT * FROM catalog_eav_attribute WHERE attribute_id = (YOUR PRICE ATTRIBUTE ID)

Set Global from 1 to 2

For some reason the attribute isn't always updated from global to website view. I have two identical installations. The staging worked perfectly, the live didn't work at all. The work around as follows
