### ISSUE TITLE
ui-select not reloading value when used in entity form after the entity is saved 

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#38643] opened 2024-04-20 09:53 UTC
### Preconditions and environment

- 2.4.1

### Steps to reproduce

1. I've created my entity using the phpstorm plugin and I've added a rule_id field. 
2. I've added a field in my UI Form Component like this 

```
<field name="rule_id" component="Magento_Ui/js/form/element/ui-select" sortOrder="10" formElement="select">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="filterOptions" xsi:type="boolean">true</item>
                    <item name="multiple" xsi:type="boolean">false</item>
                    <item name="showCheckbox" xsi:type="boolean">false</item>
                    <item name="disableLabel" xsi:type="boolean">true</item>
                    <item name="levelsVisibility" xsi:type="number">0</item>
                    <item name="searchOptions" xsi:type="boolean">true</item>
                    <item name="searchUrl" xsi:type="url" path="ioweb_base/rule/search"/>
                    <item name="options" xsi:type="object">Ioweb\Base\Model\Config\Source\CartRule</item>
                    <item name="filterPlaceholder" xsi:type="string" translate="true">Rule ID or Name</item>
                    <item name="emptyOptionsHtml" xsi:type="string" translate="true">Start typing to find rules</item>
                    <item name="missingValuePlaceholder" xsi:type="string" translate="true">Rule with ID: %s doesn\'t exist</item>
                </item>
            </argument>
            <settings>
                <required>true</required>
                <validation>
                    <rule name="required-entry" xsi:type="boolean">true</rule>
                </validation>
                <elementTmpl>ui/grid/filters/elements/ui-select</elementTmpl>
                <label translate="true">Rule ID</label>
                <dataScope>rule_id</dataScope>
                <componentType>field</componentType>
                <tooltip>
                    <description>Select rule ID. Type at least 3 characters to search.</description>
                </tooltip>
            </settings>
        </field>
```

The options are searched using the following controller 

```
<?php
/**
 * Copyright (c) 2024. IOWEB TECHNOLOGIES
 */

declare(strict_types=1);

namespace Ioweb\Base\Controller\Adminhtml\Rule;

use Magento\Backend\App\Action;
use Magento\Framework\Api\SearchCriteriaBuilder;
use Magento\Framework\App\Action\HttpGetActionInterface;
use Magento\Framework\Controller\Result\JsonFactory;
use Magento\SalesRule\Api\RuleRepositoryInterface;

/**
 * Controller for the 'ioweb_base/rule/search' URL route.
 */
class Search extends Action implements HttpGetActionInterface
{
    /**
     * Authorization level of a basic admin session.
     */
    const ADMIN_RESOURCE = 'Magento_SalesRule::config_promo';

    /**
     * @var JsonFactory
     */
    private $resultJsonFactory;

    /**
     * @var RuleRepositoryInterface
     */
    private $ruleRepository;

    /**
     * @var SearchCriteriaBuilder
     */
    private $searchCriteriaBuilder;

    /**
     * @param JsonFactory $resultJsonFactory
     * @param RuleRepositoryInterface $ruleRepository
     * @param SearchCriteriaBuilder $searchCriteriaBuilder
     * @param Action\Context $context
     */
    public function __construct(
        JsonFactory             $resultJsonFactory,
        RuleRepositoryInterface $ruleRepository,
        SearchCriteriaBuilder   $searchCriteriaBuilder,
        Action\Context          $context
    ) {
        $this->resultJsonFactory = $resultJsonFactory;
        $this->ruleRepository = $ruleRepository;
        $this->searchCriteriaBuilder = $searchCriteriaBuilder;
        parent::__construct($context);
    }

    /**
     * Execute controller action.
     *
     * @return \Magento\Framework\Controller\ResultInterface
     */
    public function execute()
    {
        $options = [];

        $searchKey = $this->getRequest()->getParam('searchKey');
        $pageNum = (int)$this->getRequest()->getParam('page');
        $limit = (int)$this->getRequest()->getParam('limit');

        $this->searchCriteriaBuilder->addFilter('name', "%$searchKey%", 'like');
        $searchCriteria = $this->searchCriteriaBuilder->create();
        $searchCriteria->setCurrentPage($pageNum);
        $searchCriteria->setPageSize($limit);
        $rulesList = $this->ruleRepository->getList($searchCriteria);
        if ($rulesList->getTotalCount() > 0) {
            $rules = $rulesList->getItems();
            foreach ($rules as $rule) {
                $options[$rule->getRuleId()] = [
                    'value' => $rule->getRuleId(),
                    'label' => $rule->getName(),
                    'level' => 0,
                    'path' => $rule->getRuleId(),
                ];
            }
        }
        $resultJson = $this->resultJsonFactory->create();
        return $resultJson->setData([
                                        'options' => $options,
                                        'total' => $rulesList->getTotalCount()
                                    ]);
    }
}
```

3. The searching works fine and the item is working correctly 
![image](https://github.com/magento/magento2/assets/20220341/70b9da9c-7561-422c-8084-0604a55fb42a)

However when reopening my form the ui-select component is not searching for the rule again to display it and shows a broken value for the name of the option

![image](https://github.com/magento/magento2/assets/20220341/e2f41224-52b6-4dfc-90e3-8fd93d8762af)

### Expected result

The item is reloaded properly based on the ID  rendering the component unusable for the admin user as he can't remember which rule he selected. 

### Actual result

The select box shows that the item with ID: X doesn't exist

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by shakil-codilar** [comment] 2024-04-27 13:52
@m2-github-services give me 2.4.4-p1 instance

**Comment by shakil-codilar** [comment] 2024-04-27 13:54
@magento give me 2.4.4-p1 instance

**Comment by engcom-Hotel** [comment] 2024-04-29 09:28
Hello @ioweb-gr,

Thanks for the report and collaboration!

We have tried to reproduce the issue in the latest development branch i.e. 2.4-develop but it seems the issue is not reproducible at our end. 

For us, the value is populating after saving:

![image](https://github.com/magento/magento2/assets/51681618/a1034ae4-c6e9-475c-8ba4-228e34f428de)

In order to reproduce the issue, we have added a fieldset in `app/code/Magento/Backend/view/adminhtml/ui_component/design_config_form.xml`, it looks something like this:

```
<field name="rule_id" component="Magento_Ui/js/form/element/ui-select" sortOrder="10" formElement="select">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="filterOptions" xsi:type="boolean">true</item>
                    <item name="multiple" xsi:type="boolean">false</item>
                    <item name="showCheckbox" xsi:type="boolean">false</item>
                    <item name="disableLabel" xsi:type="boolean">true</item>
                    <item name="levelsVisibility" xsi:type="number">0</item>
                    <item name="searchOptions" xsi:type="boolean">true</item>
                    <item name="searchUrl" xsi:type="url" path="issue38643/rule/search"/>
                    <item name="options" xsi:type="object">Magz\Issue38643\Model\Config\Source\CartRule</item>
                    <item name="filterPlaceholder" xsi:type="string" translate="true">Rule ID or Name</item>
                    <item name="emptyOptionsHtml" xsi:type="string" translate="true">Start typing to find rules</item>
                    <item name="missingValuePlaceholder" xsi:type="string" translate="true">Rule with ID: %s doesn\'t exist</item>
                </item>
            </argument>
            <settings>
                <required>true</required>
                <validation>
                    <rule name="required-entry" xsi:type="boolean">true</rule>
                </validation>
                <elementTmpl>ui/grid/filters/elements/ui-select</elementTmpl>
                <label translate="true">Rule ID</label>
                <dataScope>rule_id</dataScope>
                <componentType>field</componentType>
                <tooltip>
                    <description>Select rule ID. Type at least 3 characters to search.</description>
                </tooltip>
            </settings>
        </field>
```

Please let us know if we missed anything.

Thanks

**Comment by ioweb-gr** [comment] 2024-04-30 05:28
Please use the Magento 2 phpstorm plugin to create a new entity as that's how I noticed it

The only difference I can think of is that the area you used it on handles the data differently

**Comment by engcom-Hotel** [comment] 2024-05-02 06:58
Hello @ioweb-gr,

It seems the issue is specifically reproducible with the Magento 2 phpstorm plugin. So I suggest you please create this issue in the below repo:

https://github.com/magento/magento2-phpstorm-plugin/issues

Please let us know if we missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2024-05-13 12:43
Dear @ioweb-gr,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we're assuming it's been resolved and will be closing it. Feel free to open a new ticket or reopen this one if you require further assistance.

Regards

**Closed as completed by engcom-Hotel** 2024-05-13 12:43 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.1
