### ISSUE TITLE
Styling bug in datepicker on Report pages

### ISSUE THREAD

**Issue by cloudflexdev** [magento/magento2#35834] opened 2022-07-28 08:01 UTC
### Preconditions and environment

- Magento 2.4.4

### Steps to reproduce

1. Login to Admin Dashboard
2. Go to the Reports -> Customers -> Order Total
3. Select any "from date" and any "to date"

### Expected result

The text shouldn't overlaps.
![image](https://user-images.githubusercontent.com/78548851/181445565-4148dca1-70b2-4b20-a69d-49718b069551.png)

### Actual result

When you select dates in the datepicker, the text overlaps.
![image](https://user-images.githubusercontent.com/78548851/181445332-3f8f19f5-61eb-488a-80eb-074c658e4bac.png)

### Additional information

I noticed that the problem affects every page in Reports -> Customer eg. Order Total, Order Count, New and doesn't appear on Magento 2.4.2.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-07-28 12:22
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-07-28 12:24
Verified the issue on Magento 2.4-develop branch and the issue is reproducible. Hence updating the description and confirming the issue.
![image](https://user-images.githubusercontent.com/60198231/181504252-0ff24ed5-be70-4f3f-bea7-fc3caca868e2.png)

**Comment by engcom-Bravo** [comment] 2024-12-11 04:27
Hi @qubabyte,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.


<img width="1426" alt="Screenshot 2024-12-11 at 9 55 35 am" src="https://github.com/user-attachments/assets/f143a6b9-5021-4919-90e3-b6ce4871463a">


The text is not overlapping.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-12-11 04:27 UTC
Labels: Issue: Confirmed, Component: Reports, Reproduced on 2.4.x, Priority: P3, Progress: done, Area: Analytics / Reporting, Reported on 2.4.4
