### ISSUE TITLE
Bug: double click on a widget inside TinyMCE editor does not edit the widget but creates a new one 

### ISSUE THREAD

**Issue by dmitry-fedyuk** [magento/magento2#2238] opened 2015-11-02 04:09 UTC
![magento2-04](https://cloud.githubusercontent.com/assets/83204/10874163/9a3a1762-8130-11e5-816a-38622bd09e58.png)

![magento2-05](https://cloud.githubusercontent.com/assets/83204/10874167/a1ac24cc-8130-11e5-8e9f-2c4108e822ef.png)

To reproduce the bug you need to fix the https://github.com/magento/magento2/issues/2235 bug first.

**Comment by shiftedreality** [comment] 2016-01-14 15:00
Hi @dfediuk 

Thank you for reporting this issue. Internal ticket MAGETWO-47932 was created

**Comment by toddhainsworth** [comment] 2017-04-27 22:52
Hi @shiftedreality just wondering if you have an update on this? We're seeing this issue on our 2.1.4 installation. I've checked the commits referenced in #2235 and have confirmed they are currently in our codebase but we are still seeing the issue.

**Comment by nilarocks** [comment] 2017-09-09 12:31
Hello,

Same issue in Magento 2.1.7.

**Steps to repeat**

1. Go to Admin -> Content -> Pages, and edit a page.
2. Add a new widget to the page
3. Select Catalog Product Lists as the widget type.
4. Added Required Field
5. Click on "Insert Widget"
6. Click on "Click on "Save and Continue Edit"
7.  Double Click on "Widget icon"

**Expected result:** 
Widget open with selected/filled data 

**Actual result:** 
Widget open as new 

**Js Error:**
Uncaught DOMException: Failed to execute 'setBaseAndExtent' on 'Selection': There is no child at offset 1.  In tiny_mce_src.js
Line No.: 1173

**Comment by hostep** [comment] 2017-09-09 16:16
@nilarocks: the error you are reporting is a different problem, it's this one: https://github.com/magento/magento2/issues/9518 which has been fixed in Magento 2.1.8.

**Comment by magento-engcom-team** [comment] 2017-10-18 06:02
@dmitry-fedyuk, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Closed by magento-engcom-team** 2017-10-18 06:02 UTC
Labels: acknowledged, bug report, Can not Reproduce, Frontend, G1 Failed, G2 Passed, G3 Passed, SQUASHTOBERFEST
