### ISSUE TITLE
Saving Product Configuration with many colors and lengths fails

### ISSUE THREAD

**Issue by joebusby** [magento/magento2#3154] opened 2016-01-27 02:12 UTC
I have a product with 20 colors in 16 lengths and the large number of items fails to save with the following error:
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento2`.`catalog_product_entity`, CONSTRAINT `CAT_PRD_ENTT_ATTR_SET_ID_EAV_ATTR_SET_ATTR_SET_ID` FOREIGN KEY (`attribute_set_id`) REFERENCES `eav_attribute_set` (`attribute_set_id`) ON DELE), query was: INSERT INTO `catalog_product_entity` (`type_id`, `sku`) VALUES (?, ?)

Configurations with small numbers of results (up to 30 or more) work fine.  The problem only crops up when the Product record number get high (like over 300)
Running on debian 8 with 6 cores

**Comment by davidalger** [comment] 2016-01-27 15:11
@joebusby Thanks for reporting, definitely sounds like a bug. Would you mind sharing your PHP version, MySql version, version of Magento (2.0.0 or 2.0.1 at this point), and installation method used when installing the application to help the Magento team successfully reproduce the bug?

**Comment by dmitrii-fediuk** [comment] 2016-01-27 18:11
Looks like the same problem: https://community.magento.com/t5/Admin-Configuration-Questions/Magento-2-Create-Product-Configurations/m-p/26456

**Comment by joebusby** [comment] 2016-01-28 04:45
The problems seems very consistent with large product generation, although sometimes (trying different things) the system would just hang forever with no error.  The rest of the things I did before I ran into this problem worked well.  Here is what I have:
OpenVZ instance on debian with 3GB of ram and 6 cores
Magento Version 2.0.1  
PhP version:  PHP Version 5.6.17-0+deb8u1
MySQL version 5.6.28
installed with composer 
PHP memory 1GB

**Comment by schnappenberger** [comment] 2016-01-30 16:32
Have you tried to increase your max_input_vars Php Setting?

**Comment by joebusby** [comment] 2016-01-30 19:07
Thanks schnappenberger,  that did it.  I changed max_input_vars to 5000 and it worked!  Problem Solved.  Maybe make that part of the installation instructions for people that have a lot of attributes?

**Comment by davidalger** [comment] 2016-02-01 02:53
@joebusby I'm glad you found a workaround to the issue, but I'm re-opening because I believe this is something which still needs addressing. The sql error should not really be allowed to occur. The max_input_vars is something which has affected assigning attribute option values in the admin in the past as well. My opinion is that the admin should be sending this information in a serialized format to avoid randomly exceeding these limits, so they can stay at a sane (i.e. lower) level and so the admin will work seamlessly regardless of the quantity of associations. Server configuration such as this shouldn't have to change IMO in order to accommodate a day-to-day admin function.

**Comment by davidalger** [comment] 2016-02-01 02:54
Also, thanks for providing the detail of your installation! :)

**Comment by joebusby** [comment] 2016-02-01 13:20
Okay,

Thanks for the help.  I tried E_NOTICE disable, but could get no 
success.

Maybe this will be fixed in the next release.

Joe.

**Comment by julien30** [comment] 2016-02-04 11:11
Hello,
I have the same problem with Magento 2.0.2
Server Deb8
PHP 5.6
max_input_vars -> 5000

I try with only 2 configurations

Julien

**Comment by dmcmillin** [comment] 2016-03-15 19:31
unfortunately this issue is still present within magento 2. Same as Julien30 but attempted to create 130 configurable products. system errors, with the sql issue. resets the product to simple, then ask you to reenter price. then allows you to save never notifying you until you see the product screen that it saved as a simple product.

**Comment by mslabko** [comment] 2016-04-28 17:05
Internal ticket for this issue: MAGETWO-51772

**Comment by PieterCappelle** [comment] 2016-08-23 08:32
Any update on this ticket? In my case problem was fixed updating max_input_vars to 5000.

**Comment by veloraven** [comment] 2016-10-26 07:30
For develop was fixed in b75fc4f8
For 2.0 - Internal ticket MAGETWO-57645

**Comment by claridgicus** [comment] 2016-11-02 00:43
Is this slated for 2.1.3?

**Comment by choukalos** [comment] 2017-01-25 21:01
Yes; it's fixed in 2.1.3.  Closing this Github issue.

**Closed as completed by choukalos** 2017-01-25 21:01 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog

**Comment by peexl-dev** [comment] 2017-02-08 08:45
It is stil present in 2.1.3 when trying to save 150+ configurations with images i got 
Notice: Undefined index: weight

**Comment by rudik99** [comment] 2017-02-08 09:18
@peexl-dev I think you have a different issue - just check you have a weight in all your simple product >0 and same for your config product before you save

**Comment by peexl-dev** [comment] 2017-02-08 09:25
@rkhoury82 wheight is> 0 and if you do the same thing but without images everything is OK
