### ISSUE TITLE
Category Layout Update XML not working on frontend

### ISSUE THREAD

**Issue by test4295** [magento/magento2#31254] opened 2020-12-11 05:37 UTC
### Preconditions (*)

1.Magento 2.3.2
2.Default Mode

### Steps to reproduce (*)

1.In category admin, catalog > category > select category > Design >Layout
2. Select custom layout 

### Expected result (*)

1. Updated layout should be show on frontend page-layout-customlayout

### Actual result (*)

1. It is showing page-layout-1column not updated layout showing in default mode

**Comment by engcom-Alfa** [comment] 2020-12-14 12:23
Duplicate of #27942

**Closed as completed by engcom-Alfa** 2020-12-14 12:23 UTC
Labels: Issue: ready for confirmation, Reported on 2.3.2
