### ISSUE TITLE
bug on the template

### ISSUE THREAD

**Issue by aymen123233** [magento/magento2#36766] opened 2023-01-23 10:54 UTC
### Summary

hello , when i open magento admin and i connect , the page of admin dsiplay only in forms of texts , no image nothing only texts .

### Examples

![Capture d’écran (43)](https://user-images.githubusercontent.com/64594180/214022600-2f426417-d857-4caf-80ab-30d7329fd5d8.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-01-25 12:16
Hi @aymen123233,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.We are able to login to Magento Admin.

Kindly run `bin/magento setup:static-content:deploy -f`


Kindly follow Installation guide https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/composer.html?lang=en for installing Magento.


Please let us know if you are still facing any issue.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-02-06 10:31
Hi @aymen123233,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-02-06 10:31 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.x
