### ISSUE TITLE
Magento 2 sales report issue

### ISSUE THREAD

**Issue by naveen0592** [magento/magento2#26412] opened 2020-01-16 05:35 UTC
I am getting error in the magento 2.2 reports. When I try to generate reports for a specific time period for e.g for between two dates some of the order are not showing the sale amount in the reports while the amount is their if I am checking the order section. 
Can anyone tell me about the issue what is wrong with it?
How can I solve this issue?

**Comment by engcom-Hotel** [comment] 2020-01-17 15:51
Hello @naveen0592 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the latest 2.4-develop branch by provided steps.

We are closing this issue due to branch `2.2-develop` was closed and
> Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.

 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

Thanks for your report!

**Closed as completed by engcom-Hotel** 2020-01-17 15:51 UTC
Labels: Issue: Format is not valid, Reported on 2.2.x
