### ISSUE TITLE
Bulk Uploading & Website gets slow

### ISSUE THREAD

**Issue by w130pmpo** [magento/magento2#9056] opened 2017-03-29 20:34 UTC
### Preconditions

1. Magento version 2.1.3
2. Php 7.0.13-1 Apache2

### Steps to reproduce

1. Creating or updating Bulk Products from CLI using php script

### Expected result

1. Normal speed as long as cache reside

### Actual result

1. Whenever product->save() toggled, loading pages where list products (Category, Page that includes Product Widget) get slow. (Currently around 200K products are stored)

Note,

--- When This Script is not running
1. If there is no cache, it takes around 15-20 sec to load entire these page.
2. If there is cache, it takes around 2-3 sec to load entire these page.

-- When This Script is running
1. Even though there is cache, it takes around 15-20 sec to load entire these page after product->save() toggled.

Any Idea?

**Comment by magento-engcom-team** [comment] 2017-11-30 13:30
@w130pmpo, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-11-30 13:30 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
