### ISSUE TITLE
Customer address in admin order details like company name in not work website wise

### ISSUE THREAD

**Issue by faizanbegsm** [magento/magento2#23254] opened 2019-06-14 06:45 UTC
### Preconditions (*)
1. Magento version 2.2.7
1. On Multiwebsite 
1. In Admin view order details customer address information Billing and Shipping. Company name not showing website wise it only show when Show Company setting under customer configuration is set as optional in base website whose id is 1. If you go to different scope in setting and change to no for second website there is no changes occurred.

### Steps to reproduce (*)
1. In Admin view order details customer address information Billing and Shipping. Company name not showing website wise it only show when Show Company setting under customer configuration is set as optional in base website whose id is 1. If you go to different scope in setting and change to no for second website there is no changes occurred.
1. Attributes like company name, vat show etc depends on website whose id is 1 in admin order details. 
1. Suppose you have an order of france website and its id is website id is 2. If you change the setting in website scope like Show Company to Optional and in default Show Company is No then in France order in admin section customer address details Company name not visible. but when you change the setting in first website whose id is 1 then it show the company name in address admin order details.

### Expected result (*)
1. Company name, Show Fax etc attributes must show in order details customer address information website wise setting.

### Actual result (*)
1. Company name, Show Fax etc attributes work only on website whose id is 1.

**Comment by magento-engcom-team** [comment] 2019-06-14 07:43
:white_check_mark: Confirmed by @engcom-qa-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17497`, `MC-17498` were created

**Issue Available**: @engcom-qa-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krzysztofjasniok** [comment] 2019-09-15 15:48
Issue not reproducible on 2.3-develop.

**Comment by engcom-Bravo** [comment] 2019-09-16 13:05
Hi @krzysztofjasniok. The issue is still reproduced on the latest develop version. If You haven't manage to reproduce it that's only because You missed something in the order of reproduction. In fact the issue comes not from the website's id=1 but from the setting of Default Website. The confusion origins from after You install a fresh instance the default website is the one with id=1.
First, I think the bug here begins already in that Show Company field in Customer Configuration -> Name and Address Options should not affect Backend as those options are designated for [Frontend](https://docs.magento.com/m2/ce/user_guide/customers/name-address-options.html). The second is the Default Website setting. So have two websites with ids 1 (set as default website) and 2 (Show Company = "optional" for both of them); have two customers on each of the websites with addresses containing some companies' names; and finally have two orders created by those customers. So there has to be one order per website. Now go to admin and watch each order's, lets say, Billing Address - You shall see the according company's name in there. Now change Show Company to "no" for the website with the id of 2 and go back to watch the orders - the situation remains the same: in both orders the addresses contain the company's name. Then set website with id 2 as the default one and get back to watch the orders - companies' names are missing in orders' addresses.

**Comment by magento-engcom-team** [comment] 2019-09-16 13:05
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20168` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Closed as completed** 2021-05-25 05:11 UTC
Labels: Issue: Ready for Work, Component: Customer, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Priority: P2, Severity: S2, Progress: done
