### ISSUE TITLE
After upgrading from Magento 2.2.3 to 2.3.2 some categories are broken in the backend

### ISSUE THREAD

**Issue by benlau87** [magento/magento2#24507] opened 2019-09-07 14:02 UTC
### Preconditions (*)

1. Magento Version 2.3.2 (after update)

### Steps to reproduce (*)

1. In Admin Panel click on Catalog -> Categories -> a specific category

### Expected result (*)

1. See Category information and options

### Actual result (*)

1. (only for some categories) error is thrown: "Cannot use string offset as an array"

So it seems that during the update some categories have been corrupted. 

While indexing one error is thrown, but I am not sure if it is related:
Algolia Search Categories indexer process unknown error:
Item (Magento\Catalog\Model\Category\Interceptor) with the same ID "35" already exists.

**Comment by konarshankar07** [comment] 2019-09-07 14:32
Hello @benlau87 ,
I think this issue is regarding `url_rewrite` table and not an issue of magento. Please search the `url_rewrite` table for the mention category id (35)
Thanks

**Comment by benlau87** [comment] 2019-09-07 15:40
Thanks @konarshankar07 .
I deleted the duplicate entry in the url_rewrite and It fixed the indexing problem. But the described problem here with the category page in the admin panel still persists.

**Comment by engcom-Charlie** [comment] 2019-09-10 07:08
Hello @benlau87 
We are not able to reproduce this issue(about errors in category pages) on the lates 2.3-develop branch by provided steps.
So i close this issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-09-10 07:08 UTC
Labels: Issue: Format is valid
