### ISSUE TITLE
Unable to cancel order in Payment Review status

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#26158] opened 2019-12-20 21:14 UTC
### Preconditions (*)

Magento 2.3.3

### Steps to reproduce (*)

1. Create an order
2. Make sure the order gets stuck in Payment Review status, could happen for a variety of reasons
3. Try to cancel order (not possible). No cancel button, and cancel action on grid does not work.
4. Order will be stuck in Payment Review status permanently

### Expected result (*)

Able to cancel an order in Payment Review status

### Actual result (*)

Not able to cancel an order in Payment Review status

**Comment by engcom-Alfa** [comment] 2020-02-20 14:25
Hi, @Zyles. Thank you for your report.

This is the expected behavior that we cannot cancel an order in the payment review status.
At this stage, the bank decides whether to accept or decline the payment.
![1582208472046](https://user-images.githubusercontent.com/51679138/74942355-cd553980-53fc-11ea-963a-6cdeef520423.png)

Suppose the bank withdraws money from the account and at the same time we canceled the order.
And that's not good.
So, we have to close it.
Thanks!

**Closed as completed by engcom-Alfa** 2020-02-20 14:25 UTC
Labels: Issue: Format is valid

**Comment by Zyles** [comment] 2020-02-20 14:50
Your graph fails when Paypal fails to update your order.

**Comment by snez** [comment] 2021-12-07 11:37
@engcom-Alfa The provided diagram seems to be wrong. Magento does not set Payment Pending based on Fraud status. It sets it based on whether the payment is pending, i.e. the deferred payment path in the diagram. If you look inside Sales/Model/Order/Payment/State/AuthorizeCommand.php, you will notice the following:

![image](https://user-images.githubusercontent.com/249977/145022430-97576c97-9e29-4740-b989-4ff5bd7eb9ce.png)
