### ISSUE TITLE
Authorize vs Capture vs Authorize and Capture

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#7449] opened 2016-11-16 11:03 UTC
In di.xml, most payment methods are adding an additional command called 'sale'.

```
    <virtualType name="myCommandPool" type="Magento\Payment\Gateway\Command\CommandPool">
        <arguments>
            <argument name="commands" xsi:type="array">
                <item name="authorize" xsi:type="string">myAuthorizeCommand</item>
                <item name="capture" xsi:type="string">myGatewayCaptureCommand</item>
                <!--<item name="sale" xsi:type="string">mySaleCommand</item>-->
            </argument>
        </arguments>
    </virtualType>
```

This is a workaround as their is only 1) authorize 2) capture but not an additional 'authorize & capture' (i.e. sale) command.

Steps to reproduce:

If you set your payment method to 'authorize':

We do authorize with payment gateway
We then later have to settle it (capture) in the admin panel or some other method.

If you set your payment method to 'authorize and capture'

If you set your payment method to 'authorize and capture' it runs the capture command. This is also run when you manually capture the order using a previous order set to authorize only.

Solution:

Does it make sense therefore to add another command 'authorize_capture' which is called upon when payment method is set to 'authorize_capture'?

That way we can separate the logic from capture and authorize and capture?

**Comment by veloraven** [comment] 2016-11-17 11:59
@craigcarnell  thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by YevSent** [comment] 2016-11-18 16:01
Hi, @craigcarnell.
I will try to explain how it works and why we need `authorize`, `sale`, `capture` commands.

`authorize` - processes transaction for authorization
`sale` (authorize & capture) - processes authorization and capture for transaction
`capture` - captures transaction based on already authorized transaction

For example, if you open Braintree payment gateway [DI](https://github.com/magento/magento2/blob/develop/app/code/Magento/Braintree/etc/di.xml#L124) configuration, you will see all three commands. But the `capture` command is a [strategy command](https://github.com/magento/magento2/blob/develop/app/code/Magento/Braintree/Gateway/Command/CaptureStrategyCommand.php), which allows getting `sale` or `capture` command.

We need this workaround because Magento Sales performs `capture` action for `sale` (authorize & capture) instead real `authorize_capture` - [Payment::processAction](https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/Model/Order/Payment.php#L434).

This is known issue and will be fixed according to it priority (internal ticket MAGETWO-62684).

**Comment by veloraven** [comment] 2016-11-24 14:30
@craigcarnell  the GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions next time.

**Closed as completed** 2017-11-24 10:05 UTC
Labels: Issue: Ready for Work, improvement, Component: Payment, Component: Sales, Issue: Format is not valid
