### ISSUE TITLE
Admin dashboard Most Viewed Products Tab statistics not updating, database table also not updating.

### ISSUE THREAD

**Issue by VikasSingh1694** [magento/magento2#33389] opened 2021-06-30 07:41 UTC
### Summary (*)
In the Magento admin dashboard, no products are showing in the most viewed product grid if all products are in different attribute sets (not in default attribute set), even with Magento sample data this grid is always displaying "We couldn't find any records.".
while a visit to many products with registered users.

**Preconditions**

Magento ver. 2.4.1  with sample data

**Steps to reproduce**

1. log in to the Magento admin panel
2. Update "Refresh lifetime statistics" for "Most Viewed" from Reports -> Refresh Statistics
3. Click on "Reload Data" from the admin dashboard
4. Check the Most view product tab from the admin dashboard. 

**Actual Result** 
It should update the viewed products

![123](https://user-images.githubusercontent.com/77429949/123776049-8d556f00-d8ec-11eb-9e46-1e206c5bd169.png)

**Comment by engcom-Hotel** [comment] 2021-07-01 11:14
Hello @VikasSingh1694,

I suggest you to please click on "Reload Data" button on the admin dashboard and check if "Most Viewed Products" are coming the related tab or not.

You can also try on the magento 2 admin panel , go to reports -> statistics -> click on refresh statistics -> on this page select all the values from the top and choose refresh lifetime statistics -> then click on submit.

Please let us know if it is works for you.

**Comment by VikasSingh1694** [comment] 2021-07-02 05:03
Hi @engcom-Hotel, I have tried those steps already, but that didn't work for me.
I have also checked the related database table, there is also no entry related this.

**Comment by engcom-Hotel** [comment] 2021-07-19 07:49
Hello @VikasSingh1694,

We are confirming this issue with an updated description in the section "Steps to reproduce".

Thanksw

**Comment by magento-engcom-team** [comment] 2021-07-19 07:52
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42880` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment] 2024-06-20 06:28
Hi @VikasSingh1694,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.

<img width="1338" alt="Screenshot 2024-06-20 at 11 52 29" src="https://github.com/magento/magento2/assets/51680745/586563d7-34f9-473f-a409-2deb77924d8c">




<img width="1338" alt="Screenshot 2024-06-20 at 11 52 53" src="https://github.com/magento/magento2/assets/51680745/c725d43f-ee14-42a5-8c1f-488b75d0b40f">


We have updated statistics as well still we are not able to see Most Viewed Products from Reports.

Hence we are confirming the issue.

Thanks.

**Comment by VikasSingh1694** [comment] 2024-06-20 07:39
Hi @engcom-Bravo , 

This is issue because it's not updating automatically.
But you can update this data using report menu then select statics and refresh lifetime or specific time. Then you can find the graph. Please try that way.

**Comment by KrasnoshchokBohdan** [comment] 2024-07-12 11:58
@magento I am working on this

**Comment by NitrogenUA** [comment] 2024-07-12 13:48
@engcom-Bravo Reports are by default disabled. While having reports enabled I was unable to reproduce this issue. Can you please verify?
Reference to enable reports: https://magento.stackexchange.com/a/325408/115540

**Comment by KrasnoshchokBohdan** [comment] 2024-07-12 14:32
@magento give me 2.4-develop instance

**Comment by KrasnoshchokBohdan** [comment] 2024-07-12 14:57
Checked on a new instance, the issue was not reproduced with the configuration turned on.
(Store -> Setting -> Configuration -> General -> Reports -> General Options-> Enable Reports)

<img width="1001" alt="image" src="https://github.com/user-attachments/assets/97f77c06-5b07-4b8d-aabf-39956cddbd54">

<img width="909" alt="image" src="https://github.com/user-attachments/assets/d5d9c067-47e4-464b-a38f-415601ce0aa3">

**Comment by engcom-Bravo** [comment] 2024-07-17 06:28
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-07-17 06:41
Hi @KrasnoshchokBohdan,

Thanks for your Contribution!!

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.


<img width="1323" alt="Screenshot 2024-07-17 at 12 09 51" src="https://github.com/user-attachments/assets/5939dbe1-12bd-46a4-b4cb-a50cf112355f">


We are able to view the products.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-17 06:41 UTC
Labels: Issue: Confirmed, Component: Reports, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P3, Progress: done, Reported on 2.4.1, Area: Admin UI
