### ISSUE TITLE
The price of product custom option can't be set to 0.

### ISSUE THREAD

**Issue by zihen** [magento/magento2#4808] opened 2016-06-01 07:12 UTC
## Preconditions
1. Install Magento from `develop` branch.

## Steps to reproduce
1. Add an product custom option (Select Type)
2. Add new row and set price greater than 0.
3. Save product.
4. Change the row price to 0 or empty.
5. Save product.

## Expected result
1. The row price becomes 0.

## Actual result
1. The row price doesn't becomes 0.

**Comment by antboiko** [comment] 2016-06-02 07:38
Hi @zihen , thanks for reporting. We've created internal ticket MAGETWO-51811 to fix this issue.

Best,
Anton.

**Comment by sergei-sss** [comment] 2016-06-06 09:23
At present you can use "0.00" to bypass it:
https://github.com/magento/magento2/issues/4092

**Comment by magento-engcom-team** [comment] 2017-10-03 14:30
@zihen, thank you for your report.
We've created internal ticket(s) MAGETWO-51811 to track progress on the issue.

**Comment by keyurshah070** [comment] 2017-10-22 13:57
I can not reproduce on fresh 2.2 , please check my recordings which I have done in my setup,

https://drive.google.com/file/d/0B8gUImJC3FQoNGZ6YXVhWkxCQW8/view

Kindly confirm @okorshenko  @ishakhsuvarov

**Comment by SpartakusMd** [comment] 2017-10-30 10:03
@keyurshah070 I just saw your video, the issue is a bit different. The result price should be "0". In your case the field remained empty. Even in the case you save the product with an empty price, the saved value should be 0.

**Comment by raumatbel** [comment] 2017-10-30 12:45
@okorshenko can you assign me it please?

**Comment by okorshenko** [comment] 2017-10-31 21:06
The issue has been fixed in 2.2-develop branch and will be available with 2.2.2 release

**Closed as completed by okorshenko** 2017-10-31 21:06 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Issue: Format is valid

**Comment by magento-team** [comment] 2017-10-31 21:08
Internal ticket to track issue progress: MAGETWO-83036

**Comment by magento-team** [comment] 2017-10-31 21:34
Internal ticket to track issue progress: MAGETWO-83037

**Comment by magento-team** [comment] 2017-11-01 21:03
Internal ticket to track issue progress: MAGETWO-83038
