### ISSUE TITLE
Error if CMS pages for different store views with identical URL Key

### ISSUE THREAD

**Issue by sergei-sss** [magento/magento2#4113] opened 2016-04-12 11:04 UTC
## Steps to reproduce
1. Install Magento 2.0.2 / 2.0.4 with sample data.
2. Add store view to website 'Second Store View'.
3. Clear cache, run reindex process from CLI.
4. Create new CMS Page for DEFAULT Store View only -  "Test Default Store" with identifier 'test' - OK.
5. https://www.diigo.com/item/image/4wouz/0y1w
6. Create new CMS Page for SECOND Store View only - "Test Second Store" with identifier 'test' ... 
## Expected result
1. Save CMS Page with no errors (as in Magento 1.x.x.)
## Actual result
1. Error message appears: "URL key for specified store already exists".
2. https://www.diigo.com/item/image/4wouz/g8vx

**Comment by shiftedreality** [comment] 2016-04-15 11:33
Hi @sergei-sss 

I created internal issue MAGETWO-51921
Thank you for submission.

**Comment by BaDos** [comment] 2016-04-18 10:57
Hi @sergei-sss

I cannot reproduce this bug.
Which version of php are you using?

**Comment by sergei-sss** [comment] 2016-04-20 12:11
Hi,
Here is screen phpinfo():
https://www.diigo.com/item/image/4wouz/r0nw

**Comment by OLTC-fperrin** [comment] 2016-05-04 10:07
Hi,

I'm having the same issue here, although the process is a bit different the end result is the same and I can reproduce it every time.

**Store config:**
1 Website
1 Store
2 Store views (EN, FR)

**Process**
1. Create CMS page "Page1" for "All Store Views" (saves page ok, rewrite created for all store views)
2. Edit CMS page "Page1" to set the store view to EN only (saves page ok but rewrite rules not changed in DB, the one for the store FR is still there)
3. Create CMS page "Page2" for the FR store view with same url key as Page1 (unable to save page, error message reads: "URL key for specified store already exists.")

**Thoughts**
Looks like the rewrite rule isn't removed when the page is reassigned to a different store. If I remove the rewrite rule manually the page is saved and works as expected in the front

regards

**Comment by datbunneh** [comment] 2016-05-17 08:18
Hello,

This issue is fixed on main branch.

**Comment by shiftedreality** [comment] 2016-05-17 08:28
Closed as resolved.

**Closed as completed by shiftedreality** 2016-05-17 08:28 UTC
Labels: Issue: Ready for Work, Progress: needs update
