### ISSUE TITLE
Bundle Products - while required options are automatically selected, price calculation error appears.

### ISSUE THREAD

**Issue by creatuitydevelopers** [magento/magento2#4310] opened 2016-04-26 10:57 UTC
## Hello All,

We have encountered an error related to bundle product pages - if there are any required options for a bundle product, then they are automatically selected in frontend, but the price is not updated. Changing the selection is the only way to recalculate the price.
## Steps to reproduce
1. Go to Magento admin panel.
2. Crate a bundle product with various prices for different products options and at least one required option.
3. Go to newly created product on frontend.
4. Click on "Customize and add to cart".
5. You should see the price for your product below "Add to Cart" button.
6. As you can see, the price is lower than minimum price at the top of the page.
7. All the required selections, are automatically pre-selected with cheapest option. However, it does not reflect the total price of the bundle product.
8. After changing pre-selected options to any other you can see that the price changes.
9. Select the value that was pre-selected automatically again. You can see the difference between current price and the one displayed at the very start.
## Expected result
1. Bundle product's price will be calculated correctly even if required options are defined.
## Actual result
1. Bundle product's price is not being calculated correctly if there are any required options.

Screenshots:
1. Price on top of the page:
   ![magento2_issue2a](https://cloud.githubusercontent.com/assets/1653168/14815715/4ad97354-0bad-11e6-8f28-9b640a6a0d46.png)
2. Price of the product with obligatory options:
   ![magento2_issue2b](https://cloud.githubusercontent.com/assets/1653168/14815718/4cfaaf72-0bad-11e6-9afc-80d1307aa834.png)

**Comment by heyitsroberthe** [comment] 2016-04-28 16:50
I tried to reproduce this issue on latest develop of MagentoCE and I could not. I created a bundle product with 3 product options and 2 of them are required. The price range on the frontend shows the correct prices.

Could you provide the following information:
1. Types of products used in the options (simple, virtual, etc)
2. Number of options in the bundle product.
3. Type of input for each option (dropdown, radio, etc)

**Comment by joshuaswarren** [comment] 2016-05-10 15:56
We should've specified - this was on Magento Enterprise, not Community. Not sure if that'll make a difference in attempting to reproduce. I'll see if I can find the original team member who submitted this bug and get those additional details for you.

**Comment by creatuitydevelopers** [comment] 2016-05-12 11:08
Thanks for all your help here, guys!

Just to give you some more background - we have initially found this issue during testing data migration on Magento EE 2.0.4 and were able to reproduce the issue multiple times. The good news is that we cannot recreate the scenario outlined above on clean EE 2.0.5 instance.

Currently we're looking for the source of this issue. We do suspect that it may be related to import processes and continue investigation in this direction.

Once we find the root cause of this weird behavior, we'll give you more details.

**Comment by andimov** [comment] 2016-07-11 14:05
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by joshuaswarren** [comment] 2016-07-11 16:52
@andimov - I'm not sure why this issue was closed? Someone from Creatuity replied on May 12th with more information about the version we were able to reproduce this on, and we didn't hear back from anyone at Magento. 

Was no one else able to reproduce this on EE 2.0.4 or after running an import on newer versions of Enterprise Edition?

**Comment by magento-engcom-team** [comment] 2017-10-23 12:30
@creatuitydevelopers, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-23 12:30 UTC
Labels: bug report, Component: Tax, Issue: Clear Description, Issue: Confirmed, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid
