### ISSUE TITLE
On iPhone5 device newsletter subscription input box not contain complete text (placeholder) 

### ISSUE THREAD

**Issue by dipti2jcommerce** [magento/magento2#20163] opened 2019-01-10 10:53 UTC
On iPhone device newsletter subscription input box not contain complete text (placeholder) 

### Preconditions (*)

1.Issue is arises is 2.5 version 2.3 version of magneto on iPhone device

### Steps to reproduce (*)

1.Go to iphone5 device and check newsletter subscription block above footer 

### Expected result (*)

![2019-01-10_16-11_create new customer account](https://user-images.githubusercontent.com/18118638/50963876-e26e5200-14f3-11e9-8b4e-5af0076076c0.jpg)

### Actual result (*)

![2019-01-10_16-19_about us](https://user-images.githubusercontent.com/18118638/50963889-e9956000-14f3-11e9-939e-edfb5a0b524b.jpg)

**Comment by magento-engcom-team** [comment] 2019-01-10 10:53
Hi @dipti2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dipti2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-10 10:54
Hi @cedarvinda. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by cedarvinda** [comment] 2019-01-10 10:55
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-01-10 10:55
Hi @cedarvinda. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-01-10 10:56
Hi @cedarvinda, here is your [Magento instance](https://i-20163-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20163-2-3-develop.instances.magento-community.engineering/admin](https://i-20163-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-01-10 10:58
@cedarvinda Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-01-10 10:59
@cedarvinda Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-01-10 11:00
@cedarvinda Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-01-10 11:00
@cedarvinda Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-01-10 11:01
@cedarvinda Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97548` were created

**Comment by cedarvinda** [comment] 2019-01-10 11:02
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-01-10 11:02
Hi @cedarvinda. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-01-10 11:02
Hi @cedarvinda, here is your [Magento instance](https://i-20163-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20163-2-2-develop.instances.magento-community.engineering/admin](https://i-20163-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-02-14 20:54
Hi @dipti2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20165 by @cedarvinda in 2.3-develop branch
Related commit(s):
 - [51f1261497bd4fff2ba5221180e66457950632b5](https://github.com/magento/magento2/commit/51f1261497bd4fff2ba5221180e66457950632b5)
 - [c8d4c53d4a2a3b6d0d942453e34fc6161c63097d](https://github.com/magento/magento2/commit/c8d4c53d4a2a3b6d0d942453e34fc6161c63097d)
 - [aa669d346d16e2ad6b3fa8323c175b15797f7b03](https://github.com/magento/magento2/commit/aa669d346d16e2ad6b3fa8323c175b15797f7b03)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-02-14 20:54 UTC
Labels: Issue: Ready for Work, Area: Frontend, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Store

**Comment by magento-engcom-team** [comment] 2019-02-19 17:25
Hi @dipti2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20370 by @dipti2jcommerce in 2.2-develop branch
Related commit(s):
 - [c874bf5176c292b13e403724cb91a7d7ebc40fc6](https://github.com/magento/magento2/commit/c874bf5176c292b13e403724cb91a7d7ebc40fc6)
 - [9f1a322c239f940457b30ceadf137628651e04ad](https://github.com/magento/magento2/commit/9f1a322c239f940457b30ceadf137628651e04ad)

The fix will be available with the upcoming 2.2.9 release.
