### ISSUE TITLE
Summary Count is Wrong Add Multiple Items to Cart using addProductsToCart 

### ISSUE THREAD

**Issue by TheRealHunzik** [magento/magento2#34195] opened 2021-09-29 13:50 UTC
### Preconditions (*)

1. Magento 2.4.2 Commerce
2. PHP 7.4

### Steps to reproduce (*)

1. Add Multiple Items to Cart Using Graphql
```
mutation {
  addProductsToCart(
    cartId: "XRu4kdwSkA2Hi40PwO4jwkhZxa0bu5zA",
    cartItems: [
      {
      	quantity: 1.0,
        sku: "132110100209"
    	},
      {
        quantity: 1.0, 
        sku: "132110100210",
      }
    ]
  ) {
    cart {
      total_quantity
      items {
        product {
          name
          sku
        }
        quantity
      }
    }
  }
}
```
2. Check Cart data in Cart Section [Local Storage]

### Expected result (*)

1. summary_count Should be 2 
2. Items Must Contain 2 Items

### Actual result (*)

1. summary_count  is 1 
2. There are 2 Items in Cart
![Screenshot from 2021-09-29 18-48-04](https://user-images.githubusercontent.com/51072292/135281424-9b7f8a91-77ef-4177-81b8-80065431671a.png)

### Additional Info:

Issue: Only one item summary is displayed in Cart Icon - Summary
![image](https://user-images.githubusercontent.com/60198231/135855555-68fdc14d-5bcf-4bdd-ad42-91b30e001463.png)
![image](https://user-images.githubusercontent.com/60198231/135855599-61758b35-6c87-45ca-a9a9-328e7a529092.png)

**Note:** Due to the above is : If we noticed that even the price is calculating wrong

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [* ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2021-10-04 13:01
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
Steps to reproduce:
GraphQL - Generate Customer Access token 
Get Cart Id of Logged In customer using GraphQL
Run GraphQL Query using POST  - Add 2 Products to Cart
Issue: Only one item summary is displayed in Cart Icon - Summary
![image](https://user-images.githubusercontent.com/60198231/135855555-68fdc14d-5bcf-4bdd-ad42-91b30e001463.png)
![image](https://user-images.githubusercontent.com/60198231/135855599-61758b35-6c87-45ca-a9a9-328e7a529092.png)

**Comment by TheRealHunzik** [comment] 2021-10-05 06:00
@engcom-November this should the P1 Issue because the event the price is calculating wrong [it consider price on 1st product only]

**Comment by shikhamis11** [comment] 2021-10-30 12:59
@magento give me 2.4-develop instance

**Comment by nidhigupta13-ey** [comment] 2021-12-23 05:19
Hi @magento-engcom-team ,

I have worked on this issue and tried to reproduce it. Below are the results:

1.  "addProductsToCart" this mutation is not available inside grapql.
2. I have used addSimpleProductsToCart, addBundleProductsToCart, addConfigurableProductsToCart, addDownloadableProductsToCart these are working fine and showing the correct count in summary. This issue is not reproducible .

Query:
<img width="1246" alt="Screenshot 2021-12-23 at 10 47 41 AM" src="https://user-images.githubusercontent.com/93646392/147191642-d4605d93-2e82-4ebb-aeba-527a7980a911.png">

Result: 
<img width="417" alt="Screenshot 2021-12-23 at 10 48 40 AM" src="https://user-images.githubusercontent.com/93646392/147191710-3c7d9d97-abcc-45a0-ba8e-12d9aa04bd9f.png">

Thanks,

**Comment by TheRealHunzik** [comment] 2021-12-24 13:34
@nidhigupta13-ey 


Dovdocs to addProductToCart Mutation ->  https://devdocs.magento.com/guides/v2.4/graphql/mutations/add-products-to-cart.html

Code Reference  -> https://github.com/magento/magento2/blob/d0dccd89217f4c2021271e2a4cd71b698177fea4/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L29

**Comment by nidhigupta13-ey** [comment] 2021-12-27 05:07
Hello @TheRealHunzik ,

I have tried this in magento 2.4.3 version and I am getting the below :

<img width="1792" alt="Screenshot 2021-12-27 at 10 36 26 AM" src="https://user-images.githubusercontent.com/93646392/147436494-3cd1bfa5-7d8a-48bd-811d-2f77eff93bc5.png">

Thanks,

**Comment by TheRealHunzik** [comment] 2022-02-04 08:05
@nidhigupta13-ey Most Probably the issue is due to your GraphQl connection with host Make sure connection is working fine and schema docs is rendering in playground

**Comment by cpartica** [comment] 2022-03-22 14:52
GraphQL and Luma was never intended to be synced but if it would then Luma as it's a multi page application would have to be refreshed in order to reflect summary as it doesn't contain a subscription mechanism.
We should close this ticket as not supported behavior

**Comment by shikhamis11** [comment] 2022-03-23 17:14
https://github.com/magento give me 2.4-develop instance

**Comment by shikhamis11** [comment] 2022-03-23 17:49
I was able to reproduce this with an older version but It seems working fine on the latest 2.4-develop instance.
Probably the fix is in the commit https://github.com/magento/magento2/commit/10ffde7f6d7603c589767c9eb06ccaaedb4de0b1

**Comment by engcom-November** [comment] 2022-03-24 06:23
Verified the issue again on latest magento version 2.4-develop branch but cannot able to reproduce the issue anymore. Hence closing the issue.
:

**Closed as completed by engcom-November** 2022-03-24 06:23 UTC
Labels: Issue: Confirmed, Component: GraphQL, Reproduced on 2.4.x, Priority: P1, Project: GraphQL, Progress: done, Reported on 2.4.2, Area: Cart & Checkout

**Comment by adarshkhatri** [comment] 2023-07-21 02:52
This was a big big issue. I have been investigating for a day already. It's not only cart summary, but all the `quote->collectTotal()` wouldn't consider all the items. It was only considering the first item. Certainly this new logic in this commit https://github.com/magento/magento2/commit/10ffde7f6d7603c589767c9eb06ccaaedb4de0b1 fixes it.
