### ISSUE TITLE
Compare Down when category_ids comparable

### ISSUE THREAD

**Issue by lealemoel** [magento/magento2#35583] opened 2022-06-07 09:48 UTC
### Preconditions and environment

Hi,

I set the attribute category_ids to comparable and then when I tried to add products in my comparison list, products are added to it, but when I go to the comparision list, it's blank (see video attached).
Comparision list is working perfectly when attribute category_ids is set to no.

- Magento version : 2.4

https://user-images.githubusercontent.com/98949123/172350519-2bdb10dd-b6c2-4116-937d-340de9d6d1e8.mp4

### Steps to reproduce

1. In BO : configure category_ids attribute to comparable
2. Add products to comparision list
3. Go to comparision list
4. See that comparision list is blank

### Expected result

Comparision list should display my products

### Actual result

Comparision list is blank

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-06-07 11:38
Hi @lealemoel ,
Thank you for reporting. Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue.
**Steps performed:**
1. Stores - Attributes- Product - Configured category_ids - Comparable on Storefront - Yes and Save
2. Reindex and cache flush
3. Storefront - Add 2 products to compare  - **No issue. Compare Products page is displayed as expected.**
4. Login to storefront as customer - Add products to compare - No issue. Compare products page is displayed as expected 
Kindly recheck the issue on Magento 2.4-develop branch as it is the upcoming 2.4.x release and provide missing steps if any if the issue is still reproducible.
Thank you.
![image](https://user-images.githubusercontent.com/60198231/172370320-721009da-3aed-44f2-9d17-ee8e9904bb35.png)
![image](https://user-images.githubusercontent.com/60198231/172370354-cab2f96c-ba60-49bf-bcf1-aa323eaeab03.png)

**Comment by engcom-November** [comment] 2022-06-21 11:40
Hi @lealemoel ,
We are closing this issue as there has been no latest update on the same. Kindly reopen/create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-06-21 11:40 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
