### ISSUE TITLE
Credit memo error when order contains deleted product

### ISSUE THREAD

**Issue by chrisbadley** [magento/magento2#37492] opened 2023-05-12 03:30 UTC
### Preconditions and environment

Magento 2.4.6
If a product is sold and then deleted from the database, you cannot create a credit memo for any orders/invoices that contain that product.

Even though there was a recent patch for this issue. 

### Steps to reproduce

1. Add product to store
2. Purchase product
3. Delete the product
4. Try to create a credit memo for the order containing that product.

### Expected result

Credit memo generated

### Actual result

Error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?))' at line 2, query was: SELECT `e`.`entity_id` FROM `catalog_product_super_link` AS `l` INNER JOIN `catalog_product_entity` AS `e` ON e.entity_id = l.parent_id WHERE (l.product_id IN(?))

Credit memo not generated.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-05-12 09:07
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-05-12 13:58
Hi @chrisbadley,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Add product to store
- Purchase product
- Delete the product
- Try to create a credit memo for the order containing that product.


<img width="1445" alt="Screenshot 2023-05-12 at 2 48 05 PM" src="https://github.com/magento/magento2/assets/51680745/79aaefcc-d6a6-4e8f-be86-4e0e7fc4a9e2">



<img width="1451" alt="Screenshot 2023-05-12 at 2 47 54 PM" src="https://github.com/magento/magento2/assets/51680745/76af9ef9-2ab8-4de7-8eae-d765055f15ad">


<img width="689" alt="Screenshot 2023-05-12 at 2 48 24 PM" src="https://github.com/magento/magento2/assets/51680745/efb5a38b-eaa0-4803-8084-798954d76913">



<img width="1430" alt="Screenshot 2023-05-12 at 2 48 52 PM" src="https://github.com/magento/magento2/assets/51680745/4027b529-1d7f-40fe-838f-072a7cf3f2eb">


We are able to create **CREDIT MEMO** after deleting the product from database.

Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by chrisbadley** [comment] 2023-05-12 14:02
> Hi @chrisbadley,
> 
> Thank you for reporting and collaboration.
> 
> Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.
> 
> **Steps to reproduce**
> 
> * Add product to store
> * Purchase product
> * Delete the product
> * Try to create a credit memo for the order containing that product.
> 
> <img alt="Screenshot 2023-05-12 at 2 48 05 PM" width="1445" src="https://user-images.githubusercontent.com/51680745/237928999-79aaefcc-d6a6-4e8f-be86-4e0e7fc4a9e2.png"> <img alt="Screenshot 2023-05-12 at 2 47 54 PM" width="1451" src="https://user-images.githubusercontent.com/51680745/237929124-76af9ef9-2ab8-4de7-8eae-d765055f15ad.png"> <img alt="Screenshot 2023-05-12 at 2 48 24 PM" width="689" src="https://user-images.githubusercontent.com/51680745/237929176-efb5a38b-eaa0-4803-8084-798954d76913.png"> <img alt="Screenshot 2023-05-12 at 2 48 52 PM" width="1430" src="https://user-images.githubusercontent.com/51680745/237929230-4027b529-1d7f-40fe-838f-072a7cf3f2eb.png">
> We are able to create **CREDIT MEMO** after deleting the product from database.
> 
> Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.
> 
> Thanks.

Please attempt the same steps where simple product belongs to a configurable or Bundle product

**Comment by engcom-Bravo** [comment] 2023-05-15 13:07
Hi @chrisbadley,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Add product to store
- Purchase product
- Delete the product
- Try to create a credit memo for the order containing that product.

<img width="1424" alt="Screenshot 2023-05-15 at 1 10 28 PM" src="https://github.com/magento/magento2/assets/51680745/131044f5-c25f-4b2f-a248-ac22ff153ad7">


<img width="1460" alt="Screenshot 2023-05-15 at 1 11 23 PM" src="https://github.com/magento/magento2/assets/51680745/11ca48c5-6766-4e94-b797-8d20cf62d2f7">


<img width="489" alt="Screenshot 2023-05-15 at 1 13 30 PM" src="https://github.com/magento/magento2/assets/51680745/d65490c8-e0b0-4537-bb21-a11a74c5baec">


<img width="1363" alt="Screenshot 2023-05-15 at 1 12 55 PM" src="https://github.com/magento/magento2/assets/51680745/e096cd0c-0b62-4db7-98bf-6fb7e017ef51">



We have deleted product form database which is attached to configurable product and bundle products.We are able to create creditmemo successfully.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-05-26 06:17
Hi @chrisbadley,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-05-26 06:17 UTC
Labels: Issue: needs update, Reported on 2.4.6
