### ISSUE TITLE
after install magento

### ISSUE THREAD

**Issue by hutsanon** [magento/magento2#4941] opened 2016-06-09 12:01 UTC
after install magento

Please tell me this is normaly ?
![snap 2016-06-09 at 18 45 05](https://cloud.githubusercontent.com/assets/19837095/15929011/85731954-2e74-11e6-96ce-3bb40655b6c5.png)

**Comment by arkadiych** [comment] 2016-06-09 13:16
@hutsanon, it looks like images are not accessible, please, check [official magento2 doc](http://devdocs.magento.com/guides/v2.0/install-gde/trouble/tshoot_no-styles.html).
If it doesn't help, please, provide detailed reproducible steps, a reproducible version and environment information.

**Comment by hutsanon** [comment] 2016-06-09 16:33
@arkadiych 

Windows 7
xampp 5.6.21
Magento-CE-2.0.7+sample_data

**Comment by orlangur** [comment] 2016-06-09 16:43
> Please tell me this is normaly ?

No, this is not. Please check the Network tab of Developer Console (Ctrl + Shift + I) - most likely for static files you'll see 403 or 404 status codes. More specific, font file didn't load.

**Comment by hutsanon** [comment] 2016-06-09 17:37
@orlangur 
Yes Please help.
![capture](https://cloud.githubusercontent.com/assets/19837095/15939766/7215a564-2ea3-11e6-9fe5-8d6c022f5459.JPG)

**Comment by hutsanon** [comment] 2016-06-09 18:47
Please tell me why it's so many error ?

![snap 2016-06-10 at 01 43 54](https://cloud.githubusercontent.com/assets/19837095/15942118/471f1318-2ead-11e6-8c8e-11c2fa40455a.png)

**Comment by orlangur** [comment] 2016-06-09 19:12
For me it usually happened due to incorrect filesystem permissions. So, in any unknown situation I just do

```
chmod a+rwx var -R
chmod a+rwx pub/media -R
chmod a+rwx pub/static -R
```

I didn't try to investigate yet why Magento 2 creates folders it is not able to read, will do it if the problem persist in 2.1 stable release.

**Comment by hutsanon** [comment] 2016-06-10 07:20
in 2.1 stable release. ?

Do you mean i must to waiting a new version ?

**Comment by Asitis** [comment] 2016-06-10 08:21
This should work on 2.0.7 as well, it indeed looks like a permission issue. I'd try running these commands (I run 2.1rc2 on a local server and have seen similar issues, all rights-related)
`find var vendor pub/static pub/media app/etc -type f -exec chmod g+w {} \;`
`find var vendor pub/static pub/media app/etc -type d -exec chmod g+w {} \;`
`chmod u+x bin/magento`

And also try clearing the cache, run setup:di:compile etc.

Edit: Here is a video showing the exact same problem and fix: https://youtu.be/m8AxjZEwGns?t=311

**Comment by orlangur** [comment] 2016-06-10 17:25
@hutsanon, no, such `chmod`s worked well for me with any release.

I mean, I'll file a proper bug report if such kind of hack will still be needed in 2.1 stable.

**Comment by hutsanon** [comment] 2016-06-11 07:04
Edit: Here is a video showing the exact same problem and fix: https://youtu.be/m8AxjZEwGns?t=311
@Asitis 
This youtu.be is good work thank you so much.

**Comment by hutsanon** [comment] 2016-06-11 07:04
@orlangur 
thank you you too.

**Comment by hutsanon** [comment] 2016-06-11 07:07
Dear all
I have a new question.
Please tell me how can i Link with paypal ?
![capture](https://cloud.githubusercontent.com/assets/19837095/15983821/cc02af46-2fdd-11e6-9e9f-6750c9f83f2a.JPG)

**Comment by orlangur** [comment] 2016-06-11 13:16
Hi @hutsanon, could you please add your question to http://magento.stackexchange.com/? One thread per question it will not just speed up an answer but will allow to find a solution quicker for anybody else later.

Please close this ticket also if the issue was with permissions and it now disappeared. Let's keep Community focused ;)

**Comment by davidalger** [comment] 2016-06-12 22:28
Closing since the originally reported issue appears has been resolved. As @orlangur pointed out, questions about how to accomplish something are not not what this issue tracker is for. Please post them either in the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/).

**Closed as completed by davidalger** 2016-06-12 22:28 UTC
Labels: Progress: needs update
