### ISSUE TITLE
Warning during search in catalog by multiple custom option values. Warning should not be generated in log.

### ISSUE THREAD

**Issue by arendarenko** [magento/magento2#23557] opened 2019-07-03 12:12 UTC
Warning: strip_tags() expects parameter 1 to be string, array given in /.../magento2/vendor/magento/framework/Filter/StripTags.php on line 48 happens when customer using catalog search with custom option values which is not exist (for example: they existed previously, but later was deleted).

### Preconditions (*)

1. Magento 2.2.8 with sample data

### Steps to reproduce (*)

1. Go to frontend -> Men -> Tops -> Hoodies & Sweatshirts
2. Choose black color
3. Change URL parameter material, add ",11111" to it value

### Expected result (*)

1. Will be found products that related to "black" color filter

### Actual result (*)

1. Founded products that related to "black" color filter
2. Received warning in log file: Warning: strip_tags() expects parameter 1 to be string, array given in **/.../magento2/vendor/magento/framework/Filter/StripTags.php on line 48**

**Comment by engcom-Bravo** [comment] 2019-07-05 08:44
Hello, @alexeya-ven. Thanks for applying. You see, though the attribute is of type multiselect (in Your case materials) in the Backend, it's implementation in the Frontent (Layered Navigation) remains as of single choice type. Please take a note of the following product: Hero Hoodie - one of the products that appears on the page while following Your Steps to Reproduce. This product contains Fleece (value=145) as well as Hemp (value=146) materials. But in Layered Navigation section You can't chose, if You want to, Both of these materials, You can chose ether Fleece or Hemp. In both cases of course Hero Hoodie will appear among the outputted products. And once You have chosen one of the materials the materials filter is no longer available to add another value to it. So again, You are not able to get only those products that contain both materials at the same time, like Hero Hoodie. In the same way filtering via URL won't work ether. It will result in that warning, because the filtering function on some level expects only one value and not an array of values. So if you pass to Your URL "?materials=145,146" it will take to process only 145 and so will output all the products containing Fleece. As for the presence of other part after comma it will cast that warning.

**Comment by Nazar65** [comment] 2019-07-06 21:02
Hi @engcom-Bravo the main reason that the warning should not be generated in log.

**Comment by engcom-Bravo** [comment] 2019-07-08 14:46
@magento give me 2.3-develop instance

**Comment by Nazar65** [comment] 2019-07-08 14:52
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-08 14:52
Hi @Nazar65. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-08 14:53
Hi @Nazar65, here is your [Magento instance](https://i-23557-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23557-2-3-develop.instances.magento-community.engineering/admin](https://i-23557-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment] 2019-07-08 15:12
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-08 15:12
Hi @engcom-Bravo. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-08 15:13
Hi @engcom-Bravo, here is your [Magento instance](https://i-23557-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23557-2-3-develop.instances.magento-community.engineering/admin](https://i-23557-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment] 2019-07-08 15:13
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-08 15:13
Hi @engcom-Bravo. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-08 15:14
Hi @engcom-Bravo, here is your [Magento instance](https://i-23557-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23557-2-2-develop.instances.magento-community.engineering/admin](https://i-23557-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment] 2019-07-08 15:17
Warning should not be generated in log.

**Comment by magento-engcom-team** [comment] 2019-07-08 15:18
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17974`, `MC-17975` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by edenduong** [comment] 2019-07-13 14:53
I fixed this issue in the https://github.com/magento/magento2/pull/23687

**Comment by magento-engcom-team** [comment] 2019-08-15 22:20
Hi @alexeya-ven. Thank you for your report. 
The issue has been fixed in magento/magento2#23687 by @edenduong in 2.3-develop branch
Related commit(s):
 - [be1e905ef04189683b73a4efe0c4812921b5eb51](https://github.com/magento/magento2/commit/be1e905ef04189683b73a4efe0c4812921b5eb51)
 - [ac582d60745d5fa2293196accb54fca39400a17a](https://github.com/magento/magento2/commit/ac582d60745d5fa2293196accb54fca39400a17a)

The fix will be available with the upcoming 2.3.4 release.

**Closed as completed by magento-engcom-team** 2019-08-15 22:20 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Framework/Filter
