### ISSUE TITLE
i export data from orders but didn't appear i wait for more than 1 hour

### ISSUE THREAD

**Issue by MizoAhmed33** [magento/magento2#36850] opened 2023-02-12 07:49 UTC
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

open exported data file

### Expected result

normally i get the data within a minute 

### Actual result

no data exported (( we couldn't find any record))

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-02-13 12:02
Hi @MizoAhmed33,


Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.

We are able to export the file.

Kindly configure the your instance with cron.please follow the document for configuring the cron https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/cli/configure-cron-jobs.html.


Please try to run below command for cron

`bin/magento cron:run`. for exporting the file.


Kindly let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-02-27 06:15
Hi @MizoAhmed33,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-02-27 06:15 UTC
Labels: Issue: needs update, Reported on 2.4.x
