### ISSUE TITLE
Left side of Sales order page cut off

### ISSUE THREAD

**Issue by laamidd** [magento/magento2#38987] opened 2024-07-29 23:30 UTC
### Preconditions and environment

Magento ver. 2.4.7-p1
shared hosting service
linux
Let me know if you get a horizontal scroll bar, or no need for one you get the full page.  I tried on Chrome and IE.  Other pages will do it as well in various parts of the application.  I tried reducing the view size in the browser settings in both browsers and that didn't help.

### Steps to reproduce

From magento admin home screen
click on sales
click on orders
notice that the page that comes up, it;s like the left side is cut off.
![Screenshot 2024-07-29 192441](https://github.com/user-attachments/assets/0d09082a-f761-4afb-96d7-c8cb02491643)

### Expected result

I can't see the page correctly

### Actual result

I get to see the entire page,cnothing cutoff

### Additional information

I don't know what I'm missing from the screens that are cutoff.  are there workarounds?

### Release note

Thank you!

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by laamidd** [comment] 2024-07-29 23:51
Thank you!!

**Comment by laamidd** [comment] 2024-07-30 00:48
ok, thank you!

**Comment by laamidd** [comment] 2024-07-30 00:52
Can you change it back to the simple store front I had before?

**Comment by engcom-Dash** [comment] 2024-07-30 11:12
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2024-07-30 13:46
Hi @laamidd 

Thanks for reporting and collaboration.

Verified the issue on both the Magento 2.4 dev instance and the Magento 2.4.7-p1 instance but the issue is not reproducible.

Steps to reproduce
From Magento admin home screen
click on sales
click on orders

Please review the attached screen recording and let us know if we missed anything.

https://github.com/user-attachments/assets/9c0ed29f-389a-4f52-b4d4-3264ba13f082

**Comment by laamidd** [comment] 2024-07-30 14:01
My left side is hidden behind the magento sidebar toolbar.  I could be
wrong, after watching your video.  I didn't see or get a horizontal scroll
bar.

Unfortunately, I have deleted that www instance, because I was getting
frustrated with the hosting provider.  I'm in the process of getting a
different provider and starting from scratch.  I'm new to magento, but I
have 25 years in IT data centers.  I wanted to add a drop in and I couldn't
get to SU or root to do the install.  So, for that and other reasons I'm
changing.  If I have this issue again, after ensuring I follow the video,
I'll open a ticket again.

We can close this one.  I think it was me... :-(

Thank you for the support, Everyone has been more than helpful.

I look forward to installing/using magento soon on a new hosting provider.

Thank you all,
Bob

**Comment by engcom-Dash** [comment] 2024-07-31 06:23
Hi @laamidd 

As per the above comment, we are closing this issue.

Please feel free to reopen the issue or raise a new ticket if the issue persists.

Thanks.

**Closed as completed by engcom-Dash** 2024-07-31 06:23 UTC
Labels: Issue: needs update, Reported on 2.4.7-p1
