### ISSUE TITLE
AppendReservationsAfterOrderPlacementPlugin afterPlace function doesnt work if SKU ends with a "."

### ISSUE THREAD

**Issue by AJHopper** [magento/magento2#28662] opened 2020-06-10 11:59 UTC
### Preconditions (*)

1. Magento 2.3.5-p1
2. php 7.2

### Steps to reproduce (*)

1. create a configurable product with a numeric sku ending in a "." example 12345.
2. proceed through with a purchase of the product.

### Expected result (*)

1. purchase completes successfully and creates reservations for the order

### Actual result (*)

1. Order places into the back end successfully and payment method charges customer
2. afterPlace function throws an exception of ```Undefined index: 101550. /vendor/magento/module-inventory-sales/Plugin/Sales/OrderManagement/AppendReservationsAfterOrderPlacementPlugin.php on line 132```

This is something of a major issue for us, we have had several customers now go through and attempt to place the order 4+ times as the checkout displays an error saying the order could not be processed - however as the actual error is on the "afterPlace" function, the order has been placed and the customer charged. Resulting in the duplicated orders having to be refunded.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by engcom-Delta** [comment] 2020-08-27 16:02
Hello @AJHopper 
I'm not able to reproduce issue by steps you described on clean 2.4-develop and 2.3.5p-2
What payment and shipping method do you use?
The only error in the console. But no exceptions. 
![Screenshot_130](https://user-images.githubusercontent.com/51681379/91466354-abe77580-e897-11ea-9e2f-2cb5409295d5.png)

**Comment by AJHopper** [comment] 2020-08-27 16:08
hey @engcom-Delta 
What SKU did you use for the product? would the sku be the "Test12."? 

If so then that would work as it expected, it only works for fully numeric skus that end with . 

For example "12345." if it has letters in it the sku is fine.

the reason seems to be because when its handling the sku lookup it converts them to a string from a generic object, and that conversion treats the . at the end of numeric skus as a decimal point with nothing trailing so cuts it off

**Comment by engcom-Delta** [comment] 2020-08-27 16:46
@AJHopper 
I have checked with different variations. 
![Screenshot_132](https://user-images.githubusercontent.com/51681379/91470715-bc9aea00-e89d-11ea-8464-aeeaa6e9da09.png)

**Comment by Tjitse-E** [comment] 2020-11-27 08:54
@AJHopper this might be related to your problem https://github.com/magento/inventory/pull/3249

**Comment by engcom-Bravo** [comment] 2021-01-06 10:51
Hello @AJHopper 

Thank you for your report.

Seems like the issue is already fixed on the latest 2.4-develop installed with and without [Inventory Modules](https://github.com/magento/inventory) 
We have rechecked with different SKU variations and Product types.

Can you please confirm that you are able to reproduce the reported issue on 2.4-develop?

Thank you in Advance

**Comment by AJHopper** [comment] 2021-01-06 10:59
@engcom-Bravo Havent been able to test this on 2.4 at all so am not sure as to if its fixed on that version - not currently in a place where I would be able to test for a while either unfortunately.

**Comment by engcom-Bravo** [comment] 2021-01-06 11:13
@AJHopper Thank you for the quick response.

When you'll have an opportunity to check it, you may use the _@magento give me a_ command and the deployer will create a temporary instance for you. 

Thank you

**Comment by engcom-Bravo** [comment] 2021-02-02 12:26
We are closing this issue as it is not reproducible on the latest 2.4-develop

**Closed as completed by engcom-Bravo** 2021-02-02 12:26 UTC
Labels: Issue: needs update, Reported on 2.3.5-p1
