### ISSUE TITLE
Incompatible change in v2.1.3: added payment token factory without default preference

### ISSUE THREAD

**Issue by ytorbyk** [magento/magento2#8083] opened 2017-01-09 20:52 UTC
### Preconditions
1. There is an extension for some payment method. The extension was build for magento 2.1.* and works fine with v2.1.2.
2. It uses autogenerated `\Magento\Vault\Api\Data\PaymentTokenInterfaceFactory` factory for PaymentToken creating.
3. Starting from v2.1.3 the factory interface is not autogenerated any more. The factory interface was added (with several implementations) without default preference.
4. So there is necessity to specify which factory implementation is supposed to be used (in v2.1.3).
5. This is incompatible change. In v2.1.2 it’s an autogenerated interface/factory which doesn’t require any configuration, but in v2.1.3 the exactly same interface requires DI configuration.

**Comment by antonkril** [comment] 2017-01-10 13:45
Which version of Valut module did your extension depend on? 100.*.* or 100.1.*?

**Comment by YevSent** [comment] 2017-01-10 13:53
Hi, @ytorbyk, thanks for reporting.

These changes planned by design. You should not rely on `PaymentTokenInterfaceFactory` like autogenerated, instead it, you should use the concrete implementation of `PaymentTokenInterfaceFactory`, like built-in `\Magento\Vault\Model\AccountPaymentTokenFactory` or `\Magento\Vault\Model\CreditCardTokenFactory`, or implement your own type of token, because it depends on payment integration and should be chosen by a developer.

But, anyway, we need to discuss this issue and suppose we will add default type for a token.

**Comment by ytorbyk** [comment] 2017-01-10 14:01
@antonkril currently it depends on ^100.1.0

@joni-jones thanks for response. As I understood I have build two versions for 100.1.* and 100.2.* Valut module. In the first case I can use autogenerated factory (there is no any concrete implementation) and in the second I can specify `\Magento\Vault\Model\CreditCardTokenFactory`.
Is that what you mean?

**Comment by YevSent** [comment] 2017-01-10 14:05
Yes, if your Vault integration uses tokens based on credit cards, you need to use `\Magento\Vault\Model\CreditCardTokenFactory`, or `\Magento\Vault\Model\AccountPaymentTokenFactory` for payments, which use payment profiles, like `Authorize.net`, `Braintree PayPal`.

Also, you can use dependency to `PaymentTokenInterfaceFactory` in your code, but need to configure the correct factory via `di.xml` and in that case, your code will be the same for both versions of Vault module.

**Comment by ytorbyk** [comment] 2017-01-10 15:01
Can you please describe more detailed how to configure it for both Vault versions? Because this is the main problem for me. I know how to configure it for each version but not for both.
The module depends on `PaymentTokenInterfaceFactory` interface and I can specify `\Magento\Vault\Model\CreditCardTokenFactory` in DI, but this class doesn't exist in 100.1.1 Vault versions.
Thanks in advance.

**Comment by YevSent** [comment] 2017-01-10 16:36
I meant tokens storing implementation as "code".
The difference will be in DI.xml file, but the implementation of code will be the same. 
In the code, you might use `PaymentTokenInterfaceFactory` but for Vault integrations since Magento 2.1.3, you will need to specify preference or concrete argument via DI.

But, anyway, you always can implement own factory, which can generate needed payment token entity and use it instead `PaymentTokenInterfaceFactory`.

UPD: before Magento 2.1.3 release the `\Magento\Vault\Api\Data\PaymentTokenInterfaceFactory` was not API interface (was not public for 3d party developers and was auto generated), so it's not a breaking change.

**Comment by mcspronko** [comment] 2017-01-12 13:30
@joni-jones Question about \Magento\Vault\Api\Data\PaymentTokenInterfaceFactory.
If the PaymentTokenInterface interface is located in Api directory of a module with @api signature, should extension developers use it as "Official Public API" provided by a module?

Vault module:
100.0.* - PaymentTokenInterface interface exists with @api
100.1.* - PaymentTokenInterface interface exists with @api 

I am afraid it is a breaking change. Marketing version of a product 2.1.3 and module version 100.1.* contains backward incompatible changes and there is no way custom modules will work with 2.1.3.

The Magento\Vault\Api\Data\PaymentTokenInterfaceFactory class in Magento 2.1.3 has no @api which looks weird.

**Comment by YevSent** [comment] 2017-01-12 14:42
Hi, @mcspronko.

Yes, the `PaymentTokenInterface` is public API. But `PaymentTokenInterfaceFactory` was not introduced in Magento code, it was auto-generated.

Actually, we had not planned to add `PaymentTokenInterfaceFactory` in Magento 2.1.3, but for some internal reasons, we added it without `@api` annotation (on the develop branch it's API interface).

Also, it's our mistake what `PaymentTokenInterfaceFactory` doesn't have default preference, but if developers use this interface they always should specify concrete factory for a payment token, like `CreditCardTokenFactory` or `AccountPaymentTokenFactory`, because a type of token depends on payment integration and Magento Vault doesn't know anything about token type.

**Comment by mcspronko** [comment] 2017-01-12 15:15
Hi @joni-jones 

You know that I completely agree with you, right? :)
Everything you said makes sense for me, however changes in Magento 2.1.3 related to Vault module are backward incompatible. I understand this is highlighted in Release notes. Merchants who want to upgrade their Magento website expect that everything will be working as it is right now.

Specifying concrete factory is a new approach which does not work for older Vault versions.

**Comment by ioliinyk** [comment] 2017-02-14 13:44
Hey @ytorbyk  @mcspronko I am closing this issue since you got an answer from @joni-jones . Thank you fro reporting, keep us updated with new issues.

**Closed as completed by ioliinyk** 2017-02-14 13:44 UTC
Labels: bug report, Component: Payment

**Comment by mcspronko** [comment] 2017-02-14 14:28
Hey @ioliinyk

We were expecting to get backported fixes for previous versions of Magento to be able to have 1 version of custom payment integration and vault support without creating 2 different modules for module-vault change.

Thanks.
Cc @maksek_ua
