### ISSUE TITLE
"The specified request cannot be processed" when retrieving store websites

### ISSUE THREAD

**Issue by ispasvalentin22** [magento/magento2#35207] opened 2022-03-18 08:33 UTC
### Preconditions (*)

1. Magento version 2.4.2

### Steps to reproduce (*)

1. Use store endpoint: /rest/default/V1/store/websites

### Expected result (*)

1. Retrieve the store websites

### Actual result (*)

1. I get an error saying "The specified request cannot be processed" without any further information

What could be the reason for this error?

**Comment by engcom-November** [comment] 2022-03-22 05:19
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue:
![image](https://user-images.githubusercontent.com/60198231/159412987-b5034a93-8a94-4967-a3f4-38cf5ca3edc4.png)
@ispasvalentin22 kindly recheck the issue on Magento 2.4-develop branch as it is the upcoming 2.4.x release and have latest code base. Provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-04-04 10:21
Hi @ispasvalentin22 ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-04-04 10:21 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update

**Comment by howdyravi** [comment] 2022-08-08 14:47
> 

@engcom-November The issue occurs when you run it for a different store.

Your current endpoint is :
`<host>/rest/default/V1/store/websites`
Which is currently looking for you default store.

And issue occurs when you run for a specific store.
`<host>/rest/<storeID>/V1/store/websites`

![image](https://user-images.githubusercontent.com/39335589/183445765-a2dc0ac9-93eb-4b41-81e1-6cb6497417e3.png)

**Comment by celorodovalho** [comment] 2022-08-09 21:49
Any update about it?

**Comment by ezardarr** [comment] 2022-08-30 09:32
I am also facing same error issue in calling endpoint : /rest/default/V1/store/websites

**Comment by howdyravi** [comment] 2022-09-07 11:21
Opened a new issue here : https://github.com/magento/magento2/issues/36105
