### ISSUE TITLE
Magento\Catalog\Api\ProductRenderListInterface returns products regardless of visibility

### ISSUE THREAD

**Issue by Floddy** [magento/magento2#20409] opened 2019-01-18 14:39 UTC
### Summary (*)
Magento\Catalog\Api\ProductRenderListInterface returns products regardless of visibility.
Reproduced in 2.2.7, but 2.3-develop has the same error in di.xml.

### Examples (*)
Hard to give an example, but here's some abuse of object manager ran in the magerun2 dev console.
* Find a product that is not visible invividually. In the snippet below, it's a product from the sample data (24-WG081-gray)
* Run the following code:

//Initiating stuff that needs to be initiated...
\Magento\Framework\App\ObjectManager::getInstance()->get('\Magento\Framework\App\State')->setAreaCode(\Magento\Framework\App\Area::AREA_FRONTEND);
\Magento\Framework\App\ObjectManager::getInstance()->configure(\Magento\Framework\App\ObjectManager::getInstance()->get('\Magento\Framework\ObjectManager\ConfigLoaderInterface')->load(\Magento\Framework\App\Area::AREA_FRONTEND));

//Where it actually happens
$sc = \Magento\Framework\App\ObjectManager::getInstance()->get('\Magento\Framework\Api\SearchCriteriaBuilder')->addFilter('sku', '24-WG081-gray')->create();
\Magento\Framework\App\ObjectManager::getInstance()->get('\Magento\Catalog\Api\ProductRenderListInterface')->getList($sc, 1, 'USD')->getItems();

### Expected result
No results on the search

### Actual result
One result on the search

### Proposed solution
The issue is that in this line:
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/CatalogInventory/etc/di.xml#L114
the type has a leading backslash, which for some reason has the effect that Magento\Catalog\Model\ProductVisibilityCondition, as defined here:
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Catalog/etc/di.xml#L1082
is never ran.

Simply removing the leading backslash resolves the issue.

**Comment by magento-engcom-team** [comment] 2019-01-18 14:39
Hi @Floddy. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Floddy do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-18 14:40
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-01-18 14:41
Hi @Surabhi-Cedcoss. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by milindsingh** [comment] 2019-01-18 14:49
@Floddy Thanks for pointing out such a small issue. You can directly create PR for these type of issues. (I have created one this time).

**Comment by magento-engcom-team** [comment] 2019-01-18 14:58
Hi @milindsingh. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-01-18 15:11
@milindsingh Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97833`, `MAGETWO-97834` were created

**Comment by magento-engcom-team** [comment] 2019-01-29 03:48
Hi @Floddy. Thank you for your report. 
The issue has been fixed in magento/magento2#20410 by @milindsingh in 2.3-develop branch
Related commit(s):
 - [f199b7d018db2bd2572a727e92bb51006ef24798](https://github.com/magento/magento2/commit/f199b7d018db2bd2572a727e92bb51006ef24798)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2019-01-29 03:48 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Progress: PR Created, Component: CatalogInventory

**Comment by magento-engcom-team** [comment] 2019-02-04 18:21
Hi @Floddy. Thank you for your report. 
The issue has been fixed in magento/magento2#20886 by @milindsingh in 2.2-develop branch
Related commit(s):
 - [9092e7a98807d2aa611c2cb7161f737984cdd32f](https://github.com/magento/magento2/commit/9092e7a98807d2aa611c2cb7161f737984cdd32f)

The fix will be available with the upcoming 2.2.8 release.
