### ISSUE TITLE
I can't install magento 2.1.1

### ISSUE THREAD

**Issue by duongquyet** [magento/magento2#6485] opened 2016-09-05 02:44 UTC
I try install magento 2.1.1, no sample data but it show a bug. How do i fix it?

http://prntscr.com/ce8bwe

**Comment by andimov** [comment] 2016-09-05 11:07
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by voleye** [comment] 2016-09-22 09:19
Hi @duongquyet could you please provide following information:
- Which magento version did you tried to install?
- How did you installed magento? (git clone, download zip, composer install)
- Which version of php and which extensions installed?

This looks like an environment issue. Please re-check your env with [Installation Guide](http://devdocs.magento.com/guides/v2.1/install-gde/install-quick-ref.html)

**Comment by andimov** [comment] 2016-09-29 10:34
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by andimov** 2016-09-29 10:34 UTC
Labels: Progress: needs update
