### ISSUE TITLE
Bulk API request causes type error

### ISSUE THREAD

**Issue by akovtun** [magento/magento2#35304] opened 2022-04-13 15:35 UTC
### Preconditions (*)

1. Magento 2.4.3-p2

### Steps to reproduce (*)

1. I call Bulk API request
![image](https://user-images.githubusercontent.com/2437431/163212621-b00530b1-e740-41f0-9232-dcbb7e7abafb.png)
or
![image](https://user-images.githubusercontent.com/2437431/163212710-922d5330-6f3b-4ad2-80c8-c113f7498905.png)

### Expected result (*)

1. Response 202 with bulk operation information
![image](https://user-images.githubusercontent.com/2437431/163213005-86b84712-f0ea-4de0-950b-0b0708134965.png)

### Actual result (*)

1. Response 500
![image](https://user-images.githubusercontent.com/2437431/163213326-81b1068d-37e8-4c32-b827-b01c9a9b28de.png)

```
TypeError: Argument 1 passed to Magento\WebapiAsync\Controller\Rest\Asynchronous\InputParamsResolver::resolveBulkItemParams() must be of the type array, string given, called in /app/vendor/magento/module-webapi-async/Controller/Rest/Asynchronous/InputParamsResolver.php on line 129 and defined in /app/vendor/magento/module-webapi-async/Controller/Rest/Asynchronous/InputParamsResolver.php:183
Stack trace:
#0 /app/vendor/magento/module-webapi-async/Controller/Rest/Asynchronous/InputParamsResolver.php(129): Magento\WebapiAsync\Controller\Rest\Asynchronous\InputParamsResolver->resolveBulkItemParams('byCategoryId', 'Inriver\\Adapter...', 'move')
#1 /app/vendor/magento/module-webapi-async/Controller/Rest/AsynchronousRequestProcessor.php(100): Magento\WebapiAsync\Controller\Rest\Asynchronous\InputParamsResolver->resolve()
#2 /app/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\WebapiAsync\Controller\Rest\AsynchronousRequestProcessor->process(Object(Magento\Framework\Webapi\Rest\Request\Proxy))
#3 /app/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /app/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)
#5 /app/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#6 /app/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)
#7 /app/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#8 /app/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#9 /app/pub/index.php(29): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
```

The type error occurs at this place in the code.
![image](https://user-images.githubusercontent.com/2437431/163214836-96ec35a0-7ee1-41db-93fb-b5c29986f98f.png)
https://github.com/magento/magento2/blob/2.4.3-p2/app/code/Magento/WebapiAsync/Controller/Rest/Asynchronous/InputParamsResolver.php#L126

The resolveBulkItemParams method expects an array as the first parameter.
![image](https://user-images.githubusercontent.com/2437431/163215126-6dbf20bf-b7dd-42d6-a0f0-0f253e65aab2.png)
https://github.com/magento/magento2/blob/2.4.3-p2/app/code/Magento/WebapiAsync/Controller/Rest/Asynchronous/InputParamsResolver.php#L182

But the $this->getInputData() method also returns elements not arrays. For example, the string "byCategoryId"
![image](https://user-images.githubusercontent.com/2437431/163216192-b1f8d3f1-1db8-4f3a-bed1-55ba4b6aa1a7.png)

As a workaround, I added the following lines:
![image](https://user-images.githubusercontent.com/2437431/163216750-42549928-c0ab-4673-8683-890e4d89bbf5.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-04-26 08:35
Hi @akovtun , Thank you for reporting and collaboration. However this issue is a duplicate of https://github.com/magento/magento2/issues/35348. We are closing this issue. Please move on to this issue for latest updates / solutions.
Thank you.

**Closed as completed by engcom-November** 2022-04-26 08:35 UTC
Labels: duplicate, Issue: ready for confirmation, Reported on 2.4.3-p2
