### ISSUE TITLE
/rest/V1/orders/{id} does not return price data for bundle product options

### ISSUE THREAD

**Issue by rossparachute** [magento/magento2#38523] opened 2024-03-14 13:31 UTC
### Preconditions and environment

The REST API endpoint _/rest/V1/orders/{id}_ does not return price data for order items that represent chosen bundle options.

It should also be noted that the individual order item endpoint also does not return any price data for an order item representing a chosen bundle product option.

_/rest/V1/orders/items/{id}_

The data is confirmed as being stored in the _sales_order_item_ table under the _product_options_ field.

I might be wrong but it seems the client can't access this data via the API and a plugin will have to be created to extend the response data for both endpoints.

**Env**
- Magento v2.4.6-p3
- PHP v8.1.27
- MariaDB v10.4
- ElasticSearch v7.17
- Debian 4.19.260-1

### Steps to reproduce

1. Create one or more Simple Products with a price that can be used as bundle options
2. Create a bundle product with a price of 0 that has the products you just created as its options
3. Create an order with that bundle product, choosing one or more of the options
4. Query that order data via the endpoint: _/rest/V1/orders/{id}_ or _/rest/V1/orders/items/{id}_ (for a single order item)

### Expected result

We would expect to see all of the order items with price data in some form.

Specifically, the order item(s) that represent a chosen bundle option should have their "price" prop filled with whatever that option cost. This should exist somewhere in the response even if not on the order items themselves.

**Example**
```
{
    ...
    "price": 1.00,
    "price_incl_tax": 1.00
    etc.
    ...
}
```

**Expected Example Response (Trimmed)**
```
{
    "base_currency_code": "GBP",
    "base_grand_total": 21.23,
    "base_subtotal": 17.69,
    "base_subtotal_incl_tax": 21.23,
    "base_subtotal_invoiced": 17.69,
    "base_tax_amount": 3.54,
    "base_tax_invoiced": 3.54,

    "items": [
        {
            "amount_refunded": 0,
            "base_amount_refunded": 0,
            "base_discount_amount": 0,
            "base_discount_invoiced": 0,
            "base_discount_tax_compensation_amount": 0,
            "base_discount_tax_compensation_invoiced": 0,
            "base_original_price": 0,
            "base_price": 17.69,
            "base_price_incl_tax": 21.23,
            "base_row_invoiced": 17.69,
            "base_row_total": 17.69,
            "base_row_total_incl_tax": 21.23,
            "base_tax_amount": 3.54,
            "base_tax_invoiced": 3.54,
            "created_at": "2023-11-20 15:42:30",
            "discount_amount": 0,
            "discount_invoiced": 0,
            "discount_percent": 0,
            "discount_tax_compensation_amount": 0,
            "discount_tax_compensation_invoiced": 0,
            "is_qty_decimal": 0,
            "is_virtual": 0,
            "item_id": 504478,
            "name": "Bundle Product",
            "no_discount": 0,
            "order_id": 1,
            "original_price": 0,
            **"price": 17.69,**
            "price_incl_tax": 21.23,
            "product_id": 2698,
            "product_type": "bundle",
            "qty_canceled": 0,
            "qty_invoiced": 1,
            "qty_ordered": 1,
            "qty_refunded": 0,
            "qty_shipped": 0,
            "quote_item_id": 641421,
            "row_invoiced": 17.69,
            "row_total": 17.69,
            "row_total_incl_tax": 21.23,
            "row_weight": 0,
            **"sku": "BUNDLE",**
            "store_id": 1,
            "tax_amount": 3.54,
            "tax_invoiced": 3.54,
            "tax_percent": 20,
            "updated_at": "2023-11-20 15:57:49",
            "weee_tax_applied": "[]",
            "product_option": {
                "extension_attributes": {
                    "bundle_options": [
                        {
                            "option_id": 1271,
                            "option_qty": 1,
                            "option_selections": [
                                2395
                            ]
                        }
                    ]
                }
            }
        },
        {
            "amount_refunded": 0,
            "base_amount_refunded": 0,
            "base_discount_amount": 0,
            "base_discount_invoiced": 0,
            "base_discount_tax_compensation_invoiced": 0,
            "base_price": 0,
            "base_row_invoiced": 0,
            "base_row_total": 0,
            "base_tax_amount": 0,
            "base_tax_invoiced": 0,
            "created_at": "2023-11-20 15:42:30",
            "discount_amount": 0,
            "discount_invoiced": 0,
            "discount_percent": 0,
            "discount_tax_compensation_invoiced": 0,
            "is_qty_decimal": 0,
            "is_virtual": 0,
            "item_id": 504479,
            "name": "Bundle Option Product #1",
            "no_discount": 0,
            "order_id": 1,
            "original_price": 0,
            "parent_item_id": 504478,
            **"price": 17.69,**
            "product_id": 2579,
            "product_type": "simple",
            "qty_canceled": 0,
            "qty_invoiced": 1,
            "qty_ordered": 1,
            "qty_refunded": 0,
            "qty_shipped": 0,
            "quote_item_id": 641422,
            "row_invoiced": 0,
            "row_total": 0,
            "row_weight": 0,
            **"sku": "SIMPLE_PRODUCT",**
            "store_id": 1,
            "tax_amount": 3.54,
            "tax_invoiced": 3.54,
            "tax_percent": 20,
            "updated_at": "2023-11-20 15:42:30",
            "weight": 0.222,
            "parent_item": {
                "amount_refunded": 0,
                "base_amount_refunded": 0,
                "base_discount_amount": 0,
                "base_discount_invoiced": 0,
                "base_discount_tax_compensation_amount": 0,
                "base_discount_tax_compensation_invoiced": 0,
                "base_original_price": 0,
                "base_price": 17.69,
                "base_price_incl_tax": 21.23,
                "base_row_invoiced": 17.69,
                "base_row_total": 17.69,
                "base_row_total_incl_tax": 21.23,
                "base_tax_amount": 3.54,
                "base_tax_invoiced": 3.54,
                "created_at": "2023-11-20 15:42:30",
                "discount_amount": 0,
                "discount_invoiced": 0,
                "discount_percent": 0,
                "discount_tax_compensation_amount": 0,
                "discount_tax_compensation_invoiced": 0,
                "is_qty_decimal": 0,
                "is_virtual": 0,
                "item_id": 504478,
                "name": "Bundle Product",
                "no_discount": 0,
                "order_id": 1,
                "original_price": 0,
                "price": 17.69,
                "price_incl_tax": 21.23,
                "product_id": 2698,
                "product_type": "bundle",
                "qty_canceled": 0,
                "qty_invoiced": 1,
                "qty_ordered": 1,
                "qty_refunded": 0,
                "qty_shipped": 0,
                "quote_item_id": 641421,
                "row_invoiced": 17.69,
                "row_total": 17.69,
                "row_total_incl_tax": 21.23,
                "row_weight": 0,
                **"sku": "BUNDLE",**
                "store_id": 1,
                "tax_amount": 3.54,
                "tax_invoiced": 3.54,
                "tax_percent": 20,
                "updated_at": "2023-11-20 15:57:49",
                "weee_tax_applied": "[]",
                "product_option": {
                    "extension_attributes": {
                        "bundle_options": [
                            {
                                "option_id": 1271,
                                "option_qty": 1,
                                "option_selections": [
                                    2395,
                                ]
                            }
                        ]
                    }
                }
            },
            "row_total_incl_tax": 0,
            "base_row_total_incl_tax": 0
        }
    ]
}
```

### Actual result

Instead a response is returned with no price data on what each individual bundle option cost or its order item representation cost.

**Response (Trimmed)**
```
{

    "base_currency_code": "GBP",
    "base_grand_total": 21.23,
    "base_subtotal": 17.69,
    "base_subtotal_incl_tax": 21.23,
    "base_subtotal_invoiced": 17.69,
    "base_tax_amount": 3.54,
    "base_tax_invoiced": 3.54,

    "items": [
        {
            "amount_refunded": 0,
            "base_amount_refunded": 0,
            "base_discount_amount": 0,
            "base_discount_invoiced": 0,
            "base_discount_tax_compensation_amount": 0,
            "base_discount_tax_compensation_invoiced": 0,
            "base_original_price": 0,
            "base_price": 17.69,
            "base_price_incl_tax": 21.23,
            "base_row_invoiced": 17.69,
            "base_row_total": 17.69,
            "base_row_total_incl_tax": 21.23,
            "base_tax_amount": 3.54,
            "base_tax_invoiced": 3.54,
            "created_at": "2023-11-20 15:42:30",
            "discount_amount": 0,
            "discount_invoiced": 0,
            "discount_percent": 0,
            "discount_tax_compensation_amount": 0,
            "discount_tax_compensation_invoiced": 0,
            "is_qty_decimal": 0,
            "is_virtual": 0,
            "item_id": 504478,
            "name": "Bundle Product",
            "no_discount": 0,
            "order_id": 1,
            "original_price": 0,
            **"price": 17.69,**
            "price_incl_tax": 21.23,
            "product_id": 2698,
            "product_type": "bundle",
            "qty_canceled": 0,
            "qty_invoiced": 1,
            "qty_ordered": 1,
            "qty_refunded": 0,
            "qty_shipped": 0,
            "quote_item_id": 641421,
            "row_invoiced": 17.69,
            "row_total": 17.69,
            "row_total_incl_tax": 21.23,
            "row_weight": 0,
            **"sku": "BUNDLE",**
            "store_id": 1,
            "tax_amount": 3.54,
            "tax_invoiced": 3.54,
            "tax_percent": 20,
            "updated_at": "2023-11-20 15:57:49",
            "weee_tax_applied": "[]",
            "product_option": {
                "extension_attributes": {
                    "bundle_options": [
                        {
                            "option_id": 1271,
                            "option_qty": 1,
                            "option_selections": [
                                2395
                            ]
                        }
                    ]
                }
            }
        },
        {
            "amount_refunded": 0,
            "base_amount_refunded": 0,
            "base_discount_amount": 0,
            "base_discount_invoiced": 0,
            "base_discount_tax_compensation_invoiced": 0,
            "base_price": 0,
            "base_row_invoiced": 0,
            "base_row_total": 0,
            "base_tax_amount": 0,
            "base_tax_invoiced": 0,
            "created_at": "2023-11-20 15:42:30",
            "discount_amount": 0,
            "discount_invoiced": 0,
            "discount_percent": 0,
            "discount_tax_compensation_invoiced": 0,
            "is_qty_decimal": 0,
            "is_virtual": 0,
            "item_id": 504479,
            "name": "Bundle Option Product #1",
            "no_discount": 0,
            "order_id": 1,
            "original_price": 0,
            "parent_item_id": 504478,
            **"price": 0,**
            "product_id": 2579,
            "product_type": "simple",
            "qty_canceled": 0,
            "qty_invoiced": 1,
            "qty_ordered": 1,
            "qty_refunded": 0,
            "qty_shipped": 0,
            "quote_item_id": 641422,
            "row_invoiced": 0,
            "row_total": 0,
            "row_weight": 0,
            **"sku": "SIMPLE_PRODUCT",**
            "store_id": 1,
            "tax_amount": 3.54,
            "tax_invoiced": 3.54,
            "tax_percent": 20,
            "updated_at": "2023-11-20 15:42:30",
            "weight": 0.222,
            "parent_item": {
                "amount_refunded": 0,
                "base_amount_refunded": 0,
                "base_discount_amount": 0,
                "base_discount_invoiced": 0,
                "base_discount_tax_compensation_amount": 0,
                "base_discount_tax_compensation_invoiced": 0,
                "base_original_price": 0,
                "base_price": 17.69,
                "base_price_incl_tax": 21.23,
                "base_row_invoiced": 17.69,
                "base_row_total": 17.69,
                "base_row_total_incl_tax": 21.23,
                "base_tax_amount": 3.54,
                "base_tax_invoiced": 3.54,
                "created_at": "2023-11-20 15:42:30",
                "discount_amount": 0,
                "discount_invoiced": 0,
                "discount_percent": 0,
                "discount_tax_compensation_amount": 0,
                "discount_tax_compensation_invoiced": 0,
                "is_qty_decimal": 0,
                "is_virtual": 0,
                "item_id": 504478,
                "name": "Bundle Product",
                "no_discount": 0,
                "order_id": 1,
                "original_price": 0,
                **"price": 17.69,**
                "price_incl_tax": 21.23,
                "product_id": 2698,
                "product_type": "bundle",
                "qty_canceled": 0,
                "qty_invoiced": 1,
                "qty_ordered": 1,
                "qty_refunded": 0,
                "qty_shipped": 0,
                "quote_item_id": 641421,
                "row_invoiced": 17.69,
                "row_total": 17.69,
                "row_total_incl_tax": 21.23,
                "row_weight": 0,
                **"sku": "BUNDLE",**
                "store_id": 1,
                "tax_amount": 3.54,
                "tax_invoiced": 3.54,
                "tax_percent": 20,
                "updated_at": "2023-11-20 15:57:49",
                "weee_tax_applied": "[]",
                "product_option": {
                    "extension_attributes": {
                        "bundle_options": [
                            {
                                "option_id": 1271,
                                "option_qty": 1,
                                "option_selections": [
                                    2395,
                                ]
                            }
                        ]
                    }
                }
            },
            "row_total_incl_tax": 0,
            "base_row_total_incl_tax": 0
        }
    ]
}
```

### Additional information

I've assigned **Severity: S2** as this issue does not impact the critical functionality of the Magento store itself.

However, it does critically impact the financial reporting service provided by a third-party via the Magento API.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by elisei** [comment] 2024-03-14 15:04
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2024-03-19 13:12
Hi @rossparachute 

Thanks for reporting and collaboration.

Verified the issue in magento 2.4 dev instance but the issue is not reproducable.

Steps to reproduce
1.Create one or more Simple Products with a price that can be used as bundle options
2.Create a bundle product with a price of 0 that has the products you just created as its options
3.Create an order with that bundle product, choosing one or more of the options
4.Query that order data via the endpoint: /rest/V1/orders/{id} or /rest/V1/orders/items/{id} (for a single order item)

We are seeing price data for bundle product options.

Please refer the below response and let us know if we missed anything.


```{
    "base_currency_code": "USD",
    "base_discount_amount": 0,
    "base_grand_total": 94,
    "base_discount_tax_compensation_amount": 0,
    "base_shipping_amount": 5,
    "base_shipping_discount_amount": 0,
    "base_shipping_discount_tax_compensation_amnt": 0,
    "base_shipping_incl_tax": 5,
    "base_shipping_tax_amount": 0,
    "base_subtotal": 89,
    "base_subtotal_incl_tax": 89,
    "base_tax_amount": 0,
    "base_total_due": 94,
    "base_to_global_rate": 1,
    "base_to_order_rate": 1,
    "billing_address_id": 4,
    "created_at": "2024-03-19 12:12:06",
    "customer_email": "t123@gmail.com",
    "customer_firstname": "t",
    "customer_group_id": 1,
    "customer_id": 2,
    "customer_is_guest": 0,
    "customer_lastname": "123",
    "customer_note_notify": 1,
    "discount_amount": 0,
    "email_sent": 1,
    "entity_id": 2,
    "global_currency_code": "USD",
    "grand_total": 94,
    "discount_tax_compensation_amount": 0,
    "increment_id": "000000002",
    "is_virtual": 0,
    "order_currency_code": "USD",
    "protect_code": "31aab8c3e45b7332b4e4156e9f6eb270",
    "quote_id": 4,
    "remote_ip": "127.0.0.1",
    "shipping_amount": 5,
    "shipping_description": "Flat Rate - Fixed",
    "shipping_discount_amount": 0,
    "shipping_discount_tax_compensation_amount": 0,
    "shipping_incl_tax": 5,
    "shipping_tax_amount": 0,
    "state": "new",
    "status": "pending",
    "store_currency_code": "USD",
    "store_id": 1,
    "store_name": "Main Website\nMain Website Store\nDefault Store View",
    "store_to_base_rate": 0,
    "store_to_order_rate": 0,
    "subtotal": 89,
    "subtotal_incl_tax": 89,
    "tax_amount": 0,
    "total_due": 94,
    "total_item_count": 1,
    "total_qty_ordered": 1,
    "updated_at": "2024-03-19 12:12:08",
    "weight": 999,
    "items": [
        {
            "amount_refunded": 0,
            "base_amount_refunded": 0,
            "base_discount_amount": 0,
            "base_discount_invoiced": 0,
            "base_discount_tax_compensation_amount": 0,
            "base_original_price": 0,
            "base_price": 89,
            "base_price_incl_tax": 89,
            "base_row_invoiced": 0,
            "base_row_total": 89,
            "base_row_total_incl_tax": 89,
            "base_tax_amount": 0,
            "base_tax_invoiced": 0,
            "created_at": "2024-03-19 12:12:06",
            "discount_amount": 0,
            "discount_invoiced": 0,
            "discount_percent": 0,
            "free_shipping": 0,
            "discount_tax_compensation_amount": 0,
            "is_qty_decimal": 0,
            "is_virtual": 0,
            "item_id": 3,
            "name": "bundleproducttesting1",
            "no_discount": 0,
            "order_id": 2,
            "original_price": 0,
            "price": 89,
            "price_incl_tax": 89,
            "product_id": 3,
            "product_type": "bundle",
            "qty_canceled": 0,
            "qty_invoiced": 0,
            "qty_ordered": 1,
            "qty_refunded": 0,
            "qty_shipped": 0,
            "quote_item_id": 3,
            "row_invoiced": 0,
            "row_total": 89,
            "row_total_incl_tax": 89,
            "row_weight": 999,
            "sku": "bundleproducttesting1-simple1",
            "store_id": 1,
            "tax_amount": 0,
            "tax_invoiced": 0,
            "tax_percent": 0,
            "updated_at": "2024-03-19 12:12:06",
            "weight": 999,
            "product_option": {
                "extension_attributes": {
                    "bundle_options": [
                        {
                            "option_id": 1,
                            "option_qty": 1,
                            "option_selections": [
                                3
                            ]
                        }
                    ]
                }
            },
            "extension_attributes": {
                "itemized_taxes": []
            }
        },
        {
            "amount_refunded": 0,
            "base_amount_refunded": 0,
            "base_discount_amount": 0,
            "base_discount_invoiced": 0,
            "base_price": 0,
            "base_row_invoiced": 0,
            "base_row_total": 0,
            "base_tax_amount": 0,
            "base_tax_invoiced": 0,
            "created_at": "2024-03-19 12:12:06",
            "discount_amount": 0,
            "discount_invoiced": 0,
            "discount_percent": 0,
            "free_shipping": 0,
            "is_qty_decimal": 0,
            "is_virtual": 0,
            "item_id": 4,
            "name": "simple1",
            "no_discount": 0,
            "order_id": 2,
            "original_price": 0,
            "parent_item_id": 3,
            "price": 0,
            "product_id": 4,
            "product_type": "simple",
            "qty_canceled": 0,
            "qty_invoiced": 0,
            "qty_ordered": 1,
            "qty_refunded": 0,
            "qty_shipped": 0,
            "quote_item_id": 4,
            "row_invoiced": 0,
            "row_total": 0,
            "row_weight": 0,
            "sku": "simple1",
            "store_id": 1,
            "tax_amount": 0,
            "tax_invoiced": 0,
            "tax_percent": 0,
            "updated_at": "2024-03-19 12:12:06",
            "weight": 999,
            "parent_item": {
                "amount_refunded": 0,
                "base_amount_refunded": 0,
                "base_discount_amount": 0,
                "base_discount_invoiced": 0,
                "base_discount_tax_compensation_amount": 0,
                "base_original_price": 0,
                "base_price": 89,
                "base_price_incl_tax": 89,
                "base_row_invoiced": 0,
                "base_row_total": 89,
                "base_row_total_incl_tax": 89,
                "base_tax_amount": 0,
                "base_tax_invoiced": 0,
                "created_at": "2024-03-19 12:12:06",
                "discount_amount": 0,
                "discount_invoiced": 0,
                "discount_percent": 0,
                "free_shipping": 0,
                "discount_tax_compensation_amount": 0,
                "is_qty_decimal": 0,
                "is_virtual": 0,
                "item_id": 3,
                "name": "bundleproducttesting1",
                "no_discount": 0,
                "order_id": 2,
                "original_price": 0,
                "price": 89,
                "price_incl_tax": 89,
                "product_id": 3,
                "product_type": "bundle",
                "qty_canceled": 0,
                "qty_invoiced": 0,
                "qty_ordered": 1,
                "qty_refunded": 0,
                "qty_shipped": 0,
                "quote_item_id": 3,
                "row_invoiced": 0,
                "row_total": 89,
                "row_total_incl_tax": 89,
                "row_weight": 999,
                "sku": "bundleproducttesting1-simple1",
                "store_id": 1,
                "tax_amount": 0,
                "tax_invoiced": 0,
                "tax_percent": 0,
                "updated_at": "2024-03-19 12:12:06",
                "weight": 999,
                "product_option": {
                    "extension_attributes": {
                        "bundle_options": [
                            {
                                "option_id": 1,
                                "option_qty": 1,
                                "option_selections": [
                                    3
                                ]
                            }
                        ]
                    }
                },
                "extension_attributes": {
                    "itemized_taxes": []
                }
            },
            "extension_attributes": {
                "itemized_taxes": []
            },
            "row_total_incl_tax": 0,
            "base_row_total_incl_tax": 0
        }
    ],
    "billing_address": {
        "address_type": "billing",
        "city": "Culver City",
        "country_id": "US",
        "customer_address_id": 1,
        "email": "t123@gmail.com",
        "entity_id": 4,
        "firstname": "t",
        "lastname": "123",
        "parent_id": 2,
        "postcode": "90232",
        "region": "California",
        "region_code": "CA",
        "region_id": 12,
        "street": [
            "10441 Jefferson Blvd"
        ],
        "telephone": "4231432412"
    },
    "payment": {
        "account_status": null,
        "additional_information": [
            "Check / Money order"
        ],
        "amount_ordered": 94,
        "base_amount_ordered": 94,
        "base_shipping_amount": 5,
        "cc_exp_year": "0",
        "cc_last4": null,
        "cc_ss_start_month": "0",
        "cc_ss_start_year": "0",
        "entity_id": 2,
        "method": "checkmo",
        "parent_id": 2,
        "shipping_amount": 5
    },
    "status_histories": [],
    "extension_attributes": {
        "shipping_assignments": [
            {
                "shipping": {
                    "address": {
                        "address_type": "shipping",
                        "city": "Culver City",
                        "country_id": "US",
                        "customer_address_id": 1,
                        "email": "t123@gmail.com",
                        "entity_id": 3,
                        "firstname": "t",
                        "lastname": "123",
                        "parent_id": 2,
                        "postcode": "90232",
                        "region": "California",
                        "region_code": "CA",
                        "region_id": 12,
                        "street": [
                            "10441 Jefferson Blvd"
                        ],
                        "telephone": "4231432412"
                    },
                    "method": "flatrate_flatrate",
                    "total": {
                        "base_shipping_amount": 5,
                        "base_shipping_discount_amount": 0,
                        "base_shipping_discount_tax_compensation_amnt": 0,
                        "base_shipping_incl_tax": 5,
                        "base_shipping_tax_amount": 0,
                        "shipping_amount": 5,
                        "shipping_discount_amount": 0,
                        "shipping_discount_tax_compensation_amount": 0,
                        "shipping_incl_tax": 5,
                        "shipping_tax_amount": 0
                    }
                },
                "items": [
                    {
                        "amount_refunded": 0,
                        "base_amount_refunded": 0,
                        "base_discount_amount": 0,
                        "base_discount_invoiced": 0,
                        "base_discount_tax_compensation_amount": 0,
                        "base_original_price": 0,
                        "base_price": 89,
                        "base_price_incl_tax": 89,
                        "base_row_invoiced": 0,
                        "base_row_total": 89,
                        "base_row_total_incl_tax": 89,
                        "base_tax_amount": 0,
                        "base_tax_invoiced": 0,
                        "created_at": "2024-03-19 12:12:06",
                        "discount_amount": 0,
                        "discount_invoiced": 0,
                        "discount_percent": 0,
                        "free_shipping": 0,
                        "discount_tax_compensation_amount": 0,
                        "is_qty_decimal": 0,
                        "is_virtual": 0,
                        "item_id": 3,
                        "name": "bundleproducttesting1",
                        "no_discount": 0,
                        "order_id": 2,
                        "original_price": 0,
                        "price": 89,
                        "price_incl_tax": 89,
                        "product_id": 3,
                        "product_type": "bundle",
                        "qty_canceled": 0,
                        "qty_invoiced": 0,
                        "qty_ordered": 1,
                        "qty_refunded": 0,
                        "qty_shipped": 0,
                        "quote_item_id": 3,
                        "row_invoiced": 0,
                        "row_total": 89,
                        "row_total_incl_tax": 89,
                        "row_weight": 999,
                        "sku": "bundleproducttesting1-simple1",
                        "store_id": 1,
                        "tax_amount": 0,
                        "tax_invoiced": 0,
                        "tax_percent": 0,
                        "updated_at": "2024-03-19 12:12:06",
                        "weight": 999,
                        "product_option": {
                            "extension_attributes": {
                                "bundle_options": [
                                    {
                                        "option_id": 1,
                                        "option_qty": 1,
                                        "option_selections": [
                                            3
                                        ]
                                    }
                                ]
                            }
                        },
                        "extension_attributes": {
                            "itemized_taxes": []
                        }
                    },
                    {
                        "amount_refunded": 0,
                        "base_amount_refunded": 0,
                        "base_discount_amount": 0,
                        "base_discount_invoiced": 0,
                        "base_price": 0,
                        "base_row_invoiced": 0,
                        "base_row_total": 0,
                        "base_tax_amount": 0,
                        "base_tax_invoiced": 0,
                        "created_at": "2024-03-19 12:12:06",
                        "discount_amount": 0,
                        "discount_invoiced": 0,
                        "discount_percent": 0,
                        "free_shipping": 0,
                        "is_qty_decimal": 0,
                        "is_virtual": 0,
                        "item_id": 4,
                        "name": "simple1",
                        "no_discount": 0,
                        "order_id": 2,
                        "original_price": 0,
                        "parent_item_id": 3,
                        "price": 0,
                        "product_id": 4,
                        "product_type": "simple",
                        "qty_canceled": 0,
                        "qty_invoiced": 0,
                        "qty_ordered": 1,
                        "qty_refunded": 0,
                        "qty_shipped": 0,
                        "quote_item_id": 4,
                        "row_invoiced": 0,
                        "row_total": 0,
                        "row_weight": 0,
                        "sku": "simple1",
                        "store_id": 1,
                        "tax_amount": 0,
                        "tax_invoiced": 0,
                        "tax_percent": 0,
                        "updated_at": "2024-03-19 12:12:06",
                        "weight": 999,
                        "parent_item": {
                            "amount_refunded": 0,
                            "base_amount_refunded": 0,
                            "base_discount_amount": 0,
                            "base_discount_invoiced": 0,
                            "base_discount_tax_compensation_amount": 0,
                            "base_original_price": 0,
                            "base_price": 89,
                            "base_price_incl_tax": 89,
                            "base_row_invoiced": 0,
                            "base_row_total": 89,
                            "base_row_total_incl_tax": 89,
                            "base_tax_amount": 0,
                            "base_tax_invoiced": 0,
                            "created_at": "2024-03-19 12:12:06",
                            "discount_amount": 0,
                            "discount_invoiced": 0,
                            "discount_percent": 0,
                            "free_shipping": 0,
                            "discount_tax_compensation_amount": 0,
                            "is_qty_decimal": 0,
                            "is_virtual": 0,
                            "item_id": 3,
                            "name": "bundleproducttesting1",
                            "no_discount": 0,
                            "order_id": 2,
                            "original_price": 0,
                            "price": 89,
                            "price_incl_tax": 89,
                            "product_id": 3,
                            "product_type": "bundle",
                            "qty_canceled": 0,
                            "qty_invoiced": 0,
                            "qty_ordered": 1,
                            "qty_refunded": 0,
                            "qty_shipped": 0,
                            "quote_item_id": 3,
                            "row_invoiced": 0,
                            "row_total": 89,
                            "row_total_incl_tax": 89,
                            "row_weight": 999,
                            "sku": "bundleproducttesting1-simple1",
                            "store_id": 1,
                            "tax_amount": 0,
                            "tax_invoiced": 0,
                            "tax_percent": 0,
                            "updated_at": "2024-03-19 12:12:06",
                            "weight": 999,
                            "product_option": {
                                "extension_attributes": {
                                    "bundle_options": [
                                        {
                                            "option_id": 1,
                                            "option_qty": 1,
                                            "option_selections": [
                                                3
                                            ]
                                        }
                                    ]
                                }
                            },
                            "extension_attributes": {
                                "itemized_taxes": []
                            }
                        },
                        "extension_attributes": {
                            "itemized_taxes": []
                        },
                        "row_total_incl_tax": 0,
                        "base_row_total_incl_tax": 0
                    }
                ]
            }
        ],
        "payment_additional_info": [
            {
                "key": "method_title",
                "value": "Check / Money order"
            }
        ],
        "applied_taxes": [],
        "item_applied_taxes": [],
        "converting_from_quote": false,
        "taxes": [],
        "additional_itemized_taxes": []
    }
}
```

**Comment by engcom-Dash** [comment] 2024-04-01 05:37
Hi @rossparachute 

We have noticed that this issue has not been updated for long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel free to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2024-04-01 05:37 UTC
Labels: Issue: needs update, Reported on 2.4.6-p3
