### ISSUE TITLE
.htaccess not downloaded

### ISSUE THREAD

**Issue by cesarkohl** [magento/magento2#3706] opened 2016-03-09 21:13 UTC
Hi everyone,

Somehow my raw Magento clone was without the /.htaccess.
## Steps to reproduce
1. git clone this repository
2. followed the Wizard Setup
## Expected result
1. Access {magento root}/contact
## Actual result
1. {magento root}/contact returns "404 Not found"
## Solution
1. Downloaded the /.htaccess from this repository.
## Doubt
1. Somehow this file wasn't downloaded via git clone.

Best,
Cesar

**Comment by daim2k5** [comment] 2016-03-09 21:35
I tried to reproduce the error but both .htaccess files still exists after the setup via wizard. Have you tried again?

**Comment by daim2k5** [comment] 2016-03-09 21:35
Also maybe you can tell us a little bit more about your environment

**Comment by cesarkohl** [comment] 2016-03-10 13:34
Hi,

I did the same proccess and fortunately it worked fine. Yesterday, probably I copied and pasted all the files in the folder to another empty folder but the hidden files weren't included in it.

Thanks for the help!

**Comment by ishakhsuvarov** [comment] 2016-03-10 14:03
@cesarkohl Looks like your issue is resolved. Closing this ticket for now. Please feel free to reopen if the issue persists.

**Closed as completed by ishakhsuvarov** 2016-03-10 14:03 UTC
Labels: Progress: needs update
