### ISSUE TITLE
•	When a product is sent a second image or a second image is updated via products/{sku}/media response api "message": "The product can't be saved.".

### ISSUE THREAD

**Issue by Aythamiza** [magento/magento2#36381] opened 2022-10-28 07:36 UTC
### Preconditions and environment

- Magento Comunity2.4.3-p2
- When a product is sent a second image or a second image is updated via products/{sku}/media response api "message": "The product can't be saved.".

### Steps to reproduce

1. You sent an image to a product without an image.
2. Sending the second image already fails, the same thing happens if the product previously has more than 1 image.
3. The error also occurs when updating a product with more than one image.

### Expected result

The expected result is that the image is added to the array of images as seen in the document.

### Actual result

The current result is : {
    "message": "The product can't be saved.",
    "tra-ce": "#0 [internal function]: Magento\\Catalog\\Model\\Product\\Gallery\\GalleryManagement->create()\n#1 /var/www/magentoTS/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array()\n#2 /var/www/magentoTS/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->pro-cess()\n#3 /var/www/magentoTS/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispa-tch()\n#4 /var/www/magentoTS/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent()\n#5 /var/www/magentoTS/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magen-to\\Framework\\Interception\\{closure}()\n#6 /var/www/magentoTS/generated/code/Magen-to/Webapi/Controller/Rest/Interceptor.php(23): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins()\n#7 /var/www/magentoTS/vendor/magento/framework/App/Http.php(116): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispa-tch()\n#8 /var/www/magentoTS/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\\Framework\\App\\Http->lau-nch()\n#9 /var/www/magentoTS/vendor/magento/framework/App/Bootstrap.php(264): Magento\\Framework\\App\\Http\\Interceptor->lau-nch()\n#10 /var/www/magentoTS/pub/index.php(29): Magento\\Framework\\App\\Bootstrap->run()\n#11 {main}"
}

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-11-07 15:59
Hi @Aythamiza ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance but unable to reproduce the issue.
**Steps performed:**

1. Navigate to admin Panel > create a simple product with 1 image > save 
2. generate admin integration token using POST request : /rest/default/V1/integration/admin/token
_{
  "username": "admin",
  "password": "admin@123"
}_

3. Then execute the query to upload second image : https://<magento>/rest/V1/products/<sku>/media
_{
    "entry": {
        "mediaType": "image", 
        "position": 1,
        "disabled": false,
        "types": ["image", "small_image", "thumbnail"],
        "content": {
            "base64_encoded_data": "/9j/4AAQSkZJRgABAQAAAQABAAD/A3MD/2Q==",
            "type": "image/jpeg",
            "name": "Randomimage.jpeg"
        }
    }
}_
**No issue: Uploaded 2nd image successfully.**
4. Navigate to admin panel refresh and go to the product where image was added and edit the product > delete the 1st image > save 
5. Go back to postman and Send the request again by updating the image types  
_{
    "entry": {
        "mediaType": "image",
        "position": 1,
        "disabled": false,
        "types": ["image"],
        "content": {
            "base64_encoded_data": "/9j/4AAQSkZJRgABAQAAAQABAAD/A3MD/2Q==",
            "type": "image/jpeg",
            "name": "Randomimage.jpeg"
        }
    }
}_
observe the response 
Go back to admin and check that roles has been updated or not
we are neither facing any issues in sending images for second time or third time , nor getting such response as "The product can't be saved.". We are able to upload and update new and existing images with no issues.
Kindly recheck the behavior on Magento 2.4-develop instance as it is the upcoming 2.4.x release and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-11-21 10:27
Hi @Aythamiza ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-11-21 10:27 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update

**Comment by webloft** [comment] 2023-03-22 08:12
We can verify this issue but it's randomly, 1 of 4 requests are affected by this bug.

The second image may also end with multiple image rolls applied, which was not in the orginal request.
