### ISSUE TITLE
GraphQL categories field under ProductInterface contains disabled categories

### ISSUE THREAD

**Issue by edas11** [magento/magento2#38857] opened 2024-06-21 09:12 UTC
### Preconditions and environment

- Magento version: magento/product-enterprise-edition 2.4.5-p7
- PWA studio version: 12.6.0

### Steps to reproduce

1. Assign a disabled category to a product.
2. Call `getProductDetailForProductPage` PWA studio graphql query with `$urlKey` equal to the url key of product from step 1. Query is similar to this one:
```query getProductDetailForProductPage($urlKey: String!) {
        products(filter: { url_key: { eq: $urlKey } }) {
            items {
                id
                uid
                categories {
                    id
                    uid
                    name
                    breadcrumbs {
                        category_uid
                    }
                }
                // Other product fields
            }
        }
    }
```

### Expected result

The `categories` field in the response contains only active categories.

### Actual result

The `categories` field in the response contains both active and disabled categories.

### Additional information

The following patch for `magento/module-catalog-graph-ql` seems to fix the issue.
```
--- a/Model/Resolver/Categories.php	2024-06-21 09:45:39.372791239 +0300
+++ b/Model/Resolver/Categories.php	2024-06-21 09:53:11.208634862 +0300
@@ -123,6 +123,7 @@
                 if (!$this->collection->isLoaded()) {
                     $that->attributesJoiner->join($info->fieldNodes[0], $this->collection, $info);
                     $this->collection->addIdFilter($this->categoryIds);
+                    $this->collection->addIsActiveFilter();
                 }
                 /** @var CategoryInterface | \Magento\Catalog\Model\Category $item */
                 foreach ($this->collection as $item) {

```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2024-06-27 17:34
Hi @edas11 ,

Verified the issue on 2.4-develop and we are not able to reproduce this issue.

Preconditions and environment

Steps to reproduce:-

1.Assign a disabled category to a product.
2.Graphql query with $urlKey equal to the url key of product from step 1. 

Actual result: The categories field in the response contains only disabled category.

product details

<img width="1439" alt="Screenshot 2024-06-27 at 11 00 13 PM" src="https://github.com/magento/magento2/assets/51681379/b25deb42-117a-45cf-b4ed-dcce0fb4fa97">


<img width="1440" alt="Screenshot 2024-06-27 at 11 00 23 PM" src="https://github.com/magento/magento2/assets/51681379/1071ff10-f183-4414-a42d-8194bf5e01d2">

product assigned to disabled category

<img width="1438" alt="Screenshot 2024-06-27 at 11 01 02 PM" src="https://github.com/magento/magento2/assets/51681379/7f4bedf0-97a0-4a4d-9d86-5625d1cb47f3">

Graphql result

<img width="1430" alt="Screenshot 2024-06-27 at 11 01 30 PM" src="https://github.com/magento/magento2/assets/51681379/b99dbcca-262c-4ba4-973d-24ce054d3b9b">


Please refer the attached screenshots and let us know if we missed anything.

**Comment by engcom-Bravo** [comment] 2024-07-09 05:10
Hi @edas11,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-09 05:10 UTC
Labels: Issue: needs update, reported on 2.4.5-p7
