### ISSUE TITLE
Reorder Configurable Products

### ISSUE THREAD

**Issue by RG-1** [magento/magento2#3820] opened 2016-03-17 11:09 UTC
## Steps to reproduce
1. Magento 2.02
2. Find Configurable Product with two options to choose, like size and color.
   - Add Configurable Product to the cart. Chose size (XS) and color (red).
   - Add Configurable Product to the cart. Chose size (XS) and color (black).
   - Add Configurable Product to the cart. Chose size (XS) and color (orange).
3. Place an order.
4. View order information as a guest (Orders and Returns -> /sales/guest/form/)
5. Reorder
## Expected result
1. Configurable Product added to the shopping cart as in order: 
   - 1 x XS red + 1 x XS black + 1 x XS orange
## Actual result
1. Configurable Product is added to the shopping cart as three items of first configuration:
   - 3 x XS red
2. If you go back to order information page and reorder one more time, then in cart you will have:
   - 4 x XS red + 1 x XS black
## Thank you

Dear Magento Team, thank you for all your hard work. I really appreciate it.

**Comment by quienti** [comment] 2016-03-17 12:11
https://github.com/magento/magento2/issues/3654

**Comment by NadiyaS** [comment] 2016-03-17 15:22
Hi @RG-1 ,
thank you for reporting this issue with detailed steps to reproduce. 
Internal ticket is MAGETWO-50198.
This issue will be closed as duplicate of #3654.

**Closed as completed by NadiyaS** 2016-03-17 15:22 UTC
