### ISSUE TITLE
Magento 2.4.3-p1 Checkout Infinite loop detected

### ISSUE THREAD

**Issue by mahmoudbeikhit** [magento/magento2#34830] opened 2021-12-16 20:50 UTC
### Preconditions (*)
After I upgrade Magento form 2.4 to 2.4.3-p1  get error in Checkout page 

1-Add product to cart and go to checkout page
2-Select any payment method and try to checkout

### Steps to reproduce (*)

1- Add product to cart and go to checkout page
2- Select any payment method and try to checkout
3- I got this error "Internal Error. Details are available in Magento log file. Report ID: webapi-61bba494db91e"

### Expected result (*)
1. Order placed successful

### Actual result (*)

1. error in log file "main.CRITICAL: Report ID: webapi-61bba494db91e; Message: Infinite loop detected, review the trace for the looping path {"exception":"[object] (Exception(code: 0): Report ID: webapi-61bba494db91e; Message: Infinite loop detected, review the trace for the looping path at public_html/vendor/magento/framework/Webapi/ErrorProcessor.php:208, LogicException(code: 0): Infinite loop detected, review the trace for the looping path at public_html/vendor/magento/module-checkout/Model/Session.php:241)"} []"
2- [https://ibb.co/0rgDdZd](url)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by makzef** [comment] 2021-12-17 09:02
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2021-12-23 16:13
Hi @mahmoudbeikhit,
Thank you for reporting the issue.

However, we tried to reproduce it but the issue is not reproducible at our end.



Steps followed to reproduce issue:

1. Installed Magento 2.4.0 (composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.4)

2. Created 40000 products using the performance tools. (php bin/magento setup:perf:generate-fixtures setup/performance-toolkit/profiles/ce/medium.xml)

3. Upgraded the Magento to 2.4.3-p1 by following the steps given in the document (https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html).

4. Added multiple products to the cart and proceed to checkout.

5. I am able to checkout successfully. (See the attached screenshots).
<img width="1428" alt="Screenshot 2021-12-23 at 8 26 44 PM" src="https://user-images.githubusercontent.com/51681618/147266154-e7b2f211-2d95-4408-9ddd-ce40f4683232.png">
<img width="1428" alt="Screenshot 2021-12-23 at 8 35 47 PM" src="https://user-images.githubusercontent.com/51681618/147266171-0c2b1681-c4c0-4df5-a297-9780ac1f1354.png">
<img width="1428" alt="Screenshot 2021-12-23 at 8 36 00 PM" src="https://user-images.githubusercontent.com/51681618/147266176-eeb57c22-cf97-4cf8-8cf4-ddd3ecd64720.png">
<img width="1428" alt="Screenshot 2021-12-23 at 8 36 19 PM" src="https://user-images.githubusercontent.com/51681618/147266179-17239985-7b79-47c6-901f-cf7ecd4aad30.png">



You can observe the error logs available on your system to find out the exact issue. If the issue still persists at your end then please provide some more details like error details, screenshots, or video, accordingly, I’ll try to reproduce it again.



Thanks

**Comment by hostep** [comment] 2021-12-23 17:08
@mahmoudbeikhit: we've seen this problem also a couple of times as of lately. You won't be able to reproduce this on a vanilla Magento installation. But there most likely will be some custom code in your case that is active on the checkout that tries to load the quote from the session. This can sometimes causes infinite loops in php. Try to rewrite the custom code so it gets the quote object from somewhere else and not from the session.

See:
- https://github.com/magento/magento2/issues/30029#issuecomment-693298079 (and the comments below)
- https://dev98.de/2018/07/23/how-a-wrong-carrier-implementation-causes-a-server-outage/

Maybe this can help you further in trying to figure out what causes the issue on your end.

Hope this helps in case you have a similar issue like we did recently. If not, then good luck in finding the problem! 🙂

**Comment by engcom-Hotel** [comment] 2022-01-11 07:36
Hello @mahmoudbeikhit,

Have you tried the solution given by hostep in the [comment](https://github.com/magento/magento2/issues/34830#issuecomment-1000430049). Let me know if this helps you in resolving your issues.

Thanks

**Comment by engcom-Hotel** [comment] 2022-01-25 13:14
Dear @mahmoudbeikhit,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-01-25 13:14 UTC
Labels: Issue: needs update

**Comment by PietroFantini** [comment] 2023-01-27 00:51
> Dear @mahmoudbeikhit,
> 
> We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
> 
> Reth

> Dear @mahmoudbeikhit,
> 
> We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
> 
> Regards

this isn't fixed :(
