### ISSUE TITLE
Guest Cart Id Error

### ISSUE THREAD

**Issue by kal-codes** [magento/magento2#34770] opened 2021-12-07 23:49 UTC
### Preconditions (*)

1. Magento v2.4.2, reproducible in Chrome & Safari. Works correctly in Firefox, despite expectations that it not.

### Steps to reproduce (*)

1. Create a guest cart using `createEmptyCart ` mutation to receive a guest cart id exactly as specified here: https://devdocs.magento.com/guides/v2.4/graphql/tutorials/checkout/checkout-shopping-cart.html?itm_source=devdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=createEmptyCart#create-a-guest-cart
Then use the guest cart id from response to add a product to that cart.

### Expected result (*)

1. Item is added to guest cart successfully.

### Actual result (*)

1. Item is not added to cart due to error:
{
    "errors": [
        {
            "message": "Could not find a cart with ID \"GUEST_CARD_ID\"",
            "extensions": {
                "category": "graphql-no-such-entity"
            },
            "locations": [
                {
                    "line": 3,
                    "column": 13
                }
            ],
            "path": [
                "addVirtualProductsToCart"
            ]
        }
    ],
    "data": {
        "addVirtualProductsToCart": null
    }
}

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [S1] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2021-12-08 11:59
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue.

**Steps performed:**
Created guest cart using below mutation in Chrome browser (Altair GraphQL client extension):
mutation {
  createEmptyCart
}
Item is added to cart using addProductsToCart mutation for guest cart id - No issue
![image](https://user-images.githubusercontent.com/60198231/145204835-3eab829a-3684-4fb3-bdf7-d7a57833945b.png)
   
@KVoisard ,
Kindly recheck the issue on Magento 2.4-develop branch as it has the latest code base and provide missing steps if any if you are still facing issues.
Thank you.

**Comment by KVoisard** [comment] 2021-12-08 19:27
Do you have a public url to that 2.4-develop is accessible from? I'm guessing the one from your screenshot (`http://magento24.local/graphql`) is running from your local..

**Comment by engcom-November** [comment] 2021-12-09 12:53
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2021-12-09 13:07
Verified the issue again using above Magento 2.4-develop bot instance but still the issue is not reproducible:
![image](https://user-images.githubusercontent.com/60198231/145402041-c07d8565-6cca-426e-b231-f396f95fd101.png)

**Comment by engcom-November** [comment] 2021-12-23 05:37
Hi @KVoisard ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-12-23 05:37 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update

**Comment by iba-1** [comment] 2022-05-02 13:44
FYI We're experiencing the same issue but we're unable to reproduce it too as it seems to happen randomly
