### ISSUE TITLE
Something went wrong with processing the default view and we have restored the filter to its original state.

### ISSUE THREAD

**Issue by PapierPlume1** [magento/magento2#37765] opened 2023-07-17 17:11 UTC
### Summary

Something went wrong with processing the default view and we have restored the filter to its original state.

This message populates on the products page everything we go to add a new product. 

### Examples

![Screenshot 2023-07-17 at 12-11-06 Products _ Inventory _ Catalog _ Magento Admin](https://github.com/magento/magento2/assets/139798916/a35f11d5-4e80-41ef-934d-c61725685c2b)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-07-18 09:32
Hi @PapierPlume1,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

<img width="1503" alt="Screenshot 2023-07-18 at 11 56 44 AM" src="https://github.com/magento/magento2/assets/51680745/3f2225e7-a1ae-49a7-a683-b26fcb80b96b">



Sometimes, this error can occur due to version upgrade. Check "catalog_product_entity" table in DB and verify if any Products have NULL as SKU value Run > SELECT * FROM catalog_product_entity WHERE sku IS NULL to check all product not have sku NULL, then update them. Another temporary fix is to clear "ui_bookmark table". > TRUNCATE ui_bookmark; Also make sure to clear cache and add necessary permission/rights.
Kindly recheck the issue on Magento 2.4-develop branch as it has the latest code base and provide missing steps to reproduce if you are still facing the issue. 


Thanks.

**Comment by engcom-Bravo** [comment] 2023-07-25 06:28
Hi @PapierPlume1,

Kindly provide latest update on this https://github.com/magento/magento2/issues/37765#issuecomment-1639876053 Please let us know if you are still facing any issue.


Thanks.

**Comment by PapierPlume1** [comment] 2023-07-25 16:34
Hi yes we are still facing this issue.

**Comment by PapierPlume1** [comment] 2023-07-25 18:56
None of these options seem to work.

**Comment by engcom-Bravo** [comment] 2023-07-26 14:01
Hi @PapierPlume1,

Thanks for your update.

Please refer this comment https://github.com/magento/magento2/issues/35759#issuecomment-1361023670 this may helps you to proceed further and solve the issue.

Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-08-07 06:11
Hi @PapierPlume1,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-08-07 06:11 UTC
Labels: Issue: needs update, Reported on 2.4.x
