### ISSUE TITLE
validate-date-range not working with diffenrent Languages and Date Formats.

### ISSUE THREAD

**Issue by Scarbous** [magento/magento2#31051] opened 2020-11-25 10:34 UTC
https://github.com/magento/magento2/blob/f55f4117d2a87e5a29efd58fbb14fb4c4cd60bee/lib/web/mage/validation.js#L1055

The validator "validate-date-range" dosn't care about the date-format.

**Comment by dverkade** [comment] 2021-04-18 20:14
Posting a comment. Issues should not be automatically closed.

**Comment by engcom-Hotel** [comment] 2021-06-16 09:32
Hi @Scarbous 

We need more information in order to reproduce this issue. So, please help us in providing following information:

- Summary of the issue
- Information on your environment
- Steps to reproduce
- Expected and actual results

Thanks

**Comment by engcom-Hotel** [comment] 2021-06-30 08:15
Hi @Scarbous,

As we are unable to hear from you since past 14 days. Hence we are closing this issue. If you still facing the issue, either you can reopen this or create a new ticket.

Thanks

**Closed as completed by engcom-Hotel** 2021-06-30 08:15 UTC
Labels: Triage: Dev.Experience, Issue: needs update

**Comment by Scarbous** [comment] 2021-06-30 09:05
When I use the 'validate-date-range' with a custom DateFormat in a backend Form the form dosnt take the configured DateFormat.
In my case I want to use an german DateFormat.
