### ISSUE TITLE
Server Side Compiler doesn't import some remote CSS files

### ISSUE THREAD

**Issue by viniciusfabri** [magento/magento2#25119] opened 2019-10-17 12:11 UTC
### Preconditions (*)
1. Blank Magento 2.3.2, 2.3-develop with a custom theme(or just Luma)
2. Server side compiling enabled
3. PHP 7.1.26 & 7.2

### Steps to reproduce (*)
1. On a .less file, import the following URL, according to the [documentation](https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/css-topics/css-preprocess.html):
`@import url("https://fonts.googleapis.com/icon?family=Material+Icons");`
2. Clear `pub/static/*`
3. Run ` bin/magento setup:static-content:deploy -f`

### Expected result (*)
1. The LESS code should be compiled successfully

### Actual result (*)
1. You get the following error:
`[2019-10-17 11:21:16] report.ERROR: File https://fonts.googleapis.com/icon not found. in styles-l.less [] []
`
![image](https://user-images.githubusercontent.com/51680850/67270327-1e8e0480-f4c1-11e9-94fe-d1ba45bd381c.png)

### Root cause
We were able to track down the issue down to the **less.php** library. This URL doesn't work because it doesn't have the "css" word in it, which the library takes into account when importing css files: https://github.com/wikimedia/less.php/blob/master/lib/Less/Tree/Import.php#L44

Not sure how we can fix this in Magento (the library project doesn't have an issue queue), so maybe we can update the documentation instead?

I couldn't find a similar ticket to this, but maybe it's a duplicate. If so feel free to close

**Comment by viniciusfabri** [comment] 2019-10-17 12:18
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-10-17 12:18
Hi @viniciusfabri. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-10-17 12:19
Hi @viniciusfabri, here is your [Magento instance](https://i-25119-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25119-2-3-develop.instances.magento-community.engineering/admin](https://i-25119-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-10-22 13:12
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21973` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by DlennartD** [comment] 2020-02-06 12:36
Just tested on Magento 2.3.3, the issue still appears.

**Comment by hostep** [comment] 2020-02-06 14:08
@viniciusfabri: it looks like issues can be reported again on https://github.com/wikimedia/less.php, so @viniciusfabri or @DlennartD I'd advise you to report it over there. Because if we leave it here in Magento it will never be looked at.

Thanks! 🙂

**Comment by jkenneydaniel** [comment] 2020-05-14 21:37
This issue seems fixed on 2.3.4? I've not encountered this issue on an existing 2.3.4 project and we're doing the exact same thing - presumably 2.3.4 is using a newer version of the lessphp library?

**Comment by hostep** [comment] 2020-05-14 22:15
Strange, because the PR to fix it hasn't been merged yet: https://github.com/wikimedia/less.php/pull/28

**Comment by jkenneydaniel** [comment] 2020-05-20 02:48
@hostep Honestly I'm kind of befuddled as to why this was working previously on a 2.3.4 project but suddenly stopped today. Makes sense - considering as you said the PR to fix this is yet to be merged - either way was sad when I discovered it was also effecting me now 😢

**Comment by gabrieldagama** [comment] 2020-09-22 16:54
Hi @viniciusfabri,

Since the issue isn't related directly to Magento and there is already an issue open on less.php repository I will be closing this issue for now.

Thanks.

**Closed as completed by gabrieldagama** 2020-09-22 16:54 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Css, Partner: Youwe, Triage: Dev.Experience, Progress: done
