### ISSUE TITLE
Rest-API updating product stock_item deletes downloadable_product_links

### ISSUE THREAD

**Issue by EyalAmir** [magento/magento2#21811] opened 2019-03-18 08:39 UTC
### Preconditions (*)

1. Magento 2.4-develop
2. Create regular downloadable product, upload downloadable content

### Steps to reproduce (*)

1. Update product stock_item values using a PUT call. For example: {"product": {"sku": "Download1", "status": "1", "name": "Test Name", "price": "11.99", "type_id": "downloadable", "extension_attributes": {"stock_item": {"manage_stock": false}}}}

### Expected result (*)

1. The stock_item data would be updated and downloadable product links and samples are preserved since they're not included in the extension_attributes being sent in the update.

### Actual result (*)

1. After update product has no links to download content (no downloadable information). This is similar to https://github.com/magento/magento2/issues/15923 except that didn't resolve being able to post a subset of extension_attributes.
![image](https://user-images.githubusercontent.com/51681379/85867318-680dbc80-b7d1-11ea-86df-31c6cbe74301.png)

**Comment by magento-engcom-team** [comment] 2019-03-18 08:39
Hi @EyalAmir. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@EyalAmir do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by EyalAmir** [comment] 2019-03-18 08:40
yes

**Comment by EyalAmir** [comment] 2019-03-18 08:44
yes

Eyal Amir | Co-Founder & COO

* <http://www.farapp.com>*
eyal@farapp.com
(800) 876-4109

**Comment by magento-engcom-team** [comment] 2019-03-18 08:44
Hi @EyalAmir. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-18 08:44
Hi @EyalAmir, here is your [Magento instance](https://i-21811-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21811-2-3-develop.instances.magento-community.engineering/admin](https://i-21811-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-03-18 12:11
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-03-18 13:03
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98758`, `MAGETWO-98759` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-03-21 18:27
Hi @HMF-HFilar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by sanjay-wagento** [comment] 2019-05-04 04:33
I am working on this at #dmcdindia19

**Comment by magento-engcom-team** [comment] 2020-06-30 08:31
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35555` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2020-07-16 00:50
Hi @EyalAmir. Thank you for your report. 
The issue has been fixed in magento/magento2#28799 by @engcom-Charlie in 2.4-develop branch
Related commit(s):
 - [a09d71afe6f0ed68df98e145f3b4f9858ab71c6d](https://github.com/magento/magento2/commit/a09d71afe6f0ed68df98e145f3b4f9858ab71c6d)
 - [7e6827db4b2b08de98a089e6568e515397b54cac](https://github.com/magento/magento2/commit/7e6827db4b2b08de98a089e6568e515397b54cac)
 - [c52c6e9fe9f3f8f4fadb5c1db7f6a1672563b0c8](https://github.com/magento/magento2/commit/c52c6e9fe9f3f8f4fadb5c1db7f6a1672563b0c8)
 - [da41991d724b6a448e31b9ba51b571dbf53e45de](https://github.com/magento/magento2/commit/da41991d724b6a448e31b9ba51b571dbf53e45de)

The fix will be available with the upcoming 2.4.1 release.

**Closed as completed by magento-engcom-team** 2020-07-16 00:50 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Event: dmcdindia1, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P2, Severity: S2
