### ISSUE TITLE
Integration module is not showing up under System->Integrations 

### ISSUE THREAD

**Issue by anarbayramov** [magento/magento2#6484] opened 2016-09-04 18:53 UTC
Hello, 

I've followed all instructions given in 
http://devdocs.magento.com/guides/v2.0/howdoi/webapi/integration.html
### File Tree

this is my module under **app/code/**

```
anar
└── module-testapi
    ├── Setup
    │   └── InstallData.php
    ├── composer.json
    ├── etc
    │   ├── integration
    │   │   ├── api.xml
    │   │   └── config.xml
    │   └── module.xml
    └── registration.php
```
### registration.php

```
<?php
       \Magento\Framework\Component\ComponentRegistrar::register(
     \Magento\Framework\Component\ComponentRegistrar::MODULE,
     'Anar_Testapi',
     __DIR__
     );
```
### composer.json

```
 {
      "name": "Anar_Testapi",
      "description": "create integration from config",
      "require": {
         "php": "~5.5.0|~5.6.0|~7.0.0",
         "magento/framework": "2.0.0",
         "magento/module-integration": "2.0.0"
      },
      "type": "magento2-module",
      "version": "1.0",
      "autoload": {
         "files": [ "registration.php" ],
         "psr-4": {
            "Anar\\Testapi\\": ""
         }
      }
   }
```
### module.xml

```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
       <module name="Anar_Testapi" setup_version="2.0.0">
            <sequence>
                <module name="Magento_Integration"/>
            </sequence>
       </module>
     </config>
```
### api.xml

```
<integrations>
    <integration name="testIntegration">
        <resources>
            <!-- To grant permission to Magento_Log::online, its parent Magento_Customer::customer needs to be declared as well-->
            <resource name="Magento_Customer::customer" />
            <resource name="Magento_Log::online" />
            <!-- To grant permission to Magento_Sales::reorder, all its parent resources need to be declared-->
            <resource name="Magento_Sales::sales" />
            <resource name="Magento_Sales::sales_operation" />
            <resource name="Magento_Sales::sales_order" />
            <resource name="Magento_Sales::actions" />
            <resource name="Magento_Sales::reorder" />
        </resources>
    </integration>
</integrations>
```
### config.xml

```
<integrations>
   <integration name="TestIntegration">
       <email>anar@anar.com</email>
       <endpoint_url>http://anar.com</endpoint_url>
       <identity_link_url>http://anar.com/identity</identity_link_url>
   </integration>
</integrations>
```
## Installation

I installed module like 

**bin/magento module:enable Anar_Testapi**
**bin/magento setup:upgrade**
**bin/magento setup:di:compile**

Seleted module_setup after multiple tries.
Also tried everything mentioned in; 

https://github.com/magento/magento2/issues/4023 
and 
https://github.com/magento/magento2/issues/4824

but still I dont see my integration.

Thank you

**Comment by veloraven** [comment] 2016-11-02 10:10
@rodrane I'm closing this issue as GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you think it to be an issue which requires fixing please create new GitHub issue according to  to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. Please, also identify which version of Magento you are running.

**Closed as completed by veloraven** 2016-11-02 10:10 UTC
Labels: Component: Framework/Webapi

**Comment by fguerret** [comment] 2018-12-13 17:23
I have exactly the same technical issue. The steps are what is written: create the code above and compile. Expected result is the name of the integration (here "TestIntegration") showing in the admin panel under system / integrations, as the documentation says. But the result is that nothing is showing. The feature seems just not to be implemented. As for the version it looks like anarbayramov used 2.0 . As for me I tried with 2.3 ee.
Would it be possible to have a more detailed answer please? Thank you
