### ISSUE TITLE
Swiping gallery product images now working on mobile devices - Magento 2.4.6

### ISSUE THREAD

**Issue by pasichnikroman** [magento/magento2#37586] opened 2023-06-06 15:27 UTC
### Preconditions and environment

- Install magento 2.4.6 with sample data
- issue is reproducible in only 2.4.6 but not in 2.4-develop

### Steps to reproduce

1. Go to any product with a few images in gallery
2. Start swiping 

### Expected result

Images should move inside gallery wrapper on swipe event

### Actual result

Not working

### Additional information

The problem in lib/web/fotorama/fotorama.js , previous version from 2.4.5-x works as expected  

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-06-07 10:22
Hi @pasichnikroman,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

**Steps to reproduce**

- Go to any product with a few images in gallery
- Start swiping

We are able to swipe the images in gallery.

https://github.com/magento/magento2/assets/51680745/7aafa693-ccb4-4a7b-922e-4dd78a769c27


Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by pasichnikroman** [comment] 2023-06-08 16:45
@magento give me 2.4.6 instance

**Comment by pasichnikroman** [comment] 2023-06-08 17:05
@magento give me 2.4.6 instance

**Comment by pasichnikroman** [comment] 2023-06-08 17:08
@magento give me 2.4.6 instance

**Comment by pasichnikroman** [comment] 2023-06-10 11:01
@magento give me 2.4.6 instance

**Comment by pasichnikroman** [comment] 2023-06-13 17:21
@magento give me 2.4.6 instance

**Comment by slavvka** [comment] 2023-06-13 17:59
@magento give me 2.4.6 instance

**Comment by pasichnikroman** [comment] 2023-06-14 08:18
@magento give me 2.4.6 instance

**Comment by pasichnikroman** [comment] 2023-06-14 08:50
@engcom-Bravo Just tested on magento 2.4.6 instance, the problem exists. Same steps.

**Comment by pasichnikroman** [comment] 2023-06-14 09:42
@magento give me 2.4-develop instance

**Comment by pasichnikroman** [comment] 2023-06-14 11:33
@engcom-Bravo on 2.4-develop works fine

**Comment by engcom-Bravo** [comment] 2023-06-15 06:52
@magento give me 2.4.6 instance

**Comment by engcom-Bravo** [comment] 2023-06-15 11:32
Hi @pasichnikroman,

Thanks for update.

Verified the issue on Magento 2.4.6 instance and the issue is reproducible.Kindly refer the screenshots.


**Steps to reproduce**


- Go to any product with a few images in gallery
- Start swiping

We are not able to swipe the images in mobile view.


https://github.com/magento/magento2/assets/51680745/eba57c1e-b2f7-4d91-9269-7bcb68da28a8



The issue is no more reproducible in Magento 2.4-develop instance.issue is only reproducible in Magento 2.4.6 Instance.



Hence Confirming this issue.


Thanks.

**Comment by drinkingsouls** [comment] 2023-06-26 11:44
This looks like a duplicate of issue [#37232](https://github.com/magento/magento2/issues/37232). Maybe check there.
I believe a fix has since been made in the file: https://github.com/magento/magento2/blob/2.4-develop/lib/web/fotorama/fotorama.js

**Comment by tiagosampaio** [comment] 2023-10-03 15:00
https://github.com/magento give me 2.4.6-p2 instance

**Comment by tiagosampaio** [comment] 2023-10-03 15:01
@magento give me a 2.4.6-p2 instance.

**Comment by pasichnikroman** [comment] 2024-01-18 22:42
fixed in 2.4.7-beta

**Comment by engcom-Bravo** [comment] 2024-01-19 05:44
Hi @pasichnikroman,

Thanks for your Update.

Since issue has been fixed in Latest Version.Hence We are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-01-19 05:44 UTC
Labels: Issue: Confirmed, Component: Image, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Product, Reported on 2.4.6
