### ISSUE TITLE
Getting Error on product edit page

### ISSUE THREAD

**Issue by saurastra-developer** [magento/magento2#13003] opened 2018-01-05 04:25 UTC
When i try to access product edit page then iu give following error ..

url: 
  root/admin/catalog/product/edit/id/14997/key/abc/

Notice: Undefined index: container_size in /home/supdev/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php on line 394

<b>container_size</b > is a simple text attribute

in magento 2.2.0
![error](https://user-images.githubusercontent.com/35019950/34595457-3b394364-f1fe-11e7-89fc-1bb81b0c60bd.png)

**Comment by RakeshJesadiya** [comment] 2018-01-07 05:33
Hello I am looking for this issue #mm18in

**Comment by RakeshJesadiya** [comment] 2018-01-07 05:49
@saurastra-developer, We can't reproduce the issue.
Could you please check for other Text attributes, All having same issue or just issue with container_size.

We would close this issue.

**Comment by magento-engcom-team** [comment] 2018-01-10 15:14
@saurastra-developer , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by magento-engcom-team** [comment] 2018-01-24 09:30
@saurastra-developer, we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Closed by magento-engcom-team** 2018-01-24 09:30 UTC
Labels: G1 Failed, mm18in, needs update
