### ISSUE TITLE
Magento 2.1 CE, Attribute value deleted when changing attribute set of a product

### ISSUE THREAD

**Issue by orbitrod** [magento/magento2#6108] opened 2016-08-10 22:58 UTC
### Preconditions

1. Magento ver. 2.1.0 CE
2. PHP 7.0.9 
### Steps to reproduce

1. Find/Create product in admin with attribute set of "Default"
2. Edit product and change attribute set from "Default" to another set.
### Expected result

1. Page should refresh with new attributes from newly assigned set. 
2. Values of attributes that are used in both the "Default" set and new set should remain.

_The functionality described above, worked in Magento 2.0.8 CE._
### Actual result

1. Page refreshes with new attributes from newly assigned set. 
2. Values for attributes that are shared between both sets are deleted.

**Comment by orbitrod** [comment] 2016-08-18 23:41
@sean-jamersan @s00071609 @mikelevy300 You guys commented on another issue I reported, #5999

I was wondering if any of you were having the same problem I reported here, in regards to attribute values being mysteriously deleted.

**Comment by AVoskoboinikov** [comment] 2016-09-07 13:07
Hi, @orbitrod 

As I commented in #5999 - It works fine for me in 2.1.1. Can you upgrade and recheck it? 

Thanks!

**Comment by AVoskoboinikov** [comment] 2016-09-09 12:49
@orbitrod 
Since #5999 is acknowledged bug I've tried to reproduce this issue one more time on 2.1.1 with sample data and it worked fine for me. So please, try to upgrade your installation to 2.1.1 and recheck if you can still reproduce this error.

**Comment by andimov** [comment] 2016-10-10 14:52
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Comment by andimov** [comment] 2016-10-10 14:52
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by andimov** 2016-10-10 14:52 UTC
Labels: bug report, Progress: needs update
