### ISSUE TITLE
Unable to override default error skin

### ISSUE THREAD

**Issue by ecomchallenger** [magento/magento2#8026] opened 2017-01-04 07:41 UTC
### General summary
In Magento CE v. 2.1.2 changing skin value in file pub\errors\local.xml not gives effects. Because of this there is no possibility to create custom error templates in separate skin directory. There is only possibility to add modifications in core default error skin files located in: pub\errors\default.

### Preconditions
Http Server: nginx version: nginx/1.9.10
php: PHP 7.0.13-1~dotdeb+8.1 (cli) ( NTS )
Magento: CE 2.1.2
Current application mode: production

### Steps to reproduce
1. Configure document root in nginx configuration as follows:
root $MAGENTO_ROOT/pub;
2. Copy file: $MAGENTO_ROOT\pub\errors\local.xml.sample into same directory and rename it to: local.xml
3. Modify skin value in file: $MAGENTO_ROOT\pub\errors\local.xml as follows:
<skin>customskin</skin>
4. Create directory: $MAGENTO_ROOT\pub\errors\customskin
5. Copy file: $MAGENTO_ROOT\pub\errors\default\503.phtml into $MAGENTO_ROOT\pub\errors\customskin\503.phtml
6. Modify html content in file: $MAGENTO_ROOT\pub\errors\customskin\503.phtml, to make it visually different from core file: MAGENTO_ROOT\pub\errors\default\503.phtml
7. Enable maintenance mode from cli in $MAGENTO_ROOT directory:
php bin/magento maintenance:enable  
8. Refresh application page in browser
9. In browser should be visible content from file: $MAGENTO_ROOT\pub\errors\default\503.phtml

### Expected result
In browser should be visible content from file: $MAGENTO_ROOT\pub\errors\customskin\503.phtml

### Actual result
In browser is visible content from default core skin file: $MAGENTO_ROOT\pub\errors\default\503.phtml instead of content from customskin file: $MAGENTO_ROOT\pub\errors\customskin\503.phtml

### Debugging results:
Error in file: $MAGENTO_ROOT\pub\errors\processor.php l: 27
current state:
`const ERROR_DIR = 'pub/errors';`
Current state of line 27 from this file causes error in line: 571:
`if (preg_match('/^[a-z0-9_]+$/i', $value) && is_dir($this->_indexDir . self::ERROR_DIR . '/' . $value)) {`
where condition: 
`is_dir($this->_indexDir . self::ERROR_DIR . '/' . $value) `
could not be satisfied because of duplicated "pub" directory in path: 
`$this->_indexDir . self::ERROR_DIR . '/' . $value`

### Fix proposition
Change in file: $MAGENTO_ROOT\pub\errors\processor.php l: 27 from:
`const ERROR_DIR = 'pub/errors';`
to
`const ERROR_DIR = 'errors';`

**Comment by heldchen** [comment] 2017-01-09 13:06
duplicate of #6403

**Comment by vityakopin** [comment] 2017-06-21 08:14
I've linked this GitHub issue to internal ticket MAGETWO-69938.

**Comment by mattgreenfield** [comment] 2017-08-31 13:35
Hi, any progress on this one? I still have issue in 2.1.7. Thanks

**Comment by magento-engcom-team** [comment] 2017-10-20 13:30
@ecomchallenger, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-20 13:30 UTC
Labels: Issue: Ready for Work, bug report, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
