### ISSUE TITLE
Select Option Space issue into backend

### ISSUE THREAD

**Issue by SyntaxKay** [magento/magento2#19657] opened 2018-12-08 12:43 UTC
### Preconditions (*)

1.Magento 2.3-develop

### Steps to reproduce (*)

1.Go to Marketing -> Cart Price value -> Manage Coupon Codes 
2.Under Manage Coupon Codes All select option have inconsistent space.

### Expected result (*)

![expected](https://user-images.githubusercontent.com/33230237/49686037-9dca5200-fb14-11e8-9ed1-27c24a36d5f3.png)

### Actual result (*)

![actual](https://user-images.githubusercontent.com/33230237/49686041-a6bb2380-fb14-11e8-9a1d-17cf245bc54b.png)

**Comment by magento-engcom-team** [comment] 2018-12-08 12:43
Hi @speedy008. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@speedy008 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by rogyar** [comment] 2018-12-08 13:42
Hi @speedy008. Please, provide a description of the issue. At first glance, both screenshots look the same and it's hard to guess what is the issue about. 
Thank you.

**Comment by magento-engcom-team** [comment] 2018-12-10 16:00
Hi @speedy008. Thank you for your report. 
The issue has been fixed in magento/magento2#19659 by @speedy008 in 2.3-develop branch
Related commit(s):
 - [29f6be19ea42ba26d812797db28d9d7c0c16325e](https://github.com/magento/magento2/commit/29f6be19ea42ba26d812797db28d9d7c0c16325e)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2018-12-10 16:00 UTC
Labels: Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Backend
