### ISSUE TITLE
Can't select tax class at product edit after upgrade 

### ISSUE THREAD

**Issue by ymarc77** [magento/magento2#23935] opened 2019-07-29 09:45 UTC
### Precondition (*)
1. Magento 2.2.9
2. PHP 7.1

### Steps to reproduce (*)

Migration 2.2.8 to 2.2.9 seems to be successful but when:
1. Catalog > Product > Add Simple Product (or Edit)
2. There is no "Tax Class Field"
3. Layout is messed
https://i.ibb.co/C1D7f01/Voila-Capture-2019-07-29-11-34-33-AM.png

4. You can save product without tax class (which is required)
5. Tax_class_id is visible on the Attribute list
https://i.ibb.co/8mMnM8G/Voila-Capture-2019-07-29-11-39-32-AM.png 

5. When I duplicate product, tax class is copied properly. 

### Expected result (*)
1.  Select Tax Class and save.

### Actual result (*)
1. Can't select Tax Class. 
2. Product saves without Tax Class

@magento 2.2.9

**Comment by engcom-Charlie** [comment] 2019-07-29 10:29
Hi @ymarc77 ! I can't reproduce this issue on fresh Magento 2.2.8. 
After upgrade to 2.2.9 i have a tax class attribute on add product page.
I have to close this issue.
Thank for your report!

**Closed as completed by engcom-Charlie** 2019-07-29 10:29 UTC
Labels: Component: Setup, Issue: Clear Description, Issue: Format is not valid
