### ISSUE TITLE
Indefinite Spinner on New Media Gallery Opened in CMS Page/Block & Catalog Edit Page

### ISSUE THREAD

**Issue by chapagain** [magento/magento2#35145] opened 2022-02-25 18:56 UTC
We see an indefinite spinner in the **New Media Gallery** window when opened in the Page Builder of CMS Block, CMS Page, and Product Description edit page. 

This is blocking adding images to CMS Block or Page.

The Media Gallery page works fine when opened directly from `Magento admin > CONTENT > Media > Media Gallery`.

### Preconditions 

1. Magento version 2.4.3-p1
2. [New Media Gallery](https://docs.magento.com/user-guide/cms/media-gallery.html) is enabled 
```Magento admin > Stores > Settings > Configuration > Advanced > System > Media Gallery > Enable Old Media Gallery = No```
4. [Page Builder](https://docs.magento.com/user-guide/cms/page-builder-setup.html) is enabled.
5. Magento is in [Production mode](https://devdocs.magento.com/guides/v2.4/config-guide/bootstrap/magento-modes.html#production-mode).
6. [Javascript Bundling](https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/themes/js-bundling.html) is enabled.

### Steps to reproduce 

1. Login to Magento admin
2. Go to `CONTENT > Elements > Pages` OR `CONTENT > Elements > Blocks`
7. Click on "Add Page" or "Add Block"
8. Click on the Page Builder section.
9. Drag the HTML Code attribute to Page Builder
10. Click on Edit (Gear Icon) in the HTML Code Block you added.
11. Click on the "Insert Image" button
<img width="2039" alt="Screen Shot 2022-02-25 at 12 02 02 PM" src="https://user-images.githubusercontent.com/522616/155770278-1a8a486a-7cd7-4758-9488-0fe7ef094eba.png">
12. Media Gallery window opens with the never-ending spinner.
<img width="1472" alt="Screen Shot 2022-02-25 at 12 01 07 PM" src="https://user-images.githubusercontent.com/522616/155770337-d8ede4fa-54f2-4632-a3cc-a68431950b74.png">
13. Error displayed in the browser developer console

```
Uncaught TypeError: Cannot read properties of undefined (reading 'filters')
at UiClass.updateSelectedDirectory (eval at require.load (static.min.js:11), <anonymous>:6:1447)
at setNested (eval at require.load (static.min.js:11), <anonymous>:5:50)
at Object.nested (eval at require.load (static.min.js:11), <anonymous>:11:127)
at UiClass.set (eval at require.load (static.min.js:11), <anonymous>:12:318)
at updateValue (eval at require.load (static.min.js:11), <anonymous>:11:11)
at eval (eval at require.load (static.min.js:11), <anonymous>:8:131)
at Array.forEach (<anonymous>)
at trigger (eval at require.load (static.min.js:11), <anonymous>:8:67)
at UiClass.trigger (eval at require.load (static.min.js:11), <anonymous>:12:8)
at UiClass.eval (eval at require.load (static.min.js:11), <anonymous>:17:231)
VM6351:3

Uncaught TypeError: Cannot read properties of undefined (reading 'updateActive')
at UiClass.initialize (eval at require.load (static.min.js:11), <anonymous>:3:824)
at UiClass.eval [as initialize] (eval at require.load (static.min.js:11), <anonymous>:5:186)
at new UiClass (eval at require.load (static.min.js:11), <anonymous>:5:16)
at Object.initComponent (eval at require.load (static.min.js:11), <anonymous>:10:51)
at fire (eval at require.load (static.min.js:11), <anonymous>:214:223)
at Object.fireWith [as resolveWith] (eval at require.load (static.min.js:11), <anonymous>:220:181)
at Object.deferred.<computed> (eval at require.load (static.min.js:11), <anonymous>:222:56)
at fire (eval at require.load (static.min.js:11), <anonymous>:214:223)
at Object.fireWith [as resolveWith] (eval at require.load (static.min.js:11), <anonymous>:220:181)
at Object.deferred.<computed> [as resolve] (eval at require.load (static.min.js:11), <anonymous>:222:56)
VM5281:6

Uncaught TypeError: Cannot read properties of undefined (reading 'filters')
at UiClass.updateSelectedDirectory (eval at require.load (static.min.js:11), <anonymous>:6:1447)
at UiClass.eval (eval at require.load (static.min.js:11), <anonymous>:6:1330)
at HTMLDivElement.dispatch (eval at require.load (static.min.js:11), <anonymous>:340:447)
at HTMLDivElement.elemData.handle (eval at require.load (static.min.js:11), <anonymous>:313:172)
at Object.trigger (eval at require.load (static.min.js:11), <anonymous>:334:211)
at Object.jQuery.event.trigger (eval at require.load (static.min.js:11), <anonymous>:56:21)
at jQuery.fn.init.triggerHandler (eval at require.load (static.min.js:11), <anonymous>:382:257)
at Object.__callback (eval at require.load (static.min.js:11), <anonymous>:33:82)
at Object.loaded (eval at require.load (static.min.js:11), <anonymous>:60:110)
at Object.$.jstree._fn.<computed> [as loaded] (eval at require.load (static.min.js:11), <anonymous>:33:11)
```

### Expected result 

1. The media gallery popup window loads fine without spinner and shows the images present.
<img width="2039" alt="Screen Shot 2022-02-25 at 1 51 10 PM" src="https://user-images.githubusercontent.com/522616/155771422-7676e8ad-fb09-4985-9cda-70c2019795b9.png">

### Actual result 

1. The media gallery popup window does not load properly. 
- It shows an indefinite spinner.
- We cannot see and select any image in the media gallery.
- Error is shown in the browser dev console.
<img width="1472" alt="Screen Shot 2022-02-25 at 12 01 07 PM" src="https://user-images.githubusercontent.com/522616/155771688-cbf781cc-559e-44cd-b884-1203f91324ee.png">

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by chapagain** [comment] 2022-02-25 18:58
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by chapagain** [comment] 2022-02-25 19:26
Hi @magento, This issue happens only in production mode. Can you please provide me 2.4-production instance?

**Comment by chapagain** [comment] 2022-02-25 19:48
@magento give me 2.4-production instance ee edition - upcoming 2.4.x release

**Comment by chapagain** [comment] 2022-02-25 19:49
https://github.com/magento give me 2.4-production instance - upcoming 2.4.x release

**Comment by chapagain** [comment] 2022-02-25 19:50
@magento give me 2.4-production instance ee edition - upcoming 2.4.x release

**Comment by chapagain** [comment] 2022-02-25 19:50
@magento give me 2.4-production instance - upcoming 2.4.x release

**Comment by engcom-Delta** [comment] 2022-02-28 14:01
Hi @Mukesh Chapagain,
Thank you for reporting the issue. We tried to reproduce the issue on Magento 2.4-develop branch but the issue is not reproducible.

Steps performed:
1. Login to Magento admin
2. Go to CONTENT > Elements > Pages OR CONTENT > Elements > Blocks
3. Click on "Add Page" or "Add Block"
4. Click on the Page Builder section.
5. Drag the HTML Code attribute to Page Builder
6. Click on Edit (Gear Icon) in the HTML Code Block you added.
7. Click on the "Insert Image" button

Result:
The media gallery popup window loads fine without spinner and shows the images present as shown in screenshot
![screenshot (1)](https://user-images.githubusercontent.com/51681379/155995891-7e78c239-d0a6-4dd3-b58e-c4afceba9b75.png)

Please let me know if this is exactly what your issue was or if there is some more configuration required from my end. Will update accordingly.

**Comment by engcom-Delta** [comment] 2022-03-15 07:04
We have noticed that this issue has not been updated for a period of 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh  ticket or reopen this ticket if you need more assistance on this.

**Closed as completed by engcom-Delta** 2022-03-15 07:04 UTC
Labels: Issue: needs update, Area: Content
