### ISSUE TITLE
Configurable product is not obtained when stock change from out of stock to in stock

### ISSUE THREAD

**Issue by hhonetree** [magento/magento2#36124] opened 2022-09-09 16:46 UTC
### Preconditions and environment

- Magento 2.4.4-p1

- Using:
    "magento/module-upward-connector": "^2.0"
    "magento/pwa": "^0.3.0"

-Used GraphQl:

{
    products(      
      filter: {
        url_key: {eq: "config" }
      }
    ){
    items{
      uid
      name
      sku
      url_key
    }
  }
}

### Steps to reproduce

I have Magento 2.4.4 installed in the cloud and the problem is when you change configurable product stock in this order:

1) Create configurable product In Stock
2) Update child product Qty 0 and Out of stock
3) Update child product Qty 100 and In Stock

### Expected result

Get product to show up in GraphQl search or catalog/search.

### Actual result

The product detail admin shows "In Stock", but it still doesn't show up in catalog/search or GraphQl search.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-09-22 12:32
Hi @hhonetree Thank you for reporting.
Verified the issue on Magento 2.4-develop branch but the issue is not reproducible. After changing the stock status from out of stock to instock and with quantity - product is searchable in both front end and graphql as well.
![image](https://user-images.githubusercontent.com/60198231/191747655-926c9a6a-7303-4487-92f2-8c80e32ad0cc.png)
Kindly recheck the behavior on Magento 2.4-develop instance and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-10-10 06:03
Hi @hhonetree ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-10-10 06:03 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.4-p1

**Comment by davirs** [comment] 2023-01-13 14:26
I have the same problem here with magento version 2.4.4 with php 8.1. 
The products work correctly and randomly some entire category of products or specific products are simply marked in the display as "out of stock". Both configurable and simple products are correct and stocked, it's just in the frontend display that has this bug.

Here I also have the problem that was mentioned above, when the product is sold and has zero saleable quantity it keeps appearing on the frontend as if it was in stock...

Really are 2 extremely serious bugs because they disturb sales and generate numerous complaints daily.

If anyone has an alternative solution I would be very grateful!
