### ISSUE TITLE
Mini/sidebar shopping cart limit/count not implemented

### ISSUE THREAD

**Issue by jzahedieh** [magento/magento2#4750] opened 2016-05-27 15:38 UTC
## Steps to reproduce
1. Install Magento from `version 2.0.6 (enterprise)` branch with sample data.
2. Set store configuration `Maximum Display Recently Added Item(s)` to `2 
   (_Located under Sales > Checkout > Shopping Cart Sidebar_)
3. Clear caches
4. Add 3+ separate items to basket. 
5. Assert limited to two in mini cart / checkout sidebar
## Expected result
1. Assert 2 items are displayed in mini cart and checkout sidebar
## Actual result

No limit implemented (from what I can tell)

[Screenshot - Sidebar]
![sidebar](https://cloud.githubusercontent.com/assets/2098908/15612862/63de7df2-2428-11e6-9803-148ce9a505df.png)

[Screenshot - Minicart]
![minicart](https://cloud.githubusercontent.com/assets/2098908/15612866/68263f44-2428-11e6-8b1c-0c0df5650302.png)
## Code Search

I have also had a nosy around the code, 

checkout/sidebar/display has been assigned to a constant in
vendor/magento/module-checkout/Block/Cart/Sidebar.php:18

But I can't find any reference for the configuration option checkout/sidebar/count, has this been implemented?

**Comment by jzahedieh** [comment] 2016-05-31 12:57
I have upgrade to 2.0.7 EE and the issue persists

**Comment by ishakhsuvarov** [comment] 2016-06-01 14:19
@jzahedieh Thank you for reporting this issue. We have created an internal ticket `MAGETWO-53793` to  investigate and fix the problem.

**Comment by jzahedieh** [comment] 2016-07-05 13:10
I see a few commits in relation to the fix were included in 2.1, could you please confirm that the issue is fixed because I can still add infinite products to both my minibag and checkout side bar, if so I will update with more formal bug report.

Thanks.

**Comment by elenleonova** [comment] 2016-07-15 15:51
Hi, the issue is still present in 2.1, and we plan to have it fixed in one of the following patches. We will update the ticket once it becomes available.  However, the issue have been fixed for 2.2, thus closing the ticket.

**Closed as completed by elenleonova** 2016-07-15 15:51 UTC
Labels: Issue: Ready for Work, bug report

**Comment by elenleonova** [comment] 2016-08-10 22:15
The fix has been released as a part of 2.0.9.

**Comment by elenleonova** [comment] 2016-08-30 17:08
The issue has been released in 2.1.1.

**Comment by ghost** [comment] 2016-10-12 13:38
Thank you for raising this issue @jzahedieh.

I can confirm this issue is fixed on 2.1.1

![screen shot 2016-10-12 at 14 34 37](https://cloud.githubusercontent.com/assets/5654423/19312202/53a87492-9089-11e6-8a50-3ee1e7116eac.png)

![screen shot 2016-10-12 at 14 36 20](https://cloud.githubusercontent.com/assets/5654423/19312207/589e9558-9089-11e6-80fb-7e775c092cbe.png)
