### ISSUE TITLE
On migration from Magento 1.9 to Magento 2.4.2 on category page it shows error We can not find products matching the selection.

### ISSUE THREAD

**Issue by Webalpha97** [magento/magento2#32882] opened 2021-04-27 00:59 UTC
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Webalpha97** [comment] 2021-04-27 01:06
I had also tried reindexing,cache clean but no success.

**Comment by Webalpha97** [comment] 2021-04-27 05:55
Can anyone help me out with this issue.

**Comment by denchev** [comment] 2021-04-27 08:44
@Webalpha97 Check if you have products in admin panel. See if they are in stock, have price and belong to the appropriate website.

**Comment by Webalpha97** [comment] 2021-04-27 09:05
Yes I checked all products are there and yes it is on stockand having price and pointing to right website.

**Comment by denchev** [comment] 2021-04-28 05:47
@Webalpha97 If this is true, then the only other thing I can think of (without access to site and code) is to check your elasticsearch index. Magento 2.4.2 supports ES7 only and you should be able to see at least one index.

**Comment by Webalpha97** [comment] 2021-04-28 06:20
How I can check that can you please tell me steps.

I am using elastic search version 7.7.0.

**Comment by Webalpha97** [comment] 2021-04-28 06:45
@denchev can you tell I will do that right now.

**Comment by Webalpha97** [comment] 2021-04-28 11:20
When I run : elasticsearch-reindex.

Got this error :  Starting reindex in 1 shards.
/usr/local/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js:251
    throw new Error('"from" and "to" parameters are required');

**Comment by Webalpha97** [comment] 2021-05-04 02:55
Any one who can help me out . I am getting issue after installing and doing fresh migration.

**Comment by Webalpha97** [comment] 2021-05-07 07:12
No one is there to help out .I am getting this issue in magento 2.4.2

**Comment by denchev** [comment] 2021-05-07 07:38
@Webalpha97 Github is not a support forum. I want to help you though so please find me in the Magento Community Engineering channel on Slack - magentocommeng.slack.com

**Comment by engcom-Alfa** [comment] 2021-06-07 10:09
HI @Webalpha97 
Issue is not reproducible, it works fine in Magento 2.4 Develop.

**Comment by engcom-Delta** [comment] 2021-06-24 07:11
Issue is closing since no update from reporter. Kindly raise new ticket if required.

**Closed as completed by engcom-Delta** 2021-06-24 07:11 UTC
Labels: Issue:  Cannot Reproduce, Issue: ready for confirmation
