### ISSUE TITLE
Alt Text image product not working on 2.0.2

### ISSUE THREAD

**Issue by binamandiri** [magento/magento2#3322] opened 2016-02-07 17:44 UTC
Alt Text image product not working on 2.0.2  ??
if this cant work it's not good for SEO images product.

**Comment by katmoon** [comment] 2016-02-16 08:49
Hi,

Thank you for reporting the issue!
Internal ticket number is `MAGETWO-31691`

Thanks,
Kateryna.

**Comment by katmoon** [comment] 2016-02-26 08:31
The issue is fixed in the latest Magento version.
I'm closing the ticket. Please feel free to reopen if you have additional questions.

**Closed as completed by katmoon** 2016-02-26 08:31 UTC
Labels: Issue: Ready for Work, bug report

**Comment by johnny-longneck** [comment] 2017-06-13 12:52
This is still existing.

**Comment by timste** [comment] 2017-06-13 12:56
in category listing M2 use the name from the product for the alt tag. in product detail view, when you dont set the alt text is the alt tag missing. in M1 was the default alt text the product name.
