### ISSUE TITLE
Unable to change "shipping setting" in backed when a profiler is enabled.

### ISSUE THREAD

**Issue by phoenix128** [magento/magento2#8890] opened 2017-03-15 15:16 UTC
### Preconditions
1. Magento 2.1.3
2. PHP 7

### Steps to reproduce
1. Enable MAGE_PROFILER directive to any value (e.g.: `Magento\Framework\Profiler\Driver\Standard\Output\Firebug` or `Magento\Framework\Profiler\Driver\Standard\Output\Html`)
2. Open admin panel
3. Go to Stores > Configuration > Sales > Shipping Settings

### Expected result
1. Page should just open

### Actual result
1. Error 500 on `/admin/directory/json/countryRegion` call
2. Admin redirects to dashboard

#### First error (unalbe to use a custom profiler):
In `\Magento\Framework\Profiler::_parseConfig` you hardcoded "firebug" as default value for ajax calls. This overrides any kind of custom configuration I would apply.

#### Second error (error 500 in ajax call):
In `\Magento\Framework\Profiler\Driver\Standard\Output\Firebug::display()` you are referring to `$this->getResponse()` at line 61. But it is empty.

**Comment by phoenix128** [comment] 2017-03-20 11:59
Why this issue has been closed? Do you have problems reproducing it?

**Comment by magento-engcom-team** [comment] 2017-10-05 14:30
@phoenix128, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-05 14:30 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
