### ISSUE TITLE
After upgraded to magento 2.3.2 version then missing product images on frontend and backend

### ISSUE THREAD

**Issue by hackronshins** [magento/magento2#23546] opened 2019-07-02 18:04 UTC
Hi team, I upgraded the magento version to 2.3.2 then after I am facing an issue like missing images in frontend and backend. In this i tried all the solutions but no luck. When I am inspecting the issue in frontend there is I got 404 not found, that media url path has cache/hash code. 
**https://example.com/pub/media/catalog/product/cache/12a6713c17ae5202f73943790c153a5f/s/m/image_eel_1024x1024.jpg**
In database, this table has the url like **/i/s/isolai-oro_900x900_bd57558d-f5e6-4fd4-bca4-ab34081c7a70.jpg** catalog_product_entity_media_gallery.

in this path /pub/media/catalog/product/(empty) cached images are empty I think it means there is not cache generating for catalog product images in this respective directory, Is there any other alternative solutions .

### Preconditions (*)

1. Magento 2.3.2
2. Custom theme
3. After upgrade to latest magento 2.3.2 I got the issue
4. /pub/media/catalog/product/(empty directory)

### Steps to reproduce (*)
1. Upgrade to Magento 2.3.2
2. Must be a custom theme
3. Check the images availability in pub/media
4. Check cache/hashcode added in url file

### Expected result (*)
1. Should display product images in frontend listing page,category page and product detail page
2. Should display in product admin grid in list view and product details page

### Actual result (*)
1. Product images urls 404 error
2. In every url has cache/hashcode then it is not found as 404 error
Here is an attachment please check

![25](https://user-images.githubusercontent.com/23425297/60535479-dd12f700-9d21-11e9-92fc-6d8e44c54970.PNG)

**Comment by hackronshins** [comment] 2019-07-03 11:34
Hi, 
I tested in fresh installation, it is reproducible and I am able to see the issue, I added custom theme and tried.

**Comment by engcom-Bravo** [comment] 2019-07-03 12:36
Hi, @hackronshins. Please tell us more precisely can You reproduce Your issue on a fresh installation without applying the custom theme. Thank You.

**Comment by hackronshins** [comment] 2019-07-03 13:55
I will try and check on without applying custom theme, I created a custom theme and added custom view.xml file and tried. I upload test product and image on this and it is not updating in the frontend, instead of it and it is showing placeholder, but that image still not found when I ran the command bin/magento product:images:resize

**Comment by Userr017** [comment] 2019-07-03 15:05
This duplicate? https://github.com/magento/magento2/issues/19710

**Comment by engcom-Bravo** [comment] 2019-07-03 15:24
Indeed @hackronshins, Your issue seems to be a duplicate of #19710. Therefore we are closing this issue. Please feel free to reopen it if deem necessary. Thanks for applying.

**Closed as completed by engcom-Bravo** 2019-07-03 15:24 UTC
Labels: Progress: needs update, Issue: Format is valid
