### ISSUE TITLE
No access to read emails in Magenta 2 admin dashboard

### ISSUE THREAD

**Issue by LadyMEnterprises** [magento/magento2#34729] opened 2021-11-29 18:10 UTC
### Preconditions (*)
Magenta 2 platform admin dashboard

2. mygifts.info/emcadmin

### Steps to reproduce (*)
log into emc admin dashboard

2. Click on emails
3. A message appears.

### Expected result (*)

1. [I get an error message saying that I do not have permission to read this content. Try again or get in contact help with this error.]

**Comment by engcom-November** [comment] 2021-11-30 10:45
Hi @LadyMEnterprises ,
Thank you for reporting. We are not able to reproduce the issue with provided steps on both Magento 2.4-develop branch and 2.4-develop Enterprise edition. Kindly recheck the issue on 2.4-develop branch and elaborate the steps to reproduce this issue.
Thank you.

**Comment by engcom-November** [comment] 2021-12-16 12:47
Hi @LadyMEnterprises ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-12-16 12:47 UTC
Labels: Issue: needs update
