### ISSUE TITLE
Not possible to use different column name in multiple indexers for subscription

### ISSUE THREAD

**Issue by nikunjkotecha** [magento/magento2#21853] opened 2019-03-20 12:07 UTC
### Preconditions (*)

1. Magento 2.1.4 EE (and looking at the code I can see the same in 2.2.4 CE + 2.3.x dev CE)
2. Magento catalogsearch_fulltext indexer set to update by schedule

### Steps to reproduce (*)

1. Create custom indexer and mview on cataloginventory_stock_item with entity_column="item_id" instead of product_id used in catalogsearch_fulltext and set it to update by schedule
```
<view id="custom_stock_indexer" class="Acquia\CommerceManager\Model\Indexer\Stock" group="indexer">
        <subscriptions>
            <table name="cataloginventory_stock_item" entity_column="item_id" />
        </subscriptions>
    </view>
```

### Expected result (*)

1. Trigger should use item_id for custom indexer and product_id for catalogsearch_fulltext

### Actual result (*)

1. Trigger uses column name from the indexer last set to "update by schedule" (as per the steps to reproduce above it uses item_id for both)

**Comment by magento-engcom-team** [comment] 2019-03-20 12:07
Hi @nikunjkotecha. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nikunjkotecha do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by nikunjkotecha** [comment] 2019-03-20 12:12
Yes this is reproducible in Vanilla Magento, I'll try and provide a hacky patch soon.

**Comment by nikunjkotecha** [comment] 2019-03-20 12:52
I've created PR for possible direction towards the fix, I don't expect it to be the final fix as it should be done in more generic and global way IMO but since it is blocker in my project I'm going with a the solution I suggested with known risks (if some indexer uses it's custom Subscription class, my fixes won't be applied to it)

**Comment by magento-engcom-team** [comment] 2019-03-21 07:35
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by nikunjkotecha** [comment] 2019-03-21 09:47
@magento-engcom-team this requires custom code to be added to be able to reproduce the issue, not sure if you will allow me to add custom code in the instance you give to me

**Comment by nikunjkotecha** [comment] 2019-03-28 04:23
@magento-engcom-team @engcom-backlog-nazar can someone help me understand next steps here?

**Comment by magento-engcom-team** [comment] 2019-03-29 08:14
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98959`, `MAGETWO-98960` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Closed as completed** 2021-01-24 12:14 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Component: Mview, Triage: Dev.Experience, Priority: P2, Severity: S3, Progress: done
