### ISSUE TITLE
Import of products discards many relation links

### ISSUE THREAD

**Issue by stephansteiner** [magento/magento2#31144] opened 2020-12-02 19:28 UTC
When importing a csv file with many product relations (columns crosssell_skus, related_skus and upsell_skus) in Magento 2.4 many of the relations are discarded, but no error is reported.
A short analysis of the CatalogImportExport module showed that the function 
processLinkBunches
is called with the same nextLinkId over and over, thus importing only the first bunch of relations and discarding all other relations.

### Preconditions (*)
1. Affected versions are Magento 2.4.0 and 2.4.1 (maybe also earlier versions, did not check)
2. Create a sample import file with many relations or use the file attached to this report (contains 300 products that are linked to each other as related, crosssell and upsell). [sample_import.txt](https://github.com/magento/magento2/files/5631577/sample_import.txt)

### Steps to reproduce (*)
1. Import sample file with many relations. The sample file provided contains 300 products with each 3 links of type related, crosssell and upsell, making a total of 900 product links that should be imported.
2. Check number of relations in table catalog_product_link. With my sample file I get only 300 relations, because LinkProcessor::processLinkBunches is called with bunches of 100 items, but always with the same nextLinkid, thus only the first 300 links are being imported.

### Expected result (*)
1. Total number of product links should be 900 (300 products x 3 links per product = 900 links)

### Actual result (*)

1. Only 300 product links have been imported from the first bunch, later links are discarded.

### Workaround / Patch
One possible workaround is to import products in smaller bunches (which is really tedious if you need to import thousands of products).

Another possibility is to patch vendor/magento-catalog-import-export/Model/Import/Product/LinkProcessor.php:
```
diff --git a/vendor/magento/module-catalog-import-export/Model/Import/Product/LinkProcessor.php b/vendor/magento/module-catalog-import-export/Model/Import/Product/LinkProcessor.php
index 65064e8..4ea7620 100644
--- a/vendor/magento/module-catalog-import-export/Model/Import/Product/LinkProcessor.php
+++ b/vendor/magento/module-catalog-import-export/Model/Import/Product/LinkProcessor.php
@@ -89,7 +89,6 @@ class LinkProcessor
         $resource = $this->linkFactory->create();
         $mainTable = $resource->getMainTable();
         $positionAttrId = [];
-        $nextLinkId = $this->resourceHelper->getNextAutoincrement($mainTable);
 
         // pre-load 'position' attributes ID for each link type once
         foreach ($this->linkNameToId as $linkId) {
@@ -103,6 +102,8 @@ class LinkProcessor
             $positionAttrId[$linkId] = $importEntity->getConnection()->fetchOne($select, $bind);
         }
         while ($bunch = $dataSourceModel->getNextBunch()) {
+           // get next linkid before processing a bunch
+            $nextLinkId = $this->resourceHelper->getNextAutoincrement($mainTable);
             $this->processLinkBunches($importEntity, $linkField, $bunch, $resource, $nextLinkId, $positionAttrId);
         }
     }
```

---

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2020-12-03 13:53
Hello @stephansteiner 

Thank you for your report
We have rechecked the reported issue on 2.4.1 and 2.4-develop versions

We have Imported the attached file into our Clean Magento Installation, in _Stores - Data Transfer - Import_ as "Product" _Entity Type_
The Import successfully was done
We have checked the number of relations in `catalog_product_link` table from the Database, and we can see 900 `link_id`'s
![900](https://user-images.githubusercontent.com/51680745/101026356-78477600-357f-11eb-93b8-ae3cb61cbf4a.png)

So we were not able to reproduce the reported issue

Can you please provide additional information or point at the step that we are missing?

Thank you in advance

**Comment by stephansteiner** [comment] 2020-12-03 14:10
Hi,
I can confirm that it works on Magento 2.4.1 as this issue has already been fixed by
MC-34657: Related products are missing in some products when importing.
(https://github.com/magento/magento2/commit/9c11e765ef213c2285481ed50e106d85d858bd3f)

**Comment by engcom-Bravo** [comment] 2020-12-04 12:12
@stephansteiner Thank you for the quick response.
So if the issue is not reproducible on 2.4.1 and 2.4-develop, we can close it.
Please feel free to comment, or create a new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed** 2020-12-04 12:14 UTC
Labels: Issue: needs update, Reported on 2.4.0
