### ISSUE TITLE
Add additional info to Checkout success page

### ISSUE THREAD

**Issue by mihaimghn** [magento/magento2#4550] opened 2016-05-18 10:08 UTC
Hi guys,

I'm a newbie at M2 but have come a long way.
I'm using 2.0.4.
I'm having some trouble with adding content to the success page.
1. I switch my installation to dev mode
2. Copy file 'success.phtml' from 'ventor/magento/module-checkout/view/frontend/templates/success.phtml to 'app/design/vendor/theme_name/Magento_Checkout/templates/success.phtml'
3. Add the content. Just php. No CSS, no JS.
4. Make an order and all is ok.
5. Switch to production mode

In production mode when I make an order the content I added is not present.
I ran setup:upgrade and deployed static view files.

Any thoughts?

Thanks.

**Comment by veloraven** [comment] 2016-11-01 15:16
@mihaai 
I'm closing this issue as  the GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you think it to be an issue please create new GitHub report according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Closed as completed by veloraven** 2016-11-01 15:16 UTC
