### ISSUE TITLE
Category Design Layout Update XML ignored

### ISSUE THREAD

**Issue by johncarlson21** [magento/magento2#22497] opened 2019-04-25 18:40 UTC
### Preconditions (*)

1. Magento 2.3.1
2. cPanel server
3. custom child theme
4. used to work with version 2.2.x just notice that it no longer works.

### Steps to reproduce (*)

1. Create template file: app/design/frontent/My/Theme/Magento_Catalog/templates/category/cat_collection.phtml
2. Add just some code to the file: <?php echo "<p>we are here</p>" ?>
3. Create a category
4. use xml to update the template for the category:
`<body>
<referenceContainer name="content">
<referenceBlock name="category.products.list">
     <action method="setTemplate">
        <argument name="template" xsi:type="string">Magento_Catalog::category/cat_collection.phtml</argument>
    </action>
</referenceBlock>
</referenceContainer>
</body>`
5. Save Category
6. Flush Cache and run re-index etc re-deploy static content

### Expected result (*)

1. visiting the category page should load the new template file for product list.
2. output should show "we are here"

### Actual result (*)

1. loads original product/list.phtml file
2. ignores the layout update
<img width="1208" alt="Screen Shot 2019-04-25 at 1 39 22 PM" src="https://user-images.githubusercontent.com/25893/56759865-8dcbab80-675f-11e9-8f23-aae403ed4368.png">

**Comment by johncarlson21** [comment] 2019-04-25 18:41
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-04-25 18:41
Hi @johncarlson21. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-25 18:41
Hi @johncarlson21, here is your [Magento instance](https://i-22497-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22497-2-3-develop.instances.magento-community.engineering/admin](https://i-22497-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by johncarlson21** [comment] 2019-04-25 19:01
Cannot fully test this as I have no access to a new template file, and I cannot run the re-index of the site to show new products/categories etc..
I do however have it setup in the instance so it should load but I cannot test.

**Comment by johncarlson21** [comment] 2019-04-25 20:01
Seems that my issue isn't happening on the development branch. It might be a problem with my theme, I will try to back track this, but what is the order of these layout updates?
code -> extentions/modules -> theme -> category
is this the order? because what I am overriding should go in this order but seems that my order is going:
code -> extensions/module -> category -> theme

**Comment by johncarlson21** [comment] 2019-04-25 20:08
So looking further I've disabled my theme override in the layout file and the override in the extension/module layout file and then my category design layout update xml worked.

so it seems that the order goes: framework code -> category -> extension/module -> theme

**Comment by dipti2jcommerce** [comment] 2019-04-26 09:40
@magento-engcom-team give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment] 2019-04-26 09:40
Hi @dipti2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-26 09:40
Hi @dipti2jcommerce, here is your [Magento instance](https://i-22497-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22497-2-3-develop.instances.magento-community.engineering/admin](https://i-22497-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2019-04-26 11:02
@johncarlson21 It seems the issue you reported is due to your custom theme so closing this issue.

**Comment by johncarlson21** [comment] 2019-04-26 13:08
I think this needs to be re-opened as it seems like the order of the merge of the elements is in the wrong order. even if I install a third party module it doesn't let the xml update from the category.
please have a look at this with another theme of your choice.
also this worked up until I updated to 2.3.1 from version 2.2.x

**Comment by johncarlson21** [comment] 2019-04-26 13:41
I will try to override the blank theme with a child theme, with just some simple layout updates to the category view page. and see if it does the same thing.

**Comment by johncarlson21** [comment] 2019-04-26 15:09
@shikhamis11 

alright.. I can confirm this:

1. create a child theme of Magento Blank
2. create the folder/file structure based on the screenshot I've attached.
3. add the layout update to a category from the screenshot
4. when first loaded you will not get the category design layout update file specified (cat_collection.phtml) you will get the Murals\blank\Magento_Catalog\template\product\list.phtml
5. comment out the layout update in "catalog_category_view.xml" that changes the template for the product list
6. flush cache and you will notice that the category page will now reflect the category design layout update changes

These things cannot be tested in the github development server as there is no access to the files and structure.

![M2_issue](https://user-images.githubusercontent.com/25893/56817429-3256f780-680b-11e9-8328-d56ea1576726.jpg)

**Comment by shikhamis11** [comment] 2019-04-26 15:14
Hi @johncarlson21, Thank you for your effort .. I will check this at my end also .. for now I will keep this issue opened .

**Comment by johncarlson21** [comment] 2019-04-30 14:35
is there any more movement on this?

**Comment by imanbehboudi** [comment] 2019-06-16 06:05
i have the same problem in 2.3.1 ? is this a confirmed issue ?

**Comment by johncarlson21** [comment] 2019-06-17 13:28
@benmarks hey bud.. can you maybe elaborate on this? trying to get some movement on some of these issues, I also have another one open that is a big issue.....

**Comment by johncarlson21** [comment] 2019-07-08 14:04
hey guys. can we get an update on this?
@shikhamis11

**Comment by engcom-Charlie** [comment] 2019-07-30 09:44
Hello everyone! I can't reproduce this issue on fresh Magento 2.3-develop.

**Manual testing scenario:**

1. Create a child theme of Magento Luma
2. Create the folder/file structure based on the screenshot I've attached.
![image](https://user-images.githubusercontent.com/51680850/62118789-f5494800-b2c6-11e9-8b71-8557eda15fe5.png)
3. add the layout update to a category 
![image](https://user-images.githubusercontent.com/51680850/62118874-26c21380-b2c7-11e9-97f0-0811460c065c.png)
4. flush cache, re-index , re-deploy static content
5. Go to the category page

**Result:**
![image](https://user-images.githubusercontent.com/51680850/62119077-7f91ac00-b2c7-11e9-9082-427d777fcad9.png)

So i close it.

**Closed as completed by engcom-Charlie** 2019-07-30 09:44 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid

**Comment by johncarlson21** [comment] 2019-07-30 13:40
@engcom-Charlie thank you for testing again.
This still is happening for me.
one thing I did not mention in my above scenario is that I have a layout update in the Magento_Catalog/layout/catalog_category_view.xml file that overrides all the categories
`<referenceBlock name="category.products.list">
            <action method="setTemplate">
                <argument name="template" xsi:type="string">Magento_Catalog::product/list.phtml</argument>
            </action>
		</referenceBlock>`
this override is used to override all the categories first, then I use the Category specific layout update xml, to change that specific category.

If I remove the layout update from the catalog_category_view.xml file then the override from the category itself works.

**Comment by engcom-Charlie** [comment] 2019-07-30 14:12
@johncarlson21 so did you solve your problem?

**Comment by johncarlson21** [comment] 2019-07-30 14:18
@engcom-Charlie no, the only way that I can get this to work is to remove the product list update from the catalog_category_view.xml file.
can I send you my layout file and you can look to make sure I don't have a mistake

**Comment by engcom-Charlie** [comment] 2019-07-30 14:20
@johncarlson21 yes,sure

**Comment by johncarlson21** [comment] 2019-07-30 14:20
@engcom-Charlie also.. if you have a catalog_category_view.xml file and a catalog_category_view_id_456.xml file, it still uses the catalog_category_view.xml layout update for the product list.

**Comment by johncarlson21** [comment] 2019-07-30 14:23
here are both my files, the global one for category view and the specific one for the category.

[Archive.zip](https://github.com/magento/magento2/files/3447250/Archive.zip)

**Comment by engcom-Charlie** [comment] 2019-07-30 14:33
@johncarlson21 i got this exception "Exception #0 (Magento\Framework\Exception\ValidatorException): Invalid template file: 'Magento_Catalog::category/title.phtml' in module: 'Magento_Theme' block's name: 'page.main.title'".
Can you send this file please?

**Comment by johncarlson21** [comment] 2019-07-30 16:01
[extra_files.zip](https://github.com/magento/magento2/files/3447638/extra_files.zip)
here is the other files you will probably need.
@engcom-Charlie  please also re-open this issue.

**Comment by engcom-Charlie** [comment] 2019-07-31 07:18
Hi @johncarlson21 ! It works with your files:
![image](https://user-images.githubusercontent.com/51680850/62191602-7d3d5980-b37c-11e9-81c8-a4a6d48dfb39.png)
![image](https://user-images.githubusercontent.com/51680850/62191624-8a5a4880-b37c-11e9-8c96-96455adc7f99.png)

**Comment by johncarlson21** [comment] 2019-07-31 15:32
@engcom-Charlie can I get your full theme files so I can have a look because for some reason when I go to another install and make a simple theme, it stops using any type of product list.. just empty, which makes no sense at all.

**Comment by johncarlson21** [comment] 2019-07-31 17:38
@engcom-Charlie alright... so I've recreated the catalog_category_view_id_3.xml file and I must have had a typo or something not exactly sure.

one thing that I noticed though is I still cannot do the layout update from the category specifically. so if I were to remove that category 3 xml file, and then put the code into the categories Design -> Layout Update XML section, it does not take affect.

so again, remove the catalog_category_view_id_3.xml or rename it, then go to the category in the admin and go to the Design -> Layout Update XML section and put this code in:
`<body>
        <move element="page.main.title" destination="content" before="-" />
        <referenceBlock name="category.image" remove="true" />
        <move element="category.cms" destination="content" before="category.products" />
        <move element="category.description" destination="content" />
        <referenceContainer name="catalog.leftnav" remove="true" />
		<referenceBlock name="sub_cat_list" remove="true" />
		<referenceBlock name="category.products.list">
            <action method="setTemplate">
                <argument name="template" xsi:type="string">Magento_Catalog::category/cat_collection.phtml</argument>
            </action>
		</referenceBlock>
    </body>`

**Comment by johncarlson21** [comment] 2019-07-31 17:56
@engcom-Charlie so the weird thing is if I do this, it does everything accept override the category.products.list template.

**Comment by engcom-Charlie** [comment] 2019-08-01 07:23
@johncarlson21 i still can't reproduce it:
1.catalog_category_view_id_3.xml deleted:
![image](https://user-images.githubusercontent.com/51680850/62273505-6105ef00-b446-11e9-86f6-fa72daa9506f.png)
2. Layout Update XML with your code
![image](https://user-images.githubusercontent.com/51680850/62273587-8e529d00-b446-11e9-8c3a-9c882a04e28d.png)
**Result:**
![image](https://user-images.githubusercontent.com/51680850/62273625-a2969a00-b446-11e9-8b9b-04b7483356ad.png)

Its a Magento 2.3-develop.
I think this issue fixed.
Thank for your report!

**Comment by johncarlson21** [comment] 2019-08-01 14:41
well.. it must be something with my install not sure exactly.

**Comment by arnoutvreugdenhil** [comment] 2020-11-11 13:12
I've also encountered this issue with 2.3.3.

It seems to be a problem with presidence.

In XML:
setTemplate wins from argument.
argument wins from template attribute in block element.

Example:

1. default catalog_category_view.xml using template attribute = list.phtml
2. module 1 contains a catalog_category_view.xml using action setTemplate = lista.phtml
3. module 2 contains a catalog_category_view.xml using action setTemplate  = listb.phtml
4. custom layout update xml using admin UI using action setTemplate  = listc.phtml

Results in: listb.phtml instead of listc.phtml.

Remove listb.phtml, and lista.phtml becomes visible.
Remove lista.phtml and listc.phtml finally becomes visible.
