### ISSUE TITLE
Estimate and shipping not updating when change any country, state zip code on cart page 

### ISSUE THREAD

**Issue by hemendraajmera** [magento/magento2#12797] opened 2017-12-19 06:23 UTC
### Preconditions

1. Magento 2.1.8
2. 

### Steps to reproduce

1. Added any product to cart 
2.  Go to view and edit cart from mini cart popup
3. changed country state and zip code with two options 

### Expected result

1. it will update the shipping price and show the price according to zipcode

### Actual result

1. Nothing will works and loader also not showing on that section 
2. In console showing below 
![image](https://user-images.githubusercontent.com/2478037/34143427-ab621ee4-e4b2-11e7-95c8-bdc169c1b6b6.png)
3.  when changed values in shipping and reload the page it working and showing error in console as 
?sections=recently_viewed_product%2Crecently_compared_product%2Cproduct_data_storage&update_section_id=false&_=1513664365636 (400 Bad Request)

**Comment by magento-engcom-team** [comment] 2017-12-26 16:30
@hemendraajmera, thank you for your report.
The issue is already fixed in 2.2.2

**Closed as completed by magento-engcom-team** 2017-12-26 16:30 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Fixed in 2.2.x, Issue: Format is valid
