### ISSUE TITLE
[Stock][Inventory] Quantity for Configurable product also count disable child item.

### ISSUE THREAD

**Issue by thienhoangtran** [magento/magento2#37276] opened 2023-03-21 08:41 UTC
![image (14)](https://user-images.githubusercontent.com/107161493/226555937-bb149901-451a-41c6-bdc5-f325207dbf40.png)
### Preconditions and environment

- Magento version 2.4.6
- With sample data

### Steps to reproduce

1. Create a new source (called second_source) and assign it to new Stock (called second_stock => stock id = 2)
2. Assign this stock to the current website (or new website, called second_website)
3. Create a new configurable product, with 4 child items, and add 10 quantities for each product in second_source.
4. Now, we can check the quantity of configurable product in table inventory_stock_[stockId], it will be 40 and is_salable = 1. Still good for now.
5. Now, come back to child items and disable tow of them, then change the third child quantity from 10 to 11 and check the configurable quantity in the table inventory_stock_[stockId] again.

### Expected result

Quantity for configurable product should be 21.

### Actual result

Quantity for configurable product is 41.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-03-21 14:30
Hi @thienhoangtran,


Thank you for reporting and collaboration.
Verified the issue on Magento 2.4.6 instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Create a new source (called second_source) and assign it to new Stock (called second_stock => stock id = 2)
- Assign this stock to the current website (or new website, called second_website)
- Create a new configurable product, with 4 child items, and add 10 quantities for each product in second_source.
- Now, we can check the quantity of configurable product in table inventory_stock_[stockId], it will be 40 and is_salable = 1. Still good for now.
- Now, come back to child items and disable tow of them, then change the third child quantity from 10 to 11 and check the configurable quantity in the table inventory_stock_[stockId] again.


We have created configurable product and disabled two child products and updated the quantity of one child product.


<img width="1420" alt="Screenshot 2023-03-21 at 4 42 23 PM" src="https://user-images.githubusercontent.com/51680745/226632449-d5ee467f-7359-4290-8378-8baaef691e7c.png">


After disabling the products the products is still showing `IN STOCK`.

<img width="1457" alt="Screenshot 2023-03-21 at 4 42 37 PM" src="https://user-images.githubusercontent.com/51680745/226632320-2558a6b5-b407-40aa-98c4-2a9202e86462.png">

<img width="1457" alt="Screenshot 2023-03-21 at 4 42 50 PM" src="https://user-images.githubusercontent.com/51680745/226634187-f41168c5-27e1-41df-a859-bfcf6cfb261f.png">


Kindly check this documents https://experienceleague.adobe.com/docs/commerce-admin/inventory/quantities/quantities-assign-per-product.html?lang=en

https://experienceleague.adobe.com/docs/commerce-admin/inventory/quantities/sources-assign-per-product.html?lang=en


As per Magento devdocs when we assign the product to inventory sources we need to update the quantities physically.These values track the on-hand.


Before updating the inventory sources.

<img width="1090" alt="Screenshot 2023-03-21 at 4 41 53 PM" src="https://user-images.githubusercontent.com/51680745/226635095-e4b768dd-208f-41cc-a8a0-badad91ad631.png">


After updating the inventory sources.


<img width="1190" alt="Screenshot 2023-03-21 at 4 44 00 PM" src="https://user-images.githubusercontent.com/51680745/226635131-19cb0924-41ce-4712-95f9-e0a38eb67080.png">




Kindly let us know if you are still facing any issue.


Thanks.

**Comment by thienhoangtran** [comment] 2023-03-22 02:10
Hi @engcom-Bravo ,

It means i need to update stock to 0 for all disabled child items/products in this case,is this correct?

If yes, i think we still have another issue. Let's say i still keep the quantity of simple-black and simple-red, and change quantity of simple-white and simple-yellow to 0. So for now, quantity for simple is 20 and is_salable is 1. 

In this case, is_salable value is 1. Does it make sense?

**Comment by thienhoangtran** [comment] 2023-03-24 02:16
Hi @engcom-Bravo 

Sorry for the inconvenience caused by my step to reproduce. I mean you should keep simple-black and simple-red disabled and change simple-white and simple-yellow quantity to 0. In this case, i think the is_salable value should be 0 for simple because the remaining stock (20) is coming from disable product. Is this make sence ?

**Comment by thienhoangtran** [comment] 2023-03-27 02:46
Hi @engcom-Bravo 

Thank you for your information, but i think it's an issue now. After disable simple-black and simple-red, also change simple-white and simple-yellow to 0, in frontend, the stock status of simple will "Out of stock". But in the database, quantity of simple still 20 and is_salable is 1, so when you come to any category that contains the simple and choose move the out of stock to the bottom to reassign the position for category product, it will not work correctly because the system still identifies simple still instock.

**Comment by engcom-Bravo** [comment] 2023-03-28 14:16
Hi @thienhoangtran,

Thanks for your update.

When we disable products in the backend it will not appear in any of the categories it is working as expected.For disabled products the quantity is still in the inventory we are just diasabling the product.

Kindly can you provide what is the exact issue you are facing.This is the expected behaviour of magento.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-04-10 06:07
Hi @thienhoangtran,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-04-10 06:07 UTC
Labels: Issue: needs update, Reported on 2.4.6
