### ISSUE TITLE
2.1.3 - Web Setup Wizzard - Component Manager - spinning wheel (still doesn't work)

### ISSUE THREAD

**Issue by commcad** [magento/magento2#7958] opened 2016-12-26 07:09 UTC
### Preconditions

1. Mage 2.1.3
2. NGINX, PHP 7.0.8-0ubuntu0.16.04.3

### Steps to reproduce

1. Login to backend
2. Go into > System > Web Setup Manager
3. Click on Component Manager

### Expected result

1.  Forgot what this feature is meant for, seen it last working back in March 2016 I think.
2.  I think its for installing module purchased from the Marketplace. Thankfully I haven't purchase any, yet anyway. Wish I could in all honesty :/

### Actual result

1. Spinning wheel, caption saying "Please Wait"
2. Had this "Please wait" for nearly a year now, or since 2.0.6 if memory is good 

( the most epic wait ever!)

**Comment by JamesonNetworks** [comment] 2016-12-30 15:36
I'm seeing 20 minute page load times for the page itself, however, it does eventually load. I would say this makes it practically unusable though, as the admin session seems to timeout waiting on the page load to occur.

**Comment by storepeinture** [comment] 2017-02-11 12:44
Experiencing the same issue. In fact the whole "Web Setup Wizard" is kind of useless. Updating Magento makes no sense either. Why did this all get so complicated and instable?

**Comment by AvanorHealthcare** [comment] 2017-03-15 14:23
I'm having the same problem, but with a freshly installed instance of Magento 2.1.5 
Is there solution to this at all?

**Comment by JamesonNetworks** [comment] 2017-03-15 14:26
@AvanorHealthcare We moved everything into composer installs using marketplace credentials. Almost every popular module now offers the ability to install the module through the composer.json file instead of using the web install wizard. Personally, I'd recommend going that route

**Comment by AvanorHealthcare** [comment] 2017-03-15 14:31
@JamesonNetworks Funnily enough, that's exactly what I've been doing. It just seems daft to have to go through the grind of doing a command line install when there's supposed to be an easy, built-in function linked directly to Magento Marketplace.

**Comment by pkm32** [comment] 2017-06-15 18:43
@AvanorHealthcare, when you say you use the composer.json, can you please tell me how you used this file? Is there a UI, or did you run a command using this file?

Thank you

**Comment by JamesonNetworks** [comment] 2017-06-15 19:32
@pkm32 https://store.fooman.co.nz/blog/installing-a-magento-2-extension-from-marketplace-using-command-line.html

This is all from the commandline and gets committed with the repo

**Comment by muhammadshakeel** [comment] 2017-07-10 13:59
I have fixed this issue by following below steps:

 - Open /setup/index.php/componentGrid/components in new tab
 - It showed me actual error, in my case it was last extension installed through composer.
 - I have removed that from composer
 - After updating composer, the error goes away.

https://magento.stackexchange.com/a/182945/56221

**Comment by magento-engcom-team** [comment] 2017-10-13 10:30
@commcad, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-13 10:30 UTC
Labels: bug report, Component: Setup, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid
