### ISSUE TITLE
Magento Image sliding issue

### ISSUE THREAD

**Issue by lGlitchl** [magento/magento2#35309] opened 2022-04-14 11:14 UTC
Hello everybody. I have an issue with Magento.

I created a website to sell products, but each time I upload multiple images and I access the website from my phone, I click on a product and I want to zoom in on a product or image, it automatically sends me to the next image on the slider. I want if is possible some steps in order to add some buttons in the left side and right side of the main image so you need to click on the button in order to change the image, otherwise, the image should remain the same if you click on it to zoom in/out.

**Comment by engcom-Hotel** [comment] 2022-07-11 07:09
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment] 2022-07-12 09:39
Hi @lGlitchl ,
Thank you for reporting and collaboration. Verified the issue in Mobile Platform but could not able to reproduce the issue.When we will go for zoom on a image it works properly. Please refer the screenshots.

![WhatsApp Image 2022-07-11 at 4 33 56 PM](https://user-images.githubusercontent.com/51681379/178460447-3271d666-0923-44d0-bafc-75e201390141.jpeg)
![WhatsApp Image 2022-07-11 at 4 33 55 PM](https://user-images.githubusercontent.com/51681379/178460654-4de26cc1-4600-46b7-b641-c8bc94b3e104.jpeg)


Thanks

**Comment by engcom-Delta** [comment] 2022-07-26 06:06
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Closed as completed by engcom-Delta** 2022-07-26 06:06 UTC
Labels: Issue: needs update
