### ISSUE TITLE
v2.0.4 Orders always get a status of Suspected Fraud in multi-currency store configurations

### ISSUE THREAD

**Issue by snez** [magento/magento2#4263] opened 2016-04-21 20:15 UTC
## Steps to reproduce
1. Create a store view X and set its currency as something different than the base currency.
2. Switch to store view X from the front end.
3. Place an order as usual. Checkout with a payment method that can_authorize and implements an AuthorizeOperation.
4. Inspect the order status in the admin area
## Expected result

The order should have a status of Processing
## Actual result

The order has a fraudulent status

The fraudulent status is set on line 32 in the authorize() method of vendor/magento/module-sales/Model/Order/Payment/Operations/AuthorizeOperation.php. The problematic condition sets the order as fraudulent if $payment->isSameCurrency() is false. This will always be false if the store view is configured with a currency that is different from the base currency.

**Comment by piotrekkaminski** [comment] 2016-05-23 06:18
Internal issue MAGETWO-53268

**Comment by NadiyaS** [comment] 2016-05-30 13:17
Hi @snez,
we can not reproduce this bug neither on 2.0.4 Magento version nor on latest version (develop branch).
Please provide more detailed information and do not forget to mention version number.

**Comment by snez** [comment] 2016-06-02 15:31
@NadiyaS even if you can't reproduce it, just looking at the code in vendor/magento/module-sales/Model/Order/Payment/Operations/AuthorizeOperation.php should raise some flags about the non-sensical nature of the code:

```
        if (!$isSameCurrency || !$payment->isCaptureFinal($amount)) {
            $payment->setIsFraudDetected(true);
        }
```

Why would you always set an order as fraudulent when the currency is different? I would set it as fraudulent when the _amount is the same_ **AND** _the currency is different_, not when only the currency is different. That is, unless I am missing something and $payment->isSameCurrency() should always return true even if the order was placed on a currency that is different from the base currency?

For reference, here is the isSameCurrency() method on the Payment model:

```
    public function isSameCurrency()
    {
        return !$this->getCurrencyCode() || $this->getCurrencyCode() == $this->getOrder()->getBaseCurrencyCode();
    }
```

**Comment by ndlinh-celtic** [comment] 2016-07-29 10:14
@NadiyaS 

The problem is in `Magento\Sales\Model\Order\Payment::isCaptureFinal`

``` php
    public function isCaptureFinal($amountToCapture)
    {
        $total = $this->getOrder()->getTotalDue();
        return $this->formatAmount($total, true) == $this->formatAmount($amountToCapture, true);
    }
```

The `$amountToCapture` is in Base Currency but the `$total = $this->getOrder()->getTotalDue();` is return the value of Store Currency.
I think that function should be like this:

```
    public function isCaptureFinal($amountToCapture)
    {
        $total = $this->getOrder()->getBaseTotalDue();
        return $this->formatAmount($total, true) == $this->formatAmount($amountToCapture, true);
    }
```

**Comment by viktym** [comment] 2016-09-28 08:04
Hi @snez 
We've created internal ticket MAGETWO-59052 to address this issue
Thank you

**Comment by SerhiyShkolyarenko** [comment] 2016-11-10 10:19
@snez we delivered fix of MAGETWO-59052 to develop branch. We close the issue. There are two internal issues for backporting:
 MAGETWO-60326 -- backport to 2.1
 MAGETWO-60327 -- backport to 2.0

**Closed as completed by SerhiyShkolyarenko** 2016-11-10 10:19 UTC
Labels: Issue: Ready for Work, bug report, Component: Payment

**Comment by erfanimani** [comment] 2016-12-27 01:33
Still happening on 2.1.3.. I can't seem to find a way to search which commits MAGETWO-59052 consists of and whether it's already on the 2.1 branch.

**Comment by Ctucker9233** [comment] 2017-03-25 22:12
@okobchenko What version of Magento is this fix scheduled for?

**Comment by david-fiaty-cko** [comment] 2017-04-26 16:51
+1

**Comment by affirmative-pl** [comment] 2017-05-02 17:34
+1 - having the same issue, reproduced on several servers and with various currency settings
