### ISSUE TITLE
Integration Test DataFixture Creating Simple Product with Options not saved correctly into test database

### ISSUE THREAD

**Issue by hegi64** [magento/magento2#35261] opened 2022-04-04 12:15 UTC
### Preconditions (*)

1. 2.4.3-p1

### Steps to reproduce (*)

1. Create Integration Test in Extension

Test Function

```
/**
   * @magentoDataFixture Custom_PriceRequest::Test/Integration/_files/simpleProdcutOptions.php
   * @group simpleOptionsProduct
   * @dataProvider dataPostSimpleOptionsProduct
   */
  public function testExecuteSimpleOptionsProduct($post, $second_post) {
    $objectManager = Bootstrap::getObjectManager();
    $repository = $objectManager->create(\Magento\Catalog\Api\ProductRepositoryInterface::class);

    /** @var Product $product */
    $product = $repository->getById(32);

    var_dump('TEST VAR DUMPS');
    var_dump($product->getName());
    var_dump($product->getOptionById(1)->toJson());


    $this->getRequest()->setMethod(Http::METHOD_POST);
    $this->getRequest()->setPostValue($post);
    $this->dispatch('pricerequest/request/newrequest');

    $body = $this->getResponse()->getBody();
    $this->assertStringContainsString('Simple Product 2', $body);
    $this->assertStringContainsString('<strong>Options:</strong>', $body);
    
    $this->getRequest()->setPostValue($second_post);
    $this->dispatch('pricerequest/request/newrequest');

    $this->assertRedirect($this->stringEndsWith('/price-request-received/'));

  }

public function dataPostSimpleOptionsProduct() {
    return array(
      [
        [
          'product' => '32',
          'options' => [
            '1' => ['1']
          ]
        ],
        [
          'product' => '32',
          'options' => [
            '1' => ['1']
          ]
          'email' => 'max.mustermann@gmail.com',
          'firstname' => 'Max',
          'lastname' => 'Mustermann',
          'company' => 'acompany',
          'country' => 'DE',
          'address' => 'Musterstraße 64',
          'city' => 'Musterstadt',
          'zip' => '646464',
          'telephone' => '01000000',
          'privacy_policy' => 'on',
          'comment' => '64',
          'vatnumber' => 'DE01000000'
        ]
      ]
    );
  }
```

The Testfunction call a Controller. In the Controller this lines are executed

```
var_dump($this->dataHelper->getProductById(32)->getName());
var_dump($this->dataHelper->getProductById(32)->getOptionById(1)->toJson());
```

The Helper class Function.
```
public function getProductById($id) {
    return $this->productRepository->getById($id);
  }
```

DataFixture File

```
use \Magento\Catalog\Model\Product;
use \Magento\Catalog\Model\Product\Option;
use \Magento\Catalog\Api\ProductRepositoryInterface;
use \Magento\Catalog\Api\ProductCustomOptionRepositoryInterface;

$objectManager = \Magento\TestFramework\Helper\Bootstrap::getObjectManager();

/** @var ProductRepositoryInterface $productRepository */
$productRepository = $objectManager->create(ProductRepositoryInterface::class);

/** @var ProductCustomOptionRepositoryInterface $productOptionRepository */
$productOptionRepository = $objectManager->create(ProductCustomOptionRepositoryInterface::class);
/** @var Product $product */
$product = $objectManager->create(Product::class);
$product->setId(32)
  ->setTypeId(Product\Type::TYPE_SIMPLE)
  ->setAttributeSetId(4)
  ->setName('Simple Product 2')
  ->setSku('simple2')
  ->setPrice(64)
  ->setWeight(10)
  ->setVisibility(Product\Visibility::VISIBILITY_BOTH)
  ->setStatus(Product\Attribute\Source\Status::STATUS_ENABLED)
  ->setStockData(['use_config_manage_stock' => 1, 'qty' => 100, 'is_qty_decimal' => 0, 'is_in_stock' => 1]);
  
$productRepository->save($product);

$options = array(
  array(
    "sort_order" => 1,
    "title" => "Custom Option 1",
    "price_type" => "fixed",
    "price" => "10",
    "type" => "field",
    "is_require" => 0
  )
);

/** @var Option $option */
$option = $objectManager->create(Option::class);
$option->setProductSku($product->getSku())
  ->setTitle('Custom Option 1')
  ->setStoreId($product->getStoreId())
  ->addData($options[0]);

$productOptionRepository->save($option);

$product->setCustomOptions([$option]);

$p = $productRepository->getById(32);
var_dump('DATA FIXTURE FILE VAR DUMPS');
var_dump($p->getName());
var_dump($p->toJson());
var_dump($p->getOptions()[0]->toJson());

```

### Expected result (*)

1. The var dumps in Controller should show the same result as the var dumps in the test function and in the data fixture file.

### Actual result (*)

1. only get options of the product in the test function and in the data fixture file, not in the controller.

The output of the terminal.

```
PHPUnit 9.2.6 by Sebastian Bergmann and contributors.

Warning:       Using a custom test suite loader is deprecated

string(27) "DATA FIXTURE FILE VAR DUMPS"
string(16) "Simple Product 2"
string(412) "{"option_id":"1","product_id":"32","type":"field","is_require":"0","sku":null,"max_characters":null,"file_extension":null,"image_size_x":null,"image_size_y":null,"sort_order":"1","default_title":"Custom Option 1","store_title":"Custom Option 1","title":"Custom Option 1","default_price":"10.000000","default_price_type":"fixed","store_price":null,"store_price_type":null,"price":"10.000000","price_type":"fixed"}"
E                                                                                                                                                                     1 / 1 (100%)string(14) 
"TEST VAR DUMPS"
string(16) "Simple Product 2"
string(412) "{"option_id":"1","product_id":"32","type":"field","is_require":"0","sku":null,"max_characters":null,"file_extension":null,"image_size_x":null,"image_size_y":null,"sort_order":"1","default_title":"Custom Option 1","store_title":"Custom Option 1","title":"Custom Option 1","default_price":"10.000000","default_price_type":"fixed","store_price":null,"store_price_type":null,"price":"10.000000","price_type":"fixed"}"
string(16) "Simple Product 2"


Time: 00:03.240, Memory: 107.00 MB

There was 1 error:

1) Custom\PriceRequest\Test\Integration\Controller\Request\NewRequestTest::testExecuteSimpleOptionsProduct with data set #0 (array('32', array(array('1'))), array('32', '', 'max.mustermann@gmail.com', 'Max', 'Mustermann', 'acompany', 'DE', 'Musterstraße 64', 'Musterstadt', '646464', '01000000', 'on', '64', 'DE01000000'))
Error: Call to a member function toJson() on null
```

When I call the Controller over the Browser it work perfectly. Only in the Integtration test i have the problem.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by engcom-November** [comment] 2022-07-20 09:37
Hi @GamerHegi64 ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but couldn't reproduce the issue.
Please check the below code and you will see the correct data:
```
$product = $productRepository->getById(32);
var_dump('TEST CTRL DUMPS');
var_dump($product->getName());
var_dump($product->getOptions()[0]->toJson());
```
<img width="841" alt="image" src="https://user-images.githubusercontent.com/60198231/179950204-de369fc2-27c4-4cf8-bb62-029eb2567ee8.png">
Kindly recheck the issue on Magento 2.4-develop branch and let us know if you are still facing any issues.
Thank you.

**Comment by engcom-November** [comment] 2022-08-03 10:38
Hi @GamerHegi64 ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-08-03 10:38 UTC
Labels: Triage: Dev.Experience, Issue: needs update
