### ISSUE TITLE
Transaction has been declined - PayPal Payflow Pro Error

### ISSUE THREAD

**Issue by pratikkamani** [magento/magento2#37893] opened 2023-08-18 07:11 UTC
### Preconditions and environment

1. Magento 2.3.7-p4
2. Set Payment Method in Stores->Configuration->Sales->Payment Methods->Paypal Payflow Pro (Includes Express Checkout)

### Steps to reproduce

1. Add product to cart
2. Go to checkout
3. Place an order using PayPal Payflow Pro. Enter proper CC details including the right CVV

### Expected result

Successful order as CC details are ok

### Actual result

1. Transaction has been declined. Display to the checkout page.

As far as I debug and know that 
FILE: vendor/magento/module-paypal/Model/Payflow/Service/Response/Validator/ResponseValidator.php
Code:
case Payflowpro::RESPONSE_CODE_FRAUDSERVICE_FILTER:

	foreach ($this->validators as $validator) {
	
		if ($validator->validate($response, $transparentModel) === false) {
		
			throw new LocalizedException(__('Transaction has been declined'));
		}
	}
Is throwing an error. I further debug and know that 
File: vendor/magento/module-paypal/Model/Payflow/Service/Response/Validator/CVV2Match.php
`function isNotMatchCvv` is throwing an error but the customer enters the proper cvv. 

I have checked the /var/log/payment.log for this transaction and check there is
PayPal PayflowPro response:
'CVV2MATCH' => 'Y' on the first Verified request But on the second Authorised request I am getting the result 
'cvv2match' => 'N'.
And just after another request automatically calls for transaction Void.
My sales are down and now some customer are able to place an order, but the majority of the customer is getting an error
'**Transaction has been declined**' error. 

	

### Additional information

I have inserted the debug log and found it below
**While transaction success**

```
INFO (6): ResponseValidator::validate
 INFO (6): response result = 0
 INFO (6): validator -- validate
 INFO (6): CVV2Match -- validate
 INFO (6): CVV2Match -- isMatchCvv
 INFO (6): validator -- validate
 INFO (6): AVSResponse -- validate
 INFO (6): validator -- validate
 INFO (6): IAVSResponse -- validate
 INFO (6): validator -- validate
 INFO (6): SecureToken -- validate
 INFO (6): Transparent::authorize
 INFO (6): orderId = 1000047384
 INFO (6): ResponseValidator::validate
 INFO (6): response result = 0
 INFO (6): validator -- validate
 INFO (6): CVV2Match -- validate
 INFO (6): CVV2Match -- isMatchCvv
 INFO (6): validator -- validate
 INFO (6): AVSResponse -- validate
 INFO (6): validator -- validate
 INFO (6): IAVSResponse -- validate`
```

While **Transaction has been declined**

```
 INFO (6): ResponseValidator::validate
 INFO (6): response result = 0
 INFO (6): validator -- validate
 INFO (6): CVV2Match -- validate
 INFO (6): CVV2Match -- isMatchCvv
 INFO (6): validator -- validate
 INFO (6): AVSResponse -- validate
 INFO (6): validator -- validate
 INFO (6): IAVSResponse -- validate
 INFO (6): validator -- validate
 INFO (6): SecureToken -- validate
 INFO (6): Transparent::authorize
 INFO (6): orderId = 1000047381
 INFO (6): ResponseValidator::validate
 INFO (6): response result = 0
 INFO (6): validator -- validate
 INFO (6): CVV2Match -- validate
 INFO (6): CVV2Match -- isMatchCvv
 INFO (6): CVV2Match -- isNotMatchCvv
 INFO (6): validation fail
 INFO (6): Transaction has been declined
```
 
![Paypal Transection Log](https://github.com/magento/magento2/assets/9292282/f62b76cb-c45b-421c-af8a-ecbd2ef26cd0)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-08-21 07:14
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-08-22 10:23
Hi @pratikkamani,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

**Steps to reproduce**

- Add product to cart
- Go to checkout
- Place an order using PayPal Payflow Pro. Enter proper CC details including the right CVV


We are able to place the order with **Paypal Payflow Pro** and **Paypal Express Checkout** with successful credit card details.  



https://github.com/magento/magento2/assets/51680745/903d0e02-b1d9-4a6c-b27e-a9c5e7a35ddb



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.
it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.

Thanks.

**Comment by pratikkamani** [comment] 2023-08-22 10:39
Hi @engcom-Bravo,
The issue is reproducible on Magento 2.3.7-p4 and Credit Card hosted on the checkout page not on Express Checkout. After trying with Paypal Payflow Pro could you please share the var/log/payment.log file? 
Thanks.

**Comment by engcom-Bravo** [comment] 2023-08-23 11:47
Hi @pratikkamani,

Thanks for your update.


We are able to place the order with credit card and order is placed successfully.(Paypal Payflow Pro and Paypal Express Checkout).

Here is the var/log/payment.log.


<img width="755" alt="Screenshot 2023-08-23 at 12 33 42 PM" src="https://github.com/magento/magento2/assets/51680745/f14e40f4-bafb-4b3b-8499-a9bfe6aa3eb5">



<img width="771" alt="Screenshot 2023-08-23 at 12 37 48 PM" src="https://github.com/magento/magento2/assets/51680745/b89494b0-0cc7-498f-8692-02aba9a9d375">




it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.


Kindly recheck the issue in Magento Latest version it seems to be issue got fixed in latest versions.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-09-04 06:12
Hi @pratikkamani,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-09-04 06:12 UTC
Labels: Issue: needs update, Reported on 2.3.7-p4
