### ISSUE TITLE
Search with long string display horizontal scroll in front end

### ISSUE THREAD

**Issue by mageprince** [magento/magento2#21359] opened 2019-02-20 12:09 UTC
### Preconditions (*)

1. Magento 2.3.x
2. Magento 2.2.x

### Steps to reproduce (*)

1. Front end: Search with long string like (test4234gdfgdf34467676474747474676647747475754754745745744757745)
2. See the horizontal scroll

### Expected result (*)

![search results for test4234gdfgdf34467676474747474676647747475754754745745744757745](https://user-images.githubusercontent.com/24751863/53090633-0af75c00-3536-11e9-943d-1d231e6ccb07.png)

### Actual result (*)

![search-bug](https://user-images.githubusercontent.com/24751863/53090739-51e55180-3536-11e9-9af3-25a1decae170.png)

**Comment by magento-engcom-team** [comment] 2019-02-20 12:09
Hi @mageprince. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mageprince do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-02-20 12:09
Hi @krishprakash. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by krishprakash** [comment] 2019-02-20 12:11
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-20 12:11
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-20 12:12
Hi @krishprakash, here is your [Magento instance](https://i-21359-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21359-2-3-develop.instances.magento-community.engineering/admin](https://i-21359-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2019-02-20 12:14
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-20 12:14
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-20 12:15
Hi @krishprakash, here is your [Magento instance](https://i-21359-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21359-2-2-develop.instances.magento-community.engineering/admin](https://i-21359-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-02-20 16:31
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-02-20 16:32
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98337`, `MAGETWO-98338` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-02-25 10:46
Hi @mageprince. Thank you for your report. 
The issue has been fixed in magento/magento2#21360 by @mageprince in 2.3-develop branch
Related commit(s):
 - [b63123e693fe7f950318ed6550d71494661fea89](https://github.com/magento/magento2/commit/b63123e693fe7f950318ed6550d71494661fea89)
 - [1236770b10b14969a69ac81725a6bab781011ffd](https://github.com/magento/magento2/commit/1236770b10b14969a69ac81725a6bab781011ffd)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-02-25 10:46 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Area: Design/Frontend, Component: CatalogSearch
