### ISSUE TITLE
Partial shipments API ships all items and completes order

### ISSUE THREAD

**Issue by BernardRobbins** [magento/magento2#31649] opened 2021-01-14 22:52 UTC
### Preconditions (*)
1. Magento 2.4.*
2. Magento 2.3.*

### Steps to reproduce (*)
1. Checkout with at least two items.
2. Create Invoice.
3. Try to ship one item by following instructions for partial shipment here: https://devdocs.magento.com/guides/v2.3/rest/tutorials/inventory/create-shipment.html
4. ![image](https://user-images.githubusercontent.com/959230/104657944-dcd21680-568f-11eb-89c4-765a088db8f5.png)
5. I've tried a lot of permutations of the form data and still ended up with the actual instead of the expected.

### Expected result (*)
1. Order Status Processing
2. Partial shipment
3. ![image](https://user-images.githubusercontent.com/959230/104658224-566a0480-5690-11eb-8e96-5a40594f127a.png)

### Actual result (*)
1. Order Status Complete
2. Single shipment
3. ![image](https://user-images.githubusercontent.com/959230/104658295-7a2d4a80-5690-11eb-978f-2dd31d9bec7b.png)

---
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by engcom-Alfa** [comment] 2021-01-18 08:31
Hi @BernardRobbins. Thank you for your report.

Unfortunately, we are not able to reproduce the issue on fresh 2.4-develop. Looks like the issue has already been fixed.

**Manual testing scenario:**
1. Checkout with at least two items (2 simple products with qty =1 each);
2. Create an Invoice;
3. Send **POST** `/V1/order/{orderId}/ship`
![Screenshot from 2021-01-18 10-27-38](https://user-images.githubusercontent.com/51679138/104890169-dab1d580-5977-11eb-98a9-5cd75aaa4ad2.png)

**Actual Result:** 
1. Order Status Processing - :heavy_check_mark: 
2. Partial shipment - :heavy_check_mark: 
![2021-01-18_10-20](https://user-images.githubusercontent.com/51679138/104890286-0af97400-5978-11eb-90f4-e3c7cfa967b6.png)

@BernardRobbins Are you able to reproduce this issue on fresh 2.4-develop?
Could we have missed some details?
Thanks!

**Comment by BernardRobbins** [comment] 2021-01-18 15:40
Thank you @engcom-Alfa for looking into this. Here is a more detailed step by step.

1. /usr/bin/composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition < install-directory-name >
2. This installed Magento ver. 2.4.1
3. cd < install-directory-name >
4. php7.3 bin/magento setup:install < install settings >
5. php7.3 bin/magento module:disable Magento_TwoFactorAuth
6. php7.3 bin/magento sampledata:deploy
7. php7.3 bin/magento setup:upgrade
8. php7.3 bin/magento setup:di:compile
9. Add two items into cart.
10. Checkout with check / money order
11. Admin > Sales > Orders > Invoice sales/order/view/order_id/3/ 
12. Status now processing
![sales order view order_id 3](https://user-images.githubusercontent.com/959230/104934887-93781480-5978-11eb-95c0-7e534cdec72d.png)
13. Postman >
http://task-dropship-fulfillment/rest/V1/integration/admin/token?username=< admin user >&password=< admin pass >
Get token
16. Send POST query https://devdocs.magento.com/redoc/2.2/#operation/salesShipOrderV1ExecutePost
![postman order ship](https://user-images.githubusercontent.com/959230/104934969-a7237b00-5978-11eb-9749-b921698b99af.png)

17. Check order in admin and it's shipped both. 
![sales order view after](https://user-images.githubusercontent.com/959230/104935027-bc98a500-5978-11eb-857c-28f0ead30cce.png)

**Comment by BernardRobbins** [comment] 2021-01-18 21:03
Not sure if it matters:
mysql  Ver 8.0.22-0ubuntu0.20.04.3 for Linux on x86_64 ((Ubuntu))
Apache/2.4.41 (Ubuntu)
Zend Engine v3.3.26
Postman Version 7.34.0
Chrome Version 87.0.4280.141

**Comment by BernardRobbins** [comment] 2021-01-18 21:58
I missed the part where you said 2.4-develop. I've installed 2.4-develop and have the same result.

**Comment by BernardRobbins** [comment] 2021-01-18 22:10
I found my issue. I was sending the body in the wrong format. It should have been raw JSON format. 

Now I have another question. Is this suppose to ship all items when it doesn't receive the proper format? 

I tested again and sending an empty post to http://task-dropship-fulfillment/rest/V1/order/5/ship will ship all products.

![image](https://user-images.githubusercontent.com/959230/104966645-6c890500-59af-11eb-90ca-295e41ba2def.png)

**Comment by engcom-Alfa** [comment] 2021-01-21 12:58
Hi @BernardRobbins . 
Yes, it is currently possible to send a request with an empty body. And it is possible to do with an invoice, refund...
The Magento [documentation](https://magento.redoc.ly/2.4.1-admin/tag/orderorderIdinvoice) for this endpoint states that only the **_order_id_** is a required parameter.
Although it would be good to have information that if you make a request with an empty body then all the products will be shipped. But this needs more detailed consideration.

As I understand it, the problem described in this ticket is solved?
Can we close it?
Thanks!

**Closed as completed** 2021-01-21 13:09 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.3.6
