### ISSUE TITLE
Autoload error: 'Magento_Newsletter' component already exists

### ISSUE THREAD

**Issue by danielc1234** [magento/magento2#2670] opened 2015-12-10 14:57 UTC
Had Magento 2.0 running perfectly. Then we installed Varnish 4.0 and was working fine, but all of a sudden the site will not allow us to do anything. 

When we try to deploy an update or anything in admin/frontend we get this error:
Autoload error: 'Magento_Newsletter' component already exists

Is there a way to fix this issue? I know in magento 1.0 you could just rename the local.xml and it would initiate a new install and allow to use the same database.

Before I started all over again, I was hoping to see if there was another way to fix this.

Thanks
Dan

**Comment by davidalger** [comment] 2015-12-10 15:37
@danielc1234 Sounds like you may have multiple copies of the module. Perhaps there is one in ./vendor/ and another in ./app/code/? I'd suggest checking your registration.php files for duplicate references to that module name.

**Comment by mazhalai** [comment] 2015-12-10 15:41
@danielc1234 how did you install Magento 2 initially? via git? composer? or downloaded a zip via magento.com?

**Comment by danielc1234** [comment] 2015-12-10 17:17
@mazhalai
I installed this version via zip download.

Like I mentioned it was working fine, but all of a sudden stopped. I thought maybe had something to do with Varnish install but now I don't think so.

**Comment by mazhalai** [comment] 2015-12-10 17:26
@danielc1234 in your first post you mentioned `When we try to deploy an update` did you run composer update anytime while doing that? What exactly did you try to update? 

As @davidalger mentioned, you have somehow ended up with multiple modules in `app/code` as well as `vendor/magento` folder. I would suggest to clean your magento root folder and db (create backups if you really need data using `bin/magento setup:backup`) and start over.

**Comment by danielc1234** [comment] 2015-12-10 17:54
what would you recommend the best install method to be?

**Comment by mazhalai** [comment] 2015-12-10 18:17
@danielc1234 really it depends on your level of expertise and what you want to do. More details to help you decide: http://devdocs.magento.com/guides/v2.0/install-gde/continue.html

**Comment by alankent** [comment] 2015-12-10 18:43
We are also interested to see if we have something wrong. You definitely should be able to install from the ZIP download (not from GitHub - the one on the magento site) and do a composer update. If that has a problem, we need to identify and fix it. That is partly why we are curious in the sequence you did.

**Comment by danielc1234** [comment] 2015-12-10 18:55
@alankent Yes, that is exactly what I did. I first installed from the zip and wanted to make sure I had the lastest copy, so I tried to run the composer to do an update.

I do not recall the exact steps though that I did.

**Comment by davidalger** [comment] 2015-12-12 16:35
@danielc1234 Can you resetup from scratch the same way you did before and see if you can reproduce the problem and send us steps to reproduce if you can?

**Comment by danielc1234** [comment] 2015-12-12 18:01
@davidalger I re-installed from scratch and all seemed to be working fine, then the following day when refreshing the site, got blank white screen.

I think the 2.0 release was released a little premature. Seems there is still quite a few issues with it. Although it is an awesome version. Very quick and super easy to work with.

Not sure if this helps at all, but getting this on console and exception log.

![image](https://cloud.githubusercontent.com/assets/1151357/11763217/4e38808c-a0d0-11e5-9844-82979bef04c2.png)

[2015-12-11 01:10:34] main.CRITICAL: BadMethodCallException: Missing required argument $addressesFactory of Magento\Customer\Model\Backend\Customer. in /Projects/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:45
Stack trace:
#0 /Projects/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\Custome...', Array, Array)
#1 /Projects/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\Custome...')
#2 /Projects/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\Custome...')
#3 /Projects/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\Custome...', NULL, 'customerModel', 'Magento\Custome...')
#4 /Projects/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\Custome...', Array, Array)
#5 /Projects/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\Custome...')
#6 /Projects/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\Custome...')
#7 /Projects/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\Custome...', NULL, 'customerAccount...', 'Magento\Tax\Mod...')
#8 /Projects/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\Tax\Mod...', Array, Array)
#9 /Projects/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\Tax\Mod...')
#10 /Projects/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\Tax\Mod...')
#11 /Projects/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\Tax\Mod...', NULL, 'calculation', 'Magento\Tax\Mod...')
#12 /Projects/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\Tax\Mod...', Array, Array)
#13 /Projects/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\Tax\Mod...')
#14 /Projects/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\Tax\Mod...')
#15 /Projects/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\Tax\Api...', NULL, 'taxCalculationS...', 'Magento\Catalog...')
#16 /Projects/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\Catalog...', Array, Array)
#17 /Projects/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\Catalog...')
#18 /Projects/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\Catalog...')
#19 /Projects/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\Catalog...', NULL, 'catalogData', 'Magento\Catalog...')
#20 /Projects/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\Catalog...', Array, Array)
#21 /Projects/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\Catalog...', Array)
#22 /Projects/magento2/vendor/magento/framework/Validator/UniversalFactory.php(36): Magento\Framework\ObjectManager\ObjectManager->create('Magento\Catalog...', Array)
#23 /Projects/magento2/vendor/magento/module-eav/Model/Entity/Attribute/AbstractAttribute.php(498): Magento\Framework\Validator\UniversalFactory->create('Magento\Catalog...')
#24 /Projects/magento2/var/generation/Magento/Catalog/Model/ResourceModel/Eav/Attribute/Interceptor.php(1103): Magento\Eav\Model\Entity\Attribute\AbstractAttribute->getBackend()
#25 /Projects/magento2/vendor/magento/module-catalog-rule/Model/Indexer/IndexBuilder.php(600): Magento\Catalog\Model\ResourceModel\Eav\Attribute\Interceptor->getBackend()
#26 /Projects/magento2/vendor/magento/module-catalog-rule/Model/Indexer/IndexBuilder.php(420): Magento\CatalogRule\Model\Indexer\IndexBuilder->getRuleProductsStmt('1', NULL)
#27 /Projects/magento2/vendor/magento/module-catalog-rule/Model/Indexer/IndexBuilder.php(203): Magento\CatalogRule\Model\Indexer\IndexBuilder->applyAllRules()
#28 /Projects/magento2/vendor/magento/module-catalog-rule/Model/Indexer/IndexBuilder.php(186): Magento\CatalogRule\Model\Indexer\IndexBuilder->doReindexFull()
#29 /Projects/magento2/vendor/magento/module-catalog-rule/Model/Indexer/AbstractIndexer.php(56): Magento\CatalogRule\Model\Indexer\IndexBuilder->reindexFull()
#30 /Projects/magento2/var/generation/Magento/CatalogRule/Model/Indexer/Product/ProductRuleIndexer/Interceptor.php(38): Magento\CatalogRule\Model\Indexer\AbstractIndexer->executeFull()
#31 /Projects/magento2/vendor/magento/module-indexer/Model/Indexer.php(412): Magento\CatalogRule\Model\Indexer\Product\ProductRuleIndexer\Interceptor->executeFull()
#32 /Projects/magento2/vendor/magento/module-indexer/Console/Command/IndexerReindexCommand.php(38): Magento\Indexer\Model\Indexer->reindexAll()
#33 /Projects/magento2/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Magento\Indexer\Console\Command\IndexerReindexCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /Projects/magento2/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /Projects/magento2/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Indexer\Console\Command\IndexerReindexCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /Projects/magento2/vendor/magento/framework/Console/Cli.php(49): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /Projects/magento2/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 /Projects/magento2/bin/magento(25): Symfony\Component\Console\Application->run()
#39 {main} [] []

**Comment by mazhalai** [comment] 2015-12-15 21:41
@danielc1234 please clean your `var` folder and try again. Also please pay close attention to file and folder permissions, and user groups. If not set up correctly, you may have issues. Since your original issue of Autoload_error is resolved, we are closing this issue. Please feel free to open a new one in case you come across more issues.

**Closed as completed** 2015-12-15 21:43 UTC
