### ISSUE TITLE
Create New Wishlist not working in magento 2.3.1

### ISSUE THREAD

**Issue by dhiraj-danode** [magento/magento2#23836] opened 2019-07-23 13:06 UTC
### Preconditions (*)

1.   Magento EE 2.3.1
2.    2.3.2

### Steps to reproduce (*)

1. Enable Multiple wishlist from admin -> Store -> Configuration -> Customer -> Wishlist -> General Option -> Enable Multiple Wish Lists
2. Login to Frontend and Go to My Account -> My Wishlist
3. Click on Crete New Wishlist and save. 
4. Observed that sometimes New Wishlist didn't created.
5. We debug on it and observed that create new wishlist form action is showing as # some times 

### Expected result (*)

1. Create Wishlist should work as expected.
2. So Create wishlist action should generate as in 'wishlist issue 1.png' 
3. In 'wishlist issue 2.png' action is not generated so unable to create wishlist

### Actual result (*)

1. [Screenshots, logs or description]
2. As per screenshot create wishlist not working.
![wishlist issue 1](https://user-images.githubusercontent.com/47853083/61714509-a7898880-ad78-11e9-8d47-0b2ebfdfba95.png)
![wishlist issue 2](https://user-images.githubusercontent.com/47853083/61714519-ace6d300-ad78-11e9-9339-27212708e179.png)

**Comment by krishprakash** [comment] 2019-07-23 16:05
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-23 16:05
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-23 16:05
Hi @krishprakash, here is your [Magento instance](https://i-23836-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23836-2-3-develop.instances.magento-community.engineering/admin](https://i-23836-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment] 2019-07-24 06:42
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-24 06:42
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-24 06:42
Hi @sudheers-kensium, here is your [Magento instance](https://i-23836-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23836-2-3-develop.instances.magento-community.engineering/admin](https://i-23836-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment] 2019-07-24 06:52
Issue exists in Magento EE 2.3.1

**Comment by sudheers-kensium** [comment] 2019-07-24 06:56
Issue exits only Magento EE 2.3.1 not in Magento CE

**Comment by dhiraj-danode** [comment] 2019-07-24 07:40
We upgraded Magento from 2.3.1 to 2.3.2 and issue is still exits.

**Comment by dhiraj-danode** [comment] 2019-07-24 13:18
@sudheers-kensium Do we have any fix for this issue ?

**Comment by magento-engcom-team** [comment] 2019-07-30 12:47
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18742` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sudheers-kensium** [comment] 2019-08-08 09:58
> @sudheers-kensium Do we have any fix for this issue ?

@dhiraj-danode I observed that some js files are not loading due to this popup not showing. So I given permission to pub folder then it is working fine for me.

**Closed as completed** 2019-08-27 11:35 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Wishlist
