### ISSUE TITLE
"GMT (America/Nuuk)" timezone is not working correctly

### ISSUE THREAD

**Issue by KovenVillar** [magento/magento2#33702] opened 2021-08-06 13:12 UTC
### Preconditions (*)

1. Order is created
2. "GMT (America/Nuuk)" timezone is selected
3. Reindex and cache are run

### Steps to reproduce (*)

1. Go to Backend -> Sales -> Orders
2. Check the "Purchase Date" and "Order Date" (on the view page of the created order) columns

### Expected result (*)

1. Columns have the same time  
![9](https://user-images.githubusercontent.com/88530799/128513519-3ded6ade-ab27-4087-95d4-cbc4635372ef.png)

### Actual result (*)

1. Columns have different time  
![10](https://user-images.githubusercontent.com/88530799/128513658-0926ac97-fe31-45d0-a2de-7e88b8861183.png)

2. Fatal error appears in develop mode for Magento 2.3.7 on all pages 
![11](https://user-images.githubusercontent.com/88530799/128513986-c90619de-3f9a-4302-b5b7-9641316f8748.png)

**Comment by KovenVillar** [comment] 2021-08-06 13:19
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2021-08-09 06:35
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:

**Steps:**
1. Admin - Stores - Configuration - General - Locale Options - Select "GMT (America/Nuuk)" and save
2. Reindex and clear cache
3. Admin -> Sales -> Orders
4. Check the "Purchase Date" and "Order Date" (on the view page of the created order) columns
**Issue: Purchase Date and Order Date columns don't have same time**
![image](https://user-images.githubusercontent.com/60198231/128667509-72cd6a34-c252-49a0-9d23-adfa214db377.png)
![image](https://user-images.githubusercontent.com/60198231/128667523-f26d5f1f-0840-41dd-91bc-40fe36e6e31b.png)
![image](https://user-images.githubusercontent.com/60198231/128667538-dd52a4d0-3155-4034-bb4d-0eacc1c252fa.png)

**Note**: This issue is not observed for other time zones selected

**Comment by magento-engcom-team** [comment] 2021-08-09 06:38
:white_check_mark: Confirmed by @engcom-November 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-43021` were created

**Issue Available**: @engcom-November, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Hotel** [comment] 2021-08-17 11:10
Hello @engcom-November,

Can you please confirm if that exception is reproducible in the 2.4-develop branch?

Thanks

**Comment by engcom-November** [comment] 2021-08-18 07:09
Hi @engcom-Hotel ,
Exception is not reproducible on 2.4-develop branch but difference in "Purchase Date" and "Order Date" columns has been observed for GMT (America/Nuuk) Timezone.
Thank you.

**Comment by nidhigupta13-ey** [comment] 2021-12-15 05:23
I am picking up this issue, can you please assign it to me?

**Comment by nidhigupta13-ey** [comment] 2021-12-20 09:47
Hello @magento-engcom-team ,

After doing so many research on this I found that the Magento is getting timezone from  function getOptionTimezones from vendor/magento/framework/locale/TranslatedLists.php. So it is related to php. If the PHP is having the timezone it will work fine and if the PHP is not having the timezone then it will not work.

<img width="455" alt="Screenshot 2021-12-20 at 3 11 25 PM" src="https://user-images.githubusercontent.com/93646392/146747097-a48440fe-91c2-47de-8b71-a311fa7af047.png">

Thank you,

**Comment by engcom-Bravo** [comment] 2024-07-25 07:27
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-07-25 08:51
Hi @KovenVillar,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.


<img width="1436" alt="Screenshot 2024-07-25 at 14 18 07" src="https://github.com/user-attachments/assets/2efd8cd0-40c5-442e-97f8-077e22b8ec33">


<img width="1342" alt="Screenshot 2024-07-25 at 14 18 36" src="https://github.com/user-attachments/assets/bbecf459-3472-4a46-85db-fb6888c5ffef">


<img width="1342" alt="Screenshot 2024-07-25 at 14 20 05" src="https://github.com/user-attachments/assets/0f52409e-99a8-4e93-a6c5-5b0a357494ac">


Columns are having same date.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-25 08:51 UTC
Labels: Issue: Confirmed, Component: Locale, Reproduced on 2.4.x, Priority: P3, Progress: done, Reported on 2.3.x
