### ISSUE TITLE
Source class \Vertex for \Vertex\Mapper generation does not exist.

### ISSUE THREAD

**Issue by mariamghalleb** [magento/magento2#18497] opened 2018-10-09 19:42 UTC
### Preconditions

1. Magento 2.2.4
2.php 7

### Steps to reproduce

1. Setup:di:compile
### Expected result

1.  compilation  

### Actual result

1.  Source class \Vertex for \Vertex\Mapper generation does not exist.
![capture3](https://user-images.githubusercontent.com/28814080/46694074-6292cc00-cc14-11e8-8f08-e177d172cc3f.PNG)

Exception trace:

>  () at /home/website/public_html/vendor/magento/framework/Code/Generator.php:185
>  Magento\Framework\Code\Generator->tryToLoadSourceClass() at /home/website/public_                                               html/vendor/magento/framework/Code/Generator.php:112
>  Magento\Framework\Code\Generator->generateClass() at /home/website/public_html/ve                                               ndor/magento/framework/Code/Generator.php:180
>  Magento\Framework\Code\Generator->tryToLoadSourceClass() at /home/website/public_                                               html/vendor/magento/framework/Code/Generator.php:112
>  Magento\Framework\Code\Generator->generateClass() at /home/website/public_html/ve                                               ndor/magento/framework/Code/Generator/Autoloader.php:35
>  Magento\Framework\Code\Generator\Autoloader->load() at n/a:n/a
>  spl_autoload_call() at n/a:n/a
>  class_exists() at /home/website/public_html/setup/src/Magento/Setup/Module/Di/Cod                                               e/Scanner/PhpScanner.php:269
> 

Comments:

I don't know if this Vertex Tax Magento module related, i disabled that module and nothing changed. I cleared directories, i setup:upgrade and it's stuck in that error.

**Comment by magento-engcom-team** [comment] 2018-10-09 19:42
Hi @mariamghalleb. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mariamghalleb do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by mariamghalleb** [comment] 2018-10-09 19:54
> Hi @mariamghalleb. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [x]  Summary of the issue
> * [x]  Information on your environment
> * [x]  Steps to reproduce
> * [x]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me $VERSION instance`
> 
> where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop).
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @mariamghalleb do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [x]  yes
> * [ ]  no

**Comment by navarr** [comment] 2018-10-12 12:37
@mariamghalleb Hi!  Thanks for reporting your issue.

Can you share with me the output of these commands?

```bash
composer show vertex/module-tax
composer show vertex/sdk
```

**Comment by mariamghalleb** [comment] 2018-10-12 12:51
@navarr  I fixed the problem by eliminating vertex module from composer.json and i run composer update. It seemed that vertex module got reinstalled and the error was gone. Here's the outputs: 
![captcomposer](https://user-images.githubusercontent.com/28814080/46870087-5c7c3580-ce36-11e8-963f-f60dccf904f4.PNG)
![composer](https://user-images.githubusercontent.com/28814080/46870096-630aad00-ce36-11e8-9fa6-0256def6266b.PNG)
![composer2](https://user-images.githubusercontent.com/28814080/46870097-630aad00-ce36-11e8-9907-4de8832444aa.PNG)


I truly wonder what happened to have such problem, especially that the website was totally functional for forever.

**Comment by navarr** [comment] 2018-10-12 12:59
@mariamghalleb I'm curious too.  Ping me if you encounter the issue again.

Also: because you've updated your modules, if you decide to upgrade to version 2.2.6+ you will stumble into #18248

Disabling any modules you don't use will prevent those issues from occurring, however.

I'm going to close this ticket since the problem does not persist and there are no steps to recreate it.  Again, please let me know if you experience it again and we can investigate.

**Closed as completed by navarr** 2018-10-12 12:59 UTC
Labels: Issue: Format is valid

**Comment by zeeshan2523806** [comment] 2018-12-18 03:59
For me vertex/sdk was missing after upgrading the magento. Althrough the module was exist in my vendor directory but it was not part of the composer.json, running ` composer require vertex/sdk` solve the problem for me.
