### ISSUE TITLE
AttributeSetRepository getList() method don't use searchcriteria

### ISSUE THREAD

**Issue by zkliouel** [magento/magento2#8686] opened 2017-02-27 09:37 UTC
Magento 2.1.4

I need to filter attributset by type but the searchcriteria seem's to be not used...

Code sample : 
```
 $filter[] = $this->filterBuilder
            ->setField('entity_type_id')
            ->setConditionType('eq')
            ->setValue(4)
            ->create();
        
 $searchCriteria = $this->searchCriteriaBuilder
            ->addFilters($filter)
            ->create();

$attributSets = $this->attributeSetRepository->getList($searchCriteria)->getItems();
```
In $attributSets i have all attributesets not filtered...

Taking a look at Magento\Eav\Model\AttributeSetRepository.php
And the getList method don't use searchcriteria to filter collection....

**Comment by tormit** [comment] 2017-02-27 09:43
+1
Thanks for the issue report. Just stumbled on this myself.

**Comment by vrann** [comment] 2017-03-13 18:49
@zkliouel The issue is fixed in the latest develop. It was done with the introduction of the major changes to the API filters processing. That's why it's not something that can be backported to the 2.1 with the patch release

**Comment by magento-engcom-team** [comment] 2017-10-18 12:30
@zkliouel, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-18 12:30 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid
