### ISSUE TITLE
Can I change tittle of custom options based on store view

### ISSUE THREAD

**Issue by salelsol** [magento/magento2#2908] opened 2016-01-06 22:04 UTC
I´ve add another language in store, and when change for a particular store view language, then custom options products fails (All store views works fine), and can´t chane anything.
![custom_options_store_view](https://cloud.githubusercontent.com/assets/16081377/12156170/a709c7c2-b4c9-11e5-8a6f-1be6e35637b9.jpg)

**Comment by katmoon** [comment] 2016-01-08 11:52
Hi,

Thanks for reporting the issue.
Internal ticket is MAGETWO-47698

**Comment by GeromeF** [comment] 2016-03-09 15:00
Same problem for me running 2.0.2, no fix available at this time ??

**Comment by katmoon** [comment] 2016-03-10 08:54
Hi @GeromeF 

I think the issue should be fixed approximately within a month.

**Comment by mktudock** [comment] 2016-07-29 09:43
Is this issue still not fixed?

**Comment by gaurangjadav** [comment] 2016-09-17 14:04
Hello 

Does this issue get fixed , or what could be the easy fix from code please help..!
we running live website with Magento 2.0.6.

Thanks

**Comment by audexpro** [comment] 2017-06-05 09:03
Any news on this issue?

**Comment by veloraven** [comment] 2017-06-20 09:15
This issue has already been fixed in develop branch.
Internal ticket for ver. 2.1 - MAGETWO-57153 - fix will be available in one of the nearest releases.
We were not able to reproduce this issue for ver. 2.0.

**Comment by veloraven** [comment] 2017-06-20 09:19
I'm closing this issue as a duplicate for #5885 - as there are more comments and info in that one.

**Closed as completed by veloraven** 2017-06-20 09:19 UTC
Labels: Issue: Ready for Work, bug report
