### ISSUE TITLE
2.3.5-p1 Guest Checkout - Api Call Guest Cart Status 400 Payment method

### ISSUE THREAD

**Issue by wilhelmpa** [magento/magento2#28161] opened 2020-05-08 13:06 UTC
Hi there, 

I have encountered the fowling bug.

Preconditions (*)
Magento 2.3.5-p1 vanilla
Varnish-5.2.1 revision 67e562482
Redis 4.0.9
Nginx 1.14.0
PHP 7.2.24

Steps to reproduce (*)
Add Something to cart and go to one page checkout as guest and try to redeem a coupon and look in the developer console. 

Expected result (*)
Redeem a coupon code in guest checkout with no error

Actual result (*)
In the developer console you can see that the ajax call:

https://www.xyz.de/rest/default/V1/guest-carts/xxxxxx/set-payment-information 

return the status 400. So the payment Method isn't set (Testet with Luma Theme and Amazon Pay, Klarna Checkout as well)

It also appears an error message in the frontend, which says that I have to select the payment method. As a result coupons can not be redeemed successfully because a new error appear after coupon redeem which states: 

select-payment-method-mixin.min.js:1 Uncaught TypeError: Cannot read property 'method' of null
    at select-payment-method-mixin.min.js:1
    at wrapper.min.js:2
    at Object.setPaymentMethods (payment-service.min.js:2)
    at Object.<anonymous> (get-payment-information.min.js:2)
    at fire (jquery.min.js:212)
    at Object.fireWith [as resolveWith] (jquery.min.js:218)
    at done (jquery.min.js:628)
    at XMLHttpRequest.callback (jquery.min.js:655)

and the loading Gauge won't disappear anymore.

Best Regards

Patrick

**Comment by steved1982** [comment] 2020-05-27 18:28
![image](https://user-images.githubusercontent.com/14214911/83058438-485b6b00-a050-11ea-996e-d62f9b55ba37.png)

**Comment by Neusta-Hartwig** [comment] 2020-06-02 12:43
This is already fixed in 2.4 (see https://github.com/magento/magento2/commit/e5cd82d87c7254503b4c9b6a7ff17017413dd016)

Greetings,
Christoph

**Comment by swathishs** [comment] 2020-06-04 14:45
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment] 2020-06-04 14:45
Hi @swathishs. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by girishanand** [comment] 2020-06-25 11:21
Since this ticket is still open so I comment here.
There is still an issue since on selecting the payment method on checkout the Api will still be fired which is okay for payment methods like **Cash on Delivery**, **Check / Money order** which does not require any input but for Payment method like  **Purchase Order** or Custom payment method Credit Card api call will throw 400 error as they require input from customer.
IMHO payment method on selection should not call API which require input or validation should be called after Place order button.

![image](https://user-images.githubusercontent.com/1632477/85710578-06335100-b704-11ea-94fe-f9c7166da1f8.png)

**Comment by speedupmate** [comment] 2020-06-26 09:32
> This is already fixed in 2.4 (see [e5cd82d](https://github.com/magento/magento2/commit/e5cd82d87c7254503b4c9b6a7ff17017413dd016))
> 

Can core team just agree that it is a bad practice to do another ajax call after some ajax call is finished , effectively this is what this mixin does . And instead of this mixin create a plugin or observer for backend code to append it to existing results on the ajax call it tries to depend on.

**Comment by rhoerr** [comment] 2020-07-29 21:31
Affirming @girishanand 's note -- I do not believe https://github.com/magento/magento2/commit/e5cd82d87c7254503b4c9b6a7ff17017413dd016 fully resolves this issue. It prevents the 'undefined method' JS error but does not prevent payment validation errors from displaying over the coupon form. This is easily reproduced:
- Enable the Purchase Order payment method
- Go to checkout and open the discount form
- Select the Purchase Order payment method
- See how the discount form displays "Purchase order number is a required field.", despite no relevance to the coupon form and no opportunity for the user to have entered one yet.

The underlying cause is exactly the same mixin causing set-payment-information to be fired prematurely, and then displaying resulting error messages where they should not be.

A payment method is selected in this case, so the `if (paymentMethod === null) {` check added in 2.4.0 does not resolve this.

![2020-07-29_171844](https://user-images.githubusercontent.com/13335952/88855310-a88d9b00-d1c0-11ea-9a46-7b5a694f961a.png)

**Comment by speedupmate** [comment] 2020-08-24 14:29
https://github.com/magento/magento2/commit/e5cd82d87c7254503b4c9b6a7ff17017413dd016 will not solve this until every bit of data that this endpoint needs is validated before endpoint is called . 

+ its still incredibly stupid to evoke the action after one action is finished 

This change is so incredibly bad that its almost impossible to disable this ajax call without loosing backwards compatibility (for extension providers) or without just overwriting this file in theme context

**Comment by sayanthkoroth** [comment] 2020-08-25 05:48
@magento-engcom-team Is there any update here ? I am using custom payment method in my store and I updated the store to 2.3.5-p2. Now on selecting credit card as payment method, an ajax 'set-payment-information' is triggered with a 400 status code.

**Comment by paul-gene** [comment] 2020-08-25 14:25
@sayanthkoroth you're wasting your time I imagine. Magento won't fix this for 2.3.5 now that 2.4 is out.

**Comment by speedupmate** [comment] 2020-09-13 23:32
who really needs to disable this mishap from their own extension can add to their requirejs-config.js file 

`'Magento_Checkout/js/action/select-payment-method': {
                 'Magento_SalesRule/js/action/select-payment-method-mixin': false
}`

be aware that this module adds multiple such mixins to different action calls and you might need to disable those too

**Comment by girishanand** [comment] 2020-09-15 13:04
Basically API call on payment method selection needs to be disabled for any payment method.
The other way to disable it like @speedupmate mentioned is using the composer instead.

`"scripts": {
	"post-install-cmd": [
		"perl -pi -e \"s|'Magento_SalesRule/js/action/select-payment-method-mixin': true|'Magento_SalesRule/js/action/select-payment-method-mixin': false|\" vendor/magento/module-sales-rule/view/frontend/requirejs-config.js"
	],
	"post-update-cmd": [
		"perl -pi -e \"s|'Magento_SalesRule/js/action/select-payment-method-mixin': true|'Magento_SalesRule/js/action/select-payment-method-mixin': false|\" vendor/magento/module-sales-rule/view/frontend/requirejs-config.js"
	]
}`

**Comment by chirag-taraviya** [comment] 2020-09-29 06:43
Here is solution for 2.3.5 Extend select-payment-method-mixin.js to Your Theme app/design/frontend/Vender/Theme/Magento_SalesRule/web/js/action/select-payment-method-mixin.js

Add below code on line NO. 22
 if (paymentMethod === null) {
                return;
   }

**Comment by speedupmate** [comment] 2020-09-29 06:47
@chirag-taraviya this is bit useless.  Since there can be other params this endpoint needs or payment method needs to send to get a valid response from this endpoint

**Comment by rhoerr** [comment] 2020-11-04 14:14
Follow up: The same underlying validation error prevents Purchase Order (and any other payment methods with `global` field validation or otherwise extending `\Magento\Payment\Model\Method\AbstractMethod::validate()`) from working for the Cart Price Rule "Payment Method" condition. I believe that condition (added somewhere in 2.3) is what the AJAX call and mixin causing all of this was added for in the first place.

![2020-11-04_091411](https://user-images.githubusercontent.com/13335952/98122120-26c3a280-1e7e-11eb-92cc-40c80b2791c3.png)


Realistically, it should probably assign the payment method without first validating said payment method. You shouldn't need all payment fields to be filled in before you mark a method as active on the quote.

**Comment by engcom-Alfa** [comment] 2021-01-26 13:17
Hi @wilhelmpa . Thank you for your report!
Unfortunately, we are not able to reproduce the issue on fresh 2.4-develop. Looks like the problem has already been fixed.
Was checked the problem described in the description and from the comments and everything works as expected.
There are no errors in the process of creating an order using coupons.

@wilhelmpa Are you able to reproduce this issue on clean Magento 2.4-develop?
Thanks!

**Comment by rhoerr** [comment] 2021-01-26 14:01
Please try this additional test case based on my [prior note](https://github.com/magento/magento2/issues/28161#issuecomment-665939397):

- Create a coupon with condition "Payment Method is Purchase Order"
- Go to frontend checkout
- Select 'Purchase Order' payment method
  - See that action initiates set-payment-information 400 request
  - See that the discount form displays "Purchase order number is a required field.", despite no opportunity to enter a PO number, and no relevance of that error to the discount form
- Add PO-specific coupon
  - See that coupon/discount does not apply

**Comment by engcom-Alfa** [comment] 2021-01-28 13:55
@rhoerr .
We tried to reproduce the problem on 2.4-develop, but without success. Everything works well.

**Manual testing scenario:**

1. Create a coupon with a condition "Payment Method is Purchase Order"
2. Go to frontend checkout
3. Select 'Purchase Order' payment method;

**Actual Result:** :heavy_check_mark: Discount form does not display "Purchase order number is a required field." and `set-payment-information` 200 OK

![Peek 2021-01-28 15-49](https://user-images.githubusercontent.com/51679138/106147480-92b55e80-6180-11eb-9dbd-f36d37b6d8a9.gif)

![Screenshot from 2021-01-28 15-47-30](https://user-images.githubusercontent.com/51679138/106147495-96e17c00-6180-11eb-9d75-595fa70efa1c.png)

4. Add PO-specific coupon;

**Actual Result:** :heavy_check_mark: Coupon/discount is applied

![Screenshot from 2021-01-28 15-53-08](https://user-images.githubusercontent.com/51679138/106147801-f8a1e600-6180-11eb-84d7-a8b579df1959.png)

@rhoerr Looks like the problem has already been fixed in 2.4-develop by commit a56f2c5ea7fa7c67644b079d4048c737edabaacf

Could you take a look?
Thanks!

**Comment by rhoerr** [comment] 2021-01-28 14:02
Removing validation from the payment method's `validate()` method is an interesting way of fixing it, but I can confirm that'll work around the issue at least as it relates to the Purchase Order payment method.

I still submit it's a design flaw that should not have been introduced in the first place, since it completely defeats payment methods' validation interface. But that's a battle I'm never going to win. It might be best to mark `\Magento\Payment\Model\MethodInterface::validate()` deprecated, considering any exception thrown there will cause the same issue Purchase Order had.

**Comment by speedupmate** [comment] 2021-01-28 21:18
@engcom-Alfa  not sure if any of your team here got the issue and forgive me on commeting this and I mean no harm no offence etc just commenting this from the merchant and end user perspective: 

1. a rest endpoint (set-payment-information) is called after rest endpoint is called 
1.1. the latter rest endpoint happens to validates data and expects actual parameters dependant of payment method structure
1.2. you can't call that rest endpoint without being sure you have the data otherwise you get the error, frontend validation is not to be trusted thats web-sec ABC 
3. random method (bespoke mixin) calls the endpoint without verifying the data and knowing what data si expected

your solution (forgive the humour and don't take it as bashing , coding is fun) : 

1. lets remove validation of only payment form we know = hide head under the sand
3. implement the validation inside a plugin = lets go around the world, around the house and around the bush and maybe its solved
4. merchant installs random CC method full of fancy forms = head is under sand , sadly *ss still wide open , exceptions still thrown and expected

what would have helped :

1. remove the stupid mixin and remove callback of  ajax callback  = no more chained ajax calls that slow down the frontend
2. improve the first ajax call respnse output with a plugin (to interface) to give you the needed  data on totals update (and maybe a list of updated payment methods) you seek form the rest endpoint and update UI within your callback method 

I mean looking at referred commit , developer made a huge junk of work, tests etc and still ignored the essence of this issue and still kept:

* bad frontend coding practice 
* not solving anything

**Comment by speedupmate** [comment] 2021-01-28 23:37
@engcom-Alfa  So maybe it helps if we explain again what happens or why this issue is so important to get right, lets pick the process apart: 

<img width="773" alt="Screenshot 2021-01-29 at 01 31 01" src="https://user-images.githubusercontent.com/623004/106211784-f2882580-61d1-11eb-8800-de6022715a29.png">

### 1. by default selecting a payment method evokes 

https://github.com/magento/magento2/blob/2a4641bdab1f53ab03ab7f0ca60f277b9746c812/app/code/Magento/Checkout/view/frontend/web/js/view/payment/default.js#L175

following action  selectPaymentMethodAction(this.getData()); 

https://github.com/magento/magento2/blob/2a4641bdab1f53ab03ab7f0ca60f277b9746c812/app/code/Magento/Checkout/view/frontend/web/js/action/select-payment-method.js#L20 

and this does not evoke/execute any ajax calls just sets data to quote . on Ui level we expect no ajax calls, loaders etc

### 2. salesrule extension adds a mixin 

https://github.com/magento/magento2/blob/2a4641bdab1f53ab03ab7f0ca60f277b9746c812/app/code/Magento/SalesRule/view/frontend/requirejs-config.js#L9 

that mixin calls the default method and then does a ajax call to set-payment-information endpoint

https://github.com/magento/magento2/blob/2a4641bdab1f53ab03ab7f0ca60f277b9746c812/app/code/Magento/SalesRule/view/frontend/web/js/action/select-payment-method-mixin.js#L26 

this endpoint is executing 

https://github.com/magento/magento2/blob/2a4641bdab1f53ab03ab7f0ca60f277b9746c812/app/code/Magento/Checkout/Model/PaymentInformationManagement.php#L119 

sadly it is dumb endpoint it either throws in following order 

https://github.com/magento/magento2/blob/2a4641bdab1f53ab03ab7f0ca60f277b9746c812/app/code/Magento/Quote/Model/PaymentMethodManagement.php#L52
https://github.com/magento/magento2/blob/2a4641bdab1f53ab03ab7f0ca60f277b9746c812/app/code/Magento/Quote/Model/PaymentMethodManagement.php#L79
https://github.com/magento/magento2/blob/2a4641bdab1f53ab03ab7f0ca60f277b9746c812/app/code/Magento/Quote/Model/Quote/Payment.php#L202

or returns true 

https://github.com/magento/magento2/blob/2a4641bdab1f53ab03ab7f0ca60f277b9746c812/app/code/Magento/Checkout/Model/PaymentInformationManagement.php#L149

### 3. What this mixin does and why ? It tries to validate if the coupon is set in totals after payment method is set and then remove if not 

https://github.com/magento/magento2/blob/2a4641bdab1f53ab03ab7f0ca60f277b9746c812/app/code/Magento/SalesRule/view/frontend/web/js/action/select-payment-method-mixin.js#L43

It probably does this as someone assumes that saving a payment method can affect sales rule availability . Cool, lets fix it the way you intended , with a ajax call to action that expects payment method to be valid and payment method can be valid: 

* if data is there 
* if preflight tokens are there 
* if customer authenticates on payment gateway etc 
* insane ways payment methods validate their data before allowing to be set
* point being you can't know how people will handle this but just know that they do validate() 

I assume (forgive me as I might be off tracks ) that whoever implemented this just did not realise the scope of this API endpoint or task given and what this api endpoint needs to be set/sent beforehand for it to be successful . 

Maybe it comes as news Paypal Express implementation uses this endpoint to place the order , so take the "deprecate validate()" from @rhoerr with (huge) grain of salt. 

**_When you do that {n} payment methods on the market and in core need to be reimplemented to work with this new insane plugin-validate system offered in referred commit https://github.com/magento/magento2/commit/a56f2c5ea7fa7c67644b079d4048c737edabaacf .  Mentioned fix should not be released at all , since examples are taken from code by random developers not seeing the whole image. This implementation shown in this commit is not a fix its crap (sorry, I don't want to offend and I'm not in bad mood it's just plain truth)_** 

### 4. Instead of all the pain released with this mixin what should you do to fix it properly ? 

* remove the mixin as this endpoint execution is not meant for getting this information 
* remove all this off-track stuff to reinvent validation https://github.com/magento/magento2/commit/a56f2c5ea7fa7c67644b079d4048c737edabaacf 

* if you still need this data use the get-payment-information action instead but I assume that is not enough to know if salesrule is invalid and you are stuck and need to make a new plan
https://github.com/magento/magento2/blob/2a4641bdab1f53ab03ab7f0ca60f277b9746c812/app/code/Magento/Checkout/view/frontend/web/js/action/get-payment-information.js#L37
* validate and discard salesrule in order placement request after payment method is set, any error thrown there will bounce back to frontend with a error message , you can expand that error response with a plugin for your specific state detection. (say coupon: false) 
* based on error condition give users options/message what to do or what changes : coupon is not valid any more , change payment method, discard the coupon 
* or implement a new api endpoint /V1/guest-carts/:cartId/set-payment-method that only sets the method to quote and validates your totals and returns the totals
* or implement a new api endpoint /V1/coupons/:cartId/validate that (soft) validates (without setting anything to quote) with whatever data posted to it and returns your totals or validation status as json (not just true/false) so you don't need to make more calls to get the state

Hope this helps to explain what's the issue is all about. Thanks ahead for whoever decides to make right decisions to fix this properly.

**Comment by PascalBrouwers** [comment] 2021-01-29 07:44
@engcom-Alfa did you also try other payment methods that require user input like credit card?

**Comment by girishanand** [comment] 2021-01-29 07:58
Hello @PascalBrouwers , Just updating here as we use Paymetric (iframe within the site) we have issue there as well since it requires customer input for card information submitted from the site.

**Comment by fooman** [comment] 2021-02-02 20:57
> or implement a new api endpoint /V1/guest-carts/:cartId/set-payment-method that only sets the method to quote and validates your totals and returns the totals

👍

**Comment by tcmax76** [comment] 2021-03-23 17:04
We're on Magento 2.4.2 and use authorize.net credit card as our singular payment method on our website. We've also added the Discount form to the top of the payment page. I assume because the authorize.net payment method is automatically selected on reaching the payment page, we're getting this lovely error above the discount field every time the payment page comes up.

![payment-page-error](https://user-images.githubusercontent.com/7738781/112187102-28e19000-8bd8-11eb-8ff6-8d96af6235c2.png)

Is there any way around this until this (hopefully) gets fixed in a future version?

**Comment by itg-ddanielson** [comment] 2021-05-17 19:20
I can confirm we are getting this issue as well using a custom payment module. Best workaround I can think of is to but different valiation logic in our modules validate() method or do disable the mixin. Any other suggestions?

**Comment by braders** [comment] 2021-05-20 17:30
I'm also seeing this issue, and am amazed that it seems to be default behaviour in a platform like Magento - it's really not good. 

I think I'm going to try disabling the mixin, which I assume will just mean that shopping cart rules cannot be set per payment method. Are there any other side-effects others on this thread have faced which we should be aware of? Thanks.

**Comment by engcom-Hotel** [comment] 2021-09-30 06:46
Hello @wilhelmpa,

We have tried to reproduce the issue in Magento 2.4-develop but were unable to reproduce it, it might be the case this issue has been resolved in this branch. Please have a look at to below screenshot for reference:

![image](https://user-images.githubusercontent.com/51681618/135400969-bd60ffc4-ba52-4080-aae3-61526fcb6e80.png)

We are closing this issue for now because this is not reproducible in the 2.4-develop branch. Please reopen it or create a new ticket in case you still facing this issue.

Thanks

**Comment by girishanand** [comment] 2021-09-30 07:03
Hello Abhinav,

Did you made the test with enabling the Purchase order or some other one
which have required fields to fill in.
I hope you are aware of the issue?

Thanks
Girish

**Comment by speedupmate** [comment] 2021-09-30 08:12
@engcom-Hotel I painted this issue in red https://github.com/magento/magento2/issues/28161#issuecomment-769470078  if the code is the same the issue is the same. 

Hint, code is the same: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/SalesRule/view/frontend/web/js/action/select-payment-method-mixin.js

**Comment by speedupmate** [comment] 2021-10-01 12:50
@engcom-Hotel reopen the issue please

**Comment by Veltix** [comment] 2022-02-02 13:10
I have also same issu in 2.4.3-p1! Any solutions for fix?

**Comment by roman204** [comment] 2022-04-20 14:07
Even in Magento 2.3.4-p2 this behavior is still alive it's a shame

**Comment by speedupmate** [comment] 2022-04-22 08:19
shortcut that mixin and move on it will never be improved

**Comment by ClintTec** [comment] 2022-10-12 15:03
Still happening.

**Comment by engcom-Hotel** [comment] 2022-10-13 05:52
Hello,

We are reopening this ticket as we more inputs on this issue to reproduce.

Thanks

**Comment by engcom-Hotel** [comment] 2022-11-03 08:24
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-11-03 08:29
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-11-14 11:24
Hello @wilhelmpa @speedupmate @teodorpav,

We have tried to reproduce the issue in the bot instance above but the issue is still not reproducible for us. The bot instance has version 2.4-develop. 

As I can see the issue is a little bit old and we have had enough discussion here on this issue. But still, I am requesting to summarise the steps in order to reproduce the issue. It will help us in moving faster with this issue.

Thanks

**Comment by speedupmate** [comment] 2022-11-15 07:00
@engcom-Hotel do you know how to use google chrome developer tools ? If so then just trigger the action without data being set in forms and you get the error

**Comment by tuyennn** [comment] 2022-11-16 13:34
Has same issue with payments which have input credit card on checkout
![image](https://user-images.githubusercontent.com/4010395/202194361-6e25353a-a16c-4235-8430-5e1cde19e311.png)

**Comment by engcom-Hotel** [comment] 2022-11-25 08:22
Hello @tuyennn,

Thanks for the report!

Please let us know more about the issue. Like the steps to reproduce the issue etc.

It will help us in moving further with this ticket.

Thanks

**Comment by tuyennn** [comment] 2022-11-25 08:39
@engcom-Hotel Hard to replicate this in regular condition with offline payments.
But our live site is using Paypal, Braintree, Klarna payment Guest checkout enabled.
The problem is we got bunch of 400 Bad Request with `default/V1/guest-carts/xxxxxxxxx/set-payment-information`

We are using Noibu to trace the problem and actually solution came out after I read through this issue,

As @speedupmate explained on https://github.com/magento/magento2/issues/28161#issuecomment-769470078, I think this was quite clear.

We are monitoring this issue on Noibu, it looks promising after we disabled this mixin '**Magento_SalesRule/js/action/select-payment-method-mixin'**: false. by patching.
But doesn't seem this occurred again after the patch, looking good now.

**Comment by tuyennn** [comment] 2022-11-30 10:37
@engcom-Hotel we confirmed the issue is no longer exist after disabling the mixing.
The issue could be replicated with Paypal Braintree and Guest checkout enabled.
While performing applying coupon the issue will occurred.

**Comment by engcom-Bravo** [comment] 2023-01-16 08:42
Hi @wilhelmpa @tuyennn,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible. Kindly refer the screenhsots.


**Steps to reproduce:**

1.Enabled purchase order and guest checkout
2.Created PayPal 
3.Added product to cart and went to checkout as guest and tried to redeem a coupon and look in the developer console.
4.Checked both with PayPal and purchase order issue is not getting reproducible.



<img width="929" alt="Screenshot 2023-01-16 at 2 05 12 PM" src="https://user-images.githubusercontent.com/51680745/212633999-ff724f9e-3c58-4981-9a5a-89507a692c01.png">



<img width="895" alt="Screenshot 2023-01-16 at 2 05 53 PM" src="https://user-images.githubusercontent.com/51680745/212634069-c16d511c-a198-4850-acdd-e9e7a13de370.png">



Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Kindly let us know if we are still missing anthing.

Thanks.

**Comment by engcom-Hotel** [comment] 2023-02-02 11:51
Dear @wilhelmpa @tuyennn,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2023-02-02 11:51 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.3.5-p1

**Comment by speedupmate** [comment] 2023-02-18 07:27
magic,  solved by waiting 14 days

**Comment by tuyennn** [comment] 2023-04-04 16:21
Today we was facing another issue regarding to additional call made by `select-payment-method-mixin`, once again I recommend to disable this mixin config for the projects

**Comment by usman786cs** [comment] 2023-11-07 23:05
@tuyennn 
what could be the -ve impacts of disabling it?
We have paypal payment method enabled on our store.

**Comment by tuyennn** [comment] 2023-11-08 03:44
@usman786cs https://github.com/magento/magento2/issues/28161#issuecomment-691741577
