### ISSUE TITLE
Tax with Country store dropdown option not auto select actual tax rule calculation.

### ISSUE THREAD

**Issue by irshad-iflair** [magento/magento2#26831] opened 2020-02-12 09:28 UTC
**Summary of the issue**
**I need, Multiple stores have a common country (i.e. united states and country states* should be all) then different tax rules for all stores**.

### Preconditions (*)

Magento 2.3.2: I create Two different stores **US and US1** for the **common country (i.e. united states)** https://i.stack.imgur.com/S3X1I.png. Then create **two different tax rules (i.e. US-tax rule and US1-tax rule)** for both stores. https://i.stack.imgur.com/801Jw.png next In **Tax Zones and Rates set** **US Tax rate 5% and US1 tax 10%**. https://i.stack.imgur.com/VrSe6.png Now on the product details page while choosing store from the dropdown, **product price display sum of 5%+10%, that is the wrong calculation**. 
example the product price is $22https://i.stack.imgur.com/F7hrn.png.
**on selecting US1 or US stores on both step.**

**result display 22(10% + 5%) = 25.30$ (wrong)** https://i.stack.imgur.com/qiMFs.png.
**Steps to reproduce (*)**
**how can I display separate tax rates on the product on selected stores.**

**1. it should be on choosing US store 22*10%= $24.2(right)**
2. **US1 store 22*5%= $23.1 (right).**
**Is it bug or functionality?**

**Comment by irshad-iflair** [comment] 2020-02-12 09:43
yes want to produce on vanilla Magento instance

**Comment by irshad-iflair** [comment] 2020-02-12 10:21
YES

**Comment by engcom-Bravo** [comment] 2020-02-13 15:06
Duplicate of #26853

**Closed as completed by engcom-Bravo** 2020-02-13 15:06 UTC
Labels: Issue: Format is not valid, Reported on 2.3.2
