### ISSUE TITLE
Permanent Redirect for old URL didn't created if it was.

### ISSUE THREAD

**Issue by klakovsky** [magento/magento2#10096] opened 2017-06-29 12:43 UTC
### Preconditions

1. Magento CE 2.1.7 fresh instans without sample data.

### Steps to reproduce

1.  Create new simple product with Product Name="simple1", Price=1 and save them.
2.  Edit this product for change URL Key = simple1-new1, save checkbox (Create Permanent Redirect for old URL) and save them.
3. Edit this product for change URL Key = simple1-new2, save checkbox (Create Permanent Redirect for old URL) and save them.
4. Go to "Marketing->URL Rewrites", set filters "Request path"="simple1".

### Expected result

1. We must see 2 permanent redirects from "simple1.html" to "simple1-new2.html" and from "simple1-new1.html" to "simple1-new2.html"

### Actual result

1. We  see 1 permanent redirect from "simple1.html" to "simple1-new2.html"

### Some additionals notes:
This issue was reproduced on Magento CE 2.1.4 and 2.1.5 too.

**Comment by 1408sheva** [comment] 2017-07-04 07:55
@klakovskiy Thanks for reporting this issue. 
We've created internal ticket MAGETWO-70438 to address this issue.

**Comment by mcretien** [comment] 2017-08-24 04:16
Seems to be fixed in Magento CE 2.1.8 despite nothing appears in the release notes.

**Comment by magento-engcom-team** [comment] 2017-10-06 10:30
@klakovskiy, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-06 10:30 UTC
Labels: Issue: Ready for Work, bug report, Component: CatalogUrlRewrite, Issue:  Cannot Reproduce, Issue: Format is valid
