### ISSUE TITLE
 calc(100% - 100px) break by minify 

### ISSUE THREAD

**Issue by larsroettig** [magento/magento2#12794] opened 2017-12-18 17:52 UTC
### Preconditions
- Install Magento  Open Source 2.2 or 2.3dev 
- This branches  use  tubalmartin/cssmin 2.4.8-p4 

### Steps to reproduce
1.  Define `calc(100% - 100px) `in stylesheet
2.  Active css minify 

### Expected result
1.  In css.min is defined` calc(100% - 100px)`

### Actual result
1.  In css.min is defined` calc(100%-100px)`
2.  It is not allowed to remove  whitespaces before  and after **-** breaks the stylesheet

### Possible  Solution 
- Update to version 4.1  see: https://github.com/larsroettig/magento2_css_min_fix/blob/master/test.css.min
- https://github.com/tubalmartin/YUI-CSS-compressor-PHP-port#6-changelog has many bugfixes and performance improvements 

### Info 
https://www.w3schools.com/cssref/func_calc.asp

**Comment by sydekumf** [comment] 2017-12-19 06:49
Duplicate of: https://github.com/magento/magento2/issues/8552

**Comment by larsroettig** [comment] 2017-12-19 07:18
@sydekumf is not done Magento Base Install the wrong version in Magento 2.3.dev also

**Closed as completed** 2017-12-19 07:23 UTC
Labels: Issue: Format is valid
