### ISSUE TITLE
Update items qty on cart or minicart doesn't work with several es_ locales

### ISSUE THREAD

**Issue by barbanet** [magento/magento2#3619] opened 2016-03-02 19:46 UTC
I've created [this issue also on M1 bug tracker](https://www.magentocommerce.com/bug-tracking/issue/index/id/1200) because this problem cames from Zend_Locale and the locales xml definitions.

Using most of the es_ locales (es_ES and es_MX works fine) you aren't able to update cart quantities because the filter method on Zend_Filter_LocalizedToNormalized can't validate the number as number.

I understand that this problem is from Zend_Framework but I wasn't able to fix it yet.

When I try to update the quantity I get this message:

> exception 'Zend_Locale_Exception' with message 'Unsupported token for numberformat (Pos 6):"#"

In my case I'm using es_AR as locale but also happens with another es_ locales too.

**Comment by piotrekkaminski** [comment] 2016-06-20 22:57
@barbanet does it happen in admin or in front-end? what are the steps to reproduce?

**Comment by mauromm** [comment] 2016-06-20 23:21
Hi @piotrekkaminski, I have the same issue when use es_AR locale. The steps to reproduce the problem are:

1- Install a clean magento 2.0.x
2- In admin panel, go to Stores > Configuration > General 
3- set Country Argentina and locale Spanish(Argentina) 
4- Create a simple product and a category.
5- Go to frontend and add to cart 4 items.
6- In frontend go to cart and try to modify item's qty.
7- When you submit the update, cart qty is reset to 1.

I have found the problem is in **isNumber()** on **../vendor/magento/zendframework1/library/Zend/Locale/Format.php **

**Comment by valenciaisaza** [comment] 2016-07-21 18:24
Hi @piotrekkaminski 

The same problem reported by @barbanet for M1 is happening in M2

Here is the link with the explanation of the problem in the comments [Issue #8461](https://www.magentocommerce.com/bug-tracking/issue/index/id/1200)

The missing pattern es_419.xml or in each of your children is:

`<decimalFormats numberSystem="latn">
    <decimalFormatLength>
        <decimalFormat>
            <pattern>#,##0.###</pattern>
        </decimalFormat>
    </decimalFormatLength>
</decimalFormats>`

Any other missing definition in this file is a potential problem if it is not inherited from es.xml

**Comment by veloraven** [comment] 2016-10-24 12:32
I'm closing this issue as duplicate as we already have internal ticket MAGETWO-59973 for issue #6656.
I have updated internal ticket with additional information from this issue.

**Closed as completed by veloraven** 2016-10-24 12:32 UTC
Labels: bug report, Component: Checkout
