### ISSUE TITLE
Magento 2.1 wrong website id in catalog_inventory tables

### ISSUE THREAD

**Issue by PierAlex** [magento/magento2#5649] opened 2016-07-14 20:34 UTC
cataloginventory_stock:
![image](https://cloud.githubusercontent.com/assets/17165819/16854532/9cdcfe76-4a11-11e6-9fee-9cca3a926db9.png)

cataloginventory_stock_item
![image](https://cloud.githubusercontent.com/assets/17165819/16854564/cfba34f8-4a11-11e6-9982-88ada98c4a73.png)

cataloginventory_stock_status:
![image](https://cloud.githubusercontent.com/assets/17165819/16854603/03493350-4a12-11e6-928f-6a175ece3dca.png)

cataloginventory_stock_status_idx:
![image](https://cloud.githubusercontent.com/assets/17165819/16854673/500eae04-4a12-11e6-9034-9a7b5782ebee.png)

store_website:
![image](https://cloud.githubusercontent.com/assets/17165819/16854753/af1c613e-4a12-11e6-874b-8c020563bfc2.png)

...and what is website 0 admin?

**Comment by maderlock** [comment] 2016-07-15 17:47
In CE, all stock is against website of id 0. This is confusing, but not a bug.

**Comment by andimov** [comment] 2016-08-02 10:51
@PierAlex 
This is not a bug. I'm closing this issue. Please feel free to reopen if you need.

**Closed as completed by andimov** 2016-08-02 10:51 UTC
