### ISSUE TITLE
Minicart is always empty with luma theme

### ISSUE THREAD

**Issue by kfaer** [magento/magento2#5554] opened 2016-07-08 21:44 UTC
bought items added to cart but it is not showing in the minicart, how i can trust M2 to sell my products to my customers with such issue.
@antboiko 
![m2-minicart](https://cloud.githubusercontent.com/assets/8407530/16702186/779d494a-4575-11e6-91cb-6c94327ce664.PNG)

**Comment by commcad** [comment] 2016-07-09 06:09
Are you 'freely' complaining mate!? M2 is new and still in dev - if you can't fix it or make it better/faster than Magento Inc then by all means buy yourself a mature ecommerce platform. Lucky you; those retail more or less $100k~$500k.

Note that I've had that same issue on M2.1.0 RC3 to find out that my permissions weren't set properly on my /root when I've initially installed it.

**Comment by kfaer** [comment] 2016-07-09 06:20
OK.. so do you think it is still too early to use M2.1 in production?

**Comment by commcad** [comment] 2016-07-09 06:31
Happily in prod with M2.1.0GA here bud. Just make sure you install it correctly with properly set and maintained permissions. The only true "operational" issue I came across was the dB schema (https://github.com/magento/magento2/issues/4785) and (less operational related) some email templates that weren't loading correctly (https://github.com/magento/magento2/issues/5101).

Both offering quick fixes. Of course there are few other bugs but nothing in the lines that would make you and/or your customers to fail. So I'd say yes, good enough for prod.

Other than that, the thing is flying at 100mph and selling days & nights here.

**Comment by kfaer** [comment] 2016-07-09 06:38
ok.. can you test my site from your side and check if you can add a product/s to cart? herara.com

**Comment by commcad** [comment] 2016-07-09 06:44
Run below first and I'll give it a try:

(replace: _m2user_ as in your login account and _www-data_ as your nginx/apache group)

cd /your m2 root/

sudo usermod -g www-data _m2user_
sudo chown -R _m2user_:www-data .
find var vendor pub/static pub/media app/etc -type f -exec chmod g+w {} \;
find var vendor pub/static pub/media app/etc -type d -exec chmod g+ws {} \;
chown -R :www-data .
chmod u+x bin/magento

Once you've set perms, run below to bring it back to an ootb stance.

rm -rf /var/www/mydomain.com/var/di
rm -rf /var/www/mydomain.com/pub/static/frontend/
rm -rf /var/www/mydomain.com/var/view_preprocessed/*
rm -rf /var/www/mydomain.com/var/page_cache/*
rm -rf /var/www/mydomain.com/var/generation/*
php bin/magento setup:upgrade && php bin/magento setup:di:compile && php bin/magento setup:static-content:deploy && php bin/magento indexer:reindex && php bin/magento cache:clean && php bin/magento cache:flush

Let me know and I'll give it a go

**Comment by kfaer** [comment] 2016-07-09 06:49
I'm using centos 7 with plesk

**Comment by commcad** [comment] 2016-07-09 06:51
Just adjust so centos doesn't complain. Should be the same or similar. 

Tried your site and you are correct, minicart does not increment :/

**Comment by kfaer** [comment] 2016-07-09 06:54
it will increment if you visit the checkout/cart page then wait for the summary to load (i do not know why it takes time to load) only at that time the minicart works....!

**Comment by stevekem** [comment] 2016-07-10 01:09
https://github.com/magento/magento2/issues/5144#issuecomment-228456034

**Comment by stevekem** [comment] 2016-07-10 01:15
Might be a different issue than what your having, but thought I would share.

**Comment by kfaer** [comment] 2016-07-10 20:29
@stevekem  thank you, I think that solve the issue, testing , @commcad could you please test it, thank you

**Comment by commcad** [comment] 2016-07-10 23:44
No, not working. If not perms related then it looks as if you have 'session' issues. Does not checkin nor increment your minicart and the green banner trails for a few pages.

I see that you have tried to reinstall everything. How are you managing your sessions? use M2's cache, Opcache, memcache, others? redis?

**Comment by kfaer** [comment] 2016-07-11 07:42
I'm using M2's cache but php opcashe is enabled

**Comment by hgpit** [comment] 2016-07-12 08:55
@commcad. How can M2.1 still be officially considered "in dev" when they're offering it in the official downloads area for corporate/enterprise customers and charging ~£18k/year for the privilege?
There are ZERO "beta"/"in dev" disclaimers via the corporate portal and whenever I have contacted their corporate support regarding M2.x they've never told me to go back to M1. Simply go to https://magento.com - does that look like they're pushing an "in dev" product?

That being said, Magento 2.x is a sorry excuse for a business-ready solution. If it was free across the board (CE & EE) I could accept it, but instead it's quite laughable how Magento have the cheek to charge such amounts for such poorly developed software. I work with a lot of open source software, and most of it is great; amazing feats of software engineering in fact. But M2.x is nothing more than a train wreck in its current state. I truly hope it "matures" into a great platform, because the potential is there, but right now I wouldn't recommend it to any serious merchant - despite what Magento corporate would have you believe.

**Comment by commcad** [comment] 2016-07-12 10:51
Always had in mind that open source meant WIP. Regardless of the little adds and fancy pics (and all that CSS Three point Ohh)

Broader view; would you agree that modern technologies as a whole are a train wreck on its own? Investing in those sectors is pretty similar to gambling my friend, last time I’ve checked (looking at it from a board member’s perspective, mind you). Magento aside; there is a new programing language/library born every single weeks some having their name and purpose possibly ported to a random maiden’s name, who f n knows. That perfect eco-tech world you dream of is not going to get any better. Calls on the IEEE and the like.

My point is even if XYZ Corp is doing better now does not explicitly mean that they will in a 24months. In these circumstances, what then constitutes a serious online merchant in your opinion?!

Side note; we make products and excel in our areas of expertise (SME). Little experience in the Magento core engine myself (couldn’t care less maybe) but quite familiar with their newly established corporate product life cycle “and transparencies”. That’s what makes us feel integrated in all honesty. Meaningless bugs or not, at the end of the day Magento works for us and does/did for quite a few other retailers (correct me if I’m wrong).

@hgpit

**Comment by kfaer** [comment] 2016-08-15 17:17
@vkorotun, seriously it is something Confusing, same installation, same files, same DB different domains, one is working fine the other is not, check herara.com (M2 mini cart not function) & the other yahbee.com working fine......?! installation is M2.1

**Comment by commcad** [comment] 2016-08-17 10:38
The yah domain loads up so much faster btw, from Los Angeles anyway. Time to get stuff listed my friend ;)

Some ref for you to dig in

https://github.com/magento/magento2/pull/5807
https://github.com/magento/magento2/pull/5854
https://github.com/magento/magento2/issues?utf8=%E2%9C%93&q=minicart%20fix

**Comment by veloraven** [comment] 2016-09-13 09:33
@kfaer thank you for reporting.
Is this issue still actual?
If it is please specify exact Magento version you use.
Please also specify if it was clear install or upgrade from previous version.
And please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
If the issue is not actual for you now, please close it.

**Comment by veloraven** [comment] 2016-10-28 09:20
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Closed as completed by veloraven** 2016-10-28 09:20 UTC
Labels: Progress: needs update, Area: Frontend
