### ISSUE TITLE
JavaScript error: "Cannot read property 'closed'"  in Product Edit Page

### ISSUE THREAD

**Issue by Valentyn-Kubrak** [magento/magento2#5212] opened 2016-06-24 06:54 UTC
I found problem with window in edit product page from first magento 2 releases, when you opens Wysiwyg editor many times, then something is going wrong with JavaScript object initialization.

In new Magento 2.1 developers disabled window for wysisbvig, but I see still probem for "Insert Image" button.
## Steps to reproduce
1. Update Magento 2.0.7 to Magento 2.1 
2. Go to edit product Page
3. Click On "Insert Image"
4. Close Window
5. Click On "Insert Image" again
6. In browser console you will see:

Uncaught TypeError: Cannot read property 'closed' of undefined in  browser.js 39

And I can't open window for inserting image twice.

**Comment by Valentyn-Kubrak** [comment] 2016-07-13 15:44
Hello Team! It's real priority issue, Wysiwyg does not work correctly on all magento versions.

**Comment by koenner01** [comment] 2016-07-15 12:46
I can confirm this issue. 
Temporary bugfix would be to change the following in lib\web\mage\adminhtml\browser.js

Change 
`closeDialog: function() {
            this.modal.modal('closeModal');
        }`

to 
`closeDialog: function() {
            this.modal.modal('closeModal');
            this.modal = null;
        }`

But I assume it's not the 'correct' solution to reset the modal parameter on the MediabrowserUtility object so that's why I'm calling this a temp fix :)

**Comment by minhluan259** [comment] 2016-09-18 03:12
@koenner01 , your way is'nt work.
but I've fixed by change (lib\web\mage\adminhtml\browser.js)

```
            if (this.modal) {
                this.modal.html($(content).html());
                this.modal.modal('option', 'closed', options.closed);
            }
```

to 

```
            if (this.modal) {
                this.modal.html($(content).html());
                this.modal.modal('option', 'closed', true);
            }
```

**Comment by rob1256** [comment] 2016-10-04 16:21
Getting the same issue here but also when using a custom image uploader/chooser in a widget.  The above fix of changing the parameter to `true` works for me but currently I'm just patching the core in my version

**Comment by rob1256** [comment] 2016-10-24 09:21
It also looks like this issue was fixed 4 months ago but it's not been released yet:
https://github.com/magento/magento2/commit/04a020a2e1db9f38378473733d65925b18dbdd15

**Comment by Ctucker9233** [comment] 2016-12-02 23:17
@vkorotun Will the fix for this issue be included in 2.1.3?

**Comment by pablocattaneo** [comment] 2017-01-24 18:27
Same issue here, please could you fix it.

**Comment by homer14b** [comment] 2017-05-21 17:04
I can report this issue is still present in CE 2.1.4

**Comment by magento-engcom-team** [comment] 2017-10-19 12:30
@Valentyn-Kubrak, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-19 12:30 UTC
Labels: bug report, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid
