### ISSUE TITLE
problem with magento2 upgrade

### ISSUE THREAD

**Issue by kgvconsulting** [magento/magento2#4747] opened 2016-05-27 14:07 UTC
@mazhalai 
 Im sorry but I have the same issue I don't think the upgrade went trough, the bottom right of the admin show v 2.0.2

and yes in the web system update is showing what versions are available but the lowest one in the bottom v 2.02 state - (CURRENT)

![screenshot 2016-05-27 09 54 13](https://cloud.githubusercontent.com/assets/11282348/15610085/773adca6-23f1-11e6-8d00-a738db7d95d6.png)

And also for whatever reason I no longer am able to perform back up from Admin the screenshot above show all back ups no longer are displayed nor when I try to make back up is responding I press on the OK button but there is no reaction at all see the following screenshot

![screenshot 2016-05-27 10 00 47](https://cloud.githubusercontent.com/assets/11282348/15610185/f42aae94-23f1-11e6-9482-b464e619c1a0.png)

root/composer.json file content

```
"name": "magento/project-community-edition",
"description": "eCommerce Platform for Growth (Community Edition)",
"type": "project",
"version": "2.0.2",
"license": [
    "OSL-3.0",
    "AFL-3.0"
],
"repositories": [
    {
        "type": "composer",
        "url": "https://repo.magento.com/"
    }
],
"require": {
    "magento/product-community-edition": "2.0.5",
    "composer/composer": "@alpha"
},
```

**Comment by mazhalai** [comment] 2016-05-27 14:30
@kgvconsulting to clarify you went to admin->config->Web setup wizard->System upgrade clicked on 2.0.5 and upgrade went through without errors, but your version is not updated? I think were was a bug for version not showing up correctly, let me check if that was fixed in any 2.0.x versions. 

Right now, it looks like upgrade did go through, since composer.json has the correct version.
You can clarify by checking if [these issues](http://devdocs.magento.com/guides/v2.0/release-notes/ReleaseNotes2.0.5CE.html) are fixed in your latest instance.

Re backup, we have created ticket MAGETWO-53543 to investigate and fix.

**Comment by kgvconsulting** [comment] 2016-05-27 14:36
@mazhalai 

NO that is incorrect, I started to upgrade from v.2.0.2 to v. 2.0.3 the previous issue #4260, trough WebSetup Wizard and never went trough it stay like for over 12 hours showing that upgrading but notting upgraded at all, Than I did manual with SSH and tried the same for v. 2.0.4 and v 2.0.5 manual upgrade with SSH, unfortunately it never changed in the right bottom corner on admin site, continue to show v 2.0.2 and after the manual upgrade attempt for v 2.0.5 the admin web site back up stop working

admin->config->Web setup wizard->System upgrade  Never worked with me, don't know why, pass all checks and then stay upgrading for I waited up to 12 hours, notting, no upgrade at all

**Comment by mazhalai** [comment] 2016-05-27 14:44
@kgvconsulting, the issue is that version is incorrectly displayed in admin even though upgrade has worked. (in your case manual upgrade) This has been fixed, but not ported to  2.0.x yet.

Re Web Setup System Upgrade, we have added extensive logging in 2.1.0-rc1 so it should be easier going ahead. Also, did you happen to save any files from var after failed upgrade? It will help us diagnose the problem better.

**Comment by kgvconsulting** [comment] 2016-05-27 14:47
@mazhalai I did not have them any longer usualy after cleaning var/ I hold in temp folder for 72 hours, I need to do 2.06 and up to 2.1.0 v upgrade now so I can safe var folder before each upgrade if that would help?

**Comment by kgvconsulting** [comment] 2016-05-27 14:55
@mazhalai Please could you confirm if the following is the correct command lines for SSH upgrade? Just want to be sure that I'm doing it correctly. Thank you

---

First performing manual backup (because the web admin site no longer work), Than:

In composer.json changing this line

"magento/product-community-edition": "2.x.x",
I'm changing the line 5 as well "version": "2.x.x", to keep it in sync.

to whatever version i'm upgrading, and then run:

composer update
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy

Than I'm running the following:

composer require magento/product-community-edition 2.x.x --no-update
composer update
rm -rf var/di var/generation
php bin/magento cache:clean
php bin/magento cache:flush
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento indexer:reindex

**Comment by mazhalai** [comment] 2016-05-27 15:01
Yes it would be useful to see contents of var if upgrade fails via Web. Also, just confirming that you have the required crons setup.

`composer require magento/product-community-edition 2.x.x --no-update` and `composer update` is redundant since you already modified composer.json. Also, not sure why you need `php bin/magento setup:upgrade` after cache:flush. Everything else looks good.

**Comment by kgvconsulting** [comment] 2016-05-27 15:07
OK here is the just created log in var/log/system.log about the failure of admin site web back up

[2016-05-27 13:53:52] main.CRITICAL: Notice: Undefined offset: 1 in /home/flowersv/public_html/vendor/magento/module-backup/Helper/Data.php on line 273 [] []

Could you advise? Thank you

**Comment by mazhalai** [comment] 2016-05-27 15:13
@kgvconsulting Do you have any backed-up files under `var/backups/` ?

**Comment by kgvconsulting** [comment] 2016-05-27 15:14
Yes a lot :)

![screenshot 2016-05-27 11 13 58](https://cloud.githubusercontent.com/assets/11282348/15612290/233998d0-23fc-11e6-9bdb-96b532f4222b.png)

The last 2 on May 1st I did manually the web back up refuse to work

this from SSH image

~/public_html/var/backups]# ls -alh
total 3.1G
drwxr-xr-x  2 flowersv flowersv 4.0K May  1 13:52 ./
drwxr-xr-x 11 flowersv flowersv 4.0K May 27 11:17 ../
-rw-rw----  1 flowersv flowersv 208M Apr 21 10:06 1461247458_snapshot_April21System.tgz
-rw-rw-rw-  1 flowersv flowersv 7.3M Apr 22 13:49 1461347261_db.gz
-rw-rw----  1 flowersv flowersv 142M Apr 22 13:48 1461347261_filesystem_code.tgz
-rw-rw----  1 flowersv flowersv  51M Apr 22 13:48 1461347261_filesystem_media.tgz
-rw-rw-rw-  1 flowersv flowersv 7.9M May  1 09:31 1462109407_db.gz
-rw-rw----  1 flowersv flowersv 142M May  1 09:31 1462109407_filesystem_code.tgz
-rw-rw----  1 flowersv flowersv  51M May  1 09:31 1462109407_filesystem_media.tgz
-rw-r--r--  1 flowersv flowersv 879M May  1 09:20 backup-2016-04-30-10-12.tar.gz
-rw-r--r--  1 flowersv flowersv 1.7G May  1 13:19 backup-2016-05-01-01-19.tar.gz

**Comment by mazhalai** [comment] 2016-05-27 15:24
@kgvconsulting move  backup-2016-04-30-10-12.tar.gz and backup-2016-05-01-01-19.tar.gz to another folder outside of magneto code base, it looks like it wasn't created by Magento, hence not in the correct filename format, and hence throwing errors.

**Comment by kgvconsulting** [comment] 2016-05-27 15:30
I did move them however the back up dont work, now is showing in system.log this error

[2016-05-27 15:27:32] main.CRITICAL: Item (Magento\Framework\DataObject) with the same id "1462109407_db" already exist [] []
[2016-05-27 15:29:23] main.CRITICAL: Item (Magento\Framework\DataObject) with the same id "1462109407_db" already exist [] []

**Comment by mazhalai** [comment] 2016-05-27 16:55
@kgvconsulting that does look strange. Will investigate in scope of  MAGETWO-53543

**Comment by kgvconsulting** [comment] 2016-05-27 16:57
ok thank you will wait for your feedback

**Comment by kgvconsulting** [comment] 2016-05-27 19:12
@mazhalai 

when try to do:

composer update in root of magento install I'm getting this error, could you help, please

flowersv@flowersvibe.com [~/public_html]# composer update
bash: composer: command not found
flowersv@flowersvibe.com [~/public_html]# php composer update
Could not open input file: composer
flowersv@flowersvibe.com [~/public_html]#

**Comment by mazhalai** [comment] 2016-05-27 19:26
@kgvconsulting you do not have composer installed. `curl -sS https://getcomposer.org/installer | php`
and then `mv composer.phar /usr/local/bin/composer` or to where ever your bin folder is.

**Comment by kgvconsulting** [comment] 2016-05-27 19:31
Ok I need to move it after installation to server-root level /usr/local/bin/composer with root credentials or to magento-root folder with web user credentials?

**Comment by mazhalai** [comment] 2016-05-27 19:36
server root with root credentials.

**Comment by kgvconsulting** [comment] 2016-05-27 20:12
Ok Thanks so far all is good, however i got to issue when downloading from magento github repository, for whatever reason my github credentials dont work

flowersv@flowersvibe.com [~/public_html]# composer update
Loading composer repositories with package information
    Authentication required (repo.magento.com):
      Username: xxxxxxxxxxxxxxx
      Password:

  [Composer\Downloader\TransportException]
  Invalid credentials for 'https://repo.magento.com/packages.json', aborting.

Ignore this I found it need to use my magento keys for login and pasword

**Comment by kgvconsulting** [comment] 2016-05-27 20:31
@mazhalai Success after this update the magento admin started to show correct version:

![screenshot 2016-05-27 16 30 52](https://cloud.githubusercontent.com/assets/11282348/15620489/7abd965c-2428-11e6-915e-13a75fbad779.png)

**Comment by kgvconsulting** [comment] 2016-05-27 20:34
@mazhalai unfortunately the backup didn't fix it continue not to display the existing back up files and cant do new back up also the system.log have the same error:

[2016-05-27 20:32:00] main.CRITICAL: Item (Magento\Framework\DataObject) with the same id "1462109407_db" already exist [] []

**Comment by kgvconsulting** [comment] 2016-05-27 20:36
@mazhalai  the web system upgrade now show the correct current version too

![screenshot 2016-05-27 16 35 10](https://cloud.githubusercontent.com/assets/11282348/15620593/1fa3c2b8-2429-11e6-84ad-73b21626188e.png)

**Comment by kgvconsulting** [comment] 2016-05-27 20:42
@mazhalai 

Just one question when I'm upgrading from v 2.0.7 to v 2.1.0-rc 1 I need to change the line in composer.json file

"magento/product-community-edition": "2.1.0",

or 

"magento/product-community-edition": "2.1.0-rc 1",

Thank you

**Comment by kgvconsulting** [comment] 2016-05-28 03:41
@mazhalai 

OK I found the correct version and updated to v. 2.1.0-cr1

the admin site show the correct version in the bottom right

![screenshot 2016-05-27 23 24 36](https://cloud.githubusercontent.com/assets/11282348/15624873/0ca08a90-2463-11e6-9869-e540bf94b015.png)

However there is a issue with web wizard when access it ask for magento keys (public and private) and even after I enter them the page don't change and show this error:

![screenshot 2016-05-27 23 28 16](https://cloud.githubusercontent.com/assets/11282348/15624962/2bb33016-2465-11e6-9ae7-8e9019464ae3.png)

Could you please advise about that?

Also I try again to perform a back up from admin site:

unfortunately the same error reported in the system.log

[2016-05-28 03:25:36] main.CRITICAL: Item (Magento\Framework\DataObject) with the same ID "1462109407_db" already exists. [] []
[2016-05-28 03:28:35] main.CRITICAL: Item (Magento\Framework\DataObject) with the same ID "1462109407_db" already exists. [] []
[2016-05-28 03:32:55] main.CRITICAL: Item (Magento\Framework\DataObject) with the same ID "1462109407_db" already exists. [] []

So I will remain for your feedback. Thank you again for your help.

**Comment by ghost** [comment] 2016-05-28 15:08
FWIW, just as another point of view, I successfully upgraded from CE 2.0.2 with sample data to CE 2.0.7, creating backups along the way. I verified the system worked in both versions by placing an order on the storefront. The issue I found was that, after upgrade, I had to reapply permissions. I got the "We're sorry, an error has occurred while generating this email." on the storefront, which is due to incorrect permissions in some directories.

This is a plain installation though; I changed no config settings and created no custom code. This is just for comparison. Maybe it will help isolate the issues you're having or rule something out.

**Comment by kgvconsulting** [comment] 2016-05-28 15:34
@xcomSteveJohnson - Thanks, but with me is not the case, I don't have issues with permissions, those may arise if during installation and upgrade you mix root and web user owner during those processes, to avoid that before do upgrade or any type install you should log out root and log in and work only as web user on magento2, than you would never get permissions issues.

Our issue with back up is related to error in the magento php files or some similar bug that may got in the process of setting it up.

**Comment by mazhalai** [comment] 2016-05-31 13:36
@kgvconsulting keys are 32 characters long, not login to marketplace(though there is a plan to change it in the future to use login). Keys can be found after login to magento.com-> marketplace->my access keys

**Comment by kgvconsulting** [comment] 2016-05-31 14:12
@mazhalai - Yes correct and I have the right one, Im sorry if I dont state the issue correctly, here is the problem, see enclosed screenshots

I'm able to access Web Setup Wizard, all sections are working correctly EXCEPT the section for Web Setup Upgrade where should show the correct version and if there is new one available.

The magento 32 characters keys are installed from the very begining I even reset them so this is most likely some bug then the issue with the key

![screenshot 2016-05-31 10 05 45](https://cloud.githubusercontent.com/assets/11282348/15677320/c5e0f1e6-2717-11e6-8970-b6843e12caeb.png)
![screenshot 2016-05-31 10 06 09](https://cloud.githubusercontent.com/assets/11282348/15677324/c9fc3556-2717-11e6-8c23-9a126f51e436.png)
![screenshot 2016-05-31 10 06 22](https://cloud.githubusercontent.com/assets/11282348/15677395/1feed2d4-2718-11e6-9407-0e6d6fc02978.png)
![screenshot 2016-05-31 10 06 38](https://cloud.githubusercontent.com/assets/11282348/15677345/ea8d52c8-2717-11e6-95e6-fe9bbb47540b.png)

Even if I enter the key's again in the requested login page noting happen, after pressing submit button noting change noting move is just staying like that

**Comment by mazhalai** [comment] 2016-05-31 14:26
@kgvconsulting in your composer.json is repo.magento.com the only repository specified?

**Comment by kgvconsulting** [comment] 2016-05-31 14:30
@mazhalai 

Yes, correct

{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.0.2",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "require": {
        "magento/product-community-edition": "2.1.0-rc1",
        "composer/composer": "@alpha"

**Comment by kgvconsulting** [comment] 2016-05-31 16:58
@mazhalai - Also if that could help I didn't had this issue when did the upgrade to v2.0.6 and v 2.0.7; It happen after i upgraded to v 2.1.0-rc1

**Comment by kgvconsulting** [comment] 2016-05-31 18:22
@mazhalai 

I just try and was unable to access also Sales, Customers, Products, Marketing, Content

it is showing that load but does not go anywere

![screenshot 2016-05-31 14 17 50](https://cloud.githubusercontent.com/assets/11282348/15685716/f700a780-273a-11e6-8cec-8f7c722db71f.png)

and when try to get invoices get this message

![screenshot 2016-05-31 14 18 12](https://cloud.githubusercontent.com/assets/11282348/15685732/07e7d2d0-273b-11e6-9b5e-f021650ede1d.png)

Is there an issue with v 2.1.0-rc1?

**Comment by kgvconsulting** [comment] 2016-05-31 18:29
@mazhalai 

can I delete the content of var/ and dl/ folders except .htaccess file? Does that could fix this issue?

**Comment by mazhalai** [comment] 2016-05-31 18:41
if you clean `var/` you will need to enter keys again, since they are stored in `var/composer_home`. Try cleaning just `var/generation` and `var/di`(if you are dev or default mode, in prod mode you will have to run compile again)

**Comment by kgvconsulting** [comment] 2016-05-31 18:46
@mazhalai No I misspoke I did want ed to clean var/generation and var/dl only

**Comment by mazhalai** [comment] 2016-05-31 18:47
@kgvconsulting yes it might, also clean cache. This thread has diverged significantly from original issue. If problems still persist, please open a new issue for `unable to access also Sales, Customers, Products, Marketing, Content`

**Comment by kgvconsulting** [comment] 2016-05-31 18:48
@mazhalai any advise in this case, so far there is some issue because some of the admin menu dont work correctly some work, I cant get any access to catalog or categories under Product menu either. it is the same infinite loading of someting and does not go anywhere

**Comment by kgvconsulting** [comment] 2016-05-31 18:50
@mazhalai OK to make last attempt to flush the cache as Magento Cache or also:

Flush Catalog Images Cache - Pregenerated product images files

Flush JavaScript/CSS Cache  - Themes JavaScript and CSS files combined to one file

Flush Static Files Cache  - Preprocessed view files and static files

**Comment by kgvconsulting** [comment] 2016-05-31 19:04
@mazhalai please could you advice what mode the magento should be I got confused here, from what I originally installed as v2.0.2 and now

currently is showing

 php magento deploy:mode:show
Current application mode: default. (Note: Environment variables may override this value.)

**Comment by kgvconsulting** [comment] 2016-05-31 19:20
@mazhalai I did clean the cache don't help so I open new ticket so now i got upgraded to latest version unfortunately the application cant work correctly, what to do? Please advise, thank you

**Comment by kgvconsulting** [comment] 2016-05-31 19:36
@mazhalai if I want to downgrade to previous version because under current situation I cant do rollback, what should be the correct procedure? To delete the magento root folder and replace it with the back up made before the upgrade?

**Comment by kgvconsulting** [comment] 2016-05-31 19:44
@mazhalai also as you see on the screenshot when try to access invoices i'm geting this error that is also present in system.log

main.CRITICAL: Notice: Undefined index: base_grand_total in /xxxx/xxxx/public_html/vendor/magento/module-sales/Ui/Component/Listing/Column/Price.php on line 55 [] []

**Comment by mazhalai** [comment] 2016-05-31 19:59
re restoring, you need to restore code as well as database.
No idea about Sales module error, please open a new ticket for that.

**Comment by kgvconsulting** [comment] 2016-05-31 20:10
@mazhalai OK the code is the Magento root folder so I can replace it from back up one, and the DB is on separate server so I can get back to point of time before the last upgrade, becasue there is hourly back up on the database content there, is that sound good?

**Comment by mazhalai** [comment] 2016-05-31 20:15
Yes http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-backup.html

**Comment by kgvconsulting** [comment] 2016-06-01 00:54
@mazhalai 
So to have conclusion the issue was generated because of somehow different mysql table created by the upgrade of v 2.1.0-rc1 on admin side, so was the same issue with the system backup case, now I'm  reinstating on server level the mysql db for the time before the upgrade of v2.1.0-rc1 when all worked fine, unfortunately magento in the current state can't roll back from back up file, becasue the v2.1.0-rc1 are changing something inside the mysql tables that don't match with the previously created tables and files under v2.0.x

[~/public_html]# php bin/magento setup:rollback -m 1462109407_db.gz
Enabling maintenance mode
You are about to remove current code and/or database tables. Are you sure?[y/N]y
**_Invalid rollback file._**
Disabling maintenance mode
 [~/public_html]# exit

However the backup files made under v2.0.x are labeled by v 2.1.0-rc1 as invalid and that was the reason why I couldn't create the backup under admin side, when I moved all backup files from the /var/backups/ folder than the admin side backup started to work.

So when reinstate the server image for both servers: db server and code server so they match the same time and state prior to the upgrade and test it will update you again. 

Thank you

**Comment by kgvconsulting** [comment] 2016-06-01 18:48
@mazhalai 

Well I can confirm that v2.1.0-rc1 do change the DB tables and make a lot of bug issues on admin side after upgrade, so I doubt will want to use it soon.

Also the issue with the backup performed from admin web site, Turn to be that the newly upgraded version does not recognize the old version back up files and report error. so you simply move all content (backup files) from /var/backups/ to some other (work/tmp) folder and all start to work again, magento web admin side start to do backups again.

Now I go back to v2.0.6 and intent to stay there so far is stable and don't create (waist) of time for me.

Thank you again for your help in the endeavor. 👍

**Closed as completed** 2016-06-01 20:07 UTC
Labels: Issue: Ready for Work
