### ISSUE TITLE
Magento 2.3.0: Backup tool not correctly detecting .maintenance.flag

### ISSUE THREAD

**Issue by nexrobr** [magento/magento2#19825] opened 2018-12-15 18:47 UTC
### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.1, 7.2
3. Apache/2.2.34
4. CentOS release 6.10 (Final)

### Steps to reproduce (*)

1. Dashboard -> System -> Tools -> Backups -> Database Backup
2. Enter backup name, check "Maintenance mode", click OK.

### Expected result (*)

1. var/.maintenance.flag is created.
2. Backup proceeds.

### Actual result (*)

1. var/.maintenance.flag is created.
2. Error: You need more permissions to activate maintenance mode right now. To create the backup, please deselect "Put store into maintenance mode" or update your permissions.

### Details
Magento is correctly creating var/.maintenance.flag, but appears not to be recognizing a successful return status.

The user has full administrator rights. Also tested with creating a new role, and granting either "all" rights or using "custom" and individually granting all rights.

The function triggering the error is in:
vendor/magento/module-backup/Controller/Adminhtml/Index/Create.php

`57             if ($this->getRequest()->getParam('maintenance_mode'))`
`58                 if (!$this->maintenanceMode->set(true)) {`
`59                     $response->setError(`
`60                         __(`
`61                             'You need more permissions to activate maintenance mode right now.'`
`62                         ) . ' ' . __(`
`63                             'To create the backup, please deselect '`
`64                             . '"Put store into maintenance mode" or update your permissions.'`
`65                         )`
`66                     );`

maintenanceMode->set() is defined here -- applicable code extracted:
vendor/magento/framework/App/MaintenanceMode.php

`8 use Magento\Framework\App\Filesystem\DirectoryList;`
`22     const FLAG_FILENAME = '.maintenance.flag';`
`32     const FLAG_DIR = DirectoryList::VAR_DIR;`
`46     public function __construct(Filesystem $filesystem)`
`47     {`
`48         $this->flagDir = $filesystem->getDirectoryWrite(self::FLAG_DIR);`
`49     }`

`74     public function set($isOn)`
`75     {`
`76         if ($isOn) {`
`77             return $this->flagDir->touch(self::FLAG_FILENAME);`
`78         }`

VAR_DIR is correctly defined as "var" here:
vendor/magento/framework/App/Filesystem/DirectoryList.php

`     58     const VAR_DIR = 'var';`

The var folder has correct permissions:

`$ stat var | grep Access`
`Access: (0711/drwx--x--x)  Uid: ( 1000/user)   Gid: ( 1000/user)`

**Comment by magento-engcom-team** [comment] 2018-12-15 18:47
Hi @nexrobr. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nexrobr do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by nexrobr** [comment] 2018-12-15 18:53
Yes, I can reproduce with a fresh 2.3.0 install.

**Comment by magento-engcom-team** [comment] 2018-12-16 01:36
Hi @milindsingh. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by milindsingh** [comment] 2018-12-16 13:52
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2018-12-16 13:52
Hi @milindsingh. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2018-12-16 13:52
Hi @milindsingh, here is your [Magento instance](https://i-19825-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19825-2-3-develop.instances.magento-community.engineering/admin](https://i-19825-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2018-12-18 08:33
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2018-12-18 08:34
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97204` were created

**Comment by magento-engcom-team** [comment] 2018-12-22 06:36
Hi @hiren0241. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by hiren0241** [comment] 2018-12-22 06:37
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2018-12-22 06:37
Hi @hiren0241. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2018-12-22 06:37
Hi @hiren0241, here is your [Magento instance](https://i-19825-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19825-2-3-develop.instances.magento-community.engineering/admin](https://i-19825-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by hiren0241** [comment] 2018-12-22 06:43
Hi @magento-engcom-team Please allow access of backup in admin.
As of now, I am getting this notification : Backup functionality is disabled
Backup functionality is currently disabled. Please use other means for backups.

Will you please fire this command on console:php bin/magento config:set system/backup/functionality_enabled 1. 

So, that I can test further.

Thanks.

**Comment by hiren0241** [comment] 2018-12-22 06:55
HI @magento-engcom-team ,

I am to reproduce this on my local instance. I am working upon it.

**Comment by mbuc** [comment] 2019-03-20 21:31
Just want to add that I am having the exact same issue as the original post.  I am running Magento 2.3.0 using PHP 7.2 on Nginx 1.14.0 on Ubuntu 18.04 LTS.  User has administrative privileges, filesystem privileges are set properly, and I have not run into permissions issues elsewhere.

**Comment by mbuc** [comment] 2019-03-20 21:35
Additionally, I cannot perform a backup while the maintenance mode flag is set.  It causes the backend to enter maintenance mode as well.  Is this the intended result?

**Comment by magento-engcom-team** [comment] 2019-04-23 12:25
Hi @nexrobr. Thank you for your report. 
The issue has been fixed in magento/magento2#19993 by @hiren0241 in 2.3-develop branch
Related commit(s):
 - [fd92027ac2c34c47ff1f09dafbd1c01b549adc47](https://github.com/magento/magento2/commit/fd92027ac2c34c47ff1f09dafbd1c01b549adc47)
 - [6374f9ddd3c51aa1e4cc96b5e2339c236028c665](https://github.com/magento/magento2/commit/6374f9ddd3c51aa1e4cc96b5e2339c236028c665)
 - [658b5a7beb1f0a05be5a949c5d75edac0da9621b](https://github.com/magento/magento2/commit/658b5a7beb1f0a05be5a949c5d75edac0da9621b)
 - [5bc05b22c10927b9ec1f3c12daba8c09e35940b7](https://github.com/magento/magento2/commit/5bc05b22c10927b9ec1f3c12daba8c09e35940b7)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-04-23 12:25 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Backup
