### ISSUE TITLE
Controller extending AccountInterface breaks in Production mode

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#35211] opened 2022-03-21 16:16 UTC
### Preconditions (*)

1. Magento 2.4.2  / 2.4.3-p1

### Steps to reproduce (*)

1. Create a new module, route and controller which implements `AccountInterface` , as customer modules do 
2. Implement the controller like this:
```
class Someaction implements AccountInterface, HttpGetActionInterface
```
3. Enable production mode

### Expected result (*)

1. User is redirected to the customer login page

### Actual result (*)

1. Here is the error when you try to access the frontend route
```
{"0":"Invalid return type","1":"#1 Magento\\Framework\\App\\Bootstrap->run() called at 
[crypto\/pub\/index.php:42]\n","url":"\/mycontroller\/someaction\/","script_name":"\/index.php",
"report_id":"64317f2f4266fb92d176ead06a60faf2c27ba54790374689a1d4954d1d7cc5ed"}
```

### Solution
1. You need your controller to extend `DEPRECATED` `\Magento\Framework\App\Action\Action` class

### Important
1. This works in developer mode!

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2022-03-23 09:41
Hello @qsolutions-pl,

Thanks for posting this issue!

We have tried to reproduce the issue in Magento 2.4-develop branch and the issue is reproducible for us. Please find the below screencast for reference:

**In Development Mode**

https://user-images.githubusercontent.com/51681618/159668458-1c94f893-ab75-43c6-81b6-b1ab5748d167.mov

**In Production Mode**

https://user-images.githubusercontent.com/51681618/159668563-3e73c626-d3e2-48fd-ab35-85f9411df40f.mov

We are getting the below error in production mode:
```
[2022-03-23T09:30:47.918701+00:00] main.ERROR: Invalid return type [] []
[2022-03-23T09:30:47.918999+00:00] main.CRITICAL: InvalidArgumentException: Invalid return type in /lib/internal/Magento/Framework/App/Http.php:124
Stack trace:
#0 /lib/internal/Magento/Framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#1 /pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#2 {main} {"report_id":"7c8133a8e873ce3d24a05e0426b1922e38be5abc4bcc30dfe05081268726dab7"} []
```
**Current Deploy mode**
<img width="838" alt="image" src="https://user-images.githubusercontent.com/51681618/159669269-48c30b66-4276-416f-a914-c03072a76f47.png">

But extending the `Action` class resolves the problem which is marked as deprecated. 

The issue is doesn't occur in development mode without extending the `Action` class.

Hence confirming the issue.

Thanks

**Comment by vlmed** [comment] 2022-05-17 09:06
@magento I am working on this

**Comment by engcom-Hotel** [comment] 2022-05-17 10:42
Hi @qsolutions-pl,

As per discussion with the development team, we have investigated more on this and found the below solutions for this issue:

To make `AccountInterface` available to a controller path, it needs to be given under the allowed actions as well.

Eg: `Customer/Controller/Account/Confirm.php` controller is also passed under `Customer/etc/frontend/di.xml`

```
<type name="Magento\Customer\Controller\Plugin\Account">
    <arguments>
        <argument name="allowedActions" xsi:type="array">
            <item name="create" xsi:type="string">create</item>
            <item name="login" xsi:type="string">login</item>
            <item name="logoutsuccess" xsi:type="string">logoutsuccess</item>
            <item name="forgotpassword" xsi:type="string">forgotpassword</item>
            <item name="forgotpasswordpost" xsi:type="string">forgotpasswordpost</item>
            <item name="resetpassword" xsi:type="string">resetpassword</item>
            <item name="resetpasswordpost" xsi:type="string">resetpasswordpost</item>
            <item name="confirm" xsi:type="string">confirm</item>
            <item name="confirmation" xsi:type="string">confirmation</item>
            <item name="createpassword" xsi:type="string">createpassword</item>
            <item name="createpost" xsi:type="string">createpost</item>
            <item name="loginpost" xsi:type="string">loginpost</item>
        </argument>
    </arguments>
</type>
```
In this case:  we need to include our custom controller path into the allowed actions as well.

Let us know in case of any query.

Thanks

**Comment by engcom-Hotel** [comment] 2022-06-01 07:27
Dear @qsolutions-pl,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-06-01 07:27 UTC
Labels: Issue: Confirmed, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P2, Progress: done, Issue: needs update, Area: Framework
