### ISSUE TITLE
Not able to change a position of last two related products in case of I've 20+ related products.

### ISSUE THREAD

**Issue by patelnimesh1988** [magento/magento2#14071] opened 2018-03-13 06:22 UTC
Hello,

Not able to change a position of last two related products in case of I've 20+ related products.

### Preconditions
1. Magento 2.2.2
2. PHP 7.0.10
3. Apache 2.4.23 (Window 10)

### Steps to reproduce
1. Login to admin and edit product.
2. Add 60 products as related products and save the product.
3. Again add 2 more products in related products.
4. Try to change recently added 2 products position to 5 and 6 using drag and drop functionality.

### Expected result
1. Recently added 2 products should display at number 5 and 6 position.

### Actual result

1. Related 60 Products: https://www.screencast.com/t/LF6YaCZOcJs
2. Admin Related products: https://www.screencast.com/t/lUShfC2vqCE
3. Newly added related products: 
    Admin: https://www.screencast.com/t/iGB5o0UsQlkb
    Front-end: https://www.screencast.com/t/50W0N9JzQyJI
4. Actual result: https://www.screencast.com/t/BNszzWxr9Hx

I face the same issue for move first-page product on the third page. Drag and drop functionality allows only change a position of current page products only. We can't move first page products on a second or third page.

**Comment by magento-engcom-team** [comment] 2018-03-13 11:58
@patelnimesh1988, thank you for your report.
We've acknowledged the issue and added to our backlog. Also please be aware that Windows is not a supported operating system for Magento 2, so You may encounter other issues that do not appear on the supported operating system.

**Comment by KalaiarasanSeetharaman** [comment] 2018-05-19 04:44
I am working on it #dmcdindia

**Comment by magento-engcom-team** [comment] 2018-05-19 04:44
@KalaiarasanSeetharaman thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by patelnimesh1988** [comment] 2018-05-19 05:04
I am working on this at #dmcdindia

**Comment by vseager** [comment] 2018-11-13 11:02
This is still an issue on 2.2.5, using Centos OS.

### Preconditions
1. Magento 2.2.5
2. Centos 7

### Steps to reproduce
1. Create a product
2. Add more than 20 items to one of the product grids (Related product, bundle items etc)
3. Attempt to reorder products using drag and drop feature, moving an item from page 1 to page 2 of the product grid.

### Expected result
It is expected that the above process is possible.

### Actual result
You can only reorder items on the page that is currently selected. If you wish to reorder products between pages you have to do so directly in the database.

![bundle_item_grid_1](https://user-images.githubusercontent.com/2035088/48408937-78733f80-e732-11e8-83a0-aaf52a9dccd2.png)
![bundle_item_grid_2](https://user-images.githubusercontent.com/2035088/48408947-7c06c680-e732-11e8-9a7d-531278445b8e.png)

### Suggestion
Adding the option to show more products per page may help work around this.

**Comment by magento-engcom-team** [comment] 2018-11-15 08:33
Hi @lisovyievhenii. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-03-12 11:14
Hi @m-a-x-i-m. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by patelnimesh1988** [comment] 2019-05-04 07:43
I am working on this at #dmcdindia19

**Comment by sdzhepa** [comment] 2020-06-02 16:33
Issue has been fixed in https://github.com/magento/magento2/pull/22984

**Closed as completed by sdzhepa** 2020-06-02 16:33 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Event: dmcdindia1
