### ISSUE TITLE
Magento ver. 2.4.6 Braintree Payment Methods Missing

### ISSUE THREAD

**Issue by uakc** [magento/magento2#37661] opened 2023-06-23 18:00 UTC
### Preconditions and environment

Magento ver. 2.4.6
Braintree payment method is missing under PayPal Express Checkout. 

### Steps to reproduce

install Magento ver. 2.4.6

### Expected result

Braintree payment method 

### Actual result

Braintree payment method not listed 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-06-26 10:05
Hi @uakc,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4.6 instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- install Magento ver. 2.4.6


We are able to see the Braintree payment method under paypal express checkout.

![Configuration-Settings-Stores-Magento-Admin (9)](https://github.com/magento/magento2/assets/51680745/c289ec65-fbfa-4b97-aed1-c2137f8ea2a3)



Thanks.

**Comment by engcom-Bravo** [comment] 2023-07-07 05:16
Hi @uakc,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-07-07 05:16 UTC
Labels: Issue: needs update, Reported on 2.4.6
