### ISSUE TITLE
\Magento\MediaStorage\Model\File\Storage\Synchronization::synchronize() suppresses its exceptions for a questionably reason

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2566] opened 2015-11-30 23:54 UTC
https://mage2.pro/t/271

See also: https://github.com/magento/magento2/issues/2558

**Comment by oserediuk** [comment] 2016-06-22 15:52
Hello! To allow us research the issue, please, provide description according to the template.
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment] 2016-07-14 08:11
Hi, @mage2pro thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.

**Closed as completed by vzabaznov** 2016-07-14 08:11 UTC
Labels: Progress: needs update
