### ISSUE TITLE
Cart/Catlog Price Rules do not work for Downloadble Product Files

### ISSUE THREAD

**Issue by nickpiro** [magento/magento2#21086] opened 2019-02-08 20:13 UTC
### Preconditions (*)

1. Magento 2.2.5

### Steps to reproduce (*)

1. Create Downloadable Product
2. Add all basic product information
3. Price: $0.00
3. In Downloadable Information Add Link
4. Select 'Link Can Be Purchased Separately'
5. Add 'Title', 'Price: $25', 'File'
6. Save.

7. View product on website. Price shows $0, and list of downloads, one product +$25

8. Add Catalog Price Rule
9. For Wholesale customer group, If in this category (Category where download product is saved), 100% discount of price.

### Expected result (*)
1. -$25 price on frontend

### Actual result (*)
1. Price is not discounted.

This is the same for both cart and price rules!

**Comment by magento-engcom-team** [comment] 2019-02-08 20:13
Hi @nickpiro. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nickpiro do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by nickpiro** [comment] 2019-02-08 20:17
@magento-engcom-team give me 2.2.5-instance

**Comment by magento-engcom-team** [comment] 2019-02-08 20:36
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by nickpiro** [comment] 2019-02-08 23:22
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-08 23:22
Hi @nickpiro. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-08 23:22
Hi @nickpiro, here is your [Magento instance](https://i-21086-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21086-2-2-develop.instances.magento-community.engineering/admin](https://i-21086-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by nickpiro** [comment] 2019-02-08 23:29
@magento-engcom-team how long do reindexes take?

**Comment by nickpiro** [comment] 2019-02-08 23:46
ssue: Confirmed

**Comment by nickpiro** [comment] 2019-02-08 23:47
Issue: Confirmed

**Comment by nickpiro** [comment] 2019-02-08 23:47
* Issue: Confirmed

**Comment by nickpiro** [comment] 2019-02-08 23:49
* Issue: Clear Description

**Comment by nickpiro** [comment] 2019-02-08 23:54
@magento-engcom-team I was able to confirm the issue is also on the vanilla instance. 

I was able to get the Cart Price Rule to work, only by adding Product Subselection of Categories within Conditions. 

This way, the price is only discounted via the Shopping cart and does not display in the catalog. 

on M1 you would be able to see the discount via the Catalog Price Rule on the Product page.

**Comment by shikhamis11** [comment] 2019-02-09 13:23
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-09 13:23
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-09 13:23
Hi @shikhamis11, here is your [Magento instance](https://i-21086-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21086-2-3-develop.instances.magento-community.engineering/admin](https://i-21086-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2019-02-09 13:24
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-09 13:24
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-09 13:25
Hi @shikhamis11, here is your [Magento instance](https://i-21086-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21086-2-2-develop.instances.magento-community.engineering/admin](https://i-21086-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2019-02-09 13:38
@nickpiro Price is discounted by catalog price rule too. on current 2.2-develop instance and 2.3-develop instance I checked if the price of the product is greater than zero it will display regular price and final price both . Please check the screenshots 
![screenshot_2019-02-09_19-06-06](https://user-images.githubusercontent.com/25526037/52521485-cc43e500-2c9d-11e9-9e50-de5cc0f10995.png)
 and about the link price will not be included into the catalog price rule because that will be treated as separated entity

**Comment by nickpiro** [comment] 2019-02-09 14:37
@shikhamis11 did you add a link to the product? Because the price would show zero if you set the product main price as zero, and only select price for the linked download. I just tested the exact issue on a vanilla 2.2.5 and it was reproduced. I think you're testing if the product had a price, not if the linked item had a price.

**Comment by nickpiro** [comment] 2019-02-09 14:41
<img width="1438" alt="wrong-dl-product-issue" src="https://user-images.githubusercontent.com/36938969/52522100-d094e180-2c4e-11e9-9791-77b28230d0f3.png">
<img width="1817" alt="wrong-dl-product-issue-2" src="https://user-images.githubusercontent.com/36938969/52522101-d2f73b80-2c4e-11e9-840f-f07d55916dc3.png">
<img width="1528" alt="wrong-dl-product-issue-3" src="https://user-images.githubusercontent.com/36938969/52522105-d7bbef80-2c4e-11e9-9019-5d0a36049bc4.png">
<img width="1391" alt="wrong-dl-product-issue-4" src="https://user-images.githubusercontent.com/36938969/52522108-dbe80d00-2c4e-11e9-8263-977fa8444085.png">

**Comment by nickpiro** [comment] 2019-02-09 14:43
@shikhamis11 see? You shouldn't label this as non-issue or cannot be reproduced. This is still an issue. I logged into the instance of 2.2.5 that you tested. The issue is not the main price of a download, the issue is for the linked downloads attached to the download. For instance, we use this as a configurable/grouped download product, so we always have $0 as the main price, and the child/linked downloads are the actual priced items.

**Comment by nickpiro** [comment] 2019-02-09 14:46
@shikhamis11 this should not be normal behavior of M2. In M1 this was not the behavior. If you put a catalog price rule for a download product, of 100% discount, it would discount linked items. I don't know what your comment about "and about the link price will not be included into the catalog price rule because that will be treated as separated entity" that's the point of this Git Issue I posted. This is being treated separately. There is NO WAY to discount this price other than doing a Cart Price Rule.

**Comment by shikhamis11** [comment] 2019-02-09 14:48
@nickpiro can you please check product d1 . I have also added link and main price of the product is zero. 
Are you saying the link price also should become zero with catalog price rule ?

**Comment by nickpiro** [comment] 2019-02-09 14:51
@shikhamis11 Yes. If you add a catalog rule that items in a specific category are discounted 100%, this should include the linked items. Otherwise, how do you discount those items?

**Comment by shikhamis11** [comment] 2019-02-09 14:54
Ok @nickpiro let me check what should be expected behavior. I will update here

**Comment by nickpiro** [comment] 2019-02-09 14:57
@shikhamis11 thank you!

**Comment by shikhamis11** [comment] 2019-02-11 10:52
@nickpiro I checked even in magento1 process is same that linked products are not discounted with catalog rule so It will be processed faster if you move this to https://github.com/magento/community-features

**Closed as completed by shikhamis11** 2019-02-11 10:52 UTC
Labels: Issue: Clear Description, Issue: Format is valid
