### ISSUE TITLE
Out-of-stock options for configurable products are showing up in search and layered navigation results

### ISSUE THREAD

**Issue by JensBourgeois** [magento/magento2#24470] opened 2019-09-05 15:21 UTC
### Preconditions (*)
1. Magento version: 2.2.9

### Steps to reproduce (*)
1. On a category page, let's say we are filtering on a certain attribute, size 39 for example.

When clicking on 1 of the resulting products, we cannot see size 39 as one of the options because that simple product is out of stock (or disabled)

### Expected result (*)
1. I expect the resulting product to have the size "39" like the filter shows.

### Actual result (*)
1. The configurable product does not have the filtered size of 39.

It looks like out-of-stock options for configurable products are showing up in search and layered navigation results.

When checking the release notes of v.2.3.0, I can see the following line:

"Out-of-stock options for configurable products no longer show up in search and layered navigation results."
https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.html

It looks like this is fixed in v.2.3.0, any chanse this can be backported to 2.2.X cause we don't want to upgrade to v2.3.X as of now.

**Comment by JensBourgeois** [comment] 2019-09-05 15:27
@magento give me 2.2.9 instance

**Comment by magento-engcom-team** [comment] 2019-09-05 15:27
Hi @JensBourgeois. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` release line

**Comment by engcom-Charlie** [comment] 2019-10-02 07:24
Hello @JensBourgeois 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.

We are closing this issue due to branch `2.2-develop` was closed and
> Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.

 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-10-02 07:24 UTC
Labels: Issue: Format is valid
