### ISSUE TITLE
Currently listed colinmollenhour/cache-backend-redis is incompatible with php 8.1

### ISSUE THREAD

**Issue by damienwebdev** [magento/magento2#36033] opened 2022-08-26 02:52 UTC
### Preconditions and environment

**Magento version(s):**

- v2.4.4
- v2.4.4-p1
- v2.4.5

Redis 6.0 w/ Redis Sentinel

### Steps to reproduce

1. Install the impacted Magento 2 versions
2. Configure Redis Sentinel
3. `php pub/health_check.php`
4. Get deprecation error because of `error_reporting(E_ALL)` in `app/bootstrap.php`

### Expected result

No error. Redis Sentinel works for Magento.

### Actual result

`setup:install` succeeds, but a simple test via `php pub/health_check.php` highlights the error:

```bash
PHP Deprecated:  preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated in /var/www/html/vendor/colinmollenhour/cache-backend-redis/Cm/Cache/Backend/Redis.php on line 175
PHP Deprecated:  preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated in /var/www/html/vendor/colinmollenhour/cache-backend-redis/Cm/Cache/Backend/Redis.php on line 175
```

### Additional information

This was an issue in [1.14.2](https://github.com/colinmollenhour/Cm_Cache_Backend_Redis/blob/1.14.2/Cm/Cache/Backend/Redis.php#L175)

It was corrected in [1.14.3](https://github.com/colinmollenhour/Cm_Cache_Backend_Redis/blob/1.14.3/Cm/Cache/Backend/Redis.php#L175)

### Release note

Redis Sentinel implementation is compatible with php v8.1 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-10-03 05:44
Hi @damienwebdev ,
Thank you for reporting and collaboration. This issue is a duplicate of https://github.com/magento/magento2/issues/35634 which has been confirmed. We are closing this issue. Kindly move onto this issue for latest updates / solutions on the same.
Thank you.

**Closed as completed by engcom-November** 2022-10-03 05:44 UTC
Labels: duplicate, Issue: ready for confirmation, Reported on 2.4.5
