### ISSUE TITLE
Broken Tax Rate Search Filter - SQLSTATE[23000]

### ISSUE THREAD

**Issue by robyerevan** [magento/magento2#21521] opened 2019-03-01 02:03 UTC
### Preconditions (*)

1. Magento 2.2.3

### Steps to reproduce (*)

1. Go to Admin -> Stores -> Taxes -> Tax Rules
2. Add a tax rule
3. Search tax rule using both **Name** and **Tax Rate** fields
eg. _Name = Alabama_ & _Tax Rate = US-AL_

### Expected result (*)

1. Combined search executed and output is displayed to admin
2. Admin can continue using tax rate search again

### Actual result (*)

1. MySQL error is thrown

> Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'code' in where clause is ambiguous, query was: SELECT COUNT(DISTINCT main_table.tax_calculation_rule_id) FROM `tax_calculation_rule` AS `main_table`
 LEFT JOIN `tax_calculation` AS `tc` ON main_table.tax_calculation_rule_id = tc.tax_calculation_rule_id
 LEFT JOIN `tax_calculation_rate` AS `rc` ON tc.tax_calculation_rate_id = rc.tax_calculation_rate_id WHERE ((`code` LIKE '%Alabama%')) AND ((`rc`.`code` LIKE '%US-AL%'))

2. In production mode blank area displayed instead of grid, admin can not use tax rate search anymore until session/cookies cleared manually
![tax_rules_page_crush](https://user-images.githubusercontent.com/1753687/53611267-c34e8100-3b82-11e9-9615-56ee37eb3925.png)

**Comment by magento-engcom-team** [comment] 2019-03-01 02:03
Hi @robyerevan. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@robyerevan do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by robyerevan** [comment] 2019-03-01 02:04
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-01 02:04
Hi @robyerevan. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-01 02:05
Hi @robyerevan, here is your [Magento instance](https://i-21521-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21521-2-3-develop.instances.magento-community.engineering/admin](https://i-21521-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by robyerevan** [comment] 2019-03-01 02:11
**Reproduced on 
Magento 2.3-develop instance**
![dev-2 3-develop](https://user-images.githubusercontent.com/1753687/53611648-2db3f100-3b84-11e9-999d-7e9d56cc2235.png)

**Comment by magento-engcom-team** [comment] 2019-03-01 05:25
Hi @krishprakash. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by krishprakash** [comment] 2019-03-01 05:27
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-01 05:27
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-01 05:28
Hi @krishprakash, here is your [Magento instance](https://i-21521-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21521-2-3-develop.instances.magento-community.engineering/admin](https://i-21521-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2019-03-01 05:36
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-01 05:36
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-01 05:37
Hi @krishprakash, here is your [Magento instance](https://i-21521-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21521-2-2-develop.instances.magento-community.engineering/admin](https://i-21521-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by amol2jcommerce** [comment] 2019-03-01 09:23
* @magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-01 09:23
Hi @amol2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-01 09:24
Hi @amol2jcommerce, here is your [Magento instance](https://i-21521-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21521-2-3-develop.instances.magento-community.engineering/admin](https://i-21521-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-03-01 16:41
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-03-01 16:42
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98517`, `MAGETWO-98518` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-03-14 19:45
Hi @robyerevan. Thank you for your report. 
The issue has been fixed in magento/magento2#21701 by @tuyennn in 2.3-develop branch
Related commit(s):
 - [924dca297c1ac696e1362ec2e76a23676d87efa0](https://github.com/magento/magento2/commit/924dca297c1ac696e1362ec2e76a23676d87efa0)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-14 19:45 UTC
Labels: Issue: Ready for Work, Component: Tax, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Admin

**Comment by magento-engcom-team** [comment] 2019-04-03 16:25
Hi @robyerevan. Thank you for your report. 
The issue has been fixed in magento/magento2#21535 by @tuyennn in 2.2-develop branch
Related commit(s):
 - [d935998b6f70c9f5943b817511b0b8576366cb55](https://github.com/magento/magento2/commit/d935998b6f70c9f5943b817511b0b8576366cb55)
 - [fb2d35484179f95c908de86cb4ac17f5dca228ae](https://github.com/magento/magento2/commit/fb2d35484179f95c908de86cb4ac17f5dca228ae)

The fix will be available with the upcoming 2.2.9 release.
