### ISSUE TITLE
Warning: nl2br() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#31126] opened 2020-12-02 14:47 UTC
### Preconditions (*)

1. 2.4.1

### Steps to reproduce (*)

We are using the payment method "Bank transfer payment".
After submitting the order, I get:

> 1 exception(s):
> Exception #0 (Exception): Warning: nl2br() expects parameter 1 to be string, array given in vendor/magento/module-payment/view/frontend/templates/info/instructions.phtml on line 15

This is entered in the instructions:

```
Bitte überweisen Sie das Geld auf das folgende Konto: 

Kontoinhaber:	Company GmbH
Bankname:	XXXX YYYY
IBAN:	DE11 2222 3333 4444 5555 66
BIC:	XXXXXXXXX
```

### Expected result (*)

1. Should work

### Actual result (*)

> 1 exception(s):
> Exception #0 (Exception): Warning: nl2br() expects parameter 1 to be string, array given in vendor/magento/module-payment/view/frontend/templates/info/instructions.phtml on line 15

I also get the error when trying to view the order at https://company.de/sales/order/view/order_id/14725/

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Eddcapone** [comment] 2020-12-02 14:48
@magento give me 2.4-develop instance

**Comment by Eddcapone** [comment] 2020-12-02 14:59
I was not able to reproduce the error in the magento instance.

**Comment by engcom-Bravo** [comment] 2020-12-03 12:37
Hello @Eddcapone 

Thank you for your report

We have rechecked the reported issue on Magento 2.4-develop and 2.4.1 and are not able to reproduce the Exception 
The Instructions are displayed during checkout and the order is placed successfully
![bank_transfer](https://user-images.githubusercontent.com/51680745/101018842-c30fc080-3574-11eb-8ec4-c6dbac2ad42b.png)

So we have to close this issue. Please feel free to comment, reopen or create a new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by engcom-Bravo** 2020-12-03 12:37 UTC
Labels: Issue: ready for confirmation, not-confirmed

**Comment by Eddcapone** [comment] 2020-12-04 11:12
I debugged the Method `getInstructions()` in vendor/magento/module-payment/Block/Info/Instructions.php

```
    public function getInstructions()
    {
        $writer = new \Zend\Log\Writer\Stream(BP . '/var/log/zend_debug.log');
        $logger = new \Zend\Log\Logger();
        $logger->addWriter($writer);
        $logger->info("getInstructions()");

        if ($this->_instructions == null) {

            $logger->info("instructions is NULL");    // <-- never lands here

            $this->_instructions = $this->getInfo()->getAdditionalInformation(
                'instructions'
            ) ?: trim($this->getMethod()->getConfigData('instructions'));
        }

        $logger->info($this->_instructions);

        /* 
        Output:
        2020-12-04T11:08:28+00:00 INFO (6): array (
          'bank_account_owner' => NULL,
          'iban' => NULL,
          'bic' => NULL,
          'bank_company' => NULL,
        )
        */


        return $this->_instructions;
    }
```

If I change `if ($this->_instructions == null) {` to `if ($this->_instructions != null) {` then it is forced to reload the instructions and the error disappears. The question is, why does my instructions contain this:

```
        2020-12-04T11:08:28+00:00 INFO (6): array (
          'bank_account_owner' => NULL,
          'iban' => NULL,
          'bic' => NULL,
          'bank_company' => NULL,
        )
```

**Comment by Eddcapone** [comment] 2020-12-04 11:21
I figured out that the problem is coming from a payment extension (Threepartment_Debitpayment) that we are using. There is a bug somewhere. I will try to write a plugin for the `getInstructions()` method and check if it is an array and if true, then return an empty string. This should fix it.
