### ISSUE TITLE
Component Manager in Web Setup Wizard not loading

### ISSUE THREAD

**Issue by jldmn** [magento/magento2#5020] opened 2016-06-14 12:36 UTC
1. Open Web Setup Wizard from  Admin Panel
2. Open Component Manager Panel

![unbenannt](https://cloud.githubusercontent.com/assets/18490741/16042845/11fbd8d6-323d-11e6-8e1d-946796fda9b2.JPG)

Output from Devtools Network section:

```
Additional information:

ErrorException

File:
/var/www/html/magento2ce/setup/src/Magento/Setup/Model/DateTime/TimezoneProvider.php:35
Message:
Argument 1 passed to Magento\Setup\Model\DateTime\TimezoneProvider::__construct() must be an instance of Magento\Setup\Model\ObjectManagerProvider, instance of Magento\Framework\ObjectManager\ObjectManager given, called in /var/www/html/magento2ce/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 97 and defined
Stack trace:
#0 /var/www/html/magento2ce/setup/src/Magento/Setup/Model/DateTime/TimezoneProvider.php(35): Composer\Util\ErrorHandler::handle(4096, 'Argument 1 pass...', '/var/www/html/m...', 35, Array)
#1 /var/www/html/magento2ce/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(97): Magento\Setup\Model\DateTime\TimezoneProvider->__construct(Object(Magento\Framework\ObjectManager\ObjectManager))
#2 /var/www/html/magento2ce/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\Setup\M...', Array)
#3 /var/www/html/magento2ce/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\Setup\M...')
#4 /var/www/html/magento2ce/setup/src/Magento/Setup/Controller/ComponentGrid.php(90): Magento\Framework\ObjectManager\ObjectManager->get('Magento\Setup\M...')
#5 /var/www/html/magento2ce/setup/src/Magento/Setup/Controller/ComponentGrid.php(251): Magento\Setup\Controller\ComponentGrid->getTimezone()
#6 /var/www/html/magento2ce/setup/src/Magento/Setup/Controller/ComponentGrid.php(237): Magento\Setup\Controller\ComponentGrid->formatSyncDate('1465639793')
#7 /var/www/html/magento2ce/setup/src/Magento/Setup/Controller/ComponentGrid.php(165): Magento\Setup\Controller\ComponentGrid->formatLastSyncData(Array, Array)
#8 /var/www/html/magento2ce/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\ComponentGrid->componentsAction()
#9 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#10 /var/www/html/magento2ce/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#11 /var/www/html/magento2ce/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /var/www/html/magento2ce/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /var/www/html/magento2ce/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#14 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#15 /var/www/html/magento2ce/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#16 /var/www/html/magento2ce/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /var/www/html/magento2ce/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 /var/www/html/magento2ce/setup/index.php(31): Zend\Mvc\Application->run()
#19 {main}
```

**Comment by qmarlats** [comment] 2016-07-19 18:36
The same for me, I had this bug in 2.0.x and it's not fixed in 2.1

**Comment by flnative** [comment] 2016-07-25 20:22
Same issue for me.

**Comment by andimov** [comment] 2016-08-16 15:50
@jldmn
Thanks for reporting.
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, provide the used version also. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by TClilMouse** [comment] 2016-08-22 18:14
Same issue for me Magento 2.1
However no message under console

**Comment by ghost** [comment] 2016-08-27 14:31
Are you using `<magento root>/pub` as your Magento docroot?

**Comment by TClilMouse** [comment] 2016-08-29 16:31
Docroot is not /pub folder

**Comment by veloraven** [comment] 2016-08-31 11:16
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: please specify Magento version and format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by veloraven** 2016-08-31 11:16 UTC
Labels: Progress: needs update
