### ISSUE TITLE
Impossible to change Bundle item order from one page to another

### ISSUE THREAD

**Issue by Abdallah-herri** [magento/magento2#31585] opened 2021-01-07 16:32 UTC
### Summary (*)
i have a bundle product with more 50+ bundle items, however, doing this creates multiple pages with 20 items in each page, my issue is changing items order where if an item is in page 3 for example, i can't move it to page 2 or page 1.

### Examples (*)
![Screenshot_2021-01-07 Bundle test aubea Products Inventory Catalog Magento Admin(1)](https://user-images.githubusercontent.com/55665570/103917610-1645d780-510e-11eb-9bc2-fa926a3e9c2c.png)

### Proposed solution
create a way to drag and drop from one page to another, or something to precise the order of an item given.

### Severity
- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment] 2021-01-08 04:39
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2021-01-08 05:01
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40343` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment] 2024-07-31 03:35
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-07-31 03:51
Hi @Abdallah-herri,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.


![New-Product-Products-Inventory-Catalog-Magento-Admin (1)](https://github.com/user-attachments/assets/e13e449b-0fa6-4c64-bf23-f2c6f5025ab5)



Now we have option products per page so we can customize the size and we can drag and drop.


Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-31 03:51 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Component: Bundle, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P2, Severity: S3, Progress: done, Issue: ready for confirmation, Area: Product
