### ISSUE TITLE
Product view page does not apply custom design from category setting.

### ISSUE THREAD

**Issue by jimmyhien** [magento/magento2#10326] opened 2017-07-26 05:49 UTC
### Preconditions

1. Magento C.E 2.1.5
2. Test Category is setup with custom design layout and apply to products.
3. Product is setup.
4. Homepage is setup with list of products.
5. Product URL rewrites is using for SEO purpose.
6. URL rewrites will generate two URLs for product view page, 1 URL has category id and another URL doesn't have category id.

### Steps to reproduce

1. From homepage, click to product url and go to product view page.
2. Product view URL from homepage will be domain.com/product_name.html -> It will redirect to product view page without category.
3. Click to category -> product url and go to product view page.
4. Product view URL from category view will be domain.com/category/product_name.html -> It will redirect to product view page with category id.

### Expected result

1. Both URL should show the same layout from category custom design layout.

### Actual result

1. It shows product view page with two different layouts.

![product-view-page-without-category](https://user-images.githubusercontent.com/3213879/28606351-cd2ad52c-7200-11e7-8f7c-f3e143734515.PNG)

![product-view-page-with-category](https://user-images.githubusercontent.com/3213879/28606355-d33db704-7200-11e7-8735-0048c6c538b4.PNG)

**Comment by magento-engcom-team** [comment] 2017-09-21 19:06
@jimmyhien, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-21 19:06 UTC
Labels: bug report, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
