### ISSUE TITLE
Swagger - Uncaught SyntaxError: Unexpected token }

### ISSUE THREAD

**Issue by dankhrapiyush** [magento/magento2#34702] opened 2021-11-24 09:08 UTC
### Preconditions (*)

1. Magento 2.4.2 / 2.4.3

### Steps to reproduce (*)

1. Enable the Merge JavaScript Files
2. Go to the /swagger link

### Expected result (*)

1. It should load the page without the console error and the page should render

### Actual result (*)

1. It is throwing an error "Uncaught SyntaxError: Unexpected token '}'" and blocking the page
![swagger-err](https://user-images.githubusercontent.com/1868477/143207364-a3ef90fd-a091-474f-b16c-e3ba518fa972.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2021-11-24 11:02
Verified the issue on Magento 2.4-develop branch but the issue is not reproducible:

Steps performed:
1. Admin - Stores - Configuration - Advanced - Developer - Javascript Settings - Enable Merge JavaScript Files
2. Save
3. Reindex and cache clean
4. Launch http://magento.com/swagger/
No issue: Page is loaded as expected and no console error is thrown.
Able to send the API requests.
![image](https://user-images.githubusercontent.com/60198231/143226669-7473c5ed-d0c5-4ec9-b504-c2de88948329.png)

@dankhrapiyush kindly re verify the issue on Magento 2.4-develop branch as it has the latest code base and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2021-12-08 06:11
Hi @dankhrapiyush ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-12-08 06:11 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update

**Comment by sunilit42** [comment] 2022-03-30 08:23
@dankhrapiyush have you find fix for that?

**Comment by dankhrapiyush** [comment] 2022-07-05 16:47
@sunilit42 @RRRKotov The issue is fixed in the latest released version.
