### ISSUE TITLE
Issue with upgrading magento v 2.2.0 to v 2.4.3 via composer

### ISSUE THREAD

**Issue by emson-softound** [magento/magento2#34379] opened 2021-10-19 04:59 UTC
### Preconditions (*)

1. Magento Version 2.2.0
2. Composer 2.1.9
3. PHP version 7.4.24
4. Mysql-Server 8.0.26
4. Os - Ubuntu Server 20.04 LTS

### Steps to reproduce (*)

**Trying to upgrade magento 2.2.0 directly to 2.4.3 with the following set of commands,**

-   su magento  #(login as non root-linux user)
-   php bin/magento ma:e
-   composer require magento/composer-root-update-plugin=~1.0 --no-update
-   composer update
-   composer require magento/product-community-edition=2.4.3 --no-update
-   composer update
-   php bin/magento c:c
-   rm -rf var/cache/*
-   rm -rf var/page_cache/*
-   rm -rf generated/code/*
-   php bin/magento s:up
-   php bin/magento s:d:c
-   php bin/magento s:s:d -f en_AU
-   php bin/magento indexer:reindex
-   php bin/magento c:f
-   php bin/magento ma:d
-   php bin/magento deploy:mode:set production -s

**In the root of magento directory, Issue arises, when executing the composer update**
1. composer require magento/composer-root-update-plugin=~1.0 --no-update
2. composer update

### Expected result (*)

1. Composer should execute command "composer update" successfully without issues.

### Actual result (*)

1. Running into the following issues while executing composer update.
![composer-magento-issue](https://user-images.githubusercontent.com/87564332/137845232-06709424-56fb-4634-aab6-e2258b3d87f3.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment] 2021-11-02 21:43
Sorry, I have no experience with that eway module, maybe contact the people from eway to help you further? It might be that you are using the wrong Magento marketplace credentials in composer and maybe it can't find that eway module if you are using access keys from an account that hasn't 'purchased' that module.

**Comment by engcom-Echo** [comment] 2022-01-04 14:50
Hi @emson-softound,

Thank you for raising this issue.

After going through the conversation between you and @hostep, understood that now only problem you are facing is with [`eway/eway-rapid-magento2`](https://marketplace.magento.com/eway-eway-rapid-magento2.html#product.info.details.release_notes) module. So, can you please update if the issue is till there or you figured it out ? You can also write an email with proper query to supporthero@ewaypayments.com

Hope it helps. If your issue is resolved, do let us know so that we can close this issue otherwise please update with latest details.

Thanks

**Comment by engcom-Hotel** [comment] 2022-01-31 15:46
Dear @emson-softound,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-01-31 15:46 UTC
Labels: Issue: needs update
