### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#25112] opened 2019-10-17 08:03 UTC
### Preconditions (*)

1. Magento 2.3.2 CE Composer Ver - No sample data
2. PHP 7.2.21

### Steps to reproduce (*)

1. First Create New Product Simple
2. Go to System > Export
3. Choose Entity Type: Products

### Expected result (*)

1. Grid options show without warning

### Actual result (*)

1. Got warning 
Exception #0 (Exception): Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/vendor/magento/module-import-export/Block/Adminhtml/Export/Filter.php on line 246
Screenshot
![Screenshot from 2019-10-17 15-19-16](https://user-images.githubusercontent.com/1908873/66991189-c4242b00-f0f1-11e9-9d9a-0696e285d989.png)

return options attribute get null

**Comment by mrtuvn** [comment] 2019-10-17 08:13
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-10-17 08:13
Hi @mrtuvn. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-10-17 08:13
Hi @mrtuvn, here is your [Magento instance](https://i-25112-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25112-2-3-develop.instances.magento-community.engineering/admin](https://i-25112-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mrtuvn** [comment] 2019-10-17 08:27
Thanks @magento for sharing. Can you confirm PHP version for this shared instance.

**Comment by mrtuvn** [comment] 2019-11-01 09:45
This issue seem not available in instance installed full sample data

**Comment by engcom-Charlie** [comment] 2019-11-14 14:25
Hello @mrtuvn 
We are not able to reproduce this issue on the latest 2.3-develop & 2.3.2 branch by provided steps.

**Testing scenario:**

1. First Create New Product Simple
2. Go to System > Export
3. Choose Entity Type: Products

**Result:**
Grid options show without warning
![Peek 2019-11-14 15-40](https://user-images.githubusercontent.com/51680850/68865278-3c830980-06fb-11ea-928a-8b2a5e21d616.gif)

So i have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-11-14 14:25 UTC
Labels: Issue: Format is valid
