### ISSUE TITLE
Estimate Shipping Rates Observable Elements Do Not Include Shipping Fields Used In Cart Rules

### ISSUE THREAD

**Issue by brobie** [magento/magento2#9451] opened 2017-04-28 18:34 UTC
### Preconditions
1. Version: 2.1.6
2. Edition: Community
3. Application Mode: developer

### Steps to reproduce
1. Enable Flat Rate Shipping for $5.00
1. Create a cart price rule that uses "Shipping Region/State" as a condition. (State != Alaska)
2. Drive free pricing by that cart rule/condition.
3. On the first step of the checkout, switch your state from Alaska to Arkansas, and back.

### Expected result
1. When the state is changed to Alaska, you should see $5.00 shipping.
2. When the state is changed to Arkansas, you should see $0.00 shipping.

### Actual result
1. When you change the state to Alaska, the shipping rates do not refresh.
2. When you change the postal code (after changing the state to Alaska), the shipping rates refresh, but the free shipping is not removed.

The reason for this is that each shipping carrier defines its own observable fields (i.e. vendor/magento/module-offline-shipping/view/frontend/web/js/model/shipping-rates-validation-rules/flatrate.js) which are needed for the carrier implementation to check its rates.  However, this architecture is flawed since ANY shipping field can affect the shipping rates based on Free Shipping Cart Rules.  This is kind of a catch 22 because you need all of the shipping fields to be "observable elements", but you do not want to refresh shipping rates constantly.

**Comment by brobie** [comment] 2017-04-28 19:35
For our own usage, we only needed region_id (patch attached), but likely you would need to do something different.

[shipping_rates_adding_region_id_to_observable_elements.patch.txt](https://github.com/magento/magento2/files/965363/shipping_rates_adding_region_id_to_observable_elements.patch.txt)

**Comment by brobie** [comment] 2017-04-28 19:36
For our own usage, we only needed region_id (patch attached), but likely you would need to do something different.

[shipping_rates_adding_region_id_to_observable_elements.patch.txt](https://github.com/magento/magento2/files/965366/shipping_rates_adding_region_id_to_observable_elements.patch.txt)

**Comment by 1408sheva** [comment] 2017-07-04 11:48
Thanks for Your issue. We know for about this problem. It will be resolved in the coming release. At the moment, it has already been fixed in the branch 2.1-develop.

**Comment by 1408sheva** [comment] 2017-07-04 13:23
Internal ticket for ver. 2.1 - MAGETWO-63514
It was fixed already and fix will be available in one of the nearest releases.

**Comment by magento-engcom-team** [comment] 2017-10-04 11:30
@brobie, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-04 11:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Checkout, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid
