### ISSUE TITLE
404 Forbidden sounds not right

### ISSUE THREAD

**Issue by irinikp** [magento/magento2#10775] opened 2017-09-05 11:57 UTC
### Preconditions
Magento 2.1

### Steps to reproduce
Reopening [Issue #5176](https://github.com/magento/magento2/issues/5176) as it is still reproducible

![capture](https://user-images.githubusercontent.com/14233344/30060077-77f299ae-924a-11e7-9459-623d9c8152ae.PNG)

**Comment by kalpmehta** [comment] 2017-09-05 19:18
Make sure your hosting provider is not blocking it. Are you on nexcess?

**Comment by irinikp** [comment] 2017-09-06 08:22
Not on nexcess. I have a dedicated server, there is no blocking

**Comment by ekuusela** [comment] 2017-09-07 08:14
The forbidden status is set here:

https://github.com/magento/magento2/blob/b2f688c6402289e4efb1e21fc894bc4a8d2a8be5/app/code/Magento/Backend/Controller/Adminhtml/Noroute/Index.php#L37

**Comment by magento-engcom-team** [comment] 2017-09-13 20:18
@irinikp  thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [x] Preconditions: Magento version
 - [ ] DETAILED Steps to reproduce and enviroument configuration
 - [ ] Expected result
 - [ ] Actual result

**Comment by korostii** [comment] 2017-09-14 12:57
Hello again @magento-engcom-team
The comment above yours goes as far as pointing out the exact place in source code which ought to be fixed. Putting bureaucracy aside, that's more plenty enough information.

If you insist, it's insanely easy to reproduce: you can even access the page directly. 
Here's a CE 2.1.8: http://take.ms/Cp62g

**Comment by orlangur** [comment] 2017-09-14 16:04
Looks like there was a copy-paste typo in https://github.com/magento/magento2/commit/77ac45b6229c347784cd3d7945fff09feebd6cb4. While `'up for grabs'` is usually used for some huge necessary changes, would be nice to have some label like https://github.com/facebook/hhvm/issues?q=is%3Aopen+is%3Aissue+label%3A%22probably+easy%22 for smaller issues.

**Comment by magento-engcom-team** [comment] 2017-09-22 09:02
@korostii @ekuusela We always encourage you to submit a Pull Request if the fix is that easy.
Otherwise clear issue report is required, so that developer working can precisely identify issue and possible testing scenarios.
Thank you for understanding.

**Comment by korostii** [comment] 2017-09-29 10:24
@magento-engcom-team I think you're missing the point.
The issue was clearly valid and had just the right amount of information on it.
If it has plenty info for a PR (BTW thank you @Zifius for coming forward #11134 ), it should be enough of a "clear issue report".

Dismissing the issue after manual review with a comment that's clearly hostile (I mean, caps? http://take.ms/MWYka was that really necessary? ) because the _formatting_ is not to your liking isn't an okay way to greet voluntary bug reports.

Don't we have a [Code of Conduct](https://github.com/magento/magento2/wiki/Magento-Code-of-Conduct) which says that everyone should be, and I quote: "Gracefully accepting constructive criticism" and "Focusing on what is best for the community"?
IMHO [that comment](https://github.com/magento/magento2/issues/10775#issuecomment-329284672) goes a little overboard with this urge to get the issue template right.

**Comment by ishakhsuvarov** [comment] 2017-09-29 10:37
I have to lock this conversation as it is now beyond 
> "Gracefully accepting constructive criticism"

Thanks for collaboration. Fix for the issue hopefully will be delivered with the next patch for `2.2`.

**Comment by magento-engcom-team** [comment] 2017-10-06 20:35
Hi @irinikp the issue has been fixed in 2.2.1 and will be available soon (#11134)

**Closed as completed by magento-engcom-team** 2017-10-06 20:35 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid

**Comment by magento-team** [comment] 2017-10-06 21:00
Internal ticket to track issue progress: MAGETWO-80515

**Comment by magento-team** [comment] 2018-01-25 15:15
Hi @irinikp. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1282 by @magento-engcom-team in 2.3-develop branch
Related commit(s):


The fix will be available with the upcoming patch release.
