### ISSUE TITLE
Cart Price Rule Free Shipping Error Magento 2.3.x

### ISSUE THREAD

**Issue by nickpiro** [magento/magento2#29428] opened 2020-08-06 20:13 UTC
When creating a Cart Price Rule for Free Shipping for Orders of $49+ on Matching Items Only, with specific exclusions via Conditions, Free Shipping is given to entire cart when non-excluded items are added and cart goes above $49.

### Preconditions (*)

1. Magento 2.3.0 , 2.4-develop

### Steps to reproduce (*)

1. Create Cart Price Rule with following Conditions

- If ALL  of these conditions are TRUE :
- Subtotal  equals or greater than  49  
- Shipping State/Province  is not  Hawaii  
- Shipping State/Province  is not  Alaska  
- Shipping Country  is  United States  
- If an item is FOUND  in the cart with ALL  of these conditions true: 
- Category  is not one of  699  
- Category  is not one of  849  

2. Actions: Free Shipping For Matching Items Only
3. Add product which is excluded from free shipping via Conditions. Shipping price is displayed.
4. Add product to cart that is above $49 that matches rules to ship free, and whole cart ships free.

### Expected result (*)

1. Free shipping is only added to matching items.
2. Free shipping is not for the entire cart.

### Actual result (*)

1. Entire cart ships free, although one of the items were excluded via the Condition 'Category is not one of...'

### Additional Information

![image](https://user-images.githubusercontent.com/2028541/95747397-4a853580-0c90-11eb-9afa-61c1f93fa2da.png)

**Comment by magento-engcom-team** [comment] 2020-08-14 14:18
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36754` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by jignesh-coder** [comment] 2020-10-09 13:26
@magento add to contributors team

**Comment by jignesh-coder** [comment] 2020-10-09 13:27
@magento I am working on it

**Comment by jignesh-coder** [comment] 2020-10-12 10:55
@nickpiro @sivaschenko 
http://prntscr.com/uxoheo

**Comment by jignesh-coder** [comment] 2020-10-12 12:44
Hello @sivaschenko ,
i want to say that the issue is not generate when you set the condition like this http://prntscr.com/uxoheo

when you put the condition here https://drops.meetanshi.com/Xx6zzQ it check for the whole cart
and for particular cart item you need to set the condition here https://drops.meetanshi.com/ghU8xa

if you set the condition like http://prntscr.com/uxoheo than issue is not generate

**Comment by sivaschenko** [comment] 2020-10-12 12:51
@jignesh-coder Do you mean this is not a bug?

**Comment by nickpiro** [comment] 2020-10-12 14:10
@jignesh-coder that is absolutely the answer my friend. THANK YOU. I'm not sure if this would be considered a bug or just how the cart price rule is supposed to work. @sivaschenko but @jignesh-coder proposed solution works perfectly.

**Comment by jignesh-coder** [comment] 2020-10-12 14:41
@sivaschenko and @nickpiro 
Yes, I think it's not an issue.
This is how the cart price rule should work.

**Comment by sivaschenko** [comment] 2020-10-12 18:08
Closing the issue as not a bug. See the comments above for details

**Comment by sivaschenko** [comment] 2020-10-12 18:09
Thank you @jignesh-coder !!

**Closed as completed by sivaschenko** 2020-10-12 18:08 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Issue: Format is valid, Component: Rule, Reproduced on 2.4.x, Priority: P2, Severity: S2, Progress: done, CD, Reported on 2.3.0
