### ISSUE TITLE
Unable to override the block "Block/System/Config/Form/Field.php"

### ISSUE THREAD

**Issue by usn0545** [magento/magento2#4714] opened 2016-05-26 11:25 UTC
when I install my custom module and developer mode is on. Now if I make my module as store based.
then it is throwing an error as "**## Fatal error: Call to a member function isSingleStoreMode() on a non-object in /var/www/html/magento/vendor/magento/module-config/Block/System/Config/Form/Field.php on line 151**". And when I tried to override this block file then it is not overriding.
Can you tell me why I'm unable to solve the issue and how to solve this issue.

**Comment by veloraven** [comment] 2016-11-01 16:33
@usn0545 is this issue still actual?
If it is please describe detailed steps, actual result and expected result.
If it is not, please close it.
If it is more question than an issue please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) as GitHub issue tracker is intended for technical issues only.

**Comment by veloraven** [comment] 2016-11-16 07:43
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Closed as completed by veloraven** 2016-11-16 07:43 UTC
Labels: Progress: needs update
