### ISSUE TITLE
EU VAT not calculated corectly in frontend

### ISSUE THREAD

**Issue by mtjweb** [magento/magento2#35236] opened 2022-03-26 14:14 UTC
### Preconditions (*)

1. Magento 2.4.3-p1

### Steps to reproduce (*)

1. Configure Magento for EU Tax rules
2. Checkout with a valid EU VAT-number

### Expected result (*)

1. No tax should be calculated at checkout
2.

### Actual result (*)

1. Tax is still being calculated in frontend
2. When you manually created the order in the backend and validate the VAT-number, no tax is being calculated.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-04-08 13:01
Hi @mtjweb ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue with provided steps.
As per [Magento docs](https://docs.magento.com/user-guide/tax/vat-validation.html)
VAT is charged if the merchant and customer are located in the same EU country.
VAT is not charged if the merchant and customer are located in different EU countries, and both parties are EU-registered business entities.
https://docs.magento.com/user-guide/tax/vat-validation-configure.html
Kindly recheck the issue on Magento 2.4-develop branch and elaborate steps / configuration details if the issue still exists.
Thank you.

**Comment by engcom-November** [comment] 2022-04-22 07:20
Hi @mtjweb ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-04-22 07:20 UTC
Labels: Issue: needs update
