### ISSUE TITLE
Magento doesn't recognise .store as valid TLD

### ISSUE THREAD

**Issue by JangriX** [magento/magento2#11689] opened 2017-10-24 13:32 UTC
### Preconditions
1. Fresh magento install, version 2.1.7

### Steps to reproduce
1.  Go to website configuration
2.  Select any field that deals with email addresses
3. Enter any email address with .store domain, like example@example.store
4. Save configuration

### Expected result
1. Configuration is saved

### Actual result
1. An error appears: Please correct the email address: "info@example.store".

.store is valid TLD since 2016, and I imagine quite relevant to e-commerce.

Currently the only workaround is to set the values manually through the database, and so far I've observed no adverse effects from this, thankfully.

**Comment by orlangur** [comment] 2017-10-24 13:36
Hi @Jangri, thanks for a well-formed bug report!

It is a duplicate of https://github.com/magento/magento2/issues/4547 and already fixed on 2.2 branch.

**Closed as completed by orlangur** 2017-10-24 13:36 UTC
Labels: duplicate, Issue: Format is valid
