### ISSUE TITLE
Invoice capture not working in magento2.

### ISSUE THREAD

**Issue by ajayshukla** [magento/magento2#4742] opened 2016-05-27 13:21 UTC
## Invoice Capture is not working in Magento 2.0.6
1. For the invoices whose initial state is pending, I am trying change it to Paid by clicking the Capture link on admin invoice details page but its still remains pending. 
2. I think this is because of these lines of code in vendor/magento/module-sales/Controller/Adminhtml/Order/Invoice in execute method:
   
   ```
   $invoiceManagement = $this->_objectManager->get('Magento\Sales\Api\InvoiceManagementInterface');
           $invoiceManagement->setCapture($invoice->getEntityId());
           $invoice->getOrder()->setIsInProcess(true);
           $this->_objectManager->create(
               'Magento\Framework\DB\Transaction'
           )->addObject(
               $invoice
           )->addObject(
               $invoice->getOrder()
           )->save();
           $this->messageManager->addSuccess(__('The invoice has been captured.'));
   ```
3. Rather than changing the state of the invoice it is regenerating the same invoice with same state.
4. Instead I think it should do this:

```
if ($invoiceId) {
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $invoice = $objectManager->create('Magento\Sales\Model\Order\Invoice')->load($invoiceId);
            if ($invoice) {
                $invoice->pay()->save();
            }
        }
```

> Can anyone please suggest the solution for this core bug?

**Comment by ajayshukla** [comment] 2016-05-31 06:37
Any solution would be highly appreciated! Can anyone please have your say on the solution for this bug?

**Comment by NadiyaS** [comment] 2016-06-01 07:35
Hi @ajayshukla,
thanks for reporting this issue. It is already being tracked by MAGETWO-52552 ticket and fix will be merged to develop branch in a few days.
This issue will be closed as duplicate of #4385.

**Closed as completed by NadiyaS** 2016-06-01 07:35 UTC
Labels: Issue: Format is not valid

**Comment by parekhreena** [comment] 2017-11-28 14:16
@NadiyaS  This still does not get fixed by #4385 fix. The fix in #4385 addresses capturing from API. Capturing via Admin panel still does not work.

**Comment by NadiyaS** [comment] 2017-11-28 14:24
Hi @parekhreena ,
you can reopen the issue if it is still reproducible or create a new one if steps to reproduce are different from those were described.

**Comment by purvi99** [comment] 2020-10-07 13:39
Hello,

I have still issue when creating issue.i got issue like "SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`dbname`.`quote_payment`, CONSTRAINT `QUOTE_PAYMENT_QUOTE_ID_QUOTE_ENTITY_ID` FOREIGN KEY (`quote_id`) REFERENCES `quote` (`entity_id`) ON DELETE CASCADE), query was: INSERT INTO `quote_payment` (`additional_information`) VALUES (?)".
