### ISSUE TITLE
Automaticly subscribe customer for newsletter

### ISSUE THREAD

**Issue by robbertstevens** [magento/magento2#14743] opened 2018-04-17 14:34 UTC
When saving a customer after you visited the newsletter page, customer is automaticly signed up for newsletter.

### Preconditions

1. 2.1.12   Community
2. PHP 7.0.28-1 

### Steps to reproduce

1. Go to the customer in the backend.
2. Go to the newsletter tab
3. Don't touch anything!
4. Save customer

### Expected result

1. Customer is the same as before you saved it, because you didn't touch anything

### Actual result

![image](https://user-images.githubusercontent.com/726557/38876131-2e8b5cd4-425c-11e8-8cd1-7e6eb58df8a7.png)
1. Customer is signed up for newsletter and received the email

**Comment by Karlasa** [comment] 2018-04-19 06:36
2.1.12 has the issue, but cant reproduce on 2.2.3

**Comment by Karlasa** [comment] 2018-04-19 06:49
fixed in 2.1-developer. You can close this issue

**Comment by robbertstevens** [comment] 2018-04-19 08:43
Where is the commit that fixes this? I can't upgrade so I need to know how to fix it. @Karlasa

**Comment by Karlasa** [comment] 2018-04-19 09:36
@robbertstevens 

https://github.com/magento/magento2/commit/bc9f2c091842657cd0488fc5a59bd942347db903#diff-143aa8bdac5b6f9e9de6a342764abb04

app/code/Magento/Customer/Controller/Adminhtml/Index/Save.php file line 256

**Comment by osrecio** [comment] 2018-06-26 07:37
Solved and solution referenced

**Closed as completed by osrecio** 2018-06-26 07:37 UTC
Labels: Fixed in 2.1.x, Fixed in 2.2.x, Issue: Format is valid
