### ISSUE TITLE
isAdminSecure never used or missing code

### ISSUE THREAD

**Issue by cdiacon** [magento/magento2#4720] opened 2016-05-26 15:21 UTC
This property is never used protected $_isAdminSecure = null;
## Steps to reproduce
1. Install Magento from `develop` branch.
2. File Magento\Store\Model\Store.php  line 209
   https://github.com/magento/magento2/blob/develop/app/code/Magento/Store/Model/Store.php#L209
3. It looks like this flag is never used or there is missing code or should be moved to a new file?!?

Thanks.

**Comment by magento-engcom-team** [comment] 2017-09-11 21:29
@cdiacon thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [x] Preconditions: Magento version
 - [x] Steps to reproduce
 - [x] Expected result
 - [x] Actual result

**Comment by magento-engcom-team** [comment] 2017-09-13 19:38
Pull Request #10877 is created to address the issue

**Comment by magento-team** [comment] 2017-09-14 19:02
Internal ticket to track issue progress: MAGETWO-75114

**Comment by magento-engcom-team** [comment] 2017-09-20 23:08
@cdiacon, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by orlangur** [comment] 2017-09-20 23:25
@magento-engcom-team I don't think deprecations can be backported actually :)

**Closed as completed** 2017-09-20 23:26 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Fixed in 2.3.x, Issue: Format is not valid
