### ISSUE TITLE
Catalog Rule with SKU is filter is being applied to all products with SKU starting with given SKU

### ISSUE THREAD

**Issue by Tomasz-Silpion** [magento/magento2#36576] opened 2022-12-06 21:40 UTC
### Preconditions and environment

**2.4.5, 2.4.5-p1**,2.4 develop

Sample Data Installed.
  

Just confirmed on f7ae7502ae239b06a1ea15f75cb27671 instance from 2.4-develop.
The Store I manage has lost a huge amount of money today because of the issue.

### Steps to reproduce

1.Create a Product with SKU 24
2. Navigate to Marketing -> Catalog Price Rule -> Add New Rule
3. Apply condition:

` If ALL  of these conditions are TRUE :
   SKU is 24 `
   
4. Set any discount amount in actions.
5. Click Save and Apply
6. Flush cache
7. Go to the storefront and check price of any product starting with SKU 24 e.g. 24-WB03 Driven Backpack from demo data.

### Expected result

 Catalog rule should be applied only to single product with SKU equal to "24".

<img width="1235" alt="Screenshot 2022-12-07 at 4 09 40 PM" src="https://user-images.githubusercontent.com/51680745/206191115-4afc5358-a72d-4ade-afd4-9529deb5e987.png">

### Actual result

Discount is applying every product that starts with SKU 24 series.

<img width="1216" alt="Screenshot 2022-12-07 at 4 09 54 PM" src="https://user-images.githubusercontent.com/51680745/206191049-7124c3ff-b071-41c5-a3d2-14011a32da9a.png">

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Tomasz-Silpion** [comment] 2022-12-07 09:00
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-12-07 12:53
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-12-07 13:23
Hi @Tomasz-Silpion,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.

**Steps to reproduce**

1.Create Product with SKU 24
2.Navigate to Marketing -> Catalog Price Rule -> Add New Rule
3.Apply condition:
`If ALL of these conditions are TRUE : SKU is 24`

4.Set any discount amount in actions.
5.Click Save and Apply
6.Flush cache
7.Go to the storefront and check price of any product starting with SKU 24 e.g. 24-WB03 Driven Backpack from demo data.

It is applying Discount all products starting with SKU 24 series.


![Error-Catalog-Price-Rule-Promotions-Marketing-Magento-Admin](https://user-images.githubusercontent.com/51680745/206189852-3d5b7e1a-2484-47d8-b66f-2309d832a453.png)



<img width="1235" alt="Screenshot 2022-12-07 at 4 09 40 PM" src="https://user-images.githubusercontent.com/51680745/206189704-c4c1f86c-83db-4e19-8e26-8c913cbf2dd3.png">



<img width="1216" alt="Screenshot 2022-12-07 at 4 09 54 PM" src="https://user-images.githubusercontent.com/51680745/206189739-0f7c2d81-96e8-4cbb-99b6-55b6ce008e80.png">




Hence Confirming the issue.


Thanks.

**Comment by victoria-s1** [comment] 2022-12-07 13:28
@magento give me 2.4-develop instance

**Comment by mahesh-singh-rajawat** [comment] 2023-03-15 06:08
Hi @Tomasz-Silpion Thank you for working in this.
This issue  is already fixed in internal Ticket: [AC-6810](https://jira.corp.adobe.com/browse/AC-6810)
Commit: https://github.com/magento/magento2/commit/522d82e5c9f9ec0d0a1ff5e9d461491b589c6c41#diff-90d80b2b045bed78acfa31c17ad7dc4f0e5e7ff7e1c16a0ba2dd4c2609db4c28

Feel free to get latest changes from 2.4-develop branch.

**Closed as completed** 2023-03-15 06:51 UTC
Labels: Component: CatalogRule, Issue: Confirmed, Reproduced on 2.4.x, Priority: P1, Progress: done, Area: Catalog, Reported on 2.4.5-p1
