### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation error when saving product without sku

### ISSUE THREAD

**Issue by engcom-November** [magento/magento2#35810] opened 2022-07-25 09:59 UTC
### Preconditions and environment

2.4.4 and 2.4-develop

### Steps to reproduce

1. Admin - Stores - Attributes - Product - Search for sku - edit - set "Values Required" - No and save
2. Clear cache
3. Create product without sku - save. - Invalid error message displayed to the user.
**Error in 2.4-develop branch:**  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'sku' cannot be null, query was: INSERT INTO `catalog_product_entity` (`entity_id`, `attribute_set_id`, `type_id`, `sku`, `has_options`, `required_options`, `created_at`, `updated_at`) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
4. Create product with sku value and save
5. Edit product - remove sku and save - User is able to save the product without sku

### Expected result

Valid below error message will be displayed to the user.
"The "sku" attribute value is empty""

### Actual result

On 2.4.4 Project-community-edition, below php error is returned on creating product without SKU
Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/mg244/project-community-edition/vendor/magento/module-eav/Model/Entity/AbstractEntity.php on line 932

### Additional information

User is able to save the product without price (If configured "not required" in attribute configuration) even though it is mandated with " * " in admin configuration
![image](https://user-images.githubusercontent.com/60198231/180752533-3f700e8e-6f0b-4a15-9730-824a8cbc2352.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment] 2022-07-25 10:29
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment] 2022-07-25 10:56
:heavy_check_mark: Issue confirmed

Issue got reproduced in **2.4-develop** branch.

**Description:** Getting `SQLSTATE[23000]: Integrity constraint violation` error when saving product without sku
**Pre-requisite:**
Fresh magento `2.4-develop` should be installed.

**Steps to reproduce:**

1. 1.Admin - Stores - Attributes - Product - Search for sku - edit - set "Values Required" - No and save
2. Clear cache
3. Create product without sku - save. - Invalid error message displayed to the user.
4. Error in 2.4-develop branch: `SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'sku' cannot be null, query was: INSERT INTO catalog_product_entity (entity_id, attribute_set_id, type_id, sku, has_options, required_options, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`
5. Create product with sku value and save
6. Edit product - remove sku and save - User is able to save the product without sku 

**Expected result:** Invalid error/exception should not be displayed.
**Actual result:**  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'sku' cannot be null, query was: INSERT INTO catalog_product_entity (entity_id, attribute_set_id, type_id, sku, has_options, required_options, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
**Screenshot:**
![image](https://user-images.githubusercontent.com/60198022/180759831-ce3953a5-0b0d-4c31-a168-fdbc73579347.png)

Hence, confirming the issue.

**Comment by engcom-Hotel** [comment] 2022-07-25 14:48
@magento give me 2.4-develop instance

**Comment by KrasnoshchokBohdan** [comment] 2022-08-26 08:25
@magento I am working on this

**Comment by hostep** [comment] 2022-10-13 19:43
@engcom-Hotel: what was the reason for closing this? Please always specify a reason when closing issues in the future, otherwise it's confusing the people who watch the ticket.

/cc @sdzhepa (this closing of issues without specifying a reason happens way too often over here, please talk to all people that do this so it no longer happens, thanks!)

**Comment by glo35082** [comment] 2022-10-17 12:03
Issue resolved. Empty SKU will no longer be allowed. 
<img width="1064" alt="Screenshot 2022-10-17 at 5 24 01 PM" src="https://user-images.githubusercontent.com/104774199/196172276-8c30e53d-5b08-4c7a-8a7a-b89789af5cf0.png">

**Comment by DanK894** [comment] 2022-10-18 09:33
@glo35082  I propose to create a new notification/error to notify the user that "SKU" is required.

I can also prevent the "SKU" attribute from being made optional.

**Comment by KrasnoshchokBohdan** [comment] 2022-10-27 15:09
@glo35082 I propose to create a new notification/error to notify the user that "SKU" is required.

I can also prevent the "SKU" attribute from being made optional.

**Comment by glo35082** [comment] 2022-10-28 07:09
@KrasnoshchokBohdan we discussed the matter regarding your comment "_I can also prevent the "SKU" attribute from being made optional._" We are planning and discussing on this, in a generic way which would cater all such attributes whichever to be deemed 'not optional' in future. We shall update you once any decision is finalised in this regard. 

Right now we are delivering the fix with "The SKU attribute value is empty" as shown in the above image.

**Comment by engcom-November** [comment] 2022-11-16 07:02
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-11-16 10:05
Hi @KrasnoshchokBohdan ,
As mentioned by @glo35082 in the [comment](https://github.com/magento/magento2/issues/35810#issuecomment-1294555440), after internal discussions with Product Owner and team, it has been decided that a proper error message (The "sku" attribute value is empty") will be displayed to the end user when trying to create or save a product without SKU for the time being. This is the approved [PR](https://github.com/magento-gl/magento2ce/pull/525) having the changes related to the same and target version for the fix is 2.4.6. Display error message in a generic way for all such mandatory / predefined attributes (Ex: Name, price etc) will be soon implemented in coming future.
Thank you.

**Closed as completed** 2022-12-14 16:01 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P1, Progress: done, Component: Attributes, Reported on 2.4.x, Area: Product, Reported on 2.4.4

**Comment by engcom-Hotel** [comment] 2022-12-15 05:08
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-6020 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-6020&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks
