### ISSUE TITLE
Couldn't able to create a customer in admin panel for multi website (Magento Version : 2.4.4) 

### ISSUE THREAD

**Issue by kiruthika1611** [magento/magento2#36261] opened 2022-10-10 12:27 UTC
### Preconditions and environment

- Magento version - **2.4.4**

### Steps to reproduce

**Example :**

**Step - 1**
**Create Multi store website**

Login to admin -> Store -> Configuration -> All store -> 

1. Create a websites
2. Create store
3. Create store view

**Please refer Below image**
![image](https://user-images.githubusercontent.com/114425316/194864979-de0d8b83-24e2-4489-96b9-cbe4c6779040.png)

### Expected result

**Create a new customer in admin panel**

Go to customers -> Add new Customers -> Customer Information -> Account Information -> Select associate website to US -> Save Config 

- **We need to create a customer in admin panel for all website**

### Actual result

**Create a new customer in admin panel**

Go to customers -> Add new Customers -> Customer Information -> Account Information -> Select associate website to US -> Save Config 

- **We couldn't able to create a customer in admin panel for US and UK website**

- **We can able to create a customer in admin panel for IN website only**

Please refer the below image :

![image](https://user-images.githubusercontent.com/114425316/194865679-d1df3c9c-a8d1-4fc7-ab7d-d00deaf0dbc9.png)

### Additional information

Please refer the video to reproduce the issue:

https://user-images.githubusercontent.com/114425316/194865878-e3fff86a-95cf-4c50-a058-76eed797dd55.mp4

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-10-11 11:36
Hi @kiruthika1611,

Thanks for quick Response.

Verified the issue on Magento 2.4-develop instance but could not reproduce the issue.We are able to create Customers in admin panel for multi website.kindly refer screenshots.



Login to admin -> Store -> Configuration -> All store ->

1.Create a websites
2.Create store
3.Create store view



<img width="1401" alt="Screenshot 2022-10-11 at 2 33 15 PM" src="https://user-images.githubusercontent.com/51680745/195079188-694c902d-fbfb-4093-bd70-7c29d28f24e3.png">



Go to customers -> Add new Customers -> Customer Information -> Account Information -> Select associate website to US -> Save Config




<img width="1271" alt="Screenshot 2022-10-11 at 2 34 59 PM" src="https://user-images.githubusercontent.com/51680745/195079228-de0ab2b3-c695-47d8-ab23-23dd7fcb6369.png">



Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.


Thanks.

**Comment by kiruthika1611** [comment] 2022-10-12 06:06
Hi @engcom-Bravo 

**Summary of the issue :**

- When we change **Account Sharing Option per website to global** Then, We couldn't able to create a customer in admin panel except default website.

**Step to Reproduce :**

**Step - 1**

- Login to admin -> Store -> Settings -> Configuration -> All store -> 

1. Create Website
2. Create Store
3. Create Store View

**Please refer the below screenshot for create a multi webiste, store and store view : **

![image](https://user-images.githubusercontent.com/114425316/195259277-05298191-13e9-4d60-9a77-5945c14bd672.png)

**Step - 2**

Go to Store ->Settings -> Configuration -> Customers -> Customer Configuration -> Expend  **Account Sharing Options** -> **Change perwesite to global for Share Customer Accounts**

**Please refer the below screenshot for make global for account sharing option** 

![image](https://user-images.githubusercontent.com/114425316/195260687-bfcaff98-6fcd-4d73-b9ae-bb9baf0a0125.png)

**Step - 3**

Go to Customers -> All customer -> Add New Customer ->  select UK for associate website -> fill the firstname, lastname and email -> Save Customer

- **We couldn't able to create a customer for admin panel for UK website.**
- Error is occured **(The Store View selected for sending Welcome email from is not related to the customer's associated website).**

**Please refer the below screenshot :**

![image](https://user-images.githubusercontent.com/114425316/195261971-784fbad9-6712-412e-9529-410821283efc.png)


**Actual Result**

- When we **change the Account Sharing Option is perwebsite to global**. Then, we couldn't able to create a customer in admin panel except default website.

**Expected Result**

- When we **change the Account Sharing Option is perwebsite to global**. Then, we need to create a customer in admin panel for all websites.

**Reference video (For Step to reproduce the issue)**

https://user-images.githubusercontent.com/114425316/195262745-21358f67-9ec4-453b-94a4-28cca8119f25.mp4

**Comment by engcom-Bravo** [comment] 2022-10-13 09:49
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-10-13 13:02
Hi @kiruthika1611,


Thanks for Reporting and collaboration.

Verified the issue on Magento 2.4-develop instance but could not reproduce the issue.We are able to create Customers in admin panel for multi website.kindly refer screenshots.


<img width="1426" alt="Screenshot 2022-10-13 at 6 24 29 PM" src="https://user-images.githubusercontent.com/51680745/195602030-6d4ae34a-bbcc-4d6c-a10d-25b7af93d3c9.png">




<img width="1399" alt="Screenshot 2022-10-13 at 3 39 36 PM" src="https://user-images.githubusercontent.com/51680745/195601857-fde54cb3-a815-4504-9374-c08d6eab7130.png">



<img width="1471" alt="Screenshot 2022-10-13 at 3 39 59 PM" src="https://user-images.githubusercontent.com/51680745/195601964-1382e2ae-1aa3-4320-a6cb-f27b5bbcb46c.png">




<img width="1486" alt="Screenshot 2022-10-13 at 3 39 44 PM" src="https://user-images.githubusercontent.com/51680745/195602157-3adab9bb-801a-4f9f-b266-2f3740f231ff.png">






<img width="1483" alt="Screenshot 2022-10-13 at 3 41 05 PM" src="https://user-images.githubusercontent.com/51680745/195602398-2ee44908-63a9-490f-8e8f-b93d34684296.png">







<img width="1359" alt="Screenshot 2022-10-13 at 3 41 15 PM" src="https://user-images.githubusercontent.com/51680745/195602426-0408a6a1-6d48-47fb-80f9-b743753e37ec.png">








<img width="1490" alt="Screenshot 2022-10-13 at 3 41 28 PM" src="https://user-images.githubusercontent.com/51680745/195602472-0c7917ff-2e62-4527-9146-73cf0d2b6bb8.png">







<img width="1499" alt="Screenshot 2022-10-13 at 3 41 35 PM" src="https://user-images.githubusercontent.com/51680745/195602503-ec7e1d9d-3492-4177-aca0-d5b9a0504144.png">



Step to Reproduce :

Step - 1

Login to admin -> Store -> Settings -> Configuration -> All store ->
1.Create Website
2.Create Store
3.Create Store View


Step - 2

Go to Store ->Settings -> Configuration -> Customers -> Customer Configuration -> Expend Account Sharing Options -> Change perwesite to global for Share Customer Accounts



Step - 3

Go to Customers -> All customer -> Add New Customer -> select UK for associate website -> fill the firstname, lastname and email -> Save Customer



After changing the the Account Sharing Option is perwebsite to global.we are able to create a customer in admin panel for all websites.




Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.

Thanks

**Comment by kiruthika1611** [comment] 2022-10-13 14:24
Hi @engcom-Bravo 

I tried fresh **magento version 2.4.4** without install any 3rd party extensions / modules / patches. But, After changing the Account Sharing Option is perwebsite to global.we aren't able to create a customer in admin panel for all websites except default website.

Kindly, recheck that issue on **Magento version 2.4.4**

**Comment by engcom-Bravo** [comment] 2022-10-14 09:10
@magento give me 2.4.4 instance

**Comment by engcom-Bravo** [comment] 2022-10-14 12:53
Hi @kiruthika1611,


Thanks for quick Response.


It is recommended to verify issues on latest magento instance and issue is no more reproducible on latest magento instance but it is reproducible on 2.4.4. issue might have got fixed in 2.4-develop.

Kindly upgrade your Magento instance to latest version and please let us know if you are still facing any issue.


Thanks.

**Comment by kiruthika1611** [comment] 2022-10-14 14:24
Hi @engcom-Bravo 

Thanks for your response. 

Regarding this issue,
**Is there any patches available in **Magento Version 2.4.4****

Thanks.

**Comment by engcom-Bravo** [comment] 2022-10-17 12:07
Hi @kiruthika1611,

Thanks for quick Update.

There are no patches available in Magento Version 2.4.4 related to this.

Kindly Upgrade to Magento Latest Version 2.4.5.Please let us know if you are still facing any issue.


Thanks.

**Comment by kiruthika1611** [comment] 2022-10-17 12:29
Hi @engcom-Bravo 

Thank you for your response

Thanks.

**Comment by engcom-Bravo** [comment] 2022-11-02 06:17
Hi @kiruthika1611,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-11-02 06:17 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.4
