### ISSUE TITLE
Permissions Error When Running `bin/magento setup:upgrade`

### ISSUE THREAD

**Issue by astorm** [magento/magento2#3092] opened 2016-01-23 19:01 UTC
Sometimes, with developer mode enabled, when I run `bin/magento setup:upgrade`, the script bails with the following error message.

> Missing write permissions to the following directories: '/path/to/magento/pub/static'

Extra confusingly, this error persists even if I give **every** file in `pub/static` full user/group/world read/write/execute permissions.

The problem appears to be symlinks.  When Magento does its recursive permission check in 

```
#File: setup/src/Magento/Setup/Model/FilePermissions.php
private function checkRecursiveDirectories($directory)
{
    //...
}
```

It appears to resolve any symlinks it finds before checking the final permissions.  This means if there's a symlinked static asset file (**very** common, since that's how Magento 2 handles static assets in developer mode), and the source static asset itself doesn't have the correct permissions, this permissions check will fail.

This seems like the incorrect behavior for a permissions check on `pub/static` files.  If the symlink itself has the correct permissions, this will give Magento the ability to remove/replace the symlink as needed.

**Comment by mazhalai** [comment] 2016-02-09 20:23
Internal tracking ticket MAGETWO-48291

**Comment by chong1227** [comment] 2016-02-21 09:12
did this bug fixed?~~

**Comment by astorm** [comment] 2016-02-21 23:50
@chong1227 I don't know -- shouldn't you'all have tests the prove if that's true or not?  Also, what exactly is the fix?  I don't see a linked a pull request related to this at all?

Or is this just an optics thing where you're try to close out open bug irrespective of whether they're fixed or not?

**Comment by mazhalai** [comment] 2016-02-22 14:24
@astorm @chong1227 this ticket is WIP. It will be closed when it is merged into develop.

**Comment by erikhansen** [comment] 2016-02-29 21:53
I encountered this issue today. The cause of my issue was slightly different than what @astorm described. In my situation, I had a symlink in my `pub/static` directory that was pointing to a non-existent file. Deleting the broken symlink resolved my issue.

I found the broken symlink using this command (from @mttjohnson [Stack Exchange answer](http://magento.stackexchange.com/a/95411/2142)): 

```
find . -type l -exec sh -c "file -b {} | grep -q ^broken" \; -print
```

**Comment by Vinai** [comment] 2016-02-29 21:57
Just a note, find can directly show only broken symlinks with `find -L . -type l`

**Comment by erikhansen** [comment] 2016-03-01 01:24
@Vinai Ah, much more succinct. Thanks for sharing.

**Comment by mazhalai** [comment] 2016-03-08 21:38
@astorm We have merged a fix in the develop branch, hence closing this ticket. Please create a new ticket if issues still arise.

**Closed as completed by mazhalai** 2016-03-08 21:38 UTC
Labels: Issue: Ready for Work, bug report

**Comment by berega** [comment] 2017-02-10 18:47
Although closed I w'd like to comment.
Magento CE 2.1.3 on Windows 10, WAMP64 localhost.  As I run the command
php bin\magento maintenance:allow-ips 127.0.0.1, the ip of my localhost given by the NAT-Router  and the ip of the NAT-Router my probem was sloved.

**Comment by berega** [comment] 2017-02-10 18:48
Sorry: my magento is CE 2.1.3
