### ISSUE TITLE
Console log error on Swagger page in 2.4.3

### ISSUE THREAD

**Issue by EnzoSparacino** [magento/magento2#34223] opened 2021-10-01 14:34 UTC
### Preconditions (*)

1. Magento 2.4.3
2. Swagger module installed

The following console error shows up when navigating to the swagger page on a blank Magento2.4.3: require.config is not a function

This is because requirejs-config block got removed from the layout file for the swagger index page.

An easy fix would be to also add the following line to the layout file, but I don't know whether that is the best solution.

`<referenceBlock name="google.maps.api" remove="true" />`

This block is coming Ui module, and is defined in the default.xml file which results to be loaded on every page.

### Steps to reproduce (*)

1. Go to /swagger endpoint on Magento 2.4.3

### Expected result (*)

1. No console errors

### Actual result (*)

1. ![image](https://user-images.githubusercontent.com/25711335/135637606-adb55af9-3f94-43b3-a9ac-7198d84dcfa0.png)

**Comment by EnzoSparacino** [comment] 2021-10-02 16:26
@magento give me 2.4-develop instance

**Comment by EnzoSparacino** [comment] 2021-10-02 17:35
can be reproduced on clean 2.4-develop instance

**Comment by engcom-Lima** [comment] 2021-10-07 10:22
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment] 2021-10-07 10:42
Hi @EnzoSparacino,

Thank you for reporting the issue.

Verified and able to reproduce this issue on Magento 2.4-develop cloud instance. Attached screenshot below:

<img width="1281" alt="Screenshot 2021-10-07 at 4 04 41 PM" src="https://user-images.githubusercontent.com/60198022/136369200-377afddb-f936-4e09-b770-17e19790e7f7.png">

So based on it, confirming the issue.

Thanks

**Comment by mimou78** [comment] 2022-01-18 06:53
@magento give me 2.4-develop instance

**Comment by jdouay-wide** [comment] 2022-05-25 07:17
Hello @magento , could you please work on it?  we also add this error on Magento 2.4.3-p2
Thanks and best regards
Jeremy

**Comment by EnzoSparacino** [comment] 2023-03-28 13:54
@magento give me 2.4-develop instance

**Comment by EnzoSparacino** [comment] 2023-03-28 14:35
@magento I am working on this

**Comment by EnzoSparacino** [comment] 2023-03-28 14:35
@magento add to contributors team

**Comment by EnzoSparacino** [comment] 2023-03-29 12:04
@magento add to contributors team

**Comment by EnzoSparacino** [comment] 2023-03-29 12:09
@magento I am working on this

**Comment by engcom-Bravo** [comment] 2024-09-04 08:09
Hi @EnzoSparacino,

Thanks for your reporting and collaboration.

We have verified the issue in latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="1427" alt="Screenshot 2024-09-04 at 13 36 13" src="https://github.com/user-attachments/assets/7cb1f304-5208-4870-b54d-bcf284121836">


No console errors

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-09-04 08:09 UTC
Labels: Issue: Confirmed, Component: Swagger, Reproduced on 2.4.x, Priority: P4, Progress: done, Area: APIs
