### ISSUE TITLE
Issue with Sorting by Price in 'Products in Category' Section of Magento Admin

### ISSUE THREAD

**Issue by 77ghjr77** [magento/magento2#38003] opened 2023-09-20 09:23 UTC
### Summary

Hello,

I am using Magento version 2.4.5 and I've encountered a specific issue in the Magento admin panel that I'd like to discuss.

When I navigate to the 'Products in Category' section of any category and view the products under "ALL STORE VIEWS", all the products from all website views are displayed as expected initially. I've attached a screenshot for reference (See: Image 1).

However, when I attempt to sort these products by price, a peculiar behavior is observed:

1. After sorting by price, it seems that only products associated with the default website view are being displayed and sorted. I've included a screenshot of this behavior for clarity (See: Image 2).
 
2. For instance, if there's a product, say Product A, that is exclusively associated with a non-default website, it doesn't show up in the sorted list at all, despite being visible before sorting.

3. My hypothesis is that when sorting by price under "ALL STORE VIEWS", Magento might be unsure which website view's price to consider for a product. As a result, it might default to using the price from the default website view. This could potentially explain why only products from the default website view are displayed post-sorting.

Could you confirm if this is an intended behavior or a known issue in Magento? If it's not the intended behavior, could you guide me on possible solutions or workarounds? Also, is there any official documentation or acknowledged issues related to this in Magento's resources?

I look forward to your insights and assistance.

Thank you.

### Examples

![Image 1](https://github.com/magento/magento2/assets/82484342/b04c964f-1267-4f1a-ac26-8b5c5f622add)
![Image 2](https://github.com/magento/magento2/assets/82484342/264fe6d5-cde2-40e7-8e3d-d579fd889807)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by 77ghjr77** [comment] 2023-09-20 09:27
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-09-21 07:47
@magento give me 2.4-develop instance

**Comment by 77ghjr77** [comment] 2023-09-27 06:01
@engcom-Dash Thank you for your response. However, based on the screenshots and explanation you provided, I feel there might be a misunderstanding regarding the issue I originally described. As previously mentioned, the issue I encountered is that if a product (let's call it Product A) is specifically associated with a "non-default" website, it doesn't appear in the sorted list at all, whereas it appears normally for the default website view.

May I also inquire if the Magento version you used for testing was 2.4.5?

Thank you and looking forward to your clarification.

**Comment by 77ghjr77** [comment] 2023-09-27 06:34
@engcom-Dash Thank you for taking the time to delve into this issue. However, from the screenshots and explanations you've provided, I feel that there might be some nuances of the original problem I described that may not have been fully grasped. As I previously mentioned, the issue I encountered is:
When selecting a particular category, if there's a product (let's call it Product A) that is specifically associated with a "non-default" website, it doesn't appear in the sorted list when I sort by "Price" under "ALL STORE VIEWS".

For testing, here's what needs to be done:
1. The default website is set under STORES > All Stores by choosing one of the Web Sites as the default. So, there should be at least two websites - one default and one non-default.
2. For Product A to be specifically associated with the non-default site, you need to set its 'Categories' field to a specific category in the product edit page, and then select the "non-default website" under 'Product in Websites', and then save.
3. Navigate to the Categories page, select that category under "ALL STORE VIEWS", and then sort by "Price".

Additionally, could you confirm if the Magento version you used for testing is 2.4.5?

**Comment by engcom-Dash** [comment] 2023-09-28 06:28
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-10-03 05:31
Hi @77ghjr77. Thanks for your update.I have tried to reproduce the issue as per your previous comment. Still not able to reproduce it in 2.4 develop instance. It is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base. Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.
Thanks!

**Comment by engcom-Dash** [comment] 2023-10-16 14:04
Hi @77ghjr77 We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.
Thanks!

**Closed as completed** 2023-10-16 14:11 UTC
Labels: Issue: needs update, Reported on 2.4.5
