### ISSUE TITLE
Save and Duplicate page issue

### ISSUE THREAD

**Issue by kingshukdeb** [magento/magento2#34895] opened 2021-12-28 10:23 UTC
### Preconditions (*)

1. 2.3.2 EE

### Steps to reproduce (*)

1. You have created 2 pages.
2. Assign 1 page to only 1 store view and Assign the other one to multiple store views.
3. Go to Admin panel Content -> Pages.
4. Try to "Save & Duplicate" both the pages.

### Expected result (*)

1. We expect we can duplicate both the pages.

### Actual result (*)

1. The page which has only 1 store view got duplicated. everything is fine here.
2. The page which has multiple store views assigned also got duplicated but with an error message `Item (Namespace\VersionsCms\Model\Hierarchy\Node) with the same ID "49" already exists.`
3. If you try to open the duplicated page in the backend it will show the error and wont work.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround.

**Comment by engcom-November** [comment] 2022-01-06 05:38
Verified the issue on Magento 2,4-develop branch having Enterprise edition modules enabled but cannot able to reproduce the issue:
Steps performed:
Magento multi store setup:
Created my test page 1 from admin - Content - Pages - Add New Page and assigned to only default Store view - Save
Created my test page 2 from admin and assigned to multiple store views - Save
Reindex and clear cache
Edit my test page 1 - save and duplicate - No issue
Edit my test page 2  - save and duplicate - No issue
User is able to access both the duplicate pages and edit and enable and save them - No issue.
![image](https://user-images.githubusercontent.com/60198231/148333966-22ba6884-9a1f-4707-8433-c542b6a4592b.png)
@kingshukdeb , kindly recheck the issue on Magento 2.4-develop branch having Enterprise edition modules and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by kingshukdeb** [comment] 2022-01-18 17:33
Can you give a machine where i can check the same?

**Comment by engcom-November** [comment] 2022-01-20 13:20
Hi @kingshukdeb , currently we are not able to get Magento 2.4-develop instance from bot (ongoing issue). 2.4-develop can we installed in local machine via git: https://github.com/magento/magento2/ and Enterprise edition modules can be installed/enabled on top of it. Kindly recheck the behavior on Magento 2.4-develop branch having Enterprise edition modules and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-Hotel** [comment] 2022-02-16 14:08
Dear @kingshukdeb,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-02-16 14:08 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
