### ISSUE TITLE
Deleting products from admin grid

### ISSUE THREAD

**Issue by ajzele** [magento/magento2#1774] opened 2015-09-02 06:23 UTC
Not sure if this is a bug or by design. Under Products > Inventory > Catalog, when I select all products for deletion, it only deletes those visible in the grid current page, see image here https://goo.gl/2ABozD

**Comment by vkorotun** [comment] 2015-09-02 09:08
Hi @ajzele , the issue is fixed now in our dev branch, and will be available soon on public github.

Thank's, for reporting.

**Comment by vladimir-k** [comment] 2015-09-30 15:49
@ajzele, fix has been delivered to develop branch. If something still doesn't work for you, feel free to reopen this issue. Thank you for helping us make Magento better!

**Closed by vladimir-k** 2015-09-30 15:49 UTC
Labels: bug, MX

**Comment by magento-engcom-team** [comment] 2020-08-27 08:10
Hi @ajzele. Thank you for your report. 
The issue has been fixed in magento/magento2#29711 by @Nazar65 in 2.4-develop branch
Related commit(s):
 - [a7a20f8f1ec67aa74f350dfb03d12a7a0061bfc8](https://github.com/magento/magento2/commit/a7a20f8f1ec67aa74f350dfb03d12a7a0061bfc8)
 - [d6de4c43fe3280df8202c2e0c6254328c36d1d49](https://github.com/magento/magento2/commit/d6de4c43fe3280df8202c2e0c6254328c36d1d49)
 - [8793d83717b8a12d565ecd5c6ccd16e59784522d](https://github.com/magento/magento2/commit/8793d83717b8a12d565ecd5c6ccd16e59784522d)
 - [66cc2b1021b4a86575693c769f0dd4bd7b9a890b](https://github.com/magento/magento2/commit/66cc2b1021b4a86575693c769f0dd4bd7b9a890b)
 - [f5ef67e45f924a7e562ad59c38915494fa6ae3c0](https://github.com/magento/magento2/commit/f5ef67e45f924a7e562ad59c38915494fa6ae3c0)
 - [9be9f049ff122611e7c73d92ef5290d699f46ef2](https://github.com/magento/magento2/commit/9be9f049ff122611e7c73d92ef5290d699f46ef2)
 - [0d51e07ad38b44103cec74e4a6b7a2d8178f94de](https://github.com/magento/magento2/commit/0d51e07ad38b44103cec74e4a6b7a2d8178f94de)
 - [7ca91d145e0a0d5f12223062a60398cb60ffd867](https://github.com/magento/magento2/commit/7ca91d145e0a0d5f12223062a60398cb60ffd867)
 - [8340535fdd339677151a74d968ee2e3953c6d95b](https://github.com/magento/magento2/commit/8340535fdd339677151a74d968ee2e3953c6d95b)
 - [7138093d2a91a4c711cc4c19f07a677b02d82774](https://github.com/magento/magento2/commit/7138093d2a91a4c711cc4c19f07a677b02d82774)
 - [62a4eacde00243365c9985cecc3ebaf1f4543a8d](https://github.com/magento/magento2/commit/62a4eacde00243365c9985cecc3ebaf1f4543a8d)

The fix will be available with the upcoming 2.4.2 release.
