### ISSUE TITLE
ValueError: imagecolorsforindex(): Argument #2 ($color) is out of range

### ISSUE THREAD

**Issue by adarshkhatri** [magento/magento2#37890] opened 2023-08-18 02:30 UTC
### Preconditions and environment

- 2.4.4-p1 commerce
- VisualMerchandiser turned on

### Steps to reproduce

Go to any product,
1. Add this image to a product and make it base, small, thumb all
![360-waw28460au](https://github.com/magento/magento2/assets/8390252/fb612747-c23f-47e2-86a7-0a1eacc680fc)
2. Save the product
3. Go to Category edit page in admin and edit the category that above product is assigned to
4. Observe

### Expected result

Page should load without any error.The page

### Actual result

Page breaks while loading. Error thrown on system:

````
ValueError: imagecolorsforindex(): Argument #2 ($color) is out of range in vendor/magento/framework/Image/Adapter/Gd2.php:347
````

### Additional information

The big problem with this is that we don't know which image is throwing the error. Spent good amount of time to pinpoint the product that had this image.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by adarshkhatri** [comment] 2023-08-18 02:30
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-08-18 06:14
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-08-18 08:13
Hi @adarshkhatri,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance with EE edition and the issue is not reproducible.Kindly refer the attached video.


**Steps to reproduce**

- Go to any product,
- Add this image to a product and make it base, small, thumb all
- Save the product
- Go to Category edit page in admin and edit the category that above product is assigned to
- Observe

Page is loading without any errors.

<img width="1507" alt="Screenshot 2023-08-18 at 12 24 29 PM" src="https://github.com/magento/magento2/assets/51680745/7d689c25-cc53-47b1-b95b-29f2b7798866">



https://github.com/magento/magento2/assets/51680745/975dd500-33b0-4107-a418-bc7fba8e5912



Kindly recheck the behaviour on Magento 2.4-develop instance with EE edition and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-08-29 06:06
Hi @adarshkhatri,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/37890#issuecomment-1683538090 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Closed as completed** 2023-09-05 06:05 UTC
Labels: Issue: needs update, Reported on 2.4.4-p1

**Comment by adarshkhatri** [comment] 2023-10-03 05:04
@magento give me 2.4-develop instance

**Comment by adarshkhatri** [comment] 2023-10-03 06:01
https://github.com/magento give me 2.4.6-p2 instance

**Comment by adarshkhatri** [comment] 2023-10-03 06:02
@magento give me 2.4.6-p2 instance

**Comment by adarshkhatri** [comment] 2023-10-03 06:09
@magento give me 2.4.6-p2 instance

**Comment by adarshkhatri** [comment] 2023-10-04 03:34
@magento give me 2.4.6-p2 instance

**Comment by mohammedTBB** [comment] 2023-11-09 15:26
same here, although I can upload the image in the admin but the error appeas in the exception.log and the image does not show in the fronend, also the error appears when throwing the resize command "bin/magento catalog:image:resize".
I have changed the adapter from gd to imagemagick and it works just fine
https://experienceleague.adobe.com/docs/commerce-admin/config/advanced/developer.html#image-processing-settings

**Comment by willbrammer** [comment] 2023-11-20 17:32
I can replicate this on 2.4.6-p3 Magento. Removing all image roles from the image stopped the error.

Nothing with the image appears to be wrong

**Comment by adarshkhatri** [comment] 2023-11-20 22:21
It seems they have made some changes,

https://github.com/magento/magento2/blob/2.4.7-beta2/lib/internal/Magento/Framework/Image/Adapter/Gd2.php#L341

I haven't tested but it seems it will fix the issue.
