### ISSUE TITLE
Backend layout seems broken/botched 

### ISSUE THREAD

**Issue by Asitis** [magento/magento2#4091] opened 2016-04-11 12:06 UTC
**Steps to reproduce**
- Magento 2.0.4
- Running developer mode
- Try to create/edit a page in the admin

**Expected result**
Get to edit the page normally 

**Actual result**
![](http://i.stack.imgur.com/gzKuj.png)

I'm seeing a strange layout-error in my backend. I try to add a new Page and this is what I keep seeing : http://i.stack.imgur.com/NW3Zv.png (the content for each tab get's loaded in the tab-space itself instead of next to it).

There are no console errors, I'm running in developer mode (2.0.4), have cleared the /var/ multiple times as well as reindexed/recompiled the whole installations; no luck.
I might figure it's a problem with the VES PageBuilder plugin, but I've had that installed for a while now, and this problem really just randomly popped up after a refresh. And now it won't go away.

I figured; let's see what goes wrong in the HTML of the page, maybe a tag didn't close or something. But that's the strangest thing; it looks like the content-edit screen is neatly tucked in an `<li>` item as the rest of them.

**Comment by mazhalai** [comment] 2016-04-15 15:59
@Asitis thank you for reporting, we have created MAGETWO-51933 to investigate and fix.

**Comment by anton-huz** [comment] 2016-04-26 09:21
Hi Alex,
We cannot reproduce you issue on Magento CE@2.0.4.
I have no plugin _VES PageBuilder_ to comment issues with it.

Am I right that when you run Magento CE@2.0.3 + VES PageBuilder and after upgrade to @2.0.4 you've got issues?

**Comment by Asitis** [comment] 2016-04-26 09:28
I upgraded from 2.0.2 to 2.0.4 but I've since deleted the VES PageBuilder plugin, and after deleting that the issue hasn't reoccurred. So after all I think this might be a extension bug.

It had me confused when it didn't show before with the plugin, but ever since i removed it it never showed again.

**Comment by anton-huz** [comment] 2016-04-26 09:58
I think you cannot _just delete plugin_ (It could leave cache/configuration after this). I'll discuss with team potential side effects after module removing.

**Comment by anton-huz** [comment] 2016-04-27 11:36
About handling 3rd party extensions:
1. [Uninstall module](http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-uninstall-mods.html#instgde-cli-uninst-mod-uninst)  
   `php bin/magento module:uninstall`
2. Clear cache  
   `php bin/magento cache:flush`

Also if you'll observe such issue in further check for correct markup (hm.. page source). Looks like it was broken somewhere. Any additional _why it occurs_ to _where_ would be handy.

I close the issue as it's not actual any more. If you have any notes feel free to post here.

**Closed as completed by anton-huz** 2016-04-27 11:36 UTC
Labels: Issue: Ready for Work
