### ISSUE TITLE
Product link not working in admin panel

### ISSUE THREAD

**Issue by Dewasi94** [magento/magento2#8865] opened 2017-03-13 11:27 UTC
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by korostii** [comment] 2017-03-15 13:30
"Not working" is a bit vague for a description. Could you please provide the version you use, screenshot of the errors shown (if any) etc. ?
I don't think it's possible to even reproduce whatever issue you're experiencing otherwise (not to mention fixing it)

**Comment by Dewasi94** [comment] 2017-03-15 14:43
Thanks for reply
Now issue has been ressolved.
But I have one doubt that how to install banner slider in magento 2

**Comment by korostii** [comment] 2017-03-16 13:38
If your problem is resolved and was not caused by core code of Magento2, please close this Issue, otherwise please post the solution\workaround you used in case someone else happens to have the same issue. Thanks in advance.

If you have another issue, feel free to create a separate task, although to the best of my knowledge "banner slider" doesn't sound like an out-of-the-box feature of Magento 2 CE. You might require custom code and\or a 3rd party module in order to achieve that.

**Comment by veloraven** [comment] 2017-06-29 13:09
I'm closing this report as the issue was resolved.
If you want to report another one please create new GitHub issue formatted it issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Closed as completed by veloraven** 2017-06-29 13:09 UTC
