### ISSUE TITLE
Can't Place Order from Admin Backend Magento 2.4.3-p2

### ISSUE THREAD

**Issue by mohsinahmed22** [magento/magento2#35516] opened 2022-05-23 09:56 UTC
**Summary of the issue,**
I have multiple store setup trying to create order from admin with same store selected for customer. I when order screen comes up I tried to add a products when i add product it will show some spinner and gone, then no product added to the list, I have to refresh the page, after refreshing the product has been shown to the list. 

### Preconditions (*)

1.  Magento 2.4.3-p2
2.  Php 7.4
3.  Production Mode

### Steps to reproduce (*)

1.  Create Order from Admin backend
2.  Create New Customer
4.  Select Default store 
5.  Press Add Product Button
6.  Select Product and Add selected Products

### Expected result (*)

1. ![image](https://user-images.githubusercontent.com/3263411/169793693-43b558b1-033c-4ad7-a6c0-f8683b8af027.png)
After refreshing the page gird state will be updated.

### Actual result (*)

1. ![image](https://user-images.githubusercontent.com/3263411/169794000-f8c39e85-a253-4b8d-9248-d704130ecd02.png)
After spinner grid dose not update its state

**Comment by mohsinahmed22** [comment] 2022-05-23 13:15
Issue: Format is valid

**Comment by engcom-November** [comment] 2022-05-24 14:50
@mohsinahmed22 ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could able to reproduce the issue with provided steps.
Even after page refresh - grid is updated as expected.
![image](https://user-images.githubusercontent.com/60198231/170065103-bd4c87ab-f1dc-44e7-a301-49c49595b19c.png)
Kindly recheck the issue again on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by mohsinahmed22** [comment] 2022-05-25 07:32
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-06-07 07:39
Hi @mohsinahmed22 ,
We are closing this issue as there has been no latest update on the same. Kindly create new issue / reopen if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-06-07 07:39 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update

**Comment by tuyennn** [comment] 2022-08-19 03:13
@engcom-November I'm facing the exact thesame situation and issue on Magento 2.4.3-p2 EE kindly request the instance and confirm this

**Comment by tuyennn** [comment] 2022-08-19 10:23
Update
--- This problem caused by **Max Session Size in Admin** for anyone facing this, update this number to x10 times for example to fix.

Configuration > System > Security > Max Session Size in Admin
