### ISSUE TITLE
Email Preview is Glitched..

### ISSUE THREAD

**Issue by auteyrose** [magento/magento2#28962] opened 2020-07-01 18:30 UTC
### Preconditions (*)

1. Magento 2.3.2
2. Email Template:  New Template -> Preview Template

### Steps to reproduce (*)

1. Email Templates: "add new template":  New Template -> Preview Template (any email preview will reproduce this glitch)
2. Couldn't send screenshot because there is not an attachment icon.

### Expected result (*)

1. Click [here](https://averyaustin.com/ashdon/admin/email_template/preview/key/af1ff535658ee344d8fe95f4a1d7d35be8bf6c3b71e1b4ec6a8f989e4dc3c490/?form_key=CC9JYsokscg0SI6i&type=2&text=%7B%7Btemplate+config_path%3D%22design%2Femail%2Fheader_template%22%7D%7D%0D%0A%0D%0A%3Cp+class%3D%22greeting%22%3E%7B%7Btrans+%22%25name%2C%22+name%3D%24customer.name%7D%7D%3C%2Fp%3E%0D%0A%3Cp%3E%7B%7Btrans+%22There+was+recently+a+request+to+change+the+password+for+your+account.%22%7D%7D%3C%2Fp%3E%0D%0A%3Cp%3E%7B%7Btrans+%22If+you+requested+this+change%2C+set+a+new+password+here%3A%22%7D%7D%3C%2Fp%3E%0D%0A%0D%0A%3Ctable+class%3D%22button%22+width%3D%22100%25%22+border%3D%220%22+cellspacing%3D%220%22+cellpadding%3D%220%22%3E%0D%0A++++%3Ctr%3E%0D%0A++++++++%3Ctd%3E%0D%0A++++++++++++%3Ctable+class%3D%22inner-wrapper%22+border%3D%220%22+cellspacing%3D%220%22+cellpadding%3D%220%22+align%3D%22center%22%3E%0D%0A++++++++++++++++%3Ctr%3E%0D%0A++++++++++++++++++++%3Ctd+align%3D%22center%22%3E%0D%0A++++++++++++++++++++++++%3Ca+href%3D%22%7B%7Bvar+this.getUrl%28%24store%2C%27customer%2Faccount%2FcreatePassword%2F%27%2C%5B_query%3A%5Btoken%3A%24customer.rp_token%5D%2C_nosid%3A1%5D%29%7D%7D%22+target%3D%22_blank%22%3E%7B%7Btrans+%22Set+a+New+Password%22%7D%7D%3C%2Fa%3E%0D%0A++++++++++++++++++++%3C%2Ftd%3E%0D%0A++++++++++++++++%3C%2Ftr%3E%0D%0A++++++++++++%3C%2Ftable%3E%0D%0A++++++++%3C%2Ftd%3E%0D%0A++++%3C%2Ftr%3E%0D%0A%3C%2Ftable%3E%0D%0A%0D%0A%3Cp%3E%7B%7Btrans+%22If+you+did+not+make+this+request%2C+you+can+ignore+this+email+and+your+password+will+remain+the+same.%22%7D%7D%3C%2Fp%3E%0D%0A%0D%0A%7B%7Btemplate+config_path%3D%22design%2Femail%2Ffooter_template%22%7D%7D&styles=) to see the 1 in length preview screen glitch,=.
2.

### Actual result (*)

1. A preview screen should be a full preview. Not just an inch long preview screen.
2. Couldn't send screenshot because there is not an attachment icon.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by auteyrose** [comment] 2020-07-01 18:34
@magento what information do you need?
<img width="1324" alt="Screen Shot 2020-07-01 at 12 39 05 PM" src="https://user-images.githubusercontent.com/67702380/86279373-898af180-bb9f-11ea-9150-502c001d10bf.png">

**Comment by auteyrose** [comment] 2020-07-01 18:34
There is more to this test email that cannot be seen unless you scroll down inside of the tiny preview window. This is not optimal.

**Comment by swathishs** [comment] 2020-07-02 07:45
@auteyrose : Tested in 2.4 develop instance. I am getting preview correctly. 
Please find the attachment below : 
![image](https://user-images.githubusercontent.com/58288685/86330937-01bbea80-bc66-11ea-85fc-8c33881e7c86.png)

Email preview:
![image](https://user-images.githubusercontent.com/58288685/86330970-0ed8d980-bc66-11ea-8b53-bad322bdb85c.png)

If I am wrong to let me know the steps to reproduce it

**Comment by auteyrose** [comment] 2020-07-06 19:10
This is great if it would work that way on my end and my other staffs. Can you tell me what to do if it continues to not be a full screen preview like yours above?

**Comment by swathishs** [comment] 2020-07-07 03:58
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment] 2020-07-07 03:58
Hi @swathishs. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment] 2020-07-07 03:59
Hi @swathishs, here is your [Magento instance](https://i-28962-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-28962-2-3-5-p1.instances.magento-community.engineering/admin_5eb2](https://i-28962-2-3-5-p1.instances.magento-community.engineering/admin_5eb2)
Login: `a17e6bb4` Password: `7e8eb06120c0`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment] 2020-07-07 06:03
Issue is not reproducible in magento 2.3.5p1 instance
![image](https://user-images.githubusercontent.com/58288685/86723408-7f586f80-c045-11ea-9543-ea41258fe3e4.png)

**Comment by swathishs** [comment] 2020-07-07 06:08
@auteyrose : Since the issue is not reproducible in Magento 2.4 and 2.3.5p1 develop instance. Hence closing the ticket.

I am tester I will verify the issue in Magento 2.4 and 2.3.5p1 to develop an instance.

**Closed as completed by swathishs** 2020-07-07 06:08 UTC
Labels: Issue: Format is valid, Reported on 2.3.2

**Comment by auteyrose** [comment] 2020-07-07 14:23
<img width="1430" alt="Screen Shot 2020-07-07 at 9 22 34 AM" src="https://user-images.githubusercontent.com/67702380/86795704-72cb1b80-c033-11ea-9e5c-8e0cf5d521db.png">

**Comment by auteyrose** [comment] 2020-07-07 14:23
@swathishs today it looks like this.

**Comment by swathishs** [comment] 2020-07-07 14:30
@auteyrose : I think you should upgrade to 2.3.5 p1  or You can Kindly refer https://community.magento.com/ or https://magento.stackexchange.com/
