### ISSUE TITLE
Custom UI Component has wrong order in checkout

### ISSUE THREAD

**Issue by mgeoffray** [magento/magento2#8344] opened 2017-01-31 09:26 UTC
### Preconditions

 - Magento version 2.1.3
 - PHP 7.0.7
 - MySQL 5.7.12

### Steps to reproduce

1. In a custom module add a new UI Component in `Foo/Bar/view/frontend/layout/checkout_index_index.xml`
2. Add it in node `sidebar` > `summary` > `itemsAfter`
```xml
<?xml version="1.0"?>

<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="checkout" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="checkout.root">
            <arguments>
                <argument name="jsLayout" xsi:type="array">
                    <item name="components" xsi:type="array">
                        <item name="checkout" xsi:type="array">
                            <item name="children" xsi:type="array">
                                <item name="sidebar" xsi:type="array">
                                    <item name="children" xsi:type="array">
                                        <item name="summary" xsi:type="array">
                                            <item name="children" xsi:type="array">
                                                <item name="itemsAfter" xsi:type="array">
                                                    <item name="children" xsi:type="array">
                                                        <item name="sample-summary" xsi:type="array">
                                                            <item name="component" xsi:type="string">Foo_Bar/js/sample/summary</item>
                                                            <item name="displayArea" xsi:type="string">summary</item>
                                                            <item name="config" xsi:type="array">
                                                                <item name="template" xsi:type="string">Foo_Bar/sample/summary</item>
                                                            </item>
                                                        </item>
                                                    </item>
                                                </item>
                                            </item>
                                        </item>
                                    </item>
                                </item>
                            </item>
                        </item>
                    </item>
                </argument>
            </arguments>
        </referenceBlock>
    </body>
</page>
```
3. If we add the empty nodes in the original order, it works   
```xml
<item name="totals" xsi:type="array" />
<item name="itemsBefore" xsi:type="array" />
<item name="cart_items" xsi:type="array" />
```
```xml
<?xml version="1.0"?>

<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="checkout" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="checkout.root">
            <arguments>
                <argument name="jsLayout" xsi:type="array">
                    <item name="components" xsi:type="array">
                        <item name="checkout" xsi:type="array">
                            <item name="children" xsi:type="array">
                                <item name="sidebar" xsi:type="array">
                                    <item name="children" xsi:type="array">
                                        <item name="summary" xsi:type="array">
                                            <item name="children" xsi:type="array">
                                                <item name="totals" xsi:type="array" />
                                                <item name="itemsBefore" xsi:type="array" />
                                                <item name="cart_items" xsi:type="array" />
                                                <item name="itemsAfter" xsi:type="array">
                                                    <item name="children" xsi:type="array">
                                                        <item name="sample-summary" xsi:type="array">
                                                            <item name="component" xsi:type="string">Foo_Bar/js/sample/summary</item>
                                                            <item name="displayArea" xsi:type="string">summary</item>
                                                            <item name="config" xsi:type="array">
                                                                <item name="template" xsi:type="string">Foo_Bar/sample/summary</item>
                                                            </item>
                                                        </item>
                                                    </item>
                                                </item>
                                            </item>
                                        </item>
                                    </item>
                                </item>
                            </item>
                        </item>
                    </item>
                </argument>
            </arguments>
        </referenceBlock>
    </body>
</page>
```

### Expected result
1. New UI Component should be displayed after the items list

### Actual result
1. New UI Component will be displayed in top of the items list and not after
![sidebar_wrong_order](https://cloud.githubusercontent.com/assets/1154299/22458803/622e0a2e-e79e-11e6-927c-635d69e99604.png)
2. With the empty nodes
![sidebar_right_order](https://cloud.githubusercontent.com/assets/1154299/22459010/324ffafa-e79f-11e6-86df-679f83d9b7fd.png)

### Comments    
IMO when the XML are merge the order defined in `Foo/Bar/view/frontend/layout/checkout_index_index.xml` is kept. The final merge order will be :   
- `itemsAfter`   
- `totals`
- `itemsBefore`
- `cart_items`
  
That is why it works when is defined with empty nodes.

**Comment by magento-engcom-team** [comment] 2017-10-12 15:03
@mgeoffray, thank you for your report.
We've created internal ticket(s) MAGETWO-81808 to track progress on the issue.

**Comment by RomaKis** [comment] 2017-12-07 14:39
The same issue is here https://github.com/magento/magento2/issues/8421.
Seems like it is not a bug, because this one https://github.com/magento/magento2/issues/8421 was closed as not a bug.

**Comment by mgeoffray** [comment] 2018-01-02 16:19
@RomaKis Hi,  
how this can not be a bug? If I am not wrong in the issue you mentioned it is about missing `sortOrder` field not mandatory nodes like mine.

**Comment by RomaKis** [comment] 2018-01-02 16:49
@mgeoffray, Hi,
the problem is that these items
```
<item name="totals" xsi:type="array" />
<item name="itemsBefore" xsi:type="array" />
<item name="cart_items" xsi:type="array" />
```
don't have `sortOrder` field filled. So you can't put your block where you want.

**Comment by mgeoffray** [comment] 2018-01-02 16:54
@RomaKis OK I understand what do you mean.

My issue is not that I can not put my block where I want, my issue is that I had to add these empty nodes that the nodes themselves can be in the right order.   
My issue is a level above the `sortOrder` node attribute issue. This current issue is about the order of nodes "itemsBefore", "items" and "itemsAfter" and not the order of the elements inside them.

**Comment by RomaKis** [comment] 2018-01-03 12:12
Ok, now I understand. 
I tried to reproduce on my local environment, but seems like on the latest 2.2-develop branch it works fine.

**Comment by mattheo-geoffray** [comment] 2019-08-01 08:00
Is there any news on that issue?

**Comment by engcom-Foxtrot** [comment] 2019-12-19 11:59
Hello @mgeoffray.
Thank you for your report and collaboration.
I am not able to reproduce this issue on the 2.4-develop branch by provided steps.
![изображение](https://user-images.githubusercontent.com/51681487/71171888-85ccf880-2267-11ea-9411-66b8962f526e.png)

I have to close this issue. If you have some additional information, feel free to reopen this issue.
Thanks for your report.

**Closed as completed by engcom-Foxtrot** 2019-12-19 11:59 UTC
Labels: bug report, Area: Frontend, Issue: Clear Description, Issue: Format is valid, Triage: Dev.Experience
