### ISSUE TITLE
Calendar display issue

### ISSUE THREAD

**Issue by gacleg** [magento/magento2#4317] opened 2016-04-26 18:08 UTC
Installed M2.
Using default theme - no theme.
Went to Stores > Configuration > Catalog to select Yes for Use JS Calendar and year range 2016-2018.

See attached pics for calendar settings and how calendar displays.

Calendar display put a "Wk" column on left, does not show all gridelines, and curdate is not highlighted until hover.
![calendar](https://cloud.githubusercontent.com/assets/18035280/14829237/340d389e-0b9f-11e6-9e95-881697604ec1.jpg)
![stores-config-catalog-calendar](https://cloud.githubusercontent.com/assets/18035280/14829236/3409a742-0b9f-11e6-83e7-e19d7ea59b90.jpg)

**Comment by vil11** [comment] 2016-04-29 11:24
@gacleg 

Hi!

We have Calendar with all grid lines present & current date is highlighted without hover.
![1](https://cloud.githubusercontent.com/assets/5585456/14914604/630586e8-0e14-11e6-914b-6e23db50628a.jpg)
Please specify your environment details (OS, browser, Magento version, etc) so that we could determine the reason. **[FYI](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

And what is the issue about the **week counter** column? Which exactly behaviour you expect here?

---

:sunny: Dmytro Vilchynskyi, M2 QA engineer.

**Comment by gacleg** [comment] 2016-04-29 18:08
Hi,

Looks like the gridline missing and not highlighting current date until hove
is a Firefox issue.  I tried in IE and Chrome and no problem.  Also, I did
not know that Week was supposed to display - never saw that before.

Firefox

Magento 2.04

**Comment by vil11** [comment] 2016-05-04 14:06
We still can't reproduce it neither on Win7 (GChrome 50, IE11, MFirefox 45) nor on Mac 10.10 (Safari 9.1) - all the grid lines are present, current day is highlighted without the hover.

Have you flushed Magento cache after the Configs save?
Have you cleared your browser cache?

**Comment by gacleg** [comment] 2016-05-04 16:47
I flushed Magento and browser cache and seems to solve highlight of current day but gridline still not showing, just in FF.  See attached.  Am I able to suppress display of the Wk column?
![calendar1](https://cloud.githubusercontent.com/assets/18035280/15021718/3b670036-11dd-11e6-9a98-ef680f937c81.jpg)

**Comment by vil11** [comment] 2016-05-05 10:28
In order to disable the **week counter** you may go to **/app/code/Magento/Theme/view/frontend/templates/js/calendar.phtml** file & set **showWeek** = false.

But the issue with MFirefox stays unknown...
Try to change yours MFirefox zoom to several custom values in both directions (Ctrl + / Ctrl -) & then back to default state (Ctrl 0).
Which Magento version do you use?
Which MFirefox version do you use?

**Comment by gacleg** [comment] 2016-05-05 17:51
We are using Magento 2.04 FF is 46.0.1.  If I Ctrl + and Ctrl - both look perfect!

Thanks for the help.

**Comment by piotrekkaminski** [comment] 2016-05-14 20:03
Anyone else experiencing this? 
@gacleg are you getting any errors on the Firefox dev console?

**Comment by MomotenkoNatalia** [comment] 2016-07-18 11:02
Hi @gacleg
I'm going to close this issue. Please let me know if you still have an issue.

**Closed as completed by MomotenkoNatalia** 2016-07-18 11:02 UTC
Labels: Progress: needs update, Area: Frontend
