### ISSUE TITLE
Remote Storage is unable to handle file paths differ only in letter case

### ISSUE THREAD

**Issue by tgreeve** [magento/magento2#35534] opened 2022-05-25 03:51 UTC
### Preconditions and environment

1. Magento 2.4.3-p2
2. Remote storage enabled (s3)

### Steps to reproduce

1. Upload a file "logo.jpg" to s3 bucket path s3://[your bucket name]/media/wysiwyg/logo.jpg
2. Upload another file "Logo.jpg" to s3 bucket path s3://[your bucket name]/media/wysiwyg/Logo.jpg
3. Login to Magento CMS
4. Go to CATALOG > Inventory > Products
5. Add Product
6. Try to insert an image into Description
7. You will find "wysiwyg" folder listing fall into infinity loading 
8. You will also find the and ajax api repeatedly return the following response.

```
{
    "error": true,
    "message": "Notice: Undefined index: media\/wysiwyg\/logo.jpg in \/var\/www\/html\/vendor\/magento\/module-remote-storage\/Driver\/Adapter\/Cache\/Generic.php on line 197"
}
```

### Expected result

Magento should load the file list in remote storage folder which contains files differing only with letter case.

### Actual result

The file list cannot be loaded.

### Additional information

The cache layer with unify the cache key to upper case by this line.

[        return $this->getFrontEnd()->load($this->_unifyId($identifier));](https://github.com/magento/magento2/blob/d74bbf7295855f1c798c26d22094816b58b66d83/lib/internal/Magento/Framework/Cache/Frontend/Adapter/Zend.php#L55)

By calling _unifyId function here:
https://github.com/magento/magento2/blob/d74bbf7295855f1c798c26d22094816b58b66d83/lib/internal/Magento/Framework/Cache/Frontend/Adapter/Zend.php#L121-L124

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2022-06-06 12:43
Hello @tgreeve , 
We have tried to reproduce the issue in Magento 2.4-develop branch the issue is not reproducible.
Please refer the below screenshot for the reference;
![Screenshot from 2022-06-06 18-00-55](https://user-images.githubusercontent.com/60198592/172162218-da73fbe1-cd94-4969-b63c-26e5c19e780b.png)
![Screenshot from 2022-06-06 18-03-53](https://user-images.githubusercontent.com/60198592/172162225-3069472f-7c47-43a0-bc42-54e7a69493b1.png)
![Screenshot from 2022-06-06 18-11-43](https://user-images.githubusercontent.com/60198592/172162683-efbc8e8b-306c-4e4d-a392-8bf4fc403315.png)

We have followed the below steps in order to reproduce the issue:
1.Login to Magento CMS
2.Go to CATALOG > Inventory > Products
3.Add Product
4.Try to insert an image into Description
5.File Uploaded Sucessfully

Let us know in case we have missed anything. Thanks

**Comment by engcom-Dash** [comment] 2022-06-17 09:43
@magento give me 2.4-develop instamce

**Comment by engcom-Dash** [comment] 2022-06-22 07:07
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-08-09 09:20
Hello @tgreeve,

Thanks for the report and collaboration!

We have tried to reproduce the issue in Magento 2.4-develop branch but the issue is not reproducible for us. We can see both images in the panel. Please refer to the below screenshot for reference:

![image](https://user-images.githubusercontent.com/51681618/183613000-a136a431-2cfc-4404-91d9-4c7e214eadda.png)

Below is the screenshot from our S3 bucket:

![image](https://user-images.githubusercontent.com/51681618/183613164-cffe8cd1-ef7a-4408-b9c1-846dd81e56b1.png)

Please let us know in case we have missed anything.

Thanks

**Comment by CadenceLabs-AndrewS** [comment] 2022-08-16 00:21
@tgreeve We had a similar issue related to the regex that is parsing out a portion of the path and returning the wrong result due to case.

Take a look at the file
https://github.com/magento/magento2/blob/2.4.3-p2/app/code/Magento/MediaStorage/App/Media.php#L260

The regex will not return the proper path and removes the prefix folders if the filename starts with an uppercase.
`media/catalog/product/cache/e6da45d6sdsd67safaf/f/a/fake_example_file.jpg returns /f/a/fake_example_file.jpg
media/catalog/product/cache/e6da45d6sdsd67safaf/f/a/Fake_example_file.jpg returns /Fake_example_file.jpg
`
See this regex test https://regex101.com/r/CdPOPE/1 to confirm/test your own paths

The Fix: add case-insensitive regex flag 'i' at end of regex pattern after | pipe
`- return preg_replace('|^.*?((?:/([^/])/([^/])/\2\3)?/?[^/]+$)|', '$1', $resizedImagePath);
`
`+ return preg_replace('|^.*?((?:/([^/])/([^/])/\2\3)?/?[^/]+$)|i', '$1', $resizedImagePath);`

**Comment by engcom-Hotel** [comment] 2022-08-23 05:40
Dear @tgreeve,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-08-23 05:40 UTC
Labels: Issue: needs update
