### ISSUE TITLE
Shopping Cart not show up summary if is a registered customer

### ISSUE THREAD

**Issue by salelsol** [magento/magento2#2756] opened 2015-12-18 10:40 UTC
When add a product a not logged customer works fine, but when is a registered customer then shopping cart not show up summary.
![shopping_cart_summary](https://cloud.githubusercontent.com/assets/16081377/11895074/eb7da1ce-a57b-11e5-967b-0afacd216d6a.jpg)
![shopping_cart_guest](https://cloud.githubusercontent.com/assets/16081377/11895112/20c21eaa-a57c-11e5-9d84-4c5d516d88d3.jpg)

**Comment by ishakhsuvarov** [comment] 2015-12-21 09:28
@salelsol We have tried, but could not reproduce the issue described using stock Magento installation on the latest commit of the develop branch.
Please, provide more information, e. g. any settings different from default, branch and commit you are using, etc.

**Comment by ishakhsuvarov** [comment] 2016-01-08 15:08
@salelsol Closing the ticket for now.
Please feel free to reopen if the issue persists.

**Closed as completed by ishakhsuvarov** 2016-01-08 15:08 UTC
Labels: Progress: needs update
