### ISSUE TITLE
Can't create credit memo - free shipping related (Division by zero exception)

### ISSUE THREAD

**Issue by brian-ebizmarts** [magento/magento2#36800] opened 2023-02-02 19:43 UTC
### Preconditions and environment

- Magento version Commerce 2.4.6-beta2

### Steps to reproduce

1. Enable free shipping from Stores > Configuration > Sales > Delivery Methods.
2. Use the following Tax calculation settings:
![calulation settings](https://user-images.githubusercontent.com/46751037/216431744-3c009dff-da3b-4586-ad46-32e2394cd911.png)
4. Use the following display settings (required):
![display settings](https://user-images.githubusercontent.com/46751037/216431857-158ccfab-3b7b-4a21-a48e-60d20ca481a4.png)
6. Flush cache
7. Login on the frontend and place an order with Free shipping.
8. Create the invoice
9. Attempt to create the credit memo.

### Expected result

Credit memo created

### Actual result

The CollectTotals throws the exception "Division by zero".
vendor/magento/module-sales/Model/Order/Creditmemo/Total/Tax.php
Line 139

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-02-08 10:00
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-02-08 12:44
Hi @brian-ebizmarts,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the attached vidoe.

**Steps to reproduce**

1.Enable free shipping from Stores > Configuration > Sales > Delivery Methods.

2.Tax calculation settings:
<img width="1064" alt="Screenshot 2023-02-08 at 6 07 37 PM" src="https://user-images.githubusercontent.com/51680745/217531707-74dff7bb-7080-4001-a974-c23b3511dc1b.png">


3.Use the following display settings (required):

<img width="1185" alt="Screenshot 2023-02-08 at 6 09 14 PM" src="https://user-images.githubusercontent.com/51680745/217532112-701a6e1e-d949-4e31-a7ce-10b36113be58.png">


4.Flush cache
5.Login on the frontend and place an order with Free shipping.
6.Create the invoice
7.Attempt to create the credit memo.



https://user-images.githubusercontent.com/51680745/217532241-7e9dc2c5-4000-4d7b-8e38-32b40f6eb3f2.mov

Error Logs for reference:

<img width="1430" alt="Screenshot 2023-02-08 at 2 36 27 PM" src="https://user-images.githubusercontent.com/51680745/217532651-f217a2ec-781c-4af9-bd18-97d412dc3f7e.png">


We are not able to create the credit memo using free shipping for ordering a product.

It is working fine with other shipping methods.


Hence confirming the issue.

Thanks.

**Comment by yogesh-valiya** [comment] 2023-03-15 14:11
@magento I'm working on this

**Comment by glo71317** [comment] 2023-03-20 06:26
@yogesh-valiya Internal team already raised the PR which is in progress to deliver. Thanks for the contribution!

**Comment by yogesh-valiya** [comment] 2023-03-20 06:56
@glo71317 

1. When I started working on this issue, the issue wasn't assigned to anyone. If internal was working on it, why this wasn't assigned to anyone?
2. If a PR is already in progress, then why it's not linked with this issue?

**Comment by yogesh-valiya** [comment] 2023-03-20 13:41
@glo71317 

https://github.com/magento/magento2/issues/34180#issuecomment-1475908590

See, in the same situation again :disappointed:

**Closed as completed** 2023-04-03 13:31 UTC
Labels: Component: Shipping, Issue: Confirmed, Reproduced on 2.4.x, Priority: P1, Progress: done, Area: Order, Reported on 2.4.6
