### ISSUE TITLE
Grouped Product Quantity Validation Displays Errors for All Inputs When One Input Is Invalid

### ISSUE THREAD

**Issue by allforcode** [magento/magento2#39347] opened 2024-11-08 00:53 UTC
### Preconditions and environment

- Magento Versions
I tested in Magento 2.4.7 and Magento 2.4.7-p2
 
- Description
On the grouped product page, entering a single invalid quantity (e.g., a negative value) causes error messages to appear for all quantity input fields, even if the other inputs have valid values. This behavior creates confusion for users who have correctly entered quantities.

### Steps to reproduce

1. Navigate to a grouped product page.
2. Enter a negative value (e.g., -10) in one of the quantity input fields.
3. Enter valid values (e.g., 6 or 9) in the other quantity input fields.
4. Observe the error messages displayed.

![Cursor_and_Set_of_Sprite_Yoga_Straps](https://github.com/user-attachments/assets/e2895fa3-163e-4a61-8282-48036eef2c52)

### Expected result

Only the input field with an invalid quantity should display an error message.

### Actual result

All input fields display an error message, even if their values are valid.

### Additional information

In Magento 2.4.5, the form validation is handled by `view/frontend/web/product/view/validation.js`, whereas in Magento 2.4.7, it is managed by `lib/web/mage/validation.js`.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-11-08 04:22
Hi @allforcode,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Navigate to a grouped product page.
- Enter a negative value (e.g., -10) in one of the quantity input fields.
- Enter valid values (e.g., 6 or 9) in the other quantity input fields.
- Observe the error messages displayed.


![Group-11-08-2024_09_48_AM](https://github.com/user-attachments/assets/45030c23-0daf-48ce-aef6-711d25c16e40)




All input fields displays error message, even if their values are valid.

Hence Confirming the issue.

Thanks.

**Comment by Mohamed-Asar** [comment] 2024-11-17 06:28
@magento I'm working on this

**Comment by phes71** [comment] 2024-11-19 04:55
this will fix it https://github.com/magento/magento2/commit/95fd74f356652eb19274bf20815893649fafba72

**Comment by engcom-Charlie** [comment] 2024-12-30 10:26
Hi @allforcode,

As mentioned [here](https://github.com/magento/magento2/pull/39377#issuecomment-2565284911), the issue has been resolved now. Closing this issue now, please try to check it on latest 2.4-develop and feel free to reopen it for any further updates.

**Closed as completed by engcom-Charlie** 2024-12-30 10:26 UTC
Labels: Component: Catalog, Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Product, Reported on 2.4.7-p2
