### ISSUE TITLE
Multiple Store Views 2.3 not allowing unique descriptions per store view fields disabled

### ISSUE THREAD

**Issue by importwholesales** [magento/magento2#20154] opened 2019-01-09 20:15 UTC
### Preconditions (*)

1. Magento version 2.3 community
2. CentOS Linux release 7.5.1804 (Core)
3. PHP 7.2.11 (cli) (built: Oct 10 2018 10:00:29)
4. mysql  Ver 14.14 Distrib 5.7.24, for Linux (x86_64) using  EditLine wrapper
5. nginx version: nginx/1.12.2

### Steps to reproduce (*)

1. Install Magento 2.3 via command line composer
2. Run command line install
3. Added 3 websites, 1 store and 1 store view each
4. Add a sku  to 1 store view.  Title, price, description, url and save.
5. Add that sku to another store view by checking the box in product editor.
6. copy the data from 1 store view or default.
7. try editing the sku from each store view. 
Description & short Description boxes are disabled even if you have use default is unchecked. but I can user F12 and remove disabled attributes and those fields save per store view.  Just not editable with unchecked default.

I am not sure if "Assigned Sources" is suppose to be unique between store views but when you change on one, it changes globally.

### Expected result (*)

1. 
![what_should_happen](https://user-images.githubusercontent.com/22501320/50925423-47587800-1420-11e9-935b-bfa855d420df.jpg)

2. I was hoping to edit the sku's fields under each store view uniquely.
I get the sku cannot be changed. 
but descriptions and price should allow changed between each store view

### Actual result (*)

1. 
![what_happens](https://user-images.githubusercontent.com/22501320/50925409-3e67a680-1420-11e9-92d3-c8a19332caff.jpg)

2. When editing a product in a store view.  
description and short description are not editable even if you have use default unchecked.

**Comment by magento-engcom-team** [comment] 2019-01-09 20:16
Hi @importwholesales. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@importwholesales do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-09 20:55
Hi @saphaljha. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by saphaljha** [comment] 2019-01-10 04:39
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-01-10 04:39
Hi @saphaljha. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-01-10 04:39
Hi @saphaljha, here is your [Magento instance](https://i-20154-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20154-2-3-develop.instances.magento-community.engineering/admin](https://i-20154-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-01-10 04:55
Hi @GovindaSharma. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-01-10 05:13
@saphaljha Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-01-10 05:15
@GovindaSharma Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-01-10 05:15
@GovindaSharma Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97537` were created

**Comment by robbie-thompson** [comment] 2019-06-24 17:45
This also seems to be an issue on 2.2.8

**Comment by gauravagarwal1001** [comment] 2020-04-05 08:51
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-05 08:51
Hi @gauravagarwal1001. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-05 08:51
Hi @gauravagarwal1001, here is your [Magento instance](https://i-20154-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-20154-2-4-develop.instances.magento-community.engineering/admin_bbfe](https://i-20154-2-4-develop.instances.magento-community.engineering/admin_bbfe)
Login: `6780da8e` Password: `10650c7d32ba`
Instance will be terminated in up to 3 hours.

**Comment by quterorta** [comment] 2022-11-11 10:19
Couldn't reproduce this Issue on 2.4.5

**Comment by engcom-Bravo** [comment] 2024-05-10 05:57
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-05-13 08:25
Hi @importwholesales,

Thanks for your reporting and collaboration.

Verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="1331" alt="Screenshot 2024-05-13 at 13 54 10" src="https://github.com/magento/magento2/assets/51680745/45ec2ff0-7f29-4bad-834d-103555374605">



We are able to edit the fields.

Hence We are Closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-05-13 08:25 UTC
Labels: Component: Catalog, Issue: Confirmed, Reproduced on 2.3.x, Priority: P2, Severity: S2, Progress: done, Area: Catalog
