### ISSUE TITLE
Password strength indicator shows "No Password" even when a password is entered

### ISSUE THREAD

**Issue by cSkip** [magento/magento2#19071] opened 2018-11-05 17:51 UTC
The password strength indicator shows "No Password" at times when there is a password entered.

### Preconditions (*)
1. Anywhere where the password strength indicator is being used.

2. Customer password settings:
<img width="648" alt="screen shot 2018-11-05 at 2 58 51 pm" src="https://user-images.githubusercontent.com/18623986/48026392-8f4edc00-e10b-11e8-8c75-0e1e7b2d7f4f.png">

Passwords that are too guessable or risky will return a 0 zxcvbnScore see [Here](https://github.com/dropbox/zxcvbn#usage). e.g when "password" is entered as the actual password. 

### Steps to reproduce (*)
1. At the account register page, type "password" in the password field.

### Expected result (*)
1. An expected result would likely be a Weak Password message.

### Actual result (*)
1. 
<img width="779" alt="screen shot 2018-11-05 at 11 46 08 am" src="https://user-images.githubusercontent.com/18623986/48016263-c9f74b00-e0f0-11e8-8e16-7678ddcae289.png">

2.  the message with display "No Password".

In this scenario the issue is that the javascript is not handling a return value of "0" from xcsvbn(password) differently than an empty password.

I am currently running Magento v2.2.5

**Comment by magento-engcom-team** [comment] 2018-11-05 17:51
Hi @cSkip. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@cSkip do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-11-05 19:40
Hi @dimasalamatov. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by dimasalamatov** [comment] 2018-11-05 19:41
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2018-11-05 19:41
Hi @dimasalamatov. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2018-11-05 19:42
Hi @dimasalamatov, here is your [Magento instance](http://34.228.235.121/i-19071-2-2-develop/).
Admin access: [http://34.228.235.121/i-19071-2-2-develop//admin](http://34.228.235.121/i-19071-2-2-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by dimasalamatov** [comment] 2018-11-05 20:51
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2018-11-05 20:51
Hi @dimasalamatov. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by dimasalamatov** [comment] 2018-11-05 20:52
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment] 2018-11-05 20:52
Hi @dimasalamatov. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment] 2018-11-05 20:52
Hi @dimasalamatov, here is your [Magento instance](http://34.228.235.121/i-19071-2-2-develop/).
Admin access: [http://34.228.235.121/i-19071-2-2-develop//admin](http://34.228.235.121/i-19071-2-2-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by cSkip** [comment] 2018-11-05 21:01
Sorry, I forgot to add the current Customer password configuration that was used.

**Comment by dimasalamatov** [comment] 2018-11-05 21:08
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2018-11-05 21:08
Hi @dimasalamatov. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2018-11-05 21:08
Hi @dimasalamatov, here is your [Magento instance](http://34.228.235.121/i-19071-2-3-develop/).
Admin access: [http://34.228.235.121/i-19071-2-3-develop//admin](http://34.228.235.121/i-19071-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2018-11-16 09:43
@swnsma Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96390`, `MAGETWO-96391` were created

**Comment by swnsma** [comment] 2018-11-16 09:45
Fixed with PRs:
2.2-develop: https://github.com/magento/magento2/pull/19073
2.3-develop: https://github.com/magento/magento2/pull/19087

**Closed as completed** 2018-11-19 13:17 UTC
Labels: Issue: Ready for Work, Component: Customer, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
