### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by Lewiscowles1986** [magento/magento2#2100] opened 2015-10-13 13:57 UTC
This is an enhancement proposal to change Magento 2 folder structure, to use a more sensible folder structure At present /pub should be the ***only web root***, but it's not, and that means that there are a number of folders that do not need to face the web, potentially facing the web. This also seems to lead to a // being my store-front during my install when using nginx setup 
***might be a good idea to `str_replace( '//', '/', $url );`*** somewhere in the PHP

**Comment by johnbendi** [comment] 2015-10-14 04:05
Follow the instructions here for your nginx setup:
https://firebearstudio.com/blog/magento-2-nginx-configuration.html

That's a starting point you may need to update it to with more recent settings that you can find on the web.

**Comment by Lewiscowles1986** [comment] 2015-10-15 13:46
https://gist.github.com/Lewiscowles1986/f68dbf82b532838a76ed

It already is working... I was not reporting a problem using, I was proposing an enhancement to simplify the folder structure :wink:

**Comment by davidalger** [comment] 2015-11-10 22:04
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

Also /pub issue is duplicate of #356

**Closed by davidalger** 2015-11-10 22:04 UTC
