### ISSUE TITLE
Error message when dismiss all completed tasks

### ISSUE THREAD

**Issue by dzdaniel** [magento/magento2#36048] opened 2022-08-29 10:34 UTC
### Preconditions and environment

- Magento version 2.4.4

### Steps to reproduce

1. Update products in bulk from product grid
2. Go to bulk action logs and wait until all action success
3. Click to View Details in system message

### Expected result

The system message should show without error.

### Actual result

It's showing error message 
![image](https://user-images.githubusercontent.com/62588396/187182229-4ffc184d-f653-4ec7-883a-63547cbcfd21.png)
And the log in system.log is
`[2022-08-29T10:03:41.237871+00:00] .CRITICAL: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0f2687a6-7b98-4f4d-9847-8cf7afdcf7c1' for key 'magento_acknowledged_bulk.MAGENTO_ACKNOWLEDGED_BULK_BULK_UUID', query was: INSERT  INTO `magento_acknowledged_bulk` (`bulk_uuid`) VALUES (?) [] []`

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by UglyWillDuckling** [comment] 2022-08-30 09:41
I can confirm being able to reproduce this issue on one of our projects as well. I will update with more info.

**Comment by UglyWillDuckling** [comment] 2022-08-30 11:08
From what I can tell the issue is happening because of jQuery and the way it is deciding if an error occurred.
Basically, the response from Magento is empty and jquery expects json. This throws a parsing error.

It should be quite easy to fix by just adding an empty json result but I still need to try this.

**Comment by engcom-Hotel** [comment] 2022-08-30 14:20
Duplicate of https://github.com/magento/magento2/issues/35971

**Comment by engcom-Hotel** [comment] 2022-08-30 14:24
Reopening this issue. The issue was mistakenly closed.

**Comment by engcom-Delta** [comment] 2022-09-09 09:35
:heavy_check_mark: Issue confirmed

Issue got reproduced in **2.4-develop** branch.

**Description:**

While updating the product in bulk , In bulk action logs it showing system message with the error. 

**Pre-requisite:**

   2.4-develop

**Steps to reproduce:**

1. Update products in bulk from product grid

2. Opened bulk action logs and clicked on View Details in system message

3. checked in system.log file


**Expected result:**
 
   Only system message is display without the error. 

**Actual result:**
 
 System message displayed along with an error

**Screenshots:**
1. Update products in bulk from product grid
<img width="1420" alt="Screenshot 2022-09-09 at 2 31 46 PM" src="https://user-images.githubusercontent.com/51681379/189315868-53ac1f27-b821-4289-8e61-9470fb695c57.png">

<img width="1039" alt="Screenshot 2022-09-09 at 2 32 22 PM" src="https://user-images.githubusercontent.com/51681379/189315912-22a98605-c2e8-447c-a564-240072f04a21.png">

2. Opened bulk action logs and clicked on View Details in system message
<img width="1423" alt="Screenshot 2022-09-09 at 2 33 09 PM" src="https://user-images.githubusercontent.com/51681379/189316224-fe738a83-f049-48db-8623-b8fea184a24f.png">
<img width="1370" alt="Screenshot 2022-09-09 at 2 33 32 PM" src="https://user-images.githubusercontent.com/51681379/189316281-1f0937f4-8eff-4ad7-8254-953bbdb25ef9.png">

we can see the system message with an error .

3. checked in system.log file

<img width="1282" alt="Screenshot 2022-09-09 at 2 41 07 PM" src="https://user-images.githubusercontent.com/51681379/189316486-9b850abc-66ef-45c8-9756-cb0f0aa005b3.png">

[2022-09-09T09:03:21.463071+00:00] main.CRITICAL: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '673933f0-4bce-40c0-a75b-dc02b9cf11db' for key 'magento_acknowledged_bulk.MAGENTO_ACKNOWLEDGED_BULK_BULK_UUID', query was: INSERT  INTO `magento_acknowledged_bulk` (`bulk_uuid`) VALUES (?) [] []


Hence, confirming the issue.

Thanks.

**Comment by sdaugherty-rp** [comment] 2022-09-29 16:40
@magento I am working on this

**Comment by sdaugherty-rp** [comment] 2022-09-29 16:40
@magento add to contributors team

**Comment by sdaugherty-rp** [comment] 2022-09-29 16:41
@magento I am working on this

**Comment by sdaugherty-rp** [comment] 2022-09-29 16:46
> From what I can tell the issue is happening because of jQuery and the way it is deciding if an error occurred. Basically, the response from Magento is empty and jquery expects json. This throws a parsing error.
> 
> It should be quite easy to fix by just adding an empty json result but I still need to try this.

Spot on. Added this PR/Commit: https://github.com/magento/magento2/pull/36221/commits/f7570c22723cc67be6fae88d14419ec86a36a586

Reused similar approach in `vendor/magento/module-asynchronous-operations/Controller/Adminhtml/Bulk/Retry.php` to add non-empty json response:

![image](https://user-images.githubusercontent.com/101587900/193090332-1a9e5e9b-a8ee-4feb-b6f5-e4d3c51aabc6.png)

**Comment by FadedOut** [comment] 2023-01-03 20:29
> > From what I can tell the issue is happening because of jQuery and the way it is deciding if an error occurred. Basically, the response from Magento is empty and jquery expects json. This throws a parsing error.
> > It should be quite easy to fix by just adding an empty json result but I still need to try this.
> 
> Spot on. Added this PR/Commit: [f7570c2](https://github.com/magento/magento2/commit/f7570c22723cc67be6fae88d14419ec86a36a586)
> 
> Reused similar approach in `vendor/magento/module-asynchronous-operations/Controller/Adminhtml/Bulk/Retry.php` to add non-empty json response:
> 
> ![image](https://user-images.githubusercontent.com/101587900/193090332-1a9e5e9b-a8ee-4feb-b6f5-e4d3c51aabc6.png)

Just wish to report that this commit seemed to solve the issue for me. 👍🙂 Many thanks! It was annoying clicking the OK button after every X esp if there are many X to click (dismiss).

**Comment by mfickers** [comment] 2023-05-17 08:40
I can confirm that this commit fixes the issue.

@sdaugherty-rp could you please create a PR for this, so that this fix can be merged into the main code base?

**Comment by hostep** [comment] 2023-06-03 08:25
@mfickers: I have the feeling that this might have been fixed in Magento 2.4.6 by [ACP2E-1245: "Something went wrong" error is displayed when clearing the completed bulk tasks.](https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-1245&type=commits) (the commit are a mess, but I think this might be the merge commit: https://github.com/magento/magento2/commit/fb586ea689792a3f3c8a9f4b9e6230dc20dda9a6)

Maybe you can test this as well and let us know if this fixed it as well in your case, so we can then close this issue?

**Comment by FadedOut** [comment] 2023-06-05 06:37
This was indeed properly fixed in 2.4.6 without any manual file changes. Which merge fixed it that I'm not sure of though.

**Comment by yurii-zhuravlov** [comment] 2023-07-07 18:21
> @mfickers: I have the feeling that this might have been fixed in Magento 2.4.6 by [ACP2E-1245: "Something went wrong" error is displayed when clearing the completed bulk tasks.](https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-1245&type=commits) (the commit are a mess, but I think this might be the merge commit: [fb586ea](https://github.com/magento/magento2/commit/fb586ea689792a3f3c8a9f4b9e6230dc20dda9a6))
> 
> Maybe you can test this as well and let us know if this fixed it as well in your case, so we can then close this issue?

I can confirm that this commit fixes the issue. I've created composer patch based on this commit changes and it works great for Magento 2.4.5-p1

**Comment by hostep** [comment] 2023-07-09 14:36
Thanks for the confirmations guys, I think we should close this ticket now? @dzdaniel or @engcom-Delta or @engcom-Hotel, can one of you take care of closing the ticket? Thanks!

**Closed as completed** 2023-07-10 09:34 UTC
Labels: Issue: Confirmed, Component: Ui, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Admin UI, Reported on 2.4.4

**Comment by hostep** [comment] 2023-07-10 13:51
Thanks @engcom-Bravo, can you also close https://github.com/magento/magento2/pull/36221 then?
