### ISSUE TITLE
INVENTORY BUG. Products not appearing at frontend

### ISSUE THREAD

**Issue by davirs** [magento/magento2#38570] opened 2024-04-02 19:45 UTC
### Preconditions and environment

- Magento 2.4.6-p3 
- This error is not easy to reproduce, but it occurs in all my stores that are in production.
Basically, as products are changed in Magento directly via panel or API, this error occurs in part of the changed products. I couldn't identify any patterns.

### Steps to reproduce

1 - Register/update hundreds of configurable products and their aggregated products. In my case, I use API to register, change and set stock, but I was able to simulate directly in the Magento panel.
2 - Some of these registered products are in stock and all their settings are normal like any other product, they are enabled but will not appear on the frontend.
3 - You can clear the indexes, it won't solve it.
4 - You can clear all caches, it won't solve it.
5 - You can make changes within the product and save, it won't solve it.
6 - The bugged product will not appear in the frontend in any way.

### Expected result

Any registered or modified product that is in stock and enabled should appear on the frontend normally.

![Screenshot_24](https://github.com/magento/magento2/assets/4355062/aec9b56b-6cfc-4fcd-b059-dc0640e76da0)

### Actual result

Currently, some of the updated products have this problem, they don't appear in the frontend at all!

![Screenshot_20](https://github.com/magento/magento2/assets/4355062/3aeaf330-e1df-498e-a542-071d72f60bda)

![Screenshot_21](https://github.com/magento/magento2/assets/4355062/c8a4fd9d-922b-4344-bdb5-29ad452e7051)

### Additional information

I've read several issues about similar cases, I've tried applying several fixes but none of them helped me solve the problem.

issue examples:
https://github.com/magento/magento2/issues/35724
https://github.com/magento/inventory/issues/3350

I discovered in these cases that I am reporting the product does not appear at all in the frontend, it is possible to "force" this BUG to be circumvented in two ways:

1 - Unlink all products from the configurations within the configurable product, save the product, link all configurations again within the configurable product and save the product.
After completing this step by step process, the product appears instantly on the frontend, without having to make any edits to any of the products.

![Screenshot_23](https://github.com/magento/magento2/assets/4355062/094d74ab-698b-4713-9b1f-0be956f8b17a)

2 - Update the "control stock" field within the products. Just go to the "Advanced Inventory" option within the product registration, uncheck the "Use Config Settings" box and set "manage stock = yes" and then save the product.
After completing this step by step process, the product appears instantly on the frontend, without having to make any edits to any of the products.

![Screenshot_22](https://github.com/magento/magento2/assets/4355062/0282716f-951f-4c5f-a410-30912d140b1c)

The big problem is the large flow of products! It's impossible to take care of one by one if Magento is working as it should...
All my 4 magento 2.4.6-p3 stores have this same problem in production.

Is there actually a patch or something concrete that solves this problem?

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2024-04-04 11:03
Hello @davirs,

Thanks for the report and collaboration!

We have tried to reproduce the issue in Magento 2.4.6-p3 and the latest development branch i.e. 2.4-develop but the issue is not reproducible for us. We have 640 Configurable Products, and 39360 Simple Products in our instance. We have followed the below steps:

1. Setup Vanilla Magento instance
2. Create products using [Magento performance toolkiit](https://experienceleague.adobe.com/en/docs/commerce-operations/configuration-guide/cli/generate-data), we have used `Medium` profile.
3. Try to edit a configurable product mark it as out of stock and check the value `cataloginventory_stock_status.stock_status`, it is set to `0`
4. Try to get the product from the frontend, it is showing `out of stock`, which is expected.
5. Edit the same product to make it `in-stock` and check the value `cataloginventory_stock_status.stock_status`, it is set to `1`
6. In the frontend the issue is visible with `in-stock` status.

I suggest you please check the error log, you may get some more information on this issue. Also, have you tried the patch provided in this [comment](https://github.com/magento/magento2/issues/35724#issuecomment-1246597165)?

Thanks

**Comment by engcom-Hotel** [comment] 2024-04-19 05:51
Dear @davirs,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we're assuming it's been resolved and will be closing it. Feel free to open a new ticket or reopen this one if you require further assistance.

Regards

**Closed as completed by engcom-Hotel** 2024-04-19 05:51 UTC
Labels: Issue: needs update, Reported on 2.4.6-p3

**Comment by LaurensGoedel** [comment] 2024-11-25 10:09
We have exactly the same issue. And after some googling, more people are experiencing this issue. 
@davirs did you find a solution or work-around for this?

**Comment by MLisiecki** [comment] 2024-12-04 12:42
The best I have found is:

UPDATE cataloginventory_stock_status INNER JOIN catalog_product_entity ON product_id=catalog_product_entity.entity_id SET stock_status = 1 WHERE type_id = 'configurable';

**Comment by engcom-Hotel** [comment] 2024-12-09 12:45
Hello @davirs,

Actually, we have closed this issue because we are unable to reproduce this issue. Please refer to this https://github.com/magento/magento2/issues/38570#issuecomment-2036859379. 

Let us know if we missed anything.

**Comment by davirs** [comment] 2024-12-09 14:37
@engcom-Hotel Okay, but how can you test if this error occurs during an API integration? Did you connect a real ERP with real data? Registrations, updates, deletions?

As I said, this problem is real. I have already connected Magento to 3 different ERPs, and all 3 have the same problem.

I couldn't identify what is causing the problem here, because everything works normally. The ERP makes the requests normally, and doesn't give any kind of error. Magento simply doesn't "recognize" the information that was saved.

So I reported a real problem that impacts all users of the platform. Whether you can test it is another matter... In my opinion, it is a serious API problem.

**Comment by ZenDevDarioVranjkovic** [comment] 2024-12-13 13:34
Hello, I have same problem also. For configurable product if I set first time that product is out of stock and again move to stock system will not show product on frontend, show info that product is out of stock
