### ISSUE TITLE
Adding a custom EAV entity type can cause mysql integrity constraint violations when reinitializing the database

### ISSUE THREAD

**Issue by hostep** [magento/magento2#10398] opened 2017-08-01 19:54 UTC
### Preconditions
1. Tested with Magento CE 2.1.7 and Magento 2.2.0-preview branch (commit 22b7543a4c8)
2. PHP 7.0.20
3. MariaDB 10.2.7

### Steps to reproduce
1. Setup a new Magento installation
2. Create a module which introduces a new Entity Type, make sure the name of the module comes alphabetically before 'Magento_', I've used 'A_B' (see the bottom for a small example)
3. Run: `bin/magento setup:install` **with** the `--cleanup-database` flag

### Expected result
1. Installation runs without errors

### Actual result
1. During installation of the Magento_Sales module, an error is thrown:
```
...
[Progress: 282 / 470]
Module 'Magento_Sales':
Installing data...

  [Magento\Framework\DB\Adapter\DuplicateException]
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5' for key 'PRIMARY', query was: INSERT INTO `eav_entity_type` (`entity_type_code`, `entity_model`, `attribute_model`, `entity_table`, `value_table_prefix`, `enti
  ty_id_field`, `increment_model`, `increment_per_store`, `increment_pad_length`, `increment_pad_char`, `additional_attribute_table`, `entity_attribute_collection`, `entity_type_id`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
````

### Discussion
This problem happens because certain Magento modules (Magento_Customer, Magento_Catalog & Magento_Sales) use a hardcoded entity_type_id in their database installation scripts.
In this case, the custom module gets installed **before** the Magento_Sales module and adds an eav entity type with id '5'. The Magento_Sales module then tries to install itself, but fails to do, because it [wants to use id '5' as well](https://github.com/magento/magento2/blob/65c0b93a337f1fd5829881750fd2af545a9b79f2/app/code/Magento/Sales/Setup/SalesSetup.php#L27), but this one is already taken by the custom module.

We can fix it by adding 'Magento_Sales' in the sequence of our custom module, but this doesn't make much sense to me, since the custom module is not depending on the 'Magento_Sales' module for any functionality.

Is this considered a bug, or should something like this be better documented?

I'm wondering why the Magento_Customer and Magento_Catalog module's setups are being executed before our custom module though, if somehow Magento_Sales could also be "automagically" be executed before a custom module who wants to create an Entity Type that would fix the bug, but this is probably not so easy?

### Example module files
- `app/code/A/B/registration.php`:
```php
<?php

use \Magento\Framework\Component\ComponentRegistrar;

ComponentRegistrar::register(ComponentRegistrar::MODULE, 'A_B', __DIR__);
```

- `app/code/A/B/etc/module.xml`:
```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="A_B" setup_version="1.0.0">
        <sequence>
            <module name="Magento_Eav"/>
            <!-- Uncomment this to fix the issue -->
            <!-- <module name="Magento_Sales"/> -->
        </sequence>
    </module>
</config>
```

- `app/code/A/B/Model/ResourceModel/Example.php`:
```php
<?php

namespace A\B\Model\ResourceModel;

use \Magento\Eav\Model\Entity\AbstractEntity;

class Example extends AbstractEntity
{

}
```

- `app/code/A/B/Setup/ExampleSetup.php`:
```php
<?php

namespace A\B\Setup;

use \Magento\Eav\Setup\EavSetup;

class ExampleSetup extends EavSetup
{
    public function getDefaultEntities()
    {
        return [
            'example_entity' => [
                'entity_model' => 'A\B\Model\ResourceModel\Example',
                'table'        => 'example_entity',
                'attributes'   => [
                    'some_attribute' => [
                        'type' => 'varchar'
                    ]
                ]
            ]
        ];
    }
}
```

- `app/code/A/B/Setup/InstallData.php`:
```php
<?php

namespace A\B\Setup;

use \Magento\Framework\Setup\InstallDataInterface;
use \Magento\Framework\Setup\ModuleDataSetupInterface;
use \Magento\Framework\Setup\ModuleContextInterface ;

class InstallData implements InstallDataInterface
{
    private $exampleSetupFactory;

    public function __construct(ExampleSetupFactory $exampleSetupFactory)
    {
        $this->exampleSetupFactory = $exampleSetupFactory;
    }

    public function install(ModuleDataSetupInterface $setup, ModuleContextInterface $context)
    {
        $this->exampleSetupFactory->create(['setup' => $setup])->installEntities();
    }
}
```

**Comment by magento-engcom-team** [comment] 2017-09-28 10:30
@hostep, thank you for your report.
We've created internal ticket(s) MAGETWO-80274 to track progress on the issue.

**Comment by engcom-Charlie** [comment] 2019-12-13 10:34
Hello @hostep 
Thank you for contribution and collaboration!

We are not able to reproduce this issue on the latest 2.4-develop branch by provided steps.
**Result:**

1. No error while `Magento_Sales` installing
![1](https://user-images.githubusercontent.com/51680850/70793826-e0b4aa80-1da4-11ea-91fe-d32bf970bf23.png)

2. Magento installation complete
![2](https://user-images.githubusercontent.com/51680850/70793829-e4483180-1da4-11ea-9423-87c79d77cbf1.png)


We are closing this issue due to branch `2.2-develop` was closed and
> Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.

**Closed as completed by engcom-Charlie** 2019-12-13 10:34 UTC
Labels: Issue: Clear Description, Issue: Format is valid

**Comment by hostep** [comment] 2021-01-04 16:18
This was most likely fixed as a side-effect of https://github.com/magento/magento2/pull/21020 or https://github.com/magento/magento2/pull/21423 where the sort order of modules has been changed so that Magento modules are now **always** loaded first and all the rest later. It wouldn't surprise me if that change will get reverted on day or another because it doesn't feel right in my opinion. If that happens one day, then this issue will start happening again.
Anyway, just leaving this comment behind in case this starts happening again in the future some day.
