### ISSUE TITLE
Can't install Magento 2.1.6.

### ISSUE THREAD

**Issue by MaximKitsenko** [magento/magento2#9740] opened 2017-05-23 13:53 UTC
I'm trying to install magento 2.1.6. ce

### Preconditions

1.   SystemInfo: `PHP Version 5.6.18-1+deb.sury.org~trusty+1
System	Linux max-VirtualBox 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64
Server API	Apache 2.0 Handler
Virtual Directory Support	disabled
Configuration File (php.ini) Path	/etc/php5/apache2
Loaded Configuration File	/etc/php5/apache2/php.ini
Scan this dir for additional .ini files	/etc/php5/apache2/conf.d
Additional .ini files parsed	/etc/php5/apache2/conf.d/05-opcache.ini, /etc/php5/apache2/conf.d/10-pdo.ini, /etc/php5/apache2/conf.d/20-curl.ini, /etc/php5/apache2/conf.d/20-gd.ini, /etc/php5/apache2/conf.d/20-intl.ini, /etc/php5/apache2/conf.d/20-json.ini, /etc/php5/apache2/conf.d/20-mcrypt.ini, /etc/php5/apache2/conf.d/20-mysql.ini, /etc/php5/apache2/conf.d/20-mysqli.ini, /etc/php5/apache2/conf.d/20-pdo_mysql.ini, /etc/php5/apache2/conf.d/20-readline.ini, /etc/php5/apache2/conf.d/20-xsl.ini
PHP API	20131106
PHP Extension	20131226
Zend Extension	220131226
Zend Extension Build	API220131226,NTS
PHP Extension Build	API20131226,NTS
Debug Build	no
Thread Safety	disabled
Zend Signal Handling	disabled
Zend Memory Manager	enabled
Zend Multibyte Support	provided by mbstring
IPv6 Support	enabled
DTrace Support	enabled
Registered PHP Streams	https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, phar, zip
Registered Stream Socket Transports	tcp, udp, unix, udg, ssl, sslv3, tls, tlsv1.0, tlsv1.1, tlsv1.2
Registered Stream Filters	zlib.*, bzip2.*, convert.iconv.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, mcrypt.*, mdecrypt.*`

### Steps to reproduce

1.  get `Magento-CE-2.1.6-2017-03-29-12-40-05` 
2.  deploy, with rwxrwxrwx (just for developing), start installer

### Expected result

1.  Magento should be installed

### Actual result

1.  Magento installation stucks on 73%, and didn't changed duing tfew hours
install log:
`Starting Magento installation:
File permissions check...

Required extensions check...

Enabling Maintenance Mode...

Installing deployment configuration...

Installing database schema:
Schema creation/updates:
Module 'Magento_Store':
Installing schema... 

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':
Installing schema... 

Module 'Magento_Theme':
Installing schema... 

Module 'Magento_Backend':

Module 'Magento_Backup':

Module 'Magento_Eav':
Installing schema... 

Module 'Magento_Customer':
Installing schema... Upgrading schema... 

Module 'Magento_BundleImportExport':

Module 'Magento_CacheInvalidate':

Module 'Magento_AdminNotification':
Installing schema... 

Module 'Magento_Indexer':
Installing schema... 

Module 'Magento_CatalogImportExport':

Module 'Magento_Cms':
Installing schema... Upgrading schema... 

Module 'Magento_Rule':

Module 'Magento_Catalog':
Installing schema... Upgrading schema... 

Module 'Magento_Search':
Installing schema... Upgrading schema... 

Module 'Magento_CatalogUrlRewrite':
Installing schema... 

Module 'Magento_Widget':
Installing schema... 

Module 'Magento_Quote':
Installing schema... Upgrading schema... 

Module 'Magento_CheckoutAgreements':
Installing schema... Upgrading schema... 

Module 'Magento_SalesSequence':
Installing schema... 

Module 'Magento_CmsUrlRewrite':

Module 'Magento_Config':
Installing schema... 

Module 'Magento_ConfigurableImportExport':

Module 'Magento_Msrp':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':
Installing schema... 

Module 'Magento_CurrencySymbol':

Module 'Magento_Bundle':
Installing schema... Upgrading schema... 

Module 'Magento_CustomerImportExport':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Magento_Authorization':
Installing schema... 

Module 'Magento_Downloadable':
Installing schema... 

Module 'Magento_ImportExport':
Installing schema... Upgrading schema... 

Module 'Magento_Payment':

Module 'Magento_Email':
Installing schema... 

Module 'Magento_User':
Installing schema... Upgrading schema... 

Module 'Magento_Fedex':

Module 'Magento_Sales':
Installing schema... Upgrading schema... 

Module 'Magento_CatalogInventory':
Installing schema... 

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':
Installing schema... 

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':

Module 'Magento_DownloadableImportExport':

Module 'Magento_Checkout':

Module 'Magento_Security':
Installing schema... Upgrading schema... 

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_MediaStorage':

Module 'Magento_CatalogRule':
Installing schema... Upgrading schema... 

Module 'Magento_Multishipping':

Module 'Magento_ConfigurableProduct':
Installing schema... 

Module 'Magento_Newsletter':
Installing schema... 

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':
Installing schema... Upgrading schema... 

Module 'Magento_PageCache':

Module 'Magento_Captcha':
Installing schema... 

Module 'Magento_Vault':
Installing schema... 

Module 'Magento_Persistent':
Installing schema... 

Module 'Magento_ProductAlert':
Installing schema... 

Module 'Magento_ProductVideo':
Installing schema... 

Module 'Magento_Authorizenet':

Module 'Magento_Reports':
Installing schema... 

Module 'Magento_RequireJs':

Module 'Magento_Review':
Installing schema... 

Module 'Magento_Rss':

Module 'Magento_CatalogRuleConfigurable':

Module 'Magento_Paypal':
Installing schema... 

Module 'Magento_SalesInventory':

Module 'Magento_OfflineShipping':
Installing schema... 

Module 'Magento_GoogleAdwords':

Module 'Magento_SampleData':

Module 'Magento_CatalogSearch':
Installing schema... 

Module 'Magento_Integration':
Installing schema... Upgrading schema... 

Module 'Magento_SendFriend':
Installing schema... 

Module 'Magento_Shipping':

Module 'Magento_Sitemap':
Installing schema... 

Module 'Magento_NewRelicReporting':
Installing schema... 

Module 'Magento_Swagger':

Module 'Magento_Swatches':
Installing schema... 

Module 'Magento_SwatchesLayeredNavigation':

Module 'Magento_Tax':
Installing schema... 

Module 'Magento_TaxImportExport':

Module 'Magento_GiftMessage':
Installing schema... 

Module 'Magento_Translation':
Installing schema... 

Module 'Magento_GoogleOptimizer':
Installing schema... 

Module 'Magento_Ups':

Module 'Magento_UrlRewrite':
Installing schema... 

Module 'Magento_EncryptionKey':

Module 'Magento_Usps':

Module 'Magento_Variable':
Installing schema... 

Module 'Magento_Braintree':

Module 'Magento_Version':

Module 'Magento_Webapi':

Module 'Magento_WebapiSecurity':

Module 'Magento_Weee':
Installing schema... 

Module 'Magento_CatalogWidget':

Module 'Magento_Wishlist':
Installing schema... 

Schema post-updates:
Module 'Magento_Store':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':

Module 'Magento_Theme':

Module 'Magento_Backend':

Module 'Magento_Backup':

Module 'Magento_Eav':

Module 'Magento_Customer':

Module 'Magento_BundleImportExport':

Module 'Magento_CacheInvalidate':

Module 'Magento_AdminNotification':

Module 'Magento_Indexer':
Running schema recurring...

Module 'Magento_CatalogImportExport':

Module 'Magento_Cms':

Module 'Magento_Rule':

Module 'Magento_Catalog':
Running schema recurring...

Module 'Magento_Search':

Module 'Magento_CatalogUrlRewrite':
Running schema recurring...

Module 'Magento_Widget':

Module 'Magento_Quote':

Module 'Magento_CheckoutAgreements':

Module 'Magento_SalesSequence':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_Config':

Module 'Magento_ConfigurableImportExport':

Module 'Magento_Msrp':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':

Module 'Magento_CurrencySymbol':

Module 'Magento_Bundle':
Running schema recurring...

Module 'Magento_CustomerImportExport':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Magento_Authorization':

Module 'Magento_Downloadable':

Module 'Magento_ImportExport':

Module 'Magento_Payment':

Module 'Magento_Email':

Module 'Magento_User':

Module 'Magento_Fedex':

Module 'Magento_Sales':

Module 'Magento_CatalogInventory':
Running schema recurring...

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':

Module 'Magento_DownloadableImportExport':

Module 'Magento_Checkout':

Module 'Magento_Security':

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_MediaStorage':

Module 'Magento_CatalogRule':

Module 'Magento_Multishipping':

Module 'Magento_ConfigurableProduct':
Running schema recurring...

Module 'Magento_Newsletter':

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':

Module 'Magento_PageCache':

Module 'Magento_Captcha':

Module 'Magento_Vault':

Module 'Magento_Persistent':

Module 'Magento_ProductAlert':
Running schema recurring...

Module 'Magento_ProductVideo':

Module 'Magento_Authorizenet':

Module 'Magento_Reports':
Running schema recurring...

Module 'Magento_RequireJs':

Module 'Magento_Review':

Module 'Magento_Rss':

Module 'Magento_CatalogRuleConfigurable':

Module 'Magento_Paypal':

Module 'Magento_SalesInventory':

Module 'Magento_OfflineShipping':

Module 'Magento_GoogleAdwords':

Module 'Magento_SampleData':

Module 'Magento_CatalogSearch':

Module 'Magento_Integration':
Running schema recurring...

Module 'Magento_SendFriend':

Module 'Magento_Shipping':

Module 'Magento_Sitemap':

Module 'Magento_NewRelicReporting':

Module 'Magento_Swagger':

Module 'Magento_Swatches':

Module 'Magento_SwatchesLayeredNavigation':

Module 'Magento_Tax':

Module 'Magento_TaxImportExport':

Module 'Magento_GiftMessage':

Module 'Magento_Translation':

Module 'Magento_GoogleOptimizer':

Module 'Magento_Ups':

Module 'Magento_UrlRewrite':

Module 'Magento_EncryptionKey':

Module 'Magento_Usps':

Module 'Magento_Variable':

Module 'Magento_Braintree':

Module 'Magento_Version':

Module 'Magento_Webapi':

Module 'Magento_WebapiSecurity':

Module 'Magento_Weee':
Running schema recurring...

Module 'Magento_CatalogWidget':

Module 'Magento_Wishlist':
Running schema recurring...

DDL cache cleared successfully

Installing user configuration...

Enabling caches:
Current status:
Array
(
[config] => 1
[layout] => 1
[block_html] => 1
[collections] => 1
[reflection] => 1
[db_ddl] => 1
[eav] => 1
[customer_notification] => 1
[full_page] => 1
[config_integration] => 1
[config_integration_api] => 1
[translate] => 1
[config_webservice] => 1
)

Installing data...
Data install/update:
Module 'Magento_Store':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':
Installing data... 

Module 'Magento_Theme':
Installing data... Upgrading data... 

Module 'Magento_Backend':

Module 'Magento_Backup':

Module 'Magento_Eav':
Installing data... 

Module 'Magento_Customer':
Installing data... Upgrading data... 

Module 'Magento_BundleImportExport':

Module 'Magento_CacheInvalidate':

Module 'Magento_AdminNotification':

Module 'Magento_Indexer':
Installing data... 

Module 'Magento_CatalogImportExport':

Module 'Magento_Cms':
Installing data... Upgrading data... 

Module 'Magento_Rule':

Module 'Magento_Catalog':
Installing data... Upgrading data... 

Module 'Magento_Search':

Module 'Magento_CatalogUrlRewrite':
Installing data... 

Module 'Magento_Widget':
Installing data... 

Module 'Magento_Quote':
Installing data... 

Module 'Magento_CheckoutAgreements':

Module 'Magento_SalesSequence':
Installing data... 

Module 'Magento_CmsUrlRewrite':

Module 'Magento_Config':
Installing data... 

Module 'Magento_ConfigurableImportExport':

Module 'Magento_Msrp':
Installing data... Upgrading data... 

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':

Module 'Magento_CurrencySymbol':

Module 'Magento_Bundle':
Installing data... Upgrading data... 

Module 'Magento_CustomerImportExport':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':
Installing data... 

Module 'Magento_Authorization':
Installing data... 

Module 'Magento_Downloadable':
Installing data... 

Module 'Magento_ImportExport':

Module 'Magento_Payment':

Module 'Magento_Email':

Module 'Magento_User':
Upgrading data... 

Module 'Magento_Fedex':
Installing data... 

Module 'Magento_Sales':
Installing data... Upgrading data... 

Module 'Magento_CatalogInventory':
Installing data... Upgrading data... 

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':
Installing data... Upgrading data... 

Module 'Magento_DownloadableImportExport':

Module 'Magento_Checkout':
Installing data... 

Module 'Magento_Security':

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_MediaStorage':

Module 'Magento_CatalogRule':
Installing data... 

Module 'Magento_Multishipping':

Module 'Magento_ConfigurableProduct':
Installing data... 

Module 'Magento_Newsletter':

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':
Installing data... 

Module 'Magento_PageCache':

Module 'Magento_Captcha':

Module 'Magento_Vault':
Upgrading data... 

Module 'Magento_Persistent':

Module 'Magento_ProductAlert':

Module 'Magento_ProductVideo':

Module 'Magento_Authorizenet':

Module 'Magento_Reports':
Installing data... 

Module 'Magento_RequireJs':

Module 'Magento_Review':
Installing data... 

Module 'Magento_Rss':

Module 'Magento_CatalogRuleConfigurable':

Module 'Magento_Paypal':
Installing data... 

Module 'Magento_SalesInventory':

Module 'Magento_OfflineShipping':

Module 'Magento_GoogleAdwords':

Module 'Magento_SampleData':
Installing data... 

Module 'Magento_CatalogSearch':
Installing data... 

Module 'Magento_Integration':

Module 'Magento_SendFriend':

Module 'Magento_Shipping':

Module 'Magento_Sitemap':

Module 'Magento_NewRelicReporting':

Module 'Magento_Swagger':

Module 'Magento_Swatches':
Installing data... Upgrading data... 

Module 'Magento_SwatchesLayeredNavigation':

Module 'Magento_Tax':
Installing data... Upgrading data... 

Module 'Magento_TaxImportExport':

Module 'Magento_GiftMessage':
Installing data... Upgrading data... 

Module 'Magento_Translation':

Module 'Magento_GoogleOptimizer':

Module 'Magento_Ups':

Module 'Magento_UrlRewrite':

Module 'Magento_EncryptionKey':

Module 'Magento_Usps':
Installing data... 

Module 'Magento_Variable':

Module 'Magento_Braintree':

Module 'Magento_Version':

Module 'Magento_Webapi':

Module 'Magento_WebapiSecurity':

Module 'Magento_Weee':
Installing data...`

log:
`[Tue May 23 09:34:22.717969 2017] [:error] [pid 5694] [client so.me.ip.ad2:57638] PHP Fatal error:  require(): Failed opening required '/var/www/app/bootstrap.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/index.php on line 22, referer: http://so.me.ip.ad:4423/magento-2-1-6-0-ce/setup/
[Tue May 23 09:34:46.204459 2017] [authz_core:debug] [pid 5444] mod_authz_core.c(802): [client so.me.ip.ad2:57647] AH01626: authorization result of Require all granted: granted, referer: http://so.me.ip.ad:4423/magento-2-1-6-0-ce-2/setup/
[Tue May 23 09:34:46.204513 2017] [authz_core:debug] [pid 5444] mod_authz_core.c(802): [client so.me.ip.ad2:57647] AH01626: authorization result of <RequireAny>: granted, referer: http://so.me.ip.ad:4423/magento-2-1-6-0-ce-2/setup/
[Tue May 23 09:34:46.204676 2017] [authz_core:debug] [pid 5444] mod_authz_core.c(802): [client so.me.ip.ad2:57647] AH01626: authorization result of Require all granted: granted, referer: http://so.me.ip.ad:4423/magento-2-1-6-0-ce-2/setup/
[Tue May 23 09:34:46.204720 2017] [authz_core:debug] [pid 5444] mod_authz_core.c(802): [client so.me.ip.ad2:57647] AH01626: authorization result of <RequireAny>: granted, referer: http://so.me.ip.ad:4423/magento-2-1-6-0-ce-2/setup/
[Tue May 23 09:34:46.702163 2017] [authz_core:debug] [pid 5644] mod_authz_core.c(802): [client so.me.ip.ad2:57648] AH01626: authorization result of Require all granted: granted, referer: http://so.me.ip.ad:4423/magento-2-1-6-0-ce/setup/
[Tue May 23 09:34:46.702206 2017] [authz_core:debug] [pid 5644] mod_authz_core.c(802): [client so.me.ip.ad2:57648] AH01626: authorization result of <RequireAny>: granted, referer: http://so.me.ip.ad:4423/magento-2-1-6-0-ce/setup/
[Tue May 23 09:34:46.702310 2017] [authz_core:debug] [pid 5644] mod_authz_core.c(802): [client so.me.ip.ad2:57648] AH01626: authorization result of Require all granted: granted, referer: http://so.me.ip.ad:4423/magento-2-1-6-0-ce/setup/
[Tue May 23 09:34:46.702332 2017] [authz_core:debug] [pid 5644] mod_authz_core.c(802): [client so.me.ip.ad2:57648] AH01626: authorization result of <RequireAny>: granted, referer: http://so.me.ip.ad:4423/magento-2-1-6-0-ce/setup/
[Tue May 23 09:34:46.703437 2017] [:error] [pid 5644] [client so.me.ip.ad2:57648] PHP Warning:  require(/var/www/app/bootstrap.php): failed to open stream: No such file or directory in /var/www/index.php on line 22, referer: http://so.me.ip.ad:4423/magento-2-1-6-0-ce/setup/
[Tue May 23 09:34:46.703485 2017] [:error] [pid 5644] [client so.me.ip.ad2:57648] PHP Fatal error:  require(): Failed opening required '/var/www/app/bootstrap.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/index.php on line 22, referer: http://so.me.ip.ad:4423/magento-2-1-6-0-ce/setup/
[Tue May 23 09:34:46.845593 2017] [authz_core:debug] [pid 5582] mod_authz_core.c(802): [client so.me.ip.ad2:57649] AH01626: authorization result of Require all granted: granted, referer: http://so.me.ip.ad:4423/magento-2-1-6-0-ce-2/setup/
[Tue May 23 09:34:46.845622 2017] [authz_core:debug] [pid 5582] mod_authz_core.c(802): [client so.me.ip.ad2:57649] AH01626: authorization result of <RequireAny>: granted, referer: http://so.me.ip.ad:4423/magento-2-1-6-0-ce-2/setup/
[Tue May 23 09:34:46.845730 2017] [authz_core:debug] [pid 5582] mod_authz_core.c(802): [client so.me.ip.ad2:57649] AH01626: authorization result of Require all granted: granted, referer: http://so.me.ip.ad:4423/magento-2-1-6-0-ce-2/setup/
[Tue May 23 09:34:46.845753 2017] [authz_core:debug] [pid 5582] mod_authz_core.c(802): [client so.me.ip.ad2:57649] AH01626: authorization result of <RequireAny>: granted, referer: http://so.me.ip.ad:4423/magento-2-1-6-0-ce-2/setup/
[Tue May 23 09:34:47.698937 2017] [authz_core:debug] [pid 5276] mod_authz_core.c(802): [client so.me.ip.ad2:57650] AH01626: authorization result of Require all granted: granted, referer: http://so.me.ip.ad:4423/magento-2-1-6-0-ce/setup/
[Tue May 23 09:34:47.698990 2017] [authz_core:debug] [pid 5276] mod_authz_core.c(802): [client so.me.ip.ad2:57650] AH01626: authorization result of <RequireAny>: granted, referer: http://so.me.ip.ad:4423/magento-2-1-6-0-ce/setup/
[Tue May 23 09:34:47.701171 2017] [authz_core:debug] [pid 5276] mod_authz_core.c(802): [client so.me.ip.ad2:57650] AH01626: authorization result of Require all granted: granted, referer: http://so.me.ip.ad:4423/magento-2-1-6-0-ce/setup/
[Tue May 23 09:34:47.701250 2017] [authz_core:debug] [pid 5276] mod_authz_core.c(802): [client so.me.ip.ad2:57650] AH01626: authorization result of <RequireAny>: granted, referer: http://so.me.ip.ad:4423/magento-2-1-6-0-ce/setup/
[Tue May 23 09:34:47.701544 2017] [:error] [pid 5276] [client so.me.ip.ad2:57650] PHP Warning:  require(/var/www/app/bootstrap.php): failed to open stream: No such file or directory in /var/www/index.php on line 22, referer: http://so.me.ip.ad:4423/magento-2-1-6-0-ce/setup/
[Tue May 23 09:34:47.701599 2017] [:error] [pid 5276] [client so.me.ip.ad2:57650] PHP Fatal error:  require(): Failed opening required '/var/www/app/bootstrap.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/index.php on line 22, referer: http://so.me.ip.ad:4423/magento-2-1-6-0-ce/setup/
`

**Comment by tsifra** [comment] 2017-05-23 18:16
This happened with my server also. was just solved for me just by another try.

**Comment by MaximKitsenko** [comment] 2017-05-24 11:34
@tsifra  thanks, but i tried 3 times, and issue was not solved

**Comment by dmitriyprime** [comment] 2017-07-17 08:40
Hi, @MaximKitsenko.  Unfortunately, I could not reproduce the issue as you described it. Is this problem actual for you or we can close it?

**Comment by MaximKitsenko** [comment] 2017-07-21 09:26
@dmitriyprime yes, the problem is actual. Moreover, i'm not alone
https://magento.stackexchange.com/questions/92976/installation-hangs-while-installing-data
https://magento.stackexchange.com/questions/156221/magento-2-install-stuck-at-73
https://stackoverflow.com/questions/35218372/magento-2-0-2-installation-on-shared-server-stuck-at-66/44071968#44071968
https://stackoverflow.com/questions/41522548/magento-installation-stuck-on-53

**Comment by dmitriyprime** [comment] 2017-07-25 15:38
@MaximKitsenko, please confirm that you can reproduce this issue on a supported platform. For an overview of supported technologies, see [System Requirements](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-2.1-tech.html).

**Comment by orlangur** [comment] 2017-07-25 17:55
```
[pid 5276] [client so.me.ip.ad2:57650] PHP Fatal error: require(): Failed opening required '/var/www/app/bootstrap.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/index.php on line 22, referer: http://so.me.ip.ad:4423/magento-2-1-6-0-ce/setup/
```

The problem is with your server, not with Magento source code. Try to figure out why it happens on your server.

https://magento.stackexchange.com/a/156236 two links among four referenced stated `sudo` did the trick 🤣 So, obviously, something is not correct with file permissions.

**Comment by MaximKitsenko** [comment] 2017-07-31 12:29
@orlangur i have tried that fix before creatiing bug report. And it doesn't work for me! As a result i had half-working magento, which throws errors whn i tried to create a product

**Comment by MaximKitsenko** [comment] 2017-07-31 12:30
@dmitriyprime yes the problem still actual. All requirements are passed, also i used web installer - so all requirements were passed before installation

**Comment by orlangur** [comment] 2017-07-31 12:43
It's pretty hard to guess what could be wrong on a buggy environment.

> [Tue May 23 09:34:22.717969 2017] [:error] [pid 5694] [client so.me.ip.ad2:57638] PHP Fatal error: require(): Failed opening required '/var/www/app/bootstrap.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/index.php on line 22, referer: http://so.me.ip.ad:4423/magento-2-1-6-0-ce/setup/ [Tue May 23 09:34:46.204459 2017] 

The most effective way to spot the problem is to enable xdebug and to set breakpoint before problematic line to see what's going on in action.

**Closed as completed** 2017-09-18 19:12 UTC
Labels: bug report, Progress: needs update, Component: Setup, non-issue, Issue: Format is valid
