### ISSUE TITLE
Attribute Heading border misaligned.

### ISSUE THREAD

**Issue by suryakant-krish** [magento/magento2#19371] opened 2018-11-24 10:00 UTC
### Preconditions (*)

1. Magento 2.2.5

### Steps to reproduce (*)

1. Login to admin panel >  Stores  > Attribute sets > choose any attribute.
2. Edit Attribute set name heading border.

### Expected result (*)

![actual-result](https://user-images.githubusercontent.com/43638601/48966771-a5aad200-effd-11e8-93d8-f881d325d712.png)

### Actual result (*)

![border-misalign](https://user-images.githubusercontent.com/43638601/48966806-cf63f900-effd-11e8-8734-3abb99aca870.png)

**Comment by magento-engcom-team** [comment] 2018-11-24 10:00
Hi @suryakant-krish. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@suryakant-krish do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-11-27 18:57
Hi @dmytro-ch. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2018-11-27 19:00
@dmytro-ch Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96683`, `MAGETWO-96684` were created

**Comment by magento-engcom-team** [comment] 2019-01-19 06:55
Hi @suryakant-krish. Thank you for your report. 
The issue has been fixed in magento/magento2#19414 by @suryakant-krish in 2.3-develop branch
Related commit(s):
 - [77fa7042941849ea40632b6704fd2d043ec59da1](https://github.com/magento/magento2/commit/77fa7042941849ea40632b6704fd2d043ec59da1)
 - [976d80c533f59099a730902389721ca424037000](https://github.com/magento/magento2/commit/976d80c533f59099a730902389721ca424037000)
 - [c835aa18336af26895e140c0f4f36a129315e44f](https://github.com/magento/magento2/commit/c835aa18336af26895e140c0f4f36a129315e44f)
 - [f03953b1a4013c24fbd008505f54446862efe4c8](https://github.com/magento/magento2/commit/f03953b1a4013c24fbd008505f54446862efe4c8)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2019-01-19 06:55 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Ui, Component: Backend
