### ISSUE TITLE
Editing configurations of configurable products doesn't update quantities

### ISSUE THREAD

**Issue by dakira** [magento/magento2#12590] opened 2017-12-07 17:59 UTC
When I edit the configurations of a configurable product it allows me to set images, price and quantities for single SKUs or all products. For prices, it works, for quantities it doesn't.

### Preconditions
Magento: 2.1.10
PHP: 7.0.22
OS: Ubuntu 16.04
Webserver: Apache 2.4.18
DB: MySQL 5.7.20

### Steps to reproduce
1. Open an existing configurable product
2. Click *Edit Configurations*
3. Move on to step 3 *"Bulk Images & Price"*
4. Select to update prices based on SKU, select the attribute, enter the prices and click next
5. Verify the correct prices on the summary page, click next to finish and save the configurable product.

### Expected result
1. When looking at the individual simple products they should have the new quantities.

### Actual result
1. Quantities are the same as before

**Comment by magento-engcom-team** [comment] 2017-12-08 10:30
@dakira, thank you for your report.
The issue is already fixed in develop branch, 2.2.1

**Closed as completed by magento-engcom-team** 2017-12-08 10:30 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by dakira** [comment] 2017-12-08 10:36
@magento-engcom-team does that mean it won't be fixed for 2.1.*? I'm still having such massive problems with 2.2 that I can't move on right now (mainly not getting the frontend-theming-less workflow running after investing ~2 days).

**Comment by Ctucker9233** [comment] 2018-01-22 20:43
@dakira They usually leave it up to the community (us) to create a backport. A pretty poor practice in my opinion. Issues should be solved in the branch they were reported in first.

**Comment by dakira** [comment] 2018-01-22 21:33
@Ctucker9233 I'd backport it no problem if I knew what commit fixed it in 2.2.x. I've tried a couple of times to ask or figure out what commit fixed what.. no chance unfortunately.
