### ISSUE TITLE
Cant put id or data attribute on <img> tags in the M2 wysiwyg.

### ISSUE THREAD

**Issue by iokbomkamp** [magento/magento2#10353] opened 2017-07-27 14:37 UTC
After adding an id to <img> tags in the wysiwyg, it errors:

### Preconditions
1.  Magento 2.4

### Steps to reproduce
1.  Go to content, edit a page, insert an image in the wysiwyg. Save it. Then add an id attribute to the image like 

`<img id="image-id" src="help.jpg" />`

 or 

`<img data-id="img-id" src="help.jpg" />`.  It will throw an error: 
![selection_367](https://user-images.githubusercontent.com/20865162/28675860-2115a48a-72b7-11e7-952a-4dc59e92f4bd.png)

Then the code gets weird and weird strings get added to the src:
![selection_366](https://user-images.githubusercontent.com/20865162/28675942-5532b4f6-72b7-11e7-9066-0ec40d3e04e9.png)

### Expected result
1.  It shouldn't throw an error. 

### Actual result
1. The error message:
![selection_367](https://user-images.githubusercontent.com/20865162/28675909-3b5be5d4-72b7-11e7-8a0d-1159114a3398.png)

After error what code looks like (images won't work like this either):
![selection_366](https://user-images.githubusercontent.com/20865162/28675954-62c8970c-72b7-11e7-8c31-840414fe7a91.png)

**Comment by magento-engcom-team** [comment] 2017-09-20 13:57
@iokbomkamp, thank you for your report.
We've created internal ticket(s) MAGETWO-75586 to track progress on the issue.

**Comment by PieterCappelle** [comment] 2017-09-26 11:51
Should be fixed in #11053 .

**Comment by magento-engcom-team** [comment] 2019-12-23 14:37
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30044` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by DipaliBhalala** [comment] 2020-10-09 13:18
@magento I am working on it

**Comment by DipaliBhalala** [comment] 2020-10-09 13:23
@magento add to contributors team

**Comment by DipaliBhalala** [comment] 2020-10-10 05:09
@magento I am working on it

**Comment by DipaliBhalala** [comment] 2020-10-10 06:48
I've tried this in Magento 2.4, 
checked id and data-id ...both are working fine 
It's not throwing any kind of error!

**Comment by engcom-Bravo** [comment] 2024-09-11 10:21
Hi @iokbomkamp,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.


<img width="1437" alt="Screenshot 2024-09-11 at 15 50 00" src="https://github.com/user-attachments/assets/2e34ecdf-5180-4ccb-8233-9860917e5b7d">


it is not throwing an any error.

Hence we are closing this issue.

Thaks.

**Closed as completed by engcom-Bravo** 2024-09-11 10:21 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Component: Framework/Wysiwyg, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P2, Severity: S2, Progress: done, CD, Area: Framework
