### ISSUE TITLE
RequireJS resolver sometimes fails to detect blocked resources

### ISSUE THREAD

**Issue by ishakhsuvarov** [magento/magento2#28116] opened 2020-05-05 21:30 UTC
### Preconditions (*)
1. Magento `2.3.5-p1`. Most likely any recent release would be affected.

### Steps to reproduce (*)
1. Create a custom [RequireJS config](https://requirejs.org/docs/api.html#config) which defines a component complete with its url and [fallback path](https://requirejs.org/docs/api.html#pathsfallbacks). For example:
```js
var config = {
    paths: {
        a: ['https://example.com/advertisement.js', 'Custom_Module/js/noop']
    }
};
```
2. Include this component on Checkout (may be reproducible elsewhere)
<details>

```html
<!-- Something simple like this would work: -->
<script type="text/x-magento-init">
    {
        "*": {
            "a": {}
        }
    }
</script>
```

</details>

3. Use a browser with any aggressive Ad Blocker extension which would block the required url
4. Open Checkout page

### Expected result (*)
1. ✅ Ad Blocker extension blocks the script download from the url stated in RequireJS config (`https://example.com/advertisement.js`) 
1. ✅ Checkout page loads and renders just fine

### Actual result (*)
1. ✅ Ad Blocker Extension blocks script download from the original url
2. ℹ️ RequireJS uses [path fallback](https://requirejs.org/docs/api.html#pathsfallbacks) mechanism to load a resource from second url, therefore not triggering an error.
3. ℹ️ Magento's [RequireJS resolver](https://github.com/magento/magento2/blob/6b6f428c4b938c209658eb5d75d84b72503cbce0/lib/web/mage/requirejs/resolver.js#L36) cannot keep track of such events and continues to wait for original resource to load (as no error was produced), therefore not calling any of the [callbacks](https://github.com/magento/magento2/blob/6b6f428c4b938c209658eb5d75d84b72503cbce0/app/code/Magento/Checkout/view/frontend/web/js/checkout-loader.js#L26).
4. ❌ Checkout page is displaying 2 spinning loaders and a fully rendered page under it as resolver does not track components which were loaded via fallbacks.

**Comment by magento-engcom-team** [comment] 2020-05-06 16:10
@VladimirZaets Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2020-05-06 16:10
:white_check_mark: Confirmed by @VladimirZaets 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34099` were created

**Issue Available**: @VladimirZaets, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hostep** [comment] 2020-05-06 20:21
@ishakhsuvarov: out of curiosity: is this regarding the checkout no longer working on the Magento Marketplace when uBlock Origin is active?

**Comment by ishakhsuvarov** [comment] 2020-05-12 00:45
@hostep sorry for the delay. Yes, this is exactly that issue which started as your report on slack :)

Thank you for your participation!

**Comment by engcom-Charlie** [comment] 2020-08-28 14:41
Hi @ishakhsuvarov we are not able to reproduce this issue on the latest 2.4-develop branch by provided steps.
Could you please take a look?
Thank you.

**Comment by magento-engcom-team** [comment] 2020-09-21 12:35
Hi @ishakhsuvarov. Thank you for your report. 
The issue has been fixed in magento/magento2#28117 by @ishakhsuvarov in 2.4-develop branch
Related commit(s):
 - [303bd64e3c1a7281be08d3b73feb995ef580e61d](https://github.com/magento/magento2/commit/303bd64e3c1a7281be08d3b73feb995ef580e61d)
 - [bfdde51e16e4be105d92463ba4c481a4eb8dd363](https://github.com/magento/magento2/commit/bfdde51e16e4be105d92463ba4c481a4eb8dd363)
 - [c1f132bd07cee811a7f876bcce2eb1fba5dd98ed](https://github.com/magento/magento2/commit/c1f132bd07cee811a7f876bcce2eb1fba5dd98ed)
 - [8602befa58ccd0c215aaa48b1023ca3d2ef07ac6](https://github.com/magento/magento2/commit/8602befa58ccd0c215aaa48b1023ca3d2ef07ac6)
 - [375b129374fb83ba4993c67cb893835da91032ec](https://github.com/magento/magento2/commit/375b129374fb83ba4993c67cb893835da91032ec)

The fix will be available with the upcoming 2.4.2 release.

**Closed as completed by magento-engcom-team** 2020-09-21 12:35 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Issue: Format is valid, Component: Ui, Release Line: 2.4, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P2, Severity: S2, Triage: Done, Progress: done, Reported on 2.3.5-p1

**Comment by rav-redchamps** [comment] 2021-07-28 13:34
Hey @ishakhsuvarov,

The changes in your pull request https://github.com/magento/magento2/pull/28117 is causing issue with admin ui component grids.

Steps to reproduce:

1. Login to admin panel & navigate to Catalog > Products grid
2. Filter grid by some SKU
3. Close the browser window
4. Open admin panel in new private/incognito window
5. Go to Catalog > Product Grids

## Expected result (*)

✅ Grid should be filtered by SKU

## Actual result (*)

ℹ️ You will see that grid has SKU filter applied but it still show all the records

**Comment by hostep** [comment] 2021-07-28 16:33
@rav-redchamps: could you open a new issue describing this issue and link to that PR? That will make sure the issue is being followed up, commenting on closed issues often doesn't seem to help here.

**Comment by rav-redchamps** [comment] 2021-07-28 16:40
@hostep Done ✅ https://github.com/magento/magento2/issues/33620
