### ISSUE TITLE
Cart price rule not working as expected

### ISSUE THREAD

**Issue by VZeroCool** [magento/magento2#28409] opened 2020-05-28 14:12 UTC
### Preconditions (*)

1.   2.3.3 CE
2. AWS EC2 Nginx

### Steps to reproduce (*)

1. Create a product with amount 99, Add this to cart
2. Create cart price rule with flat 200 discount with coupon code when subtotal is equals or greater  than 10
3. Add 4 qty to cart and apply coupon code

### Expected result (*)

1. As cart total is 396 only 200 discount should given to customer

### Actual result (*)

1. It gives 100% discount to customer. 
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by VZeroCool** [comment] 2020-05-28 14:12
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-28 14:12
Hi @VZeroCool. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-05-28 14:14
Hi @VZeroCool, here is your [Magento instance](https://i-28409-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28409-2-4-develop.instances.magento-community.engineering/admin_940e](https://i-28409-2-4-develop.instances.magento-community.engineering/admin_940e)
Login: `000aefee` Password: `c59892b94a35`
Instance will be terminated in up to 3 hours.

**Comment by VZeroCool** [comment] 2020-05-28 14:20
Yes can able to reproduce this issue in 2.4 develop instance 

I've created https://i-28409-2-4-develop.instances.magento-community.engineering/phone.html 
Coupon Code is **SEASONSALE**

**Comment by swathishs** [comment] 2020-05-28 15:13
@VZeroCool: Tested the issue in 2.4 develop instances. I think the issue is invalid.

Since "Fixed amount discount" will be applied for each quantity 

Example: If I keep the Fixed amount discount = 20 , 1 qty = 99 price
               If we add 4 qty means 4*40 = 80 will be the discount amount 

Please find the attachments below:

1. **Coupon code with 20 off** : 
![image](https://user-images.githubusercontent.com/58288685/83158613-9ccf1b00-a122-11ea-8ef8-2d99bd90e1cb.png)
2. **Cartpage**:
![image](https://user-images.githubusercontent.com/58288685/83158656-aa84a080-a122-11ea-9f56-3d544b7ac928.png)

Note: In your case, the discount amount is 200 and the one quantity price is 99. So only you're getting a total of 396 discounts.

If you want to reduce 200off from the whole price you should keep as " Fixed amount discount for the whole cart"

**Comment by VZeroCool** [comment] 2020-05-28 16:06
Ah I see. Good to know that we have solution for this. Thanks for explanation. Hence closing this one.

**Comment by swathishs** [comment] 2020-05-29 04:31
As the issue is invalid . Hence closing the issue

**Closed as completed by swathishs** 2020-05-29 04:31 UTC
Labels: Issue: Format is valid, Reported on 2.3.3
