### ISSUE TITLE
Creditmemo creation error - Forgotten shipping discount tax compensation in creditmemo calculation ?

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#38088] opened 2023-10-16 12:36 UTC
### Preconditions and environment

- Magento version 2.4.6-p2

### Steps to reproduce

It's kind hard to say how to reproduce step by step because it's a very very rare rounding issue on shipping amounts. But I'll try anyway, and then give the order details : 

1. Place an order*, with a discount (not sure if the discount is mandatory)
2. Invoice & Ship order
3. Create a creditmemo (via invoice) to refund shipping amount
4. try to create another creditmemo (via invoice)

(*) Here is some order detail that might be relevant : 

- grand_total = 780.26
- subtotal = 710.77
- subtotal_incl_tax = 770.90
- total_refunded = 125
- tax_amount = 62.48
- tax_invoiced = 62.48
- tax_refunded = 11.36
- discount_tax_compensation_amount = 9.01
- discount_amount = -115.64
- shipping_amount = 113.63
- shipping_invoiced = 113.63
- shipping_refunded = 113.63
- shipping_tax_amount = 11.36
- shipping_tax_refunded = 11.36
- shipping_discount_tax_compensation_amount = 0.01
- shipping_incl_tax = 125
- shipping_discount_amount = 0

### Expected result

We can create another creditmemo

### Actual result

We can not create another creditmemo, and have an error message : `Maximum shipping amount allowed to refund is: 0,00 €`

### Additional information

`desiredAmount` is `0.01` in 

https://github.com/magento/magento2/blob/2b3ad2eeb6903643b678ceeb7d1ea7361035dee7/app/code/Magento/Sales/Model/Order/Creditmemo/Total/Shipping.php#L71-L98

So `$desiredAmount < [..]$allowedAmount` gives `0.01 < 0` which causes the exception. That 0.01 seems to correspond to `shipping_discount_tax_compensation_amount` field.

DesiredAmount is set previously here : 
https://github.com/magento/magento2/blob/2b3ad2eeb6903643b678ceeb7d1ea7361035dee7/app/code/Magento/Sales/Model/Order/CreditmemoFactory.php#L151-L154

and calculated here : 
https://github.com/magento/magento2/blob/2b3ad2eeb6903643b678ceeb7d1ea7361035dee7/app/code/Magento/Sales/Model/Order/CreditmemoFactory.php#L326-L340

As you can see, if we apply my order numbers in that code, it gives : 

`$amount = 125 - 113.63 - 11.36 = 0.01` => So I guess the calculation is forgetting about `shipping_discount_tax_compensation_amount`

And a fix would be : 

```
$amount = $order->getBaseShippingInclTax() -
                $order->getBaseShippingRefunded() -
                $order->getBaseShippingTaxRefunded() -
                $order->getBaseShippingDiscountTaxCompensationAmnt();
```

However, tax calculation is so complex in Magento 2 that I won't try to make a PR for this. It would be safer if someone used to such calculations can have a look. However, this fix seems to fix the issue.

EDIT : This fix was not OK, and it seems unrelated from `shipping_discount_tax_compensation_amount` after all.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-10-17 06:09
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-10-27 12:12
Hi @Nuranto 
Thanks for reporting and collaboration. verified in magento 2.4 develop instance
and able to create another credit memo. Not able to reproduce the issue. Please refer the screenshots below.

Creditmemos:
<img width="1440" alt="creditmemos" src="https://github.com/magento/magento2/assets/60198592/3cfcf5e0-dfbb-4966-a376-3bc1596339da">


Creditmemo1:
<img width="1440" alt="creditmemo1" src="https://github.com/magento/magento2/assets/60198592/d3ca872e-255b-4691-8f49-f7a2d07b3eae">

Creditmemo2:
<img width="1440" alt="creditmemo2" src="https://github.com/magento/magento2/assets/60198592/42d295be-0d9b-4b5c-8fbf-c5a99f0de6a0">

**Comment by Nuranto** [comment] 2023-11-06 08:30
As I said, it is a very rare issue (we got 1 case for thousands of orders). It happened on a big order (douzens of products), with a cart discount. However, I don't know how to reproduce for sure I'm afraid.

**Comment by engcom-Dash** [comment] 2023-11-07 14:51
Hi @Nuranto 
Thanks for reporting and collaboration.
We have tested with number of products.Sometimes the issue depends on the operating system.Can you please let us know the operating system you are using? 
Thanks.

**Comment by Nuranto** [comment] 2023-11-08 07:42
We're running on docker `php:8.1-apache-bullseye` image.

**Comment by engcom-Dash** [comment] 2023-12-13 13:13
Hi @Nuranto 

Thanks for reporting and collaboration.

we can divide the shipping fee into two creditmemos

We followed the steps to reproduce but not able to reproduce the issue. 

1.Place an order*, with a discount (not sure if the discount is mandatory)
2.Invoice & Ship order
3.Create a creditmemo (via invoice) to refund shipping amount
4.try to create another creditmemo (via invoice)

Please let us know the detailed steps to reproduce the issue.

**Comment by engcom-Dash** [comment] 2024-01-03 05:48
Hi @Nuranto 

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2024-01-03 05:48 UTC
Labels: Issue: needs update, Reported on 2.4.6-p2

**Comment by Nuranto** [comment] 2024-04-17 07:19
(related to #38134)

**Comment by Nuranto** [comment] 2024-04-17 07:33
Workaround Fix proposal, for those who have the issue, or if the issue is reopened one day :

Replace : 
```
if ($desiredAmount < $this->priceCurrency->round($maxAllowedAmount) + 0.0001) { 
     // since the admin is returning less than the allowed amount, compute the ratio being returned 
     $ratio = 0; 
     if ($originalTotalAmount > 0) { 
         $ratio = $desiredAmount / $originalTotalAmount; 
     } 
     // capture amounts without tax 
     // Note: ($x > $y - 0.0001) means ($x >= $y) for floats 
     if ($desiredAmount > $maxAllowedAmount - 0.0001) { 
         $shippingAmount = $allowedAmount; 
         $baseShippingAmount = $baseAllowedAmount; 
     } else { 
         $shippingAmount = $this->priceCurrency->round($orderShippingAmount * $ratio); 
         $baseShippingAmount = $this->priceCurrency->round($orderBaseShippingAmount * $ratio); 
     } 
     $shippingInclTax = $this->priceCurrency->round($orderShippingInclTax * $ratio); 
     $baseShippingInclTax = $this->priceCurrency->round($orderBaseShippingInclTax * $ratio); 
 } else { 
     $maxAllowedAmount = $order->getBaseCurrency()->format($maxAllowedAmount, null, false); 
     throw new \Magento\Framework\Exception\LocalizedException( 
         __('Maximum shipping amount allowed to refund is: %1', $maxAllowedAmount) 
     ); 
 } 
```
With

```
if ($desiredAmount >= $this->priceCurrency->round($maxAllowedAmount) + 0.0001) { 
  $desiredAmount = $maxAllowedAmount;
}
     // since the admin is returning less than the allowed amount, compute the ratio being returned 
     $ratio = 0; 
     if ($originalTotalAmount > 0) { 
         $ratio = $desiredAmount / $originalTotalAmount; 
     } 
     // capture amounts without tax 
     // Note: ($x > $y - 0.0001) means ($x >= $y) for floats 
     if ($desiredAmount > $maxAllowedAmount - 0.0001) { 
         $shippingAmount = $allowedAmount; 
         $baseShippingAmount = $baseAllowedAmount; 
     } else { 
         $shippingAmount = $this->priceCurrency->round($orderShippingAmount * $ratio); 
         $baseShippingAmount = $this->priceCurrency->round($orderBaseShippingAmount * $ratio); 
     } 
     $shippingInclTax = $this->priceCurrency->round($orderShippingInclTax * $ratio); 
     $baseShippingInclTax = $this->priceCurrency->round($orderBaseShippingInclTax * $ratio); 

```

This doesn't fix the underlaying issue that I did not identified yet. But that will prevent the exception to be thrown without damaging creditmemo data.
