### ISSUE TITLE
Outdated pelago/emogrifier package

### ISSUE THREAD

**Issue by Bartlomiejsz** [magento/magento2#6946] opened 2016-10-10 14:06 UTC
I'm providing just one example of possible bugs here. The problem is that version of pelago/emogrifier package that Magento 2 uses was released almost 1,5 year ago.
### Preconditions
1. Magento 2.1.1
### Steps to reproduce
1. Custom email-inline styles, compressed (i.e. by sass compiler)
2. `parent > children` selector used in styles (in compressed file it looks `parent>children`)
### Expected result
1. Styles should be applied correctly (description in `_email-base.less` file says that descendant is supported.
### Actual result
1. Styles are not applied due to Emogrifier bug, that was already fixed and correct version is available.

When do you plan to update this package?

**Comment by veloraven** [comment] 2016-10-13 08:44
@Bartlomiejsz thank you for your report.
However I'm closing this issue as it is a duplicate of #4737.
Please follow mentioned issue for more information.

**Closed as completed by veloraven** 2016-10-13 08:44 UTC
