### ISSUE TITLE
Product Variation Handler ignore Store View Data

### ISSUE THREAD

**Issue by philippeaellig** [magento/magento2#35354] opened 2022-04-22 15:25 UTC
On generating product variations for a configurable product in Magento admin, Magento will generate child products with data of the parent. But if the parent has different values in another store view/scope, these values where ignored. the generated child product will only get the data of the parent product from default store.

https://github.com/magento/magento2/blob/ef0ffcd37470e83337133a167dc4504f86037f28/app/code/Magento/ConfigurableProduct/Model/Product/VariationHandler.php#L180

Example:
The parent product has the description "Foo". In german store view, the description is "Bar".
The new generated child of the configurable product will have the description Foo. And in the german store view, the description is set to "use default value". I expect the value "Bar" insted.

**Comment by engcom-November** [comment] 2022-05-02 06:42
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-05-02 10:01
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-05-02 12:58
Hi @philippeaellig ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but the issue is not reproducible.
Steps performed:
Magento multi store setup
Created Configurable product with child variations and description set to "All store views description"
Edit product -  change scope to other store view (germany) and edit description set to "German site description" and save
Note: "Use Default Value" should be unchecked to update new content to other store.
View the Product in both the stores. Store specific description is getting displayed.
![image](https://user-images.githubusercontent.com/60198231/166237325-37f6595b-847b-47dd-b3ba-70f2b38f299f.png)

![image](https://user-images.githubusercontent.com/60198231/166237260-64f6e05d-c2ca-41f4-b424-c36de2e86ea4.png)
Kindly recheck the issue again on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by philippeaellig** [comment] 2022-05-02 14:02
Hi @engcom-November ,
yes, the steps you described is not the problem. this will work as expected.
steps to reproduce:
1 in admin, create a new configurable product. add german description in store view. save it.
2. genereate child products. save.
result: the generated child product have all attributes of his parent from "all store view" scope. but the files (in admin, not in frontend) of the german store view are empty.
expected: the generated child product should have all attributes from the parent, not just the attributes from "all store view".

**Comment by engcom-November** [comment] 2022-05-04 12:00
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-05-04 12:38
Hi @philippeaellig ,
Thank you for your response. Verified the issue again on Magento 2.4-develop branch with above steps however this seems to be expected behavior. Please find the observations of 2 scenarios below:
**Scenario** 1: Create configurable product - Change scope to germany - Add description in store view - save. Change scope to -  "all store views" - Generate child products and save.
Go to child Product details page in admin - Since "Use Default Value" is selected by default - German description will not be displayed which is an expected behavior.
Front end - German store - Product details page - description set is displayed - No issue.

Scenario 2: Create Configurable Product with child products and description. Change scope to german store and add different description. go to child product details page in admin - Since "Use Default Value" is selected by default - "All Store view" description is displayed for both the store views. If no description is given under "All Store View" scope - description field will be empty for both the store views due to "Use Default Value" being selected by default. 
In both the cases, no difference in behavior / inconsistency observed.
Kindly recheck the behavior again and provide reference docs/proofs that states this behavior as a valid issue.

**Comment by engcom-November** [comment] 2022-05-18 05:52
Hi @philippeaellig ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-05-18 05:52 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
