### ISSUE TITLE
Add flag to silence dot output from setup:static-content:deploy

### ISSUE THREAD

**Issue by erikhansen** [magento/magento2#3692] opened 2016-03-08 20:47 UTC
I'm using Capistrano to deploy Magento 2 to production and stage environments. As a part of the deployment process, I'm running the `bin/magento setup:static-content:deploy` command. However since Capistrano streams all output to screen, I see this:

![capistrano](https://cloud.githubusercontent.com/assets/129031/13615734/6ab919aa-e53c-11e5-964e-ff164d48c20f.png)

So I've resorted to passing in the `-q` flag to silence all output: `bin/magento setup:static-content:deploy -q`. However this doesn't allow me to see progress as each theme is compiled. I'd like to see a flag added like `--no-progress` that would result in output like this:

```
php -f bin/magento -- setup:static-content:deploy --no-progress
Requested languages: en_US
=== frontend -> Magento/blank -> en_US ===
=== frontend -> Magento/luma -> en_US ===
=== frontend -> Customvendor/customtheme -> en_US ===
```

**Comment by erikhansen** [comment] 2016-03-08 20:48
@antonkril This feature request is a similar request to the one in issue #3038, so I'm pinging you so you're aware of it.

**Comment by hshar7** [comment] 2016-03-08 21:21
Hi @erikhansen thanks for reporting this, how is this problem not because of Capistrano? Because if I run this command on my machine I get dots next to each other instead of each one on a new line.
Also it is possible to do something like this (with the addition of new line character for you of course):
![Image](http://i.imgur.com/EAmZ4Mz.png)

**Comment by vrann** [comment] 2016-03-09 16:24
@erikhansen Thanks for the suggestions. As far as it relates primarily to Capistrano, would you mind to create a Pull Request with the needed changes?

**Comment by erikhansen** [comment] 2016-03-09 17:01
@hshar7 Thanks for your suggestion of piping output through `tr` to remove the dots. I tried that and it doesn't work.

@vrann I could see this being useful for a broader audience than just Capistrano users. Unfortunately I don't have time to create a PR for it now. If you don't think this is likely to get added to the Magento 2 roadmap, then feel free to close this task.

**Comment by davidalger** [comment] 2016-04-27 03:04
@erikhansen A workaround is to use `stdbuf` from core-utils to prevent the shell from buffering the output of `tr` as seen in the above tagged commit. This results in the dots being stripped, but the normal output passing through normally to the CLI as it is output.

Ideally, there would still be an option to create a more friendly output format for deployment tools such as capistrano, but this solves the problem for capistrano in the meantime.

**Comment by hostep** [comment] 2016-05-18 08:09
This is a duplicate of https://github.com/magento/magento2/issues/2848 btw :)

**Comment by piotrekkaminski** [comment] 2016-06-20 19:31
--no-progress flag proposed in #2848 seems better name

This is low priority issue, if anyone can provide PR great but otherwise will not be done.

**Comment by erikhansen** [comment] 2016-06-20 19:40
@piotrekkaminski If PR #4294 is merged, it will satisfy the objective of this task. Since PR #4294 is actively being discussed and only needs a little more work in order to be merged in, I am going to close this task in hopes that #4294 will be merged soon.

**Comment by hostep** [comment] 2016-06-20 21:31
@erikhansen: care to explain how #4294 will help with silencing the progress output of the command? Because I don't see a flag for that? Maybe best to reopen this issue, so one day it might still get implemented.

**Comment by erikhansen** [comment] 2016-06-20 21:56
@hostep You're correct. For some reason I was getting this issue confused with #3038. Re-opening this issue.

@piotrekkaminski I agree that a `--no-progress` flag would be better. Updating my issue description accordingly.

**Comment by ClaudiuCreanga** [comment] 2016-07-13 10:09
Just to be aware that is not an issue just with capistrano, but it is affecting a lot of deployment tools (i.e deploybot and others). A PR would be nice because it is hard to debug your deployment with all those dots.

**Comment by piotrekkaminski** [comment] 2016-08-26 03:00
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Add-flag-to-silence-dot-output-from-setup-static-content-deploy/idi-p/45288).

**Closed as completed by piotrekkaminski** 2016-08-26 03:00 UTC
Labels: improvement, Area: Frontend
