### ISSUE TITLE
Special price container around every price for configurable product

### ISSUE THREAD

**Issue by torhoehn** [magento/magento2#9127] opened 2017-04-04 14:02 UTC
### Preconditions

1. Magento CE 2.1.5
2. PHP 7.0.15
3. MySQL 5.6.35

### Steps to reproduce

1. Installed Magento CE 2.1.5 with sample data
2. Admin Panel >> Products >> Catalog :: Go to configurable product e.g. SKU: WH01
3. Edit any child of this main product. Set special price to this child product and save it.
4. Search this main product from front-end.

### Expected result

1.  span class="special-price" should only appear if simple product that holds the special price is selected

### Actual result

1. Every price is surrounded by span class="special-price"

**Comment by IlnitskiyArtem** [comment] 2017-06-27 10:51
@torhoehn, Thanks for reporting this issue. 
Created internal issue MAGETWO-70285 to investigate and track this issue.

**Comment by magento-engcom-team** [comment] 2017-10-03 14:30
@torhoehn, thank you for your report.
We've created internal ticket(s) MAGETWO-70285 to track progress on the issue.

**Comment by Olek89** [comment] 2017-10-30 13:50
Special Price only working  with not configurable products,
i have an image from the frontend of reduced prices / spezial prices of configurable products and simply products, Simply prices are reduced shown, configurable products no reduced price shown.

![configurable_123](https://user-images.githubusercontent.com/31250340/32174258-adaf16c8-bd81-11e7-82d2-eb3f870a3d82.png)

**Comment by Drakas** [comment] 2017-11-21 14:43
@magento-engcom-team I can confirm the comment of @Olek89 .
The special price of "configurable product" does not appears as it was in the 2.1.5 version (now I'm on 2.2.1).
It's very uncomfortable. Please fix if possibile... 

I upgrade Magento 2.1.5 to 2.2.1 form command line.

**Comment by engcom-Echo** [comment] 2019-12-09 12:59
Hello All

I am not able to reproduce this issue on the 2.4-develop branch by provided steps.

**Testing scenario:**

**Steps to reproduce:**

1. Installed Magento CE 2.4 with sample data
2. Admin Panel >> Products >> Catalog :: Go to configurable product e.g. SKU: WH01
3. Edit any child of this main product. Set special price to this child product and save it.
4. Search this main product from front-end.

**Result**
Span class="special-price" is appear if simple product that holds the special price is selected
![4](https://user-images.githubusercontent.com/51681435/70437188-b789d680-1a93-11ea-9d5e-4b4a056628e3.png)
So I have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Echo** 2019-12-09 12:59 UTC
Labels: bug report, Component: Tax, Issue: Clear Description, Issue: Format is valid
