### ISSUE TITLE
State option required in admin customer address edit

### ISSUE THREAD

**Issue by mashb1t** [magento/magento2#8152] opened 2017-01-16 13:55 UTC
The state select-field in the customer address edit form is required despite having set the config not to be.

### Preconditions
1. Magento Version 2.1.2
2. PHP 7.0.8

### Steps to reproduce
1. Add customer
2. Add address to customer
3. Choose a country having states assigned (@see table "directory_country_region")

### Expected result
1. When selecting e.g. Germany as country in the address, the state select should neither be required due to config "general/region/state_required" not set to the selected country, nor be displayed due to config "general/region/display_all" set to no.

### Actual result
1. State select-field is displayed and required despite having the config set in the "correct" way.

Screenshot Config
![Screenshot Config](https://cloud.githubusercontent.com/assets/9307310/21985445/014b2060-dbfb-11e6-880e-cf6b41e400af.png)

Screenshot Customer Address Edit
![Screenshot Customer Address](https://cloud.githubusercontent.com/assets/9307310/21985471/2ecdca10-dbfb-11e6-95c7-e1fbe536fb30.png)

I guess the config settings are only implemented correctly in the frontend, not the backend.

**Comment by sma09sjb** [comment] 2017-02-22 12:28
Hi,

This issue is causing significant problems for us. We're unable to save a user in the admin because there is no applicable state for the city of Munich, and the field is required. 

Can i have some update of when a fix with be implemented? 

Or is there a temporary workaround i can implement. 

Thanks,

Sophie

**Comment by DavidLambauer** [comment] 2017-03-02 13:05
+1

**Comment by vrann** [comment] 2017-03-28 21:54
Closing as a duplicate of #6261

**Closed as completed by vrann** 2017-03-28 21:54 UTC
Labels: bug report, Component: Customer
