### ISSUE TITLE
Server side LESS compilation drops media-width sections where arguments are wrapped in double quotes

### ISSUE THREAD

**Issue by MichaelThessel** [magento/magento2#24929] opened 2019-10-08 19:20 UTC
### Preconditions (*)

1. 2.3.1

### Steps to reproduce (*)
1.  Use double quotes for `media-width()` arguments

### Expected result (*)
1. Running Grunt based and server-side compilation should produce identical style files

### Actual result (*)
1. When using server side compilation styles are dropped if the `max` or `min` argument for  `.media-width()`  is wrapped in double quotes. 

I.e.:
`media-width(@extremum, @break) when (@extremum = 'min') and (@break = @screen__m) {`

will be included in both cases while:

`media-width(@extremum, @break) when (@extremum = "min") and (@break = @screen__m) {`

is dropped when compiled with server-side compilation and included when compile with grunt.

This should either:
* Yield identical results
* Result in an error during compilation

Also if single quotes are a requirement this should be documented. 

**Side note:**
This is another of the countless grunt vs frontend vs server-side compilation issues showcasing how bad this design is. PLEASE unify this. When unifying this please keep in mind that this needs to work for development. Currently server-side and frontend compilation are useless for development due to their poor performance.

**Comment by DanielRuf** [comment] 2019-10-10 14:55
This is a know issue. Please see https://github.com/magento/magento2/issues/7231

Closing this one as duplicate.

**Comment by MichaelThessel** [comment] 2019-10-10 17:25
@DanielRuf this is not a duplicate of #7231. In fact this is a reproducible issue I spent several days tracking down. This can be fixed. #7231 has been open for **3 years** without any progress. I assume there will be no progress on this any time soon either. Till there is a unified approach for static asset compilation any issue that produces different results should be addressed individually. Imagine several other devs struggling with that for days. The cumulative amount of time wasted on bugs like this is insane. In addition issues like this one make Magento seem like a buggy alpha and not a production ready e-commerce platform. I updated the title of this ticket to make it more distinct from #7231.

**Comment by DanielRuf** [comment] 2019-10-10 17:39
Thanks for the clarification. As we use an old and unmaintained PHP library for the compilation it might be fixed in one of the newer forks.

**Comment by DanielRuf** [comment] 2019-10-10 17:48
https://github.com/wikimedia/less.php is the most maintained and active solution. The main problem is the PHP version so far.

**Comment by engcom-Charlie** [comment] 2019-11-18 07:46
Hello @MichaelThessel 
We are closing this issue due to the https://github.com/magento/magento2/issues/7231 was confirmed by me and i can't reproduce your issue on a fresh Magento 2.3-develop.

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-11-18 07:46 UTC
Labels: Issue: Format is valid
