### ISSUE TITLE
Import Scheduler run multiple times when use more web nodes

### ISSUE THREAD

**Issue by manhtranisobar** [magento/magento2#34429] opened 2021-10-26 02:50 UTC
### Preconditions (*)

1.Magento 2.4.1
2.PHP 7.4
3.Setup 2 web nodes and enable cronjob for both

### Steps to reproduce (*)

1.On the Admin sidebar, go to System > Data Transfer > Scheduled Import/Export.
2.Add a daily Scheduled Import for Advanced Pricing at 01:02

### Expected result (*)

1. Import scheduler run one times at 01:02
2. Received one email if import file does not exist

### Actual result (*)

1. Import scheduler ran 15 times every minute from 01:02 to 01:16
2. Received 15 emails if import file does not exist
![download](https://user-images.githubusercontent.com/88669934/138800547-576b3bc5-6363-4432-8821-4550f11caa04.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2021-12-21 13:11
Hello @manhtranisobar,

We have tried to reproduce the issue in Magento 2.4-develop branch but the issue is not reproducible for us. For us only 1 failed email has been received.

We request you to please share some more screenshots or videos in order to better analyse the issue.

Thanks

**Comment by manhtranisobar** [comment] 2021-12-22 09:08
Hi @engcom-Hotel 
Thanks for your checking,
I will try to reproduce this issue and provide to you more information if It happen again.

**Comment by engcom-Hotel** [comment] 2021-12-22 09:49
Hello @manhtranisobar,

Thanks for replying!

We will wait for your reply

Thanks

**Comment by engcom-Hotel** [comment] 2022-01-05 07:44
Dear @manhtranisobar,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-01-05 07:44 UTC
Labels: Issue: needs update
