### ISSUE TITLE
PHPSESSID cookie not generated

### ISSUE THREAD

**Issue by ktruehl** [magento/magento2#5499] opened 2016-07-06 13:46 UTC
## Steps to reproduce
1. install Magento 2.1.
2. install the Demodata
3. clear cache
4. clear domain cookies in browser
5. visit the home page
6. visit the category "Women" -> "Tops" -> "Hoodies & Sweatshirts"
7. visit any product page in the category
   => the breadcrumbs do not contain any category
8. register a new customer
9. clear cache
10. again visit the category "Women" -> "Tops" -> "Hoodies & Sweatshirts"
11. again visit any product page in the category
    => now the breadcrumbs contain the categories "Women", etc.
## Underlying problem

The `PHPSESSID` cookie, which the default frontend session cookie, is not always sent to the browser. Therefore the session data cannot be saved correctly. In particular the ID of the last visited category cannot be stored and retrieved. Therefore at step 7 the breadcrumbs do not contain any category. When registering a new or logging in an existing customer, the `PHPSESSID` cookie is created. Therefore, after clearing the cache, at step 11 the breadcrumbs now work correctly.

**Comment by sevos1984** [comment] 2016-09-01 15:45
I cant't reproduce this, is this still actual?

**Comment by ktruehl** [comment] 2016-09-01 16:20
Hm. It seems to be fixed in CE 2.1.1. What version are you using?

**Comment by sevos1984** [comment] 2016-09-05 13:43
I'm on latest 2.1. Can I close it?

**Comment by ktruehl** [comment] 2016-09-05 15:52
Weird. After all I managed to reproduce the bug in 2.1 both on our system and a different virgin system. I assume you can close the issue. If I stumble upon the problem again, I will reopen the issue.

**Closed as completed** 2016-09-06 08:13 UTC
Labels: bug report, Component: Customer

**Comment by kanduvisla** [comment] 2018-12-13 15:16
I'm stumbling on this issue now. The `PHPSESSID` cookie gets removed as soon as I am redirected to the payment page of my PSP, and when I return the cookie is gone. Magento does not create a new one at this point, resulting in an infinite amount of sessions being created and nothing works (cannot add products to cart and stuff because of the missing session ID link).

I'm running Magento 2.2.6
