### ISSUE TITLE
Unique constraint violation found after saving CMS Page (subpage)

### ISSUE THREAD

**Issue by engcom-Delta** [magento/magento2#35452] opened 2022-05-10 15:28 UTC
**Description**
https://github.com/magento/partners-magento2ee/issues/548

### Preconditions (*)

1.Magento Commerce v2.4.2 or 2.4 develop ( EE)

### Steps to reproduce (*)

1. Log in to Magento EE ( commerce edition ) 
2. Create and save a new CMS Page
3. Add page as other page's sub page in Page Hierarchy
4. Go edit the page you created and try to save - Error occurs

### Expected result (*)
Page should be saved without error and user should be redirected back to list view

### Actual result (*)

1. [Screenshots, logs or description]
<img width="1440" alt="Screenshot 2022-05-10 at 8 42 49 PM" src="https://user-images.githubusercontent.com/51681379/167665229-730ea5f9-7ece-4e15-9291-b07389293bf4.png">

2. Error displayed "Unique constraint violation found"

4. Below logs found in debug.log
```
[2022-05-10T15:12:41.695577+00:00] report.DEBUG: cache_invalidate:  {"method":"POST","url":"http://local.magentoee.com/index.php/admin/cms/page/save/key/67401d0927a567836a9fcbe61b97a57a594f2f11129f1d742709952508f436af/back/edit","invalidateInfo":{"tags":["cms_p_10","FPC"],"mode":"matchingTag"}} []
[2022-05-10T15:12:41.703540+00:00] report.CRITICAL: Exception message: Unique constraint violation found
Trace: <pre>#1 Magento\Framework\Model\AbstractModel->save() called at [generated/code/Magento/VersionsCms/Model/Hierarchy/Node/Interceptor.php:635]
#2 Magento\VersionsCms\Model\Hierarchy\Node\Interceptor->save() called at [partners-magento2ee/app/code/Magento/VersionsCms/Observer/Backend/CmsPageSaveAfterObserver.php:281]
#3 Magento\VersionsCms\Observer\Backend\CmsPageSaveAfterObserver->createNewNode() called at [partners-magento2ee/app/code/Magento/VersionsCms/Observer/Backend/CmsPageSaveAfterObserver.php:187]
#4 Magento\VersionsCms\Observer\Backend\CmsPageSaveAfterObserver->appendPageToNodes() called at [partners-magento2ee/app/code/Magento/VersionsCms/Observer/Backend/CmsPageSaveAfterObserver.php:114]
#5 Magento\VersionsCms\Observer\Backend\CmsPageSaveAfterObserver->execute() called at [lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php:88]
#6 Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() called at [lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php:74]
#7 Magento\Framework\Event\Invoker\InvokerDefault->dispatch() called at [partners-magento2ee/app/code/Magento/Staging/Model/Event/Manager.php:97]
#8 Magento\Staging\Model\Event\Manager->dispatch() called at [generated/code/Magento/Staging/Model/Event/Manager/Proxy.php:95]
#9 Magento\Staging\Model\Event\Manager\Proxy->dispatch() called at [lib/internal/Magento/Framework/Model/AbstractModel.php:832]
#10 Magento\Framework\Model\AbstractModel->afterSave() called at [lib/internal/Magento/Framework/EntityManager/Observer/AfterEntitySave.php:34]
#11 Magento\Framework\EntityManager\Observer\AfterEntitySave->execute() called at [lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php:88]
#12 Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() called at [lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php:74]
#13 Magento\Framework\Event\Invoker\InvokerDefault->dispatch() called at [partners-magento2ee/app/code/Magento/Staging/Model/Event/Manager.php:97]
#14 Magento\Staging\Model\Event\Manager->dispatch() called at [generated/code/Magento/Staging/Model/Event/Manager/Proxy.php:95]
#15 Magento\Staging\Model\Event\Manager\Proxy->dispatch() called at [lib/internal/Magento/Framework/EntityManager/EventManager.php:51]
#16 Magento\Framework\EntityManager\EventManager->dispatchEntityEvent() called at [partners-magento2ee/app/code/Magento/Staging/Model/Operation/Update.php:219]
#17 Magento\Staging\Model\Operation\Update->execute() called at [lib/internal/Magento/Framework/EntityManager/EntityManager.php:106]
#18 Magento\Framework\EntityManager\EntityManager->save() called at [app/code/Magento/Cms/Model/ResourceModel/Page.php:400]
#19 Magento\Cms\Model\ResourceModel\Page->save() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:58]
#20 Magento\Cms\Model\ResourceModel\Page\Interceptor->___callParent() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:138]
#21 Magento\Cms\Model\ResourceModel\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:153]
#22 Magento\Cms\Model\ResourceModel\Page\Interceptor->___callPlugins() called at [generated/code/Magento/Cms/Model/ResourceModel/Page/Interceptor.php:104]
#23 Magento\Cms\Model\ResourceModel\Page\Interceptor->save() called at [app/code/Magento/Cms/Model/PageRepository.php:194]
#24 Magento\Cms\Model\PageRepository->save() called at [generated/code/Magento/Cms/Model/PageRepository/Interceptor.php:23]
#25 Magento\Cms\Model\PageRepository\Interceptor->save() called at [app/code/Magento/Cms/Model/PageRepository/ValidationComposite.php:71]
#26 Magento\Cms\Model\PageRepository\ValidationComposite->save() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:58]
#27 Magento\Cms\Model\PageRepository\ValidationComposite\Interceptor->___callParent() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:138]
#28 Magento\Cms\Model\PageRepository\ValidationComposite\Interceptor->Magento\Framework\Interception\{closure}() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:153]
#29 Magento\Cms\Model\PageRepository\ValidationComposite\Interceptor->___callPlugins() called at [generated/code/Magento/Cms/Model/PageRepository/ValidationComposite/Interceptor.php:23]
#30 Magento\Cms\Model\PageRepository\ValidationComposite\Interceptor->save() called at [app/code/Magento/Cms/Controller/Adminhtml/Page/Save.php:120]
#31 Magento\Cms\Controller\Adminhtml\Page\Save->execute() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:58]
#32 Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->___callParent() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:138]
#33 Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:153]
#34 Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->___callPlugins() called at [generated/code/Magento/Cms/Controller/Adminhtml/Page/Save/Interceptor.php:23]
#35 Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->execute() called at [lib/internal/Magento/Framework/App/Action/Action.php:111]
#36 Magento\Framework\App\Action\Action->dispatch() called at [app/code/Magento/Backend/App/AbstractAction.php:151]
#37 Magento\Backend\App\AbstractAction->dispatch() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:58]
#38 Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->___callParent() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:138]
#39 Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [app/code/Magento/Backend/App/Action/Plugin/Authentication.php:145]
#40 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:135]
#41 Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:153]
#42 Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->___callPlugins() called at [generated/code/Magento/Cms/Controller/Adminhtml/Page/Save/Interceptor.php:32]
#43 Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->dispatch() called at [lib/internal/Magento/Framework/App/FrontController.php:245]
#44 Magento\Framework\App\FrontController->getActionResponse() called at [lib/internal/Magento/Framework/App/FrontController.php:212]
#45 Magento\Framework\App\FrontController->processRequest() called at [lib/internal/Magento/Framework/App/FrontController.php:147]
#46 Magento\Framework\App\FrontController->dispatch() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:58]
#47 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:138]
#48 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [lib/internal/Magento/Framework/Interception/Interceptor.php:153]
#49 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#50 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [lib/internal/Magento/Framework/App/Http.php:116]
#51 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#52 Magento\Framework\App\Http\Interceptor->launch() called at [lib/internal/Magento/Framework/App/Bootstrap.php:264]
#53 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
```
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-10-15 05:32
Hi,

We have verified the issue in Latest 2.4-develop instance with EE edition and the issue is no more reproducible.We are able to edit and save the cms page.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-10-15 05:32 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Content, Adobe Commerce
