### ISSUE TITLE
Magento Upgrade from 2.1.7 to 2.1.8 - Paypal issue

### ISSUE THREAD

**Issue by yagneshponkiya** [magento/magento2#10658] opened 2017-08-25 10:08 UTC
I have upgraded magento 2.1.7. to magento 2.1.8 using command line all seems working fine except the payment method  paypal which was enabled earlier Magento 2.1.7 is not showing up in frontend magento 2.1.8.

**Comment by orlangur** [comment] 2017-08-25 11:00
Duplicate of https://github.com/magento/magento2/issues/10499. It looks like the issue is not reproduced on every instance, please share your findings in mentioned issue to speed up problem localization.

**Closed as completed by orlangur** 2017-08-25 11:00 UTC
Labels: duplicate
