### ISSUE TITLE
Customer cannot delete address

### ISSUE THREAD

**Issue by MrBlueEyez** [magento/magento2#37461] opened 2023-05-04 11:07 UTC
### Preconditions and environment

- Noticed on Magento EE 2.4.5-p1 but can still the issue on the current development branch: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/view/frontend/templates/address/grid.phtml
- Make sure that the none trailing slash urls are configurated.

### Steps to reproduce

1. Login as customer
2. Go to your address
3. Make sure you have atleast 1 additional (not in use) address.
4. Delete one of the additional addresses

### Expected result

The address is deleted

### Actual result

The delete action causes a 404 and the url that is shown is:
`.../customer/address/deleteid/...`

When redirecting back to the addresses page, the address is still present.

### Additional information

Inside the Magento_Customer/view/frontend/templates/address/grid.phtml on line 74 the delete url is being suffixed with `id/`.
When not having trailing slashes in your url this will cause an invalid url as the url will be `/customer/address/deleteid/` instead of `/customer/address/delete/id/`.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-05-05 06:54
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-05-05 12:21
Hi @MrBlueEyez,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.



**Steps to reproduce**

- Login as customer
- Go to your address
- Make sure you have atleast 1 additional (not in use) address.
- Delete one of the additional addresses

We are able to delete the addresses.



https://user-images.githubusercontent.com/51680745/236397154-cf2c5632-256c-4aff-bc81-60df2b2dd1d0.mov



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by Usik2203** [comment] 2023-05-15 14:28
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-05-16 06:14
Hi @MrBlueEyez,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-05-16 06:14 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1
