### ISSUE TITLE
Magento 2.1: Admin: Product Edit is missing left side menu with page subsections

### ISSUE THREAD

**Issue by heldchen** [magento/magento2#5333] opened 2016-06-29 08:40 UTC
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Edit product in the admin
## Expected result
1. Left side menu with the edit page subsections (f.e. "General", "Design", ..) is shown
## Actual result
1. The subsections are shown in the main content as an "accordion" at the bottom of the page

**Comment by antboiko** [comment] 2016-06-29 11:03
Hi @heldchen , Product page in Admin was redesigned for Magento 2.1 to use unified UI along with Category pages and CMS pages. 

I'm closing this issue as it's not a bug. Please feel free to reopen if it's needed.

Thanks,
Anton.

**Closed as completed by antboiko** 2016-06-29 11:03 UTC

**Comment by heldchen** [comment] 2016-06-29 17:19
thanks for confirming that this is the intended behaviour. our customers are not at all happy with it, but I guess they'll have to learn to live with it :)

**Comment by windowbox** [comment] 2016-09-21 22:35
Is there any way to turn this back on? I understand for consistency turning off this functionality, but it was a very usable solution to manage any entity with so many fields. Since this is a community effort, where was the opportunity to chime in on this change before it went to 2.1? Is there any chance to bring this back? or is that added functionality we will need to build a module for? I did notice 'Add Users' still has this.

**Comment by pboisvert** [comment] 2016-09-21 23:06
There is no configuration to turn on the former style of tertiary navigation. The change was made for usability reasons as the left-hand navigation took up space which reduced the form area. User testing was done on the revised design by our UX team so this was done with user input. That said this is a perfect case where the community can create an extension leveraging the former code and make available to other community members that may prefer the former design.

**Comment by windowbox** [comment] 2016-09-21 23:20
Thanks for the response. We will definitely be looking into adding this. I hope the Design / UX team is handling usability of both Mobile v Desktop separately and not grouping both groups into its tests. 

I find it difficult to believe that it is easier to use on desktops without the left-hand navigation.

**Comment by heldchen** [comment] 2016-09-21 23:56
@windowbox our customer's content managers edited >10k products in the last few weeks and months and are still complaining about the "missing" lefthand submenu. an extension would be most welcome - we have not yet had the time to look into this due to more pressing pre/post-launch related stuff.

@pboisvert the "reduced form area" argument is kinda moot when the form is _limited_ in horizontal size in the desktop viewports even after removing the left menu:

![image](https://cloud.githubusercontent.com/assets/299636/18732832/77ee14fc-8066-11e6-9cdf-98b3a8d71c6c.png)

I don't doubt that the current layout is better for tablets or smaller screens, but IMO it drops the ball for the viewport most important to the targeted business users.

**Comment by pboisvert** [comment] 2016-09-22 00:06
i'll be sure to pass your feedback to the UX lead. My point was the revision was tested--not just blindly implemented. There may be other arguments in favor of the new design which i am not aware of--was just trying to reply that these are not done without merchant feedback as was being implied. 

@annhudspeth please chime in here with the findings from the testing

**Comment by heldchen** [comment] 2016-09-22 00:15
@pboisvert appreciated! I understood the point you were trying to make but just wanted to chime in to give some feedback we received from our "people in the field". 

and to maybe add another data point: our product edit page currently has 16 subsections due to roughly 120 custom product attributes. quickly jumping from one section to another was really easy with the left menu, now not anymore - just to get to the 2nd subsection after the initial page load I'm currently having to press page-down 3 times, and it get's worse when some of the sections are expanded and others collapsed.

maybe you could better accommodate heavy users by adding keyboard shortcuts: `j` jumps to the previous and `l` jumps to the next subsection, `k` collapses and `m` expands the current section :-)

**Comment by annhudspeth** [comment] 2016-09-22 13:45
We developed a UX solution to this back in July but I'm not sure where it's prioritized.  Will resurface the thread.

**Comment by JasonFerris** [comment] 2016-10-15 15:44
I found this thread when I was asked where these menus went after upgrading to 2.1. We have a pretty complex catalog and losing that left hand menu makes navigating through our product data much more difficult. Maybe add this menu system back with an option to turn off/on?

**Comment by annhudspeth** [comment] 2016-10-17 14:47
We have a solution that is in development.  I'll circle back with an ETA when I find out what the dev schedule is.

**Comment by JasonFerris** [comment] 2016-10-17 16:23
Awesome thank you!

On Oct 17, 2016, at 7:48 AM, Ann Hudspeth <notifications@github.com<mailto:notifications@github.com>> wrote:

We have a solution that is in development. I'll circle back with an ETA when I find out what the dev schedule is.

**Comment by scottsb** [comment] 2017-03-09 00:38
@annhudspeth Was any further decision made on this?

**Comment by JasonFerris** [comment] 2017-03-09 00:50
Yes the removal of the menus makes it MUCH harder to navigation through the product editor in the admin. Any chance this will get fixed in 2.1.6?

**Comment by annhudspeth** [comment] 2017-03-09 14:54
@pboisvert do you know where this is prioritized?

**Comment by alxanthony** [comment] 2017-03-21 18:51
Can we please get an update on this? or could you provide a workaround to get the left menu back? clients are complaining that it takes them almost double the time to populate data.

**Comment by windowbox** [comment] 2017-04-26 00:07
@pboisvert Just checked out 2.1.6 and didn't see any change. Any update if this might be fixed soon?

**Comment by andyjv** [comment] 2018-01-31 21:50
This issue is unfortunately a sadly accurate representation of overall development of Magento 2. Changes are made to parts of the system with flimsy reasoning like "We tested this, _honest_.", when in reality there's no way this could have passed even a rudimentary review. 

I'm going to be upgrading to 2.2.2 soon, and apparently the "Fix" for this is slated for 2.2.3; and this issue was brought to the developers attention 2 years ago. I'm going to be facing the same questions when we launch 2.2.2, and I'm going to have to answer with another "Thats just the way Magento is".

Does the Magento team ever talk to actual store managers? Not just the developers installing Magento for clients, but people who are in Magento every day managing their store. I could create a list a mile long of truly poor decisions by the Magento team on a number of issues, but I'm already off-topic.

**Comment by hostep** [comment] 2018-01-31 22:07
@antboiko: Could this change also have something to do with the fact that when saving a product/category and you don't open one of these accordions, it saves different content to the database then when you do open one of these accordions? We've been noticing lately that a lot of things can go wrong when not opening all those accordions before saving (especially on storeview level), which is ridiculous.

**Comment by windowbox** [comment] 2018-02-01 19:40
@hostep The issue you are having is alarming and I would imagine has severe impact on your operations. I would highly recommend you create a new issue with specifics, ideally steps to replicate the error.

The issue in this thread is in regards to the early 2.0 releases had a left hand navigation similar to the  1.* product edit screen, but it was stripped away and replaced with the accordion in the 2.1 release with no regard to users that rely on it. This was likely a reaction to a different 'issue' created which makes me wonder, who is filtering what is actually an 'issue' and focusing on core e-commerce changes vs customizations for a specific use.

**Comment by hostep** [comment] 2018-02-01 20:47
@windowbox: yes it is very alarming indeed, a colleague of mine added steps to reproduce over here: https://github.com/magento/magento2/issues/8897#issuecomment-361927613, I was just wondering if the change discussed in this issue might have introduced the problem, due to the fact that it works perfectly fine in Magento 1 where we don't have this accordeon system.
