### ISSUE TITLE
FPC Cache via Files or Redis does not work on Magento 2.4.7 for multi-view stores

### ISSUE THREAD

**Issue by dandrikop** [magento/magento2#39221] opened 2024-09-27 12:09 UTC
### Preconditions and environment

This bug report is actually related with the issue: https://github.com/magento/magento2/issues/38626

Besides the Files used as the default medium for FPC, I tested Redis with Magento 2.4.7-p2 and FPC did not work. Namely it seems that cached content is stored at Files or Redis. The problem is that Magento cannot somehow identify the cached pages so it thinks that they have not been cached.

This problem is No-Go for Magento 2.4.7 for store owners with multi-domain and multi-view Magento installations, as Magento without FPC is out-of-question. It is said that the problem will be fixed at Magento 2.4.8. However, a patch should become available at Magento Quality Patches; otherwise store owners with multi-domain and multi-view Magento installations should stay at version 2.4.6 till 2.4.8 is released.

### Steps to reproduce

1. Set the multi-view store to Developer mode.
2. Visit various pages on the front-end.
3. Monitor the value of the HTTP header "X-Magento-Cache-Debug".

### Expected result

The value of the HTTP header "X-Magento-Cache-Debug" is HIT for subsequent requests of the same page.

### Actual result

The value of the HTTP header "X-Magento-Cache-Debug" is always MISS no matter how many times a page has been visited at the front-end.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dandrikop** [comment] 2024-09-27 12:13
It is absolutely necessary to have patch available at Magento quality patches for this issue:

https://experienceleague.adobe.com/tools/commerce-quality-patches/index.html

This is a serious problem, as FPC is a crucial performance factor for Magento.

**Comment by engcom-Hotel** [comment] 2024-10-14 12:19
Hello @dandrikop,

Thanks for the report and collaboration!

We are discussing this issue internally, meanwhile please use the below commits to fix this issue:

https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-11819&type=commits

We are moving this issue `On Hold`.

Thanks

**Comment by engcom-Hotel** [comment] 2024-10-15 13:21
Hello @dandrikop,

We have tried to reproduce the issue in 2.4.7-p3 with both default FPC and Redis. and for us the issue is not reproducible. We have created multiple store views to reproduce the issue.

The first time when we access a store view it shows as `Miss` and the next time it shows as `Hit`. Please refer to the below screenshot for reference:

_**English Storeview**_
![image](https://github.com/user-attachments/assets/cdeb378b-d558-45e7-ba46-7ea21b648971)
![image](https://github.com/user-attachments/assets/e20448ab-8d24-44d0-bdfe-e7527d611439)

_**French Storeview**_
![image](https://github.com/user-attachments/assets/0937aca2-4c19-48f8-adaf-74d9a45b50aa)
![image](https://github.com/user-attachments/assets/34882a80-e963-4a97-b21c-a766ee04923a)

Please let us know if we have missed anything.

Thanks

**Comment by dandrikop** [comment] 2024-10-16 09:58
The error depends on the implementation. My multi-store implementation has 7 websites, each website has one store, and each store has one store view. The routing at the appropriate store view is regulated by the .htaccess file with directives such as the following ones:

SetEnvIf Host fr\.dlastore\.com MAGE_RUN_CODE=french_dla
SetEnvIf Host fr\.dlastore\.com MAGE_RUN_TYPE=store

This problem has been reproduced and identified with AC-11819. My concern is that we'd better have a patch available at:

https://experienceleague.adobe.com/tools/commerce-quality-patches/index.html

**Comment by engcom-Hotel** [comment] 2024-10-17 07:58
Hello @dandrikop,

Thanks for the input.

We have tried to reproduce the issue with the multi-websites and multi-stores, and the issue has been reproducible for us. Let me keep this issue on hold to discuss it with the PO.

We will keep you posted.

Thanks

**Comment by engcom-Hotel** [comment] 2024-10-24 12:33
Hello @dandrikop,

Could you please confirm if you are running the above-mentioned scenario (multi-store, multi-website) with Varnish configured? If so, what is the value of the x-magento-cache-debug header?

**Comment by dandrikop** [comment] 2024-10-25 07:52
Hello @engcom-Hotel ,

I'm running the above scenario with Files for Magento FPC. My app/etc/env.php file contains the below code for the section 'cache'
`
'cache' => [
        'graphql' => [
            'id_salt' => 'i38cdiM3Hdrq2PKAPJ5NQNyUbZkSqCUe'
        ],
        'frontend' => [
            'default' => [
                'id_prefix' => '8e8_'
            ],
            'page_cache' => [
                'id_prefix' => '8e8_'
            ]
        ],
        'allow_parallel_generation' => false
    ]
`
I also tried it with Redis Magento FPC. I have not tested the scenario with Varnish.

**Comment by engcom-Hotel** [comment] 2024-11-04 09:43
Keeping this issue `On hold` till further updates.

**Comment by MartinL1983** [comment] 2024-11-08 08:30
Hello!

We encountered this issue yesterday on our staging environment and did some investigation. We discovered a difference between the results returned by `$this->identifier->getValue()` and `$this->identifierForSave->getValue()` in PageCache/Kernel.php.

Here are the values being returned:

- `$this->identifierForSave->getValue() = 31cf127754c679b1a38b4a2c19af6f9ad2b3d849`
- `$this->identifier->getValue() = MAGE_RUN_TYPE=store|MAGE_RUN_CODE=aedwinkel_nl|31cf127754c679b1a38b4a2c19af6f9ad2b3d849`

It’s clear that one of the methods is returning an unexpected value. We’re not yet certain which one. Logically, it seems the hashed version is the correct value, but we are also unsure if MAGE_RUN_TYPE and MAGE_RUN_CODE are meant to be part of the hash.

Since it’s surprising that an issue this small hasn’t been identified by others, we are continuing to investigate to confirm if this is indeed the root cause.

For now, we’re using the provided patch and haven’t observed any negative effects while doing so.
[kernel.patch.txt](https://github.com/user-attachments/files/17675460/kernel.patch.txt)

We’ll post any new information we find here.

Does anybody else have any ideas to confirm if we are on the right track?

**Comment by dandrikop** [comment] 2024-11-08 10:01
@MartinL1983 

Indeed, this problem has been reported with https://github.com/magento/magento2/issues/38626. What I added was just some tests with REDIS used for FPC in addition to Files FPC for which the problem was initially reported. I don't know if the problem also occurs if Varnish is used for FPC. 

This problem has been routed to be resolved with Magento 2.4.8 version. See AC-11819 at the below link:

https://experienceleague.adobe.com/en/docs/commerce-operations/release/notes/magento-open-source/2-4-8

However, I believe that it should be resolved, as soon as possible, with an official patch for the version 2.4.7 in which it appeared for the first time. It is obvious that multi-stores which are currently on Magento 2.4.6 cannot be upgraded to 2.4.7 due to this serious problem, as a multi-store on Magento 2.4.7 actually works without FPC, at least if FPC is configured with either Files or REDIS.

**Comment by Webroju** [comment] 2024-11-08 10:43
thanks for the patch, but I see no positive effect from the patch. (NGINX, MAGE_RUN_CODE)

**Comment by MartinL1983** [comment] 2024-11-08 11:44
@Webroju 

Did you add it to your composer.json followed by a composer install?

**Comment by Webroju** [comment] 2024-11-08 12:21
@MartinL1983 
I have not installed it over composer, I have installed like a patch. 
patch -p1 < filename.patch

**Comment by MartinL1983** [comment] 2024-11-08 12:28
@Webroju 

I have never applied a patch that way, so I could not tell you what is wrong.

I always apply patches via composer like this:

```
"extra": {
    "magento-force": "override",
    "composer-exit-on-patch-failure": true,
    "patches": {
        "magento/framework": {
            "Patch for FPC Identifier on load": "patches/composer/magento/framework/cache/kernel.patch"
        },
    }
}
```

**Comment by dandrikop** [comment] 2024-11-08 12:30
@MartinL1983, @Webroju

I believe that an official patch should become available at the below page:

https://experienceleague.adobe.com/tools/commerce-quality-patches/index.html

I don't think that there are only a small number of multi-store Magento installations around the world. The reason that this issue has not taken significant publicity yet maybe that either a few installations may be upgraded to 2.4.7, or some store owners who have already upgraded to 2.4.7 may have not yet realized that they don't actually have FPC.

**Comment by dandrikop** [comment] 2024-11-16 13:25
@MartinL1983,

The attributes MAGE_RUN_TYPE and MAGE_RUN_CODE must be part of the hash. I'm using a 3rd party module for Full Page Cache warming on Magento 2.4.6, where the FPC works fine with Magento multi-store, and I can see that the Vary data shown by that module includes the MAGE_RUN_TYPE and MAGE_RUN_CODE. I attached here in a relevant screenshot from Magento 2.4.6:

![image](https://github.com/user-attachments/assets/6db20e59-e253-4aac-9db3-3330f717a307)

**Comment by MartinL1983** [comment] 2024-11-18 07:55
@dandrikop 

We have identified that the issue lies with the save identifier returning an incorrect value. I have updated our patch to replicate the original behavior.

The patch you referred to contains significantly more code changes. To test it, I implemented it as an app/code module. However, this exacerbated the issue in Magento 2.4.7, causing both identifiers to return entirely different values. Based on this, I suspect Magento 2.4.8 introduces additional changes that, together with the patch, resolve the issue. This might also explain why no further releases are planned before the official 2.4.8 launch.

So far, we have not observed any negative effects from using our custom patch. From what we can see, these identifiers are only used for FPC (Full Page Cache) keys. In the worst-case scenario, the FPC might remain broken, but for now, everything seems to be functioning correctly.

Updated patch
[kernel.patch.txt](https://github.com/user-attachments/files/17796658/kernel.patch.txt)

**Comment by dandrikop** [comment] 2024-11-18 08:25
@MartinL1983,

I appreciate your work on this issue. I just wondered how the unofficial patch mentioned with the below included much more code changes than your patch:

https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-11819&type=commits

I still consider the FPC issue to be important, and I believe that many store owners who have upgraded their multi-stores to Magento 2.4.7 may not have noticed that they are actually working without FPC, while any 3rd party cache warmers they may use just burden their servers without warming the FPC. This is because the performance of Magento 2.4.7 is noticeably better than 2.4.6.

@engcom-Hotel,
In any case, I consider that simply resolving the issue with Magento 2.4.8 is not a solution. This issue should be fixed on 2.4.7, as many store owners may not be able to upgrade directly to 2.4.8 from Magento versions prior to 2.4.7.

**Comment by engcom-Hotel** [comment] 2024-11-20 09:10
Hello @dandrikop,

I agree with your point. I have initiated a discussion on releasing a patch for this fix. I will update you soon on this.

Thanks

**Comment by dandrikop** [comment] 2024-11-23 10:28
Hello @engcom-Hotel,

I appreciate your understanding of the situation. Upgrading to a newer version of Magento requires that the 3rd party modules installed on a specific Magento implementation can also work with the newer Magento version. Many vendors of 3rd party modules are still in the process for making their software compatible with Magento 2.4.7. As a result, waiting for the launch of Magento 2.4.8 for having the FPC problem resolved may take many months.

On the other hand, I believe that the FPC issue with multi-store implementations of Magento 2.4.7 is serious. Although the majority of Magento implementations may have a single store view, there is still a large number of multi-store implementations for multilingual purposes.

**Comment by engcom-Hotel** [comment] 2024-12-04 08:48
Hello @dandrikop,

We have received an update on this issue. The patch has been released with the patch Id ACSD-62591. You can find more information on the same here:

[https://experienceleague.adobe.com/en/docs/commerce-operations/tools/quality-patches-tool/patches-available-in-qpt/v1-1-55/overview](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fexperienceleague.adobe.com%2Fen%2Fdocs%2Fcommerce-operations%2Ftools%2Fquality-patches-tool%2Fpatches-available-in-qpt%2Fv1-1-55%2Foverview&data=05%7C02%7Cglo24157%40adobe.com%7C248b6f35f34f4f8f22f908dd13eb7b9c%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C638688624317402779%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=nZWX5TwtRBmazHf2k0kl57bCNDMwj1kfAEns84FOM%2BM%3D&reserved=0)

We are closing this issue for now. Let us know in case of any queries.

Thanks

**Closed as completed by engcom-Hotel** 2024-12-04 08:48 UTC
Labels: Triage: Dev.Experience, Issue: On Hold, Reported on 2.4.7

**Comment by MartinL1983** [comment] 2024-12-04 08:55
Hello @engcom-Hotel  

Did you link to an incorrect page? Don't see any mention of a fix for the multi store FPC issue in the description of path ACSD-62591 or anywhere else on that page.

**Comment by engcom-Hotel** [comment] 2024-12-09 14:47
Hello @dandrikop,

As I can see here:

https://experienceleague.adobe.com/tools/commerce-quality-patches/index.html?lang=es

It shows that it is also released for 2.4.7-p2. Please refer to the below-screenshot:

![image](https://github.com/user-attachments/assets/67fb52f2-e68b-49a1-a5d0-d3ff845a912c)

Hello @MartinL1983,

Yes it is not mentioned in the description, but as discussed with internal team, it is available in this patch along with the other patches.

Thanks

**Comment by dandrikop** [comment] 2024-12-09 16:31
Hello @engcom-Hotel, @MartinL1983,

Please check my findings at the below link:
https://github.com/magento/quality-patches/issues/129

**Comment by engcom-Hotel** [comment] 2024-12-11 14:36
Hello @dandrikop,

Please refer to this https://github.com/magento/quality-patches/issues/129#issuecomment-2531080852.

Thanks
