### ISSUE TITLE
Cart Price Rule scheduling feature doesn't accept changes to the 'label' value

### ISSUE THREAD

**Issue by mparrSaatva** [magento/magento2#32994] opened 2021-05-11 18:33 UTC
### Preconditions (*)

1. v 2.3.4
2. Cart Price Rule exists with:
* rule name
* description
* is active
* specific coupon and coupon code
* conditions:
** "If ALL  of these conditions are TRUE :"
***"Subtotal (Excl. Tax)  equals or greater than  1000"
* actions:
** fixed amount discount for whole cart, $200
** applied if "Attribute Set is ...."
* label

### Steps to reproduce (*)

1. create cart price rule
2. select "schedule new update
3. define Update Name, description, start and end date
4. change rule name, description, and label
5. save update
6. save changes to coupon

### Expected result (*)

Steps 1-6 from above
When we view the update (via "edit"), all changes are present **EXCEPT** for label (which is the same)

### Actual result (*)

Steps 1-6 from above...
When we view the update (via "edit"), the change to label is also present

**NOTE**
If label is changed on regular coupon data (not in update), the label change is then present in the update.

### Impact
The label is what's used in the invoice by default, as well as what we leverage for our headless implementation on the UI side. As the invoice is a more involved update, for the time being we're manually changing the label as a workaround at every change, defeating the purpose of the scheduling feature.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment] 2021-06-01 15:15
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment] 2021-06-02 04:50
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment] 2021-06-02 05:11
Hello @mparrSaatva,
I have verified this issue as per your pre-conditions, steps, actual result and expected result. I have create a cart price with your updated information and verified it. Label name is changed as per expected result.

![image](https://user-images.githubusercontent.com/24711761/120427109-f0f08900-c38e-11eb-81b7-cc950f158789.png)

Please give attached the screenshot create rule and after update rule.

Thanks.

**Comment by mparrSaatva** [comment] 2021-06-02 14:09
hi @ajijshekh123, here are three screenshots showing each phase:
1. rule creation with label "Label One"
2. scheduled update with label "Label Two" (before saving)
3. scheduled update with label "Label One"  (after saving the update and the rule)

1. 
![store-staging saatva com_index php_admin_asdf_sales_rule_promo_quote_edit_id_8025_key_b0065871ece29ff24beaf3fad13ed337bc0d1da09821fa63b80b1d7d109d875a_](https://user-images.githubusercontent.com/35461440/120494877-cfd56b80-c381-11eb-8224-b581257a0618.png)


2. 
<img width="718" alt="Screen Shot 2021-06-02 at 9 00 42 AM" src="https://user-images.githubusercontent.com/35461440/120495137-0ad79f00-c382-11eb-868e-df41bd5f49de.png">

3. 
<img width="608" alt="Screen Shot 2021-06-02 at 9 01 57 AM" src="https://user-images.githubusercontent.com/35461440/120495147-0dd28f80-c382-11eb-92fc-2bfde4288b69.png">


Additionally, I waited until the time of the scheduled change, and the label still didn't update:
![image](https://user-images.githubusercontent.com/35461440/120495313-335f9900-c382-11eb-94f0-48941e80401b.png)

**Comment by mparrSaatva** [comment] 2021-06-09 03:12
@ajijshekh123 Are you able to see this issue i'm able to replicate?

**Comment by ajijshekh123** [comment] 2021-06-24 04:43
Hello @mparrSaatva,
Sorry for the later response. This weekend I'll review again this issue and update the status.
Thanks.

**Comment by mparrSaatva** [comment] 2021-07-26 01:44
@ajijshekh123 , just checking in on this. thank you!

**Comment by ajijshekh123** [comment] 2021-08-02 06:01
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment] 2021-08-02 07:22
Hi @mparrSaatva,

I tried with your additional steps but I didn't reproduce the issue. So Can you please send me the video So I can review it and Verified this issue.
Sorry for the inconvenience.

Thanks.

**Comment by ajijshekh123** [comment] 2021-08-02 09:41
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment] 2021-08-03 11:37
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment] 2021-08-04 05:56
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment] 2021-08-16 15:03
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment] 2021-08-18 03:50
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment] 2021-08-20 04:39
Hi @mparrSaatva 
We tried to reproduce the issue on  Magento **2.4-develop** branch but were unable to do so.
Here are the steps we followed.
1. Created a cart price rule with details & conditions as you have mentioned under preconditions
2. Created a Scheduled update by giving the following details Update Name, description, start and end date, a new rule name, new description, and a new label.
3. Saved the Scheduled update.
4. 
save update
save changes to coupon

**Comment by engcom-Echo** [comment] 2021-08-20 05:17
Hi @mparrSaatva 
We tried to reproduce the issue on Magento **2.4-develop** branch.
Here are the steps we followed.

1. Created a cart price rule with details & conditions as you have mentioned under preconditions
2. Created a Scheduled update by giving the following details Update Name, description, start and end date, a new rule name, new description, and a new label.
3. Saved the Scheduled update, when the price rule & the scheduled update was revisited we found the updated label.
So It seems **Cart Price Rule scheduling feature was accepting changes to the label value.**
So kindly recheck this issue on Magento 2.4-develop branch and if the issue is still reproducible or if you feel that we need to try it with different steps. Please provide more details or additional/missing steps regarding the same.
Would also like to request you to drop in a **video** ( if possible) of the steps you are following. It would definitely help us better.

Thank you.

**Comment by engcom-Delta** [comment] 2021-09-09 09:45
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Closed as completed by engcom-Delta** 2021-09-09 09:45 UTC
Labels: Component: Rule, Issue: needs update
