### ISSUE TITLE
Magento Upgrade Issue 2.3.1 ==> 2.3.2  catalogCategoryManagementV1

### ISSUE THREAD

**Issue by ju2kr** [magento/magento2#23951] opened 2019-07-30 20:42 UTC
### Preconditions (*)

1. I upgraded my Magento 2.3.1 Magento 2.3.2; 
2. I'm using two store views, german and english
<img width="1782" alt="Bildschirmfoto 2019-07-30 um 22 34 40" src="https://user-images.githubusercontent.com/8549484/62163406-91e90580-b31a-11e9-9baf-20d7b5ee95e5.png">

### Steps to reproduce (*)

1. http://myurl.com/rest/german/V1/categories?rootCategoryId=27&depth=1

### Expected result (*)

1. JSON with given name attribute 

### Actual result (*)

1. name attribute is null
<img width="1035" alt="Bildschirmfoto 2019-07-30 um 22 38 00" src="https://user-images.githubusercontent.com/8549484/62163534-d96f9180-b31a-11e9-8eb8-a5d5fdee2a48.png">

When I'm using the catalogCategoryRepositoryV1 I get the correct data
<img width="1363" alt="Bildschirmfoto 2019-07-30 um 22 41 16" src="https://user-images.githubusercontent.com/8549484/62163691-2d7a7600-b31b-11e9-85fa-1bf681e6a116.png">

In Magento 2.3.1 it works correctly and I did't change anything after the upgrade.

**Comment by ju2kr** [comment] 2019-07-30 20:46
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-30 20:46
Hi @ju2kr. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-30 20:47
Hi @ju2kr, here is your [Magento instance](https://i-23951-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23951-2-3-develop.instances.magento-community.engineering/admin](https://i-23951-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ju2kr** [comment] 2019-07-30 20:55
@m2-assistant  do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?

  yes

**Comment by magento-engcom-team** [comment] 2019-07-31 09:53
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18784` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-08-07 16:38
Hi @ju2kr. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-19015` was closed as `non-reproducible` in `2.2-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by ju2kr** [comment] 2019-08-10 05:54
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-08-10 05:54
Hi @ju2kr. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-08-10 05:55
Hi @ju2kr, here is your [Magento instance](https://i-23951-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23951-2-3-develop.instances.magento-community.engineering/admin](https://i-23951-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ju2kr** [comment] 2019-08-10 06:05
Hi,

i tested it at 2.3-develop and it is reproducible.

Preconditions (*)
A new Magento 2.3-develop instance
Two store views with one website and one store

Steps to reproduce (*)
http://myurl.com/rest/german/V1/categories?rootCategoryId=27&depth=1
Expected result (*)
JSON with given name attribute
Actual result (*)
name attribute is null

<img width="1051" alt="Bildschirmfoto 2019-08-10 um 08 02 23" src="https://user-images.githubusercontent.com/8549484/62818267-829d5f80-bb45-11e9-9e56-4735054bbdc2.png">

**Comment by magento-engcom-team** [comment] 2019-08-20 22:34
Hi @ju2kr. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [eb28168184ff769e0f03c8c2e5c2fe223cdac7a2](https://github.com/magento/magento2/commit/eb28168184ff769e0f03c8c2e5c2fe223cdac7a2)

The fix will be available with the upcoming `2.3.4` release.

**Closed as completed by magento-engcom-team** 2019-08-20 22:34 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Api
