### ISSUE TITLE
Async issue with store urls that are generated for sales mails wrong url

### ISSUE THREAD

**Issue by leonhelmus** [magento/magento2#35274] opened 2022-04-06 20:49 UTC
### Preconditions (*)

1. Magento 2.4.3-p1
2. php 7.4
3. composer 2
4. mysql 8.0

### Steps to reproduce (*)

1. Create two store views
2. assing different urls to the created store views
3. Make sure sales_email/general/async_sending is enabled
4. Create orders in both store views (these should be created at the same time which means they are sending mails in the same queue of async sending)
5. use this query to trigger that both mails are send at the same time: 
`update sales_order
set send_email = 1,
    email_sent = null
where entity_id in (<order 1>, <order 2>);
`
6. Check the order mails

### Expected result (*)

1. Urls that are shown in both mails have the correct url.

### Actual result (*)

1. Urls that are shown (logo url/customer/account) in the first mail are correct, but the second mail gets the urls of the first mail.

I use this patch for module magento/module-email to resolve the issues:
```
# Add scope to urls that are generated in mail. If not it could give the url of a different store.
#
# Github link:

diff --git a/Model/Template/Filter.php b/Model/Template/Filter.php
--- a/Model/Template/Filter.php
+++ b/Model/Template/Filter.php
@@ -609,6 +609,9 @@
             unset($params['url']);
         }

+        $params['_scope'] =  $this->getStoreId();
+        $this->urlModel->setScope($this->getStoreId());
+
         return $this->sanitizeValue($this->urlModel->getUrl($path, $params));
     }

diff --git a/Model/AbstractTemplate.php b/Model/AbstractTemplate.php
--- a/Model/AbstractTemplate.php
+++ b/Model/AbstractTemplate.php
@@ -771,6 +771,7 @@
         if ($this->storeManager->getStore()->getId() != $store->getId()) {
             $params['_scope_to_url'] = true;
         }
+        $params['_scope'] =  $store->getId();
         return $url->getUrl($route, $params);
     }
 }
```

The reason why it is going wrong is because of this function `\Magento\Framework\Url::getUrl` it caches the urls when it's the same instance of the class which is good, but for mails this goes wrong, because the urls that are generated are cached because of this class variable: `cacheUrl`. Because of the patch that i provided above it adds a scope which makes urls that have the same path to be cached with the scope which makes it unique to the store. Before it did not do that.

This does not resolve all issues, because if you use {{store direct_url=""}} it will still generate urls of the second mail that is why i needed to add  $this->urlModel->setScope($this->getStoreId()); this way those urls are generated correctly as well.

Please ask if you need additional information.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-04-11 12:50
@magento give me 2.4-develop instance

**Comment by leonhelmus** [comment] 2022-04-11 20:37
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-04-12 07:09
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-04-12 10:09
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue.
Steps performed:
Multi store setup with different website URLS
sales_email/general/async_sending is enabled
Enable cron
Fron-end -Main website - login as customer - Add product to cart and checkout
Other website (France) - Login using other customer - Add product to cart and checkout
Place Order at same time in both the websites.
No issue: Emails triggered for both the stores have expected URLS
Run the query update sales_order set send_email = 1, email_sent = null where entity_id in (<order 1>, <order 2>);
No issue: Emails triggered both the stores have expected URL's
![image](https://user-images.githubusercontent.com/60198231/162936217-90c01691-040e-4792-a346-4caa305e261d.png)
![image](https://user-images.githubusercontent.com/60198231/162936404-be2a0b59-adbd-4421-9c01-38dcd9ab5a1b.png)
@leonhelmus kindly recheck the issue on Magento 2.4-develop branch as it is the upcoming 2.4.x release and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by leonhelmus** [comment] 2022-04-12 20:26
Will do hope to do it this week if im not too busy.

**Comment by leonhelmus** [comment] 2022-04-25 14:21
@engcom-November  working on magento 2.4.3-p2 releases will check after.

**Comment by engcom-November** [comment] 2022-05-10 05:26
Hi @leonhelmus ,
We are closing this issue as there has been no latest update on the same. Kindly reopen/create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-05-10 05:26 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
