### ISSUE TITLE
Order confirmation email sent twice- Magento 2.4.3-p1

### ISSUE THREAD

**Issue by davidandersson1** [magento/magento2#34452] opened 2021-10-27 12:00 UTC
Hello,

We noticed when order placed, order confirmation email sent twice so duplicate issue.

### Preconditions (*)
1. Magento 2.4.3-1
2. klarna checkout - https://marketplace.magento.com/klarna-m2-checkout.html
3. configure dotmailer

### Steps to reproduce (*)
Place order with any item.

### Expected result (*)
1. Order confirmation email sent twice

### Actual result (*)
1.  it should sent only one time instead of 2 times.

if Is there any solution here, please let me know for the same!

Thanks,
David Andersson

**Comment by davidandersson1** [comment] 2021-11-03 05:40
Now i confirmed, with disabled mode of klarna/kco + Magento_Paypal + Magento_PaypalGraphQl modules, still duplicate order confirmation email on order placed (even from admin order place) so klarna/kco or paypal doesn't matter here. means possibly issue from any other core module.

**Comment by engcom-Hotel** [comment] 2021-11-29 09:21
Hello @davidandersson1,

We have tried to reproduce this issue in Magento 2.4-develop branch, but the same is not reproducible for us. We have tried it with the Magepal SMTP extension.

Maybe this issue is with the dotmailer only. Please try any other extension to send email.

Thanks

**Comment by davidandersson1** [comment] 2021-11-29 09:30
Hi @engcom-Hotel 

Yes, you are right and issue within dotmailer only and according to discussed with their support team, they have fixed in their latest version v4.13.7
https://github.com/dotmailer/dotmailer-magento2-extension#4137

However, I haven't check yet but asap will check and update here!

**Comment by engcom-Hotel** [comment] 2021-12-10 09:33
Hello @davidandersson1,

Thanks for the confirmation!

Hence the issue is not related to Magento. We are closing this issue.

Thanks

**Closed as completed by engcom-Hotel** 2021-12-10 09:33 UTC
Labels: Issue: needs update
