### ISSUE TITLE
jQuery.fn.hover() is deprecated in lib/web/fotorama/fotorama.js:3642

### ISSUE THREAD

**Issue by jesperingels** [magento/magento2#37333] opened 2023-04-05 09:01 UTC
### Preconditions and environment

- Magento version 2.4.5-p2

### Steps to reproduce

1. Navigate to storefront as a guest 
2. Open Test Category.
3. Click on a product to open the product detail page
4. Open the browser console
5. You'll see the warning: "JQMIGRATE: jQuery.fn.hover() is deprecated"

### Expected result

Expecting to not see a deprecation warning coming from the Magento codebase. 

### Actual result

Seeing a deprecation warning coming from the Magento codebase:
JQMIGRATE: jQuery.fn.hover() is deprecated

This happens here "lib/web/fotorama/fotorama.js" Line 3642

Current situation:
```        
        $wrap.hover(
            function () {
```

To fix the deprecation warning use:
```
        $wrap.on("hover",
            function () {
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-04-05 13:40
@magento give me 2.4-develop instance

**Comment by hostep** [comment] 2023-04-05 19:02
@engcom-Bravo: you can't see the problem anymore in 2.4-develop because the jquery migrate library which brings these deprecations to light has been removed. That doesn't mean the deprecated usage is magically solved, it's just not being brought to our attention anymore in the browser's console.

So this needs to be decided:
- do we leave all the deprecated jquery code alive and ignore it until it starts causing problems (probably when jQuery 4 gets released)
- do we still try to fix all deprecated usage of jquery in core Magento

See https://github.com/magento/magento2/pull/36715 for one example where we already cleaned up one single deprecated call, I've asked some questions in the "Questions or comments" section over there, but never got an answer unfortunately :(
Maybe the discussion can continue in this ticket then?

**Comment by engcom-Bravo** [comment] 2023-04-20 13:18
Hi @hostep,

Thanks for your update.

As per steps to reproduce the issue is not reproducible.

According to your update we will make this ticket as in open state for further discussions regarding deprecated Jquery.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-01-19 11:30
Hi @jesperingels,

We are Closing this issue as there is no update from long time.

Please feel free to open the issue if you are still facing any issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-01-19 11:30 UTC
Labels: Issue: needs update, Reported on 2.4.x

**Comment by hostep** [comment] 2024-01-19 13:16
@engcom-Bravo: you realise we were waiting on feedback from you right?

My question was:
> So this needs to be decided:
> - do we leave all the deprecated jquery code alive and ignore it until it starts causing problems (probably when jQuery 4 gets released)
> - do we still try to fix all deprecated usage of jquery in core Magento
