### ISSUE TITLE
Cannot add product in admin if single store mode website id != 1

### ISSUE THREAD

**Issue by kyegil** [magento/magento2#35009] opened 2022-01-23 11:15 UTC
I'm not able to add any products from admin. My Magento is in single store mode with website id = 2.
Saving a new product fails with Integrity constraint violation.
Editing and saving an existing product works fine. I am also able to create new products using the import feature.
The issue was reproduced on a clean Magento instance.

### Preconditions (*)

1. Magento Open Source 2.4.3-p1
2. php 7.4
3. MariaDB 10.4

### Steps to reproduce (*)

1. Install a clean version of Magento version 2.4.3-p1
2. Add a new website, store and store view, and make this the default
 * In Stores -> All Stores:
 
	 * Create new website (`new_website`)
	 * Create new store (`new_store`) under new_website
	 * Create new store view (`new_store_view`)  under new_store
 * Open `new_website` again, and set this as default. Save.

3. Delete the preinstalled website (`base`)
4. Verify your website db entries. The default website should be 2:

    ```
    SELECT * FROM store_website;
    +------------+-------------+-------------+------------+------------------+------------+
    | website_id | code        | name        | sort_order | default_group_id | is_default |
    +------------+-------------+-------------+------------+------------------+------------+
    |          0 | admin       | Admin       |          0 |                0 |          0 |
    |          2 | new_website | New Website |          0 |                2 |          1 |
    +------------+-------------+-------------+------------+------------------+------------+
    
    ```
5. In Stores -> Configuration -> General -> SIngle-Store Mode
 * Enable Single-store Mode. Save.
6. Verify your Single-store configuration:

   ```
   bin/magento config:show general/single_store_mode/enabled
   ```
   Should return 1
7. In Catalog -> Products
 * Add Product
 * Populate name, sku and price. Save.

### Expected result (*)

1. The product should save successfully

### Actual result (*)

1. The save action fails, with the following message:

```
`SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`denuhabsxr`.`catalog_product_website`, CONSTRAINT `CATALOG_PRODUCT_WEBSITE_WEBSITE_ID_STORE_WEBSITE_WEBSITE_ID` FOREIGN KEY (`website_id`) REFERENCES `store_website` (`website_id`) ON DELETE ), query was: INSERT INTO `catalog_product_website` (`product_id`,`website_id`) VALUES (?, ?)`
```

**Comment by engcom-November** [comment] 2022-01-27 12:01
Hi @kyegil,

Thank you for reporting the issue.

I have tried this issue on the fresh installation (Magento 2.4-dev/2.4.3-P1) but I am not able to reproduce it. Product is created successfully with above steps followed
Kindly recheck the issue on Magento 2.4-develop branch and elaborate the steps if the issue is still reproducible.
Thank you.

**Comment by kyegil** [comment] 2022-01-28 13:49
@magento give me 2.4-develop instance

**Comment by kyegil** [comment] 2022-01-28 14:22
@engcom-November Could you verify your website settings? I've just updated the Steps to reproduce, and added verification steps. I've also just tested on another new Magento project 2.4.3-1 as I wasn't able to get a develop instance, and was able to reproduce the issue.

**Comment by kyegil** [comment] 2022-02-04 07:39
@magento give me 2.4-develop instance

**Comment by kyegil** [comment] 2022-02-04 07:56
I managed to reproduce the issue on the Magento 2.4-develop instance following the steps above.
![Screenshot 2022-02-04 at 07 54 15](https://user-images.githubusercontent.com/26584237/152492400-b977efa3-927f-47ac-a911-227be0af371c.png)

**Comment by engcom-Lima** [comment] 2022-02-04 09:47
Hi @kyegil,

Thank you for reporting the issue. 
We verified the issue on Magento 2.4-develop branch and the issue is reproducible.

Steps performed:

1. Install a clean version of Magento version 2.4-develop
2. Add a new website, store and store view, and make this the default
3. In Stores -> All Stores:
4. Create new website (new_website)
5. Create new store (new_store) under new_website
6. Create new store view (new_store_view) under new_store
7. Open new_website again, and set this as default. 
8. Save the website
9. Delete the preinstalled website (base)
10. Verify your website db entries. The default website should be 2:

SELECT * FROM store_website;
+------------+-------------+-------------+------------+------------------+------------+
| website_id | code        | name        | sort_order | default_group_id | is_default |
+------------+-------------+-------------+------------+------------------+------------+
|          0 | admin       | Admin       |          0 |                0 |          0 |
|          2 | new_website | New Website |          0 |                2 |          1 |
+------------+-------------+-------------+------------+------------------+------------+

In Stores -> Configuration -> General -> SIngle-Store Mode

Enable Single-store Mode -> Save
Verify your Single-store configuration:

`bin/magento config:show general/single_store_mode/enabled`
Output should return 1

In Catalog -> Products

**Add Product**
Populate name, sku and price. Save.

**Result**: Product save failed
![Screenshot from 2022-02-04 14-11-23](https://user-images.githubusercontent.com/60198022/152507423-e05c53ce-7270-4435-a272-78dad365cd46.png)

Based on this confirming the issue.

Thanks!

**Comment by hutychivan** [comment] 2023-03-24 10:47
@magento I am working on this

**Comment by ihor-sviziev** [comment] 2023-07-19 07:28
The issue was fixed in https://github.com/magento/magento2/commit/c7402729868f9753f6d7a4e48c4a47d6a78f06be  (changes from https://github.com/magento/magento2/pull/37292)

**Closed as completed by ihor-sviziev** 2023-07-19 07:28 UTC
Labels: Component: Catalog, Issue: Confirmed, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P2, Progress: done, Area: Product, Reported on 2.4.3-p1
