### ISSUE TITLE
Duplicating product with translated url keys over multiple storeviews causes non-unique url keys to be generated

### ISSUE THREAD

**Issue by hostep** [magento/magento2#21737] opened 2019-03-13 19:05 UTC
Hi there

I'm back with yet another problem in Magento with url keys on multiple storeviews which are incorrectly generated.
This might already have been reported before, but I'm trying to create an issue with very clear steps of how to reproduce. So hopefully it can get some well needed attention.

### Preconditions (*)
1. PHP 7.2.15
2. Magento 2.3.0, 2.2.x, 2.1.x, 2.0.x

### Steps to reproduce (*)
1. Setup a vanilla Magento 2.3.0 installation using composer
2. Make sure you have 2 storeviews, I've opted for the names 'English' and 'French'
3. Create a category, I just named it 'Test', nothing translated here
4. Create a product:
    * Name: Default
    * Sku: Default
    * Price: 123
    * Qty: 9999
    * Category: Test
    * Url key: default
5. Switch to the English storeview, and change the url key of the product to 'english', uncheck 'Create Permanent Redirect for old URL'
6. Switch to the French storeview, and change the url key of the product to 'french', uncheck 'Create Permanent Redirect for old URL'
7. Up until now, everything is perfectly fine.
8. Back on the 'All Store Views' scope, open the product and click the dropdown next to the Save button and choose 'Save & Duplicate'
9. Now take a look in the database at the various url keys and url rewrites which got generated, because they are very wrong and contain duplicates which Magento shouldn't allow.

### Expected result (*)
1. Url key for the second product on the admin store is different then the first product
2. Url key for the second product on the english store is different then the first product
3. Url key for the second product on the french store is different then the first product
4. Url rewrites are generated with the url keys from each individual storeview

### Actual result (*)
1. Url key for the second product on the admin store is 'default-1' => **good**
2. Url key for the second product on the english store is 'english' => **not good**, is not unique
3. Url key for the second product on the french store is 'french' => **not good**, is not unique
4. Url rewrites for the second product are like this:

| entity_type | entity_id | request_path        | target_path                          | store_id |
|-------------|-----------|---------------------|--------------------------------------|----------|
| product     | 2         | default-1.html      | catalog/product/view/id/2            |   1      |
| product     | 2         | test/default-1.html | catalog/product/view/id/2/category/3 |   1      |
| product     | 2         | default-1.html      | catalog/product/view/id/2            |   2      |
| product     | 2         | test/default-1.html | catalog/product/view/id/2/category/3 |   2      |

 => **not good**, all of these are incorrect in that they use the url key of the 'all store views' scope, and not from the storeview scope itself.

**Comment by magento-engcom-team** [comment] 2019-03-13 19:05
Hi @hostep. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@hostep do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-03-19 08:25
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-03-21 08:02
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98826`, `MAGETWO-98827` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-04-26 03:38
Hi @hostep. Thank you for your report. 
The issue has been fixed in magento/magento2#22178 by @yvechirko in 2.3-develop branch
Related commit(s):
 - [48b0ab873183966d3f797df97d64cf7fccc1bd5d](https://github.com/magento/magento2/commit/48b0ab873183966d3f797df97d64cf7fccc1bd5d)
 - [30b0f9173a58cba4f9d70c4dc362219375383c6d](https://github.com/magento/magento2/commit/30b0f9173a58cba4f9d70c4dc362219375383c6d)
 - [4e15099e35a4493c3925d10d1b2df1623ab6e3b7](https://github.com/magento/magento2/commit/4e15099e35a4493c3925d10d1b2df1623ab6e3b7)
 - [0c88939b7c041aba3530e44f74843956d3d52e23](https://github.com/magento/magento2/commit/0c88939b7c041aba3530e44f74843956d3d52e23)
 - [a45d5196c23985068c8250a9d79fae25e89b4a1d](https://github.com/magento/magento2/commit/a45d5196c23985068c8250a9d79fae25e89b4a1d)
 - [5c384be16392cfea40896c996c1086616279e0c2](https://github.com/magento/magento2/commit/5c384be16392cfea40896c996c1086616279e0c2)
 - [9721c678c93e060573ce03cd70042147c377d70d](https://github.com/magento/magento2/commit/9721c678c93e060573ce03cd70042147c377d70d)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-04-26 03:38 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid
