### ISSUE TITLE
No element found with ID 'before.body.end' when moving 'currency' block - when adding product to a Wishlist

### ISSUE THREAD

**Issue by mcspronko** [magento/magento2#8545] opened 2017-02-14 11:12 UTC
### Preconditions
1. Magento 2.x installed with deployment mode set to "production"
2. Luma theme is configured as a default theme on a website

### Steps to reproduce
1. Navigate to Customer Login page
2. Login as a customer
3. Navigate to a product page
4. Add product to a Wishlist
5. Observe error in var/log/system.log file

### Expected result
1. No error with "No element found with ID 'before.body.end' in the var/log/system.log file

### Actual result
1. Error in var/log/system.log, this error related to Luma theme where "copyright" block is moved to "before.body.end" container. This is on Production mode
{code}
main.CRITICAL: Broken reference: No element found with ID 'before.body.end'
{code}
2. Using Developer mode shows much more errors related to missing blocks and containers.

Observations:
The `Magento\Wishlist\CustomerData\Wishlist::getItems()` is used to retrieve list of product items added to a Wishlist. There is a call `$this->view->loadLayout();` which loads layout. This is not clear why class should load layout for retrieving items from database. Without loading layout no errors occur in `system.xml` file.

**Comment by maksek** [comment] 2017-02-20 16:01
Related  to  https://github.com/magento/magento2/issues/3507

**Comment by mcspronko** [comment] 2017-02-27 23:19
Hi @maksek 

Do you have any update for this issue?

Thanks.

**Comment by maksek** [comment] 2017-02-28 16:27
Hi @mcspronko, see #5627, messaging is fixed in develop branch and targeting for 2.2, you can apply it for 2.1. For back porting we are confirming and will update on 5627.

**Comment by KrystynaKabannyk** [comment] 2017-03-07 15:48
Closing as a duplicate of #5627

**Closed as completed by KrystynaKabannyk** 2017-03-07 15:48 UTC
