### ISSUE TITLE
No tax calculation combination to give correct discount and tax when destination tax rate differs from store rate

### ISSUE THREAD

**Issue by maderlock** [magento/magento2#7507] opened 2016-11-21 17:03 UTC
### preconditions

1. Install Magento 2.1.2
2. Set up a store with origin of the US and a 0% tax rate in the US
3. Set up a tax rate of 20% for the UK
4. Use the UK and US rates for products and shipping
5. Set the tax calculation settings to apply discounts inclusive of tax and calculate tax after discounts
6. Create a blanket 10% discount

### Steps to reproduce

1. Add items to basket and checkout with a shipping address in the UK

### Expected result

1. Tax would be calculated after 10% taken from the subtotal and shipping

### Actual result

1. Tax is calculated after the discount PLUS TAX is subtracted from the subtotal and shipping, so that the tax and grandtotal are too low.

It is worth noting that in the UK, and probably elsewhere, it is standard to display everything including tax, and the assumption is that discounts apply to the amounts inclusive of tax. It's makes for a simpler process for customers than them having to estimate the tax as they go.

There is a comment in the settings saying 'Apply discount on price including tax is calculated based on store tax if "Apply Tax after Discount" is selected.' This suggests that the tax will be calculated using partially the wrong rate. As a statement to have hard-coded into the settings, this suggests there is something wrong with the approach to tax. As this seems to have been an issue in Magento 1 as well, if this cannot be fixed (unless I've missed something, this is definitely a bug), perhaps there is some advice that can be given as to how to achieve the following:

* The ability to charge tax correctly when discounts are applied to a cart where the destination tax rate is different to the store tax rate.

**Comment by choukalos** [comment] 2016-11-30 20:42
Hey @maderlock are you available for a Skype chat on this subject?  Could we have a discussion over an example in excel that shows the expected calculation?  My work email is in my profile - I can free up time my Friday or Monday morning (your late afternoon) - shoot me some times you're available along with your Skype and I'll setup a meeting to discuss.  Thanks!

**Comment by choukalos** [comment] 2016-12-05 18:35
Thanks for the chat!  This looks like it might be related to internal ticket MAGETWO-61120 .  I'm adding the examples you provided to that ticket and will escalate the priority.

**Comment by choukalos** [comment] 2017-01-25 20:42
Circling back on this one; we dove into this deeper and noticed that there are some configurations that don't work appropriately.  We have added warnings in MAGETWO-61120 to address this case.  As discussed please adjust your configuration to address the issue.  Key settings are catalog price including tax, setting both the tax/tax origin and shipping/shipping origin to the same address will tell Magento what tax rate to use for your catalog prices.   61120 is currently in resolved state/waiting to be merged into mainline.  We'll close this github when that issue is closed.

**Comment by maderlock** [comment] 2017-02-08 14:26
Thanks for coming back to this. We changed the settings as suggested and it seems to be working as expected now.

**Comment by magento-engcom-team** [comment] 2017-09-20 22:40
@maderlock, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:40 UTC
Labels: Issue: Ready for Work, bug report, Component: Tax, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
