### ISSUE TITLE
illegal offset type' warning in MutableScopeConfig

### ISSUE THREAD

**Issue by BorisovskiP** [magento/magento2#35471] opened 2022-05-13 11:36 UTC
Basically https://github.com/magento/magento2/issues/28075 also happens on Magento 2.4.4, PHP 7.4

 [MutableScopeConfig::getValue ](https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/App/MutableScopeConfig.php#L32) may receive `\Magento\Framework\App\ScopeInterface` as a scopeCode but uses it as array key: `$this->data[$scope][$scopeCode][$path]`

**Comment by engcom-Hotel** [comment] 2022-07-20 11:11
Hello @BorisovskiP,

We have tried to reproduce the issue in the Magento 2.4-develop branch as well as 2.4.4 but the issue is not reproducible for us with PHP 8.1, which is mentioned here in [system requirement](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html).

The code mentioned below returns `Main Website Store` for us:

```
$result = \Magento\Framework\App\ObjectManager::getInstance()
            ->create(\Magento\Store\Model\Store::class)
            ->load(1)
            ->getFrontendName();
$output->writeln($result);
```

Let us know in case we have missed anything.

Thanks

**Comment by BorisovskiP** [comment] 2022-07-21 07:46
Hello @engcom-Hotel,

Even tho the recommended version of` Magento 2.4.4` is `PHP8.1`, it still supports `PHP7.4`, which a lot of shops/extension version still use.

Could you tests this with `PHP7.4`?

**Comment by engcom-Hotel** [comment] 2022-07-21 16:27
Hello @sdzhepa,

Thanks for the detailed information! 

Hello @BorisovskiP,

We have switched to PHP 7.4 and tried to reproduce the issue in both Magento 2.4.4 and 2.4-develop, but for us the issue is still not reproducible. Please refer the screenshot for reference:

**PHP Version**

<img width="741" alt="image" src="https://user-images.githubusercontent.com/51681618/180264079-5cf8d1c6-0310-4722-a7fc-d69c09539139.png">

**Magento 2.4.4**

<img width="732" alt="image" src="https://user-images.githubusercontent.com/51681618/180264787-44126258-abb4-4828-b411-2e3c300fe790.png">

**Magento 2.4-develop**

<img width="719" alt="image" src="https://user-images.githubusercontent.com/51681618/180264975-9d89ef50-5d57-4c9c-9db9-14dd09820f27.png">


Let us know in case we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2022-08-04 06:39
Dear @BorisovskiP,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-08-04 06:39 UTC
Labels: Triage: Dev.Experience, Issue: needs update
