### ISSUE TITLE
Bundle Item price cannot differ per website

### ISSUE THREAD

**Issue by AntonEvers** [magento/magento2#12584] opened 2017-12-07 15:27 UTC
### Preconditions

1. Magento 2.2-develop
2. Magento 2.1-develop

### Steps to reproduce

1. Set `Stores | Configuration | Catalog | Catalog | Price | Catalog Price Scope` to 'Website'
2. Create a second website, store and store view
3. Create a bundle product with option 'Dynamic Price': 'No'
4. Add it to both websites
5. Add a bundle item with price type 'fixed' and price '12'
6. Save the product
7. Use the dropdown on the top left to change scope to your second store view
8. Set the Bundle Item price to '10'
9. Save the product

### Expected result

1. The bundle item should have price '12' in the default scope and in the first store view
2. The bundle item should have price '10' in the second store view
3. Website specific prices should be saved in table `catalog_product_bundle_selection_price`

### Actual result

1. The bundle item has price '10' everywhere
2. There are no entries in `catalog_product_bundle_selection_price`
3. The price is only saved in `catalog_product_bundle_selection` which is not website specific

Tip: almost all logic is already in place, because if you add entries to the `catalog_product_bundle_selection_price` table manually, the bundle items do have different prices per website, until you save the product in the backend. Then the `catalog_product_bundle_selection_price` entry is deleted again and only the `catalog_product_bundle_selection` entry remains.

**Comment by magento-engcom-team** [comment] 2017-12-08 09:30
@ajpevers, thank you for your report.
We've created internal ticket(s) MAGETWO-85221 to track progress on the issue.

**Comment by TomWhitmey1** [comment] 2018-02-12 13:07
@magento-engcom-team Do you guys have a timeframe on when this fix might go live? I can see in your backlog it is sitting in 'to-do'. Grateful for advice here.

**Comment by nkajic** [comment] 2018-03-14 10:20
Hi @ajpevers, 

I am testing this patch on my staging with M2.2.0. and M2.2.3 After applying patch I have noticed when saving product on store level it applies this price to website level (that is fine), but it also applies same price to default level resulting in replacing original default price and replacing prices for other websites which does not have their price in catalog_product_bundle_selection_price

In addition to your patch we should somehow stop magento updating price in catalog_product_bundle_selection if product have been updated on store/website level.

I will try to find myself where this magic happens, if you can help please let me know. Thx.

**Comment by PerfectusInc** [comment] 2018-11-16 08:58
Any update on this issue? I can still see this issue on latest Magento v2.2.6 
When this will be resolved?

Thanks

**Comment by emastyle** [comment] 2019-04-11 08:02
Same issue seems still present on Magento 2.3.

**Comment by JPinkstonSaatva** [comment] 2019-09-24 18:21
Any update on this issue? This is a blocker for the ability to set a different price per currency for bundle items.

**Comment by magento-engcom-team** [comment] 2020-01-09 14:22
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30317` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by craig-bartlett** [comment] 2020-05-21 12:12
Hi @rain2o 

I've been looking into a related issue which I think is the cause of your PR failing. The reason you get the 'The stock item was unable to be saved. Please try again' error is because the price indexer fails when you have rows in catalog_product_bundle_selection_price. Coincidentally we already had data in there from our M1 import, and upgrading to 2.3.5 from 2.3.3 caused the indexer to fail. Essentially it looks like the update from select wasn't specific enough. I posted more of my ramblings on the PR here if you want more info: https://github.com/magento/magento2/pull/27315#issuecomment-630866505

I've written a fix here but haven't made a PR as I wasn't sure how that worked when it relied on an existing PR: https://github.com/craig-bartlett/magento2/commit/8fdd190644794887c6e5f8737789b8b8817af46f?diff=unified

Hope it's of use!

**Comment by rain2o** [comment] 2020-07-10 13:44
@craig-bartlett Thanks for the details you provided! I used the changes in the commit you linked to and pushed to my pull request. When testing in my local it seemed to work great. I'm going to do some more testing to make sure it still works in multiple environments.

**Comment by gabrieldagama** [comment] 2021-02-18 12:59
Hi @AntonEvers. Thank you for your report. 
The issue has been fixed in magento/magento2#27315 by @rain2o in 2.4-develop branch
Related commit(s):
 - [b25a34f3dab7fb228241156a328591c67a8bcbeb](https://github.com/magento/magento2/commit/b25a34f3dab7fb228241156a328591c67a8bcbeb)
 - [fc9559e2612f147ca3995e71ada3648c7fdbe4b6](https://github.com/magento/magento2/commit/fc9559e2612f147ca3995e71ada3648c7fdbe4b6)
 - [a59b0e8cb5b1f91ed835352f624a5e965cefb5b8](https://github.com/magento/magento2/commit/a59b0e8cb5b1f91ed835352f624a5e965cefb5b8)
 - [8cca552dc880227a1a91d4633bebc8d66c50a57d](https://github.com/magento/magento2/commit/8cca552dc880227a1a91d4633bebc8d66c50a57d)
 - [49c261ebdbfa3932b4dcac015ffe42e681dcb136](https://github.com/magento/magento2/commit/49c261ebdbfa3932b4dcac015ffe42e681dcb136)
 - [659beb2fd940c2435d5f1b75fdefe06ad4c13871](https://github.com/magento/magento2/commit/659beb2fd940c2435d5f1b75fdefe06ad4c13871)
 - [f75a78b217536cc5d6382902d2bfbeade524ee15](https://github.com/magento/magento2/commit/f75a78b217536cc5d6382902d2bfbeade524ee15)
 - [fd40a7b2eb3d3cabc7b59c148e8048544f1230d0](https://github.com/magento/magento2/commit/fd40a7b2eb3d3cabc7b59c148e8048544f1230d0)
 - [d7f283cb12ad7685f27ff50e5f3ce58bae67d8ae](https://github.com/magento/magento2/commit/d7f283cb12ad7685f27ff50e5f3ce58bae67d8ae)
 - [56ef44b3a8a8ef927a0853af8f84016f57f3ac71](https://github.com/magento/magento2/commit/56ef44b3a8a8ef927a0853af8f84016f57f3ac71)
 - [b5c97576241006f421456a78eb7b47375d4dd070](https://github.com/magento/magento2/commit/b5c97576241006f421456a78eb7b47375d4dd070)
 - [9f622eef3737e8f8ac34d1448d0f0e9facf736c8](https://github.com/magento/magento2/commit/9f622eef3737e8f8ac34d1448d0f0e9facf736c8)
 - [64db19a685fcce189f3373ca65031b53653fb2e2](https://github.com/magento/magento2/commit/64db19a685fcce189f3373ca65031b53653fb2e2)
 - [dc7cc2c6db6abd2182d9f7c4750c607ca734163d](https://github.com/magento/magento2/commit/dc7cc2c6db6abd2182d9f7c4750c607ca734163d)
 - [ed0f987dc4ee5b34b7424d278783df297de982bf](https://github.com/magento/magento2/commit/ed0f987dc4ee5b34b7424d278783df297de982bf)
 - [ac37ae1cf1e118fe771944b0680dcde017f0ea3e](https://github.com/magento/magento2/commit/ac37ae1cf1e118fe771944b0680dcde017f0ea3e)
 - [975c0c143b7c9e18164387fff5d81ecc61266356](https://github.com/magento/magento2/commit/975c0c143b7c9e18164387fff5d81ecc61266356)
 - [171c54d7807259c92f02c59b1e49d3f1244aed85](https://github.com/magento/magento2/commit/171c54d7807259c92f02c59b1e49d3f1244aed85)
 - [a2a9cbae20545cbcf7583ab1897e5fca249a71ea](https://github.com/magento/magento2/commit/a2a9cbae20545cbcf7583ab1897e5fca249a71ea)
 - [ea5451980b21cc3849693870fea7a4d57d4e3034](https://github.com/magento/magento2/commit/ea5451980b21cc3849693870fea7a4d57d4e3034)
 - [377e070714ed22bcb7a02393257ff2b226e5fa74](https://github.com/magento/magento2/commit/377e070714ed22bcb7a02393257ff2b226e5fa74)
 - [605fb88ab4574d210b0bececb0f3708647eb793d](https://github.com/magento/magento2/commit/605fb88ab4574d210b0bececb0f3708647eb793d)
 - [6cc13cc69748e56c6a3c07fff52517f4c2b3520d](https://github.com/magento/magento2/commit/6cc13cc69748e56c6a3c07fff52517f4c2b3520d)
 - [88ea96371386e36c7ca14eea5d7a3c6db0e07207](https://github.com/magento/magento2/commit/88ea96371386e36c7ca14eea5d7a3c6db0e07207)
 - [dc3226bf2bf2792bbdf25913b8a673897bd5e8ab](https://github.com/magento/magento2/commit/dc3226bf2bf2792bbdf25913b8a673897bd5e8ab)
 - [7da12c16407840070a44a32492ca15b254b9a2c7](https://github.com/magento/magento2/commit/7da12c16407840070a44a32492ca15b254b9a2c7)
 - [c57d4d00eed8b06eb4889f5614399bde28f15ef0](https://github.com/magento/magento2/commit/c57d4d00eed8b06eb4889f5614399bde28f15ef0)
 - [f6bb216b5e7ca5e49261160ed2f7660765ac1585](https://github.com/magento/magento2/commit/f6bb216b5e7ca5e49261160ed2f7660765ac1585)
 - [27627ca83f71734f7cf290af5ac8ac9c374a4c63](https://github.com/magento/magento2/commit/27627ca83f71734f7cf290af5ac8ac9c374a4c63)
 - [b00b4231346d55c0eb82eadacdb52034d9ee9c68](https://github.com/magento/magento2/commit/b00b4231346d55c0eb82eadacdb52034d9ee9c68)
 - [eb5e30cf621edd084b47af08fe6713cc7e2ec280](https://github.com/magento/magento2/commit/eb5e30cf621edd084b47af08fe6713cc7e2ec280)

The fix will be available with the upcoming 2.4.3 release.

**Closed as completed by gabrieldagama** 2021-02-18 12:59 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Component: Bundle, Reproduced on 2.4.x, Fixed in 2.4.x, Progress: PR in progress, Priority: P2, Severity: S2, Progress: done
