### ISSUE TITLE
Internal Server Error in /V1/products/tier-prices API Endpoint

### ISSUE THREAD

**Issue by mlf20** [magento/magento2#35922] opened 2022-08-12 10:25 UTC
### Preconditions and environment

- Magento version 2.4

### Steps to reproduce

1. Retrieve auth token from the admin endpoint /V1/integration/admin/
2. Request endpoint:

```
curl -H 'Content-Type: application/json' -H 'Authorization: Bearer' <AUTH TOKEN> -d '{"admin": true, "prices": ""}' -X PUT http://<MAGENTO_URL>/pub/rest/default/V1/products/tier-prices
```

### Expected result

Returns a 400 error as the request is malformed.

### Actual result

Returns a 500 status code as an error is thrown as $prices is a null argument in Magento\Catalog\Model\Product\Price\TierPriceStorage\Interceptor::replace()

### Additional information

output of var/log/system.log:

```[2022-08-01T11:11:15.455247+00:00] main.CRITICAL: TypeError: Magento\Catalog\Model\Product\Price\TierPriceStorage\Interceptor::replace(): Argument #1 ($prices) must be of type array, null given in /magento/generated/code/Magento/Catalog/Model/Product/Price/TierPriceStorage/Interceptor.php:38
	Stack trace:
	#0 [internal function]: Magento\Catalog\Model\Product\Price\TierPriceStorage\Interceptor->replace()
	#1 /magento/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array()
	#2 /magento/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process()
	#3 /magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch()
	#4 /magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent()
	#5 /magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}()
	#6 /magento/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins()
	#7 /magento/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch()
	#8 /magento/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
	#9 /magento/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
	#10 /magento/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
	#11 {main} [] []

```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-08-16 10:53
Hi @mlf20 ,
Thanks for the update. Verified the issue on Magento 2.4-develop branch and the issue is reproducible with above payload. But however, similar issue has been confirmed here: https://github.com/magento/magento2/issues/35934. Since the issue occurred for all these API's is with same/ similar payload and with similar exception / error, we are tracking this in a single bug mentioning all endpoints / API's here: https://github.com/magento/magento2/issues/35934 and closing this issue as duplicate. Please move on to this issue for latest updates / solutions on the same.
Thank you.

![image](https://user-images.githubusercontent.com/60198231/184862660-737333a2-c42f-438e-a057-8a3ac1342f7a.png)

**Closed as completed by engcom-November** 2022-08-16 10:53 UTC
Labels: duplicate, Issue: ready for confirmation
