### ISSUE TITLE
sku attribute save error

### ISSUE THREAD

**Issue by CatherineLearmonth** [magento/magento2#7247] opened 2016-10-31 12:23 UTC
### Preconditions

1. Magento 2.1.2 
Note: I thought this may be the same as bug https://github.com/magento/magento2/issues/1222 but I have upgraded from Magento 2.1.0 to 2.1.2 and am still seeing the same error

### Steps to reproduce

I am updating the attributes of an existing product through the Magento API, using method addAttributeUpdate($code, $value, $store) in Catalog/Model/Product.php

I am able to update other product attributes (of any scope) using this method apart from the sku attribute, I get error Unknown column 'catalog_product_entity.value_id' in 'field list' in C:\xampp\htdocs\magento\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php on line 228

So I want to change the sku name from one value to another value through the method, but get the above error message. 

### Expected result

1. I should be able to use the addAttributeUpdate method to update the sku value. 

### Actual result

1. From exception.log file:
Next exception 'Exception' with message 'Report ID: webapi-58172eac5556e; Message: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'catalog_product_entity.value_id' in 'field list', query was: SELECT `catalog_product_entity`.`value_id` FROM `catalog_product_entity` WHERE (attribute_id='71' AND entity_id='2052')' in C:\xampp\htdocs\magento\vendor\magento\framework\Webapi\ErrorProcessor.php:195
Stack trace:
#0 C:\xampp\htdocs\magento\vendor\magento\framework\Webapi\ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(Zend_Db_Statement_Exception))
#1 C:\xampp\htdocs\magento\vendor\magento\module-webapi\Controller\Rest.php(219): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(Zend_Db_Statement_Exception))
#2 C:\xampp\htdocs\magento\var\generation\Magento\Webapi\Controller\Rest\Interceptor.php(37): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 C:\xampp\htdocs\magento\vendor\magento\framework\App\Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 C:\xampp\htdocs\magento\vendor\magento\framework\App\Bootstrap.php(258): Magento\Framework\App\Http->launch()
#5 C:\xampp\htdocs\magento\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#6 {main} [] []

**Comment by CatherineLearmonth** [comment] 2016-10-31 13:22
I have seen this ticket - https://github.com/magento/magento2/issues/3687 suggesting it's not possible to update the sku value through the api. If this is the case, can you change the error message to something more meaningful to indicate that the sku can't be changed as it's a unique key.

**Comment by CatherineLearmonth** [comment] 2016-10-31 16:57
I'm also getting the same issue on trying to update the category the product belongs to.
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'catalog_product_entity.value_id' in 'field list', query was: SELECT `catalog_product_entity`.`value_id` FROM `catalog_product_entity` WHERE (attribute_id='102' AND entity_id='2052')

This happens in program module-eav\Model\Entity\AbstractEntity.php - saveAttribute method. 
The select statement selects the catalog_product_entity table and looks for a column that doesn't exist, and has an attribute value that also doesn't exist on that table.

**Comment by olysenko** [comment] 2016-11-03 16:48
Hi, thank you for your report. The purpose of addAttributeUpdate($code, $value, $store) in Catalog/Model/Product.php is to update EAV attributes only. So you cannot use this method for SKU which is not en EAV attribute. Closed as not a bug

**Closed as completed by olysenko** 2016-11-03 16:48 UTC
Labels: bug report, Component: Catalog

**Comment by aliomattux** [comment] 2020-04-21 00:16
I agree it is not a bug but the error could indicate the problem generically such as just what you said, error: Cannot update non-eav attribute.
