### ISSUE TITLE
Assign custom email template to specific payment method

### ISSUE THREAD

**Issue by devhn** [magento/magento2#5689] opened 2016-07-18 12:05 UTC
What is the proper way to assign custom email template to specific payment method upon creating an order?

**For example:**
When choosing a Bank transfer payment method on the checkout it should send custom email template upon submiting the order, not the default order email (new/existing customer).

**Maybe a feature:**
It would be good if we had ability to choose custom email template for specific payment method from the administration itself. Lot of times there is a need for small text change or data variations within the email templates depending on the payment method choosen on the checkout.

http://i.imgur.com/ci82mSo.jpg

**Comment by devhn** [comment] 2016-08-26 07:38
Any news on this?

**Comment by veloraven** [comment] 2016-11-07 12:38
@devhn thank you for your feedback.
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

**Comment by razbakov** [comment] 2016-11-16 12:21
@devhn did you create email template in backend?

**Comment by devhn** [comment] 2016-11-16 12:29
Not yet, would a good option to create one from the administration directly.

**Comment by razbakov** [comment] 2016-11-16 12:44
@devhn afaik there is a bug #7452 in custom email templates. If you didn't use backend for creating email templates and have it in files, then it is probably other issue.

**Comment by devhn** [comment] 2016-11-16 12:50
Yes, #7452 is not related.

**Comment by veloraven** [comment] 2016-11-17 14:21
I'm closing this issue as it is not a technical issue.
If you think it to be an issue please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
Please refer questions to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site.
Please refer improvements and feature requests  to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Closed as completed by veloraven** 2016-11-17 14:21 UTC
Labels: Progress: needs update
