### ISSUE TITLE
Placing order in Graphql using PayPal Express is slow

### ISSUE THREAD

**Issue by zexperto** [magento/magento2#37676] opened 2023-06-27 15:25 UTC
### Preconditions and environment

- Magento version 2.4.x
- PayPal Express sandbox

### Steps to reproduce

by Graphql
1- Get Customer Token
2- Get Customer Cart ID
3- add product to Cart
4- set the shipping address
5- set the shipping method
6- set the billing address
7- get PayPal token
8- set the Paymeth method with PayerId and Token
9- Place the order

the time to place the order took around 3.5 - 5 seconds 

### Expected result

placing the order should not take more than 1 to 2 seconds maximun

### Actual result

it took at least 3.5 seconds

### Additional information

everything standard no modules/no customization 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-07-06 09:39
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-07-14 07:34
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-07-17 07:47
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-09-12 12:44
Hi @zexperto,

Thank you for reporting and collaboration.

We have tried to reproduce the issue on Magento 2.4-develop instance.

**Steps to reproduce**

by Graphql

-  Get Customer Token
-  Get Customer Cart ID
-  add product to Cart
-  set the shipping address
-  set the shipping method
-  set the billing address
-  get PayPal token
-  set the Paymeth method with PayerId and Token
-  Place the order


We are not able to proceed further with placeOrder mutation could you please let us know we are missing anything.


<img width="1448" alt="Screenshot 2023-09-12 at 1 03 43 PM" src="https://github.com/magento/magento2/assets/51680745/fb813bba-dbcc-402f-8390-2e586c8d9552">




We are getting error **Unable to place order: A server error stopped your order from being placed. Please try to place your order again**.

As per this document https://developer.adobe.com/commerce/webapi/graphql/schema/cart/mutations/place-order/ we will get this error when we don't have products in cart but we have products in cart.

<img width="1462" alt="Screenshot 2023-09-12 at 1 12 40 PM" src="https://github.com/magento/magento2/assets/51680745/bc3b5d3e-7125-4ba2-82d8-8a1cf2fdf9ca">


Could you please help us to proceed further.


Thanks.

**Comment by zexperto** [comment] 2023-09-12 21:40
Hello @engcom-Bravo , the steps are correct, did you add the PayPal sandbox configuration in the backend? maybe this is the reason, I suggest to try first place an order by the frontend then try by the graphql

**Comment by engcom-Bravo** [comment] 2023-09-27 11:45
Hi @zexperto,

Thanks for your update.

We have added PayPal sandbox configuration and it is working fine from the frontend and we are able to place the order.
Similar issue has been confirmed here https://github.com/magento/magento2/issues/37824 we need to close this issue as Duplicate of this one https://github.com/magento/magento2/issues/37824. Kindly move onto this issue for latest updates / solutions on the same.


Thanks.

**Closed as completed by engcom-Bravo** 2023-09-27 11:45 UTC
Labels: duplicate, Project: GraphQL, Issue: needs update, Reported on 2.4.x
