### ISSUE TITLE
Filters not working on category pages in 2.4.5

### ISSUE THREAD

**Issue by harleeniweb** [magento/magento2#35960] opened 2022-08-17 08:24 UTC
### Preconditions and environment

- Magento version - 2.4.5 

### Steps to reproduce

Set **Display Out of Stock Products** to **Yes** in the configuration under _Store > Configuration > Catalog > Inventory_ in the admin.

### Expected result

Filters should only show matching results on the category pages
[
![Screenshot 2022-08-17 at 9 11 07 am](https://user-images.githubusercontent.com/79199454/185069975-affa2a30-2ab5-4a28-a4f6-5e85ae664fa5.png)
](url)

### Actual result

Instead it shows all the products in that category and works fine if I set **Display Out of Stock Products** to **No** 

![Screenshot 2022-08-17 at 9 20 04 am](https://user-images.githubusercontent.com/79199454/185070403-486a5d5b-cd0a-4abe-9e77-6db33f83a6f7.png)

### Additional information

This seems to be the **getProductsIdsBySaleability** function resetting the filtered products items added in the SearchResultApplier file.

https://github.com/magento/magento2/blob/2.4.5/app/code/Magento/Elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php
<img width="836" alt="Screenshot 2022-08-17 at 9 24 39 am" src="https://user-images.githubusercontent.com/79199454/185071353-e5c42da6-f712-441d-81fc-e5be41650946.png">

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-08-17 12:22
Hi @harleeniweb,

Thank you for reporting and collaboration.

When we are Set Display Out of Stock Products to Yes in the configuration we are not able to select size and color, but in your expected result we are able to select size and color.

Kindly provide exact steps to reproduce to replicate the issue.


Thanks,

**Comment by harleeniweb** [comment] 2022-08-17 12:37
Hi @engcom-Bravo 

you can replicate the issue with any filter that's displaying in the sidebar after the setting is set to Yes.

**Comment by gwharton** [comment] 2022-08-17 14:26
Duplicate of #35899

**Comment by gwharton** [comment] 2022-08-17 14:30
F.Y.I. this is the commit that broke it. https://github.com/magento/magento2/commit/3a889f465e21cdba4a78788704f3c5b31f3d2d9f

**Comment by maconeto** [comment] 2022-08-17 14:50
i got the same issue on my environment

**Comment by engcom-Bravo** [comment] 2022-08-18 09:35
@magento give me 2.4-develop instance

**Comment by drinkingsouls** [comment] 2022-08-18 10:22
Does your database have a prefix set?

**Comment by engcom-Bravo** [comment] 2022-08-18 12:54
Hi @harleeniweb,

Thanks for the update. Verified the issue on Magento 2.4-develop branch and the issue is reproducible with above steps to reproduce. however, similar issue has been confirmed [here](https://github.com/magento/magento2/issues/35899).


We are closing this issue as duplicate.


Thanks.

**Closed as completed by engcom-Bravo** 2022-08-18 12:54 UTC
Labels: duplicate, Reported on 2.4.5

**Comment by madbounce** [comment] 2022-08-18 18:00
@magento give me 2.4.3 instance
