### ISSUE TITLE
search page result price filter missing

### ISSUE THREAD

**Issue by Joshua-Ye** [magento/magento2#34810] opened 2021-12-14 03:21 UTC
### Preconditions (*)

1. Magento 2.4.3
2. Elasticsearch 7 on cloud server

### Steps to reproduce (*)

1. install M2
2. create one configurable product with several colors and different prices
3. enable price & color attribute in search results layered navigation
4. see the search result 

### Expected result (*)

1. price filter will show on sidebar in search result page

### Actual result (*)

1. there is no price filter on search result page
![20211214111131](https://user-images.githubusercontent.com/73095214/145926433-c098e3ff-6fb0-4e26-b325-95652b06ab20.png)
2.compared with search result page,category have the price filter
![20211214111404](https://user-images.githubusercontent.com/73095214/145927068-53c87a70-7da4-4cb3-b1f8-078cf4277e86.png)

**Comment by engcom-Hotel** [comment] 2021-12-14 08:05
Hello @Joshua-Ye,

We have tried to reproduce this issue in Magento 2.4-develop branch. But we are unable to reproduce it, we can see the `price` attribute in `Shopping Options` while searching. Please have a look at below screenshot for reference:

![image](https://user-images.githubusercontent.com/51681618/145957597-191523c6-1797-4a25-aff7-c11799a834e6.png)


Please let us know if we have missed anything in order to reproduce it.

Thanks

**Comment by Joshua-Ye** [comment] 2021-12-16 09:13
Hi @engcom-Hotel,

Thank you very much for your help.
I made a boo-boo. I apologize.
I regarded the Cost of product attribute to Price.
I am terrible sorry for these.
Please forgive me.
This issue can be closed.

Best Regards

**Comment by engcom-Hotel** [comment] 2021-12-17 07:36
Dear @Joshua-Ye,

Thanks for the confirmation!

As per your comment, we are closing this issue.

Thanks

**Closed as completed by engcom-Hotel** 2021-12-17 07:36 UTC
Labels: Issue: needs update
