### ISSUE TITLE
Creating Invoice from Sales Order View does not respect "Email Copy of Invoice" setting

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#30854] opened 2020-11-09 19:29 UTC
### Preconditions (*)

1. deploy 2.4-develop
2. Ensure test system is configured to send emails
3. Ensure system is set to send email on new Invoice (Config -> Sales -> Sales Emails)

### Steps to reproduce (*)

1. Create Test product
2. Make sale of test product with guest customer with valid email address
3. Got to sales order grid and open sales order view for order
4. Click "Invoice" button
5. Ensure "Email copy of Invoice" is unchecked
6. Click "Submit Invoice"

### Expected result (*)

1. The guest user email address does not receive confirmation of invoice

### Actual result (*)

1. The guest user receives the email

If you repeat the same process, but for shipment emails, the shipment emails are only sent if the "Email copy of Invoice" box is checked.

### Investigation

https://github.com/magento/magento2/blob/c644b3dc357622c453043ca368a937cd580360b0/app/code/Magento/Sales/Controller/Adminhtml/Order/Invoice/Save.php#L214-L222
Here the invoice email will ALWAYS be sent if the global setting Config->Sales->Sales Emails->Invoice->Enabled = YES
This is regardless of what is set on the form.

Here is the equivalent lines from the Credit Memo Save process
https://github.com/magento/magento2/blob/c644b3dc357622c453043ca368a937cd580360b0/app/code/Magento/Sales/Controller/Adminhtml/Order/Creditmemo/Save.php#L111-L113
You can see here, it ignores the global setting, and just does whatever is set on the form.

And here, the equivalent code from the Shipment Save process
https://github.com/magento/magento2/blob/c644b3dc357622c453043ca368a937cd580360b0/app/code/Magento/Shipping/Controller/Adminhtml/Order/Shipment/Save.php#L159-L161
Again, ignoring the global setting.

So, I would really expect all three to operate the same way, and would expect that if the tick box is unticked on the form, then the email should NOT be sent. i.e Credit Memo and Shipment have it right, and Invoice has it wrong.

The clue is in the name of that function "canSendNewInvoiceEmail". It returns whether the email CAN be sent, not whether it SHOULD be sent.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by gwharton** [comment] 2020-11-09 19:31
Shouldn't the test be

if (!empty($data['send_email']) && $this->salesData->canSendNewInvoiceEmail())

i.e the form has to be ticked, and the global setting enabled for the email to go, otherwise the email is not sent.

likewise, to be consistent, the same check should be made on Invoice, CreditMemo and Shipment forms.

**Comment by engcom-Alfa** [comment] 2020-11-10 07:53
Hi @gwharton . 

Seems the same issue is already reported in #28511.
So, we have to close it as a duplicate.

Thank you!

**Comment by engcom-Alfa** [comment] 2020-11-10 07:55
Duplicate of #28511

**Closed as completed by engcom-Alfa** 2020-11-10 07:55 UTC
