### ISSUE TITLE
The requested URL /magento/ was not found on this server

### ISSUE THREAD

**Issue by caneraydinbey** [magento/magento2#6535] opened 2016-09-08 07:27 UTC
### Preconditions

1.  Ubuntu 16.04
2.  magento 2.2 Apache/2.4.18 (Ubuntu) Server at localhost Port 80 php7.0
### Steps to reproduce

1. downloaded magento 2.1
2. extracted to www/html
3. installed from web.
### Expected result

1.  when i go to localhost/magento, i should see store. 2 days ago with php 5.6, i could see but it was not adding to store when i add items.
### Actual result

1.  when i go that url
   **Not Found

The requested URL /magento was not found on this server.

Apache/2.4.18 (Ubuntu) Server at localhost Port 80**

I try to install magaento2 with php7 apache2 from web.

it succeded. Installation succeeded. this page was shown.

```
Magento Admin Info:

Username:
admin
Email:
admin@test.com
Password:
******
Your Store Address:
http://localhost/magento/
Magento Admin Address:
http://localhost/magento/admin/
```

but when i click those linkss

 i got error

```
Not Found

The requested URL /magento/ was not found on this server.

Apache/2.4.18 (Ubuntu) Server at localhost Port 80
```

in other topics, people say

go to

```
/etc/php/7.0/apache2/conf.d
```

and some lines. But at that directory, i hve a lot of ini, it is not a texxtfile

```
“/etc/php/7.0/apache2/conf.d” is a directory.
```

when i try to open wit gedit

but for

```
gedit /etc/apache2/apache2.conf
```

it shows

```
# This is the main Apache server configuration file.  It contains the
# configuration directives that give the server its instructions.
# See http://httpd.apache.org/docs/2.4/ for detailed information about
# the directives and /usr/share/doc/apache2/README.Debian about Debian specific
# hints.
#
#
# Summary of how the Apache 2 configuration works in Debian:
# The Apache 2 web server configuration in Debian is quite different to
# upstream's suggested way to configure the web server. This is because Debian's
# default Apache2 installation attempts to make adding and removing modules,
# virtual hosts, and extra configuration directives as flexible as possible, in
# order to make automating the changes and administering the server as easy as
# possible.

# It is split into several files forming the configuration hierarchy outlined
# below, all located in the /etc/apache2/ directory:
#
#   /etc/apache2/
#   |-- apache2.conf
#   |   `--  ports.conf
#   |-- mods-enabled
#   |   |-- *.load
#   |   `-- *.conf
#   |-- conf-enabled
#   |   `-- *.conf
#   `-- sites-enabled
#       `-- *.conf
#
#
# * apache2.conf is the main configuration file (this file). It puts the pieces
#   together by including all remaining configuration files when starting up the
#   web server.
#
# * ports.conf is always included from the main configuration file. It is
#   supposed to determine listening ports for incoming connections which can be
#   customized anytime.
#
# * Configuration files in the mods-enabled/, conf-enabled/ and sites-enabled/
#   directories contain particular configuration snippets which manage modules,
#   global configuration fragments, or virtual host configurations,
#   respectively.
#
#   They are activated by symlinking available configuration files from their
#   respective *-available/ counterparts. These should be managed by using our
#   helpers a2enmod/a2dismod, a2ensite/a2dissite and a2enconf/a2disconf. See
#   their respective man pages for detailed information.
#
# * The binary is called apache2. Due to the use of environment variables, in
#   the default configuration, apache2 needs to be started/stopped with
#   /etc/init.d/apache2 or apache2ctl. Calling /usr/bin/apache2 directly will not
#   work with the default configuration.


# Global configuration
#

#
# ServerRoot: The top of the directory tree under which the server's
# configuration, error, and log files are kept.
#
# NOTE!  If you intend to place this on an NFS (or otherwise network)
# mounted filesystem then please read the Mutex documentation (available
# at <URL:http://httpd.apache.org/docs/2.4/mod/core.html#mutex>);
# you will save yourself a lot of trouble.
#
# Do NOT add a slash at the end of the directory path.
#
#ServerRoot "/etc/apache2"

#
# The accept serialization lock file MUST BE STORED ON A LOCAL DISK.
#
Mutex file:${APACHE_LOCK_DIR} default

#
# PidFile: The file in which the server should record its process
# identification number when it starts.
# This needs to be set in /etc/apache2/envvars
#
PidFile ${APACHE_PID_FILE}

#
# Timeout: The number of seconds before receives and sends time out.
#
Timeout 300

#
# KeepAlive: Whether or not to allow persistent connections (more than
# one request per connection). Set to "Off" to deactivate.
#
KeepAlive On

#
# MaxKeepAliveRequests: The maximum number of requests to allow
# during a persistent connection. Set to 0 to allow an unlimited amount.
# We recommend you leave this number high, for maximum performance.
#
MaxKeepAliveRequests 100

#
# KeepAliveTimeout: Number of seconds to wait for the next request from the
# same client on the same connection.
#
KeepAliveTimeout 5


# These need to be set in /etc/apache2/envvars
User ${APACHE_RUN_USER}
Group ${APACHE_RUN_GROUP}

#
# HostnameLookups: Log the names of clients or just their IP addresses
# e.g., www.apache.org (on) or 204.62.129.132 (off).
# The default is off because it'd be overall better for the net if people
# had to knowingly turn this feature on, since enabling it means that
# each client request will result in AT LEAST one lookup request to the
# nameserver.
#
HostnameLookups Off

# ErrorLog: The location of the error log file.
# If you do not specify an ErrorLog directive within a <VirtualHost>
# container, error messages relating to that virtual host will be
# logged here.  If you *do* define an error logfile for a <VirtualHost>
# container, that host's errors will be logged there and not here.
#
ErrorLog ${APACHE_LOG_DIR}/error.log

#
# LogLevel: Control the severity of messages logged to the error_log.
# Available values: trace8, ..., trace1, debug, info, notice, warn,
# error, crit, alert, emerg.
# It is also possible to configure the log level for particular modules, e.g.
# "LogLevel info ssl:warn"
#
LogLevel warn

# Include module configuration:
IncludeOptional mods-enabled/*.load
IncludeOptional mods-enabled/*.conf

# Include list of ports to listen on
Include ports.conf


# Sets the default security model of the Apache2 HTTPD server. It does
# not allow access to the root filesystem outside of /usr/share and /var/www.
# The former is used by web applications packaged in Debian,
# the latter may be used for local directories served by the web server. If
# your system is serving content from a sub-directory in /srv you must allow
# access here, or in any related virtual host.
<Directory />
    Options FollowSymLinks
    AllowOverride None
    Require all denied
</Directory>

<Directory /usr/share>
    AllowOverride None
    Require all granted
</Directory>

<Directory /var/www/>
    Options Indexes FollowSymLinks
    AllowOverride All 
    Require all granted
</Directory>

#<Directory /srv/>
#   Options Indexes FollowSymLinks
#   AllowOverride None
#   Require all granted
#</Directory>




# AccessFileName: The name of the file to look for in each directory
# for additional configuration directives.  See also the AllowOverride
# directive.
#
AccessFileName .htaccess

#
# The following lines prevent .htaccess and .htpasswd files from being
# viewed by Web clients.
#
<FilesMatch "^\.ht">
    Require all denied
</FilesMatch>


#
# The following directives define some format nicknames for use with
# a CustomLog directive.
#
# These deviate from the Common Log Format definitions in that they use %O
# (the actual bytes sent including headers) instead of %b (the size of the
# requested file), because the latter makes it impossible to detect partial
# requests.
#
# Note that the use of %{X-Forwarded-For}i instead of %h is not recommended.
# Use mod_remoteip instead.
#
LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %O" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent

# Include of directories ignores editors' and dpkg's backup files,
# see README.Debian for details.

# Include generic snippets of statements
IncludeOptional conf-enabled/*.conf

# Include the virtual host configurations:
IncludeOptional sites-enabled/*.conf

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```

when i change some parts, it affects the localhost root. for example when i dsable, localhost becomes forbidden.

this is error log 

```
[Thu Sep 08 10:08:07.838247 2016] [mpm_prefork:notice] [pid 27202] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Thu Sep 08 10:08:07.838287 2016] [core:notice] [pid 27202] AH00094: Command line: '/usr/sbin/apache2'
[Thu Sep 08 10:08:10.217465 2016] [mpm_prefork:notice] [pid 27202] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Thu Sep 08 10:08:10.264056 2016] [mpm_prefork:notice] [pid 27202] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Thu Sep 08 10:08:10.264067 2016] [core:notice] [pid 27202] AH00094: Command line: '/usr/sbin/apache2'
```

in

```
/var/log/apache2/error.log
```

i also created apache.conf like this

```
<VirtualHost *:80>
    DocumentRoot /var/www/html
    <Directory /var/www/html/>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
    </Directory>
</VirtualHost>
```

in

```
/etc/apache2/sites-available/magento.conf
```

and theen did this

```
sudo a2ensite magento.conf
sudo a2dissite 000-default.conf
```

i looked from here but

https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-magento-on-ubuntu-14-04

but nothing changed

and also did

http://devdocs.magento.com/guides/v2.0/install-gde/prereq/apache.html

**a2enmod rewrite**

/etc/apache2/sites-available/000-default.conf
i added those

**<Directory "/var/www/html">
    AllowOverride  <value from Apache site>
</Directory>**

then restarted but still same.

this is error log latest

**[Thu Sep 08 12:03:33.793836 2016] [mpm_prefork:notice] [pid 1931] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Thu Sep 08 12:03:33.793872 2016] [core:notice] [pid 1931] AH00094: Command line: '/usr/sbin/apache2'
[Thu Sep 08 12:07:41.111492 2016] [mpm_prefork:notice] [pid 1931] AH00169: caught SIGTERM, shutting down
[Thu Sep 08 12:07:42.257943 2016] [mpm_prefork:notice] [pid 2170] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Thu Sep 08 12:07:42.257974 2016] [core:notice] [pid 2170] AH00094: Command line: '/usr/sbin/apache2'**

so

```
Generated custom log for  site. Below DocumentRoot added 2 lines . "CustomLog /var/log/apache2/mysite-access.log combined" "ErrorLog /var/log/apache2/mysite-error.log" 
```

i put those to my apache conf.

this is error log only after apache restart

```
[Thu Sep 08 12:38:08.630069 2016] [mpm_prefork:notice] [pid 4059] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Thu Sep 08 12:38:08.630108 2016] [core:notice] [pid 4059] AH00094: Command line: '/usr/sbin/apache2'


now i try to navigate to
```

localhost/magento

no errorlog but for acccess

```
127.0.0.1 - - [08/Sep/2016:12:38:49 +0300] "GET /magento HTTP/1.1" 404 497 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
```

now i try to navigate to

localhost/magento2
url changes to 

http://localhost/magento/?SID=cq4mo1k2p1pik3me0ufk0p7ae4

access log (inclding previosu)

```
127.0.0.1 - - [08/Sep/2016:12:38:49 +0300] "GET /magento HTTP/1.1" 404 497 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
127.0.0.1 - - [08/Sep/2016:12:39:25 +0300] "GET /magento2/ HTTP/1.1" 302 490 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
127.0.0.1 - - [08/Sep/2016:12:39:25 +0300] "GET /magento/?SID=cq4mo1k2p1pik3me0ufk0p7ae4 HTTP/1.1" 404 497 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
```

error log

```
[Thu Sep 08 12:38:08.630069 2016] [mpm_prefork:notice] [pid 4059] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Thu Sep 08 12:38:08.630108 2016] [core:notice] [pid 4059] AH00094: Command line: '/usr/sbin/apache2'
```

now magento/admin
no error but accesss

```
127.0.0.1 - - [08/Sep/2016:12:38:49 +0300] "GET /magento HTTP/1.1" 404 497 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
127.0.0.1 - - [08/Sep/2016:12:39:25 +0300] "GET /magento2/ HTTP/1.1" 302 490 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
127.0.0.1 - - [08/Sep/2016:12:39:25 +0300] "GET /magento/?SID=cq4mo1k2p1pik3me0ufk0p7ae4 HTTP/1.1" 404 497 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
127.0.0.1 - - [08/Sep/2016:12:40:44 +0300] "GET /magento/admin HTTP/1.1" 404 503 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
```

now magento/setup

access

```
127.0.0.1 - - [08/Sep/2016:12:38:49 +0300] "GET /magento HTTP/1.1" 404 497 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
127.0.0.1 - - [08/Sep/2016:12:39:25 +0300] "GET /magento2/ HTTP/1.1" 302 490 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
127.0.0.1 - - [08/Sep/2016:12:39:25 +0300] "GET /magento/?SID=cq4mo1k2p1pik3me0ufk0p7ae4 HTTP/1.1" 404 497 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
127.0.0.1 - - [08/Sep/2016:12:40:44 +0300] "GET /magento/admin HTTP/1.1" 404 503 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
127.0.0.1 - - [08/Sep/2016:12:41:20 +0300] "GET /magento/setup/ HTTP/1.1" 404 504 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
```

error

```
[Thu Sep 08 12:38:08.630069 2016] [mpm_prefork:notice] [pid 4059] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Thu Sep 08 12:38:08.630108 2016] [core:notice] [pid 4059] AH00094: Command line: '/usr/sbin/apache2'
```

i think error still was nt changed

now magento 2/admin

access

```
127.0.0.1 - - [08/Sep/2016:12:38:49 +0300] "GET /magento HTTP/1.1" 404 497 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
127.0.0.1 - - [08/Sep/2016:12:39:25 +0300] "GET /magento2/ HTTP/1.1" 302 490 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
127.0.0.1 - - [08/Sep/2016:12:39:25 +0300] "GET /magento/?SID=cq4mo1k2p1pik3me0ufk0p7ae4 HTTP/1.1" 404 497 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
127.0.0.1 - - [08/Sep/2016:12:40:44 +0300] "GET /magento/admin HTTP/1.1" 404 503 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
127.0.0.1 - - [08/Sep/2016:12:41:20 +0300] "GET /magento/setup/ HTTP/1.1" 404 504 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
127.0.0.1 - - [08/Sep/2016:12:42:10 +0300] "GET /magento2/admin/ HTTP/1.1" 302 647 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
127.0.0.1 - - [08/Sep/2016:12:42:14 +0300] "GET /magento/admin/admin/index/index/key/5693df064035428c19e5fa184b4afa34e077e014143dd178179a37cff78cb0e1/ HTTP/1.1" 404 590 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"127.0.0.1 - - [08/Sep/2016:12:38:49 +0300] "GET /magento HTTP/1.1" 404 497 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
127.0.0.1 - - [08/Sep/2016:12:39:25 +0300] "GET /magento2/ HTTP/1.1" 302 490 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
127.0.0.1 - - [08/Sep/2016:12:39:25 +0300] "GET /magento/?SID=cq4mo1k2p1pik3me0ufk0p7ae4 HTTP/1.1" 404 497 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
127.0.0.1 - - [08/Sep/2016:12:40:44 +0300] "GET /magento/admin HTTP/1.1" 404 503 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
127.0.0.1 - - [08/Sep/2016:12:41:20 +0300] "GET /magento/setup/ HTTP/1.1" 404 504 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
127.0.0.1 - - [08/Sep/2016:12:42:10 +0300] "GET /magento2/admin/ HTTP/1.1" 302 647 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
127.0.0.1 - - [08/Sep/2016:12:42:14 +0300] "GET /magento/admin/admin/index/index/key/5693df064035428c19e5fa184b4afa34e077e014143dd178179a37cff78cb0e1/ HTTP/1.1" 404 590 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36"
```

error
same stilli think.

**Comment by andimov** [comment] 2016-09-08 09:09
@caneraydinbey 
Thanks for reporting this issue.
Please use our issue reporting template to describe this issue. The template specifies the version and configuration information we need to assess your issue. See the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) for more information.

**Comment by designbyadrian** [comment] 2016-09-08 12:40
This might be a silly question, but did you copy the .htaccess file from the installation folder?

**Comment by caneraydinbey** [comment] 2016-09-08 12:44
No. I even couldnot find the location of ht access.

**Comment by designbyadrian** [comment] 2016-09-08 12:46
It's an invisible file. It should still sit in the downloaded folder.

Or you can just take this: [htaccess.txt](https://github.com/magento/magento2/files/461648/htaccess.txt) then rename it. Don't trust anyone who sends htaccess files, though 😉

**Comment by andimov** [comment] 2016-09-13 07:06
@caneraydinbey 
You wrote magento 2.2 in "preconditions" and magento 2.1 in "steps to reproduce"
Please, specify which magento version you use.
Also check .htaccess file as @designbyadrian  adviced.

**Comment by andimov** [comment] 2016-09-27 09:39
@caneraydinbey 
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Closed as completed by andimov** 2016-09-27 09:39 UTC
Labels: Progress: needs update
