### ISSUE TITLE
Disabled payment methods show in Customer Dashboard

### ISSUE THREAD

**Issue by JacobDrummond** [magento/magento2#6659] opened 2016-09-18 20:30 UTC
### Preconditions (*)
1. Apache 2.4.17
2. MySQL  5.0.11-dev
3. PHP 5.6.15
4. Magento version: develop branch as of 15/09/2016 12:08:30. Commit hash: [7800e3791f71dc09d854581a2d8440b8100f593c](/magento/magento2/tree/7800e3791f71dc09d854581a2d8440b8100f593c).
### Steps to reproduce
1. Disable "Vault" and "Paypal" payment methods in Stores > Configuration > Sales > Payment Methods
2. Login as customer, and go to customer dashboard
### Expected result
1. "Stored Payment Methods" (Magento_Vault) and "Billing Agreements" (Magento_Paypal) should disappear from customer dashboard navigation.
### Actual result
1. Both navigation items appear, despite their corresponding modules being disabled: 
   ![payment-1](https://cloud.githubusercontent.com/assets/8377620/18618784/900f7cac-7de5-11e6-88b9-31fe6fe65f38.png)
### Cause
1. Layout XML files do not add navigation link using "ifconfig" attribute.
2. Here's the offending [Vault line](/magento/magento2/blob/7800e3791f71dc09d854581a2d8440b8100f593c/app/code/Magento/Vault/view/frontend/layout/customer_account.xml#L11)
3. Here's the offending [Paypal line](/magento/magento2/blob/7800e3791f71dc09d854581a2d8440b8100f593c/app/code/Magento/Paypal/view/frontend/layout/customer_account.xml#L14)
### Solution
1. Add  `ifconfig="paypal_alternative_payment_methods/express_checkout_us/express_checkout_required/enable_express_checkout"` and `ifconfig="braintree_section/braintree/active"` to the `Magento\Framework\View\Element\Html\Link\Current` blocks.

**Comment by YevSent** [comment] 2016-09-26 14:48
Hi, @JacobDrummond, thanks for reporting. We've created internal ticket MAGETWO-58963 .

**Comment by ctadlock** [comment] 2017-02-01 04:59
I would suggest that there be a way to hide the "Billing Agreements" nav item even if using PayPal Express Checkout if `Billing Agreement Signup = Never` in the config. It's confusing to most consumers (and admin) that operate stores that don't have "Billing Agreement". Its easily confused with stored credit cards which are provided by extensions for Authorize.NET CIM and Stripe.

**Comment by magento-engcom-team** [comment] 2017-10-06 13:30
@JacobDrummond, thank you for your report.
We've created internal ticket(s) MAGETWO-58963 to track progress on the issue.

**Comment by ctadlock** [comment] 2018-05-17 22:31
@magento-engcom-team Any update on this? Its been a couple years...

**Comment by magento-engcom-team** [comment] 2019-01-30 10:07
Hi @vasilii-b. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-04-11 13:30
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99144`, `MAGETWO-99145` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-07-10 23:05
Hi @JacobDrummond, @torhoehn, @vasilii-b. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. 

The fix will be available with the upcoming `2.3.3` release.

**Closed as completed by magento-engcom-team** 2019-07-10 23:05 UTC
Labels: Issue: Ready for Work, Component: Payment, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, good first issue, Component: Paypal, Component: Vault
