### ISSUE TITLE
mview.xml doesn't allow numbers in "module name"

### ISSUE THREAD

**Issue by bhapps** [magento/magento2#26222] opened 2020-01-01 00:42 UTC
### Preconditions (*)

1.Magento ver. 2.3.3
2.LAMP Build using Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-72-generic x86_64)

### Steps to reproduce (*)

1.Create extension that has a number in the module name and utilizing Materialized View
2.naming convention example: \MyCompany\My3rdExtension\
3.table resource example: mycompany_my3rdextension
4.Review also [magento/magento2/issues/24323#issue-486016132](https://github.com/magento/magento2/issues/24323#issue-486016132) which I beleive is related but this issue is covering the module name not vendor name

### Expected result (*)

1. [Screenshots, logs or description]
2. install without related issues below;

### Actual result (*)

1. [Screenshots, logs or description]
2. Running schema recurring...The XML in file "/app/code/MyCompany/My3rdExtension/etc/mview.xml" is invalid:
Element 'table', attribute 'class': [facet 'pattern'] The value 'MyCompany\My3rdExtension\...' is not accepted by the pattern '[a-zA-Z\\]+'.
Line: 3

**Comment by mrtuvn** [comment] 2020-01-02 04:32
Next update v2.3.4 will have this fix. So if you are using 2.3.3 problem still exist
Solution: Use module name without number or wait update

**Comment by engcom-Alfa** [comment] 2020-01-06 10:23
Hi, @bhapps. Thank you for your reporting.
We are not able to reproduce this issue on the fresh 2.4-develop instance.
The problem was solved by PR #24324 and the decision will be present in the next release.
So we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-01-06 10:23 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid, Reported on 2.3.3
