### ISSUE TITLE
Wysiwig vs UTF-8

### ISSUE THREAD

**Issue by serzhik** [magento/magento2#12333] opened 2017-11-17 15:10 UTC
### Preconditions
1. Magento 2.1.2

### Steps to reproduce
1. Go to "create new product" page
2. Set Description: "für"
3. Hide Editor

### Expected result
1. Description value: `<p>"für"</p>`

### Actual result
1. Decription value: `<p>"f&uuml;r"</p>`

**Comment by magento-engcom-team** [comment] 2017-11-17 15:44
@Serzhik, thank you for your report.
The issue is already fixed in develop branch, 2.2.1

**Closed as completed by magento-engcom-team** 2017-11-17 15:44 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
