### ISSUE TITLE
Product can't be re-assigned to a category after it was unassigned by Async Bulk REST API

### ISSUE THREAD

**Issue by mattiteraslahti** [magento/magento2#32461] opened 2021-03-12 11:54 UTC
### Preconditions (*)

1. Magento Commerce 2.3.6-p1
2. RabbitMQ set up and configured
3. Consumer for "async.operations.all" configured to be started via Magento cron (default)

### Steps to reproduce (*)

1. Assign a product to the category via Bulk REST API using "POST <host>/rest/all/async/bulk/V1/categories/byCategoryId/products" endpoint
2. Unassign the product from the category via Bulk REST API using "DELETE <host>/rest/all/async/bulk/V1/categories/byCategoryId/products/bySku" endpoint
3. Assign a product again to the category via Bulk REST API using "POST <host>/rest/all/async/bulk/V1/categories/byCategoryId/products" endpoint

### Expected result (*)

1. The product is assigned to the category

### Actual result (*)

1. The product is not assigned to the category

### Additional Information
If you kill the consumer process "bin/magento queue:consumers:start async.operations.all" between steps 2 and 3, you'll get the expected result. The hypothesis is that if you delete the category product link and create it again within the same consumer process, the original link ID is still cached in memory and \Magento\Catalog\Model\CategoryLinkRepository class is using the cached value.

**Comment by mattiteraslahti** [comment] 2021-03-12 12:01
I'm facing the same issue when creating configurable product child links through "POST {{host}}/rest/all/async/bulk/V1/configurable-products/bySku/child" endpoint.
If I delete the child product and create it again, and do the link again through the bulk API, it will fail.
Again, if I kill the consumer after the delete, linking the child product succeeds.

**Comment by hostep** [comment] 2021-06-11 08:43
Sounds valid and sounds dangerous, this shouldn't have been closed without any attention. @Den4ik or @ihor-sviziev could we get somebody to review this first please? Thanks!

**Comment by ihor-sviziev** [comment] 2021-06-13 13:02
Looks quite dangerous. Thank you @hostep 
/cc @sdzhepa

**Comment by engcom-Golf** [comment] 2021-06-14 14:09
@mattiteraslahti I tried reproducing this issue on Magneto 2.4.2 & 2.4-develop, but can't reproduce it. Kindly upgrade your version.  Snapshots attached for your reference.
Step 1: Product Inserted via Async Bulk Rest API 
![image](https://user-images.githubusercontent.com/51681547/121904646-ff538300-cd46-11eb-9ec8-933848261725.png)
Step 2: Product Deleted
![image](https://user-images.githubusercontent.com/51681547/121904945-417cc480-cd47-11eb-8608-202a26ada7a3.png)
Step 3: Repeated Step 1

Thus Product is successfully re-assigned to the same category after it was unassigned by Async Bulk REST API.

**Comment by engcom-Golf** [comment] 2021-06-29 07:04
@mattiteraslahti I haven’t heard back from you in a while, so I’m going to consider this as resolved.Thus Closing this Issue. Feel free to reopen if you have any further questions!

**Closed as completed** 2021-06-29 07:12 UTC
Labels: Issue:  Cannot Reproduce, non-issue, Component: AsynchronousOperations, Severity: S1, Reported on 2.3.6
