### ISSUE TITLE
Image Swatch size change not working

### ISSUE THREAD

**Issue by ghost** [magento/magento2#12647] opened 2017-12-12 10:11 UTC
### Preconditions

1. Magento Commerce 2.1.8
2. Have an active frontend theme whose first letter comes alphabetically before "Magento/blank" e.g. "Acme/default"
3. Have an "Visual swatch" attribute with at least one option
4. Have a configurable product that offers this "Visual swatch" as an option with one simple product using it.

### Steps to reproduce

1. In "app/design/frontend/YOUR THEME/etc/view.xml" add changes for the image swatches. (e.g. "YOUR THEME" may be "Acme/default")
```xml
<?xml version="1.0"?>
<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Config/etc/view.xsd">
    <media>
        <images module="Magento_Catalog">
            <image id="swatch_image" type="swatch_image">
                <width>250</width>
                <height>250</height>
            </image>
            <image id="swatch_thumb" type="swatch_thumb">
                <width>500</width>
                <height>500</height>
            </image>
            <image id="swatch_image_base" type="swatch_image">
                <width>250</width>
                <height>250</height>
            </image>
            <image id="swatch_thumb_base" type="swatch_thumb">
                <width>500</width>
                <height>500</height>
            </image>
        </images>
    </media>
</view>
```
1. Flush Magento Cache
1. In backend go to Stores => (Attributes) Product and edit your "Visual swatch" attribute
1. Upload a new image for the option used in the simple product.
1. Flush Magento Cache and go to the product detail page of that simple product
1. Inspect the "Visual swatch" option image with the inspector of your browser

### Expected result
The background image used for the visual swatch has the dimensions 250x250

### Actual result
The background image used for the visual swatch has the dimensions 30x20 which represents the default setting

__________________________________________________________________

### Underlying issue

The media helper in the module Magento_Swatches loops through all, even unused, themes in an alphabetical order to apply their view configuration. 
In our case loading the view configuration happened in the following order:
1. Acme/default     (swatch_image: 250x250, swatch_thumb: 500x500)
1. Magento/blank  (swatch_image: 30x20, swatch_thumb: 110x90)
1. Magento/luma   (swatch_image: 30x20, swatch_thumb: 110x90)

Each step overwrites its previous settings therefore we don't see the dimensions of the swatch image changing.

Uploading image for a visual swatch option happens here:
[Magento/Swatches/Controller/Adminhtml/Iframe/Show.php#L105](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Swatches/Controller/Adminhtml/Iframe/Show.php#L105)
```php
// ...
$this->swatchHelper->generateSwatchVariations($newFile);
```

generateSwatchVariations
[Magento/Swatches/Helper/Media.php#L184](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Swatches/Helper/Media.php#L184)
```php
// ...
$imageConfig = $this->getImageConfig();
```

getImageConfig
[Magento/Swatches/Helper/Media.php#L253](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Swatches/Helper/Media.php#L253)
```php
public function getImageConfig() {
    // ... 
    foreach ($this->themeCollection->loadRegisteredThemes() as $theme) {
    // ...
}
```

The problem is that the function loadRegisteredThemes returns all themes in an alphabetical order, even unused ones. It should load themes in the order they are used in frontend taking their hierarchy into account and also skip themes that are not used.

**Comment by magento-engcom-team** [comment] 2018-02-15 14:50
@joachim-havloujian, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2018-02-16 20:40
Hi @joachim-havloujian. Thank you for your report. 
The issue has been fixed in magento/magento2#13506 by @pmclain in 2.3-develop branch
Related commit(s):
 - [magento](https://github.com/magento2/dfd734e0dc9f4786cbe4735609760eb8766fab94/commit/dfd734e0dc9f4786cbe4735609760eb8766fab94)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment] 2018-11-15 09:38
Hi @TomashKhamlai. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Closed as completed** 2018-11-15 09:39 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by magento-engcom-team** [comment] 2018-11-15 09:42
Hi @TomashKhamlai. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.
