### ISSUE TITLE
Coupon Codes Usage Increases Although Placing Order Throws a Validation Error on Admin Dashboard

### ISSUE THREAD

**Issue by MeeGz** [magento/magento2#33100] opened 2021-05-30 13:09 UTC
### Preconditions (*)

1. Magento Version 2.4.2
3. Create a Cart Price Rule with coupon code: **Test** with **Use per customer** = 1 and **Uses per Coupon** = 1 with any off percentage on the whole cart
3. Create a simple product to create the order with
4. Create a new customer with this email: **email@email.com**

### Steps to reproduce (*)

1. Try to Create a new order (with creating new customer)
2. Use same email for the created customer before: **email@email.com** to throw a validation error of existing email
3. Select the created simple product
4. Use `test` coupon created on this order
5. place the order after inserting all other required data (shipping/billing/payment)

### Expected result (*)

1. Validation error of existing email is being thrown
2. `coupon_usage.times_used` should **NOT** be increased by 1 as the order has been not created yet

### Actual result (*)

1. Validation error of existing email is being thrown
2. `coupon_usage.times_used` increases by one and never be valid to be used again with no orders created

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by MeeGz** [comment] 2021-05-30 13:10
@magento give me 2.4-develop instance

**Comment by MeeGz** [comment] 2021-05-30 13:44
Confirmed on the provided environment

Kindly check the screenshots below.

1. Created coupon code `robusta` with Use per customer = 1 and Uses per Coupon = 1 
2. Tried to create an order as the screenshot below (with an existing email for another customer)
<img width="1374" alt="Screen Shot 2021-05-30 at 3 36 36 PM" src="https://user-images.githubusercontent.com/15185278/120106446-3fb6dc80-c15d-11eb-93dd-2b2b1e2f0d43.png">
3. on submitting the order I get this validation error
<img width="1372" alt="Screen Shot 2021-05-30 at 3 36 49 PM" src="https://user-images.githubusercontent.com/15185278/120106526-8efd0d00-c15d-11eb-9133-64596ee4b6ca.png">
4. on submitting once more (coupon removed and same validation error gets thrown) 
<img width="1374" alt="Screen Shot 2021-05-30 at 3 36 59 PM" src="https://user-images.githubusercontent.com/15185278/120106539-9de3bf80-c15d-11eb-845a-cc8cab32c371.png">
5. on trying to apply the coupon code I get this error
<img width="1373" alt="Screen Shot 2021-05-30 at 3 37 12 PM" src="https://user-images.githubusercontent.com/15185278/120106564-c5d32300-c15d-11eb-9125-83ef8bfb99ee.png">

So the code marked as used but it is not used as the order is not created.

**Comment by krishprakash** [comment] 2021-05-31 05:22
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2021-05-31 06:25
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42504` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by jonatasavila** [comment] 2021-06-10 21:03
@magento i'm work on it

**Comment by jonataswebjump** [comment] 2021-06-10 21:07
@magento I'm working on it

**Comment by jonataswebjump** [comment] 2021-06-10 21:08
@magento add to contributors team

**Comment by jonataswebjump** [comment] 2021-06-10 21:08
@magento I'm working on it

**Comment by jonataswebjump** [comment] 2021-06-10 22:07
@magento give me 2.4-develop instance

**Comment by tuanpht** [comment] 2022-01-18 09:34
I think this issue is fixed by https://github.com/magento/magento2/commit/f26c3ddac4ab1def55a5b3acee29cec9712b9194

**Comment by tuanpht** [comment] 2022-01-18 10:28
> I think this issue is fixed by f26c3dd

Sorry, it is not fixed.

The above commit hasn't fixed the root cause, which is when order submit failed: Decrement may be executed before Increment, because they are queue jobs and there is no mechanism to ensure which job should be run first.

https://github.com/magento/magento2/blob/44a86cbbc5a2d6c8309de34922818c3e04b2dcd1/app/code/Magento/SalesRule/Plugin/CouponUsagesIncrement.php#L52,L56

**Comment by Nuranto** [comment] 2023-05-24 12:14
Why is this process async at the first place ? If the queue has some load, and activity is high, it could result to unauthorized coupon usage ?!

If for some reason I'm wrong on that, then passing the `times_used` column to `signed` should solve the issue described by @tuanpht

**Comment by engcom-Bravo** [comment] 2024-06-14 04:10
Hi @MeeGz,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the attached video.


**Steps to reproduce**

- Try to Create a new order (with creating new customer)
- Use same email for the created customer before: [email@email.com](mailto:email@email.com) to throw a validation error of existing email
- Select the created simple product
- Use test coupon created on this order
- place the order after inserting all other required data (shipping/billing/payment)


https://github.com/magento/magento2/assets/51680745/d459f8fe-c7ed-495f-8c6e-94799bac1b4d


Validation error of existing email is being thrown
coupon_usage.times_used should NOT be increased by 1 as the order has been not created yet

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-14 04:10 UTC
Labels: Component: Sales, Issue: Confirmed, Component: Admin, Reproduced on 2.4.x, Priority: P2, Severity: S3, Progress: done, Area: Cart & Checkout
