### ISSUE TITLE
Fake User registrations

### ISSUE THREAD

**Issue by terrybakshi** [magento/magento2#25705] opened 2019-11-23 03:13 UTC
### Preconditions (*)
   Magento 2.2.7
   PHP 7.0

 Fake user registration 
     - Magento 2.2.7,
     - User are getting registered even when putting link or spam text in name and last name field,
     - Expected results should be no more than 10 or 15 character allowed in User Name and last name field on registration page,

### Steps to reproduce (*)
   
-->
1. User are getting registered even when putting link or spam text in name and last name field,
you just type any character it will just register no matter what.

### Expected result (*)
1. Expected results should be no more than 10 or 15 character allowed in User Name and last name field on registration page. There should be limit on character to use in these fields.

### Actual result (*)

1. [Screenshots, logs or description]
![Untitled](https://user-images.githubusercontent.com/13229022/69472206-19dba980-0dfb-11ea-930e-6c18c0b64f89.png)

**Comment by terrybakshi** [comment] 2019-11-23 11:13
I have already provided all the asked information, Also what is the point of continuing focusing on new magento versions when basic security features are always missing in all the Version that have been out so far. Tested and found the same issue in Magento 2.3.3.

![Screenshot (71)](https://user-images.githubusercontent.com/13229022/69478147-1b30c480-0e43-11ea-81d9-1002602fb5b0.png)

**Comment by magenx** [comment] 2019-11-24 10:24
Duplicate of https://github.com/magento/magento2/issues/7266

**Comment by terrybakshi** [comment] 2019-11-24 11:06
> Duplicate of #7266

But still no fix as of yet.

**Comment by engcom-Echo** [comment] 2019-11-25 12:02
Hello @terrybakshi 

Thank you for your report and collaboration!
This issue is duplicate of [#7266](https://github.com/magento/magento2/issues/7266)

So I close it.
Thanks for your report!

**Closed as completed by engcom-Echo** 2019-11-25 12:02 UTC
Labels: Issue: Format is valid
