### ISSUE TITLE
Sales Order Grid - Mass Action - Multi Page Select All not working 

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#33113] opened 2021-06-01 10:09 UTC
Sales Order Grid - Mass Action - Multi Page Select All not working. Only the records on the page visible are affected. 

### Preconditions (*)

1. Magento 2.4.2-p1

### Steps to reproduce (*)

1. Deploy fresh store
2. Create test product
3. Purchase test product 3 times to create 3 orders
4. Go to Sales Order Grid
5. Change pagination to Custom Value of 2
6. Select All. Verify that it says 3 selected
7. Select Hold Mass Action

### Expected result (*)

1. All 3 orders are placed on hold

### Actual result (*)

1. Only the two visible orders are placed on hold

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment] 2021-06-01 10:38
:white_check_mark: Confirmed by @Den4ik 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42517` were created

**Issue Available**: @Den4ik, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Den4ik** [comment] 2021-06-01 11:01
@magento I'm working on it

**Comment by engcom-Bravo** [comment] 2024-06-12 04:45
Hi @gwharton,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.kindly refer the screenshots.

<img width="1294" alt="Screenshot 2024-06-12 at 10 13 41" src="https://github.com/magento/magento2/assets/51680745/1a8b38de-8c26-43d6-a1f3-94dbc239140c">


All 3 orders are placed on hold

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-12 04:45 UTC
Labels: Component: Sales, Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Progress: done
