### ISSUE TITLE
Shipping method subscriber callbacks are called twice

### ISSUE THREAD

**Issue by danslo** [magento/magento2#5814] opened 2016-07-26 11:08 UTC
In checkout, we can subscribe to shippingAddress observable. Something like:

``` js
quote.shippingMethod.subscribe(function(address) {
    // do something interesting with shipping method
});
```

However, this callback is executed twice when selecting a shipping method. This can cause issues with double AJAX calls for custom components.
### Steps to reproduce
1. Create a component that subscribes to shippingMethod observable as seen above.
2. Go to the checkout and click on a shipping method.
### Expected result
1. Code is executed once.
### Actual result
1. Code is executed twice.

**Comment by veloraven** [comment] 2016-07-29 14:13
@danslo thank you for your report.
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by danslo** [comment] 2016-07-29 14:31
@veloraven

This is on Magento 2.1.0.

**Comment by danslo** [comment] 2016-08-02 08:15
@veloraven I have submitted a pull request which fixes this issue.

**Comment by viktym** [comment] 2016-09-30 11:47
Hi @danslo 
I’m closing this issue because it is a duplicate https://github.com/magento/magento2/pull/5928
Thanks for contributing

**Closed as completed by viktym** 2016-09-30 11:47 UTC
Labels: bug report, Component: Checkout
