### ISSUE TITLE
Request rest API URL issue

### ISSUE THREAD

**Issue by gcampedelli** [magento/magento2#22481] opened 2019-04-24 14:54 UTC
Preconditions (*)

1. Magento Version 2.2.6 Community Edition
2. Server Apache 2
3. Varnish
4. Redis

Steps to reproduce (*)

1. Make an API request to get product attributes and respective response using browser or Postman without Bearer Authorization. 
2. First API request using encoded URL - https://mymagento2domain.com/rest/default/V1/products/attributes?searchCriteria[filterGroups][0][filters][0][field]=attribute_id&searchCriteria[filterGroups][0][filters][0][condition_type]=gt&searchCriteria[filterGroups][0][filters][0][value]=0
3. Make another API request using unencoded url https://mymagento2domain.com/rest/default/V1/products/attributes?searchCriteria%5BfilterGroups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bfield%5D=attribute_id&searchCriteria%5BfilterGroups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bcondition_type%5D=gt&searchCriteria%5BfilterGroups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bvalue%5D=0

Expected result (*)
1. Both API requests same resources and should have same response, while not authorized shouldn't return attributes requests

Expected Result

Both calls should return same response. 

Actual result (*)

1. Encoded URL returns right response, returning all attributes and correct headers, and %consumer is not authorized%. 
2. Unencoded URL returns an old API response, all attributes are visible, even if not authorized, incorrect headers and older attributes configuration. Please see screeshot request was made today and it returns a response from 10 april. 
![image](https://user-images.githubusercontent.com/7084395/56669129-0d397c00-6687-11e9-953e-95196f87b758.png)

**Comment by gcampedelli** [comment] 2019-08-16 11:15
I confirm the issue still exists in 2.2.6 instance. 
1- Preconditions: 
Magento 2.2.6
Apache 2
Varnish and Redis installed

2- Steps to take
Create New attribute. Assign attribute to attribute set. Declare attribute in product
Create API request to check if attribute is showing in the results
Request urls: 
https://mymagento2domain.com/rest/default/V1/products/attributes?searchCriteria[filterGroups][0][filters][0][field]=attribute_id&searchCriteria[filterGroups][0][filters][0][condition_type]=gt&searchCriteria[filterGroups][0][filters][0][value]=0

https://mymagento2domain.com/rest/default/V1/products/attributes?searchCriteria%5BfilterGroups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bfield%5D=attribute_id&searchCriteria%5BfilterGroups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bcondition_type%5D=gt&searchCriteria%5BfilterGroups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bvalue%5D=0

3- Expected results - Both results urls should show the new attribute

4 - Actual Result 
Results are different in the urls. 
First url shows the new attribute
Second url show cached result without the attribute. 

5- Not tested in 2.3.x instance.

**Comment by engcom-Charlie** [comment] 2019-08-21 07:34
Hello @gcampedelli 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.

We are closing this issue due to branch 2.2-develop was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.
See Accepted pull requests and ported code for more details

If you still faced this issue on 2.3 please create a new Issue with all required details according to Issue reporting guidelines

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-08-21 07:34 UTC
Labels: Issue: Clear Description, Issue: Format is valid, Component: Elasticsearch
