### ISSUE TITLE
GraphQL Customer Newsletter Subscriptions are inconsistent in multi website setups

### ISSUE THREAD

**Issue by pawel-siejba** [magento/magento2#33599] opened 2021-07-27 09:07 UTC
Customer type is_subscribed field value is taken from the customer website: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CustomerGraphQl/Model/Resolver/IsSubscribed.php#L52

When you're updating the subscription via createCustomer/createCustomerV2/updateCustomer/updateCustomerV2 mutation the subscription store is taken from the current store: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CustomerGraphQl/Model/Customer/UpdateCustomerAccount.php#L115

### Preconditions (*)

1. Magento version 2.4.2(probably more)
2. At least 2 websites
3. Customer Global accounts enabled

### Steps to reproduce (*)

1. Create customer account in the 1st website
2. Subscribe to newsletter from the 2nd website
3. Confirm your subscription

### Expected result (*)

1. Customer can see that he's subscribed

### Actual result (*)

1. Customer can't see that he's subscribed as the subscription data is taken from the website he created his account in, but the subscription is created for the website/store he was browsing from when updating the subscription.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment] 2021-08-06 12:02
:white_check_mark: Confirmed by @Den4ik 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-43013` were created

**Issue Available**: @Den4ik, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment] 2021-08-20 10:00
Verified the issue on Magento 2.4-develop branch and the issue is reproducible.

Preconditions (*)
1. At least 2 websites setup 
https://devdocs.magento.com/guides/v2.4/config-guide/multi-site/ms_websites.html
2. Customer Global accounts enabled
https://docs.magento.com/user-guide/customers/account-scope.html

Steps To Reproduce
1. Create customer account in the 1st website
<img width="1315" alt="CretaeAccountFirstStore" src="https://user-images.githubusercontent.com/51680745/130215632-920fade1-2df4-4f53-a90f-6343d72e5b38.png">

2. Sign in to 2nd website using same credentials
<img width="1371" alt="LoginToSecondStore" src="https://user-images.githubusercontent.com/51680745/130215679-13ad3ca1-3b46-47c8-abc3-0bcff9e5f1b8.png">

3. Subscribe to newsletter from the 2nd website
<img width="1374" alt="NewletterSubscribe" src="https://user-images.githubusercontent.com/51680745/130215747-099e4202-61de-4b64-8606-c7fc420d9a45.png">

4. Confirm your subscription
<img width="1042" alt="ConfirmNewsletterSubscription" src="https://user-images.githubusercontent.com/51680745/130215778-c20a8956-8772-4868-a798-5661cd0fa90a.png">

5. Subscription can be seen in 2nd website
<img width="1359" alt="NewsletterSubscribeSecondStore" src="https://user-images.githubusercontent.com/51680745/130215833-0feaade7-f81b-4828-bdb6-e6d5f2c1be50.png">

6. Go to 1st website MyAccount->NewsLetter Subscription. Subscription is not shown 
<img width="1374" alt="NewsletterNotSubscriberInFirstStore" src="https://user-images.githubusercontent.com/51680745/130215919-9c5de006-d3d1-46a1-af10-10a00da4302c.png">

**Comment by engcom-Alfa** [comment] 2022-05-31 08:18
Hello @pawel-siejba 
As I can see this issue got fixed in the scope of the internal Jira ticket AC-2797 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-2797&type=commits

Based on Jira, target version is 2.4.5

**Closed as completed by engcom-Alfa** 2022-05-31 08:18 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Component: CustomerGraphQl, Priority: P1, Severity: S1, Project: GraphQL, Progress: done, Reported on 2.4.2, Area: APIs
