### ISSUE TITLE
Magento 2 not supporting BCRYPT passwords introduced in SUPEE-11219

### ISSUE THREAD

**Issue by SamJUK** [magento/magento2#26731] opened 2020-02-06 12:47 UTC
### Preconditions (*)

1. Magento 2.3.4
2. Magento 1.9.3.9 (Patched with SUPEE-11219_CE_1939)

### Steps to reproduce (*)

1. Create a user account on a Magento 1 store with SUPEE-11219 Applied
2. Migrate data to Magento 2 using data migration tool
3. Try to login with the user details

### Expected result (*)

1. Customer who set their password after SUPEE-11219 was applied can log into account without reseting their password.

### Actual result (*)

1. Customer gets an invalid password error. 

### Additional Information `2.4-develop`
This case has been verified for current `2.4-develop` and was [confirmed here](https://github.com/magento/magento2/issues/26731#issuecomment-584703503) that issue still actual

Rechecked with: 
Magento 1.9.3.9 and [SUPEE-11219_CE_1939](https://magento.com/security/patches/supee-11219)
Data Migration tool [`2.3.4`](https://github.com/magento/data-migration-tool)
Magento 2.4-develop

### Actual Result:
After migrating, the customers appeared in Magento 2.4- develop  _Customers - All Customers_ grid
But Sign In to Storefront fails 
The customer is still able to Sign In Magento 1.9.3.9 Storefront
![customer](https://user-images.githubusercontent.com/51680745/74252809-d7898080-4cf6-11ea-96b4-2de8033de2b9.png)

**Comment by engcom-Bravo** [comment] 2020-02-11 15:52
@sdzhepa The issue is reproducible if migrate to Magento 2.4-develop

Rechecked with: 
Magento 1.9.3.9 and SUPEE-11219_CE_1939
Data Migration tool [`2.3.4`](https://github.com/magento/data-migration-tool)
Magento 2.4-develop

### Actual Result:
After migrating, the customers appeared in Magento 2.4- develop  _Customers - All Customers_ grid
But Sign In to Storefront fails 
The customer is still able to Sign In Magento 1.9.3.9 Storefront
![customer](https://user-images.githubusercontent.com/51680745/74252809-d7898080-4cf6-11ea-96b4-2de8033de2b9.png)

**Comment by magento-engcom-team** [comment] 2020-02-11 19:30
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31414` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by pipe-devnull** [comment] 2020-02-12 09:20
Hi,

I have this issue migrating from 1.9.4.X to  2.3.4.  I just found this issue while partway through a migration and now have thousands of accounts with passwords that will not work on the M2.3.4 site.   Do you have a workaround?

**Comment by SamJUK** [comment] 2020-02-12 09:54
We got the client to just get customers to reset their password until a offical mage fix, since its around 5% of the userbase affected. 

If you wanted to implement a fix, although i haven't tried it, you could do something along the lines of modifying the `isValidHash` method of  `\Magento\Framework\Encryption\Encryptor`. Where you chec the first 4 characters and if they match the start of a bcrypt password `$2y$`, if so try the password_verify function against it. Obviously test on a dev site and make sure you test through thoroughly before implementing in a live environment. 

So something like
```php
public function isValidHash($password, $hash)
{
if (stripos($hash, '$2y$') === 0) {
    return password_verify($password, $hash);
}
...
}
```

**Comment by pipe-devnull** [comment] 2020-02-12 10:44
Thanks for  your comment @SamJUK -  I've just implemented almost the same patch myself in that class since posting my question:

`
          if (stripos($hash, "$2Y$10") > === 0 && function_exists('password_hash')) {
                return password_verify($password, $hash);
            }
`
It's important to us because a lot of those customers affected will be new/active customers.

**Comment by Fidelity88** [comment] 2020-02-12 13:37
> `if (stripos($hash, "$2Y$10") > === 0 && function_exists('password_hash')) { return password_verify($password, $hash); }`

Is it just me, or does the function password_hash and/or password_verify does not exist in Encryptor.php on Magento 2.3.3?

**Comment by SamJUK** [comment] 2020-02-12 13:47
Both `password_hash` and `password_verify` should be available on Magento 2 since they are native PHP functions added in PHP 5.5 according to the PHP docs.

**Comment by victor-v-rad** [comment] 2020-03-11 17:04
@SamJUK @Fidelity88 @pipe-devnull You can try to use this fix https://github.com/magento/data-migration-tool/commit/3c7f83b8eaab690734113f574a26595e61415b62 clean cache and empty magento_root/generated directory. When customers login the tool will validate the password and rehash it in algorithm which Magento 2 understand.

**Comment by hostep** [comment] 2020-06-04 06:55
Hi @sdzhepa or @victor-v-rad 

What is the status over here?
Are there plans to put the solution from https://github.com/magento/data-migration-tool/commit/3c7f83b8eaab690734113f574a26595e61415b62 into core Magento?
Because not everybody who migrates from an M1 to M2 database is using your data-migration-tool module 🙂

Thanks!

**Comment by victor-v-rad** [comment] 2020-08-17 19:29
@hostep @SamJUK 
It is recommended to use Data Migration Tool to fix this issue and it is the easiest way. You just need to install it into your Magento 2 and it will take care of BCRYPT passwords. As an alternative you can upgrade your Magento 1 to 1.9.4.5/1.14.4.5. These versions has the fix as well. But you need to wait until all the customers relogin and their passwords get rehashed with SHA256 algorithm which is compatible with Magento 2 and then migrate. Also you can try to find similar solution in Magento Marketplace extensions.

**Comment by sdzhepa** [comment] 2020-08-17 21:06
Thank you @victor-v-rad  for the update and details 
It seems Issue already resolved and we can close it

cc: @hostep

**Closed as completed by sdzhepa** 2020-08-17 21:06 UTC
Labels: Issue: Ready for Work, Component: Customer, Issue: Confirmed, Issue: Format is valid, Component: Encryption, Reproduced on 2.4.x, Reported on 2.3.4
