### ISSUE TITLE
Reward points balance history UI overlap in luma

### ISSUE THREAD

**Issue by Vigneshmuthusamy** [magento/magento2#26041] opened 2019-12-14 10:47 UTC
### Preconditions (*)

1. M2EE 2.3.3
2. Luma theme

### Steps to reproduce (*)

1. As a customer, login into your account in frontend
2. Goto Reward points section from My account sidebar.
3. In the Balance History section we should have atleast 2 pages

### Expected result (*)

1. ![Reward Points-expected](https://user-images.githubusercontent.com/11820699/70847689-1f259480-1e8d-11ea-89e5-891b45359ad4.png)

### Actual result (*)

1. ![Reward Points](https://user-images.githubusercontent.com/11820699/70847662-ca821980-1e8c-11ea-8840-2055ae04f195.png)

**Comment by krzksz** [comment] 2019-12-16 10:53
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2019-12-16 10:53
Hi @krzksz. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-12-16 10:53
Hi @krzksz, here is your [Magento instance](https://i-26041-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26041-2-4-develop.instances.magento-community.engineering/admin](https://i-26041-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krzksz** [comment] 2019-12-16 11:13
Hello @Vigneshmuthusamy, thanks for you contribution. Unfortunately, because of the fact that this is the EE feature and it is not reproducible here I'm going to close it.

Worry not, I'm going to pass this issue and try to fix it for EE version and get back to you once it is fixed there.

**Closed as completed by krzksz** 2019-12-16 11:13 UTC
Labels: Area: Frontend, Issue: Format is valid, Area: Design/Frontend, Partner: Ziffity
