### ISSUE TITLE
While updating the order status increment_id is also updating why?

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#33666] opened 2021-08-03 07:58 UTC
### Preconditions (*)

1. Magento version 2.3.1

### Steps to reproduce (*)

1. Call the API /rest/V1/orders
2. Provide the following request in API
{"entity":{"entity_id":287,"status":"pending"}}
3. Now downlaod the order id 287
4. You will see increment_id is updated on UI and in order downlaod response as well.

### Expected result (*)

1.When we are updating only status it should only update status. it should not update increment_id
2.

### Actual result (*)

1.When we are updating the status it should only update status. its updating increment_id
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by ajijshekh123** [comment] 2021-08-03 08:14
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2021-08-06 11:06
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible:
**Steps performed:**
1. Created a new Order from front-end (Add a product to cart, checkout and submit payment using check/Money Order) - New Order is created with entity_id=24, Increment_id=000000029
Order status is "Pending"
2. API - Generate Admin access token using /rest/default/V1/integration/admin/token
3. Send POST request to /rest/V1/orders to update the Order status from "pending" to "processing"
4. Verify increment_id for the same Order in UI and DB - **No issue**
increment_id is not getting updated. It remains the same value
5. Sent the request multiple times - Only Order status is getting updated. increment_id remains same.

![image](https://user-images.githubusercontent.com/60198231/128501227-a483fda2-8278-4f15-a76f-c90e4990a45c.png)
![image](https://user-images.githubusercontent.com/60198231/128501346-aa6d6852-223e-4316-9f8e-30209e232967.png)
![image](https://user-images.githubusercontent.com/60198231/128501374-b69976f8-1138-490a-84fa-d146f05316c2.png)

select increment_id from sales_order;
select increment_id from sales_order where entity_id=24;
+--------------+
| increment_id |
+--------------+
| 000000029    |
+--------------+
@webgility-amazonapi , Kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2021-08-23 05:42
@webgility-amazonapi, we are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-08-23 05:42 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
