### ISSUE TITLE
Configurable product options incorrect when using an attribute source model

### ISSUE THREAD

**Issue by KevinMace** [magento/magento2#7052] opened 2016-10-17 11:09 UTC
### Preconditions

1.  Magento Enterprise Edition 2.1.1
2. PHP 7.0.8
### Steps to reproduce

1. Install a new attribute via a setup script that uses a source model for its values (as an example, like the core does here Magento\Catalog\Model\Product\Attribute\Source\Boolean) and add to the default attribute set.
2. Create two new simple products with different options from the attribute you just created.
3.  Create a configurable product and manually add the two simple products you just created, using your recently created attribute as the two options. Save the product.
### Expected result
1. If you then view the product on the frontend, the option values shown in the dropdown should be  taken from the source model.  I should see `Black` and `Blue` as options. I would also expect these two values to be shown when exporting the configurable product in the admin.
### Actual result
1. If you then view the product on the frontend, the option values shown in the dropdown are taken from the `eav_attribute_option_value` database table and not from the attributes source model. This same issue also occurs when you try to export the same product in the admin. In my example I see `female` and `null`

<img width="353" alt="screen shot 2016-10-17 at 12 07 19" src="https://cloud.githubusercontent.com/assets/1065240/19435400/5078a97c-9462-11e6-8359-470ff9142d2b.png">

View from within the admin.

<img width="1315" alt="screen shot 2016-10-17 at 12 05 53" src="https://cloud.githubusercontent.com/assets/1065240/19435409/5b53732c-9462-11e6-92aa-fb23e3638175.png">

**Comment by veloraven** [comment] 2016-10-17 12:15
@KevinMace thank you for your feedback.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.

**Comment by KevinMace** [comment] 2016-10-17 13:08
Hi @veloraven I have raised this issue with EE support as well, I just thought it was worth putting here incase a CE user was having the same issue.

**Comment by pguedesbr** [comment] 2016-10-18 12:10
I've also already reported this here https://github.com/magento/magento2/issues/6719#issuecomment-252467721 more than weeks ago.

**Comment by oshmyheliuk** [comment] 2016-11-16 15:07
Hi @KevinMace ,
I’m closing this issue because it is a duplicate of [#6719](https://github.com/magento/magento2/issues/6719) and we've created internal ticket for that issue. 
Please reopen this issue as needed.

**Closed as completed by oshmyheliuk** 2016-11-16 15:07 UTC
