### ISSUE TITLE
Checkout page login not working

### ISSUE THREAD

**Issue by meetvora69** [magento/magento2#37577] opened 2023-06-05 06:27 UTC
### Preconditions and environment

2.4.6 -p1

### Steps to reproduce

1. Goto checkout page
2. Enter already registed customer email address
3. error showing after email address put

### Expected result

After email address added on checkout page then check If customer is already login or not If login then show the password field and then show login button. So already registerd customer login site.

### Actual result

Currently after enter email address of already registred customer in checkout page, password field has not be visible that's why already register customer not placed and order .

Every order placing as a guset If customer is already registerd.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-06-05 06:33
@magento give me 2.4-develop instance

**Comment by meetvora69** [comment] 2023-06-05 06:44
Hi @engcom-Bravo, issue in 2.4.6 -p1 version.

**Comment by engcom-Bravo** [comment] 2023-06-05 13:55
@hostep Thanks for your contribution & collaboration over here

Hi @meetvora69,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.


**Steps to reproduce**

- Goto checkout page
- Enter already registed customer email address
- error showing after email address put


After adding email address on checkout page we are able to get the If customer is already login or not and also login fields are showing.


https://github.com/magento/magento2/assets/51680745/853eb2f3-a230-437b-b5b9-06b978f74451


As per this document https://experienceleague.adobe.com/docs/commerce-operations/release/planning/schedule.html?lang=en 2.4.6-p1 will be available from June 13, 2023.

it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-06-06 12:52
@hostep Thanks for your contribution & collaboration over here.

@meetvora69,


We have installed 2.4.6-p1 and verified the issue and we are not able to reproduce the issue.Kindly refer the screenshots and  attached video.


**Steps to reproduce**

- Goto checkout page
- Enter already registed customer email address
- error showing after email address put

As per this comment https://github.com/magento/magento2/issues/37577#issuecomment-1576812441 a new feature has been added in configuration to enhance security.

when **Enable Guest Checkout Login** to **No**. Password field is not visible.



<img width="1164" alt="Screenshot 2023-06-06 at 12 31 40 PM" src="https://github.com/magento/magento2/assets/51680745/f6b69b09-152b-4947-b624-952fec109d4b">


<img width="751" alt="Screenshot 2023-06-06 at 12 31 35 PM" src="https://github.com/magento/magento2/assets/51680745/8c357eb5-a333-4f52-878e-38b8b70e9455">



When **Enable Guest Checkout Login** to **Yes** Password field is visible and we are able login to registered customer.Please try to enable to Yes.



<img width="1094" alt="Screenshot 2023-06-06 at 12 32 46 PM" src="https://github.com/magento/magento2/assets/51680745/cdebb8d5-f1ed-449b-821c-3d7aea4f0350">




https://github.com/magento/magento2/assets/51680745/127ff933-a7e4-47ce-adf9-29a634bc4c5e


We are closing this issue as expected behaviour.


Thanks.

**Closed as completed by engcom-Bravo** 2023-06-06 12:52 UTC
Labels: non-issue, Reported on 2.4.6-p1

**Comment by densen45** [comment] 2023-06-27 08:05
Thank you @meetvora69 for reporting this issue and @hostep to be aware of this. I am very happy that I found this before I invested quite a few hours to figure it out.

@engcom-Bravo For the cleanliness, you assigned a wrong version label to this issue. It was reported on 2.4.6-p1.
