### ISSUE TITLE
Catalog Price Rules not applied to custom options that are a part of Configurable Products

### ISSUE THREAD

**Issue by msyhr** [magento/magento2#36564] opened 2022-12-02 21:29 UTC
### Preconditions and environment

2.4.5-p1

Sample data installed. 

### Steps to reproduce

1. Create a catalog discount. In this case global 20% discount. 
![rule](https://user-images.githubusercontent.com/22968596/205386924-6fd48712-52f4-4225-bf14-6d1526d5de38.png)

2. Create a custom option with a price and assign it to both a configurable product and simple product.
![custom_option_config](https://user-images.githubusercontent.com/22968596/205386988-3227a3c8-5645-4741-b9d1-796c92d54de7.png)

3. Run cron / indexes / etc.
4. View Product on the frontend as a customer group that should receive global discount.

### Expected result

Both product's  custom option have applied discounts.

### Actual result

Custom options assigned to configurable products do not receive discount:

![image](https://user-images.githubusercontent.com/22968596/205387319-dc7587e7-0044-4d54-9ef1-b701e90717ac.png)

Custom option assigned to simple product do display receive discount discount:

![image](https://user-images.githubusercontent.com/22968596/205387528-017db22f-9c2b-4149-95bf-3a9ee552614e.png)

### Additional information

Not sure if this is intended functionality or a bug  because [documentation](https://experienceleague.adobe.com/docs/commerce-admin/marketing/promotions/catalog-rules/price-rules-catalog-create.htmll) states  "Fixed Price product Customizable Options are not affected by Group Price, Tier Price, Special Price, or Catalog Price rules" but that seems to be only the case for configurable products (currently)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by prince1jassi1** [comment] 2022-12-05 12:13
@magento give me 2.4.5-p1 instance

**Comment by msyhr** [comment] 2022-12-05 16:54
@prince1jassi1, you seem to be misunderstanding my issue. The issue is not the price being added to the parent product and the total cost of the item. The issue is that is the discounting is inconsistent. Both products in the above screenshot have a 10$ Fixed custom option assigned to them. However, the configurable product's custom option is not discounted, while the simple products custom option price is. (10$ vs 8$ in the screenshot)

**Comment by engcom-Bravo** [comment] 2022-12-06 12:40
Hi @msyhr,

Thank you for reporting and collaboration.


Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

1.Create a catalog discount. In this case global 20% discount.
2.Create a custom option with a price and assign it to both a configurable product and simple product.
3.Run cron / indexes / etc.
4.View Product on the frontend as a customer group that should receive global discount.


For Simple Product 

<img width="1354" alt="Screenshot 2022-12-06 at 1 41 42 PM" src="https://user-images.githubusercontent.com/51680745/205913901-2ab081b8-8b0e-41be-a6f3-e42a35029066.png">


 
For Configurable Product as we created a catalog Price Rule based on `Apply as Percentage of original`.The original price of below configurable Product is $10 and we are getting 20% discount as $2.


<img width="1338" alt="Screenshot 2022-12-06 at 1 41 13 PM" src="https://user-images.githubusercontent.com/51680745/205914650-b29d2e84-c84c-494e-b1c1-0366ad7023b3.png">



<img width="1274" alt="Screenshot 2022-12-06 at 1 41 35 PM" src="https://user-images.githubusercontent.com/51680745/205915013-8571c816-1b3f-4d6c-8526-b7093b2f62bd.png">

Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by msyhr** [comment] 2022-12-06 17:14
@engcom-Bravo 


Are you just saying that there is a fundamental difference in how custom options are discounted when they are attached to a configurable products versus a simple product?

Your screenshots are just replicating the issue that was the reason I created this ticket.

As you can see here, yes the discount for the product is calculated correctly

54.00 (20%) = 64.00

![image](https://user-images.githubusercontent.com/22968596/205973856-55265c54-0f54-4166-b204-e9c710bd7be0.png)

But this base price of the custom option has not been reduced (We are just adding +10$ to the 20% discounted base price), when really I would like the prices for the custom option to be **also** reduced 20% (making the custom option a +8$ charge) reason being I have client that uses customer groups to do blanket discounts for an entire catalog of products.


![image](https://user-images.githubusercontent.com/22968596/205975414-6b7a84aa-7837-4e67-ae8d-0c094e2fb0bd.png)


My issue is that the core does function this way when you use a simple product.

The base price is reduced by 20%

![image](https://user-images.githubusercontent.com/22968596/205977337-ad01117b-d00a-4d14-b08e-f6f37910e77a.png)

As well as the custom option's additional charge:

8$ instead of 10$

![image](https://user-images.githubusercontent.com/22968596/205977447-75c4fb70-4de9-4765-b9c1-015f98ab83c4.png)


Simple Product Configuration

![image](https://user-images.githubusercontent.com/22968596/205977587-fbf00d72-e073-4674-a1f1-9241cda9f2b3.png)

![image](https://user-images.githubusercontent.com/22968596/205977719-aa206d29-fe5e-4298-a4f5-43ebdcc66785.png)

Configurable Product 

![image](https://user-images.githubusercontent.com/22968596/205977868-268448f0-97a1-4443-b65c-4881e7536811.png)

**Comment by Tomasz-Silpion** [comment] 2022-12-06 21:13
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-12-08 09:41
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-12-08 13:37
Hi @msyhr,

Thanks for your Update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

1.Create a catalog discount. In this case global 20% discount.
2.Create a custom option with a price and assign it to both a configurable product and simple product.
3.Run cron / indexes / etc.


In both cases Discount is not applying for custom options.


<img width="1446" alt="Screenshot 2022-12-08 at 4 54 02 PM" src="https://user-images.githubusercontent.com/51680745/206459861-82c1788e-99b2-4c3f-a9f8-f8e6d05934ed.png">



<img width="1331" alt="Screenshot 2022-12-08 at 4 51 31 PM" src="https://user-images.githubusercontent.com/51680745/206459955-b5eca961-576a-4cab-b77e-8c403be5cbae.png">


<img width="1344" alt="Screenshot 2022-12-08 at 4 51 39 PM" src="https://user-images.githubusercontent.com/51680745/206460027-03468e5e-e067-47bd-82b8-31c28c50efdd.png">


<img width="1451" alt="Screenshot 2022-12-08 at 4 54 49 PM" src="https://user-images.githubusercontent.com/51680745/206460118-b74ea77d-6db0-431a-9b8c-54bd8bac2c7e.png">


<img width="1326" alt="Screenshot 2022-12-08 at 4 52 02 PM" src="https://user-images.githubusercontent.com/51680745/206460177-e36d345a-f46a-4135-98cc-d28f49a8a24b.png">



<img width="1328" alt="Screenshot 2022-12-08 at 4 52 10 PM" src="https://user-images.githubusercontent.com/51680745/206460228-6ff1d81e-c3e3-4ecc-8378-2ca766c2fa06.png">


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by msyhr** [comment] 2022-12-08 17:28
@magento give me 2.4.5-p1 instance

**Comment by msyhr** [comment] 2022-12-08 17:57
@magento give me 2.4-develop instance

**Comment by msyhr** [comment] 2022-12-08 18:16
@engcom-Bravo 

It looks like 2.4-develop **does not apply** the discount for either product as you replied


Rule:

![Screenshot 2022-12-08 at 12-05-10 20% Discount _ Catalog Price Rule _ Promotions _ Marketing _ Magento Admin](https://user-images.githubusercontent.com/22968596/206533028-796b34a0-1973-4b89-aedd-4f8bc8ed299a.png)

Simple

https://f7ae7502ae239b06a1ea15f75cb27671.instances.magento-community.engineering/joust-duffle-bag.html

![Screenshot 2022-12-08 at 12-04-53 Joust Duffle Bag _ Products _ Inventory _ Catalog _ Magento Admin](https://user-images.githubusercontent.com/22968596/206533120-7f0035bd-df24-4c6c-8542-53ab500b8c9c.png)

![Screenshot 2022-12-08 at 12-10-31 Joust Duffle Bag](https://user-images.githubusercontent.com/22968596/206533273-bf8c6fe8-f972-4f6a-98ca-f3d6035e06cc.png)



Configurable 

https://f7ae7502ae239b06a1ea15f75cb27671.instances.magento-community.engineering/chaz-kangeroo-hoodie.html

![Screenshot 2022-12-08 at 12-12-31 Chaz Kangeroo Hoodie](https://user-images.githubusercontent.com/22968596/206533410-fd032ef2-23c0-4819-8e2c-496d03038ccb.png)


My question remains: Which one of these outcomes is the expected one? 

Is the discounted amount working in 2.4.4-p1 a bug that has been resolved in 2.4-develop?

**Comment by engcom-Bravo** [comment] 2022-12-09 11:21
Hi @msyhr,

Thanks for your update.

It is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.

The issue might got fixed in magento` 2.4 develop`.

Kindly let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2022-12-21 06:12
Hi @msyhr,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-12-21 06:12 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1
