### ISSUE TITLE
Automatic (equalize product counts) and ElasticSearch 10,000 limit

### ISSUE THREAD

**Issue by jonesio** [magento/magento2#22792] opened 2019-05-08 14:56 UTC
### Preconditions (*)

1. Magento Commerce (EE) 2.3.1
2. Use ElasticSearch (MySQL works fine)

### Steps to reproduce (*)

1. Configure `Catalog -> Catalog -> Catalog Search -> Search Engine` to use `ElasticSearch` or `ElasticSearch 5.0+`
2. Configure `Catalog -> Catalog -> Layered Navigation -> Price Navigation Step Calculation` to use `Automatic (equalize product counts)` (default)
3. Setup **over** 10,000 products in a category (or more likely in child categories of an anchor parent category)
4. Visit the category (or parent anchor category) with the 10,000+ products

### Expected result (*)

1. Catalog category view with over 10,000 products and a price filter showing appropriate ranges equalized by product count e.g. £0.00 - £99.99 (5)

### Actual result (*)

1. `Notice: Undefined offset: 310 in ../vendor/magento/framework/Search/Dynamic/Algorithm.php on line 302`

When there are over 10,000 products in a category the `Magento\Framework\Search\Dynamic\Algorithm` assumes the total product count (over 10,000 in this case) is available when calculating the ranges in `Magento\Framework\Search\Dynamic\Algorithm::calculateSeparators`. This causes undefined offset errors specifically in `Magento\Framework\Search\Dynamic\Algorithm::_findValueSeparator`. Using ElasticSearch all queries appear to be limited to 10,000 in a filter clause meaning the range algorithm is looking for values not available. 

ElasticSearch has a default limit of only returning 10,000 results. This setting can be changed but this is not advisable by ElasticSearch. They recommend other approaches like streaming:

> Note that from + size can not be more than the index.max_result_window index setting which defaults to 10,000

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html

This error can appear to be the fault of modules such as `Amasty_Shopby` but this is not correct. They simply add functionality to view all products in the catalog via a single page meaning the 10,000 limit is hit more easily.

Having less than 10,000 products in a category or using MySQL have none of the above problems. Using the other `Price Navigation Step Calculation` settings do work with ElasticSearch although total product count incorrectly shows 10,000 when a category may have many more (a separate but related issue)  

Some related include: #6626, #11028, #7287, #6625

**Comment by jonesio** [comment] 2019-05-08 15:02
> Hi @jonesio. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [X]  Summary of the issue
> * [X]  Information on your environment
> * [X]  Steps to reproduce
> * [X]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @jonesio do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [x]  yes
> * [ ]  no

**Comment by magento-engcom-team** [comment] 2019-05-08 15:02
Hi @jonesio. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-05-08 15:03
Hi @jonesio, here is your [Magento instance](https://i-22792-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22792-2-3-develop.instances.magento-community.engineering/admin](https://i-22792-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-07-18 13:15
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18264` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ron-jomashop** [comment] 2019-07-22 14:30
It seems like when there are about 8000 to 10000 products, it will work but the price filter will not show.

**Comment by magento-engcom-team** [comment] 2019-07-31 16:03
Hi @jonesio. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-18795` was closed as `non-reproducible` in `2.2-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by magento-engcom-team** [comment] 2019-09-11 19:25
Hi @jonesio. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. 

The fix will be available with the upcoming `2.3.4` release.

**Closed as completed by magento-engcom-team** 2019-09-11 19:25 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Elasticsearch

**Comment by 0m3r** [comment] 2020-07-08 15:09
Fixed in 2.4-develop

https://github.com/magento/magento2/commit/db69693bd929bd8665015ff6d9b6a3845584aa0b

**Comment by Jeep4x4** [comment] 2021-01-20 05:05
> 
> 
> Fixed in 2.4-develop
> 
> [db69693](https://github.com/magento/magento2/commit/db69693bd929bd8665015ff6d9b6a3845584aa0b)

Sorry but any patch of this issue for 2.3.3?
