### ISSUE TITLE
Sales rule is applied even though discount step qty did not pass.

### ISSUE THREAD

**Issue by leonhelmus** [magento/magento2#36756] opened 2023-01-19 10:51 UTC
### Preconditions and environment

- Magento version 2.4.4-p1
- php 8.1
- Verified on magento commerce.

### Steps to reproduce

Go to backend > Cart Price Rule > add new rule > add the following data:
Rule name: test
Active: true
websites: all 
customer groups: all
Coupon: No Coupon
No conditions
Actions:
* Apply Fied amount discount
* Discount amount 5
* Maximun Qty Discount is applied to: 0
* Discount Qty Step (Buy X): 4
* Discard subsequent rules: no
Apply the rule only to cart items matching the following conditions (leave blank for all items):
* If ALL of these conditions are TRUE:
** Category is: Choose a category with many products
Labels
* Add test in all fields

Let the index salesrule_rule run

Now add one product of that category to the cart go to the checkout/cart page. Than check in the database in the table quote in the column applied_rules_ids and you will see the salesrule which you have created is applied. While it should not be added because the Discount Qty Step (Buy X) is set too 4. So it should have only been added if 4 of those products were added in the cart not with 1. Same for the table quote_item.applied_rule_ids.

### Expected result

quote.applied_rules_ids should have no salesrules applied and quote_item.applied_rules_ids should have no salesrules applied.

### Actual result

quote.applied_rules_ids should has a salesrule applied and quote_item.applied_rules_ids has a salesrules applied.

### Additional information

The function: 
\Magento\SalesRule\Model\RulesApplier::applyRules

Only checks if actions and conditions passed. In this case the salesrule is applied because all conditions / actions are applied. To resolve this i added the following patch:
```
diff --git a/vendor/magento/module-sales-rule/Model/RulesApplier.php b/vendor/magento/module-sales-rule/Model/RulesApplier.php
--- a/vendor/magento/module-sales-rule/Model/RulesApplier.php
+++ b/vendor/magento/module-sales-rule/Model/RulesApplier.php
@@ -134,7 +134,16 @@
             }

             $this->applyRule($item, $rule, $address, $couponCode);
-            $appliedRuleIds[$rule->getRuleId()] = $rule->getRuleId();
+            $discounts = $item->getExtensionAttributes()->getDiscounts();
+            if ($discounts) {
+                foreach ($discounts as $discount) {
+                    if ($rule->getRuleId() !== $discount->getRuleId()) {
+                        continue;
+                    }
+
+                    $appliedRuleIds[$rule->getRuleId()] = $rule->getRuleId();
+                }
+            }
         }

         return $appliedRuleIds;

```
and this patch:
```
# Github link: https://github.com/magento/magento2/issues/33459

diff --git a/vendor/magento/module-sales-rule/Model/Validator.php b/vendor/magento/module-sales-rule/Model/Validator.php
--- a/vendor/magento/module-sales-rule/Model/Validator.php
+++ b/vendor/magento/module-sales-rule/Model/Validator.php
@@ -278,6 +278,12 @@
         if ($this->_isFirstTimeResetRun) {
             $address->setAppliedRuleIds('');
             $address->getQuote()->setAppliedRuleIds('');
+            /** @var \Magento\Quote\Model\Quote\Item $item */
+            if ($address->getQuote()->getItems()) {
+                foreach ($address->getQuote()->getItems() as $item) {
+                    $item->setAppliedRuleIds('');
+                }
+            }
             $this->_isFirstTimeResetRun = false;
         }
```

Also see this issue:
https://github.com/magento/magento2/issues/33459

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-01-25 12:29
Hi @leonhelmus,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.


**Steps to reproduce**

1.Go to backend > Cart Price Rule > add new rule > add the following data:
Rule name: test
Active: true
websites: all
customer groups: all
Coupon: No Coupon
No conditions
Actions:

Apply Fied amount discount
Discount amount 5
Maximun Qty Discount is applied to: 0
Discount Qty Step (Buy X): 4
Discard subsequent rules: no
Apply the rule only to cart items matching the following conditions (leave blank for all items):
If ALL of these conditions are TRUE:
** Category is: Choose a category with many products
Labels
Add test in all fields



<img width="411" alt="Screenshot 2023-01-25 at 3 48 12 PM" src="https://user-images.githubusercontent.com/51680745/214562631-1c36c565-d8f8-4b4e-abc4-3ad3eebbd394.png">



<img width="638" alt="Screenshot 2023-01-25 at 3 53 41 PM" src="https://user-images.githubusercontent.com/51680745/214562663-809d5e29-9653-452c-a99e-80c6206206fe.png">



As per the rule discount(cart price rule) should be applied when we add Qty 4 to cart.it is adding when we adding 1 Qty.The issue is in DB records.

In frontend it is not applying discount when we add Qty 1.It is working fine.

<img width="1303" alt="Screenshot 2023-01-25 at 3 56 25 PM" src="https://user-images.githubusercontent.com/51680745/214562972-296147c7-b2b3-4431-9314-624b6a9e09e8.png">



Hence confirming the issue.

Thanks.

**Comment by engcom-Charlie** [comment] 2023-01-31 11:55
As per the discussion in the triage call, tagging it as dev exp. and making it as Ready for confirmation again.

Thank you!

**Comment by engcom-Hotel** [comment] 2023-02-01 07:32
Hello @leonhelmus @engcom-Bravo,

I have rechecked this issue in Magento's latest development branch ie [2.4-develop](https://github.com/magento/magento2), and the is no more reproducible for us.

Please refer to the screenshot below for reference:

**Cart Price Rule**
![image](https://user-images.githubusercontent.com/51681618/215978482-0130e335-3453-46dd-bd4b-a28960172d1a.png)

**Frontend**
![image](https://user-images.githubusercontent.com/51681618/215978568-49cc92a9-62ae-4575-8294-19da97358254.png)

**Database**
_quote_ Table
<img width="481" alt="image" src="https://user-images.githubusercontent.com/51681618/215978691-89270a7d-e959-48d7-8559-3651f78f6588.png">

_quote_item_ Table
<img width="424" alt="image" src="https://user-images.githubusercontent.com/51681618/215978799-095a6de0-d2ec-40f0-a88d-9c473b45f83a.png">

As per the above screenshot, there is no entry for today ie 1st-Feb-23, which means the cart price rule is not applied yet.

For us, the cart price rule id is `5`. It seems the issue is fixed in the development branch and will be fixed for the next Magento release. 

Thanks

**Comment by leonhelmus** [comment] 2023-02-03 14:46
Good to hear. What was the change that resolved it?

**Comment by engcom-Hotel** [comment] 2023-02-06 07:38
Hello @leonhelmus,

As the issue is not reproducible now in the 2.4-develop instance we are closing this issue. And as per your query in the last comment, we will provide the commit link for the same.

Thanks

**Closed as completed by engcom-Hotel** 2023-02-06 07:38 UTC
Labels: Component: DB, Triage: Dev.Experience, Reproduced on 2.4.x, Issue: needs update, Area: Product, Reported on 2.4.4-p1
