### ISSUE TITLE
Cart rule with 100% discount applied to shipping after tax, leaving the tax to pay

### ISSUE THREAD

**Issue by PashaIhnatjo** [magento/magento2#36097] opened 2022-09-06 15:33 UTC
### Preconditions and environment

- Magento 2.4.2 and 2.4.4

### Steps to reproduce

1) go to marketing ->cart price->rule
2)  create a new coupon for 200$
3) go to tab action -> Apply ->set 'Fixed amount discount for whole cart'
4) Discount Amount = 200$
5)  Apply to Shipping Amount => 'yes'
here is screen
![image](https://user-images.githubusercontent.com/22341033/188674162-d5199ac5-c551-4053-ae3f-2b482aff9224.png)

6) add configurations for tax 
Tax = 10%

![image](https://user-images.githubusercontent.com/22341033/188673825-685764d0-0871-4a27-8492-1f61c2bd3ab5.png)
![image](https://user-images.githubusercontent.com/22341033/188674032-db6bbf22-332d-4749-af1c-f8f3c641744d.png)

7) shipping price = 10$
8)) add product with price 100$ to cart

### Expected result

I expect the amount in the cart to be 0

### Actual result

it takes off 100% of the product price and 100% of the shipping pre-tax, leaving the tax of shipment hanging. 
![image](https://user-images.githubusercontent.com/22341033/188675110-e73033bc-e8f6-4217-a52a-abf59d3947ca.png)

### Additional information

if we look at the table of quote, we will see what grand_total =0.9100, but base_grand_total= 0
![image](https://user-images.githubusercontent.com/22341033/188675561-765e7b93-d070-4d20-ab34-20cdafd0e456.png)

I found this error in my project 2.4.2,after which I downloaded a clean version of Magenta 2.4.4, but this error is also reproduced

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-09-13 08:36
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-09-13 12:02
Hi @PashaIhnatjo,


Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue.

Kindly refer the screenshots.


<img width="1172" alt="Screenshot 2022-09-13 at 4 56 17 PM" src="https://user-images.githubusercontent.com/51680745/189894577-d7b579c6-0eba-479f-8dd4-c0a0e142ce07.png">





<img width="1084" alt="Screenshot 2022-09-13 at 4 55 58 PM" src="https://user-images.githubusercontent.com/51680745/189894719-776a07bf-3a9b-486c-a49f-45339dba6096.png">





Steps to reproduce:

1.go to marketing ->cart price->rule
2.create a new coupon for 200$
3.go to tab action -> Apply ->set 'Fixed amount discount for whole cart'
4.Discount Amount = 200$
5.Apply to Shipping Amount => 'yes'
6.add configurations for tax (Tax =10%).
7.shipping price = 10$
8.add product with price 100$ to cart.




Thanks.

**Comment by engcom-Bravo** [comment] 2022-09-14 08:31
@magento give me 2.4-develop instance

**Comment by PashaIhnatjo** [comment] 2022-09-14 11:27
what version of magento is installed on this instance?

**Comment by engcom-Bravo** [comment] 2022-09-14 12:09
Hi @PashaIhnatjo,

Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue.Kindly refer the screenshots.


<img width="1512" alt="Screenshot 2022-09-14 at 2 17 34 PM" src="https://user-images.githubusercontent.com/51680745/190148907-34f06fcb-e355-41a9-a736-8d4f202295e4.png">



<img width="1512" alt="Screenshot 2022-09-14 at 2 17 52 PM" src="https://user-images.githubusercontent.com/51680745/190149004-d60072b9-3f33-4df1-af66-0bc3874f00f2.png">



<img width="1512" alt="Screenshot 2022-09-14 at 2 18 10 PM" src="https://user-images.githubusercontent.com/51680745/190149022-507219c6-3bc9-42ab-b1f4-280888e65bd8.png">



<img width="1512" alt="Screenshot 2022-09-14 at 2 18 20 PM" src="https://user-images.githubusercontent.com/51680745/190149078-a169ea38-0cec-42e0-9947-a58d47a76429.png">




<img width="1512" alt="Screenshot 2022-09-14 at 2 16 56 PM" src="https://user-images.githubusercontent.com/51680745/190149119-9ba1c622-831c-4504-8dc1-4786ed7c05d9.png">



<img width="1512" alt="Screenshot 2022-09-14 at 2 17 11 PM" src="https://user-images.githubusercontent.com/51680745/190149172-416ced27-c0a4-4f0a-89da-6da1dca92e74.png">

Steps to reproduce:

1.go to marketing ->cart price->rule
2.create a new coupon for 200$
3.go to tab action -> Apply ->set 'Fixed amount discount for whole cart'
4.Discount Amount = 200$
5.Apply to Shipping Amount => 'yes'
6.add configurations for tax (Tax =10%).
7.shipping price = 10$
8.add product with price 100$ to cart.








Please try to reproduce in Magento 2.4-develop instance.


Let us Know we miss anything.

Thnaks

**Comment by PashaIhnatjo** [comment] 2022-09-14 13:07
Nfr

> Hi @PashaIhnatjo,
> 
> Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue.Kindly refer the screenshots.
> 
> <img alt="Screenshot 2022-09-14 at 2 17 34 PM" width="1512" src="https://user-images.githubusercontent.com/51680745/190148907-34f06fcb-e355-41a9-a736-8d4f202295e4.png">
> 
> <img alt="Screenshot 2022-09-14 at 2 17 52 PM" width="1512" src="https://user-images.githubusercontent.com/51680745/190149004-d60072b9-3f33-4df1-af66-0bc3874f00f2.png">
> 
> <img alt="Screenshot 2022-09-14 at 2 18 10 PM" width="1512" src="https://user-images.githubusercontent.com/51680745/190149022-507219c6-3bc9-42ab-b1f4-280888e65bd8.png">
> 
> <img alt="Screenshot 2022-09-14 at 2 18 20 PM" width="1512" src="https://user-images.githubusercontent.com/51680745/190149078-a169ea38-0cec-42e0-9947-a58d47a76429.png">
> 
> <img alt="Screenshot 2022-09-14 at 2 16 56 PM" width="1512" src="https://user-images.githubusercontent.com/51680745/190149119-9ba1c622-831c-4504-8dc1-4786ed7c05d9.png">
> 
> <img alt="Screenshot 2022-09-14 at 2 17 11 PM" width="1512" src="https://user-images.githubusercontent.com/51680745/190149172-416ced27-c0a4-4f0a-89da-6da1dca92e74.png">
> 
> Steps to reproduce:
> 
> 1.go to marketing ->cart price->rule 2.create a new coupon for 200$ 3.go to tab action -> Apply ->set 'Fixed amount discount for whole cart' 4.Discount Amount = 200$ 5.Apply to Shipping Amount => 'yes' 6.add configurations for tax (Tax =10%). 7.shipping price = 10$ 8.add product with price 100$ to cart.
> 
> Please try to reproduce in Magento 2.4-develop instance.
> 
> Let us Know we miss anything.
> 
> Thnaks

yes in your environment I also cant reproduce it
but if I am correct understand  you have version 2.4.5 (perhaps higher)
I checked on 2.4.4 and 2.4.2 and it plays for me (
I will check it again

**Comment by orkuncv** [comment] 2022-09-16 10:03
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-09-28 06:38
Hi @PashaIhnatjo,


We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.


Thanks.

**Closed as completed by engcom-Bravo** 2022-09-28 06:38 UTC
Labels: Issue: needs update, Reported on 2.4.4
