### ISSUE TITLE
Can't Filter Order in Magento -Error during Filter "Something went wrong with processing the default view and we have restored the filter to its original state" 

### ISSUE THREAD

**Issue by curtisgift** [magento/magento2#38901] opened 2024-07-04 03:14 UTC
### Preconditions (*)

1. Whenever we filter data from ORDERS an error always occurred that ""Something went wrong with processing the default view and we have restored the filter to its original state" . We cannot filter any data from ORDERS due to that error. Please fix and if possible a customer support can contact directly on our email.
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description] We should be able to extract data of Orders whenever we filter for a desired output or result in ORDERS.

### Actual result (*)

1. [Screenshots, logs or description] However, during filter in ORDERS an error occur. "Something went wrong with processing the default view and we have restored the filter to its original state"

**Comment by engcom-Bravo** [comment] 2024-07-04 04:21
Hi @curtisgift,

Thanks for your reporting and collaboration.

we have verified the issue in Latest 2.4-develop and we are not able to reproduce the issue.We are able to filter the orders.

Could you please refer this comment https://github.com/magento/magento2/issues/26515#issuecomment-802797711 it may resolves the issue and check the issue in Magento 2.4-develop instance.

Thanks.

**Comment by curtisgift** [comment] 2024-07-04 05:09
Sir,

We tried to filter it just now and this is the error occurred, same as previous.
[cid:158fb571-ba97-48a1-9ebd-772ddee71756]

Thank you
Regards
Curtis Mar

[all-logo-all-office]

Unit 2202, 22/F, Causeway Bay Plaza 1, 489 Hennessy Rd, Causeway Bay, Hong Kong.
Unit 2403, 24/F, Tsuen Wan Ind Centre, 220 Texaco Rd, Tsuen Wan, Hong Kong.

21 Ubi Rd 1, #03-01, Singapore 408724.

8 Jalan Tun Sambanthan 3, Brickfields, 50470, Kuala Lumpur, Malaysia.



T  + 852 2730 0885<tel:%2B%20852%202730%200885> │ F  + 852 2730 0206<tel:%2B%20852%202730%200206>

giftflowers.com.hk<http://giftflowers.com.hk/> │gifthampers.com.hk<http://gifthampers.com.hk/> │giftsomething.com<http://www.giftsomething.com/>

[https://mail.google.com/mail/u/2?ui=2&ik=14cf2c4d59&attid=0.0.3&permmsgid=msg-f:1750271285094013205&th=184a3675e0985915&view=fimg&fur=ip&sz=s0-l75-ft&attbid=ANGjdJ9uuIorrIybMzxJ_DzYlw1BCsxcJ0eSwjeT9Oczu9lVbDRM44_zdaENvVKQda4aJHKwspMMp3-s4OHynIW1W7Urz-olwCggi3WAE9juWePJDQm34oUTI4BJfQk&disp=emb]

________________________________

**Comment by engcom-Bravo** [comment] 2024-07-04 11:11
Hi @curtisgift,

Thanks for your update.

FYI.. Sometimes, this error can occur due to version upgrade. Check "catalog_product_entity" table in DB and verify if any Products have NULL as SKU value
Run > SELECT * FROM catalog_product_entity WHERE sku IS NULL to check all product not have sku NULL, then update them.
Another temporary fix is to clear "ui_bookmark table". > TRUNCATE ui_bookmark;
Also make sure to clear cache and add necessary permission/rights.

Kindly recheck the issue on Magento 2.4-develop branch as it has the latest code base and provide missing steps to reproduce if you are still facing the issue.

Thank you

**Comment by curtisgift** [comment] 2024-07-05 01:21
Hi!

As an update this morning. The problem left is when we filter ORDERS in PURCHASE DATE, same error still occur.
But when filtering other data it is now working.

Please see screenshot below

[cid:b0733c5e-ae15-44a0-9925-11f3cdc31d6e]


I would like to ask for extra help to fix this error since I am not familiar with technical issue or command in Magento.


Thank you
Regards
Curtis Mar

[all-logo-all-office]

Unit 2202, 22/F, Causeway Bay Plaza 1, 489 Hennessy Rd, Causeway Bay, Hong Kong.
Unit 2403, 24/F, Tsuen Wan Ind Centre, 220 Texaco Rd, Tsuen Wan, Hong Kong.

21 Ubi Rd 1, #03-01, Singapore 408724.

8 Jalan Tun Sambanthan 3, Brickfields, 50470, Kuala Lumpur, Malaysia.



T  + 852 2730 0885<tel:%2B%20852%202730%200885> │ F  + 852 2730 0206<tel:%2B%20852%202730%200206>

giftflowers.com.hk<http://giftflowers.com.hk/> │gifthampers.com.hk<http://gifthampers.com.hk/> │giftsomething.com<http://www.giftsomething.com/>

[https://mail.google.com/mail/u/2?ui=2&ik=14cf2c4d59&attid=0.0.3&permmsgid=msg-f:1750271285094013205&th=184a3675e0985915&view=fimg&fur=ip&sz=s0-l75-ft&attbid=ANGjdJ9uuIorrIybMzxJ_DzYlw1BCsxcJ0eSwjeT9Oczu9lVbDRM44_zdaENvVKQda4aJHKwspMMp3-s4OHynIW1W7Urz-olwCggi3WAE9juWePJDQm34oUTI4BJfQk&disp=emb]

________________________________

**Comment by engcom-Bravo** [comment] 2024-07-08 08:50
Hi @curtisgift,

Thanks for your update.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

<img width="1431" alt="Screenshot 2024-07-08 at 13 34 09" src="https://github.com/magento/magento2/assets/51680745/9237f006-0bda-490e-91c9-85aa2d1324b3">


Kindly check if any third party modules causing the issue.

Thanks.

**Comment by atIOCrON** [comment] 2024-07-09 22:17
We have the same issue since upgrading to v2.4.7-p1.

**Comment by atIOCrON** [comment] 2024-07-12 02:08
For anyone else looking for a fix, please see here:

https://github.com/magento/magento2/issues/38916

**Comment by engcom-Bravo** [comment] 2024-07-16 08:39
@atIOCrON Thanks for your Contribution!!.

Hi @curtisgift,

Could you please refer this https://github.com/magento/magento2/issues/38901#issuecomment-2224295320 and we are closing this duplicate for this https://github.com/magento/magento2/issues/38916.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-16 08:39 UTC
Labels: duplicate, Issue: needs update, Reported on 2.4.x

**Comment by hclauss-ltk** [comment] 2024-07-19 06:24
Hello everyone, 

we have the same problem. We can´t filter our products anymore and because of the error we also can´t see the product overview in general. Are there any news on how to reset it? 

Thanks in advance!
