### ISSUE TITLE
M2.1.2 : Interceptor breaks when type hinting a string

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#7620] opened 2016-11-30 09:09 UTC
I generated a block glass that has a method that takes a single string as parameter. I type-hinted the parameter in the method, but the generator interceptor doesn't take this into account. The result is an error.

### Steps to reproduce

Create a method in a block class that has type-hinting for a string:

```php
public function getFoo(string $foo)
{
    return $foo;
}
```

Make Magento re-generate it's `var/generated`-folder.

### Expected result

No error thrown. Generated method in the interceptor should have the same signature.

### Actual result

Magento throws an error:

```
Warning:
Declaration of Vendor\Module\Block\Foo\Interceptor::getFoo($foo) 
should be compatible with 
Vendor\Module\Block\Foo\Interceptor::getFoo(string $foo) 
in .../var/generation/Vendor\Module\Block\Foo\Interceptor.php on line 7
```

If you open the interceptor you see that the signature lacks the type hint. Which of course will throw an error since it's inherited:

```php
public function getFoo($foo)
{
    $pluginInfo = $this->pluginList->getNext($this->subjectType, 'getFoo');
    if (!$pluginInfo) {
        return parent::getFoo($imageId);
    } else {
        return $this->___callPlugins('getFoo', func_get_args(), $pluginInfo);
    }
}
```

**Comment by KamilBalwierz** [comment] 2016-12-13 10:26
Same issue applies to returned types (PHP7 functionality) generated interceptor code is missing return type causing error.

**Comment by kanduvisla** [comment] 2017-02-09 10:55
Is there any update on this?

**Comment by kanduvisla** [comment] 2017-07-13 11:35
Almost half a year later this problem still persists in Magento 2.1.7

Is there any update on this issue?

**Comment by nei** [comment] 2017-07-26 14:50
Same here. PHP 7.0.6, Magento 2.1.7

**Comment by orlangur** [comment] 2017-07-26 20:36
Duplicate of #6106. Fixed in `develop` but unlikely to be backported to 2.1. Not a bug, obviously, but limitation of third-party component used.

**Comment by magento-engcom-team** [comment] 2017-10-13 15:30
@kanduvisla, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-13 15:30 UTC
Labels: bug report, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by Ctucker9233** [comment] 2017-12-03 01:26
@magento-engcom-team and backported to 2.1 I hope?

**Comment by orlangur** [comment] 2017-12-03 11:54
@Ctucker9233,
> unlikely to be backported to 2.1

**Comment by Ctucker9233** [comment] 2018-01-19 18:06
@orlangur Does it break BC? If it doesn't, I'll take a stab at it.
