### ISSUE TITLE
Export CSV or excel both only works in the second time.

### ISSUE THREAD

**Issue by devqualwebs** [magento/magento2#34846] opened 2021-12-20 05:22 UTC
### Preconditions (*)

1. Install and setup magento 2
2. Even tried with the latest version of magento. Orders, products, reports all export option works in second time.

### Steps to reproduce (*)

1. Login to the admin panel.
2. Go to reports section, click on export CSV.
3. It will redirect to the dashboard page instead of export the csv.

### Expected result (*)

1. After clicking on the export option, the CSV/XML should export the file.

### Actual result (*)

1. It's redirecting on the dashboard page the first time. Again if I got to the reports page, and try to export the CSV, now I'm able to export it.

After exporting the second time, If again click on the export, now its exporting. Issue only occurs when admin login and directly export the CSV.

**Comment by makzef** [comment] 2021-12-20 09:39
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2021-12-20 10:05
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible for 1st time admin login as well.
Export is working fine for Orders, Products etc. - No issue
@devqualwebs kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.
![image](https://user-images.githubusercontent.com/60198231/146749664-d5d4c996-61ca-4d92-904e-ae9397caa882.png)

**Comment by engcom-November** [comment] 2022-01-03 12:10
Hi @devqualwebs ,
We are closing this issue as there has been no latest update on the same.
Thank you

**Closed as completed by engcom-November** 2022-01-03 12:10 UTC
Labels: Issue:  Cannot Reproduce, Component: Reports, Issue: needs update
