### ISSUE TITLE
Customer group id field set is null during placing guest order

### ISSUE THREAD

**Issue by Citizen4our** [magento/magento2#36514] opened 2022-11-23 11:45 UTC
### Preconditions and environment

- Magento version: 2.4.5
- place guest order

### Steps to reproduce

1. Place guest order

### Expected result

Customer group id is 0 (NOT LOGGED IN) 

### Actual result

Customer group id is null

### Additional information

Problem in this line: \Magento\Quote\Model\QuoteManagement::placeOrder 429:
` $groupId = $customer ? $customer->getGroupId() : GroupInterface::NOT_LOGGED_IN_ID;`
$customer object is empty object, so $customer->getGroupId() return null

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Citizen4our** [comment] 2022-11-23 12:05
I see it fixed https://github.com/magento/magento2/commit/d692049464a40921c2673f447fe7ddab30f63254

**Comment by engcom-Bravo** [comment] 2022-11-24 08:40
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-24 12:33
Hi @Citizen4our,


Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

1.Place guest order.


<img width="532" alt="Screenshot 2022-11-24 at 2 45 17 PM" src="https://user-images.githubusercontent.com/51680745/203785405-1785940b-ea29-45dc-9b20-7f094ea8c37f.png">



<img width="1343" alt="Screenshot 2022-11-24 at 2 42 11 PM" src="https://user-images.githubusercontent.com/51680745/203785439-0c954260-d95b-46c6-9970-09501b4e8750.png">



<img width="1421" alt="Screenshot 2022-11-24 at 2 50 08 PM" src="https://user-images.githubusercontent.com/51680745/203785495-521172dd-9975-4a34-a75e-da9159de766a.png">



Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by Citizen4our** [comment] 2022-11-24 12:37
Hi @engcom-Bravo 
Looks like this bug has been fixed on 2.4-develop branch. But I can reproduce it on 2.4.5 instance

**Comment by engcom-Bravo** [comment] 2022-11-25 11:22
Hi @Citizen4our,

Thanks for your update.

It is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.

Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2022-12-09 06:15
Hi @Citizen4our,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-12-09 06:15 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.5

**Comment by Ig0r-M-magic42** [comment] 2023-03-02 13:40
## Reproduced on 2.4.4-p2 enterprise
### Here is the example when customer object is an empty shell but still an object which in turn will get the customerGroupId as null
![image](https://user-images.githubusercontent.com/22006850/222439867-ec69278d-3114-4951-b074-ed9902af054f.png)
### Here we seen how empty shell is created
![image](https://user-images.githubusercontent.com/22006850/222440734-0017b501-3289-4694-997e-f7451bf82ac1.png)
### In here i can confirm that https://github.com/magento/magento2/commit/d692049464a40921c2673f447fe7ddab30f63254 fixes it for guest checkout
![image](https://user-images.githubusercontent.com/22006850/222441952-2fea1c51-e104-4fff-b8ea-f51f37ff38c3.png)

@Citizen4our @engcom-Bravo  FYI
