### ISSUE TITLE
Impossible to unselect a multiselect attribute on products

### ISSUE THREAD

**Issue by syno-dlr** [magento/magento2#8577] opened 2017-02-16 14:31 UTC
Hello all,

### Preconditions
1. Install Magento 2
2. Create a product with a multiselect attribute AND selected values.
3. Save It

### Steps to reproduce
1. Unselect ALL values
2. Save product again

### Expected result
1. All values should be unselected.

### Actual result
1. Previous values are still selected.

I create a Pull Request now to fix it.

**Comment by vrann** [comment] 2017-02-23 03:45
@damien-synolia cannot reproduce the issue on the latest develop branch. What version are you observing it at?

**Comment by syno-dlr** [comment] 2017-02-23 15:59
Hey vrann !

I tested on the community edition 2.1.4 with sample data (from Magento Website).

Damien.

**Comment by vrann** [comment] 2017-03-02 19:56
@damien-synolia Can you please try to reproduce it on latest mainline? Please attach screenshots if it is reproducible. Tried that with the sample data, here is what I've got, consistent with the expected result.
![screen shot 2017-03-02 at 1 54 10 pm](https://cloud.githubusercontent.com/assets/2277722/23524363/e75b4680-ff4f-11e6-8413-da727ec8be68.png)

**Comment by vrann** [comment] 2017-03-13 17:48
closing as duplicate #7687, which is resolved on the latest develop and being backported to 2.1

**Closed as completed by vrann** 2017-03-13 17:48 UTC
Labels: Issue: Ready for Work

**Comment by magento-team** [comment] 2017-08-01 14:58
Internal ticket to track issue progress: MAGETWO-64754
