### ISSUE TITLE
Declarative Schema: referential constraint rule updates not applied

### ISSUE THREAD

**Issue by Vinai** [magento/magento2#23417] opened 2019-06-26 09:21 UTC
Changes of foreign key constraint rules in `db_schema.xml` from `onUpdate="CASCADE" to `onUpdate="SET NULL" or the other way are ignored.

# Preconditions (*)
1. Magento 2.3 or later

### Steps to reproduce (*)
1. Create a table using declarative schema with a column that has a foreign key constraint rule `onUpdate="CASCADE"`
2. Run `bin/magento setup:upgrade` to create the table
3. Change the constraint rule to `onUpdate="SET NULL"`
4. Run `bin/magento setup:upgrade` again to apply the change

### Expected result (*)
The column foreign key constraint rule is `SET NULL`

### Actual result (*)
The column foreign key constraint rule is still `CASCADE`

**Comment by engcom-Charlie** [comment] 2019-11-04 10:08
Hello @Vinai 
We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps,
because `onUpdate` attribute is not allowed:
![image](https://user-images.githubusercontent.com/51680850/68113173-ce209900-fefb-11e9-9c9c-68863995c6be.png)

So i have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-11-04 10:08 UTC
Labels: Issue: Format is valid, Triage: Dev.Experience
