### ISSUE TITLE
In Backend, default store values for product attributes instead of admin values

### ISSUE THREAD

**Issue by FloForMagento** [magento/magento2#39177] opened 2024-09-17 13:59 UTC
### Preconditions and environment

Adobe Commerce ver. 2.4.5-p8

### Steps to reproduce

1. Go to Store, Attributes Product, select one attribute (eg: color), set Default Store view value for an option, different from the admin one. Save attribute.
![1](https://github.com/user-attachments/assets/a3c94ce7-38e3-49e9-9cf8-2df9c0a9e8f9)

2. Go to Marketing, Cart Price Rules, Add new rule. Under Conditions, clic on plus, select "Product attribute combinaison". Clic on the plus to select the attribute edited in step 1, color for my exemple.
![2](https://github.com/user-attachments/assets/1852ccc8-824c-473b-b58a-09d1afad4e19)

### Expected result

In Backend, attributes should use admin values. 
So for my exemple, I should see Black. 

### Actual result

Default store values are used instead of admin values.

### Additional information

The point of Admin values is to be used in Backend. Typically thoses would be unique code values, while in Default store view you likely want label intented for customers, not necessary unique.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by FloForMagento** [comment] 2024-09-17 14:24
@magento give me 2.4-develop instance

**Comment by benjamin-volle** [comment] 2024-09-18 07:14
@magento give me 2.4-develop instance

**Comment by FloForMagento** [comment] 2024-09-18 13:28
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-09-19 07:22
Hi @FloForMagento,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.


<img width="1437" alt="Screenshot 2024-09-19 at 12 12 29" src="https://github.com/user-attachments/assets/fd0f7b5d-2728-4041-b53f-d73bd059fb73">



<img width="1437" alt="Screenshot 2024-09-19 at 12 12 19" src="https://github.com/user-attachments/assets/77a8da4d-54b1-47aa-969e-d48118963177">


Default store values are used instead of admin values.

Hence Confirming the issue.

Thanks.

**Comment by glo23503** [comment] 2024-11-20 06:35
Internal team is working on it.

**Comment by FloForMagento** [comment] 2024-11-28 15:01
While I need further tests before pushing to production, the patch from Adobe team fixed this issue on my project.
In vendor/magento/module-rule/Model/Condition/Product/AbstractProduct.php, line 246:

-                $selectOptions = $attributeObject->getSource()->getAllOptions($addEmptyOption);
+                $selectOptions = $attributeObject->getSource()->getAllOptions($addEmptyOption, true);

Thank you for addressing this issue.

**Comment by engcom-Bravo** [comment] 2024-12-10 05:02
Hi @FloForMagento,

Thanks for your Contribution!!.

As I can see this issue got fixed in the scope of the internal Jira ticket ACP2E-3374 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-3374&type=commits


Thanks.

**Closed as completed by engcom-Bravo** 2024-12-10 05:02 UTC
Labels: Issue: Confirmed, Component: Admin, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Admin UI, Reported on 2.4.5-p8
