### ISSUE TITLE
Magento 2.1 REST API Add options to configurable product

### ISSUE THREAD

**Issue by yuklia** [magento/magento2#7355] opened 2016-11-08 16:10 UTC
1. Magento v2.1.2
2. php 7

### Steps to reproduce
1. Create configurable product
2. Assign options (simple products) via configurableProductOptionRepositoryV1 
```

{
    "option": {
    "attribute_id": "162",
    "label": "Collection",
    "position": 0,
    "is_use_default": true,
    "values": [
      {
        "value_index": 25,
        "extension_attributes": {}
      }
    ],
    "extension_attributes": {},
    "product_id": 102
  },
  
  "option": {  
    "attribute_id": "144",
    "label": "Size",
    "position": 0,
    "values": [
      {
        "value_index": 45
      }
    ],
    "product_id": 102
   }
}

```
### Expected result
```
. [
  {
    "id": 46,
    "attribute_id": "144",
    "label": "Size",
    "position": 0,
    "values": [
      {
        "value_index": 45
      }
    "product_id": 102
  },
  {
    "id": 45,
    "attribute_id": "162",
    "label": "Collection",
    "position": 0,
    "values": [
      {
        "value_index": 25
      }
    "product_id": 102
  }
]
```

### Actual result
There is no   "value_index" attribute in values

```
. [
  {
    "id": 46,
    "attribute_id": "144",
    "label": "Size",
    "position": 0,
     "values": [],
    "product_id": 102
  },
  {
    "id": 45,
    "attribute_id": "162",
    "label": "Collection",
    "position": 0,
    "values": [],
    "product_id": 102
  }
]
```

**Comment by yuklia** [comment] 2016-11-09 09:50
vendor/magento/module-configurable-product/Helper/Product/Options/Loader.php

```
 public function load(ProductInterface $product)
    {
        $options = [];
        /** @var Configurable $typeInstance */
        $typeInstance = $product->getTypeInstance();
        $attributeCollection = $typeInstance->getConfigurableAttributeCollection($product);
        $this->extensionAttributesJoinProcessor->process($attributeCollection);
        foreach ($attributeCollection as $attribute) {
            $values = [];
            $attributeOptions = $attribute->getOptions(); // IS EMPTY ! How to fill it right way from REST API ?
            if (is_array($attributeOptions)) {
                foreach ($attributeOptions as $option) {
                    /** @var \Magento\ConfigurableProduct\Api\Data\OptionValueInterface $value */
                    $value = $this->optionValueFactory->create();
                    $value->setValueIndex($option['value_index']);
                    $values[] = $value;
                }
            }
            $attribute->setValues($values);
            $options[] = $attribute;
        }

        return $options;
    }
```

**Comment by iluvcode** [comment] 2016-11-18 16:54
@veloraven  @yuklia ,

I am having similar issue. Did you find any solution for this?

**Comment by olysenko** [comment] 2016-12-02 15:47
Hi, thank you for your report. In your case actual result is correct  because   
POST /V1/configurable-products/{sku}/options should  create only relation between product_id and attribute_id. 

Below i describe how to add simple products to configurable product as the options
 1. Create configurable product:
`curl -X POST -H "Authorization: Bearer <ACCESS_TOKEN>" -H "Content-Type: application/json" -d '{
    "product": {
        "attribute_set_id": 4,
        "type_id": "configurable",
        "sku": "CONFIGURABLE_BY_API",
        "name": "CONFIGURABLE_BY_API",
        "price": 99,
        "status": 1,
        "visibility": 4,
        "custom_attributes": {
            "description": "DESCRIPTION",
            "meta_description": "Some description"
        }
    }
}' "http://<BASE_URL>/index.php/rest/all/V1/products"
`
2. Set the option to configurable product
`curl -X POST -H "Authorization: Bearer <ACCESS_TOKEN>" -H "Content-Type: application/json" -d '{
  "option": {
    "attribute_id": "93",
    "label": "Color",
    "position": 0,
    "is_use_default": true,
    "values": [
      {
        "value_index": 9
      }
    ]
  }
}' "http://<BASE_URL>/index.php/rest/all/V1/configurable-products/CONFIGURABLE_BY_API/options"
`

3.  Link simple product with selected color attribute option as the child to configurable
`curl -X POST -H "Authorization: Bearer <ACCESS_TOKEN>" -H "Content-Type: application/json" -d '{"childSku": "<CHILD_SKU>"}' "http://<BASE_URL>/index.php/rest/all/V1/configurable-products/CONFIGURABLE_BY_API/child"`
Please, check and  if it works for you please close the issue

**Comment by veloraven** [comment] 2016-12-22 07:49
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Closed as completed by veloraven** 2016-12-22 07:49 UTC
Labels: bug report, Progress: needs update, Component: Framework/Webapi
