### ISSUE TITLE
Product MassDelete issue  

### ISSUE THREAD

**Issue by shreyasavion** [magento/magento2#24980] opened 2019-10-11 09:42 UTC
Hello,

 There is an issue encounter while using mass delete functionality at actalag product. I am using  Magento 2.2.2 setup.
Steps to replicate this issue:
    - Select multiple product and submit delete action.
    - Refresh the product list page open at another browser or another PC with same or different admin account.
  It will delete all product of your store. 
I fell prey two times.

Please help me to avoid this.

**Comment by krishprakash** [comment] 2019-10-11 10:08
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-10-11 10:08
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-10-11 10:09
Hi @krishprakash, here is your [Magento instance](https://i-24980-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24980-2-3-develop.instances.magento-community.engineering/admin](https://i-24980-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2019-10-11 10:16
Hi @shreyasavion. Thank you for your report.
I'm not able to reproduce the issue as provided steps by you.
Can you please confirm that issue is reproduce on latest magento instance as provided here
https://github.com/magento/magento2/issues/24980#issuecomment-541003912
Thanks

**Comment by shreyasavion** [comment] 2019-10-11 13:38
Hii @krishprakash. Thank you for looking into it.

Admin access: https://i-24980-2-3-develop.instances.magento-community.engineering/admin
Login: admin Password: 123123q
I have tried on above instance also, I had selected 999out of 1100* and call massDelete and Now result is  all product are deleted

And I have tried it on my setup also.
  Summary of the issue -> 
    I was trying to delete about 2000 products, so select those and submitted delete action,and I wait for result but result did not show up for considerable time. Then I refresh the page to check what if it was done or not, but what saw the count became 0. There was 14000 products deleted.

Information on your environment-> 
   I am  using  Magento 2.2.2 , PHP 7.1

Steps to reproduce->
    Select Products > call Delete action > Refresh before action get complete. 

Expected and actual results
      Expected-> Need to delete only selected product.
    Actual result-> Deleted All products

**Comment by sdzhepa** [comment] 2019-10-11 16:57
Looks like similar or related to https://github.com/magento/magento2/issues/15935

**Comment by krishprakash** [comment] 2019-10-14 04:33
Hi @shreyasavion.
Closing this as issue is duplicate to #15935 and already in Open state.
Thanks.

**Closed as completed by krishprakash** 2019-10-14 04:33 UTC
Labels: duplicate, Issue: Format is not valid

**Comment by shreyasavion** [comment] 2019-10-14 12:52
Hello @krishprakash, I got solution. I know that this is not reliable but it works for me. I made changes in Massdelete controller.
 
**$count = count($collection); // newly added
            foreach ($collection as $product) {
               $this->productRepository->delete($product);
                $productDeleted++;
                if($count == $productDeleted){break;} // newly added
            }**


And now i am going to override this controller.  And Looking forward to correct answer.
