### ISSUE TITLE
Wrong css for ui-datepicke

### ISSUE THREAD

**Issue by jarekherisz** [magento/magento2#21551] opened 2019-03-01 22:15 UTC
### Preconditions
1. 2.3.0 vanilla install

tested on 
- firefox 65.0.1 mac
- firefox 65.0.1 windows
- chrome 72.0.3626.119 mac

### Steps to reproduce
On product page, in all position with date from to , where exists datepicker, the icon of calendar is in wrong place.

![obraz](https://user-images.githubusercontent.com/6222216/53669168-7cda4e80-3c76-11e9-97d6-7787359e9232.png)

I think reason of this behavior is wrong params left in css ".admin__control-grouped-date .ui-datepicker-trigger" 

<img width="434" alt="zrzut ekranu 2019-03-1 o 23 08 55" src="https://user-images.githubusercontent.com/6222216/53669335-11dd4780-3c77-11e9-8a66-039b27a22209.png">

After remove it it's look like correctly:

<img width="1169" alt="zrzut ekranu 2019-03-1 o 23 12 27" src="https://user-images.githubusercontent.com/6222216/53669531-a47de680-3c77-11e9-8fed-701518e1dc95.png">

**Comment by magento-engcom-team** [comment] 2019-03-01 22:15
Hi @jarekherisz. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jarekherisz do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by jarekherisz** [comment] 2019-03-01 22:20
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-01 22:20
Hi @jarekherisz. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-01 22:20
Hi @jarekherisz, here is your [Magento instance](https://i-21551-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21551-2-3-develop.instances.magento-community.engineering/admin](https://i-21551-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by DanielRuf** [comment] 2019-03-02 11:02
The issue is a missing `position: relative` on the direct parent imo.

**Comment by magento-engcom-team** [comment] 2019-03-03 03:13
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment] 2019-03-03 03:15
@jarekherisz Thank you for your report. This issue is already fixed in current 2.3-develop instance . Message here if you still getting this issue on current 2.3-develop instance.

**Closed as completed by shikhamis11** 2019-03-03 03:15 UTC
Labels: Issue: Format is not valid
