### ISSUE TITLE
Styling of <legend> elements break in Chrome 56

### ISSUE THREAD

**Issue by thlassche** [magento/magento2#7155] opened 2016-10-24 09:45 UTC
### Preconditions

1. Magento version: 2.1.3
2. Chrome 56 (Chrome 55 works fine)
### Steps to reproduce

1. Open the admin login page
### Expected result

1.  A proper styled login form
### Actual result

1. 
   ![screen shot 2016-10-24 at 11 42 42](https://cloud.githubusercontent.com/assets/2959888/19640930/3d356d6e-99df-11e6-8c4a-c93d7099198d.png)
   ![screen shot 2016-10-24 at 11 48 44](https://cloud.githubusercontent.com/assets/2959888/19641073/d620a12e-99df-11e6-9c11-ab7fbf8b580b.png)

Same issue occurs on more forms: e.g. customer register page. The cause of this is the `<legend>` tag. Replacing this by a `<div>` tag works fine. Might be a render bug in Chrome 56, but since this is rolling out very soon to a lot of people this might be worth looking into.

**Comment by ihor-sviziev** [comment] 2016-10-24 10:24
@thlassche you're using dev version, that could contains issues. I think issues like this should be reviewer & fixed only in stable versions

**Comment by thlassche** [comment] 2016-10-24 13:35
@ihor-sviziev Agreed, however we should make sure that Magento is compatible by the time Chrome 56 is released

**Comment by alex-bukach** [comment] 2016-10-25 18:16
It might be not Magento issue, I have faced <legend> issue in Chrome on other sites.

**Comment by timrsmith** [comment] 2016-12-03 03:35
This issue exists in 55 (previously beta), now including stable

**Comment by softcommerceltd** [comment] 2016-12-03 09:33
Same issue on Version 55.0.2883.75 (64-bit)

**Comment by hostep** [comment] 2016-12-03 10:47
This is being tracked over here in the chromium bugtracker: https://bugs.chromium.org/p/chromium/issues/detail?id=670837

Looks like a regression, I don't think Magento will need to fix something and we just need to wait for Chrome to release a new version...

**Comment by hostep** [comment] 2016-12-09 20:30
Chrome 55.0.2883.87 was just released which fixes these issues 🎉

**Comment by ihor-sviziev** [comment] 2016-12-14 16:39
This issue can be closed, it was fixed in chrome latest stable, now this issue is not reproducing

**Closed as completed** 2016-12-23 07:43 UTC
Labels: bug report, Area: Frontend
