### ISSUE TITLE
ProxyClasses broken in 2.0.2 on session_write_close

### ISSUE THREAD

**Issue by ghost** [magento/magento2#3419] opened 2016-02-16 08:27 UTC
The proxy classes stopped working for me since updating to 2.0.2

```
<preference for="Magento\Framework\Logger\Monolog" type="MyModule\FancyLog\Logger\LogManager\Proxy" />
<type name="MyModule\FancyLog\Logger\LogManager">
      <arguments>
             <argument name="configInterface" xsi:type="object">Magento\Framework\App\Config\ScopeConfigInterface</argument>
      </arguments>
 </type>
 <type name="MyModule\FancyLog\Logger\RemoteLogFactory">
      <arguments>
         <argument name="configInterface" xsi:type="object">MyModule\FancyLog\Helper\ConfigurationProvider</argument>
      </arguments>
 </type>
```

In ConfigurationProvider.php

```
class ConfigurationProvider extends \Magento\Framework\App\Helper\AbstractHelper
{
    public function getRemoteLogLevel()
    {
     $config = $this->scopeConfig->getValue('wonderful/logging/loglevel');
    }
}

```

Error:

```
PHP Fatal error:  Uncaught Exception: Notice: session_write_close(): &quot;_underscoreCache&quot; returned as member variable from __sleep() but does not exist in /var/www/html/lib/internal/Magento/Framework/Session/SessionManager.php on line 139
```

Extends #3405

Since I'm extending Monolog/Logger I will always have circular dependencies, so a proxy is needed here I guess

Strangewise this happens only when trying to login into the admin backend

Please let me know how to workaround this issue.

Best

**Comment by ghost** [comment] 2016-02-16 12:55
Update

Magento is autogenerating the ProxyClasses for LogManger, which results in `LogManager/Proxy.php` . 
Every proxy uses a `__sleep()` Method which is called on `session_write_close` .
This is where the error happens, because `_underscoreCache` is returned as member variable, but it is not existend in LogManager/Proxy.

The `_underscoreCache` is a member variable coming from `ScopeConfigInterface` which is used by dependency injection inside my class.

So when generating thre proxy this is not considered

**Comment by sevos1984** [comment] 2016-10-10 09:24
@xhallix Is this still actual?

**Comment by sevos1984** [comment] 2016-11-01 09:55
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-11-01 09:55 UTC
Labels: bug report, Component: Customer
