### ISSUE TITLE
Magento 2.4.1 - ZIP code doesn't change unless other field is edited

### ISSUE THREAD

**Issue by gondas33** [magento/magento2#30951] opened 2020-11-17 13:49 UTC
### Preconditions (*)

1. Magento 2.4-develop
2. Magento 2.4.1

### Steps to reproduce (*)

1. Create an order where the zip code contains the ('.') character at the end;

![2020-11-19_12-17](https://user-images.githubusercontent.com/51679138/99652994-2cfe7500-2a61-11eb-8655-91f4bbbf1ea8.png)
2. Click on the **Edit** billing address button;
3. Remove the ('.') character from the zipcode;
2. Save

### Expected result (*)

1. New ZIP code should save without the symbol at the end

### Actual result (*)

1. ZIP code doesn't change unless another field is edited(like address) or the whole zipcode is changed
![Peek 2020-11-19 12-20](https://user-images.githubusercontent.com/51679138/99653495-c0d04100-2a61-11eb-9dff-ee12147e7236.gif)

Issue was also mentioned on: https://magento.stackexchange.com/questions/257750/magento-2-cant-change-the-zip-code-in-order

Reproduced on dev: https://www.loom.com/share/fad8304feab342c6b560155488dae1a7

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by an4rei** [comment] 2020-11-17 13:50
@magento give me 2.4-develop instance

**Comment by an4rei** [comment] 2020-11-17 14:02
issue is reproducible on dev: https://www.loom.com/share/fad8304feab342c6b560155488dae1a7
note: the zipcode must contain a '.' at the end, it might be the same case for other symbols as well.

**Comment by magento-engcom-team** [comment] 2020-11-19 10:23
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39186` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by an4rei** [comment] 2021-02-03 13:33
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed after 14 days if no further activity occurs. Is this issue still relevant? If so, what is blocking it? Is there anything you can do to help move it forward? Thank you for your contributions!

issue is still relevant

**Comment by nabhanmaswood98** [comment] 2021-02-18 20:24
@magento add to contributors team

**Comment by nabhanmaswood98** [comment] 2021-02-18 20:25
@magento I am working on it

**Comment by engcom-Bravo** [comment] 2024-06-05 04:33
Hi @gondas33,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.


https://github.com/magento/magento2/assets/51680745/cf92d10d-41a3-4e44-8957-b1470202df56


New ZIP code should save without the symbol at the end


Hence We are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-05 04:33 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Severity: S3, Progress: done, Component: CustomerAttributes, Issue: ready for confirmation, Reported on 2.4.1
