### ISSUE TITLE
Schedule update from filed misalignment in 768 x 1147 resolution

### ISSUE THREAD

**Issue by amol2jcommerce** [magento/magento2#20402] opened 2019-01-18 12:56 UTC
### Preconditions (*)

1. 2.3.x
2. 2.2.x

### Steps to reproduce (*)

1. Login to Admin panel => Catalog => Categories => Navigate any category => Schedule Design Update section
2. Schedule update from filed misalignment in 768 x 1147 resolution

### Expected result (*)

1. 
![2](https://user-images.githubusercontent.com/18118631/51387981-1f6ac200-1b4e-11e9-9834-9323440d76e6.jpg)

2.

### Actual result (*)

1. 
![1](https://user-images.githubusercontent.com/18118631/51387997-28f42a00-1b4e-11e9-86b3-49995e0a86bd.jpg)

2.

**Comment by magento-engcom-team** [comment] 2019-01-18 12:56
Hi @amol2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@amol2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-18 12:58
Hi @Surabhi-Cedcoss. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-01-18 13:04
@Surabhi-Cedcoss Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-01-18 13:05
@Surabhi-Cedcoss Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97824` were created

**Comment by magento-engcom-team** [comment] 2019-02-10 22:30
Hi @amol2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20403 by @amol2jcommerce in 2.3-develop branch
Related commit(s):
 - [9ce78e09a22c8b8b12f501ab1842a6038b384158](https://github.com/magento/magento2/commit/9ce78e09a22c8b8b12f501ab1842a6038b384158)
 - [48917fc59ac4fee46ca7bb179d31fe5a6939254a](https://github.com/magento/magento2/commit/48917fc59ac4fee46ca7bb179d31fe5a6939254a)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2019-02-10 22:30 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by magento-engcom-team** [comment] 2019-02-13 21:25
Hi @amol2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20404 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [2eeecdb5501e68e53ee1f2e40d5d1012232860c6](https://github.com/magento/magento2/commit/2eeecdb5501e68e53ee1f2e40d5d1012232860c6)

The fix will be available with the upcoming 2.2.9 release.
