### ISSUE TITLE
Password reset link not working after updating to Magento 2.4.4

### ISSUE THREAD

**Issue by BenItt** [magento/magento2#35487] opened 2022-05-17 06:58 UTC
### Preconditions (*)

1. Magento 2.4.4. Community Edition / self hosted
2. Running with PHP 7.4
3. Multi Store environment de (German) en (English)

### Steps to reproduce (*)

1. Go to Stores --> Configurations --> Settings --> Customers --> Customer Configuration
2. Set "Recovery Link Expiration Period (hours) = 2" or leave as it is per configuration settings on "Default Config" level
4. Register customer via YourMagentoInstance.com/en/customer/account/create/
5. Log out
6. Go to Forgot password via YourMagentoInstance.com/en/customer/account/forgotpassword/
7. Enter your E-Mail --> Demand Password Reset
8. Access E-Mail in your e-mail program
9. Click on "Set a new password" in mail

### Expected result (*)

1. Link will forward you to YourMagentoInstance.com/en/customer/account/forgotpassword/
2. You can set new password accordingly

### Actual result (*)

1. Link will forward you to YourMagentoInstance.com/en/customer/account/forgotpassword/
2. Error message will show "Your password reset link has expired."

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by manavluhar** [comment] 2022-05-17 11:33
@magento give me 2.4-develop instance

**Comment by BenItt** [comment] 2022-05-17 11:53
Dear @manavluhar,

thank you for the same.

Using same template code as from your Magento instance leads to same error on our instance :/

Very strange. Magento 2.4.4 update from 2.3.5 was fresh update.

Possibly extensions cause this problem?!

Do you have same CreatePassword.php as the one here?

`<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

namespace Magento\Customer\Controller\Account;

use Magento\Customer\Api\AccountManagementInterface;
use Magento\Customer\Model\ForgotPasswordToken\ConfirmCustomerByToken;
use Magento\Customer\Model\ForgotPasswordToken\GetCustomerByToken;
use Magento\Customer\Model\Session;
use Magento\Framework\App\Action\Context;
use Magento\Framework\App\Action\HttpGetActionInterface;
use Magento\Framework\App\ObjectManager;
use Magento\Framework\Controller\Result\Redirect;
use Magento\Framework\View\Result\Page;
use Magento\Framework\View\Result\PageFactory;
use Magento\Customer\Api\CustomerRepositoryInterface;

/**
 * Controller for front-end customer password reset form
 */
class CreatePassword extends \Magento\Customer\Controller\AbstractAccount implements HttpGetActionInterface
{
    /**
     * @var AccountManagementInterface
     */
    protected $accountManagement;

    /**
     * @var Session
     */
    protected $session;

    /**
     * @var PageFactory
     */
    protected $resultPageFactory;

    /**
     * @var ConfirmCustomerByToken
     */
    private $confirmByToken;

    /**
     * @var GetCustomerByToken
     */
    private $getByToken;

    /**
     * @var CustomerRepositoryInterface
     */
    private $customerRepository;

    /**
     * @param Context $context
     * @param Session $customerSession
     * @param PageFactory $resultPageFactory
     * @param AccountManagementInterface $accountManagement
     * @param ConfirmCustomerByToken|null $confirmByToken
     * @param GetCustomerByToken|null $getByToken
     * @param CustomerRepositoryInterface|null $customerRepository
     */
    public function __construct(
        Context $context,
        Session $customerSession,
        PageFactory $resultPageFactory,
        AccountManagementInterface $accountManagement,
        ConfirmCustomerByToken $confirmByToken = null,
        GetCustomerByToken $getByToken = null,
        CustomerRepositoryInterface $customerRepository = null
    ) {
        $this->session = $customerSession;
        $this->resultPageFactory = $resultPageFactory;
        $this->accountManagement = $accountManagement;
        $this->confirmByToken = $confirmByToken
            ?? ObjectManager::getInstance()->get(ConfirmCustomerByToken::class);
        $this->getByToken = $getByToken
            ?? ObjectManager::getInstance()->get(GetCustomerByToken::class);
        $this->customerRepository = $customerRepository
            ?? ObjectManager::getInstance()->get(CustomerRepositoryInterface::class);

        parent::__construct($context);
    }

    /**
     * Resetting password handler
     *
     * @return Redirect|Page
     */
    public function execute()
    {
        $resetPasswordToken = (string)$this->getRequest()->getParam('token');
        $customerId = (int)$this->getRequest()->getParam('id');
        $isDirectLink = $resetPasswordToken != '';
        if (!$isDirectLink) {
            $resetPasswordToken = (string)$this->session->getRpToken();
            $customerId = (int)$this->session->getRpCustomerId();
        }

        try {
            $this->accountManagement->validateResetPasswordLinkToken($customerId, $resetPasswordToken);
            $this->confirmByToken->resetCustomerConfirmation($customerId);

            // Extend token validity to avoid expiration while this form is
            // being completed by the user.
            $customer = $this->customerRepository->getById($customerId);
            $this->accountManagement->changeResetPasswordLinkToken($customer, $resetPasswordToken);

            if ($isDirectLink) {
                $this->session->setRpToken($resetPasswordToken);
                $this->session->setRpCustomerId($customerId);
                $resultRedirect = $this->resultRedirectFactory->create();
                $resultRedirect->setPath('*/*/createpassword');

                return $resultRedirect;
            } else {
                /** @var Page $resultPage */
                $resultPage = $this->resultPageFactory->create();
                $resultPage->getLayout()
                           ->getBlock('resetPassword')
                           ->setResetPasswordLinkToken($resetPasswordToken)
                           ->setRpCustomerId($customerId);

                return $resultPage;
            }
        } catch (\Exception $exception) {
            $this->messageManager->addErrorMessage(__('Your password reset link has expired.'));
            /** @var Redirect $resultRedirect */
            $resultRedirect = $this->resultRedirectFactory->create();
            $resultRedirect->setPath('*/*/forgotpassword');

            return $resultRedirect;
        }
    }
}
`

Wondering were the bug comes from. Any possibility to reach out to you directly?

Yours

**Comment by BenItt** [comment] 2022-05-17 12:23
Could you check to send Password reset link to any given Gmail address? It seems that link is removed then and arrives as <a>LINK</a> 

Also our finding: 

When loading templates for forgot e-mail after update to Magento 2.4.4 varibale differs from vendor e-mail variable:

Your instance as well as ours:

`<a href="{{var this.getUrl($store,'customer/account/createPassword**/**',[_query:[id:$customer.id,token:$customer.rp_token],_nosid:1])}}" target="_blank">{{trans "Set a New Password"}}</a>`

When I get the variable from /vendor/magento/module-customer/view/frontend/email --> PasswordReset.html it differs:

`<a href="{{var this.getUrl($store,'customer/account/createPassword',[_query:[id:$customer.id,token:$customer.rp_token],_nosid:1])}}" target="_blank">{{trans "Set a New Password"}}</a>`

So old instance adds a "/" behind password which then hinders to function properly.

**Comment by hostep** [comment] 2022-05-17 13:08
Does the following screenshot help? It's a report I send to Hyvä frontend themes in order to have them fix something very similar.
Maybe also double check if your custom theme didn't overwrite the `resetforgottenpassword.phtml` because in that case you might be missing something there that was added in 2.4.4

<img width="1036" alt="Screen Shot 2022-05-17 at 15 06 42" src="https://user-images.githubusercontent.com/85479/168817971-27fb55a6-6fbe-4d00-91a5-e59027665786.png">

**Comment by BenItt** [comment] 2022-05-17 13:18
Dear @hostep,

this looks like it could be a solution. Indeed the green marked parts are missing in our vendor/magento/module-customer/view/frontend/templates/form/resetforgottenpassword.phtml

We check to change and inform about progress.

**Comment by hostep** [comment] 2022-05-17 13:21
Alrighty, it's most likely going to be this that fixes your issue.

Next time when you work on a Magento upgrade, consider using this tool: https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper, it helped us discover this problem (and many others in the past) 🙂

**Comment by BenItt** [comment] 2022-05-17 13:30
Dear @hostep,

roll back. I have checked and our Core looks exactly like the screenshot you had posted.

Possibly still our Theme overwrites this function. Checking this now going back to Luma. Thank you for the Ampersand Patch Helper. Will consider this.

**Comment by BenItt** [comment] 2022-05-17 14:59
Dear @hostep,

in Luma Theme same issue. Very weird.

Yours

**Comment by hostep** [comment] 2022-05-17 18:31
Ah okay, then it must be a different problem than I ran into apparently.

**Comment by engcom-Delta** [comment] 2022-06-03 06:13
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Closed as completed by engcom-Delta** 2022-06-03 06:13 UTC
Labels: Issue: needs update, Reported on 2.4.4

**Comment by robsoned** [comment] 2022-08-29 21:17
Hello guys, In case someone is having some problem as well. We started having this problem after upgrading from magento 2.3* to Magento 2.4.3-p2. Our problem here was fixed by:

1. Updating `resetforgottenpassword.phtml` in our custom theme, to include the customerId in the form action. Like @hostep had commented above: https://github.com/magento/magento2/issues/35487#issuecomment-1129189569
2. Updating the reset password email template at Marketing -> Email Templates, to also include the customerId in the form action. You can create a new form from the `Forgot Password` template to see the difference between the 'new' one in magento2.4 and the one you've been using.
    The old version:  [_query:[token:$customer.rp_token],_nosid:1]
    The one updated:  [_query:[id:$customer.id,token:$customer.rp_token],_nosid:1]
    You can see that a new parameter is added to the button url, `id` in this case.
    
    
Resuming: 

* Check your resetforgottenpassword.phtml in your theme, if you have it.
* Check your Reset Password email template in the Admin.

**Comment by royalkaroma** [comment] 2023-01-29 09:53
Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop and 2.4.5 instances and the issue is reproducible on both the instances.

We are not getting any exception.But the session has expired, and again we need to Login.

Steps to reproduce :

1.Have 2 browsers open. One with the magento shop, second one with your gmail account.

2.Register a new customer.

3.In the first browser, click on the "forgotten password" link and enter your email address. You'll be redirected to a customer login page. Don't close the tab.

4.In the second browser, click on the "reset password" link in your gmail account. A new browser tab will open. Set a new password.

5.Go back to the first browser, enter your new login information and click on the "login" button.

and i got
Capture
![Capture](https://user-images.githubusercontent.com/36032214/215318543-7f3ab5d0-c898-4e63-bf76-48fbae578556.PNG)

**Comment by fabrice-dresscodes** [comment] 2023-02-14 07:24
Got the same than @royalkaroma on 2.4.4

**Comment by karanguilherme** [comment] 2023-04-27 13:46
Reset Password link not working where outlook mail
