### ISSUE TITLE
Cannot use a scalar value as an array in SessionManager

### ISSUE THREAD

**Issue by HenKun** [magento/magento2#31742] opened 2021-01-18 11:52 UTC
https://github.com/magento/magento2/blob/1e846a4aa38f1ff5d7238d70df9d887b3bdf5acb/lib/internal/Magento/Framework/Session/SessionManager.php#L492
### Preconditions (*)

1. Magento 2.4.1 (we encountered it in previous version, too)
2. Redis for Session Storage (it occured also with file session storage)

### Steps to reproduce (*)

1. Occurs randomly

### Expected result (*)

1. Everything works fine

### Actual result (*)

Randomly the store crashes with:

```
Warning: Cannot use a scalar value as an array in \/home\/xx\/public_html\/magento2\/prod\/releases\/20201224091226\/vendor\/magento\/framework\/Session\/SessionManager.php on line 492
```

Full Report:

```
#1 Magento\\Framework\\Session\\SessionManager->_addHost() called at [vendor/magento/framework/Session/SessionManager.php:216]
#2 Magento\\Framework\\Session\\SessionManager->start() called at [generated/code/Magento/Backend/Model/Auth/Session/Interceptor.php:32]
#3 Magento\\Backend\\Model\\Auth\\Session\\Interceptor->start() called at [vendor/magento/framework/Session/SessionManager.php:141]
#4 Magento\\Framework\\Session\\SessionManager->__construct(&Magento\\Framework\\App\\Request\\Http#0000000006b036360000000061080f76#, &Magento\\Framework\\Session\\SidResolver\\Proxy#0000000006b036a50000000061080f76#, &Magento\\Backend\\Model\\Session\\AdminConfig#0000000006b037420000000061080f76#, &Magento\\Framework\\Session\\SaveHandler#0000000006b0373c0000000061080f76#, &Magento\\Framework\\Session\\Validator#0000000006b0373f0000000061080f76#, &Magento\\Framework\\Session\\Storage#0000000006b0373e0000000061080f76#, &Magento\\Framework\\Stdlib\\Cookie\\PhpCookieManager#0000000006b036e60000000061080f76#, &Magento\\Framework\\Stdlib\\Cookie\\CookieMetadataFactory#0000000006b036790000000061080f76#, &Magento\\Framework\\App\\State#0000000006b036040000000061080f76#) called at [vendor/magento/module-backend/Model/Auth/Session.php:103]
#5 Magento\\Backend\\Model\\Auth\\Session->__construct(&Magento\\Framework\\App\\Request\\Http#0000000006b036360000000061080f76#, &Magento\\Framework\\Session\\SidResolver\\Proxy#0000000006b036a50000000061080f76#, &Magento\\Backend\\Model\\Session\\AdminConfig#0000000006b037420000000061080f76#, &Magento\\Framework\\Session\\SaveHandler#0000000006b0373c0000000061080f76#, &Magento\\Framework\\Session\\Validator#0000000006b0373f0000000061080f76#, &Magento\\Framework\\Session\\Storage#0000000006b0373e0000000061080f76#, &Magento\\Framework\\Stdlib\\Cookie\\PhpCookieManager#0000000006b036e60000000061080f76#, &Magento\\Framework\\Stdlib\\Cookie\\CookieMetadataFactory#0000000006b036790000000061080f76#, &Magento\\Framework\\App\\State#0000000006b036040000000061080f76#, &Magento\\Framework\\Acl\\Builder\\Proxy#0000000006b037390000000061080f76#, &Magento\\Backend\\Model\\UrlInterface\\Proxy#0000000006b036b10000000061080f76#, &Magento\\Backend\\App\\Config#0000000006b036b30000000061080f76#, NULL) called at [generated/code/Magento/Backend/Model/Auth/Session/Interceptor.php:14]
#6 Magento\\Backend\\Model\\Auth\\Session\\Interceptor->__construct(&Magento\\Framework\\App\\Request\\Http#0000000006b036360000000061080f76#, &Magento\\Framework\\Session\\SidResolver\\Proxy#0000000006b036a50000000061080f76#, &Magento\\Backend\\Model\\Session\\AdminConfig#0000000006b037420000000061080f76#, &Magento\\Framework\\Session\\SaveHandler#0000000006b0373c0000000061080f76#, &Magento\\Framework\\Session\\Validator#0000000006b0373f0000000061080f76#, &Magento\\Framework\\Session\\Storage#0000000006b0373e0000000061080f76#, &Magento\\Framework\\Stdlib\\Cookie\\PhpCookieManager#0000000006b036e60000000061080f76#, &Magento\\Framework\\Stdlib\\Cookie\\CookieMetadataFactory#0000000006b036790000000061080f76#, &Magento\\Framework\\App\\State#0000000006b036040000000061080f76#, &Magento\\Framework\\Acl\\Builder\\Proxy#0000000006b037390000000061080f76#, &Magento\\Backend\\Model\\UrlInterface\\Proxy#0000000006b036b10000000061080f76#, &Magento\\Backend\\App\\Config#0000000006b036b30000000061080f76#, NULL) called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121]
#7 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Magento\\Backend\\...', array(&Magento\\Framework\\App\\Request\\Http#0000000006b036360000000061080f76#, &Magento\\Framework\\Session\\SidResolver\\Proxy#0000000006b036a50000000061080f76#, &Magento\\Backend\\Model\\Session\\AdminConfig#0000000006b037420000000061080f76#, &Magento\\Framework\\Session\\SaveHandler#0000000006b0373c0000000061080f76#, &Magento\\Framework\\Session\\Validator#0000000006b0373f0000000061080f76#, &Magento\\Framework\\Session\\Storage#0000000006b0373e0000000061080f76#, &Magento\\Framework\\Stdlib\\Cookie\\PhpCookieManager#0000000006b036e60000000061080f76#, &Magento\\Framework\\Stdlib\\Cookie\\CookieMetadataFactory#0000000006b036790000000061080f76#, &Magento\\Framework\\App\\State#0000000006b036040000000061080f76#, &Magento\\Framework\\Acl\\Builder\\Proxy#0000000006b037390000000061080f76#, &Magento\\Backend\\Model\\UrlInterface\\Proxy#0000000006b036b10000000061080f76#, &Magento\\Backend\\App\\Config#0000000006b036b30000000061080f76#, NULL)) called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:108]
#8 Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\Backend\\...') called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:150]
#9 Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('Magento\\Backend\\...') called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:79]
#10 Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\Backend\\...') called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:150]
#11 Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('Magento\\Backend\\...') called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:79]
#12 Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\Backend\\...') called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:150]
#13 Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('Magento\\Backend\\...') called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:125]
#14 Magento\\Framework\\ObjectManager\\Factory\\Compiled->parseArray(array('csrf_validator' => array('_i_' => 'Magento\\Backend\\...'), 'http_method_vali...' => array('_i_' => 'Magento\\Framewor...'))) called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:86]
#15 Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('RequestValidator') called at [vendor/magento/framework/ObjectManager/ObjectManager.php:70]
#16 Magento\\Framework\\ObjectManager\\ObjectManager->get('RequestValidator') called at [vendor/magento/framework/App/FrontController.php:86]
#17 Magento\\Framework\\App\\FrontController->__construct(&Magento\\Framework\\App\\RouterList#0000000006b036880000000061080f76#, &Magento\\Framework\\App\\Response\\Http\\Interceptor#0000000006b036fd0000000061080f76#, NULL, NULL, NULL, NULL, NULL) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:14]
#18 Magento\\Framework\\App\\FrontController\\Interceptor->__construct(&Magento\\Framework\\App\\RouterList#0000000006b036880000000061080f76#, &Magento\\Framework\\App\\Response\\Http\\Interceptor#0000000006b036fd0000000061080f76#, NULL, NULL, NULL, NULL, NULL) called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121]
#19 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Magento\\Framewor...', array(&Magento\\Framework\\App\\RouterList#0000000006b036880000000061080f76#, &Magento\\Framework\\App\\Response\\Http\\Interceptor#0000000006b036fd0000000061080f76#, NULL, NULL, NULL, NULL, NULL)) called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:108]
#20 Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\Framewor...') called at [vendor/magento/framework/ObjectManager/ObjectManager.php:70]
#21 Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\Framewor...') called at [vendor/magento/framework/App/Http.php:115]
#22 Magento\\Framework\\App\\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#23 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:263]
#24 Magento\\Framework\\App\\Bootstrap->run(&Magento\\Framework\\App\\Http\\Interceptor#0000000006b036ff0000000061080f76#) called at [pub/index.php:40]
```

## Reason

`$this->_getHosts()` in `vendor/magento/framework/Session/SessionManager.php` on line 491 seems to return a scalar, which cannot be used on line 492. However, I cannot imagine how `$hosts` can be a scalar, when `$_SESSION[self::HOST_KEY]` is only set on line 493, where `$hosts` for sure is an array.

## Possible solution

As suggested in the links below, it might be a solution to replace 

```
protected function _getHosts()
{
    return $_SESSION[self::HOST_KEY] ?? [];
}
```

with

```
protected function _getHosts()
{
        
   return isset($_SESSION[self::HOST_KEY]) ? [$_SESSION[self::HOST_KEY]] : [];

}
```

However, this will give problems if `$_SESSION[self::HOST_KEY]` is an array (which it is supposed to be), so it won't work IMHO.

## Other Links

Other users have encountered the error, too:

https://community.magento.com/t5/Magento-2-x-Technical-Issues/Warning-Cannot-use-a-scalar-value-as-an-array-in-SessionManager/td-p/454851

https://magento.stackexchange.com/questions/318895/warning-cannot-use-a-scalar-value-as-an-array-in-sessionmanager-php-on-line

https://magento.stackexchange.com/questions/204426/magento-2-error-cannot-use-a-scalar-value-as-an-array

Github issue #7236 closed due to missing feedback

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by orlangur** [comment] 2021-01-18 12:34
@HenKun reliable steps to reproduce need to be provided.

If the issue was real, instead of suggested
```
return isset($_SESSION[self::HOST_KEY]) ? [$_SESSION[self::HOST_KEY]] : [];
```
one could use
```
return isset($_SESSION[self::HOST_KEY]) ? (array)$_SESSION[self::HOST_KEY] : [];
```

**Comment by HenKun** [comment] 2021-01-18 13:06
@orlangur Unfortuantely I cannot provide deterministic reproducible steps, since it occurs occasionally.

Your suggested code change might work. However it is not clear to me in which path this value can get a scalar value at all. So it might be better to find the cause where and why a scalar value might be assigned.

**Comment by mrtuvn** [comment] 2021-04-06 16:06
seem not stale and we may need more investigate on this scenario
Maybe create PR following suggest by https://github.com/magento/magento2/issues/31742#issuecomment-762222658

**Comment by pmbright** [comment] 2021-04-27 15:04
I get the same problem on Magento 2.3.6 using redis for session storage, I reverted to using DB for session storage and still got the problem.

Clearing site cookies fixes it temporarily.

**Comment by engcom-Echo** [comment] 2021-06-16 08:34
Hi @HenKun ,

As per your screenshot , it looks the issue is a warning and this shouldn't crash the application . 
Can you please specify what production issues are you getting because of this , also can you please elaborate the steps to re-produce so that we can try to re-produce the same at our end.

Thanks

**Comment by engcom-Hotel** [comment] 2021-06-30 08:31
Hello @HenKun ,

It seems that your issue has been resolved, since we have not received any reply from your side for past 14 days. Hence we are closing this issue. You can either reopen it, in case you are still facing the issue or create a new ticket.

Thanks

**Closed as completed by engcom-Hotel** 2021-06-30 08:31 UTC
Labels: Component: Framework/Session, Severity: S1, Issue: needs update, Reported on 2.4.1
