### ISSUE TITLE
PayPal doesn’t work

### ISSUE THREAD

**Issue by Smoult07** [magento/magento2#38255] opened 2023-12-08 14:15 UTC
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug
- I tried to check out but whenever I click continue with PayPal the page goes white and it won’t load

### Steps to reproduce

I’m not sure how to fix this

### Expected result

When clicking continue to PayPal the website successfully brings the customer to paypal

### Actual result

Brings me to a white screen and not paypal

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by FadedOut** [comment] 2023-12-09 21:59
Hello @Smoult07 welcome to Magento Github.

A few things:

A) When you click PayPal Checkout, a second window should pop up - does that happen? If so, is that where the white screen appears or is the white screen appearing in the main website window?

B) You may be new to Magento - for the best, quickest help (for us to help you and so you can maybe find the solution before posting here) you should always use the log files to see if there are any errors being logged. They are always located in the /var/log/ folder on your server in the Magento directory (something like: /public_html/var/log/). Check exception.log & system.log files. See if there are any errors being logged when you click the paypal checkout button. It may be something simple you can resolve yourself or you can post the error here. 

C) Seeing how this is your first git ticket, a few tips for you: that first box where it says "Preconditions and environment" and then it says "Magento version", you are supposed to enter the version of Magento you are using there. And you can erase the text that says "Anything else that would help a developer reproduce the bug". This section is great to let us know things like what PHP version you are using, if you're using Apache or NGINX, are you using default theme or a custom theme...things like that help us narrow down if the culprit is on your side or Magento side. Then when you entered "I tried to check out but whenever I click continue with PayPal the page goes white and it won’t load" should go under "Steps to reproduce". Just some tips to help you create a clearer ticket next time.

**Comment by engcom-Dash** [comment] 2023-12-20 14:30
Hi @Smoult07 

Thanks for reporting and collaboration.

Verified the issue on magento developer instance. We are not able to reproduce this issue. 
When we tried to place an order using paypal we are not getting any errors and able to place the order successfully.
Please refer the screenshot attached.
please clarify this point :
When you click PayPal Checkout, a second window should pop up - does that happen? If so, is that where the white screen appears or is the white screen appearing in the main website window?
and please check the magento version you are using and any if you are having any third party extensions.

**Comment by engcom-Dash** [comment] 2024-01-09 06:14
Hi @Smoult07 

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2024-01-09 06:14 UTC
Labels: Issue: needs update, Reported on 2.4.x
