### ISSUE TITLE
Missing payment method on sales order grid

### ISSUE THREAD

**Issue by Leone** [magento/magento2#23976] opened 2019-08-01 11:40 UTC
In the order grid, in the admin panel, payment methods are missing:
- in filters (it is not possible to choose e.g. "Bank Transfer Payment"
- in the payment method column in the grid (column "Payment Method" is empty if customer chose e.g. "Bank Transfer Payment" method).

### Preconditions (*)

1. Magento 2.2.9 and 2.3.0+
2. Configured payment methods (e.g. Bank Transfer Payment)

### Steps to reproduce (*)

1. Enable some payment method, for example, "Bank Transfer Payment" in the admin panel
2. Create an order using this payment method
3. Open Order Grid page in the admin panel
4. Add Payment Method column to the grid

### Expected result (*)

1. Method "Bank Transfer Payment" should be in "Payment Method" filter in the filters section
2. Name of the payment method should be visible in the payment method column in the grid

### Actual result (*)

1. Method "Bank Transfer" is missing in "Payment Method" filter
2. Payment method column is empty

I have checked the code and found that the problem is in \Magento\Payment\Helper\Data::getPaymentMethodList method.
@victorpetryk added `if (!empty($data['active']))` condition in [this commit](https://github.com/magento/magento2/commit/1181d0fba1d2061f8136bd777041559792867c3d#diff-8256f35d1118cefe17ef3731bbc346ab) (MAGETWO-93221).
Unfortunately, some payment methods (default, like banktransfer and from other payment providers) don't have flag `active` set to `1` by default.

I wasn't able to find any information why this condition was added to getPaymentMethodList() method.
Could you provide a reason why it was introduced?

**Comment by Leone** [comment] 2019-08-01 11:41
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-08-01 11:41
Hi @Leone. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-08-01 11:42
Hi @Leone, here is your [Magento instance](https://i-23976-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23976-2-3-develop.instances.magento-community.engineering/admin](https://i-23976-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Leone** [comment] 2019-08-01 11:49
I'm sorry, I just noticed that this issue has been fixed in 2.3-develop ([commit](https://github.com/magento/magento2/commit/da0c7374e5dcae81735552bdd685ee5e646b8486))

But the issue is still valid in 2.3.2. What are the chances that in 2.3.3 version the bug will be fixed?

**Comment by engcom-Bravo** [comment] 2019-08-02 13:39
Hello @Leone. Thanks for applying. The general rule is - If the issue is fixed in the develop version it shall be supplied with the next release version.

**Closed as completed by engcom-Bravo** 2019-08-02 13:39 UTC
Labels: Issue: Format is valid
