### ISSUE TITLE
Outdated Composer Packages - magento/composer

### ISSUE THREAD

**Issue by jonathan-martz** [magento/magento2#26604] opened 2020-01-31 09:11 UTC
https://github.com/magento/composer/issues/23

### Preconditions (*)
1. a simple Magento2 Shop with Community Edition

### Steps to reproduce (*)
1. Update Magento2 to 2.3.3
2. Update Php to 7.2
3. use Proxy like Toran which uses repo.magento.com as source of package
4. clean composer cache
5. Run Composer update

### Expected result (*)
1. updates every package, maybe fails because of php version issues of other packages

### Actual result (*)
1. Doesnt find a possible package of versions, because of Missing Version which is compatible wit Magento 2.3.3 and Php 7.2

**Comment by engcom-Bravo** [comment] 2020-02-03 11:24
Hello @jonathan-martz 

Thank you for your report 

When updating to Magento 2.3.3, before updating the composer, please use the following commands: 
1. ```php bin bin/magento maintenance:enable```
2. ```composer remove magento/product-community-edition --no-update```
3. ```composer require magento/product-community-edition=2.3.3 --no-update```
4. ```composer require --dev allure-framework/allure-phpunit:~1.2.0 friendsofphp/php-cs-fixer:~2.14.0 lusitanian/oauth:~0.8.10 magento/magento-coding-standard:~3.0.0 magento/magento2-functional-testing-framework:2.4.5 pdepend/pdepend:2.5.2 phpmd/phpmd:@stable phpunit/phpunit:~6.5.0 sebastian/phpcpd:~3.0.0 squizlabs/php_codesniffer:~3.4.0 --sort-packages --no-update```
5. ```composer require –dev friendsofphp/php-cs-fixer:~2.10.0 –no-update```
6. ```composer require –dev sebastian/phpcpd:~3.0.0 –no-update```
7. And run ```composer update```
If you still face error with upgrade, please try to clean cache from your magento root directory
```rm -rf var/*
rm -rf pub/static/*
rm -rf generated/*
``` 
and edit the _composer.json_ file. Add 
``` 
"Magento\\": "app/code/Magento/",
"Zend\\Mvc\\Controller\\": "setup/src/Zend/Mvc/Controller/"
```
So it would look like this 
![zend](https://user-images.githubusercontent.com/51680745/73649407-64de2c80-4688-11ea-9e3a-b614885a8187.png)

Please, let us know in the comments section if this helped or not 

Thank you

**Comment by jonathan-martz** [comment] 2020-02-03 12:13
Fails on Step 5, because php 7.3 isnt compatible.
If i skip that it works, like expected because magento 2.3.3 isnt my problem.

I want to install 2.3.4, bot ;)

When i add 2.3.4 to composer.json and try update again, it fails because of:
Your requirements could not be resolved to an installable set of packages.

**Comment by engcom-Bravo** [comment] 2020-02-03 12:34
Hello @jonathan-martz 

In the first **Step to Reproduce** you've set _Update Magento2 to **2.3.3**_

If you face the same with upgrading to Magento 2.3.4, please try to
- install php 7.2
- on the step3 change the 2.3.3 to 2.3.4 ```composer require magento/product-community-edition=2.3.4 --no-update```


Thank you

**Comment by jonathan-martz** [comment] 2020-02-03 12:37
No everything works well with 2.3.3.
With 2.3.4 it fails, like always.
Tried many things like clean cache, no-update stuff, install with composer install and no lock or composer update with no lock.

**Comment by engcom-Bravo** [comment] 2020-02-03 12:46
@jonathan-martz 

Thank you for the quick response. 

As we understand, you've tried to use the following command line, correct? ```composer require magento/product-community-edition=2.3.4 --no-update```

**Comment by jonathan-martz** [comment] 2020-02-03 13:36
Yes.
Result is:
Could not find package magento/product-community-edition in a version matching 2.3.4

**Comment by engcom-Bravo** [comment] 2020-02-03 14:21
@jonathan-martz 

This error usually occurs if try to update a git version using a composer update. 
![invalidargument](https://user-images.githubusercontent.com/51680745/73660414-d1652580-46a0-11ea-9a82-4137364a02e3.png)

- Do you experience the same error as on the screenshot? 
- Is your current Magento 2.3.3 is a git version? 

Thank you in advance

**Comment by jonathan-martz** [comment] 2020-02-03 14:27
![magento-update-2 3 4](https://user-images.githubusercontent.com/20771653/73660977-8b589380-4699-11ea-8da2-30397178b895.png)

What do you mean with git version?
Iam using composer to update the project.

**Comment by engcom-Bravo** [comment] 2020-02-03 14:39
> ![magento-update-2 3 4](https://user-images.githubusercontent.com/20771653/73660977-8b589380-4699-11ea-8da2-30397178b895.png)
> 
> What do you mean with git version?
> Iam using composer to update the project.

When you installed the current Magento 2.3.3 did you:
- clone it from github?
OR
- installed it via composer like ```composer create-project --repository=https://repo.magento.com/ magento/project-community-edition=2.2.3 .``` ?

**Comment by jonathan-martz** [comment] 2020-02-03 14:48
I used composer create-project.

**Comment by engcom-Bravo** [comment] 2020-02-03 15:07
Can I please ask you to try one more thing, because it all looks like an OS-specific issue, not a general Magento issue.

Can you please try to create a new folder on your machine, and try to create a new Magento instance 
```composer require magento/product-community-edition=2.3.4 --no-update```

Let's see if any error occurs.

Sorry for so many questions. We try to reproduce this, but no results so far.

**Comment by jonathan-martz** [comment] 2020-02-03 15:20
It works but the reason is that he isnt using toran as proxy, which uses repo.magento.com.

**Comment by jonathan-martz** [comment] 2020-02-03 15:30
Looks like using repo.magento.com works because composer project use repo.magento.com.
The Problem is Toran i think.

**Comment by jonathan-martz** [comment] 2020-02-03 16:21
... doesnt works Toran is the Problem.

**Comment by engcom-Bravo** [comment] 2020-02-04 08:01
@jonathan-martz 

We are glad that the issue is resolved.

As this is not a Magento issue, we have to close it.

If you ever experience any issues with Magento, please feel free to create a new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 

Thank you for your collaboration

**Closed as completed** 2020-02-04 08:01 UTC
Labels: Issue: Format is valid, Reported on 2.3.3
