### ISSUE TITLE
I can not translate title attribute in xml files translation not working

### ISSUE THREAD

**Issue by megamosa** [magento/magento2#8676] opened 2017-02-25 17:15 UTC
hi i have this code in acl.xml file

` <resource id="Magento_Paypal::use" title="Place Order Using Billing Agreements" translate="title" sortOrder="15" />`
and i already added this string in ar_SA.csv file like that

  `   "Place Order Using Billing Agreements","translation here"`
but translation doesn't appear yet !!, i missed something ? I've updated translation file, flushed the cache but it didn't help. Any suggestions would be highly appreciated :)?

![place](https://cloud.githubusercontent.com/assets/4708233/23333156/6fd14448-fb8f-11e6-918d-441315f0ea4d.jpg)

also how how I can translate magento roles resources
![rol](https://cloud.githubusercontent.com/assets/4708233/23333377/31a7ba54-fb93-11e6-80ad-a7d64f3936f3.jpg)

**Comment by megamosa** [comment] 2017-02-26 13:36
any help?

**Comment by okorshenko** [comment] 2017-03-13 19:30
Thank you for reporting the issue. The title is not translated https://github.com/magento/magento2/blob/develop/app/code/Magento/Integration/Helper/Data.php#L24

The attribute translate="title" is designed for the tool that will collect all phrases for translation files but this attribute does not force translation itself

**Comment by megamosa** [comment] 2017-03-14 01:33
@okorshenko thank you for kind reply so  how I can translate magento roles resources !!  Any suggestions would be highly appreciated

**Comment by okorshenko** [comment] 2017-03-14 23:15
@desertlioon the easiest fix will be:
https://github.com/magento/magento2/blob/develop/app/code/Magento/Integration/Helper/Data.php#L24
` $item['data'] = __($resource['title']);`

This fix works on my installation

**Comment by magento-engcom-team** [comment] 2017-09-20 23:03
@megamosa, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 23:03 UTC
Labels: Issue: Ready for Work, Fixed in 2.2.x, Issue: Format is not valid
