### ISSUE TITLE
It downs when filtered to 999 per page

### ISSUE THREAD

**Issue by yrp06** [magento/magento2#37883] opened 2023-08-17 00:09 UTC
### Preconditions (*)

1. Magento ver. 2.3.7-p4
2. It downs when I filter per page tap to 999 in 'Orders' page.

### Steps to reproduce (*)

1. 
2.
3. 

### Expected result (*)

1. I'd like to see as much orders as possible in one page.

### Actual result (*)

1. It downs....

**Comment by engcom-Bravo** [comment] 2023-08-17 10:07
Hi @yrp06,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Go to Sales>>Orders
- Filter 999 orders in one page.

We are able to filter the orders using 999 per page.

<img width="1494" alt="Screenshot 2023-08-17 at 11 44 05 AM" src="https://github.com/magento/magento2/assets/51680745/cf79b29c-703f-470c-b30b-f257046a06d7">



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by yrp06** [comment] 2023-08-21 06:41
Hello,

I've sent you an e-mail like below. Can you share me any updates?

Best,

===================== original e-mail ====================
Dear Venkata,

Thanks for reviewing.

What I have asked you was as below.
When I filter to '999' per page, the server downs and I can't do anything. (all the pages go unclickable / cursor disabled)
I'd like to reset the filter to default, but I can't do any further actions...

Can you please help?

**Comment by engcom-Bravo** [comment] 2023-08-22 06:37
Hi @yrp06,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.


We are able to filter with the Custom value with 999.



https://github.com/magento/magento2/assets/51680745/5f509eb3-57a7-4549-8a9b-3638e209918f




Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.

Thanks.

**Comment by yrp06** [comment] 2023-08-24 01:37
Hi,

What I meant was that I cannot filter 'per page' option to '999' or other options like '20' or something
because the page already went down when I click and move on to SALES > ORDERS menu.

I cannot click anything on this page...

Can you please review?

<attach captured image link>
https://bigfile.mail.naver.com/download?fid=BYRmW40ZpB0P16ij1XiCHqujKqEmKAgXKIYZKAUqKA2ZFAumKqM9KwYwFov9FA2wKxvlHq2lpoI0azMmKx30MxbmF4EmMxpSpAFvMou9ax+SpxEm

**Comment by engcom-Bravo** [comment] 2023-08-24 12:55
Hi @yrp06,

Thanks for your update.

Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue. Please check below possible workarounds which may help you resolve the issue:

- Please check "catalog_product_entity" table in the database for any sku 's having NULL value and update them:
- UPDATE catalog_product_entity SET sku='' WHERE sku IS NULL;
- Check if the user is having very restricted Access to the magento backend and grant users access to the product catalog / orders that may fix this issue.
- Run the query: TRUNCATE ui_bookmark; this will reset the grid back to it's default and stop the infinite load.

Kindly recheck the issue on Magento 2.4-develop branch and elaborate steps to reproduce if the issue is still reproducible.

Thank you.

**Comment by engcom-Bravo** [comment] 2023-09-05 06:05
Hi @yrp06,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-09-05 06:05 UTC
Labels: Issue: needs update, Reported on 2.3.7-p4
