### ISSUE TITLE
Invalid option value in row(s) when importing configurable products

### ISSUE THREAD

**Issue by githeat** [magento/magento2#7284] opened 2016-11-02 21:28 UTC
When I try and use the Magento 2 native import function, I get a validation error which reads
"1. Invalid option value in row(s)". This happens when importing configurable products, and does not affect simple/virtual products. This does not affect every single configurable product I'm trying to import, I cannot find a pattern.

I have used Notepad++ to encode the .csv using UTF-8-BOM. I have also ensured there are no special characters within the document, and the CSV is formatted correctly. 

### Preconditions

1.  Magento 2.1.2 Community Edition
2.  PHP 7.0.11-1
3. MySQL 5.6.30
4. Ubuntu 14.04.1 LTS

### Steps to reproduce

1. **(Using this .xlsx - I couldn't attach a .csv): [Magento configurable products error.xlsx](https://github.com/magento/magento2/files/567730/Magento.configurable.products.error.xlsx)**, login to Magento 2 admin panel.
2. Click "System" on the left hand side, select "import" underneath "Data Transfer" header.
3. Use the following settings for import:
- Entity type: "products"
- Import behaviour "Add/Update" and "Stop on error"
- Allowed errors count "1"

- Field seperator ","
- Multiple value separator ","
- File to import "--Select Magnto file I have attached--"

### Expected result

1. The imported records should pass validation correctly, and should show an "import" button, along with a count of products/errors.

### Actual result

1. ![Image of error, showing row numbers](https://gyazo.com/988093712dfdcf7803f7aa35bb239b01.png)
2. No error logs in "/var/log/apache2/error.log" or "/var/log/mysql/error.log"
3. Potentially unrelated, but this entry appears in "/path to magento install/var/log/system.log"
"main.INFO: Cache file with merged layout: LAYOUT_adminhtml_STORE1_3653d47e1ccc494d3d055c758a8b45f4e and handles adminhtml_import_validate: Please correct the XML data and try again.  [] []"

**Comment by MattDelac** [comment] 2017-01-10 09:50
Hello,

I've got the same problem and all my configurable products have been import except 57 that encounter the same problem (over 7700+ products in overall).

Do you know if this issue is fixed with Magento 2.1.3 ?

Thank you

**Comment by lucaspozzi** [comment] 2017-01-10 15:59
@MattDelac It's not fixed in 2.1.3.
Best alternative is to db dump.

**Comment by antbates91** [comment] 2017-01-18 09:16
I can also confirm I've come across this error in 2.1.2 and 2.1.3. Like @githeat says, It's only happening for Configurable Products and there also doesn't seem to be a pattern to the behaviour.

My Preconditions are

Magento 2.1.3 Community Edition
PHP 7.0.13 / 7.0.7
MySQL 5.6.34

**Comment by Jawwadiftikhar** [comment] 2017-01-31 06:14
Resolved, I had the same issue but it was due to the configurable products that i was trying to upload them before all the associated simple products.
Check your associated simple products that all of them are imported before you import configurable product.
OR
(For dropdown/multiple select) check the attribute option values of simple products if they are same in admin.

**Comment by magento-engcom-team** [comment] 2017-10-11 14:30
@githeat, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-11 14:30 UTC
Labels: bug report, Component: ImportExport, Issue:  Cannot Reproduce, Issue: Format is valid

**Comment by denzildoyle** [comment] 2020-09-24 22:07
I was able to reproduce this error when there is a trailing space at the end of the product attribute name.
