### ISSUE TITLE
\n & other can break csv files for i18n phrases !?

### ISSUE THREAD

**Issue by iw0der** [magento/magento2#3330] opened 2016-02-08 12:26 UTC
Hi,
I have the feeling that the .csv files generated by 

`bin/magento i18n:collect-phrases -m --output=/tmp/phrases.csv ~/www`

breaking some of the rules of the csv files! I see, for example, that the sequences "\n" in the code are unfortunately interpreted and transformed into a LF into the csv file :-(

So, for example, when in **./vendor/magento/module-config/Model/Config/Structure/Reader.php** we have the following code:

`new \Magento\Framework\Phrase("Invalid XML in file %1:\n%2", [$key, $e->getMessage()])`

then, in the file that collects the texts, we find the sentence split into multiple lines because the code has interpreted "\n" in the text:

"Invalid XML in file %1:
%2","Invalid XML in file %1:
%2",module,Magento_Config

So getting a single record broken in three lines :-( Now I do not trust what I say, but if I try to import the .csv file in a program like OOo, I lose several phrases in the file for this and for other reasons (it seems that there are even worse cases).

_Am I wrong to consider this an abnormal practice or there is an error, like a printf that   interpret the text as it should not?_

Tnx,
A

**Comment by mazhalai** [comment] 2016-02-08 14:33
@iw0der are you  using php7?

**Comment by iw0der** [comment] 2016-02-08 14:44
No: `Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.5.32` with `mysqlnd 5.0.11-dev - 20120503` clìent and `mysqld  Ver 5.6.29 for Linux on x86_64`.

Essentially a CentOS 7 to which was added a version of PHP and MySQL compatible with the software.

73s,
A.

**Comment by scholtz** [comment] 2016-02-09 19:19
I think it is not a problem.. http://php.net/manual/en/function.fgetcsv.php can handle this...

problem might be only if you are first splitting on new lines, and then look for data

**Comment by iw0der** [comment] 2016-02-10 09:12
I am not very much agree; probably not all programs that work with csv support this splitting across multiple lines; I would find more linear store \n, \t or other as they are in the original texts; not least because one can see well \t or \n or \b rather than the equivalent "real" (I'm so legacy!?). 

Well, if we skip this there are other problems with some strange sequences of quotes, maybe not escaped well... I see if later I find them, maybe they are my eyes that cross, now I do not see :-)

Thanks for the note,

73s,
A.

**Comment by davidalger** [comment] 2016-02-10 22:37
@iw0der \n and \t are merely representations of the line-feed and tab character codes. To store them differently in the output would require actually escaping them on write, and unescaping them on read. I.e. while you see `"Invalid XML in file %1:\n%2"` in the PHP code, you see the \n but the computer sees a line-feed and not a \ followed by an 'n'.

You may need to either tell OOo to read the file using the double-quote to properly break up the file, or switch to an alternate program for editing the CSV file. 

Closing as this is not a bug, but expected behavior. If you have questions on how to work with these files, etc, might try heading over to and posting on the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2).

**Closed as completed by davidalger** 2016-02-10 22:37 UTC

**Comment by iw0der** [comment] 2016-02-10 23:11
Yes, 
dear @davidalger  I know exactly what is a \n; I also solved with OOo, I found the right options! Essentially prefer to put \t on a file rather than count and not see difference between space or tab, that's all.

I will not be the only one who has had some problems in dealing with these Magento files; clear, once we figured how they are made, there is a solution and perhaps we can use to tray to produce a translation that still missing.

There is always a first time ;-) Thanks you all  for your kind attention.

73s,
A.
