### ISSUE TITLE
Cannot Fetch Payflow Pro transaction account with multiple business accounts associated with multiple stores

### ISSUE THREAD

**Issue by 0xMatt** [magento/magento2#34725] opened 2021-11-27 17:55 UTC
### Preconditions (*)

1. 2.4.3-p1
2. CentOS 8
3. PHP 7.4.26 

### Steps to reproduce (*)

1. Setup Secondary Website
2. Setup PayflowPro credentials for Primary Website
3. Setup PayflowPro credentials for Secondary Website
4. Create order in secondary website, which uses the config scope for that website

### Expected result (*)

1. Place order on secondary website which uses configurations for the scope of that secondary website
2. Fetch transaction details from PayPal via the Transaction ID.
3. Get results from transaction ID from paypal

### Actual result (*)

1. Go to transactions for secondary website, fetch transaction info, get error 'Account ID Invalid - Due to it not pulling scope for the website configurations

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by 0xMatt** [comment] 2021-11-27 17:56
I cannot request an instance without first knowing if you guys have two separate PayflowPro account details you can supply in the demo environment for me to properly reproduce this bug. Please advise.

**Comment by engcom-November** [comment] 2021-12-01 14:17
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue.
Steps performed:
Magento Setup multiple Store/website
Admin - Stores - Configuration -  Sales - Payment Methods - Configure - Payflow Pro for all store views scope
Reindex and clear cache
Front-end - Second Webiste - Create / Place Order
User is able to retrieve Order info from both admin and Frontend My Account - My Orders pages - No issue.
@0xMatt kindly recheck the issue on Magento 2.4-develop branch and elaborate steps to reproduce if you are still facing the issue.
Thank you

**Comment by engcom-November** [comment] 2021-12-16 13:01
Hi @0xMatt ,

We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-12-16 13:01 UTC
Labels: Issue: needs update
