### ISSUE TITLE
setup:db:status cli doesn't track queue consumer changes

### ISSUE THREAD

**Issue by Vigneshmuthusamy** [magento/magento2#37473] opened 2023-05-08 16:39 UTC
### Preconditions and environment

- Magento version -  Old and latest versions till 2.4.6
- Occurs in both commerce and open source editions
- We need to have message queue configured to test it

### Steps to reproduce

- Setup message queues and add new topics/queues via any existing custom module
- run `bin/magento setup:db:status` command to check for db schema changes
- It'll output `All modules are up to date.` even though we have new DB changes to the queue table 

### Expected result

Whenever we run `bin/magento setup:db:status` command to check for DB schema changes, it'll output if we should run `setup:upgrade` for the DB schema changes to reflect.

Since we have new queue created and DB changes waiting to be updated which should show the correct status on status cli.

### Actual result

It's showing  `All modules are up to date.` even though we have new DB changes to the queue table 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2023-05-16 06:11
Hi @Vigneshmuthusamy ,
Thank you for reporting and collaboration. Verified the behavior on Magento 2.4-develop instance and is reproducible. But however this seems to be expected behavior but not a bug. On setting up the message queues as per [docs](https://devdocs.magento.com/guides/v2.3/config-guide/mq/manage-message-queues.html) / Configure the consumers behavior or creating the deployment configuration using `bin/magento setup:config:set` command as per [docs](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/tutorials/deployment.html?lang=en) does not require `setup:upgrade` operation from CLI to update the modules as the values being set are updated without the need of `setup:upgrade`. Kindly refer the [docs](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/tutorials/database-status.html?lang=en) and provide your inputs on this.
Thank you.

**Comment by Vigneshmuthusamy** [comment] 2023-05-23 13:48
ok. But even the config values tracked in config.php that was dumped using app:conf:dump also didn't output correct status on any updates. Only the changes in module node shows we need to run the setup:upgrade. Is that also expected behavior?

**Comment by engcom-November** [comment] 2023-06-13 05:28
Thank you for the response @Vigneshmuthusamy . As per Magento [devdocs](https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/cli/configuration-management/export-configuration.html?lang=en), after we configure settings in the Magento Admin, we export those settings to configuration files using command: app:config:dump and this does not require setup:upgrade operation to update the configuration files or on the UI and is an expected behavior. Kindly refer the docs and let us know if you face any issues.
Thank you.

**Comment by engcom-Bravo** [comment] 2023-07-03 05:30
Hi @Vigneshmuthusamy,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-07-03 05:30 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.6
