### ISSUE TITLE
GraphQl context, extension attribute isCustomer returns true for Admin and Integration tokens

### ISSUE THREAD

**Issue by pmarjan** [magento/magento2#29893] opened 2020-09-03 15:25 UTC
### Preconditions (*)

1. Have a token generated for admin user
2. Have a token generated for integration

### Steps to reproduce (*)

1. get the `$context` object that is passed into any GraphQl resolver
2. execute `$context->getExtensionAttributes()->getIsCustomer()` when the request uses the admin token, or the integration token

### Expected result (*)

1. `$context->getExtensionAttributes()->getIsCustomer()` will return `true`
2.

### Actual result (*)

1. `$context->getExtensionAttributes()->getIsCustomer()` should return `false`
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2022-11-16 16:42
Hello @pmarjan,

Thanks for the report and collaboration!

As per this comment https://github.com/magento/magento2/pull/29894#issuecomment-909118997 in its related PR, the issue is already been fixed. Hence closing this issue.

Let us know in case you are still facing the issue.

Thanks

**Closed as completed by engcom-Hotel** 2022-11-16 16:42 UTC
Labels: Issue: Format is valid, Triage: Dev.Experience, Priority: P2, Project: GraphQL, PAP, Progress: done
