### ISSUE TITLE
Web Setup Wizard Not open Any one help me??

### ISSUE THREAD

**Issue by mitulispace** [magento/magento2#6969] opened 2016-10-12 13:00 UTC
### Steps to reproduce

1.  I go System -> Web Setup Wizard
### Expected result

1. Web Setup Wizard Perfect Open
### Actual result

1. Web Setup Wizard not Open (Many time try )
   ![error](https://cloud.githubusercontent.com/assets/16436069/19310872/d4039868-90a9-11e6-8962-9c3952a39c9b.PNG)

**Comment by pboisvert** [comment] 2016-10-12 14:09
@mitulispace can you provide your system information such as OS, PHP version, etc..

**Comment by mitulispace** [comment] 2016-10-13 06:29
pliz check It 
![version](https://cloud.githubusercontent.com/assets/16436069/19338707/5a0a0c02-913c-11e6-917f-01b245a1e74d.PNG)

@veloraven @pboisvert

**Comment by veloraven** [comment] 2016-10-25 13:07
@mitulispace please identify which version of Magento you are running.
This issue seems to be a duplicate of #4687

**Comment by mitulispace** [comment] 2016-10-26 04:03
Magento ver. 2.1.1  But This issue Solved
Step follow  
Note : Your Website path Will be put Ex. php abc.com/bin/magento 
Step1 Run following command php bin/magento setup:static-content:deploy
Step2 Run  php bin/magento setup:upgrade
Step3 Run  php bin/magento setup:di:compile
Step4 Run  php bin/magento cache:clean

**Closed as completed** 2016-10-26 04:34 UTC
Labels: Progress: needs update, Component: Setup
