### ISSUE TITLE
Cron generates the same jobs in the same time

### ISSUE THREAD

**Issue by atsareva** [magento/magento2#12602] opened 2017-12-08 17:22 UTC
Hi guys,

Recently we upgraded magento with 2.2.0 version and faced with a strange issue for generating cron jobs.

### Preconditions
1. Magento 2.2.0 / 2.2.1
2. Ubuntu 16.04 lts
3. PHP 7.0.22
4. mysql  Ver 14.14 Distrib 5.7.20
5. apache

### Steps to reproduce
1. I was only observing cron_schedule table about one hour.

### Expected result
1. cron_schedule shouldn't contain repeated jobs in the same time
 
### Actual result
But actually it contains wrong job's schedule, therefore some jobs will be run more often. 
![cron_fiege](https://user-images.githubusercontent.com/1243876/33777176-794034b4-dc4c-11e7-9926-5673c8d02e85.png)
or
![cron_newrelic](https://user-images.githubusercontent.com/1243876/33777191-83f1de9e-dc4c-11e7-8314-4dc3fb01e733.png)

**More serious problems can occurs due to repeated cron jobs. E.g we have import job which should be run each 15minutes, but sometimes it's run twice a minute. Therefore reindex process is working all time and we have a lot of deadlock issues.** 

Thanks,
Alena Tsareva

**Comment by magento-engcom-team** [comment] 2017-12-11 09:52
@atsareva Thank you for your report! This issue is already addressed in internal ticket MAGETWO-83782 We are closing this issue as a duplicate of https://github.com/magento/magento2/issues/11002

**Comment by tomasvinduska** [comment] 2018-02-07 13:02
This is not duplicit its separate problem when cron create duplicit records on shedule time.

**Comment by vlauria** [comment] 2018-03-06 09:09
on magento 2.2.2 i have same problem. This is not duplicate. It's another problem, cron run schedule more job at times.

**Comment by ccasciotti** [comment] 2018-03-06 11:43
I agree with @tomasvinduska and @vlauria, I'm facing the same issue using Magento 2.2.2. The cron schedules job at the same time more than once for the same schedule time.

![cron](https://user-images.githubusercontent.com/4273323/37030602-d2c67c6c-213b-11e8-818f-717ca8feaf9e.png)

I'll reopen issue.

**Comment by developer-vtnetzwelt** [comment] 2018-03-22 12:36
I am facing the same issue. Can we know why it is labelled as non-issue?

**Comment by harrigo** [comment] 2018-04-05 10:29
Yeah this is a really frustrating issue for me also and it causing some crons to fail and get stuck in a running state. These then stack leading to issues like here: https://github.com/magento/magento2/issues/11002

This also seems similar to https://github.com/magento/magento2/issues/10279 however this is supposed to be a duplicate of this (however different and may be the cause of the following rather) https://github.com/magento/magento2/issues/10650 and seems like its fixed in 2.2.5 so hopefully that clears up all our issues.

For now however i have created a little script that seems to be working for me and just run via cron (i know its just a plaster on a problem and doesn't fix but easy and better than nothing if its causing you issues like mine). This basically just groups all job_codes and loops through creating an array of scheduled times for that code. If the job_code already has a job set for that time it is deleted from the schedule so that these duplicates are removed. It takes about a seconds to run so i just run it every min:

```
<?php 
require '/home/sites/magento/public_html/app/bootstrap.php'; 
$bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $_SERVER); 
$objectManager = $bootstrap->getObjectManager(); 
$resource = $objectManager->get('Magento\Framework\App\ResourceConnection'); 
$connection = $resource->getConnection(); 
$sql = 'SELECT job_code FROM cron_schedule GROUP BY job_code;'; 
$collection = $connection->query($sql); 

foreach ($collection as $job):
	$sql = 'SELECT scheduled_id, scheduled_at FROM cron_schedule WHERE job_code = "' . $job["job_code"] . '";';
	$jobcollection = $connection->query($sql);
	$jobarray = array();
	foreach ($jobcollection as $jobinstance):
		if(in_array($jobinstance['scheduled_at'], array_column($jobarray, 'scheduled_at'))) {
			$sql = 'DELETE FROM cron_schedule WHERE schedule_id = ' . $jobinstance['schedule_id'] . ';";'
			$connection->query($sql);
		} else {
			array_push($jobarray, array(
					"schedule_id" => $jobinstance['schedule_id'],
					"scheduled_at" => $jobinstance['scheduled_at'],
				));
		}
	endforeach;
endforeach;
?>
```

**Comment by bpoiss** [comment] 2018-05-04 06:30
Is there any fix/workaround?

**Comment by bpoiss** [comment] 2018-05-04 07:07
I fixed this with overriding vendor/magento/module-cron/Model/Schedule.php tryLockJob method with:

```
public function tryLockJob($oldStatus = self::STATUS_PENDING)
{
    if ( $this->_getResource()->trySetJobStatusAtomic($this->getId(), self::STATUS_RUNNING, $oldStatus)) {
        $this->setStatus(self::STATUS_RUNNING);
        return true;
    }
    return false;
}
```

**Comment by MrDaar** [comment] 2018-05-18 12:08
I've experienced similar issues...

**Comment by rauberdaniel** [comment] 2018-05-30 13:44
This is a major issue here as well, since it seems that `sales_send_order_emails` jobs are queued multiple times at the same time which causes order emails to be sent multiple times. I wonder if it could be simply "fixed" (workaround) by adding a `UNIQUE` constraint to the `job_code` and `scheduled_at` columns, but I assume that might break the whole scheduling stuff.

**Comment by rauberdaniel** [comment] 2018-06-01 07:00
I created a mysql query that takes care of the duplicate jobs and removes them. Simply run this as a cron job every minute and you should be fine:

```bash
mysql -u $DBUSER -p$DBPASSWORD -h $DBHOST $DBDATABASE -e "DELETE FROM cron_schedule WHERE schedule_id IN (SELECT schedule_id FROM (SELECT MAX(schedule_id) as schedule_id, job_code, scheduled_at, COUNT(*) as num FROM cron_schedule WHERE status = \"pending\" GROUP BY job_code, scheduled_at) as a WHERE num > 1 ORDER BY scheduled_at DESC);"
```

(please note you have to replace the variables with your real credentials and Database Information.)

**Comment by marcinfr** [comment] 2018-06-27 09:14
Hi,
Issue is because some of cron schedule groups are running as separate process, each of this process execute method to generate schedules for all of groups, so each job schedule is created few times. 

I have found 2 solutions:

1. in cofiguration (stores->configuration->advanced->system->cron) set "Use Separate Process" to NO for all of cron groups.

2. in code, i have found that there is already fix for this issue: https://github.com/magento/magento2/commit/fcda71dd9a38f2ae2dda95dc1877b0634ea108d4
, its merged into 2.2-develop, but its not merged into 2.3 and 2.4.

**Comment by crtl** [comment] 2018-08-02 12:43
I am having the same issue in Magento 2.2.4 CE.
Some cronjobs are scheduled 20 times.

**Comment by engcom-backlog-nickolas** [comment] 2018-08-07 12:28
Hello @atsareva, thank you for your report. The fix will be available with the upcoming 2.2.7 release.

**Closed as completed by engcom-backlog-nickolas** 2018-08-07 12:28 UTC
Labels: Component: Cron, Issue: Clear Description, Issue: Confirmed, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by hostep** [comment] 2018-08-07 19:07
@engcom-backlog-nickolas: any reference to a commit or PR for the fix in 2.2.7 you are referring to would be appreciated!

I was under the impression all big cron related issues got fixed in 2.2.5, but according to your comment, that's still not true?

**Comment by engcom-backlog-nickolas** [comment] 2018-08-08 06:12
@hostep, https://github.com/magento/magento2/pull/12497

**Comment by hostep** [comment] 2018-08-08 06:55
@engcom-backlog-nickolas: correct me if I'm wrong but #12497 got included in Magento 2.2.5, see: https://github.com/magento/magento2/commit/f274f03a45f0fa230efd5c1b6ee8e37b03530e2e

**Comment by Ctucker9233** [comment] 2018-11-05 21:39
@engcom-backlog-nickolas What @hostep said is correct. If it is fixed, then why are we still seeing cron jobs created one on top of the other resulting in a server deadlock? Every few days I have to truncate the cron db table to keep everything running smoothly. If I don't, I get multiple notifications like this:

 [Magento\Framework\DB\Adapter\DeadlockException]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction, query was: DELETE FROM `mgit_cron_schedule` WHERE (status = 'missed') AND (job_code in ('ddg_automation_customer_subscriber_guest_sync', 'ddg_automation_importer', 'ddg_automation_status', 'ddg_automation_abandonedcarts', 'ddg_automation_reviews_and_wishlist', 'ddg_automation_campaign', 'ddg_automation_order_sync', 'ddg_automation_cleaner', 'ddg_automation_catalog_sync', 'ddg_automation_email_templates')) AND (created_at < '2018-11-05 01:59:03')  

Please provide the commit that fixes this issue and will be included in 2.2.7.

**Comment by tim-reynolds-visionet** [comment] 2018-12-19 14:46
Is there confirmation from anyone that this was fixed in 2.2.7? We are affected by this presently and would very much like to have it stop.

**Comment by hostep** [comment] 2018-12-19 16:19
@tim-reynolds-visionet : most big cron related issues should have been fixed in 2.2.5, if you still run against such issues in 2.2.5 or 2.2.6 or 2.2.7, can you open a new issue describing what you are experiencing? Thanks! :)

**Comment by blickcreative** [comment] 2019-06-17 03:55
I am having the exact same issue after updated Magento to 2.2.8
Is there a patch or fix available?

**Comment by rizwan-i-khan** [comment] 2019-11-07 12:56
@crtl
I am facing the same issue, any solutions for this?

**Comment by KLeval** [comment] 2019-12-05 13:26
Same here, our task that send the ordered products to logistic service scheduled at 3:00AM  is sometime sent 3 times ... We had to deport the task on linux crontab for the moment !

**Comment by rizwan-i-khan** [comment] 2019-12-05 13:28
@KLeval 
https://magento.stackexchange.com/questions/294926/magento-2-duplicate-cron-jobs-in-cron-schedule-table
maybe this workaround can solve your issue.
