### ISSUE TITLE
Hamburger Icon was available on a page where menu was not present. Issue in responsive view

### ISSUE THREAD

**Issue by ghoshsweta** [magento/magento2#20210] opened 2019-01-11 10:19 UTC
### Preconditions (*)

1.Magento version 2.3.0
2.php version 7.2

### Steps to reproduce (*)

1)Login to Customer Panel
2)Place Order for any product
3)Create invoice and shipment for this order from the backend
4)Repeat step 1
5)Open the browser in mobile responsive
6)Go to my account->my order->view the same order or any other order with the status "complete"
7)Click on Order Shipment subtab
8)Click on Print All Shipments
9)Cancel the option to print the Shipment form
10)Check the page so received

### Expected result (*)

1. Hamburger icon should not be there when viewing in responsive view as there is no menu on that page

### Actual result (*)

1. Hamburger icon is available on the page

![ixndex](https://user-images.githubusercontent.com/25763126/51027926-232f9f00-15b8-11e9-9e0e-9d5514edf66e.png)

**Comment by magento-engcom-team** [comment] 2019-01-11 10:19
Hi @swetacedcoss. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@swetacedcoss do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-11 10:19
Hi @GovindaSharma. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-01-11 10:20
@GovindaSharma Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97573`, `MAGETWO-97574` were created

**Comment by magento-engcom-team** [comment] 2019-01-11 10:43
Hi @amol2jcommerce. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-01-16 22:05
Hi @swetacedcoss. Thank you for your report. 
The issue has been fixed in magento/magento2#20219 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [8ddc45b97fb87c7e65cf3ed5f1146568fb437ccf](https://github.com/magento/magento2/commit/8ddc45b97fb87c7e65cf3ed5f1146568fb437ccf)

The fix will be available with the upcoming 2.2.8 release.

**Closed as completed by magento-engcom-team** 2019-01-16 22:05 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by magento-engcom-team** [comment] 2019-01-19 06:55
Hi @swetacedcoss. Thank you for your report. 
The issue has been fixed in magento/magento2#20214 by @amol2jcommerce in 2.3-develop branch
Related commit(s):
 - [a0bfa97e97e09ba7d1d25b5bec28d276cfb3aa18](https://github.com/magento/magento2/commit/a0bfa97e97e09ba7d1d25b5bec28d276cfb3aa18)
 - [bbe41a20060aa878a65f30bd53c09cc3f784ec08](https://github.com/magento/magento2/commit/bbe41a20060aa878a65f30bd53c09cc3f784ec08)

The fix will be available with the upcoming 2.3.1 release.
