### ISSUE TITLE
Magento 2.3.4 array print while setup upgrade

### ISSUE THREAD

**Issue by RHapani** [magento/magento2#27091] opened 2020-02-29 10:11 UTC
### Preconditions (*)

1. Install Magento 2.3.4 from GitHub.
2. After Install Magento, Execute command php bin/magento s:up

### Steps to reproduce (*)

1.Install Magento 2.3.4 from GitHub.
2.After Install Magento, Execute command php bin/magento s:up

### Expected result (*)

1. Setup Upgrade sucessfully without print array.

### Actual result (*)

1. Print array when setup upgrade.
![image](https://user-images.githubusercontent.com/56859210/75605556-e4d1a800-5b09-11ea-8d4d-676b5f0babe6.png)

**Comment by lurajcevi** [comment] 2020-04-03 11:01
This is reproducible on 2.4-develop branch.

Looking into the implementation, printed array information comes from `\Magento\Setup\Model\Installer::installDataFixtures`

        $this->log->log('Data install/update:');
        $this->log->log('Disabling caches:');
        $this->updateCaches(false, $frontendCaches);
        $this->handleDBSchemaData($setup, 'data', $request);
        $this->log->log('Enabling caches:');
        $this->updateCaches(true, $frontendCaches);

with `updateCaches` doing the printing.

	private function updateCaches($isEnabled, $types = [])
    {
        /** @var \Magento\Framework\App\Cache\Manager $cacheManager */
        $cacheManager = $this->objectManagerProvider->get()->create(\Magento\Framework\App\Cache\Manager::class);

        $availableTypes = $cacheManager->getAvailableTypes();
        $types = empty($types) ? $availableTypes : array_intersect($availableTypes, $types);
        $enabledTypes = $cacheManager->setEnabled($types, $isEnabled);
        if ($isEnabled) {
            $cacheManager->clean($enabledTypes);
        }

        // Only get statuses of specific cache types
        $cacheStatus = array_filter(
            $cacheManager->getStatus(),
            function (string $key) use ($types) {
                return in_array($key, $types);
            },
            ARRAY_FILTER_USE_KEY
        );

        $this->log->log('Current status:');
        // phpcs:ignore Magento2.Functions.DiscouragedFunction
        $this->log->log(print_r($cacheStatus, true));
    }

This seems to be introduced as part of MC-30236
	https://github.com/magento/magento2/commit/96a2e17754c78e3939fcbe14f7729d7ded52e544 (conditionally print out array data)

and reworked in this commit: https://github.com/magento/magento2/commit/25886c2d3dd819a65db4a92a888db0d767c53b3b to print data always.

Now, I'm not sure whether this is necessary - but it doesn't seem like it is.

**Comment by magento-engcom-team** [comment] 2020-04-06 05:36
@sudheers-kensium Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2020-04-06 06:08
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33096` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2020-06-24 09:30
Hi @RHapani. Thank you for your report. 
The issue has been fixed in magento/magento2#27567 by @srsathish92 in 2.4-develop branch
Related commit(s):
 - [d95a65adde03f8a573b0b1dd15d0c5a247d8d99d](https://github.com/magento/magento2/commit/d95a65adde03f8a573b0b1dd15d0c5a247d8d99d)
 - [981df7bdc533a1209253976b2677b8af03f2df08](https://github.com/magento/magento2/commit/981df7bdc533a1209253976b2677b8af03f2df08)
 - [16ebd28965b8bda3ed32a40ea841867159cbcbfa](https://github.com/magento/magento2/commit/16ebd28965b8bda3ed32a40ea841867159cbcbfa)
 - [a044c531ed9c9dc54cfc73630bbaf0ae003b7995](https://github.com/magento/magento2/commit/a044c531ed9c9dc54cfc73630bbaf0ae003b7995)
 - [075f997093284c1fd1f94c0cef3c4f7b199591db](https://github.com/magento/magento2/commit/075f997093284c1fd1f94c0cef3c4f7b199591db)
 - [479166ef9ae0ba50c813c3f502372b05299a0c84](https://github.com/magento/magento2/commit/479166ef9ae0ba50c813c3f502372b05299a0c84)

The fix will be available with the upcoming 2.4.1 release.

**Closed as completed by magento-engcom-team** 2020-06-24 09:30 UTC
Labels: Issue: Ready for Work, Component: Setup, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Cleanup, Reproduced on 2.4.x, Fixed in 2.4.x, Severity: S3, Triage: Done, Reported on 2.3.4
