### ISSUE TITLE
Depending on frontend language prices are reformated to 0 or currency is not shown.

### ISSUE THREAD

**Issue by rarog** [magento/magento2#36343] opened 2022-10-21 07:54 UTC
### Preconditions (*)

1. Magento version 2.4.5-p1 via composer with following packages:
```
    "require": {
        "amasty/module-shipping-suite": "^1.0",
        "firegento/magesetup2": "^1.0",
        "magento/composer-root-update-plugin": "~2.0",
        "magento/data-migration-tool": "2.4.5",
        "magento/product-community-edition": "2.4.5p1",
        "mageplaza/module-smtp": "^4.3.0",
        "splendidinternet/mage2-locale-de-de": "^1.55"
    },
    "require-dev": {
        "allure-framework/allure-phpunit": "~1.2.0",
        "friendsofphp/php-cs-fixer": "^3",
        "lusitanian/oauth": "~0.8.10",
        "magento/magento-coding-standard": "*",
        "pdepend/pdepend": "~2.7.1",
        "phpmd/phpmd": "^2|^3",
        "phpunit/phpunit": "^9",
        "sebastian/phpcpd": "^6",
        "squizlabs/php_codesniffer": "~3.5.4"
    },
```

### Steps to reproduce (*)

Set frontend language to de_de and open any product.
With frontend language set to de_de the prices are reset/reformated fo 0,00 € after a second after loading. First it appears as "3,90 €", then it's changed to "0,00 €"
With frontend language set to en_us the prices are correct, but no currency symbol is shown. First it appears as "€ 3.90", then it's changed to "3.90"

### Expected result (*)

1. Normal price and currency symbol showing in any language set up.

### Actual result (*)

1. Screenshot of result with de_de:
<img width="400" alt="de_de" src="https://user-images.githubusercontent.com/2520875/197143159-69caf6b8-cb93-44cb-8a76-8263bba8ebee.png">
2. Screenshot of result with en_us:
<img width="371" alt="en_us" src="https://user-images.githubusercontent.com/2520875/197143190-0282e868-f2cf-4855-a5d8-b4d4bd46dec6.png">

**Comment by rarog** [comment] 2022-10-21 12:17
I now know, why the price is shown as "0,00 €" but don't know yet, how this conditions happens.

For en_US I get this price format:
`        "[data-role=priceBox][data-price-box=product-id-24092]": {
            "priceBox": {
                "priceConfig":  {"productId":"24092","priceFormat":{"pattern":"%s","precision":2,"requiredPrecision":2,"decimalSymbol":".","groupSymbol":",","groupLength":3,"integerRequired":false},"tierPrices":[]}            }
        }

for de_DE this:
        "[data-role=priceBox][data-price-box=product-id-24092]": {
            "priceBox": {
                "priceConfig":  {"productId":"24092","priceFormat":{"pattern":"0,00\u00a0\u20ac","precision":2,"requiredPrecision":2,"decimalSymbol":",","groupSymbol":".","groupLength":3,"integerRequired":false},"tierPrices":[]}            }
        }`

So obviously with the German setting later in price-utils.js the function formatPriceLocale doesn't have anything to replace the price it gets, if priceFormat would be like "%s\u00a0\u20ac" I would get correct prices for de_DE, obviously similar happens to en_US, where the pattern just gets the price and doesn't have the currency in it.

**Comment by rarog** [comment] 2022-10-21 12:52
My suspicion is that it happens as early as in `app/code/Magento/Directory/Model/Currency.php` somewhere here: https://github.com/magento/magento2/blob/e0d650c78dc6791460089ed43e88b27b31d6ecca/app/code/Magento/Directory/Model/Currency.php#L503

**Comment by rarog** [comment] 2022-10-21 13:02
@magento give me 2.4.5-p1 instance

**Comment by engcom-November** [comment] 2022-10-21 13:15
Hi @rarog ,
Thank you for reporting and collaboration. This issue is not reproducible on Magento 2.4-develop instance with german or french language packs installed. As per the pre conditions mentioned by you, composer.json file has 3rd party extensions / modules: "amasty/module-shipping-suite": "^1.0", "firegento/magesetup2": "^1.0" etc enabled. Can you please check if the issue caused due to any 3rd party modules enabled as community cannot able to provide fix for such issues in this https://github.com/magento/magento2 git repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page. If yes, kindly recheck on the clean latest Magento instance and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by rarog** [comment] 2022-10-21 16:32
@engcom-November I think it is a specific bug. Either a general one in php version on the server or in the flavour of the distribution.

I tested the following code on my server running on PHP 8.1.11:
```php<?php
$price = sprintf("%F", 0);
$numberFormatter = new \NumberFormatter('de_DE', \NumberFormatter::CURRENCY);
$numberFormatter->setSymbol(\NumberFormatter::CURRENCY_SYMBOL, '');
echo $numberFormatter->formatCurrency(
    $price,
    'EUR'
);`
The output is `0,00 €` instead of expected `0,00 `, which leads to my bug as followup code would produce $number value `0,00€` inside `public function getOutputFormat()` and would lead to returning of `0,00 €` instead of `%s €`.

The same behaviour with same PHP version can be reproduced here: https://onlinephp.io/c/24853

**Comment by rarog** [comment] 2022-10-21 17:24
Obviously the logic inside https://github.com/magento/magento2/blob/e0d650c78dc6791460089ed43e88b27b31d6ecca/app/code/Magento/Directory/Model/Currency.php#L479 can't work the intended way.

Are there tests for this function?

The comments inside https://www.php.net/manual/de/numberformatter.setsymbol.php says similar thing.

I submitted a pull request that shows the changes that made the prices work correctly for me.

**Comment by royalkaroma** [comment] 2022-10-22 12:20
hi i have the same problem ones curency change look 0.00 in product page
i work with 2.4.5 magento 8.1 php

**Comment by royalkaroma** [comment] 2022-10-23 16:19
bonjour j attrouper la solution j ai changer la ligne 442 
app/code/Magento/Directory/Model/Currency.php
$formattedCurrency = preg_replace(['/[^0-9.,۰٫]+/', '/ /'], '', $formattedCurrency);
source [glo81187]

**Comment by engcom-November** [comment] 2022-10-25 13:51
Verified the issue again on clean Magento 2.4.5-p1 composer installation with no 3rd party extensions / modules enabled but unable to reproduce the issue. 
Steps performed:
1. Installed 2.4.5-p1 project-community-edition
2. Setup Currency options - Euro from admin and save
3. Clear cache
4. Created Simple and configurable products
5. Installed German Language pack
6. Open Front end - Product details page
No issue: Price displayed as expected and user able to place order
Changed currency to US Dollar from Admin and save
Clear cache
Open Front end - Product details page
No issue: Price displayed as expected
![image](https://user-images.githubusercontent.com/60198231/197791556-4bcc902a-025a-42bb-90fa-d5b590861c6c.png)
![image](https://user-images.githubusercontent.com/60198231/197791607-4c49c514-abb4-4fcf-b7a2-0253d42a7222.png)
![image](https://user-images.githubusercontent.com/60198231/197791646-1f5486c6-b659-44ab-8b85-6cc106f549df.png)
![image](https://user-images.githubusercontent.com/60198231/197791687-63eb5e16-2c1d-48af-b485-b9519cb1ee9d.png)
Kindly provide missing steps / configuration details if any.
Thank you.

**Comment by rarog** [comment] 2022-10-25 15:24
@engcom-November Is on the frontend this kind of code produced on the product page?

`<script type="text/x-magento-init">
    {
        "[data-role=priceBox][data-price-box=product-id-1234]": {
            "priceBox": {
                "priceConfig":  {"productId":"1234","priceFormat":{"pattern":"%s\u00a0\u20ac","precision":2,"requiredPrecision":2,"decimalSymbol":",","groupSymbol":".","groupLength":3,"integerRequired":false},"tierPrices":[]}            }
        }
    }
</script>`

Does it have the correct pattern "%s\u00a0\u20ac" when set to Euro? Is this code run and interpreted in the frontend after loading the page (probably by price-box.js)?

**Comment by rarog** [comment] 2022-10-25 16:28
@engcom-November Okay, it's harder to reproduce or needs different server setup. I tested on 2 machines and on one I get the bug and on another I don't. Looks like NumberFormatter::formatCurrency on which Magento 2 relies is just not reliable and behaves differently depending on underlying ICU library.

On the machine where it works I have Ubuntu 22.10 with php 8.1 and according to phpinfo it's this:
`ICU version => 70.1
ICU Data version => 70.1
ICU Unicode version => 14.0`

On the machine where it doesn't work, I have CentOS7 with php 8.1 provided by Plesk and following ICU:
`ICU version => 50.2
ICU Data version => 50.2
ICU Unicode version => 6.2`

So depending on this setSymbol and formatCurrency will or will not produce the price with or without the currency symbol and the code works correctly or it doesn't. (e.g. this tells similar behaviour: https://github.com/php/php-src/issues/9034)

So this is either depending on system or compilation process of PHP and is unreliable.

**Comment by royalkaroma** [comment] 2022-10-26 14:34
Thanks a lot for your precious information but I don’t now where I put the script that you send it to me

 



Responsable technique

Azzabi Lassad

Mob : +41(0)79 229 87 47 

Tel   : +41(0)22 321 76 12 

Mail :   ***@***.***> ***@***.***

Rue de la Coulouvrenière 27 CH 1204 Genéve

 

 

De : Andrej Sinicyn ***@***.***> 
Envoyé : mardi, 25 octobre 2022 17:25
À : magento/magento2 ***@***.***>
Cc : Azzabi Lassad ***@***.***>; Comment ***@***.***>
Objet : Re: [magento/magento2] Depending on frontend language prices are reformated to 0 or currency is not shown. (Issue #36343)

 

@engcom-November <https://github.com/engcom-November>  Is on the frontend this kind of code produced on the product page?

<script type="text/x-magento-init"> { "[data-role=priceBox][data-price-box=product-id-1234]": { "priceBox": { "priceConfig": {"productId":"1234","priceFormat":{"pattern":"%s\u00a0\u20ac","precision":2,"requiredPrecision":2,"decimalSymbol":",","groupSymbol":".","groupLength":3,"integerRequired":false},"tierPrices":[]} } } } </script>

Does it have the correct pattern "%s\u00a0\u20ac" when set to Euro? Is this code run and interpreted in the frontend after loading the page (probably by price-box.js)?

**Comment by royalkaroma** [comment] 2022-10-26 15:09
But it looks good for me now with chf and euro work well I have only problem with expired reset password for client other way every thing is perfect



Responsable technique

Azzabi Lassad

Mob : +41(0)79 229 87 47 

Tel   : +41(0)22 321 76 12 

Mail :   ***@***.***> ***@***.***

Rue de la Coulouvrenière 27 CH 1204 Genéve

 

 

De : Andrej Sinicyn ***@***.***> 
Envoyé : mardi, 25 octobre 2022 18:28
À : magento/magento2 ***@***.***>
Cc : Azzabi Lassad ***@***.***>; Comment ***@***.***>
Objet : Re: [magento/magento2] Depending on frontend language prices are reformated to 0 or currency is not shown. (Issue #36343)

 

@engcom-November <https://github.com/engcom-November>  Okay, it's harder to reproduce or needs different server setup. I tested on 2 machines and on one I get the bug and on another I don't. Looks like NumberFormatter::formatCurrency on which Magento 2 relies is just not reliable and behaves differently depending on underlying ICU library.

On the machine where it works I have Ubuntu 22.10 with php 8.1 and according to phpinfo it's this:
ICU version => 70.1 ICU Data version => 70.1 ICU Unicode version => 14.0

On the machine where it doesn't work, I have CentOS7 with php 8.1 provided by Plesk and following ICU:
ICU version => 50.2 ICU Data version => 50.2 ICU Unicode version => 6.2

So depending on this setSymbol and formatCurrency will or will not produce the price with or without the currency symbol and the code works correctly or it doesn't. (e.g. this tells similar behaviour: php/php-src#9034 <https://github.com/php/php-src/issues/9034> )

So this is either depending on system or compilation process of PHP and is unreliable.

**Comment by engcom-Hotel** [comment] 2022-12-21 10:51
Hello @rarog,

Thanks for the reporting and collaboration!

We have tried to reproduce the issue in the 2.4-develop instance with ICU version 50 but the issue is not reproducible for us. Please refer to the screenshots for reference:

### ICU Version
<img width="442" alt="image" src="https://user-images.githubusercontent.com/51681618/208887971-3b7abe86-ae8f-4748-a4e7-ed5f2a8a68ad.png">

### Product detail page
![image](https://user-images.githubusercontent.com/51681618/208888033-d0497b0e-4f89-4f16-8b0e-1eb91d0ec9e2.png)

### PHP Version
<img width="579" alt="image" src="https://user-images.githubusercontent.com/51681618/208888129-5f09e800-182c-4360-8643-4a51d1b08cad.png">

Please let us know if we have missed anything.

Thanks

**Comment by ljr95** [comment] 2023-01-02 16:33
Hello,
I have exactly the same problem and the server also works with plesk.
Did you find a solution without needing to modify Magento core files?
Thanks in advance,

**Comment by ljr95** [comment] 2023-01-03 13:23
@engcom-Hotel 

We are migrating from 2.4.3 to 2.4.5-p1 and we are facing the same problem.
Locally we use a php-fpm container (debian) and we don't have the problem.
Production and staging use Centos.

Locally in our container we manage to reproduce the error by downgrading the ICU version to 6.2
ICU version => 50.2
ICU Data version => 50.2
ICU TZData version => 2019a
ICU Unicode version => 6.2

This problem should therefore not have the label "Cannot Reproduce".

I remain at your disposal for any further information.

**Comment by engcom-Hotel** [comment] 2023-01-13 10:11
Hello @ljr95,

Thanks for the reply!

We have tried to reproduce the issue via an upgrade from 2.4.3 to 2.4.5-p1 but it seems the issue is not reproducible. Our server configuration is as follows:

OS: Centos 7
ICU Version: 50.2

The issue was reproducible in 2.4.3, please refer to the screenshot below for reference:
![BeforeUpgradeProductDetailPage](https://user-images.githubusercontent.com/51681618/212294365-4eff6ec7-07f3-475a-982e-afab547e8ea0.png)

But After upgrading to 2.4.5-p1 the issue was resolved:
![image](https://user-images.githubusercontent.com/51681618/212294516-1bc6ddda-c1af-4fd6-97f1-272b4d0bb20b.png)

Please let us know if we missed anything.

Thanks

**Comment by ljr95** [comment] 2023-01-13 13:50
Hello,
Thank you for your reply.
A point that I did not specify the store is configured in € and not in $.
Can you please repeat the test in €?
Thanks

**Comment by engcom-Hotel** [comment] 2023-01-19 12:36
Hello @ljr95,

Thanks for the reply!

As I mentioned in my previous https://github.com/magento/magento2/issues/36343#issuecomment-1381602904, the issue was reproducible with $ in the previous version on Magento before updates but after the upgrade, it is not reproducible. 

Thanks

**Comment by engcom-Hotel** [comment] 2023-02-02 02:12
Dear @ljr95,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2023-02-02 02:12 UTC
Labels: Issue:  Cannot Reproduce, Priority: P2, Progress: done, Issue: needs update, Reported on 2.4.5-p1
