### ISSUE TITLE
Type Error occurred when creating object: Magento\Framework\MessageQueue\PublisherPool, Argument 3 passed to Magento\Framework\MessageQueue\PublisherPool::__construct() must be of the type array, null given, called in /var/www/update/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121

### ISSUE THREAD

**Issue by rohit-12284** [magento/magento2#35425] opened 2022-05-05 06:14 UTC
### Preconditions (*)

1. I just updated magento version 2.3.1 to 2.4.3 
2.

### Steps to reproduce (*)

1.While I edit my store configuration and save then this error will comes .And my store configuration is not save
![Screenshot_4](https://user-images.githubusercontent.com/91955751/166871236-2458c10d-9ded-4481-b32b-c40e09791640.png)

2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-05-09 10:58
Hi @7018424048 Thank you for reporting and collaboration. Verified the issue by upgrading from Magento 2.3.1 to 2.43 but could not able to reproduce the issue. User is able to edit and save Store Configuration.
Can you please check if any third party extensions / modules is causing this issue. Also please check [system requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) that are required for specific magento versions before and after upgrade. Kindly elaborate steps to reproduce if you are still facing issues.
![image](https://user-images.githubusercontent.com/60198231/167395955-605bba7d-eed3-4772-9df1-6189568be8a9.png)
Thank you.

**Comment by engcom-November** [comment] 2022-05-23 12:33
Hi @7018424048 ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-05-23 12:33 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
