### ISSUE TITLE
Magento 2 back-office cart is not recollected properly if previously collected with no shipping address

### ISSUE THREAD

**Issue by MeCapron** [magento/magento2#35406] opened 2022-05-02 13:14 UTC
### Summary (*)

Collecting totals before original collectTotals when creating an order in Magento backend will result to a total of zero if there is no shipping address defined and "Same as billing" is checked

### Examples (*)

- Create a preference on the loadHandler after load : 
```php
<?php

declare(strict_types=1);

namespace M2test\FailingQuote\Plugin\Quote\Model\QuoteRepository;

use Magento\Quote\Api\Data\CartInterface;
use Magento\Quote\Model\QuoteRepository\LoadHandler;

class LoadHandlerPlugin
{
    public function afterLoad(LoadHandler $subject, CartInterface $quote): CartInterface
    {
        $quote->collectTotals();

        return $quote;
    }
}
```

```xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\Quote\Model\QuoteRepository\LoadHandler">
        <plugin sortOrder="1" name="zodioCustomerSDKRewardsLoadHandler"
                type="M2test\FailingQuote\Plugin\Quote\Model\QuoteRepository\LoadHandlerPlugin"/>
    </type>
</config>
```

- Add a product in the back-office
- Create an order
- Add the product to the order
- Refresh the price
![image](https://user-images.githubusercontent.com/76486816/166236864-072de904-4329-4421-a05d-326355b0b36a.png)
- Price is at zero

### Proposed solution
**What is hapenning underneath?**
- Click "Update items and quantities"
- The quote is loaded once, setting the `getTotalsCollectedFlag` to true
---
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Controller/Adminhtml/Order/Create.php#L190
- Magento will init the order, going to this code : 
```php
$this->setShippingAsBilling(1);
```
---
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Model/AdminOrder/Create.php#L1480
```php
    public function setShippingAsBilling($flag)
    {
        if ($flag) {
            $tmpAddress = clone $this->getBillingAddress();
            $tmpAddress->unsAddressId()->unsAddressType();
            $data = $tmpAddress->getData();
            $data['save_in_address_book'] = 0;
            // Do not duplicate address (billing address will do saving too)
            $this->getShippingAddress()->addData($data);
        }
        $this->getShippingAddress()->setSameAsBilling($flag);
        $this->setRecollect(true);
        return $this;
    }
```
---
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Model/AdminOrder/Create.php#L464
- The quote is asked to recollect **localy** in the backend AdminOrder/Create model
- Then when saving the quote : 
```php
    public function saveQuote()
    {
        if (!$this->getQuote()->getId()) {
            return $this;
        }

        if ($this->_needCollect) {
            $this->getQuote()->collectTotals();
        }

        $this->quoteRepository->save($this->getQuote());
        return $this;
    }
```
---
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Quote/Model/Quote/TotalsCollector.php#L246
- It will go to the `collectTotals` function and see that the quote is **already** collected. However, Magento replaced the previously calculated shippingAddress by the billingAddress because of the workflow. Resulting totals to zero.
- There is also another problem, when collecting totals for the address, Magento will look to setItems to the shippingAssignment : 
```php
$shippingAssignment->setItems($address->getAllItems());
```
---
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Quote/Model/Quote/Address.php#L642
- Because the shippingAddress was completly replaced by the billing address **without even being reset**, the cache key of items is still linked to the billingAddress : 
```php
        if (!$this->hasData(self::CACHED_ITEMS_ALL)) {
```
- The cache will always be empty as this is based on the billing address that was previously cloned.
---
My suggestion is : 

- When setting the recollect data to the quote in the backend model, flags of the quote must also be reset : 
```php
    public function setRecollect($flag)
    {
        $this->_needCollect = $flag;

       $this->getQuote()->setTotalsCollectedFlag(false);

        return $this;
    }
```

- Also, when the billing address is cloned, the cache key of the shipping address should be cleaned : 
```php
    public function setShippingAsBilling($flag)
    {
        if ($flag) {
            $tmpAddress = clone $this->getBillingAddress();
            $tmpAddress->unsAddressId()->unsAddressType()->unsCachedItemsAll();
            $data = $tmpAddress->getData();
            $data['save_in_address_book'] = 0;
            // Do not duplicate address (billing address will do saving too)
            $this->getShippingAddress()->addData($data);
        }
        $this->getShippingAddress()->setSameAsBilling($flag);
        $this->setRecollect(true);
        return $this;
    }
```

Additional data : this is what the https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Model/AdminOrder/Create.php#L605 is doing here when initializing the order.

---

This is a specific case that could not be handled by Magento 2 before anyone run into this issue and I'm completely ok with this. If you can confirm this issue, I'd be glad to do a Pull Request to resolve this issue.

Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment] 2022-07-21 12:23
Hi @MeCapron,

Thank you for reporting. Verified the issue on Magento 2.4-develop branch but couldn't reproduce the issue.

Steps performed:
1. Created a preference on the loadHandler after load
2. Added a product in the back-office
3. Created an order
4. Added the product to the order
5. Refreshed the price
![Screenshot from 2022-07-21 16-47-46](https://user-images.githubusercontent.com/51681435/180212250-fa4ec017-884a-49ed-9321-664a60c6549d.png)

and the screenshot of result is attached below for reference 

Please provide more information with exact step and screenshot so that we can reproduce it at our end and kindly test on latest 2.4-develop branch also.

Thanks

**Comment by engcom-Echo** [comment] 2022-08-08 09:33
Hello @MeCapron,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Echo** 2022-08-08 09:33 UTC
Labels: Triage: Dev.Experience, Issue: needs update
