### ISSUE TITLE
Something went wrong with processing the default view and we have restored the filter to its original state.

### ISSUE THREAD

**Issue by msheehan21** [magento/magento2#34811] opened 2021-12-14 10:18 UTC
### Preconditions (*)

1. 2.3.4-p2
2.

### Steps to reproduce (*)

1. When entering to **products** in the Catalogue menu, an error message comes up "Something went wrong with processing the default view and we have restored the filter to its original state." I am unable to search or edit products.  I logged in and out and tried other browsers, issue persists.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.
![image](https://user-images.githubusercontent.com/96115239/145979401-44b6c1e4-d440-422d-ab96-c3464d9c4596.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2021-12-17 12:35
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue
Admin - Catalog - Products - Search using Product Name or any other filter applied - No issue. Search working fine.
User is able to navigate to Product Details page.
@msheehan21 FYI.. Sometimes, this error can occur due to version upgrade. Check "catalog_product_entity" table in DB and verify if any Products have NULL as SKU value
Run > SELECT * FROM catalog_product_entity WHERE sku IS NULL to check all product not have sku NULL, then update them.
Another temporary fix is to clear "ui_bookmark table". > TRUNCATE ui_bookmark;
Also make sure to clear cache and add necessary permission/rights.

Kindly recheck the issue on Magento 2.4-develop branch as it has the latest code base and provide missing steps to reproduce if you are still facing the issue.
Thank you.

**Comment by engcom-November** [comment] 2021-12-30 11:47
Hi @msheehan21, 
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-12-30 11:47 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.x

**Comment by magentoprasad** [comment] 2022-07-02 09:20
same issue are showing in Magento 2.4.4

**Comment by cbtrident** [comment] 2022-11-30 20:23
can this case be reopen or do we need to open a new case as this is still happening and it making magento useless to use as people can not check stock
