### ISSUE TITLE
megento 2.1.5 ... unable to upload product image through back end

### ISSUE THREAD

**Issue by osirus211** [magento/magento2#9097] opened 2017-04-02 07:32 UTC
hi i have recently upgraded my magento version to 2.1.5 and  i am unable to upload any product image through the backend

**Comment by korostii** [comment] 2017-04-03 07:56
Hello. If you are looking for an advice please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. 
The GitHub issue tracker is intended for technical issues only.
The issues which cannot be consistently reproduced on a clean installation of Magento 2 CE aren't likely to get resolved in here.
Thus if you are reporting a technical issue, please try add as much information as possible, including the environment you use, 3rd party themes and modules installed, preconditions, steps to reproduce, etc. in order simplify attempts in reproducing it. Screenshots and stack trace from browser console (if any) are also helpful.

**Comment by veloraven** [comment] 2017-06-26 12:33
@osirus211 please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by magento-engcom-team** [comment] 2017-09-11 20:37
@osirus211 we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Closed as completed by magento-engcom-team** 2017-09-11 20:37 UTC
Labels: Progress: needs update, Issue: Format is not valid
