### ISSUE TITLE
Exception on reorder from admin

### ISSUE THREAD

**Issue by likemusic** [magento/magento2#21926] opened 2019-03-25 19:21 UTC
### Preconditions (*)
1. Latest Magento 2.2-develop or 2.3-develop.

### Steps to reproduce (*)
1. Create product with:
  - Minimum Qty Allowed in Shopping Cart: 0.01
  - Qty Uses Decimals: Yes
2. Place from fronent order with Qty: 0.1.
3. Change product with:
  - Minimum Qty Allowed in Shopping Cart: 1
  - Qty Uses Decimals: No
4. From Admin open order and click "Reorder".

### Expected result (*)
1. Page with edit order fom.

### Actual result (*)
1. Exception with message: `Exception #0 (Exception): Warning: Division by zero in /var/www/bateel/vendor/magento/module-tax/Model/Calculation/AbstractAggregateCalculator.php on line 151`

**Comment by magento-engcom-team** [comment] 2019-03-25 19:21
Hi @likemusic. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@likemusic do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [x] no

**Comment by likemusic** [comment] 2019-03-25 19:34
It happens because in [\Magento\CatalogInventory\Model\StockStateProvider::checkQuoteItemQty()#L122](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/CatalogInventory/Model/StockStateProvider.php#L122) decimal qty from orderconverted to int value. For deciamals less then 1 it becomes zero.

Seems that here for decimal qty minimum value should be set to 1 if it is 0 after casting to int.

**Comment by magento-engcom-team** [comment] 2019-03-25 20:17
Hi @dmytro-ch. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-03-25 20:20
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98862` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-04-08 11:36
Hi @likemusic. Thank you for your report. 
The issue has been fixed in magento/magento2#21928 by @likemusic in 2.3-develop branch
Related commit(s):
 - [d073b0c6367c492637ce1aa8f007b5310a72825a](https://github.com/magento/magento2/commit/d073b0c6367c492637ce1aa8f007b5310a72825a)
 - [b82503ae50f324ce9fb5add2b5e21159567b2412](https://github.com/magento/magento2/commit/b82503ae50f324ce9fb5add2b5e21159567b2412)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-04-08 11:36 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: SalesInventory
