### ISSUE TITLE
catalog Product Attribute Media Gallery Management V1Update Put Ignores ID in Route

### ISSUE THREAD

**Issue by Stoyvo** [magento/magento2#27148] opened 2020-03-04 01:45 UTC
### Preconditions (*)
1. Magento 2.3.4

### Steps to reproduce (*)
1. PUT {{baseUrl}}/V1/products/:sku/media/:entryId
2. Use a different ID in the route and the payload

### Expected result (*)
1. ID in the payload shouldn't be an option
2. Or IDs in route and payload do not match

### Actual result (*)
1. :entryId in the route is ignored, however a value is required. Any value can be populated. This leads to false indication of what image is being updated if payload has a different ID.

**Comment by engcom-Oscar** [comment] 2020-09-29 12:58
Hello @Stoyvo 

Thank you for your report.
Unfortunately, I was not able to reproduce this issue on the latest `2.4-develop` code. Probably it was already fixed and will appear in the next release. Or we missed some steps or preconditions.

Could you please recheck it on clean Magento 2.4 installation and confirm?

**Comment by engcom-Alfa** [comment] 2020-12-23 08:53
Hi @Stoyvo. Thank you for your report.
Unfortunately, We are not able to reproduce this issue on the latest 2.4-develop code. Looks like the issue has been already fixed and everything works as expected.

So, we have to close it.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch.
 Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-12-23 08:53 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.3.4
