### ISSUE TITLE
Importing product with SKU that has Unicode character fails

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/magento2#33989] opened 2021-09-03 12:20 UTC
1. Magento 2.x

1. Import product that has sku `30612190-5233-8  16Â½`

### Expected result (*)
1. Product is imported without errors

### Actual result (*)
1. Error
Note: There is no issue when product is created from Admin UI - Catalog - Products page with sku 30612190-5233-8  16Â½. Product created successfully.
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by PascalBrouwers** [comment] 2021-09-03 12:21
Severity above S2 that below S1:
Affects non-critical data or functionality and leaves users without workaround.

**Comment by engcom-Delta** [comment] 2021-09-03 12:52
Hi @PascalBrouwers,

May i close this issue as it is belong to fix issue #33990.

Thanks
Penchal

**Comment by PascalBrouwers** [comment] 2021-09-06 09:13
No, that's the pull request. Why would you close an issue that has a pull request?

**Comment by engcom-November** [comment] 2022-09-06 12:05
Verified the issue on Magento 2.4-develop branch and the issue is reproducible but no invalid error/exception is observed.
Below error is displayed on UI while importing.
Note: There's no issue when the product is created manually with sku 30612190-5233-8 16Â½. Product created successfully.
Hence confirming this issue.
![image](https://user-images.githubusercontent.com/60198231/188630559-a281d75b-18a4-482a-af53-29de2207b342.png)

**Comment by engcom-Bravo** [comment] 2024-09-05 07:17
Hi @PascalBrouwers,

Thanks for your reporting and collaboration.

As per this comment https://github.com/magento/magento2/pull/33990#issuecomment-925638326 issue is not reproducible.we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-09-05 07:17 UTC
Labels: Component: ImportExport, Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done, Reported on 2.4.x, Area: Import / export
