### ISSUE TITLE
massDelete CMS Block not working (error 500)

### ISSUE THREAD

**Issue by nelero** [magento/magento2#10870] opened 2017-09-13 13:55 UTC
Hi,
i'm using the latest stable 2.1.x version.
When i try to mass delete some cms blocks (1 or more checked), i receive an error 500 and blocks are not deleted.

But if i click individually on the block, access the detail page and click delete, the block is deleted as expected.

How can i fix this ?
thanks

**Comment by harshvardhanmalpani** [comment] 2017-09-13 19:34
Duplicate of #8415 and #8418

**Comment by orlangur** [comment] 2017-09-15 11:50
@harshvardhanmalpani yeah, thanks.

Issue seems to be fixed on `develop` but not backported to `2.1.x` yet. Anyone from Community can do it due to https://community.magento.com/t5/Magento-DevBlog/Pull-Requests-for-2-1-x-Patch-Releases/ba-p/65630.

**Closed as completed** 2017-09-20 16:09 UTC
Labels: duplicate, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is not valid
