### ISSUE TITLE
Disallowed File Type for YouTube Videos

### ISSUE THREAD

**Issue by drinkingsouls** [magento/magento2#35702] opened 2022-06-29 12:35 UTC
### Preconditions and environment

- Magento 2.4.3-p2 & Magento 2.4.4
- YouTube API Key correctly set up

### Steps to reproduce

1. Add YouTube Video to product.

### Expected result

Video is added correctly to product listing.

### Actual result

YouTube video fails to add due to "disallowed file type" warning.

<img src="https://i.ibb.co/ry9vpM2/YCnWO.jpg" alt="disallowed file type" title="disallowed file type">

### Additional information

I have correctly setup the YouTube API key but I am presented with the error "disallowed file type" when attempting to add YouTube videos to product listings.
Images & Vimeo videos add correctly but YouTube does not.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-06-30 13:39
Hi @drinkingsouls ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue.
**Steps performed:**
1. Magento Youtube API key setup using https://docs.magento.com/user-guide/catalog/product-video.html
2. Edited a product and expanded images and videos section - uploaded you tube video and saved
No issue: User is able to save video with youtube url.
![image](https://user-images.githubusercontent.com/60198231/176691022-63fa3d66-e6ff-425b-81ea-61678f98b99e.png)
![image](https://user-images.githubusercontent.com/60198231/176691475-d1f6a535-61c1-428b-ac01-e9146be02cd8.png)
Kindly recheck the issue on Magento 2.4-develop branch as its the upcoming 2.4.x release and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by drinkingsouls** [comment] 2022-07-01 22:02
I can confirm that I have phpinfo enabled.
I did not have this issue on previous versions of Magento prior to 2.4.3.

**Comment by engcom-November** [comment] 2022-07-06 09:44
hi @drinkingsouls ,
I verified the issue on Magento 2.4-develop branch with PHP fileinfo enabled but still could not able to reproduce the issue. Kindly recheck the issue on Magento 2.4-develop branch as its the upcoming 2.4.x release and have latest code base and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-07-20 11:16
Hi @drinkingsouls ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-07-20 11:16 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update

**Comment by irfanullah676** [comment] 2023-06-19 16:49
Thanks for sharing this helpful article. Your Internet access speed has an impact on how quickly you can download YouTube videos. Records may pause frequently to filter at slow rates. If you're aware of your slow connection, you can change the video  resolution to continue watching without interruption. Therefore, check your broadcasting speeds or do <a href="https://techiewall.com/how-to-test-youtube-speed/"  >  YouTube speed test  </a>
 history if your connectivity seems to be going more slowly than usual.
