### ISSUE TITLE
GRAPHQL - CategoryInterface breadcrumbs are not correctly sorted

### ISSUE THREAD

**Issue by alexmtch** [magento/magento2#36215] opened 2022-09-29 15:01 UTC
### Preconditions and environment

- Magento version : 2.4.3
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

Run a categoryList query on a specific category (not top level) and retrieve results

### Expected result

Get breadcrumbs sorted

### Actual result

Breadcrumbs are not sorted

### Additional information

`\Magento\CatalogGraphQl\Model\Resolver\Category\DataProvider\Breadcrumbs` :
```
public function getData(string $categoryPath): array
    {
        $breadcrumbsData = [];

        $pathCategoryIds = explode('/', $categoryPath);
        $parentCategoryIds = array_slice($pathCategoryIds, 2, -1);

        if (count($parentCategoryIds)) {
            $collection = $this->collectionFactory->create();
            $collection->addAttributeToSelect(['name', 'url_key', 'url_path']);
            $collection->addAttributeToFilter('entity_id', $parentCategoryIds);
            $collection->addAttributeToFilter(CategoryInterface::KEY_IS_ACTIVE, 1);

            foreach ($collection as $category) {
                $breadcrumbsData[] = [
                    'category_id' => $category->getId(),
                    'category_uid' => $this->uidEncoder->encode((string) $category->getId()),
                    'category_name' => $category->getName(),
                    'category_level' => $category->getLevel(),
                    'category_url_key' => $category->getUrlKey(),
                    'category_url_path' => $category->getUrlPath(),
                ];
            }
        }
        return $breadcrumbsData;
    }
```

You should add `$collection->setOrder('level');` like you done in \Magento\CatalogGraphQl\Model\Resolver\Products\DataProvider\CategoryTree

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-09-30 03:39
Hi @alexmtch ,
Verified the issue on Magento 2.4-develop instance but could not reproduce the issue. Breadcrumbs information is retrieved level wise:
![image](https://user-images.githubusercontent.com/60198231/193184975-3292bc1b-7c8a-468e-a696-a96866670a50.png)
![image](https://user-images.githubusercontent.com/60198231/193185008-db4ad75f-d208-4ae4-97a3-8b7be0c7c733.png)
Kindly check the behavior on Magento 2.4-develop instance and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-10-14 09:21
Hi @alexmtch ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-10-14 09:21 UTC
Labels: Issue: needs update, Reported on 2.4.3
