### ISSUE TITLE
Image roles are not being selected in items created by API after upgrade to 2.3.3. 

### ISSUE THREAD

**Issue by merance2000** [magento/magento2#25763] opened 2019-11-26 17:43 UTC
### Preconditions (*)

1. Upgrade to Magento 2.3.3
2. Create or update products via API
3. Product image roles are deselected and unavailable - yet they show as assigned in exports and in tables. Image roles not showing on front end and also showing as not selected on backend. 

### Steps to reproduce (*)

1.Upgrade to 2.3.3 from 2.3.1 
2. Create or edit products with images via api endpoint connection

### Expected result (*)

1. expect images to automatically be assigned to the base/small/thumbnail roles
2.

### Actual result (*)

1. Images are imported but are assigned no roll
2.
![image of deselected roles](https://user-images.githubusercontent.com/58000536/69658075-821fca80-1049-11ea-8dbc-3574e00a0d68.png)
![image of export image assignments](https://user-images.githubusercontent.com/58000536/69658367-10944c00-104a-11ea-836c-a0748258c64e.png)

**Comment by merance2000** [comment] 2019-11-26 18:05
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment] 2019-11-26 18:05
Hi @merance2000. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-26 18:06
Hi @merance2000, here is your [Magento instance](https://i-25763-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25763-2-3-develop.instances.magento-community.engineering/admin](https://i-25763-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by merance2000** [comment] 2019-11-26 18:37
We will need an endpoint to connect the api sync to. And may need the instance time extended while we build the sync

**Comment by engcom-Charlie** [comment] 2019-11-27 12:22
Hello @merance2000 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the latest 2.3-develop & 2.3.3 branches by provided steps.

**Testing scenario:**
Add images with different types & positions to the product:
![image](https://user-images.githubusercontent.com/51680850/69722354-86b6b280-111f-11ea-9a5a-f5c3d17b1630.png)
![image](https://user-images.githubusercontent.com/51680850/69722393-ab128f00-111f-11ea-9b89-d04683066bed.png)
![image](https://user-images.githubusercontent.com/51680850/69722410-bbc30500-111f-11ea-8a7f-54a13dd13b61.png)

**Result:**
Image roles are assigned to the product
![image](https://user-images.githubusercontent.com/51680850/69722430-c8475d80-111f-11ea-9c50-946496cc30db.png)

So i have to close this issue.
Do you have any updates for it?

**Comment by merance2000** [comment] 2019-12-02 23:33
We are still struggling with this.

 

This from our sync vendor. Do you have any suggestions? We didn’t have the issue until we upgraded to 2.3.3. Please help if you can!!!! 

 


  <https://secure.gravatar.com/avatar/27f7f9611eca76eb137b0e54934b7205?size=40&default=https%3A%2F%2Fassets.zendesk.com%2Fimages%2F2016%2Fdefault-avatar-80.png&r=g> 

Greg Maclean (FarApp) 

Dec 2, 3:03 PM PST 

Hi Merance,

There doesn't appear to be a way we can work around this. It seems no matter what we send M2 always loses the image roles after the image has synced once. I'm betting that when they tested it they didn't try resending the same post again and if they had they likely would have hit the same issue. In any case I think its pretty clearly a Magento 2 issue both in the fact that all was well until you upgraded to 2.3.3 and the fact that you get different results in Magento for new or existing items even though both show no roles. I've tried sending a separate image entry (using the same image) for each type to see if the multiple types is throwing it off but that doesn't seem to be the case either.

This is our posting doc
{"StoreDty": {"all": {"sku": "7340041111390", "status": "1", "media_gallery_entries": [{"disabled": "false", "media_type": "image", "content": {"type": "image/jpeg", "name": "204208.jpg", "base64_encoded_data": <REMOVED>, "types": ["image", "small_image", "thumbnail"]}], "name": "Back on Track Poll Cover with Velcro Straps", "weight": "0.1", "type_id": "simple", "price": "26.95", "attribute_set_id": "4", "visibility": "4", "custom_attributes": [{"attribute_code": "category_ids", "value": [2000, 2009, 1879]}, {"attribute_code": "special_price", "value": "27.0"}, {"attribute_code": "brand", "value": "4942"}, {"attribute_code": "cp_item_no", "value": "204208"}, {"attribute_code": "custom_stock_status", "value": "3869"}, {"attribute_code": "custom_stock_status_qty_based", "value": "1"}, {"attribute_code": "custom_stock_status_qty_rule", "value": "3880"}, {"attribute_code": "description", "value": "Back on Track Poll Cover with velcro straps attaches securely to the top of a bridle or halter to help ease tightness and improve comfort in the sensitive poll area.</P><P>Back on Track products use a special polypropylene fabric impregnated with ceramic powder. The ceramic powder reflects body heat back in the form of FAR infrared rays to improve circulation and help to relax muscles. By placing the pad on the poll, the therapeutic rays are able to relax the muscles of the head and neck as well as padding the crown piece, making it more comfortable. This could lead to better acceptance of the bit and a more relaxed ride. </p><LI>Small pad with velcro straps can be attached to a bridle or halter crown</LI><LI>Ceramic infused fabric reflects body heat back to warm and loosen muscles</LI><P>Not recommended for use on pregnant mares."}, {"attribute_code": "google_exclude", "value": "0"}, {"attribute_code": "mpn", "value": "2062-002"}, {"attribute_code": "primary_vendor", "value": "5909"}, {"attribute_code": "shipping_length", "value": "15"}, {"attribute_code": "shipping_rules", "value": "4900"}, {"attribute_code": "shipping_width", "value": "6"}, {"attribute_code": "special_from_date", "value": "2019-09-07"}, {"attribute_code": "special_to_date", "value": "2019-09-09"}], "extension_attributes": {"stock_item": {"use_config_manage_stock": "1", "backorders": "1", "manage_stock": "1", "qty": 0, "is_in_stock": "1", "use_config_backorders": "0"}}}}, "WebsiteUpdates": []}

If Magento wants us to do something different we would be happy to it's just that we don't know what to do. Sorry I wish I could do something more but we are out of options at this point.

Thanks,
Greg

**Comment by merance2000** [comment] 2019-12-03 00:23
Another note from our sync guys:

 

I tried doing the exact same thing but it didn't retain the roles. The difference is I was sending an image that already existed once before on that product whereas they sent a new image.

When I switched over to your standalone item on the initial sync the roles were retained but on subsequent syncs they were lost with no change in the data we were sending. That is why I wrote that I bet if they were to resend those same posting again they would lost the roles.



 

Have you tested when you resend the same image?

**Comment by engcom-Charlie** [comment] 2019-12-03 11:08
Hello @merance2000 
I tried again on Magento 2.3.3 & 2.3-develop with this body(create product firstly than edit it with image types changing):
```
PUT /rest/V1/products/08130056-DARKNAVY HTTP/1.1
Host: magento2.loc
Content-Type: application/json
Authorization: Bearer itx8i4614iogy9xl8ldfo8rl8ot8byi1
User-Agent: PostmanRuntime/7.19.0
Accept: */*
Cache-Control: no-cache
Postman-Token: 00688769-92aa-43a7-8e9e-ef6a99c93e34,6e75d2f4-69f6-4e99-ab9f-634bbcf3e65b
Host: magento2.loc
Accept-Encoding: gzip, deflate
Content-Length: 10412
Cookie: PHPSESSID=sbhjdjd93e9g30v4mq8gb23gj3
Connection: keep-alive
cache-control: no-cache

{
"product": {
    "sku": "08130056-DARKNAVY",
    "name": "Dakine Campus 25L Backpack - Dark Navy",
    "price": "44.9900",
    "status": "1",
    "visibility": "4",
    "type_id": "simple",
    "weight": "1.0000",
    "extension_attributes": {
        "stock_item": {
            "manage_stock": 1,
            "qty": "1.0000",
            "is_in_stock": true
        }
    },
    "options": [],
    "tier_prices": [],
    "media_gallery_entries": [{
        "media_type": "image",
        "label": "Dakine Campus 25L Backpack - Dark Navy2222",
        "position": "0",
        "disabled": 0,
        "types": [
        	"small_image"
        	],
        "content": {
            "base64_encoded_data": DELETED,
            "type": "image\/jpeg",
            "name": "08130056 DARKNAVY22332"
        }
    }, {
        "media_type": "image",
        "label": "Dakine Campus 25L Backpack - Dark Navy22",
        "position": "0",
        "disabled": 0,
        "types": ["thumbnail", "swatch_image"],
        "content": {
            "base64_encoded_data": DELETED,
            "type": "image\/jpeg",
            "name": "08130056 DARKNAVY3333"
        }
    }],
    "attribute_set_id": 4
},
"save_options": true
}
```
and the result was same as before(all works fine). 
So i can't confirm your issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-12-03 11:08 UTC
Labels: Issue: Format is valid

**Comment by merance2000** [comment] 2019-12-03 12:08
But we aren’t changing the image. He is sending the same image when he updates the product.

**Comment by merance2000** [comment] 2019-12-03 22:59
Did you get my message that the error is occurring when we DON’T change the image. Other data is changing but the image hasn’t the sync sends everything when it syncs, so the image is sent again even though technically it hasn’t changed. This is what they are sending – do you see any glaring errors? Have you tried the scenario where you create the item/images. Then send an update where some other things change but not the image but the image info is also sent? (the same as when it was created)?

 

This is our posting doc
{"StoreDty": {"all": {"sku": "7340041111390", "status": "1", "media_gallery_entries": [{"disabled": "false", "media_type": "image", "content": {"type": "image/jpeg", "name": "204208.jpg", "base64_encoded_data": <REMOVED>, "types": ["image", "small_image", "thumbnail"]}], "name": "Back on Track Poll Cover with Velcro Straps", "weight": "0.1", "type_id": "simple", "price": "26.95", "attribute_set_id": "4", "visibility": "4", "custom_attributes": [{"attribute_code": "category_ids", "value": [2000, 2009, 1879]}, {"attribute_code": "special_price", "value": "27.0"}, {"attribute_code": "brand", "value": "4942"}, {"attribute_code": "cp_item_no", "value": "204208"}, {"attribute_code": "custom_stock_status", "value": "3869"}, {"attribute_code": "custom_stock_status_qty_based", "value": "1"}, {"attribute_code": "custom_stock_status_qty_rule", "value": "3880"}, {"attribute_code": "description", "value": "Back on Track Poll Cover with velcro straps attaches securely to the top of a bridle or halter to help ease tightness and improve comfort in the sensitive poll area.</P><P>Back on Track products use a special polypropylene fabric impregnated with ceramic powder. The ceramic powder reflects body heat back in the form of FAR infrared rays to improve circulation and help to relax muscles. By placing the pad on the poll, the therapeutic rays are able to relax the muscles of the head and neck as well as padding the crown piece, making it more comfortable. This could lead to better acceptance of the bit and a more relaxed ride. </p><LI>Small pad with velcro straps can be attached to a bridle or halter crown</LI><LI>Ceramic infused fabric reflects body heat back to warm and loosen muscles</LI><P>Not recommended for use on pregnant mares."}, {"attribute_code": "google_exclude", "value": "0"}, {"attribute_code": "mpn", "value": "2062-002"}, {"attribute_code": "primary_vendor", "value": "5909"}, {"attribute_code": "shipping_length", "value": "15"}, {"attribute_code": "shipping_rules", "value": "4900"}, {"attribute_code": "shipping_width", "value": "6"}, {"attribute_code": "special_from_date", "value": "2019-09-07"}, {"attribute_code": "special_to_date", "value": "2019-09-09"}], "extension_attributes": {"stock_item": {"use_config_manage_stock": "1", "backorders": "1", "manage_stock": "1", "qty": 0, "is_in_stock": "1", "use_config_backorders": "0"}}}}, "WebsiteUpdates": []}

**Comment by merance2000** [comment] 2019-12-05 18:15
Any updates on this? My sync team made this change and now it works half the time

 

The dev team made a change to send null for the id field but it isn't a perfect work around. It seems to toggle the roles on and off. If the sync goes with the roles set then the roles disappear. The next time the sync goes the roles re-appear. This is despite the fact that we are sending the exact same post each time. It's better than what you had in that before you would lose the images on 100% of the syncs and now you are down to 50% of the syncs.

**Comment by markalston** [comment] 2020-01-23 22:34
We are having this same problem when using Magento's import.  All roles are gone.

**Comment by merance2000** [comment] 2020-01-23 23:44
They say they can't reproduce - we still have the issue - my developer wrote script to assign image roles when they became un-assigned and we try to not sync any images if they don't change so the corruption doesn't occur. Still have problems with some products and the script does not always fix but can't find a rhyme or reason to it.

**Comment by markalston** [comment] 2020-01-24 22:31
So I think it might be related to the new Swatch image stuff.  Our import files didn't have columns from swatch image and swatch label.  I added those with blank data and now the image roles are back and fixed.  Now if I try to import without those columns is also still works.  Weird.  Looks like something isn't initialized correctly for those of us with products we are updating.

**Comment by markalston** [comment] 2020-01-24 22:36
I also just noticed that @merance2000 's post data didn't have swatch image fields but @engcom-Charlie always has it in his post data.
