### ISSUE TITLE
When using MysqlMQ messages are always set to complete even if exception occurs

### ISSUE THREAD

**Issue by php4umagento** [magento/magento2#18140] opened 2018-09-19 16:41 UTC
### Preconditions (*)

1. Magento 2.3 and 2.4-develop
2. Using mysql mq driver to work with the queue

### Steps to reproduce (*)

1. Publish any message to the queue
2. In the consumer throw Exception

### Expected result (*)

1.Message should be flagged as error in the queue

### Actual result (*)

1. Message is set to complete and ACK

Problem is here -

When exception happens in the Consumer message is flagged as error here 
https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/MessageQueue/Consumer.php#L229

but then this status is overwritten by

 https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/MysqlMq/Model/Driver/Queue.php#L114

**Comment by magento-engcom-team** [comment] 2018-09-19 16:41
Hi @php4umagento. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@php4umagento do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-09-20 05:51
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `acknowledged` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by magento-engcom-team** [comment] 2018-09-20 15:30
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95138` were created

**Comment by vdubyna** [comment] 2019-07-31 13:04
The issue still exists in 2.3.2, the only thing needed to fix it is to update the lock resource 
and set lock_id to lock 

```php
   /**
     * {@inheritDoc}
     */
    public function saveLock(\Magento\Framework\MessageQueue\LockInterface $lock)
    {
        $object = $this->lockFactory->create();
        $object->setMessageCode($lock->getMessageCode());
        $object->setCreatedAt($this->dateTime->gmtTimestamp());
        $object->save();
        // After save we set lock id to lock object
        $lock->setId($object->getId());
    }
```

**Comment by magento-engcom-team** [comment] 2019-12-27 11:15
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30104` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by geet07** [comment] 2020-10-10 10:06
@magento I am working on it

**Comment by geet07** [comment] 2020-10-10 10:06
#dmcdindia2020

**Comment by dineshvb** [comment] 2020-12-01 09:22
@magento I am working on this

**Comment by dineshvb** [comment] 2020-12-14 10:44
> The issue still exists in 2.3.2, the only thing needed to fix it is to update the lock resource
> and set lock_id to lock
> 
> ```
>    /**
>      * {@inheritDoc}
>      */
>     public function saveLock(\Magento\Framework\MessageQueue\LockInterface $lock)
>     {
>         $object = $this->lockFactory->create();
>         $object->setMessageCode($lock->getMessageCode());
>         $object->setCreatedAt($this->dateTime->gmtTimestamp());
>         $object->save();
>         // After save we set lock id to lock object
>         $lock->setId($object->getId());
>     }
> ```

Hi @vdubyna, can I add this line and give a PR? Will it resolve the issue?

**Closed as completed** 2021-01-05 13:20 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.2.x, Issue: Format is valid, Component: Backend, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P1, Severity: S1, Progress: done, CD, Event: dmcdindia2020
