### ISSUE TITLE
Backup cron schedule not working

### ISSUE THREAD

**Issue by MajorKuprich** [magento/magento2#31979] opened 2021-02-05 11:22 UTC
### Preconditions (*)

1. Magento 2.4.1 CE

### Steps to reproduce (*)

1. Enable scheduled backup from admin config (Stores -> Configuration -> Advanced -> System -> Backup Settings).
2. Flush M2 cache.
3. Install and run cronjobs (bin/magento cron:install && bin/magento cron:run).

### Expected result (*)

1. Cronjob scheduled & executed (related record created in **cron_schedule** table).

### Actual result (*)

1. Cronjob not scheduled (related record not created in **cron_schedule** table).

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment] 2021-02-08 09:25
Hi @MajorKuprich. Thank you for your report.
Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop. Everything works as expected.

**Manual testing scenario:**

1. Go to `Admin -> Stores -> Configuration -> General -> Locale Options` and set correct Time Zone ( in my case:

![Screenshot from 2021-02-08 10-52-56](https://user-images.githubusercontent.com/51679138/107197871-23036700-69fd-11eb-8c18-5bb4047be3e2.png)

2. Enable scheduled backup from admin config (`Stores -> Configuration -> Advanced -> System -> Backup Settings`).
![Screenshot from 2021-02-08 10-53-58](https://user-images.githubusercontent.com/51679138/107198028-4cbc8e00-69fd-11eb-9384-f9041b7c1497.png)
![2021-02-08_10-54](https://user-images.githubusercontent.com/51679138/107198010-47f7da00-69fd-11eb-80c0-f695e02970c9.png)

3. Install and run cronjobs (`bin/magento cron:install` && `bin/magento cron:run`).

**Actual Result:** :heavy_check_mark: Cronjob scheduled & executed (related record created in cron_schedule table).

![2021-02-08_10-55](https://user-images.githubusercontent.com/51679138/107199145-b721fe00-69fe-11eb-9683-9f4ca0a32ae4.png)
![Screenshot from 2021-02-08 10-58-31](https://user-images.githubusercontent.com/51679138/107199152-b8ebc180-69fe-11eb-923d-866b7c47c402.png)

Most likely, the problem was in the unset time zone.
So, we have to close it.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch.
 Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2021-02-08 09:25 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.4.1
