### ISSUE TITLE
All products deleted after mass action request

### ISSUE THREAD

**Issue by nbennett25** [magento/magento2#19533] opened 2018-12-03 17:59 UTC
_Originally posted by @nbennett25 in https://github.com/magento/magento2/issues/15935#issuecomment-443777390_

The bug described in https://github.com/magento/magento2/issues/15935 still exists in v2.2.5.

Env:
Magento 2.2.5, PHP 7.0, 5.6.40 MySQL

Steps to reproduce:
1 Download clean Magento 2.2.5 CE, configure site, install sample data
2 Go to Catalog > Products
3 Select 3 products in the grid
4 Select Actions > Delete
5 Confirm OK
6 Immediately perform steps 4 and 5 again

Expected result:
Only the 3 products selected are deleted

Actual result:
All products deleted
User is sent to admin log in page

**Comment by magento-engcom-team** [comment] 2018-12-03 18:00
Hi @nbennett25. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nbennett25 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by hostep** [comment] 2018-12-03 18:42
Closing as duplicate of #15935, please continue discussion in there, looks like the fix made it in 2.2.6.

**Closed as completed by hostep** 2018-12-03 18:42 UTC
Labels: Issue: Format is not valid

**Comment by nbennett25** [comment] 2018-12-03 18:59
> Closing as duplicate of #15935, please continue discussion in there, looks like the fix made it in 2.2.6.

Thanks @hostep  - can you point me to the commit that fixed the issue? Also from #15935 it looks like it's reproduceable in 2.3.

**Comment by hostep** [comment] 2018-12-03 19:06
It looks like it was fixed with reference to Magento's internal jira issue: `MAGETWO-91411`, if I look through the git history I can find this merge commit: https://github.com/magento/magento2/commit/7028b311c05 (which consists of a892d87bc3b & 70cbd3cf8b4)

As for 2.3, I can find `MAGETWO-93715` with the following 3 commits: 80fc4aa81a9 & c840ade149c & 62520aff20f, all of these are in 2.3.0, so should be fine, but don't hesitate to re-test.
