### ISSUE TITLE
Magento Persistent Cart Issue

### ISSUE THREAD

**Issue by AGranitsas** [magento/magento2#33064] opened 2021-05-24 09:14 UTC
### Summary (*)
 
I am facing an issue while trying to make our Persistent Cart work. 

### Examples (*)
 I specifically need the Cart Cookie to work on our e commerce platform and disable the Session cookie. I only see five options on the persistent cart to customize it, but I think they are not appropriate. 
They are the following:
1. Persistence Lifetime (seconds)
2. Enable "Remember Me"
3. "Remember Me" Default Value
4. Clear Persistence On Sign Out
5. Persist Shopping Cart

How should I proceed?
![Persistent Cart](https://user-images.githubusercontent.com/84708690/119325415-82724380-bc89-11eb-9397-9cdcb1da3d02.PNG)

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by AGranitsas** [comment] 2021-05-27 07:31
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment] 2021-05-31 05:31
HI @AGranitsas 

As per your reported description, seems to be no issue but you want to disable the session cookie and as per the UI content it is not being satisfied.
Well Kindly check the document link - https://docs.magento.com/user-guide/sales/cart-persistent.html?itm_source=merchdocs&itm_medium=quick_search&itm_campaign=federated_search&itm_term=pers

Also we have additional features with commerce edition and below is the screenshot of it.
![image](https://user-images.githubusercontent.com/51679138/120144284-47c75880-c1ff-11eb-9501-e96a7a5d06a7.png)

If you are expecting something based on this, kindly help me with providing more expected content in detail.

**Comment by engcom-Alfa** [comment] 2021-06-14 06:23
Since there is no update to me in last ~14 days on my last comment, I am closing this ticket.
In case of any issue in future relevant to it in the latest versions, kindly report with a new ticket having all the reproducible information.
Thanks

**Closed as completed by engcom-Alfa** 2021-06-14 06:23 UTC
Labels: Progress: needs update, non-issue, Issue: ready for confirmation
