### ISSUE TITLE
Date design change show not correctly value in backend

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#21425] opened 2019-02-25 03:02 UTC
### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.1.17

### Steps to reproduce (*)

1. Go to Admin
2. Content > Design > Schedule
3. Add new design change
4. Fill form with date pick to year 21xx
5. Go back to edit one more, click on date icon to see issue

### Expected result (*)

1. Show correctly date Ex: 02/04/2100

### Actual result (*)

1. Currently date show 2/4/00
This happen in interface US locale
Reproduced on 2.2.8-dev too

**Comment by magento-engcom-team** [comment] 2019-02-25 03:02
Hi @mrtuvn. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mrtuvn do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by mrtuvn** [comment] 2019-02-25 03:04
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-25 03:04
Hi @mrtuvn. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-25 03:05
Hi @mrtuvn, here is your [Magento instance](https://i-21425-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21425-2-3-develop.instances.magento-community.engineering/admin](https://i-21425-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mrtuvn** [comment] 2019-02-25 03:09
@magento-engcom-team  yes i can reproduce issue in develop test enviroment

See my image attachment

![screenshot from 2019-02-25 10-08-49](https://user-images.githubusercontent.com/1908873/53311907-726e2c80-38e5-11e9-8c17-44d6a27576d7.png)

**Comment by magento-engcom-team** [comment] 2019-02-25 04:36
Hi @krishprakash. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by krishprakash** [comment] 2019-02-25 04:38
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-25 04:38
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-25 04:38
Hi @krishprakash, here is your [Magento instance](https://i-21425-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21425-2-3-develop.instances.magento-community.engineering/admin](https://i-21425-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-02-25 05:05
:white_check_mark: Confirmed by @krishprakash
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment] 2019-02-25 07:36
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-02-25 08:27
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98412`, `MAGETWO-98413` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-03-04 14:47
Hi @mrtuvn. Thank you for your report. 
The issue has been fixed in magento/magento2#21443 by @shikhamis11 in 2.3-develop branch
Related commit(s):
 - [68ee3af4512ec5db3e8b65e66a59db5b061e5dd0](https://github.com/magento/magento2/commit/68ee3af4512ec5db3e8b65e66a59db5b061e5dd0)
 - [8e95bfdc91823a91d8c7a351a96ef24ed0eed60e](https://github.com/magento/magento2/commit/8e95bfdc91823a91d8c7a351a96ef24ed0eed60e)
 - [f0a98a5a8263cba774d503171e2eb00567365d5b](https://github.com/magento/magento2/commit/f0a98a5a8263cba774d503171e2eb00567365d5b)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-04 14:47 UTC
Labels: Issue: Ready for Work, Component: Config, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Admin

**Comment by magento-engcom-team** [comment] 2019-03-11 13:30
Hi @mrtuvn. Thank you for your report. 
The issue has been fixed in magento/magento2#21568 by @mage2pratik in 2.2-develop branch
Related commit(s):
 - [080743fba05fdcc4cfb98fd9bcdc15e39d7e02d9](https://github.com/magento/magento2/commit/080743fba05fdcc4cfb98fd9bcdc15e39d7e02d9)
 - [2b41017794d74966ed2df9932d7d1d33518475f1](https://github.com/magento/magento2/commit/2b41017794d74966ed2df9932d7d1d33518475f1)
 - [21cd1cb0ac7479528da78b802231c65d98a416bd](https://github.com/magento/magento2/commit/21cd1cb0ac7479528da78b802231c65d98a416bd)

The fix will be available with the upcoming 2.2.9 release.
