### ISSUE TITLE
Customer "Sign In" button not working anymore.

### ISSUE THREAD

**Issue by The-Krang** [magento/magento2#11529] opened 2017-10-17 22:35 UTC
The button worked a few times, then stopped.

Clean install of version 2.2.

On a Linux-based web host.

In the cPanel, 1H Software PHP version Manager shows PHP version 7.1.

phpMyAdmin Web Server PHP shows up as version: 5.6.30.  I don't know how to upgrade that yet.

No theme chosen for the store.

The only external thing I have is a module installed and enabled.  It only affects the Order Success Page/ success.phtml.

Attached below is the image of what I am talking about.

In the Admin, I have: the default store view; One page checkout is enabled;

I tried using Internet Explorer and Opera browsers with a clean browser cache, but the result is still the same.

I am testing the store from a Windows 7 Professional computer.

I didn't see any errors in the /var/log files.

From the Admin side, I cleaned the cache, emptied cahe storage, and refreshed whatever needed it.

**Steps taken to produce the error:**
In the store, I add a virtual, downloadable item to the cart.
I click the cart icon in the top right of the screen.
I click on the "View and Edit Cart" link in the small window that opens.
I click the "Proceed to Checkout" button on the right side of the screen.
The account popup form appears, and I put my credentials into it.
I click the "Sign In" button, and it turns a darker color of gray.
Nothing happens afer that.

**Expected result:**
Using the same procedure as above, after clicking the "Sign In" button, it should take me to a page that asks for the customer's address.

The "Create Account" button on that same popup works though.

Below is the Opera browser console output.  These errors are **only** shown **after** the Sign In button is clicked:

JQMIGRATE: Logging is active

/pub/static/version1507935652/frontend/Magento/luma/en_US/Magento_Customer/js/view/authentication-popup.js:76 

Uncaught TypeError: Cannot read property 
'currentTarget' of undefined

at UiClass.login 
(/pub/static/version1507935652/frontend/Magento/luma/en_US/Magento_Customer/js
/view/authentication-popup.js:76)

    
at HTMLFormElement.<anonymous> 
(/pub/static/version1507935652/frontend/Magento/luma/en_US/knockoutjs/knockout
.js:4241)
    

at HTMLFormElement.dispatch 
(/pub/static/version1507935652/frontend/Magento/luma/en_US/jquery.js:5226)
    

at HTMLFormElement.elemData.handle 
(/pub/static/version1507935652/frontend/Magento/luma/en_US/jquery.js:4878)

Everything else so far about the store seems to be working as expected.

Thank you very much.

Also, thank you folks for making the telephone field optinal on orders in version 2.2.

![customer sign in button not working](https://user-images.githubusercontent.com/28166039/31692915-d8a1ab6a-b369-11e7-96f8-d4279ff04ef0.jpg)

**Comment by magento-engcom-team** [comment] 2017-10-19 08:25
@The-Krang, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-19 08:25 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid

**Comment by The-Krang** [comment] 2017-10-19 17:05
Thank you folks for replying to the problem.

I see that you folks have closed this issue.

I am a programmer, but I am still a newbie when it comes to using Magento 2,  so I don't know how or where I am supposed to fix the problem with the "Sign In" button.  Is there supposed to be something that I should download/upgrade?

I did a quick search for "_**The issue is already fixed in develop branch...**_", but nothing showed up.
I went to the Magento patches page and didn't see anything there.

I don't know if it makes any difference now, but I failed to mention that I was using the Open Source version, that was installed using Softaculous.

Thank you again.

**Comment by Yamaha32088** [comment] 2017-12-14 14:16
@magento-engcom-team do you happen to have the pull request number or the specific files that were changed to patch this bug? I can't seem to find it anywhere and I am having the same issue after upgrading to 2.2.2. I believe I may be doing an override in my theme that may be causing it which is why I would like to know which files were modified.

**Comment by The-Krang** [comment] 2017-12-19 17:37
Forgive my ignorance, but I don't know what a "pull request" is.

I upgraded to version 2.2.1 and the problem went away after that.

I'm still a newbie to Magento.

Sorry.


________________________________

**Comment by sabarivenkat** [comment] 2018-01-16 13:41
I am also facing the same issue in Magento 2.2.2 itself. I think this happens only when upgrading the Magento version.

**Comment by kanhaiya5590** [comment] 2018-03-31 22:09
@sabarivenkat & @The-Krang 

I found 2 files which are using for [authentication popup](https://magento.stackexchange.com/questions/198687/customer-sign-in-button-not-working-anymore/220607#220607), If still having same concern then update these 2 files in your theme. 

 **authentication-popup.html**
`data-bind="submit:login"` change to `data-bind="event: {submit: login }"`

I feel **authentication-popup.js** is already updated that wise you getting `'currentTarget' of undefined`

Hope this will help you.

**Comment by The-Krang** [comment] 2019-04-25 15:24
@kanhaiya5590 Thank you for replying.  I "solved" this issue quite a while back, by updating to a newer version of Magento 2.  Now, it looks like this issue has surfaced again in version 2.3.1, but your response to my post (https://magento.stackexchange.com/questions/198687/customer-sign-in-button-not-working-anymore) may help me resolve it too.  Thank you very much.
