### ISSUE TITLE
Product Image Alt Text not used on product grid 

### ISSUE THREAD

**Issue by magefan** [magento/magento2#12437] opened 2017-11-24 18:16 UTC
Magento 2 use product name instead of img alt text on product grid.

### Preconditions

1. Magento 2.2.1 (Luma theme)
2. PHP 7.0.22
4. OS Ubuntu 16.04

### Steps to reproduce
1. Set the alt text for product image (we used simple product for test)
2. Run reindex + flush cache
3. Look at alt tag for product image on product page - it's OK.
3. Look at alt tag for product image on category page - it use not alt text but product name

### Expected result
1. On category page product image use alt text (if set in admin panel) not product name

**Comment by orlangur** [comment] 2017-11-25 10:16
It could be intentional system behavior, see https://github.com/magento/magento2/issues/9931#issuecomment-308108631

**Comment by magento-engcom-team** [comment] 2017-11-27 07:58
@magefan, thank you for your report.
We've created internal ticket(s) MAGETWO-84514 to track progress on the issue.

**Comment by vindhuja** [comment] 2018-05-19 11:27
I am working on this at #dmcdindia

**Comment by magento-engcom-team** [comment] 2018-05-19 11:27
@vindhuja thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by lewis-dan** [comment] 2018-05-19 11:45
I am working on this at #dmcdindia

**Comment by santhoshp** [comment] 2018-05-19 18:50
I am working on this at #dmcdindia

**Comment by hitesh-wagento** [comment] 2018-05-25 06:03
@magefan I have tested above alt tag issue in Magento ver. 2.2.6-dev and Magento ver. 2.2.4 but Not able to reproduce it's working fine please review attached screenshots.

![-magento-ver -2 2 4-cateogrypage](https://user-images.githubusercontent.com/23443991/40528682-6919a0e2-600f-11e8-851f-3a50459ac470.png)
____________________________________________________________
![magento-ver -2 2 4-product-detailpage](https://user-images.githubusercontent.com/23443991/40528683-6943a39c-600f-11e8-8bf1-2f59bdac13a0.png)
____________________________________________________________
![magento-ver -2 2 6-dev-category](https://user-images.githubusercontent.com/23443991/40528684-696c87d0-600f-11e8-9dad-1bafb9169fb8.png)
____________________________________________________________
![magento-ver -2 2 6-dev-product-detail](https://user-images.githubusercontent.com/23443991/40528685-69963102-600f-11e8-8f9b-dd73cd0fe1d1.png)

**Comment by magento-engcom-team** [comment] 2018-05-26 10:59
@hitesh-wagento Thank you for research.
@magefan We are closing this now, as problem does not seem to be reproducible. Thanks

**Closed as completed by magento-engcom-team** 2018-05-26 10:59 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is not valid, Event: dmcdindia

**Comment by Harshadtricore** [comment] 2018-08-14 14:53
Preconditions

Magento 2.1.8
OS Ubuntu 16.04 LTS

Steps to reproduce

Set the alt text for product image
Run reindex + flush cache
Look at alt tag for product image on product page - it is display alt text.
Look at alt tag for product image on category page - it can't update and take the product name

I have checked your comment and you told that it is resolved in Latest version.I cant upgrade my magento version now so can you please let me know what is fix for it? So, I can apply those fixes on my magento.
