### ISSUE TITLE
Feature request: add a link to admin in Setup Wizard

### ISSUE THREAD

**Issue by qmarlats** [magento/magento2#4798] opened 2016-05-31 14:31 UTC
Hey! Don't you think it would be a great idea to add a link to Magento admin in Setup Wizard? Currently we have to manually edit URL to go back to admin.

**Comment by mazhalai** [comment] 2016-05-31 14:34
Please see https://github.com/magento/magento2/issues/3742#issuecomment-196420331
Closing since this is not a bug.

**Closed as completed by mazhalai** 2016-05-31 14:34 UTC
