### ISSUE TITLE
Template hints visible in admin pages.

### ISSUE THREAD

**Issue by ctubio** [magento/magento2#1198] opened 2015-04-19 02:45 UTC
When i enable the template hints for a store view, the template hints are also visible in the admin pages:
![admin_template_hints](https://cloud.githubusercontent.com/assets/1634027/7217950/c916f99c-e64e-11e4-84cf-693ccefb6b78.png)

this is the expected behaviour?

thank you''

**Comment by tzyganu** [comment] 2015-04-19 03:04
Duplicate of #647. I see this isn't fixed yet. Please fix.

**Comment by ctubio** [comment] 2015-04-20 12:30
See #647 for up-to-date comments.

(i hate duplicates, sorry for this one :disappointed:)

**Comment by snohe** [comment] 2015-04-27 22:28
@ctubio @tzyganu, thanks for the update.  We'll go ahead and close this issue in favor or #647.  Please watch that issue for any updates.

**Closed by snohe** 2015-04-27 22:28 UTC
Labels: bug, PS
