### ISSUE TITLE
[Paypal Payflow] Credit Memo is duplicated on full refund

### ISSUE THREAD

**Issue by roma-glushko** [magento/magento2#24149] opened 2019-08-16 09:32 UTC
It's possible to get credit memo duplications of when doing the full refund for orders that are paid by Paypal Payflow.

### Preconditions
1. Magento 2.2.6 Open Source (or Commerce) 
2. PayPay Payflow is configured and enabled:

<img width="1114" alt="2019-08-16_09-39-11" src="https://user-images.githubusercontent.com/9402690/63148691-ab709980-c00a-11e9-944c-1609e7afaf86.png">

3. An order with non-zero total and paid by PayPal Payflow methods (Paypal Express Checkout) with no credit memos created
4. The testing environment is accessible for PayPal IPN requests

### Steps to reproduce 
1. Go to the order view page of the order
2. Create a full refund credit memo for the order
3. Wait a couple of minutes till Paypal reached IPN endpoint of Magento

### Expected result
For the full refund request, it's expected to see only one credit memo that refunds all paid amount to the customer. 

### Actual result
For the full refund request, Magento creates two and sometimes more credit memos which look almost the same and are created with a couple of seconds difference. Here is a list of recent cases:

#### Case 1. Two credit memos: 1 offline and 1 online

Order History:

<img width="1591" alt="2019-08-16_10-57-34" src="https://user-images.githubusercontent.com/9402690/63152638-f7284080-c014-11e9-9200-9eb2f02628bc.png">

Credit Memos:
<img width="1581" alt="2019-08-16_11-00-50" src="https://user-images.githubusercontent.com/9402690/63152743-3c4c7280-c015-11e9-890c-7f295cb762ff.png">

Credit Memo View Pages:
<img width="1590" alt="2019-08-16_11-02-27" src="https://user-images.githubusercontent.com/9402690/63152875-8f262a00-c015-11e9-9325-a398e384dc97.png">

<img width="1592" alt="2019-08-16_11-04-21" src="https://user-images.githubusercontent.com/9402690/63152949-c1378c00-c015-11e9-9b1d-1b2f1a7d2926.png">

Anonymized Server Access logs (13.08, from 15:40 till 16:10, only selected records from CreditMemo and Paypal IPN routes):

[custom-08-13-71116.log](https://github.com/magento/magento2/files/3508762/custom-08-13-71116.log)

#### Case 2. Three credit memos: 1 offline  and 2 online
Order History:

<img width="1680" alt="2019-08-16_08-31-16" src="https://user-images.githubusercontent.com/9402690/63151418-25f0e780-c012-11e9-86e0-3f0ee30150f5.png">

Credit Memos:
![2019-08-15_14-28-12](https://user-images.githubusercontent.com/9402690/63151240-b4b13480-c011-11e9-8025-174cb2bb97fa.png)

Credit Memo View Pages:

<img width="1588" alt="2019-08-16_10-46-48" src="https://user-images.githubusercontent.com/9402690/63152100-ad8b2600-c013-11e9-820e-07db4e11f697.png">

<img width="1575" alt="2019-08-16_10-51-32" src="https://user-images.githubusercontent.com/9402690/63152239-078beb80-c014-11e9-9810-fc422c9fdd95.png">

<img width="1589" alt="2019-08-16_10-53-29" src="https://user-images.githubusercontent.com/9402690/63152357-4de14a80-c014-11e9-9bfc-df0d0015c721.png">

Anonymized Server Access logs (12.08, from 10:40 till 11:10, only selected records with CreditMemo and Paypal IPN routes):

[custom-08-12-68822.log](https://github.com/magento/magento2/files/3508845/custom-08-12-68822.log)

**Comment by engcom-Charlie** [comment] 2019-08-22 08:19
Hello @roma-glushko 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.

We are closing this issue due to branch 2.2-develop was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.
See Accepted pull requests and ported code for more details

If you still faced this issue on 2.3 please create a new Issue with all required details according to Issue reporting guidelines

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-08-22 08:19 UTC
Labels: bug report, Component: Sales, Issue: Format is valid, Component: Paypal

**Comment by claudioxu** [comment] 2022-03-15 02:59
We are facing the same problem on 2.3.5-P1 (CE)
