### ISSUE TITLE
Shipping address renderer is not loading customAttributes in Magento EE 2.3.4

### ISSUE THREAD

**Issue by noeli-eshopguru** [magento/magento2#26740] opened 2020-02-06 21:49 UTC
### Preconditions (*)

1. Magento EE 2.3.4
2. Checkout

### Steps to reproduce (*)

1. Add a product to cart as logged in customer with the default shipping & billing address.
2. Go to checkout.
3. Move to the payment step and try to select the payment methods.
4. Come back to the shipping step.
5. Move to the payment step again.

### Expected result (*)

1. You can select the payment methods without any error.
2. You have to go to the payment step without any error.

### Actual result (*)

1. You can't select any payment method.
2. You can't go to the payment step again
3. You will see knockout js errors on the browser console.
![image](https://user-images.githubusercontent.com/50664110/73981103-81ba7e80-496c-11ea-9cba-4c517633efba.png)

You can't do any action because of those errors.
Magento EE 2.3.4 added a new function getCustomAttributeLabel for shipping address, shipping information and billing address templates. But this function is occurring error.
For example, /Magento_Checkout/js/view/shipping-address/address-renderer/default.js line:68
![image](https://user-images.githubusercontent.com/50664110/73981318-f8577c00-496c-11ea-85a2-691ef58eb163.png)
this.source.get('customAttributes') is undefined.
I know Magento EE 2.3.4 has vendor/magento/module-customer-custom-attributes module.
Is this error related to this module?

**Comment by engcom-Bravo** [comment] 2020-02-10 09:59
Hello @noeli-eshopguru 

Thank you for your report

We are not able to reproduce this on 2.4-develop instance with a custom **Product attribute**, and  with an added **Customer attribute**
![customer_attribute](https://user-images.githubusercontent.com/51680745/74139480-1d155300-4bfc-11ea-81c7-410df64e066f.png)

Tried with several payment methods 
![payment_method](https://user-images.githubusercontent.com/51680745/74139672-78474580-4bfc-11ea-83e5-60162d5f22a2.png)

Can you please help us to resolve this issue by answering the following questions:
- does this issue occur on 2.4-develop instance?
- what kind of custom attribute are you using, if it is possible, please attach a screenshot with the attribute settings? 
- what kind of payment methods are available fro your store?

Thank you in advance

**Comment by noeli-eshopguru** [comment] 2020-02-10 12:10
Hi @engcom-Bravo 

- The issue occurred on Magento EE 2.3.4.
- It's not for the product custom attribute. It's for the customer custom attributes from module-customer-custom-attributes. I have already showed the cases on the top. Please read again.

Thanks.

**Comment by darinda** [comment] 2020-02-10 16:52
I can confirm that problem, we have it too after upgradng von v2.3.3 to v2.3.4. The problem can indeed be tracked down to the method mentioned by @noeli-eshopguru, the `getCustomAttributeLabel` [method](https://github.com/magento/magento2/commit/22c4ee1413212f4b55cff5014d48966c26582fe5#diff-58918a1c0b2e0806d4ed1c4ff74c9b1fR247) that was introduced by https://github.com/magento/magento2/commit/22c4ee1413212f4b55cff5014d48966c26582fe5.

In our case we're talking about a custom attribute added to `quote_address` and `order_address` entities, respectively.

The new input field is added to the **billing address** using (a therefore slightly modified version) of the [official documentation](https://devdocs.magento.com/guides/v2.3/howdoi/checkout/checkout_new_field.html).

**Comment by xmav** [comment] 2020-02-10 17:27
Appears to be fixed in https://github.com/magento/magento2/commit/4ef5d3939ee7498f1d0af1257b603e55fb5ff162

**Comment by darinda** [comment] 2020-02-11 07:53
@xmav, confirmed. Thank you, the problem is fixed by the mentioned commit.

**Comment by engcom-Bravo** [comment] 2020-02-12 09:03
@noeli-eshopguru 

The issue is fixed on Magento 2.4-develop with the commit mentioned above https://github.com/magento/magento2/commit/4ef5d3939ee7498f1d0af1257b603e55fb5ff162

So we have to close this issue
If you'll ever face any issues with Magento, please feel free to create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thank you for collaboration

**Closed as completed by engcom-Bravo** 2020-02-12 09:03 UTC
Labels: Progress: needs update, Issue: Format is valid, Reported on 2.3.4

**Comment by noeli-eshopguru** [comment] 2020-02-12 09:08
@engcom-Bravo 
Yes, right.
Thanks for your help.

**Comment by mts527** [comment] 2020-04-29 06:28
On EE 2.3.4. we also needed to extend `js/view/checkout/shipping-information/address-renderer/shipping.js` from the **Temando Shipping module** by adding `getCustomAttributeLabel` method which was missing (same way as applied in the [4ef5d39]https://github.com/magento/magento2/commit/4ef5d3939ee7498f1d0af1257b603e55fb5ff162)).
