### ISSUE TITLE
Timezone converts to invalid value

### ISSUE THREAD

**Issue by yash7690** [magento/magento2#22946] opened 2019-05-20 07:23 UTC
Magento 2.3.0 converts timezone to invalid value when defining the cron job.

Preconditions (*)
1. Magento community 2.3.0
2. PHP 7.1.25-1+ubuntu16.04.1+deb.sury.org+1

Steps to reproduce (*)
1. Installed Magento 2.3.0 on a system which is having UTC timezone as server time
2. Setup Indian Timezone in Store -> Configuration -> General -> General -> Locale Options -> Timezone, Setup India Standard TIme (Asia/Kolkata)
3. Setup custom cronjob at schedule with value "45 11 * * *"
4. checking in cron_schedule table at 11:40 which should have entry of custom created cronjob but it is not there due to invalid time conversion.

Expected result (*)
1. In cron_schedule table, it should have entry of custom cron but not having.

Actual result (*)
1. While debugging, found that the file

File: vendor/magento/module-cron/Model/Schedule.php
Function: trySchedule()
Line: $time = $this->timezoneConverter->date($time)->format('Y-m-d H:i');

I saw that it does not convert time from UTC to IST, instead it keeps the time as it is.
While the same configuration and setup works fine with magento 2.2.6. Magento 2.2.6 convert time from UTC to IST as expected.

For example, below date,
2019-05-20 07:09
is converted to 
2025-11-09 07:09

By using mentioned line of code.

**Comment by magecp** [comment] 2019-06-29 05:18
I am working on ir.

**Comment by engcom-Charlie** [comment] 2019-11-01 14:28
Hello @yash7690 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the latest 2.3-develop branch by provided steps.

`trySchedule()` function is updated now:
![image](https://user-images.githubusercontent.com/51680850/68028875-9d075500-fcbe-11e9-9100-38ecf7cbcf84.png)

So i have to close this issue as not actual.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-11-01 14:28 UTC
Labels: Issue: Format is valid, Triage: Dev.Experience
