### ISSUE TITLE
Unable to create magento/magento2 repository fork

### ISSUE THREAD

**Issue by pierzakp** [magento/magento2#36385] opened 2022-10-28 11:13 UTC
### Preconditions (*)

1. macOS Monterey 12.6.1
2. Opera browser / Chrome browser

### Steps to reproduce (*)

1. Open webpage of magento/magento2 repository
2. Click on Fork button on the top right
3. On the next page click Create Fork button

### Expected result (*)

1. Expected is that fork of magento/magento2 repository will be created under my private account

### Actual result (*)

1. During fork creation error occurs saying: "Description cannot be more than 350 characters"

**Comment by pierzakp** [comment] 2022-10-28 12:18
For your information, I tried also to remove whole description while creating fork and it does not help.

**Comment by pierzakp** [comment] 2022-10-28 13:01
It does not work when I do not touch description - leave it as it is loaded in the form,
also it does not work when I remove whole description.

But... it works if I remove part of the description ;)

**Comment by DavaGordon** [comment] 2022-11-01 20:24
@pierzakp this is not an issue i folked this repo earlier today with the same issue after changing the description to something more relevant and less than 350 characters it worked no issues.

**Comment by pierzakp** [comment] 2022-11-02 14:16
@DavaGordon indeed, but some action needs to be taken in order to resolve this issue.

**Comment by DavaGordon** [comment] 2022-11-02 17:34
@pierzakp agreed but not a critical issue.

**Comment by engcom-Hotel** [comment] 2022-11-03 08:43
Hello @pierzakp,

Thanks for the report and collaboration!

We have tried to reproduce this issue in Mac Monterey 12.6 with the Chrome browser. We are able to create a fork. It might be possible that the issue has been resolved.

Thanks

**Comment by DavaGordon** [comment] 2022-11-03 13:37
@engcom-Hotel i also am using Mac Monterey 12.6 with the Chrome browser and was able to recreate the issue.

**Comment by engcom-Hotel** [comment] 2022-11-09 09:40
Hello @DavaGordon,

It seems the issue has been resolved because we have tried to reproduce this in other systems as well but this is not reproducible. We request you to please let us know if the issue is still reproducible for you.

Thanks

**Comment by engcom-Hotel** [comment] 2022-11-23 05:59
Dear @pierzakp,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-11-23 05:59 UTC
Labels: Issue:  Cannot Reproduce, Priority: P0, Progress: done, Issue: ready for confirmation, Issue: needs update
