### ISSUE TITLE
Gd2 error logs need improving

### ISSUE THREAD

**Issue by adamlavery** [magento/magento2#36413] opened 2022-11-03 09:40 UTC
### Preconditions (*)

1. OS 2.4.3-p1
2. PHP 7.4
3. Ubuntu 20.4

### Steps to reproduce (*)

1. Run catalog:images:resize

### Expected result (*)

1. If there are any issue with image files then any files that have an issue are logged so they can checked.

### Actual result (*)

Nothing to show which files have an issue so no way to know which need to be looked at:
```
bm catalog:images:resize
1322/1322 [============================] 100% 16 mins 136.5 MiB         | /r/c/rc_thumb_new.jpg
Product images resized with errors:
Warning: imagecreatefrompng(): gd-png: libpng warning: iCCP: known incorrect sRGB profile in ...vendor/magento/framework/Image/Adapter/Gd2.php on line 84
Warning: imagecreatefrompng(): gd-png: libpng warning: iCCP: known incorrect sRGB profile in ...vendor/magento/framework/Image/Adapter/Gd2.php on line 84
Warning: imagecreatefrompng(): gd-png: libpng warning: iCCP: known incorrect sRGB profile in ...vendor/magento/framework/Image/Adapter/Gd2.php on line 84
etc...

```

**Comment by engcom-November** [comment] 2022-11-07 17:51
Hi @adamlavery ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance but unable to reproduce the issue.
On running the command:  bin/magento catalog:images:resize, image files having issue are logged as expected in the response. Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.
![image](https://user-images.githubusercontent.com/60198231/200380222-2df2d9a5-8478-4692-81b0-d9022a1cc00b.png)

Thank you.

**Comment by engcom-November** [comment] 2022-11-21 10:26
Hi @adamlavery ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-11-21 10:26 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
