### ISSUE TITLE
urlResolver ignores current store view for products and categories

### ISSUE THREAD

**Issue by t-heuser** [magento/magento2#33447] opened 2021-07-09 09:18 UTC
### Preconditions (*)

1. Magento 2.4.2
2. Multiple store views

### Steps to reproduce (*)

1. Have atleast 2 store views
2. Create a product/category and don't activate it for the second store view
3. Execute the urlResolver query for the product/category in the second store view

### Expected result (*)

```JSON
{
  "data": {
    "urlResolver": null
  }
}
```

### Actual result (*)

```JSON
{
  "data": {
    "urlResolver": {
      "redirectCode": 0,
      "relative_url": "testsimple",
      "id": 5,
      "type": "PRODUCT"
    }
  }
}
```

Side note: For cms pages the urlResolver is working as expected, it just doesn't work for products and categories
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by oneserv-heuser** [comment] 2021-07-09 09:19
@magento give me 2.4-develop instance

**Comment by oneserv-heuser** [comment] 2021-07-09 09:40
I can confirm this issue exists. I also found out that the urlResolver doesnt respect if you disable a product. The urlResolver still thinks it's active and returns the url data.

All of this leads to the problem that the urlResolver says yes to an url, but if you then use the products query there are no results because the product/category is disabled or not activated for the store view.

**Comment by denchev** [comment] 2021-07-24 15:33
I looked at the issue and here is what I found:

- The urlResolver is deprecated in favor of route. So any efforts of fixing this should be focused on the route resolver.
- It is questionable if there is anything to be fixed. The reason it works for product and for pages not (or vice versa depending on how you see the world :) ) is that a page assigns the store view per single entity and when a store is unassigned the url_rewrite row for that route is deleted. Thus the graphql cannot find it. But when you disable a product for a view the url_rewrite row remains. And in that row there is no information about the state of the entity.
- So the only way to verify if the url row is for alive entity is to check the entity itself. On one side you have to do it for every single request so it is a performance hit. And then it opens a can of worms what is considered as the rule for inactive products - is it just being disabled, is it being out of stock?

In my opinion this is a minor issue and it shouldn't be fixed as it is just not worth it.

**Comment by engcom-November** [comment] 2021-11-18 10:47
Hi @oneserv-heuser ,
The urlResolver query has been deprecated. Use the [route](https://devdocs.magento.com/guides/v2.4/graphql/queries/route.html) query instead.
On running route Query, this issue is not observed. URL for only assigned store and category are returned in the response.
![image](https://user-images.githubusercontent.com/60198231/142401204-fa966db4-e2fa-4d37-884b-339f113f77ef.png)

Kindly recheck the issue on Magento 2.4-develop branch and let us know if you are still facing any issues.
Thank you.

**Comment by oneserv-heuser** [comment] 2021-11-22 08:17
@engcom-November youre right, the issue is not reproducible with the route query. Issue closed as the urlResolver is deprectated.

**Closed as completed by oneserv-heuser** 2021-11-22 08:17 UTC
Labels: Issue:  Cannot Reproduce, Project: GraphQL, Issue: needs update
