### ISSUE TITLE
related product add to cart

### ISSUE THREAD

**Issue by Aartitops** [magento/magento2#6150] opened 2016-08-13 13:09 UTC
Hi,
I use magento 2.1.0 and i made related product into product page and when i click on add to cart from product page add to cart not working.
Please give me solution,
Thanks.

**Comment by wert2all** [comment] 2016-08-15 11:57
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by Aartitops** [comment] 2016-08-16 06:14
Hello,
When I try to add to cart it not working(Can't clicked) and can't redirect to cart page

Actual result:-
![related-product](https://cloud.githubusercontent.com/assets/20356638/17689640/a2f428b2-63a6-11e6-9853-fd3fae015af5.png)
expected result:-
Related product add to cart should be working.

Thanks.

**Comment by pboisvert** [comment] 2016-08-16 06:20
@Aartitops please read the [contributor guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) especially the part around preconditions. Is this a clean 2.1 install? An upgrade from a previous version? Please list your system configuration as well. The specific issue (related product add to cart not working is clear) so our team needs specific on your setup to try and reproduce.

**Comment by Aartitops** [comment] 2016-08-16 06:24
Hi,
I have using magento 2.1.0 version. I have does not upgrade from old vesrion. only i get the related product into product page using catalog_product_view.xml file.
but it not woking to add to cart like other products.
can you please solve this issue?
Thanks.

**Comment by sevos1984** [comment] 2016-09-12 14:16
Do you have any errors in browser console or in magento logs?

**Comment by sevos1984** [comment] 2016-09-26 12:17
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-09-26 12:17 UTC
Labels: bug report, Progress: needs update, Component: Catalog
