### ISSUE TITLE
Magento 2.4.7-px Installation fails with Elasticsearch 8.11

### ISSUE THREAD

**Issue by kkhebbar89** [magento/magento2#39438] opened 2024-12-05 05:07 UTC
### Preconditions and environment

- Magento V 2.4.7-px
- symfony/http-client version 7.2.0 which was released on 29th November 2024 is causing Elasticsearch connection issues during installation.
- Before 29th November 2024 when Magento was installed through composer had symfony/http-client version 7.1.9. Fresh installation works fine with this.

### Steps to reproduce

1) composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition .
2) composer require magento/module-elasticsearch-8 --with-all-dependencies
3) Run php bin/magento setup:install ................

### Expected result

Magento Installation should be successful

### Actual result

Magento Installation fails with below error.
**Could not validate a connection to Elasticsearch. Verify that the Elasticsearch host and port are configured correctly.**

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Eikzx** [comment] 2024-12-05 09:40
Hello,

I can confirm this behavior.

A quick fix would be to add `symfony/http-client version` in version 7.2.0 as a conflict in the composer.json.
<img width="386" alt="image" src="https://github.com/user-attachments/assets/bbc25bef-958d-4ee2-9a90-d39baf043a8c">
Running a `composer update `afterwards installs version 7.1.9 and `magento set:up `will go through.

Caution:
Removing 7.2.0 might break other parts so test everything, to be safe

**Comment by Bhavik-kumar** [comment] 2024-12-05 11:28
@magento
I think whole M2 community affecting with this composer update, who using ES8.

**Comment by cjayalmontecm** [comment] 2024-12-06 06:25
I have same issue. Did you find fix for this @kkhebbar89  ?

**Comment by novikor** [comment] 2024-12-09 12:49
Not sure whether that should be handled by the Magento, however - a temporary workaround is

Adding 
```
    "conflict": {
        "symfony/http-client": "7.2.0"
    },
```
To the project's root `composer.json`.

**Comment by Eikzx** [comment] 2024-12-16 13:32
@kkhebbar89 @engcom-Hotel 

Symfony released v7.2.1. (https://github.com/symfony/http-client/releases)
This fixes the initial issue for me.

Kind regards
Eike

**Comment by kkhebbar89** [comment] 2024-12-16 14:01
@Eikzx @engcom-Hotel 
Yeah symfony/http-client:7.2.1 fixes the issue.

**Comment by engcom-Bravo** [comment] 2024-12-18 05:23
@Eikzx Thanks for you Contribution!!.

Hi @kkhebbar89,

Thanks for your reporting and collaboration.

As per this comment https://github.com/magento/magento2/issues/39438#issuecomment-2545644845 we are closing this issue since issue was fixed.

Thanks.

**Closed as completed by engcom-Bravo** 2024-12-18 05:23 UTC
Labels: Issue: ready for confirmation, Reported on 2.4.x
