### ISSUE TITLE
Show empty / null value instead of 0(Zero) in minicart

### ISSUE THREAD

**Issue by mitul69** [magento/magento2#3631] opened 2016-03-03 12:22 UTC
Hello Team, 

I am working on the magento2 theme and I have problem with the minicart.

**Scenario.** 

When i open the page in Private Browsing / Quote no initialize at that time it show the empty value in minicart count. 

If i add product(s) in cart then i can see the number of the items in cart like 1, 2, 3 ...
after adding i remove all product from the cart then also i can see the 0 in Cart count. 

So main concern with the initial page load i cant see the Item counts in minicart.

Many thanks in advance.

Mitul Patel

**Comment by ishakhsuvarov** [comment] 2016-03-03 12:54
@mitul69 Hi, thank you for reporting this issue. Minicart should not show "0" in product count section. Please provide your Magento version (or branch you used to install) for us to investigate the issue.
Thank you.

**Comment by mitul69** [comment] 2016-03-03 13:12
Hello @ishakhsuvarov 

Thank you so much for your quick reply

Here is the link 
http://192.168.10.40:90/hoverboard/ you can check the issue.

**Comment by ishakhsuvarov** [comment] 2016-03-03 14:19
@mitul69 Unfortunately, the link you provided seems to lead to a server on your internal network, therefore I am unable to access it.

**Comment by mitul69** [comment] 2016-03-04 03:59
@ishakhsuvarov  sorry for the wrong link update

here is the new one : http://103.204.192.170/hoverboard/

**Comment by ishakhsuvarov** [comment] 2016-03-04 09:22
@mitul69 Thank you for the updated link. Looks like some css classes for the mini shipping cart are absent in your custom template.

Stock Luma theme:

``` html
<span class="counter qty empty" data-bind="css: { empty: cart().summary_count == 0 }, blockLoader: isLoading">...</span>
```

Your theme:

``` html
<span class="cart-title hidden-xs  empty" data-bind="css: { empty: cart().summary_count == 0 }, blockLoader: isLoading">...</span>
```

**Comment by mitul69** [comment] 2016-03-04 10:47
@ishakhsuvarov  thanks for your update,

Actually i have instigate the code and check the some time `cart().summary_count == empty`

So i have do following changes and its working fine

`<span class="cart-title empty"
              data-bind="css: { empty: cart().summary_count == 0 }, css: { empty: !cart().summary_count }, blockLoader: isLoading">`
I have added following 

 `css: { empty: !cart().summary_count }`

**Comment by ishakhsuvarov** [comment] 2016-03-04 11:12
@mitul69 Thanks for the update. Looks like the issue is fixed, so I'm closing this ticket. Feel free to reopen if you have more questions.

**Closed as completed by ishakhsuvarov** 2016-03-04 11:12 UTC

**Comment by NagamaniNaresh** [comment] 2016-06-21 15:40
Hi Team, For me also the same issue, I am using Magento2.0.7 and i have below code,

```
<span class="counter qty empty" data-bind="css: { empty: cart().summary_count == 0 }, blockLoader: isLoading">
            <span class="counter-number"><!-- ko text: cart().summary_count --><!-- /ko --></span>
        </span>
```

But it is not displaying 0 count when opened in Private Browser.

**Comment by KalaiarasanSeetharaman** [comment] 2016-10-04 14:14
Hi Team , 
I am using Magento 2.0.6
For me in minicart need to display the itemscount instead of cart().summary_count. How it is possible . Can suggest some way for me .....

**Comment by pboisvert** [comment] 2016-10-04 14:20
@KalaiarasanSeetharaman This issue is closed as fixed for the original issue. If you have a new issue please file a new ticket with full steps to reproduce.

**Comment by KalaiarasanSeetharaman** [comment] 2016-10-04 14:23
@pboisvert  Thanks
