### ISSUE TITLE
Redirect to secure_url removes url parameters (like "?product_list_limit=20")

### ISSUE THREAD

**Issue by fwolfst** [magento/magento2#12615] opened 2017-12-10 22:44 UTC
### Preconditions
1. Using magento 2.2.1
2. php, mysql and other libraries current from vanilla ubuntu 16.04
3. (not really necessary I GUESS) ssl-setup via nginx443->varnish80->nginx8080(magento)
4. secure and unsecure URL set to the https adress (we dont want unencrypted traffic except between varnish80 and nginx8080). That means magento2 will always ask the browser to visit us on https if nginx and varnish didnt tell magento that it was already spoken to via https.

### Steps to reproduce
1. see preconditions, then e.g. `curl --verbose --head --location http://yourshop/yourstuff/thestuff.html\?product_list_limit\=30` - note the http (not https) in the request
 -> this is a trivial example, loosing the product_list_limit is not so dramatic, but we actually deal with affiliate ids that are given as parameters ("?affiliate=me")

### Expected result
1. Magento answers with
`Location: https://yourshop/yourstuff/thestuff.html/?product_list_limit\=30`

### Actual result
1. Magento answers with
`Location: https://yourshop/yourstuff/thestuff.html/`
(missing **product_list_limit** or any other parameter at the end).

I guess one location where things go wrong is around here
./project-community-edition/vendor/magento/framework/App/Router/Base.php:372 and the `getRedirectUrl` implementation.

The unit test case should include cases where a parameter is given.

Probably this has side-effects or security consequences that I cannot overlook. In that case the parameters might have to be whitelisteable or the general behaviour could be made on/off-switcheable.

Probably this issue is related: https://github.com/magento/magento2/issues/12242 .

**Comment by fwolfst** [comment] 2017-12-15 08:55
If you want to have redirects working in a similar setting, the "trick" would be to to but nginx even more in front and let it do the redirection.

So, nginx 80 -> nginx 443 (just tls stuff) -> varnish (local, 8011 or whatever) -> nginx (local 8080, serving magento).

Still the original issue is not solved (and I am somewhat curious if there any security implications).

**Comment by magento-engcom-team** [comment] 2018-03-07 12:30
@fwolfst, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magenx** [comment] 2019-03-07 08:37
the problem in `http -> https` redirect in nginx ??

**Comment by magento-engcom-team** [comment] 2019-12-10 14:37
@fwolfst, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by pkocybik** [comment] 2022-02-25 07:44
Is there any chance of getting it fixed in the near future?

**Comment by tobiasolge** [comment] 2023-12-22 11:04
still not fixed.

**Comment by engcom-November** [comment] 2024-05-20 12:42
Hello @fwolfst,

Thank you for the report and collaboration!

We were not able to reproduce this on 2.4-develop.
Configured ssl, secure and unsecure URL is set to the https. But `?product_list_limit\=30` parameter was intact in the request.
Please take a look at the screenshot below:
<img width="1068" alt="image" src="https://github.com/magento/magento2/assets/60198231/b6c224f3-2bd1-43d1-ab6e-0f8c24314f35">

Below is the httpd-vhosts.conf
```
<VirtualHost *:443>
    DocumentRoot /opt/homebrew/var/www/magento7
    ServerName  local.magento7ce.com
    SSLEngine on
    SSLCertificateFile ...
    SSLCertificateKeyFile ...
    SSLCipherSuite ...
    <Directory "/opt/homebrew/var/www">
        AllowOverride all
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
   ServerName local.magento7ce.com
   Redirect / https://local.magento7ce.com/
</VirtualHost>
```

Please reverify the issue on latest 2.4-develop branch.

Thank you.

**Comment by engcom-November** [comment] 2024-06-04 11:37
Hello @fwolfst,

As there is no activity on this issue for a long time, we believe the issue has been resolved, hence closing this issue.
Feel free to raise a new issue or reopen this if you need more assistance.

Thank you.

**Comment by engcom-November** [comment] 2024-06-04 11:37
Hello @fwolfst,

As there is no activity on this issue for a long time, we believe the issue has been resolved, hence closing this issue.
Feel free to raise a new issue or reopen this if you need more assistance.

Thank you.

**Closed as completed by engcom-November** 2024-06-04 11:37 UTC
Labels: Triage: Dev.Experience, Priority: P3, Severity: S3, Progress: done, Issue: ready for confirmation, Issue: needs update, Area: Framework
