### ISSUE TITLE
Can not create creditmemo with not exists products

### ISSUE THREAD

**Issue by oleksiyzestlogic** [magento/magento2#38062] opened 2023-10-10 11:18 UTC
### Preconditions and environment

- Magento version is 2.4.6
- MSI

### Steps to reproduce

Add configurable product to cart
Place order
Change SKU for simple product from new order
Create Invoice and Shipping
Create Credit Memo

### Expected result

New credit memo page loaded and admin can create credit memo

### Actual result

Credit memo page is broken
Issue in logs:
main.CRITICAL: TypeError: Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor::execute(): Argument #1 ($productType) must be of type string, null given, called in /vendor/magento/module-inventory-sales/Model/GetProductSalableQty.php on line 108

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-10-11 05:54
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-10-11 07:40
Hi @oleksiyzestlogic,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible. Kindly refer the screenshots.

**Steps to reproduce**

- Add configurable product to cart
- Place order
- Change SKU for simple product from new order
- Create Invoice and Shipping
- Create Credit Memo


<img width="1485" alt="Screenshot 2023-10-11 at 12 26 47 PM" src="https://github.com/magento/magento2/assets/51680745/ba9b4905-bf27-44af-bb0e-24420450fe0c">




<img width="1497" alt="Screenshot 2023-10-11 at 12 26 56 PM" src="https://github.com/magento/magento2/assets/51680745/d08c070c-d342-48d5-a833-e3af7085c5fc">



We are able to do invoice and Credit memo after changing the product SKU.But for Shipment we are getting below error


<img width="1444" alt="Screenshot 2023-10-11 at 12 28 55 PM" src="https://github.com/magento/magento2/assets/51680745/10dfb1fc-76fb-4317-b6af-752b22c4f82a">



Could you please let us know if we are missing anything.

Thanks.

**Comment by oleksiyzestlogic** [comment] 2023-10-11 07:57
@engcom-Bravo thank you for your review
We do not have MSI on this Magento instance.

As you can see in description issue in log file is:
`main.CRITICAL: TypeError: **Magento\InventoryConfiguration**\Model\IsSourceItemManagementAllowedForProductType\Interceptor::execute(): Argument https://github.com/magento/magento2/issues/1 ($productType) must be of type string, null given, called in /vendor/magento/module-inventory-sales/Model/GetProductSalableQty.php on line 108`

Sure MSI is a separate project, But I have MSI after I install Magento out of the box.
Similar (but not the same) issue has been reported in MSI repo - https://github.com/magento/inventory/issues/3330

**Comment by engcom-Bravo** [comment] 2023-10-12 10:20
Hi @oleksiyzestlogic,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

We have verified the issue with MSI and Without MSI we are able to create Invoice and creditmemo.


**Without MSI**:

<img width="1412" alt="Screenshot 2023-10-12 at 12 13 08 PM" src="https://github.com/magento/magento2/assets/51680745/0322193e-0e63-4879-aacc-555ff95d57cb">




<img width="1444" alt="Screenshot 2023-10-12 at 12 13 14 PM" src="https://github.com/magento/magento2/assets/51680745/8aae0a7d-98da-416f-9b44-cc6b4c99e663">




**With MSI** :


<img width="1485" alt="Screenshot 2023-10-11 at 12 26 47 PM" src="https://github.com/magento/magento2/assets/51680745/e783f7ae-7f56-4716-bcf6-a984453e2041">



<img width="1497" alt="Screenshot 2023-10-11 at 12 26 56 PM" src="https://github.com/magento/magento2/assets/51680745/b5cdff84-2af3-4d86-8f32-05f113928d82">




https://github.com/magento/inventory/issues/3330 this issue has been different.

So i request to you to please try to reproduce the issue in Magento 2.4-develop Instance.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-10-23 05:30
Hi @oleksiyzestlogic,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-10-23 05:30 UTC
Labels: Issue: needs update, Reported on 2.4.6

**Comment by norgeindian** [comment] 2023-11-22 13:48
@engcom-Bravo , we have the same issue, but when the bought child product has been removed in the meantime.
Could you please check at which point your call stack differs?
```
2023-11-22T13:10:39.318418+00:00] .CRITICAL: TypeError: Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor::execute(): Argument #1 ($productType) must be of type string, null given, called in /var/www/share/example.url/releases/329/vendor/magento/module-inventory-sales/Model/GetProductSalableQty.php on line 108 and defined in /var/www/share/example.url/releases/329/generated/code/Magento/InventoryConfiguration/Model/IsSourceItemManagementAllowedForProductType/Interceptor.php:45
Stack trace:
#0 /var/www/share/example.url/releases/329/vendor/magento/module-inventory-sales/Model/GetProductSalableQty.php(108): Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor->execute(NULL)
#1 /var/www/share/example.url/releases/329/vendor/magento/module-inventory-sales/Model/GetProductSalableQty.php(75): Magento\InventorySales\Model\GetProductSalableQty->validateProductType('12345.11')
#2 /var/www/share/example.url/releases/329/vendor/magento/module-inventory-sales-admin-ui/Model/GetSalableQuantityDataBySku.php(105): Magento\InventorySales\Model\GetProductSalableQty->execute('12345.11', 2)
#3 /var/www/share/example.url/releases/329/vendor/magento/module-inventory-sales-admin-ui/Model/GetIsManageStockForProduct.php(95): Magento\InventorySalesAdminUi\Model\GetSalableQuantityDataBySku->execute('12345.11)
#4 /var/www/share/example.url/releases/329/vendor/magento/module-inventory-sales-admin-ui/Model/GetIsManageStockForProduct.php(66): Magento\InventorySalesAdminUi\Model\GetIsManageStockForProduct->getProductStockIds('12345.11)
#5 /var/www/share/example.url/releases/329/vendor/magento/module-inventory-sales-admin-ui/Plugin/Sales/Block/Items/Renderer/DefaultRenderer/ChildManageStockIsOn.php(59): Magento\InventorySalesAdminUi\Model\GetIsManageStockForProduct->execute('12345.11', 'en')
```
In this scenario `12345.11` is the SKU of the child product.

**Comment by norgeindian** [comment] 2023-11-23 08:58
@engcom-Bravo , I just tested on a clean Magento instance. It is actually reproducible:

- Create a configurable with one child
- Buy this one child and create an invoice for the order
- Remove the child product from the catalog
- Try to create a creditmemo for the order

**Comment by SamJUK** [comment] 2024-04-05 13:35
@engcom-Bravo @norgeindian Was there any outcome to this? We are seeing the same issue on a few stores.

```
[2024-04-05T13:10:03.541722+00:00] main.CRITICAL: TypeError: Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor::execute(): Argument #1 ($productType) must be of type string, null given, called in /vendor/magento/module-inventory-sales/Model/GetProductSalableQty.php on line 108 and defined in /generated/code/Magento/InventoryConfiguration/Model/IsSourceItemManagementAllowedForProductType/Interceptor.php:20
Stack trace:
#0 /vendor/magento/module-inventory-sales/Model/GetProductSalableQty.php(108): Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor->execute()
#1 /vendor/magento/module-inventory-sales/Model/GetProductSalableQty.php(75): Magento\InventorySales\Model\GetProductSalableQty->validateProductType()
#2 /vendor/magento/module-inventory-sales-admin-ui/Model/GetSalableQuantityDataBySku.php(105): Magento\InventorySales\Model\GetProductSalableQty->execute()
#3 /vendor/magento/module-inventory-sales-admin-ui/Model/GetIsManageStockForProduct.php(95): Magento\InventorySalesAdminUi\Model\GetSalableQuantityDataBySku->execute()
#4 /vendor/magento/module-inventory-sales-admin-ui/Model/GetIsManageStockForProduct.php(66): Magento\InventorySalesAdminUi\Model\GetIsManageStockForProduct->getProductStockIds()
#5 /vendor/magento/module-inventory-sales-admin-ui/Plugin/Sales/Block/Items/Renderer/DefaultRenderer/ChildManageStockIsOn.php(59): Magento\InventorySalesAdminUi\Model\GetIsManageStockForProduct->execute()
#6 /vendor/magento/framework/Interception/Interceptor.php(146): Magento\InventorySalesAdminUi\Plugin\Sales\Block\Items\Renderer\DefaultRenderer\ChildManageStockIsOn->afterCanReturnItemToStock()
#7 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Block\Adminhtml\Items\Renderer\DefaultRenderer\Interceptor->Magento\Framework\Interception\{closure}()
#8 /generated/code/Magento/Sales/Block/Adminhtml/Items/Renderer/DefaultRenderer/Interceptor.php(23): Magento\Sales\Block\Adminhtml\Items\Renderer\DefaultRenderer\Interceptor->___callPlugins()
#9 /var/view_preprocessed/pub/static/vendor/magento/module-sales/view/adminhtml/templates/order/creditmemo/create/items/renderer/default.phtml(1): Magento\Sales\Block\Adminhtml\Items\Renderer\DefaultRenderer\Interceptor->canReturnItemToStock()
```

**Comment by norgeindian** [comment] 2024-04-08 08:19
@SamJUK, no, the issue was kept closed.
