### ISSUE TITLE
Authorize.net module not visible on front end on checkout after upgrade to 2.3.5-p1

### ISSUE THREAD

**Issue by iamshy** [magento/magento2#28122] opened 2020-05-06 09:51 UTC
Failed to load the "AuthorizeNet_CreditCard/js/view/payment/method-renderer/creditcard" component in console error
### Preconditions (*)

1.Magento 2.3.5-p1
2.Magento 2 Authorize.net Marketplace module installed

### Steps to reproduce (*)

1.Enable Authorize.net module in admin
2.Enable 'Credit Card' payment method within Authorize.net

### Expected result (*)

1.User can see 'Credit Card' payment method in checkout, which uses the Authorize.net gateway

### Actual result (*)

1. Credit card method is not visible and a console error 
2.
![80795312-c34c7580-8bb9-11ea-9ad8-69f8d6273eae](https://user-images.githubusercontent.com/53165569/81163991-36d0f700-8fad-11ea-8906-2af524ae299e.png)

**Comment by sudheers-kensium** [comment] 2020-05-07 14:21
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-07 14:21
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by Mty95** [comment] 2020-05-07 19:19
@magento give me a 2.4 develop instance

**Comment by VigneshVenkatesan154** [comment] 2020-05-28 09:06
@iamshy As per Magento the authorize .net integration will be removed in Magento 2.4.0 release and available as extension So the issue is not valid. Closing the issue.

Please go through the below link.
https://docs.magento.com/user-guide/payment/authorize-net-direct-post.html

**Closed as completed by VigneshVenkatesan154** 2020-05-28 09:06 UTC
Labels: Issue: Format is valid, Reported on 2.3.5-p1
