### ISSUE TITLE
Magento 2.4.3p1 gift message option doesn't show for items in cart when using product customizable options

### ISSUE THREAD

**Issue by DomPixie** [magento/magento2#35110] opened 2022-02-15 23:35 UTC
### Preconditions (*)
1. Magento 2.4.3p1

### Steps to reproduce (*)
1. Create simple product with customizable options
2. Create simple product without customizable options
3. Stores > Settings > Configuration > Gift Options. Set the gift message options to *Allow Gift Messages for Order Items - yes*
4. Add both SKUs to cart
5. View Cart

### Expected result (*)
1. Have option to edit Gift Options under both SKUs

### Actual result (*)
1. Can only edit Gift Options under SKU without customizable options

![image](https://user-images.githubusercontent.com/94372161/154167795-ea620ec7-f2ee-4177-942f-1bc0f5241420.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment] 2022-02-16 13:42
Hi @DomPixie,

Thank you for reporting the issue.
We tried to reproduce the issue on Magento 2.4-develop branch but the issue is not reproducible.

Steps performed:

1. Create one simple product with customisable options
2. Create another simple product without customisable options
3. **Stores > Settings > Configuration > sales>Gift Options**. Set the gift message options to **Allow Gift Messages for Order Items** to **Yes**
4. Add both SKUs to cart
5. View Cart

**Result:**
Have option to edit Gift Options under both SKUs as shown under below screenshot
![35110](https://user-images.githubusercontent.com/60198022/154276459-3efd6247-918a-4caf-bfe6-21808bf9d28a.png)

Please let me know if this is exactly what your issue was or if there is some more configuration required from my end. Will update accordingly.

Thanks

**Comment by engcom-Hotel** [comment] 2022-03-02 14:01
Dear @DomPixie,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-03-02 14:01 UTC
Labels: Issue: needs update

**Comment by hgati** [comment] 2024-03-11 13:19
There is a possibility that the "allow gift message" option is unchecked on the product modification page.

![010](https://github.com/magento/magento2/assets/6913728/0bc95415-5f14-4042-883b-4df40df75808)
