### ISSUE TITLE
Layered Navigation: “Equalize product count” not working as expected

### ISSUE THREAD

**Issue by trinitecDev** [magento/magento2#21960] opened 2019-03-27 08:50 UTC
### Preconditions (*)
2.2.7

### Steps to reproduce (*)
Create a custom attribute of type price.
Got to Stores > Configuration > Catalog > Layered Navigation and set “price navigation step calculation” to “Automatic (equalize product counts)”
![grafik](https://user-images.githubusercontent.com/48954244/55061363-debe8600-5073-11e9-912f-3d361ea7e891.png)

### Expected result (*)
I would expect ten ranges with equalized product counts (as the name suggests).

### Actual result (*)
Result is not equal ranges but one in the end with half of the products in it:
![grafik](https://user-images.githubusercontent.com/48954244/55061984-504b0400-5075-11e9-82f2-ef6cfe307227.png)
Whats also weird is the last to -0.01 value, since the lowest value is 250 and the highest 6000 (i checked that in the catalog_product_entity_decimal table).

**Comment by magento-engcom-team** [comment] 2019-03-27 08:50
Hi @trinitecDev. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@trinitecDev do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-03-27 08:52
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-03-27 10:08
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98880`, `MAGETWO-98881` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-03-27 12:31
Hi @Nazar65. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-04-20 17:20
Hi @trinitecDev. Thank you for your report. 
The issue has been fixed in magento/magento2#21968 by @Nazar65 in 2.3-develop branch
Related commit(s):
 - [7cb0cf8dc21612761b9e58de600447c12ef340dd](https://github.com/magento/magento2/commit/7cb0cf8dc21612761b9e58de600447c12ef340dd)
 - [bbe71ef43062429cd3f235ad885cc3a996e7628d](https://github.com/magento/magento2/commit/bbe71ef43062429cd3f235ad885cc3a996e7628d)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-04-20 17:20 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, good first issue

**Comment by magento-engcom-team** [comment] 2019-04-23 19:48
Hi @trinitecDev. Thank you for your report. 
The issue has been fixed in magento/magento2#22453 by @Nazar65 in 2.2-develop branch
Related commit(s):
 - [34b2dccf322c1af0d5c563063e439de1b4a9cbe9](https://github.com/magento/magento2/commit/34b2dccf322c1af0d5c563063e439de1b4a9cbe9)

The fix will be available with the upcoming 2.2.9 release.
