### ISSUE TITLE
M2 hamburger menu incompatible with recent versions of Android browsers.

### ISSUE THREAD

**Issue by n2diving-dgx** [magento/magento2#36050] opened 2022-08-29 14:21 UTC
### Preconditions and environment

The "hamburger" menu that is displayed in the upper left hand corner of the Luma theme (and thus any theme derived from the Luma Theme, such as ours) in vertical orientation does not function correctly for navigating to subcategories on Android smartphones.  However, on a classic PC desktop with Windows then simply resizing the browser window to very narrow such that the hamburger menu appears, the desktop version does function as expected when the hamburger menu items are moused over and hovered.  This issue seems to be a compatibility issue with recent versions of Android only... the theme works as expected on iOS devices.   This issue is reproduceable on recent Android smartphones and appears to be independent of the browser used. 

### Steps to reproduce

(1) Clean installation of M2.4.5 with Luma theme and store sample data.
(2) Open the website home page using a recent version of the Chrome browser on an Android mobile device
(3) Observe that touching the "hamburger" navigation icon displays the list of store sample data categories

### Expected result

Able to navigate to sub-categories using the hamburger menu on Android devices.

### Actual result

Using the responsive navigation menu on Android devices, touching those categories which have subcategories (i.e. "WOMEN", "MEN", "GEAR" and "TRAINING") are completely non-functional.  Touching those four does not expose a list of the sub-categories, indeed nothing at all happens making it **impossible to navigate to those categories and their subcategories using responsive navigation on Android mobile devices with M2.4.5 (and M2.4.4)**

### Additional information

The issue seems to be that at some point in recent updates, the Magento code that drives responsive navigation has become incompatible with Android based browsers.    This issue was reproduced using a Samsung S22+ mobile phone, Android 12, Chrome 104.0.5112.97 and Firefox 98.0.1 as well as some other Android phones and browsers.  Although, common iOS browsers on iPhone devices such as Safari, Chrome and Firefox do work as expected.  The issue was first reported on our production website following an upgrade to M2.4.5 and Php 8.1, but possibly was present on 2.4.4 and Php 7.4 version.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by JKetelaar** [comment] 2022-08-29 22:35
Same issue here

**Comment by JKetelaar** [comment] 2022-08-30 00:33
Fixed with
https://github.com/magento/magento2/issues/35329#issuecomment-1139618176

**Comment by engcom-Lima** [comment] 2022-09-28 06:37
@magento give me 2.4.5 instance

**Comment by engcom-Lima** [comment] 2022-09-28 07:10
Hi @n2diving-dgx ,

Thanks for contribution and collaboration.

This issue is duplicate of  this issue https://github.com/magento/magento2/issues/35329
Hence, closing this issue as duplicate.

Thanks

**Closed as completed by engcom-Lima** 2022-09-28 07:10 UTC
Labels: duplicate, Issue: ready for confirmation, Reported on 2.4.5

**Comment by schossler** [comment] 2022-12-17 18:43
> Fixed with [#35329 (comment)](https://github.com/magento/magento2/issues/35329#issuecomment-1139618176)

this fix not working in M2.4.5-p1

**Comment by dennismetz** [comment] 2023-01-25 08:59
Any updates on this issue?

**Comment by hostep** [comment] 2023-01-29 14:26
@dennismetz: does [this comment](https://github.com/magento/magento2/issues/35329#issuecomment-1380867451) help?

**Comment by dennismetz** [comment] 2023-01-30 15:38
@hostep Hi, unfortunately not - I've tried everything, only under 2.4.5-p1 it doesn't work.
