### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by marvincaspar** [magento/magento2#2538] opened 2015-11-27 08:59 UTC
Hi,

I just installed magento 2 with sample data and try to search for a product. After starting the search, mysql has a query which now is running over 27 minutes and it is still running.

Here the query:

``` sql
INSERT INTO `search_tmp_5658146c0b72c8_28632618` SELECT `main_select`.`entity_id`, MAX(score) AS `relevance` FROM (SELECT `search_index`.`entity_id`, ((0) + LEAST((MATCH (data_index) AGAINST ('back*' IN BOOLEAN MODE)), 1000000) * POW(2, search_weight)) AS `score` FROM `catalogsearch_fulltext_scope1` AS `search_index`
 LEFT JOIN `catalog_eav_attribute` AS `cea` ON search_index.attribute_id = cea.attribute_id
 LEFT JOIN `cataloginventory_stock_status` AS `stock_index` ON search_index.entity_id = stock_index.product_id AND stock_index.website_id = '1' WHERE (stock_index.stock_status = 1) AND (MATCH (data_index) AGAINST ('back*' IN BOOLEAN MODE))) AS `main_select` GROUP BY `entity_id` ORDER BY `relevance` DESC LIMIT 10000 /* statement may be truncated */
```

**Comment by jamescowie** [comment] 2015-11-27 14:58
Hello @mc388 Are you able to provide any more information such as what version you are using, MySQL version etc. I will try and replicate the issue and report back

**Comment by marvincaspar** [comment] 2015-11-27 16:37
Magento 2 EE, MySQL 5.7.x, PHP 5.6.x-fpm

Currently no redis and no solr

**Comment by choukalos** [comment] 2015-11-29 19:27
That's odd - looks like the query that builds the catalog search index.  Can you provide some insight on the timing of that query - i.e. when did the search fire relative to cron running to build the catalog search index would be helpful for us to understand if there's a race condition during index creation.

Also please try killing that query in mysql ( i.e. show process list; kill {process#} }, run cron twice and then try searching and let us know if your still seeing an issue.  

Thanks!

**Comment by kandy** [comment] 2015-11-29 20:53
Looks like MySql 5.7 related issue. Can you try reproduce it on MySql 5.6?

**Comment by marvincaspar** [comment] 2015-11-30 07:13
Yes, it is a MySql 5.7 issue. I changed the docker container to 5.6, reinstall Magento and now it works fine.

Please fix the search for MySql 5.7

**Comment by choukalos** [comment] 2015-11-30 14:59
Created issue - MAGETWO-46201 to track internally.  Lower priority as MySQL 5.6 is still in the process of being adopted by major distributions.

**Comment by robfico** [comment] 2016-02-03 19:28
fyi, seeing this same issue with PHP 7.0.2 and MySQL 5.7.10. MySQL 5.7 is GA, and recommended version by MySQL. Cannot search as original author stated. Is this slated to be fixed? Any quick workaround?

**Comment by kandy** [comment] 2016-02-27 23:49
As workaround you can apply patch

```
Index: lib/internal/Magento/Framework/Search/Adapter/Mysql/Mapper.php
===================================================================
--- lib/internal/Magento/Framework/Search/Adapter/Mysql/Mapper.php  (date 1456520676000)
+++ lib/internal/Magento/Framework/Search/Adapter/Mysql/Mapper.php  (revision )
@@ -159,7 +159,7 @@
     {
         $parentSelect = $this->getConnection()->select();
         $parentSelect->from(
-            ['main_select' => $select],
+            ['main_select' => $select->limit(10000000000)],
             [
                 $this->entityMetadata->getEntityId() => 'entity_id',
                 'relevance' => sprintf('MAX(%s)', $scoreBuilder->getScoreAlias())
```

**Comment by EmilyPepperman** [comment] 2016-04-25 19:35
Hi Kandy... I am a bit new to M2 can you help with a little more instruction on how to apply your patch for this issue?

**Comment by maghamed** [comment] 2016-05-25 13:23
@EmilyPepperman and @mc388 could you please provide exact version of MySQL on which you reproduce the bug? Because on our infrastructure Search works as expected. Seems that was a MySQL bug which has been fixed in one of the MySQL releases.

**Comment by robfico** [comment] 2016-05-25 16:23
ok, we upgraded from MySQL 5.7.10 to latest 5.7.12, and the search now completes without any issue. Looks like MySQL fixed a bug that Magento was triggering previously.  :)

**Comment by EmilyPepperman** [comment] 2016-05-25 19:09
This morning upgraded MySQL to 5.7.12 and all is well! @maghamed

**Comment by daim2k5** [comment] 2016-05-25 20:16
@mc388 did you tried the MySQL to 5.7.12 ?

**Comment by marvincaspar** [comment] 2016-06-01 12:45
@daim2k5 we switched back to mysql 5.6.

**Comment by piotrekkaminski** [comment] 2016-08-30 19:32
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Search-not-working/idi-p/46478).

**Closed as completed by piotrekkaminski** 2016-08-30 19:32 UTC
Labels: Issue: Ready for Work, improvement, Component: Search

**Comment by choukalos** [comment] 2016-09-19 14:12
Update; we're now working in mainline with 5.7.12+
