### ISSUE TITLE
Cron performance issue after upgrading 2.3.2 to 2.3.3

### ISSUE THREAD

**Issue by vincentteyssier** [magento/magento2#25593] opened 2019-11-14 05:27 UTC
Start state:
PHP7.2
Magento 2.3.2 Open Source Vanilla installation
Ubuntu 18.04

I install Netdata to monitor CPU usage and can see my cron running every minute impacting CPU as follow : 
![2 3 2-fpm7 2](https://user-images.githubusercontent.com/16136533/68828864-0b4a0f80-06e2-11ea-85c7-64ca8d8e34f0.PNG)

I then upgrade to 2.3.3 by command line following instructions on : 
[https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html](https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html)

No more changes and netdata reports as follow:
![2 3 3-fpm7 2](https://user-images.githubusercontent.com/16136533/68828947-4b10f700-06e2-11ea-8ed7-6ab0a27bd296.PNG)

I have also tried upgrading to php7.3 and php-fpm 7.3 but no change in performance.

**Comment by Yuwei9291** [comment] 2019-11-18 10:50
Clean install, same issue.

**Comment by vincentteyssier** [comment] 2019-11-19 03:09
Just as a precision, on a t2.medium instance I observe the following run time for the cron job running every minute:
Clean Magento 2.3.2: 1s
Clean Magento 2.3.3: 3.5s
Upgraded magento 2.3.2 to 2.3.3: 9s

**Comment by jorgb90** [comment] 2019-11-19 11:03
A lot of users are reporting cron issues since 2.3.3.. This should get some priority!

**Comment by engcom-Charlie** [comment] 2019-11-19 14:55
Hello, everyone!
I am closing this issue as a duplicate of https://github.com/magento/magento2/issues/25634, because i prefer to confirm 25634(this issue includes more clear description).

Thank you all for contribution and collaboration!

**Closed as completed by engcom-Charlie** 2019-11-19 14:55 UTC
Labels: duplicate, Issue: Format is not valid
