### ISSUE TITLE
MSI Bundle issue: parent needs Default source Qty to auto change to "In stock" when Default source not used

### ISSUE THREAD

**Issue by ivagarfitt** [magento/magento2#37684] opened 2023-06-28 16:23 UTC
### Preconditions and environment

- Magento version 2.4.5-p2 Adobe commerce cloud

### Steps to reproduce

1. Enable MSI
2. Create Stock sources and assign them to stores
3. Leave Default source but do not assign it to any store
4. Set all Default Quantities to 0 and leave Stock Status to "true/In stock"
5. Update stock regularly for other sources

### Expected result

Bundle product parent that had Stock status auto changed to "Out of stock" to auto change to "In Stock" when children product updated with positive Qty.

### Actual result

Bundle product parent that was auto changed to "Out of stock" not auto changing to "In stock" when all children having positive stock.

Reason:
Bundle product status only auto change to "In stock" when positive Qty is added to Default source against the parent!

### Additional information

Default source Qty not impacting children Stock status because if we update Qty using inventory/sorce-items API status is properly updated.

However status update for the parent using same API does nothing if Default source is having Qty=0

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ivagarfitt** [comment] 2023-06-28 17:16
@magento give me 2.4.5-p2 instance

**Comment by ivagarfitt** [comment] 2023-06-28 19:36
@magento give me 2.4.5-p2 instance

**Comment by ivagarfitt** [comment] 2023-06-29 07:53
@magento give me 2.4.5-p2 instance

**Comment by engcom-Bravo** [comment] 2023-07-03 12:38
Hi @ivagarfitt,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Enable MSI
- Create Stock sources and assign them to stores
- Leave Default source but do not assign it to any store
- Set all Default Quantities to 0 and leave Stock Status to "true/In stock"
- Update stock regularly for other sources


As per Magento devdocs https://experienceleague.adobe.com/docs/commerce-admin/inventory/quantities/quantities-assign-per-product.html?lang=en. After adding [sources](https://experienceleague.adobe.com/docs/commerce-admin/inventory/quantities/sources-assign-per-product.html?lang=en), update the inventory quantities for your product. These values track the on-hand, available stock amounts.We have to update stock status even though if we set Set all Default Quantities to 0 the child product will be in instock only we have to make it as out of stock after the parent bundle product will go to out of stock.


Thanks

**Comment by ivagarfitt** [comment] 2023-07-03 12:40
Have you tested for a Bundle parent product?

**Comment by ivagarfitt** [comment] 2023-07-03 16:23
I can see that is looking fixed in 2.4.6
![image (49)](https://github.com/magento/magento2/assets/1512371/31f964be-0c78-477b-81f3-f4968d7de042)

**Comment by engcom-Bravo** [comment] 2023-07-11 06:14
Hi @ivagarfitt,

Thanks for your update.

We have verified for Bundle Parent product also it is working as expected.As per comment https://github.com/magento/magento2/issues/37684#issuecomment-1618830558 the seems to be fixed please let us know can we close this issue?


Thanks.

**Comment by engcom-Bravo** [comment] 2023-07-24 05:36
Hi @ivagarfitt,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-07-24 05:36 UTC
Labels: Issue: needs update, Reported on 2.4.5-p2
