### ISSUE TITLE
Can not save an inactive Admin User that has no access tokens generated 

### ISSUE THREAD

**Issue by dpoltoratsky** [magento/magento2#16513] opened 2018-07-03 18:11 UTC
### Preconditions
1. Magento version 2.2.3
2. An inactive Admin User that has no access tokens generated

### Steps to reproduce
1. Log in to Admin Panel
2. Navigate to "System" -> "Permissions" -> "All Users"
3. Click on the inactive Admin User
4. Click "Save User"

### Expected result
1. The Admin User is successfully saved

### Actual result
1. The Admin User is not saved
2. Following error message is shown:
> This user has no tokens.

**Comment by magento-engcom-team** [comment] 2018-07-03 18:11
Hi @dpoltoratsky. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@dpoltoratsky do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment] 2018-07-04 08:37
Hello @dpoltoratsky, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2019-04-18 23:10
Hi @dpoltoratsky. Thank you for your report. 
The issue has been fixed in magento/magento2#20772 by @mage2pratik in 2.3-develop branch
Related commit(s):
 - [4c71a227680c0ff48e3f2a02e7567e46de3664d8](https://github.com/magento/magento2/commit/4c71a227680c0ff48e3f2a02e7567e46de3664d8)
 - [b159dfb6004281991de5ee3f80936d69e65fe5ed](https://github.com/magento/magento2/commit/b159dfb6004281991de5ee3f80936d69e65fe5ed)
 - [ce4af9e43627d6d31acb0cb5a8a841e81a830a82](https://github.com/magento/magento2/commit/ce4af9e43627d6d31acb0cb5a8a841e81a830a82)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-04-18 23:10 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Integration
