### ISSUE TITLE
REST API :  Search Criteria Filters not working for Product Repository GetList 

### ISSUE THREAD

**Issue by mack4hack** [magento/magento2#29126] opened 2020-07-14 10:46 UTC
### Description
SearchCriteria filters not working on a Product Attribute which is used while creating a Configurable Product.
Visibility filter applied to show only Visible products in product list.

### Preconditions (*)
1. Magento 2.4
2. Enable 'Allow Anonymous Guest Access' from Store -> Configuration -> Services -> Magento Web API

### Steps to reproduce (*)
1. **Create a Configurable Product**

![Screenshot from 2020-07-14 15-44-06](https://user-images.githubusercontent.com/11089409/87414185-029b3780-c5e9-11ea-8dc2-cc3b4ae4e0ff.png)

2. **GET** :  /rest/V1/products?searchCriteria[filterGroups][0][filters][0][field]=category_id&searchCriteria[filterGroups][0][filters][0][value]=33&searchCriteria[filterGroups][1][filters][0][field]=visibility&searchCriteria[filterGroups][1][filters][0][value]=2&searchCriteria[filterGroups][1][filters][0][conditionType]=eq&searchCriteria[filterGroups][1][filters][1][field]=visibility&searchCriteria[filterGroups][1][filters][1][value]=4&searchCriteria[filterGroups][1][filters][1][conditionType]=eq&searchCriteria[filterGroups][2][filters][1][field]=mycolor&searchCriteria[filterGroups][2][filters][1][value]=5431

![image](https://user-images.githubusercontent.com/11089409/87422667-ab9c5f00-c5f6-11ea-9fd4-d9ee2da50b6b.png)

### Expected result (*)
1.  **Must Return Parent Product with attribute "mycolor" is set** 

![image](https://user-images.githubusercontent.com/11089409/87416082-cd441900-c5eb-11ea-8acc-166c26798bd9.png)

### Actual result (*)
1. **No Items in the response**

![image](https://user-images.githubusercontent.com/11089409/87422835-f74f0880-c5f6-11ea-87e1-7043a0ed2efc.png)

![Screenshot from 2020-07-14 17-45-41-1](https://user-images.githubusercontent.com/16210367/87427661-c2df4a80-c5fe-11ea-8d39-d34cec29a4e1.png)
![Screenshot from 2020-07-14 17-45-54](https://user-images.githubusercontent.com/16210367/87427664-c4a90e00-c5fe-11ea-8edd-63409e17fe12.png)
![Screenshot from 2020-07-14 17-42-54-1](https://user-images.githubusercontent.com/16210367/87427668-c541a480-c5fe-11ea-81bb-6c7521ae4b35.png)
---

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by RanjitBShinde** [comment] 2020-07-14 11:04
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-07-14 11:04
Hi @RanjitBShinde. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-07-14 11:06
Hi @RanjitBShinde, here is your [Magento instance](https://i-29126-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29126-2-4-develop.instances.magento-community.engineering/admin_aba9](https://i-29126-2-4-develop.instances.magento-community.engineering/admin_aba9)
Login: `095533f1` Password: `1fafce6de901`
Instance will be terminated in up to 3 hours.

**Comment by RanjitBShinde** [comment] 2020-07-14 12:51
The issue is reproducible in Magento 2.4 develop instance

Please find the attachment below

![Screenshot from 2020-07-14 17-45-41-1](https://user-images.githubusercontent.com/16210367/87427661-c2df4a80-c5fe-11ea-8d39-d34cec29a4e1.png)
![Screenshot from 2020-07-14 17-45-54](https://user-images.githubusercontent.com/16210367/87427664-c4a90e00-c5fe-11ea-8edd-63409e17fe12.png)
![Screenshot from 2020-07-14 17-42-54-1](https://user-images.githubusercontent.com/16210367/87427668-c541a480-c5fe-11ea-81bb-6c7521ae4b35.png)

**Comment by magento-engcom-team** [comment] 2020-07-17 14:13
:white_check_mark: Confirmed by @engcom-Lima 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35975` were created

**Issue Available**: @engcom-Lima, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Lima** [comment] 2020-07-20 15:57
Hello @mack4hack 
Please verify this steps:
1 Create configurable product with two child products 
2 Open child product
![Screenshot_35](https://user-images.githubusercontent.com/60198022/87955586-9f147c80-cab6-11ea-958d-47ee0d71f5f4.png)

![Screenshot_36](https://user-images.githubusercontent.com/60198022/87955530-8dcb7000-cab6-11ea-9af5-9103d2708dfe.png)

![Screenshot_37](https://user-images.githubusercontent.com/60198022/87955772-d97e1980-cab6-11ea-95e6-bda3346da21d.png)
Visible in both childs are 1 and value of the "my_color" is 5 and 4 respectively
3 Open the parent product
![Screenshot_38](https://user-images.githubusercontent.com/60198022/87956605-ecddb480-cab7-11ea-8025-382186e8b076.png)
**Result**
my_color attrebute is disabled. So it`s impossible to change the value or add it. 

It`s impossible to get this value because it is equals to `null`
Its can be checked in` \Magento\Catalog\Model\ProductRepository.php:631`. Just add `$collection->getSelect(0->__toString()` there.

**Comment by mack4hack** [comment] 2020-07-21 06:01
@engcom-Lima I checked the steps you provided and found as it is, as you mentioned. 
But I would like to know how can I filter products according to attributes assigned to its child parents.

Like in the frontstore.

**Available Filter**
![Screenshot from 2020-07-21 11-24-57](https://user-images.githubusercontent.com/11089409/88018457-6374c380-cb45-11ea-80b1-7d79c4ca3f73.png)

**Filter Applied**
![Screenshot from 2020-07-21 11-25-16](https://user-images.githubusercontent.com/11089409/88018471-6a9bd180-cb45-11ea-90ac-35291f42133e.png)

**Comment by engcom-Lima** [comment] 2020-07-21 07:58
Hello @mack4hack 
[Step 2](https://github.com/magento/magento2/issues/29126#issue-656517118)
![image_2020_07_21T07_48_06_450Z](https://user-images.githubusercontent.com/60198022/88027905-9a94a600-cb40-11ea-9373-99673ec7f500.png)
1 - it`s vizability 
4 - it`s attribute value
![Screenshot_37](https://user-images.githubusercontent.com/60198022/88028255-1262d080-cb41-11ea-83cd-e6cd4c106078.png)

**Comment by mack4hack** [comment] 2020-07-21 08:07
> The issue is reproducible in Magento 2.4 develop instance
> 
> Please find the attachment below
> 
> ![Screenshot from 2020-07-14 17-45-41-1](https://user-images.githubusercontent.com/16210367/87427661-c2df4a80-c5fe-11ea-8d39-d34cec29a4e1.png)
> ![Screenshot from 2020-07-14 17-45-54](https://user-images.githubusercontent.com/16210367/87427664-c4a90e00-c5fe-11ea-8edd-63409e17fe12.png)
> ![Screenshot from 2020-07-14 17-42-54-1](https://user-images.githubusercontent.com/16210367/87427668-c541a480-c5fe-11ea-81bb-6c7521ae4b35.png)

@engcom-Lima Please refer this comment where "attribute value = 4"  is used on Magento 2.4 develop instance

Also Visibility is set to 2/4 because I want to only Parent Products in the Product Listing.
I am aware that child products have visibility = 1 (Not Visible Individually)

**Comment by engcom-Lima** [comment] 2020-07-21 08:35
@mack4hack 
If the [visibility](https://docs.magento.com/user-guide/system/data-attributes-product.html) is set to 2, it means that the product will not appear in the search.

**Comment by engcom-Lima** [comment] 2020-07-21 08:39
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-07-21 08:39
Hi @engcom-Lima. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-07-21 08:40
Hi @engcom-Lima, here is your [Magento instance](https://i-29126-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29126-2-4-develop.instances.magento-community.engineering/admin_6c27](https://i-29126-2-4-develop.instances.magento-community.engineering/admin_6c27)
Login: `3f6708ca` Password: `0f42a0d3ac77`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Lima** [comment] 2020-07-21 10:54
@mack4hack 
See my steps

1. Create category (id will be 33)
2. Create a configurable product with `Attribute set 1` (because this is the only set of attributes where we can find the `mycolor` attribute)
3. Create configurations for the configurable product with the `mycolor` attribute
4. Check if the `mycolor` attribute Searchable and Filterable (with results) 
 ![Screenshot_40](https://user-images.githubusercontent.com/60198022/88042546-c15cd780-cb54-11ea-9678-bcdbc0768600.png)
5. Fill in all information -> Save
6. Open the parent product (Visibility is 4)
 ![Screenshot_41](https://user-images.githubusercontent.com/60198022/88042911-5e1f7500-cb55-11ea-9f2b-ae2a16055e8a.png)
7. Open child product (Visibility is 1 and attribute value is 4 )
![Screenshot_42](https://user-images.githubusercontent.com/60198022/88043105-ad65a580-cb55-11ea-9f38-f2155f6935c6.png)
![Screenshot_43](https://user-images.githubusercontent.com/60198022/88043236-da19bd00-cb55-11ea-8a9e-84d2058427e6.png)

Run API request 

`/rest/default/V1/products?searchCriteria%5BfilterGroups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bfield%5D=category_id&searchCriteria%5BfilterGroups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bvalue%5D=33&searchCriteria%5BfilterGroups%5D%5B1%5D%5Bfilters%5D%5B0%5D%5Bfield%5D=visibility&searchCriteria%5BfilterGroups%5D%5B1%5D%5Bfilters%5D%5B0%5D%5Bvalue%5D=1&searchCriteria%5BfilterGroups%5D%5B1%5D%5Bfilters%5D%5B0%5D%5BconditionType%5D=eq&searchCriteria%5BfilterGroups%5D%5B2%5D%5Bfilters%5D%5B1%5D%5Bfield%5D=mycolor&searchCriteria%5BfilterGroups%5D%5B2%5D%5Bfilters%5D%5B1%5D%5Bvalue%5D=4`
**Result**
![Peek 2020-07-21 13-31](https://user-images.githubusercontent.com/60198022/88044432-bd31b980-cb56-11ea-8d90-6ec39b4ce7c8.gif)

To find parent product run
`rest/default/V1/products?searchCriteria%5BfilterGroups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bfield%5D=category_id&searchCriteria%5BfilterGroups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bvalue%5D=33&searchCriteria%5BfilterGroups%5D%5B1%5D%5Bfilters%5D%5B0%5D%5Bfield%5D=visibility&searchCriteria%5BfilterGroups%5D%5B1%5D%5Bfilters%5D%5B0%5D%5Bvalue%5D=4&searchCriteria%5BfilterGroups%5D%5B1%5D%5Bfilters%5D%5B0%5D%5BconditionType%5D=eq`

**Result**
![Peek 2020-07-21 13-47](https://user-images.githubusercontent.com/60198022/88046856-5c57b080-cb59-11ea-9ccb-9437125af1d6.gif)

**Note** In parent product `mycolor` attribute is disabled

**Comment by engcom-Lima** [comment] 2020-07-21 11:54
> @engcom-Lima I checked the steps you provided and found as it is, as you mentioned.
> But I would like to know how can I filter products according to attributes assigned to its child parents.
> 
> Like in the frontstore.
> 
> **Available Filter**
> ![Screenshot from 2020-07-21 11-24-57](https://user-images.githubusercontent.com/11089409/88028157-e9006f80-cb55-11ea-86b0-cddb7fb950b1.png)
> 
> **Filter Applied**
> ![Screenshot from 2020-07-21 11-25-16](https://user-images.githubusercontent.com/11089409/88028180-f0c01400-cb55-11ea-95b2-3441e53f72a5.png)

Simple. You can create two requests and combine them programmerly 
Firstly find child product and then using this information find parent product.

**Comment by engcom-Lima** [comment] 2020-07-21 12:25
@mack4hack 
Can this issue be closed? Because programming it is not related to this ticket

**Comment by mack4hack** [comment] 2020-07-21 12:34
> 
> @mack4hack
> Simple. You can create two requests and combine them programmerly
> Firstly find child product and then using this information find parent product.

@engcom-Lima So you mean to say that we cannot filter parent products with the attributes used while creating a child product with core Product Repository getList() ?

**Comment by mack4hack** [comment] 2020-07-21 14:55
@engcom-Lima checked with provided link, but didn't find it useful in my case.

I just want to achieve the same via Product List API which is done in storefront.

![screencast-appgototrainingcom-20 (1)](https://user-images.githubusercontent.com/11089409/88070430-4ca78e80-cb90-11ea-9853-413f49715bc8.gif)

**Comment by engcom-Lima** [comment] 2020-07-21 20:16
@mack4hack 
Try using the information given in [this comment](https://github.com/magento/magento2/issues/29126#issuecomment-661810518). But it's not related to this ticket.

**Comment by engcom-Lima** [comment] 2020-07-24 15:12
@mack4hack 
Closed as discussed in [this](https://github.com/magento/magento2/issues/29126#issuecomment-661127780) and [this](https://github.com/magento/magento2/issues/29126#issuecomment-661785687) comments

**Closed as completed by engcom-Lima** 2020-07-24 15:12 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Format is valid, Component: Api, Triage: Dev.Experience, Reported on 2.4.0

**Comment by hari-codilar** [comment] 2021-09-06 15:08
This issue is still there in 2.4.2
The rest API should provide the parent product that matches the child product as rendered on fronted
