### ISSUE TITLE
Product is visible & in stock although salable quantity = 0

### ISSUE THREAD

**Issue by SchranzKatharina** [magento/magento2#31267] opened 2020-12-11 15:44 UTC
### Preconditions (*)

1. Magento 2.4.1

### Steps to reproduce (*)

1. 'Display Out of Stock Products' is set to "No"
2. Buy the entire available number of a product so that the salable quantity is 0.
3. The quantity of the product is still not null, because the product was not shipped yet.

### Expected result (*)

1. The product is not longer visible on frontend.

### Actual result (*)

1. The product is visible as 'In Stock' on frontend.
2. If the user clicks "Add to Cart" an error message shows "not available".

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2020-12-14 09:55
Hello @SchranzKatharina 

Thank you for your report.

This issue is a Duplicate of #31117. Please, see all the future updates in that issue 

Thank you

**Closed as completed by engcom-Bravo** 2020-12-14 09:55 UTC
Labels: Issue: ready for confirmation
