### ISSUE TITLE
Is version 2.4.3 unavailable via composer ?

### ISSUE THREAD

**Issue by Sartoric** [magento/magento2#34026] opened 2021-09-08 11:19 UTC
### Preconditions (*)

I'm not sure it can be classified as bug, but not even as a general discussion
I'm trying to update an existing magento 2.4.2 via composer but it seems I can't find 2.4.3

### Steps to reproduce (*)

if i run, as per manual 

`composer show magento/product-community-edition 2.4.* --all | grep -m 1 versions `

I only get 
`versions : * 2.4.2-p2`

Am I missing something ? 

Thanks

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by devchris79** [comment] 2021-09-08 11:27
I have just tried the command and I get:

`versions : * 2.4.3, 2.4.2-p2, 2.4.2-p1, 2.4.2, 2.4.1-p1, 2.4.1, 2.4.0-p1, 2.4.0`

**Comment by engcom-November** [comment] 2021-09-08 12:01
Verified the issue on Magento 2.4.3 version and the issue is not reproducible:
On running the command: composer show magento/product-community-edition 2.4.* --all | grep -m 1 versions  
version 2.4.3 is returned.
![image](https://user-images.githubusercontent.com/60198231/132504908-0022b1ed-c005-4f99-aab9-635beb79a508.png)

@Sartoric We can able to upgrade Magento version from 2.4.2-p1 to 2.4.3 using below steps:
`
composer require magento/product-community-edition 2.4.3 --no-update
composer update
php bin/magento setup:upgrade 
php bin/magento setup:di:compile 
sudo php bin/magento setup:static-content:deploy -f
reindex and clear cache

`
Or New installation using composer can be done using:
`
composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition="2.4.3"

php bin/magento setup:install --base-url=http://repourl --db-host=localhost --db-name=dbname --db-user=username --db-password=yourpassword --admin-firstname=admin --admin-lastname=admin --admin-email=admin@admin.com --admin-user=admin --admin-password=admin123 --language=en_US --currency=USD --timezone=America/Chicago --use-rewrites=1 --backend-frontname=admin
`
Please recheck and let us know if you are still facing the issue.
Thank you.

**Comment by Sartoric** [comment] 2021-09-08 14:15
@devchris79 
Well, that's strange.

I had the suspicion that it wasn't loading the json from repo.magento so I did some additional test 
I've found that the machine I was working on was using composer 2.0.9, so i tried the same with the latest version (2.1.6) in verbose mode (removing the auth.json just to be sure)

I'm getting this 

````
Running 2.1.6 (2021-08-19 17:11:08) with PHP 7.3.29 on Darwin / 17.7.0
Reading ./composer.json (<OMISSIS>composer.json)
Loading config file <OMISSIS>.composer/config.json
Loading config file ./composer.json (<OMISSIS>composer.json)
Checked CA file /usr/local/etc/openssl/cacert.pem: valid
Reading <OMISSIS>.composer/composer.json
Loading config file <OMISSIS>.composer/config.json
Loading config file <OMISSIS>.composer/composer.json (<OMISSIS>.composer/composer.json)
Reading <OMISSIS>vendor/composer/installed.json
Reading <OMISSIS>.composer/vendor/composer/installed.json
Loading plugin Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin (from dealerdirect/phpcodesniffer-composer-installer)
Loading plugin MagentoHackathon\Composer\Magento\Plugin (from magento/magento-composer-installer)
Loading plugin Magento\InventoryComposerInstaller\Plugin (from magento/inventory-composer-installer)
Loading plugin Laminas\DependencyPlugin\DependencyRewriterPluginDelegator (from laminas/laminas-dependency-plugin)
Loading plugin Magento\ComposerRootUpdatePlugin\Plugin\PluginDefinition (from magento/composer-root-update-plugin)
> pre-command-run: Laminas\DependencyPlugin\DependencyRewriterPluginDelegator->onPreCommandRun
Reading ./composer.lock (<OMISSIS>composer.lock)
> command: MagentoHackathon\Composer\Magento\Plugin->onCommandEvent
Downloading https://repo.magento.com/packages.json
[401] https://repo.magento.com/packages.json
Warning from repo.magento.com: You haven't provided your Magento authentication keys. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html
    Authentication required (repo.magento.com):
      Username: <OMISSIS>
      Password: 
Using HTTP basic authentication with username "<OMISSIS>"
Downloading https://repo.magento.com/packages.json
[200] https://repo.magento.com/packages.json
Do you want to store credentials for repo.magento.com in <OMISSIS>.composer/auth.json ? [Yn] n
Writing <OMISSIS>Library/Caches/composer/repo/https---repo.magento.com/packages.json into cache
Reading <OMISSIS>Library/Caches/composer/repo/https---repo.magento.com/p-provider-ce.json from cache
Reading <OMISSIS>Library/Caches/composer/repo/https---repo.magento.com/p-provider-marketplace-extensions.json from cache
Downloading https://repo.packagist.org/packages.json
[200] https://repo.packagist.org/packages.json
Writing <OMISSIS>Library/Caches/composer/repo/https---repo.packagist.org/packages.json into cache
Reading <OMISSIS>Library/Caches/composer/repo/https---repo.packagist.org/provider-magento-hackathon~magento-composer-installer.json from cache
Downloading https://repo.packagist.org/p2/magento-hackathon/magento-composer-installer.json if modified
Reading <OMISSIS>Library/Caches/composer/repo/https---repo.packagist.org/provider-magento-hackathon~magento-composer-installer~dev.json from cache
Downloading https://repo.packagist.org/p2/magento-hackathon/magento-composer-installer~dev.json if modified
[304] https://repo.packagist.org/p2/magento-hackathon/magento-composer-installer.json
[304] https://repo.packagist.org/p2/magento-hackathon/magento-composer-installer~dev.json
Reading <OMISSIS>Library/Caches/composer/repo/https---repo.packagist.org/provider-flyingmana~composer-config-reader.json from cache
Downloading https://repo.packagist.org/p2/flyingmana/composer-config-reader.json if modified
Reading <OMISSIS>Library/Caches/composer/repo/https---repo.packagist.org/provider-eloquent~composer-config-reader.json from cache
Downloading https://repo.packagist.org/p2/eloquent/composer-config-reader.json if modified
Reading <OMISSIS>Library/Caches/composer/repo/https---repo.packagist.org/provider-flyingmana~composer-config-reader~dev.json from cache
Downloading https://repo.packagist.org/p2/flyingmana/composer-config-reader~dev.json if modified
Reading <OMISSIS>Library/Caches/composer/repo/https---repo.packagist.org/provider-eloquent~composer-config-reader~dev.json from cache
Downloading https://repo.packagist.org/p2/eloquent/composer-config-reader~dev.json if modified
[304] https://repo.packagist.org/p2/flyingmana/composer-config-reader.json
[304] https://repo.packagist.org/p2/eloquent/composer-config-reader.json
[304] https://repo.packagist.org/p2/flyingmana/composer-config-reader~dev.json
[304] https://repo.packagist.org/p2/eloquent/composer-config-reader~dev.json
Reading <OMISSIS>Library/Caches/composer/repo/https---repo.packagist.org/provider-eloquent~enumeration.json from cache
Downloading https://repo.packagist.org/p2/eloquent/enumeration.json if modified
Reading <OMISSIS>Library/Caches/composer/repo/https---repo.packagist.org/provider-icecave~isolator.json from cache
Downloading https://repo.packagist.org/p2/icecave/isolator.json if modified
Reading <OMISSIS>Library/Caches/composer/repo/https---repo.packagist.org/provider-eloquent~liberator.json from cache
Downloading https://repo.packagist.org/p2/eloquent/liberator.json if modified
Reading <OMISSIS>Library/Caches/composer/repo/https---repo.packagist.org/provider-eloquent~enumeration~dev.json from cache
Downloading https://repo.packagist.org/p2/eloquent/enumeration~dev.json if modified
Reading <OMISSIS>Library/Caches/composer/repo/https---repo.packagist.org/provider-icecave~isolator~dev.json from cache
Downloading https://repo.packagist.org/p2/icecave/isolator~dev.json if modified
Reading <OMISSIS>Library/Caches/composer/repo/https---repo.packagist.org/provider-eloquent~liberator~dev.json from cache
Downloading https://repo.packagist.org/p2/eloquent/liberator~dev.json if modified
[304] https://repo.packagist.org/p2/eloquent/enumeration.json
[304] https://repo.packagist.org/p2/icecave/isolator.json
[304] https://repo.packagist.org/p2/eloquent/liberator.json
[304] https://repo.packagist.org/p2/eloquent/enumeration~dev.json
[304] https://repo.packagist.org/p2/icecave/isolator~dev.json
[304] https://repo.packagist.org/p2/eloquent/liberator~dev.json
Reading <OMISSIS>Library/Caches/composer/repo/https---repo.packagist.org/provider-eloquent~pops.json from cache
Downloading https://repo.packagist.org/p2/eloquent/pops.json if modified
Reading <OMISSIS>Library/Caches/composer/repo/https---repo.packagist.org/provider-eloquent~pops~dev.json from cache
Downloading https://repo.packagist.org/p2/eloquent/pops~dev.json if modified
[304] https://repo.packagist.org/p2/eloquent/pops.json
[304] https://repo.packagist.org/p2/eloquent/pops~dev.json

versions : * 2.4.2-p2
```

Could it be a server mirror out of sync issue ?

**Comment by devchris79** [comment] 2021-09-09 13:21
@engcom-November Doesn't the screenshot you have posted also show the issue that @Sartoric has seen?
The command `composer show magento/product-community-edition 2.4.* --all | grep -m 1 versions` should show all available 2.4.x versions, not just one like in your screenshot that shows only 2.4.3.

I am running composer 1.10.22, so I would suggest that the package list isn't working correctly with version 2

**Comment by Sartoric** [comment] 2021-09-09 14:04
> should show all available 2.4.x versions, not just one like in your screenshot that shows only 2.4.3.

Exactly, it seems it just show the current one
Maybe there is some strange constraints I'm just missing

**Comment by hostep** [comment] 2021-09-09 20:59
@Sartoric: it's a change in behavior of the `show --all` flag in composer v1 vs composer v2. I noticed it as well half a year ago or so. Maybe you can consider it a bug in composer v2?
But what you can do and what will fix your problem, is to use the `--available` flag instead of the `--all` flag. That one will give you the info you need and as a bonus also works on composer v1.

So this is definitely not a bug in Magento, but in the way you are using composer.

**Comment by Sartoric** [comment] 2021-09-10 08:19
> 
> So this is definitely not a bug in Magento, but in the way you are using composer.

Well, I'm not saying it is a Magento bug, but if what you say about -all / -available it's correct (I mean, it is what it is supposed to do now with v2) for sure Magento's docs need to be updated 

https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html

as well as composer one : https://getcomposer.org/doc/03-cli.md#show
```
--all : List all packages available in all your repositories.
--available (-a): List available packages only.

```
So yes, maybe it's due to a composer bug, not to the way I'm using it 😄 
But in fact --all works as expected for other packages from default repo 

That said, the command 
`composer require magento/product-community-edition 2.4.3 --no-update`
works as expected

**Comment by hostep** [comment] 2021-09-10 11:20
@Sartoric: ah I wasn't aware of that documentation page.

I've opened [an issue](https://github.com/magento/devdocs/issues/9132) with them to change their recommendation to suggest using the `--available` flag:

**Comment by engcom-November** [comment] 2021-09-14 07:32
Hi @Sartoric ,
We are closing this issue as this is not a Magento bug and [new issue](https://github.com/magento/devdocs/issues/9132) has been created to update the devdocs.
Thank you.

**Closed as completed by engcom-November** 2021-09-14 07:32 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
