### ISSUE TITLE
Free Shipping stuck on checkout page when update qty on Checkout Cart page

### ISSUE THREAD

**Issue by Tapin1** [magento/magento2#6780] opened 2016-09-27 21:55 UTC
**"Free shipping" method still visible (available) when you change cart (below free shipping threshold) during checkout.**
### Preconditions
1. Magento ver. 2.1.0
2. PHP 7
### Steps to reproduce

1) set free shipping amount to $50 (or any value you like)
2) Go to your store and add to cart any 2 items total cost of ABOVE 50$ ($45+$45 for example)
3) Go to check out. Complete checkout form
4) You'll see free shipping method - it's OK
5) No Go back to your cart and remove one item (so you card gonna be below $50)
6) Go to checkout again
7) Free shipping is still there (You can't remove it ever!)
### Expected result
1. Free shipping method should be removed if cart price fall below free shipping amount after cart change
### Actual result
1. 7) Free shipping is still there (You can't remove it ever!)

**Comment by ErikPel** [comment] 2016-10-04 06:35
Also happening here.

Magento 2.1 and PHP 7

Those customers that do the steps described in the issue are getting free shipping forever until we  remove then straight from the database to fix it.

**Comment by Tapin1** [comment] 2016-10-04 12:04
Any solution/fix?

**Comment by SerhiyShkolyarenko** [comment] 2016-10-11 08:38
@Tapin1 thank you for reporting! Please clarify the details which way you set 50$ free shipping?
@ErikPel please join the clarification.

**Comment by Tapin1** [comment] 2016-10-11 09:01
I have a "Free shipping" method set. The amount for free shipping is >=$50
If you update your cart on a final step and cart amount goes below 50, free shipping method still available. After this free shipping will be always available until you clean cookie

**Comment by SerhiyShkolyarenko** [comment] 2016-10-11 09:20
@Tapin1 it seems to be fixed on the latest develop branch.

**Comment by Tapin1** [comment] 2016-10-11 09:21
Give me a link please

**Comment by SerhiyShkolyarenko** [comment] 2016-10-11 09:24
sorry, which link do you mean?

**Comment by Tapin1** [comment] 2016-10-11 09:26
Where can I see fixed issues?

**Comment by SerhiyShkolyarenko** [comment] 2016-10-11 09:37
I think console commands `git clone https://github.com/magento/magento2.git .` and `git log` will provide the complete list of fixes.
If you have the cloned repository, `git pull`, `git checkout develop` and `git log` will be better for you.

**Comment by SerhiyShkolyarenko** [comment] 2016-10-25 14:32
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by SerhiyShkolyarenko** 2016-10-25 14:32 UTC
Labels: bug report, Progress: needs update, Component: Checkout
