### ISSUE TITLE
Magento 2.1.2 Bank Transfer cannot make a payment for Virtual Product and Downloadable Product

### ISSUE THREAD

**Issue by jurpro** [magento/magento2#7483] opened 2016-11-18 11:13 UTC
Hello again.
I need to sell a virtual product and downloadable product such as pdf or other files sending to email, but on checkout it cannot make a payment.

### Preconditions
I need to sell a virtual product and downloadable product such as:
1. Virtual Product : PDF files send to email. ==Generate by third company==
2. Downloadable product : music product. ==download in Menu Customer account==

I'm using Magento 2.1.2, 
Payment method : Bank Transfer
No Shipping requaired.

### Steps to reproduce
For Virtual Product:
1. Customer Buy a virtual product, such as Gift Card.
2. Virtual Product add to Chart Shopping
3. Customer go to Checkout. page

For Downloadable Product
1. Customer buy a downloadable product such as music files
2. Product add to chart shopping
3. Customer go to checkout page
4. Customer must sign in for downloadable product on checkout page

### Expected result
1. On the checkout page, Customers must be success to pay their order by Bank Transfer payment method
2. Place Order success. 
3. Customers go to ATM, or internet banking, or teller bank to transfer a payment.
4. After money received, customer can download their downloadable product, or waiting an email for virtual product.

### Actual result
1. No Payment method available. I only use Bank Transfer payment method
2. If this product change to simple product, it can be checkout until success. But this is not simple product, it's a downloadable with some files, and virtual with sending by email.

![Image of Yaktocat](https://s18.postimg.org/edbl1po15/03_virtual_product_bank_transfer_bug.jpg)

**Comment by jurpro** [comment] 2016-11-20 11:25
Hello @joni-jones and @alena-marchenko 

Is there any progress on this?
I need fix this issue immediately.

Thanks for your help and answer

**Comment by BlitzInternet** [comment] 2016-11-24 13:36
+1

- if there is no shipping
- and the payment method is restricted by country
- and no addressess fitting the country restrictions exist (e.g. because customer is guest)
- then no payment method is shown
- then there is no way to enter an address in checkout and order!

**Comment by jurpro** [comment] 2016-12-14 11:52
hello everyone. is there any progress? 
Thank you

**Comment by YevSent** [comment] 2016-12-27 13:50
Hi, @jurpro, we cannot reproduce specified issue. Please, provide more details.

On Magento 2.1.3 all works as expected. Checkout with a downloadble product:
![screenshot from 2016-12-27 15-45-40](https://cloud.githubusercontent.com/assets/2736528/21500885/081f9222-cc4c-11e6-864c-411cd90691e9.png)

And filled billing address for a guest customer:
![screenshot from 2016-12-27 15-46-35](https://cloud.githubusercontent.com/assets/2736528/21500886/0b95c318-cc4c-11e6-9076-3a501d49556c.png)

**Comment by jurpro** [comment] 2016-12-30 23:32
Hi @joni-jones 

Yes I know. On Magento 2.1.3 it works fine. But, there is a little bit "annoying" sorry if I write annoying. It should fill all address necessary, then customers should hit "update" button to activate "Place Order" button. On simple product, customers directly push "place order" button after Review Order on Step 2.

I wish, the "update" button is removed, so customers directly push "Place Order" button.

Thank you so much.

**Comment by YevSent** [comment] 2017-01-01 18:15
@jurpro, `Update` button is required because it triggers address updating. It useful in many cases, for example, customer can enter billing country which is not allowed for some payments, so payments should be rerendered.

Closed as not a bug.

**Closed as completed by YevSent** 2017-01-01 18:15 UTC
Labels: bug report, Progress: needs update, Component: Payment
