### ISSUE TITLE
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#10983] opened 2017-09-21 09:11 UTC
Composer shows the message 'Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.' after running `composer install`.

### Preconditions
n/a

### Steps to reproduce
Run `composer install` after cloning the repo.

### Expected result
No warning.

### Actual result
Abandoned package warning.

### Fix
Replace the `package fabpot/php-cs-fixer` with `friendsofphp/php-cs-fixer`

**Comment by orlangur** [comment] 2017-09-21 09:33
@schadom thanks for your report! Closing as duplicate of https://github.com/magento/magento2/issues/7310.

**Closed as completed by orlangur** 2017-09-21 09:33 UTC
Labels: duplicate, Issue: Format is valid
