### ISSUE TITLE
Virtual Orders doesn't complete using PayPal payflow method.

### ISSUE THREAD

**Issue by amarroni** [magento/magento2#6977] opened 2016-10-12 20:37 UTC
### Preconditions
1.  Magento version 2.1.0
2. Using API and successfully reproduced from the site
### Steps to reproduce

1. Add a virtual product to the cart.
2. Use paypal payflow as payment method.
3. Order is created.
### Expected result
1. After virtual order is created status should be COMPLETE
### Actual result
1.  Order still in processing status
   ![order-no-complete-1](https://cloud.githubusercontent.com/assets/5198527/19326741/242a2cec-90a2-11e6-9774-1ea30f09cb4c.png)

Quick test Order problem, putting the order on Hold
![order-no-complete-2](https://cloud.githubusercontent.com/assets/5198527/19326748/2c06ff62-90a2-11e6-9942-6c59265e6207.png)
Order was successfully changed to "on Hold" status then unHold the order
![order-no-complete-3](https://cloud.githubusercontent.com/assets/5198527/19326749/2c35f7c2-90a2-11e6-90ff-1c820de1cb85.png)
Order successfuly unHold and put in the correct status "complete"
![order-no-complete-4](https://cloud.githubusercontent.com/assets/5198527/19326750/2c38ae18-90a2-11e6-9aa6-80230321b14b.png)

Best,
Alejandro.

**Comment by amarroni** [comment] 2016-10-13 12:52
Something I didn't mentioned is if you used check on money method the order is completed successfully.

Best,
Alejandro.

**Comment by viktym** [comment] 2016-10-20 15:34
Hi @amarroni 
I can't reproduce this issue on 2.1.2 and develop branch.
If I understand you well you try to place an order with the virtual product using PayPal Payflow Pro method with Payment Action "Sale". In this case, the order is placed with status "Complete". Try to update your magento instance to latest patch release 2.1.2
Thanks for the feedback.

**Comment by amarroni** [comment] 2016-10-21 13:10
Hi @vikty, thank you so much for your response. I'll try to update my instance and I'll let you know.
Right now I'm running other project with 2.2-dev version I will to apply other order there too.

Thank you so much,
Best,
Alejandro.

**Comment by YevSent** [comment] 2016-11-28 16:40
Hi, @amarroni. We are closing this issue because it hasn’t been updated in more than two weeks.

If you can still reproduce this issue, please, be free to reopen it.

**Closed as completed by YevSent** 2016-11-28 16:40 UTC
Labels: bug report, Progress: needs update, Component: Payment

**Comment by amarroni** [comment] 2016-11-28 17:33
Hi @joni-jones sorry about that I was without time to review again. we still expecting same issue in our end but if the team think like is impossible to reproduce the issue... Maybe is a exception case.

I'll try to debug a little more and back with my findings.

Best,
Alejandro.

**Comment by iwdjoe** [comment] 2017-01-06 20:11
We do receive same issue with Magento 2.1.0 Enterprise version.
Once we switched gift card to "virtual", we've started getting issues with checkout via PayPal Express and duplicated invoice ID.
