### ISSUE TITLE
How to reproduce this issue "the product that was requested doesn't exist. verify the product and try again"

### ISSUE THREAD

**Issue by pkatare** [magento/magento2#34244] opened 2021-10-05 06:47 UTC
### Preconditions (*)

1. Magento 2.3 
2. 

### Steps to reproduce (*)

1. Login to website
2. Go to PDP
3. Enter qty and click on add  to cart button

### Expected result (*)
Product should be able to add in minicart
1. [Screenshots, logs or description]

### Actual result (*)
When I am adding product to cart getting error - "the product that was requested doesn't exist. verify the product and try again"
But when I tried again not getting this issue it it very rarely showing
1. [Screenshots, logs or description]

**Comment by engcom-Lima** [comment] 2021-10-05 12:49
Hi @pkatare,

Thank you for reporting the issue. Although we won't be able to analyse it until we can reproduce it on 2.4-develop. So in order to do that, please update below queries:

1. Can you please try again with the same steps as you did when you got error ? Maybe you'll be able to reproduce it again. Please make sure to clear cache.
2. Did you update inventory just before going to Product detail page ?

If you are not able to reproduce it, we will have to close this issue.

**Closed as completed** 2021-10-19 05:07 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
