### ISSUE TITLE
Elasticsearch parsing exception

### ISSUE THREAD

**Issue by sigismund** [magento/magento2#22491] opened 2019-04-25 08:19 UTC
### Preconditions (*)
1. Magento 2.3.1 or current `2.3-develop` branch
2. Elasticserach 6.7.1

### Steps to reproduce (*)
1. Add dropdown product attribute with: 
   * Scope: global scope
   * Unique value: no
   * Add to Column options: yes
   * Use inf Filter options: yes
   * Use in search: yes 
2. Search for a term used in one of the dropdown's options.

### Expected result (*)
1. Search results based on Elasticsearch

### Actual result (*)
1. Fallback search results based on MySQL search
2. Exception:
```
[2019-04-25 08:06:28] main.CRITICAL: {"error":{"root_cause":[{"type":"parsing_exception","reason":"[terms] unknown token [START_ARRAY] after [in]","line":1,"col":115}],"type":"parsing_exception","reason":"[terms] unknown token [START_ARRAY] after [in]","line":1,"col":115},"status":400} {"exception":"[object] (Elasticsearch\\Common\\Exceptions\\BadRequest400Exception(code: 400): {\"error\":{\"root_cause\":[{\"type\":\"parsing_exception\",\"reason\":\"[terms] unknown token [START_ARRAY] after [in]\",\"line\":1,\"col\":115}],\"type\":\"parsing_exception\",\"reason\":\"[terms] unknown token [START_ARRAY] after [in]\",\"line\":1,\"col\":115},\"status\":400} at /home/xxx/public_html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:615)"} []
```
3. Query sent to Elasticsearch looks like this:
```
"query": {
        "bool": {
            "must": [
                {
                    "term": {
                        "category_ids": "222"
                    }
                },
                {
                    "terms": {
                        "manufacturer": {
                            "in": [
                                "166",
                                "53",
                                "65",
                                "66",
                                "164"
                            ]
                        }
                    }
                }
            ]
        }
    },
```
This isn't valid ES query, `manufacturer` in terms shouldn't include `in` parameter. When I manually tested without `in` it worked without any problem.

**Comment by magento-engcom-team** [comment] 2019-04-26 10:47
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99427` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by GovindaSharma** [comment] 2019-05-04 04:21
#dmcdindia1

**Comment by sigismund** [comment] 2019-06-06 14:29
Any news regarding this issue?

**Comment by scne** [comment] 2019-08-09 08:56
any news? In my case I get this error using elasticsearch5
```
main.CRITICAL: {"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query: {
  "bool" : {
    "must" : [
      {
        "term" : {
          "category_ids" : {
            "value" : "279",
            "boost" : 1.0
          }
        }
      },
      {
        "terms" : {
          "visibility" : [
            "2",
            "4"
          ],
          "boost" : 1.0
        }
      },
      {
        "terms" : {
          "manufacturer" : [
            "{",
            "eq",
            "948",
            "}"
          ],
          "boost" : 1.0
        }
      }
    ],
    "disable_coord" : false,
    "adjust_pure_negative" : true,
    "boost" : 1.0
  }
}","index_uuid":"V1_G2RWGQP-O-G9iNIoh9w","index":"magento2_product_1_v41"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"magento2_product_1_v41","node":"DlRawzy2QsiSXBGwxwenjw","reason":{"type":"query_shard_exception","reason":"failed to create query: {
  "bool" : {
    "must" : [
      {
        "term" : {
          "category_ids" : {
            "value" : "279",
            "boost" : 1.0
          }
        }
      },
      {
        "terms" : {
          "visibility" : [
            "2",
            "4"
          ],
          "boost" : 1.0
        }
      },
      {
        "terms" : {
          "manufacturer" : [
            "{",
            "eq",
            "948",
            "}"
          ],
          "boost" : 1.0
        }
      }
    ],
    "disable_coord" : false,
    "adjust_pure_negative" : true,
    "boost" : 1.0
  }
}","index_uuid":"V1_G2RWGQP-O-G9iNIoh9w","index":"magento2_product_1_v41","caused_by":{"type":"number_format_exception","reason":"For input string: "{""}}}]},"status":400} {"exception":"[object] (ElasticsearchCommonExceptionsBadRequest400Exception(code: 400): {"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query: {
  "bool" : {
    "must" : [
      {
        "term" : {
          "category_ids" : {
            "value" : "279",
            "boost" : 1.0
          }
        }
      },
      {
        "terms" : {
          "visibility" : [
            "2",
            "4"
          ],
          "boost" : 1.0
        }
      },
      {
        "terms" : {
          "manufacturer" : [
            "{",
            "eq",
            "948",
            "}"
          ],
          "boost" : 1.0
        }
      }
    ],
    "disable_coord" : false,
    "adjust_pure_negative" : true,
    "boost" : 1.0
  }
}","index_uuid":"V1_G2RWGQP-O-G9iNIoh9w","index":"magento2_product_1_v41"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"magento2_product_1_v41","node":"DlRawzy2QsiSXBGwxwenjw","reason":{"type":"query_shard_exception","reason":"failed to create query: {
  "bool" : {
    "must" : [
      {
        "term" : {
          "category_ids" : {
            "value" : "279",
            "boost" : 1.0
          }
        }
      },
      {
        "terms" : {
          "visibility" : [
            "2",
            "4"
          ],
          "boost" : 1.0
        }
      },
      {
        "terms" : {
          "manufacturer" : [
            "{",
            "eq",
            "948",
            "}"
          ],
          "boost" : 1.0
        }
      }
    ],
    "disable_coord" : false,
    "adjust_pure_negative" : true,
    "boost" : 1.0
  }
}","index_uuid":"V1_G2RWGQP-O-G9iNIoh9w","index":"magento2_product_1_v41","caused_by":{"type":"number_format_exception","reason":"For input string: "{""}}}]},"status":400} at /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:636)"} []
```

**Comment by salehawal** [comment] 2019-08-12 15:49
same here ... Magento 2.3

[2019-08-12 11:29:47] main.CRITICAL: {"error":{"root_cause":[{"type":"parsing_exception","reason":"[terms] unknown token [START_ARRAY] after [in]","line":1,"col":153}],"type":"parsing_exception","reason":"[terms] unknown token [START_ARRAY] after [in]","line":1,"col":153},"status":400} {"exception":"[object] (Elasticsearch\\Common\\Exceptions\\BadRequest400Exception(code: 400): {\"error\":{\"root_cause\":[{\"type\":\"parsing_exception\",\"reason\":\"[terms] unknown token [START_ARRAY] after [in]\",\"line\":1,\"col\":153}],\"type\":\"parsing_exception\",\"reason\":\"[terms] unknown token [START_ARRAY] after [in]\",\"line\":1,\"col\":153},\"status\":400} at /public_html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:615)"} []

**Comment by salehawal** [comment] 2019-08-23 08:58
@sigismund did you find a solution?

**Comment by sigismund** [comment] 2019-08-24 09:53
Not really, I lost hope with this bug. It seems like another of Magento bugs that isnt't gonna get solved, because enterprise edition doesn't have a problem with it ;)

I made a switch to [ElasticSuite](https://github.com/Smile-SA/elasticsuite) solution. It's open source, has additional settings and it works.

**Comment by MagentoSeba** [comment] 2019-09-04 20:57
@sigismund the issue is actually also in Magento Commerce 2.3.0, the @magento-engcom-team  should be aware of that.

**Comment by magento-engcom-team** [comment] 2019-09-23 19:21
Hi @sigismund, @GovindaSharma, @ashutoshwebkul. 

Thank you for your report and collaboration!

The related internal Jira ticket `MAGETWO-99427` was closed as `non-reproducible` in `2.3-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by MagentoSeba** [comment] 2019-09-23 20:39
@magento-engcom-team  @sigismund @GovindaSharma and @ashutoshwebkul  did you take into account that is a different version of ElasticSearch as of 2.3.2.  
This issue is applicable to 2.3.0 and 2.3.1.

**Comment by sidolov** [comment] 2019-09-23 20:52
@MagentoSeba we will check once again, thank you for the input! Maybe you have more information about it, it would be great to add it here. Thank you!

**Comment by MagentoSeba** [comment] 2019-09-23 21:11
sure @sidolov ! 

The main error is :

```
[2019-04-30 11:34:00] report.CRITICAL: {"error":{"root_cause":[{"type":"parsing_exception","reason":"[terms] unknown token [START_ARRAY] after [in]","line":1,"col":183}],"type":"parsing_exception","reason":"[terms] unknown token [START_ARRAY] after [in]","line":1,"col":183},"status":400} {"exception":"[object] (Elasticsearch\\Common\\Exceptions\\BadRequest400Exception(code: 400): {\"error\":{\"root_cause\":[{\"type\":\"parsing_exception\",\"reason\":\"[terms] unknown token [START_ARRAY] after [in]\",\"line\":1,\"col\":183}],\"type\":\"parsing_exception\",\"reason\":\"[terms] unknown token [START_ARRAY] after [in]\",\"line\":1,\"col\":183},\"status\":400} at /mnt/data/www/client/releases/DEV-release-350/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:610)"} []

```

The query in our case is :
![image](https://user-images.githubusercontent.com/8442395/65463101-05cff780-de0c-11e9-939b-77b58e310708.png)


If query modified by removing "in", Elasticsearch works as expected.

**Comment by magento-engcom-team** [comment] 2019-09-23 21:46
@sdzhepa Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-09-23 21:46
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99427 ` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment] 2019-09-23 22:03
Hello @MagentoSeba

Thank you for the input and collaboration!

The issue was closed by mistake - were used not accurate steps to reproduce/preconditions.
Now internal team has confirmed that issue can be reproduced by provided steps. The issue will be resolved in the scope of internal Jira ticket `MAGETWO-99427` by Magento team

As soon as it will be delivered into `2.3-develop`, we provide a list of commits here as a comment.

**Comment by magento-engcom-team** [comment] 2019-10-01 19:52
@sigismund and @MagentoSeba, 

Thank you for your report and collaboration!

The issue has been fixed by Magento team in the scope of internal Jira tickets `MC-20381` and `MAGETWO-99427` 
The fix has been delivered into `2.3-develop` branch

Related commit(s):
- https://github.com/magento/magento2/commit/4844c67145e87ae77dc30b09907fa3dfbf181fd5

**Closed as completed by magento-engcom-team** 2019-10-01 19:52 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Elasticsearch, Event: dmcdindia1

**Comment by adarshkhatri** [comment] 2020-02-05 05:07
I am having this issue in M2.3.3 EE

**Comment by adarshkhatri** [comment] 2020-02-05 07:10
> any news? In my case I get this error using elasticsearch5
> 
> ```
> main.CRITICAL: {"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query: {
>   "bool" : {
>     "must" : [
>       {
>         "term" : {
>           "category_ids" : {
>             "value" : "279",
>             "boost" : 1.0
>           }
>         }
>       },
>       {
>         "terms" : {
>           "visibility" : [
>             "2",
>             "4"
>           ],
>           "boost" : 1.0
>         }
>       },
>       {
>         "terms" : {
>           "manufacturer" : [
>             "{",
>             "eq",
>             "948",
>             "}"
>           ],
>           "boost" : 1.0
>         }
>       }
>     ],
>     "disable_coord" : false,
>     "adjust_pure_negative" : true,
>     "boost" : 1.0
>   }
> }","index_uuid":"V1_G2RWGQP-O-G9iNIoh9w","index":"magento2_product_1_v41"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"magento2_product_1_v41","node":"DlRawzy2QsiSXBGwxwenjw","reason":{"type":"query_shard_exception","reason":"failed to create query: {
>   "bool" : {
>     "must" : [
>       {
>         "term" : {
>           "category_ids" : {
>             "value" : "279",
>             "boost" : 1.0
>           }
>         }
>       },
>       {
>         "terms" : {
>           "visibility" : [
>             "2",
>             "4"
>           ],
>           "boost" : 1.0
>         }
>       },
>       {
>         "terms" : {
>           "manufacturer" : [
>             "{",
>             "eq",
>             "948",
>             "}"
>           ],
>           "boost" : 1.0
>         }
>       }
>     ],
>     "disable_coord" : false,
>     "adjust_pure_negative" : true,
>     "boost" : 1.0
>   }
> }","index_uuid":"V1_G2RWGQP-O-G9iNIoh9w","index":"magento2_product_1_v41","caused_by":{"type":"number_format_exception","reason":"For input string: "{""}}}]},"status":400} {"exception":"[object] (ElasticsearchCommonExceptionsBadRequest400Exception(code: 400): {"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query: {
>   "bool" : {
>     "must" : [
>       {
>         "term" : {
>           "category_ids" : {
>             "value" : "279",
>             "boost" : 1.0
>           }
>         }
>       },
>       {
>         "terms" : {
>           "visibility" : [
>             "2",
>             "4"
>           ],
>           "boost" : 1.0
>         }
>       },
>       {
>         "terms" : {
>           "manufacturer" : [
>             "{",
>             "eq",
>             "948",
>             "}"
>           ],
>           "boost" : 1.0
>         }
>       }
>     ],
>     "disable_coord" : false,
>     "adjust_pure_negative" : true,
>     "boost" : 1.0
>   }
> }","index_uuid":"V1_G2RWGQP-O-G9iNIoh9w","index":"magento2_product_1_v41"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"magento2_product_1_v41","node":"DlRawzy2QsiSXBGwxwenjw","reason":{"type":"query_shard_exception","reason":"failed to create query: {
>   "bool" : {
>     "must" : [
>       {
>         "term" : {
>           "category_ids" : {
>             "value" : "279",
>             "boost" : 1.0
>           }
>         }
>       },
>       {
>         "terms" : {
>           "visibility" : [
>             "2",
>             "4"
>           ],
>           "boost" : 1.0
>         }
>       },
>       {
>         "terms" : {
>           "manufacturer" : [
>             "{",
>             "eq",
>             "948",
>             "}"
>           ],
>           "boost" : 1.0
>         }
>       }
>     ],
>     "disable_coord" : false,
>     "adjust_pure_negative" : true,
>     "boost" : 1.0
>   }
> }","index_uuid":"V1_G2RWGQP-O-G9iNIoh9w","index":"magento2_product_1_v41","caused_by":{"type":"number_format_exception","reason":"For input string: "{""}}}]},"status":400} at /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:636)"} []
> ```

I am having this issue in M2.3.3
