### ISSUE TITLE
Redis sessions don't work when using Redis on 2.2-develop

### ISSUE THREAD

**Issue by vtimonin** [magento/magento2#12583] opened 2017-12-07 14:49 UTC
### Preconditions
1. Magento 2.2-develop branch
2. Redis for session management

### Steps to reproduce
1. Enable developer mode
2. Open home page

### Expected result
1. The home page is displayed

### Actual result
1. Unhandled exception `Exception #0 (Exception): Notice: Undefined offset: 0 in /media/home/Projects/magento2/vendor/colinmollenhour/php-redis-session-abstract/src/Cm/RedisSession/Handler.php on line 494`

This error is caused by module colinmollenhour/php-redis-session-abstract:1.3.4 being incompatible with module colinmollenhour/credis:1.9.1 -  Credis_Client::hMGet started to return an object, but Cm/RedisSession/Handler.php still expects an array, this error is fixed in colinmollenhour/php-redis-session-abstract:1.3.5.

**Comment by magento-engcom-team** [comment] 2018-03-05 14:29
@vtimonin, thank you for your report.
The issue is already fixed in 2.3.0, 2.1.12

**Closed as completed by magento-engcom-team** 2018-03-05 14:29 UTC
Labels: Issue: Confirmed, Reproduced on 2.2.x, Fixed in 2.1.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by xtremevision** [comment] 2024-01-30 23:05
I have just gotten this error and I am running PHP 8.1.27, Magento 2 OS v2.4.6, redis 3.2.12,

1 exception(s):
Exception #0 (Exception): Warning: Undefined array key 0 in /home/michael/www/XXXXXXXXXXXX/htdocs/vendor/colinmollenhour/php-redis-session-abstract/src/Cm/RedisSession/Handler.php on line 515

Exception #0 (Exception): Warning: Undefined array key 0 in /home/michael/www/XXXXXXXXXXXX/htdocs/vendor/colinmollenhour/php-redis-session-abstract/src/Cm/RedisSession/Handler.php on line 515
<pre>#1 Cm\RedisSession\Handler->read() called at [vendor/magento/framework/Session/SaveHandler/Redis.php:98]
#2 Magento\Framework\Session\SaveHandler\Redis->read() called at [vendor/magento/framework/Session/SaveHandler.php:212]
#3 Magento\Framework\Session\SaveHandler->callSafely() called at [vendor/magento/framework/Session/SaveHandler.php:125]
#4 Magento\Framework\Session\SaveHandler->read()
#5 session_start() called at [vendor/magento/framework/Session/SessionManager.php:186]
#6 Magento\Framework\Session\SessionManager->start() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#7 Magento\Framework\Session\Generic\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#8 Magento\Framework\Session\Generic\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#9 Magento\Framework\Session\Generic\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/Session/Generic/Interceptor.php:23]
#10 Magento\Framework\Session\Generic\Interceptor->start() called at [vendor/magento/framework/Session/SessionManager.php:123]
#11 Magento\Framework\Session\SessionManager->__construct() called at [generated/code/Magento/Framework/Session/Generic/Interceptor.php:14]
#12 Magento\Framework\Session\Generic\Interceptor->__construct() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121]
#13 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:108]
#14 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:150]
#15 Magento\Framework\ObjectManager\Factory\Compiled->get() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:79]
#16 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:150]
#17 Magento\Framework\ObjectManager\Factory\Compiled->get() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:79]
#18 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:150]
#19 Magento\Framework\ObjectManager\Factory\Compiled->get() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:79]
#20 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:150]
#21 Magento\Framework\ObjectManager\Factory\Compiled->get() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:125]
#22 Magento\Framework\ObjectManager\Factory\Compiled->parseArray() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:86]
#23 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:70]
#24 Magento\Framework\ObjectManager\ObjectManager->get() called at [vendor/magento/framework/App/FrontController.php:109]
#25 Magento\Framework\App\FrontController->__construct() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:14]
#26 Magento\Framework\App\FrontController\Interceptor->__construct() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121]
#27 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:108]
#28 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:70]
#29 Magento\Framework\ObjectManager\ObjectManager->get() called at [vendor/magento/framework/App/Http.php:115]
#30 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#31 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
</pre>
