### ISSUE TITLE
Download of downloadable product in pending state isn't allowed even when pending downloads are allowed in the admin (fix provided)

### ISSUE THREAD

**Issue by crankycyclops** [magento/magento2#21757] opened 2019-03-14 22:08 UTC
### Preconditions (*)

1. Magento 2.2.7
2. PHP 7.1

### Steps to reproduce (*)

1. Login to the admin and set Stores -> Configuration -> Catalog -> Downloadable Product Options -> Order Item Status to Enable Downloads to "Pending"
2. Log into the frontend of a Magento store and purchase a downloadable product as a registered user
3. Click on one of the downloadable product links, which should be in a pending state

### Expected result (*)

The download should proceed, because downloadable products in a pending state have been allowed via an admin config value.

### Actual result (*)

User is presented with the message 'Download is not available.'

### Proposed Solution

I've submitted a pull request which references this issue.

Issue is related to #21753.

**Comment by magento-engcom-team** [comment] 2019-03-14 22:08
Hi @crankycyclops. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@crankycyclops do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by shikhamis11** [comment] 2019-03-15 16:09
@crankycyclops the issue is same as  #21753 so I am closing this one

**Closed as completed by shikhamis11** 2019-03-15 16:09 UTC
Labels: Issue: Format is valid

**Comment by crankycyclops** [comment] 2019-03-15 16:47
@shikhamis11, they're related but slightly different issues. This one is an issue with the download not actually working. The other has to do with the download links not being displayed in "My Downloads." Fixing #21753 would still leave this issue unfixed (although the pull request I submitted fixes both issues, so if work progresses under the other issue that's probably fine.)
