### ISSUE TITLE
"Add to Cart" button on product details page after buy all product quantity

### ISSUE THREAD

**Issue by LordHansolo** [magento/magento2#33394] opened 2021-06-30 14:24 UTC
### Preconditions (*)
1. Magento Open Source 2.4.2

### Steps to reproduce (*)
1. Create test source
2. Create test stock
3. Assing source and Main Website to test stock
4. Assign Simple Product to source
5. Buy all available product quantity on Main Website
6. Go back to product details page

### Expected result (*)
1. "Out of stock" information appears instead "Add to Cart" button
![out_of_stock](https://user-images.githubusercontent.com/22025597/123975681-d1647480-d9bd-11eb-861d-9945a06bfd62.png)

### Actual result (*)
1. "Add to Cart" button appears.
![add_to_cart_product](https://user-images.githubusercontent.com/22025597/123975767-e2ad8100-d9bd-11eb-8207-84f001a401e9.png)

### Additional information
It looks like reservations are not considered during isSaleable check.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2021-07-01 10:28
Verified the issue on Latest Magento version 2.4.2 and the issue is reproducible:
**Steps to reproduce:**
1. Add new Source (Stores -> Inventory -> Sources -> Add New Source)
2. Add new Stock (Stores -> Inventory -> Stocks -> Add New Stock -> Assign main website and newly created source)
3. Create new Simple Product and assign Source.
4. Front End -> Buy all the product quantity
5. Clear cache and refresh the pages
6. Front end -> Navigate to Product Details page
**Issue:** In Stock Status is displayed along with Add to Cart button.
Note: However, on clicking Add to Cart button, error is displayed.
**Expected behavior:** Out Of Stock status should be displayed and Add to Cart button should not be displayed. 
![image](https://user-images.githubusercontent.com/60198231/124109591-ef48dc80-da84-11eb-8e62-33390c403222.png)
![image](https://user-images.githubusercontent.com/60198231/124109758-1dc6b780-da85-11eb-9b60-fc64c8a80753.png)

**Comment by magento-engcom-team** [comment] 2021-07-01 16:34
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42772` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by quterorta** [comment] 2022-11-11 13:15
@magento I am working on this

**Comment by engcom-Bravo** [comment] 2024-06-19 05:12
@magento give me 2.4-develop instance

**Closed as completed** 2024-06-19 05:17 UTC
Labels: Issue: Confirmed, Component: Inventory, Reproduced on 2.4.x, Priority: P2, Progress: done, Reported on 2.4.2, Area: Inventory / MSI
