### ISSUE TITLE
Updating customer via API resets default billing adres

### ISSUE THREAD

**Issue by PaulBoss** [magento/magento2#7380] opened 2016-11-09 14:18 UTC
### Preconditions
Magento 2.1
A customer with a default billing adres set

### Steps to reproduce
1. Update firstname and lastname via the API.
PUT /rest/v1/customers/1
`{"customer":{"id":1,"email":"roni_cost@example.com","firstname":"Paul","lastname":"Boss","middlename":null,"gender":0}}
`
### Expected result
1. Customer with id 1 has firstname "Paul" and lastname "Boss". Other data is left intact

### Actual result
1. Default billing address option is reset. The address is stil available, but the "default billing address" option is now false.

**Comment by Bbbrinks** [comment] 2016-11-10 13:26
Same goes for Default shipping addresses.

**Comment by Bbbrinks** [comment] 2016-11-10 13:29
Workaround would be to fetch the customer before updating and setting the default_billing and default_shipping values in the PUT request.

Makes me wonder what other data is lost when using partial PUT requests.

**Comment by olysenko** [comment] 2016-11-25 17:11
Hi, thank you for your request. Internal ticket MAGETWO-59872 was created

**Comment by vzabaznov** [comment] 2016-12-15 16:06
as workaround can advice to modify put data and add:

 "default_billing": <address_id> ,
  "default_shipping": <address_id>

**Comment by veloraven** [comment] 2017-06-20 12:10
This issue was fixed in develop branch.
It also was fixed for ver. 2.1 in internal ticket MAGETWO-61907 and for ver. 2.0 in internal ticket MAGETWO-61908. 
Fixes will be available in one of the nearest releases.

**Comment by magento-engcom-team** [comment] 2017-09-20 22:40
@PaulBoss, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:40 UTC
Labels: Issue: Ready for Work, bug report, Component: Framework/Webapi, Fixed in 2.2.x, Issue: Format is valid

**Comment by MarWestermann** [comment] 2018-01-23 10:22
Still face the same issue on 2.2.1 (enterprise edition)
