### ISSUE TITLE
Coupon code applied in the cart page not showing in the Checkout shipping page

### ISSUE THREAD

**Issue by rameshpushparaj** [magento/magento2#8713] opened 2017-02-28 12:47 UTC
When any coupon code is applied in the shopping cart ,the discount shows up on cart page and after you enter shipping information in checkout but not when you initially go to checkout.

Preconditions

Magento CE v2.0.10

Steps to reproduce

Sign into Magento store.
Add product(s) to cart.
Apply any available discount coupon code in Shopping cart page
Click Go to Checkout.

Expected result

The Order Summary should display the applied discount code with discount amount in shipping tab.

Actual result

The  Discount amount and coupon code gets displayed only after shipping information is entered.

This issue is affecting the store wide sales. The end user is getting confused on why the discount amount and coupon code is not showing.

**Comment by sivaschenko** [comment] 2017-03-30 11:03
Fixed by https://github.com/magento/magento2/commit/7431c276fd6558f59f4b0b500f860a6795d77b20

**Comment by magento-engcom-team** [comment] 2017-10-02 12:57
Hi @rameshpushparaj 
We are closing this as the issue is already fixed in 2.2
Thank you

**Closed as completed by magento-engcom-team** 2017-10-02 12:57 UTC
Labels: Issue: Format is valid
