### ISSUE TITLE
Product import issue with images from external resource

### ISSUE THREAD

**Issue by dhiraj-danode** [magento/magento2#26061] opened 2019-12-16 09:49 UTC
### Preconditions (*)

1. Magento Enterprise 2.3.3
2.

### Steps to reproduce (*)

1. While product import from admin -> System -> Import I am getting following error.
	**Imported resource (image) could not be downloaded from an external resource due to timeout or access permissions in row(s): 1, 2**
[products.zip](https://github.com/magento/magento2/files/3967275/products.zip)
![Error](https://user-images.githubusercontent.com/47853083/70896832-7b1c2480-2017-11ea-83c8-c671b10cd066.png)

2. In the image column, we have image URL from other sources. Attached the import file which we are using.

### Expected result (*)

1. [Screenshots, logs or description]
2. The import should work.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by dhiraj-danode** [comment] 2019-12-16 09:53
Hello Support team

Yes, I am facing issue in default 2.3.3 enterprise version.
Attached the issue screenshot and file I am trying to import.

Thanks
Dhiraj

**Comment by engcom-Echo** [comment] 2019-12-16 11:15
Hello @dhiraj-danode 

Thank you for contribution and collaboration!
@sdzhepa Could you move this issue into  [Magento Commerce private repository](https://github.com/magento/partners-magento2ee/issues) where it could be fixed and delivered by Solution Partners Contribution Program.
[Current repository](https://github.com/magento/magento2) and [issue tracker](https://github.com/magento/magento2/issues) aimed at Magento Open Source version only and the main focus is community contribution/collaboration. It described in [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and it is a part of the issue report template:
> Verify, that the issue you are about to report does not relate to the Magento Commerce. GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub. You can report Commerce-related issues in one of two ways:
> - You can use the Support portal associated with your account
> - If you are a Partner reporting on behalf of a merchant, use the Partner portal.

**Comment by selvathangam** [comment] 2019-12-17 11:57
Hello Support team

Yes, I am facing issue in default 2.3.3 community version.


Thanks
Thangadurai.S

**Comment by sdzhepa** [comment] 2019-12-17 15:02
Hello @engcom-Echo 

Could you please provide more details about why this issue is Enterprise specific and why it cannot be reproduced in CE(Open Source) edition?

**Comment by engcom-Echo** [comment] 2019-12-17 16:56
Hello @sdzhepa @dhiraj-danode 

I am not able to reproduce this issue on the 2.4-develop branch by provided steps. 
Tested on the both EE(Enterprise) and CE(Open Source) editions.

**Testing scenario:**

**Preconditions:**
Product Import File [products.zip](https://github.com/magento/magento2/files/3967275/products.zip)

**Steps to reproduce:**

1. Go to System -> Import
2. Import Settings:
3. ![Screenshot from 2019-12-17 18-14-59](https://user-images.githubusercontent.com/51681435/71013619-a4ad7c80-20f9-11ea-971b-e4ebeedfb551.png)
4. Select File to Import from preconditions.
5. Click “Check Data” -> “Import”

**Result**
Import successfully done. No errors.
![Screenshot from 2019-12-17 18-19-55](https://user-images.githubusercontent.com/51681435/71014296-66fd2380-20fa-11ea-89e6-5787825c0f4a.png)
Images successfully imported.
![Screenshot from 2019-12-17 17-56-05](https://user-images.githubusercontent.com/51681435/71014531-bf342580-20fa-11ea-9c93-83dc33d8f3a7.png)

**Note**
During testing on 2.3.3 CE by the same scenario, I had an error.
![Screenshot from 2019-12-17 17-30-00](https://user-images.githubusercontent.com/51681435/71014943-6fa22980-20fb-11ea-8173-faa143081259.png)
It looks like this has been fixed and this change will be included in release 2.3.4.
So I have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Echo** 2019-12-17 16:56 UTC
Labels: Issue: Format is valid
