### ISSUE TITLE
Not able to sync products cost using api /rest/V1/products/cost

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#28371] opened 2020-05-26 13:29 UTC
Hi Magento,

We are using magento version 2.3.0 community edition.
We want to sync the cost but we are not able to sync cost.
API : rest/V1/products/cost
Request : {"prices":[{"cost":100.0,"store_id":0,"sku":"Test Prdouct-104"}]}
Response : []

We are getting empty body in response. how can we solve this ?

**Comment by sambath1293** [comment] 2020-05-27 15:34
Hi @webgility-amazonapi this is a duplicate of #28374 so closing this bug.

**Closed as completed by sambath1293** 2020-05-27 15:34 UTC
Labels: duplicate, Issue: Format is not valid, Reported on 2.3.0
