### ISSUE TITLE
Catalog category can't save data

### ISSUE THREAD

**Issue by zhouzuoxuan** [magento/magento2#30874] opened 2020-11-11 09:16 UTC
vendor/magento/module-eav/Model/Entity/AbstractEntity.php line: 868 
code: $result = $this->walkAttributes('backend/validate', [$object], $object->getCollectExceptionMessages());
Make the data you want to save lost
If this problem has been solved, can anyone tell me a better way?
Thank you very much.

**Comment by zhouzuoxuan** [comment] 2020-11-11 09:20
Step: open the catalog category and select any category to edit. No changes can be saved.
Version: magento2.3.4
Reappear: always reappear
Expectation: data can be saved.

**Comment by jordanvector** [comment] 2020-11-13 16:45
@zhouzuoxuan do have L2 redis caching configured?  There is an issue on 2.3.4 with L2 redis caching and saving category data.

Its fixed in newer versions, there is also a magento cloud patch to fix it as well if you are on magento cloud

**Comment by engcom-Delta** [comment] 2021-01-20 08:53
Hi @zhouzuoxuan , thank you for your report, I'm not able to reproduce issue by steps you [described](https://github.com/magento/magento2/issues/30874#issuecomment-725306843) on clean 2.4-develop
**Result:**
:heavy_check_mark: Category is saved with all input data

Are you able to reproduce this issue on 2.4-develop?

**Comment by engcom-Delta** [comment] 2021-02-24 08:31
@zhouzuoxuan , we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Closed as completed by engcom-Delta** 2021-02-24 08:31 UTC
Labels: Issue: needs update, not-confirmed
