### ISSUE TITLE
Missing backend + no css

### ISSUE THREAD

**Issue by drbn** [magento/magento2#1484] opened 2015-07-14 15:13 UTC
I followed the installation guide except for the sample data.(Apache 2.4.6,PHP 5.6.10,Red Hat 7)
I was able to run the setup with all css and images.It didn't give me any errors during the setup and it installed successful but than the trouble came. The frontend is missing js and css and the backend is just giving  a 404.

Also i tried to do a find in the server for the missing js but i couldn't find it. What can i check/redo ?

172.31.64.13 - - [14/Jul/2015:17:02:22 +0200] "GET /magento2/ HTTP/1.1" 200 18707 "-" "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)"
172.31.64.13 - - [14/Jul/2015:17:02:22 +0200] "GET /magento2/pub/static/frontend/Magento/blank/nl_NL/mage/calendar.css HTTP/1.1" 404 264 "http://172.30.0.222/magento2/" "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)"
172.31.64.13 - - [14/Jul/2015:17:02:22 +0200] "GET /magento2/pub/static/frontend/Magento/blank/nl_NL/css/print.css HTTP/1.1" 404 260 "http://172.30.0.222/magento2/" "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)"
172.31.64.13 - - [14/Jul/2015:17:02:22 +0200] "GET /magento2/pub/static/frontend/Magento/blank/nl_NL/css/styles-l.css HTTP/1.1" 404 263 "http://172.30.0.222/magento2/" "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)"
172.31.64.13 - - [14/Jul/2015:17:02:22 +0200] "GET /magento2/pub/static/frontend/Magento/blank/nl_NL/requirejs/require.js HTTP/1.1" 404 267 "http://172.30.0.222/magento2/" "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)"
172.31.64.13 - - [14/Jul/2015:17:02:22 +0200] "GET /magento2/pub/static/frontend/Magento/blank/nl_NL/css/styles-m.css HTTP/1.1" 404 263 "http://172.30.0.222/magento2/" "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)"
172.31.64.13 - - [14/Jul/2015:17:02:22 +0200] "GET /magento2/pub/static/frontend/Magento/blank/nl_NL/images/logo.svg HTTP/1.1" 404 262 "http://172.30.0.222/magento2/" "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)"
::1 - - [14/Jul/2015:17:02:28 +0200] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.6 () PHP/5.6.10 (internal dummy connection)"
::1 - - [14/Jul/2015:17:02:29 +0200] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.6 () PHP/5.6.10 (internal dummy connection)"
172.31.64.13 - - [14/Jul/2015:17:06:44 +0200] "GET /magento2/admin HTTP/1.1" 404 212 "-" "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)"
172.31.64.13 - - [14/Jul/2015:17:06:51 +0200] "GET /magento2/admin/ HTTP/1.1" 404 213 "-" "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)"

**Comment by xcomSteveJohnson** [comment] 2015-07-14 16:11
Check the page using a browser inspector like Firebug for Firefox. See where the page is calling CSS and JS from and make sure the path exists.

There are at least two possibilities: a) Apache web server rewrites are not enabled; b) You specified the wrong backend-frontname (or Magento base URL) during installation.

Rewrites: http://devdocs.magento.com/guides/v1.0/install-gde/prereq/apache.html#install-ubuntu-apache-rewrites

**Comment by Mackovey** [comment] 2015-07-14 17:12
Or *pub/static/.htaccess* was removed

**Comment by drbn** [comment] 2015-07-14 17:25
shouldn't i find the files like styles-m.css or logo.svg when i do a find in the magento2 folder ?
I'll check if rewriting is enabled (would i need to reinstall if it wasn't on ?)

**Comment by drbn** [comment] 2015-07-14 18:11
I found the problem. I have to change AllowOverride none to All in the httpd.conf for the document root. Thank you all for helping.

<Directory "/var/www/html">
    #
    # Possible values for the Options directive are "None", "All",
    # or any combination of:
    #   Indexes Includes FollowSymLinks SymLinksifOwnerMatch ExecCGI MultiViews
    #
    # Note that "MultiViews" must be named *explicitly* --- "Options All"
    # doesn't give it to you.
    #
    # The Options directive is both complicated and important.  Please see
    # http://httpd.apache.org/docs/2.4/mod/core.html#options
    # for more information.
    #
    Options Indexes FollowSymLinks
    #
    # AllowOverride controls what directives may be placed in .htaccess files.
    # It can be "All", "None", or any combination of the keywords:
    #   Options FileInfo AuthConfig Limit
    #
    AllowOverride All

    #
    # Controls who can get stuff from this server.
    #
    Require all granted
</Directory>

**Comment by xcomSteveJohnson** [comment] 2015-07-14 18:43
Yes, that's correct and no you don't have to reinstall, just restart Apache (for the benefit of someone who might see this).

**Comment by vrann** [comment] 2015-07-16 20:18
@drbn assuming the problem is solved, closing the issue. Feel free to reopen if you had new details.

**Closed by vrann** 2015-07-16 20:18 UTC
Labels: acknowledged, PS, question

**Comment by Mackovey** [comment] 2015-07-18 05:10
I got the same error under windows, boken theme after instalation
It was solved as commented line in app/etc/di.xml

**Comment by tarwin** [comment] 2015-12-16 23:08
I had the same problem on Windows 10. SKovbel's solution fixed it, but I'm not sure what the consequences will be.

**Comment by drbn** [comment] 2015-12-17 03:00
I am out of the office until 21/12/2015.

Gelieve voor dringende zaken naar support@axi.be te mailen


Note: This is an automated response to your message  "Re: [magento2]
Missing backend + no css (#1484)" sent on 17/12/2015 0:24:01.

This is the only notification you will receive while this person is away.
