### ISSUE TITLE
Validation message not displayed in the Calendar widget

### ISSUE THREAD

**Issue by pratikvs** [magento/magento2#32667] opened 2021-04-05 07:53 UTC
**Preconditions**

- Install Magento version 2.4.2
- Create a module to display a custom form . This form has  a calendar field in it. The field is created as per mention in magento devdocs link. Please refer to this link [https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/widgets/widget_calendar.html]
- Added class required , required-entry to the all the text fields including the Calendar field. The code for the calendar field looks like as follows.
```
<div class="field">
    <label>Date : </label>

    <input type="text" class="input-text required required-entry" id="example-date" style="width: auto" name="example-date" />
</div>

<script>
  require([
    'jquery',
    'mage/translate',
    'mage/calendar'
    ], function ($, $t) {
      $('#example-date').calendar({
        changeMonth: true,
        changeYear: true,
        showButtonPanel: true,
        currentText: $t('Go Today'),
        closeText: $t('Close'),
        showWeek: true
      });
    })
</script>
```

**Steps to reproduce**

- Go to custom the form
- Click the submit button

**Actual result:** 
The other fields in the form will give validation error message "This field is required". The text field with calendar widget will not show this message. Only the text field get red in color.

**Expected result :**
The calendar widget field should also display the "This field is required"  message

**Comment by pratikvs** [comment] 2021-04-05 07:58
> Hi @pratikvs. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * Summary of the issue
> * Information on your environment
> * Steps to reproduce
> * Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.4-develop instance` - upcoming 2.4.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> Please, add a comment to [assign the issue](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#assigning-an-issue): `@magento I am working on this`
> 
> * Join [Magento Community Engineering Slack](https://opensource.magento.com/slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.
> 
>  According to the Magento Contribution requirements, all issues must go through the Community Contributions Triage process. Community Contributions Triage is a public meeting.
> 
>  You can find the schedule on the [Magento Community Calendar page](https://opensource.magento.com/community-calendar).
> 
>  The triage of issues happens in the queue order. If you want to speed up the delivery of your contribution, please join the Community Contributions Triage session to discuss the appropriate ticket.
> 
>  You can find the recording of the previous Community Contributions Triage on the [Magento Youtube Channel](https://www.youtube.com/playlist?list=PLDvMskiz68Q2BLkj0-xzjuFl7ZVti9Quj)
> 
>  Feel free to post questions/proposals/feedback related to the Community Contributions Triage process to the corresponding [Slack Channel](https://magentocommeng.slack.com/archives/C016SG16J03)

I have updated the issue please check.

**Comment by magento-engcom-team** [comment] 2021-04-05 11:09
:white_check_mark: Confirmed by @eduard13 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41745` were created

**Issue Available**: @eduard13, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by eduard13** [comment] 2021-04-05 11:26
Hi @pratikvs, as a simple workaround, you may simply add a hidden `button` after the date field, as result, you'll have the error message shown.

Looks like the issue states around these lines.
https://github.com/magento/magento2/blob/be82efbbc04ba9e6619687a4f8742e1035112c5c/lib/web/mage/validation.js#L1873-L1876

Thank you.

**Comment by mrtuvn** [comment] 2021-04-11 00:36
Error happen because your date input missing button (date icon for pickup date) => Validate will miss to check
Here is demo date input in customer register form
![Screenshot from 2021-04-11 07-35-49](https://user-images.githubusercontent.com/1908873/114288290-96c2fe00-9a98-11eb-9a67-13b0998368f2.png)

**Comment by mrtuvn** [comment] 2021-04-11 22:56
I don't think this is a bug! What do you think @eduard13

**Comment by eduard13** [comment] 2021-04-12 05:04
Hi @pratikvs, after having a closer look, it seems that the code sample misses some configurations. Here you can find the whole list of available widget's configurations: https://jqueryui.com/datepicker/#icon-trigger.

Closing as a non issue.
Thank you.

**Closed as completed by eduard13** 2021-04-12 05:04 UTC
Labels: Issue: Confirmed, non-issue, Component: Ui, Component: Validator, Priority: P3, Progress: done

**Comment by magento-engcom-team** [comment] 2021-04-12 05:06
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
