### ISSUE TITLE
Exception during saving category image

### ISSUE THREAD

**Issue by VladyslavSikailo** [magento/magento2#27434] opened 2020-03-25 11:44 UTC
### Preconditions (*)
1. Pure Magento 2.3.4 CE/EE

### Steps to reproduce (https://youtu.be/c0gp_88BEgc)
1. Go to some category edit page
2. Open Content tab
3. Upload Category Image
4. Save category

### Expected result (*)
1. No exception.logs should be

### Actual result (*)
1. var/log/exception.log contains: _[2020-03-25 11:24:23] report.CRITICAL: Something went wrong while saving the file(s). {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): Something went wrong while saving the file(s). at /var/www/html/vendor/magento/module-catalog/Model/ImageUploader.php:224)"} []_

**Comment by ajijshekh123** [comment] 2020-03-25 13:32
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-25 13:32
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-03-25 13:33
Hi @ajijshekh123, here is your [Magento instance](https://i-27434-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27434-2-4-develop.instances.magento-community.engineering/admin_3a0c](https://i-27434-2-4-develop.instances.magento-community.engineering/admin_3a0c)
Login: `27a6d1e9` Password: `fde8f7394f64`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2020-03-25 13:47
Hi @Dren7755 ,
I have verified this issue as per your steps on the latest Magento 2.4 Instance. But I can't able to reproduce this issue.
Can you please share the video?
I think this issue is related to the customization code.

Thanks.

**Comment by Dren7755** [comment] 2020-03-25 15:34
> Hi @Dren7755 ,
> I have verified this issue as per your steps on the latest Magento 2.4 Instance. But I can't able to reproduce this issue.
> Can you please share the video?
> I think this issue is related to the customization code.
> 
> Thanks.

Hi @ajijshekh123 
You can check the video: https://youtu.be/c0gp_88BEgc

How you checked exception.log by magento-engcom-team's Magento Instance? As I understand, you don't have access to file system of this instance)

**Comment by ajijshekh123** [comment] 2020-03-26 04:31
Hi @Dren7755 ,
Thanks for the send the video. You are right. I don't have access to the file system.
This issue needs to developer help.

Thanks.

**Comment by krishprakash** [comment] 2020-03-26 04:38
Hi @Dren7755. Thank you for your report.Looks like issue is for Magento Enterprise Edition so we need to move this issue to it's separate repository
@sdzhepa Kindly move this issue to EE repo.

**Comment by Dren7755** [comment] 2020-03-26 13:42
> Hi @Dren7755. Thank you for your report.Looks like issue is for Magento Enterprise Edition so we need to move this issue to it's separate repository
> @sdzhepa Kindly move this issue to EE repo.

I have also reproduced it on pure CE Magento 2.3.4 installation.

**Comment by hostep** [comment] 2020-03-28 11:54
I can reproduce the issue as described on Magento OS 2.3.4, but I can't reproduce it on Magento OS 2.4-develop, which most likely means that it got solved and the fix will most likely be included in Magento 2.4.0
Maybe somebody can try to find the commit which fixed this issue by doing some git bisecting?

**Comment by krishprakash** [comment] 2020-09-29 10:37
Hi @Dren7755. Issue may be fixed in 2.4-develop branch.
Feel free to reopen the issue once you confirm that issue is reproduce on 2.4-develop branch 
Thanks!!

**Closed as completed by krishprakash** 2020-09-29 10:37 UTC
Labels: Issue: Format is valid, Triage: Dev.Experience, Progress: done, Reported on 2.3.4
