### ISSUE TITLE
Custom Options mess

### ISSUE THREAD

**Issue by Grumag** [magento/magento2#3417] opened 2016-02-16 07:52 UTC
Magento 2.0.2. This bug occurred yesterday, and cache and indexes are not fixing it. 

Can't create new products with Custom Options. When choosing any of the Input Types under the this error was produced:
Uncaught ReferenceError: rowTmpl is not defined
followed by 
Uncaught TypeError: this.addSelection is not a function

seems to be happening in custom-options.min.js

Existing products are also bugged. For example, product is showing 2 text fields front-end and it's working fine, but in admin it is only showing 1 text field.

Any ideas anyone? 

Thanks!

**Comment by Grumag** [comment] 2016-02-18 07:26
Rolled back the DB few days back, no change.
New Magento 2.0.2 install (dev), pointing to old DB. still nothing..  Same issue. Same console errors.

Some bug completely broke down Admin custom options and who knows what else. The only option seems to be to start the site all over again, but who is to say it wont happen again?

**Comment by Grumag** [comment] 2016-02-19 05:06
The bug has also broken down checkout, just noticed. Once you click on Go to Checkout, only the logo at the top and Copyright at the bottom are loaded. Middle of the page has a circle that just keeps spinning for hours.

Is there anything that I can try to address this bug?

**Comment by Grumag** [comment] 2016-02-23 23:59
Is this is a know issue?

**Comment by keyurshah** [comment] 2016-03-03 17:47
I'm having the same issue, can't add new rows after attempting to create an option. On 2.0.2

The error I see in console is this:

```
custom-options.min.js:14 

Uncaught ReferenceError: rowTmpl is not defined
$.widget._bindUseDefault @ custom-options.min.js:14
(anonymous function) @ jquery-ui-1.9.2.min.js:26
_on.change select[id^=product_option_][id$=_type] @ custom-options.min.js:10
handlerProxy @ jquery-ui-1.9.2.min.js:42
jQuery.event.dispatch @ jquery.min.js:309
elemData.handle @ jquery.min.js:282

custom-options.min.js:2 

Uncaught TypeError: this.addSelection is not a function_on.click button[id^=product_option_][id$=_add_select_row] @ custom-options.min.js:2
handlerProxy @ jquery-ui-1.9.2.min.js:42
jQuery.event.dispatch @ jquery.min.js:309
elemData.handle @ jquery.min.js:282
```

**Comment by Grumag** [comment] 2016-03-03 17:58
I had to roll back few weeks to a version before the bug happened. Couldn't find any help or other solution. Don't know how the bug occurred, or if it is going to occur again.

**Comment by keyurshah** [comment] 2016-03-03 18:16
that's interesting. I'm on a fresh install. I've had enabled javascript minification. After your message, I then turned off "Minify Javascript" (while on production mode) and then the error stopped. 

So it seems to be something with the server generated javascript minify feature.

**Comment by Grumag** [comment] 2016-03-03 19:26
I think you hit the nail in the head with that one. I haven't enabled Minify JavaScript since the rollback. I was about to do it today, as I did enable everything else. When I experienced the bug my JS was minimized.

Definitely not enabling it now. Will be interesting to see if it happens to others as well.

**Comment by devdesco-ceo** [comment] 2016-04-30 04:10
Same problem here when trying to edit Custom Options in Virtual Product. M2.0.4. :-1:

**Comment by wittness87** [comment] 2016-09-30 13:32
Has anyone found a fix for this yet? We have upgrade to 2.0.9 and still have the same issue.

**Comment by veloraven** [comment] 2016-10-06 14:56
Can you provide your settings?
Especially for JavaScript Settings (Stores ->Configuration -> Advanced ->  Developer) and which mode is used.
I was not able to reproduce this issue.

**Comment by Grumag** [comment] 2016-10-18 04:12
Hello,

It happened just now with a new install (not even the same server as in February). I was editing products, I added a custom option (2 radio buttons). I clicked on save and nothing happened. Flushed cache  / re-indexed, tried saving but still nothing --> won't save. Moved to another product in the list (I imported ~ 200 products with basic info and I am adding more detail to products) and noticed that when I save lets say product with ID 283, the changes were actually applied to product with ID 284. 

I can give you access to admin if you want to see the bug in action. Hosting is done by Nexcess, Magento 2.1.2, PHP 7.

At this point this installation is ruined, as in no one knows how to fix it. I would have to roll back to yesterday's DB / setting to fix.

Furthermore, this time around I haven't touched anything under Stores ->Configuration -> Advanced -> Developer, unlike back in February. 
- Merge JavaScript Files : No
- Enable JavaScript Bundling : No
- Minify JavaScript Files: No

The bug, and there is a bug - and it is HUGE, happens when Customizable Options are added, so if you want to re-create it try editing few hundreds of items with Customizable options, maybe try to import some basic information first.

**Comment by tiffanyqm** [comment] 2016-11-01 22:02
It's not a permanent fix by any means (take care that when rebuilding, deploying, etc. you could overwrite this change), but to keep yourself from needing to restore or take other drastic measures, replacing the content of the custom-options.min.js with custom-options.js (the unminified version) in /pub/static/adminhtml/Magento/backend/en_US/Magento_Catalog/js/ will _temporarily_ allow you to edit product custom options in the admin again. I haven't tested yet, but I think the issue might be with this syntax after minification: 

```
addSelection: function (event) {
            var data = {},
                element = event.target || event.srcElement || event.currentTarget,
                rowTmpl;
```

**Comment by dmitriyprime** [comment] 2017-06-23 13:03
We cannot reproduce this issue as described. May you please advise if this problem is still relevant for latest release Magento 2?

**Closed as completed** 2017-09-18 16:59 UTC
Labels: bug report, Progress: needs update, Component: Catalog, Issue:  Cannot Reproduce, Issue: Format is not valid
