### ISSUE TITLE
Magento 2.4.3 - Shipping cost and product prices on checkout page show as 0.00

### ISSUE THREAD

**Issue by xtremevision** [magento/magento2#34727] opened 2021-11-29 13:56 UTC
### Preconditions (*)

1. Migrated site from Magento 1.9.3.6
2. When upgrading to Magento 2.4.3
2. Dedicated production server running Plesk Obsidian Version 18.0.39 Update #2
3. Nginx 1.20.1-2.centos.7+p18.0.39.2+t211117.1817 used as proxy to apache
4. Apache 2.4.6-97.el7.centos.2
5. MariaDB 10.2.41-1.el7.centos
6. PHP 7.4.26-1centos.7.211118.1928

### Steps to reproduce (*)

I don't know how you can reproduce it since this is happening only on the above server, with the above configuration.

### Expected result (*)

1. Checkout to display the shipping cost
2. Checkout to display product prices in the summary block

### Actual result (*)

1. Shipping cost is displayed as 0.00 although the ajax call returns 16.40
2. Product price in the summary block is displayed as 0.00 despite the ajax call returning the correct price 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

The production site is running Magento 2.4.2 on the same production server. Upgrading to Magento 2.4.2-p1 and p2 work just fine, everything behaves as expected. The moment I upgrade to Magento 2.4.3 the checkout is affected.

I tried disabling all 3rd party modules and the theme, with no luck. The default Magento checkout page still shows 0.00 and 0.00 for shipping and product prices.

**Cloning the same site (the upgraded 2.4.3 version) to a development server, without Plesk and nginx works just fine.**

I have tried a million combinations with no luck. Something is going on with the production server, that I have not been able to identify. See screenshots with expected and actual results.

Any help would be appreciated, I am at wits end.
![2021-11-29 08 46 41](https://user-images.githubusercontent.com/6533394/143880708-23d96e4e-a345-48d3-ba9a-96feacdbf44b.png)

![2021-11-29 08 53 29](https://user-images.githubusercontent.com/6533394/143880718-20247512-27b8-4d8d-a19b-e591137080bf.png)

**Comment by xtremevision** [comment] 2021-11-29 14:10
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by xtremevision** [comment] 2021-11-29 14:29
Not reproduceable on the vanilla Magento develop instance.

**Comment by xtremevision** [comment] 2021-11-29 14:39
From what I can tell, unless I am wrong, it looks like the checkout sections are not being updated on refresh. Inspecting the ajax requests shows the correct information returned.

**/rest/default/V1/guest-carts/G9e717t6yjHzG91JKWePSwPlERC9Ycib/shipping-information:**
[{"carrier_code":"fancourier_customshipping","method_code":"Cont_Colector","carrier_title":"FAN Courier","method_title":"<a href=\"https:\/\/www.selfawb.ro\/order.php?order_id=f1bc49776f2b36bae4e24df493fe399b\" target=\"_blank\">Cont Colector<\/a>","amount":16.4,"base_amount":16.4,"available":true,"error_message":"","price_excl_tax":16.4,"price_incl_tax":16.4}]

**/rest/default/V1/guest-carts/G9e717t6yjHzG91JKWePSwPlERC9Ycib/totals?_=1638196233686:**
{"grand_total":116.15,"base_grand_total":116.15,"subtotal":99.75,"base_subtotal":99.75,"discount_amount":0,"base_discount_amount":0,"subtotal_with_discount":99.75,"base_subtotal_with_discount":99.75,"shipping_amount":16.4,"base_shipping_amount":16.4,"shipping_discount_amount":0,"base_shipping_discount_amount":0,"tax_amount":0,"base_tax_amount":0,"weee_tax_applied_amount":null,"shipping_tax_amount":0,"base_shipping_tax_amount":0,"subtotal_incl_tax":99.75,"shipping_incl_tax":16.4,"base_shipping_incl_tax":16.4,"base_currency_code":"RON","quote_currency_code":"RON","items_qty":1,"items":[{"item_id":189828,"price":99.75,"base_price":99.75,"qty":1,"row_total":99.75,"base_row_total":99.75,"row_total_with_discount":0,"tax_amount":0,"base_tax_amount":0,"tax_percent":0,"discount_amount":0,"base_discount_amount":0,"discount_percent":0,"price_incl_tax":99.75,"base_price_incl_tax":99.75,"row_total_incl_tax":99.75,"base_row_total_incl_tax":99.75,"options":"[]","weee_tax_applied_amount":null,"weee_tax_applied":null,"name":"Filtru Cascada Ultra Slim Hang On US-1"}],"total_segments":[{"code":"subtotal","title":"Subtotal","value":99.75},{"code":"shipping","title":"Livrare si manipulare(FAN Courier - <a href=\"https:\/\/www.selfawb.ro\/order.php?order_id=cf3c89896552dab6a6b85a46dd1285cd\" target=\"_blank\">Cont Colector<\/a>)","value":16.4},{"code":"tax","title":"Taxe","value":0,"extension_attributes":{"tax_grandtotal_details":[]}},{"code":"grand_total","title":"Total general","value":116.15,"area":"footer"}]}

**Comment by xtremevision** [comment] 2021-11-29 14:48
I've just noticed the same thing is happening in the cart page, in the shipping estimator, the amount is 0.00 instead of 16.40. The Ajax request returns the shipping cost, but the estimator block does not update.

![2021-11-29 09 47 23](https://user-images.githubusercontent.com/6533394/143889011-b6c0783d-fad9-4026-a73c-6e4a24d84ca0.png)

**Comment by xtremevision** [comment] 2021-12-01 12:08
Hi, anything I can do to help?

**Comment by chernenm** [comment] 2021-12-03 20:07
@magento give me 2.4.3 instance with edition ee

**Comment by engcom-November** [comment] 2021-12-16 13:52
Hi @xtremevision ,
It looks like this is a duplicate of https://github.com/magento/magento2/issues/33856 that was already fixed in the 2.4-develop branch. For more info, please check the [comment](https://github.com/magento/magento2/issues/33856#issuecomment-946761019)

**Comment by xtremevision** [comment] 2021-12-16 14:19
Mmm... I will try this patch and see what mileage I get. Thank you.
But how do you explain it is working fine or one server but not on another? Same codebase/version, but different hosting stack?

**Comment by engcom-November** [comment] 2021-12-23 12:29
Hi @xtremevision ,
This issue was fixed in the 2.4-develop branch (latest code base), which wasn't yet included in the latest release. Hence this is not reproducible on 2.4-develop version. Kindly recheck on 2.4-develop branch and provide missing steps if any if you are still facing issues.
Thank you.

**Comment by frilogg** [comment] 2021-12-30 21:43
@engcom-November where can we find the solution? I have  a couple of Norwegian pages where this error occur in Magento 2.4.3-p1

**Comment by engcom-November** [comment] 2021-12-31 11:52
Hi @frilogg , 
As a workaround, kindly apply this https://github.com/magento/magento2/commit/ae304d43cd36322b1ff8145d70c9b2e9aeb0cde as a patch and confirm if you are still facing the issue.
Thank you.

**Comment by calvinmuller** [comment] 2022-01-14 07:29
@engcom-November How do I apply this as a patch to a magento installed via composer? `2.4.3-p1` ?

**Comment by engcom-November** [comment] 2022-01-28 11:24
Hi @calvinmuller ,
Please refer the Magento [devdocs](https://devdocs.magento.com/cloud/project/project-patch.html) guide which can help you apply patch in specific environment.
Thank you.

**Comment by engcom-Hotel** [comment] 2022-02-16 14:08
Dear @xtremevision,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-02-16 14:08 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
