### ISSUE TITLE
Credit Memo Show Wrong Currency Code on sales_order_credit_memo grid in magento 2.4.2

### ISSUE THREAD

**Issue by sprajapat770** [magento/magento2#32182] opened 2021-02-16 11:43 UTC
### Preconditions (*)

1.You Should Have Magento 2.4.2
2. Two Websites and Different Currency Setup

### Steps to reproduce (*)

1.Create An Order From Admin Or Storefront on your secod website
2.Now Accept Order and Create Credit Memo.
3. Look at both grids now they have different currency sign.

### Expected result (*)

1. sales order credit memo grid should show currency dollar as like sales order grid show

### Actual result (*)

1. ![Configuration_Settings_Stores_Magento_Admin](https://user-images.githubusercontent.com/57035224/108058361-f0e7aa00-7079-11eb-8bf8-a8c41a9cd4dd.png)
2.
 ![Ina_Compression_Short_Red_Products_Inventory_Catalog_Magento_Admin](https://user-images.githubusercontent.com/57035224/108058391-fb09a880-7079-11eb-8098-2758ee9ff918.png)

3.
![Credit_Memos_Operations_Sales_Magento_Admin](https://user-images.githubusercontent.com/57035224/108058388-f9d87b80-7079-11eb-8f75-1e9bf78dc1db.png)
4. ![Orders_Operations_Sales_Magento_Admin](https://user-images.githubusercontent.com/57035224/108058395-fba23f00-7079-11eb-8b39-cd25fcbc7f96.png)
5.
![Screenshot from 2021-02-16 17-20-03](https://user-images.githubusercontent.com/57035224/108059482-97807a80-707b-11eb-9cfa-1b4dd5bef949.png)
6.
![Screenshot from 2021-02-16 17-20-34](https://user-images.githubusercontent.com/57035224/108059494-9c452e80-707b-11eb-90f7-52394255d065.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment] 2021-02-17 08:25
Hi @sprajapat770 . Thank you for your report! 
Unfortunately, we are not able to reproduce this issue on a fresh 2.4-develop. Looks like the problem has already been fixed.

**_Precondition:_**

 Two Websites and Different Currency Setup

- Main Website - Indian Rupee;
- Second Website - US Dollar

**Manual testing scenario:**

1.Create An Order From Admin Or Storefront on your Second website
2.Now Accept Order and Create Credit Memo.
3. Look at both grids;

**Actual Result:** :heavy_check_mark: sales order credit memo grid shows currency dollar as like sales order grid show

![2021-02-17_10-14](https://user-images.githubusercontent.com/51679138/108175971-11f7db80-710a-11eb-820b-5e4125ce3f08.png)
![2021-02-17_10-23](https://user-images.githubusercontent.com/51679138/108176114-44093d80-710a-11eb-979f-ee3ae8302803.png)
![2021-02-17_10-24](https://user-images.githubusercontent.com/51679138/108176127-466b9780-710a-11eb-8726-5b7f8052c138.png)

@sprajapat770 Maybe we missed something?
Could you take a look?
Thanks!

**Comment by sprajapat770** [comment] 2021-02-20 04:52
@engcom-Alfa i am also thinking you are missing something. So am sharing you again probelm

precondition
1. You should have Magento 2.4.2 setup
2. Should have 2 running websites with different currency setup like I have. 
3. I have 2 websites -- a) Main website -- indian currency b) second website -- us dollar currency
c) base currency as indian rupee. 
4. I order on second website which have dollar currency and creat credit memo for that order and I face this issue. 
5. You should notice I was having two different currency setups for both the websites. 
6. You can create order for both the websites and then create credit memo for both than look in credit memo grid. 
7. After all this previous conditions So you should have two different currency code in grid if you found both currency than inform me.

**Comment by engcom-Oscar** [comment] 2021-03-12 15:26
Hi @sprajapat770!
I also can't reproduce the issue following steps in the ticket.
I have Currency setup for Main Website 
![Screenshot from 2021-03-12 16-47-12](https://user-images.githubusercontent.com/60198413/110959700-a5fa4300-8356-11eb-819a-8ee2bc0be8de.png)
and for test website:
![Screenshot from 2021-03-12 16-47-28](https://user-images.githubusercontent.com/60198413/110959768-b4e0f580-8356-11eb-9508-ab3bffafeac5.png)
After placing order from test website:
![Screenshot from 2021-03-12 16-47-41](https://user-images.githubusercontent.com/60198413/110959873-cde9a680-8356-11eb-9cb5-50067b2089ee.png)
I made Credit memo for this oder:
![Screenshot from 2021-03-12 16-47-55](https://user-images.githubusercontent.com/60198413/110959922-dd68ef80-8356-11eb-89ea-0a1af3a2cbe5.png)
Currency in both grids is correct (USD)

So, we have to close this ticket.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch.
 Thank you for collaboration.

**Closed as completed by engcom-Oscar** 2021-03-12 15:26 UTC
Labels: not-confirmed

**Comment by sprajapat770** [comment] 2021-03-13 13:40
@m2-community-project and @engcom-Oscar i recorded a video for this please look at the video i share you the exact issue and i mentioned in issue that this is issue of credit memo grid not the order grid.
https://www.awesomescreenshot.com/video/3050766?key=eb65fd2e4927f556f26c3f7a2fbc87dd
