### ISSUE TITLE
If you going to reorder for Virtual product or Downloadable Product from admin panel "You don't need to select a shipping address." this label overlapping over the checkbox

### ISSUE THREAD

**Issue by cedarvinda** [magento/magento2#25086] opened 2019-10-16 10:05 UTC
If you going to reorder for Virtual product or Downloadable Product from admin panel **"You don't need to select a shipping address."** this label overlapping over the checkbox

### Preconditions (*)
1. php 7.2
2. Magento 2.3.x

### Steps to reproduce (*)
1. Go frontent and make an order for Vertual or Downloadable product
2. now login to admin panel and view same order you have done 
3. Now click on **Reorder** button in top and scroll page to Billing address section right side is Shipping address section, And refer screenshot bellow ..

### Expected result (*)

![image](https://user-images.githubusercontent.com/26018716/66907758-793de100-f027-11e9-9512-5aa37a3231e8.png)

### Actual result (*)
![image](https://user-images.githubusercontent.com/26018716/66907876-b1ddba80-f027-11e9-9814-d557dfab7794.png)

**Comment by magento-engcom-team** [comment] 2019-10-16 10:07
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21864` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-10-16 10:08
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21864` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment] 2020-08-18 21:54
I am not able to reproduce this issue on the latest `2.4-develop` possibly it was already fixed.

**Closed as completed by sdzhepa** 2020-08-18 21:54 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Admin
