### ISSUE TITLE
Upgrade process failed

### ISSUE THREAD

**Issue by jotadrilo** [magento/magento2#4853] opened 2016-06-03 11:28 UTC
**Steps to reproduce**
1. Upgrade from the latest CE version to 2.10.rc1
2. I ran into this this issue

```
[2016-06-03 03:52:04 PDT] Job "maintenance_mode {"enable":true}" has been started
[2016-06-03 03:52:04 PDT] Magento maintenance mode is enabled.
[2016-06-03 03:52:04 PDT] Job "maintenance_mode {"enable":true}" has successfully completed
[2016-06-03 03:52:04 PDT] Job "update {"components":[{"name":"magento/product-community-edition","version":"2.1.0-rc1"}]}" has been started
[2016-06-03 03:52:04 PDT] Starting composer update...
[2016-06-03 03:52:04 PDT] ./composer.json has been updated

[2016-06-03 03:54:03 PDT] Update is already in progress.
[2016-06-03 03:54:34 PDT] Loading composer repositories with package information
Updating dependencies (including require-dev)
- Removing magento/framework (100.0.9)
- Installing magento/framework (100.1.0-rc1)
Downloading: Connecting... Downloading: 0% Downloading: 5% Downloading: 10% Downloading: 15% Downloading: 20% Downloading: 25% Downloading: 30% Downloading: 35% Downloading: 40% Downloading: 45% Downloading: 50% Downloading: 55% Downloading: 60% Downloading: 65% Downloading: 70% Downloading: 75% Downloading: 80% Downloading: 85% Downloading: 90% Downloading: 95% Downloading: 100% Downloading: 100%

- Removing magento/language-zh_hans_cn (100.0.5)
- Installing magento/language-zh_hans_cn (100.1.0-rc1)
Downloading: Connecting... Downloading: 0%  Downloading: 100%

...


Module 'Magento_CatalogWidget':
Module 'Magento_Wishlist':
Please re-run Magento compile command

[2016-06-03 10:55:12 UTC] Job "setup:upgrade {"command":"setup:upgrade"}" has been successfully completed
[2016-06-03 10:55:12 UTC] Job "setup:static:regenerate []" has started

[2016-06-03 10:55:12 UTC] Cleaning generated files...
[2016-06-03 10:55:12 UTC] Clearing cache...
[2016-06-03 10:55:12 UTC] Cleaning static view files
[2016-06-03 10:55:12 UTC] Job "setup:static:regenerate []" has been successfully completed
[2016-06-03 03:56:02 PDT] Job "maintenance_mode {"enable":false}" has been started
[2016-06-03 03:56:02 PDT] Magento maintenance mode is disabled.
[2016-06-03 03:56:02 PDT] Job "maintenance_mode {"enable":false}" has successfully completed

[2016-06-03 10:56:06 UTC] An error occurred while executing job "setup:cache:enable ["config layout block_html collections reflection db_ddl eav config_integration config_integration_api full_page translate config_webservice compiled_config"]": Could not complete setup:cache:enable ["config layout block_html collections reflection db_ddl eav config_integration config_integration_api full_page translate config_webservice compiled_config"] successfully: The following requested cache types are not supported: 'compiled_config'.
Supported types: config, layout, block_html, collections, reflection, db_ddl, eav, customer_notification, full_page, config_integration, config_integration_api, translate, config_webservice
```

I'm not sure if `compiled_config` was supported in the previous version or if I should not upgrade but migrate to 2.1.0.rc1. I tried to figure out what is wrong but I got nothing. 

Did you see this error before? Could be related to the new version and upgrading incompatibilities?

**Comment by AirmanAJK** [comment] 2016-06-10 21:21
I upgraded from CE version 2.1.0.rc1 to 2.1.0.rc2 using the Magento System Upgrade Wizard and received the following error in the console log:

> An error occurred while executing job "setup:cache:enable ["compiled_config"]": Could not complete setup:cache:enable ["compiled_config"] successfully: The following requested cache types are not supported: 'compiled_config'.
> Supported types: config, layout, block_html, collections, reflection, db_ddl, eav, customer_notification, full_page, config_integration, config_integration_api, translate, config_webservice

I previously upgraded using the CLI to get to 2.1.0.rc1.

**Comment by magnetic5355** [comment] 2016-06-13 13:21
Same issue after running setup:upgrade using git clone on develop branch

**Comment by simobenso** [comment] 2016-08-22 22:47
same error occured while enabling new component installed via marketplace on 2.1.0 CE

**Comment by ttnnkkrr** [comment] 2016-09-01 19:57
same error occured while enabling new component installed not via marketplace on 2.1.0 CE

**Comment by ttnnkkrr** [comment] 2016-09-01 19:58
I would really like to know if there is ever going to be a problem free Magento 2.x iteration that is going to work out of the box

**Comment by doomdance** [comment] 2016-09-01 23:36
Looks to be duplicate of #6078 which has a workaround

**Comment by magento-engcom-team** [comment] 2017-10-03 10:58
Closing as duplicate per comment above.

**Closed as completed by magento-engcom-team** 2017-10-03 10:58 UTC
Labels: bug report, Issue: Format is not valid
