### ISSUE TITLE
Subtotal (Excl. Tax) Cart Price Rule Condition not working for edit order and reorder

### ISSUE THREAD

**Issue by jerome-zhang** [magento/magento2#25726] opened 2019-11-25 07:11 UTC
### Preconditions (*)

1. Create a latest Magento instance with sample free shippping rule: "Spend $50 or more - shipping is free!"
2. Edit the rule to change condition from **Subtotal** to **Subtotal (Excl. Tax)** https://www.screencast.com/t/xxw3Uc4Q
3. Create an BE order with amount equals or greater than $50

### Steps to reproduce (*)

1. Open the newly create order
2. Click on **reorder** or **edit** button
3. After page redirect to order creation page, you will see the Free Shipping Cart Price Rule is not applied to the order

### Expected result (*)

1. Free shipping rule should be applied and order shipping amount should be $0

### Actual result (*)

1. Free shipping rule not applied to the order on page loaded

**Comment by abrarpathan19** [comment] 2019-11-25 07:30
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-25 07:30
Hi @abrarpathan19. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-25 07:31
Hi @abrarpathan19, here is your [Magento instance](https://i-25726-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25726-2-3-develop.instances.magento-community.engineering/admin](https://i-25726-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2019-11-25 10:04
Hi @jerome-zhang,
I have verified your issue in Latest Magento 2.3 Instance with your steps and conditions.
I am not able to reproduce this issue. Please review the below-attached video and Let me know which points I have missed it.
See the attached video:
![Reorder_CouponCode_Issue](https://user-images.githubusercontent.com/24711761/69530975-12ea9d80-0f99-11ea-8335-71c30fb0c348.gif)

@jerome-zhang - Please send a video or proper step on your end.

Thanks.

**Comment by jerome-zhang** [comment] 2019-11-26 02:17
Hi @ajijshekh123 , Actually i was creating order from admin, and use free shipping cart price rule action. Please see my video to reproduce the issue: https://www.screencast.com/t/LLIb1RTA46

**Comment by ajijshekh123** [comment] 2019-11-26 04:20
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-26 04:20
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-26 04:21
Hi @ajijshekh123, here is your [Magento instance](https://i-25726-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25726-2-3-develop.instances.magento-community.engineering/admin](https://i-25726-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2019-11-26 04:46
Issue reproduced as per the attached video steps and scenario.

**Comment by magento-engcom-team** [comment] 2019-11-26 04:47
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29176` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by frostbitten** [comment] 2019-12-03 22:32
Just want to note this has the potential to create another issue when an order is edited after a Cart Price Rule expires. Sorry if this should be opened as a separate issue but I figure it likely to come up.

**Comment by sdzhepa** [comment] 2020-09-16 19:50
The issue should be re-verified and re-confirmed on the latest `2.4-develop` code.

**Comment by engcom-Oscar** [comment] 2020-09-17 09:17
Hello @jerome-zhang 

Thank you for your report.
Unfortunately, I was not able to reproduce this issue on the latest `2.4-develop` code. Probably it was already fixed and will appear in the next release. Or we missed some steps or preconditions.
If you have some more details how to reproduce this issue on latest 2.4 Magento, feel free to update the description and reopen it.

**Closed as completed by engcom-Oscar** 2020-09-17 09:17 UTC
Labels: Issue: Ready for Work, Component: Sales, Component: Shipping, Issue: Clear Description, Issue: Format is valid, Component: Admin, Progress: done
