### ISSUE TITLE
I dont want to use welcome message

### ISSUE THREAD

**Issue by farzeen-cloud** [magento/magento2#38175] opened 2023-11-14 11:55 UTC
### Preconditions and environment

- 2.4.6-p2

### Steps to reproduce

1. Navigate to Content->Design->Configuration
2. Edit Theme, Leave welcome message empty in Header Section

### Expected result

I dont want to use Welcome Message

### Actual result

Now Homepage Got error. I dont want to use welcome message
![Screenshot from 2023-11-14 17-23-05](https://github.com/magento/magento2/assets/80716853/b0ccd94e-db25-48be-8b37-664d57160ed7)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by devchris79** [comment] 2023-11-14 13:43
This sounds like a duplicate of #37208

**Comment by engcom-Bravo** [comment] 2023-11-15 06:13
Hi @farzeen-cloud,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

1. Navigate to Content->Design->Configuration
2. Edit Theme, Leave welcome message empty in Header Section


<img width="1408" alt="Screenshot 2023-11-15 at 11 40 54 AM" src="https://github.com/magento/magento2/assets/51680745/dc6395bd-5f4e-4e26-82e6-3797f3985a6d">




The issue is fixed with this commit https://github.com/magento/magento2/commit/4b5c1dc1382c2e6e144789c49db27c9085146551 and it is no longer reproducible in Magento 2.4-develop instance and also changes included in Magento latest version.


Thanks.

**Comment by ananth-iyer** [comment] 2023-11-20 06:22
@farzeen-cloud If you don't plan to upgrade yet, then add a space in the welcome text. It'll fix the issue temporary.

**Comment by engcom-Bravo** [comment] 2023-11-23 06:19
@ananth-iyer Thanks for your contribution & collaboration over here.

@farzeen-cloud,

Please refer this comment https://github.com/magento/magento2/issues/38175#issuecomment-1818297355 and if you are still facing any issue please let us know.

Thanks.

**Closed as completed** 2023-12-04 04:55 UTC
Labels: Issue: needs update, Reported on 2.4.6-p2
