### ISSUE TITLE
Advance Pricing - Customer Group Price , Select box and Text box alignment issue

### ISSUE THREAD

**Issue by SyntaxKay** [magento/magento2#19472] opened 2018-11-30 06:01 UTC
### Preconditions (*)

1.Magento 2.3-Develop

### Steps to reproduce (*)

1.Open  Catalog > Product > Add/Edit Product
2. Open Advance Pricing 

### Expected result (*)

 ![expected](https://user-images.githubusercontent.com/33230237/49271375-51876e00-f493-11e8-96f9-91590b6b1db6.jpg)

### Actual result (*)

![actual](https://user-images.githubusercontent.com/33230237/49271387-66fc9800-f493-11e8-8cd2-a1edd4ef3689.jpg)

**Comment by magento-engcom-team** [comment] 2018-11-30 06:01
Hi @speedy008. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@speedy008 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-12-07 16:16
Hi @speedy008. Thank you for your report. 
The issue has been fixed in magento/magento2#19473 by @speedy008 in 2.3-develop branch
Related commit(s):
 - [c4294625e6c2da06468a349a45fe41cf265c7def](https://github.com/magento/magento2/commit/c4294625e6c2da06468a349a45fe41cf265c7def)
 - [22daf662fe84b54c3f3c10e5c2ebc84745915e2b](https://github.com/magento/magento2/commit/22daf662fe84b54c3f3c10e5c2ebc84745915e2b)
 - [1e919a577dd950d8e4d776c050ddbc94e6135492](https://github.com/magento/magento2/commit/1e919a577dd950d8e4d776c050ddbc94e6135492)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2018-12-07 16:16 UTC
Labels: Issue: Ready for Work, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Backend
