### ISSUE TITLE
Customer Account Share per Website causes Exception in Admin when adding addresses

### ISSUE THREAD

**Issue by davidhiendl** [magento/magento2#36509] opened 2022-11-22 15:42 UTC
### Preconditions and environment

When attempting to add an address to a customer entity in the admin area a "NoSuchEntity" exception is thrown because the website id does not exist. This happens because https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/Model/ResourceModel/Address/Attribute/Source/CountryWithWebsites.php#L131 us using a storeId as websiteId when looking up available options in the option source.

- Magento version: 2.4.5

### Steps to reproduce

- Create a customer in a store with a store id that does not have a corresponding website id (for create 1 website, 3 stores and use the last store, to ensure the store id does not also exist in the website table)
- Create customer or signup as customer
- Open customer in admin area
- Switch to address tab and attempt to add address

### Expected result

No exception, adding an address should be allowed

### Actual result

An exception is thrown, because they requested website id does not exist.
![image](https://user-images.githubusercontent.com/11006964/203349602-30013940-3b9b-40de-951e-8541503421ff.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-11-23 05:06
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-23 09:06
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-23 12:16
Hi @davidhiendl,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screemshots.


**Steps to reproduce**

1.Create a customer in a store with a store id that does not have a corresponding website id (for create 1 website, 3 stores and use the last store, to ensure the store id does not also exist in the website table)
2.Create customer or signup as customer
3.Open customer in admin area
4.Switch to address tab and attempt to add address


No Exception We are able to add the address successfully.


<img width="1449" alt="Screenshot 2022-11-23 at 3 42 01 PM" src="https://user-images.githubusercontent.com/51680745/203544537-f84c9297-94b6-42a4-a2ae-6889e27e0568.png">



Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment] 2022-12-08 06:08
HI @davidhiendl,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by davidhiendl** [comment] 2023-01-29 14:16
@hostep Thanks for confirming as well. Sadly I dropped the ball in re-confirming the issue since I patched it myself.
I think the reason it was not reproducible is because I did not mention the flag `Share Customer Accounts = Global`

**Comment by engcom-Hotel** [comment] 2023-01-30 02:27
Thanks @hostep for the updates. Let me reopen this issue for further processing.

**Comment by engcom-Bravo** [comment] 2023-01-30 11:44
Hi @hostep,

Thanks for your contribution & collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible but There is an ongoing confirmed issue [here](https://github.com/magento/magento2/issues/36582) for the same. Kindly move on to this issue for latest updates / solutions on the same.

We are closing this as duplicate.

Thanks.

**Closed as completed by engcom-Bravo** 2023-01-30 11:44 UTC
Labels: duplicate, Issue: ready for confirmation, Reported on 2.4.5

**Comment by davidhiendl** [comment] 2023-01-30 15:56
@engcom-Bravo Technically this is not a duplicate since it was reported first.

**Comment by simonmaass** [comment] 2023-08-16 12:49
@davidhiendl do you mind sharing a patch file?

**Comment by hostep** [comment] 2023-08-23 19:32
@simonmaass: the fix should be these changes: https://github.com/magento/magento2/pull/36583, here's a patch (but you might need to change some filenames): https://patch-diff.githubusercontent.com/raw/magento/magento2/pull/36583.diff
