### ISSUE TITLE
Problem with adding to cart with the es_CL locale

### ISSUE THREAD

**Issue by AlexandreKhayrullin** [magento/magento2#7502] opened 2016-11-21 11:00 UTC
### Preconditions
The Magento used is the "develop" branch.
PHP: PHP 7.0.10-1+deb.sury.org~xenial+1

### Steps to reproduce

1. Change the frontend locale to es_CL (Chilean Spanish)
2. Add a product to cart with a quantity higher than 1

### Expected result
1. The product is added to the cart with the expected quantity.

### Actual result
1. The product is added, but the quantity is ignored.

After a debugging session, it appears that the problem comes from the Zend Framework:

- The class Zend_Filter_LocalizedToNormalized, that is supposed to sanitize the "qty" parameter turns it into a date instead (where the value of "qty" becomes the day of the month and the rest is blank). After this, the parameter is completely ignored.
- It appears that the locale inheritance algorithm has problems, the Chilean Spanish locale is unable to use the format for decimal numbers from the generic Spanish locale it is supposed to be extending.

So far, we have been able to deal with the issue by adding the following node to the XML file vendor/magento/zendframework1/library/Zend/Locale/Data/es_419.xml (delimited with comments) :

```

	<numbers>
		<symbols numberSystem="latn">
			<decimal>.</decimal>
			<group>,</group>
		</symbols>
		<decimalFormats numberSystem="latn">
			<!-- This part is new  -->
			<decimalFormatLength>
				<decimalFormat>
					<pattern>#,##0.###</pattern>
				</decimalFormat>
			</decimalFormatLength>
			<!--  End of the added part -->
			<decimalFormatLength type="short">
				<decimalFormat>
					<pattern type="1000" count="one" draft="contributed">0</pattern>

```

**Comment by veloraven** [comment] 2016-11-23 06:35
@AlexandreKhayrullin thank you  for your report.
I'm closing this issue as duplicate of #6656

**Closed as completed by veloraven** 2016-11-23 06:35 UTC

**Comment by janmech** [comment] 2016-12-21 10:52
I commented another possible workaround that avoids changing core files: https://github.com/magento/magento2/issues/6656
