### ISSUE TITLE
URL key for specified store already exists when Creating new Products, secondary store view

### ISSUE THREAD

**Issue by blizam** [magento/magento2#5527] opened 2016-07-07 16:55 UTC
2.1.0

When creating a new product you cannot specify another Store View other than the Default or you will get a "URL key for specified store already exists." error when creating the product.

You cannot change any options on "Products in Website" options while creating the product (well, you can choose NO option, you can untick the default store view, but you cannot select another store view), even if the store checked/defaulted is incorrect. You have to create the Product first, THEN change your Configuration Scope in the upper left (unavailable during initial create) THEN you can select your other store view and Save.

The Products in Website options seem to be in general conflict with the overarching Configuration Scope when creating and editing products since 2.1.0

**Comment by antboiko** [comment] 2016-07-08 08:19
Hello @blizam . Could you please provide detailed steps to reproduce the issue? As for now, I cannot reproduce it using your description. 
Scope selector is not present during product creation and it's a correct behavior. Regarding "Product in Website" section, I could easily select another website by ticking an appropriate checkbox near its label.

Thanks,
Anton.

**Comment by blizam** [comment] 2016-07-08 18:43
I'm unable to reproduce this currently... it was happening consistently yesterday when I was trying to create a bunch of products... but I can't get it to do it today

**Comment by blizam** [comment] 2016-07-08 18:46
never mind, I got it... it's because I wasn't setting any categories

**Comment by blizam** [comment] 2016-07-08 18:49
Add Product 

Fill out: Name, SKU, Price, Quantity

Set Parent > Sub categories from Second Website

Enter description

Add image

Products in Websites > untick default Website, tick my 2nd Website

Save

Error: URL key for specified store already exists.

**Comment by antboiko** [comment] 2016-07-11 10:41
Hi @blizam , thanks for the steps. However, I still cannot reproduce the issue, all works well. 

> Fill out: Name, SKU, Price, Quantity

Check the name which you're filing there whether it already exists or not. By default, URL key is generated using a product name.

> Set Parent > Sub categories from Second Website

Please provide more preconditions to reproduce this step. 

Thanks,
Anton.

**Comment by blizam** [comment] 2016-07-11 16:00
I've tried it manually setting a unique key... and yeah, my Product Names are all unique as well

For my 2nd Website I have:

Root Category
+Shop
++Category 1
+++Sub-Cat A
+++Sub-Cat B
++Category 2
+++Sub-Cat A
+++Sub-Cat B

The Categories I added when creating my Products were:

Shop, Category 2, Sub-Cat B (the one underneath Category 2)

**Comment by andimov** [comment] 2016-08-04 08:16
@blizam
Thank you for reporting!
Was this problem solved?

**Comment by rosserl** [comment] 2016-08-04 09:46
We have the same or a similar problem with 2.1.0: When switching store view (from "All" to one we use for a different language), we cannot save the product the first time, we get the url key error, second save works most of the time, but even that sometimes fails. We have different product names, so that should not be the problem.

in the 2.0.8 release notes it says "Magento no longer duplicates URL keys during the creation of a configurable product." - maybe that has something to do with this issue, and it is not yet in 2.1 code?

**Comment by blizam** [comment] 2016-08-04 16:47
@amdimov no, I just tested with my exact same steps in #issuecomment-231779664 and the issue persists in Mage 2.1.0

**Comment by blizam** [comment] 2016-08-14 20:05
I'm guessing it's related to this: https://github.com/magento/magento2/issues/4430

I can't add valid categories to many of my products because of this... which also means that I can't sort/order many of my products in their various sub categories and parent categories because of this

**Comment by blizam** [comment] 2016-08-14 21:14
hrm... my basic "issue" is trying to add any category to an existing product (issues with create documented in another ticket) while in the Default Stores View configuration scope... even though Categories are marked as Global I HAVE to switch to a specific Store View to add new categories... note this is only true on products in my secondary Websites... it does not occur on the Default Website products

**Comment by AVoskoboinikov** [comment] 2016-08-30 13:33
Hi @blizam, can you provide full steps to reproduce issue? Something like:
1. install magento;
2. create view A;
3. create view B;
4. etc.
Because it is still not obvious how to reproduce it in new magento installation with sample data. I've tried several ideas but without success. It looks like it is problem somewhere in url rewrite engine or in misunderstanding of some functionality. So it would be great if you can clarify steps.

Thanks!

**Comment by blizam** [comment] 2016-08-30 13:52
I detailed them above... I think it's a fundamental issue with there being no configuration scope when creating a new product when the categories in website 1 and website 2 have the same URL keys... in my setup, sub-categories also have the same name as other sub-categories within the same Website

Install magento, create Website 1 with a single Default Store View, create Website 2 with a single Default Store View

Add categories and subcategories of the same names to both Websites

Add Product a new product

Fill out: Name, SKU, Price, Quantity

Set Parent > Sub categories from **Second** Website

Enter description

Add image

Products in Websites > untick default Website, tick my 2nd Website

Save

Error: URL key for specified store already exists.

**Comment by AVoskoboinikov** [comment] 2016-09-06 07:43
@blizam 
Well I am still can't reproduce issue with your description. Here are my steps (pay attention that no other steps were executed except described below): 
1. Install Magento CE 2.1.0;
2. Install sample data;
3. Create next category tree:
   --- Root Category [already exists]
   ------ Shop
   --------- Category 1
   ------------ Sub-Cat A
   ------------ Sub-Cat B
   --------- Category 2
   ------------ Sub-Cat A
   ------------ Sub-Cat B
4. Create Website 1 with one Default Store View;
5. Create Website 2 with one Default Store View;
6. Set Shop category as root category for Website 1;
7. Set Shop category as root category for Website 2;
8. Create new simple product with next data:
   Name: Name;
   SKU: Sku;
   Price: 123;
   Categories: Shop, Category 2, Sub-Cat B (the one underneath Category 2)
   Description: Desc;
   Image: [image.jpg];
   Product in websites: Only Website 2 is checked 
9. Save product
10. Product successfully saved.

So, this steps are result of your description and I can't reproduce issue by them. Maybe I've missed something? Can you say what should I do to get error?

Thanks!

**Comment by blizam** [comment] 2016-09-06 17:51
Website 1 should be the default Website

For Website 2... create the Same Category tree under a separate Root and give the categories, and Sub Categories the same names as Website 1's categories and Subcategories

When creating a product be sure and pick a Category and Sub-Category from Website 2

All other steps seem identical to what I was doing

**Comment by AVoskoboinikov** [comment] 2016-09-07 10:34
Hi @blizam 

Thanks for update, but I still have no success in reproduce. Here is my updated steps:
1. Install Magento CE 2.1.0;
2. Install sample data;
3. Create next category tree:
   --- Root Category [already exists]
   ------ Shop 1
   --------- Category 1
   ------------ Sub-Cat A
   ------------ Sub-Cat B
   --------- Category 2
   ------------ Sub-Cat A
   ------------ Sub-Cat B
   ------ Shop 2
   --------- Category 1
   ------------ Sub-Cat A
   ------------ Sub-Cat B
   --------- Category 2
   ------------ Sub-Cat A
   ------------ Sub-Cat B
4. Create Website 1 with one Default Store View;
5. Create Website 2 with one Default Store View;
6. Set Website 1 as default web site; 
7. Set Shop 1 category as root category for Website 1;
8. Set Shop 2 category as root category for Website 2;
9. Create new simple product with next data:
   Name: Name;
   SKU: Sku;
   Price: 123;
   Categories: Shop 2, Category 2 (the one underneath Shop 2), Sub-Cat B (the one underneath Shop 2 - Category 2)
   Description: Desc;
   Image: [image.jpg];
   Product in websites: Only Website 2 is checked
10. Save product
11. Product successfully saved.

Have you any thoughts about this?

**Comment by blizam** [comment] 2016-09-08 05:13
That sounds right to me.... I just got 2.1.1 installed and I'll test it again and see if it still errors... I had a number of different scenarios where I would get the ""URL key for specified store already exists." error when I was building out this site... so perhaps I had some other complication or something carried on/up from a previous version of magento... I started with like 2.0.6 I believe.

The only other thing I can think of is try changing your Store Scope on the new Product screen if that's an option in 2.1.0... I actually don't see the scope selector dropdown in the upper left in 2.1.1 anymore... and I guess I have to question if it was there in 2.1.0... I seem to remember creating new products and I always felt it odd that my configuration scope would be default but I'm checking only website in the "Product in websites" area...

anyways, I will try and create a new product in 2.1.1 and see if I can produce the error

**Comment by AVoskoboinikov** [comment] 2016-09-09 07:48
Ok, thanks for help! I will wait for your results.

**Comment by blizam** [comment] 2016-09-13 20:36
I can't reproduce in 2.1.1

**Comment by AVoskoboinikov** [comment] 2016-09-14 07:13
OK, thanks! I will close this issue then. Fill free to open new one if you will have any new questions.

Have a good day!

**Closed as completed by AVoskoboinikov** 2016-09-14 07:13 UTC
Labels: bug report, Component: Catalog

**Comment by commalex** [comment] 2016-10-21 15:23
URL key for specified store already exists. - I'm getting this error when trying to upload products via CSV.  Have truncated all the SQL tables relating to products, but still some underlying issues.  The products are enabled, with a stock level, but products not coming up on my front end.  Using A configurable products and 6 children from 2 variation types, size and material.

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0-133-product' for key 'GOOGLEOPTIMIZER_CODE_STORE_ID_ENTITY_ID_ENTITY_TYPE', query was: INSERT INTO `mgdu_googleoptimizer_code` (`entity_id`, `entity_type`, `store_id`, `experiment_script`) VALUES (?, ?, ?, ?)
