### ISSUE TITLE
Magento admin gets in redirect loop when I login with a role that has no resources assigned

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#10611] opened 2017-08-22 08:11 UTC
The Magento admin gets in redirect loop when I login with a role that has no resources assigned.

### Preconditions

1. Magento 2.1.7
2. Chrome

### Steps to reproduce

1. Create a user role with no resources assigned to it.
2. Create an admin user with that role.
3. Log in with that user.

### Expected result

I would expect a redirect back to the login page with a message or a page that shows an error message or warning.

### Actual result

I get an `ERR_TOO_MANY_REDIRECTS` error in Chrome, insinuating that the page is in a redirect loop. The URL is: `http://somedomain.dev/admin_1gqkv1/admin/noroute/denied/key/b6d4.../`.

**Comment by lbajsarowicz** [comment] 2017-09-17 10:51
I've been debugging this issue and found out that if we add *adminhtml/noroute/denied* to public actions, this displays error page correctly:
![zrzut ekranu z 2017-09-17 12-48-22](https://user-images.githubusercontent.com/1639941/30520112-c7e5c00c-9ba6-11e7-80c3-a77aa8ce5ffe.png)

Need to go deeper if it won't cause any side effects. If not - I believe that will be enough solution for the issue.

**Comment by magento-engcom-team** [comment] 2017-09-19 13:34
@kanduvisla thank you for your bug report.
We've created internal ticket MAGETWO-75337 to track progress on the issue

**Comment by magento-team** [comment] 2017-10-01 09:00
Internal ticket to track issue progress: MAGETWO-75326

**Comment by okorshenko** [comment] 2017-10-03 21:10
we need to backport the solution to 2.2-develop

**Comment by convenient** [comment] 2017-10-04 15:24
@okorshenko Should this one be a straight port of #10921 or the full fix as described by https://github.com/magento/magento2/pull/10921#discussion_r141584859 ? 

If its the port i'll pick it up.

**Comment by okorshenko** [comment] 2017-10-04 16:42
Hi @convenient 
We can accept a backport, but it would be great if you can provide full solution

**Comment by okorshenko** [comment] 2017-10-04 22:43
@kanduvisla thank you for your report. The issue is already fixed in 2.2-develop branch (PR: #11229  by @convenient ) and will be available in the Magento 2.2.2 release

**Closed as completed by okorshenko** 2017-10-04 22:43 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Fixed in 2.2.x, Issue: Format is valid

**Comment by vivek291186** [comment] 2017-11-21 20:47
Nginx server still I am getting the same issue for redirect loop 


PHP 7.1
Magento 2.2.1
