### ISSUE TITLE
Sections missing from Stores > Configuration > General > Design

### ISSUE THREAD

**Issue by dvanhise** [magento/magento2#5240] opened 2016-06-24 17:51 UTC
Hi.  I've run into this problem since using versions 2.1+.  I'm still new to Magento so I haven't ruled out user error 100%.
## Steps to reproduce
1. Install Magento from `develop` branch.
2. In Admin panel, navigate to Stores > Configuration > General > Design
3. Try changing store view to Default Config, Website, or Store View
## Expected result
1. Sections such as Watermark, HTML Head, and Footer exist on the page
## Actual result
1. The only section visible is "Search Engine Robots"

Using Magento version 2.2.0-dev
Also occurred when using enterprise edition v 2.1.0

The user guide hasn't been updated to 2.1.0 yet but I looked at the change log and didn't see any changes to indicate these sections were moved.

**Comment by paales** [comment] 2016-06-24 18:47
@Bobrm2k3 This is by design, can not be found under content:

<img width="259" alt="schermafbeelding 2016-06-24 om 20 47 42" src="https://cloud.githubusercontent.com/assets/1244416/16347425/ec08548e-3a4c-11e6-81e0-dacde2fe4fea.png">

**Comment by dvanhise** [comment] 2016-06-24 19:03
Yup, that's it.  It moved and I never thought to check outside of store > config.  Thanks.

**Comment by paales** [comment] 2016-06-24 19:19
@Bobrm2k3 Could you please close the issue since it has been resolved 😄

**Closed as completed** 2016-06-24 19:46 UTC
Labels: Issue: Format is not valid

**Comment by gergely-42droids** [comment] 2017-09-25 09:38
Could this doc be updated, please? It is very misleading... http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/themes/theme-apply.html
