### ISSUE TITLE
fixer.io currency conversion not working

### ISSUE THREAD

**Issue by pawan** [magento/magento2#36748] opened 2023-01-16 14:49 UTC
### Preconditions and environment

-  Magento version = 2.4.1 or newer version
-  Allowed currency should be 2 or more in configuration

### Steps to reproduce

1.  Get Apikey for Fixer.io
2.  Update API key at Stores >> Configuration >> Currency Setup >> Fixer.io
3.  go to Stores >> Currency Rates >> click Import with Fixer.io as a service selected in drop down

### Expected result

New rates should be fetched

### Actual result

No API Key was specified or an invalid API Key was specified.

![image](https://user-images.githubusercontent.com/22196227/212705667-a35d5a76-4fa6-4a9d-814a-d6d9bed23c4c.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by pawan** [comment] 2023-01-16 14:56
@magento I am working on this

**Comment by engcom-November** [comment] 2023-01-17 05:32
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2023-01-19 13:25
Verified the issue on Magento 2.4-develop instance and the issue is reproducible with valid API key as well.
Hence confirming the issue.
![image](https://user-images.githubusercontent.com/60198231/213454195-3517079a-d042-4fe3-ae71-9d914218939d.png)

**Comment by hostep** [comment] 2023-01-29 12:25
This is probably a duplicate of https://github.com/magento/magento2/issues/36010

See [from this comment onward](https://github.com/magento/magento2/issues/36010#issuecomment-1369042075) for how it got fixed and a patch that might solve the problem (which was untested on Magento 2.4.1, but it might work)

**Comment by amarroni** [comment] 2023-03-01 12:29
@hostep thanks you so much for your new adapter. I already needed to create my own as well, searching I found your solution that work like a charm. My commit is related to handle the errores. Based on ApiLayer, the errores codes no longer be used and I commit a minor change in order to handle errores.

**Comment by engcom-Bravo** [comment] 2024-12-24 05:02
Hi,

As per this comment https://github.com/magento/magento2/issues/36010#issuecomment-1369042075 we are closing this issue as issue has been fixed.

Thanks.

**Closed as completed by engcom-Bravo** 2024-12-24 05:02 UTC
Labels: Component: Config, Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done, Reported on 2.4.1, Area: Admin UI
