### ISSUE TITLE
Incorrect VAT and prices - Frontend and backend different

### ISSUE THREAD

**Issue by TectonicKestrel** [magento/magento2#31847] opened 2021-01-26 18:44 UTC
### Preconditions (*)
1. Magento 2.4.1
2. PHP 7.4.14
3. 5.7.32-35-log Percona Server
4. Using Unit price to calculate UK VAT of 20%

### Steps to reproduce (*)
1. Add two products to the basket with a non-round ex VAT price, such as £6.6667 (to 4dp)
2. Add the same two products when creating an order from the admin area

### Expected result (*)
1. Both frontend and backend to display the correct prices.

### Actual result (*)
1. On the frontend, the ex VAT price is rounded to £13.34 and the inc VAT price is £16.00. While the the ex VAT amount is technically wrong, it should be 13.34 i can live with that, the inc VAT at £16.00 is correct.
![frontend](https://user-images.githubusercontent.com/10212208/105889256-e3547c80-6005-11eb-9b03-d7d7f92898e9.JPG)
2. In the admin panel the ex VAT price is the same, but the inc VAT price is £16.01.
![admin-order](https://user-images.githubusercontent.com/10212208/105889445-139c1b00-6006-11eb-95b3-98a3310a0c7f.JPG)

Calculation should be:
£6.6667 * 1.2 = £8.00004
£7.5000 * 1.2 = £9.00000

£6.6667 * 2 = £13.3334 * 2 = £16.00008

If i process an order manually from the admin area the customers are charged an incorrect amount.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [*] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by jorgb90** [comment] 2021-01-27 09:01
In the admin panel the subtotal is calculated as 13.34 when you take that 13.34 * 1.2 = 16.008 which is 16.01 rounded. The calculation shouldn't be different on front or back-end of course, but I can see where its coming from.

**Comment by alexsmith2709** [comment] 2021-01-27 09:21
Ok, i get that, I thought the prices were now worked out using 4 decimal places to solve this issue, but am i wrong?
Is there anyway i can have the prices i want including VAT? How does anyone sell anything for £8.00 inc UK VAT when having catalog prices ex VAT? I use a price and stock import plugin so prices are all exc VAT.
I forgot to include this screenshot in my original post, but this is the top of the admin order screen. Adding 1 product shows it is £8.00, adding 2 makes it £8.01, £6.67 * 1.2 = £8.004 so when rounded would be £8.00 or is this trying to calculate by row instead of unit and that is where the difference between frontend and backend is happening?
![admin-order2](https://user-images.githubusercontent.com/10212208/105969891-a6799b80-6080-11eb-8fde-bc58a8e68473.JPG)

**Comment by alexsmith2709** [comment] 2021-01-27 18:00
From doing further research and talking with a payment processor, it seems magento does use row total to work out tax in the admin panel, the settings for unit based calculations only apply to the frontend. Is this correct and is this likely to be addressed?

**Comment by dverkade** [comment] 2021-04-18 20:11
Posting a comment. Issues should not be automatically closed.

**Comment by engcom-Alfa** [comment] 2021-06-11 07:10
HI @alexsmith2709 
I tried to reproduce it in Magento 4.2-develop version, and haven't noticed price difference as such. Below are the screenshots.
Kindly give a try to reproduce it in latest version and let me know. If you find the same issue again, please give a complete reproducible steps including the products configurations and the tax configurations you have done, and any other information that helps us to reproduce.
Below is the working screenshots that I have tried.

![image](https://user-images.githubusercontent.com/51679138/121645608-04e46b00-cab2-11eb-906a-937f1bd5f85e.png)

![image](https://user-images.githubusercontent.com/51679138/121645676-17f73b00-cab2-11eb-8cd6-4e64372a7d91.png)

**Comment by alexsmith2709** [comment] 2021-06-11 08:02
@engcom-Alfa Your test is using different amounts and tax to my test so its not an accurate reproduction of the issue, you are also only using a quantity of 1 for the product.
I have just tested on 2.4.2 and I get the same results as my initial post. If you use the same product amount (or any ex VAT amount that does not round (like 3.33 or 6.67) and then use 20% VAT.
Using my example of an excluding VAT amount of £6.67, adding 2 of these products in the admin panel gives £16.01 inc VAT and in the frontend i get it rounded correctly to £16.00.

Please see my comment above (https://github.com/magento/magento2/issues/31847#issuecomment-768466753) where i state it looks like in the admin panel the price is always worked out using row total, whereas the frontend can be changed to use unit total. The magento settings for changing how tax is added only applies to the frontend which i believe is causing this issue.

**Comment by engcom-Alfa** [comment] 2021-06-14 09:04
@magento give me 2.4.2 instance

**Comment by engcom-Alfa** [comment] 2021-06-14 10:56
Hi @alexsmith2709 

I have tried multiple times to reproduce, Below is all my details investigation details.

**Try 1: Using Magento 2.4-develop version**
1. Set the tax percentage to 20% based on pin code range.
2. Set the Currency type to Euro.
3. Created a new product with the amount 6.667 (Once adding the new product, the price rounds up to 6.67 only)
4. Checked out a product in the front end with 2 quantities and the result will be as shown in below screenshot.
![image](https://user-images.githubusercontent.com/51679138/121880117-416ecb80-cd2b-11eb-980a-43ed1336515a.png)
(The total amount is 16.01 and in which 2.67 is tax amount and it is an absolutely perfect calculation. The product total amount is 13.34 and so 205 of it will be 2.668 and hence rounded automatically to 2.67)
5. After placing an order, checked in the admin side invoice and found the same details and the screen shot is below.
![image](https://user-images.githubusercontent.com/51679138/121880545-c22dc780-cd2b-11eb-820b-c7a15a52270f.png)

6. Later I tried changing the currency type to British Pounds as well. Where I tried with a new order placement, and found no issues again as shown in below screen shots.
![image](https://user-images.githubusercontent.com/51679138/121880722-f903dd80-cd2b-11eb-9992-ae2a8970aa8b.png)
![image](https://user-images.githubusercontent.com/51679138/121880793-0de07100-cd2c-11eb-88c0-11f387328206.png)

7. Since it worked well in my system and again I tried to reproduce in the Magento 2.4.2 version by requesting the Magento cloud instance (the login details are in the above comment). (Created buyer profile with credentials: test@test.com/Test1234)
You may access and check the above instance.
Using this 2.4.2 version also, I could not reproduce, and the relevant screenshots are below.
![image](https://user-images.githubusercontent.com/51679138/121881492-fbb30280-cd2c-11eb-8009-60ab8c3928aa.png)
![image](https://user-images.githubusercontent.com/51679138/121881571-14bbb380-cd2d-11eb-8676-5e8aa160b43b.png)

Kindly try to reproduce in the latest version as I mentioned. Also If you are able to reproduce, please share a screen recoded video starting from the tax configuration-product creation-order placement and invoice generation. It helps to reproduce exactly.

**Comment by alexsmith2709** [comment] 2021-06-15 09:18
@engcom-Alfa where you using the unit price to calculate tax?
As stated above i believe this is where the issue lies. Changing to calculate the tax on unit price, only affects the front end, not the backend. I use unit price as i want the price to be rounded at unit level so the total would be £16 in this example, not £16.01 which happens when using row total.

**Comment by engcom-Alfa** [comment] 2021-06-17 06:45
Hi @alexsmith2709 
Answering to your question:
_where you using the unit price to calculate tax?_ >> In the step number 4 in my [last comment](https://github.com/magento/magento2/issues/31847#issuecomment-860593209)

_As stated above i believe this is where the issue lies. Changing to calculate the tax on unit price, only affects the front end, not the backend_ >> It is affecting both the front and back end as per my screenshots in the step no 4 & 6 of my [above comment](https://github.com/magento/magento2/issues/31847#issuecomment-860593209)

_I use unit price as i want the price to be rounded at unit level so the total would be £16_ >> Well, the Magento helps to round the values from 3rd decimal point. (If the product price input value is 6.667 > then the rounded value will be 6.67; and it will not round to the value 7. If the product price input value is 6.67 > then the rounded value will remain 6.67)

**No worries, if you are still having an issue, please read my [above comment](https://github.com/magento/magento2/issues/31847#issuecomment-860593209), kindly tell me what is the procedure I have to change in my steps, what is the expected thing in each and every step, and in which you are noticing the issue?

Kindly replay me back with the step numbers I have written above, that will help me understanding exactly without any faults.**

**Comment by alexsmith2709** [comment] 2021-06-17 08:26
@engcom-Alfa you dont mention anything about using unit price to calculate the tax, the calculations used look to be based on row total. In Stores > Configuration > Sales > Tax, "Tax Calculation Method Based On" should be set to "Unit Price".
For example using unit price it should be:
£6.67 * 1.2 (for UK VAT) = £8.004, magento rounds this to £8.00 * 2 for number of products  = £16.00. This is how it is currently working on my front end, but not in the backend.
The backend is using row total which uses the calculations you mentioned of:
£6.67 * 2 = £13.34 *1.2 = £16.008, which is rounded to £16.01.

**Comment by engcom-Alfa** [comment] 2021-06-18 09:43
@alexsmith2709 
Thanks for the information about Stores > Configuration > Sales > Tax, "Tax Calculation Method Based On" settings.

Well, I tried to reproduce applying the "tax price per unit" settings in the Magento latest version 4.2-develop. Yes, as you tried, the tax percentage is rounding up per unit. But as I checked, tax price is rounding up per unit in the backend too along with front end. Below are the screenshots.

![image](https://user-images.githubusercontent.com/51679138/122541477-4becd600-d047-11eb-9083-d435e5c4db68.png)

![image](https://user-images.githubusercontent.com/51679138/122541549-5e670f80-d047-11eb-9fbf-b64d7bda5adb.png)

**So, kindly upgrade yourself to the latest version and try to reproduce the same issue. If you are still able to do so, kindly report me back.**

Thanks

**Comment by alexsmith2709** [comment] 2021-06-18 10:48
I am using 2.4.2 and here are my screenshots showing the different amounts
![frontend](https://user-images.githubusercontent.com/10212208/122549959-fa365280-d02a-11eb-9fc7-274aa4016b95.PNG)
![backend](https://user-images.githubusercontent.com/10212208/122549960-facee900-d02a-11eb-921b-c0309e400f12.PNG)
If this has been fixed in the development version and will be released in 2.4.3 or whichever version is next released then that is good to know

**Comment by engcom-Alfa** [comment] 2021-06-21 07:35
@magento give me 2.4.2 instance

**Comment by engcom-Alfa** [comment] 2021-06-21 09:40
Hi @alexsmith2709 

Tried to reproduce in **Magento 2.4.2** version as you mentioned above, and unable to successfully reproduce it.
To test in 2.4.2, I have requested the instance again and you can see the details in the [above comment](https://github.com/magento/magento2/issues/31847#issuecomment-864803941).

I had mentioned in my [Previous Comments](https://github.com/magento/magento2/issues/31847#issuecomment-860593209), and I had asked you if you are following the same steps or have to change any!
Well, anyhow I am rewriting all the steps I followed below. Please check if anything is deviating from what you are following.

1. Stores > Configuration > Sales > Tax > tax Calculation, "Tax Calculation Method Based On" - Unit Price

2. Set the Currency type to Euro.

3. Set the tax percentage to 20% based on pin code range.

4. Created a new product with the amount 6.667 (Once adding the new product, the price rounds up to 6.67 only, and that is acceptable.)

5. Checked out a product in the front end with 2 quantities and the result is as shown in below screenshot.
![image](https://user-images.githubusercontent.com/51679138/122736276-7d5edf00-d29d-11eb-88a5-5b18f7463db6.png)

6. Placed the order successfully in the front end.

7. Navigated to the admin side Sales > Order > invoice; Found the same calculated values as front end details. This backend screen shot is below.
![image](https://user-images.githubusercontent.com/51679138/122736428-a54e4280-d29d-11eb-9130-ca157ae21f95.png)

8. Since, I could not reproduce in the Magento version 2.4.2 based on above steps, In the above step4, I had added one product with 2 quantities. This time, I changed concept by adding 2 different products each with 1 quantity (having same price). Still could not reproduce. Below are the screenshots of that.
![image](https://user-images.githubusercontent.com/51679138/122741317-771f3180-d2a2-11eb-82e4-0901ce290e33.png)
![image](https://user-images.githubusercontent.com/51679138/122741260-6a024280-d2a2-11eb-9fe0-ff1f387f008a.png)

You may please re-try using the same above instance and let me know if you are able reproduce! As off now, I am marking it as non-issue
- If there is any change you want to do in the execution considering above steps, kindly inform me the required change mentioning that step number.
- If you are expecting other output for any of the steps, kindly mention that expected output with the step number only please.
- If you want to add/remove any step from the list, kindly tell me what is that you want to add/remove and in between which step number.

**Comment by alexsmith2709** [comment] 2021-06-21 10:30
@engcom-Alfa It seems that a vanilla installation now works fine. I do not know what is causing this in my installation. When adding 2 products in the admin panel the price include tax changes to £8.01 and the total for 2 is £16.01, the frontend is fine. On the instance created for this issue does not have this issue.
I have no rounding plugins installed, the only things i can think of that may be causing this issue are my payment provider plugin (Stripe) or my accounting software plugin (Xero). After talking with Stripe about this, they initially denied it was their plugin, but if it is not magento then it must be even though this happens whether i select a payment type in the admin or not.

Thanks for your help

**Comment by engcom-Alfa** [comment] 2021-06-22 06:11
Since it is not a issue with Magento as per above comments, I am closing the issue.
In case of any issues relevant to Magento, kindly test in latest Magento version and report a bug with all detailed information like Preconditions, details steps to reproduce, expected and actual results along with screen shots / screen recordings possibly.

For any clarifications, you may take a look into the [Magento User Guide](https://docs.magento.com/user-guide/).

**Closed as completed by engcom-Alfa** 2021-06-22 06:11 UTC
Labels: non-issue, Issue: needs update, Reported on 2.4.1
