### ISSUE TITLE
CMS Hierarchy renders breadcrumbs even when disabled

### ISSUE THREAD

**Issue by fredden** [magento/magento2#35513] opened 2022-05-21 15:36 UTC
### Preconditions and environment

- Adobe Commerce. Tested on version 2.4.3-p2.
- Set a hierarchy for CMS pages
- Turn off hierarchy (admin -> Stores -> Settings -> Configuration -> General -> Content Management -> CMS Page Hierarchy -> Enable Hierarchy Functionality)

### Steps to reproduce

1. Navigate to a CMS page on the front-end which exists within a hierarchy
1. Observe the breadcrumbs displayed

### Expected result

Default (ie, no hierarchy) breadcrumbs displayed

### Actual result

Breadcrumbs from CMS Page Hierarchy are shown. Clicking these may result in a 404.

### Additional information

I don't have access to the relevant repository any more so I'm unable to submit this as a pull request. The following is what I have used to fix this in the `magento/module-versions-cms` composer package via `cweagans/composer-patches`.

```patch
diff --git a/Block/Cms/Page.php b/Block/Cms/Page.php
index 751c658..08df823 100644
--- a/Block/Cms/Page.php
+++ b/Block/Cms/Page.php
@@ -76,6 +76,10 @@ class Page extends \Magento\Cms\Block\Page
      */
     protected function _addBreadcrumbs(\Magento\Cms\Model\Page $page)
     {
+        if (!$this->_scopeConfig->isSetFlag('cms/hierarchy/enabled', ScopeInterface::SCOPE_STORE)) {
+            return parent::_addBreadcrumbs($page);
+        }
+
         $breadcrumbs = [];
         if ($this->_scopeConfig->getValue('web/default/show_cms_breadcrumbs', ScopeInterface::SCOPE_STORE)
             && ($breadcrumbsBlock = $this->getLayout()->getBlock('breadcrumbs'))
```

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-05-25 12:28
Hi @fredden ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch with enterprise edition modules enabled and the issue is reproducible.
Breadcrumbs from CMS Page Hierarchy getting displayed even after disabling page Hierarchy Functionality
![image](https://user-images.githubusercontent.com/60198231/170261686-8a3c2ea6-143f-402e-99dc-2f9bcf43dbe8.png)
Clicking on the node gives 404 error
![image](https://user-images.githubusercontent.com/60198231/170261881-6243f041-0117-4b47-aa41-da532aff9d9c.png)

**Comment by glo17680** [comment] 2022-09-01 06:42
@fredden thanks for contributing, internal team has started working on this.

**Comment by engcom-Hotel** [comment] 2022-10-10 11:51
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-3167 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-3167&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks

**Closed as completed by engcom-Hotel** 2022-10-10 11:51 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Progress: done, Component: Frontend, Area: Content, Reported on 2.4.3-p2, Adobe Commerce
