### ISSUE TITLE
Magento Setting Up Cron “Error during saving of crontab: sh: line 6: crontab: command not found”

### ISSUE THREAD

**Issue by dalvan03** [magento/magento2#24544] opened 2019-09-10 21:25 UTC
### Preconditions (*)

1. Magento 2.3.0
2. Professional Cloud Server from Hostinger

### Steps to reproduce (*)

1. I installed Magento
2. I followed the steps of the official magento website. [This link.](https://devdocs.magento.com/guides/v2.3/install-gde/install/post-install-config.html#post-install-cron)

### Expected result (*)

1. Magento Cron Works

### Actual result (*)

1. Error during saving of crontab: sh: line 6: crontab: command not found”
![image](https://user-images.githubusercontent.com/53019481/64652456-48500800-d3fa-11e9-89ff-a83b41402c53.png)

**Comment by engcom-Charlie** [comment] 2019-09-11 06:05
Hello @dalvan03 
I can't reproduce this issue on Magento 2.3-develop.
**Manual testing scenario:**
1. Install magento
2. `php bin/magento cron:install`
3. `crontab -l`
**Result:**
Crontab exist:
![image](https://user-images.githubusercontent.com/51680850/64672036-0020fc00-d473-11e9-9a84-42154855e45b.png)

So i have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-09-11 06:05 UTC
Labels: Issue: Format is valid
