### ISSUE TITLE
Product list does not contain [extension_attributes][stock_item]

### ISSUE THREAD

**Issue by olsavmic** [magento/magento2#36533] opened 2022-11-25 15:51 UTC
### Preconditions and environment

- Magento version 2.3.1, probably all newer versions affected as well 2.4-development

### Steps to reproduce

Call `/rest/V1/products?searchCriteria` API, look for extension_attributes and compare the output with the API documentation

### Expected result

stock_item should be part of extension_attributes in product listing

### Actual result

stock_item is available only on the product detail

### Additional information

I'd like to reopen the discussion around already existing but closed issues:
https://github.com/magento/magento2/issues/24418
https://github.com/magento/magento2/issues/22737

The official API documentation for `/rest/V1/products` endpoint contains `stock_item` record in the `extension_attributes`. The `stock_item` is indeed part of the `/rest/V1/products/{productSku}` extension_attributes.

From the [comment and code](https://github.com/magento/magento2/issues/24418#issuecomment-541317280) on one of the issues, it seems like the `stock_item` field will be removed in the future and /stockItems/{productSku} endpoint should be used instead.

Since it took us hours to find out that the documentation is invalid, I'd propose one of following:

1. Fix the API docs to reflect that the `stock_item` is missing from `extension_attributes` (although not ideal, the intent would be clear)
2. Add `stock_items` (already tried in https://github.com/magento/magento2/pull/28435, closed for inactivity)

Correct me please if the issue was fixed as I see https://github.com/magento/magento2/issues/24418 in "status:done" (and I don't have a testing environment with the latest release) but I did not find any finished PR with the fix.

We'd highly prefer the option to get the stock_item information during product listing as we're integrating Magento with our ERP and right now we have to execute thousands of additional queries (I don't know of any bulk endpoint to retrieve the stock details for all products) but we can work with the workaround, fixing the docs would be enough if that's the agreed direction.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-11-28 13:27
Hi @olsavmic ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance and the issue is reproducible. No "stock_item" in the GET API response for /rest/V1/products
As per Magento [devdocs](https://developer.adobe.com/commerce/webapi/rest/quick-reference/), all fields of stock_item should be displayed under "extension_attributes" in the GET API response of rest/default/V1/products. Hence confirming this issue.

**Comment by Kannakiraj123** [comment] 2022-12-15 11:24
@magento I am working on this

**Comment by engcom-Bravo** [comment] 2024-12-12 03:55
Hi @olsavmic,

Thanks for your Contribution!!.

As per this comment https://github.com/magento/magento2/pull/36615#issuecomment-2503827940 we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-12-12 03:55 UTC
Labels: Issue: Confirmed, Component: Api, Reproduced on 2.4.x, Priority: P3, Priority: P1, Progress: done, Reported on 2.3.1, Area: APIs
