### ISSUE TITLE
CMS page in different store with same URL can't be saved

### ISSUE THREAD

**Issue by flipflap** [magento/magento2#6596] opened 2016-09-13 13:22 UTC
### Preconditions

1. Magento 2.0.9
### Steps to reproduce

1. I add a new cms page in (content > pages) for a different store language
2. The URL must be same as a page url of an other store
3. Save
### Expected result

1. Page should be saved
### Actual result

1. Get error: **URL key for specified store already exists.**
   ![image](https://cloud.githubusercontent.com/assets/6672673/18475177/c860c24c-79c5-11e6-963c-3ad8a8824561.png)

**Comment by antboiko** [comment] 2016-09-13 14:21
Hi @flipflap , can you please provide more detailed steps to reproduce the issue? 

> The URL must be same as a page url of an other store

Do you mean store view?

Thanks,
Anton.

**Comment by flipflap** [comment] 2016-09-13 14:23
Yes Anton, store view.

**Comment by antboiko** [comment] 2016-09-13 15:11
Thanks @flipflap . 

This is a correct behavior. The URL key for each page under the same Store has to be unique. Meaning, for  that translated page on another store view (e.g. EN) a unique URL key should be specified, which is different from those you have on DE and FR store views.

I hope this will help.

I'm closing this issue since it's not a bug. Please feel free to reopen if you have additional questions.

Best,
Anton.

**Closed as completed by antboiko** 2016-09-13 15:11 UTC
Labels: Component: Cms

**Comment by flipflap** [comment] 2016-09-13 15:15
Ok, thanks. But my language switcher from my old magento doesn't work anymore that way. Can you give me some hint how to build a language switcher that works for CMS pages in Magento 2? 

Regards

Oliver

**Comment by tkacheva** [comment] 2016-09-13 15:46
Language switcher for CMS content has never been native Magento functionality. We are having this in CMS roadmap
