### ISSUE TITLE
Impossible to run graphql functional tests

### ISSUE THREAD

**Issue by delyriand** [magento/magento2#32252] opened 2021-02-23 09:46 UTC
### Summary (*)

When we follow the [documentation to run GraphQL functional tests](https://devdocs.magento.com/guides/v2.4/graphql/functional-testing.html#run-functional-tests), we get an error: Could not use "Magento\TestFramework\ApiSuiteLoader" as loader

### Examples (*)

- Configure your instance, copy  the phpunit_graphql.xml.dist file to phpunit_graphql.xml and set environment values
- Run the single test `vendor/bin/phpunit -c dev/tests/api-functional/phpunit_graphql.xml dev/tests/api-functional/testsuite/Magento/GraphQl/Customer/GenerateCustomerTokenTest.php
`

We get the error:
![image](https://user-images.githubusercontent.com/465524/108825997-0ef66280-75c4-11eb-9593-7df2d171eee2.png)

### Proposed solution

For me, it fails with the error because the bootstrap instantiates a WebApiApplication, by inheritance, it executes the following code and we are in the wrong folder:

```php
if (getcwd() != BP . '/dev/tests/integration') {
      chdir(BP . '/dev/tests/integration');
}
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by oneserv-heuser** [comment] 2021-02-23 16:12
Can confirm in magento 2.4.2

**Comment by magento-engcom-team** [comment] 2021-03-23 22:41
:white_check_mark: Confirmed by @bgorski 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41522` were created

**Issue Available**: @bgorski, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by bgorski** [comment] 2021-08-14 19:15
@magento I'm working on this

**Comment by bgorski** [comment] 2021-08-15 12:45
I'm unassigning myself from this after all as it requires a bit more effort to fix it the right way than I can currently commit to. 

The part of the functionality that's failing here - the custom test suite loader PHPUnit functionality is actually deprecated (https://github.com/sebastianbergmann/phpunit/issues/4039) and marked with a `@internal This class is not covered by the backward compatibility promise for PHPUnit` comment so it can stop working any moment. 

From what I see in Magento it's used to provide wrappers for tests to make it possible to skip them, so a right approach here would be to provide the same functionality in a different way. I don't think a simple workaround fixing the directory issue is enough. 

Maybe @mykhailomatiola would have some ideas on how to deal with this as from what I see in the commits history he's the author of this feature that later on got deprecated on the PHPUnit side. Mykhailo, any hints? :) 

And if someone does require a simple workaround - the initial comment in the task is correct, that piece of code changing the directory makes API Functional tests fail to find the test suite loader file. 

Workaround 1:
Modify the `dev/tests/integration/framework/Magento/TestFramework/Application.php` file and change
```
if (getcwd() != BP . '/dev/tests/integration') {
    // phpcs:ignore Magento2.Functions.DiscouragedFunction
    chdir(BP . '/dev/tests/integration');
}
```
to 
```
if (getcwd() != $this->getExecutionDir()) {
    // phpcs:ignore Magento2.Functions.DiscouragedFunction
    chdir($this->getExecutionDir());
}
```
and introduce the getExecutionDir() method:
```
    protected function getExecutionDir(): string
    {
        return BP . '/dev/tests/integration';
    }
```
Then modify the `dev/tests/api-functional/framework/Magento/TestFramework/WebApiApplication.php` file by adding the same method with a different dir:
```
    protected function getExecutionDir(): string
    {
        return BP;
    }
```

Workaround 2:
Include full path to the testSuiteLoaderFile in your phpunit_graphql.xml config file, instead of:
```
testSuiteLoaderFile="framework/Magento/TestFramework/ApiSuiteLoader.php"
```
use something like:
```
testSuiteLoaderFile="/shared/httpd/github-magento2-ce/htdocs/dev/tests/api-functional/framework/Magento/TestFramework/ApiSuiteLoader.php"
```
Of course replace with the actual path on your system, the one above is just an example.

**Comment by hostep** [comment] 2021-10-21 11:40
@ihor-sviziev: could you remove the label "progress: PR in progress" again? I think the automation accidentaly added it just because I referenced this issue from [a PR](https://github.com/magento/magento2/pull/34361) that doesn't solve this.

**Comment by andrewbess** [comment] 2021-11-03 18:51
Hello there.
Try to run tests from directory `dev/tests/integration`.
It works for me.

cc @delyriand @bgorski

**Comment by sprankhub** [comment] 2022-01-28 10:42
The workaround suggested by @andrewbess also works for me. Another option is to run the tests with an absolute path to the configuration file:

    vendor/bin/phpunit -c $(pwd)/dev/tests/api-functional/phpunit_graphql.xml dev/tests/api-functional/testsuite/Magento/GraphQl/Customer/GenerateCustomerTokenTest.php

**Comment by cpartica** [comment] 2022-02-08 00:57
I think this option works fine and we can document it in devdocs. Since I am using PHPStorm I did not even have this problem as it uses full URLs all the time

**Comment by cpartica** [comment] 2022-02-08 15:17
Thank you @sprankhub, @andrewbess, @bgorski @delyriand for exposing your workarounds

If you experienced things that have a workaround that we need to document, please open a PR to the docs.
We can get far faster to those PRs than these ones
The Severity 4 of this ticket makes this ticket to linger like this for a while until we get to it. It also has no PR which will just prolongue its existence. Docs brings more value meanwhile.

**Comment by sprankhub** [comment] 2022-02-10 07:33
Thanks for caring @cpartica! I agree that having a documented workaround is better than having nothing. However, we probably agree that this should still be fixed in the core as it is awful developer experience.

Please mind that this also affects integration tests.

**Comment by engcom-November** [comment] 2022-11-19 07:39
Verified the issue on Magento 2.4-develop branch and the issue is still reproducible.
Configured the instance as per [devdocs](https://devdocs.magento.com/guides/v2.4/graphql/functional-testing.html#run-functional-tests) but unable to run the functional tests from CLI. Hence confirming the issue.
![image](https://user-images.githubusercontent.com/60198231/202840409-5304d3c4-182e-44ae-91fe-01e08bc0345e.png)

**Closed as completed** 2023-07-11 12:33 UTC
Labels: Issue: Confirmed, Component: GraphQL, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P2, Severity: S4, Progress: done, Reported on 2.4.x, Area: Framework
