### ISSUE TITLE
Magento Roles Help

### ISSUE THREAD

**Issue by Iocean1** [magento/magento2#38162] opened 2023-11-09 09:01 UTC
### Summary

I want to know what is best access for this Roles,
I only want each role to be on his Field :

Markting 
Developr
Finance
Sales 
Shipping 

### Examples

<img width="447" alt="Screenshot - 2023-11-09 12-00-14" src="https://github.com/magento/magento2/assets/149070113/e922b3f3-d1c8-46c0-a1c5-7e153df61e96">

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-11-09 11:39
Hi @Iocean1,

Thank you for reporting and collaboration.

Kindly check this document https://experienceleague.adobe.com/docs/commerce-admin/systems/user-accounts/permissions-user-roles.html?lang=en regarding Role Resources and please provide us on which scenario you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-11-20 06:13
Hi @Iocean1,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38162#issuecomment-1803671065 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by Iocean1** [comment] 2023-11-20 06:15
Dear,

  I don't have issue with how to set the roles
 I only want to know access for each role

Thank you
________________________________

**Comment by engcom-Bravo** [comment] 2023-11-21 10:41
Hi @Iocean1,

Thanks for your update.

Could you please refer this document https://experienceleague.adobe.com/docs/commerce-admin/systems/user-accounts/permissions-user-roles.html?lang=en regarding Roles.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-11-28 05:23
Hi @Iocean1,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-11-28 05:23 UTC
Labels: Issue: needs update, Reported on 2.4.x
