### ISSUE TITLE
Product review success message showing in all pages

### ISSUE THREAD

**Issue by ewallkrishnaprakash** [magento/magento2#7168] opened 2016-10-25 06:43 UTC
### Preconditions

1. We are  using magento2.1.1 on apache2.4 with php7 and mysql 5.7.
### Steps to reproduce

1. Open the product detail page and review the product. Review success message will showing the product detail page (http://prnt.sc/cylror).
2. The same message displayed in home page (http://prnt.sc/cylrsw)
### Expected result

1. The success message needs to shown only in product details.
### Actual result

1. Review success message will showing the product detail page (http://prnt.sc/cylror) and other pages (http://prnt.sc/cylrsw). In some times the detail page not displaying the review success message.

**Comment by palamar** [comment] 2016-10-26 14:31
Internal ticket MAGETWO-60147 for this issue has been created.

**Comment by andidhouse** [comment] 2016-12-01 09:17
Als related to this one here:
https://github.com/magento/magento2/issues/7427

**Comment by quienti** [comment] 2016-12-07 13:58
I think it's fixed in develop branch with this commit: https://github.com/magento/magento2/commit/9515999f75fc728084079b8aae7ccc784cd8c1f3

**Comment by andidhouse** [comment] 2016-12-15 12:03
This is just fixed half in 2.1.3
If a product is out of stock two problems remain when you try to ad it to the cart (for example you ad a product two times to cart but it is only one in stock).

The error message is stored somehow in magento and if you go to another site and put a product in the cart - et voila - still totally confusing messages.

![12](https://cloud.githubusercontent.com/assets/16196483/21223300/bd0c769e-c2c6-11e6-8a3f-ee95650e7b88.png)

**Comment by magento-engcom-team** [comment] 2017-10-05 18:31
@ewallkrishnaprakash, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-05 18:31 UTC
Labels: Issue: Ready for Work, bug report, Issue: Format is valid
