### ISSUE TITLE
Table rate value not getting correct and unable to set from custom shipping method on setCost method

### ISSUE THREAD

**Issue by hemendraajmera** [magento/magento2#36633] opened 2022-12-19 13:41 UTC
### Summary

Preconditions

Enabled table rate method and custom shipping method and saved
Magento Open Source 2.4.4-p1
custom module hide table rate shipping and set table rate based on condition define in custom module  (added code)
when i set from code constant it will showing the price 

Steps to reproduce
we can add product into cart and go to checkout it will show the custom shipping method and rate 

Expected result:

it will show price on shipping method section and cost on summary 
Actual result:

it showing price on shipping method but not on the summary 
![image](https://user-images.githubusercontent.com/2478037/208438464-b4217db3-1333-4aca-b5ef-6335e700554a.png)

Please check and help me to fix that issue

### Examples

class Carrier extends \Magento\Shipping\Model\Carrier\AbstractCarrier
    implements \Magento\Shipping\Model\Carrier\CarrierInterface
{
    /**
     * Carrier's code, as defined in parent class
     *
     * @var string
     */
    protected $_code = 'freight';

    /**
     * @var \Magento\Shipping\Model\Rate\ResultFactory
     */
    protected $shippingRateResultFactory;

    /**
     * @var \Magento\Catalog\Model\ProductFactory
     */
    protected $catalogProductFactory;

    /**
     * @var \Magento\Quote\Model\Quote\Address\RateResult\MethodFactory
     */
    protected $quoteQuoteAddressRateResultMethodFactory;

    /**
     * @param \Magento\Shipping\Model\Rate\ResultFactory
     * @param \Magento\Catalog\Model\ProductFactory
     * @param \Magento\Quote\Model\Quote\Address\RateResult\MethodFactory
     * @param \Magento\OfflineShipping\Model\ResourceModel\Carrier\Tablerate
     * 
     */

    public function __construct(
        \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig,
        \Magento\Quote\Model\Quote\Address\RateResult\ErrorFactory $rateErrorFactory,
        \Magento\Shipping\Model\Rate\ResultFactory $shippingRateResultFactory,
        \Magento\Catalog\Model\ProductFactory $catalogProductFactory,
        \Magento\Quote\Model\Quote\Address\RateResult\MethodFactory $quoteQuoteAddressRateResultMethodFactory,
        \Magento\OfflineShipping\Model\ResourceModel\Carrier\TablerateFactory $tableRate,
        LoggerInterface $logger,
        array $data = []
    ) {
        $this->shippingRateResultFactory = $shippingRateResultFactory;
        $this->catalogProductFactory = $catalogProductFactory;
        $this->quoteQuoteAddressRateResultMethodFactory = $quoteQuoteAddressRateResultMethodFactory;
        $this->tableRate = $tableRate;
        $this->logger = $logger;
      
        parent::__construct($scopeConfig, $rateErrorFactory, $logger, $data);
    }
    /**
     *
     * @param \Magento\Quote\Model\Quote\Address\RateRequest $request
     * @return \Magento\Shipping\Model\Rate\Result
     */
    public function collectRates(\Magento\Quote\Model\Quote\Address\RateRequest $request)
    {
        
       
        /** @var \Magento\Shipping\Model\Rate\Result $result */
        $result = $this->shippingRateResultFactory->create();
       
		
		$oldWeight = $request->getPackageWeight();

       $this->logger->info('oldWeight:'.$oldWeight);      
		
		$shipping_forwarding = false;
        
		$attribute_shipping_forwarding = $this->getConfigData('attribute_spedition');
        if ($request->getAllItems()) {
        	foreach ($request->getAllItems() as $item) {
        		if ($item->getProduct()->isVirtual() || $item->getParentItem()) {
        			continue;
        		}
        		$product_id = $item->getProductId();
        		$productObj = $this->catalogProductFactory->create()->load($product_id);
        		if($productObj->getData($attribute_shipping_forwarding)) {
					$shipping_forwarding = true;
                   // $this->logger->info('1:'.$shipping_forwarding);
        		}
        	}
        }

		$weight_spedition = doubleval($this->getConfigData('weight_spedition'));

        $this->logger->info('weight_spedition:'.$weight_spedition);      
		
		if ($shipping_forwarding && $oldWeight < $weight_spedition) {
			// Gewicht = $weight_spedition + 0.1
			// Preis anhand neuem Gewicht
			// Spedition als Versand setzen
			$request->setPackageWeight($weight_spedition + 0.1);
			$shipping_forwarding = true;
           // $this->logger->info('2:'.$shipping_forwarding);
		} else {
			// Preis anhand Table Rate und Gewicht Warenkorb (STANDARD)
			if ($oldWeight > $weight_spedition) {
				// Spedition als Versand setzen
				$request->setPackageWeight($oldWeight);
				$shipping_forwarding = true;	
              //  $this->logger->info('3:'.$shipping_forwarding);		
			} else {
				// Table rate standard
				$shipping_forwarding = false;
				$request->setPackageWeight($oldWeight);
			}
				
		}

       //$this->logger->info('shipping_forwarding:'.$shipping_forwarding);
        
        if ($shipping_forwarding) {
            $method=$this->_getStandardRate($request);
			$result->append($method);
		} else {
			return null;
		}

        return $result;
    }

   
    public function getAllowedMethods()
    {
        return [$this->_code => $this->getConfigData('name')];
    }

    /**
     * Get Standard rate object
     *
     * @return \Magento\Quote\Model\Quote\Address\RateResult\Method
     */
    protected function _getStandardRate($request)
    {	
		// $cost = Mage::getResourceModel('shipping/carrier_tablerate')->getRate($request);
        $cost1 = $this->tableRate->create()->getRate($request);

		/** @var \Magento\Quote\Model\Quote\Address\RateResult\Method $rate */
		$rate = $this->quoteQuoteAddressRateResultMethodFactory->create();
		$this->logger->info('cost'.print_r($cost1,true));

		$rate->setCarrier($this->_code);
		$rate->setCarrierTitle($this->getConfigData('title'));

		$rate->setMethod($this->_code);
		$rate->setMethodTitle($this->getConfigData('name'));

        //$price = (string) '0.00';

        if(is_array($cost1) && $cost1['price']>0){
            $price=(float) number_format($cost1['price'], 2, '.', '');
            $this->logger->info('price'.$price);
           // $price = '99.99';
            $rate->setPrice($price);
            $rate->setCost($price);
        }
        //$price = '999.99';
           
		if ( $request->getFreeShipping() == true) {
				$rate->setPrice(0);
				$rate->setCost(0);
		}
        return $rate;
    }

    public function isTrackingAvailable()
    {
        return true;
    }

}

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hemendraajmera** [comment] 2022-12-21 09:42
I tried to replicate same tablerate with another method name but it not working.

**Comment by janssensjelle** [comment] 2022-12-23 09:09
This issue seems to also occur with Sendcloud extension. It will not show the custom shipping method, just the tablerate. When choosing any other condition (ie. per items instead of based on price vs location) it will show both

**Comment by engcom-Hotel** [comment] 2023-01-04 13:42
Hello @hemendraajmera @janssensjelle,

Thanks for the report and collaboration!

We have tried to reproduce the issue in Magento 2.4-develop branch, but the issue is not reproducible for us. In order to reproduce the issue, we have followed the below steps:
1. Create a custom shipping method. Please find attached the module for reference:
[Magz.zip](https://github.com/magento/magento2/files/10344556/Magz.zip)

2. Tried to make an order using that shipping method:
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/51681618/210567496-6f8da6f3-12ce-4473-b31d-27408ce89096.png">

3. Enable the Table rate shipping method and upload the table rates by following this [documentation](https://experienceleague.adobe.com/docs/commerce-admin/stores-sales/delivery/basic-methods/shipping-table-rate.html#).
4. Tried to make an order and we can see the table rate in the summary.

Please let us know if we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2023-01-18 13:17
Dear @hemendraajmera @janssensjelle ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2023-01-18 13:17 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.4-p1
