### ISSUE TITLE
AttributeOptionLabelInterfaceFactory not being generated

### ISSUE THREAD

**Issue by mahmoud-abdelmalek** [magento/magento2#38350] opened 2024-01-12 05:34 UTC
### Preconditions and environment

- Magento version 2.4.4
- Upon running bin/magento setup:di:compile, I noticed that /generated/code/Magento/Eav/Api/Data/AttributeOptionLabelInterfaceFactory not being generated

### Steps to reproduce

Run bin/magento setup:di:compile
Navigate to /generated/code/Magento/Eav/Api/Data/ Directory
Observe

### Expected result

AttributeOptionLabelInterfaceFactory.php  Should be generated

### Actual result

AttributeOptionLabelInterfaceFactory.php is not generated

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mahmoud-abdelmalek** [comment] 2024-01-12 05:43
@magento give me 2.4-develop instance

**Comment by mahmoud-abdelmalek** [comment] 2024-01-12 05:57
I cannot access instance files to check generated classes

**Comment by engcom-Bravo** [comment] 2024-01-12 08:03
Hi @mahmoud-abdelmalek,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.

**Steps to reproduce**

Run bin/magento setup:di:compile
Navigate to /generated/code/Magento/Eav/Api/Data/ Directory
Observe


![Screenshot from 2024-01-12 11-12-36](https://github.com/magento/magento2/assets/51680745/f1e5c602-765c-44b1-b261-afb9bd36d7f8)




AttributeOptionLabelInterfaceFactory.php is not generated.

Hence Confirming the issue.

Thanks.

**Comment by andrewbess** [comment] 2024-01-12 13:06
Hello @mahmoud-abdelmalek 
Thank you for your collaboration

I've checked the Magento OpenSource codebase (2.4.4) with Sample Data.
So, it doesn't require the class.
Accordingly, the system will not be to generate it.
If we've created feature with dependency of this factory the system will generate it.
Please check screenshot.

<img width="1816" alt="magento-opensource – TestCommand php 2024-01-12 15-02-34" src="https://github.com/magento/magento2/assets/10788564/cafa8e5e-40e1-49e1-b56f-8f79e9fcc10f">

So, I think the problem is not relevant.
Thank you in advance.

**Comment by engcom-Bravo** [comment] 2024-01-15 05:50
@andrewbess Thanks for your contribution and collaboration.

Hi @mahmoud-abdelmalek,

We have verified the issue in Magento 2.4-develop instance and the issue is not reproducible.

As per this comment https://github.com/magento/magento2/issues/38350#issuecomment-1889150788 the issue is not relevant in Latest Magento 2.4-develop instance and it is working fine and  AttributeOptionLabelInterfaceFactory.php file got generated.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-01-15 05:50 UTC
Labels: Issue: Confirmed, Issue:  Cannot Reproduce, Component: Other, Reproduced on 2.4.x, Priority: P3, Progress: done, Area: Other Developer Tools, Reported on 2.4.4
