### ISSUE TITLE
Order status is not getting changed

### ISSUE THREAD

**Issue by arunkasyakar** [magento/magento2#2607] opened 2015-12-04 09:05 UTC
When i am submitting the invoice from the admin panel for an order the order status is changed to processing from pending, but when i am submitting the invoice by using the REST API order status is still pending. 
Here is my api call url:
       http://MYHOST/rest/default/V1/invoices

and payload is:
{
  "entity": {
    "baseCurrencyCode": "INR",
    "baseDiscountAmount": -512.4,
    "baseGrandTotal": 2054.6,
    "baseDiscountTaxCompensationAmount": 0,
    "baseShippingAmount": 5,
    "baseShippingDiscountTaxCompensationAmnt": 0,
    "baseShippingInclTax": 0,
    "baseShippingTaxAmount": 0,
    "baseSubtotal": 2562,
    "baseSubtotalInclTax": 2562,
    "baseTaxAmount": 0,
    "baseTotalRefunded": 0,
    "baseToGlobalRate": 1,
    "baseToOrderRate": 1,
    "billingAddressId": 24,
    "canVoidFlag": 0,
    "createdAt": "2015-12-04 12:07:29",
    "discountAmount": -512.4,
    "discountDescription": "string",
    "emailSent": 1,
    "globalCurrencyCode": "INR",
    "grandTotal": 2054.6,
    "discountTaxCompensationAmount": 0,
    "isUsedForRefund": 0,
    "orderCurrencyCode": "string",
    "orderId": 12,
    "shippingAmount": 5,
    "shippingDiscountTaxCompensationAmount": 0,
    "shippingInclTax": 0,
    "shippingTaxAmount": 0,
    "state": 2,
    "storeCurrencyCode": "INR",
    "storeId": 1,
    "storeToBaseRate": 0,
    "storeToOrderRate": 0,
    "subtotal": 2562,
    "subtotalInclTax": 2562,
    "taxAmount": 0,
    "totalQty": 1,
    "items": [
      {
        "additionalData": "string",
        "baseCost": 2562,
        "baseDiscountAmount": 512.4,
        "baseDiscountTaxCompensationAmount": 0,
        "basePrice": 512.4,
        "basePriceInclTax": 512.4,
        "baseRowTotal": 0,
        "baseRowTotalInclTax": 0,
        "baseTaxAmount": 0,
        "description": "string",
        "discountAmount": 512.4,
        "discountTaxCompensationAmount": 0,
        "name": "VNR AG LONG",
        "orderItemId": 20,
        "price": 2562,
        "priceInclTax": 2562,
        "productId": 2066,
        "qty": 1,
        "rowTotal": 2562,
        "rowTotalInclTax": 2562,
        "sku": "VNR-AG-LONG",
        "taxAmount": 0,
        "extensionAttributes": {}
      }
    ],
    "extensionAttributes": {}
  }
}

**Comment by apluzhnikov** [comment] 2016-04-14 11:46
Hi,

We are facing the same issue. 
Does someone know why the order is still pending and doesn't want to be processing? 
Also order shows against item only "Ordered 1", but didn't show "Invoiced 1"?????

Thank you in advance!

**Comment by ruby10** [comment] 2016-05-02 09:02
@NadiyaS  , is there any update on it? I am also facing this issue.

**Comment by srinivasanithin** [comment] 2016-05-02 09:16
@NadiyaS This seems to be same issue with all REST API POST call for shipments, invoice and Credit memo. Can there be a fix for all REST API Calls? This seems to be open more than 2 month now. 
Issue#3307 and #4329

**Comment by ruby10** [comment] 2016-05-02 15:25
Also , for invoices created using this api , "Grand Total" is coming as "0" . Attaching screenshot 
![invoice](https://cloud.githubusercontent.com/assets/12557241/14958378/31b76aca-10a8-11e6-84fb-ab16301c5d32.PNG)

**Comment by ruby10** [comment] 2016-05-05 16:48
@NadiyaS  Any update on this issue?

**Comment by NadiyaS** [comment] 2016-06-01 13:38
Hi,
We've created story to improve order functionality where described bug will also be fixed (internal ticket is MAGETWO-50299).
It will be delivered as soon as possible according to other items priority. 
Thank you for understanding and we are sorry for delay about this issue.
This issue will be closed as duplicate of #3307

**Closed as completed by NadiyaS** 2016-06-01 13:38 UTC
