### ISSUE TITLE
Admin page 404 error after flush cache from admin

### ISSUE THREAD

**Issue by Dysp1** [magento/magento2#7158] opened 2016-10-24 12:17 UTC
I have a fully working installation of Magento.  Customer pages and admin pages both work perfectly.  I can browse products and make orders as a customer.  I can login to admin pages, see the orders, add new products, see dashboard etc.  But as soon as I hit the "Flush Magento Cache" -button from admin I will jump to Magento 404 page and Admin is not accessible.

Preconditions
1. Magento CLI version 2.1.1 with sample data 
2. Ubuntu 16.04.1
3. PHP 7.0.11-1
4. Apache 2.4.18
5. MySQL 5.7.15 
6. VMWare 8.5

Steps to reproduce
1. Open magento admin page and login
2. Go to System / Cache management 
3. Click "Flush Magento Cache" -button

Expected result
1. Caches Flushed and return to admin pages 

Actual result
1.  404 error and admin not accessible

_After_ hitting the 404 problem in Admin I have:
1. Checked rewrite module is still running. 
2. sudo php ./magento cache:clean 
3. sudo php ./magento cache:flush
4. MAGENTO2_ROOT > var > cache > _DELETE ALL_
5. MAGENTO2_ROOT > var > page_cache > _DELETE ALL_
6. MAGENTO2_ROOT > var > session > _DELETE ALL_
7. MAGENTO2_ROOT > var > view_preprocessed > _DELETE ALL_
8. MAGENTO2_ROOT > pub > static > DELETE ALL EXCEPT .HTACCESS
9. cp MAGENTO2_ROOT/pub/.htaccess ../.
10. sudo php ./magento setup:static-content:deploy
11. sudo php ./magento indexer:reindex
12. Checked the core_config_data table, no changes before and after problem
13. Double Checked the admin uri from configs. (Have not changed it at any point)
14. Checked Magento2_root/var/log files but nothing printed there
15. Check the /var/log/apache2 access and error logs and nothing broken there
16. sudo service apache2 restart

None of the above works to restore the admin back on.  It always gives 404.  Only way to fix it seems to be to make a new fresh install.  Or now that I have it in VMWare I can go back to previous image and admin will work again just fine.  But as soon as I hit the "Flush Magento Cache" -button the admin will break to 404 and no way to fix it.

**Comment by slopukhov** [comment] 2016-11-28 13:49
@Dysp1 thank you for your feedback.
Please, recheck it on the latest 2.1 version of Magento

**Comment by Dysp1** [comment] 2016-11-29 10:51
Thanks, working with 2.0 for now as this was quite an show stopper.  I will find time later to test it again.

**Comment by Dysp1** [comment] 2016-12-02 14:09
Ok, Cache flushing seems to be working in the latest Magento-CE-2.1.2-2016-10-11-11-16-47.zip build.  Thanks.

**Comment by veloraven** [comment] 2017-07-03 13:11
I'm closing this issue as it seems to be resolved.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Closed as completed by veloraven** 2017-07-03 13:11 UTC
Labels: bug report, Progress: needs update, Component: Framework/Cache
