### ISSUE TITLE
Sitemap contains utility pages in multi store setup

### ISSUE THREAD

**Issue by enr-beck-mellow** [magento/magento2#35001] opened 2022-01-20 14:54 UTC
### Preconditions (*)

1. Magento 2.4.2-p2

### Steps to reproduce (*)

1. Create second store view
2. Duplicate "home" (or "enable-cookies" or "no-route") cms page 
3. Set "Page in websites" of original page to default store view and for the duplicate page to second store view
4. Change autogenerated url key of the duplicated page to the same url key like the original page (may be optional)
5. Assign original page as "CMS Home page" for default store view (Configuration > General > Web > Default pages)
6. Assign duplicate as "CMS Home page" for second store view
7. Create & generate Sitemaps for both store views

### Expected result (*)

1. Sitemaps of both store views doesn't contain the assigned default pages

### Actual result (*)

1. Sitemap of second store view contains the assigned default pages (because \Magento\Cms\Model\GetUtilityPageIdentifiers::execute() returns the page identifiers of second store view with appended | (pipe) and page id and these identifiers dont match the identifier of the duplicate page)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-02-23 13:05
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
Sitemap of second store view contains assigned page whereas sitemap of default store view does not contain assigned page.

Default store view sitemap:
![image](https://user-images.githubusercontent.com/60198231/155324605-f362ed07-d63e-4e48-96eb-6d54ffe193f5.png)

2nd store view sitemap:
![image](https://user-images.githubusercontent.com/60198231/155325090-0ddfe7f0-4794-4b2f-b03c-a4cf03c9f176.png)

**Comment by ihor-sviziev** [comment] 2023-07-17 09:27
This issue was already fixed in https://github.com/magento/magento2/commit/0ce75991942a56663a4fc77b3cc8eb6e1cdddce5 (changes from https://github.com/magento/magento2/pull/35156 )

**Closed as completed** 2023-07-17 09:28 UTC
Labels: Issue: Confirmed, Component: Sitemap, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P3, Progress: done, Reported on 2.4.2-p1, Area: Search, Area: SEO

**Comment by ted101media** [comment] 2025-01-08 08:40
We're currently having a scenario where this piece of code is breaking sitemap generation
vendor/magento/module-sitemap/Model/ResourceModel/Cms/Page.php line 119:
`static function ($urlKey) {
                    return explode('|', $urlKey, 2)[0];
                },`

An extra check would at least prevent code from failing.
