### ISSUE TITLE
Subtotal Cart Price Rule excludes product tax

### ISSUE THREAD

**Issue by bamboekeizer** [magento/magento2#28472] opened 2020-06-02 10:08 UTC
### Preconditions (*)
Magento ver. 2.3.5-p1 - upgraded from 2.3.3 using composer
1. Product price includes product tax. Product tax is 21%. Shipping table rate is 6 euro.
2. Create subtotal cart price rule to have free shipping start from 99 euro. Use 0 discount either as fixed value or percentage, tried both configurations
3. Shipping costs set to 6 euro from table rates

### Steps to reproduce (*)
1. As customer, add a product to the cart of 102 euro
2. Go to checkout
3. Look at the shipping costs displayed as part of the cart price
4. The shipping costs remain on 6 euro
5. The order total is product price + shipping costs = 102 + 6 euro

### Expected result (*)
1. At checkout, the subtotal cart rule should evaluate the product price including tax, being 102
2. The subtotal cart rule applies the free shipping and 0 discount
3. The order total is only product price and has 0 shipping costs: 102 euro

### Actual result (*)
1. At checkout, the subtotal cart rule should evaluate the product price including tax, being 102 euro
2. The subtotal cart rule does not apply the free shipping and 0 discount
3. The order total remains at product price and 6 euro shipping costs: 108 euro

---
- Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by bamboekeizer** [comment] 2020-06-02 10:10
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-02 10:10
Hi @bamboekeizer. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-06-02 10:11
Hi @bamboekeizer, here is your [Magento instance](https://i-28472-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28472-2-4-develop.instances.magento-community.engineering/admin_a0ab](https://i-28472-2-4-develop.instances.magento-community.engineering/admin_a0ab)
Login: `b3d8be9e` Password: `fac8c1affc86`
Instance will be terminated in up to 3 hours.

**Comment by Esteraa** [comment] 2020-06-03 08:21
We have the same issue on Magento 2.3.5-p1. For a workaround I changed the free shipping amount to the subtotal price - tax.

**Comment by bamboekeizer** [comment] 2020-06-03 11:11
@magento-engcom-team I could not reproduce the issue on the 2.4-develop instance, unfortunately

**Comment by bamboekeizer** [comment] 2020-06-03 21:08
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment] 2020-06-03 21:08
Hi @bamboekeizer. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment] 2020-06-03 21:10
Hi @bamboekeizer, here is your [Magento instance](https://i-28472-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-28472-2-3-5-p1.instances.magento-community.engineering/admin_f71f](https://i-28472-2-3-5-p1.instances.magento-community.engineering/admin_f71f)
Login: `24628926` Password: `bef83902a39b`
Instance will be terminated in up to 3 hours.

**Comment by bamboekeizer** [comment] 2020-06-03 21:46
Reproduced successfully on 3.5.1-p1

**Comment by ruthgeridema** [comment] 2020-07-02 09:25
Also having this issue. Reproduced on 2.3.5-p1.

Temporary workaround is:
$amount / 1,{$taxrate}. So in NL (21%) with 20$ MOQ:
20/1,21 = 16,53. If you fill this in your good.

**Comment by cproboscht** [comment] 2020-07-10 12:00
Also having this issue in 2.3.5-p1.
Got second problem  which is according to this one: we have the issue, that free shipping is also calculated without tax #13392
we did not have this in 2.3.4-p2 and so we investigated changes:

found this:
vendor\magento\module-tax\Model\Sales\Total\Quote\CommonTaxCollector.php Line 596FF
       $address = $shippingAssignment->getShipping()->getAddress();
        $address->setBaseSubtotalTotalInclTax($baseSubtotalInclTax);
        $address->setSubtotal($total->getSubtotal());
        $address->setBaseSubtotal($total->getBaseSubtotal());

removed 
        $address->setSubtotal($total->getSubtotal());
        $address->setBaseSubtotal($total->getBaseSubtotal());
for test and both issues where fixed?!

**Comment by k4emic** [comment] 2020-09-02 13:59
@magento give me 2.3.5-p2 instance

**Comment by magento-engcom-team** [comment] 2020-09-02 13:59
Hi @k4emic. Thank you for your request. I'm working on Magento 2.3.5-p2 instance for you

**Comment by magento-engcom-team** [comment] 2020-09-02 14:01
Hi @k4emic, here is your [Magento instance](https://i-28472-2-3-5-p2.instances.magento-community.engineering).
Admin access: [https://i-28472-2-3-5-p2.instances.magento-community.engineering/admin_3d2c](https://i-28472-2-3-5-p2.instances.magento-community.engineering/admin_3d2c)
Login: `fee6df65` Password: `940632d1e907`
Instance will be terminated in up to 3 hours.

**Comment by k4emic** [comment] 2020-09-02 14:18
Not able to reproduce this on 2.3.5-p2

**Comment by k4emic** [comment] 2020-09-02 14:19
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment] 2020-09-02 14:19
Hi @k4emic. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment] 2020-09-02 14:21
Hi @k4emic, here is your [Magento instance](https://i-28472-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-28472-2-3-5-p1.instances.magento-community.engineering/admin_29e6](https://i-28472-2-3-5-p1.instances.magento-community.engineering/admin_29e6)
Login: `d501ef65` Password: `9518be51ad2f`
Instance will be terminated in up to 3 hours.

**Comment by k4emic** [comment] 2020-09-03 11:13
We worked around this by introducing a new condition option

```
--- Model/Rule/Condition/Address.php	2020-09-03 12:01:26.000000000 +0200
+++ Model/Rule/Condition/Address.php	2020-09-03 12:53:46.000000000 +0200
@@ -62,7 +62,8 @@
     {
         $attributes = [
             'base_subtotal_with_discount' => __('Subtotal (Excl. Tax)'),
-            'base_subtotal' => __('Subtotal'),
+            'base_subtotal' => __('Subtotal (Avoid this one: Known to be unreliable for most tax settings)'),
+            'base_subtotal_total_incl_tax' => __('Subtotal (Incl. Tax)'),
             'total_qty' => __('Total Items Quantity'),
             'weight' => __('Total Weight'),
             'payment_method' => __('Payment Method'),
```

**Comment by koenner01** [comment] 2020-09-09 09:45
Bumping this ticket as this is quite a critical feature.

The descriptive labels on the address attributes are just plain wrong. The first option was introduced in https://github.com/magento/magento2/pull/21288 but this clearly was a mistake and never properly tested.

The suggestion of @k4emic is going towards the right direction with adding the correct option but the labels are still not very descriptive for the excluding tax options.

**Comment by grassst** [comment] 2020-09-19 07:51
I also have the same problem on 2.3.5-p2.
We are using at least two tax clases. So for us changing the values in the table rate CSV is no option for us.
@k4emic can you please tell me what I have to do to get your work arround running in my system? I changed vendor/magento/module-sales-rule/Model/Rule/Condition/Address.php as you described, but where can i find this new condition to choose?

thank you!

**Comment by willtran** [comment] 2020-10-06 07:23
I believe I am seeing the same problem. 
Found inconsistency here vendor/magento/module-quote/Model/Quote/Address.php:1031
        
**$request->setPackageValue($item ? $item->getBaseRowTotal() : $this->getBaseSubtotal());**

$this->getBaseSubtotal() should be $this->getBaseTotal() _**or**_ 

$item-getBaseRowTotal should be $item->getBaseSubtotal()

**Comment by sdzhepa** [comment] 2020-10-13 14:45
closed as Duplicate of  https://github.com/magento/magento2/issues/29740

**Closed as completed by sdzhepa** 2020-10-13 14:45 UTC
Labels: Issue: Format is valid, Progress: done, Reported on 2.3.3

**Comment by pixel-paul** [comment] 2020-11-23 09:43
This exists in 2.3.6.
