### ISSUE TITLE
Error "Please correct the target currency" when switching store with different currency than default one on GraphQl

### ISSUE THREAD

**Issue by aelmizeb** [magento/magento2#38732] opened 2024-05-16 13:13 UTC
### Preconditions and environment

- Magento 2.4.7
- Issue seems to be related to https://github.com/magento/magento2/issues/31336 exactly on the following function : 
![magento changes](https://github.com/magento/magento2/assets/19288561/60058685-e82d-4046-b00f-5a1cd5e292a4)
The currency validation is done before set the current store in the context, then, the first GraphQL request will try to check the currency with the default store currency.
- Also, now, these validations are executed two times: one in **vendor/magento/module-graph-ql/Controller/GraphQl.php** line **192** and in **vendor/magento/module-graph-ql-cache/Controller/Plugin/GraphQl.php** in beforeDispatch function

### Steps to reproduce

1. In storefront using GraphQl, switch the store to an other with a different currency than default store
2. Check logs 

### Expected result

No error on logs

### Actual result

Logs contains : 
"message":"**Please correct the target currency**"

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-05-21 10:01
Hi @aelmizeb,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- In storefront using GraphQl, switch the store to an other with a different currency than default store
- Check logs


<img width="1231" alt="Screenshot 2024-05-21 at 15 19 48" src="https://github.com/magento/magento2/assets/51680745/e8b1b9a3-245d-45c0-b88c-8d72b8fea795">


<img width="1231" alt="Screenshot 2024-05-21 at 15 19 53" src="https://github.com/magento/magento2/assets/51680745/a4d13640-49c3-48d8-87f5-3e0c1f8a717f">


<img width="1331" alt="Screenshot 2024-05-21 at 15 22 25" src="https://github.com/magento/magento2/assets/51680745/d5931e62-7551-40a0-92e1-b2aaa95d21be">



Could you please provide us the mutation and also provide screenshots it will helps us to proceed further and please let us know if we are missing anything.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-06-03 06:56
Hi @aelmizeb,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-03 06:56 UTC
Labels: Issue: needs update, Reported on 2.4.7
