### ISSUE TITLE
Disable product issue with Cart Item bundle product

### ISSUE THREAD

**Issue by sunilit42** [magento/magento2#25484] opened 2019-11-06 08:36 UTC
### Preconditions (*)

1. Latest Magento
2.  at least one bundle product

### Steps to reproduce (*)

1. Create one bundle product with some simple product and create another simple product
2. do add to cart  bundle product and simple product
3. go to cart page 
4. then disable bundle product from product grid
5. check cart page again, it showing one error msg and checkout button missing https://www.screencast.com/t/ui0FVQfCm
6. then refresh again you will see checkout button
7. same thing working fine if we change status from edit product

### Expected result (*)

1.  edit product status from product edit or grid should be the same behavior
2. it should not show that msg and should show checkout button first time

### Actual result (*)

1.  https://www.screencast.com/t/ui0FVQfCm it should be directly removed and should be shown checkout button

**Comment by ajijshekh123** [comment] 2019-11-06 08:57
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-06 08:57
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-06 08:57
Hi @ajijshekh123, here is your [Magento instance](https://i-25484-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25484-2-3-develop.instances.magento-community.engineering/admin](https://i-25484-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2019-11-06 09:17
I have verified this issue as per the Steps to be reproduced.
**See the attached video:**

![Shoppingcart_Checkout_Issue](https://user-images.githubusercontent.com/24711761/68284911-55107580-00a4-11ea-93f5-366a36467f99.gif)

**Comment by magento-engcom-team** [comment] 2019-11-06 09:18
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22856` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-11-21 08:51
Hi @sunilit42. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-25140` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by bubasuma** [comment] 2019-11-21 19:55
Internal Magento team is working on this issue right now.

**Comment by magento-engcom-team** [comment] 2019-12-03 15:51
Hi @sunilit42. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. 

The fix will be available with the upcoming `2.3.5` release.

**Closed as completed by magento-engcom-team** 2019-12-03 15:51 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Bundle

**Comment by rparsi-boxycharm** [comment] 2020-01-08 19:46
@magento-engcom-team Which commits fixed this issue?

**Comment by matthewhaworth** [comment] 2020-01-27 22:42
Also, wondering what @rparsi-boxycharm asked.

**Comment by rparsi-boxycharm** [comment] 2020-01-27 22:48
@matthewhaworth 


> Also, wondering what @rparsi-boxycharm asked.

According to magento-engcom-team:

> Hi @sunilit42.
> 
> Thank you for your report and collaboration!
> 
> The issue was fixed by Magento team.
> 
> The fix will be available with the upcoming `2.3.5` release.

I searched closed pr's and commit history of various branches, can't find the commits for the fix.
I can't wait for release 2.3.5, need to find the commits magento-engcom-team made so I can create a composer patch and apply the fix(es) to my project.

**Comment by matthewhaworth** [comment] 2020-02-10 21:11
@rparsi-boxycharm Magento said to me that it wouldn't be possible to backport a fix to 2.2.6

**Comment by rparsi-boxycharm** [comment] 2020-02-10 21:20
@matthewhaworth I'm using 2.3.3 with the security only patch 2.3.4-p1.  Can you ask for the commit urls that fixes this issue in 2.3.5?
I don't get why they don't just tell us, I'm fine with back porting it myself.

**Comment by bubasuma** [comment] 2020-02-10 21:36
Sorry guys for the delay,
Here is the commit 41565f0f7b702136668189eb5a2ecfa1d6b82d69 that fixes the issue.

**Comment by rparsi-boxycharm** [comment] 2020-02-10 21:43
@bubasuma Thank you.  Out of curiosity, why isn't it standard procedure to include commit urls whenever some says `blah` issue is fixed in `blah` magento version?  It's annoying having to play conversation tag asking for this info each time, and frequently it takes months for the answer to be finally provided.
