### ISSUE TITLE
Unable to update Image types

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#13724] opened 2018-02-19 13:02 UTC
### Preconditions

1. Magento all versions
2. 

### Steps to reproduce

1. Using Magento\Catalog\Model\Product\Gallery\Processor Class, updateImage function to update image types.
2. Previous data : {
        "id": 224,
        "media_type": "image",
        "label": null,
        "position": null,
        "disabled": null,
        "types": [],
        "file": "/i/m/image_new.jpg"
    }
3. New data : {
        "id": 224,
        "media_type": "image",
        "label": null,
        "position": 0,
        "disabled": false,
        "types": ['image'],
        "file": "/i/m/image_new.jpg"
    }
4. In new data, i am trying to image disabled and types.

### Expected result

1. Disabled and types should be updated:
{
        "id": 224,
        "media_type": "image",
        "label": null,
        "position": 0,
        "disabled": false,
        "types": ['image'],
        "file": "/i/m/image_new.jpg"
    }

### Actual result

1. Disabled got update but types not updated
{
        "id": 224,
        "media_type": "image",
        "label": null,
        "position": 0,
        "disabled": false,
        "types": [],
        "file": "/i/m/image_new.jpg"
    }

Please check and let us know if we are missing anything.

**Comment by me2r036** [comment] 2018-03-15 03:11
Hi there,
updateImage() won't update media attribute, i.e. "types". 

As you can see the $fieldsMap does not contain "type".
    public function updateImage(\Magento\Catalog\Model\Product $product, $file, $data)
    {
        $fieldsMap = [
            'label' => 'label',
            'position' => 'position',
            'disabled' => 'disabled',
            'exclude' => 'disabled',
            'media_type' => 'media_type',
        ];
       ...
}

Instead, we assign media attributes when adding image using addImage() or you can set media attribute by using setMediaAttribute().

$this->_mediaProcessor->addImage($product, $file, yourData['type'], false, false);
or
$this->_mediaProcessor->setMediaAttribute($product, yourData['type'], yourData['file']);

Hope these help.

Kind regards,
Jeremy Ren

**Comment by engcom-backlog-nickolas** [comment] 2018-08-07 08:54
Hello @ankursachdeva11, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2019-06-20 20:37
Hi @ankursachdeva11. 

Thank you for your report and collaboration!

The related internal Jira ticket `MAGETWO-94535` was closed as `non-reproducible` in `2.2.x`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Closed as completed** 2020-10-16 18:31 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue:  Cannot Reproduce, Issue: Format is valid, Progress: done
