### ISSUE TITLE
Using search in Admin panel, and choosing "% in Products" returns full catalog

### ISSUE THREAD

**Issue by spyrule** [magento/magento2#7861] opened 2016-12-17 18:30 UTC
If you attempt to use the Search tool in the admin panel, and select "XX in Products" that appears, it brings you to the full catalog view, without narrowing down the list.

### Preconditions

1. Magento 2.1.3 CE, 
2. PHP 7.0.14
3. NginX (not sure of the version, hosted service)

### Steps to reproduce

1. upload/create ~10 products in the catalog, create 3 with SKU's starting with "ZX-"
2. Click on the Search icon at the top
3. Type in ZX-
4. Choose "ZX- in Products"
5. Wait for the catalog view to appear.

### Expected result

1. It should only show the products with the SKU ZX- in their SKU

### Actual result

1. It actually shows the entire catalog of products with no filtering applied.

**Comment by VasylShvorak** [comment] 2017-06-21 14:11
Internal ticket was created MAGETWO-70067

**Comment by magento-engcom-team** [comment] 2017-10-04 11:30
@spyrule, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by laconica-sergey** [comment] 2017-12-15 08:19
#mageconf

**Comment by magento-engcom-team** [comment] 2017-12-15 08:20
@laconica-sergey thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by laconica-sergey** [comment] 2017-12-15 11:01
duplicate #12193

**Comment by magento-engcom-team** [comment] 2018-04-28 07:54
Hi @spyrule. Thank you for your report. 
The issue has been fixed in magento/magento2#12735 by @hannassy in 2.2-develop branch
Related commit(s):
 - [0666b27c6f3aed663992beb166ef97f5523c2355](https://github.com/magento/magento2/commit/0666b27c6f3aed663992beb166ef97f5523c2355)
 - [f5d93c3e04ebf7ee8fd2537c7415ae3b11ba07a9](https://github.com/magento/magento2/commit/f5d93c3e04ebf7ee8fd2537c7415ae3b11ba07a9)
 - [790ac311344350c33af6f6a697a8d5f8bfe478d8](https://github.com/magento/magento2/commit/790ac311344350c33af6f6a697a8d5f8bfe478d8)

The fix will be available with the upcoming 2.2.5 release.

**Closed as completed by magento-engcom-team** 2018-04-28 07:54 UTC
Labels: Issue: Ready for Work, bug report, Component: Search, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
