### ISSUE TITLE
Command app:config:dump add unnecessary spacing every time it's run

### ISSUE THREAD

**Issue by Linek** [magento/magento2#11664] opened 2017-10-23 23:21 UTC
### Preconditions

1. PHP 7.0.24
2. nginx/1.11.13
3. Percona Ver 14.14 Distrib 5.7.19-17
4. Magento 2.2.0 installed with sample data by composer

### Steps to reproduce

1. Run "bin/magento app:config:dump" to dump configuration to app/etc/config.php file
2. Save your config.php file somewhere to compare
3. Run "bin/magento app:config:dump" again
4. Compare config.php after second dump with the one after first dump

### Expected result
File config.php should not change when there is no modification in configuration

### Actual result
Every time app:config:dump is run few fields is generated with additional spaces

![image](https://user-images.githubusercontent.com/136248/31917678-07f56a2a-b859-11e7-8959-30d6e35438ee.png)

List of fields:
default_custom_instructions
minify_exclude
address_templates

**Comment by davidalger** [comment] 2017-10-24 03:34
Closing as duplicate of #11328; fixed in 2.1-develop, there are PRs in progress for 2.2 and 2.3 to apply the same fix.

**Closed as completed by davidalger** 2017-10-24 03:34 UTC
Labels: Issue: Format is valid
