### ISSUE TITLE
M2.1 Multishipping Checkout step New Address - Old State is saved when country is changed

### ISSUE THREAD

**Issue by ajaysinghrana23** [magento/magento2#8621] opened 2017-02-20 13:56 UTC
**Preconditions**

1) Magento ver. 2.1.3
2) PHP 7

**Steps to reproduce**
1. Add multiple product to cart (minimum 2 product or 1 product with quantity 2) .
2. Check Out with Multiple Addresses.
3. Now Click on Enter a New Address button.
4. Now fill the form with **Country : United States** and select **State : New Jersey**
5. Others fields value can be anything you like 
6. Now before saving the form, do change in country and State.
7. Select **Country : Australia** and set **State: NSW**
8. No Click on Save Address Button.
9. You will be redirected to Ship to Multiple Addresses page.
10. In address dropdown, look for Address you just saved. You will see **"New Jersey"** in address dropdown.
11. But we saved **"NSW"** as State from Multishipping New Address form.

**Expected result**

1. Old State **"New Jersey"** was saved in the address dropdown.
2. State we saved was **"NSW"**

**Actual result**
1. State that we last select must be saved whether its from dropdown or Field.
2. I have attached 4 screenshot stepwise.

![step1](https://cloud.githubusercontent.com/assets/25449889/23127794/519b997e-f7a2-11e6-8840-bade42b248dd.png)
![step2](https://cloud.githubusercontent.com/assets/25449889/23127798/568c3eb6-f7a2-11e6-9e13-7684bbe2b9bb.png)
![step3](https://cloud.githubusercontent.com/assets/25449889/23127800/59233468-f7a2-11e6-96ea-bb22889cca99.png)
![step4](https://cloud.githubusercontent.com/assets/25449889/23127804/5b8ec37a-f7a2-11e6-9b3d-eaac7ab46f59.png)

**Comment by AlexWorking** [comment] 2017-06-30 11:45
Hello, @ajaysinghrana23. An internal ticked MAGETWO-70378 has been created based upon Your issue. You'll be informed as the issue is fixed. Thank You for applying.

**Comment by magento-engcom-team** [comment] 2017-10-05 11:30
@ajaysinghrana23, thank you for your report.
We've created internal ticket(s) MAGETWO-70378 to track progress on the issue.

**Comment by enriquei4** [comment] 2018-01-23 22:09
I'm working on: https://github.com/magento/magento2/pull/13339

**Comment by magento-team** [comment] 2018-01-25 23:00
Hi @ajaysinghrana23. Thank you for your report. 
The issue has been fixed in magento/magento2#13339 by @enriquei4 in 2.3-develop branch
Related commit(s):


The fix will be available with the upcoming patch release.

**Comment by okorshenko** [comment] 2018-01-30 22:36
Hi @ajaysinghrana23. Thank you for your report. 
The issue has been fixed in magento/magento2#13367 by @enriquei4 in 2.1-develop branch
Related commit(s):
 - d0aba21ca2782c197efbd474ce3045455d795592

The fix will be available with the upcoming patch release.

**Comment by magento-engcom-team** [comment] 2018-01-31 01:05
Hi @ajaysinghrana23. Thank you for your report. 
The issue has been fixed in magento/magento2#13364 by @enriquei4 in 2.2-develop branch
Related commit(s):
 - 1b2a17cd137a32718d9732905adabd6d9ed843cc

The fix will be available with the upcoming patch release.

**Closed as completed by magento-engcom-team** 2018-01-31 01:05 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
