### ISSUE TITLE
REST API /V1/orders ignores sortOrders

### ISSUE THREAD

**Issue by vanderlee** [magento/magento2#3788] opened 2016-03-15 11:26 UTC
## Steps to reproduce
1. Install Magento with sample data.
2. Call `/V1/orders` with a single `sortOrders` with `field` `created_id` and `direction` `DESC`. (used path: `/V1/orders?searchCriteria%5BsortOrders%5D%5B0%5D%5Bfield%5D=created_at&searchCriteria%5BsortOrders%5D%5B0%5D%5Bdirection%5D=ASC`)
## Expected result
1. Orders sorted according to criteria.
## Actual result
1. Unsorted orders.
## Note

I couldn't find any `field` which caused results to be sorted correctly, regardless of `direction`.

**Comment by NadiyaS** [comment] 2016-03-15 12:08
Duplicate of #3018. Tracking as MAGETWO-49212 internal issue.

**Closed as completed by NadiyaS** 2016-03-15 12:08 UTC
