### ISSUE TITLE
Magento 2.1 Customers Address Book Not Displayed Properly

### ISSUE THREAD

**Issue by chrone81** [magento/magento2#5681] opened 2016-07-18 04:01 UTC
## Steps to reproduce
1. Install Magento 2.1 CE
2. Add or Edit Address Book when checking out
3. Go to My Account to see my Address Book
## Expected result
1. The Customers Address Book information should be displayed properly
## Actual result
1. The Address Book in frontend "customer/address" and backend "Customer Information > Customer View > Addresses" display field variables instead of the address value we just entered.

![magento 2 frontend customer address book bug](https://cloud.githubusercontent.com/assets/1284195/16905848/d36109b6-4cd6-11e6-8c93-f3926b8106e1.png)
![magento 2 backend customer address book bug](https://cloud.githubusercontent.com/assets/1284195/16905850/dd84029a-4cd6-11e6-9ce7-1cd808eb041e.png)

**Comment by andimov** [comment] 2016-08-02 10:40
@chrone81 
Thank you for reporting!
Did you migrate from a previous version?

**Comment by andimov** [comment] 2016-08-02 10:41
@chrone81 
Try to use this solution: https://github.com/magento/magento2/issues/5873#issuecomment-236868255

**Comment by chrone81** [comment] 2016-08-02 11:07
Nope, this is on new installation. :)

Thanks @andimov I'll look it  up on my spare time.

**Comment by ilol** [comment] 2016-09-23 15:01
@chrone81 did you have a chance to look up?

**Comment by chrone81** [comment] 2016-09-23 15:23
@andimov @ilol Oops, I missed this one, sorry, busy at work. Let me check real quick today and update you later.

**Comment by chrone81** [comment] 2016-09-23 15:54
@ilol Sorry I'm no expert with MySQL cli. How to update the entity_type_id to '2' properly?

> select \* from eav_entity_type;
> +----------------+------------------+----------------------------------------------------+
> | entity_type_id | entity_type_code | entity_model                                       |
> +----------------+------------------+----------------------------------------------------+
> |              4 | customer         | Magento\Customer\Model\ResourceModel\Customer      |
> |              7 | customer_address | Magento\Customer\Model\ResourceModel\Address       | 
> +----------------+------------------+----------------------------------------------------+
> 
> update eav_entity_type set entity_type_id = '2';
> ERROR 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails (`chronic101_magento2`.`eav_attribute`, CONSTRAINT `EAV_ATTRIBUTE_ENTITY_TYPE_ID_EAV_ENTITY_TYPE_ENTITY_TYPE_ID` FOREIGN KEY (`entity_type_id`) REFERENCES `eav_entity_type` (`entity_type_id`) O)
> 
> > select \* from eav_attribute_set;
> > +------------------+----------------+--------------------+------------+
> > | attribute_set_id | entity_type_id | attribute_set_name | sort_order |
> > +------------------+----------------+--------------------+------------+
> > |                4 |              4 | Default            |          2 |
> > |                7 |              7 | Default            |          2 |
> > |               10 |             10 | Default            |          1 |
> > |               13 |             13 | Default            |          1 |
> > |               16 |             16 | Default            |          1 |
> > |               19 |             19 | Default            |          1 |
> > |               22 |             22 | Default            |          1 |
> > |               25 |             25 | Default            |          1 |
> > |               28 |             13 | Top                |          0 |
> > |               31 |             13 | Bottom             |          0 |
> > |               34 |             13 | Gear               |          0 |
> > |               37 |             13 | Sprite Stasis Ball |          0 |
> > |               40 |             13 | Sprite Yoga Strap  |          0 |
> > |               43 |             13 | Downloadable       |          0 |
> > |               46 |             13 | Bag                |          0 |
> > +------------------+----------------+--------------------+------------+

**Comment by sevos1984** [comment] 2016-10-31 11:23
Is this still actual in latest release version?

**Comment by sevos1984** [comment] 2016-11-14 12:19
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-11-14 12:19 UTC
Labels: bug report, Progress: needs update, Component: Customer

**Comment by Dart18** [comment] 2017-01-18 11:37
Please reopen this issue, it's related to #5873, see my comment [here](https://github.com/magento/magento2/issues/5873#issuecomment-273334035). It affects M2.1.3 after migration.
