### ISSUE TITLE
In the invoice it is not shown, if the invoice email has been sent or not

### ISSUE THREAD

**Issue by norgeindian** [magento/magento2#27474] opened 2020-03-27 14:51 UTC
### Preconditions (*)

Magento 2.3.4

### Steps to reproduce (*)

1. Create an order
2. Create the corresponding invoice in the backend
3. Open the invoice in the backend and take a look at the header

### Expected result (*)

I would assume to see an information in the header section of the invoice, which informs me if the invoice email has been sent or not. It was this way in Magento 1, it is available for the order, but not for the invoice. So you only see, if the order confirmation mail has been sent out, but not if the invoice is actually sent or not.

### Actual result (*)

No email hint is shown.
![Screenshot from 2021-05-05 10-50-54](https://user-images.githubusercontent.com/11156287/117117495-e3e07a00-ad8f-11eb-8b77-17c3051964a1.png)

I debugged this issue a bit. The email hint would normally be processed by `\Magento\Sales\Block\Adminhtml\Order\Invoice\View::getHeaderText`. But this function is never called as far as I can see. The corresponding block is defined in `vendor/magento/module-sales/view/adminhtml/layout/sales*order_invoice*view.xml:14`, but has no template defined. In the end this block is initialized in `\Magento\Sales\Controller\Adminhtml\Order\Invoice\View::execute` where the title is set. But there only the invoice increment id is shown, no status hint.

**Comment by shikhamis11** [comment] 2020-03-27 18:56
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-27 18:56
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-03-27 18:56
Hi @shikhamis11, here is your [Magento instance](https://i-27474-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27474-2-4-develop.instances.magento-community.engineering/admin_5e79](https://i-27474-2-4-develop.instances.magento-community.engineering/admin_5e79)
Login: `0ba49f1c` Password: `f1a98bbb5c9f`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2020-03-27 19:07
Hi @norgeindian 
I checked and found the email sent information is there in invoice view on magento 2.4 instance 
Please check below image 

![image](https://user-images.githubusercontent.com/25526037/77791267-514db180-708c-11ea-9a18-ad8034ead2cf.png)

**Comment by sprankhub** [comment] 2020-03-27 19:34
@shikhamis11 please mind that @norgeindian is talking about the **invoice** email. In your screenshot, I can see that there is a note that the **order** confirmation email was not sent, but nothing is shown regarding the **invoice** email. Could you please double check?

**Comment by magento-engcom-team** [comment] 2020-04-01 07:12
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32976` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by luanalves** [comment] 2020-04-04 18:06
Hi @norgeindian default magento send email from invoice, and send custom information when write comment in box

**Comment by luanalves** [comment] 2020-04-11 11:02
@shikhamis11 why do you remove the assignment ? I'm response your question

**Comment by norgeindian** [comment] 2020-04-20 09:32
@luanalves , @shikhamis11 , during the invoice creation step a backend user can choose if the invoice mail should be sent or not. As it is possible to send the mail later again in the backend view of the invoice, it should be visible if the mail has already been sent or not in my eyes. 
This was already shown in Magento1 and I don't see a reason, why it should not be displayed in Magento2 as well.
Do you need any more information regarding this issue from my side?

**Comment by shikhamis11** [comment] 2020-04-20 11:12
@norgeindian this issue is already confirmed and ticket has been created.
If you have possible solution for the issue you can create pull request for this issue.

**Comment by monikav-dckap** [comment] 2020-08-27 17:18
@magento I am working on this

**Comment by norgeindian** [comment] 2021-01-29 08:42
@monikav-dckap , any news regarding this issue?

**Comment by sprankhub** [comment] 2021-05-04 18:37
Still relevant :roll_eyes:

**Comment by petrovsa** [comment] 2021-05-05 07:43
![Screenshot from 2021-05-05 10-41-21](https://user-images.githubusercontent.com/41642399/117110259-8697f900-ad8e-11eb-9866-8ad5eff2a8ab.png)
On 2.4-develop. Recheck please

**Comment by magento-engcom-team** [comment] 2021-05-05 07:51
Hi @norgeindian. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-32976` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by norgeindian** [comment] 2021-05-05 08:03
@petrovsa , your screenshot only provides information about the order confirmation mail.
This issue is about the invoice and the information if this has been sent or not.
Please be so kind and check again.

**Comment by petrovsa** [comment] 2021-05-05 08:30
@norgeindian You are right!  Information is absent about the invoice and the information if this has been sent or not

**Comment by magento-engcom-team** [comment] 2021-05-05 08:40
Hi @norgeindian. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-32976` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by norgeindian** [comment] 2021-05-05 09:01
@petrovsa , thanks for checking. Do you have the possibility to reopen this issue somehow resp. re-open JIRA ticket `MC-32976`

**Comment by petrovsa** [comment] 2021-05-05 09:20
@norgeindian I don`t have possibility reopen this issue.

**Comment by norgeindian** [comment] 2021-05-05 09:40
@dmitriyprime , thanks for trying, but it's still closed...

**Comment by sdzhepa** [comment] 2021-05-10 18:34
Reopened due to request from the community. 
The issue should be reconsidering one more time

**Comment by norgeindian** [comment] 2021-06-07 06:09
@sdzhepa , great, thanks a lot.
It would be awesome if this could be fixed, as this is a pretty important information for a shop owner....

**Comment by norgeindian** [comment] 2021-09-16 14:12
Why is this ticket closed @sdzhepa ?
In version 2.4.3 this is still not fixed.

**Comment by norgeindian** [comment] 2021-10-11 07:45
@sdzhepa , in my eyes this is still open. Please be so kind and check again

**Comment by norgeindian** [comment] 2021-11-08 10:42
@sdzhepa , this is still a bug. Please be so kind and open this ticket again.

**Comment by sdzhepa** [comment] 2021-11-11 19:40
Hello @norgeindian 

I asked the team to check it and provide details 

cc: @engcom-Hotel

**Comment by engcom-Alfa** [comment] 2021-11-12 11:24
we are re-opening this issue to cross check again in the 2.4-develop.

**Comment by engcom-Hotel** [comment] 2021-11-16 08:46
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2021-11-16 09:01
Hello @norgeindian,

The issue is reproducible in the Magento 2.4-develop branch, hence confirming this issue. Please refer below screenshot for reference:

![image](https://user-images.githubusercontent.com/51681618/141954510-eb47b409-273a-4ca2-a98c-59ca89603923.png)

Thanks

**Comment by norgeindian** [comment] 2022-03-14 11:26
@engcom-Hotel , thanks for your feedback. What's the current status of this issue?

**Comment by norgeindian** [comment] 2022-05-09 13:29
@engcom-Hotel , what's the current status here?

**Comment by norgeindian** [comment] 2022-06-13 09:03
@engcom-Hotel , any update on this?

**Comment by engcom-Hotel** [comment] 2022-06-17 07:25
Hello @norgeindian,

I will update you on this soon

Thanks

**Comment by norgeindian** [comment] 2022-07-18 10:00
@engcom-Hotel , do you have any news for me?

**Comment by norgeindian** [comment] 2022-08-08 05:55
@engcom-Hotel , what's the current status here?

**Comment by engcom-Hotel** [comment] 2022-08-08 08:16
Hello @norgeindian,

The JIRA ticket is still in process. I will update on this further.

Thanks

**Comment by topanok** [comment] 2022-08-23 12:38
@magento I am working on this

**Comment by topanok** [comment] 2022-12-11 10:30
@norgeindian Hello. Here is the PR. Unfortunately, reviewers have not responded to it for 3 months. https://github.com/magento/magento2/pull/36030

**Closed as completed** 2023-08-31 01:54 UTC
Labels: Component: Sales, Issue: Confirmed, Component: Admin, Reproduced on 2.4.x, Priority: P2, Severity: S3, Progress: done, Reported on 2.3.4, Area: Order
