### ISSUE TITLE
magento 2: all form inputs cut in half in admin side

### ISSUE THREAD

**Issue by gelanivishal** [magento/magento2#7716] opened 2016-12-07 12:30 UTC
I first noticed this bug on chrome canary and now occurs with the latest update to chrome beta. I have logged it as a bug to chrome, but wanted to get some additional input if this bug is indeed chrome related or is actually magento.

Chrome Version: Chrome/55.0.2883.75 
![tugxx](https://cloud.githubusercontent.com/assets/12389799/20967542/0c257644-bca6-11e6-8e20-9a5703f640f8.png)

If I remove the float on .admin__legend, form changes to this

![igjzt](https://cloud.githubusercontent.com/assets/12389799/20967544/0c268408-bca6-11e6-9be4-a8fa194d3428.png)

It seems that the legend tag's width is unable to be changed, which may be causing the issue and the additional white space inside the legend tag.

Here is what I have tried

![45hp4](https://cloud.githubusercontent.com/assets/12389799/20967543/0c267f8a-bca6-11e6-9d47-5a97ca3e2345.png)

Ultimately I could solve this with position: absolute; but I feel like that is cheating.

Let me know if you think this is a chrome related issue or something magento needs to prepare to fix. Also I'd be interested if anyone can come up with a simple fix.

**Comment by ihor-sviziev** [comment] 2016-12-08 07:03
https://github.com/magento/magento2/issues/7155

**Comment by veloraven** [comment] 2016-12-21 14:58
I'm closing this issue as a duplicate of #7155.

**Closed as completed by veloraven** 2016-12-21 14:58 UTC
