### ISSUE TITLE
Cleanup of cron_schedule database table doesn't cleanup non-existing jobs

### ISSUE THREAD

**Issue by hostep** [magento/magento2#38217] opened 2023-11-24 10:14 UTC
### Preconditions and environment

- Magento version 2.4.6-p3 (but most likely all versions will be affected)

### Steps to reproduce

Explanation below how to trigger this with a cronjob from inside core Magento. But the most likely cases will come from 3rd party modules containing cronjobs, that were installed for a while and then removed again.

1. Have a Magento shop with MSI modules enabled
2. Have a working crontab and have it running for a couple of hours
3. Inspect the `cron_schedule` table and notice that the job `inventory_in_store_pickup_sales_send_order_notified_emails` is mentioned many times with status `success`
4. Now, disable all MSI modules in `app/etc/config.php` and run `bin/magento setup:upgrade`
5. Keep the crontab running for a few more hours
6. Inspect your `cron_schedule` table again

### Expected result

It's expected that all jobs that were successful and having run more than 60 minutes ago are removed from the `cron_schedule` table.

### Actual result

See that there are still jobs `inventory_in_store_pickup_sales_send_order_notified_emails` in the table with status success and being older then 60 minutes. Those don't get cleaned up because the MSI modules are no longer active and calling `getJobs()` [over here](https://github.com/magento/magento2/blob/2.4.6-p3/app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php#L577) doesn't return jobs from inactive (or removed) modules.

### Additional information

Ideally, the cronjob cleanup should also figure out which jobs are in the `cron_schedule` table that are no longer found in the system and clean those up as well.
Or maybe this can be added in the existing Recurring data script that exists in the Magento_Cron module, as then it doesn't need to be checked every minute when the cron actually runs. Since removing and disabling modules requires a `bin/magento setup:upgrade` call anyway, it might be a good idea to only then check for outdated entries in that table and remove them...

And since the `cron_schedule` table receives a lot of queries the entire day, it's beneficial to performance that it contains as few rows as possible. Old data should be cleaned up automatically.

I found this in a shop where we have hundreds of entries from 2021 in the `cron_schedule` table for jobs that for a long time no longer existed.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ananth-iyer** [comment] 2023-11-28 07:24
@magento I am working on this

**Comment by engcom-Dash** [comment] 2024-01-12 14:07
Hi @hostep 

Thanks for reporting and collaboration.

It is not advisable to disable MSI modules.

As per the adobe dev docs, Disabling the Inventory Management modules can cause an unstable system and result in various issues.

Please refer the below devdocs for more information :

https://experienceleague.adobe.com/docs/commerce-admin/inventory/get-started/install-update.html

Thanks

**Comment by hostep** [comment] 2024-01-12 15:05
@engcom-Dash: that's not the point, this was just the easiest way I could find to demonstrate the problem 😉 

This will most likely happen in the real world where you had a third party module installed (which contains a cronjob) for a couple of months and then decide to remove it again. Afterwards, you'll still find entries from that no longer existing module in your `cron_schedule` table and that is polluting the database.

Please re-read the description and if it's not clear, try to pull in one of your colleagues and see if they understand it better. And if it's still not clear, then let me know what's not clear so I can try to describe it better.

**Comment by engcom-Dash** [comment] 2024-01-23 13:38
Hi @hostep 

Thanks for reporting and collaboration.

Verified the issue in magento 2.4 dev instance and the issue is reproducible.

After disabling MSI modules , seeing the inventory_in_store_pickup_sales_send_order_notified_emails in the table with status success when we run the cron job and checked in the cron_schedule table.

Please refer the attached screenshots.
<img width="1440" alt="Screenshot 2024-01-23 at 11 21 50 AM" src="https://github.com/magento/magento2/assets/60198592/6a68f2eb-6272-4ec2-a3fd-efef9bb59077">
<img width="1440" alt="38217_Confiremd" src="https://github.com/magento/magento2/assets/60198592/c0f50d08-5500-4dc5-a651-bdd1cfe981b7">

**Closed as completed** 2024-07-04 16:37 UTC
Labels: Component: Cron, Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Catalog, Reported on 2.4.6-p3
