### ISSUE TITLE
VAT Number input not appearing in checkout shipping address

### ISSUE THREAD

**Issue by ErikDW1** [magento/magento2#37456] opened 2023-05-03 13:09 UTC
### Preconditions and environment

- Magento version 2.4-develop

### Steps to reproduce

1. Add something to cart
2. Navigate to checkout page

### Expected result

The shipping address form should include the VAT number input.

### Actual result

The shipping address form doesn't include the VAT number input.

### Additional information

I have enabled both options:

- Stores-> Configurations->Customer->Customer Configuration->Create New Account Options -> Show VAT Number on Storefront ->yes
- Stores-> Configurations->Customer->Customer Configuration->Name & Address Options -> Show Tax/VAT Number ->required

The VAT number input shows on Account creation page but not in checkout page in Shipping Address.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ErikDW1** [comment] 2023-05-03 13:10
@magento give me 2.4-develop instance

**Comment by swleighton** [comment] 2023-05-04 00:51
@magento give me 2.4.5-p1 instance with ee

**Comment by swleighton** [comment] 2023-05-04 01:08
@magento give me 2.4.5-p1 instance with edition ee

**Comment by swleighton** [comment] 2023-05-04 01:14
@magento give me 2.4-develop instance with edition ee

**Comment by engcom-November** [comment] 2023-05-04 04:01
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2023-05-04 04:09
Hi @ErikDW1 ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance but the issue is not reproducible.
VAT number input field is getting displayed on Shipping form page and user is able to place order.
![image](https://user-images.githubusercontent.com/60198231/236110650-d84b58aa-df54-4c7f-8d2a-72a8b9822d8f.png)
Kindly recheck the issue on Magento 2.4-develop instance as it is having latest code base and upcoming 2.4.x release and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by swleighton** [comment] 2023-05-04 04:11
@magento give me 2.4-develop instance with edition ee

**Comment by swleighton** [comment] 2023-05-04 23:58
@magento give me 2.4-develop instance with edition ee

**Comment by ErikDW1** [comment] 2023-05-05 13:46
> Hi @ErikDW1 , Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance but the issue is not reproducible. VAT number input field is getting displayed on Shipping form page and user is able to place order. ![image](https://user-images.githubusercontent.com/60198231/236110650-d84b58aa-df54-4c7f-8d2a-72a8b9822d8f.png) Kindly recheck the issue on Magento 2.4-develop instance as it is having latest code base and upcoming 2.4.x release and provide missing steps if any if the issue is still reproducible. Thank you.

@engcom-November Yes I found out that there was an issue with a plugin installed on my instance: more specifically Hevelop/invoice-request is altering the distribution of fields between shipping and billing forms.

By the way, now that I got to display the field, how do I make it as required?
In the Stores-> Configurations->Customer->Customer Configuration->Name & Address Options -> Show Tax/VAT Number I set it as "Required", however it is required only on the signup form but not on the shipping one.

**Comment by engcom-November** [comment] 2023-05-18 05:51
Hi @ErikDW1 ,
VAT number can be made as mandatory / required filed in Shipping form page as well if configured as per Magento [docs](http://docs.magento.com/m2/ce/user_guide/tax/vat-validation-configure.html) or by directly updating from Database
`UPDATE `eav_attribute` SET `is_required` = '1' WHERE `eav_attribute`.`attribute_id` = 36;`
![image](https://github.com/magento/magento2/assets/60198231/82520e4a-80ab-4d61-83f6-306627675c62)

**Comment by engcom-Bravo** [comment] 2023-05-31 06:11
Hi @ErikDW1,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-05-31 06:11 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
