### ISSUE TITLE
empty space display below footer in search term page

### ISSUE THREAD

**Issue by renard123** [magento/magento2#22974] opened 2019-05-22 13:00 UTC
empty space display below footer in search term page

### Preconditions (*)
magento 2.3

### Steps to reproduce (*)
A. Front end -> Add 6-7 different product to the cart
B. Search Term page -> Open floating cart and scroll down to footer
C. Displaying empty space below footer

### Expected result (*)
Empty space should not display after footer.

### Actual result (*)
![image](https://user-images.githubusercontent.com/50658701/58176178-5e0cb680-7cbf-11e9-8352-998abbed021e.png)

**Comment by krishprakash** [comment] 2019-05-22 13:01
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-05-22 13:01
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-05-22 13:02
Hi @krishprakash, here is your [Magento instance](https://i-22974-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22974-2-2-develop.instances.magento-community.engineering/admin](https://i-22974-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-05-22 13:13
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99797`, `MAGETWO-99798` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by abrarpathan19** [comment] 2019-05-23 11:40
@krishprakash @magento-engcom-team 
I have review Issue we can't consider as a bug because we can't add the fixed height to minicart and also we can't set the minimum height to the main content area when content is not available.
so, I am going to close this issue

**Closed as completed by abrarpathan19** 2019-05-23 11:40 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Component: Ui, Area: Design/Frontend
