### ISSUE TITLE
[GraphQL] Query all available routes in Magento for static builds and sitemaps.

### ISSUE THREAD

**Issue by paales** [magento/magento2#35508] opened 2022-05-20 08:52 UTC
*As a developer I want to be able to fetch all available routes based on their typename so that I can use those routes to statically generate those routes*

*As a developer I want to be able to fetch all available routes so that I can easily generate a sitemap for my storefront*

### AC

Be able to run the following query

```graphql
query SimpleProducts {
    routes(filter: { type: [SimpleProduct] }, pageSize: 1000, currentPage: 1) {
        __typename
       redirect_code
       relative_url
    }
}
```

### Approved Schema

```graphql
enum RoutableImplementors {
    CategoryTree
    CmsPage
    VirtualProduct
    SimpleProduct
    DownloadableProduct
    BundleProduct
    GroupedProduct
    ConfigurableProduct    
}

input RoutesFilterInput {
  type: [RoutableImplementors]
}

type Query {
  routes(filter: RoutesFilterInput, pageSize: Int = 200, currentPage: Int = 1): [RoutableInterface]
}
```

**Comment by engcom-November** [comment] 2022-05-20 11:44
Hi @paales ,
Thank you for reporting and collaboration. We are closing this issue as this is a duplicate of https://github.com/magento/magento2/issues/35507. Please move on to this ticket for latest updates/ solutions.
Thank you.

**Closed as completed by engcom-November** 2022-05-20 11:44 UTC
Labels: duplicate, Project: GraphQL, Issue: ready for confirmation
