### ISSUE TITLE
How to import products with its images

### ISSUE THREAD

**Issue by adzminz** [magento/magento2#1298] opened 2015-05-23 07:40 UTC
Hi,

Can someone please guide me how to import products with images using import functionality?

Here what I've tried:
1. Export an existing product to cvs as a template.
2. Transfer images to ../pub/media/catalog/product/import
3. Modify the template the products I want to add.
4. For any related image columns, put /import/example1.jpg

All products are successfully imported without images.

Thanks

**Comment by asemenenko** [comment] 2015-05-26 10:13
Hi @adzminz 

We already have this improvement assigned to the development team and it is in progress. We will update you once it gets resolved.

/regards
Andrii

**Comment by adzminz** [comment] 2015-06-26 08:24
It's possible to import products and product images now. Thank you!

**Comment by SLv99** [comment] 2015-06-29 12:43
Hi @adzminz,

I'm also trying to import products with images. All products are added, but no images. I'm on beta15. Can you provide instructions to import products with images?

Thanks.

**Comment by naspar** [comment] 2015-06-29 18:22
Hi SLv99,

I am trying to achieve the same .. quick question : did you find any how-to or step-by-step procedure about how to import product ? i guess we need a csv .. also as soon as you know how to link the images .. please share the info.

I have been trying to import products by using the API but facing several issues .. not sure the API layer is ready or stable yet for such purpose.

Thanks

**Comment by SLv99** [comment] 2015-06-30 06:14
Hi naspar,

No, there is no step-by-step procedure. But since beta 15 there is an example CSV file available from the import file page. This works great. Also the export works better. So you could manually create some products and export these as an example for your import file.

Regards
Silvan

**Comment by adzminz** [comment] 2015-06-30 17:12
Hi @SLv99,

What is your web server? Nginx/Apache?

On beta 15, I still have an issue where no product images imported when using Nginx with the configuration file provided by Magento -> https://github.com/magento/magento2/blob/develop/nginx.conf.sample
However, it seems this issue didn't appear when using Apache. So my workaround is to switch web server from Nginx to Apache just for import purpose.

I haven't have time to find the root cause yet (maybe not the sample nginx config). This is my import file https://drive.google.com/file/d/0BzRi20am0HfyQTduLV81Sl82MWc/view?usp=sharing  ***Some fields need to be corrected***

Thanks,

**Comment by SLv99** [comment] 2015-07-01 06:27
I can confirm that the image import is working with your import file. My web sever is Apache. My own import file does also import the images now, thanks! 

For image import, I did the following:
* Upload all images to pub/media/import
* Add image names to your csv file, both the base_image and additional_images columns did work for me
* Leave 'Images File Directory' empty on import

**Comment by minikist** [comment] 2015-10-29 11:15
Hello, 
Is this still an issue in 1.0.0-beta? I try to import products, but the images doesn't work for me. 
I tried:
- Upload all images to pub/media/import
- Add image names to your csv file, both the base_image and additional_images columns did work for me
- Leave 'Images File Directory' empty on import
the product is succesfully loaded and when i edit the product i can see the image_label(alt tag) of the images but there is no images.

Can someone help me with this?
Thanks

**Comment by SLv99** [comment] 2015-10-29 11:23
Hi,

As far as I know, this issue is fixed. I imported multiple products with images. Do you see the image in the Image Management tab for the product?

What I did to import:
* Added image name with extension to import file for columns base_image and thumbnail
* Uploaded images to var/import
* Added Image File Directory: var/import

After a reindex the products are shown with the image.

**Comment by minikist** [comment] 2015-10-29 11:39
Hello SLv99,
Thanks for the fast reply,
i have add a printscreen of the product and the import screen.
this is what i see. 

all the images are moved to install_dir/var/import

![error magento](https://cloud.githubusercontent.com/assets/15378686/10817336/678c667a-7e39-11e5-8414-f65ee96adad0.png)

my csv file 
base_image = 2_pic1.jpg
base_image_label = 40000001
small_image = 
small_image_label = 
thumbnail_image = 2_pic1.jpg	
thumbnail_image_label = 40000001
additional_images = 2_pic1.jpg
additional_image_labels = 40000001

i also run apache.
Thanks

**Comment by SLv99** [comment] 2015-10-29 12:13
Weird, I think this should work. The only difference that I see compared to my import is that I have an extra column 'image', but I don't think this can be the problem.

![schermafbeelding 2015-10-29 om 13 12 54](https://cloud.githubusercontent.com/assets/1763934/10818067/db9a18dc-7e3e-11e5-9f0c-e7798886e86e.png)

**Comment by minikist** [comment] 2015-10-29 12:20
I test it, but that make no sense. 
Is there a way to debug or is there already a log for the importer?

I tried also with the url, but that's not working too.

**Comment by minikist** [comment] 2015-10-29 15:38
Do you know which version you have from magento 2 (github version)?? 

the images weren't moved to the dir pub/media/catalog/product after importing? that's weird i gues.

Thanks

**Comment by minikist** [comment] 2015-10-31 12:36
Sorry, i have fixed the problem. the base url was install dir/pub and should be install dir/ 
So this worked with images and i think it could be closed.

But i test a lot with the csv and 1 product and that worked. But now i create a file with +5000 products and get this error "URL key for specified store already exists" #1471 

So Thanks @SLv99 for the help and maybe you can help me also with this?

**Comment by SLv99** [comment] 2015-10-31 18:39
Good to hear that it's working now.

I received the same error. I think the problem is in the url_rewrite database table. The URL key refers to the requested path that's already in the table. I think Magento does not properly update this value if it already exists. What I did is truncate the url_rewrite table. After this the import did run fine. I recommend doing a database backup from Magento before the truncate. Also if the webshop already contains products, I don't recommend doing this. I deleted all products before the truncate and the new import.

**Comment by minikist** [comment] 2015-10-31 18:44
Thanks for the reply @SLv99,
I understand the way you do, but that's not possible for me. I need to added 4 csv files. 
I'm debugging now some objects to files, i hope that give me more information.

If someone have a fix let me know.

**Comment by minikist** [comment] 2015-10-31 20:12
I add a comment on the other thread. I hope someone has a fix or workaround for this issue.
But for now Thanks for your help @SLv99

**Comment by davidalger** [comment] 2015-11-10 20:16
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Closed by davidalger** 2015-11-10 20:16 UTC
Labels: forum
