### ISSUE TITLE
after contact form submitted, success message wont show on magento 2.4.6

### ISSUE THREAD

**Issue by heneral** [magento/magento2#38288] opened 2023-12-14 21:47 UTC
### Summary

after contact form submitted, success message wont show on magento 2.4.6
please need guidance

### Examples

after contact form submitted, success message wont show on magento 2.4.6

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-12-15 05:03
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-12-15 05:20
Hi @heneral,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached screenshots.


![Screenshot from 2023-12-15 10-48-25](https://github.com/magento/magento2/assets/51680745/ce637539-5db1-4744-a0f1-e4bdc7871a93)


We are getting Success message after submitting contact-us form.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-12-29 05:00
Hi @heneral,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38288#issuecomment-1857294940  still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-01-05 05:10
Hi @heneral,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-01-05 05:10 UTC
Labels: Issue: needs update, Reported on 2.4.6
