### ISSUE TITLE
There is no webapi resource for newsletter registration

### ISSUE THREAD

**Issue by degaray** [magento/magento2#8027] opened 2017-01-04 10:43 UTC
### Preconditions
As of Magento 2.1 there is no endpoint in the webapi to subscribe to the newsletter.

### Expected result
1. There should be a post method to subscribe an email to the newsletter.

**Comment by misha-kotov** [comment] 2017-01-27 19:45
Hi @degaray , 
you can currently subscribe/unsubscribe customers to the newsletter via the Customer resource. You PUT something like the following, specifying the `extension_attribute` `is_subscribed`: 
```
{"customer": 
  {
    "id": 2,
    "group_id": 1,
    "default_billing": "0",
    "default_shipping": "0",
    "created_at": "2017-01-10 16:32:32",
    "updated_at": "2017-01-27 15:27:33",
    "created_in": "Default Store View",
    "email": "customer@example.com",
    "firstname": "FirstName",
    "lastname": "LastName",
    "store_id": 1,
    "website_id": 1,
    "addresses": [],
    "disable_auto_group_change": 0,
    "extension_attributes": {
      "is_subscribed": true
    }
  }
}
```

There's an issue currently reading this extension attribute on GET. The problem is that the plugin for the Customer module does not express how to populate this newsletter extension attribute data on a GET of a customer resource, hence it's missing from the response. The missing function needs to be defined here: 
`<magento dir>/app/code/Magento/Newsletter/Model/Plugin/CustomerPlugin.php`

**Comment by piotrekkaminski** [comment] 2017-02-10 17:17
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/There-is-no-webapi-resource-for-newsletter-registration/idi-p/60558).

**Closed as completed by piotrekkaminski** 2017-02-10 17:17 UTC
Labels: improvement
