### ISSUE TITLE
Set tier prices greater than base price

### ISSUE THREAD

**Issue by bikash-webo** [magento/magento2#33887] opened 2021-08-23 11:06 UTC
### Summary (*)

Currently the base price overrides the tier price if the tier price is greater than base price. How can we override this feature?
Magento: 2.4.1

### Examples (*)

Steps to reproduce:
1. Set base price of any product to 20.
2. Set price of any tier group to 25.
3. Price on website to that tier group shows 20.
4. Expected result: 25. Output: 20

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment] 2021-08-24 05:45
Hi @bikash-webo 
Please update the issue description with **Preconditions**, **Steps to reproduce**, **Expected** result, **Actual** result. So that we can verify your issue.
Thank you.

**Comment by bikash-webo** [comment] 2021-08-24 05:52
> Hi @bikash-webo
> Please update the issue description with **Preconditions**, **Steps to reproduce**, **Expected** result, **Actual** result. So that we can verify your issue.
> Thank you.

**Comment by engcom-Echo** [comment] 2021-08-24 09:16
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment] 2021-08-24 12:19
Hi @bikash-webo 
According to magento documentation **Tier pricing** lets you offer a **quantity discount** from a product listing or product page in the storefront. So when base price is given to be lower than the tier prices that you have set (which are expected to be discounts & hence lower than base price), it will pick up the lowest price at front end. This is the expected behaviour that magento will show the minimum price, because the retail price should always be higher than the group prices. This is also evident from the following code,
```
    /**
     * Apply tier price for product if not return price that was before
     *
     * @param   Product $product
     * @param   float $qty
     * @param   float $finalPrice
     * @return  float
     */
    protected function _applyTierPrice($product, $qty, $finalPrice)
    {
        if ($qty === null) {
            return $finalPrice;
        }

        $tierPrice = $product->getTierPrice($qty);
        if (is_numeric($tierPrice)) {
            $finalPrice = min($finalPrice, (float) $tierPrice);
        }
        return $finalPrice;
    }
```
Accordingly this is not an issue & its an expected behaviour. If you still face any issues regarding tier pricing in line with magento expected behaviour, please feel free to write back to us with prerequisites, steps to reproduce, expected & actual results.
Thank you

**Comment by bikash-webo** [comment] 2021-08-24 16:40
If we want to modify this feature. what should we do?

**Comment by engcom-Echo** [comment] 2021-08-25 04:44
Hi @bikash-webo ,
Unfortunately I cannot help you with a solution to modify this feature, May be I can suggest you to develop a custom extension to override this feature, without modifying the core code. You could take up suggestions from our public forums.
As this is an Issue confirmation & triage board & this ticket, that you have opened is **not an issue** & is an expected behaviour of magento, unfortunately I will have to close this ticket.
If you find any new issues in magento you can always open a new ticket for the same.
Thank you!

**Closed as completed by engcom-Echo** 2021-08-25 04:44 UTC
Labels: non-issue, Triage: Dev.Experience
