### ISSUE TITLE
Can't add product

### ISSUE THREAD

**Issue by shikata-ga-nai** [magento/magento2#1725] opened 2015-08-21 19:29 UTC
Master branch, Apache 2.4.7, 1.0.0-beta
I'm trying to add new product but it just hangs on Please wait loader. Waited 10 minutes - nothing. 
in debug log
```
[2015-08-21 18:17:27] main.DEBUG: cache_invalidate {"method":"POST","url":"http://*URL*/admin/catalog/product/new/set/4/type/simple/key/*KEY*/","invalidateInfo":{"tags":["BACKEND_MAINMENU"],"mode":"matchingAnyTag"},"is_exception":false} []
[2015-08-21 19:11:30] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["EAV"],"mode":"matchingAnyTag"},"is_exception":false} [] 
[2015-08-21 19:11:32] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["EAV","EAV_ATTRIBUTE"],"mode":"matchingAnyTag"},"is_exception":false} []
[2015-08-21 19:11:32] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["EAV_ATTRIBUTE"],"mode":"matchingAnyTag"},"is_exception":false} []
[2015-08-21 19:11:33] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["EAV","EAV_ATTRIBUTE"],"mode":"matchingAnyTag"},"is_exception":false} []
[2015-08-21 19:11:33] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["EAV_ATTRIBUTE"],"mode":"matchingAnyTag"},"is_exception":false} []
[2015-08-21 19:11:34] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["cms_page"],"mode":"matchingAnyTag"},"is_exception":false} []
[2015-08-21 19:11:34] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["cms_page"],"mode":"matchingAnyTag"},"is_exception":false} []
[2015-08-21 19:11:34] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["cms_page"],"mode":"matchingAnyTag"},"is_exception":false} []
[2015-08-21 19:11:34] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["cms_page"],"mode":"matchingAnyTag"},"is_exception":false} []
[2015-08-21 19:11:34] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["EAV"],"mode":"matchingAnyTag"},"is_exception":false} []
[2015-08-21 19:11:46] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["catalog_category"],"mode":"matchingAnyTag"},"is_exception":false} []
[2015-08-21 19:11:50] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["catalog_category"],"mode":"matchingAnyTag"},"is_exception":false} []
[2015-08-21 19:11:51] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["BACKEND_MAINMENU"],"mode":"matchingTag"},"is_exception":false} []
[2015-08-21 19:11:51] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["EAV"],"mode":"matchingAnyTag"},"is_exception":false} []
[2015-08-21 19:11:52] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["cms_page"],"mode":"matchingAnyTag"},"is_exception":false} []
[2015-08-21 19:12:04] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["EAV","EAV_ATTRIBUTE"],"mode":"matchingAnyTag"},"is_exception":false} []
[2015-08-21 19:12:04] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["EAV_ATTRIBUTE"],"mode":"matchingAnyTag"},"is_exception":false} []
[2015-08-21 19:12:11] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["EAV","EAV_ATTRIBUTE"],"mode":"matchingAnyTag"},"is_exception":false} []
[2015-08-21 19:12:11] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["EAV_ATTRIBUTE"],"mode":"matchingAnyTag"},"is_exception":false} []
[2015-08-21 19:12:14] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["CONFIG"],"mode":"matchingTag"},"is_exception":false} []
[2015-08-21 19:12:14] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["LAYOUT_GENERAL_CACHE_TAG"],"mode":"matchingTag"},"is_exception":false} []
[2015-08-21 19:12:14] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["BLOCK_HTML"],"mode":"matchingTag"},"is_exception":false} []
[2015-08-21 19:12:14] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["VIEW_FILES_FALLBACK"],"mode":"matchingTag"},"is_exception":false} []
[2015-08-21 19:12:14] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["VIEW_FILES_PREPROCESSING"],"mode":"matchingTag"},"is_exception":false} []
[2015-08-21 19:12:14] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["COLLECTION_DATA"],"mode":"matchingTag"},"is_exception":false} []
[2015-08-21 19:12:14] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["DB_DDL"],"mode":"matchingTag"},"is_exception":false} []
[2015-08-21 19:12:14] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["EAV"],"mode":"matchingTag"},"is_exception":false} []
[2015-08-21 19:12:14] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["FPC"],"mode":"matchingTag"},"is_exception":false} []
[2015-08-21 19:12:14] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["TRANSLATE"],"mode":"matchingTag"},"is_exception":false} []
[2015-08-21 19:12:14] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["INTEGRATION"],"mode":"matchingTag"},"is_exception":false} []
[2015-08-21 19:12:14] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["INTEGRATION_API_CONFIG"],"mode":"matchingTag"},"is_exception":false} []
[2015-08-21 19:12:14] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["WEBSERVICE"],"mode":"matchingTag"},"is_exception":false} []
[2015-08-21 19:12:20] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http://url/?SID=f5r93ju2lptp09n1ed45u5n0o4","invalidateInfo":{"tags":["interception","CONFIG"],"mode":"matchingTag"},"is_exception":false} []
[2015-08-21 19:12:20] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http://url/?SID=sf59ulele7q610v2u1ql9vltm2","invalidateInfo":{"tags":["interception","CONFIG"],"mode":"matchingTag"},"is_exception":false} []
```

in system.log:

```
[2015-08-21 19:12:24] main.CRITICAL: Broken reference: the 'page.bottom' element cannot be added as child to 'page.bottom.container', because the latter doesn't exist [] []
[2015-08-21 19:12:24] main.CRITICAL: Broken reference: the 'page.bottom' element cannot be added as child to 'page.bottom.container', because the latter doesn't exist [] []
[2015-08-21 19:12:24] main.CRITICAL: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-08-21 19:12:24] main.CRITICAL: Broken reference: the 'minicart.subtotal.msrp' element cannot be added as child to 'minicart.subtotal.container', because the latter doesn't exist [] []
[2015-08-21 19:12:24] main.CRITICAL: Broken reference: the 'minicart.subtotal.msrp' tries to reorder itself towards 'minicart.subtotal', but their parents are different: 'minicart.subtotal.container' and '' respectively. [] []
[2015-08-21 19:12:24] main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-08-21 19:12:24] main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-08-21 19:12:24] main.CRITICAL: Broken reference: the 'store.settings.currency' tries to reorder itself towards 'store_language', but their parents are different: 'store.settings' and 'header.panel' respectively. [] []
[2015-08-21 19:12:24] main.CRITICAL: Broken reference: the 'paypal.partner.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-08-21 19:12:24] main.CRITICAL: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-08-21 19:12:24] main.CRITICAL: Broken reference: the 'minicart.subtotal.msrp' element cannot be added as child to 'minicart.subtotal.container', because the latter doesn't exist [] []
[2015-08-21 19:12:24] main.CRITICAL: Broken reference: the 'minicart.subtotal.msrp' tries to reorder itself towards 'minicart.subtotal', but their parents are different: 'minicart.subtotal.container' and '' respectively. [] []
[2015-08-21 19:12:24] main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-08-21 19:12:24] main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-08-21 19:12:24] main.CRITICAL: Broken reference: the 'store.settings.currency' tries to reorder itself towards 'store_language', but their parents are different: 'store.settings' and 'header.panel' respectively. [] []
[2015-08-21 19:12:24] main.CRITICAL: Broken reference: the 'paypal.partner.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-08-21 19:12:24] main.CRITICAL: Broken reference: the 'bml.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-08-21 19:12:24] main.CRITICAL: Broken reference: the 'bml.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-08-21 19:12:24] main.CRITICAL: Directory "/var/www/html/pub/static/_requirejs/frontend/Magento/blank/en_US" cannot be created Warning!mkdir(): File exists [] []
[2015-08-21 19:12:24] main.CRITICAL: Block requirejs-config throws exception and cannot be rendered. [] []
[2015-08-21 19:12:33] main.CRITICAL: Broken reference: the 'page.bottom' element cannot be added as child to 'page.bottom.container', because the latter doesn't exist [] []
[2015-08-21 19:12:33] main.CRITICAL: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-08-21 19:12:33] main.CRITICAL: Broken reference: the 'minicart.subtotal.msrp' element cannot be added as child to 'minicart.subtotal.container', because the latter doesn't exist [] []
[2015-08-21 19:12:33] main.CRITICAL: Broken reference: the 'minicart.subtotal.msrp' tries to reorder itself towards 'minicart.subtotal', but their parents are different: 'minicart.subtotal.container' and '' respectively. [] []
[2015-08-21 19:12:33] main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-08-21 19:12:33] main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-08-21 19:12:33] main.CRITICAL: Broken reference: the 'store.settings.currency' tries to reorder itself towards 'store_language', but their parents are different: 'store.settings' and 'header.panel' respectively. [] []
[2015-08-21 19:12:33] main.CRITICAL: Broken reference: the 'paypal.partner.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-08-21 19:12:33] main.CRITICAL: Broken reference: the 'bml.right.logo' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2015-08-21 19:13:05] main.INFO: Item Magento_Backend::system_currency was removed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Theme::system_design_theme was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Backend::system_design_schedule was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Backend::system_store was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Backend::dashboard was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Backend::system was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Backend::system_tools was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Backend::system_design was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Backend::system_convert was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Backend::system_cache was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Backend::marketing was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Backend::marketing_communications was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Backend::marketing_seo was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Backend::marketing_user_content was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Backend::content was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Backend::content_elements was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Backend::stores was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Backend::stores_settings was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Backend::stores_attributes was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Backend::other_settings was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Backend::system_other_settings was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Backend::setup_wizard was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Backup::system_tools_backup was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Customer::customer was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Customer::customer_manage was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Customer::customer_group was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Indexer::system_index was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Cms::cms_page was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Cms::cms_block was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Catalog::catalog was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Catalog::catalog_products was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Catalog::catalog_categories was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Catalog::catalog_attributes_attributes was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Catalog::catalog_attributes_sets was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Catalog::inventory was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Search::search_terms was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Widget::cms_widget_instance was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_CheckoutAgreements::sales_checkoutagreement was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Config::system_config was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_CurrencySymbol::system_currency was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_CurrencySymbol::system_currency_rates was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_CurrencySymbol::system_currency_symbols was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Downloadable::report_products_downloads was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Email::template was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Sales::sales was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Sales::sales_operation was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Sales::sales_order was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Sales::sales_invoice was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Sales::sales_shipment was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Sales::sales_creditmemo was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Sales::sales_transactions was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Sales::system_order_statuses was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_ImportExport::system_convert_import was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_ImportExport::system_convert_export was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_ImportExport::system_convert_history was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_User::system_acl was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_User::system_acl_users was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_User::system_acl_roles was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Log::visitor_online was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Newsletter::newsletter_template was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Newsletter::newsletter_queue was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Newsletter::newsletter_subscriber was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Newsletter::newsletter_problem was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_SalesRule::promo_quote was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Paypal::report_salesroot_paypal_settlement_reports was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Paypal::paypal_billing_agreement was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Reports::report was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Reports::report_marketing was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Reports::report_salesroot was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Reports::report_salesroot_sales was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Reports::report_salesroot_tax was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Reports::report_salesroot_invoiced was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Reports::report_salesroot_shipping was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Reports::report_salesroot_refunded was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Reports::report_salesroot_coupons was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Reports::report_shopcart_product was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Reports::report_shopcart_abandoned was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Reports::report_products was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Reports::report_products_bestsellers was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Reports::report_products_sold was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Reports::report_products_viewed was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Reports::report_products_lowstock was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Reports::report_customers was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Reports::report_customers_accounts was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Reports::report_customers_totals was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Reports::report_customers_orders was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Reports::report_statistics was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Reports::report_statistics_refresh was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Search::report_search_term was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Review::catalog_reviews_ratings_ratings was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Review::catalog_reviews_ratings_reviews_all was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Review::report_review was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Review::report_review_customer was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Review::report_review_product was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_CatalogRule::promo was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_CatalogRule::promo_catalog was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Sitemap::catalog_sitemap was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_AdminNotification::system_adminnotification was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Tax::sales_tax was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Tax::sales_tax_rules was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Tax::sales_tax_rates was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_TaxImportExport::system_convert_tax was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_UrlRewrite::urlrewrite was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Integration::system_extensions was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Integration::system_integrations was processed [] []
[2015-08-21 19:13:05] main.INFO: Add of item with id Magento_Variable::system_variable was processed [] []
[2015-08-21 19:13:13] main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2015-08-21 19:13:13] main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2015-08-21 19:13:13] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []
[2015-08-21 19:13:15] main.CRITICAL: Invalid template file: '' [] []
[2015-08-21 19:13:19] main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2015-08-21 19:13:19] main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2015-08-21 19:13:19] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []
[2015-08-21 19:13:20] main.CRITICAL: Invalid template file: '' [] []
[2015-08-21 19:13:30] main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2015-08-21 19:13:30] main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2015-08-21 19:13:30] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []
[2015-08-21 19:13:31] main.CRITICAL: Invalid template file: '' [] []
[2015-08-21 19:13:32] main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2015-08-21 19:13:32] main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2015-08-21 19:13:32] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []
[2015-08-21 19:13:32] main.CRITICAL: Invalid template file: '' [] []
[2015-08-21 19:13:36] main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2015-08-21 19:13:36] main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2015-08-21 19:13:36] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []
[2015-08-21 19:13:37] main.CRITICAL: Invalid template file: '' [] []
[2015-08-21 19:13:38] main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2015-08-21 19:13:38] main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2015-08-21 19:13:38] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []
[2015-08-21 19:13:38] main.CRITICAL: Invalid template file: '' [] []
[2015-08-21 19:13:43] main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2015-08-21 19:13:43] main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2015-08-21 19:13:43] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []
[2015-08-21 19:13:44] main.CRITICAL: Invalid template file: '' [] []
[2015-08-21 19:13:46] main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2015-08-21 19:13:46] main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2015-08-21 19:13:46] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []
[2015-08-21 19:13:46] main.CRITICAL: Invalid template file: '' [] []
[2015-08-21 19:13:48] main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2015-08-21 19:13:48] main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2015-08-21 19:13:48] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []
[2015-08-21 19:13:49] main.CRITICAL: Invalid template file: '' [] []
```

Tried to reindex, flush storage - no effect.

**Comment by mazhalai** [comment] 2015-08-24 15:44
@shikata-ga-nai can you please give more details? Did you try to add a product from the admin page?

**Comment by shikata-ga-nai** [comment] 2015-08-24 20:10
@mazhalai yes, from admin page. Entered data, clicked Save and the preloader just keeps spinning.

**Comment by mazhalai** [comment] 2015-08-31 14:04
@shikata-ga-nai thank you for your report. We have created ticket MAGETWO-42232 to track a  fix for this.

**Comment by mazhalai** [comment] 2015-09-23 13:12
@shikata-ga-nai can you please check your apache logs and see if there are any errors in that?

**Comment by shikata-ga-nai** [comment] 2015-09-23 13:18
@mazhalai unfortunately, I removed beta and installed v. 1.9

**Comment by piotrekkaminski** [comment] 2015-10-03 18:46
..It might be caused by too small value of max_execution_time (or too slow system) so static resources generation fails with messages "Fatal error: Maximum execution time of XXX exceeded". It can be found in apache's error_log.

Please reopen if this does not help.

**Closed by piotrekkaminski** 2015-10-03 18:46 UTC
Labels: acknowledged, bug, MX
