### ISSUE TITLE
Unable to properly delete product attribute which input is file type

### ISSUE THREAD

**Issue by ngtuan96lc** [magento/magento2#34161] opened 2021-09-26 05:01 UTC
### Preconditions (*)

1. Magento version 2.3.0 Enterprise Edition
2. PHP 7.3.28
3. Mysql 8.0.26-0ubuntu0.20.04.2

### Steps to reproduce (*)

1. Create 2 product attributes which input is **file** type

>         $eavSetup = $this->_eavSetupFactory->create(["setup"=>$setup]);
>         $eavSetup->addAttribute(
>             \Magento\Catalog\Model\Product::ENTITY,
>             'uploadfile_1',
>             [
>                 'group' => 'Product Details',
>                 'type' => 'varchar',
>                 'label' => 'Energy File',
>                 'input' => 'file',
>                 'backend' => 'MyModule\CatalogWidget\Model\Attribute\Product\Pdf',
>                 'frontend' => '',
>                 'class' => '',
>                 'source' => '',
>                 'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_WEBSITE,
>                 'visible' => true,
>                 'required' => false,
>                 'user_defined' => true,
>                 'default' => '',
>                 'searchable' => false,
>                 'filterable' => false,
>                 'comparable' => false,
>                 'visible_on_front' => false,
>                 'unique' => false,
>                 'apply_to' => '',
>                 'used_in_product_listing' => true
>             ]
>         );

2. Go to Edit a product
3. At scope All Store Views, fill value for attributes and save.
4. Switch to specify Storeview, uncheck use default value, fill new value and save.
5. Still at scope Storeview, delete the value of each attribute.
 - tick on checkbox delete the value of the first attribute -> save
 - tick on checkbox delete the value of the second attribute -> save

I videoed a clip, please see it to get more information. 
Please refer to video: https://drive.google.com/file/d/1bKfDkpwT_pLnH05K_hJnrwFAinB0UkZO/view?usp=sharing
Please refer to my module: https://drive.google.com/file/d/1RUV1dDHOOP-cKlW9DSOViTrP1LbdHidv/view?usp=sharing

### Expected result (*)

1. Delete successfully
2. After save, checkbox Use default value is not checked automatically.
3. Not apply the use default value

### Actual result (*)

1. Delete not successfully 
2. Checkbox Use default value is checked automatically
3. Apply the use default value automatically

**Severity: S0**

**Comment by vladyslav-sikailo-decima** [comment] 2021-09-29 13:24
@magento give me 2.3 instance

**Comment by engcom-Hotel** [comment] 2021-12-08 14:44
Hi @ngtuan96lc,

Thank you for reporting the issue with a proper video description and details.

I have tested the functionality with your custom module but I think it could be happening due to the custom functionality which you have added. As far as I can understand you are overriding the default functionality and the issue is not related to Magento core implementation.

Similar questions can be raised on various Magento Forums like Magento Community(https://community.magento.com/) or Magento Stack Exchange(https://magento.stackexchange.com/) also and you might get the required help there.

If you think the issue is related to the Magento core code, please update the description with relevant details so that we can check further, or otherwise we’ll have to close this issue here.

Thanks

**Comment by engcom-Hotel** [comment] 2021-12-23 10:48
Dear @ngtuan96lc,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2021-12-23 10:48 UTC
Labels: Triage: Dev.Experience, Issue: needs update
