### ISSUE TITLE
Customers created using api cannot login, nor reset password

### ISSUE THREAD

**Issue by degaray** [magento/magento2#2351] opened 2015-11-13 03:47 UTC
If I try to create a user on API endpoint [POST] `/customers` then I cannot login using [POST] `/integration/customer/token`

```javascript
{
  "customer": {
    "groupId": 0,
    "email": "some@password.com",
    "firstname": "Peter",
    "lastname": "Lopez",
    "storeId": 0,
    "websiteId": 0
  },
  "password": "yeahyeah"
}
```

**Comment by slavvka** [comment] 2015-11-13 09:59
Hi @degaray. That is not a bug since you don't specify valid website ans store IDs. It is a achived behaviour. Please recheck it with correct IDs and close the issue.

**Comment by slavvka** [comment] 2015-11-13 10:10
And creating a customer with Group ID 0 (NOT LOGGED IN) is also not a good idea.

**Comment by degaray** [comment] 2015-11-13 12:12
Shouldn't it throw an error? I create it correctly. I have checked it in the admin backend. However. I think that if the store is not set or set to zero it should then throw an exception.

**Comment by slavvka** [comment] 2015-11-13 12:34
You can create it because 0 for website and store means backend, it is not a bug. And impossibility to login for such customer is the expected behavior.

**Comment by degaray** [comment] 2015-11-13 12:44
Oh you are right. Now I understand so many things. Hey do you guys have a "happy path" sample of calls to the api in order to buy a product? That will be of great help. I am trying to create a real mobile app using the api but having to understand a hundred and so endpoints is really time consuming. By the way which is your most stable branch: master or merchant beta?

**Comment by slavvka** [comment] 2015-11-13 12:56
Master is more stable version. 
All the documentations you can find at http://devdocs.magento.com/guides/v2.0/rest/bk-rest.html

**Comment by slavvka** [comment] 2015-11-13 13:17
If you don't have any questions, please close the issue.

**Closed** 2015-11-13 13:30 UTC
Labels: CS, question, reject

**Comment by Jen143** [comment] 2017-03-01 06:42
Hi slavvka,
I have encountered same issue. I have set the group_id = 1 and website_id = 1 but still when i tried to login to the store. It says Invalid Login or Password. When I tried to reset the password in the admin page, i can login.
