### ISSUE TITLE
skip_gallery_before/after incorrect block ordering

### ISSUE THREAD

**Issue by MichaelThessel** [magento/magento2#27216] opened 2020-03-09 20:20 UTC
### Preconditions (*)

1.  Magento 2.4
Also reproduced on 2.3.4

### Steps to reproduce (*)

1.Create some product
2. Visit product page
3. View system.log

### Expected result (*)

No messages in system.log

### Actual result (*)

System log shows error:

```
[2020-03-09 20:06:24] main.INFO: Broken reference: the 'skip_gallery_before' tries to reorder itself towards 'product.info.media.image', but their parents are different: 'skip_gallery_before.wrapper' and 'product.info.media' respectively. [] []
[2020-03-09 20:06:24] main.INFO: Broken reference: the 'skip_gallery_after' tries to reorder itself towards 'product.info.media.image', but their parents are different: 'skip_gallery_after.wrapper' and 'product.info.media' respectively. [] []
```

The reason for that can be found in: (on Magento 2.3.4)
`vendor/magento/module-catalog/view/frontend/layout/catalog_product_view.xml`

As you can see there on line 121 and 135 the before and after attributes refer to elements that are not on the same level. 

This patch fixes the problem:
```
diff -u /tmp/catalog_product_view.xml vendor/magento/module-catalog/view/frontend/layout/catalog_product_view.xml                                                                                                                                                                                        
--- /tmp/catalog_product_view.xml       2020-03-09 13:13:42.931370664 -0700
+++ vendor/magento/module-catalog/view/frontend/layout/catalog_product_view.xml 2020-03-09 13:14:39.252674374 -0700
@@ -117,8 +117,8 @@
                         <argument name="target_id" xsi:type="string">gallery-prev-area</argument>
                     </arguments>
                 </block>
-                <container name="skip_gallery_before.wrapper" htmlTag="div" htmlClass="action-skip-wrapper">
-                    <block class="Magento\Framework\View\Element\Template" before="product.info.media.image" name="skip_gallery_before" template="Magento_Theme::html/skip.phtml">
+                <container name="skip_gallery_before.wrapper" htmlTag="div" htmlClass="action-skip-wrapper" before="product.info.media.image">
+                    <block class="Magento\Framework\View\Element\Template" name="skip_gallery_before" template="Magento_Theme::html/skip.phtml">
                         <arguments>
                             <argument name="target" xsi:type="string">gallery-next-area</argument>
                             <argument name="label" translate="true" xsi:type="string">Skip to the end of the images gallery</argument>
@@ -131,8 +131,8 @@
                         <argument name="imageHelper" xsi:type="object">Magento\Catalog\Helper\Image</argument>
                     </arguments>
                 </block>
-                <container name="skip_gallery_after.wrapper" htmlTag="div" htmlClass="action-skip-wrapper">
-                    <block class="Magento\Framework\View\Element\Template" after="product.info.media.image" name="skip_gallery_after" template="Magento_Theme::html/skip.phtml">
+                <container name="skip_gallery_after.wrapper" htmlTag="div" htmlClass="action-skip-wrapper" after="product.info.media.image">
+                    <block class="Magento\Framework\View\Element\Template" name="skip_gallery_after" template="Magento_Theme::html/skip.phtml">
                         <arguments>
                             <argument name="target" xsi:type="string">gallery-prev-area</argument>
                             <argument name="label" translate="true" xsi:type="string">Skip to the beginning of the images gallery</argument>
```

I would have submitted a pull request but there is no repo for the core modules?

**Comment by MichaelThessel** [comment] 2020-03-09 20:50
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-09 20:50
Hi @MichaelThessel. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-03-09 20:50
Hi @MichaelThessel, here is your [Magento instance](https://i-27216-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27216-2-4-develop.instances.magento-community.engineering/admin_147b](https://i-27216-2-4-develop.instances.magento-community.engineering/admin_147b)
Login: `60ac4fb7` Password: `5b54aabba334`
Instance will be terminated in up to 3 hours.

**Comment by MichaelThessel** [comment] 2020-03-09 20:52
No ssh for dev instance, cannot check the logs without SSH.

**Comment by magento-engcom-team** [comment] 2020-07-17 20:53
:white_check_mark: Confirmed by @engcom-Lima 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35995` were created

**Issue Available**: @engcom-Lima, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2021-02-12 07:42
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by magento-engcom-team** [comment] 2021-04-07 08:56
:white_check_mark: Confirmed by @ihor-sviziev 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35995` were created

**Issue Available**: @ihor-sviziev, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Delta** [comment] 2024-06-10 05:26
Hi @MichaelThessel ,

Verified the issue on 2.4-develop and it is reproducible.

Hence confirming this issue.

Steps to reproduce:-

1. Create some product
2. Visit product page
3. View system.log

created product

<img width="1440" alt="Screenshot 2024-06-10 at 10 48 40 AM" src="https://github.com/magento/magento2/assets/51681379/329a9da3-0577-4542-9d77-278c7280bf4d">

visit to product page

<img width="1440" alt="Screenshot 2024-06-10 at 10 48 06 AM" src="https://github.com/magento/magento2/assets/51681379/9f32c18c-b310-4ca5-b83a-43e1e7954610">

system log

<img width="939" alt="Screenshot 2024-06-10 at 10 52 45 AM" src="https://github.com/magento/magento2/assets/51681379/06b8027b-a663-4beb-bc28-d34ef783e54b">

**Comment by engcom-Delta** [comment] 2024-06-10 05:37
Hi @magentopits ,

Thanks for your reporting and collaboration.

We have verified the issue on 2.4-develop instance and the issue is no more reproducible.Kindly refer the attached screenshots.

Steps to reproduce (*)

1. Create some product
2. Visit product page
3. View system.log


<img width="1440" alt="Screenshot 2024-06-10 at 10 48 40 AM" src="https://github.com/magento/magento2/assets/51681379/92e78f17-c8dc-404a-88d7-3bf8e0ac2c87">

<img width="1440" alt="Screenshot 2024-06-10 at 10 48 06 AM" src="https://github.com/magento/magento2/assets/51681379/6f1094ef-d1b9-4621-96a6-642c051837c0">

<img width="691" alt="Screenshot 2024-06-10 at 11 03 04 AM" src="https://github.com/magento/magento2/assets/51681379/2ad1b9da-4e62-4cae-bda3-29063bbf846b">

Hence closing the issue.

**Closed as completed by engcom-Delta** 2024-06-10 05:37 UTC
Labels: Priority: P3, Severity: S3, Triage: Ready for Triage, Progress: done, Reported on 2.3.4
