### ISSUE TITLE
Special price active when special_to_date has already passed

### ISSUE THREAD

**Issue by joachimVT** [magento/magento2#36656] opened 2022-12-21 11:00 UTC
### Preconditions and environment

- Magento version 2.4.3-p3

### Steps to reproduce

1. Create a product with a price of 100 and a special price of 50 trough the API
2. Set a special from date in the past 1-12-2022
3. Set a special_to_date 1 day before current day with time of 12:00 example: 2022-12-20 12:00:00
4. Create the product trough the REST API, because you can't set the time of a special_to_date in the backoffice

`
{
    "product": {
        "attribute_set_id": 19,
        "custom_attributes": [
            {
                "attribute_code": "special_price",
                "value": "15.000"
            },
            {
                "attribute_code": "special_from_date",
                "value": "2022-12-01 00:00:00"
            },
            {
                "attribute_code": "special_to_date",
                "value": "2022-12-20 12:00:00"
            }
        ],
        "name": "Test article",
        "price": 100,
        "sku": "28500",
        "status": 1,
        "tier_prices": [],
        "visibility": 4
    },
    "sku": "28500"
}
`

### Expected result

Final price has no discount (special price) and should be 100€ because special to date is a date in the past.

### Actual result

Special price is displayed as final price and discount is displayed, price is 15€.

### Additional information

Its important to set a special price end date 1 day before the current date, and with a time different than 00:00:00.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-12-21 11:03
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-12-21 14:10
Hi @joachimVT,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


We are not able to create a product with special price with given API request.


<img width="862" alt="Screenshot 2022-12-21 at 6 04 38 PM" src="https://user-images.githubusercontent.com/51680745/208923607-ed5d5559-7a82-4d9e-a8d4-aedf84eade62.png">



For creating a product with special prices. Prices field is required.


<img width="1479" alt="Screenshot 2022-12-21 at 7 15 57 PM" src="https://user-images.githubusercontent.com/51680745/208923717-c7904e23-0851-4a3b-a52e-ad537489b73a.png">



Kindly provide more information it is helpful for us to proceed further.


Thanks.

**Comment by joachimVT** [comment] 2022-12-21 20:25
Yeah well my call was from the update product endpoint. But the same result applies for:
POST https://app.m2.test/rest/V1/products/special-price

```
{
    "prices": [
        {
            "store_id": 0,
            "price_from": "2022-12-01 00:00:00",
            "price_to": "2022-12-21 12:00:00",
            "price": 15,
            "sku": "28500"
        }
    ]
}
```

**Comment by engcom-Bravo** [comment] 2022-12-29 05:22
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-12-29 12:35
Hi @joachimVT.

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

We have updated product special price with below API and we have set a Timezone for special price.


<img width="889" alt="Screenshot 2022-12-29 at 2 32 00 PM" src="https://user-images.githubusercontent.com/51680745/209951509-f69e7f2d-889b-450c-8e5a-61e6de7c3c3d.png">


After completion of Timezone the product has no special price.


<img width="1097" alt="Screenshot 2022-12-29 at 2 32 08 PM" src="https://user-images.githubusercontent.com/51680745/209951803-5f3432f1-61db-4d92-8131-1d3ae6575c1c.png">



Kindly let us know we miss anything.


Thanks.
.

**Comment by engcom-Bravo** [comment] 2023-01-10 06:09
Hi @joachimVT,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-01-10 06:11
Hi @joachimVT,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-01-10 06:11 UTC
Labels: Issue: needs update, Reported on 2.4.3-p3
