### ISSUE TITLE
Bug: «Uncaught ReferenceError: iterate is not defined» in mage/utils/template.js on line 176 (and my fix)

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2177] opened 2015-10-24 19:15 UTC
The problem line is: https://github.com/magento/magento2/blob/af32ac1da2b877ed444eed2fbd2f92bb31cefda5/lib/web/mage/utils/template.js#L176
My fix: https://mage2.pro/t/142

**Comment by guz-anton** [comment] 2015-10-26 17:49
Hm.. Interesting bug. I'll make an investigation. But how you got it? Was it an IE? IE9 in some mode?

**Comment by guz-anton** [comment] 2015-10-27 08:54
Internal issue MAGETWO-44645

**Comment by kumbas111** [comment] 2015-10-27 14:28
Please provide details how could you manage to get this error on recursion callback in underscore method

**Comment by kumbas111** [comment] 2015-11-04 12:36
We have tested this bug in various environments with different set of data on the most popular browsers(IE, Mozilla, Chrome) and this issue can't be reproduced; since you didn't provide us details, we close issue as won't fix.

**Comment by guz-anton** [comment] 2015-11-04 12:52
@dfediuk 
Sory, but your fix just declares function in another way. Nor current neither your solution should cause an error. Please pay attention to environment where this code was used.

**Closed by guz-anton** 2015-11-04 12:52 UTC
