### ISSUE TITLE
The front-end date-picker is not localized.

### ISSUE THREAD

**Issue by magentopits** [magento/magento2#26565] opened 2020-01-28 12:47 UTC
The front-end date-picker is not localized: days short names are all in default en_US. 
### Preconditions (*)
1. Magento 2.3.x & 2.4-develop
2. Date format used is "E, dd.mm.yy"
3. Create a store view ( German -  de ) 
4. From Stores > Settings > Configuration > General > General > Locale drop down , assign language ( German (Switzerland) )  to the created store . ( Scope : German from top left drop down )

### Steps to reproduce (*)
1. Run:
```
composer require community-engineering/language-de_de
php bin/magento setup:static-content:deploy de_DE
php bin/magento indexer:reindex
php bin/magento cache:clean
php bin/magento cache:flush
```
2. Admin > Settings > Configuration > Customer > Customer Configuration > "Show Date of Birth: Require"
3. Login and switch to German store (de) and edit your account and use the datepicker of the DOB field.

### Expected result (*)
Days ( Short name ) are translated to German ( Ex in de_DE store)

### Actual result (*)
Days ( Short name ) are in English.
![image](https://user-images.githubusercontent.com/51681618/73441622-f03f8100-435b-11ea-8f3c-394f13ec978e.png)

**Comment by magentopits** [comment] 2020-01-29 04:54
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2020-01-29 04:55
Hi @magentopits. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-29 04:55
Hi @magentopits, here is your [Magento instance](https://i-26565-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26565-2-4-develop.instances.magento-community.engineering/admin_9ff6](https://i-26565-2-4-develop.instances.magento-community.engineering/admin_9ff6)
Login: `e63bae5e` Password: `c2e324309205`
Instance will be terminated in up to 3 hours.

**Comment by magentopits** [comment] 2020-01-29 06:10
@magento give me 2.3-develop instance , with German language pack installed.

I tried to install **magento/language-de_de** via Extension Manager but its error .
![Screenshot_2020-01-29 Readiness Check](https://user-images.githubusercontent.com/45989748/73335492-91afcf80-4295-11ea-91a3-92658d054c73.png)

**Comment by magento-engcom-team** [comment] 2020-01-29 06:10
Hi @magentopits. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by engcom-Hotel** [comment] 2020-01-30 09:40
Hello @magentopits 
The GitHub issue tracker is intended for Magento Core technical issues only.
Your issue is related to 3rd party extension. 
Please refer to the `magento/language-de_de` support.

I have to close this issue.

Thanks for your report!

**Comment by magento-engcom-team** [comment] 2020-01-30 10:32
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30916` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magentopits** [comment] 2020-02-04 04:28
Any update on this issue ?

**Comment by pawankparmar** [comment] 2020-02-19 04:37
@engcom-Hotel, I have checked and found there is no translation available for short day name in CSV.

**Comment by webalvk** [comment] 2020-02-26 15:22
Hi i'm having the same issue, in magento 2.3.3 with locale set to pt_br, is there a fix yet?

**Comment by Alexie81** [comment] 2020-03-24 09:30
Very nice !!! 😊

**Comment by pankajparmar12** [comment] 2020-10-10 04:08
@magneto #dmcdindia2020

**Comment by magento-engcom-team** [comment] 2020-10-10 04:09
@pankajparmar12 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by pankajparmar12** [comment] 2020-10-10 04:10
@magento I'm working on it

**Comment by pankajparmar12** [comment] 2020-10-10 04:59
@magento #dmcdindia2020

**Comment by pankajparmar12** [comment] 2020-10-10 05:00
@magento I'm working on it

**Comment by chiranjeevi-cj** [comment] 2020-10-30 11:15
@magento I am working on this

**Comment by chiranjeevi-cj** [comment] 2020-11-02 08:21
@magento give me a 2.4-develop instance

**Comment by chiranjeevi-cj** [comment] 2020-11-02 08:23
@magento give me 2.4-develop instance

**Comment by chiranjeevi-cj** [comment] 2020-11-03 09:01
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment] 2024-05-31 15:58
Hi @magentopits  ,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the attached screenshots.

Preconditions (*)

1.Date format used is "E, dd.mm.yy"
2.Create a store view ( German - de )
3.From Stores > Settings > Configuration > General > General > Locale drop down , assign language ( German (Switzerland) 
   ) to the created store . ( Scope : German from top left drop down )

Steps to reproduce (*)

1.Run:
   composer require community-engineering/language-de_de
   php bin/magento setup:static-content:deploy de_DE
   php bin/magento indexer:reindex
   php bin/magento cache:clean
   php bin/magento cache:flush
2.Admin > Settings > Configuration > Customer > Customer Configuration > "Show Date of Birth: Require"
3.Login and switch to German store (de) and edit your account and use the datepicker of the DOB field.

Days ( Short name ) are translated to German ( Ex in de_DE store)


<img width="1432" alt="Screenshot 2024-05-30 at 7 03 46 PM" src="https://github.com/magento/magento2/assets/51681379/4a8361c5-dc73-4a1a-a536-b0824eec579d">


<img width="1413" alt="Screenshot 2024-05-31 at 9 26 41 PM" src="https://github.com/magento/magento2/assets/51681379/a517a817-d699-41c3-b2c1-1c485393b5bb">


<img width="1283" alt="Screenshot 2024-05-31 at 9 13 20 PM" src="https://github.com/magento/magento2/assets/51681379/662be4b6-0910-4bbf-8635-272d7b857f57">

Hence closing this issue.Please feel free to reopen to create a new issue if you still face this.

**Closed as completed by engcom-Delta** 2024-05-31 15:58 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Locale, Reproduced on 2.4.x, Priority: P2, Severity: S2, Triage: Done, Progress: done, Event: dmcdindia2020, Reported on 2.3.x
