### ISSUE TITLE
Translations with \n are not translatable

### ISSUE THREAD

**Issue by DanieliMi** [magento/magento2#38943] opened 2024-07-17 10:38 UTC
### Preconditions and environment

- 2.4.6-p6
- A store with language de_DE
- The following in the translation file for de_DE:
```csv
"Failed address validation:\n%1","Adressvalidierung fehlgeschlagen:\n%1"
```

### Steps to reproduce

1. Go to storefront
2. Add a product to the cart
3. Go to the checkout
4. Fill in form
5. Provide an incorrect email address (for example just a string)
6. Ignore/circumvent JS validation (this testcase assumes frontend validation fails/does not work and we have to rely on the backend validation)
7. Place order

### Expected result

You receive the translated message "Adressvalidierung fehlgeschlagen:..."

### Actual result

You receive the original message. "Failed address validation:...".

### Additional information

In https://github.com/magento/magento2/blob/1b99b6d59b27613ca70e60f4067743d715c3e02d/app/code/Magento/Quote/Model/SubmitQuoteValidator.php#L69C24-L69C56 `"\n"` is used but when the csv is read it equals to `'\n'` so the key cannot be found within `\Magento\Framework\Phrase\Renderer\Translate::render`.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2024-07-18 07:51
@magento please give me 2.4-develop instance

**Comment by engcom-Delta** [comment] 2024-07-19 12:11
Hi @DanieliMi ,

Thanks for your reporting and collaboration.
We have verified the issue in latest 2.4-develop instance, but we are unable to reproduce the issue. Kindly refer the screenshots.

Steps to reproduce.
1. Store with language de_DE
2. Go to storefront
3. Add an item to cart
4. Navigate to checkout
5. Disable email field validation by changing the validation.js and elements
    Email Address field
![image](https://github.com/user-attachments/assets/19e2ddc5-01aa-43b3-a436-e7658e6aeb6e)
validation.js
![image](https://github.com/user-attachments/assets/9b0bfe3d-6689-4efe-a06e-27a28806902a)
6. Enter string value in the email field
7. Fill Shipping information and click on proceed/further button.
8. User will be navigated to the payment page.
9. Fill in payment details and click on place order button
10. Observe "Invalid Email Format" error displays instead of the error message mentioned in your steps i.e. "Failed address validation:..."
<img width="957" alt="invalid email error" src="https://github.com/user-attachments/assets/17859ba3-59cd-4303-bc33-65c8b35edb6f">

Please let us know if any other steps are needed to be performed.

Thanks.

**Comment by engcom-Delta** [comment] 2024-08-08 06:42
Hi @DanieliMi ,

We have noticed that this issue has not been updated since long time.
Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Delta** 2024-08-08 06:42 UTC
Labels: Component: Checkout, Issue: needs update, Area: Cart & Checkout, Reported on 2.4.6-p6
