### ISSUE TITLE
Product Attribute Label Translation Not Showing Correct For The Store Ordered In

### ISSUE THREAD

**Issue by stijntrinos** [magento/magento2#37335] opened 2023-04-05 09:41 UTC
### Preconditions and environment

- Magento version : 2.4.5-p1
- Multi Store with 2 languages
- Configurable Product with color option

### Steps to reproduce

We need a configurable product with a dropdown attribute option. The label of the attribute is translated for different stores.

![Screenshot 2023-04-05 at 11 31 56](https://user-images.githubusercontent.com/96116544/230041426-03057138-814b-458f-be17-e82ce30e52dc.png)

- When ordering this product in the default store, everything is normal and the label is translated correctly.
- After you ordered from the default store, you go to a different store (in this case store3).
- Here you order the same product as before in the default store.
- After the product is ordered, you go to the `Admin > Sales > Orders` grid and open the order of `store3`

Here you see under `Items Ordered`, that the label translation is from the default store and the value of the attribute is translated correctly. 

![Screenshot 2023-04-05 at 11 40 17](https://user-images.githubusercontent.com/96116544/230043573-c504b3e1-bf9a-4493-92d4-4eb17c3ca154.png)

### Expected result

The saved translation for the attribute label is showed in ordered items.

### Actual result

The translation of a different language is shown

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-04-11 09:29
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-04-11 13:53
Hi @stijntrinos,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- When ordering this product in the default store, everything is normal and the label is translated correctly.
- After you ordered from the default store, you go to a different store (in this case store3).
- Here you order the same product as before in the default store.
- After the product is ordered, you go to the Admin > Sales > Orders grid and open the order of store3


<img width="1387" alt="Screenshot 2023-04-11 at 4 08 53 PM" src="https://user-images.githubusercontent.com/51680745/231161628-cdcf833d-46d3-4d30-8c23-6178aff438d9.png">

We have ordered from default store.


<img width="757" alt="Screenshot 2023-04-11 at 5 57 32 PM" src="https://user-images.githubusercontent.com/51680745/231162048-26cc0bf7-27d5-4636-8650-54ba106c05ee.png">


We have ordered from German store.We are able to get the Labels.

<img width="493" alt="Screenshot 2023-04-11 at 4 08 27 PM" src="https://user-images.githubusercontent.com/51680745/231161731-5a87e08b-77ad-44ec-915d-f7d2665bdb46.png">


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-04-26 06:05
Hi @stijntrinos,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-04-26 06:05 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1

**Comment by LucScu** [comment] 2024-07-03 11:32
@stijntrinos are you still experiencing this problem?

**Comment by stijntrinos** [comment] 2024-07-11 05:44
Hi @LucScu,
Yes we still are still experiencing this issue

**Comment by stijntrinos** [comment] 2024-07-11 08:12
@LucScu unfortunately randomly. So I have no idea how this comes

**Comment by LucScu** [comment] 2024-07-11 08:20
@stijntrinos me too, i have this issue also in the previous version 2.2.11 and now in 2.4.6-p3.
The wrong language translation is saved directly in quote_options so from there is propagated in all sequent steps.
What could there be that introduces randomness? Could it be a simultaneous cache flush?
Do you have any hypotheses?

**Comment by stijntrinos** [comment] 2024-07-11 08:24
@LucScu 
Unfortunately not. Have looked at the basic debug steps, but the thing is that it's random...
So we now have just leaved it for a bit as we hope it will be fixed with a newer version. We are also currently remaking this shop with Hyva, so it might be fixed within that for us.

**Comment by LucScu** [comment] 2024-07-24 13:11
@hostep @engcom-Bravo do you have some hints about this? thx

**Comment by chapagain** [comment] 2024-12-13 22:00
It could be related to “**EAV types and attributes**” cache. 
Clearing that cache type from `System > Cache Management` resolved the issue for me.

**Comment by jmulleman** [comment] 2025-07-25 09:36
@engcom-Bravo issue still persist on the latest magento environment. Please reopen the ticket and prioritize it.
