### ISSUE TITLE
Authorization failed when using SearchCriteria using REST API

### ISSUE THREAD

**Issue by minetteyou** [magento/magento2#4161] opened 2016-04-14 20:01 UTC
Similar questions have been posted here, but none provided the solution that worked for me.
## Summary

I authenticated with `/admin/token`, and was able to access `/products/:sku`. However, when I tried to do `/products?searchCriteria...`, I encountered an access error:

> { "message": "Consumer is not authorized to access %resources", "parameters": { "resources": "Magento_Catalog::products" } }

I checked the user roles in my admin site, and I belong to a user role with access to all resources. Can you tell me why I'm seeing this error?
## Steps I took
1. Got an admin token
   `curl -X POST "http://magento2.stores.klaviyo.com/index.php/rest/V1/integration/admin/token" \
    -H "Content-Type:application/json" \
    -d '{"username":<admin>, "password":<Minsanity1234}'`
2. Did a test Web API call using the searchCriteria example given in Magento's official doc.
   `http GET http://magento2.stores.klaviyo.com/index.php/rest/V1/products? \
   searchCriteria[filter_groups][0][filters][0][field]=size& \
   searchCriteria[filter_groups][0][filters][0][value]=Large& \
   searchCriteria[filter_groups][0][filters][0][condition_type]=eq& \
   searchCriteria[filter_groups][0][filters][1][field]=color& \
   searchCriteria[filter_groups][0][filters][1][value]=Red& \
   searchCriteria[filter_groups][0][filters][1][condition_type]=eq \
   Authorization:'Bearer oly9bh07dljyo2sj7n8ck1bd9iwn7ee9'`

Thank you!

**Comment by piotrekkaminski** [comment] 2016-05-24 16:14
@mbrinton01 can you have someone look into it?
@minetteyou that question is probably more suited for http://magento.stackexchange.com/

**Comment by mbrinton01** [comment] 2016-08-22 19:02
@minetteyou It may have something to do with your syntax of how you are passing the token in the call. I tried this several different ways and it was successful.  For example, here is the same call using curl:

```
curl -X "GET" "http://m2github.dev/index.php/rest/V1/products?searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bfield%5D=size&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bvalue%5D=Large&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bcondition_type%5D=eq&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B1%5D%5Bfield%5D=color&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B1%5D%5Bvalue%5D=Red&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B1%5D%5Bcondition_type%5D=eq" \
    -H "Authorization: bearer u02c9216l7eypenc2ihfdn9tbmmi4tde"
```

Of course your hostname and token will need to be changed to work on your local instance.  Because I'm not able to reproduce your issue, I'm closing this ticket.  If you have more questions about how to format API calls, http://magento.stackexchange.com/ would be a more suitable place to ask general questions.

**Closed as completed by mbrinton01** 2016-08-22 19:02 UTC
Labels: Component: Framework/Webapi
