### ISSUE TITLE
M 2.1.1 Wysiwyg can not click button 'Insert Image' the second in Admin cms pages

### ISSUE THREAD

**Issue by Gin-Tuyen** [magento/magento2#6892] opened 2016-10-06 04:49 UTC
Preconditions
     1.Server: ubuntu server 16
     2.PHP 7

Steps to reproduce
     1. In Admin, click Content -> Pages-> New Page -> Click tap Content -> Click button 'Show / Hide Editor' -> click button 'Insert Image...'
     2. In page Insert File, Click closed (image X)
     3.In Page content -> Click button 'Insert Image...' -> bug Uncaught TypeError: Cannot read property 'closed' of undefined

Expected result
1.
![1](https://cloud.githubusercontent.com/assets/16332775/19140789/2bb890a8-8bba-11e6-9be2-f7f13548698c.png)
2.
![screenshot](https://cloud.githubusercontent.com/assets/16332775/19140801/3e9be9a4-8bba-11e6-892d-2252c6f80dac.png)
3.
<img width="1257" alt="screenshot at oct 06 11-41-01" src="https://cloud.githubusercontent.com/assets/16332775/19140803/4641807e-8bba-11e6-9d6f-082c1b66bfee.png">

Actual result
   Show page Insert File

**Comment by miakusha** [comment] 2016-10-18 13:57
Hi @Gin-Tuyen thanks for report

We've created internal ticket MAGETWO-59822 to address this issue.

**Comment by magento-engcom-team** [comment] 2017-09-20 23:19
@Gin-Tuyen, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 23:19 UTC
Labels: Issue: Ready for Work, bug report, Component: Cms, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
