### ISSUE TITLE
Attribute text field takes blank values

### ISSUE THREAD

**Issue by mageprince** [magento/magento2#21504] opened 2019-02-28 12:55 UTC
Attribute text field takes the blank value on `create new value` in `Create Product Configurations` popup
### Preconditions (*)

Magento 2.3.x

### Steps to reproduce (*)

1. Go to Admin
2. Add Configurable product
3. Create Configurations
4. Select any attribute
5. From any attribute click on Create new Value 
6. Add the size with blank value with space, it adds successfully.

### Expected result (*)

Attribute text field should not take blank values(also before and after attribute text)

### Actual result (*)

On Frontend configurable product show blank values in dropdown

![screenshot from 2019 02 28 18 19 28](https://user-images.githubusercontent.com/24751863/53567620-c860ff80-3b85-11e9-9068-c5670cd8279a.png)

**Comment by magento-engcom-team** [comment] 2019-02-28 12:55
Hi @mageprince. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mageprince do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-02-28 12:56
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-02-28 12:56
Hi @krishprakash. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by krishprakash** [comment] 2019-02-28 12:58
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-28 12:58
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-28 12:59
Hi @krishprakash, here is your [Magento instance](https://i-21504-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21504-2-3-develop.instances.magento-community.engineering/admin](https://i-21504-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2019-02-28 13:10
![att](https://user-images.githubusercontent.com/46617848/53568554-5c33cb00-3b88-11e9-9465-8ab562674a6b.png)

**Comment by magento-engcom-team** [comment] 2019-02-28 14:07
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98487` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ElangoLS** [comment] 2019-05-04 04:54
I am working on this at #dmcdindia1

**Comment by magento-engcom-team** [comment] 2019-05-04 04:54
@ElangoLS thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by VladimirZaets** [comment] 2019-12-03 17:08
Hi @mageprince. Thank you for your report. 
The issue has been fixed in magento/magento2#25421 by @torhoehn in 2.3-develop branch
Related commit(s):
 - [be24d9005aecac7cbeabdefc2a49771a3d4790cd](https://github.com/magento/magento2/commit/be24d9005aecac7cbeabdefc2a49771a3d4790cd)
 - [0cd4aeae861db9593da45040f9e46691ea340379](https://github.com/magento/magento2/commit/0cd4aeae861db9593da45040f9e46691ea340379)
 - [d8e02f37021f1ae793b664ed3a8f241b129cfb8c](https://github.com/magento/magento2/commit/d8e02f37021f1ae793b664ed3a8f241b129cfb8c)
 - [a9d15943f0f6f35a1d42eee15c5b992ed66810ab](https://github.com/magento/magento2/commit/a9d15943f0f6f35a1d42eee15c5b992ed66810ab)
 - [729c0cd6bbe7bc02b08420a8319ee894a730f16e](https://github.com/magento/magento2/commit/729c0cd6bbe7bc02b08420a8319ee894a730f16e)

The fix will be available with the upcoming 2.3.5 release.

**Closed as completed by VladimirZaets** 2019-12-03 17:08 UTC
Labels: Issue: Ready for Work, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: ConfigurableProduct, Component: Admin, Event: dmcdindia1
