### ISSUE TITLE
Creating a category via import corrupts catalog - category view in admin when catagory contains "\" backslash character

### ISSUE THREAD

**Issue by fabotha** [magento/magento2#39220] opened 2024-09-26 09:18 UTC
### Preconditions and environment

- Magento version 2.4.7
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

import a product with add/update
2 columns
sku and categories
1122 in column 1 
Home/More Items/More Items\Manuals in column 2
check data
import
import works ok
Please note I got the category name wrong and did not mean to do this
Please note the slash between More Items and Manuals is a backslash "\"

### Expected result

Expected result is that a new category is created in home called "Home/More Items/More Items\Manuals"
I coded the wrong dash I meant to create a new category in Home/More Items called Manuals but it created a new category called "Home/More Items/More Items\Manuals" in the home category.
This new category displayed ok on the store front, but caused a corruption in the M2 Admin catalog - categories screen, so that no categories are displayed.

### Actual result

The result I got was a new category "Home/More Items/More Items\Manuals" in the home category
However in M2 , the catalog - categories admin screen now shows no categories and no structure,
Images below

### Additional information

See images
https://firesupportltd-my.sharepoint.com/:f:/g/personal/accounts_firesupport_uk/EmdNw1PMzhFNg_03qrFohG8BZwp5PSflGf76ea34mqcEHg?e=R4EGm7

### Release note

backslash character "\" not allowed in a catagory name and fails the check data stage with an error message.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by fabotha** [comment] 2024-09-26 09:20
my release note should have said
backslash character "\" not allowed in a category name and fails the check data stage with an error message.

**Comment by fabotha** [comment] 2024-10-08 08:03
Hi
Did you created the folder manually or using an import of a product?
I had the problem when importing a csv file.

Please confirm

Thanks
Frank


Please note we have a new email address
***@***.******@***.***>

We ship Airsoft products all over the world.
Tax free (20% off) at checkout to all countries.

Marui recoil Specials - repairs, upgrade, lipo conversion and custom work

Latest products - www.fire-support.co.uk/latest_products.php<http://www.fire-support.co.uk/latest_products.php>

OPEN 4 Days a week, Tue - friday 9am - 5.30pm
Alternate Saturdays 10-5
see https://www.fire-support.co.uk/openingtimes.php
Please always reply with our email in yours so we can track the conversation.

Frank - Director
Tel 01733 247171

**Comment by engcom-Bravo** [comment] 2024-10-09 07:56
Hi @fabotha,

Thanks for your update.

We have verified while importing the CSV file for a product.

Here is the CSV file :

[export_catalog_product_20240918_032635.csv](https://github.com/user-attachments/files/17304494/export_catalog_product_20240918_032635.csv)


Thanks.

**Comment by fabotha** [comment] 2024-10-09 09:32
Hi
Thank you for your reply.
This broke my admin catalog / category screen display but I accept your results.
We are on 2.4.7 p1 magento

Is it possible that an extension would have cause the issue?
It displayed ok on the customer storefront display, just broke admin.

Thanks
Frank




Please note we have a new email address
***@***.******@***.***>

We ship Airsoft products all over the world.
Tax free (20% off) at checkout to all countries.

Marui recoil Specials - repairs, upgrade, lipo conversion and custom work

Latest products - www.fire-support.co.uk/latest_products.php<http://www.fire-support.co.uk/latest_products.php>

OPEN 4 Days a week, Tue - friday 9am - 5.30pm
Alternate Saturdays 10-5
see https://www.fire-support.co.uk/openingtimes.php
Please always reply with our email in yours so we can track the conversation.

Frank - Director
Tel 01733 247171

**Comment by engcom-Bravo** [comment] 2024-10-09 09:37
Hi @fabotha,

Thanks for your update .

It might be possible any third party modules can causing this issue please check and let us know if you are facing any issue.

Thanks.

**Comment by fabotha** [comment] 2024-10-09 09:43
Thank you.
Frank


Please note we have a new email address
***@***.******@***.***>

We ship Airsoft products all over the world.
Tax free (20% off) at checkout to all countries.

Marui recoil Specials - repairs, upgrade, lipo conversion and custom work

Latest products - www.fire-support.co.uk/latest_products.php<http://www.fire-support.co.uk/latest_products.php>

OPEN 4 Days a week, Tue - friday 9am - 5.30pm
Alternate Saturdays 10-5
see https://www.fire-support.co.uk/openingtimes.php
Please always reply with our email in yours so we can track the conversation.

Frank - Director
Tel 01733 247171

**Comment by engcom-Bravo** [comment] 2024-10-10 05:03
Hi @fabotha,

Thanks for your update.

Since the issue is no more reproducible we are closing this issue Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-10-10 05:03 UTC
Labels: Issue: needs update, Reported on 2.4.7
