### ISSUE TITLE
Admin - dropdown toggle arrow not working on closing

### ISSUE THREAD

**Issue by saphaljha** [magento/magento2#20240] opened 2019-01-12 08:44 UTC
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Add/Edit any product
2. Click on any dropdown and again click on it closing it.
3. Array will not rotate on closing

### Expected result (*)

 ![acpected-productsinventorycatalogmagentoadmin](https://user-images.githubusercontent.com/23274052/51071262-25efca00-1674-11e9-9e37-cc36837e2f95.png)

### Actual result (*)

![actual-productsinventorycatalogmagentoadmin](https://user-images.githubusercontent.com/23274052/51071266-356f1300-1674-11e9-8f73-20de33e18d0f.png)

**Comment by magento-engcom-team** [comment] 2019-01-12 08:45
Hi @saphaljha. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@saphaljha do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-12 08:45
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-01-12 08:45
Hi @niravkrish. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by saphaljha** [comment] 2019-01-12 08:45
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-01-12 08:46
Hi @saphaljha. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-01-12 08:46
Hi @saphaljha, here is your [Magento instance](https://i-20240-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20240-2-3-develop.instances.magento-community.engineering/admin](https://i-20240-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-01-12 08:47
@saphaljha Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-01-12 08:48
@saphaljha Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97604` were created

**Comment by magento-engcom-team** [comment] 2019-01-19 06:55
Hi @saphaljha. Thank you for your report. 
The issue has been fixed in magento/magento2#20241 by @niravkrish in 2.3-develop branch
Related commit(s):
 - [52130ac66561228a7a07fd41785940e0156e2286](https://github.com/magento/magento2/commit/52130ac66561228a7a07fd41785940e0156e2286)
 - [c1d987b1c437924a22b22fd48ca270742afa4991](https://github.com/magento/magento2/commit/c1d987b1c437924a22b22fd48ca270742afa4991)
 - [75d3b003b784a1ad92f298d28883df85b5db5d25](https://github.com/magento/magento2/commit/75d3b003b784a1ad92f298d28883df85b5db5d25)
 - [860e4e3aef7984b4595bf3deddd6d617f9e527e1](https://github.com/magento/magento2/commit/860e4e3aef7984b4595bf3deddd6d617f9e527e1)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2019-01-19 06:55 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Ui

**Comment by magento-engcom-team** [comment] 2019-02-13 21:25
Hi @saphaljha. Thank you for your report. 
The issue has been fixed in magento/magento2#20616 by @niravkrish in 2.2-develop branch
Related commit(s):
 - [b8fa8f3069b3559f4276783a9b9d254e8bb9568f](https://github.com/magento/magento2/commit/b8fa8f3069b3559f4276783a9b9d254e8bb9568f)

The fix will be available with the upcoming 2.2.9 release.
