### ISSUE TITLE
Additional Image Labels are not being imported

### ISSUE THREAD

**Issue by stefanguapa** [magento/magento2#9120] opened 2017-04-04 08:43 UTC
### Preconditions
1. Magento EE 2.1.3

### Steps to reproduce

1. Create a product and upload several additional images without an ALT tag
2. Create a CSV to import additional image labels. My example has 4 additional images. Example CSV:
`sku;website_id;additional_images;additional_image_labels
BB142;1;/1/7/1700x700x380mm-round-single-ended-bath-front-view-bb142-v5001.jpg,/1/7/1700x700x380mm-round-single-ended-bath-close-up-view-bb142-v5000.jpg,/1/7/1700x700x380mm-round-single-ended-bath-zoomed-out-view-bb142-v5001.jpg,/1/7/1700x700x380mm-round-single-ended-bath-dimensions-i2-bb142-v5000.jpg;,Test image 1,,Test image 4`
3. Go to `System > Imports`
4. Change the settings to the following:
Entity Type: `Products`
Import Behavior: `Add/Update`
Field seperator: `;`
5. Select your CSV file and run the import

### Expected result
The additional image labels (alt tags) of the selected products should have the value that has been set by the import.

### Actual result
The alt tags of the selected images of the selected products are not updated.

**Comment by stefanguapa** [comment] 2017-04-12 11:29
Is there any chance this issue could be reviewed?

**Comment by gman-1986** [comment] 2017-04-25 08:20
I have the same issue in 2.1.5

**Comment by stefan1294** [comment] 2017-05-31 08:21
Issue is still occurring..

**Comment by stefanguapa** [comment] 2017-05-31 08:21
Issue is still occurring...

**Comment by johnny-longneck** [comment] 2017-06-26 14:17
I am still struggling with that. Our SEO is so bad right now since we launched the M2 shop. 
Anyone here who is able to fix this?

**Comment by IlnitskiyArtem** [comment] 2017-07-04 14:11
@stefanguapa, Thanks for reporting this issue. 
We've created internal ticket MAGETWO-70459 to address this issue.

**Comment by magento-engcom-team** [comment] 2017-12-04 14:30
@stefanguapa, thank you for your report.
The issue is already fixed in develop branch, 2.1.10, 2.2.1

**Closed as completed by magento-engcom-team** 2017-12-04 14:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Confirmed, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
