### ISSUE TITLE
Bug with currency symbol in magento 2.4.3

### ISSUE THREAD

**Issue by leduydong94** [magento/magento2#34947] opened 2022-01-10 04:36 UTC
### Preconditions (*)

1. Magento 2.4.3
2. Currency is Euro

### Steps to reproduce (*)

1. Set currency is Euro
2. Flush Cache
3. Visit product page

### Expected result (*)

1. Currency symbol will appear

### Actual result (*)

1. https://www.loom.com/share/37046d17879247108adbc71f0fa58628
2. Currency symbol does not appear

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment] 2022-01-10 10:25
@magento give me 2.4.3-develop instance

**Comment by ajijshekh123** [comment] 2022-01-10 10:31
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-01-10 13:36
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue.
We are closing this issue as this is a duplicate of https://github.com/magento/magento2/issues/33856 and fixed in 2.4-develop branch. Kindly apply this as patch https://github.com/magento/magento2/commit/ae304d43cd36322b1ff8145d70c9b2e9aeb0cde as a workaround to resolve your issue. 
Thank you.

**Closed as completed by engcom-November** 2022-01-10 13:36 UTC
Labels: duplicate, Issue: ready for confirmation

**Comment by leduydong94** [comment] 2022-01-12 08:14
> Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue. We are closing this issue as this is a duplicate of #33856 and fixed in 2.4-develop branch. Kindly apply this as patch [ae304d4](https://github.com/magento/magento2/commit/ae304d43cd36322b1ff8145d70c9b2e9aeb0cde) as a workaround to resolve your issue. Thank you.

Thanks for solution !
