### ISSUE TITLE
Not possible to create an invoice in Magento 2.3

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#16653] opened 2018-07-09 14:33 UTC
When testing the new Magento 2.3 Alpha version it found out it it's not possible to create a new invoice for an order. An error is thrown. 

### Preconditions
1. Magento 2.3 Alpha installed 
2. Create an order without an invoice attached to it. 

### Steps to reproduce
1. Open the order and click the "Invoice" action to start creating an invoice  

### Expected result
1. See the invoice screen, so that an invoice can be created. 

### Actual result
1. Error is thrown, a new invoice can't be created. 

![image](https://user-images.githubusercontent.com/1058480/42456637-694c7fd6-8363-11e8-8237-ae334763673f.png)

**Comment by magento-engcom-team** [comment] 2018-07-09 14:33
Hi @dverkade. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@dverkade do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment] 2018-07-09 14:55
Hello @dverkade, thank you for your report. Unfortunately I cannot reproduce this issue by provided steps.
![peek 2018-07-09 17-52](https://user-images.githubusercontent.com/40755810/42457811-1a0f3fd8-83a1-11e8-96e4-af14f7aceb9b.gif)
Can you please add more details?

**Comment by dverkade** [comment] 2018-07-09 15:32
@magento-engcom-team give me 2.3.0-alpha instance

**Comment by magento-engcom-team** [comment] 2018-07-09 15:32
Hi @dverkade. Thank you for your request. I'm working on Magento 2.3.0-alpha instance for you

**Comment by dverkade** [comment] 2018-07-09 16:35
@engcom-backlog-nickolas I see you are using a 2.3-develop instance. I was on the 2.3.0-alpha which was installed with composer. Can that be the difference? Also I tried the command to spin up a new clean environment of Magento 2.3.0-alpha but it's not giving me an instance.

**Comment by engcom-backlog-nickolas** [comment] 2018-07-10 06:16
@dverkade, thank you for feedback and pull request. 
I believe 2.3.0-alpha already outdated. And if you take a look at current 2.3-develop, this block still in use
![toolbar](https://user-images.githubusercontent.com/40755810/42492400-a194d942-8421-11e8-988b-b130eb16eace.png)
So, I'm closing this issue, if you don't mind. And our team will process your pull request. Feel free to reopen it if needed.

Best regards!

**Closed as completed by engcom-backlog-nickolas** 2018-07-10 06:16 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by dverkade** [comment] 2018-07-10 13:45
Hi @engcom-backlog-nickolas 

As you can see in your screenshot the totalbar block is empty and not rendering anything (see highlight in my screenshot below). I could not find any screen where this was actually rendering something (See issue #16656). Also if it does render something there is no styling attached to it, so would look very weird as shown here: #16563#issuecomment-403501388

![image](https://user-images.githubusercontent.com/1058480/42513678-8a74dcd6-8425-11e8-80d1-2553ac1832b2.png)

**Comment by engcom-backlog-nickolas** [comment] 2018-07-10 14:00
@dverkade, thanks for feedback and investigation. Still, issue described here not reproducible on 2.3-develop anymore, so I leave it closed for now. 
You may create another issue with steps, actual and expected results which reflect more correctly current behaviour on 2.3-develop branch. It will help more easily process pull request to 2.3-develop.

**Comment by magento-engcom-team** [comment] 2018-08-07 10:30
Hi @dverkade. Thank you for your report. 
The issue has been fixed in magento/magento2#16656 by @dverkade in 2.2-develop branch
Related commit(s):
 - [19bff300ecd22dca8966da691f01044ba9e5575b](https://github.com/magento/magento2/commit/19bff300ecd22dca8966da691f01044ba9e5575b)

The fix will be available with the upcoming 2.2.7 release.

**Comment by sidolov** [comment] 2018-08-08 11:17
Hi @dverkade. Thank you for your report. 
The issue has been fixed in magento/magento2#17413 by @dverkade in 2.1-develop branch
Related commit(s):
 - [db166c748957a161d9cdc79d0c110caa609857c7](https://github.com/magento/magento2/commit/db166c748957a161d9cdc79d0c110caa609857c7)

The fix will be available with the upcoming 2.1.16 release.

**Comment by magento-engcom-team** [comment] 2018-08-10 08:05
Hi @dverkade. Thank you for your report. 
The issue has been fixed in magento/magento2#17414 by @dverkade in 2.3-develop branch
Related commit(s):
 - [1fe125161c3e9a4b94b8b9ae8c1dd46ed10b4ed4](https://github.com/magento/magento2/commit/1fe125161c3e9a4b94b8b9ae8c1dd46ed10b4ed4)

The fix will be available with the upcoming 2.3.0 release.
