### ISSUE TITLE
Sales Rule Coupons usage is incremented asynchronously but decremented Synchronously

### ISSUE THREAD

**Issue by tommi-martin** [magento/magento2#34627] opened 2021-11-12 14:23 UTC
In Magento 2.4.3 a commit introduced asynchronous incrementation to the sales rule coupon usage system in task MC-29335. However this implementation did not modify the decrement logic, which can lead to database error when coupon usage is being decremented during order cancellation. I would expect that this error is quite rare on actual production servers, however it makes testing and developing payment methods a headache. 

### Preconditions (*)
1. Magento 2.4.3 or higher
2. Message queue consumers are inactive or delayed.
3. Active Cart sales rule that gives free shipping for purchases over 50$ 

### Steps to reproduce (*)

1. Add products to cart with combined value exceeding 50$
2. Proceed to checkout 
3. Fill checkout details and submit order
4. Cancel order using \Magento\Sales\Api\OrderManagementInterface::cancel before message queue has been processed. This can be achieved from admin order cancel controller

### Expected result (*)

1. Order is cancelled 

### Actual result (*)

1. Cancelling order fails to the following exception.
```
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento-clean`.`salesrule_customer`, CONSTRAINT `SALESRULE_CUSTOMER_RULE_ID_SEQUENCE_SALESRULE_SEQUENCE_VALUE` FOREIGN KEY (`rule_id`) REFERENCES `sequence_salesrule` (`sequence_value`) ON DE), query was: INSERT INTO `salesrule_customer` () VALUES ()
```
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2021-11-16 15:58
Hi @tommi-martin,
Tried to reproduce it on Magento 2.4 Develop latest branch , order has cancelled successfully, while cancelling getting error "You have not cancelled the item

Uploading https___mgnregs..mp4…

"
Please find the attached screenshots & video for reference.
![OrderCanceled](https://user-images.githubusercontent.com/51681379/142017140-0b3d62b3-4de6-458e-9426-a4f9224cbed6.JPG)

**Comment by tommi-martin** [comment] 2021-11-17 09:00
Hello @engcom-Delta Thank you for your attention towards this matter. In the recording did you perhaps check the exception that caused the error message to be printed? It originates from the cancel controller's try catch logic and if I gave you my instructions right, the actual exception should be the mysql query error in the original description, while the message shown to user is inaccurate.

\Magento\Sales\Controller\Adminhtml\Order\Cancel::execute
```
try {
    $this->orderManagement->cancel($order->getEntityId());
    $this->messageManager->addSuccessMessage(__('You canceled the order.'));
} catch (\Magento\Framework\Exception\LocalizedException $e) {
    $this->messageManager->addErrorMessage($e->getMessage());
} catch (\Exception $e) {
    $this->messageManager->addErrorMessage(__('You have not canceled the item.'));
    $this->_objectManager->get(\Psr\Log\LoggerInterface::class)->critical($e);
}
```

I suspect the exception behind that particular error message is the same as I had in the development of my payment module on the frontend side of things. Which I will cover up with a similar try catch, however shouldn't the original issue be addressed?

**Comment by engcom-Hotel** [comment] 2022-02-02 10:47
Hello @tommi-martin,

We have tried to reproduce the issue in the Magento 2.4-develop branch and we are unable to reproduce the issue. It may be possible the issue has been fixed in this branch. We are able to cancel the order without any issue. For us the message queue is inactive.

Please have a look at the below screenshot for reference:
![image](https://user-images.githubusercontent.com/51681618/152138984-dd442a95-a28c-4ca6-b90a-b4e9fcf261c6.png)

We request you to try to reproduce the issue in the Magento 2.4-develop branch and let us know if it is still reproducible for you.

Thanks

**Comment by braders** [comment] 2022-02-11 16:59
I manage a high-traffic Magento site using the Cybersource payment gateway, and am seeing this issue frequently in relation to 3DSecure. If the 3DSecure authentication fails, cybersource is throwing an error which causes the sales coupon to be cancelled.

In addition to the SQL error, we are having significant issues with customers re-trying the payment and finding their coupon has reportedly been used (becuase the coupon was decremented, but the increment was still in queue). Our customer services team are having to manually refund several missed coupons per day due to the customer confusion this is causing.

Any progress here would be much appreciated.

**Comment by engcom-Hotel** [comment] 2022-03-02 10:10
Hello @tommi-martin @braders,

Have you tried to reproduce the issue in Magento 2.4-develop branch? It seems that the is already fixed in this branch.

Thanks

**Comment by engcom-Hotel** [comment] 2022-03-16 06:30
Dear @tommi-martin,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-03-16 06:30 UTC
Labels: Triage: Dev.Experience, Issue: needs update
