### ISSUE TITLE
Integration Tests Framework AppArea annotation doesn't affect regular Object Manager which resolves dependencies during objects creation

### ISSUE THREAD

**Issue by alexey-dorosh** [magento/magento2#36090] opened 2022-09-06 11:21 UTC
### Preconditions and environment

- Magento version: CE 2.4.5
- You need a single class which will delete an order. Something like `$order->delete()`. But this class should be required with constructor.

_Why not object manager: integration tests are purposed to test complex systems, so there are a lot of classes, which requires classes, which requires classes and so on. And if some of that required < required < required classes tries to delete an order -- it will lead to an exception
And it doesn't help if we are getting this class with TestFramework\Helperr\Bootstrap::getObjectManager()->get(...)_

### Steps to reproduce

1) Create an integration test on that class.
2) use `@magentoAppState adminhtml` annotaion
3) run the test

### Expected result

An order will be deleted

### Actual result

![image](https://user-images.githubusercontent.com/100999051/188621406-1aac8c63-8de5-4f7f-bec5-cde445da98a4.png)

### Additional information

During order deletion there is an isAllowed check
[Magento\Framework\Model\ActionValidator\RemoveAction::isAllowed](https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Model/ActionValidator/RemoveAction.php#L45)

But for adminhtml scope this class [is preferenced](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Backend/etc/adminhtml/di.xml#L29) with Magento\Framework\Model\ActionValidator\RemoveAction\Allowed, where this method [always returns true](https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Model/ActionValidator/RemoveAction/Allowed.php#L20).
(also this preference is declared for webapi)

The problem is:
When annotation `@magentoAppState adminhtml` is being used -- we are reinitializing the application: [Magento\TestFramework\Annotation\AppArea::startTest](https://github.com/magento/magento2/blob/2.4-develop/dev/tests/integration/framework/Magento/TestFramework/Annotation/AppArea.php#L99),
And then we are loading correct area. But if we do it this way -- the object manager, which is responsive for classes constructors dependencies resolving -- will be working with global DI configs, not adminhtml.

[Magento\TestFramework\Annotation\AppArea::startTest](https://github.com/magento/magento2/blob/2.4-develop/dev/tests/integration/framework/Magento/TestFramework/Annotation/AppArea.php#L100) calls [Magento\TestFramework\Application::reinitialize](https://github.com/magento/magento2/blob/2.4-develop/dev/tests/integration/framework/Magento/TestFramework/Application.php#L481) without parameters
```
public function startTest(TestCase $test)
{
    $values = [];
    try {
        $values = $this->parse($test);
    } catch (\Throwable $exception) {
        ExceptionHandler::handle(
            'Unable to parse fixtures',
            get_class($test),
            $test->getName(false),
            $exception
        );
    }

    $area = $values[0]['area'] ?? Application::DEFAULT_APP_AREA;

    if ($this->_application->getArea() !== $area) {
        $this->_application->reinitialize(['area' => $area]);

        if ($this->_application->getArea() !== $area) {
            $this->_application->loadArea($area);
        }
    }
}
```
Reinitialize calls [Magento\TestFramework\Application::initialize](https://github.com/magento/magento2/blob/2.4-develop/dev/tests/integration/framework/Magento/TestFramework/Application.php#L385)
There is a complex methow, which creates and configures an object manager and loads the application. But somewhy -- always global:
[Line 454](https://github.com/magento/magento2/blob/2.4-develop/dev/tests/integration/framework/Magento/TestFramework/Application.php#L454):
```
if ($this->canLoadArea) {
    $this->loadArea(TestFramework\Application::DEFAULT_APP_AREA);
}
```
And then it finishes to configure the object manager.

Yeah, after that we are reloading the application with correct area, but the object manager is configured wrong

My workaround:
```
Index: dev/tests/integration/framework/Magento/TestFramework/Annotation/AppArea.php
===================================================================
diff --git a/dev/tests/integration/framework/Magento/TestFramework/Annotation/AppArea.php b/dev/tests/integration/framework/Magento/TestFramework/Annotation/AppArea.php
--- a/dev/tests/integration/framework/Magento/TestFramework/Annotation/AppArea.php
+++ b/dev/tests/integration/framework/Magento/TestFramework/Annotation/AppArea.php
@@ -97,7 +97,7 @@
         $area = $values[0]['area'] ?? Application::DEFAULT_APP_AREA;
 
         if ($this->_application->getArea() !== $area) {
-            $this->_application->reinitialize();
+            $this->_application->reinitialize(['area' => $area]);
 
             if ($this->_application->getArea() !== $area) {
                 $this->_application->loadArea($area);
Index: dev/tests/integration/framework/Magento/TestFramework/Application.php
===================================================================
diff --git a/dev/tests/integration/framework/Magento/TestFramework/Application.php b/dev/tests/integration/framework/Magento/TestFramework/Application.php
--- a/dev/tests/integration/framework/Magento/TestFramework/Application.php
+++ b/dev/tests/integration/framework/Magento/TestFramework/Application.php
@@ -384,6 +384,9 @@
      */
     public function initialize($overriddenParams = [])
     {
+        $area = $overriddenParams['area'] ?? null;
+        unset($overriddenParams);
+
         $overriddenParams[\Magento\Framework\App\State::PARAM_MODE] = $this->_appMode;
         $overriddenParams = $this->_customizeParams($overriddenParams);
         $directories = isset($overriddenParams[\Magento\Framework\App\Bootstrap::INIT_PARAM_FILESYSTEM_DIR_PATHS])
@@ -452,7 +455,7 @@
         );
 
         if ($this->canLoadArea) {
-            $this->loadArea(TestFramework\Application::DEFAULT_APP_AREA);
+            $this->loadArea($area ?? TestFramework\Application::DEFAULT_APP_AREA);
         }
 
         TestFramework\Helper\Bootstrap::getObjectManager()->configure(

```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2022-09-07 09:26
Hello @alexey-dorosh,

Thanks for the report and collaboration!

We have tried to reproduce this issue in Magento 2.4-develop branch but for us, the issue is not reproducible for us. We have followed the below steps in order to reproduce the issue:

1. Create an Integration test on the class `Magento\Sales\Model\Order`. Please find attached the file for the same for reference:
[OrderTest.tar.gz](https://github.com/magento/magento2/files/9504724/OrderTest.tar.gz)

2. Run the test via the following command:
`../../../vendor/bin/phpunit ../../../dev/tests/integration/testsuite/Magento/Sales/Model/OrderTest.php`

Please review the steps and let us know in case we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2022-09-21 10:53
Dear @alexey-dorosh,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-09-21 10:53 UTC
Labels: Triage: Dev.Experience, Priority: P2, Progress: done, Issue: needs update, Reported on 2.4.5
