### ISSUE TITLE
Some of JS validation rules making fields required

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2#16544] opened 2018-07-04 19:45 UTC
Hi, dear Magento Comunity Engineering team.
In some cases quite useful to have validation only for the filled fields. For example:
we have on the form field `phone` which is not required, but it required to have valid data when user will fill out this field. In case if a user did not fill out anything error should not be displayed.
Bunch of validation rules makes this not possible.

On the screenshot, I've selected more important validation rules for my opinion. Some of them work fine, others have unexpected behavior. 

![new form content magento admin](https://user-images.githubusercontent.com/20116393/42292352-85e391ca-7fda-11e8-8238-604f21b0795e.png)

Here [form source ](https://github.com/VitaliyBoyko/validation-issues-magento-2/blob/master/view/adminhtml/ui_component/form_form.xml) to more convenient reproducing.

### Preconditions
1. Create a new module with form and field, or add a field to existing form
2. Set field validation, for example:
`<validation>
                    <rule name="phoneUS" xsi:type="boolean">true</rule>
 </validation>`
3. Field should not be required

### Steps to reproduce
1. Don't fill out the field just submit a form

### Expected result
1. The form is submitting as well

### Actual result
1. Form not being submitted, field validation process error

**Comment by magento-engcom-team** [comment] 2018-07-04 19:45
Hi @VitaliyBoyko. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@VitaliyBoyko do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment] 2018-07-05 07:15
Hello @VitaliyBoyko, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2018-08-08 10:50
Hi @VitaliyBoyko. Thank you for your report. 
The issue has been fixed in magento/magento2#16724 by @VitaliyBoyko in 2.2-develop branch
Related commit(s):
 - [e189fc97873278be4e4358565f022bd15276d64e](https://github.com/magento/magento2/commit/e189fc97873278be4e4358565f022bd15276d64e)
 - [2ed9af37dee0e223b2cae2d22659564a3b472a74](https://github.com/magento/magento2/commit/2ed9af37dee0e223b2cae2d22659564a3b472a74)
 - [e71836be515b7e0eb15fb1806e34b4672dcd7740](https://github.com/magento/magento2/commit/e71836be515b7e0eb15fb1806e34b4672dcd7740)
 - [c6a8fec4eedd1fe4033c56f42010bef81e7e1c6f](https://github.com/magento/magento2/commit/c6a8fec4eedd1fe4033c56f42010bef81e7e1c6f)

The fix will be available with the upcoming 2.2.7 release.

**Closed as completed by magento-engcom-team** 2018-08-08 10:50 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Ui

**Comment by ishakhsuvarov** [comment] 2018-09-12 10:17
Hi @VitaliyBoyko. Thank you for your report. 
The issue has been fixed in magento/magento2#17724 by @nmalevanec in 2.3-develop branch
Related commit(s):
 - [63c3198d277289ee8b9c56360d8da811f0d0a944](https://github.com/magento/magento2/commit/63c3198d277289ee8b9c56360d8da811f0d0a944)
 - [e7eba956761d894675b0b20fc89dc544c9144e2b](https://github.com/magento/magento2/commit/e7eba956761d894675b0b20fc89dc544c9144e2b)
 - [2fc0817b55567c6c73008b12c3b1544bdee5266e](https://github.com/magento/magento2/commit/2fc0817b55567c6c73008b12c3b1544bdee5266e)
 - [bcf8b516fbdb2f004da537d2ffec5500be93106c](https://github.com/magento/magento2/commit/bcf8b516fbdb2f004da537d2ffec5500be93106c)
 - [6588dab9a10b607a5b98490770ddcb0605fd85e7](https://github.com/magento/magento2/commit/6588dab9a10b607a5b98490770ddcb0605fd85e7)

The fix will be available with the upcoming 2.3.0 release.
