### ISSUE TITLE
Translation issue in admin grid on different locales

### ISSUE THREAD

**Issue by mobeen-sarwar** [magento/magento2#31050] opened 2020-11-25 09:54 UTC
**Preconditions (*)**

1- Magento 2.3.4-p2
2- Magento 2.3.5-p2
3- Translations for at least two locales

**Assumptions(*)**
1- We are assuming that we have three locales English, Japanese, and Korean, with translations.
![image](https://user-images.githubusercontent.com/75013004/100209604-e6f75480-2f2b-11eb-9f21-53d9a3308cab.png)
2- Make sure we have added translations for this path  `Admin->Sales->Orders->view(open an order details)->Transactions`

**Steps to reproduce (*)**

1- Login to Magento admin
2- Go to this path `Admin->Sales->Orders->view(open an order details)->Transactions` and note down header translations
![image](https://user-images.githubusercontent.com/75013004/100209953-42294700-2f2c-11eb-8861-a51f04b6bd2b.png)

3- Now set the Interface Locale to Korean assuming the previous was English US (`Go to admin -> Account Settings`).
4- Repeat step 2. 

**Expected result (*)**
1- Grid headers should be translated into Korean.

**Actual result (*)**
1- Grid headers are still in English.
![image](https://user-images.githubusercontent.com/75013004/100210498-deebe480-2f2c-11eb-9e4b-f1e69f768f52.png)

**Comment by mobeen-sarwar** [comment] 2020-11-25 10:00
@ajijshekh123

**Comment by engcom-Alfa** [comment] 2020-11-25 13:53
Hi @mobeen-sarwar .

Unfortunatelly, we are not able to reproduce this issue on fresh 2.4-develop.
Everything works as expected.

**Actual Result:** 

:heavy_check_mark: Japanese Language

![Screenshot from 2020-11-25 15-10-15](https://user-images.githubusercontent.com/51679138/100235804-85d47e80-2f35-11eb-9172-48d149d9860c.png)

:heavy_check_mark: Korean Language

![Screenshot from 2020-11-25 15-45-08](https://user-images.githubusercontent.com/51679138/100236114-ec599c80-2f35-11eb-91a4-73d2a13454be.png)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-11-25 13:53 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.3.4-p2

**Comment by mobeen-sarwar** [comment] 2020-11-25 14:07
Hi @engcom-Alfa 

Thanks for your humble responce. I already checked it on Magento 2.4 and found no issue there. I'm facing this issue on Magento 2.3.4-p2 and Magento 2.3.5-p2. So I'm looking a fix for Magento 2.3.4-p2 version.

Many thanks for your instant response.
