### ISSUE TITLE
Wrong Cart Price Rule calculation logic

### ISSUE THREAD

**Issue by aleksejtsebinoga** [magento/magento2#32736] opened 2021-04-13 11:36 UTC
### Preconditions (*)
1. Magento CE 2.4.0
2. Vertex is disabled
3. Configure Tax calculation settings in Stores -> Configuration -> Sales -> Tax -> Calculation settings to -

![Screenshot 2021-04-13 at 15 20 17](https://user-images.githubusercontent.com/28878572/114551242-cc6c1080-9c6b-11eb-84de-aaaa64fc6e92.png)

### Steps to reproduce (*)

1. Create a Cart Rule with the TEST10P code and the action to give a 10% discount on products;
2. Create a cart with the product;
3. Apply the coupon code;
4. Do the checkout;
5. Open the order in the admin and see taxes applied on the order;

### Expected result (*)
If - 
- the product costs 899 MEX 
- shipping is 99 MEX 
- the tax rate is 16% 
- the discount of 10% was applied 

The following results are expected -

Subtotal: 899 MEX
Discount: 89.9 MEX
Shipping: 99 MEX
Total without discount = Subtotal + Shipping = 998 MEX
Grand Total = Subtotal - Discount + Shipping = 908.1 MEX

Tax = 908.1 / 116 * 16 (tax rate) = 125.26 

### Actual result (*)
Instead of the expected result with the same preconditions we see different Tax amount - 

<img width="582" alt="Screenshot 2021-04-13 at 14 32 14" src="https://user-images.githubusercontent.com/28878572/114545830-1dc4d180-9c65-11eb-9fb9-8c6aed54f870.png">

Subtotal: 899 MEX
Discount: 89.9 MEX
Shipping: 99 MEX
Total without discount = Subtotal + Shipping = 998 MEX
Grand Total = Subtotal - Discount + Shipping = 908.1

And instead of the tax being calculated on the Grand Total it is calculated on the Total without discount

Tax = 998 / 116 * 16 (tax rate) = 137.6552

**Comment by engcom-Oscar** [comment] 2021-04-13 12:07
Hi @aleksejtsebinoga ! Thank you for your report.
I try to verify this issue, but looks like we miss some preconditions, because I get different result. May you please update description of the ticket.
![Uploading Screenshot from 2021-04-13 15-06-30.png…]()

**Comment by aleksejtsebinoga** [comment] 2021-04-13 12:22
@engcom-Oscar , I see that your Original Price is 899. 
It seems like your installation is configured as Catalog Prices - Including Taxes.

In our case - it is different I moved the configuration preconditions from steps to reproduce into the Preconditions section and added the screenshot of the current configs we have.


Hope this will help.

**Comment by engcom-Oscar** [comment] 2021-04-15 12:20
@aleksejtsebinoga Yes, as it written in the ticket - price of product is 899. Tax Calculation setting the same as in your description.
![Screenshot from 2021-04-15 15-17-37](https://user-images.githubusercontent.com/60198413/114867795-e178a900-9dfd-11eb-84a3-bdf16f5a3e00.png)
But result is still the same
![Screenshot from 2021-04-15 15-19-18](https://user-images.githubusercontent.com/60198413/114867915-0240fe80-9dfe-11eb-913a-dbdc1ddd4bd9.png)
What settings do you have in "Price Display Settings"?

**Comment by aleksejtsebinoga** [comment] 2021-04-15 12:43
Price Display Settings are Including Tax - 

![Uploading Screenshot 2021-04-15 at 15.23.24.png…]()

**Comment by engcom-November** [comment] 2021-07-12 11:16
Verified the issue on Magento 2.4.2 version and the issue is not reproducible with the provided steps for both US store and Mexican Stores setup:
**Steps performed:**
Mexican Store setup configuration - Default Country - Mexico, Currency: Mexcan peso, Default Tax Destination Calculation - Mexico
Stores -Configuration - Shipping Settings - Origin - Mexico
Admin - Stores - Configuration - Sales - Tax - Vertex disabled
Admin - Stores - Configuration - Sales - Tax - Configured as below:
![image](https://user-images.githubusercontent.com/60198231/125274550-b4b82d00-e32b-11eb-8c40-c92679c1d272.png)
![image](https://user-images.githubusercontent.com/60198231/125274614-c3064900-e32b-11eb-813c-a36901c8b862.png)
Created Tax Zone rate of 16% for Country - Mexico and applied to Tax rule (Stores - > Taxes)
Created Cart Price Rule of 10% (Marketing - Cart Price Rules )
![image](https://user-images.githubusercontent.com/60198231/125275113-41fb8180-e32c-11eb-96d4-023ad1762cba.png)
Front end - Added a Simple Product to Cart: MX 899 and proceed to checkout
Sub Total excluding tax: 899
Sub Total including tax: 899 + 16%(899) = 899 + 143.84 = 1042.84 - **No issue**   (since Catalog Prices set to Excluding Tax)
Shipping Excluding tax = 85.34
Shipping including tax = 85.34+ 16%(85.34) = 85.34 + 13.6544 = 99 - **No issue**  (since Shipping Prices set to Including Tax)
Now Total tax = 143.84+13.654 = 157.5 - **No issue** 
Apply promo code of 10% discount in Checkout page: 10%(1042.84) = 104.284 **No issue** (since Apply discount on Prices set to Including tax)
![image](https://user-images.githubusercontent.com/60198231/125271748-b6342600-e328-11eb-957a-ff5b14499231.png)
![image](https://user-images.githubusercontent.com/60198231/125277525-280f6e00-e32f-11eb-96ee-1156c9caef33.png)

**Note: For US Store setup with above Tax class configuration also, this issue is not reproducible.**
@aleksejtsebinoga As per your screenshot, discount is applied for price excluding tax but your Tax class configuration has Apply discount including tax. Also, Shipping rate should be including tax as per your Tax class Configuration. Can you please recheck the issue and provide the missing configuration details if its still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2021-07-26 07:17
@aleksejtsebinoga, We are closing this issue as there has been no latest update on the same.
Kindly re-check the issue again on 2.4-develop branch and reopen new ticket by providing the missing steps as well. if the issue is still reproducible.
![image](https://user-images.githubusercontent.com/60198231/126947985-b9d5b292-2e82-494e-bbe6-8914c887b987.png)
![image](https://user-images.githubusercontent.com/60198231/126947922-39703053-fe04-4840-a175-202fb99592fb.png)
![image](https://user-images.githubusercontent.com/60198231/126946832-5d1eeebd-2bbd-4f76-90c6-4e6888c3a76a.png)

**Closed as completed by engcom-November** 2021-07-26 07:17 UTC
Labels: Component: Tax, Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.0
