### ISSUE TITLE
Product option not reflated at my wish list when added from listing page

### ISSUE THREAD

**Issue by renard123** [magento/magento2#25091] opened 2019-10-16 11:08 UTC
Product option not reflated at my wish list when added from listing page

Preconditions (*)
Magento : 2.3

Steps to reproduce (*)
1. Front end > Product listing page
2. As login user
3. Select product option and click on wish list icon
4. review at my wish list page

Expected result (*)
Product should added into wish list with product options.

Actual result (*)
No product options when it added from product listing
It works fine in product detail page

**Comment by magento-engcom-team** [comment] 2019-10-16 11:20
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21866` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rafalcao** [comment] 2019-10-30 21:29
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-10-30 21:29
Hi @rafalcao. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by rafalcao** [comment] 2019-10-30 21:43
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-10-30 21:43
Hi @rafalcao. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-10-30 21:45
Hi @rafalcao, here is your [Magento instance](https://i-25091-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25091-2-3-develop.instances.magento-community.engineering/admin](https://i-25091-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Bartlomiejsz** [comment] 2020-10-27 20:59
@magento-engcom-team this seems to be the same that got fixed by https://github.com/magento/magento2/pull/28157

**Comment by engcom-Golf** [comment] 2021-01-13 14:07
I can confirm that issue is fixed on 2.4-develop branch. Will close this.

**Closed as completed** 2021-01-13 14:09 UTC
Labels: Issue: Ready for Work, Component: Catalog, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Wishlist, Event: cd-cologne19, Fixed in 2.4.x, Priority: P2, Severity: S2, Progress: done

**Comment by magento-engcom-team** [comment] 2021-01-13 14:11
Hi @renard123. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24943` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
