### ISSUE TITLE
Network error when print invoice in order grid

### ISSUE THREAD

**Issue by pandyakrunal** [magento/magento2#23855] opened 2019-07-24 11:46 UTC
Magento version 2.3.2
PHP 7.2
Got network error when clicking on the print invoice.
when it download process is going on and after time its show Fail. Network error
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1. Go to order grid.
2.select complete order.
3. Action dropdown selects Print invoice.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by engcom-Bravo** [comment] 2019-07-24 11:54
Hello @pandyakrunal. Thanks for applying. Though the essence of the issue may seem obvious judging by the three lines of Your description, still please provide all the necessary information in the required format (fill in the Preconditions, steps to reproduce, etc.).

**Comment by pandyakrunal** [comment] 2019-07-24 12:01
@engcom-Bravo Please check now.

**Comment by engcom-Bravo** [comment] 2019-07-24 12:23
Thank You @pandyakrunal. Unfortunately we've been not able to reproduce Your issue on a clear magento installation. Could You please try to reproduce it Yourself on such an installation. For that just leave a comment as You are advised above:
![Advised](https://user-images.githubusercontent.com/51680745/61793040-d5c5a180-ae26-11e9-87a4-7ae06711e0fa.png)

Thank You.

**Comment by pandyakrunal** [comment] 2019-07-26 09:14
Some time its work and some time it throws Network error when download.

**Comment by engcom-Bravo** [comment] 2019-07-26 09:58
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-26 09:58
Hi @engcom-Bravo. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-26 09:58
Hi @engcom-Bravo, here is your [Magento instance](https://i-23855-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23855-2-3-develop.instances.magento-community.engineering/admin](https://i-23855-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment] 2019-07-26 10:15
@pandyakrunal, please enter the above instance where we created an order and processed it to Complete status. Then we printed the invoice and here is what we successfully got:
[invoice2019-07-26_10-03-13.pdf](https://github.com/magento/magento2/files/3435266/invoice2019-07-26_10-03-13.pdf)
You can try to do it Yourself.
Thus we cannot confirm this issue as a Magento's core bug, and so we are supposed to close it. But if You find the way we can reproduce it on a vanilla instance please feel free to reopen it and explain us that. Thanks for applying.

**Closed as completed by engcom-Bravo** 2019-07-26 10:15 UTC
Labels: Progress: needs update, Issue: Format is valid

**Comment by pandyakrunal** [comment] 2019-07-26 10:20
Yes, I check it is work. Is this version is 2.3.2?

**Comment by engcom-Bravo** [comment] 2019-07-26 10:30
@magento give me 2.3.2 instance

**Comment by magento-engcom-team** [comment] 2019-07-26 10:30
Hi @engcom-Bravo. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by magento-engcom-team** [comment] 2019-07-26 10:31
Hi @engcom-Bravo, here is your [Magento instance](https://i-23855-2-3-2.instances.magento-community.engineering).
Admin access: [https://i-23855-2-3-2.instances.magento-community.engineering/admin](https://i-23855-2-3-2.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by pandyakrunal** [comment] 2019-07-26 10:33
Ok, thank you for your support.

**Comment by engcom-Bravo** [comment] 2019-07-26 10:37
You are welcome @pandyakrunal. The last instance is exactly of 2.3.2 version. Unfortunately the result is the same as You may see.
