### ISSUE TITLE
Braintree Settlement Report show error

### ISSUE THREAD

**Issue by anhnhan1997** [magento/magento2#33119] opened 2021-06-02 04:13 UTC
### Preconditions (*)

1. Error when go to the "Braintree Settlement Report"

### Steps to reproduce (*)

1. Go to the Admin -> Report -> Sales - > Braintree Settlement
![2222](https://user-images.githubusercontent.com/57820879/120422600-cc96ab80-c392-11eb-8615-2f48476e589b.png)

2. Click on the  Braintree Settlement -> the grid will show this error 
![image](https://user-images.githubusercontent.com/57820879/120422668-f4860f00-c392-11eb-9e3a-fd3e1b0c3560.png)

### Expected result (*)

1. In Magento 2.4.2 p1
2. I expected the grid will show without error

### Actual result (*)

1. The grid show error :  "Call to undefined method "PayPal\Braintree\Model\Report\TransactionsCollection\Interceptor::getSelect() ![image](https://user-images.githubusercontent.com/57820879/120422668-f4860f00-c392-11eb-9e3a-fd3e1b0c3560.png)
2. 
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by salman231** [comment] 2021-06-18 12:08
Facing this issue in Magento EE 2.4.2 also. Hoping to get this fix from Magento asap.

**Comment by engcom-Delta** [comment] 2021-06-25 12:41
Hi @anhnhan1997,

Issue has been verified and found that it is reproducible .Hence added the label 'Issue confirmed'.
Steps followed:
Installing Braintree module from command line:
1. Ensure you the Magento MarketPlace repository listed in your composer.json file (typically https://repo.magento.com)
2. Update composer to require the "gene/module-braintree" package with the command: $ composer require gene/module-Braintree ^3.0.6
3. To enable the module, run the command: $ bin/magento module:enable Magento_Braintree 
4. Then run setup:upgrade to install the necessary updates, with the command: $ bin/magento setup:upgrade
5. If a production environment - re deploy the static content and run the di compiler
6. Restart servers and reindex. Re login to application
( Link - https://marketplace.magento.com/media/catalog/product/paypal-module-braintree-4-0-7-ce/installation_guides.pdf )
7. Click on Reports--> Select Braintree
8. Observe that displayed error.

Please refer the attached snapshot for reference.
![braintree](https://user-images.githubusercontent.com/51681379/123426244-cb971980-d5e0-11eb-9d07-69de746a91ee.jpg)

**Comment by magento-engcom-team** [comment] 2021-06-25 12:44
@engcom-Delta Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-06-25 12:44
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-06-25 12:51
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42732` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment] 2021-06-29 11:11
Closing this one as a duplicate of https://github.com/magento/magento2/issues/32292.

**Closed as completed by gabrieldagama** 2021-06-29 11:11 UTC
Labels: Issue: Confirmed, Component: Reports, Reproduced on 2.4.x, Progress: done, Reported on 2.4.x
