### ISSUE TITLE
Problem of displaying configurable product page and allocated store different.

### ISSUE THREAD

**Issue by HarmonyDumas** [magento/magento2#34581] opened 2021-11-08 16:20 UTC
### Preconditions (*)
Following the update of magento 2.4.3.
We have a configurable product.
Some categories on some countries, went up empty on our site. We understood that this problem was due to the configurable product.

### Steps to reproduce (*)
On my configurable form I have 3 simple products open on 10 Stores.
On one of the 3 simple products, I do not have the same number of open Store because some products are not marketed on this store. To correct the problem I had to open the store on the simple product page in question and then put it in disable. 

### Actual result (*)
The problem is that by doing this in the category I see in the quantity selector of the configurable product my 3rd product appear. It is not purchasable but appears.

Would it be possible to fix this problem?

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by jonathanribas** [comment] 2021-11-29 06:12
Hi @engcom-Hotel, any update on this issue please?

**Comment by engcom-November** [comment] 2021-11-29 12:33
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue:
Created a Configurable Product with multiple Attribute sets (Simple Products) assigned to multiple Categories and Store views.
Front-end - Viewed the Product with different Attribute combinations on all store views - No issue. User is able to select and add product to cArt.
@jonathanribas Kindly recheck the issue on Magento 2.4-develop branch as it has the latest code base and elaborate steps to reproduce the issue is you are still facing issues.
Thank you.

**Comment by jonathanribas** [comment] 2021-12-04 08:17
Hi @engcom-Hotel,
Actually, one of the simple product is not available for one of the stores, we don't want to sell it on a particular store.
Can you verify this case please?

**Comment by engcom-November** [comment] 2021-12-10 11:39
Verified again on 2.4-develop branch having multiple Store views with below steps performed but cannot able to reproduce the issue:
Created a simple product and assigned to only one Store (Main Store view). Visibility set to - Catalog Search. Product is visible on Main website front end and not visible on other Stores.
Created Configurable Product with multiple Simple product variations along with above simple product created. 
Configurable product is assigned to all Store views.
Store-front - Searched for Configurable Product in all Stores - No issue. 
User is able to navigate to Product Details page and add to Cart. - No issue
@jonathanribas , kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2021-12-23 12:22
Hi @jonathanribas ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-12-23 12:22 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
