### ISSUE TITLE
Uncaught TypeError: Event.observe is not a function in admin review edit page

### ISSUE THREAD

**Issue by lng50k** [magento/magento2#30388] opened 2020-10-09 18:14 UTC
Preconditions
1. Magento 2.4.0
2. Mac OS High Sierra Environment

Steps to reproduce
1. Login to admin
2. Go to menu Marketing -> All Reivews
3. Try to edit any order

Expected result
1.  Working review edit

Actual result
1. JS console error - Uncaught TypeError: Event.observe is not a function
2. Styles are broken
3. Changing status and saving is working though

Screenshots attached
![Screen Shot 2020-10-10 at 4 13 49 AM](https://user-images.githubusercontent.com/41349031/95617599-0850ce00-0aaf-11eb-9bb6-532d8893c321.png)

![Screen Shot 2020-10-10 at 4 14 14 AM](https://user-images.githubusercontent.com/41349031/95617646-1bfc3480-0aaf-11eb-826a-609606558f1e.png)

**Comment by krishprakash** [comment] 2020-10-10 04:16
#dmcdindia2020

**Comment by krishprakash** [comment] 2020-10-10 04:17
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment] 2020-10-10 04:41
Hi @lng50k. Looks like console error shows for other OS/browsers as well.

![image](https://user-images.githubusercontent.com/46617848/95645730-95ac1680-0adf-11eb-86dd-e5281e555cc3.png)

**Comment by magento-engcom-team** [comment] 2020-10-10 04:43
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38330` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sunilit42** [comment] 2020-10-10 07:07
#dmcdindia2020

**Comment by sunilit42** [comment] 2020-10-10 07:08
@magento I am working on this

**Comment by magento-engcom-team** [comment] 2020-10-24 10:35
Hi @lng50k. Thank you for your report. 
The issue has been fixed in magento/magento2#30402 by @sunilit42 in 2.4-develop branch
Related commit(s):
 - [af2d29a16e8b7bc30a872d9e20914bdae5b24111](https://github.com/magento/magento2/commit/af2d29a16e8b7bc30a872d9e20914bdae5b24111)
 - [e08499bd5083956ac807c4bd93354714bc9005f7](https://github.com/magento/magento2/commit/e08499bd5083956ac807c4bd93354714bc9005f7)
 - [a4be3e0e51eae4f8d9ebc4c8b9c833ef656aa779](https://github.com/magento/magento2/commit/a4be3e0e51eae4f8d9ebc4c8b9c833ef656aa779)
 - [a88f5808e69a3823645988cb0a6e3f91fc682272](https://github.com/magento/magento2/commit/a88f5808e69a3823645988cb0a6e3f91fc682272)
 - [7ea472187a74f57588ea5945646cadd356e9da95](https://github.com/magento/magento2/commit/7ea472187a74f57588ea5945646cadd356e9da95)

The fix will be available with the upcoming 2.4.2 release.

**Closed as completed by magento-engcom-team** 2020-10-24 10:35 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Component: Review, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P3, Severity: S3, Progress: done, Event: dmcdindia2020, Event: MageCONF CD 2020, Reported on 2.4.0
