### ISSUE TITLE
Regression for #14849 - frontend_status_label not translated in email templates

### ISSUE THREAD

**Issue by YiffyToys** [magento/magento2#35496] opened 2022-05-18 15:39 UTC
### Preconditions and environment

2.4.3-p2

### Steps to reproduce

Use {{var order_data.frontend_status_label}} in email template because {{var $order.getFrontendStatusLabel(}} as a workaround from #14849 is a function call and thus no longer allowed in 2.4.3-p2 .

Trigger a status change email from a German Admin-UI to an English customer.

### Expected result

oder_data.frontend_status_label  in the english email is in English

### Actual result

oder_data.frontend_status_label  in the english email is in German

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-07-21 09:53
Hi @YiffyToys ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch and I can see "order_status" value as $order_data.frontend_status_label for "Order Update" email template.
![image](https://user-images.githubusercontent.com/60198231/180185368-72102cc9-de61-4265-9b52-4bab6cf3f7e8.png)
Kindly recheck the issue on Magento 2.4-develop branch and elaborate the steps to reproduce if you are still facing any issues.
Thank you.

**Comment by YiffyToys** [comment] 2022-07-21 10:23
Did you read the issue?
Yes, it now has to be "$order_data.frontend_status_label" in the template again. That is the problem. It means the workaround in issue #14849 can not be applied anymore.
But "$order_data.frontend_status_label"  is not translated.
See the linked issue #14849 about steps to reproduce the missing translation.


Template:
```
<p style="font-size:12px; line-height:16px; margin:0 0 10px 0;">
                        your order #YT{{var order.increment_id}} is now in status <br/>
                        <strong>{{var order_data.frontend_status_label}}</strong>.
                    </p>
```

Output is in German for an ENGLISH email :
![grafik](https://user-images.githubusercontent.com/52350973/180191525-f57b6b6a-3d68-4d17-ac25-fbb2b819548b.png)

**Comment by engcom-November** [comment] 2022-07-27 12:59
Hi @YiffyToys ,
Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue with below steps followed:
1. Stores - Settings - Order status - like below
![image](https://user-images.githubusercontent.com/60198231/181251531-066543c9-d8ef-4111-af85-98757755aa26.png)
2. Created orders in both the stores - Main website and german site
3. Changed order status for both the orders in admin - Emails triggered in respective language with expected order status:
![image](https://user-images.githubusercontent.com/60198231/181252457-90778041-3009-43ce-ba61-b02ecb4e4a8c.png)
![image](https://user-images.githubusercontent.com/60198231/181252533-38209284-d22b-4d76-a1c7-e0028a331dc8.png)

![image](https://user-images.githubusercontent.com/60198231/181252310-d783cb3e-17c1-420a-bc00-ef1195b902d1.png)
![image](https://user-images.githubusercontent.com/60198231/181252351-e88ab69c-b538-4c7f-bc69-2c110eddbbca.png)
Kindly recheck the issue on Magento 2.4-develop branch as it is the latest code base and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by YiffyToys** [comment] 2022-07-27 13:05
Thanks. 
We'll check again with 2.4.4 when there is a Debian package of OpenSearch and all our plugins support PHP8.1.

**Comment by engcom-November** [comment] 2022-08-10 06:16
Hi @YiffyToys ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-08-10 06:16 UTC
Labels: Issue:  Cannot Reproduce, Triage: Dev.Experience, Issue: needs update
