### ISSUE TITLE
Saving a CMS page with parentheses in the SEO meta data fields results in 404 error.

### ISSUE THREAD

**Issue by RobotsPlay** [magento/magento2#6529] opened 2016-09-07 21:15 UTC
When trying to add a meta description to a CMS page, if the input includes `()` characters, the result is a 404 error.

The following post request returns 404: 

`/admin/cms/page/save/key/xxx...xxxx/back/edit`

### Preconditions

1. Magento CE 2.1.0
### Steps to reproduce

1. Create or Edit a CMS page and enter a string with `()` in it.
2. Click Save
### Expected result

1. The page saves and the meta fields are saved.
### Actual result

1. The form post returns 404 and a 404 message appears on screen.

**Comment by sevos1984** [comment] 2016-09-09 08:01
Cannot reproduce in 2.1.1, have you tried updating your code to the latest version?

**Comment by sevos1984** [comment] 2016-09-26 12:14
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-09-26 12:14 UTC
Labels: bug report, Progress: needs update, Component: Cms
