### ISSUE TITLE
Internal Server Error in FedEx Model/Carrier

### ISSUE THREAD

**Issue by jhbowser** [magento/magento2#7670] opened 2016-12-02 23:29 UTC
### Preconditions

1. Magento Community 2.1.2
2. PHP 5.6

### Steps to reproduce

1. FedEx Shipping is enabled
2. Get error obtaining FedEx Shipping rates
3. Happens often but not every time.

### Expected result

1. 

### Actual result
Stack trace:

[2016-12-02 18:05:26] main.CRITICAL: SoapFault exception: [soapenv:Server] Internal Server Error in vendor/magento/module-fedex/Model/Carrier.php:492
Stack trace:
#0 /var/www/vhosts/shop9round.com/httpdocs/vendor/magento/module-fedex/Model/Carrier.php(492): SoapClient->__call('getRates', Array)
#1 /var/www/vhosts/shop9round.com/httpdocs/vendor/magento/module-fedex/Model/Carrier.php(492): SoapClient->getRates(Array)
#2 /var/www/vhosts/shop9round.com/httpdocs/vendor/magento/module-fedex/Model/Carrier.php(526): Magento\Fedex\Model\Carrier->_doRatesRequest('general')
#3 /var/www/vhosts/shop9round.com/httpdocs/vendor/magento/module-fedex/Model/Carrier.php(274): Magento\Fedex\Model\Carrier->_getQuotes()
#4 /var/www/vhosts/shop9round.com/httpdocs/vendor/magento/module-shipping/Model/Shipping.php(293): Magento\Fedex\Model\Carrier->collectRates(Object(Magento\Quote\Model\Quote\Address\RateRequest))
#5 /var/www/vhosts/shop9round.com/httpdocs/vendor/magento/module-shipping/Model/Shipping.php(209): Magento\Shipping\Model\Shipping->collectCarrierRates('fedex', Object(Magento\Quote\Model\Quote\Address\RateRequest))

**Comment by YevSent** [comment] 2016-12-05 08:11
Hi, @jhbowser.

You need to wrap soap call into `try and catch` construction to find a reason of your error. This can be done in the follows way:

```php
$client = new \SoapClient($wsdl, ['trace' => true]);
try {
    // use client to call soap method
} catch (\SoapFault $e) {
    // handle exception message
}
```

This construction allows to do next two things:

1. You can get exception message -> `$e->getMessage()` and exception details `$e->detail`.
2. The trace option allows seeing details of your `$client` request. For example, if you use `xdebug` and set break point in the catch block, you can get request and response details: `$client->__last_request` and `$client->__last_response`, which allow you to find reason of your problem.

**Comment by jhbowser** [comment] 2016-12-08 22:36
This is in Magento core code, already within an try-catch block.
vendor\magento\module-fedex\Model\Carrier.php
try {
                $client = $this->_createRateSoapClient();
                $response = $client->getRates($ratesRequest);
                $this->_setCachedQuotes($requestString, serialize($response));
                $debugData['result'] = $response;
            } catch (\Exception $e) {
                $debugData['result'] = ['error' => $e->getMessage(), 'code' => $e->getCode()];
                $this->_logger->critical($e);
            }
I enabled debug and got this:

  'result' =>
  array (
    'error' => 'Internal Server Error',
    'code' => 0,
  ),
) {"is_exception":false} []

The request is also in the debug.log Nothing unusual about it that I see.
There is no response due to the exception.

**Comment by YevSent** [comment] 2016-12-09 08:15
Yes, but this code doesn't catch soap exceptions, that's why I wrote options for `SoapClient`.

**Comment by YevSent** [comment] 2016-12-26 09:50
We are closing this issue because it hasn’t been updated in more than two weeks.

If you still can reproduce the issue, please, be free to reopen it.

**Closed as completed by YevSent** 2016-12-26 09:50 UTC
Labels: bug report, Progress: needs update, Component: Shipping

**Comment by twistedatrocity** [comment] 2017-02-26 05:53
I'm getting the exact same error. Fedex is only carrier enabled.
Magento CE 2.1.4
PHP 7.0.15
CENTOS 6

from debug.log:
```
[2017-02-26 05:44:37] main.CRITICAL: SoapFault exception: [SOAP-ENV:Server] Fault in /magento2/vendor/magento/module-fedex/Model/Carrier.php:492
Stack trace:
#0 /magento2/vendor/magento/module-fedex/Model/Carrier.php(492): SoapClient->__call('getRates', Array)
#1 /magento2/vendor/magento/module-fedex/Model/Carrier.php(526): Magento\Fedex\Model\Carrier->_doRatesRequest('general')
#2 /magento2/vendor/magento/module-fedex/Model/Carrier.php(274): Magento\Fedex\Model\Carrier->_getQuotes()
#3 /magento2/vendor/magento/module-shipping/Model/Shipping.php(293): Magento\Fedex\Model\Carrier->collectRates(Object(Magento\Quote\Model\Quote\Address\RateRequest))
#4 /magento2/vendor/magento/module-shipping/Model/Shipping.php(209): Magento\Shipping\Model\Shipping->collectCarrierRates('fedex', Object(Magento\Quote\Model\Quote\Address\RateRequest))
#5 /magento2/vendor/magento/module-quote/Model/Quote/Address.php(995): Magento\Shipping\Model\Shipping->collectRates(Object(Magento\Quote\Model\Quote\Address\RateRequest))
#6 /magento2/vendor/magento/module-quote/Model/Quote/Address.php(936): Magento\Quote\Model\Quote\Address->requestShippingRates()
#7 /magento2/vendor/magento/module-quote/Model/Quote/Address/Total/Shipping.php(161): Magento\Quote\Model\Quote\Address->collectShippingRates()
#8 /magento2/vendor/magento/module-quote/Model/Quote/TotalsCollector.php(265): Magento\Quote\Model\Quote\Address\Total\Shipping->collect(Object(Magento\Quote\Model\Quote), Object(Magento\Quote\Model\ShippingAssignment), Object(Magento\Quote\Model\Quote\Address\Total))
#9 /magento2/vendor/magento/module-quote/Model/ShippingMethodManagement.php(273): Magento\Quote\Model\Quote\TotalsCollector->collectAddressTotals(Object(Magento\Quote\Model\Quote), Object(Magento\Quote\Model\Quote\Address))
#10 /magento2/vendor/magento/module-quote/Model/ShippingMethodManagement.php(213): Magento\Quote\Model\ShippingMethodManagement->getShippingMethods(Object(Magento\Quote\Model\Quote), Array)
#11 /magento2/vendor/magento/module-quote/Model/GuestCart/GuestShippingMethodManagement.php(103): Magento\Quote\Model\ShippingMethodManagement->estimateByExtendedAddress(18367, Object(Magento\Quote\Model\Quote\Address))
#12 [internal function]: Magento\Quote\Model\GuestCart\GuestShippingMethodManagement->estimateByExtendedAddress('2a661b1ac240e3f...', Object(Magento\Quote\Model\Quote\Address))
#13 /magento2/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)
#14 /magento2/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()
#15 /magento2/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#16 /magento2/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /magento2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#18 /magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#19 {main} [] []
```

no other errors in logs.

**Comment by twistedatrocity** [comment] 2017-02-27 18:32
@joni-jones 
sorry above was from exception log. Here is debug.log:

```
  'result' => 
  stdClass::__set_state(array(
     'HighestSeverity' => 'ERROR',
     'Notifications' => 
    stdClass::__set_state(array(
       'Severity' => 'ERROR',
       'Source' => 'crs',
       'Code' => '803',
       'Message' => 'Meter number is missing or invalid.  ',
       'LocalizedMessage' => 'Meter number is missing or invalid.  ',
    )),
     'Version' => 
    stdClass::__set_state(array(
       'ServiceId' => 'crs',
       'Major' => 10,
       'Intermediate' => 0,
       'Minor' => 0,
    )),
  )),
) {"is_exception":false} []
```

Hard to tell if meter number is correct due to it being hashed in the database. However I used the data migration tool to bring in the settings from M1 store.  It is sending "****" as the meter number. It is sending the proper account number however.

```'
MeterNumber' => '****',
```

Doing the same for account credentials:

```
    array (
      'UserCredential' => 
      array (
        'Key' => '****',
        'Password' => '****',
      ),
```
Unsure if this is what it's really sending to fedex or if it's trying to mask them for debug logs. I would think it would not mask them for debugging.

I input the proper values manually and saved in the Fedex Shipping method of store config. Retested and I am getting the same issue.

It seems there is a bug in this module as it is sending exactly 4 stars for Key, Password, and Meter number, at least according to the debug log.

This is a fresh vanilla install with no extensions. Data migration import of settings and products, and now with manual save of fedex credentials.

**Comment by twistedatrocity** [comment] 2017-02-27 19:06
It is masking for debug log... stupid. Commented this out:

```
    protected function filterDebugData($data)
    {
        /*foreach (array_keys($data) as $key) {
            if (is_array($data[$key])) {
                $data[$key] = $this->filterDebugData($data[$key]);
            } elseif (in_array($key, $this->_debugReplacePrivateDataKeys)) {
                $data[$key] = self::DEBUG_KEYS_MASK;
            }
        }*/
        return $data;
    }
```

Logs appear to be sending correct values yet it is still failing with Invalid or Missing Meter number and throwing a soap exception.

The credentials and meter number are correct as the same is being used and were taken from a live functioning M1 store.

**Comment by twistedatrocity** [comment] 2017-02-27 20:30
Further testing reveals this is an issue with data migration tool.
