### ISSUE TITLE
Creditmemo not possible if Total Amount was 0

### ISSUE THREAD

**Issue by chequille** [magento/magento2#34294] opened 2021-10-11 05:12 UTC
### Preconditions (*)

1. Magento Version 2.4.3
2.

### Steps to reproduce (*)

1. Create a discount rule with 100%
2. Enable free shipping
3. Place an order with the discount and choose free shipping
4. Total amount is 0
5. Create Shipping and Invoice
6. Order is going to status closed
7. Creditmemo is not possible

### Expected result (*)

1. Even if there was a 100% discount on the order, it should be possible to create a creditmemo, as the customer does have the right to give back to product. It must be possible to get back the product and having the creditmemo on the invoice 
2.

### Actual result (*)

1. Order is going to status closed and creditmemo is not possibe anymore
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment] 2021-10-12 08:02
Hi @chequille,
I have verified this issue on the latest Magento version. Once I have place an order and generate the Invoice and Shipment the order status is showing "Complete" instead of "Close". 
After generating the Invoice and Shipment, Admin can generate the Credit memo.

**The issue is not getting and it's working as expected.**

**See attached the screenshot:**

![image](https://user-images.githubusercontent.com/24711761/136909572-05ce06c6-5904-4ff8-9677-afbd8d1444dc.png)

![image](https://user-images.githubusercontent.com/24711761/136916023-3cae1ce7-8472-44e8-a262-63ff1785366c.png)

![image](https://user-images.githubusercontent.com/24711761/136915794-0a66d5ea-7121-4cfd-8531-573956619629.png)

![image](https://user-images.githubusercontent.com/24711761/136915834-e3778a1e-72b3-490f-8626-2cda3c1c995c.png)

![image](https://user-images.githubusercontent.com/24711761/136915998-2765eeb2-9be2-42de-9228-968452424a00.png)

Thanks

**Comment by chequille** [comment] 2021-10-13 05:27
@ajijshekh123 
morning
I tried to reproduce it, but the settings of the standard instance differ at so many points compared with my shop which is set to use in Germany.
As well, there are some modules installed taking care of German and EU law, which are not installed here in the instance.
Maybe the only way for my shop would be to know, where Magento decides to disable the credit memo button and setting status to closed. If I would know this, I may develop a plugin for it to handle it as I need it.
But I have no idea where this is done.
Maybe you can help me.
Best regards,
Jürgen

**Comment by ajijshekh123** [comment] 2021-10-14 14:22
Okay @chequille, I will verify this issue ASAP and Update it here.

**Comment by chequille** [comment] 2021-10-17 13:36
Hi @ajijshekh123,

I believe I found the problem. It is alittle bit tricky to setup a new shop to rperoduce it, as my shop is a german shop with some special things. But I can describe when it happens and when it is working.
Some explanations: we do have two different tax rates in germany, 19% and 7%.
THese rates are valid all over germany and they do not depend on regions or states as it is in the US.
There are products with 7% tax and there are products with 19% tax.
Below a screenshot from my tax rules
![grafik](https://user-images.githubusercontent.com/15807794/137629179-96455cda-6cc6-4b7b-b4bb-0bbf2e8c4547.png)
What I found is, if an order does contain only products with 7% tax (the frist entry in the rules list), I can create a creditmemo if doing it like above with discount and free shipping.
If the order contains a product with 19% tax, creditmemo is not possible anymore as after invoicing the order state is going to closed.

Because of this, you could not reproduce it as the demo shop of an instance is set to US and all products are non tabable.

Therefore, I would like to know the part of the code which is setting the order state after invoicing. It seems for me, that there will be the error.

Do you know where it is done and could you let me know so I can have a look into it?
Regards,
Chequille

**Comment by chequille** [comment] 2021-10-17 21:26
Additional info:
in model Magento\Sales\Model\ResourceModel\Order\Handler\State the state of the order is checked and set.
WIthin this check, there is a function canCreditmemo() which is called and in case of this function returning false status is set to Closed
This canCreditmemo function is defined in Magento\Sales\Model\Order
Why it is returning false in case of an order having a product with the 19% tax I have no idea. It is returning true if the order contains only products with 7% tax.
So far my insvestigations. I hope somebody does have an idea why this happens and how to fix it.

Regards
Chequille

**Comment by simonmaass** [comment] 2021-11-18 17:08
We also have a german magento 2.4.3 shop and i can confirm the same issue

**Comment by chequille** [comment] 2021-11-18 18:52
@simonmaass 
Thank you very much for this.
Maybe this helps, we are now two having this issue.

**Comment by engcom-Hotel** [comment] 2022-01-07 06:26
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-01-07 13:02
Hello @chequille @simonmaass,

We have tried to reproduce the issue in Magento 2.4-develop branch but for us, it is not reproducible. Please have a look at our configuration below:

1. Tax Rule:
![image](https://user-images.githubusercontent.com/51681618/148546979-c9d0502c-8fd1-4a38-b7e9-8076eacc96de.png)

2. Discount Rule:
![image](https://user-images.githubusercontent.com/51681618/148547071-eca355a4-146c-44e6-a400-df0ebf77ec5c.png)

3. Product:
![image](https://user-images.githubusercontent.com/51681618/148547128-17cb0784-0de1-46f4-bb11-5f602b64f3a8.png)

4. Tax Configuration in Stores->Configuration ->Sales->Tax:
a. Calculation Settings:
![image](https://user-images.githubusercontent.com/51681618/148547239-c59260cc-6377-45f5-8c02-f45dd93dfaf4.png)

b. Default Tax Destination Calculation:
![image](https://user-images.githubusercontent.com/51681618/148547304-7b0604e6-4289-427f-89b7-ff481e6a3a78.png)

5. After creating shipment and invoice of order, we can create credit memo for the same:
![image](https://user-images.githubusercontent.com/51681618/148547456-975c47f4-2216-4e3d-bf09-2c5810a96d03.png)

Please let us know if we have missed anything.

Thanks

**Comment by simonmaass** [comment] 2022-01-07 16:22
@engcom-Hotel could you please show a screenshot from the order?

you have to admit, that a refund of the grand total of 19€ makes absolutely no sense if the order total was 0€

**Comment by chequille** [comment] 2022-01-07 23:18
@engcom-Hotel 
Question: The product you choosed for the order, which tax does it have?
If it has the VAT-Standard, then please try to make the same with a the product having the VAT-Reduced Tax

As I said in my comments before, it only happens with one of the two defined tax classes.
![grafik](https://user-images.githubusercontent.com/15807794/148619149-925475e6-d692-4332-bfae-d587e9838d23.png)

In my shop I can do the credit memo when the product does have the 7% Tax, but not when I am using the second defined tax class 19%

If you do not try this, you cannot reproduce the bug I and Simonmaass are reporting.

Best regards,
CHequille

**Comment by chequille** [comment] 2022-01-07 23:24
Just saw, that your product was set to use VAT-Standard. Therefore, you have to try it with a product having the VAT-Reduced. You (hopefully) will see, that this order cannot be credited.

As well your refund is not correct as Simonmaas said before.

**Comment by chequille** [comment] 2022-01-08 08:58
Hi Everybody,
as I made as well a few new tests regarding this issue, I found a new situation and it is strange.

Whether the order is going to closed or completed depends on the price value of the product.

I made an order with a product having a price (incl. 19% tax) of 17,40€ and this order is going to closed after I made the invoice.
I made another order with a product having a price (incl. 19% tax) of 9,90€ and this order is going to completed after I made the invoice, which is the correct behaviour.

So, I think that there is somewhere a rounding problem of float vlaues which causes this problem.
Unfortunately, I did not find yet the point in the code where the status of the order is set, but I guess within this procedure the fault can be found.

Do you know where status is set after invoice is made? 

Best regards,
Chequile

**Comment by engcom-Hotel** [comment] 2022-01-10 10:07
@chequille 

Below I have tried with the product price with 17,40€, please have a look at checkout page:

![image](https://user-images.githubusercontent.com/51681618/148747998-f1cb4234-d4d8-4b69-9d53-5e12498e9e97.png)

I can create the credit memo for this as well. As you mentioned in the main description, we need to enable free shipping, do we need to follow this here as well.

Thanks

**Comment by chequille** [comment] 2022-01-10 18:54
Yes, you must add free shipping and as well a coupon code. Order Total must be 0.00€

**Comment by engcom-Hotel** [comment] 2022-01-17 09:43
Hello @chequille,

We have tried to reproduce the issue again but we are unable to get the order total as 0. Maybe we have different tax calculations, below are the screenshots for the same:

**Checkout Page**
![image](https://user-images.githubusercontent.com/51681618/149745768-6289fb20-66fc-45d2-92ac-4c43ff8e771c.png)

**Tax Calculation Settings**
![image](https://user-images.githubusercontent.com/51681618/149745841-02231c57-2143-4c5b-b04a-140d9208e4b2.png)

Do we need to make any changes to it? Please let us know.

Thanks

**Comment by chequille** [comment] 2022-01-17 21:57
Hi @engcom-Hotel,

sorry, but this is now a completly different bug. 
Where is the 3,31€ coming from?
Sorry, product is €17,40, discount is €17,40
With my calculator 17,40 -17,40 is ZERO

We do not have to go one if the order is wrong as it is above in your example.
But, to answer your question: the settings are the same in my setup.

BR
Chequille

**Comment by engcom-Hotel** [comment] 2022-01-31 08:58
Hello @chequille,

In that case, can we edit the main description with the bug I have encountered? Because we are not able to reproduce the issue you have mentioned.

Or please tell us if missed anything in order to reproduce the issue.

Thanks

**Comment by chequille** [comment] 2022-01-31 18:54
Hello @engcom-Hotel,
I do not understand what you are talking about.
I said in my last comment, that the order you made is completly wrong. There is already the bug that your order does have a total of 3.35€, because it should have a total of 0€
Therefore it is clear, that you cannot reproduce my issue.
In my point of view you have first to find why your order is NOT ZERO !!!!

Best regards,
Jürgen

**Comment by engcom-Hotel** [comment] 2022-02-02 09:03
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-02-02 11:48
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-02-21 06:15
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-02-21 06:48
@magento give me 2.4-develop instance

**Comment by slavvka** [comment] 2022-02-22 20:07
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-02-25 09:45
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-03-04 12:34
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue due to below issue:
https://github.com/magento/magento2/issues/35162.
Unable to place order with above configuration as order amount is always becoming negative value.
Steps performed:
Create Cart Price Rule with Action "Fixed amount discount for Whole Cart" and amount $100
Stores - Settings - Configuration - Sales - Tax - Calculation Settings - 'Apply Customer Tax' Set to "After Discount", Apply 'Discount On Prices' - "Including Tax" - Save Config
Default Tax Destination Calculation - Germany
Stores - Settings - Configuration - Sales - Shipping Methods - Enable Free Shipping
Created 2 tax rules - Germany 19% and 7% with 2 different tax classes
Reindex and clear cache
Create Products assigned to 2 different tax classes - whole cart value is < 100 . (Ex: Created product with amount $17.40. assigned to 19% tax rate)
Front-end Login as Customer - Add Product to Cart
Ship to Germany Address, Apply Discount - Payment Step
![image](https://user-images.githubusercontent.com/60198231/156764109-f28f6c60-731a-4039-b18e-2a681e0d6f3c.png)

**Comment by engcom-November** [comment] 2022-03-23 11:53
We are moving this ticket to on hold as this is dependent on https://github.com/magento/magento2/issues/35162 to reproduce. This needs to be verified once #35162 is fixed.

**Comment by engcom-Hotel** [comment] 2022-06-01 12:58
Hello @engcom-November,

I can see the JIRA related to #35162 has been done. You can continue with this ticket.

Thanks

**Comment by engcom-November** [comment] 2022-06-02 15:44
Related JIRA of https://github.com/magento/magento2/issues/35162 was closed as not a bug due to incorrect tax configuration from admin which is applicable to this issue as well. We cannot reproduce this issue without this particular tax configuration for valid tax [combinations](https://docs.magento.com/user-guide/tax/warning-messages.html) this issue is not reproducible.

**Closed as completed** 2022-06-21 15:00 UTC
Labels: Component: Admin, Component: order status, Issue: needs update, Reported on 2.4.3, Area: Order

**Comment by simonmaass** [comment] 2022-06-21 20:52
Also running magento in Germany and absolutely agree @chequille
