### ISSUE TITLE
Magento 2.1.3 Currency Converted Incorrectly

### ISSUE THREAD

**Issue by w130pmpo** [magento/magento2#7941] opened 2016-12-22 22:02 UTC
### Preconditions

1. Magento 2.1.3 Installed
2. Create EN, CN Store View
3. Base Currency US Dollar
4. EN Store Default Display US Dollar
5. CN Store Default Display CN Yuan
6. Allowed Currency for Both is US Dollar and CN Yuan
7. Create Configurable Product and priced $100 (for example) 
8. Import Currency Rate

### Steps to reproduce

1. Go to EN store view with US currency (Front-end)
2. Go to detail page of Product that you you created (Configurable) (Front-end)
3. You will see correct price as $100
4. Change Storeview or Currency to CN using switcher at top-link

### Expected result

1. System should one-time convert Original US price to CN Yuan 
2. For this case, Should be around CNY 600 

### Actual result

1. System convert two-time Original US price to CN yuan
2. For this case, it displays CNY 3600, which means it converts once and then it converts again with result of first converted price. US 100 -> CNY 600 -> CNY 3600

**Comment by erfanimani** [comment] 2016-12-23 17:18
@w130pmpo duplicate of #7371  (and #7712 & #7941)

**Comment by veloraven** [comment] 2016-12-26 15:30
@w130pmpo thank you for your report.
I have created internal ticket MAGETWO-62682 for this issue

**Comment by erfanimani** [comment] 2016-12-28 12:37
Any ETA on this one? It actually prevents stores from using configurable products in combination with multi currency..

**Comment by dthampy** [comment] 2017-01-13 05:22
closing this as a duplicate of #7371 which was reported much earlier.

**Closed as completed by dthampy** 2017-01-13 05:22 UTC
Labels: Issue: Ready for Work, bug report, Component: Tax
