### ISSUE TITLE
bundle product keep out of stock

### ISSUE THREAD

**Issue by wingsoul** [magento/magento2#9402] opened 2017-04-26 02:08 UTC
Hi all,
In these few days, I have tested magento2 bundle product function in a multi-site magento2.
However, there is a problem.

First, I have two sites which are TW and US.
I followed the document in magento website for setting up a test bundle product.
http://docs.magento.com/m2/ce/user_guide/catalog/product-create-bundle.html

I am able to find that product in TW but not in US.
And then I directly accessed that product page, I found It is out of stock.
But I have set as in stock.
![1](https://cloud.githubusercontent.com/assets/3104634/25415107/3897ec54-2a68-11e7-91c5-cbe0b5353d8f.png)

Please give me some advices
Thank you

**Comment by korostii** [comment] 2017-04-26 09:04
If you are looking for some help or an advice regarding setup or configuration please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.

**Comment by El-Rico** [comment] 2017-07-13 18:56
Looks like a bug to me... If not... it's a usability bug, because I can't find a fix.

**Comment by magento-engcom-team** [comment] 2017-09-22 10:31
@wingsoul Closing per comment @korostii. If you think this is a bug in Magento 2 Core please reopen and edit issue description to include the preconditions, the steps required to reproduce, the actual result, and the expected result.

Thank you

**Closed as completed by magento-engcom-team** 2017-09-22 10:31 UTC
Labels: Issue: Format is not valid
