### ISSUE TITLE
2.0.0RC issue: "Storage Configuration For Media" set as database causes product image serving to fail

### ISSUE THREAD

**Issue by matthewwiggins** [magento/magento2#2277] opened 2015-11-06 12:22 UTC
Found this issue when testing for a potential deploy. Similar issues with this have been present throughout our testing of the 2.0 develop branch.

Issue: When setting "storage configuration for media" to 'database', product images upload (in admin) and download (on public site) will fail.

Repro steps:
1. Set "Stores->Configuration->System->Storage Configuration For Media" to "database".
2. Go to product entry page
3. Drag or other wise select an image file to add to page
4. Note that image will not display - resource not available. Also observe that on the public-facing page for the product the image resource will not be available

Tested environment:
- Clean install of commit tagged 2.0.0RC on nginx + mysql.

**Comment by ftsf** [comment] 2015-11-24 05:21
Seems to be due to missing `get.php` which was present in Magento 1 and was responsible for serving images from the database if they didn't exist locally.

`get.php` is only present under `pub/` but not under the root directory, so it may work if you're using `pub/` as the document root..

**Comment by vzabaznov** [comment] 2016-06-22 12:55
Hi @matthewwiggins thank you for contributing, please confirm is this this bug is reproducible on current mainline?

**Comment by vzabaznov** [comment] 2016-07-14 08:19
Hi, @matthewwiggins thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.

**Closed by vzabaznov** 2016-07-14 08:19 UTC
Labels: needs update, PS
