### ISSUE TITLE
Translation is not working in admin as well as frontend

### ISSUE THREAD

**Issue by Rajat9620** [magento/magento2#26298] opened 2020-01-07 18:26 UTC
Hello Support,

I have upgraded my magento store from 2.2.9 to 2.3.3 and after migration translation not working in admin as well as frontend. Please check attached screenshot: https://prnt.sc/qki1p0
https://prnt.sc/qki2e5

Please help me to solve this issue.
@ivannpaz  @magento-admin  @magento-engcom-team 

Thanks

**Comment by engcom-Hotel** [comment] 2020-01-17 12:01
Hello @Rajat9620 
We are not able to reproduce this issue after upgrade Magento from 2.2.6 version to 2.3.3.
Probably the problem in language pack you used.
Please refer to the language pack support, for advice or general discussion about this issue.
I have to close this issue as not reproducible.

Thanks for your report!

**Closed as completed by engcom-Hotel** 2020-01-17 12:01 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is not valid, Reported on 2.3.3
