### ISSUE TITLE
Default email templates are not compatible with strict mode

### ISSUE THREAD

**Issue by ffrodoe** [magento/magento2#30224] opened 2020-09-28 21:15 UTC
### Preconditions (*)

1. Magento 2.3.4 with sample data

### Steps to reproduce (*)

1. Go to Marketing > Email templates
2. Press 'Add new template'
3. On the new template page, in the 'Load default template' section select and load "New order" default template
4. Set any name for the new template and save
5. Set this template as a template for the new order email in Store configuration > Sales emails > Order > New Order Confirmation Template
6. Make an order or send an order email for any existing order
7. Open received email

### Expected result (*)

1. Order items and totals info is present; whole email content is the same as for default new order template
![29-09-2020 00-06-15](https://user-images.githubusercontent.com/12183505/94486147-a4ddbb00-01e7-11eb-8795-8a28fa1a8954.png)

### Actual result (*)

1. Order items and totals info is missing, though email template content remains the same as for default new order template
![28-09-2020 23-57-17](https://user-images.githubusercontent.com/12183505/94485969-66e09700-01e7-11eb-960e-e8a6cb60d7ca.png)

The same issue is actual for other sales emails (shipment, credit memo, etc.).

This is a result of strict mode template processing, [there is](https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/templates/template-email.html) magento's documentation for it. But anyway the behaviour of the system is unexpected for the end user

**Comment by ffrodoe** [comment] 2020-09-28 21:28
Ok, this seems to be a duplicate, finally found similar issue https://github.com/magento/magento2/issues/26882. Is there any patch for 2.3.x versions, or the only option is to upgrade to 2.4?

**Comment by ihor-sviziev** [comment] 2020-09-29 11:40
Hi @ffrodoe,
Thank you for your report! This issue seems to me really critical. As you already said above - this is duplicate of #26882 .

You can find in the comments changes that were applied in order to resolve this issue and also some people prepared patches for 2.3.x release line.

I’m closing this issue as duplicate

**Closed as completed by ihor-sviziev** 2020-09-29 11:40 UTC
Labels: duplicate, Issue: Format is valid, Severity: S2, Progress: done, Reported on 2.3.4
