### ISSUE TITLE
product page ask to choose option when no option is set

### ISSUE THREAD

**Issue by to8gal** [magento/magento2#6377] opened 2016-08-29 12:32 UTC
### Preconditions

I´m on a dev enviroment on mac

mamp with mysql 5.6 and php 7.0.8 for magento 2.2  with Luma Theme
### Steps to reproduce

1. trying to add product form the product list page but it redirect to product page
2. Try there as well with same result, warning message "You need to choose options for your item."
3. no option is set on backend, not for the configurable or the children
4. configurable product  on customazible option say "Custom options with price type "percent" is not available for configurable product." when all prices look fixed to me
### Expected result

1. add product to cart
### Actual result

"You need to choose options for your item." and empty cart

**Comment by pboisvert** [comment] 2016-08-29 15:08
closing as duplicate of #5882

**Closed as completed by pboisvert** 2016-08-29 15:08 UTC
