### ISSUE TITLE
Problem when adding an product to the cart in two windows for the same user

### ISSUE THREAD

**Issue by weissye** [magento/magento2#37465] opened 2023-05-04 17:28 UTC
### Preconditions and environment

- Magento 2.4.x
- 

### Steps to reproduce

1. Open one window and log in as a user
2. Make sure that the cart is empty (if not, empty the cart)
3. Open the second window and log in as the same user
4. Add any product to the cart in the first windows
5. The product doesn't appear in the cart in the second window (for the same user). The cart remains empty.
6. If the cart is not empty in steps 2-3 when the same user logs in to the second widows, that cart will be updated. 

### Expected result

When the same user logs in to the second window with the same user, the cart will be updated with every update of the first window.

### Actual result

When the same user logs in to the second window with the same user, the cart will **not** be updated with every update of the first window.

### Additional information

We found this issue when we ran automatic tests using our new tool called Provengo. In one session we log-in and added products to the cart and in another session, we try to do checkout to the same user and the same cart.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-05-05 10:22
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-05-05 12:22
Hi @weissye,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Open one window and log in as a user
- Make sure that the cart is empty (if not, empty the cart)
- Open the second window and log in as the same user
- Add any product to the cart in the first windows
- The product doesn't appear in the cart in the second window (for the same user). The cart remains empty.
- If the cart is not empty in steps 2-3 when the same user logs in to the second widows, that cart will be updated.


<img width="1454" alt="Screenshot 2023-05-05 at 4 24 58 PM" src="https://user-images.githubusercontent.com/51680745/236447357-a1f1bee1-36df-469b-9939-54463d4d5b05.png">




<img width="1512" alt="Screenshot 2023-05-05 at 4 25 05 PM" src="https://user-images.githubusercontent.com/51680745/236447490-ce61e6ea-4496-4a27-bc77-73f6b0bcfcd9.png">



When the same user logs in to the second window with the same user, the cart is updating with every update of the first window.


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.



Thanks.

**Comment by weissye** [comment] 2023-05-06 18:42
[image: image.png]
Hi
I ran the scenario (automatically, using our Provento testing tool) and the
same phenomena is the same as I ran on localhost.
I added a 'refresh' to the 'checkout' session before I start the 'checkout'
process to make sure that this is not a refreshing problem.

Please send back your link to reproduce the problem and will try to run
this there.

regards


‫בתאריך יום ו׳, 5 במאי 2023 ב-15:22 מאת ‪Venkata Kumar Kuntumalla‬‏ <‪
***@***.***‬‏>:‬

**Comment by weissye** [comment] 2023-05-06 18:47
![Screenshot 2023-05-06 214610](https://user-images.githubusercontent.com/51288697/236641529-7469d580-81a3-44d5-87bc-5413c0f56796.png)

**Comment by engcom-Bravo** [comment] 2023-05-08 11:24
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-05-08 13:25
Hi @weissye,

Thanks for your update.


Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots


<img width="1406" alt="Screenshot 2023-05-08 at 5 16 44 PM" src="https://user-images.githubusercontent.com/51680745/236816148-ac2fe7d0-30ac-4a70-af87-a301f2884be3.png">



<img width="1481" alt="Screenshot 2023-05-08 at 5 16 56 PM" src="https://user-images.githubusercontent.com/51680745/236816191-ddc497ef-244f-40d8-b9dc-4fa25460d8fa.png">



The cart is updating in other window for the same user successfully.


Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.

Please try to access this Magento 2.4 develop instance https://94f81cfd4c5c183e6376ce2458bbb97f.instances-prod.magento-community.engineering/admin_057a  and try to reproduce the issue.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-05-11 13:16
@magento give me 2.4-develop instance

**Comment by weissye** [comment] 2023-05-16 20:46
https://github.com/magento/magento2/assets/51288697/67d7f6e4-4e84-40cc-81b0-226065566dc8

**Comment by engcom-Bravo** [comment] 2023-05-17 06:21
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-05-17 14:35
Hi @weissye,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.



https://github.com/magento/magento2/assets/51680745/bb541c5d-9455-461f-8a36-64b9eed6d1f5



Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-05-29 06:13
Hi @weissye,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-05-29 06:13 UTC
Labels: Issue: needs update, Reported on 2.4.x
