### ISSUE TITLE
405 Error on Network

### ISSUE THREAD

**Issue by rymanACM** [magento/magento2#35219] opened 2022-03-23 19:05 UTC
### Preconditions (*)

1. Magento ver. 2.3.2
2. Error on Front end site

### Steps to reproduce (*)

1. Open web site on newtork
2. 405 error appears

### Expected result (*)

1. Website appears
2. 

### Actual result (*)

1.  405 Error shows instead of website
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by engcom-November** [comment] 2022-03-24 04:30
Hi @rymanACM , 
Thank you for reporting and collaboration. However provided steps are not enough for us to reproduce the issue on Magento 2.4-develop branch.
Please check below possible workarounds which may help to resolve your issue in your environment.

1. /etc/apache2/sites-available/elasticsearch.conf

=> paste this code
<VirtualHost *:8080>
ProxyPass "/" "http://localhost:9200/"
ProxyPassReverse "/" "http://localhost:9200/"
</VirtualHost>

> sudo a2ensite elasticsearch.conf

2. If the issue is due to any module not working correctly or memory limit or timeouts:
Try disabling the modules / disable 3rd party extensions if any
rm -rf var/* generated/*
php bin/magento setup:upgrade
php bin/magento indexer:reset
php bin/magento indexer:reindex
php bin/magento setup:static-content:deploy -f
php bin/magento cache:clean

Kindly elaborate the steps / configuration details if you are still facing issues.
Thank you.

**Comment by rymanACM** [comment] 2022-03-24 14:49
Hi,
It seems that We can access our site on a public network but not on our company’s network.

Thanks,

Anna Cate Myers
E-Commerce Content Coordinator | Opry Entertainment Group
One Gaylord Drive • Nashville, TN 37214
Email: ***@***.*** ***@***.***>  Office: 615.316.6053<tel:6153166053> Mobile: 334.819.6336<tel:3348196336>

[A close up of a sign  Description automatically generated]



From: Girija Bhavani Kudupudi ***@***.***>
Date: Wednesday, March 23, 2022 at 11:30 PM
To: magento/magento2 ***@***.***>
Cc: Myers, Anna Cate ***@***.***>, Mention ***@***.***>
Subject: Re: [magento/magento2] 405 Error on Network (Issue #35219)
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Hi @rymanACM<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FrymanACM&data=04%7C01%7Camyers%40opry.com%7Cfafd89815dac412ba39208da0d4f0e65%7Cc8b8a0955c414568bef04a95378f0257%7C0%7C0%7C637836930459107147%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DpagHzB2pyOs%2BlZ1SLDMsyeTv5LuaQVF3idqqeFgfvw%3D&reserved=0> ,
Thank you for reporting and collaboration. However provided steps are not enough for us to reproduce the issue on Magento 2.4-develop branch.
Please check below possible workarounds which may help to resolve your issue in your environment.

  1.  /etc/apache2/sites-available/elasticsearch.conf

=> paste this code
<VirtualHost *:8080>
ProxyPass "/" "http://localhost:9200/"
ProxyPassReverse "/" "http://localhost:9200/"

sudo a2ensite elasticsearch.conf

  1.  If the issue is due to any module not working correctly or memory limit or timeouts:
Try disabling the modules / disable 3rd party extensions if any
rm -rf var/* generated/*
php bin/magento setup:upgrade
php bin/magento indexer:reset
php bin/magento indexer:reindex
php bin/magento setup:static-content:deploy -f
php bin/magento cache:clean

Kindly elaborate the steps / configuration details if you are still facing issues.
Thank you.

**Comment by engcom-November** [comment] 2022-04-01 09:00
Hi @rymanACM ,
405 Error is generally observed when web browser can't access the requested web page. Looks like your company's network is restricting / not allowing to access this e-commerce website. Can you please check your VPN Settings / network Settings and grant permissions if required.
This is not a Magento issue as we can able to access it using both Public network and VPN aswell.
Thank you.

**Comment by engcom-November** [comment] 2022-04-18 06:01
Hi @rymanACM ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-04-18 06:01 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
