### ISSUE TITLE
Design configuration (2.1.0) does not save

### ISSUE THREAD

**Issue by abdel1220** [magento/magento2#5288] opened 2016-06-27 16:24 UTC
Hello,
thank you for the effort you are making.
i have issue in Content -> Desing -> Configuration in 2.1.0 version.
## Steps to reproduce
1. Browse Content -> Design -> Configuration.
2. Click Edit Global.
3. Change any value and then Save Configuration.
## Expected result
1. Save and refresh the page
## Actual result
1.  dose not save and show error: 
   Cannot read contents from file "path/to/magento/" Warning!file_get_contents(path/to/magento/): failed to open stream: No such file or directory

web server info:

IIS 7.5
PHP 7.07 (fastcgi).

thank you.

**Comment by andimov** [comment] 2016-06-27 17:15
@akacemy 
thank you for reporting.
I can't reproduce on supported web servers. Looks like this is a IIS 7.5 issue;
Please use web server according [System Requirements](http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements.html)
I'm closing issue since system requirements not pass.
Please feel free to reopen if it's needed.

**Closed as completed by andimov** 2016-06-27 17:15 UTC

**Comment by psiegel404** [comment] 2016-07-15 12:49
Hello,
i got the exact same problem on Magento 2.1.0 with XAMPP 3.2.2 (Apache 2.4.18) on Windows 7. So I don't think it's a IIS 7.5 only problem.

**Comment by devDomM** [comment] 2016-07-15 13:00
Can also reproduce this problem. We updated to Magento 2.1.0 today locally on a Windows 10 with XAMPP 3.2.2 using Apache 2.4.17
As soon as we try to save the design configuration we get the "Cannot read contents from file ..." error.

We also noticed that there is no entry in any of the log-Files for this.

**Comment by andimov** [comment] 2016-07-15 13:14
@kurtjmeyoung @devDomM
In order to allow us to investigate this problems, please create a new issue in accordance with the template.

**Comment by abdel1220** [comment] 2016-07-16 17:49
hello,
thank you for your replay.
new ticket was created by someone else [#5666](https://github.com/magento/magento2/issues/5666)

**Comment by vivek201** [comment] 2016-07-17 18:12
@akacemy 
Hello, I have found a workaround for this. You will need to copy the folder `\vendor\magento\module-email\view\frontend\email` to `\vendor\magento\module-email\view\adminhtml\email`. For some reason, it's looking in the adminhtml folder for the `header.html` file.
Don't know if this is a proper solution, but hope it helps.

**Comment by abdel1220** [comment] 2016-07-19 19:13
hello,
this works, but i think this is not the real solution. i think there is something to be fixed in the code.

**Comment by vivek201** [comment] 2016-07-20 06:00
Yeah, I looked into the Email module again and I think I might've found the issue.

I have posted an issue (#5703) regarding it. Also, I posted an explanation for it in the stackoverflow post http://magento.stackexchange.com/a/126454/32459

**Comment by abdel1220** [comment] 2016-07-20 15:21
Hello,

thats worked too.
let's wait for magento team opinion. 
thanks for the effort 👍 :)

**Comment by vivek201** [comment] 2016-07-21 04:43
Glad, it helped.

**Comment by Fairlight60** [comment] 2016-10-20 20:49
I still have this issue in Magento 2.1.2 running under Uniform Server Zero XIII, PHP 7.0 and Windows 8.1, did I miss something?

**Comment by EmpeRoar** [comment] 2016-10-30 08:05
the issue it solve using vivek201 solution

**Comment by vasilii-b** [comment] 2017-05-05 08:22
The workaround works.

**Comment by mtkumar82** [comment] 2017-05-24 09:50
Great!, I have same issue on local and @akacemy solution worked for me..
