### ISSUE TITLE
Product image is not shown in the gallery box on IOS and Mac OS on Safari on the product page

### ISSUE THREAD

**Issue by igortregub** [magento/magento2#10278] opened 2017-07-18 14:39 UTC
I found that on some product pages on IOS and Mac OS on Safari don't show their images.
In this case the problem has caused on some product pages, where main image is not first on the list. 
In cases when the main image is first on the list, everything works well.

### Preconditions

1. Magento version 2.1.7
2. PHP Version 7.0.19
3. Apache Version 2.4.10 (Debian)
4. MySQL 5.6.36 
5. Redis server v=3.0.7 
6. Docker version 17.03.1-ce, build c6d412e
7. Linux ubuntu 4.4.0-62-generic x86_64

### Steps to reproduce

1. Go to product page: http://magento2-demo.nexcess.net/selene-yoga-hoodie.html
2. Product image is not shown in the gallery box.

### Expected result

1. Go to product page (http://magento2-demo.nexcess.net/hero-hoodie.html)
2. Product image is shown in the gallery box:
![expectedresult](https://user-images.githubusercontent.com/6198012/28321706-95753b92-6bdc-11e7-8549-e907199f0851.jpg)

### Actual result

1. Go to product page (http://magento2-demo.nexcess.net/selene-yoga-hoodie.html)
2. Product image is not shown in the gallery box.
![actualresult](https://user-images.githubusercontent.com/6198012/28322570-1d5f757a-6bdf-11e7-9e50-9fa821967de9.jpg)

Related issues:
* https://github.com/magento/magento2/issues/7357

**Comment by orlangur** [comment] 2017-07-18 14:48
Yeah, http://magento2-demo.nexcess.net/selene-yoga-hoodie.html image is scrolled to the very left right after load. Safari 10.1.1 in my case.

**Comment by grantkemp** [comment] 2017-07-19 16:21
confirmed for me too

**Comment by helalbookmark** [comment] 2017-08-14 16:07
I have this error also

**Comment by erikhansen** [comment] 2017-09-18 15:50
@Those of you experiencing this issue - You should try applying the patch I mentioned in [this comment](https://github.com/magento/magento2/issues/7357#issuecomment-330266513) to see if it fixes your issue.

**Comment by orlangur** [comment] 2017-09-18 15:58
@erikhansen how does it work? I don't see any visible changes in commit.

**Comment by erikhansen** [comment] 2017-09-18 16:08
@orlangur This is the commit I'm talking about: https://github.com/magento/magento2/commit/bee0c6db07e17cab97864f71142072e423d63403

**Comment by orlangur** [comment] 2017-09-18 19:20
@erikhansen me to, looks like a formatting change to me.

**Comment by erikhansen** [comment] 2017-09-18 19:29
@orlangur Oh, my bad. I linked to the wrong commit. Check out this commit: [4386f8db](https://github.com/magento/magento2/commit/4386f8db587fe06d4593cf3eb29d333141ef3fb1#diff-0c04816bd63e8024a1d4732df9aab816)

**Comment by denguyen-tvit** [comment] 2017-09-19 07:41
@erikhansen It worked for my after checkout this commit. Thanks!

**Comment by orlangur** [comment] 2017-09-19 09:52
@erikhansen thanks! Worth backporting to `2.1.x` according to my understanding.

**Comment by orlangur** [comment] 2017-09-19 22:58
Closing as the fix for this issue is already available on Magento 2.2.0 branch.

Anyone, do not hesitate to create a backport to `2.1-develop` if needed, see https://community.magento.com/t5/Magento-DevBlog/Pull-Requests-for-2-1-x-Patch-Releases/ba-p/65630 for details.

**Closed as completed by orlangur** 2017-09-19 22:58 UTC
Labels: bug report, Component: Catalog, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
