### ISSUE TITLE
Tax for complete order applied when refunding partial order

### ISSUE THREAD

**Issue by MartinSchillinger** [magento/magento2#32222] opened 2021-02-18 16:58 UTC
### Preconditions (*)

1. Magento 2.4.1 installed with sample data
2. Online Payment Method i.e. PayPal set up
3. Tax rules set up for germany (19%)

### Steps to reproduce (*)

1. Create order with multiple positions
2. Invoice one or more (but not all) positions
3. Create a second invoice for the remaining positions
4. Go to the invoice view of the first invoice and click "credit memo" from the top menu
5. Compare the lineitem's tax values to the summary tax values

### Expected result (*)

1. The tax for the credit memo should be as much as the position's accumulated tax

### Actual result (*)

1. The tax for the lineitems is correct but the tax amount in the summary is the value for the complete order.

### Workaround
If you enter the credit memo section out of the order view the tax is calculated correctly.
The difference is: If you come from an invoice view, you only see the positions of this invoice. When you access the credit memo editor page from the order page, you see all positions.
**Drawback** of the workaround: No online refund will be created. Only offline.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by MartinSchillinger** [comment] 2021-05-06 06:54
Still relevant

**Comment by engcom-Oscar** [comment] 2021-05-06 12:56
Hi @MartinSchillinger ! Thank you for your report.
Unfortunately, we are not able to reproduce the issue. Looks like we miss some important preconditions, so may you please recheck and update description?
After following steps from this ticket, we have such result:
![Screenshot from 2021-05-06 15-53-14](https://user-images.githubusercontent.com/60198413/117301680-8af20e00-ae83-11eb-831a-64b3cef38a90.png)

![Screenshot from 2021-05-06 15-52-45](https://user-images.githubusercontent.com/60198413/117301695-904f5880-ae83-11eb-9f77-6745197ffb4c.png)

**Comment by gocom** [comment] 2021-05-10 06:17
@engcom-Oscar 

> Unfortunately, we are not able to reproduce the issue. Looks like we miss some important preconditions, so may you please recheck and update description?

As @MartinSchillinger outlined in the issue, you'll need to create multiple credit memos to be able to partially refund an order. In real life scenario this could also be an order that is processed in smaller batches (multiple invoices/shipments). In those screenshots, the whole order at appears to be invoiced at once and then single credit memo is created, instead of partial refunds.

More detailed flow that does make it happen for us, is for instance:

1. Products need to use taxes.
2. Order 2 qty of product sim1 and 1 qty of product sim2.
3. Create first invoice containing 1 qty of sim1 and 1 qty of sim2.
4. Create second invoice containing 1 qty of sim1.
5. Refund 1 qty of sim1 from first invoice by creating credit memo from the invoice view.
7. Refund 1 qty of sim1 from the second invoice by creating credit memo from the invoice view.
8. Similarly to this issue report, for us, it applies full order taxes to the second credit memo making the refunded amount greater than expected.

**Comment by engcom-Oscar** [comment] 2021-05-11 11:57
Hi @gocom @MartinSchillinger  
I did partial invoice, just as it was said in the ticket.
### Steps to reproduce (*)
1. Products need to use taxes.
2. Order 2 qty of product sim1 and 1 qty of product sim2.
3. Create first invoice containing 1 qty of sim1 and 1 qty of sim2.
4. Create second invoice containing 1 qty of sim1.
5. Refund 1 qty of sim1 from first invoice by creating credit memo from the invoice view.
7. Refund 1 qty of sim1 from the second invoice by creating credit memo from the invoice view.

**Actual Result:** :heavy_check_mark: 
my order
![Screenshot from 2021-05-11 14-54-44](https://user-images.githubusercontent.com/60198413/117811167-e730a580-b268-11eb-8205-cc746369e511.png)
![Screenshot from 2021-05-11 14-55-45](https://user-images.githubusercontent.com/60198413/117811284-08919180-b269-11eb-8a8b-27d88b7cf92d.png)
![Screenshot from 2021-05-11 14-55-56](https://user-images.githubusercontent.com/60198413/117811298-0c251880-b269-11eb-91b7-8e9d2fd60ba0.png)

first credit memo
![Screenshot from 2021-05-11 14-56-39](https://user-images.githubusercontent.com/60198413/117811378-26f78d00-b269-11eb-903d-df2aa0f9f69c.png)

second credit memo
![Screenshot from 2021-05-11 14-57-32](https://user-images.githubusercontent.com/60198413/117811460-3ecf1100-b269-11eb-9cff-e89d4fc3eae9.png)

**Comment by MartinSchillinger** [comment] 2021-05-11 12:45
Did you go to the creditmemo view by clicking "credit memo" in the invoice view or by creating new creditmemo from the order view. I can normally refund them if i don't come from the invoice view.
The difference is that the refund in the payment method is automatically triggered when you come from the invoice view but not if you come from the order view.

**Comment by engcom-Oscar** [comment] 2021-05-11 12:49
yes, from invoice view

**Comment by gocom** [comment] 2021-05-12 22:55
@engcom-Oscar 

In the first credit memo you are refunding all products instead of just one (full, rather than [partial refund](https://github.com/magento/magento2/issues/32222#issuecomment-836233491)).

That said, reviewing code changes, at least that case appears to be fixed (but not yet released) in 7f9a7fd39b4514fee0ca9eb0a1a8701c6f2b4030, 8b873ad45946dbefbd75038baea32df29c49980b, 7d9d478b7c6b5dac52c7f4544b89612a0859d24b, 38fc6c6e907f1bc574e8d8365195b8a04ab3d1b8 and 08a6b9cb5fdd08b0813936d0e0309219c11e3c84. I haven't tested those changes, but it appears to longer reference the order tax when creating the credit memo from invoice in this case, so it appears promising.

**Comment by engcom-Oscar** [comment] 2021-05-13 07:14
Hi @gocom ! I did partial refund - for 1 product from the 1 invoice - but still issue not reproducing. Looks like it been fixed in latest 2.4-develop.
![Screenshot from 2021-05-13 10-07-37](https://user-images.githubusercontent.com/60198413/118091831-faac4f80-b3d3-11eb-8b7c-10edf9d2bad1.png)

**Comment by engcom-Oscar** [comment] 2021-05-27 10:49
We have to close this ticket.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) if you are still facing this issue on the latest `2.4-develop` branch.
Thank you for collaboration.

**Closed as completed by engcom-Oscar** 2021-05-27 10:49 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
