### ISSUE TITLE
Can't open order with a product recently disabled

### ISSUE THREAD

**Issue by LeoNun** [magento/magento2#24838] opened 2019-10-03 12:19 UTC
Hello,
as the title mention when I try to open an order recently created with any state with a product that I disable I cannot open this order.
Anybody with this issue?
Can anyone try with magento 2.3.2?

Best regards,
Leonel Nuens

**Comment by LeoNun** [comment] 2019-10-03 18:15
Hello again, to reproduce these error, just add an order in the frontend, and in the backend disable the product and then check the order in the backend, and the page keeps loading and loading, eventually afte a while I get this error:

Gateway Timeout, The gateway did not receive a timely response from the upstream server or application.

Additionally, a 504 Gateway Timeout error was encountered while trying to use an ErrorDocument to handle the request.

Best regards,
Leonel Nunes

**Comment by engcom-Bravo** [comment] 2019-10-04 06:22
Hello @LeoNun, thanks for reporting. Currently we are not able to reproduce Your issue on the latest 2.3-develop version. Please watch the gif below:
![order](https://user-images.githubusercontent.com/51680745/66185139-15aacf80-e687-11e9-8c12-3e5e385bfa4d.gif)
Nether are we able to reproduce it on Your reported version of 2.3.2.
For being on the safe side we also tried to do that with guest customer but result was the same - everything worked Ok. So would You please try Yourself to reproduce the issue on a vanilla instance of Magento 2.3-develop version as You are asked above in the [comment](https://github.com/magento/magento2/issues/24838#issuecomment-537920452) and if You still succeed let us know what we do wrong or not exactly as You meant. Thank You.

**Comment by LeoNun** [comment] 2019-10-04 08:53
Hello and thanks for checking.
Well what you did it's the correct to reproduce the error, I the problem might be in my instalation :S

Thanks for the support,

Best regards,
Leonel Nunes

**Comment by engcom-Bravo** [comment] 2019-10-04 09:55
Then @LeoNun we are supposed to close this issue. But please feel free to reopen it if You find the way how to reproduce it on a clear Magento installation. Thanks for applying.

**Closed as completed by engcom-Bravo** 2019-10-04 09:55 UTC
Labels: Issue: Format is not valid
