### ISSUE TITLE
Possible nonstandard HTML class in Checkout Authentication template

### ISSUE THREAD

**Issue by JeffersonTeixeira** [magento/magento2#32572] opened 2021-03-22 18:52 UTC
### Summary (*)
The class `action action-remind` only exist in checkout authentication template for **Forgot Password Link**. In all other pages is used: class="action remind" instead
I didn't find any style or selector using the tag `action-remind`

### Examples (*)
All the following templates use `action remind` instead `action-remind`:
vendor/magento/module-checkout/view/frontend/web/template/form/element/email.html
vendor/magento/module-customer/view/frontend/templates/form/login.phtml

Class ‘action action-remind’ is there in authentication template  Path: app/code/Magento/Checkout/view/frontend/web/template/authentication.html
Other all related files have class ‘action remind’ instead.
Issue: Inaccurate class name added in authentication template

### Proposed solution
Change the class from **action-remind** to **remind** in other words:
Before:
`class="action action-remind"`
After:
`class="action remind"`

or the changes could be done in reverse too.

---

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by rodrigowebjump** [comment] 2021-03-23 17:12
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment] 2021-08-19 04:55
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
1. Found class ‘action-remind’ added in authentication template  Path: app/code/Magento/Checkout/view/frontend/web/template/authentication.html
2. Other all related files have class ‘remind’ instead.
**Issue:** Inaccurate class name added in authentication template

**Comment by engcom-Bravo** [comment] 2024-07-24 09:05
Hi @JeffersonTeixeira,

Thanks for your reporting and collaboration.

AS per this comment https://github.com/magento/magento2/pull/32575#issuecomment-2066150797 we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-24 09:05 UTC
Labels: Issue: Confirmed, Triage: Dev.Experience, Priority: P4, Progress: done, Area: Content
