### ISSUE TITLE
setup:db-declaration:generate-whitelist fails with no logs/error anywhere

### ISSUE THREAD

**Issue by adamlavery** [magento/magento2#35102] opened 2022-02-14 16:27 UTC
### Preconditions (*)
1. M2.4.3-p1. 

### Steps to reproduce (*)
- Create a db_schema.xml file and hope everything in it is correct
- Upload (new) module to app/code
- Run module:enable Vendor_Module (possibly, schema process is not clear)
- Run cache:clean & cache:flush (to be on the safe side)
- Run setup:db-declaration:generate-whitelist --module-name=Vendor_Module

### Expected result (*)
db_schema_whitelist.json generated in Vendor/Module/etc

### Actual result (*)
Nothing, nowt, zilch

Command runs, no errors, nothing in system.log, exception.log or reports - nothing anywhere. No db_schema_whitelist.json is created. Run setup:upgrade and module is installed (appears in setup_module) but no database tables created. 

Changes that were supposed to improve logging of this command as per https://github.com/magento/magento2/issues/27241 are present.

Tried adding additional logging as per https://magento.stackexchange.com/questions/255583/magento-2-is-not-generating-the-db-schema-whitelist-json-file-via-cli but still nothing.

How can this command, or any command for that matter, fail without providing any indication of why it is failing?

**Comment by adamlavery** [comment] 2022-02-14 16:29
@magento give me 2.4-develop instance

**Comment by adamlavery** [comment] 2022-02-14 16:40
Develop instance is no use for testing this issue.

**Comment by dudzio12** [comment] 2022-02-15 21:48
I'll check that

**Comment by dudzio12** [comment] 2022-02-15 22:02
@adamlavery I couldn't reproduce the issue on `2.4-develop` branch. Here's the output file of `bin/magento setup:db-declaration:generate-whitelist --module-name=Vendor_Module` command:

```
{
    "alp_tablepricing_quantities": {
        "column": {
            "quantity_id": true,
            "product_id": true,
            "quantity": true
        },
        "constraint": {
            "PRIMARY": true
        }
    },
    "alp_tablepricing_prices": {
        "column": {
            "price_id": true,
            "product_id": true,
            "quantity_id": true,
            "option_one_id": true,
            "option_two_id": true
        },
        "constraint": {
            "PRIMARY": true
        }
    },
    "alp_tablepricing_customprices": {
        "column": {
            "customprices_id": true,
            "product_id": true,
            "custom_attribute_option_id": true,
            "option_one_id": true,
            "option_two_id": true,
            "price": true
        },
        "constraint": {
            "PRIMARY": true
        }
    }
}
```

**Comment by engcom-Echo** [comment] 2022-08-01 06:13
Hello @adamlavery,

Since there is no update from 14 days hence we are closing this issue if you are still facing same issue you can reopen this or   create a new issue.

Thanks

**Closed as completed by engcom-Echo** 2022-08-01 06:13 UTC
Labels: Triage: Dev.Experience, Issue: needs update

**Comment by adamlavery** [comment] 2022-08-01 07:53
Please reopen. Just because you didn't encounter an issue doesn't mean there isn't one. The key point of this ticket is that it IS failing on our install but with no information anywhere as to why. As demonstrated, our schema definition works elsewhere so why is it failing on our install? 

That must be addressed. Basic 101 of coding practice: either something works as expected or it fails with an indication of why. Poor coding practice to allow something (anything) to fail silently. The DB schema code needs to be reworked so that if anything fails then there's a log somewhere to indicate what needs looking at. This should never have passed QA in the first place.

**Comment by engcom-Echo** [comment] 2022-08-02 08:40
Hello @adamlavery,

We have close this issue because this window is not updated for more than 14 days.

Can you please help us in getting the actual steps to reproduce the issue, we are not able to reproduce issue by the mentioned steps in the main description.

Thanks

**Comment by adamlavery** [comment] 2022-08-02 09:18
@engcom-Echo the issue is you cannot reproduce it but nevertheless it still happens on my install. It's quite common for issues to be unreproducible on a vanilla install. A vanilla install doesn't have any history whereas real-world sites do. Just because you can't reproduce on a vanilla install doesn't mean you can ignore it.

The core issue is that it fails to do anything **silently**. It must not fail silently. It's not just this - far too much fails silently in M2. The UI side is a nightmare to work with; if you make a simple naming mistake somewhere, nothing happens and nothing is logged. 

Somewhere in the schema processing something is failing but instead of checking for success at every action it just fails silently.

I suspect in this case its's because our database was migrated from M1 and there's something there the code cannot handle. No idea what because it just fails silently. That's the issue that needs addressing. Not just for this instance but throughout in M2  so that if something is wrong, it gives us a clue for what to look for.

**Comment by engcom-Echo** [comment] 2022-08-03 06:33
Hello @adamlavery,

Thanks you for your reply.

I can understand your issue but we need more information in order to reproduce this issue. Can you please tell us from which version from M1 you have upgrade the Magento with version 2.4.3-p1.

It seems an upgrade issue for us so we will check in that way.

Thanks

**Comment by adamlavery** [comment] 2022-08-03 08:01
From 1.9.3.6, but I don't expect that to shed any light. The M1 site has been upgraded multiple times through it's life and has a fair few 3rd party extensions. I encountered multiple issues during data migration due to faults in previous upgrade processes that left unwanted stuff behind that the migration scripts didn't deal with.

You are approaching this wrong, as did whoever was involved in developing the functionality. I say again, all code must generate logs/errors when it encounters something unexpected. Another 101 of best coding practice - check for what's expected and reject anything else; never look for the unexpected. 

Being able to reproduce an issue is the ideal situation but that's not always possible. Then you have to rely on well-written code to indicate where an issue has occurred (i.e. what step of the process) instead of just dying silently. The code can then be tracked back to hopefully discover the cause. With nothing logged at all, we're blind as to where it is getting to.

First thing to do is to add some optional verbose logging so we can see how it is progressing through the process and what step it's dying at. Even a crash would be better than nothing at all.

**Comment by engcom-Echo** [comment] 2022-08-05 08:33
Hi 

Thanks for raising your concern.

In order to proceed further with any community issue we first have to reproduce it and then we can proceed with the confirmation of the same.


We can see 2 different issues in your mentioned description.

1. Magento need to improve the logging feature: Agreed on this. May be we can consider this as feature request as a separate issue.
2. The .json is not getting created and table is also not created.

In order to consider point#2 as a bug, we first have to reproduce this on Magento 2.4-develop as a part of process. I agree that the issue is reproducible only on your instance but their has to be some reason due to which you are getting this issue. Hence may be you can do some more analysis on the steps to reproduce and perquisites and provide us that information so that we can go ahead with those steps.


Thank you in advance!
