### ISSUE TITLE
FPC does't work properly on multistore

### ISSUE THREAD

**Issue by 0m3r** [magento/magento2#24361] opened 2019-08-29 15:09 UTC
### Preconditions (*)

1. Magento 2.3.2
2. Enable developer mode
3. Enable FPC 
4. Create two or more store view

### Steps to reproduce (*)

1. Enable 'Add Store Code to Urls'
Stores-> Configuration -> General -> Web -> Url Options -> Add Store Code to Urls set Yes
2. Flush all caches (bin/magento flush:all)
3. Run commands 
~~~
curl -s -I http://magento23.local/default/ | grep X-Magento-Cache-Debug
MISS
curl -s -I http://magento23.local/default/ | grep X-Magento-Cache-Debug
HIT

curl -s -I http://magento23.local/custom_storeview/ | grep X-Magento-Cache-Debug
MISS
curl -s -I http://magento23.local/custom_storeview/ | grep X-Magento-Cache-Debug
MISS
~~~

### Expected result (*)
MISS -> HIT
MISS -> HIT 

### Actual result (*)
MISS -> HIT
MISS -> MISS

![Знімок екрану з 2019-08-29 17-44-53](https://user-images.githubusercontent.com/412612/63951065-c53bc300-ca85-11e9-8e6d-fda3603fd268.png)

### Why 

Cache Id calculation logic is wrong 

[Magento/Framework/App/PageCache/Kernel.php#L112](https://github.com/magento/magento2/blob/2.3/lib/internal/Magento/Framework/App/PageCache/Kernel.php#L112)
~~~php
$responseData = $this->fullPageCache->load($this->identifier->getValue());
~~~

[Magento/Framework/App/PageCache/Identifier.php#L57](https://github.com/magento/magento2/blob/2.3/lib/internal/Magento/Framework/App/PageCache/Identifier.php#L57)
~~~php
        $data = [
            $this->request->isSecure(),
            $this->request->getUriString(),
            $this->request->get(\Magento\Framework\App\Response\Http::COOKIE_VARY_STRING)
                ?: $this->context->getVaryString()
        ];
~~~
cookie is empty so running $this->context->getVaryString()

~~~php
public function getVaryString()
    {
        $data = $this->getData();
        if (!empty($data)) {
            ksort($data);
            return sha1($this->serializer->serialize($data));
        }
        return null;
    }
~~~
getVaryString() returns null because store still wasn't set  

'store' is set only after  Magento\Framework\App\PageCache\Kernel::load
in Magento\Store\App\Action\Plugin\Context

![Знімок екрану з 2019-08-29 18-05-07](https://user-images.githubusercontent.com/412612/63952071-8dce1600-ca87-11e9-92be-5b344d2a3760.png)

at beforeDispatch
![Знімок екрану з 2019-08-29 18-07-26](https://user-images.githubusercontent.com/412612/63952268-eac9cc00-ca87-11e9-9cb4-1fd6bef518c3.png)

**Comment by 0m3r** [comment] 2019-08-30 06:50
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-08-30 06:50
Hi @0m3r. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-08-30 06:50
Hi @0m3r, here is your [Magento instance](https://i-24361-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24361-2-3-develop.instances.magento-community.engineering/admin](https://i-24361-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by 0m3r** [comment] 2019-08-30 07:21
sorry but I can't change 
deploy mode to develop at the demo (https://i-24361-2-3-develop.instances.magento-community.engineering) without shell.
So I can't see  X-Magento-Cache-Debug header value

**Comment by magento-engcom-team** [comment] 2019-08-30 08:22
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19754` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Rus0** [comment] 2019-09-02 19:46
Hey @0m3r,

I cannot reproduce it on 2.3-develop, I will close it, I followed every step you mentioned.
![image](https://user-images.githubusercontent.com/6666392/64131738-37ffb380-cd90-11e9-9d37-c93e521ca6a6.png)

I double checked if I was sync'd with latest changes:

![image](https://user-images.githubusercontent.com/6666392/64131742-3df59480-cd90-11e9-88d0-a6612fabe84a.png)

If you can still reproduce it, please reopen it, and add more steps for reproduction, since I took the exact steps you mentioned.

**Closed as completed by Rus0** 2019-09-02 19:46 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Store

**Comment by 0m3r** [comment] 2019-09-03 11:36
Ok. In 2.3-develop the bug was already fixed. But not in Magento 2.3.2.

https://github.com/magento/magento2/blame/2.3-develop/app/code/Magento/Store/App/Action/Plugin/Context.php

thanks for @dhorytskyi and Roman Lytvynenko

https://github.com/magento/magento2/commit/438b0f0a3ab24e7a563e6543070824545de8781e
https://github.com/magento/magento2/commit/50acd4f556ec313e4ad1ec6efc1739af4e8e9dbe

p.s. What about 2.2?

**Comment by Rus0** [comment] 2019-09-03 16:26
@0m3r There is no longer development for 2.2 :cry: 

If you need it you'll need to modify the vendor file or make a patch to the file in the vendor, I suggest making a composer patch.
