### ISSUE TITLE
Loged in customer on add Wishlist occasionally facing this error. "Unique constraint violation found"

### ISSUE THREAD

**Issue by hassanas** [magento/magento2#35893] opened 2022-08-09 10:44 UTC
### Preconditions and environment

- 2.3.1
- I am facing this issue on production some time following error recorded into the logs when loged in user want to add product into wish list.
- **Unique constraint violation found**
- issue is on the following file _vendor/magento/module-wishlist/Model/Wishlist.php_ on function _loadByCustomerId_
- in this function when resource is loading by customer id it returns null
- but when in second call when it try to create wish list entry by customer id this id already exists due to which I am facing 'Unique constraint violation found'
- Issue occured few times in the day. reading _wishlist_ table is returning null while entry exists their.

```
**main.CRITICAL: Exception message: Unique constraint violation found**
Trace: <pre>#1 Magento\Wishlist\Model\ResourceModel\Wishlist->save() called at [vendor/magento/framework/Model/AbstractModel.php:655]
#2 Magento\Framework\Model\AbstractModel->save() called at [vendor/magento/module-wishlist/Model/Wishlist.php:242]
#3 Magento\Wishlist\Model\Wishlist->loadByCustomerId() called at [vendor/magento/module-wishlist/Controller/WishlistProvider.php:85]
#4 Magento\Wishlist\Controller\WishlistProvider->getWishlist() called at [vendor/magento/module-wishlist/Helper/Data.php:206]
#5 Magento\Wishlist\Helper\Data->getWishlist() called at [vendor/magento/module-wishlist/Helper/Data.php:250]
#6 Magento\Wishlist\Helper\Data->_createWishlistItemCollection() called at [vendor/magento/module-wishlist/Helper/Data.php:261]
#7 Magento\Wishlist\Helper\Data->getWishlistItemCollection() called at [vendor/magento/module-wishlist/Helper/Data.php:593]
#8 Magento\Wishlist\Helper\Data->calculate() called at [vendor/magento/module-wishlist/Helper/Data.php:237]
#9 Magento\Wishlist\Helper\Data->getItemCount() called at [vendor/magento/module-wishlist/CustomerData/Wishlist.php:87]
#10 Magento\Wishlist\CustomerData\Wishlist->getCounter() called at [vendor/magento/module-wishlist/CustomerData/Wishlist.php:75]
#11 Magento\Wishlist\CustomerData\Wishlist->getSectionData() called at [vendor/magento/module-customer/CustomerData/SectionPool.php:90]
#12 Magento\Customer\CustomerData\SectionPool->getSectionDataByNames() called at [vendor/magento/module-customer/CustomerData/SectionPool.php:60]
#13 Magento\Customer\CustomerData\SectionPool->getSectionsData() called at [vendor/magento/module-customer/Controller/Section/Load.php:78]
#14 Magento\Customer\Controller\Section\Load->execute() called at [generated/code/Magento/Customer/Controller/Section/Load/Interceptor.php:24]
#15 Magento\Customer\Controller\Section\Load\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#16 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#17 Magento\Customer\Controller\Section\Load\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#18 Magento\Customer\Controller\Section\Load\Interceptor->Magento\Framework\Interception\{closure}() called at [app/code/Apptrian/PinterestPixel/Plugin/App/Action/Context.php:61]
#19 Apptrian\PinterestPixel\Plugin\App\Action\Context->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#20 Magento\Customer\Controller\Section\Load\Interceptor->Magento\Framework\Interception\{closure}() called at [app/code/Apptrian/FacebookPixel/Plugin/App/Action/Context.php:61]
#21 Apptrian\FacebookPixel\Plugin\App\Action\Context->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#22 Magento\Customer\Controller\Section\Load\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#23 Magento\Customer\Controller\Section\Load\Interceptor->___callPlugins() called at [generated/code/Magento/Customer/Controller/Section/Load/Interceptor.php:39]
#24 Magento\Customer\Controller\Section\Load\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:186]
#25 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:118]
#26 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#27 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#28 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]
#29 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#30 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [app/code/Amasty/InvisibleCaptcha/Plugin/Predispatch.php:113]
#31 Amasty\InvisibleCaptcha\Plugin\Predispatch->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#32 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:69]
#33 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#34 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#35 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#36 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#37 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#38 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#39 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:40]
```

### Steps to reproduce

1. logedin on the site in busy hours
2. add product to wishlist

### Expected result

This error should not appear "Unique constraint violation found" and product added to cart successfully.

### Actual result

Product not added to wish list at that time and error logs in the system.log
Unique constraint violation found

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-08-09 11:35
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-08-09 11:49
Hi @hassanas,

Thank you for reporting and collaboration.

 Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue. Kindly refer the screenshots.

<img width="943" alt="wish" src="https://user-images.githubusercontent.com/51680745/183639766-f76f5c0c-c24e-44d1-a33e-fff901a53cf9.png">


Thanks.

**Comment by hassanas** [comment] 2022-08-09 12:01
@engcom-Bravo its working on my site as well. But the issue I highlighted occured some times in the day in peak time.

**Comment by engcom-Bravo** [comment] 2022-08-10 12:50
Hi @hassanas,

Thanks for quick response.

We are checking from long time but we didn't face any error related to add a product to Wishlist. kindly Provide specific scenario that you have face this error.

Thanks.

**Comment by engcom-Bravo** [comment] 2022-08-24 05:24
Hi @hassanas,


We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-08-24 05:24 UTC
Labels: Issue: needs update, Reported on 2.3.1
