### ISSUE TITLE
Guest must Refresh in order to Checkout after being sent directly to the Cart

### ISSUE THREAD

**Issue by twistedindustries** [magento/magento2#4872] opened 2016-06-03 19:46 UTC
## Steps to reproduce
1. Install Magento 2.0.7.
2. Create a bundle product.
3. Change setting "After Adding a Product Redirect to Shopping Cart" to YES.
4. Add product to cart, you will be redirected to the cart.
5. Click "Go to Checkout"
## Expected result
1. Takes user to onepage checkout.
## Actual result
1. Opens authentication modal and tells the user they must either create an account  or login.
2. Refresh the page.
3. Click "Go to Checkout", you will be taken to the checkout page as expected.

**Comment by twistedindustries** [comment] 2016-06-03 20:04
Looks like it is due to cart.isGuestCheckoutAllowed not being set.

**Comment by twistedindustries** [comment] 2016-06-03 21:12
Actually looks like all of customerData is empty, perhaps this is knockout related

**Comment by sdzhepa** [comment] 2016-06-07 14:56
Hello @twistedindustries !
We have tried to reproduce this issue
We use clear Magento installation from GitHub(2.0.7). It means with default settings as after installation, without any extensions, on default Magento mode
After installation was created two simple product and then TWO bundle(bundle1, bundle2) products that contain both simples.
Bundle products settings:
 **First bundle has settings**
- Dynamic SKU = Yes
- Dynamic Price = Yes
- Dynamic Weight = Yes
- Ship Bundle Items = Together
  
  **Second bundle has settings**
- Dynamic SKU = No (Fixed)
- Dynamic Price = No (Fixed)
- Dynamic Weight = No (Fixed)
- Ship Bundle Items = Separately

Then was changed option in Stores>Configurations>Sales>Checkout  "After Adding a Product Redirect to Shopping Cart" = YES

Then go to Storefront as Guest user and add bundle1 to the shopping cart
Actual Result: Shopping cart page is opened, selected bundle option is presented in cart

Then click "Proceed to Checkout" button under Summary block of shopping cart
Actual Result: The first checkout step - Shipping - is opened

The same situation for bundle2 product

So we cannot reproduce it, first checkout step is opened, there is no modal window for login or create new account. Probably we missed some setting or configuration.
Could you pls provide a little bit more information about configuration/settings/extensions/Magento mode that You used?

**Comment by twistedindustries** [comment] 2016-06-08 19:28
@sdzhepa Thanks for getting back to me, I just ran through it again and came up with the same results.  Here are the details of my setup:

Installed Magento 2.0.7 using default settings (Downloaded from magentocommerce.com, maybe that is part of the issue) I added and changed nothing besides what is outlined below.
Changed two settings:
Stores>Configurations>General>Search Engine Robots Set Default Robots to "No index, no follow"
Stores>Configurations>Sales>Checkout "After Adding a Product Redirect to Shopping Cart" = YES
Disabled All Cache under Cache Management

Create 1 Category and Place it under Default Category I called mine "Purchase"

Add 1 Simple Product Using these Settings and leaving everything else default:
Quantity : 100 - In Stock
Weight: Does this item have weight NO
Advanced Settings > Auto Settings > Visibility: Not Visible Individually

Add 1 Bundle Product Using these Settings and leaving everything else default:
Sku: Dynamic
Quantity: In Stock
Weight: Fixed 100lbs
Categories: Purchase (Newly made category)
Ship Bundle Items: Together
Bundle Item Settings:
1 Radio Button Option using default settings and simple product.

I tested this by going to the site, adding the bundle product to the cart from the product view page and then clicking "Proceed to Checkout" button on the cart page.  Tested in Firefox, Chrome, and Safari with all the same resulting in the login popup modal activating when clicking Proceed to Checkout.  After refreshing 2 times I was able to checkout as expected.

I have this isolated as a test on a server if you would like to see for yourself.

**Comment by ricardojle** [comment] 2016-06-17 01:15
I have the same problem.
The best way to simulate the problem:

```
change the config -> Settings / Sales / Checkout / After Adding a Product Redirect to Shopping Cart = yes

delete the browser cache
add item to my cart
click proceed to checkout
```

The problem occurs only once , that is, on the first visit . Then it works normally.

**Comment by SerhiyShkolyarenko** [comment] 2016-10-03 14:52
@rafaelstz performed that steps on 2.0.9 and didn't reproduce the issue in default mode. Do you have a message 'You added ... to your shopping cart.'?
Any other ideas on steps to reproduce?

**Comment by SerhiyShkolyarenko** [comment] 2016-10-25 14:31
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by SerhiyShkolyarenko** 2016-10-25 14:31 UTC
Labels: bug report, Progress: needs update, Component: Checkout
