### ISSUE TITLE
Error when consumers start

### ISSUE THREAD

**Issue by chrom** [magento/magento2#35393] opened 2022-04-28 10:53 UTC
### Preconditions (*)
1. docker container from markshust
2. last version of magento

### Steps to reproduce (*)
1. Install last version m2 2.4.4
2. install sample data
3. run `./bin/magento queue:consumers:start async.operations.all -vvv`

### Expected result (*)
1. running consumers

### Actual result (*)
Error: 
`./bin/magento queue:consumers:start async.operations.all -vvv 
/bin/sh: /tmp/_MEIH7Urg9/libreadline.so.7: no version information available (required by /bin/sh)

In ErrorHandler.php line 61:
                                                                                                                                                                               
  [Exception]                                                                                                                                                                  
  Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/vendor/magento/framework-amqp/Config.php on line 143  
                                                                                                                                                                               

Exception trace:
  at /var/www/html/vendor/magento/framework/App/ErrorHandler.php:61
 Magento\Framework\App\ErrorHandler->handler() at n/a:n/a
 trim() at /var/www/html/vendor/magento/framework-amqp/Config.php:143
 Magento\Framework\Amqp\Config->createConnection() at /var/www/html/vendor/magento/framework-amqp/Config.php:169
 Magento\Framework\Amqp\Config->getChannel() at /var/www/html/vendor/magento/framework-amqp/Queue.php:156
 Magento\Framework\Amqp\Queue->subscribe() at /var/www/html/vendor/magento/module-asynchronous-operations/Model/MassConsumer.php:76
 Magento\AsynchronousOperations\Model\MassConsumer->process() at /var/www/html/vendor/magento/module-message-queue/Console/StartConsumerCommand.php:94
 Magento\MessageQueue\Console\StartConsumerCommand->execute() at /var/www/html/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/magento/framework/Interception/Interceptor.php:58
 Magento\MessageQueue\Console\StartConsumerCommand\Interceptor->___callParent() at /var/www/html/vendor/magento/framework/Interception/Interceptor.php:138
 Magento\MessageQueue\Console\StartConsumerCommand\Interceptor->Magento\Framework\Interception\{closure}() at /var/www/html/vendor/magento/framework/Interception/Interceptor.php:153
 Magento\MessageQueue\Console\StartConsumerCommand\Interceptor->___callPlugins() at /var/www/html/generated/code/Magento/MessageQueue/Console/StartConsumerCommand/Interceptor.php:23
 Magento\MessageQueue\Console\StartConsumerCommand\Interceptor->run() at /var/www/html/generated/code/Magento/MessageQueue/Console/StartConsumerCommand/Proxy.php:143
 Magento\MessageQueue\Console\StartConsumerCommand\Proxy->run() at /var/www/html/vendor/symfony/console/Application.php:1009
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/magento/framework/Console/Cli.php:115
 Magento\Framework\Console\Cli->doRun() at /var/www/html/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /var/www/html/bin/magento:23

queue:consumers:start [--max-messages MAX-MESSAGES] [--batch-size BATCH-SIZE] [--area-code AREA-CODE] [--single-thread] [--multi-process [MULTI-PROCESS]] [--pid-file-path PID-FILE-PATH] [--] <consumer>

`

**Comment by chrom** [comment] 2022-04-28 10:56
I found this issue here https://github.com/magento/magento2/issues/35380
This is a duplicate, pls close this issue.

**Comment by engcom-November** [comment] 2022-04-28 14:14
Hi @chrom ,
Thank you for reporting and collaboration.  We are closing this issue as its a duplicate of https://github.com/magento/magento2/issues/35380. Please move on to this ticket for latest updates/ solutions.
Thank you.

**Closed as completed by engcom-November** 2022-04-28 14:14 UTC
Labels: duplicate, Issue: ready for confirmation, Reported on 2.4.4
