### ISSUE TITLE
Magento is no refreshing the cart page if you delete a product from cart side block

### ISSUE THREAD

**Issue by addison74** [magento/magento2#11292] opened 2017-10-07 19:43 UTC
### Preconditions

1.  Magento CE 2.1.8
2.  Apache 2.4.10, PHP 7.0.23 w/ opcache, Percona MySQL 5.3.37-82-2

### Steps to reproduce

1. Add a product to cart
2.  Go to cart page
3.  Delete the product from cart side block

### Expected result

1.  Cart page should be refreshed partially via AJAX showing no products

### Actual result

1. Cart page still shows the product in cart, even the cart side block is empty
2. If you reload the page it will be empty as it should be

### Before Deleting the product

![side_cart_1](https://user-images.githubusercontent.com/8360474/31311220-352b21de-abb0-11e7-9e32-5861e5ac4253.jpg)

### After Deleting the product

![side_cart_2](https://user-images.githubusercontent.com/8360474/31311223-3820b85e-abb0-11e7-9721-84a32bcdf460.jpg)

**Comment by orlangur** [comment] 2017-10-08 16:36
Observed system behavior is correct. Asynchronous actions performed via AJAX, like removing item in cart sidebar, must not cause a full page reload. Are there any pages behaving like this in core currently?

Shopping cart page may be AJAXified though using some extension or your custom implementation, for your particular store you may even implement full page reload as you suggest, but this is not something which needs to be changed in core.

**Comment by addison74** [comment] 2017-10-08 16:54
Please check Magento 1.9.3.6 behavior related to this issue. Removing the item from cart side block the page will update according to your action, without any reloading.

This is a bug and creates confusion. Once you delete the product from cart side block AJAX should do the job removing that product from cart page. If you consider this a correct behavior just hide cart side block if the current page is cart page.

**Comment by orlangur** [comment] 2017-10-08 17:16
> Removing the item from cart side block the page will update according to your action, without any reloading.

Is sidebar updated via AJAX in 1.9.x? Is main content area of shopping cart page updated via AJAX as well?

What would be really confusing to user is full page reload when he interacts with cart sidebar block.

**Comment by korostii** [comment] 2017-11-23 14:44
> What would be really confusing to user is full page reload when he interacts with cart sidebar block.

So you're saying that main content area should be updated without page reload by the same piece of JS? That makes perfect sense.

**Comment by orlangur** [comment] 2017-11-23 14:48
>  should be updated without page reload

@korostii, _could_ be updated. For core such behavior seems to be a feature request, there are quite a lot of AjaxCart extensions in the market though.

**Comment by korostii** [comment] 2017-11-23 16:17
I mean it's pretty strange to take aim at the specific solution suggested in the bug report, instead of discussing the issue itself.

Cart content is getting out of sync with the minicart - that's clearly a bug. Whether there are 3rd-party extensions "fixing" this or other known workarounds is irrelevant.

**Comment by addison74** [comment] 2017-11-23 19:36
This is a bug. It is clear to me Magento Team doesn't want to check Magento 1 for this behavior. If they could check they will see immediately this issue. Normally Magento 2 should keep all features available from Magento 1. This one is a bug, trust me I played thousands of times with Magento 1 and I saw this issue in version 2 from the very beginning. 

Maybe it is better to find an extension, or keep it close, but disappointing loyal people who would like to find Magento 2 same like Magento 1.

**Comment by orlangur** [comment] 2017-11-24 09:51
Ok, let's @magento-engcom-team decide whether it's a bug or a feature request.

**Comment by orlangur** [comment] 2017-11-24 10:47
@ADDISON74, for the record

> Expected result
> Cart page should refresh and shows no product

Such behavior looks like a poor UX to me. Removing item from minicart staying on Shopping Cart page is quite a nonrealistic scenario. Proper expected result is updating page main content via AJAX or something.

**Comment by magento-engcom-team** [comment] 2017-11-27 14:07
@ADDISON74, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1

**Comment by magento-engcom-team** [comment] 2017-11-28 10:03
@ADDISON74, thank you for your report.
We've created internal ticket(s) MAGETWO-84614 to track progress on the issue.

**Comment by Microguru** [comment] 2018-09-10 18:44
This error is still their in magento 2.5.5
Cart product count is not getting updated ,when cart item is remove  programmatically .

**Comment by Ctucker9233** [comment] 2018-11-17 20:12
@magento-engcom-team A year later and still no fix?

**Comment by orlangur** [comment] 2018-11-18 00:52
@Ctucker9233 such scenario is still quite nonrealistic. I don't see this issue got much upvotes, isn't it?

> Cart product count is not getting updated ,when cart item is removed programmatically

@Microguru looks like you're not invalidating private data accordingly.

**Comment by Ctucker9233** [comment] 2019-03-05 22:38
@orlangur Just wondering what was up with this, since its old and still open. If it's a non-issue, why is it still open?

**Comment by orlangur** [comment] 2019-03-06 11:32
@Ctucker9233 refreshing the whole page would be really lame UX, so, expected result here in description is wrong. Looks like just nobody bothered to fix current behavior - as I mentioned earlier, this scenario is quite nonrealistic.

**Comment by addison74** [comment] 2019-03-06 20:34
If nobody was bothered to fix this issue it doesn't mean it is fixed by default. As an engineer I have to analyze all aspects that could potentially create trouble without letting my users to discover them. This means being a pro. Thanks God this is not aircraft industry!

I will recommend to all my clients continuing using Magento 1 as much as they can. There a many wrong UX aspects in Magento 2 really annoying and not fixed yet. This one is a long time bug and should be fixed by now. Remember, Magento 1 is dealing with this out of the box!

@orlangur: If you are satisfy by this non-realistic scenario I am really sorry I reported it before. As you can see other people are finding my post. Anyway many sorry. It is easy to contest, trying finding votes, than admitting the real facts. This attitude made me to stop reporting bugs in Magento 2. Believe me I report daily bugs in many places but never find such of attitude.

**Comment by orlangur** [comment] 2019-03-13 15:15
@ADDISON74,

> There a many wrong UX aspects in Magento 2 really annoying and not fixed yet

Reloading the full page would be a poor UX compared to current one.

There is nothing to sorry about, did you elaborate a kind of fix maybe if you faced with it on real projects?

I didn't say a word that this issue should not be fixed, just that there are much more important ones, for example https://github.com/magento/magento2/issues/3625.

Every report matters and also it is important to vote to highlight some of them.

**Comment by aKalisch** [comment] 2019-04-02 04:52
@ADDISON74 it‘s bad layout and ux to have a shopping cart sidebar on the actual shopping cart ;-)

Maybe just remove the sidebar if you are at the cart page as stated above.

**Comment by ADDISON74** [comment] 2019-04-02 21:08
@Kalisch: Magento 2 Team should provide a solution not me. I gave up Magento 2 which in my opinion is far away from Magento 1 in many aspects. I reported this issue because in Magento 1 is working out of the box (RWD theme). End of story.

You mentioned it is a bad layout and UX to have a shopping cart sidebar visible in cart page. Please let me know how many online stores do you know which are hiding the cart sidebar when visiting the cart page. Just for improving my knowledge.

**Comment by magento-engcom-team** [comment] 2019-09-03 18:20
Hi @ADDISON74. Thank you for your report. 
The issue has been fixed in magento/magento2#22478 by @ravi-chandra3197 in 2.3-develop branch
Related commit(s):
 - [60a465c9c83d4b2c33583f1028bf29f9143c516c](https://github.com/magento/magento2/commit/60a465c9c83d4b2c33583f1028bf29f9143c516c)
 - [c08dffb1d32d3c5786076bcf51c50fae622ede66](https://github.com/magento/magento2/commit/c08dffb1d32d3c5786076bcf51c50fae622ede66)
 - [7d481bdfa764e6f8a20a9381c26f1b3696fe199f](https://github.com/magento/magento2/commit/7d481bdfa764e6f8a20a9381c26f1b3696fe199f)
 - [ce6c2288f0a386bb79688e7e6d3232e519ec2ae3](https://github.com/magento/magento2/commit/ce6c2288f0a386bb79688e7e6d3232e519ec2ae3)
 - [b370b1e5f0005f17ebbe6e637cdb65b51f9710ea](https://github.com/magento/magento2/commit/b370b1e5f0005f17ebbe6e637cdb65b51f9710ea)
 - [bcd75f44e9c9e126571ddb126ea6a7bb3ab5c9fb](https://github.com/magento/magento2/commit/bcd75f44e9c9e126571ddb126ea6a7bb3ab5c9fb)
 - [73b96122f3df5c99dfc25a809a725e54e2039998](https://github.com/magento/magento2/commit/73b96122f3df5c99dfc25a809a725e54e2039998)
 - [49936baec526f950e3b6d3affd67e85299bc4fad](https://github.com/magento/magento2/commit/49936baec526f950e3b6d3affd67e85299bc4fad)
 - [aa7ac82dfd96e4410695cb0cda1bb44e0c65b0a4](https://github.com/magento/magento2/commit/aa7ac82dfd96e4410695cb0cda1bb44e0c65b0a4)

The fix will be available with the upcoming 2.3.4 release.

**Closed as completed by magento-engcom-team** 2019-09-03 18:20 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by ADDISON74** [comment] 2021-05-02 13:14
I recently installed Magento 2.4.2 and I discovered that this issue was fixed, beyond the smiles of some people who thought they were superior. In life you may meet many people who try to make you give up, but it is good to see your interest and never give up. Maybe the problem of these people comes from education, good manners, location.

A white ball for the Magento team anyway.
