### ISSUE TITLE
Image link broken on product Description and short description part.

### ISSUE THREAD

**Issue by kishan7172** [magento/magento2#10169] opened 2017-07-06 23:34 UTC
When I try to add image in product short description after I logout from Admin an image link is broken and once I visited front end of website I did not see any image in product description. I will share you screenshot below,please look into that it will help me to fix issue.
![admin_screenshot](https://user-images.githubusercontent.com/29963923/27964951-ec76936a-62ee-11e7-8c2d-883176ea6405.png)
![front_end](https://user-images.githubusercontent.com/29963923/27964952-ec7e85d4-62ee-11e7-8a8b-f120109a2027.png)

### Preconditions

1. Magento 2.1.5 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1.  Image link is broken once logout from admin

### Actual result

1. [Screenshot, logs]

**Comment by korostii** [comment] 2017-07-07 14:53
> Expected result
> Image link is broken

That can't be right. 
Could you please update the issue descriptions with some more details? If you don't feel comfortable explaining it in text, a couple of screenshots instead is also fine.

**Comment by veloraven** [comment] 2017-07-25 06:43
@kishan7172 thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please clarify steps, expected and actual result.

**Comment by hostep** [comment] 2017-07-25 06:52
This is most likely a duplicate of https://github.com/magento/magento2/issues/6138, which should get [fixed](https://github.com/magento/magento2/pull/10131) in Magento 2.1.8

**Comment by magento-engcom-team** [comment] 2017-09-11 21:08
@kishan7172 we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue

**Closed as completed by magento-engcom-team** 2017-09-11 21:08 UTC
Labels: Progress: needs update, Issue: Format is valid
