### ISSUE TITLE
Klarna configure button disabled in admin

### ISSUE THREAD

**Issue by JannMulton** [magento/magento2#29421] opened 2020-08-06 12:08 UTC
Resolution of this issue will be provided in the scope of internal tickets
- `BUNDLE-2831` [Klarna 2.4.2] Remove dependency on PayPal module
- `BUNDLE-2832` [Klarna 2.3.7] Remove dependency on PayPal module

### Preconditions (*)

1. Magento 2.3.2 + can be reproduced on the 2.3.5-p2 and 2.4.0 composer versions
2. PHP 7.2

### Steps to reproduce (*)

1. Disable Magento_Paypal
2. Enable Klarna payment (Klarna_Core, Klarna_Ordermanagement, Klarna_Kp)

### Expected result (*)

1. Klarna configure button enabled
![image](https://user-images.githubusercontent.com/23705682/89530016-73073400-d7f6-11ea-91e3-ae0e3b304dfd.png)

### Actual result (*)

Configure button is disabled
![image](https://user-images.githubusercontent.com/23705682/89530044-7dc1c900-d7f6-11ea-967b-af3c9753f97a.png)

<button type="button" **disabled="disabled"** class="button action-configure **disabled**" id="payment_klarna_section_klarna-head"

After enabling the Paypal, the configure button will be enabled

### Additional information

- Based on Klarna support response the issue on the Magento side https://github.com/magento/magento2/issues/29421#issuecomment-671829461
- Detailed steps and confirmation on the latest releases https://github.com/magento/magento2/issues/29421#issuecomment-673597629
- Result of RCA: https://github.com/magento/magento2/issues/29421#issuecomment-674109298

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ihor-sviziev** [comment] 2020-08-06 15:05
Hi @JannMulton,
Thank you for your report!

This report relates to bundled extension and not to Magento, support of this extension is available on Magento Marketplace:
https://marketplace.magento.com/klarna-m2-checkout.html#product.info.details.support

Please contact the support in order to resolve this issue.

BR,
Ihor

**Comment by JannMulton** [comment] 2020-08-07 07:50
Klarna is part of Magento core and not installed separately

**Comment by ihor-sviziev** [comment] 2020-08-07 14:50
@JannMulton it would be better to submit issue to support since the Klarna is vendor bundled extensions and we don’t control it’s source code

**Comment by JannMulton** [comment] 2020-08-11 09:11
Klarna response to this
![image](https://user-images.githubusercontent.com/23705682/89879551-cd740c00-dbcb-11ea-8bc8-cfbee00e5920.png)

**Comment by ihor-sviziev** [comment] 2020-08-11 09:18
@JannMulton thank you so much for your response! I'll re-open this issue.

@engcom-Alfa @engcom-Bravo @engcom-Charlie could you verify this issue?

**Comment by sdzhepa** [comment] 2020-08-12 20:31
@engcom-Alfa 
Could you please check this issue on the latest released 2.3.x and 2.4.x composer version?
Probably this issue is already fixed in the current versions.

**Comment by engcom-Alfa** [comment] 2020-08-13 17:07
Hi @ihor-sviziev @sdzhepa @JannMulton . We can confirm that this problem can be reproduced on the 2.3.5-p2 and 2.4.0 composer versions.

**Manual testing scenario** (for 2.4.0 composer)

1. Disable `Magento_Paypal`:
run in console: `php bin/magento module:disable Magento_Paypal PayPal_Braintree Amazon_Payment Amazon_Login Amazon_Core Magento_PaypalGraphQl`

_info:_ To disable PayPal, you must also disable the depend to it, modules.

2. Go to Admin -> Stores -> Configuration -> Sales -> Payment Methods ;

**Actual Result :** :heavy_multiplication_x: it is not possible to configure the **Klarna** payment method. Configure button is disabled.

`Magento 2.3.5-p2 composer`

![Screenshot from 2020-08-13 14-50-05](https://user-images.githubusercontent.com/51679138/90163771-3495ea00-dd9f-11ea-8c70-d04ec782e8a3.png)

`Magento 2.4.0 composer`

![2020-08-13_15-18](https://user-images.githubusercontent.com/51679138/90163802-41b2d900-dd9f-11ea-983b-a8c75e05e41f.png)

For a more detailed investigation, whether this problem is related to Magento or directly to the Klarna payment method, and possible solutions we asked for help from developers. 
Based on the results of the investigation, a comment will be left here.

Thanks!

**Comment by engcom-Charlie** [comment] 2020-08-14 14:45
by default (when all modules are enabled) all **Configure** button go from backend as disabledduring the page loads in `module-paypal/view/adminhtml/web/js/solutions.js` in function `wipeButtonsConfiguration()` is removing attribute disable from all `.button.action-configure` (for Klarna Config button also).
![image](https://user-images.githubusercontent.com/51680850/90261476-ac265080-de55-11ea-8c7c-5f8c90b3457b.png)

So when we disable PayPal, this file doesn't include and we have this issue.

**Comment by magento-engcom-team** [comment] 2020-08-14 17:59
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36756` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by lfluvisotto** [comment] 2020-09-14 04:42
@magento I'm working on it

**Comment by lfluvisotto** [comment] 2020-09-14 04:49
@ihor-sviziev or @sdzhepa could any of you review the PR #30022 ?

**Comment by lfluvisotto** [comment] 2020-10-15 01:23
This issue should be closed, here are the arguments and facts:

1) Klarna_Core has dependency of Mage_Paypal > app/code/Klarna/Core/etc/module.xml:19

2) Klarna_Core composer is missing the require declaration of magento/module-paypal > app/code/Klarna/Core/composer.json:42

3) For Klarna_Core works without dependency of Mage_Paypal, Klarna_Core must remove the dependency on > app/code/Klarna/Core/etc/adminhtml/system.xml:19

4) Klarna_Core must put the business logic on > protected function _getHeaderTitleHtml($element) inside of its own module

FYI @JannMulton + @ihor-sviziev + @sdzhepa + @sidolov + @engcom-Charlie

**Comment by ihor-sviziev** [comment] 2020-10-15 04:54
@engcom-Charlie could you confirm that issue not inside magento, but inside the Klarna module?

**Comment by sdzhepa** [comment] 2020-10-29 20:29
Hello @JannMulton @ihor-sviziev

This issue was reviewed and discussed with Klarna. 
As a result, it was confirmed and added to the backlog related to Klarna:
- `BUNDLE-2831` [Klarna 2.4.2] Remove dependency on PayPal module
- `BUNDLE-2832` [Klarna 2.3.7] Remove dependency on PayPal module

**Comment by ihor-sviziev** [comment] 2020-10-30 04:20
@sdzhepa so the issue not in magento and we can close this one?

**Comment by ihor-sviziev** [comment] 2021-01-29 04:57
@sidolov @sdzhepa, could you confirm that this issue in the Klarna module and not in Magento?

**Comment by sdzhepa** [comment] 2021-01-29 17:50
Hello @ihor-sviziev 
cc: @sidolov @JannMulton @lfluvisotto

Thank you for reminding this issue!
At the moment when I posted this https://github.com/magento/magento2/issues/29421#issuecomment-719003342 was not clear the root cause of this bug. In the comments was the response from Klarna support https://github.com/magento/magento2/issues/29421#issuecomment-671829461 and also arguments why it's not related to Magento code https://github.com/magento/magento2/issues/29421#issuecomment-674109298

To escalate the investigation I created additional internal tickets to the team's backlog who collaborating with Vendors Bundle Extensions. And keep this issue open for updates.

I have checked the current status of these tickets `BUNDLE-2831`, `BUNDLE-2832`. All of them are completed and merged into `ext-klarna`. As I can see fix should be available in the `2.3.7` and `2.4.2` releases.

I think we can close it now

**Comment by magento-engcom-team** [comment] 2021-01-29 17:51
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Closed as completed by sdzhepa** 2021-01-29 17:50 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Issue: Format is valid, Priority: P3, Severity: S2, Progress: done, Reported on 2.3.2
