### ISSUE TITLE
Configurable swatch not working for price in Listing/Category Page

### ISSUE THREAD

**Issue by jayankaghosh** [magento/magento2#10976] opened 2017-09-21 04:54 UTC
__Preconditions__

1. Magento version 2.1.8
2. PHP version 7.0.22
3. Apache2 running on an Ubuntu 16.04 environment 
2. Install Default LUMA theme if not present
3. Install Sample Data through CLI

__Steps to reproduce__

1. Add configurable product
2. Add associated simple products based on some configurable attribute (let's say color)
3. Set different price for each color (Let's say Blue 350 INR and Green 400 INR)
4. Set different image for each color as well

__Expected result__

1. On product listing page (also called category page) price and image of product should change when selecting a different variation of color

__Actual result__

1. Image changes as expected while price stays the same

**Comment by jayankaghosh** [comment] 2017-10-06 17:10
Any updates on this?

**Comment by magento-engcom-team** [comment] 2017-10-11 19:03
@jayankaghosh, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-11 19:03 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid

**Comment by eduard-kistner** [comment] 2017-11-27 11:12
As i am currently have the same probs and the customer wants it corrected, is an downgrade to CE 2.1 planned?
At the moment there seems to be related changes in 2.2.* but not backported to 2.1.10 ( seems to be handled with MAGETWO-47017 commits ).

As not everyone is planning to upgrade to 2.2 but need the functionality it would IMO be nice to add Links to the commits which fixed that in 2.2.
