### ISSUE TITLE
"The configuration parameter "componentType" is a required for "advanced_inventory_modal" component".

### ISSUE THREAD

**Issue by bartoszkubicki** [magento/magento2#5734] opened 2016-07-21 13:29 UTC
I have upgrade magento 2.05 to Magento 2.1, but I have old db structure - I haven't erased my old products and attributes.
Following error occurs while i click on add new Product. 
Now after clean installation of magento and adding attributes again it doesn't happen - maybe it is case connected with changing version of Magento. However it should not occur this way... 

I wa trying to debug this `parameter "componentType" is a required for "advanced_inventory_modal"`, but even on working copy of Magento 2.1 it was empty in `UiComponentFactory`.

`a:4:{i:0;s:99:"The configuration parameter "componentType" is a required for "advanced_inventory_modal" component.";i:1;s:7712:"#0 /srv/html/dev/motion-dev/vendor/magento/framework/View/Element/UiComponentFactory.php(360): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false)
#1 /srv/html/dev/motion-dev/vendor/magento/framework/View/Element/UiComponentFactory.php(272): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false)
#2 /srv/html/dev/motion-dev/vendor/magento/framework/View/Element/UiComponentFactory.php(164): Magento\Framework\View\Element\UiComponentFactory->mergeMetadata('product_form', Array, false)
#3 /srv/html/dev/motion-dev/vendor/magento/framework/View/Layout/Generator/UiComponent.php(124): Magento\Framework\View\Element\UiComponentFactory->create('product_form', NULL, Array)
#4 /srv/html/dev/motion-dev/vendor/magento/framework/View/Layout/Generator/UiComponent.php(93): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'product_form', Array, Object(Magento\Framework\View\Layout\Interceptor))
#5 /srv/html/dev/motion-dev/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#6 /srv/html/dev/motion-dev/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#7 /srv/html/dev/motion-dev/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#8 /srv/html/dev/motion-dev/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#9 /srv/html/dev/motion-dev/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#10 /srv/html/dev/motion-dev/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#11 /srv/html/dev/motion-dev/vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#12 /srv/html/dev/motion-dev/vendor/magento/framework/View/Layout.php(859): Magento\Framework\View\Layout->build()
#13 /srv/html/dev/motion-dev/var/generation/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#14 /srv/html/dev/motion-dev/vendor/magento/module-backend/Model/View/Result/Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#15 /srv/html/dev/motion-dev/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Catalog...')
#16 /srv/html/dev/motion-dev/vendor/magento/module-catalog/Controller/Adminhtml/Product/NewAction.php(71): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Catalog...')
#17 /srv/html/dev/motion-dev/var/generation/Magento/Catalog/Controller/Adminhtml/Product/NewAction/Interceptor.php(24): Magento\Catalog\Controller\Adminhtml\Product\NewAction->execute()
#18 /srv/html/dev/motion-dev/vendor/magento/framework/App/Action/Action.php(102): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->execute()
#19 /srv/html/dev/motion-dev/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#20 /srv/html/dev/motion-dev/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /srv/html/dev/motion-dev/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->___callParent('dispatch', Array)
#22 /srv/html/dev/motion-dev/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor), Array, 'adminAuthentica...')
#23 /srv/html/dev/motion-dev/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#24 /srv/html/dev/motion-dev/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#25 /srv/html/dev/motion-dev/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor), Array, 'adminMassaction...')
#26 /srv/html/dev/motion-dev/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#27 /srv/html/dev/motion-dev/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#28 /srv/html/dev/motion-dev/var/generation/Magento/Catalog/Controller/Adminhtml/Product/NewAction/Interceptor.php(39): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->___callPlugins('dispatch', Array, Array)
#29 /srv/html/dev/motion-dev/vendor/magento/framework/App/FrontController.php(55): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#30 /srv/html/dev/motion-dev/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#31 /srv/html/dev/motion-dev/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#32 /srv/html/dev/motion-dev/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#33 /srv/html/dev/motion-dev/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#34 /srv/html/dev/motion-dev/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /srv/html/dev/motion-dev/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#36 /srv/html/dev/motion-dev/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /srv/html/dev/motion-dev/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#38 /srv/html/dev/motion-dev/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#39 {main}";s:3:"url";s:127:"/admin_159b1p/catalog/product/new/set/4/type/downloadable/key/cf1bcae453b6b4a3d28e60b97e17b934e4e3f114ee62edfecf7870b8c0a81f79/";s:11:"script_name";s:10:"/index.php";}`

**Comment by dengfan** [comment] 2016-07-29 08:18
I have upgrade magento 2.0.6 to Magento 2.1.0, and i have the same problem.
When I clean caches and batch execute  update attributes action for products, It's be OK.
But a few days later, it again errors!

`a:4:{i:0;s:99:"The configuration parameter "componentType" is a required for "advanced_inventory_modal" component.";i:1;s:7487:"#0 /var/www/magento2206/vendor/magento/framework/View/Element/UiComponentFactory.php(360): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false)
#1 /var/www/magento2206/vendor/magento/framework/View/Element/UiComponentFactory.php(272): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false)
#2 /var/www/magento2206/vendor/magento/framework/View/Element/UiComponentFactory.php(164): Magento\Framework\View\Element\UiComponentFactory->mergeMetadata('product_form', Array, false)
#3 /var/www/magento2206/vendor/magento/framework/View/Layout/Generator/UiComponent.php(124): Magento\Framework\View\Element\UiComponentFactory->create('product_form', NULL, Array)
#4 /var/www/magento2206/vendor/magento/framework/View/Layout/Generator/UiComponent.php(93): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'product_form', Array, Object(Magento\Framework\View\Layout\Interceptor))
#5 /var/www/magento2206/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#6 /var/www/magento2206/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#7 /var/www/magento2206/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#8 /var/www/magento2206/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#9 /var/www/magento2206/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#10 /var/www/magento2206/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#11 /var/www/magento2206/vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#12 /var/www/magento2206/vendor/magento/framework/View/Layout.php(859): Magento\Framework\View\Layout->build()
#13 /var/www/magento2206/var/generation/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#14 /var/www/magento2206/vendor/magento/module-backend/Model/View/Result/Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#15 /var/www/magento2206/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Catalog...')
#16 /var/www/magento2206/vendor/magento/module-catalog/Controller/Adminhtml/Product/Edit.php(69): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Catalog...')
#17 /var/www/magento2206/var/generation/Magento/Catalog/Controller/Adminhtml/Product/Edit/Interceptor.php(24): Magento\Catalog\Controller\Adminhtml\Product\Edit->execute()
#18 /var/www/magento2206/vendor/magento/framework/App/Action/Action.php(102): Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->execute()
#19 /var/www/magento2206/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#20 /var/www/magento2206/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /var/www/magento2206/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->___callParent('dispatch', Array)
#22 /var/www/magento2206/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor), Array, 'adminAuthentica...')
#23 /var/www/magento2206/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#24 /var/www/magento2206/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#25 /var/www/magento2206/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor), Array, 'adminMassaction...')
#26 /var/www/magento2206/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))`

**Comment by andimov** [comment] 2016-08-02 10:31
@bartek9007 
To allow us to research the issue, please, format description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by bartoszkubicki** [comment] 2016-08-04 07:10
@andimov 
updated a liitle - it's hard to add more in this case I have updated Magento and it has just happend. If it just upgrading error, possible reasons ar also welcome.

**Comment by magelifesaver** [comment] 2016-08-10 21:20
I have the same issue when adding or editing products.

Is this a core issue. I'm not sure if I should continue looking for a solution or what for Magento to resolve this.

Thanks,
Marsel

**Comment by j1nx3d** [comment] 2017-03-17 19:58
Hi guys, 

I was having the same issue, This help me to solve it, but with this new magento version could be another issue showing the same error.  Happened to me with other issues.

## Steps to reproduce
1. Install Magento 2.1.4 from any source.
2. Module **Magento_CatalogInventory** to **Disable** (Stores/Configuration/Advanced/Advanced)
3. Go to edit or create a new product
## Expected result
1. Product available for creation or update without Inventory management.
## Actual result
1. Exception error
## Issue
The configuration parameter "componentType" is a required for "advanced_inventory_modal" component.

Regards,

**Comment by vityakopin** [comment] 2017-07-21 10:28
Thanks for reporting this issue. We've created internal ticket MAGETWO-70918.

**Comment by magento-engcom-team** [comment] 2017-10-13 17:00
@bartek9007, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-13 17:00 UTC
Labels: Issue: Ready for Work, bug report, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid
