### ISSUE TITLE
Setup Install 2.4.6 Only Possible with OpenSearch

### ISSUE THREAD

**Issue by laurnts** [magento/magento2#37236] opened 2023-03-18 04:33 UTC
### Preconditions and environment

- Magento version 2.4.6
- Running php bin/magento setup:install --search-engine=elasticsearch8 ... will returned an error during installation

### Steps to reproduce

1. Ensure Elasticsearch 8.4 is installed
2. Ensure Magento 2.4.6 composer installation works
3. Run php bin/magento .... --search-engine=elasticsearch8

### Expected result

A successful Magento2 setup installation while using elasticsearch as the search engine

### Actual result

Could not validate a connection to the OpenSearch. No alive nodes found

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magenx** [comment] 2023-03-18 17:25
yes, just tested with elasticsearch 8.6:
installed with `--search-engine=elasticsearch7 `
i dont see anything elasticsearch 8 related,
when you change in menu to opensearch search engine, magento works ok 🤕

**Comment by lcw-media** [comment] 2023-03-21 07:55
At first, try installing the official magento 2 Elasticsearch 8 Module:

composer require magento/module-elasticsearch-8 --with-all-dependencies


Then, try installing with following parameters:

bin/magento setup:install --disable-modules=Magento_InventoryElasticsearch,Magento_Elasticsearch8,Magento_Elasticsearch,Magento_OpenSearch


After setup is done, enable modules again (Dont enable Magento_OpenSearch again):

bin/magento module:enable Magento_InventoryElasticsearch Magento_Elasticsearch8 Magento_Elasticsearch


Change default search engine to elasticsearch 8:
bin/magento config:set catalog/search/engine 'elasticsearch8'


Start Magento Setup: (ElasticSearch 8 Service should run while starting setup again ;) )

bin/magento setup:upgrade
bin/magento setup:di:compile


Good Luck!

**Comment by magenx** [comment] 2023-03-21 10:39
this must be in documentation, not hidden somewhere in github issue.

i think installation must be also very simple.
this is not an upgrade.
and the other problem it will not work with xpack security enabled.

then opensearch also have issues with security plugin enabled.

the only working installation with proper authentication is elasticsearch 7

**Comment by oneserv-heuser** [comment] 2023-03-21 10:43
I can confirm the issue in v2.4.6, even integration tests are failing in setup if you have ElasticSearch 8 installed and not ElasticSearch7 or OpenSearch.

**Comment by magenx** [comment] 2023-03-21 10:53
feels like issue is coming from adobe commerce cloud platform, they run opensearch without security plugin
probably thats why nothing ever was properly tested

**Comment by laurnts** [comment] 2023-03-21 11:00
> this must be in documentation, not hidden somewhere in github issue.
> 
> i think installation must be also very simple. this is not an upgrade. and the other problem it will not work with xpack security enabled.
> 
> then opensearch also have issues with security plugin enabled.
> 
> the only working installation with proper authentication is elasticsearch 7

Completely agree with MagenX here. The setup install of Magento2 provide the option to use elasticsearch and opensearch respectively (unlike the previous version before where it gets mixed). Thus the installation should be straight forward.

Also the xpack security enabled needed to be disabled (false). Else the node cluster canno't be found error will get triggered.

Aside from that (not related to this ticket). varnish.vcl can only export version 6 while in 2.4.6 Varnish 7 is supported.

**Comment by magenx** [comment] 2023-03-24 11:41
i wasted all weekend to find out this, running different setups like crazy.
adobe fiddled around for `217` days and came up with a broken release, a non-working core component without which the whole patform can't be installed... now it's my time to whine...

**Comment by FadedOut** [comment] 2023-03-24 19:47
> i wasted all weekend to find out this, running different setups like crazy. adobe fiddled around for `217` days and came up with a broken release, a non-working core component without which the whole patform can't be installed... now it's my time to whine...

Such oversight makes me want to rant now...

I find this happens with almost every single release they come out with. I've upgraded from 2.4.0 to each release to now 2.4.5 (I will not be updating to .6 until .6-p1) and every single "major" release (.1, .2, .3, .4, .5) has had some profoundly surprising bugs that makes you wonder who tests these releases. Almost like they test with one setup and say "good to go". It's absolutely absurd and can destroy businesses. I wonder if paying the $1500+ per month for "Adobe Commerce" has less bugs. Highly doubt it. The sad part? It's released only two weeks prior to GA (general availability) for "testing" even to those paying customers. Like really? 

I swear, whoever came up with the release schedule for this system should be fired. It's just simply not the way to do it. Smaller, quicker releases are MUCH smarter and better to do. For instance, WooCommerce (which has like 100x more store running it, like 10m compared to 500k for Magento) does releases like once per month. Those releases are MUCH smaller. Easier to deal with bugs and testing - they will also release fixes quickly after instead of making the merchant wait 4-5 months. It's also available for testing WHILE it's being developed. Adobe, for reasons unknown (probably greed somehow) keeps the testing of the dev version behind closed doors (like all those "jira" bug reports require you to be an "Adobe staff member" - like really?? thought this was open-source) so the only **REAL** testing is done in the two weeks prior to GA. Like how dumb. Then problems like this arises. Problems that should not even have happened if it were tested better. But now stores that rely on a stable eCommerce system so they can make MONEY deal with major site breaking bugs. That is explicitly why most Magento stores pay like $5k for "upgrade" teams - because of the garbage QC (quality control) that Adobe does.

It's sad because overall I think the features and usual stability of Magento is above most others, but during release time it's always a disaster. Always. So...the trick I think I'm learning? ALWAYS wait for the "p" release. Then move to that one, which should HOPEFULLY have the major release's bugs fixed. Because again, with their garbage release schedule they don't release minor point releases to fix problems like this. This major issue, and others, will only be [hopefully] fixed now 4-5 months from now with the "p" release - though knowing them, they will say "this fix is targeted for 2.4.7" or "2.4.8", at the end of 2023 or this time next year - which is just insane. Instead of doing what many other sane companies do and just come out with a minor point release (2.4.6.1) fixing major issues like this. 

Gah rant over. Good luck to anyone that updated. I will be waiting, and will always do with this system. Never have I before seen such garbage QC every release. Every...single...time. Really wish WooCommerce was more like this system (features, stability, etc.) because I would just stick with that, I trust their new releases so much more. The garbage Adobe pulls every time with these releases sours my outlook on Magento so much 😡

**Comment by mattryding** [comment] 2023-03-26 02:51
Incase this helps anyone:

- When installed without "--search-engine=elasticsearch7", I get the error: "Could not validate a connection to the OpenSearch. No alive nodes found"
- When installed using "--search-engine=elasticsearch7", install works correct

It looks like by default the install is now using OpenSearch and not ElasticSearch7?

I can't comment on ElasticSearch 8 but hopefully the above may help some people.

**Comment by n2diving-dgx** [comment] 2023-03-28 09:15
We decided to migrate M2.4.6 on CentOS 7  to Oracle Linux 8.  As part of the migration effort I took the opportunity to switch from ElasticSearch (v7.17 on CentOS) to OpenSearch (v2.6 on OL).  Attempting a straightforward install of M2.4.6 using a script that ran fine on the existing server with ElasticSearch, I discovered M2.4.6 would not install on the new server running OpenSearch, returning the "No alive nodes found" error.

The problem was OpenSearch had been installed taking the configuration defaults which included enabling ssl/https.   Checking the installation of OpenSearch the console command line with this...

curl -XGET --insecure -u 'admin:admin' 'https://localhost:9200'

All was good and the version number of OpenSearch was returned as expected.

Eventually, we discovered that disabling SSL as had been the setting with ElasticSearch, that Magento 2.4.6 would then install as expected.  See https://opensearch.org/docs/1.1/security-plugin/configuration/disable/

The command to check OpenSearch as Magento 2.4.6 seems to require it to be configured changes https to http...

curl -XGET --insecure -u 'admin:admin' 'http://localhost:9200'

It is possible that M2.4.6 has a compatibility issue with OpenSearch configuration defaults that may differ from ElasticSearch?

**Comment by magenx** [comment] 2023-03-28 10:06
working self hosted configuration for Magento 2.4.6

| | security enabled | security disabled | ssl enabled | ssl disabled ||
|  ---|   ---|  ---|  ---|  ---| --- |
| ElasticSearch 7 | **OK** | *n/a* | *error* | **OK** | |
| ElasticSearch 8 | *error* | *ok*	| *error* | *ok* | not recommended |
| OpenSearch 2.6 | *error* | *ok* | *error* | *ok* | not recommended |

**Comment by hostep** [comment] 2023-03-28 22:03
Just to add someting about ES 8, some manual steps need to be taken before Magento 2.4.6 can work with it. Out of the box it doesn't come with ES 8 support, you need to install a new composer package first: https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/prepare/prerequisites.html?lang=en#upgrade-elasticsearch

**Comment by engcom-Dash** [comment] 2023-03-31 04:56
Hi @laurnts ,

Issue Confirmed,

Verified the issue 2.4.6 magento instance and the issue is reproducible,Hence we are confirming the issue.

Preconditions:
Magento Version 2.4.6
PHP 8.1

Steps to reproduce:

- Ensure Elasticsearch 8.4 is installed
- Ensure Magento 2.4.6 composer installation works
- Run php bin/magento setup:install --search-engine=elasticsearch 8 

KIndly refer the below screenshots:
<img width="1512" alt="op2" src="https://user-images.githubusercontent.com/60198592/229011167-08c5c263-7ddc-4831-b7b4-0a975550afc5.png">
<img width="1512" alt="op1" src="https://user-images.githubusercontent.com/60198592/229011176-9b0492b5-df6c-4010-bd75-2a11979ec500.png">

We are getting actual result which is Could not validate a connection to the OpenSearch. No alive nodes found ,Hence we are confirming the issue.

Regards,

**Comment by hostep** [comment] 2023-04-04 21:46
@engcom-Dash: out of curiosity: after your second step, so _before_ the `setup:install`: did you install the extra composer package for ES8 like mentioned in [the documentation](https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/prepare/prerequisites.html?lang=en#upgrade-elasticsearch)?

**Comment by laurnts** [comment] 2023-04-11 20:09
> @engcom-Dash: out of curiosity: after your second step, so _before_ the `setup:install`: did you install the extra composer package for ES8 like mentioned in [the documentation](https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/prepare/prerequisites.html?lang=en#upgrade-elasticsearch)?

It's a good find, I will test it out if it works.



> Incase this helps anyone:
> 
> * When installed without "--search-engine=elasticsearch7", I get the error: "Could not validate a connection to the OpenSearch. No alive nodes found"
> * When installed using "--search-engine=elasticsearch7", install works correct
> 
> It looks like by default the install is now using OpenSearch and not ElasticSearch7?
> 
> I can't comment on ElasticSearch 8 but hopefully the above may help some people.

I confirm that swapping the elasticsearch8 to elasticsearch7 does work (by means of using older elasticsearch version). However I also think I've tried once running elasticsearch8 and using the install flag elasticsearch7 does work too

**Comment by laurnts** [comment] 2023-04-11 22:45
> > i wasted all weekend to find out this, running different setups like crazy. adobe fiddled around for `217` days and came up with a broken release, a non-working core component without which the whole patform can't be installed... now it's my time to whine...
> 
> Such oversight makes me want to rant now...
> 
> I find this happens with almost every single release they come out with. I've upgraded from 2.4.0 to each release to now 2.4.5 (I will not be updating to .6 until .6-p1) and every single "major" release (.1, .2, .3, .4, .5) has had some profoundly surprising bugs that makes you wonder who tests these releases. Almost like they test with one setup and say "good to go". It's absolutely absurd and can destroy businesses. I wonder if paying the $1500+ per month for "Adobe Commerce" has less bugs. Highly doubt it. The sad part? It's released only two weeks prior to GA (general availability) for "testing" even to those paying customers. Like really?
> 
> I swear, whoever came up with the release schedule for this system should be fired. It's just simply not the way to do it. Smaller, quicker releases are MUCH smarter and better to do. For instance, WooCommerce (which has like 100x more store running it, like 10m compared to 500k for Magento) does releases like once per month. Those releases are MUCH smaller. Easier to deal with bugs and testing - they will also release fixes quickly after instead of making the merchant wait 4-5 months. It's also available for testing WHILE it's being developed. Adobe, for reasons unknown (probably greed somehow) keeps the testing of the dev version behind closed doors (like all those "jira" bug reports require you to be an "Adobe staff member" - like really?? thought this was open-source) so the only **REAL** testing is done in the two weeks prior to GA. Like how dumb. Then problems like this arises. Problems that should not even have happened if it were tested better. But now stores that rely on a stable eCommerce system so they can make MONEY deal with major site breaking bugs. That is explicitly why most Magento stores pay like $5k for "upgrade" teams - because of the garbage QC (quality control) that Adobe does.
> 
> It's sad because overall I think the features and usual stability of Magento is above most others, but during release time it's always a disaster. Always. So...the trick I think I'm learning? ALWAYS wait for the "p" release. Then move to that one, which should HOPEFULLY have the major release's bugs fixed. Because again, with their garbage release schedule they don't release minor point releases to fix problems like this. This major issue, and others, will only be [hopefully] fixed now 4-5 months from now with the "p" release - though knowing them, they will say "this fix is targeted for 2.4.7" or "2.4.8", at the end of 2023 or this time next year - which is just insane. Instead of doing what many other sane companies do and just come out with a minor point release (2.4.6.1) fixing major issues like this.
> 
> Gah rant over. Good luck to anyone that updated. I will be waiting, and will always do with this system. Never have I before seen such garbage QC every release. Every...single...time. Really wish WooCommerce was more like this system (features, stability, etc.) because I would just stick with that, I trust their new releases so much more. The garbage Adobe pulls every time with these releases sours my outlook on Magento so much 😡

I have to say I completely agreed with you. Upgrading on minor releases were ok, but big major release with major changes always a hassle. Waiting for the patch version is one of the safest, most easy solution to go with unless there are some imminent issues to be fixed.

**Comment by engcom-Dash** [comment] 2023-04-17 01:33
Hi @laurnts ,

Verified the issue in 2.4.6 in magento instance and issue is not reproducible after installing magento package ES8 and Kindly refer the below screenshots.We can able run the search engine of ES 8 with following command.

"php bin/magento setup:install --search-engine=elasticsearch 8"

Screenshots:
<img width="1512" alt="es1" src="https://user-images.githubusercontent.com/60198592/231090570-c607ac7a-728a-4d11-bec4-87ec72163fe0.png">

We can successfully the run above mentioned the command without any issue .
Kindly try again with some manual steps of elasticsearch.You may get some information.Here is the [link](https://github.com/magento/magento2/issues/37236#issuecomment-1487650849)  for composer package of elasticsearch 8

Thanks,

**Comment by scholtz** [comment] 2023-04-22 09:56
I am using this preparation docker build:

```
FROM ubuntu
USER root
ENV DEBIAN_FRONTEND noninteractive
RUN apt update && apt dist-upgrade -y && apt install -y mc wget telnet git curl net-tools iotop atop vim dnsutils jq && apt-get autoremove --yes && rm -rf /var/lib/{apt,dpkg,cache,log}/
RUN apt update && apt dist-upgrade -y && apt install -y software-properties-common && apt-get autoremove --yes && rm -rf /var/lib/{apt,dpkg,cache,log}/

RUN DEBIAN_FRONTEND=noninteractive && add-apt-repository ppa:ondrej/php

RUN apt update && apt dist-upgrade -y && apt install -y nginx php8.2-fpm php8.2-cli && apt-get autoremove --yes && rm -rf /var/lib/{apt,dpkg,cache,log}/
#RUN apt-cache search php8.2
RUN apt update && apt dist-upgrade -y && apt install -y php8.2-curl php8.2-zip php8.2-pdo php8.2-mysqlnd php8.2-opcache php8.2-xml php8.2-gd php8.2-mysql php8.2-intl php8.2-mbstring php8.2-bcmath php8.2-iconv php8.2-soap && apt-get autoremove --yes && rm -rf /var/lib/{apt,dpkg,cache,log}/

RUN echo 2
RUN sed -i 's~memory_limit = .*~memory_limit = 2G~g' /etc/php/8.2/fpm/php.ini \
&& sed -i 's~max_execution_time = 30~max_execution_time = 1800~g' /etc/php/8.2/fpm/php.ini \
&& sed -i 's~zlib.output_compression = Off~zlib.output_compression = On~g' /etc/php/8.2/fpm/php.ini 

RUN sed -i 's~memory_limit = .*~memory_limit = 2G~g' /etc/php/8.2/cli/php.ini \
&& sed -i 's~max_execution_time = 30~max_execution_time = 1800~g' /etc/php/8.2/cli/php.ini \
&& sed -i 's~zlib.output_compression = Off~zlib.output_compression = On~g' /etc/php/8.2/cli/php.ini 

RUN grep memory_limit /etc/php/8.2/cli/php.ini  \
&& grep max_execution_time /etc/php/8.2/cli/php.ini \
&& grep output_compression /etc/php/8.2/cli/php.ini

#RUN nginx -v

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

RUN cat /etc/php/8.2/fpm/pool.d/www.conf
RUN mkdir /app
RUN sed -i 's~www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin~www-data:x:33:33:www-data:/app:/bin/bash~g' /etc/passwd 
RUN chown www-data:www-data /app -R

USER www-data
WORKDIR /app
ARG REPO_USER
ARG REPO_PASS
RUN echo "REPO_USER:$REPO_USER"
RUN composer config --global http-basic.repo.magento.com $REPO_USER $REPO_PASS
RUN composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition /app/magento
WORKDIR /app/magento
RUN composer require magento/module-elasticsearch-8 --update-with-all-dependencies

USER root

RUN apt update && apt dist-upgrade -y && apt install -y supervisor tzdata && apt-get autoremove --yes && rm -rf /var/lib/{apt,dpkg,cache,log}/

COPY supervisord.conf /etc/supervisord.conf

USER root
#RUN cat /etc/nginx/sites-available/default
COPY web.conf /etc/nginx/sites-available/default
COPY magento.template.conf /etc/nginx/snippets/magento.template.conf

RUN rm /app/.config/composer/auth.json 

RUN sed -i 's~expose_php = .*~expose_php = Off~g' /etc/php/8.2/fpm/php.ini \
&& sed -i 's~display_errors = .*~display_errors = On~g' /etc/php/8.2/fpm/php.ini \
&& sed -i 's~post_max_size =.*~post_max_size = 32M~g' /etc/php/8.2/fpm/php.ini \
&& sed -i 's~;opcache.enable=.*~opcache.enable=1~g' /etc/php/8.2/fpm/php.ini \
&& sed -i 's~;opcache.save_comments=.*~opcache.save_comments=1~g' /etc/php/8.2/fpm/php.ini \
&& sed -i 's~listen =.*~listen = 127.0.0.1:9000~g' /etc/php/8.2/fpm/pool.d/www.conf

RUN sed -i 's~;access.log~access.log~g' /etc/php/8.2/fpm/php.ini \
&& sed -i 's~;error_log~error_log~g' /etc/php/8.2/fpm/php.ini
RUN grep error_log /etc/php/8.2/fpm/php.ini

ENV TZ="Europe/London"

RUN grep opcache /etc/php/8.2/fpm/php.ini 

RUN grep listen /etc/php/8.2/fpm/pool.d/www.conf
RUN mkdir /run/php-fpm/
COPY start.sh /app/start.sh
EXPOSE 80
CMD ["/app/start.sh"]
```

this elastic search setup:

```
# kubectl create -f https://download.elastic.co/downloads/eck/2.7.0/crds.yaml
# kubectl apply -f https://download.elastic.co/downloads/eck/2.7.0/operator.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: magento
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-magento
  namespace: magento
spec:
  version: 8.7.0
  nodeSets:
  - name: default
    count: 2
    config:
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: nfs-fast-retain
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-magento
  namespace: magento
spec:
  version: 8.7.0
  count: 2
  elasticsearchRef:
    name: elastic-magento
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress-test01
  namespace: magento
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - kibana-magento.h2.mydomain.com
    secretName: tls-kibana-magento.h2.mydomain.com
  rules:
  - host: kibana-magento.h2.mydomain.com
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: kibana-magento-kb-http
            port:
              number: 5601
              
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elastic-es-ingress-test01
  namespace: magento
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - elastic-magento.k8s.h2.mydomain.com
    secretName: tls-elastic-magento.k8s.h2.mydomain.com
  rules:
  - host: elastic-magento.k8s.h2.mydomain.com
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: elastic-magento-es-http
            port:
              number: 9200
```

this sample installation

```
FROM scholtz2/magento:mag-2.4.6-nginx-1-8-php-8-2-stable

USER www-data
WORKDIR /app/magento
RUN ls -lA bin
RUN bin/magento setup:install \
--base-url=http://localhost/ \
--db-host=mysql.mydomain.com \
--db-name=magento2 \
--db-user=magento2 \
--db-password=myMysqlPass \
--admin-firstname=admin \
--admin-lastname=admin \
--admin-email=admin@admin.com \
--admin-user=admin \
--admin-password=myMagentoAdminPass \
--language=en_US \
--currency=USD \
--timezone=Europe/London \
--use-rewrites=1 \
--search-engine=elasticsearch8 \
--elasticsearch-host=https://elastic-magento.k8s.mydomain.com \
--elasticsearch-enable-auth=1 \
--elasticsearch-username=magento2 \
--elasticsearch-password=myElasticSearchUserPass
```

and i get error 
![image](https://user-images.githubusercontent.com/1223439/233777048-0df7c80c-5a58-4a6e-85ac-fa0b7c950c78.png)


I am sure that connection to elasticsearch8 works properly as i can access it through the browser and i can see everything in kibana.

**Comment by engcom-Dash** [comment] 2023-05-02 15:12
Hi @laurnts ,


We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2023-05-02 15:12 UTC
Labels: Issue: needs update, Reported on 2.4.6

**Comment by Chris25602** [comment] 2023-05-23 00:09
I have an issue with the stated resolution. I was unable to find the es8 magento package following the links provided by @engcom-Dash.

<img width="880" alt="m2_es8_composer" src="https://github.com/magento/magento2/assets/8037053/1715f3f4-b7cb-43ad-8c10-d64d0508931f">

**Comment by aashishgurung** [comment] 2023-06-19 12:23
I am having same issue as @Chris25602. `composer require magento/module-elasticsearch-8 --with-all-dependencies` outputs package could not be found.

**Comment by hostep** [comment] 2023-06-19 21:07
@aashishgurung: the correct command is `composer require magento/module-elasticsearch-8 --update-with-all-dependencies` (like is being mentioned in [the documentation](https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/prepare/prerequisites.html?lang=en#upgrade-elasticsearch))

And over here that command works both in Magento 2.4.6 and 2.4.6-p1...

**Comment by aashishgurung** [comment] 2023-06-20 01:21
@hostep Thanks for correcting the option. But the issue here is that the package itself is not found. I tried again, got the same result.

```composer require magento/module-elasticsearch-8 --update-with-all-dependencies```

```
Could not find a matching version of package magento/module-elasticsearch-8.
Check the package spelling, your version constraint and that the package is
available in a stability which matches your minimum-stability (stable).
```

**Comment by hostep** [comment] 2023-06-20 19:15
@aashishgurung: The only thing I can come up with is that you guys are not using repo.magento.com for your composer packages repository and that this repository hasn't got this package yet. Is that the problem maybe? Have you defined an alternative repository in your `composer.json` file?

You can probably figure this out by enabling more verbose output:
```
composer require -vvv magento/module-elasticsearch-8 --update-with-all-dependencies
```

**Comment by medigeek** [comment] 2023-07-01 19:54
I think we need a detailed explanation/documentation on how to configure magento 2 with elasticsearch 8 and opensearch with security enabled.

Otherwise I had to switch to opensearch and use `plugins.security.disabled: true` in `/etc/opensearch/opensearch.yml`

also, suffered from https://magento.stackexchange.com/a/323415 and this error: `Fatal error: Uncaught Error: Cannot instantiate interface Magento\AdvancedSearch\Model\Client\ClientOptionsInterface`

and obviously required to enable `Magento_Elasticsearch` module even though I'm using Magento_Opensearch

Here's a quick how-to with security disabled and opensearch 2.5.x on ubuntu and magento 2.4.6

```

As of version 2.3.7-p3, Adobe Commerce and Magento Open Source support OpenSearch. On-premises installations continue to support Elasticsearch, although it is no longer supported for Adobe Commerce on cloud infrastructure.


test opensearch

https://stackoverflow.com/questions/76252296/can-i-install-opensearch-without-using-docker-on-ubuntu/76364021#76364021
https://opensearch.org/docs/latest/install-and-configure/install-opensearch/debian/

using on dev version 2.5.x instead of supported magento 2 2.2.x: https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html



sudo apt-get install opensearch=2.5.0

systemctl stop elasticsearch
systemctl disable elasticsearch


nano /etc/opensearch/opensearch.yml
add:
network.host: localhost
node.name: node-1
plugins.security.disabled: true

systemctl start opensearch
systemctl enable opensearch

curl -X GET http://localhost:9200/

bin/magento config:set catalog/search/engine 'opensearch'

bin/magento module:disable Magento_InventoryElasticsearch Magento_Elasticsearch8 Magento_Elasticsearch Magento_OpenSearch
bin/magento module:enable Magento_OpenSearch Magento_Elasticsearch

bin/magento setup:install --search-engine=opensearch --opensearch-host=localhost --opensearch-port=9200 --opensearch-enable-auth=0 --opensearch-index-prefix=magento2 --opensearch-timeout=15

php -d memory_limit=-1 composer.phar install
php -d memory_limit=2G bin/magento setup:upgrade
php -d memory_limit=2G bin/magento setup:di:compile

php -d memory_limit=2G bin/magento s:s:d -f -j 4

php -d memory_limit=2G bin/magento cache:clean

php -d memory_limit=2G bin/magento indexer:reindex

php -d memory_limit=2G bin/magento cache:clean
````

**Comment by medigeek** [comment] 2023-07-01 20:54
something tells me we're missing the part where we add the self signed ssl certificate to be trusted as verified in php or in the server OS.

something like https://stackoverflow.com/questions/21187946/curl-error-60-ssl-certificate-issue-self-signed-certificate-in-certificate-cha

some setting in php.ini ? like https://serverfault.com/questions/633644/adding-a-self-signed-cert-to-the-trusted-certs-within-curl-in-windows

I wonder if hacking this configuration to disable ssl verification in file `vendor/magento/framework/HTTP/Adapter/Curl.php` will make any difference?

```
        'verifypeer' => true,
        'verifyhost' => 2
```

**Comment by cfortin** [comment] 2023-07-14 10:11
> > i wasted all weekend to find out this, running different setups like crazy. adobe fiddled around for `217` days and came up with a broken release, a non-working core component without which the whole patform can't be installed... now it's my time to whine...
> 
> Such oversight makes me want to rant now...
> 
> I find this happens with almost every single release they come out with. I've upgraded from 2.4.0 to each release to now 2.4.5 (I will not be updating to .6 until .6-p1) and every single "major" release (.1, .2, .3, .4, .5) has had some profoundly surprising bugs that makes you wonder who tests these releases. Almost like they test with one setup and say "good to go". It's absolutely absurd and can destroy businesses. I wonder if paying the $1500+ per month for "Adobe Commerce" has less bugs. Highly doubt it. The sad part? It's released only two weeks prior to GA (general availability) for "testing" even to those paying customers. Like really?
> 
> I swear, whoever came up with the release schedule for this system should be fired. It's just simply not the way to do it. Smaller, quicker releases are MUCH smarter and better to do. For instance, WooCommerce (which has like 100x more store running it, like 10m compared to 500k for Magento) does releases like once per month. Those releases are MUCH smaller. Easier to deal with bugs and testing - they will also release fixes quickly after instead of making the merchant wait 4-5 months. It's also available for testing WHILE it's being developed. Adobe, for reasons unknown (probably greed somehow) keeps the testing of the dev version behind closed doors (like all those "jira" bug reports require you to be an "Adobe staff member" - like really?? thought this was open-source) so the only **REAL** testing is done in the two weeks prior to GA. Like how dumb. Then problems like this arises. Problems that should not even have happened if it were tested better. But now stores that rely on a stable eCommerce system so they can make MONEY deal with major site breaking bugs. That is explicitly why most Magento stores pay like $5k for "upgrade" teams - because of the garbage QC (quality control) that Adobe does.
> 
> It's sad because overall I think the features and usual stability of Magento is above most others, but during release time it's always a disaster. Always. So...the trick I think I'm learning? ALWAYS wait for the "p" release. Then move to that one, which should HOPEFULLY have the major release's bugs fixed. Because again, with their garbage release schedule they don't release minor point releases to fix problems like this. This major issue, and others, will only be [hopefully] fixed now 4-5 months from now with the "p" release - though knowing them, they will say "this fix is targeted for 2.4.7" or "2.4.8", at the end of 2023 or this time next year - which is just insane. Instead of doing what many other sane companies do and just come out with a minor point release (2.4.6.1) fixing major issues like this.
> 
> Gah rant over. Good luck to anyone that updated. I will be waiting, and will always do with this system. Never have I before seen such garbage QC every release. Every...single...time. Really wish WooCommerce was more like this system (features, stability, etc.) because I would just stick with that, I trust their new releases so much more. The garbage Adobe pulls every time with these releases sours my outlook on Magento so much rage

I wholeheartedly agree. As someone coming from the Drupal ecosystem, Magento makes Drupal look like the Rolls-Royce of open source software. This is not the way to do open source properly.

**Comment by preetkakkar** [comment] 2023-07-20 08:49
@medigeek I have tried with your instructions how-to with security disabled and opensearch magento 2.4.6

php -d memory_limit=-1 composer.phar install ( shows the following error_
Could not open input file: composer.phar

and
php -d memory_limit=2G bin/magento setup:upgrade 
Could not validate a connection to the OpenSearch. No alive nodes found in your cluster

Does anyone got any solution for this.

**Comment by hielh** [comment] 2023-10-30 16:01
@preetkakkar any solution for your problem please

**Comment by guvra** [comment] 2023-11-16 10:26
This issue still exists in 2.4.7-beta2...
It is not possible to use the `opensearch` engine during installation.

Our current fix is to install magento with the elasticsearch7 engine, then switch to opensearch engne after the installation.

**Comment by deborahsbg** [comment] 2023-11-30 01:03
I have installed 2.4.6 with Elasticsearch 8.5 using security enabled, but ssl is not possible so no kibana... 
Do you recommend going for opensearch?
