### ISSUE TITLE
Multishipping does not update cart item subtotal correctly

### ISSUE THREAD

**Issue by sanjay-wagento** [magento/magento2#30408] opened 2020-10-10 08:43 UTC
### Preconditions (*)
1. Magento 2.4.0
1. Multishipping Enable

### Steps to reproduce (*)
1. Add product in the cart
1. Click on Check Out with Multiple Addresses Link
1. Back to the cart page
1. Update product qty and click on Update Shopping Cart

### Expected result (*)
1. Item subtotal should display the correct amount based on qty
![Shopping_Cart](https://user-images.githubusercontent.com/8655914/95650527-d61c8c00-0b01-11eb-9577-7783f62fa525.png)

### Actual result (*)
1. Item subtotal does not display the correct amount
![Shopping_Cart(1)](https://user-images.githubusercontent.com/8655914/95650568-0bc17500-0b02-11eb-98e7-a2307a10ba8c.png)

## 
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- < ] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
- [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
- [X] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
- [ > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

**Comment by sanjay-wagento** [comment] 2020-10-10 08:43
@magento I am working on it

**Comment by sanjay-wagento** [comment] 2020-10-10 08:44
#dmcdindia2020

**Comment by sanjay-wagento** [comment] 2020-10-10 09:02
@krishprakash I am already started working on this. So please work on another issue.

**Comment by krishprakash** [comment] 2020-10-10 09:04
@sanjay-wagento Don't worry. I'm just verifying the issue

**Comment by krishprakash** [comment] 2020-10-10 09:46
Verified the issue in local 2.4-develop instance 

![image](https://user-images.githubusercontent.com/46617848/95651933-25b38580-0b0b-11eb-82ad-16ccf02aa138.png)

**Comment by magento-engcom-team** [comment] 2020-10-10 09:46
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38334` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment] 2020-10-10 10:42
Hi @sanjay-wagento I'm not able to reproduce the issue, maybe I'm missing something, can you provide more details or maybe a video with the steps?

**Comment by sanjay-wagento** [comment] 2020-10-10 11:00
@gabrieldagama Please check here
[screencast-nimbus-capture-2020.10.10-16_26_57.zip](https://github.com/magento/magento2/files/5358853/screencast-nimbus-capture-2020.10.10-16_26_57.zip)

**Comment by gabrieldagama** [comment] 2020-11-13 13:28
Hi @sanjay-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#30411 by @sanjay-wagento in 2.4-develop branch
Related commit(s):
 - [043bf815aed0d042c15400227039d89e3ad3ca08](https://github.com/magento/magento2/commit/043bf815aed0d042c15400227039d89e3ad3ca08)
 - [1e11f7f15d61718c74ff4233468af727918e6f03](https://github.com/magento/magento2/commit/1e11f7f15d61718c74ff4233468af727918e6f03)
 - [54f813264252fae05c586c3f6dcaad778aa42804](https://github.com/magento/magento2/commit/54f813264252fae05c586c3f6dcaad778aa42804)
 - [f1a622620c506a49e2d27210b725508bf66c8bdb](https://github.com/magento/magento2/commit/f1a622620c506a49e2d27210b725508bf66c8bdb)
 - [03d0e13d99550024773ef6bec2226efb2aa6bb90](https://github.com/magento/magento2/commit/03d0e13d99550024773ef6bec2226efb2aa6bb90)
 - [51d8e6c158fac629c2a778c601138db997584f1f](https://github.com/magento/magento2/commit/51d8e6c158fac629c2a778c601138db997584f1f)
 - [3869db87d4705aba35c0ddf1525f0c128bb18157](https://github.com/magento/magento2/commit/3869db87d4705aba35c0ddf1525f0c128bb18157)
 - [56c48145449562295e454687c2cda13716307dfe](https://github.com/magento/magento2/commit/56c48145449562295e454687c2cda13716307dfe)

The fix will be available with the upcoming 2.4.2 release.

**Closed as completed by gabrieldagama** 2020-11-13 13:28 UTC
Labels: Issue: Ready for Work, Component: Checkout, Issue: Clear Description, Issue: Confirmed, Component: Multishipping, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P2, Severity: S2, Progress: done, Event: dmcdindia2020, Reported on 2.4.0
