### ISSUE TITLE
[GraphQl] Categories from root categories of other websites are returned.

### ISSUE THREAD

**Issue by Hexmage** [magento/magento2#34570] opened 2021-11-08 10:57 UTC
### Preconditions (*)

1. Magento 2.4.2-p1
2. Two Websites with different root categories

### Steps to reproduce (*)

1. Create a product
2. Assign the product to both websites
2. Add the product to a subcategory of both root categories.
3. Request the product through GraphQl using the Store header of the first website.
```
query productDetail {
    productDetail: products(filter: {url_key: {eq: "24-MB01"}}) {
        items {
            sku
            __typename
            categories {
                name
                path
                url_key
            }
        }
    }
}
```

### Expected result (*)

Only returns categories that are in the website's root category (in this example 2).
```
{
    "data": {
        "productDetail": {
            "items": [
                {
                    "sku": "24-MB01",
                    "__typename": "SimpleProduct",
                    "categories": [
                        {
                            "name": "Gear",
                            "path": "1/2/3",
                            "url_key": "gear"
                        },
                        {
                            "name": "Bags",
                            "path": "1/2/3/4",
                            "url_key": "bags"
                        }
                    ]
                }
            ]
        }
    }
}
```

### Actual result (*)

Returns categories in every root category (in this case 2 and 41).
```
{
    "data": {
        "productDetail": {
            "items": [
                {
                    "sku": "24-MB01",
                    "__typename": "SimpleProduct",
                    "categories": [
                        {
                            "name": "Gear",
                            "path": "1/2/3",
                            "url_key": "gear"
                        },
                        {
                            "name": "Bags",
                            "path": "1/2/3/4",
                            "url_key": "bags"
                        },
                        {
                            "name": "Not Default Category",
                            "path": "1/41",
                            "url_key": "not-default-category"
                        }
                    ]
                }
            ]
        }
    }
}
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2021-11-08 14:17
Verified the issue on Magento 2.4-develop branch but the issue is not reproducible:
Only categories that are in the website's root category are returned - No issue:
![image](https://user-images.githubusercontent.com/60198231/140757531-2d9a6031-b2fc-43bb-80a0-653868f84df7.png)

![image](https://user-images.githubusercontent.com/60198231/140757486-5b4a897a-3449-4d36-9b2f-b1c0bdb79b1b.png)
@Hexmage kindly verify the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by Hexmage** [comment] 2021-11-08 14:19
@engcom-November 
Your test is exactly what is wrong.
It shouldn't show both default and france. It should only show either default or france based on which website your storeview is in.

**Comment by engcom-November** [comment] 2021-11-25 12:10
Thank you for the confirmation @Hexmage. Verified the issue again on Magento 2.4-develop branch and the issue is reproducible.
All categories are returned on running the GraphQL query regardless to the store view assigned.

**Comment by Usik2203** [comment] 2021-12-10 13:28
@magento I am working on this

**Comment by Usik2203** [comment] 2021-12-15 15:17
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-05-31 08:20
Hello @Hexmage,

As I can see this issue got fixed in the scope of the internal Jira ticket `AC-1883` by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-1883&type=commits

Based on Jira, the target version is 2.4.5.

Thanks

**Closed as completed by engcom-Hotel** 2022-05-31 08:20 UTC
Labels: Issue: Confirmed, Component: GraphQL, Reproduced on 2.4.x, Priority: P1, Progress: done, Reported on 2.4.2-p1, Area: Product
