### ISSUE TITLE
Magento2 rest api add customer token in create customer api

### ISSUE THREAD

**Issue by NileshThote** [magento/magento2#19189] opened 2018-11-13 14:23 UTC
i am using 
magento 2.1.1
php version 7.0

this is my payload and response.

![screenshot 106](https://user-images.githubusercontent.com/42933455/48419184-5226c180-e77d-11e8-8d21-45279364d78c.png)

### Summary (*)

i want to add customer token in the response and i am using following magento 2 api :

http://host/index.php/rest/default/V1/customers

### Example (*)

in the response i want to add **seesion id** in following response :

{
    "id": 2278,
    "group_id": 1,
    "created_at": "2018-11-13 14:06:24",
    "updated_at": "2018-11-13 14:06:24",
    "created_in": "Default Store View",
    "email": "test1023@gmail.com",
    "firstname": "test",
    "lastname": "lastName",
    "store_id": 1,
    "website_id": 1,
    "addresses": [],
    "disable_auto_group_change": 0
    **"session_id": "b5la2wrgxx00oqu83yuvqdthnqjv1tmv"**
}
hope you guys understand my problem

**Comment by orlangur** [comment] 2018-11-13 17:25
@NileshThote, GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.

**Comment by magento-engcom-team** [comment] 2018-11-13 17:25
Hi @orlangur. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Closed as completed by orlangur** 2018-11-13 17:25 UTC
Labels: non-issue, Issue: Format is not valid
