### ISSUE TITLE
Thumbnail images not being generated for some products in non-default website/web store view

### ISSUE THREAD

**Issue by DH0** [magento/magento2#9629] opened 2017-05-14 00:37 UTC
I have two websites in my Magento installation, one that includes a full set of products and the other that is a subset for a specific brand. 

After upgrading to 2.1.6, I cleared the product image cache in /pub/media/catalog/product/cache. I then ran catalog:images:resize to regenerate it. 

All of the thumbnails for my default store were generated. In addition, some of the thumbnails for my subset website were generated. However, a number are missing. I have checked the path and the file simply does not exist where it should. 

For the same product - the thumbnail in the default site is created. However, this is at a different cache location from the one expected by the subset website. (Even though the themes do not specify a different thumbnail size, and the frontend/etc/view.xml files are in fact identical, I think the system is supposed to generate two separate thumbnails ). 

This issue seems closely related to a number of other issues that have been reported for 2.1.6, but it is different in that re-running  catalog:images:resize does not fix the problem; the missing thumbnails are still not generated. 

Further, if a new product is created using a new product image via the control panel, the thumbnail for the subset site is not generated, yet exists in the default site. 

The only thumbnails that are actually generated for the subset site are the ones for products that are used in a "catalogue products widgit" on the home page of the subset site. All products not shown in this are also missing thumbnails. 

Magento version 2.1.6 last upgraded from 2.1.2
Php 7.0.8 
Ubuntu 16.04
Mysql 14.14

### Expected result
All thumbnails should be generated for products that are available to order when catalog:images:resize is run, for all websites and store views. 

### Actual result
Product thumbnails missing for secondary magento website/store view.

**Comment by mzeis** [comment] 2017-05-31 21:26
Hi!

Magento just released 2.1.7 with a "reversion of the changes to image resizing that we introduced in 2.1.6": http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.7CE.html

Can you please check if the problem is gone in 2.1.7? Thanks!

**Comment by veloraven** [comment] 2017-06-12 13:01
@DH0 this issue should be fixed in Magento 2.1.7.
If you still experience it please format this issue according to [template](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce.

**Comment by veloraven** [comment] 2017-07-03 06:37
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Closed as completed by veloraven** 2017-07-03 06:37 UTC
Labels: Progress: needs update
