### ISSUE TITLE
After Installation in admin pannel none of the link works

### ISSUE THREAD

**Issue by ausmani** [magento/magento2#3868] opened 2016-03-22 15:00 UTC
After the installation magento on local machine none of the link works

i install magento 3-4 times

http://prntscr.com/aiimiu

**Comment by mrkhoa99** [comment] 2016-03-22 15:16
Hello @ausmani,
Please, refer to this ticket: https://github.com/magento/magento2/issues/815#issuecomment-199285060

**Comment by mazhalai** [comment] 2016-03-22 16:47
Closing as this is not a bug.

**Closed as completed by mazhalai** 2016-03-22 16:47 UTC
