### ISSUE TITLE
Magento 2 Braintree Payment Gateway Issue - Error Message Not Displayed on Failed Transactions

### ISSUE THREAD

**Issue by sumeetmagento** [magento/magento2#38193] opened 2023-11-16 08:18 UTC
### Preconditions and environment

- Magento version  is 2.4.5-p1
- We're running Magento version 2.4.5-p1 and utilizing the Braintree payment gateway for both credit card and Paypal transactions.

Our concern is that when a customer attempts to place an order and the transaction fails due to insufficient funds, there is no error message being displayed at checkout.

According to our expectations, an error message should appear in such cases. Has anyone encountered this issue before or can offer insights into potential solutions?

### Steps to reproduce

1 - Add any product in cart
2 - Proceed to checkout
3 - Pay via credit card braintree payment

### Expected result

Error message should show if there is a error message coming from braintree like insufficient funds on checkout page

### Actual result

Right now there is no error message is showing on checkout

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sims-smith-corona** [comment] 2023-11-16 15:18
In case it's helpful to you, we observed that the Braintree module would render all transactions error messages in its hosted fields section, even if the transaction error is coming from a vaulted credit card attempt. This was problematic for us because when using a vaulted payment method, the Braintree hosted fields section isn't visible (so neither were the error messages.)

We implemented a workaround where was observe any error messages added to that message container and clone them in a message container that's visible when using vaulted payment methods.

**Comment by gene-roussetos** [comment] 2023-11-16 20:18
@sims-smith-corona by vaulted payment methods, do you mean payment methods vaulted in Magento (and thereby Braintree as well)? or payment methods vaulted only in Braintree?

To load Braintree only payment methods vaulted, you would require Braintree's customer ID when generating a token which is something the current version of the Magento Braintree module does not support for cards.
In this case, your issue is not related to the Braintree magento module.

The module supports vaulting payment methods in Magento (with the token) which do not load the Hosted fields at all during checkout.

Apologies, I was just confused. Maybe a video recording of the issue could be useful?

**Comment by sims-smith-corona** [comment] 2023-11-16 20:42
@gene-roussetos Sorry for any confusion, but I'm not trying to report any issue or problem. I was just commenting to the original poster. 

Our checkout is extremely customized which leads to a lot of nonstandard behavior, so that may be to blame, in our case, transaction errors resulting from failed authorizations using a vaulted Braintree credit card method would result in error messages being added to the hosted fields method renderer component's message container rather than vaulted method renderer's.

**Comment by gene-roussetos** [comment] 2023-11-16 21:52
@sims-smith-corona fair, it is true that if the checkout is customised or using 3rd party modules, some errors might not be picked up straight away as this needs to be accommodated if not hitting the place order (set payment information and place order) API endpoint.

For all I know, in general, during the API place order action, PHP code is triggered to execute the Transaction process and a braintree error should be returned within a Localized exception to the frontend and a 400 error.
Then the checkout message manager displays that error. Not all errors are visible as is, as some might be hidden on purpose and a generic message is displayed. Or in other cases of course, it's been missed and the message is generic while it shouldn't.

**Comment by sumeetmagento** [comment] 2023-11-23 13:22
Is there any update ?

**Comment by sumeetmagento** [comment] 2023-12-15 06:06
any update please ?

**Comment by engcom-Dash** [comment] 2024-01-17 14:30
Hi @sumeetmagento 

Thanks for reporting and collaboration.

Verified the issue on Magento 2.4 dev instance but the issue is not reproducible.

When there are insufficient funds in paypal account we are seeing error message. 

Please refer the attached screenrecord


https://github.com/magento/magento2/assets/60198592/d04b5f85-9e89-4853-bf1c-1a781d9d5e2f

**Comment by engcom-Dash** [comment] 2024-01-29 06:58
Hi @sumeetmagento 

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2024-01-29 06:58 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1

**Comment by ou86** [comment] 2024-08-30 16:28
@sims-smith-corona This is the exact problem our site is facing. When placing an order with a vault/stored card that leads to some error, that error will be displayed within the Credit Card payment method which is inactive and hidden. So the customer has no idea why the payment isn't going through. Can you share your fix or what files I need to look at?

**Comment by sims-smith-corona** [comment] 2024-08-30 17:14
> @sims-smith-corona This is the exact problem our site is facing. When placing an order with a vault/stored card that leads to some error, that error will be displayed within the Credit Card payment method which is inactive and hidden. So the customer has no idea why the payment isn't going through. Can you share your fix or what files I need to look at?

It's convoluted but effective.

We override the js/view/payment/method-renderer/vault.js with our own. During the component's initialization, we use setInterval() to fire a function that watches the Braintree Hosted Fields messages container HTML element to identify any new message elements that get injected and insert them into the vaulted payment method's component's messageContainer so they get rendered in the appropriate place on the page.

Here's the function that gets triggered by setInterval:

`copyHostedFieldsErrorMessages: function() {

            var self = this;

            var sourceMessageContainerElement = $('#braintree-hosted-fields .messages');

            if(sourceMessageContainerElement.length == 1) {

                var errorMessageElements = $(sourceMessageContainerElement).find('.message-error > div:not(.copied)');

                $(errorMessageElements).each(function(messageIndex, messageElement) {

                    $(messageElement).addClass('copied');

                    self.messageContainer.addErrorMessage({message: $(messageElement).html(), parameters: []});

                });

            }

        },`

**Comment by ou86** [comment] 2024-09-03 15:59
@sims-smith-corona 

First of all, thank you for your quick reply on this old thread. I faced some issues trying to implement this on Friday, but I tried again today and its working partially. It works on the first stored payment method/card. In my case, I have several stored cards and it doesn't show the error on any of the other cards, only the first one.
