### ISSUE TITLE
404 error when attempting to change any product attribute settings in admin panel

### ISSUE THREAD

**Issue by diamondavocado** [magento/magento2#22393] opened 2019-04-17 17:10 UTC
### Preconditions (*)

1. Magento 2.3.0, data imported from Magento 1.9 using the migration tool
2. Centos 7, Apache, php-fpm

### Steps to reproduce (*)
1. Visit Admin panel -> Stores -> Attribute -> Products
2. Choose an attribute (in my case "Size")
3. Note the URL is `https://example.com/admin/catalog/product_attribute/edit/attribute_id/200/` at this stage
4. Try to change any setting (e.g. Catalog Input Type -> Dropdown)
5. Hit "Save" or "Save and Continue" to save your changes

### Expected result (*)

1. Attribute should be saved with new settings
2. Page should reload to the same URL (`https://example.com/admin/catalog/product_attribute/edit/attribute_id/200/`)

### Actual result (*)

1. Page makes a POST request with all the settings data to `https://example.com/admin/catalog/product_attribute/validate/attribute_id/200/?isAjax=true` but it seems that request gets a blank/empty response?
2. Page then reloads to different URL `https://example.com/admin/catalog/` which results in a 404 error
3. Changes are not saved to the attribute

Please note I have tried clearing (and disabling) all caches, indexes, deployed static content, checked file/folder permissions, etc. and this is still happening.

At least some other parts of the admin panel DO save correctly.

**Comment by orlangur** [comment] 2019-04-17 17:41
This is similar to https://github.com/magento/magento2/issues/22224 and a bunch of other issues, should be pretty straightforward to fix.

**Comment by shikhamis11** [comment] 2019-04-17 18:03
hi @diamondavocado 
thank you for your report .. this issue is not reproduceable at magento 2.3-develop instance

**Comment by diamondavocado** [comment] 2019-04-17 21:33
I updated to 2.3.1 and the attribute options are now showing in the dropdown format on the front-end, however the back-end (admin panel) still reports the attribute as being a Text Swatch:

![large](https://user-images.githubusercontent.com/32345083/56322378-d502dc80-6160-11e9-8cf5-fbe2b492fe26.png)

![large](https://user-images.githubusercontent.com/32345083/56322384-d8966380-6160-11e9-94ed-893c5b7157c9.png)


Any ideas as to why this is happening, if you can't replicate it?

**Comment by shikhamis11** [comment] 2019-04-18 17:11
Hi @diamondavocado 
I checked at 2.3.1 instance . It is working fine. expect once I changed the `Catalog Input Type for Store Owner` to `dropdown` from `Text Swatch` or  vice versa from backend you need flush FPC .

**Comment by shikhamis11** [comment] 2019-04-19 16:35
hello @diamondavocado I am closing this issue since I am not able to reproduce this issue. message here if you think this issue exists on magento 2.3-develop instance

**Closed as completed by shikhamis11** 2019-04-19 16:35 UTC
Labels: Issue: Format is valid, good first issue
