### ISSUE TITLE
Magento 2.2 with PHP and Opache 7.1.12 unable to save product in admin page

### ISSUE THREAD

**Issue by Jilco** [magento/magento2#12551] opened 2017-12-05 14:21 UTC
After updating a module yesterday with composer update also some of the framework and/or modules of magento are updated. After that saving a product is not possible anymore, before the update there was no problem. So updating the framework components seem to be te cause of the problem.

### Preconditions
Magento 2.2.1
Php 7.1.12
Opcache 7.1.12
Redis

### Steps to reproduce
1. go to product page
2. adjust in stock
3. save

### Expected result
1. product is saved and stock is adjusted

### Actual result
Error: Warning: Narrowing occurred during type inference. Please file a bug report on bugs.php.net in /home/jilco01/public_html/vendor/composer/ClassLoader.php on line 444 and product is not saved.

**Comment by orlangur** [comment] 2017-12-05 15:44
> After updating a module yesterday with composer update

Which module? Please provide exact commands used and `composer.json` + `composer.lock` files.

**Comment by Jilco** [comment] 2017-12-05 16:08
mollie ideal, when i did the update also some Magento core/framework files were updated. I don't know anymore wich ones.

{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.1.6",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "require": {
        "magento/product-community-edition": "2.2.1",
        "composer/composer": "@alpha",
        "mollie/magento2": "1.1.3",
        "magento/data-migration-tool": "2.2.0",
        "honl/magento2-nl-nl": "^1.1",
        "myparcelnl/magento": "2.3.0-beta.5",
        "myparcelnl/sdk": "v1.3.0"
    },
    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "@stable",
        "pdepend/pdepend": "2.2.2",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.3 <=0.7.0",
        "sebastian/phpcpd": "2.0.0"
    },
    "config": {
        "use-include-path": true
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": "app/code/"
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "alpha",
    "prefer-stable": true,
    "repositories": {
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        "data-migration-tool": {
            "type": "git",
            "url": "https://github.com/magento/data-migration-tool"
        }
    },
    "extra": {
        "magento-force": "override"
    }
}

**Comment by Jilco** [comment] 2017-12-05 17:45
[composerlock.txt](https://github.com/magento/magento2/files/1532264/composerlock.txt)
[composerjson.txt](https://github.com/magento/magento2/files/1532275/composerjson.txt)

Module i updated was the mollie module, but with the composer update automatic some magento core/framework files were updated

**Comment by orlangur** [comment] 2017-12-05 17:51
@Jilco could you please also locate a problematic class as suggested in top comment of https://bugs.php.net/bug.php?id=74980?

**Comment by Jilco** [comment] 2017-12-05 17:53
How do i find that class....

I'm not a specialist unfortunatly

**Comment by orlangur** [comment] 2017-12-05 17:55
Add `echo $class, PHP_EOL;` in `\Composer\Autoload\ClassLoader::loadClass` (it is usually placed in `vendor/composer/ClassLoader.php`).

**Comment by Jilco** [comment] 2017-12-05 18:05
I located the Classloader file, i attached it. i don't know what you mean exactly, do i need to paste the text somewere in a function of the classloader.php?
[ClassLoader.txt](https://github.com/magento/magento2/files/1532355/ClassLoader.txt)

**Comment by orlangur** [comment] 2017-12-05 18:14
Yes, you need to add this code and then reproduce the issue again.

**Comment by Jilco** [comment] 2017-12-05 18:16
at the end of the file?

**Comment by Jilco** [comment] 2017-12-05 20:00
I figured it out, but the outcome is huge. I cannot conclude from that what the class with the problem is. See attached.
[classloader_out.txt](https://github.com/magento/magento2/files/1532702/classloader_out.txt)

**Comment by orlangur** [comment] 2017-12-06 09:24
@Jilco I don't see in this file warning mentioned in issue description "Error: Warning: Narrowing occurred during type inference".

**Comment by Jilco** [comment] 2017-12-06 09:28
See screenshot
![error](https://user-images.githubusercontent.com/23727130/33654375-2bbdb05a-da70-11e7-8475-09d12b7aa597.jpg)

**Comment by orlangur** [comment] 2017-12-06 11:37
@Jilco ok, then looks like `Magento\Framework\App\Response\HeaderProvider\XFrameOptions` was the class which tried to be loaded and caused exception.

**Comment by Jilco** [comment] 2017-12-06 11:47
How can i check/confirm that? And of course what to do about it :-)

**Comment by Jilco** [comment] 2017-12-07 07:59
I found a work around, but not the sollution. It is something in Opcache, but the strange thing is that it was not a problem before the update. So there has to be something wrong in the core files. 
For the work around see:
https://stackoverflow.com/questions/47656426/magento-2-2-1-unable-to-save-product-error-narrowing-occurred-during-type-infe
Also i'm not the only one with the problem apparently

**Comment by orlangur** [comment] 2017-12-07 08:39
@Jilco thanks for your investigation.

@magento-engcom-team can you reproduce this issue on a clean Magento installation using PHP 7.1.12? Should we maybe disable this version in `composer.json` then like it was with PHP 7.0.5?

**Comment by magento-engcom-team** [comment] 2017-12-11 13:30
@Jilco, thank you for your report.
We've created internal ticket(s) MAGETWO-85308 to track progress on the issue.

**Comment by Jilco** [comment] 2017-12-11 13:57
@magento-engcom-team i switched on PhP-FPM and the problem was gone for some reason. So the problem is PhP (FPM) related i think

**Comment by lingwooc** [comment] 2017-12-12 10:21
Does this affect any other parts of magento?

**Comment by piszczek** [comment] 2017-12-13 06:29
In my case (php 7.1.12) error was caused by restarted php-fpm after update new release (I have to restart php-fpm, for folder symlink update).

Fully restart nginx solve that problem but it's workaround I guess.

**Comment by engcom-Alfa** [comment] 2020-01-06 13:11
Hi @Jilco. Thank you for your reporting.
We are not able to reproduce this issue on the fresh 2.4-develop instance. So we have to close it.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-01-06 13:11 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid
