### ISSUE TITLE
Issue with drag&drop setting bulk Images for configurable products

### ISSUE THREAD

**Issue by fvillata** [magento/magento2#4605] opened 2016-05-20 13:20 UTC
## Steps to reproduce

In the third step of the creation of configurable products “Bulk Images, Price, and Quantity
1. Select “Apply unique images by attribute to each SKU”
2. Select an attribute 
3. Drag an image on one of the values of the attribute
## Expected result
1. When I drag on the single attribute, I expect my image is set only for that value
## Actual result
1. The image is set for all the values

Only drag&drop cause the issue, browsing to find and upload the image works well.
So it's not a blocking issue but could be very confusing for end users.

Verified with Firefox 46.0.1, Chrome 50.0.2661.102, Safari 9.0 on Os X 10.10.5

<img width="567" alt="issue_dd" src="https://cloud.githubusercontent.com/assets/3791799/15429177/fb951f0e-1e9f-11e6-9f72-d2c993706519.png">

**Comment by pboisvert** [comment] 2016-05-20 14:32
Antom--can you check with UX if this is expected behavior or a bug in implementation (seems like a bug)?

**Comment by antboiko** [comment] 2016-05-20 15:59
Hi @fvillata , thanks for reporting this issue. The fix is already in develop branch and will be also available in one of future patches.

Best,
Anton.

**Comment by magento-engcom-team** [comment] 2017-09-20 22:10
@fvillata, thank you for your report.
The issue is already fixed in 2.1.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:10 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Fixed in 2.1.x, Issue: Format is not valid
