### ISSUE TITLE
Email Not Send and receive  Both Side. In magento 2 

### ISSUE THREAD

**Issue by mitulispace** [magento/magento2#7577] opened 2016-11-26 11:09 UTC
### Steps to reproduce

1.  Email Setting perfect   in Sales Email  But Email Not Work 
   like Oder Email, NEW A/C Email Means All Email Not Work. I Will Changed Port And Something Setting But no Understand please Any One Help me

### Expected result

1.  Email Send and Receive  Both Side 

### Actual result

1. Email Not Send  And Receive

Magento ver. 2.1.2

**Comment by vasilii-b** [comment] 2016-11-26 13:16
First, have a look at this #7289, then: 

1. Setup cron jobs.
2. Check if you have some modules that interrupt Magento default behaviour.

**Comment by mitulispace** [comment] 2016-11-28 09:48
But i will tried Setup Cron Jobs  Like Steps =>
php domain/html/bin/magento cron:run
php domain/html/update/cron.php
php domain/html/bin/magento setup:cron:run
Reference  
http://devdocs.magento.com/guides/v2.0/install-gde/install/post-install-config.html#post-install-cron
https://community.magento.com/t5/Admin-Configuration-Questions/not-able-to-send-transaction-emails-for-Magento-2/m-p/54132#M930
Any solutions How TO Solve  ???

**Comment by veloraven** [comment] 2016-11-28 13:03
@mitulispace thank you for your feedback.
If you think it to be an issue please describe detailed steps and your settings: so that we can reproduce your problem by your steps.
If you are looking for help and advise how to set up mails, please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. As GitHub issue tracker is intended for technical issues only.

**Comment by mitulispace** [comment] 2016-11-28 13:09
Email functionality Not Work  i tried  Some Setting And Port,Cron Job Setup   but Not Work. I think SMTP Not Work Hosting Side . 
Run Email Command in putty   But email  not Send Via Command  So I Think Hosting Side problem.
Ex.  mail -s testingmail testing@gmail.com
mailx -s "Test Mail" mitul.ispace@gmail.com

**Comment by mitulispace** [comment] 2016-11-28 13:16
@veloraven @vasilii-b 
Step 
Store => Advanced => System =>  Please check  Image  All Setting Proper Or not ???

![download](https://cloud.githubusercontent.com/assets/16436069/20669557/df77e788-b59a-11e6-9c01-c2d88a45fbcd.png)

**Comment by vasilii-b** [comment] 2016-11-29 06:25
@mitulispace 
The screenshot you gave says it's all fine with your Admin Configurations. But is seems you didn't configure Cron Jobs like is said in [DevDocs](http://devdocs.magento.com/guides/v2.0/install-gde/install/post-install-config.html#post-install-cron) after looking at your code:

> But i will tried Setup Cron Jobs Like Steps =>
php domain/html/bin/magento cron:run
php domain/html/update/cron.php
php domain/html/bin/magento setup:cron:run

To make sure it runs (cron), please have a look at your M2 database: table `cron_schedule`. If it is empty or have very, very old entries it seems like your cron job is not running at all.

You can give a try buy typing in your terminal (in M2 root directory) this command `php bin/magneto cron:run` and then see what's in table `cron_schedule`. This time you should be able to see some entries in this table.

If your hosting company uses DirectAdmin and you have access to it, I have an example on how to configure cron jobs for M2 there.

Good luck!

**Comment by mitulispace** [comment] 2016-11-29 10:58
@vasilii-b 
cron_schedule All Status  success But it means CronJob Start  ??

Cron_schedule  Table 
![db](https://cloud.githubusercontent.com/assets/16436069/20707289/cfb48b74-b650-11e6-948e-f0fe74609a88.png)

**Comment by veloraven** [comment] 2017-01-03 12:43
@mitulispace please format your description with accurate steps rather than a story.
Please describe your environment: OS, versions of PHP, MySQL, web-server, post-server.
Please let us know if you have any external extension installed.

And as you are looking for help how to fix your particular case rather than submitting general issue which should be fixed in next releases please  refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. As GitHub issue tracker is intended for technical issues only and not for discussions.

**Comment by veloraven** [comment] 2017-01-18 15:01
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Closed as completed by veloraven** 2017-01-18 15:01 UTC
Labels: Progress: needs update
