### ISSUE TITLE
Advanced Reporting 404 

### ISSUE THREAD

**Issue by MobiphoneNL** [magento/magento2#28660] opened 2020-06-10 09:16 UTC
**Intro**

Im having some issues with Advanced Reporting. I have tried a lot of different things, spent many hours debugging and took the necessary 24hrs waiting time in between each "experiment". Unfortunately, it does not work. I have tried it on a vanilla magento 2.3.5 with sample data and some orders. I verified whether the Magento Analytics Integration is correct by calling the Magento 2  API with the key of that user and I do get a response. However, I noticed something interesting, when I ping the advancedreporting.rjmetrics.com I do not get a response. I also checked whether it was down via the website  "downforjusteveryone.com" as well as "isitdownrightnow.com"  and it seems to be down. 

### Preconditions (*)

1. Magento 2.3.5 with sample Data on Amazon AWS EC2
2. SSL certificate is added
3. Magento Analytics users integration is create and tested

### Steps to reproduce (*)

1. Dashboard -> Advanced Reporting
2.

### Expected result (*)

1. The Advanced Reporting Page should open
2.

### Actual result (*)

1. The blue 404 screen opens
![Advanced Reporting 404](https://user-images.githubusercontent.com/66625718/84249631-50fd7800-ab0b-11ea-8269-740773527d6f.png)

2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sambath1293** [comment] 2020-06-10 11:02
@MobiphoneNL -This issue is a duplicate of https://github.com/magento/magento2/issues/24180
moving this ticket to closed.

**Closed as completed by sambath1293** 2020-06-10 11:02 UTC
Labels: duplicate, Issue: Format is valid, Reported on 2.3.5

**Comment by sambath1293** [comment] 2020-06-11 04:58
@MobiphoneNL -Thanks
