### ISSUE TITLE
Why Magento/Framework/AppInterface.php doesn't have VERSION const in develop branch? 

### ISSUE THREAD

**Issue by benbor** [magento/magento2#4369] opened 2016-05-02 08:25 UTC
Why VERSION const exists only for 2.0 branch? And it doesn't exist for develop branch.

**Comment by adragus-inviqa** [comment] 2016-05-02 08:54
I'm guessing because the code in the `develop` branch is not released, so it cannot have a version. Think of it as a git tag.

**Comment by benbor** [comment] 2016-05-02 10:09
It desn't have logic. Interface should always has the same definition from version to version. 
I'll just leave [symfony](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Kernel.php#L62) [](url) [laravel](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Application.php#L28)  links here

**Comment by mazhalai** [comment] 2016-05-02 18:28
It was refactored to be read from composer instead.
https://github.com/magento/magento2/commit/e46a3cfeccae6f8fcd1eb408719f48d2e039c433

**Comment by benbor** [comment] 2016-05-03 09:11
@mazhalai thx for the answer. But aim of my question is difference in the same interface between last released version and develop branch. Maby magento  should remove VERSION const from 2.0 branch? Guys, what do you think?

**Comment by mazhalai** [comment] 2016-05-09 17:56
AFAIK it will be removed in 2.1 
Closing since it is not a bug.

**Closed as completed by mazhalai** 2016-05-09 17:56 UTC
