### ISSUE TITLE
can't add or see products in catalog after upgrading from 2.0.6 to 2.1.1 and many other issues

### ISSUE THREAD

**Issue by terrybakshi** [magento/magento2#6515] opened 2016-09-06 22:58 UTC
### Preconditions

1. Magento version 2.1.1 php 5.6
### Steps to reproduce

1. Tried to add products wheel spinning but nothing is happening
2. Tried to see the old products in catalog still the wheel is spinning but nothing is happening.
3. before the issue occurred tried adding products, after adding the products, products don't appear in the front end. New Magento 2.1.1 Update is useless.
### Expected result

1. Magento Should thoroughly check the issues before rolling out the update, rather hassling other people.
### Actual result

1. 
   ![screenshot 3](https://cloud.githubusercontent.com/assets/13229022/18293956/4781c1b2-74d9-11e6-962a-b4a55745927a.png)
   ![screenshot 4](https://cloud.githubusercontent.com/assets/13229022/18293957/478d4640-74d9-11e6-9dcf-cd92ede31203.png)

**Comment by joanhe** [comment] 2016-09-06 23:22
It might be the same issue as in #6513

**Comment by shiftedreality** [comment] 2016-09-07 12:20
Hi @terrybakshi 

I would like to ask you to perform next steps:
1. Clean your`var` and `pub/static` folders
2. Clean your browser cache with `localStorage.clear();` in console
3. Open Browser console and paste here any errors that appearing there.

**Comment by andimov** [comment] 2016-09-27 09:40
@terrybakshi 
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Closed as completed by andimov** 2016-09-27 09:40 UTC
Labels: bug report, Progress: needs update, Component: Setup, Component: Catalog
