### ISSUE TITLE
Content Page grid view url doesn't work for some pages

### ISSUE THREAD

**Issue by MrBlueEyez** [magento/magento2#37869] opened 2023-08-09 13:00 UTC
### Preconditions and environment

- 2.4.6-p1
- Use the fix inside https://github.com/magento/magento2/pull/37532 so that the encoded uenc is also being decoded correctly.

### Steps to reproduce

1. Open the admin panel and login
2. Go towards Content > Elements > Pages
3. Make sure some pages are existing, and try to use the "View" action of some.

### Expected result

Every view action should work, and we should end up on the page we wanted to view.
As of 2.4.6 the url encode is working with RFC3986, and is decoding `=` to `~` instead of a comma.
We expect all urls to now work with tildes.

### Actual result

The view url is generated using the `Magento\Framework\Url\QueryParamsResolver` which is using the default php function `http_build_query` to convert the url . However the uenc which is included is using the new encoder, and so can have tildes in it. The `http_build_query` is using the `PHP_QUERY_RFC1738` instead of the `PHP_QUERY_RFC3986` which causes the tildes to be converted towards `%7E`.

This all ends up with the admin getting redirect towards the home page, and not the page that was requested.

### Additional information

It might be hard to reproduce this, as I am not 100% sure when the unencoded uenc contains `=`.

### Release note

Using RFC3986 in the http_build_query, to be in line with https://github.com/magento/magento2/pull/35885

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-08-10 12:06
Hi @MrBlueEyez,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Open the admin panel and login
- Go towards Content > Elements > Pages
- Make sure some pages are existing, and try to use the "View" action of some.


<img width="1387" alt="Screenshot 2023-08-10 at 2 14 46 PM" src="https://github.com/magento/magento2/assets/51680745/64df3e71-a82e-473f-ba74-ea0536419266">



<img width="1187" alt="Screenshot 2023-08-10 at 2 14 51 PM" src="https://github.com/magento/magento2/assets/51680745/39b4e9f7-cb06-4831-8b86-dedda3d19dc2">



<img width="1032" alt="Screenshot 2023-08-10 at 2 14 54 PM" src="https://github.com/magento/magento2/assets/51680745/847d9604-2d8a-4128-8c65-b9c92448dd46">


Every view action is working we are getting the page wanted to view and ~ converting instead of a comma.please let us if we are missing anything.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-08-21 06:07
Hi @MrBlueEyez,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/37869#issuecomment-1673093202 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by MrBlueEyez** [comment] 2023-08-21 06:24
Hello,
The issue is still reproducable, it is beter to check the decoded uenc inside the preview url itself. Instead of checking the final page you end up.
In the provided example provided by @engcom-Bravo I do not see any "~" inside the url, hence the situation is not reproduced.

Please try again with another page with larger names (I do not know what triggers the "=" inside base64 decoded string, but you will have to reproduce that)

**Comment by engcom-Bravo** [comment] 2023-08-31 08:54
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-08-31 11:55
Hi @MrBlueEyez,

Thanks for your update.

We have given ~ for content pages and it is converting into - in SEO.

<img width="1467" alt="Screenshot 2023-08-31 at 3 00 01 PM" src="https://github.com/magento/magento2/assets/51680745/ad9b1f33-ad22-4cda-b403-bbe4344c7a71">



<img width="1021" alt="Screenshot 2023-08-31 at 3 02 18 PM" src="https://github.com/magento/magento2/assets/51680745/ecf3565e-2352-4f26-bad7-7652248fcb51">



While giving ~ in SEO section we are getting below error.

<img width="1372" alt="Screenshot 2023-08-31 at 3 07 58 PM" src="https://github.com/magento/magento2/assets/51680745/449e08a8-d2bf-4d57-9172-ea7343cce658">



Could you please elaborate the steps to reproduce and also provide screenshots and video if possible it will helps us to reproduce the issue easily.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-09-05 07:00
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-09-05 13:25
Hi @MrBlueEyez,

Thanks for your update.

We have used this String **magentothusdw** which contains Encoded value as **bWFnZW50b3RodXNkdw==**.The same value we have given in Url key for pages.

<img width="1234" alt="Screenshot 2023-09-05 at 1 33 19 PM" src="https://github.com/magento/magento2/assets/51680745/1824839d-a8f2-4928-a243-05e0ded6c0b4">


<img width="939" alt="Screenshot 2023-09-05 at 1 34 10 PM" src="https://github.com/magento/magento2/assets/51680745/a9ce03aa-7762-4cf6-878d-4ad929094dc8">



The view action is working fine and we are able to access the page.Could you please let us know if we are missing anything.Please provide screenshots it will helps us to proceed further.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-09-21 06:14
Hi @MrBlueEyez,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-09-21 06:14 UTC
Labels: Issue: needs update, Reported on 2.4.6-p1
