### ISSUE TITLE
Issue in module-inventory-bundle-product with duplicate bundle product

### ISSUE THREAD

**Issue by vivekbhatt119** [magento/magento2#39358] opened 2024-11-12 09:30 UTC
### Preconditions and environment

- Magento version 2.4.7-p3
- magento/module-inventory-bundle-product

### Steps to reproduce

- create a new MSI source and stock
- create two simple product p1 and p2
- create bundle product b1 and p1 and p2 in one option.
- edit bundle product b1 and click save and duplicate.
- edit simple product p1 and click on save.

### Expected result

- product should save without any error.

### Actual result

- Getting error "Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "5" already exists."

### Additional information

when we duplicate the bundle product, we have duplicate entries of selection_id in catalog_product_bundle_selection.
When \Magento\InventoryBundleProduct\Model\GetChidrenSkusByParentIds::iterate() tries to load \Magento\Bundle\Model\ResourceModel\Selection\Collection, it is showing error as collection can not have multiple items with same ID.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-11-13 08:01
Hi @vivekbhatt119,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- create a new MSI source and stock
- create two simple product p1 and p2
- create bundle product b1 and p1 and p2 in one option.
- edit bundle product b1 and click save and duplicate.
- edit simple product p1 and click on save.



<img width="1440" alt="Screenshot 2024-11-13 at 10 59 27" src="https://github.com/user-attachments/assets/81141641-cbb2-4102-af05-80beafba9eb1">



<img width="1440" alt="Screenshot 2024-11-13 at 11 00 15" src="https://github.com/user-attachments/assets/59f9f9fd-5c3a-4946-82c5-6f895e561435">


We are able to save the product successfully.

Thanks.

**Comment by vivekbhatt119** [comment] 2024-11-13 09:09
hello @engcom-Bravo 
The issue is related to magento / inventory
you can close it here.

**Comment by engcom-Bravo** [comment] 2024-11-14 03:57
Hi @vivekbhatt119,

Thanks for your update.

As per this comment https://github.com/magento/magento2/issues/39358#issuecomment-2472913650 we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-11-14 03:57 UTC
Labels: Progress: done, Issue: needs update, Reported on 2.4.7-p3
