### ISSUE TITLE
Currency rate value not align proper in order information tab  when we create creditmemo from admin

### ISSUE THREAD

**Issue by dipti2jcommerce** [magento/magento2#20609] opened 2019-01-25 08:54 UTC
Currency rate value not align proper in order information tab  when we create creditmemo from admin

### Preconditions (*)

1.Magento 2.3
2.In admin configuration

### Steps to reproduce (*)

1.In admin configuration create credit memo for any order 
2.In Order information tab currency value not align proper

### Expected result (*)
![2019-01-25_14-23_new memo - credit memos](https://user-images.githubusercontent.com/18118638/51735248-e205b780-20ac-11e9-8d46-9202be150649.jpg)

### Actual result (*)
![2019-01-25_14-17_new memo - credit memos](https://user-images.githubusercontent.com/18118638/51735252-e7630200-20ac-11e9-94cb-afb114ac5bd1.jpg)

**Comment by magento-engcom-team** [comment] 2019-01-25 08:54
Hi @dipti2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dipti2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-25 08:54
Hi @nainesh2jcommerce. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by nainesh2jcommerce** [comment] 2019-01-25 08:56
Hi issue exist
![image](https://user-images.githubusercontent.com/18118539/51735598-d5359380-20ad-11e9-9c28-d8e934d6cc3c.png)

**Comment by magento-engcom-team** [comment] 2019-01-25 08:56
@nainesh2jcommerce Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97924` were created

**Comment by magento-engcom-team** [comment] 2019-01-31 22:55
Hi @dipti2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20613 by @dipti2jcommerce in 2.2-develop branch
Related commit(s):
 - [7bf7ce1c3b33a7e0fc9b7c095865dce3bb1f7209](https://github.com/magento/magento2/commit/7bf7ce1c3b33a7e0fc9b7c095865dce3bb1f7209)

The fix will be available with the upcoming 2.2.8 release.

**Closed as completed by magento-engcom-team** 2019-01-31 22:55 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Progress: PR Created, Area: Design/Frontend

**Comment by magento-engcom-team** [comment] 2019-02-10 22:30
Hi @dipti2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20610 by @dipti2jcommerce in 2.3-develop branch
Related commit(s):
 - [8c4dc05e1a2595a3c9a56831d8967514fd94adb0](https://github.com/magento/magento2/commit/8c4dc05e1a2595a3c9a56831d8967514fd94adb0)

The fix will be available with the upcoming 2.3.1 release.
