### ISSUE TITLE
Backorder Import does not refresh saleable quantity 

### ISSUE THREAD

**Issue by nadroj467** [magento/magento2#36356] opened 2022-10-21 20:23 UTC
### Preconditions and environment

- Fresh Magento 2.4.5 with demo data
- 
- And currently same issue in my magento 2.4.3 install

### Steps to reproduce

1. With demo data active ie. demo product stock showing SKU 24-MB05 with Default source showing 100 units
2. Import > Products > Add/Update with below CSV to take product out of stock 

`sku,min_qty,qty,backorders,is_in_stock,allow_backorders
24-MB05,0,0,0,0,0
`

3. WAIT for indexes to run and for quantity and SALEABLE quantity to both show 0 on product grid 

4. Import below CSV to allow backorders with min threshold

`sku,min_qty,qty,backorders,is_in_stock,allow_backorders
24-MB05,-5,0,1,1,1
`

5. Import and check product grid

### Expected result

Product grid should show qty = 0 and saleable quantity = 5  allowing product to be purchasable

### Actual result

Qty = 0, saleable quantity does not update. If you check the advanced inventory for product in admin it shows the import was successful. If you manually click save in the admin screen for the product the product becomes saleable again.

This makes managing backorders via imports impossible

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by nadroj467** [comment] 2022-10-21 20:27
@magento give me 2.4.5 instance

**Comment by engcom-Dash** [comment] 2022-10-25 08:08
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-10-25 11:32
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-10-25 13:11
@magento give me 2.4.5 instance

**Comment by engcom-Dash** [comment] 2022-10-26 01:56
Hi @nadroj467 ,
We are trying to reproduce the issue in 2.4-develop branch...But we are not able to reproduce the issue.We are expected result.we got a result like "Product grid should show qty = 0 and saleable quantity = 5 ".So we are not able to reproduce the issue.
Let us know if we missing anything!!!

Thanks!!!

**Comment by engcom-Lima** [comment] 2022-10-26 12:54
@magento give me 2.4-develop instance

**Comment by nadroj467** [comment] 2022-10-26 21:50
@magento give me 2.4-develop instance

**Comment by nadroj467** [comment] 2022-10-26 22:22
Hi @engcom-Dash 
I have been able to reproduce using the attached files.

1. Set all indexes to run by schedule 
2. Check stock of 24-MB04 is 100 quantity and 100 saleable on product grid
3. Import file 1stImport.csv (the import actually doesn't give competition notice but data is imported .... not sure if thats a new bug all together)
4. Check product grid for 24-MB04 wait until quantity is updated by index to 0 and saleable is 0 (both need to be 0)
5. Import file 2ndImport.csv look back at the grid, allow some time for indexing
6. Notice product grid does not update to 0 quantity, 5 saleable. But if you click into the product advanced inventory and check the import was successful the data is there. Do not click save on exit as this resolves the issue


[2ndImport.csv](https://github.com/magento/magento2/files/9874003/2ndImport.csv)
[1stImport.csv](https://github.com/magento/magento2/files/9874004/1stImport.csv)

**Comment by nadroj467** [comment] 2022-10-26 22:29
@engcom-Dash here is a screen record of the issue https://icecreamapps.com/v/ddh2v43

**Comment by nadroj467** [comment] 2022-10-26 22:44
@engcom-Dash here is a screen record of the issue (I used a different sku in the video)  https://icecreamapps.com/v/gqdhses

**Comment by engcom-Dash** [comment] 2022-10-28 05:18
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-10-28 08:19
Hi @nadroj467 ,

Thanks for your information...
We tried the steps which is given by you...We are not able to reproduce the issue..Because the import actually doesn't give completion me also as well as the data is not imported in the particular product... For your reference i attached the screenshots...Kindly check its...Thanks!!!
<img width="1512" alt="Screenshot 2022-10-28 at 12 51 53 PM" src="https://user-images.githubusercontent.com/60198592/198539296-02dab4e7-8523-48aa-9bce-ec586d582ffe.png">
<img width="1512" alt="Screenshot 2022-10-28 at 12 53 39 PM" src="https://user-images.githubusercontent.com/60198592/198539345-712a1295-9bb4-472a-ae52-59fda7011cd9.png">


There is no changes in product quantity....So we are not able to reproduce the issue.

Let us know if we missing anything!!!!

Thanks!!!

**Comment by nadroj467** [comment] 2022-10-28 08:21
@engcom-Dash You can see the screen record here https://icecreamapps.com/v/gqdhses

**Comment by engcom-Dash** [comment] 2022-10-31 10:47
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-10-31 12:51
Hi @nadroj467 ,

We are trying to reproduce the issue in 2.4 develop branch...we are not able to reproduce the issue.

We are worked as per your last comments with 24-MB06. Event hough we are not not able reproduce the issue.

We are getting same results...The product quantity and saleable quantity is not changing.

Here i attached screenshots for your reference:

<img width="1512" alt="Screenshot 2022-10-31 at 5 28 44 PM" src="https://user-images.githubusercontent.com/60198592/199011850-47df52ba-ee6c-4159-a574-ce0a013b534c.png">


<img width="1512" alt="Screenshot 2022-10-31 at 5 28 42 PM" src="https://user-images.githubusercontent.com/60198592/199011900-6a4cfb01-b42e-41cb-8499-561f77a0250e.png">

There is no changes in both quantity and saleable quantity....

Kindly let us know if we Missing anything!!!

Thanks!!!!

**Comment by engcom-Dash** [comment] 2022-11-14 05:31
Hi @nadroj467 ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2022-11-14 05:31 UTC
Labels: Issue: needs update, Reported on 2.4.5
