### ISSUE TITLE
Error saving new order status in backend

### ISSUE THREAD

**Issue by jaimestuardo** [magento/magento2#4146] opened 2016-04-13 22:28 UTC
When going to order status page in backend, and then create a new status, I tried to add "Delivered" state, so I entered "delivered" in code and "Delivered" in label. After pressing "Save Status" button, this error is shown:

Warning: Invalid argument supplied for foreach() in /home/depasa/public_html/vendor/magento/module-sales/Controller/Adminhtml/Order/Status/Save.php on line 32
#0 /home/depasa/public_html/vendor/magento/module-sales/Controller/Adminhtml/Order/Status/Save.php(32): Magento\Framework\App\ErrorHandler->handler(2, 'Invalid argumen...', '/home/depasa/pu...', 32, Array)
#1 /home/depasa/public_html/var/generation/Magento/Sales/Controller/Adminhtml/Order/Status/Save/Interceptor.php(24): Magento\Sales\Controller\Adminhtml\Order\Status\Save->execute()
#2 /home/depasa/public_html/vendor/magento/framework/App/Action/Action.php(102): Magento\Sales\Controller\Adminhtml\Order\Status\Save\Interceptor->execute()
#3 /home/depasa/public_html/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#4 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#5 /home/depasa/public_html/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#6 /home/depasa/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Sales\Controller\Adminhtml\Order\Status\Save\Interceptor->___callParent('dispatch', Array)
#7 /home/depasa/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Sales\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Status\Save\Interceptor), Array, 'adminAuthentica...')
#8 /home/depasa/public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#9 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Status\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#10 /home/depasa/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#11 /home/depasa/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Sales\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Status\Save\Interceptor), Array, 'designLoader')
#12 /home/depasa/public_html/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#13 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Status\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 /home/depasa/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#15 /home/depasa/public_html/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Sales\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Status\Save\Interceptor), Array, 'adminMassaction...')
#16 /home/depasa/public_html/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Sales\Controller\Adminhtml\Order\Status\Save\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#17 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Status\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 /home/depasa/public_html/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#19 /home/depasa/public_html/var/generation/Magento/Sales/Controller/Adminhtml/Order/Status/Save/Interceptor.php(39): Magento\Sales\Controller\Adminhtml\Order\Status\Save\Interceptor->___callPlugins('dispatch', Array, Array)
#20 /home/depasa/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Sales\Controller\Adminhtml\Order\Status\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#21 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /home/depasa/public_html/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#23 /home/depasa/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#24 /home/depasa/public_html/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#25 /home/depasa/public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#26 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#27 /home/depasa/public_html/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#28 /home/depasa/public_html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#29 /home/depasa/public_html/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#30 /home/depasa/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#31 /home/depasa/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#32 {main}

**Comment by NadiyaS** [comment] 2016-04-19 13:49
Hi @jaimestuardo ,

this bug is not reproducible on latest magento version. Please upgrade your magento version. 
If you still have the same problem, please provide more detailed steps to reproduce. 

Regards

**Comment by jaimestuardo** [comment] 2016-04-28 21:06
The problem is that I cannot upgrade because of another bug in update system. However, I have 2.0.2. Do you reallythink this is the cause?

**Comment by jaimestuardo** [comment] 2016-05-04 23:07
I have upgraded to version 2.0.4 but the same error occurs.

**Comment by piotrekkaminski** [comment] 2016-05-24 16:29
We cannot reproduce on latest develop version. Are you able to check there as well? Is it reproducible in vanilla installation?

**Comment by nsergo** [comment] 2016-06-07 06:41
I get this error when Single-Store Mode is turned on, but it's fine if it's turned off. Version is 2.0.7

**Comment by jaimestuardo** [comment] 2016-06-10 12:18
@nsergo Thanks!! I have turned Single Store mode off and it worked! What is really the difference if that setting is off or on?

@piotrekkaminski Can you try to reproduce it by turning that settng on?

**Comment by NadiyaS** [comment] 2016-06-10 12:33
Hi @jaimestuardo , @nsergo ,
thank you for this additional condition. 
Internal ticket MAGETWO-54191 was created to track this issue.

**Comment by NadiyaS** [comment] 2016-06-21 15:43
Hi,
the fix was delivered to develop branch [6176951](https://github.com/magento/magento2/commit/61769514a1180a69adf3281058dc05c20c2cf4da)
The issue is closed as resolved.

**Closed as completed by NadiyaS** 2016-06-21 15:43 UTC
Labels: Issue: Ready for Work, bug report

**Comment by dferramosi** [comment] 2016-12-28 20:58
I am sorry to add to a closed issue, but I am getting this in 2.0.10 - any recommendations? (I do have single store mode on)
