### ISSUE TITLE
Exception undefined variable itemsOrderItemId while creating shipment through MSI

### ISSUE THREAD

**Issue by mohammadzakir** [magento/magento2#19940] opened 2018-12-22 08:35 UTC
### Preconditions (*)

1. Magento 2.3.0
2. Php version 7.2
3. Developer mode should be enable 

### Steps to reproduce (*)

1. Login to Admin Panel 
2. On left navigation goto Stores-> Inventory->sources
3. Create two source
4. Now goto left navigation Stores-> Inventory->stocks
5. Create stock with Sales Channels : Main website , and add source created above to the stock
6. Go to Catalog->products 
7. Click edit button of any products which is type of simple product , now assign two source and add quantity to them, at last save product.
8. repeat step 7 for another product
9. Now goto frontend and place order of above mentioned two products of single quantity each.
10. From admin panel select order and create shipment
11. Ship only one products from first source.
12. Now one product shipped from first source
13. Try to ship that product again.

### Expected result (*)

1. The process should be done without any error

### Actual result (*)
1. Showing Exception Notice: undefined variable itemsOrderItemId
![screenshot from 2018-12-22 13-29-01](https://user-images.githubusercontent.com/43291220/50372302-5652c400-05f2-11e9-825f-b771782e9bb2.png)

**Comment by magento-engcom-team** [comment] 2018-12-22 08:35
Hi @mohammadzakir. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mohammadzakir do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-12-22 08:35
Hi @GovindaSharma. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by GovindaSharma** [comment] 2018-12-22 08:36
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2018-12-22 08:36
Hi @GovindaSharma. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2018-12-22 08:37
Hi @GovindaSharma, here is your [Magento instance](https://i-19940-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19940-2-3-develop.instances.magento-community.engineering/admin](https://i-19940-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by GovindaSharma** [comment] 2018-12-22 09:03
@mohammadzakir nice catch...Since it is related to MSI and in develop branch MSI feature not present,but its look like issue is there so created a pull request for this as the same file is present in develop branch

**Comment by magento-engcom-team** [comment] 2018-12-22 18:01
@shikhamis11 Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2018-12-22 18:01
@shikhamis11 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97303` were created

**Comment by magento-engcom-team** [comment] 2018-12-23 13:33
Hi @maheshWebkul721. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by sidolov** [comment] 2019-01-04 22:18
Hi @mohammadzakir. Thank you for your report. 
The issue has been fixed in magento/magento2#19941 by @GovindaSharma in 2.3-develop branch
Related commit(s):
 - [b54ab2dc9cf90c5186765e94e067704fc4b382e7](https://github.com/magento/magento2/commit/b54ab2dc9cf90c5186765e94e067704fc4b382e7)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by sidolov** 2019-01-04 22:18 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by sidolov** [comment] 2019-01-14 19:05
Hi @mohammadzakir. Thank you for your report. 
The issue has been fixed in magento/magento2#20082 by @milindsingh in 2.2-develop branch
Related commit(s):
 - [4802e00643bae377a254e8d9b92e2bad72c33e65](https://github.com/magento/magento2/commit/4802e00643bae377a254e8d9b92e2bad72c33e65)
 - [cb15b010ddf4bbe9caddac141dfb829926c4a631](https://github.com/magento/magento2/commit/cb15b010ddf4bbe9caddac141dfb829926c4a631)

The fix will be available with the upcoming 2.2.8 release.
