### ISSUE TITLE
Garbage code issue

### ISSUE THREAD

**Issue by ghost** [magento/magento2#25214] opened 2019-10-22 12:59 UTC
### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

Unnecessary closing span tag is written in the getHintHtml function in \Magento\Backend\Block\Store\Switcher.php

### Expected result (*)

![image](https://user-images.githubusercontent.com/56463897/67288402-8876d000-f4fa-11e9-8542-3e34ac621c8f.png)

### Actual result (*)

![image](https://user-images.githubusercontent.com/56463897/67288420-93c9fb80-f4fa-11e9-8880-a0c50eae94e0.png)

**Comment by dmytro-ch** [comment] 2019-10-22 17:48
Hello @vishesh-webkul, could you please provide Steps to reproduce to simplify the testing process for quality assurance team?
Thank you!

**Comment by dmytro-ch** [comment] 2019-10-23 05:50
@vishesh-webkul, please provide proper manual testing scenarios.

**Comment by dmytro-ch** [comment] 2019-10-23 06:01
The issue is related to the tooltip block for the store switcher widget on Admin Dashboard.
![Screenshot 2019-10-23 at 08 56 46](https://user-images.githubusercontent.com/11693779/67362398-94eb3f00-f573-11e9-84a6-622e588ede8c.png)
![Screenshot 2019-10-23 at 08 58 47](https://user-images.githubusercontent.com/11693779/67362399-94eb3f00-f573-11e9-9cd0-af8744d1ed70.png)

**Comment by magento-engcom-team** [comment] 2019-10-23 06:02
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22026` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Delta** [comment] 2019-10-28 12:59
Issue is fixed by [#25215](https://github.com/magento/magento2/pull/25215)
Change status to **Closed**

**Closed as completed by engcom-Delta** 2019-10-28 12:59 UTC
Labels: Issue: Ready for Work, Progress: needs update, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Backend
