### ISSUE TITLE
Tier price some times show and some times not displayed

### ISSUE THREAD

**Issue by Yuwei9291** [magento/magento2#28612] opened 2020-06-08 07:09 UTC
### Preconditions (*)

1.Magento 2.3.5-p1
2.Production mode

### Steps to reproduce (*)

1.upload simple products and add to configurable product.
2.upload advanced price 
2.go to configurable product

### Expected result (*)

1. Show tier price under price in product page
![expect](https://user-images.githubusercontent.com/45879513/84001005-5d14f880-a998-11ea-85a1-860d990e2221.png)

### Actual result (*)

**1.** For the configurable product include different price simple products, some items will show the tier price but some won't show.
![expect](https://user-images.githubusercontent.com/45879513/84001005-5d14f880-a998-11ea-85a1-860d990e2221.png)
![actual](https://user-images.githubusercontent.com/45879513/84001060-7cac2100-a998-11ea-9ae5-4bd3008e703f.png)
![actual2](https://user-images.githubusercontent.com/45879513/84001210-bc730880-a998-11ea-9026-1a7a5916bb9e.png)
As you can see, tier price for this sku was applied in the shopping cart but hid in product page.
**2.**For the configurable product with same price simple products, no tier price will be displayed in product page. 

![actual3](https://user-images.githubusercontent.com/45879513/84001409-1f649f80-a999-11ea-8cdf-15af10736151.png)
As you can see from the shopping cart page, the tier prices are set correctly.
![actual4](https://user-images.githubusercontent.com/45879513/84001570-7a969200-a999-11ea-9855-8caae2a456ba.png)
**3.** Additional, there is no problem with the price display for simple products, it will also show the lowest price. It would be great if configurable product could be displayed this way as well.

![actual5](https://user-images.githubusercontent.com/45879513/84001809-f85a9d80-a999-11ea-8678-30248e7c74cd.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by swathishs** [comment] 2020-06-11 13:19
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-11 13:19
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by swathishs** [comment] 2020-06-12 05:48
@Yuwei9291: Issue is not reproducible in Magento 2.4 develop instance
Please find the attachment below:

1. Configurable product:
![image](https://user-images.githubusercontent.com/58288685/84469178-11b36080-ac9e-11ea-87e6-e0441402c0f9.png)

2. Product detail page:
![image](https://user-images.githubusercontent.com/58288685/84469213-23950380-ac9e-11ea-9a26-d4f47d8ee534.png)

3. Cart page:
![image](https://user-images.githubusercontent.com/58288685/84469291-55a66580-ac9e-11ea-9e78-a34cd0ed15d9.png)

**Comment by swathishs** [comment] 2020-06-12 05:48
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment] 2020-06-12 05:48
Hi @swathishs. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment] 2020-06-12 05:49
Hi @swathishs, here is your [Magento instance](https://i-28612-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-28612-2-3-5-p1.instances.magento-community.engineering/admin_ce7f](https://i-28612-2-3-5-p1.instances.magento-community.engineering/admin_ce7f)
Login: `cfbbaefc` Password: `320eda01258c`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment] 2020-06-12 07:37
@Yuwei9291: Issue is reproducible in Magento 2.3.5-p1 instance

I have added 8 products and the first product has this problem

Please find the attachment :

1. Admin:
![image](https://user-images.githubusercontent.com/58288685/84476747-3a425700-acac-11ea-8a43-c807eb15f412.png)

2. Product detail page:
![image](https://user-images.githubusercontent.com/58288685/84476942-7f668900-acac-11ea-9890-ace448b33037.png)

3. Cart page:
![image](https://user-images.githubusercontent.com/58288685/84477046-a4f39280-acac-11ea-9eca-5ab8b299c57f.png)
![image](https://user-images.githubusercontent.com/58288685/84477126-c8b6d880-acac-11ea-8aa8-cba156b7211c.png)

Viedo for reference:
![igX9IpHla0](https://user-images.githubusercontent.com/58288685/84477656-98bc0500-acad-11ea-9bc3-1ba0c8099b21.gif)

**Comment by swathishs** [comment] 2020-06-12 07:47
Can be reproduced only on 2.3.5p1 but not on 2.4 develop instance

**Comment by magento-engcom-team** [comment] 2020-06-12 07:50
:white_check_mark: Confirmed by @swathishs 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35131` were created

**Issue Available**: @swathishs, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2020-07-15 21:26
Hi @Yuwei9291. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-35131` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Closed as completed by magento-engcom-team** 2020-07-15 21:26 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Issue:  Cannot Reproduce, Issue: Format is valid, Component: ConfigurableProduct, Reproduced on 2.3.5p1, Reported on 2.3.5-p1
