### ISSUE TITLE
2.4.1 Infinite loop detected

### ISSUE THREAD

**Issue by weiqj** [magento/magento2#30557] opened 2020-10-20 01:04 UTC
### Preconditions (*)

1. Magento 2.4.1

### Steps to reproduce (*)

1. Add a product to cart

### Expected result (*)

1. Exception

### Actual result (*)

Infinite loop detected, review the trace for the looping path at /var/www/magento/vendor/magento/module-checkout/Model/Session.php:241)"

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by librehome** [comment] 2020-10-20 01:37
Please ignore. It was caused by a module. Just contacted their support.

**Comment by ihor-sviziev** [comment] 2020-10-20 03:32
Hi @weiqj ,
I'm closing this issue as it's causses by some external extension

**Comment by ihor-sviziev** [comment] 2020-10-20 03:32
Hi @weiqj

**Closed as completed by ihor-sviziev** 2020-10-20 03:32 UTC
Labels: Progress: done, not-confirmed, Reported on 2.4.1
