### ISSUE TITLE
Product video is not Opening/Playing in mobile device (YouTube embedded video)

### ISSUE THREAD

**Issue by Ritesh-Rana** [magento/magento2#36376] opened 2022-10-27 05:35 UTC
### Preconditions and environment

Magento version 2.4.4
php version 8.1.11

### Steps to reproduce

1- login as admin, go to  Catalog  > Products > Add new Product .
2- Create new simple product.
3-  Go to Images and videos and click on Add video
![Screenshot from 2022-10-27 10-46-43](https://user-images.githubusercontent.com/109286689/198198055-5d13f686-7d05-455a-9437-f8fb923740cc.png).
4- Now add YouTube video Link in URL and save and save product.
5- Now go to storefront search for product that recently we have added.
6- Now open developer tool in chrome browser and select mobile view (view as any mobile/phone).
7- Now play video of product.

### Expected result

Video of product should be played.
[Screencast from 27-10-22 11:01:17 AM IST.webm](https://user-images.githubusercontent.com/109286689/198199794-a86c54c5-3555-4d08-b280-3cee87172896.webm)

### Actual result

Video of product is not playing/opening in iframe.
[Screencast from 27-10-22 11:02:27 AM IST.webm](https://user-images.githubusercontent.com/109286689/198199900-72355593-96b1-4674-956b-627d335dccb5.webm)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Ritesh-Rana** [comment] 2022-10-27 12:35
Hi, @engcom-Bravo let me know if more information is required about this.

**Comment by engcom-Bravo** [comment] 2022-11-04 07:44
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-04 11:39
Hi @Ritesh-Rana,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the video.


Steps Followed :

1- login as admin, go to Catalog > Products > Add new Product .
2- Create new simple product.
3- Go to Images and videos and click on Add video.
4- Now add YouTube video Link in URL and save and save product.
5- Now go to storefront search for product that recently we have added.
6- Now open developer tool in chrome browser and select mobile view (view as any mobile/phone).
7- Now play video of product.



https://user-images.githubusercontent.com/51680745/199963956-a48deede-a669-4cd0-9c1d-2e17a7e0c830.mov



Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.


Thanks.

**Comment by engcom-Lima** [comment] 2022-11-04 14:08
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-18 06:12
Hi @Ritesh-Rana,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-11-18 06:12 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.4
