### ISSUE TITLE
Recently viewed products not working in product page with enabled page cache(FPC)

### ISSUE THREAD

**Issue by JananiKrishnan** [magento/magento2#5137] opened 2016-06-21 16:03 UTC
## Steps to reproduce

1.add: <block class="Magento\Reports\Block\Product\Widget\Viewed" page_size="4" name="recently_viewed" template="widget/viewed/content/viewed_grid.phtml" cacheable="false" />  to catalog_product_view.xml in any container
or
Add recently viewed widget in product detail page
1. The magento we use is multi site with multiple themes .

Expected result
With all cache enabled you should see recently viewed products block in product page.

Actual result
Block is visible only with disabled **page cache** alone, when page cache is enabled, it does not have output.

**Comment by duhon** [comment] 2016-06-22 12:31
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by JananiKrishnan** [comment] 2016-06-22 13:47
We used Community version 2.0.2 and also we faced issue in Enterprise edition version 2.0.4.. We have checked in latest version also.

**Comment by serzhik** [comment] 2016-06-29 14:50
Duplicate #3890

**Comment by andimov** [comment] 2016-08-01 15:37
@JananiKrishnan 
Thank you for reporting!

This is a duplicate issue. I'm closing this one. Please feel free to reopen if you have any additional questions about theme selection.

**Closed as completed by andimov** 2016-08-01 15:37 UTC
Labels: bug report
