### ISSUE TITLE
Magento 2.4.2 to 2.4.3 Upgrade Issue

### ISSUE THREAD

**Issue by intheshallow** [magento/magento2#33754] opened 2021-08-11 15:34 UTC
### Preconditions (*)

1. 2.4.2 upgrading to 2.4.3

### Steps to reproduce (*)

1. Start on 2.4.2. Run composer require magento/product-community-edition 2.4.3 --no-update
2. Run composer update
3. Run php bin/magento setup:upgrade && php bin/magento setup:di:compile

### Expected result (*)

1. Successfully upgrading to 2.4.3

### Actual result (*)

1. Getting this error instead: Unable to apply data patch Magento\Paypal\Setup\Patch\Data\UpdateBmltoPayLater for module Magento_Paypal. Original exception message: Notice: Undefined offset: 1 in /chroot/home/ac9de204/55c08fbd8a.nxcli.net/magento/vendor/magento/module-paypal/Setup/Patch/Data/UpdateBmltoPayLater.php on line 138

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment] 2021-08-11 18:19
Duplicate of https://github.com/magento/magento2/issues/33678, hopefully the advise in there can help you further.

**Comment by abude** [comment] 2021-08-23 00:39
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment] 2021-08-23 08:34
Hi @intheshallow,

As @hostep said, this issue is a duplicate of #33751.

Based on it, can you please check and advise if your issue is resolved ?

**Comment by birdman002** [comment] 2021-08-23 14:56
We came across this issue when we upgraded I ended up removing the `payment/paypal_express_bml/active` from the `core_config_data` table. 

The core is bombing on this because it is trying to explode one the `_` on the last param. Since active doesn't have a `_` it fails

**Comment by hostep** [comment] 2021-08-23 15:18
A fix landed in https://github.com/magento/magento2/commit/5753111dc7ba1dca2ef0ca98f7d0abac488ebbb2

Also this ticket is a duplicate of https://github.com/magento/magento2/issues/33678, which contains some other interesting comments.
We should close this one, @engcom-Lima, could you do that? 🙂

**Closed as completed** 2021-08-27 05:38 UTC
Labels: duplicate, Issue: needs update, Reported on 2.4.3
