### ISSUE TITLE
Incorrect currency symbol for surinamese dollar

### ISSUE THREAD

**Issue by Fuseteam** [magento/magento2#30589] opened 2020-10-21 14:15 UTC
### Preconditions (*)

Magento 2.4-develop
### Steps to reproduce (*)

1. set base currency to Suriname Dollar

### Expected result (*)

1. prices on the catalog and the frontend to be prepended with the SRD symbol
![image](https://user-images.githubusercontent.com/51681379/96878073-16292a80-1483-11eb-952a-fe5fe3f9c84e.png)

### Actual result (*)

1. prices on the catalog and the frontend are prepended with the $ symbol
![2020-10-21-102115_410x319_scrot](https://user-images.githubusercontent.com/10421851/96732688-003a3d80-138f-11eb-9b87-133554cb22e1.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by bhanu-webkul** [comment] 2020-10-22 05:38
@Fuseteam 
Suriname Dollar
Currency
The Surinamese dollar has been the currency of Suriname since 2004. It is normally abbreviated with the dollar sign $, or alternatively Sr$ to distinguish it from other dollar-denominated currencies. It is divided into 100 cents. Wikipedia
Official website: cbvs.sr
Symbol: $
Thats why i showing $ this symbol on front end

**Comment by magento-engcom-team** [comment] 2020-10-22 13:26
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38657` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Fuseteam** [comment] 2020-10-22 14:05
> @Fuseteam
> Suriname Dollar
> Currency
> The Surinamese dollar has been the currency of Suriname since 2004. It is normally abbreviated with the dollar sign $, or alternatively Sr$ to distinguish it from other dollar-denominated currencies. It is divided into 100 cents. Wikipedia
> Official website: cbvs.sr
> Symbol: $
> Thats why i showing $ this symbol on front end

i am from suriname we never actually abbreviate as $ or sr$ we abbreviate it as SRD, this is also set by default in magento admin console but i don't see anywhere else but in the configuration section

**Comment by gabrieldagama** [comment] 2020-10-23 11:53
@magento I'm working on this

**Comment by Amit-Hariyani** [comment] 2020-10-27 06:27
@magento I'm working on this

**Comment by Amit-Hariyani** [comment] 2020-10-27 11:21
> The solution is remove tick mark below SRD currency and place one space before SRD it will work as per your requirement
![demo](https://user-images.githubusercontent.com/72494149/97294929-ac3ec580-1874-11eb-9d88-6847579756c0.jpg)

**Comment by Fuseteam** [comment] 2020-10-27 14:10
not sure if i have tested that @Amit-Hariyani  but if that works its really just confusing; it says SRD by default why should unticking that box make a difference

**Comment by aasim110** [comment] 2020-10-31 05:38
@magento  I'm working on this

**Comment by gabrieldagama** [comment] 2021-02-18 17:29
Hi @Fuseteam, thanks for reporting this issue.

Just to clarify, regards Wikipedia https://en.wikipedia.org/wiki/Surinamese_dollar the symbol for Surinamese dollar is the same as USD, can you confirm that?

Thank you!

**Comment by Fuseteam** [comment] 2021-02-19 16:05
@gabrieldagama as someone living in suriname i can confirm that it does not use $ symbol in practice nor Sr$ we use SRD
ah couple of examples:
https://www.kirpalani.com/nl/apparaten
https://www.hsdsonline.com/nl/shop/
https://kev.store/product-category/computers-electronica/
please don't ask me this over and over again [I already confirmed this in october](https://github.com/magento/magento2/issues/30589#issuecomment-714518001) i live in suriname if you still doubt me go ask on reddit.com/r/suriname or something

**Comment by engcom-Bravo** [comment] 2024-10-23 04:49
Hi @Fuseteam,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="1415" alt="Screenshot 2024-10-23 at 10 17 46" src="https://github.com/user-attachments/assets/8f5888e7-af3b-4586-bf12-b4a65abb97b8">



<img width="1415" alt="Screenshot 2024-10-23 at 10 17 39" src="https://github.com/user-attachments/assets/020e9012-530e-4029-868e-8a7af8f51063">


prices on the catalog and the frontend to be prepended with the SRD symbol

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-10-23 04:49 UTC
Labels: Issue: Confirmed, Component: CurrencySymbol, Reproduced on 2.4.x, Priority: P2, Progress: done, Reported on 2.4.0, Area: Admin UI
