### ISSUE TITLE
pagebuilder ( element margins ) doesn't compatible with direction rtl

### ISSUE THREAD

**Issue by ppeyman** [magento/magento2#36455] opened 2022-11-10 16:00 UTC
### Preconditions and environment

- 2.4.5-p1
- magento default luma theme 

### Steps to reproduce

1.create a row from pagebuilder 
2.add a column to the row 
3.add to banner or add to image 
4.go to settings of each of them 
5. add margin left or right for both of them

### Expected result

when i added a css code `direction:rtl` margins doesn't works well

![Selection_005](https://user-images.githubusercontent.com/13271466/201142901-2b8cb124-4594-4cf8-831b-f16daf324f25.png)

![Selection_006](https://user-images.githubusercontent.com/13271466/201144298-4a8502d6-3f96-458d-8178-40c1a58b34d3.png)

### Actual result

margin doesn't works in rtl direction 

![Selection_004](https://user-images.githubusercontent.com/13271466/201143119-e71dda58-4f8e-423e-83ab-541b7f5de028.png)

### Additional information

and when i add custom `direction:ltr` works well : 

![Selection_003](https://user-images.githubusercontent.com/13271466/201143320-28163b3f-e917-41bd-a8c9-6bc3f9677877.png)

Regards 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-11-11 08:31
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-11 10:19
Hi @ppeyman,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce** :

1.create a row from pagebuilder
2.add a column to the row
3.add to banner or add to image
4.go to settings of each of them
5. add margin left or right for both of them

We are getting Margin Space as per dimensions we are given in settings.



<img width="1479" alt="Screenshot 2022-11-11 at 3 15 52 PM" src="https://user-images.githubusercontent.com/51680745/201318237-f8c1c98e-2e0c-4096-84e9-c7ca8340090b.png">



As per Magento [devdocs](https://docs.magento.com/user-guide/v2.3/cms/page-builder-layout-row.html).  Margins are used for Blank spaces.


<img width="948" alt="Screenshot 2022-11-11 at 3 46 40 PM" src="https://user-images.githubusercontent.com/51680745/201319169-c281a403-fd20-4537-a027-2cc50db020d4.png">



Kindly go through with this document and please let us know if you are still facing any issue.

Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by ppeyman** [comment] 2022-11-11 13:23
> Hi @ppeyman,
> 
> Thanks for your update.
> 
> Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.
> 
> **Steps to reproduce** :
> 
> 1.create a row from pagebuilder 2.add a column to the row 3.add to banner or add to image 4.go to settings of each of them 5. add margin left or right for both of them
> 
> We are getting Margin Space as per dimensions we are given in settings.
> 
> <img alt="Screenshot 2022-11-11 at 3 15 52 PM" width="1479" src="https://user-images.githubusercontent.com/51680745/201318237-f8c1c98e-2e0c-4096-84e9-c7ca8340090b.png">
> 
> As per Magento [devdocs](https://docs.magento.com/user-guide/v2.3/cms/page-builder-layout-row.html). Margins are used for Blank spaces.
> 
> <img alt="Screenshot 2022-11-11 at 3 46 40 PM" width="948" src="https://user-images.githubusercontent.com/51680745/201319169-c281a403-fd20-4537-a027-2cc50db020d4.png">
> 
> Kindly go through with this document and please let us know if you are still facing any issue.
> 
> Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.
> 
> Thanks.

i said when we have direction rtl tag margins doesn't works in luma fresh default theme 
i don't know how explain it to you 
thanks

**Comment by engcom-Bravo** [comment] 2022-11-14 10:02
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-14 12:20
Hi @ppeyman,

Thanks for your Update.


Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

Steps to reproduce :

1.create a row from pagebuilder
2.add a column to the row
3.add to banner or add to image
4.go to settings of each of them
5. add margin left or right for both of them


Before applying `direction:rtl`

<img width="1444" alt="Screenshot 2022-11-14 at 4 00 34 PM" src="https://user-images.githubusercontent.com/51680745/201657687-513220c0-5058-4c3f-a9f8-3dca43c24287.png">



After applying `direction:rtl`

<img width="1417" alt="Screenshot 2022-11-14 at 4 07 34 PM" src="https://user-images.githubusercontent.com/51680745/201657731-59ceaa89-a57d-4634-9d1a-29d4716ff904.png">


The images are changed from left to right.





Kindly let us know if we miss anything.

Thanks.

**Comment by ppeyman** [comment] 2022-11-18 08:01
> Hi @ppeyman,
> 
> Thanks for your Update.
> 
> Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.
> 
> Steps to reproduce :
> 
> 1.create a row from pagebuilder 2.add a column to the row 3.add to banner or add to image 4.go to settings of each of them 5. add margin left or right for both of them
> 
> Before applying `direction:rtl`
> 
> <img alt="Screenshot 2022-11-14 at 4 00 34 PM" width="1444" src="https://user-images.githubusercontent.com/51680745/201657687-513220c0-5058-4c3f-a9f8-3dca43c24287.png">
> 
> After applying `direction:rtl`
> 
> <img alt="Screenshot 2022-11-14 at 4 07 34 PM" width="1417" src="https://user-images.githubusercontent.com/51680745/201657731-59ceaa89-a57d-4634-9d1a-29d4716ff904.png">
> 
> The images are changed from left to right.
> 
> Kindly let us know if we miss anything.
> 
> Thanks.

did you check it in frontend side result  ? 

i saw the result in frontend side

**Comment by engcom-Bravo** [comment] 2022-11-23 12:07
Hi @ppeyman,

Thanks for your Update.

Kindly can you please elaborate steps We are Verified in frontend side.

Thanks.

**Comment by engcom-Bravo** [comment] 2022-12-07 06:03
Hi @ppeyman,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-12-07 06:03 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1
