### ISSUE TITLE
Can't create label for existing shipment

### ISSUE THREAD

**Issue by alinalexandru** [magento/magento2#34964] opened 2022-01-12 15:44 UTC
### Preconditions (*)

1. Have at least one online carrier configured

### Steps to reproduce (*)

1. Create a shipment without selecting the `Create Shipping Label` checkbox. 
2. Try to create a shipping label after the shipment is created.

### Expected result (*)

1. In the pop-up you should be capable to distribute the items to packages

### Actual result (*)

1. Even though the ajax (GetShippingItemsGrid) requests returns the order items, no products are displayed in the pop-up.

The issue seems to be in `Magento/Shipping/view/adminhtml/web/order/packaging.js` in `processPackagePrepare` function, where the quantity is retrieved from input text. When there is a shipment, the input text does not exits. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Nazar65** [comment] 2022-01-12 16:37
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-01-14 05:49
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
Steps performed:
Created Order using UPS Shipping method and money Order payment
Admin - Sales - Orders - View Order - Created Invoice
Created Shipment without selecting Shipping Label checkbox
Shipments - View shipment - Create Shipping Label
Issue: Unable to Add products or unable to save the details. Save button is disabled
![image](https://user-images.githubusercontent.com/60198231/149458275-777eb4a4-670c-44f8-8d32-2a2f4792d6e6.png)

**Comment by alinalexandru** [comment] 2022-06-07 14:32
The bug was introduced in 2.4.2 with this PR https://github.com/magento/magento2/pull/27672

**Comment by glo05363** [comment] 2023-03-14 11:06
@alinalexandru while analysing the issue with given steps we have following observations:

**Preconditions:**
1. created one order using fedex carrier with two prosucts.
2. created shipment without shipment lable.
3. Once shipment is created , generated shipment label .

**Results:**

1. when go to create label after creating shipment , we see the below screen and we are very well allowed to add packages and the products.
<img width="1415" alt="Screenshot 2023-03-13 at 5 08 22 PM" src="https://user-images.githubusercontent.com/87003041/224978783-0589ced6-4d54-4b0b-823a-c57e9e8263b6.png">
<img width="1415" alt="Screenshot 2023-03-13 at 5 08 57 PM" src="https://user-images.githubusercontent.com/87003041/224979642-77836f93-a928-40b3-87f6-8a6f0a5c19c9.png">

in above screen we have added two packages and one product in each package.

2. Moreover while adding these products the quantities though are editable but we do not have the avenue to enter wrong quantity data that does not match the shipment, meaning it looks good with the quantity information as well.
<img width="1415" alt="Screenshot 2023-03-13 at 5 25 06 PM" src="https://user-images.githubusercontent.com/87003041/224979769-10644b88-e817-4586-8d05-88c08f84bcf9.png">

3. The shipment page where we show the quantity information is also looking good with the exact information.
<img width="1391" alt="Screenshot 2023-03-14 at 4 28 56 PM" src="https://user-images.githubusercontent.com/87003041/224980798-151f98c2-160c-45f6-a4a7-c8d9c9489806.png">

As per our analysis everything is working as expected and the proposed changes under [#34968](https://github.com/magento/magento2/pull/34968) would do no effect except adding the quantity as a hidden value. 

Please let us know further on this based on our explanation as what are you trying to achieve as the process looks good.

**Comment by engcom-November** [comment] 2023-03-16 04:33
Hi @alinalexandru ,
As mentioned in the [comment](https://github.com/magento/magento2/issues/34964#issuecomment-1467891899), this issue is no more reproducible on 2.4-develop instance. We are able to create Shipping label for existing shipment. Kindly recheck the issue on Magento 2.4-develop instance and let us know if you are still facing any issues.
Thank you.

**Comment by engcom-November** [comment] 2023-04-03 05:31
Hi @alinalexandru ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2023-04-03 05:31 UTC
Labels: Component: Shipping, Reproduced on 2.4.x, Priority: P1, Progress: done, Issue: needs update, Reported on 2.4.x, Area: Shipping
