### ISSUE TITLE
cannot assisgn theme

### ISSUE THREAD

**Issue by jpcsguru** [magento/magento2#12532] opened 2017-12-04 05:27 UTC
After installing magento 2.2.1 @content>design
you cannot assign the theme rendering home blank

**Comment by magento-engcom-team** [comment] 2017-12-04 07:05
@jpcsguru , thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by jpcsguru** [comment] 2017-12-04 07:13
Normal install 6 times does the same >magento 2.2.1
Precondition
Magento 2.2.1

Steps to reproduce:
1. login backendend
2. content>design>configuration

Actual result:
Cannot assign any theme at all
Cannot select theme

Expected result:
Can assign and select any theme at all

**Comment by magento-engcom-team** [comment] 2017-12-04 08:42
@jpcsguru ,We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation
![design_1](https://user-images.githubusercontent.com/31669971/33543440-baf682ac-d8df-11e7-8a8a-09ce894f0e50.png)
![design_2](https://user-images.githubusercontent.com/31669971/33543451-c073e2ce-d8df-11e7-95ea-8709b9b3ab08.png)

**Comment by jpcsguru** [comment] 2017-12-04 09:37
That is not what we , we see nothing

 

James Purcell

DIRECTOR

 



JPComputer Solutions Pty Ltd

119b edwards Street,Ayr,QLD.4807

Phone 0747836425  

www.jpcomputersolutions.com.au

**Comment by jpcsguru** [comment] 2017-12-04 09:39
we see nothing
![no theme](https://user-images.githubusercontent.com/12822019/33545744-d28dd410-d92a-11e7-9229-8bb4f8be8d08.png)

**Comment by magento-engcom-team** [comment] 2017-12-04 09:50
@jpcsguru, thanks for update.
we were not able to reproduce this issue by following the steps provided. Please check this issue on vanilla installation without any extension if you have

**Comment by jpcsguru** [comment] 2017-12-04 10:13
YOUR SOFTWARE DOIES NOT I SUGGEST YOU FIX IT

**Comment by jpcsguru** [comment] 2017-12-04 10:16
IT DOES NOT WORK FIX IT MY SERVER TEAM HAS SPENT 7 DAYS ON UR DODGY  MAGENTO 2.2.1

**Comment by jpcsguru** [comment] 2017-12-04 10:41
YOUR SOFTWARE IS DODGY

**Comment by ishakhsuvarov** [comment] 2017-12-04 14:05
Closing and locking this thread due to improper communication.
Offensive posts were removed.

**Closed as completed by ishakhsuvarov** 2017-12-04 14:05 UTC
Labels: Progress: needs update, Issue: Clear Description, Issue: Format is not valid
