### ISSUE TITLE
Images in pagebuilder break the aspect ratio!

### ISSUE THREAD

**Issue by cptX** [magento/magento2#37493] opened 2023-05-12 09:42 UTC
### Preconditions and environment

- Magento version: verified in 2.4.5 and 2.4.6

### Steps to reproduce

1. Create a page with pagebuilder
2. Insert a ROW, and TEXT. In TEXT write a line of text and under it insert a wide enough image (eg 1000px wide!!) through the corresponding wysiwyg button "Insert/edit Image". Then write some text under the image too and save.
3. Go to the website **in mobile view** and view the page. It will be shown correctly.
4. Reopen the page for editing,  **change something in the text** and save.
5. Visit the page again **in mobile view** and you will see that the image has broken aspect ratio!

So note that in order to see the bug you have to reedit the page and resave!

Current workaround is to open every image in pagebuilder and delete their dimensions before saving. This has to be done for every image everytime you save the page!!!!

Of course this is really frustrating because every time you want to edit something in the page you have to open every image and delete the saved dimensions! If you don't do this the images will be distorted!

### Expected result

Images should be correctly resized independenty of every screen dimension keeping their aspect ratio.

For example this is how a circle should look like in a mobile phone:
![image](https://github.com/magento/magento2/assets/9040042/2c852a80-562c-4133-9e8f-03ebae82611b)

### Actual result
For example this is how the same circle looks like now in a mobile phone:
Now there is a bug and the way pagebuilder saves or presents the images break their aspect ratio...

![image](https://github.com/magento/magento2/assets/9040042/c8929991-474d-43f5-a0a2-e9e21c2056e2)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-05-15 08:13
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-05-15 13:07
Hi @cptX,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.



**Steps to reproduce**

- Create a page with pagebuilder
- Insert a ROW, and TEXT. In TEXT write a line of text and under it insert a wide enough image (eg 1000px wide!!) through the corresponding wysiwyg button "Insert/edit Image". Then write some text under the image too and save.
- Go to the website in mobile view and view the page. It will be shown correctly.
- Reopen the page for editing, change something in the text and save.
- Visit the page again in mobile view and you will see that the image has broken aspect ratio!

![Magento-Page](https://github.com/magento/magento2/assets/51680745/bcba9bf8-6f44-4cf7-af78-4dafe9087bbc)

**After re-editing the page**


![Magento-Page (1)](https://github.com/magento/magento2/assets/51680745/216ee0a5-6849-45dd-99a6-01dbbec11d60)



<img width="1256" alt="Screenshot 2023-05-15 at 2 51 17 PM" src="https://github.com/magento/magento2/assets/51680745/a66211d1-781b-4021-b973-a2785308d0ca">


<img width="1327" alt="Screenshot 2023-05-15 at 3 05 13 PM" src="https://github.com/magento/magento2/assets/51680745/260b9754-485b-433e-b1ea-a5786af41228">


**After re-editing the page**

<img width="796" alt="Screenshot 2023-05-15 at 3 11 52 PM" src="https://github.com/magento/magento2/assets/51680745/b86f3a1d-5ac6-428f-9e78-1586d1cfc1a0">


After re-editing images are breaking their aspect ratio.

Hence Confirming this issue.

Thanks.

**Comment by rostilos** [comment] 2023-05-16 22:08
@magento I am working on this

**Comment by MrPotatox** [comment] 2023-09-20 10:01
Issue is still active in 2.4.6 - has any fix been found for this yet?

**Comment by engcom-Bravo** [comment] 2023-12-04 05:47
Hi @cptX,

We have checked this issue on Magento 2.4-develop and we found that this issue is not able to reproduce.Please find the attached screenshot for your references.

Before text edit:-

![Screenshot 2023-11-29 at 10 53 15 AM](https://github.com/magento/magento2/assets/51680745/af3806a8-877c-41f2-bceb-3c658ca69227)

After text edit:-

![Screenshot 2023-11-29 at 11 33 19 AM](https://github.com/magento/magento2/assets/51680745/a5d6e8f4-5a58-441d-a420-0d4d1334ccc1)


Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by cptX** [comment] 2023-12-04 08:43
On 15 May, you did tests again and you managed to reproduce it! What did you change now? Please repeat the steps I suggested or the steps you followed on May 15th.

**Comment by engcom-Bravo** [comment] 2023-12-04 09:13
Hi @cptX,

Thanks for your update.

It might be possible issue got fixed in Latest Magento 2.4-develop branch could you please recheck the issue in Latest Magento 2.4-develop instance.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-12-12 11:34
Hi @cptX,

We have retested the latest Magento version 2.4-develop,2.4.6-p4-develop, 2.4.7-beta2-develop, composer version 2.4.6. After updating the text with image found that this issue is no more reproducible. Hence we are closing this issue.Please find the attached screencast for your references.


https://github.com/magento/magento2/assets/51680745/3007790c-fc90-49a4-aefa-aefdbd01c76c



Thanks.

**Closed as completed by engcom-Bravo** 2023-12-12 11:34 UTC
Labels: Reproduced on 2.4.x, Priority: P1, Progress: done, Component: PageBuilder, Issue: needs update, Area: Content, Reported on 2.4.6
