### ISSUE TITLE
[GraphQL] Cart Discounts and Tax amounts are inconsistent

### ISSUE THREAD

**Issue by phtmgt** [magento/magento2#32561] opened 2021-03-21 12:45 UTC
### Summary (*)

1. CartDiscount object returns gross amount (inclusive of taxes).
2. CartTaxItem object returns taxes post discounts.

I think you can see where I am going, but anyway:

Tax: 10%
Discount: 20%

Net amount (as shown - subtotal_excluding_tax): 20
Tax (as shown): 1.6
Discount (as shown): -4.4

Total (of above): **17.2**

Actual total: **17.6**

I know we can go around that by calculating stuff, but this is very messy.

### Proposed solution

1. CartDiscount should return net discount, not gross.
2. CartDiscount should return net **and** gross discount.

I think point 2 is much more versatile.

---

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Hexmage** [comment] 2021-03-25 14:43
I have experienced an issue similar and most likely related to this.

I've set my Tax settings to the following.
![Screenshot from 2021-03-25 15-21-37](https://user-images.githubusercontent.com/22170051/112488487-dc37b980-8d7d-11eb-9fd6-45faae98a623.png)

Make a cart with 1 product in it that costs $100 of which 20% is tax.
So for this cart the subtotal_including_tax = $100 and the subtotal_excluding_tax = $80.
If I add a discount of $50 to this cart the subtotal_with_discount_excluding_tax should be $40. But the actual value of subtotal_with_discount_excluding_tax is $30.

The issue seems to be that certain values on the quote object are not correct. Which I can understand because the correct value is influenced by many configuration settings. But this also means that these quote values should not be returned, but should be calculated when requests as happens everywhere else in Magento.

**Comment by plamenh** [comment] 2021-06-14 08:17
I am just making this comment to prevent the issue from going stale. I think this is quite valid, there should be consistency in amounts.

**Comment by engcom-Lima** [comment] 2021-06-15 12:09
Hi @plamenh, 

I tested on magento 2.4-develop, I can't reproduce the issue.

And also all the required information(**Preconditions, Steps to reproduce, Expected result, Actual result**) is missing to reproduce the issue.
Can you please provide me the reproducible steps and screenshots.

**Comment by engcom-Hotel** [comment] 2021-07-08 08:00
Hi @plamenh,

We are unable to hear from you since more than 14 days, so we are closing this issue. If you still facing the issue, then you can reopen this ticket or create a new ticket.

Thanks

**Closed as completed by engcom-Hotel** 2021-07-08 08:00 UTC
Labels: Triage: Dev.Experience, Issue: needs update
