### ISSUE TITLE
Embedded translation strategy breaks JS files

### ISSUE THREAD

**Issue by timhofman** [magento/magento2#5630] opened 2016-07-14 06:35 UTC
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Set Translation Strategy to embedded
3. Run static deploy for needed locales
4. At least validation.js and dropdown.js suffer from this problem
## Expected result
1. Translated strings in JS in the provided locale, instead to be translated strings like return 
   `$.mage.__("Maximum length of this field must be equal or less than %1 symbols.")
                   .replace('%1', this.attrLength);`
## Actual result
1. `return """.replace('%1', this.attrLength);`
2. Errors on frontend i.e validation.js:1109 Uncaught SyntaxError: Invalid or unexpected token

**Comment by jurgisl** [comment] 2017-06-08 16:40
Here is a bugfix I made for our projects https://github.com/LuxTechnology/mage2_fix_bug5630

It fixes the embedded JS rendering, by checking if there is a translation for a particular string, before replacing it. Original code has a buggy regexp, that matches too broad strings and messes up a JS code in them.

Also this bugfix checks .html knockout templates for JS strings, and replaces those.

There is also a special case, when translations is in the knockout i18n binding. It needs a special treatment, and is replaced with text binding.

It is not PR quality, but works for us and does not require to edit M2 core files.

**Comment by IlnitskiyArtem** [comment] 2017-07-11 11:17
Hi, @timhofman.
I cannot reproduce this issue on the latest Magento develop branches. Please, provide more details to your description of the steps you followed when identifying this issue and your configurations.

**Comment by magento-engcom-team** [comment] 2017-10-23 11:30
@timhofman, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-23 11:30 UTC
Labels: bug report, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid
