### ISSUE TITLE
Triggers for scconnector_google_feed_cl are not removed correctly 

### ISSUE THREAD

**Issue by sippsolutions** [magento/magento2#37801] opened 2023-07-26 12:44 UTC
### Preconditions and environment

- Magento version 2.4.6 (upgraded from Magento 2.3.x)

### Steps to reproduce

Try to save new product images

### Expected result

Images are saved

### Actual result

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xyz.scconnector_google_feed_cl' doesn't exist, query was: DELETE FROM `catalog_product_entity_media_gallery_value` WHERE (value_id = 336222 AND row_id = 92521 AND store_id = 0)

### Additional information

In `\Magento\GoogleShoppingAds\Setup\Recurring` the `scconnector_google_feed` table is removed, but existing triggers are not removed. 
Seems to be other people are having that issue too: https://magento.stackexchange.com/questions/323050/scconnector-google-feed-cl-error-after-product-save-just-upgraded-to-2-3-5-p2

Issue is about the triggers
**trg_catalog_product_entity_media_gallery_value_after_insert**
```
BEGIN
SET @entity_id = (SELECT `entity_id` FROM `catalog_product_entity` WHERE `row_id` = NEW.`row_id`);
INSERT IGNORE INTO `scconnector_google_feed_cl` (`entity_id`) values(@entity_id);
END
```

**trg_catalog_product_entity_media_gallery_value_after_update**
```
BEGIN
SET @entity_id = (SELECT `entity_id` FROM `catalog_product_entity` WHERE `row_id` = NEW.`row_id`);
IF (NOT(NEW.`value_id` <=> OLD.`value_id`) OR NOT(NEW.`store_id` <=> OLD.`store_id`) OR NOT(NEW.`label` <=> OLD.`label`) OR NOT(NEW.`position` <=> OLD.`position`) OR NOT(NEW.`disabled` <=> OLD.`disabled`) OR NOT(NEW.`record_id` <=> OLD.`record_id`) OR NOT(NEW.`row_id` <=> OLD.`row_id`)) THEN INSERT IGNORE INTO `scconnector_google_feed_cl` (`entity_id`) values(@entity_id); END IF;
END
```

**trg_catalog_product_entity_media_gallery_value_after_delete**
```
BEGIN
SET @entity_id = (SELECT `entity_id` FROM `catalog_product_entity` WHERE `row_id` = OLD.`row_id`);
INSERT IGNORE INTO `scconnector_google_feed_cl` (`entity_id`) values(@entity_id);
END
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### Steps to reproduce

1. Install 2.3.7-p4 Magento instance
2. Upgrade instance to 2.4.6 by following [DevDocs](https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html)
3. Trying add new Product images
4. Set mode = enabled for all entries in mview_state (especially scconnector*)
5. Go to backend, and set one random indexer to "on schedule" so the triggers get regenerated
6. Try to save new product images

### Expected result

Product images can be saved

### Actual result

Error occurs

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sippsolutions** [comment] 2023-07-26 12:45
Duplicates #37472, please see https://github.com/magento/magento2/issues/37472#issuecomment-1611368623

**Comment by engcom-Dash** [comment] 2023-07-31 04:30
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-08-03 09:28
Hi @sippsolutions ,

verified the issue in 2.4.6 instance (upgraded from 2.3.5) instance and issue is not reproducible.We can able to save image sucessfully.
Kindly refer the below screenshots:
<img width="1512" alt="Screenshot 2023-08-03 at 2 55 22 PM" src="https://github.com/magento/magento2/assets/60198592/36b89676-06a6-4f9a-90e3-8f8fa3ac30a3">
<img width="1512" alt="Screenshot 2023-08-03 at 2 56 29 PM" src="https://github.com/magento/magento2/assets/60198592/cfb7ada4-1c6e-4a3f-8193-8768335ae7ad">
<img width="1512" alt="Screenshot 2023-08-03 at 2 53 55 PM" src="https://github.com/magento/magento2/assets/60198592/5c4d951d-495b-48de-9d6c-59afb1bfed0a">
Thanks!

**Comment by sippsolutions** [comment] 2023-08-07 11:20
@engcom-Dash
Can you confirm that in Table `mview_state` the value for `status`=`enabled` for `view_id`=`scconnector_google_feed` (if not, please ensure it is and change another indexer's state to "on schedule" in the backend so the triggers get regenerated)?

**Comment by engcom-Dash** [comment] 2023-08-09 13:24
Hi @sippsolutions ,

Verified the issue in latest stable version 2.4.7-beta1 upgraded from 2.3.x and issue is not reproducible.
Kindly refer the screenshots:
<img width="1512" alt="Screenshot 2023-08-09 at 6 52 03 PM" src="https://github.com/magento/magento2/assets/60198592/8779f040-162b-4305-a585-bacc1f177994">
<img width="1512" alt="Screenshot 2023-08-09 at 6 52 41 PM" src="https://github.com/magento/magento2/assets/60198592/911f195d-074e-43cc-bd20-c3d1e8a161fb">

**Comment by sippsolutions** [comment] 2023-08-09 13:26
Hi @engcom-Dash, unfortunately you did not answer my question

**Comment by engcom-Dash** [comment] 2023-08-10 10:58
Hi @sippsolutions ,

As per last [comment](https://github.com/magento/magento2/issues/37801#issuecomment-1667672779) We checked in latest stable version database and the " view_id=scconnector_google_feed" and its not available and issue is not reproducible in latest stable version 2.4.7-beta1,Kindly check [here](https://github.com/magento/magento2/issues/37801#issuecomment-1671321867).
Kindly refer the below screenshot:
<img width="1512" alt="Screenshot 2023-08-10 at 4 08 40 PM" src="https://github.com/magento/magento2/assets/60198592/fdc06a4d-dc0f-4453-88a2-ac62a46541fe">

Let as know if we are missing anything!

Thanks.

**Comment by engcom-Dash** [comment] 2023-08-21 06:07
Hi @sippsolutions ,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2023-08-21 06:07 UTC
Labels: Issue: needs update, Reported on 2.4.6
