### ISSUE TITLE
[2.4.5] setup:static-content:deploy hanging after upgrading

### ISSUE THREAD

**Issue by DuckThom** [magento/magento2#36185] opened 2022-09-23 09:20 UTC
### Preconditions and environment

- Magento 2.4.5
- PHP 8.1

### Steps to reproduce

1. Run `bin/magento setup:static-content:deploy -f -j 4 en_US en_GB nl_NL nl_BE sv_SE`

### Expected result

Execution time is the same as 2.4.4:

```
❯ time php -d memory_limit=-1 bin/magento s:s:d -vvvvvv -f -j 4 en_GB nl_BE nl_NL da_DK sv_SE

[...]Progress bars[...]

Execution time: 45.576536178589

php -d memory_limit=-1 bin/magento s:s:d -vvvvvv -f -j 4 en_GB nl_BE nl_NL    99.31s user 26.01s system 266% cpu 46.942 total
```

### Actual result

Process appears to hang and is using 100% of the CPU core it's running on, any child processes that were created will be marked as Zombie since the parent is stuck and cannot reap them.

In some cases, the execution time of s:s:d is increased from 45 seconds to over 45 minutes.

![image](https://user-images.githubusercontent.com/6512901/191929779-75ef8ed0-3c34-4bdf-8729-e54eb325fd83.png)

As seen in the screenshot, the process is already running for over 10 minutes while normally this would take 45 seconds. The 2 sub-processes are marked with Z (zombie) as the main thread is stuck in a loop in `\Magento\Deploy\Package\Processor\PreProcessor\Less::inParentFiles`.

### Additional information

Reverting the change made in https://github.com/magento/magento2/commit/4514e651f5e793cbee6123487b72aafa119bd1fe will restore the static content deploy quick strategy performance and reduce the execution time back to normal levels.

It seems that every iteration through `\Magento\Deploy\Package\Processor\PreProcessor\Less::inParentFiles` will increase the deployment time until it reaches a point where it gets completely stuck in the loop.

As it stands, this is blocking our server deployments and a revert-patch is needed to make them succeed.

```
diff --git a/htdocs/vendor/magento/module-deploy/Package/Processor/PreProcessor/Less.php b/htdocs/vendor/magento/module-deploy/Package/Processor/PreProcessor/Less.php
--- a/htdocs/vendor/magento/module-deploy/Package/Processor/PreProcessor/Less.php	
+++ b/htdocs/vendor/magento/module-deploy/Package/Processor/PreProcessor/Less.php
@@ -154,9 +154,7 @@
                 return true;
             } else {
                 foreach ($map[$parentFile] as $pFile) {
-                    if ($this->inParentFiles($fileName, $pFile, $map)) {
-                        return true;
-                    }
+                    return $this->inParentFiles($fileName, $pFile, $map);
                 }
             }
         }

```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Anve94** [comment] 2022-09-23 09:29
+1
I can confirm severe performance degradation in static content deploy on three independent projects, all using a quick deploy strategy using multiple jobs in parallel. All these projects are being upgraded to 2.4.5 and this issue started occurring when deploying our upgrade branch to test and acceptance environments. Production is on 2.4.3-p2 for all 3 projects and is unaffected by performance degradation.

**Comment by engcom-Delta** [comment] 2022-09-28 03:48
Hi @DuckThom ,

Thank you for reporting and collaboration

We have tried to reproduce this issue but issue is not reproducible .

Precondition:
• Magento version : 2.4.5-develop
• PHP 8.1

We have followed below step

1. Run bin/magento setup:static-content:deploy -f -j 4 en_US en_GB nl_NL nl_BE sv_SE in magento2.4.4
<img width="1120" alt="Screenshot 2022-09-28 at 8 57 19 AM" src="https://user-images.githubusercontent.com/51681379/192682406-fce7f639-d9f0-4c08-b14b-5d418348a5a0.png">

2.Run bin/magento setup:static-content:deploy -f -j 4 en_US en_GB nl_NL nl_BE sv_SE in magento2.4.5
<img width="1129" alt="Screenshot 2022-09-28 at 8 57 39 AM" src="https://user-images.githubusercontent.com/51681379/192682596-142dfcff-d2f4-4b94-ae8e-f37024bcf291.png">

Please let us know if we are missing any steps here.

Thanks

**Comment by engcom-Delta** [comment] 2022-09-28 05:24
Hi @DuckThom,

Thank you for reporting and collaboration.

We have tried to reproduce this issue but issue is not reproducible .

Precondition:
• Magento version : 2.4.5-develop
• PHP 8.1

We have followed below steps
1.Ran bin/magento setup:static-content:deploy -f -j 4 en_US en_GB nl_NL nl_BE sv_SE in magento 2.4.4

<img width="1120" alt="Screenshot 2022-09-28 at 8 57 19 AM" src="https://user-images.githubusercontent.com/51681379/192687289-d55534a3-760d-4edc-86c9-6509bf7d6b97.png">

2.After upgrading Magento2.4.4 to Magento2.4.5 When we ran the bin/magento setup:static-content:deploy -f -j 4 en_US en_GB nl_NL nl_BE sv_SE we are getting as below ,please have a look .

<img width="1238" alt="Screenshot 2022-09-28 at 9 51 36 AM" src="https://user-images.githubusercontent.com/51681379/192687580-a3d67126-4d04-481a-b512-d30457998472.png">

3. we are not able to see process appears to hang 
<img width="869" alt="Screenshot 2022-09-28 at 10 46 58 AM" src="https://user-images.githubusercontent.com/51681379/192693699-bc8b2621-a63a-433f-b82d-a88a5fb592da.png">


Please let us know if we are missing any steps here.

Thanks

**Comment by hostep** [comment] 2022-09-28 05:58
I've just tested it out over here on a project where we are upgrading from Magento 2.3.7-p4 to Magento 2.4.5 and can confirm that the same problem is happening. When I switch from 4 jobs to 1 job, it's no longer hanging, but it takes a lot longer to execute then normal.
With 4 jobs, it just seems stuck on the line for `frontend/Magento/luma/sv_SE`:
<img width="888" alt="Screenshot 2022-09-28 at 07 55 11" src="https://user-images.githubusercontent.com/85479/192699220-9e889f0e-0596-4194-afac-5754a41e1a25.png">
We have a custom theme that has parent: `Magento/blank`

@engcom-Delta: do you have the php extension `pcntl` installed and active (you can check with `php -m | grep pcntl`)? Because you'll need it before the parallel jobs will start working. Also make sure to always execute the following between test runs: `rm -R var/view_preprocessed/* pub/static/frontend/*`.

**Comment by DuckThom** [comment] 2022-09-28 11:23
@engcom-Delta I've done some testing on clean installations and the slowdown effect is not very noticeable, however it is still there. Here are some timings taken from my testing:

### Magento Open Source

<details><summary>2.4.4</summary>
<p>

```
❯ rm -rf var/view_preprocessed pub/static/*  && php -d memory_limit=-1 bin/magento s:s:d -f -j 4 en_GB nl_BE nl_NL da_DK sv_SE

Deploy using quick strategy
frontend/Magento/blank/en_GB            2174/2174           ============================ 100%   < 1 sec
adminhtml/Magento/backend/en_GB         2911/2911           ============================ 100%   < 1 sec
frontend/Magento/blank/nl_BE            2174/2174           ============================ 100%   < 1 sec
frontend/Magento/blank/nl_NL            2174/2174           ============================ 100%   < 1 sec
frontend/Magento/blank/da_DK            2174/2174           ============================ 100%   2 secs
frontend/Magento/blank/sv_SE            2174/2174           ============================ 100%   2 secs
adminhtml/Magento/backend/nl_BE         2911/2911           ============================ 100%   2 secs
adminhtml/Magento/backend/nl_NL         2911/2911           ============================ 100%   1 sec
adminhtml/Magento/backend/da_DK         2911/2911           ============================ 100%   0
adminhtml/Magento/backend/sv_SE         2911/2911           ============================ 100%   0
frontend/Magento/luma/en_GB             2190/2190           ============================ 100%   0
frontend/Magento/luma/nl_BE             2190/2190           ============================ 100%   3 secs
frontend/Magento/luma/nl_NL             2190/2190           ============================ 100%   1 sec
frontend/Magento/luma/da_DK             2190/2190           ============================ 100%   1 sec
frontend/Magento/luma/sv_SE             2190/2190           ============================ 100%   < 1 sec

Execution time: 19.21523809433
```

</p>
</details>

<details><summary>2.4.5</summary>
<p>

```
❯ rm -rf var/view_preprocessed pub/static/*  && php -d memory_limit=-1 bin/magento s:s:d -f -j 4 en_GB nl_BE nl_NL da_DK sv_SE

Deploy using quick strategy
frontend/Magento/blank/en_GB            2181/2181           ============================ 100%   < 1 sec
adminhtml/Magento/backend/en_GB         2921/2921           ============================ 100%   < 1 sec
frontend/Magento/blank/nl_BE            2181/2181           ============================ 100%   < 1 sec
frontend/Magento/blank/nl_NL            2181/2181           ============================ 100%   < 1 sec
frontend/Magento/blank/da_DK            2181/2181           ============================ 100%   2 secs
frontend/Magento/blank/sv_SE            2181/2181           ============================ 100%   2 secs
adminhtml/Magento/backend/nl_BE         2921/2921           ============================ 100%   2 secs
adminhtml/Magento/backend/nl_NL         2921/2921           ============================ 100%   1 sec
adminhtml/Magento/backend/da_DK         2921/2921           ============================ 100%   0
adminhtml/Magento/backend/sv_SE         2921/2921           ============================ 100%   0
frontend/Magento/luma/en_GB             2197/2197           ============================ 100%   0
frontend/Magento/luma/nl_BE             2197/2197           ============================ 100%   0
frontend/Magento/luma/nl_NL             2197/2197           ============================ 100%   3 secs
frontend/Magento/luma/da_DK             2197/2197           ============================ 100%   3 secs
frontend/Magento/luma/sv_SE             2197/2197           ============================ 100%   2 secs

Execution time: 21.784950017929
```

</p>
</details>

As you can see, not a large difference. Things get more interesting though when we switch to a clean enterprise installation (since it has an extra theme in 2.4.5, Magento/spectrum)

### Magento Commerce

<details><summary>2.4.4</summary>
<p>

```
❯ rm -rf var/view_preprocessed pub/static/*  && php -d memory_limit=-1 bin/magento s:s:d -f -j 4 en_GB nl_BE nl_NL da_DK sv_SE

Deploy using quick strategy
frontend/Magento/blank/en_GB            2303/2303           ============================ 100%   < 1 sec
adminhtml/Magento/backend/en_GB         3000/3000           ============================ 100%   < 1 sec
frontend/Magento/blank/nl_BE            2303/2303           ============================ 100%   < 1 sec
frontend/Magento/blank/nl_NL            2303/2303           ============================ 100%   < 1 sec
frontend/Magento/blank/da_DK            2303/2303           ============================ 100%   2 secs
frontend/Magento/blank/sv_SE            2303/2303           ============================ 100%   2 secs
adminhtml/Magento/backend/nl_BE         3000/3000           ============================ 100%   2 secs
adminhtml/Magento/backend/nl_NL         3000/3000           ============================ 100%   1 sec
adminhtml/Magento/backend/da_DK         3000/3000           ============================ 100%   0
adminhtml/Magento/backend/sv_SE         3000/3000           ============================ 100%   0
frontend/Magento/luma/en_GB             2320/2320           ============================ 100%   3 secs
frontend/Magento/luma/nl_BE             2320/2320           ============================ 100%   3 secs
frontend/Magento/luma/nl_NL             2320/2320           ============================ 100%   < 1 sec
frontend/Magento/luma/da_DK             2320/2320           ============================ 100%   < 1 sec
frontend/Magento/luma/sv_SE             2320/2320           ============================ 100%   0

Execution time: 20.095071077347
```

</p>
</details>

<details><summary>2.4.5</summary>
<p>

```
❯ rm -rf var/view_preprocessed pub/static/*  && php -d memory_limit=-1 bin/magento s:s:d -f -j 4 en_GB nl_BE nl_NL da_DK sv_SE

Deploy using quick strategy
frontend/Magento/blank/en_GB            2318/2318           ============================ 100%   < 1 sec
adminhtml/Magento/backend/en_GB         3012/3012           ============================ 100%   < 1 sec
frontend/Magento/blank/nl_BE            2318/2318           ============================ 100%   < 1 sec
frontend/Magento/blank/nl_NL            2318/2318           ============================ 100%   < 1 sec
frontend/Magento/blank/da_DK            2318/2318           ============================ 100%   2 secs
frontend/Magento/blank/sv_SE            2318/2318           ============================ 100%   2 secs
adminhtml/Magento/backend/nl_BE         3012/3012           ============================ 100%   2 secs
adminhtml/Magento/backend/nl_NL         3012/3012           ============================ 100%   1 sec
adminhtml/Magento/backend/da_DK         3012/3012           ============================ 100%   0
adminhtml/Magento/backend/sv_SE         3012/3012           ============================ 100%   0
frontend/Magento/luma/en_GB             2335/2335           ============================ 100%   0
adminhtml/Magento/spectrum/en_GB        3012/3012           ============================ 100%   0
frontend/Magento/luma/nl_BE             2335/2335           ============================ 100%   0
frontend/Magento/luma/nl_NL             2335/2335           ============================ 100%   3 secs
frontend/Magento/luma/da_DK             2335/2335           ============================ 100%   2 secs
frontend/Magento/luma/sv_SE             2335/2335           ============================ 100%   0
adminhtml/Magento/spectrum/nl_BE        3012/3012           ============================ 100%   0
adminhtml/Magento/spectrum/nl_NL        3012/3012           ============================ 100%   0
adminhtml/Magento/spectrum/da_DK        3012/3012           ============================ 100%   0
adminhtml/Magento/spectrum/sv_SE        3012/3012           ============================ 100%   0

Execution time: 80.963579893112
```

</p>
</details>

As you can see, the execution time increased from 20s to 80s, a 300% increase in compilation time. Now, an increase is obviously expected when a new theme is added, however, a 3x increase seems excessive.

Using this information, I decided to grab a random theme from the marketplace to see how the times would change in Magento Open Source since virtually _all_ Magento sites are using one or more custom themes.


### Magento Open Source

<details><summary>2.4.4</summary>
<p>

```
❯ rm -rf var/view_preprocessed pub/static/\*  && php -d memory_limit=-1 bin/magento s:s:d -f -j 4 en_GB nl_BE nl_NL da_DK sv_SE

Deploy using quick strategy
frontend/Magento/blank/en_GB            2210/2210           ============================ 100%   < 1 sec
adminhtml/Magento/backend/en_GB         2971/2971           ============================ 100%   < 1 sec
frontend/Magento/blank/nl_BE            2210/2210           ============================ 100%   < 1 sec
frontend/Magento/blank/nl_NL            2210/2210           ============================ 100%   < 1 sec
frontend/Magento/blank/da_DK            2210/2210           ============================ 100%   0
frontend/Magento/blank/sv_SE            2210/2210           ============================ 100%   0
adminhtml/Magento/backend/nl_BE         2971/2971           ============================ 100%   0
adminhtml/Magento/backend/nl_NL         2971/2971           ============================ 100%   0
adminhtml/Magento/backend/da_DK         2971/2971           ============================ 100%   0
adminhtml/Magento/backend/sv_SE         2971/2971           ============================ 100%   0
frontend/Magento/luma/en_GB             2226/2226           ============================ 100%   0
frontend/Magento/luma/nl_BE             2226/2226           ============================ 100%   0
frontend/Magento/luma/nl_NL             2226/2226           ============================ 100%   0
frontend/Magento/luma/da_DK             2226/2226           ============================ 100%   0
frontend/Magento/luma/sv_SE             2226/2226           ============================ 100%   0
frontend/Swissup/absolute/en_GB         2261/2261           ============================ 100%   0
frontend/Swissup/absolute/nl_BE         2261/2261           ============================ 100%   0
frontend/Swissup/absolute/nl_NL         2261/2261           ============================ 100%   0
frontend/Swissup/absolute/da_DK         2261/2261           ============================ 100%   0
frontend/Swissup/absolute/sv_SE         2261/2261           ============================ 100%   0

Execution time: 7.2641670703888
```

</p>
</details>

<details><summary>2.4.5</summary>
<p>

```
❯ rm -rf var/view_preprocessed pub/static/*  && php -d memory_limit=-1 bin/magento s:s:d -f -j 4 en_GB nl_BE nl_NL da_DK sv_SE

Deploy using quick strategy
frontend/Magento/blank/en_GB            2217/2217           ============================ 100%   < 1 sec
adminhtml/Magento/backend/en_GB         2981/2981           ============================ 100%   < 1 sec
frontend/Magento/blank/nl_BE            2217/2217           ============================ 100%   < 1 sec
frontend/Magento/blank/nl_NL            2217/2217           ============================ 100%   < 1 sec
frontend/Magento/blank/da_DK            2217/2217           ============================ 100%   2 secs
frontend/Magento/blank/sv_SE            2217/2217           ============================ 100%   2 secs
adminhtml/Magento/backend/nl_BE         2981/2981           ============================ 100%   2 secs
adminhtml/Magento/backend/nl_NL         2981/2981           ============================ 100%   1 sec
adminhtml/Magento/backend/da_DK         2981/2981           ============================ 100%   0
adminhtml/Magento/backend/sv_SE         2981/2981           ============================ 100%   0
frontend/Magento/luma/en_GB             2233/2233           ============================ 100%   0
frontend/Magento/luma/nl_BE             2233/2233           ============================ 100%   0
frontend/Magento/luma/nl_NL             2233/2233           ============================ 100%   0
frontend/Magento/luma/da_DK             2233/2233           ============================ 100%   0
frontend/Magento/luma/sv_SE             2233/2233           ============================ 100%   0
frontend/Swissup/absolute/en_GB         2268/2268           ============================ 100%   4 secs
frontend/Swissup/absolute/nl_BE         2268/2268           ============================ 100%   0
frontend/Swissup/absolute/nl_NL         2268/2268           ============================ 100%   0
frontend/Swissup/absolute/da_DK         2268/2268           ============================ 100%   0
frontend/Swissup/absolute/sv_SE         2268/2268           ============================ 100%   0

Execution time: 93.378259181976
```

</p>
</details>

And this time, the execution time also increased dramatically on the Open Source installation. Where it was 7s in 2.4.4, it increased massively to 93s in 2.4.5 using only a base installation with 1 custom theme and no additional code or changes. Combine this with the added admin theme in Commerce and the process execution time will increase exponentially.

I hope this will be of use to you.

**Comment by engcom-Delta** [comment] 2022-10-04 17:02
Hi @hostep @DuckThom,

Thank you for the response.

:heavy_check_mark: Issue confirmed

We have checked this issue in magento 2.4.4 to magento 2.4.5 and magento 2.4 - develop.

**Description:**


**Pre-requisite:**
1. Magento 2.4.5
2. PHP 8.1

**Steps to reproduce:**

1. Install Magento 2.4.4 instance and execute rm -R var/view_preprocessed/* pub/static/* && time php -d memory_limit=-1 bin/magento setup:static-content:deploy -f -j 4 en_US en_GB nl_NL nl_BE sv_SE command
2. Upgrade Magento 2.4.4 to magento 2.4.5 and execute rm -R var/view_preprocessed/* pub/static/* && time php -d memory_limit=-1 bin/magento setup:static-content:deploy -f -j 4 en_US en_GB nl_NL nl_BE sv_SE command
3. Compare both execution time 

**Expected result:**
   Execution time is same as Magento 2.4.4

**Actual result:**
   Execution time is more than magento 2.4.4

**Screenshots:**
1. In Magento 2.4.4
<img width="1078" alt="Screenshot 2022-10-04 at 10 09 23 PM" src="https://user-images.githubusercontent.com/51681379/193881374-ef938534-3afc-4852-9cb9-81546b646e04.png">
2. Upgrade Magento 2.4.4 to Magento 2.4.5
<img width="917" alt="Screenshot 2022-10-04 at 10 09 06 PM" src="https://user-images.githubusercontent.com/51681379/193881138-fcbd993f-000e-454d-aa7a-7982a6abfdd7.png">


Hence,confirming the issue.

**Comment by DuckThom** [comment] 2022-10-05 09:27
It looks like this might be fixed by https://github.com/magento/magento2/commit/12a9eacaf57baf1dbd71b22cbd9ada32f3ffa479

I just applied these changes to my 2.4.5 Open Source testing installation I used above (where the compilation time was 93s) and it's now back to a more normal 26s

Unfortunately, it doesn't look like this will be released with 2.4.5-p1 as I just installed the pre-release in my Commerce testing installation and this commit is not in there.

It can, however, be installed as a patch by applying the changes from these commits (in order):

1. https://github.com/magento/magento2/commit/8635f6b3ab2697a4dc1904dc16adc9c37518dcdf
2. https://github.com/magento/magento2/commit/571ad3019cac39aa2822e20108516da5d20b84f5
3. https://github.com/magento/magento2/commit/79ef3d9c087d61ad31124abdbee5326a42299681
4. https://github.com/magento/magento2/commit/12a9eacaf57baf1dbd71b22cbd9ada32f3ffa479

### Patch

<details><summary>View</summary>
<p>


```
From 8635f6b3ab2697a4dc1904dc16adc9c37518dcdf Mon Sep 17 00:00:00 2001
From: Roman Flowers <flowers@adobe.com>
Date: Tue, 19 Jul 2022 13:25:36 -0500
Subject: [PATCH] ACP2E-923: Compact strategy causes an invalid reference to an
 external domain when running SCD

---
 .../Package/Processor/PreProcessor/Css.php    | 23 +++++++++++++++----
 1 file changed, 19 insertions(+), 4 deletions(-)

diff --git a/vendor/magento/module-deploy/Package/Processor/PreProcessor/Css.php b/vendor/magento/module-deploy/Package/Processor/PreProcessor/Css.php
index 152c95f86552c..c65e6a4e9f78d 100644
--- a/vendor/magento/module-deploy/Package/Processor/PreProcessor/Css.php
+++ b/vendor/magento/module-deploy/Package/Processor/PreProcessor/Css.php
@@ -120,6 +120,19 @@ private function hasOverrides(PackageFile $parentFile, Package $package)
         return false;
     }
 
+    /**
+     * See if given path is local or remote URL
+     *
+     * @param string $path
+     * @return bool
+     */
+    private function isLocal(string $path): bool {
+        $pattern = '{^(file://(?!//)|/(?!/)|/?[a-z]:[\\\\/]|\.\.[\\\\/]|[a-z0-9_.-]+[\\\\/])}i';
+        $result = preg_match($pattern, $path);
+
+        return (bool) $result;
+    }
+
     /**
      * Build map file
      *
@@ -138,10 +151,12 @@ private function buildMap($packagePath, $filePath, $fullPath)
             $content = $this->staticDir->readFile($this->minification->addMinifiedSign($fullPath));
 
             $callback = function ($matchContent) use ($packagePath, $filePath, &$imports) {
-                $importRelPath = $this->normalize(pathinfo($filePath, PATHINFO_DIRNAME) . '/' . $matchContent['path']);
-                $imports[$importRelPath] = $this->normalize(
-                    $packagePath . '/' . pathinfo($filePath, PATHINFO_DIRNAME) . '/' . $matchContent['path']
-                );
+                if ($this->isLocal($matchContent['path'])) {
+                    $importRelPath = $this->normalize(pathinfo($filePath, PATHINFO_DIRNAME) . '/' . $matchContent['path']);
+                    $imports[$importRelPath] = $this->normalize(
+                        $packagePath . '/' . pathinfo($filePath, PATHINFO_DIRNAME) . '/' . $matchContent['path']
+                    );
+                }
             };
             preg_replace_callback(Import::REPLACE_PATTERN, $callback, $content);
 


From 571ad3019cac39aa2822e20108516da5d20b84f5 Mon Sep 17 00:00:00 2001
From: Roman Flowers <flowers@adobe.com>
Date: Wed, 20 Jul 2022 07:34:52 -0500
Subject: [PATCH] ACP2E-923: Compact strategy causes an invalid reference to an
 external domain when running SCD

---
 .../Magento/Deploy/Package/Processor/PreProcessor/Css.php  | 7 +++++--
 1 file changed, 5 insertions(+), 2 deletions(-)

diff --git a/vendor/magento/module-deploy/Package/Processor/PreProcessor/Css.php b/vendor/magento/module-deploy/Package/Processor/PreProcessor/Css.php
index c65e6a4e9f78d..cd05109ce6300 100644
--- a/vendor/magento/module-deploy/Package/Processor/PreProcessor/Css.php
+++ b/vendor/magento/module-deploy/Package/Processor/PreProcessor/Css.php
@@ -126,7 +126,8 @@ private function hasOverrides(PackageFile $parentFile, Package $package)
      * @param string $path
      * @return bool
      */
-    private function isLocal(string $path): bool {
+    private function isLocal(string $path): bool
+    {
         $pattern = '{^(file://(?!//)|/(?!/)|/?[a-z]:[\\\\/]|\.\.[\\\\/]|[a-z0-9_.-]+[\\\\/])}i';
         $result = preg_match($pattern, $path);
 
@@ -152,7 +153,9 @@ private function buildMap($packagePath, $filePath, $fullPath)
 
             $callback = function ($matchContent) use ($packagePath, $filePath, &$imports) {
                 if ($this->isLocal($matchContent['path'])) {
-                    $importRelPath = $this->normalize(pathinfo($filePath, PATHINFO_DIRNAME) . '/' . $matchContent['path']);
+                    $importRelPath = $this->normalize(
+                        pathinfo($filePath, PATHINFO_DIRNAME) . '/' . $matchContent['path']
+                    );
                     $imports[$importRelPath] = $this->normalize(
                         $packagePath . '/' . pathinfo($filePath, PATHINFO_DIRNAME) . '/' . $matchContent['path']
                     );


From 79ef3d9c087d61ad31124abdbee5326a42299681 Mon Sep 17 00:00:00 2001
From: Roman Flowers <flowers@adobe.com>
Date: Wed, 20 Jul 2022 12:44:23 -0500
Subject: [PATCH] ACP2E-923: Compact strategy causes an invalid reference to an
 external domain when running SCD

---
 vendor/magento/module-deploy/Package/Processor/PreProcessor/Css.php | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/vendor/magento/module-deploy/Package/Processor/PreProcessor/Css.php b/vendor/magento/module-deploy/Package/Processor/PreProcessor/Css.php
index cd05109ce6300..8799cb62272c3 100644
--- a/vendor/magento/module-deploy/Package/Processor/PreProcessor/Css.php
+++ b/vendor/magento/module-deploy/Package/Processor/PreProcessor/Css.php
@@ -131,7 +131,7 @@ private function isLocal(string $path): bool
         $pattern = '{^(file://(?!//)|/(?!/)|/?[a-z]:[\\\\/]|\.\.[\\\\/]|[a-z0-9_.-]+[\\\\/])}i';
         $result = preg_match($pattern, $path);
 
-        return (bool) $result;
+        return is_int($result) ? (bool) $result : true;
     }
 
     /**


From 12a9eacaf57baf1dbd71b22cbd9ada32f3ffa479 Mon Sep 17 00:00:00 2001
From: Oleksandr Iegorov <oiegorov@adobe.com>
Date: Fri, 9 Sep 2022 09:31:20 -0500
Subject: [PATCH] ACP2E-1168: Static content deployment timed out or failed

---
 vendor/magento/module-deploy/Collector/Collector.php        |  3 +++
 .../Deploy/Package/Processor/PreProcessor/Css.php      |  7 ++++++-
 .../Deploy/Package/Processor/PreProcessor/Less.php     | 10 ++++++++++
 .../testsuite/Magento/Deploy/DeployTest.php            |  2 +-
 4 files changed, 20 insertions(+), 2 deletions(-)

diff --git a/vendor/magento/module-deploy/Collector/Collector.php b/vendor/magento/module-deploy/Collector/Collector.php
index b09001a7ac04c..441d165f6792a 100644
--- a/vendor/magento/module-deploy/Collector/Collector.php
+++ b/vendor/magento/module-deploy/Collector/Collector.php
@@ -93,6 +93,9 @@ public function collect()
                 if ($file->getModule() && !$this->moduleManager->isEnabled($file->getModule())) {
                     continue;
                 }
+                if (!$file->getFileName()) {
+                    continue;
+                }
                 $file->setDeployedFileName($this->fileNameResolver->resolve($file->getFileName()));
                 $params = $this->getParams($file);
                 $packagePath = "{$params['area']}/{$params['theme']}/{$params['locale']}";
diff --git a/vendor/magento/module-deploy/Package/Processor/PreProcessor/Css.php b/vendor/magento/module-deploy/Package/Processor/PreProcessor/Css.php
index 8799cb62272c3..6fc9c05eb3527 100644
--- a/vendor/magento/module-deploy/Package/Processor/PreProcessor/Css.php
+++ b/vendor/magento/module-deploy/Package/Processor/PreProcessor/Css.php
@@ -149,7 +149,12 @@ private function buildMap($packagePath, $filePath, $fullPath)
             $imports = [];
             $this->map[$fullPath] = [];
 
-            $content = $this->staticDir->readFile($this->minification->addMinifiedSign($fullPath));
+            $tmpFilename = $this->minification->addMinifiedSign($fullPath);
+            if ($this->staticDir->isReadable($tmpFilename)) {
+                $content = $this->staticDir->readFile($tmpFilename);
+            } else {
+                $content = '';
+            }
 
             $callback = function ($matchContent) use ($packagePath, $filePath, &$imports) {
                 if ($this->isLocal($matchContent['path'])) {
diff --git a/vendor/magento/module-deploy/Package/Processor/PreProcessor/Less.php b/vendor/magento/module-deploy/Package/Processor/PreProcessor/Less.php
index dbda66cc948f1..f4339b40f5be8 100644
--- a/vendor/magento/module-deploy/Package/Processor/PreProcessor/Less.php
+++ b/vendor/magento/module-deploy/Package/Processor/PreProcessor/Less.php
@@ -59,6 +59,11 @@ class Less implements ProcessorInterface
      */
     private $map = [];
 
+    /**
+     * @var array
+     */
+    private $pFileCache = [];
+
     /**
      * Less constructor
      *
@@ -132,6 +137,7 @@ private function hasOverrides(PackageFile $parentFile, Package $package)
         $currentPackageFiles = array_merge($package->getFilesByType('less'), $package->getFilesByType('css'));
 
         foreach ($currentPackageFiles as $file) {
+            $this->pFileCache = [];
             if ($this->inParentFiles($file->getDeployedFileName(), $parentFile->getFileName(), $map)) {
                 return true;
             }
@@ -154,6 +160,10 @@ private function inParentFiles($fileName, $parentFile, $map)
                 return true;
             } else {
                 foreach ($map[$parentFile] as $pFile) {
+                    if (in_array($pFile, $this->pFileCache)) {
+                        continue;
+                    }
+                    $this->pFileCache[] = $pFile;
                     if ($this->inParentFiles($fileName, $pFile, $map)) {
                         return true;
                     }
diff --git a/dev/tests/integration/testsuite/Magento/Deploy/DeployTest.php b/dev/tests/integration/testsuite/Magento/Deploy/DeployTest.php
index 72c722e139259..48f82fdcee184 100644
--- a/dev/tests/integration/testsuite/Magento/Deploy/DeployTest.php
+++ b/dev/tests/integration/testsuite/Magento/Deploy/DeployTest.php
@@ -240,7 +240,7 @@ private function assertCssFromChildTheme($actualRootCssContent)
     private function assertBundleSize($theme)
     {
         $expectedSize = $this->bundleConfig->getBundleFileMaxSize('frontend', $theme);
-        $expectedSize *= 1.15;
+        $expectedSize *= 1.2;
 
         $iterator = $this->getDirectoryIterator("frontend/{$theme}/en_US/js/bundle");
         /** @var \SplFileInfo $file */

```

</p></details>

Applying the changes in this patch to the Commerce 2.4.5 and 2.4.5-p1 installations drops the compilation time back from 80s to 28s

**Comment by engcom-Delta** [comment] 2022-10-10 07:35
Hi @hostep @DuckThom,

Thank you for the response.

✔️ Issue confirmed

Issue got reproduce,After upgrading magento2.4.4 to magento 2.4.5.

**Description:**

After upgrading magento 2.4.4 to magento 2.4.5, while running setup:static-content:deploy command It is taking more time than magento 2.4.4 

**Pre-requisite:**

1. Magento 2.4.5
2. PHP 8.1

**Steps to reproduce:**

1. Install Magento 2.4.4 instance and execute rm -R var/view_preprocessed/* pub/static/* && time php -d memory_limit=-1 bin/magento setup:static-content:deploy -f -j 4 en_US en_GB nl_NL nl_BE sv_SE command.

2. Upgrade Magento 2.4.4 to magento 2.4.5 and execute rm -R var/view_preprocessed/* pub/static/* && time php -d memory_limit=-1 bin/magento setup:static-content:deploy -f -j 4 en_US en_GB nl_NL nl_BE sv_SE command.

3. Compare both execution time.


**Expected result:**
Execution time is same as Magento 2.4.4

**Actual result:**
Execution time is more than magento 2.4.4

**Screenshots:**

1.In Magento 2.4.4

<img width="917" alt="Screenshot 2022-10-04 at 10 09 06 PM" src="https://user-images.githubusercontent.com/51681379/194813332-85a35277-97a1-4279-a40c-ee9dbf2e365a.png">

2. Upgrade Magento 2.4.4 to Magento 2.4.5

<img width="1078" alt="Screenshot 2022-10-04 at 10 09 23 PM" src="https://user-images.githubusercontent.com/51681379/194813210-66b288fa-86c7-4af6-94d2-19d5fc5875d2.png">

3. Magento 2.4.4 took  42s and Magento 2.4.5 took  51s .

Hence,confirming the issue.

Thanks

**Comment by hostep** [comment] 2022-10-10 07:38
@engcom-Delta: can you verify it again on the latest 2.4-develop branch?

Like @DuckThom said, it sounds like it already got fixed in [ACP2E-1168: Static content deployment timed out or failed](https://github.com/magento/magento2/search?q=ACP2E-1168&type=commits)

**Closed as completed** 2022-10-11 13:39 UTC
Labels: Triage: Dev.Experience, Reported on 2.4.5
