### ISSUE TITLE
admin layout broken 

### ISSUE THREAD

**Issue by chazzs** [magento/magento2#36057] opened 2022-08-30 20:25 UTC
### Preconditions and environment

-  Magento ver. 2.4.3-p2

### Steps to reproduce

I am not clear how to reproduce this, it just started happening and is happening more and more lately.

1. login to the admin/backend.

### Expected result

I expect the admin layout to be consistent; not having the content appear below the side menubar.

### Actual result

admin layout broken and page content appears below the sidebar/menu.

![Screenshot_2022-08-30_14-14-03](https://user-images.githubusercontent.com/1693121/187534837-e9d00241-bf89-4372-a172-a5dbb121da21.png)

### Additional information

I am sorry there is not much information here, This just started happening.  I have made no customizations(aside from color of the sidebar 3 years ago) to the admin interface styles so I am unsure as to why this is all of the sudden happening.  The results are inconsistent as well.  If i do a hard reload(shift + reload) the page loads fine, but if i just hit page reload button the layout breaks and I have to do a hard reload again to fix the layout.  This will also happen when browser debug tools are open and network cache is **not** "disabled". The layout will not break when network cache is "disabled"

There are no errors in the debug tools console.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by chazzs** [comment] 2022-08-30 20:33
@magento give me 2.4.3-p2-develop instance

**Comment by chazzs** [comment] 2022-08-30 20:34
@magento give me 2.4-develop instance

**Comment by hostep** [comment] 2022-08-31 11:54
It's been happening to me as well on various Magento versions since a week or 2-3. It only seems to happen on Google Chrome, not on Firefox.
It only happens every so often, not all the time.

I _think_ it's caused by a Google Chrome update from version 103 to 104, but can't say with certainty.
Maybe somebody should report this to the Google Chrome team? Not sure if a bug in Chrome itself, or a bug in the css/javascript of Magento that's causing an undefined behavior in certain browsers?

**Comment by chazzs** [comment] 2022-08-31 21:07
Sometimes the layout fixes itself as soon as you scroll

**Comment by n2diving-dgx** [comment] 2022-09-01 06:00
Can confirm it's happening with the admin pages of M2.4.5 + Php8.1 to everyone in the office using Win11/Chrome Version 105.0.5195.54 (Official Build) (64-bit).  Really annoying, most often a browser page scroll or a page refresh corrects the display, but occasionally not.

**Comment by engcom-Dash** [comment] 2022-09-01 09:16
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-09-01 09:28
Hi @chazzs ,
 We are trying to reproduce the issue in 2.4-develop branch...But we are not able to reproduce the issue.
we are getting expected result.

Here i attached screenshot for your reference:
![Screenshot from 2022-09-01 14-54-15](https://user-images.githubusercontent.com/60198592/187880842-70eee25b-96ee-4f97-a0d6-f751848edcdb.png)

Steps:
1. Install magento instance
2. Open admin Panel
3. Contents of Admin Panel displaying properly

Let us know if we are missing anything

Thanks!!!

**Comment by hostep** [comment] 2022-09-01 10:39
I've just tested with a clean Magento 2.4.5 on Chrome 105.0.5195.52 with a screen resolution of 2560x1440 and could reproduce a couple of times. But it wasn't on the Dashboard this time, but on the Sales > Orders grid.

So again: this is only sometimes happening, not all of the times, it's pretty hard to reproduce, basically you probably want to click around in the backoffice 10 or 20 times between different pages and maybe you'll be able to trigger it.

**Comment by n2diving-dgx** [comment] 2022-09-01 12:13
I never see it on the dashboard, but it reproduces for me consistently on Sales > Orders grid.
(1) Open incognito copy of browser with large window on desktop.
(2) Visit M2.4.5 + Php8.1 store admin URL and login
(3) Observe dashboard loads normally
(4) navigate to Admin > Sales > Orders and observe

![image](https://user-images.githubusercontent.com/17930467/187911119-2b219e87-21a3-44ef-bd06-6c22d1dd9199.png)

**Comment by engcom-Dash** [comment] 2022-09-02 10:05
Hi @n2diving-dgx ,

We are not able to reproduce the issue....As per your Comments I used incognito mode and Used magento version 2.4.5 with php 8.1...I am not getting any error in dashboard and sales grid.

Here i attached screenshot of Sales grid:
![Screenshot from 2022-09-02 14-40-14](https://user-images.githubusercontent.com/60198592/188115051-2f80cc51-c7ee-46e0-9047-813c0a5c48f7.png)

Let us know if we are Missing

thanks!!!!

**Comment by hostep** [comment] 2022-09-02 10:16
@engcom-Dash: It definitely still happens, you just need to test and test and test and try again over and over again and only sometimes it will happen.

I just had it happen again over here, both on the Dashboard as on the Orders grid with a vanilla Magento 2.4.5, using Google Chrome 105.0.5195.52 this time with a screen resolution of 2304x1296, not sure if that latter is important, probably not.
I'm able to trigger it more easily when **not** using incognito, but I guess it's different for everyone.

**Comment by engcom-Dash** [comment] 2022-09-05 10:52
Hi @hostep ,

We are tried this issue more then 3 three times we are getting admin dashboard properly...

Environment:
1. magento 2.4.3 or 2.4 develop instance and 2.4.5 
2. php 7.4 and 8.1
3. google chrome version - Version 105.0.5195.52 (Official Build) (64-bit)

Let us know if we are missing anything!!!

Thanks!!!

**Comment by hostep** [comment] 2022-09-06 09:29
Yeah sorry, all I can say is that it only happens "sometimes". I just had it happen again on a Magento 2.3.6-p1 installation as well an hour ago or so. But yeah, no idea about specifying exact steps for reproducing, you just need to get "lucky" to run into it. Maybe keep your eyes open for this issue the next few weeks while testing other tickets, maybe you'll see it happen by accident one day ...

**Comment by hostep** [comment] 2022-09-06 10:01
Some people on Slack claim this problem is also happening in Firefox, so this might no longer be considered a browser bug.
Even though it's still strange that this started happening only in the last month or so on all kinds of different Magento versions where this never happened before...

**Comment by chazzs** [comment] 2022-09-08 19:47
Something to add to the strangeness: Scrolling a ways down the page will sometimes correct the layout.

**Comment by briangmoore77** [comment] 2022-09-08 23:12
I didn't have the issue at all today... with chrome... it just updated to version 105.0.5195.102 (Official Build) (64-bit) in the early morning. I haven't tested it in Firefox yet. I did test chrome incognito mode all day yesterday and never saw the issue but at the same time I saw the issue in my regular chrome window multiple times.

I'm hoping the latest Chrome update solved the problem... I will update if I see the issue again.

**Comment by chazzs** [comment] 2022-09-09 17:43
I do have LastPass installed. it does seem strange that it would hose up a
page that it does not interact with (Magento dashboard or the odd list/grid)

**Comment by briangmoore77** [comment] 2022-09-09 18:28
@chazzs Lastpass interacts with what ever is in your browser tab. Try incognito mode and see if the issue is there. Make sure you didn't give Lastpass permission to show up on incognito mode.

**Comment by n2diving-dgx** [comment] 2022-09-10 12:52
I can confirm that simply disabling the LastPass extension in Chrome stops the issue from occurring.   

![image](https://user-images.githubusercontent.com/17930467/189484140-282e49be-105d-4d6c-948c-fb8c869defcc.png)

Re-enabling the extension causes the issue to return immediately for me.

What is unclear... is this a bug in LP, or is this a something being done in M2 that is improper and/or unexpected.

**Comment by hostep** [comment] 2022-09-10 16:57
Okay, thanks for the investigation @n2diving-dgx!

I don't think it's something in M2, because it never happened before. So it's probably a new bug in one of the last LastPass browser extension versions.
I think we should try to report this to LastPass and see if they can figure out what goes wrong (even though the bug seems to be hard to reproduce).

**Comment by engcom-Dash** [comment] 2022-09-12 09:19
> Yeah sorry, all I can say is that it only happens "sometimes". I just had it happen again on a Magento 2.3.6-p1 installation as well an hour ago or so. But yeah, no idea about specifying exact steps for reproducing, you just need to get "lucky" to run into it. Maybe keep your eyes open for this issue the next few weeks while testing other tickets, maybe you'll see it happen by accident one day ...

Hi @hostep ,

Sure we are watching this issue Continuously. If we will find any bug regarding this we will update you....

Thanks!!!

**Comment by briangmoore77** [comment] 2022-09-12 17:29
@hostep @chazzs @n2diving-dgx If all of us can go to lastpass and submit bug reports it would help resolve this issue.

I've also created a topic in their support discussions:
https://community.logmein.com/t5/LastPass-Support-Discussions/Magento-2-Admin-loading-issues-with-Chrome-extenstion/m-p/293009

**Comment by engcom-Dash** [comment] 2022-09-16 10:56
Dear @n2diving-dgx ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks!!!

**Closed as completed by engcom-Dash** 2022-09-16 10:56 UTC
Labels: Issue: needs update
