### ISSUE TITLE
Magento Swatch Tooltip: bottom arrow design issue

### ISSUE THREAD

**Issue by vishal-7037** [magento/magento2#21994] opened 2019-03-28 08:57 UTC
There is a designing issue with Swatch option tooltip. this design issue occurs at all the page where swatch options populated.

### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

1. Go to configurable category view page
2. hover on swatch attribute.

### Expected result (*)

![2019_03_28_Tooltip_003](https://user-images.githubusercontent.com/38535982/55143662-30930900-5165-11e9-9755-a92b702791f3.png)

### Actual result (*)
![2019_03_28_Tooltip_002](https://user-images.githubusercontent.com/38535982/55143673-3688ea00-5165-11e9-9fa1-df7163b03790.png)

**Comment by magento-engcom-team** [comment] 2019-03-28 08:57
Hi @vishal-7037. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@vishal-7037 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-03-28 08:59
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment] 2019-03-28 09:01
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-28 09:01
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-28 09:02
Hi @shikhamis11, here is your [Magento instance](https://i-21994-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21994-2-3-develop.instances.magento-community.engineering/admin](https://i-21994-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-03-28 09:19
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment] 2019-03-28 09:25
@vishal-7037 this issue is not reproduceable at current magento 2.3-develop version. 
Please check the screenshot
![Screenshot_2019-03-28_14-53-53](https://user-images.githubusercontent.com/25526037/55145868-91bcdb80-5169-11e9-9ff2-c57b46ba779e.png)

**Comment by vishal-7037** [comment] 2019-03-28 09:37
@shikhamis11 Have you checked same issue in google chrome browser?
Please check it in chrome.

**Comment by shikhamis11** [comment] 2019-03-28 09:51
@vishal-7037 Please check chrome screenshot 
![Screenshot_2019-03-28_15-19-35](https://user-images.githubusercontent.com/25526037/55147815-18bf8300-516d-11e9-90eb-1a7800559998.png)

**Comment by vishal-7037** [comment] 2019-03-28 09:54
@shikhamis11 I've checked in chrome using above m2 instance. Please check here:
![2019_03_28_Tooltip_001](https://user-images.githubusercontent.com/38535982/55148049-8370be80-516d-11e9-8e58-f0f8bb325712.png)

**Comment by shikhamis11** [comment] 2019-03-28 10:52
@vishal-7037 Can you send your chrome version ?? 
as I also checked on mac system ..not getting this

**Comment by vishal-7037** [comment] 2019-03-28 11:03
@shikhamis11 **Chrome Version:** Version 73.0.3683.75 (Official Build) (64-bit)

**Comment by shikhamis11** [comment] 2019-03-29 19:11
@vishal-7037 I checked on the same version but didn't find the issue . Anyway I will let this issue open if anyone can verify this

**Comment by Nazar65** [comment] 2019-04-30 11:11
Hi @vishal-7037 thank you for you report, this issue is not reproducible on 2.3-develop branch, tested with chrome 73-74 firefox or any other browsers. and tested with hight resolution screen.

**Closed as completed by Nazar65** 2019-04-30 11:11 UTC
Labels: Issue: Format is valid
