### ISSUE TITLE
414 Request-URI Too Large while Assign Sources on inventory stock edit

### ISSUE THREAD

**Issue by mansato** [magento/magento2#38121] opened 2023-10-25 09:45 UTC
### Preconditions and environment

Magento 2.4.5-p2
PHP 8.1.21

### Steps to reproduce

Login to admin panel
Go to store inventory > stock
Edit one Stock
Click on Assign Sources
Expected result
Order Item Should be exported successfully
**My payload:** (243 parameters)
`namespace: inventory_source_listing
search: 
keywordUpdated: false
paging[pageSize]: 20
paging[current]: 1
filters[placeholder]: true
filters_modifier[source_code][condition_type]: nin
filters_modifier[source_code][value][]: 000
filters_modifier[source_code][value][]: 5001
filters_modifier[source_code][value][]: 5002
filters_modifier[source_code][value][]: 2252
filters_modifier[source_code][value][]: 2193
filters_modifier[source_code][value][]: 2287
filters_modifier[source_code][value][]: 2256
filters_modifier[source_code][value][]: 2159
filters_modifier[source_code][value][]: 2210
filters_modifier[source_code][value][]: 2178
filters_modifier[source_code][value][]: 2281
filters_modifier[source_code][value][]: 2127
filters_modifier[source_code][value][]: 2036
filters_modifier[source_code][value][]: 2197
filters_modifier[source_code][value][]: 2215
filters_modifier[source_code][value][]: 2262
filters_modifier[source_code][value][]: 2233
filters_modifier[source_code][value][]: 2312
filters_modifier[source_code][value][]: 2306
filters_modifier[source_code][value][]: 2109
filters_modifier[source_code][value][]: 2037
filters_modifier[source_code][value][]: 2255
filters_modifier[source_code][value][]: 2305
filters_modifier[source_code][value][]: 2140
filters_modifier[source_code][value][]: 2315
filters_modifier[source_code][value][]: 2004
filters_modifier[source_code][value][]: 2254
filters_modifier[source_code][value][]: 2217
filters_modifier[source_code][value][]: 2175
filters_modifier[source_code][value][]: 2141
filters_modifier[source_code][value][]: 2245
filters_modifier[source_code][value][]: 2319
filters_modifier[source_code][value][]: 2173
filters_modifier[source_code][value][]: 2027
filters_modifier[source_code][value][]: 2224
filters_modifier[source_code][value][]: 2118
filters_modifier[source_code][value][]: 2152
filters_modifier[source_code][value][]: 2282
filters_modifier[source_code][value][]: 2145
filters_modifier[source_code][value][]: 2278
filters_modifier[source_code][value][]: 2234
filters_modifier[source_code][value][]: 2292
filters_modifier[source_code][value][]: 2195
filters_modifier[source_code][value][]: 2314
filters_modifier[source_code][value][]: 2187
filters_modifier[source_code][value][]: 2171
filters_modifier[source_code][value][]: 2247
filters_modifier[source_code][value][]: 2052
filters_modifier[source_code][value][]: 2017
filters_modifier[source_code][value][]: 2170
filters_modifier[source_code][value][]: 2285
filters_modifier[source_code][value][]: 2243
filters_modifier[source_code][value][]: 2269
filters_modifier[source_code][value][]: 2270
filters_modifier[source_code][value][]: 2295
filters_modifier[source_code][value][]: 2129
filters_modifier[source_code][value][]: 2046
filters_modifier[source_code][value][]: 2289
filters_modifier[source_code][value][]: 2181
filters_modifier[source_code][value][]: 2157
filters_modifier[source_code][value][]: 2298
filters_modifier[source_code][value][]: 2188
filters_modifier[source_code][value][]: 2128
filters_modifier[source_code][value][]: 2321
filters_modifier[source_code][value][]: 2309
filters_modifier[source_code][value][]: 2279
filters_modifier[source_code][value][]: 2001
filters_modifier[source_code][value][]: 2205
filters_modifier[source_code][value][]: 2283
filters_modifier[source_code][value][]: 2244
filters_modifier[source_code][value][]: 2251
filters_modifier[source_code][value][]: 2286
filters_modifier[source_code][value][]: 2303
filters_modifier[source_code][value][]: 2011
filters_modifier[source_code][value][]: 2174
filters_modifier[source_code][value][]: 2300
filters_modifier[source_code][value][]: 2297
filters_modifier[source_code][value][]: 2202
filters_modifier[source_code][value][]: 2259
filters_modifier[source_code][value][]: 2264
filters_modifier[source_code][value][]: 2163
filters_modifier[source_code][value][]: 2216
filters_modifier[source_code][value][]: 2018
filters_modifier[source_code][value][]: 2238
filters_modifier[source_code][value][]: 2235
filters_modifier[source_code][value][]: 2034
filters_modifier[source_code][value][]: 2117
filters_modifier[source_code][value][]: 2299
filters_modifier[source_code][value][]: 2192
filters_modifier[source_code][value][]: 2207
filters_modifier[source_code][value][]: 2112
filters_modifier[source_code][value][]: 2062
filters_modifier[source_code][value][]: 2293
filters_modifier[source_code][value][]: 2231
filters_modifier[source_code][value][]: 2311
filters_modifier[source_code][value][]: 2021
filters_modifier[source_code][value][]: 2214
filters_modifier[source_code][value][]: 2296
filters_modifier[source_code][value][]: 2268
filters_modifier[source_code][value][]: 2040
filters_modifier[source_code][value][]: 2258
filters_modifier[source_code][value][]: 2230
filters_modifier[source_code][value][]: 2307
filters_modifier[source_code][value][]: 2266
filters_modifier[source_code][value][]: 2153
filters_modifier[source_code][value][]: 2294
filters_modifier[source_code][value][]: 2267
filters_modifier[source_code][value][]: 2248
filters_modifier[source_code][value][]: 2038
filters_modifier[source_code][value][]: 2240
filters_modifier[source_code][value][]: 2265
filters_modifier[source_code][value][]: 2219
filters_modifier[source_code][value][]: 2020
filters_modifier[source_code][value][]: 2218
filters_modifier[source_code][value][]: 2257
filters_modifier[source_code][value][]: 2010
filters_modifier[source_code][value][]: 2261
filters_modifier[source_code][value][]: 2049
filters_modifier[source_code][value][]: 2246
filters_modifier[source_code][value][]: 2288
filters_modifier[source_code][value][]: 2130
filters_modifier[source_code][value][]: 2301
filters_modifier[source_code][value][]: 2209
filters_modifier[source_code][value][]: 2121
filters_modifier[source_code][value][]: 2275
filters_modifier[source_code][value][]: 2242
filters_modifier[source_code][value][]: 2304
filters_modifier[source_code][value][]: 2208
filters_modifier[source_code][value][]: 2250
filters_modifier[source_code][value][]: 2201
filters_modifier[source_code][value][]: 2039
filters_modifier[source_code][value][]: 2134
filters_modifier[source_code][value][]: 2024
filters_modifier[source_code][value][]: 2101
filters_modifier[source_code][value][]: 2241
filters_modifier[source_code][value][]: 2273
filters_modifier[source_code][value][]: 2212
filters_modifier[source_code][value][]: 2260
filters_modifier[source_code][value][]: 2280
filters_modifier[source_code][value][]: 2320
filters_modifier[source_code][value][]: 2110
filters_modifier[source_code][value][]: 2065
filters_modifier[source_code][value][]: 2149
filters_modifier[source_code][value][]: 2007
filters_modifier[source_code][value][]: 2150
filters_modifier[source_code][value][]: 2047
filters_modifier[source_code][value][]: 2263
filters_modifier[source_code][value][]: 2239
filters_modifier[source_code][value][]: 2126
filters_modifier[source_code][value][]: 2048
filters_modifier[source_code][value][]: 2191
filters_modifier[source_code][value][]: 2232
filters_modifier[source_code][value][]: 2132
filters_modifier[source_code][value][]: 2008
filters_modifier[source_code][value][]: 2310
filters_modifier[source_code][value][]: 2160
filters_modifier[source_code][value][]: 2031
filters_modifier[source_code][value][]: 2183
filters_modifier[source_code][value][]: 2313
filters_modifier[source_code][value][]: 2119
filters_modifier[source_code][value][]: 2115
filters_modifier[source_code][value][]: 2272
filters_modifier[source_code][value][]: 2249
filters_modifier[source_code][value][]: 2199
filters_modifier[source_code][value][]: 2274
filters_modifier[source_code][value][]: 2105
filters_modifier[source_code][value][]: 2291
filters_modifier[source_code][value][]: 2228
filters_modifier[source_code][value][]: 2222
filters_modifier[source_code][value][]: 2206
filters_modifier[source_code][value][]: 2012
filters_modifier[source_code][value][]: 2019
filters_modifier[source_code][value][]: 2033
filters_modifier[source_code][value][]: 2253
filters_modifier[source_code][value][]: 2009
filters_modifier[source_code][value][]: 2316
filters_modifier[source_code][value][]: 2276
filters_modifier[source_code][value][]: 2237
filters_modifier[source_code][value][]: 2003
filters_modifier[source_code][value][]: 2318
filters_modifier[source_code][value][]: 2050
filters_modifier[source_code][value][]: 2236
filters_modifier[source_code][value][]: 2022
filters_modifier[source_code][value][]: 2185
filters_modifier[source_code][value][]: 2229
filters_modifier[source_code][value][]: 2023
filters_modifier[source_code][value][]: 2308
filters_modifier[source_code][value][]: 2271
filters_modifier[source_code][value][]: 2317
filters_modifier[source_code][value][]: 2290
filters_modifier[source_code][value][]: 2058
filters_modifier[source_code][value][]: 2223
filters_modifier[source_code][value][]: 2164
filters_modifier[source_code][value][]: 2196
filters_modifier[source_code][value][]: 2302
filters_modifier[source_code][value][]: 2284
filters_modifier[source_code][value][]: 2045
filters_modifier[source_code][value][]: 2055
filters_modifier[source_code][value][]: 2113
filters_modifier[source_code][value][]: 2066
filters_modifier[source_code][value][]: 2322
filters_modifier[source_code][value][]: 2323
filters_modifier[source_code][value][]: 2329
filters_modifier[source_code][value][]: 2324
filters_modifier[source_code][value][]: 2325
filters_modifier[source_code][value][]: 2327
filters_modifier[source_code][value][]: 2326
filters_modifier[source_code][value][]: 2328
filters_modifier[source_code][value][]: 2333
filters_modifier[source_code][value][]: 2335
filters_modifier[source_code][value][]: 2336
filters_modifier[source_code][value][]: 2339
filters_modifier[source_code][value][]: 2337
filters_modifier[source_code][value][]: 2341
filters_modifier[source_code][value][]: 2332
filters_modifier[source_code][value][]: 2331
filters_modifier[source_code][value][]: 2338
filters_modifier[source_code][value][]: 2334
filters_modifier[source_code][value][]: 2340
filters_modifier[source_code][value][]: 2343
filters_modifier[source_code][value][]: 2344
filters_modifier[source_code][value][]: 2342
filters_modifier[source_code][value][]: 2345
filters_modifier[source_code][value][]: 2348
filters_modifier[source_code][value][]: 2349
filters_modifier[source_code][value][]: 2347
filters_modifier[source_code][value][]: 2346
filters_modifier[source_code][value][]: 2350
filters_modifier[source_code][value][]: 2351
filters_modifier[source_code][value][]: 2200
filters_modifier[source_code][value][]: 2277
filters_modifier[source_code][value][]: 2204
filters_modifier[source_code][value][]: 5003
filters_modifier[source_code][value][]: sfs_fr
filters_modifier[source_code][value][]: 2330
isAjax: true`

### Expected result

![image](https://github.com/magento/magento2/assets/16746311/262fecab-8496-4e99-858a-d4347596e2d5)

### Actual result

![Capture d’écran du 2023-10-25 11-40-12](https://github.com/magento/magento2/assets/16746311/910d1109-899c-425c-8067-6b66fb9b28a0)
![image](https://github.com/magento/magento2/assets/16746311/5ccd9925-2c9e-4257-982d-36db5ee41b4d)
![Capture d’écran du 2023-10-25 11-42-15](https://github.com/magento/magento2/assets/16746311/177e9498-89bf-48ab-9403-215533d3b127)
![Capture d’écran du 2023-10-25 11-42-48](https://github.com/magento/magento2/assets/16746311/26893e87-d642-4cdb-80b4-7285e3d11a79)

It generate an error 414 Request-URI Too Large

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mansato** [comment] 2023-10-25 09:46
@magento give me 2.4-develop instance

**Comment by mansato** [comment] 2023-10-25 13:19
I have a problem with magento instance 
![Capture d’écran du 2023-10-25 15-17-51](https://github.com/magento/magento2/assets/16746311/de2ed260-8847-47b2-bc2b-6d00b3a518d5)

**Comment by mansato** [comment] 2023-10-25 13:55
https://github.com/magento give me 2.4-develop instance

**Comment by mansato** [comment] 2023-10-25 13:56
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-10-26 06:19
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-10-26 06:37
Hi @mansato,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Login to admin panel
- Go to store inventory > stock
- Edit one Stock
- Click on Assign Sources


<img width="1366" alt="Screenshot 2023-10-26 at 12 02 30 PM" src="https://github.com/magento/magento2/assets/51680745/88fabb77-1473-4612-9b00-ec3e3971caf8">


<img width="1420" alt="Screenshot 2023-10-26 at 12 02 50 PM" src="https://github.com/magento/magento2/assets/51680745/6b55f9b3-5c54-46e4-8fbd-e7f3d576ac36">



We are able to edit the stock and assign the respective sources to the stock successfully.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by mansato** [comment] 2023-10-27 08:58
Hi, @engcom-Bravo 

**Problem Location (in the vendor directory):**

`vendor/magento/module-inventory-admin-ui/view/adminhtml/ui_component/inventory_source_listing.xml`

**Solution:**

You need to override this file in your local module. Instead of directly modifying the core Magento files, always try to override them in your local module to ensure future compatibility and easier upgrades.

**Override Path:**

`app/code/[Your_Company]/[Your_Module]/view/adminhtml/ui_component/inventory_source_listing.xml`

(Note: Replace [Your_Company] and [Your_Module] with your actual company and module names.)

**File Content:**
Your overridden XML should look like this:

```
<?xml version="1.0"?>
<!--
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<listing xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
    <dataSource name="inventory_source_listing_data_source" component="Magento_Ui/js/grid/provider">
        <settings>
            <storageConfig>
                <param name="requestConfig" xsi:type="array">
                    <param name="method" xsi:type="string">POST</param>
                </param>
            </storageConfig>
        </settings>
    </dataSource>
</listing>
```
By following these steps, you should be able to successfully override the method and change the request type from GET to POST. Remember, always try to avoid editing the core files directly. Instead, make use of Magento's override system.

**Comment by engcom-Bravo** [comment] 2023-10-30 06:12
Hi @mansato,

Thanks for your update.

As per the steps to reproduce the issue is not reproducible in Magento 2.4-develop instance so i request to please try to reproduce the issue in Magento 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-11-13 05:54
Hi @mansato,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.
Thanks.

**Closed as completed by engcom-Bravo** 2023-11-13 05:54 UTC
Labels: Issue: needs update, Reported on 2.4.5-p2

**Comment by aligent-lturner** [comment] 2023-11-22 03:12
@engcom-Bravo the reason you could not reproduce the error is that you only had 3 inventory sources. Clearly in the original issue's screenshot (and from reading the request parameters), @mansato had many, many more already assigned.
The issue is that a URI is generated to exclude any sources already assigned, so if you have something like 200 sources already assigned, the URI becomes massive.

**Comment by andrewdaluz** [comment] 2024-07-01 15:25
For who needs a patch this should be a fix for it: 
[](https://experienceleague.adobe.com/en/docs/commerce-knowledge-base/kb/support-tools/patches/v1-1-21/acsd-46809-the-user-gets-an-error-when-assigning-a-large-number-of-product-sources)
[](https://github.com/magento/quality-patches/blob/master/patches/os/ACSD-46809_2.4.4.patch)
