### ISSUE TITLE
AGAIN: Photorama Skript bugs - I really get angry with magentos bug handling policy!

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#8924] opened 2017-03-17 11:07 UTC
### Preconditions

1. Magento 2.1.4, Nginx, Varnish, Redis, PHP7, Mysql
2. Set up for production environment

### Steps to reproduce

1. Open product page with for example chrome on an android device (also same for chrome mac desktop!)
2. Click on product picture to expand the picture

### Expected result

1. The product picture is shown on the right format (meaning the bulletpoint are on the bottom and the picture is in the middle

### Actual result

1. the product page is stuck to the top and the bullet point are not whown on the bottom of the screen - only when you touch the picture again it gets rezized right!

Our comments about the fotorama script:

We reported a lot of bugs regarding the photorama implementation for example the scroll issue etc. It seems that at magento side nobody is really caring about really fixing ALL bugs! 

I give you two examples:

One more bug seen third screenshot: 
If you close the photorama script with the "X" at the top right corner the click effects the cart laying beneath the script and leads to a redirect or open of the cart page/popup.

--> Worst case for usability

Second example and mentioned here several times without a feedback/solution:

The implementation of the photorama script is just not good. The loading time like mentioned here from other users as well is way above the ecceptable - a product page needs 3-4 seconds to show the first picture. With other scripts like magic zoom plus it loads in under one second.

--> Worst case for mobile usability at all!

I am not shure how magento handles bugs but if i look around here i loose trust at all! 

Pls give us a feedback on these 3 bugs on the photorama script magento team and pls do not tell us "commit xyz" - will be solved in 10 month...

Thanks!

![opens-cart-or-cart-popup](https://cloud.githubusercontent.com/assets/16196483/24040602/32a2a23a-0b0a-11e7-820f-e9153376b77c.png)
![right-position](https://cloud.githubusercontent.com/assets/16196483/24040603/32caa42e-0b0a-11e7-9bae-3255b9cd5285.png)
![wrong-possition](https://cloud.githubusercontent.com/assets/16196483/24040604/32ccbaca-0b0a-11e7-84de-6001738f4fe7.png)

**Comment by andidhouse** [comment] 2017-03-17 11:08
Never ending story with magento 2 bugs so far? AND: Is there anybody caring about the bugs reported here any more? It looks like there are many open bugs here since weeks?

**Comment by dakzilla** [comment] 2017-03-20 14:43
> It looks like there are many open bugs here since weeks?

Make that years. Some of the oldest open issues are from over 2 years ago. Magento is keeping itself busy selling that EE, ain't nobody got time for bug-fixing or quality assurance!

**Comment by magento-engcom-team** [comment] 2017-11-14 13:30
@andidhouse, thank you for your report.
The issue is already fixed in 2.2.1

**Closed as completed by magento-engcom-team** 2017-11-14 13:30 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
