### ISSUE TITLE
Batch delete blocks not working

### ISSUE THREAD

**Issue by quisse** [magento/magento2#12329] opened 2017-11-17 12:22 UTC
When deleting a batch of blocks on the blocks grid, en error occurs:
`Uncaught Error: Call to undefined method Magento\Cms\Model\ResourceModel\Block\Grid\Collection::_getAllIdsSelect() in /[magento location]/vendor/magento/module-cms/Model/ResourceModel/Block/Grid/Collection.php on line 97`

### Preconditions

1. Magento 2.1.10

### Steps to reproduce

1. Select one or multiple blocks in the blocks grid in the Magento backend
2. Select delete action

### Expected result

1. Selected block is deleted

### Actual result

1. 
```
Uncaught Error: Call to undefined method Magento\Cms\Model\ResourceModel\Block\Grid\Collection::_getAllIdsSelect() in /[magento location]/vendor/magento/module-cms/Model/ResourceModel/Block/Grid/Collection.php on line 97

( ! ) Fatal error: Uncaught Error: Call to undefined method Magento\Cms\Model\ResourceModel\Block\Grid\Collection::_getAllIdsSelect() in /Users/tommyquissens/sites/wegro/vendor/magento/module-cms/Model/ResourceModel/Block/Grid/Collection.php on line 97
--



1 | 0.0045 | 380312 | {main}( ) | .../index.php:0
2 | 0.2209 | 7784864 | Magento\Framework\App\Bootstrap->run( ??? ) | .../index.php:61
3 | 0.2221 | 7833928 | Magento\Framework\App\Http\Interceptor->launch( ) | .../Bootstrap.php:258
4 | 0.2326 | 8311008 | Magento\Framework\App\Http\Interceptor->launch( ) | .../Interceptor.php:24
5 | 0.4066 | 14269024 | Magento\Framework\App\FrontController\Interceptor->dispatch( ??? ) | .../Http.php:135
6 | 0.4088 | 14202352 | Magento\Framework\App\FrontController\Interceptor->___callPlugins( ???, ???, ??? ) | .../Interceptor.php:26
7 | 0.4439 | 15096184 | Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch( ???, ???, ??? ) | .../Interceptor.php:142
8 | 0.4442 | 15096256 | Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}( ??? ) | .../DbStatusValidator.php:69
9 | 0.4442 | 15096632 | Magento\Framework\Interception\Chain\Chain->invokeNext( ???, ???, ???, ???, ??? ) | .../Interceptor.php:138
10 | 0.4443 | 15096672 | Magento\Framework\App\FrontController\Interceptor->___callParent( ???, ??? ) | .../Chain.php:70
11 | 0.4443 | 15096672 | Magento\Framework\App\FrontController\Interceptor->dispatch( ??? ) | .../Interceptor.php:74
12 | 0.7821 | 22871968 | Magento\Cms\Controller\Adminhtml\Block\MassDelete\Interceptor->dispatch( ??? ) | .../FrontController.php:55
13 | 0.7851 | 22987152 | Magento\Cms\Controller\Adminhtml\Block\MassDelete\Interceptor->___callPlugins( ???, ???, ??? ) | .../Interceptor.php:39
14 | 1.1744 | 28443032 | Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch( ???, ???, ??? ) | .../Interceptor.php:142
15 | 1.1744 | 28443032 | Magento\Cms\Controller\Adminhtml\Block\MassDelete\Interceptor->Magento\Framework\Interception\{closure}( ??? ) | .../MassactionKey.php:33
16 | 1.1744 | 28443408 | Magento\Framework\Interception\Chain\Chain->invokeNext( ???, ???, ???, ???, ??? ) | .../Interceptor.php:138
17 | 1.1950 | 28774104 | Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch( ???, ???, ??? ) | .../Chain.php:67
18 | 1.2248 | 28830272 | Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}( ??? ) | .../Authentication.php:143
19 | 1.2248 | 28830648 | Magento\Framework\Interception\Chain\Chain->invokeNext( ???, ???, ???, ???, ??? ) | .../Chain.php:63
20 | 1.2250 | 28830688 | Magento\Cms\Controller\Adminhtml\Block\MassDelete\Interceptor->___callParent( ???, ??? ) | .../Chain.php:70
21 | 1.2250 | 28830688 | Magento\Cms\Controller\Adminhtml\Block\MassDelete\Interceptor->dispatch( ??? ) | .../Interceptor.php:74
22 | 1.2431 | 29275912 | Magento\Cms\Controller\Adminhtml\Block\MassDelete\Interceptor->dispatch( ??? ) | .../AbstractAction.php:226
23 | 1.2628 | 29521560 | Magento\Cms\Controller\Adminhtml\Block\MassDelete\Interceptor->execute( ) | .../Action.php:102
24 | 1.2628 | 29521560 | Magento\Cms\Controller\Adminhtml\Block\MassDelete\Interceptor->execute( ) | .../Interceptor.php:24
25 | 1.2746 | 29753640 | Magento\Ui\Component\MassAction\Filter->getCollection( ??? ) | .../MassDelete.php:56
26 | 1.2747 | 29753640 | Magento\Ui\Component\MassAction\Filter->getFilterIds( ) | .../Filter.php:104
27 | 6.1514 | 33361472 | Magento\Cms\Model\ResourceModel\Block\Grid\Collection->getAllIds( ???, ??? ) | .../Filter.php:238
```

**Comment by magento-engcom-team** [comment] 2017-11-20 08:26
@quisse, thank you for your report.
The issue is already fixed in develop branch, 2.2.1

**Closed as completed by magento-engcom-team** 2017-11-20 08:26 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
