### ISSUE TITLE
Cart can't be emptied if any product is out of stock

### ISSUE THREAD

**Issue by wojtekn** [magento/magento2#21294] opened 2019-02-18 12:14 UTC
### Preconditions

1. Magento 2.3
2. Magento 2.2

### Steps to reproduce

1. Add simple product in backend, set positive quantity and Stock Status = In Stock
2. Open another browser tab and access product in frontend
3. Add product to cart
4. Navigate to cart
5. Enable "Clear Shopping Cart" button by running this code in console:
`jQuery('.action.clear').show()`
It's hidden in CSS for some reason.
6. Back to product form in the backend
7. Set Stock Status for product to Out of Stock, save
8. Click "Clear Shopping Cart" button in the cart in frontend

### Expected result

1. Cart is cleared

### Actual result

1. Popup with "This product is out of stock." error is displayed

**Comment by magento-engcom-team** [comment] 2019-02-18 12:14
Hi @wojtekn. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@wojtekn do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-02-18 12:22
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by wojtekn** [comment] 2019-02-18 12:24
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-18 12:24
Hi @wojtekn. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-18 12:25
Hi @wojtekn, here is your [Magento instance](https://i-21294-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21294-2-3-develop.instances.magento-community.engineering/admin](https://i-21294-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by wojtekn** [comment] 2019-02-18 12:30
I reproduced issue on test 2.3 instance.

**Comment by magento-engcom-team** [comment] 2019-02-18 12:33
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98308`, `MAGETWO-98309` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-03-01 08:00
Hi @wojtekn. Thank you for your report. 
The issue has been fixed in magento/magento2#21295 by @wojtekn in 2.3-develop branch
Related commit(s):
 - [4cdcb7475eb7e2feb14be9f7951341cd9b84a89c](https://github.com/magento/magento2/commit/4cdcb7475eb7e2feb14be9f7951341cd9b84a89c)
 - [f6656f95401bf5ad858e632df862f6c4e8f88da5](https://github.com/magento/magento2/commit/f6656f95401bf5ad858e632df862f6c4e8f88da5)
 - [96793feaf7d4e8b3524ae859cae55fec880e41ff](https://github.com/magento/magento2/commit/96793feaf7d4e8b3524ae859cae55fec880e41ff)
 - [f82299b746f6f7846d98693d343f6633e430c5c9](https://github.com/magento/magento2/commit/f82299b746f6f7846d98693d343f6633e430c5c9)
 - [a1578b550ef678f9821a6f6756e3efe5206162be](https://github.com/magento/magento2/commit/a1578b550ef678f9821a6f6756e3efe5206162be)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-01 08:00 UTC
Labels: Issue: Ready for Work, Component: Checkout, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by magento-engcom-team** [comment] 2019-03-14 15:30
Hi @wojtekn. Thank you for your report. 
The issue has been fixed in magento/magento2#21528 by @wojtekn in 2.2-develop branch
Related commit(s):
 - [7bb5dd47e92e4d20da612e62bae7822de48d1bee](https://github.com/magento/magento2/commit/7bb5dd47e92e4d20da612e62bae7822de48d1bee)
 - [847115efd5068b40a4d274702d6086f0d6549adc](https://github.com/magento/magento2/commit/847115efd5068b40a4d274702d6086f0d6549adc)
 - [42b03bb7cd92320bb6b689b82101ac4eb91b1b93](https://github.com/magento/magento2/commit/42b03bb7cd92320bb6b689b82101ac4eb91b1b93)

The fix will be available with the upcoming 2.2.9 release.
