### ISSUE TITLE
Api Integration activate error 

### ISSUE THREAD

**Issue by Rajat9620** [magento/magento2#26864] opened 2020-02-13 17:34 UTC
Hello Support,

I hope you are doing fine.
I have installed printfull Integration in the my magento 2 store. After installing the the extension, when tried to activate I am getting this error "The attempt to post data to consumer failed due to an unexpected error. Please try again later."

After checking the exception log, I am getting this error message 
main.CRITICAL: Invalid header line detected {"exception":"[object] (Zend_Http_Exception(code: 0): Invalid header line detected at /vendor/magento/zendframework1/library/Zend/Http/Response.php:572

My current magento version is 2.3.0. 
@magento-engcom-team  Please check this issue and help me to solve this issue.

Thanks

**Comment by Rajat9620** [comment] 2020-02-15 10:58
@magento-engcom-team  any update please?

**Comment by engcom-Alfa** [comment] 2020-02-20 09:09
Hi, @Rajat9620. Thank you for your report.

Unfortunately, we are not able to reproduce this issue on clean 2.4 develop and 2.3.4 instances.
Probably the problem is with **Printful Integration** 3rd party extension.
So, we have to close it.

Thanks!

**Closed as completed by engcom-Alfa** 2020-02-20 09:09 UTC
Labels: Issue: Format is not valid, Reported on 2.3.0
