### ISSUE TITLE
SQLSTATE[42000]: Syntax error - When running php bin/magento setup:rollback (M 2.4.2 and Maria DB 10.4)

### ISSUE THREAD

**Issue by Munktells** [magento/magento2#32452] opened 2021-03-11 15:17 UTC
### Preconditions (*)
1. Install `Magento 2.4.2` using `Maria DB 10.4.18` as your SQL Server.

### Steps to reproduce (*)
1. Run `php bin/magento setup:rollback -d 1615417201_db.sql `
2. Wait until error occurs.

### Expected result (*)
Operation ends with:
`[SUCCESS]: Database rollback completed successfully.`

### Actual result (*)
Operations ends with:
`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'delimiter' at line 1, query was: delimiter ;;`

![sql](https://user-images.githubusercontent.com/57530884/110808977-c954bd80-8284-11eb-99b5-6488bd775d3f.png)

### Workaround (*)
Use **file load** of Magento backup file in HeidiSQL and hit "F9" (no errors or warnings).

### Notes (*)
The rollback job seems to work and seems to complete.

- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by AlldoGroup** [comment] 2021-03-26 07:22
More information on this issue that might help:

https://mariadb.com/kb/en/delimiters/

Two delimiters fount in all or back up files at the following location:
![delimiter](https://user-images.githubusercontent.com/57530884/112596624-5a42a180-8e0c-11eb-95ca-611a1265afc4.jpg)

Doesn't seem to be related to any third party extensions.

**Comment by magento-engcom-team** [comment] 2021-06-14 04:12
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42626` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Alfa** [comment] 2021-06-14 04:16
Still we are getting error "The rollback file doesn't exist. Verify the file and try again."

**Comment by engcom-Delta** [comment] 2021-06-17 04:18
Hi @AlldoGroup:

I tried on Magento 2.4. Develop & My SQL , it was not reproducible , i got success message like "DB rollback completed successfully". PFA screenshot for reference.

Followed below steps and observed that DB rollback successfully completed.
1.	Installed Magento 2.4 Develop
2.	Installed apache & my SQL by xampp and db tables created
3.	Run command “bin/magento setup:backup –db” ( in git bash) 
4.	Created the file “1615417201_db.sql” in backup folder
5.	Run the php bin/magento setup:rollback -d 1615417201_db.sql
6.	Received the message “[SUCCESS]: DB rollback completed successfully”

Kindly help me with appropriate steps if my understanding is [wrong.](url)

<img width="960" alt="DB_rollback" src="https://user-images.githubusercontent.com/51681379/122330607-254c7380-cf51-11eb-9d75-6d2b122399ba.png">

**Comment by AlldoGroup** [comment] 2021-06-17 04:38
Hi @engcom-Delta 

We use Maria DB 10.4.18 as our SQL Server, and not MySQL.
If that would make any difference?

https://mariadb.com/kb/en/delimiters/

**Comment by engcom-Delta** [comment] 2021-06-17 13:20
Hi @AlldoGroup,
We tried on Maria DB 10.1.47 & 10.4.19 found that successfully the process has been completed without any issues.Hence request to help us to reproduce the issue.
![image](https://user-images.githubusercontent.com/51681379/122404412-d4fb0300-cf9c-11eb-8b42-bf101f1ba639.png)
PFA.
Thanking you.

**Comment by engcom-Delta** [comment] 2021-07-02 11:38
Hi @AlldoGroup,

There has no update from reporter since ~ 14 days. hence closing the ticket.
Kindly log new ticket if required or re-open the existing issue.

Thanks

**Closed as completed by engcom-Delta** 2021-07-02 11:38 UTC
Labels: Component: Backend, Reproduced on 2.4.x, Progress: done, Issue: ready for confirmation, Reported on 2.4.2
