### ISSUE TITLE
Accessing Admin causes ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by gacleg** [magento/magento2#3886] opened 2016-03-24 00:44 UTC
I just set up a new install of Magento 2. I can access the main home page, but when I try to get into the Admin page, it gives me a ERR_TOO_MANY_REDIRECTS.  

The URL I enter is:  http://mywebsite_com.apache4.cloudsector.net/shop/Admin and when the error returns the URL in the browser is: http://mywebsite_com.apache4.cloudsector.net/shop/Admin/http:/index/mywebsite_com.apache4.cloudsector.net/shop/Admin/admin/index/index/key/key/a7eaad42cc20d3387784d3402680d9809113ec8f1cf80700c7b.../

I've tried this both in Chrome and IE with the same result.  Any help would be appreciated.

**Comment by der-workfloh** [comment] 2016-03-25 09:06
@gacleg Evaluate if your sessions folder respective to your configuration in the env.php file is accessable and writable by the executing user (e.g. www-data).

**Comment by gacleg** [comment] 2016-03-25 19:24
Thank you for the help.  It turns out that initially having my site in a subdirectory required a change to 4 different .htaccess files as per https://mage2.pro/t/topic/260.  That still didn't fix it, so then we discovered that magento doesn't like URL's with an _ underscore.  So we changed the URL to  http://mywebsite-com.apache4.cloudsector.net/shop/Admin and that seemed to fix the problem.

**Comment by mazhalai** [comment] 2016-03-28 15:13
@gacleg closing this ticket, since original issue is resolved. Please create a new tickets if further issues arise.

**Closed as completed by mazhalai** 2016-03-28 15:13 UTC

**Comment by ghost** [comment] 2016-05-12 12:01
@mazhalai I have run into this issue on a fresh install also. Only the frontend is accessible and provides ERR_TOO_MANY_REDIRECTS as an error when trying to access the admin. The setup consists of haproxy with ssl termination in front of nginx. I'm assuming the issue is how haproxy interacts with the magento backend with ssl enabled.

**Comment by ghost** [comment] 2016-05-12 13:40
Adding fastcgi_param HTTPS on; within my nginx config made the admin area accessible. Is this the appropriate solution for this?
