### ISSUE TITLE
Upload Product Photos

### ISSUE THREAD

**Issue by kkrafts** [magento/magento2#38293] opened 2023-12-17 17:51 UTC
### Preconditions and environment

- Magento 2
- product photos not uploading when creating a new product on back end

### Steps to reproduce

Upload a product photo. Use png format in the proper size, I used 600kb.  (see attached) It will not upload and produces an error message. 
![Square Back Upholstered Dining Chair-2](https://github.com/magento/magento2/assets/154083992/e6c05551-c047-4d93-aa90-7f03019c137b)

### Expected result

Photo upload successfully

### Actual result

Error Message, see screenshot. 
<img width="1373" alt="Screenshot 2023-12-17 at 12 51 08 PM" src="https://github.com/magento/magento2/assets/154083992/a4f12eb5-3e96-4388-a39e-2485c1658b48">

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by FadedOut** [comment] 2023-12-18 05:24
@kkrafts 

Please check your log files in the /var/log/ directory. Check system.log and exception.log. They will help point you to the exact problem. My guess is the tmp folder is missing in the /pub/media/catalog dir, or the permissions/ownership of the folder is wrong. Though it may not even be an image problem as the error seems to be appearing when you simply try to save the product? Those log files will help you best.

Any time you see the "a technical problem has occurred" error, check the log files, they are your best friend debugging Magento.

**Comment by engcom-Bravo** [comment] 2023-12-18 06:07
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-12-18 06:23
@FadedOut Thanks for your contribution & collaboration over here.

Hi @kkrafts,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


![Screenshot from 2023-12-18 11-52-09](https://github.com/magento/magento2/assets/51680745/a7be862c-44c8-45fd-a80d-3526afc8b620)


We have Uploaded Photo Successfully.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-12-29 04:59
Hi @kkrafts,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38293#issuecomment-1859627855 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by kkrafts** [comment] 2023-12-29 17:44
Al set, I solved the problem.
[image: photo] <https://kingstonkrafts.com>

Robyn
Owner-Mom-Wife-Furniture Lover,
Kingston Krafts

[image: icon] 401.272.0292 option 1 <401.272.0292option1>

[image: icon] www.KingstonKrafts.com

[image: icon] ***@***.***

[image: icon] 15 Industrial Rd Unit 2 Cranston, RI 02920
<https://maps.google.com/?q=15+Industrial+Rd+Unit+2+Cranston,+RI+02920>

[image: facebook]
<https://business.facebook.com/latest/self_view?asset_id=512110988805466&business_id=2387380867990841&nav_ref=bizweb_landing_login_button&tab=facebook>

[image: instagram] <https://www.instagram.com/kingstonkrafts/>

[image: pinterest] <https://www.pinterest.com/KingstonKrafts/>

[image: Meeting Button App] <https://calendly.com/kingston-krafts/30min>

[image: __tpx__]

**Comment by engcom-Bravo** [comment] 2024-01-02 05:50
Hi @kkrafts,

Thanks for your update.

Since the issue has been resolved We are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-01-02 05:50 UTC
Labels: Issue: needs update, Reported on 2.4.x
