### ISSUE TITLE
app:config:import stop when retrieve a warning or notice on php code

### ISSUE THREAD

**Issue by rubenpurple** [magento/magento2#31428] opened 2020-12-23 14:04 UTC
Hello, im trying to configure the pipeline system of Magento 2.4.

In the production system, the last step, i do the next commands:

/usr/local/bin/php bin/magento app:config:import
/usr/local/bin/php bin/magento setup:upgrade --keep-generated

As the documentation says. The problem, is when import the config.php file, i get the next error:

![image](https://user-images.githubusercontent.com/60217290/103002412-287d1e80-452f-11eb-9c4a-4f981193ecb4.png)

looking at the code:

![image](https://user-images.githubusercontent.com/60217290/103002482-49de0a80-452f-11eb-9c68-4bfd4f35ac24.png)

The $time variable, get null from function:  $this->getData('groups/productalert_cron/fields/time/value');

I changed the code so that if it is null, I left a zero as the value.

Then i try again, and now get the next error:
![image](https://user-images.githubusercontent.com/60217290/103002396-1bf8c600-452f-11eb-8d59-8e601ba2872f.png)

When i saw that error is a warning, i try to disable error_reporting in app/bootstrap.php:
//error_reporting(E_ALL);   

and now, the import works fine.
![image](https://user-images.githubusercontent.com/60217290/103002385-14d1b800-452f-11eb-8230-32200825f082.png)

I don't understand why I get these errors, caused by the values ​​returned by the functions, which are null.

I checked my database and config.php file, if I have the requested value:
![image](https://user-images.githubusercontent.com/60217290/103002809-e4d6e480-452f-11eb-922b-8af2b540ec18.png)
![image](https://user-images.githubusercontent.com/60217290/103002833-ec968900-452f-11eb-875c-12454bda3009.png)

now i have the doubt if avoiding error_reporting works fine the import function.

Reggards.

### Additional Information 
- steps to reproduce with additional details https://github.com/magento/magento2/issues/31428#issuecomment-866144213
- steps used for confirmation https://github.com/magento/magento2/issues/31428#issuecomment-866872060

**Comment by engcom-Delta** [comment] 2021-01-21 19:45
Hi @rubenpurple  thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Manual testing scenario:**

- Enable `error_reporting` in app/bootstrap.php:

```error_reporting(E_ALL);
ini_set('display_errors', 1);
```

- Add code into config.php:
```'crontab' => [
        'default' => [
            'jobs' => [
                'sitemap_generate' => [
                    'schedule' => [
                        'cron_exp' => '0 0 * * *',
                    ],
                ],
                'catalog_product_alert' => [
                    'schedule' => [
                        'cron_exp' => '0 0 * * *',
                    ],
                    'run' => null,
                ],
            ],
        ],
    ],
```

- Run `bin/magento app:config:import`

**Result:**
:heavy_check_mark: Import is finished without errors
![image](https://user-images.githubusercontent.com/51681379/105403629-a36e4d80-5c31-11eb-88dd-4447bf3c86e5.png)

Are my steps correct or something was missed?

**Comment by metadan** [comment] 2021-01-22 13:53
I have this same issue whilst doing a site upgrade from 2.3.5 to 2.4

**Comment by rubenpurple** [comment] 2021-01-25 07:13
Hello, i was talking with my partner, and the magento was 2.3.4 upgrade to 2.4.

Its possible that the error only happens when upgrade? but not with clean new installation of 2.4 version?

**Comment by barbazul** [comment] 2021-03-19 14:37
This is actually a very big bug.

AFAIK it affects the following areas:

* Scheduled Import/Export Log Cleaning
* Product Alert Cron
* Sitemap Generation

The issue is that the same value being exported by `app:config:dump` cannot be read by `app:config:imoprt`, completely breaking the whole shared configuration deployment pipeline.

So far, the workaround we are using is 

* Run `magento app:config:dump`
* Manually comment out the `time` and `frequency` settings in the resulting `config.php` file
* Run `magento app:config:import` (to sync dev environment with updated configuration)
* Commit fixed `config.php`
* Push (then the whole pipeline runs...)

**Comment by hostep** [comment] 2021-06-04 06:19
Leaving a comment to prevent the stalebot from closing this automatically

**Comment by engcom-Hotel** [comment] 2021-06-10 15:02
Hi @rubenpurple,

We have checked this issue in Magento CLI 2.4.2-p1 with steps mentioned in the portal (https://devdocs.magento.com/guides/v2.4/config-guide/deployment/pipeline/technical-details.html). But the issue is not reproducible. We are going through with below steps:
1. Start maintenance mode
2. bin/magento app:config:import to import configuration changes.
3. bin/magento setup:upgrade --keep-generated to update the database schema and data, preserving generated static files.
But the issue is not reproducible. Please let us know if we missed anything.

**Comment by barbazul** [comment] 2021-06-17 13:07
Steps to reproduce are the following:

1. Fresh Magento 2.4.2-p1 installation
2. Make configuration changes via admin panel (for instance, change store name)
3. Run `bin/magento app:config:dump`
4. Make changes to config.php (for instance, change store name to something different)
5. Run `bin/magento app:config:import`

**Comment by hostep** [comment] 2021-06-22 16:31
Also ran into this problem today.

Steps to reproduce on latest `2.4-develop`:

1. Setup clean Magento from 2.4-develop branch (I've used commit f121ac83597)
2. After Magento is up and running, execute `bin/magento app:config:dump`
3. Manually change the `app/etc/config.php` file like this:
```diff
--- app/etc/config.php.orig   2021-06-22 18:28:35.000000000 +0200
+++ app/etc/config.php  2021-06-22 18:28:42.000000000 +0200
@@ -1302,8 +1302,8 @@
                 ],
                 'generate' => [
                     'enabled' => '0',
-                    'time' => null,
-                    'frequency' => null,
+                    'time' => '03,07,00',
+                    'frequency' => 'D',
                     'error_email_identity' => 'general',
                     'error_email_template' => 'sitemap_generate_error_email_template',
                 ],
@@ -4023,7 +4023,7 @@
                     'jobs' => [
                         'sitemap_generate' => [
                             'schedule' => [
-                                'cron_expr' => '0 0 * * *',
+                                'cron_expr' => '7 3 * * *',
                             ],
                         ],
                     ],
```
4. Try to import those changes by using: `bin/magento app:config:import`
5. You now get this error in the output:

```
Processing configurations data from configuration file...
Import failed: Notice: Trying to access array offset on value of type null in app/code/Magento/Cron/Model/Config/Backend/Sitemap.php on line 78
```

**Comment by engcom-Hotel** [comment] 2021-06-23 14:12
Hi @barbazul,

I have tried to reproduce this issue in 2.4.2-p1 and 2.4-develop, using below steps:
1. Setup and run Magento
2. Execute bin/magento app:config:dump
3. Make changes in ./app/etc/config.php as stated by @hostep 
4. Execute bin/magento app:config:import

We are getting below error:

<img width="1440" alt="Screenshot 2021-06-23 at 7 41 37 PM" src="https://user-images.githubusercontent.com/51681618/123112202-27d03100-d45b-11eb-9f7b-a54175ef937b.png">

**Comment by magento-engcom-team** [comment] 2021-06-23 14:13
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42706` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by barbazul** [comment] 2021-07-15 12:49
@engcom-Hotel  Yes I ran into that one as well. Its a different head for the same monster. This one is a little easier to work around as you can actually change the value of the offending config from `'[]'` to `[]`.

The issue is explained more thotoughly in https://github.com/magento/magento2/issues/12298

**Comment by waynetheisinger** [comment] 2021-08-06 15:22
Big issue for pipeline...

**Comment by cmuench** [comment] 2021-10-08 10:37
> Big issue for pipeline...

Same here. Gitlab-CI failed. We always to a fresh installation to test the setup process.

**Comment by cmuench** [comment] 2021-10-08 10:44
> white_check_mark Jira issue https://jira.corp.magento.com/browse/AC-988 is successfully created for this GitHub issue.

@sidolov Not very transparent. How can we see the internals here? Maybe you can share more information.

**Closed as completed** 2021-10-26 15:19 UTC
Labels: Component: ImportExport, Issue: Confirmed, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P1, Severity: S3, Progress: done, Area: Import / export

**Comment by cmuench** [comment] 2021-11-11 08:48
@sidolov Any chance to publish an official quality patch for that issue?

**Comment by sidolov** [comment] 2021-11-22 17:17
Hi @cmuench! You may create a pull request to 2.3.7-release or 2.4.3-release branch to deliver the patch, or use https://github.com/magento/quality-patches/ repo directly

**Comment by densen45** [comment] 2022-01-14 11:57
I experienced that the merge that @hostep referenced in https://github.com/magento/magento2/issues/31428#issuecomment-952079113 solves only part of the issue. 

After applying the modifications to the Alert.php and Sitemap.php I get the following error:
```
Import failed: Notice: Trying to access array offset on value of type null in [..]/vendor/magento/module-config/Model/Config/Backend/Currency/Cron.php on line 66
```

The changes applied to the Alert.php and Sitemap.php need to be applied to the Cron.php as well.
```
-            (int)$time[1],                                 # Minute
-            (int)$time[0],                                 # Hour
+            (int)($time[1] ?? 0),                                 # Minute
+            (int)($time[0] ?? 0),                                 # Hour
```

Has anyone else experienced this?

**Comment by Aquive** [comment] 2022-08-12 10:57
@densen45 works, thanks!

In addition I got the following error:

`application/vendor/amasty/module-xml-google-sitemap/Model/Config/Cron.php on line 52`

The fix is the same:
```
-            (int)$timeConfig[1],
-            (int)$timeConfig[0],
+           (int)($timeConfig[1] ?? 0),
+           (int)($timeConfig[0] ?? 0),
```

**Comment by hostep** [comment] 2022-08-12 11:10
@Aquive: can you notify Amasty about this and reference this issue in your ticket, so they know what this is about and they can fix it as well on their end, thanks! 🙂 

@densen45: could you create a new issue for this here on github? It appears Adobe forgot to fix it for currency rates update cronjob. Thanks! 🙂

**Comment by dossy** [comment] 2023-12-20 03:06
I just ran into this issue with `Magento\ScheduledImportExport\Model\System\Config\Backend\Logclean\Cron` (`vendor/magento/module-scheduled-import-export/Model/System/Config/Backend/Logclean/Cron.php`), and found this issue.

Here's a patch for anyone else who needs it:

```
--- vendor/magento/module-scheduled-import-export/Model/System/Config/Backend/Logclean/Cron.php.orig    2023-12-20 02:52:12.287897448 +0000
+++ vendor/magento/module-scheduled-import-export/Model/System/Config/Backend/Logclean/Cron.php 2023-12-20 03:05:54.156095976 +0000
@@ -55,8 +55,14 @@
      */
     public function afterSave()
     {
-        $time = $this->getData('groups/magento_scheduled_import_export_log/fields/time/value');
-        $frequency = $this->getData('groups/magento_scheduled_import_export_log/fields/frequency/value');
+        $time = $this->getData('groups/magento_scheduled_import_export_log/fields/time/value') ?:
+            explode(',', $this->getValue());
+        $frequency = $this->getData('groups/magento_scheduled_import_export_log/fields/frequency/value') ?:
+            $this->_config->getValue(
+                'system/magento_scheduled_import_export_log/frequency',
+                $this->getScope(),
+                $this->getScopeId()
+            );
 
         $frequencyDaily = \Magento\Cron\Model\Config\Source\Frequency::CRON_DAILY;
         $frequencyWeekly = \Magento\Cron\Model\Config\Source\Frequency::CRON_WEEKLY;
```
