### ISSUE TITLE
Error while creating a scheduled update for bundle product within store view scope

### ISSUE THREAD

**Issue by gnumus** [magento/magento2#38281] opened 2023-12-13 16:07 UTC
### Preconditions and environment

- Magento version: EE 2.4.6-p3
- 2+ websites, stores, store views 
- Price scope: website
- Have a bundle product with Dynamic price "On" (can be reproduced using the bundle from sample data)

### Steps to reproduce

In admin area:
- Open the bundle product for editing
- Switch to a store view scope
- Click "Schedule new update"
- Set title and time for the update
- Some product attributes can be changed (however, I can reproduce with no changes in attributes)
- Click "Save"

### Expected result

Product's content change is scheduled

### Actual result

An error message "Could not save child" appears, please see screenshot

![msedge_OoPTju38rx](https://github.com/magento/magento2/assets/22933058/c1b3107f-a101-439b-9682-38c9115821c8)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-12-28 04:10
Hi @gnumus 

Thanks for reporting and collaboration.
Verified the issue in magento developer instance and the issue is not reproducible.
The products content change is getting scheduled. we are not seeing the error while creating a schuduled update for bundle products.
Please refer the screenshots.
<img width="1440" alt="38281" src="https://github.com/magento/magento2/assets/60198592/bb4e592b-722a-4c05-858c-bca705b67162">

**Comment by gnumus** [comment] 2024-01-02 20:39
Hi @engcom-Dash 

Could you please make sure that you have several websites on your instance, price scope is set to "Website":
![paW9NfJRyJ](https://github.com/magento/magento2/assets/22933058/88d8c286-dbe9-4b79-b69f-d09eb1ef38d4)
![msedge_8gxEceyvPn](https://github.com/magento/magento2/assets/22933058/82bf4293-f5ae-40d7-b1a0-43efcea7bb7f)

I recorded a video with the bug on clear 2.4.6-p3 + Sample data: 

https://github.com/magento/magento2/assets/22933058/6c785f8c-ca1c-4f1b-bcba-b6abe1ec242e

Thanks

**Comment by engcom-Dash** [comment] 2024-01-11 13:40
Hi @gnumus 

Thanks for reporting and collaboration.

Verified the issue on magento dev instance but the issue is not reproducable.

As per the previous comment we have set the price scope to website and tried to schedule update. Able to schedule update for a bundle product successfully.

Please refer the attached screen recording.


https://github.com/magento/magento2/assets/60198592/3d845dc7-86b8-466f-bc9b-7aec811840a6

**Comment by engcom-Dash** [comment] 2024-01-25 06:28
Hi @gnumus 

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2024-01-25 06:28 UTC
Labels: Issue: needs update, Adobe Commerce, Reported on 2.4.6-p3
