### ISSUE TITLE
Installation Ext. on Magento

### ISSUE THREAD

**Issue by Tdyok** [magento/magento2#30206] opened 2020-09-26 16:51 UTC
### Preconditions (*)

1. i can't install the Ext. on magento & integration API doesnt work too.
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. ![Capture](https://user-images.githubusercontent.com/29939856/94345830-ec7f0e00-0052-11eb-8b41-c9e6d43f6810.JPG)

**Comment by ihor-sviziev** [comment] 2020-09-27 10:25
Hi @Tdyok,
Could you add more info what steps to reproduce, which magento version, what do you expect and what is happening ?

**Comment by ihor-sviziev** [comment] 2020-10-12 12:11
Hi @Tdyok,
Unfortunately we didn't get any responce for a long time from you and we need close this issue as we can't reproduce it.
If this issue still relevant - please provide us more information and re-open the issue.

**Closed as completed by ihor-sviziev** 2020-10-12 12:11 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid, Progress: done
