### ISSUE TITLE
Forcing sample data 

### ISSUE THREAD

**Issue by magetraining** [magento/magento2#2891] opened 2016-01-05 20:16 UTC
When taking a version of Magento2 and installing without sample data (I used both the zip from the Magento download and the git repo) I get the following error

```
[ERROR] exception 'LogicException' with message 'Unknown module in the requested list: 'Magento_BundleSampleData'' in /chroot/home/magetrai/magento2.magetraining.com/magento2/setup/src/Magento/Setup/Model/Installer.php:401
Stack trace:
#0 /chroot/home/magetrai/magento2.magetraining.com/magento2/setup/src/Magento/Setup/Model/Installer.php(362): Magento\Setup\Model\Installer->readListOfModules(Array, Array, 'enable_modules')
#1 
```

I can install on my Local and on Amazon without issue, it is only on Nexcess. Nexcess has told me to open the issue here.

**Comment by miguelbalparda** [comment] 2016-01-05 20:43
To add some more info to the issue, we were able to install Magento 2 + Sample data in the same server without issues. 
We keep seeing the error despite the fact there is not a single occurrence of BundleSampleData in the code we are downloading. 
From what we see in the error it seems to be a list of modules to install and it seems the Magento_BundleSampleData module is being added to that list despite the fact this is a non sample data install. 
How is this list built? I've seen this issue here too magento.stackexchange.com/questions/92582/magento2-installing-problem

**Comment by ghost** [comment] 2016-01-05 22:26
`magento/module-bundle-sample-data` is a sample data module; they might be the same thing.

Are you on Nexcess also?

**Comment by magetraining** [comment] 2016-01-05 22:34
Yes this is happening on Nexcess only and Miguel is a dev at Nexcess

**Comment by alankent** [comment] 2016-01-05 23:22
Could you do a grep -r for both "bundle-sample-data" and "BundleSampleData" on the whole directory tree?  My guess is the root composer.json or composer.lock file has a bundle-sample-data reference still, or BundleSampleData is still in the app/etc/config.php file.

**Comment by davidalger** [comment] 2016-01-06 01:18
@miguelbalparda is this on a shared server or a dedicated box?

**Comment by miguelbalparda** [comment] 2016-01-06 11:50
It is a shared server @davidalger.
@alankent I've found 

```
[magetrai@sip3-226 m2]$ find . -type f -exec grep -F -n -H -A 2 -T "module-bundle-sample-data" {} \;
./composer.lock:1329   :                "magento/module-bundle-sample-data": "Sample Data version:100.0.*",
./composer.lock-1330   -                "magento/module-webapi": "100.0.*"
./composer.lock-1331   -            },
./vendor/magento/module-bundle/composer.json:  24      :        "magento/module-bundle-sample-data": "Sample Data version:100.0.*"
./vendor/magento/module-bundle/composer.json-  25      -    },
./vendor/magento/module-bundle/composer.json-  26      -    "type": "magento2-module",
./vendor/composer/installed.json:3913  :            "magento/module-bundle-sample-data": "Sample Data version:100.0.*",
./vendor/composer/installed.json-3914  -            "magento/module-webapi": "100.0.*"
./vendor/composer/installed.json-3915  -        },

```

after a fresh unzip. Every occurrence is like

```
        "suggest": {
            "magento/module-bundle-sample-data": "Sample Data version:100.0.*",
            "magento/module-webapi": "100.0.*"
        },

```

but it keeps trying to install it. Any ideas?

**Comment by ajay09Payal** [comment] 2016-01-09 20:18
i am also getting the same issue and i am on shared server (aws)

**Comment by mazhalai** [comment] 2016-01-20 15:31
@miguelbalparda @magetraining did you have a clean db with no previous installation?  is it possible db had details of previously installed modules?

**Comment by miguelbalparda** [comment] 2016-01-20 15:34
We used a clean db every time we had this problem @mazhalai.

**Comment by mazhalai** [comment] 2016-01-20 15:53
@miguelbalparda one last question, did you see this error on CLI or Web? If it was on Web, did you clean browser cache, especially if you installed sample data earlier. Possibly list of modules was stored in localstorage.

**Comment by miguelbalparda** [comment] 2016-01-20 15:55
Web @mazhalai. We cleared cache multiple times and even installed it from incognito windows + different machines.

**Comment by mazhalai** [comment] 2016-01-20 20:27
@miguelbalparda our QA encountered this same problem, but when we cleaned all data in the browser(chrome) related to that URL, (not just cleaning cache and cookies) but going to `settings->advanced options->Privacy->content settings->all cookies and site data->` then look for your local site and clear everything for it, it worked fine as usual. Also, another way to check is in the "Customize your store" step, click on "Advanced Modules Configurations" and check if sample data modules are listed there. If you first installed sample data, even if you used incognito windows in the same browser, with the same url, it would have stored some data.

**Comment by miguelbalparda** [comment] 2016-01-21 12:41
@magetraining can you try what @mazhalai suggested?

**Comment by cgrechcw** [comment] 2016-01-28 15:16
I can confirm that clearing browser cache (chrome) - or incognito mode- solves the issue in my case

**Comment by mazhalai** [comment] 2016-02-11 23:36
@miguelbalparda  @magetraining can we close this issue?

**Comment by sshrewz** [comment] 2016-02-26 23:02
As we have not heard from you for quite some time, we will go ahead and close this issue.  Feel free to reopen it if you have any updates.

**Closed as completed by sshrewz** 2016-02-26 23:02 UTC
