### ISSUE TITLE
Magento 2 import with images is failing

### ISSUE THREAD

**Issue by kbrakband** [magento/magento2#10235] opened 2017-07-13 13:13 UTC
### Preconditions
1. Magento 2.1.3
2. PHP 7

### Steps to reproduce
I'm trying to import a CSV file with new products that contain local images but I am receiving the following error:
_Imported resource (image) could not be downloaded from external resource due to timeout or access permissions in row(s):
General system exception happened
URL-key for specific store already exists._

I've read a lot but nothing seems to work. Note that every time I did a failed import I truncated the product tables in database. This is what I've tried/already did:

1. The images are in the pub/media/import folder as the documentation tells us to
2. I've changed the chmod of these images to 777 just in case
3. The csv file is UTF-8
4. The image doesn't contain the path in the CSV, just the file name (e.g. 12356.jpg)
5. Checked my categories to make sure they match the existing categories in my store
6. Tried adding other image fields as well instead of just 'base_image' as I did at first to make sure I wasn't missing required fields
7. Turned the CSV file into one line to check if this would work (which it didn't)

**Comment by AlexWorking** [comment] 2017-07-24 14:56
Hello @arvenzis. An internal ticket has been created - MAGETWO-70967 that is based on Your issue. As the bug is fixed You will be informed about it. Thanks for applying.

**Comment by magento-engcom-team** [comment] 2017-10-09 14:30
@arvenzis, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-09 14:30 UTC
Labels: Issue: Ready for Work, bug report, Component: ImportExport, Issue: Clear Description, Issue: Confirmed, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid
