### ISSUE TITLE
 order with invoice status pending get closed after shipping #34055 

### ISSUE THREAD

**Issue by onlinebizsoft** [magento/magento2#35769] opened 2022-07-14 09:07 UTC
### Preconditions and environment

- Magento version : 2.4.4
- Order with invoice with pending status
- Order have shipment

### Steps to reproduce

1. Place an order
2. Create an invoice
3. Edit the database to set status pending for invoice, set paid amount zero for the order and invoice
4. Ship the order

### Expected result

The order should be Processing (or Completed)

### Actual result

The order gets closed

### Additional information

Many discussion here already https://github.com/magento/magento2/issues/34055

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by MabidAlinaqvi** [comment] 2022-07-15 10:23
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment] 2022-07-19 13:22
As per our internal discussion closing this issue as it is duplicate of this [issue](https://github.com/magento/magento2/issues/34055).

**Closed as completed by engcom-Lima** 2022-07-19 13:22 UTC
Labels: Component: Shipping, Issue: Confirmed, Reproduced on 2.4.x, Area: Order
