### ISSUE TITLE
No ability to switch Store View. Store cookie not deleted for default store views with multistore setup.

### ISSUE THREAD

**Issue by artmouse** [magento/magento2#37666] opened 2023-06-26 10:28 UTC
### Preconditions and environment

A vanilla installation of Magento 2.4.6-p1 with default settings.

1. Set up Magento 2 multiple websites in sub directories
2. The site exists and opens as / by default.
3. The default language of the site is English.
4. You need to add German language to the site (set up the multi-language store).
5. The German language should be available as /de/.
6. Setup [instruction](https://gist.github.com/thagxt/0f605f0a8a95c79302db0d2f04383788)
7. In the future the German store should open by default. (Make the German Store View the default).

**Stores and Web Site Configuration:**

**Web Site information:**  
- Name: Main Website
- Code: base
- Sort Order: 0
- Default Store: Main Website Store

**Store information:**  
- Name: Main Website Store
- Code: main_website_store
- Root Category: Default Category
- Default Store View: English

### Steps to reproduce

***Add second Store View and change the values of the main Store View for clarity***

**English Store View (default) information:**  
- Store: Main Website Store
- Name: English
- Code: en
- Status: enabled
- Sort Order: 10

**German Store View information:**  
- Store: Main Website Store
- Name: German
- Status: enabled
- Code: de
- Sort Order: 20

***For the German store, you need to create a subdirectory in the pub, so that it can be accessed at /de/ and assign a proper URL.***

- Create a subdirectory /de/ in the pub.
- Place the modified index.php in /de/ directory

```diff
+$params = $_SERVER;  
+$params[\Magento\Store\Model\StoreManager::PARAM_RUN_CODE] = 'de';
+$params[\Magento\Store\Model\StoreManager::PARAM_RUN_TYPE] = 'store';  
+$bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $params);
-$bootstrap = Bootstrap::create(BP, $_SERVER);
```

- Allow NGINX to execute index.php file from the /de/ directory.

```diff
# PHP entry point for main application
+location ~ (index|get|static|errors/report|errors/404|errors/503|health_check)\.php$ {
-location ~ ^/(index|get|static|errors/report|errors/404|errors/503|health_check)\.php$ {
```

***For Static and Media View Files, you will need to globally change the URL to something like this: https//domain.com/static/(media/) so that the styles would be available in /de/ as well.***

- Stores -> Configuration -> General -> Web (Scope: Default Config)
	- Base URLs
		- Base URL for Static View Files: https//domain.com/static/
		- Base URL for User Media Files: https//domain.com/media/
	- Base URLs (Secure)
		- Secure Base URL for Static View Files: https//domain.com/static/
		- Secure Base URL for User Media Files https//domain.com/media/

***Specify a URL for the German store with the prefix /de/.***

- Stores -> Configuration -> General -> Web (Scope: German Store View)
	- Base URLs
		- Base Link URL: https//domain.com/de/
	- Base URLs (Secure)
		- Base Link URL: https//domain.com/de/

***Change the main Store View for Store to German. (make it default)***

- Stores -> Settings -> All Stores -> Store (Main Website Store)
	- Change Default Store View: en -> de

Going to the site... 
- [x] Now by default we are redirected to /de/ and the site opens in German (Default, Store View Code: de). Great!
- [x] The site also displays a language switcher.
- [x] Switching to English (Store View Code: en) - redirect to / and the language changes.
- [ ] Switch back to German (Default, Store View Code: de) - redirect to /de/ but language does not change, English remains. In the same way all store URLs without the prefix /de/.

### Expected result

There is no "store" cookie for the primary Store View.
When the primary Store View (de) is located on the /de/ path and when you switch to another Store View (en) that is located on the / path, the "store" cookie is set for the target Store View (en).

| Name | Value | Domain | Path |
| --- | --- | --- | --- |
| store | en | .domain.com | / |

And when switching from another Store View (en) when the "store" cookie is already set, it checks to match the target Store View ID with the default Store View ID.
If there is a match, the "store" cookie should be removed.

https://github.com/magento/magento2/blob/35e8e434be0b21072382b3f91c71678efc0242c1/app/code/Magento/Store/Model/StoreSwitcher/ManageStoreCookie.php#L58-L71

But when try to delete the store cookie in $cookieMetadata set the path /de, but existing "store" cookie has path /.

https://github.com/magento/magento2/blob/35e8e434be0b21072382b3f91c71678efc0242c1/app/code/Magento/Store/Model/StoreCookieManager.php#L72-L78

getStorePath() returns /de, but the "store" cookie has a path / - perhaps because of this the "store" en cookie is not deleted and the site always stays on Store View (en)

https://github.com/magento/magento2/blob/35e8e434be0b21072382b3f91c71678efc0242c1/app/code/Magento/Store/Model/Store.php#L1373-L1378

### Actual result

1. When the primary Store View (de) is located on the /de/ path and when you switch to another Store View (en) that is located on the / path, the "store" cookie is set for the target Store View (en).
2. And when switching from another Store View (en) when the "store" cookie is already set, it checks to match the target Store View with the default Store View ID.
3. If there is a match, the "store" cookie should be removed.

### Additional information

Similar problem: https://github.com/magento/magento2/issues/8509

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2023-07-13 13:37
Hello @artmouse,

Thanks for the report and collaboration!

We have tried to reproduce the issue in 2.4-develop instance via the following link.
https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/multi-sites/ms-admin.html

In order to reproduce this issue we have cretaed two store views, `en` and `de` and make `de` as default store view.
We are able to get the expected result, for `de` store there is no cookie but for `en` store cookie is there, Please have a look at the scrreenshot below:
**For `de` store there is no cookie**
![image](https://github.com/magento/magento2/assets/60198231/6e60d3ad-7a2b-4296-ad03-1a2e9af88ec1)

**Fot `en` store cookie is visible with name store**
![image](https://github.com/magento/magento2/assets/60198231/f54f38a6-5455-4cd1-aa1c-f6b5f9089ad9)

Please let us know if we missed anything in order to reproduce the issue.

Thanks.

**Comment by artmouse** [comment] 2023-07-13 13:46
You didn't read the description carefully.
Here the specific task is not to use store codes, but to use subdirectories instead.
Main storeview /de/
Second storeview /

**Comment by engcom-November** [comment] 2023-07-14 07:53
Hello @artmouse,

Thank you for your quick response!

As I can understand with the main desription, you need to setup multistore/multiwebsite in your magento instance.
For this you can follow the below official documetnation provided by magento.
https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/multi-sites/ms-admin.html

If you still want to setup store views in sub directories via following the below link :
[instruction](https://gist.github.com/thagxt/0f605f0a8a95c79302db0d2f04383788)

You need to provide us the use case for the same.

Thank you.

**Comment by engcom-November** [comment] 2023-08-29 13:03
Hello @artmouse,

We have noticed that this issue has not been updated since long time. Hence we assume that the issue is fixed now, so we are closing it. Please feel free to raise a new one or reopen this issue if you need more assistance.

Thanks.

**Closed as completed by engcom-November** 2023-08-29 13:03 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.6-p1
