### ISSUE TITLE
Incorrect constructor of Magento\Sales\Model\Order\Address\Validator

### ISSUE THREAD

**Issue by Bartlomiejsz** [magento/magento2#21692] opened 2019-03-11 15:17 UTC
### Summary (*)
Tested on 2.3, but exactly same logic is included in this constructor on 2.2-develop branch.
Constructor of `Magento\Sales\Model\Order\Address\Validator` includes logic and should not. The reason of it is that if this class is injected in constructor in Cli Command in some custom module, installation of Magento fails.

### Examples (*)

1. Add custom module with Cli Command in which `Magento\Sales\Model\Order\Address\Validator` is injected
2. Try to install Magento from scratch using Cli.
3. See following error: `Base table or view not found: 1146 Table 'database.eav_entity_type' doesn't exist, query was: SELECT `main_table`.* FROM `eav_entity_type` AS `main_table`"`

### Proposed solution
I'm preparing PR for this one.

**Comment by magento-engcom-team** [comment] 2019-03-11 15:18
Hi @Bartlomiejsz. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Bartlomiejsz do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-03-12 07:45
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-03-12 09:40
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98657` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by MaksymGrom** [comment] 2019-03-22 15:10
@Bartlomiejsz Hello, CLI in Magento loads all Command classes and them injections
So you should use Proxy to avoid loading Repositories and other classes with the same problem
Please change your injection. (while issue is not resolved)
Magento\Sales\Model\Order\Address\Validator => Magento\Sales\Model\Order\Address\Validator\Proxy

Also, you can change the injection attribute via di.xml.
You can see this way in [\Magento\Catalog\Console\Command\ImagesResizeCommand](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Catalog/Console/Command/ImagesResizeCommand.php)
[magento/module-catalog/etc/di.xml:557](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Catalog/etc/di.xml)

**Comment by Bartlomiejsz** [comment] 2019-03-22 22:30
@MaksymGrom you're right, it can be handled using proxy, but still such logic should not be included in constructor so I hope it will be merged soon.
Thank you for response!

**Comment by magento-engcom-team** [comment] 2019-03-25 13:53
Hi @Bartlomiejsz. Thank you for your report. 
The issue has been fixed in magento/magento2#21693 by @Bartlomiejsz in 2.3-develop branch
Related commit(s):
 - [28b047ec570fce2752960668e5b4e6eda21593b4](https://github.com/magento/magento2/commit/28b047ec570fce2752960668e5b4e6eda21593b4)
 - [b92ffa24299d32b62d2a211aa7756d866ad13154](https://github.com/magento/magento2/commit/b92ffa24299d32b62d2a211aa7756d866ad13154)
 - [fda4377384169d385a04057e7edf2f1ac32bc5ec](https://github.com/magento/magento2/commit/fda4377384169d385a04057e7edf2f1ac32bc5ec)
 - [b2004c3f74f7cdd2654986f056f6ba8d8beaa5ee](https://github.com/magento/magento2/commit/b2004c3f74f7cdd2654986f056f6ba8d8beaa5ee)
 - [b86f981ad04f63c7ca8d2c3ca5f3b4abe999ca4d](https://github.com/magento/magento2/commit/b86f981ad04f63c7ca8d2c3ca5f3b4abe999ca4d)
 - [73d88aaeaa7da30c68608d7f048b7b88557e936d](https://github.com/magento/magento2/commit/73d88aaeaa7da30c68608d7f048b7b88557e936d)
 - [9c7fbfdc24380fc3174d313bcf5c12ca381e9313](https://github.com/magento/magento2/commit/9c7fbfdc24380fc3174d313bcf5c12ca381e9313)
 - [e09429f7cca09d91245c0999cb043e7845d4fa74](https://github.com/magento/magento2/commit/e09429f7cca09d91245c0999cb043e7845d4fa74)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-25 13:53 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by magento-engcom-team** [comment] 2019-03-29 16:10
Hi @Bartlomiejsz. Thank you for your report. 
The issue has been fixed in magento/magento2#21719 by @Bartlomiejsz in 2.2-develop branch
Related commit(s):
 - [068eedf0b8fb069df8e8432e8b78d3a0dff33110](https://github.com/magento/magento2/commit/068eedf0b8fb069df8e8432e8b78d3a0dff33110)
 - [8a4cfa4eac8b5d18d1c9b30655dbacabce9d9d53](https://github.com/magento/magento2/commit/8a4cfa4eac8b5d18d1c9b30655dbacabce9d9d53)
 - [43cc9a4d3ab36e292382ca06c8256b47452cfed3](https://github.com/magento/magento2/commit/43cc9a4d3ab36e292382ca06c8256b47452cfed3)
 - [f77f54dac19e6d9853b0e34a4bda1b39fd62fd3c](https://github.com/magento/magento2/commit/f77f54dac19e6d9853b0e34a4bda1b39fd62fd3c)
 - [cece0869efc4333abdd410f0482d0d6586a04ce8](https://github.com/magento/magento2/commit/cece0869efc4333abdd410f0482d0d6586a04ce8)
 - [67b1d0a12fea5f46073ca4e4133e5debd3bf6ede](https://github.com/magento/magento2/commit/67b1d0a12fea5f46073ca4e4133e5debd3bf6ede)

The fix will be available with the upcoming 2.2.9 release.
