### ISSUE TITLE
Remove compare product option is not working for out of stock products in magento2.3.2

### ISSUE THREAD

**Issue by sudheers-kensium** [magento/magento2#24582] opened 2019-09-13 08:32 UTC
### Preconditions (*)

1. Magento 2.3.2
2.

### Steps to reproduce (*)

1. Create simple product in admin
2. Go to frontend and add product to compare list
3. Change product stock status from In Stock to Out Of Stock and save
4. Change admin configuration "Display Out of Stock Products" to "Yes" under Catalog -> Inventory -> Stock Options
5. Go to frontend compare list, **_reload the page_**, and remove out of stock product from compare list (not working)

### Expected result (*)

1. It should remove from compare list and show message You removed product <product name> from the comparison list.

### Actual result (*)

1. Product not removed from compare list

**Comment by magento-engcom-team** [comment] 2019-09-13 08:32
@sudheers-kensium Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-09-13 09:04
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20141` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by cristhianss** [comment] 2019-09-14 14:10
#mm19br

**Comment by magento-engcom-team** [comment] 2019-09-14 14:10
@cristhianss thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by cristhianss** [comment] 2019-09-14 14:41
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-09-14 14:41
Hi @cristhianss. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-09-14 14:41
Hi @cristhianss, here is your [Magento instance](https://i-24582-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24582-2-3-develop.instances.magento-community.engineering/admin](https://i-24582-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by cristhianss** [comment] 2019-09-14 15:03
Hi guys,
I used the instance created to reproduce the problem, but i can't reproduced.
I followed all the steps, in the step four the result is different.

When i go to the comparison page, the following message appears:
[ https://imgur.com/a/7zNA5AC ](url)

**Comment by engcom-Bravo** [comment] 2019-09-14 20:54
@cristhianss I can't really understand why You closed the issue. Look once more at the actual result: "Product not removed from compare list". And that's true. The message You are talking about ("You have no items to compare.") is a bit lying and that just proves the bug. Why lying? - because the product to compare is still there:
![compare](https://user-images.githubusercontent.com/51680745/64913370-92612280-d747-11e9-8618-9d82a86bd2bc.png)
And once You make the product to be In Stock again and get back to the frontend You'll be able to see it there:
![see](https://user-images.githubusercontent.com/51680745/64913411-68f4c680-d748-11e9-8d38-a0c3bfbefcc9.gif)
So it remains there no matter whether it is In Stock or Out of Stock.
In fact it is possible to remove it even when it is Out of Stock. For that You need not to reload the page in step 4 - the removing will be done easily just as it is supposed to be (anyway wrong behavior). Or, if You have the page reloaded in step 4 You are able to remove this product from the Comparison list by clicking on "Clear All" what is also wrong  - "You have no items to compare" but at the same time You can "Clear" them "All".
Thus I would agree with You if You said this issue needs to be expanded in description but never it should be closed.

**Comment by magento-engcom-team** [comment] 2019-09-14 20:55
@engcom-Bravo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-09-14 20:55
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20161` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krisdante** [comment] 2019-09-15 10:45
#mm19pl

**Comment by krisdante** [comment] 2019-09-15 11:06
Tuns out this is not on the #mm19pl list so I am unassigning myself for now.

**Comment by engcom-Delta** [comment] 2020-02-04 07:41
Hi @sudheers-kensium, thank you for your report. I am not able to reproduce issue by steps you described on clean 2.4-develop. 

If you'd like to update the issue, please reopen it.

**Closed as completed by engcom-Delta** 2020-02-04 07:41 UTC
Labels: Component: Catalog, Issue: Clear Description, Reproduced on 2.3.x, Issue: Format is valid, Partner: Kensium Solutions LLC, Event: mm19br, Event: mm19pl
