### ISSUE TITLE
Warning "Something went wrong" appears every time I try to edit a product

### ISSUE THREAD

**Issue by jibrandlr** [magento/magento2#6297] opened 2016-08-23 17:48 UTC
### Preconditions
1. Magento 2.1.0, php 7.0.8, ubuntu 16.04
### Steps to reproduce
1. Create a product (simple or configurable)
2. After saved, try to edit the product
### Expected result
1. The editing page displays without errors.
### Actual result
1. A pop up displays the warning: "Attention. Something went wrong."

The product can be edited and saved successfully. However the pop up appears **every time** I want to edit a product.
![something-wrong](https://cloud.githubusercontent.com/assets/8398744/17902951/1c4b499c-692f-11e6-9fb0-e43e1434e00b.jpg)

**Comment by thomvanderboon** [comment] 2016-08-23 18:44
@lgarridoj Did you disable any modules? This is a known problem if you disable the reviews module.  See https://github.com/magento/magento2/issues/6264

**Comment by jibrandlr** [comment] 2016-08-23 19:32
That's my case. I disabled the reviews module. Thanks

**Comment by thomvanderboon** [comment] 2016-08-23 20:15
@lgarridoj Please go to issue https://github.com/magento/magento2/issues/6264 and press subscribe button at bottom of right column. You will be notified when this issue has been resolved.
@veloraven Please close #6297. It is duplicate of https://github.com/magento/magento2/issues/6264

**Closed as completed** 2016-08-23 21:04 UTC
