### ISSUE TITLE
Missing title in paypal_paylater method

### ISSUE THREAD

**Issue by Minirock** [magento/magento2#36549] opened 2022-11-29 10:36 UTC
### Preconditions and environment

- Magento version : 2.4.4

- magento/module-paypal :     "version": "101.0.4",

### Steps to reproduce

- Go to order or invoice grid on magento 2.4.4 version.

### Expected result

The order grid is printed

### Actual result

We reach an error cause of the paypal_paylater payment method. 

### Additional information

Digging into it it looks like the method in `vendor/magento/module-paypal/etc/config.xml` is missing the title which is causing this issue.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-11-29 17:19
Hi @Minirock ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance but no errors were observed with below steps performed:
**Steps performed:**
1. Configured PayPal Express Checkout payment with PayPal Pay Later enabled
2. Clear cache
3. Login to Front end and made payment with Paypal Paylater
4. Admin - Sales - Orders - Grid - Payment method displayed as expected.
5. Created invoice
6. Invoices - Grid - Payment method displayed and no errors observed
7. Created Shipment - Payment method displayed in Shipments Grid.
![image](https://user-images.githubusercontent.com/60198231/204597626-dbccb514-f7fa-41ac-b30c-1404dc00ba66.png)
![image](https://user-images.githubusercontent.com/60198231/204597725-5f2b616c-87f9-4191-9f29-a964399512e9.png)
![image](https://user-images.githubusercontent.com/60198231/204597527-ec70621e-6d6e-4d78-9a45-1d29ddc90012.png)
Kindly recheck the issue on Magento 2.4-develop instance and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by Minirock** [comment] 2022-11-30 15:21
The error seems to come from this file `vendor/magento/module-paypal/etc/config.xml` . Did you check if the version and content was the same ? 

To fix it on my own i had to extend the config and add the title

```
            <paypal_paylater>
                <title>Paypal Pay Later</title>
```

**Comment by engcom-November** [comment] 2022-12-01 10:21
Hi @Minirock ,
In Magento 2.4-develop latest instance and 2.4.5-p1 project-community edition, title named as  <title>PayPal Express Checkout</title> as shown below but no title is mentioned under <paypal_paylater> in /etc/config.xml and the issue is not reproducible.Admin - Invoice or Sales order grid - payment method is displayed as "Paypal express checkout" for the payment made using Paypal Paylater experience from front-end (Paypal Paylater enabled for paypal express checkout configuration from admin) and no error messages are getting displayed in both UI and logs.
```<payment>
            <paypal_express>
                <model>Magento\Paypal\Model\Express</model>
                <title>PayPal Express Checkout</title>```
Its recommended to verify issue on magento 2.4-develop instance / having latest code base without any 3rd party extensions / modules enabled. Kindly recheck the issue on 2.4-develop instance / latest version and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by Minirock** [comment] 2022-12-01 14:56
Hi, I can't tell why this isn't reproductible ou your instance, and it's probably also due to one of our third partiy module.

Though you can't deny, checking at the following file : [magento2](https://github.com/magento/magento2)/[app](https://github.com/magento/magento2/tree/2.4-develop/app)/[code](https://github.com/magento/magento2/tree/2.4-develop/app/code)/[Magento](https://github.com/magento/magento2/tree/2.4-develop/app/code/Magento)/[Paypal](https://github.com/magento/magento2/tree/2.4-develop/app/code/Magento/Paypal)/[etc](https://github.com/magento/magento2/tree/2.4-develop/app/code/Magento/Paypal/etc)/config.xml

Everyone of the payment methods in this file have a title declared like paypal_express indeed, each one of them is right except from the last one of the file paypal_paylater which is missing the title which is causing (for unknown reason and unknown circumstances this issue).

**Comment by engcom-November** [comment] 2022-12-05 15:28
Hi @Minirock ,
Thank you for the response. I rechecked magento2/app/code/Magento/PayPal/etc/config.xml file again and agree that every payment method has a title included but since Paypal pay later is not a separate payment method but integrated with all other paypal payment methods, default main payment method used is displayed on backend order details grid page on making payment with Paypal pay later method. I rechecked the behavior again with Payflow pro payment method configured from back end and placed order using "Papal pay later" and the issue is still no reproducible. Payment method is displayed as "Payflow Pro" on back end order details and invoice Grid. Kindly check the behavior on latest magento instance / 2.4-develop instance without 3rd party modules and let us know if you are still facing any issues.
Thank you.

**Comment by Minirock** [comment] 2022-12-06 11:12
I can't reproduce neither on fresh 2.4 installation. Anyway, adding a title to the method fixed it in our case...so i can't really tell what was causing that issue. I guess this can be close, unless someone can reproduce to get an other use case.

**Comment by engcom-November** [comment] 2022-12-07 06:27
Thank you for the confirmation @Minirock . We are closing this issue. Kindly reopen / create new one if you face any issues.
Thank you.

**Closed as completed by engcom-November** 2022-12-07 06:27 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
