### ISSUE TITLE
Magento2 reindex is not working with php7

### ISSUE THREAD

**Issue by sumanparihar** [magento/magento2#2750] opened 2015-12-17 13:38 UTC
Hello,

Thanks in Advance. I got issue when i try to re-index in magento2 using command line. 

I got segment fault error. i have already assigned unlimited memory to all. i am using Ubuntu os. 

Thanks
Suman

**Comment by mazhalai** [comment] 2015-12-17 17:44
@sumanparihar I think it depends on how PHP7 was installed. Can you please give us more information on how did you install PHP7?

**Comment by sumanparihar** [comment] 2015-12-18 08:28
I follow same as php7 installation guide show.
Other thing is working fine even project speed is much better. but only re-index issue with one (catalogsearch_fulltext).

Please update me if any other way to  re-index (catalogsearch_fulltext) after ststus "Processing".

Thanks
Suman

**Comment by mazhalai** [comment] 2015-12-21 16:05
@sumanparihar maybe I should have been more specific, which php7 guide? Since you can install it via a repo on ubuntu, (AFAIK it is only available from `ppa:ondrej/php-7.0`) OR did you compile php src? Also, php 7.0.1 is available, did you try upgrading to see if your issue is fixed?

We have encountered this problem, but in CentOS. We have not been able to reproduce it on Ubuntu. We will post an update as soon as we figure out the solution. Related stackoverflow issue for CentOS : http://stackoverflow.com/questions/34343271/segmentation-fault-in-php7

**Comment by arondesign** [comment] 2015-12-22 20:59
I've been getting this as well for days, php7, installed via homebrew, osx

**Comment by al-Obaidi** [comment] 2015-12-25 18:25
Centos 7.1, PHP 7.0.1 unable to reindex via shell. segmentation fault will result destroying the database. Problem exist with Magento 2 with sample data installed. No matter whatever you make  memory limit  in php.ini.

**Comment by danslo** [comment] 2015-12-25 18:52
I have encountered this issue as well, but you should report this at php.net instead. Userland code should not be able to crash the PHP process. Magento is not at fault here.

Maybe if I have some time in the new year, and if it isn't fixed yet by then, I'll try to fix this issue.

**Comment by michsk** [comment] 2015-12-28 12:33
Im not having the issue trough cli, only trough the web ui. I've updated to 7.0.2RC but still happens.

**Comment by chrissm79** [comment] 2015-12-28 18:37
I am hitting a segmentation fault when attempting to save a product in a module I created as well as reindexing. The store has had data migrated over from v1.9.2.2 (along with products). For some reason the products are listed in the correct categories on the backend but don't show up on the frontend. The only way around it (that I've seen so far) is to resave the products. So I created a module that loops through the products, doesn't make any changes, and calls the save method.

In a vagrant box w/ PHP 7.0, I get a segmentation fault error when trying to run the code (it's a console command). I updated the memory_limit and set xdebug.max_nesting_level=300 with no joy. On my Mac w/ PHP v5.6 it ran successfully after updating the max_nesting_level in my php.ini. 

**Here's the last bit of the strace:**

``` bash
$ strace ./bin/magento mystore:product:resave
...
lstat("/home/vagrant/magento2/vendor/magento/module-eav/Model/ResourceModel/Entity/Attribute/Option.php", {st_mode=S_IFREG|0644, st_size=4520, ...}) = 0
lstat("/home/vagrant/magento2/vendor/magento/module-eav/Model/ResourceModel/Entity/Attribute", {st_mode=S_IFDIR|0755, st_size=340, ...}) = 0
lstat("/home/vagrant/magento2/vendor/magento/module-eav/Model/ResourceModel/Entity", {st_mode=S_IFDIR|0755, st_size=238, ...}) = 0
lstat("/home/vagrant/magento2/vendor/magento/module-eav/Model/ResourceModel", {st_mode=S_IFDIR|0755, st_size=272, ...}) = 0
lstat("/home/vagrant/magento2/vendor/magento/module-eav/Model", {st_mode=S_IFDIR|0755, st_size=680, ...}) = 0
open("/home/vagrant/magento2/vendor/magento/module-eav/Model/ResourceModel/Entity/Attribute/Option.php", O_RDONLY) = 8
fstat(8, {st_mode=S_IFREG|0644, st_size=4520, ...}) = 0
fstat(8, {st_mode=S_IFREG|0644, st_size=4520, ...}) = 0
fstat(8, {st_mode=S_IFREG|0644, st_size=4520, ...}) = 0
fstat(8, {st_mode=S_IFREG|0644, st_size=4520, ...}) = 0
mmap(NULL, 4520, PROT_READ, MAP_SHARED, 8, 0) = 0x7f838351a000
munmap(0x7f838351a000, 4520)            = 0
close(8)                                = 0
sendto(3, "\30\2\0\0\3SELECT `main_table`.*, `tdv"..., 540, MSG_DONTWAIT, NULL, 0) = 540
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=3, revents=POLLIN}])
recvfrom(3, "\1\0\0\1\6V\0\0\2\3def\20magento_v2\nm"..., 4910, MSG_DONTWAIT, NULL, NULL) = 556
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0x7f83711bcd40} ---
+++ killed by SIGSEGV +++
Segmentation fault
```

**PHP Code executed from console:**

``` php
/**
 * {@inheritdoc}
 */
protected function execute(InputInterface $input, OutputInterface $output)
{
    $this->state->setAreaCode('adminhtml');
    $this->objectManager->configure($this->configLoader->load('adminhtml'));
    $this->registry->register('isSecureArea', true);

    $output->writeln('<info>Getting list of products:<info>');

    try {
        $searchCriteria = $this->searchCriteriaBuilder
            ->setPageSize(1000)
            ->setCurrentPage(1)
            ->create();

        $results = $this->productRepo->getList($searchCriteria);
        $products = $results->getItems();

        foreach ($products as $product) {
            $product->save(); // This is where I hit the segmentation fault
            $output->writeln('<info>Updated Product: '. $product->getSku() .'</info>');
        }
    } catch (\Exception $e) {
        // Unfortunately, this does't work...
        $this->writeln('Caught Error:');
        $this->writeln(var_dump($e->getMessage()));
    }

    $output->writeln('<info>Updating Complete!</info>');
}
```

**Comment by michsk** [comment] 2015-12-29 10:26
@chrissm79 you probably get the issue because your reindex settings are set to "After save". So you save your product and the reindex starts. Im not sure what file it was in, but there is a `yield` somewhere in the reindexer code, it breaks on that yield.

**Comment by cscd98** [comment] 2016-01-06 13:57
Same issue with php 7.0.1 - OS X

It segfaulted, left my index_state at working and then I realized the indexer would never run again by inspecting the code.

So I re-indexed using php56.

However I am missing prices and product names in grid/list view.

**Comment by everon** [comment] 2016-01-10 23:34
Same issue here with Centos 7.x and PHP 7.0.2
Spent hours trying to debug this, strangely it worked on PHP7.0.0 on another server I deal with for work.

**Comment by al-Obaidi** [comment] 2016-01-10 23:54
Hi Everon,
I was busy trying to install php 7.0.2 to see if the problem still exist. From your comment, it seems it is unfortunately still exist.
It is PHP7 bug.
You saved my time to install the latest php7 version.
Can you tell me please what the guide/reference, you follow to install php7.0.2 with all required extensions needed by magento 2. I use latest minimal fresh Centos 7.x.
Thank you

**Comment by everon** [comment] 2016-01-11 09:27
@Ferfoor 
It was the latest Centos 7 on Digital Ocean, I used the Remi repo to get it working. As for the other server I imagine it will show up sooner or later and will just deem 7.x as a no go until it is patched up. (7.0.3 any one?).

The Remi repo can be found with a few Google searches and added to the yum repository list will yield the php70-\* packages.

**Comment by al-Obaidi** [comment] 2016-01-11 09:41
Thank you @everon  for clarification.
I will wait version 7.0.3 hoping it will be patched. I think to get fastest result, the PHP team/developers should be alert about magento 2 segmentation fault error. It might give their attention directly so they focus on the cause of bug. 

Thanks again @everon.

**Comment by cscd98** [comment] 2016-01-11 11:27
Has this been reported so that it will be fixed in 7.0.3? What is the php bug number? (e.g. link)

**Comment by al-Obaidi** [comment] 2016-01-11 11:44
Hi @craigcarnell ,
I'm not familiar with ( github - development process/community - bug reporting ...), so I may can't help. I may can tell how to reproduce this error. On Centos 7.x  if you install "magento 2" with sample data, and want to reindex via cli, a segmentation fault will result. This damage the magento database by somehow which make the whole application not working properly (not showing category/products all or some), and need to be  reinstalled. It happened with me on both Centos & Windows with php7, but with windows the application could be survived after a repeated reindexing, but I can't  trust php7 to develope a "magento 2" webstore with the current situation.

**Comment by cscd98** [comment] 2016-01-11 12:01
@Ferfoor The bug would need reporting at https://bugs.php.net/

But they won't accept Magento 2, they need specific code to reproduce the error

**Comment by mazhalai** [comment] 2016-01-20 16:05
@all PHP7 issues have been fixed in [tag 2.0.1](https://github.com/magento/magento2/tree/2.0.1) Please have a look and let us know if your issue has been fixed.

**Comment by maksymcherevko** [comment] 2016-01-21 15:32
I have the same problem, with Custome Grid and Catalog Search. After fault error they stay in "processing" status. Tried to change the status in the database (table: mr_indexer_state), then run again. Process start, but the result is the same.

![screenshot_40](https://cloud.githubusercontent.com/assets/16465396/12484816/ac46da1c-c064-11e5-8941-325c39059637.png)

**Comment by cscd98** [comment] 2016-01-21 17:10
@mazhalai I successfully re-indexed catalog search using PHP 7.0.2 and Magento 2.0.1. Cheers :+1:

**Comment by mazhalai** [comment] 2016-01-21 17:38
@craigcarnell thank you for confirming. Will close this issue. 

@maksymcherevko is your indexer issue related to php7? If not please open a new issue. if it is related to php7, please try on the 2.0.1 tag mentioned above.

@sumanparihar this issue has been confirmed fixed, so closing this issue. Please re-open if it still persists.

**Closed as completed by mazhalai** 2016-01-21 17:38 UTC
Labels: Progress: needs update

**Comment by maksymcherevko** [comment] 2016-01-22 09:40
@mazhalai , yes, php-7.0.2. Update to 2.0.1 helped. Thank's.
