### ISSUE TITLE
Simple available in more then one storeview returns 404

### ISSUE THREAD

**Issue by jorgb90** [magento/magento2#33592] opened 2021-07-26 12:04 UTC
### Preconditions (*)
1. Magento 2.4.2-p1

### Steps to reproduce (*)
1. Create an extra storeview.
2. Create a configurable with simples.
3. Take one of the generated simples and make it available to the extra storeview, set visibility for that storeview to "Catalog, Search" and add the product to a category.
4. Visit the product at the frontend of that extra storeview. It will display in the category correctly but when clicking on it you will get a 404.

### Expected result (*)
1. Not receiving a 404 for the product.

### Actual result (*)
1. 404 product not found while rewrites seems to be generated correctly.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2021-07-28 12:02
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible:
**Steps:**
1. Setup a new Store (Ex France) from Magento Admin
2. Create a Configurable Product (Visible in default store view only) from Admin - Catalog - Products - Add New Configurable Product
3. Create Configurations - Generate Products. 
Note: Products can be manually added
4. Open newly generated products from Admin - Catalog - Products - make it available to the extra store view, set Visibility to "Catalog, Search", assign Category and Save
5. Navigate to new Store view Front end Website (ex: france) - Open the generated product - **No issue: User is able to navigate to Product Details page**
@jorgb90 kindly recheck the issue on Magento 2.4-develop branch and provide exact steps to reproduce if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2021-08-11 06:36
@jorgb90, we are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-08-11 06:36 UTC
Labels: Issue:  Cannot Reproduce, Component: ConfigurableProduct, Issue: needs update, Reported on 2.4.2-p1
