### ISSUE TITLE
Increased page load time with 2.3.4

### ISSUE THREAD

**Issue by monotheist** [magento/magento2#26692] opened 2020-02-04 11:44 UTC
### Preconditions (*)

1. Magento 2.3.4
2. Varnish
3. Redis

### Steps to reproduce (*)

1. Upgrade from 2.3.3 to 2.3.4

### Expected result (*)

1. Page load either match the previous version or better

### Actual result (*)

1. Product page load is around 2700 ms while 2.3.3 delivers at 800 to 1000 ms

**Comment by devchris79** [comment] 2020-02-04 12:29
You might want to check the cache is enabled, Composer does disable it following an upgrade. I think this is due to be fixed though.

To check cache status:

`bin/magento cache:status`

To enable cache:

`bin/magento cache:enable`

**Comment by devchris79** [comment] 2020-02-04 12:33
Sorry, looks like it should be fixed in 2.3.4 #24892

**Comment by monotheist** [comment] 2020-02-04 12:38
Cache is enabled. I have also tested this in atleast 3 development instances.

**Comment by GuiltyNL** [comment] 2020-02-09 21:25
When you enable the profiler, you can see where the processing time goes to:

bin/magento dev:profiler:enable

**Comment by kurtdeserter** [comment] 2020-02-10 11:03
I can confirm performance issues with 2.3.4 and cache enabled.

**Comment by palviggi-flagbit** [comment] 2020-02-20 14:46
We had the same problem, and at least on our case we tracked it down to a high amount of "show table status like 'store';" queries, resulting from the fix in https://github.com/magento/magento2/pull/24959

it adds a constant check to see if the store tables exists, without caching, even in the same transaction.

I reverted the changes and load went back to normal

**Comment by alex9434** [comment] 2020-02-28 09:21
I can also confirm the same issue. Google Pagespeed gives me now timeouts!

**Comment by alex9434** [comment] 2020-03-01 15:09
Dear @palviggi-flagbit,
can you tell me how you did revert back the changes from the fix in #24959. I would like to do the same to reduce load times back to the previous status.
Thank you,
alex

**Comment by palviggi-flagbit** [comment] 2020-03-02 08:51
> Dear @palviggi-flagbit,
> can you tell me how you did revert back the changes from the fix in #24959. I would like to do the same to reduce load times back to the previous status.
> Thank you,
> alex

I copied the function code from the previous tag available for each file (for example https://github.com/ivan-koliadynskyy/magento2/blob/2.3.2/app/code/Magento/Store/App/Config/Source/RuntimeConfigSource.php).

Last week we learned that in our case the main problem was that our hosting service had a peculiar filesystem setup on the databases that made "SHOW STATUS" queries take 60x longer than usual, and they knew about it but didn't tell us until we raised the problem.
But you have to test it to see if it's really a fix for you. Best way is to profile your website, our profiling lead to this particular query/PR

**Comment by alex9434** [comment] 2020-03-06 15:33
> I copied the function code from the previous tag available for each file (for example https://github.com/ivan-koliadynskyy/magento2/blob/2.3.2/app/code/Magento/Store/App/Config/Source/RuntimeConfigSource.php).
> 
> Last week we learned that in our case the main problem was that our hosting service had a peculiar filesystem setup on the databases that made "SHOW STATUS" queries take 60x longer than usual, and they knew about it but didn't tell us until we raised the problem.
> But you have to test it to see if it's really a fix for you. Best way is to profile your website, our profiling lead to this particular query/PR

I can confirm that this solved the problem for me! So it seems to be the fix in #24959 that caused these issues. 

You mentioned that your hosting service hat a particular setup that made "SHOW STATUS" slow. I have a Percona Mysql on EXT4 on a SSD. Is that similar to your setup?

**Comment by palviggi-flagbit** [comment] 2020-03-06 15:42
@alex9434 good thing it helped you.
I don't know the specifics about the setup, they mentioned that at least part of the storage comes from a network share or something like that and that why that query is slow, but no idea. 
They are working in a new solution to move our db server soon; I hope that helps, but so far we are good with the patch.

**Comment by bubasuma** [comment] 2020-04-02 21:32
Internal Magento team is working on this issue right now.

**Comment by bubasuma** [comment] 2020-04-14 14:45
Hi @monotheist

Thank you for your report and collaboration!

The issue was fixed by Magento team.

The fix will be available with the upcoming 2.4.0 release.

Related commits: 05667ed53584030e1771654585cdb9234ad834fe

**Closed as completed by bubasuma** 2020-04-14 14:45 UTC
Labels: Issue: Format is valid, Reported on 2.3.3

**Comment by nadroj467** [comment] 2020-07-13 22:31
Hi,

Having some trouble applying this patch in Magento 2.3.5-p1 

We have only one file in this directory 
**public_html/lib/internal**/Magento/Framework/DB/Adapter/TableNotFoundException.php

We have the remainder of the files in the below directory (vendor)

**public_html/vendor**/magento/framework/DB/Adapter

In Pdo/Mysql.php as per patch
There is addition of path to
use Magento\Framework\DB\Adapter\TableNotFoundException;

But our file is not in this location it is in the location above. How can we resolve this? by copying TableNotFoundException.php to vendor/magento/framework/DB/Adapter ? 

We have an error report No such file or directory","1":"#1 Zend_Db_Adapter_Pdo_Mysql-> [vendor\/magento\/framework\/DB\/Adapter\/Pdo\/Mysql.php

Thanks
