### ISSUE TITLE
Magento widgets source models forced to use deprecated interface

### ISSUE THREAD

**Issue by Floddy** [magento/magento2#20064] opened 2019-01-04 10:18 UTC
### Summary (*)
\Magento\Framework\Option\ArrayInterface, is marked as deprecated, and \Magento\Framework\Data\OptionSourceInterface should be the replacement.

However, when using a source model for a select in a widget, the source model has to implement \Magento\Framework\Option\ArrayInterface, because of this check:
https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/Option/ArrayPool.php#L36-L38

This forces 3rd party widgets to implement the deprecated \Magento\Framework\Option\ArrayInterface.

### Examples (*)
* Change from implementing \Magento\Framework\Option\ArrayInterface to implement \Magento\Framework\Data\OptionSourceInterface in https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Config/Model/Config/Source/Yesno.php#L12
* Create a new CMS page in admin
* Insert a Catalog Products List widget

The options will not be shown, and system.log now has an entry with 'main.ERROR: Magento\Config\Model\Config\Source\Yesnodoesn't implement \Magento\Framework\Option\ArrayInterface'.

### Proposed solution
Easiest fix would be to change the condition in \Magento\Framework\Option\ArrayPool to allow for both interfaces, unless there are some plans of deprecating the ArrayPool class too?

**Comment by magento-engcom-team** [comment] 2019-01-04 10:18
Hi @Floddy. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Floddy do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-04 10:18
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-01-04 12:50
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97436` were created

**Comment by magento-engcom-team** [comment] 2019-01-23 17:47
Hi @Floddy. Thank you for your report. 
The issue has been fixed in magento/magento2#20248 by @milindsingh in 2.3-develop branch
Related commit(s):
 - [a958f5b3f333917766bc7d31c63480945a605f2c](https://github.com/magento/magento2/commit/a958f5b3f333917766bc7d31c63480945a605f2c)
 - [f7275c53ceaecb8a3e16a2dc286b8614ebd1aef8](https://github.com/magento/magento2/commit/f7275c53ceaecb8a3e16a2dc286b8614ebd1aef8)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2019-01-23 17:47 UTC
Labels: Issue: Ready for Work, Component: Config, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid
