### ISSUE TITLE
Cart price rules - Incorrect discount amount when using fixed discount amount for whole cart which applies to shipping amount

### ISSUE THREAD

**Issue by wyomind** [magento/magento2#35714] opened 2022-07-01 12:55 UTC
### Preconditions and environment

- Magento version 2.4.3 with sample datas.

### Steps to reproduce

1. Create a tax rate (20%) applied on both products and shipping. https://screenrec.com/share/GVq5dIjwnp

2. Configure the tax base calculation to make the tax be applied by default https://screenrec.com/share/3Yv4WJRpDS

3. In Sales > Tax configuration Panel:
Tax Class for Shipping : Taxable Goods
Catalog Prices: Including Tax
Shipping Prices: Including Tax
Apply Discount On Prices: Including Tax
Enable Cross BorderTrade : No
https://screenrec.com/share/oh1QPUCYMV

4. Create a new cart rule
Coupon: Specific Coupon
Apply: Fixed amount discount for whole cart
Apply to shipping amount: yes
Discount Amount: 24
https://screenrec.com/share/1BR7ritfVn

5. Add a product in shopping cart (24$ including tax)
Go to checkout and use a shipping methods: Flat Rate 18$
Apply the cart rule using the coupon code
https://screenrec.com/share/KRJ0oSOr2q

Error in the amounts is visible in cart, and is the same during the checkout

### Expected result

Applied discount is 24$ , because this is the configured amount for the coupon and the total for the order is greater than 24$

### Actual result

Discount is 25.01$
Cart: https://screenrec.com/share/ag5KbdsUpE
Checkout: https://screenrec.com/share/E6RWfLynUm

### Additional information

Let me know if you need more information or if you want me to reproduce the issue in a vanilla instance

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by wyomind** [comment] 2022-07-01 12:55
-- Please reply above this line --

Hey Magento/magento2,

Thank you for your message.

 Your request has been correctly submitted.
     
 We’ll be getting back to you as soon as possible!

 Best Regards,
 The Wyomind Team

**Comment by wyomind** [comment] 2022-07-01 13:03
In addition to this, if the amount for the cart rule is bigger than the order total (lets say 100€) the order total after discount doesn't go to 0: https://screenrec.com/share/wPibC7jJsD

It looks like the discount is NOT applied to the shipping amount's VAT

**Comment by engcom-Delta** [comment] 2022-07-07 12:22
Hi @wyomind ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue.Go through with each and every step u have provided for Tax Rates,Tax Rules,Cart Rules.After adding an product to cart coupon code is added successfully, and total for the order is greater than the 24.please refer the screenshots.

![Screenshot (260)](https://user-images.githubusercontent.com/51681379/177771937-be6def95-07f7-4223-bb28-5de9fbcf210d.png)
![Screenshot (261)](https://user-images.githubusercontent.com/51681379/177771957-7bd8ad3b-932d-4627-ad5b-d5057325e60b.png)
![Screenshot (262)](https://user-images.githubusercontent.com/51681379/177771962-c62e3efb-6a3c-4ea7-89b0-08f95ac77613.png)
![Screenshot (263)](https://user-images.githubusercontent.com/51681379/177771966-7d51b5f7-940c-4203-83c2-6a9725a1868b.png)
![Screenshot (264)](https://user-images.githubusercontent.com/51681379/177771972-54492620-aff3-467a-9a9f-b73b9a87cac0.png)

**Comment by wyomind** [comment] 2022-07-07 12:56
Hello @engcom-Delta ,

I understand you don't have the exact same bug as the one I am having, but if you pay attention to your order's total you will see it is incorrect

Order total should be 18.00 (24-24+18) and it is 26.40

Would it be useful for you to provide me with an access to an instance so we can work on the same data?

Also as the issue I reported is about Magento 2.4.3, I guess this means the issue has evolved with 2.4.4-dev?

Kind regards,
Jean-Paul

**Comment by engcom-Delta** [comment] 2022-07-08 12:42
Hi @wyomind ,
This is a expected behaviour of magento.when we save tax class configuration it will throws an error,it is not recommended 
configuration of tax Configuration.Can you please check on 2.4-develop branch whether you are still able to reproduce the issue.
Please refer the attached screenshots.
![Screenshot (269)](https://user-images.githubusercontent.com/51681379/177994012-54122573-92b5-47a1-8f45-3f7bc487285c.png)
![Screenshot (275)](https://user-images.githubusercontent.com/51681379/177994034-5edace0c-44ae-4790-ba8f-da43dc40ed45.png)

**Comment by wyomind** [comment] 2022-07-08 13:54
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment] 2022-07-22 05:53
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Closed as completed by engcom-Delta** 2022-07-22 05:53 UTC
Labels: Issue: needs update

**Comment by wyomind** [comment] 2022-07-22 15:30
Hey Magento/magento2,

Since we haven't heard from you on this issue in a while, we're marking
this ticket closed.

Feel free to contact us at any time if you need. To do so simply log into
your Wyomind account and go to 'My account > My tickets' to create a new
one.

Best Regards,
The Wyomind Team
{#HS:1937328362-522966#}

**Comment by wyomind** [comment] 2022-07-22 15:30
Hey Magento/magento2,

Since we haven't heard from you on this issue in a while, we're marking
this ticket closed.

Feel free to contact us at any time if you need. To do so simply log into
your Wyomind account and go to 'My account > My tickets' to create a new
one.

Best Regards,
The Wyomind Team
{#HS:1937253212-522948#}

**Comment by wyomind** [comment] 2022-10-11 06:58
-- Please reply above this line --

Hey Magento/magento2,

Thank you for your message.

 Your request has been correctly submitted.
     
 We’ll be getting back to you as soon as possible!

 Best Regards,
 The Wyomind Team

**Comment by wyomind** [comment] 2022-10-25 14:42
https://github.com/magento give me 2.4.2-p2 instance

**Comment by wyomind** [comment] 2022-10-25 14:42
@magento give me 2.4.2-p2 instance

**Comment by wyomind** [comment] 2022-10-25 14:44
@magento give me 2.4-develop instance

**Comment by wyomind** [comment] 2022-10-25 14:44
-- Please reply above this line --

Hey Magento/magento2,

Thank you for your message.

 Your request has been correctly submitted.
     
 We’ll be getting back to you as soon as possible!

 Best Regards,
 The Wyomind Team

**Comment by wyomind** [comment] 2022-10-25 14:45
@magento give me 2.4.2 instance

**Comment by wyomind** [comment] 2022-10-25 15:41
https://github.com/magento give me 2.4.2 instance

**Comment by wyomind** [comment] 2023-05-01 21:42
Hey Magento/magento2,

Since we haven't heard from you on this issue in a while, we're marking
this ticket closed.

Feel free to contact us at any time if you need. To do so simply log into
your Wyomind account and go to 'My account > My tickets' to create a new
one.

Best Regards,
The Wyomind Team
{#HS:1943599985-523822#}
