### ISSUE TITLE
Cannot change cms block values

### ISSUE THREAD

**Issue by kilis** [magento/magento2#5826] opened 2016-07-27 06:53 UTC
### Preconditions

1. Magento 2.1
2. PHP 7
3. MYSQL 5.7.13
### Steps to reproduce

1. Load cms block by title
2. Set new store id
3. Save it

`foreach ($cmsBlocks as $cmsBlockItems) {`
 `$block = clone $this->_blockResource;`
 `$block->load($cmsBlockItems, 'title')`
 `->setStoreId([$storeId])`
 `->save();`
 `}`
### Expected result

1. Change block store id
### Actual result

1. [Mysql error](http://imgur.com/a/75OBa)

**Comment by magento-engcom-team** [comment] 2018-03-06 14:30
@kilis, thank you for your report.
The issue is already fixed in 2.2.3, 2.3.0, 2.1.12

**Closed as completed by magento-engcom-team** 2018-03-06 14:30 UTC
Labels: bug report, Component: Cms, Issue: Confirmed, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
