### ISSUE TITLE
Upgrade from 2.4.4 -> 2.4.4-p2 products not showing

### ISSUE THREAD

**Issue by johncarlson21** [magento/magento2#36350] opened 2022-10-21 13:58 UTC
### Preconditions and environment

Magento 2.4.4-p2
Upgraded from 2.4.4

### Steps to reproduce

1. Navigate to site
2. choose a category
3. No products found for category

### Expected result

1. Navigate to site
2. choose a category
3. products listed for category

### Actual result

No products shown in frontend for category, and products under category in admin show out of stock.

### Additional information

Site uses some managed stock but mostly no managed stock.
Create products with qty of 0, manage stock set to "No", and in stock status is set to "In Stock"
Setting product to a qty of 2 and setting manage stock to "Yes" and saving the product does not keep the qty after page load and sets it to 0.
Site has been reindexed, flushed all caches etc.

We also use Amasty Product Merchandising, and in the admin under product merchandising, all products show out of stock.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by rarog** [comment] 2022-10-23 08:52
@johncarlson21 Do you have the option "Allow All Products per Page" enabled?

**Comment by engcom-Bravo** [comment] 2022-10-25 12:48
Hi @johncarlson21,


Thank you for reporting and collaboration.

Verified the issue Upgrading from 2.4.4 to 2.4.4-p2 we are not able to reproduce the issue.Kindly refer screenshots.


Products are visible in Category.


<img width="1403" alt="Screenshot 2022-10-25 at 5 06 33 PM" src="https://user-images.githubusercontent.com/51680745/197776935-fb356922-977b-4ced-8b5d-5742812296b7.png">





Please let us know we miss anything.


Kindly recheck the issue if any 3rd party extensions / modules enabled is causing this issue.



Thanks.

**Comment by engcom-Bravo** [comment] 2022-11-09 06:09
Hi @johncarlson21,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-11-09 06:09 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.x

**Comment by tarekfellah** [comment] 2022-12-14 14:46
Did you check if the ElasticSearch version is supported?
