### ISSUE TITLE
[2.1.0] Product attribute : Can not change the value Use "Product Image for Swatch if Possible"

### ISSUE THREAD

**Issue by delyriand** [magento/magento2#7008] opened 2016-10-14 08:54 UTC
### Preconditions

1. Magento CE 2.1.0 + Sample data
2. PHP 7.0.8
### Steps to reproduce

1. Edit a visual swatch product attribute, for example "color"
2. Change value of "Product Image for Swatch if Possible" to "Yes" 
3. Save attribute with "Save and Continue Edit" button
### Expected result

1. Confirmation message "You saved the product attribute."
2. The value of "Product Image for Swatch if Possible" to "Yes"
### Actual result

1.  Confirmation message "You saved the product attribute."
2. The value of "Product Image for Swatch if Possible" has not changed

---

The problem is the method `populateAdditionalDataEavAttribute` into `Magento\Swatches\Helper\Data` she overrides the form data.  I think we should add a test `&& null === $attribute->getData($key)`.

``` php
    private function populateAdditionalDataEavAttribute(Attribute $attribute)
    {
        $additionalData = unserialize($attribute->getData('additional_data'));
        if (isset($additionalData) && is_array($additionalData)) {
            foreach ($this->eavAttributeAdditionalDataKeys as $key) {
                if (isset($additionalData[$key]) && null === $attribute->getData($key)) {
                    $attribute->setData($key, $additionalData[$key]);
                }
            }
        }
        return $this;
    }
```

Or, populate swatch attribute values after attribute load

**Comment by olysenko** [comment] 2016-10-18 14:51
Hi, thanks for your report. I checked this issue on 2.1.2 and cannot reproduce. Closed as cannot reproduce on newer version

**Closed as completed by olysenko** 2016-10-18 14:51 UTC
Labels: bug report, Component: Catalog
