### ISSUE TITLE
Magento 2.0.4 very slow in localhost wamp  windows

### ISSUE THREAD

**Issue by nltheme** [magento/magento2#4382] opened 2016-05-03 05:50 UTC
increase memory limit  = 2048 MB
enabled developer mode.
let me know if i am missing any php.ini setting or apache.

**Comment by tkn98** [comment] 2016-05-03 08:04
I don't want to sound harsh, but in general, Magento 2 is not supported on Windows.

**Comment by shashankitsoft** [comment] 2016-05-03 09:02
Refer to this guide: http://www.devside.net/wamp-server/wamp-is-running-very-slow . Do appropriate settings. Magento 2.0.4 will work fine on Windows. :)
Also, refer to issue #4363 for more details.

Thanks.

**Comment by tkn98** [comment] 2016-05-03 09:26
Not saying it does not run, but reporting Windows issues in the Github issue-tracker is perhaps not the best venue. It perhaps makes more sense when there is a windows dedicated install section in the forums to collect the knowledge & tips and tricks?

**Comment by mazhalai** [comment] 2016-05-03 14:12
Closing since this is not a bug.

**Closed by mazhalai** 2016-05-03 14:12 UTC
