### ISSUE TITLE
Visibility of rating can't be saved.

### ISSUE THREAD

**Issue by Bravarg** [magento/magento2#2837] opened 2015-12-30 08:51 UTC
Hello,
![screenshot_70](https://cloud.githubusercontent.com/assets/11926404/12048345/ee5eded8-aee2-11e5-8935-7694193889a7.png)

When I try to save rating visibility to a few stores, I receive transaction rollback, because of method array_keys (on screenshots) and array_diff_assoc instead of array_diff . 
![screenshot_72](https://cloud.githubusercontent.com/assets/11926404/12049034/03e10710-aeeb-11e5-8f1c-18ed543595d0.png)

![screenshot_71](https://cloud.githubusercontent.com/assets/11926404/12049002/b1e2a5cc-aeea-11e5-9d01-bcfd19c4949f.png)
in class Magento\Review\Model\ResourceModel\Rating.
The values of "store_id" become wrong after this foreach and can't be saved. I think there are noneed to use array_keys and array_diff_assoc methods. Correct me if I'm wrong.
Thank you.

**Comment by shiftedreality** [comment] 2016-01-12 17:03
Hi, @rawick 

I cannot reproduce current issue. Are you using latest developer branch code?

**Comment by Bravarg** [comment] 2016-01-14 07:57
Yes, thank you @shiftedreality for answer. When I published my issue it was the latest version. And atm I use overrided core classes for saving ratings.

**Comment by komsitr** [comment] 2016-04-24 12:57
I had the same issue using Magento 2.0.2. The problem solve after I apply the fix from @rawick

Clase Magento\Review\Model\ResourceModel\Rating

Line: 213
from `$this->deleteRatingData($ratingId, $table, array_diff_assoc($old, $new));`
to `$this->deleteRatingData($ratingId, $table, array_diff($old, $new));`

Line: 216
from `foreach (array_keys(array_diff_assoc($new, $old)) as $storeId) {`
to `foreach (array_diff($new, $old) as $storeId) {`

Line 237
from `$where = ['rating_id = ?' => $ratingId, 'store_id IN(?)' => array_keys($data)];`
to `$where = ['rating_id = ?' => $ratingId, 'store_id IN(?)' => $data];`

**Comment by shiftedreality** [comment] 2016-04-25 09:07
Thank you for submission.
I created internal ticket MAGETWO-52259 to fix this bug

**Comment by wert2all** [comment] 2016-08-16 12:30
Closed as fixed

**Closed as completed by wert2all** 2016-08-16 12:30 UTC
Labels: Issue: Ready for Work
