### ISSUE TITLE
DateTime type not working with Web API

### ISSUE THREAD

**Issue by zingix** [magento/magento2#24791] opened 2019-09-30 14:09 UTC
When trying to request Web API end-point which has an interface with methods returning DateTime Magento throws the following error:

```
Each getter must have a doc block. See DateTime::format()
```

### Preconditions (*)
1. Magento version 2.3-develop
2. PHP v7.2

### Steps to reproduce (*)
1. Create a new interface as shown below.

```
interface TestInterface
{
    /**
     * Gets the current date.
     * 
     * @return \DateTime
     */
    public function getDate() : \DateTime;
}
```

2. Implement the interface and simply return an a new DateTime object.

```
class TestApi implements TestInterface
{
    /**
     * Gets the current date.
     * 
     * @return \DateTime
     */
    public function getDate() : \DateTime {
        return new \DateTime();
    }
}
```

3. Create an entry in webapi.xml pointing to the service.

```
    <route method="GET" url="/V1/test">
        <service class="TestInterface" method="getDate"/>
        <resources>
            <resource ref="anonymous"/>
        </resources>
    </route>
```

4. Call the service using curl.

### Expected result (*)
1. The DateTime should be correctly serialized.
2. When using JSON serializer, the output should be in ISO8601

### Actual result (*)
1. An error is thrown as shown below.

```
Each getter must have a doc block. See DateTime::format()
```

**Comment by zingix** [comment] 2019-10-01 09:36
Hi @engcom-Charlie , do I need to do anything? Can I help with providing more infomration?

**Comment by magento-engcom-team** [comment] 2019-10-01 09:44
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20656` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Charlie** [comment] 2019-10-01 09:44
Hello @zingix ! No, thanks. I reproduced this issue.

**Comment by gabrieldagama** [comment] 2020-10-20 16:34
Hi @zingix, thanks for reporting this, I believe the reason for not having a serializer for the DateTime class is even though there is an ISO for standardization, the format of the DateTime still may need to be different depending on country or client.

We recommend to your `getDate` method to return a string formatted on the way need.

I will be closing this issue since there are no plans to implement such a feature.

**Closed as completed by gabrieldagama** 2020-10-20 16:34 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Webapi, Triage: Dev.Experience, Progress: done

**Comment by zingix** [comment] 2020-10-21 01:12
Hi @gabrieldagama, I do not agree that the date should be formatted as string. Using this method, you cannot directly load date types from the database and use the Magento default tools to have it properly mapped - except you store the dates as strings as well.

I added this issue for the API not Magento in general. The API should exactly be client independent and close to standard as possible. It is way easier to e. g. in front-end use libraries like moment.js for bringing the date into the clients preferred format. Think of multi-country / multi-language sites. In your scenario you would need to have an endpoint for each config.

To be honest, after waiting more than one year to get a focus on this issue I also do not expect it to be solved.
