### ISSUE TITLE
Error on adminhtml popup product grids (e.g. adding Simple Product to Grouped Product)

### ISSUE THREAD

**Issue by densen45** [magento/magento2#38778] opened 2024-05-30 10:19 UTC
### Preconditions and environment

- Magento version 2.4.7
- PHP 8.2

### Steps to reproduce

1. Open or create a Grouped Product
2. Scroll down and click "Add Products to Group"
3. Wait until the grid is loaded

This issue also occurs on the Bundle Product page "Add Products to Option". 

### Expected result

The pop up displays without any error.

### Actual result

The following error is shown in the browser:
`A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.`

The following warning can be found in the system.log:
`main.ERROR: Warning: Undefined array key "filters" in /path/to/magento/vendor/magento/module-ui/Controller/Adminhtml/Bookmark/Save.php on line 250 [] []`

### Additional information

In the Save.php on line 250 it is expected, that the two arrays `$existingConfig` and `$currentConfig` contains a key called `filters`. This part is new in 2.4.7 and was not present in 2.4.6-p4.
Both arrays don't contain the `filters` key on these 'pop up product grids', however the key exists in both variables on e.g. the Product Grid (Catalog > Products). I guess this is because the filter for the Product Grid is saved for later visits, but for the ‘pop-up product tables’ the filter is never saved.

I have not noticed any restrictions due to this error. The filter works as expected and once you have set a filter, the error is no longer displayed.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by densen45** [comment] 2024-05-30 10:20
@magento give me 2.4.7 instance

**Comment by densen45** [comment] 2024-05-30 10:36
I was able to reproduce this issue on the provided Magento instance for both, Grouped and Bundle Products.

Grouped Product:
![Bildschirmfoto vom 2024-05-30 12-34-00](https://github.com/magento/magento2/assets/3801001/13f637c3-7735-4ec0-8e62-98470f58d26d)

Bundle Product:
![Bildschirmfoto vom 2024-05-30 12-35-47](https://github.com/magento/magento2/assets/3801001/28e86953-8741-443c-bfe3-3c940c345b52)

**Comment by engcom-Bravo** [comment] 2024-05-30 10:48
Hi @densen45,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.

<img width="1439" alt="Screenshot 2024-05-30 at 16 15 28" src="https://github.com/magento/magento2/assets/51680745/e8f91c6d-d114-43d3-ad7f-78d69db220de">


<img width="1438" alt="Screenshot 2024-05-30 at 16 13 48" src="https://github.com/magento/magento2/assets/51680745/33a1a085-0ce5-42e2-892d-4dbdd4eb4137">


The following error is shown in the browser:

`A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later`.


The following warning can be found in the system.log :

`main.ERROR: Warning: Undefined array key "filters" in /usr/local/var/www/magentop/magento2/app/code/Magento/Ui/Controller/Adminhtml/Bookmark/Save.php on line 250 [] []`


Hence Confirming the issue.

Thanks.

**Comment by rogerdz** [comment] 2024-06-03 02:43
It error only first time, I can duplicate by remove grouped_product_listing in ui_bookmark and reload admin product page

**Comment by gwharton** [comment] 2024-07-15 08:09
I see these pop up all the time in my logs. And not just on that page too.

[2024-07-15T07:52:59.721745+00:00] main.ERROR: Warning: Undefined array key "filters" in /home/ubuntu/production/vendor/magento/module-ui/Controller/Adminhtml/Bookmark/Save.php on line 250 [] []

![image](https://github.com/user-attachments/assets/c2cb2ade-1489-45a6-802c-2f837ad4af75)

![image](https://github.com/user-attachments/assets/25973830-4e61-4d1b-a9d5-080b95294ac4)

**Comment by simonmaass** [comment] 2024-07-26 08:30
anyone have a patch for this?

**Comment by NetStorm84** [comment] 2024-09-05 11:43
> anyone have a patch for this?

Yes, this works!

https://patch-diff.githubusercontent.com/raw/magento/magento2/pull/39143.patch

**Comment by Calvin495** [comment] 2024-11-11 06:10
Does anyone have an official patch for this? We are getting the issue in 2.4.7-p1.

**Comment by engcom-Bravo** [comment] 2024-12-23 05:13
Hi @densen45,

Thanks for reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.


<img width="1418" alt="Screenshot 2024-12-23 at 10 43 03 am" src="https://github.com/user-attachments/assets/cb9c326d-2a25-4368-92e3-9f506b3e7cd5" />


The pop up displays without any error.


Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-12-23 05:13 UTC
Labels: Issue: Confirmed, Component: Admin, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Admin UI, Reported on 2.4.7
