### ISSUE TITLE
Magento 2.4.1: One or more of your dotdigital cron tasks have errors: ddg_automation_customer_subscriber_guest_sync,

### ISSUE THREAD

**Issue by JR2Media** [magento/magento2#32951] opened 2021-05-05 18:43 UTC
Latest version of Magento installed. At the top of Magento admin page, below are the messages displayed:

```One or more of your dotdigital cron tasks have errors: ddg_automation_customer_subscriber_guest_sync, ddg_automation_status, ddg_automation_reviews_and_wishlist, ddg_automation_catalog_sync, ddg_automation_importer, ddg_automation_campaign, ddg_automation_order_sync, ddg_automation_monitor, ddg_automation_abandonedcarts. Please go to Cron Tasks to review.```

3 people are also having this issue: https://magento.stackexchange.com/questions/332394/magento-2-4-1-one-or-more-of-your-dotdigital-cron-tasks-have-errors-ddg-automa

**Comment by ihor-sviziev** [comment] 2021-05-10 06:44
@sivaschenko @sidolov @gabrieldagama could you forward this issue to dotdigital extension developers?

**Comment by sta1r** [comment] 2021-05-10 15:16
This is just our module flagging cron errors via System messages. See https://docs.magento.com/user-guide/configuration/dotdigital/developer.html#system-alerts. To remove the messages either disable system alerts in the configuration, or (if you're not using it) disable the module and clear cache.

**Comment by engcom-November** [comment] 2021-06-09 15:13
Hi @JR2Media 

I verified this issue on latest Magento version 2.4.2 and is not reproducible. Can you please provide the details - on which Magento Version and PHP version this issue is reproduced.
Also please try to rerun Magento step upgrade and clean cache to check if the issue is still reproducible.

Thanks and regards,
@engcom-November.

**Comment by engcom-November** [comment] 2021-06-14 09:26
Verified this issue on latest Magento version 2.4.2 and the issue is reproducible when setup and run cron jobs but is resolved when disabled system alerts in the configuration (Stores > Settings > Configuration > dotdigital > Developer -> System Alerts) and clean cache or rerun Magento setup upgrade and clean cache.
Please let us know if the issue still exits or can be closed if resolved.

Thanks,
@engcom-November .

**Comment by engcom-November** [comment] 2021-06-29 06:22
Hi @JR2Media 
We are closing this ticket , as there has been no update on the same.
Thank you.

**Closed as completed** 2021-06-29 06:22 UTC
Labels: Component: Bundled Extension, Issue: needs update, Reported on 2.4.1
