### ISSUE TITLE
ImportExport : Import Category "AlreadyExistsException"

### ISSUE THREAD

**Issue by EliasKotlyar** [magento/magento2#7415] opened 2016-11-13 12:33 UTC
### Preconditions
Any Magento2 Version

### Steps to reproduce
1. Create a Category named "Test-1"
2. Import a Product using the Backend with the Field "categories" filled with the value "Test 1"(without "-", just a space)

### Expected result
1. Existing Category should be used

### Actual result
1. There is an Error, that the import has failed

### Why this error occurs? 

The Category import function has an event which creates an URL-Rewrite. Because of the similar Name, it will create an URL-Rewrite with the same request-path(due to the translitURL Function), which will result in a DB conflict. Instead of doing this, we can just find the Category which has the same request-path and add the product inside it.

Greetings
Elias

**Comment by veloraven** [comment] 2016-11-15 12:53
@EliasKotlyar thank you for your report.
Please identify which version of Magento you are running.

**Comment by EliasKotlyar** [comment] 2016-11-16 22:29
Hello,

It appears that this Error is in every Magento2 Version. I was using the 2.1.1.

Greetings
Elias

**Comment by vaguemind** [comment] 2016-11-27 12:20
I applied this fix you shared , but when i import the csv file it create additional category with the name of category in the column "categories" . although i choose import behavior  " Add/update " or "replace" but when i choose " Delete" it add imports but not add the product to a category ? what is the fix for this ? 
i use magento ver. 2.1.1 .

**Comment by antboiko** [comment] 2017-02-07 17:51
Hi @EliasKotlyar. It's a correct behavior and not a bug. 
Test 1 and Test-1 are different names and are two different Categories. 

URL keys for Categories and Products are generated automatically based on Category or Product Name if left empty. So both categories Test-1 and Test 1 will try to get URL key test-1 using a default template for auto-generated fields. 
Since category Test-1 already exists and has URL key test-1 in DB, the import won't allow saving the category Test 1 as it intends to have the same URL key "test-1".

I'm closing this issue since it's not a bug.

Best,
Anton.

**Closed as completed by antboiko** 2017-02-07 17:51 UTC
Labels: Component: ImportExport
