### ISSUE TITLE
The Default Attribute Codes give no response when add/update product information by CSV files

### ISSUE THREAD

**Issue by ghost** [magento/magento2#35979] opened 2022-08-19 10:48 UTC
### Preconditions and environment

- Magento version 2.4.4 Open Source
- Composer 2.1.0
- PHP 8.1.9

### Steps to reproduce

- Magento version 2.4.4 Open Source
- PHP 7.4.3
- Upgrade Magento from 2.4.0 to 2.4.4 Open Source by **Composer 1.10.16**
- Add/Update Product with default attributes by importing CSV files

### Expected result

Data of attributes `category_ids`, `tax_class_id`, `status` can be imported by csv correctly and makes the backend response to update product information.

### Actual result

Attribute in backend setting: `category_ids` -> Made no response
Attribute in imported csv: `categories` -> Made response
![WechatIMG2010 (1)](https://user-images.githubusercontent.com/110151530/185600682-1d724898-bbc3-4101-91cf-a264e6d1a639.jpeg)

--------

Attribute in backend setting: `tax_class_id` -> Made no response
Attribute in imported csv: `tax_class_name` -> Made response
![20111658680237_ pic](https://user-images.githubusercontent.com/110151530/185600696-b28d6a75-d418-4673-a280-1676f74d9d79.jpg)

--------

Attribute in backend setting: `status` -> Made no response
Attribute in imported csv: `product_online` -> Made response
![20121658680502_ pic](https://user-images.githubusercontent.com/110151530/185600706-ce46c1bc-d0fe-4c1e-815d-a8945280d030.jpg)

### Additional information

Hello Guys. I am a beginner who is using Magento 2.4.4 community edition, upgraded from 2.4.0.
I found a big question that the default attributes are not updated and unavailable caused magento system can't detect them in my CSV file even my back-end has these default attributes: category_ids, tax_class_id, status etc. They are not effecting the system at the moment, but I am not sure if they will effect the entire web environment in the future after upgraded the Magento Version. This is irregular for users if the magento back-end system and the codes are not match.

Finally I found the updated attribute codes on https://docs.magento.com/user-guide/system/data-attributes-product.html . 
### I am looking for solutions to update the default setting of magento attribute codes or make changes inside the Magento files of my VMware through SSH to fix them if they can't be fixed by command through SSH.

Thank you very much for your attention. Wish you all the best!

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by KrasnoshchokBohdan** [comment] 2022-08-19 13:20
@magento add to contributors team

**Comment by KrusLeung** [comment] 2022-08-19 13:30
Thank you Krasnosh for joining contributors team! <3

**Comment by KrusLeung** [comment] 2022-08-19 16:38
PHP 8.1.9

**Comment by engcom-November** [comment] 2022-08-29 16:40
Hi @KrusLeung ,
Thank you for reporting and collaboration. Verified the issue by upgrading from 2.4.0 to 2.4.4 project-community-edition and also on 2.4-develop branch but could not reproduce the issue. Data of attributes category_ids, tax_class_id, status are imported successfully. Kindly check the issue on Magento 2.4-develop branch as per [System requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) and provide missing steps / any 3rd party extensions / modules enabled if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-09-20 03:18
Hi @KrusLeung ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed** 2022-09-20 03:18 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
