### ISSUE TITLE
The wrong price is showing in other currency when creating order by Admin and set custom price in it

### ISSUE THREAD

**Issue by rituraj001** [magento/magento2#27309] opened 2020-03-17 09:31 UTC
### Preconditions (*)

1. The issue is in Magento 2.3.2 and higher. We have not checked in Magento 2.3.1 and earlier versions.

### Steps to reproduce (*)

1. Go to the Admin Panel.
2. Create a new order.
3. Choose customer and Select Product
4. Enter the Custom Price (Select the CheckBox)
5. Click on Update Items and quantities.
6. Change Currency at Order Currency drop-down at the left-hand side.
7. It displays the wrong price at Price field.
8. After Submitting Order, it displays wrong on the Order Detail page, Invoice pdf, etc.

### Expected result (*)

1. The correct price should be visible according to the currency like subtotal.

### Actual result (*)

1. The wrong price is showing in other currency when creating order by Admin and set custom price in it
2. See the attached video for issue.

[Custompricedisplaywrong.mkv.zip](https://github.com/magento/magento2/files/4342490/Custompricedisplaywrong.mkv.zip)

**Comment by rituraj001** [comment] 2020-03-17 09:42
@rituraj001 do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?

yes

**Comment by AltayAkkus** [comment] 2020-03-17 11:42
@magento give me 2.3.2 instance

**Comment by magento-engcom-team** [comment] 2020-03-17 11:42
Hi @AltayAkkus. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by AltayAkkus** [comment] 2020-03-17 12:23
@magento give me 2.3.2 instance

**Comment by magento-engcom-team** [comment] 2020-03-17 12:24
Hi @AltayAkkus. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by ajijshekh123** [comment] 2020-03-17 13:35
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-17 13:35
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by riturajebizon** [comment] 2020-03-24 12:01
Hi
Any update on this?

**Comment by ajijshekh123** [comment] 2020-03-24 12:22
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-24 12:22
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-03-24 12:23
Hi @ajijshekh123, here is your [Magento instance](https://i-27309-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27309-2-4-develop.instances.magento-community.engineering/admin_2c0c](https://i-27309-2-4-develop.instances.magento-community.engineering/admin_2c0c)
Login: `b64664b3` Password: `bfea52a3288d`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2020-03-24 12:46
Hi @rituraj001 ,
Wrong price is displayed after place the order.
See attached the screenshot:

![WrongPriceIssue](https://user-images.githubusercontent.com/24711761/77426980-90190880-6dfb-11ea-99e8-9ac921d757ff.png)

Thanks.

**Comment by magento-engcom-team** [comment] 2020-03-24 12:47
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32703` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by riturajebizon** [comment] 2020-03-24 12:53
Hi
Yes,it displayed after placed the order.
And it display all the place like Invoice e.t.c
Most important is that the wrong place has displayed on pdf invoice that is totaly different

**Comment by rituraj001** [comment] 2020-04-02 14:31
Hi 
have you find any solution for this issues?

**Comment by AltayAkkus** [comment] 2020-04-03 13:19
I'm gonna work on it.

**Comment by AltayAkkus** [comment] 2020-04-03 13:19
@magento give me 2.3.2 instance

**Comment by magento-engcom-team** [comment] 2020-04-03 13:19
Hi @AltayAkkus. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by magento-engcom-team** [comment] 2020-04-03 13:20
Hi @AltayAkkus, here is your [Magento instance](https://i-27309-2-3-2.instances.magento-community.engineering).
Admin access: [https://i-27309-2-3-2.instances.magento-community.engineering/admin_af5a](https://i-27309-2-3-2.instances.magento-community.engineering/admin_af5a)
Login: `ee56954a` Password: `7e627ca6e28d`
Instance will be terminated in up to 3 hours.

**Comment by jigneshkhunt** [comment] 2020-04-25 05:44
I am working on this issue.

**Comment by sushantvishwas1990** [comment] 2020-07-10 15:07
Hi, @ajijshekh123  I was able to solve this issue you can follow what I have done.
1. Created a plugin that will override Magento core function by using etc/di.xml your di.xml looks like as following code.
`<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    
    <type name="Magento\Quote\Model\Quote\Item\ToOrderItem">
        <plugin name="product_set_price_before_order" type="Vendor\Module\Plugin\Quote\Model\Quote\Item\ToOrderItemPrice"/>
    </type>
</config>`
2.Your Plugin File as follows:
`<?php

namespace Vendor\Module\Plugin\Quote\Model\Quote\Item;

use Vendor\Module\Helper\Data;


class ToOrderItemPrice {
    
    /**
     * @var helper
     */
    protected $helper;
    
    public function __construct(
        Data $helper
    ) {
        $this->helper = $helper;
    }
    
    public function afterConvert(\Magento\Quote\Model\Quote\Item\ToOrderItem $subject, $result) {
        
        $result->setPrice($this->helper->convertToBaseCurrency($result->getPrice()));
        return $result;
    }
}`
3. One More thing the helper function we used in our plugin file helper file as follows:
`<?php
/**
 * Vendor Module.
 * @category  Vendor
 * @package   Vendor_Module
 * @author    Vendor
 */

namespace Vendor\Module\Helper;

use Magento\Framework\App\Helper\Context;
use Magento\Framework\Pricing\Helper\Data as PriceHelper;

/**
 * Class Data
 * @package Vendor\Module\Helper\Data
 */
class Data extends \Magento\Framework\App\Helper\AbstractHelper {
    
    protected $_priceHelper;
    
    /**
     * get Auth token
     */
    public function __construct(
        Context $context,
        PriceHelper $priceHelper
    ) {
        $this->_priceHelper = $priceHelper;
        parent::__construct($context);
    }
    
    /**
     * @param $price
     * @return int|float
     */
    public function convertToBaseCurrency($price = null) {
        
        $formattedCurrencyValue = $this->_priceHelper->currency($price, false, false);
        return $formattedCurrencyValue;
    }
}`
You need to do this extra code with your custom price code.

Thanks

**Comment by ajijshekh123** [comment] 2020-07-10 17:26
Thanks for the Update @sushantvishwas1990 and Solution about the issue.

**Closed as completed** 2020-07-10 17:27 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Admin, Component: Pricing, Reproduced on 2.4.x, Reported on 2.3.1
