### ISSUE TITLE
Error JS when select product attribute in sales rules: Uncaught ReferenceError: sales_rule_form is not defined

### ISSUE THREAD

**Issue by lionalex** [magento/magento2#28211] opened 2020-05-13 14:53 UTC
### Preconditions (*)

1. Magento 2.3.5-p1 (reproduced only on composer versions of Magento)

### Steps to reproduce (*)

1. Go to sales rule
2. in tab Action try to select a product's attribute (example SKU)
3. then click to show product to search

### Expected result (*)

1. The list of product that I can select
<img width="1616" alt="Schermata 2020-05-13 alle 16 51 06" src="https://user-images.githubusercontent.com/4151825/81828466-18817300-953a-11ea-982e-a02f08a1ed25.png">

### Actual result (*)

1. The list of products with a JS error and if I try to select one product, this not added in input field
<img width="1230" alt="Schermata 2020-05-13 alle 16 51 13" src="https://user-images.githubusercontent.com/4151825/81828447-14edec00-953a-11ea-8317-6f11fbd356a5.png">

**Comment by edenduong** [comment] 2020-05-14 06:44
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-14 06:44
Magento instance deployment temporary unavailable due to service maintenance.

**Comment by pemann** [comment] 2020-05-18 07:53
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment] 2020-05-18 07:53
Hi @pemann. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment] 2020-05-18 14:37
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34380` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by edenduong** [comment] 2020-05-20 07:44
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-20 07:45
Hi @edenduong. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-05-20 07:46
Hi @edenduong, here is your [Magento instance](https://i-28211-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28211-2-4-develop.instances.magento-community.engineering/admin_3ed5](https://i-28211-2-4-develop.instances.magento-community.engineering/admin_3ed5)
Login: `1ed9d1b4` Password: `fee0b281ba95`
Instance will be terminated in up to 3 hours.

**Comment by edenduong** [comment] 2020-05-20 07:54
Seems it was fixed in 2.4-develop.

**Comment by lionalex** [comment] 2020-06-29 09:02
So, is there a solution?

**Comment by lionalex** [comment] 2020-07-09 13:43
> Seems it was fixed in 2.4-develop.

in my magento 2.3.4 can I fixed the bug?

**Comment by squeegy06** [comment] 2020-08-05 12:45
Has anyone found a solution for this?  We are also experiencing this issue with out shop after updating to 2.3.5

**Comment by diegoplada** [comment] 2020-08-05 16:06
@squeegy06 

https://drive.google.com/file/d/1AQ2KBFLgo5flTrzBeTz7iyOV0s20qBYI/view?usp=sharing

**Comment by jonaschen623** [comment] 2020-08-05 20:53
patch file from magento support team (for **EE** version),

[MDVA-26005_EE_2.3.4_COMPOSER_v1.patch.zip](https://github.com/magento/magento2/files/5031058/MDVA-26005_EE_2.3.4_COMPOSER_v1.patch.zip)

To apply the patch:

Please upload the patch into your Magento root directory and run the SSH command below:
`patch -p1 < FILE_NAME.patch`

**Comment by himanshu8dev** [comment] 2020-09-26 09:34
@magento I am working on this
--

**Comment by himanshu8dev** [comment] 2020-09-26 09:34
@magento add to contributors team

**Comment by himanshu8dev** [comment] 2020-09-26 09:35
@magento I am working on this

**Comment by himanshu8dev** [comment] 2020-09-26 10:28
@magento Issue has been fixed in the latest Magento 2.3-develop code base. please update the file with 2.3.5-p1.

**Comment by himanshu8dev** [comment] 2020-09-26 11:23
The issue has been fixed in develop branch @magento-engcom-team as I have checked the source code twice but  the code is not updated in the 2.3.5-p1 version so kindly proceed further with the related step.

**Comment by himanshu8dev** [comment] 2020-10-02 07:07
@sidolov Can you please check my above comment? the issue has been resolved in the latest package but not updated in 2.3.5 version.

**Comment by sidolov** [comment] 2020-10-02 15:00
Hi @himanshu8dev , it's expected behavior, the known issue will be fixed in the upcoming release. Since the issue is fixed in the develop branch I'm closing it since it's not relevant anymore. Thank you for your collaboration!

**Closed as completed by sidolov** 2020-10-02 15:00 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Issue: Format is valid, Component: SalesRule, Priority: P1, Severity: S3, Reproduced on 2.3.5p1, Progress: done, Reported on 2.3.5-p1
