### ISSUE TITLE
All page header, footer and some other option is broken.

### ISSUE THREAD

**Issue by khalidbony** [magento/magento2#36127] opened 2022-09-10 13:27 UTC
### Preconditions and environment

- Magento version 2
- Anything else that would help a developer reproduce the bug
- how may i solve this bugging problem. 

### Steps to reproduce

1. All page broken some option
2. all pages header and footer broken 

### Expected result

child theme upload successfully.
https://demo.drm.com.bd/

### Actual result

header and footer broken. and some other option also broken

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2022-09-12 16:42
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-09-13 08:24
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-09-13 09:00
Hi @khalidbony ,

We are trying to reproduce the issue in 2.4-develop branch....But we are not able to reproduce the issue.

Header And footer not broken Everything is fine in Magento instance.

Screenshots:
![Screenshot from 2022-09-13 14-27-56](https://user-images.githubusercontent.com/60198592/189859006-242d09c8-e49e-4f46-8f70-d0de4c488509.png)
![Screenshot from 2022-09-13 14-27-54](https://user-images.githubusercontent.com/60198592/189859017-e3a92fb2-4b1d-4715-a313-58a20b915d73.png)
![Screenshot from 2022-09-13 14-25-49](https://user-images.githubusercontent.com/60198592/189859024-bfeb0226-75ac-4cdb-869d-3429b0feeccb.png)

Let us know if we Missing anything!!!

Thnaks!!!

**Comment by engcom-Dash** [comment] 2022-10-19 12:18
Hi @khalidbony ,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2022-10-19 12:18 UTC
Labels: Issue: needs update, Reported on 2.4.x
