### ISSUE TITLE
Layered navigation with Multiple Select and Filterable (with results) broken

### ISSUE THREAD

**Issue by diybook** [magento/magento2#7027] opened 2016-10-14 21:48 UTC
Layered navigation do not show the attribute when using a multiple select attribute where more than one option is selected in the product.
### Preconditions
1. Magento Version 2.1.0
### Steps to reproduce

I have added an multiple select attribute with the settings:  filterable (with results) 
There are two options defined: option 1 and option 2

There are also two products in the database for the selected category. 
- Product 1 with **option 1**
- Product 2 with **option 1** and **option 2** selected

But the layered navigation shows only **option 2** where the product count is 1. Option 1 is not shown.

Changing the attribute to filterable (no results), show all options in layered navigation with the corrent product count like:
- Option 1 (2) 
- Option 2 (1) 

Is there a problem counting products with multiple options selected? Wheren changing the products to the following: 
- Product 1 with **option 1**
- Product 2 **option 2** selected
  both options are shown again in layered navigation, even when the attribute ist changed to filterable (with results).
### Expected result

Layered navigation should show both options when the attibute is set to filterable (with results).
- Option 1 (2) 
- Option 2 (1)

**Comment by bartoszkubicki** [comment] 2016-10-15 22:22
what is data type of attribute? text, varchar?

**Comment by Abuknawu** [comment] 2016-10-16 06:51
The datatype is varchar as the multiple select requires.

**Comment by romainruaud** [comment] 2016-10-17 07:59
If you are looking to a proper way of implementing layered navigation with multiple select filters, you can take a look at our module : https://github.com/Smile-SA/elasticsuite

Regards,

**Comment by sevos1984** [comment] 2016-10-19 15:23
Internal ticket created MAGETWO-59877, thanks for reporting

**Comment by jzembala** [comment] 2016-10-27 14:57
With filterable option "with results" Magento not shows options which not reduce results. In other words when you choose filter "with results" on attribute, Magento will list only options with counting less than number of all products returned by collection.

It is implemented here: vendor/magento/module-catalog-search/Model/Layer/Filter/Attribute.php:110

**Comment by diybook** [comment] 2016-11-02 11:05
Hi bizzi, thanks for clarification. So it's no bug but a feature. 

Best regards, 
Gerald

**Comment by zanilee** [comment] 2016-12-13 17:23
Hi, @diybook!
If there are no other concerns we are going to close this issue.

**Comment by xmav** [comment] 2017-01-31 15:35
I’m closing this issue because it is not a bug. Please reopen this issue as needed.

**Closed as completed** 2017-01-31 15:35 UTC
Labels: Issue: Ready for Work, bug report, Progress: needs update, Component: Catalog, Component: Search, Issue: Format is not valid

**Comment by moto-jsc** [comment] 2017-02-02 12:11
Ok, this is a feature, but what to do if you want that multible select attribute would work as fillterable (with results) as it is described in the beggining in the first comment? 
How to get expected result:
    Option 1 (2)
    Option 2 (1)

**Comment by xmav** [comment] 2017-02-02 15:42
@moto-jsc 
You may set "Use in Layered Navigation" to "Filterable (no results)". In this case you will see all options.

**Comment by diybook** [comment] 2017-02-03 06:47
@xmav no, thats no option becase then you also get emtpy options
Option 1 (2)
Option 2 (1)
Option 3 (0)

If you show a layered navigation there should be all options visible even if the next option do not reduce the product collection. Otherwise you are never sure what is visible to the customer. 

For Example: If someone want to filter for blue shirts of size xxl and all your products are available for that selection - the user will never see that the size (assuming its option 2) is also available.

**Comment by moto-jsc** [comment] 2017-02-03 11:39
We do not want attributes with qty 0 appear, so function Filterable (no results) do not works for us.
Magento itself do not give what we want and it is excatly what diybook explains. 
We'll chekk for extension. Thank you.

**Comment by 666triv** [comment] 2017-10-19 14:08
We have the same issue. Will this be included in the next update?

**Comment by 666triv** [comment] 2017-11-20 00:58
What needs to be done to have this re-opened, im new here and not quite sure what needs to be done. :)
