### ISSUE TITLE
Tooltip overlapping over the label and store label hiding in left side menu (Design issue in New Cart Price Rule)

### ISSUE THREAD

**Issue by cedarvinda** [magento/magento2#22706] opened 2019-05-04 10:47 UTC
Tooltip overlapping over the label and store label hiding in left side menu (Design issue in New Cart Price Rule) in admin panel

### Preconditions (*)
1. php 7.2
2. Magento 2.3

### Steps to reproduce (*)
1. Login to admin panel 
2. Go to marketing tab in left menu and click on Cart Price Rules under the Promotions 
3. Now click in Add new rule and go to Labels  (Now you see issue ref as in screenshot) 

### Expected result (*)
![solution1](https://user-images.githubusercontent.com/26018716/57178015-15b06480-6e88-11e9-99b9-cc3544c1b01d.png)

### Actual result (*)
![issue1](https://user-images.githubusercontent.com/26018716/57178016-1b0daf00-6e88-11e9-9568-d12fdd4631d1.png)

**Comment by sivaschenko** [comment] 2019-05-04 10:49
#dmcdindia1

**Comment by shikhamis11** [comment] 2019-05-04 10:49
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-05-04 10:49
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-05-04 10:50
Hi @shikhamis11, here is your [Magento instance](https://i-22706-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22706-2-3-develop.instances.magento-community.engineering/admin](https://i-22706-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2019-05-04 10:54
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-05-04 10:54
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by cedarvinda** [comment] 2019-05-04 10:54
I am working in this issue at #dmcdindia1

**Comment by magento-engcom-team** [comment] 2019-05-04 10:54
Hi @shikhamis11, here is your [Magento instance](https://i-22706-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22706-2-2-develop.instances.magento-community.engineering/admin](https://i-22706-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-05-04 11:03
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99557` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Karlasa** [comment] 2019-05-05 19:21
Will close this issue as is duplicate of #19647

**Closed as completed by Karlasa** 2019-05-05 19:21 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.2.x, Issue: Format is valid, Component: SalesRule, Component: Admin, Event: dmcdindia1
