### ISSUE TITLE
Can't create new customer account from frontend with required DOB field

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#26700] opened 2020-02-04 15:40 UTC
### Preconditions (*)

1. 2.4-develop
2. php7.3
3. Default English locale

### Steps to reproduce (*)

1. Enable DOB field from customer configuration (Show required)
2. Go to create new customer page

### Expected result (*)

1. Form register customer should pass with valid dob

### Actual result (*)

1. Form still show date of birth invalid and not allow to submit
![Screenshot from 2020-02-04 22-38-25](https://user-images.githubusercontent.com/1908873/73759975-4f0f5b00-479f-11ea-8dee-8bb49eafc772.png)

**Comment by mrtuvn** [comment] 2020-02-04 15:41
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-04 15:42
Hi @mrtuvn. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-04 15:42
Hi @mrtuvn, here is your [Magento instance](https://i-26700-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26700-2-4-develop.instances.magento-community.engineering/admin_9e67](https://i-26700-2-4-develop.instances.magento-community.engineering/admin_9e67)
Login: `4dbca955` Password: `82415b898f5a`
Instance will be terminated in up to 3 hours.

**Comment by mrtuvn** [comment] 2020-02-04 15:46
yes i have able to reproduced the issue on vanilla Magento instance following steps to reproduce

**Comment by krishprakash** [comment] 2020-02-05 04:36
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-05 04:36
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-05 04:36
Hi @krishprakash, here is your [Magento instance](https://i-26700-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26700-2-4-develop.instances.magento-community.engineering/admin_5e87](https://i-26700-2-4-develop.instances.magento-community.engineering/admin_5e87)
Login: `66996247` Password: `aeded9ca1339`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2020-02-05 04:43
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31117` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sudheers-kensium** [comment] 2020-02-05 07:19
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-05 07:19
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-05 07:20
Hi @sudheers-kensium, here is your [Magento instance](https://i-26700-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26700-2-4-develop.instances.magento-community.engineering/admin_7579](https://i-26700-2-4-develop.instances.magento-community.engineering/admin_7579)
Login: `2cba6bf0` Password: `ba9a4fd2ed5b`
Instance will be terminated in up to 3 hours.

**Comment by mrtuvn** [comment] 2020-02-06 11:20
After workaround this i found problem seem related with dateformat + momenjs validate

var test = moment("09/12/1911", "M/d/Y");
invalid

var test =  moment("09/12/1911", "M/D/Y"); <= Work
valid

**Comment by viveksingh55** [comment] 2020-02-29 09:20
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-29 09:21
Hi @viveksingh55. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-29 09:22
Hi @viveksingh55, here is your [Magento instance](https://i-26700-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26700-2-4-develop.instances.magento-community.engineering/admin_78e8](https://i-26700-2-4-develop.instances.magento-community.engineering/admin_78e8)
Login: `52732e76` Password: `5792c4348ae6`
Instance will be terminated in up to 3 hours.

**Comment by bubasuma** [comment] 2020-03-12 14:41
Internal Magento team is working on this issue right now.

**Comment by magento-engcom-team** [comment] 2020-03-26 17:12
Hi @mrtuvn, @monikachintu, @sertlab. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. 

The fix will be available with the upcoming `2.4.0` release.

**Closed as completed by magento-engcom-team** 2020-03-26 17:12 UTC
Labels: Issue: Ready for Work, Component: Customer, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Reproduced on 2.4.x, Fixed in 2.4.x, Reported on 2.4.0

**Comment by azambon** [comment] 2020-05-11 15:19
Fixed in 2.4, but this issue persists in 2.3

**Comment by hostep** [comment] 2020-07-02 11:41
Looks like this is the commit which fixed it: [MC-31117](https://github.com/magento/magento2/commit/4ecae3093cfc04c0a7d66045e0b54b30c73112b3)
