### ISSUE TITLE
Email encoding leads to problems in several clients - add ENCODING_QUOTEDPRINTABLE

### ISSUE THREAD

**Issue by klein0r** [magento/magento2#22065] opened 2019-03-30 19:36 UTC
### Preconditions (*)

1. Install Magento 2.2.8 or 2.3+
2. PHP 7.1.26

### Steps to reproduce (*)

1. Create an email template with umlauts or other chars like ```ö ä ü ß €```
2. Send the email

### Expected result (*)

1. Readable email

### Actual result (*)

1. Chars are not displayed correctly since ZF2 mail

![Screenshot 2019-03-30 at 20 33 46](https://user-images.githubusercontent.com/1959049/55280826-376b7880-532b-11e9-85bd-7646fb20d334.png)

Solution: Add ENCODING_QUOTEDPRINTABLE as encoding to Zend_Mime_Parts

vendor/magento/framework/Mail/Message.php:168
```
    private function createHtmlMimeFromString($htmlBody)
    {
        $htmlPart = new Part($htmlBody);
        $htmlPart->setEncoding(\Zend\Mime\Mime::ENCODING_QUOTEDPRINTABLE);
        $htmlPart->setCharset($this->zendMessage->getEncoding());
        $htmlPart->setType(Mime::TYPE_HTML);
        $mimeMessage = new \Zend\Mime\Message();
        $mimeMessage->addPart($htmlPart);
        return $mimeMessage;
    }
```

**Comment by gwharton** [comment] 2019-04-02 01:31
In addition to the above, since 2.2.8, and presumably in 2.3 plain text emails are no longer sent as MIME, and so also do not display character encoding properly. See #22103

**Comment by gwharton** [comment] 2019-04-02 02:10
In 2.2.7 plain text emails were sent including the following headers

```
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: quoted-printable
Content-Disposition: =?utf-8?Q?=3D=3Fbase64=3FQ=3Finline=3F=3D?=
Subject: =?utf-8?Q?=E2=9C=85=20Order=20#005071?=
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: quoted-printable
Content-Disposition: =?utf-8?Q?=3D=3Fbase64=3FQ=3F=3D3D=3D3Fbase64=3D3FQ=3D3Finline=3D3F=3D3D=3F=3D?=
MIME-Version: 1.0

Hello,=0D=0A=0D=0AYou are receiving this email because you have placed 
```
In 2.2.8 the equivalent email is sent
```
Subject: âœ… Order #005252

Hello,

You are receiving this email because
```

**Comment by gwharton** [comment] 2019-04-02 02:45
I don't understand why Magento has changed plain text emails to non MIME emails. It means I can't use foreign characters or add attachments anymore! Grrr.

**Comment by magento-engcom-team** [comment] 2019-04-08 08:30
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99083`, `MAGETWO-99084` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rvoronovmeticulosity** [comment] 2019-04-13 13:19
#cdkyiv2019

**Comment by magento-engcom-team** [comment] 2019-04-13 13:20
@rvoronovmeticulosity thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by rvoronovmeticulosity** [comment] 2019-04-13 14:19
Can't reproduce the bug. Not actually anymore

**Closed as completed** 2019-04-13 14:19 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, good first issue, Component: Framework/Mail, Event: cdkyiv2019

**Comment by klein0r** [comment] 2019-04-13 14:39
@rvoronovmeticulosity Which email clients have been tested?

**Comment by Nazar65** [comment] 2019-04-13 16:18
@rvoronovmeticulosity lets just close issue if you not able to reproduce :+1:

**Comment by gwharton** [comment] 2019-04-13 16:54
Unable to reproduce on Thunderbird 60.6.1
