### ISSUE TITLE
Admin sidebar top links not reachable

### ISSUE THREAD

**Issue by tgsergiu** [magento/magento2#7321] opened 2016-11-04 17:14 UTC
Hello,

I am trying to add some products and after saving the problem the admin sidebar has some problems. i can not reach the top links. ther is no more scroll. I know the buttons are there but i can not reach them.
Sorry if i do not follow the exact rules of explaining but i am doing my best. I attached a screenshot.
I am usig a toshia satellite 11 inch.
![issue](https://cloud.githubusercontent.com/assets/23265106/20015170/e4a5eaec-a2c2-11e6-8d4e-e6fd48d63d9d.png)

**Comment by rganin** [comment] 2016-11-07 11:14
Thanks for reporting, Seems it's caused by system notifications block in the top along with success message. Page refresh helps.
Created internal ticket: MAGETWO-60580.

**Comment by magento-engcom-team** [comment] 2017-10-06 06:30
@tgsergiu, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-06 06:30 UTC
Labels: Issue: Ready for Work, bug report, Issue: Format is not valid
