### ISSUE TITLE
Error while installing sample data in magento 2.4.1

### ISSUE THREAD

**Issue by ajmalbuffy** [magento/magento2#31558] opened 2021-01-05 19:37 UTC
**Preconditions:**
Getting the below error while trying to install sample data and upgrading the setup in Magento 2.4.1
Error: **Unable to apply data patch Magento\CatalogRuleSampleData\Setup\Patch\Data\InstallCatalogRuleSampleData for module Magento_CatalogRuleSampleData. Original exception message: Rolled back transaction has not been completed correctly.**

 **Steps to reproduce:** 
Step:1 Install Magento 2.4.1 using composer and CLI
Step:2 Set to developer mode and run the sample data deploy and setup upgrade command 
Commands used:
**bin/magento sampledata:deploy**
**bin/magento setup:upgrade**

**Expected result:**
setup:upgrade should be successful without any error and the site should be loaded with the sample data.

**Actual result:**
Getting the below error while trying to upgrade the setup after deploying the sample data.
Error: **Unable to apply data patch Magento\CatalogRuleSampleData\Setup\Patch\Data\InstallCatalogRuleSampleData for module Magento_CatalogRuleSampleData. Original exception message: Rolled back transaction has not been completed correctly.**

**Environment details:** I am using 
ubuntu 20.04 
PHP 7.3.25 
apache 2.4.46 
MYSQL 5.7.32 
elastic search 7.6.0 
Magento 2.4.1
composer 1.10.19

Recently I have installed the Magento 2.4.1 community edition in Ubuntu 20.04, Installation went correct and while I try to set sample data I got the error "Unable to apply data patch Magento\CatalogRuleSampleData\Setup\Patch\Data\InstallCatalogRuleSampleData for module Magento_CatalogRuleSampleData. Original exception message: Rolled back transaction has not been completed correctly."

I have searched about this issue and tried all the solution which have been provided

**Tried solutions:**

1. Switch to developer mode before installing sample data
2. Using MySQL 5.7
3. Remove the sample data and rerun again
4. Remove the corn job before installing the sample data but none of the solutions worked for me. 
![Screenshot from 2021-01-06 00-49-40](https://user-images.githubusercontent.com/11898037/103691059-90b21280-4fbb-11eb-91df-25c796990aad.png)

As a temporary fix, I have disabled the Magento_CatalogRuleSampleData Magento_SalesRuleSampleData and using the local site.

Anybody, please suggest a proper fix for this issue.

**Comment by mrtuvn** [comment] 2021-01-06 00:44
Have you try switch php version from 7.3 to 7.4( Ex: 7.4.9)

**Comment by mrtuvn** [comment] 2021-01-06 00:58
Another problem come from 
https://github.com/magento/magento2-sample-data/blob/2.4-develop/app/code/Magento/CatalogRuleSampleData/fixtures/catalog_rules.csv
Invalid json in csv in column `conditions_serialized`. As my view in code magento try to process string replace data before insert to database. You can see reference with %url_key=%
Before i still get issue similiar you but recently i don't get issue. Maybe this fixed or something else

**Comment by engcom-Bravo** [comment] 2021-01-06 13:12
Hello @ajmalbuffy 

Thank you for your report.

This is a known issue and has been previously reported, https://github.com/magento/magento2/issues/30685 Here is the PR wich fixes the issue https://github.com/magento/magento2/pull/30928
It will be fixed in the next release.

We are closing this issue as Duplicate of #30685

**Closed as completed by engcom-Bravo** 2021-01-06 13:12 UTC
Labels: duplicate, Issue: ready for confirmation, not-confirmed

**Comment by moloni-es** [comment] 2021-01-14 15:48
I have my Magento installation updated to the latest available version. 
How can I apply this patch to make the sample data work in 2.4.1?

**Comment by unic0rn** [comment] 2021-02-13 00:53
> Hello @ajmalbuffy
> 
> Thank you for your report.
> 
> This is a known issue and has been previously reported, #30685 Here is the PR wich fixes the issue #30928
> It will be fixed in the next release.
> 
> We are closing this issue as Duplicate of #30685

Unfortunately, I was getting the same error with the latest Magento release (as well as github clone). Disabling GTIDs in mysql fixed it.

**Comment by unic0rn** [comment] 2021-02-14 18:24
Since someone found the above funny, here's the exact error from system.log:

`[2021-02-13 00:11:43] main.ERROR: Sample Data error: SQLSTATE[HY000]: General error: 1787 Statement violates GTID consistency: CREATE TEMPORARY TABLE and DROP TEMPORARY TABLE can only be executed outside transactional context.  These statements are also not allowed in a function or trigger because functions and triggers are also considered to be multi-statement transactions., query was: CREATE TEMPORARY TABLE `tmp_select_RJittlP0DAn81zsDeB6aLI5XAtLrFjNF` (PRIMARY KEY(`url_rewrite_id`),INDEX `HASHKEY_ENTITY_STORE` USING HASH(`hash_key`),INDEX `ENTITY_STORE` USING HASH(`entity_id`,`store_id`)) ENGINE=`INNODB` IGNORE (SELECT `e`.*, CONCAT(e.store_id,'_', e.entity_id) AS `hash_key` FROM `url_rewrite` AS `e` WHERE (entity_type = 'category') AND (entity_id IN('3'))) [] []`

End result is the same error message as mentioned earlier here. Fresh install with GTIDs disabled works fine, but that's obviously just an ugly workaround. Looks like a different issue, just causing the same error from install script - and with people not posting exact system.log errors, the result is people looking for a solution find an old issue like this one, think it is fixed, but in reality they're encountering different bug. It's why I've posted about it here, mentioning "the same error", not "the same issue". I may open a new issue later on, for now I don't have time to replicate it to paste proper logs.

**Comment by mrtuvn** [comment] 2021-02-16 10:45
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/mysql.html
Maybe is not a bug this is feature LOLs

**Comment by PascalBrouwers** [comment] 2022-03-01 07:46
Issue still exists in 2.4.3. The patch in https://github.com/magento/magento2/pull/30928 does not fix it as this PR is already in 2.4.3.

**Comment by Jinnah34** [comment] 2022-10-18 06:09
I also received the same error and invested four days rectifying it.

I also tried the above solution, i.e., commenting the line under install function from vendor/magento/module catalogue rule sample data/setup/installer.php and vendor/magento/module sales rule sample data/setup/installer.php. It too worked, but only temporarily. Because after following the above procedure, you cannot see the products from your Magento homepage, just banners only visible to you.

The real problem is that there is no sufficient space to deploy the sample data. Clear more than 4GB of space on your system and try it. It will work.

**Comment by jarvisa98** [comment] 2023-04-03 10:45
Installing sample data in Magento 2.4.1 can be a useful way to explore the platform's features and functionality. However, sometimes errors may occur during the installation process. One common error that may occur is a "SQLSTATE[23000]: Integrity constraint violation" error. This error typically indicates that there is a duplicate entry in the database. To resolve this error, you can try running the installation process again [Pinterest Image Downloader ](https://pintdd.com/pinterest-image-downloader/)but make sure to clear your database and remove any previous installation attempts. You can also try increasing the memory limit in your php.ini file to ensure that the installation process has enough resources to complete successfully. Additionally, you may need to check your file permissions and make sure that the web server has the necessary permissions to access and modify the files during the installation process. By troubleshooting these potential issues, you can overcome errors and successfully install sample data in Magento 2.4.1.

**Comment by smith76432** [comment] 2023-04-04 21:50
Installing sample data in Magento 2.4.1 can be a difficult task, and errors can arise during the process. If an error occurs, it is important to troubleshoot the issue in order to ensure that the data is installed correctly. Common errors include missing files, incompatibilities between the sample data and the version of Magento being used, and issues with the database. It is important to ensure that all prerequisites are met before installing sample data of [do cabling](https://dabcontracting.com/cabling-for-camera/) , and to check the log files to help diagnose the exact cause of the error. It is also important to remember that the sample data should only be installed on a development version of the site, and not on a live site.

**Comment by jarvisa98** [comment] 2023-04-07 11:15
Magento is a popular e-commerce platform that allows businesses to create and manage online stores. While installing sample data is a common practice for Magento users, sometimes errors can occur during the installation process to [Pintdd](https://pintdd.com/)

One common error that users may encounter when installing sample data in Magento is a "SQLSTATE[23000]: Integrity constraint violation" error. This error typically occurs when there is a conflict between the sample data being installed and the existing data in the database.

**Comment by Amelia792** [comment] 2023-04-07 17:31
I am having an issue while installing sample data in Magento 2.4.1. Whenever I try to install sample data, I get an error message saying that the installation failed. This is causing me to be unable to use any of the features from the sample data of [rice purity test](https://ricepuritytestnow.com/), which I need to develop my website. I have tried to troubleshoot the issue by looking at the logs, but I am unable to find out the exact cause of the error. Can someone please help me figure out the issue and get the sample data installed properly?
