### ISSUE TITLE
Store switcher not sliding up and down, only dropdown arrow working 

### ISSUE THREAD

**Issue by cedarvinda** [magento/magento2#20259] opened 2019-01-14 06:42 UTC
Store switcher not sliding up and down, only dropdown arrow working 

### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.2

### Steps to reproduce (*)

Step 1: Go to frontend in mobile device
Step 2: click on toggle in left top corner
Step 3: Go to setting tab and see store switcher and click on label (Ref screenshot)
   
### Expected result (*)

Dropdown should open and close as arrow working

### Actual result (*)

![mobile](https://user-images.githubusercontent.com/26018716/51098808-e996a800-17f2-11e9-9ac2-faa59c31006e.png)

**Comment by magento-engcom-team** [comment] 2019-01-14 06:42
Hi @cedarvinda. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@cedarvinda do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-14 06:42
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment] 2019-01-14 06:42
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-01-14 06:43
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-01-14 06:43
Hi @shikhamis11, here is your [Magento instance](https://i-20259-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20259-2-3-develop.instances.magento-community.engineering/admin](https://i-20259-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-01-14 06:46
@shikhamis11 Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-01-14 06:47
@shikhamis11 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97609`, `MAGETWO-97610` were created

**Comment by magento-engcom-team** [comment] 2019-01-14 06:56
Hi @milindsingh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-01-14 15:59
Hi @sdzhepa. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-01-23 17:47
Hi @cedarvinda. Thank you for your report. 
The issue has been fixed in magento/magento2#20260 by @cedarvinda in 2.3-develop branch
Related commit(s):
 - [8bc0309bf756c59333dbbe75d24cd612b1353507](https://github.com/magento/magento2/commit/8bc0309bf756c59333dbbe75d24cd612b1353507)
 - [905368ce2b036211d209ed18da5898aafbdd1667](https://github.com/magento/magento2/commit/905368ce2b036211d209ed18da5898aafbdd1667)
 - [ec33182beef6e13f9caf2c5fc4f4d731bebccf50](https://github.com/magento/magento2/commit/ec33182beef6e13f9caf2c5fc4f4d731bebccf50)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2019-01-23 17:47 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Store, Area: Design/Frontend

**Comment by magento-engcom-team** [comment] 2019-02-04 20:15
Hi @cedarvinda. Thank you for your report. 
The issue has been fixed in magento/magento2#20540 by @irajneeshgupta in 2.2-develop branch
Related commit(s):
 - [4741489674e363357de9fddb3920924ab1177009](https://github.com/magento/magento2/commit/4741489674e363357de9fddb3920924ab1177009)
 - [cd75f2928d56785e86b5235e56727a571cc1d8ff](https://github.com/magento/magento2/commit/cd75f2928d56785e86b5235e56727a571cc1d8ff)
 - [1f01d9258b7768e3156be05bb0b2cb3537bcfa1e](https://github.com/magento/magento2/commit/1f01d9258b7768e3156be05bb0b2cb3537bcfa1e)

The fix will be available with the upcoming 2.2.8 release.
