### ISSUE TITLE
Search box in admin interface auto-filled with comma by bookmark data which causes errors

### ISSUE THREAD

**Issue by rhertogh** [magento/magento2#6499] opened 2016-09-05 15:30 UTC
### Preconditions

1. Magento 2.1.0, PHP 5.6.24 MySQL 5.6.27
2. Not yet sure what caused the insertion of the incorrect bookmark data (see steps to reproduce)
### Steps to reproduce

1. Insert incorrect bookmark data in database:  `INSERT INTO`ui_bookmark`VALUES (1,1,'cms_page_listing','current',0,NULL,'{\"current\":{\"search\":{\"value\":[\"\",\"\"]},\"filters\":{\"applied\":{\"placeholder\":[true,true]}},\"columns\":{\"page_id\":{\"visible\":[true,true],\"sorting\":false},\"title\":{\"visible\":[true,true],\"sorting\":false},\"identifier\":{\"visible\":[true,true],\"sorting\":false},\"store_id\":{\"visible\":[true,true],\"sorting\":[false,false]},\"meta_title\":{\"visible\":[false,false],\"sorting\":false},\"meta_keywords\":{\"visible\":[false,false],\"sorting\":false},\"meta_description\":{\"visible\":[false,false],\"sorting\":false},\"ids\":{\"visible\":[true,true],\"sorting\":[false,false]},\"page_layout\":{\"visible\":[true,true],\"sorting\":false},\"is_active\":{\"visible\":[true,true],\"sorting\":false},\"custom_theme\":{\"visible\":[false,false],\"sorting\":false},\"custom_root_template\":{\"visible\":[false,false],\"sorting\":false},\"actions\":{\"visible\":[true,true],\"sorting\":[false,false]},\"creation_time\":{\"visible\":[true,true],\"sorting\":false},\"update_time\":{\"visible\":[true,true],\"sorting\":false},\"custom_theme_from\":{\"visible\":[false,false],\"sorting\":false},\"custom_theme_to\":{\"visible\":[false,false],\"sorting\":[false,false]}},\"paging\":{\"options\":{\"20\":{\"value\":20,\"label\":20},\"30\":{\"value\":30,\"label\":30},\"50\":{\"value\":50,\"label\":50},\"100\":{\"value\":100,\"label\":100},\"200\":{\"value\":200,\"label\":200},\"201\":{\"value\":20,\"label\":20},\"202\":{\"value\":30,\"label\":30},\"203\":{\"value\":50,\"label\":50},\"204\":{\"value\":100,\"label\":100},\"205\":{\"value\":200,\"label\":200}},\"value\":[20,20]},\"displayMode\":[\"grid\",\"grid\"],\"positions\":{\"ids\":0,\"page_id\":1,\"title\":2,\"identifier\":3,\"page_layout\":4,\"store_id\":5,\"is_active\":6,\"creation_time\":7,\"update_time\":8,\"custom_theme_from\":9,\"custom_theme_to\":10,\"custom_theme\":11,\"custom_root_template\":12,\"meta_title\":13,\"meta_keywords\":14,\"meta_description\":15,\"actions\":16}}}','0000-00-00 00:00:00','0000-00-00 00:00:00');`
2. In the admin interface go to: Content -> Pages
### Expected result

1. A list of pages is shown
### Actual result

frontend:

![Magento 2 admin interface comma bug](http://image.prntscr.com/image/651fa29882a44727a8c3d2e1cb726112.png)

backend:

`a:4:{i:0;s:171:"Warning: strtoupper() expects parameter 1 to be string, array given in /var/www/vhosts/magento2/vendor/magento/module-ui/Component/Listing/Columns/Column.php on line 136";i:1;s:5786:"#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'strtoupper() ex...', '/var/www/vhosts...', 136, Array)
#1 /var/www/vhosts/magento2/vendor/magento/module-ui/Component/Listing/Columns/Column.php(136): strtoupper(Array)
#2 /var/www/vhosts/magento2/vendor/magento/module-ui/Component/Listing/Columns/Column.php(93): Magento\Ui\Component\Listing\Columns\Column->applySorting()
#3 /var/www/vhosts/magento2/vendor/magento/module-ui/Controller/Adminhtml/Index/Render.php(46): Magento\Ui\Component\Listing\Columns\Column->prepare()
#4 /var/www/vhosts/magento2/vendor/magento/module-ui/Controller/Adminhtml/Index/Render.php(44): Magento\Ui\Controller\Adminhtml\Index\Render->prepareComponent(Object(Magento\Ui\Component\Listing\Columns\Date))
#5 /var/www/vhosts/magento2/vendor/magento/module-ui/Controller/Adminhtml/Index/Render.php(44): Magento\Ui\Controller\Adminhtml\Index\Render->prepareComponent(Object(Magento\Ui\Component\Listing\Columns))
#6 /var/www/vhosts/magento2/vendor/magento/module-ui/Controller/Adminhtml/Index/Render.php(31): Magento\Ui\Controller\Adminhtml\Index\Render->prepareComponent(Object(Magento\Ui\Component\Listing))
#7 /var/www/vhosts/magento2/var/generation/Magento/Ui/Controller/Adminhtml/Index/Render/Interceptor.php(24): Magento\Ui\Controller\Adminhtml\Index\Render->execute()
#8 /var/www/vhosts/magento2/vendor/magento/framework/App/Action/Action.php(102): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->execute()
#9 /var/www/vhosts/magento2/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#10 /var/www/vhosts/magento2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#11 /var/www/vhosts/magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callParent('dispatch', Array)
#12 /var/www/vhosts/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Ui\Cont...', 'dispatch', Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Array, 'adminAuthentica...')
#13 /var/www/vhosts/magento2/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#14 /var/www/vhosts/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#15 /var/www/vhosts/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Ui\Cont...', 'dispatch', Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Array, 'adminMassaction...')
#16 /var/www/vhosts/magento2/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#17 /var/www/vhosts/magento2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 /var/www/vhosts/magento2/var/generation/Magento/Ui/Controller/Adminhtml/Index/Render/Interceptor.php(52): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callPlugins('dispatch', Array, Array)
#19 /var/www/vhosts/magento2/vendor/magento/framework/App/FrontController.php(55): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#20 /var/www/vhosts/magento2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /var/www/vhosts/magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#22 /var/www/vhosts/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#23 /var/www/vhosts/magento2/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#24 /var/www/vhosts/magento2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#25 /var/www/vhosts/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#26 /var/www/vhosts/magento2/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#27 /var/www/vhosts/magento2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#28 /var/www/vhosts/magento2/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#29 {main}";s:3:"url";s:1329:"/admin/mui/index/render/key/1160d4369b433a7df0f80b09c07a14b71440a082a7b963bd151dc6f2753e2d81/?namespace=cms_page_listing&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&search%5B%5D=&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&paging%5BpageSize%5D=20&paging%5Bcurrent%5D=1&sorting%5Bfield%5D=custom_theme_to&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&isAjax=true";s:11:"script_name";s:10:"/index.php";}`

**Comment by andimov** [comment] 2016-09-05 16:18
@rhertogh 
This is not the expected use case.
Please, explain more if you think this is a Magento bug.

**Comment by rhertogh** [comment] 2016-09-05 16:20
The incorrect data was not inserted manually but by magento itself. The sql above is just to reproduce the error.

**Comment by andimov** [comment] 2016-09-13 07:15
"Steps to reproduce" not clarify the reason for the incorrect data.
So, there a missed steps and we can't reproduce it or be sure that here is a Magento bug.
Please, clarify steps to reproduce or preconditions to allow us research this issue.

**Comment by andimov** [comment] 2016-09-27 09:40
@rhertogh 
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Closed as completed by andimov** 2016-09-27 09:40 UTC
Labels: Progress: needs update
