### ISSUE TITLE
Magento2: Success/Error messages not auto hiding

### ISSUE THREAD

**Issue by deepak-netwin** [magento/magento2#7660] opened 2016-12-02 09:24 UTC
### Preconditions
1. Installed Magento2.1.1 on local. Downloaded from magento site.
2. Installed on local wampserver3 with php 7 and mysql 5.7.
3. Created my custom theme and set from backend.
4. Created separate admin account and Admin Session Lifetime (seconds) set to 31536000 at backend.
5. Admin Account Sharing = No at backend.
6. All other settings are default one.

### Step to reproduce
Submit contact form or forgot password form
### Expected result
Success massage showing at top
### Actual result
When I register or submit contact form or forgot password form, its showing success message at top. But the messages are not auto hiding. They are always showing on each page I'm browsing.
Please see this http://prntscr.com/dee0ij

**Comment by quienti** [comment] 2016-12-06 17:41
Probably fixed in develop branch: https://github.com/magento/magento2/commit/9515999f75fc728084079b8aae7ccc784cd8c1f3

**Comment by vzabaznov** [comment] 2016-12-14 12:10
@deepak-netwin can you check please https://github.com/magento/magento2/commit/9515999f75fc728084079b8aae7ccc784cd8c1f3 and give us update

**Comment by deepak-netwin** [comment] 2016-12-14 12:42
@vzabaznov I already tried it but couldn't fix.

**Comment by magento-engcom-team** [comment] 2017-09-25 22:00
@deepak-netwin, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Closed as completed by magento-engcom-team** 2017-09-25 22:00 UTC
Labels: bug report, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is not valid
