### ISSUE TITLE
Typo in error message "Table <tablename> is not exists"

### ISSUE THREAD

**Issue by fwolfst** [magento/magento2#8529] opened 2017-02-13 12:28 UTC
Magento 2.1.4 using the data migration tool (reported there: https://github.com/magento/data-migration-tool/issues/242 - but the text probably stems from magento 'core').

[Zend_Db_Exception]
Table "customgrid_grid" is not exists

Should read ... "does not exist".

**Comment by bvrbanec** [comment] 2017-03-16 14:38
Issue in progress @bvrbanec

**Comment by magento-engcom-team** [comment] 2017-11-28 12:30
@fwolfst, thank you for your report.
The issue is already fixed in develop branch, 2.2.1

**Closed as completed by magento-engcom-team** 2017-11-28 12:30 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid
