### ISSUE TITLE
[2.1.5] Admin - Products Category dropdown blank

### ISSUE THREAD

**Issue by tonyr101** [magento/magento2#10467] opened 2017-08-08 17:15 UTC
### Preconditions
After updating Magento from 2.1.1 to 2.1.5 (via composer) I've found that the "Categories" field in the product admin is blank? The products are showing correctly on the frontend but I am unable to edit / add or remove categories from products in the admin.

1. Magento CE 2.1.5
2. PHP 7.0 

### Steps to reproduce
1. Upgrade from 2.1.1 > 2.1.5 + reindex and flush caches
2. Go to Admin > Products > Catalog and select any product
3. Categories select box is blank.

### Expected result
1. Should be able to assign products to categories!

### Actual result
![missing categories](http://www2.exclusivemirrors.co.uk/external/missingcats.JPG)

**Comment by magento-engcom-team** [comment] 2017-09-19 07:56
We are closing this issue because we cannot reproduce this issue as described. If you have questions, please refer to a question and answer site, such as Stack Exchange and the Magento Forums, where Magento community members can quickly provide recommendations and advice.

**Closed as completed by magento-engcom-team** 2017-09-19 07:56 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid

**Comment by JorenRapini** [comment] 2021-05-27 21:13
> ### Preconditions
> After updating Magento from 2.1.1 to 2.1.5 (via composer) I've found that the "Categories" field in the product admin is blank? The products are showing correctly on the frontend but I am unable to edit / add or remove categories from products in the admin.
> 
> 1. Magento CE 2.1.5
> 2. PHP 7.0
> 
> ### Steps to reproduce
> 1. Upgrade from 2.1.1 > 2.1.5 + reindex and flush caches
> 2. Go to Admin > Products > Catalog and select any product
> 3. Categories select box is blank.
> 
> ### Expected result
> 1. Should be able to assign products to categories!
> 
> ### Actual result
> ![missing categories](https://camo.githubusercontent.com/63d22e0f954d7aa27511fd3aec9b803ab35c7260e4b04374ed97562aa9ebfffa/687474703a2f2f777777322e6578636c75736976656d6972726f72732e636f2e756b2f65787465726e616c2f6d697373696e67636174732e4a5047)

Did you ever find a solution? We just ran into this exact same problem
