### ISSUE TITLE
Upgrade CE 2.1.0 to 2.1.1: Invalid FULLTEXT index for customer_flat_grid table

### ISSUE THREAD

**Issue by boldhedgehog** [magento/magento2#6973] opened 2016-10-12 14:38 UTC
### Preconditions
1. Have installed Magento CE 2.1.0 with sample data
2. MySQL version: 5.6.33
### Steps to reproduce
1. Upgrade Magento CE from 2.1.0 to 2.1.1 with composer
2. run php bin/magento setup:upgrade
### Expected result
1. setup:upgrade completes successfully
### Actual result
1. setup:upgrade fails with this MySQL error during upgrading : 
   `Error in query (1170): BLOB/TEXT column 'created_in' used in key specification without a key length`
   on step `Module 'Magento_Customer': Upgrading data..`

MySQL query:

``` sql
CREATE TABLE IF NOT EXISTS `customer_grid_flat` (                                                                                                                                    
    `entity_id` int UNSIGNED NOT NULL COMMENT 'Entity ID' ,                                                                                                           
    `name` text NULL COMMENT 'Name' ,                                                                                                                                 
    `email` varchar(255) NULL COMMENT 'Email' ,                                                                                                                       
    `group_id` int NULL COMMENT 'Group_id' ,                                                                                                                          
    `created_at` timestamp NULL default NULL COMMENT 'Created_at' ,                                                                                                   
    `website_id` int NULL COMMENT 'Website_id' ,                                                                                                                      
    `confirmation` varchar(255) NULL COMMENT 'Confirmation' ,                                                                                                         
    `created_in` text NULL COMMENT 'Created_in' ,                                                                                                                     
    `dob` date NULL COMMENT 'Dob' ,                                                                                                                                   
    `gender` int NULL COMMENT 'Gender' ,                                                                                                                              
    `taxvat` varchar(255) NULL COMMENT 'Taxvat' ,                                                                                                                     
    `lock_expires` timestamp NULL default NULL COMMENT 'Lock_expires' ,                                                                                               
    `shipping_full` text NULL COMMENT 'Shipping_full' ,                                                                                                               
    `billing_full` text NULL COMMENT 'Billing_full' ,                                                                                                                 
    `billing_firstname` varchar(255) NULL COMMENT 'Billing_firstname' ,                                                                                               
    `billing_lastname` varchar(255) NULL COMMENT 'Billing_lastname' ,                                                                                                 
    `billing_telephone` varchar(255) NULL COMMENT 'Billing_telephone' ,                                                                                               
    `billing_postcode` varchar(255) NULL COMMENT 'Billing_postcode' ,                                                                                                 
    `billing_country_id` varchar(255) NULL COMMENT 'Billing_country_id' ,                                                                                             
    `billing_region` varchar(255) NULL COMMENT 'Billing_region' ,                                                                                                     
    `billing_street` varchar(255) NULL COMMENT 'Billing_street' ,                                                                                                     
    `billing_city` varchar(255) NULL COMMENT 'Billing_city' ,                                                                                                         
    `billing_fax` varchar(255) NULL COMMENT 'Billing_fax' ,                                                                                                           
    `billing_vat_id` varchar(255) NULL COMMENT 'Billing_vat_id' ,                                                                                                     
    `billing_company` varchar(255) NULL COMMENT 'Billing_company' ,                                                                                                   
    PRIMARY KEY (`entity_id`),                                                                                                                                        
    INDEX `CUSTOMER_GRID_FLAT_GROUP_ID` (`group_id`),                                                                                                                 
    INDEX `CUSTOMER_GRID_FLAT_CREATED_AT` (`created_at`),                                                                                                             
    INDEX `CUSTOMER_GRID_FLAT_WEBSITE_ID` (`website_id`),                                                                                                             
    INDEX `CUSTOMER_GRID_FLAT_CONFIRMATION` (`confirmation`),                                                                                                         
    INDEX `CUSTOMER_GRID_FLAT_CREATED_IN` (`created_in`),                                                                                                             
    INDEX `CUSTOMER_GRID_FLAT_DOB` (`dob`),                                                                                                                           
    INDEX `CUSTOMER_GRID_FLAT_GENDER` (`gender`),                                                                                                                     
    INDEX `CUSTOMER_GRID_FLAT_BILLING_COUNTRY_ID` (`billing_country_id`),                                                                                             
    FULLTEXT `FTI_AC9FBFAE9FBD3A0B02DBA986349612A6` (`name`, `email`, `taxvat`, `shipping_full`, `billing_full`, `billing_firstname`, 
`billing_lastname`, `billing_telephone`, `billing_postcode`, `billing_region`, `billing_street`, `billing_city`, `billing_fax`, `billing_vat_id`, `billing_company`)                              
  ) COMMENT='customer_grid_flat' ENGINE=innodb charset=utf8 COLLATE=utf8_general_ci
```

Stackoverflow article: http://stackoverflow.com/questions/1827063/mysql-error-key-specification-without-a-key-length

**Comment by sevos1984** [comment] 2016-10-18 15:49
Can't reproduce this, do you have any customization in customer module? Try doing it on clean magento install.

**Comment by sevos1984** [comment] 2016-11-01 09:27
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-11-01 09:27 UTC
Labels: bug report, Progress: needs update, Component: Setup
