### ISSUE TITLE
Fatal error  when i try to reorder from admin

### ISSUE THREAD

**Issue by jasminrathod** [magento/magento2#31124] opened 2020-12-02 10:38 UTC
### Preconditions (*)

1. 2.3.6
2. When i try to "REORDER" then  fatal error show.

### Steps to reproduce (*)

1.  go to admin side sales order check is there any order there or not if not then place one order. after that set that product to out of stock. after that try to reorder from admin at that time it show fatal error in admin
2. in my site all product is configure product

### Expected result (*)

1. Exception #0 (Magento\Framework\Exception\LocalizedException): This product is out of stock.
2. if product out of stock then show out of stock message on page but it throw a error

### Actual result (*)

1. Exception #0 (Magento\Framework\Exception\LocalizedException): This product is out of stock.
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by jasminrathod** [comment] 2020-12-02 10:39
@magento I am working on this

**Comment by engcom-Alfa** [comment] 2020-12-02 13:11
Hi @jasminrathod . Thank you for your report!

Could you clarify an actual result? Because we are not able to reproduce the fatal error when trying to reorder on clean 2.4-develop.

**Manual testing scenario:**

1. Create a configurable product (Name **_Test_** for ex.)
2. Create an order;
3. Set "out of stock" for **_Test_** product;
4. Go to Sales -> Orders and open created before order for edit;
5. Click on the **Reorder** button;

**Actual Result:** :heavy_check_mark: The product is out of stock

![Screenshot from 2020-12-02 13-30-16](https://user-images.githubusercontent.com/51679138/100876319-e58bd600-34af-11eb-9125-2ad8d1ae18d2.png)

 :heavy_multiplication_x: See `exception.log `file:

![Screenshot from 2020-12-02 14-01-27](https://user-images.githubusercontent.com/51679138/100876421-0bb17600-34b0-11eb-9732-692c97a2de89.png)

@jasminrathod Did you mean this error in the logs or a fatal error on the reorder page?

If you still have a fatal error on the reorder page then provide us with additional information on how to get it?

Thank you!

**Comment by jasminrathod** [comment] 2020-12-02 13:15
Yes in your screeshot that is error show in page in my client site

**Comment by jasminrathod** [comment] 2020-12-02 14:00
is show me below msg on page. fatal error on page



{"0":"This product is out of stock.","1":"#1
Magento\\Sales\\Model\\AdminOrder\\Create->initFromOrderItem() called at
[vendor\/magento\/module-sales\/Model\/AdminOrder\/Create.php:534]\n#2
Magento\\Sales\\Model\\AdminOrder\\Create->initFromOrder() called at
[vendor\/magento\/module-sales\/Controller\/Adminhtml\/Order\/Create\/Reorder.php:95]\n#3
Magento\\Sales\\Controller\\Adminhtml\\Order\\Create\\Reorder->execute()
called at [vendor\/magento\/framework\/App\/Action\/Action.php:108]\n#4
Magento\\Framework\\App\\Action\\Action->dispatch() called at
[vendor\/magento\/module-backend\/App\/AbstractAction.php:248]\n#5
Magento\\Backend\\App\\AbstractAction->dispatch() called at
[vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#6
Magento\\Sales\\Controller\\Adminhtml\\Order\\Create\\Reorder\\Interceptor->___callParent()
called at
[vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#7
Magento\\Sales\\Controller\\Adminhtml\\Order\\Create\\Reorder\\Interceptor->Magento\\Framework\\Interception\\{closure}()
called at
[vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:143]\n#8
Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch()
called at
[vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#9
Magento\\Sales\\Controller\\Adminhtml\\Order\\Create\\Reorder\\Interceptor->Magento\\Framework\\Interception\\{closure}()
called at
[vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#10
Magento\\Sales\\Controller\\Adminhtml\\Order\\Create\\Reorder\\Interceptor->___callPlugins()
called at
[generated\/code\/Magento\/Sales\/Controller\/Adminhtml\/Order\/Create\/Reorder\/Interceptor.php:26]\n#11
Magento\\Sales\\Controller\\Adminhtml\\Order\\Create\\Reorder\\Interceptor->dispatch()
called at [vendor\/magento\/framework\/App\/FrontController.php:186]\n#12
Magento\\Framework\\App\\FrontController->processRequest() called at
[vendor\/magento\/framework\/App\/FrontController.php:119]\n#13
Magento\\Framework\\App\\FrontController->dispatch() called at
[vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#14
Magento\\Framework\\App\\FrontController\\Interceptor->___callParent()
called at
[vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#15
Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}()
called at
[vendor\/m2e\/ebay-amazon-magento2\/Plugin\/HealthStatus\/Magento\/Framework\/App\/FrontController.php:79]\n#16
Ess\\M2ePro\\Plugin\\HealthStatus\\Magento\\Framework\\App\\FrontController->processDispatch()
called at
[vendor\/m2e\/ebay-amazon-magento2\/Plugin\/AbstractPlugin.php:43]\n#17
Ess\\M2ePro\\Plugin\\AbstractPlugin->execute() called at
[vendor\/m2e\/ebay-amazon-magento2\/Plugin\/HealthStatus\/Magento\/Framework\/App\/FrontController.php:42]\n#18
Ess\\M2ePro\\Plugin\\HealthStatus\\Magento\\Framework\\App\\FrontController->aroundDispatch()
called at
[vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#19
Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}()
called at
[vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#20
Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins()
called at
[generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#21
Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at
[vendor\/magento\/framework\/App\/Http.php:116]\n#22
Magento\\Framework\\App\\Http->launch() called at
[generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:24]\n#23
Magento\\Framework\\App\\Http\\Interceptor->launch() called at
[vendor\/magento\/framework\/App\/Bootstrap.php:261]\n#24
Magento\\Framework\\App\\Bootstrap->run() called at
[pub\/index.php:40]\n","url":"\/admin_iltty9\/sales\/order_create\/reorder\/order_id\/17817\/key\/934c2cc9d51e33e5f89a05d794802e8ec045a8477b0abcbdcd1e39d8955a3fa2\/","script_name":"\/index.php","report_id":"b1b3dbfcf40d35d6bd5276cd89cd56d431aa9f36e32737fed5fd87d3757f3ec3"}

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jasminrathod** [comment] 2020-12-03 07:51
hi did  you find any solution??

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jasminrathod** [comment] 2020-12-04 06:39
Did you find any solution. for this

please find attachment which show on site
[image: image.png]

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jasminrathod** [comment] 2020-12-04 07:25
Create a configurable product 
Create an order;
Set "out of stock" for Test product simple 
Go to Sales -> Orders and open created before order for edit;
Click on the Reorder button;

![image](https://user-images.githubusercontent.com/75366456/101134097-dfbcfe80-362f-11eb-922e-a33c40722e6f.png)

**Comment by engcom-Alfa** [comment] 2020-12-04 14:30
@magento give me 2.4-develop instance

**Comment by jasminrathod** [comment] 2020-12-04 14:48
My magento version is 2.3.6

**Comment by WebKenth** [comment] 2021-02-15 09:40
This is still an issue

Running 2.3.6 and exception is reported @ vendor/magento/module-quote/Model/Quote.php:1691

This used to only fail silently, but it now throws a Critical exception and since nothing catches it proppely and returns a message it just exits the application. Any Magento shop running in Production mode will simply exit and show a 
![image](https://user-images.githubusercontent.com/13419123/107929595-29a05a00-6f7a-11eb-9b39-4b4fd30e4518.png) message...

**Comment by WebKenth** [comment] 2021-02-15 10:20
Expected Behaviour:

![image](https://user-images.githubusercontent.com/13419123/107933798-85b9ad00-6f7f-11eb-862a-332fa14202b9.png)


Temporary patch which is probably a very terrible solution, but atleast you can continue your work:

Using Objectmanager as the Quote class is a giant mess. I needed a decent way to checking if it was backend only
```
If an exception occurs due to ie. Product is Out of Stock the backend stops completely
@package magento/module-quote
--- Model/Quote.php
+++ Model/Quote.php
@@ -1688,7 +1688,13 @@
             }
         }
         if (!empty($errors)) {
-            throw new \Magento\Framework\Exception\LocalizedException(__(implode("\n", $errors)));
+            $objectmanager = \Magento\Framework\App\ObjectManager::getInstance();
+            $state =  $objectmanager->get('Magento\Framework\App\State');
+            if($state->getAreaCode() == 'frontend'){
+                throw new \Magento\Framework\Exception\LocalizedException(__(implode("\n", $errors)));
+            }else{
+                // Do Nothing ADMINS KNOW BEST
+            }
         }

         $this->_eventManager->dispatch('sales_quote_product_add_after', ['items' => $items]);
``` 

@jasminrathod if you still have this problem the above patch works for backend reorder

The errors are still shown but the backend nolonger exits in a critical error state

**Comment by engcom-Alfa** [comment] 2021-02-16 10:22
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment] 2021-02-16 10:37
Hi @jasminrathod @WebKenth .
Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop. Looks like the problem has already been fixed.

**Actual Result:** 
:heavy_check_mark: Exception #0 (Magento\Framework\Exception\LocalizedException): This product is out of stock.
:heavy_check_mark: if product out of stock then show out of stock message on page
![Screenshot from 2020-12-02 13-30-16](https://user-images.githubusercontent.com/51679138/100876319-e58bd600-34af-11eb-9125-2ad8d1ae18d2.png)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch.
 Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2021-02-16 10:37 UTC
Labels: Issue: needs update, not-confirmed, Reported on 2.3.6

**Comment by WebKenth** [comment] 2021-02-16 10:57
@engcom-Alfa 2.4 is not mentioned in this issue, so why are you testing it on 2.4?

it is a 2.3.6 bug and should be tested on 2.3.6 and 2.3.6-p1 not 2.4

2.3 is on a different path than 2.4 with breaking changes all around which is why an upgrade from 2.3 to 2.4 is not a viable solution for most clients

**Comment by anthonyherve** [comment] 2021-05-05 14:22
Hello,

I'm agree with @WebKenth because the error is still there in 2.3.6.
Can you please test on 2.3.6 to try to confirm issue?

Thank you.

Regards,
