### ISSUE TITLE
Customer Store ID is tied to the Welcome Email when creating in admin

### ISSUE THREAD

**Issue by cykirsch** [magento/magento2#10411] opened 2017-08-02 18:29 UTC
### Preconditions

1. EE 2.1.6, but have not tested other versions

### Steps to reproduce

1. Website1 -> Store1 -> StoreView1
2. Website2 -> Store2 -> StoreView2
3. Create new customer. Associate it to Website2. Send welcome email from StoreView1.

### Expected result

1. It should not be possible for a customer to be associated to website 1 and store 2.
2. Perhaps welcome email options should be restricted based on the website chosen.
3. Or at the very least make it clear that the customer will be associated with the store chosen in the welcome email. 
4. And don't default the dropdown to a particular store. This should be explicitly chosen (and required) because it is way too easy to forget to update that field from the default. It's not even in the same place as the website dropdown right now.

### Actual result

1. Welcome email is sent from Store2 and customer_entity gets website_id 1 and store_id 2 in the database.

**Comment by magento-engcom-team** [comment] 2017-09-20 06:57
@cykirsch, thank you for your report.
We've created internal ticket(s) MAGETWO-75539 to track progress on the issue.

**Comment by jasonevans1** [comment] 2017-10-05 21:16
I'm working on it #SQUASHTOBERFEST

**Comment by okorshenko** [comment] 2017-10-05 22:07
Hi @jasonevans1 could you please accept an invitation from magento/magento2 ?

**Comment by jasonevans1** [comment] 2017-10-06 12:55
@okorshenko I have accepted the invitation.

**Comment by jasonevans1** [comment] 2017-10-06 21:30
I will work on changing the customer create in the admin so the welcome email options will be restricted based on the website chosen.

**Comment by magento-engcom-team** [comment] 2018-08-10 08:05
Hi @cykirsch. Thank you for your report. 
The issue has been fixed in magento/magento2#17375 by @jasonevans1 in 2.3-develop branch
Related commit(s):
 - [cfc77b08986dc1707476e17a762f40f83013f6dc](https://github.com/magento/magento2/commit/cfc77b08986dc1707476e17a762f40f83013f6dc)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment] 2018-11-15 12:57
Hi @TomashKhamlai. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by TomashKhamlai** [comment] 2018-11-15 12:59
The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.

**Closed as completed** 2018-11-15 13:06 UTC
Labels: Issue: Ready for Work, Component: Customer, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid
