### ISSUE TITLE
Abandoned Cart Report Showing Wrong Customer for Cart

### ISSUE THREAD

**Issue by jhbowser** [magento/magento2#7462] opened 2016-11-17 03:18 UTC
### Preconditions
1. Magento 2.0.10
2. PHP 5.5
3. MySQL 5.6.27-log

### Steps to reproduce
1. In the admin back-end, navigate to the Reports > Abandoned Carts
2. Click on a row in the report

### Expected result
1. Should go to the selected customer's profile

### Actual result
1. May or may not be taken to the correct customer.

### My Analysis
1. \vendor\magento\module-reports\Block\Adminhtml\Shopcart\Abandoned\Grid.php:_prepareCollection() first gets a collection of quotes (carts) using prepareForAbandonedReport()
2. That generates SQL with data by the quote's updated_at date.
SELECT `main_table`.*, (main_table.base_subtotal_with_discount*main_table.base_to_global_rate) AS `subtotal` 
  FROM `quote` AS `main_table` 
  WHERE (`items_count` != '0') AND (`main_table`.`is_active` = '1') 
  AND (`main_table`.`customer_id` != '') 
  ORDER BY updated_at DESC LIMIT 20
3. Then this method is called on the results:  $this->getCollection()->resolveCustomerNames();
4. That method pulls back the customer's name and email from the customer table, using the customer_id from the collection. Using SQL like this.
SELECT `customer`.`email`, CONCAT_WS(' ', firstname, lastname) AS `customer_name` 
  FROM `customer_entity` AS `customer` 
  WHERE (customer.entity_id IN ('6','63','59','18'))
5. Then the method iterates over both collections merging them to add the customer_name and email to the grid's collection.
  foreach ($this->getItems() as $item) {
            $item->setData(array_merge($item->getData(), current($customersData)));
            next($customersData);
6. The problem is that while the customer entity ids used in the second query are ordered in the WHERE statement in the same order as they exist in the resulting collection of the first query, there is no guarantee the results of the second query will be returned in that order. 
7. When they don't come back in the same order, the wrong customer name and email get merged with the data in the first collection. In the report rows are rendered where the customer name and email are not the for the customer whose values are shown in the rest of the row, nor the generated link to the customer's profile.

**Comment by jhbowser** [comment] 2016-11-17 16:12
I suspect the name and email are being saved on the quote to support guest checkout. But sometimes when data from one table (Customer) is duplicated into another table (Quote) it seems like it might be to facilitate reporting (don't have to do that extra join).  If I were developing an extension using the Quote table and saw customer name and email in the table, my assumption would be they are accurate and safe to use. If I only saw customer id, I would know I need to join the customer table to get those values.  Would the right way to address this problem be to have something in the Quote module observing changes to Customer account and updating the name and email in the quote if necessary? Then the data in the quote table would always be accurate and the resolveCustomerNames() step could be eliminated from preparing the report data.

**Comment by sevos1984** [comment] 2016-11-28 13:21
Thanks for reporting, this is a known issue. Internal ticket id MAGETWO-55512

**Comment by jhbowser** [comment] 2016-11-28 13:52
How can I search the list of known enterprise issues? Issues raised for
community are publicly visible in github, but I don't see where to search
for issues submitted for enterprise. I have 2 other bugs I haven't yet
reported, but would like to know if someone has reported them already. I
spent a lot of time debugging this abandoned cart issue and then even more
time properly documenting everything for the bug report. I had done a Web
search and not found any mention of the problem. Had I been able to see
this was a known issue it would have saved me several hours of my time.
Thanks.

**Comment by magento-engcom-team** [comment] 2017-10-10 14:30
@jhbowser, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-10 14:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Customer, Issue: Confirmed, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
