### ISSUE TITLE
magento 2 Oauth token request gets 400 bad request 

### ISSUE THREAD

**Issue by integrationworktual** [magento/magento2#38019] opened 2023-09-28 13:57 UTC
Hi,
I'm using magento Oauth token based authentication to my third party application to use the Magento ADMIN api's
For that i've created app in magento integration module with following details - identity url, callback url, App name , password of the account.
Select the activate button in the list integration page, it open a side pop up with allow button . click the allow button am getting 
identity url response :
 
```
 {
  oauth_consumer_key: 'consumer key',
  success_call_back: 'success call back url'
}

```
callback url response:
```
{
   oauth_consumer_key: 'consumer key',
    oauth_consumer_secret: 'consumer secret',
    store_base_url: 'store url',
    oauth_verifier: 'verifier key'
}
```

after am getting callack response trying to hint the post  oauht/token/request api getting errors 
here is my code...

```
 console.log("req in callback", req.body);
    let {oauth_consumer_key, oauth_consumer_secret, store_base_url, oauth_verifier} = req.body;
    const uuidValue = uuidv4(); 
    const currentTimeStamp  = new Date().getTime();

    const oauthParam = {
        "oauth_consumer_key ": oauth_consumer_key,
        "oauth_nonce" : uuidValue,
        "oauth_signature_method" : "HMAC-SHA256",
        "oauth_timestamp" : currentTimeStamp,
        "oauth_version" : "1.0",
    }

    const httpMethod = 'POST';

    const parameterString = Object.entries(oauthParam).map(([key, value]) =>`${encodeURIComponent(key)}=${encodeURIComponent(value)}`)
    .join('&');

    console.log("parameterString------",parameterString);
 
    const signatureBaseString = `${httpMethod.toUpperCase()}&${encodeURIComponent(store_base_url)}&${encodeURIComponent(parameterString)}`;
    console.log("signatureBaseString-----",signatureBaseString);
    const signatureValue  = signatureBaseString;

   Object.assign(oauthParam, {oauth_signature : signatureBaseString})
    
const headers = {
    'Authorization' : `oauth_consumer_key=${oauth_consumer_key}&oauth_signature_method=HMAC-SHA256&oauth_signature=${signatureValue}&oauth_nonce=${uuidValue}&oauth_timestamp=${currentTimeStamp}&oauth_version=1.0`
};
console.log("oauthParam-------",oauthParam);

await axios.post(`${store_base_url}oauth/token/request`,oauthParam ,{headers}).then((resp)=> {
    console.log("resp-------",resp)

}).catch((err)=>{
    console.log("err------------",err);
}) 

```

error response: 'oauth_problem=%22oauth_consumer_key%22+is+required.+Enter+and+try+again%2C+%22oauth_signature%22+is+required.+Enter+and+try+again%2C+%22oauth_signature_method%22+is+required.+Enter+and+try+again%2C+%22oauth_nonce%22+is+required.+Enter+and+try+again%2C+%22oauth_timestamp%22+is+required.+Enter+and+try+again'

**Comment by engcom-Bravo** [comment] 2023-09-29 06:24
Hi @integrationworktual,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.but Similar issue has been confirmed here https://github.com/magento/magento2/issues/37913 we need to close this issue as Duplicate of this one https://github.com/magento/magento2/issues/37913. Kindly move onto this issue for latest updates / solutions on the same.

Thanks.

**Closed as completed by engcom-Bravo** 2023-09-29 06:24 UTC
Labels: duplicate, Issue: ready for confirmation, Reported on 2.4.x
