### ISSUE TITLE
Rest api (create product),  set wrong qty (Always set: 0)

### ISSUE THREAD

**Issue by dariovranjkovic** [magento/magento2#35527] opened 2022-05-24 07:46 UTC
### Preconditions and environment

- Magento version 2.4.3

### Steps to reproduce

Create product with rest api:
Method POST: 
Url: https://arvid.zendev.se/rest/V1/products (/rest/V1/products )
Request:

```
{
  "product": {
    "sku": "samsung-a1",
    "name": "Samsung A50 124 3423423 ",
    "attribute_set_id": 4,
    "price": 150000,
    "status": 1,
    "visibility": 1,
    "type_id": "Default",
    "weight": "1",
    "extension_attributes": {
        "website_ids":[
            "1"
         ],
      "category_links": [
        {
          "position": 0,
          "category_id": "6"
        }
      ],
      "stock_item": {
        "qty": "10",
        "is_in_stock": true
      }
    }
  }
}
```

### Expected result

```
{
    "id": 28,
    "sku": "samsung-a1",
    "name": "Samsung A50 124 3423423 ",
    "attribute_set_id": 4,
    "status": 1,
    "visibility": 1,
    "type_id": "Default",
    "created_at": "2022-05-24 07:41:03",
    "updated_at": "2022-05-24 07:41:03",
    "extension_attributes": {
        "website_ids": [
            1
        ],
        "category_links": [
            {
                "position": 0,
                "category_id": "6"
            }
        ],
        "stock_item": {
            "item_id": 28,
            "product_id": 28,
            "stock_id": 1,
            "qty": 10,
            "is_in_stock": true,
            "is_qty_decimal": false,
            "show_default_notification_message": false,
            "use_config_min_qty": true,
            "min_qty": 0,
            "use_config_min_sale_qty": 1,
            "min_sale_qty": 1,
            "use_config_max_sale_qty": true,
            "max_sale_qty": 10000,
            "use_config_backorders": true,
            "backorders": 0,
            "use_config_notify_stock_qty": true,
            "notify_stock_qty": 1,
            "use_config_qty_increments": true,
            "qty_increments": 0,
            "use_config_enable_qty_inc": true,
            "enable_qty_increments": false,
            "use_config_manage_stock": true,
            "manage_stock": true,
            "low_stock_date": null,
            "is_decimal_divided": false,
            "stock_status_changed_auto": 0
        }
    },
    "options": [],
    "media_gallery_entries": [],
    "custom_attributes": [
        {
            "attribute_code": "url_key",
            "value": "samsung-a50-124-3423423"
        },
        {
            "attribute_code": "color_test",
            "value": "16"
        },
        {
            "attribute_code": "options_container",
            "value": "container2"
        },
        {
            "attribute_code": "category_ids",
            "value": [
                "6"
            ]
        },
        {
            "attribute_code": "required_options",
            "value": "0"
        },
        {
            "attribute_code": "has_options",
            "value": "0"
        },
        {
            "attribute_code": "cmtestattribute5",
            "value": "16"
        },
        {
            "attribute_code": "cmtestattr2",
            "value": "16"
        },
        {
            "attribute_code": "cmtestattr3",
            "value": "16"
        },
        {
            "attribute_code": "cmtestattr4",
            "value": "16"
        },
        {
            "attribute_code": "cmtestattr5",
            "value": "16"
        },
        {
            "attribute_code": "cmtestattr1",
            "value": "16"
        }
    ]
}
```

### Actual result

```
{
    "id": 28,
    "sku": "samsung-a1",
    "name": "Samsung A50 124 3423423 ",
    "attribute_set_id": 4,
    "status": 1,
    "visibility": 1,
    "type_id": "Default",
    "created_at": "2022-05-24 07:41:03",
    "updated_at": "2022-05-24 07:41:03",
    "extension_attributes": {
        "website_ids": [
            1
        ],
        "category_links": [
            {
                "position": 0,
                "category_id": "6"
            }
        ],
        "stock_item": {
            "item_id": 28,
            "product_id": 28,
            "stock_id": 1,
            "qty": 0,
            "is_in_stock": true,
            "is_qty_decimal": false,
            "show_default_notification_message": false,
            "use_config_min_qty": true,
            "min_qty": 0,
            "use_config_min_sale_qty": 1,
            "min_sale_qty": 1,
            "use_config_max_sale_qty": true,
            "max_sale_qty": 10000,
            "use_config_backorders": true,
            "backorders": 0,
            "use_config_notify_stock_qty": true,
            "notify_stock_qty": 1,
            "use_config_qty_increments": true,
            "qty_increments": 0,
            "use_config_enable_qty_inc": true,
            "enable_qty_increments": false,
            "use_config_manage_stock": true,
            "manage_stock": true,
            "low_stock_date": null,
            "is_decimal_divided": false,
            "stock_status_changed_auto": 0
        }
    },
    "options": [],
    "media_gallery_entries": [],
    "custom_attributes": [
        {
            "attribute_code": "url_key",
            "value": "samsung-a50-124-3423423"
        },
        {
            "attribute_code": "color_test",
            "value": "16"
        },
        {
            "attribute_code": "options_container",
            "value": "container2"
        },
        {
            "attribute_code": "category_ids",
            "value": [
                "6"
            ]
        },
        {
            "attribute_code": "required_options",
            "value": "0"
        },
        {
            "attribute_code": "has_options",
            "value": "0"
        },
        {
            "attribute_code": "cmtestattribute5",
            "value": "16"
        },
        {
            "attribute_code": "cmtestattr2",
            "value": "16"
        },
        {
            "attribute_code": "cmtestattr3",
            "value": "16"
        },
        {
            "attribute_code": "cmtestattr4",
            "value": "16"
        },
        {
            "attribute_code": "cmtestattr5",
            "value": "16"
        },
        {
            "attribute_code": "cmtestattr1",
            "value": "16"
        }
    ]
}
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-05-25 09:13
@magento give me 2.4-develop instance

**Comment by dariovranjkovic** [comment] 2022-05-30 14:13
Hi, thank you very much, there was a problem with payload

**Comment by engcom-November** [comment] 2022-05-31 11:42
Thank you for the update @dariovranjkovic. We are closing this issue as its not a bug. Kindly reopen / create new issue if you are still facing issues.
Thank you.

**Closed as completed by engcom-November** 2022-05-31 11:42 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
