### ISSUE TITLE
Main page with error

### ISSUE THREAD

**Issue by FabXav** [magento/magento2#39256] opened 2024-10-11 13:32 UTC
### Preconditions and environment

- Magento version
- Anything After input a block on the main pageelse that would help a developer reproduce the bug
Magento 2
Gemmart Theme

### Steps to reproduce

1. Access the created web site;
2. Active CMS Bulder on;
3. Input a new block in the main page

### Expected result

N/A

### Actual result

	<div class="sort-block" id="sortable_home">
						<section class=" builder-container section-builder sort-item section-builder-full" style="" id="panel-section-1">
				<div class="frame container-panel no-padding">
											<div class="edit-panel parent-panel"><ul><li class="up-link"><a title="Move Up" onclick="return false;" href="#" class="moveuplink"><em class="fa fa-arrow-up">&nbsp;</em></a></li><li class="down-link"><a title="Move Down" onclick="return false;" href="#" class="movedownlink"><em class="fa fa-arrow-down">&nbsp;</em></a></li><li><a id="section-1-edit" href="http://link2.databit.com.br/fbuilder/edit/section/id/1/" class="popup-link" title="Edit Section" onclick="return false"><em class="fa fa-gear"></em></a></li><li><a href="#" title="Duplicate Section" onclick="if(confirm('Are you sure you would like to duplicate this section?')) setLocation('http://link2.databit.com.br/fbuilder/index/duplicate/id/1/'); return false"><em class="fa fa-copy"></em></a></li><li><a href="#" title="Delete Section" onclick="if(confirm('Are you sure you would like to remove this section?')) removeSection(1); return false"><em class="fa fa-close"></em></a></li></ul></div>															
											<div class="line">
							<div class="col-des-12  col-builder">
								<div id="sort-block-block1-0" class="line sort-block-container">
															<div class="panel-block-row panel-block col-des-12 block2 sort-item builder-container child-builder"  id="block-2">
				
									<div class="edit-panel child-panel"><ul><li class="sort-handle"><a href="#" onclick="return false;" title="Move Block"><em class="fa fa-arrows-alt">&nbsp;</em></a></li><li><a href="http://link2.databit.com.br/fbuilder/create/element/page_id/2/block/block1-0/id/2/type/image/" class="popup-link" title="Editar"><em class="fa fa-edit">&nbsp;</em></a></li><li><a href="#" title="Copiar" onclick="copyBlock(2);return false;"><em class="fa fa-copy">&nbsp;</em></a></li><li class="change-col"><a href="javascript:void(0)" title="Change column setting"><em class="fa fa-columns">&nbsp;</em></a><ul><li><a id="changecol-2-1" href="//link2.databit.com.br/fbuilder/element/changecol/id/2/col/1/" onclick="changeBlockCol(this.href, 12, 2); return false"><span>1/12</span></a></li><li><a id="changecol-2-2" href="//link2.databit.com.br/fbuilder/element/changecol/id/2/col/2/" onclick="changeBlockCol(this.href, 12, 2); return false"><span>2/12</span></a></li><li><a id="changecol-2-3" href="//link2.databit.com.br/fbuilder/element/changecol/id/2/col/3/" onclick="changeBlockCol(this.href, 12, 2); return false"><span>3/12</span></a></li><li><a id="changecol-2-4" href="//link2.databit.com.br/fbuilder/element/changecol/id/2/col/4/" onclick="changeBlockCol(this.href, 12, 2); return false"><span>4/12</span></a></li><li><a id="changecol-2-5" href="//link2.databit.com.br/fbuilder/element/changecol/id/2/col/5/" onclick="changeBlockCol(this.href, 12, 2); return false"><span>5/12</span></a></li><li><a id="changecol-2-6" href="//link2.databit.com.br/fbuilder/element/changecol/id/2/col/6/" onclick="changeBlockCol(this.href, 12, 2); return false"><span>6/12</span></a></li><li><a id="changecol-2-7" href="//link2.databit.com.br/fbuilder/element/changecol/id/2/col/7/" onclick="changeBlockCol(this.href, 12, 2); return false"><span>7/12</span></a></li><li><a id="changecol-2-8" href="//link2.databit.com.br/fbuilder/element/changecol/id/2/col/8/" onclick="changeBlockCol(this.href, 12, 2); return false"><span>8/12</span></a></li><li><a id="changecol-2-9" href="//link2.databit.com.br/fbuilder/element/changecol/id/2/col/9/" onclick="changeBlockCol(this.href, 12, 2); return false"><span>9/12</span></a></li><li><a id="changecol-2-10" href="//link2.databit.com.br/fbuilder/element/changecol/id/2/col/10/" onclick="changeBlockCol(this.href, 12, 2); return false"><span>10/12</span></a></li><li><a id="changecol-2-11" href="//link2.databit.com.br/fbuilder/element/changecol/id/2/col/11/" onclick="changeBlockCol(this.href, 12, 2); return false"><span>11/12</span></a></li><li><a id="changecol-2-12" href="//link2.databit.com.br/fbuilder/element/changecol/id/2/col/12/" onclick="changeBlockCol(this.href, 12, 2); return false" class="active"><span>12/12</span></a></li></ul></li><li><a href="//link2.databit.com.br/fbuilder/element/delete/id/2/" onclick="if(confirm('Are you sure you would like to remove this block?')) removeBlock(this.href, 2); return false" title="Excluir Bloco"><em class="fa fa-trash">&nbsp;</em></a></li></ul></div>								<div style="">
					<div class="content-block mgs-image-block">
								<div class="image-content">
				<span class="span-container">
										
					<img src="http://link2.databit.com.br/media/mgs/fbuilder/images/n/o/nossa_historia.png" alt="" />
									</span>
			</div>
			</div>

				</div>
			</div>
						<div class="panel-block-row panel-block col-des-12 block3 sort-item builder-container child-builder"  id="block-3">
				
									<div class="edit-panel child-panel"><ul><li class="sort-handle"><a href="#" onclick="return false;" title="Move Block"><em class="fa fa-arrows-alt">&nbsp;</em></a></li><li><a href="http://link2.databit.com.br/fbuilder/create/element/page_id/2/block/block1-0/id/3/type/products_slider/" class="popup-link" title="Editar"><em class="fa fa-edit">&nbsp;</em></a></li><li><a href="#" title="Copiar" onclick="copyBlock(3);return false;"><em class="fa fa-copy">&nbsp;</em></a></li><li class="change-col"><a href="javascript:void(0)" title="Change column setting"><em class="fa fa-columns">&nbsp;</em></a><ul><li><a id="changecol-3-1" href="//link2.databit.com.br/fbuilder/element/changecol/id/3/col/1/" onclick="changeBlockCol(this.href, 12, 3); return false"><span>1/12</span></a></li><li><a id="changecol-3-2" href="//link2.databit.com.br/fbuilder/element/changecol/id/3/col/2/" onclick="changeBlockCol(this.href, 12, 3); return false"><span>2/12</span></a></li><li><a id="changecol-3-3" href="//link2.databit.com.br/fbuilder/element/changecol/id/3/col/3/" onclick="changeBlockCol(this.href, 12, 3); return false"><span>3/12</span></a></li><li><a id="changecol-3-4" href="//link2.databit.com.br/fbuilder/element/changecol/id/3/col/4/" onclick="changeBlockCol(this.href, 12, 3); return false"><span>4/12</span></a></li><li><a id="changecol-3-5" href="//link2.databit.com.br/fbuilder/element/changecol/id/3/col/5/" onclick="changeBlockCol(this.href, 12, 3); return false"><span>5/12</span></a></li><li><a id="changecol-3-6" href="//link2.databit.com.br/fbuilder/element/changecol/id/3/col/6/" onclick="changeBlockCol(this.href, 12, 3); return false"><span>6/12</span></a></li><li><a id="changecol-3-7" href="//link2.databit.com.br/fbuilder/element/changecol/id/3/col/7/" onclick="changeBlockCol(this.href, 12, 3); return false"><span>7/12</span></a></li><li><a id="changecol-3-8" href="//link2.databit.com.br/fbuilder/element/changecol/id/3/col/8/" onclick="changeBlockCol(this.href, 12, 3); return false"><span>8/12</span></a></li><li><a id="changecol-3-9" href="//link2.databit.com.br/fbuilder/element/changecol/id/3/col/9/" onclick="changeBlockCol(this.href, 12, 3); return false"><span>9/12</span></a></li><li><a id="changecol-3-10" href="//link2.databit.com.br/fbuilder/element/changecol/id/3/col/10/" onclick="changeBlockCol(this.href, 12, 3); return false"><span>10/12</span></a></li><li><a id="changecol-3-11" href="//link2.databit.com.br/fbuilder/element/changecol/id/3/col/11/" onclick="changeBlockCol(this.href, 12, 3); return false"><span>11/12</span></a></li><li><a id="changecol-3-12" href="//link2.databit.com.br/fbuilder/element/changecol/id/3/col/12/" onclick="changeBlockCol(this.href, 12, 3); return false" class="active"><span>12/12</span></a></li></ul></li><li><a href="//link2.databit.com.br/fbuilder/element/delete/id/3/" onclick="if(confirm('Are you sure you would like to remove this block?')) removeBlock(this.href, 3); return false" title="Excluir Bloco"><em class="fa fa-trash">&nbsp;</em></a></li></ul></div>								<div style="">
					<div class="content-block product-slider">
		
				<div id="products_slider-products8512338531728650993"  class="block widget mgs-products products-grid product-items">
			<div id="mgs-slider-8512338531728650993"  class="items owl-carousel mgs-owl-carousel mgs-carousel-single nav-type-font nav-position-middle-inside  dot-position-center" >
														<div class="product product-item ">
						<div class="product-item-info" data-container="product-grid">
							
							<div class="product-top ">
								<a href="http://link2.databit.com.br/refletor-led-ultra-10-6500k-luz-branca.html" class="product photo product-item-photo" tabindex="-1">
									<img src="http://link2.databit.com.br/media/catalog/product/cache/a837683496ce2af38d4cb314202c9a16/r/e/refletores-led.png" alt="REFLETOR LED" loading="lazy">
								</a>
																	<div class="actions-primary ">
																				<form data-role="tocart-form" data-product-sku="REFLETOR LED" action="http://link2.databit.com.br/checkout/cart/add/uenc/aHR0cDovL2xpbmsyLmRhdGFiaXQuY29tLmJyLw~~/product/1/" method="post">
											<input type="hidden" name="product" value="1">
											<input type="hidden" name="uenc" value="aHR0cDovL2xpbmsyLmRhdGFiaXQuY29tLmJyL2NoZWNrb3V0L2NhcnQvYWRkL3VlbmMvYUhSMGNEb3ZMMnhwYm1zeUxtUmhkR0ZpYVhRdVkyOXRMbUp5THd-fi9wcm9kdWN0LzEv">
											<input name="form_key" type="hidden" value="glxcSjTSMsdjDP4O" />											<button type="submit" title="Adicionar ao Carrinho" class="action tocart primary">
												<span>Adicionar ao Carrinho</span>
											</button>
										</form>
									</div>
															</div>
							<div class="product details product-item-details">
								DivisionByZeroError: Division by zero in /home/magento/magento2/app/code/MGS/ThemeSettings/Helper/Config.php:79
Stack trace:
#0 /home/magento/magento2/app/design/frontend/Mgs/gemmart/MGS_Fbuilder/templates/widget/products_slider.phtml(77): MGS\ThemeSettings\Helper\Config->getPercent()
#1 /home/magento/magento2/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('...')
#2 /home/magento/magento2/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php->render()
#3 /home/magento/magento2/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView()
#4 /home/magento/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Framework\View\Element\Template->_toHtml()
#5 /home/magento/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#6 /home/magento/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#7 /home/magento/magento2/vendor/magento/module-email/Model/Template/Filter.php(440): Magento\Framework\View\Element\AbstractBlock->toHtml()
#8 [internal function]: Magento\Email\Model\Template\Filter->blockDirective()
#9 /home/magento/magento2/vendor/magento/framework/Filter/DirectiveProcessor/LegacyDirective.php(42): ReflectionMethod->invokeArgs()
#10 /home/magento/magento2/vendor/magento/framework/Filter/Template.php(272): Magento\Framework\Filter\DirectiveProcessor\LegacyDirective->process()
#11 /home/magento/magento2/vendor/magento/framework/Filter/Template.php(206): Magento\Framework\Filter\Template->processDirectives()
#12 /home/magento/magento2/vendor/magento/module-email/Model/Template/Filter.php(1116): Magento\Framework\Filter\Template->filter()
#13 /home/magento/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Email\Model\Template\Filter->filter()
#14 /home/magento/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Widget\Model\Template\Filter\Interceptor->___callParent()
#15 /home/magento/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Widget\Model\Template\Filter\Interceptor->Magento\Framework\Interception\{closure}()
#16 /home/magento/magento2/generated/code/Magento/Widget/Model/Template/Filter/Interceptor.php(32): Magento\Widget\Model\Template\Filter\Interceptor->___callPlugins()
#17 /home/magento/magento2/app/code/MGS/Fbuilder/Block/Panel/Block.php(94): Magento\Widget\Model\Template\Filter\Interceptor->filter()
#18 [internal function]: MGS\Fbuilder\Block\Panel\Block->getContentOfBlock()
#19 /home/magento/magento2/vendor/magento/framework/View/TemplateEngine/Php.php(94): call_user_func_array()
#20 /home/magento/magento2/app/code/MGS/Fbuilder/view/frontend/templates/panel/block.phtml(14): Magento\Framework\View\TemplateEngine\Php->__call()
#21 /home/magento/magento2/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('...')
#22 /home/magento/magento2/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php->render()
#23 /home/magento/magento2/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView()
#24 /home/magento/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Framework\View\Element\Template->_toHtml()
#25 /home/magento/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#26 /home/magento/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#27 /home/magento/magento2/app/code/MGS/Fbuilder/view/frontend/templates/panel/homecontent.phtml(37): Magento\Framework\View\Element\AbstractBlock->toHtml()
#28 /home/magento/magento2/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('...')
#29 /home/magento/magento2/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php->render()
#30 /home/magento/magento2/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView()
#31 /home/magento/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Framework\View\Element\Template->_toHtml()
#32 /home/magento/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#33 /home/magento/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#34 /home/magento/magento2/app/code/MGS/Fbuilder/Block/Cms/Page.php(105): Magento\Framework\View\Element\AbstractBlock->toHtml()
#35 /home/magento/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(1095): MGS\Fbuilder\Block\Cms\Page->_toHtml()
#36 /home/magento/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#37 /home/magento/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#38 /home/magento/magento2/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#39 /home/magento/magento2/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#40 /home/magento/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#41 /home/magento/magento2/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#42 /home/magento/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#43 /home/magento/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#44 /home/magento/magento2/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#45 /home/magento/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#46 /home/magento/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#47 /home/magento/magento2/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#48 /home/magento/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#49 /home/magento/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#50 /home/magento/magento2/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#51 /home/magento/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#52 /home/magento/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#53 /home/magento/magento2/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#54 /home/magento/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#55 /home/magento/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#56 /home/magento/magento2/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#57 /home/magento/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#58 /home/magento/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#59 /home/magento/magento2/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout->renderElement()
#60 /home/magento/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#61 /home/magento/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent()
#62 /home/magento/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#63 /home/magento/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout\Interceptor->___callPlugins()
#64 /home/magento/magento2/vendor/magento/framework/View/Result/Page.php(260): Magento\Framework\View\Layout\Interceptor->getOutput()
#65 /home/magento/magento2/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render()
#66 /home/magento/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult()
#67 /home/magento/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent()
#68 /home/magento/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}()
#69 /home/magento/magento2/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(41): Magento\Framework\View\Result\Page\Interceptor->___callPlugins()
#70 /home/magento/magento2/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult()
#71 /home/magento/magento2/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#72 /home/magento/magento2/pub/index.php(30): Magento\Framework\App\Bootstrap->run()

### Additional information

N/A

### Release note

N/A

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment] 2024-10-14 08:50
The error says:

```
DivisionByZeroError: Division by zero in /home/magento/magento2/app/code/MGS/ThemeSettings/Helper/Config.php:79
```

This doesn't seem to be part of core magento, this seems to be a third party module, maybe ask the support of that module for help?

@engcom-Bravo: in my opinion this ticket can be closed here...

**Comment by engcom-Bravo** [comment] 2024-10-14 09:05
@hostep Thanks for your Contribution!!.

Hi @FabXav,

Thanks for your reporting and collaboration.

We have also verified the issue in Latest 2.4-develop instance and the issue is not reproducible.since the issue is related to third party module we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-10-14 09:05 UTC
Labels: Issue: ready for confirmation, Reported on 2.4.x
