### ISSUE TITLE
dev/js/minify_exclude returns array of results instead of string

### ISSUE THREAD

**Issue by usman786cs** [magento/magento2#28178] opened 2020-05-10 16:26 UTC
### Preconditions (*)

1. You should have installed Magento 2.3.4 version.
2. php version 7.2.

### Steps to reproduce (*)

1. Add minification settings in config.php file
2. Run bin/magento app:config:import

### Expected result (*)

1. Processing configurations data from configuration file...
2. Configuration processed 

### Actual result (*)

1. Import failed: Notice: Array to string conversion in vendor/magento/framework/App/Config/Value.php on line 100

I'm working on Magento version 2.3.4.
It was required by client to add minification settings in config.php file.
After I added them in config.php file . Below are the settings that I added:
**'system' => [
        'stores' => [
            'default' => [
                'dev' => [
                    'css' => [
                        'minify_files' => '1',
                        'merge_css_files' => '1'
                    ],
                    'js' => [
                        'merge_files' => '1',
                        'minify_files' => '1',
                        'enable_js_bundling' => '0'
                    ],
                    'template' => [
                        'minify_html' => '1'
                    ]
                ]
            ]
        ]
    ]**

After I run bin/magento app:config:import I get below error:
**Import failed: Notice: Array to string conversion in vendor/magento/framework/App/Config/Value.php on line 100
**

I was assuming that it will process configuration but useless.
After digging into it I found that vendor/magento/framework/App/Config/Value.php::getOldValue() returns array instead of string value against path **dev/js/minify_exclude**
Below is screenshot that shows result array contains array of three values instead of one string.
Can someone tell me how can i get rid of this issue.
![image](https://user-images.githubusercontent.com/20777255/81505078-57c77e00-9306-11ea-8922-dcc0a7db9139.png)

Thanks!

**Comment by usman786cs** [comment] 2020-05-10 20:57
I tried one solution which is 
delete from flag_data FROM flag WHERE flag_code = 'system_config_snapshot';

and it worked fine for me.

But is it fine solution or if it has disadvantages, please guide.

**Comment by engcom-Alfa** [comment] 2020-05-14 13:04
Hi @usman786cs 

Unfortunately, we are not able to reproduce the issue on a clean 2.4-develop.

**Manual testing scenario:**

1. Add minification settings in **config.php** file  ([devdocs](https://devdocs.magento.com/cloud/live/sens-data-initial.html#change-config)) :
![Screenshot from 2020-05-14 15-39-50](https://user-images.githubusercontent.com/51679138/81937006-acffda00-95fb-11ea-8f95-3949fea84cf6.png)

2. Run in console: ` bin/magento app:config:import`

**Actual Result:**

:heavy_check_mark: Processing configurations data from configuration file...

:heavy_check_mark: Configuration processed

![Screenshot from 2020-05-14 16-00-54](https://user-images.githubusercontent.com/51679138/81937296-213a7d80-95fc-11ea-9556-31b75b95b724.png)

So, we have to close it.

Please, feel free to comment, reopen, or create new ticket according to the[ Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) if you are still facing this issue on the latest `2.4-develop` brunch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-05-14 13:04 UTC
Labels: Issue: Format is valid, Reported on 2.3.4

**Comment by usman786cs** [comment] 2020-05-14 13:08
Thanks @engcom-Alfa  for your help.

I resolved this issue by this command:
delete flag_data FROM flag WHERE flag_code = 'system_config_snapshot';

**Comment by hostep** [comment] 2020-05-14 18:27
Hi @usman786cs: have you upgraded from Magento 2.2 to 2.3?
The structure of how the `minify_exclude` configuration has been defined changed in Magento 2.3.0 by https://github.com/magento/magento2/pull/13687

I posed the question in the PR if there was a possibility that the configuration was stored in the database and how to handle that, but got no answer. So I think we needed to have some database upgrade script changing old structures to new structures in the database, but that didn't happen.

Other than that, I don't know what the `system_config_snapshot` flag is being used for or how the `minify_exclude` value got stored in there.
So if you could figure out what that flag does and what it is used for you can probably determine if it is important or not to keep or if it's safe to remove.

Sorry, this comment probably doesn't help you further I'm afraid.
