### ISSUE TITLE
2.0.9 Community - Parts of order mail are not translated when asynchronous mailing enabled

### ISSUE THREAD

**Issue by micheleo** [magento/magento2#7516] opened 2016-11-22 08:53 UTC
When flag sales_email/general/async_sending is active some parts of the order confirmation mail are not translated, in particular  Magento\Sales\Block\Order\Totals. With synchronous mailing the problem won't appear. 

### Preconditions
Name: Magento                                                   
Version: 2.0.9                                                     
Edition: Community                                                 
Application Mode: production                                                

PHP 5.5.9-1

### Steps to reproduce
1. Add a new order with asynchronous mailing active

### Expected result
1. The confirmation email arrives completely translated

### Actual result
1. The confirmation email arrives with some parts translated and others not

Not tested with 2.1 yet. 

Thank you in advance

**Comment by wozniakm** [comment] 2017-03-15 10:32
Same thing happens in 2.1 version.

**Comment by magento-engcom-team** [comment] 2017-09-29 13:30
@micheleo, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-29 13:30 UTC
Labels: bug report, Component: Translation, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
