### ISSUE TITLE
Issue with Adding Products - System Times Out

### ISSUE THREAD

**Issue by Dckeystone** [magento/magento2#33377] opened 2021-06-29 03:36 UTC
### Preconditions (*)

1.Magento version 2.4.2
2.When adding a product to my store the system times out after taking several minutes to add the products.  502 Bad Gateway is the screen it goes to.

### Steps to reproduce (*)

1. Every time I add a product this is what happens.   Magento spins its wheel in the center of the screen for a few minutes and then times out saying 502 Bad Gateway.
2. Steps are - Click on Catalog, click products, add products and go through all the steps to add the product with configurations and attributes set for several variations per product, then click on save to have the products created.  

### Expected result (*)

1. I expect all the product variations to be created.  It takes several minutes to create all the variations and set the right attributes and configurations to the products.  
2. At the end of one product creation I should have 20 products arrive with all the variations available.  The system created 10 once and now it just times out every time.  It does not create all the products that I set it to and the system stops and goes to a blank screen saying 502 Bad Gateway.

### Actual result (*)

1. After a good 3 to 5 minutes of the spinning wheel in the center of the screen the screen changes to an all blank screen that says bad gateway 502.  
2. One time it created a few of the products, but not near all the variations that it should have.  

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2021-06-29 06:08
Hi @Dckeystone,

I am looking into this issue meanwhile please add "Reported on {Version}" and "Component : {ComponentName}" label with this issue.

**Comment by engcom-Hotel** [comment] 2021-06-29 10:17
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2021-06-29 12:43
Hi @Dckeystone ,

We have tried to reproduce the issue in version 2.4-develop, but unable to reproduce the same. We have followed below steps:

1. Create configurable product.
2. Fill all mandatory fields.
3. Create configurations with color and size of the product.
4. Click on save, to create the product.

Please let us know if we need to perform any specific step in order to reproduce the issue. And also, sometimes 502 bad gateway error comes due to server misconfiguration.

I suggest you to check the server configuration.

Thanks

**Comment by engcom-Hotel** [comment] 2021-07-13 05:07
Hi @Dckeystone,

We hope that this issue has been resolved. As we are not able to hear from you since 14 days, we are closing this issue.

If you still facing the issue either you can reopen it or create a new ticket.

Thanks

**Closed as completed by engcom-Hotel** 2021-07-13 05:07 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
