### ISSUE TITLE
Product URL not regenerating on save

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#39042] opened 2024-08-14 11:55 UTC
### Preconditions and environment

Magento 2.4.4-p9

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

### Steps to reproduce

1. Delete the URLs of a product in "Marketing -> SEO & Search -> URL Rewrites".
2. Try to access the product -> you will get 404
3. Save the product from the backend

### Expected result

Saving the product should regenerate the URL

### Actual result

URL does not regenerate and you still get 404.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-08-16 06:44
Hi @Eddcapone,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Delete the URLs of a product in "Marketing -> SEO & Search -> URL Rewrites".
- Try to access the product -> you will get 404
- Save the product from the backend


<img width="1431" alt="Screenshot 2024-08-16 at 11 31 16" src="https://github.com/user-attachments/assets/f1398cbb-7349-4461-bb76-3cf2a725ea95">


<img width="1431" alt="Screenshot 2024-08-16 at 11 31 30" src="https://github.com/user-attachments/assets/358567d1-e953-4288-bd3e-985bfeabbc09">


After product saving URL again regenerating successfully.

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by Eddcapone** [comment] 2024-08-16 08:13
I tested it on a fresh magento 2.4.4-p9 Enterprise instance and I am able to reproduce it:
![demo](https://github.com/user-attachments/assets/0146b354-6546-4354-9ff8-44a28ea0c62e)

@magento give me Latest 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-08-19 07:28
Hi @Eddcapone,

Thanks for your update.

We have verified the issue in Latest 2.4-develop instance with  EE edition and the issue is not reproducible.Kindly refer the attached video.


https://github.com/user-attachments/assets/5a81453a-a199-4dd5-a9d3-3574a5eded23



After product saving URL again regenerating successfully.It is recommended to verify the issue in Latest 2.4-develop instance.


Thanks.

**Comment by engcom-Bravo** [comment] 2024-08-30 05:02
Hi @Eddcapone,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-08-30 05:02 UTC
Labels: Issue: needs update, Reported on 2.4.4-p9

**Comment by Eddcapone** [comment] 2024-09-06 06:33
Thank you, so it must be a bug in magento that is fixed in the developer version?... I will change to the developer version if I have time and test it.
