### ISSUE TITLE
notifications are carry forward to the next page in magento 2

### ISSUE THREAD

**Issue by TalibSaifi003** [magento/magento2#38560] opened 2024-04-01 16:21 UTC
### Preconditions and environment

our site version is 2.4.2.
getting a success message on the other page.
https://prnt.sc/TCTc6hnpd-Nl

### Steps to reproduce

when I save any info on the storefront i.e remove the newsletter subscription then a success message will come(you have removed your newsletter subscription). then i go to another page so i am getting same message on other page also.
i.e https://prnt.sc/TCTc6hnpd-Nl
please provide me solution of this issue

### Expected result

notification message should not carry forward to other page

### Actual result

notifications are carry forward to the other page.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-04-02 03:29
Hi @TalibSaifi003,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.



https://github.com/magento/magento2/assets/51680745/91085bc8-9b23-4dd9-9385-cee94074d6ef




Notification message is not carrying forward to other page.

Kindly check the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible and check if any third party modules causing the issue.


Thanks.

**Comment by engcom-Bravo** [comment] 2024-04-15 05:35
Hi @TalibSaifi003,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-04-15 05:35 UTC
Labels: Issue: needs update, Reported on 2.4.2
