### ISSUE TITLE
_isScopePrivate vs ESI hole punching vs private data

### ISSUE THREAD

**Issue by onlinebizsoft** [magento/magento2#33555] opened 2021-07-22 05:26 UTC
### Summary (*)

Related to 
https://github.com/magento/magento2/pull/31754
https://support.magento.com/hc/en-us/articles/360040208612--isScopePrivate-in-private-content-blocks-slows-Magento-performance
https://devdocs.magento.com/guides/v2.3/extension-dev-guide/cache/page-caching/private-content.html

_isScopePrivate couldn't be replaced by "private content" completely

### Examples (*)

When you have a small block for announcement which appears on every page of the website, it has no interaction with user action (different from users action like adding to cart,....). The block may have content changed often but you wont want to flush whole cache to get it updated to every user. In this case you really want to use _isScopePrivate or ESI hole punching (depends on developer choice). It can't be done or replaced by "private content"

### Proposed solution

So I don't understand why you are going to remove _isScopePrivate in future? We should keep the feature as it is and you just need to change to "private content" for necessary user cases.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by onlinebizsoft** [comment] 2021-07-22 05:27
@mrtuvn @sivaschenko @ihor-sviziev

**Comment by mrtuvn** [comment] 2021-07-22 05:33
I think docs seem outdated and we need to update it
I think new approach for private content is like product compare functional (section ajax update)
Some other cases we can set cache_lifetime (via xml or php block) to false for dynamic block content
CC: @Vinai

**Comment by onlinebizsoft** [comment] 2021-07-22 06:42
@mrtuvn you refer to product compare but it is not same, it could be done with "private data" because an user action "add to compare" can trigger an invalidation,....
However the  private scope variable is helpful when we want a small non-cacheable block on all pages

**Comment by Vinai** [comment] 2021-07-26 12:57
The main benefit from my point of view is that private scope blocks make migrating blocks from Magento 1 to Magento 2 very easy.
It would be cool if the deprecation note from the docs would be removed.

**Comment by engcom-Delta** [comment] 2021-12-24 09:56
Hi @mrtuvn  ,

Thank you for raising an issue , we are happy to work on this issue . Kindly provide steps to reproduce , actual results with screenshots.

Regards,

**Comment by engcom-Delta** [comment] 2022-01-07 13:48
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Comment by Vinai** [comment] 2022-01-12 19:54
lol

**Comment by engcom-Hotel** [comment] 2022-01-14 15:28
We are reopening this issue for further analysis.

**Comment by engcom-Lima** [comment] 2022-07-22 09:32
HI @onlinebizsoft,

I have gone through the conversation happened on this issue and did some research on same. 

Based on it, I think the decision to discourage the use of `_isScopePrivate()` is related to performance and main purpose was ‘Reduce AJAX requests due to non-cacheable blocks’ as suggested in the below article:

https://developer.adobe.com/commerce/php/development/cache/page/private-content/

And for the example which you have provided, I agree for the use case which you mentioned, `_isScopePrivate()` can be seen as work approach but that’s why it is recommended to handle it on the web browser or client side instead of sending multiple requests to server. Since `_isScopePrivate()` can trigger additional AJAX requests, that is why it is discouraged from Magento’s performance perspective.

Hope the above explanation is helpful. If you still have any doubt, feel free to comment back or let us know if we can close this issue ?

Thanks

**Comment by engcom-Lima** [comment] 2022-08-05 06:23
Hi @onlinebizsoft ,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Lima** 2022-08-05 06:23 UTC
Labels: Triage: Dev.Experience, Issue: needs update
