### ISSUE TITLE
Magento Ui form validator message callback not supported

### ISSUE THREAD

**Issue by floorz** [magento/magento2#20078] opened 2019-01-04 23:38 UTC
### Preconditions (*)

1. 2.1.x, 2.2.x, 2.3.x

### Steps to reproduce (*)

1. Create a new validation rule using the `Magento_Ui::js/lib/validation/validator.js`, using a callback as the validator's message.
  - **Note:** the unused "validate-customer-password" in `Magento_Ui::js/lib/validation/rules.js` already does this: https://github.com/magento/magento2/blob/2.1/app/code/Magento/Ui/view/base/web/js/lib/validation/rules.js#L423-L463
2. Add the new validation rule to a form field (in my case, one of the checkout address fields)
3. Use the field in the form it resides, making it fail validation

### Expected result (*)

1. Seeing a failed validation message for that field

### Actual result (*)

1. **Javascript Error:** Uncaught TypeError: msg.replace is not a function
2. Error occurance happens at https://github.com/magento/magento2/blob/2.1/app/code/Magento/Ui/view/base/web/js/lib/validation/validator.js#L43-L45
![javascript-type-error](https://user-images.githubusercontent.com/4982916/50717339-a9962f00-1054-11e9-96a2-bc34c9e86787.png)
3. Any case where the message is a callback function, this error seems like it will happen

### Additional Notes
1. Jquery validation already seems to handle this scenario of the validation message being a callback. It checks if the message is of type `function`, and if so, calls it, setting the `this` context appropriately.

### Proposed Solution
1. Adding the same sort of type check that jquery does, and reassigning the `message` variable to the result of calling the message callback.

**Example (in Magento_Ui::js/lib/validation/validator::vailidate()):**

    if (typeof message === 'function') {
        message = message.call(rule);
    }

**Comment by magento-engcom-team** [comment] 2019-01-04 23:38
Hi @floorz. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@floorz do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-05 01:21
@shikhamis11 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97459`, `MAGETWO-97460` were created

**Comment by floorz** [comment] 2019-01-08 02:47
@shikhamis11 are one of those internal tickets for 2.2.x and the other for 2.3.x ?

**Comment by magento-engcom-team** [comment] 2019-03-05 21:17
Hi @floorz. Thank you for your report. 
The issue has been fixed in magento/magento2#20079 by @floorz in 2.3-develop branch
Related commit(s):
 - [be02c1e1cd1b1547b3d087be9a96ea7a12f2b46c](https://github.com/magento/magento2/commit/be02c1e1cd1b1547b3d087be9a96ea7a12f2b46c)
 - [dc8d2d5a316ec9013a97d5850f78d39446351131](https://github.com/magento/magento2/commit/dc8d2d5a316ec9013a97d5850f78d39446351131)
 - [5cefe94f5aa49cc2263b0fe0af7e9a60b9510722](https://github.com/magento/magento2/commit/5cefe94f5aa49cc2263b0fe0af7e9a60b9510722)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-05 21:17 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Ui

**Comment by magento-engcom-team** [comment] 2019-04-17 12:10
Hi @floorz. Thank you for your report. 
The issue has been fixed in magento/magento2#20107 by @floorz in 2.2-develop branch
Related commit(s):
 - [63c592a1b35fbd5dc2917d49b6fc10a6ab6fb46c](https://github.com/magento/magento2/commit/63c592a1b35fbd5dc2917d49b6fc10a6ab6fb46c)

The fix will be available with the upcoming 2.2.9 release.
