### ISSUE TITLE
Admin able to edit shipping and billing address for completed orders status backend

### ISSUE THREAD

**Issue by Abhay-Agrawal** [magento/magento2#35544] opened 2022-05-27 04:07 UTC
### Summary (*)

1. Place and order from the frontend side
2. generate the shipping and invoice of order make the order status complete
3. Now check the billing and shipping address and admin can edit the address here
4. what is the purpose of edit link here

<img width="809" alt="issue" src="https://user-images.githubusercontent.com/55655451/170627233-82982ac4-6ebe-40a5-a86e-282cf85dc2b6.PNG">

**Comment by engcom-November** [comment] 2022-05-27 13:26
Hi @Abhay-Agrawal ,
Thank you for reporting and collaboration. Verified the behavior on Magento 2.4-develop branch and as per Magento [docs](https://docs.magento.com/user-guide/sales/order-processing.html), Billing and shipping addresses can be edited for a processing order however, this can also be useful for a Completed order as well because user can still use them for reorder or issuing a credit memo. Also edit links are present for completed order in screenshot of magento [docs](https://docs.magento.com/user-guide/sales/order-processing.html) and user experience is also not effected with this behavior. Its an existing behavior of magento but not a bug. Please provide your inputs on this.
Thank you.

**Comment by engcom-November** [comment] 2022-06-10 05:55
Hi @Abhay-Agrawal ,
We are closing this issue as there has been no latest update on the same. Kindly reopen/ create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-06-10 05:55 UTC
Labels: Triage: Dev.Experience, Issue: needs update
