### ISSUE TITLE
error when open some product page in adminhtml

### ISSUE THREAD

**Issue by salah11172** [magento/magento2#36938] opened 2023-03-01 09:02 UTC
### Preconditions and environment

- Magento version 2.4.4
php 7.4 

### Steps to reproduce

open product page in backend

### Expected result

expected open product page and view product details

### Actual result

TypeError: Argument 1 passed to Magento\Framework\View\Element\UiComponent\DataProvider\Sanitizer::sanitizeComponentMetadata() must be of the type array, null given in /chroot/home/a44febd9/b077da9ab2.nxcli.net/vendor/magento/framework/View/Element/UiComponent/DataProvider/Sanitizer.php:85
Stack trace:
#0 [internal function]: Magento\Framework\View\Element\UiComponent\DataProvider\Sanitizer->sanitizeComponentMetadata(NULL)
#1 /chroot/home/a44febd9/b077da9ab2.nxcli.net/vendor/magento/framework/View/Element/UiComponent/DataProvider/Sanitizer.php(97): array_map(Array, Array)
#2 [internal function]: Magento\Framework\View\Element\UiComponent\DataProvider\Sanitizer->sanitizeComponentMetadata(Array)
#3 /chroot/home/a44febd9/b077da9ab2.nxcli.net/vendor/magento/framework/View/Element/UiComponent/DataProvider/Sanitizer.php(97): array_map(Array, Array)
#4 /chroot/home/a44febd9/b077da9ab2.nxcli.net/vendor/magento/framework/View/Element/UiComponentFactory.php(332): Magento\Framework\View\Element\UiComponent\DataProvider\Sanitizer->sanitizeComponentMetadata(Array)
#5 /chroot/home/a44febd9/b077da9ab2.nxcli.net/vendor/magento/framework/View/Element/UiComponentFactory.php(231): Magento\Framework\View\Element\UiComponentFactory->mergeMetadata('product_form', Array, false)
#6 /chroot/home/a44febd9/b077da9ab2.nxcli.net/vendor/magento/framework/View/Layout/Generator/UiComponent.php(140): Magento\Framework\View\Element\UiComponentFactory->create('product_form', NULL, Array)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by salah11172** [comment] 2023-03-01 09:09
![Screenshot from 2023-03-01 11-07-51](https://user-images.githubusercontent.com/77698583/222093810-5ea97352-9f26-479e-adfa-518b9c0a26b7.png)


Note: This only happens with recently imported products

**Comment by devchris79** [comment] 2023-03-01 10:42
Magento 2.4.4 requires PHP 8.1 not 7.4.

See system requirements [here](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html)

**Comment by engcom-Bravo** [comment] 2023-03-01 11:32
@devchris79 Thanks for your contribution & collaboration over here.

Hi @salah11172,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

1.Import the Products.
2.open product page in backend

We are able to edit the product.


<img width="1465" alt="Screenshot 2023-03-01 at 3 42 42 PM" src="https://user-images.githubusercontent.com/51680745/222127097-13280c2e-20fe-41fe-9f1f-211046b7d657.png">

Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.

Kindly check your system requirements https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html.Please let us know if you are still facing any issue.

Thanks.

**Comment by shilpsauce** [comment] 2023-03-02 07:31
@magento give me 2.4-develop instance

**Comment by salah11172** [comment] 2023-03-02 08:29
**Update**
the missing thing cause error in new products imported  is Attribute set is Empty

**Comment by engcom-Bravo** [comment] 2023-03-02 13:26
Hi @salah11172,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


Steps to reproduce

1.Import the Products.
2.open product page in backend.


We have imported a products with Attribute set is Empty.Below is the CSV file.

[catalog_product (9).csv](https://github.com/magento/magento2/files/10870887/catalog_product.9.csv)



We are able to open the product page.

<img width="1424" alt="Screenshot 2023-03-02 at 2 48 57 PM" src="https://user-images.githubusercontent.com/51680745/222419111-b4be9ac0-15ce-40f9-ada8-5daaec1514a0.png">




Thanks.

**Comment by engcom-Bravo** [comment] 2023-03-14 06:17
Hi @salah11172.

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-03-14 06:17 UTC
Labels: Issue: needs update, Reported on 2.4.4

**Comment by rahulks16** [comment] 2023-03-24 16:36
Faced same issue, any update on this ??

**Comment by salah11172** [comment] 2023-03-25 08:06
check  Attribute set is empty ?

**Comment by bka** [comment] 2023-08-17 12:12
Had the same issue today. 

`TypeError: Magento\Framework\View\Element\UiComponent\DataProvider\Sanitizer::sanitizeComponentMetadata(): Argument #1 ($meta) must be of type array, null given in /var/www/html/www/vendor/magento/framework/View/Element/UiComponent/DataProvider/Sanitizer.php:85`

The product was assigned to a non-existing attribute_set. Here is a query you can use to check if your database contains any products with orphaned attribute sets:

`SELECT * FROM mg2catalog_product_entity main LEFT JOIN mg2eav_attribute_set s ON main.attribute_set_id = s.attribute_set_id WHERE s.attribute_set_id IS NULL;
`

**Comment by lpwe** [comment] 2025-01-13 09:59
almost the same error here in ver. 2.4.7-p3 (all requirements are matched)
only one extension is installed: amasty importer.
sample products can be opened / edited, newly imported can't.
Add Product (adding a simple new product im backend manually) causes the error alerady.
