### ISSUE TITLE
Attribute value display storeview when adding a new product.

### ISSUE THREAD

**Issue by bbatten** [magento/magento2#23823] opened 2019-07-22 18:40 UTC
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

1. Create a new dropdown product attribute.
2. Under the manage options section set a new value for the dropdown but make sure the label for the admin vs the storeview are different.  In our admin view we have color codes added to the front of a color.  For example:
Admin: AC - Assorted Colors
Storeview: Assorted Colors
3. Now go to add a new product.
4. When adding a new product the dropdown displays the storeview value and not the admin value.  

- We have tested this with multiple dropdown attributes and on a vanilla Magento install.  
- One you save the new product the attribute changes to the admin version.  
- When editing an existing product the attribute displays the admin version.

### Expected result (*)

1. When adding a new product in the admin it should always display the admin values for the attribute.  

### Actual result (*)

1. When adding a new product the attribute values are always the storeview.

**Comment by bbatten** [comment] 2019-07-22 19:01
Yes, I was able to reproduce the issue on vanilla Magento instance following steps to reproduce.

**Comment by sudheers-kensium** [comment] 2019-07-23 06:58
Hi @bbatten ! If you enter any value in Default Store View that will display in frontend and  Is Default Admin value display in admin side.

**Comment by engcom-Charlie** [comment] 2019-07-23 09:56
Hi @bbatten ! I can't reproduce this issue on fresh 2.3-develop branch. So i have to close this issue, sry.
Thank you for contribution!

**Closed as completed by engcom-Charlie** 2019-07-23 09:56 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Admin
