### ISSUE TITLE
Scroll in remove product popup in responsive view in compare/mini cart page.

### ISSUE THREAD

**Issue by bhavik43** [magento/magento2#22968] opened 2019-05-22 05:42 UTC
scroll in remove product popup in responsive view in compare/mini cart page.

### Preconditions (*)
magento 2.2

### Steps to reproduce (*)
1. Front end: Add to compare product/Add to cart product
2. Compare page/mini cart
3. Click on remove icon
4. Review the popup horizontal scroll

### Expected result (*)
![scroll expected](https://user-images.githubusercontent.com/49804008/58149831-2b909880-7c82-11e9-9729-5a13181992e2.png)

### Actual result (*)
![scroll actual](https://user-images.githubusercontent.com/49804008/58149840-33503d00-7c82-11e9-8679-b9243dc65ec2.png)

**Comment by krishprakash** [comment] 2019-05-22 05:42
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-05-22 05:43
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-05-22 05:43
Hi @krishprakash, here is your [Magento instance](https://i-22968-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22968-2-2-develop.instances.magento-community.engineering/admin](https://i-22968-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2019-05-22 05:48
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-05-22 05:48
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-05-22 05:49
Hi @krishprakash, here is your [Magento instance](https://i-22968-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22968-2-3-develop.instances.magento-community.engineering/admin](https://i-22968-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-05-22 05:59
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99791` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by bellodaniel** [comment] 2019-06-05 11:12
I have faced this issue in the past too. But it turned out to be an Inspect Element issue.
When I resized the browser I faced this issue.
But, when I tested on Mobile/Tablet it looked good.
Also, you need to pay attention to the other page elements. There might be any page element that might have bigger width than the device width and it will cause the other page elements to extend further.

**Comment by engcom-Delta** [comment] 2019-08-02 06:49
Hi @bhavik43 
Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by engcom-Delta** 2019-08-02 06:49 UTC
Labels: Issue: Ready for Work, Component: Checkout, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Ui, Area: Design/Frontend
