### ISSUE TITLE
fix the container for description inserted with page builder inside catalog product view 

### ISSUE THREAD

**Issue by PierW** [magento/magento2#35123] opened 2022-02-19 21:28 UTC
### Preconditions (*)

1. Magento 2.4.3-p1
2. Module Page Builder Enabled (Default)
3. Design Page - Template Product full width (Default with page builder enabled)

### Steps to reproduce (*)

1. Enter to the backoffice
2. Create a Product and insert a description with page builder inside a row and 1 column
3. Save

### Expected result (*)

1. <img width="1348" alt="Schermata 2022-02-19 alle 20 39 30" src="https://user-images.githubusercontent.com/6259010/154819430-7a130153-375f-46c8-93ef-cc7fff6295f0.png">
2. The text should be aligned

### Actual result (*)

1. <img width="1421" alt="Schermata 2022-02-19 alle 20 35 38" src="https://user-images.githubusercontent.com/6259010/154819499-8d70ddbe-d30f-4470-a489-5710c303db6e.png">

2. It's not aligned

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by PierW** [comment] 2022-02-19 21:31
@magento I am working on this

**Comment by engcom-Delta** [comment] 2022-02-25 13:36
Hi @PierW ,
Thank you for reporting the issue.We have verified the issue on Magento 2.4-develop branch however the issue is reproducible.Hence we are confirming the issue.

**Steps performed:**
1. Install a clean version of Magento version 2.4-develop
2. go to backend
3. Create a Product and insert a description with page builder inside a row and 1 column
4. Save

Actual Result:
Text is not aligned  as shown in screenshot.
![first](https://user-images.githubusercontent.com/51681379/155723961-73b50e04-5d93-41d8-a9e8-210bc37334ac.png)

Thanks.

**Comment by engcom-Bravo** [comment] 2024-10-07 06:01
Hi @PierW,

Thanks for your reporting and collaboration.

As per this comment https://github.com/magento/magento2-page-builder/pull/802#issuecomment-2376078694 issue is no more reproducible.Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-10-07 06:01 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Progress: done, Area: Content
