### ISSUE TITLE
Issue Creating Tax Rate and Zone

### ISSUE THREAD

**Issue by zaoky** [magento/magento2#4873] opened 2016-06-03 21:08 UTC
## Steps to reproduce
1. Install Magento 2.0.7
2. create a new Tax Rate and zone by API/REST with the rate = 0
## Expected result
1. new tax rate and zone create with rate = 0 for a rule that applies to non-taxable customers
## Actual result
1. Error message appears: 
   {
   "message": "%fieldName is a required field.",
   "parameters": {
     "fieldName": "percentage_rate"
   }
   }
   <a href="http://www.freeimagehosting.net/commercial-photography/california/palm-springs/"><img src="http://i.imgur.com/tIFsL8z.png" alt="Palm Springs commercial photography"></a>
## Note

I can create a Tax Rate and Zone with rate = 0 through the admin page

**Comment by zaoky** [comment] 2016-07-06 20:39
any update ??

**Comment by zaoky** [comment] 2016-07-27 16:29
please, any news ??

**Comment by mikeweis** [comment] 2016-07-29 22:52
@zaoky ... thank you for reporting.  I have created internal ticket MAGETWO-56156 to track this issue.

**Comment by mikeweis** [comment] 2016-07-29 22:57
@zaoky ... a _possible_ work-around:
- the database table (tax_calculation_rate) that holds the Tax Rate "rate" column is set to 4 digits after the decimal place
- using the Tax Rate API, send in a rate of 0.00001 (as an example)
- the rate stored in the database table will be 0.0000 (zero)
- note that the API response will claim that the rate is 0.00001 however  :(

**Comment by magento-engcom-team** [comment] 2017-09-20 22:17
@zaoky, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:17 UTC
Labels: Issue: Ready for Work, bug report, Component: Tax, Fixed in 2.2.x, Issue: Format is not valid
