### ISSUE TITLE
Wrong special_price is displayed for products on frontend

### ISSUE THREAD

**Issue by FerihumF** [magento/magento2#26561] opened 2020-01-28 09:48 UTC
### Preconditions (*)

1. Magento 2.2.10
2. PHP 7.1

### Steps to reproduce (*)

1. Create 2 websites with a store and a store view each. Stores share the same root category.
2. Set catalog prices to "website" scope.
3. Set default currency to EUR and currency of website 2 to USD
4. Create a product and set values only for default store view (id 0)
5. Set a special price of 100 (EUR) and a valid time range in default store view
6. Switch to store view of website 2 and set a special price 150 (USD), do not modify time range
7. Visit the product page on store view of website 2.

### Expected result (*)

1. Product showing a price of 150 USD.

### Actual result (*)

1. Product shows a price of 100 USD
2. In minicart wrong price is shown
3. In checkout prices are correct

In [FrontSpecialPrice](https://github.com/magento/magento2/blob/06a0dd0d5f7ea3e389dc5fa718400866ab4c1eef/app/code/Magento/Catalog/Model/Product/Type/FrontSpecialPrice.php#L82) it just chooses minimal price from its candidates (from default store view and the current store view), but it should prioritize the special price of the current store view.

**Comment by FerihumF** [comment] 2020-01-28 09:49
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-01-28 09:49
Hi @FerihumF. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by shikhamis11** [comment] 2020-01-28 10:13
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-01-28 10:13
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by FerihumF** [comment] 2020-01-28 10:32
First thing I noticed: In file [SpecialPrice.php#L105](https://github.com/magento/magento2/blob/06a0dd0d5f7ea3e389dc5fa718400866ab4c1eef/app/code/Magento/Catalog/Model/ResourceModel/Product/Price/SpecialPrice.php#L105) the select should return only one entry per store_id but it returns every combination of datetime_from and datetime_to with it. That is wrong and adds overhead for multi store environments. You should improve that by adding `'AND ' . $priceTable . '.store_id = datetime_from.store_id'` to the first JOIN and `'AND ' . $priceTable . '.store_id = datetime_to.store_id'` to the second JOIN

This is an improvement but will not fix the issue. To fix the issue, logic in FrontSpecialPrice.php would have to be different.

**Comment by engcom-Bravo** [comment] 2020-03-25 14:54
Hello @FerihumF 

This is not a bug, this is a functionality of Magento, and this has nothing to do with Second Web site.
It is not possible to set _Special price_ **bigger** than the original. I have rechecked it with Default _Website_, _Store_ and _Storeview_ 

I have also rechecked the scenario, provided in the Steps to reproduce.
When the _Special Price is 150_ and the Original is 100, then 100 is displayed. When the _Special Price_ is 75, for example, and the Original is 100, then **75** USD is displayed on the Second Seb site

I'm closing this issue. 
Please feel free to comment or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thank you

**Closed as completed by engcom-Bravo** 2020-03-25 14:54 UTC
Labels: Issue: Format is valid, Reported on 2.1.x
