### ISSUE TITLE
HTTP 502 error when cart has coupon code and disabled products

### ISSUE THREAD

**Issue by mike-thepixel** [magento/magento2#27978] opened 2020-04-24 15:35 UTC
### Preconditions (*)

1. 2.3.2 and above

### Steps to reproduce (*)

1. Add a product to the cart
2. Add a coupon code to the cart
3. Disable the product in the admin
4. Re-load the cart page

### Expected result (*)

1. Cart page should load with the disabled product removed and totals recalculated

### Actual result (*)

1. HTTP 502 error

Some coupon code validation is loading he quote record during the totals collection, but because of the disabled product the collection is retriggered causing an infinite loop.

I've attached a patch to load the quote record via the connection object to avoid load events.

[error_with_cart_coupon_disabled_product.patch.txt](https://github.com/magento/magento2/files/4529856/error_with_cart_coupon_disabled_product.patch.txt)

**Comment by shikhamis11** [comment] 2020-04-24 16:54
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-24 16:54
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-24 16:55
Hi @shikhamis11, here is your [Magento instance](https://i-27978-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27978-2-4-develop.instances.magento-community.engineering/admin_192a](https://i-27978-2-4-develop.instances.magento-community.engineering/admin_192a)
Login: `20d6cffd` Password: `7d14682a3fc4`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2020-04-24 17:22
hi @mike-thepixel 
I checked this issue at magento 2.4-develop instance but not able to reproduced this issue there.
can you check this issue on the instance and confirm

**Comment by mike-thepixel** [comment] 2020-04-27 08:58
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-27 08:58
Hi @mike-thepixel. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-27 08:59
Hi @mike-thepixel, here is your [Magento instance](https://i-27978-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27978-2-4-develop.instances.magento-community.engineering/admin_c4d7](https://i-27978-2-4-develop.instances.magento-community.engineering/admin_c4d7)
Login: `dac2efdb` Password: `0bdc77aa04a5`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2020-05-07 17:14
@mike-thepixel I am closing this issue as I am not able to reproduce this issue . feel free to reopen this issue if you are able to reproduce it on 2.4-develop instance

**Closed as completed by shikhamis11** 2020-05-07 17:14 UTC
Labels: Issue: Format is valid, Reported on 2.3.2
