### ISSUE TITLE
Street lines ignoring blank lines

### ISSUE THREAD

**Issue by r-martins** [magento/magento2#27847] opened 2020-04-13 23:35 UTC
### Preconditions (*)

1. Magento Open Source 2.3.4 to 2.4.1
2. Configure Customer street lines to 3 or more lines
3. No additional module or configuration is required

### Steps to reproduce (*)

1. Go to Customer configuration in admin, and set the number of street lines to 3 or more (`customer/address/street_lines`)
2. In the frontend, proceed to checkout and add a new address. When adding a new address in the checkout, leave blank street lines in the middle. I.e: Populate line 1 with `Line 1` string, and line 3 with `Line 3` string.
3. After the order is placed and the address is saved, try to edit this address or see this address in the database (table `customer_address_entity`).

### Expected result (*)

1. It's expected to see the line 1 and 3 populated in the frontend when going to customer's adress book (/customer/address).
2. It's expected to see the value `Line 1⏎⏎Line 3` in the database

### Actual result (*)

1. The value we inserted in the address line 3 is displayed as line 2 when editing the address
2. In `customer_address_entity.street` column we see `Line 1⏎Line 3`.

Note that doesn't happen if you manually insert the address in customer area (instead of inserting it during the checkout).

![Screenshot_14_04_20_09_32](https://user-images.githubusercontent.com/191149/79170495-e09be880-7e32-11ea-8bcd-62320d4e0463.jpg)
![magento2playground____www_magento2playground__-_magento2playground_customer_address_entity__magento2playground_localhost_](https://user-images.githubusercontent.com/191149/79170441-bcd8a280-7e32-11ea-923c-59341165fc0d.jpg)
![Edit_Address](https://user-images.githubusercontent.com/191149/79170558-0fb25a00-7e33-11ea-988f-332d0357b988.jpg)

![issue-27847](https://user-images.githubusercontent.com/3409584/81244749-d3f55500-8fd8-11ea-9841-5c172ffed24e.gif)

### Additional Information
Quote from https://github.com/magento/magento2/issues/27847#issuecomment-625012111
 

> I don't remember problems in the frontend, except when editing the address.
> The main problem is that it breaks integrations that relies on the correct line. For instance, we use line 4 as Neighborhood in many stores in Brazil, but we faced integration issues when it's saved in line 3. It also breaks payments integrations(and payment methods) that requires neighborhood for placing an order. In those cases, registered customers can't place an order with an existing address.
> These are just a few cases.

**Comment by r-martins** [comment] 2020-04-13 23:40
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-13 23:41
Hi @r-martins. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-13 23:42
Hi @r-martins, here is your [Magento instance](https://i-27847-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27847-2-4-develop.instances.magento-community.engineering/admin_cf28](https://i-27847-2-4-develop.instances.magento-community.engineering/admin_cf28)
Login: `215c7447` Password: `b4652bc4c4cc`
Instance will be terminated in up to 3 hours.

**Comment by r-martins** [comment] 2020-04-13 23:52
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment] 2020-04-13 23:52
Hi @r-martins. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment] 2020-04-13 23:53
Hi @r-martins, here is your [Magento instance](https://i-27847-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-27847-2-3-4.instances.magento-community.engineering/admin_e1fa](https://i-27847-2-3-4.instances.magento-community.engineering/admin_e1fa)
Login: `f8da86f9` Password: `8287f1b7f570`
Instance will be terminated in up to 3 hours.

**Comment by r-martins** [comment] 2020-04-14 00:07
I could reproduce the error both in 2.3.4 and 2.4-develop instances.

**Comment by magento-engcom-team** [comment] 2020-04-14 07:14
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33344` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krishprakash** [comment] 2020-04-14 07:15
Reproduced on latest instance:

![image](https://user-images.githubusercontent.com/46617848/79196439-bd326700-7e4d-11ea-8d33-5042048b8afb.png)

**Comment by sdzhepa** [comment] 2020-05-07 01:16
Hello @r-martins 

I can confirm that
1. If Customer create new address during checkout = Steet Line 3 will be saved into address line 2
2. But if create new address from My account = line 2 will not be replaced 

Could you please provide any examples/scenarios when it brakes user flow on Storefront or creates any difficulties during development, etc?

Or the issue only about inconsistency in these cases?

**Comment by r-martins** [comment] 2020-05-07 03:44
Hello @sdzhepa . I don't remember problems in the frontend, except when editing the address.
The main problem is that it breaks integrations that relies on the correct line. For instance, we use line 4 as Neighborhood in many stores in Brazil, but we faced integration issues when it's saved in line 3. It also breaks payments integrations(and payment methods) that requires neighborhood for placing an order. In those cases, registered customers can't place an order with an existing address.
These are just a few cases.

**Comment by r-martins** [comment] 2021-01-15 02:36
I was able to test the Pull Request [#28126](https://github.com/magento/magento2/pull/28126) on Magento 2.4.1 and it seems it **does fix this issue**. I hope someone from Magento could notice the importance of this issue.

**Comment by r-martins** [comment] 2022-01-27 23:34
🎂 Happy birthday to this old and persistent bug! I hope someone takes care of you one day.

**Comment by ZIPITRO** [comment] 2022-03-17 10:21
Anyone can move this issue to the drawing table please?

**Comment by engcom-Bravo** [comment] 2024-06-26 04:28
Hi @r-martins,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the attached video.



https://github.com/magento/magento2/assets/51680745/03cc4911-b116-42fe-b271-9efdc4e1a296



We are able to to see the line 1 and 3 populated in the frontend when going to customer's adress book


Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-26 04:28 UTC
Labels: Issue: Ready for Work, Component: Customer, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Reproduced on 2.4.x, Priority: P3, Severity: S3, Triage: Done, Progress: done, Reported on 2.3.4
