### ISSUE TITLE
Shipping address fields blank, but ship methods remain after adding new product to cart 2.2.0

### ISSUE THREAD

**Issue by tstamplis** [magento/magento2#11574] opened 2017-10-20 07:04 UTC
### Preconditions
1.  Magento 2.2.0GA
2. Cpanel Server - PHP 7.0.12 
3. MySQL 5.6.37

### Steps to reproduce
1. Add product to cart
2. Proceed to checkout
3. Fill out shipping address fields
4. Carrier shipping methods are loaded (USPS, FEDEX)
5. Return to store (click logo top left)
6. Add a different product to cart
7.  Return to checkout

### Expected result
1. Shipping address fields remain
2. Shipping methods update for newly added product 
OR
1. Shipping address fields blank
2. NO shipping methods show (using carrier methods only, not flat rate or table rate)
(shipping address fields and methods update is preferred, of course!)

### Actual result
1. Shipping address fields are blank
2. Shipping methods from previously entered address fields still show and are not updated
3. Try to click a different shipping method, get error (method not found)

If you leave the checkout and come back, shipping address fields remain, as do shipping methods.  But if you leave checkout and add a new product to the cart, then return, shipping address fields are blank but shipping methods remain (though if you try to change methods, you get an error and if you try to proceed, no shipping method error.

**Comment by magento-engcom-team** [comment] 2017-10-20 11:07
@tstamplis, thank you for your report.
We've created internal ticket(s) MAGETWO-82411 to track progress on the issue.

**Comment by mrodespin** [comment] 2017-11-04 12:53
I am working on this issue #mm17es

**Comment by magento-engcom-team** [comment] 2019-06-20 20:37
Hi @tstamplis. 

Thank you for your report and collaboration!

The related internal Jira ticket `MAGETWO-82411` was closed as `non-reproducible` in `2.3.x`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Closed as completed by magento-engcom-team** 2019-06-20 20:37 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Issue:  Cannot Reproduce, Issue: Format is valid
