### ISSUE TITLE
php bin/magento setup:db-declaration:generate-whitelist command does not work when Magento install with prefix

### ISSUE THREAD

**Issue by sanjay-wagento** [magento/magento2#23032] opened 2019-05-28 10:32 UTC
### Preconditions (*)

1. Install Magento 2.3.1 with the prefix 

### Steps to reproduce (*)

1. Install Magento 2.3.1 with the prefix
2. Run `php bin/magento setup:db-declaration:generate-whitelist --module-name=Magento_Catalog` command

### Expected result (*)

1. Command must work and create db_schema_whitelist.json file

### Actual result (*)

1. It gives `Magento was installed with a table prefix. Please re-install without prefix.` message

**Comment by magento-engcom-team** [comment] 2019-09-11 12:34
@Den4ik Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-09-11 12:34
:white_check_mark: Confirmed by @Den4ik 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20114` were created

**Issue Available**: @Den4ik, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by buskamuza** [comment] 2019-10-01 16:44
This is expected behavior. The whitelist should be generated on dev environment by the extension developer, so it should not be necessary to support DB with prefix.
Presence of the prefix impacts names of DB entities (such as names of keys), and such names can't be used in the generated whitelist.
The whitelist is a temporary solution while we're migrating from old setup scripts to the declarative schema, and in the future will be eliminated (together with the whitelist command).

**Comment by sdzhepa** [comment] 2019-10-01 16:58
Hello @sanjay-wagento  and @Den4ik 

Thank you for contribution and collaboration!

Based on feedback from the Magento Architecture team it is not a bug.
Please see this https://github.com/magento/magento2/issues/23032#issuecomment-537123379 for more details and explanation.

I'm closing this issue

**Closed as completed by sdzhepa** 2019-10-01 16:58 UTC
Labels: Issue: Ready for Work, Component: Setup, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, WIP
