### ISSUE TITLE
Logging out when new Mega menu item is added 

### ISSUE THREAD

**Issue by tyeHTD** [magento/magento2#38342] opened 2024-01-09 19:01 UTC
### Preconditions and environment

- Magento version ver. 2.4.5-p1
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

Navigate to mega menu, add menu item and save. 

### Expected result

Menu item is added 

### Actual result

Item is not added and user is logged out.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-01-10 06:30
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-01-10 06:41
Hi @tyeHTD,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Navigate to mega menu, add menu item and save.

![Screenshot from 2024-01-10 12-10-07](https://github.com/magento/magento2/assets/51680745/d070158f-a2d7-49e8-a180-1443dbef9420)


Item was added to the cart and user is not logged out.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by andrewbess** [comment] 2024-01-10 14:13
Hello @tyeHTD 
Thank you for your contribution
I tried to reproduce it on the local environment
The problem is not reproducible with Magento 2.4.5-P1
Looks like you have 3rd-party extension that can provoke this problem
Please provide more details
Thank you in advance.

**Comment by engcom-Bravo** [comment] 2024-01-22 04:32
Hi @tyeHTD,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-01-22 04:32 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.5-p1
