### ISSUE TITLE
Cannot pass a different date & time format for order created_at

### ISSUE THREAD

**Issue by EliasZ** [magento/magento2#13072] opened 2018-01-09 12:48 UTC
### Preconditions
1.  Magento 2.2

### Steps to reproduce
1. Get an order's formatted created_at property with `Magento\Sales\Model\Order::getCreatedAtFormatted`

### Expected result
1. Be able to fully customize the date and time format

### Actual result
1. You can pass a `IntlDateFormatter` constant indicating which format to use but it is applied to both the date and time display:

```
    /**
     * Get formatted order created date in store timezone
     *
     * @param   string $format date format type (short|medium|long|full)
     * @return  string
     */
    public function getCreatedAtFormatted($format)
    {
        return $this->timezone->formatDateTime(
            new \DateTime($this->getCreatedAt()),
            $format,
            $format,
            null,
            $this->timezone->getConfigTimezone('store', $this->getStore())
        );
    }
```

As you can see `$format` is passed to the `formatDateTime` method for both the `$dateType` and `$timeType` argument. I would expect two arguments (`$dateFormat` and `$timeFormat`) for the `getCreatedAtFormatted` method? With the second one being null and defaulting to the first one if it isn't set.

**Comment by magento-engcom-team** [comment] 2018-02-15 08:34
@EliasZ, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2019-02-20 18:39
Hi @devamitbera. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by devamitbera** [comment] 2019-02-22 11:27
@magento-engcom-team ,is mail server not working at test instance?

Is there any way to access SSh of that server?

Note:Even,don't get customer new creation mail.

**Comment by devamitbera** [comment] 2019-02-28 07:23
@sivaschenko, Sorry I don't understand why this  PR is closed.Can you please explain.

If  adding an extract parameter to` public function getCreatedAtFormatted($dateFormat, $timeFormat = \IntlDateFormatter::MEDIUM)` ,Is the reason  of closing this PR  then i believe  that 

https://github.com/magento/magento2/issues/13072  should  be closed as  this issue main purpose is . `getCreatedAtFormatted() ` can support  different date & time format.

Another solution for this case, I can introduce an  method which can different date & time format for return of  created_at value..

Kindly put your valuable view on this issue

**Comment by sivaschenko** [comment] 2019-03-21 13:43
In my opinion that is not an issue, but a description of specific function configurability limitations. The client code can use `getCreatedAt` method of order model and format the value based on its preferences. Also, it's better to keep formatting operations in the presentation layer rather than in a model

**Closed as completed by sivaschenko** 2019-03-21 13:43 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid

**Comment by devamitbera** [comment] 2019-03-21 13:53
@sivaschenko , i am agreed with you.
