### ISSUE TITLE
Theme type changed after switch code branch

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#34126] opened 2021-09-20 11:00 UTC
### Summary (*)

Got this issue when i change local code base. Not sure underneath why code base do such behavior
Here is my use case
Example i have some theme in mainline code.
==main-line ===> theme A B C
when new requirements create new theme D i switch branch from main-line to develop

==develop ==== theme A B C D (still good work here) => type theme D =  0

but sometimes i work with code/task at main

switch back to main-line. But now the magic happen. Seem theme type of D (in DB reference table theme) after switch code branch will change to 1 (previous is 0). And this value not able to change back. You have to connect modify directly to DB when you work again with theme D at branch develop. Seem look cool feature underneath base

Expected results
theme type switch back to 0 

Actual results
theme type still 1

0 mean type physical
1 mean type virtual

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2021-12-24 09:54
Hi @mrtuvn  ,

Thank you for raising an issue , we are happy to work on this issue . Kindly provide steps to reproduce , actual results with screenshots.

Regards,

**Comment by mrtuvn** [comment] 2021-12-24 13:34
This can reproduceable in development scenario
Example
Main codeline branch (master) created theme ABC. Now developer switch to feature (branch) create new theme D. Everything setup theme correctly without problem. Now developer switch code back to branch master. And run setup upgrade to continues works at this branch. Now if we check database (theme database) , magento setup theme D to type 1 (virtual) in the behind the scenes without notify to developer. And it's never change back to 0 (physical). That may be make developer very confuse and take sometimes to realise the problem. 
Not theme virtual type will not apply any layout. So basically changes in layout xml will not apply at all

**Comment by engcom-Hotel** [comment] 2022-03-03 11:24
Hello @mrtuvn,

We have tried to reproduce the issue in Magento 2.4-develop branch, but for us, the issue is not reproducible. We have followed the below steps to reproduce:

Steps:
1. Create a theme in the Master branch and check the `theme` table for its entry. Please have a look at the below screenshot:
![with_master_theme_1](https://user-images.githubusercontent.com/51681618/156555099-b2b3a561-5f6b-4670-95b8-a2e93bd0d9fb.jpg)
2. Create a new branch and then create a theme in that branch. And then check the `theme` table for its entry. Please have a look at the below screenshot:
![with_feature_theme_1](https://user-images.githubusercontent.com/51681618/156555216-94f50205-2507-4b95-9e77-68e80f3d906a.jpg)
3. Switch back to the `master` branch and check the `theme` table for its entry. Please have a look at the below screenshot:
![switch_back_to_master](https://user-images.githubusercontent.com/51681618/156555307-72132105-f3dd-4e75-90ca-371a8ba311d4.jpg)

Please let us know if we have missed anything in order to reproduce the issue.

Thanks

**Comment by engcom-Hotel** [comment] 2022-03-04 05:53
Hello @mrtuvn,

I have tried the steps given in your last [comment](https://github.com/magento/magento2/issues/34126#issuecomment-1057973423) as well, but for us, the values are not changing in the database. Please have a look at the below screenshot:

- In `master` branch after running `setup:upgrade` command:

![1](https://user-images.githubusercontent.com/51681618/156707524-a4acfd46-a4ba-4155-a7da-aab3dcfff2d5.jpg)

- In `feature_34126` branch  after running `setup:upgrade` command:
![2](https://user-images.githubusercontent.com/51681618/156707644-6379f184-1414-4a28-963f-45a1e5b727b4.jpg)

Please let us know we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2022-03-21 08:10
Dear @mrtuvn,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-03-21 08:10 UTC
Labels: Triage: Dev.Experience, Issue: needs update
