### ISSUE TITLE
Logo url contains "/pub" in asynchronous command line generated emails

### ISSUE THREAD

**Issue by textarea** [magento/magento2#27043] opened 2020-02-26 19:05 UTC
### Preconditions (*)
1. Magento 2.3.4

### Steps to reproduce (*)
1. Magento store is running on the webserver docroot /path_to_magento/pub
2. Logo image selected in Content->Design->Configuration->Transactional Emails->Logo Image [design/email/logo db setting] (let's assume the value is "default/mylogo.png")
3. Run an email with a template with logo tag with variable **{{var logo_url}}** from command line or by Magento cron (email sent from any http(s) action will work because webserver is calling /path_to_magento/pub/index.php while Magento cron use /path_to_magento/index.php).

### Expected result (*)
1. Received email with visible remote image
2. Remote image logo has url https://store_url/media/email/logo/default/mylogo.png

### Actual result (*)
1. Cannot load remote image logo
2. Remote image logo has url https://store_url/pub/media/email/logo/default/mylogo.png which is unreachable from the webserver.

**Comment by magento-engcom-team** [comment] 2020-02-27 10:04
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31958` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dmytro-ch** [comment] 2020-02-27 10:11
Hello, @textarea, thank you for the report.

Confirmed, the issue is reproducible in `2.4-develop` branck.
<img width="559" alt="Screenshot 2020-02-27 at 12 08 16" src="https://user-images.githubusercontent.com/11693779/75434204-dd6b9c80-5959-11ea-937c-6de7235ad1b6.png">

**Comment by thiaramus** [comment] 2020-04-06 15:31
The internal Magento team is working on this issue right now.

**Comment by thiaramus** [comment] 2020-04-14 21:21
Hi @textarea, 

When the webserver is configured to serve the Magento app from the `/pub` directory, it is necessary to add the node below to the `app/etc/env.php` file.

```conf
'directories' => [
    'document_root_is_pub' => true
]
```

This issue should not be reproducible afterward. 

We are working to update the documentation with this information.

**Comment by textarea** [comment] 2020-04-15 10:51
Hi @thiaramus,

thanks, I confirm that the issue is not reproducible after adding that setting.
Regards

**Comment by hostep** [comment] 2020-04-15 11:12
@thiaramus: next to some documentation, it would also be nice if this could be set automatically during Magento's installation, like with an additional flag in the `bin/magento setup:install` command for example, so this can be automated instead of having to do it manually.

**Comment by sdzhepa** [comment] 2020-04-21 14:02
Hello @textarea 

Based on https://github.com/magento/magento2/issues/27043#issuecomment-613687993
Documentation has been updated:
- https://devdocs.magento.com/guides/v2.3/config-guide/prod/config-reference-envphp.html#directories
8:57
- https://devdocs.magento.com/guides/v2.3/install-gde/tutorials/change-docroot-to-pub.html#3-update-the-envphp-file

This issue can be closed

**Closed as completed by sdzhepa** 2020-04-21 14:02 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Email, Reproduced on 2.4.x, Reported on 2.3.4
