### ISSUE TITLE
Max Qty Allowed: Core Magento feature removed by #18477 and causes bug #23319

### ISSUE THREAD

**Issue by duffner** [magento/magento2#23731] opened 2019-07-16 16:16 UTC
Through ticket #18477, a core Magento feature was removed.  When removing the ability to set "0" as an allowed value of Max Qty in Cart, multiple things happen. 

1. *The ability to have an "infinite" value allowed in the cart no longer exists, this forces store administrators to set some crazy value or 1,000,000 for this setting since most stores don't restrict by Max amount in cart.  This has been native Magento behavior for 11 years
2. Bug #23319 is now introduced because the previous default value of 0 is the core default. 
3. Minor issue, but decimal-based inventory no longer works, because sometimes an allowed value of .5 which is now no longer valid (Separate ticket for this will be created) 

### Preconditions (*)

1. Magento 2.3.2 & 2.2.8

### Steps to reproduce (*)

1. Install Magento 2.3.1 or 2.2.7 
2. Create a test product 
3. Ensure Max Qty in Cart remains at the default value of "0"
4. Attempt to save a product

### Expected result (*)

1. [Screenshots, logs or description]
2. The product should save with "0" as the value set for "Max Quantity in Cart" 

### Actual result (*)

1. [Screenshots, logs or description]
2. Error #23319 is presented 
3. Product with Max Quantity of "0" cannot be saved  

If a customer has an issue with this value, then they should update this value themselves instead of Magento removing this feature.

**Comment by engcom-Bravo** [comment] 2019-07-17 08:15
Hi, @duffner ! I can't reproduce this issue on fresh 2.3-develop branch and on 2.3.1, because this is already fixed(added validation for "max qty in cart" input). 
![maxqty](https://user-images.githubusercontent.com/51680745/61358927-0be1af00-a884-11e9-95c9-3f4d31c00ef1.png)
So i have to close this issue. 
Thank for your report!

**Closed as completed by engcom-Bravo** 2019-07-17 08:15 UTC
Labels: Issue: Clear Description, Fixed in 2.3.x, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Inventory

**Comment by duffner** [comment] 2019-08-21 14:23
@engcom-Bravo, maybe you don't understand.   

I want infinite allowed in the shopping cart, how is this possible today?

**Comment by engcom-Bravo** [comment] 2019-08-21 14:53
@duffner, this GitHub issue tracker is intended for Magento Core technical issues only. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. Thank You.

**Comment by hostep** [comment] 2019-08-21 18:44
I kind of agree with @duffner here, if the number 0 previously had a special meaning of infinite then the changes done in https://github.com/magento/magento2/pull/18481 & https://github.com/magento/magento2/pull/18552 were not correct.

To make this consistent with the global config value, either the same validation should be applied to that field, or the new validation from above PR's should get reverted.

However, the default value for that field is set to 10.000, I just verified this both in code as in a vanilla installation.
@duffner: Is there a valid use case for shop owners wanting this field to be bigger than the default 10.000? I understand it's "just a number". But are people actually putting more than 10.000 of something in their cart? And isn't it then enough to only update the global value to a number even more crazy than 10.000?

I think it's enough to keep https://github.com/magento/magento2/issues/23319 open as that seems to track the same problem, I'm leaving this one closed for now.

**Comment by hostep** [comment] 2020-08-20 20:43
Hi @duffner

Sorry currently little time to dig into this again (it was indeed a while ago), but I'm noticing that #23319 is fixed now in Magento 2.3.4 by MC-17606.
There isn't 1 merge commit but 4 apparently:
- https://github.com/magento/magento2/commit/d6b08dc90a6e032d8dfd33c2b386ab46de9b22bb
- https://github.com/magento/magento2/commit/b413b024507c7d817b54514294c3d8079e98cfe0
- https://github.com/magento/magento2/commit/3081c38cd3f8b949032a4703f921a7bc2d6ab7b5
- https://github.com/magento/magento2/commit/c4b62a3ecad68df6834ea7e25c6cf790ca96e24e

If I understand Magento's fix correctly, it kind of fixes the issue, but not like you want probably.
Have you already tested this issue on 2.3.4 or higher and does it work more like expected or not?
