### ISSUE TITLE
Status downloadable product stays pending after succesfull payment

### ISSUE THREAD

**Issue by KooTjoo** [magento/magento2#22545] opened 2019-04-29 17:04 UTC
When a downloadable product has been order and paid for download status should automatically become available. Status remains pending although order is invoiced and completed automatically by payment processor. When order is invoiced from admin it all works.

### Preconditions (*)

1. Magento 2.3.1 CE
2. PHP 7.2

### Steps to reproduce (*)

1. Setup Magento site with demo contents
2. Order Item Status to Enable Downloads->Invoiced
3. Setup Payment for instance Paypal
4. Make purchase of downloadable product with payment method Paypal
5. Make sure payment is succesfull (Order status is completed) 

### Expected result (*)

1. Download link should be available in customer account
2. Status of downloadable product should be available

### Actual result (*)

1. In customer account order status is completed
2. In customer account downloadable product is pending

When an order is placed and in Magento admin the order is invoiced the it works as it should. So somehow downloadable status is not changed when an order is automatically set to completed when payment is succesfull.

This issue occured only after upgrading to Magento 2.3.1 in 2.3.0 it all worked like it should.

**Comment by magento-engcom-team** [comment] 2019-04-29 19:45
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99452` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by shikhamis11** [comment] 2019-05-04 04:16
I am working on this at #dmcdindia1

**Comment by saeohioalpha** [comment] 2019-07-03 14:06
To fix this without waiting for the PR to be approved and pushed to the next release.

1. Edit vendor/magento/module-downloadable/Observer/SaveDownloadableOrderItemObserver.php
   a. Apply changes on lines specified in:
https://github.com/magento/magento2/pull/22658/files
   b. See changes inline in full file:
https://raw.githubusercontent.com/magento/magento2/1524687560c4a71322eefd4448ff79d9ea334ac9/app/code/Magento/Downloadable/Observer/SaveDownloadableOrderItemObserver.php
2. Also (pre-2.3.2) make sure Lines 95-100 match as well. These were changed in 2.3.2
        $storeId = $orderItem->getOrder()->getStoreId();
        $orderStatusToEnableItem = $this->_scopeConfig->getValue(
            \Magento\Downloadable\Model\Link\Purchased\Item::XML_PATH_ORDER_ITEM_STATUS,
            ScopeInterface::SCOPE_STORE,
            $storeId
        );
3. Recompile/Redeploy:
a. bin/magento deploy:mode:set developer
b. bin/magento deploy:mode:set production

Testing on my store, this fixes the download link problem.

**Comment by magento-engcom-team** [comment] 2019-07-07 23:10
Hi @KooTjoo. Thank you for your report. 
The issue has been fixed in magento/magento2#22658 by @shikhamis11 in 2.3-develop branch
Related commit(s):
 - [c4dc289c57852cfe906462a605c7aaff814932d7](https://github.com/magento/magento2/commit/c4dc289c57852cfe906462a605c7aaff814932d7)
 - [7174745ab7e2443349a644f64261b388b41935b7](https://github.com/magento/magento2/commit/7174745ab7e2443349a644f64261b388b41935b7)
 - [630bbb5276780e97a67d747d0ab58ee790d5b015](https://github.com/magento/magento2/commit/630bbb5276780e97a67d747d0ab58ee790d5b015)
 - [a800c6b9e24ad23d97e4a9c8369a1042aaf23b5b](https://github.com/magento/magento2/commit/a800c6b9e24ad23d97e4a9c8369a1042aaf23b5b)
 - [e2f06b37cc7a6640fa24b59971f5aee3cf96641d](https://github.com/magento/magento2/commit/e2f06b37cc7a6640fa24b59971f5aee3cf96641d)
 - [1524687560c4a71322eefd4448ff79d9ea334ac9](https://github.com/magento/magento2/commit/1524687560c4a71322eefd4448ff79d9ea334ac9)

The fix will be available with the upcoming 2.3.3 release.

**Closed as completed by magento-engcom-team** 2019-07-07 23:10 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Downloadable, Event: dmcdindia1

**Comment by janmech** [comment] 2019-10-27 16:49
i came up with a very simple fix (though) it probably needs further testing. I figured that the problem is that changes/new entries in  downloadable_link_purchased are not yet committed when SaveDownloadableOrderItemObserver is executed.

my 1-line fix/proposition is changing the module-downloadable/etc/events.xml:
FROM:

&#x3C;event name="sales_order_save_after"&#x3E;
        &#x3C;observer name="downloadable_observer" instance="Magento\Downloadable\Observer\SetLinkStatusObserver" /&#x3E;
        &#x3C;observer name="downloadable_observer_assign_customer" instance="Magento\Downloadable\Observer\UpdateLinkPurchasedObserver" /&#x3E;
&#x3C;/event&#x3E;

TO:
&#x3C;event name="sales_order_save_commit_after"&#x3E;
        &#x3C;observer name="downloadable_observer" instance="Magento\Downloadable\Observer\SetLinkStatusObserver" /&#x3E;
        &#x3C;observer name="downloadable_observer_assign_customer" instance="Magento\Downloadable\Observer\UpdateLinkPurchasedObserver" /&#x3E;
&#x3C;/event&#x3E;
