### ISSUE TITLE
Error in TinyMCE when typing %-character

### ISSUE THREAD

**Issue by Arriba99** [magento/magento2#8369] opened 2017-02-01 15:28 UTC
### Preconditions
1.  Magento 2.1.3 CE
2.  PHP 5.6.21

### Steps to reproduce
1. Open product or page
2. Type %-character in TinyMCE Editor field

### Expected result
1. Everything should be fine

### Actual result
1. Immediatly an error is displayed (2 times):
error: error in [unknown object].fireEvent(): event name: tinymceChange error message: malformed URI sequence

![unbenannt-1](https://cloud.githubusercontent.com/assets/25484339/22512870/b3a1c1c8-e89a-11e6-83be-f6bdab001636.jpg)

Once the %-character is typed in the editor, the error pops up again everytime you type in the editor field. All other characters doesn't trigger the error. When the product or page is saved, the %-character gets deleted in the text.

We use another magento installation for testing and there the error doesn't show up. 

Kind regards!

**Comment by fxdegroot** [comment] 2017-05-12 18:27
We got the exact same problem on Magento 2.1.4 EE

**Comment by hostep** [comment] 2017-05-14 12:50
That's really strange, since the code which causes this problem is only active in the `develop` branch and not in a previously released version. See https://github.com/magento/magento2/issues/9452 for more details.
Although the error message is slightly different (`malformed URI sequence` vs `URI malformed`), so maybe this is then a different issue?

**Comment by veloraven** [comment] 2017-06-21 08:23
We already have internal ticket for ver. 2.1 - MAGETWO-68810

**Comment by magento-engcom-team** [comment] 2017-09-20 22:56
@Arriba99, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:56 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
