### ISSUE TITLE
Why "search_tmp_" used? and whats use of it?

### ISSUE THREAD

**Issue by nagrgk** [magento/magento2#26184] opened 2019-12-26 13:52 UTC
#15545 
https://magento.stackexchange.com/questions/143420/magento2-search-tmp-join-leads-to-empty-results-in-category-listing

### Preconditions
There are lot of issues with Magento, biggest is performance issue at category/search.
Main issue is creating dynamic tables on run time and causing lot of issues.
1. create search_tmp temp table when click on category/search
2. it creates more than 12 or 24 tables for every search you do for any keyword or sometime it goes more than 40.

### Steps to reproduce (*)
1. take any magento2 website and search for any product
2. it creates dynamic tables and drop it after search is done

### Expected result (*)
1. it should not create temp tables on run time and causing website down

### Actual result (*)
1. it should not create temp tables on run time

questions:
1. why search_tmp tables introduced in Magento2 , what is reason?
2. lets says it has been introduced but why is it generated at website run time , in frontend or when you search for product?
3. why same Magento1 approach not used? is it something being used with scheduling?
4. How can we not use search_tmp tables?
5. There are so many queries regarding this, why is it not being answered? is it resolved in latest versions?
6. Any actions had been taken in Magento2.3.3?
7. Why it is being used when customer searching products and creating more than 12 tables in single page?
8. Lets says if search_tmp not completed, page goes to not responding, it ends up creating sleep queries. queries are not being killed which supposed to kill after page render.
9. is this happening with Elastic search? I dont think so, because I could see issue even after enabling mysql search.

Please let all questions answered because all customers facing this issue. customers are running huge servers to keep website up and running. 

Please help.

Thanks
nagaraj

**Comment by nagrgk** [comment] 2019-12-26 13:59
yes, it is reproducible in vanilla Magento

**Comment by engcom-Hotel** [comment] 2020-01-13 13:09
Hello @nagrgk 
I am not able to reproduce this issue on a fresh Magento 2.4-develop because `search_tmp_` table usage was deprecated. 
![image](https://user-images.githubusercontent.com/51681618/72258133-f6242b00-3615-11ea-848b-58729e3521fc.png)
Magento is using `search_query` table now:
![image](https://user-images.githubusercontent.com/51681618/72258376-92e6c880-3616-11ea-9432-a03721fa7c45.png)

So i have to close this issue as not relevant.

Thanks for your report!

**Comment by hostep** [comment] 2020-01-13 13:46
@engcom-Hotel, it doesn't mean that if the class is marked as deprecated that it is no longer used within Magento.
I can still find at least 3 references in Magento's CatalogSearch module where it is being used.

Also be aware that not every single Magento user is able to run ElasticSearch on their hosting, a lot of Magento users will still use Mysql as the search engine.

I'm reopening, because it was closed for the wrong reason.

**Comment by nagrgk** [comment] 2020-01-13 13:51
@engcom-Hotel 
2.4 is long way to go. search_temp queries are killing stores.

Before you justify, please think about the performance and business use cases always.
here people are very eager to close tickets and not take any actions and not thinking about the end users.

**Comment by engcom-Hotel** [comment] 2020-01-13 15:34
@hostep @nagrgk 
i have to discuss with my team lead about this issue, because we cannot just confirm issues that are not reproducible on the Magento 2.4-develop.

**Comment by nagrgk** [comment] 2020-01-13 15:47
@engcom-Hotel 
looks this is perfect reply. taking time and investigating is always best than just closing.

thanks

**Comment by magento-engcom-team** [comment] 2020-01-14 15:45
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30417` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Hotel** [comment] 2020-01-14 15:51
Hello @hostep @nagrgk 
Sorry for my mistake. I did not understand the description correctly.
Now we found a problem.

Thanks for collaboration!

**Comment by arunelangovan** [comment] 2020-04-08 15:22
Is there any fix or patch so far, Our productions is getting killed atleast once a day.

**Comment by ilnytskyi** [comment] 2020-04-08 16:48
Using ES may help. Or even better to profile the application and eliminate redundant queries on DB
dxebug dumps 
this profiler 
https://github.com/NoiseByNorthwest/php-spx
or xdebug
removing join from that table would result with empty filters in layered navigation

**Comment by arunelangovan** [comment] 2020-04-08 19:11
@ilnytskyi We are using elastic search, but not sure what went wrong. We get same error. The above query is hitting with DB again whenever we lift up maintenance page

Can you lead me to a possible fix?

**Comment by arunelangovan** [comment] 2020-04-08 19:50
@magento-engcom-team @engcom-Hotel  Any insight on the above issue?

**Comment by sshymko** [comment] 2020-05-01 21:46
@nagrgk 
We've experienced the issue with the queries `INSERT INTO search_tmp_*` overloading the MySQL database hosted at AWS. Normally, such queries execute very quickly in under ~10ms. However, occasionally dramatic and prolonged spikes are observed in the New Relic APM.
![DoHDkDbU8AEhqKR](https://user-images.githubusercontent.com/1231423/80843358-fd694780-8bb8-11ea-8aa7-0de7adff8e7a.jpeg)


**The root cause** turned out to be **exceeding Write IOPS** of the RDS database. By default, RDS databases have a General Purpose (SSD) storage. Such databases accrue the IOPS credits at a rate dependent on the database storage size. If the database load exceeds the credits accumulation rate, all credits will be used up and AWS will artificially limit the database performance. In our case. the limit was ~300 Write IOPS. You can see your Write IOPS stats in the RDS monitoring charts.
![aws_rds_write_iops_limit](https://user-images.githubusercontent.com/1231423/80843975-6ef5c580-8bba-11ea-80fd-ed67776b3bf4.png)

**The solution** is to upgrade the Storage Type to the Provisioned IOPS. 1000 IOPS cost like $100/mo and are well worth the expense.
<img width="594" alt="aws_rds_provisioned_iops" src="https://user-images.githubusercontent.com/1231423/80843921-4ec60680-8bba-11ea-993d-8950edee6592.png">

**Comment by sshymko** [comment] 2020-05-01 22:31
Related bug #9807

**Comment by arunelangovan** [comment] 2020-05-04 19:44
@sshymko Thanks for the explanation

**Comment by maghamed** [comment] 2020-07-14 21:21
hey @nagrgk, 
the main reason why we have dynamically generated `search_tmp` table is the way how Magento search works right now, and in particular that internally our Search API returns the only IDs of matched documents, but not documents by themselves. 

The simplified algorithm is quite simple. 

1. User makes request specifying needed filters and providing search phrase 
2. Magento builds either MySQL (deprecated since 2.4.0) or Elasticsearch Full-Text Search query and processes this request. As a result a bunch (up to 10 000 results) of document IDs which correspond to the search query is returned
3. Then Magento has to refine data for those entities (currently we support only product search). So, the system needs to retrieve data for the bunch of product IDs above. There are two options here:
a. Make a query similar to`Select ... from catalog_product_entity where entity_ID in (lis_of_ids_here)`
b. Store the IDs into a temporary table and then make a query with join, similar to `select .. from catalog_product_entity inner join search_tmp where catalog_product_entity.entity_id = search_tmp.entiry_id`

The last option is more efficient if the number of returned documents is high because MySQL would use an index for joining tables, while in case of the query with IN (many_ids) - most probably query optimizer will decide to end up with disk scan.

The behavior is the same for both adapters MySQL and Elasticsearch because currently both of them follow the same API (read return IDs of documents found, but not data itself).

Regarding the spikes you mentioned @sshymko, we noticed similar spikes on some installations before. It was really hard to reproduce those spikes while testing, and as far as I remember those issues were specific to particular MySQL/Maria version and been solved with an upgrade.

**Comment by sivaschenko** [comment] 2020-09-17 16:34
The issue may be not actual as MySQL was removed from Magento version 2.4.0 and Elasticsearch should be used instead

**Comment by gabrieldagama** [comment] 2020-09-30 09:22
Closing this issue because it is not actual since MySQL was removed from Magento version 2.4.0 and Elasticsearch should be used instead.

**Comment by hws47a** [comment] 2020-09-30 09:30
I believe all the comments above state that the issue is still present even when you have Elasticsearch enabled. It's also reproduced in 2.4

**Comment by gabrieldagama** [comment] 2020-09-30 10:13
Hi @hws47a, I've done some investigation on this before closing, but maybe I'm missing something. 

As far as I understood `Magento\Framework\Search\Adapter\Mysql\TemporaryStorage` is being used by `Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplier` which is an implementation of `Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplierInterface` and it's preference is being  overwriten by ElasticSearch's implementation `Magento\Elasticsearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplier`.

On my investigation, from what I could see, the ids that come from ElasticSearch are filtered with an `e.entity_id IN (?)` condition, as shown on `Magento\Elasticsearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplier` line 73, as a result we are getting the following query:

```
SELECT `e`.*,
       `price_index`.`price`,
       `price_index`.`tax_class_id`,
       `price_index`.`final_price`,
       IF(price_index.tier_price IS NOT NULL, Least(price_index.min_price,
                                              price_index.tier_price),
       price_index.min_price)                   AS `minimal_price`,
       `price_index`.`min_price`,
       `price_index`.`max_price`,
       `price_index`.`tier_price`,
       Ifnull(review_summary.reviews_count, 0)  AS `reviews_count`,
       Ifnull(review_summary.rating_summary, 0) AS `rating_summary`,
       `stock_status_index`.`stock_status`      AS `is_salable`
FROM   `catalog_product_entity` AS `e`
       INNER JOIN `catalog_product_index_price` AS `price_index`
               ON price_index.entity_id = e.entity_id
                  AND price_index.customer_group_id = 0
                  AND price_index.website_id = '1'
       INNER JOIN `catalog_product_website` AS `product_website`
               ON product_website.product_id = e.entity_id
                  AND product_website.website_id = 1
       LEFT JOIN `review_entity_summary` AS `review_summary`
              ON e.entity_id = review_summary.entity_pk_value
                 AND review_summary.store_id = 1
                 AND review_summary.entity_type = (SELECT
                     `review_entity`.`entity_id`
                                                   FROM   `review_entity`
                                                   WHERE  ( entity_code =
                                                            'product' ))
       INNER JOIN `cataloginventory_stock_status` AS `stock_status_index`
               ON e.entity_id = stock_status_index.product_id
                  AND stock_status_index.website_id = 0
                  AND stock_status_index.stock_id = 1
WHERE  ( stock_status_index.stock_status = 1 )
       AND ( e.entity_id IN ( 1 ) )
ORDER  BY Field(e.entity_id, 1) 
```

I've tried to find any usage of this temporary table but wasn't able to. Can you please provide more details on why you believe this is still actual?

Thanks

**Comment by gabrieldagama** [comment] 2020-10-05 08:29
Closing this issue again, please, if you find evidence that the `search_tmp` is being used provide more details here and re-open the issue.

Thank you.

**Closed as completed by gabrieldagama** 2020-10-05 08:29 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: CatalogSearch, Triage: Dev.Experience, Reproduced on 2.4.x, Severity: S2, Progress: done

**Comment by webrod** [comment] 2020-11-08 08:22
Hi, on magento 2.4.1, tmp table is still used, see logged query:
SELECT COUNT(DISTINCT e.entity_id)
FROM `catalog_product_flat_1` AS `e`
INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.customer_group_id = 0 AND price_index.website_id = '1'
INNER JOIN `catalog_category_product_index_store1` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id=1 AND cat_index.visibility IN(3, 4) AND cat_index.category_id=1997
INNER JOIN `cataloginventory_stock_status` AS `stock_status_index` ON e.entity_id = stock_status_index.product_id
INNER JOIN `search_tmp_5fa7aa3ad505c7_73512525` AS `search_result` ON e.entity_id = search_result.entity_id
WHERE (stock_status_index.stock_status = 1)

**Comment by scott-xigen** [comment] 2020-11-25 09:09
> Hi @hws47a, I've done some investigation on this before closing, but maybe I'm missing something.
> 
> As far as I understood `Magento\Framework\Search\Adapter\Mysql\TemporaryStorage` is being used by `Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplier` which is an implementation of `Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplierInterface` and it's preference is being overwriten by ElasticSearch's implementation `Magento\Elasticsearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplier`.
> 
> On my investigation, from what I could see, the ids that come from ElasticSearch are filtered with an `e.entity_id IN (?)` condition, as shown on `Magento\Elasticsearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplier` line 73, as a result we are getting the following query:
> 
> ```
> SELECT `e`.*,
>        `price_index`.`price`,
>        `price_index`.`tax_class_id`,
>        `price_index`.`final_price`,
>        IF(price_index.tier_price IS NOT NULL, Least(price_index.min_price,
>                                               price_index.tier_price),
>        price_index.min_price)                   AS `minimal_price`,
>        `price_index`.`min_price`,
>        `price_index`.`max_price`,
>        `price_index`.`tier_price`,
>        Ifnull(review_summary.reviews_count, 0)  AS `reviews_count`,
>        Ifnull(review_summary.rating_summary, 0) AS `rating_summary`,
>        `stock_status_index`.`stock_status`      AS `is_salable`
> FROM   `catalog_product_entity` AS `e`
>        INNER JOIN `catalog_product_index_price` AS `price_index`
>                ON price_index.entity_id = e.entity_id
>                   AND price_index.customer_group_id = 0
>                   AND price_index.website_id = '1'
>        INNER JOIN `catalog_product_website` AS `product_website`
>                ON product_website.product_id = e.entity_id
>                   AND product_website.website_id = 1
>        LEFT JOIN `review_entity_summary` AS `review_summary`
>               ON e.entity_id = review_summary.entity_pk_value
>                  AND review_summary.store_id = 1
>                  AND review_summary.entity_type = (SELECT
>                      `review_entity`.`entity_id`
>                                                    FROM   `review_entity`
>                                                    WHERE  ( entity_code =
>                                                             'product' ))
>        INNER JOIN `cataloginventory_stock_status` AS `stock_status_index`
>                ON e.entity_id = stock_status_index.product_id
>                   AND stock_status_index.website_id = 0
>                   AND stock_status_index.stock_id = 1
> WHERE  ( stock_status_index.stock_status = 1 )
>        AND ( e.entity_id IN ( 1 ) )
> ORDER  BY Field(e.entity_id, 1) 
> ```
> 
> I've tried to find any usage of this temporary table but wasn't able to. Can you please provide more details on why you believe this is still actual?
> 
> Thanks

What if we're using a third party search like Algolia or Klevu, rather the Elasticsearch, which means we have to have Elasticsearch turned off to work?
