### ISSUE TITLE
ElasticSearch MG 234

### ISSUE THREAD

**Issue by dtavieres** [magento/magento2#27112] opened 2020-02-29 19:38 UTC
Hello,

We do experimenting an issue with Elasticsearch 6, we do not have any issues with mysql but enabling Elasticsearch in a clean installation (MG234, Ubuntu 18, Php 7.2 and 7.3 we are facing  the following  message. 

Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Elasticsearch\Model\Adapter\FieldMapper\Product\AttributeProvider::getByAttributeCode() must be of the type string, null given, called in /var/www/html/magento2/vendor/magento/module-elasticsearch/SearchAdapter/Query/Builder/Sort.php on line 92 and defined in /var/www/html/magento2/vendor/magento/module-elasticsearch/Model/Adapter/FieldMapper/Product/AttributeProvider.php:72 Stack trace: #0 /var/www/html/magento2/vendor/magento/module-elasticsearch/SearchAdapter/Query/Builder/Sort.php(92): Magento\Elasticsearch\Model\Adapter\FieldMapper\Product\AttributeProvider->getByAttributeCode(NULL) #1 /var/www/html/magento2/vendor/magento/module-elasticsearch/Elasticsearch5/SearchAdapter/Query/Builder.php(91): Magento\Elasticsearch\SearchAdapter\Query\Builder\Sort->getSort(Object(Magento\Framework\Search\Request)) #2 /var/www/html/magento2/vendor/magento/module-elasticsearch/Elasticsearch5/SearchAdapter/Mapper.php(66): Magento\Elasticsearch\Elasticsearch5\SearchAdapter\Qu in /var/www/html/magento2/vendor/magento/module-elasticsearch/Model/Adapter/FieldMapper/Product/AttributeProvider.php on line 72

Since there are no other mention. we assume that the problem is with any misconfiguration or typo , such as dob (by the way, it was'nt fixes In 2.3.4)  in customers

Thank you in advance. 

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by dtavieres** [comment] 2020-03-03 02:51
Hello, We did not try to reproduce the issue at vanilla Magento instance but  we tried several times, with clean instances, alway we do have the same overcame. Ubuntu 18, MySql 5.6, Php 7.3 and php 7.2, mod apache and fpm, AWS ElasticSearch service 6.7 and 6.8 but always we had the same result.  Since the catalog search in MYSQL mode presents no problems, something In the module elasticsearch/elasticsearch may be wrong or any kind of typo is present. 
Thank you in advance.

**Comment by parekhreena** [comment] 2020-03-04 11:38
We are facing same error with Magento CE 234

**Comment by ASWC** [comment] 2020-03-06 18:47
Exact same issue with exact same error code on cloud: 

php 7.3.11
mgc 2.3.4
elasticsearch 6.7.2
mariaDB 10.0.37


No problem on local cloud instance clone.
Local cloud clone update to 2.3.4 (no error)

php 7.1.33
mgc 2.3.4
elasticsearch 6.7.2
mysql 5.7.26

**Comment by dtavieres** [comment] 2020-03-09 17:15
Good afternoon, Did anyone find a fix for this issue? Thank you

**Comment by jaywilliams** [comment] 2020-03-30 18:46
Here's a simple patch I used to help fix this issue on Magento 2.3.4:

```diff
diff --git a/vendor/magento/module-elasticsearch/SearchAdapter/Query/Builder/Sort.php b/vendor/magento/module-elasticsea
index e8085787..d7fb9e7e 100644
--- a/vendor/magento/module-elasticsearch/SearchAdapter/Query/Builder/Sort.php
+++ b/vendor/magento/module-elasticsearch/SearchAdapter/Query/Builder/Sort.php
@@ -21,6 +21,7 @@ class Sort
      * List of fields that need to skipp by default.
      */
     private const DEFAULT_SKIPPED_FIELDS = [
+        null,
         'entity_id',
     ];
```

**Comment by Alexander-Pop** [comment] 2020-05-29 18:54
same error still appears in 2.3.5 magento/magento-cloud-metapackage. Above patch fixes it

**Comment by artis-ozolins** [comment] 2020-10-13 16:12
To me it seems that the problem is coming from \Magento\Framework\Api\Search\SearchCriteriaBuilder::create method.
```php
    /**
     * Builds the SearchCriteria Data Object
     *
     * @return SearchCriteria
     */
    public function create()
    {
        foreach ($this->filters as $filter) {
            $this->data[SearchCriteria::FILTER_GROUPS][] = $this->filterGroupBuilder->setFilters([])
                ->addFilter($filter)
                ->create();
        }
        $this->data[SearchCriteria::SORT_ORDERS] = [$this->sortOrderBuilder->create()];
        return parent::create();
    }
```

Here the search criteria builder by default for no reason adds an empty sort order that doesn't have field and direction value.
Removing this line that creates the empty sort order seem to work.

```php
$this->data[SearchCriteria::SORT_ORDERS] = [$this->sortOrderBuilder->create()];
```
If anyone can point out on why there should be an empty sort order created here that would be good to know. At the moment I don't see any reason.

**Comment by danielpugh** [comment] 2020-10-17 17:58
still applies in 2.3.6

**Comment by ronak2ram** [comment] 2020-12-21 11:08
etc/di.xml

```
<type name="Magento\Elasticsearch\SearchAdapter\Query\Builder\Sort">
    <arguments>
        <argument name="skippedFields" xsi:type="array">
            <item name="null" xsi:type="string"></item>
        </argument>
    </arguments>
</type>
```

**Comment by dverkade** [comment] 2021-03-17 15:33
Ready for confirmation issues can't be closed automatically.

**Comment by engcom-Bravo** [comment] 2021-06-24 09:49
Hi @dtavieres ,

Please let me know if you are still facing this issue.

**Comment by engcom-Hotel** [comment] 2021-07-08 08:05
Hi @dtavieres,

We are unable to hear from you since 14 days, so we are closing this issue. If you still facing the issue, then you can reopen this ticket or create a new ticket.

Thanks

**Closed as completed by engcom-Hotel** 2021-07-08 08:05 UTC
Labels: Issue: needs update, Reported on 2.3.4

**Comment by mischabraam** [comment] 2021-07-13 13:38
This bug is still present in 2.4.2-p1 and occurs with Elasticsearch7 (default config) and PHP7.4

**Comment by xtremevision** [comment] 2021-09-19 00:36
> Here's I used to fix this issue on Magento 2.4.0:
> 
> etc/di.xml
> 
> ```
> <type name="Magento\Elasticsearch\SearchAdapter\Query\Builder\Sort">
>     <arguments>
>         <argument name="skippedFields" xsi:type="array">
>             <item name="null" xsi:type="string"></item>
>         </argument>
>     </arguments>
> </type>
> ```

Can you specify the path to etc/di.xml? Thanks.

**Comment by HarishSTOnline** [comment] 2021-09-19 13:18
@xtremevision I think you can create a module and place the config in its di.xml. It will override the arguments in Magento\Elasticsearch\SearchAdapter\Query\Builder\Sort class.

**Comment by aadmathijssen** [comment] 2022-06-10 12:48
Just confirmed that bug is still present in 2.4.4 with the default Elasticsearch7 configuration.

**Comment by engcom-Hotel** [comment] 2022-06-13 07:28
Hello @aadmathijssen,

Please help us with the reproduction steps of this issue.

Thanks
