### ISSUE TITLE
Can't create customer account!! [Compatibility issue with PHP 8.1 and Magento 2.4.4??]

### ISSUE THREAD

**Issue by ghost** [magento/magento2#35985] opened 2022-08-19 16:55 UTC
### Preconditions and environment

- Magento 2.4.4 Open Source
- PHP 8.1.9
- Composer 2.1.0

### Steps to reproduce

1. Upgraded PHP version 7.4.3 to 8.1.9
2. Enabled PHP 8.1.9
3. Disabled PHP 7.4.3
4. Enter to [https:///www.xxxxx.com](url)
5. Enter to `Create an account`
6. [https://www.xxxxx.com/customer/account/create/](url) shows the Error.

### Expected result

Enter customer create page successfully.

### Actual result

1 exception(s):
Exception #0 (Exception): Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/vendor/magento/module-customer/Block/Widget/Name.php on line 110

Exception #0 (Exception): Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/vendor/magento/module-customer/Block/Widget/Name.php on line 110
<pre>#1 trim() called at [vendor/magento/module-customer/Block/Widget/Name.php:110]
#2 Magento\Customer\Block\Widget\Name->getPrefixOptions() called at [vendor/magento/module-customer/view/frontend/templates/widget/name.phtml:39]
#3 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:71]
#4 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/View/Element/Template.php:263]
#5 Magento\Framework\View\Element\Template->fetchView() called at [vendor/magento/framework/View/Element/Template.php:293]
#6 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1095]
#7 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1099]
#8 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:660]
#9 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/module-customer/view/frontend/templates/form/register.phtml:40]
#10 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:71]
#11 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/View/Element/Template.php:263]
#12 Magento\Framework\View\Element\Template->fetchView() called at [vendor/magento/framework/View/Element/Template.php:293]
#13 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1095]
#14 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1099]
#15 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:660]
#16 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:578]
#17 Magento\Framework\View\Layout->_renderBlock() called at [vendor/magento/framework/View/Layout.php:555]
#18 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#19 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#20 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#21 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#22 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#23 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#24 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#25 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#26 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#27 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#28 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#29 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#30 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#31 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#32 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#33 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#34 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#35 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#36 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#37 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:975]
#38 Magento\Framework\View\Layout->getOutput() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#39 Magento\Framework\View\Layout\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#40 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#41 Magento\Framework\View\Layout\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:41]
#42 Magento\Framework\View\Layout\Interceptor->getOutput() called at [vendor/magento/framework/View/Result/Page.php:260]
#43 Magento\Framework\View\Result\Page->render() called at [vendor/magento/framework/View/Result/Layout.php:171]
#44 Magento\Framework\View\Result\Layout->renderResult() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#45 Magento\Framework\View\Result\Page\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#46 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#47 Magento\Framework\View\Result\Page\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:23]
#48 Magento\Framework\View\Result\Page\Interceptor->renderResult() called at [vendor/magento/framework/App/Http.php:120]
#49 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#50 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
</pre>

### Additional information

I was wondering if editing document can fix this compatibility issue?

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by KrusLeung** [comment] 2022-08-19 17:32
Solution at the moment: [https://github.com/magento/magento2/pull/35442/files](url)

**Comment by KrusLeung** [comment] 2022-08-19 18:04
> [#35542](https://github.com/magento/magento2/pull/35442) #35490 #35985
> 
> Edited `app/code/Magento/Customer/Block/Widget/Name.php` as below:
> 
> From `$prefixOption = $this->getObject()->getPrefix();` to `$prefixOption = $this->getObject()->getPrefix() ?? '';`
> 
> **After submited account creation** Got this on https://www.example.com/customer/account/createpost/
> 
> ```
> ValueError: bcsub(): Argument #1 ($num1) is not well-formed in /var/www/html/vendor/magento/zendframework1/library/Zend/Locale/Math.php:259
> Stack trace:
> #0 /var/www/html/vendor/magento/zendframework1/library/Zend/Locale/Math.php(259): bcsub()
> #1 /var/www/html/vendor/magento/zendframework1/library/Zend/Locale/Format.php(385): Zend_Locale_Math::Sub()
> #2 /var/www/html/vendor/magento/zendframework1/library/Zend/Locale/Format.php(662): Zend_Locale_Format::toNumber()
> #3 /var/www/html/vendor/magento/zendframework1/library/Zend/Filter/NormalizedToLocalized.php(106): Zend_Locale_Format::toFloat()
> #4 /var/www/html/vendor/magento/framework/Data/Form/Filter/Date.php(69): Zend_Filter_NormalizedToLocalized->filter()
> #5 /var/www/html/vendor/magento/module-customer/Model/Metadata/Form/AbstractData.php(197): Magento\Framework\Data\Form\Filter\Date->inputFilter()
> #6 /var/www/html/vendor/magento/module-customer/Model/Metadata/Form/Date.php(20): Magento\Customer\Model\Metadata\Form\AbstractData->_applyInputFilter()
> #7 /var/www/html/vendor/magento/module-customer/Model/Metadata/Form.php(244): Magento\Customer\Model\Metadata\Form\Date->extractValue()
> #8 /var/www/html/generated/code/Magento/Customer/Model/Metadata/Form/Interceptor.php(23): Magento\Customer\Model\Metadata\Form->extractData()
> #9 /var/www/html/vendor/magento/module-customer/Model/CustomerExtractor.php(84): Magento\Customer\Model\Metadata\Form\Interceptor->extractData()
> #10 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Customer\Model\CustomerExtractor->extract()
> #11 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Model\CustomerExtractor\Interceptor->___callParent()
> #12 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Model\CustomerExtractor\Interceptor->Magento\Framework\Interception\{closure}()
> #13 /var/www/html/generated/code/Magento/Customer/Model/CustomerExtractor/Interceptor.php(23): Magento\Customer\Model\CustomerExtractor\Interceptor->___callPlugins()
> #14 /var/www/html/vendor/magento/module-customer/Controller/Account/CreatePost.php(368): Magento\Customer\Model\CustomerExtractor\Interceptor->extract()
> #15 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Customer\Controller\Account\CreatePost->execute()
> #16 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callParent()
> #17 /var/www/html/vendor/magento/module-customer/Controller/Plugin/Account.php(64): Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}()
> #18 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Customer\Controller\Plugin\Account->aroundExecute()
> #19 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}()
> #20 /var/www/html/generated/code/Magento/Customer/Controller/Account/CreatePost/Interceptor.php(23): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callPlugins()
> #21 /var/www/html/vendor/magento/framework/App/Action/Action.php(111): Magento\Customer\Controller\Account\CreatePost\Interceptor->execute()
> #22 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch()
> #23 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callParent()
> #24 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}()
> #25 /var/www/html/generated/code/Magento/Customer/Controller/Account/CreatePost/Interceptor.php(32): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callPlugins()
> #26 /var/www/html/vendor/magento/framework/App/FrontController.php(245): Magento\Customer\Controller\Account\CreatePost\Interceptor->dispatch()
> #27 /var/www/html/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
> #28 /var/www/html/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
> #29 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
> #30 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
> #31 /var/www/html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
> #32 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
> #33 /var/www/html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(75): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
> #34 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch()
> #35 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
> #36 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
> #37 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
> #38 /var/www/html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
> #39 /var/www/html/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
> #40 {main}
> ```

This seems to be an issue with me not running  `bin/magento set:upgrade` or `bin/magento setup:static-content:deploy -f` or `bin/magento s:d:c` only

**Comment by engcom-Dash** [comment] 2022-08-22 06:27
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-08-22 10:38
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-08-22 12:28
Hi @KrusLeung ,

We are trying to reproduce the issue in 2.4-develop But we are not able to reproduce the issue...

Customer account able to create successfully...

Here i Attached the screenshots for your reference....
![Screenshot from 2022-08-22 17-52-29](https://user-images.githubusercontent.com/60198592/185920797-85b11604-b381-4dd3-b8e2-031d94325daa.png)
![Screenshot from 2022-08-22 17-52-24](https://user-images.githubusercontent.com/60198592/185920813-50ba1b9d-5e28-411e-a353-7b4980a9fc45.png)

Steps to reproduce the issue:
1. Install Magento Instance
2. Create the Account in Customer view Page
3. Account was Successfully created.

Let us know if we are miss anything....

Thanks!!!

**Comment by KrusLeung** [comment] 2022-08-23 05:47
> reproduce the issue

To reproduce the issue, 
![螢幕快照 2022-08-23 下午1 44 47](https://user-images.githubusercontent.com/110151530/186079584-4bb04d0a-4eed-491a-8ef8-885c740edd36.png)
you have to revise back this modification

1. Edit /var/www/html/app/code/Magento/Customer/Block/Widget/Name.php as below:

From `$prefixOption = $this->getObject()->getPrefix() ?? '';` to `$prefixOption = $this->getObject()->getPrefix();`

@engcom-Dash

**Comment by engcom-Dash** [comment] 2022-08-26 08:28
Hi @KrusLeung ,

We are not able reproduce the issue in 2.4-develop...we  are not have revise back anything in modification...Please check the below link for your reference:

https://github.com/magento/magento2/blob/e235082a74c86dcbe30a89752e43af605510bdaf/app/code/Magento/Customer/Block/Widget/Name.php#L167

Can you tell me upgraded version ??? Its very useful to proceed further in this case.

Thanks!!!

**Comment by KrusLeung** [comment] 2022-08-27 06:08
My Magento Version is 2.4.4 @engcom-Dash

**Comment by engcom-Dash** [comment] 2022-08-29 09:57
Hi @KrusLeung ,

We are trying to reproduce the issue....we are not able to reproduce.Customer account page also able to create successfully.
As per your comments we are checked in 2.4-develop we need not to revise back anything.please upgrade your magento version and install new magento instance...Thanks!!!

**Comment by engcom-Dash** [comment] 2022-09-12 09:16
Hi @KrusLeung ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks!!!

**Closed as completed by engcom-Dash** 2022-09-12 09:16 UTC
Labels: Issue: needs update

**Comment by pmonosolo** [comment] 2022-11-14 20:49
I was testing a size with OWASP ZAP and got the same issue with one of the requests:

The POST content was:

form_key=QaxoFpREuXOnJBHd&success_url=&error_url=&firstname=ZAP&lastname=ZAP&is_subscribed=1&dob=ZAP&assistance_allowed_checkbox=1&assistance_allowed=&email=foo-bar%40example.com&password=ZAP&password_confirmation=ZAP&persistent_remember_me=on

ERROR

ValueError: bcsub(): Argument #1 ($num1) is not well-formed in /var/www/php/sitename/vendor/magento/zendframework1/library/Zend/Locale/Math.php:259
Stack trace:
#0 /var/www/php/sitename/vendor/magento/zendframework1/library/Zend/Locale/Math.php(259): bcsub('ZAP', 'ZAP', 0)
#1 /var/www/php/sitename/vendor/magento/zendframework1/library/Zend/Locale/Format.php(385): Zend_Locale_Math::Sub('ZAP', 'ZAP', 0)
#2 /var/www/php/sitename/vendor/magento/zendframework1/library/Zend/Locale/Format.php(662): Zend_Locale_Format::toNumber('ZAP', Array)
#3 /var/www/php/sitename/vendor/magento/zendframework1/library/Zend/Filter/NormalizedToLocalized.php(106): Zend_Locale_Format::toFloat('ZAP', Array)
#4 /var/www/php/sitename/vendor/magento/framework/Data/Form/Filter/Date.php(69): Zend_Filter_NormalizedToLocalized->filter('ZAP')
#5 /var/www/php/sitename/vendor/magento/module-customer/Model/Metadata/Form/AbstractData.php(197): Magento\Framework\Data\Form\Filter\Date->inputFilter('ZAP')
#6 /var/www/php/sitename/vendor/magento/module-customer/Model/Metadata/Form/Date.php(20): Magento\Customer\Model\Metadata\Form\AbstractData->_applyInputFilter('ZAP')
#7 /var/www/php/sitename/vendor/magento/module-customer/Model/Metadata/Form.php(244): Magento\Customer\Model\Metadata\Form\Date->extractValue(Object(Magento\Framework\App\Request\Http))
#8 /var/www/php/sitename/generated/code/Magento/Customer/Model/Metadata/Form/Interceptor.php(23): Magento\Customer\Model\Metadata\Form->extractData(Object(Magento\Framework\App\Request\Http), NULL, true)
#9 /var/www/php/sitename/vendor/magento/module-customer/Model/CustomerExtractor.php(84): Magento\Customer\Model\Metadata\Form\Interceptor->extractData(Object(Magento\Framework\App\Request\Http))
#10 /var/www/php/sitename/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Customer\Model\CustomerExtractor->extract('customer_accoun...', Object(Magento\Framework\App\Request\Http))
#11 /var/www/php/sitename/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Model\CustomerExtractor\Interceptor->___callParent('extract', Array)
#12 /var/www/php/sitename/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Model\CustomerExtractor\Interceptor->Magento\Framework\Interception\{closure}('customer_accoun...', Object(Magento\Framework\App\Request\Http))
#13 /var/www/php/sitename/generated/code/Magento/Customer/Model/CustomerExtractor/Interceptor.php(23): Magento\Customer\Model\CustomerExtractor\Interceptor->___callPlugins('extract', Array, Array)
#14 /var/www/php/sitename/vendor/magento/module-customer/Controller/Account/CreatePost.php(368): Magento\Customer\Model\CustomerExtractor\Interceptor->extract('customer_accoun...', Object(Magento\Framework\App\Request\Http))
#15 /var/www/php/sitename/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Customer\Controller\Account\CreatePost->execute()
#16 /var/www/php/sitename/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callParent('execute', Array)
#17 /var/www/php/sitename/vendor/magento/module-customer/Controller/Plugin/Account.php(64): Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}()
#18 /var/www/php/sitename/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Customer\Controller\Plugin\Account->aroundExecute(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure))
#19 /var/www/php/sitename/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}()
#20 /var/www/php/sitename/generated/code/Magento/Customer/Controller/Account/CreatePost/Interceptor.php(23): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callPlugins('execute', Array, Array)
#21 /var/www/php/sitename/vendor/magento/framework/App/Action/Action.php(111): Magento\Customer\Controller\Account\CreatePost\Interceptor->execute()
#22 /var/www/php/sitename/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /var/www/php/sitename/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callParent('dispatch', Array)
#24 /var/www/php/sitename/vendor/vendor/sitename/General/Plugin/App/Action/Context.php(49): Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#25 /var/www/php/sitename/vendor/magento/framework/Interception/Interceptor.php(135): vendor\General\Plugin\App\Action\Context->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 /var/www/php/sitename/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#27 /var/www/php/sitename/generated/code/Magento/Customer/Controller/Account/CreatePost/Interceptor.php(32): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callPlugins('dispatch', Array, NULL)
#28 /var/www/php/sitename/vendor/magento/framework/App/FrontController.php(245): Magento\Customer\Controller\Account\CreatePost\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#29 /var/www/php/sitename/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Magento\Framework\App\Request\Http))
#30 /var/www/php/sitename/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\Customer\Controller\Account\CreatePost\Interceptor))
#31 /var/www/php/sitename/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#32 /var/www/php/sitename/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#33 /var/www/php/sitename/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#34 /var/www/php/sitename/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /var/www/php/sitename/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(75): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#36 /var/www/php/sitename/vendor/magento/framework/Interception/Interceptor.php(58): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#37 /var/www/php/sitename/vendor/magento/framework/Interception/Interceptor.php(138): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->___callParent('aroundDispatch', Array)
#38 /var/www/php/sitename/vendor/magento/framework/Interception/Interceptor.php(153): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#39 /var/www/php/sitename/generated/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin/Interceptor.php(23): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->___callPlugins('aroundDispatch', Array, Array)
#40 /var/www/php/sitename/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#41 /var/www/php/sitename/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#42 /var/www/php/sitename/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#43 /var/www/php/sitename/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#44 /var/www/php/sitename/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#45 /var/www/php/sitename/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#46 {main}
