### ISSUE TITLE
magento is able to save a product twice with the same sku via the repository

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#24799] opened 2019-09-30 21:02 UTC
### Preconditions (*)
1. Magento 2.3.1 
2. An application which creates a product programmatically
For example in my app we constantly check for a product by an attribute and if it exists update it but if it doesn't exist in the website we create it programmatically.

Occassionally I've seen duplicate products emerging from the programmatic saving using the product repository. However the user is not able to save the product as duplicate because the SKU attribute is unique. 

The API and Repository class should enforce this no matter the reason and throw an exception if you try to create the product with the same SKU that already exists. 

### Steps to reproduce (*)

My code is fairly simple in this case. 

   ```
    /**
      * @param $magentoProduct ProductInterface
      * @param $erpProduct
      * @return bool
      */
     private function createProduct($erpProduct)
     {
         $this->logger->notice(sprintf('creating product with data from erpproduct %s', json_encode($erpProduct)));
         $slugger = new Slugify();
         $magentoProduct = $this->productFactory->create();
         foreach ($this->createMap as $index => $field) {
             $attributeCode = $field->attribute_option;
             $erpField = $field->erp_field_option;
             if (in_array($erpField, $skip)) {
                 continue;
             }

             if (!empty($erpProduct[0][$erpField])) {
                 $magentoProduct->setData($attributeCode, $erpProduct[0][$erpField]);
             }
         }
         //update discounted prices
//            $magentoProduct->setPrice((float)$erpProduct[0][AbstracterpProduct::price_original]);
         if (empty($erpProduct[0][AbstracterpProduct::v6]) || ($erpProduct[0][AbstracterpProduct::v6] >= $erpProduct[0][AbstracterpProduct::price])) {
             $magentoProduct->setData('special_price', null);
             $magentoProduct->setData('special_price_from', null);
             $magentoProduct->setData('special_price_to', null);
         }


         $magentoProduct->setData('sku', $erpProduct[0][AbstracterpProduct::code]);
         $magentoProduct->setVisibility(Product\Visibility::VISIBILITY_NOT_VISIBLE);
         $url = $slugger->slugify($erpProduct[0][AbstracterpProduct::name] . $erpProduct[0][AbstracterpProduct::mtrl]);
         $magentoProduct->setData('url_key', $url);

         try {
             $date = new \DateTime('now');
             $timestamp = $date->setTimezone(new \DateTimeZone('UTC'))
                 ->format('Y-m-d H:i:s')
             ;;
             $magentoProduct->setData(ProductHelper::ATTRIBUTE_TS_DETAILS, $timestamp);
             $magentoProduct->setAttributeSetId($this->productModel->getDefaultAttributeSetId());
             $magentoProduct->setTypeId('simple');
             $magentoProduct->setWeight(0.1);
             $magentoProduct->setData(ProductHelper::ATTRIBUTE_TS_CREATE, $date->format('Y-m-d H:i:s'));
//                $magentoProduct->save();
             $this->productRepository->save($magentoProduct);
             return true;
         } catch (\Exception $exception) {
             $this->logger->error($exception->getMessage());
             return false;
         }
     }
```

### Expected result (*)
1. The product is saved once and the save action throws an exception if the sku already is taken by another product

### Actual result (*)
1. The product was saved correctly as a duplicate product

**Comment by engcom-Charlie** [comment] 2019-10-03 14:23
Hello @ioweb-gr 
I can't reproduce this issue on a fresh Magento 2.3-develop.
I used my code for testing because i can't use your code.
![image](https://user-images.githubusercontent.com/51680850/66126517-4ab91280-e5f2-11e9-81a0-2383881681f9.png)

**Result:** After running the code twice i had only one product.
If change name of the product magento saves product with changed sku(screenshot attached).
![image](https://user-images.githubusercontent.com/51680850/66127060-8d2f1f00-e5f3-11e9-9218-ea2d29a481a8.png)

So i have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-10-03 14:23 UTC
Labels: Issue: Format is valid

**Comment by ioweb-gr** [comment] 2019-10-03 14:26
I see, 
do you have any idea what possible situation could cause a duplicate product to be saved in the database with the same SKU value then?
It's the third case in 3 months we've faced this during saving products via the repository and we're really puzzled by this. 
 I would like ideas on what to test so we can replicate it. Because it definitely happens due to some reason.

**Comment by ioweb-gr** [comment] 2019-10-16 17:21
I'm just facing this situation again and I would like to dig deeper to how it can happen. Can someone offer insight to this?

My end result is this 
![image](https://user-images.githubusercontent.com/20220341/66942753-68569500-f052-11e9-8906-7d6539cb87b2.png)

You will see that unlike the scenario described above the products have identical sku. It seems as if there's a double write on the database from the same action when the product model is saved.

**Comment by manaftryzens** [comment] 2020-09-28 12:48
We are also having the same issue.

**Comment by ioweb-gr** [comment] 2020-09-29 08:50
@manaftryzens It seems like a race condition in Magento core that's causing this. I was able to circumvent this issue by tripple checking whether the product exists before saving with a small delay between checks but I wasn't able to find the root cause. I of course slowed down the sync speed like this but I wasn't able to stop this from happening any other way.

**Comment by manaftryzens** [comment] 2020-09-29 08:59
@ioweb-gr , thanks for the respone. So when you slowed down the sync speed, did it resolve your issue? If that is the case we can also do the same as there are no other ways...

**Comment by ioweb-gr** [comment] 2020-09-29 09:21
So far I've had no reoccurence.

**Comment by manaftryzens** [comment] 2020-09-29 09:33
Hi @ioweb-gr , what was the sync speed when you faced the issue and to where you had reduced it to resolve the issue?

**Comment by adarshkhatri** [comment] 2023-03-01 03:11
I am facing this too. The problem is don't know how to reproduce. It just happens to be the same product twice in the catalog grid. 

I am using the `product repository save` function too.


And the issue is, even though I have checked in place to check if the SKU already exists, it is still creating multiple products with the same SKU. 

I had hoped we have unique constraint in the `catalog_product_entity` table for SKU column, but no, we don't.

**Comment by ioweb-gr** [comment] 2023-03-01 06:37
@adarshkhatri Actually I've had some similar cases lately with other entities. There seems to be a delay when actually committing the save to the database so when you save an entity in your code like we do in a loop and follow up with a new check if the element exists almost instantly after the save there's high chance that the check won't find the item that's persisted slightly later. But the fact that there is a unique constraint on the sku in application level but not in database level in my opinion should be fixed.

I actually added the unique constraint to my system via a module just for this in some cases

**Comment by charvi-parikh** [comment] 2023-04-28 12:19
Hello @engcom-Charlie  

If we run API twice then from where sku is updated and new product created.

**Comment by ioweb-gr** [comment] 2025-11-01 11:00
It's good to have the constraint, we actually did so ourselves, however on the application level regarding BC, the save action should throw an AlreadyExists exception instead of a generic constraint failure so that each module can handle the exception gracefully.
