### ISSUE TITLE
Magento 2.4.2 composer upgrade broke after 2.4.3 released

### ISSUE THREAD

**Issue by EliminatorRC-Christian** [magento/magento2#33760] opened 2021-08-11 21:23 UTC
I am currently in the process of upgrading Magento 2.2.6 to 2.4.2. I had a stable upgrade working prior to 2.4.3 being released. After Tuesday, August 10 when 2.4.3 was released, when I composer upgrade our installation with:

`composer require magento/product-community-edition 2.4.2 --no-update`
`composer require --dev phpunit/phpunit:^9 friendsofphp/php-cs-fixer:~2.16.0 lusitanian/oauth:~0.8.10 pdepend/pdepend:~2.7.1 sebastian/phpcpd:~5.0.0 squizlabs/php_codesniffer:3.5.4 --no-update`
`composer remove --dev sjparkinson/static-review fabpot/php-cs-fixer --no-update`
`composer require msp/recaptcha 2.2.2 --no-update`
`composer require picqer/php-barcode-generator --no-update`
`composer update`

I then enabled MSI modules. During `bin/magento inventory:reservation:list-inconsistencies -r | bin/magento inventory:reservation:create-compensations` I had problems where each inconsistency would throw an error saying 'caused exception "Area code is not set"'. I fixed this problem by manually setting the state in `vendor/magento/module-inventory-reservation-cli/Command/CreateCompensations.php`. I did not have to do this workaround prior to Tuesday.

After fixing this bug it appears my paid extensions (which hasn't been upgraded yet) now have errors.
There may be more bugs but I currently can't browse the storefront due to these errors.

Was the repository for 2.4.2 updated with the release of 2.4.3? I went from having a stable upgrade to an upgrade full of errors and the only thing that has changed is the new version of Magento releasing.

**Comment by davidandersson1** [comment] 2021-08-12 08:42
After finished, composer update of 2.4.3, I am facing same error "Area code is not set" with command "setup:upgrade". 

Also klarna checkout installation (through command: composer require klarna/m2-checkout) not working with 2.4.3 and its throw Conclusion: don't install klarna/m2-checkout 9.2.4|install ramsey/uuid 3.9.4

Please help if any body faced same issue and got any solution for same!

**Comment by hostep** [comment] 2021-08-12 09:49
@davidandersson1: you should report that problem to Klarna, Magento increased the dependency on `ramsey/uuid` from v3 to v4 and probably that Klarna module only supports v3 at the moment.

**Comment by davidandersson1** [comment] 2021-08-12 09:56
@hostep thanks for you quick reponse, we already reported to klarna for same. is there any update regarding one more issue related "Area code is not set" with command "setup:upgrade"?

**Comment by hostep** [comment] 2021-08-12 10:05
There is a PR that fixes one such issue: https://github.com/magento/magento2/pull/33726, but I'm not sure if that is the same as your issue.
Would be great if you could try to debug somehow and figure out what sets the area in your specific case (probably in some constructor of some class that is called by a magento command somewhere)

**Comment by davidandersson1** [comment] 2021-08-20 07:06
Hi @hostep its same issue(app/code/Magento/Payment/Helper/Data.php) for us, so is there any patch to resolve the bug or how?

**Comment by engcom-Delta** [comment] 2021-08-23 12:44
Hi @EliminatorRC-Christian,

Hope this issue is resolved , if not , kindly provide issue description , steps to reproduce and expected results.

Thanks

**Comment by pmonosolo** [comment] 2021-08-24 16:18
Maybe EDIT HTML should be next to EDIT WITH PAGE BUILDER? This is so you dont have to click through 2-3 times just to get to EDIT WITH HTML flow every time?

![image](https://user-images.githubusercontent.com/66754347/130652621-12efeff8-ea6d-4723-8532-89a63cbe6e31.png)

**Comment by engcom-Delta** [comment] 2021-09-09 09:58
Looks like patch is working fine . We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Comment by davidandersson1** [comment] 2021-10-13 11:57
> @davidandersson1: you should report that problem to Klarna, Magento increased the dependency on `ramsey/uuid` from v3 to v4 in Magento 2.4.3 and probably that Klarna module only supports v3 at the moment.

Hi @ihor-sviziev 

Klarna have upgraded their module with latest version 9.3.0 and "ramsey/uuid" issue resolved with it but new issue borned with core magento module "Klarna_Kp" + Magento version 2.4.3 is at Admin->Sales-> Orders grid and error is

i.e
{"0":"Payment model name is not provided in config!","1":"#1 Magento\\Payment\\Helper\\Data\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#2 Magento\\Payment\\Helper\\Data\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/klarna\/module-kp\/Plugin\/Payment\/Helper\/DataPlugin.php:223]
![Screenshot from 2021-10-12 16-09-01](https://user-images.githubusercontent.com/49389320/137127832-23463427-0d77-4a4d-b505-c01d55903730.png)

It would be really good if you will help us here to sort out the issue!

Thanks,
David Andersson

**Comment by engcom-Alfa** [comment] 2021-10-13 14:09
1. Create a custom command (We need to use the _Payment/Helper/Data_ class in the constructor of the _Index.php_ file.)
2. We don't have to set the area code in the execute function.
3. When we try to access any Magento command, we get the error message saying - "area code not set"
Below is the Index.php class code snippet

`<?php
namespace Globallogic\Custom\Console;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Magento\Payment\Helper\Data;

class Custom extends Command
{
    public function __construct(Data $data, string $name = null)
    {
        $this->data = $data;
        parent::__construct($name);
    }

    protected function configure()
    {
        $this->setName('custom:command');
        $this->setDescription('Demo command line');

        parent::configure();
    }
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $output->writeln("Hello World");
    }
}`


Below is the error screenshot.

![image](https://user-images.githubusercontent.com/51679138/137149687-d643b037-0667-4745-bb74-ea85d1166617.png)

Hence re-opening the issue

**Closed as completed** 2021-10-28 02:09 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P2, Severity: S1, Progress: done, Reported on 2.4.2, Area: Framework
