### ISSUE TITLE
Magento2 search criteria does not show correctly for "yes/no" attribute in advanced search result page

### ISSUE THREAD

**Issue by wenpingguo** [magento/magento2#7478] opened 2016-11-17 23:50 UTC
### Preconditions

1.  Default Magento 2.1.2

### Steps to reproduce

1. Create a "yes/no" product attribute and enable for advanced search. e.g. "Australian Made"
2. Go to advanced search page in front end
3. input "top" for "Product Name" text box
4. click search

### Expected result

1. "Australian Made" should not be showed as it is not selected, or it need to show "Australian Made:All" instead of "Australian Made:no" 

### Actual result

1. It shows "Australian Made:no" in search result page
see video record: http://take.ms/Gqxtr

I believe logic is wrong here in 
vendor/magento/module-catalog-search/Model/Advanced.php line 370-374

`  } elseif ($attribute->getFrontendInput() == 'boolean') {` 
           `  $value = $value == 1` 
                ` ? __('Yes')` 
               `  : __('No');` 
   `  }`

Here should be, 
value=1 ->yes
Value=0 -> no
value=null -> remove from from search criteria

**Comment by xmav** [comment] 2017-01-31 14:31
@wenpingguo Thanks for reporting this issue. 
This issue is already addressed in internal ticket MAGETWO-52846. I’ve added your report on this issue to that ticket.

**Comment by magento-engcom-team** [comment] 2017-10-09 11:30
@wenpingguo, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-09 11:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Search, Issue: Clear Description, Issue: Format is valid
