### ISSUE TITLE
thumbnail images aren't shown anymore after adding a new variation to an existing configurable product

### ISSUE THREAD

**Issue by MarianNapi** [magento/magento2#33271] opened 2021-06-17 09:15 UTC
### Preconditions (*)

1. Magento version 2.4.2
2. PHP 7.4

### Steps to reproduce (*)

1. Create new configurable product
2. add several child products with thumbnail images
3. save the configurable product
4. add a new variation

### Expected result (*)

1. the thumbnail images of the old variations should be shown

### Actual result (*)

1. no thumbnail is shown
2. old image does NOT get replaced after saving, it's only a visual bug

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by MarianNapi** [comment] 2021-06-17 09:37
@magento give me 2.4-develop instance

**Comment by MarianNapi** [comment] 2021-06-17 10:13
Tested on clean instance, bug still occurs

**Comment by oneserv-heuser** [comment] 2021-06-17 11:11
This bugs lead to another problem: We have a custom field in the configurable matrix. This field also gets buggy after adding another child product to a configurable product. Here the result is that all the values for our custom fields (except the values for the new child products) are not sent to the Validation or Save controller. I guess that this problem is somehow linked to this ticket.

**Comment by krishprakash** [comment] 2021-06-18 05:54
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2021-06-18 06:17
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42670` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by SilinMykola** [comment] 2021-06-21 08:37
@magento I am working on this

**Comment by engcom-Bravo** [comment] 2024-07-19 06:47
Hi @MarianNapi,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="1404" alt="Screenshot 2024-07-19 at 12 15 16" src="https://github.com/user-attachments/assets/c95ca6c1-0593-4ddb-ba4c-90ae47ef231f">



the thumbnail images of the old variations is showing for the products.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-19 06:47 UTC
Labels: Issue: Confirmed, Component: ConfigurableProduct, Reproduced on 2.4.x, Priority: P3, Severity: S3, Progress: done, Issue: ready for confirmation

**Comment by MarianNapi** [comment] 2024-07-19 07:02
@magento  give me 2.4-develop instance
