### ISSUE TITLE
No specialprice showing on Customer Wishlist

### ISSUE THREAD

**Issue by AmannMax** [magento/magento2#11305] opened 2017-10-09 11:01 UTC
### Preconditions

1. Magento 2.1.5 - 2.1.8 and new versions.

### Steps to reproduce

1. Setup special price for any product
2. Add this product to wishlist
3. go to wishlist section

### Expected result

1. It should display the special price.
### Actual result

1. Normalprice is shown.

![wishlist](https://user-images.githubusercontent.com/29060188/31335213-e07ceeea-acf1-11e7-8c52-0a593ed08801.PNG)

**Comment by magento-engcom-team** [comment] 2017-10-09 13:30
@AmannMax, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-09 13:30 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by duckchip** [comment] 2017-10-13 13:11
@magento-engcom-team could you provide the PR, or issue where this is fixed?

**Comment by CNanninga** [comment] 2017-11-02 20:59
@magento-engcom-team - Any word?  Those of us still on 2.1 still need a patch for this.
