### ISSUE TITLE
When single-store modus is activated a new created page returns can not be found (404)

### ISSUE THREAD

**Issue by joenivl** [magento/magento2#7918] opened 2016-12-21 19:27 UTC
When activating the single-store modus and creating a page this page can not be found (404). After disabling the single store modus and saving the page the page is found.

### Preconditions
Magento version 2.1.3

### Steps to reproduce
Activatie single-store modus
Create a new page
Try to reach the page in the frontend
See a 404 error

Disable the single-store modus
Save the page again
The page is now available in the frontend.

### Expected result
When creating a page in single-store modus the page should be available.

### Actual result
The page is not available.

**Comment by Cacasapo** [comment] 2016-12-21 21:02
Yeah, this is a known bug from 2.1.1 that keeps getting passed forward.

**Comment by joenivl** [comment] 2016-12-22 06:00
@Cacasapo thanks, I could not find any issue related to this problem. Do you perhaps know this issue so I can mark my issue as duplicate.

**Comment by Cacasapo** [comment] 2016-12-22 11:50
@joenivl I was incorrect when I said 2.1.1, it's actually from 2.1.0.
https://github.com/magento/magento2/issues/5923

**Comment by veloraven** [comment] 2016-12-26 15:19
@joenivl  I'm closing this issue as a duplicate of #5923.
We have internal ticket MAGETWO-58383 to fix this issue in 2.1 branch.
@Cacasapo thank you for help and pointing at corresponding issue.

**Closed as completed by veloraven** 2016-12-26 15:19 UTC
Labels: bug report

**Comment by joenivl** [comment] 2016-12-28 08:37
@veloraven thanks! Sorry for duplicating!!
