### ISSUE TITLE
Add product customization option collapsible design issue

### ISSUE THREAD

**Issue by SyntaxKay** [magento/magento2#19399] opened 2018-11-24 16:05 UTC
### Preconditions (*)

1.Magento 2.2-develop 

### Steps to reproduce (*)

1.Go to -> Catalog Product -> add product from backend 
2.Go to -> customization option

### Expected result (*)

![expected1](https://user-images.githubusercontent.com/33230237/48970286-9ee98280-f030-11e8-88f8-25c989cca0dd.jpg)

### Actual result (*)

![actual-1](https://user-images.githubusercontent.com/33230237/48970297-b32d7f80-f030-11e8-95e4-c5261113eb87.jpg)

**Comment by magento-engcom-team** [comment] 2018-11-24 16:05
Hi @speedy008. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@speedy008 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by rogyar** [comment] 2018-11-26 08:01
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2018-11-26 08:01
Hi @rogyar. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2018-11-26 08:02
Hi @rogyar, here is your [Magento instance](https://i-19399-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-19399-2-2-develop.instances.magento-community.engineering/admin](https://i-19399-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2018-12-07 16:16
Hi @speedy008. Thank you for your report. 
The issue has been fixed in magento/magento2#19405 by @speedy008 in 2.3-develop branch
Related commit(s):
 - [c4294625e6c2da06468a349a45fe41cf265c7def](https://github.com/magento/magento2/commit/c4294625e6c2da06468a349a45fe41cf265c7def)
 - [7ef0c2c827588867d76ae3b981d9ae578303b105](https://github.com/magento/magento2/commit/7ef0c2c827588867d76ae3b981d9ae578303b105)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2018-12-07 16:16 UTC
Labels: Issue: Ready for Work, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Backend

**Comment by magento-engcom-team** [comment] 2019-01-23 00:00
Hi @speedy008. Thank you for your report. 
The issue has been fixed in magento/magento2#19400 by @speedy008 in 2.2-develop branch
Related commit(s):
 - [731fd07205839e554d4f84cf6154a9224b7c338d](https://github.com/magento/magento2/commit/731fd07205839e554d4f84cf6154a9224b7c338d)

The fix will be available with the upcoming 2.2.8 release.
