### ISSUE TITLE
Multiple and inaccurate backorder messages in admin

### ISSUE THREAD

**Issue by CNanninga** [magento/magento2#29311] opened 2020-07-28 17:27 UTC
A quirk of inventory quantity validation means that when creating an order for a backordered product in the admin, multiple backorder messages are shown, with incorrect quantities for one such message.

### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Create a simple product with: A) A current inventory quantity of 0, B) Stock Status set to "In Stock," and C) Backorders set to "Allow Qty Below 0 and Notify Customer."
2. Create a new order in the admin.
3. On the order creation screen, "Add Product" and choose the product created in step 1.  Click "Add Selected Product to Order" with Qty 1.

### Expected result (*)

1. The following message will be displayed: "We don't have as many quantity as you requested, but we'll back order the remaining 1."

### Actual result (*)

1. Two messages are displayed: A) "We don't have as many quantity as you requested, but we'll back order the remaining 1." and B) "We don't have as many quantity as you requested, but we'll back order the remaining 2."

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

---
### Cause

The root of the cause is `\Magento\CatalogInventory\Model\Quote\Item\QuantityValidator\QuoteItemQtyList::getQty`.  

Any time `setQty` is called on a Quote Item, a series of observers and plugins ultimately leads to the above method being called in order to determine what quantity should be checked.  The internals of the method use a caching mechanism to track which Quote Item IDs have already been checked for the same product, and the intention seems to be to accumulate qty from multiple Quote Items for the same product, so that the full qty for the entire quote/cart is checked.  But this is accumulated by the ID of the Quote Items, and if `setQty` is called before the Quote Item is saved (and there is no ID), then again _after_ an ID is assigned, the first call to this method results in a NULL value being cached as the Quote Item ID, and then subsequent calls with a real ID end up adding the two quantities together.  In the admin order creation process, natively, there are multiple such calls to `setQty` before and after a Quote Item ID is assigned.  (`\Magento\AdvancedCheckout\Model\Cart::addProduct` results in multiple calls to `setQty`, and `\Magento\Sales\Block\Adminhtml\Order\Create\Items\Grid::getItems` calls it again after the Quote Item has an ID.)

It is worth noting that the "accumulation" logic doesn't seem to result in the correct backorder messaging even in the circumstances it was designed for, because of the sequential nature of the check.  To demonstrate this:

1. Similar to instructions above, create a simple product with 0 qty that allows backorders, but also create a custom option with at least two possible values.
2. Front-end:  Place two of the same product in the cart, but with different custom option values, which will result in separate cart line items.  The first has the backorder message "we'll back order the remaining 1," and the second has the message "we'll back order the remaining 2."
3. Admin:  Create an order with two of the same product but different custom option values.  The first has the backorder message "we'll back order the remaining 1," while the second again has _two_ backorder messages, one mentioning qty 1 and one mentioning qty 2.

**Comment by CNanninga** [comment] 2020-07-28 17:30
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-07-28 17:30
Hi @CNanninga. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-07-28 17:32
Hi @CNanninga, here is your [Magento instance](https://i-29311-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29311-2-4-develop.instances.magento-community.engineering/admin_7a4f](https://i-29311-2-4-develop.instances.magento-community.engineering/admin_7a4f)
Login: `c078af48` Password: `108f190ab787`
Instance will be terminated in up to 3 hours.

**Comment by CNanninga** [comment] 2020-07-28 17:42
@magento give me 2.3.5 instance

@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment] 2020-07-28 17:42
Hi @CNanninga. Thank you for your request. I'm working on Magento 2.3.5 instance for you

**Comment by magento-engcom-team** [comment] 2020-07-28 17:43
Hi @CNanninga, here is your [Magento instance](https://i-29311-2-3-5.instances.magento-community.engineering).
Admin access: [https://i-29311-2-3-5.instances.magento-community.engineering/admin_da77](https://i-29311-2-3-5.instances.magento-community.engineering/admin_da77)
Login: `3af7a1a0` Password: `5254d2b27784`
Instance will be terminated in up to 3 hours.

**Comment by CNanninga** [comment] 2020-07-28 17:47
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment] 2020-07-28 17:48
Hi @CNanninga. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment] 2020-07-28 17:49
Hi @CNanninga, here is your [Magento instance](https://i-29311-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-29311-2-3-4.instances.magento-community.engineering/admin_cd39](https://i-29311-2-3-4.instances.magento-community.engineering/admin_cd39)
Login: `8ad85371` Password: `cd533abaa00d`
Instance will be terminated in up to 3 hours.

**Comment by CNanninga** [comment] 2020-07-28 18:00
I was not able to reproduce this on the provided instance, even on 2.3.4, which is the version I first observed it on.

My local installation, while a completely vanilla install, I just realized happens to be an install of Commerce edition, not Open Source.  I can only conclude that a Commerce-only module is involved with the unique calls to `setQty` that manifest this issue.

This leaves me conflicted about how to proceed:

1. It should be safe to call `setQty` any number of times before or after the Quote Item is saved, and I suspect that this is still an issue in the Open Source core code, just not one that manifests with the particular order of execution in play.  Should I look into adding a custom `setQty` call as part of the reproduction steps in Open Source?
2. What is the best path forward for reporting this bug in Commerce edition?  (Particularly since I don't know which specific Commerce module is related.)

**Comment by CNanninga** [comment] 2020-07-28 18:57
Turns out I _can_ reproduce this on a local vanilla instance of 2.3.4 Open Source.

**Comment by gwharton** [comment] 2020-08-04 09:03
https://github.com/magento/magento2/issues/24191
https://github.com/magento/magento2/issues/24203

**Comment by engcom-Oscar** [comment] 2020-09-29 09:38
Hello @CNanninga 

Thank you for your report.
Unfortunately, I was not able to reproduce this issue on the latest `2.4-develop` code. Probably it was already fixed and will appear in the next release. Or we missed some steps or preconditions.

Could you please recheck it on clean Magento 2.4 installation and confirm?

**Comment by engcom-Bravo** [comment] 2020-10-28 10:06
Hello @CNanninga 

Thank you for your report

We are not able to reproduce the issue on 2.4-develop.
On the order creation screen, we get only one message 
![One message](https://user-images.githubusercontent.com/51680745/97421880-b1078600-1915-11eb-89ad-c2d0464b5d34.png)

So we are closing this issue. Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by engcom-Bravo** 2020-10-28 10:06 UTC
Labels: Component: SalesInventory, not-confirmed, Reported on 2.3.4
