### ISSUE TITLE
Password forgot send Newsletter E-Mails, if Newsletter confirmation is enabled.

### ISSUE THREAD

**Issue by mad-develop** [magento/magento2#17167] opened 2018-07-26 13:58 UTC
The Password Forgot process seems to send "Newsletter subscription confirmation" with specific settings.

### Preconditions
1. Magento CE 2.2.5
2. PHP 7.1.19-1+ubuntu16.04
3. Enable Newsletter Confirmation (Stores -> Configuration -> Customer -> Newsletter -> Need to Confirm: Yes)
4. Register Account 
5. Activate and confirm "General Subscription" Newsletter, so its active your account.

### Steps to reproduce
1. Fill in Password Forgot Form and send.

### Expected result
1. Only get one Mail with password reset link

### Actual result
1. You get 2 Mails. One with the password reset link and one "Newsletter subscription confirmation" Mail.

### More Information
Investigation so far shows its a problem inside the \Magento\Newsletter\Model\Subscriber::_updateCustomerSubscription Function which is initiated after Customer save.

![grafik](https://user-images.githubusercontent.com/40065929/43309239-85426f1e-9184-11e8-86c5-77ab2c5b9213.png)

$subscribe is true due to updateSubscription function which gets called from the afterSave of customer.

So an unwanted Newsletter Mail gets send in the following process.

**Comment by magento-engcom-team** [comment] 2018-07-26 13:58
Hi @mad-develop. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@mad-develop do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by mad-develop** [comment] 2018-07-27 08:53
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment] 2018-07-27 08:53
Hi @mad-develop. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment] 2018-07-27 08:53
Hi @mad-develop, here is your [Magento instance](https://i-17167-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17167-2-2-5.engcom.dev.magento.com/admin](https://i-17167-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mad-develop** [comment] 2018-07-27 08:57
I confirm that i was able to reproduce the issue on vanilla Magento instance.
![grafik](https://user-images.githubusercontent.com/40065929/43311975-40b470d8-918c-11e8-9989-8787d34ad55c.png)

**Comment by magento-engcom-team** [comment] 2018-10-13 06:42
Hi @rdudhara. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by anujwebkul** [comment] 2018-10-29 10:08
@magento-engcom-team  give me 2.2.6 instance

**Comment by engcom-Alfa** [comment] 2020-01-03 12:52
Hi @mad-develop. Thank you for your reporting.

We are not able to reproduce this issue on the fresh 2.4-develop instance. Everything works correctly.

**Manual testing scenario:**
1. Enable Newsletter Confirmation (Stores -> Configuration -> Customer -> Newsletter -> Need to Confirm: Yes)
2. Register Account
3. Activate and confirm "General Subscription" Newsletter, so it's active your account.
4. Fill in Password Forgot Form and send it.

**Actual Result:**
We've got one Mail with a password reset link

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration

**Closed as completed by engcom-Alfa** 2020-01-03 12:52 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Newsletter
