### ISSUE TITLE
Customer Email with diacritics isn't allowed

### ISSUE THREAD

**Issue by Drakhunter** [magento/magento2#12075] opened 2017-11-07 11:17 UTC
Magento2 doesn't allow E-Mails with diacritics in CURL Requests.
According to [wikipedia](https://en.wikipedia.org/wiki/Email_address#Internationalization) this should be allowed, but Magento is restricting it. 

Is there a Fix or Workaround or something?

### Preconditions
1. Magento Version 2.1.8

### Steps to reproduce
1. get email address with diacritics (pepé@emailtest.com)
2. create json data object with email 
`$data = [
                    'customer' =>
                    [
                        'email' => pepé@emailtest.com
                     ]
]`
3. create user using curl via /index.php/rest/V1/customers

### Expected result
1. User should be created with correct email address

### Actual result
1.` {"message":"\"Email\" ist keine g\u00fcltige E-Mail-Adresse."` (roughly translated: Email isn't a valid E-Mail-Address)

### Additional Notes
Reproduced it via Swagger with using the following query  /swagger#/customerAccountManagementV1/customerAccountManagementV1CreateAccountPost
![swagger_create customer](https://user-images.githubusercontent.com/51680745/72134993-1772e600-338e-11ea-9e72-62fa1b432b6e.png)
The response is : 
```
{
  "message": "\"Email\" is not a valid email address."
}
```
But this is also reproducible if try to create a customer from Magento Admin
![email_from admin](https://user-images.githubusercontent.com/51680745/72135583-86047380-338f-11ea-9754-1f2d122f9a9e.png)

**Comment by magento-engcom-team** [comment] 2017-11-07 12:06
@Drakhunter, thank you for your report.
We've created internal ticket(s) MAGETWO-83378 to track progress on the issue.

**Comment by rparsi-boxycharm** [comment] 2019-07-12 20:16
@magento-engcom-team any updates? We need a fix asap

**Comment by magento-engcom-team** [comment] 2020-01-10 08:14
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30334` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ProkopovVitaliy** [comment] 2020-04-22 18:28
@sdzhepa  Looks like it is not bug this is default behavior. Even more, for this responsible not magento.

There is special class for validation` Zend_Validate_EmailAddress`  his contain function where regular expression prohibits emails with such characters.

![image](https://user-images.githubusercontent.com/29776509/80019292-f74fd880-84df-11ea-94a2-d52730a77534.png)

It is easy to fix but it is not Magento. So i think we can close current issue.

**Comment by rparsi-boxycharm** [comment] 2020-04-22 19:16
@ProkopovVitaliy No, it is Magento because magento core code is using this.  Magento customers such as myself need customer entity email addresses to support special characters like diacritics.
Magento team is responsible for fixing this.

**Comment by konarshankar07** [comment] 2020-10-10 04:54
@magento I'm working on this

**Comment by rparsi-boxycharm** [comment] 2020-10-13 15:28
@konarshankar07 FYI this issue is fixed in upstream zendframework
https://github.com/zendframework/zend-validator/blob/release-2.12.0/src/EmailAddress.php

For my team I created a composer patch that ports the fix to the zendframework 1.x release used within magento.

**Comment by gixid192** [comment] 2021-03-19 07:16
> @konarshankar07 FYI this issue is fixed in upstream zendframework
> https://github.com/zendframework/zend-validator/blob/release-2.12.0/src/EmailAddress.php
> 
> For my team I created a composer patch that ports the fix to the zendframework 1.x release used within magento.

Hi guys, as @konarshankar07 already point out the fix, I think the code should be modified in [magento/zendframework1](https://github.com/magento/zf1) repo

**Comment by Alexander-Khohklov** [comment] 2022-08-24 13:21
@magento I am working on this

**Closed as completed** 2022-12-03 20:20 UTC
Labels: Issue: Ready for Work, Component: Customer, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Component: Email, Reproduced on 2.4.x, Priority: P1, Severity: S1, Progress: done, Area: APIs
