### ISSUE TITLE
addImageToMediaGallery throws Exception

### ISSUE THREAD

**Issue by miro-kodet** [magento/magento2#13585] opened 2018-02-09 13:24 UTC
### Preconditions

1. Magento 2.2.2
2. Linux (K/Ubuntu 17.04)
3. Apache 2.4.25
4. GD 2.2.4

### Steps to reproduce

1. Create new product via product factory
2. Set basic parameters
3. Assign images and save via product repository

### Expected result

1. Image should be stored

### Actual result

1. Image is not stored, exception with 'The image content is not valid.' being thrown. This can be bypassed using ->save() method directly on newly created product (productFactory->create()), unfortunately this method is deprecated (since 100.1.0)

**Comment by magento-engcom-team** [comment] 2018-02-14 11:17
Duplicate of #6803

**Closed as completed by magento-engcom-team** 2018-02-14 11:17 UTC
Labels: duplicate, Issue: Format is valid

**Comment by magento-engcom-team** [comment] 2018-02-14 11:30
@NORDCOMPCZ, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
