### ISSUE TITLE
'Add to cart' stuck 'adding'

### ISSUE THREAD

**Issue by QwertyZW** [magento/magento2#8854] opened 2017-03-11 05:51 UTC
### Preconditions

 php 7.0
 mysql 5.7
magento 2.1.5
apache 2.4

### Steps to reproduce

This happens when I checkout a fresh copy from github and add 1 product
Or when I download a release from the magento website with providing email+address

### Expected result

1.  get 'added to cart' instead of a greyed out frozen 'adding...'

### Actual result

1. greyed out frozen 'adding...'

Note that this only happens with chrome and microsoft edge. I do NOT have this problem with firefox

**Comment by korostii** [comment] 2017-03-15 13:11
This seems like some kind of js\ajax error.
Have you tried pressing F12 and checking the browser console? If there are any errors present, please attach a screenshot or copy of the full trace, that should speed up tracing the issue you have.

**Comment by QwertyZW** [comment] 2017-05-26 19:48
Still running into this issue in 2.1.6. There are no errors in the console, and the ajax posts look identical between firefox and chrome.

**Comment by veloraven** [comment] 2017-06-29 13:12
@QwertyZW thank you for your feedback.
Please provide exact and detailed steps to reproduce.

**Comment by FreekPaans** [comment] 2017-07-29 14:31
I had the same issue when I had magento running on a domain consisting of just a single segment, in my case `magentovm` (so magento was running on `http://magentovm/`). When I changed this to `magentovm.dev`, it worked.

This also fixed me not being able to add anything to the compare list.

**Comment by QwertyZW** [comment] 2017-07-29 18:34
Good observation. Anyone willing to investigate why this happens or should I look into it?

**Comment by magento-engcom-team** [comment] 2017-09-25 08:37
Hello, @QwertyZW. Unfortunately, we are not able to reproduce Your issue. We also tried to do it with a domain consisting of just a single segment, but the result is the same. Also please let us know if You can reproduce it on 2.1.9.

**Comment by magento-engcom-team** [comment] 2017-09-25 22:00
@QwertyZW, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by vrann** [comment] 2018-03-02 19:30
I was able to reproduce it with the following conditions:
- run magento under http://localhost:32722/
*Actual result*: add to cart hangs on "Adding" 

Then, added record in /etc/hosts `127.0.0.1       deployment.vm`, updated core_config_data with the base url `http://deployment.vm:32722/`, cleared cache.

*Actual Result*: add to cart works.

**Comment by rhino-corey** [comment] 2018-03-02 22:55
I have observed this same behavior running Magento CE 2.2.2 under http://localhost with the Blank theme inside a docker container. I added one product with a photo, hit Add To Cart and the button freezes after some ajax requests come back.

The xhr request to http://localhost/customer/section/load/?sections=cart%2Cmessages&update_section_id=true&_=1520030826719 responds with this payload:

`{"cart":
{"summary_count":0,
"subtotalAmount":null,
"subtotal":"<span class=\"price\">$0.00<\/span>",
"possible_onepage_checkout":true,
"items":[],
"extra_actions":"",
"isGuestCheckoutAllowed":true,
"website_id":"1",
"subtotal_incl_tax":"<span class=\"price\">$0.00<\/span>",
"subtotal_excl_tax":"<span class=\"price\">$0.00<\/span>",
"data_id":1520030854},
"messages":{"messages":[],
"data_id":1520030854}}`

...which if you ask me, looks rather bogus.

**Follow up:**
I adjusted the host name to domain.dev.com and the Add to Cart works correctly.

**Comment by magento-engcom-team** [comment] 2018-03-30 12:48
@QwertyZW, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by leonhelmus** [comment] 2018-07-23 01:37
Still a problem. If the link has http://localhost/magento/project-community-edition it does nothing when adding to cart. If you change http://localhost/magento/project-community-edition to http://127.0.0.1/magento/project-community-edition it works again. Hope this helps some people.

I use Magento ver. 2.2.5, XAMPP.

**Comment by daaannorris** [comment] 2018-08-08 12:30
I remember having this issue with M1 - and also recently encountered it with M2.
Simply change the domain of your docker instance from localhost:8080 to local.theme:8080 and add the appropriate line within your /etc/hosts file.

**Comment by noahp78** [comment] 2018-10-04 09:08
Can confirm this issue stil happens on the latest release of Magento 2.2.6, maybe worth including this solution in documentation / installer?

It looks like a issue with the FormKey and it's validator, and a session not being correctly set or get?

**Comment by rerlinger** [comment] 2018-10-17 14:39
I reproduced this issue on release of Magento 2.2.2, if it's running inside a Docker container. 
After adding a custom domain name (e.g. "magento.local") to /etc/hosts and changing the config values "web/secure/base_url" and "web/unsecure/base_url" to "https://magento.local") the Add-To-Cart button is working now.

**Comment by krzksz** [comment] 2019-12-17 19:36
I'm going to close this ticket as this is a matter of local development environment configuration and multiple workarounds were already provided.

**Closed as completed by krzksz** 2019-12-17 19:36 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid
