### ISSUE TITLE
Export data issue

### ISSUE THREAD

**Issue by MizoAhmed33** [magento/magento2#37470] opened 2023-05-07 06:48 UTC
### Preconditions and environment

- Magento version : Magento ver. 2.3.7-p4

### Steps to reproduce

i export orders data but the file still bending for a long time i cannot get the data till now since  ore than 1 hour

### Expected result

i need the exported file to be  success to download the data 

### Actual result

the file export status is pending 

### Additional information

i try to reduce the time period to reduce the data but the same 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by MizoAhmed33** [comment] 2023-05-07 07:40
Case Solved

**Comment by engcom-Dash** [comment] 2023-05-08 09:29
@magento give me 2.4-develop instance

**Comment by MizoAhmed33** [comment] 2023-05-11 07:00
Hi dears  
i still have the same issue  
when i request to extract data  from magento it take alot of time more than 2 hours  
that is happen when i make first  request after 8.30 a.m. (Egypt time ) if i request before that time i get  the within 1 Minute

**Comment by engcom-Dash** [comment] 2023-05-11 18:36
Hi @MizoAhmed33 ,

Thanks for contribution and collaboration!

Verified the issue 2.4-develop instance and the issue is not reproducible.

 Preconditions:
Magento version 2.4-develop
PHP 8.1
 
Kindly refer below screenshots:
<img width="1511" alt="Screenshot 2023-05-08 at 3 26 22 PM" src="https://github.com/magento/magento2/assets/60198592/22f7d3fe-6d54-48f0-b8d6-097079d44074">

Steps to reproduce:
1.Install magento instance
2.Go to System>Export>export the File
 
There is no time taken for export  the file and we can download the file.this is was expected behaviour ,Kindly provide more information if the issue still reproducible.
 
thanks

**Comment by engcom-Bravo** [comment] 2023-06-02 06:18
Hi @MizoAhmed33,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-06-02 06:18 UTC
Labels: Issue: needs update, Reported on 2.3.7-p4
