### ISSUE TITLE
Single store setup does not show values that were saved at website level

### ISSUE THREAD

**Issue by eikoncode** [magento/magento2#33721] opened 2021-08-09 07:30 UTC
### Preconditions (*)
Magento 2.4.2

### Steps to reproduce (*)
Saved some values and  configuration field is only at website level. Then switch to single store setup page then return back to configuration you can see the field for website level but values are not showing up for configuration.

### Actual result (*)

![image](https://user-images.githubusercontent.com/75497880/128672504-2d58f2f1-84c0-4bb6-afa5-77f937078362.png)

**Comment by engcom-November** [comment] 2021-08-10 10:02
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible:
We are able to save the values/configurations at website level. In Single Store Setup, all the values saved are getting displayed as expected.
Unable to find Configuration - Service Base URL fields in Magento 2.4-develop branch. Kindly recheck the issue on Magento 2.4-develop and provide 3rd party extension/module details if using,  elaborate the steps to reproduce if the issue is still reproducible.
Thank you.

**Comment by eikoncode** [comment] 2021-08-11 04:15
Hi @magento-engcom-team The issue is when I have field  that has show in website option only
![image](https://user-images.githubusercontent.com/75497880/128968685-d9d43661-5ade-4b75-8784-b587fe63234c.png)

so lets say I save this field and it saves at websites level in core config data. Then I switch to single scope mode and then I came to configuration page again the values saves for this field will not be shown as well as I cannot update that field data also it does not save the data also.

**Comment by engcom-November** [comment] 2021-08-19 10:11
Hi @eikoncode, verified system.xml files for all Admin configurations and all the fields having showInWebsite='"1" have showInDefault="1" option as well.  Couldn't find "Service Base URL" on Magento 2.4-develop branch and any other field having showInWebsite="1" only. Kindly recheck the issue on clean Magento 2.4-develop instance and elaborate steps to reproduce / Configuration details if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2021-09-02 04:43
Hi @eikoncode ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-09-02 04:43 UTC
Labels: Issue: needs update, Reported on 2.4.2
