### ISSUE TITLE
Removing upsells using CSV import removes related products, upsells & cross-sells

### ISSUE THREAD

**Issue by vseager** [magento/magento2#33523] opened 2021-07-19 12:16 UTC
When updating related products, upsells and cross-sells via `System > Data Transfer > Import`, if you remove all upsells from a product using  `__EMPTY__VALUE__`, it removes all products from "Related Product", "Upsells" and "Cross-sells" even if the columns don't existing in the CSV import file.

### Preconditions (*)

1. Magento 2.4.2-p1
2. Brand new Magento installation with sample data

### Steps to reproduce (*)

1. Log into admin
2. Add a related products, upsells and cross-sells to a product
3. Create an import file which just removes upsells from the product and has no other columns (Example import file: [reset_upsells.csv](https://github.com/magento/magento2/files/6840605/reset_upsells.csv))
4. Go to `System > Data Transfer > Import`
5. Choose `Entity Type = Product` and `Import Behaviour = Add/Update`, and choose the example import file in step 3 (check SKU is correct)
6. Click "Check Data" and then "Import"

### Expected result (*)

1. Product should have no upsells but still have related products and cross-sells.

### Actual result (*)

1. Upsells, Related Products and Cross-sells have all been removed

**Before import:**
![screenshot-2021 07 19-12_58_53](https://user-images.githubusercontent.com/2035088/126157987-64c75c51-f03a-4718-99a0-f263ad69e590.png)

**Import settings:**
![screenshot-2021 07 19-12_59_26](https://user-images.githubusercontent.com/2035088/126158046-e08bbc8f-7ad1-4361-843e-bbf6c243395b.png)

**After import:**
![screenshot-2021 07 19-13_11_50](https://user-images.githubusercontent.com/2035088/126158075-8da88ecd-6fe6-4cbc-8bbd-a4cd712d1c9d.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by shikhamis11** [comment] 2021-07-20 05:25
@magento give me 2.4-develop instance

**Comment by shikhamis11** [comment] 2021-07-20 05:52
@magento give me 2.4.2-p1 instance

**Comment by shikhamis11** [comment] 2021-07-20 06:17
@magento give me 2.4.2-p2 instance

**Comment by shikhamis11** [comment] 2021-07-20 06:23
Hi, @vseager Thank you for reporting this issue. 
I can reproduce this issue on Magento 2.4.2-p1 but not on 2.4- develop instance. so it seems the issue is already fixed and will be available in the release.

**Comment by engcom-Echo** [comment] 2021-08-18 04:04
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by engcom-Echo** [comment] 2021-08-18 06:53
Hi @vseager 
We tried to reproduce this issue on 2.4-develop & was unable to do so.
Here are the Steps we followed,
1. Choose a product  from admin panel & add related products, upsells and cross-sells to that product
2. Create an import file which just removes upsells from the product and has no other columns ( We used the sample CSV shared by you)
3. Go to **System** > **Data Transfer** > **Import**
Set Entity Type = Product and Import Behaviour = Add/Update, and choose the file to be imported
Click **Check Dat**a and then **Import**
File was successfully imported
4. Go to products page, view the product chosen above & check the **Related Products, Up-Sells, and Cross-Sells** section, it was observed that only the Up-Sells were removed & Related products & Cross-Sells were intact.

<img width="1044" alt="Screenshot 2021-08-18 at 09 47 55" src="https://user-images.githubusercontent.com/51681435/129851677-2ef29f3b-69a9-4cb1-b57f-52adac14b4fe.png">

So kindly recheck this issue on Magento 2.4-develop branch and if the issue is still reproducible, please provide more details or additional/missing steps regarding the same.
Thank you.

**Comment by engcom-Echo** [comment] 2021-09-01 07:25
Hi @vseager 
Since we didn't get any updates from you & since we couldn't reproduce the issue being reported, we are closing this issue.
If this issue is still reproducible for you on magento 2.4-develop, please feel free to reopen this issue & provide more details or additional/missing steps regarding the same.

Thank you.

**Closed as completed by engcom-Echo** 2021-09-01 07:25 UTC
Labels: Issue: needs update

**Comment by adnanahmed-ki5** [comment] 2022-03-28 12:26
@engcom-Echo I am also facing that issue!
how can i get rid of it?
