### ISSUE TITLE
Problems update attribute with rest API

### ISSUE THREAD

**Issue by CodeGlitcher** [magento/magento2#5963] opened 2016-08-03 12:28 UTC
### Preconditions

1. Install Magento 2.1.0
### Steps to reproduce
1.  Create a selectable attribute.
   ![image](https://cloud.githubusercontent.com/assets/7511533/17364951/87418042-5983-11e6-8502-6fe225475c5a.png)
2. Update the attribute with the rest api

put  /rest/V1/products/attributes/{attribute_code}
body:

```
{
    "attribute":
        {

              "attribute_id": 192,
              "default_frontend_label": "Color2"
        }
}

```
### Expected result
1.  The default frontend label is set to Color2
### Actual result
1. An new empty option is added to the attribute
   ![image](https://cloud.githubusercontent.com/assets/7511533/17364975/bd147814-5983-11e6-8956-a0fe8c1a5208.png)

Sending an empty options array has the same result. 

```
{
    "attribute": {
        "attribute_id": 192,
        "attribute_code": "color",
        "default_frontend_label": "Color2",
        "options": []
    }
}
```

Another little thing. If you update the attribute labels using frontend_labels: 

```
{
    "attribute": {
        "attribute_id": 192,
        "attribute_code": "color",
                "default_frontend_label": "color",
        "frontend_labels": [
        {
            "store_id": 1,
            "label": "kleur"
        },
        {
            "store_id": 2,
            "label": "test"
        }]
    }
}
```

the field default_frontend_label is ignored.

**Comment by j4hangir** [comment] 2016-08-17 00:57
This might be relevant, but here having the same exact version of Magento, it is impossible to create a new attribute:

`post /rest/V1/products/attributes`
body:
`{
  'attribute': {
    'default_frontend_label': 'azmun', 
    'frontend_labels': [{'store_id': 1, 'label': 'azmun'}],
               'is_required ': False, 'frontend_input': 'azmun'
    }
 }
`

**Comment by j4hangir** [comment] 2016-08-17 01:02
This might be relevant, but here having the same exact version of Magento, it is impossible to create a new attribute:

`post /rest/V1/products/attributes`
body:
`{
  'attribute': {
    'default_frontend_label': 'azmun', 
    'frontend_labels': [{'store_id': 1, 'label': 'azmun'}],
               'is_required ': False, 'frontend_input': 'azmun'
    }
 }
`

While the same exception will be thrown:
`Exception: {"message":"%fieldName is a required field.","parameters":{"fieldName":"frontend_label"}}`

**Comment by j4hangir** [comment] 2016-08-17 01:02
This might be relevant, but here having the same exact version of Magento, it is impossible to create a new attribute:

`post /rest/V1/products/attributes`
body:
`{
  'attribute': {
    'default_frontend_label': 'azmun', 
    'frontend_labels': [{'store_id': 1, 'label': 'azmun'}],
               'is_required ': False, 'frontend_input': 'azmun'
    }
 }
`

While the same exception will be thrown:
`Exception: {"message":"%fieldName is a required field.","parameters":{"fieldName":"frontend_label"}}`

**Comment by SerhiyShkolyarenko** [comment] 2016-09-12 13:11
Hi @robg66!
Thank you for reporting the issue. I managed to reproduce it on the latest develop branch. default_frontend_label is set properly in my case, but empty value is added on each request.
Also, I reproduced inability to reset options. Our internal issue is MAGETWO-58290.

**Comment by SerhiyShkolyarenko** [comment] 2016-09-12 13:24
Hi @j4hangir!
'attribute_code" is required field for any attribute, but I don't see it in your data. 
I managed to create new attribute with the following data:
`{
  "attribute": {
    "is_visible": true,
    "extension_attributes": {},
    "attribute_code": "azmun",
    "frontend_input": "text",
    "entity_type_id": 4,
    "is_required": false,
    "options": [
    ],
    "is_user_defined": true,
    "default_frontend_label": "azmun",
    "frontend_labels": [
      {
        "store_id": 0,
        "label": "azmun_front_lagel"
      }
    ]
  }
}`

**Comment by SerhiyShkolyarenko** [comment] 2016-09-13 10:11
@robg66 we investigated that service(put /rest/V1/products/attributes/{attribute_code}) a bit.
When it works with options, it is oriented on _merging new options_ only, so resetting doesn't work.
For more fine-grained attribute options management please use /V1/products/attributes/:attributeCode/options service.
In the issue MAGETWO-58290 we will fix adding empty value to the options list.

**Comment by SerhiyShkolyarenko** [comment] 2016-09-16 09:27
Created a separate issue for default_frontend_label ignoring(MAGETWO-58609).

**Comment by SerhiyShkolyarenko** [comment] 2016-09-20 12:26
MAGETWO-58290 is delivered to develop branch

**Comment by SerhiyShkolyarenko** [comment] 2016-09-27 12:42
MAGETWO-58609 is delivered to develop branch. Closing the issue. Please feel free to leave comments if the issue is still reproducible for you.

**Closed as completed by SerhiyShkolyarenko** 2016-09-27 12:42 UTC
Labels: Issue: Ready for Work, bug report

**Comment by Ctucker9233** [comment] 2016-12-02 22:06
@SerhiyShkolyarenko Is MAGETWO-58290 going to be included in 2.1.3?

**Comment by SerhiyShkolyarenko** [comment] 2016-12-06 17:06
@Ctucker9233 unfortunately, no. Internal issue for backporting to 2.1 is MAGETWO-61922.

**Comment by Ctucker9233** [comment] 2016-12-06 22:03
@SerhiyShkolyarenko Thanks. Do you have the commit numbers for MAGETWO-58609? Do you know if those commits are safe to integrate into a 2.1.2 production environment with a live website as they currently exist?

**Comment by SerhiyShkolyarenko** [comment] 2016-12-08 15:54
@Ctucker9233 commits are 421ded5 and d3853ae. These changes were not tested on v.2.1.x.
