### ISSUE TITLE
Unused coupon marked as used

### ISSUE THREAD

**Issue by Thundar** [magento/magento2#32384] opened 2021-03-05 07:30 UTC
### Preconditions (*)

1. Magento 2.3.6 (I've checked code version for Magento 2.4 and it's the same) and minimum order amount limit set
2. Registered user
3. Coupon code with 1 use for customer and fixed discount amount

### Steps to reproduce (*)

1. Fill the cart up to the minimum order amount
2. Put the coupon to the cart just before the last checkout step, so the new total order amount is below minimum amount
3. Submit the order in the fastest way (i.e. I used payment-information API)

### Expected result (*)
1. The order is not placed, an error about minimum amount is shown
2. The coupon is still usable

### Actual result (*)
1. The order is not placed and an error about minimum amount is shown
2. The coupon is marked as used for the customer (in `salesrule_customer` ) and cannot be used again

Hint maybe:
The coupon is marked as used by `CouponUsagesIncrement`, a plugin to `beforeSubmit` of `QuoteManagement`. The quote validation is in `submitQuote`, nested to `submit`, so it is run after, and throws uncatched exceptions up to the frontend, so the database keeps the coupon as used. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment] 2021-03-11 14:36
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41267` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by navaneeth-m-terrificminds** [comment] 2024-03-06 13:03
Hi, can we prioritise this issue?

**Comment by engcom-Bravo** [comment] 2024-07-31 04:40
Hi @Thundar,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.


<img width="1340" alt="Screenshot 2024-07-31 at 10 07 25" src="https://github.com/user-attachments/assets/77b61a2c-2e34-4e0c-b1b6-ae8192da51f5">



Order is not placed and the coupon is still usable.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-31 04:40 UTC
Labels: Issue: Confirmed, Component: Webapi, Component: SalesRule, Reproduced on 2.4.x, Priority: P2, Progress: done
