### ISSUE TITLE
Installation seems stucked at 76% but it does finish

### ISSUE THREAD

**Issue by frilogg** [magento/magento2#28087] opened 2020-05-03 13:55 UTC
### Preconditions (*)

1. Magento Version 2.3.5.-1p
2. Centos 7.8, Mysql 5.7.30, PHP 7.3.17 - 

### Steps to reproduce (*)

1.Fresh install

### Expected result (*)

1. I would expect it to finish to 100% and say Magento Installation Sucess
2.

### Actual result (*)

1. It stuckes on 76% at the stage 
Module 'Magento_Customer':
Running data recurring...

2. From the installer log it is actually 100% finished and complete as it should but the output in the Browser doesent complete indicating the installation newer completed.

**Comment by engcom-Delta** [comment] 2020-11-17 14:37
Hi @frilogg thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop as Web Set Up Wizard was [removed](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-open-source.html#infrastructure-improvements) since version 2.4.0

Closed as Cannot Reproduce on the latest megento version

**Closed as completed by engcom-Delta** 2020-11-17 14:37 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.3.5
