### ISSUE TITLE
Create new Account with Date of Birth in magento 2.4.3

### ISSUE THREAD

**Issue by leduydong94** [magento/magento2#34990] opened 2022-01-19 09:33 UTC
### Preconditions (*)

1. Magento 2.4.3

### Steps to reproduce (*)

1. Set locale: Timezone is Brasilia Standard Time (America/Sao_Paulo); Locale is Portuguese (Brazil).
2. Set config Show Date of Birth is Optional or Required in Configuration->Customers->Customer Configuration->Name and Address Options
3. Create an Account in frontend

### Expected result (*)

1. Form create display normally

### Actual result (*)

1. Form create not display, through exception.
Video: https://www.loom.com/share/8c8d0a3336ae4282ba0061feb87f077a
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-01-20 13:11
Hi @leduydong94,

Thank you for reporting the issue.

I have tried this issue on the fresh installation (Magento 2.4-dev/2.4.3-P1) but I am not able to reproduce it. Account is getting created.
![image](https://user-images.githubusercontent.com/60198231/150344961-56544fa7-1fd8-4965-a36a-ccd8009b8431.png)
![image](https://user-images.githubusercontent.com/60198231/150345201-77735e99-37b1-4e62-929d-a2e4fb889b91.png)

Kindly recheck the issue on Magento 2.4-develop branch and elaborate the steps if the issue is still reproducible.
Thank you.

**Comment by leduydong94** [comment] 2022-01-21 02:48
> Hi @leduydong94,
> 
> Thank you for reporting the issue.
> 
> I have tried this issue on the fresh installation (Magento 2.4-dev/2.4.3-P1) but I am not able to reproduce it. Account is getting created. ![image](https://user-images.githubusercontent.com/60198231/150344961-56544fa7-1fd8-4965-a36a-ccd8009b8431.png) ![image](https://user-images.githubusercontent.com/60198231/150345201-77735e99-37b1-4e62-929d-a2e4fb889b91.png)
> 
> Kindly recheck the issue on Magento 2.4-develop branch and elaborate the steps if the issue is still reproducible. Thank you.

Thank you! 
I'll recheck on Magento 2.4-develop branch

**Comment by engcom-Hotel** [comment] 2022-02-09 06:10
Hello @leduydong94,

We request you to please try to reproduce this issue in Magento 2.4-develop branch and let us know in case you are able to reproduce the issue.

Thanks

**Comment by leduydong94** [comment] 2022-02-21 08:52
> Hello @leduydong94,
> 
> We request you to please try to reproduce this issue in Magento 2.4-develop branch and let us know in case you are able to reproduce the issue.
> 
> Thanks

Sorry for the late reply. The issue does not appear in branch develop, but in released version, it still happening. I don't know why. Can you tell me reason and how to fix it? If possible, please check on the released version.
Thanks

**Comment by engcom-Hotel** [comment] 2022-02-23 12:54
Hello @leduydong94,

Thanks for the confirmation. The issue will automatically be resolved in the next Magento release. As per confirmation in this [comment](https://github.com/magento/magento2/issues/34990#issuecomment-1046615899), we are closing this issue.

Thanks

**Closed as completed by engcom-Hotel** 2022-02-23 12:54 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
