### ISSUE TITLE
Console error on checkout after changing the allowed countries from admin.

### ISSUE THREAD

**Issue by mahesh-rajawat** [magento/magento2#20631] opened 2019-01-26 11:55 UTC
### Preconditions (*)

1. Magento 2.2.x
2. Magento 2.3.x

### Steps to reproduce (*)

1. Add a product to cart as guest.
2. Fill the shipping address and reload the page now shipping address must be filled already.
3. Go to Admin->Stores->configuration->General, Change allowed countries single one that is not filled on checkout. like i have filled United State at checkout and change allowed countries to Libya.
4. Now reload the checkout shipping page again. 

### Expected result (*)

1. 
![screen shot 2019-01-26 at 5 23 49 pm](https://user-images.githubusercontent.com/32479280/51786778-32554600-218f-11e9-9675-a397cbb2165e.png)

2.

### Actual result (*)

1. ![screen shot 2019-01-26 at 5 21 28 pm](https://user-images.githubusercontent.com/32479280/51786760-edc9aa80-218e-11e9-955b-7e205853b969.png)
2.

**Comment by magento-engcom-team** [comment] 2019-01-26 11:55
Hi @maheshWebkul721. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@maheshWebkul721 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-26 12:02
Hi @amol2jcommerce. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-01-26 12:04
@amol2jcommerce Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97941` were created

**Comment by magento-engcom-team** [comment] 2019-01-26 15:55
Hi @GovindaSharma. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-02-01 20:15
Hi @maheshWebkul721. Thank you for your report. 
The issue has been fixed in magento/magento2#20634 by @GovindaSharma in 2.3-develop branch
Related commit(s):
 - [12deeebc95e467bcc628bb39d2d8ec753ec20b85](https://github.com/magento/magento2/commit/12deeebc95e467bcc628bb39d2d8ec753ec20b85)
 - [d1340328cb649cec143cd31484536e15393d00bf](https://github.com/magento/magento2/commit/d1340328cb649cec143cd31484536e15393d00bf)
 - [0902931633e350761e509a62ad66b22ff40cd093](https://github.com/magento/magento2/commit/0902931633e350761e509a62ad66b22ff40cd093)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2019-02-01 20:15 UTC
Labels: Issue: Ready for Work, Component: Checkout, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by sidolov** [comment] 2019-02-08 17:02
Hi @maheshWebkul721. Thank you for your report. 
The issue has been fixed in magento/magento2#20885 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [467a2a8cedf087bf9440ff8d711057188d2084b8](https://github.com/magento/magento2/commit/467a2a8cedf087bf9440ff8d711057188d2084b8)
 - [a48a4dec39556645fc2511c52065f78401d16ac8](https://github.com/magento/magento2/commit/a48a4dec39556645fc2511c52065f78401d16ac8)
 - [8d6721317e84b2382add21b5f21c4627becf0c67](https://github.com/magento/magento2/commit/8d6721317e84b2382add21b5f21c4627becf0c67)
 - [1a3806794361745f7678ad4d5ede83ecdaa688cb](https://github.com/magento/magento2/commit/1a3806794361745f7678ad4d5ede83ecdaa688cb)

The fix will be available with the upcoming 2.2.9 release.
