### ISSUE TITLE
/update/ folder exists on production and not protected with admin login check

### ISSUE THREAD

**Issue by magenx** [magento/magento2#21539] opened 2019-03-01 09:38 UTC
### Preconditions (*)

1. Magento 2.x
2. Installed with composer / download zip
3. Default nginx config or apache .htaccess

### Steps to reproduce (*)

1. Navigate to my-magento-shop.com/update/

### Expected result (*)

1. Login page, Redirect to login, 401 error, empty page.
2. Update folder and its functionality must be included within magento admin interface.
3. Setup/Update folders and its functionality must be loaded only to setup/update, and unloaded after immediately, and not available in production mode.

### Actual result (*)

you have access to log entries, can see status `update/index.php/status`
in some circumstances you can see `Rollback` button.
![screencapture-update-2019-03-01-09_03_53](https://user-images.githubusercontent.com/1591200/53628721-b2921f80-3c03-11e9-96a5-01bee0df45ce.png)

**Comment by magento-engcom-team** [comment] 2019-03-01 09:38
Hi @magenx. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@magenx do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-03-01 09:45
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-03-01 09:53
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98511`, `MAGETWO-98512` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2020-11-30 21:47
The report related to technology or functionality that was removed(or not supported) from the Magento code-base.
Or cannot be fixed and delivered in the scope of this public repository.

Examples:
- Removed payment methods. [Magento Commerce 2.4.0 Release Notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-commerce.html), [Deprecation of Magento core payment integrations](https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445). All questions, issue reports, and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
- Mysql search. Replaced with Elasticsearch 
- Not [Supported browsers](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#supported-browsers)
- Not supported [Operating systems](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#operating-systems-linux-x86-64)
- Web Wizard install
- Not a bug 
- etc

**Closed as completed by magento-engcom-team** 2020-11-30 21:47 UTC
Labels: Component: Setup, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, help wanted, Progress: done

**Comment by magento-engcom-team** [comment] 2020-11-30 21:53
The report related to technology or functionality that was removed(or not supported) from the Magento code-base.
Or cannot be fixed and delivered in the scope of this public repository.

Examples:
- Removed payment methods. [Magento Commerce 2.4.0 Release Notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-commerce.html), [Deprecation of Magento core payment integrations](https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445). All questions, issue reports, and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
- Mysql search. Replaced with Elasticsearch 
- Not [Supported browsers](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#supported-browsers)
- Not supported [Operating systems](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#operating-systems-linux-x86-64)
- Web Wizard install
- Not a bug 
- etc

**Comment by magento-engcom-team** [comment] 2021-02-17 14:33
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
