### ISSUE TITLE
Create a order from magento 2 admin with multiple website return Invalid customer address id error

### ISSUE THREAD

**Issue by rama-tm** [magento/magento2#31163] opened 2020-12-04 09:24 UTC
### Preconditions (*)

1. Magento 2.3.4 CE
2.

### Steps to reproduce (*)

1. Create two websites with different stores and store views.
> Germany Website - Germany store -> Germany Store view
> English Website - English store -> English Store view
2. Create a customer (xxx@xxx.xxx) from the Germany website and add the address for that user.
3. Goto Admin -> Sales -> Order -> Create New order -> Select the existing customer(xxx@xxx.xxx).
4. Then select the store view ( Select the English store view).
5. Now add the product and use the existing customer(xxx@xxx.xxx) address data in the address information section and select the payment and shipping method.
![image](https://user-images.githubusercontent.com/59078028/101145792-49450900-3640-11eb-8a54-400363e57e21.png)
6. Now submit the order.

### Expected result (*)

1. Create a customer(xxx@xxx.xxx) in the English store view.
2. And order needs to be placed under this customer name.

### Actual result (*)

1. Customer created successfully in the English store view and got the customer register success mail.
2. But the order not placed successfully. It returns **Invalid customer address id 23**
![image](https://user-images.githubusercontent.com/59078028/101145267-88bf2580-363f-11eb-879c-e8f15037f129.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment] 2020-12-04 10:45
@magento give me 2.4-develop instance

**Comment by rama-tm** [comment] 2020-12-24 05:42
Hi @krishprakash , Are you able to reproduce this issue? Can you please share your update?

**Comment by engcom-Bravo** [comment] 2020-12-29 14:48
Hello @rama-tm 

Thank you for your report.

Seems like the issue is already fixed in the latest 2.4-develop.

We have tried to reproduce via the provided steps, and the order is successfully created. Please see the attachment.
![order](https://user-images.githubusercontent.com/51680745/103291996-94f79200-49f5-11eb-8916-9de13185b2f9.gif)

Can you please Confirm that you are able to reproduce the issue on 2.4-develop?

Thank you

**Comment by rama-tm** [comment] 2020-12-29 14:53
Hi @engcom-Bravo,

Thanks for the update.

We are having this issue in Magento ver. 2.3.4

Is there any patch available to add the fix in Magento ver. 2.3.4 version.
Please suggest to me possible ways to fix this issue in my magento instance.

**Comment by rama-tm** [comment] 2021-01-04 06:41
Hi @engcom-Bravo , 
Hope you are well.
Could you please share your suggestion for my concern?

**Comment by engcom-Bravo** [comment] 2021-01-04 10:56
Hello @rama-tm. I'm not aware of any particular commit which fixes the issue. 
I can offer you to follow the discussion https://magento.stackexchange.com/questions/265364/how-to-fix-invalid-customer-address-id-in-magento-2-1-5, and check the discussion in this issue https://github.com/magento/magento2/issues/23618

**Comment by engcom-Bravo** [comment] 2021-01-19 12:31
Hello @rama-tm 
Did the proposed solution help to resolve your issue?

Thank you

**Comment by rama-tm** [comment] 2021-01-19 12:45
Hi @engcom-Bravo ,

Hope you are well.
Actually, they [suggested some commands](https://magento.stackexchange.com/questions/265364/how-to-fix-invalid-customer-address-id-in-magento-2-1-5) to execute in the database, but which is not working.
And the [discussion](https://github.com/magento/magento2/issues/23618) was also not yet closed.

**Comment by engcom-Bravo** [comment] 2021-02-02 12:45
Hello @rama-tm 

As we can not deliver a fix into an already released version 2.3.4, and the issue is not reproducible on 2.4-develop - we have to close this ticket. 
Thank you for your collaboration and quick responses.
Please feel free to comment and share any updates on the issue.

**Closed as completed by engcom-Bravo** 2021-02-02 12:45 UTC
Labels: Issue: needs update
