### ISSUE TITLE
Monolog issue

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#35604] opened 2022-06-10 08:32 UTC
### Preconditions and environment

- Magento version 2.4.4
- PHP8.1
- Install data-migration-tool
- Monolog 2.7.0

### Steps to reproduce

1. composer update
2. bin/magento setup:upgrade

### Expected result

Everything works fine

### Actual result

```
PHP Fatal error:  Declaration of Migration\Logger\Logger::addRecord(int $level, string $message, array $context = []): bool must be compatible with Monolog\Logger::addRecord(int $level, string $message, array $context = [], ?Monolog\DateTimeImmutable $datetime = null): bool in /var/www/html/vendor/magento/data-migration-tool/src/Migration/Logger/Logger.php on line 34
```

### Additional information

Monolog 2.7.0 has bee released yesterday, and have breaking changes.

Quick Solution : fix dependency to 2.6.0
Best Solution : fix compatibility issues

Note that everyone who upgrades to 2.4.4 from now will probably have this issue.

Quick solution for devs who don't want to wait for a fix & release : `composer require monolog/monolog:2.6.0`

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment] 2022-06-10 08:59
i think we should report here
https://github.com/magento/data-migration-tool/issues

**Comment by mrtuvn** [comment] 2022-06-10 09:01
quick workaround composer require monolog/monolog:"!=2.7.0" --no-update

**Comment by convenient** [comment] 2022-06-10 14:56
https://github.com/magento/magento2/pull/35596

**Comment by engcom-November** [comment] 2022-06-16 16:20
Hi @Nuranto ,
Thank you for reporting and collaboration. Verified the issue by upgrading from 2.4.3-p1 to 2.4.4 but could not able to reproduce the issue.
Steps performed:
1. Installed 2.4.3-p1 project-community-edition with PHP7.4
2. Upgraded to 2.4.4 project-community-edition [(Ref upgrade guide:](https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/implementation/perform-upgrade.html)
3. Ran composer update
4. Ran: php bin/magento setup:upgrade - No issue
5. Upgraded php to 8.1
No issue: Upgrade successful. User is able to access Magento admin and UI.
Kindly elaborate the steps/ missing configuration details to reproduce the issue. Thank you.

**Comment by mrtuvn** [comment] 2022-06-16 23:31
you need install monolog v2.7.0 to able see problem

**Comment by engcom-November** [comment] 2022-06-17 12:36
Thanks for the update @mrtuvn 
However, [monolog](https://github.com/Seldaek/monolog) is not part of https://github.com/magento/magento2 git repository. Community cannot able to provide fix for it in this repository.
As per Magento [devdocs](https://devdocs.magento.com/guides/v2.4/config-guide/log/log-magento.html?itm_source=devdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=monolog), Magento uses Monolog by default. Monolog implemented as a preference for Psr\Log\LoggerInterface in the Magento application [di.xml](https://github.com/magento/magento2/blob/2.4/app/etc/di.xml#L9) Kindly refer this guide to use the same for logging. Otherwise all questions, issue reports and fix for them should be addressed to the corresponding extension owners(support)
Thank you.

**Comment by convenient** [comment] 2022-06-17 12:48
@engcom-November 

The facts
- Magento require version `^2.6` of  monolog, which means that 2.7.0 is the highest version that is installed when you `composer create project` of magento
- This means magento either needs to say `<=2.7.0` for their monolog requirement, or fix their code to be compatible.

Either way there is an action for magento here, when you build a version of latest magento from scratch you will pull in a monolog version incompatible with some magento code.

The maintainer of monolog thinks the implementations by magento in the data migration tool and the integration test infrastructure is, and i quote, "madness".

See https://github.com/Seldaek/monolog/issues/1684#issuecomment-1152874168

**Comment by engcom-November** [comment] 2022-06-17 13:46
Verified the issue again by installing Magento 2.4.4 project-community-edition with PHP 8.1 but could not able to reproduce the issue with below steps performed:
1. Installed Magento 2.4.4 Project Community edition with PHP 8.1.6
2. Ran > composer require monolog/monolog:2.7.0 . (composer.json file got updated with "monolog/monolog": "2.7.0")
3. Ran > composer update
4. Ran > php bin/magento setup:upgrade
No issue: Upgrade is successful.
Kindly provide missing steps / configuration details to reproduce the issue.
Thank you.

**Comment by engcom-November** [comment] 2022-06-20 12:39
Verified the issue again on Magento 2.4.4 Project community edition with PHP 8.1.6 and the issue is reproducible on installing data-migration-tool.
Error:
PHP Fatal error:  Declaration of Migration\Logger\Logger::addRecord(int $level, string $message, array $context = []): bool must be compatible with Monolog\Logger::addRecord(int $level, string $message, array $context = [], ?Monolog\DateTimeImmutable $datetime = null): bool in /var/www/html/mg244/project-community-edition/vendor/magento/data-migration-tool/src/Migration/Logger/Logger.php on line 34

**Comment by fvlasie** [comment] 2022-06-22 16:28
This also occurs with PHP 7.4...
<img width="679" alt="Screenshot 2022-06-22 at 9 27 55 AM" src="https://user-images.githubusercontent.com/33334298/175086215-7b757bed-d15c-48d0-af2f-2bb1387965d8.png">

**Comment by fvlasie** [comment] 2022-06-22 16:36
Confirming that composer `require monolog/monolog:2.6.0` fixed the issue.

**Comment by timoffmax** [comment] 2022-07-19 18:24
Also reproducible when you run integration tests.

**Comment by convenient** [comment] 2022-07-22 11:20
https://github.com/Seldaek/monolog/commit/3cba75ec0926eec177a4a2cd6c977ecddd0fc7c1

```
Mark Logger https://github.com/Final to discourage extension
```

Updating to use a handler seems like the right thing to do.

**Comment by damienwebdev** [comment] 2022-07-24 14:51
Just a notification that a further update to Monolog versions occurred ~3 hours ago - `2.8.0` https://github.com/Seldaek/monolog/releases/tag/2.8.0.

I had code like:

```bash
composer require monolog/monolog:"!=2.7.0" --no-update
```

Which I now changed to:

```bash
composer require monolog/monolog:"<2.7.0" --no-update
```

**Comment by earlelnar** [comment] 2022-08-04 00:54
Hello Everyone, 

Encountered these issues as well.
Created a patch to temporary fix the issue of monolog. until there's an official fix from Magento to fix those issues

Patch file to fix the issue:
(This patch is created based on this one: https://github.com/magento/magento2/pull/35596/files )
https://gist.github.com/earlelnar/5321567ca4551a4da37761e7cbe41977 

I hope that patch will help you out.

One thing after you fix the monolog issue you might encounter this issue as well.
Deprecated Functionality: Return type of Migration\ResourceModel\AbstractCollection::current()
So here's the link for the fix in case you guys will need it.
https://github.com/magento/data-migration-tool/issues/893 

Thanks,
Earl

**Comment by glo35082** [comment] 2022-08-05 08:45
@magento give me 2.4-develop instance

**Comment by ihor-sviziev** [comment] 2022-08-09 21:01
Looks like in Magento 2.4.5 we have a fix for this issue https://github.com/magento/magento2/commit/360fd1ba9d6e67185b7fbd3e00223cd948bb896e

**Comment by hostep** [comment] 2022-08-11 17:10
The full AC-3556 fix is here: https://github.com/magento/magento2/commit/b2bfd0562c3ea5708fb836347404ce38b57040c4

Unfortunately the fix seems just like a workaround, because this problem might happen again in the future.
It's probably wiser if Adobe listens to [the recommendations](https://github.com/Seldaek/monolog/issues/1684#issuecomment-1152874168) of the author of the monolog library who suggests a more future proofed way to fix this.

**Comment by convenient** [comment] 2022-08-11 17:36
Agreed @hostep 

I did try and have some conversation about this back in June but was ignored.

https://github.com/magento/magento2/pull/35596#issuecomment-1153655914

My workaround was then taken in any case 🙃

**Comment by Nuranto** [comment] 2022-08-29 07:49
Hi here,

I think you missed this one : `vendor/magento/data-migration-tool/src/Migration/Logger/Logger.php`

**Comment by engcom-Hotel** [comment] 2022-10-10 08:23
Hello,

As I can see this issue got fixed by the internal team
Related commits: https://github.com/magento/magento2/commit/b2bfd0562c3ea5708fb836347404ce38b57040c4

Hence closing the issue.

Thanks

**Closed as completed by engcom-Hotel** 2022-10-10 08:23 UTC
Labels: Issue: Confirmed, Component: Framework/Code, Reproduced on 2.4.x, Priority: P1, Progress: done, Area: Upgrades - Upgrade Compatibility Tool, Reported on 2.4.4
