### ISSUE TITLE
Unable to install B2B module in magento 2.4.5-p1 EE

### ISSUE THREAD

**Issue by rahulrj-eglobeits** [magento/magento2#36498] opened 2022-11-21 09:15 UTC
### Summary

we are trying to install b2b in fresh magento 2.4.5-p1 EE unfortunately getting some error

### Examples

```
Problem 1
    - magento/module-b2b 100.3.4 requires magento/framework 103.0.5 -> found magento/framework[103.0.5] but the package is fixed to 103.0.5-p1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - magento/extension-b2b 1.3.4 requires magento/module-b2b 100.3.4 -> satisfiable by magento/module-b2b[100.3.4].
    - Root composer.json requires magento/extension-b2b 1.3.4 -> satisfiable by magento/extension-b2b[1.3.4].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-11-21 10:24
Hi @rahulrj-eglobeits ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance with enterprise edition and unable to reproduce the issue.
B2B modules are successfully installed in Magento 2.4-develop with ee edition. No exceptions/errors were observed.
Kindly recheck the issue by installing b2b on Magento 2.4-develop instance with ee editon and elaborate steps / configuration details / or any 3rd party extensions / modules enabled is causing the issue.
Thank you.

**Comment by hostep** [comment] 2022-11-21 18:34
@rahulrj-eglobeits: you'd probably want to also upgrade the package `magento/module-b2b` to version `100.3.4-p1`. 
That should work.

@engcom-November: stuff like this can't be tested on `2.4-develop`, this is about version constraints of stable released magento packages. Just FYI 😉

**Comment by rahulrj-eglobeits** [comment] 2022-11-22 08:14
> @rahulrj-eglobeits: you'd probably want to also upgrade the package `magento/extension-b2b` to version `1.3.4-p1` and/or `magento/module-b2b` to version `100.3.4-p1`. That should work.
> 
> @engcom-November: stuff like this can't be tested on `2.4-develop`, this is about version constraints of stable released magento packages. Just FYI wink

thank you mahn its worked

**Comment by hostep** [comment] 2022-11-22 12:00
Great to hear, can you close this issue now that you solved your problem? 🙂

**Closed as completed** 2022-11-22 13:51 UTC
Labels: Issue:  Cannot Reproduce, Triage: Dev.Experience, Issue: needs update

**Comment by raquelperez899** [comment] 2023-02-23 19:05
@magento give me 2.4.5-p1 instance

**Comment by raquelperez899** [comment] 2023-02-23 19:13
@magento it's displayed this message:
"An error has happened during application run. See exception log for details."
in this link: https://478a62c6c75124afbfbe69dffaadce26.instances.magento-community.engineering/
