### ISSUE TITLE
page cache also caches breadcrumbs

### ISSUE THREAD

**Issue by ktruehl** [magento/magento2#5502] opened 2016-07-06 13:57 UTC
## Steps to reproduce
1. install magento 2.1
2. install the demo data
3. clear the cache (including page cache)
4. visit the category "Women" -> "Tops" -> "Hoodies & Sweatshirts"
5. visit the product page of "Mona Pullover Hoodlie-XS-Green"
   => the breadcrumbs look like this

```
Home > Women > Tops > Hoodies & Sweatshirts > Hera Pullover Hoodie-XS-Orange 
```
1. visit the category "Women" -> "Tops"
2. visit the product page of the same product "Mona Pullover Hoodlie-XS-Green"
## Expected result

The breadcrumbs shoud look like this

```
Home > Women > Tops > Hera Pullover Hoodie-XS-Orange 
```
## Actual result

The breadcrumbs look like this

```
Home > Women > Tops > Hoodies & Sweatshirts > Hera Pullover Hoodie-XS-Orange 
```

The breadcrumbs have been cached. The last visited category should is "Women" -> "Tops" and therefore the breadcrumbs should reflect this. Instead the breadcrumbs from the first visit of the product page after the clearing of the cache (including the page cache) are still shown.

**Comment by AlexShaban** [comment] 2016-07-11 08:42
Try "Advanced Breadcrumbs" for Magento 2! Just follow the link
https://www.magestyapps.com/magento-2-extensions/

**Comment by ktruehl** [comment] 2016-07-11 08:49
@AlexShaban If I wanted an extended (or better) breadcrumb functionality, I would Google for it. Instead I want Magento to fix this, that's why I posted on Github. Please don't use Github for advertisements.

**Comment by kanduvisla** [comment] 2016-07-29 14:01
Is there any update on this? I can confirm this in 2.0.8. Has this been addressed in 2.1?

**Comment by ktruehl** [comment] 2016-07-29 14:54
It's still a problem in Magento 2.1. Just checked.

**Comment by andimov** [comment] 2016-08-19 15:13
@ktruehl
in which way Magento was installed?

**Comment by ktruehl** [comment] 2016-08-19 19:37
I don't understand your question @andimov. What exactly do you mean? Just install the store with the demo data following the official instructions.

**Comment by andimov** [comment] 2016-08-31 14:22
@ktruehl 
It was install from zip archive or from github or by "composer create-project"?

**Comment by ktruehl** [comment] 2016-08-31 14:23
From zip archive.

**Comment by andimov** [comment] 2016-09-02 15:33
@ktruehl 
I've created an internal ticket MAGETWO-58014  for this issue and linked it to this one.

**Comment by kanduvisla** [comment] 2016-09-20 08:45
For the record: it still exists in M2.1.1

**Comment by phuc128t** [comment] 2016-09-21 10:23
I got same issue here.

**Comment by InsomniakDev** [comment] 2017-04-04 15:34
No news there ?
I'm having the same problem, do I need to play with ttl attribute on breadcrumbs block?

**Comment by vtiertant** [comment] 2017-04-14 09:29
Personally, I have bypassed the problem by overload the getBreadcrumbPath method to always display the same breadcrumb regardless of which page you are. I chose to display the breadcrumb of the more refined category. (Because in addition to the magento cache, I have another cache on the website)


I know that it loses the main utility of a breadcrumb but it is better than an erroneous display

```php
    /**
     * Return current category path or get it from current category
     * and creating array of categories|product paths for breadcrumbs
     *
     * @return string
     */
    public function getBreadcrumbPath()
    {
        if (!$this->_categoryPath) {

            $path = [];

            //if product page
            if ($this->getProduct()) {

                $categories = $this->getProduct()->getCategoryCollection()->getItems();

                $finalCategory = null;

                foreach ($categories as $category) {
                    //first loop
                    if (null === $finalCategory) {
                        $finalCategory = $category;
                    }

                    if ($finalCategory->getPosition() > $category->getPosition()) {
                        //recover the most refined category
                        $finalCategory = $category;
                    }
                }

                $parentCategories = $finalCategory->getParentCategories();

                //foreach parentCategory from this category
                foreach ($parentCategories as $parentCategory) {
                    // add parent category path breadcrumb
                    $path['category' . $parentCategory->getId()] = [
                        'label' => $parentCategory->getName(),
                        'link'  => $this->_isCategoryLink($parentCategory->getId()) ? $parentCategory->getUrl() : ''
                    ];
                }

                // add last category path breadcrumb
                $path['category' . $finalCategory->getId()] = [
                    'label' => $finalCategory->getName(),
                    'link'  => $this->_isCategoryLink($finalCategory->getId()) ? $finalCategory->getUrl() : ''
                ];

                //// add product path breadcrumb
                $path['product'] = ['label' => $this->getProduct()->getName()];
            }
            else { //else, page list (category)
                $category = $this->getCategory();
                if ($category) {
                    $pathInStore = $category->getPathInStore();
                    $pathIds = array_reverse(explode(',', $pathInStore));

                    $categories = $category->getParentCategories();

                    // add category path breadcrumb
                    foreach ($pathIds as $categoryId) {
                        if (isset($categories[$categoryId]) && $categories[$categoryId]->getName()) {
                            $path['category' . $categoryId] = [
                                'label' => $categories[$categoryId]->getName(),
                                'link'  => $this->_isCategoryLink($categoryId) ? $categories[$categoryId]->getUrl() : ''
                            ];
                        }
                    }
                }
            }

            $this->_categoryPath = $path;
        }

        return $this->_categoryPath;
    }
```

Without forgetting to override the method getCategoryCollection from ResourceModel/Product to add Attribute 'name' :

```php
     /**
     * Get collection of product categories
     *
     * @param \Magento\Catalog\Model\Product $product
     * @return \Magento\Catalog\Model\ResourceModel\Category\Collection
     */
    public function getCategoryCollection($product)
    {
        $collection = parent::getCategoryCollection($product);
        $collection->addAttributeToSelect('name');

        return $collection;
    }
```

Hope this helps someone...

PS: Sorry for my English :p

**Comment by InsomniakDev** [comment] 2017-04-14 10:37
thanks a lot @vtiertant nice work around

**Comment by kamilszewczyk** [comment] 2017-06-21 12:03
Is this issue going to be addressed in Magento 2.2?

**Comment by magento-engcom-team** [comment] 2017-10-13 08:33
@ktruehl, thank you for your report.
We've created internal ticket(s) MAGETWO-58014 to track progress on the issue.

**Comment by ilnytskyi** [comment] 2018-03-23 10:32
#distributed-cd

**Comment by magento-engcom-team** [comment] 2018-03-23 10:33
@ilnytskyi thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by ilnytskyi** [comment] 2018-03-23 11:10
Tried to reproduce on 2.2-develop and 2.1-develop
Can not be reproduced.

For 2.1-develop need to enable **Use Categories Path for Product URLs**  in 
Stores -> Configuration -> Catalog -> Catalog 
to see full path of breadcrumbs

**Comment by andrei-vdc** [comment] 2021-07-19 11:10
This is not solved even in m2.3

Breadcrumbs get cached in FPC and the first cached version will always show. 
Expected behavior is that the last active category should be in the breadcrumbs even if long urls are not enabled.

**Comment by haroldclaus** [comment] 2022-08-04 09:51
I've noticed that this issue is still unfixed in 2.4.4... Any thoughts on when this will be finally resolved?

**Comment by Morgy93** [comment] 2024-03-05 14:55
Issue is still present in 2.4.6-p4.

@ilnytskyi Any chance of reopening?

**Comment by engcom-November** [comment] 2024-03-06 09:17
Hello @ktruehl,
Thank you for the report and collaboration.
Thank you @Morgy93 for the update.

Tried to verify this issue on 2.4-develop. But in our case it is not reproducible.
Installed sample data on 2.4-develop, and cleared full_page cache.

Please take a look at the screenshot:
**Opened the hera pullover hoodie through "Women" -> "Tops" -> "Hoodies & Sweatshirts", got the below breadcrumb**
```
Home > Women > Tops > Hoodies & Sweatshirts > Hera Pullover Hoodie
```

**Opened the same product through "Women" -> "Tops" with below breadcrumb**
```
Home > Women > Tops > Hera Pullover Hoodie
```
We are getting correct breadcrumb paths.

Let us know if we are missing anything.

Thank you.

**Comment by Morgy93** [comment] 2024-03-06 13:23
Breadcrumbs are loaded via AJAX on that demo by default. That's remarkably interesting.

@engcom-November I think I judged too early. Deeply sorry for bothering you. There should be an easier way to get these demo instances for testing. Maybe I would've checked it earlier. Anyway, big thanks for you quick action. 🙏 Please close this issue.

**Comment by engcom-November** [comment] 2024-03-07 10:08
Hello @Morgy93,

Thank you for the confirmation, closing this issue as fixed.

**Closed as completed by engcom-November** 2024-03-07 10:08 UTC
Labels: bug report, Component: Framework/Cache, Event: distributed-cd, Issue: needs update, Reported on 2.1.x
