### ISSUE TITLE
Extra headers in api-functional test cases

### ISSUE THREAD

**Issue by darshankhatri16** [magento/magento2#25106] opened 2019-10-17 06:58 UTC
I need to pass extra values in the header while writing api-functional test cases. No provision is there where I can pass extra header.

### Preconditions (*)

1.Magento version 2.3.3

### Steps to reproduce (*)

1. write api-functional test case for any custom module and pass extra values in header apart from authorization token

### Expected result (*)

1. Allow passing extra values in the header

### Actual result (*)

1. The throwing error header is missing.

**Comment by shikhamis11** [comment] 2019-10-17 07:04
@darshankhatri16 thank you for reporting this issue can you set proper title for the issue ?

**Comment by darshankhatri16** [comment] 2019-10-17 07:36
@shikhamis11 Sure. Done.

**Comment by engcom-Charlie** [comment] 2019-11-12 13:33
Hello @darshankhatri16 

We are not able to reproduce this issue on the latest 2.3-develop branch by provided steps.

**Testing scenario:**
 Pass extra values in header apart from authorization token

**Result:**
Allowed passed extra values in the header:
![image](https://user-images.githubusercontent.com/51680850/68675856-6e606880-0561-11ea-96b3-2c29325b42c7.png)

So i have to close this issue. 

If you still faced this issue on `2.3-develop` please create a new Issue with all required details

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-11-12 13:33 UTC
Labels: Issue: Format is valid
