### ISSUE TITLE
Error when bin/magento when upgrading from Magento 2.4.5-p2 to Magnto 2.4.6

### ISSUE THREAD

**Issue by tashil-lucrin** [magento/magento2#37536] opened 2023-05-24 19:09 UTC
### Summary

We did an upgrade from Magento 2.4.5-p2 to Magento 2.4.6 

PHP Fatal error:  Declaration of Magento\Setup\Mvc\Bootstrap\InitParamListener::__invoke(Interop\Container\ContainerInterface $container, $requestedName, ?array $options = null) must be compatible with Laminas\ServiceManager\Factory\FactoryInterface::__invoke(Psr\Container\ContainerInterface $container, string $requestedName, ?array $options = null): mixed in /setup/src/Magento/Setup/Mvc/Bootstrap/InitParamListener.php on line 111

Fatal error: Declaration of Magento\Setup\Mvc\Bootstrap\InitParamListener::__invoke(Interop\Container\ContainerInterface $container, $requestedName, ?array $options = null) must be compatible with Laminas\ServiceManager\Factory\FactoryInterface::__invoke(Psr\Container\ContainerInterface $container, string $requestedName, ?array $options = null): mixed in /setup/src/Magento/Setup/Mvc/Bootstrap/InitParamListener.php on line 111

### Examples

Please find Composer file below. We believe the problem is with the composer file

{
    "name": "magento/project-enterprise-edition",
    "description": "eCommerce Platform for Growth (Enterprise Edition)",
    "type": "project",
    "license": [
        "proprietary"
    ],
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "magento/magento-composer-installer": true,
            "laminas/laminas-dependency-plugin": true,
            "magento/inventory-composer-installer": true,
            "magento/composer-dependency-version-audit-plugin": true,
            "dealerdirect/phpcodesniffer-composer-installer": true,
            "magento/composer-root-update-plugin": true
        }
    },
    "require": {
        "algolia/algoliasearch-magento-2": "3.10.0",
        "celigo/magento2-netsuite-connector": "^1.4",
        "classyllama/module-zendesk": "^1.1",
        "dompdf/dompdf": "^2.0.0",
        "google/apiclient": "^2.0",
        "laminas/laminas-log": "2.17.x-dev",
        "laminas/laminas-serializer": "2.15.x-dev",
        "magefan/module-community": "^2.0",
        "magefan/module-convert-guest-to-customer": "2.0.19",
        "magefan/module-geoip": "dev-master",
        "magefan/module-login-as-customer": "dev-master",
        "magento/composer-dependency-version-audit-plugin": "~0.1",
        "magento/composer-root-update-plugin": "^2.0",
        "magento/product-enterprise-edition": "^2.4",
        "mageplaza/module-core": "dev-master",
        "meetanshi/magento-2-google-analytics-4": "^1.0",
        "mgtcommerce/module-mgtdevelopertoolbar": "^1.0",
        "picqer/php-barcode-generator": "^2.0.1",
        "stripe/stripe-php": "^7",
        "tnw/salesforce": "2.10.8",
        "tnw/sforcecustomergroup": "2.10.2",
        "tnw/sforceenterprise": "2.10.15",
        "tnw/sforcetierprice": "2.10.2",
        "tnw/soap-client": "2.1.1"
    },
    "require-dev": {
        "allure-framework/allure-phpunit": "^2",
        "dealerdirect/phpcodesniffer-composer-installer": "^0.7",
        "dg/bypass-finals": "^1.4",
        "friendsofphp/php-cs-fixer": "^3.8",
        "lusitanian/oauth": "^0.8",
        "magento/magento2-functional-testing-framework": "^4.2.1",
        "pdepend/pdepend": "^2.12",
        "phpmd/phpmd": "^2.13",
        "phpstan/phpstan": "^1.9",
        "phpunit/phpunit": "^9.5",
        "sebastian/phpcpd": "^6.0",
        "squizlabs/php_codesniffer": "^3.6",
        "symfony/finder": "^5.4"
    },
    "conflict": {
        "gene/bluefoot": "*"
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": [
                "app/code/",
                "generated/code/"
            ]
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "version": "2.3.1",
    "minimum-stability": "dev",
    "repositories": {
        "powersync": {
            "type": "composer",
            "url": "https://dist.powersync.biz"
        },
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        "magefan": {
            "type": "composer",
            "url": "https://magefan.com/repo/"
        }
    },
    "extra": {
        "magento-force": "override"
    }
}

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by tashil-lucrin** [comment] 2023-05-25 03:59
I have been able to run magento by setting "laminas/laminas-servicemanager" to 3.16.0 in composer.json. 
The newer version is causing issues to deploy magento 2.4.6

**Comment by engcom-Bravo** [comment] 2023-05-25 13:16
Hi @tashil-lucrin,

Thank you for reporting and collaboration.

Verified the issue while upgrading from Magento 2.4.5-p2 to Magento 2.4.6(latest version) we are not able to reproduce the issue.Kindly refer the screenshots.


<img width="1299" alt="Screenshot 2023-05-25 at 2 22 21 PM" src="https://github.com/magento/magento2/assets/51680745/9cec94d1-50ee-4aec-8452-5c483f58bd98">



<img width="1465" alt="Screenshot 2023-05-25 at 2 16 23 PM" src="https://github.com/magento/magento2/assets/51680745/e83c42a3-b431-4e7d-95fc-f92573fa4ae7">


<img width="1452" alt="Screenshot 2023-05-25 at 2 21 39 PM" src="https://github.com/magento/magento2/assets/51680745/cbbe9bdc-847d-4c40-9391-760a30ab3f53">


Please refer the upgrade document https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/implementation/perform-upgrade.html and recheck the issue while upgrading from 2.4.5-p2 to 2.4.6.

Thanks.

**Comment by tashil-lucrin** [comment] 2023-05-29 09:41
could you kindly tell me the version of laminas service manager that you are using ?

**Comment by engcom-Bravo** [comment] 2023-05-30 13:28
Hi @tashil-lucrin,

Thanks for your update.

We are using **laminas/laminas-servicemanager** version `3.19.0` in composer.json.


<img width="819" alt="Screenshot 2023-05-30 at 11 57 27 AM" src="https://github.com/magento/magento2/assets/51680745/b85ca127-3fae-4903-95c7-75a895e9370f">



Thanks

**Comment by engcom-Bravo** [comment] 2023-06-12 06:31
Hi @tashil-lucrin,

Please provide us latest update https://github.com/magento/magento2/issues/37536#issuecomment-1568438019 are you able upgraded successfully form Magento 2.4.5-p2 to 2.4.6.Please let us know if you are still facing any issue.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-06-23 05:59
Hi @tashil-lucrin,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-06-23 05:59 UTC
Labels: Issue: needs update, Reported on 2.4.6
