### ISSUE TITLE
MSI - products not in the default stock are not updating stock status 

### ISSUE THREAD

**Issue by heerdt** [magento/magento2#38569] opened 2024-04-02 17:15 UTC
### Preconditions and environment

- Magento version 2.4-develop

### Steps to reproduce

1. Create at least one additional custom stock source
2. Create a new stock associated to the website
3. Associate the custom sources to the new stock
4. Create or edit a product, assigning its stock only to the new source
![image](https://github.com/magento/magento2/assets/819013/a145dfe3-12f9-4596-b108-9027af16d696)
5. Reindex, clear cache if needed
6. Check the product in the storefront

### Expected result

1. Product shows "In Stock"
2. Add to cart button is enabled
3. Can complete an order

### Actual result

1. Product shows "Out Stock"
2. Not able to add to cart
![image](https://github.com/magento/magento2/assets/819013/aff318bd-bf59-48a8-8db2-5fa0a3b8de49)

### Additional information

Table `inventory_stock_2` is not updated after saving the product or reindexing the catalog/inventory, which result in the out of stock status. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by gabrieldagama** [comment] 2024-04-03 19:47
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2024-04-04 09:51
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2024-04-04 10:27
Hi @heerdt 

Thanks for reporting and collaboration.

Verified the issue in magento 2.4 dev instance and the issue is not reproducible.

Steps to reproduce

1. Create at least one additional custom stock source
2. Create a new stock associated to the website
3. Associate the custom sources to the new stock
4. Create or edit a product, assigning its stock only to the new source
5. Reindex, clear cache if needed
6. Check the product in the storefront

We are able to see the product on storefront.

Please refer the attached screenshot. Let us know if we missed anything.

<img width="1440" alt="Screenshot 2024-04-04 at 3 51 38 PM" src="https://github.com/magento/magento2/assets/60198592/c9d6a3e6-ad0b-431a-80a8-29e89a155117">

<img width="1440" alt="Screenshot 2024-04-04 at 3 40 34 PM" src="https://github.com/magento/magento2/assets/60198592/85492a50-1bd9-42a0-a706-f2f1adc8e730">


<img width="1440" alt="Screenshot 2024-04-04 at 3 56 19 PM" src="https://github.com/magento/magento2/assets/60198592/989d04db-7b21-4efa-bede-d016755e7b2a">

**Comment by heerdt** [comment] 2024-04-04 10:31
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2024-04-15 10:10
Hi @heerdt 

We have noticed that this issue has not been updated for long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel free to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2024-04-15 10:10 UTC
Labels: Issue: needs update, Reported on 2.4.x
