### ISSUE TITLE
Cannot change price in Update Attribute when currency symbol is changed to USD or CAD

### ISSUE THREAD

**Issue by asadyar** [magento/magento2#8570] opened 2017-02-15 19:37 UTC
Cannot change price in Update Attribute when currency symbol is changed to USD$ or CAD$ tested this issue with Magento 2.1.3 and 2.1.4 both has this issue.

### Preconditions
1. Change Currency Symbols to USD$ or CAD $ or CA$ in Stores > Currency > Currency Symbols

### Steps to reproduce
2. Products > Inventory > Catalog
3. Select few product for which you want to change price and special price.
e.g. Magento 2.1.4 Sample data select Attribute set "TOP" SKU MH-01 select all 16 products
4. Click on "Update attributes"
5. Change "Price" or Change "Special Price" System will not let you to enter price or give the cursor

### Expected result
1. System should allow to input the value, Currency symbols are overlapping on the input field.
![bug-m2-1](https://cloud.githubusercontent.com/assets/5817658/22991932/03ababc4-f38c-11e6-9dc0-180e885c6c5f.png)
![bug-m2-2](https://cloud.githubusercontent.com/assets/5817658/22991933/03ad82aa-f38c-11e6-9248-dbe32877959a.png)
![bug-m2-3](https://cloud.githubusercontent.com/assets/5817658/22991934/03b38cb8-f38c-11e6-90ef-3fc94e59b267.png)

**Comment by asadyar** [comment] 2017-02-15 19:44
Experienced the same in Google Chrome and Firefox.

**Comment by andreame** [comment] 2017-02-17 00:12
also with EUR, same issue on Magento 2.1.4

**Comment by onepack** [comment] 2017-03-10 22:06
It's a styling issue. You can actually change the price but it is not visible as it is behind the currency symbol text with background #fff.

The next line should have an addition to fix it in the admin less file.
vendor\magento\theme-adminhtml-backend\web\css\styles-old.less
line #1676
Changing:

            &:focus ~ .addafter {
                border-color: #007bdb;

                strong {
                    margin-top: 0;
                }
            }

to

            &:focus ~ .addafter {
                border-color: #007bdb;

                strong {
                    display: none;
                }
            }


Css output:
.admin__scope-old .addon input[type="text"]:focus ~ .addafter strong {
    display: none;
}

I'm not sure if the margin-top:0 is still needed because "focus + display: none" will make this irrelevant.

Greetings,

OnePack

**Comment by onepack** [comment] 2017-03-10 22:15
I can confirm that this adjustment will solve the issue of the price not being visible. Just tested on Magento 2.1.5

**Comment by AlexWorking** [comment] 2017-07-04 08:54
Hello, @asadyar. Based on Your issue an internal ticked MAGETWO-70443 has been created. You'll be informed as the issue is resolved. Thanks for applying.

**Comment by ShapesGraphicStudio** [comment] 2017-09-29 13:44
Still not fixed in 2.1.9.

**Comment by magento-engcom-team** [comment] 2017-10-05 08:30
@asadyar, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-05 08:30 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is not valid
