### ISSUE TITLE
Store configuration loaded multiple times in Currencysymbol class

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#37929] opened 2023-08-29 06:27 UTC
### Preconditions and environment

- All Magento 2 versions
- Multistore Configuration, blackfire for profiling, REDIS for cache

### Steps to reproduce

1. Create 15 store views, each with different currency
2. Connect REDIS

Here is a detailed explanation of the issue:
When `Currencysymbol` class is created during `__construct` a property `_systemStore` is being assigned a systemStore.
Because it is not passed by `StoreManagerInterface` the entire store configuration is being loaded again in the `reload()` method in the `Store.php` class - as the object is initiated 

It is causing the additional calls to REDIS on every `default.phtml` price rendered multiplied by number of allowed stores and currencies
![image](https://github.com/magento/magento2/assets/4256191/a03145f6-0b27-4764-b68e-eac32d666bd9)

The problem is the fact that the method `getCurrencyOptions` in `CurrencyDisplayOptions` class is creating a new object for each price render basically creating a huge bottle neck in the code.  

### Expected result

One of 2 options:

1. Symbol factory class should be created once.
``` $customCurrencySymbol = $this->symbolFactory->create()->getCurrencySymbol($baseCode); ``` this code is executed on every single price render 
2. `CurrencySymbol` class should use StoreManagerInterface so the store configuration is not reloaded on every single page load

### Actual result

17-20ms extra load on every single price render
![image](https://github.com/magento/magento2/assets/4256191/2ff44117-1f8f-435e-8af2-03178a2060d5)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2023-09-12 08:35
Hello @qsolutions-pl,

Thanks for the report and collaboration!

We have tried to reproduce the issue in the Magento 2.4-develop branch with PHP-SPX profiling but for us it seems the issue is not reproducible. Please have a look at our findings:

- Redis is enabled for this Magento instance
- Tried to access the PDP from strorefront
- Please have a look into the below screenshot from PHP-SPX profiler

![image](https://github.com/magento/magento2/assets/51681618/0b793139-30c8-44a9-b4f9-4efb6bce5bad)

according to the profiler `Proxy::Dispatch` method has been called only once.

Please let us know in case we have missed anything.

Thanks

**Comment by qsolutions-pl** [comment] 2023-09-12 11:48
I cannot replicate this issue anymore, thank you for checking.
I think we can close this one.

**Closed as completed by qsolutions-pl** 2023-09-12 11:48 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.x
