### ISSUE TITLE
FPC disable - Customer messages not working

### ISSUE THREAD

**Issue by fchalet69** [magento/magento2#5343] opened 2016-06-29 11:33 UTC
## Steps to reproduce
1. Install Magento 2.0.7
2. Go to back office and disable full page cache
3. Clear your site cookies
4. Create an account
## Expected result
1. Success message ("Thank you for registering with ...") appear
## Actual result
1. Message is missing (same if in case of error, e.g account already exist)
2. If you add a product for exemple, then you have the success message of product added and the registration succes message
## Notes

It seems to affect other ajax loading, like the mini shopping cart (add a product -> log in -> add product, log out).
For the customer case it maybe related to the customer-data.js wich look for a 'private_content_version' cookie. This cookie is only set with FPC enable.

Best regards,
Fabien.

**Comment by sevos1984** [comment] 2016-09-01 15:51
This should be fixed in 2.0.8, have you tried updating your code base?

**Comment by sevos1984** [comment] 2016-09-29 09:56
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-09-29 09:56 UTC
Labels: bug report, Progress: needs update, Component: Framework/Cache, Component: Customer
