### ISSUE TITLE
migrateDataFromAnotherTable() does not work for declarative schema

### ISSUE THREAD

**Issue by DmitryFurs** [magento/magento2#34394] opened 2021-10-20 15:31 UTC
### Preconditions
1. Magneto Community Edition 2.4.3-p1

### Steps to reproduce
1. Create a table using a declarative schema
2. run setup:upgrade
3. Add rows to the created table
4. Rename the table using migrateDataFromAnotherTable() in the declarative schema
5. run setup:upgrade again

### Expected result
1. Table with a new name has been created
2. Data from the table with the previous name is copied to the table with the new name

### Actual result
1. Table with a new name has been created
2. Data is not copied to the new table

### Additional Info

During the investigation, it was found that the **vertexinc/module-tax** module was installed together with Magneto. 

This module adds its own trigger to create a table in a declarative schema
![image](https://user-images.githubusercontent.com/1055999/138123418-6568e6ff-97df-4c7f-8b1f-5e51195bd665.png)

When you breakpoint in the [Magento\Framework\Setup\Declaration\Schema\Operations\CreateTable](https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/lib/internal/Magento/Framework/Setup/Declaration/Schema/Operations/CreateTable.php#L50) class, you can see that the trigger added in [app/etc/di.xml](**url**) is missing from the list of added ones, and there is only vertexinc present there
![image](https://user-images.githubusercontent.com/1055999/138123512-8cede5d6-53cd-4cef-8a1b-d70a54df900d.png)

After vertexinc was commented out
![image](https://user-images.githubusercontent.com/1055999/138123216-5a7e5f1d-792d-41c5-94f2-2e8c2f057f24.png)

and the setup:upgrade started again, vertexinc disappeared and migrateDataFromAnotherTable appeared
![image](https://user-images.githubusercontent.com/1055999/138123313-49bbc377-86cc-47a9-8d7c-2a8cbfd88588.png)

After the setup:upgrade was completed, the rows were copied to the new table.

Most likely the reason lies somewhere in the merger [app/etc/di.xml](https://github.com/magento/magento2/blob/2.4-develop/app/etc/di.xml#L1762) and others **di.xml** files, in our case it is **vendor/vertexinc/module-tax/etc/di.xml**

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ilnytskyi** [comment] 2021-11-04 07:43
Faced similar issue, when wanted to add new items in different area
https://github.com/magento/magento2/issues/34464

**Comment by DmitryFurs** [comment] 2022-02-22 05:57
Is there any news here? Thanks!

**Comment by engcom-Delta** [comment] 2022-09-19 13:33
Hi @DmitryFurs,

We have tried to reproduce this issue in 2.4-develop but for us, it is not reproducible.

We have followed below steps

1.Created catalogproducts table using a declarative schema
<img width="385" alt="Screenshot 2022-09-19 at 4 03 10 PM" src="https://user-images.githubusercontent.com/51681379/190999381-c4ddad11-4d60-4fd2-b16d-9cc6cc477992.png">

2.Added rows to the catalogproducts table.
<img width="478" alt="Screenshot 2022-09-19 at 4 07 17 PM" src="https://user-images.githubusercontent.com/51681379/190999900-65c1c9f7-dc8a-4ab5-9c35-bb057c45c39c.png">

3.Rename the table using migrateDataFromAnotherTable() as catalogproducts1
<img width="939" alt="Screenshot 2022-09-19 at 4 08 47 PM" src="https://user-images.githubusercontent.com/51681379/191000132-b6ed735a-da8e-4bcd-b299-7a973cb6fd34.png">

4. Table with new name is created and the data are copied to renamed table.  
<img width="428" alt="Screenshot 2022-09-19 at 4 09 40 PM" src="https://user-images.githubusercontent.com/51681379/191000287-bf815810-c73f-4700-8ed1-26cd77de9bfd.png">

Please let us know if we are missing any steps here. 

Thanks.

**Comment by navarr** [comment] 2022-09-19 14:11
@engcom-Delta The removal of VBEs resolved the symptom of the issue.

The real issue is the way di.xml is merged between the global app/etc/di.xml and module di.xmls (with module di.xml's replacing, instead of expanding, entries in app/etc/di.xml).

When this issue was created, Vertex added a schema trigger.  Any module that does so will overwrite core schema triggers - which is not desirable.

**Comment by DmitryFurs** [comment] 2022-09-19 17:53
@engcom-Delta Yes, @navarr is right, the problem is that you can't add your own triggers. When merging from different areas, native triggers will be overridden, even if they have other unique names.

**Comment by engcom-Delta** [comment] 2022-09-20 09:36
@DmitryFurs ,@navarr
We have tried to reproduce this issue in magento 2.4-develop still this issue is not reproducible with merging of di.xml files. In below document vertex is not bundled extension in latest versions. 
https://docs.magento.com/user-guide/tax/taxes.html
<img width="995" alt="Screenshot 2022-09-20 at 2 43 11 PM" src="https://user-images.githubusercontent.com/51681379/191218568-00e97493-1fc1-4f68-91a4-77c39159563b.png">
Please let us know if we are missed anything.
Thanks.

**Comment by DmitryFurs** [comment] 2022-09-20 18:54
@engcom-Delta What should we do if we need to install the vertex module or any other that adds its own triggers? If this module is installed, the problem will reappear. How to fix the situation?

**Comment by engcom-Hotel** [comment] 2022-11-02 10:39
Hello @DmitryFurs @navarr,

We have tried to reproduce this issue in the Magento 2.4-develop as well as 2.4.5 by creating a custom module to create a table. We have followed the below steps with and without the Vertex module installed:

1. Creating a module to create a table.
2. Run `bin/magento setup:db-declaration:generate-whitelist --module-name=Magz_Issue34394` command
3. and then `bin/magento s:up`

With the Vertex module, we have the new table created but no data copied from the existing table but without that module the data is also copied.

We need to fix the way in which di.xml merges. So the issue seems in the Magento module. Hence confirming the issue.

Thanks

**Comment by engcom-Hotel** [comment] 2022-11-24 13:22
Hello @DmitryFurs @navarr,

We have discussed this issue with developers internally and come to the below conclusion:

As per the analysis for the issue, the `vertexinc/vertex-tax-module:4.2.8` `di.xml` is an area-specific configuration, and the app/etc/di.xml is the initial one. As per devdocs the area-specific config will override the initial one so this is expected behavior. we can check further [Here](https://developer.adobe.com/commerce/php/development/build/dependency-injection-file/).

We have one different example as well to demonstrate the expected behavior of DI.
vendor/magento/module-customer/etc/di.xml
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/51681618/203793928-3a818f8a-f4ba-4eb0-a551-ade43703ba94.png">

app/etc/di.xml
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/51681618/203794036-75d51ac3-38bb-4344-95d7-ea0fd4b92cd2.png">
<img width="515" alt="image" src="https://user-images.githubusercontent.com/51681618/203794605-fd0564ae-128e-45b5-b675-32f3702bfb8e.png">

The module-specific configuration will override the same expected behavior.

Thanks

**Comment by navarr** [comment] 2022-11-24 13:39
@engcom-Hotel I think everyone in this thread understands that's the expected behavior of XML merge as it exists today

However, I think the point of the ticket is that database triggers especially should not be disappear if a module tries to add one

This has two potential solutions to that regard:

* Merge initial and area configuration instead of overwriting
* Or Magento needs to host important configuration in an area configuration file

Personally, I've never understood why app/etc/di.xml exists or is treated differently.

**Comment by DmitryFurs** [comment] 2022-12-01 12:26
@engcom-Hotel I completely agree with @navarr

**Comment by engcom-Hotel** [comment] 2022-12-01 13:36
Hello @navarr @DmitryFurs,

We are under discussion on this issue internally. Will keep you posted on this soon.

Thanks

**Comment by engcom-Hotel** [comment] 2022-12-12 05:21
Moving this ticket "On hold"

**Closed as completed** 2023-09-28 01:16 UTC
Labels: Component: Bundled Extension, Triage: Dev.Experience, Reproduced on 2.4.x, Severity: S2, Priority: P1, Progress: done, Issue: On Hold, Issue: needs update, Area: Framework

**Comment by ihor-sviziev** [comment] 2023-09-28 07:18
@engcom-Hotel @engcom-Echo any updates? Why task was closed w/o any comments?

**Comment by engcom-Bravo** [comment] 2023-09-28 12:05
Hi @ihor-sviziev @DmitryFurs,

As per the Internal team they are not able to reproduce the issue hence they have closed jira form their side.

Thanks.

**Comment by navarr** [comment] 2023-09-28 13:01
Were there any changes made to the way di.xml entries are loaded, or did internal just give up on fixing this architectural issue?
