### ISSUE TITLE
Adding product to compare doesn't work. 

### ISSUE THREAD

**Issue by moe-kayali** [magento/magento2#4037] opened 2016-04-06 15:38 UTC
## Steps to reproduce
1. Install Magento 2.0.4 with sample data.
2. Add product to compare.
3. Navigate to the category page to be able to check the compare list.  
## Expected result
1. Confirmation message "You added product X to the comparison list" should appear.
2. The product should be added to the compare list on the side menu under the layered navigation within the category page.
## Actual result
1. The confirmation message doesn't appear. 
2. The product doesn't appear on the compare list. It shows that "You have no items to compare".

![compare 1](https://cloud.githubusercontent.com/assets/12815266/14322432/922ce192-fc25-11e5-9ec8-092a648260ee.gif)

**Comment by piotrekkaminski** [comment] 2016-05-27 20:35
internal issue MAGETWO-53568

**Comment by antboiko** [comment] 2016-06-13 15:16
Hi @moe-kayali , we cannot reproduce the issue on 2.0.4. I'm closing this ticket. Please feel free to reopen it if needed.

Best,
Anton.

**Closed as completed by antboiko** 2016-06-13 15:16 UTC
Labels: bug report

**Comment by lucasng13** [comment] 2016-06-15 09:58
Hi @antboiko, you should clear all caches, session both browsers and Magento to test it. I had the same problem after I installed Magento 2.0.7 with sample data.
Compare function just works after I added a product to cart.
