### ISSUE TITLE
First partial invoice contains all ordered products, not only invoiced ones [CE 2.1.5]

### ISSUE THREAD

**Issue by lfritsche** [magento/magento2#11408] opened 2017-10-12 20:36 UTC
### Preconditions

1. Magento CE 2.1.5
2. PHP 7

### Steps to reproduce

1. Create Order with 1x simple product & 1 configurable product 
2. Create invoice separately for each product
3. Get invoiced items programmatically

### Expected result

1. first invoice id should return the simple product only
2. second invoice id should return the configurable and the corresponding simple product.

### Actual result

1. first invoice id returns all ordered products (SELECT * FROM `sales_invoice_item` WHERE `parent_id` = '#first id')
2. second invoice id returns the invoiced items correctly.
3. Backend shows the items correctly. The issue is visible only, if I fetch the data directly.

**Comment by magento-engcom-team** [comment] 2017-10-13 07:06
Hi @lfritsche 
Thanks for reporting this issue.
Please share the code that appear, how do you get order items from invoice.

**Comment by lfritsche** [comment] 2017-10-13 21:57
Hi!

I think it's not about the get order items code itself. It's more about invoice items db info:

Ordered Items:
![image](https://user-images.githubusercontent.com/15127451/31567705-1c621958-b071-11e7-8123-0fa16e9deee9.png)

Two invoices / one per product:
![image](https://user-images.githubusercontent.com/15127451/31567748-3fa51eb0-b071-11e7-828b-87efc06f44de.png)

First Invoice (simple product) ...1109
![image](https://user-images.githubusercontent.com/15127451/31567794-73bb5336-b071-11e7-8b9f-5bb2a037d084.png)
Second Invoice (config. product) ...1110
![image](https://user-images.githubusercontent.com/15127451/31567821-96a52fac-b071-11e7-8c7d-e0f931115be6.png)

DB Query for invoice 1109: (issue: all ordered products)
```SELECT entity_id, parent_id, base_price, product_id, order_item_id, sku  FROM `sales_invoice_item` WHERE `parent_id` = '1109'```
![image](https://user-images.githubusercontent.com/15127451/31567919-0f31a572-b072-11e7-8ede-e0ad4dab4775.png)

DB Query for invoice 1110: (only correct invoiced item)
```SELECT entity_id, parent_id, base_price, product_id, order_item_id, sku  FROM `sales_invoice_item` WHERE `parent_id` = '1110'```
![image](https://user-images.githubusercontent.com/15127451/31567938-27fa7246-b072-11e7-97e2-d7e26f95c111.png)

**Comment by magento-engcom-team** [comment] 2017-10-18 07:30
@lfritsche, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-18 07:30 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid

**Comment by lfritsche** [comment] 2017-10-18 10:05
That's great. Could you provide the specific commit(s) for me to patch them manually?
Thank you!

**Comment by lfritsche** [comment] 2017-10-23 02:11
@magento-engcom-team could you please reference to the commits fixing this issue?
Thank you!

**Comment by LovelySetia** [comment] 2018-09-13 12:41
How to create partial invoice in magento-2.1.12?
