### ISSUE TITLE
Improve query speed archiving orders/ shipment / invoices / creditmemo

### ISSUE THREAD

**Issue by leonhelmus** [magento/magento2#35621] opened 2022-06-15 13:31 UTC
### Preconditions and environment

- Magento version: 2.4.3-p1
- Php: 7.4
- Magento Commerce
- Enabled sales/magento_salesarchive/active
- Enable dev/grid/async_indexing

### Steps to reproduce

1. Have a big dataset of orders/invoices/shipments/creditmemos.
2. Run cron sales_grid_order_async_insert or sales_grid_order_invoice_async_insert or sales_grid_order_shipment_async_insert or sales_grid_order_creditmemo_async_insert

### Expected result

The class \Magento\Sales\Model\ResourceModel\Provider\UpdatedIdListProvider will check both sales_order_grid as magento_sales_order_grid_archive when checking if any orders/shipments/invoices/creditmemo are missing in the grid in one query. 

### Actual result

The class \Magento\Sales\Model\ResourceModel\Provider\UpdatedIdListProvider will check only sales_order_grid when checking if any orders/shipments/invoices/creditmemo are missing in the grid in one query. Which for my client results in 2.5m missing since the other order/shipments/invoices/creditmemos are stored in archive.

After it checks with a plugin in \Magento\SalesArchive\Plugin\ArchivedEntitiesProcessorPlugin if any of the previous results out of \Magento\Sales\Model\ResourceModel\Provider\UpdatedIdListProvider are available in the archive. For us this is a query that has in the `in` condition 2.5m ids... which is quite consuming for mysql.

this is the result of our mysql slow log:
Query_time: 17.552443  Lock_time: 0.000357  Rows_sent: 2328578  Rows_examined: 3354520  Rows_affected: 0
Bytes_sent: 26872258
SET timestamp=1653884608;
SELECT `sales_order`.`entity_id` FROM `sales_order`
 LEFT JOIN `sales_order_grid` ON sales_order.entity_id = sales_order_grid.entity_id WHERE (sales_order_grid.entity_id IS NULL);

Query_time: 4.163008  Lock_time: 1.425977  Rows_sent: 2028574  Rows_examined: 2028574  Rows_affected: 0
Bytes_sent: 26872252
SET timestamp=1653884627;
SELECT `magento_sales_order_grid_archive`.`entity_id` FROM `magento_sales_order_grid_archive` WHERE (magento_sales_order_grid_archive.entity_id IN ('2', '3', '350', '362', '363', '364', '365', '366', '367', '368', '369', '372', '373', '374', '375', '377', '380', '385', '388', '393', '401', '402', '413', '414', '416', '420', '421', '434', '442', '443', '445', '484', '509', '549', '563', '573', '600', '627', '628', '676', '680', '681', '715', '722', '797', '1060', '1129', etc 2.5m ids futher...

### Additional information

To resolve this i added the following patch:
```
# Improve speed query add order/shipment/invoice/creditmemo to archive.
#
# Github link:  

diff --git a/Model/ResourceModel/Provider/UpdatedIdListProvider.php b/Model/ResourceModel/Provider/UpdatedIdListProvider.php
--- a/Model/ResourceModel/Provider/UpdatedIdListProvider.php
+++ b/Model/ResourceModel/Provider/UpdatedIdListProvider.php

@@ -5,6 +5,7 @@
  */
 namespace Magento\Sales\Model\ResourceModel\Provider;

+use Magento\Framework\App\Config\ScopeConfigInterface;
 use Magento\Framework\App\ResourceConnection;
 use Magento\Framework\DB\Adapter\AdapterInterface;

@@ -22,15 +23,19 @@
      * @var AdapterInterface
      */
     private $connection;
+    private ScopeConfigInterface $scopeConfig;

     /**
      * NotSyncedDataProvider constructor.
      * @param ResourceConnection $resourceConnection
+     * @param ScopeConfigInterface $scopeConfig
      */
     public function __construct(
-        ResourceConnection $resourceConnection
+        ResourceConnection $resourceConnection,
+        ScopeConfigInterface $scopeConfig
     ) {
         $this->resourceConnection = $resourceConnection;
+        $this->scopeConfig        = $scopeConfig;
     }

     /**
@@ -52,8 +57,23 @@
                     'entity_id'
                 ),
                 []
-            )
-            ->where($gridTableName . '.entity_id IS NULL');
+            );
+        if ($this->scopeConfig->isSetFlag('sales/magento_salesarchive/active')) {
+            $archiveGridTableName = 'magento_' . $gridTableName . '_archive';
+            $select->joinLeft(
+                [$archiveGridTableName => $archiveGridTableName],
+                sprintf(
+                    '%s.%s = %s.%s',
+                    $mainTableName,
+                    'entity_id',
+                    $archiveGridTableName,
+                    'entity_id'
+                ),
+                []
+            )->where($gridTableName . '.entity_id IS NULL AND ' . $archiveGridTableName . '.entity_id IS NULL');
+        } else {
+            $select->where($gridTableName . '.entity_id IS NULL');
+        }

         return $this->getConnection()->fetchAll($select, [], \Zend_Db::FETCH_COLUMN);
     }

```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-01-19 07:20
Hi @leonhelmus,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.


Steps to Reproduce :

1.Enabled sales/magento_salesarchive/active
2.Enabled dev/grid/async_indexing 3. Have a big dataset of orders/invoices/shipments/creditmemos.4.Run cron sales_grid_order_async_insert or sales_grid_order_invoice_async_insert or sales_grid_order_shipment_async_insert or sales_grid_order_creditmemo_async_insert


<img width="769" alt="Screenshot 2023-01-19 at 12 21 16 PM" src="https://user-images.githubusercontent.com/51680745/213379522-8a0afd85-a54d-4bdb-8d5e-1bbcf64d34d0.png">



The class \Magento\Sales\Model\ResourceModel\Provider\UpdatedIdListProvider will check both sales_order_grid as magento_sales_order_grid_archive when checking if any orders/shipments/invoices/creditmemo are missing in the grid in one query.So issue is not getting reproducible to us.So please kindly check and let us know if we are missing any steps.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-01-30 06:14
Hi @leonhelmus,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-01-30 06:14 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.3-p1
