### ISSUE TITLE
BUG: Wrong selected product image when query url param configurable product

### ISSUE THREAD

**Issue by kylianleemkuil** [magento/magento2#26473] opened 2020-01-21 14:29 UTC
###  Summary of the issue (*)
In my webshop I have games and this games have different editions and a used and a new state.
Now I have one configurable product for example: "007 From Russia With Love" with a couple of simple products under it:

*(Attribute) System*
1. PlayStation 2
2. GameCube

*(Attribute) State*
1. New
2. Used

In my product listings I only show the configurable products but the product URL is changed to the specific system attribute in my condition it is: http://local.magento/007-from-russia-with-love.html#142=345 so it links to the specific simple product with that system already selected. 

The price and the selected system attribute is correct on the productpage only the product image is not selected for this simple product. It takes the default image of the configurable product.

### Preconditions (*)

1. Magento 2.3.3
2. MySQL 5.6.23
3. Ubuntu 16.04.5 LTS (Docker container: https://hub.docker.com/r/alexcheng/magento2/)
4. PHP 7.2.12

### Steps to reproduce (*)

1. Make a configurable product with a random image.
2. Make 2 simple products under it with 2 attributes System,State(See summary) and the simple products need different images.
3. Link to the productpage of the configurable product with # query like http://local.magento/007-from-russia-with-love.html#142=345 so that a system is already selected. Ofcourse change the '142' to your attribute super id and the '345' with a option of the attribute.
4. Check if it shows image of Configurable product or from simple product.

### Expected result (*)

1.  ![alt text](https://i.imgur.com/WLMl4Rd.png)

### Actual result (*)

1.  ![alt text](https://i.imgur.com/5iEkee3.png)

**Comment by engcom-Echo** [comment] 2020-01-23 08:27
Hi @kylianleemkuil. Thank you for your report.
Unfortunately, I could not reproduce this behavior.

Actual result: 

![image](https://user-images.githubusercontent.com/51681435/72967106-324f4c80-3dc9-11ea-9531-511c49eb7f9a.png)

![image](https://user-images.githubusercontent.com/51681435/72967131-42672c00-3dc9-11ea-892e-10d879c6f329.png)

![image](https://user-images.githubusercontent.com/51681435/72967156-57dc5600-3dc9-11ea-8e29-f31219f76b40.png)

![image](https://user-images.githubusercontent.com/51681435/72967178-662a7200-3dc9-11ea-8860-cac927ba7e94.png)

![image](https://user-images.githubusercontent.com/51681435/72967211-75a9bb00-3dc9-11ea-8cc5-306f24d0f462.png)

I have to close it.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by kylianleemkuil** [comment] 2020-01-23 08:33
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-01-23 08:33
Hi @kylianleemkuil. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-23 08:34
Hi @kylianleemkuil, here is your [Magento instance](https://i-26473-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26473-2-4-develop.instances.magento-community.engineering/admin_db97](https://i-26473-2-4-develop.instances.magento-community.engineering/admin_db97)
Login: `0f55a834` Password: `be97e6333acb`
Instance will be terminated in up to 3 hours.

**Comment by kylianleemkuil** [comment] 2020-01-23 09:06
@engcom-Echo I reproduced this bug on the 2.4 develop branch

**Result:**
![2 4-develop-bug](https://user-images.githubusercontent.com/17156823/72970142-42fec300-3dc7-11ea-9628-fdf914392b97.png)

As you can see if I use the # as param in the URL the Select field changes and the price also. But the product image is not changed. 

**This is how it supposed to work:**

![2 4-develop-suppose](https://user-images.githubusercontent.com/17156823/72970316-b0125880-3dc7-11ea-9769-5e09e4bd34de.png)


I noticed in Magento\ConfigurableProduct\view\frontend\web\js\configurable.js in function **_changeProductImage()** that "**galleryObject**" is not defined when using the # param.

Reopen please

**Comment by engcom-Echo** [comment] 2020-01-23 12:27
Hi, @kylianleemkuil. Thank you for the clarification.

**Comment by magento-engcom-team** [comment] 2020-01-23 12:28
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30688` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2020-03-19 04:55
Hi @kylianleemkuil. Thank you for your report. 
The issue has been fixed in magento/magento2#26560 by @sergiy-v in 2.4-develop branch
Related commit(s):
 - [54f93e22ae3d9387d5a8c259d6933efbcd5461e8](https://github.com/magento/magento2/commit/54f93e22ae3d9387d5a8c259d6933efbcd5461e8)

The fix will be available with the upcoming 2.4.0 release.

**Closed as completed by magento-engcom-team** 2020-03-19 04:55 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Issue: Format is valid, Component: ConfigurableProduct, Reproduced on 2.4.x, Fixed in 2.4.x, Reported on 2.3.3
