### ISSUE TITLE
Payment Method Filter

### ISSUE THREAD

**Issue by bernd-reindl** [magento/magento2#27038] opened 2020-02-26 16:39 UTC
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Create a customer with 2 Addresses. One for country A and one for country B
2. Configure payment method A for country A
3 .Configure payment method B for country B
4. Add a product to cart in frontend
5. Goto onepage checkout
6. Select address  A
7. Go to Payment step and select payment A and select "My billing and shipping address are the same"
8. Go back to shipping step
9. Select Address B
10. Go to payment step

### Expected result (*)

1. Payment method B is shown

### Actual result (*)

1. Payment method A is shown

This happens, because the payment mehtods are filtered by billing address. But the billing address is not set or maybe different from shipping address. Because of the fact, that the shipping address is selected in step 1, this address should be used to determin the available payment methods.

Magento\Payment\Model\Checks\CanUseForCountry\CountryProvider.php

```
public function getCountry(Quote $quote)
    {
        $address = $quote->getShippingAddress();
        return (!empty($address) && !empty($address->getCountry()))
            ? $address->getCountry()
            : $this->directoryHelper->getDefaultCountry();
    }
```

**Comment by bernd-reindl** [comment] 2020-02-27 11:02
How can i add such labels?

**Comment by AnnaShepa** [comment] 2020-02-27 13:12
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-27 13:12
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-27 13:12
Hi @AnnaShepa, here is your [Magento instance](https://i-27038-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27038-2-4-develop.instances.magento-community.engineering/admin_2e21](https://i-27038-2-4-develop.instances.magento-community.engineering/admin_2e21)
Login: `b8bf02b1` Password: `293a548a029a`
Instance will be terminated in up to 3 hours.

**Comment by AnnaShepa** [comment] 2020-02-27 13:41
I tried to reproduce and for me it looks like restriction by country doesn't work at all: I always can see all payment methods and one more strange things that after save "Payment from specific countries" displays like disabled, but " Use Default" is still unchecked
 
![Screenshot 2020-02-27 at 14 39 23](https://user-images.githubusercontent.com/24183408/75450524-4ad5f800-596f-11ea-82dc-45f5be5260a5.png)

**Comment by magento-engcom-team** [comment] 2020-02-27 13:43
@AnnaShepa Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2020-02-27 13:44
:white_check_mark: Confirmed by @AnnaShepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31965` were created

**Issue Available**: @AnnaShepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rogyar** [comment] 2020-02-29 15:14
Hi @bernd-reindl. Technically, the payment method per country restriction should be based on the billing address (as it is) not the shipping address. Payment may be allowed or disallowed for the country where you are processing the payment (and receiving the bill). That means billing address. In other words, the definition of location here is the place where you are performing the payment but not the place where you are going to deliver the order goods.

**Comment by bernd-reindl** [comment] 2020-03-02 06:52
Hi @rogyar . But then you have to select the billing address before the payment methods are shown, because you cannot filter the payment methods by billing address if the billing address is selected inside the payment methods.

Maybe set the billing address in step 1 instead of step 2?

**Comment by Rus0** [comment] 2020-04-05 01:39
Hey @bernd-reindl 

The payment methods are showing as they should be, you will need to set up the taxes to calculate from billing address:

Stores > Configuration > Sales > Tax > Calculation Settings > Tax Calculation Based On 

Set it up to billing address, even if you are not using taxes, I just tested it.

**Closed as completed by Rus0** 2020-04-05 01:39 UTC
Labels: Issue: Ready for Work, Component: Payment, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Reproduced on 2.4.x, Event: Global-Contribution-Day, Reported on 2.3.4
