### ISSUE TITLE
Terms and Conditions validation not working on Braintree Creditcard payment

### ISSUE THREAD

**Issue by bst2002git** [magento/magento2#25672] opened 2019-11-20 16:16 UTC
### Preconditions (*)
Magento 2.3.3 or 2.3-develop
Simple product is created.
Condition in Terms and Conditions is created and enabled. 

### Steps to reproduce (*)

1. Activate Braintree Creditcard with 3D Secure enabled
2. Make a checkout
3. Select Braintree-Creditcard payment 
4. Don`t mark "Terms and Conditions" checkbox
4. Click "Place Order" button

### Expected result (*)
Should alert that mandatory Terms and Conditions are not checked before Submit and get the 3D Secure-Popup

### Actual result (*)
![magento_2 3 3_braintree_creditcard_payment](https://user-images.githubusercontent.com/10232785/69255906-e6114180-0bb8-11ea-8217-e80c01b7a200.jpg)
After continuing 3D Secure with Password and press Submit i get (picture below) 
![braintree_magento_native_onepage_checkout_after_3ds_password](https://user-images.githubusercontent.com/10232785/69255917-e90c3200-0bb8-11ea-8e30-669325c4f047.jpg)

**Comment by bst2002git** [comment] 2019-11-20 16:25
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-20 16:26
Hi @bst2002git. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-20 16:26
Hi @bst2002git, here is your [Magento instance](https://i-25672-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25672-2-3-develop.instances.magento-community.engineering/admin](https://i-25672-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by bst2002git** [comment] 2019-11-20 16:57
Same Issue as Magento 2.3.3, see Pictures
![magento_2 3 3_vanilla_braintree_creditcard_payment](https://user-images.githubusercontent.com/10232785/69259825-28d61800-0bbf-11ea-9503-61c766406035.jpg)
![braintree_magento_vanilla_onepage_checkout_after_3ds_password](https://user-images.githubusercontent.com/10232785/69259837-2bd10880-0bbf-11ea-8144-c91bd1f22ce7.jpg)

**Comment by engcom-Echo** [comment] 2019-11-21 09:49
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-21 09:49
Hi @engcom-Echo. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-21 09:50
Hi @engcom-Echo, here is your [Magento instance](https://i-25672-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25672-2-3-develop.instances.magento-community.engineering/admin](https://i-25672-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-11-21 10:46
@engcom-Echo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-11-21 10:46
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29039` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by muratbinerbay** [comment] 2020-02-19 17:04
I think is an issue for PayPal payments through Braintree too.

**Preconditions (*)**
Magento 2.3.3 or 2.3-develop
Simple product is created.
Condition in Terms and Conditions is created and enabled.

**Steps to reproduce (*)**
Activate Braintree Paypal
Make a checkout
Don`t mark "Terms and Conditions" checkbox
Select Braintree Paypal payment
Click "Place Order" button

**Expected result (*)**
Should alert that mandatory Terms and Conditions are not checked and not show PayPal pop-up

**Actual result (*)**
PayPal pop-up is shown where user can confirm payment on PayPal. The order does not succeed on the Magento side as the `default.js` under `magento-checkout` module calls `additionalValidators.validate()`

**Comment by adam-paterson** [comment] 2020-10-02 12:22
@magento give me 2.3.5-develop instance

**Comment by adam-paterson** [comment] 2020-10-02 12:23
@magento give me 2.3-develop instance

**Comment by engcom-Delta** [comment] 2020-10-19 13:58
@muratbinerbay thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop and on the latest composer version 2.4.1
**Result:**
Alert that Terms and Conditions are not checked and PayPal pop-up is not shown
- 2.4.1
![#25672Issue](https://user-images.githubusercontent.com/51681379/96460692-24313e00-122c-11eb-9648-d894d1345613.png)

- 2.4-develop with Credit Card (Payflow Pro)
![#25672IssuePaypal](https://user-images.githubusercontent.com/51681379/96460699-285d5b80-122c-11eb-9d77-ddb3f42c2306.png)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Delta** 2020-10-19 13:58 UTC
Labels: Issue: Ready for Work, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Braintree, Progress: done

**Comment by magento-engcom-team** [comment] 2021-02-18 10:04
Hi @bst2002git, @engcom-Delta. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-29039` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.
