### ISSUE TITLE
Product price of a configurable product is mismatched on a product detail's page of a store using a non-default currency

### ISSUE THREAD

**Issue by crdt** [magento/magento2#9289] opened 2017-04-18 08:25 UTC
### Preconditions

1. Magento CE 2.1.+, PHP 7

### Steps to reproduce

1. You have a multistore with stores using different currencies.
2. You have a configurable product consisting of simple products containing attributes (eg. color).
3. Visit a frontend of a store using a non default currency and go to a product detail's page.

### Expected result

1. The product detail's price should be the same as the product has on category list (equal to the product's price without selected attributes).

### Actual result

1. The product detail's price remains mismatched until some product attribute is selected.

**Comment by smoskaluk** [comment] 2017-06-27 08:41
Internal ticket MAGETWO-70297 is created

**Comment by magento-engcom-team** [comment] 2017-10-04 13:30
@crdt, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-04 13:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Tax, Issue: Clear Description, Issue: Format is valid
