### ISSUE TITLE
API SOAP default scopeId doesn't work

### ISSUE THREAD

**Issue by MaximKitsenko** [magento/magento2#7605] opened 2016-11-29 10:47 UTC
When i call catalogInventoryStockRegistryV1GetLowStockItems for magento 2.1.1
and use scope=1 i receive empty list. But when i used scope=0 i receive the list of items with stockId=1;

When i call catalogInventoryStockRegistryV1GetLowStockItems for magento 2.0.2
and use scope=0 i receive empty list. But when i used scope=1 i receive the list of items with stockId=1;

Db and config for both stores are the same but soap response is different. Which scopeId should i use to receive all inventory for the root scope?

the problem is actual not only for these 2 versions but for all 2.0.x versions and 2.1.x

### Preconditions

1. SOAP, Magento 2-1-1
2. SOAP, Magento 2-0-2
3. `core_config_data`.`scope_id`  contains _0_ for all records for both stores.
`core_config_data`.`scope`  contains _default_ for all records for both stores.
4. ![chrome_2016-11-29_13-34-40](https://cloud.githubusercontent.com/assets/4807486/20706555/e98bd268-b638-11e6-9ba0-60bfb2c99a7a.png)
![chrome_2016-11-29_13-35-31](https://cloud.githubusercontent.com/assets/4807486/20706554/e98b1616-b638-11e6-989e-dcc6d6215500.png)

### Steps to reproduce

1. Request :`<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
	<s:Body>
		<catalogInventoryStockRegistryV1GetLowStockItemsRequest xmlns="http://youmagentohost/magento-2-1-1-0-ce/soap/default?services=catalogInventoryStockRegistryV1">
			<scopeId xmlns="">1</scopeId>
			<qty xmlns="">1E+12</qty>
			<currentPage xmlns="">1</currentPage>
			<pageSize xmlns="">500</pageSize>
		</catalogInventoryStockRegistryV1GetLowStockItemsRequest>
	</s:Body>
</s:Envelope>
`

### Expected result

1. `<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://youmagentohost/magento-2-1-1-0-ce/soap/default?services=catalogInventoryStockRegistryV1">
	<SOAP-ENV:Body>
		<ns1:catalogInventoryStockRegistryV1GetLowStockItemsResponse>
			<result>
				<items>
					<item>
						<productId>1</productId>
						<stockId>1</stockId>
						<qty>402</qty>
						<stockStatus/>
						<stockItem/>
					</item>
					<item>
						<productId>2</productId>
						<stockId>1</stockId>
						<qty>0</qty>
						<stockStatus/>
						<stockItem/>
					</item>
					<item>
						<productId>3</productId>
						<stockId>1</stockId>
						<qty>438</qty>
						<stockStatus/>
						<stockItem/>
					</item>
				</items>
				<searchCriteria>
					<mapperInterfaceName>Magento\CatalogInventory\Model\ResourceModel\Stock\Item\StockItemCriteriaMapper</mapperInterfaceName>
					<criteriaList/>
					<filters/>
					<orders/>
					<limit>
						<item>1</item>
						<item>500</item>
					</limit>
				</searchCriteria>
				<totalCount>3</totalCount>
			</result>
		</ns1:catalogInventoryStockRegistryV1GetLowStockItemsResponse>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
`

### Actual result

1.  `<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://youmagentohost/magento-2-1-1-0-ce/soap/default?services=catalogInventoryStockRegistryV1">
	<SOAP-ENV:Body>
		<ns1:catalogInventoryStockRegistryV1GetLowStockItemsResponse>
			<result>
				<items/>
				<searchCriteria>
					<mapperInterfaceName>Magento\CatalogInventory\Model\ResourceModel\Stock\Item\StockItemCriteriaMapper</mapperInterfaceName>
					<criteriaList/>
					<filters/>
					<orders/>
					<limit>
						<item>1</item>
						<item>500</item>
					</limit>
				</searchCriteria>
				<totalCount>0</totalCount>
			</result>
		</ns1:catalogInventoryStockRegistryV1GetLowStockItemsResponse>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
`

**Comment by olysenko** [comment] 2016-12-06 11:06
Hi, thank you for your report. The correct behavior is in 2.1.x(the same in develop branch). Field website_id=0 in table cataloginventory_stock_item. It is incorrect in the 2.0.x. where website_id=1.  Internal issue was created MAGETWO-61904

**Comment by magento-engcom-team** [comment] 2017-10-17 08:30
@MaximKitsenko, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-17 08:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Framework/Webapi, Issue: Clear Description, Issue: Confirmed, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
