### ISSUE TITLE
NewRelic: CLI commands are reported as `bin/magento` transaction

### ISSUE THREAD

**Issue by adarshkhatri** [magento/magento2#38250] opened 2023-12-08 01:22 UTC
### Preconditions and environment

- Magento version: 2.4.6-p2
- Make sure NewRelic is installed and configured

### Steps to reproduce

1. Create a CLI command. 
2. Set AreaCode in that command execution: `$this->appState->setAreaCode(\Magento\Framework\App\Area::AREA_ADMINHTML);`

### Expected result

The transaction should appear under the same name as the CLI command.

If my CLI command is `bin/magento my:custom:command`, then the Transaction should be created as `my:custom:command`

### Actual result

The transaction appears under `bin/magento`. 

### Additional information

If we don't set the `setAreaCode` then it is correctly reported to NewRelic though.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2024-02-19 11:33
Hello @adarshkhatri,

Thanks for the report and collaboration!

We have tried to reproduce the issue in the latest Magento 2.4-develop branch but it seems the issue is not reproducible for us. We can trace the transaction with AreaCode `AdminHTML`. Please have a look into the below screenshot for reference:

![image](https://github.com/magento/magento2/assets/51681618/da9fcdfb-cbe4-4985-a0da-a41d5a5cbb1b)

Please find below the custom module used to reproduce the issue:
[Magz.zip](https://github.com/magento/magento2/files/14330472/Magz.zip)

Let us know in case we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2024-03-01 07:28
Dear @adarshkhatri,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we're assuming it's been resolved and will be closing it. Feel free to open a new ticket or reopen this one if you require further assistance.

Regards

**Closed as completed by engcom-Hotel** 2024-03-01 07:28 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.6-p2
