### ISSUE TITLE
Wrong discount value - Shopping Cart rule fixed on shipping when shipping tax is different than products tax

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#33446] opened 2021-07-09 09:10 UTC
### Preconditions (*)

Magento 2.4.2-p1

### Steps to reproduce (*)

1. Add a cart rule : Fixed amount for whole cart, with coupon, 5€, Apply discount to shipping to 'Yes'
2. Set up a tax class for shipping, create a specific rate (different rate than other products you will use for test) and rule for it, and assign that tax class to shipping tax.

### Expected result (*)

5€ discount

### Actual result (*)

5,20€ discount

For more details about the issue and configuration, please check this [comment](https://github.com/magento/magento2/issues/33446#issuecomment-877156873)

### Screenshots

Tax rules : 
![Capture d’écran 2021-07-09 à 11 07 09](https://user-images.githubusercontent.com/1633463/125053836-d902d800-e0a5-11eb-84b9-6cd792d1739c.png)

Tax config :
![Capture d’écran 2021-07-09 à 11 06 54](https://user-images.githubusercontent.com/1633463/125053844-d99b6e80-e0a5-11eb-8778-6464e2e02343.png)

Cart rule config :
![Capture d’écran 2021-07-09 à 11 06 43](https://user-images.githubusercontent.com/1633463/125053846-da340500-e0a5-11eb-9a35-a1a52243f43e.png)

Cart result :
![Capture d’écran 2021-07-09 à 11 05 16](https://user-images.githubusercontent.com/1633463/125053849-da340500-e0a5-11eb-87d3-a56e1239409b.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2021-07-09 12:38
Verified the issue on Magento 2.4.2 -p1 version and the issue is reproducible:
Steps to reproduce:
1. European store setup (Currency: EURO and Country: Germany)
2. Admin - Stores - Taxes - Tax Zones and Rates - Add New Tax Rate
3. Stores - Taxes - Tax Rules - Apply new tax rate
4. Additional Settings - Add new Tax class and save rule
5. Stores - Configuration - Sales - Tax - Tax Class for Shipping - Apply new created tax class
6. Configure Tax Calculation Settings as per below screenshot
![image](https://user-images.githubusercontent.com/60198231/125078870-9c080700-e0e0-11eb-9467-604088e3421d.png)
![image](https://user-images.githubusercontent.com/60198231/125078905-a4f8d880-e0e0-11eb-9e8c-23a16aa5254c.png)

7. Create Cart Price Rule: Fixed amount for whole cart, with coupon, 5€, Apply discount to shipping to 'Yes' (Marketing - Cart Price Rules - Add New Rule)
8. Clear cache and re-index
9. Navigate to Front end - Login to the website
10. Add a product to Cart - Go to Shopping Cart page
11. Select country Germany 
12. Select shipping method
13. Apply discount
**Issue:**  Discount €5.22 is getting applied instead of 5€
![image](https://user-images.githubusercontent.com/60198231/125078962-b80ba880-e0e0-11eb-9ccc-5ae4ab42c8a5.png)

**Comment by magento-engcom-team** [comment] 2021-07-13 11:35
:white_check_mark: Confirmed by @gabrieldagama 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42835` were created

**Issue Available**: @gabrieldagama, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment] 2021-07-19 13:37
Hi All,

Implementation is in progress on this.

Thanks.

**Comment by dino6213221** [comment] 2021-08-16 10:22
Hi @engcom-Bravo 
Is there any news about this issue?

**Closed as completed** 2021-08-16 11:04 UTC
Labels: Component: Tax, Issue: Confirmed, Reproduced on 2.4.x, Priority: P1, Progress: done
