### ISSUE TITLE
Report search terms csv export

### ISSUE THREAD

**Issue by esseremmerik** [magento/magento2#22971] opened 2019-05-22 10:28 UTC
### Preconditions (*)

Magento 2.2.7

### Steps to reproduce (*)

1. Setup Magento with multiple stores and views
2. Choose Report->Sales terms->export to CSV

### Expected result (*)

1. A valid CSV file containing all search terms

### Actual result (*)

1. A CSV is generated with an incorrect format, the storeview column contains invalid cr/lf lines. The system should not include cr/lf combinations for the storeview column.

**Comment by esseremmerik** [comment] 2019-05-22 10:29
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-05-22 10:29
Hi @esseremmerik. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-05-22 10:30
Hi @esseremmerik, here is your [Magento instance](https://i-22971-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22971-2-3-develop.instances.magento-community.engineering/admin](https://i-22971-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by esseremmerik** [comment] 2019-05-22 10:34
Just reproduced this issue on 2.3-develop instance
![image](https://user-images.githubusercontent.com/3390371/58168194-f12cf880-7c8d-11e9-8e9f-a16622ad5311.png)

**Comment by krishprakash** [comment] 2019-05-22 10:48
Hi @esseremmerik,
I'm not able to reproduce this issue.
PFA
![image](https://user-images.githubusercontent.com/46617848/58168895-01a09b80-7cad-11e9-8e26-d44770d4fc4f.png)
Can you please explain with more detail with proper reproducible steps.
Thank you.

**Comment by esseremmerik** [comment] 2019-05-22 10:51
Hi @krishprakash. Your screenshot looks like an excel view. Probably Excel can "fix" this issue automagically, but if you open the file with a plain file editor, you see the issue. Rows should be on 1 line, the CSV has rows over multiple lines.

**Comment by krishprakash** [comment] 2019-05-22 11:32
Opened with Notepad,N++ but not able to reproduce.
![image](https://user-images.githubusercontent.com/46617848/58171330-6828b800-7cb3-11e9-9bd4-26fd4d8fd696.png)

**Comment by esseremmerik** [comment] 2019-05-22 13:09
Hi @krishprakash, your screenshot is actually confirming the issue instead of not reproducing it.
It should be on one line, so the file should contain 4 lines, 1 title row and 3 data rows. Your screenshot is showing 10 lines, 3 lines per data row.

**Comment by esseremmerik** [comment] 2019-05-22 15:19
Hi @krishprakash, Why did you add the label "Issue: Cannot Reproduce", please update this to the correct state.

**Comment by magento-engcom-team** [comment] 2019-05-31 09:48
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17154`, `MC-17155` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by chickenland** [comment] 2019-06-18 13:05
@esseremmerik Why do you class this output as invalid? As the string is enclosed in quotes, newlines are allowed.

**Comment by magento-engcom-team** [comment] 2020-11-06 19:18
The related internal Jira ticket `MC-17154, MC-17155` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem on the latest `2.4-develop` please create new Issue with updated information/steps/preconditions in the **_Description section_**.

**Comment by magento-engcom-team** [comment] 2020-11-06 19:18
The related internal Jira ticket `MC-17154, MC-17155` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem on the latest `2.4-develop` please create new Issue with updated information/steps/preconditions in the **_Description section_**.

**Closed as completed** 2020-11-06 19:19 UTC
Labels: Component: ImportExport, Reproduced on 2.2.x, Reproduced on 2.3.x, Component: Admin
