### ISSUE TITLE
Switching store groups when in category

### ISSUE THREAD

**Issue by snky1987** [magento/magento2#912] opened 2015-01-05 16:27 UTC
When I was in a sample category (201) and changed store group in a footer I received 404 error (which is correct).

I think it may be useful to reset view into main view when change store group (unless there is a option to show different products under the same category depends on store group).

It's not a bug but I am 99% sure that it will come back as an issue to any agency that set up Magento multi-store.

**Comment by waynemowdirect** [comment] 2015-01-05 16:33
+1 or to put it another way "404 response should be prevented and user should be redirected to homepage whenever the action that has caused the potential 404 is a switching of a storegroup"

**Comment by snky1987** [comment] 2015-01-05 16:38
@waynemowdirect thanks but in some cases 404 is required otherwise people will struggle with "Why it redirects me?" e.g. when someone try to access non active category form Google search engine (or AdWords). But its for a different conversation ;)

**Comment by waynemowdirect** [comment] 2015-01-05 17:26
@snky1987 ah yes, but that wouldn't be caused by the switching of a store group... that would visiting a URL that magento doesn't know how to display - 

What I was trying to explain was if the user does an action, like manually switching a storegroup using the footer dropdown, magento should know how to display content, the customer is asking us to change stores and display some content hopefully in the same or similare category of product. Magento shouldn't return a 404, as the user has chosen to do something that from a usability point of view is foreseeable, the user is expecting to see content from a different store, and expects us to understand that, therefore from a usability point of view a 404 should be avoided and the user should be redirected a category higher in the tree if one exists or the homepage if one doesn't. 

A 404 should be reserved for actions where we can't guess what a logical action should be...

**Comment by snky1987** [comment] 2015-01-05 17:31
@waynemowdirect yes you are right so we get the same point in a bit different way :) its just my english skills, sorry :)

**Comment by waynetheisinger** [comment] 2015-01-05 17:38
your english is perfect, and your reply continued the discussion which is always a good thing...

**Comment by orlangur** [comment] 2015-01-05 22:00
When category exists in both store groups, switching store groups must just change URLs, but category remains the same, right?

But when there is no current route in store group user switched to, why perform an immediate redirect? Other option could be to show some fancy 404 page with message "There is no AAA route in BBB store group." and a couple of links "Go back to CCC category in DDD store view", "Go to BBB store group home page".

**Comment by snky1987** [comment] 2015-01-05 23:24
To be honest there is no need to complicate things like that. Most of business models will say that when you enter (or swith to) store they would prefer to show special offers, discounts etc. that are usually on the homepage. 

Following this kind of thinking there would be much less code to write and whats follows after more code clarity and better engine speed :) its important to think about it with every sigle line of code.

**Comment by verklov** [comment] 2015-01-30 13:27
@snky1987, thank you for your suggestion! We created the ticket in the internal tracker and put it to the backlog. PM responsible for the area will review it and make the appropriate decision.
Internal ID: MAGETWO-33440.
We are closing this ticket on the GitHub now.

**Comment by piotrekkaminski** [comment] 2016-08-30 20:12
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Switching-store-groups-when-in-category/idi-p/47323).

**Closed by piotrekkaminski** 2016-08-30 20:12 UTC
Labels: acknowledged, feature request, moved_to_forums, PROD
