### ISSUE TITLE
Error while installing Magento 2.4 from CLI

### ISSUE THREAD

**Issue by lucasvm** [magento/magento2#29462] opened 2020-08-11 01:08 UTC
### Summary (*)
Installing Magento 2.4 from CLI getting Interceptor error

### Examples (*)
php bin/magento setup:install --base-url=http://local.web.com/ --db-host=localhost --db-name=mydb --db-user=root --db-password= --admin-firstname=admin --admin-lastname=admin --admin-email=test@test.com --admin-user=admin --admin-password=admin123 --language=en_US --currency=USD --timezone=America/Chicago

### Proposed solution

---
Getting error: Class Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor does not exist

**Comment by ihor-sviziev** [comment] 2020-08-11 09:06
hi @lucasvm,
As I understood - did you run the composer install command before it?

**Comment by lucasvm** [comment] 2020-08-11 13:57
Yes of course i have ran the composer install, there is no more web setup wizard install', only cli?, im running php 7.3 on Ubuntu, do i need to install some php extension? the docs are not clear.

**Comment by ihor-sviziev** [comment] 2020-08-11 15:36
Yes, in magento 2.4 there no more web installer. In case if you’ll have
some missing extension - composer install should fail. Could you rerun the
install command with -vvv flag at the end?

**Comment by mrtuvn** [comment] 2020-08-11 16:06
in case you download package from magento homepage you don't need run composer install. If you add extra package to composer.json just run composer update

From 2.4.0 magento install via cli only cause web wizard has removed
Cli command should add elasticsearch to avoid issue during cli run
--search-engine=elasticsearch7 --elasticsearch-host=elasticsearch --elasticsearch-port=9200 --elasticsearch-index-prefix=magento2 --elasticsearch-enable-auth=0 --elasticsearch-timeout=15

**Comment by lucasvm** [comment] 2020-08-11 16:13
I have installed via Composer, doing the create project.

**Comment by sdzhepa** [comment] 2020-08-11 20:50
Hello @lucasvm 

Not sure exactly but seems this issue related to your dev environment. Probably some required extension is missed or some artifacts in DB or code.

I verified this issue by the next steps:
1. Get Magento using composer as described here: https://devdocs.magento.com/guides/v2.4/install-gde/composer.html#get-the-metapackage
```
composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition
```
2. Create empty DB and user for Magento. 
3. Check that Elasticsearch is run and configured. More details here: https://devdocs.magento.com/guides/v2.4/config-guide/elasticsearch/es-overview.html
4. Install Magento using CLI. Example of my CLI
```
php bin/magento setup:install \
--db-host=db \
--db-name=magento_i3 \
--db-user=magento \
--db-password=123123q \
--base-url=http://magento.i3.loc \
--backend-frontname=admin \
--admin-user=admin \
--admin-password=123123q \
--admin-email=admin@test.com \
--admin-firstname=Magento \
--admin-lastname=User \
--language=en_US \
--currency=USD \
--timezone=America/Chicago \
--skip-db-validation \
--elasticsearch-host=000.00.00.000 \
--elasticsearch-port=9200 \
--elasticsearch-index-prefix=instance_3 \
&& chown -R www-data:www-data .
```

**Result:**  
- Magento 2.4.0 successfully installed.
- No errors like `Class Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor does not exist` during installation and after in log files


Please, review my steps and additional docs probably it has the answer.
Also, if I missed some details please let me know. Unfortunately without additional details, this issue could be closed as cannot reproduce

**Comment by lucasvm** [comment] 2020-08-12 01:49
Ok thank you!, i think i have installed the software, i can see all the tables in the database, also the env file has been created, but when going to the website i still see the setup landing page, do i need to delete something?

**Comment by mrtuvn** [comment] 2020-08-12 02:25
@lucasvm yes 2.4 required elastic when install. Before you run cli for install make sure elastic service run

**Comment by ihor-sviziev** [comment] 2020-09-29 11:50
Hi @lucasvm,
I’m closing this issue as it reproducing only when you don’t have configured elasticsearch, which is requirement for magento correct work.

**Closed as completed by ihor-sviziev** 2020-09-29 11:50 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid, help wanted, Triage: Dev.Experience, Progress: done, Reported on 2.4.0

**Comment by potticus** [comment] 2021-05-10 14:08
In my case, it was saying the domain was invalid, but it turned out it was all to do with invisible illegal characters that got pasted when I copied the whole install command code from another website. It seems to tell you that the domain is invalid as that tends to be the first parameter declared in the command.
