### ISSUE TITLE
Recently Ordered sidebar error in a special character like TM

### ISSUE THREAD

**Issue by hitesh-wagento** [magento/magento2#26426] opened 2020-01-17 06:01 UTC
### Summary
Recently Ordered sidebar error in a special character like **TM**

### Preconditions
1. Magento 2x - This issue reproduce in all version.

### Steps to reproduce

1. Order placed any product
2. Go to a category page
3. You can see the left side Recently Ordered section

### Expected result

![expected](https://user-images.githubusercontent.com/23443991/72587999-ead64580-391c-11ea-9935-e476df8766de.png)

### Actual result

![actual](https://user-images.githubusercontent.com/23443991/72587998-ead64580-391c-11ea-9f60-3a35e0430be8.png)

**Comment by hitesh-wagento** [comment] 2020-01-17 06:04
I am working on this issue

**Comment by krishprakash** [comment] 2020-01-17 08:49
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-01-17 08:49
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-17 08:49
Hi @krishprakash, here is your [Magento instance](https://i-26426-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26426-2-4-develop.instances.magento-community.engineering/admin_6a36](https://i-26426-2-4-develop.instances.magento-community.engineering/admin_6a36)
Login: `c018fd70` Password: `f02126a13d67`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2020-01-17 09:00
Hi @hitesh-wagento. Not able to reproduce issue on latest magento instance.
It working fine at category page as well as my account pages.
Refer below screenshot
![image](https://user-images.githubusercontent.com/46617848/72598391-bfac2000-3935-11ea-8237-b8f7d5e041f0.png)

**Comment by hitesh-wagento** [comment] 2020-01-17 09:24
Hi @krishprakash 

I have created the same name used in Luma theme I can reproduce this issue please review attached screenshot

![Test](https://user-images.githubusercontent.com/23443991/72600207-35fe5180-3939-11ea-81ba-ec2e792e858c.png)

**Comment by ajijshekh123** [comment] 2020-01-17 09:34
Issue reproduced in the Magento 2.4 Instance.
See attached the screenshot:

![1](https://user-images.githubusercontent.com/24711761/72601034-a78acf80-393a-11ea-8ddd-2afe9c737b47.png)

**Comment by magento-engcom-team** [comment] 2020-01-17 09:35
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30507` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ajijshekh123** [comment] 2020-01-17 09:52
@hitendra-wagento - Please verify once again on the Product section on the admin section.
I have changed the Product name content and Place the order it is working fine.

See attached the screenshot:

![2](https://user-images.githubusercontent.com/24711761/72602358-2b45bb80-393d-11ea-95d9-6c039088f623.png)

Please update your thought and Update me let me close this issue or not?

Thanks.

**Comment by hitesh-wagento** [comment] 2020-01-17 09:57
Hi @ajijshekh123 

Again your mistake I am @hitesh-wagento, not @hitendra-wagento  :)

Yes, This is issue you can see in changes I have changed code **text** to **html** so It will work in both scenarios. 
https://github.com/magento/magento2/pull/26428/commits/777675042387e2502cb5fe8750c05cf49a208789

If customer write **Minerva LumaTech&trade; V-Tee** (This is an issue on frontend)
If customer write **Minerva LumaTechTM V-Tee** (This is a not issue on frontend)

**Comment by ajijshekh123** [comment] 2020-01-17 09:59
Okay, @hitesh-wagento :)
Thanks for the Update.

**Comment by manishsoni5041** [comment] 2020-02-29 10:39
I have checked on dev-2.4-develop instance and not able to produce this issue, Looks fine.
![Screenshot from 2020-02-29 16-09-27](https://user-images.githubusercontent.com/33372563/75605950-ea30f180-5b0d-11ea-8e77-fae96e58853d.png)

**Comment by engcom-Foxtrot** [comment] 2020-05-12 08:23
Issue is not reproducible on 2.4-dev branch.

**Closed as completed by engcom-Foxtrot** 2020-05-12 08:23 UTC
Labels: Issue: Ready for Work, Component: Sales, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Area: Design/Frontend
