### ISSUE TITLE
Data order wrong on invoice

### ISSUE THREAD

**Issue by TWIAntonio** [magento/magento2#36454] opened 2022-11-10 11:01 UTC
### Preconditions and environment

- Magento version 2.3.5-p2
- Anything else that would help a developer reproduce the bug

data order is 13-april - 2028 

real data order was 24-oct-2022

### Steps to reproduce

1. try number ordre
2. select numebr order
3. selct invoices
4. flag on row 
5. select action 
6. select pdf invoice

### Expected result

data order 24-oct-2022

### Actual result

13 -apr - 2028

[Fattura Sannino.pdf](https://github.com/magento/magento2/files/9979988/Fattura.Sannino.pdf)

### Additional information

Could you pease check ad fix it ?

thanks

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-11-10 11:06
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-10 11:18
Hi @TWIAntonio,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to Reproduce** :

1.Place an order.
2.Submit an Invoice.
3.Select action.
4.Select pdf Invoice.
5.Check the ordered Date.


<img width="580" alt="Screenshot 2022-11-10 at 4 43 46 PM" src="https://user-images.githubusercontent.com/51680745/201077376-51c7224b-6325-42f5-b419-0670b50053eb.png">


<img width="751" alt="Screenshot 2022-11-10 at 4 44 19 PM" src="https://user-images.githubusercontent.com/51680745/201077421-f3e82194-90af-413c-8271-260863a5ccfa.png">


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by TWIAntonio** [comment] 2022-11-10 13:12
where do I go wrong ?

![image](https://user-images.githubusercontent.com/117908267/201100521-929db5be-f35e-438f-bb7c-db337ff7c2c0.png)

![image](https://user-images.githubusercontent.com/117908267/201099849-ef204b58-e717-4ef5-9815-178a2be4eb76.png)

![image](https://user-images.githubusercontent.com/117908267/201100113-9f70f0b4-a082-4f6f-96c5-36577fb94f2b.png)

Thanks

**Comment by engcom-Bravo** [comment] 2022-11-11 07:18
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-11 07:30
Hi @TWIAntonio,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

<img width="1036" alt="Screenshot 2022-11-11 at 12 57 03 PM" src="https://user-images.githubusercontent.com/51680745/201288945-91a32c72-d9a7-4e4a-b99f-3ba9102caf86.png">



<img width="767" alt="Screenshot 2022-11-11 at 12 57 13 PM" src="https://user-images.githubusercontent.com/51680745/201288965-640d953b-7685-446d-8ccf-91f3921fa7c7.png">




Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2022-11-25 06:10
Hi @TWIAntonio,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.


Thanks.

**Closed as completed by engcom-Bravo** 2022-11-25 06:10 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.3.5-p2
