### ISSUE TITLE
No fallback to attribute option for text swatch

### ISSUE THREAD

**Issue by paales** [magento/magento2#5143] opened 2016-06-21 19:35 UTC
Version 2.1-rc3
When creating an attribute option as a text-swatch it should fall back to the default option value.

<img width="944" alt="schermafbeelding 2016-06-21 om 21 33 11" src="https://cloud.githubusercontent.com/assets/1244416/16243489/ca5cad82-37f7-11e6-9640-ce50b3687328.png">

Results in:
<img width="562" alt="schermafbeelding 2016-06-21 om 21 33 45" src="https://cloud.githubusercontent.com/assets/1244416/16243503/dc8fd902-37f7-11e6-8963-d1e1bad1febd.png">

It should result in:
<img width="532" alt="schermafbeelding 2016-06-21 om 21 34 41" src="https://cloud.githubusercontent.com/assets/1244416/16243525/fe2ad378-37f7-11e6-9a71-b1264ca808af.png">

But this requires me to do the following (with 30+ storeviews this becomes problematic)
<img width="944" alt="schermafbeelding 2016-06-21 om 21 35 02" src="https://cloud.githubusercontent.com/assets/1244416/16243542/11280004-37f8-11e6-94ba-bce0afdd5da9.png">

Related to #5142

**Comment by pboisvert** [comment] 2016-06-22 05:27
@paales Can you provide more info in terms of steps to reproduce and the version number? I tried to reproduce but when creating a new attribute of type "text swatch" and then clicking Add Swatch, there is always a default selected. Not sure your path for creating this swatch field that results in no default option so may be version specific.

**Comment by pboisvert** [comment] 2016-06-22 05:29
oops--just caught that version is listed above screenshots. 

@antboiko can you have the team test against RC3 for this?

**Comment by paales** [comment] 2016-06-22 08:41
> I tried to reproduce but when creating a new attribute of type "text swatch" and then clicking Add Swatch, there is always a default selected.

To clarify, I'm not referring to the 'Is Default' column, but I'm referring to the Admin and Swatch columns. When the Swatch column isn't filled in, the swatch should fall back to the Admin column. Hope that makes sense.

**Comment by antboiko** [comment] 2016-06-22 15:11
Hi @paales , thanks for reporting. I could easily reproduce this issue. Internal ticket MAGETWO-54648 was created. I mentioned https://github.com/magento/magento2/issues/5142 within it as well.

Best,
Anton.

**Comment by BuysTooMuch** [comment] 2017-03-01 14:23
This issue still exists in 2.1.5 - wondering if it will be addressed?  Huge, huge inconvenience on multisite installations with many attributes.  I also don't quite follow the reason for the two-columns-per-store.  And lastly, this bug causes a very misleading effect of swatches "disappearing" which costs lots of man-hours in troubleshooting.

Not sure how this feature's state affects data imports/migrations yet either, but this feature needs to be tightened-up for shop owners!

**Comment by magento-engcom-team** [comment] 2017-09-20 22:21
@paales, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:21 UTC
Labels: Issue: Ready for Work, bug report, Fixed in 2.2.x, Issue: Format is not valid

**Comment by pixiemediaweb** [comment] 2018-05-27 10:18
We have this problem in 2.2.3. We've migrated products from M1 and have a size attribute with around 200 options and 6 store views.  We expect the text swatch to take on the already populated label value for each store view but it does not. I am unable to save 'Admin is a required field in the each row.'
