### ISSUE TITLE
Magento 2.4.4 CE - Import (add/replace) an existing product with a quantity does not increase the salable quantity. If initial quantity at 0.

### ISSUE THREAD

**Issue by lucbard** [magento/magento2#36236] opened 2022-10-04 13:40 UTC
### Preconditions and environment

Magento 2.4.4 CE
This test was also perform on a vanilla install of Magento with sample data

### Steps to reproduce

1. Create a CSV File with these headers: sku, qty, is_in_stock
2. Put the sku of an existing product with a qty of 10 for example and is_in_stock = 1
3. Make sure the existing product in Magento has a current qty and salable quantity at 0
4. Got to System --> Import, Entity Type = Product, Import Behavior = Add / Update
5. Browse to select your file, click on Check Data and then Import
6. Go back to Catalog->Product and search for that sku. 

### Expected result

The new qty should be set to 10 and so should the salable quantity.

### Actual result

Quantity is set correctly but not the Salable quantity

### Additional information

- If you go to the product and hit save the salable qty will be correct.
- If the initial product quantity > 0 then this is not an issue the qty and salable qty will be the same.
- If you import a product that does not exist you will not have this issue
- If you change the qty to 0 in Magento admin and try to import a CSV with qty the problem will occur again.

It is really when the initial quantity is 0.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-10-07 09:01
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-10-07 12:23
Hi @lucbard,


Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance but could not reproduce the issue. After Importing (add/replace) an existing product with a quantity we are able to increase the salable quantity.If initial quantity at 0.Kindly refer the screenshots.


<img width="1226" alt="Screenshot 2022-10-07 at 5 49 44 PM" src="https://user-images.githubusercontent.com/51680745/194551895-75a06572-d163-4e3f-814c-899935cb286a.png">



<img width="1222" alt="Screenshot 2022-10-07 at 5 49 23 PM" src="https://user-images.githubusercontent.com/51680745/194551937-781a11d2-a987-4a86-a1f3-c49266256435.png">

**CSV FILE** 

[catalog_product (3).csv](https://github.com/magento/magento2/files/9733821/catalog_product.3.csv)



Can you please recheck the behavior on Magento 2.4-develop instance and elaborate/ provide missing steps if the issue is still reproducible.


Thanks.

**Comment by lucbard** [comment] 2022-10-10 15:14
I sorry for the delay but the Magento instances given above aren't working.

**Comment by engcom-Bravo** [comment] 2022-10-19 06:12
HI @lucbard,

To deploy vanilla Magento instance, please add a comment to this issue: "[@magento](https://github.com/magento) give me 2.4-develop instance".

Kindly recheck the issue on Magento 2.4-develop instance.



Thanks.

**Comment by engcom-Bravo** [comment] 2022-11-02 06:18
Hi @lucbard,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-11-02 06:18 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.4
