### ISSUE TITLE
Internet Explorer shopping cart content not showing up after log-in (untill I add an extra product)

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#6011] opened 2016-08-05 10:34 UTC
### Preconditions

1. Magento version 2.1
### Steps to reproduce

1. Use Internet Explorer
2. Make an account and log -in
3. Add some products to your cart
4. Log out
5. Log in Again
### Expected result

1. When logged in again you should see the products that you left in your cart
### Actual result

1. The products don't seem to be in your cart after logging in
2. however they actually are still present, they reappear when adding a new product to the cart when you are logged in

**Comment by AVoskoboinikov** [comment] 2016-09-07 13:31
Hi @SidneyBilliet 

I have tried to reproduce this issue on latest 2.1.1 version and it works fine for me. Could you update your Magento to 2.1.1 and try to recheck if this bug is still actual?

Thanks!

**Comment by andimov** [comment] 2016-10-10 14:52
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by andimov** 2016-10-10 14:52 UTC
Labels: bug report, Progress: needs update
