### ISSUE TITLE
The title «Store Design Schedule» above the admin design changes grid is untranslatable (and my fix)

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2009] opened 2015-10-02 18:39 UTC
https://mage2.pro/t/104

![magento2-01](https://cloud.githubusercontent.com/assets/83204/10254705/0cc38c0a-694e-11e5-8d6c-38ef733055ee.png)

**Comment by mbrinton01** [comment] 2015-10-16 19:51
Hello @dfediuk, can you create a pull request for the fix you propose?

**Comment by vzabaznov** [comment] 2016-06-22 11:40
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment] 2016-07-14 09:27
Hi, @mage2pro thank you for contributing, i will close this issue for now as no update more than 14 days, if you think that issue is still reproducible, please fell free to open another one.

**Closed by vzabaznov** 2016-07-14 09:27 UTC
Labels: bug, needs update, PS
