### ISSUE TITLE
Visual Swatches not showing swatch color in admin

### ISSUE THREAD

**Issue by lee586** [magento/magento2#11828] opened 2017-10-27 22:31 UTC
### Preconditions

1. Magento CE 2.2
2. PHP 7.1.0

### Steps to reproduce

1. Inside admin, go to Stores->Product and click on an attribute that contains visual swatches.  

### Expected result

1. Visual Swatches that have a color assigned should show that color in the swatch box.

### Actual result

1. Although the color swatch values are being saved, the visual representation of the color in the box is colorless.
![swatches](https://user-images.githubusercontent.com/332639/32127440-8651ef20-bb3c-11e7-86c5-4dbc431b6fd8.png)

**Comment by magento-engcom-team** [comment] 2017-10-30 08:29
@lee586, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by leoncito73** [comment] 2017-11-01 08:02
I have the same issue.
Magento 2.2.0
PHP 7.1.0
In front view the swatches shown correctly but in admin panel no.
When you add the new color (by image or picking the color) it shows, but when you save the attribute, it disappear.

I prove to reindex by command but nothing fix.
![captura de pantalla 2017-11-01 a las 10 00 49](https://user-images.githubusercontent.com/31698668/32265433-b3e1ba12-beeb-11e7-8f52-fce654609cb2.png)
![captura de pantalla 2017-11-01 a las 10 01 21](https://user-images.githubusercontent.com/31698668/32265434-b3fb2a06-beeb-11e7-8fe7-7a3a3925d0ae.png)

![captura de pantalla 2017-10-27 a las 16 25 33](https://user-images.githubusercontent.com/31698668/32265299-1b2d7720-beeb-11e7-9187-949d32854e0f.png)

**Comment by AgentGod** [comment] 2017-11-05 09:32
![php7 0 25](https://user-images.githubusercontent.com/8660031/32413557-460f8e4a-c21c-11e7-92d4-4e1f952767dc.PNG)

Similar issue here. This one on top is with php7.1.11. The swatches are saved but not visible. 

After changing the php version to 7.0.25 and refresh the page, I have this one below:

![php7 1 11](https://user-images.githubusercontent.com/8660031/32413559-53ce4f6c-c21c-11e7-879d-a15aac35da35.PNG)

Another problem with swatches: I have changed text swatches to color swatches, but on front end in layered nav, I still see them as Visual swatches. I think the problem is related or similar to this issue https://github.com/magento/magento2/issues/3139

I don't have product with option to see what is the status on product pages.

**Comment by matin73** [comment] 2017-11-10 11:49
same issue on php 7.1.11

**Comment by alex4allofyou** [comment] 2017-11-20 16:20
I also have this issue, PHP7.1.9.

Also, the dropdown has a lower z-index than the rest, so if you have not many swatches or choose one at the bottom you cannot see all options.

![zindex](https://user-images.githubusercontent.com/9028498/33028750-009b3056-ce17-11e7-9db6-3bb111e17088.JPG)

**Comment by GlobalOutsourcing** [comment] 2017-12-05 12:43
Just want to confirm the same issue as above with PHP Version 7.1.1 with Magento Verison 2.2.1.

**Comment by chris-pook** [comment] 2018-01-10 11:31
This is an issue with the way PHP7.1 handles strings differently. This issue should not be closed. I have added a PR to fix the issue here: https://github.com/magento/magento2/pull/13093

**Comment by ishakhsuvarov** [comment] 2018-01-10 15:29
@chris-pook Thank you for providing the fix. Reopened while it's in the delivery process.

**Comment by magento-team** [comment] 2018-01-17 01:55
Hi @lee586. Thank you for your report. 
The issue has been fixed in magento/magento2#13101 by @chris-pook in 2.2-develop branch
Related commit(s):
 - ee5fc2ece394318aa8f06ecaaae15ffc6dddb645

The fix will be available with the upcoming patch release.

**Closed as completed by magento-team** 2018-01-17 01:55 UTC
Labels: Fixed in 2.2.x, Fixed in 2.3.x, Issue:  Cannot Reproduce, Issue: Format is valid

**Comment by magento-engcom-team** [comment] 2018-01-29 18:30
Hi @lee586. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1302 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 176b9f09d657cea1ba04d69d273641a1d47841b3
 - ab504376148b77c73447c8abbb5ae42a66071a10
 - 6a527a87bc6e46fce9ed45b2561b45c44a7a7e85
 - a0cb9e274b6a4cca5f410224babb6625546ce45b
 - 6e6c7d2987182cb48042db28f72a8c08de615d8d
 - 1d45a064e783f109cd413989672073c9ccac8bdb
 - 1fdee0001742c5fd1b5980aaa1f3ed81ab545cc3
 - 727f9b306bb8ea889dc580fe8056f8080fd62680
 - f842883a7a0b680f2cda361f7f9628bd739c1c38
 - 547426435ddbb263d30baee68fd5cd29a7dc1267
 - ba1d05a023f3e989d49ea8e29546433fe62090b0
 - 6fb29ac2a4f92dde2947f2a07225a6c55899c946
 - be2840d4f2d930ce97a5c1d005ebd5d071f782a7
 - 17da65c817295631c34d4902e62798d88e010ecb
 - ded8aa9710c5527d3eb8b679b8fb58ba1a222faa
 - 818cccdd55a4009fe7617e9c535b4c858967b273

The fix will be available with the upcoming patch release.

**Comment by EBotha1** [comment] 2018-06-28 08:03
I have the same issue with Magento2 and RestAPI, please check [here](https://github.com/magento/magento2/issues/16289)
@magento-admin @magento-devops  @magento-engcom-team Please assist

**Comment by matheus0608** [comment] 2019-08-17 02:43
not work

**Comment by vishalbaytech** [comment] 2020-02-12 08:22
How do I show swatchvisual color in admin section as well?
![screenshot-74 208 252 21-2020 02 11-17_14_38](https://user-images.githubusercontent.com/48333434/74316114-e3c91880-4d9e-11ea-8745-6a821a8f91b4.png)
