### ISSUE TITLE
Sign-In Sign-Out problem

### ISSUE THREAD

**Issue by monotheist** [magento/magento2#26837] opened 2020-02-12 11:47 UTC
### Preconditions (*)

1. Magento 2.3.3
2. Varnish 6
3. Redis
4. SSL enabled

### Steps to reproduce (*)

1. Header Sign-in link doesn't change into Sign-out after Sign-in to the store and navigating to category pages. 
2. See this video to reproduce. [https://youtu.be/X1jqpPMOSVg](url)

### Expected result (*)

1. After sign-in, the link should remain displaying sign-out till the user logs off.

### Actual result (*)

1. After sign-in, the link remains displaying sign-in. Header Sign-in link doesn't change into Sign-out after Sign-in to the store and navigating to category pages. 
2. See this video to reproduce. [https://youtu.be/X1jqpPMOSVg](url)

**Comment by shikhamis11** [comment] 2020-02-12 11:56
@monotheist are you able to reproduce this issue on 2.4-dev instance ?

**Comment by devchris79** [comment] 2020-02-12 13:22
Its a caching issue, we saw the same thing so I disabled the cache and the issue went away!

Seems like this has been doing the rounds for a while:
#9156
#20571

**Comment by monotheist** [comment] 2020-02-12 14:39
@devchris79 Is there a solution to this issue? I can't afford to disable cache.

**Comment by devchris79** [comment] 2020-02-12 15:21
As I understand it there was supposed to be a fix to load headers that were not cached last year, unfortunately this doesn't appear to work for you. I don't know if this is down to Magento core functionality or your theme (Ultimo) implementation of the sign in link.

**Comment by devchris79** [comment] 2020-02-17 13:30
I have done a bit more experimentation and the issue appears to be a Magento core caching issue. When Signed in I am sometimes seeing the account link display sign in while already signed in, I can then clear the full page cache while signed in and the issue disappears and pages behave normally for the signed on session.

Ultimo is using core functionality to add the sign in/out link:

![issue](https://user-images.githubusercontent.com/43850303/74657663-a1318280-5188-11ea-8a9f-eb5a1bfa5cec.jpg)

Issue was seen with Magento 2.3.4, Ultimo theme and only using the Magento Cache.

**Comment by monotheist** [comment] 2020-02-17 13:44
@devchris79 Thanks for checking on this. Really appreciate. Is there a possible workaround or fix?

**Comment by devchris79** [comment] 2020-02-17 14:04
Sorry but I don't have anything

**Comment by devchris79** [comment] 2020-02-19 11:42
@shikhamis11 Ultimo is using top.links from xml  /vendor/magento/module-customer/view/frontend/layout/default.xml. This appears to be getting cached in the Magento full page cache and served incorrectly as if the user is signed out.

If I applied cacheable="false" to the authorization-link it works fine, but this kills the entire page cache as far as I know. It seems like Magento has been closing block hole punching through the cache, I have seen that knockout js appears to be used for dynamic data but its a bit beyond my knowledge.

Does this sound like the true issue or has the cachable = false just caused a regeneration that has masked the true root of the problem?

**Comment by devchris79** [comment] 2020-02-19 17:19
I have updated default.xml to the simplest form imaginable and the issue still seems to be there. I now have:

```
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="top.links">
        </referenceBlock>
    </body>
</page>
```
I browse through a few pages, home screen, category, product page etc. while not signed in, then I sign in and browse, the sign in link will incorrectly appear on some pages.

**Comment by shikhamis11** [comment] 2020-02-20 03:28
@devchris79 thanks for all the information .. 
did you try to reproduce the issue at magento clean instance without theme ?

**Comment by devchris79** [comment] 2020-02-21 11:01
Root of the issue seems to be in the Ultimo theme caching, I have taken this up with the authors and will let @monotheist know the outcome.

Luma and blank themes don't show the issue.

**Comment by devchris79** [comment] 2020-02-24 12:14
The issue appears to be a change in 2.3.2 that made view models shared by default, consequently the settings that are built up in cfg.css wouldn't be correct for all the view models (product view, homepage, cat view etc.) There is a shared=false attribute, but I have been unable to get that to work.

The layouts for all pages are defined in
/app/design/frontend/Infortis/ultimo/Infortis_Ultimo/layout/default.xml
this then brings in block
app/design/frontend/Infortis\base/Magento_Theme/layout/default.xml

My quick fix until a theme update was to simply disable the Ultimo caching, I did this by just adding a quick return false in there check:

/app/code/Infortis/Cgen/Plugin/Magento/Framework/App/FrontController.php

```
    protected function shouldCacheRequest()
    {
        $path = $this->getPathInfo();
        return false;
        return in_array($path, [
            'asset/dynamic/assets/m/iult/f/cfg.css']
        );

    }
```

If you have any suggestions please let me know. I would also recommend closing this issue as its not an issue in the Magento core.

**Comment by devchris79** [comment] 2020-03-03 10:37
@shikhamis11 Can you please close this issue as its not a core fault. The author monotheist tells me he is now using an alternative cart software.

**Closed as completed** 2020-03-04 03:29 UTC
Labels: Issue: Format is valid, Reported on 2.3.3

**Comment by ngtuan96lc** [comment] 2020-12-21 06:44
> @shikhamis11 Can you please close this issue as its not a core fault. The author monotheist tells me he is now using an alternative cart software.

Hi @devchris79 , 
I'm facing this issue on Magento version 2.4.1. 
The header is still cached when I switched between websites.

**Comment by devchris79** [comment] 2020-12-21 09:25
@ngtuan96lc Did the theme code change not work? 

We are still at Magento 2.3.5 because we are on a hosted service that doesn't support Elasticsearch. The Ultimo theme has been dead for a while now and I know that there are other issues with 2.4, why don't you consider a theme change as the issues are likely to get worse?

**Comment by ngtuan96lc** [comment] 2020-12-21 09:34
> @shikhamis11 Ultimo is using top.links from xml /vendor/magento/module-customer/view/frontend/layout/default.xml. This appears to be getting cached in the Magento full page cache and served incorrectly as if the user is signed out.
> 
> If I applied cacheable="false" to the authorization-link it works fine, but this kills the entire page cache as far as I know. It seems like Magento has been closing block hole punching through the cache, I have seen that knockout js appears to be used for dynamic data but its a bit beyond my knowledge.
> 
> Does this sound like the true issue or has the cachable = false just caused a regeneration that has masked the true root of the problem?

If disable cache for a block named "top.links". It will affect performance.
so, we couldn't disable it.
Do we have any solution?

**Comment by shikhamis11** [comment] 2020-12-21 09:42
@ngtuan96lc yes `cacheable = false` is not recommended you can implement [view models](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/view-models.html) or load data through knockout js

**Comment by devchris79** [comment] 2020-12-21 09:43
The only way I found to stop the issue was with the post on Feb 24th. 
If you find a better way of correcting the issue I would love to hear it so we can update our code.

The cachable=false command will kill all caching as far as I know.

**Comment by rahulbarot** [comment] 2021-09-29 07:55
@shikhamis11 @devchris79 Any solution for this issue? I am facing this issue on M2.4.2 also.

**Comment by devchris79** [comment] 2021-09-29 08:12
@rahulbarot We moved to Porto theme as its so popular and it has support for the latest Magento core. It had a few issues, but nothing severe.
Ultimo has been dead for quite a while now and the fixes get less practical as time goes by, the post from the 24th Feb did correct the issue for us, but only by stopping the Ultimo cache feature.

**Comment by rahulbarot** [comment] 2021-09-29 08:25
@devchris79 But I am facing this issue with default Magento with varnish cache enabled. None of the solution are seems to be working.
