### ISSUE TITLE
Magento 2 Can't upload images for "disabled" aka "inactive" products using API

### ISSUE THREAD

**Issue by joepperkins** [magento/magento2#36743] opened 2023-01-13 20:29 UTC
### Summary: 
When calling the REST API to upload images for product that are "disabled" aka "inactive, the API responds with.
{"message":"The product can't be saved."}
 HTTP status 400 bad request 

### Preconditions (*)
Adobe Cloud Magento ver. 2.4.3-p2

### Steps to reproduce (*)
1. Set product inactive.
2. Wait for indexing to complete.
3. Call API to add image fails.
4. Set product Active.
5. Wait for indexing to complete.
6. Call API to add image succeeds.

### Expected result (*)
HTTP Status 200 - OK

### Actual result (*)
HTTPS Status 400 - Bad Request
{"message":"The product can't be saved."}

**Comment by engcom-November** [comment] 2023-01-17 14:02
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2023-01-18 04:38
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2023-01-19 05:10
Hi @joepperkins ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance but the issue is not reproducible with below steps performed.
Steps performed:
1. Created a disabled product (Enable product set to No)
2. Sent POST request to - /rest/all/V1/products/{sku}/media using below sample payload and the image is successfully uploaded to both disabled and enabled products - No issue.
_{
        "entry": {
            "media_type": "image",
            "label": "Image",
            "position": 1,
            "disabled": false,
            "types": [
                "image",
                "small_image",
                "thumbnail"
            ],
            "file": "/m/b/mb01-blue-0.png",
            "content": {
                "base64EncodedData": "iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAWtJREFUeNpi/P//P8NgBkwMgxyMOnDUgTDAyMhIDNYF4vNA/B+IDwCxHLoakgEoFxODiQRXQUYi4e3k2gfDjMRajsP3zED8F8pmA+JvUDEYeArEMugOpFcanA/Ef6A0CPwC4uNoag5SnAjJjGI2tKhkg4rLAfFGIH4IxEuBWIjSKKYkDfZCHddLiwChVhokK8YGohwEZYy3aBmEKmDEhOCgreomo+VmZHxsMEQxIc2MAx3FO/DI3RxMmQTZkI9ALDCaSUYdOOrAIeRAPzQ+PxCHUM2FFDb5paGNBPRa5C20bUhxc4sSB4JaLnvxVHWHsbVu6OnACjyOg+HqgXKgGRD/JMKBoD6LDb0dyAPE94hwHAw/hGYcujlwEQmOg+EV9HJgLBmOg+FMWjsQVKR8psCBoDSrQqoDSSmoG6Hpj1wA6ju30LI9+BBX4UsC+Ai0T4BWVd1EIL5PgeO+APECmoXgaGtm1IE0AgABBgAJAICuV8dAUAAAAABJRU5ErkJggg==",
                "type": "image/png",
                "name": "new_image.png"
            }
        }
    }_

Kindly recheck the issue on Magento 2.4-develop instance and provide missing steps if any is the issue is still reproducible.
Thank you.

**Comment by engcom-Hotel** [comment] 2023-02-03 12:21
Dear @joepperkins,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2023-02-03 12:21 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.3-p2
