### ISSUE TITLE
'Go to Checkout' Button on cart page is not working.

### ISSUE THREAD

**Issue by vishal6714** [magento/magento2#1816] opened 2015-09-08 10:58 UTC
![bug-magento2-cart](https://cloud.githubusercontent.com/assets/6058016/9733277/935f1000-5647-11e5-9973-7efe3a3d7a58.png)
Hello Team,
Here we facing an issue for 'Go to Checkout' Button in summary block of cart page. 
There is not any error on console in any browser and still not able to redirect on checkout URL.

**Comment by piotrekkaminski** [comment] 2015-10-08 21:43
@vishal6714 can you let us know the following:
- browser and operating system version
- are you use any blocker extensions (AdBlockers, PrivacyBadger etc)

**Comment by vishal6714** [comment] 2015-10-10 14:43
Hello Team,

Yes, sure.

We are using mozilla firefox & google chrome in windows 7 license version.

We not use any extensions.

Also we are working on Magento2 beta 1.0.0

We also have some list of bugs which we create in github in few days.

Let us know if you have any questions further more.

**Comment by mbrinton01** [comment] 2015-10-20 15:33
Internal issue MAGETWO-44236

**Comment by sdzhepa** [comment] 2015-10-21 13:28
@vishal6714  We can't reproduce this issue for now. Could you please verify whether this issue still present?

**Comment by vishal6714** [comment] 2015-10-22 06:48
Hello Team,

Let us pull latest git commit and will verify again.

Have a happy Navratri and Dashera. (Great Indian Festival).

Thanks

**Comment by ishakhsuvarov** [comment] 2015-12-24 09:14
@vishal6714 Closing this ticket for now. Feel free to reopen if the issue persists.

**Closed by ishakhsuvarov** 2015-12-24 09:14 UTC
Labels: CS, needs update
