### ISSUE TITLE
Discount(s) ignored in Subtotal condition of Free Shipping Cart Rule

### ISSUE THREAD

**Issue by Rickertje** [magento/magento2#35168] opened 2022-03-06 15:21 UTC
### Preconditions (*)
1. M2.4 develop

### Steps to reproduce (*)
1. Clean install
2. Deactivate Flat rate shipping method
3. Activate Free shipping for minimum amount of 99999999
4. Remove alle cart rules. Create 2 new cart rules:
a) TEST with coupon code TEST, no conditions, discount 100 for the whole cart, discard subsequent rules = No
b) FREE SHIPPING no coupon code, condition: subtotal excl VAT > $820, free shipping for shipment with matching items, discard subsequent rules = No
3) Add products to cart for total amount of just a little over $820 > Check the shipping costs
4) Enter promo code TEST > Again check the shipping costs

### Expected result (*)
Free shipping should NOT be applied after entering the promo TEST

### Actual result (*)
Free shipping is still applied.

Observations:
- It's not clear from the dev docs if Cart Rule conditions Subtotal and Subtotal ex VAT should include discounts

![Knipselx](https://user-images.githubusercontent.com/27420995/157225703-00d1511d-9165-440c-8217-f9ec4d37efb1.JPG)
![Knipsel5](https://user-images.githubusercontent.com/27420995/156929482-8d784309-0295-489d-8c3d-9fe8d8929137.JPG)
---
Severity S1/S2

**Comment by Rickertje** [comment] 2022-03-07 10:00
I just tried this on 2.2.10 and it seemed to have worked correctly back then

**Comment by engcom-November** [comment] 2022-03-08 05:13
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue in both the cases: A and B.
In both the cases A and B Shipping Method is not getting applied - No issue
![image](https://user-images.githubusercontent.com/60198231/157169496-8c66f73c-2659-42e2-8407-66be29cd6d5f.png)
![image](https://user-images.githubusercontent.com/60198231/157169525-048aa7aa-40e7-45ac-abbc-a63bf28c9022.png)
@Rickertje , kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by Rickertje** [comment] 2022-03-08 10:12
@magento give me 2.4-develop instance

**Comment by Rickertje** [comment] 2022-03-08 10:53
Hi @engcom-November. I tried develop. Things seemed to have changed since 2.4.0. In your test of case A at least a tablerate shipping methode for 811,88 should be applied. Agree? So why was it not applied?
Because of the changes since 2.4.0 the testcases like I originally described do not produce the problem in develop. But the problem is still here. I will change the problem description and then hopefully you can have another look. I will let you know when finished.

**Comment by Rickertje** [comment] 2022-03-08 11:07
@engcom-November: I changed the steps to reproduce the problem on develop. Can you take another look please?

**Comment by engcom-November** [comment] 2022-03-09 11:40
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-03-09 12:23
Hi @Rickertje Thank you for updating the description. Verified the issue again on Magento 2.4-develop branch and the issue is reproducible. Hence confirming the issue.
![image](https://user-images.githubusercontent.com/60198231/157441192-ac14b39c-ca72-4aea-b22f-923a4b4081c8.png)

**Comment by engcom-November** [comment] 2022-07-07 12:18
Hi @Rickertje ,
Thanks for your response.
Its mentioned in Magento [docs](https://docs.magento.com/user-guide/marketing/price-rules-cart-create.html) that, "In a case of multiple parallel promotions/rules, the Subtotal condition is applied to the base shopping cart **subtotal amount before any discounts.** " If this has to be changed then it can be considered as feature request but not a bug as its an existing behavior. Kindly check the ref guides and provide your inputs on this.
Thank you.

**Comment by engcom-November** [comment] 2022-07-20 10:06
Hi @Rickertje ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-07-20 10:06 UTC
Labels: Component: Shipping, Reproduced on 2.4.x, Priority: P2, Progress: done, Issue: needs update, Reported on 2.4.0, Area: Shipping
