### ISSUE TITLE
2.2.5 wrong swatch admin value when adding value via php

### ISSUE THREAD

**Issue by LouNik1984** [magento/magento2#19775] opened 2018-12-14 10:01 UTC
### Preconditions (*)
 - Magento 2.2.5 with php 7
 - Have a product attribute set as text attribute

### Steps to reproduce (*)
 - add a new option via php code

### Expected result (*)
After the code has run, I can see the new option correctly under the list of options with all values and labels under their right column

### Actual result (*)
New option is added and labels for both admin and store view are correct. However, admin and store values fields are empty. The values of the new option have replaced the values of first item of the list. See attached screenshot: 

![cattura](https://user-images.githubusercontent.com/6501073/49996534-8fa28880-ff8f-11e8-9b00-2ad8e0bfa53d.JPG)

EDIT: I forgot to post the code I'm using to add the new option: 

![cattura](https://user-images.githubusercontent.com/6501073/49996681-fb84f100-ff8f-11e8-966a-d2935381b5b8.JPG)

**Comment by magento-engcom-team** [comment] 2018-12-14 10:01
Hi @LouNik1984. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@LouNik1984 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by LouNik1984** [comment] 2018-12-14 11:13
do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?

How can I reproduce the issue on a given istance? Php code needs to run and I have no way of accessing the files to run the script

**Comment by milindsingh** [comment] 2018-12-14 11:18
@LouNik1984 I don't think its a Magento issue so I am closing it as it cannot be reproduce in the vanilla Magento instance.

**Closed as completed by milindsingh** 2018-12-14 11:18 UTC
Labels: Issue: Format is valid
