### ISSUE TITLE
Google Pay Payment fails with message error 2099 (The customer's bank declined the transaction because a 3D Secure authentication was not performed during checkout. Have the customer authenticate using 3D Secure, then attempt the authorization again.)

### ISSUE THREAD

**Issue by ameerpotrik** [magento/magento2#37962] opened 2023-09-06 04:24 UTC
### Preconditions and environment

Magento version 2.4.6

### Steps to reproduce

3DS enabled from the backend, 3DS enabled via Braintree,
Google Pay is set up in Magento and Braintree, including integration with the website.
Challenge requested - Configured true
Add a product to the cart, proceed to checkout, and place an order via Google Pay.

### Expected result

The order should get placed successfully with Google Pay

### Actual result

Google Pay Payment fails with message error 2099 (The customer's bank declined the transaction because a 3D Secure authentication was not performed during checkout. Have the customer authenticate using 3D Secure, then attempt the authorization again.)

### Additional information

I have reached out to the Braintree support team regarding this error and below is the reply we received from them, hope that will help.

Taking a look at the last Google Pay transactions [p1vbvjr4] we can see indeed a decline with the message: [error 2099](https://developer.paypal.com/braintree/articles/control-panel/transactions/declines#code-2099) - The customer's bank declined the transaction because a 3D Secure authentication was not performed during checkout. Have the customer authenticate using 3D Secure, then attempt the authorization again.

This error was received because the authentication through 3DS was not run for this transaction.

[Google Pay](https://developer.paypal.com/braintree/docs/guides/3d-secure/client-side#using-3d-secure-with-google-pay) transactions are usually out-of-scope for PSD2, however, depending on the tokenization method, you can process 3DS for certain transactions.

While some are tokenized card data, which means Braintree receives a DPAN in lieu of actual card data, other Google Pay payment methods are non-network tokenized (meaning Braintree receives actual card data, just from Google).

The latter, since it's actual card data, is subject to PSD2 and requires 3D Secure as a result. [As non-network tokenized Google Pay payment methods fall under PSD2](https://developer.paypal.com/braintree/docs/guides/3d-secure/client-side/javascript/v3#using-3d-secure-with-google-pay), you'll need to ensure that your integration is [passing non-network tokenized Google Pay payment methods to 3D Secure](https://developer.paypal.com/braintree/docs/guides/3d-secure/client-side/javascript/v3#custom-ui).

In order to do that, check if your Google Pay nonce is non-network tokenized using the code below: 
if (nonce.isNetworkTokenized === false) { // eligible for 3DS Verification }

Then, if details.is_network_tokenized is returned as false from the PaymentMethodNonce object, pass the nonce to threeDSecureParameters:
var threeDSecureParameters = {
amount: '500.00',
nonce: GOOGLE_PAY_NONCE, // Use Google Pay nonce
email: '[test@example.com](mailto:test@example.com)',
billingAddress: {// see example above },additionalInformation: {// see example above },
onLookupComplete: function (data, next) {next();}};"
This should prevent [2099 - Cardholder Authentication Required](https://developer.paypal.com/braintree/articles/control-panel/transactions/declines#code-2099), a 3D Secure specific decline, for Google Pay non-network tokenized card transactions. Some Google Pay cards aren't eligible for 3DS as we don't have the real card data. Cards that weren't tokenized by Google are eligible for 3DS.

As you mentioned, you are currently working with Gene Magento, It's important to keep in mind that the Magento payment plug-in wasn't developed by Braintree, and we have very limited insight into their integration. With that in mind, I strongly recommend [reaching out to the Magento support team](https://support.magento.com/hc/en-us) for more insight about the integration. You can always feel free to share with us any communications you have with them so that we can chime in to offer clarity whenever appropriate.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ameerpotrik** [comment] 2023-09-18 03:55
Was this issue reproducible?

**Comment by engcom-Delta** [comment] 2023-09-22 10:09
@magento give me 2.4-develop instance

**Comment by ameerpotrik** [comment] 2023-10-05 03:42
Hello @engcom-Delta , what are the next action steps?

**Comment by ameerpotrik** [comment] 2023-11-17 11:58
@Henryrchurchill Thank you for sharing your experience. It's reassuring to hear that a fix has been implemented in Magento v2.4.7-beta2. We look forward to the stable release of this version to address the Google Pay payment issue.

**Comment by sumeetmagento** [comment] 2024-01-05 10:10
I understood that this is fixed in Magento v2.4.7-beta2.

How can we fix this issue on Magento ver. 2.4.5-p1 manually?

**Closed as completed** 2024-01-12 14:06 UTC
Labels: Issue: ready for confirmation, Reported on 2.4.6

**Comment by LucScu** [comment] 2024-07-06 10:49
@ameerpotrik i have the same issue on 2.4.6-p3.
Do you have a fix for it?
I just see that gene commerce release new version 4.6.1 (https://support.gene.co.uk/support/solutions/articles/35000228529-braintree-release-notes-for-v4-6-1-adobe-commerce-magento-open-source-v2-4-7-) with the feature "3DS support for Google Pay".

**Comment by engcom-Dash** [comment] 2024-07-09 07:54
@magento give me 2.4-develop instance

**Comment by LucScu** [comment] 2024-07-09 09:50
@engcom-Dash i just opened a ticket with gene support. i hope they'll reply so i will be able to share the answer.

**Comment by controllermodzltd** [comment] 2024-10-30 15:28
Did you manage to find a 2.4 fix for this?

> @engcom-Dash i just opened a ticket with gene support. i hope they'll reply so i will be able to share the answer.

**Comment by Henryrchurchill** [comment] 2024-10-30 15:31
@controllermodzltd In Magento ver. 2.4.7-p1 the issue is resolved. We just turned off GPAY until we managed to update.

**Comment by controllermodzltd** [comment] 2024-10-30 15:33
> @controllermodzltd In Magento ver. 2.4.7-p1 the issue is resolved. We just turned off GPAY until we managed to update.

Do you know if there is any workaround for 2.4.3?
