### ISSUE TITLE
Re-index action required

### ISSUE THREAD

**Issue by vishal6714** [magento/magento2#1075] opened 2015-03-04 09:44 UTC
Hello Team,

I am using Magento ver. 0.42.0-beta10 where i am not able to re-index any indexer. 
There is not any action to apply mass-re-index or single re-index link as it was in previous versions.

So, It seems bug and needs re-index actions both single and mass.

![re-index](https://cloud.githubusercontent.com/assets/6058016/6481151/18e3cc76-c281-11e4-9ef2-12860c754aa4.png)

**Comment by Sanuch** [comment] 2015-03-04 09:52
It looks like a duplicate of [Unable to reindex from backend, bug?](https://github.com/magento/magento2/issues/824)

**Comment by Sanuch** [comment] 2015-03-04 11:22
As wrote @WilliamAtMagento this behavior is as expected by design

You have two ways for re-index:
1. set up cron job e.g. `* * * * * {your_magento_folder}/dev/shell/cron.sh`
2. run console script `php -f  {your_magento_folder}/dev/shell/indexer.php -- reindexall`

**Comment by kokoc** [comment] 2015-03-12 07:38
@vishal6714, This behavior is as expected by design.
Indexing has become a background operation with automatic consideration for partial or full re-indexing.

Do you have other questions regarding indexing?

**Comment by vpelipenko** [comment] 2015-03-27 09:41
Closed. There is no response from contributor.

**Closed by vpelipenko** 2015-03-27 09:41 UTC
Labels: MX, needs update

**Comment by sumanparihar** [comment] 2015-12-18 08:33
i try to do re-index in magento stable version using command bin/magento indexer:reindex catalogsearch_fulltext.

But it's display segment fault error with index status change from "require reindex" to "Processing". 
Please tell me after change status howe i can reindex this .

Where it's lock file create in magento2

Thanks
Suman

**Comment by ghost** [comment] 2016-01-09 15:43
@sumanparihar In a different context, we have a fix for a segmentation fault by setting `ulimit` as shown [here](http://devdocs.magento.com/guides/v2.0/comp-mgr/prereq/prereq_compman-ulimit.html). The segmentation fault is likely why the status is still Processing.

Because this is a closed issue, recommend you open a new one if you still have this issue.
