### ISSUE TITLE
Mini Cart Price issue 

### ISSUE THREAD

**Issue by rishabhrkrai** [magento/magento2#10600] opened 2017-08-21 11:00 UTC
### Preconditions

1. Magento 2.1.7, MySQL 5.7, PHP 7.0
2. Nginx Server

### Steps to reproduce

1. I have a product with price 41.67 and store locale is UK
2. I have a VAT of 20% on the product in UK
3. On the admin section, I enable to show the price on catalog and cart is including VAT.
**Store > Configuration > Sales > Tax > Price Display Setting**
                              Display Product Prices In Catalog is Including Tax
**Store > Configuration > Sales > Tax > Price Display Setting**
                              Display Prices to Including Tax
                              Display Subtotal to  Including Tax
4. On Catalog page unit price is 50.
5. Add product to cart.
6. Click on basket and increase the qty to 2.

### Expected result

1. Unit price should not be changed to 50.01

### Actual result

1. Unit price of the product in the Mini-Cart changed to 50.01

**Comment by manish-mithilasoft** [comment] 2017-08-21 11:22
Strange issue and its no where defined or stated what is the reason.

**Comment by magento-engcom-team** [comment] 2017-09-19 13:32
@RishabhRkRai thank you for your bug report.
We've created internal ticket MAGETWO-75338 to track progress on the issue.

**Comment by Quinten** [comment] 2017-09-26 14:54
I can reproduce this in the 2.2-develop branch.

The calculation is handled in app/code/Magento/Tax/Model/Calculation/AbstractAggregateCalculator.php
around line 151

(but i have no idea what the best practice to fix it could be)

**Comment by KirianM** [comment] 2017-11-04 11:14
I am working on it at #mm17es

**Comment by KirianM** [comment] 2017-11-04 12:46
I can't reproduce it. I followed the steps specified by @RishabhRkRai plus configured a new tax for UK with a 20% VAT and configured that one as the default tax.

<img width="241" alt="qty1" src="https://user-images.githubusercontent.com/844565/32405483-6843639e-c166-11e7-8329-f2491af9c5d8.png">
<img width="225" alt="qty2" src="https://user-images.githubusercontent.com/844565/32405484-686ac984-c166-11e7-9593-52e65464bd66.png">

**Comment by okorshenko** [comment] 2017-12-14 12:48
Hi @RishabhRkRai 
We are closing this issue. @KirianM thank you for research.

**Closed as completed by okorshenko** 2017-12-14 12:48 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Issue:  Cannot Reproduce, Issue: Format is valid
