### ISSUE TITLE
2.3.3 Issue with catalog_product_view.xml not affecting all product types.

### ISSUE THREAD

**Issue by kieran85james** [magento/magento2#26343] opened 2020-01-10 10:32 UTC
### Preconditions (*)

1. Fresh install of Magento 2.3.3
2. Create the needed directories/files for custom theme
3. Add a container to custom catalog_product_view.xml within your theme's Magento_Catalog/layout/ directory

### Steps to reproduce (*)

1. Content > Widgets > Add Widget > CMS Static Block > Select Theme > Layout Updates > Add layout update
2. Select Display on All product types & your custom container will show
3. Select a specific product type such as simple product and container doesn't show

### Expected result (*)

1. Select all product types > shows container
2. Select simple product type or any other specific product type > shows container

### Actual result (*)

1. Select all product types > shows container
2. Select simple product type or any other specific product type > Container **doesn't** show

### Extra Information
As Magento docs say the catalog_product_view should affect all product types: https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/layouts/product-layouts.html#product-view-page

This isn't an issue on 2.3.1 and it works as expected.

### Example of catalog_product_view.xml
```xml
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <!-- Custom Containers -->
        <referenceContainer name="content">
            <referenceContainer name="product.info.main">
                <container name="test.container" label="Test Container" after="product.name" htmlTag="div" htmlClass="test-container" />
            </referenceContainer>
        </referenceContainer>
    </body>
</page>
```

**Comment by engcom-Echo** [comment] 2020-01-13 12:04
Hi @kieran85james. Thank you for your report.

Unfortunately, I am not able to reproduce these issues. 

Maybe you do not apply and configure a storefront theme.
If you do not configure the custom theme, a container doesn't show on the storefront. 

Try to follow the next guide https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/theme-apply.html

Could you take a look?

**Comment by kieran85james** [comment] 2020-01-13 12:43
I have definitely applied and configured a storefront theme.

Surely, if I hadn't done that, the container wouldn't show under all product types either but it does.

Just to be clear, any containers set do show on the front-end. I am talking about the container not showing as an option when setting up a widget.

Did you test on Magento 2.3.3?

**Comment by engcom-Echo** [comment] 2020-01-13 16:30
@kieran85james 
> I am talking about the container not showing as an option when setting up a widget.

Thank.  The common layout is universal for all types. You have the ability to create a configuration for each individual type of product if you want to use a different layout.

**Comment by kieran85james** [comment] 2020-01-13 20:25
I am aware of this. If I create the container in the xml related to simple product type only it will then show in the widget layout update under simple product type as well.. but this means adding a container to all product type xml files rather than just the one.

On an older install of magento we have 2.3.1 we only have to apply our container in catalog_product_view and it works for all product types.

**Comment by magento-engcom-team** [comment] 2020-01-14 07:20
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30402` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment] 2020-08-04 21:07
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-08-04 21:07
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-08-04 21:08
Hi @sdzhepa, here is your [Magento instance](https://i-26343-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26343-2-4-develop.instances.magento-community.engineering/admin_0f0f](https://i-26343-2-4-develop.instances.magento-community.engineering/admin_0f0f)
Login: `656f5e0a` Password: `e248991d4a84`
Instance will be terminated in up to 3 hours.

**Comment by engcom-November** [comment] 2024-10-30 11:42
As this is a old issue, we tried to reproduce this on 2.4-develop and the issue is not reproducible.

Hence closing this.

**Closed as completed by engcom-November** 2024-10-30 11:42 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Widget, Component: Theme, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P2, Severity: S2, Progress: done, CD, Reported on 2.3.1, Area: Product
