### ISSUE TITLE
Attribute values cleared after changing attribute group

### ISSUE THREAD

**Issue by Tjitse-E** [magento/magento2#26895] opened 2020-02-17 10:49 UTC
### Related issues:
- https://github.com/magento/magento2/issues/15433

### Preconditions (*)

1. 2.4-develop  community develop instance

### Steps to reproduce (*)

1. Create a new product with a price of $100 and the default attribute set
2. Create a new attribute set based on 'Default'. Create a new attribute group, call it 'New pricing group' and add the price and price view attributes to this group.
3. Open the product you've created in step 1
4. Try to change the attribute set to the attribute set you've created in step 2.

### Expected result (*)

1. The product is assigned to the new attribute set with all of the attribute values intact.

### Actual result (*)

1. [Screenshots, logs or description]
2. The price attribute is now empty, because it was moved to another attribute group.

In Magento 2.3.x the same issue exists, only the there is an error thrown by Magento: "A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later."

![ Magento Admin 2020-02-17 11-46-56](https://user-images.githubusercontent.com/14849044/74647032-3a599c80-517b-11ea-8d56-bc7dce1e047e.png)

**Comment by Tjitse-E** [comment] 2020-02-17 12:29
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-17 12:29
Hi @Tjitse-E. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-17 12:30
Hi @Tjitse-E, here is your [Magento instance](https://i-26895-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26895-2-4-develop.instances.magento-community.engineering/admin_51bd](https://i-26895-2-4-develop.instances.magento-community.engineering/admin_51bd)
Login: `b792e526` Password: `364574a44e7e`
Instance will be terminated in up to 3 hours.

**Comment by Tjitse-E** [comment] 2020-02-17 13:11
Possible duplicate: https://github.com/magento/magento2/issues/11516

**Comment by engcom-Alfa** [comment] 2020-02-19 14:24
Hi @Tjitse-E. Thank you for your report.
This issue is duplicate to #11516.
The problem was reproduced on 2.4-develop instance and confirmed. The status is now "ready for dev"
So, we have to close it.
Thanks!

**Comment by engcom-Alfa** [comment] 2020-02-19 14:25
Duplicate of #11516

**Closed as completed by engcom-Alfa** 2020-02-19 14:25 UTC
Labels: Issue: Format is valid, Reported on 2.3.x
