### ISSUE TITLE
Widget conditions (in a block) are stored in database but not in back-office

### ISSUE THREAD

**Issue by cduperron** [magento/magento2#7054] opened 2016-10-17 13:11 UTC
### Preconditions

1. Magento 2.0.7
### Steps to reproduce

1. Connect to back-office
2. Create a new block in `Content` > `Blocks`
3. In this new block, click on the widget button into the WYSIWYG to add a new widget
4. Choose `Catalog Products List` as widget type
5. Add some conditions (whatever the conditions)
6. Click on `Insert Widget`
### Expected result

1. Double click on the widget icon (into the `Content` area)
2. Conditions are saved and are displayed in back-office
### Actual result

1. Conditions are stored in database but nothing appears

Screenshot : http://prnt.sc/cvdmi7

**Comment by sevos1984** [comment] 2016-10-19 13:14
Could you please update your code to latest 2.0 version?

**Comment by sevos1984** [comment] 2016-11-04 10:13
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-11-04 10:13 UTC
Labels: bug report, Progress: needs update, Component: Cms
