### ISSUE TITLE
Cannot deploy sample data on fresh install

### ISSUE THREAD

**Issue by mindsoft-gr** [magento/magento2#36680] opened 2022-12-29 11:55 UTC
### Preconditions and environment

- Magento version 2.4.5

### Steps to reproduce

1. Install magento2 v2.4.5
2. execute sampledata:deploy

### Expected result

Sample data is deployed

### Actual result

```
<warning>Warning from repo.magento.com: Your Magento authentication keys are invalid. Please double-check your keys in your Marketplace account. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html</warning>
<warning>Warning from repo.magento.com: Your Magento authentication keys are invalid. Please double-check your keys in your Marketplace account. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html</warning>
<warning>Warning from repo.magento.com: Your Magento authentication keys are invalid. Please double-check your keys in your Marketplace account. For instructions, visit https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html</warning>
```

### Additional information

I already inserted my marketplace keys when asked by composer. That's how I installed magento in the first place.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-12-29 13:11
Hi @mindsoft-gr,

Thank you for reporting and collaboration.We are not able to reproduce the issue.Kindly refer the screenshots.


**Steps to Reproduce** :

1. Install Magento `2.4.5`
2. Execute sampledata:deploy


We deployed sampledata successfully.


<img width="1497" alt="Screenshot 2022-12-29 at 6 15 11 PM" src="https://user-images.githubusercontent.com/51680745/209955652-34e5c19b-54f4-40d4-bc5e-657136bf4bf3.png">



<img width="1495" alt="Screenshot 2022-12-29 at 6 15 32 PM" src="https://user-images.githubusercontent.com/51680745/209955660-7342c753-9342-4628-9867-b8556f7180ef.png">




Kindly let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-01-10 06:09
Hi @mindsoft-gr,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-01-10 06:11
Hi @mindsoft-gr,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-01-10 06:11 UTC
Labels: Issue: needs update, Reported on 2.4.5
