### ISSUE TITLE
PHP8.1 : Tests failures

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#35683] opened 2022-06-27 12:25 UTC
### Summary (*)

Launching Unit tests with M2.4.4 and PHP8.1 gives errors and failures

### Examples (*)

Errors : 

```
1) PayPal\Braintree\Test\Unit\Block\FormTest::testIsVaultEnabled
TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, first array member is not a valid class name or object
/var/www/html/vendor/magento/framework/Session/SessionManager.php:169
/var/www/html/vendor/paypal/module-braintree-core/Block/Form.php:116
/var/www/html/vendor/paypal/module-braintree-core/Test/Unit/Block/FormTest.php:156
2) PayPal\Braintree\Test\Unit\Ui\Component\Report\Filters\Type\DateRangeTest::testPrepare with data set #1 ('test_date', array(array(null, '11-05-2015')), array('2015-05-11T23:59:00+0000', 'lteq'))
Exception: Deprecated Functionality: DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in /var/www/html/vendor/paypal/module-braintree-core/Test/Unit/Ui/Component/Report/Filters/Type/DateRangeTest.php on line 117
/var/www/html/vendor/magento/framework/App/ErrorHandler.php:61
/var/www/html/vendor/paypal/module-braintree-core/Test/Unit/Ui/Component/Report/Filters/Type/DateRangeTest.php:117
--
```

Failures (I have 153 failures, I give you only one for example) : 
```
153) Magento\Framework\ObjectManager\Test\Unit\Config\XsdTest::testSchemaCorrectlyIdentifiesInvalidXml with data set "virtualtype with digits_and_prefix_slash" ('<config xmlns:xsi="http://www...onfig/>', array('Element 'virtualType', attrib...e: 2\n', 'Element 'virtualType', attrib...e: 2\n', 'Element 'virtualType', attrib...e: 2\n'))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => 'Element 'virtualType', attrib...e: 2\n'
-    1 => 'Element 'virtualType', attribute 'name': '\777Digits\IsNotAllowed' is not a valid value of the atomic type 'phpClassName'.\n
+    1 => 'Element 'virtualType', attribute 'name': Warning: No precomputed value available, the value was either invalid or something strange happened.\n
     Line: 2\n
     '
-    2 => 'Element 'virtualType', attrib...e: 2\n'
 )
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ihor-sviziev** [comment] 2022-07-05 08:31
@Nuranto, I think it's a duplicate of https://github.com/magento/magento2/issues/34733

**Comment by Nuranto** [comment] 2022-07-05 11:24
@ihor-sviziev, Oh yes probably. I didn't find it before creating this one. (And I forgot it existed, even if I commented on it on May :p )

I think we could keep this one open for the errors though, which seem to be PHP8.1-compatibility issues.

**Comment by engcom-Charlie** [comment] 2022-07-07 15:29
Hi @Nuranto,

Thank you for your contribution!

In order to reproduce this issue, I have followed below 2 approaches.

1. Installed Magento 2.4-develop with PHP 8.1, run ./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist. Got below result.
<img width="674" alt="image" src="https://user-images.githubusercontent.com/51680850/177811821-a7f59da6-009f-40cb-b87f-5d1e8af836b2.png">


2. Installed Magento 2.4.4 with PHP 8.1, run ./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist. Got below result.
<img width="755" alt="image" src="https://user-images.githubusercontent.com/51680850/177811869-c94a1cb9-9a4e-4741-9992-9e8f5bd0e58a.png">

As per the above results, the failures(3) from 2.4.4(the reported magento version from the issue description) are very less with comparison to 153 as mentioned in issue description.

Kindly let us know if we are missing any other step or else can you please cross check once in order to investigate it further.

Thank you in advance!

**Comment by engcom-Charlie** [comment] 2022-07-08 07:07
@Nuranto, @ihor-sviziev as per above [comment](https://github.com/magento/magento2/issues/35683#issuecomment-1177810919), I have updated the [#34733](https://github.com/magento/magento2/issues/34733) issue by adding this issue's url and also added Failures examples.

Closing this issue now considering its a duplicate of [#34733](https://github.com/magento/magento2/issues/34733)

**Closed as completed** 2022-07-08 07:08 UTC
Labels: Triage: Dev.Experience, Issue: needs update
