### ISSUE TITLE
PHP8.1 readonly syntax error on setup:di:compile

### ISSUE THREAD

**Issue by pabman11** [magento/magento2#36521] opened 2022-11-23 12:35 UTC
### Preconditions and environment

- Magento 2.4.5-p1
- PHP 8.1

### Steps to reproduce

Execute bin/magento setup:di:compile

### Expected result

Task is completed succesfully

### Actual result

bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/9 [===>------------------------]  11% < 1 sec 133.0 MiBsyntax error, unexpected token "readonly", expecting identifier#0 /html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass()
#1 /html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract()
#2 /html/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php(61): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList()
#3 /html/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation()
#4 /html/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(216): Magento\Setup\Module\Di\App\Task\Manager->process()
#5 /html/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DiCompileCommand->execute()
#6 /html/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#7 /html/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#8 /html/vendor/magento/framework/Console/Cli.php(116): Symfony\Component\Console\Application->doRun()
#9 /html/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()
#10 /html/bin/magento(23): Symfony\Component\Console\Application->run()
#11 {main}

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by pabman11** [comment] 2022-11-23 12:38
@magento give me 2.4-develop instance

**Comment by subbu1993** [comment] 2022-11-23 20:33
@magento give me 2.4.3-p2 instance

**Comment by engcom-Bravo** [comment] 2022-11-24 12:30
Hi @subbu1993,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

`Execute bin/magento setup:di:compile`


<img width="696" alt="Screenshot 2022-11-24 at 12 33 33 PM" src="https://user-images.githubusercontent.com/51680745/203784937-b2de45b2-fb72-47a6-8270-ce0a28828ea5.png">




Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by pabman11** [comment] 2022-11-24 12:34
Hi @engcom-Bravo ,
¿What is the php version that are you using? Mine is PHP 8.1.12

**Comment by hostep** [comment] 2022-11-24 21:03
@pabman11: since this is about the `readonly` keyword, can you maybe specify what PHP classes you have that use this new syntax? Is it a PHP class that represents a plugin, or is it a PHP class that another PHP class plugins to? Or even something else ...?

**Comment by pabman11** [comment] 2022-11-25 08:07
That's the problem @hostep , this is a light project. Luma based for frontend, some modules on app/ and others on vendor/

I searched the `readonly` keyword at all project. Nothing found. And as you said, the error output of `setup:di:compile` doesn't tell anything. It' doesn't matter if you give the -vvv parameter,  the output is the same.

**Comment by pabman11** [comment] 2022-11-28 08:49
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-28 13:23
Hi @pabman11,

Thanks for your update.

We are using PHP 8.1




<img width="662" alt="Screenshot 2022-11-28 at 12 07 38 PM" src="https://user-images.githubusercontent.com/51680745/204288184-856e9ece-15c4-444f-8051-562397f8b9a3.png">


<img width="533" alt="Screenshot 2022-11-28 at 12 47 43 PM" src="https://user-images.githubusercontent.com/51680745/204288255-326bae5b-9eef-4ac2-9f47-10ac25c86e77.png">

Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue..

Thanks.

**Comment by engcom-Bravo** [comment] 2022-12-12 06:04
Hi @pabman11,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-12-12 06:04 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.5-p1

**Comment by sumeetmagento** [comment] 2022-12-26 07:06
Hi @pabman11 @subbu1993 @hostep 

Are you able to resolve this issue we are also getting this issue after upgrading Magento from 2.4 to 2.4.5-p1

Thanks

**Comment by pabman11** [comment] 2022-12-26 07:17
Hi, sorry for not adding more details, but I've discovered that one of the external modules was the responsible.

This can be closed, of course.
