### ISSUE TITLE
Cannot mass update Enable Qty Increments & Qty Increments attributes 

### ISSUE THREAD

**Issue by stevekem** [magento/magento2#29544] opened 2020-08-14 17:04 UTC
### Preconditions (*)
1. 2.4.0 (and 2.4-develop)

### Steps to reproduce (*)
1. Go to Admin > Catalog > Products
2. Check 1 or more products
3. Select dropdown Actions > Update attributes
4. Under Advanced Inventory > Enable Qty Increments
    Check Change, uncheck Use Config Settings and change to Yes
5. Under Advanced Inventory > Qty Increments
    Check Change, uncheck Use Config Settings and change to 2
6. Hit Save button
7. Page is redirected back to Products list and message is generated "Message is added to queue"
8. Run  twice CLI command -  bin/magento cron:run

### Expected result (*)
1. Attribute Enable Qty Increments would be updated to Yes for all selected products.
2. Attribute Qty Increments would be updated to 2 for all selected products.

### Actual result (*)
1. Neither attribute is updated.

Screen grab showing issue in 2.4.0 instance: https://drive.google.com/file/d/1hGk9v4IFMzbIWkMPyHScedeTtNIp8bL8/view

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by stevekem** [comment] 2020-08-14 17:11
Previously reported it (issue #29215) and bug was confirmed and reproduced in latest 2.4.0 instance but was closed because Rabbit MQ was not installed in instance. We did have Rabbit MQ installed on OUR site and bug is still reproducible. Only these 2 attributes seem to be affected, all others (that we tested) are updating fine with mass update using steps above.

**Comment by stevekem** [comment] 2020-08-14 17:14
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-08-14 17:14
Hi @stevekem. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-08-14 17:16
Hi @stevekem, here is your [Magento instance](https://i-29544-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29544-2-4-develop.instances.magento-community.engineering/admin_902c](https://i-29544-2-4-develop.instances.magento-community.engineering/admin_902c)
Login: `bbb94b13` Password: `08c4c669ac8e`
Instance will be terminated in up to 3 hours.

**Comment by stevekem** [comment] 2020-08-14 17:27
Issue is reproducible on instance.

**Comment by sdzhepa** [comment] 2020-08-14 18:17
@engcom-Oscar 

Could you please re-check this issue?

Note: Previous report https://github.com/magento/magento2/issues/29215 I closed due to https://github.com/magento/magento2/issues/29215#issuecomment-664602234 but seems I was wrong

**Comment by magento-engcom-team** [comment] 2020-08-17 16:30
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36787` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by shyam100379** [comment] 2020-10-07 06:14
Hello there,

This issue is there in Magento ver. 2.3.3 as well. All other attributes are updating other than this two:  Enable Qty Increments and Qty Increments via bulk attibute update. 
I would like to know whether any patches are available to solve this for old M2 versions.

Please help.

**Comment by bubasuma** [comment] 2020-11-24 22:15
Internal Magento team is working on this issue right now.

**Comment by magento-engcom-team** [comment] 2020-12-17 22:59
Hi @stevekem. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-36787` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Closed as completed** 2020-12-17 22:58 UTC
Labels: Issue: Confirmed, Issue: Format is valid, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P2, Severity: S2, Component: Mass Update attributes, Progress: done, Reported on 2.4.0
