### ISSUE TITLE
GraphQL returns null address if optional telephone is set as empty string

### ISSUE THREAD

**Issue by Magepim** [magento/magento2#30218] opened 2020-09-28 12:20 UTC
### Preconditions (*)

1. Version 2.4.0 and 2.4-develop
2.

### Steps to reproduce (*)

1.Configure Magento address settings to have telephone number as optional.
2. Using GraphQL add a billing address to a quote using an empty string as the telephone value
3. Execute cart query via GraphQL.  Billing address will return as 'null'

### Expected result (*)

1. Billing address expected to return in GraphQL response with full address details shown
2.

### Actual result (*)

1. billing address returns as null.
2. This is caused because the telephone field in the CartAddressInput in the GraphQL schema is marked as non-nullable. Magento saved the telephone value as null in the quote address when it is passed an empty string.  The address is then validated against the schema when the response is being prepared and fails the schema validation.

### Additional info from Engcom
**Steps to reproduce**
1. From Admin, go to _Stores - Configuration - Customer - Customer Configuration - Name and Address Options_. Set **Show Telephone** to **Optional**
![show_telephone](https://user-images.githubusercontent.com/51680745/97709480-1351b980-1ac3-11eb-95c0-15b105945c33.png)
2. Using GraphQL mutation, add a product to Cart
3. Set Billing Address on cart using the following Mutation 
```graphql
mutation {
  setBillingAddressOnCart(
    input: {
      cart_id: "YOrpn8PaE1sNO88W4KTqGlMu1UB6Rpoh"
      billing_address: {
        address: {
          firstname: "Bob"
          lastname: "Roll"
          company: "Magento"
          street: [
            "Magento Pkwy"
            "Main Street"
          ]
          city: "Austin"
          region: "TX"
          postcode: "78758"
          telephone: ""        #<---- note that the telephone is an empty string. 
          country_code: "US"
          save_in_address_book: true
        }
        same_as_shipping: false
      }
    }
  ) {
    cart {
      billing_address {
        firstname
        lastname
        company
        street
        city
        region {
          code
          label
        }
        postcode
        telephone
        country {
          code
          label
        }
      }
    }
  }
}
```
4. Query Cart 
```graphql
query{
  cart(cart_id: "YOrpn8PaE1sNO88W4KTqGlMu1UB6Rpoh"){
    billing_address{
      city
      firstname
      lastname
      telephone
      region{
        code
      }
      street
    }
    items{
      id
      quantity
      product{
        name
      }
    }
  }
}
```
**Actual Result**
Cart query displayed Billing Adress as _null_
```graphql
{
  "data": {
    "cart": {
      "billing_address": null,
      "items": [
        {
          "id": "1",
          "quantity": 3,
          "product": {
            "name": "Sproduct"
          }
        }
      ]
    }
  }
}
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Magepim** [comment] 2020-09-28 14:55
@magento give me 2.4-develop instance

**Comment by Magepim** [comment] 2020-09-28 15:01
@magento I am working on this

**Comment by Magepim** [comment] 2020-09-28 15:01
@magento add to contributors team

**Comment by ashish-wagento** [comment] 2020-10-10 09:05
@magento I am working on this.

**Comment by ashish-wagento** [comment] 2020-10-10 09:09
#dmcdindia2020

**Comment by engcom-Bravo** [comment] 2020-10-30 13:27
The issue is reproducible on the latest 2.4-develop. Additional info from Engcom is added to the description

**Comment by magento-engcom-team** [comment] 2020-10-30 13:32
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38815` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by SaftaArtem** [comment] 2020-11-18 11:51
@magento add to contributors team

**Comment by SaftaArtem** [comment] 2020-11-18 12:09
@magento I am working on this

**Comment by SaftaArtem** [comment] 2020-11-19 12:45
@magento give me test instance

**Comment by SaftaArtem** [comment] 2020-11-19 12:47
@magento give me 2.4-develop instance

**Comment by SaftaArtem** [comment] 2020-11-19 16:21
@magento run all tests

**Closed as completed** 2021-08-24 18:45 UTC
Labels: Issue: Confirmed, Triage: Dev.Experience, Reproduced on 2.4.x, Component: SalesGraphQl, Component: CustomerGraphQl, Priority: P2, Severity: S2, Progress: done, Event: dmcdindia2020, Reported on 2.4.0
