### ISSUE TITLE
Magento EE license file name placeholder is still not replaced with proper value

### ISSUE THREAD

**Issue by orlangur** [magento/magento2#6940] opened 2016-10-10 07:21 UTC
### Steps to reproduce

1. Open https://github.com/magento/magento2/blob/develop/COPYING.txt#L7
### Expected result

1. `<insert file name of the MEE license>` placeholder must be replaced with file name of EE license added to CE repository or the whole sentence must be reworded to eliminate this placeholder
### Actual result

1. `<insert file name of the MEE license>` is observed

**Comment by veloraven** [comment] 2016-10-10 10:57
I’m closing this issue because it is a duplicate of #5528

**Closed as completed by veloraven** 2016-10-10 10:57 UTC
