### ISSUE TITLE
Attributes not showing up when creating Product Configurations

### ISSUE THREAD

**Issue by jerome-zhang** [magento/magento2#27508] opened 2020-03-31 06:15 UTC
**Summary**

When we try to assign simple products to a configurable product, not all the product attributes show in the attribute grid of 'Step 1: Select Attributes'. You have to switch the pagination to show 200 items to make all the attributes appear.

### Preconditions (*)

1. Install Magento version 2.3.4
2. Have sample data installed

### Steps to reproduce (*)

1. Login to Magento Admin
2. Create a configurable item
3. Under Configurations tab, click 'Create Configurations'
4. When the 'Create Product Configurations' panel opened, you will see the grid says 7 records found, but you can only see 3 in the grid, or something like that https://www.screencast.com/t/SP8z5s53 

### Expected result (*)

1. All the product attributes that can be used to create simple products should be shown in the grid.

### Actual result (*)

1. Only few attribute shows https://www.screencast.com/t/SP8z5s53

**Comment by ajijshekh123** [comment] 2020-03-31 07:14
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-31 07:14
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-03-31 07:15
Hi @ajijshekh123, here is your [Magento instance](https://i-27508-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27508-2-4-develop.instances.magento-community.engineering/admin_f46c](https://i-27508-2-4-develop.instances.magento-community.engineering/admin_f46c)
Login: `acc70c0b` Password: `c59d6c38de4f`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2020-03-31 07:43
Hi @jerome-zhang ,
I have verified this issue as per your steps, actual result and expected result.
I can't able to verify this issue in the Latest Magento 2.4 Instance.
Please see attached screenshot:

![Attributecount_Issue](https://user-images.githubusercontent.com/24711761/78000056-4b3c2700-7351-11ea-9c23-f88db176e495.png)

Can you please share the video? I will verify this issue.

Thanks.

**Comment by jerome-zhang** [comment] 2020-03-31 09:10
@ajijshekh123 , can you try to add more attributes, i am assuming only 3 will be shown?

**Comment by jerome-zhang** [comment] 2020-03-31 09:14
@ajijshekh123 here is the video: https://www.screencast.com/t/WuUuxo6s3p

**Comment by ajijshekh123** [comment] 2020-03-31 10:02
@jerome-zhang - Please review the below video:
https://drive.google.com/file/d/1xKZUQwA0WyjXDfYtAXpk50F5gveYjrNG/view?usp=sharing
Still, This issue is not reproduced.

Thanks.

**Comment by jerome-zhang** [comment] 2020-04-01 01:07
Hi @ajijshekh123 , can you try 20 per page in your demo?

**Comment by ajijshekh123** [comment] 2020-04-01 05:05
Okay @jerome-zhang , Let me try and update you.

**Comment by ajijshekh123** [comment] 2020-04-03 06:12
Hi @jerome-zhang ,

I have reverified this issue of the 20 pagination list in my local demo but still, the issue is not reproduced.
Please verify your customization code Or Extension configuration.
if you don't found this issue again please let me know so I will close this issue.
please update your thought here.

![1](https://user-images.githubusercontent.com/24711761/78329764-24276480-75a0-11ea-9f79-d665cff71166.png)


Thanks.

**Comment by ajijshekh123** [comment] 2020-04-10 08:27
@jerome-zhang - Let me close this issue because this issue is not reproduced in the Latest Magento 2.4 instance.
If you have any issue you can reopen feel free.

Thanks.

**Closed as completed by ajijshekh123** 2020-04-10 08:27 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid, Reported on 2.3.4
