### ISSUE TITLE
Bundle product with option type radio and dropdown can be added to the cart with multiple choices

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#26110] opened 2019-10-31 16:02 UTC
### Preconditions (*)

1. Sample Data

### Steps to reproduce (*)

1. Add product to the cart
```graphql
mutation addBundle(
  $cart_id: String!
) {
  addBundleProductsToCart(
    input: {
      cart_id: $cart_id
      cart_items: {
        data: {
          quantity: 1
          sku: "24-WG080"
        }
        bundle_options: [
          {
            id: 1
            quantity: 1
            value: [
              "1"
              "2"
              "3"
            ]
          }
          {
            id: 2
            quantity: 1
            value: [
              "4"
            ]
          }
                    {
            id: 3
            quantity: 1
            value: [
              "5"
            ]
          }
                    {
            id: 4
            quantity: 1
            value: [
              "8"
            ]
          }
        ]
      }
    }
  ) {
    cart {
      items {
        id
        quantity
        product {
          sku
        }
        ... on BundleCartItem {
          bundle_options {
            id
            label
            type
            values {
              id
              label
              quantity
              __typename
            }
          }
        }
      }
    }
  }
}
```

### Expected result (*)

1. Some message that complains about invalid input for BundleItem.type: radio/dropdown

### Actual result (*)

1. Successfully added to cart

### Additional information 
The issue was confirmed again on the lates `2.4-develop` code. May 28, 2020
In general it is possible to add to Shopping Cart and place order with option type radio and dropdown with multiple choices. This flow is not possible using UI on Storefront.
More details: https://github.com/magento/magento2/issues/26110#issuecomment-635308289

**Comment by magento-engcom-team** [comment] 2019-12-18 21:26
:white_check_mark: Confirmed by @lenaorobei 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29908` were created

**Issue Available**: @lenaorobei, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sedonik** [comment] 2019-12-18 23:25
Hi @lenaorobei,

I've created [PR #26122](https://github.com/magento/magento2/pull/26122)
Could you check is it implemented correctly?

Thanks.

**Comment by lenaorobei** [comment] 2020-05-27 14:37
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-27 14:37
Hi @lenaorobei. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-05-27 14:38
Hi @lenaorobei, here is your [Magento instance](https://i-26110-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26110-2-4-develop.instances.magento-community.engineering/admin_7b6b](https://i-26110-2-4-develop.instances.magento-community.engineering/admin_7b6b)
Login: `79ed051f` Password: `9a178b5c48e9`
Instance will be terminated in up to 3 hours.

**Comment by chalov-anton** [comment] 2020-05-28 12:23
Rechecked on the latest Magento 2.4-develop

The issue is still reproducible.
I can successfully perform the following queries and Place an order: 
```graphql
1. addBundleProductsToCart
2. setBillingAddressOnCart
3. setShippingAddressesOnCart
4. setShippingMethodsOnCart
5. setPaymentMethodOnCart 
```
and Place order 
```graphql
mutation {
  placeOrder(input: {cart_id: "AgfUXQZms2gu5SUTPHRvisT8VnzPLdF5"}) {
    order {
      order_number
    }
  }
}

response: 
{
  "data": {
    "placeOrder": {
      "order": {
        "order_number": "000000003"
      }
    }
  }
}
```
The order is created in Admin Panel
![order_admin](https://user-images.githubusercontent.com/45624059/83140291-86ab6580-a0f6-11ea-9580-c6bdf73ff58d.png)

Admin can successfully:
1. Send Email 
2. Invoice
3. Ship
and **Complete** the order
![order_admin_complete](https://user-images.githubusercontent.com/45624059/83140654-151fe700-a0f7-11ea-8035-fcb7b8922670.png)

**Closed as completed** 2020-08-11 19:33 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Bundle, Reproduced on 2.4.x, Component: BundleGraphQl, Priority: P2, Severity: S2, Triage: Done, Project: GraphQL
