### ISSUE TITLE
Partially shipped and partially refunded order not moving to a "Complete" status

### ISSUE THREAD

**Issue by graemelambert** [magento/magento2#23270] opened 2019-06-14 14:59 UTC
### Preconditions (*)

1. Magento 2.2.8

### Steps to reproduce (*)

1. Place an order for more than 1 of the same item
2. Ship less than the quantity ordered
3. Generate a creditmemo and refund the quantity not shipped

### Expected result (*)

1. Order moves to `Complete` status as all items either shipped or refunded

### Actual result (*)

1. Order stays in `Processing`

I believe the cause of this is `\Magento\Sales\Model\Order::isRefunded`;

```
    /**
     * Check if item is refunded.
     *
     * @param OrderItemInterface $item
     * @return bool
     */
    private function isRefunded(OrderItemInterface $item): bool
    {
        return $item->getQtyRefunded() == $item->getQtyOrdered();
    }
```

`isRefunded` returns `false`, so `canShip` returns `true`, so `\Magento\Sales\Model\Order\StateResolver::getStateForOrder` never returns a `Complete` status

**Comment by graemelambert** [comment] 2019-06-14 15:00
@magento give me 2.2.8 instance

**Comment by magento-engcom-team** [comment] 2019-06-14 15:01
Hi @graemelambert. Thank you for your request. I'm working on Magento 2.2.8 instance for you

**Comment by magento-engcom-team** [comment] 2019-06-14 15:01
Hi @graemelambert, here is your [Magento instance](https://i-23270-2-2-8.instances.magento-community.engineering).
Admin access: [https://i-23270-2-2-8.instances.magento-community.engineering/admin](https://i-23270-2-2-8.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by graemelambert** [comment] 2019-06-14 15:22
Steps replicated on vanilla Magento 2.2.8 instance

**Comment by krishprakash** [comment] 2019-06-14 15:35
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-06-14 15:35
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-06-14 15:36
Hi @krishprakash, here is your [Magento instance](https://i-23270-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23270-2-3-develop.instances.magento-community.engineering/admin](https://i-23270-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-06-14 16:07
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17509` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sivaschenko** [comment] 2019-06-16 19:15
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-06-16 19:15
Hi @sivaschenko. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-06-16 19:16
Hi @sivaschenko, here is your [Magento instance](https://i-23270-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23270-2-3-develop.instances.magento-community.engineering/admin](https://i-23270-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by syed92hasan** [comment] 2019-06-18 10:43
I am working on this at #MM19UK

**Comment by engcom-Alfa** [comment] 2019-08-02 08:30
Hello @graemelambert !
Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by engcom-Alfa** 2019-08-02 08:30 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Admin
