### ISSUE TITLE
Cache Import Products Disabled

### ISSUE THREAD

**Issue by thammanjaku** [magento/magento2#37195] opened 2023-03-13 04:33 UTC
### Preconditions and environment

- Magento version 2.3.3
- Cache Import Products Disabled. I cannot upload new product and edit existing product.  
- How to re-enable it? 
- 
<img width="870" alt="image" src="https://user-images.githubusercontent.com/127713083/224608255-2e9c0bf5-7b81-4214-ae49-1e7e1043e6a0.png">

### Steps to reproduce

1. Go to Catalog > Products > Add product.
2. Fill in product details and upload photos. 
3. Error message- The stock item was unable to be saved. Please try again. 

### Expected result

Product upload successfully. 

### Actual result

Error message- The stock item was unable to be saved. Please try again. 
![image](https://user-images.githubusercontent.com/127713083/224608756-5daec55d-fccf-4e3f-9919-769a5460dbe6.png)

### Additional information

Photo will showed 0kb. 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by thammanjaku** [comment] 2023-03-13 04:41
@magento give me 2.4-develop instance

**Comment by thammanjaku** [comment] 2023-03-13 06:25
@magento I am working on this

**Comment by thammanjaku** [comment] 2023-03-13 06:32
@magento add to contributors team

**Comment by engcom-Bravo** [comment] 2023-03-13 13:19
HI @thammanjaku,


Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Go to Catalog > Products > Add product.
- Fill in product details and upload photos.
- Error message- The stock item was unable to be saved. Please try again.


There is no cache type `Cache Import Products`,Please provide more information.if we want to enable we have option to enable kindly check below screenshot :



<img width="1439" alt="Screenshot 2023-03-13 at 12 59 53 PM" src="https://user-images.githubusercontent.com/51680745/224684249-77f783fd-0edc-4e66-94e4-095efc9acfae.png">



We are able to upload the photos for a product successsfully.


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.
it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.

Thanks.

**Comment by thammanjaku** [comment] 2023-03-14 01:04
Hi,
Besides the cache import products disabled.
I have index problem also. I tried to reindex but it could not help.
I’m having problem since these 2 issues appeared.

***@***.***

Thank you.

Regards,
Tham Chia Hoe
Assistant Manager E-Commerce
***@***.***
Manjaku Baby Centre (Bangi) Sdn Bhd (898344-T)
E-Com Hub, No 5-11-02 & 5-13-02,
Jalan Medan Pusat Bandar 8A,
Bangi Sentral,43650 Bandar Baru Bangi,
Selangor Darul Ehsan.
Tel: +603-89256631
Mobile: +6012-6360672
Email: ***@***.******@***.***>
Website: www.manjaku.com<https://www.manjaku.com/>
***@***.***

**Comment by engcom-Bravo** [comment] 2023-03-14 12:41
HI @thammanjaku,

Thanks for your update.


Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


We are able to reindex.


<img width="876" alt="Screenshot 2023-03-14 at 11 56 51 AM" src="https://user-images.githubusercontent.com/51680745/224973459-8ef2b704-638a-4d32-83ec-db1773d4e20f.png">



Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.

it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.

Thanks.

**Comment by thammanjaku** [comment] 2023-03-14 14:15
Hi, it is due to server hard disk full. Problem resolved.

Thank you.

On 14 Mar 2023 8:41 pm, Venkata Kumar Kuntumalla ***@***.***> wrote:

HI @thammanjaku<https://github.com/thammanjaku>,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

We are able to reindex.

[Screenshot 2023-03-14 at 11 56 51 AM]<https://user-images.githubusercontent.com/51680745/224973459-8ef2b704-638a-4d32-83ec-db1773d4e20f.png>

Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.

it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-03-15 06:29
Hi @thammanjaku,

Thanks for your update.

We are Closing this issue on the basis of this https://github.com/magento/magento2/issues/37195#issuecomment-1468183924 Issue has been resolved.
Please reopen and update if you wish to continue.

Thank you for your contribution

**Closed as completed by engcom-Bravo** 2023-03-15 06:29 UTC
Labels: Issue: needs update, Reported on 2.3.3
