### ISSUE TITLE
Dont select an option - > Add to cart - > Errors UNDER add to cart instead of under the option.

### ISSUE THREAD

**Issue by HRR1337** [magento/magento2#5930] opened 2016-08-02 10:16 UTC
### Preconditions

1. Magento 2.1 Luma theme
2. PHP 7
### Steps to reproduce

1. Open a product with (multiple) options (i tested the configurable product)
2.  Dont select any option
3. Click on 'Add to Cart'
### Expected result

1. The error 'This is a required field.' needs to be positioned at the attribute that wasn't selected.
### Actual result

1. The message (or multiple when you have more then 1 option) "This is a required field." is under the add to cart button. 

![error-add-to-cart](https://cloud.githubusercontent.com/assets/4428675/17325283/0cc83d52-58ab-11e6-996e-d16e603b97df.jpg)

**Comment by antboiko** [comment] 2016-08-02 12:52
Hi @HRR1337 , thanks for reporting. We've created internal ticket MAGETWO-56256.

Best,
Anton.

**Comment by HRR1337** [comment] 2016-08-02 14:26
You're welcome!

**Comment by MomotenkoNatalia** [comment] 2016-08-15 13:34
Hi @HRR1337 
Thanks for reporting this issue. But i am going to close it as duplicate of #5428.

**Closed as completed by MomotenkoNatalia** 2016-08-15 13:34 UTC
Labels: Issue: Ready for Work, bug report
