### ISSUE TITLE
ProductRepository Save with Associated Product Ids bug.

### ISSUE THREAD

**Issue by bytes-max** [magento/magento2#33937] opened 2021-08-27 15:24 UTC
Renewal of https://github.com/magento/magento2/issues/16349 as it happens still in Magento 2.4.3. 

When use $product->setAssociatedProductIds($ids), and then use ProductRepository->save($product); An exception occurs after save.
Preconditions

    Magento 2.4.3
    PHP 7.2

Steps to reproduce

    Direct Inject Magento\Catalog\Api\ProductRepositoryInterface in constructor
    create an Magento\Catalog\Model\Product object
    $productObj->setAssociatedProductIds($ids);
    $this->productRepository->save($productObj);

Expected result

    created product with links between parent and children products without exception.

Actual result

    created product.
    throws exception after save
    Exception messages:
    {"0":"Products "26" and "23" have the same set of attribute values.","1":"#0 /var/www/html/src/vendor/magento/module-configurable-product/Model/Plugin/ProductRepositorySave.php(83): Magento\ConfigurableProduct\Model\Plugin\ProductRepositorySave->validateProductLinks(Array, Array)\n#1 /var/www/html/src/vendor/magento/framework/Interception/Interceptor.php(146): Magento\ConfigurableProduct\Model\Plugin\ProductRepositorySave->afterSave(Object(Magento\Catalog\Model\ProductRepository\Interceptor), Object(Magento\Catalog\Model\Product\Interceptor), Object(Magento\Catalog\Model\Product\Interceptor))\n#2 /var/www/html/src/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Model\ProductRepository\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor))\n#3 /var/www/html/src/generated/code/Magento/Catalog/Model/ProductRepository/Interceptor.php(52):

See my example code how to create products:

```
$product = $this->collection->addAttributeToFilter('sku', ['eq' => $data['sku']])->getFirstItem();

        $product->setData([
            ProductAttributeInterface::CODE_SKU => $data['sku'],
            ProductAttributeInterface::CODE_NAME => $data['name'],
            ProductAttributeInterface::CODE_WEIGHT => $data['weight'] ?? 1,
            ProductAttributeInterface::CODE_DESCRIPTION => $data['description'],
            ProductAttributeInterface::CODE_STATUS => 1,
            ProductAttributeInterface::CODE_PRICE => 0,
            Product::ATTRIBUTE_SET_ID => 4,
            Product::VISIBILITY => 4,
            Product::TYPE_ID => Manager::TYPE_CONFIGURABLE,
            Product::STORE_ID => 1,
            'category_ids' => [3],
            'tax_class_id' => 1,
            'stock_data' => [
                'is_in_stock' => 1,
                'qty' => 0,
                'max_sale_qty' => 999,
                'min_sale_qty' => 1,
                'manage_stock' => 0,
                'use_config_manage_stock' => 0,
            ],
        ]);

        foreach ($data['custom_attributes'] as $key => $value) {
            if (in_array($key, $this->_allowedCustomAttributes)) {
                $product->setData($key, $this->creator->getValueFromCustomAttributes($key, $value));
            }
        }

        $product->setAffectConfigurableProductAttributes(4)
            ->setNewVariationsAttributeSetId(4);

        $product = $this->repository->save($product);

        if(!isset($data['configurable_attributes']) || !count($data['configurable_attributes'])) {
            $data['configurable_attributes'] = $this->_allowedCustomAttributes;
        }

        if (isset($data['configurable_attributes'])) {
            $eavIds = $this->creator->getEavIdsForCodes($data['configurable_attributes']);
            $existingIds = $product->getTypeInstance()->getConfigurableAttributesAsArray($product);
            $pos = 0;
            foreach (array_diff($eavIds, array_keys($existingIds)) as $id) {
                $attribModel = $this->creator->getAttributeFactory($id, $product);
                $attribModel->setData([
                    'attribute_id' => $id,
                    'product_id' => $product->getId(),
                    'position' => $pos++,
                ]);
                $attribModel->getResource()->save($attribModel);
            }
            
            $this->assign($product, $data);
            $indexToRenew = ['catalog_product_attribute', 'inventory'];
            foreach($indexToRenew as $indexName) {
                $indexer = $this->indexerRegistry->get($indexName);
                if(!$indexer->isScheduled()) {
                    $indexer->reindexList([$product->getId()]);
                }
            }
        }

        $product = $this->repository->save($product);
```

Inside $data['child_products] I pass Interceptor Classes of previously generated Simples. The simples do always have different attributes assigned for the Attribute that is also being passed to the configurable as being the configurable attribute ($data['configurable_attributes']).

The issue does NOT occour if I save the same set of products again, it only happens ONCE per creation of a set of Simples + Configurables. I do renew indexes like above also on creation for simples, but IMO it should not be relevant to run re-indexing on individual product creation/updating.

**Comment by webstraxt-ben** [comment] 2021-09-19 17:37
We're seeing this same issue. Using previously working code to create configurable products. This has only started to occur in 2.4.3. 

It looks like in Magento\ConfigurableProduct\Model\Plugin\ProductRepositorySave::validateProductLinks() the $attributeCodes array is empty.

**Comment by Giakie** [comment] 2022-06-01 10:35
Hi,
Any update on this? I have the very same issue, the problem is that this occurs inside the Webkul Akeneo Magento Connector extension, therefore I can't update their core code.
thanks

**Comment by engcom-Hotel** [comment] 2024-02-16 14:33
Hello @nopenopenope,

Thanks for the report and collaboration!

We have tried to reproduce the issue in the Magento 2.4-develop branch but the issue is not reproducible for us. Please find below the custom module made by us to reproduce the issue:

[Magz.zip](https://github.com/magento/magento2/files/14312193/Magz.zip)

Please let us know if we have missed anything.

Thanks

**Comment by nopenopenope** [comment] 2024-02-18 21:01
Hi @engcom-Hotel - this issue is very old now. I have moved on from Magento2 platform because its way to buggy to use it for clients that don't have unlimited budget to fix all of these issues. Due to this, I cannot review your Zip properly. 

Maybe @benjaminwilcock or @Giakie can help you with it.

**Comment by engcom-Hotel** [comment] 2024-02-19 05:06
Thanks @nopenopenope for the response.

Hello @benjaminwilcock @Giakie,

Please go through with this comment https://github.com/magento/magento2/issues/33937#issuecomment-1948489697 and let us know if you are still able to reproduce the issue.

Thanks

**Comment by engcom-Hotel** [comment] 2024-03-01 07:29
Dear @nopenopenope @benjaminwilcock @Giakie,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we're assuming it's been resolved and will be closing it. Feel free to open a new ticket or reopen this one if you require further assistance.

Regards

**Closed as completed by engcom-Hotel** 2024-03-01 07:29 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.3
