### ISSUE TITLE
HELP ASAP!!

### ISSUE THREAD

**Issue by leslilcp** [magento/magento2#35774] opened 2022-07-15 14:12 UTC
### Summary (*)
<The pricing of products is changing to pricing I did not put in. I check the products in Magento and all the pricing is correct and no discounts were added. The pricing shows it correct when you click on the item from the check but as soon as you add it to the chart it changes. The total of the chart says the correct pricing as well so I have no idea what is going on. It is doing this for multiple products and across all my websites. Please explain in detail i'm not great with magento or coding.
>

### Examples (*)
<
![magento help](https://user-images.githubusercontent.com/101366526/179240846-2627a286-9f51-4f18-9a1e-5efb85685557.jpg)
![magento help 2](https://user-images.githubusercontent.com/101366526/179240859-ba393203-b1d1-47cc-bb47-428578259dd3.jpg)
>

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by onlinebizsoft** [comment] 2022-07-15 15:09
Look like related to tax setting for price display

**Comment by leslilcp** [comment] 2022-07-15 16:18
It does it for random products not all.

**Comment by leslilcp** [comment] 2022-07-15 16:19
I can it back by just taking the product off the website and back on and the price always goes back to what it should be

**Comment by leslilcp** [comment] 2022-07-18 15:05
Where would I check the tax setting for price display?

**Comment by engcom-November** [comment] 2022-07-19 13:29
Hi @leslilcp ,
Thank you for reporting and collaboration. Please check the tax calculation settings and price display settings in your store: Stores > Settings > Configuration - Sales - Tax. Ref [guide](https://docs.magento.com/user-guide/tax/tax-settings-general.html). Also check the tax zones / rules added. Stores - Taxes - Tax Zones and tax rules. [Ref guide](https://docs.magento.com/user-guide/tax/tax-rules.html)
Price also gets changed if any catalog Price rules are enabled. Marketing - Catalog Price Rules.
Unable to reproduce the issue on Magento 2.4develop branch with provided information. Kindly recheck the issue on Magento 2.4-develop branch and elaborate steps if you are still facing any issues.
Thank you.

**Comment by leslilcp** [comment] 2022-07-19 13:47
Just checked all of that. All looked good. Any other ideas??

**Comment by engcom-November** [comment] 2022-07-20 10:52
Hi @leslilcp ,
Please provide more details to reproduce the issue like: your current Magento version, any 3rd party extensions / modules enabled, previous and current magento versions if issue is caused after upgrade. This issue is not reproducible on 2.4-develop branch. Kindly check the Magento system [requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) and recheck the behavior on Magento 2.4-develop branch and elaborate missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-08-02 10:26
Hi @leslilcp ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-08-02 10:26 UTC
Labels: Issue:  Cannot Reproduce, Triage: Dev.Experience, Issue: needs update
