### ISSUE TITLE
Extra generated cache images when a product is saved in admin

### ISSUE THREAD

**Issue by miquelcoma** [magento/magento2#10363] opened 2017-07-28 08:15 UTC
When saving a product in admin, extra images are generated in **pub/media/catalog/product/cache**.

the sizes are coming from the **view.xml** file defined in the luma and blank themes in the vendor core folder.

### Preconditions
1. A custom theme with a custom image sizes defined in the view.xml file.
2. Magento 2.1.7 C.E., in development or production mode.
3. Running in ngingx with php 7.0.

### Steps to reproduce
1. Have a look at **pub/media/catalog/product/cache**
2. Go to admin
3. Go to Product -> Catalog -> select an article.
3. Save the product (is not necessary any modification)
4. Have a look again to the cache folder.

### Expected result
1. In the cache image folder, only the image sizes defined in our custom theme view.xml file exists plus the sizes defined in magento backend theme view.xml file.

### Actual result
1. In the images cache folder appears extra images that have no relation with our theme or magento backend theme etc/view.xml file.
2. Those extra sizes are coming from the **view.xml** file defined in the **luma** and **blank** themes in the vendor core folder.

How I can  avoid those extra images generated in the cache folder?

**Comment by orlangur** [comment] 2017-07-28 14:15
Looks like https://github.com/magento/magento2/issues/3650 is related to me. Some workarounds are available in comments there.

**Comment by hostep** [comment] 2017-07-30 19:03
This is more a duplicate of https://github.com/magento/magento2/issues/8145, although being able to remove/disable a theme should probably also work around this issue.
There is also a closed PR which you can maybe turn into a module which should solve this problem (haven't tested this for a couple of months, so no idea if this is still relevant for the latest Magento version): https://github.com/magento/magento2/pull/8142

**Comment by miquelcoma** [comment] 2017-07-31 08:01
Thanks @orlangur and @hostep,

I have tested the proposed solution from @vrann and works fine! 

I have created a temporary module (waiting for the next update of magento 2.x) that implements the fix without changing anything in the vendor core folder:

**di.xml**:

`
  <preference for="Magento\Catalog\Model\Product\Image\Cache"
    type="VENDOR\MagentoFix\Model\Product\Image\Cache"/>
`


**app\code\VENDOR\MagentoFix\Model\Product\Image\Cache.php**:

With the contents of: [@vrann fix](https://github.com/magento/magento2/pull/8142/commits/35e3225f0478a7b952119dca2a800a76b9ae5f3e#diff-dbf04232abcedbe2e67996b043041b48)

with the namespace changed to VENDOR.

**Comment by magento-engcom-team** [comment] 2017-09-29 11:30
@miquelcoma, thank you for your report.
We've created internal ticket(s) MAGETWO-80436 to track progress on the issue.

**Comment by denisristic** [comment] 2017-10-16 08:22
I'm working on it #SQUASHTOBERFEST

**Comment by prestashoppay** [comment] 2017-11-08 08:06
@vrann ,

I am using magento 2.1.6 version , in my admin panel having images on each and every products , but frontend image path didn't created a folder '"cache/f073062f50e48eb0f0998593e568d857" ..


Please give a solutions .

**Comment by teoteo** [comment] 2018-03-31 10:48
Waiting for the official fix, do you have suggestions to identify which are the unused cache folders so I can delete it?

**Comment by faisalmirza** [comment] 2018-06-26 11:02
Hi was wondering if is there is an update on this?

**Comment by magento-engcom-team** [comment] 2020-01-06 12:21
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30227` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2020-04-21 13:20
Hi @miquelcoma. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-33501` was closed as `non-reproducible` in `2.3-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by magento-engcom-team** [comment] 2020-04-21 17:25
Hi @miquelcoma. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-30227` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Closed as completed by magento-engcom-team** 2020-04-21 17:25 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Cache

**Comment by ArtemVasyliev** [comment] 2020-04-21 17:28
I was not able to reproduce the issue according to provided steps.
_find pub/media/catalog/product/cache -type f -exec sha1sum {} \; | sort_ did not show any duplicate files
