### ISSUE TITLE
Wrong image cache generated from request

### ISSUE THREAD

**Issue by sawwd** [magento/magento2#38188] opened 2023-11-15 20:13 UTC
### Preconditions and environment

- Magento 2.3.7 CE
- nginx
- PHP 7.4

If the original image contains `..` or `...` in the filename, the image cache versions are not generated from request but are generated when the image uploaded to product via admin interface. Same, the image cache versions are not generated when the product is added via import tool.

What I found very strange is that the small thumbnail from Admin -> Catalog -> Products is generated correctly.

### Steps to reproduce

1. Upload an image named `01zz...-flow.er_1234.jpeg` to a product in admin.
2. Delete cache image versions from media/catalog/product/cache
3. Reload product page

### Expected result

I expect cache images to be generated correctly from request even if the image contains special chars like `..` or `...` in the filename. Users doesn't care.

I don't understand why Magento allow such characters in uploader if these are not handled correctly.

### Actual result

If there is no cache version for the original image the customers see the default placeholder image.

### Additional information

I found that the dots are replaced from the pathInfo here and this cause this issue https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/MediaStorage/Model/File/Storage/Request.php

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by konradszwed** [comment] 2023-11-16 13:12
@magento give me 2.4-develop instance

**Comment by sawwd** [comment] 2023-11-25 09:51
@konradszwed wonder if you successfully reproduced it. let me know if you need anything from me.

**Comment by engcom-Dash** [comment] 2023-11-27 16:23
Hi @sawwd 

Thanks for reporting and collaboration.

As per the steps to reproduce we have uploaded an image with the same name : 01zz...-flow.er_1234.jpeg to a product via admin. After uploading we are not able to find the path : media/catalog/product/cache. Can you please provide more information regarding the path.This will help us in reproducing the issue.

Thanks

**Comment by sawwd** [comment] 2023-11-28 21:07
@magento give me 2.4-develop instance

**Comment by sawwd** [comment] 2023-11-30 07:37
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-11-30 11:09
@magento give me 2.4-develop instance

**Comment by sawwd** [comment] 2023-12-01 08:29
@engcom-Dash have you managed to reproduce it?

**Comment by engcom-Dash** [comment] 2023-12-04 08:44
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-12-04 10:18
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-12-07 06:16
Hi @sawwd 
 
Thanks for reporting and collaboration.
Verified the issue as per your previous comment. 
Steps to reproduce:
1.Upload an image named 01zz...-flow.er_1234.jpeg to a product via admin or import
2.Flush Catalog Images cache
3.Check product image on store view
 
We are able to see the product image on store view. 
Please check the issue on 2.4 developer instance and run reindex and check if the cron job is on schedule.

**Comment by sawwd** [comment] 2023-12-07 14:53
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-12-26 14:57
Hi @sawwd 

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel free to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2023-12-26 14:57 UTC
Labels: Issue: needs update, Reported on 2.4.x
