### ISSUE TITLE
Product URL rewrites being removed on mass with multiple websites

### ISSUE THREAD

**Issue by jordanbrierley** [magento/magento2#4850] opened 2016-06-03 10:28 UTC
Iv just been trying to set up multiple websites each with their own store and store view but there's a problem with the product urls when assigning them to multiple websites.

All of the product data has already been populated into Magento and we needed multiple websites each with their own store and store view. When I go back into the products, check all and select update attributes from the actions drop, from here I tick the websites tab and select the websites I want to add the products to and then save this. This then causes all of the url rewrites to get removed from the `url_rewrite` for any row with the `product` entity type leaving all of the products with messy urls so instead of `/store_code/product_name` all of the products have `catalog/product/view/id/424/s/product_name/category/11/` for example

**Comment by antboiko** [comment] 2016-06-06 09:28
Hello @jordanbrierley , what version of Magento 2 are you running?

Thanks,
Anton.

**Comment by jordanbrierley** [comment] 2016-06-06 09:43
Hi @antboiko version 2.0.2 currently

Thanks,
Jordan

**Comment by antboiko** [comment] 2016-06-06 10:12
@jordanbrierley , I've created internal ticket MAGETWO-53927 to investigate this issue.

Thanks,
Anton.

**Comment by jordanbrierley** [comment] 2016-06-06 10:44
@antboiko Thanks for your help.

Just for some extra info, I also tried using the import/export using a CSV to add all the products to multiple websites instead of through the update all attribute and although this preserved the url rewrites for the default website, it didn't create any url rewrites for the other websites

Thanks,
Jordan

**Comment by kayintveen** [comment] 2016-07-28 12:30
Still no news on this issue??

**Comment by andimov** [comment] 2016-08-16 12:53
Internal ticket MAGETWO-53927 has been closed as 'can't reproduce'.

**Closed as completed by andimov** 2016-08-16 12:53 UTC
Labels: Issue: Ready for Work, bug report, Component: CatalogUrlRewrite

**Comment by joshdavenport** [comment] 2016-11-08 16:18
My team and I have been struggling with this issue for the last week and we believe we've found a reliable route to reproducing this issues. It's a very tricky issue which has some very odd nuances. After I've written up a bug report, should I add it here or create a new issue? Present on 2.1

**Comment by andimov** [comment] 2016-11-08 17:20
@joshdavenport 
Please create a new issue according to the [issue reporting guideline](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).
