### ISSUE TITLE
AGAIN: Missing paid orders and lock wait timeouts in Guest Checkout 

### ISSUE THREAD

**Issue by hubertus2017** [magento/magento2#31967] opened 2021-02-04 12:31 UTC
During peak sales hour, we loose 3% of orders, due to "ghost orders".

**#25862: NOT FIXED!!**

We have a problem in Magento 2.4.1 : Customers tell me: After payment they are redirected to the shop. And: their cart is still filled after the payment. Then they order a second time and then it works. But the payment is done twice. And only one order is in magento, the other first order is a "ghost order" not appearing. (mixed payment types OR same payment type affected)

So two orders with same article:
4000043424	Jan 17 2021, 05:17 PM CET, credit card	- not in Magento
4000043425	Jan 17 2021, 05:20 PM CET, PayPal  	- successfull in Magento

It started approx after installing the new magento version 2.4.1 last year. It affects 3% 

There are no clear steps to reproduce. Its kind of hazardeous. It seems to be when a higher amount of customers are in the shop ( like 50+ customers)

This is HIGHLY critical, because it do cost ressources and a lot of money. I did not see that there is a fix in M2.4.2 ? (i looked in beta release notes)

Preconditions (*)

    Magento 2.4.1
    Enabled Guest Checkout
    Site-wide sales rule like "Free shipping above x amount"

Steps to reproduce (*)

    Stress test system with concurrent guest orders 

Expected result (*)

    All paid payment transactions are saved to the database and visible in the admin panel

Actual result (*)

    A small fraction of orders is saved in the database while the majority of orders lost because of lock wait timeout.

**Comment by mrtuvn** [comment] 2021-02-04 22:58
I'm not sure this problem fixed or not 
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/Model/GuestPaymentInformationManagement.php#L102
Here is the last file modify
Seem this problem hard to reproduce in when you need real online payment with high stress store peaks

**Comment by hubertus2017** [comment] 2021-02-05 07:33
Hello,
thank you. Hmm, the file GuestPaymentInformationManagement.php on github, that you referenced, is exactly the one we already have on the server. A diff gives no difference between both files.

**Comment by mrtuvn** [comment] 2021-02-05 09:11
@sidolov @sivaschenko @gabrieldagama maybe know this

**Comment by sdzhepa** [comment] 2021-02-05 15:35
Hello @mrtuvn 
cc: @sidolov @gabrieldagama @zakdma
Based on the discussion and comments https://github.com/magento/magento2/issues/25862

- https://github.com/magento/magento2/issues/25862#issuecomment-745423635


As I understood fix was delivered into `2.4-develop` and should be available in the next release version.

**Comment by hubertus2017** [comment] 2021-02-05 18:00
Hello,
i read magento 2.4.3 release is in August 2011 😲
As this is a higly time and turnover killer, is there anywhere a fix available?

**Comment by magento-quality-patches** [comment] 2021-02-10 22:22
The patch solving a similar issue is available in [Magento Quality Patches](https://support.magento.com/hc/en-us/articles/360047139492) package (MQP)
 
**Patch**
MDVA-31519: Fixes the issue where missing paid orders and lock wait timeouts in Guest Checkout.
 
**Compatible versions**
Magento OpenSource/Commerce/Commerce Cloud 2.3.5, 2.3.5-p1, 2.3.5-p2
 
:warning: We strongly recommend testing all patches in a staging or development environment before deploying to production.
 
**Applying a patch - Magento OpenSource/Commerce**
 
1. `$ composer require magento/quality-patches`
2. `$ ./vendor/bin/magento-patches apply MDVA-31519`
 
See [MQP Magento Commerce documentation](https://devdocs.magento.com/guides/v2.4/comp-mgr/patching/mqp.html)
 
**Applying a patch - Magento Commerce Cloud**
See [MQP Magento Commerce Cloud documentation](https://devdocs.magento.com/cloud/project/project-patch.html)
 
**Patch Details**
https://support.magento.com/hc/en-us/articles/360055441412

**Comment by magento-quality-patches** [comment] 2021-02-10 22:24
@mrtuvn @hubertus2017 ^^^^

**Comment by hubertus2017** [comment] 2021-02-11 08:15
Hello,
is there also a patch for M2.4.1/ M2.4.2 ?

**Comment by gabrieldagama** [comment] 2021-02-16 18:03
Closing since this issue is already fixed on `2.4-develop`.

**Closed as completed by gabrieldagama** 2021-02-16 18:03 UTC
Labels: Issue: ready for confirmation

**Comment by hubertus2017** [comment] 2021-02-16 18:30
Hello,
thank you for your support.

@gabrieldagama Can you please provide the information, if there is a patch planned for M2.4.2 ?  

As 2.4.3 is released in August? 

We have daily, hourly issues with missing ghost order, double payments and customer complaints.
