### ISSUE TITLE
KnockoutJS $parent-Element in Checkout seems to miss some information

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#7085] opened 2016-10-19 09:09 UTC
When trying to modify the knockout.js-templates in `Magento_Checkout/web/template/summary/item/details.html` there are a few appearances of "`$parent.identifier`", where `identifier` is the desired part of it (e.g.: `text`)

It seems that `$parent.name` works, but `$parent.url` doesn't work. Shouldn't the array contain such informations? On Magento 2.0.6. its not in there. 

### Preconditions

1. Use of Magento 2.0.6, intended to use in Germany
### Steps to reproduce

1. Try to modify the knockout js template in order to be legit with german ecommerce laws
2. Try to access the products URL
3. 
### Expected result

1. in $parent theres a key with the url
### Actual result

1. $parent only contain item_id, name and qty of product

Its less a bug report, but a feature request. In Germany you need to link the products on the last pages in the cart. Without a URL, KO JS can't load it (obviously). Therefore, $parent needs to have a key with the URL in order to link the product to its page.

**Comment by veloraven** [comment] 2016-10-19 11:29
@grasdaggel thank you for your feedback. 
If you think it to be an issue please format it according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
If it is a question please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions as GitHub issue tracker is intended for technical issues only.

**Comment by grasdaggel** [comment] 2016-10-19 11:55
I've updated the initial request. Its less a bug report, more of a feature request. I've asked my question on Stackexchange, but most likely I'll _not_ get any answers there. Whats the best way to request Feature Requests?

**Comment by veloraven** [comment] 2016-10-27 14:32
@grasdaggel thank you for update and additional explanation.
We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues. Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by grasdaggel** [comment] 2016-10-28 09:09
Does this ticket still needs my update or can I now just wait until the feature request has been implemented?

**Comment by veloraven** [comment] 2016-11-23 08:23
@grasdaggel no, this issue does not require any updates, I leaved it open only for case if you have any additional questions.
If you added corresponding feature request to the specified forum, I can close this issue now.

**Closed as completed** 2016-11-24 14:35 UTC
Labels: feature request, Progress: needs update, Component: Checkout
