### ISSUE TITLE
Error Processing Requests

### ISSUE THREAD

**Issue by alexdonald22** [magento/magento2#34012] opened 2021-09-07 16:50 UTC
### Preconditions (*)

1. Magento ver. 2.3.6-p1
2.

### Steps to reproduce (*)

1. When clicking back from invoicing an order this error is common "There has been an error processing your request
Warning: include(/var/www/html/magento2/generated/metadata/adminhtml.php): failed to open stream: No such file or directory in /var/www/html/magento2/vendor/magento/framework/App/ObjectManager/ConfigLoader/Compiled.php on line 31
Error log record number: 8ff8c9c1fefa211fe9b560b5db152ff7f3d26c6c6282039d7dc10b9401d1f50f"
2. Sometimes even when going to invoice or unhold the order the same error pages comes up

### Expected result (*)

1. Need to stop this from happening
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2021-09-08 07:45
Verified the issue on Magento 2.4-develop branch and unable to reproduce this issue for new orders and existing Orders as well:
Steps performed:
Admin - Sales - Orders - View Order - Click on invoice and Navigate Back - No issue
Admin - Sales - Orders - View Order - Click on Invoice and Submit - No issue: Invoice is created
When clicking back from invoicing an order, user is navigated back to Order information page for new or existing orders. No issue
@alexdonald22 kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2021-09-22 05:24
Hi @alexdonald22 , we are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-09-22 05:24 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
