### ISSUE TITLE
Using the "in" search criteria with the Rest API

### ISSUE THREAD

**Issue by canassa** [magento/magento2#3411] opened 2016-02-15 17:05 UTC
Hello,

I am trying to use the "in" search criteria with the Rest API but it doesn't seems to be working.

I first tested passing only a single item to the `value` attribute, in this case `1`:

http://127.0.0.1:9002/index.php/rest/V1/shipments?searchCriteria[filterGroups][0][filters][0][condition_type]=in&searchCriteria[filterGroups][0][filters][0][field]=order_id&searchCriteria[filterGroups][0][filters][0][value]=1

That worked correctly, it returned the `order_id` 1. My trouble started when I tried to send more than one item:

http://127.0.0.1:9002/index.php/rest/V1/shipments?searchCriteria[filterGroups][0][filters][0][condition_type]=in&searchCriteria[filterGroups][0][filters][0][field]=order_id&searchCriteria[filterGroups][0][filters][0][value]=1,2

That doesn't work, it ignores the comma and returns only the order_id 1.

I also tried sending other values to the `value` field, I tried `(1,2)`, `[1,2]`, `1 2` and a few others, but none seems to work.

Thanks,

**Comment by arkadiych** [comment] 2016-02-17 21:24
Looks like duplicate of https://github.com/magento/magento2/issues/2892

**Comment by okorshenko** [comment] 2016-03-04 14:56
@canassa please let us know if fix from #2892 does not work for you

**Closed as completed by okorshenko** 2016-03-04 14:56 UTC

**Comment by canassa** [comment] 2016-04-01 07:51
@okorshenko I just tested it again with the 2.0.3 release but the "in" condition is still not working with the REST API

**Comment by okorshenko** [comment] 2016-04-01 13:53
@canassa This issue was fixed in `develop` branch and will be available in the next minor release. Thank you

**Comment by zahmed-f3** [comment] 2016-04-04 12:11
I am still getting this error. Has this issue fixed in 2.0.4 release?

**Comment by okorshenko** [comment] 2016-04-04 15:53
Hi @zahmed-f3 
This issue was fixed in `develop` branch which has target release 2.1.0

**Comment by vincentwinkel** [comment] 2018-05-16 14:27
Still have this issue. Please show us the workaround, I'm bored to face stupid issues everyday with Magenshit.

**Comment by skast96** [comment] 2018-06-27 09:57
You say it @vincentwinkel. This little issue would be fixed within minutes, but nobody cares. :(
