### ISSUE TITLE
"Minimum Qty Allowed in Shopping Cart" functionality breaks product "Update Attributes" functionality

### ISSUE THREAD

**Issue by samgranger** [magento/magento2#21640] opened 2019-03-08 08:54 UTC
### Preconditions (*)
1. Magento 2.2.7 / 2.3.0

### Steps to reproduce (*)
1. Check the value of `cataloginventory/item_options/min_sale_qty`, the default value is `1`.
2. Go to: Stores -> Configuration -> Catalog -> Inventory
3. Make sure there are multiple or no rules for 'Minimum Qty Allowed in Shopping Cart' & save your configuration.
4. You'll now see that `cataloginventory/item_options/min_sale_qty` gets an array as a value.
5. Go to: Catalog -> Products
6. Select one or more products and click on `Update Attributes` in the Actions dropdown menu.

### Expected result (*)
1. The ability to do a Mass Update of attributes for the selected product(s).

### Actual result (*)
1. No form visible
2. Our `system.log` reports the following issue:
```
main.CRITICAL: Warning: A non-numeric value encountered in vendor/magento/module-catalog/view/adminhtml/templates/catalog/product/edit/action/inventory.phtml on line 135
```
This is because `cataloginventory/item_options/min_sale_qty` is no longer a numeric value.

<img width="1145" alt="screen shot 2019-03-08 at 09 50 51" src="https://user-images.githubusercontent.com/1847151/54017904-b2f06480-4187-11e9-8fa2-96e094d59d85.png">

**Comment by magento-engcom-team** [comment] 2019-03-08 08:54
Hi @samgranger. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@samgranger do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by hiren0241** [comment] 2019-03-08 09:10
@magento-engcom-team Please give me 2.3-develop instance

**Comment by hiren0241** [comment] 2019-03-08 09:14
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-08 09:14
Hi @hiren0241. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-08 09:15
Hi @hiren0241, here is your [Magento instance](https://i-21640-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21640-2-3-develop.instances.magento-community.engineering/admin](https://i-21640-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by hiren0241** [comment] 2019-03-08 09:29
Hi @samgranger, By following steps to reproduce, I am unable to reproduce it.

**Comment by samgranger** [comment] 2019-03-08 09:36
@hiren0241 I noticed the setting wasn't changed, see screenshot. I have changed this for you. Please try the Update Attributes functionality again.
<img width="1492" alt="screen shot 2019-03-08 at 10 31 39" src="https://user-images.githubusercontent.com/1847151/54020400-fcdc4900-418d-11e9-9fea-1711c2e619c3.png">

<img width="1598" alt="screen shot 2019-03-08 at 10 35 50" src="https://user-images.githubusercontent.com/1847151/54020391-f8b02b80-418d-11e9-9417-f23cf0cbd502.png">

<img width="1598" alt="screen shot 2019-03-08 at 10 35 38" src="https://user-images.githubusercontent.com/1847151/54020419-05cd1a80-418e-11e9-979b-1e8b3b2134c7.png">

**Comment by hiren0241** [comment] 2019-03-08 09:38
@samgranger Okay, got  your point. Let me try once again.

**Comment by hiren0241** [comment] 2019-03-08 09:44
@samgranger Reproduced. Thanks for correction.

**Comment by magento-engcom-team** [comment] 2019-03-08 09:44
Hi @hiren0241. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-03-08 09:47
:white_check_mark: Confirmed by @hiren0241
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by hiren0241** [comment] 2019-03-08 09:47
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-08 09:47
Hi @hiren0241. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-08 09:48
Hi @hiren0241, here is your [Magento instance](https://i-21640-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21640-2-2-develop.instances.magento-community.engineering/admin](https://i-21640-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-03-08 10:00
Hi @hiren0241. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by hiren0241** [comment] 2019-03-08 10:08
@samgranger 
Issue confirmed: https://prnt.sc/mv00le
Presently, I am working on this issue.

**Comment by magento-engcom-team** [comment] 2019-03-08 10:39
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by samgranger** [comment] 2019-03-08 10:40
Great, thank you @hiren0241

**Comment by magento-engcom-team** [comment] 2019-03-08 10:44
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98627`, `MAGETWO-98628` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hiren0241** [comment] 2019-03-08 13:45
@samgranger While getting configuration from database , this value: '{&quot;32000&quot;:456,&quot;0&quot;:123}' creates an error. we need to unserialize the config value. 
I case of default value, nothing is happen. But, while we not using default system config it gives an error.

**Comment by samgranger** [comment] 2019-03-08 14:02
@hiren0241 Indeed, I believe this use to be a fixed integer value configuration but now it can vary per user group. You'd expect the default value would also be an object now instead of just being `1`.

**Comment by hiren0241** [comment] 2019-03-08 15:35
@samgranger  I have fixed issue by getting exact configuration value set by back-end configuration. Now, whatever sets in back-end same will reflect in frontend as well.

**Comment by dmytro-ch** [comment] 2019-03-10 11:18
Hi @samgranger,
thank you for your report!

This bug has been already reported in #17592.
So I'm closing the current issue in order to avoid duplicates.

Thank you!

**Closed as completed by dmytro-ch** 2019-03-10 11:18 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Component: CatalogInventory
