### ISSUE TITLE
Price is automatically rewritten to 0.00 in product detail page for magento 2.4.3-p1

### ISSUE THREAD

**Issue by wildxl** [magento/magento2#34728] opened 2021-11-29 14:22 UTC
### Preconditions (*)

1.
2.

### Steps to reproduce (*)
**1. Magento installation** 
2. **Change locale Options** Locale english (United States) to french (Switzerland)
3. **Create a new product** with a price 
4. Go to frontend and click on the product detail page

### Expected result (*)
1. the price is the same that was created.

### Actual result (*)
1.  the price is overwritten to 0.00 from the original price

**Comment by engcom-November** [comment] 2021-11-29 15:50
Verified the issue on Magento 2.4-develop branch but the issue is not reproducible:
@wildxl ,
This issue is a duplicate of https://github.com/magento/magento2/issues/33798
Please apply the following patch as a workaround and check if it works for you : [#33856 (comment)](https://github.com/magento/magento2/issues/33856#issuecomment-904606945)
This issue was fixed in the 2.4-develop branch in [ae304d4,](https://github.com/magento/magento2/commit/ae304d43cd36322b1ff8145d70c9b2e9aeb0cde) As a workaround, you could apply it as patch.

Kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2021-12-13 06:05
Hi @wildxl ,
We are closing this issue as there has been no latest update on the same.
Thank  you.

**Closed as completed by engcom-November** 2021-12-13 06:05 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
