### ISSUE TITLE
MariaDB 10.0.x Support

### ISSUE THREAD

**Issue by starnetwork** [magento/magento2#2470] opened 2015-11-22 12:42 UTC
Hi,
I try to Install magento 2 with MariaDB 10.0.22 DB
and I got the following error: Sorry, but we support MySQL version 5.6.0 or later.

Please add MariaDB support in next fix release

Regards,

**Comment by markshust** [comment] 2015-11-22 22:30
MariaDB should just really work out of the box (see my ticket https://github.com/magento/magento2/issues/1906). Just use a standard mysql connection string/data when connecting to the mariadb instance and all should be ok.

**Comment by starnetwork** [comment] 2015-11-23 10:42
Hi, it's should but it's not working and give this message using "web interface" for installation and regular connection string values
the message: Sorry, but we support MySQL version 5.6.0 or later.

**Comment by alankent** [comment] 2015-11-23 19:30
There were lots of obtuse error messages when people used the wrong version of MySQL. It may be this was just improved to be more informative, but as a result more restrictive as well. Is there a good way to work out if a system is MySQL 5.6 compatible?

**Comment by BlackIkeEagle** [comment] 2015-11-24 19:55
@starnetwork I assume this is a web install, since `bin/magento` does not complain when installing using mariadb and runs just fine with mariadb

**Comment by starnetwork** [comment] 2015-11-24 20:18
Hi,
yes, this is web install
@alankent, I don't know why you say that MariaDB 10.0 is not MySQL compatible, it its!
just using another version numbering
why to use MariaDB? please read https://seravo.fi/2015/10-reasons-to-migrate-to-mariadb-if-still-using-mysql
compatibility: https://blog.mariadb.org/mariadb-10-0-and-mysql-5-6/

**Comment by markshust** [comment] 2015-11-24 20:26
Note that if you install with mariadb and command line, no error is returned. Everything installs and works just fine. So there is a check in web installer that isn't in CLI installer.

**Comment by markshust** [comment] 2015-11-24 20:27
@starnetwork fyi they do plan on supporting mariadb, just not 'officially' https://github.com/magento/magento2/issues/1906

**Comment by asrob** [comment] 2015-11-25 05:33
I use Fedora 23 with MariaDB and everything works fine and I used web installer.

> $ mysql --version
> mysql  Ver 15.1 Distrib 10.0.21-MariaDB, for Linux (x86_64) using readline 5.1
> 
> Installed Packages
> Name        : mariadb-server
> Arch        : x86_64
> Epoch       : 1
> Version     : 10.0.21
> Release     : 1.fc23
> Size        : 86 M
> Repo        : @System
> From repo   : updates
> Summary     : The MariaDB server and related files
> URL         : http://mariadb.org
> License     : GPLv2 with exceptions and LGPLv2 and BSD
> Description : MariaDB is a multi-user, multi-threaded SQL database server. It is a
> client/server implementation consisting of a server daemon (mysqld)
> and many different client programs and libraries. This package contains
> the MariaDB server and some accompanying files and directories.
> MariaDB is a community developed branch of MySQL.

**Comment by hgpit** [comment] 2016-01-11 10:23
I have installed M2CE three times and M2EE once, all on systems running MariaDB 10.0.23 and experienced zero issues regarding the DB engine version.

I should add that these were clean CentOS installed though with no old MySQL files floating around.

Sorry I can't be more helpful!

**Comment by mazhalai** [comment] 2016-01-11 15:28
@starnetwork were you able to try installing via CLI?

**Comment by starnetwork** [comment] 2016-01-11 15:56
Hi @mazhalai 
I already change the environment to MySQL 5.6 and can't touch it now :(
anyway, next time I will have same environment, I will check it again...

**Comment by alankent** [comment] 2016-01-12 00:28
If I understand correctly from this page (https://mariadb.com/kb/en/mariadb/what-is-mariadb-100/), MariaDB is _close to_ MySQL 5.6. It is not exactly the same - it is 5.5 with some 5.6 features back-ported. So they don't claim 100% compatibility. That means to more officially support MariaDB we may need to add it to all our test plans. At present we only test against the official MySQL 5.6 release. (If I recall, MySQL 5.7 changed something so Magento does not work with MySQL 5.7 out of the box.) A painful area.

**Comment by markshust** [comment] 2016-01-12 01:28
I think this is something specific to the user's environment. I've run both
10.0 and 10.1 on m 2.0.0 with zero issues. Installed, configured, ran fine
out of the box.

**Comment by JHGitty** [comment] 2016-02-12 19:14
Today I tried to install Magento over the Setup Wizard and got this warning:
``Sorry, but we support MySQL version 5.6.0 or later.``

We want to run Magento on a up-to-date Plesk system. The default software for MySql is MariaDB (currently version 10). That because we really need support for this. Hopefully this will be added in the future as official supported MySQL version. Also there should be a information about this on the Setup Wizard.

**Comment by JHGitty** [comment] 2016-02-12 19:36
@BlackIkeEagle
There is also a mysql version check on CLI. How did you install it with MariaDB? Maybe the mysql version check on CLI has been added after your post?

**Comment by JHGitty** [comment] 2016-02-12 20:20
MariaDB is currently not compatible with Magento 2: https://github.com/magento/magento2/issues/3390

**Comment by asrob** [comment] 2016-07-23 05:53
I agree with @markoshust. I installed Magento 2.1.0 via cli and everything was fine, using MariaDB 10.1.14.

**Comment by markshust** [comment] 2016-07-23 11:37
this ticket should be closed as a dupe of https://github.com/magento/magento2/issues/1906

**Comment by zgggzrzx** [comment] 2016-07-28 23:12
Hi,i got the same issue for web installation.
Finally i modified this php file ( i use community edition and directory structure like this)
Magento\setup\src\Magento\Setup\Model\Installer.php
There is a const variable here :const MYSQL_VERSION_REQUIRED = '5.6.0';
You can set it =''; Then the installation will igonre the mysql version check.

**Comment by markshust** [comment] 2016-07-29 01:25
It appears you are using a web installer? I've been installing from CLI.

**Comment by zgggzrzx** [comment] 2016-07-29 01:29
Ye, web installer maybe not support marian,  so need to modify something.

**Comment by markshust** [comment] 2016-07-29 03:41
Ok, this should in fact be a bug then. I would expect the web interface should work exactly like the CLI. Whatever is happening in CLI should be the correct/default method, looks like web interface is doing some additional MySQL checks it shouldn't be doing.

**Comment by zgggzrzx** [comment] 2016-07-29 06:32
Hi,yes,just I continue installing magneto, it reported some error when
creating database tables.

**Comment by veloraven** [comment] 2016-09-13 12:30
@zgggzrzx please create a new issue if you still have this problem.
Please use our issue reporting template to describe the issue. The template specifies the version and configuration information we need to assess your issue. See the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) for more information. 
Please specify exact errors you see and their places.

I'm going to close this one as it does not follow required format and as it is not actual for the author anymore there is no sense to ask to update it.

**Closed as completed** 2016-09-29 12:39 UTC
Labels: Progress: needs update
