### ISSUE TITLE
Exporting-Products

### ISSUE THREAD

**Issue by MahamMubashir** [magento/magento2#34123] opened 2021-09-20 06:37 UTC
**Exporting products via Stock Inventory**

In my Magento 2.4.2 environment, I have deleted a product. Then I exported the CSV with entity type Stock Sources, I am still getting the product in my next CSV Export.
Is this a BUG or any other issue,

Can anyone help, please?

**Comment by MahamMubashir** [comment] 2021-09-23 04:58
**Summary of the issue**
While exporting the products via stock inventory the deleted products are also shown in the exported CSV.

**Information on your environment**
Magneto 2.4.2
Php 7.4

**Steps to reproduce**
> Add a dummy product in Catalog->Products->Add Product
> Export the products via Stock Inventory System->DataTransfer->Export (Entity Type-> Stock Inventory)-> Continue (It includes the new product)
> Delete the product 
> Again export the  products via Stock Inventory

**Expected results**
The exported file must not include deleted products.

**Actual results**
The exported file also includes the deleted products


Can anyone help me with it, please?

**Comment by hostep** [comment] 2021-09-23 15:45
@MahamMubashir: could you close this ticket please? Because it's a duplicate of https://github.com/magento/magento2/issues/34146

Thanks!

**Closed as completed** 2021-09-24 10:20 UTC
Labels: Triage: Dev.Experience, Issue: ready for confirmation
