### ISSUE TITLE
Segmentation fault on setup:di:compile in PHP7

### ISSUE THREAD

**Issue by devdesco-ceo** [magento/magento2#3039] opened 2016-01-19 15:51 UTC
I get segmentation fault on setup:di:compile in PHP 7.0.2-2+deb.sury.org~wily+1

Log:
> Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% 22 secs 18.0 MiB 5101 Segmentation fault      (core dumped) /var/data/mfs/www/magento/bin/magento setup:di:compile

**Comment by mazhalai** [comment] 2016-01-19 17:04
@devdesco-ceo thank you for reporting, but this is a duplicate of 2880, hence closing.

**Closed by mazhalai** 2016-01-19 17:04 UTC
