### ISSUE TITLE
Images removed from pagebuilder content when saving category twice

### ISSUE THREAD

**Issue by haroldclaus** [magento/magento2#32399] opened 2021-03-09 10:12 UTC
When you edit a category in the backend of Magento and you add an image (via upload or media gallery) in a pagebuilder block, the image itself is saved properly when you save the category. It loads itself again (page-refresh after save) and you can see the image in the description field which has been build with the pagebuilder. Though if you hit the SAVE button of the category again, a new page-reload is triggered and the images from the pagebuilder are gone.

The same error arises when saving a product twice when the description contains an image as well.

### Preconditions (*)
1. Magento Commerce 2.4.1 / 2.4.2

### Steps to reproduce (*)
1. Edit a category in the backend
2. Add a description via the pagebuilder
3. Add a row
4. Add an image (upload an image)
5. Add another row
6. Add text
7. Save the category
8. You'll see the image AND the text in the description preview
9. Save the category one more without making any changes
10. The preview of the description will only contain the text you've added. The image is gone

### Expected result (*)
1. After the second save of a category, I expect to see the text AND the image in the description preview

![Selection_876](https://user-images.githubusercontent.com/8625729/110455022-396a1480-80c8-11eb-8368-1e4ed2a65351.jpg)

### Actual result (*)
1. After the second category save, the only thing I see is the text and a media placeholder but without the image

![Selection_877](https://user-images.githubusercontent.com/8625729/110455151-5acb0080-80c8-11eb-9cc4-6f7bb16d9c32.jpg)

---

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Oscar** [comment] 2021-03-09 14:23
Hi @haroldclaus ! Thank you for your report.
Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop by following steps from this ticket.
### Steps to reproduce (*)
1. Edit a category in the backend
2. Add a description via the pagebuilder
3. Add a row
4. Add an image (upload an image)
5. Add another row
6. Add text
7. Save the category
8. You'll see the image AND the text in the description preview
9. Save the category one more without making any changes

**Actual Result:** :heavy_check_mark: 
After the second save of a category, the text and the image displaying in the description preview as they should
![Screenshot from 2021-03-09 16-21-06](https://user-images.githubusercontent.com/60198413/110484613-7bf51680-80f3-11eb-8618-80fdc48cf9dc.png)

So, we have to close this ticket.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch.
 Thank you for collaboration.

**Closed as completed** 2021-03-09 14:26 UTC
Labels: Issue: ready for confirmation, not-confirmed
