### ISSUE TITLE
URL key for specified store already exists. While saving Category magento2.1.2

### ISSUE THREAD

**Issue by canadasatellite** [magento/magento2#7777] opened 2016-12-13 13:51 UTC
### Preconditions

1. Magento version :2.1.2 
2. PHP Version 5.6.28
3. MySQL  Client API version	5.5.32
4. Data imported from Magento 1.9.2.4 using migration tool
5. category has same names . URL KEYS ARE DIFFERENT

### Steps to reproduce

1.  Tried to save category from admin

### Expected result

1. its should save category as the urlkeys used are different for each category and products

### Actual result

1. URL key for specified store already exists.
![satellite phones categories inventory products magento admin](https://cloud.githubusercontent.com/assets/24546040/21142651/303db088-c169-11e6-9fa9-ba7065891278.png)

**Comment by quienti** [comment] 2016-12-13 14:42
https://github.com/magento/magento2/issues/6671

**Comment by mowreggioemilia** [comment] 2017-01-20 10:04
same here on Magento 2.1.3 data imported from 1.8.1.0

**Comment by jimul** [comment] 2017-05-11 09:56
Same here on Magento 2.1.5 EE

**Comment by veloraven** [comment] 2017-07-06 09:06
@canadasatellite thank you for your report but I'm closing this issue as a duplicate of #6671

**Closed as completed by veloraven** 2017-07-06 09:06 UTC
Labels: bug report
