### ISSUE TITLE
URL Rewrites vs multiple storeviews - too many rewrites are being generated

### ISSUE THREAD

**Issue by hostep** [magento/magento2#11616] opened 2017-10-21 12:11 UTC
This case demonstrates that too many url rewrites are being generated
It happens in Magento 2.4-develop, I tested it in 2.2 and over there it works as expected

### Preconditions
1. PHP 7.2
2. Magento 2.4-develop

### Steps to reproduce
1. Setup a Magento 2.4-develop installation
2. In the backend, go to Stores > Configuration > Catalog > Catalog > Search Engine Optimization and change the configuration 'Use Categories Path for Product URLs' to 'Yes'
3. In the backend, go to Stores > All Stores and make sure you have 2 storeviews, I'm using 'Dutch' and 'French' as examples here
4. In the backend, go to Catalog > Categories and create 2 subcategories with the following url keys in the default values and 2 storeview specific (don't check the 'Create Permanent Redirect for old URL' checkbox while doing so):

| Tree                     | Name     | Default | Dutch      | French     |
| ------------------------ | -------- | ------- | ---------- | ---------- |
| Default Category/Level 1 | Level 1  | level-1 | level-1-nl | level-1-fr |
| Default Category/Level 1/Level 2 | Level 2  | level-2 | level-2-nl | level-2-fr |

5. In the backend, go to Catalog > Products and create a new simple product. I named it 'Product 2'.  Assign it to **both** categories 'Level 1' and 'Level 2'
6. Check the `url_rewrite` table in the database

### Expected result
| request_path                         | target_path                          | store_id |
| ------------------------------------ | ------------------------------------ | -------- |
| level-1-nl.html                      | catalog/category/view/id/3           | 1        |
| level-1-nl/level-2-nl.html           | catalog/category/view/id/4           | 1        |
| level-1-fr.html                      | catalog/category/view/id/3           | 2        |
| level-1-fr/level-2-fr.html           | catalog/category/view/id/4           | 2        |
| product-2.html                       | catalog/product/view/id/2            | 1        |
| level-1-nl/product-2.html            | catalog/product/view/id/2/category/3 | 1        |
| level-1-nl/level-2-nl/product-2.html | catalog/product/view/id/2/category/4 | 1        |
| product-2.html                       | catalog/product/view/id/2            | 2        |
| level-1-fr/product-2.html            | catalog/product/view/id/2/category/3 | 2        |
| level-1-fr/level-2-fr/product-2.html | catalog/product/view/id/2/category/4 | 2        |

#### Magento 2.4-develop
| request_path                         | target_path                              | store_id |
| ------------------------------------ | ------------------------------------     | -------- |
| level-1-nl.html                      | catalog/category/view/id/3               | 1        |
| level-1-nl/level-2-nl.html           | catalog/category/view/id/4               | 1        |
| level-1-fr.html                      | catalog/category/view/id/3               | 2        |
| level-1-fr/level-2-fr.html           | catalog/category/view/id/4               | 2        |
| product-2.html                       | catalog/product/view/id/2                | 1        |
| level-1-nl/product-2.html            | catalog/product/view/id/2/category/3     | 1        |
| level-1-nl/level-2-nl/product-2.html | catalog/product/view/id/2/category/4     | 1        |
| **level-1/product-2.html**           | **catalog/product/view/id/2/category/3** | **1**        |
| product-2.html                       | catalog/product/view/id/2                | 2        |
| level-1-fr/product-2.html            | catalog/product/view/id/2/category/3     | 2        |
| level-1-fr/level-2-fr/product-2.html | catalog/product/view/id/2/category/4     | 2        |
| **level-1/product-2.html**           | **catalog/product/view/id/2/category/3** | **2**        |

The two rows in bold shouldn't be generated.

**Comment by orlangur** [comment] 2017-10-21 15:03
Are `level-1/product-2.html` request paths working for those stores?

**Comment by hostep** [comment] 2017-10-21 15:09
Correct, so all these url's work:

Dutch storeview:
- level-1-nl/product-2.html
- level-1/product-2.html

French storeview:
- level-1-fr/product-2.html
- level-1/product-2.html

**Comment by magento-engcom-team** [comment] 2017-10-23 12:30
@hostep, thank you for your report.
We've created internal ticket(s) MAGETWO-82512 to track progress on the issue.

**Comment by engcom-Alfa** [comment] 2020-01-10 09:41
The issue is still reproducible on the fresh 2.4-develop instance

**Actual Result:**
![screen](https://user-images.githubusercontent.com/51679138/72142669-da165480-339d-11ea-8568-c80a85ea4a05.png)

**Comment by magento-engcom-team** [comment] 2020-01-10 09:45
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30342` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by slavvka** [comment] 2020-03-17 05:17
Hi @hostep. Thank you for your report. 
The issue has been fixed in magento/magento2#26784 by @hostep in 2.4-develop branch
Related commit(s):
 - [cb685d15b2b590bdb4d99a3d4ebe563037d0aa31](https://github.com/magento/magento2/commit/cb685d15b2b590bdb4d99a3d4ebe563037d0aa31)
 - [acb8642c44d1ecb60ad023c81f6541fa9ebae47d](https://github.com/magento/magento2/commit/acb8642c44d1ecb60ad023c81f6541fa9ebae47d)
 - [97258e1a9ce97ad32971731eceac8fee32f66b74](https://github.com/magento/magento2/commit/97258e1a9ce97ad32971731eceac8fee32f66b74)
 - [6cf26dc19e2f80f0c2da445443d0b48a1974fc77](https://github.com/magento/magento2/commit/6cf26dc19e2f80f0c2da445443d0b48a1974fc77)
 - [0b941218dcc86dcbd518f5400934e995ad1f2e3c](https://github.com/magento/magento2/commit/0b941218dcc86dcbd518f5400934e995ad1f2e3c)
 - [b0c0c59900b4ddf8d70cf2ae9c9ec12805d13908](https://github.com/magento/magento2/commit/b0c0c59900b4ddf8d70cf2ae9c9ec12805d13908)
 - [28fa34531f4c7cd4bcad46500ba027b9b58ff297](https://github.com/magento/magento2/commit/28fa34531f4c7cd4bcad46500ba027b9b58ff297)
 - [bf514b0b435a75f5688f56f8e9465af9bb3284c1](https://github.com/magento/magento2/commit/bf514b0b435a75f5688f56f8e9465af9bb3284c1)

The fix will be available with the upcoming 2.4.0 release.

**Closed as completed by slavvka** 2020-03-17 05:17 UTC
Labels: Issue: Ready for Work, Component: CatalogUrlRewrite, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Reproduced on 2.4.x, Fixed in 2.4.x
