### ISSUE TITLE
Visual Swatch - Configurable Products Edit Item Do not shows the selected option

### ISSUE THREAD

**Issue by gayankt** [magento/magento2#4440] opened 2016-05-10 02:33 UTC
01 . Add to cart Configurable product with Visual Swatch options enabled
02. Goto cart page and click edit item
03. The sected options are not shows on edit product page

![edit-product](https://cloud.githubusercontent.com/assets/654973/15134008/a7fa433c-1685-11e6-8609-964762f23ad2.png)

**Comment by pboisvert** [comment] 2016-05-12 15:27
Olena--assuming this may be your area given this is theme related.

**Comment by pboisvert** [comment] 2016-05-13 14:28
Tagging as improvement. Even if behaving as designed for better continuity for the shopper selected options should be preserved when returning to edit selections rather than a full reset.

**Comment by kandy** [comment] 2016-06-02 12:35
I cannot reproduce issue in latest mainline, so I am closing this issue, as fixed. Feel free to reopen issue if we missed anything.

**Comment by tkacheva** [comment] 2016-06-16 16:06
@gayankt  I can't reproduce the issue. Edit product has swatches in place. 
![edit_configurable](https://cloud.githubusercontent.com/assets/5603216/16123906/553a9f88-33f5-11e6-8986-236ae723c4ad.png)

Reopen if still has this issue

**Closed as completed by tkacheva** 2016-06-16 16:06 UTC
Labels: improvement, Component: Catalog

**Comment by Tyrianad** [comment] 2018-05-14 16:07
The issue is still persent, tested on Magento 2.2 and 2.3, clean install, Luma theme, single product.
Steps to reproduce are the same pointed at the beginning. As mentioned here #4684 the internal ticket should be MAGETWO-53459, i cannot find any fix for this issue, even if here #5218 @magento-engcom-team states it's fixed in develop 2.2.0
