### ISSUE TITLE
Clic on a product generates 404 not found

### ISSUE THREAD

**Issue by ILinKI** [magento/magento2#5754] opened 2016-07-22 09:01 UTC
Hi all !
I have some problems with the product urls.
I import 200 products from a csv file.
All products get quantity and are "In stock".
So I can see all the products appear in my listing products.
The problem is when I click on any products, it generates a 404 not found instead of details product page whereas all urls of each products are well stocked in url_rewrite in the database.

I found a "solution" like if I go to a product in the panel admin and I click on "Save" without modify any of my labels which already existed. I can come back to my listing products et click on this product, and the page is generated well.

But if I must click on "Save" for each products knowing in some days I will import thousands of products it will be a big problem.

Maybe I must modify a value (a boolean ?) in a particular table for all the products (like the button "Save" do ?) to activate pages of products.

Thanks for your answers and sorry for my bad english !

**Comment by veloraven** [comment] 2016-07-29 14:16
@ILinKI thank you for your report.
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by ILinKI** [comment] 2016-08-02 12:28
@veloraven ok sorry for not tagging it earlier
I am actually in magento 2.0.7.

I found a solution for my problem if someone wants to know or have the same problem that me, not a really neat solution but it works.

There is my solution, the products existed, but apparently needed to have "-" instead of " " (space) for matching with the url and once you updated your database with these requests, it works for all products.

UPDATE catalog_product_entity_varchar SET value = replace(value, ' ', '-') WHERE attribute_id IN (SELECT attribute_id FROM eav_attribute WHERE attribute_code LIKE 'url_key');

UPDATE url_rewrite SET request_path = replace(request_path, ' ', '-') WHERE entity_type like 'product';

**Comment by veloraven** [comment] 2017-06-21 10:24
I'm closing this issue as the problem was resolved.
If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by veloraven** 2017-06-21 10:24 UTC
Labels: bug report
