### ISSUE TITLE
Place Order doesn't work with sample data

### ISSUE THREAD

**Issue by ivanweiler** [magento/magento2#1503] opened 2015-07-16 12:05 UTC
Magento2 1.0.0-beta + Sample data 1.0.0-beta (I had same problem on previous 0.74.0-beta16)

Placing order from frontend/checkout raises exception:

main.CRITICAL: exception 'Zend_Db_Statement_Exception' with message 'Report ID: webapi-55a791090fd3e; Message: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '000000002-1' for key 'SALES_ORDER_INCREMENT_ID_STORE_ID'

This is most likely sample data problem. sequence_order_1 table is missing one entry for some reason, everything works if you insert new entry with next sequence number.

**Comment by vpelipenko** [comment] 2015-07-16 12:10
It is duplicate of https://github.com/magento/magento2/issues/1452.

**Comment by ivanweiler** [comment] 2015-07-16 12:22
Yes, sorry, missed that one :)

**Comment by vpelipenko** [comment] 2015-07-16 12:56
Closed as duplicate.

**Closed by vpelipenko** 2015-07-16 12:56 UTC
Labels: bug, MX

**Comment by vpelipenko** [comment] 2015-07-17 11:47
@ivanweiler, we've fixed this issue. Please, try to do sample data again, but before you need to clean composer cache, sample data package was updated, but has old version.
