### ISSUE TITLE
Interceptor.php generation failure in production mode

### ISSUE THREAD

**Issue by AirmanAJK** [magento/magento2#7026] opened 2016-10-14 20:59 UTC
Magento CE 2.1.2

I tracked down a bug in a third party extension where developer mode worked fine, but as soon as I moved to production mode, I was getting server 500 error responses. I tracked the problem down to a slight letter-casing difference in the namespace of a class that would have an Interceptor.php class generated on its behalf by Magento.

I believe errors likes this should show up consistently in both developer and production mode to avoid surprises after moving new code to a live server.
## STEPS TO REPRODUCE

Switch to developer mode.

Choose any class that will have a corresponding Interceptor.php file generated. For example:
\vendor\magento\module-catalog\Controller\Category\View.php
Change the namespace of this file to be as follows (note the uppercase Y at the end):
namespace Magento\Catalog\Controller\CategorY;

Save the file and clear out the /var/generation folder

Visit any category page in the store's frontend. No errors.
Now clear out /var/generation again and switch to production mode.
Visit the same category page.
## EXPECTED RESULT

The page would load as it did in developer mode since no code has changed.
## ACTUAL RESULT

Error. Here is the apache error entry:
[Fri Oct 14 15:55:47.847687 2016] [:error] [pid 3525] [client 192.168.1.157:33354] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Catalog\Controller\CategorY\View::__construct() must be an instance of Magento\Framework\App\Action\Context, instance of Magento\Framework\ObjectManager\ObjectManager given, called in /var/www/magento2/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93 and defined in /var/www/magento2/public_html/vendor/magento/module-catalog/Controller/Category/View.php:87\nStack trace:\n#0 /var/www/magento2/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Magento\Catalog\Controller\CategorY\View->__construct(Object(Magento\Framework\ObjectManager\ObjectManager))\n#1 /var/www/magento2/public_html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Catalog...', Array)\n#2 /var/www/magento2/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Compiled->create in /var/www/magento2/public_html/vendor/magento/module-catalog/Controller/Category/View.php on line 87

**Comment by sevos1984** [comment] 2016-10-19 16:02
I can't reproduce it using your steps, have you generated static content before enabling production mode?

**Comment by AirmanAJK** [comment] 2016-10-20 02:58
I cleared out all of my cache, di, generation, and pub/static subdirectories before running "deploy:mode:set production". So compilation and static-content deployment both occur.

When you say you can't reproduce the problem, are you saying that changing the namespace letter-casing to not match the file path will work in both developer and production mode, or fail in both developer and production mode?

Is there anything else I can provide to help diagnose? I have no trouble reproducing this problem on different classes.

**Comment by AirmanAJK** [comment] 2016-10-20 02:59
I also noticed that the Interceptor.php file generated for the classes in question are different for the two different versions of the namespace (the good and the bad one). It was what helped me pinpoint the problem to begin with.

**Comment by sevos1984** [comment] 2016-10-20 12:46
I mean everything works fine in both modes. The problem seems to be in case sensitive file system, are you using Windows?

**Comment by sevos1984** [comment] 2016-11-04 10:13
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-11-04 10:13 UTC
Labels: bug report, Progress: needs update, Component: Catalog
