### ISSUE TITLE
GET order search API response is not incorrect

### ISSUE THREAD

**Issue by srinivasanithin** [magento/magento2#7518] opened 2016-11-22 09:49 UTC
### Preconditions
1. We are using GA released version of Magento ver CE 2.1.2 setup.
2. We created some simple items and used that items to create orders.

### Steps to reproduce

1. Create a simple item itemToBeDelete and place an order using this only this simple item.
2. Now create some more items and place order using items excluding the itemToBeDelete.
3. When you make a REST API Call GET: /V1/orders?searchCriteria[currentPage]=1 and you will get all orders details
4. Now delete that item itemToBeDelete and then make a REST API Call GET: /V1/orders?searchCriteria[currentPage]=1 

### Expected result

1. It should only throw/give error for in one particular order related object and other order details should be made available in response or fail entire order API with proper status code. If status code is 200 then we expecting it to be successful and more over we don't even know fetching which order it failed.

### Actual result

1. It is given status code 200 when request body   
{
"message": "Requested product doesn't exist"
}

This is failing entire API call without explicit error or what is the cause of this issue we need to debug a lot to find that one item was deleted and it has failed entire order API result.

**Comment by olysenko** [comment] 2016-11-23 13:59
Hi, thank you for your report. Unfortunately I cannot reproduce this issue by provided steps on fresh install of Magento 2.1.2. In case you have installed extensions please disable them and try again

**Comment by vzabaznov** [comment] 2016-12-09 10:58
Hi @srinivasanithin , close this issue as we don't receive update for more than 2 weeks, please feel free to write here or reopen current / create new issue

**Closed as completed by vzabaznov** 2016-12-09 10:58 UTC
Labels: bug report, Progress: needs update, Component: Framework/Webapi
