### ISSUE TITLE
Buy X get Y free cart price rule does not show up on Coupons Report

### ISSUE THREAD

**Issue by petehouston** [magento/magento2#27848] opened 2020-04-14 03:51 UTC
### Preconditions (*)

1. A fresh installation of Magento version 2.3.4

### Steps to reproduce (*)

1. Access the admin backend.
2. On admin left sidebar, access **Marketing > Cart Price Rules**
3. Add any rule with "**Buy X Get Y Free**", let say a **BOGO**.
4. Create any order with **BOGO** applied.
5. Visit admin backend, select **Reports > Sales: Coupons**
6. On filter options, select "**Cart Price Rule: Any**", and click on **Show Report** button

### Expected result (*)

1. Order with BOGO (**Buy X Get Y Free**) doesn't show up on the Coupon Report

### Actual result (*)

1. It should display all orders that applied "**Buy X Get Y Free**" Cart Price Rule

**Comment by petehouston** [comment] 2020-04-14 03:52
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-14 03:52
Hi @petehouston. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-14 03:53
Hi @petehouston, here is your [Magento instance](https://i-27848-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27848-2-4-develop.instances.magento-community.engineering/admin_f5ec](https://i-27848-2-4-develop.instances.magento-community.engineering/admin_f5ec)
Login: `c1c9290c` Password: `9f0933cd1848`
Instance will be terminated in up to 3 hours.

**Comment by petehouston** [comment] 2020-04-14 04:05
yes

**Comment by petehouston** [comment] 2020-04-14 04:08
@magento yes I can reproduce the issue on this vanilla Magento instance

**Comment by ajijshekh123** [comment] 2020-04-14 05:53
Hello @petehouston,
I have verified this issue as per the steps, actual result and expected result.
See attached the screenshot:

![1](https://user-images.githubusercontent.com/24711761/79190551-39bf4880-7e42-11ea-8da3-5c820eb4bbaf.png)

![2](https://user-images.githubusercontent.com/24711761/79190557-3b890c00-7e42-11ea-8443-63c6dbc5b3bd.png)

Thanks.

**Comment by magento-engcom-team** [comment] 2020-04-14 05:54
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33341` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by tna274** [comment] 2020-04-14 14:39
Hi @petehouston,
The Coupons Report only shows orders that you applied discount with **coupon code**. According to your step, I think that you applied cart price rule without coupon code that why you did not see the order on report.
I created a cart price rule with coupon code and used it to create a new order.
![image](https://user-images.githubusercontent.com/14144384/79237423-55edd480-7e98-11ea-8f57-c9e1373ee0ea.png)
Then I could see it on my report
![image](https://user-images.githubusercontent.com/14144384/79237508-6d2cc200-7e98-11ea-9ca5-791b1b696e62.png)

**Comment by petehouston** [comment] 2020-04-14 16:58
@tna274  no. Cart Price Rule can be created with either No Coupon (auto applied on cart when conditions matched) or Specific Coupon. 

<img width="697" alt="Screen Shot 2020-04-14 at 11 55 29 AM" src="https://user-images.githubusercontent.com/9006720/79252323-0b903780-7e47-11ea-9a53-0b8278080c52.png">

In Coupons Report, there are also 2 options to filter Cart Price Rule: Any , Specific Coupon. If I select Any, it should show report for Cart Price Rule with No Coupon set.

<img width="912" alt="Screen Shot 2020-04-14 at 11 57 40 AM" src="https://user-images.githubusercontent.com/9006720/79252455-42664d80-7e47-11ea-8e07-e72ebf3b8291.png">

**Comment by srsathish92** [comment] 2020-04-15 14:07
@ajijshekh123 This issue is not valid, because coupon reports only shows the list which order has applied coupon code not no coupon (cart price rule). please re validate.

**From Doc:**
_Cart Price Rules :_ Determines which coupon promotions are included in the report.
Options:
_Any:_ Includes order information for any coupon promotion that was used during the specified date range.
_Specified:_ Includes only order information for the selected coupon promotion during the specified date range.

**FYI:**
https://docs.magento.com/m2/ce/user_guide/marketing/price-rules-cart-coupon-report.html
https://docs.magento.com/m2/ce/user_guide/marketing/price-rules-cart-coupon.html

**Comment by petehouston** [comment] 2020-04-15 14:50
@srsathish92 is there any way to get Report for any order having Cart Price Rule that doesn't use Specific Coupon Code?

**Comment by srsathish92** [comment] 2020-04-15 16:50
@petehouston Not at the moment.

**Comment by ajijshekh123** [comment] 2020-04-16 05:35
Hello @srsathish92,
You are right. But Report should be displayed to all the coupon lists which we have applied to place the order. That's why I have verified this issue.
Thanks.

**Comment by srsathish92** [comment] 2020-04-16 14:08
> Hello @srsathish92,
> You are right. But Report should be displayed to all the coupon lists which we have applied to place the order. That's why I have verified this issue.
> Thanks.

Yes, As per the steps to reproduce coupon reports working fine, from your [comments](https://github.com/magento/magento2/issues/27848#issuecomment-613240160) you didn't added a  coupon code. Its seems just a cart price rule with no coupon code. Then how it shows in report?

can you please confirm?

**Comment by swapnilT2jcommerce** [comment] 2020-06-12 12:46
Hi @petehouston ,

Yes, I have tried to replicate this case as mention steps and found that, it's working as expected.

If you go through Magento reference doc, you will understand the use of this option  **Any** or **Specific** of Cart Price Rule field in coupon report section.  

https://docs.magento.com/user-guide/marketing/price-rules-cart-coupon-report.html

**Cart Price Rules** | Determines which coupon promotions are included in the report. 

**Options:**

**Any:** Includes order information for any coupon promotion that was used during the specified date range.

**Specified:** Includes only order information for the selected coupon promotion during the specified date range.

Please see the screenshot: -

**Coupon report with Any option**
![cart-price-rule-with-any-option-in-coupon-report](https://user-images.githubusercontent.com/18118677/84503420-c8800280-acd7-11ea-8d5a-de8f2222b06d.png)

**Coupon report with Specific option**
![specific-coupon-report](https://user-images.githubusercontent.com/18118677/84503424-c9b12f80-acd7-11ea-8809-193714251bf4.png)

This issue is not valid

**Comment by sdzhepa** [comment] 2020-06-22 16:03
Reverified on the lates `2.4-develop`

Not able to reproduce it now

Report: **Cart Price Rule = Any**
![2020-06-22_11-00-34](https://user-images.githubusercontent.com/3409584/85309161-cce6b100-b477-11ea-9b22-1cb8110cafec.jpg)

Report: **Cart Price Rule = Specified**
![2020-06-22_11-01-04](https://user-images.githubusercontent.com/3409584/85309171-d243fb80-b477-11ea-872e-add5217f882b.jpg)

**Closed as completed by sdzhepa** 2020-06-22 16:03 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Reports, Component: Admin, Reproduced on 2.4.x, Reported on 2.3.4
