### ISSUE TITLE
Checkout with PayPal throws a "Something went wrong ......" error

### ISSUE THREAD

**Issue by chequille** [magento/magento2#28092] opened 2020-05-03 21:28 UTC
### Preconditions (*)

1. Magento Version 2.4 -develop
2. Paypal Sandbox Configuration Enabled
3. InContext Checkout Disabled

### Steps to reproduce (*)

1. Do a Checkout 
2. Click Paypal Radio and Click on "Continue to Paypal" button

### Expected result (*)

1. Of course not showing this error, because PayPal is still opened and the order is processed till the end

### Actual result (*)

1. Getting this error after Pay Button is pressed, but the change to the PayPal site is still happening.
![errormessagepaypalpayment](https://user-images.githubusercontent.com/15807794/80926133-889f3480-8d95-11ea-8821-3d59d0e2e1d8.png)

I just installed my backups from 2.3.4 version and there it does not happen.
So something within the 2.3.5-p1 update must be the reason for this.

Ok, the order is still processed but sorry, I do not want to see this error message, even if it is disappearing after a few seconds and the page is moving to PayPal sites.

Unfortunately, nothing logged in the log directory or in the the report directory.

**Comment by chequille** [comment] 2020-05-04 06:33
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment] 2020-05-04 06:33
Hi @chequille. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-05-04 06:34
Hi @chequille, here is your [Magento instance](https://i-28092-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28092-2-4-develop.instances.magento-community.engineering/admin_d845](https://i-28092-2-4-develop.instances.magento-community.engineering/admin_d845)
Login: `31c6188a` Password: `b042640d8753`
Instance will be terminated in up to 3 hours.

**Comment by chequille** [comment] 2020-05-04 07:01
Hi,
I confirm it is happening as well on the 2.4-develop instance.
Here is the screenshot
![errorondevinstance](https://user-images.githubusercontent.com/15807794/80942503-3d147700-8de5-11ea-8b51-033876a78b68.png)

Used my sandbox account and "InContext Checkout" is disabled.

If "InContext Checkout" is enabled, the error messages does not appear.

**Comment by chequille** [comment] 2020-05-04 21:11
Any idea yet?

**Comment by prasannachelladurai90** [comment] 2020-05-12 06:39
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-12 06:39
Magento instance deployment temporary unavailable due to service maintenance.

**Comment by plastikschnitzer** [comment] 2020-05-14 19:03
As long as I see its not distracting the paypal checkout workflow.

With Website Payment Standard, the option "InContext Checkout" enabled @chequille described above is not available.

Quick and (very) dirty fix to hide the message from customers with css:
`.checkout-index-index .message.message-error div{display: none !important;}`

**Comment by chequille** [comment] 2020-05-14 19:25
Hi, this is relly quick and dirty. I thought to do so as well, but if a real error occurs, the message is also not shown.
Therefore no solution.
What I found is, that it does not happen every checkout. Sometimes it went through without showing the message, the next time it is showing.
Maybe it has to do with the PayPal Sandbox??????

Nevertheless, as this error was not there in 2.3.4, there is some change somewhere cuasing this and therefore it needs to be investigated.
My opinion!!

Best regards and stay healthy :-)

**Comment by prasannachelladurai90** [comment] 2020-05-15 06:02
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-15 06:02
Hi @prasannachelladurai90. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-05-15 06:04
Hi @prasannachelladurai90, here is your [Magento instance](https://i-28092-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28092-2-4-develop.instances.magento-community.engineering/admin_57d9](https://i-28092-2-4-develop.instances.magento-community.engineering/admin_57d9)
Login: `367d4cbf` Password: `e07f143057ef`
Instance will be terminated in up to 3 hours.

**Comment by prasannachelladurai90** [comment] 2020-05-15 07:27
Hi @chequille By Default 2.4 Magento Instance does not have paypal enabled in Front End. Do you have Sandbox credentials to test this issue?

**Comment by prasannachelladurai90** [comment] 2020-05-15 15:49
Hi @chequille I tried to reproduce the issue in Magento 2.4 and it did not occur to me 
Please find the video attachment https://drive.google.com/open?id=1gN771KPKxUuRljOx7-PjUCBPAHrQN6aH. Am i missing something here ?

**Comment by chequille** [comment] 2020-05-15 19:57
Sorry, can not acces the video.

**Comment by prasannachelladurai90** [comment] 2020-05-16 03:38
Sorry I have granted Permission. You should able to see the Video now. And i did try multiple times going to Payment From Checkout.

**Comment by chequille** [comment] 2020-05-16 07:17
Sorry, still saying no permission to open the video.

**Comment by prasannachelladurai90** [comment] 2020-05-16 07:53
@chequille I think you should be able to view now

**Comment by chequille** [comment] 2020-05-16 08:05
Sorry, no.
Page is saying redirection error!?!?

**Comment by prasannachelladurai90** [comment] 2020-05-16 08:14
@chequille Permission is set from My end and this is the Link https://drive.google.com/file/d/1gN771KPKxUuRljOx7-PjUCBPAHrQN6aH/view?usp=sharing
Can you please try opening the Link again or Refreshing the Page?

**Comment by chequille** [comment] 2020-05-16 09:29
It is not working
![grafik](https://user-images.githubusercontent.com/15807794/82116212-506dfd80-9768-11ea-89b2-94b986ba2b7c.png)
To which email address you set the permission. Google is saying no permission. Do not know whats happening here !?

**Comment by chequille** [comment] 2020-05-16 09:30
In the picture it says Perrmission missing. I am logged in with the account for js@chequille.de

**Comment by prasannachelladurai90** [comment] 2020-05-16 09:56
@chequille Ah the Permission is set to your gmail account "chequille22@gmail.com" can you please open it from your gmail

**Comment by chequille** [comment] 2020-05-16 11:52
Hi Again,
ok, now I got it. Question: where did you get this email from? Im wondering, because here in github i am logged in with another one !?!?!?!

Ok, back to the problem:
it is clear, the error message does not occure if "InContext Checkout" is enabled.
You have to disable "InContext" in the configuration of PayPal.
Than you will get the error message, as I have it in my setup and as I could reproduce in the 2.4 develop instance.

- Strange is, that if you change this now, it can be, that the frist checkout is ok, but if you try a second, third ect. checkout, thant the error message comes up.
- Strange as well is, that all orders are proceeded correct.
- Strange as well, this behaviour was definetely not within 2.3.4

Looking forward to hearing from you.
Best regards,
Jürgen

**Comment by prasannachelladurai90** [comment] 2020-05-19 07:47
@chequille I Pasted the Drive link here and it automatically took the email. 

And Coming to the Bug. I did try Disabling the InContext Checkout in Paypal Configuration 
![image](https://user-images.githubusercontent.com/60870557/82296552-f91d9680-99ce-11ea-9c2b-97a72ecb9be7.png)
But i was unable to re create the issue During multiple checkouts
Please refer to the Video Session
https://drive.google.com/open?id=1cvBMHj_tDR2fDqfajhcCY34gkcQQFJIw

**Comment by chequille** [comment] 2020-05-19 18:07
Hi,
sorry, the error occurs after pressing "Continue to Paypal", not as you did just selecting PayPal as payment method.
Of course you will not see it. 

So again, go on with the checkout and press continue to paypal.

Regards,
Jürgen

**Comment by chequille** [comment] 2020-05-19 18:19
https://drive.google.com/file/d/1J_s-eMnESuqrIEwU9Mw4i2zA1L_GTlPS/view?usp=sharing

Ok, this is now my video.
After Pressing "Zahlungspflichtig bestellen" the error occurs before it is going to the PayPal site.

**Comment by chequille** [comment] 2020-05-19 18:20
PS: of course "Zahlungspflichtig bestellen" is on your site "Continue to PayPal"

**Comment by prasannachelladurai90** [comment] 2020-05-21 10:01
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-21 10:01
Hi @prasannachelladurai90. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by chequille** [comment] 2020-05-25 07:58
@prasannachelladurai90 
Could you reporduce it now?
Again the information: it does not happen in 2.3.4
Regards
Chequille

**Comment by prasannachelladurai90** [comment] 2020-05-25 09:11
@chequille Thanks for checking in. My magento instance seems to be down and i have requested for a new instance but haven't received one yet. Will get back to you once the instance is up.

**Comment by prasannachelladurai90** [comment] 2020-05-25 09:11
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-25 09:11
Hi @prasannachelladurai90. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by Sutharsan27** [comment] 2020-05-26 06:55
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-26 06:55
Hi @Sutharsan27. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by prasannachelladurai90** [comment] 2020-05-26 08:12
@chequille The issue is Reproduced on the  2.4-develop branch

Please refer to attachment https://drive.google.com/open?id=1_WgX9rifH5l_Ud6thz3MS-E_rPPQU5J1

and i have also edited the steps to Recreate. Thanks for the inputs

**Comment by magento-engcom-team** [comment] 2020-05-26 08:16
:white_check_mark: Confirmed by @prasannachelladurai90 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34638` were created

**Issue Available**: @prasannachelladurai90, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment] 2020-05-27 13:33
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-27 13:33
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by chequille** [comment] 2020-06-03 07:25
Any news about this?
When will it be fixed?
Is there a workaround?

This prevents me to go online with the new shop and i have to stay with 1.9.x.x
What is the status of this?

Regards,
Jürgen

**Comment by LLudas** [comment] 2020-06-08 16:18
Hello,
this have nothing to do with paypal. I guess that this is checkout problem. But I can't figure out where yet.
We have upgraded from Magento Comunity 2.3.4 to 2.3.5 and since first minute this issue didn't gone.

Here's the link to the video how everything is happening:

https://drive.google.com/file/d/1r20BS66GVjfGLwcBuWPiBIXSnqI2d1ms/view?usp=sharing

Email order is being sent but not possible for users to finish the purchase process.

Is there any solution for that bug to be fixed? 
It would be great if anyone have some good ideas where to look.
Thank you.

**Comment by chequille** [comment] 2020-06-08 22:11
@LLudas 
Hi, but this must be some other problems, as on my site the purchase finished. And as you see in my video above, there is only the error message shown when PayPal is used as payment method. When using f.e. banktransfer the error does not occur.

Did you check the error logs? It might be some incomatibility with your theme or used extensions.
So on my site, it is definetely only with paypal.
Regards,
Chequille

**Comment by zeeshan2523806** [comment] 2020-06-12 10:18
Hi, i can confirm this error is also being reproduced on other payment methods as well. any luck with the solution ?

**Comment by chequille** [comment] 2020-06-12 11:08
@zeeshan2523806 
ok, but question: is on your site the order processed till the end or not as @LLudas reported?

This is a main difference, because on my site, I do only get this error message shown for a few seconds and afterwards it is going to PayPal site and I make my payment and get at the end the checkout success page.

How is it on your site?

**Comment by chequille** [comment] 2020-06-24 08:33
Hi Guys,
it is coming to a very important state, because my customer is forcing me to go online with the new shop latest 1 July 2020.
As a matter of facts, I do need a solution for this.

What I found is, that it seems to be a browser issue, because I tried as well with Chrome and the error message does not occur.
On Firefox, the error is in costumer-data.js of the Magento_Customer module.
Maybe this helps to find at least a workaround.

Please be so kind and let me know how this issue is handled and maybe somebody has already a patch which I could use.

Looking forward to hearing from you soon.
Best regards,
Chequille

**Comment by plastikschnitzer** [comment] 2020-06-24 08:55
Its a true nightmare for those who have to migrate and are faced with such a bug.

As I said above, I migrated a while ago and hided the error message by css – a very quick and dirty fix as Paypal still works in my case and the error message is useless here. I think with my code you still see a red box, so just change the background color of that box or find the correct class to hide all of that.

Downside: All other payment method related error are also hidden. No problem if you only have paypal or payment methods which cannot throw any error message ;-)

If you want to be more specific and only hide the paypal error message, you can build a little more advanced filter by javascript and just hide the paypal error message and and not the others, this link might be helpful for you: https://stackoverflow.com/questions/46790860/hide-div-that-contains-specific-text

Maybe I will build it like this soon and I will share the result, but I am packed now with other post-migration bugs so no time to work on things like this atm.

**Comment by ezzyloud** [comment] 2020-07-13 04:16
Any updates on this guys? It's the only thing stopping my new store.  Thank you

**Comment by dev-Dhaval** [comment] 2020-07-24 12:12
I am also facing same issue.
Its related to get-totals.js that file is not return cart total data that's why its throwing this error.
If i removed the line from get-totals.js then its working fine.
deferred.reject();
errorProcessor.process(response);

This is error is only visible on firefox browser.

**Comment by chequille** [comment] 2020-07-24 20:04
It seems nobody cares about bugs.

But guys, we will have soon a new version 2.4.x.
You will see, there are all bugs fixed and a lot of new bugs will be there!!!!!

I am really thinking about changing the system. The only fact that I did not do it yet is, that I made a couple of changes in extensions to get the shop working as I want.
I really fear about upgrading when 2.4.x is out. Currently my shop is up and running (so far ok), but what will be after uprgading?

As well since two weeks, the magento 2.4 instance stuff is not working and I can not try to reproduce some other bug (maybe not bug :-) ) Really strange.

Ok, enough for today. There are some more important things to do. It is weekend :-)

Regards to everybody and keep on fighting !!!
Chequille

**Comment by tushhan** [comment] 2020-08-28 15:48
I am using Magento 2.3.5-p2 and having the same problem, I don't know what is causing this but some customers facing the same issue while others not, and this makes me think whether Magento checkout page is compatible with all browsers or not. 

It has been weeks now, no solution, and many customers think to move Shopify or similar platforms because of these bugs and problems while Magento fails many users and people can not sell their goods online. It is a shame and I wish there could be a more agile team resolving issues for Magento.

**Comment by almr** [comment] 2020-10-02 16:41
tushhan, I am using Magento 2.3.5-p2 also and having the same problem. Any solution you found?
No way to find the issue, still struggling, it looks like attacks from hackers which made checkout dis-functional.

**Comment by LLudas** [comment] 2020-10-02 18:57
HELLO, everyone,
the easiest way is to move to Magento 2.4 this bug is fixed there.
Thank you everyone for solutions and answers.

**Comment by chequille** [comment] 2020-10-02 19:52
Unfortunately, moving to 2.4.0 is not that easy as you say with all the new requirements like ElasticSearch !!!!

**Comment by tushhan** [comment] 2020-10-02 20:00
Hi, just let you know. The problem we had was because of a wrong number of website (scope) given to products. Let’s say the default website has number 1 in product CSV, I have detected that the numbers were changed to 3 or 4 and some 0. I have corrected all by downloading inventory and changed settings correctly in csv and uploaded, after that we didn’t have problem.

I had this problem with one of my client’ website who migrated from M 1 to M 2. They also created  new websites on the same magento and I guess they messed up there the settings of products. 

If a product with wrong website setting added to cart then at checkout website gives an error, as you can not buy a product that is not belong to the default (or whichever is chosen) website.

**Comment by JoostWan** [comment] 2020-10-07 11:35
@tushhan you mean _website_id_ inside **catalog_product_website**? Checked it but there a no record with website_id that doesn't exist.

**Comment by tushhan** [comment] 2020-10-07 20:45
In my case, it is "website_id" as seen on the attached screenshot but it could be "catalog_product_website" on another Magento. You can download an existing SKU and check the CSV column to find the right column name.

![Screenshot 2020-10-07 at 21 39 16](https://user-images.githubusercontent.com/746774/95385568-130c3700-08e6-11eb-8506-1a2436065e60.png)

**Comment by Amit-Hariyani** [comment] 2020-10-10 05:15
@magento I am working on this

**Comment by chequille** [comment] 2020-11-08 12:35
What is the solution for that? Why closed? 
Getting angry now!!!

**Comment by hostep** [comment] 2020-11-08 17:21
@chequille: there is some sort of automation problem happening for a while here which closes tickets for some reason. But @sdzhepa often manually leaves a comment a few days later to explain why it was closed. So @sdzhepa: if you could figure out why this one got closed, that would be appreciated! 🙂

**Comment by brianrootways** [comment] 2020-11-13 09:15
I am getting an error (Something went wrong with your request. Please try again later.) while doing PayPal express checkout in firefox especially and redirect to PayPal website. In chrome, edge etc. working fine. Here I give you a screenshot for better understanding.

Can you please help me to fix this issue?

![paypal-express](https://user-images.githubusercontent.com/68637204/99052871-d1466e80-25be-11eb-9e5d-df51c144be68.jpg)

**Comment by cengizcoskun** [comment] 2020-12-03 14:19
Did you find any solution? I have same problem.

**Comment by Amit-Hariyani** [comment] 2020-12-06 07:21
Well this error comes because of Magento_Csp extension , it creates some problem for paypal so disable the Magento_Csp extension, set all paypal configurations for paypal payment method from magento admin and try again,

I hope error will gone.

**Comment by chequille** [comment] 2020-12-06 23:12
@Amit-Hariyani 
Hi, unfortunately this did not solve the problem in my setup.
As well I do not know if it is a good idea to disable this, because maybe some other extensions depend on it.

**Comment by brianrootways** [comment] 2020-12-07 04:10
@Amit-Hariyani Hi, I did disable CSP module but we are getting an error while doing PayPal express checkout. @chequille 

![image](https://user-images.githubusercontent.com/68637204/101308484-fce01000-386f-11eb-91de-56243fac2913.png)

Maybe its causes because of customer-data.js error (line number: 95) throw in the console.

![image](https://user-images.githubusercontent.com/68637204/101308506-09fcff00-3870-11eb-861a-ebdc3d92430e.png)

**Comment by brianrootways** [comment] 2020-12-10 12:17
@chequille  Let me know if you find any solution regarding to error: PayPal express checkout error something went wrong with your request.

**Comment by chequille** [comment] 2021-04-09 05:13
Hi All,
still have this problem as well on Magento 2.4.2
Can somebody let us know if this will be fixed sometimes???????

**Comment by arunkumar247** [comment] 2021-04-29 11:01
@magento-engcom-team 
I am also facing the issue in 2.4.1-p1 . Is there any steps taken to fix the issue? Why the ticket status is closed?
Please consider re-opening this issue and find the cause.

**Comment by 5m-solutions** [comment] 2021-05-04 11:52
We resolved this by removing the 'Email Associated with PayPal Merchant Account' and leaving it blank. A capital in this was the issue and on another client account they got their email mixed up. As the API is used anyway you don't need this filled in on the new Magento versions we believe. Works fine without it.

**Comment by magento-engcom-team** [comment] 2021-05-04 12:43
:white_check_mark: Confirmed by @Den4ik 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34638` were created

**Issue Available**: @Den4ik, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by chequille** [comment] 2021-05-05 04:57
@5m-solutions 
Hi, it does not work on my test shop using 2.3.5p2 version. I still get the error message "something went wrong ......."
Which version do you use?
Regards,
Chequille

**Comment by engcom-Oscar** [comment] 2021-05-05 14:36
I could reproduce this issue on latest 2.4-develop branch using Firefox browser.

**Comment by chequille** [comment] 2021-05-05 17:54
I confirm this on 2.4.2
I cannot test develop branch. 
But I do not wonder that it is still an issue, because it seems that nobody cares !!!!!!!
As it is with other things.
I am not happy, because I cannot switch to 2.4.x version. We rented a V-Server 6 months ago to get 2.4.x requirements and to be aible to switch but I am still online with 2.3.5 on a hosting server.
It is a shame, sorry guys but it is as I said.

Looking forward to find some solved issues here
Regards,
Chequille

**Comment by muxmix** [comment] 2021-05-16 13:25
> We resolved this by removing the 'Email Associated with PayPal Merchant Account' and leaving it blank. A capital in this was the issue and on another client account they got their email mixed up. As the API is used anyway you don't need this filled in on the new Magento versions we believe. Works fine without it.

This solution worked for me too! Thanks 5m

**Comment by plastikschnitzer** [comment] 2021-05-18 05:35
Thank you @5m-solutions for the idea, I removed the email and the issue was still there.

Then checked all my paypal settings and disabled the method "Website Payment Standard" and enabled "PayPal Express" and the issue was gone! Not sure what Website Payment Standard is doing there because its handled by PayPal Express anyway as far as I can see.

So anyone who cannot solve it by simply removing the email address, check if you use website payment standard or PayPal Express and switch to express. Maybe this will solve it for you as well.

**Comment by chequille** [comment] 2021-08-29 07:18
Unbelievable, still happens in version 2.4.3
What are you going to do with this?

**Comment by chequille** [comment] 2021-10-21 05:09
Little bit confused now!!!!
Just made a few orders on my site with firefox and did not get the error anymore.
My firefox is version 93.0
Could it be tht firefox changed something?

**Comment by convenient** [comment] 2021-12-16 15:49
We're seeing this issue as well on an enterprise client. Replicable on safari and firefox when you quickly click the paypal button after selecting the payment method.

**Comment by plastikschnitzer** [comment] 2022-01-05 09:18
@convenient did you enter the paypal email address in the backend? Try to remove it and see if it still appears, this field is not mandatory and solved the issue for me.

**Comment by LLudas** [comment] 2022-01-05 09:28
What we did:
We've updated magento to newer version (actually reinstalled freshly everything) and problem was solved. Probably there was a fix in newer version. This is the best and easiest solution to upgrade.
Another solution to disable Paypal payment. This should solve this problem too.
BR

**Comment by plastikschnitzer** [comment] 2022-04-12 19:40
According to the release notes of Magento 2.4.4, the issue is fixed there! Maybe someone can test and confirm?

https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-4.html

**Comment by hostep** [comment] 2022-04-19 18:04
The following is just FYI, no confirmation from my end.

@plastikschnitzer probably means this entry from the release notes of Magento 2.4.4:
> Magento Open Source no longer displays an error during checkout with the PayPal Express payment method. Previously, although the checkout process completed, Magento Open Source displayed this error: Something went wrong.

This is linked to internal ticket number MC-42154 of which I can only find this commit: https://github.com/magento/magento2/commit/d2666309e925856c9854b3c65af0bdb4730b0c43

Again, no confirmation if this is a fix for this issue, this is just information I gathered from the release notes.

**Comment by plastikschnitzer** [comment] 2022-04-19 18:19
I could not check with Magento 2.4.4 yet, but I used the chance now to apply the commit @hostep mentioned to Magento 2.4.3-p1 and it solves the issue for me. Thank you @hostep for doing the research for the commit!

Give it a try ;-)

**Comment by Xuanmoi** [comment] 2022-09-30 07:26
I also encountered this problem. 
From the network point of view, the safari browser, using paypal to place an order, will repeatedly send the request, send 4 set-payment-information requests, (normally 2 times), and thus send 2 get-total requests (normally 1 time) times), the second get-total request fails, resulting in the display of an error message.
Temporary solution: The set-payment-information request sent when placing an order with paypal does not send a get-total request.
Hopefully there will be a better solution later.

**Comment by engcom-Delta** [comment] 2024-08-05 10:49
Hi @chequille  ,

Thanks for your reporting and collaboration.
We have verified the issue in latest 2.4-develop instance, but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce.**
1. Enable PayPal Sandbox Configuration.
2. Disable InContext Checkout.
<img width="890" alt="paypal config" src="https://github.com/user-attachments/assets/acefcace-979d-4710-9bd4-e9e1d87fe30d">
3. Add items to cart.
4. Navigate to checkout.
5. Enter shipping address and select shipping method.
6. Select PayPal as Payment method.
7.  Click on "Continue to PayPal"


https://github.com/user-attachments/assets/d34cd9cb-8b8d-4ca6-859c-9fd52ab45923



Please let us know if any other steps are needed to be performed.

Thanks.

**Comment by engcom-Delta** [comment] 2024-08-21 12:37
Hi @chequille,

We have noticed that this issue has not been updated since long time.
Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by engcom-Delta** [comment] 2024-08-21 12:38
Hi @chequille,

We have noticed that this issue has not been updated since long time.
Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Delta** 2024-08-21 12:38 UTC
Labels: Component: Payment, Reproduced on 2.4.x, Priority: P2, Severity: S3, Progress: done, CD, Issue: needs update, Reported on 2.3.4, Area: Payments
