### ISSUE TITLE
Previous scrolling to invalid form element is not being canceled on hitting submit multiple times

### ISSUE THREAD

**Issue by lukeromanowicz** [magento/magento2#21715] opened 2019-03-12 12:16 UTC
### Preconditions (*)
Magento 2.3-develop, possibly older versions

### Steps to reproduce (*)
1. Go to a product page
2. Enter an invalid value like -1
3. Hit 'Add to cart' several times
4. When you get scrolled to the qty input try scrolling away

### Expected result (*)
When scrolling is finished, the form will let you scroll away, no matter how many times you hit the add to cart button

### Actual result (*)
You will be getting scrolled back to the qty input exactly same amount of times that you hit add to cart button.

**Comment by magento-engcom-team** [comment] 2019-03-12 12:16
Hi @lukeromanowicz. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@lukeromanowicz do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by lukeromanowicz** [comment] 2019-03-12 12:17
@magento-engcom-team give me 2.0 instance

**Comment by lukeromanowicz** [comment] 2019-03-12 12:18
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-12 12:18
Hi @lukeromanowicz. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-12 12:19
Hi @lukeromanowicz, here is your [Magento instance](https://i-21715-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21715-2-2-develop.instances.magento-community.engineering/admin](https://i-21715-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by lukeromanowicz** [comment] 2019-03-12 12:23
2.2-develop and 2.3-develop confirmed

**Comment by magento-engcom-team** [comment] 2019-03-12 16:19
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-03-12 16:20
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98661`, `MAGETWO-98662` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Al3ks73** [comment] 2019-03-13 07:41
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-04-15 20:40
Hi @lukeromanowicz. Thank you for your report. 
The issue has been fixed in magento/magento2#22117 by @yvechirko in 2.3-develop branch
Related commit(s):
 - [3e0836e142b3e48c9d3644e8e1a6044a31aeeaad](https://github.com/magento/magento2/commit/3e0836e142b3e48c9d3644e8e1a6044a31aeeaad)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-04-15 20:40 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Area: Design/Frontend

**Comment by magento-engcom-team** [comment] 2019-04-26 15:10
Hi @lukeromanowicz. Thank you for your report. 
The issue has been fixed in magento/magento2#22358 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [bcc45269c187cdafb144dc1c2e40b78be6050fc8](https://github.com/magento/magento2/commit/bcc45269c187cdafb144dc1c2e40b78be6050fc8)

The fix will be available with the upcoming 2.2.9 release.
