### ISSUE TITLE
Creating a creditmemo without products doesn't work anymore in 2.4

### ISSUE THREAD

**Issue by antonfries** [magento/magento2#35333] opened 2022-04-20 07:37 UTC
### Preconditions (*)
1. Magento 2.4.3-p2

### Steps to reproduce (*)
1. Create an order
2. Create an invoice
3. Try to issue a partial refund without giving the products back

### Expected result (*)
![2022-04-20_09h34_32](https://user-images.githubusercontent.com/49792220/164175353-21987b33-aa33-4ab9-bd8b-4f5954987ba2.png)
Does work in latest 2.3.7-p3 release, updating qty to 0 results in order total = 0

### Actual result (*)
![2022-04-20_09h35_45](https://user-images.githubusercontent.com/49792220/164175619-06cf04d6-4134-400a-9384-e960463f64ac.png)
Updating qty to 0 doesn't affect order total, creating refund with field "adjustment fee" renders products in creditmemo pdf

---
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by engcom-November** [comment] 2022-04-20 09:30
@antonfries ,
Thank you for reporting and collaboration. Verified this issue on both Magento 2.4-develop branch and 2.4.3-p2 instance but cannot able to reproduce the issue.
Steps performed:
Create Order
Submit Invoice
Click on Credit Memo - Update Qty to "0" -  "Refund Offline" button is disabled
Enter partial refund amount and click on Update Totals - Refund Offline button is enabled
Click on Refund Offline - Working fine
Credit memo issued.
![image](https://user-images.githubusercontent.com/60198231/164197515-ea7bbdca-570e-468c-bf1b-3fc1a2dc3153.png)

![image](https://user-images.githubusercontent.com/60198231/164197437-6eaf12e9-2318-411f-97f3-b3d26c1915b4.png)
Kindly recheck the issue on Magento 2.4-develop branch as it is the upcoming 2.4.x release / have latest code base and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by antonfries** [comment] 2022-04-20 12:48
There is some more configuration necessary to get to the code block, which is not working:
![2022-04-20_14h39_07](https://user-images.githubusercontent.com/49792220/164232823-401f7b6e-cad6-4e38-b188-03d1c0722ef1.png)
Method call $rate->getId() in vendor/magento/module-sales/view/adminhtml/templates/order/totals/tax.phtml Line 62 and 77
My sample configuration (a bit overloaded), transported from a customer project:
admin/system_config/edit/section/carriers/:
![2022-04-20_14h44_18](https://user-images.githubusercontent.com/49792220/164233188-9b9f25fb-f4b4-491d-a350-2ca688929185.png)
admin/system_config/edit/section/tax/:
![2022-04-20_14h45_07](https://user-images.githubusercontent.com/49792220/164233443-1769fc10-4f42-46fb-988d-35f820a06a05.png)
![2022-04-20_14h45_19](https://user-images.githubusercontent.com/49792220/164233449-4906f9a2-4ee3-4eff-9e26-82fdd97977a5.png)
![2022-04-20_14h45_25](https://user-images.githubusercontent.com/49792220/164233451-94a74e64-bb39-4b53-a0de-e12fc496b2bc.png)
Some tax rules:
![2022-04-20_14h46_41](https://user-images.githubusercontent.com/49792220/164233839-d56bbefc-43f3-4dc2-841c-b615652bca5b.png)
![2022-04-20_14h46_59](https://user-images.githubusercontent.com/49792220/164233842-4de4d93f-5de9-416e-a7ca-e443b3760a19.png)
![2022-04-20_14h47_37](https://user-images.githubusercontent.com/49792220/164233844-84b58943-39df-40cc-ac8a-b73e0e6d28e2.png)

**Comment by antonfries** [comment] 2022-04-20 12:53
And then take the free shipping method in the order to get no taxes applied to not get into the if-block in vendor/magento/module-tax/Helper/Data.php::763
`if ($shippingTaxAmount && $originalShippingTaxAmount &&
            $shippingTaxAmount != 0 && (float)$originalShippingTaxAmount
        )`

**Comment by engcom-November** [comment] 2022-04-22 07:22
@magento give me 2.4-develop instance

**Comment by antonfries** [comment] 2022-04-22 07:42
Did some research, seems to be fixed in 2.4.4: https://github.com/magento/magento2/commit/d648bdc238ba6b59890694251655f725ad1b5d88
Error seems in 2.4.3-p2: https://github.com/magento/magento2/blob/2.4.3-p2/app/code/Magento/Sales/view/adminhtml/templates/order/totals/tax.phtml line 62,77
So we fixing this in all our 2.4.3 customer projects 👍

**Comment by engcom-November** [comment] 2022-04-22 07:57
Thanks for the update @antonfries ,
We are closing this issue as its fixed in 2.4-develop: https://github.com/magento/magento2/commit/d648bdc238ba6b59890694251655f725ad1b5d88. Kindly reopen this / create a new ticket if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-04-22 07:57 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
