### ISSUE TITLE
Previously installed with sample data, reinstall with clean database option without sample data option still installs sample data

### ISSUE THREAD

**Issue by skygunner** [magento/magento2#37366] opened 2023-04-13 06:36 UTC
### Preconditions and environment

- 2.4.6

### Steps to reproduce

1. Previously installed **with** sample data **--use-sample-data**
```shell
bin/magento setup:install \
--base-url=http://domain.com \
--db-host=localhost \
--db-name=m2_db \
--db-user=m2_user \
--db-password=password \
--use-rewrites=1 \
--use-secure=1 \
--base-url-secure=https://domain.com \
--use-secure-admin=1 \
--sales-order-increment-prefix="ORD$" \
--use-sample-data \
--document-root-is-pub=1 \
--cleanup-database
```

2. Reinstall **with clean database option**, but **without** sample data option like:
```shell
bin/magento setup:install \
--base-url=http://domain.com \
--db-host=localhost \
--db-name=m2_db \
--db-user=m2_user \
--db-password=password \
--use-rewrites=1 \
--use-secure=1 \
--base-url-secure=https://domain.com \
--use-secure-admin=1 \
--sales-order-increment-prefix="ORD$" \
--document-root-is-pub=1 \
--cleanup-database
```

### Expected result

should not install sample data if no 
--use-sample-data has been supplied

### Actual result

The program still installs sample data regardless of --use-sample-data present or not.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-04-14 02:44
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-05-02 05:56
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-05-11 18:11
Hi @skygunner ,

verified the issue in 2.4.6 instance and the issue is not reproducible.

 **Preconditions:**
Magento version 2.4.6
PHP 8.1
 
**Steps to reproduce:**
I.Install fresh Magento instance
2.Install sample data via Sample data deploy commnets as per Dev docs
https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/next-steps/sample-data/composer-packages.html?lang=en
3.Reinstall sample data with clean database without sample data option.
 
Kindly refer the below screenshots:
<img width="1511" alt="Screenshot 2023-05-09 at 9 18 36 AM" src="https://github.com/magento/magento2/assets/60198592/30e09545-d023-40d0-b58e-4a11a738c905">
<img width="1511" alt="Screenshot 2023-05-09 at 9 18 20 AM" src="https://github.com/magento/magento2/assets/60198592/9a391b8e-1afb-4678-ad48-73449c5e9dd0">

We are not able to install reinstall again with cleanup database without sample data option and we attached screenshot's of the error.kindly provide more information if the issue still reproducible.
 
Thanks

**Comment by engcom-Bravo** [comment] 2023-06-02 06:17
Hi @skygunner,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-06-02 06:17 UTC
Labels: Issue: needs update, Reported on 2.4.6
