### ISSUE TITLE
Price Indexer for configurable products does not work correctly when showing out of stock products

### ISSUE THREAD

**Issue by brosenberger** [magento/magento2#29540] opened 2020-08-14 09:57 UTC
# Description
The min/max Price of a configurable product is not correctly updated if the configurable has out of stock products and the option "Show out of stock products" is checked

# Manual testing scenarios 

* configure to show out of stock products (stores -> configuration -> catalog -> inventory -> display out of stock product)
* create a configurable product with 2 out of stock products and prices with 10 and 20
* go to the configurable product page

Result:
* see the price from 0 before selecting a simple product

Expected:
* see the price from 10 before selecting a simple product

# comments:

Code Refernece:
https://github.com/magento/magento2/blob/7198c763fd7552063e69f10e0f4c36c301e81a4d/app/code/Magento/ConfigurableProduct/Model/ResourceModel/Product/Indexer/Price/Configurable.php#L202

here it should be if (!$this->isConfigShowOutOfStock()) (only add restriction for IN_STOCK if *not* showing out of stock products)

**Comment by brosenberger** [comment] 2020-08-17 05:12
the same wrong check seems to be wrong in https://github.com/magento/magento2/blob/49309635a56774ce4d3f326a08a4e607020a2a6e/app/code/Magento/ConfigurableProduct/Model/ResourceModel/Product/StockStatusBaseSelectProcessor.php#L48

**Comment by engcom-Delta** [comment] 2020-08-17 12:25
Hi @brosenberger thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Manual testing scenario:**

- Create configurable product with Visual Swatch attribute:
![image](https://user-images.githubusercontent.com/51681379/90394107-b4230200-e09a-11ea-9682-e2b72d0c8458.png)
![image](https://user-images.githubusercontent.com/51681379/90394201-e5033700-e09a-11ea-844b-b7f3bcec4228.png)
![image](https://user-images.githubusercontent.com/51681379/90394211-eaf91800-e09a-11ea-8b74-7d943a0354c5.png)

- Set Out of Stock for configurable variations
![image](https://user-images.githubusercontent.com/51681379/90394559-8d190000-e09b-11ea-94f5-a96111ef18b2.png)
![image](https://user-images.githubusercontent.com/51681379/90394586-96a26800-e09b-11ea-8b8e-f65e0a462851.png)

- Go to configurable product page

**Result:**
:heavy_check_mark: No configurable options are shown
![image](https://user-images.githubusercontent.com/51681379/90394734-d9fcd680-e09b-11ea-9fc2-2a1ca3d1306f.png)

Same scenario for configurable product with dropdown attribute
![image](https://user-images.githubusercontent.com/51681379/90395458-43c9b000-e09d-11ea-832e-c362569ba575.png)
![image](https://user-images.githubusercontent.com/51681379/90395526-58a64380-e09d-11ea-8b78-8bd0a05e6907.png)
**Result:**
:heavy_check_mark: No configurable options are shown
![image](https://user-images.githubusercontent.com/51681379/90395577-68258c80-e09d-11ea-9790-883235a8ef48.png)


Could you add more details how you get price from 0 before selecting a simple product on configurable product page?

**Comment by brosenberger** [comment] 2020-08-17 12:29
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-08-17 12:29
Hi @brosenberger. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-08-17 12:30
Hi @brosenberger, here is your [Magento instance](https://i-29540-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29540-2-4-develop.instances.magento-community.engineering/admin_a07d](https://i-29540-2-4-develop.instances.magento-community.engineering/admin_a07d)
Login: `cfcf8b06` Password: `ef7f981e63ef`
Instance will be terminated in up to 3 hours.

**Comment by brosenberger** [comment] 2020-08-17 12:41
@engcom-Delta some behavior seems to be changed that not even the simple options are displayed (i experience that problem with a 2.2.x magento - but the underlying price indexer is still the same).

in my opinion when the option show out of stock products the simple options should be choosable (as the images might be different) and the price should additionally be shown for each simple (including the as low as price from the configurable)

**Comment by engcom-Delta** [comment] 2020-09-01 10:22
@brosenberger Seems like it is expected behavior for latest magento version - 2.4-develop
Feel free to create issue in [community-features](https://github.com/magento/community-features/issues) repo for further discussion
I'm closing this issue as **Cannot Reproduce** on 2.4-develop

If you'd like to update it, please reopen the issue.

**Closed as completed by engcom-Delta** 2020-09-01 10:22 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is not valid, Progress: ready for QA

**Comment by thai2301** [comment] 2021-02-02 19:25
still in Magento 2.4.1
