### ISSUE TITLE
Contact emails adresses: domain ".dog" not accepted

### ISSUE THREAD

**Issue by guystewart** [magento/magento2#7867] opened 2016-12-18 17:20 UTC
Email addresses with less well known domain names are not accepted, such as ".dog"

1.  Apache server
2. Magento 2 - version 2.1.3

### Steps to reproduce

1.  Login into Magento 2 - Admin Area 
2.  Go to Step: Stores > Configuration 
3.  General Tab > Store Email Addresses
4.  Enter an email address ending with the domain ".dog" (e.g. hello@unleashed.dog)

### Expected result

1.  Email address should be accepted, as ".dog" is a valid domain name now

### Actual result

1.  Error message: Please correct the email address: "hello@unleashed.dog".

**Comment by olysenko** [comment] 2016-12-27 13:05
Hi, thank for your report. Internal issue MAGETWO-62711 was created

**Comment by hostep** [comment] 2016-12-27 13:10
@olysenko: this is a duplicate of https://github.com/magento/magento2/issues/4547, you are already tracking this in MAGETWO-55432 ;)

**Comment by olysenko** [comment] 2016-12-27 16:40
Hi,  @hostep our internal issue  MAGETWO-55432 is closed but you can see the result (actually absence of the result)

**Comment by magento-engcom-team** [comment] 2017-10-02 13:15
Hi @guystewart 
We are going to close this ticket as it duplicates #4547.
Please track it for the solution. Thank you

**Closed as completed by magento-engcom-team** 2017-10-02 13:15 UTC
Labels: Issue: Ready for Work, bug report, Issue: Format is not valid
