### ISSUE TITLE
Bundle child product that is OOS still visible on front end

### ISSUE THREAD

**Issue by nbennett25** [magento/magento2#35413] opened 2022-05-03 17:08 UTC
With a fresh copy of 2.4.4, and installed sample data: if you mark one of the child products in a bundle as OOS, that item is still visible on the front end product page of the bundle.

### Preconditions (*)

1. Magento 2.4.4
2. Sample Data installed

### Steps to reproduce (*)

1. Go to product record for `24-WG081-blue` sku, mark qty to 0 and set to Out of Stock
2. Clear cache / reindex. 

### Expected result (*)

1. '24-WG081-blue' is no longer visible as a bundle option on the product page for Customize Sprite Yoga Companion Kit

### Actual result (*)

1. '24-WG081-blue' is visible as a bundle option on the product page for Customize Sprite Yoga Companion Kit

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by nbennett25** [comment] 2022-05-03 17:09
@magento give me 2.4.4 instance

**Comment by engcom-Hotel** [comment] 2022-05-05 08:28
@magento give me 2.4.4 instance

**Comment by engcom-Hotel** [comment] 2022-05-05 08:31
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-05-05 09:07
Hello @nbennett25,

We have tried to reproduce the issue in Magento 2.4-develop branch. But for us the issue is not reproducible, we have followed the below steps:
1. Initial PDP is look like below with the `Sprite Stasis Ball 55 cm` available:
![image](https://user-images.githubusercontent.com/51681618/166893231-28487000-1686-454a-a048-09f5f9df449d.png)

2. Edit `Sprite Stasis Ball 55 cm` with Quantity 0 and mark it as out of stock
3. After editing `Sprite Stasis Ball 55 cm` is not showing on the product detail page:
![image](https://user-images.githubusercontent.com/51681618/166893438-57813e69-82f6-4479-87c2-d3d82dad1e08.png)

Here functionality is working as expected. 

Thanks

**Comment by engcom-Hotel** [comment] 2022-05-20 07:27
Dear @nbennett25,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-05-20 07:27 UTC
Labels: Issue: needs update, Reported on 2.4.4
