### ISSUE TITLE
Magento\Framework\HTTP\PhpEnvironment\Request::getHeader() has incorrect return type in dockblock

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#21034] opened 2019-02-07 09:21 UTC
The docblock of method `Magento\Framework\HTTP\PhpEnvironment\Request::getHeader()` states that it will return a `bool` or an instance of `Zend\Http\Header\HeaderInterface()`. However, it returns either a `bool` or a `string`. 

This costed me some time debugging why my tests worked, but my live code didn't (since I had mocked the method in question and it returned a mocked `HeaderInterface` whereas the real code returned a `string`.

### Preconditions

1. Magento 2.3-develop

### Steps to reproduce

1. No real steps, it's an incorrect docblock

### Expected result

Either the method should return a `HeaderInterface` or the docblock should be changed (the latter is most probably the most friendly BC fix.

### Actual result

The return value does not match the docblock.

**Comment by magento-engcom-team** [comment] 2019-02-07 09:21
Hi @kanduvisla. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kanduvisla do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-02-07 09:25
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-02-07 09:29
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98137`, `MAGETWO-98138` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VZeroCool** [comment] 2019-02-07 09:36
@magento-engcom-team give me 2.3 instance

**Comment by VZeroCool** [comment] 2019-02-07 09:37
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-07 09:38
Hi @VZeroCool. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-07 09:38
Hi @VZeroCool, here is your [Magento instance](https://i-21034-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21034-2-3-develop.instances.magento-community.engineering/admin](https://i-21034-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-02-12 17:40
Hi @kanduvisla. Thank you for your report. 
The issue has been fixed in magento/magento2#21035 by @milindsingh in 2.3-develop branch
Related commit(s):
 - [e64dbcb257e9bc1c9f311c36eeeafed1253f51a6](https://github.com/magento/magento2/commit/e64dbcb257e9bc1c9f311c36eeeafed1253f51a6)
 - [666c63c1a37361d1bf58398e88ad85e8809c7b56](https://github.com/magento/magento2/commit/666c63c1a37361d1bf58398e88ad85e8809c7b56)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2019-02-12 17:40 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Progress: PR Created, Component: Framework/HTTP
