### ISSUE TITLE
the custom option Newest and  Oldest is not working in magento2.4.3p1

### ISSUE THREAD

**Issue by Japharul** [magento/magento2#35098] opened 2022-02-14 10:04 UTC
I have created a custom sorting in magento2.4.3p1 but the custom option newest and oldest is not working.

### Preconditions (*)

1. magento2.4.3p1 is the exact version .

### Steps to reproduce (*)

1. I have created a custom product sorting. Other option are working fine, like as naming ascending or descending but one option is not working, that is option newest and oldest.

### Expected result (*)

1. [Screenshots, logs or description]
2. product should be  showed as created at  

### Actual result (*)

1. [Screenshots, logs or description]
2. the issue is  "We can't find products matching the selection."

![Jackets - Tops - Men](https://user-images.githubusercontent.com/82087732/153842758-9b745114-4166-4752-8b23-7dd63596ae87.png)

in the log file the issue is showing:

[2022-02-14 09:58:52] main.CRITICAL: {"error":{"root_cause":[{"type":"query_shard_exception","reason":"No mapping found for [created_at.sort_created_at] in order to sort on","index_uuid":"4KfEq5CGSbi29eKeXUrxSw","index":"magento2_product_1_v75"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"magento2_product_1_v75","node":"z05ffY5HR6qD1n4WAjw1Kg","reason":{"type":"query_shard_exception","reason":"No mapping found for [created_at.sort_created_at] in order to sort on","index_uuid":"4KfEq5CGSbi29eKeXUrxSw","index":"magento2_product_1_v75"}}]},"status":400} {"exception":"[object] (Elasticsearch\\Common\\Exceptions\\BadRequest400Exception(code: 400): {\"error\":{\"root_cause\":[{\"type\":\"query_shard_exception\",\"reason\":\"No mapping found for [created_at.sort_created_at] in order to sort on\",\"index_uuid\":\"4KfEq5CGSbi29eKeXUrxSw\",\"index\":\"magento2_product_1_v75\"}],\"type\":\"search_phase_execution_exception\",\"reason\":\"all shards failed\",\"phase\":\"query\",\"grouped\":true,\"failed_shards\":[{\"shard\":0,\"index\":\"magento2_product_1_v75\",\"node\":\"z05ffY5HR6qD1n4WAjw1Kg\",\"reason\":{\"type\":\"query_shard_exception\",\"reason\":\"No mapping found for [created_at.sort_created_at] in order to sort on\",\"index_uuid\":\"4KfEq5CGSbi29eKeXUrxSw\",\"index\":\"magento2_product_1_v75\"}}]},\"status\":400} at C:\\xampp\\htdocs\\magento2\\vendor\\elasticsearch\\elasticsearch\\src\\Elasticsearch\\Connections\\Connection.php:675)"} []

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2022-02-18 13:41
Hi @Japharul ,
Thank you for reporting an issue , we tried to reproduce the issue on Magento 2.4 Develop with latest branch code  but we are able to reproduce the issue on front end.
<img width="1440" alt="Screenshot 2022-02-16 at 7 05 50 PM" src="https://user-images.githubusercontent.com/51681379/154693201-ee580daf-14a5-4756-8b7b-e6d0e09e89f2.png">

Unfortunately , we could not get the errors in the logs file ( System.log & debug.log).
Hence , request to review the steps provided once.

**Comment by tuey30716** [comment] 2022-02-24 09:52
I got same error but mind, if that catalog page have bundle product. the page stop render by that bundle product grid.
![121321](https://user-images.githubusercontent.com/27965693/155500763-4a4a0dd7-a4b6-45f2-9177-fa07ce2b1bef.PNG)

**Comment by engcom-Delta** [comment] 2022-03-01 10:07
@magento2.4 instance

**Comment by engcom-Delta** [comment] 2022-03-03 06:48
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment] 2022-03-04 01:03
https://github.com/magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment] 2022-03-04 01:09
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment] 2022-08-03 13:41
Hi @Japharul ,

Thanks for your contribution and collaboration.

I have tried to reproduce the issue but unable to reproduce it.
Please provide more information regarding creation of the newest and oldest custom sorting options.
Also, check in latest `2.4-develop` .

Thanks

**Comment by engcom-Lima** [comment] 2022-08-17 13:03
Hi @Japharul ,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Lima** 2022-08-17 13:03 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Area: Catalog
