### ISSUE TITLE
Package videlalvaro/php-amqplib is abandoned

### ISSUE THREAD

**Issue by 7ochem** [magento/magento2#4675] opened 2016-05-24 15:04 UTC
I have initiated a new composer project and added Magento2 (EE) as a dependency (version `~2.06`).

When running `$ composer install` I'm getting a warning: 

> Package videlalvaro/php-amqplib is abandoned, you should avoid using it. Use php-amqplib/php-amqplib instead.

With `$ composer depends videlalvaro/php-amqplib` I'm seeing which packages depend on this abandoned one:

> magento/magento2-ee-base            2.0.7    requires  videlalvaro/php-amqplib (2.5.*)
> magento/module-amqp                 100.0.5  requires  videlalvaro/php-amqplib (2.5.*)
> magento/product-enterprise-edition  2.0.7    requires  videlalvaro/php-amqplib (2.5.*)

Is this an issue? Shouldn't Magento2 use php-amqplib/php-amqplib instead as suggested?

_I suppose CE has the same issue, therefor reporting it here_

**Comment by mazhalai** [comment] 2016-05-24 15:09
@7ochem Please do not post EE issues on github. Please use partner portal. 

Also, this has already been fixed in 2.1.0-rc1. 

Closing, since not a bug.

**Closed as completed by mazhalai** 2016-05-24 15:09 UTC
