### ISSUE TITLE
TinyMCE WYSIWYG not working on Magento 2.3.1 admin

### ISSUE THREAD

**Issue by atulGupta2922** [magento/magento2#25929] opened 2019-12-06 08:58 UTC
### Preconditions (*)

1. Mangento 2.3.1

### Steps to reproduce (*)

1. Go to Admin > Content > Blocks
2. Click on Show /Hide Editor

### Expected result (*)

1. TinyMCE wysiwyg is loaded

### Actual result (*)

1. TinyMCE wysiwyg is not getting loaded and it still shows the default textarea with HTML code.

**Comment by atulGupta2922** [comment] 2019-12-06 08:59
Error on Console:
```
tinymce4Adapter.js:145 Uncaught TypeError: Cannot read property 'plugins' of undefined
    at g.addPluginToToolbar (tinymce4Adapter.js:145)
    at tinymce4Adapter.js:81
    at Array.forEach (<anonymous>)
    at g.setup (tinymce4Adapter.js:78)
    at g.turnOn (tinymce4Adapter.js:443)
    at g.toggle (tinymce4Adapter.js:488)
    at g.toggle (setup.js:56)
    at HTMLButtonElement.M (legacy-build.min.js:8)
```

**Comment by engcom-Echo** [comment] 2019-12-06 09:57
Hello @atulGupta2922 


Thank you for your report and collaboration!
We are not able to reproduce this issue on the 2.4-develop branch by provided steps.

**Testing scenario:**

**Steps to reproduce:**

1. Go to Admin > Content > Blocks
2. Click "Add New Block"
3. Click on Show /Hide Editor

**Result**
TinyMCE wysiwyg is loaded
![Peek 2019-12-06 11-50](https://user-images.githubusercontent.com/51681435/70314065-712c4180-181f-11ea-9f9c-47e45568bf7b.gif)
So I have to close this issue.
Thank you!

**Closed as completed by engcom-Echo** 2019-12-06 09:57 UTC
Labels: Issue: Format is valid

**Comment by atulGupta2922** [comment] 2019-12-06 10:03
I am facing this issue on Magento 2.3.1

**Comment by muralidharan-rade** [comment] 2020-09-11 07:12
@atulGupta2922 Were you successful in finding solution for this issue for version Magento 2.3.1?
We are facing the same.. Your inputs would be helpful..  Thanks.

**Comment by Sabrina-tahir** [comment] 2023-02-28 12:06
> @atulGupta2922 Were you successful in finding solution for this issue for version Magento 2.3.1? We are facing the same.. Your inputs would be helpful.. Thanks.

did u find the solution?

**Comment by antonioste** [comment] 2024-03-21 09:00
Hi,
someone have found a solution?
