### ISSUE TITLE
Unable Remove existing categories to existing product magento 2.4.2

### ISSUE THREAD

**Issue by Monica8955** [magento/magento2#33548] opened 2021-07-21 08:16 UTC
### Preconditions (*)
Magento 2.4.2 after migration Magento 2.3
Php 7.3

### Steps to reproduce (*)
1. edit a product and select/remove categories and save
2. the save product command reports success
3. not show error console and /catalog/product/save/id/1340/type/simple/store/0/set/4/back/edit return array with correct categories id

<img width="1584" alt="after_save_product" src="https://user-images.githubusercontent.com/57487715/126455028-6621383e-e9ed-4f1e-874c-74cf0d9bc3d5.png">

see video reproduce bug
https://drive.google.com/file/d/17wSC98fECsnplTuw1TdkI8HAELGrl1sU/view

### Expected result (*)
I expect to be able to remove categories on product page edit.

### Actual result (*)
Categories are not updated, but the save product command reports success.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Monica8955** [comment] 2021-07-22 08:45
Issue: Confirmed

**Comment by Monica8955** [comment] 2021-07-22 09:52
Add label Issue: Confirmed

**Comment by engcom-November** [comment] 2021-07-22 13:52
@Monica8955, this issue is not reproducible on Magento 2.4-develop clean instance.
Can you please provide specific Magento 2.3.x version (supporting php 7.3 version) that you have used to upgrade to 2.4.2 and reproduce the issue.
Thank you.

**Comment by Monica8955** [comment] 2021-07-23 07:53
@engcom-November 
specific Magento version is 2.3.2 (php PHP Version 7.3.29) 
Thank you.

**Comment by chernenm** [comment] 2021-07-23 22:31
@magento give me test instance

**Comment by chernenm** [comment] 2021-07-23 23:26
@magento give me 2.4-develop instance

**Comment by Monica8955** [comment] 2021-08-04 13:16
Hi,
news?

I can't access the attached screen

tnks


<img width="826" alt="Schermata 2021-08-04 alle 15 14 45" src="https://user-images.githubusercontent.com/57487715/128187378-9c0a0a1f-4bb6-41d9-b502-8c25021dbf8d.png">

**Comment by engcom-November** [comment] 2021-08-24 10:09
Verified the issue again after upgrading Magento 2.3.2 version to 2.4.2 version and cannot able to reproduce this issue:
**Steps performed:**
Installed 2.3 version using composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.3.2
Login to Admin - Catalog - Categories - Created multiple Root categories and Sub Categories
Admin - Catalog - Products - Added new Simple Product with few categories selected and Saved
Upgraded to Magento 2.4.2 version using: composer require magento/product-community-edition 2.4.2 --no-update
>composer update
>php bin/magento setup:upgrade 
php bin/magento setup:di:compile 
>php bin/magento setup:static-content:deploy -f
>php bin/magento indexer:reindex
>php bin/magento cache:flush
Login to Admin - Edit the Product - removed few categories and Save - No issue.
User is able to add/remove categories as expected.
@Monica8955 kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2021-09-07 08:44
Hi @Monica8955 ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-09-07 08:44 UTC
Labels: Issue: needs update, Reported on 2.4.2
