### ISSUE TITLE
File regeneration requests should not be fullfilled in Production mode

### ISSUE THREAD

**Issue by joeshelton-wagento** [magento/magento2#35035] opened 2022-01-29 18:42 UTC
### Summary (*)

When in Production mode, a regeneration request (caused by setting the `var/.regenerate` flag) puts Magento into a failed state.

The methods that create the .regenerate flag are titled "requestRegeneration()". But, Magento is not capable of actual regeneration when in Production mode. The regeneration request is essentially not fulfilled. Files are deleted, but *not* regenerated. The system is appropriate for other deploy modes where automated regeneration occurs, but not appropriate for Production mode.

Regeneration requests happen for many practical reasons, but sometimes also happen inadvertently. (Like when a new revision of a project is being built on the same server as an old version that is still in operation.) It is very unexpected for Magento to delete it's own code files and put itself in a broken state. This leads to a lengthy time spent troubleshooting. Magento does not detect that generated files are missing and handle the error gracefully. Instead it issues a random and confusing error when it first encounters a missing generated file in Production mode.

The whole system seems like an overreach of automation. Magento is not truly detecting when regeneration is necessary. Instead it is trying to detect when it *might* be necessary, and then puts itself into a failed state. It is a medicine worse than the disease.

Magento should not delete generated files when in Production mode.

### Examples (*)

1. Set Magento deploy mode to Production
2. On the command line: `touch var/.regenerate` - to simulate a regeneration request
3. Browse the site and observe that is in a failed state

### Proposed solution

I created a plugin which is not effective because the target is not instantiated using the Object Manager. Still it demonstrates my thinking. Simply check the deploy mode and don't proceed with cleaning files if in Production mode.

```
<?php

namespace Wagento\RegenerateFiles\Plugin;

use Magento\Framework\App\State;
use Magento\Framework\Code\GeneratedFiles;

class RegenerateFiles
{

    protected $_appState;

    public function __construct( State $appState )
    {
        $this->_appState = $appState;
    }

    /**
     * @param GeneratedFiles $subject
     * @param callable $proceed
     * @return void
     */
    public function aroundCleanGeneratedFiles(GeneratedFiles $subject, callable $proceed): void
    {
        if ($this->_appState != State::MODE_PRODUCTION) {
            $proceed();
        }
    }
}
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment] 2022-01-31 11:03
Hi @joeshelton-wagento ,

Thank you for reporting the issue.

However, we tried to reproduce it on Magento 2.4-develop but the issue is not reproducible.

Steps followed to reproduce issue:

1. Installed fresh Magento 2.4-develop instance
2. Set the mode to production using magento cli `bin/magento deploy:mode:set production`
3. Created a new file **.regenerate** in **var/** directory
4. Browsed the site and navigated through multiple pages

**Expected:** 
The site should be in failed state

**Actual:** 
The site is running perfectly fine. Also in **var/**  directory **.regenerate.lock** file is created once the site is hit from frontend and no errors are seen.

**Note:** Can you verify from your end that there is no permission issue for the newly created **.regenerate** file.

If the issue still persists at your end then please provide some more details or provide the exact steps, accordingly, I’ll try to reproduce it again.

Thanks!

**Comment by engcom-Hotel** [comment] 2022-02-16 14:16
Dear @joeshelton-wagento,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-02-16 14:16 UTC
Labels: Triage: Dev.Experience, Issue: needs update
