### ISSUE TITLE
Simple product save sets configurable Stock Status to Out Of Stock (MSI)

### ISSUE THREAD

**Issue by chesuch-smarte** [magento/magento2#30088] opened 2020-09-17 11:00 UTC
### Preconditions (*)
Magento ver. 2.3.3 (CE)
MSI - Multiple Inventory Sources setup, a default one and multiple others

### Summary (*)

All products currently have no stock within the Default stock source.
All products currently have all their stocks set only against a secondary stock source.

When viewing a simple product, we see 2 stock sources:
Default stock source which has 0 stock and a Source Item Status = Out Of Stock 
Secondary stock source which has positive stock and a Source Item Status = In Stock

When save the simple product in the admin, the parent configurable Stock Status is set to Out Of Stock.

Ideally we want to keep the default stock source, even though currently will have no stock, as at some point another site will be merged into the project that will use the default stock source.

### Proposed solution

All we can do at the moment is go back to the parent configurable and resave it with the Stock Status set back to "in Stock" so it continues to be visible on the website.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [*] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Oscar** [comment] 2020-10-01 12:43
Hello @chesuch-smarte 

Thank you for your report.
Unfortunately, I was not able to reproduce this issue on the latest `2.4-develop` code. Looks like we missed some steps or preconditions.

Could you please update the description?

**Comment by chesuch-smarte** [comment] 2020-10-01 13:06
<img width="1579" alt="Screenshot 2020-10-01 at 14 01 37" src="https://user-images.githubusercontent.com/45458626/94812460-adeca900-03ee-11eb-8e03-d0145abf4b6f.png">

ok, we're currently on Mage 2.3.3 CE, so perhaps this now does not occur on 2.4, I have not tried to upgrade tbh.

But as can be seen from the screenshot, not much to it really.
A configurable has child simple products, and they currently have 0 stock in the Default Source and only have stock within the secondary source (kuhn rikon global - tosca)

Default Source: 0
kuhn rikon global - tosca: 335

When editing the simple and saving, it sets the parent configurable to "Out of Stock"
which seems to be due to the fact that Default Source = 0

**Comment by jpkileaf** [comment] 2020-11-11 14:04
Any possible way to fix this issue in 2.3.5?

**Comment by engcom-Bravo** [comment] 2020-12-29 13:28
Hello @chesuch-smarte 

Unfortunately, we can not deliver a fix to previous releases. This issue is already fixed on the latest 2.4-develop.
So we have to close this issue. Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thank you

**Closed as completed by engcom-Bravo** 2020-12-29 13:28 UTC
Labels: Component: MSI, Issue: ready for confirmation, Reported on 2.3.3
