### ISSUE TITLE
Double slash

### ISSUE THREAD

**Issue by beckindesigns** [magento/magento2#2149] opened 2015-10-21 01:19 UTC
During the install there is a double slash for the store url. Example: http://yoursite.com//magento2/

**Comment by mazhalai** [comment] 2015-10-21 13:19
@beckindesigns was this using Web Setup Wizard or CLI?

**Comment by beckindesigns** [comment] 2015-10-21 13:53
@mazhalai sorry, that occurred during the Web Setup Wizard. Thanks!

**Comment by mazhalai** [comment] 2015-10-21 14:14
@beckindesigns we are unable to reproduce this. What is your environment and how did you deploy: git clone or composer create-project?

**Comment by beckindesigns** [comment] 2015-10-21 14:19
I used git clone to pull in the files. It's definitely there. Would you like me to do another installation and record my process?

**Comment by mazhalai** [comment] 2015-10-21 14:21
Yes, please mention what changes were made. For example, if default store address was changed etc.

**Comment by beckindesigns** [comment] 2015-10-21 14:23
No problem at all, I'll do that. I'll take a screen recording of the process for you. Thanks!

**Comment by beckindesigns** [comment] 2015-10-21 23:30
Here you go. https://vimeo.com/143163215 Excuse my southern Bama voice lol

**Comment by mazhalai** [comment] 2015-10-22 13:30
@beckindesigns thank you for the video! Can you please give more details about your environment? Also, if you are on `master` or `develop` branch

**Comment by beckindesigns** [comment] 2015-10-22 14:21
Hi @mazhalai I am running Apache, PHP-FPM, PHP Cache - Zend Cache, Percona Database Server & Memcache on a dedicated server. I am also pulling directly from Master. Let me know if that helps.

Thanks!

**Comment by daim2k5** [comment] 2015-11-04 21:49
Hi @beckindesigns thanks again for the great video. Can you try the `develop` branch?

**Comment by beckindesigns** [comment] 2015-11-04 22:01
Sure @daim2k5 I'll give it a shot and let you know how it goes.

**Comment by daim2k5** [comment] 2015-11-25 21:01
@beckindesigns any update on this? Or can we close this issue?

**Closed** 2015-12-05 17:02 UTC
Labels: needs update, PS

**Comment by jkristoffer** [comment] 2016-01-13 14:02
I'm facing the same issue as described here.

Im using develop branch `commit 3991d65ea5b4c91b39f130ceadac7e413233ada6`. I installed using the CLI with `--base-url={{base_url}}` and all the links have a double slash at the end of the base url.

I tried omitting `--base-url` completely and the double slashes disappeared. However i'm running magento2 in a docker container and the server rewrites the base url to `0.0.0.0`.
