### ISSUE TITLE
Session Handling Errors in PHP 7 using DB driver

### ISSUE THREAD

**Issue by anaxmedia** [magento/magento2#2827] opened 2015-12-28 17:25 UTC
Recently upgraded my M2 sample site to PHP 7 to do some performance benchmarking and I'm running into the following issue when trying to do anything session related (admin login, checkout, account functions, etc).

I use Redis backend for cache and Memcache for php session cache.

Getting the following error in Magento 2 on PHP 7.0.1:

 `session_regenerate_id(): Failed to create(read) session ID: user (path: aws-memcache-instance:11211) in /var/www/mysite.com/html/vendor/magento/framework/Session/SessionManager.php on line 473`

Same issue with CM Redis and another M2 extension:

https://github.com/Inchoo/Inchoo_PHP7/issues/4
https://github.com/colinmollenhour/Cm_RedisSession/issues/70

It appears to be an issue with the read function not always returning a string.

As a temporary fix I cast the return value for the read() function in the SessionHandler as a string.

**Comment by johnbendi** [comment] 2016-01-03 14:23
@anaxmedia Please can you show exactly how you did the casting?

**Comment by pmquan** [comment] 2016-01-07 07:26
I got a similar issue with my setup CentOS 7 + PHP 7.02. I did exactly as anaxmedia's fix.
Changed file vendor/magento/framework/Session/SaveHandler.php line 112
From: return $this->saveHandlerAdapter->read($sessionId); 
To: return (string)$this->saveHandlerAdapter->read($sessionId);

My system detailed information:
php-pecl-memcached-2.2.0
libmemcached-1.0.16
php-7.0.2
apache-itk

**Comment by shiftedreality** [comment] 2016-01-14 11:22
Hi @anaxmedia 

Please ,try to reproduce this bug in latest developer branch.
Looks like https://github.com/magento/magento2/issues/2454 should fix your case

**Comment by ostark** [comment] 2016-01-15 11:34
It looks like these patches tackle this session handler issue in PHP 7 core:
https://github.com/php/php-src/blob/PHP-7.0/NEWS#L46

**Comment by mazhalai** [comment] 2016-04-11 16:27
@anaxmedia any update on this issue?

**Comment by mazhalai** [comment] 2016-05-09 20:49
@anaxmedia closing due to responsiveness.

**Closed as completed by mazhalai** 2016-05-09 20:49 UTC
Labels: Progress: needs update
