### ISSUE TITLE
While we are creating Page Show / Hide Editor button is not working

### ISSUE THREAD

**Issue by BhautikAjmera007** [magento/magento2#6539] opened 2016-09-08 09:16 UTC

**Comment by andimov** [comment] 2016-09-08 09:32
@BhautikAjmera007 
Please use our issue reporting template to describe this issue. The template specifies the version and configuration information we need to assess your issue. See the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) for more information.

**Comment by andimov** [comment] 2016-09-27 09:39
@BhautikAjmera007 
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Closed as completed by andimov** 2016-09-27 09:39 UTC
Labels: Progress: needs update
