### ISSUE TITLE
Magento2 REST API: "created" cart is not empty

### ISSUE THREAD

**Issue by povesma** [magento/magento2#7042] opened 2016-10-16 19:25 UTC
### Preconditions

Magento 2.1.2 CE
### Steps to reproduce
1. POST /V1/carts/mine/ with {"customer_id": 10} , returns "76"
2.  PUT /V1/carts/mine/ with 
   {
   "customer_id":10,
   "quote": 
   {
       "id":76, <---- cart_id
       "items":[
           {
               "sku":"Toast MP3-3",
               "qty":1
           }
       ]
   }
   }
   OK, SKU added to the cart.
3.  now we need to have the cart empty as per docs 
   http://devdocs.magento.com/swagger/index.html#!/quoteCartManagementV1

_Implementation Notes

Creates an empty cart and quote for a specified customer._

**POST /V1/carts/mine/ with {"customer_id": 10}**
### Expected result

Empty cart is created (as per docs - "Creates an empty cart and quote for a specified customer.").
### Actual result

Last created cart ID returned - "76".

**Comment by SerhiyShkolyarenko** [comment] 2016-10-17 14:29
@povesma thank you for reporting the issue!
It seem to be a duplicate of #5913. According to internal logic that API call returns and **active** cart of the user when available. It creates a new cart when user doesn't have an active one. Documentation will be updated in scope of internal issue MAGETWO-58190. Closing the issue. Let's continue discussion in #5913.

**Closed as completed by SerhiyShkolyarenko** 2016-10-17 14:29 UTC
Labels: bug report, Component: Framework/Webapi
