### ISSUE TITLE
"Unique constraint violation found" when adding anything to cart on front end

### ISSUE THREAD

**Issue by shomanath6** [magento/magento2#37678] opened 2023-06-27 21:56 UTC
### Preconditions and environment

- Magento version: 2.4.5
 
Getting error banner "Unique constraint violation found" when adding anything to cart on front end. Item does not add to cart. 

### Steps to reproduce

spandexhouse.com

Add any item to cart

### Expected result

Should be able to add item to cart without error

### Actual result

not able to add to cart & receive error

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-06-28 06:38
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-06-28 06:53
Hi @shomanath6,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.


We are able to add the product to the cart without any issues and able to place the order.



https://github.com/magento/magento2/assets/51680745/0589f617-35ff-45f1-9dc7-a7ff86adad0e




Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-07-10 06:11
Hi @shomanath6,

Please provide us latest update on this https://github.com/magento/magento2/issues/37678#issuecomment-1610869883 if you are able to reproduce the issue provide us steps to reproduce the issue.Please let us know if you are facing any issue.

Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-07-17 06:20
Hi @shomanath6,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-07-17 06:20 UTC
Labels: Issue: needs update, Reported on 2.4.5
