### ISSUE TITLE
Changing product position in the category has no effect on the front-end

### ISSUE THREAD

**Issue by aleksinoleg** [magento/magento2#28149] opened 2020-05-08 06:30 UTC
### Preconditions (*)
1. Magento 2.4-develop
2 All indexes mode is "update by schedule"
![Capture 2020-05-08 at 9 25 50](https://user-images.githubusercontent.com/12597294/81377322-e9b86680-910d-11ea-8035-66807871cd48.png)

### Steps to reproduce (*)
1. Go to admin panel -> catalog -> inventory -> categories
2. Click on any category with the products and visible on the front-end
3. On the "Products in Category" tab change position of some product (do not delete or add any product from/to category)
4. click the "Save" button

### Expected result (*)

1. Product indexes are invalidated
2. After running cron jobs "indexer_reindex_all_invalid" and "indexer_update_all_views" product position on the category page is changed on the frontend.

### Actual result (*)

1. All indexes are still valid
2. The product position on the category page on the frontend is not changed.

### Additional information

Detailed steps and examples defined during confirmation: https://github.com/magento/magento2/issues/28149#issuecomment-629136334

**Comment by aleksinoleg** [comment] 2020-05-08 06:38
Here is the pull request to fix this issue
https://github.com/magento/magento2/pull/28150

**Comment by krishprakash** [comment] 2020-05-08 08:49
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-08 08:50
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-05-08 08:51
Hi @krishprakash, here is your [Magento instance](https://i-28149-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28149-2-4-develop.instances.magento-community.engineering/admin_e816](https://i-28149-2-4-develop.instances.magento-community.engineering/admin_e816)
Login: `8ba9069f` Password: `a843e740d26a`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Alfa** [comment] 2020-05-15 09:34
The issue is reproducible on a fresh 2.4-develop instance.

**Manual testing scenario:**

1. Create a category with a few simple products;
2. Set all indexes mode to "Update by Schedule" (Admin->System->Index Management);
![Screenshot from 2020-05-15 12-33-13](https://user-images.githubusercontent.com/51679138/82035557-56040e80-96a8-11ea-8724-5257ebfb63e8.png)
3. Go to Admin -> Catalog -> Inventory -> Categories;
4. Click on any category with the products and visible on the front-end;
5. On the "Products in Category" tab change position of some product (do not delete or add any product from/to category)
![screenshot_11](https://user-images.githubusercontent.com/51679138/82034507-f1947f80-96a6-11ea-860a-0c74219f2ddf.png)
6. Go to Storefront -> Category with products;

**Actual Result:**

:heavy_multiplication_x:  All indexes are still valid

![Screenshot from 2020-05-15 12-30-05](https://user-images.githubusercontent.com/51679138/82035187-dbd38a00-96a7-11ea-81aa-d089f0cf51dd.png)

:heavy_multiplication_x: The product position on the category page on the frontend is not changed.

![Screenshot from 2020-05-15 12-24-26](https://user-images.githubusercontent.com/51679138/82035219-e8f07900-96a7-11ea-8015-d1102b9214f0.png)

**Expected Result:**

1. Product indexes are invalidated;
2. After running cron jobs "indexer_reindex_all_invalid" and "indexer_update_all_views" product position on the category page is changed on the frontend.

**Comment by magento-engcom-team** [comment] 2020-05-15 09:36
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34357` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by slavvka** [comment] 2020-05-21 00:01
Hi @aleksinoleg. Thank you for your report. 
The issue has been fixed in magento/magento2#28150 by @aleksinoleg in 2.4-develop branch
Related commit(s):
 - [64dca9cf2a8698c01f3844ce3bbd09ec08c96679](https://github.com/magento/magento2/commit/64dca9cf2a8698c01f3844ce3bbd09ec08c96679)
 - [c7efd91d16c46de0657f01b51b9af4faaa806050](https://github.com/magento/magento2/commit/c7efd91d16c46de0657f01b51b9af4faaa806050)
 - [232ce853d894f94d0f00acb4688e30ce9ae417fd](https://github.com/magento/magento2/commit/232ce853d894f94d0f00acb4688e30ce9ae417fd)
 - [6b1b1a35af117b47c10872d9658f3d339c1f2c1e](https://github.com/magento/magento2/commit/6b1b1a35af117b47c10872d9658f3d339c1f2c1e)

The fix will be available with the upcoming 2.4.0 release.

**Closed as completed by slavvka** 2020-05-21 00:01 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Confirmed, Issue: Format is valid, Component: Indexer, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P3, Severity: S2, Triage: Done, Progress: done, Reported on 2.4.0
