### ISSUE TITLE
Date of Birth field in customer registration form gets obfuscated on registration failure

### ISSUE THREAD

**Issue by logicallimit** [magento/magento2#11721] opened 2017-10-25 12:32 UTC
The Date of Birth field in customer registration form shows comma separated numeric values on registration failure due to any reason whatsoever.

### Preconditions

1. Magento 2.2.0
2. MySQL 5.7.14
3. Apache 2.4.23
4. PHP 7.0.10
5. Wamp 3.0.6 (64bit) 

### Steps to reproduce
Issue 1:
1. Enter data in customer registration form and use an already registered email address to register again.
2. Now submit form.

### Expected result
1. A message is shown "There is already an account with this email address". This message is fine.

### Actual result
1. But if you see the date of birth field, the date which was entered earlier got disturbed and some random commas "," are added.

![registration-submission-after-error-dob-scattered](https://user-images.githubusercontent.com/7191368/31998653-3541caa4-b9ae-11e7-98fa-45f3ab3ceb7d.png)

**Comment by magento-engcom-team** [comment] 2017-10-25 15:09
Hi @logicallimit, thanks for a well-formed bug report!

It is a duplicate of [#7778](https://github.com/magento/magento2/issues/7778)

**Closed as completed** 2017-10-25 15:09 UTC
Labels: duplicate, Issue: Clear Description, Issue: Format is valid
