### ISSUE TITLE
When will there be stable PROD ready release?

### ISSUE THREAD

**Issue by jsakars** [magento/magento2#3404] opened 2016-02-15 12:00 UTC
Latest 2.0.2 version is still not PROD ready because:
1. https://github.com/magento/magento2/issues/3124 - custom payment method not working
2. https://github.com/magento/magento2/issues/2672 - custom cronjobs not working
3. ... and many more serious bugs
4. Lack of documentation(e.g. how to create custom payment/shipping method)

M2 is presented as latest stable release when M1 is archived. It seems like a dead-end at the moment. I would like to hear what M2 leads have to say about this situation.

**Comment by davidalger** [comment] 2016-02-15 16:52
@werdlv 2.0.2 is a production ready release and is being used in production by actual merchants by this point. That's not to say that there are no bugs remaining in the platform. To think there would be no bugs in an initial production release of a major re-architecture would be smoking a pipe dream. 

To speak to your specific points…
1. That's not bug, it's a question from someone not understanding how to create a custom module implementing a new payment method, and with no detail at that regarding what they tried to do. It belongs on the forums (as is now indicated on the issue page).
2. Yep. It's been acknowledged, and will hopefully be addressed soon. :)
3. Same as number 2, they're being worked on…
4. If there are specific things currently undocumented which you would like to see documented, I would open an issue requesting priority for documenting those topics at the magento/devdocs repo, not here. There is a lot of documentation work left to do, but the Magento team is doing a stellar job with the documentation efforts they are making and it's getting better by the day.

Fixing bugs is, I know, a big priority internally and that is evidenced by the fact that Magento has already shipped multiple dot releases to that end. Be patient a little, and these bug fix releases will keep on coming. If you're not satisfied with the current stability of the platform for production, then perhaps wait till 2.1 comes out later this year…it's not an official date, but my bet is on it being launched around Imagine, and by then there will have been many more months resolving the highest priority issues.

I'm going to close this issue since it is not in fact reporting anything new. If you have further discussion, please take it to the forums. However, if there are new bugs you find that have not already been reported, by all means go ahead and open a ticket with steps to reproduce so they _can_ be fixed! :)

**Closed as completed by davidalger** 2016-02-15 16:52 UTC
