### ISSUE TITLE
store cookie saved on wrong storeview subdomain by using language switcher

### ISSUE THREAD

**Issue by gtlt** [magento/magento2#22966] opened 2019-05-22 02:11 UTC
### Preconditions (*)

Magento CE 2.3.1
php : 7.2.18
nginx : 1.15.2
Full page cache : Built In

nginx config to simulate subdomains on localhost :
```
map $http_host $MAGE_RUN_CODE {
    www.test.localhost en;
    fr.test.localhost fr;
}

server {
   server_name www.test.localhost;
   location / {
        proxy_pass http://www.test.localhost:9090;
        proxy_set_header Host $host;
   }
}

server {
   server_name fr.test.localhost:80;
   location / {
        proxy_pass http://fr.test.localhost:9090;
        proxy_set_header Host $host;
   }
}
server {

    listen 9090;
    server_name $host;
...
```

### Steps to reproduce (*)

1. setup 1 website / 1 store / multi storeviews
2. setup each base url storeview on a subdomain
3. keep cookie path and cookie domain empty

English - code : en - base url : www.test.localhost
French - code : fr - base url : fr.test.localhost

run steps : 
1. check no _store_ cookies exist on any subdomain
2. open www.test.localhost
3. switch using language store switcher to _French_
4. check _store_ cookies on each subdomains
5. reuse language switcher to _English_

### Expected result (*)

1. _store_ cookie with value _fr_ and domain _fr.test.localhost_
2. reusing language switcher works and give correct content

### Actual result (*)

1. _store_ cookie with value _fr_ is stored on subdomain _www.test.localhost_
2. switch back doesn't work

![image](https://user-images.githubusercontent.com/17992895/58141455-c28a3000-7c43-11e9-891f-ea6db670a880.png)

**Comment by gtlt** [comment] 2019-05-22 02:13
give me @magento-engcom-team give me 2.3.1 instance

**Comment by magento-engcom-team** [comment] 2019-05-22 02:13
Hi @gtlt. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by magento-engcom-team** [comment] 2019-05-22 02:14
Hi @gtlt, here is your [Magento instance](https://i-22966-2-3-1.instances.magento-community.engineering).
Admin access: [https://i-22966-2-3-1.instances.magento-community.engineering/admin](https://i-22966-2-3-1.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by gtlt** [comment] 2019-05-22 19:59
(I forgotten that the issue is not testable on your magento instance)
I can workaround my issue by setting cookie domain in `Magento\Store\Model\StoreCookieManager`
```
public function setStoreCookie(StoreInterface $store)
    {
        $cookieMetadata = $this->cookieMetadataFactory->createPublicCookieMetadata()
            ->setHttpOnly(true)
            ->setDurationOneYear()
            ->setPath($store->getStorePath())
            ->setDomain($store->getCode() . '.test.localhost')
        ;
```
I don't know if it is a magento bug or a misconfig somewhere on my side (nginx ?). For now I will override StoreCookieManager Model...

**Comment by gtlt** [comment] 2019-05-22 20:16
When switching back to default store view the following message remains, it is also present when switching currencies sometimes.
 _The store that was requested wasn't found. Verify the store and try again._

**Comment by engcom-Charlie** [comment] 2019-08-13 08:55
Hello @gtlt 
I close this issue because its duplicate of #23755 issue. 
This issue describes the problem differently.
Thank for your report!

**Closed as completed by engcom-Charlie** 2019-08-13 08:55 UTC
Labels: Issue: Format is valid
