### ISSUE TITLE
Admin config section not expanded when fields are required.

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#26427] opened 2020-01-17 06:44 UTC
### Preconditions (*)

1. Magento 2.3.3 / 2.3.2 Open Source

### Steps to reproduce (*)

1. Create a new module that adds new system configuration
2. In this system configuration add 2 group of fields
3. For first group make all fields not required
4. For second group make at least 1 field required
5. Go to that section in admin panel 
6. Make sure both sections are *not* expanded (by default they should not be)
7. Try to save system config

### Expected result (*)

1. System should expand tab with required fields and scrolls to it / them

### Actual result (*)

1. Nothing happens, from customer  / UX point of view system hangs and there is no error message

**Comment by magento-engcom-team** [comment] 2020-01-21 19:58
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30623` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by qsolutions-pl** [comment] 2020-04-22 12:51
@sdzhepa  this is in progress for 28 days, any update?

**Comment by qsolutions-pl** [comment] 2020-05-06 10:44
@sdzhepa another 14 days have passed, how is progress on this task? @magento-engcom-team can I have any update on this?

**Comment by sdzhepa** [comment] 2020-05-07 03:18
Hello @qsolutions-pl 

I just set label `Dev In Progress` because 
> vikalps4 self-assigned this on Jan 27

But seems @vikalps4 is not working on it and I can unassign him
So, it is this issue is ready for development - feel free to propose PR with fix

**Comment by Bartlomiejsz** [comment] 2020-05-19 10:47
@magento I am working on this

**Comment by magento-engcom-team** [comment] 2020-07-21 10:45
Hi @qsolutions-pl. Thank you for your report. 
The issue has been fixed in magento/magento2#28285 by @Bartlomiejsz in 2.4-develop branch
Related commit(s):
 - [a7fa47b4a30dbb86c90d615474e566c5535c800d](https://github.com/magento/magento2/commit/a7fa47b4a30dbb86c90d615474e566c5535c800d)
 - [c842d73772943284f4633c3c14db1eade1b8c928](https://github.com/magento/magento2/commit/c842d73772943284f4633c3c14db1eade1b8c928)
 - [9d70a32057c91f89d994c24b8de83e44972c18b5](https://github.com/magento/magento2/commit/9d70a32057c91f89d994c24b8de83e44972c18b5)
 - [ac5ce560880c0ea1963a2a99294fab60317d5c65](https://github.com/magento/magento2/commit/ac5ce560880c0ea1963a2a99294fab60317d5c65)

The fix will be available with the upcoming 2.4.1 release.

**Closed as completed by magento-engcom-team** 2020-07-21 10:45 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Issue: Format is valid, Component: Backend, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P3, Severity: S3, Triage: Ready for Triage, Triage: Done, Progress: done, Reported on 2.3.2
