### ISSUE TITLE
Invoices, shipments and credit memos not filtered according to admin timezone

### ISSUE THREAD

**Issue by atIOCrON** [magento/magento2#34956] opened 2022-01-12 05:43 UTC
### Preconditions (*)

1. Magento v2.4.3-p1
2. PHP Version: 7.3.33

### Steps to reproduce (*)

1. Stores > Configuration > Locale Options: Timezone - set the timezone to your local timezone
2. Clear the cache
3. Sales > Invoices OR Sales > Shipments OR Sales > Credit Memos
4. Filter by date

### Expected result (*)

1. The results that are displayed match the admin timezone

### Actual result (*)

1. The results that are displayed are in UTC time

This same issue was patched for the Sales > Orders grid already:

https://support.magento.com/hc/en-us/articles/4403024155917-MDVA-34330-Orders-not-filtered-according-to-admin-timezone

However, the same issue still persists for invoices, shipments and credit memos.
---

Severity: **S1** - Affects critical data or functionality and forces users to employ a workaround

**Comment by engcom-Echo** [comment] 2022-01-12 14:43
Hi @atIOCrON,

Thank you for reporting the issue.

We have tried this issue on Magento 2.4-dev/2.4.3-P1 and we have successfully reproduced it.

Steps followed to reproduce issue:
1. Installed the clean Magento 2.4-dev/2.4.3-P1
2. Setup timezone to Magento Default, Created orders and invoices.
3. Updated timezone to (Australia/Sydney), created new order and invoice.
4. Filtered the invoices by using the invoice date and observed the result.
5. The invoice date filter is not filtering data as per the new time zone. (See the attached screenshots)

<img width="1428" alt="1 - Screenshot 2022-01-12 at 7 13 12 PM" src="https://user-images.githubusercontent.com/51681435/149161600-abe7b806-d72d-482d-a4df-f9b4838aa0e6.png">
<img width="1428" alt="2 - Screenshot 2022-01-12 at 7 13 48 PM" src="https://user-images.githubusercontent.com/51681435/149161611-b79e2d36-ad94-4168-9881-b1285f3cafd1.png">
<img width="1428" alt="3 - Screenshot 2022-01-12 at 7 14 11 PM" src="https://user-images.githubusercontent.com/51681435/149161624-4757fca6-f028-44d2-9362-984a1f78dabf.png">
<img width="1428" alt="4 - Screenshot 2022-01-12 at 7 23 26 PM" src="https://user-images.githubusercontent.com/51681435/149161640-3a34630a-6714-4eed-9928-dc719b1316da.png">
<img width="1428" alt="5 - Screenshot 2022-01-12 at 7 23 44 PM" src="https://user-images.githubusercontent.com/51681435/149161684-f7ef580e-1e02-4666-96af-69f6a6494c7f.png">

The invoice date filter on the Invoices page is not working as expected. Hence confirming the issue.

Thanks

**Comment by tuanpht** [comment] 2022-01-19 10:51
Related to https://github.com/magento/magento2/issues/30214

**Comment by tuanpht** [comment] 2022-01-19 12:00
> This same issue was patched for the Sales > Orders grid already:
>
> https://support.magento.com/hc/en-us/articles/4403024155917-MDVA-34330-Orders-not-filtered-according-to-admin-timezone

Related commit https://github.com/magento/magento2/commit/77e1e2beacbcd03da2fe612ccfdb6c0c23e00951

**Comment by atIOCrON** [comment] 2022-06-07 14:03
Is there any update on this issue? Is it going to be fixed?

**Comment by atIOCrON** [comment] 2022-09-18 00:48
Any update on this? When will it be fixed?

**Comment by atIOCrON** [comment] 2023-01-21 06:42
Hi @engcom-Echo ,
Is anyone working on a fix for this issue?

I can see it is tagged dev in progress but if no one is actually working on it can you remove that tag so someone else will see it and pick it up?

**Comment by atIOCrON** [comment] 2024-07-31 23:12
Hi @engcom-Echo 
Are you working on this issue? It's been 2 years, please remove yourself if you're not working on it.

**Comment by engcom-Bravo** [comment] 2024-09-09 08:39
@tuanpht Thanks for your contribution!!.

As per this comment https://github.com/magento/magento2/issues/34956#issuecomment-1016399330 we are closing this issue since issue has been fixed.

Thanks.

**Closed as completed by engcom-Bravo** 2024-09-09 08:39 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Analytics / Reporting
