### ISSUE TITLE
Checkout Page - Endless spinning of the loading icon on Invalid credit card

### ISSUE THREAD

**Issue by noprobz09** [magento/magento2#8292] opened 2017-01-26 09:48 UTC
**Preconditions**
Magento 2.1.2
PHP version 7.0.8
MySQL version 5.7.13

**Steps to reproduce**
Checkout page
Input sample credit card number: 4111111111111111
with expiry date Jan. 2017
with CV Number: 123

**Expected result**
It will return a message that the credit card number is invalid.

**Actual result**
The loading icon spin endlessly. It did not popup or notify error message.

Screenshots: 
https://www.screencast.com/t/w3UnQy94pO
https://www.screencast.com/t/h9b8EcIdh
https://www.screencast.com/t/8uBjjxEaBg

**Comment by YevSent** [comment] 2017-01-26 11:26
Hi, @noprobz09, thanks for reporting, this is known issue (internal ticket MAGETWO-56932) and already fixed on develop branch and in Magento 2.1.3 version.

If this issue is still reproducible on 2.1.3, please, be free to reopen it.

**Closed as completed by YevSent** 2017-01-26 11:26 UTC
Labels: Issue: Ready for Work, bug report, Component: Payment

**Comment by noprobz09** [comment] 2017-01-27 03:12
Hello @joni-jones,

Thanks for the quick response. The infinite loading icon is done but still not showing the error message. It supposed to show the "Please enter a valid credit card type number."  Also I have now the updated Magento 2.1.3 version.

**Comment by YevSent** [comment] 2017-01-27 08:05
@noprobz09, Magento shows only high-level errors if an error is provided on backend side, this behavior allows making the system more secure. If payment can process validation on frontend (like Braintree) the error will be shown.

**Comment by noprobz09** [comment] 2017-01-27 08:20
Hello there @joni-jones, So what is the good approached when 4111 1111 1111 1111 is invalid, I mean to remind the user that the entered visa number is invalid? currently, nothing show up. :)

**Comment by YevSent** [comment] 2017-01-27 08:32
For sandbox accounts, this card is valid even for different payments. Authorize.net returns errors to Magento callback controller, this controller doesn't recognize kind of errors, just log it and throw a high-level exception.

**Comment by noprobz09** [comment] 2017-01-31 10:20
Hi @joni-jones , I tried to input valid credit card number but with invalid cv and expiry date, and still no error showing up on the frontend to remind the customer that they input invalid data. I tried to switch in Magento Luma theme but still no luck :(

**Comment by amandeepsinghvirdi** [comment] 2017-03-02 01:39
@noprobz09 - not sure if you have already resolved the issue. But try to keep md5-hash value to just 10 characters. (it did solve the issue for me).

**Comment by d0brii** [comment] 2017-03-08 22:44
@amandeepsinghvirdi  It doesn't resolve issue since invalid MD5 would deemed, both valid and invalid transactions, to return error and possibly stuck. Which is not the case. 
Issues is only with invalid transactions in the live mode that after the error message returns from Aturize.net are stuck with endless spinning issue. 
  
In addition to that, there is no issues at all with sandbox credentials.
