### ISSUE TITLE
Quote api calls ignore config settings

### ISSUE THREAD

**Issue by roma84** [magento/magento2#8153] opened 2017-01-16 15:41 UTC
I use following calls to quote api to set product quantity: 
```
'guest': '/guest-carts/:cartId/items'
'customer': '/carts/mine/items'
```
Using those api calls quantity can be changed regardless of admin configurations.

### Preconditions
1. Magento 2.1.3 with sample data
2. Enable `Stores > Configuration > SALES > Sales > Minimum Order Amount`
3. Set `Maximum Qty Allowed in Shopping Cart`, `Minimum Qty Allowed in Shopping Cart` and `Qty Increments` in `Stores > Configuration > CATALOG > Inventory > Product Stock Options`

### Steps to reproduce
1. Make call to api setting item quantity: 
```
{
    cartItem: {
        item_id: itemId,
        qty: qty,
        quote_id: quoteId
    }
}
```

### Expected result
1. Error message if quantity change conflicts with one of described configurations.

### Actual result
1. Quantity is changed regardless of quantity and totals configurations.

**Comment by magento-engcom-team** [comment] 2017-10-12 11:30
@roma84, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-12 11:30 UTC
Labels: Component: Framework/Webapi, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
