### ISSUE TITLE
Back-office : cannot search customer by wildcard "*"

### ISSUE THREAD

**Issue by ghost** [magento/magento2#12099] opened 2017-11-08 10:37 UTC
In back-office, searching customers with keyword: * displays an error "Something went wrong"

### Preconditions
1. Magento 2.1.3 EE
2. PHP 7.0.16
3. Apache/2.4.10 (Debian)
4. Redis enabled
5. All Caches enabled

### Steps to reproduce
1. In the back-office, go to Customers > All Customers
2. In the search-bar, type the single character : * and press enter

### Expected result
1. Customers should be searched like with any other keyword

### Actual result
1. An error popup displays : "Attention Something went wrong", "Confirm"
2. Even after confirm, it's impossible to search with another keyword, page is stuck

### Workaround / how to unstuck after reproducing
In the database, run : 
```delete from ui_bookmark where user_id = <your_user_id> and namespace = 'customer_listing';```

### Cause of bug
We see this error on the Ajax request : 
```SQLSTATE[42000]: Syntax error or access violation: 1064 syntax error, unexpected $end, expecting FTS_TERM or FTS_NUMB or '*', query was: SELECT COUNT(*) FROM `customer_grid_flat` AS `main_table` WHERE (MATCH(`main_table`.name,`main_table`.email,`main_table`.created_in,`main_table`.taxvat,`main_table`.full_telephone,`main_table`.shipping_full,`main_table`.billing_full,`main_table`.billing_firstname,`main_table`.billing_lastname,`main_table`.billing_telephone,`main_table`.billing_postcode,`main_table`.billing_region,`main_table`.billing_city,`main_table`.billing_fax,`main_table`.billing_company) AGAINST('*'))```
This is due to a Mysql bug : https://bugs.mysql.com/bug.php?id=78485

### Possible solution
I think Magento should protect against this Mysql bug and avoir querying the database with keyword "*" and instead either : 
- search without any keyword (this is a wildcard symbol after all)
- or display an error message "Can't search with '*'" and clear filter

**Comment by magento-engcom-team** [comment] 2017-11-08 13:16
@quentinfarizon, thank you for your report.
We've created internal ticket(s) MAGETWO-83450 to track progress on the issue.

**Comment by aleksandrosadchiy** [comment] 2018-07-12 09:50
has a fix in https://github.com/magento/magento2/commit/01b546fe244246dbe033217918e4d0e6c294b2d2

**Comment by magento-engcom-team** [comment] 2019-06-20 20:34
Hi @quentinfarizon. 

Thank you for your report and collaboration!

The related internal Jira ticket `MAGETWO-83450` was closed as `non-reproducible` in `2.3.x`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Closed as completed by magento-engcom-team** 2019-06-20 20:34 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Issue:  Cannot Reproduce, Issue: Format is valid
