### ISSUE TITLE
Admin Catalog Product grid pagination and count don't update when filtering

### ISSUE THREAD

**Issue by batmike** [magento/magento2#32180] opened 2021-02-15 21:36 UTC
### Preconditions (*)
1. Magento version 2.4.2 (specifically tested on Cloud)
2. MariaDB 10.4
3. PHP 7.4

### Steps to reproduce (*)
1. Go to Admin panel, Catalog -> Products page
2. Have more than one page worth of products (i.e. products per page set to 20 and total products of 100)
3. Filter products by some filter - SKU, Name, etc.

### Expected result (*)
Filter products should show and product count and pagingation options should update according to the new, filtered product counts.

### Actual result (*)
Products are filtered, but total product count and pagination do not update. See attached screenshot - the SKU filter applied shows only one product in the catalog, but the product count and page counts are reflecting the entire catalog.

<img width="3191" alt="Screen Shot 2021-02-15 at 15 33 57" src="https://user-images.githubusercontent.com/6025821/107995025-79dfe200-6fa3-11eb-9013-b34b6f629783.png">

**Comment by michalbednarzcsm** [comment] 2021-02-22 20:34
Hi, I confirm the problem, the same for me.

I started debugging the problem and looking at the commits, I think the reason is here:

https://github.com/magento/magento2/commit/7a662f5ee991e5768c1dccb30bcaace3891c6f35

What I found is that when we restore the contents of the file `app/code/Magento/Catalog/Ui/DataProvider/Product/ProductCollection.php` from before commit, the filters on the grid behave correctly.

**Comment by michalbednarzcsm** [comment] 2021-02-23 10:48
I made a mistake in the previous message, problem is in the file I pointed out, but in other commit.

https://github.com/magento/magento2/commit/517f5a5055eef488daf6aeefd2829b2ee1013bcd

Method `getSize()` in `app/code/Magento/Catalog/Ui/DataProvider/Product/ProductCollection.php` can return wrong count of grid items.

Now I'm sure sorry for mistake.

**Comment by amcguireweb** [comment] 2021-03-03 20:29
Is there a fix for this? I can also confirm on 2.4.2.

**Comment by michalbednarzcsm** [comment] 2021-03-04 08:12
For me, the problem occurred after upgrade from version 2.3.3 to 2.4.2, so yes confirmed on 2.4.2.
My quick fix is to remove the methods that were added to the commit mentioned above.

**Comment by amcguireweb** [comment] 2021-04-06 11:54
It's not just the pagination and the counts. You also can't use the Search by Keyword search box. If you do, it just spins, and it sets a record in the ui_bookmark table requiring you to delete the record before the page will load again.

**Comment by julien-jourde** [comment] 2021-04-06 16:59
Hello,
The Issue still persist when you reload the filtered page despite of removing `getSize` method on `app/code/Magento/Catalog/Ui/DataProvider/Product/ProductCollection.php`.

**Comment by crispyz** [comment] 2021-04-23 07:18
For now, I think the only solution to get the previous behavior, is to write a preference for `Magento\Catalog\Ui\DataProvider\Product\ProductCollection` and override the `getSize()` method:
```
    /**
     * @return int
     */
    public function getSize()
    {
        return AbstractDb::getSize();
    }
```

**Comment by mrtuvn** [comment] 2021-05-05 00:01
Maybe we have regression bug here after some refactor

**Comment by batmike** [comment] 2021-05-05 16:24
Looks like there is a fix for this is the quality-patches release 1.0.21 under MDVA-36615
[https://devdocs.magento.com/quality-patches/release-notes.html]

The fix is the same as what @michalbednarzcsm suggested above and it's working for me in our various environments.

**Comment by mrtuvn** [comment] 2021-05-05 22:58
@batmike can you verify your issue in latest code 2.4-develop ?

**Comment by batmike** [comment] 2021-05-06 19:44
@mrtuvn - The latest 2.4-develop code does fix the issue. Thanks!

My comment from yesterday with the quality patch was tested again the 2.4.2 release code and that works also.

**Comment by engcom-November** [comment] 2021-06-30 12:27
Verified the issue on Magento 2.4-develop version and the product count and pagination issue is resolved now when there are more than 100 products in Admin -> Catalog -> Products page:
@batmike Can you please verify the issue on latest Magento version and confirm if this is still reproducible.
![image](https://user-images.githubusercontent.com/60198231/123960015-72f2c280-d9cc-11eb-89b5-31e70f71656f.png)
Thank you.

**Closed as completed** 2021-06-30 12:59 UTC
Labels: Component: Admin, Component: Filter, Fixed in 2.4.x, Issue: ready for confirmation, Reported on 2.4.2

**Comment by DevAwesomeK** [comment] 2021-07-09 12:22
Can anyone please add this patch as attachment file in this thread. Thanks!

**Comment by batmike** [comment] 2021-07-09 16:57
@DevAwesomeK - I have attached the patch file that corrected this issue for our site (in text format).

[MDVA-36615_2.4.2.txt](https://github.com/magento/magento2/files/6792873/MDVA-36615_2.4.2.txt)

**Comment by WinstonN** [comment] 2021-07-26 03:51
The bigger question for me is, how can these bugs be prevented? We deployed 2.4.2-p1 a week ago, and saw this bug too late. Now we need 1. another patch and deploy to fix 2. remove the patch with the next upgrade cycle 
Why does those 200 000 unit tests and MFTF not do what they are supposed to, and that is, catch and prevent simple bugs like this? Don't be mad, I'm only being real....

**Comment by mrtuvn** [comment] 2021-07-26 04:06
@batmike in latest code magento already removed code that you added in patch. Have you check in latest

**Comment by mrtuvn** [comment] 2021-07-26 04:17
actually that changes not cover by any tests. Internal core team fixed and merge code immediately to codebase
So we can't guarantee the changes not break any other function
You may not be supprise this because it happen everyday

**Comment by batmike** [comment] 2021-07-26 18:47
@mrtuvn - I have tested it on our site, running 2.4.2-p1 and the patch does still need to be applied for it to be working properly. I have not done any tests with the forthcoming 2.4.3 release but I'll reply when I'm able to see whether that works without the patch changes.

**Comment by mrtuvn** [comment] 2021-07-26 19:15
Better have label reproduced in 2.4.2
