### ISSUE TITLE
Error when uploading Image in Admin Page (Category and Page Content section)

### ISSUE THREAD

**Issue by quintinnel2** [magento/magento2#36424] opened 2022-11-06 11:38 UTC
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug
Magento Open Source 2.4.5-p1

### Steps to reproduce

Login in as Admin
Navigate to Catalog -> Categories
Select and category, navigate to the Content Section, and try adding a Media Image.
Upload Image from Local drive.

### Expected result

The image should be added to the content of the Category page. I receive the same issue when uploading an Image to a Page.

### Actual result

No Image is uploaded. Instead, I get the following error in the logs.
file-uploader.js:396 
        
       TypeError: Argument 2 passed to Magento\MediaGalleryIntegration\Plugin\SaveImageInformation::afterSave() must be of the type array, bool given, called in /var/www/html/magento_uwell/vendor/magento/framework/Interception/Interceptor.php on line 146 and defined in /var/www/html/magento_uwell/vendor/magento/module-media-gallery-integration/Plugin/SaveImageInformation.php:86
Stack trace:
#0 /var/www/html/magento_uwell/vendor/magento/framework/Interception/Interceptor.php(146): Magento\MediaGalleryIntegration\Plugin\SaveImageInformation->afterSave()
#1 /var/www/html/magento_uwell/vendor/magento/framework/Interception/Interceptor.php(153): Magento\RemoteStorage\Model\File\Uploader\Interceptor->Magento\Framework\Interception\{closure}()
#2 /var/www/html/magento_uwell/generated/code/Magento/RemoteStorage/Model/File/Uploader/Interceptor.php(23): Magento\RemoteStorage\Model\File\Uploader\Interceptor->___callPlugins()
#3 /var/www/html/magento_uwell/vendor/magento/module-page-builder/Controller/Adminhtml/ContentType/Image/Upload.php(119): Magento\RemoteStorage\Model\File\Uploader\Interceptor->save()
#4 /var/www/html/magento_uwell/vendor/magento/framework/Interception/Interceptor.php(58): Magento\PageBuilder\Controller\Adminhtml\ContentType\Image\Upload->execute()
#5 /var/www/html/magento_uwell/vendor/magento/framework/Interception/Interceptor.php(138): Magento\PageBuilder\Controller\Adminhtml\ContentType\Image\Upload\Interceptor->___callParent()
#6 /var/www/html/magento_uwell/vendor/magento/framework/Interception/Interceptor.php(153): Magento\PageBuilder\Controller\Adminhtml\ContentType\Image\Upload\Interceptor->Magento\Framework\Interception\{closure}()
#7 /var/www/html/magento_uwell/generated/code/Magento/PageBuilder/Controller/Adminhtml/ContentType/Image/Upload/Interceptor.php(23): Magento\PageBuilder\Controller\Adminhtml\ContentType\Image\Upload\Interceptor->___callPlugins()
#8 /var/www/html/magento_uwell/vendor/magento/framework/App/Action/Action.php(111): Magento\PageBuilder\Controller\Adminhtml\ContentType\Image\Upload\Interceptor->execute()
#9 /var/www/html/magento_uwell/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#10 /var/www/html/magento_uwell/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#11 /var/www/html/magento_uwell/vendor/magento/framework/Interception/Interceptor.php(138): Magento\PageBuilder\Controller\Adminhtml\ContentType\Image\Upload\Interceptor->___callParent()
#12 /var/www/html/magento_uwell/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\PageBuilder\Controller\Adminhtml\ContentType\Image\Upload\Interceptor->Magento\Framework\Interception\{closure}()
#13 /var/www/html/magento_uwell/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#14 /var/www/html/magento_uwell/app/code/Webkul/Marketplace/Plugin/App/Action/Context.php(54): Magento\PageBuilder\Controller\Adminhtml\ContentType\Image\Upload\Interceptor->Magento\Framework\Interception\{closure}()
#15 /var/www/html/magento_uwell/vendor/magento/framework/Interception/Interceptor.php(135): Webkul\Marketplace\Plugin\App\Action\Context->aroundDispatch()
#16 /var/www/html/magento_uwell/vendor/magento/framework/Interception/Interceptor.php(153): Magento\PageBuilder\Controller\Adminhtml\ContentType\Image\Upload\Interceptor->Magento\Framework\Interception\{closure}()
#17 /var/www/html/magento_uwell/generated/code/Magento/PageBuilder/Controller/Adminhtml/ContentType/Image/Upload/Interceptor.php(32): Magento\PageBuilder\Controller\Adminhtml\ContentType\Image\Upload\Interceptor->___callPlugins()
#18 /var/www/html/magento_uwell/vendor/magento/framework/App/FrontController.php(245): Magento\PageBuilder\Controller\Adminhtml\ContentType\Image\Upload\Interceptor->dispatch()
#19 /var/www/html/magento_uwell/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#20 /var/www/html/magento_uwell/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#21 /var/www/html/magento_uwell/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#22 /var/www/html/magento_uwell/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#23 /var/www/html/magento_uwell/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#24 /var/www/html/magento_uwell/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#25 /var/www/html/magento_uwell/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#26 /var/www/html/magento_uwell/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#27 /var/www/html/magento_uwell/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#28 /var/www/html/magento_uwell/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#29 {main}

### Additional information

I have not created any plugins for the uploaded.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-11-07 11:16
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-07 12:06
Hi @quintinnel2,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

We are able to add the image to the content of the Category page from Local Drive.


<img width="1410" alt="Screenshot 2022-11-07 at 4 53 01 PM" src="https://user-images.githubusercontent.com/51680745/200306227-8f8ff9e2-11dc-474b-8fad-f0d6044cd87d.png">



Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.



Thanks.

**Comment by engcom-Bravo** [comment] 2022-11-21 06:11
Hi @quintinnel2,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-11-21 06:11 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.5-p1

**Comment by vdideo** [comment] 2023-04-06 09:52
I had same error, I solved by giving 777 permissions to pub/media and pub/static folders
