### ISSUE TITLE
Boolean type product attribute filter is not working as expected

### ISSUE THREAD

**Issue by rani-priya** [magento/magento2#30740] opened 2020-11-01 06:45 UTC
### Preconditions (*)

1. Magento version 2.4
2. PHP version: 7.3

### Steps to reproduce (*)

1. Create a Boolean type attribute and make it Filterable (with results)
![image](https://user-images.githubusercontent.com/44425160/97796625-423e6b80-1c3a-11eb-9a5a-5174cb457652.png)
2. Assign this attribute to attribute set
3. Create bundle product and mark that Boolean type attribute to 1
4. Set this Boolean attribute to no for any one bundle child product
5. check the product graphql query

### Expected result (*)

1. It should not consider bundle child items attribute data.

### Actual result (*)

![image](https://user-images.githubusercontent.com/44425160/97796694-69e20380-1c3b-11eb-860b-352ec2d220ae.png)
![image](https://user-images.githubusercontent.com/44425160/97796710-854d0e80-1c3b-11eb-8b0b-de2a44d5a39f.png)
![image](https://user-images.githubusercontent.com/44425160/97796718-91d16700-1c3b-11eb-839a-56638c49bf93.png)

### Additional info from Engcom
Reproduced on 2.4-develop
Product attribute with _Catalog Input Type_ Yes/No
GraphQL query
```graphql
query {
  products(
    filter: { price: { from: "0", to: "999999" }, is_deal: { eq: "0" } }
    pageSize: 32
    currentPage: 1
  ) {
    items {
      name
      is_deal
    }
  }
}
```
![graph](https://user-images.githubusercontent.com/51680745/107020418-826a3880-67ab-11eb-8bae-dbd2572a51f7.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by rani-webkul** [comment] 2020-11-01 09:52
Even it is  not working for text type attribute as well
![image](https://user-images.githubusercontent.com/44425160/97798607-a585c900-1c4d-11eb-9b01-1fe2d0a318f0.png)

**Comment by rani-webkul** [comment] 2020-11-10 04:51
@magento give me 2.4-develop instance

**Comment by rani-webkul** [comment] 2020-12-18 04:57
@magento give me 2.4-develop instance

**Comment by rani-webkul** [comment] 2020-12-28 09:56
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2021-02-05 10:14
Hello @rani-webkul 

Thank you for your report.

We confirm that the issue is reproducible on the latest 2.4-develop. Additional info is added to the description.

**Comment by magento-engcom-team** [comment] 2021-02-05 10:16
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40778` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rani-webkul** [comment] 2021-02-12 05:26
@magento give me 2.4-develop instance

**Comment by rani-webkul** [comment] 2021-02-14 14:06
@magento give me 2.4-develop instance

**Comment by korovitskyi** [comment] 2021-02-24 14:27
@magento I am working on this

**Comment by korovitskyi** [comment] 2021-02-24 16:25
Hi, @rani-priya !
Looks like it is native behavior.
Bundle product as a parent is extending attribute values by their children.
If one of these children has another attribute value of the bundle (parent) product it affects the filter result.
CC: @engcom-Bravo, @engcom-Delta.

**Comment by rani-webkul** [comment] 2021-04-20 08:42
@magento give me 2.4.2 instance
@magento give me 2.4.0 instance

**Comment by rani-webkul** [comment] 2021-04-20 08:48
@magento give me 2.4.0 instance

**Closed as completed** 2022-10-17 08:09 UTC
Labels: Issue: Confirmed, Component: GraphQL, Reproduced on 2.4.x, Severity: S2, Priority: P1, Project: GraphQL, Progress: done, Reported on 2.4.x
