### ISSUE TITLE
Newly created ACL issues with existing roles

### ISSUE THREAD

**Issue by baatractive** [magento/magento2#35365] opened 2022-04-25 10:35 UTC
### Summary (*)
The newly created ACL does not have an entry in the `authorization_rule` table after running `setup:upgrade` so every user who have  permissions to **Backend_Admin** are able to see because the permissions are resolved to true as the parent ACL permission matches.

Should we need to save all existing roles so that newly created ACL permission applies? If yes, why it is not documented anywhere?

### Examples (*)
I've created a new module called `Test_Products`. Added a new controller inside `Controller/Adminhtml/Rename/Index.php` and overriden the `_isAllowed` method to only allow specific users who have the following permissions: `Test_Products::bulk_rename_products` but apparently every user who have `Magento_Backend::admin` are able to access it unless I save the ROLE permissions again which will add **DENY** entry in the `authorization_rule` for that particular role.

```
class Index extends Action
{
    public const REQUIRED_RULES = 'Test_Products::bulk_rename_products';

    private PageFactory $pageFactory;

    public function __construct(Context $context, PageFactory $pageFactory)
    {
        parent::__construct($context);
        $this->pageFactory = $pageFactory;
    }

    public function execute()
    {
        return $this->pageFactory->create();
    }

    protected function _isAllowed(): bool
    {
        return $this->_authorization->isAllowed(self::REQUIRED_RULES);
    }
}

/// ACL.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:Acl/etc/acl.xsd">
    <acl>
        <resources>
            <resource id="Magento_Backend::admin">
                <resource id="Test_Products::bulk_rename_products" title="Bulk rename products"
                          translate="title" sortOrder="114">
                </resource>
            </resource>
        </resources>
    </acl>
</config>

/// routes.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:App/etc/routes.xsd">
    <router id="admin">
        <route id="test_products" frontName="test_products">
            <module name="Test_Products"/>
        </route>
    </router>
</config>

///MENU.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Backend:etc/menu.xsd">
    <menu>
        <add id="Test_Products::products"
             title="Bulk Product Rename"
             module="Test_Products"
             sortOrder="40"
             action="test_products/rename"
             resource="Test_Products::bulk_rename_products"
             parent="Magento_Catalog::inventory"
        />
    </menu>
</config>


```

### Proposed solution
During `setup:upgrade` the magento should add `deny` for newly created ACL permissions in `authorization_rule` table for all roles except administrator/super admin.

Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment] 2022-07-22 11:26
Hi @baatractive,
Thank you for the collaboration and reporting the issue.

Tried reproducing the issue on 2.4-develop instance however the issue is not reproducible.

Steps followed to reproduce the issue:

1. Install latest 2.4-develop instance
2. Create a custom module [ref](https://devdocs.magento.com/videos/fundamentals/create-a-new-module/)
3. Create a new ACL [ref](https://developer.adobe.com/commerce/php/tutorials/backend/create-access-control-list-rule/)
4. Run setup:upgrade (New ACL is not added in table authorization_rule )
5. Try accessing the page with the user having permission **Magento_Backend::admin** and no entry in authorization_rule for custom ACL

Output:
Page is not accessible and proper error is thrown

**Screenshot:**
![image](https://user-images.githubusercontent.com/60198022/180429689-afe3ef6f-f4f5-4c89-967b-ac89e2639183.png)

Please let us know it there is additional step required, I will try it again
thanks

**Comment by engcom-Lima** [comment] 2022-08-05 06:20
Hi @baatractive ,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Lima** 2022-08-05 06:20 UTC
Labels: Triage: Dev.Experience, Issue: needs update

**Comment by renaudDan** [comment] 2022-08-16 18:51
@engcom-Lima Have you tried using \Magento\Framework\Authorization::isAllowed(), like in the issue example? It is always returning true when the ACL is not added to the "authorization_rule" table

**Comment by coding-daniel** [comment] 2023-04-18 12:08
I can also recreate the issue.

In `Zend_Acl::_getRules()` _(vendor/magento/zendframework1/library/Zend/Acl.php)_, it cannot find a rule for the newly created resource in line 1175 `$this->_rules['byResourceId'][$resourceId]` and because the `$create` flag is false by default, it returns null to `_roleDFSAllPrivileges()` which returns null to `isAllowed()` which finally falls back trying the parent permission in line 893.
