### ISSUE TITLE
Settings "catalog/search/search_recommendations_count_results_enabled" or "search_suggestion_count_results_enabled" don't affect visibility of result count in autocomplete

### ISSUE THREAD

**Issue by oskar-olaussen** [magento/magento2#32828] opened 2021-04-23 13:02 UTC
### Preconditions (*)

1. Magento 2.4.1.
2. Enable Search Suggestions set to true. 
3. Show Results Count for Each Suggestion and Show Results Count for Each Recommendation disabled.

### Steps to reproduce (*)

1. Go to front page
2. Start inputting a string in search box so that autocomplete suggestion will appear.

### Expected result (*)

1. Suggestions appear without results count.

### Actual result (*)

1. Suggestions appear with results count.

### Possible cause
In Magento\CatalogSearch\Model\Autocomplete\Dataprovider the method getItems returns 'num_results' regardless of settings
described before.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment] 2021-04-26 09:48
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42055` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by alinalexandru** [comment] 2021-10-07 15:30
Those 2 settings are related for 2 blocks `Magento\AdvancedSearch\Block\Suggestions` and `Magento\AdvancedSearch\Block\Recommendations` located in search result page.

The autocomplete feature can't be disabled or configured on a Magento2 default instance.

Autocomplete is part of `magento/module-search` module, and those settings are part of `magento/module-advanced-search`.
This ticket seems to be a feature request, not a bug.

**Comment by engcom-Bravo** [comment] 2024-07-29 09:08
Hi @oskar-olaussen,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.


<img width="1434" alt="Screenshot 2024-07-29 at 14 34 44" src="https://github.com/user-attachments/assets/237157c9-9831-4635-b75c-3d529e0ecd06">

<img width="1434" alt="Screenshot 2024-07-29 at 14 37 35" src="https://github.com/user-attachments/assets/f3b41fe4-8b7b-423c-b51f-89cdf2397d3b">



Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-29 09:08 UTC
Labels: Component: Search, Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Search
