### ISSUE TITLE
Problem in price-options.js. Extra price adds for all product on the page.

### ISSUE THREAD

**Issue by izmailov-labs** [magento/magento2#2755] opened 2015-12-18 09:00 UTC
When you fill options input prices changes for all products on the page.
See screanshot:

![erika running short 2015-12-18 10-40-52](https://cloud.githubusercontent.com/assets/972489/11892792/f9d2428c-a573-11e5-8061-329272eda821.png)

After fill option field

![erika running short 2015-12-18 10-41-37](https://cloud.githubusercontent.com/assets/972489/11892802/09ae94da-a574-11e5-8ef1-aa5f3f457832.png)

Problem in selector than does not have parent select like .product-view.
Or need rewrite widget that It use only component where it init.  
change price only in box with id product_addtocart_form
Exemple
{
            "#product_addtocart_form": {
                "configurable": {
                    "spConfig": <?php /\* @escapeNotVerified */ echo $block->getJsonConfig() ?>
                }
            }
        }

https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/view/base/web/js/price-options.js#L17

The same problem can be in all product types widget like
configurable.
grouped 
https://github.com/magento/magento2/blob/develop/app/code/Magento/ConfigurableProduct/view/frontend/web/js/configurable.js#L21

Now if you want to use this widget in page where is many products you get unexpected behavior
And you have to change widget options.
https://github.com/magento/magento2/blob/develop/app/code/Magento/ConfigurableProduct/view/frontend/templates/product/view/type/options/configurable.phtml#L34

**Comment by vzabaznov** [comment] 2016-06-22 14:09
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment] 2016-07-14 09:26
Hi, @kostya7777 thank you for contributing, i will close this issue for now as no update more than 14 days, if you think that issue is still reproducible, please fell free to open another one.

**Closed as completed by vzabaznov** 2016-07-14 09:26 UTC
Labels: bug report, Progress: needs update
