### ISSUE TITLE
Frontend 3rd level of submenu not accessible

### ISSUE THREAD

**Issue by stradd** [magento/magento2#28198] opened 2020-05-12 11:14 UTC
### Preconditions (*)
1. Magento 2.4-develop

### Steps to reproduce (*)
1. Install Magento 2.4-develop with sample data;
2. Go to Catalog - Categories;
3. Go to Women / Tops / Brass & Tanks;
4. Ad a new subcategory (_**Test**_ for example);
5. Save;
6. Go to Homepage;
7. Main Menu -> Woman >Tops  Brass & Tanks;

### Expected result (*)
The new submenu is next to Brass & Tanks
Example 2nd level:  [Image link](https://user-images.githubusercontent.com/15693687/82024545-3e209080-9690-11ea-8048-92035c58b48c.png)

### Actual result (*)
The new submenu is at the top and cannot be reached.
![Screenshot from 2020-05-18 15-29-21](https://user-images.githubusercontent.com/51679138/82213323-9c61a380-991c-11ea-9bcd-6ff05e1f8855.png)

### Additional Information
Example: https://github.com/magento/magento2/issues/28198#issuecomment-629092922

**Comment by ajijshekh123** [comment] 2020-05-13 07:04
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-13 07:04
Magento instance deployment temporary unavailable due to service maintenance.

**Comment by ajijshekh123** [comment] 2020-05-15 05:00
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-15 05:00
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-05-15 05:01
Hi @ajijshekh123, here is your [Magento instance](https://i-28198-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28198-2-4-develop.instances.magento-community.engineering/admin_4dab](https://i-28198-2-4-develop.instances.magento-community.engineering/admin_4dab)
Login: `48c96a0a` Password: `46247c1ed8bf`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2020-05-15 05:15
Hello @stradd,
This issue has been fixed in the latest Magento 2.4 instance. Please update your Magento version it will automatically fix the issue.

**See attached screenshot:**
![SubMenu_HoverIssue](https://user-images.githubusercontent.com/24711761/82013792-c9058900-9698-11ea-85e6-e2e87f164613.PNG)

This issue is the same as the below issue.
https://github.com/magento/magento2/issues/25589

Let me close this issue.

Thanks.

**Comment by stradd** [comment] 2020-05-15 07:46
I'm not sure it's the same issue. The category is displayed, but at the top and is inaccessible.
![sub2](https://user-images.githubusercontent.com/15693687/82024545-3e209080-9690-11ea-8048-92035c58b48c.png)
![Sub3](https://user-images.githubusercontent.com/15693687/82024562-42e54480-9690-11ea-939b-4ad4ec3537e0.png)
As can be seen in the picture, this is only the case with the third sub-level.

**Comment by ajijshekh123** [comment] 2020-05-15 08:01
Right, @stradd,
I can't able to access the 3rd level category.
See attached the video:

![MenuHoverIssue](https://user-images.githubusercontent.com/24711761/82026438-5ef8de00-96b0-11ea-84e9-49161e01e7ec.gif)

Thanks.

**Comment by magento-engcom-team** [comment] 2020-05-15 08:03
@ajijshekh123 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by kishorenagalingam** [comment] 2020-05-18 11:47
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-18 11:47
Hi @kishorenagalingam. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-05-18 11:48
Hi @kishorenagalingam, here is your [Magento instance](https://i-28198-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28198-2-4-develop.instances.magento-community.engineering/admin_d73d](https://i-28198-2-4-develop.instances.magento-community.engineering/admin_d73d)
Login: `c20242ab` Password: `7311c2133d4c`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Alfa** [comment] 2020-05-18 12:29
The issue is reproducible on fresh 2.4-develop

**Actual Result:**
![Screenshot from 2020-05-18 15-29-21](https://user-images.githubusercontent.com/51679138/82213156-60c6d980-991c-11ea-893e-0e41ded1d71e.png)

**Comment by magento-engcom-team** [comment] 2020-05-18 12:32
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34375` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by kishorenagalingam** [comment] 2020-05-18 13:06
@magento I am working on this

**Comment by david-ziffity** [comment] 2020-05-20 06:02
@magento give me test instance

**Comment by magento-engcom-team** [comment] 2020-06-12 17:50
Hi @stradd. Thank you for your report. 
The issue has been fixed in magento/magento2#28260 by @kishorenagalingam in 2.4-develop branch
Related commit(s):
 - [a06e9c04f6abf257863d7abe115b567f3fd2a035](https://github.com/magento/magento2/commit/a06e9c04f6abf257863d7abe115b567f3fd2a035)
 - [d0bcebae8741211afbefabef597ce6d4b556d8c5](https://github.com/magento/magento2/commit/d0bcebae8741211afbefabef597ce6d4b556d8c5)
 - [4d4e07fb1a858569a3bd7de8cf448369d6444254](https://github.com/magento/magento2/commit/4d4e07fb1a858569a3bd7de8cf448369d6444254)
 - [b2af00b26c9ae67611f8081404cea85b86c7584c](https://github.com/magento/magento2/commit/b2af00b26c9ae67611f8081404cea85b86c7584c)
 - [1abb42315d606199c68ce69743c2e6289ba522fe](https://github.com/magento/magento2/commit/1abb42315d606199c68ce69743c2e6289ba522fe)
 - [c1b71d93911c39ad365efe25d9116c8311ecd77d](https://github.com/magento/magento2/commit/c1b71d93911c39ad365efe25d9116c8311ecd77d)
 - [84bfc0bfd309e4bda64bbf4baea66b37fe98e000](https://github.com/magento/magento2/commit/84bfc0bfd309e4bda64bbf4baea66b37fe98e000)

The fix will be available with the upcoming 2.4.1 release.

**Closed as completed by magento-engcom-team** 2020-06-12 17:50 UTC
Labels: Issue: Ready for Work, Component: Catalog, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P3, Severity: S2, Triage: Done, Progress: done, Reported on 2.4.0
