### ISSUE TITLE
Order/ Invoice/ Shipment emails are not being received by customer if First Name and Last Name of customer name is in Arabic.

### ISSUE THREAD

**Issue by sudheer-gajjala** [magento/magento2#32601] opened 2021-03-25 15:34 UTC
### Preconditions (*)

1. Users should be able to enter First / Last Name in Arabic Language.

### Steps to reproduce (*)

1. Enter the url
2. Go to PLP ->Select and item
3. Add an item to cart
4. click on view and edit ->proceed to checkout
5. Enter guest user mandatory fields -> click on next
6. Place an order with CC/COD
7. Order success page with Order id and view order shall be displayed.

### Expected result (*)

1. Order confirmation/Invoice/Shipment and all emails should be received by customer.

### Actual result (*)

1. Order/ Invoice/ Shipment emails are not  being received by customer

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Oscar** [comment] 2021-03-26 08:27
Hi @sudheer-gajjala  ! Thank you for your report.
Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop by following steps from this ticket.

**Actual Result:** :heavy_check_mark: 
![Screenshot from 2021-03-26 10-26-16](https://user-images.githubusercontent.com/60198413/112603556-d85b7400-8e1d-11eb-9040-3180b1269ad0.png)

So, we have to close this ticket.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch.
 Thank you for collaboration.

**Closed as completed by engcom-Oscar** 2021-03-26 08:27 UTC
Labels: Issue: ready for confirmation, not-confirmed
