### ISSUE TITLE
is_anchor is not working on store level if the categories are disabled on global level

### ISSUE THREAD

**Issue by amenk** [magento/magento2#33398] opened 2021-07-01 13:56 UTC
### Preconditions (*)
1. Magento 2.4-develop (seen originally on 2.3.4-p2)
2. Multi store setup

### Steps to reproduce (*)
1. Create category "Parent" in Admin store, deactivate it, is anchor = true
2. Create category "Parent -> Child" In Admins store as a child, deactivate it, is anchor = true
3. Now assign a product to The Child category
4. Go to a store view, enable the Parent and the Child Categories on store level
5. Check in the frontend: "Parent"

### Expected result (*)

1. "Parent" should show the Product on the frontend which is assigned to the child, because both a anchor categories.

### Actual result (*)
1. Parent category is empty

### Workaround
1. Enable both categories on the main store (0) as well, then the is anchor functionality works

Problem might be somewhere here: 
* Problem is the products do not get added to the catalog_category_product_index_storeX table
* https://github.com/magento/magento2/blob/52d92dbd07f09620d23693ba0c4d4bdb4ba09916/app/code/Magento/Catalog/Model/Indexer/Category/Product/AbstractAction.php#L669

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by amenk** [comment] 2021-07-01 13:56
@magento give me 2.4-develop instance

**Comment by amenk** [comment] 2021-07-01 14:22
![ksnip_tmp_pvSBhD](https://user-images.githubusercontent.com/1087128/124140062-78154780-da88-11eb-867c-7cb5aeb164d8.png)
![ksnip_tmp_gvlRpR](https://user-images.githubusercontent.com/1087128/124140072-79df0b00-da88-11eb-89a8-88212cdb70ff.png)
![ksnip_tmp_JXoLEQ](https://user-images.githubusercontent.com/1087128/124140084-7c416500-da88-11eb-96f0-0c543ea09478.png)
![ksnip_tmp_RbDkPx](https://user-images.githubusercontent.com/1087128/124140092-7e0b2880-da88-11eb-9668-9ab16dea5ec1.png)
![ksnip_tmp_hBHLpQ](https://user-images.githubusercontent.com/1087128/124140111-7fd4ec00-da88-11eb-9a74-9bf89b35b64e.png)
![ksnip_tmp_TkTdla](https://user-images.githubusercontent.com/1087128/124140124-82374600-da88-11eb-8be0-f7be9c66ec99.png)

**Comment by magento-engcom-team** [comment] 2021-07-02 04:38
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42778` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by amenk** [comment] 2021-07-02 05:40
Thanks for confirming. Isn't that technically a Severity: S1 ? It affects critcial data (showing products in the catalog seems critical for a shop), while there is a workaround.

**Comment by SilinMykola** [comment] 2021-07-20 05:29
@magento I am working on this

**Comment by ioweb-gr** [comment] 2023-07-15 07:19
I'm also facing this one. Unfortunately the problem isn't only that the default store view is disabled. If it is disabled in any store view I get the same error. Is anchor is ignored and I end up with 0 products. 

Saving the category seems to temporarily fix the issue, but then suddenly products disappear again. 

It seems to affect when the indexers are in scheduled mode as well.

**Comment by SilinMykola** [comment] 2023-07-18 09:16
@ioweb-gr hello! Did you try my PR? Did it help you? Thanks!

**Comment by ioweb-gr** [comment] 2023-07-18 09:19
Yeah I tried it but it made no difference.

**Comment by engcom-Bravo** [comment] 2024-06-18 04:32
Hi @amenk,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.kindly refer the screenshots.


**Steps to reproduce**

- Create category "Parent" in Admin store, deactivate it, is anchor = true
- Create category "Parent -> Child" In Admins store as a child, deactivate it, is anchor = true
- Now assign a product to The Child category
- Go to a store view, enable the Parent and the Child Categories on store level
- Check in the frontend: "Parent"



<img width="1061" alt="Screenshot 2024-06-18 at 09 58 04" src="https://github.com/magento/magento2/assets/51680745/1de1a314-fbd7-43e6-8b9f-7121c8ae1319">



<img width="1061" alt="Screenshot 2024-06-18 at 09 58 10" src="https://github.com/magento/magento2/assets/51680745/5a8a77da-bae8-4955-aa61-3a474a90551c">



<img width="1061" alt="Screenshot 2024-06-18 at 09 58 22" src="https://github.com/magento/magento2/assets/51680745/32b0137c-b2f4-4d1c-a6b8-099d334ae43a">



<img width="1061" alt="Screenshot 2024-06-18 at 09 58 26" src="https://github.com/magento/magento2/assets/51680745/53a7e1c6-33bb-4cc5-ae4b-d118ecd92af0">



<img width="1061" alt="Screenshot 2024-06-18 at 09 57 56" src="https://github.com/magento/magento2/assets/51680745/4427d183-c5b5-40bf-a06b-3e2010a1d4ad">



"Parent" showing the Products on the frontend which is assigned to the child


Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-18 04:32 UTC
Labels: Component: Catalog, Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Severity: S2, Progress: done, Issue: ready for confirmation, Area: Catalog
