### ISSUE TITLE
[M2.4.4] Admin broken views and grids

### ISSUE THREAD

**Issue by Stoyvo** [magento/magento2#35590] opened 2022-06-07 21:12 UTC
### Preconditions and environment

- Magento 2.4.4
- PHP 8.1

### Steps to reproduce

1. Upgrade from clean Magento 2.4.3 to 2.4.4

2. Login to Admin, look at a grid.

### Expected result

One default view, one link to save view, functional column selector

### Actual result

![image](https://user-images.githubusercontent.com/6148099/172483383-e8ca95f5-9cff-4744-8fa1-e0e233213303.png)
![image](https://user-images.githubusercontent.com/6148099/172483527-2b99b78f-1fe2-4ac9-8d7e-48e26c010164.png)

Screen shots of Product, but issue visible on all admin grids

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-06-08 11:19
Hi @Stoyvo ,
Thank you for reporting and collaboration. Verified the issue by upgrading from 2.4.3 to 2.4.4 but could not able to reproduce the issue.
**Steps performed:**
1. Installed Magento 2.4.3 Project Community edition with PHP 7.4 version
2. Upgraded to 2.4.4. Ref [Guide](https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/implementation/perform-upgrade.html)
3. Upgraded PHP Version to 8.1 as it the compatible/ supported version for Magento 2.4.4
4. Login to Magento Admin - No issue with Product Grid etc.

![image](https://user-images.githubusercontent.com/60198231/172603920-e0ff2941-e4bd-4b09-b177-dca0b3cc47f3.png)

Kindly check the Magento [system requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) and also if any third party extensions/Modules enabled is causing the issue. Please provide missing configuration details if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-06-22 11:01
Hi @Stoyvo ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-06-22 11:01 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update

**Comment by Stoyvo** [comment] 2022-08-13 18:56
For those who run into this issue, this was the root cause and is fixed (not released). Manually pull a patch and apply to correct your instance.
https://github.com/magento/magento2/issues/35325
