### ISSUE TITLE
Magento 2.2.4 : Image Assign Issues when Create Product Using REST API

### ISSUE THREAD

**Issue by ghost** [magento/magento2#15056] opened 2018-05-08 10:10 UTC
### Preconditions

1. Magento CE 2.2.4, Apache : 2.4.23, PHP : 7.1.16

### Steps to reproduce

1. Setup REST API User and Create Role with all resource.
2.  Call REST API using REST Client in Chrome Browser.
3.  Here is product JSON.
`{
  "product": {
  "attribute_set_id": 4,
  "type_id": "simple",
  "sku": "B201-SKU",
  "name": "B201",
  "price": 25,
  "status": 1,
  "custom_attributes": {
    "description": "Heavy Duty Brake Cables",
    "meta_description": "Some describing text",
    "image" : "error.png",
    "small_image": "error.png",
    "thumbnail": "error.png"
   }
  }
 }`
4. Image already imported under pub/media/catalog/product directory.
5. Executed Upgrade, Indexer, Cache.

### Expected result
1. Product Should be created with given information and image should assign to it. 

### Actual result
1. Product Created but image assigned to only grid not at front end and back end. (Open Product using edit option at grid).
2. Image is there in grid, Also Displayed in Popup when clicked.
3. Not Found in when open product at back end as well Front end. 

![screenshot-2018-5-8 products inventory catalog magento admin](https://user-images.githubusercontent.com/39085366/39751364-93db0150-52d5-11e8-939d-2b737bd235bb.png)

![screenshot-127 0 0 1-2018 05 08-15-39-29](https://user-images.githubusercontent.com/39085366/39751538-23285466-52d6-11e8-927a-65b91d1c5185.png)

**Comment by engcom-backlog-nickolas** [comment] 2018-07-17 08:44
Hello @TBSMage, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by engcom-Charlie** [comment] 2019-09-24 10:19
Hello @ghost

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by engcom-Charlie** 2019-09-24 10:19 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid
