### ISSUE TITLE
Compilation error. 2.4.2.-p1 Clean installation / no extensions installed . 

### ISSUE THREAD

**Issue by dtavieres** [magento/magento2#33603] opened 2021-07-27 11:03 UTC
### Preconditions (*)

1.Magento 2.4.2-p1 
2.Oracle Linux 8.4 PHP 7.4 Apache 2.4 MYSQL 8. ES7

(**) Some outcome in other installations running MG 2.4.2-p1 after running composer update  ***today*** 
without update no issue shows up.  
For isolating the problem, we performed a clean installation with the same outcome. 

### Steps to reproduce (*)

1. Just installed 2.4.2-p1 via composer, setup:install,  running se:up and se:di:c and we got compilation error.  
2. https://prnt.sc/1gjybrr

### Expected result (*)

1 Generated code and dependency injection configuration successfully.
2.

### Actual result (*)

1.https://prnt.sc/1gjybrr
2.magento2@stage5  /var/www/magento2/html  magento se:di:c -vv
Compilation was started.
Interception cache generation... 6/9 [==================>---------] 66% 25 secs 346.0 MiBErrors during compilation:
Magento\Framework\Setup\Option\AbstractConfigOption
Incompatible argument type: Required type: int. Actual type: string; File:
/var/www/magento2/html/vendor/magento/framework/Setup/Option/AbstractConfigOption.php
Total Errors Count: 1
In Log.php line 92:
[Magento\Framework\Validator\Exception]
Error during compilation
Exception trace:
at /var/www/magento2/html/setup/src/Magento/Setup/Module/Di/Compiler/Log/Log.php:92
Magento\Setup\Module\Di\Compiler\Log\Log->report() at /var/www/magento2/html/setup/src/Magento/Setup/Module/Di/Code/Reader/Decorator/Interceptions.php:85
Magento\Setup\Module\Di\Code\Reader\Decorator\Interceptions->getList() at /var/www/magento2/html/setup/src/Magento/Setup/Module/Di/App/Task/Operation/InterceptionCache.php:59
Magento\Setup\Module\Di\App\Task\Operation\InterceptionCache->doOperation() at /var/www/magento2/html/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php:56
Magento\Setup\Module\Di\App\Task\Manager->process() at /var/www/magento2/html/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php:216
Magento\Setup\Console\Command\DiCompileCommand->execute() at /var/www/magento2/html/vendor/symfony/console/Command/Command.php:255
Symfony\Component\Console\Command\Command->run() at /var/www/magento2/html/vendor/symfony/console/Application.php:1009
Symfony\Component\Console\Application->doRunCommand() at /var/www/magento2/html/vendor/symfony/console/Application.php:273
Symfony\Component\Console\Application->doRun() at /var/www/magento2/html/vendor/magento/framework/Console/Cli.php:115
Magento\Framework\Console\Cli->doRun() at /var/www/magento2/html/vendor/symfony/console/Application.php:149
Symfony\Component\Console\Application->run() at /var/www/magento2/html/bin/magento:2
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

It's a blocking issue. No possible compilation.  

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ethmelly** [comment] 2021-07-27 11:25
Confirm , facing same issue on all websites we tried to deploy starting today

**Comment by sebastian-ehrling** [comment] 2021-07-27 12:12
composer2 require "symfony/console:4.4.26" solves the problem temporarily

**Comment by plel** [comment] 2021-07-27 12:54
Same applies for 2.3.7 installation.
Problem is in the detection of Parameters with doc-block and static position. Symfony/console removed the `$name` parameter from the doc-block which leads to the assumption that the `$mode` parameter is the one to compare to.
src/vendor/laminas/laminas-code/src/Reflection/ParameterReflection.php:109

From there it goes just wrong ending up in the `isCompatibleType` function of the `ArgumentsReader`

**Comment by mrtuvn** [comment] 2021-07-27 13:55
![Screenshot from 2021-07-27 20-54-44](https://user-images.githubusercontent.com/1908873/127166380-6556ce87-be87-457c-8831-a79e76149add.png)
Got same issue with update composer approach. For test only purpose in local
Latest 2.4-develop

**Comment by mrtuvn** [comment] 2021-07-27 13:57
https://github.com/magento/magento2/issues/33595
This one created previously seem same your condition

**Comment by ethmelly** [comment] 2021-07-27 13:59
I've applied this small patch found here [#33595](https://github.com/magento/magento2/issues/33595#issuecomment-887347288) and it fixes my issue with symfony console

**Comment by navarr** [comment] 2021-07-27 14:23
I'm working around this by adding

```
  "conflict": {
    "symfony/console": ">4.4.26"
  },
```

to my composer.json

**Comment by mortenbirkelund** [comment] 2021-07-27 16:43
This is a duplicate of #33595

**Comment by sidolov** [comment] 2021-07-27 17:27
I'm closing the issue as duplicate, let's keep all communication in one place for easy reference: https://github.com/magento/magento2/issues/33595

**Closed as completed by sidolov** 2021-07-27 17:27 UTC
Labels: duplicate, Severity: S0, Priority: P0, Progress: done, Issue: ready for confirmation
