### ISSUE TITLE
Unable to delete categories from products or products from categories when category is a sub-category

### ISSUE THREAD

**Issue by byronrode** [magento/magento2#25407] opened 2019-10-31 15:10 UTC
### Preconditions (*)

1. Magento 2.3.3
2. PHP 7.1.17 (Production, CentOS Linux 7 (Core)) PHP 7.2.24 (Staging, Ubuntu 18.04)
3. Error happens on both servers 

### Steps to reproduce (*)

**This does not happen on top-level categories. Only on sub categories** 

1. Navigate to a product category
1.1 Select a sub-category from the list of categories
1.2 Expand Products in Category
1.3 Uncheck a product to remove from category and save
1.4 Presented with white screen.
1.5 exception.log contains no stack trace related to issue
1.6 PHP logs show stack trace related to core URL Rewrite module (below)

2. Navigate to a product
2.1 Scroll to Categories
2.2 Click to delete a category
2.3 Save product
2.4 Presented with white screen
2.5 exception.log contains no stack trace related to issue
2.6 PHP logs show stack trace related to core URL Rewrite module

### Expected result (*)

1. Expected product to save and no longer be visible in category or show category on the product pages.

### Actual result (*)

1. PHP Stack from stdin error log

```
[31-Oct-2019 13:36:41 UTC] PHP Fatal error:  Uncaught Error: __clone method called on non-object in /var/www/vhosts/redacted/htdocs/vendor/magento/module-catalog-url-rewrite/Observer/UrlRewriteHandler.php:183
Stack trace:
#0 /var/www/vhosts/redacted/htdocs/vendor/magento/module-catalog-url-rewrite/Observer/CategoryProcessUrlRewriteSavingObserver.php(121): Magento\CatalogUrlRewrite\Observer\UrlRewriteHandler->updateProductUrlRewritesForChangedProduct(Object(Magento\Catalog\Model\Category\Interceptor))
#1 /var/www/vhosts/redacted/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\CatalogUrlRewrite\Observer\CategoryProcessUrlRewriteSavingObserver->execute(Object(Magento\Framework\Event\Observer))
#2 /var/www/vhosts/redacted/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\CatalogUrlRewrite\Observer\CategoryProcessUrlRewriteSavingObserver), Object(Magento\Framework\Event\Observer))
#3 /var/www/vhosts/redacted in /var/www/vhosts/redacted/htdocs/vendor/magento/module-catalog-url-rewrite/Observer/UrlRewriteHandler.php on line 183
```

**Comment by byronrode** [comment] 2019-10-31 15:11
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-10-31 15:11
Hi @byronrode. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-10-31 15:11
Hi @byronrode, here is your [Magento instance](https://i-25407-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25407-2-3-develop.instances.magento-community.engineering/admin](https://i-25407-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by byronrode** [comment] 2019-10-31 15:29
Does not seem to be an issue on a vanilla instance of `2.3-develop` however this was not an issue prior to updating from `2.2.x` to `2.3.x`.

The issue is that the on line `183` where `$mergeDataProvider = clone $this->mergeDataProviderPrototype;` runs: `$this->mergeDataProviderPrototype;` is null.

**Comment by byronrode** [comment] 2019-10-31 15:30
I am going to do some more investigation.

**Comment by engcom-Charlie** [comment] 2019-11-04 12:55
Hi @byronrode, I can't reproduce this issue on a fresh Magento 2.3-develop.

**Preconditions:**
Two categories is created with several subcategories. Products are assigned to each subcategory

**Manual testing scenario:**

Navigate to a product category:
1. Go to Catalog → Categories
1.1 Select a sub-category from the list of categories
1.2 Expand Products in Category
1.3 Uncheck a product to remove from category and save 

**Result:** 
Category is saved successfully. 
![image](https://user-images.githubusercontent.com/51680850/68122416-f5369500-ff12-11e9-91fc-984f8de478f1.png)


2. Navigate to a product:
2.1 Scroll to Categories
2.2 Click to delete a category
2.3 Save product

**Result:**

Product is saved successfully.
![image](https://user-images.githubusercontent.com/51680850/68122468-097a9200-ff13-11e9-859f-4f97e0ecd9e2.png)

So i have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-11-04 12:55 UTC
Labels: Issue: Format is valid
