### ISSUE TITLE
Time to time html display on Backend

### ISSUE THREAD

**Issue by brayan-kemana** [magento/magento2#35782] opened 2022-07-19 14:56 UTC
### Preconditions and environment

- Magento version 2.4.3-p2
- PHP 7.4
- Developer mode

### Steps to reproduce

1.) Login on admin.
2.) Open some menu on admin.
3.) It sometimes display sometimes not.

### Expected result

No html diplaye on Admin

### Actual result

When you open some menu this html popup displayed

### Additional information

I'm using Magento 2.4.3-p2 version and I'm getting this issue on my Admin Magento.

Please see attached image.

Can someone help me with this ? Thank you
<img width="412" alt="image" src="https://user-images.githubusercontent.com/109609810/179780637-b0e91805-fdaf-4090-a90c-ab9d11e81dc9.png">

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2022-07-20 10:41
Hello @magentothings ,

 We have tried to reproduce the issue in Magento 2.4-develop branch the issue is not reproducible.

Please refer the below screenshot for the reference; 
![Screenshot from 2022-07-20 15-02-26](https://user-images.githubusercontent.com/60198592/179962381-23b11015-5322-4e03-bc43-20cb5c80e742.png)

We have followed the below steps in order to reproduce the issue: 

1.) Login on admin.
2.) Open some menu on admin.
3.) There is no html display

Let us know in case we have missed anything. 

Thanks!!!

**Comment by magentothings** [comment] 2022-07-21 01:38
Hello @engcom-Dash 

Thank you for your reply, appreciated. Can you give me idea where this issue comes from ? I search this for many times and it tooks me almost a week to fix this kind of issue but still no luck. And as I checked this popup it's under Magento_Ui module here's the path.

Path:
Magento_Ui/templates/tooltip/tooltip.html 

And I tried to override this html file to add hide this elements but issue still persist.  I guess the <% is not converted to text/html. Can you give me idea on how to fix this ? Thank you

**Comment by magentothings** [comment] 2022-07-22 09:12
Hi @engcom-Dash ,

Thank you so much.

**Comment by engcom-Dash** [comment] 2022-07-26 09:58
Hi @magentothings ,

We could not find the exact issue...You may check your logs and clean the cache then try.It may works.

Thanks!!!

**Comment by engcom-Dash** [comment] 2022-08-09 10:35
Dear @magentothings  ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks!

**Closed as completed by engcom-Dash** 2022-08-09 10:35 UTC
Labels: Issue: needs update
