### ISSUE TITLE
GraphQL: category & categoryList query return wrong image url

### ISSUE THREAD

**Issue by mhaack** [magento/magento2#29089] opened 2020-07-13 09:27 UTC
The `category` & `categoryList` query return wrong image URL on an upgraded instance (from 2.3.4 to 2.3.5).

For example - GraphQl result:

```
{
  "id": 34,
  "url_path": "venia-dresses",
  "image": "https://cif-enablement-s4n4tla-o24f6fbtz7p34.demo.magentosite.cloud/index.php/media/catalog/category/timeless.jpg"
}
```
URL is wrong and resolves into 404. Correct URL should be without `/index.php` like `https://cif-enablement-s4n4tla-o24f6fbtz7p34.demo.magentosite.cloud/media/catalog/category/timeless.jpg`

### Preconditions (*)

1. Magento 2.3.5, upgraded from 2.3.4
2.

### Steps to reproduce (*)

1. Setup Magento 2.3.4
2. Install Venia sample data like described on the docs
3. Upgrade to Magento 2.3.5
4. Query for categories which have an image, both `category` & `categoryList` returns wrong image URL

### Expected result (*)

1. Correct Image URL
2.

### Actual result (*)

1. Wrong image URL, see above
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by achleitner** [comment] 2020-07-13 09:28
give me 2.4-develop instance

**Comment by achleitner** [comment] 2020-07-13 09:29
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-07-13 09:29
Hi @achleitner. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by mauragcyrus** [comment] 2020-10-13 15:24
We fixed this in 2.3.5 for when URL rewrites are turned **on** (https://github.com/magento-commerce/magento2ce/pull/5369) but now we need to enable it even when URL rewrites are turned **off**.

**Comment by konarshankar07** [comment] 2020-10-23 13:36
@magento I'm working on this

**Comment by engcom-November** [comment] 2022-09-08 12:29
Verified the issue on Magento 2.4-develop branch but the issue is not reproducible in both the cases: url rewrites turned off / on.
![image](https://user-images.githubusercontent.com/60198231/189121931-b51a485f-4fa9-4ae9-88e7-1a443d0cda42.png)
Kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-09-21 11:41
We are closing this issue as there has been no latest updates on the same. Kindly reopen / create if the issue is still reproducible.
Thanks.

**Closed as completed by engcom-November** 2022-09-21 11:41 UTC
Labels: Issue: Format is valid, Priority: P2, Project: GraphQL, Progress: done, Mageconf_Contribution_Day, Issue: needs update
