### ISSUE TITLE
Improper validation in Catalog REST Webapi: Eav Indexer Duplicate entry error

### ISSUE THREAD

**Issue by thomas-kl1** [magento/magento2#38097] opened 2023-10-18 08:12 UTC
### Preconditions and environment

- 2.4.4, but may exists on any version
- Update a product through the rest webapi
- Indexer update
- Observe modification on frontend

Create an attribute allergens which is a multiselect, with many options.

### Steps to reproduce

Send a request to the Magento Catalog Rest Bulk Async Webapi in order to update the products:

```json
[ { "product":{ "sku":"sku-test", "name":"Test", "Weight":0.28, "price":10, "custom_attributes":[ { "attribute_code":"ingredient", "value":"Test" }, { "attribute_code":"dimention", "value":"19,9 cm x 12,1 cm x 3,3 cm" }, { "attribute_code":"tax_class_id", "value":"11" }, { "attribute_code":"allergens", "value":"1115,1115,877,934" }, { "attribute_code":"lty_price_in_pts", "value":500 }, { "attribute_code":"price_kg", "value":44550 } ] } } ]
```

The fact that '1115' is duplicated in the message is on purpose in order to expose the problem.

- Run the request, the product is correctly updated
- The indexer are in error (eav, product, price, inventory, stock, targe, search)

Error:
`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'x-x-x-x-x' for key 'catalog_product_index_eav_temp.PRIMARY', query was: INSERT INTO `catalog_product_index_eav_temp` (`entity_id`,`attribute_id`,`store_id`,`value`,`source_id`) VALUES (?, ?, ?, ?, ?)`

### Expected result

Magento remove duplicated values, indexer runs well, data is updated on frontend.

### Actual result

Magento does not remove duplicated values, indexer are in errors, updates are not reflected on frontend.

### Additional information

This issue does not occurs from BO because the multi-select field prevent to have the same values multiple times, however, a check which enforce data integrity would be useful to prevent any damage on the system.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by chalov-anton** [comment] 2023-10-30 09:34
@magento give me 2.4-develop instance

**Comment by chalov-anton** [comment] 2023-10-30 16:58
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2024-01-23 12:20
Hello @thomas-kl1,

Thank you for the report and collaboration!

We tried to reproduce this issue on 2.4-develop, but the issue is not reproducible in our case.
Updated the product with duplicate attribute in the message request as below,
```
{
    "product": {
      "sku": "test-prd-1",
      "name": "Test Product one",
      "Weight": 0.28,
      "price": 10,
      "custom_attributes": [
        {
          "attribute_code": "allergens",
          "value": "20030,20030,20031,20032"
        }
      ]
    }
  }
```
Duplicate attribute is handled, able to view the changes in frontend, and indexer is working well.

Please take a look at the screenshot below:
**Duplicate entry is handled**
<img width="783" alt="image" src="https://github.com/magento/magento2/assets/60198231/534af9fe-3edb-4231-ae13-5e813ce46964">
**Changes are reflected on frontend**
<img width="1408" alt="image" src="https://github.com/magento/magento2/assets/60198231/2d198762-1adc-40d2-a46e-75142ea5269c">

This issue might have been fixed in the latest version, if you are still facing this issue llet us know.

Thank you.

**Comment by engcom-November** [comment] 2024-02-14 11:45
Hello @thomas-kl1,

As there is no activity on this issue for a long time, we believe the issue has been resolved, hence closing this issue.
Feel free to raise a new issue or reopen this if you need more assistance.

Thank you.

**Closed as completed by engcom-November** 2024-02-14 11:45 UTC
Labels: Issue: needs update, Reported on 2.4.x
