### ISSUE TITLE
Stores are not shown in "Login as Customer: Select Store" modal window on order view page

### ISSUE THREAD

**Issue by engcom-Delta** [magento/magento2#29752] opened 2020-08-26 13:32 UTC
### Preconditions (*)

1. Magento 2.4.1 ( СЕ )
2. Login as Customer module enabled
3. Store View To Login To=Manual Selection
4. Create additional website
![image](https://user-images.githubusercontent.com/51681379/91309370-31482880-e7b9-11ea-8d66-f90aebb2590b.png)

### Steps to reproduce (*)

1. Create customer with checked "Allow remote shopping assistance" option
2. Place order by customer
3. Go to admin panel
4. Go to Sales->Orders
5. Click Edit for last order
6. Click on Login as Customer

### Expected result (*)

1. Stores are shown in dropdown in "Login as Customer: Select Store" modal window
![image](https://user-images.githubusercontent.com/51681379/91309645-85eba380-e7b9-11ea-85a3-992813bb763f.png)

### Actual result (*)

1.  No stores are shown in dropdown in "Login as Customer: Select Store" modal window
![image](https://user-images.githubusercontent.com/51681379/91309776-b0d5f780-e7b9-11ea-8757-740811743e38.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment] 2020-08-26 19:38
@sdzhepa Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2020-08-26 19:39
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37097` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by konarshankar07** [comment] 2020-08-27 06:32
@magento I'm working on this

**Comment by engcom-Foxtrot** [comment] 2020-08-27 07:56
@konarshankar07 this issue isn't reproducible on 2.4-develop branch. You need access to a private repository to fix this issue.

**Comment by konarshankar07** [comment] 2020-08-27 08:19
Hello @engcom-Foxtrot ...
Yes, I'm not able to reproduce this issue in 2.4-develop branch so Shall I need to unassign the issue? cause I don't have access to the private repo

**Comment by engcom-Foxtrot** [comment] 2020-08-27 09:15
@konarshankar07 I'll unassign you.

**Comment by magento-engcom-team** [comment] 2020-09-08 13:28
Hi @engcom-Delta, @engcom-Foxtrot. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. 

The fix will be available with the upcoming `2.4.2` release.

**Closed as completed by magento-engcom-team** 2020-09-08 13:28 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Issue: Format is valid, Component: Other, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P1, Severity: S1, Project: Login as Customer, Progress: done, Reported on 2.4.1
