### ISSUE TITLE
[2.0.6] Issues with INR currency in checkout in multisite

### ISSUE THREAD

**Issue by develsites** [magento/magento2#5036] opened 2016-06-15 10:33 UTC
## Steps to reproduce
1. Please, create two websites with different currency, for example GBR and INR. Where GBR is a base store.
2. Please, go to Configuration > Gatalog > Catalog > Price, set up the "Catalog Price Scope" as "Website"
3. Please, go to Configuration > General > Currecy Setup > Select "Indian" website on the top, and set up the "Base Currency", the "Default Display Currency" and the "Allowed Currencies" as "Indian Rupee"
4. Create some configurable products for test for each store (use Websites option)
5. Set up prices for each "Simple" products
6. Order some products in IN storefront
## Expected result
1. After ordering you go to Admin > Sales > Orders  you should see INR currency of ordering products 
## Actual result
1. If you go to Admin > Sales > Orders so you are seeing GBR currency for this 
2. Screen-grab is attached

![screenshot_1](https://cloud.githubusercontent.com/assets/2625408/16076736/9491e716-32fd-11e6-9ad8-1afe27619d80.png)

**Comment by NadiyaS** [comment] 2016-06-21 15:39
Hi @millionerrr ,
this issue is not reproducible on develop branch. You can upgrade your code from this branch or 2.1-rc3 or wait until next release.
This is also duplicate of #4980 and #4553
Feel free to reopen this bug if you encountered the same problem in next version

**Closed as completed by NadiyaS** 2016-06-21 15:39 UTC

**Comment by maderlock** [comment] 2016-11-30 17:03
Finding the same issue in 2.1.2

In this case, having different base currencies in two stores, the sale_order_grid has some entries with EUR as base_currency_code and order_currency_code and others with GBP for the same.

The default currency is GBP, so it is showing all prices with a pound symbol in the order grid, even though the values are in Euros. All prices then look correct in the orders themselves.

**Comment by maderlock** [comment] 2016-11-30 17:43
having stepped through the prepareDataSource method of module-sales/Ui/Component/Listing/Column/Price.php, I've found the issue in my case.  Magento\Framework\Pricing\PriceCurrencyInterface is used to format the currency via a format method call, but when this is called the following is run:
````
$currency = $this->currencyFactory->create()
                ->load($currency);
            $baseCurrency = $this->getStore($scope)
                ->getBaseCurrency();
            $currentCurrency = $baseCurrency->getRate($currency) ? $currency : $baseCurrency;
````

What you'll notice is that it loads a base currency and then tries to find a conversion from it to the requested currency. If you have two websites with separate base currencies where you set the prices manually, there is no reason why you would necessarily set a conversion rate at all (this is the case with my site). However, the above code means that it will then ignore the base currency of the site and use the default base currency.

The solution would seem to be to pass the scope of the order's store to the formatter, which will then use the base currency of the item rather than the default base currency. Unfortunately, when one gets to module-sales/Ui/Component/Listing/Column/Price.php::prepareDataSource, the store_id has already been replaced with the display version of the store name, so the fix is not quite a one liner.

**Comment by maderlock** [comment] 2016-11-30 17:43
In the meantime, the work around is to ensure that there is a conversion rate for all currencies, even if you don't use them.

**Comment by danpecher** [comment] 2017-01-20 23:41
I also had this issue and setting conversion rates (even though I set prices manually) worked.

**Comment by wescey** [comment] 2018-11-13 12:29
Im running a 2.2.2 installation with 5 multiple websites with each own currency. In the Sales > Orders grid (grand total base), it's only displaying one currency that is based on default value.
