### ISSUE TITLE
GraphQl query categoryList with no argumets returns tree up to level 3

### ISSUE THREAD

**Issue by martinbabic** [magento/magento2#35988] opened 2022-08-19 19:59 UTC
### Preconditions and environment
Magento 2.4.5 Commerce, 2.4-develop
PHP 8.1
Composer 2.1.0
Category Tree with over 400 categories that runs through 5 levels (Default > Products > View By Category > Level4 > Level5
### Steps to reproduce
Run Graphql query:

`# Write your query or mutation here
query getMegaMenu {
  categoryList {
    uid
    name	
    children {
      uid
      include_in_menu
      name
      position
      url_path
      image
      children {
        uid
        include_in_menu
        name
        position
        url_path
        image
        children {
          uid
          include_in_menu
          name
          position
          url_path
          children {
            uid
            include_in_menu
            name
            position
            url_path
            __typename
          }
          __typename
        }
        __typename
      }
      __typename
    }
    __typename
  }
}
`

### Expected result

Return the category tree up to 5 levels because it doesn't breaks the queryDepth nor queryComplexity limits.

### Actual result

Returns only a handful of categories up to level 3, levels 4 and 5 are not returned (the children is [] for level 3 even if there are actually subcategories to them.

### Suspected cause:

In File vendor/magento/module-catalog-graph-ql/Model/Resolver/Products/DataProvider/CategoryTree.php, in function `public function getCollection()` the collection doesn't load - if I replace the return statement from:

`return $collection;`

to

`return $collection->load();`

I get the **expected result**.

**Comment by engcom-November** [comment] 2022-10-04 17:30
Verified the issue on Magento 2.4-develop instance and the issue is reproducible. Hence confirming the issue.
Issue: Sub categories children categories are not retrieved in the response.
![image](https://user-images.githubusercontent.com/60198231/193886676-fe59d1d1-0d71-437e-9d9e-579f85e3bf71.png)
![image](https://user-images.githubusercontent.com/60198231/193886727-1ca3a171-331c-41c2-a8a7-17ae164579e8.png)

**Comment by ed007m** [comment] 2022-11-22 15:16
That happens because of pagination was added here
vendor/magento/module-catalog-graph-ql/Model/Resolver/Products/DataProvider/CategoryTree.php:215

`        $pageSize = $criteria['pageSize'] ?? 20;
        $currentPage = $criteria['currentPage'] ?? 1;`

**Comment by engcom-November** [comment] 2023-03-06 05:38
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2023-03-06 05:43
Hi @martinbabic ,
We re verified the issue again on Magento 2.4-develop instance and the issue is no more reproducible. All 5levels of categories are retrieved in the GraphQl response. Kindly recheck the issue again on Magento 2.4-develop instance and let us know if you are still facing any issues.
![image](https://user-images.githubusercontent.com/60198231/223028262-c05ee976-f6d0-4f88-b1f7-9dacd756aacf.png)
![image](https://user-images.githubusercontent.com/60198231/223028315-de27ee72-e9ad-4ceb-964c-fa2570189dd1.png)

**Comment by engcom-November** [comment] 2023-03-20 06:02
Hi @martinbabic ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2023-03-20 06:02 UTC
Labels: Issue:  Cannot Reproduce, Component: GraphQL, Reproduced on 2.4.x, Priority: P2, Project: GraphQL, Progress: done, Issue: needs update, Area: Catalog, Reported on 2.4.5
