### ISSUE TITLE
Wrong sort order for option values on the product detail page.

### ISSUE THREAD

**Issue by basselalaraaj** [magento/magento2#8196] opened 2017-01-19 10:44 UTC
### Preconditions
1. Magento develop branch
2. Php 7

### Steps to reproduce
1. Change the sort order of swatch values in admin. Then go to the product detail page.
![screen shot 2017-01-19 at 11 32 37](https://cloud.githubusercontent.com/assets/5745279/22103630/2ef2bfee-de3c-11e6-9a76-9f24dcff9ee6.png)

### Expected result
![screen shot 2017-01-19 at 11 45 00](https://cloud.githubusercontent.com/assets/5745279/22103776/bfd5f148-de3c-11e6-95c5-260933292fbe.png)

### Actual result
![fault](https://cloud.githubusercontent.com/assets/5745279/22103675/5e6bd206-de3c-11e6-92f0-94e8b15a41a1.jpg)

### Issue
Its sorting based on option_id instead of sort_order

**Comment by basselalaraaj** [comment] 2017-01-19 10:47
I built the solution in https://github.com/magento/magento2/pull/8197

**Comment by magento-engcom-team** [comment] 2017-09-20 22:58
@basselalaraaj, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:58 UTC
Labels: bug report, Component: Catalog, Fixed in 2.2.x, Issue: Format is valid
