### ISSUE TITLE
Admin Checkout Customer Form Datepicker Not Displaying After AJAX Load

### ISSUE THREAD

**Issue by mrIntegrator** [magento/magento2#9951] opened 2017-06-14 22:22 UTC
When placing an order in the admin, date attribute fields (e.g. date of birth) on the customer form are not transformed into date pickers when the form is loaded by AJAX. If the page is refreshed, the date pickers appear.

### Preconditions

1. Magento CE 2.1.5 with sample data.

### Steps to reproduce

1. In the admin, under Stores > Configuration > Customers > Customer Configuration > Name and Address Options, set the "Show Date of Birth" option to "Required".
2. Go to Sales > Orders and then click "Create a New Order" and then "Create a New Customer".
3. Note that the "Date of Birth" field is not displayed as a date picker.
4. Refresh the page and note that the date picker now appears.

### Expected result

1. The date picker should always appear.

### Actual result

1. The date picker does not appear when the form is loaded by AJAX.

There is a missing "contentUpdated" event after the form is loaded.

**Comment by mrIntegrator** [comment] 2017-06-14 22:47
Found the solution. The following line must be added after [app/code/Magento/Sales/view/adminhtml/web/order/create/scripts.js:1037](https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/view/adminhtml/web/order/create/scripts.js#L1037):

`jQuery('#' + this.getAreaId(id)).trigger('contentUpdated');`

I can create this pull request if the issue has not already been fixed.

**Comment by korostii** [comment] 2017-06-15 20:55
It's not likely that you'll have any attention from core developers soon enough.
I'd advise to either go ahead with pull request right away or check whether the issue can be reproduced using latest code from `develop` branch yourself.

**Comment by Stas94** [comment] 2017-06-23 09:54
@mrIntegrator Thanks for reporting this issue.  We've created internal ticket MAGETWO-70140 to address this issue.

**Comment by magento-engcom-team** [comment] 2017-10-09 08:30
@mrIntegrator, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-09 08:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Customer, Issue: Format is valid
