### ISSUE TITLE
order with invoice status pending get closed after shipping

### ISSUE THREAD

**Issue by onlinebizsoft** [magento/magento2#34055] opened 2021-09-11 02:06 UTC
Magento has a check canCreditMemo canInvoice canShip to decide to close the order. This sounds good but Magento also offer status for Invoice (pending/paid) and status for Credit memo (pending/refunded)

The problem happen when we have a module or have a customization which can create an invoice with status Pending -> the order will get closed after shipping because all above conditions are met. I think we could take a look for different user cases and adding more conditions

### Preconditions (*)

1. Order with invoice payment pending status
2. Order have shipment

### Steps to reproduce (*)

1. Place an order from front-end using PayPal Express checkout
2. Create an invoice from admin with option - "Not capture"  (Sales - Orders - View Order - Invoice - Select Not Capture and submit) - Order status is Processing and Invoice status is "Pending"
3. Create shipment from admin (Sales - Orders - View Order - Ship) - **Issue**: Order status became closed and Invoice status is "Pending"

### Expected result (*)

1. The order should be Processing (or Completed)

### Actual result (*)

1. The order gets closed and invoice status is still Pending.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment] 2021-09-15 09:19
Hi @onlinebizsoft,

I tried to reproduce this but the description needs some more info.

From the look, it could be an expected behaviour. General behaviour is once Invoice is created and order is shipped it can be considered as 'Complete'. So if you are changing values directly in DB after invoicing, it could affect the order. Anyways, will do further analysis once you provide some more info.

Can you please elaborate on **Step 3** ? I mean what values you changed in which specific table fields to understand the issue.

**Comment by onlinebizsoft** [comment] 2021-09-16 16:36
> Hi @onlinebizsoft,
> 
> I tried to reproduce this but the description needs some more info.
> 
> From the look, it could be an expected behaviour. General behaviour is once Invoice is created and order is shipped it can be considered as 'Complete'. 

I do agree and if it works that way then it would be good as well.

>So if you are changing values directly in DB after invoicing, it could affect the order. 

Since I don't have a way to create the invoice with pending status in a standard installation but maybe you can do it if a payment method which support "not capture", see the document https://docs.magento.com/user-guide/v2.3/sales/invoice-create.html
"if the method of payment is a purchase order, the order can be invoiced and shipped before payment is received"

So it is normal for a custom payment method which allow an invoice without capturing.

>Anyways, will do further analysis once you provide some more info.
> 
> Can you please elaborate on **Step 3** ? I mean what values you changed in which specific table fields to understand the issue.

"state" in table sales_invoice (change from 2 to 1)

**Comment by engcom-Lima** [comment] 2021-09-23 13:38
Hi @onlinebizsoft,

Yes exactly, if you are going with option 'Not Capture', please make sure you read the below notice from the documentation:

`Do not select the Not Capture option unless you are certain that you are going to capture the payment through Magento at a later date. You cannot create a credit memo until the payment has been captured using the Capture button.`

From your last comment, I think it can solve your issue. Please let me know if you need more assistance on this or can we close this issue ?

Thanks

**Comment by onlinebizsoft** [comment] 2021-09-23 16:33
@engcom-Lima no, we cant close. I have read that line and it has no relation this ticket. I am NOT going to create credit memo. Im shipping the order then the order get closed -> this is wrong.

Do not ask to close the issue when you dont read carefully.
@hostep you may have some ideas?

**Comment by hostep** [comment] 2021-09-23 18:30
Hmm, so:

- You have an order
- You have an invoice that's not paid yet (payment happens after shipment arrived with the customer I guess?)
- You have a shipment

And the order gets status 'Closed', but you expect it to be in 'Processing' until the invoice is paid or just be 'Completed'.
Is this a correct summary?

I think the status 'Closed' is then not correct here. But I'm not sure what status it really should be in.

I have very little experience in this area, @paliarush: I believe you might have some knowledge around this? Do you have some time to look into this to see if this is a valid request?

**Comment by onlinebizsoft** [comment] 2021-09-24 06:10
@hostep yes thats correct. I wrote it clearly at the begining I think

**Comment by jackjimmy** [comment] 2021-09-29 09:40
first try to disabled all third party extension and test 1 order. because it's not related to magento issues. there is something conflict with third party extension.

**Comment by onlinebizsoft** [comment] 2021-09-29 13:53
@jackjimmy how do you know if it is not related to magento issue? ;)
as said, in Magento core, the logic is "if !canCreditMemo() and !canInvoice() and !canShip() then close order".
So in our cases, all above conditions are passed and the order were closed.

**Comment by onlinebizsoft** [comment] 2021-11-02 13:10
Any news @engcom-Lima ?

**Comment by engcom-Echo** [comment] 2022-01-03 12:26
Hi @onlinebizsoft,

Thank you for your input.

Can you please specify where can I find the logic "if !canCreditMemo() and !canInvoice() and !canShip() then close order" or anywhere written ? I’ll do further analysis accordingly.

Thanks

**Comment by hostep** [comment] 2022-01-22 17:09
@engcom-Echo: I *think* it's over [here](https://github.com/magento/magento2/blob/c901f760818228faaf72177a0601bb4258aa9eec/app/code/Magento/Sales/Model/ResourceModel/Order/Handler/State.php#L33-L45)

**Comment by engcom-Delta** [comment] 2022-04-07 01:36
Hi @hostep ,

We have noticed that this issue has not been updated for a period of more than 14 Days and it was over as per last comment.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Comment by hostep** [comment] 2022-04-07 06:00
@engcom-Delta: how did you not see my last comment? 😛

**Comment by numan201** [comment] 2022-04-08 09:27
Running into same issue. Added `&& (int) $order->getTotalDue() == 0` to line 33 of [State.php linked by hostep](https://github.com/magento/magento2/blob/c901f760818228faaf72177a0601bb4258aa9eec/app/code/Magento/Sales/Model/ResourceModel/Order/Handler/State.php#L33-L45).

Just a temporary fix for our store. I think my int cast is not necessary. Thanks for pointing to the code snippet @hostep!

**Comment by Xeo67** [comment] 2022-06-10 08:49
Hello,

i reproduce this issue on Magento 2.4.3-p2 since i use the new Adyen module (v8.2.2) with asynchronous capture.
How can we reopen this issue ? Must we do a new one ?

**Comment by engcom-Lima** [comment] 2022-07-19 13:23
As per our internal team discussion, reopening this issue.

**Comment by engcom-Lima** [comment] 2022-07-19 13:27
Hi @onlinebizsoft,

In order reproduce the issue can you provide us steps where we do not have to change anything in Db?

Thank you

**Comment by onlinebizsoft** [comment] 2022-07-19 13:40
@engcom-Lima Magento designed the status flag for Invoice which can be Pending/Paid.
So can you tell me how can I create an invoice with Pending status?

**Comment by engcom-November** [comment] 2022-08-09 10:06
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-08-09 12:02
Hi @onlinebizsoft ,
It is not possible to create an invoice with Pending status on latest Magento 2.4-develop instance. Ref [docs1](https://docs.magento.com/user-guide/v2.3/configuration/sales/payment-methods.html), [docs2](https://docs.magento.com/user-guide/sales/order-status-workflow.html) However this issue is reproducible with below steps performed:
1. Created an Order from front-end with PayPal Express checkout payment method. Order status is "Processing"
2. Created an invoice from admin with option "Not capture" and submit. Order status is Processing and Invoice status is "Pending"
3. Created shipment from admin - Order status is closed and invoice status is Pending.
![image](https://user-images.githubusercontent.com/60198231/183642100-1bc777cc-0c53-41f2-804d-ca03313cce6f.png)
![image](https://user-images.githubusercontent.com/60198231/183642236-d2fcca1e-3594-4d0e-8c2c-bb86e279fa86.png)
Hence updating the description and confirming the issue.

**Comment by jsamhall** [comment] 2023-02-15 13:25
Experiencing this issue in 2.4.5-p1, in our case it is related to orders paid with Klarna who's merchant terms mandate capturing payment upon shipment release.

Is there any progress on this ticket, or a confirmation of the bandaid suggested by @numan201 to avoid this issue?

Capturing an invoice after shipment is released is a standard biz practice, this must be recognized by Magento!

**Comment by engcom-Delta** [comment] 2024-10-10 12:27
Hi @onlinebizsoft ,

Thanks for your reporting and collaboration.
We have re-verified the issue in 2.4-develop instance , but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce**
1. Created an Order from front-end with PayPal Express checkout payment method. Order status is "Processing"
2. Created an invoice from admin with option "Not capture" and submit. Order status is Processing and Invoice status is "Pending"
3. Created shipment from admin - Order status is processing and invoice is pending
![image](https://github.com/user-attachments/assets/8841af19-6b08-4e1d-8a9b-4f9dfeea36b2)
![image](https://github.com/user-attachments/assets/544d697f-15bc-4f54-963b-8059df192ca7)

Can you please re-verify and confirm if you are still facing the issue.
Thanks.

**Comment by engcom-Delta** [comment] 2024-10-22 13:09
Hi @onlinebizsoft ,

We have noticed that this issue has not been updated since long time.
Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Delta** 2024-10-22 13:09 UTC
Labels: Component: Payment, Reproduced on 2.4.x, Priority: P2, Progress: done, Issue: needs update, Reported on 2.4.x, Area: Payments

**Comment by hostep** [comment] 2024-10-23 20:19
If I have to _guess_, it might have been fixed by [ACP2E-2756: [Cloud] Order Status changed to complete when partially refund of a partially shipped order](https://github.com/magento/magento2/commit/6b088e92a154fdb4e7461376768fa30e8e756f64) and/or [ACP2E-3045: Order closed without fully refunded](https://github.com/magento/magento2/commit/89adeba03b8377c575661757885c6b2e7e599dfe) (both to be released in Magento 2.4.8), but I'm not sure...
