### ISSUE TITLE
[MAGETWO-2343] Import does not work for product Custom Option with type = File

### ISSUE THREAD

**Issue by piotrekkaminski** [magento/magento2#11978] opened 2017-11-02 20:48 UTC
### Preconditions
1. Version 2.0

### Steps to reproduce
1. Open Backend - Manage Products
2. Create new Product with custom option type = File
3. Open Export and make Product export
4. Open created Product and remove File custom option
5. Open Import and make Product import with before exported file

### Actual result
Imported custom option with type = File is not imported

### Expected result
Imported custom option with type = File is imported

**Comment by magento-engcom-team** [comment] 2017-11-03 09:13
@piotrekkaminski, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-11-03 09:13 UTC
Labels: Component: ImportExport, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
