### ISSUE TITLE
Magento 2.3.3 rest api Get call rest/all/V1/categories not returning name in the the response

### ISSUE THREAD

**Issue by YouCanDoIt12** [magento/magento2#25837] opened 2019-11-29 09:49 UTC
### Preconditions (*)

Magento version: community 2.3.3 
Rest Api : rest/all/V1/categories
Method: Get

### Steps to reproduce (*)

Make a get call to the rest api rest/all/V1/categories 
check the response:
The response should contain name for the child category 

### Expected result (*)

{
    "id": 1,
    "parent_id": 0,
    "name": "sss",
    "is_active": null,
    "position": 0,
    "level": 0,
    "product_count": null,
    "children_data": [
        {
            "id": 2,
            "parent_id": 1,
            "name": "sss",
            "is_active": true,
            "position": 1,
            "level": 1,
            "product_count": null,
            "children_data": []
        },
        {
            "id": 3,
            "parent_id": 1,
            "name": "sss",
            "is_active": true,
            "position": 2,
            "level": 1,
            "product_count": null,
            "children_data": [
                {
                    "id": 4,
                    "parent_id": 3,
                    "name": "sss",
                    "is_active": true,
                    "position": 1,
                    "level": 2,
                    "product_count": null,
                    "children_data": []
                }
            ]
        }
    ]
}

### Actual result (*)
{"id":1,"parent_id":0,"name":null,"is_active":null,"position":0,"level":0,"product_count":null,"children_data":[{"id":2,"parent_id":1,"name":null,"is_active":null,"position":1,"level":1,"product_count":null,"children_data":[]},{"id":3,"parent_id":1,"name":null,"is_active":null,"position":2,"level":1,"product_count":null,"children_data":[{"id":4,"parent_id":3,"name":null,"is_active":null,"position":1,"level":2,"product_count":null,"children_data":[]}]}]}

**Comment by engcom-Charlie** [comment] 2019-11-29 10:14
Hello @13mcmc12 
This is known issue and it is fixed now by https://github.com/magento/magento2/commit/eb28168184ff769e0f03c8c2e5c2fe223cdac7a2#diff-06419995ef6a4b327e3306cfba805293R110. (fix will be included in 2.3.4 release line)

So i can close this issue as duplicate of https://github.com/magento/magento2/issues/25269

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-11-29 10:14 UTC
Labels: Issue: Format is valid

**Comment by Ghadawi** [comment] 2020-04-27 22:19
i have update magento 2.3.4 but still remain same problem, any suggestion?

**Comment by Ghadawi** [comment] 2020-04-27 22:49
i have update vendor/magento/module-catalog/Model/Category/Tree.php
with following code and it works
` $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
       $categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');
       $categoryId = $node->getId();
       $nodeS = $categoryFactory->create()->load($categoryId);
       /** @var \Magento\Catalog\Api\Data\CategoryTreeInterface[] $children */
       $children = $this->getChildren($node, $depth, $currentLevel);
       /** @var \Magento\Catalog\Api\Data\CategoryTreeInterface $tree */
       $tree = $this->treeFactory->create();
       $tree->setId($nodeS->getId())
           ->setParentId($nodeS->getParentId())
           ->setName($nodeS->getName())
           ->setPosition($nodeS->getPosition())
           ->setLevel($nodeS->getLevel())
           ->setIsActive($nodeS->getIsActive())
           ->setProductCount($nodeS->getProductCount())
           ->setChildrenData($children);
       return $tree;`
