### ISSUE TITLE
Incorrect coordinate value in dashboard diagram

### ISSUE THREAD

**Issue by Yuwei9291** [magento/magento2#25865] opened 2019-12-01 09:07 UTC
### Preconditions (*)

1.CentOS 7,Nginx 16, Mysql 5.6, php 7.3
2.Clean install magento 2.3.3
3.Upload products 
4. Enable Charts.
### Steps to reproduce (*)

1.Place an order 
2. Invoice an order
3.Go to dashboard
### Expected result (*)

1. It should show 1 not 2 here
![shouldb elikethat](https://user-images.githubusercontent.com/45879513/69911867-cbfb1d00-145c-11ea-9536-4d814143a73f.jpg)

### Actual result (*)

1.It showed 2 orders instead of 1 in diagram
![TIM截图20191201165643](https://user-images.githubusercontent.com/45879513/69911848-80487380-145c-11ea-813f-2f2995c45a98.jpg)

**Comment by magento-engcom-team** [comment] 2019-12-02 14:04
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29307` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ihor-sviziev** [comment] 2021-02-18 14:05
@magento give me test instance

**Comment by ihor-sviziev** [comment] 2021-02-18 14:05
@magento give me 2.4-develop instance

**Comment by ihor-sviziev** [comment] 2021-02-18 16:04
Hi @Yuwei9291,
I can't reproduce this issue  on 2.4-develop branch.

![image](https://user-images.githubusercontent.com/1873745/108384732-b0bc2f00-7213-11eb-8faa-2063cf389e57.png)


Could you double-check if you still can reproduce it?

**Comment by ihor-sviziev** [comment] 2021-04-07 08:25
As we didn't get any confirmation that the issue still valid - I'm closing this issue.

**Closed as completed by ihor-sviziev** 2021-04-07 08:25 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.3.x, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Other, Severity: S4, Priority: P4, Progress: done
