### ISSUE TITLE
StorefrontFreeShippingDisplayWithInclTaxOptionTest MFTF Test failed in CLI.

### ISSUE THREAD

**Issue by ajithkumar-maragathavel** [magento/magento2#26773] opened 2020-02-08 18:07 UTC
### Preconditions (*)

1. Setup Magento 2.3.4 develop branch in a local environment.
2. Configure the MFTF test environment.

### Steps to reproduce (*)

After configuring the MFTF test environment.
1. Run the below command: 
vendor/bin/mftf run:test StorefrontFreeShippingDisplayWithInclTaxOptionTest --remove
2. The test result is getting failed. below is the reference screenshot.

![mftf-issue](https://user-images.githubusercontent.com/47966038/74089861-9cefd000-4acb-11ea-86ac-6d66226b25c6.png)

### Expected result (*)

1. The test should pass after execution.

### Actual result (*)

1. The test is throwing error and failed.

**Comment by engcom-Alfa** [comment] 2020-02-12 12:35
Hi @ajithkumar-maragathavel. 
Unfortunately, we are not able to reproduce this issue on the fresh 2.4-develop instance.

**Actual Result:** 
The test passed successfully
![screen](https://user-images.githubusercontent.com/51679138/74335304-93ed5000-4da4-11ea-95a5-53101e07c365.png)
So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-02-12 12:35 UTC
Labels: Issue: Format is valid, Reported on 2.3.4
