### ISSUE TITLE
Insert Image button not working 2nd time magento2 cms page backend

### ISSUE THREAD

**Issue by tripath** [magento/magento2#10691] opened 2017-08-29 05:20 UTC
When try to click on insert image 2nd time it's not working please note that it's working on first time

### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

![magento2_backend_image_issue](https://user-images.githubusercontent.com/31430019/29805484-aa3154da-8ca7-11e7-94ae-37a27db24077.png)

**Comment by magento-engcom-team** [comment] 2017-09-12 08:23
@tripath  thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
- [ ]  Preconditions: Magento version
- [ ] Steps to reproduce
- [ ] Expected result
- [ ] Actual result

**Comment by magento-engcom-team** [comment] 2017-09-27 22:00
@tripath, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-27 22:00 UTC
Labels: bug report, Progress: needs update, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
