### ISSUE TITLE
Page is not responsive after adding filter in order grid 

### ISSUE THREAD

**Issue by abhay1198** [magento/magento2#37481] opened 2023-05-10 10:03 UTC
### Summary

Magento Version - 2.4.6
Steps
1. Open the Admin Panel
2. Navigate to Sales-> Order 
3. Add filters from column in the grid
4. check the page responsiveness
5. Page is not responsive

<img width="880" alt="image" src="https://github.com/magento/magento2/assets/39663362/36c01d9a-cdf1-49e9-a15a-ebd1f98ef7ab">

### Examples

Magento 2.4.6

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-05-10 20:57
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-05-10 21:19
Hi @abhay1198 ,
Thanks for Contribution and Collaboration!

Verified the issue in 2.4-develop instance and 2.4.6 Magento instance and the issue is not reproducible.

Preconditions:
Magento version 2.4-develop and 2.4.6
PHP 8.1

Steps to reproduce:
1.Install Magento instance
2.Go to Admin >Sales >Order and Add filter in Column grid
3.Check page responses

Kindly refer the screenshots:
After adding some options in Column :
<img width="1511" alt="After adding column" src="https://github.com/magento/magento2/assets/60198592/6b71910d-3c48-4fbf-bfe1-149e359a62f1">
Before Adding the filter in column :
<img width="1511" alt="Before Add column filter" src="https://github.com/magento/magento2/assets/60198592/0b1880ff-d52c-499a-bd66-4e97fedbc850">

Kindly provide some information if the issue still reproducible.

Regard's,

**Comment by mrtuvn** [comment] 2023-05-11 03:40
Duplicated when we have reported here https://github.com/magento/magento2/issues/37459

**Comment by abhay1198** [comment] 2023-05-11 03:46
@mrtuvn ++

**Comment by engcom-Dash** [comment] 2023-05-11 11:09
Hi @abhay1198 ,

Seems the this issue [Duplicate](https://github.com/magento/magento2/issues/37481#issuecomment-1543286117),Hence we are closing this issue.

Regards

**Closed as completed by engcom-Dash** 2023-05-11 11:09 UTC
Labels: duplicate, Triage: Dev.Experience, Issue: needs update, Reported on 2.4.6
