### ISSUE TITLE
State label is inconsistent with state code on status listing page

### ISSUE THREAD

**Issue by matthewhaworth** [magento/magento2#9682] opened 2017-05-18 10:03 UTC
### Preconditions
1. Install Magento 2.1.6  
2. Install sample data

### Steps to reproduce

1. Login to the admin panel
2. Navigate to Stores -> Order Status

### Expected result

The states in the "State Code and Title" should have the correct title in the square brackets afterwards, for example processing[Processing].

### Actual result

Each status code in the 'State Code and Title' has the incorrect label in the square brackets.

### What do I think is causing it?
To find the label for the state, Magento searches through the collection `Magento\Sales\Model\ResourceModel\Order\Status\Collection`. This collection is a join between the `sales_order_status` table and the `sales_order_status_state` table. Magento selects the first record in that collection which represents the state (`module-sales/Model/Order/Config.php::90`) it's looking for, and uses that label from the status table.  This may not be the label associated to the state, but rather the label from the first status it finds associated with that state.

This is platform independent.

It may be similar to issue #9566

**Comment by IlnitskiyArtem** [comment] 2017-07-03 08:08
@matthewhaworth, Thanks for reporting this issue. 
We've created internal ticket MAGETWO-70407 to address this issue.

**Comment by barbanet** [comment] 2017-08-04 18:56
I'm not completely sure if is related but I got this result (the labels issue):

![area de trabajo 1_002](https://user-images.githubusercontent.com/392385/28982727-3f23b3be-792d-11e7-8a3d-5ab9da535fcd.png)

And also I'm not being able to associate more than 2 status to the Complete and Canceled states.
I've saw that canceled state label was replaced for the last status I've assigned:

![area de trabajo 1_003](https://user-images.githubusercontent.com/392385/28982797-6ae01cd6-792d-11e7-8a16-218f9aca4bc5.png)

I wasn't able to fix it yet. (My two cents to the issue)

**Comment by magento-engcom-team** [comment] 2017-10-10 08:30
@matthewhaworth, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-10 08:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Sales, Issue: Clear Description, Issue: Format is valid
