### ISSUE TITLE
Can't bulk update prices

### ISSUE THREAD

**Issue by popovdenis** [magento/magento2#12204] opened 2017-11-13 08:47 UTC
Don't know if this issue is already discussed.

### Preconditions

1. First of all needs to display 'Include tax' for prices in Admin > Sales.

### Steps to reproduce

1. avigate to Admin > Products > Catalog.
2. Select a few products (in my case its were virtual products).
3. In Actions dropdown select Update attributes.
4. Try to change price or special price value.

### Expected result

1. Value is not overlapping on placeholder.

### Actual result

1. ![screenshot-1](https://user-images.githubusercontent.com/2659392/32716682-95838aa0-c85f-11e7-8adf-a9da50bef791.png)
2. ![selection_016](https://user-images.githubusercontent.com/2659392/32716811-06567c2e-c860-11e7-936a-e1a547c85382.png)

**Comment by magento-engcom-team** [comment] 2017-11-13 11:59
Hello @popovdenis. Thanks for reporting. Would You please describe us making display 'Include tax' for prices in Admin > Sales in more details:  what and where exactly You have checked/unchecked, set to Yes/No or chosen.

**Comment by popovdenis** [comment] 2017-11-13 12:58
Hi team,
thanks for reply.
1. Navigate to Admin > Stores > Configuration > Sales > Tax.
2. On Tax Classes for Tax Class for Gift Options select Taxable Goods.
3. On Calculation Sales for Catalog Prices and Shipping prices select Including Tax.

**Comment by magento-engcom-team** [comment] 2017-11-14 09:34
@popovdenis, thank you for your report.
The issue is already fixed in develop branch, 2.2.1

**Closed as completed by magento-engcom-team** 2017-11-14 09:34 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
