### ISSUE TITLE
magento 2.2.2 cron:install formating incorrect

### ISSUE THREAD

**Issue by centminmod** [magento/magento2#14047] opened 2018-03-11 21:11 UTC
### Preconditions
1.  Magento 2.2.2 installed via composer
2. CentOS 7.4, PHP 7.1.15 with Zend Opcache, MariaDB 10.1.31 MySQL

### Steps to reproduce

1. installed Magento 2.2.2 via composer
2. run `bin/magento cron:install` command

### Expected result
Proper setup of cronjob with MAGENTO comment on newline

```
php $WEBROOT/bin/magento cron:install
Crontab has been generated and saved

crontab -l
11 */23 * * * /usr/local/src/centminmod/tools/autoprotect.sh 2>/dev/null
0 */4 * * * /usr/bin/cminfo_updater 2>/dev/null
#~ MAGENTO START e62ad2add6593b3556cf71a699c00f
* * * * * /usr/local/bin/php /home/nginx/domains/magento.domain.com/public/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /home/nginx/domains/magento.domain.com/public/var/log/magento.cron.log
* * * * * /usr/local/bin/php /home/nginx/domains/magento.domain.com/public/update/cron.php >> /home/nginx/domains/magento.domain.com/public/var/log/update.cron.log
* * * * * /usr/local/bin/php /home/nginx/domains/magento.domain.com/public/bin/magento setup:cron:run >> /home/nginx/domains/magento.domain.com/public/var/log/setup.cron.log
#~ MAGENTO END e62ad2add6593b3556cf71a699c00f
```

### Actual result
Missing newline for MAGENTO START comment as it's tagged on end of the last cronjob entry

```
php $WEBROOT/bin/magento cron:install
Crontab has been generated and saved

crontab -l
11 */23 * * * /usr/local/src/centminmod/tools/autoprotect.sh 2>/dev/null
0 */4 * * * /usr/bin/cminfo_updater 2>/dev/null#~ MAGENTO START e62ad2add6593b3556cf71a699c00f
* * * * * /usr/local/bin/php /home/nginx/domains/magento.domain.com/public/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /home/nginx/domains/magento.domain.com/public/var/log/magento.cron.log
* * * * * /usr/local/bin/php /home/nginx/domains/magento.domain.com/public/update/cron.php >> /home/nginx/domains/magento.domain.com/public/var/log/update.cron.log
* * * * * /usr/local/bin/php /home/nginx/domains/magento.domain.com/public/bin/magento setup:cron:run >> /home/nginx/domains/magento.domain.com/public/var/log/setup.cron.log
#~ MAGENTO END e62ad2add6593b3556cf71a699c00f
```

I could fix it manually but thought I'd submit the issue

```
crontab -l > cronjob.magento
sed -i 's|#~ MAGENTO START|\n#~ MAGENTO START|' cronjob.magento
crontab cronjob.magento
```

```
crontab -l
11 */23 * * * /usr/local/src/centminmod/tools/autoprotect.sh 2>/dev/null
0 */4 * * * /usr/bin/cminfo_updater 2>/dev/null
#~ MAGENTO START e62ad2add6593b3556cf71a699c00f
* * * * * /usr/local/bin/php /home/nginx/domains/magento.domain.com/public/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /home/nginx/domains/magento.domain.com/public/var/log/magento.cron.log
* * * * * /usr/local/bin/php /home/nginx/domains/magento.domain.com/public/update/cron.php >> /home/nginx/domains/magento.domain.com/public/var/log/update.cron.log
* * * * * /usr/local/bin/php /home/nginx/domains/magento.domain.com/public/bin/magento setup:cron:run >> /home/nginx/domains/magento.domain.com/public/var/log/setup.cron.log
#~ MAGENTO END e62ad2add6593b3556cf71a699c00f
```

### Suggestion

Maybe add an additional option for `/bin/magento cron:display` which would output the cronjob entries themselves so for scripting installs can automate adding the MAGENTO cronjobs to cron ?

**Comment by magento-engcom-team** [comment] 2018-03-12 10:30
@centminmod, thank you for your report.
The issue is already fixed in 2.3.0
But we will consider to backport the fix to patch releases

**Comment by centminmod** [comment] 2018-03-12 15:34
Cheers @magento-engcom-team much appreciated :)

**Comment by osrecio** [comment] 2018-03-24 14:35
Working on it to create a Backport for 2.2 #distributed-cd

**Comment by osrecio** [comment] 2018-03-24 14:43
@centminmod Was solved with [this commit](https://github.com/magento/magento2/commit/491ed56238c618d84fe2b6a6a5007ead43a64883#diff-3e6170893a81eae41948b1aa940dfe83) for 2.2.x, In the next minor release will be solved.

**Closed as completed by osrecio** 2018-03-24 14:43 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Event: distributed-cd
