### ISSUE TITLE
newsletter not sending 2.2.0-dev

### ISSUE THREAD

**Issue by dmcmillin** [magento/magento2#7113] opened 2016-10-20 20:10 UTC
### Preconditions
1. php 5.6  
2. magento 2.2.0-dev
3. centos 6
4. Dovecot 
5. Google Hosted Email. 
### Steps to reproduce
1. Setup as normal 2.2.0-dev
2. Put customers in and assign them to the newsletter 
3. Send out a newsletter
### Expected result

1. Should send out. 
### Actual result

1. Nothing sends out. 

I checked database and cron. It's appearing in there and says its successful. I checked logs, etc.. nothing is showing up. 
![cron edit - list magento admin](https://cloud.githubusercontent.com/assets/13723980/19576075/827bd258-96c6-11e6-8c36-7bda81b195ee.png)

On 1.9.x.x My newsletters were sent out without any difficulty. In 2.x. It seems they are not.

**Comment by lhsatch** [comment] 2016-10-21 12:07
Hi,
Have you checked with your hosting provider to see if emails/newsletters are being sent out and by which email address. If you are not using SMTP then the email address that the emails are being sent from may be being blocked.

**Comment by dmcmillin** [comment] 2016-10-21 20:17
I actually partially fixed the problem return sender as yes under configuration. However, its now doing this as following as the return email. info@xxxx.com CustomerSupport@ip-x-x-x-x.ip.secureserver.net

**Comment by lhsatch** [comment] 2016-10-21 20:30
Magnetos email is using the server user as the from address. You can ask your hosting provider to map outgoing email addresses to the address set in magento or you can get a free SMTP plugin and ask your hosting provider to send emails from SMTP.

**Comment by dmcmillin** [comment] 2016-10-21 20:48
this seems more like a bug than a hosting issue. Especially considering I had never encountered this issue in 1.9.x.x

**Comment by lhsatch** [comment] 2016-10-21 20:55
It would be interesting to find out the from address (within the email headers) your emails were being sent from before you upgraded. Some email clients such as hotmail can be quite strict as to let an unauthorised email be allowed to pass through. Setting up SMTP is the best way when dealing with php based email sending.

**Comment by dmcmillin** [comment] 2016-10-21 21:18
from address was whatever address I specified within m1. for some odd reason, m2 is sending out as if for name it's expecting an email address rather than a name.

**Comment by lhsatch** [comment] 2016-10-21 21:45
I bet magento 1 was sending emails out using serverusername@serverdetails,com but you would never know unless you checked the email logs with the hosting provider. I stumbled across this when a client said that customers that have hotmail emails were not receiving order detail emails but other customers were . Further investigations led to finding out the email from the header was actually using the server name and server as the email from address. One of the issues with this is that if too many get sent to hotmail then hotmail will blacklist the email address and won't let any emails pass through. SMTP is the really only way to make sure emails are sending out correctly.

**Comment by dmcmillin** [comment] 2016-10-25 18:49
Weirdly enough you're semi right. Magento is not attempting to utilize -f to send mail as from in exim. Which is causing the issue.

**Comment by veloraven** [comment] 2016-10-27 11:40
@dmcmillin thank you for report.
I'm closing this issue as duplicate of #6975 as according to your comments they both have the same reason.

**Closed as completed by veloraven** 2016-10-27 11:40 UTC

**Comment by AgenturSchroeder** [comment] 2016-12-09 14:26
Hi,
Im sorry but is it possible to reopen this problem?

I have the same problem with magento 2.1.2.

**Comment by Magento-baby** [comment] 2017-08-16 05:28
I have the same problem with magento 2.1.6
