### ISSUE TITLE
Checkout - Conflict in the discount label

### ISSUE THREAD

**Issue by ghost** [magento/magento2#32942] opened 2021-05-05 02:50 UTC
Hey guys,

The checkout is applying the title of the block totals "discount" in the wrong way.

If there is a third-party block in totals_segment containing "discount" as part of the code and it comes before the discount, it is applied instead. (Attachment "checkout-discount.jpg")

Analyzing the code of the file "module-sales-rule/view/frontend/web/js/view/summary/discount.js", line line 60, there is a search with indexOf ('discount').

### Preconditions (*)
Magento 2.3.x, 2.4.x

### Steps to reproduce (*)
Create any module whose totals code contains "discount" and precede "discount" block.

### Expected result (*)
Ideally, change the "return segment.code.indexOf('discount') !== -1;" for "return segment.code == 'discount';" (Attachment "discount-code.jpg")

![checkout-discount](https://user-images.githubusercontent.com/55707463/117091540-00e66000-ad32-11eb-8cb5-e77d6a9c9818.jpg)
![discount-code](https://user-images.githubusercontent.com/55707463/117091547-0479e700-ad32-11eb-8ee6-d53f68b42fe8.jpg)

**Comment by dholidev** [comment] 2021-05-05 02:53
@felipeSoulmkt, pode acompanhar.

**Comment by felipeSoulmkt** [comment] 2021-05-05 02:58
perfeito @dholidev, obrigado pela ajuda

**Comment by engcom-Lima** [comment] 2021-05-27 12:53
Hi @dholidev,

Unfortunately can't reproduce, Can you please provide me more reproducible steps e.g. which module you are using?

It would be helpful for me in debugging if you can give me more details.

**Comment by eloom** [comment] 2021-05-27 17:57
Hi @engcom-Lima,

I cannot provide the module, but we have an assembled environment.

We have a Magento discount rule "Desconto (10 OFF)" and the discount that our payment module offers when the credit card purchase is made in a single payment "Desconto à vista".

Please enter this address "https://m2.eloom.com.br/customer/account/login/", with this access data "m2@eloom.com.br / Papa1mage2to", go to the checkout, choose any shipping method and in the payment choose "Terminado in 1111 (expires: 2023/11)" and in the parcels leave the first one selected.

Note that in the review, both blocks have "Desconto à vista". In the console, type "window.checkoutConfig.totalsData.total_segments" and see that the block "eloom_discount" comes before "discount" (must come before).

This is because of the indexOf of the file "module-sales-rule/view/frontend/web/js/view/summary/discount.js".

Please tell me if you need my help.

Thanks.

**Comment by engcom-Lima** [comment] 2021-05-31 07:40
Hi @dholidev 

I checked your instance and saw the response in console same which you mentioned in your ticket.

Can you confirm me one thing? your concern is label should be "Desconto (10 OFF)" instead of "Desconto à vista"? Am i right?

**Comment by eloom** [comment] 2021-05-31 15:40
Hi @engcom-Lima 

Yes, "Desconto (10 OFF)".

If you change the javascript code I mentioned to "return segment.code == 'discount';", both discounts will be correct.

**Comment by engcom-Lima** [comment] 2021-06-02 14:21
Hi @dholidev 

One more thing please confirm, We have created magento discount rule "Discount (10 OFF)". It is applied as per expected. here i have one more question, it is necessary to install any payment offer module to reproduce this? if yes then tell me about the same so that i can install and try to reproduce for you.

**Comment by eloom** [comment] 2021-06-02 16:28
Hi @engcom-Lima,

we cannot provide the payment module causing the conflict.

**Comment by engcom-Lima** [comment] 2021-06-14 09:23
Hi @dholidev

As far as it is not an magento issue, it may be due to your payment module specific only. We had worked on the ticket and can't reproduce the issue so We need the reproducible steps. Hence we are closing this ticket.

Please feel free to raise the new ticket or reopen the existing ticket in case of any issue.

Thanks for the understanding !

**Comment by engcom-Lima** [comment] 2021-06-14 09:24
Hi @dholidev

As far as it is not an magento issue, it may be due to your payment module specific only. We had worked on the ticket and can't reproduce the issue so We need the reproducible steps. Hence we are closing this ticket.

Please feel free to raise the new ticket or reopen the existing ticket in case of any issue.

Thanks for the understanding !

**Closed as completed by engcom-Lima** 2021-06-14 09:23 UTC
Labels: Progress: needs update, Triage: Dev.Experience, Issue: ready for confirmation

**Comment by dholidev** [comment] 2021-06-14 15:44
Hi @engcom-Lima,

The problem lies in Magento's poorly written code logic when using the "indexOf()" method, reported in the first thead. It is not in the payment module.

We will provide this link to agencies and developers using our solution and they will know which side the problem is on.

Thanks for your attention.

**Comment by eloom** [comment] 2021-06-14 22:08
@felipeSoulmkt,

conforme pode ver em 2 theads acima, o suporte do Magento finalizou o ticket informando que o problema não está no Magento porque não conseguiu reproduzir o erro em razão de não fornecemos o módulo de pagamento a eles, mesmo montando um ambiente e dando acessos para testarem.

Se analisar o primeira thead deste chamado em que reportamos o problema e com o mínimo conhecimento de lógica de programação, verá que ao varrer o array de segmentos dos totais usando um "indexOf()" é o causador do conflito, visto que qualquer string contendo "discount" satisfaz a busca no trecho de código.

Não iremos alterar os nomes dos blocos de desconto no nosso módulo de pagamento porque o problema está no código mal escrito do Magento.

Abraço
