### ISSUE TITLE
United State's States not populating when adding new Tax Rule

### ISSUE THREAD

**Issue by gauravharshranosys** [magento/magento2#37650] opened 2023-06-21 15:53 UTC
### Preconditions and environment

- Magento version: >= 2.4.6
- Screenshot References attached
Tax Zones and Rates
![image](https://github.com/magento/magento2/assets/47966694/9733d775-c737-47c1-813b-503859284383)

Tax Rules
![image](https://github.com/magento/magento2/assets/47966694/37b8eabc-dfd1-4522-979d-26fa4089ccda)
![image](https://github.com/magento/magento2/assets/47966694/c06d0363-ae17-455d-a0aa-0d755563b90f)

### Steps to reproduce

Example:
  1. Navigate to Admin > Stores > Tax Zone and Rates .
  2. Create/Edit any row, and select US country.
  3. Then the State dropdown will be changeable, select any state and fill in other details.
  4. Navigate to Admin > Stores > Tax Rules.
  5. Create/Edit any row.
  6. Click on the edit action of the tax rate list and choose the rate where the US country and any state were configured.
 

### Expected result

The configured state should be auto-selected.

### Actual result

The asterisk (*) value is selected even if any state is configured.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-06-22 08:09
Hi @gauravharshranosys,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**


- Navigate to Admin > Stores > Tax Zone and Rates .
- Create/Edit any row, and select US country.
- Then the State dropdown will be changeable, select any state and fill in other details.
- Navigate to Admin > Stores > Tax Rules.
- Create/Edit any row.
- Click on the edit action of the tax rate list and choose the rate where the US country and any state were configured.


The Configured state is getting auto-selected.

<img width="1198" alt="Screenshot 2023-06-22 at 1 27 18 PM" src="https://github.com/magento/magento2/assets/51680745/ed601150-0973-4b52-a1c5-54168ce61bb3">



<img width="1341" alt="Screenshot 2023-06-22 at 1 27 37 PM" src="https://github.com/magento/magento2/assets/51680745/ed70377e-3d02-4ef6-8bed-2ebc5d747224">



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-07-06 05:37
Hi @gauravharshranosys,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-07-06 05:37 UTC
Labels: Issue: needs update, Reported on 2.4.6
