### ISSUE TITLE
Incorrect Item Count on Catalog Search Pages

### ISSUE THREAD

**Issue by hewgim** [magento/magento2#36404] opened 2022-10-31 19:05 UTC
### Preconditions and environment

Magento 2.4.5-p1
 Set Stores->Config->Catalog->Inventory->Stock Options->Show Out Of Stock Products = Yes

### Steps to reproduce

On a clean install on Magento 2.4.5-p1 with sample data, enter "Marco" as the search string

### Expected result

A single product Marco Lightweight Active Hoodie is displayed and an Item count of 1

### Actual result

A single product Marco Lightweight Active Hoodie is displayed and an Item count of 181 !

### Additional information

I debugged the code and it appears there may be a bug in the plugin vendor/magento/module-inventory-catalog/Plugin/Catalog/Block/ProductList/UpdateToolbarCount.php in the following method

```
    public function afterGetTotalNum(Toolbar $subject, int $result): int
    {
        if ($this->stockConfiguration->isShowOutOfStock()) {
            try {
                $currentCategory = $this->layerResolver->get()->getCurrentCategory();
                $category = $this->categoryFactory->create()->load($currentCategory->getEntityId());
                $defaultScopeId = $this->storeManager->getWebsite()->getCode();
                $stock_id = (int) $this->stockRegistry->getStock($defaultScopeId)->getStockId();
                $skus = [];
                $items = $category->getProductCollection()->getItems();
                array_walk(
                    $items,
                    function ($item) use (&$skus) {
                        array_push($skus, $item->getSku());
                    }
                );
                $salableProducts = $this->areProductsSalable->execute($skus, $stock_id);
                if ($salableProducts) {
                    $result = count($salableProducts);
                }
            } catch (\Exception $e) {
                $this->logger->critical($e->getMessage());
            }
        }
        return $result;
    }
```

This method gets called when a frontend search is performed. You can see that this code only gets called if Show Out Of Stock Products is set to true. It then executes logic based on the current category which does not seem to be logical for a catalog search page. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hewgim** [comment] 2022-10-31 19:06
@magento give me 2.4-develop instance

**Comment by hewgim** [comment] 2022-10-31 23:17
@magento give me 2.4-develop instance

**Comment by hewgim** [comment] 2022-10-31 23:36
I can confirm that the issue is reproducible on the 2.4-develop instance. See image.
<img width="1288" alt="Screenshot 2022-10-31 at 23 28 30" src="https://user-images.githubusercontent.com/24464795/199129068-2eb76058-3c57-406f-9229-a8f9a88aa256.png">

**Comment by paulhaidon** [comment] 2022-11-01 10:53
@magento give me 2.4-develop instance

**Comment by paulhaidon** [comment] 2022-11-01 11:59
I span up a test environment to try and recreate an issue we have experienced relating to stock control on our freshly upgraded 2.4.5-p1.. the issue is not directly linked with searching though. Instead, it is when you are trying to save a simple product within a configurable product from out of stock, to in stock again.

Editing a simple product within a configurable product:
1. Set simple product stock to zero
2. Product out of stock reflected instantly on frontend
3. Set more stock against simple product within a configurable product
4. Product out of stock remains on the frontend

Expected result:
1. Set simple product stock to zero
2. Product out of stock reflected instantly on frontend
3. Set more stock against simple product within a configurable product
4. Product should appear in stock

Unable to reproduce in the test environment created above though.

**Comment by hewgim** [comment] 2022-11-01 13:09
Hi @paulhaidon, I'm sorry but I have to disagree with you. The error appears directly when searching, but you have to have to have the configuration Stores->Config->Catalog->Inventory->Stock Options->Show Out Of Stock Products = Yes. You can see from the screenshot I attached for the search "Marco" that 1 item is returned (I put one marco product into stock), yet the number of items displays as 47. This was done on the magento instance that was given to me. Regards Mark

**Comment by paulhaidon** [comment] 2022-11-01 13:19
Sorry I think you may have misunderstand what I was saying - I was not saying your issue doesn't exist, I was merely highlighting that I was also having an issue similar which related to the stock inventory, but in my case it was when we updated a product when we changed it from out of stock. 

To avoid creating a new bug for what I thought could have been a similar issue, I added my comments here. 

But as I said, I couldn't replicate the issue in a new instance the bot gave me so left the comment there in case others found similar.

**Comment by engcom-November** [comment] 2022-11-03 07:23
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-11-03 09:05
Verified the issue on Magento 2.4-develop instance and the issue is reproducible.
Incorrect count is displayed on Catalog Search results page while searching for the products using search term. Hence confirming this issue.
![image](https://user-images.githubusercontent.com/60198231/199682287-eeffac11-1ba5-4835-a6f8-bb352bcddb5b.png)

**Comment by norgeindian** [comment] 2022-12-07 10:05
We're facing the same issue for categories with active filters.
There, the `afterGetTotalNum` method also does not calculate the correct item count.

**Comment by Kannakiraj123** [comment] 2022-12-21 09:47
@magento I am working on this

**Comment by Kannakiraj123** [comment] 2022-12-22 05:12
@magento give me 2.4-develop instance

**Comment by Kannakiraj123** [comment] 2022-12-22 05:18
This instance ask Two-Factor Authorization.

**Comment by Kannakiraj123** [comment] 2022-12-22 06:54
@magento give me 2.4-develop instance

**Comment by Kannakiraj123** [comment] 2022-12-22 11:32
I cant reproduce this issue at 2.4.develop

I followed  below steps

1.Set Stores->Config->Catalog->Inventory->Stock Options->Show Out Of Stock Products = Yes
2.I set "Out of stock" status to all simple product of Marco Lightweight Active Hoodie (parent sku MH13) except one simple product "Marco Lightweight Active Hoodie-XS-Blue"

<img width="1792" alt="Screenshot 2022-12-22 at 4 56 50 PM" src="https://user-images.githubusercontent.com/88073031/209125496-ee33c709-85e1-48b4-b212-a31fb6859a0e.png">

**Comment by Kannakiraj123** [comment] 2023-01-02 08:03
@magento give me 2.4-develop instance

**Comment by Kannakiraj123** [comment] 2023-01-02 11:39
This issue will resolve , if we change code in the plugin vendor/magento/module-inventory-catalog/Plugin/Catalog/Block/ProductList/UpdateToolbarCount.php in the following method


`public function afterGetTotalNum(Toolbar $subject, int $result): int
    {
        if ($this->stockConfiguration->isShowOutOfStock()) {
            try {
                $defaultScopeId = $this->storeManager->getWebsite()->getCode();
                $stock_id = (int) $this->stockRegistry->getStock($defaultScopeId)->getStockId();
                $skus = [];
                $items = $subject->getCollection()->getItems();
                array_walk(
                    $items,
                    function ($item) use (&$skus) {
                        array_push($skus, $item->getSku());
                    }
                );
                $salableProducts = $this->areProductsSalable->execute($skus, $stock_id);
                if ($salableProducts) {
                    $result = count($salableProducts);
                }
            } catch (\Exception $e) {
                $this->logger->critical($e->getMessage());
            }
        }
        return $result;
    }`

**Comment by Kannakiraj123** [comment] 2023-01-23 02:26
@magento give me 2.4.develop instance

**Comment by Kannakiraj123** [comment] 2023-01-23 02:26
@magento give me 2.4-develop instance

**Comment by iwanzijderveld** [comment] 2023-02-09 10:56
Any news on this? Seems to me the plugin can be removed entirely.

**Comment by vacla** [comment] 2023-03-01 08:34
Any clue what the issue is/was here, we have the same issue for different projects we are working on.

**Comment by shmVan** [comment] 2023-03-23 14:57
@magento I am working on this

**Comment by simthax** [comment] 2023-03-23 19:15
Isn't it fixed with [ACSD-48234](https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/support-tools/patches/v1-1-25/acsd-48234-catalog-search-result-shows-incorrect-category-item-count-when-show-out-of-stock-option-enabled.html?lang=en)? We had the same issue and this patch has fixed it

**Comment by glo80326** [comment] 2023-06-06 11:00
@magento give me 2.4.develop instance

**Comment by glo80326** [comment] 2023-06-06 11:02
@magento give me 2.4.develop instance

**Closed as completed** 2023-06-20 14:28 UTC
Labels: Component: Search, Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Search, Reported on 2.4.5-p1

**Comment by engcom-Bravo** [comment] 2023-06-21 06:12
Hello,

"The internal team has verified this issue & its no longer reproducible".We have cancelled the JIRA from our end.


Thanks.

**Comment by norgeindian** [comment] 2023-08-07 09:09
@engcom-Bravo , can you tell me, in which PR this is fixed and in which version the fix will be included?

**Comment by norgeindian** [comment] 2023-09-11 08:31
@engcom-Bravo , I don' really see, where this issue is fixed. Could you link the fitting PR?

**Comment by engcom-Bravo** [comment] 2023-09-11 12:33
Hi @norgeindian,

Could you please check these commits : https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-748&type=commits


Thanks.
