### ISSUE TITLE
Minicart uses module-weee template instead of module-tax

### ISSUE THREAD

**Issue by ghost** [magento/magento2#5616] opened 2016-07-13 12:05 UTC
https://github.com/magento/magento2/blob/2.1/app/code/Magento/Tax/Plugin/Checkout/CustomerData/Cart.php#L69

When prices are set to show both excl. and incl. VAT the template used is:
`$this->itemPriceRenderer->setTemplate('checkout/cart/item/price/sidebar.phtml');`

It uses the template from the WEEE module although I don't have WEEE enabled in the backend. They both share the same path and filename so I guess the WEEE module gets used as it is instantiated later than the tax module.

Is this intentional or will it be corrected in future versions?

**Comment by veloraven** [comment] 2016-08-02 10:54
@rasmuswikman thank you for your report.
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by ghost** [comment] 2016-08-09 08:39
We're using Magento 2.1 CE.

**Comment by magento-engcom-team** [comment] 2017-11-29 14:19
@rasmuswikman, thank you for your report.
The issue is already fixed in develop branch, 2.1.10, 2.2.1

**Closed as completed by magento-engcom-team** 2017-11-29 14:19 UTC
Labels: bug report, Component: Tax, Issue: Confirmed, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid
