### ISSUE TITLE
Flat rate not showing 

### ISSUE THREAD

**Issue by jotakar** [magento/magento2#25888] opened 2019-12-03 19:06 UTC
Hello
Magento 2.3.3 (just one store and default store view )
I set Flat Rate but the option doesn't appear when shopping. 
Others shipping methods works fine, and they are shown right.
I'm sure the setting parameters are OK. I tested and check each and every value in config tab for this shipping method. 
Please any fix for this bug?
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by jotakar** [comment] 2019-12-03 19:13
Hello again
Cannot understand the way to send a issue, I repeat
Magento 2.3.3 witth just one store
Flat Rate does not shown, even if it has been set right.
Following m2-assistant I write this line (but I dont understand why I have do this)
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment] 2019-12-03 19:14
Hi @jotakar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-12-03 19:14
Hi @jotakar, here is your [Magento instance](https://i-25888-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25888-2-3-develop.instances.magento-community.engineering/admin](https://i-25888-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jotakar** [comment] 2019-12-03 19:15
OOh, I've seen the light. Now.

**Comment by jotakar** [comment] 2019-12-03 19:26
I can not reproduce this issue. In vainilla all is OK
My magento has mageplaza shippingrules module

**Comment by engcom-Echo** [comment] 2019-12-04 09:18
Hello @jotakar 

Could you provide more details for reproduce this issue?
Please add steps to reproduce and screenshots of settings.

Thank you!

**Comment by jotakar** [comment] 2019-12-04 10:05
Thanks.
My magento has the Shipping Restriction(MagePlaza) extension installed, with just a rule for hidding table rate shipping for amounts below €70, and it works fine.
I have enabled Table Rate and it is shown properly. The carrier shipping is shown properly too. I searched every setup.
I atttach the flat rate config:
![Snap11](https://user-images.githubusercontent.com/18536565/70132807-35f60b00-1685-11ea-92e2-3b907e8df1b5.png)

**Comment by engcom-Echo** [comment] 2019-12-04 15:07
Hello @jotakar 

Thank you for your report and collaboration!
We are not able to reproduce this issue on the 2.3-develop branch by provided steps.

**Testing scenario:**

**Preconditions:**

1. Some product is created.
2. Flat Rate is enabled and configured

**Steps to reproduce:**

1. Add product to cart
2. Go to Shopping Cart
3. Click on the "Proceed to Checkout" button

**Result**
Flat Rate is shown. 
![Screenshot from 2019-12-04 16-42-20](https://user-images.githubusercontent.com/51681435/70152685-568a8900-16b6-11ea-8fb8-eccdb555d133.png)
![Screenshot from 2019-12-04 16-42-42](https://user-images.githubusercontent.com/51681435/70152692-5ab6a680-16b6-11ea-8522-0d61f829746a.png)

This is related with Mageplaza Shipping Rules module which is third party extension and not included in magento by default.
Please refer to the [Mageplaza support](https://mageplaza.freshdesk.com/support/login), for advice or general discussion about this issue.

So I have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Echo** 2019-12-04 15:07 UTC
Labels: Issue: Format is not valid, Component: Bundled Extension

**Comment by jotakar** [comment] 2019-12-04 17:00
That's the problem, demos o vainilla doesn't show the error. 
The Shipping Restriction(MagePlaza) doesn't seem to be the problem. I disabled it and the problem keeps on.
I dont know if there is another parameter or config set that affects shipping method. Is there any other way to disble or enabled shipping methods apart of the stores->config->sales?

Thanks for your answer.

**Comment by engcom-Echo** [comment] 2019-12-05 08:32
Hello @jotakar 

Try to check Cart Price Rules and clear cache.

**Comment by jotakar** [comment] 2019-12-05 09:31
?? I cannot find any parameter related to shipping methods in Cart Price Rules, just one actin about abply or not free shiping.

**Comment by engcom-Echo** [comment] 2019-12-05 10:24
Hello @jotakar 

I have default the Flat Rate settings and it works fine. I don`t have any Cart Price Rules which is hiding the Flat Rate from frontend.
If without the Shipping Restriction(MagePlaza) module and with the default settings Flat Rate will display and work properly, please refer to the [Mageplaza support](https://mageplaza.freshdesk.com/support/login), for advice or general discussion about this issue.

Thank you for report!
