### ISSUE TITLE
Magento 2.3 Wrong product url for anchor categories for multiple storeviews

### ISSUE THREAD

**Issue by juharintanen** [magento/magento2#25124] opened 2019-10-17 17:59 UTC
### Preconditions (*)

1. Magento 2.3.2

### Steps to reproduce (*)

1. Regenerate new url rewrite for product

### Expected result (*)

1. All product urls with categories are genereted accordingly by correct store view

### Actual result (*)

1. Product urls that are generated from anchor categories are missing StoreId and are generated wrong.

Underlined $storeId is missing and needs to be added in code.

![image](https://user-images.githubusercontent.com/16240211/67034700-d5386080-f120-11e9-8da0-3556c8b4e6d4.png)

**Comment by hostep** [comment] 2019-10-17 19:57
This is most likely a duplicate of https://github.com/magento/magento2/issues/11615, but I'm leaving it open, because this problem definitely needs a lot more attention.

We are awaiting for many months now on https://github.com/magento/magento2/pull/20826 finally getting approved...

**Comment by engcom-Delta** [comment] 2019-10-31 08:22
@juharintanen thank you for your report. This this known issue and PR for it is already created. 
@hostep I mark this issue as duplicate and close it.  You could reopen it if PR won't be merged or issue will appears in the future

Duplicate of [#11615](https://github.com/magento/magento2/issues/11615)

**Closed as completed by engcom-Delta** 2019-10-31 08:22 UTC
Labels: Component: CatalogUrlRewrite, duplicate, Issue: Format is valid, Fixed in 2.4.x

**Comment by slavvka** [comment] 2020-03-17 05:17
Hi @juharintanen. Thank you for your report. 
The issue has been fixed in magento/magento2#26784 by @hostep in 2.4-develop branch
Related commit(s):
 - [cb685d15b2b590bdb4d99a3d4ebe563037d0aa31](https://github.com/magento/magento2/commit/cb685d15b2b590bdb4d99a3d4ebe563037d0aa31)
 - [acb8642c44d1ecb60ad023c81f6541fa9ebae47d](https://github.com/magento/magento2/commit/acb8642c44d1ecb60ad023c81f6541fa9ebae47d)
 - [97258e1a9ce97ad32971731eceac8fee32f66b74](https://github.com/magento/magento2/commit/97258e1a9ce97ad32971731eceac8fee32f66b74)
 - [6cf26dc19e2f80f0c2da445443d0b48a1974fc77](https://github.com/magento/magento2/commit/6cf26dc19e2f80f0c2da445443d0b48a1974fc77)
 - [0b941218dcc86dcbd518f5400934e995ad1f2e3c](https://github.com/magento/magento2/commit/0b941218dcc86dcbd518f5400934e995ad1f2e3c)
 - [b0c0c59900b4ddf8d70cf2ae9c9ec12805d13908](https://github.com/magento/magento2/commit/b0c0c59900b4ddf8d70cf2ae9c9ec12805d13908)
 - [28fa34531f4c7cd4bcad46500ba027b9b58ff297](https://github.com/magento/magento2/commit/28fa34531f4c7cd4bcad46500ba027b9b58ff297)
 - [bf514b0b435a75f5688f56f8e9465af9bb3284c1](https://github.com/magento/magento2/commit/bf514b0b435a75f5688f56f8e9465af9bb3284c1)

The fix will be available with the upcoming 2.4.0 release.
