### ISSUE TITLE
My site magento 2.3 ver paypal checkout is not working

### ISSUE THREAD

**Issue by haroonsulahri** [magento/magento2#35947] opened 2022-08-14 16:17 UTC
Hi
I am faicing a problem many days.My site checkout working fine but when i move to paypal site and when i put payer acount then paypal refreshing automatically and show error msg.
"To comply with international regulations, this transaction has been declined."
And i've contact paypal but paypal team say this not a paypal error this your magnto site error.And i've changed account but the issue not fixed.My site magento version is ver. 2.3.7-p3 .Please help me this issue.
Thank You
Regards
Haroon Sulehri

**Comment by haroonrajpoot** [comment] 2022-08-14 16:17
https://www.paypal.com/checkoutweb/genericError?code=Q09NUExJQU5DRV9WSU9MQVRJT04%3D&cancelLink=&merchantName=

**Comment by haroonrajpoot** [comment] 2022-08-14 16:17
Error link above

**Comment by engcom-Hotel** [comment] 2022-08-17 11:28
Hello @haroonsulahri 

Thank you for your report.

It seems to be a configuration issue for us. To speed up the processing of this issue, please provide us with the following information:

- Summary of the issue
- Information on your environment
- Steps to reproduce
- Expected and actual results

Thanks

**Comment by engcom-Hotel** [comment] 2022-09-01 06:44
Dear @haroonsulahri,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-09-01 06:44 UTC
Labels: Triage: Dev.Experience, Issue: needs update
