### ISSUE TITLE
Unable to view/edit grouped product in admin

### ISSUE THREAD

**Issue by molovo** [magento/magento2#26031] opened 2019-12-13 16:58 UTC
### Preconditions (*)

1. Magento EE 2.3.3
2. PHP 7.2.25

### Steps to reproduce (*)

1. Create a grouped product
2. Edit grouped product in back end

### Expected result (*)

1. Product edit form is shown

### Actual result (*)

1. The following error appears:
```
Fatal error: Uncaught TypeError: Argument 2 passed to Magento\Framework\Stdlib\ArrayManager::set() must be of the type array, null given, called in /Users/molovo/projects/bmc/vendor/magento/module-catalog-staging/Ui/DataProvider/Product/Form/Modifier/ScheduleDesignUpdate.php on line 60 and defined in /Users/molovo/projects/bmc/vendor/magento/framework/Stdlib/ArrayManager.php:72 Stack trace: #0 /Users/molovo/projects/bmc/vendor/magento/module-catalog-staging/Ui/DataProvider/Product/Form/Modifier/ScheduleDesignUpdate.php(60): Magento\Framework\Stdlib\ArrayManager->set('data/config/lab...', NULL, 'Design') #1 /Users/molovo/projects/bmc/vendor/magento/module-catalog/Ui/DataProvider/Product/Form/ProductDataProvider.php(73): Magento\CatalogStaging\Ui\DataProvider\Product\Form\Modifier\ScheduleDesignUpdate->modifyMeta(Array) #2 /Users/molovo/projects/bmc/vendor/magento/framework/View/Element/UiComponentFactory.php(316): Magento\Catalog\Ui\DataProvider\Product\Form\ProductDataProvider->getMeta() #3 /Users/molovo/projects/bmc/vend in /Users/molovo/projects/bmc/vendor/magento/framework/Stdlib/ArrayManager.php on line 72
```

**Comment by ajijshekh123** [comment] 2019-12-13 17:16
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2019-12-13 17:16
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-12-13 17:17
Hi @ajijshekh123, here is your [Magento instance](https://i-26031-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26031-2-4-develop.instances.magento-community.engineering/admin](https://i-26031-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2019-12-13 17:27
@molovo - It is proper working on Default Magento 2.4 Verison.
If you face an issue on your end. Please upload the video or screenshot.

Thanks.

**Comment by molovo** [comment] 2019-12-16 09:54
@ajijshekh123 here's a screenshot of the error received when visiting the admin detail page.

![Screenshot 2019-12-16 at 09 53 34](https://user-images.githubusercontent.com/2746289/70897146-f961d200-1fe9-11ea-99f4-71552bf36d1c.jpg)

The code used to generate the product is as follows:

```php
private function createGroupedProduct(ProductInterface $product, ConfigurationInterface $configuration): ?ProductInterface
{
    // Add bike product
    $child    = null;
    $children = $product->getTypeInstance()->getUsedProducts($product);
    foreach ($children as $option) {
        $swatches = $this->swatchHelper->getSwatchesByOptionsId([$option->getSize()]);
        $swatch   = array_pop($swatches);
        if ($swatch && $swatch['value'] === $configuration->getSize()) {
            $child = $option;
        }
    }

    if (!$child) {
        return null;
    }

    try {
        /** @var ProductInterface $groupedProduct */
        $groupedProduct = $this->productFactory->create();
        $groupedProduct->setSku($child->getSku().'-configuration-'.$configuration->getId());
        $groupedProduct->setUrlKey($child->getSku().'-configuration-'.$configuration->getId());
        $groupedProduct->setTypeId(Grouped::TYPE_CODE);
        $links = [];

        $link = $this->productLinkFactory->create()
            ->setSku($groupedProduct->getSku())
            ->setLinkedProductSku($child->getSku())
            ->setLinkType('associated');
        $link->getExtensionAttributes()
            ->setQty(1);
        $links[] = $link;

        // Add cone product
        $link = $this->productLinkFactory->create()
            ->setSku($groupedProduct->getSku())
            ->setLinkedProductSku('cone-'.$configuration->getCone())
            ->setLinkType('associated');
        $link->getExtensionAttributes()
            ->setQty(1);
        $links[] = $link;

        // Add spacer product
        $link   = $this->productLinkFactory->create()
            ->setSku($groupedProduct->getSku())
            ->setLinkedProductSku('spacer')
            ->setLinkType('associated');
        $link->getExtensionAttributes()
            ->setQty((int) $configuration->getSpacer());
        $links[] = $link;

        // Add stem product
        $link = $this->productLinkFactory->create()
            ->setSku($groupedProduct->getSku())
            ->setLinkedProductSku('stem-'.$configuration->getStem())
            ->setLinkType('associated');
        $link->getExtensionAttributes()
            ->setQty(1);
        $links[] = $link;

        $groupedProduct->setProductLinks($links);
        $groupedProduct->save();

        return $groupedProduct;
    } catch (\Exception $e) {
        $this->logger->critical($e->getMessage(), json_decode(json_encode($e), true));
    }

    return null;
}
```

The products are correctly generated, and appear in the admin listing, but I cannot view or edit them.

**Comment by ajijshekh123** [comment] 2019-12-16 11:42
Hi @molovo,
This issue may be related to your customization code or Third-party integration.
Thanks.

**Comment by molovo** [comment] 2019-12-16 12:23
@ajijshekh123 the only custom code above is the `ConfigurationInterface` object used to retrieve values. Everything else (to actually create the product) is methods from within Magento core

**Comment by molovo** [comment] 2019-12-16 12:27
Judging by the error message, it looks as though something to do with the design configuration isn't being set when the product model is created

**Comment by ajijshekh123** [comment] 2019-12-16 12:42
Yes @molovo, This issue may be happening.

**Comment by engcom-Echo** [comment] 2019-12-16 12:58
Hello @molovo 

Thank you for contribution and collaboration!
@sdzhepa Could you move this issue into  [Magento Commerce private repository](https://github.com/magento/partners-magento2ee/issues) where it could be fixed and delivered by Solution Partners Contribution Program.
[Current repository](https://github.com/magento/magento2) and [issue tracker](https://github.com/magento/magento2/issues) aimed at Magento Open Source version only and the main focus is community contribution/collaboration. It described in [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and it is a part of the issue report template:
> Verify, that the issue you are about to report does not relate to the Magento Commerce. GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub. You can report Commerce-related issues in one of two ways:
> - You can use the Support portal associated with your account
> - If you are a Partner reporting on behalf of a merchant, use the Partner portal.

**Comment by sdzhepa** [comment] 2019-12-17 15:06
Hello @engcom-Echo 

Did you try to reproduce it on the both EE(Enterprise) and CE(Open Source) editions and can confirm this is Enterprise specific?

**Comment by engcom-Echo** [comment] 2019-12-18 13:12
Hello @molovo @sdzhepa 

I am not able to reproduce this issue on the 2.4-develop branch by provided steps. 
Tested on the both EE(Enterprise) and CE(Open Source) editions.

**Testing scenario:**

**Steps to reproduce:**

1. Create a grouped product
2. Edit grouped product in back end

**Result:**
Product edit form is shown. No errors.
![Screenshot_16](https://user-images.githubusercontent.com/51681435/71088121-6d48d980-21a6-11ea-9a58-477a2691e333.png)
![Screenshot from 2019-12-18 14-35-42](https://user-images.githubusercontent.com/51681435/71088223-9f5a3b80-21a6-11ea-8b13-cc2d3641c72e.png)

So I have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Echo** 2019-12-18 13:12 UTC
Labels: Issue: Format is valid

**Comment by molovo** [comment] 2019-12-18 13:17
@engcom-Echo as I have outlined above, this issue only occurs when creating the product programatically, not when creating it through the admin area.

**Comment by engcom-Echo** [comment] 2019-12-18 15:20
Hello @molovo 

This GitHub repository is intended for bug reports in core Magento modules, in case of problems with some third party extensions/themes their respective vendors should be contacted instead.

**Comment by molovo** [comment] 2019-12-18 15:26
@engcom-Echo I am aware of this. As I also have stated above, the error is occuring within the Magento core modules, when creating a product using the code above.

**Comment by Nazar65** [comment] 2019-12-19 09:51
Hi @molovo where did you get a manual to create grouped product programmatically ? :) I think that you have an issue some where in your code, because error says that it expected to be array, but instead got null, so i think your missed some data in your code. Could you check how it works in "core" files an find the difference with your code ? or you can check integration test files to find how create  grouped product programaticaly

**Comment by kin-allan** [comment] 2020-11-05 13:21
Hey, I know it has been a long time for this post. But I was facing the same issue and realize the issue was that the **attribute_set_id** for the **catalog_product_entity** was incorrect set up. Due a mistake on my script I was insertin with the attribute_set_id as 0, instead 4.
You can check the why the issue happens here: 
`\vendor\magento\module-catalog\Ui\DataProvider\Product\Form\Modifier\Eav.php`
On method **getGroups** that relies on ATTRIBUTE_SET_ID, and if is 0 it never populate the 'design' info for $meta.

**Comment by Eddcapone** [comment] 2020-11-20 11:08
I got a similar error:

"TypeError: Argument 2 passed to Magento\Framework\Stdlib\ArrayManager::set() must be of the type array, null given, called in /home/hausfuxde/relaunch.hausfux.de/vendor/magento/module-catalog-staging/Ui/DataProvider/Product/Form/Modifier/ScheduleDesignUpdate.php on line 64"

The problem is, that in the Attribute Set I removed the attributes for Scheduled Design...

**Comment by tiwarimukesh** [comment] 2021-04-19 14:59
@Eddcapone I am also facing same issue. Could you share information in which table you did the change?

**Comment by Eddcapone** [comment] 2021-04-19 17:32
@tiwarimukesh , you can remove the attribute from the magento backend

**Comment by tiwarimukesh** [comment] 2021-04-20 04:14
Hi @kin-allan 

Could you share some more details like query how did you find out the issue and the fix.

**Comment by tiwarimukesh** [comment] 2021-04-20 07:59
@Eddcapone I do not want to delete the attribute. Is there any better solution available?

**Comment by Eddcapone** [comment] 2021-04-20 12:38
@tiwarimukesh , oh sorry. My answer was written in bad english. The problem was, that attributes were missing in the attribute group "Scheduled Design"

**Comment by tiwarimukesh** [comment] 2021-04-20 16:51
@Eddcapone Thanks

**Comment by Reno-Axel** [comment] 2021-08-09 19:04
> Hey, I know it has been a long time for this post. But I was facing the same issue and realize the issue was that the **attribute_set_id** for the **catalog_product_entity** was incorrect set up. Due a mistake on my script I was insertin with the attribute_set_id as 0, instead 4.
> You can check the why the issue happens here:
> `\vendor\magento\module-catalog\Ui\DataProvider\Product\Form\Modifier\Eav.php`
> On method **getGroups** that relies on ATTRIBUTE_SET_ID, and if is 0 it never populate the 'design' info for $meta.

Thank you this was my problem and it was the same issue in root category:
https://github.com/magento/magento2/issues/30725
