### ISSUE TITLE
Cannot change theme for the store after upgrade from 2.2.3

### ISSUE THREAD

**Issue by kerlama** [magento/magento2#14989] opened 2018-05-04 09:30 UTC
### Preconditions
1. Magento 2.2.4
2. PHP 7.0.28

### Steps to reproduce
1. Upgrade from 2.2.3
2. Login to admin go to Content > Design > Configuration
3. Edit main store (for example) and from "Applied Theme" select Luma theme.
4. Save

### Expected result
1. Theme should be successfully changed and applied to store

### Actual result
1. Error thrown

![screenshot_20](https://user-images.githubusercontent.com/4161312/39621265-6a9723ae-4f8e-11e8-91c9-6e011f638909.png)

Also, there is a strange captioned back button:

![screenshot_21](https://user-images.githubusercontent.com/4161312/39621288-8146ab10-4f8e-11e8-8040-d5770be6fbf5.png)

**Comment by hostep** [comment] 2018-05-04 10:11
@kerlama: I think you are talking about Magento 2.2.4 instead of 2.2.3? If that's the case, then this bug was already reported before in https://github.com/magento/magento2/issues/14968

If you agree this is the same issue, can you close this one, so there is only a single issue tracking the same problem, thanks!

**Comment by hostep** [comment] 2018-05-04 10:15
Ah sorry, didn't read your issue completely, you're indeed upgrading to 2.2.4. Let me close it as a duplicate of #14968 then.

**Comment by kerlama** [comment] 2018-05-04 10:16
@hostep ok, thanks :)

**Closed as completed by hostep** 2018-05-04 10:15 UTC
Labels: Issue: Format is valid

**Comment by abhisekhranjan** [comment] 2018-05-04 10:28
Update theme using terminal its working for me .

INSERT INTO `core_config_data` (`config_id`,`scope`,`scope_id`,`path`,`value`) VALUES ('19','default',0,'design/theme/theme_id',5);
or update 

UPDATE core_config_data SET value=5 where config_id=19;

**Comment by kerlama** [comment] 2018-05-04 10:30
@abhisekhranjan well, I guess that's not the proper solution :)

**Comment by abhisekhranjan** [comment] 2018-05-04 10:41
INSERT INTO `core_config_data` (`config_id`,`scope`,`scope_id`,`path`,`value`) VALUES ('19','default',0,'design/theme/theme_id',5);
or update 

UPDATE core_config_data SET value=5 where config_id=19;
Set value= as theme id listed then run the command 

php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy -f
php bin/magento indexer:reindex
php bin/magento cache:flush

chmod -R 777 var
chmod -R 777 pub
