### ISSUE TITLE
addColumn in grid creates an incomplete url without additional params

### ISSUE THREAD

**Issue by DaddyDomi** [magento/magento2#33674] opened 2021-08-03 18:08 UTC
### Preconditions (*)

1. Magento 2.4.2
2.

### Steps to reproduce (*)

1. Use  addColumn() to create new column in grid:
        $this->addColumn(
            'edit',
            [
   // (...)
             'actions' => [
                    ['url' => ['base' => '\*/\*/edit', 'params' => ['myparam' => 9 ] ], 'field' => 'entity_id'  ] ],
//(..)
            ]
        );
2. Problem source found in app/code/Magento/Backend/Block/Widget/Grid/Column/Renderer/Action.php :
The line 147 :
$params[] = $action['url']['params'];
 gives invalid data,  change this line to:
 $params = array_merge($action['url']['params'], $params);
 solving a problem 

### Expected result (*)

1. /admin/section/subsection/edit/entity_id/1/myparam/9/key/keyvalue/

### Actual result (*)

1. /admin/section/subsection/edit/entity_id/1/key/keyvalue/
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by DaddyDomi** [comment] 2021-08-03 18:56
Edit:

The line 147 :
_$params[] = $action['url']['params'];_
gives invalid data, change this line to:
_$params = array_merge($action['url']['params'], $params);_
solving a problem

**Comment by engcom-Lima** [comment] 2021-09-02 07:41
Hi @DaddyDomi,

We are not able to reproduce the issue as the information provided is not clear. Please provide more information for further analysis:
1. Can you please state what is the issue that you are facing with the current url composition ?
2. Can you please update the issue description with more specific ‘Steps to reproduce’ and results so that we can try again to understand the need for additional params in url ?

**Comment by JohnAyling1979** [comment] 2021-09-02 14:18
I was able to reproduce the issue. Using 
        $this->addColumn(
            'test',
            [
                'header' => __('Test'),
                'type' => 'action',
                'getter' => 'getId',
                'actions' => [
                    [
                        'caption' => __('Test'),
                        'url' => [
                            'base' => '*/*/Test',
                            'params' => ['myparam' => 9, 'myparam2' => 25]
                        ],
                        'field' => 'id'
                    ]
                ],
                'filter' => false,
                'sortable' => false,
                'index' => 'stores',
                'header_css_class' => 'col-action',
                'column_css_class' => 'col-action'
            ]
        );

it would create an associate array of [id => id number, 0 => ['myparam' => 9, 'myparam2' => 25]]
Doing the suggested fix created an associate array of [id => id number, 'myparam' => 9, 'myparam2' => 25]

The only correction to the initial comment would be that I found it on line 182 of app/code/Magento/Backend/Block/Widget/Grid/Column/Renderer/Action.php

**Comment by engcom-Lima** [comment] 2021-09-14 07:22
Hi @JohnAyling1979, @DaddyDomi,

Can you please update the answers for questions asked in https://github.com/magento/magento2/issues/33674#issuecomment-911326216 ?

Also can you share the whole code which you guys are using so that I can try to reproduce this on 2.4-dev instance ?

**Comment by DaddyDomi** [comment] 2021-09-15 21:17
I prepared an example module DaddyDomi_Example so that you can see the wrong effect exactly. I overwrite the grid "products in category" (Catalog-> Categories -> (select category with products) -> Products in Category). In this grid, I added a "Test" column containing a link to edit the product, but with additional parameters.
In the DaddyDomi\Example\Block\Adminhtml\Category\Tab\Product.php file, the code:

        $ this-> addColumn (
                'Test',
                [
                    'header' => __ ('Test'),
                    'type' => 'action',
                    'getter' => 'getId',
                    'actions' => [
                        [
                            'caption' => __ ('Edit product with extra params'),
                            'url' => [
                                'base' => 'catalog / product / edit',
                                'params' => ['myparam' => 9, 'myparam2' => 25]
                            ],
                            'field' => 'id'
                        ]
                    ],
                    'filter' => false,
                    'sortable' => false,
                    'index' => 'stores',
                    'header_css_class' => 'col-action',
                    'column_css_class' => 'col-action'
                ]
        );

should generate a URL with additional parameters:
catalog/product/edit/id/2046/myparam/9/myparam2/25/key/<keyvalue>/

but it generates without these additional parameters:
catalog/product/edit/id/2046/key/<keyvalue>/

Problem source found in class Magento\Backend\Block\Widget\Grid\Column\Renderer\Action 
in line 182 (@JohnAyling1979 thanks for correcting the line number):
$params[] = $action['url']['params'];

In this line it should be (and in the past it was):
$params = array_merge($action['url']['params'],$params);

[DaddyDomi.zip](https://github.com/magento/magento2/files/7173315/DaddyDomi.zip)

**Comment by engcom-Lima** [comment] 2021-09-21 07:56
Hi @DaddyDomi,

I tried with your example code and code seems to be working fine. I was able to edit product from the grid option as expected.

In order to do further analysis on the same, please update on the below queries:

1. Can you please state what is the issue that you are facing with the current url composition ? Perhaps a clear issue description would be helpful in understand as to why you need additional params in url specifically ?
2. If you can attach the screenshots of the issue that you are facing with current url composition, that would be helpful.

**Comment by DaddyDomi** [comment] 2021-09-21 19:15
Module DaddyDomi DaddyDomi_Example is just a simple example of problem. 
I need a URL with extraparams in custom module (with using method addColumn()) as :
/admin/something/item/edit/myparam/9/myparam2/25/id/2046

On Magento 2.2.7 everything is correct and URL contains extraparams but not on Magento 2.4.2

DaddyDomi_Example  on Magento 2.2.7 builds URL as (magento227_url.jpg): 
/admin/catalog/product/**edit/myparam/9/myparam2/25/id/2026/**
and this is correct. 

But this same module on Magento 2.4.2 builds URL as (magento224_url.jpg):
/admin_1fua47/catalog/product/**edit/id/2027/**
and this isn't correct - url does not contain myparam and myparam2. 


![magento227_url](https://user-images.githubusercontent.com/88398618/134233004-3fbb7efe-66a8-4c2f-b9a1-0c419146bc2c.JPG)
![magento242_url](https://user-images.githubusercontent.com/88398618/134233017-bab1c72e-5c99-47e9-ba4a-bb66e0ec13e6.JPG)

**Comment by engcom-Lima** [comment] 2021-10-20 10:54
Hi @DaddyDomi,

Looks like you got the fix based on your approach. But since this is deprecated functionality and there is an alternate way to achieve this, we are closing this issue. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Lima** 2021-10-20 10:54 UTC
Labels: Issue:  Cannot Reproduce, Triage: Dev.Experience, Issue: needs update
