### ISSUE TITLE
Fatal Error setup:di:compile in magento 2

### ISSUE THREAD

**Issue by andy17612** [magento/magento2#13005] opened 2018-01-05 06:56 UTC
### Preconditions

1. linux centos7
2. magento 2.2.2
3. php71 

### Steps to reproduce

1. 2.2.0 upgraded to 2.2.2
2. php bin/magento deploy:mode:set production <-Fatal Error
3. getting the comment is need to run php bin/magento setup:di:compile <-Fatal Error

### Expected result

1. Does anyone know how to fix it? Thank you!

### Actual result

1. 

> php -f bin/magento setup:di:compile -vvv
> Compilation was started.
> Proxies code generation... 0/7 [>---------------------------]   0% < 1 sec 34.0 Proxies code generation... 1/7 [====>-----------------------]  14% 1 sec 36.0 MiRepositories code generation... 1/7 [====>-----------------------]  14% 1 sec 36.0 MiB
> 
>   [Exception]
>   Warning: Narrowing occurred during type inference. Please file a bug report
>    on bugs.php.net in /home/xxxx/public_html/vendor/composer/ClassLoader.
>   php on line 444
> 
> 
> Exception trace:
>  () at /home/xxxx/public_html/vendor/magento/framework/App/ErrorHandler.php:61
>  Magento\Framework\App\ErrorHandler->handler() at /home/xxxx/public_html/vendor/composer/ClassLoader.php:444
>  include() at /home/xxxx/public_html/vendor/composer/ClassLoader.php:444
>  Composer\Autoload\includeFile() at /home/xxxx/public_html/vendor/composer/ClassLoader.php:322
>  Composer\Autoload\ClassLoader->loadClass() at n/a:n/a
>  spl_autoload_call() at n/a:n/a
>  class_exists() at /home/xxxx/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:122
>  Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClasses() at /home/xxxx/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:108
>  Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract() at /home/xxxx/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:79
>  Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList() at /home/xxxx/public_html/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php:61
>  Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation() at /home/xxxx/public_html/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php:56
>  Magento\Setup\Module\Di\App\Task\Manager->process() at /home/xxxx/public_html/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php:205
>  Magento\Setup\Console\Command\DiCompileCommand->execute() at /home/xxxx/public_html/vendor/symfony/console/Command/Command.php:242
>  Symfony\Component\Console\Command\Command->run() at /home/xxxx/public_html/vendor/symfony/console/Application.php:842
>  Symfony\Component\Console\Application->doRunCommand() at /home/xxxx/public_html/vendor/symfony/console/Application.php:193
>  Symfony\Component\Console\Application->doRun() at /home/xxxx/public_html/vendor/magento/framework/Console/Cli.php:104
>  Magento\Framework\Console\Cli->doRun() at /home/xxxx/public_html/vendor/symfony/console/Application.php:117
>  Symfony\Component\Console\Application->run() at /home/xxxx/public_html/bin/magento:23
> 
> setup:di:compile

**Comment by magento-engcom-team** [comment] 2018-01-05 12:08
@rigu12 Thanks for the report. We tried with a clean instance of Magento, and we weren't able to reproduce it. Please provide more information/steps in order for us to reproduce this issue. Also please clarify if you are using any 3'rd party code?

**Comment by orlangur** [comment] 2018-01-05 16:02
Hi @rigu12, thanks for bug report, it is a duplicate of https://github.com/magento/magento2/issues/12551. Feel free to share any additional information in that ticket.

**Closed as completed by orlangur** 2018-01-05 16:02 UTC
Labels: Progress: needs update, duplicate, Issue: Format is valid
