### ISSUE TITLE
Mobile product page image jumps

### ISSUE THREAD

**Issue by bondimedical3** [magento/magento2#10518] opened 2017-08-12 23:17 UTC
Preconditions: Magento version 2.1.8 on a mobile device

When you scroll down on the product page and you are about half way of the product image the page jumps up to the top. Movement should be fluid always.

Product image scrolling is not fluid on mobiles

### Preconditions
1. Magento 2.1.8
2. PHP 7.0.2

### Steps to reproduce
1. Open a product page 
2. Scroll down to approximately 50% of the image height and the page jumps back to the top. Issue also occurs when scrolling up
3. Bug is intermittent and glitchy and can take a few atrempts to reproduce. Mainly occurs when you use a flick style scroll past the 50% mark.

### Expected result
1. Product image scrolling should be fluid 

### Actual result
1. Page jumps to the top. 

Platform dependent comment
1. Mobile only

**Comment by vherasymenko** [comment] 2017-08-15 14:40
@bondimedical3 Thank you for your report.
Please use the issue reporting [guidelines ](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)to report an issue. Include the steps required to reproduce, the actual result, and the expected result.

**Comment by magento-engcom-team** [comment] 2017-09-11 18:13
@bondimedical3 we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Comment by bondimedical3** [comment] 2017-09-11 22:31
Can you guys stop closing serious bugs. Product image scrolling is not fluid on any mobile device and any M2 version. Even a 5 year child could reproduce it. Have you even bothered to check or you are too interested in red tape?

**Comment by magento-engcom-team** [comment] 2017-09-12 02:39
Hi @bondimedical3 Thank you for the response.
Please use the issue reporting guidelines to report an issue. Include the steps required to reproduce, the actual result, and the expected result. We have thousands of reported issues, so we are trying to clarify as much as we can before pushing it to the core developers or community developers to let them fix as many issues as they can.
Please update the issue according to our requirements and we or Magento Community will be more than happy to fix it. Thank you for collaboration

**Comment by bondimedical3** [comment] 2017-09-12 02:51
Product image scrolling is not fluid on mobiles

### Preconditions
1. Magento 2.1.8
2. PHP 7.0.2

### Steps to reproduce
1. Open a product page 
2. Scroll down to approximately 50% of the image height and the page jumps back to the top. Issue also occurs when scrolling up
3. Bug is intermittent and glitchy and can take a few atrempts to reproduce. Mainly occurs when you use a flick style scroll past the 50% mark.

### Expected result
1. Product image scrolling should be fluid 

### Actual result
1. Page jumps to the top. 

Platform dependent comment
1. Mobile only

**Comment by magento-engcom-team** [comment] 2017-09-12 02:56
@bondimedical3 thank you for update

**Comment by magento-engcom-team** [comment] 2017-09-28 14:30
@bondimedical3, thank you for your report.
We've created internal ticket(s) MAGETWO-80325 to track progress on the issue.

**Comment by dowittwer** [comment] 2018-02-20 07:42
@bondimedical3 if you are still interested in a fix, put this in your css (or in the gallery.less):
`.fotorama__stage__frame.fotorama__active {
  position: static;
}`

**Comment by bondimedical3** [comment] 2018-02-21 03:20
I added the css to my Theme but the image still jumps. Did I do something wrong?

![mobile](https://user-images.githubusercontent.com/10808588/36461582-69c62e84-1712-11e8-9324-0492fba9591b.jpg)

**Comment by dowittwer** [comment] 2018-02-21 07:11
there should be no space between .fotorama__stage__frame and .fotorama__active it has t be like this: fotorama__stage__frame.fotorama__active

**Comment by bondimedical3** [comment] 2018-02-21 07:40
I tried that and the result was the same.

**Comment by dowittwer** [comment] 2018-02-21 07:56
you could try `position: static !important;`
if that doesnt help, your fotorama config for the classes is probably different from mine

**Comment by bondimedical3** [comment] 2018-02-22 04:16
No, its still not working. This is the webpage - https://www.extenderstore.com.au/test-product.html

**Comment by magento-engcom-team** [comment] 2018-12-10 12:11
Hi @TomashKhamlai. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-01-08 15:43
Hi @engcom-backlog-tomash. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-01-08 15:44
@engcom-backlog-tomash Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97496`, `MAGETWO-97497` were created

**Comment by amjadm61** [comment] 2019-06-12 13:11
@magento give me test instance

**Comment by amjadm61** [comment] 2019-06-12 13:14
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-06-12 13:14
Hi @amjadm61. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-06-12 13:15
Hi @amjadm61, here is your [Magento instance](https://i-10518-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-10518-2-3-develop.instances.magento-community.engineering/admin](https://i-10518-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by APanteleychuk** [comment] 2019-09-27 09:38
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-09-27 09:38
Hi @APanteleychuk. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-09-27 09:38
Hi @APanteleychuk, here is your [Magento instance](https://i-10518-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-10518-2-3-develop.instances.magento-community.engineering/admin](https://i-10518-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by slavvka** [comment] 2020-02-07 23:13
Hi @bondimedical3. Thank you for your report. 
The issue has been fixed in magento/magento2#25385 by @krzksz in 2.4-develop branch
Related commit(s):
 - [0b278c84278cb42f03083a4115763d3ed5c7dd52](https://github.com/magento/magento2/commit/0b278c84278cb42f03083a4115763d3ed5c7dd52)
 - [d74f73c7272887c68d595fafd25d997c815758e1](https://github.com/magento/magento2/commit/d74f73c7272887c68d595fafd25d997c815758e1)
 - [80b8514a601923b66abb8492e0868ad7fb5dfb1f](https://github.com/magento/magento2/commit/80b8514a601923b66abb8492e0868ad7fb5dfb1f)
 - [c5991d3c719d68f66c64f5f10978b6412021165c](https://github.com/magento/magento2/commit/c5991d3c719d68f66c64f5f10978b6412021165c)
 - [acdc9b429bfab2a9aa496f571d9ccc37d0b6492d](https://github.com/magento/magento2/commit/acdc9b429bfab2a9aa496f571d9ccc37d0b6492d)

The fix will be available with the upcoming 2.4.0 release.

**Closed as completed** 2020-02-07 23:13 UTC
Labels: Issue: Ready for Work, Component: Catalog, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Fixed in 2.4.x
