### ISSUE TITLE
Customer logged out automatically in checkout process

### ISSUE THREAD

**Issue by Gaboemmi** [magento/magento2#15641] opened 2018-06-01 02:40 UTC
### Preconditions
1. Magento ver. 2.2.4
2. Current PHP Version: PHP 7.0.28
3. I have tried deleting the browser cache, and doing it from a new incognito tab and from other computers
4. It has installed a module of One Step Checkout, however the error persists with the module enabled and disabled.
5. In the browser's developer console it does not show any errors, it simply redirects me to (.../customer/account/login/) and it takes me out of the session.

### Steps to reproduce
1. Create simple product.
2. Navigate to storefront and register customer without address.
3. Add created product to cart as guest.
4. Proceed to checkout.
5. In email field enter created customer email.
6. In appeared password field enter created customer password.
7. Press "Login" button.

### Expected result
1. customer is logged in and checkout page is reloaded.

### Actual result
1. customer is logged out on checkout page reload

### Additional info
To reproduce issue guaranteed put a breakpoint in Magento\CatalogInventory\Observer\QuantityValidatorObserver::execute method.
Issue is caused by duplicated session cookies send after session_regenerate_id() is called.
Possible related to PHP with Apache bug: https://bugs.php.net/bug.php?id=75554&edit=1

**Comment by FreekVandeursen** [comment] 2018-06-02 10:49
Duplicate of https://github.com/magento/magento2/issues/12362 ?

**Comment by OleksiyOleksiyovych** [comment] 2018-07-03 09:13
We have a similar issue on one our project.
Magento 2.2.4.
Fix from bug [#12362](https://iwdagency.teamwork.com/#tasks/10853913) did not help to fix this issue (yes, it fixed log out after some quick reload on the checkout page, but not this issue)

Have someone any ideas how to catch and fix this intermittent issue?

**Comment by OleksiyOleksiyovych** [comment] 2018-07-04 20:49
Looks like, we found the reason. It's customer plugin for each action - https://github.com/magento/magento2/blob/2.2/app/code/Magento/Customer/Model/Plugin/CustomerNotification.php

The most easly and fuster way to reproduce this issue is appling coupon on shopping cart page for logged in customer (sometimes you need to apply/cancel couplon several times).

**Comment by engcom-backlog-nickolas** [comment] 2018-07-10 08:21
Hello, @Gaboemmi, thank you for your report. Can you please specify, what browser do you use?

**Comment by agata-maksymiuk** [comment] 2018-07-25 07:20
Magento 2.2.5 EE - I confirm, the same error.
Easiest way to reproduce is hitting F5 on checkout page several times.

Seems related to:
https://github.com/magento/magento2/issues/13889
https://github.com/magento/magento2/issues/12362

As I investigated, every time /checkout/index/index page is refreshed, it changes session ID (PHPSESSID). It does not happen on other pages. I've tried to remove
`$this->_customerSession->regenerateId();`
in Magento\Checkout\Controller\Index line 35
and it helped.

I really have no idea why is it here and what it's supposed to do.
This line came from version 0.1.0 and seems completely unnecessary here.

![magento2 app code magento checkout controller index index php at e177f452801bd2e4213fead60556c43464dc0e79 magento magento2](https://user-images.githubusercontent.com/23284435/43199338-e7bdd2e2-9011-11e8-9bed-1121af959cbd.png)

PS. I've even checked Magento 1 Mage_Checkout_OnepageController class to check if there was a line such like this. Nope. This one only appeared in Magento 2 without any corresponding issue.

**Comment by engcom-backlog-nickolas** [comment] 2018-07-25 14:42
@Gaboemmi, thank you for your bug report.
We've created internal ticket MAGETWO-93111t o track progress on the issue.

**Comment by gx2g** [comment] 2018-08-24 19:14
@agata-maksymiuk I followed your directions and this fixed my problem. The line has been commented out for now. hopefully, Magento 2 will remove this deprecated code that is causing issues. I did a clean upgrade to 2.2.5 and the issue is easily deprecated.

**Comment by magento-engcom-team** [comment] 2019-06-20 20:38
Hi @Gaboemmi. 

Thank you for your report and collaboration!

The related internal Jira ticket `MAGETWO-93861` was closed as `non-reproducible` in `2.2.x`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Closed as completed** 2020-10-16 18:28 UTC
Labels: Issue: Ready for Work, Component: Checkout, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Framework/Session, Progress: done
