### ISSUE TITLE
GraphQl Get Product Filter By Category display incorrect label 

### ISSUE THREAD

**Issue by lano-vargas** [magento/magento2#29635] opened 2020-08-18 13:27 UTC
### Preconditions (*)

1.  Magento2.3.5 instance
### Steps to reproduce (*)

2. Set up multistore view at most 2 or 3 store views
3. Add options for Color at red, green etc.
4. Add labels for all store views.
5. Have at least 2 or 3 products  and add option Color attribute.
6. Query getProductFiltersByCategory 
```
query getProductFiltersByCategory($categoryIdFilter: FilterEqualTypeInput!) {
    products(filter: { category_id: $categoryIdFilter }) {
        aggregations {
            label
            count
            attribute_code
            options {
                label
                value
            }
        }
    }
}
{"categoryIdFilter": {"eq": "4"}}
```

### Expected result (*)

1. [Screenshots, logs or description]
2. I expected to return the Default Store View Label. 

### Actual result (*)

1. [Screenshots, logs or description]
2. 
![Screenshot 2020-08-18 at 12 05 21](https://user-images.githubusercontent.com/3495481/90517540-70dd9780-e15d-11ea-883a-23675afba268.png)

**It return last item in the array.**

![Screenshot 2020-08-18 at 12 42 50](https://user-images.githubusercontent.com/3495481/90517469-56a3b980-e15d-11ea-8614-0c11edbbda93.png)

ref: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php

Possible cause issue: https://github.com/magento/magento2/blob/49309635a56774ce4d3f326a08a4e607020a2a6e/app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php#L126

my.log shows
`$logger->info( $option );`
<img width="543" alt="Screenshot 2020-08-18 at 14 20 02" src="https://user-images.githubusercontent.com/3495481/90518275-725b8f80-e15e-11ea-88fd-8e0ccb58d092.png">

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by lano-vargas** [comment] 2020-08-18 14:11
@magento I am working on this

**Comment by lano-vargas** [comment] 2020-08-18 14:12
@magento add to contributors team

**Comment by lano-vargas** [comment] 2020-08-18 14:13
@magento I am working on this

**Comment by engcom-November** [comment] 2022-09-13 12:47
Hi @lano-vargas , Verified the issue on Magento 2.4-develop branch but the issue is not reproducible for all the store views.
Default store view label is retrieved in response as expected
![image](https://user-images.githubusercontent.com/60198231/189904255-8f4c5dd8-4a6f-4c0f-9519-1edb50db0086.png)
When the query is run for other store - other store label is retrieved as expected.
![image](https://user-images.githubusercontent.com/60198231/189904488-c51ece14-289f-4a6a-8690-ab7f2cb5f172.png)
![image](https://user-images.githubusercontent.com/60198231/189904726-6b564d1f-6ae2-44c0-a491-85d92205eca3.png)
Kindly recheck the issue on Magento 2.4-develop branch as it is the upcoming 2.4.x release and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by lano-vargas** [comment] 2022-09-13 14:58
Ahahha that's convenient the issue was created 2020 2 years ago on version 2.3.5 Obviously. I haven't test it on 2.4 back them not sure if it was available yet! Thanks for fixing the issue on 2.4 versions.

**Comment by engcom-November** [comment] 2022-09-16 09:55
Thank you for the response @lano-vargas . We are closing this issue as the issue is not reproducible anymore on 2.4-develop. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-09-16 09:55 UTC
Labels: Issue: Confirmed, Issue: Format is valid, Component: GraphQL, Reproduced on 2.4.x, Priority: P2, Project: GraphQL, Progress: done, Reported on 2.4.x, Area: Framework

**Comment by engcom-Alfa** [comment] 2023-02-17 05:26
Hey All,

as per discussion with the internal team confirming this issue.
