### ISSUE TITLE
Swagger have problem with layout

### ISSUE THREAD

**Issue by Sharkozp** [magento/magento2#13538] opened 2018-02-07 11:11 UTC
### Preconditions
1. Magento 2.2.2 (Upgraded from 2.2.1)

### Steps to reproduce

1. Go to Swagger
2. Find integrationAdminTokenServiceV1
3. Open accordion for POST /V1/integration/admin/token

### Expected result

1. It is must look like this:
![image](https://user-images.githubusercontent.com/3489232/35913243-53302242-0bff-11e8-800a-603583e4d3f3.png)
2. It was correct in Magento 2.2.1 and less

### Actual result

1. But it is real result:
![image](https://user-images.githubusercontent.com/3489232/35913292-74931f8e-0bff-11e8-9993-cc9f59d2942f.png)
2. Data type block is out of visible block
3. I think problem in layout or in long parameter name:
![image](https://user-images.githubusercontent.com/3489232/35913363-a46d11f6-0bff-11e8-9cee-b756fa21cd56.png)

**Comment by magento-engcom-team** [comment] 2018-02-07 12:04
@Sharkozp, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2019-01-24 08:44
Hi @XxXgeoXxX. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by XxXgeoXxX** [comment] 2019-01-24 08:57
Hi @Sharkozp
You are wrong. This is not bug in magento.
You described and provided screenshot from magento 2.1.x but Magento 2.2.x works in another way.
Steps for manage(use swagger functionality):
- Go to Swagger
- Find integrationAdminTokenServiceV1
- click button 'Try it out'
- fill 'Example values' according to the example and types
- press 'Execute'

**Comment by Sharkozp** [comment] 2019-01-24 09:09
Hi @XxXgeoXxX, 

I didn't use 2.1.x. As I described and provided screenshots from **Magento 2.2.2**. I have used Magento 2.2.1 and after updating to 2.2.2 I found that layouts is not correct. Maybe this is fixed with new release. I will check later

All the best

**Comment by XxXgeoXxX** [comment] 2019-01-24 09:38
@Sharkozp
rechecked on Magento vanilla 2.2.2, 2.2.3, 2.2.4, 2.2.6, branch 2.2-developer, branch 2.3-developer.
I couldn't reproduce your problem. Please, recheck your layout/template rewrites in your custom themes.
If I  have a mistake, please, reopen the issue.

**Closed as completed by XxXgeoXxX** 2019-01-24 09:38 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid
