### ISSUE TITLE
"select" custom customer address attribute does not render for new customer address

### ISSUE THREAD

**Issue by markshust** [magento/magento2#34950] opened 2022-01-10 13:59 UTC
Custom customer address EAV attributes of `'type' => 'int'` and `'input' => 'select'` do not render after a logged-in customer creates a new address at checkout.

### Preconditions (*)
1. Base install of Magento 2.4.3-p1

### Steps to reproduce (*)

1. Create a custom module with a new setup patch data script to create a custom customer address attribute, with `'type' => 'int'` and `'input' => 'select'`. Ensure `'system' => false` so it's created as a "custom" attribute.

`app/code/MarkShust/MyModule/registration.php`
```php
<?php declare(strict_types=1);

use Magento\Framework\Component\ComponentRegistrar;

ComponentRegistrar::register(
    ComponentRegistrar::MODULE,
    'MarkShust_MyModule',
    __DIR__
);
```

`app/code/MarkShust/MyModule/etc/module.xml`
```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="MarkShust_MyModule">
        <sequence>
            <module name="Magento_Customer"/>
        </sequence>
    </module>
</config>
```

`app/code/MarkShust/MyModule/Setup/Patch/Data/AddAddressClassificationAttribute.php`
```php
<?php declare(strict_types=1);

namespace MarkShust\MyModule\Setup\Patch\Data;

use Magento\Customer\Api\AddressMetadataInterface;
use Magento\Eav\Model\Config as EavConfig;
use Magento\Framework\Exception\AlreadyExistsException;
use Magento\Framework\Exception\LocalizedException;
use Magento\Framework\Setup\Patch\DataPatchInterface;
use Magento\Framework\Setup\ModuleDataSetupInterface;
use Magento\Eav\Setup\EavSetupFactory;
use Magento\Customer\Model\ResourceModel\Attribute as AttributeResourceModel;
use MarkShust\MyModule\Model\Config\Source\AddressClassification;
use Zend_Validate_Exception;

class AddAddressClassificationAttribute implements DataPatchInterface
{
    const ATTRIBUTE_CODE = 'address_classification';

    private AttributeResourceModel $attributeResourceModel;
    private EavConfig $eavConfig;
    private EavSetupFactory $eavSetupFactory;
    private ModuleDataSetupInterface $moduleDataSetup;

    public function __construct(
        AttributeResourceModel $attributeResourceModel,
        EavConfig $eavConfig,
        EavSetupFactory $eavSetupFactory,
        ModuleDataSetupInterface $moduleDataSetup
    ) {
        $this->attributeResourceModel = $attributeResourceModel;
        $this->eavConfig = $eavConfig;
        $this->eavSetupFactory = $eavSetupFactory;
        $this->moduleDataSetup = $moduleDataSetup;
    }

    /**
     * @return array
     */
    public static function getDependencies(): array
    {
        return [];
    }

    /**
     * @return array
     */
    public function getAliases(): array
    {
        return [];
    }

    /**
     * @return $this
     * @throws LocalizedException
     * @throws AlreadyExistsException
     * @throws Zend_Validate_Exception
     */
    public function apply(): self
    {
        $eavSetup = $this->eavSetupFactory->create(['setup' => $this->moduleDataSetup]);
        $eavSetup->addAttribute(
            AddressMetadataInterface::ENTITY_TYPE_ADDRESS,
            self::ATTRIBUTE_CODE,
            [
                'type' => 'int',
                'label' => 'Address Classification',
                'input' => 'select',
                'source' => AddressClassification::class,
                'required' => true,
                'default' => 0,
                'system' => false,
                'position' => 150,
                'sort_order' => 150,
            ]
        );
        $attribute = $this->eavConfig->getAttribute(
            AddressMetadataInterface::ENTITY_TYPE_ADDRESS,
            self::ATTRIBUTE_CODE
        );
        $attribute->setData('used_in_forms', [
            'adminhtml_customer_address',
            'customer_address_edit',
            'customer_register_address',
        ]);
        $this->attributeResourceModel->save($attribute);

        return $this;
    }
}
```

`app/code/MarkShust/MyModule/Model/Config/Source/AddressClassification.php`
```php
<?php declare(strict_types=1);

namespace MarkShust\MyModule\Model\Config\Source;

use Magento\Eav\Model\Entity\Attribute\Source\AbstractSource;
use Magento\Eav\Model\Entity\Attribute\Source\SourceInterface;
use Magento\Framework\Data\OptionSourceInterface;

class AddressClassification extends AbstractSource implements OptionSourceInterface, SourceInterface
{
    public function getAllOptions(): array
    {
        return [
            [
                'value' => 0,
                'label' => 'Residential',
            ],
            [
                'value' => 1,
                'label' => 'Commercial',
            ],
        ];
    }
}
```

2. Enable the module with `bin/magento module:enable MarkShust_MyModule`.
3. Execute the setup patch data script by running `bin/magento setup:upgrade`.
4. Go to frontend of the site and log in as a registered customer.
5. Add a product to the cart and start checkout.
6. At the Shipping step under Shipping Address, click New Address.
7. Enter the new address info along with a value for the custom attribute, then click Ship Here.

### Expected result (*)

1. I expect to see the custom customer address attribute rendered just as the saved addresses do:

![Screen Shot 2022-01-08 at 10 33 39 AM](https://user-images.githubusercontent.com/437029/148776632-5d206ecf-549e-4e06-b99f-e623cc6d1bc9.png)

2. Note how saved addresses are created under a `custom_attributes` property. This differs from the data stored for the new customer address as explained in the Actual result info below. They are also stored as an object containing a `label` and `value`, as opposed to just an integer:

![Screen Shot 2022-01-09 at 10 18 09 AM](https://user-images.githubusercontent.com/437029/148776945-a506ed94-e2ed-4cbb-9f84-28c393330ff2.png)

3. I'd expect the way the data assigned to the new customer address to be congruent with how data is stored for saved addresses.

### Actual result (*)

1. The new address is created, but the custom customer attribute does not display. Note how the attribute is stored as a child property directly on the `newCustomerShippingAddress` property, and as an integer (`address_classification: 0`).

![Screen Shot 2022-01-08 at 10 33 10 AM](https://user-images.githubusercontent.com/437029/148776348-dcf8b920-e3d8-4710-a2ca-b2e5e8019128.png)

---

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by markshust** [comment] 2022-01-10 14:08
@magento give me 2.4-develop instance

**Comment by markshust** [comment] 2022-01-10 19:34
@magento give me 2.4-develop instance

**Comment by markshust** [comment] 2022-01-11 16:30
@magento give me 2.4-develop instance

**Comment by markshust** [comment] 2022-01-15 16:30
@magento give me 2.4-develop instance

**Comment by markshust** [comment] 2022-01-19 14:08
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment] 2022-01-31 12:07
Hi @markshust ,

Thank you for reporting the issue.

We were able to reproduce this issue on 2.4-develop instance.

Steps followed to reproduce the issue :-

1. Install fresh Magento 2.4-develop instance
2. Create a custom module to add custom customer address attribute. Create following files for this step:-

`app/code/MarkShust/MyModule/registration.php`
```php
<?php declare(strict_types=1);

use Magento\Framework\Component\ComponentRegistrar;

ComponentRegistrar::register(
    ComponentRegistrar::MODULE,
    'MarkShust_MyModule',
    __DIR__
);
```

`app/code/MarkShust/MyModule/etc/module.xml`
```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="MarkShust_MyModule">
        <sequence>
            <module name="Magento_Customer"/>
        </sequence>
    </module>
</config>
```

`app/code/MarkShust/MyModule/Setup/Patch/Data/AddAddressClassificationAttribute.php`
```php
<?php declare(strict_types=1);

namespace MarkShust\MyModule\Setup\Patch\Data;

use Magento\Customer\Api\AddressMetadataInterface;
use Magento\Eav\Model\Config as EavConfig;
use Magento\Framework\Exception\AlreadyExistsException;
use Magento\Framework\Exception\LocalizedException;
use Magento\Framework\Setup\Patch\DataPatchInterface;
use Magento\Framework\Setup\ModuleDataSetupInterface;
use Magento\Eav\Setup\EavSetupFactory;
use Magento\Customer\Model\ResourceModel\Attribute as AttributeResourceModel;
use MarkShust\MyModule\Model\Config\Source\AddressClassification;
use Zend_Validate_Exception;

class AddAddressClassificationAttribute implements DataPatchInterface
{
    const ATTRIBUTE_CODE = 'address_classification';

    private AttributeResourceModel $attributeResourceModel;
    private EavConfig $eavConfig;
    private EavSetupFactory $eavSetupFactory;
    private ModuleDataSetupInterface $moduleDataSetup;

    public function __construct(
        AttributeResourceModel $attributeResourceModel,
        EavConfig $eavConfig,
        EavSetupFactory $eavSetupFactory,
        ModuleDataSetupInterface $moduleDataSetup
    ) {
        $this->attributeResourceModel = $attributeResourceModel;
        $this->eavConfig = $eavConfig;
        $this->eavSetupFactory = $eavSetupFactory;
        $this->moduleDataSetup = $moduleDataSetup;
    }

    /**
     * @return array
     */
    public static function getDependencies(): array
    {
        return [];
    }

    /**
     * @return array
     */
    public function getAliases(): array
    {
        return [];
    }

    /**
     * @return $this
     * @throws LocalizedException
     * @throws AlreadyExistsException
     * @throws Zend_Validate_Exception
     */
    public function apply(): self
    {
        $eavSetup = $this->eavSetupFactory->create(['setup' => $this->moduleDataSetup]);
        $eavSetup->addAttribute(
            AddressMetadataInterface::ENTITY_TYPE_ADDRESS,
            self::ATTRIBUTE_CODE,
            [
                'type' => 'int',
                'label' => 'Address Classification',
                'input' => 'select',
                'source' => AddressClassification::class,
                'required' => true,
                'default' => 0,
                'system' => false,
                'position' => 150,
                'sort_order' => 150,
            ]
        );
        $attribute = $this->eavConfig->getAttribute(
            AddressMetadataInterface::ENTITY_TYPE_ADDRESS,
            self::ATTRIBUTE_CODE
        );
        $attribute->setData('used_in_forms', [
            'adminhtml_customer_address',
            'customer_address_edit',
            'customer_register_address',
        ]);
        $this->attributeResourceModel->save($attribute);

        return $this;
    }
}
```

`app/code/MarkShust/MyModule/Model/Config/Source/AddressClassification.php`
```php
<?php declare(strict_types=1);

namespace MarkShust\MyModule\Model\Config\Source;

use Magento\Eav\Model\Entity\Attribute\Source\AbstractSource;
use Magento\Eav\Model\Entity\Attribute\Source\SourceInterface;
use Magento\Framework\Data\OptionSourceInterface;

class AddressClassification extends AbstractSource implements OptionSourceInterface, SourceInterface
{
    public function getAllOptions(): array
    {
        return [
            [
                'value' => 0,
                'label' => 'Residential',
            ],
            [
                'value' => 1,
                'label' => 'Commercial',
            ],
        ];
    }
}
```
3. Enable the module `bin/magento module:enable MarkShust_MyModule`
4. Install the data run `bin/magento setup:upgrade`
5. Go to frontend of the site and log in as a registered customer.
6. Add a product to the cart and start checkout.
7. At the Shipping step under Shipping Address, click New Address.
8. Enter the new address info along with a value for the custom attribute, then click Ship Here.

**Expected Result:**
The custom address attribute should be rendered just as it is being rendered for previous addresses.

**Actual Result:**
Custom address attribute is not rendered.
<img width="1435" alt="Screenshot 2022-01-31 at 5 19 12 PM" src="https://user-images.githubusercontent.com/60198022/151790584-c67a9cf8-5b3d-4c1a-a5e7-7831b9c489da.png">

As we can see above, the attribute **Residential** is set for default address but not for newly added address.
Based on this confirming the issue.

Thanks!

**Comment by engcom-Hotel** [comment] 2022-02-01 12:13
Hello @engcom-Lima,

Thanks for your input!

As per our discussion in the triage call, please try to reproduce the issue with the fresh Magento module.

Thanks

**Comment by engcom-Lima** [comment] 2022-02-08 09:18
Hi @engcom-Hotel,
I tried reproducing the issue with the fresh Magento 2.4-develop instance and the issue is still reproducible.
I created the custom module and added the patch script following the [documentation ](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/declarative-schema/data-patches.html) and as per the reproducible steps mentioned by @markshust I was able to reproduce the issue.
![34950](https://user-images.githubusercontent.com/60198022/152955935-740eb58a-e2ab-4964-bab6-984b38653d8c.png)

Based on this confirming the issue!

Thanks.

**Comment by engcom-Hotel** [comment] 2024-11-12 10:07
We have tried to reproduce the issue in the latest development branch i.e. 2.4-develop and the issue is still relevant. The added attribute is not visible in the checkout page:

We have selected `Residential` while adding new address:
![image](https://github.com/user-attachments/assets/83c2795f-2632-4868-bd9d-6624ff43c0a4)

But it is not showing here:
![image](https://github.com/user-attachments/assets/820bdf68-0fde-48cd-a38b-72cb3e2e7ae1)

Also we are unable to checkout with address because the `Address Classification` field is marked as `required`:
![image](https://github.com/user-attachments/assets/cc7da042-026e-4a49-a58f-36530e8344c0)

Hence reconfirming the issue and prioritize it as P1.

Thanks

**Comment by engcom-Bravo** [comment] 2024-11-20 07:34
Hi @markshust,

The Magento core engineering team is working on the issue and may do further implementation to cover few more scenarios as needed. We will reach out to you if we need more information.

Thank you once again!

**Comment by engcom-Charlie** [comment] 2024-11-26 08:46
Internal team have investigated thoroughly and found that system attribute has been created previously. However, need to create user defined attribute using 'user_defined' => true property. After this change in your shared module script, it will work as expected.

```
public function apply(): self
    {
        $eavSetup = $this->eavSetupFactory->create(['setup' => $this->moduleDataSetup]);
        $eavSetup->addAttribute(
            AddressMetadataInterface::ENTITY_TYPE_ADDRESS,
            self::ATTRIBUTE_CODE,
            [
                'type' => 'int',
                'label' => 'Address Classification',
                'input' => 'select',
                'source' => AddressClassification::class,
                'required' => true,
                'user_defined' => true,
                'default' => 0,
                'system' => false,
                'position' => 150,
                'sort_order' => 150,
            ]
        );
        $attribute = $this->eavConfig->getAttribute(
            AddressMetadataInterface::ENTITY_TYPE_ADDRESS,
            self::ATTRIBUTE_CODE
        );
        $attribute->setData('used_in_forms', [
            'adminhtml_customer_address',
            'customer_address_edit',
            'customer_register_address',
        ]);
        $this->attributeResourceModel->save($attribute);
        return $this;
    }
```

**Comment by engcom-Hotel** [comment] 2024-12-30 14:26
Dear @markshust,

This issue is being closed since it has not been updated in a long time. Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks

**Closed as completed by engcom-Hotel** 2024-12-30 14:26 UTC
Labels: Component: Setup, Issue: Confirmed, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P1, Progress: done, Area: Account, Area: Cart & Checkout, Reported on 2.4.3-p1
