### ISSUE TITLE
magento email sent as attachment in 2.3.4 open source

### ISSUE THREAD

**Issue by sendoapp** [magento/magento2#28134] opened 2020-05-07 13:28 UTC
### Preconditions (*)
1.magento 2.3.4

### Steps to reproduce (*)
1.make an order

### Expected result (*)
1.email confirmation sent in the body of email

### Actual result (*)
1. email sent in the attachment of email

**Comment by devchris79** [comment] 2020-05-07 15:30
Duplicate of #25076

**Comment by sendoapp** [comment] 2020-05-07 16:08
i can't find the solution there !!

**Comment by devchris79** [comment] 2020-05-07 16:19
There is a hotfix in there to headers.php from @georgios-2317 on the 9th December that worked for me.

I think there is still some debate as to what approach the core should be taking with headers, but the hotfix will sort it for now.

**Comment by sendoapp** [comment] 2020-05-07 16:23
i tried that it's not work ! when i change code in zendframe work should i upgrade or deploy ?

**Comment by sendoapp** [comment] 2020-05-07 16:30
it's really works with exchange but not with gmail . the email blocked in gmail

**Comment by krishprakash** [comment] 2020-05-08 05:05
Hi @sendoapp. Thank you for your report, The issue is duplicate to #25076 and it's already open. You can track the conversion from given issue link,Thanks!!

**Closed as completed by krishprakash** 2020-05-08 05:05 UTC
Labels: duplicate, Issue: Format is valid, Reported on 2.3.4
