### ISSUE TITLE
Widget option labels are misalinged

### ISSUE THREAD

**Issue by yashwant2jcommerce** [magento/magento2#20113] opened 2019-01-08 10:08 UTC
### Preconditions (*)

1. 2.3

### Steps to reproduce (*)

1. In admin content >> Widgets >> Edit widget >> widget options

### Expected result (*)

1. 
![expected_widgets - contact us info](https://user-images.githubusercontent.com/26630846/50823970-545f6380-135b-11e9-8884-6ba8d323b8a4.jpg)

### Actual result (*)

1. 
![actual_widgets - contact us info](https://user-images.githubusercontent.com/26630846/50823979-5c1f0800-135b-11e9-97f5-3f81f6f8bf7d.jpg)

**Comment by magento-engcom-team** [comment] 2019-01-08 10:08
Hi @yashwant2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@yashwant2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-08 10:10
Hi @GovindaSharma. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by GovindaSharma** [comment] 2019-01-08 10:11
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-01-08 10:12
Hi @GovindaSharma. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-01-08 10:12
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-01-08 10:15
@GovindaSharma Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97484`, `MAGETWO-97485` were created

**Comment by magento-engcom-team** [comment] 2019-01-29 03:48
Hi @yashwant2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20114 by @GovindaSharma in 2.3-develop branch
Related commit(s):
 - [d62149824075b462e1d0d1506fa6e83beaaa1653](https://github.com/magento/magento2/commit/d62149824075b462e1d0d1506fa6e83beaaa1653)
 - [95defccc553c652eb8493d428a1277a2e7ae2e04](https://github.com/magento/magento2/commit/95defccc553c652eb8493d428a1277a2e7ae2e04)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2019-01-29 03:48 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Widget

**Comment by magento-engcom-team** [comment] 2019-01-31 22:55
Hi @yashwant2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20270 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [936d71fda5b37941dba89a08c79bd0aa1fba820d](https://github.com/magento/magento2/commit/936d71fda5b37941dba89a08c79bd0aa1fba820d)
 - [935d3d2c648982b7b3b62b206b2815c3dffb6336](https://github.com/magento/magento2/commit/935d3d2c648982b7b3b62b206b2815c3dffb6336)

The fix will be available with the upcoming 2.2.8 release.
