### ISSUE TITLE
Product price within bundle-products incorrect if product does not have a special price

### ISSUE THREAD

**Issue by thompalstra** [magento/magento2#21874] opened 2019-03-21 13:55 UTC
### Preconditions (*)

1. Magento version 2.2.6
2. Using bundled products

When using Magento Bundled products, some sub-products' price may be reset to 0 when this is not expected. This issue appears to stem from the bundle selection price.php or maybe even further back.

### Steps to reproduce (*)

1. Create bundled product
2. Add products to bundle

### Expected result (*)

1. Expected products->productInfo to output the regular price. 

### Actual result (*)

Price is set to 0.

1. Price is always returned as 0 when the price code is "regular_price".
2. Price is always returned as 0 when the price code is "final_price" and no sales price is set on a product.

vendor/magento/module-bundle/Pricing/Price/BundleSelectionPrice.php:119

            $value = $this->priceInfo
                ->getPrice($priceCode)
                ->getValue();

This issue does NOT occur on the product view, but only seems to "happen" within a bundled product's sub-products.

**Comment by magento-engcom-team** [comment] 2019-03-21 13:55
Hi @thompalstra. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@thompalstra do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-03-26 10:17
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by Mobecls** [comment] 2019-04-13 10:47
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-04-13 10:47
Hi @Mobecls. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-13 10:48
Hi @Mobecls, here is your [Magento instance](https://i-21874-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21874-2-3-develop.instances.magento-community.engineering/admin](https://i-21874-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Mobecls** [comment] 2019-04-13 11:57
@thompalstra, I wasn't able to reproduce the issue on 2.3-develop instance. 

1. Created 2 simples
2. Created 1 bundle
3. Added simples to bundle

On a product page I can see the non-0 price. When adding to a cart the price is not 0.

**Closed as completed** 2019-04-13 12:22 UTC
Labels: Issue: Format is valid, Event: cdkyiv2019
