### ISSUE TITLE
The stock item was unable to be saved. Please try again.

### ISSUE THREAD

**Issue by scne** [magento/magento2#23962] opened 2019-07-31 13:58 UTC
### Preconditions
1. magento 2.3.1 CE
2. PHP 7.1.29
3. elasticsearch 5

### Steps to reproduce (*)
update multiple products via REST API with a PUT request. Every time I get this error: **_The stock item was unable to be saved. Please try again._**. This issue persist with elasticsearch 5 as indexer, and with MariaDB as indexer

To reproduce this issue try to perform a PUT request with this body

`{
	"product": {
		"sku": "product_code",
		"attribute_set_id": 4,
		"status": 1,
		"type_id": "simple",
		"visibility": 4,
		"extension_attributes": {
			"stock_item": {
				"qty": 132,
				"is_in_stock": true,
				"is_qty_decimal": false,
				"min_qty": 1,
				"qty_increments": 1
			}
		},
		"custom_attributes": [{
			"attribute_code": "news_to_date",
			"value": "1546905600"
		}, {
			"attribute_code": "news_from_date",
			"value": "1546300800"
		}]
	}
}`

### Expected result (*)
Updating of stock item related to product sku via PUT request

### Actual result (*)
error in console:  **_The stock item was unable to be saved. Please try again._**

**Comment by engcom-Charlie** [comment] 2019-08-01 11:47
Hello @scne
I can't reproduce this issue on fresh Magento 2.3-develop.
**Manual testing scenario:** 

1. Configure Elasticsearch 5
2. Create simple product
3.  To update a product send a PUT request with this body:
`{
	"product": {
		"sku": "product_code",
		"attribute_set_id": 4,
		"status": 1,
		"type_id": "simple",
		"visibility": 4,
		"extension_attributes": {
			"stock_item": {
				"qty": 132,
				"is_in_stock": true,
				"is_qty_decimal": false,
				"min_qty": 1,
				"qty_increments": 1
			}
		},
		"custom_attributes": [{
			"attribute_code": "news_to_date",
			"value": "1546905600"
		}, {
			"attribute_code": "news_from_date",
			"value": "1546300800"
		}]
	}
}`

**Actual result:**
Response 200 OK
![image](https://user-images.githubusercontent.com/51680850/62290903-1a76bb80-b46b-11e9-8a1b-227bcbefb377.png)

So i close this issue.
Thank for your report!

**Closed as completed by engcom-Charlie** 2019-08-01 11:47 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Elasticsearch, Component: Api

**Comment by scne** [comment] 2019-08-01 11:52
@engcom-Charlie Please try to update more products simultaneously! For one single request all works ok.

**Comment by engcom-Charlie** [comment] 2019-08-01 13:31
@scne i tried:
![image](https://user-images.githubusercontent.com/51680850/62297277-9d9f0e00-b479-11e9-85a0-e12993ee6d1b.png)

![image](https://user-images.githubusercontent.com/51680850/62297345-b4ddfb80-b479-11e9-917f-7e3a81d2ca01.png)

**Comment by scne** [comment] 2019-08-01 15:45
@engcom-Charlie I've a queue which send more then two requests simultaneously to REST endpoint of my magento. If I try to send these request with a REST client all works fine, but when I try to update the stock quantity of products in _**burst**_ mode I get this issue. I send 5 or 6 requests concurrently.

**Comment by engcom-Charlie** [comment] 2019-08-02 07:46
@scne i tried to reproduce it with 6 requests via cmd(multiple requests):
![image](https://user-images.githubusercontent.com/51680850/62353089-78121300-b512-11e9-831c-67699f5eaf50.png)
All responses is OK.

**Comment by engcom-Charlie** [comment] 2019-08-02 07:53
@scne can you please provide your steps to reproduce this issue with simultaneously requests?

**Comment by scne** [comment] 2019-08-08 10:34
@engcom-Charlie please try to index with saving mode

**Comment by engcom-Charlie** [comment] 2019-08-08 12:33
@scne 
![image](https://user-images.githubusercontent.com/51680850/62703414-d434d580-b9f1-11e9-8b32-0853c882440c.png)

**Comment by davirs** [comment] 2020-10-16 00:10
Same problem here.

**Comment by Shlok2927** [comment] 2024-07-25 07:19
hello @engcom-Charlie. while accessing the ui and creating the store from magento2. I am facing the same issue and have been working for weeks to resolve it but was unable to do so. I even tried the postman to create the product but same error is being repeated.
![Screenshot 2024-07-25 124723](https://github.com/user-attachments/assets/582d5689-6d04-40a4-812c-005074c12648)
