### ISSUE TITLE
Typo in Magento\Cms\Model\Wysiwyg\Images\Storage function resizeFile($source, $keepRation = true)

### ISSUE THREAD

**Issue by simonworkhouse** [magento/magento2#17587] opened 2018-08-14 04:30 UTC
The parameter $keepRation should be called $keepRatio

### Preconditions

1. Magento 2.2.5

### Steps to reproduce

Look at the resizeFile function on line 572 of the Magento\Cms\Model\Wysiwyg\Images\Storage class.

### Expected result

The parameter $keepRation should be $keepRatio

### Actual result

The parameter is called $keepRation

**Comment by magento-engcom-team** [comment] 2018-08-14 04:30
Hi @simonworkhouse. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@simonworkhouse do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment] 2018-08-14 12:46
Hello @simonworkhouse, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2018-08-16 14:15
Hi @simonworkhouse. Thank you for your report. 
The issue has been fixed in magento/magento2#17596 by @eduard13 in 2.3-develop branch
Related commit(s):
 - [9a5bfd3f38f09f94553ef79da140291943a5e57a](https://github.com/magento/magento2/commit/9a5bfd3f38f09f94553ef79da140291943a5e57a)

The fix will be available with the upcoming 2.3.0 release.

**Comment by MartinAarts** [comment] 2018-08-24 06:41
Fixed in #17776 for 2.2

**Closed as completed by MartinAarts** 2018-08-24 06:41 UTC
Labels: Issue: Ready for Work, Component: Cms, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, good first issue

**Comment by magento-engcom-team** [comment] 2018-08-28 09:45
Hi @simonworkhouse. Thank you for your report. 
The issue has been fixed in magento/magento2#17776 by @MartinAarts in 2.2-develop branch
Related commit(s):
 - [8855a66a1437c4c4b8098de27ba3ad944f0a79f0](https://github.com/magento/magento2/commit/8855a66a1437c4c4b8098de27ba3ad944f0a79f0)

The fix will be available with the upcoming 2.2.7 release.
