### ISSUE TITLE
upgrading from 2.1.0 to 2.1.1 causes products to disappear from category

### ISSUE THREAD

**Issue by dmcmillin** [magento/magento2#6512] opened 2016-09-06 20:24 UTC
1. centos Linux 
2. PHP Version 5.6.23
### Steps to reproduce

1. install 2.1 from git
2. make products. 
3. put products into categories
4. install 2.1.1 from git
5. make new products.
6. put products into categories.
### Expected result
1. products should be showing up on frontend that are new along with the old products 
### Actual result

old products show up but not new ones at all. 
If new products are alongside old products no products show up.
Turns out that if you have layered navigation enabled and attributes supporting it/anchor. it will display the products after choosing the attribute.

**Comment by dapdx** [comment] 2016-09-06 21:34
Yah, I'm having some issue like this as well. The products will show up if I add them to multiple categories, but when only set to one category they aren't showing up. It's not consistent either, just certain categories are doing this. 

Overall 2.1.1 is just completely unusable. My clients are pissed and I'm ditching Matgento 2 and moving everything back to 1.9.

**Comment by terrybakshi** [comment] 2016-09-07 07:11
ok go in admin -> System -> index management and select all and from the drop down action box change it to save on update.

Thanks

**Comment by dapdx** [comment] 2016-09-07 16:36
Ok, so update on this. On my store this issue only happens when a category has a configurable product in it that has a simple associated product with a quantity of 0. When I disable that simple product all of the items in the category show up ok, but if it's enabled none of the products show up. Ideas?

**Comment by dmcmillin** [comment] 2016-09-08 00:36
I do index management by default(cli). I am also running without cache. Site still has issues. I narrowed it down to simple products show up but not configurable. but only if they're by themselves.

**Comment by sevos1984** [comment] 2016-09-12 08:29
You must be running into similar issue https://github.com/magento/magento2/issues/6422

**Comment by grusy** [comment] 2016-09-13 07:50
Setting "Display Out of Stock Products" to yes brings back all of the missing products.
Or setting the stock for a configurable product to not 0

**Comment by sevos1984** [comment] 2016-09-13 08:31
Sub products of configurable should also be in stock, if they're not configurable will not be shown.

**Comment by dmcmillin** [comment] 2016-09-13 17:06
for configurable products it shows 0 even after I goto advanced stock and change the quantity to any value. I saved the database and manually changed the qty to 1000.0000 as a check on this problem and it still doesn't show up on frontend. However, it shows up in the backend as having 1000.000 quantity.

**Comment by sevos1984** [comment] 2016-09-14 07:41
Configurable qty is ignored, it uses sub-products stock, this is by design. If you set all sub products in stock and add qty to them configurable will appear in store.

**Comment by grusy** [comment] 2016-09-14 08:01
Adding stock to the configurable product itself added it back to the front end for me.

**Comment by dmcmillin** [comment] 2016-09-14 16:34
steps I have taken:
1) selected configurable product.
2) went to area where it says on product "in stock" or "out of stock"
3) all products already show in stock

expected result. 

1) product should show up in frontend

actual result

1) product does not show up in front end

**Comment by terrybakshi** [comment] 2016-09-14 16:40
Dmcmillin ok go in admin -> System -> index management and select all and from the drop down action box change it to save on update. it happens sometime when you have not configured cron job to run, to reindex so once you do the settings in index management to save on update it should work.

**Comment by dmcmillin** [comment] 2016-09-14 16:45
@terrybakshi

I already run ./magento indexer:reindex after any changes and its set to save on update. The weird thing is in the qty field for configurables. it's grayed out and 0. So I have to change it via mysql.

**Comment by epadmin** [comment] 2016-09-16 05:05
I had similar problem but running php bin/magento indexer:reindex fixed it for me.

**Comment by sevos1984** [comment] 2016-09-19 15:01
Qty for configurable is disabled intentionally as it is not used, only sub-products qty matters

**Comment by sevos1984** [comment] 2016-10-03 09:24
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-10-03 09:24 UTC
Labels: bug report, Progress: needs update, Component: Setup, Component: Catalog
