### ISSUE TITLE
Check box alignment issue at Statistics

### ISSUE THREAD

**Issue by renard123** [magento/magento2#25491] opened 2019-11-06 12:03 UTC
Check box alignment issue at Statistics

### Preconditions (*)
Magento : 2.3.3

### Steps to reproduce (*)
Admin -> Reports -> Statistics -> Refresh Statistics

### Expected result (*)
Check box alignment should proper

### Actual result (*)
![image](https://user-images.githubusercontent.com/50658701/68296561-e7237880-00ba-11ea-8b62-17c929c0662c.png)

**Comment by krishprakash** [comment] 2019-11-06 12:04
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-06 12:04
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-06 12:04
Hi @krishprakash, here is your [Magento instance](https://i-25491-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25491-2-3-develop.instances.magento-community.engineering/admin](https://i-25491-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-11-06 12:08
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22861` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by drpayyne** [comment] 2019-11-06 12:44
Hi @renard123 @krishprakash, I'm unable to reproduce it in my local with updated `2.3-develop` branch. Were you able to reproduce this on `2.3-develop` branch, @krishprakash?
![image](https://user-images.githubusercontent.com/22623301/68299177-35d41100-00c1-11ea-87fb-f18bb1d4834d.png)

**Comment by krishprakash** [comment] 2019-11-06 12:52
Hi @drpayyne. Thanks for your feedback
I have checked at my local instance and also verify on latest magento instance as provided here https://github.com/magento/magento2/issues/25491#issuecomment-550280077

Local instance screenshot:
![image](https://user-images.githubusercontent.com/46617848/68299742-4fc22380-00c2-11ea-8e96-0fac4120e060.png)

**Comment by drpayyne** [comment] 2019-11-06 13:15
Thanks, @krishprakash. Let me test it here and check.

**Comment by drpayyne** [comment] 2019-11-06 13:15
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-06 13:15
Hi @drpayyne. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-06 13:16
Hi @drpayyne, here is your [Magento instance](https://i-25491-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25491-2-3-develop.instances.magento-community.engineering/admin](https://i-25491-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by drpayyne** [comment] 2019-11-06 13:16
@krishprakash, what browser, may I ask? :thinking:

**Comment by krishprakash** [comment] 2019-11-06 13:17
Yes, Chrome Version 78.0.3904.87 (Official Build) (64-bit)

**Comment by drpayyne** [comment] 2019-11-06 13:19
Not reproducible on Firefox Developer Edition 71.0b6 (64-bit). Checking on Chromium.

**Comment by drpayyne** [comment] 2019-11-06 13:20
Not reproducible on Chromium Version 77.0.3865.90 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit), either. Will check on Chrome.

**Comment by ernesthernandez** [comment] 2019-11-06 14:41
This issue is reproducible in latest Google Chrome version, I use 2.3.2 and 2.3.3 and all my magento sites presents this issue in cache module as well

**Comment by hostep** [comment] 2019-11-06 18:45
Let me close this as it's a duplicate of https://github.com/magento/magento2/issues/25429
To summarize: the problem only occurs in Magento 2.3.2 and 2.3.3 when using Google Chrome version 78

A fix is already in the works in https://github.com/magento/magento2/pull/25443

**Closed as completed by hostep** 2019-11-06 18:45 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Backend, Component: Reports
