### ISSUE TITLE
[EE] Appropriate message should be shown when no stores are available to select

### ISSUE THREAD

**Issue by engcom-Delta** [magento/magento2#29754] opened 2020-08-26 14:20 UTC
### Preconditions (*)

1. Magento 2.4.1 EE edition
2. Login as Customer module related
3. Store View To Login To=Manual Selection
4. Create additional website
![image](https://user-images.githubusercontent.com/51681379/91309370-31482880-e7b9-11ea-8d66-f90aebb2590b.png)
5. Customer with checked "Allow remote shopping assistance" option is created on additional website
6. Share Customer Accounts=Per Website

### Steps to reproduce (*)

1. Go to Store->Configuration->General
2. Change Scope to additional website( e.g., `New Website`)
3. Set Website Restrictions->Access Restriction=Website Closed
![image](https://user-images.githubusercontent.com/51681379/91312045-7457cb00-e7bc-11ea-8b68-f36a875b001a.png)
4. Go to Customers->All Customers
5. Click Edit action for customer that was created on additional website
6. Click on Login as Customer

### Expected result (*)

1. Explanation message why all stores are not available for select is shown in modal window

### Actual result (*)

1. Disabled store is preselected when all stores are not available to select
![image](https://user-images.githubusercontent.com/51681379/91315340-42e0fe80-e7c0-11ea-8836-bcbbc06f810e.png)
2. Admin is able to click on Login as Customer button in "Login as Customer: Select Store" modal window
3. Admin is redirected to customer grid and notice message "Login as Customer cannot be logged in restricted website." is shown
![image](https://user-images.githubusercontent.com/51681379/91315482-686e0800-e7c0-11ea-9030-dc39b16d3ffd.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by teodoramoldovan** [comment] 2021-08-24 13:17
@magento give me 2.4.1-develop instance

**Comment by engcom-November** [comment] 2021-09-24 06:54
Verified the issue on Magento 2.4-develop branch having EE modules enabled and is reproducible.
But since Share Customer Accounts is set to "Per Website", user is not able to select other store views which is expected behavior regardless of whether the store is disabled/enabled - Same behavior is present
Since the customer is created on other website - Regardless of whether the website is enabled/disabled - the store is pre selected in "Login as Customer" popup model
However, on selecting the disabled websites - Error popup model "Logged in as customer cannot be logged in restricted website" error message is displayed.
Current Magento behavior does not show any explanation message if other store views cannot be selected in Login as Customer Model popup. It can be considered as feature request to introduce this new feature. Please provide your inputs on this.
Thank you.
![image](https://user-images.githubusercontent.com/60198231/134631223-8d344278-d119-499e-9d63-7939c76d2a05.png)
![image](https://user-images.githubusercontent.com/60198231/134631258-5a46fcef-4398-4b6e-94dc-cd6a0dbe1122.png)

**Comment by engcom-November** [comment] 2021-10-08 06:29
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-10-08 06:29 UTC
Labels: Project: Login as Customer, Issue: needs update, Reported on 2.4.1
