### ISSUE TITLE
Issue occuring on multi-address-checkout when there are different currencies are setup, the shipping price creating issue.

### ISSUE THREAD

**Issue by gitgitmunassir** [magento/magento2#37791] opened 2023-07-24 12:03 UTC
### Preconditions and environment

- Magento version -> 2.4.6-p1
- Currency setup:
    - Base Currency: US Dollar.
    - Default Display Currency: Indian Rupee.

### Steps to reproduce

1. Place an order with the multiaddress checkout
2. Check the Shipping price, find the attachment for the same.
![Screenshot from 2023-07-24 17-17-40](https://github.com/magento/magento2/assets/105411426/6533f575-cf78-46c9-b498-b3781553c274)
![Screenshot from 2023-07-24 17-18-42](https://github.com/magento/magento2/assets/105411426/a2a86ac4-9ec0-4353-a5f1-78439635d4de)

### Expected result

Shipping prices should be converted according to the currency rates.
![Screenshot from 2023-07-24 17-31-48](https://github.com/magento/magento2/assets/105411426/bb2f8954-d384-4636-b4e7-b88bfd360e58)

### Actual result

Currency is not converting according to currency rates.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by BeggiNN** [comment] 2023-07-24 12:16
@magento add to contributors team

**Comment by engcom-Bravo** [comment] 2023-07-25 10:45
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-07-25 13:15
Hi @gitgitmunassir,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Place an order with the multiaddress checkout
- Check the Shipping price, find the attachment for the same.


<img width="1395" alt="Screenshot 2023-07-25 at 4 37 15 PM" src="https://github.com/magento/magento2/assets/51680745/691ee784-6c1f-46a0-ad37-97e47a2dc350">



<img width="1418" alt="Screenshot 2023-07-25 at 4 51 28 PM" src="https://github.com/magento/magento2/assets/51680745/1f8ef21c-a044-4a06-8d7e-ca0f3135f92d">

Currency rates are converting successfully as per the configuration.

As per this document https://experienceleague.adobe.com/docs/commerce-admin/config/general/currency-setup.html?lang=en the fixer.io service is deprecated and replaced with the FIxer API.Please refer the document and try to use APILAYER.

<img width="1140" alt="Screenshot 2023-07-25 at 4 52 45 PM" src="https://github.com/magento/magento2/assets/51680745/4d7105d4-8c46-47e0-9e5a-b3004c970049">





Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by gitgitmunassir** [comment] 2023-07-25 13:35
Hi @engcom-Bravo thanks for your response,

What if I do not use the **Fixer API Layer** API Key and set the currency rates manually?

I have tried it with **Fixer API Layer** by setting the currency rates manually but the issue still occurred.

Thanks.

**Comment by gitgitmunassir** [comment] 2023-07-26 07:54
Hii @engcom-Bravo can you please guide me on this?

**Comment by engcom-Bravo** [comment] 2023-07-26 14:01
Hi @gitgitmunassir,

Thanks for your update.

Please refer this document regarding currency rates https://experienceleague.adobe.com/docs/commerce-admin/stores-sales/site-store/currency/currency-update.html?lang=en and also this document https://experienceleague.adobe.com/docs/commerce-admin/config/general/currency-setup.html?lang=en and kindly let us know if you are still facing any issue.

Regarding updating currency rates manually.

<img width="921" alt="Screenshot 2023-07-26 at 11 49 49 AM" src="https://github.com/magento/magento2/assets/51680745/a6a5e36c-84f4-4d16-9e30-02f45cd92cb1">

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-08-07 06:11
Hi @gitgitmunassir,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-08-07 06:11 UTC
Labels: Issue: needs update, Reported on 2.4.6-p1
