### ISSUE TITLE
Can't anyone realy create a tutorial how to add dropdown and input to shipping methods?

### ISSUE THREAD

**Issue by user3748173** [magento/magento2#7494] opened 2016-11-20 07:22 UTC
Sorry for posting in this forum I know the rules, but I do not know anywhere else where it would be more suitable. Because it has been so much asked in magento.stackexchange (and magento forum) and those questions have not got answers. 

In magento 1.X the developers just edited the phtml file that displayed the shipping method (can be found, when searched) but in magento 2.x uses html files where php can't be used. **Examples: where dropdown is needed is - some countries uses post-offices (list of offices displayed in webpage) where customers can get their orders; where input form would be needed is if shop owner wants to ask clients address only when specific shipping method has been selected.**

I am beginner developer and have tried to search a way how to make it possible in Magento 2 but have not found any. I assume that this might be also reason why some shops in those countries won't go over using Magento 2 - or i have just too little experience to create such module and the community tries to keep it a secret? :(  

[Woocommerce offers that option why not Magento2 ?](https://docs.woocommerce.com/document/woocommerce-checkout-add-ons/)

![test](https://cloud.githubusercontent.com/assets/23082054/20480575/cd3fe336-afeb-11e6-8937-556df57c85d6.png)

**Comment by veloraven** [comment] 2016-11-24 12:08
@user3748173 thank you for your feedback.
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you think it to be an issue (including lack of documentation) please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. Please, also identify which version of Magento you are running.
Also you can submit an improvement to the [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by user3748173** [comment] 2016-11-24 16:32
I have tried both Community Forums (programming section) and Magento Stack Exchange! Both of these websites contains a lot of questions about checkout page (like the one i have asked here) without no replies. Is it because developers lack such knowledge or something else that is unclear. I have found this [post](https://github.com/magento/magento2/issues/3793) that also have trouble with checkout page. The main problem is that magento 2 official sample modules github repository and documentations only contains possibility to add text as shipping method. The documentation also lacks a ways how to manage form validation (Example: from selected shipping method depends if address field is required or not). It seems to me like the developers had only one specific group in mind when writing checkout page (customers that order their product to their homes/workplaces or come to the shop to pick up).
I have tired to solve it myself but I do not like none of the solutions that i have came up with: adding the selection field with jQuery (somehow adding it to the order) below shipping method its content depends on shipping method that is selected (main disadvantage is that it might decrease the speed) or writing completely new shipping module that contains this possibility (I have not enough knowledge to do it and i am afraid of updates in default module that might depend or change the shipping method - writing new module means writing over many default files).  
**I find those functionalities elementary in such cms and can not understand why they are not added. Why developers have not thought about that user group - Magento is used all over the globe and so should be the features that can be added without changing too much the original code?**  
I did not look at the  "Magento 2 Feature Requests and Improvements forum" because: I did not get any answers in the programming section, none guided me to that section of the forum, and even if I had known I doubt for now that anyone would have bothered or known what to answer in there.

**Comment by user3748173** [comment] 2016-11-24 18:28
Looking to the website  "Magento 2 Feature Requests and Improvements forum". It seems to me that the website is not known very well among Magento 2 users - Posts from two weeks ago has been without any replies also yesterdays post. Most recent post with answer is about month old. The up-votes have not been many in most popular post only 30. Does it really should take a month to get any feedback?

**Comment by vzabaznov** [comment] 2016-12-09 09:19
closed as we don't receive update more than 2 week, @user3748173 please feel free to write here/reopen or to open new issue

**Closed as completed by vzabaznov** 2016-12-09 09:19 UTC
Labels: Progress: needs update
