### ISSUE TITLE
Braintree order email not displaying credit card type/number label

### ISSUE THREAD

**Issue by middlegrey** [magento/magento2#6568] opened 2016-09-11 10:04 UTC
Upgraded from CE 2.0.7 to CE 2.1.1 using Composer

When orders are placed using Braintree Payments, the order email shows –

cc_type           Visa
cc_number   xxxx-1234

Instead of –

Credit Card Type            Visa
Credit Card Number  xxxx-1234

![order-email](https://cloud.githubusercontent.com/assets/18087322/18416539/8469cb60-7817-11e6-94a5-097002e9b950.jpg)

**Comment by iivashchenko** [comment] 2016-09-16 13:55
Hi @middlegrey, thanks for the feedback, but we can't reproduce your issue as described. Could you please provide more detailed steps we must follow to reproduce this issue. If possible, identify the web server you are running, the versions of PHP and MySQL, logs would be helpful too.

**Comment by middlegrey** [comment] 2016-09-16 14:04
Hi @iivashchenko, thanks for following up.

The server is running Apache 2.4.23 with PHP 5.6.25 and MySQL 5.6.31.

The steps to reproduce are the standard ones to purchase a product, albeit with a custom shipping module to calculate shipping cost.

Which logs would you like exactly?

**Comment by iivashchenko** [comment] 2016-09-19 08:12
I've meant log files from /var/log folder within your root Magento installation. exception.log and system.log files may contain information concerning your issue.

**Comment by middlegrey** [comment] 2016-09-30 20:12
I've checked the logs and there doesn't seem to be anything relevant. I also tried re-installing everything from scratch but the problem still remains.

Can you direct me to the module and/or methods responsible for generating the email payment details so I can try to track down the issue?

**Comment by iivashchenko** [comment] 2016-11-04 15:56
Try to debug: `app\code\Magento\Sales\Model\Order\Email\Sender\OrderSender::prepareTemplate`
The `$transport['payment_html]` variable must contain required template data.

**Comment by antbates91** [comment] 2016-11-14 08:21
I can confirm I'm also having this issue with Magento 2.1.2, PHP 7.0.7 and MySQL 5.6. 

We originally had Magento 2.0.7 installed and upgraded to 2.1.0, then 2.1.2. 

I've also noticed this same issue with PayPal too. The email renders payerEmail instead of the translation.

![image](https://cloud.githubusercontent.com/assets/8401438/20257712/53b57902-aa43-11e6-8435-274b9c0baa6b.png)

![image](https://cloud.githubusercontent.com/assets/8401438/20257713/56be4f8e-aa43-11e6-8958-cd9c9b0f7bec.png)

**Comment by iivashchenko** [comment] 2017-01-19 14:37
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Comment by antbates91** [comment] 2017-01-19 14:51
@iivashchenko This issue is still present in 2.1.3

PHP 7.0.7 / 7.0.13 and MySQL 5.6. 

Our upgrade path was Magento 2.0.7 -> 2.1.0 -> 2.1.2 -> 2.1.3.

![image](https://cloud.githubusercontent.com/assets/8401438/22111299/c37d24aa-de56-11e6-9106-3dc57891df62.png)

**Comment by iivashchenko** [comment] 2017-01-20 11:08
@antbates1991, thank you. We will try to reproduce it according to your upgrade path.

**Comment by staffrob** [comment] 2017-02-18 03:37
Same issue here on 2.1.4
Upgrade path 2.1.1 -> 2.1.2 -> 2.1.3 -> 2.1.4
This is the least of our issues but just confirming

**Comment by iivashchenko** [comment] 2017-02-20 14:00
@antbates1991, I've tested an upgrade circle of my Magento instance from 2.0.7 through 2.1.0, 2.1.2 to 2.1.3 with Braintree Payment configured. On every newly upgraded instance, I made one order via Braintree payment and didn't face a described issue. 

My upgrade process includes the next steps:
> composer require magento/product-community-edition 2.1.x --no-update
>composer update
>php bin/magento setup:upgrade
>php bin/magento setup:static-content:deploy
>php bin/magento indexer:reindex

Please, let me know if I missed something or what extra steps should I do to reproduce an issue. Thanks.

**Comment by irevdev** [comment] 2017-07-16 19:58
Hi @iivashchenko 

Having same issue on 2.1.5 CE 

<img width="565" alt="screen shot 2017-07-17 at 7 53 22 am" src="https://user-images.githubusercontent.com/4889559/28250785-14fc2bbe-6ac5-11e7-8dc1-3070855ea65a.png">

With locale options set to:
<img width="1150" alt="screen shot 2017-07-17 at 7 56 42 am" src="https://user-images.githubusercontent.com/4889559/28250805-89b3cfb6-6ac5-11e7-9657-1ec275243635.png">

Theme has en_NZ translation file and all translations work fine on frontend.  

Ran all of the above mentioned steps 
composer require magento/product-community-edition 2.1.5 --no-update
composer update
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy
php bin/magento indexer:reindex

But issue still remains.

Cheers

**Comment by gboz17** [comment] 2017-07-17 16:05
I'm having the same problem with 2.1.7. 

It is showing up in the email and the customer account section.

**Comment by iivashchenko** [comment] 2017-07-24 10:53
@irevdev, thank you for configuration settings which helped me to reproduce the bug. I've linked this GitHub issue to internal ticket MAGETWO-70958.

**Comment by gboz17** [comment] 2017-08-01 21:56
For some reason, Braintree's language file is not working (located in yourmagentoinstall/vendor/magento/module-braintree/i18n/en_US.csv

As a workaround, add the following to your language file:

"cc_type","Credit Card Type",module,Magento_Braintree
"cc_number","Credit Card Number",module,Magento_Braintree
"avsPostalCodeResponseCode","AVS Postal Code Response Code",module,Magento_Braintree
"avsStreetAddressResponseCode","AVS Street Address Response Code",module,Magento_Braintree
"cvvResponseCode","CVV Response Code",module,Magento_Braintree
"processorAuthorizationCode","Processor Authorization Code",module,Magento_Braintree
"processorResponseCode","Processor Response Code",module,Magento_Braintree
"processorResponseText","Processor Response Text",module,Magento_Braintree
"braintree", "Braintree",module,Magento_Braintree
"liabilityShifted", "Liability Shifted",module,Magento_Braintree
"liabilityShiftPossible", "Liability Shift Possible",module,Magento_Braintree
"riskDataId", "Risk ID",module,Magento_Braintree
"riskDataDecision", "Risk Decision",module,Magento_Braintree
"paymentId", "Payment Id",module,Magento_Braintree
"payerEmail", "Payer Email",module,Magento_Braintree
"sale","Sale",module,Magento_Braintree
"credit","Credit",module,Magento_Braintree
"authorization_expired","Authorization expired",module,Magento_Braintree
"authorizing","Authorizing",module,Magento_Braintree
"authorized","Authorized",module,Magento_Braintree
"gateway_rejected","Gateway rejected",module,Magento_Braintree
"failed","Failed",module,Magento_Braintree
"processor_declined","Processor declined",module,Magento_Braintree
"settled","Settled",module,Magento_Braintree
"settling","Settling",module,Magento_Braintree
"submitted_for_settlement","Submitted for settlement",module,Magento_Braintree
"voided","Voided",module,Magento_Braintree
"unrecognized","Unrecognized",module,Magento_Braintree
"settlement_declined","Settlement declined",module,Magento_Braintree
"settlement_pending","Settlement pending",module,Magento_Braintree
"settlement_confirmed","Settlement confirmed",module,Magento_Braintree
"paypal_account","Paypal account",module,Magento_Braintree
"coinbase_account","Coinbase account",module,Magento_Braintree
"europe_bank_accout","Europe bank account",module,Magento_Braintree
"credit_card","Credit card",module,Magento_Braintree
"apple_pay_card","Apple pay card",module,Magento_Braintree
"android_pay_card","Android pay card",module,Magento_Braintree

**Comment by magento-engcom-team** [comment] 2017-10-19 14:30
@middlegrey, thank you for your report.
We've created internal ticket(s) MAGETWO-70958 to track progress on the issue.

**Comment by fireatwill** [comment] 2018-09-20 22:45
I'm seeing the same issue with 2.2.5, and 2.2.6, and with other payment modules. These are new installs, so in my case not upgrade path related.

Having the store locale (Configuration / General / Locale Options / Locale) set to anything other than English (United States) seems to cause this problem. In my case, I'm using English (United Kingdom). If I set the locale back to English (United States), the email text works properly.

It seems to be related to translation fallback - the payment module has i18n/en_US.csv with translations for cc_type etc., but because the locale is en_GB, not en_US, the fallback seems to be to use the original text string (in this case "cc_type" for example) instead of the en_US translation.

**Comment by gulshanchitransh** [comment] 2019-05-14 07:19
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-05-14 07:19
Hi @gulshanchitransh. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-05-14 07:20
Hi @gulshanchitransh, here is your [Magento instance](https://i-6568-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-6568-2-3-develop.instances.magento-community.engineering/admin](https://i-6568-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sheshagiriAnvekar** [comment] 2020-08-20 11:17
Is this issue solved in 2.3.5 p1 ?

**Comment by magento-engcom-team** [comment] 2020-11-30 21:48
The report related to technology or functionality that was removed(or not supported) from the Magento code-base.
Or cannot be fixed and delivered in the scope of this public repository.

Examples:
- Removed payment methods. [Magento Commerce 2.4.0 Release Notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-commerce.html), [Deprecation of Magento core payment integrations](https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445). All questions, issue reports, and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
- Mysql search. Replaced with Elasticsearch 
- Not [Supported browsers](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#supported-browsers)
- Not supported [Operating systems](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#operating-systems-linux-x86-64)
- Web Wizard install
- Not a bug 
- etc

**Closed as completed by magento-engcom-team** 2020-11-30 21:48 UTC
Labels: bug report, Component: Payment, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Progress: ready for dev
