### ISSUE TITLE
One or more indexers are invalid. Make sure your Magento cron job is running. please help.

### ISSUE THREAD

**Issue by garunna** [magento/magento2#37501] opened 2023-05-15 14:05 UTC
### Preconditions and environment

- Magento version: 2.4.6, installed in hostgator sofaculous.
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

ran reindex

### Expected result

shows: 
Catalog Search index process error during indexation process:
Could not ping search engine: No alive nodes found in your cluster

### Actual result

now can not create new product.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-05-16 13:34
Hi @garunna,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**
1.ran reindex. `bin/magento indexer:reindex && bin/magento c:f`

reindex completed successfully.

<img width="768" alt="Screenshot 2023-05-16 at 11 52 05 AM" src="https://github.com/magento/magento2/assets/51680745/994dc014-a41b-4d16-bdbf-390b94652ef3">



To configure CRON jobs please refer this document https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/cli/configure-cron-jobs.html.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.

Thanks.

**Comment by LeanderFS** [comment] 2023-05-17 10:27
@garunna The error you're facing means that Magento cannot reach your Elasticsearch instance. Ensure the instance is running and accepting connections on the hostname and port as configured. Refer to the experience league for detailed information: [Ensure Elasticsearch is installed properly
](https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/troubleshooting/elasticsearch/ensure-elasticsearch-is-installed-properly.html?lang=en)

**Comment by engcom-Bravo** [comment] 2023-05-30 06:17
Hi @garunna,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-05-30 06:17 UTC
Labels: Issue: needs update, Reported on 2.4.6
