### ISSUE TITLE
Category::getUrl() should not fetch 301 redirect

### ISSUE THREAD

**Issue by kweij** [magento/magento2#38152] opened 2023-11-06 14:36 UTC
### Preconditions and environment

- Magento version: 2.4.6-p3

### Steps to reproduce

1. Create a category in the Admin
  URL Key is now auto-generated, system/auto-generated URL Rewrite is created (redirect_type = 0)
2. Change category URL Key
  System/auto-generated URL Rewrite is updated to a 301 from old to new (redirect_type = 301)
  A new system/auto-generated URL Rewrite is added (redirect_type = 0) from new tot internal route
3. Enable canonical URLs
  `bin/magento config:set catalog/seo/category_canonical_tag 1`
4. View the category in the frontend

State in the database with example data:

![image](https://github.com/magento/magento2/assets/2248429/f65d497c-1d8b-4c2a-a3d9-0258411c0b3e)

### Expected result

Canonical URL === New category URL Key

### Actual result

Canonical URL === Old category URL Key

### Additional information

In `\Magento\Catalog\Model\Category.php::getUrl()` URL rewrites are loaded for the category by ID and store. This returns the first result, which is the 301 redirect from the old to the new category URL. The `request_path` of this rewrite is used to form the return value of `Category.php:getUrl()`, which contains the old URL.

The fix is that only the system/auto-generated URL rewrite is loaded. Therefor the array param provided to `\Magento\UrlRewrite\Model\UrlFinderInterface::findOneByData()` in `vendor/magento/module-catalog/Model/Category.php:613` should be extended with `UrlRewrite::REDIRECT_TYPE => 0,`. The same addition is already in place for `\Magento\Catalog\Model\Product\Url::getProductUrl()`, but missing for categories.

### Release note

Note that I've only yet encountered this issue in the category canonicals, but since the issue resides in `Category.php:getUrl()`, there are probably other area's where this bug causes an issue.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by kweij** [comment] 2023-11-06 14:50
@magento The issue is reproducible on the vanilla Magento instance

**Comment by engcom-Bravo** [comment] 2023-11-07 11:40
Hi @kweij,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Create a category in the Admin
- URL Key is now auto-generated, system/auto-generated URL Rewrite is created (redirect_type = 0)
- Change category URL Key
- System/auto-generated URL Rewrite is updated to a 301 from old to new (redirect_type = 301)
- A new system/auto-generated URL Rewrite is added (redirect_type = 0) from new tot internal route
- Enable canonical URLs
- bin/magento config:set catalog/seo/category_canonical_tag 1
- View the category in the frontend


<img width="1418" alt="Screenshot 2023-11-07 at 2 25 11 PM" src="https://github.com/magento/magento2/assets/51680745/a20e5e9e-0dfa-411f-bd25-12a37b11c365">



<img width="1462" alt="Screenshot 2023-11-07 at 2 26 10 PM" src="https://github.com/magento/magento2/assets/51680745/c8735ee7-5f58-40c1-9b31-f0df89dab632">



<img width="1461" alt="Screenshot 2023-11-07 at 2 27 26 PM" src="https://github.com/magento/magento2/assets/51680745/e14cc944-46fd-4cdf-825f-483182b8182f">



In frontend the category url is changed to new url key but the canonical url is still in old url key.

Hence Confirming the issue.

Thanks.

**Comment by hostep** [comment] 2023-12-27 20:32
Seems to be fixed by [ACP2E-2481: Category Canonical URLs not working](https://github.com/magento/magento2/commit/3adc18f407cb74e4074099092d38f496bb5cc7f0), so we can close this issue down I guess.

**Comment by engcom-Bravo** [comment] 2023-12-28 07:51
Hi @kweij,

The issue is fixed under this commits : https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-2481&type=commits

Hence we are Closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2023-12-28 07:51 UTC
Labels: Issue: Confirmed, Component: Url, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: SEO, Reported on 2.4.6-p3
