### ISSUE TITLE
Backend redirects to 404

### ISSUE THREAD

**Issue by Taral-Patoliya** [magento/magento2#2278] opened 2015-11-06 14:00 UTC
When I changes the port to 8080 from 80, and tried to access the backend, it redirected me to 404,
This is due to the isHostBackend() method in Magento\Backend\App\Area\FrontNameResolver
returns false,
The $backendHost and $_SERVER['HTTP_HOST']) are not the same.

**Comment by kassner** [comment] 2015-11-06 14:03
I guess this is somehow related to `Auto-redirect to Base URL` as in #2272

**Comment by arkadiych** [comment] 2015-11-06 16:53
Internally tracking - MAGETWO-45105

**Comment by danslo** [comment] 2015-11-06 17:57
Can confirm this issue, and fixed it with following diff:

```diff
diff --git app/code/Magento/Backend/App/Area/FrontNameResolver.php app/code/Magento/Backend/App/Area/FrontNameResolver.php
index ab4e9eb..a375fb4 100644
--- app/code/Magento/Backend/App/Area/FrontNameResolver.php
+++ app/code/Magento/Backend/App/Area/FrontNameResolver.php
@@ -85,7 +85,7 @@ class FrontNameResolver implements \Magento\Framework\App\Area\FrontNameResolver
     {
         $backendUrl = $this->configInterface->getValue(Store::XML_PATH_UNSECURE_BASE_URL, ScopeInterface::SCOPE_STORE);
         $backendHost = parse_url(trim($backendUrl), PHP_URL_HOST);
-        $host = isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : '';
+        $host = isset($_SERVER['SERVER_NAME']) ? $_SERVER['SERVER_NAME'] : '';
         return (strcasecmp($backendHost, $host) === 0);
     }
 }
```

**Comment by davidalger** [comment] 2015-11-10 21:50
Closing as duplicate of #2272

**Comment by mazhalai** [comment] 2015-11-13 16:21
@Taral-Patoliya  Please try again, this has been fixed in RC2.

**Closed** 2015-11-13 18:24 UTC

**Comment by 100rabhMisra** [comment] 2016-06-14 12:39
after installation magento2, it redirected me to 404, not open admin panel ?
how to fix it can you any one tell me ??

**Comment by benmarks** [comment] 2016-06-16 11:38
@100rabhMisra please do not comment on closed issues. Moreover, support questions should be asked on the [Magento forums](http://community.magento.com/) or at [Magento SE](http://magento.stackexchange.com/).
