### ISSUE TITLE
Magento 2.2.5 Order Email Confirmation is not working

### ISSUE THREAD

**Issue by nilesh111091** [magento/magento2#17781] opened 2018-08-24 08:16 UTC
Order email confirmation and all sales emails are not working. 
In Advanced > System > Mail sending settings ->
Disable Email Communications set to "No"
Also set host and username password and port details too. Still not working.
![image](https://user-images.githubusercontent.com/42668713/44573349-067b0200-a7a4-11e8-832c-31d5c985862f.png)

**Comment by magento-engcom-team** [comment] 2018-08-24 08:16
Hi @nilesh111091. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nilesh111091 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by nilesh111091** [comment] 2018-08-24 08:19
My magento version is 2.2.5.

**Comment by MartinAarts** [comment] 2018-08-24 09:30
I think this issue is related to #14952

**Comment by gwharton** [comment] 2018-08-25 17:46
Looks like a third party smtp mail module is being used. Do the emails work if you disable the email module?

**Comment by ihor-sviziev** [comment] 2018-08-30 12:40
Duplicate of https://github.com/magento/magento2/issues/14952

**Closed as completed by ihor-sviziev** 2018-08-30 12:40 UTC
Labels: duplicate, Fixed in 2.3.x, Issue: Format is not valid

**Comment by nilesh111091** [comment] 2018-08-30 12:47
Dotmailer extension is conflicting with emails.
Any solutions?

**Comment by jurpro** [comment] 2018-09-14 14:29
Hello. I have the same issue on Magento 2.2.5
Result from sending email is : myusername@hosting something like kukudari@227eg.hosting.com but I was set sender email address is no-reply@mywebsite.com
Is there any fix ?
Thanks

**Comment by gwharton** [comment] 2018-09-15 00:01
As a temprary workaround, until the long term fix is rolled out into Magento, provided you don't need/use Amazon payments, run the command

`bin/magento module:disable Amazon_Core Amazon_Login Amazon_Payment`

to disable the Amazon payments module. This will cause it to start working properly again.

**Comment by magento-engcom-team** [comment] 2019-01-07 19:15
Hi @nilesh111091. Thank you for your report. 
The issue has been fixed in magento/magento2#18471 by @gwharton in 2.3-develop branch
Related commit(s):
 - [ad50297e7bf4ea39db62f0969579a1ca8eb5f1a3](https://github.com/magento/magento2/commit/ad50297e7bf4ea39db62f0969579a1ca8eb5f1a3)
 - [e16ff74e4f5f24a4a2530b6aced6ef50032515e0](https://github.com/magento/magento2/commit/e16ff74e4f5f24a4a2530b6aced6ef50032515e0)
 - [621d2cfeaf8e0a15e592cdc001c856385b3cbd83](https://github.com/magento/magento2/commit/621d2cfeaf8e0a15e592cdc001c856385b3cbd83)
 - [b6f9e48289119117df230b6578ac9ff3d69e4996](https://github.com/magento/magento2/commit/b6f9e48289119117df230b6578ac9ff3d69e4996)
 - [0dc85785e522e2be8c72dfeaee7e9f5054195034](https://github.com/magento/magento2/commit/0dc85785e522e2be8c72dfeaee7e9f5054195034)
 - [122019c953037df74ef97245a42b274eae2e6639](https://github.com/magento/magento2/commit/122019c953037df74ef97245a42b274eae2e6639)
 - [193c6c2f6facf7276c1c8858d29ea3b847062ef5](https://github.com/magento/magento2/commit/193c6c2f6facf7276c1c8858d29ea3b847062ef5)
 - [bd0aa57cc837918335015d051f08cf380dc186d0](https://github.com/magento/magento2/commit/bd0aa57cc837918335015d051f08cf380dc186d0)
 - [523b0464966f81f1f01aa13073092bfddf363219](https://github.com/magento/magento2/commit/523b0464966f81f1f01aa13073092bfddf363219)
 - [424929fe9aee1005601cc2c9c7ad0090741be723](https://github.com/magento/magento2/commit/424929fe9aee1005601cc2c9c7ad0090741be723)
 - [c32ca7a0d58cbc57276349b26eb5ecd38451fd2d](https://github.com/magento/magento2/commit/c32ca7a0d58cbc57276349b26eb5ecd38451fd2d)
 - [e39ce7a3f2a7e6ee134cff9a097b7321756c32cf](https://github.com/magento/magento2/commit/e39ce7a3f2a7e6ee134cff9a097b7321756c32cf)
 - [99621b32f8c7d3d12f83db7e67f5f1c1ef3e7f31](https://github.com/magento/magento2/commit/99621b32f8c7d3d12f83db7e67f5f1c1ef3e7f31)
 - [f171c9d6ab035439ffb6374ec14dd8d51123dcd2](https://github.com/magento/magento2/commit/f171c9d6ab035439ffb6374ec14dd8d51123dcd2)

The fix will be available with the upcoming 2.3.1 release.

**Comment by pratikhmehta** [comment] 2019-01-09 06:53
The transportbuilderbystore class has already been deprecated in 2.3 and soon will be in 2.2.

> This will also work in Magento 2.2.7

https://magento.stackexchange.com/a/257215/68619
