### ISSUE TITLE
Synchronization for media gallery with CLI failed (*.webp and *.svg) in production mode

### ISSUE THREAD

**Issue by bonanzadigger** [magento/magento2#39009] opened 2024-08-05 12:37 UTC
### Preconditions and environment

Installed Magento v2.4.7-p1 with all media gallery modules activated and also all adobe stock modules
Set deploy-mode to production (./bin/magento deploy:mode:set production)

### Steps to reproduce

Upload a new *.webp image or *.svg image per ftp somewhere in pub/media directory
**Set deploy-mode to production (./bin/magento deploy:mode:set production)**
Perform _**php bin/magento media-gallery:sync**_

### Expected result

Synchronization pass successfully

### Actual result

Following error occurred:
In Synchronize.php line 83:
**Failed to execute the following synchronizers: media_gallery_asset_synchronizer**
media-gallery:sync

### Additional information

In developer mode, tha above mentioned exception will not be thrown.
AREA: Backend

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2024-08-07 13:03
Hi @bonanzadigger ,

Thanks for your reporting and collaboration.
We have verified the issue in latest 2.4-develop instance, but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce**
1. Upload a .svg image somewhere in pub/media directory
![image](https://github.com/user-attachments/assets/4428161d-7e30-4768-9271-a6e670730242)
2. Enable production mode - ./bin/magento deploy:mode:set production
![image](https://github.com/user-attachments/assets/ed44524a-c88e-4b67-8256-667527f5d8ae)
3. Run php bin/magento media-gallery:sync
![image](https://github.com/user-attachments/assets/a5b662e9-e653-4b25-b7fe-dfd56e09df71)

Observe synchronization is successful.  Please let us know if any other steps are needed to be performed.

Thanks.

**Comment by engcom-Delta** [comment] 2024-08-27 08:24
Hi @bonanzadigger ,

We have noticed that this issue has not been updated since long time.
Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Delta** 2024-08-27 08:24 UTC
Labels: Component: MediaGallery, Issue: needs update, Area: Content, Reported on 2.4.7-p1
