### ISSUE TITLE
Product name wise sorting not working

### ISSUE THREAD

**Issue by sunilit42** [magento/magento2#36076] opened 2022-09-02 11:48 UTC
### Preconditions and environment

- lastest magento
- add product 
- create category and assign that product
- consider page limit per page 12

### Steps to reproduce

- Category and that related product
- open that category page
- elasticsearch configure
- click on sort by product name
- find that first product that category into backend add store wise name entry
- open that category page
- you will page limit 12 but it is showing 11 if you do store wise entry

### Expected result

- it should be show all 12 products

### Actual result

- it is showing 11 products 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sunilit42** [comment] 2022-09-02 11:49
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by engcom-November** [comment] 2022-09-20 03:23
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-09-20 04:15
Hi @sunilit42 , Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop branch but the issue is not reproducible. Sort By Product Name - All 12 products are getting displayed per page and sorting is working on alphabetical order in the category page
![image](https://user-images.githubusercontent.com/60198231/191166105-e73b3791-ccd8-4aa0-bd9e-7a8d979b797e.png)
Kindly recheck the issue on Magento 2.4-develop branch as it is having latest code base and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by sunilit42** [comment] 2022-09-20 05:43
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php#L239

Check this line , here is bug

if we enter name store wise name, coding doing sorting based on global name

i found that issue with EE endition and here may be also

**Comment by mirianfalconi** [comment] 2022-09-22 18:59
@magento I am working on this

**Comment by mirianfalconi** [comment] 2022-09-22 18:59
@magento add to contributors team

**Comment by mirianfalconi** [comment] 2022-09-22 19:01
@magento add to contributors team

**Comment by mirianfalconi** [comment] 2022-09-22 19:02
@magento I am working on this

**Comment by engcom-November** [comment] 2022-09-28 04:23
Verified the issue again on Magento 2.4-develop instance but observed below different issue on Admin - Categories page.
Steps performed:
1. Saved 12 products with different product names in All Store views scope, Default store view scope and other website scope
2. Clean cache
3. Verified front end - Category page of main website and other website
4. sort by Product Name - No issue found
Sorting working as expected and 12 products displayed per page.
5. Verified Admin - Categories page - All Store Views scope - Products in Category - Default view - No issue. 
Product names displayed as expected
Sort by Product Name - Issue: After applying sorting - Product names got changed to default store view product names. 
Bug logged for the same: https://github.com/magento/magento2/issues/36208
Issue verification is in progress for Enterprise edition.

**Comment by engcom-November** [comment] 2022-09-29 05:44
Verified the issue again on Magento 2.4-develop instance and the issue is reproducible for other website store (Other than default website). Hence confirming this issue.
![image](https://user-images.githubusercontent.com/60198231/192948650-a62dd5c3-cc3d-4053-8a40-ab7bc0492a8f.png)
![image](https://user-images.githubusercontent.com/60198231/192948720-f4ab56ce-64d4-4ee0-a040-a42bbd941111.png)

**Comment by sunilit42** [comment] 2022-09-29 06:45
To fix issue

diff --git a/vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php b/vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php
index 97cb92ab..d57cc7e2 100755
--- a/vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php
+++ b/vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php
@@ -236,13 +236,27 @@ class SearchResultApplier implements SearchResultApplierInterface
                 $entityTypeId = $this->collection->getEntity()->getTypeId();
                 $entityMetadata = $this->metadataPool->getMetadata(ProductInterface::class);
                 $linkField = $entityMetadata->getLinkField();
-                $query->joinLeft(
+                $query->joinInner(
                     ['product_var' => $this->collection->getTable('catalog_product_entity_varchar')],
                     "product_var.{$linkField} = e.{$linkField} AND product_var.attribute_id =
                     (SELECT attribute_id FROM eav_attribute WHERE entity_type_id={$entityTypeId}
-                    AND attribute_code='name')",
+                    AND attribute_code='name') AND product_var.store_id='0'",
                     ['product_var.value AS name']
                 );
+
+                $query->joinLeft(
+                    ['product_var_store' => $this->collection->getTable('catalog_product_entity_varchar')],
+                    "product_var_store.{$linkField} = e.{$linkField} AND product_var_store.attribute_id =
+                    (SELECT attribute_id FROM eav_attribute WHERE entity_type_id={$entityTypeId}
+                    AND attribute_code='name') AND product_var_store.store_id='$storeId'",
+                    ['product_var_store.value AS name_store']
+                );
+
+                $query->columns([
+                    'name' => new \Zend_Db_Expr(
+                        $connection->getIfNullSql('product_var_store.value', 'product_var.value')
+                    ),
+                ]);
             } elseif ($field === 'price') {
                 $query->joinLeft(
                     ['price_index' => $this->collection->getTable('catalog_product_index_price')],

**Comment by sunilit42** [comment] 2022-09-29 06:45
To fix issue

`diff --git a/vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php b/vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php
index 97cb92ab..d57cc7e2 100755
--- a/vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php
+++ b/vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php
@@ -236,13 +236,27 @@ class SearchResultApplier implements SearchResultApplierInterface
                 $entityTypeId = $this->collection->getEntity()->getTypeId();
                 $entityMetadata = $this->metadataPool->getMetadata(ProductInterface::class);
                 $linkField = $entityMetadata->getLinkField();
-                $query->joinLeft(
+                $query->joinInner(
                     ['product_var' => $this->collection->getTable('catalog_product_entity_varchar')],
                     "product_var.{$linkField} = e.{$linkField} AND product_var.attribute_id =
                     (SELECT attribute_id FROM eav_attribute WHERE entity_type_id={$entityTypeId}
-                    AND attribute_code='name')",
+                    AND attribute_code='name') AND product_var.store_id='0'",
                     ['product_var.value AS name']
                 );
+
+                $query->joinLeft(
+                    ['product_var_store' => $this->collection->getTable('catalog_product_entity_varchar')],
+                    "product_var_store.{$linkField} = e.{$linkField} AND product_var_store.attribute_id =
+                    (SELECT attribute_id FROM eav_attribute WHERE entity_type_id={$entityTypeId}
+                    AND attribute_code='name') AND product_var_store.store_id='$storeId'",
+                    ['product_var_store.value AS name_store']
+                );
+
+                $query->columns([
+                    'name' => new \Zend_Db_Expr(
+                        $connection->getIfNullSql('product_var_store.value', 'product_var.value')
+                    ),
+                ]);
             } elseif ($field === 'price') {
                 $query->joinLeft(
                     ['price_index' => $this->collection->getTable('catalog_product_index_price')],
`

**Comment by sunilit42** [comment] 2022-09-29 14:06
@magento I am working on this

**Comment by mirianfalconi** [comment] 2022-10-11 02:47
@magento I am working on this

**Comment by zaximus84** [comment] 2022-11-14 19:24
I ran into this issue as well. To provide additional detail, the problem with the name sort is that it joins the catalog_product_entity_varchar table in a way that can produce multiple rows for the same product in the final query. On my Magento installation we have 3 websites and lots of products have ended up with name values at the default scope and all 3 website scopes.

The final query executed in \Magento\Elasticsearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplier::categoryProductByCustomSortOrder expects to return 12 distinct product ids, but due to joining the scoped names, it returns these 12 rows (where what appear to be duplicates are actually different store ids):

| entity_id | is_salable | position | name |
------------|------------|----------|---------
| 518 | 1 | 123 | Product Name |
| 518 | 1 | 123 | Product Name |
| 518 | 1 | 123 | Product Name |
| 518 | 1 | 123 | Product Name |
| 270 | 1 | 51 | Another Product Name |
| 270 | 1 | 51 | Another Product Name |
| 270 | 1 | 51 | Another Product Name |
| 270 | 1 | 51 | Another Product Name |
| 414 | 1 | 105 | Different Product Name |
| 414 | 1 | 105 | Different Product Name |
| 414 | 1 | 105 | Different Product Name |
| 414 | 1 | 105 | Different Product Name |

As a result, only 518, 270, and 414 are returned, and only those 3 products show on the page. The solution here will be to properly group the query so only 1 row per entity id is returned, though that will be complicated by the need to include the product name for the proper scope for each product.

While not an actual fix for this issue, I worked around it on my installation by completely circumventing the logic with the flawed query. I patched Magento\Elasticsearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplier and replaced this:
```
        $ids = $this->getProductIdsBySaleability();

        if (count($ids) == 0) {
            $items = $this->sliceItems($this->searchResult->getItems(), $this->size, $this->currentPage);
            foreach ($items as $item) {
                $ids[] = (int)$item->getId();
            }
        }
```
with this:
```
        $items = $this->sliceItems($this->searchResult->getItems(), $this->size, $this->currentPage);
        foreach ($items as $item) {
            $ids[] = (int)$item->getId();
        }
```
This removes the logic that's trying to show all in stock products before all the out of stock products, and it instead uses the results from Elasticsearch directly without running the additional query containing the bug.

**Comment by engcom-Delta** [comment] 2024-11-11 13:49
Hi @sunilit42 ,

Thanks for your reporting and collaboration.
We have re-verified the issue in Latest 2.4-develop instance , but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce**
1. Create multiple websites
2. Category and that related product
3. open that category page
4. click on sort by product name
5. find that first product that category into backend add store wise name entry
6. open that category page
7. Observe all 12 products are displaying with sort applied.
![image](https://github.com/user-attachments/assets/896fd36c-e921-404b-802f-6ed7e05bff56)

Can you please re-verify and confirm if you are still facing the issue.
Thanks.

**Comment by engcom-Delta** [comment] 2024-11-22 09:53
Hi @sunilit42 ,

This issue is being closed since it has not been updated in a long time.
Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.

**Closed as completed by engcom-Delta** 2024-11-22 09:53 UTC
Labels: Component: Catalog, Reproduced on 2.4.x, Priority: P2, Progress: done, Issue: needs update, Reported on 2.4.x, Area: Catalog, Reported on 2.4.5
