### ISSUE TITLE
Pricing changing in chart and other areas

### ISSUE THREAD

**Issue by leslilcp** [magento/magento2#35179] opened 2022-03-10 21:58 UTC
### Summary (*)
 The pricing of products are changing to pricing I did not put in. I check the products in Magento and all the pricing is correct and no discounts were added. The pricing shows it correct when you click on the item from the check but as soon as you add it to the chart it changes. The total of the chart says the correct pricing as well so I have no idea what is going on.  It is doing this for multiple products and across all my websites. 

### Examples (*)
 

- [ ] 
![269 90](https://user-images.githubusercontent.com/101366526/157761687-24fcc229-5d39-42c1-b72e-60e071b840ea.JPG)

![chart](https://user-images.githubusercontent.com/101366526/157761630-6e688b84-a5b8-42f4-8f2b-b7eed2807fd8.JPG)

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-03-11 10:28
Hi @leslilcp ,
Thank you for reporting and collaboration. However we are unable to reproduce the issue on Magento 2.4-develop branch:
![image](https://user-images.githubusercontent.com/60198231/157848093-45886d23-fef4-4c4a-8200-36292232892d.png)

Also looks like this issue is a duplicate of https://github.com/magento/magento2/issues/33798. Kindly check the updates on this: https://github.com/magento/magento2/issues/33856#issuecomment-904606945
Similar issue- https://github.com/magento/magento2/issues/33856 was fixed in the 2.4-develop branch in [ae304d4,](https://github.com/magento/magento2/commit/ae304d43cd36322b1ff8145d70c9b2e9aeb0cde)

Kindly recheck the issue on Magento 2.4-develop branch as is the upcoming 2.4.x release and have latest code base and elaborate steps to reproduce if the issue is still reproducible.
Thank you.

**Comment by leslilcp** [comment] 2022-03-11 14:52
How do I do that? Trying to get this fixed asap.

**Comment by engcom-November** [comment] 2022-03-14 12:56
Hi @leslilcp ,
You can try applying the changes from the commit https://github.com/magento/magento2/commit/ae304d43cd36322b1ff8145d70c9b2e9aeb0cde and check if the workaround is working in your environment.
To check the issue on Magento 2.4-develop branch, please comment on this ticket writing "@magento give me 2.4-develop instance". Kindly provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-03-28 05:55
Hi @leslilcp ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-03-28 05:55 UTC
Labels: Issue:  Cannot Reproduce, Triage: Dev.Experience, Issue: needs update
