### ISSUE TITLE
Saving via ProductRepository changes untouched attributes

### ISSUE THREAD

**Issue by ochnygosch** [magento/magento2#7879] opened 2016-12-19 14:35 UTC
Saving a loaded product via the ProductRepository updates attribute values of unchanged attributes. Even loading a product and saving it without making changes can lead to a product no longer using default values for a store.

### Preconditions

1. Magento 2.1.3
2. Single store mode is disabled

### Steps to reproduce

1. Create a simple product
2. Make sure this product uses default value for product name (or other attributes) for default store
3. Load product in a backend controller via getById($productId) method of ProductRepositoryInterface
4. Save the loaded product via save($product) method of ProductRepositoryInterface

### Expected result

1. No attribute value of the product should have changed. Especially the product name in store 1 should still use the default value

### Actual result

1. The name of the save product is copied from store 0 to store 1 and store 1 no longer uses the default value for the product name

Attached is a sample module that provides a backend controller that loads product with id 1 and saves it without changing an attribute.
[ProductSave.zip](https://github.com/magento/magento2/files/661288/ProductSave.zip)

**Comment by ochnygosch** [comment] 2016-12-20 09:44
I think something in the eav system is seriously broken. 

I've tried adding another website with a store and store view (say having the id 2).

Having a product (with id 1) and the following values:

Store 0 Name: "Testproduct"
Store 1 Name: Use default value
Store 2 Name: Use default value

Store 0 Description: "Test description"
Store 1 Description:  Use default value
Store 2 Description: "Test description in store 2"

Then I tried to edit an attribute of the new store with the following code:

`$product = $this->_productRepository->getById(1,true,2);`
`$product->setName('Testproduct in store 2');`
`$this->_productRepository->save($product);`


I expected this result:

Store 0 Name: "Testproduct"
Store 1 Name: Use default value
Store 2 Name: Use default value

Store 0 Description: "Test description"
Store 1 Description:  Use default value
Store 2 Description: "Test description in store 2"

But I got this result:

Store 0 Name: "Testproduct"
Store 1 Name: "Testproduct in Store 2"
Store 2 Name: Use default value

Store 0 Description: "Test description"
Store 1 Description:  "Test description in store 2"
Store 2 Description: "Test description in store 2"

And every other attribute in store 1 got copied from store 2.

**Comment by magento-engcom-team** [comment] 2017-11-09 09:01
Possible duplicate #7720

**Comment by magento-engcom-team** [comment] 2017-11-09 09:30
@ochnygosch, thank you for your report.
We've created internal ticket(s) MAGETWO-83254 to track progress on the issue.

**Comment by versdivers** [comment] 2017-12-26 04:06
Is there a quick fix for this? Experiencing this within Magento 2.2.1 when saving an a product trough the product repository for a store.

So i do set the StoreId but some attributes (not all and kind of random) are getting 'use default value' unchecked while not setting those.

Edit : This is not random. This is only on the attributes that have a default value

**Comment by magento-engcom-team** [comment] 2018-03-06 12:52
Closing, as this issue duplicates https://github.com/magento/magento2/issues/7720

**Closed as completed by magento-engcom-team** 2018-03-06 12:52 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid

**Comment by oneserv-heuser** [comment] 2022-03-11 14:39
Love it. Just stumbled upon this issue. Using Magento 2.4.3 this is still an issue and it's definitly not a duplicate of https://github.com/magento/magento2/issues/7720.

This issue should be reopened and the bug fixed. Maybe a new ticket should be raised but I'm really too tired of creating new issues here which are closed for completely bs reasons.
