### ISSUE TITLE
Incorrect currency format

### ISSUE THREAD

**Issue by Bartlomiejsz** [magento/magento2#8198] opened 2017-01-19 12:47 UTC
### Preconditions
1. Magento 2.1.2

### Steps to reproduce
1. Store with CHF currency configured

### Expected result
1. Currency on front should be displayed as CHF 99.99 (it is correct format in Switzerland)

### Actual result
1. It is displayed as CHF99.99

**Comment by IlnitskiyArtem** [comment] 2017-06-15 12:32
This is not a bug.
You can change the Currency display settings in "Stores > Currency > Currency Symbols"

**Comment by Bartlomiejsz** [comment] 2017-06-19 05:15
@IlnitskiyArtem You can set there only symbol. I.e. if you would like to show CHF price in store view with fr_FR language price will show as 99.99 CHF, and it doesn't matter that country is still set to Switzerland. So I don't think it is the good place to change this.
Tell me if I'm wrong.

**Comment by Bartlomiejsz** [comment] 2017-06-23 10:30
@IlnitskiyArtem what is more, in i.e. de_DE store view currency is already displayed as CHF 99.99, so with additional space it looks like this:
![image](https://user-images.githubusercontent.com/9566840/27478372-ac435a1a-580f-11e7-9c94-ee13c442c767.png)

**Comment by IlnitskiyArtem** [comment] 2017-06-27 07:57
@Bartlomiejsz, Thanks for the feedback.
We've created internal ticket MAGETWO-70275 to address this issue.

**Comment by magento-engcom-team** [comment] 2017-10-05 07:30
@Bartlomiejsz, thank you for your report.
We've created internal ticket(s) MAGETWO-70275 to track progress on the issue.

**Comment by magento-engcom-team** [comment] 2018-08-20 11:05
Hi @Bartlomiejsz

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by Bartlomiejsz** [comment] 2018-08-20 11:09
@magento-engcom-team Should not-solved issue be closed after two weeks? Really?

**Comment by magento-engcom-team** [comment] 2018-09-07 12:03
Hi @Bartlomiejsz

This is not the idea behind this. Intent is to close only inactive issues.

**Comment by johnny-longneck** [comment] 2019-02-13 08:58
We have wrong currency symbol for Singapore Dollar. It always shows "$" instead of SGD, S$ or the user entered value in the backend.

Note we have a multi-store setup, with at least 10 currencies. Singapore Dollar is the only wrong format. 
Even CHF is shown correctly.

How is the progress on this one?

**Comment by olivercastro** [comment] 2019-09-06 01:43
@johnny-longneck I've replicated the issue on version 2.2.8. The issue seems to be caused by the zend framework library that is being used that causes the "$" symbol to be used by SGD currency.

**Comment by magento-engcom-team** [comment] 2019-10-01 22:30
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by avoelkl** [comment] 2020-02-11 12:43
Too bad this was closed. We are having the same issue with singapore dollars too.

**Comment by ihor-sviziev** [comment] 2020-02-11 15:20
@avoelkl @johnny-longneck @olivercastro
Similar issue with Canadian Dollar we were fixing by setting en_CA locale. In your case you should probably define locale en_SG

**Comment by sdzhepa** [comment] 2020-02-13 14:28
Reopened this issue to re-consider, investigate one more times

**Comment by engcom-Golf** [comment] 2020-02-13 14:51
Hi @avoelkl  @olivercastro, thank you for attention on this issue, the current behavior is correct, for now magento render prices depend on locale that your store have, for example if your store have en_US locale and you have for example CHF currency, then all curency will be displayed as an "USA standart prices" not an "CHF". 
And If you switch locale to de-CH then your price will render for Swiss standards.

If we will decide to change this behavior and render price by their own standarts, wich mean every currency will be rendered per standard wich uses for their country, it may breaks a lot of thirth party extensions, so i think current behavior of rendreing prices is correct.

**Comment by avoelkl** [comment] 2020-02-24 07:28
This, thanks for having a look again.
I'll talk to my colleague if the he set en_SG correctly. @ihor-sviziev

**Closed as completed** 2020-10-08 20:21 UTC
Labels: bug report, Component: Tax, Issue: Clear Description, Issue: Format is valid, Progress: done
