### ISSUE TITLE
"the requested qty is not available" error for virtual product with Zero Subtotal Checkout and Automatically Invoice All Items enabled

### ISSUE THREAD

**Issue by paulvandermeijs** [magento/magento2#31881] opened 2021-01-28 16:36 UTC
### Preconditions (*)

1. Magento version 2.3.6
2. Using a virtual product with a _Price_ of 0, _Manage Stock_ "Yes", and _Quantity_ of 1
3. Having _Zero Subtotal Checkout_ enabled with _New Order Status_ "Processing" and _Automatically Invoice All Items_ "Yes"

### Steps to reproduce (*)

1. Add the virtual product to the cart with a quantity of 1
2. Continue to checkout
3. Place order using _Zero Subtotal Checkout_

### Expected result (*)

1. The order should be placed succesfully

### Actual result (*)

1. An error reading "The requested qty is not available" is shown

So far I have been able to figure out that the quantity is checked twice; once by `Magento\CatalogInventory\Observer\QuantityValidatorObserver` and a second time by `Magento\InventorySales\Plugin\Sales\OrderManagement\AppendReservationsAfterOrderPlacementPlugin::afterPlace()`. The issue occurs under these circumstances since the order is completed immediately and by the time the second check is executed the ordered quantity was already subtracted from the stock.

I haven't been able to reproduce this issue with a simple product; since these also require to be shipped the stock isn't reduced and the second check succeeds.

**Comment by Vipul-Aniya** [comment] 2021-01-30 06:56
Hi @paulvandermeijs. Thank you for your report.

@magento give me 2.4-develop instance to verify this issue.

**Comment by Vipul-Aniya** [comment] 2021-01-30 09:51
I'm unable to reproduce the issue as provided steps by you. Kindly provide more details to reproduce this issue and confirm the issue is on 2.4-develop instance

**Comment by paulvandermeijs** [comment] 2021-02-03 12:35
@Vipul-Aniya It seems that the issue was resolved in Magento 2.4 with [this commit](https://github.com/magento/inventory/commit/532b82b34b4cdef8c0ba318dae5ae0631f97376f) for [this issue](https://github.com/magento/inventory/pull/3046).

It is still in 2.3.6 though and I'm not sure what will happen with 2.3.6-p1 and 2.3.7 for that matter.

**Comment by engcom-Alfa** [comment] 2021-02-09 12:33
Hi @paulvandermeijs. Thank you for your report!
Unfortunately, we are not able to reproduce the issue on fresh 2.4-develop.
Looks like the issue has already been fixed.

**Preconditions:**

1. Magento 2.4-develop;
2. Using a virtual product with a Price of 0, Manage Stock "Yes", and Quantity of 1;
3. Having Zero Subtotal Checkout enabled with New Order Status "Processing" and Automatically Invoice All Items "Yes";

**Manual testing scenario:**

1. Add the virtual product to the cart with a quantity of 1
2. Continue to checkout
3. Place an order using Zero Subtotal Checkout

**Actual Result:** :heavy_check_mark: The is placed succesfully
![Screenshot from 2021-02-09 13-39-59](https://user-images.githubusercontent.com/51679138/107364073-a7301a00-6ae3-11eb-9787-d62a11275ed3.png)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch.
 Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2021-02-09 12:33 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.3.6
