### ISSUE TITLE
Timeout after click on Shopping cart Tab of a customer profile page

### ISSUE THREAD

**Issue by angelo983** [magento/magento2#26914] opened 2020-02-18 19:11 UTC
### Preconditions (*)
1. Magento 2.3.4

### Steps to reproduce (*)
1. Login as a customer, for example ALICE
2. Put a simple variation of a configurable product into the shopping cart
3. With API call, decrease stock to 0 and put simple product Out of Stock
4. From backend, open ALICE customer profile and click on Shopping cart Tab

### Expected result (*)
1. Product listed in the abandoned cart

### Actual result (*)
1. Spinner gif rotating until web server gateway timeout is reached

I noticed moreover that customer row in db table becomes locked.

Deleting from db the quote row stops the spinner and prevent the timeout.

**Comment by angelo983** [comment] 2020-02-18 19:30
> Hi @m2-assistant[bot] Here is your new Magento Instance: https://i-26914-2-4-develop.magento-testing-service.engineering
> Admin access: https://i-26914-2-4-develop.magento-testing-service.engineering/admin_448a
> Login: b9aad04a , Password: c5c593e4b485

OFF-TOPIC: in this vanilla instance, you can find in var report an exception trace because is impossible to use search box in home page

**Comment by angelo983** [comment] 2020-02-18 19:38
Issue is not reproducible in Magento 2.4, but only in Magento 2.3.X

**Comment by engcom-Delta** [comment] 2020-02-21 09:46
Hi @angelo983 , thank you for your report. According contributor's [guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) Magento is focusing development efforts on v2.4. 
I confirm that issue is not reproducible on the latest `2.4-develop` branch.
If you'd like to update the issue, please reopen it.

**Comment by angelo983** [comment] 2020-02-27 09:19
I reject the indiscriminate closure of this ticket.
Magento 2.3.5 will be released in April 2020 and actually #26914 is a bug introduced in one of last updates, so Magento is focusing development efforts on v2.3.5 too.

**Comment by angelo983** [comment] 2020-02-28 16:17
Moreover a customer cannot login anymore, because timeout happens in all logic calls that involve quote entity

**Comment by engcom-Alfa** [comment] 2020-12-29 14:54
Hi @angelo983 .
Unfortunately, we are not able to reproduce this issue on 2.3.6, 2.4.1, and 2.4-develop.
Looks like the issue has already been fixed.

**Manual testing scenario:**

1. log in as a customer, for example, ALICE
2. Put a simple variation of a configurable product into the shopping cart
3. With API calls, decrease stock to 0 and put simple product Out of Stock
4. From the backend, open ALICE customer profile and click on Shopping cart Tab

**Actual Result:** :heavy_check_mark: Product listed in the abandoned cart

![Peek 2020-12-29 16-49](https://user-images.githubusercontent.com/51679138/103292399-5c0bed00-49f6-11eb-82a2-3461dea51908.gif)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-12-29 14:54 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.3.4
