### ISSUE TITLE
Sitemap media URLs have pub/ in them

### ISSUE THREAD

**Issue by subbu1993** [magento/magento2#13002] opened 2018-01-04 23:46 UTC
Sitemap.xml image urls are generated with a pub/ in them

### Preconditions
1. Magento version - 2.1.8
2. PHP version - 7.0.26

### Steps to reproduce
1. Go to Marketing > Sitemap
2. Add sitemap
3. Set filename to sitemap.xml
4. Set path to /pub/media/

### Expected result
1. Sitemap is generated with Media URLs like https://www.site-name.com/media/catalog/....

### Actual result
1. Sitemap is generated with Media URLs like https://www.site-name.com/pub/media/catalog/....

**Comment by magento-engcom-team** [comment] 2018-01-05 09:13
@subbu1993 , thanks for you report. Why you think for Expected result
Sitemap is generated with Media URLs like https://www.site-name.com/media/catalog/....&? But image is be in path https://www.site-name.com/pub/media/catalog/.... and opening without problem.

**Comment by magento-engcom-team** [comment] 2018-01-19 09:30
@subbu1993, we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Comment by linden2015** [comment] 2018-05-28 14:48
@magento-engcom-team ,

On Magento 2.2.2 and Magento 2.2.3 we are experiencing the same issue.

> Why you think for Expected result
Sitemap is generated with Media URLs like https://www.site-name.com/media/catalog/....&? But image is be in path https://www.site-name.com/pub/media/catalog/.... and opening without problem.

We expect the image url in the sitemap to be /media/.. because that's also the url of the image used on the actual website. In our case the /pub/media/.. does not work for the image. We use the index.php inside /pub folder, symlinked from the webroot of nginx.

**Comment by hostep** [comment] 2018-05-28 17:28
This is probably a duplicate of: https://github.com/magento/magento2/issues/5321
Can you try if my [suggested workaround](https://github.com/magento/magento2/issues/5321#issuecomment-310153777) fixes the issue?

**Comment by magento-engcom-team** [comment] 2018-07-05 09:09
Hi @linden2015 
We are closing this ticket again, due to inactivity. Additionally, it really seems to duplicate #5321.
Please reopen again if it's now correct

**Closed as completed by magento-engcom-team** 2018-07-05 09:09 UTC
Labels: Progress: needs update, Issue: Clear Description, Issue: Format is valid
