### ISSUE TITLE
Custom currency symbol ignored in some Currency formatting

### ISSUE THREAD

**Issue by kardeiz** [magento/magento2#35824] opened 2022-07-26 20:59 UTC
### Preconditions and environment

- Magento version 2.4.3-p2

### Steps to reproduce

1. In Magento admin, set the base currency to some non-USD value (Stores -> Configuration -> General -> Currency Setup) .
2. In Magento admin, set a custom currency symbol for the base currency (Stores -> Currency -> Currency Symbols).
3. In Magento admin, refresh the cache as requested for the invalidated sections.

### Expected result

Currency values should use use the custom currency symbol.

### Actual result

Currency values instead use the "default" currency symbol in many, but not all locations, across the frontend, admin pages, and email HTML. We first noticed it specifically after upgrading to 2.4.3-p1 in our Order Confirmation emails.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by kardeiz** [comment] 2022-07-26 21:00
@magento give me 2.4-develop instance

**Comment by kardeiz** [comment] 2022-07-26 21:05
The issue seems introduced by these lines: https://github.com/magento/magento2/blob/2.4.3-p1/app/code/Magento/Directory/Model/Currency.php#L368-L370.

There seem to be other issues (now resolved) with the number formatter here: https://github.com/magento/magento2/issues/33856.

**Comment by engcom-Lima** [comment] 2022-07-27 12:40
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment] 2022-07-27 13:44
Hi @kardeiz ,

I have tried to reproduce the issue in `2.4-develop` but unable to reproduce the issue.
I am able to see custom currency symbols in all the pages and in emails.

Below is the screenshot for your reference:
![image](https://user-images.githubusercontent.com/60198022/181260518-124a1101-802f-4fe4-87ab-41fc9061a81c.png)
![image](https://user-images.githubusercontent.com/60198022/181261383-7126cf95-9ed7-4fa1-8f46-dec99fe2b108.png)
![image](https://user-images.githubusercontent.com/60198022/181261599-c784f617-e0cd-4bbc-a01e-9a0b1135a3bb.png)

If I am missing anything provide us information. Kindly attach screenshot of the configuration you have done on your side.
Kindly refer to [devdocs](https://docs.magento.com/user-guide/stores/currency-configuration.html) and also test in `2.4-develop` branch.

Thank you

**Comment by kardeiz** [comment] 2022-07-27 14:00
@magento give me 2.4.3-p2 instance with edition ee

**Comment by kardeiz** [comment] 2022-07-27 17:42
https://github.com/magento give me 2.4.3-p2 instance

**Comment by kardeiz** [comment] 2022-07-27 17:42
@magento give me 2.4.3-p2 instance

**Comment by kardeiz** [comment] 2022-07-27 19:13
@magento give me 2.4.3 instance

**Comment by kardeiz** [comment] 2022-08-04 18:40
@magento give me 2.4.3 instance

**Comment by engcom-Lima** [comment] 2022-08-10 10:03
Hi @kardeiz ,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed** 2022-08-10 10:06 UTC
Labels: Issue: needs update

**Comment by europrotection** [comment] 2022-11-25 14:29
This issue still exists on magento 2.4.5 p1
