### ISSUE TITLE
"The requested qty is not available" doesn't always show

### ISSUE THREAD

**Issue by gavinlimely** [magento/magento2#37984] opened 2023-09-12 11:53 UTC
### Preconditions and environment

- Latest version of Magento, however we're using 2.4.6-p2

### Steps to reproduce

"The requested qty is not available" message doesn't always show. However, I suspect this will be the case for all messages that show after a redirection.

This message WILL show if the customer-data component hasn't initialised before the Magento_Theme/js/view/messages.js component.

If you open up the console in Chrome & click "Disable Cache" within the Network tab. This will force the website to load slowly, meaning you will be able to replicate the issue easier. 

In this file: https://github.com/magento/magento2/blob/2.4.6-p2/app/code/Magento/Theme/view/frontend/web/js/view/messages.js there is a check on line 38 to see if this.messages().messages it not empty.

If the website is slow to load & the customer data has already initialised before this line is hit, it's possible that the messages observable is populated with messages & then emptied when it shouldn't be.

As the messages key is "disposableCustomerData", it's my opinion that we don't need  customerData.set('messages', {}); on line 39. I believe this was added in an early release to fix messages not disappearing & it's now causing issues.

Could somebody look over this and confirm if they believe that line is needed? Thanks

### Expected result

"The requested qty is not available" should show after trying to add more qty of a product to the cart than what is in stock.

### Actual result

The message doesn't always show.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by gavinlimely** [comment] 2023-09-13 11:20
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-09-13 11:22
Hi @gavinlimely,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.


When we are trying add more qty of the product what is in the stock it is always showing **The requested qty is not available**.We have disabled **Disable Cache** within the Network tab even though it is working fine.Could you please elaborate steps to reproduce.

https://github.com/magento/magento2/assets/51680745/1ef5fb0b-271a-4adb-ac0a-e97b70b55365




Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible


Thanks.

**Comment by gavinlimely** [comment] 2023-09-13 11:25
Hi @engcom-Bravo 

I'll try and reproduce on a vanilla instance so I can show you a screen recording. As I say, it doesn't happen everytime, so it might take a few attempts to see the issue.

Thanks

**Comment by gavinlimely** [comment] 2023-09-13 11:27
@magento give me 2.4-develop instance

**Comment by gavinlimely** [comment] 2023-09-13 11:29
@magento give me 2.4-develop instance

**Comment by gavinlimely** [comment] 2023-09-13 11:38
Hi @engcom-Bravo 

This is produced on https://magento2-demo.magebit.com/beaumont-summit-kit.html#size=171&color=58

https://github.com/magento/magento2/assets/16940261/02d3417a-104a-4f58-bd99-63e7679c51e0

As you can see it doesn't happen everytime, it will only happen if the messages component loads after the local storage has been initialised in the Magento_Customer/js/customer-data component.

Cheers

**Comment by engcom-Bravo** [comment] 2023-09-14 13:10
Hi @gavinlimely,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.



https://github.com/magento/magento2/assets/51680745/6a8229d8-5720-4bb1-9318-2517bd48d8b3



We are getting error message as **The requested qty is not available** while adding more qty to the cart.We are getting message but it is taking some to load.

Could you please let us know in which version you are checking the issue please try to reproduce the issue in Magento 2.4-develop instance.

Thanks.

**Comment by gavinlimely** [comment] 2023-09-14 13:19
@magento give me 2.4-develop instance

**Comment by gavinlimely** [comment] 2023-09-14 13:24
@magento-deployment-service give me 2.4-develop instance

**Comment by gavinlimely** [comment] 2023-09-14 13:25
@magento give me 2.4-develop instance

**Comment by gavinlimely** [comment] 2023-09-14 13:46
@magento give me 2.4-6-p2 instance

**Comment by gavinlimely** [comment] 2023-09-14 13:47
@magento give me 2.4-6-p2 instance

**Comment by gavinlimely** [comment] 2023-09-14 13:47
@magento give me 2.4-6-p2 instance

**Comment by gavinlimely** [comment] 2023-09-14 13:50
@magento give me 2.4-6-p2 instance

**Comment by gavinlimely** [comment] 2023-09-14 13:50
@magento give me 2.4-6-p2 instance

**Comment by gavinlimely** [comment] 2023-09-14 13:50
@magento give me 2.4.6-p2 instance

**Comment by gavinlimely** [comment] 2023-09-14 13:53
@magento give me 2.4.6-p2 instance

**Comment by gavinlimely** [comment] 2023-09-14 13:58
@magento give me 2.4.6 instance

**Comment by gavinlimely** [comment] 2023-09-14 14:25
@magento give me 2.4.6-p2 instance without extensions magento/module-persistent

**Comment by gavinlimely** [comment] 2023-09-14 14:26
@magento give me 2.4-develop instance without extensions magento/module-persistent

**Comment by gavinlimely** [comment] 2023-09-14 14:26
@magento give me 2.4-develop instance without extensions magento/module-persistent

**Comment by gavinlimely** [comment] 2023-09-14 14:27
@magento give me 2.4.6 instance without extensions magento/module-persistent

**Comment by gavinlimely** [comment] 2023-09-14 14:41
@magento give me 2.4.6-p2 instance

**Comment by gavinlimely** [comment] 2023-09-14 14:44
@magento give me 2.4.6-p2 instance

**Comment by gavinlimely** [comment] 2023-09-18 11:41
Hi @engcom-Bravo 

It seems that the Magento version that is deployed by the Magento Deployment Service has an additional module called Magento_Persistent. Is there a way you could spin up an environment with that module disabled & then try to replicate? I think this module fixes the issue.. However correct me if I'm wrong, but it doesn't look to be included in 2.4.6-p2 OS?

Thanks

**Comment by engcom-Bravo** [comment] 2023-09-21 09:22
Hi @gavinlimely,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

We have disabled Magento_Persistent module still we are getting error message.We have checked in magento 2.4.6-p2 instance we have the module.

<img width="527" alt="Screenshot 2023-09-21 at 2 06 37 PM" src="https://github.com/magento/magento2/assets/51680745/41e89a78-bc23-40f7-811c-b6e25ddf520b">



https://github.com/magento/magento2/assets/51680745/c01fbee5-e628-430b-b81e-1ab61de9a923









So I request you to please try to reproduce the issue in the latest development branch.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-09-28 06:11
Hi @gavinlimely,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-09-28 06:11 UTC
Labels: Issue: needs update, Reported on 2.4.6-p2

**Comment by ssx** [comment] 2024-08-21 13:03
@gavinlimely did you ever solve this? We're seeing the same on one of our sites.

**Comment by patruvlad** [comment] 2024-12-28 18:15
I have the same issue, most occurrences happen on Windows11, I have Magento 2.4.7-p1 @gavinlimely or @ssx did you find any sollution?

**Comment by ssx** [comment] 2024-12-30 07:55
> I have the same issue, most occurrences happen on Windows11, I have Magento 2.4.7-p1 @gavinlimely or @ssx did you find any sollution?

Sadly not. That was the same for our reporting too - Windows 11 seemed to be the most likely culprit.

**Comment by WebHostingAce** [comment] 2025-09-13 01:44
Hi @gavinlimely 

Have you had any luck solving this issue? It’s been quite an annoying one.
