### ISSUE TITLE
The default value for EAV attributes is not honored for existing products

### ISSUE THREAD

**Issue by stupachenko** [magento/magento2#29073] opened 2020-07-10 12:33 UTC
### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Navigate to Admin Panel > Catalog > Products and create a new simple product:
```
Name: Test Product
Price: 100
```
2. Navigate to Admin Panel > Stores > Attributes > Product and create a new attribute:
```
Default Label: Test Attribute
Catalog Input Type for Store Owner: Dropdown
Values Required: Yes
Manage Options: add 2 options Option 1 and Option 2, Option 2 is default
```
3. Navigate to Admin Panel > Stores > Attributes > Attribute Sets and add attribute to Default attribute set.
4. Navigate to Admin Panel > Catalog > Products and open Test Product.

### Expected result (*)

1. Test Attribute = Option 2, because Option 2 is set as default.

### Actual result (*)

1. Test Attribute is not defined.
![image](https://user-images.githubusercontent.com/51681379/92466336-9f88e400-f1d8-11ea-81f3-0b14516a96b1.png)
![Peek 2020-09-08 11-44](https://user-images.githubusercontent.com/51681379/92466638-132af100-f1d9-11ea-9b84-8dc9ee8862bf.gif)

---

- [ ] Severity: **S2**

**Comment by magento-engcom-team** [comment] 2020-09-08 10:43
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37446` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment] 2020-09-10 21:33
Hello @stupachenko @engcom-Delta

As I remember it was discussed multiple times and each time it was closed as not a bug.
Based on the description its appears only if we add Attribute to the Attribute Set. This Attribute Set was already used for products. And after that, we add a new required attribute with a default value. 
If Magento automatically updates all products based on this Attribute Set and updated value for the attribute - it will be not obvious for Admin User. And potentially could update products that should not be updated.

So. current behavior looks more save and expected. And still, Admin can use mass action and update old products with new value according to the new attribute

**Comment by sdzhepa** [comment] 2020-10-08 19:41
Hello @stupachenko @engcom-Delta

We discussed this issue one more time during triage with the engineering and Product Manager.
From one point of view, it could be an expected and logical result: Admin updates/add 1 new attributes with a predefined value and expects that all existed products will be updated with this attribute and value.

But from another perspective, this quite old behavior, maybe even from M1.
And potentially changing this behavior could affect current merchants that used(using)  this behavior. Which could lead to unexpected results. In other words, it could be dangerous.
Also, take into account this does not block any functionality and admin still can update the product using mass actions.

So, was decided to close this issue and keep the current behavior

**Closed as completed by sdzhepa** 2020-10-08 19:41 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Confirmed, Issue: Format is valid, Reproduced on 2.4.x, Progress: done, Triage: Need PO Confirmation, Event: Distributed CD India 2020, Reported on 2.4.0
