### ISSUE TITLE
Upgrade 2.3.3 to 2.3.4 with Dotdigitalgroup_Email disabled

### ISSUE THREAD

**Issue by onepack** [magento/magento2#26573] opened 2020-01-29 10:12 UTC
### Preconditions (*)

1. Magento 2.3.4
2.

### Steps to reproduce (*)

1. Disable the Dotdigitalgroup_Email module in 2.3.3 and upgrade Magento 2 to 2.3.4
2. After upgrading via composer login to the backend of magento2.

### Expected result (*)

1. Expected to dashboard

### Actual result (*)

I got an error page with the following:
Exception #0 (OutOfRangeException): Specified invalid parent id (Dotdigital group Email::marketing automation)

**Comment by onepack** [comment] 2020-01-29 11:34
Enabling the module fixes the backend but the backend should not break on a disabled third-party module!

**Comment by devchris79** [comment] 2020-01-29 11:35
I have attempted an upgrade with Dotdigitalgroup_Email disabled this morning and get an error report:

`{"0":"Specified invalid parent id (Dotdigitalgroup_Email::marketing_automation)","1":
"#1 Magento\\Backend\\Model\\Menu\\Builder\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]
\n#2 Magento\\Backend\\Model\\Menu\\Builder\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]
\n#3 Magento\\Backend\\Model\\Menu\\Builder\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Backend\/Model\/Menu\/Builder\/Interceptor.php:26]
\n#4 Magento\\Backend\\Model\\Menu\\Builder\\Interceptor->getResult() called at [vendor\/magento\/module-backend\/Model\/Menu\/Config.php:148]
\n#5 Magento\\Backend\\Model\\Menu\\Config->_initMenu() called at [vendor\/magento\/module-backend\/Model\/Menu\/Config.php:111]
\n#6 Magento\\Backend\\Model\\Menu\\Config->getMenu() called at [vendor\/magento\/module-backend\/Model\/Url.php:365]
\n#7 Magento\\Backend\\Model\\Url->_getMenu() called at [vendor\/magento\/module-backend\/Model\/Url.php:325]
\n#8 Magento\\Backend\\Model\\Url->getStartupPageUrl() called at [vendor\/magento\/module-backend\/App\/AbstractAction.php:281]
\n#9 Magento\\Backend\\App\\AbstractAction->_processUrlKeys() called at [vendor\/magento\/module-backend\/App\/Request\/BackendValidator.php:175]
\n#10 Magento\\Backend\\App\\Request\\BackendValidator->validate() called at [vendor\/magento\/framework\/App\/Request\/CompositeValidator.php:40]
\n#11 Magento\\Framework\\App\\Request\\CompositeValidator->validate() called at [vendor\/magento\/framework\/App\/FrontController.php:137]
\n#12 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:98]
\n#13 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]
\n#14 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]
\n#15 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [app\/code\/Infortis\/Cgen\/Plugin\/Magento\/Framework\/App\/FrontController.php:32]
\n#16 Infortis\\Cgen\\Plugin\\Magento\\Framework\\App\\FrontController->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]
\n#17 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]
\n#18 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]
\n#19 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:116]
\n#20 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:24]
\n#21 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:261]
\n#22 Magento\\Framework\\App\\Bootstrap->run() called at [index.php:39]\n","url":"\/admin\/index\/index\/key\/xx\/","script_name":"\/index.php","report_id":"xx"}`

**Comment by magento-engcom-team** [comment] 2020-01-29 13:54
@srsathish92 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by srsathish92** [comment] 2020-01-29 14:10
@onepack Instead of enabling `Dotdigitalgroup_Email`, you can also disable `Dotdigitalgroup_Chat`. It will solve the issue.
FYI: `Dotdigitalgroup_Chat` added in new release.

**Comment by onepack** [comment] 2020-01-29 14:14
@srsathish92 I noticed the new module later today and suspected this. I will disable both now. Is it an idea to work in a different way with dependencies regarding non-core modules?

**Comment by srsathish92** [comment] 2020-01-29 14:28
@onepack As of now, No. We need to do manually. I thought purposefully added on exception in `app/code/Magento/Backend/Model/Menu/Builder.php Line: 83` .

@engcom-Bravo @magento-engcom-team please add the valid label for triage.

**Comment by ruggi69** [comment] 2020-01-29 14:48
To solve the issue I changed parent attribute in line 5 in /vendor/dotmailer/dotmailer-magento2-extension-chat/etc/adminhtml/menu.xml
from "Dotdigitalgroup_Email::marketing_automation" to "Magento_Backend::marketing"

**Comment by magento-engcom-team** [comment] 2020-01-30 10:11
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30914` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by adamrandazzo** [comment] 2020-01-30 17:57
Magento really needs to stop including this crapware with the core packages.

**Comment by gwharton** [comment] 2020-02-01 15:27
It also breaks di compile if dotdigital email is disabled but chat is enabled.

**Comment by inkobject** [comment] 2020-02-06 19:24
> Magento really needs to stop including this crapware with the core packages.

At the very least offer the option disable the packages prior to deployment, if not default to new/improved 3rd party packages being disabled altogether. 

I ran into this problem and had to determine what was breaking. Nearly all of my upgrade/update pains in 2.3.* have come from bundled modules. I'm looking at you temando #25979

**Comment by onepack** [comment] 2020-02-06 19:59
@inkobject Yes, Temando has been a real pain...

**Comment by gcampedelli** [comment] 2020-02-07 22:23
I had the same problem with Temando and something with DotMailer version blocking composer from upgrading. Had to manually edit composer to achieve upgrade. I don't use nor Temando or DotMailer.

**Comment by tuyennn** [comment] 2020-02-17 10:16
Has same issue, crapware on magento

**Comment by rparsi-boxycharm** [comment] 2020-03-12 20:09
Check your composer.lock file; ours had all the Dotdigitalgroup modules, removing them and running `composer install` should permanently remove these crapware modules.

**Comment by prateek-karanpuria** [comment] 2020-03-20 11:01
Enable the **Dotdigitalgroup_Email** module & then run setup upgrade fixes the issue. Afterwards we can again disable the module if required.

**Comment by rparsi-boxycharm** [comment] 2020-03-20 13:34
Or, as others have mentioned, magento can stop including crapware modules in their releases.

**Comment by Finbayern** [comment] 2020-04-09 20:35
> 
> 
> Or, as others have mentioned, magento can stop including crapware modules in their releases.

Oh, how I wish that will happen one day. All this crapware could be added as extensions IF needed, now they only create a load of issues in EVERY damn update. Magento is a really fragile (unstable) platform already without all the crapware and by adding all this useless junk, it creates a nightmare. Each update should be easily finished within an hour or a few, but I've gotten used to be prepared for hours of bug-hunting and reverting back to the previous, functional version. Please Magento, make all this crapware an OPTION, not a part of core code that only pushes people to use other platforms with all the constant issues.

**Comment by hostep** [comment] 2020-04-10 07:49
Nobody has mentioned this in this thread yet, but if you want to get rid of all dotmailer packages in composer, they have been bundled together in a meta package called `dotmailer/dotmailer-magento2-extension-package` since Magento 2.3.4 I believe.

So it suffices to just add the following in your `composer.json` file if you want to get rid of them all (and most likely also all new dotmailer modules which might get added in the future):
```
    "replace": {
        "dotmailer/dotmailer-magento2-extension-package": "*",
    }
```

**Comment by matthew99** [comment] 2020-05-01 14:27
Oh yes!, thank you @hostep ! I could not compile when updated from 2.3.3 to 2.3.5 due to the digitalgroup-chat module giving errors. You replace command did the trick!

Every update, there's just some junk throwing errors! I could not agree more to keep the core clean (and fragile as it is).

**Comment by sdzhepa** [comment] 2020-10-06 18:30
Based on the response from Dotdigital (owner of this extension)

After a couple of internal discussions and investigation was defined it is not a bug but not a supported the case.
At this moment Magento does not support partial disable of the module. Please disable all modules related to the extension.
Also, there are no plans to implement and support such case at this moment.

**Closed as completed by sdzhepa** 2020-10-06 18:30 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Bundled Extension, Component: Admin, Reproduced on 2.4.x, Progress: done, Reported on 2.3.3

**Comment by an4rei** [comment] 2021-02-26 15:18
For anyone upgrading to 2.4.2, now you need to remove all of the below:

**Dotdigitalgroup_Email**
**Dotdigitalgroup_Chat**
**Dotdigitalgroup_Sms**    (new crapware that breaks your backend if you have the other 2 modules disabled)

Why is dotdigitalgroup still included in magento 2?

**Comment by micwallace** [comment] 2021-03-03 05:34
This issue should be reopened. As others have mentioned, if @magento-team insists on adding crapware, they can at least fix the upgrade process so it doesn't break everything when new 3rd party modules are added.

It's pretty bloody simple to avoid this. Either have 3rd party modules disabled by default (fat chance of that happening), or:
1. Check dependencies on new 3rd party modules
2. Check config.php to see if any dependent modules are disabled
3. If dependent modules are disabled, the new 3rd party module should remain disabled.

**Comment by jaimiedijstra** [comment] 2021-08-31 18:52
100% agree the errors for users who don't need Dotdigital or other bundled "extras"/"crap" this is a real pain, costs devs time and costs small magento stores built in house a serious headache and trouble shooting, continuing into Magento 2.4.3. Dito to hostep's and matthew99's solutions, but alternatively check:

`bin/magento module:status`
if not disabled (or some are not) run:
`bin/magento module:disable Dotdigitalgroup_Email Dotdigitalgroup_Chat Dotdigitalgroup_ChatGraphQl Dotdigitalgroup_EmailGraphQl Dotdigitalgroup_Sms`
Remove any from above command that are already disabled.
