### ISSUE TITLE
2.4.5-p1 some of the products are disabled in checkout

### ISSUE THREAD

**Issue by Jilco** [magento/magento2#36465] opened 2022-11-11 16:01 UTC
### Preconditions and environment

- Magento 2.4.5-p1
- It is with products in the cart with a qty below 1 (eg. 0.6)

### Steps to reproduce

Note: We sell fabrics per meter with a minimum qty of 0.5
1. Add product (in backend) with a "Minimum Qty Allowed in Shopping Cart" of 0.5, and "Qty Uses Decimals" to yes
2. Add product to cart with default qty (0.5) or 0.6
3. Go to checkout
4. Fill in adress and go to next step
5. Make order

### Expected result

Order is placed succefully

### Actual result

Not possible to order because of error "Some of the products are disabled"

![some-of](https://user-images.githubusercontent.com/23727130/201380542-d9fe4c12-1c77-4d61-8ecb-ed953fc1bbab.jpg)

### Additional information

When qty is above 1 there is no problem, so it occurs with products below 1

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Jilco** [comment] 2022-11-11 16:01
@magento give me 2.4.5-p1 instance

**Comment by Jilco** [comment] 2022-11-11 16:10
Issue: Confirmed (See screenshot)
![repro](https://user-images.githubusercontent.com/23727130/201382795-e35ebbbb-bbb6-48f6-a085-4ad19ca9096e.jpg)

**Comment by Jilco** [comment] 2022-11-11 16:11
Issue: Confirmed

**Comment by engcom-Bravo** [comment] 2022-11-14 07:39
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-14 08:04
Hi @Jilco,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop and 2.4.5 instances and the issue is not reproducible on both the instances.Kindly refer the screenshots.

**Steps to reproduce** :

1.Add product (in backend) with a "Minimum Qty Allowed in Shopping Cart" of 0.5, and "Qty Uses Decimals" to yes
2.Add product to cart with default qty (0.5) or 0.6
3.Go to checkout
4.Fill in adress and go to next step
5.Make order


Order Placed Successfully.


<img width="1452" alt="Screenshot 2022-11-14 at 1 18 48 PM" src="https://user-images.githubusercontent.com/51680745/201606777-1be2f11b-f52c-436d-8965-2cba260f9d87.png">



<img width="1442" alt="Screenshot 2022-11-14 at 1 19 00 PM" src="https://user-images.githubusercontent.com/51680745/201606818-1c6d77b5-858c-4b44-a41e-b3c92181f431.png">


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by Jilco** [comment] 2022-11-14 09:22
@magento give me 2.4-develop instance

**Comment by Jilco** [comment] 2022-11-14 09:23
I found with a lot of google this article, the file: vendor/magento/module-checkout/Model/GuestPaymentInformationManagement.php

So it only occurs when checking out as a guest

https://magento.stackexchange.com/questions/355647/error-message-some-of-the-products-are-disabled-on-checkout

**Comment by engcom-Bravo** [comment] 2022-11-15 10:07
Hi @Jilco,

Thanks for your Update.

We verified with both guest and existing customers we are not able to reproduce the issue.we are able to place the order successfully.

Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2022-11-29 06:03
Hi @Jilco,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-11-29 06:03 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.5-p1
