### ISSUE TITLE
Write File method

### ISSUE THREAD

**Issue by Minirock** [magento/magento2#35515] opened 2022-05-23 09:47 UTC
### Preconditions and environment

- Magento version : 2.4.1 (but looks like the bug is valid for all magento 2 version) 
- As a developer, I want to create a custom file that will be sent threw ftp (but looks like the method is the same to write in magento directly). This file content will exceed the max length as defined by php when I ran the code threw observer. But will be written successfully by CLI command.

### Steps to reproduce

1. Create an observer

```
<event name="sales_order_save_after">
    <observer name="vendor_module_observer_sales_order_place" instance="Vendor\Module\Observer\OrderSave" />
</event>
```

2. Create a CLI command

```    
<type name="Magento\Framework\Console\CommandList">
        <arguments>
            <argument name="commands" xsi:type="array">
                <item name="writeOrderFile" xsi:type="object">Vendor\Module\Console\Write</item>
            </argument>
        </arguments>
    </type>
```

3. In both files, add the following

```
$filename = 'input/order-' . $order->getIncrementId() . '-' . date('YmdHis') . '.xml';
    /* $content needs to contains a lot of data, in my case the issue appears 
    when the order has more than 10 items, but you can simulate by entering 
    a very long string it's not directly related to the data itself bu to his length */
    $content = $orderXml->asXML();
    $this->sftp->write($filename, $content); // (or without ftp directly in magento it's the same)
```

4. Create an order to trigger the observer, you will get the error : 

> Warning: is_readable(): File name is longer than the maximum allowed path length on this platform (4096)

5. Run the CLI command, which will execute the same code, it will work properly

### Expected result

The file should be written is both case. (CLI + Observer). The method is_readable shouldn't mistake the file content with the filename. THe actual error message on the filename length is actually wrong, cause the issue isn't on the file length but on the file content.

```
    /**
     * Write a file from string, file or stream
     *
     * @param string $filename
     * @param string|resource $src filename, string data or source stream
     * @param null $mode
     * @return bool
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function write($filename, $src, $mode = null)
    {
        if (is_string($src) && is_readable($src)) {
```

### Actual result

> Warning: is_readable(): File name is longer than the maximum allowed path length on this platform (4096)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Minirock** [comment] 2022-05-25 12:23
The workaround we manage to find was to write the file to our magento in the first place.

Then sending to the write method the file resource instead of the file content.

But I think something should be fixed here; is_readdable is clearly not supposed to get something else than a filename as a parameter. But magento use it all the time even if we send the filecontent.

Either we should add an exception, either we should create two distinct write method, one for file resource and one for file content.

**Comment by engcom-Hotel** [comment] 2022-06-10 11:39
Hello @Minirock,

Thanks for the report and collaboration!

We have tried to reproduce the issue by following the steps mentioned in the main description. We have used Magento 2.4-develop branch. But for us, the issue is not reproducible. 

I am attaching the module below for reference which has been made by is in order to reproduce the issue:
[Magz.zip](https://github.com/magento/magento2/files/8878460/Magz.zip)

Do we need to change anything in the PHP.ini file as well in order to reproduce the issue?

Thanks

**Comment by Minirock** [comment] 2022-06-10 12:45
I think you don't reproduce because you are not using the write method from the same class as we are : 

`Magento\Framework\Filesystem\Io\Ftp`

**Comment by engcom-Hotel** [comment] 2022-06-30 11:51
Hello @Minirock,

We have tried it with the below class as well:

`Magento\Framework\Filesystem\Io\Ftp`

We have tried to write almost 11MB file through FTP. But it was working properly for us. Please let us know if we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2022-07-14 11:30
Dear @Minirock,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-07-14 11:30 UTC
Labels: Triage: Dev.Experience, Issue: needs update
