### ISSUE TITLE
db_schema foreign key issues When referencing tax_class table class_id

### ISSUE THREAD

**Issue by JesperHerrloff** [magento/magento2#36886] opened 2023-02-19 12:39 UTC
### Summary

As padding is removed, there is no way to set length on the column when the column is an integer. 

When you try to reference class_id in table tax_class which has a length of 6 and standard smallint is 5. it works to add a foreign key to store table. 

### Examples

When adding column 
<column xsi:type="smallint" name="tax_class_id" nullable="false" unsigned="false" identity="false"/>
The length is 5

When trying to add foreign key its complaining about column definition is wrong and thats true. 

### Proposed solution

A solution would be to alter the tax_class table to be the default length for small int which is 5. Then there should be no issues creating foreign keys to tax_class table. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2023-02-21 13:14
Hello @JesperHerrloff,

Thanks for the reporting and collaboration!

We are looking into this issue and found that `class_id` in table `tax_class` has datatype smallint which has default length 5, not 6. 

And according to the MySQL official doc, `The size and sign of fixed precision types such as [INTEGER](https://dev.mysql.com/doc/refman/5.6/en/integer-types.html) and [DECIMAL](https://dev.mysql.com/doc/refman/5.6/en/fixed-point-types.html) must be the same.`

Please refer [this link](https://dev.mysql.com/doc/refman/5.6/en/create-table-foreign-keys.html) for more information.

Please let us know if we have missed anything.

Thanks

**Comment by JesperHerrloff** [comment] 2023-02-21 13:50
Is it fixed later than 2.4.5-p1
Which has class_id length 6 in my install. 
<img width="1435" alt="2023-02-21" src="https://user-images.githubusercontent.com/70312997/220363431-0b9cc247-ecc6-430d-87a9-481a11e860aa.png">

I know about the foreign key thing that they must be the same.

**Comment by engcom-Hotel** [comment] 2023-02-22 07:43
Hello @JesperHerrloff,

We have tried it in Magento's latest development branch i.e. 2.4-develop and the issue is not reproducible for us. Please have a look at the below screenshot for reference:

<img width="916" alt="image" src="https://user-images.githubusercontent.com/51681618/220554926-d2efd908-77a2-4ad8-a313-de581cad1e1c.png">

Thanks

**Comment by JesperHerrloff** [comment] 2023-02-22 07:53
Thats strange. I will make a new install and check. A bit odd that my table is different. I will have to look into how that might happen to me.
Did a composer install, but that should not make a difference, the code base should be the same.

**Comment by engcom-Hotel** [comment] 2023-03-08 05:47
Dear @JesperHerrloff,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2023-03-08 05:47 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.x
