### ISSUE TITLE
2.1 - can't save changes to CMS pages

### ISSUE THREAD

**Issue by ghost** [magento/magento2#5295] opened 2016-06-28 03:25 UTC
## Steps to reproduce
1. Update Magento via composer require product/magento-community-edition 2.1.0 --no-update / composer update / bin/magento setup:upgrade
2. Select a page to edit under Content / Pages
3. Make changes to page content, attempt to Save  changes
## Expected result
1. Changes are saved.
## Actual result
1. Choosing either SAVE or SAVE and CONTINUE produces a non-save. Just get zero response. Page never updates
2. [2016-06-28 03:20:07] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["catalog_category","catalog_product","BLOCK_HTML"],"mode":"matchingAnyTag"},"is_exception":false} []

Is the only debug log entry and doesn't seem relevant to issue
3. ...

**Comment by wert2all** [comment] 2016-06-30 15:29
I cannot reproduce this issue. Can You click to "Edit HTML source" into content editor and show this code?

**Comment by vzabaznov** [comment] 2016-07-14 08:01
Hi, @dgarbe thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.

**Closed as completed by vzabaznov** 2016-07-14 08:01 UTC
Labels: Progress: needs update
