### ISSUE TITLE
Magento installation fails with composer 2.2.0 RC1

### ISSUE THREAD

**Issue by jonashrem** [magento/magento2#34831] opened 2021-12-16 21:55 UTC
magento installation fails with composer 2.2.0 RC1

### Preconditions (*)
install composer 2.2.0 RC1

### Steps to reproduce (*)
download composer 2.2.0 from https://getcomposer.org/download/2.2.0-RC1/composer.phar
php7.4 composer2  create-project --repository-url=https://repo.magento.com/ magento/project-community-edition magento2

### Expected result (*)
magento installes as with composer 2.1

### Actual result (*)
magento installation fails:
```
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 591 installs, 0 updates, 0 removals
  - Installing laminas/laminas-dependency-plugin (2.2.0): Extracting archive
laminas/laminas-dependency-plugin contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "laminas/laminas-dependency-plugin" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] y
Plugin initialization failed (require(app/etc/NonComposerComponentRegistration.php): failed to open stream: No such file or directory), uninstalling plugin
  - Removing laminas/laminas-dependency-plugin (2.2.0)
    Install of laminas/laminas-dependency-plugin failed

                                                                                                           
  [ErrorException]                                                                                         
  require(app/etc/NonComposerComponentRegistration.php): failed to open stream: No such file or directory  
                                                                                                           

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package>] [<directory>] [<version>]
```

**Comment by engcom-Hotel** [comment] 2021-12-17 10:22
Hello @jonashrem,

We have tried this issue by running below command:

`./composer220RC1.phar create-project --repository-url=https://repo.magento.com/ magento/project-community-edition magento34831 <FOLDER-NAME>`

And for us, the issue is reproducible for us:

![image](https://user-images.githubusercontent.com/51681618/146529696-b612ec99-2601-486b-831b-bc0278c28bcc.png)

Hence confirming this issue.

Thanks

**Comment by ihor-sviziev** [comment] 2021-12-18 10:48
@sidolov i put priority to p1 as you can’t crate a new magento project with composer 2.2

**Comment by giacmir** [comment] 2021-12-22 11:24
Composer 2.2 has been released today. At this time Magento2 is not compatible with Composer 2.

**Comment by raumatbel** [comment] 2021-12-22 11:53
Can you downgrade the version of composer to 2.1.4
Run this `composer selfupdate -- 2.1.4`. With the last version of composer 2.2, the installation fails.

**Comment by mbrioski** [comment] 2021-12-22 13:49
In Magento cloud we have the version 2.1.14 and we have the same problem

**Comment by ssx** [comment] 2021-12-22 13:56
> In Magento cloud we have the version 2.1.14 and we have the same problem

If you pin it in `.magento.app.yaml` it'll work:

```
dependencies:
  php:
    composer/composer: '2.1.4'
```

then clear your project's build cache.

**Comment by alanbort** [comment] 2021-12-22 14:14
Hi, consider using the more generic '>=2.0 <2.2' for composer version:

```yaml
dependencies:
    php:
        composer/composer: '>=2.0 <2.2'
```

**Comment by ssx** [comment] 2021-12-22 14:18
> 

yup, or that :)

**Comment by mbrioski** [comment] 2021-12-22 14:21
As long there are versions like 2.1.14 having the same issue, i will go with :
```
dependencies:
  php:
    composer/composer: '2.1.14'
```

**Comment by Alexander-Pop** [comment] 2021-12-22 17:28
changing composer version to '2.1.4' fixed this issue for us. TY

**Comment by gvasilakiss** [comment] 2021-12-22 19:51
Same issue here, by changing the version to 2.1.4 fixed my installation.

**Comment by hostep** [comment] 2021-12-22 20:23
Linking to two bugreports on composer's repo:
- https://github.com/composer/composer/issues/10390
- https://github.com/composer/composer/issues/10384

Based on the comments in there, I'd expect the next version of composer to be released within a few days which will probably fix this problem.

**Comment by hostep** [comment] 2021-12-23 07:22
This issue is now fixed in composer 2.2.1

Make sure to allow all the plugins it asks for during installation to be allowed though.

**Comment by manugentoo** [comment] 2022-01-05 02:21
In my end. Composer version 2.1.2 worked well on Magento V2.4.2, V2.4.2-p1, V2.4.3, V2.4.3-p1

**Comment by hostep** [comment] 2022-01-06 17:03
You'd probably want to update to at least composer 2.2.3 to avoid other [crazy weirdness](https://github.com/composer/composer/issues/10401) happening 😉

**Closed as completed** 2022-01-22 02:23 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Severity: S1, Progress: done, Reported on 2.4.x, Area: Framework
