### ISSUE TITLE
Product details page - Review list section not expand when click on review count from wish list page

### ISSUE THREAD

**Issue by renard123** [magento/magento2#33234] opened 2021-06-14 09:12 UTC
Product details page - Review list section not expand when click on review count from wish list page

### Preconditions (*)

1. Magento 2.4.1
2.

### Steps to reproduce (*)

1. Login into account 
2. Add to wish list which have more than 1 review 
3. My wish list page -> Click on Review count
4. Refer the link: https://nimb.ws/tjVeIu

### Expected result (*)
User should see reviews 

### Actual result (*)
It shows the add review form 
![image](https://user-images.githubusercontent.com/50658701/121868332-7b85a080-cd1e-11eb-890e-d20864d80d96.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment] 2021-06-14 09:13
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2021-06-14 09:25
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42627` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by jayachandraoggy** [comment] 2021-06-14 11:30
@magento give me 2.4-develop instance

**Comment by khrystynastolbova** [comment] 2021-06-29 15:04
@magento I am working on this

**Comment by slavvka** [comment] 2021-08-20 16:29
@magento give me test instance

**Comment by engcom-Bravo** [comment] 2024-06-14 03:56
Hi @renard123,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="833" alt="Screenshot 2024-06-14 at 09 25 01" src="https://github.com/magento/magento2/assets/51680745/ce915534-f5ae-4552-9f2a-cd4edc77efbc">




User able to see the reviews.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-14 03:56 UTC
Labels: Issue: Confirmed, Component: Review, Reproduced on 2.4.x, Priority: P3, Severity: S3, Progress: done, Issue: ready for confirmation
