### ISSUE TITLE
Upgraded from 2.0.7 to 2.1.0 - Saving Customer goes blank

### ISSUE THREAD

**Issue by malaiselvan** [magento/magento2#5799] opened 2016-07-25 22:24 UTC
Upgraded Magento 2.0.7 to 2.1.0.  Clean the cache and index has been rebuilt.  After upgrade, I just edited a customer and tried to save and blank page appears.  No problem for adding a new customer.  The problem is only for editing and saving an existing customer.
### Preconditions
1. Upgrade from 2.0.7 to 2.1.0
2. fyi, it was migrated using data migration tool from 1.9.0.1 to 2.0.2
### Steps to reproduce
1. Login to admin side
2. Edit a customer, change some data
3. Save the customer
### Expected result
1.  The customer should saved
### Actual result
1. The page goes blank and customer didnt saved
2. No error message appeared on the screen
3. No log or exception captured

**Comment by sevos1984** [comment] 2016-08-31 13:21
Did you clean your magento cache after upgrade? Also check your file permissions according to that doc http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html

**Comment by NikoAlexis** [comment] 2016-09-14 06:21
The same issue.
Migrated to 2.0.7, then updated from 2.0.7 to 2.1.0. It's ok if I create a new user, but when I try to edit the user and press "save" - blank page.
Magento cache is cleaned.

**Comment by sevos1984** [comment] 2016-09-27 09:15
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-09-27 09:15 UTC
Labels: bug report, Progress: needs update, Component: Customer
