### ISSUE TITLE
Cannot create preference for Magento\Bundle\Block\Catalog\Product\View\Type\Bundle

### ISSUE THREAD

**Issue by khoi-le** [magento/magento2#23057] opened 2019-05-29 17:52 UTC
### Preconditions (*)

1. I've seen on 2.2.4 and it still occurs on 2.3.1.

### Steps to reproduce (*)

1. Create a module to use to override a block.
2. Override this block Magento\Bundle\Block\Catalog\Product\View\Type\Bundle.

### Expected result (*)

1. Override should load your file.

### Actual result (*)

1. Magento still uses the core file.

**Comment by orlangur** [comment] 2019-05-30 15:19
@khoi-le please provide code sample. There is nothing special with this class from DI perspective.

**Comment by kirtinariya1** [comment] 2019-06-06 06:04
You can use plugin for single function override.
https://magento.stackexchange.com/questions/142607/magento-2-1-preference-doesnt-work-with-block

**Comment by engcom-Charlie** [comment] 2019-10-18 12:50
Hello @khoi-le 
We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.
So i have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-10-18 12:50 UTC
Labels: Issue: Format is valid
