### ISSUE TITLE
Datepicker in "Expiration date" field on user edit form returns date in incorrect format after save

### ISSUE THREAD

**Issue by thomas-harding** [magento/magento2#35028] opened 2022-01-27 15:23 UTC
### Preconditions (*)

1. Magento 2.4.3

### Steps to reproduce (*)

1. Create a user with an en_GB locale
2. While logged in as en_GB user, go into System > Permissions > All Users and Add New User
3. Fill out required details, set user role and set Expiration Date to **26/01/2022**
4. Save User
5. Go to user edit page for new account just created

### Expected result (*)

1. The expiration date should be 26/01/2022 15:14:15 (which was my current time)

### Actual result (*)

1. The date returns as 15 Jul 2031 15:14:00 (even the incorrect format)
![image](https://user-images.githubusercontent.com/3355212/151388136-f6c24e9c-b1a0-49cb-a867-96024b93bd3b.png)
2. The result stored in `admin_user_expiration` is correct. In this case, it's **2022-01-26 15:14:15**

**Comment by engcom-November** [comment] 2022-02-22 11:44
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue:
Steps performed:
Created Admin User from System - All Users - Add new User - with interface Locale - United Kingdom (GB) - Save User 
Activate the user/grant access
Login to admin using newly created user
System > Permissions > All Users and Add New User
Fill out required details, set user role and set Expiration Date to 22 Feb 2022  and Save
Edit the User again - No issue. Expiration date is displayed as expected.
![image](https://user-images.githubusercontent.com/60198231/155125557-6dda6568-c4ae-4a3b-b458-4ed54e34009e.png)
@thomas-harding kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.

**Comment by engcom-November** [comment] 2022-03-08 05:18
Hi @thomas-harding,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-03-08 05:18 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.3
