### ISSUE TITLE
Clear all filter when switch store on front end

### ISSUE THREAD

**Issue by thanhthaitran** [magento/magento2#36489] opened 2022-11-18 07:29 UTC
### Preconditions and environment

- Magento version: 2.4.5
I switch store after filter product, but the parameters have been disappeared.

### Steps to reproduce

1. Choose filter on layered navigation
2. Switch store

### Expected result

 Parameter filter still appeared

### Actual result

 Parameter filter disappeared

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by thanhthaitran** [comment] 2022-11-18 08:07
Seem the issue is in Magento\UrlRewrite\Model\StoreSwitcher\RewriteUrl when call `$request->getPathInfo()`
```
public function switch(StoreInterface $fromStore, StoreInterface $targetStore, string $redirectUrl): string
    {
        $targetUrl = $redirectUrl;
        /** @var \Magento\Framework\HTTP\PhpEnvironment\Request $request */
        $request = $this->requestFactory->create(['uri' => $targetUrl]);

        $urlPath = ltrim($request->getPathInfo(), '/');
        .....
```
why you remove the query string from REQUEST_URI in Magento\Framework\HTTP\PhpEnvironment\Request ?
```
public function setPathInfo($pathInfo = null)
    {
        if ($pathInfo === null) {
            $requestUri = $this->getRequestUri() ?? '';
            if ('/' == $requestUri) {
                return $this;
            }

            // Remove the query string from REQUEST_URI
            $pos = strpos($requestUri, '?');
            if ($pos) {
                $requestUri = substr($requestUri, 0, $pos);
            }

            $baseUrl = $this->getBaseUrl();
            ....
```

**Comment by engcom-Bravo** [comment] 2022-11-18 08:46
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-18 11:51
Hi @thanhthaitran,

Thank you for reporting and collaboration.


Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


Steps to reproduce:

1.Choose filter on layered navigation
2.Switch store

We have created two store view.in first store we a applied a filter on layered navigation and switched to another store view.Parameter filter still appeared.



<img width="1439" alt="Screenshot 2022-11-18 at 2 15 01 PM" src="https://user-images.githubusercontent.com/51680745/202698690-7eb647b6-64b0-4824-b503-e532fb6153c5.png">



<img width="1420" alt="Screenshot 2022-11-18 at 2 15 21 PM" src="https://user-images.githubusercontent.com/51680745/202698820-38aac99c-f1e8-425e-a67c-36ab25fa20fb.png">


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment] 2022-12-06 06:13
Hi @thanhthaitran,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-12-06 06:13 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.5
