### ISSUE TITLE
Magneto 2.3.4 - The Date of Birth should not be greater than today (JavaScript Calendar - DD/MM/YYYY)

### ISSUE THREAD

**Issue by gilbertsohal** [magento/magento2#27655] opened 2020-04-08 11:49 UTC
### Preconditions (*)

1. Magento version 2.3.4
2. Australia locale in admin
3. PHP ver 7.1
4. CLOUDLINUX 6.10

### Steps to reproduce (*)

1. Use JavaScript Calendar (Yes)
2. Date Fields Order (DD/MM/YYYY)
3. Screenshot - https://prnt.sc/rvdcgj
4. Customer > Edit Customer > Account Information > Date of Birth

### Expected result (*)

1. Save Customer Any Date of Birth without error
2.

### Actual result (*)

1. Showing error on save (The Date of Birth should not be greater than today.)
2. Screenshot - https://prnt.sc/rvdd2u

**Comment by sudheers-kensium** [comment] 2020-04-08 11:53
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-08 11:54
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-08 11:55
Hi @sudheers-kensium, here is your [Magento instance](https://i-27655-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27655-2-4-develop.instances.magento-community.engineering/admin_5375](https://i-27655-2-4-develop.instances.magento-community.engineering/admin_5375)
Login: `f6b6eb25` Password: `35ac5f6aef56`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment] 2020-04-08 12:36
@gilbertsohal **Use JavaScript Calendar**  setting for to enable or disable the JavaScript Calendar in product custom option, not for the time format in customer edit.

Please check below link
https://docs.magento.com/m2/ce/user_guide/stores/attribute-date-time-options.html

![image](https://user-images.githubusercontent.com/50358141/78784796-9c888e00-79c3-11ea-8146-2a80baca7ef5.png)

**Comment by sudheers-kensium** [comment] 2020-04-08 12:40
This is not an issue, so I am closing this.

**Comment by gilbertsohal** [comment] 2020-04-08 12:58
Hi

> This is not an issue, so I am closing this.

Why this issue happening with my fresh Installation can you investigate
Showing error on save (The Date of Birth should not be greater than today.)
Screenshot - https://prnt.sc/rvdd2u

**Comment by sudheers-kensium** [comment] 2020-04-08 13:34
@gilbertsohal Please use calendar to choose the date. You are entering wrong format.

**Comment by gilbertsohal** [comment] 2020-04-08 13:45
> @gilbertsohal Please use calendar to choose the date. You are entering wrong format.

Sorry about miss understanding forgot about the calendar.

Please check the Date of Birth error. I installed fresh magneto 2.3.4 and getting below error.

Customer > Edit Customer > Account Information > Date of Birth

Screenshot 
https://prnt.sc/rvdd2u

Could you please help me.

**Comment by sudheers-kensium** [comment] 2020-04-08 13:51
@gilbertsohal Click on calendar icon and select the date.

**Comment by gilbertsohal** [comment] 2020-04-08 14:00
> @gilbertsohal Click on calendar icon and select the date.

Yes i m doing same click on calendar icon and selecting date but i m getting error if i select MM/DD/YYYY then its working fine but i need DD/MM/YYYY

Screenshot (MM/DD/YYYY)
https://prnt.sc/rvgavu

Screenshot 1 (DD/MM/YYYY)
https://prnt.sc/rvgcgt

Same thing happening with product Set as new

Screenshot 1
https://prnt.sc/rvd3o8

Screenshot 2
https://prnt.sc/rvd42u

**Comment by sudheers-kensium** [comment] 2020-04-08 14:27
@gilbertsohal  To change visible date format in date inputs You need to set proper Interface Locale in the Account Setting. Please follow below steps and save the configuration.

![image](https://user-images.githubusercontent.com/50358141/78795833-1a07ca80-79d3-11ea-9e60-b9c6554db374.png)

**Comment by gilbertsohal** [comment] 2020-04-08 14:32
> @gilbertsohal To change visible date format in date inputs You need to set proper Interface Locale in the Account Setting. Please follow below steps and save the configuration.
> 
> ![image](https://user-images.githubusercontent.com/50358141/78795833-1a07ca80-79d3-11ea-9e60-b9c6554db374.png)

I have setup everything Please check screenshot.
https://prnt.sc/rvh37p

**Comment by sudheers-kensium** [comment] 2020-04-08 15:05
@gilbertsohal This is working in Magento 2.4-develop instance

**Comment by gilbertsohal** [comment] 2020-04-08 15:27
> @gilbertsohal This is working in Magento 2.4-develop instance

But its not working on my Magento version 2.3.4. Is this possibility i have new VPS server and newly account created in WHM is this possibility to miss any php extension or configuration.

**Comment by Jibin1996** [comment] 2020-04-23 11:17
So what was the issue then for showing "The Date of Birth should not be greater than today." I have the same issue now. I am using 2.3.4 and why did you close it when the issue wasn't fixed

**Comment by gilbertsohal** [comment] 2020-04-23 11:21
> So what was the issue then for showing "The Date of Birth should not be greater than today." I have the same issue now. I am using 2.3.4 and why did you close it when the issue wasn't fixed

Yes this issue is still present in 2.3.4 nobody want to fix it...lol

**Comment by gilbertsohal** [comment] 2020-04-23 11:25
Screenshot (MM/DD/YYYY)
https://prnt.sc/rvgavu

Screenshot 1 (DD/MM/YYYY)
https://prnt.sc/rvgcgt

Same thing happening with product Set as new

Screenshot 1
https://prnt.sc/rvd3o8

Screenshot 2
https://prnt.sc/rvd42u

**Comment by jkg1996** [comment] 2020-04-23 11:26
I have the same issue exact same issue I am not sure why this is happening like its unreal.

**Comment by jkg1996** [comment] 2020-04-23 11:30
I am only seeing this issue on the customer section in admin, if I update a customer I get this error.
I can see the date is picking up on Catalog Price Rule, Basket Price Rules

**Comment by jkg1996** [comment] 2020-04-23 12:39
@gilbertsohal I found a temporary solution for amine customer dob issue
core file -> Need to create a patch magento\module-ui\view\base\web\js\lib\validation\rules.js
"validate-dob": [
                function (value) {
                    **return true;** - this does the job
                    if (value === "") {
                        return true;
                    }

                    return moment(value).isBefore(moment());
                },

**Comment by gilbertsohal** [comment] 2020-04-23 12:47
> @gilbertsohal I found a temporary solution for amine customer dob issue
> core file -> Need to create a patch magento\module-ui\view\base\web\js\lib\validation\rules.js
> "validate-dob": [
> function (value) {
> **return true;** - this does the job
> if (value === "") {
> return true;
> }
> 
> ```
>                 return moment(value).isBefore(moment());
>             },
> ```

Sorry what to do here?

**Comment by jkg1996** [comment] 2020-04-23 12:51
Check it in your core file add **return true;** before the if statement.
The core file is located ->magento\module-ui\view\base\web\js\lib\validation\rules.js line 1071

**Comment by gilbertsohal** [comment] 2020-04-23 12:58
> Check it in your core file add **return true;** before the if statement.
> The core file is located ->magento\module-ui\view\base\web\js\lib\validation\rules.js line 1071
> 
> ```
> validate-dob': [
>             function (value) {
>                 return true; //This will fix it for now
>                 if (value === '') {
>                     return true;
>                 }
> 
>                 return moment(value).isBefore(moment());
>             },
>             $.mage.__('The Date of Birth should not be greater than today.')
>         ]
> ```

My Coding already showing that

'validate-dob': [
            function (value) {
                if (value === '') {
                    return true;
                }

                return moment(value).isBefore(moment());
            },
            $.mage.__('The Date of Birth should not be greater than today.')
        ]

**Comment by jkg1996** [comment] 2020-04-23 13:01
Did that work for you? after adding a new return true before the if statement

**Comment by gilbertsohal** [comment] 2020-04-23 13:02
> Did that work for you? after adding a new return true before the if statement

Sorry not working for me. Do i need to clear cache or deploy static content?

**Comment by jkg1996** [comment] 2020-04-23 13:04
Oh yes you need to clear clear cache and I did ran set:di:compile please run set:up as well

**Comment by jkg1996** [comment] 2020-04-23 13:05
It's working for me now I can save/edit a customer from the admin area

**Comment by gilbertsohal** [comment] 2020-04-23 13:07
Can't we add same file in theme folder and change code coz core files always risky...

**Comment by gilbertsohal** [comment] 2020-04-23 13:45
> Did it work for you?
> You can add a patch for this, I wanted to make sure it works for you that's why I asked you to check in core @gilbertsohal

Yes, great its working fine.

**Comment by jkg1996** [comment] 2020-04-23 13:58
Hi @gilbertsohal  I won't add it in frontend I am not sure would that work, to be honest.
I created a patch for this. good to hear you got it working too.

is that product thing a custom module? or core?

**Comment by gilbertsohal** [comment] 2020-04-23 13:59
> Hi @gilbertsohal I won't add it in frontend I am not sure would that work, to be honest.
> I created a patch for this. good to hear you got it working too.
> 
> is that product thing a custom module? or core?

Yes this is core functionality not working with dd/mm/yyyy

**Comment by jkg1996** [comment] 2020-04-23 14:05
@gilbertsohal I will check the js file maybe you are missing this return true there as well

**Comment by gilbertsohal** [comment] 2020-04-23 14:18
If you can find out will be much appreciated.

**Comment by jkg1996** [comment] 2020-04-23 14:21
can you tell me which core module it is? like i can't see it on mine

**Comment by gilbertsohal** [comment] 2020-04-23 14:25
I think this is module-catalog

**Comment by jkg1996** [comment] 2020-04-23 14:28
Hi @gilbertsohal 
the same issue you have with the product
https://github.com/magento/magento2/issues/12215
the fix they provided
https://github.com/Magonex/module-datetime

**Comment by gilbertsohal** [comment] 2020-04-23 14:29
they put this function here
vendor\magento\framework\Stdlib\DateTime\Filter

**Comment by jkg1996** [comment] 2020-04-23 14:32
Yeah, but it might fix it not sure about this issue but could be the right one

**Comment by gilbertsohal** [comment] 2020-04-23 16:02
The mention module is 2 year old. i don't think so this will work.

Where have all the magneto 2 developer gone!! Please help

**Comment by Gabiunlock** [comment] 2020-05-20 21:38
hello, i have same problem in register customer "The Date of Birth should not be greater than today." u can solved this problem?

**Comment by ssniranga** [comment] 2020-05-25 00:14
I am having the same issue on Register form

**Comment by DanielRuf** [comment] 2020-05-25 00:30
https://github.com/magento/magento2/issues/27655#issuecomment-618378693
https://github.com/magento/magento2/issues/27655#issuecomment-618384385

**Comment by ssniranga** [comment] 2020-05-25 08:45
> [#27655 (comment)](https://github.com/magento/magento2/issues/27655#issuecomment-618378693)
> [#27655 (comment)](https://github.com/magento/magento2/issues/27655#issuecomment-618384385)

I added above to the JS file but still getting the issue mate

**Comment by DanielRuf** [comment] 2020-05-25 09:17
> I added above to the JS file but still getting the issue mate

Did you recompile everything?

https://github.com/magento/magento2/issues/27655#issuecomment-618391308

**Comment by ssniranga** [comment] 2020-05-25 09:28
> > I added above to the JS file but still getting the issue mate
> 
> Did you recompile everything?
> 
> [#27655 (comment)](https://github.com/magento/magento2/issues/27655#issuecomment-618391308)

Yes. Did everything

**Comment by jkg1996** [comment] 2020-05-27 09:04
@ssniranga how you editing the core or patch?

**Comment by jkg1996** [comment] 2020-05-27 09:05
this fix worked for me I am not getting that error now. try to change the core first see if that works then create a patch.
The core file is located ->magento\module-ui\view\base\web\js\lib\validation\rules.js line 1071

**Comment by Gabiunlock** [comment] 2020-05-28 22:08
fix for me, in cloudflare clear cache clear all cache  and found fine.

**Comment by ncompass** [comment] 2020-05-29 14:25
Experiencing the same issue here on Magento 2.3.4-p2 on the customer registration page. 

Above fixes only work for the admin area.

**Comment by ncompass** [comment] 2020-05-29 14:25
en_GB locale DD/MM/YYYY

**Comment by ncompass** [comment] 2020-05-29 14:52
A better fix for magento\module-ui\view\base\web\js\lib\validation\rules.js is found here...  

https://github.com/magento/magento2/issues/27027
https://github.com/magento/magento2/commit/8f81132dcf27bc1b09ba89a6e7002a2f3dd02ef2


Still trying to find a fix for vendor/magento/module-customer/view/frontend/web/js/validation.js for the frontend...

**Comment by ncompass** [comment] 2020-05-29 15:18
Ok so I've fixed the front end/registration page.. 

@ssniranga - I can see you had the same issue.

"vendor/magento/module-customer/view/frontend/web/js/validation.js"
change the below line..
return moment(value).isBefore(moment());
to
return moment(value, ["YOUR DATE FORMAT HERE"]).isBefore(moment());

For us (enGB / UK format):-
return moment(value, ["DD.MM.YYYY"]).isBefore(moment());

Your welcome.

**Comment by ssniranga** [comment] 2020-05-30 06:39
@ncompass Legend. I added the fixed and it seems working now. :).

Thank you very much Guys.

**Comment by chandu-pinpoint** [comment] 2020-06-04 13:16
This issue still exists on magento 2.3.5-p1

**Comment by swathishs** [comment] 2020-06-04 17:44
@chandu-pinpoint : Tested the issue in 2.3.5 p1 the issue is not reproducible

1. Date format.
![image](https://user-images.githubusercontent.com/58288685/83792063-2f8a2f80-a6b8-11ea-9aaf-debdee8e185e.png)

2. Date of birth:
![E2E5R5Bpox](https://user-images.githubusercontent.com/58288685/83792449-b808d000-a6b8-11ea-9779-740242dc9fc2.gif)

3. Can  Set Product as New From for the product:
![wUvOBcHj2q](https://user-images.githubusercontent.com/58288685/83792689-0322e300-a6b9-11ea-9880-2add01b2bba4.gif)

 Note: This issue was reported by the reporter. Could you please let me know this issue is what your saying or any other issue is there. please let me know

**Comment by chandu-pinpoint** [comment] 2020-06-04 18:07
@ swathishs  The issue is during Create customer account on frontend.

**Comment by swathishs** [comment] 2020-06-05 15:31
@chandu-pinpoint : Thank you for your report.
Seems a similar issue is already been in ready for dev. 
Please check  - https://github.com/magento/magento2/issues/28482

Hence closing the issue

**Closed as completed by swathishs** 2020-06-05 15:31 UTC
Labels: duplicate, Issue: Format is valid, Reported on 2.3.4

**Comment by jhonathan93** [comment] 2020-07-10 01:26
@ncompass thank you my friend
