### ISSUE TITLE
As low as displays incorrect pricing on category page, tax appears to be added twice

### ISSUE THREAD

**Issue by devchris79** [magento/magento2#21383] opened 2019-02-21 12:21 UTC
### Preconditions (*)

1. Magento 2.2.6

### Steps to reproduce (*)

1. Add a new item with some tier pricing
2. Set Stores->Configuration->Sales->Tax->Price Display Settings->Display Product Prices In Catalog to "Including and Excluding Tax".

### Expected result (*)

1. As low as price to be correct, even if displayed without tax only.
2.

### Actual result (*)

1. As low as price appears to have tax added twice, this does not happen if Excluding Tax is used as display option.
2. Please see example below, price is correct on product page but not in the category view.
![ds2824a](https://user-images.githubusercontent.com/43850303/53168349-59f2cf00-35d2-11e9-88ea-968a0c878704.jpg)
![ds2824b](https://user-images.githubusercontent.com/43850303/53168369-5eb78300-35d2-11e9-9451-b8e4f86a8692.jpg)

**Comment by magento-engcom-team** [comment] 2019-02-21 12:21
Hi @devchris79. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@devchris79 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-02-21 12:53
Hi @krishprakash. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by krishprakash** [comment] 2019-02-21 12:55
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-21 12:55
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-21 12:56
Hi @krishprakash, here is your [Magento instance](https://i-21383-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21383-2-2-develop.instances.magento-community.engineering/admin](https://i-21383-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AltayAkkus** [comment] 2019-02-21 17:06
@magento-engcom-team Give me 2.2.6-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-21 17:06
Hi @AltayAkkus. Thank you for your request. I'm working on Magento 2.2.6-develop instance for you

**Comment by AltayAkkus** [comment] 2019-02-21 17:14
@magento-engcom-team Give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-21 17:14
Hi @AltayAkkus. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-21 17:15
Hi @AltayAkkus, here is your [Magento instance](https://i-21383-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21383-2-2-develop.instances.magento-community.engineering/admin](https://i-21383-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by devchris79** [comment] 2019-02-22 09:42
The fix suggested by Jitheesh appears to work for me 👍

**Comment by magento-engcom-team** [comment] 2019-02-23 08:34
:white_check_mark: Confirmed by @rogyar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98410` were created

**Issue Available**: @rogyar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-03-01 08:00
Hi @devchris79. Thank you for your report. 
The issue has been fixed in magento/magento2#21395 by @Jitheesh in 2.3-develop branch
Related commit(s):
 - [c9fff890e5da3e9e173fd2163f8accc7ef5338e6](https://github.com/magento/magento2/commit/c9fff890e5da3e9e173fd2163f8accc7ef5338e6)
 - [70f25998f47337656e61300df1c348534f0d2271](https://github.com/magento/magento2/commit/70f25998f47337656e61300df1c348534f0d2271)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-01 08:00 UTC
Labels: Issue: Ready for Work, Component: Catalog, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by magento-engcom-team** [comment] 2019-03-06 13:25
Hi @devchris79. Thank you for your report. 
The issue has been fixed in magento/magento2#21527 by @eduard13 in 2.2-develop branch
Related commit(s):
 - [eaad776629a933b944663ef35c4bac08143d0592](https://github.com/magento/magento2/commit/eaad776629a933b944663ef35c4bac08143d0592)
 - [aa7fee51fb66d75800c7c454da013b75d565ebe4](https://github.com/magento/magento2/commit/aa7fee51fb66d75800c7c454da013b75d565ebe4)

The fix will be available with the upcoming 2.2.9 release.

**Comment by devchris79** [comment] 2019-03-29 10:44
I have upgraded to 2.3.1 and the issue appears in that version too.

**Comment by Jitheesh** [comment] 2019-03-29 11:24
"The fix will be available with the upcoming 2.3.2 release"

**Comment by devchris79** [comment] 2019-03-29 13:35
Hi @Jitheesh,

Do you know where the line in 2.3.1 is that needs changing? 
/vendor/magento/module-catalog/Pricing/Price/MinimalTierPriceCalculator.php just looks like function prototypes.

Thanks in advance if you are able to help.

**Comment by Jitheesh** [comment] 2019-04-01 11:47
Hi @devchris79 

You can refer changes from this commit c9fff890e5da3e9e173fd2163f8accc7ef5338e6

**Comment by devchris79** [comment] 2019-04-01 15:36
Ah, was looking in MinimalPriceCalculatorInterface.php, too many similar sounding files :-)
Thanks Jitheesh
