### ISSUE TITLE
Catalog pricerules are not working with custom options as expected in Magento 2.3.0 product details page

### ISSUE THREAD

**Issue by dcwnaveen** [magento/magento2#22856] opened 2019-05-13 07:22 UTC
Catalog price rules are not working with custom options as expected in Magento 2.3.0 product details page. We created the catalog price-rule 10% discount for some x products and expecting the results like a 10% discount on total price( (product price + options price) * 10%). But results are showing discounted price + custom options price. 

**Preconditions**
Magento 2.4-develop
PHP 7.3

**Steps to reproduce**
1. Go to Admin->Marketing->Catalog Price Rule->Add New Rule;
2. Fill all required fields and set _Discount Amount_ to **10** % for ex.;
![Screenshot from 2020-06-10 12-30-57](https://user-images.githubusercontent.com/51679138/84251693-60ce8980-ab16-11ea-94ed-da17fdc2473c.png);
3. Click on **Save and Apply** button;
4. Create simple product (Price = 1000 $) with a drop-down custom option (**Size** for example); 
Options for **Size**:

-  _**Small**_ price is 100$,
-  _**Medium**_ price is 200$,
-  _**Large**_ price is 500$. 

![Screenshot from 2020-06-10 12-34-54](https://user-images.githubusercontent.com/51679138/84252083-d5092d00-ab16-11ea-9093-50707da1db59.png)

5. Go to Storefront;
6. Open created before product;

**Expected Result**

We are expecting the 10% discount on the total price (product price + options price) * 10%). For:

- Small - 990$,
- Medium - 1080$,
- Large - 1350$

**Actual result**

Its showings final prices like:
-  Small - 1,000$,
- Medium - 1,100$,
- Large - 1,400$
![Screenshot from 2019-05-13 12-51-09](https://user-images.githubusercontent.com/28339353/57602878-eaabcc00-757d-11e9-9069-c8ad529d4608.png)

**Comment by dcwnaveen** [comment] 2019-05-13 07:27
@magento-engcom-team give me 2.3-develop instance So I will create the product and catalog price rule.

**Comment by magento-engcom-team** [comment] 2019-05-13 07:27
Hi @dcwnaveen. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-05-13 07:28
Hi @dcwnaveen, here is your [Magento instance](https://i-22856-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22856-2-3-develop.instances.magento-community.engineering/admin](https://i-22856-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by dcwnaveen** [comment] 2019-05-13 07:38
@magento-engcom-team 
I have created one product with custom options and created the catalog price rule.
please reindex and run the cron job for a discounted price.
https://i-22856-2-3-develop.instances.magento-community.engineering/product-a.html

**Comment by dcwnaveen** [comment] 2019-05-13 07:51
Hi @AlexWorking. Please check the issue and confirm.
https://i-22856-2-3-develop.instances.magento-community.engineering/product-a.html

**Comment by magento-engcom-team** [comment] 2019-05-13 09:41
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99657`, `MAGETWO-99658` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment] 2020-01-08 05:13
Hi @dcwnaveen. Thank you for your report. 
The issue has been fixed in magento/magento2#22917 by @p-bystritsky in 2.4-develop branch
Related commit(s):
 - [a8f3b9e8931d69a4bfa3af51483ed89b16292eea](https://github.com/magento/magento2/commit/a8f3b9e8931d69a4bfa3af51483ed89b16292eea)
 - [4fb5da819cb2517de204e7dcf8c545505eeabd2c](https://github.com/magento/magento2/commit/4fb5da819cb2517de204e7dcf8c545505eeabd2c)
 - [56142aea26c20689ef2f36495c48b58d5417efcb](https://github.com/magento/magento2/commit/56142aea26c20689ef2f36495c48b58d5417efcb)
 - [74892074f9bbed128a4c0c2e7c14a8f47d317755](https://github.com/magento/magento2/commit/74892074f9bbed128a4c0c2e7c14a8f47d317755)
 - [20ae9e3f3c9b89afe9a7439728cb05f20c09080d](https://github.com/magento/magento2/commit/20ae9e3f3c9b89afe9a7439728cb05f20c09080d)
 - [8b159d0e6e2d7d2034a2960cd484fe33a50ed2b3](https://github.com/magento/magento2/commit/8b159d0e6e2d7d2034a2960cd484fe33a50ed2b3)
 - [4ac980bbb6783472f24295ac835723412de8680f](https://github.com/magento/magento2/commit/4ac980bbb6783472f24295ac835723412de8680f)
 - [fbea751258747182da71d1175e466405c80b01ab](https://github.com/magento/magento2/commit/fbea751258747182da71d1175e466405c80b01ab)

The fix will be available with the upcoming 2.4.0 release.

**Comment by engcom-Alfa** [comment] 2020-06-10 08:29
After multiple discussion and several attempts to fix consequences was decided to revert this PR #22917

Purpose for revert
During internal regression testing for future 2.4.0 release Core team found two regression bugs
1. [MC-34245] Adding a Product with Customizable Option to Wish List results in a fatal error
2. [MC-34322] Adding a Product with Customizable Option to a "Gift Registry" results in a fatal error when loading shared Gift Registry page

Root cause analysis defined that changes from #22917  brought these regression bugs.

So, we will reopen and confirm this issue again.

**Comment by magento-engcom-team** [comment] 2020-06-10 09:45
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35065` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by AbdulRahmanAbouzaid** [comment] 2020-06-10 11:14
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-10 11:14
Hi @AbdulRahmanAbouzaid. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by AbdulRahmanAbouzaid** [comment] 2020-06-10 11:57
@magento-engcom-team give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-10 11:57
Hi @AbdulRahmanAbouzaid. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by sdzhepa** [comment] 2020-10-23 20:52
The issue has been fixed by Magento team and delivered with internal PR
Related commits https://github.com/magento/magento2/search?q=MC-35065&type=commits

**Comment by ashar01** [comment] 2023-10-02 12:57
@sdzhepa @magento-engcom-team @VladimirZaets This ticket says the issue is fixed but i am bit confused after reading this https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/support-tools/patches/v1-1-23/acsd-47107-catalog-price-rule-is-applied-to-custom-options.html?lang=en
This document magento reverts this fix in m2.4.6 release.

**Comment by sprankhub** [comment] 2024-01-17 08:22
@sdzhepa @magento-engcom-team, could you please check the last comment?

**Comment by engcom-Dash** [comment] 2024-01-23 05:05
Hi @dcwnaveen 

Thank you for reporting and collaboration.

Verified the issue in Magento 2.4.7-beta2 and 2.4 dev instances and the issue is reproducible in both the instances. 

Catalog price rules are not working with custom options.

Please refer the attached screenshots.
<img width="1440" alt="Screenshot 2024-01-22 at 3 15 17 PM" src="https://github.com/magento/magento2/assets/60198592/91c0dbd7-4c7a-41ca-a233-27769a674d76">
<img width="1440" alt="Screenshot 2024-01-22 at 3 15 17 PM" src="https://github.com/magento/magento2/assets/60198592/fd7c453a-bdb2-49f1-bcc7-dba1ad4c7e52">
<img width="1440" alt="Screenshot 2024-01-22 at 4 22 02 PM" src="https://github.com/magento/magento2/assets/60198592/bffb1568-40e9-4518-a939-6be66f3cf5a3">

**Comment by engcom-Charlie** [comment] 2024-11-27 09:56
Adobe Commerce Engineering team started working on this issue. We will reach out to you if we need more information and you will get notified once the issue is fixed. Please leave comments for any further questions. 

Thank you!

**Comment by engcom-Bravo** [comment] 2024-12-06 04:03
Hi @dcwnaveen,

Thanks for your reporting and collaboration.

This is the default functionality of Magento Its not a bug.We discussed this internally with the product owner and confirmed that this is working as expected. We will not be modifying the functionality at this time.

Thanks.

**Closed as completed by engcom-Bravo** 2024-12-06 04:03 UTC
Labels: Component: Catalog, Component: CatalogRule, Issue: Confirmed, Component: Pricing, Reproduced on 2.4.x, Priority: P1, Severity: S1, Triage: Done, Progress: done, CD, Event: Distributed CD India 2020, Reported on 2.4.x, Area: Catalog
