### ISSUE TITLE
Provide a setting to allow previously used passwords to be re-used when changing passwords

### ISSUE THREAD

**Issue by diamondavocado** [magento/magento2#21862] opened 2019-03-20 17:31 UTC
### Description (*)
Currently Magento 2 prevents you from re-using old passwords when changing your password. The code states "at least 4" previous passwords will be blocked from re-use. This is arbitrary and only leads to insecure practices such as incrementing passwords (`hunter2` -> `hunter3`) or writing passwords down on paper. 

Guidance from the National Cyber Security Centre explicitly advises against this poor practice: https://www.ncsc.gov.uk/blog-post/problems-forcing-regular-password-expiry

An option to allow re-use of old passwords should be added to Magento 2.

### Expected behavior (*)
An option to allow re-use of old passwords should be added to the Stores -> Configuration section.

### Benefits
Eliminate arbitrary password security requirements. 

Guidance from the National Cyber Security Centre explicitly advises against this poor practice: https://www.ncsc.gov.uk/blog-post/problems-forcing-regular-password-expiry

### Additional information
It's very annoying.

**Comment by magento-engcom-team** [comment] 2019-03-20 17:31
Hi @diamondavocado. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@diamondavocado do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-03-21 07:22
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-03-26 12:40
Hi @kisroman. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by tomekjordan** [comment] 2019-03-26 15:52
100% agree. This is poor practice and gives poor security. Its just another problem for users that makes UX worse with not gain for security

**Comment by orlangur** [comment] 2019-05-05 23:29
Quoting a PR:

>Enforcing not reusing old passwords came from PCI DSS rules:
>> 8.2.5 Do not allow an individual to submit a new password/passphrase that is the same as any of the last four passwords/passphrases he or she has
used.
https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf?agreement=true&time=1557036684432

@diamondavocado @tomekjordan what do you think?

**Comment by VasylShvorak** [comment] 2019-06-05 10:42
@diamondavocado , thank you for your report. We are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Closed as completed by VasylShvorak** 2019-06-05 10:42 UTC
Labels: Progress: needs update, Issue: Clear Description, Issue: Format is valid, Component: User

**Comment by lastralab** [comment] 2021-02-17 20:10
Hi, if this is helpful for someone, I just went straight to the DB and ran:
```sql
SELECT * FROM admin_passwords WHERE user_id IN (SELECT user_id FROM admin_user WHERE username = '<USERNAME>');
DELETE FROM admin_passwords WHERE password_id IN (<OLD ID>, <OLD ID>, <OLD ID>);
UPDATE admin_passwords SET last_updated = UNIX_TIMESTAMP(NOW()) WHERE user_id = <USER ID>;
```
Sorry if not best practice, but I no longer have to memorize password variations :)

**Comment by cptX** [comment] 2022-11-12 14:59
I also am frustrated about forcing me to not use a password I want and happened to be used before...
If there articles that state that actually is a bad methodology maybe we should reconsider
