### ISSUE TITLE
setIsPickupLocationActive() method not found

### ISSUE THREAD

**Issue by nbennett25** [magento/magento2#34443] opened 2021-10-26 15:03 UTC
### Preconditions (*)

1. Magento 2.4.2-p2

### Steps to reproduce (*)

1. Open store page, or

1. Go to pdp, add product to cart

### Expected result (*)

1. Store loads, or

1. Product is added to cart

### Actual result (*)

1. Store does not load, or

1. Product is not added to cart

Technical notes:
Multiple MSI modules are calling `setIsPickupLocationActive()` which is not defined. Stack trace:
`[2021-10-26 13:58:54] main.CRITICAL: Error: Call to undefined method Magento\InventoryApi\Api\Data\SourceExtension::setIsPickupLocationActive() in /[]/vendor/magento/module-inventory-in-store-pickup/Model/Source/InitPickupLocationExtensionAttributes.php:57`

If `setIsPickupLocationActive` is supposed to be a magic method, does the `SourceExtension` model not extend a class that supports it?

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2021-12-09 06:58
Hi (username),

Thank you for reporting the issue.

However, we tried to reproduce it on Magento 2.4-develop but the issue is not reproducible.

Steps followed to reproduce issue:

1. Installed the fresh Magento 2.4-dev instance.
2. Added the sample product data.
3. Visited the store website, product details page and added the product to the cart (See the attached screenshots)
<img width="1291" alt="Screenshot 2021-12-08 at 5 33 13 PM" src="https://user-images.githubusercontent.com/51681618/145348809-88ec6026-09a6-4360-b837-ac1a8c8c7aa9.png">
<img width="1291" alt="Screenshot 2021-12-08 at 5 33 31 PM" src="https://user-images.githubusercontent.com/51681618/145348832-16f3733f-c775-4f35-b7e0-739f89911b84.png">
<img width="1291" alt="Screenshot 2021-12-08 at 5 33 48 PM" src="https://user-images.githubusercontent.com/51681618/145348836-c61257c7-5d7e-4096-bc53-eb9c43d83b0a.png">
<img width="1291" alt="Screenshot 2021-12-08 at 5 34 24 PM" src="https://user-images.githubusercontent.com/51681618/145348837-b393074b-9344-4d16-b088-090b5662fd47.png">

If the issue still persists at your end then please provide some more details like error details, screenshots, or video, accordingly, I’ll try to reproduce it again.

Thanks

**Comment by engcom-Hotel** [comment] 2021-12-24 08:47
Dear @nbennett25,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2021-12-24 08:47 UTC
Labels: Issue: needs update
