### ISSUE TITLE
`Magento_ServiceProxy` has an undefined hard dependency on `Magento_PaymentServicesDashboard`

### ISSUE THREAD

**Issue by fritzmg** [magento/magento2#39124] opened 2024-08-29 09:17 UTC
### Preconditions and environment

- Magento version: 2.4.7-p2
- Disabled `Magento_PaymentServicesDashboard` module

### Steps to reproduce

1. Install Magento 2.4.7-p2
2. Disable `Magento_PaymentServicesDashboard` (and all modules that Magento says depend on it).
3. Access the back end

### Expected result

The back end can be accessed.

### Actual result

The following error occurs:

```
Exception #0 (LogicException): Could not create an acl object: Invalid Document 
Error in merged XML after reading vendor/magento/module-config/etc/acl.xml
Element 'resource': The attribute 'title' is required but missing.
```

### Additional information

The problem is, that `Magento_ServiceProxy` actually depends on `Magento_PaymentServicesDashboard` because it references a `<resource>` in its `etc/acl.xml` that is actually defined by `Magento_PaymentServicesDashboard`:

```xml
<!-- vendor/magento/module-service-proxy/etc/acl.xml -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Acl/etc/acl.xsd">
    <acl>
        <resources>
            <resource id="Magento_Backend::admin">
                <resource id="Magento_Sales::sales">
                    <resource id="Magento_Sales::sales_operation">
                        <resource id="Magento_PaymentServicesDashboard::paymentservices">
                            <resource id="Magento_ServiceProxy::services" title="Saas Services Proxy" translate="title" sortOrder="100"/>
                        </resource>
                    </resource>
                </resource>
            </resource>
        </resources>
    </acl>
</config>
```

The `<resource id="Magento_PaymentServicesDashboard::paymentservices">` would be defined by `Magento_PaymentServicesDashboard`, but since the latter is disabled, the `<resource>` does not exist and the XML validation will then fail with the aforementioned error.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-09-02 09:50
Hi @fritzmg,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

<img width="1426" alt="Screenshot 2024-09-02 at 15 17 22" src="https://github.com/user-attachments/assets/c4c044ae-ce7d-42fd-b6eb-0357cea9c0ad">



We are still able to access the backend.

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by fritzmg** [comment] 2024-09-02 10:04
@engcom-Bravo I think you did not follow the reproduction steps exactly:

> Disable `Magento_PaymentServicesDashboard` __(and all modules that Magento says depend on it)__.

According to your screenshot you haven't disabled all modules that depend on `Magento_PamentServicesDashboard`.

**Comment by RichardOutram** [comment] 2024-10-09 09:48
This issue happened for me to.

Related to this https://github.com/magento/magento2/issues/38839#issuecomment-2356281493

**Comment by engcom-Bravo** [comment] 2024-10-10 05:01
@RichardOutram Thanks for your contribution!!.

Hi @fritzmg,

Thanks for your update.

similar issue has been confirmed here https://github.com/magento/magento2/issues/38839.

Hence we are closing this as duplicate.

Thanks.

**Closed as completed by engcom-Bravo** 2024-10-10 05:01 UTC
Labels: duplicate, Issue: needs update, Reported on 2.4.7-p2
