### ISSUE TITLE
Error while fetching a request token: cannot create request token because consumer token is not a verifier token

### ISSUE THREAD

**Issue by userException** [magento/magento2#2580] opened 2015-12-02 08:10 UTC
POST: http://192.168.1.180/magento/oauth/token/request

This api returns an error in response: cannot create request token because consumer token is not a verifier token.

Authorization header: OAuth oauth_consumer_key="------",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1449043011",oauth_nonce="kkcfIG",oauth_version="1.0",oauth_signature="XVZWKkbNEnNn433zG6Oa6h%2FPuIY%3D"

**Comment by davidalger** [comment] 2015-12-02 15:37
Closing as duplicate of #2540.

**Closed as completed by davidalger** 2015-12-02 15:37 UTC
