### ISSUE TITLE
Use of undefined constant GLOB_BRACE in dependency "magento/magento-composer-installer"

### ISSUE THREAD

**Issue by jissereitsma** [magento/magento2#36116] opened 2022-09-08 15:16 UTC
### Preconditions (*)
Magento 2.4.5

### Steps to reproduce (*)
Following the PHP manual (https://www.php.net/manual/en/function.glob.php) the constant `GLOB_BRACE` is not available on some systems. More specifically this is an issue on Docker containers based on Alpine Liux. Create a Docker container based on Alpine Linux, install Magento in it, deploy the sample data and then remove them again with the command `bin/magento sampledata:deploy`. The last steps of the removal delete various files. At that very moment, the call https://github.com/magento/magento-composer-installer/blob/master/src/MagentoHackathon/Composer/Magento/Deploystrategy/DeploystrategyAbstract.php#L345 causes the command to crash.

### Expected result (*)
The expected result is that the command finishes succesfully.

### Actual result (*)
The PHP Fatal Error `Undefined constant "MagentoHackathon\Composer\Magento\Deploystrategy\GLOB_BRACE"#0 vendor/magento/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Deploystrategy/DeploystrategyAbstract.php(319): MagentoHackathon\Composer\Magento\Deploystrategy\DeploystrategyAbstract->removeContentOfCategory()` occurs.

**Comment by engcom-Hotel** [comment] 2022-09-08 17:09
Duplicate of #36062

**Closed as completed by engcom-Hotel** 2022-09-08 17:09 UTC
Labels: Issue: ready for confirmation

**Comment by jissereitsma** [comment] 2022-09-08 17:34
Whoops, I didn't spot that issue yet. Thanks for closing this one and sorry for the trouble.
