### ISSUE TITLE
DbValidator will fail even if required privileges are granted

### ISSUE THREAD

**Issue by TheNavigat** [magento/magento2#5783] opened 2016-07-24 10:52 UTC
Magento version: Latest version as I type this. PHP's version and MySQL versions: latest as well.

To reproduce, create a MySQL user, grant the user all permissions, and configure Magento accordingly, then try to update the database.

What's expected is that the database will update correctly. What happens is that it raises an exception at https://github.com/magento/magento2/blob/develop/setup/src/Magento/Setup/Validator/DbValidator.php#L181

This happens because of the usage of `array_diff`. If more privileges are granted on the database than the ones hard-coded in `$requiredPrivileges`, an exception will be raised.

An appropriate fix would be using `array_intersect` and comparing the result with `$requiredPrivileges` itself.

**Comment by SerhiyShkolyarenko** [comment] 2016-09-13 09:55
Hi @TheNavigat !
Some questions to clarify:
1. "configure Magento accordingly". Do you mean setting that username and password in web installer?
   1. "try to update the database". What exactly do you mean here?

**Comment by andimov** [comment] 2016-10-10 14:52
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by andimov** 2016-10-10 14:52 UTC
Labels: bug report, Progress: needs update
