### ISSUE TITLE
Paypal express was not working with cancel discount code in cart/basket page.

### ISSUE THREAD

**Issue by rajubytes** [magento/magento2#33813] opened 2021-08-16 13:24 UTC
**Preconditions**
Paypal express was not working with cancel discount code in cart page.

**Steps to reproduce**
Step 1. Set UK as merchant country
Step 2. Configure Paypal express with sandbox account.
Step 3. Added to cart 1 product with without login customer.
Step 4. Apply discount code from cart page.
Step 5. Remove discount code
Step 6. Click on Paypal express button.

**Expected result**
    Paypal express popup should be display.

**Actual result**
    Paypal express popup not display and given warning message "To check out, please sign in with your email address."

Screen with apply discount code
![paypal-discount-issue-1](https://user-images.githubusercontent.com/53551805/129570661-8ea56f54-2e30-4f98-9f1d-5b01aec705f6.png)

Screen with remove discount code
![paypal-discount-issue-2](https://user-images.githubusercontent.com/53551805/129570726-4d9af186-f1a7-41ba-859c-3738e4fab98e.png)

Screen with paypal warning message
![paypal-discount-issue-3](https://user-images.githubusercontent.com/53551805/129570749-0c6a1e16-5ba9-4d0d-9562-a89ca113757b.png)

**Comment by engcom-November** [comment] 2021-08-18 07:39
Hi @rajubytes,
This is the duplicate of https://github.com/magento/magento2/issues/33445 for which PR is in Progress. Hence closing this issue.
Thank you.

**Closed as completed by engcom-November** 2021-08-18 07:39 UTC
Labels: duplicate, Issue: ready for confirmation
