### ISSUE TITLE
Newsletter email template preview design issue

### ISSUE THREAD

**Issue by keyurshah070** [magento/magento2#3865] opened 2016-03-22 13:23 UTC
## Steps to reproduce
1. Login into magento with admin details
2. Go to Marketing> Newsletter Templates > Add New Template
3. Write your appropriate newsletter content and save and click on Preview Template
## Expected result
1. It should be display well design manner.
## Actual result
1. It mess-up design format,please check below screenshot

![email_new](https://cloud.githubusercontent.com/assets/17308601/13952979/93e2d658-f05f-11e5-91cc-61c8984eba15.png)

**Comment by AmerSej** [comment] 2016-04-11 12:19
I have the same problem. Is there a fix for that?

**Comment by moe-kayali** [comment] 2016-04-14 13:52
Same issue here on Magento 2.0.4
How Reproducible: Always.

**Comment by YellowSmith** [comment] 2016-05-05 07:59
Still not fixed. Any suggestions?

**Comment by kgvconsulting** [comment] 2016-06-04 16:09
the same here no PREVIEW, just upgraded to v 2.0.6 no changes empty page display

**Comment by teokolo** [comment] 2016-06-16 17:01
Same problem here.
Since I cannot preview newsletter, I'm just wondering if newsletter are sent out as expected.

**Comment by kgvconsulting** [comment] 2016-06-16 17:26
@teokolo - No they are not notting is emailed, it is Magento system issue, my personal opinion based on the last 10 months experience with different Magento versions, If you want all to work, just choose one version, install it and never more upgrade or do changes, the Magento upgrades does not include the old versions in full and you always will have issues with one or other component, It is just waist of time and resources, you can see also my ticket #4866 again assigned as MX that mean merchant experience - MX: merchant experience, admin panel stuff like defining products, etc. see https://mage2.pro/t/topic/1076

honestly do not expect too much help it is system issue, the new Magento version upgrade changes are made without any consideration of the old version system specification, and you have this mess, something is fixed or added other stop to work.

**Comment by Ctucker9233** [comment] 2016-06-27 21:20
+1 Experiencing the same issue in version 2.0.7....you would think they'd have built in a way to send a test newsletter to yourself to make sure it really works.

**Comment by sevos1984** [comment] 2016-09-14 16:22
This is fixed in develop https://github.com/magento/magento2/commit/182b2f2beb26f53f6522034d302d7c1beb1d60eb.  Ticket for 2.0 created MAGETWO-58417

**Comment by magento-engcom-team** [comment] 2017-10-11 12:30
@keyurshah070, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-11 12:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Customer, Issue:  Cannot Reproduce, Issue: Format is not valid
