### ISSUE TITLE
ca domains not working with 'validate-clean-url' 

### ISSUE THREAD

**Issue by Neo-Creo** [magento/magento2#30618] opened 2020-10-23 11:09 UTC
### Preconditions (*)

1. Magento Commerce 2.3.4 

### Steps to reproduce (*)
1. Validate url using 'validate-clean-url' in an input field
2. Validate value http://www.example.ca in the field

### Expected result (*)
1. The url should be validated successfully

### Actual result (*)
1. We get error "Please enter a valid URL. For example http://www.example.com or www.example.com."

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround.

**Comment by Neo-Creo** [comment] 2020-10-23 11:44
@magento I am working on it.

**Comment by Nazar65** [comment] 2020-10-23 12:29
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment] 2021-01-08 07:44
Duplicate of #30152

**Closed as completed by engcom-Alfa** 2021-01-08 07:44 UTC
Labels: Issue: ready for confirmation, Event: MageCONF CD 2020, Reported on 2.3.4
