### ISSUE TITLE
CHANGELOG.md is reporting the incorrect issue links (I expect to see this in the changelog)

### ISSUE THREAD

**Issue by MellenIO** [magento/magento2#27049] opened 2020-02-27 08:47 UTC
The Magento CHANGELOG.md reports every issue link as one for magento/magento2, when in fact we have multiple repositories each tracking their own set of changes (eg magento/graphql-ce)

### Preconditions (*)
View **CHANGELOG.md** - https://github.com/magento/magento2/blob/2.3/CHANGELOG.md

### Steps to reproduce (*)
Look in the 2.3.4 changelog for the following:
```md
    * [#167](https://github.com/magento/magento2/issues/167) -- Fatal error: Class 'Mage' not found (fixed in [magento/graphql-ce#800](https://github.com/magento/graphql-ce/pull/800))

```

### Expected result (*)
It should link to https://github.com/magento/graphql-ce/issues/167 (it's a GraphQL issue, not a Magento one) and have the issue title **Add support for '@magentoConfigFixture' annotation on API-functional tests** (or potentially link to https://github.com/magento/graphql-ce/issues/794 based off of the PR text?)

### Actual result (*)
It links to https://github.com/magento/magento2/issues/167 with the (very amusing) incorrect issue title.

**Comment by magento-engcom-team** [comment] 2020-03-01 04:42
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32032` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by okorshenko** [comment] 2020-10-26 18:18
Hi @MellenIO 
Thank you for your report. The issue is added to our tools internal backlog: DEVX-312

**Closed as completed by okorshenko** 2020-10-26 18:18 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Api, Reproduced on 2.4.x, Priority: P1, Severity: S1, Progress: done, Reported on 2.3.4
