### ISSUE TITLE
 Delete operation is forbidden for current area

### ISSUE THREAD

**Issue by Moinashraf** [magento/magento2#8631] opened 2017-02-21 07:59 UTC
I am trying all above possibilities to resolve this issue but the error shown in the frontend and In admin The address data should not display.

![screenshot from 2017-02-21 13-24-02](https://cloud.githubusercontent.com/assets/25338993/23155672/a690ca66-f839-11e6-9694-ff9f4d752020.png)
![screenshot from 2017-02-21 13-25-52](https://cloud.githubusercontent.com/assets/25338993/23155674/aa60de92-f839-11e6-89ac-9a1c37decb99.png)

**Comment by orlangur** [comment] 2017-02-21 17:31
It looks like you are trying to delete something on `frontend` while it is only allowed in `admin`.

Please describe issue using [template](https://github.com/magento/magento2/blob/develop/ISSUE_TEMPLATE.md) so that it can be reproduced on default Magento 2 installation.

**Comment by Moinashraf** [comment] 2017-02-22 04:28
Hello @orlangur,
When we are enable address field in customer_account_create.xml file using 
`<referenceBlock name="customer_form_register">
            <arguments>
                        <argument name="show_address_fields" xsi:type="string">1</argument>
            </arguments>
</referenceBlock>`
And when we want to register the user on My Account.It will display Above 
`Delete operation is forbidden for current area`.

**Comment by allamsettiramesh** [comment] 2017-05-27 18:44
I am also facing same issue, Can please provide solution for this issue

**Comment by veloraven** [comment] 2017-06-30 07:23
@Moinashraf if you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.

**Comment by magento-engcom-team** [comment] 2017-09-13 21:31
@Moinashraf we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Comment by ndlinh** [comment] 2018-08-14 09:49
This problem can be reproduced by using a proxy to modify input value (eg: burp suite) that make the address validation failed. Technically, the method `AccountManagement.createAccountWithPasswordHash(...)` has code like this:

```
try {
    foreach ($customerAddresses as $address) {
        if ($address->getId()) {
            $newAddress = clone $address;
            $newAddress->setId(null);
            $newAddress->setCustomerId($customer->getId());
            $this->addressRepository->save($newAddress);
        } else {
            $address->setCustomerId($customer->getId());
            $this->addressRepository->save($address);
        }
    }
    $this->customerRegistry->remove($customer->getId());
} catch (InputException $e) {
    $this->customerRepository->delete($customer);
    throw $e;
}
```

I has a plugin on `AbstractAddress.validate()` to add custom validation on address base on my customer requirements. When the validation return errors `InputException` will be throw then ` $this->customerRepository->delete($customer);` is called. This will cause error `Delete operation is forbidden for current area `.  Even through getting that error, customer account was created but address was not.

The workaround for this problem is avoid to add custom validation to `AbstractAddress.validate()` but I think it will better if we wrap the saving process of customer & address in to a transaction with commit & rollback.

**Comment by ihor-sviziev** [comment] 2023-05-25 06:47
Re-opening since we got answer

**Comment by engcom-November** [comment] 2023-09-06 06:27
Hello @Moinashraf,

As there is already an issue present https://github.com/magento/magento2/issues/31540, and that's been confirmed.
Hence we are closing the issue, feel free to open this issue if you need more assistance.

Thank you.

**Closed as completed by engcom-November** 2023-09-06 06:27 UTC
Labels: Triage: Dev.Experience, Issue: ready for confirmation, Reported on 2.4.x
