### ISSUE TITLE
Klarna payment not working in 2.4.2 as regionCode is missing in checkout.

### ISSUE THREAD

**Issue by JithinJay** [magento/magento2#33268] opened 2021-06-17 08:01 UTC
**Preconditions**
1 Magneto 2.4.2.
2 Fresh Magneto installed without any custom plugins.
3 Klarna modules installed  :
- klarna/m2-payments                                                8.2.1     
- klarna/module-core                                                  6.1.1      
- klarna/module-kp                                                     7.2.1    
- klarna/module-kp-graph-ql                                       0.9.1     
- klarna/module-onsitemessaging                              1.0.3     
- klarna/module-ordermanagement                            6.1.1     

** Summary **

![Screenshot from 2021-06-17 13-27-35](https://user-images.githubusercontent.com/53341290/122355815-d6620680-cf6f-11eb-9060-2312a415cdb0.png)

configure the Klarna payment module, with a store where a state field is required like US / AU. I replicated the issue in AU sotore. try to place an order with Klarna payment then you will get an error: **There has been an error with your address
Please check the following fields:
State** The reason for this issue is because the regionCode is undefined in the quote file path: vendor/klarna/module-kp/view/frontend/web/js/model/klarna.js .  There is similar issue in the checkout after upgrading to 2.4.2 like: https://magento.stackexchange.com/questions/325281/shipping-region-id-is-missing-in-checkout-after-upgrading-from-magento-2-3-4-to
I think it has something to do with Magento instead of the Klarna module.

**Steps to reproduce**

1. Configure the Klarna payment in a store with state field is required.
2. Try to make an order with the proper address and you must be able to replicate the issue.

Expected result

Order placed successfully.

Actual result

 Error in order placing.

**Comment by JithinJay** [comment] 2021-06-17 08:02
@magento give me 2.4-develop instance

**Comment by JithinJay** [comment] 2021-06-17 08:14
> Hi @JithinJay, here is your Magento Instance: https://91bd63be252ab5bd2a172ffeb47b9a76-2-4-develop.instances.magento-community.engineering
> Admin access: https://91bd63be252ab5bd2a172ffeb47b9a76-2-4-develop.instances.magento-community.engineering/admin_b646
> Login: 93ced648
> Password: 574404e0db8d
 
There is no klarna payment in this Instance so I was not able to replicet the issue there.

**Comment by engcom-Hotel** [comment] 2021-07-02 12:20
Hi @JithinJay,

We have tried to reproduce the issue in Magento 2.4.2-p1, but unable to reproduce this. We have tried below steps:

1. We generated the north America merchant account on Klarna.
2. Tried one checkout using:  Us, California, san Francisco, 94016. But we are not getting any error related with region code. Please find below screenshot for the reference, where regioncode is defined as "CA":

<img width="1440" alt="Screenshot 2021-07-02 at 3 55 23 PM" src="https://user-images.githubusercontent.com/51681618/124273484-b03a8a00-db5d-11eb-8f3d-d973d898f56a.png">

3. We might need information regarding the specific input [regioncode] and other given in shipping address to test it further.

Thanks

**Comment by engcom-Hotel** [comment] 2021-09-13 07:34
Dear @JithinJay,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2021-09-13 07:34 UTC
Labels: Component: Payment, Issue: needs update, Reported on 2.4.2
