### ISSUE TITLE
.gitignore inclusion in further versions (Request, Question)

### ISSUE THREAD

**Issue by bhargavmehta** [magento/magento2#2927] opened 2016-01-08 07:33 UTC
Can we add a default gitignore in develop branch so that it is easily trackable and easy to merge with current development by ignoring some static files like composer.lock.

Thank you

**Comment by davidalger** [comment] 2016-02-26 02:51
@bhargavmehta I think you are going to need to elaborate on what you are looking for here. I'm not sure what you're asking for. :) There is a .gitignore file in the root of the develop branch already, and there is also a default one created in your project directory when using composer create-project to setup a new build. composer.lock is not ignored though because it _should_ be committed.

**Comment by bhargavmehta** [comment] 2016-02-26 05:33
I saw the gitignore. But if I do composer update then my composer.lock will change and hence if we can ignore that it will help in updating the project from develop branch directly.

Thank you

**Comment by maksek** [comment] 2016-05-09 21:02
Please ask questions on forum. GitHub only for confirmed issues with steps to reproduce or PR.

**Closed as completed by maksek** 2016-05-09 21:02 UTC
