### ISSUE TITLE
Magento 2.3 : Customer after login Storeview switcher/redirect problem

### ISSUE THREAD

**Issue by sangeetajain** [magento/magento2#25136] opened 2019-10-18 06:33 UTC
### Summary (*)
Customer after login Storeview switcher/redirect problem

### Examples (*)
In my case if any customer is register from any store or store view. They are successfully register from any store/storeview. and successfully login from any store/storeview but after login from any store/storeview when user click on store/storeview switcher it's will not working. In admin setting I have done. Without login is working properly.

Add Store Code to Urls to Yes
Customer Share to "Global"
![front](https://user-images.githubusercontent.com/4272871/67071065-3b63c880-f19f-11e9-8bab-ee14662d6941.PNG)

After login Redirect
![wrong](https://user-images.githubusercontent.com/4272871/67071052-36067e00-f19f-11e9-9bf0-a19c91e658b6.PNG)

### Proposed solution
It will redirect to properly after login same as without login.

**Comment by Khushbu-Webkul-QA** [comment] 2019-10-18 14:17
As i have checked, this feature working fine

![Screenshot (61)](https://user-images.githubusercontent.com/45037885/67101891-22c7d280-f1e0-11e9-94fc-bb5da9437997.png)
![Screenshot (60)](https://user-images.githubusercontent.com/45037885/67101892-22c7d280-f1e0-11e9-96e3-b8933ff65a04.png)

issue not found

**Comment by engcom-Charlie** [comment] 2019-10-21 14:06
Hello @sangeetajain 
We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.

**Manual  testing scenario:**

1. Create customer
2. Go to the Stores->Configuration
3. Set Add Store Code to Urls to Yes
4. Set Customer Share to "Global"
5. Go to the frontend
6. Try to switch store or storeview with using switcher 

**Actual result:**
I can switch stores without any errors.

I have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-10-21 14:06 UTC
Labels: Issue: Format is valid
