### ISSUE TITLE
Updating a product through the API unchecks "Use Default Value" on a bunch of attributes

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#26484] opened 2020-01-22 05:26 UTC
When you update a product. For example adding an image using the API. Which is totally unrelated to anything else, such as editing price.

The checkbox "Use Default Value" becomes unchecked on a bunch of attributes, such as price.

This turns into a problem when you want to edit the product later, update the price, or the description etc. and nothing happens. So you have to change store view scope to that particular store, check the box "Use Default Value" and save to be able to change the price.

This should not happen in the first place.

### Preconditions (*)

1. Magento 2.3.3
2. 2 store views

### Steps to reproduce (*)

1. Create 2 store views
2. Add a new product with a price
3. Change store view on the product. You can see "Use Default Value" for price is checked.
4. Update the product using the API, for example uploading an image
5. View the product again and change store scope
6. Notice the "Use Default Value" on price is now unchecked (amongst other attributes)

### Expected result (*)

Checkbox "Use Default Value" should remain checked until a user actually unchecks it.

### Actual result (*)

Checkbox "Use Default Value" unchecks itself when you update the product using the API for all store views.

### Additional info 
I just re-produced it on 2.4-dev.

Seems to be a problem with scopes.

In addition to the steps above, do the following:

1. Stores > All Stores. Click "Main Website Store" and change "Default Store View" to the second store view

![image](https://user-images.githubusercontent.com/1741593/73576575-0b54e280-447b-11ea-863e-c8f466999a25.png)

2. Open "Default Store View" and change to status to disabled
3. Go into product, select scope "Default store view" (first store) Click "Use Default Value" on everything. Save.
4. Change store scope to second store view. Click "Use Default Value" on everything. Save.
5. Change scope to second store view again. A bunch of "Use Default Value" are unchecked.

![image](https://user-images.githubusercontent.com/1741593/73576115-0b081780-447a-11ea-8e07-3af9ec72d1f6.png)

**Comment by engcom-Bravo** [comment] 2020-01-23 14:37
Hello @Zyles,
Thank you for your report.
 
Unfortunately, we are not able to reproduce this issue. 
We tried to reproduce it via **Swagger API**, _catalogProductAttributeMediaGalleryManagementV1 POST
/V1/products/{sku}/media_
We are using the following body
```
{
  "entry": {
    
    "media_type": "image",
    "label": "string",
    "position": 0,
    "disabled": false,
    "types": [
      
    ],
    "file": "test.jpeg",
    "content": {
      "base64_encoded_data": "/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBw0NDQ0NDw0QDg0NDQ8NDQ4PDw8QEhAOGBEXFxURFRUYHCggGBomGxYVITEhJSkrLy4uFx8zODMsNzQtLisBCgoKDQ0ODg0NDisZHxkrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrK//AABEIAOEA4QMBIgACEQEDEQH/xAAcAAEAAwADAQEAAAAAAAAAAAAABQYHAQQIAwL/xABIEAACAgECAgUGBw0GBwAAAAAAAQIDBAUREiEGMUFRYQcTFCIycSNCVJGSk9EVFhdDUlZigYKUodLTJTNVcrHhJDVTosHi8P/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A2QABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHxyMqFe8W+Kzzc7Y1R2dk4Q24nGO/PnKK98kU78Kekd+T9R/wCwF3BXejvTXT9SulRjzsVsYOzhsr4OKKaT4eb3a3RYgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB+bbIwjKcpKMIRcpSb2UYpbtvw2P0Zz5X+kfmaI6dVLazISnkNdccfflD9pr5ovvApmp9Nrp6xHVKnLgpn5uml8k8RcnB+M05N9za7kc+UXR6q7q9Rxdng6nHz9bXJRua3nB92/tbf5l2FSfcXnoNkV5+JkaBkSS88pX6dOX4vIS4nFfxlsuzzneEU7StQtw8inKpe1tE1OG/U+xxfg02n4NnpDRdUqzsanKpe9d0FJLti+qUH4ppp+KPNeTj2VWTosjwW1TlXZF7Jxmns1v+rrL/5IOkaovlp1svgsqXFj7vlHI25x8FJL54rvA2IABQAAAAAAAAAAAAAAAAAAAAAAAAAAAVO/pP6XfqOnYNqrzsWvix7JKEoXWxfwlezTXJ7Rfvb7DN5eUjWotxlfCMotqUXj0pqS5NNbcnuBtepZsMai2+abjVBzcY+1J9kV4t7L9Z511izMzMm7Ktptdl03OXwc9orqUFy6kkkvBE7+EvWflEP3en7A/KbrXyiH1FP2BFTtx7ILedc4rdbOUJRXu3a6xjZE6bKrapOu2qashNdk090/9jROjnSuzWnfpOp2RlDNr4cW2NcIOrIjvKPUtt+Sa8Y7dpn2o4NmLfdj2x4babJVzj4p9a701zT7mgLl07or1DExtex4qKtUcfUK1+KyI+qpP9e0d+1Ot9pRoTlFxlGTjOLUoSi9nGSaakn3rrLb5OtXqrut07J9bB1OPmLU3soXNbQmu7f2d+/hfYQXSDR7NPzLsOzduqSSm1txwa3jYvBp/wCoG89CukC1PBqyHsro/BZMF8W6PW9uxNbSXhInTA/Jx0j+5udFWS2xcrhpyN3yg93wWv3NvfwkzfQrgAAAAAAAAAAAAAAAAAAAAAAAArXlA6Rfc3BnOEksm7enGXdNrnZt3RXP38K7SyyaSbb2SW7b5JLvPPfTvpC9Tz7LU36PUnTirsdaf95t3yfP3cK7AInStRtxMmnKrk/O02KxNv2vyoyfapJtPwbL30o6I3apOnVNMpU6c+pXW1uddbrv+M/WaXN9e3bGT7UU/otoc9SzacSO6Unx3TX4ule3P+KS8ZIl+nPSV3ZSow7Z04WDH0THjTZKCko8pT9VrdPbZeEU+1hH5/BxrfyNfX4/85+fwba38jX1+P8AzlflquXvv6XkfX2/acfdTL+VZH7xb/MBZK/J1rsJRnHF4ZwkpQksjHTjJPdNPi5NNE75S9ByLcPG1a6lU5kIQo1GtOEk+fDC1OLa235d+049xRsDIz8m6rHqyciV101XWvSLecn38+SXNt9yZaPKNqaorx9EptnbDDjGeZbKUpSuyWt9m29+W7lt3yS+KBRGjSLsO3pJpdGRVFT1XAksXITcYu+p84y4nst/je/zi7jOqqp2ThXXFzsnJQhBdcpt7KK8W9kXzphkrSMLG0TGtcb+WVqN1U3GTtezjXxLnt1fsxh3sCN/BvrfyNfX4/8AOa90Khnwwa6c+rzeRR8EpccJ+dqXsSbi3zS5Pfu37Tz+9Uy/lWS+5K65t+C5m/dB9GtwcGuF9k7Mq34XIc5ym4za5VptvlFbL37vtAnwAFAAAAAAAAAAAAAAAAAAAAOvqObVi0W5FsuGqmuVk3+il1LvfYl4gUjyudI/RsVYFcvh8yL87t1wxeqX0n6vuUjGFtz37v4nf17V7c/Luy7Pauk3GHWq6+qEF7lt/Fkv0A0OGZlu6/aODgw9Ky5y9lqPONb8Hs2/CMu9BEzH+w9F39nUtZj6vZOjD26+9PZ+/ea/JKAkl7l/oS/SzXZ6lm25Uk1Bvgx4P4lCfqR9/Nt+MmdvoJoEdQzNreWJjR9Iy5PlHzS6oN/pbfMpdwEppfk4uvwq867Npw67Iec2ug/Vrb9WUpcSS3TT/Wjh9A8T84NO+nD+od/C6dRv1i7z/wDyrNh6A6p8oQo5quxx7N3KXF4Tfcio9KdDnpubdiS3cYvjpm/xlDb4Je/k0/GLAvXR/QqdHo1DVKsujU8jFxmqY4/DJUuW6lOe0n2f9sZmYXWzsnOycnOc5Oc5y5uUm92347k90G1/7m5sbJ88W5eYy4tbp1P4zXbwvn7uJdp3Nc6F21avDT8fnXlyVuJZzlFYz3cm328CT3580o94Hb8n+JVh05OvZMd6sROvCg+Xncp+ruvduo7+Mn8Upubl2ZF1t9suO26bssl3yb57dy7EuxItvlE1Srjp0nF3WHpiVXJpqzI2anJ97Te2/e7O8qeFiW5N1VFUeO66arrjv8Zvbn3Lt37uYF18k3Rv0vL9Nsjvj4Uk4J9U8nbeK/Z9r38Bthj/AEi6QfcSzA0zBlxR02SuzXvt6RfKPrVy8HGcn27OUfyTWNOzasqirIqlxVXQjZB+DXU+5rqa70B2AAFAAAAAAAAAAAAAAAAAAAM78tM8lYWPGC/4SV//ABLW+/GlvVGX6O/E/eomiHU1bTqszHuxbVvXfBwl3rukvFPZrxQHmauuUpRjGLlKclGEY83KTeyivFvZF66W2R0nTaNErkvSL1HK1Oce1v2at+7eK/Zgvyj7dFej33LuztRz4/B6TKVdMdtvP5TS4JQ3601KO3jNdsWUfUs2zKvuybpcVt9jsm11bvsXglsl4JBHWS57Jp8+vfb/AFL9gc+i2UsP++WR/aqftuj9H9Dh4P1Kzt3KD/8AfxLD0H19admqdnPFyF6PlxfOLql8drt4Xz9zku0CuS/2NAlvruib+1qejx59sr8Pb529l89f6RXemmgfczOspXOiaV2LPrUqJPlHfta5xfuT7T4dFNcnpmbTlxTcE+C6C/GUSe0o+/kmvGKAiOLu3SaXbvuaV0L6e4lGFHHznZG/GjZRi5FVanZHHkl6qfxWnFL3Rj17Fc8oGhQw8tXY+zwc6HpOLOPspS2cq14LiTXhJFXQF4830S/62pPt5qLb9/qnb07Wej2mSty8L0u7NVM4Y6yYrgVkltxb7Lbxfc2u0z1/NsEB+7bZTnOyc3OycpTnOXXKbe8pPx3Zpfkc6R8E56ZZL1bHK3E37J9dla969ZeKl3mZde3LqW3L/wAn1xr50zhbXJwsrlGdc11xmmmpL5u0D1CCJ6K65DUsKnKjspSXDdBfEuXtR93avBolgoAAAAAAAAAAAAAAAAAAAAA62oadj5UFXkU131qSmoWwjOKkk0pbPt5v5yP+9LSf8NxP3er7CZAEN96Wk/4bifu9X2D70tJ/w3E/d6vsJkAVHygdFYZunKuitRuwo8eJCCS9VR2lQl2JxSSXfGJg3Lbfw36us9Tmd5nQimjWLNUmv7PqhLOlXFcUvS09/NqC5tb+vsut7RCIvOz6tG0nTcHNxK9RyZueV6NkOKji1y4tlu4y5pycdv8APz2SRCffpp35s4H04f0SE1/Jzc/LuzLMe9StnvGPmrPg4LlCC5di2973ZHegZHye76mz7ALX9+unfmzgfTh/ROfv10782cD6cP6JU/QMj5Pd9TZ9g9AyPk931Vn2AW1dNdO/NrB+nD+iH000782sH6cP6JUlgZHye76mz7CT6O9GsnOy6cbzVtcJy3ttlXJKFS5ylu1tvtyXi0BsXk7yYZGJPJr02nTqrrXwQpafnlFcLsltCO3PeK/y+4tR88XHhTXXVXFQrqhGuuC6owS2SX6j6BQAAAAAAAAAAAAAAAAAAAAAAAAAAAABzu+8bvvOABzu+8bvvOABzu+8bnAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//2Q==",
      "type": "image/jpeg",
      "name": "test.jpeg"
    }
    
  }
}
```
 The product is updated, image added. But when we switch between Store Views, the **Use Default value** checkboxes are still checked. We tried to reproduce with one Website and several, the result is the same, all checkboxes are checked. 
![usedefaultcheckboxes](https://user-images.githubusercontent.com/51680745/72993266-c63b0b80-3dfd-11ea-84a1-27d3f493f8d5.gif)

Can you please provide us with more info: the number of Websites and StoreViews, which API Client and query body you are using?

Thank you for your contribution.

**Comment by Zyles** [comment] 2020-01-23 15:17
Where is the text swatch?

Look at the other store views.

**Comment by Zyles** [comment] 2020-01-23 15:19
Oh sorry another issue.

See if the effect happens if you do this: https://github.com/magento/magento2/issues/26481

Could be related to the text swatch that unchecks the boxes.

I also found this: https://community.magento.com/t5/Magento-2-x-Technical-Issues/quot-Use-Default-Values-quot-Checkbox-Unchecked-While-Update/td-p/137217

So can be related to `$Product->save();` and swatches. I assume that call is being made when you update something with the API.

**Comment by engcom-Bravo** [comment] 2020-01-24 12:30
Hello @Zyles 

Thank you for your quick response. Can you please clarify what do you mean by "_See if the effect happens if you do this: #26481"_ ?
The issue #26481 is already **Confirmed** and is **Ready for Work**

Thank you

**Comment by Zyles** [comment] 2020-01-24 14:20
That issue does not mention the "unchecking of use default value" problem.

But it MAY be related to text swatch.

Please confirm by testing with a text swatch with a default value on the product.

**Comment by engcom-Bravo** [comment] 2020-01-27 10:15
Hello @Zyles 

We have tested Updating the product with **Text Swatch** attribute through the API. 
We have rechecked with a default _value1_, for example,
![swatch_2](https://user-images.githubusercontent.com/51680745/73165101-d273e100-40fb-11ea-8750-c46360a5491e.png)
and with default _empty_ value.
![swatch_1](https://user-images.githubusercontent.com/51680745/73164549-d2bfac80-40fa-11ea-9170-986d899f1fa2.png)


Rechecked with two API requests:
- _catalogProductRepositoryV1 PUT /V1/products/{sku}_
- _catalogProductAttributeMediaGalleryManagementV1 POST
/V1/products/{sku}/media_
 
The _Use Default Value_  checkboxes **do not** become unchecked on all Store Views 

This issue is not reproducible on Magento 2.4-develop, so we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest 2.4-develop branch. 

Thank you for collaboration.

**Comment by Zyles** [comment] 2020-01-31 21:43
I just re-produced it on 2.4-dev.

Seems to be a problem with scopes.

In addition to the steps above, do the following:

1. Stores > All Stores. Click "Main Website Store" and change "Default Store View" to the second store view

![image](https://user-images.githubusercontent.com/1741593/73576575-0b54e280-447b-11ea-863e-c8f466999a25.png)


2. Open "Default Store View" and change to status to disabled
3. Go into product, select scope "Default store view" (first store) Click "Use Default Value" on everything. Save.
4. Change store scope to second store view. Click "Use Default Value" on everything. Save.
5. Change scope to second store view again. A bunch of "Use Default Value" are unchecked.


![image](https://user-images.githubusercontent.com/1741593/73576115-0b081780-447a-11ea-8e07-3af9ec72d1f6.png)

Please confirm.

**Comment by Zyles** [comment] 2020-02-04 12:57
Please re-open this issue.

**Comment by blacktek** [comment] 2020-02-04 19:06
I've the same issue on 2.3.3; after creating a product it's enough to send the empty payload {"product":{}} in PUT to /en/index.php/rest/<shop_code>/V1/products/<sku> in order to uncheck all the "Use Default Value" attributes having scope "website"

could you please double check?

**Comment by magento-engcom-team** [comment] 2020-02-05 07:30
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31118` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Zyles** [comment] 2020-02-05 19:36
This has caused massive problems for us.

When we update our product prices using the API, every single product has unchecked the "Use default" values.

So that means everytime we edit a product, disable it etc. We have to do it on multiple storefronts because the values are no longer shared.

**Comment by hostep** [comment] 2020-02-05 19:42
This is a duplicate of https://github.com/magento/magento2/issues/9186 btw
The official response from the Magento Enterprise support can be found [here](https://github.com/magento/magento2/issues/9186) (more then 6 months have passed since then, it looks like nothing happened, yay!)

**Comment by Zyles** [comment] 2020-02-06 02:23
Good to see they are working on a 3 year old bug that affects thousands of store... Oh wait.

**Comment by blacktek** [comment] 2020-02-06 09:41
indeed it's very strange; it's a very severe bug leading to data corruption. At the moment we're stuck with a quite big project due to this bug

**Comment by leeroybrun** [comment] 2020-04-02 19:20
Has anyone found a good solution/workaround?

I may have found something, which should be temporary until it's fixed (well let's be honest, might as well be a permanent "dirty fix" given the speed at which they are trying to fix this bug).

Wanted to share it because this bug is kind of a nightmare and it feels like I might not be the only one...

Have not tried it yet, but it's explained on the main issue here if you are interested: https://github.com/magento/magento2/issues/9186#issuecomment-608047932

**Comment by blacktek** [comment] 2020-04-03 14:05
no good solution. On my side I'm sending at every request to update a storeview the base settings of the website too. Quick and (very) dirty, but far from optimal

**Comment by raindropsinfotech** [comment] 2020-07-27 05:52
just onep this file 
/public_html/vendor/magento/module-ui/view/base/web/js/form/form.js

search 
 _.each(additional, function (value, name) {
                source.set('data.' + name, value);
            });
add code after that 


// HACK for product - use default value...
                if($('input[name="product[name]"]').length){
                    console.log("admin edit ");
                    // source.set('data.use_default[name]', 1);
                    $(".admin__field-service").each(function(i, v){
                        if($(this).find("input").attr("type") == "checkbox"){
                            var name = $(this).find("input").attr("name");
                            var checked = $(this).find("input").prop("checked");
                            var value = 0;
                            if(checked){
                                value = 1;
                            }
                            source.set('data.'+name, value);
                        }
                    });
                }
            // HACK for product - use default value...

**Comment by Zyles** [comment] 2020-07-27 07:11
That solves nothing.

**Comment by eddyszucs** [comment] 2020-08-07 05:53
I've just had this issue. 
I am creating or updating a product with "rest/all/V1/products/", everything fine until than but after that i have to make some store specific changes for a product with "rest/<shop_code>/V1/products/sku" like price or name, the product images "loose" their roles for that store.

**Comment by stanleyyuenyiu** [comment] 2020-09-15 02:16
i have the same issue but with category api, as i havent test the product api yet

i use admin token, i have 3 store view, which is en, tc,sc

i call below request

PUT https://{my domain}/rest/{my store view code}/V1/categories/10

with this body

`{
    "category": {
        "name": "Eng name"
    }
}`


Result: include in menu, enable category, url key will uncheck usedefault

**Comment by domi-nique** [comment] 2020-11-25 11:07
We have exactly the same problem at the moment - but we are not using the API, we used the Import functionality and now... all our products are a huge mess and when saving a field in a store view, sometimes all the translations are kicked out without noticing. 
This bug is not Low Priority... This should be critical. Multistore Setup with Magento 2 is impossible with this bug.

**Comment by lbajsarowicz** [comment] 2020-11-25 13:37
@domi-nique I tried to resolve the issue several times, but significant resources are necessary to solve it. If it is critical for you - you can assign your resources to resolve it - at least partially.

**Comment by Vishrootways** [comment] 2020-12-30 13:28
Try below POST URL, it should solve the issue of unchecks "Use Default Value"

rest/all/V1/products/{sku}

**Comment by Zyles** [comment] 2020-12-30 21:22
> Try below POST URL, it should solve the issue of unchecks "Use Default Value"
> 
> rest/all/V1/products/{sku}

How do you upload an image to this endpoint?

**Comment by blacktek** [comment] 2020-12-30 21:32
> Try below POST URL, it should solve the issue of unchecks "Use Default Value"
> 
> rest/all/V1/products/{sku}

POST is supposed to only create products, not update them.

If you look at my previous post:

> I've the same issue on 2.3.3 (and 2.3.5 now); after creating a product it's enough to send the empty payload {"product":{}} in PUT to /en/index.php/rest/<shop_code>/V1/products/ in order to uncheck all the "Use Default Value" attributes having scope "website"

this is my (easy) way to reproduce the problem

**Comment by Vishrootways** [comment] 2020-12-31 04:00
@blacktek It's a typo, I tried with PUT using the below endpoint and the product has been updated.
rest/all/V1/products/{sku}

@Zyles Still I didn't test the above endpoint with images

**Comment by hostep** [comment] 2021-01-21 07:14
This might have been finally fixed: https://github.com/magento/magento2/issues/31083#issuecomment-763905573 (not tested myself)

**Comment by engcom-Golf** [comment] 2021-01-28 12:49
Can not reproduce on 2.4-develop. This issue has been fixed in #31083.
Will close this one.

**Closed as completed by engcom-Golf** 2021-01-28 12:49 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Api, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P2, Severity: S2, Progress: done, CD, Reported on 2.3.3

**Comment by magento-engcom-team** [comment] 2021-01-28 12:52
Hi @Zyles, @engcom-Golf. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-31118` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by ssstankiewicz** [comment] 2022-11-04 14:51
@magento-engcom-team It occurs again in Magento 2.4.5. Adding new image via API to product cause uncheck checkboxes for 'Use default value'

Product before request:
![24-MB01_before_request](https://user-images.githubusercontent.com/25231802/200004056-b96f2705-b57d-49f0-b853-44d59f343bb4.png)

Product after request:
![24-MB01_after_request](https://user-images.githubusercontent.com/25231802/200004124-be6c1e34-d704-404e-8b0f-a52eb5dd3d35.png)

Request endpoint: /rest/en/V1/products/24-MB01/media
Request body: 
[24-MB01_request.odt](https://github.com/magento/magento2/files/9939438/24-MB01_request.odt)

**Comment by blacktek** [comment] 2023-01-09 07:36
what is the status for this issue that happens again on 2.4.5?

**Comment by blacktek** [comment] 2023-01-19 12:04
@thomas-kl1 do you think we can use your fix in production, despite it didn't pass all tests? we urge to migrate from 2.4.3 to 2.4.5 because we're on php7.4 that is end of life. Thank you

**Comment by thomas-kl1** [comment] 2023-01-19 14:14
Hi @blacktek

The fix helps with the loss of data when using the Magento webapi. I'm not sure we can rely on the tests as many of them are dumb tests that check the implementation instead of the expected result.
So you can use it at your own risk.
Regarding the issue of "default value checkboxes", I don't think it's actually solved, but it's not a blocking issue (just think to update the product for each scopes).
Magento suffer a lot of its implementation of scopable EAV.
