### ISSUE TITLE
Credit Memo Adjustment fee tax isn't calculated

### ISSUE THREAD

**Issue by violuke** [magento/magento2#12494] opened 2017-11-30 10:21 UTC
Duplicate of #7937 which was wrongly closed before but is an serious bug from an accounting perspective. All details on that issue.

## Preconditions
Magento 2.1.2 - 2.1.10 (I believe 2.2.1 too but not tested)

## Steps to reproduce
Create a credit memo and add an adjustment refund / fee

## Expected result
Tax is recalculated

## Actual result
No difference in tax

**Comment by magento-engcom-team** [comment] 2017-11-30 11:16
@violuke , thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by violuke** [comment] 2017-11-30 11:18
Thanks for the reply, but I don't see how any further information is needed. See #7937, it's all explained there. Thanks.

**Comment by magento-engcom-team** [comment] 2017-11-30 11:21
@violuke Thanks for the feedback. Please provide preconditions and steps to reproduce here, even if they duplicate ones from previous issue.

**Comment by violuke** [comment] 2017-11-30 11:22
Ok, I've updated the original message above. Thanks.

**Comment by magento-engcom-team** [comment] 2017-11-30 11:30
@violuke, thank you for your report.
We've created internal ticket(s) MAGETWO-84801 to track progress on the issue.

**Comment by Echron** [comment] 2019-01-16 11:54
Is there any progress on this issue? @violuke How did you deal with this issue?

**Comment by ACassiusD** [comment] 2019-04-02 19:53
Any progress on this?

**Comment by LindenFR** [comment] 2019-06-03 10:05
Any news or updates on this please ?

**Comment by sdzhepa** [comment] 2019-12-10 00:40
Duplicate of #23938

**Closed as completed by sdzhepa** 2019-12-10 00:40 UTC
Labels: Issue: Clear Description, Issue: Format is valid
