### ISSUE TITLE
Shipping Address is not updated on Checkout Shipping page when no Shipping Method is available

### ISSUE THREAD

**Issue by mcspronko** [magento/magento2#5181] opened 2016-06-23 11:04 UTC
## Steps to reproduce
1. Navigate to Admin -> Stores -> Configuration -> Sales -> Shipping Method
2. Open any available shipping method tab (Flat Rate or Free Shipping or Table Rates)
3. Set Enabled = Yes
4. Set "Ship to Applicable Countries" = "Specific Countries"
5. Select "United States" country.
6. Save configuration
7. Navigate to Frontend
8. Add any Simple or Configurable product to a shopping cart
9. Click "Proceed to Checkout" button from mini shopping cart
10. Fill all required fields in the shipping form
11. Select any other country which is not configured in step 5
12. Click "Next" button
13. Observe the results.
## Expected result
1. When a customer changes Country/Region input values the Shipping Methods section should be updated.
## Actual result
1. Error shows to a customer - Carrier with such method not found...
2. When customer changes Country to United States, Shipping Methods section is not updated.
## Observations

Currently, only in case customer clicks "Next" button shipping address from form is updated for Quote object. It is expected to update Quote object even there is no "Next" button (case where no shipping methods are available).
## Versions

All Magento 2.x versions.

**Comment by andimov** [comment] 2016-06-23 11:09
@mcspronko
Thank you for reporting this issue.
Please provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by mcspronko** [comment] 2016-06-23 11:15
Hi @andimov ,

Magento 2.x all versions, all branches.

Hope it helps.

**Comment by andimov** [comment] 2016-06-23 14:41
@mcspronko, thanks!

**Comment by veloraven** [comment] 2016-07-04 12:34
Hi @mcspronko !
Could you please confirm that issue is still present for ver. 2.1.0? 
As I was not able to reproduce it. 
As soon as I change country, the Next button disappears as well as shipping method itself. 
And if some other shipping method is enabled, I can finish order using it.

**Comment by leechilli** [comment] 2016-07-04 12:45
Hi, Thank you for your email.

I'm currently out of the office until Monday 11th July. Where I'll be able to pick up your email on my return.

If you have any urgent support requests please contact the office on 02392822377

**Comment by leechilli** [comment] 2016-07-11 08:51
Hi @veloraven 
Can confirm this is an issue still present for ver 2.1.0.
Using only table rate shipping.

If required to help yourselves debug the issue, I'm happy to provide files being used for the magento 2 site

**Comment by sumisudish** [comment] 2016-09-25 13:06
Hi, Is there any fix available for this bug ? or is there any quick way to force triggering the shipping quote by a button ?

**Comment by SerhiyShkolyarenko** [comment] 2016-10-12 10:24
@mcspronko I didn't reproduce the issue on v2.0.9.
I don't have 'Next' button on step 12.

**Comment by SerhiyShkolyarenko** [comment] 2016-10-12 13:14
the same result on the latest develop branch.
@mcspronko please confirm if it is reproducible for you.

**Comment by SerhiyShkolyarenko** [comment] 2016-10-26 14:23
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by SerhiyShkolyarenko** 2016-10-26 14:23 UTC
Labels: bug report, Progress: needs update, Component: Checkout
