### ISSUE TITLE
Checkout error message "The order wasn't placed. First, agree to terms and conditions, then try placing your oder again."

### ISSUE THREAD

**Issue by chequille** [magento/magento2#31461] opened 2020-12-25 10:53 UTC
### Preconditions (*)

1. Magento 2.4.1

### Steps to reproduce (*)

1. You must have at least one terms and conditions configured
2. Add a product to the cart
3. Go to checkout
4. Go to second step (payments)
5. Before selecting a pament method, open coupon code to be aible to enter a coupon code
6. Than select a pament method.
7. As soon as you selected the payment method, the error message is shown.

### Expected result (*)

1. Not showing this message, because there is no reason for it at that point.

### Actual result (*)

1. When coupon code is open and you select a pament method, the error message is shown.
2. Absolutely not right to show it.
3. 
![grafik](https://user-images.githubusercontent.com/15807794/103132938-bc71f600-46a7-11eb-9c39-70ef6899984d.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment] 2020-12-25 11:52
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment] 2020-12-25 12:33
Hi @chequille,
I have verified this issue as per the Preconditions, Steps to reproduce, Actual result, and Expected result.
Terms & Conditions warning error message showing on the Coupon code section.

**See attached the screenshot:** 
![image](https://user-images.githubusercontent.com/24711761/103135014-44bdbe80-46db-11eb-8bb7-05801d4a736a.png)

Thanks.

**Comment by magento-engcom-team** [comment] 2020-12-25 12:34
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40237` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by chequille** [comment] 2021-01-12 14:12
Hi Guys,
any news on that?
Why is this only on Low Priority Backlog ?
Prevents me from going online with 2.4.1 !!

ANy news would be very much appriciated.

Best regards,
Chequille

**Comment by mdevrees** [comment] 2021-01-20 12:50
I've started debugging a little bit on this issue, and it looks like there's a `before` plugin in `vendor/magento/module-checkout-agreements/Model/Checkout/Plugin/Validation.php`:
```
public function beforeSavePaymentInformation(
        \Magento\Checkout\Api\PaymentInformationManagementInterface $subject,
        $cartId,
        \Magento\Quote\Api\Data\PaymentInterface $paymentMethod,
        \Magento\Quote\Api\Data\AddressInterface $billingAddress = null
    ) {
        $quote = $this->quoteRepository->getActive($cartId);
        if ($this->isAgreementEnabled() && !$quote->getIsMultiShipping()) {
            $this->validateAgreements($paymentMethod);
        }
    }
```
This method is going to validate the agreements:
```
protected function validateAgreements(\Magento\Quote\Api\Data\PaymentInterface $paymentMethod)
    {
        $agreements = $paymentMethod->getExtensionAttributes() === null
            ? []
            : $paymentMethod->getExtensionAttributes()->getAgreementIds();

        if (!$this->agreementsValidator->isValid($agreements)) {
            throw new \Magento\Framework\Exception\CouldNotSaveException(
                __(
                    "The order wasn't placed. "
                    . "First, agree to the terms and conditions, then try placing your order again."
                )
            );
        }
    }
```
and in the request that is being sent, there are no extension_attributes with agreement IDs, as the request looks like the following example:
```
{"cartId":"41","paymentMethod":{"method":"checkmo"}}
```
Now I've checked around a bit and came across [this stackexchange](https://magento.stackexchange.com/questions/309981/how-do-you-accept-terms-and-conditions-via-api) issue which basically says "To resolve this you need to pass agreement_ids in payment method to place order:" which will conclude in the following request, if you have a single term & condition enabled:
```{"cartId":"41","paymentMethod":{"method":"checkmo"}}, "extension_attributes": {"agreement_ids": ["1"]}}```

Either that, or the validateAgreements method should not be executed in the `beforeSavePaymentInformation` method (I can understand you want to validate terms & conditions for `beforeSavePaymentInformationAndPlaceOrder` but why also for savepayment only?)

**Comment by chequille** [comment] 2021-01-21 06:26
Hi,
in my point of view there is no need for the beforeSavePaymentMethod. It was not there in Version 2.3.5,
As well, for quest checkout this method is not in the code, so why for logged in users?
Hope you will change this soon.

**Comment by dhairya-shah** [comment] 2021-01-30 05:55
@magento I am working on it

**Comment by dhairya-shah** [comment] 2021-01-30 05:56
@magento add to contributors team

**Comment by dhairya-shah** [comment] 2021-01-30 05:57
@magento I am working on it

**Comment by mrlerch** [comment] 2021-04-16 14:01
Any update on this? it seems weird to get this message on page load, and not when you are trying to process an order without checking the box. Please advise.

**Comment by paugnu** [comment] 2021-07-14 08:42
Hi,

To avoid this problem (until it's fixed), you can create a preference and empty the method which is causing the issue:

```php
<preference for="Magento\CheckoutAgreements\Model\Checkout\Plugin\Validation" type="Vendor\Module\Model\Checkout\Plugin\Validation" />
```

```php
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

namespace Vendor\Module\Model\Checkout\Plugin;

use Magento\CheckoutAgreements\Model\AgreementsProvider;
use Magento\CheckoutAgreements\Model\Api\SearchCriteria\ActiveStoreAgreementsFilter;
use Magento\Quote\Api\CartRepositoryInterface;
use Magento\Store\Model\ScopeInterface;

/**
 * Class Validation validates the agreement based on the payment method
 */
class Validation extends \Magento\CheckoutAgreements\Model\Checkout\Plugin\Validation
{
    /**
     * Check validation before saving the payment information
     *
     * @param \Magento\Checkout\Api\PaymentInformationManagementInterface $subject
     * @param int $cartId
     * @param \Magento\Quote\Api\Data\PaymentInterface $paymentMethod
     * @param \Magento\Quote\Api\Data\AddressInterface|null $billingAddress
     * @return void
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     * @throws \Magento\Framework\Exception\NoSuchEntityException
     * @throws \Magento\Framework\Exception\CouldNotSaveException
     */
    public function beforeSavePaymentInformation(
        \Magento\Checkout\Api\PaymentInformationManagementInterface $subject,
        $cartId,
        \Magento\Quote\Api\Data\PaymentInterface $paymentMethod,
        \Magento\Quote\Api\Data\AddressInterface $billingAddress = null
    ) {
        // Do nothing to avoid error.
    }
}

```

**Comment by kweij** [comment] 2021-07-29 07:41
I run into a similar issue where we also get a backend validation error message shown in the couponcode form. In my case this is a *justified* validation error (when a payment method field blank), but the placement of this message is _just as issue_ in the couponcode form.

I see that the pull request for this issue is resolving the unjustified validation error for the checkout agreements, but it's not resolving the incorrect placement of the error message (yet). I'd be glad a resolution or workaround for that aspect of this issue as well.

Magento version: 2.4.2-p1

**Comment by bertterheide** [comment] 2021-08-10 11:52
I looked into this issue today, and I found out that the SalesRule module adds the mixin `Magento_SalesRule/js/action/select-payment-method-mixin` to `Magento_Checkout/js/action/select-payment-method`, and then calls the `Magento_Checkout/js/action/set-payment-information-extended` component using the wrong `Magento_SalesRule/js/model/payment/discount-messages` message container. This component is normally called from the payment component using a message container that is built in place. 

Could you please look into this?

**Comment by kweij** [comment] 2021-08-10 12:19
@bertterheide seems spot on the cause of the misplacement of the checkout billing validation message.

**Comment by Morgy93** [comment] 2021-08-10 21:50
This seems to be fixed with today released 2.4.3 if you check release notes: 

>Magento now displays the Terms and Conditions validation message in the relevant block only when a shopper clicks the Place Order button. Previously, Magento displayed this message in the Apply Discount Code block whenever a shopper changed payment method in the checkout workflow: `The order wasn't placed. First, agree to the terms and conditions, then try placing your order again`.
https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-3.html#cart-and-checkout

**Comment by bertterheide** [comment] 2021-08-11 07:36
I think I found the relevant commit: https://github.com/magento/magento2/commit/9cc436f1723c643e676ec73d9bd2c6f97424806e#diff-6945d6c5613728418ab6761e7105838484fb91fb5c60dd019b76f392d4f5ba6e. This seems to only fix an issue where this error was thrown on saving the payment information, where it is now thrown when placing the order. I cannot find a fix for the placement of the error message. This still requires the fix that I suggested in https://github.com/magento/magento2/issues/31461#issuecomment-895964729.

**Comment by rykiplov** [comment] 2021-08-20 09:31
Any updates on this error message placement? 
@bertterheide instead of disabling mixin you can also try to change message container inside mixin. In your `select-payment-method-mixin` in `define` section change:

`'Magento_SalesRule/js/model/payment/discount-messages' `

to

`'Magento_Ui/js/model/messages',`

and then pass it as observable variable, so whole file will looks like this:

`define([
    'jquery',
    'mage/utils/wrapper',
    'Magento_Checkout/js/model/quote',
    'Magento_Ui/js/model/messages', // - CHANGE #1 
    'Magento_Checkout/js/action/set-payment-information-extended',
    'Magento_Checkout/js/action/get-totals',
    'Magento_SalesRule/js/model/coupon'
], function ($, wrapper, quote, messageContainer, setPaymentInformationExtended, getTotalsAction, coupon) {
    'use strict';

    return function (selectPaymentMethodAction) {

        return wrapper.wrap(selectPaymentMethodAction, function (originalSelectPaymentMethodAction, paymentMethod) {

            originalSelectPaymentMethodAction(paymentMethod);

            if (paymentMethod === null) {
                return;
            }

            $.when(
                setPaymentInformationExtended(
                    messageContainer(), // CHANGE #2
                    {
                        method: paymentMethod.method
                    },
                    true
                )
            ).done(
                function () {
                    var deferred = $.Deferred(),

                        /**
                         * Update coupon form.
                         */
                        updateCouponCallback = function () {
                            if (quote.totals() && !quote.totals()['coupon_code']) {
                                coupon.setCouponCode('');
                                coupon.setIsApplied(false);
                            }
                        };

                    getTotalsAction([], deferred);
                    $.when(deferred).done(updateCouponCallback);
                }
            );
        });
    };
});`

After that it seems to be working fine and error placement is fixed

**Comment by engcom-Bravo** [comment] 2024-06-05 04:28
Hi @chequille,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**


- You must have at least one terms and conditions configured
- Add a product to the cart
- Go to checkout
- Go to second step (payments)
- Before selecting a pament method, open coupon code to be aible to enter a coupon code
- Than select a pament method.
- As soon as you selected the payment method, the error message is shown.


<img width="946" alt="Screenshot 2024-06-05 at 09 54 08" src="https://github.com/magento/magento2/assets/51680745/755c1e25-ba2d-413f-865b-f3d49b638348">



There is no error message after selecting payment method.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-05 04:28 UTC
Labels: Component: Checkout, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Progress: done, Issue: ready for confirmation
