### ISSUE TITLE
Rest API for place order taking much time.

### ISSUE THREAD

**Issue by devqualwebs** [magento/magento2#22462] opened 2019-04-23 06:22 UTC
### Preconditions (*)

1. Created a custom one page checkout.
2. Placing order for guest users using Rest API Magento 2
3. Magento -v 2.1.3
4. php -v 7.0.4
5. Apache 2.4
6. MySQL 5.7, AWS RDS 16G RAM, 4 core CPU with 1000 IOPS
7. AWS EC2 Ubuntu 16.4 4G RAM 4 core CPU 100G SSD
8. Redis for session and cache
9. Opcache enabled

### Steps to reproduce (*)

1. Placing an order using Cash  On Delivery Method.

### Expected result (*)

1. Since all the optimizations and cache are already done. The Rest API time should be less.

### Actual result (*)

1. Place order API taking too much time around 30 sec. to complete. On the other hand, I'm using one more server having the same configurations, But the Place Order API responding less than 3 seconds on that server.

Can you please help me out to figure out the solution.

**Comment by orlangur** [comment] 2019-04-23 07:56
@devqualwebs you should perform a profiling on your side to find a root cause.

**Comment by engcom-Charlie** [comment] 2019-08-16 08:25
Hello @devqualwebs 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.

We are closing this issue due to branch 2.2-develop was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.
See Accepted pull requests and ported code for more details

If you still faced this issue on 2.3 please create a new Issue with all required details according to Issue reporting guidelines

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-08-16 08:25 UTC
Labels: Issue: Clear Description, Issue: Format is valid, Component: Api
