### ISSUE TITLE
processing shipments

### ISSUE THREAD

**Issue by t-marci5** [magento/magento2#33461] opened 2021-07-12 13:05 UTC
### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment] 2021-07-12 13:23
Hi @t-marci5. In the current stage, it is not clear what the problem and what functionality is broken.
Steps to reproduce, actual and expected result, screens that illustrate problem will help a lot.
Without such details, this issue could be closed as cannot reproduce

**Comment by krishprakash** [comment] 2021-07-13 04:24
Hi @t-marci5. Feel free to reopen once you update the issue description as per [issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
Thanks

**Closed as completed by krishprakash** 2021-07-13 04:24 UTC
Labels: Triage: Dev.Experience, Issue: needs update
