### ISSUE TITLE
Contact US page weird problem of map not showing

### ISSUE THREAD

**Issue by gcampedelli** [magento/magento2#10345] opened 2017-07-27 04:35 UTC
I have a screeshoot of the page. But I tried to edit Contact Us block and display the map for my region. Instead, I've got magento 2 columns page showing in the iframe. I like it better, but I would like to know how did I achieve this. The issue is more bizarre when we notice I have breadcrumbs in the iframe for home > Contact Us and I couldn't achieve those breadcrumbs in regular page. But in iframe they look really nice. 

Steps to reproduce. Go to block Contact US. Edit Google maps and set it for your region. 

If you can or cannot reproduce the issue, please, let me know!

![404-magento](https://user-images.githubusercontent.com/7084395/28654583-d3acb904-726b-11e7-820a-6ac69136269a.png)

**Comment by Shade634** [comment] 2017-07-27 08:07
Well to reproduce the issue, it would be nice to know if its a 3rd party template you are using, or a magento theme?

**Comment by gcampedelli** [comment] 2017-07-27 13:22
I'm using a 3rd part template and I have Contact Us enabled. It was not sending emails. It is still not sending emails. Else, I edited the block to add another form, because I wanted it to display in a pop up and pop up wasn't showing form. If you add manually, pop up shows form. I have a phtml which call the pop up modal and when I went to edit Google maps, I got this. I also tried to add breadcrumbs and so on without a change

**Comment by Shade634** [comment] 2017-07-27 13:37
I already had that feeling, then you should file this issue with them, since we wont be able to reproduce the issue at first, second, its not a bug in pure Magento2. ;)

**Comment by gcampedelli** [comment] 2017-07-27 14:03
Well, that's very weird. I have 2 Google Maps codes. The first reproduces my Ipad view of Magento store, which is very useful if you want to test your design, the second returns the map. Both codes are bellow. The secret is a iframe inside a iframe. It is how I did it. But not sending emails on contact form remains. 

For the Ipad view - <div class="contact-us" style="width: 50%; float: left;"><iframe style="border: 0;" src="<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d237786.50185914087!2d-46.66529102331447!3d-21.373593944559033!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94b63fd66d6e7b61%3A0xdabcd80eedb2da0e!2sMuzambinho+-+MG!5e0!3m2!1spt-BR!2sbr!4v1501129630893" width="600" height="450" frameborder="0" style="border:0"</iframe></div>

For the map

<div class="ggoo" style="width: 50%; float: left;"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d237785.98253531693!2d-46.66529077962294!3d-21.373913679086286!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94b63fd66d6e7b61%3A0xdabcd80eedb2da0e!2sMuzambinho+-+MG!5e0!3m2!1spt-BR!2sbr!4v1501162820931" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe></div>

**Comment by korostii** [comment] 2017-07-28 06:46
Hi @gcampedelli 
Please keep in mind that this is not a help desk.
If you are looking for some help or an advice regarding setup or customization, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") of Magento CE itself only.

**Comment by magento-engcom-team** [comment] 2017-09-21 07:36
Hi @gcampedelli 
We are closing this issue for now, as it seems that issue relates to the custom theme or modules. If you manage to reproduce the issue with clean installation – please reopen the issue and provide clear steps to reproduce. 
Thank you.

**Closed as completed by magento-engcom-team** 2017-09-21 07:36 UTC
Labels: Issue: Format is not valid
