### ISSUE TITLE
Not Able to set Rest API oAuth admin token expire in minutes or seconds.

### ISSUE THREAD

**Issue by sangeetajain** [magento/magento2#24716] opened 2019-09-25 06:21 UTC
### Summary (*)
Not Able to set Rest API oAuth token expire in minutes or seconds in admin. Currently it's showing hours and it will not accept like 0.5(for 30 minute etc) 
### Preconditions (*)
1. Magento 2.3-develop

### Steps to reproduce (*)

1. Login to Admin
2. Go to the Stores-->Configuration-->Services-->OAuth
3. Change values in Customer Token Lifetime (hours) & in Admin Token Lifetime (hours) to '0.5'
 ![image](https://user-images.githubusercontent.com/51680850/65674090-ad3f6b00-e054-11e9-829d-a31728c45f47.png)
4. Get the admin token (POST `<yourlocal>/rest/V1/integration/admin/token`)
 ![image](https://user-images.githubusercontent.com/51680850/65684590-a7ec1b80-e068-11e9-937e-cf1d425cf46b.png)
5. Notice the time when you sent the request
 ![image](https://user-images.githubusercontent.com/51680850/65684887-60b25a80-e069-11e9-9785-1d6d63e53677.png)
6. Wait 30+ minutes
7. Send any request with admin token ( GET `<yourlocal>/rest/V1/products/<sku>` in my case)
 

### Expected result (*)
1. We get an error
![image](https://user-images.githubusercontent.com/51680850/65685409-93108780-e06a-11e9-86c6-9b9f8f69c91d.png)

### Actual result (*)
200 OK
![image](https://user-images.githubusercontent.com/51680850/65685669-3366ac00-e06b-11e9-9a3d-218d9018d464.png)

**Comment by engcom-Charlie** [comment] 2019-09-26 09:01
Hello @sangeetajain 
I can't reproduce this issue on a fresh Magento 2.3-develop.

**Manual testing scenario:**

1. Login to Admin
2. Go to the Stores-->Configuration-->Services-->OAuth
3. Change values in **Customer Token Lifetime (hours)** & in **Admin Token Lifetime (hours)** to '0.5'

**Actual result:**
Configuration is saved
![image](https://user-images.githubusercontent.com/51680850/65674090-ad3f6b00-e054-11e9-829d-a31728c45f47.png)

So i have to close this issue. If you have some updates left a comment please.
Thanks for your report!

**Comment by sangeetajain** [comment] 2019-09-26 09:09
0.5 is save but it will not work on practically. Like if we set 0.5 means token will expire after 30 minute by logic but in Magento 2.3 it's not happen.
If we put 0.5 that means it will check $hour > 0 then it will set 0 hour which is never expire toke.

**Comment by sangeetajain** [comment] 2019-09-26 09:10
> Hello @sangeetajain
> I can't reproduce this issue on a fresh Magento 2.3-develop.
> 
> **Manual testing scenario:**
> 
> 1. Login to Admin
> 2. Go to the Stores-->Configuration-->Services-->OAuth
> 3. Change values in **Customer Token Lifetime (hours)** & in **Admin Token Lifetime (hours)** to '0.5'
> 
> **Actual result:**
> Configuration is saved
> ![image](https://user-images.githubusercontent.com/51680850/65674090-ad3f6b00-e054-11e9-829d-a31728c45f47.png)
> 
> So i have to close this issue. If you have some updates left a comment please.
> Thanks for your report!

0.5 is save but it will not work on practically. Like if we set 0.5 means token will expire after 30 minute by logic but in Magento 2.3 it's not happen.
If we put 0.5 that means it will check $hour > 0 then it will set 0 hour which is never expire token.

**Comment by engcom-Charlie** [comment] 2019-09-26 11:03
@sangeetajain you are right. I will update a description of issue and confirm it.

**Comment by magento-engcom-team** [comment] 2019-09-26 11:41
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20487` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by orlangur** [comment] 2019-09-27 15:19
@sangeetajain there is no bug here. Hours are supposed to be integer and config works as expected.

What is the use case to have token expiry less than 1 hour?

**Comment by sangeetajain** [comment] 2019-09-30 07:14
@ivan-koliadynskyy : Thank you for the updated code.
Just Suggestion that In admin side it's captured the string value in input filed which is not correct thing, because it should take only number then it's better.
![download](https://user-images.githubusercontent.com/4272871/65857063-b431ea80-e380-11e9-98ba-46db72ef31f1.png)

**Comment by magento-engcom-team** [comment] 2019-10-08 19:15
Hi @sangeetajain. Thank you for your report. 
The issue has been fixed in magento/magento2#24769 by @ivan-koliadynskyy in 2.3-develop branch
Related commit(s):
 - [218c16459e07c0b072c2949cae1a9f0b9f0a7754](https://github.com/magento/magento2/commit/218c16459e07c0b072c2949cae1a9f0b9f0a7754)
 - [c283bba9d737ffc426d2f24fa60b4d9743063aed](https://github.com/magento/magento2/commit/c283bba9d737ffc426d2f24fa60b4d9743063aed)
 - [0bda8d0248923c9409e76fe4378667e26f030a86](https://github.com/magento/magento2/commit/0bda8d0248923c9409e76fe4378667e26f030a86)
 - [fc5ff1266c548e09af2e6fc3db4d2c469aecf55c](https://github.com/magento/magento2/commit/fc5ff1266c548e09af2e6fc3db4d2c469aecf55c)
 - [867925dc92a51fc711275a51bc77b794fe190e0f](https://github.com/magento/magento2/commit/867925dc92a51fc711275a51bc77b794fe190e0f)

The fix will be available with the upcoming 2.3.4 release.

**Closed as completed by magento-engcom-team** 2019-10-08 19:15 UTC
Labels: Issue: Clear Description, Fixed in 2.3.x, Issue: Format is valid, Component: Api
