### ISSUE TITLE
Magento 2.4.2-p2 is showing empty attribute values after importing through csv

### ISSUE THREAD

**Issue by himanshusavranntz** [magento/magento2#35801] opened 2022-07-22 11:47 UTC
### Preconditions and environment

Magento 2.4.2-p2

### Steps to reproduce

1. The latest Magento2.4 is installed
2. Create 2 attribute sets:- attributeset1 and attributeset2
3. Create a text type attribute: attribute1
4. Assign attribute1to attributeset2
5. Create a product with attribute set attributeset1.
6. Create CSV to update the attribute set of product to attributeset2 and assign the value of attribute "attribute1" to 12.
7. Import CSV In Magento admin.

### Expected result

The product should have attribute set "attributeset2 " and the value of attribute "attribute1" to 12.

### Actual result

The product have attribute set "attributeset2 " but the value of attribute "attribute1" is empty.has

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by alikhani97** [comment] 2022-07-23 10:12
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-08-01 12:22
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-08-01 13:34
Hi @himanshusavranntz ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue.
**Steps performed:**
1. Created 2 attribute sets:- attributeset1 and attributeset2
2. Created a text type attribute: attribute1 (Admin - Stores - Attributes - Product)
3. Assigned attribute1to attributeset2
4. Created a product with attribute: attribute1. We cannot create a product with attribute set but only able to create product with attribute only.
5. Created CSV to update the attribute of product : "attribute1" to 12.
6. Import CSV In Magento admin.
No issue. Value updated as expected.
![image](https://user-images.githubusercontent.com/60198231/182159534-6a2ed819-744b-4f46-a869-f4527a33b133.png)
Kindly recheck the behavior on Magento 2.4-develop branch as it is having latest code base and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by himanshusavranntz** [comment] 2022-08-02 06:41
Hi @engcom-November 
After creating a new product please check the attribute set of the product if it's not "attributeset1" then please update attribute set to "attributeset1" then upload the csv file.

**Comment by engcom-November** [comment] 2022-08-08 11:46
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-08-08 14:08
Thank you for the response @himanshusavranntz . Verified the issue again on Magento 2.4-develop branch but unable to import CSV. Getting below error even after updating the attribute values and import is unsuccessful.
![image](https://user-images.githubusercontent.com/60198231/183436939-6731e789-fbbd-4937-802d-e73ffa3871c7.png)
Please confirm whether same behavior is observed at your end to confirm the issue and update the description.
Thank you.

**Comment by engcom-November** [comment] 2022-08-22 12:02
Hi @himanshusavranntz ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-08-22 12:02 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
