### ISSUE TITLE
Cannot instantiate interface

### ISSUE THREAD

**Issue by NguyenXuanNam** [magento/magento2#36297] opened 2022-10-14 10:35 UTC
### Preconditions and environment

- Magento version 2.4.3-p2  to 2.4.5-p2

### Steps to reproduce

1.composer require-commerce magento/product-community-edition 2.4.5-p1 --no-update
2. composer update
3. bin/magento s:up

### Expected result

Upgrade completed succesfully

### Actual result

Cannot instantiate interface Magento\AdobeImsApi\Api\ConfigInterface#0 /var/www/html/namnguyen.tech/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by NguyenXuanNam** [comment] 2022-10-14 10:36
![image](https://user-images.githubusercontent.com/14059073/195827209-505ec5ca-ed29-49d2-9634-b0be0896bc2d.png)

**Comment by NguyenXuanNam** [comment] 2022-10-14 10:38
![image](https://user-images.githubusercontent.com/14059073/195827443-5a3b8725-e0cc-45dc-889a-d3698ec86e5f.png)

**Comment by engcom-November** [comment] 2022-10-17 17:21
Hi @NguyenXuanNam ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance but the issue is not reproducible with below steps performed:
1. Installed magento 2.4.3-p2 instance with PHP 7.4 active version
2. Upgraded to 2.4.5-p1 project-community-edition as per [upgrade guide](https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/implementation/perform-upgrade.html)
3. Switched to PHP 8.1 and restart apache
No issue: User is able to access admin and store-front and no errors have been observed.
Kindly check the Magento system [requirements](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html) and any 3rd party extensions / modules enabled is causing the issue. Elaborate steps / configuration details if you are still facing any issues.
Thank you.

**Comment by engcom-November** [comment] 2022-11-03 09:14
Hi @NguyenXuanNam ,
We are closing this issue as there has been no latest updates on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-11-03 09:14 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.5-p1
