### ISSUE TITLE
Customer Reviews issue on the product page when we redirected from the customer account dashboard

### ISSUE THREAD

**Issue by Dhaval410** [magento/magento2#35062] opened 2022-02-07 12:59 UTC
### Preconditions (*)

1. Magento 2.4.3-p1

### Steps to reproduce (*)

1. Login in the frontend.
2. Add a review to any product. 
3. Goto account dashboard and click on the 'My Product Reviews' tab from the account sidebar as shown in the attached image.
![My-Account](https://user-images.githubusercontent.com/59201168/152770618-a9ec0bbd-ea70-4e5d-ba59-f0aade0714dc.png)

4. Now click on the 'See Details' link from the My Product Reviews. 
![My-Product-Reviews](https://user-images.githubusercontent.com/59201168/152771322-cf68ca68-31ba-4b5f-91fe-06377edabbbe.png)

5. Now from the 'Review Details' click on the 'Reviews' link. It will go to the product page with the review tab selected. And customer reviews are missing.
![Review-Details](https://user-images.githubusercontent.com/59201168/152772032-ef2a89ed-f93f-4c2d-9e78-de624dd51166.png)

### Expected result (*)

1. When we click on the review link from the Review Details from the customer account then it should display the customer review in the review tab on the product page. Please see attached image.
![customer-review-on-review-tab](https://user-images.githubusercontent.com/59201168/152774921-2b7fa323-2170-4f86-832f-c4ccfc13ca32.png)

### Actual result (*)

1. Customer Reviews are missing on the product page in the review tab.
![missing-customer-review](https://user-images.githubusercontent.com/59201168/152775104-a55ff59b-64f8-4c8e-b5ce-07c59c51f9ed.png)

### Additional comments (*)

I have found that the issue may be in this file on line number 43.
File path - vendor/magento/module-review/view/frontend/web/js/process-reviews.js

reviewTab.hasClass('active') this gives 'false'  instead of the 'true' result when we see the review from the customer account dashboard. It seems that this script executes before the active class adds to that element. Maybe it will helpful to you.
![process-review-js](https://user-images.githubusercontent.com/59201168/152786092-7c46c8cd-c343-41bb-87a9-411faa5f0033.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as a Reporter. This information will help during the Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without a workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look, and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2022-02-10 13:55
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment] 2022-02-11 12:58
Hi @Dhaval410,

Thank you for reporting the issue.
We tried to reproduce the issue on Magento 2.4-develop branch but the issue is not reproducible.

Steps performed:
1. Install a clean version of Magento 2.4-develop
2. Create new product
3. Login in the frontend.
4. Add a review to any product.
5. Go to account dashboard and click on the **My Product Reviews** tab from the account navigation as shown in the attached image.
![Screenshot from 2022-02-10 19-50-42](https://user-images.githubusercontent.com/60198022/153594119-67ab608b-de1c-4689-a6a3-faa4aaf9a5f5.png)

6:Now click on the 'See Details' link from the **My Product Reviews** Page.
![Screenshot from 2022-02-10 19-50-54](https://user-images.githubusercontent.com/60198022/153594239-c16d8ca4-850f-4ac7-8452-73419e4b8d12.png)

**Result:** 
Customer Reviews are present on the Product Page in the Review tab
![Screenshot from 2022-02-10 19-51-12](https://user-images.githubusercontent.com/60198022/153594913-e885f1cc-ec4a-4c1d-aefc-c834f5084f96.png)

**Note:** In order for the product review to be reflected on the frontend the review needs to be approved from **admin panel**. For that we need to go to **Marketing->User Content->All/Pending Reviews**.
Once the review is approved it will be visible on storefront.

Please let me know if this is exactly what your issue was or if there is some more configuration required from my end. Will update accordingly.

Thanks!

**Comment by engcom-Hotel** [comment] 2022-02-25 08:20
Dear @Dhaval410,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-02-25 08:20 UTC
Labels: Issue: needs update, Area: Account, Area: Product
