### ISSUE TITLE
Magento 2.4.5CE - An error occurs when dismiss a task message

### ISSUE THREAD

**Issue by nhatlich994** [magento/magento2#36581] opened 2022-12-08 03:29 UTC
### Preconditions and environment

- Magento version 2.4.5CE

### Steps to reproduce

Example:
- Login Admin
- Go to Catalog > Products 
- Select one product
- Choose mass action Update attributes
- Update the Product Name and click Save
- At this point, new message will be added to top.
- Click X to dismiss the message > An error will be showed.

Video: https://www.loom.com/share/597167c0a4614a288ac636e8b804ed5e

### Expected result

Message is dismissed successfully

### Actual result

Message is dismissed successfully but an error still shows

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-12-08 12:34
Hi @ihor-sviziev,

I saw your previous comment and you have mentioned for the super admin, I have Administrator role in that all the privileges has been given. Below is the screenshot:

<img width="1192" alt="Screenshot 2022-12-08 at 5 24 01 PM" src="https://user-images.githubusercontent.com/51680745/206446701-797a1da8-b13c-4d73-8f4b-0c96384a6e19.png">


I found the same issue using that Administrator role.I want to know whether we have any other way to create a super admin.

Thanks.

**Comment by ihor-sviziev** [comment] 2022-12-08 12:41
If that issue is reproducible as the administrator with selected all permissions - please just confirm it

**Comment by engcom-Bravo** [comment] 2022-12-08 13:49
Thanks for your update @ihor-sviziev

**Comment by engcom-Bravo** [comment] 2022-12-08 13:56
Hi @psydog-1101,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the attached video.


**Steps to reproduce**


1.Login Admin
2.Go to Catalog > Products
3.Select one product
4.Choose mass action Update attributes
5.Update the Product Name and click Save
6.At this point, new message will be added to top.
7.Click X to dismiss the message > An error will be showed.


Message is dismissed successfully but an error still shows.



https://user-images.githubusercontent.com/51680745/206463504-8b6740d7-67ff-4226-8e4f-04c143acfb78.mov



Hence Confirming the issue.

Thanks.

**Comment by rshadab25** [comment] 2022-12-09 08:21
@magento I am working on it

**Comment by rshadab25** [comment] 2022-12-09 08:25
@magento add to contributors team

**Comment by rshadab25** [comment] 2022-12-09 08:32
@magento I am working on it

**Comment by rshadab25** [comment] 2022-12-17 17:47
@magento give me 2.4.5 instance

**Comment by vDeggial** [comment] 2023-01-07 00:36
any update on this? applied the PR patch and it does delete the notification but error something happened still occurs 

thanks

**Comment by hostep** [comment] 2023-01-19 18:51
@vDeggial : I think it got fixed in scope of [ACP2E-1245: "Something went wrong" error is displayed when clearing the completed bulk tasks.](https://github.com/magento/magento2/search?q=ACP2E-1245&type=commits), I _think_ this is the merge commit: https://github.com/magento/magento2/commit/fb586ea689792a3f3c8a9f4b9e6230dc20dda9a6 (but not sure)

**Closed as completed** 2023-06-13 13:04 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done, Component: Attributes, Area: Admin UI, Reported on 2.4.5
