### ISSUE TITLE
Setting price step calculation to equalize product count breaks graphQl

### ISSUE THREAD

**Issue by dwsmart** [magento/magento2#36803] opened 2023-02-03 10:53 UTC
### Preconditions and environment

- Magento version 2.4.5
- elastic search 

### Steps to reproduce

1. Go to  Stores > Configuration > Catalog > Layered Navigation and change price step calculation to equalize product counts.
2. Reindex / clear caches
3. try and fetch aggregations for a category via graphQL

### Expected result

Aggregation is returned, with price banded as expects

### Actual result

Get a 500, with an error response, missing index in

`vendor/magento/framework/Search/Dynamic/Algorithm/Improved.php` line 79

Specifically it seems to be an issue with $data[$key]['to'] missing from the array.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2023-02-09 08:55
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2023-02-09 09:49
Hi @dwsmart ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance but the issue is not reproducible with the below steps performed:
Steps performed:
1. Stores - Configuration - Catalog - Catalog - Layered Navigation - Price Navigation Step Calculation set to "Automatic (equalize product counts)" save
2. Reindex and clear cache
3. Run the below graphql query
No errors were observed.
![image](https://user-images.githubusercontent.com/60198231/217777812-cf51a649-2329-4acc-bd67-c7dd9f439e0f.png)
Kindly recheck the behavior on Magento 2.4-develop instance and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2023-02-23 04:35
Hi @dwsmart ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2023-02-23 04:35 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.5
