### ISSUE TITLE
Exception on Customer Email Update

### ISSUE THREAD

**Issue by a4deel** [magento/magento2#34771] opened 2021-12-08 07:28 UTC
### Summary (*)
I am trying to update customer email in Magento 2 by using Customer Repository via REST API but it throws exception when we try to save customer. We are using Magento 2.3.7 Community Version.

Here is my exception

"messages": {
        "error": [
            {
                "code": 500,
                "message": "Fatal Error: 'Uncaught Error: Call to undefined method Magento\\Framework\\Exception\\StateException::getResponse() in /var/www/html/kaswaa/vendor/magento/framework/Reflection/DataObjectProcessor.php:91\nStack trace:\n#0 /var/www/html/kaswaa/vendor/magento/framework/Webapi/ServiceOutputProcessor.php(126): Magento\\Framework\\Reflection\\DataObjectProcessor->buildOutputDataArray(Object(Magento\\Framework\\Exception\\StateException), 'DevBatch\\\\WebApi...')\n#1 /var/www/html/kaswaa/vendor/magento/framework/Webapi/ServiceOutputProcessor.php(78): Magento\\Framework\\Webapi\\ServiceOutputProcessor->convertValue(Object(Magento\\Framework\\Exception\\StateException), 'DevBatch\\\\WebApi...')\n#2 /var/www/html/kaswaa/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(97): Magento\\Framework\\Webapi\\ServiceOutputProcessor->process(Object(Magento\\Framework\\Exception\\StateException), 'DevBatch\\\\WebApi...', 'changeSellerEma...')\n#3 /var/www/html/kaswaa/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\\Webapi\\Controller\\' in '/var/www/html/kaswaa/vendor/magento/framework/Reflection/DataObjectProcessor.php' on line 91",
                "trace": "Trace is not available."
            }
        ]
    }

### Examples (*)

Here is my code

public function changeSellerEmail(){
        $paramData = $this->_request->getParams();
        $sellerId = $paramData['seller_id'];
        $password = $paramData['password'];
        $email = $paramData['email'];
        if($this->_customerAuthentication->authenticate($sellerId, $password))
        {
            $customer  = $this->_customerRepository->getById($sellerId);
            $customer->setEmail($email);
            try {
                $this->_customerRepository->save($customer);
                return "customer saved";
            } catch (\Exception $e) {
                return $e;
            }
        }
    }

---

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround.

**Comment by engcom-Hotel** [comment] 2021-12-09 07:48
Hi @a4deel,

Thank you for reporting the issue.
However, we tried to reproduce it on Magento 2.4-develop but the customer update functionality is working as expected.
From the error details, it looks like the issue is with the code that you have tried.
See the code sample used in the following integration test, it is having the almost same code that you want to do.

dev/tests/integration/testsuite/Magento/Customer/Block/Adminhtml/Edit/Tab/View/PersonalInfoTest.php

If the issue still persists at your end then please provide more details, I’ll try to reproduce it again.

Thanks

**Comment by a4deel** [comment] 2021-12-09 13:34
Hi @engcom-Hotel,
When we try to update customer email in web flow then it works fine but in REST API it did not work for me. I tried this code on multiple systems. And also if we use  $customer->setData() function to set email it works fine as well. issue is only in REST API when we save customer repository after setting email.

**Comment by engcom-Hotel** [comment] 2022-02-02 10:56
Hello @a4deel,

Please tell us about your environment, and are you using CE or B2B.

Thanks

**Comment by engcom-Hotel** [comment] 2022-02-16 01:52
Dear @a4deel,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-02-16 01:52 UTC
Labels: Triage: Dev.Experience, Issue: needs update
