### ISSUE TITLE
app:config:dump adds extra space every time in multiline array value

### ISSUE THREAD

**Issue by gulshan-streammarket** [magento/magento2#11328] opened 2017-10-10 09:52 UTC
### Preconditions

1. php 7.0.19
2. Magento 2.2

### Steps to reproduce

1. RUN > php bin/magento app:config:dump
2. Search for 'address_templates' key in config.php and count number of spacees in every line of formatted multiline text value.
3. Now run  again>php bin/magento app:config:dump
4. Again check for number of spaces. You will find two more space.
5. Every time when we dump of execute setup:upgrade it adds extra space to multiline config value.

### Expected result

1. There should be no extra space if there is no change in the configuration.

### Actual result

1. It adds extra space and it shows as modified in git local working copy. So every time it needs commit when sending feature to repository.
![m2-config-issue](https://user-images.githubusercontent.com/32667915/31380343-065289a6-ada9-11e7-9421-6b5114aab158.png)

**Comment by magento-engcom-team** [comment] 2017-10-10 11:30
@gulshan-streammarket, thank you for your report.
We've created internal ticket(s) MAGETWO-81401 to track progress on the issue.

**Comment by gulshan-streammarket** [comment] 2017-10-10 11:42
Thank You. I will be waiting for fix.

**Comment by dmanners** [comment] 2017-10-13 09:53
For more detail on the problem the issue is with config elements that contain `\n` in them. For example the address templates or the search_engine_robots->default_custom_instructions section.

The problem happens in the class `lib/internal/Magento/Framework/App/DeploymentConfig/Writer/PhpFormatter.php` https://github.com/magento/magento2/blob/2.2-develop/lib/internal/Magento/Framework/App/DeploymentConfig/Writer/PhpFormatter.php#L37 when formatting the output it replaces `\n` characters with `\n   `

`return "<?php\nreturn array (\n" . implode(",\n", str_replace("\n", "\n  ", $elements)) . "\n);\n";` I think that a good solution here would be to change the way that this file is created

**Comment by adrian-martinez-interactiv4** [comment] 2017-10-13 19:47
@gulshan-streammarket @dmanners Hope this PR fixes this issue

**Comment by okorshenko** [comment] 2017-10-24 01:53
Hi @gulshan-streammarket the issue has been fixed in 2.1-develop branch. PRs to 2.2 and 2.3 are on the way. Closing the issue

**Closed as completed by okorshenko** 2017-10-24 01:53 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid

**Comment by magento-team** [comment] 2017-10-24 02:16
Internal ticket to track issue progress: MAGETWO-82237

**Comment by magento-team** [comment] 2017-10-24 22:18
Internal ticket to track issue progress: MAGETWO-82236

**Comment by magento-team** [comment] 2017-10-25 04:16
Internal ticket to track issue progress: MAGETWO-82235
