### ISSUE TITLE
Unable to process binding "if: function (){return quoteIsVirtual == 0 }"

### ISSUE THREAD

**Issue by shravanpathipaka** [magento/magento2#29476] opened 2020-08-11 13:13 UTC
Preconditions (*)
2.3.5-p2
Default Checkout 

Steps to reproduce (*)
Add any product to cart
Go to Checkout & Proceed as a guest user
Choose Any payment
Expected result (*)
Order should have been created.

Actual result (*)
Error appears in the console  "Unable to process binding "if: function (){return quoteIsVirtual == 0 }"
![js](https://user-images.githubusercontent.com/57125351/89901287-88b79780-dc02-11ea-97fe-d5c809e856c6.PNG)

- Repro on 2.4-develop - NO
- Repro on 2.3.5p2 - NO
- Repro on 240 - NO

**Comment by engcom-Oscar** [comment] 2020-08-18 08:02
Hi @shravanpathipaka 

Thank you for your report and collaboration!

I closing this issue, because I was unable to reproduce it using provided Steps to Reproduce from the Description section on clean 2.4-develop and 2.3.5-p2 version of Magento. Perhaps the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the Description section and reopen this issue.

**Closed as completed by engcom-Oscar** 2020-08-18 08:02 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid, Reported on 2.3.5-p2

**Comment by user-aruntr** [comment] 2020-11-11 10:18
I have getting the same error while updating from 2.3 to 2.4 magento.
