### ISSUE TITLE
Dropdown values of product attributes are not getting.

### ISSUE THREAD

**Issue by devqualwebs** [magento/magento2#7087] opened 2016-10-19 09:29 UTC
I am trying to show all the dropdown values of product attributes on product list page in magento 2.
### Magento Version
1. Magento ver. 2.1.0

<?php // $productList is an array of all products showing on product list page
$firstProduct = array_shift($productList);

```
    // this product's price rule category
    $price_rule_category = $firstProduct->getprice_rule_category();

    // loop through simple products
    // loop through simple products
    $conf = $objectManager->create('Magento\ConfigurableProduct\Model\Product\Type\Configurable')->setProduct($firstProduct);
    $simple_collection = $conf->getUsedProductCollection()->addAttributeToSelect('*')->addFilterByRequiredOptions();

    foreach($simple_collection as $simple_product){

        // get size
        $size_option = $simple_product->getAttributeText('size_option');
        $size_options[$size_option] = $simple_product->getsize_option();

        // get the pricing table key for this product, we'll only show products that have the same qty breaks in this loop
        $table = $price_rules->getPricingTable($price_rule_category,$size_options[$size_option]);
        if($table) $current_table = $table;

        // get this product's price breaks to get the column labels
        if($price_rules) $price_breaks[$size_option] = $price_rules->getQtyBreaks($price_rule_category,$simple_product->getsize_option());
    }   

    // add first product back to list
    array_unshift($productList,$firstProduct);
```
### Steps to reproduce
1. on putting the above code, products are not showing on the list page. 
2. also when i am using "setProduct()" function to pass my $firstProduct. i am getting 
   Fatal error: Call to undefined method Magento\ConfigurableProduct\Model\Product\Type\Configurable\Interceptor::setProduct().
### Expected result
1. I want to get all values of "$size_option" of product so that i can show these values in my frontend on product list page.

**Comment by veloraven** [comment] 2016-10-19 11:42
@devqualwebs thank you for your feedback.
Please, identify which version of Magento you are running.

**Comment by devqualwebs** [comment] 2016-10-19 11:44
I am using Magento ver. 2.1.0

**Comment by lhsatch** [comment] 2016-10-21 12:28
If you take a look in vendor\magento\module-configurable product\view\frontend\templates\product\view\type\options\configurable.phtml you will see a call to $block->getJsonConfig(). This function contains all the data you will probably need relating to the dropdown values of a configurable product. The only problem is that it currently is only setup to get the current product. In your list.phtml file add the below code to request the configurable product details.
`<script type="text/x-magento-init">
                                            {
                                                "#product_addtocart_form<?php echo $_product->getId();?>": {
                                                    "configurable": {
                                                        "spConfig": <?php /* @escapeNotVerified */ echo $matrixConfigurableBlock->getJsonConfigForProdList($_product) ?>,
                                                        "onlyMainImg": <?php /* @escapeNotVerified */ echo $matrixConfigurableBlock->getVar('change_only_base_image', 'Magento_ConfigurableProduct') ?: 'false'; ?>
                                                    }
                                                }
                                            }
                                        </script>`
Note that I have created a new configurable.php class extended from Magento\ConfigurableProduct\Block\Product\View\Type\Configurable which gets assigned to "matrixConfigurableBlock" as below:
`$matrixConfigurableBlock = $this->getLayout()->createBlock('Its\ConfigMatrix\Block\Catalog\Product\View\Type\Configurable');`
 Below is the additional function (getJsonConfigForProdList) that I have created which passes each product object through and gets the data for it.
`public function getJsonConfigForProdList($product)
    {

```
    $store = $this->getCurrentStore();
    $currentProduct = $product;
    $regularPrice = $currentProduct->getPriceInfo()->getPrice('regular_price');
    $finalPrice = $currentProduct->getPriceInfo()->getPrice('final_price');
 $options = $this->helper->getOptions($currentProduct, $this->getAllowProductsForProdList($product));

    $attributesData = $this->configurableAttributeData->getAttributesData($currentProduct, $options);

    $config = [
        'attributes' => $attributesData['attributes'],
        'template' => str_replace('%s', '<%- data.price %>', $store->getCurrentCurrency()->getOutputFormat()),
        'optionPrices' => $this->getOptionPrices(),
        'currencySymbol'=>str_replace('%s','', $store->getCurrentCurrency()->getOutputFormat()),
        'prices' => [
            'oldPrice' => [
                'amount' => $this->_registerJsPrice($regularPrice->getAmount()->getValue()),
            ],
            'basePrice' => [
                'amount' => $this->_registerJsPrice(
                    $finalPrice->getAmount()->getBaseAmount()
                ),
            ],
            'finalPrice' => [
                'amount' => $this->_registerJsPrice($finalPrice->getAmount()->getValue()),
            ],
        ],
        'productId' => $currentProduct->getId(),
        'chooseText' => __('Choose an Option ...'),
        'images' => isset($options['images']) ? $options['images'] : [],
        'index' => isset($options['index']) ? $options['index'] : [],
    ];

    if ($currentProduct->hasPreconfiguredValues() && !empty($attributesData['defaultValues'])) {
        $config['defaultValues'] = $attributesData['defaultValues'];
    }

    $config = array_merge($config, $this->_getAdditionalConfig());

    return $this->jsonEncoder->encode($config);
}`
```

You will also need to craete another new function to accommodate passing individual products instead of the current product.

`public function getAllowProductsForProdList($confProduct)
    {
        if (!$confProduct->hasAllowProducts()) {
            $products = [];
            $skipSaleableCheck = $this->catalogProduct->getSkipSaleableCheck();

```
        $allProducts = $confProduct->getTypeInstance()->getUsedProducts($confProduct, null);
        foreach ($allProducts as $product) {
            if ($product->isSaleable() || $skipSaleableCheck) {
                $products[] = $product;
            }
        }

        $this->setAllowProducts($products);
    }
    return $this->getData('allow_products');
}` 
```

You should now have an array of  all the details you need.

**Comment by magento-engcom-team** [comment] 2017-10-25 08:30
@devqualwebs, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-25 08:30 UTC
Labels: bug report, Component: Catalog, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is not valid
