### ISSUE TITLE
Magento 2.2.7 single product image doesn't display unless more than one image is added to product

### ISSUE THREAD

**Issue by sts-ryan-holton** [magento/magento2#21138] opened 2019-02-11 16:47 UTC
### Preconditions (*)
1. Magento 2.2.7
2. Custom theme based off of Magento Black/Luma

### Steps to reproduce (*)
1. Add a new product and attach a single image

### Expected result (*)
1. Image should be displayed on frontend

### Actual result (*)
1. Image area is empty and isn't displayed, the images will display if more than one image is attached to a product. 

![screenshot 2019-02-11 at 16 46 43](https://user-images.githubusercontent.com/25177538/52578679-a42ec000-2e1c-11e9-9b42-9a92927e6a3a.png)

![screenshot 2019-02-11 at 16 47 04](https://user-images.githubusercontent.com/25177538/52578701-adb82800-2e1c-11e9-8486-3f052e32b543.png)

**Comment by magento-engcom-team** [comment] 2019-02-11 16:47
Hi @sts-ryan-holton. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sts-ryan-holton do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-02-11 19:12
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment] 2019-02-12 05:34
@sts-ryan-holton this issue doesn't exists on current magento 2.2-develop instance it is may be due to custom work on at your end. as github is intended for issues in magento core files and functionality I am closing this

**Closed as completed by shikhamis11** 2019-02-12 05:34 UTC
Labels: Issue: Format is valid
