### ISSUE TITLE
Magento/Multishipping: Setting wrong back url on creation New Customer Shipping Address Page

### ISSUE THREAD

**Issue by Totem4ik** [magento/magento2#24701] opened 2019-09-23 14:50 UTC
### Preconditions (*)
1. Magento 2.3.2
2. Sample data installed

### Steps to reproduce (*)
1. Create new customer (customer should not have addresses).
2. Add some product to cart.
3. Open cart.
4. Click "Check Out with Multiple Addresses".
5. On "Create shipping address" page click "Back button".

### Expected result (*)
1. Url in Back button : `https://example.com/checkout/cart/`.
2. Back on checkout cart.

### Actual result (*)
1.  Url in Back button : `https://example.com/multishipping/cart/`.
2. Get 404 page.

**Comment by ajijshekh123** [comment] 2019-09-24 05:00
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-09-24 05:00
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-09-24 05:00
Hi @ajijshekh123, here is your [Magento instance](https://i-24701-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24701-2-3-develop.instances.magento-community.engineering/admin](https://i-24701-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2019-09-24 05:27
@Totem4ik - I have reproduced this issue as per your steps and scenario. Back functionality is working fine in the latest Magento 2.3 instance.
Please review attach the video:

![Backbutton Issue](https://user-images.githubusercontent.com/24711761/65483487-00c98180-deba-11e9-899c-89574dd1bfd3.gif)

**Comment by Totem4ik** [comment] 2019-09-24 07:54
@ajijshekh123 Hi! Thank you! One more detail what i missed. "Back Button" hide on this theme, but if you make a visible this block, you'll see that problem.
I attach two images to show you what i mean
![magento_bug](https://user-images.githubusercontent.com/17617628/65492312-5cdfd600-deb9-11e9-817e-a046c7e3f46c.png)
![magento_bug_3](https://user-images.githubusercontent.com/17617628/65492453-a4666200-deb9-11e9-9457-e7f7c30a396f.png)

**Comment by magento-engcom-team** [comment] 2019-09-24 07:59
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20370` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by MaxSouza** [comment] 2019-10-01 19:51
@Totem4ik for default the button is hidden, so it does not an error. We can't reproduced your issue.

**Comment by Totem4ik** [comment] 2019-10-02 07:50
@MaxSouza you have this functionality in core of magento2 on backend. So, behavior of this functional is wrong. This doesn't a theme problem, this problem in core, so when we using another theme this bug doesn't hidden. How to reproduce this issue you can find above in topic and comment with screenshot.
Could you remove behavior of this button from controller or fix it ?

**Comment by MaxSouza** [comment] 2019-10-02 13:46
@Totem4ik Ah ok, I'll fix the url.

**Comment by magento-engcom-team** [comment] 2019-10-08 19:15
Hi @Totem4ik. Thank you for your report. 
The issue has been fixed in magento/magento2#24827 by @MaxSouza in 2.3-develop branch
Related commit(s):
 - [7c5e7178abdb799062b67230589e4b7c70f8213c](https://github.com/magento/magento2/commit/7c5e7178abdb799062b67230589e4b7c70f8213c)
 - [a528841c676f188824ca30479ca3e1d801b729c4](https://github.com/magento/magento2/commit/a528841c676f188824ca30479ca3e1d801b729c4)
 - [88532ef5e2cd5b580250793c39f7b1ae32e93815](https://github.com/magento/magento2/commit/88532ef5e2cd5b580250793c39f7b1ae32e93815)
 - [ecb2249fd67ce4d489e81c131349191c7256268b](https://github.com/magento/magento2/commit/ecb2249fd67ce4d489e81c131349191c7256268b)
 - [fded460ee1bc92156ff479e29115fe06fbbaffaa](https://github.com/magento/magento2/commit/fded460ee1bc92156ff479e29115fe06fbbaffaa)

The fix will be available with the upcoming 2.3.4 release.

**Closed as completed by magento-engcom-team** 2019-10-08 19:15 UTC
Labels: Issue: Ready for Work, Progress: needs update, Component: Checkout, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Multishipping
