### ISSUE TITLE
User with custom permissions can not save Vimeo videos to products

### ISSUE THREAD

**Issue by theGC** [magento/magento2#3031] opened 2016-01-19 09:39 UTC
After setting up a new user role we found that users assigned it are unable to save Vimeo videos within products unless they are granted:

Resource Access : all

Any custom permissions, even checking everything, prevents the user from being able to save Vimeo videos.

**Comment by xmav** [comment] 2016-09-09 10:59
Hi @theGC, thanks for reporting this issue. Internal ticket MAGETWO-58228 was created.

Thanks,
Maksym

**Comment by magento-engcom-team** [comment] 2017-10-11 11:30
@theGC, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-11 11:30 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid
