### ISSUE TITLE
Site will not let me view all our customers

### ISSUE THREAD

**Issue by KatieCoyle-RitzSafety** [magento/magento2#37595] opened 2023-06-08 18:27 UTC
### Preconditions (*)

1.  Magento ver. 2.4.3-p1
2. I'm not a tech person, I'm not sure what any of those mean

### Steps to reproduce (*)

1.  I literally have no idea, it worked one second and not the next.
2.  I thought the issue would resolve itself but 2 hours later and it still hasn't,
3. 

### Expected result (*)

1. It should pull all our customer database, I should be able to search by name, emai;, customer code and filter by bill to account numbers etc.

### Actual result (*)

1. I get an action popup with "Attention Something went wrong." after clearing this away. The screen continues to load, and a red banner is at the header stating: "Something went wrong with processing the default view and we have restored the filter to its original state" - the screen never loads, and refreashing brings back the popup. I've restarted my computer, logged out of my account, signed back in, everything. This is the only tab not working, all the other routes and tabs load just fine!
2. 
![image](https://github.com/magento/magento2/assets/136011180/ffe1e602-61ba-4bb8-aa5f-af80eddad363)
![image](https://github.com/magento/magento2/assets/136011180/fe3eb498-fa15-4d56-a926-3d1fdf382952)

**Comment by engcom-Bravo** [comment] 2023-06-09 06:25
Hi @KatieCoyle-RitzSafety,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

We are able to create the customers and able to edit.

<img width="1503" alt="Screenshot 2023-06-09 at 11 54 04 AM" src="https://github.com/magento/magento2/assets/51680745/4b84fe40-76b7-405a-b429-e4a6dd40041a">



Please try to clean cache and browser cache and try to enable cron by refering this document https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/cli/configure-cron-jobs.html

```
bin/magento indexer:reindex && bin/magento c:f
bin/magento setup:upgrade
```

Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.

Thanks.

**Comment by baijuncybercom** [comment] 2023-06-09 07:16
#Reported on 2.4.3-p1

**Comment by engcom-Bravo** [comment] 2023-06-20 10:03
@drinkingsouls Thanks for your contribution & collaboration over here.

@KatieCoyle-RitzSafety,

Please provide us latest update on this comment https://github.com/magento/magento2/issues/37595#issuecomment-1584041570 and kindly let us know still if you are facing any issue.Please refer this https://github.com/magento/magento2/issues/37595#issuecomment-1597474357


Thanks.

**Comment by engcom-Bravo** [comment] 2023-07-05 05:42
Hi @KatieCoyle-RitzSafety,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-07-05 05:42 UTC
Labels: Issue: needs update, Reported on 2.4.3-p1
