### ISSUE TITLE
Can't change email on customer profile and then send out new order emails

### ISSUE THREAD

**Issue by lisaspencer1** [magento/magento2#37198] opened 2023-03-13 09:50 UTC
### Preconditions and environment

- Magento ver. 2.3.5-p2
Sometimes customer's will accidentally write a typo in their email address so they don't end up receiving them order emails etc. When they let us know and we go and change it, the email address has changed in the customer's account but the order still has the wrong email address in there. Is there no way of resending the email to the correct email address?

### Steps to reproduce

1. Customers > All Customers > 'search customer' > change email address > save and continue
2. Sales > Orders > 'search customer's order' > (here you can see on the account information that the customer's email address has still not changed from the typo) > 'Send Email' 
3. Mageplaza > Email logs > 'search customer typo email address' > new email has been sent /// 'search customer correct email address' no email logs

### Expected result

Email address is changed and I can resend emails 

### Actual result

Email address doesn't change for the customer's orders and will only send to the original email

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-03-14 10:54
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-03-14 14:19
**Hi @lisaspencer1 ,**

Verified the issue in 2.4-develop instance and the issue is not reproducible.

**Preconditions:**
Magento Version 2.4-develop instance
PHP Version 8.1

**Steps to reproduce:**
1.Install magento instance
2.Go to Back end >> Customers >> All customers
3.Select one customer and go to account information change the email address
4.Go to Sales >> Order>>select the order and check the email address
5.Try to resend the mail from order page.

**Kindly refer the below screenshots:**

<img width="1505" alt="cu5" src="https://user-images.githubusercontent.com/60198592/225029300-31bc9d8e-05ea-4e20-8bc4-f52106f2ea28.png">**
<img width="1505" alt="cu1" src="https://user-images.githubusercontent.com/60198592/225029234-d87d6ab6-7aec-4ffe-a2c7-46b92ee44504.png">
<img width="1504" alt="cu2" src="https://user-images.githubusercontent.com/60198592/225029280-ccad8c3b-204b-48fa-91da-443d21e6fb2a.png">
<img width="1504" alt="cu3" src="https://user-images.githubusercontent.com/60198592/225029292-57945069-1371-48f2-acad-e18c850ba9bb.png">

We are getting expected results as per the description and we attached screenshot of resend mail.Email is changed and received resend mail.

Let us know if we missing anything.

Regards,

**Comment by engcom-Dash** [comment] 2023-03-15 08:57
Hi @lisaspencer1 ,

Thanks for your Quick response,

In your last [comment](https://github.com/magento/magento2/issues/37198#issuecomment-1468212485) You attached steps with Screenshots,But we are not able you see any screenshots from our end.Kindly check your last comments and Kindly attach respective screenshots to reproduce the as soon as possible.

Regards,

**Comment by lisaspencer1** [comment] 2023-03-15 09:27
Hi

I'll show from my end and I wonder if it's my specific page then?

The order right now: (the @[hotmail.com](http://hotmail.com/) email is incorrect, the original email address signed up for when purchasing. It should be @[outlook.com](http://outlook.com/)). I click on 'Edit Customer':
![image (2)](https://user-images.githubusercontent.com/127735881/225266307-152c42ca-2471-49ef-9557-bc1938396f5a.png)

When I click on 'Edit customer', I'm taken to the next page where the email address is, and the new email address I inputted before is still there. I click 'Save Customer' again:
![image (3)](https://user-images.githubusercontent.com/127735881/225266352-b2db04ac-0da8-42af-a391-ad8613b54edb.png)


The customers page here shows the changed new email address:
![image (4)](https://user-images.githubusercontent.com/127735881/225266463-71c03add-3b1b-4ae9-a875-d308e56507d6.png)



But when I go back to the order, it still shows the old email address:
![image (5)](https://user-images.githubusercontent.com/127735881/225266493-42f717cf-4b52-4e0a-89c0-95844623aec4.png)


Kind Regards,

Lisa Spencer She/Her

**Comment by engcom-Bravo** [comment] 2023-03-16 13:09
Hi @lisaspencer1,

Thanks for your update.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


We have ordered a product with registered customer.

<img width="1391" alt="Screenshot 2023-03-16 at 2 23 40 PM" src="https://user-images.githubusercontent.com/51680745/225574297-5c648ffc-913e-48bf-b893-ccc6ca910cbe.png">




We have changed customer email address by clicking edit customer.


<img width="1417" alt="Screenshot 2023-03-16 at 2 24 40 PM" src="https://user-images.githubusercontent.com/51680745/225573728-0901c07e-0a3c-4844-8840-95259acddd64.png">




New email is triggered in the order.


<img width="1362" alt="Screenshot 2023-03-16 at 2 25 22 PM" src="https://user-images.githubusercontent.com/51680745/225574338-ec421d3b-2fe6-43f2-a98a-008e9ddf93c1.png">



Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.


it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-03-27 06:05
Hi @lisaspencer1,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-03-27 06:05 UTC
Labels: Issue: needs update, Reported on 2.3.5-p2

**Comment by intuji-bhimlamichhane** [comment] 2025-03-17 08:22
Scenerio : In magento2.4.7 admin panel,I created a user "ABC" with email 'abc@gmail.com" and then placed a order,It is working fine.
But the Issue is that, when I try to change the email of that user "ABC"  to "xyz@gmail.com ' and try saving that user, Then it is throwing ""Rolled back transaction has not been completed correctly" in system.log file.
whereas it is throwing "Something went wrong while saving the customer" in admin panel UI.

My concern is that: Does the magento 2.4.7 allow was to change that old email  to new email of those user who has placed the order previoulsy with those old email?As, that old email is linked with the sales order,does it prevent updating the user email?
