### ISSUE TITLE
 Reviews by Customers - customer_entity - exceptions

### ISSUE THREAD

**Issue by ComputerNorth** [magento/magento2#5471] opened 2016-07-05 12:05 UTC
## Steps to reproduce
1. Install 2.0.6 CE
2. Upgrade to 2.1.0 CE by composer update
## Expected result
1. In magento 2.0.6 when you go in the backend to Reports --> Reviews by Customers, you see a table with all the reviews per customer, I expected the same result in 2.1.0.
## Actual result
1. 2 exception(s):
   Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S02]: Base table or view not found: 1146 Table '[DBname].customer_entity' doesn't exist, query was: SELECT COUNT(DISTINCT detail.customer_id) FROM `[DBprefix_]review` AS `main_table`
   INNER JOIN `[DBprefix_]review_detail` AS `detail` ON main_table.review_id = detail.review_id
   INNER JOIN `customer_entity` AS `customer` ON customer.entity_id = detail.customer_id

Exception #1 (PDOException): SQLSTATE[42S02]: Base table or view not found: 1146 Table '[DBname].customer_entity' doesn't exist

---

'It looks like the prefix isn't used for customer_entity. Shouldn't the table be '[DBname].[DBprefix_]customer_entity' and [DBprefix_]customer_entity

**Comment by miakusha** [comment] 2016-09-15 12:23
Hi @ComputerNorth 
Thank you for your report.
 We've created internal ticket MAGETWO-58513 to address this issue.

**Comment by magento-engcom-team** [comment] 2017-10-18 11:30
@ComputerNorth, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-18 11:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Customer, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid
