### ISSUE TITLE
Login into frontend for customers no longer works

### ISSUE THREAD

**Issue by stradd** [magento/magento2#35620] opened 2022-06-15 13:16 UTC
### Preconditions and environment

2.4.3-p1
Php: 7.4.30
community edition

### Steps to reproduce

composer update command

rm -rf var/cache/* && rm -rf var/page_cache/* && rm -rf generated/code/* && php bin/magento setup:upgrade && php bin/magento setup:di:compile && php bin/magento setup:static-content:deploy && php bin/magento indexer:reindex && php bin/magento cache:clean && php bin/magento cache:flush 

### Expected result

Login to customer account is still possible

### Actual result

Login in frontend for customers no longer works.
When I want to create a new account the error message is: We can't save the customer.
Customer Login: The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.
Reset Admin Password wit the Link in the mail:

1 exception(s):
Exception #0 (SodiumException): unsupported password hashing algorithm

Exception #0 (SodiumException): unsupported password hashing algorithm
<pre>#1 Magento\Framework\Encryption\Encryptor->getArgonHash() called at [vendor/magento/framework/Encryption/Encryptor.php:225]
#2 Magento\Framework\Encryption\Encryptor->getHash() called at [vendor/magento/module-user/Model/User.php:731]
#3 Magento\User\Model\User->_getEncodedPassword() called at [vendor/magento/module-user/Model/User.php:293]
#4 Magento\User\Model\User->beforeSave() called at [vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php:412]
#5 Magento\Framework\Model\ResourceModel\Db\AbstractDb->save() called at [vendor/magento/framework/Model/AbstractModel.php:655]
#6 Magento\Framework\Model\AbstractModel->save() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#7 Magento\User\Model\User\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#8 Magento\User\Model\User\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#9 Magento\User\Model\User\Interceptor->___callPlugins() called at [generated/code/Magento/User/Model/User/Interceptor.php:23]
#10 Magento\User\Model\User\Interceptor->save() called at [vendor/magento/module-user/Controller/Adminhtml/Auth/ResetPasswordPost.php:77]
#11 Magento\User\Controller\Adminhtml\Auth\ResetPasswordPost->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#12 Magento\User\Controller\Adminhtml\Auth\ResetPasswordPost\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#13 Magento\User\Controller\Adminhtml\Auth\ResetPasswordPost\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#14 Magento\User\Controller\Adminhtml\Auth\ResetPasswordPost\Interceptor->___callPlugins() called at [generated/code/Magento/User/Controller/Adminhtml/Auth/ResetPasswordPost/Interceptor.php:23]
#15 Magento\User\Controller\Adminhtml\Auth\ResetPasswordPost\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#16 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:151]
#17 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#18 Magento\User\Controller\Adminhtml\Auth\ResetPasswordPost\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#19 Magento\User\Controller\Adminhtml\Auth\ResetPasswordPost\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:145]
#20 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#21 Magento\User\Controller\Adminhtml\Auth\ResetPasswordPost\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#22 Magento\User\Controller\Adminhtml\Auth\ResetPasswordPost\Interceptor->___callPlugins() called at [generated/code/Magento/User/Controller/Adminhtml/Auth/ResetPasswordPost/Interceptor.php:32]
#23 Magento\User\Controller\Adminhtml\Auth\ResetPasswordPost\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:245]
#24 Magento\Framework\App\FrontController->getActionResponse() called at [vendor/magento/framework/App/FrontController.php:212]
#25 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:147]
#26 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#27 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#28 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#29 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#30 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#31 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#32 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]
</pre>

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by FadedOut** [comment] 2022-06-15 15:55
@stradd 

It might be that you're missing libsodium (or ext-sodium). Check to see if you have that installed as a package/php extension.

**Comment by stradd** [comment] 2022-06-15 17:20
I found the following instructions

curl -O https://download.libsodium.org/libsodium/releases/ libsodium-1.0.18..tar.gz \
   && tar xfvz libsodium-1.0.18.tar.gz \
   && cd libsodium-1.0.18 \
   && ./configure
&& make && make check
sudo make install

I ran this at root level and restarted the server. Unfortunately that was unsuccessful

**Comment by engcom-November** [comment] 2022-06-16 12:10
Verified the issue on Magento 2.4-develop branch and the issue is reproducible.
Login into admin works but login using existing customers on front end no longer works after following the steps mentioned in description. Hence confirming the issue.
![image](https://user-images.githubusercontent.com/60198231/174066759-982f63d6-18a4-4b7b-9442-12dc434f8231.png)

**Comment by FadedOut** [comment] 2022-06-17 04:06
@engcom-November 

Odd, everything works fine for me on 2.4.4. I used the same browser, logged into admin then made a new tab and logged into a customer account on the front end. 

Maybe it is only a 2.4.3-p1 & PHP 7.4.x bug. Though for OP, his error specifically mentions sodium
```
(SodiumException): unsupported password hashing algorithm
```
Which would cause login issues if not correctly installed (or is missing) on the server.

**Comment by engcom-November** [comment] 2022-06-17 05:56
Hi @FadedOut ,
It was reproducible to me on 2.4-develop branch but no exception/errors in logs were observed. I'll recheck the issue again and update the description.
Thank you.

**Comment by engcom-November** [comment] 2022-06-22 11:54
Verified the issue again on clean magento 2.4-develop instance with PHP 8.1 version but could not able to reproduce the issue. Login to both admin and frontend using existing and new customers working fine with no issues.
@stradd , please recheck the behavior on 2.4-develop branch and elaborate steps / missing configuration details if you are still facing any issues.
Thank you.

**Comment by stradd** [comment] 2022-06-22 14:04
I've now got libsodium running on Plesk.
After that, everything in the frontend and admin area worked perfectly again

**Comment by FadedOut** [comment] 2022-06-23 04:33
@stradd Glad to hear you got it sorted out - I had a feeling it was because of libsodium.

**Comment by engcom-November** [comment] 2022-06-24 05:30
Thanks for the update @stradd. We are closing this issue as cannot reproduce on 2.4-develop branch.

**Closed as completed by engcom-November** 2022-06-24 05:30 UTC
Labels: Issue:  Cannot Reproduce, Component: Login, Reproduced on 2.4.x, Issue: ready for confirmation, Issue: needs update, Area: Account, Area: UI Framework, Reported on 2.4.3-p1
