### ISSUE TITLE
Duplicate URL key on enabling 'Not visible individually' product

### ISSUE THREAD

**Issue by npluimers** [magento/magento2#35623] opened 2022-06-16 08:40 UTC
### Preconditions and environment

- 2.4.3-p1

### Steps to reproduce

1. Create a configurable product with URL key: 'test'
2. Try to create a simple product under this configurable product with Visibility: 'Not visible individually', status disabled and url key: 'test'

### Expected result

Product should be allowed to be created. as there is no URL rewrite generated due to it's visibility setting

### Actual result

Magento shows a `The value specified in the URL Key field would generate a URL that already exists.` error

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2022-06-16 10:37
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-06-16 11:52
Hello @npluimers ,
 We have tried to reproduce the issue in Magento 2.4-develop branch the issue is not reproducible.
Please refer the below screenshot for the reference; 

![Screenshot from 2022-06-16 17-17-56](https://user-images.githubusercontent.com/60198592/174063430-c761aecb-0518-47c7-89aa-a2b7514edca2.png)
We have followed the below steps in order to reproduce the issue:
1.Create a configurable product with URL key: 'test'
2.to create a simple product under this configurable product with Visibility
3.Product should be allowed to be created sucessfully.

Let us know in case we have missed anything.
Thanks.

**Comment by npluimers** [comment] 2022-06-17 06:39
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-06-22 07:05
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-06-22 11:32
@magento give me 2.4-develop instance

**Comment by npluimers** [comment] 2022-06-22 14:56
Hi @engcom-Dash, we noticed this issue in the following use case:

- We sell a number of products with the same name, but different SKU's (and different attributes).
- These products are collected under a configurable product.
- The default URL key for the parent and sub-products are the same (`test` in the example).
- When we want to enable a sub-product (with the visibility still being Not visible Individually) magento starts to complain.

In my opinion this error is invalid, since the product actually isn't available at the URL key. (And never will be as long as Not Visible individually is set)
Getting the error while changing the visibility is (in my opinion) when the error should be shown, as at that moment the URL actually will be duplicated.

**Comment by engcom-Dash** [comment] 2022-06-23 08:18
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-06-23 09:20
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-06-23 11:47
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-06-27 10:28
Hi @npluimers ,
 I agree your Opinion for this use case.But we need  Customised functionality or customised users for this use case. If you facing any Difficulties to create customised functionalities please let us know.

Thanks

**Comment by engcom-Dash** [comment] 2022-07-11 06:27
Dear @npluimers ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Comment by engcom-Dash** [comment] 2022-07-11 06:28
Dear @npluimers ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Dash** 2022-07-11 06:28 UTC
Labels: Priority: P3, Progress: done, Issue: needs update
