### ISSUE TITLE
Magento does not translate product alert mail if two stores with different languages are under the same website

### ISSUE THREAD

**Issue by sezio** [magento/magento2#23063] opened 2019-05-30 13:45 UTC
### Summary
With several stores under a same website, if the stores don't have the same language, product alert stock will send product information in the default website language. 

### Preconditions (*)
1. Magento 2.2.5

### Steps to reproduce (*)
1. Create a main store, (ie language FR) under main website
2. Create a secondary store, (ie language EN) under main website 
3. Enable product alert stock 
4. Go to a product and set a different name / description / short_description for the two stores (FR and EN)
5. Make the product out of stock
6. Create a customer account on the main storeview (FR here) 
7. Change your storeview to EN and login with the previously created customer account
6. On the product page on the EN frontend and subscribe to the stock alert 
7. Make the product in stock 
8. Alert mail should be sended

### Expected result (*)
1. In the email, product description, name, etc should be in English as we subscribed to the alert stock on the english storeview. 

### Actual result (*)
1. In the email, product description, name, etc is in French as it is the main store of the website because there is only a website_id in the alert stock table structure. By default, in the mail sender, the default store to be used is the store where the customer has been created : 

vendor/magento/module-product-alert/Model/Email.php:309
```
        if ($this->_customer->getStoreId() > 0) {
            $store = $this->_storeManager->getStore($this->_customer->getStoreId());
        } else {
            $store = $this->_website->getDefaultStore();
        }
```

**I assume the behabior is the same on magento 2.3 as the table structure has not changed**

Is it the normal behavior ? 
In my opinion, an alert should be translated at the store level, what do you think ?

Thanks

**Comment by AlexWorking** [comment] 2019-06-04 12:41
In 2.2-develop not only the name, and the descriptions are in French but the whole text of the email, while in 2.3-develop the first line of the email (right after customer's name) is in English.

**Comment by magento-engcom-team** [comment] 2019-06-04 12:42
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17202`, `MC-17203` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by wilfriedwolf** [comment] 2020-02-13 21:35
Hi, 

just found this issue after debugging a similar issue in M 2.3.1:
When using theme specific translations, the Phrase above the product images (view/frontend/templates/email/price.phtml:12) uses the the theme specific translation, the one below (view/frontend/templates/email/price.phtml:45) does not.
This is probably due to the fact, that the `\Magento\Store\Model\App\Emulation::startEnvironmentEmulation` is used in a nested way in `\Magento\ProductAlert\Block\Product\ImageProvider::getImage`, at least it works if I comment out these parts.
Maybe this is the reason also for this Issue.
If not, I might open another one.

Best regards,
Willi

**Comment by Axel29** [comment] 2021-02-12 14:40
Does anyone have a solution for that bug? Even a hotfix that could be applied via an override? Thank you!

**Comment by wanghsingchuan** [comment] 2021-03-29 09:53
Same issue in Magento 2.1.6

**Comment by ngtuan96lc** [comment] 2021-06-22 03:05
Hi everyone, 
I'm still facing the same issue on version Magento ver. 2.3.4-p2
Please investigate the issue again.

**Comment by Albinoty** [comment] 2022-09-15 10:49
Hello everyone, have we some updates about this issue ?

**Comment by sezio** [comment] 2022-09-20 14:02
I think the easiest way to solve this problem is by adding a `store_id` column in the stock and price alert tables. 
I know it modifies a core table but that's the way I fixed it when I faced this problem. 

Then, I overrided the `\Magento\ProductAlert\Controller\Add\Price` and `\Magento\ProductAlert\Controller\Add\Stock` classes to get the current `store_id` and set it in the alert. 

Once the correct store_id was saved and available, I overrided `\BodyAndMoves\ProductAlert\Rewrite\Magento\ProductAlert\Model\Email::send` (to include the `store_id` when the email sending is done) and I also overrided `Magento\ProductAlert\Model\Observer::_processPrice` and `Magento\ProductAlert\Model\Observer::_processStock` to include the correct `store_id` when the alerts are processed.

**Comment by jilvins** [comment] 2023-01-03 08:38
> I think the easiest way to solve this problem is by adding a `store_id` column in the stock and price alert tables. I know it modifies a core table but that's the way I fixed it when I faced this problem.
> 
> Then, I overrided the `\Magento\ProductAlert\Controller\Add\Price` and `\Magento\ProductAlert\Controller\Add\Stock` classes to get the current `store_id` and set it in the alert.
> 
> Once the correct store_id was saved and available, I overrided `\BodyAndMoves\ProductAlert\Rewrite\Magento\ProductAlert\Model\Email::send` (to include the `store_id` when the email sending is done) and I also overrided `Magento\ProductAlert\Model\Observer::_processPrice` and `Magento\ProductAlert\Model\Observer::_processStock` to include the correct `store_id` when the alerts are processed.

Has anyone tried this solution? Looks like stock alert table already contains column with right store_id.

**Comment by Albinoty** [comment] 2024-10-03 08:11
> > I think the easiest way to solve this problem is by adding a `store_id` column in the stock and price alert tables. I know it modifies a core table but that's the way I fixed it when I faced this problem.
> > Then, I overrided the `\Magento\ProductAlert\Controller\Add\Price` and `\Magento\ProductAlert\Controller\Add\Stock` classes to get the current `store_id` and set it in the alert.
> > Once the correct store_id was saved and available, I overrided `\BodyAndMoves\ProductAlert\Rewrite\Magento\ProductAlert\Model\Email::send` (to include the `store_id` when the email sending is done) and I also overrided `Magento\ProductAlert\Model\Observer::_processPrice` and `Magento\ProductAlert\Model\Observer::_processStock` to include the correct `store_id` when the alerts are processed.
> 
> Has anyone tried this solution? Looks like stock alert table already contains column with right store_id.

hi @jilvins, I'm working on version 2.4.7 and using the store_id column, I've managed to create a patch like this

````patch
--- Model/Mailing/AlertProcessor.php	2024-09-30 11:37:16
+++ Model/Mailing/AlertProcessor.php	2024-10-02 15:25:27
@@ -170,6 +170,7 @@
             try {
                 if ($alert->getStoreId()) {
                     $email->setStoreId($alert->getStoreId());
+                    $defaultStoreId = $alert->getStoreId();
                 }
                 if ($customer === null) {
                     $customer = $this->customerRepository->getById($alert->getCustomerId());
````

I hope you find this useful

**Comment by lucafuser** [comment] 2024-11-14 15:16
hi @engcom-Delta , this issue has already been fixed by https://github.com/magento/magento2/commit/c397d787e2aed68b9293475324d9d7b13346c588

**Comment by engcom-Bravo** [comment] 2024-12-27 03:35
Hi @lucafuser,

Thanks for your Contribution!!.

As per this comment https://github.com/magento/magento2/issues/23063#issuecomment-2476668657  issue has been fixed hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-12-27 03:35 UTC
Labels: Component: Translation, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Component: Store, Priority: P3, Severity: S3, Progress: done
