### ISSUE TITLE
Bug with success message box

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#4656] opened 2016-05-24 08:13 UTC
There is a bug when you ad a product to cart or subscribe to "alert subscription" on a product. The bug appears when you do this actions and then after hitting the button (for example "ad to cart") and then do not wait a while to completely render the message box but change quickly to another site. Then the "success message" is shown on each page. It looks like if the action is not completed at the site the message box is transferred to all other sites and shown on every site then (screen attached). 

It could not be to have for example the message "you added configurable product 102 to your shopping cart" on the site "configurable product 405" - screen 3.

Steps to reproduce
Plain install version 2.0.3., 2.0.4, 2.0.5 and 2.0.6
Magento internal FPC and also varnish version 4.x are effected
## Expected result
1. The message box is only shown on the product page related to the message
## Actual result
1. The message box is shown on all sites as long as you do not put any other product in the shopping cart and let the site render the message box completely.

![3](https://cloud.githubusercontent.com/assets/16196483/15496852/e31efdb4-2197-11e6-89a5-f26ce2db51ff.png)
![2](https://cloud.githubusercontent.com/assets/16196483/15496855/e35bbd26-2197-11e6-8c1b-fc251c9edccc.png)
![1](https://cloud.githubusercontent.com/assets/16196483/15496854/e3537a4e-2197-11e6-89b1-e39843444cdb.png)

**Comment by PieterCappelle** [comment] 2016-05-24 20:50
We're having the same problem. Magento version 2.0.7.

**Comment by jcccg2016** [comment] 2016-08-30 10:46
I also have this Problem. Magento Version 2.09

**Comment by sevos1984** [comment] 2016-09-16 07:16
This was fixed in 2.0.8. See comment https://github.com/magento/magento2/issues/4307#issuecomment-221278794. Ensure you have that code.

**Comment by sevos1984** [comment] 2016-10-03 09:40
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-10-03 09:40 UTC
Labels: bug report, Component: Customer
