### ISSUE TITLE
Making state required for country that doesn't have any regions defined in the database, doesn't work

### ISSUE THREAD

**Issue by archonkulis** [magento/magento2#10897] opened 2017-09-15 10:47 UTC
### Preconditions

1. Magento version is 2.1.6
2. I don't think PHP or Mysql versions matter

### Steps to reproduce

1. Stores -> Configuration -> General, General -> State Options
2. Select one country that has states defined in the database, e.g. "Estonia" and other one that doesn't have any states in the "directory_country_region" table, e.g. "Japan"
3. Go to check-out, and try selecting those 2 countries

### Expected result

1. In both cases it should make "State/Province" field required

### Actual result

1. Instead, it makes only that countries state field required, for whom there are states defined in the "directory_country_region" table. And if country doesn't have any states, the field is not becoming required.

For example, here is the "Estonia", for whom we have some states -> https://prnt.sc/glg0ed

And here is "Japan", which doesn't have any states, that field is no longer required -> https://prnt.sc/glg17r , although in the admin the "Japan" is selected in the "State is Required for" list.

**Comment by orlangur** [comment] 2017-09-15 11:14
Looks like a misconfiguration to me. How the customer is supposed to fill required `State/Province` field when there are no options?

**Comment by archonkulis** [comment] 2017-09-15 11:19
Doesn't look like misconfigurations to me. 

Thing is, that when there are no options, this field becomes "text-input" and not an option list ( "select" ), so user can still write something there, but "required" part is not added to that text input field.

Do you understand what I mean?

**Comment by orlangur** [comment] 2017-09-15 11:27
> so user can still write something there

Ok, I wasn't aware of such behavior, the field on screenshot looks like a disabled select rather than a text input. No objections then if Magento is able to actually save such state.

**Comment by archonkulis** [comment] 2017-09-15 11:31
> field on screenshot looks like a disabled select rather than a text input

oh, didn't notice that, but yeah, as you already understood, it's really a working text input, and not a disabled select

**Comment by pboisvert** [comment] 2017-09-16 03:17
Guessing merchants may not be reporting this issue more widely as Japan uses an inverse order on address to the default. There postcode comes first, followed by prefecture, followed by the detailed address info. Proper checkout for Japan would be customized to invert this order vs relying on default order. Likely needs some research into original decision not to use prefectures in place of state/province to keep as option list vs free form text.

**Comment by archonkulis** [comment] 2017-09-16 10:54
@pboisvert This has nothing to do with Japan. It's just an example. You can take any other country that is not listed in "directory_country_region" table and the result will be the same. As I already mentioned - this has nothing to do with the country you select and/or how they fill that form. The option that I select in the admin, is supposed to **make state text input or select field required**, but it doesn't do that for countries that aren't in the "directory_country_region" table. That's all. Do you understand?

**Comment by orlangur** [comment] 2017-09-16 12:04
> This has nothing to do with Japan

@archonkulis sure thing, I believe it's just some thinking on how real merchants use Magento and why such case was overlooked yet. Probably they were just satisfied with non-required state field.

**Comment by magento-engcom-team** [comment] 2017-09-22 16:17
@archonkulis, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-22 16:17 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Fixed in 2.2.x, Issue: Format is valid

**Comment by archonkulis** [comment] 2017-09-28 05:40
@magento-engcom-team Thanks. Could you please give me a commit ID or better a link to where it is fixed? Or ticket nr.?
