### ISSUE TITLE
Magento 2.4.5-p1 clean install array_merge() error

### ISSUE THREAD

**Issue by Sharlyll** [magento/magento2#36745] opened 2023-01-16 10:06 UTC
### Preconditions (*)

1. Magento version: 2.4.5-p1
2. tag: open source
3.  PHP: 8.1.2
4.  MySQL version: 8.1
5. Nginx: 1.18
6. OpenSearch: 2.4
7. Ubuntu 22
8. Composer 2

### Steps to reproduce (*)

1. Install all Magento prequisites according to the documentation. 
2. Configure php settings according to the prerequisites

### Expected result (*)

1. Magento should install smoothly without any error messages using composer

### Actual result (*)

1. bin/magento setup:install 
--base-url=http://123.123.123.123/ 
--db-host=localhost 
--db-name=magento 
--db-user=magento 
--db-password="U274eeGzNCqKJ2LpvtS@329" 
--admin-firstname=bob 
--admin-lastname=smith 
--admin-email=[bob@example.com](mailto:bob@example.com) 
--admin-user=bob 
--admin-password=example@123 
--language=en_US 
--currency=GBP 
--timezone=Europe/London 
--use-rewrites=1

here is the error:

here is the error:
array_merge(): Argument https://github.com/magento/magento2/pull/2 must be of type array, string given#0 /var/www/html/setup/src/Magento/Setup/Model/ConfigModel.php(157): array_merge()
https://github.com/magento/magento2/issues/1 /var/www/html/setup/src/Magento/Setup/Console/Command/InstallCommand.php(273): Magento\Setup\Model\ConfigModel->validate()
https://github.com/magento/magento2/pull/2 /var/www/html/vendor/symfony/console/Command/Command.php(221): Magento\Setup\Console\Command\InstallCommand->initialize()
https://github.com/magento/magento2/pull/3 /var/www/html/vendor/symfony/console/Application.php(1021): Symfony\Component\Console\Command\Command->run()
https://github.com/magento/magento2/issues/4 /var/www/html/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand()
https://github.com/magento/magento2/issues/5 /var/www/html/vendor/magento/framework/Console/Cli.php(116): Symfony\Component\Console\Application->doRun()
https://github.com/magento/magento2/issues/6 /var/www/html/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()
https://github.com/magento/magento2/issues/7 /var/www/html/bin/magento(23): Symfony\Component\Console\Application->run()
https://github.com/magento/magento2/issues/8 {main}

please help

**Comment by Sharlyll** [comment] 2023-01-16 22:36
Turns out the issues was passwords: no hypen allowed. It must contain numbers, upper and lower case letters. 
 slashes not allowed
and proper language and currency codes. 
E.g en_GB

**Comment by engcom-November** [comment] 2023-01-18 05:01
Hi @Sharlyll ,
Thank you for reporting and collaboration. Verified the issue by installing project-community-edition 2.4.5-p1 with the same command mentioned in the description but the issue is not reproducible. No errors were observed and 2.4.5-p1 is installed successfully. Kindly check the Magento [system requirements](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements.html) and elaborate missing configuration details if any if the issue is still reproducible.
![image](https://user-images.githubusercontent.com/60198231/213088187-b39304e7-2f4b-4c1a-9e48-5090eae3ee7e.png)

**Comment by engcom-Hotel** [comment] 2023-02-03 12:21
Dear @Sharlyll,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2023-02-03 12:21 UTC
Labels: Issue: needs update
