### ISSUE TITLE
Symbol of the Belarusian currency BYR is outdated

### ISSUE THREAD

**Issue by loid345** [magento/magento2#24713] opened 2019-09-25 01:56 UTC
### Preconditions (*)
**Magento 2.3.x**
Symbol of the Belarusian currency BYR is outdated.
Since 2016, the symbol of the Belarusian currency BYR has become obsolete and is no longer used. 
![image](https://user-images.githubusercontent.com/51680850/65577593-c07f0780-df7c-11e9-89b3-8722accec5ed.png)
![image](https://user-images.githubusercontent.com/51680850/65577670-ed331f00-df7c-11e9-90dd-c3e75e3c4a73.png)

Resources:
https://www.xe.com/currency/byr-belarusian-ruble
https://www.xe.com/currencyconverter/convert/?Amount=1&From=BYN&To=USD

### Steps to reproduce (*)
1. Login to admin
2. Go to the Stores --> Configuration--> Currency Setup
3. In Currency Options add "Belarusian Ruble(2000-2016)" to the Allowed Currencies list
4. Go to the Stores--> Currency Rates
5. Check Belarusian Ruble's currency symbol

### Expected result (*)
![image](https://user-images.githubusercontent.com/51680850/65578589-b827cc00-df7e-11e9-9d07-ca9cabf99ffb.png)

### Actual result (*)
![image](https://user-images.githubusercontent.com/51680850/65578633-d392d700-df7e-11e9-8b2c-7965e871c3d0.png)

**Comment by olivercastro** [comment] 2019-09-25 02:33
@volanar 

This is somewhat related to @johnny-longneck issue wherein the default symbol for Singapore dollar is $ instead of SGD. This seems to be an issue caused by an outdated Zend Framework library. 

You can create an "after plugin" to modify the currency symbol. 
`<type name="Magento\Framework\Locale\Currency">
<plugin disabled="false" name="Sample_Module::customcurrency" sortOrder="1" type="Sample\Module\Plugin\Magento\Framework\Locale\Currency" />
</type>`

**Comment by engcom-Charlie** [comment] 2019-09-25 07:09
Hello @volanar 
You are right. I will update the description and confirm it.

**Comment by magento-engcom-team** [comment] 2019-09-25 07:27
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20407` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment] 2019-12-12 06:30
Hi @volanar. Thank you for your report. 
The issue has been fixed in magento/magento2#25723 by @Bartlomiejsz in 2.4-develop branch
Related commit(s):
 - [9348fb818ae587d87e71d485a95592d105117e97](https://github.com/magento/magento2/commit/9348fb818ae587d87e71d485a95592d105117e97)

The fix will be available with the upcoming 2.4.0 release.

**Closed as completed by VladimirZaets** 2019-12-12 06:30 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Progress: PR Created, Component: CurrencySymbol, Fixed in 2.4.x
