### ISSUE TITLE
Object of class Magento\Framework\Phrase could not be converted to int on loading catalog product view page

### ISSUE THREAD

**Issue by ivanko-dev** [magento/magento2#35909] opened 2022-08-10 14:18 UTC
### Preconditions and environment

- Magento Enterprise 2.4.5

### Steps to reproduce

1. Set catalog/frontend/list_allow_all to 1
2. Open catalog product view page

### Expected result

Page loaded with no errors

### Actual result

Error on loading appears:
Exception #0 (Exception): Warning: Object of class Magento\Framework\Phrase could not be converted to int in /path_to_project/vendor/magento/module-catalog/view/frontend/templates/product/list/toolbar/limiter.phtml on line 26

### Additional information

Magento 2.4.5 content of vendor/magento/module-catalog/view/frontend/templates/product/list/toolbar/limiter.phtml Lines 21-28: 

```
<?php foreach ($block->getAvailableLimit() as $_key => $_limit):?>
    <option value="<?= $block->escapeHtmlAttr($_key) ?>"
        <?php if ($block->isLimitCurrent($_key)):?>
            selected="selected"
        <?php endif ?>>
        <?= $block->escapeHtml($localeFormatter->formatNumber((int) $_limit)) ?>
    </option>
<?php endforeach; ?>
```

Previous verisons:

```
<?php foreach ($block->getAvailableLimit() as $_key => $_limit) :?>
    <option value="<?= $block->escapeHtmlAttr($_key) ?>"
        <?php if ($block->isLimitCurrent($_key)) :?>
            selected="selected"
        <?php endif ?>>
        <?= $block->escapeHtml($_limit) ?>
    </option>
<?php endforeach; ?>
```
Same time in vendor/magento/module-catalog/Helper/Product/ProductList.php Lines 134-138:
```
if ($this->scopeConfig->isSetFlag('catalog/frontend/list_allow_all', ScopeInterface::SCOPE_STORE)) {
       return ($perPageValues + ['all' => __('All')]);
} else {
       return $perPageValues;
}
```
As result code in template https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/view/frontend/templates/product/list/toolbar/limiter.phtml#L26 not designed to accept value, which assigned in https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Helper/Product/ProductList.php#L135 if catalog/frontend/list_allow_all enabled

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by kamzata** [comment] 2022-08-11 00:08
+1

**Comment by StruggleSnuggl3** [comment] 2022-08-11 07:44
+1

**Comment by digitalbricklayer** [comment] 2022-08-11 12:04
+1

**Comment by aohlrogge** [comment] 2022-08-11 15:47
I'm having this same issue on Magento Community Edition as well

**Comment by qiangvei** [comment] 2022-08-12 07:02
I'm having this same issue on Magento Community Edition as well

**Comment by engcom-Echo** [comment] 2022-08-12 12:26
Hello @ivanko-dev,

Thanks for contribution and collaboration.
Please elaborate more where we can set catalog/frontend/list_allow_all to 1 and provide more information with exact steps and screenshot so that we can reproduce this issue.

Thanks

**Comment by engcom-Echo** [comment] 2022-08-12 15:17
Hello @ivanko-dev,

Thanks for contribution and collaboration.
We have found this issue is duplicate of https://github.com/magento/magento2/issues/35900. Hence we are closing the issue.

Thanks

**Closed as completed by engcom-Echo** 2022-08-12 15:17 UTC
Labels: duplicate, Reported on 2.4.5

**Comment by isaacdzca** [comment] 2022-08-26 19:54
+1

**Comment by writyou** [comment] 2022-08-30 06:19
[2022-08-30T05:45:59.812731+00:00] main.CRITICAL: Exception: Warning: Object of class Magento\Framework\Phrase could not be converted to int in /website/tt/var/view_preprocessed/pub/static/vendor/magento/module-catalog/view/frontend/templates/product/list/toolbar/limiter.phtml on line 1 in /website/tt/vendor/magento/framework/App/ErrorHandler.php:62
Stack trace:
#0 /website/enerart/var/view_preprocessed/pub/static/vendor/magento/module-catalog/view/frontend/templates/product/list/toolbar/limiter.phtml(1): Magento\Framework\App\ErrorHandler->handler()
#1 /website/enerart/var/view_preprocessed/pub/static/app/design/frontend/Enerart/tt/Magento_Catalog/templates/product/list/toolbar.phtml(1): include('...')

**Comment by elizad** [comment] 2022-09-04 21:13
1 exception(s):
Exception #0 (Exception): Warning: Object of class Magento\Framework\Phrase could not be converted to int in /var/www/html/m245/vendor/magento/module-catalog/view/frontend/templates/product/list/toolbar/limiter.phtml on line 26

Exception #0 (Exception): Warning: Object of class Magento\Framework\Phrase could not be converted to int in /var/www/html/m245/vendor/magento/module-catalog/view/frontend/templates/product/list/toolbar/limiter.phtml on line 26
<pre>#1 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:71]
#2 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/View/Element/Template.php:263]
#3 Magento\Framework\View\Element\Template->fetchView() called at [generated/code/Magento/Catalog/Block/Product/ProductList/Toolbar/Interceptor.php:401]
#4 Magento\Catalog\Block\Product\ProductList\Toolbar\Interceptor->fetchView() called at [vendor/magento/module-catalog/view/frontend/templates/product/list/toolbar.phtml:21]

**Comment by klein0r** [comment] 2022-09-21 09:56
Looks like this has been fixed in bb55549cd3016987663272e7ffe3f452c8d6e40d

I'm going to override the limiter.phtml

**Comment by sippsolutions** [comment] 2023-03-15 16:26
Patch for 2.4.5-p1:

```
--- vendor/magento/module-catalog/view/frontend/templates/product/list/toolbar/limiter.phtml
+++ vendor/magento/module-catalog/view/frontend/templates/product/list/toolbar/limiter.phtml
@@ -23,7 +23,9 @@
                     <?php if ($block->isLimitCurrent($_key)):?>
                         selected="selected"
                     <?php endif ?>>
-                    <?= $block->escapeHtml($localeFormatter->formatNumber((int) $_limit)) ?>
+                    <?= $block->escapeHtml(
+                        is_numeric($_limit) ? $localeFormatter->formatNumber((int) $_limit) : $_limit
+                    ) ?>
                 </option>
             <?php endforeach; ?>
         </select>

```

**Comment by jmilanovy** [comment] 2023-04-19 08:12
Having set this:
Set catalog/frontend/list_allow_all to 1
Products were not showing in categories.  Set it back to 0 and everything was fine
