### ISSUE TITLE
Error in configurable_variations on product export

### ISSUE THREAD

**Issue by darren-halo** [magento/magento2#14990] opened 2018-05-04 09:36 UTC
The product export completes the 'configurable_variations' field incorrectly.
Magento populates this field with the Front end label, but it requires the backend label to import correctly.

For example, it exports:
sku=test-SM,size=Small|sku=test-ME,size=Medium|sku=test-LA,size=Large|sku=test-XL,size=Extra Large

but it requires the backend value for the attribute. in this case 'small' values are SM, ME, LA, XL. so the correct output should be:
sku=test-SM,size=SM\|sku=test-ME,size=ME\|sku=test-LA,size=LA\|sku=test-XL,size=XL

Environment
1. Magento CE 2.2.3 without sample data is installed.
2. Base Magento with no customisation

### Preconditions

1.  Local environment on AMPPS, Mac
2. PHP 7.1
3. MYSQL - /Applications/AMPPS/mysql/bin/mysql  Ver 14.14 Distrib 5.6.37, for osx10.6 

### Steps to reproduce
1. Create a custom global dropdown attribute with front and backend values that are different
2. Create a Configurable product in Magento 2 Admin, using the above attribute
3. Export the product data
4. try to import the Data

### Expected result

1. Products should import

### Actual result

1. Error is given: 1. Invalid option value for attribute "size" in row(s): 1

**Comment by engcom-backlog-nickolas** [comment] 2018-07-25 10:49
Hello @darren-halo, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by engcom-Bravo** [comment] 2024-09-18 07:30
Hi @darren-halo,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.We are able to the data.

<img width="1434" alt="Screenshot 2024-09-18 at 13 00 12" src="https://github.com/user-attachments/assets/9f5386b9-59ba-4741-b1f7-70b76750f8c3">



Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-09-18 07:30 UTC
Labels: Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, help wanted, Component: ConfigurableImportExport, Reproduced on 2.4.x, Priority: P2, Severity: S2, Progress: done, Area: Catalog, Area: Import / export
