### ISSUE TITLE
Can't count right items when sort by bestsellers

### ISSUE THREAD

**Issue by clion007** [magento/magento2#25955] opened 2019-12-09 07:39 UTC
### Preconditions (*)

1. Magento version: 2.3.3
2. PHP version: 7.1.29; Apache version: 2.4.39; Mysql version: 5.7.26

### Steps to reproduce (*)

1. develop a plugin for block of product toolbar to sort product connection by sold quantity use joinleft method of Magento\Framework\DB\Select as below:

$toolbarCollection
                     ->getSelect()
                     ->joinLeft(
                        'sales_order',
                        'e.entity_id = sales_order.entity_id',
                         array('qty_ordered'=>'sales_order.total_qty_ordered'))
                    ->group('e.entity_id')
                    ->order('qty_ordered desc');

2. flush the product page, the total number of connection items display only 1, not the true number, and don't get the right pagination.

### Expected result (*)

1. fix the bug and display the true number in amount.phtml;
2. get the right pagination.

I try to fix it override the method of protected function _getSelectCountSql in file \Magento\Catalog\Model\ResourceModel\Product\Collection like below in a new module:

protected function _getSelectCountSql( ?\Magento\Framework\DB\Select $select = null , $resetLeftJoins = true )
{
$this -> _renderFilters();
$countSelect = $this -> _buildClearSelect( $select );
if ( count( $countSelect ->getPart( \Zend_Db_Select::GROUP ) ) > 0 ) {
$countSelect ->reset( \Zend_Db_Select::GROUP );
}
$countSelect -> columns( 'COUNT(DISTINCT e.entity_id)' );
if ( $resetLeftJoins ) {
$countSelect -> resetJoinLeft();
}
return $countSelect;
}

But it does not work.

### Actual result (*)

1. only get 1 item of product connection number;
2. can't get the right total page number and display the real pagination.

**Comment by magento-engcom-team** [comment] 2020-01-21 19:58
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30624` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by wagento-bhavin** [comment] 2020-02-02 05:23
#mm20in

**Comment by VladimirZaets** [comment] 2020-08-03 19:45
Hi @clion007, can you please provide more details about what you do you want to do?
Also, we don't like to use "left join" in this case because Magento support split DB functionality and those tables can be in two different DB instances and in that case we will not have the ability to use "join"

**Closed as completed** 2020-09-10 10:40 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Format is valid, Triage: Dev.Experience, Reproduced on 2.4.x, Event: mm20in, Progress: done
