### ISSUE TITLE
No way to specify cascade for onUpdate in foreign keys

### ISSUE THREAD

**Issue by maderlock** [magento/magento2#4447] opened 2016-05-10 10:05 UTC
In \Magento\Framework\DB\Ddl\TableAdapterInterface the addForeignKey method's type hints include a @param string $onUpdate, but no such parameter exists in the signature of the interface:

```
public function addForeignKey(
    $fkName,
    $tableName,
    $columnName,
    $refTableName,
    $refColumnName,
    $onDelete = self::FK_ACTION_CASCADE,
    $purge = false,
    $schemaName = null,
    $refSchemaName = null
);
```

This interface is then implemented by \Magento\Framework\DB\Adapter\Pdo\Mysql etc. and so there is no way to specify the onUpdate action, only onDelete.

Is this feature likely to be added, and/or is there a work-around for this?

**Comment by mazhalai** [comment] 2016-05-10 14:23
@maderlock closing as duplicate of #1728

**Closed as completed by mazhalai** 2016-05-10 14:23 UTC
