### ISSUE TITLE
The list of allowed countries in checkout per store won't update

### ISSUE THREAD

**Issue by prasannanwr** [magento/magento2#33343] opened 2021-06-24 13:17 UTC
### Preconditions:

1. Magento version 2.4.0 (installed via composer)
2. PHP version 7.4.8
3. MySQL 8

### Steps to reproduce (*)
1. Create multiple websites and stores.
2. Set Account Sharing Option to "Global" under System > Customer > Customer configuration
3. Update Allowed Countries Under Stores -> Configuration -> General -> Country options -> Allow countries.  on default configuration level, and for every other created website. 

### Expected result (*)
1. On the frontend particular website's Checkout page, the countries list should be updated as per the Allowed Countries updated at the backend for that website.

### Actual result (*)
1. On checkout page, it merges all website allowed countries and shows them.
![image](https://user-images.githubusercontent.com/2860968/123269294-8f9b8000-d51e-11eb-9271-61549cf36ee9.png)

---
- [ ] Severity: **S1**

**Comment by engcom-Delta** [comment] 2021-06-30 11:45
Hi @prasannanwr,
Tried to reproduce the issue on Magento version 2.4.0 with provided steps, but we are unable to reproduce it.it works as expected.

Please find the attached snapshot for reference. Kindly see if you can provide more steps to replicate the issue.
![Default_configurations_set for country](https://user-images.githubusercontent.com/51681379/123955048-c9f59900-d9c6-11eb-9182-541fcea77cde.jpg)
![checkoutPage_frontEnd](https://user-images.githubusercontent.com/51681379/123955061-d0841080-d9c6-11eb-91cd-a7606851df1c.jpg)

**Comment by Prasannastha** [comment] 2021-07-05 06:40
Hello @engcom-Delta 

1. Please create multiple websites, stores, and storeview as shown below.
![image](https://user-images.githubusercontent.com/69232506/124427213-d09b5c00-dd8a-11eb-9171-2f70a4089e10.png)

2. Configure the Allow Countries list as shown below for a store eg. France
![image](https://user-images.githubusercontent.com/69232506/124427597-50c1c180-dd8b-11eb-824e-8e1272a1dcb0.png)

3. Set Account Sharing Option to "Global" as shown below:
![image](https://user-images.githubusercontent.com/69232506/124427747-84045080-dd8b-11eb-97a0-63f942522161.png)

4. On frontend checkout of a store eg. France, all the countries are listed 
![image](https://user-images.githubusercontent.com/69232506/124427907-c037b100-dd8b-11eb-81cd-1bb3c4bd8d60.png)
But it should list only the allowed countries as shown here. It only works when we set the Account Sharing option to "Per Website".
![image](https://user-images.githubusercontent.com/69232506/124428075-f117e600-dd8b-11eb-9860-03cd6b78ce68.png)

Thank you

**Comment by engcom-Delta** [comment] 2021-07-12 11:13
Hi @prasannanwr,

I tried on Magento 2.4.2 , it is reproducible , found that more than two countries displayed in configured store.
Hence , Marking this issue as Needs update.
Followed steps:
1. Create the new Web site, store and store view
2. Set Scope to France  & set the  Allow Country options as US & UK from Store--> configuration
3. Set Account sharing options to Global
4. Launch the France Store (Front End)
5. add an item to cart & go to checkout page
6. Verify the list of countries in Shipping address page
7. observed that many countries are listed other that we set step# 2 

Kindly review my steps once.

**Comment by magento-engcom-team** [comment] 2021-07-19 09:54
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42881` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by chernenm** [comment] 2021-09-15 21:34
@magento give me 2.3-develop instance

**Comment by chernenm** [comment] 2021-09-15 21:37
@magento give me 2.3.7 instance

**Comment by engcom-Bravo** [comment] 2022-11-02 12:03
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-03 07:15
Hi @prasannanwr,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop and the issue is not reproducible.The list of allowed countries in checkout working as per configuration per store.Kindly refer the screenshots.


Steps Followed:

1.Create multiple websites and stores.
2.Set Account Sharing Option to "Global" under System > Customer > Customer configuration
3.Update Allowed Countries Under Stores -> Configuration -> General -> Country options -> Allow countries. on default configuration level, and for every other created website.


<img width="1455" alt="Screenshot 2022-11-02 at 5 53 00 PM" src="https://user-images.githubusercontent.com/51680745/199664868-f1ba21f0-48e6-44f5-ba79-84a13a0d7d38.png">




<img width="884" alt="Screenshot 2022-11-02 at 5 52 40 PM" src="https://user-images.githubusercontent.com/51680745/199664953-3e80edeb-f7f4-4779-b250-ae9bfe84291d.png">




Kindly recheck the issue on latest Magento 2.4-develop instance and Please let us know if you are still facing any issue.


Thanks.

**Comment by engcom-Bravo** [comment] 2022-11-17 06:14
Hi @prasannanwr,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-11-17 06:14 UTC
Labels: Component: Checkout, Issue:  Cannot Reproduce, Reproduced on 2.4.x, Priority: P1, Progress: done, Issue: needs update, Reported on 2.4.0, Reproduced on 2.4.2

**Comment by lbajsarowicz** [comment] 2023-04-06 12:30
@qsolutions-pl Remember to provide the reason for reopening : )

**Comment by simonmaass** [comment] 2024-07-18 14:28
this still exists in 2.4.7

**Comment by engcom-Delta** [comment] 2024-07-23 10:00
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment] 2024-07-23 13:33
Hi @prasannanwr,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop and the issue is not reproducible.The list of allowed countries in checkout working as per configuration per store.Kindly refer the screenshots.

**Steps to Reproduce** 
1. User should create multiple websites and stores.
![image](https://github.com/user-attachments/assets/727a1948-1b51-4b69-95c1-7cc304a46a79)
2. Set list of countries for each website.
 e.g. France Website
![image](https://github.com/user-attachments/assets/834496db-778e-48b2-9026-7013e7396894)
 e.g. Default Website
3. Set Account sharing option to global.
![image](https://github.com/user-attachments/assets/79cf5140-50a8-4f2d-ab42-275ac449bf3d)
4. Save config and clear cache.
5. Access frontend and navigate to checkout.
6. Observe list of country is displaying as expected.
France
<img width="778" alt="france" src="https://github.com/user-attachments/assets/01c9c8be-7943-494f-8deb-1c6c97a84d4e">
Global
<img width="838" alt="default" src="https://github.com/user-attachments/assets/ac28953d-5388-41cf-8b79-f3683d2aa663">

Kindly recheck the issue on latest Magento 2.4-develop instance and Please let us know if you are still facing any issue.

Thanks.
