### ISSUE TITLE
Bundle Creditmemo zero quantity bug

### ISSUE THREAD

**Issue by josephmcdermott** [magento/magento2#12074] opened 2017-11-07 10:22 UTC
### Summary (*)
There is a bug when creating a creditmemo for a bundle product when all of its parts are set to 0 quantity. This can become an issue when you only want to refund the shipping of a bundle-only order, since rather than refunding the shipping the entire order is refunded.

For mixed bundle and other product type orders, the behaviour is as expected in the resulting creditmemo, however the UI is impacted since the bundle product completely disappears when changing its quantities to 0.

### Preconditions (*)
Issue occurs on vanilla Magento 2.2.x & 2.3.x, no other preconditions.
Magento 2.4-develop

### Steps to reproduce (*)
- add to cart a bundle product with at least 2 parts/products
- place the order ensuring some shipping fee is included
- in the admin panel fully invoice the order
- next click on create credit memo
- update 'Qty to Refund' to 0 for all parts of the bundle
- click on 'Update Qty's' button
- note that the entire items to refund section has disappeared
![refund](https://user-images.githubusercontent.com/51680850/70522917-a8199480-1b4a-11ea-891d-50df436888ff.png)
- click on the main 'Refund' or 'Refund Offline' button
- the refund amount should have been just the shipping, however the entire order is refunded

### Expected result (*)
- Bundle product should not disappear when setting all of its parts to 0 on creating a creditmemo.
- When raising a creditmemo for a bundle-only order for just the shipping amount, the resulting refunded value should match the shipping amount only, not the shipping + bundle product value.

### Actual result (*)
The opposite of the expected results.
Credit memo with all items:
![memo](https://user-images.githubusercontent.com/51680850/70523011-c7b0bd00-1b4a-11ea-9b3c-5d9749b37269.png)

**Comment by magento-engcom-team** [comment] 2017-11-07 11:31
@josephmcdermott, thank you for your report.
We've created internal ticket(s) MAGETWO-83375 to track progress on the issue.

**Comment by josephmcdermott** [comment] 2017-11-08 10:18
Thanks for creating a ticket on this and I look forward to progress updates.

It appears as though the issue stems from `\Magento\Sales\Model\Order\CreditmemoFactory::canRefundItem` where the `$qtys` variable contains `0` for all of the children (because the intention is not to refund any of the Bundle parts), so as a result the Bundle parent item becomes _non-refundable_ and is therefore not included in the creditmemo form.

**Stack / Flow:**
- `\Magento\Sales\Controller\Adminhtml\Order\CreditmemoLoader::load`
- `\Magento\Sales\Model\Order\CreditmemoFactory::createByOrder`
- `\Magento\Sales\Model\Order\CreditmemoFactory::canRefundItem`
- `canRefundItem()` returns `FALSE` for the Bundle parent
- `$creditmemo->addItem($item);` is not called for the Bundle parent
- as a result, the Bundle product is omitted from the form data, causing it do _disappear_

That is the cause, but the solution I am struggling with due to not fully understanding the business logic around `canRefundItem` and why it needs to check for qty of children at all. My assumption being this is used elsewhere in the code. Perhaps you could shed some light on that?

**Comment by karlsminton** [comment] 2018-03-28 12:09
@magento-engcom-team we're also experiencing this issue - is there an update on this?

**Comment by karlsminton** [comment] 2018-04-05 08:45
@magento-engcom-team @magento is it possible to get a response on this?

**Comment by vtimonin** [comment] 2018-10-30 17:29
It seems `CreditmemoFactory::canRefundItem` method has an unnecessary `$qtys[$child->getId()] > 0` condition, probably copy-pasted from `InvoiceService::_canInvoiceItem` method - I don't see why it is needed there.

**Comment by magento-engcom-team** [comment] 2019-12-10 10:45
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29612` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Delta** [comment] 2020-11-04 14:28
Hi @josephmcdermott I rechecked issue and it is not reproducible on latest 2.4-develop
**Manual testing scenario:**
_Case 1:_
- Create bundle product with dynamic price and two dropdown options
![#12074BunleDynamic1](https://user-images.githubusercontent.com/51681379/98122125-d4ec3e00-1eb8-11eb-8b93-6b61fca3aa9e.png)
![#12074BundleDynamic2](https://user-images.githubusercontent.com/51681379/98122130-d74e9800-1eb8-11eb-8a46-1d3f52e38865.png)
- Add to cart a bundle product
- Place the order ensuring some shipping fee is included 
- Create invoice for order in admin panel
- Next click on create credit memo
- Update 'Qty to Refund' to 0 for all options of the bundle
- Click on 'Update Qty's' button
- Cick on the 'Refund Offline' button
:heavy_check_mark: The refund amount is created for the shipping, bundle product is not refunded
![BundleDynamic](https://user-images.githubusercontent.com/51681379/98122334-1bda3380-1eb9-11eb-9d31-da34731af0e5.gif)

_Case 2:_
- Create bundle product with dynamic price and two dropdown options
![#12074BundleStatic1](https://user-images.githubusercontent.com/51681379/98123070-129d9680-1eba-11eb-8421-49984d7d7bc9.png)
![#12074BundleStatic2](https://user-images.githubusercontent.com/51681379/98123076-14675a00-1eba-11eb-86ed-8f5c622bcf49.png)
- Add to cart a bundle product
- Place the order ensuring some shipping fee is included 
- Create invoice for order in admin panel
- Next click on create credit memo
- Update 'Qty to Refund' to 0 for the bundle product
- Click on 'Update Qty's' button
- Cick on the 'Refund Offline' button
:heavy_check_mark: The refund amount is created for the shipping, bundle product is not refunded
![BundleStatic](https://user-images.githubusercontent.com/51681379/98123031-074a6b00-1eba-11eb-86bb-ca059fb62dc6.gif)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Delta** 2020-11-04 14:28 UTC
Labels: Component: Sales, Issue:  Cannot Reproduce, Progress: done, not-confirmed

**Comment by magento-engcom-team** [comment] 2021-02-17 10:58
Hi @josephmcdermott, @engcom-Delta. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-29612` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.
