### ISSUE TITLE
For the MSI magento 2 store, While  downlaoding  prodcut by  sku  using  below  request and response we are getting  the  cost in the custom attribute which is the cost displayed over the catalog page. Is there  any  possibility or the api  from  where we will get the  cost of  all the website  along  with  the  particular store ?

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#38377] opened 2024-01-24 14:00 UTC
### Preconditions and environment

- Magento version ->   2.3.0

### Steps to reproduce

Download the  product by sku  

Request URL -> 
http://php72.webgility.com/magento230_test/rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=sku&searchCriteria[filter_groups][0][filters][0][value]=Asus_Laptop&searchCriteria[filter_groups][0][filters][0][condition_type]=in

### Expected result

The cost  of the different website should appear along  with the store id

### Actual result

The  cost   which appearing under the  custom attribute is appearing  , is the  cost  which is  displayed over the catalog page

check the attached  response -> 
{
    "items": [
        {
            "id": 282,
            "sku": "Asus_Laptop",
            "name": "Asus Laptop",
            "attribute_set_id": 4,
            "price": 99,
            "status": 1,
            "visibility": 4,
            "type_id": "simple",
            "created_at": "2023-10-10 13:40:48",
            "updated_at": "2024-01-22 11:01:29",
            "extension_attributes": {
                "website_ids": [
                    1,
                    2,
                    3,
                    4,
                    5,
                    6
                ]
            },
            "product_links": [],
            "options": [],
            "media_gallery_entries": [],
            "tier_prices": [],
            "custom_attributes": [
                {
                    "attribute_code": "url_key",
                    "value": "asus-laptop"
                },
                {
                    "attribute_code": "special_price",
                    "value": "262.0000"
                },
                {
                    "attribute_code": "gift_message_available",
                    "value": "2"
                },
                {
                    "attribute_code": "manufacturer",
                    "value": "37"
                },
                {
                    "attribute_code": "create",
                    "value": "35"
                },
                {
                    "attribute_code": "meta_title",
                    "value": "Asus Laptop"
                },
                {
                    "attribute_code": "special_from_date",
                    "value": "2023-11-08 00:00:00"
                },
                {
                    "attribute_code": "options_container",
                    "value": "container2"
                },
                {
                    "attribute_code": "cost",
                    "value": "599.0000"
                },
                {
                    "attribute_code": "meta_keyword",
                    "value": "Asus Laptop"
                },
                {
                    "attribute_code": "vendor",
                    "value": "32"
                },
                {
                    "attribute_code": "meta_description",
                    "value": "Asus Laptop "
                },
                {
                    "attribute_code": "tax_class_id",
                    "value": "2"
                },
                {
                    "attribute_code": "required_options",
                    "value": "0"
                },
                {
                    "attribute_code": "has_options",
                    "value": "0"
                },
                {
                    "attribute_code": "category_ids",
                    "value": []
                }
            ]
        }
    ],
    "search_criteria": {
        "filter_groups": [
            {
                "filters": [
                    {
                        "field": "sku",
                        "value": "Asus_Laptop",
                        "condition_type": "in"
                    }
                ]
            }
        ]
    },
    "total_count": 1
}

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-02-01 05:56
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-02-01 07:50
Hi @webgility-amazonapi,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

![Screenshot from 2024-02-01 12-11-11](https://github.com/magento/magento2/assets/51680745/ada5f6e0-ebe7-4a82-874e-a7b7b1107526)




![Screenshot from 2024-02-01 12-11-39](https://github.com/magento/magento2/assets/51680745/8ee6e185-df59-40b5-8295-f7218a9623a3)



We are able to get the price from the different websites.we have used store code in the url for different websites.

Could you please refer this document https://developer.adobe.com/commerce/webapi/rest/quick-reference/ and please let us know if we are still facing any issue.

Thanks.

**Comment by engcom-Dash** [comment] 2024-02-19 07:26
Hi @webgility-amazonapi 

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Dash** 2024-02-19 07:26 UTC
Labels: Issue: needs update, Reported on 2.3.0
