### ISSUE TITLE
Even after deleting new theme still its showing in drop down

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1596] opened 2015-07-31 17:38 UTC
![theme appear](https://cloud.githubusercontent.com/assets/7636894/9013361/fbcaffa6-37d8-11e5-85cb-466976974e6f.png)

**Comment by sivajik34** [comment] 2015-07-31 17:46
i created new theme based on parent theme luma.i enabled my theme.but in front end styles are missing.i deleted cache and i checked no luck.after that i deleted my  newly created theme files.but the theme title still showing in drop down.

**Comment by vpelipenko** [comment] 2015-08-11 11:14
hi @sivajik34, it is known issue. It will be fixed when in time of re-working theme management. This task exists in Magento 2 product backlog. As workaround you can remove this record directly from 'theme' table in database.

**Comment by vpelipenko** [comment] 2015-08-11 11:15
Internal ticket: MAGETWO-46231

**Comment by buskamuza** [comment] 2015-08-12 17:52
Hi @sivajik34 ,

you can also use `bin/magento theme:uninstall` command to uninstall a theme. It removes a record from DB when uninstalling a theme. But it will terminate if the theme is in use requiring an action from the user (e.g., going to Admin Panel and selecitng another theme).

**Comment by magento-engcom-team** [comment] 2017-09-19 22:05
Internal ticket has been closed as not a bug

**Closed by magento-engcom-team** 2017-09-19 22:05 UTC
Labels: acknowledged, bug report, G1 Failed
