### ISSUE TITLE
Wrong invoice prefix in multistore setup due to default store id

### ISSUE THREAD

**Issue by shinesoftware** [magento/magento2#14063] opened 2018-03-12 16:04 UTC
### Preconditions
Ubuntu, Standard LAMP (Apache, MySQL, ....)
Magento ver. 2.1.9 - Clean setup by command line
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
mysql Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using EditLine wrapper

#### Magento Store Configuration
The magento store has been configured as multistore with multiviews.

- Store A
    - Store View Italian (default) - **id:1** - invoice prefix: S-
    - Store View English - **id:3** - invoice prefix: SS-
- Store B
    - Store View Italian (default) - **id:2** - invoice prefix: Z-
    - Store View English - **id:4** - invoice prefix: ZZ-

I have discovered that Magento 2 set the **DefaultStoreId** in the second **getSequence()** parameter but this is not good if you need to set a correct prefix for the invoices. Look at https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Sales/Model/ResourceModel/EntityAbstract.php#L129  

If create an order from the administration panel for the Store B English Store View you'll get the Default Store Id equals to 2 but the correct value is 4.

### Expected result
I would like to set the correct invoice prefix when I try to create a new invoice from a specific store view.

### Actual result
Magento creates the invoice number using the default store view id 

I suggest to change the storeid parameter:

    protected function _beforeSave(\Magento\Framework\Model\AbstractModel $object)
    {
        /** @var \Magento\Sales\Model\AbstractModel $object */
        if ($object instanceof EntityInterface && $object->getIncrementId() == null) {
            $object->setIncrementId(
                $this->sequenceManager->getSequence(
                    $object->getEntityType(),
                    $object->getStore()->getId() // <<< This parameter will be get from the invoice object
                )->getNextValue()
            );
        }
        parent::_beforeSave($object);
        return $this;
    }

thanks

**Comment by magento-engcom-team** [comment] 2018-03-13 09:30
@shinesoftware, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by sanjay-wagento** [comment] 2018-05-19 04:38
I am working on this at #dmcdindia

**Comment by sidolov** [comment] 2018-06-05 07:30
Hi @shinesoftware. Thank you for your report. 
The issue has been fixed in magento/magento2#15665 by @vgelani in 2.3-develop branch
Related commit(s):
 - [d5c395295aa59d8d42e12dca82ec933bad096668](https://github.com/magento/magento2/commit/d5c395295aa59d8d42e12dca82ec933bad096668)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment] 2018-11-15 13:10
Hi @TomashKhamlai. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by TomashKhamlai** [comment] 2018-11-15 13:12
The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.

**Closed as completed** 2018-11-15 13:12 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, good first issue, Progress: PR Created, Event: dmcdindia
