### ISSUE TITLE
Review Paypal transaction in paypal from order page link - Bad Url

### ISSUE THREAD

**Issue by rob-gonz** [magento/magento2#12534] opened 2017-12-04 08:36 UTC
If a customer has paid with paypal a link is provided at the bottom of the order page. Clicking the transaction id leads you to paypal, but the URL is bad.

### Preconditions

1. Paypal Express Payment
2. Magento 2.1.10

### Steps to reproduce

1. Place order and pay with Paypal Express 
2. Go to Sales -> Orders -> Select order
3.  Scroll to bottom and click Transaction ID: "[click transaction ID here]"

### Expected result

1. To be taken to paypal to view the transaction details.

### Actual result

1. Improper url is generated for the link.  The link attempts to link to 'https://www..paypal.com' (notice the double '.')

**Comment by magento-engcom-team** [comment] 2017-12-04 09:30
@THEANONYMOU5, thank you for your report.
The issue is already fixed in 2.2.1

**Closed as completed by magento-engcom-team** 2017-12-04 09:30 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Fixed in 2.2.x, Issue: Format is valid
