### ISSUE TITLE
Update to 2.4.4 not working

### ISSUE THREAD

**Issue by chequille** [magento/magento2#35289] opened 2022-04-12 21:48 UTC
Tried to update to 2.4.4 but do get the following Problem:

  Problem 1
    - The requested package magento/product-community-edition 2.4.4 exists as magento/product-community-edition[2.4.3] but these are rejected by your constraint

Any idea why?
Best regards,
Chequille

**Comment by chequille** [comment] 2022-04-14 21:34
Hi @sdzhepa,
ok, more infos.
I am on 2.4.3 Open Source and want to update to 2.4.4 Open Source.
Normally, I just change the version in composer.json to the one I need:
```
	"require" : {
		"magento/product-community-edition" : "2.4.4",
```
This worked in the past for other updates like 2.4.2 to 2.4.3 f.e.
But now I get this error.
I had as well a look to the "Perform an Upgrade" pages and I tried the command to get all available versions:
`composer show magento/product-community-edition 2.4.* --available | grep -m 1 versions
`
This shows an error and I had to change --available to --all. This results in:
![grafik](https://user-images.githubusercontent.com/15807794/163480039-851c96b6-fba5-4e40-95bb-ab8c7e3048ec.png) 

Tried as well to update the composer-root-plugin, but this did as well not work.

Any ideas? Coud it be maybe some access rights? My auth.json is on the directory var/composer-home

Looking forward to hearing from you
Best regards,
chequille

**Comment by engcom-November** [comment] 2022-04-18 10:09
Hi @chequille ,
Thank you for reporting and collaboration. Verified the issue by upgrading from 2.4.3 to 2.4.4 with the help of [Reference guide](https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/implementation/perform-upgrade.html) but cannot able to reproduce the issue. Successfully upgraded to 2.4.4 and able to access all pages.
`> composer require magento/product-community-edition 2.4.4 --no-update
> composer update
`
Kindly refer the upgrade guides [](https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/prepare/prerequisites.html?lang=en) and elaborate the issue if you are still facing issues.
Thank you.

**Comment by chequille** [comment] 2022-04-20 04:46
Hi Guys,

maybe I have an idea why it is not working on my site.
My site was originally installed with the web installation and not with a composer project.
As I remember it was version 2.3.1 or around that version.
All updates, as well to 2.4.x worked with the way I said by setting the version in the composer file.
But now it seems not to work anymore and I guess this is because of the need of the new composer-root-plugin which I cannot update.
I tried to install as described in the upgrade guides but it is not working.

Of course if you tried it with an installation made with composer, you cannot reproduce my problem.
Maybe this information gives you a hint what could be wrong on my site and what I could do to get it working.

Best regards,
Chequille

**Comment by hostep** [comment] 2022-04-27 13:25
@chequille: setup a vanilla Magento 2.4.4 installation on your local machine or something and take a look at the `composer.json` file that gets created. Here's how it looks on my machine:

```json
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "config": {
        "allow-plugins": {
            "dealerdirect/phpcodesniffer-composer-installer": true,
            "laminas/laminas-dependency-plugin": true,
            "magento/*": true
        },
        "preferred-install": "dist",
        "sort-packages": true
    },
    "version": "2.4.4",
    "require": {
        "magento/product-community-edition": "2.4.4",
        "magento/composer-dependency-version-audit-plugin": "~0.1",
        "magento/composer-root-update-plugin": "~2.0"
    },
    "autoload": {
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ],
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "psr-0": {
            "": [
                "app/code/",
                "generated/code/"
            ]
        },
        "psr-4": {
            "Magento\\": "app/code/Magento/",
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/"
        }
    },
    "require-dev": {
        "allure-framework/allure-phpunit": "~1.5.0",
        "dealerdirect/phpcodesniffer-composer-installer": "^0.7.0",
        "friendsofphp/php-cs-fixer": "~3.3.0",
        "lusitanian/oauth": "~0.8.10",
        "magento/magento-coding-standard": "*",
        "magento/magento2-functional-testing-framework": "^3.7",
        "pdepend/pdepend": "~2.10.0",
        "phpmd/phpmd": "^2.9.1",
        "phpstan/phpstan": "~1.2.0",
        "phpunit/phpunit": "~9.5.0",
        "sebastian/phpcpd": "^6.0.3",
        "squizlabs/php_codesniffer": "~3.6.0",
        "symfony/finder": "^5.2"
    },
    "conflict": {
        "gene/bluefoot": "*"
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\PhpStan\\": "dev/tests/static/framework/Magento/PhpStan/",
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/"
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true,
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "extra": {
        "magento-force": "override"
    }
}
```

Then compare that file with your own file and try to figure out which changes from your file you need to take over to that other file (or vice-versa) to include all your other dependencies or configurations that you need, and try to fix your `composer.json` file that way.

Usually new Magento versions come with more changes in the `composer.json` file than only the `magento/product-community-edition` version, this could potentially explain - in case you forgot to apply previous changes in older updates - why you got in the trouble that you are now.

**Comment by engcom-November** [comment] 2022-05-16 05:30
Hi @chequille ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing issues.
Thank you.

**Closed as completed by engcom-November** 2022-05-16 05:30 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.4
