### ISSUE TITLE
Product goes out of stock when allow backorder is set to true

### ISSUE THREAD

**Issue by web4exposure-org** [magento/magento2#33321] opened 2021-06-22 15:12 UTC
### Preconditions (*)

1. 2.4.2
2. Product is in stock
3. manage stock is enabled
3. qty of product is 0

### Steps to reproduce (*)

1. Product is sold
2. (?) reindex

### Expected result (*)

1. Product is still in stock

### Actual result (*)

1. Product is updated to out of stock

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by web4exposure-org** [comment] 2021-06-22 15:13
@magento give me 2.4-develop instance

**Comment by web4exposure-org** [comment] 2021-06-22 15:46
@magento give me 2.4-2 instance

**Comment by web4exposure-org** [comment] 2021-06-22 16:17
@engcom-November I am looking into this, as it is not certain I can reproduce the bug on a clean install. I hope this is not a problem. The pre-conditions are unclear as of now.

**Comment by engcom-November** [comment] 2021-06-23 08:51
Hi @web4exposure-org ,
I verified the issue on Magento 2.4-develop version and the issue is not reproducible with above preconditions.
Steps performed:
1.Admin Global Configuration - Manage Stock is enabled (Stores - Configuration - Catalog - Inventory - Product Stock Option - Manage Stock  - Set to Yes)
2. Enable Back orders - Allow Quantity below 0 and Notify Customers (Stores - Configuration - Catalog - Inventory - Product Stock Option - Back Orders)
3. Catalog - Products - Edit Product - Advanced Inventory - Verify the configuration of Manage Stock and Back orders, Stock Status is - In Stock
4. Set Quantity to 0 and save
5. Navigate to Magento Front End and Add the product to cart - Checkout - Place Order
User is able to place the order and the product is still displayed as In-Stock only.
Reindex and tried to place the order multiple times but the issue is not reproducible. User is able to place the order multiple times and quantity is updated in Admin as expected.
![image](https://user-images.githubusercontent.com/60198231/123066731-f5f4a580-d42d-11eb-96c1-90eeba650a4d.png)
![image](https://user-images.githubusercontent.com/60198231/123066937-250b1700-d42e-11eb-99e3-0b954db182c7.png)
Quantity and Stock Status is displayed as expected in Admin after placing order multiple times: 
![image](https://user-images.githubusercontent.com/60198231/123067022-3b18d780-d42e-11eb-85e1-1915409b494e.png)

**Comment by engcom-November** [comment] 2021-07-07 10:09
@web4exposure-org,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed** 2021-07-07 10:09 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.2
