### ISSUE TITLE
Pagination issue: added page with no products

### ISSUE THREAD

**Issue by jtw372** [magento/magento2#7923] opened 2016-12-22 04:31 UTC
Summary of issue: 

Categories with products that have pagination are showing an extra page...when clicking on that extra page it is showing content and no products. 
http://www.evernote.com/shard/s383/sh/0886f826-25f4-4215-b0c9-9048c78bf05c/57acbc38dbd69efa374cb9093a9eb1e5

### Preconditions

1. Magento 2.1.2
2. php 7.0.14

### Steps to reproduce

1. Go to this category page: http://104.236.239.155/doorbells/buttons/wired-buttons
2.  Click on pagination for page 2..it works as it should
3.  There should not be a page 3.  When you click it the page with no products loads.

### Expected result

1.  There should only be the number of pages that have products on them.
2.  No forward arrow or extra page when products exhausted on current page

### Actual result

1. Initial category page: http://www.evernote.com/shard/s383/sh/5ca6d812-a9f7-448c-8c7f-91cbbc92621e/ab3ee7fe76f69d0bb7b907c8899eaad0
2.  Page 3 clicked: http://www.evernote.com/shard/s383/sh/5ca6d812-a9f7-448c-8c7f-91cbbc92621e/ab3ee7fe76f69d0bb7b907c8899eaad0

**Comment by veloraven** [comment] 2016-12-22 07:32
@jtw372 thank you for your report.
I'm closing this issue as a duplicate of #6841.
If you think it to be different issue, please fill free to create new GitHub issue with additional information.

**Closed as completed by veloraven** 2016-12-22 07:32 UTC
