### ISSUE TITLE
Plugin runs twice when is attached to decorated class

### ISSUE THREAD

**Issue by madonzy** [magento/magento2#32469] opened 2021-03-12 15:41 UTC
### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Create a decorated  class for  CustomerRepository
2. Add  preference for your new decorated class
2. Override method `get()`

### Expected result (*)

1. Plugins assigned to get() method  would be fired once

### Actual result (*)

1. Plugins assigned to get() method are fired twice

**Comment by Usik2203** [comment] 2021-03-15 17:09
@magento give me 2.4-develop instance

**Comment by hostep** [comment] 2021-06-02 11:55
Leaving comment so Stalebot doesn't auto close the issue.

This sounds like something that needs to be reviewed as it can be quite important. Maybe @Den4ik can help?

**Comment by Den4ik** [comment] 2021-06-03 12:28
@madonzy Described issue don't reproduced on 2.4-develop branch.

I followed next steps:
1. Create decorator for CustomerRepository
2. Create preference for decorator
3. Create plugin for original class with `aroundGet` method
4. Make object via ObjectManager for decorator class
5. Call `get` method

**Actual Result**
![2021-06-03-15-24-12@2x](https://user-images.githubusercontent.com/1129623/120644659-40fb4880-c480-11eb-98f0-c9bf1b401aa9.jpg)

Please feel free update issue with more details and reopen it.

**Comment by madonzyaccenture** [comment] 2021-06-04 08:52
@Den4ik first of all, the Magento version is 2.3.3. Could you please the code that you tested on?

**Comment by Den4ik** [comment] 2021-06-09 10:22
@madonzyaccenture Same result on 2.3.3

[Magenius_Decorator.tar.gz](https://github.com/magento/magento2/files/6622998/Magenius_Decorator.tar.gz)

**Comment by madonzyaccenture** [comment] 2021-06-10 09:44
@Den4ik what you've done is not the decorator, but generalization...

You can learn this pattern here: https://designpatternsphp.readthedocs.io/en/latest/Structural/Decorator/README.html

**Comment by madonzyaccenture** [comment] 2021-06-10 10:39
@Den4ik please reopen issue

**Comment by Den4ik** [comment] 2021-06-10 11:43
Described situation reproduced with next module [Magenius_Decorator.tar.gz](https://github.com/magento/magento2/files/6630826/Magenius_Decorator.tar.gz). For reproducing just open `{base_url}/magenius`

Plugin called twice because it's assigned to interface and we have 2 objects that implement same interface

After discussing in slack with @madonzyaccenture his main goal (if I understood correctly) is:
Plugins should not be called for original class if this class has preference.
As result plugin interceptors should be generated only for classes that override exist class/interface and described as preference in di.

**Comment by magento-engcom-team** [comment] 2021-06-10 11:44
:white_check_mark: Confirmed by @Den4ik 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42615` were created

**Issue Available**: @Den4ik, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Den4ik** [comment] 2021-06-10 11:50
In my opinion it make since, but could faced with unexpected behaviour when we have decorator and another custom module with injection of direct class

@gabrieldagama Could you please assist forward this question to discuss with other developers and architects?

**cc** @ihor-sviziev

**Closed as completed** 2021-09-24 07:37 UTC
Labels: Issue: Confirmed, Component: Interception, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P1, Progress: done, Reported on 2.3.x, Area: Account

**Comment by ihor-sviziev** [comment] 2021-09-24 07:44
@gabrieldagama @sidolov @sivaschenko, why this issue was closed w/o any comments?

**Comment by Den4ik** [comment] 2021-09-24 07:49
Is it fixed?

**Comment by engcom-Lima** [comment] 2021-09-24 07:59
Hi @ madonzy,

In the module magenius used to reproduce the issue, method 'get' is called twice (1 by CustomerRepositoryDecorate.php class and another by Magento/Customer/Model/ResourceModel/CustomerRepository.php class). 
Hence, as plugins are attached to methods it is getting called twice. Once we removed 'get' call to CustomerRepository from CustomerRepositoryDecorate.php 'get' method, plugin was called once only. 

Even though class preference is given in di.xml, plugins are attached to methods and gets called every time the method with that name(Observed method) gets called. Hence closing this ticket as non-issue. Please reopen the ticket for any concerns.

Thanks

**Comment by ihor-sviziev** [comment] 2021-09-24 08:01
@engcom-Lima,
Thank you for the clarification on why it was closed.
In the future, it would be great to write a comment and then close the issue to prevent such confusion.
