### ISSUE TITLE
\Magento\Checkout\Observer\SalesQuoteSaveAfterObserver fails to update the checkout session quote id when applicable

### ISSUE THREAD

**Issue by dhayakawa** [magento/magento2#19424] opened 2018-11-27 22:52 UTC
### Preconditions (*)

1. Magento version 2.2.6
2. Magento version 2.3-develop

### Steps to reproduce (*)

1. In your favorite editor, open class file: \Magento\Checkout\Observer\SalesQuoteSaveAfterObserver

### Expected result (*)

1. To update the checkout session quote id, line 35 should be: $this->checkoutSession->setQuoteId($quote->getId());

### Actual result (*)

1. The checkout session quote id is not updated due to line 35 which incorrectly calls $this->checkoutSession->getQuoteId($quote->getId());
2. I'm not sure if this should go here but the unit test for this observer \Magento\Checkout\Test\Unit\Observer\SalesQuoteSaveAfterObserverTest::testSalesQuoteSaveAfter() does not reveal the error because it is also incorrect and expects the getQuoteId method to be called. Line 39: $this->checkoutSession->expects($this->once())->method('getQuoteId')->with(7);

**Comment by magento-engcom-team** [comment] 2018-11-27 22:52
Hi @dhayakawa. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dhayakawa do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-11-27 22:56
Hi @dmytro-ch. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2018-11-27 23:00
@dmytro-ch Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96695`, `MAGETWO-96696` were created

**Comment by subbu1993** [comment] 2018-11-27 23:02
@magento-engcom-team Please give me 2.1.15 instance

**Comment by magento-engcom-team** [comment] 2018-12-07 16:16
Hi @dhayakawa. Thank you for your report. 
The issue has been fixed in magento/magento2#19425 by @dmytro-ch in 2.3-develop branch
Related commit(s):
 - [4d3347c78da87dac832e72b896ca23485b1a508e](https://github.com/magento/magento2/commit/4d3347c78da87dac832e72b896ca23485b1a508e)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2018-12-07 16:16 UTC
Labels: Issue: Ready for Work, Component: Checkout, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by magento-engcom-team** [comment] 2018-12-10 17:10
Hi @dhayakawa. Thank you for your report. 
The issue has been fixed in magento/magento2#19678 by @dmytro-ch in 2.2-develop branch
Related commit(s):
 - [fc56b80ba8a0ebbc59054b29dc6ab13efdc76a29](https://github.com/magento/magento2/commit/fc56b80ba8a0ebbc59054b29dc6ab13efdc76a29)

The fix will be available with the upcoming 2.2.8 release.
