### ISSUE TITLE
Tier price saving percentage wrong when VAT is included in price

### ISSUE THREAD

**Issue by martinhetschel** [magento/magento2#8833] opened 2017-03-09 14:28 UTC
### Preconditions

Magento ver. 2.1.5, Luma theme

### Steps to reproduce

1. Store->Configuration->Sales->Tax->Catalog Prices: including tax
2. Article Price 16€
3. Tier Price 13.60€ for 10 pieces

### Expected result

1.  Frontend should show:
Buy 10 for €13.60 each and save 15%

### Actual result

1.  Frontend shows instead:
Buy 10 for €13.60 each and save 29%
![image](https://cloud.githubusercontent.com/assets/17616012/23754327/d80c8b2a-04dc-11e7-9019-67538b73a32b.png)

**Comment by PGLDK** [comment] 2017-03-10 09:30
2.1.4
Same error.
The % is calculated by the difference between normal price incl. vat, and the tier price ex. vat, 
that adds the difference in the vat to the % saved.

It should be calculated by the difference between ex. vat / ex. vat or incl. vat / incl. vat.

**Comment by martinhetschel** [comment] 2017-03-10 09:40
Evaluated a bit...

In: magento2/app/code/Magento/Catalog/Pricing/Price/TierPrice.php

Function:   public function getSavePercent(AmountInterface $amount)
    {
        return round(
            100 - ((100 / $this->priceInfo->getPrice(FinalPrice::PRICE_CODE)->getValue())
                * $amount->getBaseAmount())
        );
    }

Line: 213  * $amount->getBaseAmount())

changed to * $amount->getValue())

Looks like it's working now...

**Comment by PGLDK** [comment] 2017-03-10 09:52
Yes. did the trick.

**Comment by veloraven** [comment] 2017-06-30 13:21
@martinhetschel thank you for your feedback.
Internal ticket was created for it: MAGETWO-70377

**Comment by pascaladriaansen** [comment] 2017-07-10 10:29
@veloraven fyi, it looks like this is the same issue as #6923 for which an internal ticket was also created

**Comment by magento-engcom-team** [comment] 2017-09-20 22:56
@martinhetschel, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:56 UTC
Labels: Issue: Ready for Work, bug report, Component: Tax, Fixed in 2.2.x, Issue: Format is valid

**Comment by dfatkulin** [comment] 2017-11-01 16:48
Magento 2.2. Tier price saving percentage wrong  in category. Reindex does not help.   have anyone a solution?
![wrong-tax-calculate](https://user-images.githubusercontent.com/12584463/32286166-7d6b46cc-bf24-11e7-9c65-c0ca6c9a59d9.jpg)

**Comment by deloenzien** [comment] 2019-02-23 09:06
### on magento 2.3 this is till a issue.

![schermafdruk 2019-02-23 10 03 18](https://user-images.githubusercontent.com/44753322/53284292-92b9b200-3752-11e9-9c2b-93373bdbc238.png)
![schermafdruk 2019-02-23 10 03 25](https://user-images.githubusercontent.com/44753322/53284298-99e0c000-3752-11e9-8566-1cb5689cd909.png)

price displayed on front is price incl.taxes +taxes
0.42 * 1.21 (21% taxes) = 0.5082

**Comment by deloenzien** [comment] 2019-02-24 09:06
to solve the problem in magento 2.3.0 i changed 
Magento_Catalog/templates/product/price/final_price.phtml

I added text to tell there is % when buy more 'by more and get %'
then I marked out the render of tier price. 
So, no tier price is shown, only some replace text with link to product page where tiere prices are correct.

` <a href="<?= /* @escapeNotVerified */ $block->getSaleableItem()->getProductUrl() ?>" class="minimal-price-link">
        By more and get % 
        </a>`
