### ISSUE TITLE
Magneto2 storing all messages in the cookie and uses JavaScript to display these messages. That makes problems for codeception-automatic testings of login-functionality

### ISSUE THREAD

**Issue by p06pratibha-verma** [magento/magento2#28863] opened 2020-06-24 07:56 UTC
### Preconditions (*)
Magento 2.x

### Actual result (*)

**Issue :** Magneto2 storing all messages in the cookie and uses JavaScript to display these messages. That makes problems for codeception-automatic testings of login-functionality (which cannot use JavaScript) and also sometimes we have more messages then a cookie allows (max size of cookies is 4kb), Please suggest any module/ code fix for this.

**Comment by Serializator** [comment] 2020-06-24 09:50
Hi @p06pratibha-verma, this issue seems to be a duplicate of #28862, can you confirm?

**Comment by p06pratibha-verma** [comment] 2020-06-24 10:14
> Hi @p06pratibha-verma, this issue seems to be a duplicate of #28862, can you confirm?

Yes it exactly same.

**Comment by engcom-Lima** [comment] 2020-06-30 07:13
@p06pratibha-verma Closed as duplicate of [#28862](https://github.com/magento/magento2/issues/28862)

**Closed as completed by engcom-Lima** 2020-06-30 07:13 UTC
Labels: duplicate, Issue: Format is valid
