### ISSUE TITLE
Downloadable product view layout

### ISSUE THREAD

**Issue by melaxon** [magento/magento2#20187] opened 2019-01-10 23:31 UTC
### Preconditions (*)

1. Magento 2.3.0 fresh installation, Luma
2. All default settings, nothing special
3. Any web browser
4. Tried to re-install with the same result

### Steps to reproduce (*)

1. Install Magento 2.3.0
2. Install one downloadable product and one simple product
3. in frontend open both products in different browser tabs to compare the layout

### Expected result (*)

1. Normal layout is expected, like for example in case of simple product. See screenshot:
https://gyazo.com/f4c7bb10d03da34528bd236700b93971

### Actual result (*)

1. The layout of downloadable product is broken:
https://gyazo.com/945c9322b0fbef9dd145176738315784
2. The price is duplicated for some reason
3. Empty not used space on the right.
4. Not sure why the word "links" appears on frontend (I guess only Samples would be sufficient)
5. In case of downloadable product the settings "Block after Info Column" or "Product Info Column" will not change anything
6. Qty is not shown up

Will try to play with catalog_product_view_type_downloadable.xml

**Comment by magento-engcom-team** [comment] 2019-01-10 23:31
Hi @melaxon. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@melaxon do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by melaxon** [comment] 2019-01-10 23:34
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment] 2019-01-10 23:34
Hi @melaxon. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment] 2019-01-10 23:34
Hi @melaxon, here is your [Magento instance](https://i-20187-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-20187-2-3-0.instances.magento-community.engineering/admin](https://i-20187-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by melaxon** [comment] 2019-01-10 23:46
this is a screenshot from vanilla https://gyazo.com/9e8e39e335562927a8775e04b5028422

**Comment by magento-engcom-team** [comment] 2019-01-11 01:44
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-01-11 01:47
@shikhamis11 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97567` were created

**Comment by melaxon** [comment] 2019-01-11 06:39
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-01-11 06:39
Hi @melaxon. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-01-11 06:40
Hi @melaxon, here is your [Magento instance](https://i-20187-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20187-2-3-develop.instances.magento-community.engineering/admin](https://i-20187-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by melaxon** [comment] 2019-01-11 06:51
the issue is reproducible on 2.3-develop as well
https://gyazo.com/ba0e56ee5f204715075390523f72060b

**Comment by magento-engcom-team** [comment] 2019-01-14 16:23
Hi @GovindaSharma. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-03-08 11:59
Hi @melaxon. Thank you for your report. 
The issue has been fixed in magento/magento2#20239 by @GovindaSharma in 2.3-develop branch
Related commit(s):
 - [e6f642277893816ba6384f3a3b92c6b2ead6a4bc](https://github.com/magento/magento2/commit/e6f642277893816ba6384f3a3b92c6b2ead6a4bc)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-08 11:59 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Area: Design/Frontend, Component: Downloadable
