### ISSUE TITLE
UPS shipping module fails to retrieve package pricing information

### ISSUE THREAD

**Issue by digitalbricklayer** [magento/magento2#34098] opened 2021-09-16 13:43 UTC
Whilst the error would not appear to be one caused by magento 2 software, the UPS module is included as part of the magento software. I have talked to UPS support and they say that they don't support the built-in UPS module and therefore I should go elsewhere for support.

### Preconditions (*)

1. Magento 2.3.7
2. UPS shipping needs to be configured with valid account information.

### Steps to reproduce (*)

1. Place a product in shopping cart
2. Click the link to proceed to Checkout

### Expected result (*)

1. The checkout page should display with the Economy shipping option as well as the UPS shipping options.

### Actual result (*)

1. The shipping options for UPS are missing only the Economy option is available
2. The `shipping.log` file says `The postal code is invalid for GB` in the `ErrorDescription` section of the xml. The postal code is perfectly valid and has been our post code for ~15 years.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Nazar65** [comment] 2021-09-16 15:50
@magento give me 2.4-develop instance

**Comment by shopaalogics** [comment] 2021-09-17 06:14
Go for [product scraper magento 2 extension](https://shop.aalogics.com/product-scraper-magento-2-extension) this might help you in retrieve  the product/package price information.

**Comment by engcom-November** [comment] 2021-09-17 10:15
Hi @digitalbricklayer ,

Verified the issue on Magento 2.4-develop branch but the issue is not reproducible for different Shipping Address Countries verified:
Shipping Origin Country: US
Front-end - Checkout - Shipping Address
UK:
![image](https://user-images.githubusercontent.com/60198231/133766366-a07f3e46-0029-4e69-9e1a-64e4c595397e.png)

Germany:
![image](https://user-images.githubusercontent.com/60198231/133766463-09ffb933-eab9-4239-a977-fe036d91d38b.png)

Canada:
![image](https://user-images.githubusercontent.com/60198231/133766546-6e895331-e979-4c9b-b4c3-611f29d41f32.png)

Kindly recheck the issue on Magento 2.4-develop branch as it has the latest code base and elaborate/provide configuration details like: Shipping Origin Address, Checkout Shipping Address, product details etc if the issue is still reproducible on 2.4-develop.

Thank you.

**Comment by digitalbricklayer** [comment] 2021-09-17 10:48
The issue happens prior to the customer entering their address. I believe the problem is not with the customer post code but with the shop post code. In the `shipping.log` there is no post code apart from the store post code. The customer post code hasn't been entered by this point.

**Comment by digitalbricklayer** [comment] 2021-09-17 10:57
Here is an excerpt from `shipping.log`: [ups pricing interface error.txt](https://github.com/magento/magento2/files/7185042/ups.pricing.interface.error.txt)

**Comment by engcom-November** [comment] 2021-10-04 13:25
Hi @digitalbricklayer ,

We are closing this issue as there has been no latest update on the same. Kindly reopen/create new ticket with missing steps if any if the issue still reproducible on Magento 2.4-develop branch

**Closed as completed by engcom-November** 2021-10-04 13:25 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update

**Comment by alexgubarev** [comment] 2022-01-11 13:30
@magento give me 2.4-develop instance

**Comment by alexgubarev** [comment] 2022-01-12 16:29
@magento give me 2.4-develop instance
