### ISSUE TITLE
Dashboard Report for "Month" has incorrect timezone set 

### ISSUE THREAD

**Issue by duffner** [magento/magento2#22077] opened 2019-04-01 02:15 UTC
The Magento Chart on the Dashboard for the "Current Month" dropdown is off by 2.5 hours for the EST -5 (America/New_York) timezone. As the date shown on the graph changes to the next business day at 9:30 pm EST. Appears to be a timezone calculation issue, or double conversion issue. 

### Preconditions (*)

1. Magento 2.3.0
2. Magento Dashboard Charts are Enabled
3. Server, Magento, and PHP all report correct timezone of America/New_York) 

### Steps to reproduce (*)

1. Date is 03/31/2019
2. Timezone is (America/New_York) on Server, PHP, and Magento
3. Current Time is 9:30 pm (America/New_York) -5 EST 
4. Select "Current Month" dropdown from Dashboard Chart 

### Expected result (*)

1. Report graph shows a report for starting 03/01/2019  - 03/31/2019
2. At 12:00am 04/01/2019 the report should change to April
3. Revenue Reported should be from 03/01/2019 to 03/31/2019 

### Actual result (*)

1. Report graph shows a report for 04/01/2019 even though it's still 03/31/2019
<img width="926" alt="Screen Shot 2019-03-31 at 9 08 57 PM" src="https://user-images.githubusercontent.com/7387019/55299594-3bfe6280-53f9-11e9-8b18-a5595d468904.png">
Take note, that it's still 03/31/2019 at the time of this screenshot. 
2. Revenue Reported is from anyime after 9:30 pm EST 03/31/2019. 

It appears that timezone for the charts are double corrected for the "Month" dropdown as EST is -5 from GMT and splitting the difference much like the Newsletter bug would result in a 2.5-hour difference in time.

**Comment by duffner** [comment] 2019-04-01 02:19
> Hi @duffner. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [x]  Summary of the issue
> * [x]  Information on your environment
> * [x]  Steps to reproduce
> * [x]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @duffner do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [x]  yes
> * [ ]  no

**Comment by magento-engcom-team** [comment] 2019-04-01 02:19
Hi @duffner. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-01 02:19
Hi @duffner, here is your [Magento instance](https://i-22077-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22077-2-3-develop.instances.magento-community.engineering/admin](https://i-22077-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by duffner** [comment] 2019-04-01 02:28
@magento-engcom-team, I was able to reproduce the issue within your test environment.  I placed an order and invoiced it, checked the Graph and it reports from 03/31/2019 to 04/01/2019 for month view. 

<img width="907" alt="Screen Shot 2019-03-31 at 9 25 34 PM" src="https://user-images.githubusercontent.com/7387019/55300149-d069c480-53fb-11e9-8651-d7d5ddfa521e.png">
Screen Shot taken from supplied instance, report should display 03/01/2019 - 03/31/2019, verified month start date in admin configuration is set to "01" .

**Comment by magento-engcom-team** [comment] 2019-04-01 11:47
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98996` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment] 2024-05-06 10:27
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-10-03 06:31
Hi

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-10-03 06:31 UTC
Labels: Component: Cms, Issue: Confirmed, Reproduced on 2.3.x, Reproduced on 2.4.x, Priority: P2, Severity: S2, Progress: done, Area: Analytics / Reporting
