### ISSUE TITLE
Admin permissions error when trying to save WYSIWYG content

### ISSUE THREAD

**Issue by sma09sjb** [magento/magento2#6067] opened 2016-08-09 09:30 UTC
Experiencing the similar issues to this ticket https://github.com/magento/magento2/issues/4920
### Steps to reproduce

Install Magento CE 2.1.0
Sign into the admin panel as a user with full permissions
Go to Products > CXatalog and select "edit" for a product
Go to the description wysiwyg and paste: 

`from time-to-time (collectively, "Conditions")`

also the following text is causing the same issue:

```
Amount per serving 
Curcumin C3 Complex® 400 mg 
(Curcuma longa)(root & rhizomes) 
[containing three curcuminoids: Curcumin, 
Bisdemethoxy curcumin, Demethoxy curcumin] 
Curcumin (Curcuma longa) 
[standardized to contain 95% turmeric] 
Lecithin Powder 100 mg 
[standardized to contain 3.5% flavonoids] 
Other Ingredients: Magnesium stearate (kosher), di calcium phosphate.
```
### Expected result

The WYSIWYG properly encodes/converts any special characters so that content is able to be saved
### Actual result

When you hit "Save" you get the following error at this url: 

`Failed to load resource: the server responded with a status of 404 (Not Found)
`

Strangely this is only on our softlaunch environment, locally we're not experiencing these issues. 

The previous ticket mentioned permissions, what specific permissions should i set to resolve this issue. 

This is causing a real problem for us, as we're not able to populate the products on the site. 

Any help is greatly appreciated. 

Kind regards, 

Sophie

**Comment by sma09sjb** [comment] 2016-08-16 10:13
Hi, 

Is this being reviewed, this bug is becoming a real problem for us?

Thanks,

Sophie

**Comment by AVoskoboinikov** [comment] 2016-08-18 10:11
Hello Sophie

Thank you for request, but unfortunately it is not reproducible on my build. I am using CE 2.1.0 version and WYSIWYG works fine, you can check it on attached screenshots (Pic 1 and Pic 2). Probably error is connected to your environment or system configuration. 

Could you please add some screenshots of that error? Maybe they will bring me some thoughts about error source. It would be great if you could give screenshots from debug tool. Here is steps how you can get them:
1. use Google Chrome;
2. make everything you need to reproduce error but don't press "save" button;
3. press F12 - you will see debug tool;
4. go to the network tab;
5. check checkbox "Preserve log";
6. don't close debug tool;
7. go back to product page and press "save" button;
8. go back to debug tool and somewhere you should see red line with error;
10. make screenshot of that error. You can check how it looks on my side on Pic 3 (notice that I have no error);
11. press on the line with error and make one more picture (like my Pic 4);
12. go to Response tab and make one more picture please (like my Pic 5. It is ok that I have empty tab there). That is last one, I promise.

I think it is all for now. Looking forward to getting your response.
Thanks and sorry for waiting!

Pic 1
![pic1](https://cloud.githubusercontent.com/assets/17980272/17769814/2e73fa28-6543-11e6-9eae-89acdad20864.png)

Pic 2
![pic2](https://cloud.githubusercontent.com/assets/17980272/17769817/2e75d3c0-6543-11e6-8daf-bc737fb2f8b4.png)

Pic 3
![pic3](https://cloud.githubusercontent.com/assets/17980272/17769818/2e76c71c-6543-11e6-857e-25d48039c4fc.png)

Pic 4
![pic4](https://cloud.githubusercontent.com/assets/17980272/17769815/2e74f0a4-6543-11e6-9226-f435ccf9881f.png)

Pic 5
![pic5](https://cloud.githubusercontent.com/assets/17980272/17769816/2e757d94-6543-11e6-8797-8bbc4a643934.png)

**Comment by sma09sjb** [comment] 2016-08-18 10:24
Hi,

i've done a screencast, you can see that here 
http://screencast.com/t/XCElpKwe

![error2](https://cloud.githubusercontent.com/assets/19289786/17770558/5cd3c9c8-6536-11e6-9d27-1744cc27b007.png)
![error3](https://cloud.githubusercontent.com/assets/19289786/17770556/5cd01e9a-6536-11e6-888d-776397837654.png)
![error1](https://cloud.githubusercontent.com/assets/19289786/17770557/5cd1533c-6536-11e6-9ae8-2a54bcf2e7df.png)

Let me know if you need anything else.

And thanks :-)

**Comment by AVoskoboinikov** [comment] 2016-08-19 10:12
Hi,

Thanks for screencast, it helped to make situation more clear, but I am still trying to reproduce error without success. 

Can you help me with some new questions?
1. Could you describe your environment (webserver, php version, mysql, etc.)?
2. Could you tell how you got your custom attributes like "key features", etc.?
3. Is there any difference between how you create product and your custom attributes  ("key features", etc.) on your local machine and server?
4. Could you try to reproduce the same error with WYSIWYG on other attributes? For example what will you get if you put 'from time-to-time (collectively, "Conditions")'  to Content->Description field?
5. Is there any data that can be successfully saved in "Key features" field or it fails with all variants of data?
6. Do you have installed any 3rd-party extensions?

I appreciate your response.

**Comment by sma09sjb** [comment] 2016-08-23 09:31
Hi,

Apologies for the delay, i've been out of the office for a few days.

1.

**Nexcess server** 
Bandwidth (Monthly):    Total: 125 GB   Used: 3.64 GB  
Disk Space: Total: 25000 MB Used: 606.70 MB

**PHP version**
PHP 7.0.8 (cli) (built: Jun 23 2016 11:27:39) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8, Copyright (c) 1999-2016, by Zend Technologies

**PHP Modules**
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
intl
json
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
pspell
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

**Zend Modules**
Zend OPcache

**MySQL- Database server**
Server: Localhost via UNIX socket
Software: Percona Server
Software version: 5.6.31-77.0 - Percona Server (GPL), Release 77.0, Revision 5c1061c
Protocol version: 10
Server charset: UTF-8 Unicode (utf8)

**MySQL- Web server**
Apache
Database client version: libmysql - 5.5.45-37.4
PHP extension: mysqli

**MySQLO - phpMyAdmin**
Version information: 3.5.4
1. custom attributes, such as Key Feature were installed in the following manner, 

```
/**
     * @param EavSetup $eavSetup
     * @param string $fieldName
     * @param string $fieldTitle
     */
    private function addWysiwygField($eavSetup, $fieldName, $fieldTitle) {
        $eavSetup->addAttribute(
            Product::ENTITY,
            $fieldName,
            [
                'type' => 'text',
                'label' => $fieldTitle,
                'input' => 'textarea',
                'required' => false,
                'source' => '',
                'global' => Attribute::SCOPE_GLOBAL,
                'visible' => true,
                'user_defined' => false,
                'searchable' => false,
                'filterable' => false,
                'filterable_in_search' => false,
                'comparable' => false,
                'visible_on_front' => true,
                'unique' => false,
                'group' => 'Additional details',
                'is_used_in_grid' => false,
                'is_visible_in_grid' => false,
                'is_filterable_in_grid' => false,
                'system' => 0
            ]
        );
        $eavSetup->updateAttribute(Product::ENTITY, $fieldName, 'is_wysiwyg_enabled', 1);
        $eavSetup->updateAttribute(Product::ENTITY, $fieldName, 'is_html_allowed_on_front', 1);
    }
```
1. There should be no difference between server environments when it comes to creating a product and interacting with custom attributes.
2. Same issues applies to attributes that are not custom, such as the description field.
3. No some data has been successfully been saved, but the issue seems very intermittent. I have successfully saved the paragraph below,

"Suggested Use: Mix one scoop with 8 oz. of water or your favorite beverage daily, or as directed by your health care practitioner."

 but copying and pasting this into an empty wysiwyg field today, i'm unable to save it. 

I'm wondering if showing/hiding the editor, changes how the data gets posted in some way, because testing initially, toggling between these states seems to make a discernible difference, i'm not able to screencast this though at the moment, as i cannot reproduce it today, as i say it's very intermittent. 

Also, i'm aware there was an issue with the way html was parsed in Magento 1 in terms of inserting line breaks,  the method nl2br() caused a number of issues, http://stackoverflow.com/questions/28670367/linebreak-in-magento-product-description-when-not-using-wysiwyg, could this be a similar problem.
1. We have two successfully installed extensions, links below; http://www.manadev.com/layered-navigation-filters-multiple-select-magento-2, http://store.cryozonic.com/magento-2/stripe-payments.html

I'm absolutely baffled as to the cause of this bug and i've been investigating this for over a week, so any help would be great.

Thanks,

Sophie

**Comment by AVoskoboinikov** [comment] 2016-08-25 12:01
Hi,

I am afraid that we still have no idea how to reproduce this issue. However, we have some assumptions.
1. In my personal experience there was issue with another wysiwyg tool, that was not able to process copy-pasted data from Microsoft Word, because it contained some extra symbols specific only for Microsof Word (e.g. styles). So, could try to write your data by hand? Or you can try to paste it from notepad.
2. Second assumption is related to your server environment. There is posibility that your 404-requests are blocked/rejected (or just handled in some strange way) by any intermediate proxy server. That could be a reason, why we could not reproduce this issue on our local machines.

I hope this could help you

**Comment by sma09sjb** [comment] 2016-08-25 13:02
Hi, 

Typing out/pasting the text into notepad etc doesn't work.

My assumption is that it's to do with my server configuration, but i don't know what precisely to check to resolve the problem, do you have any documentation on how the server should be set up in terms of permissions etc. 

Thanks,

Sophie

**Comment by AVoskoboinikov** [comment] 2016-08-25 13:51
We do, here is list:
http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html
http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-sys-perms-over.html
http://devdocs.magento.com/guides/v2.0/install-gde/install/legacy-file-system-perms.html
http://devdocs.magento.com/guides/v2.0/config-guide/prod/prod_file-sys-perms.html

**Comment by AVoskoboinikov** [comment] 2016-08-30 14:53
Hi @sma09sjb 
Could you please have a look at this comments?
https://github.com/magento/magento2/issues/2966#issuecomment-234610309
https://github.com/magento/magento2/issues/2966#issuecomment-234790690

It seams that other users have similar problem with 404 pages and they use Nexcess server too. I think you can try to solve your issue by contacting Nexcess support.

**Comment by sma09sjb** [comment] 2016-08-30 15:27
Hi, 

Yes this has now been resolved, the issue was regarding a mod security regular expression that matched on the REQUEST of the saving process for a new product. 

Nexcess need to review and update this regex in line with changes made to Magento 2.1.

For now they are adding an exception for the admin area.

Thanks,

Sophie

**Comment by AVoskoboinikov** [comment] 2016-08-30 16:00
Cool that it is ok now. I close this issue then.

**Closed as completed by AVoskoboinikov** 2016-08-30 16:00 UTC
Labels: bug report
