### ISSUE TITLE
Setup:di:compile verbosity does nothing

### ISSUE THREAD

**Issue by adamlavery** [magento/magento2#35391] opened 2022-04-28 09:29 UTC
### Summary (*)
setup:di:compile produces no useful output when there is a coding error. Using -v, -vv, -vvv or --verbose does nothing to help. The stack trace doesn't identify the file being processed let alone the source line of the error. If we've uploaded multiple files, none of which show any error in the code editor, we have no indicators where to find the code error.

### Examples (*)
```
$ bin/magento set:di:com -vvv
Compilation was started.
Repositories code generation... 1/9 [===>------------------------]  11% < 1 sec 127.0 MiBsyntax error, unexpected '->' (T_OBJECT_OPERATOR)#0 [root]/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#2 [internal function]: spl_autoload_call()
#3 [root]/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists()
#4 [root]/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass()
#5 [root]/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract()
#6 [root]/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php(61): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList()
#7 [root]/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation()
#8 [root]/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(216): Magento\Setup\Module\Di\App\Task\Manager->process()
#9 [root]/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DiCompileCommand->execute()
#10 [root]/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#11 [root]/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#12 [root]/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun()
#13 [root]/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()
#14 [root]/bin/magento(23): Symfony\Component\Console\Application->run()
#15 {main}

```
Nothing here indicates where the error is.

### Proposed solution
As a minimum, the ClassLoader must identify the class it is trying to load. Preferably it would also include the line that generated the error.
---

- [x ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._

**Comment by engcom-Charlie** [comment] 2022-07-20 07:59
:heavy_check_mark: Issue Confirmed

Tried to reproduce the issue on magento 2.4-develop and its reproducible.

**Manual testing scenario:**

1. Clean Magento setup
2. Created coding error by adding some extra or wrong operator in controller
3. Executed bin/magento set:di:com -vvv 
4. Also tried with -v, -vv options
5. We are getting the error on compile

**Expected Result:**
We should get the proper indication that where the error is or where to find the error. Verbosity is not working, on error it should tell the file or specifically line that generated the error

**Actual Result:** 
Getting the error without any clear indication of class or file.
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/51680850/179928502-87ccbeff-5303-49d3-bcd2-09fa342c3237.png">


As per above findings confirming the issue.

**Comment by artskirk** [comment] 2022-07-22 08:55
The issue is not reproduced on 2.4-develop 
![image](https://user-images.githubusercontent.com/57759456/180402760-c759a1fe-0bdf-4dc9-9f35-0757b97c6d69.png)
Seems like it already fixed.

**Comment by adamlavery** [comment] 2022-07-22 09:24
That is not testing a code error. The point is when di:com fails it should provide adequate information to identify where the issue is.

**Comment by engcom-Hotel** [comment] 2022-08-29 12:58
Hello @<reporter>,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-5994 by the internal team
Related commits: https://github.com/magento/magento2/commit/fd7e45e945796afcb39ef96c57121f494d651754

Based on the Jira ticket, the target version is 2.4.6.

Thanks

**Closed as completed by engcom-Hotel** 2022-08-29 12:58 UTC
Labels: Issue: Confirmed, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P3, Progress: done, Area: Other Developer Tools
