### ISSUE TITLE
$(html) HTML strings must start with '<' character

### ISSUE THREAD

**Issue by hgpit** [magento/magento2#3105] opened 2016-01-24 16:33 UTC
According to this post: https://github.com/magento/magento2/issues/1936, this should be fixed, but I am seeing it in Magento 2.0.1 today:

![image](https://cloud.githubusercontent.com/assets/16598973/12537473/100fc98c-c2b8-11e5-9d71-3b93dd4a2fbf.png)

**Comment by anton-huz** [comment] 2016-01-25 18:07
Dear hgpit, the issue #1936 was about another page (Product detail page on Storefront area).
Issue you are mention really occurs on develop and 2.0.1 branches.

Internal issue MAGETWO-48308 was created.

Thank you for reporting. But in general this is not what you should worry about. At all. jQMigrate just notifies about something unusual. Issue doesn't break any functionality.

**Comment by hgpit** [comment] 2016-01-25 18:53
Okay, great, thank you :)

On 25 January 2016 at 18:08, Anton Guz notifications@github.com wrote:

> Dear hgpit, the issue #1936
> https://github.com/magento/magento2/issues/1936 was about another page
> (Product detail page on Storefront area).
> Issue you are mention really occurs on develop and 2.0.1 branches.
> 
> Internal issue MAGETWO-48308 was created.
> 
> Thank you for reporting. But in general this is not what you should worry
> about. At all. jQMigrate just notifies about something unusual. Issue
> doesn't break any functionality.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/magento/magento2/issues/3105#issuecomment-174606102.

## 

Group IT Support
Hayley Group PLC (Site 3)
Shelah Road, Halesowen, West Midlands, B63 3PG, England
Company No: 1257303. VAT No: GB 287546119
[Tel] +44 (0)121 585 5334 | [Fax] +44 (0)121 585 7924 | [www]
http://helpdesk.hayley-group.local

## 

The information contained in this e-mail is intended only for the person or 
entity to which it is addressed and may contain confidential and/or 
privileged material. If you are not the intended recipient of this e-mail, 
the use of this information or any disclosure, copying or distribution is 
strictly prohibited and may be unlawful. If you received this e-mail in 
error, please contact the sender immediately and delete the material from 
any computer.

The views expressed in this e-mail may not necessarily be the views of 
Hayley Group PLC and should not be taken as authority to carry out any 
instruction contained within.

**Comment by katmoon** [comment] 2016-03-12 15:45
Hi all,

The internal has been closed since the issue is not reproducible anymore.
I'm closing the ticket.

Thanks for reporting!
Kateryna.

**Closed as completed by katmoon** 2016-03-12 15:45 UTC
Labels: Issue: Ready for Work, bug report

**Comment by devdesco-ceo** [comment] 2016-04-30 21:59
Same thing here on 2.0.4 and 2.0.5

![image 2016-04-30 16 58 16](https://cloud.githubusercontent.com/assets/8983883/14938779/effc6d7e-0ef4-11e6-93e3-d71ef1b826fd.png)
![image 2016-04-30 16 58 24](https://cloud.githubusercontent.com/assets/8983883/14938780/f0012cb0-0ef4-11e6-8e0d-521b8060e7a8.png)

**Comment by sbwcws** [comment] 2016-05-08 22:01
I CONFIRM THE same in Magento 2.05 - Product is not saving - Spinner is just spinner if I am even lucky going that far.

<img width="1280" alt="screenshot 2016-05-08 18 00 22" src="https://cloud.githubusercontent.com/assets/7937555/15100669/c1b3ad30-1546-11e6-8992-fca77dc739b2.png">

**Comment by mhabou** [comment] 2016-06-17 13:51
@sbwcws : 
I confirm the same in Magento 2.0.7 - product is not saving

```
JQMIGRATE: $(html) HTML strings must start with '<' character jquery-migrate.js:41:4
console.trace(): jquery-migrate.js:43
migrateWarn() jquery-migrate.js:43
jQuery.fn.init() jquery-migrate.js:204
jQuery() jquery.js:75
._create/<() base-image-uploader.js:70
jQuery.event.dispatch() jquery.js:4623
jQuery.event.add/elemData.handle() jquery.js:4292
jQuery.event.trigger() jquery.js:4533
jQuery.event.trigger() jquery-migrate.js:493
.trigger/<() jquery.js:5235
.each() jquery.js:384
jQuery.prototype.each() jquery.js:137
.trigger() jquery.js:5234
._create/<() product-gallery.js:38
.proxy/proxy() jquery.js:556
.each() jquery.js:384
._create() product-gallery.js:37
$.widget/</prototype[prop]</<() jquery-ui-1.9.2.js:432
$.widget/</prototype[prop]</_super() jquery-ui-1.9.2.js:419
._create() product-gallery.js:260
$.widget/</prototype[prop]</<() jquery-ui-1.9.2.js:432
$.Widget.prototype._createWidget() jquery-ui-1.9.2.js:597
$.widget/$[namespace][name]() jquery-ui-1.9.2.js:396
$.widget/$[namespace][name]() jquery-ui-1.9.2.js:390
init/<() main.js:30
newContext/context.execCb() require.js:1650
newContext/Module.prototype.check() require.js:866
newContext/Module.prototype.enable/</<() require.js:1113
bind/<() require.js:132
newContext/Module.prototype.emit/<() require.js:1156
each() require.js:57
newContext/Module.prototype.emit() require.js:1155
newContext/Module.prototype.check() require.js:917
newContext/Module.prototype.enable/</<() require.js:1113
bind/<() require.js:132
newContext/Module.prototype.emit/<() require.js:1156
each() require.js:57
newContext/Module.prototype.emit() require.js:1155
newContext/Module.prototype.check() require.js:917
newContext/Module.prototype.enable/</<() require.js:1113
bind/<() require.js:132
newContext/Module.prototype.emit/<() require.js:1156
each() require.js:57
newContext/Module.prototype.emit() require.js:1155
newContext/Module.prototype.check() require.js:917
newContext/Module.prototype.enable/</<() require.js:1113
bind/<() require.js:132
newContext/Module.prototype.emit/<() require.js:1156
each() require.js:57
newContext/Module.prototype.emit() require.js:1155
newContext/Module.prototype.check() require.js:917
newContext/Module.prototype.enable/</<() require.js:1113
bind/<() require.js:132
newContext/Module.prototype.emit/<() require.js:1156
each() require.js:57
newContext/Module.prototype.emit() require.js:1155
newContext/Module.prototype.check() require.js:917
newContext/Module.prototype.enable() require.js:1143
newContext/Module.prototype.init() require.js:774
callGetModule() require.js:1170
newContext/context.completeLoad() require.js:1544
context.completeLoad() resolver.js:105
newContext/context.onScriptLoad()
```

**Comment by rhertogh** [comment] 2016-08-30 15:07
I had the same issue (magento v2.1.0).
Workaround for me (sort of, since this is not recommended in a production env): disabled and flushed all caches in magento and browser cache.
