### ISSUE TITLE
Ui component grid filter/sorting not working

### ISSUE THREAD

**Issue by rav-redchamps** [magento/magento2#33620] opened 2021-07-28 16:39 UTC
### Preconditions (*)

1. Magento version >= 2.4.2

### Steps to reproduce (*)

1. Login to admin panel & navigate to Catalog > Products grid
2. Filter grid by some SKU
3. Close the browser window
4. Open admin panel in new private/incognito window
5. Go to Catalog > Product Grids

### Expected result (*)

✅ Grid should be filtered by SKU

### Actual result (*)

ℹ️ You will see that grid has SKU filter applied but it still show all the records

P.S Grid will show correct result if you refresh the page again.

### Caused by pull request https://github.com/magento/magento2/pull/28117
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Den4ik** [comment] 2021-07-28 19:32
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2021-07-28 19:38
:white_check_mark: Confirmed by @Den4ik 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42930` were created

**Issue Available**: @Den4ik, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2021-07-28 19:40
:white_check_mark: Confirmed by @Den4ik 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42930` were created

**Issue Available**: @Den4ik, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2021-07-28 19:41
:white_check_mark: Confirmed by @Den4ik 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42930` were created

**Issue Available**: @Den4ik, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Vasudev-22** [comment] 2023-01-06 14:09
@magento give me 2.4-develop instance

**Comment by Vasudev-22** [comment] 2023-01-06 14:20
@rav-redchamps , 

Issue is not reproducible, Please check this again in latest 2.4-develop branch.

<img width="1297" alt="Screenshot 2023-01-06 at 7 47 29 PM" src="https://user-images.githubusercontent.com/104893739/211030183-e966820b-58af-4a6e-a144-78a5bf1a92be.png">

**Comment by Vasudev-22** [comment] 2023-01-06 15:33
@magento I am working on this

**Comment by engcom-Bravo** [comment] 2024-06-24 04:35
Hi @rav-redchamps,

Thanks for your reporting and collaboration.

As the issue is not reproducible in latest 2.4-develop instance https://github.com/magento/magento2/issues/33620#issuecomment-1373703232 We are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-24 04:35 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Severity: S1, Progress: done
