### ISSUE TITLE
Second swatch for out-of-stock doesn't get striked-out

### ISSUE THREAD

**Issue by cptX** [magento/magento2#37357] opened 2023-04-10 17:36 UTC
### Preconditions and environment

Magento version 2.4.6
Luma Theme
Elasticsuite 2.11.0

### Steps to reproduce

Create a configurable product with two attributes color and size.
Let's say that pink helmet is available but only in M size.
The out-of-stock colors are correctly striked-out (bug from 2.4.5 corrected in 2.4.6).
But the out-of-stock sizes don't get striked out.
So the customer can see which colors are available but when selecting a color cannot see which sizes are available as all of them show as in stock...

if the customer selects a color and then a size which with this combination is out of stock and clicks 'Add to Cart' then receives the message "There are no source items with the in stock status".

In the following example the pink helmet is only available in M size. Both S and L sizes show as available without strike out. Also the availability on the top right always shows as in stock which is very misleading...

![image](https://user-images.githubusercontent.com/9040042/230958341-790ef643-fed5-45e3-b06e-cf523c08d774.png)

### Expected result

Both visual and text swatches should have the ability to get striked-out when out-of-stock.

### Actual result

Now only visual swatches can get striked-out when out-of-stock. Text swatches never get striked-out

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment] 2023-04-11 00:33
Is this issue same case with https://github.com/magento/magento2/issues/37209 ? Or totally different

**Comment by mrtuvn** [comment] 2023-04-11 01:00
@cptX Found this one. But this not offical fix yet and i dont know if it fit perfect with your scenario
https://github.com/magento/inventory/pull/3040/files

**Comment by cptX** [comment] 2023-04-11 06:46
Hi @mrtuvn https://github.com/magento/magento2/issues/37209 is different but maybe slightly related or maybe people should see the issues together to provide a universal solution...
I don't know what MSI modules are, I didn't install anything extra regarding inventory.

**Comment by cptX** [comment] 2023-04-11 06:51
> @cptX Found this one. But this fix is not merge yet and i dont know if it fit perfect with your scenario https://github.com/magento/inventory/pull/3040/files

Yes this https://github.com/magento/inventory/issues/3035 looks related to my problem ! Thanks for finding it!
Question is what we do now, is this planned to get into final release? It's been 3 years since the opening of the issue!

**Comment by cptX** [comment] 2023-04-11 07:02
I just discovered that the mechanism is actually partially working but only if you disable the simple products that are out of stock
![image](https://user-images.githubusercontent.com/9040042/231081635-349180ad-e697-41f9-a741-1fd7475b1b30.png)
So the problem seems that the swatches are not striked when out-of-stock but only when disabled. Of course this is not correct behavior. They should get striked also when out-of-stock!

**Comment by mrtuvn** [comment] 2023-04-11 07:41
Yes, MSI modules enabled by default for both version community and commerce. It's have controls your stocks, back orders, etc..

**Comment by cptX** [comment] 2023-04-11 10:01
@mrtuvn in my opinion I think the problem is different.
As I show in my last post the functionality to strike out also the second swatch is there but not working depending on stock. So an out-of-stock product still shows without strike-out but when disabled shows indeed as strike-out. Maybe the solution is much more simple, and there could be a bug somewhere that doesn't allow the out-of-stock status to be correctly checked ...

**Comment by engcom-Dash** [comment] 2023-04-12 09:36
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-04-14 04:15
@magento give me 2.4.6 instance

**Comment by cptX** [comment] 2023-05-04 21:33
Any progress on this? Did anybody verify the bug?

**Comment by engcom-Dash** [comment] 2023-05-09 01:57
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-05-11 18:33
Hi @cptX ,

Verified the issue in 2.4.6 Magento instance and 2.4-develop issue can be reproducible, Hence we are confirming the issue.

 
Preconditions:
Magento version 2.4.6 and 2.4-develop
PHP 8.1
 
Steps to reproduce:
1.Install Magento instance
2.Create Configurable product with Visual swatches
3.Set some of the simple products as out of stock or quantity is 0 and Save
4.Go to front and go to product of page respective configurable product
5.Select any Size and colour to add to cart in bucket
 
Kindly refer the below screenshots:
<img width="1511" alt="Screenshot 2023-05-09 at 7 21 55 AM" src="https://github.com/magento/magento2/assets/60198592/09206316-2d89-4eb2-8df5-f4794efa263e">
<img width="1511" alt="Screenshot 2023-05-09 at 7 22 04 AM" src="https://github.com/magento/magento2/assets/60198592/05ced0ba-020e-4b9b-b6e6-e2a7c0ca127a">

We are getting actual result as per the description, which product when strike out when selecting size of the product, otherwise product showing with in stock,So the customer can see which colours are available but when selecting a colour cannot see which sizes are available as all of them show as in stock.

 
Regards,

**Comment by engcom-Dash** [comment] 2023-05-16 17:57
Hi @cptX ,

As per the internal discussion we are getting expected behaviour for this issue.
Kindly refer the below screenshot:
<img width="1511" alt="Screenshot 2023-05-16 at 5 38 08 PM" src="https://github.com/magento/magento2/assets/60198592/61c0012d-783f-4a1b-aff1-d56c121e6421">

If all the products goes to  out of stock ,the particular Size got strike out(In above screenshot all the colours out of stock in M size ).Because all the colour variants depends one size variant.If all the products get out of stock then only its striked out otherwise the particular size is showing with in stock status only.this expected behaviour as per the description.

let us know if we are missing anything!

Thanks!

**Comment by engcom-Dash** [comment] 2023-06-07 03:36
Hi @cptX 

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by cptX** [comment] 2023-06-07 04:22
Hi engcom-Dash, please don't close it yet! I don't understand. Initially after my report the issue was verified. Then an internal jira ticket was created. Then 3 weeks ago you reported that you get the expected behavior! (sorry I didn't see this earlier).
So you get the expected behavior after you did modifications in the code? As I said with the original code the behavior was not correct!! Please explain! Also if you did modifications please explain how to apply them in our systems!
Also, if somebody selects the out of stock item, correct behavior would be to show the item but say "out of stock". Now the customer cannot view the out of stock item at all, and the availability label is not updated at all!!
Why are you closing this??

**Comment by cptX** [comment] 2023-06-07 04:27
> Hi @cptX
> 
> We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
> 
> Thanks.

Why are you closing this??? Please read my last message! I don't know how can I reopen it?

**Comment by engcom-Dash** [comment] 2023-06-08 04:37
Hi @cptX ,

Thanks for Contribution and collaboration !

Initially verified the issue in 2.4-develop instance and checked the behaviour with wrong reproduction path,After that We had internal discussion with team and verified the issue and its expected behaviour as well as we didn't change anything form code level FYI.
**Kindly refer the below screenshots:**
<img width="1505" alt="Screenshot 2023-06-08 at 10 00 08 AM" src="https://github.com/magento/magento2/assets/60198592/1b8040ac-c830-40f8-83e6-42ad049144de">

In above Screenshot Size M out of stock for green colour but remaining sizes of red and blue will available,thats the reason text swatch not striked out.If all the sizes of green colour got out of stock at that time both text swatch and visual swatch will get striked out.

This is expected behaviour and Kindly recheck the issue one again with 2.4-develop instance and let me know if we are missing anything.

Thanks.

**Comment by timpea-splat** [comment] 2023-06-20 12:08
@magento give me 2.4.6-p1 instance

**Comment by timpea-splat** [comment] 2023-06-20 12:35
@magento give me 2.4.6-p1 instance

**Comment by timpea-splat** [comment] 2023-06-20 13:09
@magento give me 2.4.6-p1 instance

**Comment by timpea-splat** [comment] 2023-06-20 15:03
@magento give me 2.4.6-p1 instance

**Comment by engcom-Dash** [comment] 2023-06-21 12:23
Hi @cptX ,

verified the issue as per your last [comments](https://github.com/magento/magento2/issues/37357#issuecomment-1582012931).
Kindly refer the screenshots as well as video reference:
<img width="1509" alt="Screenshot 2023-06-21 at 4 51 50 PM" src="https://github.com/magento/magento2/assets/60198592/e58a22e4-aa64-433c-b75d-2f715d460b72">

https://github.com/magento/magento2/assets/60198592/ed2771f7-1cc5-447e-b2a1-f7bcb365933d

**Comment by cptX** [comment] 2023-06-21 16:03
@engcom-Dash thanks for your effort!
So on your side it works correctly?

**Comment by engcom-Dash** [comment] 2023-06-22 11:20
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-06-22 11:52
Hi @cptX ,

Once again we verified the issue in 2.4-develop bot instance and its working as expected.
Kindly refer the below video reference:

https://github.com/magento/magento2/assets/60198592/3a30943f-2097-4ea4-8120-b5ddf67ae3ea

Note: We verified only in bot instance  and Manage stock also Enabled as well as second swatch is Text Swatch only.
<img width="1509" alt="Screenshot 2023-06-22 at 5 20 30 PM" src="https://github.com/magento/magento2/assets/60198592/b246410c-8b31-4742-8ea3-79f8d36a34e1">

Thanks!

**Comment by timpea-splat** [comment] 2023-06-22 14:50
@magento give me 2.4.6-p1 instance

**Comment by timpea-splat** [comment] 2023-06-27 11:27
@magento give me 2.4-develop instance

**Comment by timpea-splat** [comment] 2023-06-27 11:46
@cptX @engcom-Hotel, I can confirm this bug on Magento 2.4.6-p1, but it works as expected on the dev instance.

Steps to reproduce in 2.4.6-p1:
Enable display out of stock products:
![Screenshot 2023-06-27 at 12 40 34](https://github.com/magento/magento2/assets/68768633/7197915e-7de3-43d8-afea-15f2e983718d)

Change simple product to Out Of Stock:
![Screenshot 2023-06-27 at 12 43 19](https://github.com/magento/magento2/assets/68768633/4c2bb398-4e96-4904-a6e6-b8b47aabe9d0)

2nd Swatch is not crossed out, when trying to add to cart:  "There are no source items with the in stock status"
![Screenshot 2023-06-27 at 12 44 08](https://github.com/magento/magento2/assets/68768633/4c025e85-a49c-4627-bf56-31737fed9c28)

**Comment by cptX** [comment] 2023-06-27 12:37
That's great news!!!! Thanks god you confirmed it because I was thinking of thousand other causes that could have this effect! Great job @engcom-Hotel. So what are now the next steps? I consider this important because now I need to disable all the products that get out of stock in order to show the correct availability in the swatches, and of course when something gets out of stock the swatches are not showing the problem correctly...

**Comment by engcom-Bravo** [comment] 2023-07-06 13:10
Hi @timpea-splat,

Thanks for your update.

Verified the issue on **Magento 2.4.6-p1 instance** and the issue is reproducible.Kindly refer the screenshots.


<img width="1460" alt="Screenshot 2023-07-06 at 3 22 28 PM" src="https://github.com/magento/magento2/assets/51680745/cefbe2fb-358a-4ea8-b7a4-2dae6eec3c1b">





But the issue is not reproducible in Latest version **Magento 2.4.7-beta1** it seems issue got fixed.please upgrade to latest version of the magento.



<img width="1442" alt="Screenshot 2023-07-06 at 4 10 18 PM" src="https://github.com/magento/magento2/assets/51680745/b83034f0-362d-4063-a287-c8d799a1f10c">




It is working as expected in **Magento 2.4-develop instance**.


<img width="1439" alt="Screenshot 2023-07-06 at 3 21 38 PM" src="https://github.com/magento/magento2/assets/51680745/08a7fd5c-6c10-4604-bfc6-98bb575db1bb">



Kindly let us know if you are still facing any issue.


Thanks.

**Comment by timpea-splat** [comment] 2023-07-06 13:13
@engcom-Bravo thank you, do you know which commit has fixed this issue?   We do not want to run 2.4.7-beta1 in a live environment.

**Comment by cptX** [comment] 2023-07-16 08:27
Guys any news about how to patch the 2.4.6? This is important functionality and I need it urgently!

**Comment by chernenm** [comment] 2023-07-17 20:45
Hello @cptX,

The fix for the issue is available as an individual quality patch https://github.com/magento/quality-patches/blob/master/patches/os/ACSD-47803_2.4.4.patch in QPT tool v1.1.24  https://experienceleague.adobe.com/docs/commerce-operations/tools/quality-patches-tool/release-notes.html#v1-1-24

It was initially released for 2.4.4 version, but it should be also compatible with 2.4.6.

**Comment by cptX** [comment] 2023-07-17 21:31
@chernenm your information helps significantly. So this was an already known bug?

**Comment by engcom-Bravo** [comment] 2023-07-18 09:32
@chernenm Thanks for your contribution & collaboration over here.

@cptX We hope issue has been solved now please let us know if you are still facing any issue.As per this comment https://github.com/magento/magento2/issues/37357#issuecomment-1638915225 can we close this issue?

Thanks.

**Comment by cptX** [comment] 2023-07-18 11:47
Yes, let's close this. Only one question though: how can I install a quality patch from a previous QPT tool.
This patch was declaring version <2.4.6 but actually worked in 2.4.6 when applied manually. Is there a way to apply it with the correct methodologies?

**Comment by cptX** [comment] 2023-07-19 08:28
@chernenm It would be nicer if the user could see the available options even striked-through, because now he cannot know what options exist and also cannot see the pictures of these options.
You are free to close this issue if you consider it completed

**Closed as completed** 2023-07-19 14:58 UTC
Labels: Issue: needs update, Reported on 2.4.6
