### ISSUE TITLE
Inventory min/max limit and increments PER website #MSI

### ISSUE THREAD

**Issue by tomekjordan** [magento/magento2#19152] opened 2018-11-10 14:55 UTC
### Description (*)

Magento 1 & 2 cannot limit product min / max added to the cart per website.
If Magento is multistore this is crucial feature.
You have different stores, different strategies, and merchant want give limits for inventory per website scope not only globally

### Expected behavior (*)

Inventory tab (also for #MSI) should have just Websites scope not only global scope.
Allowing merchants to fill fields for 
1. Min/Max QTY added to the cart per website
2. QTY increments per website

ADVANCED INVENTORY tab: its working on global scope only (mostly)
[http://prntscr.com/lgohik](http://prntscr.com/lgohik)

### Benefits

2 websites - means you can have different limits and marketing strategy.
One website can have limit for 5 Iphones in the care, while second store can have limit of 10 and different prices and shipping costs.

### Additional information

This should not be a problem to just add website scope for this inventory tab attributes.
Since #MSI is a complete rewrite of inventory for Magento - it can at once add website scope for min/max qty added to the cart and qty increments 

Thanks

**Comment by magento-engcom-team** [comment] 2018-11-10 14:55
Hi @tomekjordan. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@tomekjordan do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-11-12 11:51
Hi @TomashKhamlai. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by TomashKhamlai** [comment] 2018-11-12 12:04
Please open exactly the same issue on [magento-engcom/msi](https://github.com/magento-engcom/msi/issues/new?template=bug_report.md), then slightly modify this issue and open it also in [magento/community-features](https://github.com/magento/community-features/issues/new), but remove all the MSI related stuff(change the screenshot and description).

Now you have like 2 in 1 bug and both of them are feature-requests. We do not accept feature-reqests here, that is why I am closing this issue.

**Closed as completed** 2018-11-12 12:08 UTC
Labels: Issue: Clear Description, Reproduced on 2.3.x, Issue: Format is valid, Component: CatalogInventory, Component: MSI
