### ISSUE TITLE
Product edit/add issue

### ISSUE THREAD

**Issue by huzanf** [magento/magento2#23096] opened 2019-06-02 06:03 UTC
**Preconditions (*)**
1. Magento 2.3
2. PHP 7

**Steps to reproduce (*)**
1. In magento admin panel, on catalogue on clicking on add or edit product the page loads and the loading sign never goes

**Expected result (*)**
1. On clicking on edit or add product, I should be able to edit information and update/save the product

**Actual result (*)**
1. Browser console error log:
![error-console](https://user-images.githubusercontent.com/10163650/58757427-16412700-852a-11e9-9ac4-7e4989cfdd5a.png)

**Comment by orlangur** [comment] 2019-06-02 20:53
@huzanf this is something with your env. Static files not returning 404 Not Found normally.

**Comment by ajijshekh123** [comment] 2019-06-03 04:57
Give me @magento give me 2.3-develop instance.

**Comment by magento-engcom-team** [comment] 2019-06-03 04:57
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-06-03 04:58
Hi @ajijshekh123, here is your [Magento instance](https://i-23096-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23096-2-3-develop.instances.magento-community.engineering/admin](https://i-23096-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by huzanf** [comment] 2019-06-03 05:02
@orlangur thank you for your comment. Could this be something to do with the file permissions?

**Comment by ajijshekh123** [comment] 2019-06-03 05:19
Give me @magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-06-03 05:19
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-06-03 05:19
Hi @ajijshekh123, here is your [Magento instance](https://i-23096-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23096-2-2-develop.instances.magento-community.engineering/admin](https://i-23096-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2019-06-03 05:34
The issue is not reproduced on Magento 2.3 and Magento 2.2 Instance.
@huzanf - This issue is related to an external static file or any security reason do not read the file.

**Comment by huzanf** [comment] 2019-06-03 05:43
Hi @ajijshekh123 
Thank you very much for your time and support. Could this be because of wrong file permissions?

**Comment by ajijshekh123** [comment] 2019-06-03 05:48
Hi @huzanf, I am not sure but It may be wrong file permission or related to extension file if you have using it.
Please apply permission for the proper file Or Disable the extension and check it.

**Comment by huzanf** [comment] 2019-06-03 05:52
Hi @ajijshekh123 
Could you please help with what should be the correct file permissions for Magento? Thank you for your support

**Comment by ajijshekh123** [comment] 2019-06-03 05:57
@huzanf - I don't have proper idea about the correct file permission for Magento.
Sorry for the inconvenience.

**Comment by ajijshekh123** [comment] 2019-06-04 06:07
@huzanf - Have you fixed the issue?

**Comment by huzanf** [comment] 2019-06-04 11:41
Hi @ajijshekh123 
No. I haven’t been able to fix this yet.

**Comment by sdzhepa** [comment] 2019-06-04 23:37
Hello @huzanf , @ajijshekh123 

It is more like local env issue instead of Magento bug
More details about [File systems access permissions](https://devdocs.magento.com/guides/v2.3/config-guide/prod/prod_file-sys-perms.html)
Also, re-generating static content and flush all caches could help

> Step 1) rm -rf var/* pub/static/*
> Step 2) php bin/magento setup:upgrade
> Step 3) php bin/magento setup:static-content:deploy -f
> Step 4) php bin/magento cache:flush

I think we can close this issue as not a bug or Cannot reproduce

**Comment by huzanf** [comment] 2019-06-05 06:26
Hello @sdzhepa ,

Could you please help me with what should be the exact file permissions.

My current permissions are:
Folder: 775
Files: 664

Is this the reason I am facing issues?

**Comment by huzanf** [comment] 2019-06-07 09:51
Hi @sdzhepa,

Looking forward for your support

**Comment by ajijshekh123** [comment] 2019-06-10 06:51
Ok @sdzhepa, Let me check the document and Update it.

**Comment by huzanf** [comment] 2019-06-13 08:00
Hi @ajijshekh123 
Looking forward for your support.

**Comment by engcom-Delta** [comment] 2019-06-25 13:49
Hi @huzanf  
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

**Closed as completed by engcom-Delta** 2019-06-25 13:49 UTC
Labels: Component: Catalog, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Admin
