### ISSUE TITLE
Bulk Import: fwrite(): send of 21 bytes failed with errno=32 Broken pipe

### ISSUE THREAD

**Issue by taihuuho** [magento/magento2#25947] opened 2019-12-08 06:04 UTC
### Preconditions (*)

1. Magento 2.3.3
2. Rabbit MQ heartbeat set to 1800s

### Steps to reproduce (*)

1. Trying to import 2 configurable products. Each one has about 100 simple products (two or three times before moving on to the next step)
`rest/async/bulk/V1/products`
2. Run `bin/magento queue:consumers:start async.operations.all` to start the consumers

### Expected result (*)

1. The consumers should consume the messages from rabbitmq and import the products fine
### Actual result (*)

1. It ran for about 10-15 seconds then threw an exception and crashed the consumer.

![Screenshot_34](https://user-images.githubusercontent.com/51681435/71412800-ebe6c080-2657-11ea-8cb4-4a8bd884d61d.png)

<img width="1440" alt="Screen Shot 2019-12-08 at 12 04 34 AM" src="https://user-images.githubusercontent.com/12061272/70384990-5c9a9700-194e-11ea-8dd2-a44e9c479979.png">
<img width="839" alt="Screen Shot 2019-12-08 at 12 06 10 AM" src="https://user-images.githubusercontent.com/12061272/70385015-b733f300-194e-11ea-9164-93cbf08333af.png">

**Comment by taihuuho** [comment] 2019-12-08 15:55
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2019-12-08 15:55
Hi @taihuuho. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-12-08 15:56
Hi @taihuuho, here is your [Magento instance](https://i-25947-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25947-2-4-develop.instances.magento-community.engineering/admin](https://i-25947-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by taihuuho** [comment] 2019-12-08 16:21
Yes, was able to reproduce it

**Comment by engcom-Echo** [comment] 2019-12-19 12:59
Hello @taihuuho 

Could you provide more details for reproduce this issue?
Please add screenshot with your memory settings.

**Comment by taihuuho** [comment] 2019-12-20 17:47
@engcom-Echo 
I tried to import 2 configurable products. Each one has about 100 simple products.
I'll add the screenshots and more details tonight.
Sorry for the late response

**Comment by taihuuho** [comment] 2019-12-23 20:49
<img width="1276" alt="Screen Shot 2019-12-23 at 2 42 40 PM" src="https://user-images.githubusercontent.com/12061272/71379889-bdeb7880-2592-11ea-9481-ccb20c97c13c.png">

@engcom-Echo , please see the memory settings in the screenshot above.

**Reproduction steps**
- Create 10 different colors and 9 different sizes
- Try using the Bulk API to import 2 configurable products using those colors and sizes. Each will create about 90 simple products.
- Rabbit MQ set the heartbeat to 1800 seconds.
- The messages were queued up fine in RabbitMQ queue.
- On the Magento2 server, from the root folder, run `bin/magento queue:consumers:start async.operations.all` to start the consumers.
- It would run for 15-20 seconds or 45 seconds sometimes, then crashed

**Comment by magento-engcom-team** [comment] 2019-12-24 12:17
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30062` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by advancedngwarati** [comment] 2020-07-16 11:47
I'm facing this issue as well, did you managed to solve this @taihuuho ?

**Comment by pandurangbabar** [comment] 2020-07-17 11:41
I am also facing same issue. any solution to this @taihuuho

**Comment by Nazar65** [comment] 2020-10-01 13:35
@magento I am working on this

**Comment by victorpetryk** [comment] 2020-10-30 12:18
@magento I am working on this

**Comment by victorpetryk** [comment] 2020-11-02 12:32
Hi @taihuuho.
I used official **rabbitmq:3-management** from https://hub.docker.com/_/rabbitmq with configured **heartbeat = 1800**.
Also, I used your payload from https://github.com/magento/magento2/issues/25526#issuecomment-557391997 to import products as you described. But cannot reproduce the issue. Could you help with it? Is this issue still relevant to you?
(I used the **2.4-develop** branch)

**Comment by taihuuho** [comment] 2020-11-02 13:03
Hi Vikto,
I didn’t use docker container on a same machine. My RabbitMQ was on another
server.

This could be the reason when my magento server is far enough away from the
rabbit mq server.

Let me know if you can reproduce it with that set up.

**Comment by victorpetryk** [comment] 2020-11-02 13:08
@taihuuho Thank you for your response. I will try to apply your suggestions.
One more question - Is this payload (https://github.com/magento/magento2/issues/25526#issuecomment-557391997) suitable for this case?

**Comment by victorpetryk** [comment] 2020-11-03 12:10
Hi @taihuuho.
Could you provide your *rabbitmq.conf*?

**Comment by taihuuho** [comment] 2020-11-03 12:16
Hi Victor,
My apologies for late response.
I stop the server few months ago, so I don’t have the confit file any more.
Basically, I just installed the RabbitMQ server from their website and use
the default config. I got the error and then I increased the heart beat to
1800 s. Still go the same error.

You can try this payload
https://github.com/magento/magento2/issues/25526#issuecomment-552355582.

**Comment by victorpetryk** [comment] 2020-11-03 12:27
> Basically, I just installed the RabbitMQ server from their website and use
the default config.

@taihuuho In this case, your mean that the issue can be reproduced locally by using RabbitMQ on the same server as Magento installed?
Do you still use Magento 2.3.3 as you mentioned in the description?

**Comment by taihuuho** [comment] 2020-11-03 12:28
Yes, you can reproduce that locally.

And I no longer use Magento because of that issue. It happened on that
2.3.3 version

**Comment by victorpetryk** [comment] 2020-11-03 14:27
@taihuuho Unfortunately, I cannot reproduce the current issue locally even on 2.4-develop, 2.3.3-develop, and composer installation 2.3.3. I've recorded a video, so you can see my configs and steps.
![Peek 2020-11-03 16-16](https://user-images.githubusercontent.com/506103/97996930-0bf71c80-1df1-11eb-9dc9-6857d2e1f628.gif)

**Comment by taihuuho** [comment] 2020-11-03 14:49
That’s interesting. I’ll let into it and get back to you.
Thanks for looking into this for me.

**Comment by engcom-Echo** [comment] 2020-11-10 07:40
Hi, @taihuuho I checked it again, and now this issue can't reproduce. @victorpetryk came to the same result. 
So, I'm closing this issue.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Comment by advancedngwarati** [comment] 2020-11-26 07:01
Hi @engcom-Echo, I'm having the same issue. I'm using Magento 2.3.2. Check the screenshot below, same Magento command and error.

![Screenshot 2020-11-26 at 08 57 04](https://user-images.githubusercontent.com/45203079/100317911-d0054080-2fc5-11eb-91d1-8c8a9191e197.png)

**Comment by Nazar65** [comment] 2020-11-30 12:43
@magento I am working on this   (again)

**Comment by advancedngwarati** [comment] 2020-12-14 07:47
@Nazar65 any updates regarding this? I have a live site that is affected with this. Thank you.

**Comment by duckchip** [comment] 2021-03-23 12:03
can reproduce on 2.3.6-p2

**Comment by zakdma** [comment] 2021-04-12 11:35
@duckchip @taihuuho @pandurangbabar 
Thank you for your messages.
We cannot reproduce it as we wrote above. There are several possible reasons that can cause this issue and most of them not on Magento side. Among them: too small heartbeat, load balancer between Magento and RabbitMQ that has too small connection timeout,
Please refer to this comment for full list with explanation
https://github.com/php-amqplib/php-amqplib/issues/424#issuecomment-332090471
Please provide RabbitMQ logs also if you still can reproduce it.

**Closed as completed** 2021-07-14 22:59 UTC
Labels: Component: MessageQueue, Triage: Dev.Experience, Priority: P1, Severity: S1, Progress: done
