### ISSUE TITLE
Updating customer's email takes a lot of time if customer has a lot of orders 

### ISSUE THREAD

**Issue by jayankaghosh** [magento/magento2#36081] opened 2022-09-02 18:11 UTC
### Preconditions and environment

- Magento version - 2.4.4

### Steps to reproduce

1. Create a customer and place 100+ orders with the customer
2. Try to change the customer's email using REST API or GraphQL

### Expected result

The email change shouldn't take more than a few seconds

### Actual result

It is taking around 43 seconds for 107 orders. The time is directly dependent on number of orders placed

### Additional information

The `\Magento\Customer\Observer\UpgradeOrderCustomerEmailObserver::execute` is the culprit here. Magento is forced to load all of the customer's orders and save them one by one after changing the email. This is not ideal for a store having customer's with high order volume.

This can be optimized by replacing the 

         $searchCriteria = $this->searchCriteriaBuilder
            ->addFilter(OrderInterface::CUSTOMER_ID, $customer->getId())
            ->create();

        /**
         * @var Collection $orders
         */
        $orders = $this->orderRepository->getList($searchCriteria);
        $orders->setDataToAll(OrderInterface::CUSTOMER_EMAIL, $customerEmail);
        $orders->save();

code with a direct SQL multi-update query of some sort, since we don't need to load the orders. We just need to update all of them. And since sales_order is a flat table, it shouldn't take too much time.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-09-21 06:26
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-09-21 11:52
Hi @jayankaghosh,

Thank you for reporting and collaboration.


Verified the issue on Magento 2.4-develop branch but the issue is not reproducible.We are able to Update customer email with customer has 100+ orders with in a few seconds.Kindly refer the screenshots.

<img width="1171" alt="Screenshot 2022-09-21 at 5 17 49 PM" src="https://user-images.githubusercontent.com/51680745/191496376-032009f2-9569-47e5-b492-098a7c7d7b63.png">



<img width="1164" alt="Screenshot 2022-09-21 at 5 16 32 PM" src="https://user-images.githubusercontent.com/51680745/191496444-ba683371-5d49-408f-91ac-df9aaf250a8e.png">



Please let us know we miss anything.


Thanks.

**Comment by engcom-Bravo** [comment] 2022-10-07 06:18
Hi @jayankaghosh,


We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-10-07 06:18 UTC
Labels: Issue: needs update, Reported on 2.4.4

**Comment by GeertRoza** [comment] 2023-08-23 07:06
I have the same issue. Our b2b customers have lots of orders and for some it's not even possible to update anymore because it runs out of memory. Please fix this.

**Comment by mattiweb** [comment] 2024-01-18 16:43
I've also ran into this issue with a customer having 639 orders. When trying to edit their email through the admin it would also run out of memory. Tested locally by adding return; to the top of `\Magento\Customer\Observer\UpgradeOrderCustomerEmailObserver::execute` to prevent it from updating the orders. This then allowed me to save the customer

**Comment by ayushi011** [comment] 2024-02-08 13:25
Hi @jayankaghosh ,

I am facing same issue. Can you please share the solution?

**Comment by ayushi011** [comment] 2024-02-09 06:46
> I've also ran into this issue with a customer having 639 orders. When trying to edit their email through the admin it would also run out of memory. Tested locally by adding return; to the top of `\Magento\Customer\Observer\UpgradeOrderCustomerEmailObserver::execute` to prevent it from updating the orders. This then allowed me to save the customer

Hi @mattiweb 
Can you please share the solution?

**Comment by mattiweb** [comment] 2024-02-09 10:15
@ayushi011 I didn't fix the underlying issue but I disabled the functionality that updates all the customers orders with the new email by creating a custom module and inside the etc/events.xml I just disabled the event with the following. (more of a temp workaround)

```xml
<event name="customer_save_after_data_object">
        <observer name="upgrade_order_customer_email" disabled="true"/>
    </event>
```
You could also create an around plugin on `\Magento\Customer\Observer\UpgradeOrderCustomerEmailObserver::execute` with custom logic to prevent it
