### ISSUE TITLE
Search term minimum length is static

### ISSUE THREAD

**Issue by abelyanvahe** [magento/magento2#12053] opened 2017-11-06 08:41 UTC
### Preconditions

1. Magento v2.2
2 . Everything else does not matter

### Steps to reproduce

1. Search for a term which has less then 3 characters.

### Expected result

1. Should see some results

### Actual result

1. Results are empty

### Solution
This is because even though we have a field in admin to set this, minimum term length is hardcoded i Magento\Framework\Search\Adapter\Mysql\Query\Builder\Match 

const MINIMAL_CHARACTER_LENGTH = 3;

**Comment by magento-engcom-team** [comment] 2017-11-07 09:03
@abelyanvahe, thank you for your report.
We've created internal ticket(s) MAGETWO-83358 to track progress on the issue.

**Comment by p-bystritsky** [comment] 2017-12-15 14:05
Hello, @abelyanvahe. Seems like this value is hardcoded because of some mariaDB full-text issues.

**Comment by magento-engcom-team** [comment] 2019-02-20 07:31
Hi @ravi-chandra3197. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by sdzhepa** [comment] 2019-12-09 23:48
Closed as fixed.
https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Search/Adapter/Mysql/Query/Builder/Match.php#L33

**Closed as completed by sdzhepa** 2019-12-09 23:48 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Progress: PR Created
