### ISSUE TITLE
Show/Hide Editor sometimes not work

### ISSUE THREAD

**Issue by ClodClod** [magento/magento2#9069] opened 2017-03-31 07:39 UTC
HI guys,
sometimes, in pages and block, doesn't work Show/Hide editor (and there isn't any error in console js).

When click on this button nothing change and not show WYSIWYG editor.

![show-hide-editor-not-work](https://cloud.githubusercontent.com/assets/24482000/24541008/f40057ec-15f5-11e7-9b36-786560b04afd.JPG)

**Comment by ThakurPradeep** [comment] 2017-04-10 13:57
Plz below link:

https://github.com/magento/magento2/commit/3524943ac6544ee969480536ef6f0cd1a29b0b56

After edit file run below command:
1) sudo php bin/magento cache:flush
2) sudo php bin/magento setup:static-content:deploy

I hope it will working fine.

**Comment by kevingreek** [comment] 2017-05-19 20:42
It worked for me , thanks ThakurPradeep

**Comment by veloraven** [comment] 2017-06-26 12:49
@ClodClod please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by korostii** [comment] 2017-06-26 13:26
Possible duplicate of #6222, #4828, #6815

**Closed as completed** 2017-09-13 21:22 UTC
Labels: Progress: needs update, Issue:  Cannot Reproduce, Issue: Format is not valid
