### ISSUE TITLE
Adding category to product in store view scope does not generate all url rewrites

### ISSUE THREAD

**Issue by juhanihaapala** [magento/magento2#32910] opened 2021-04-30 05:20 UTC
### Preconditions (*)

1. Reproduced at least on Magento 2.3.1, 2.3.6-p1, 2.4.2

### Steps to reproduce (*)

1. Create 2 store views
2. Create category with anchor enabled (and in 2.4.2 make sure category/product url generation is enabled)
3. Add new product without category
4. Open product edit in storeview scope
5. Add product to category and save

### Expected result (*)

1. Category product urlrewrites are generated to both storeviews
![image](https://user-images.githubusercontent.com/3079827/116651731-82ce3600-a98c-11eb-8762-a178f139c930.png)

### Actual result (*)

1. Urlrewrites are generated only to the storeview where changes where made
![image](https://user-images.githubusercontent.com/3079827/116651700-6d590c00-a98c-11eb-9112-2a0d0c99da08.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment] 2021-04-30 13:17
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42144` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by SilinMykola** [comment] 2021-05-05 11:15
@magento I am working on this

**Comment by korovitskyi** [comment] 2022-01-31 15:18
@magento I am working on this

**Comment by engcom-Charlie** [comment] 2022-04-18 07:43
As per the [comment](https://github.com/magento/magento2/pull/35053#issuecomment-1098921847), closing this issue.

Thank you!

**Comment by hostep** [comment] 2022-04-20 13:04
@engcom-Charlie: you've not tested the expected scenario as described in this issue.

Please try again, but now only use **one** website, **one** store and **one** root category but **two** different storeviews.

I've just tried it myself on the `2.4-develop` branch (using commit 5807cd9a05f) and I was perfectly able to reproduce with the steps mentioned in the opening post.

@sidolov, @sdzhepa: I'm tagging you guys as well, because the engcom squad tends to ignore comments on closed issues. In my opinion this issue (and the connected PR) so get re-opened and re-tested because the issue was not tested correctly. Thanks!

**Comment by hostep** [comment] 2022-09-20 17:45
@engcom-November: in case you're wondering, after @engcom-Charlie's last comment here, we moved the discussion to [the associated PR](https://github.com/magento/magento2/pull/35053#issuecomment-1108685058), sorry for not leaving an update over here.

**Comment by engcom-Charlie** [comment] 2022-09-21 05:56
Hi @engcom-November,

Missed out to mention that latest update here which we have posted on PR.

As per the clarification from @hostep [here](https://github.com/magento/magento2/pull/35053#issuecomment-1103905337), I have reproduced the issue and mentioned the [steps](https://github.com/magento/magento2/pull/35053#issuecomment-1108607663) for the reproduction. Observed that issue is reproducible hence we proceed further on [PR](https://github.com/magento/magento2/pull/35053)


Thank you!

**Comment by engcom-November** [comment] 2022-09-21 10:57
Thanks for the update @engcom-Charlie , confirming this issue as its reproducible on 2.4-develop branch.
Thank you.

**Closed as completed** 2023-05-03 19:22 UTC
Labels: Component: Catalog, Issue: Confirmed, Component: UrlRewrite, Reproduced on 2.4.x, Priority: P2, Progress: done, Reported on 2.4.2, Area: Product
