### ISSUE TITLE
Cannot batch-print invoices from the orders grid

### ISSUE THREAD

**Issue by JacobDrummond** [magento/magento2#5639] opened 2016-07-14 14:29 UTC
## Steps to reproduce
1. Install Magento 2.1.0.
2. Place some orders, and generate some invoices
3. Verify that the invoices have been generated in Admin > Sales > Operations > Invoices:
   ![1](https://cloud.githubusercontent.com/assets/8377620/16842623/0b3bdb26-49d6-11e6-9f1c-9931222fec90.png)
4. Try to batch-print these invoices in Sales > Orders:
   ![2](https://cloud.githubusercontent.com/assets/8377620/16842753/7322c998-49d6-11e6-9444-d906a960d288.png)
## Expected result
1. Invoice Collection rendered as PDF
## Actual result
1. "There are no printable documents related to selected orders":
   ![3](https://cloud.githubusercontent.com/assets/8377620/16842779/8cafdb62-49d6-11e6-9da9-cb14068b8373.png)
## Problem
1. The $collection argument passed to [Magento\Sales\Controller\Adminhtml\Order\Pdfinvoices::massAction()](https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/Controller/Adminhtml/Order/Pdfinvoices.php) is an instance of Magento\Sales\Model\ResourceModel\Order\Invoice\Collection.
2. The line
   `$invoicesCollection = $this->collectionFactory->create()->setOrderFilter(['in' => $collection->getAllIds()]);` filters $invoicesCollection with setOrderFilter() using a an array of invoice IDs, not order IDs
3. Apparently it should be `$invoicesCollection = $this->collectionFactory->create()->addAttributeToFilter('entity_id', ['in' => $collection->getAllIds()]);`.

**Comment by maderlock** [comment] 2016-07-15 17:50
This is a duplicate of an existing issue #4974 which was incorrectly closed, so it's great to see a suggested fix. Hopefully this will get sorted now. I'll give it a test.

**Comment by JacobDrummond** [comment] 2016-07-18 15:38
Hi @maderlock, were you able to replicate the issue, and confirm that the suggested fix works?

**Comment by Danielc3** [comment] 2016-07-21 11:20
The recommended fix on the above post did not work due to an empty collection getting passed into massAction. The issues lies around Magento\Ui\Component\MassAction\Filter. The getCollection function of this class is called within Magento\Sales\Controller\Adminhtml\Order\AbstractMassAction and then this collection is passed into massAction. The issue with what is happening within this getCollection function is that document->getId() returns an order ID, $collection->addFieldToFilter($collection->getIdFieldName(), ['in' => $ids]); is then used, the ID field name being the entity_id. So essentially it ends up filtering an invoice collection by entity IDs, using an array of order IDs. As this is quite an abstract class, the problem most likely revolves around the document itself and what it's ID is set to be. What you end up with is an empty invoice collection by the time you have got to massAction.

**Comment by maderlock** [comment] 2016-09-01 11:36
So I'm guessing that this is not fixed in 2.1.1? It's a major sticking point for clients that rely on the order grid to process orders (as seems reasonable). They currently have to move back and forth between the invoice grid for printing and the order grid for other tasks. Given #6438 on top of this, the invoice grid is hard to use itself if you have customers using PayPal.

Please please put some effort into these order-related bugs.

**Comment by JacobDrummond** [comment] 2016-09-14 13:38
@veloraven, we're approaching the 14-day inactivity cutoff for open issues. Has this issue been replicated by the Magento team?

**Comment by pboisvert** [comment] 2016-09-14 14:26
@JacobDrummond  To be clear the 14-day inactivity applies only to issues where Magento has requested more information in order to reproduce an issue. There is no "needs update" label on this issue which indicates we are still investigating and trying to reproduce-so no inactivity clock running on this one.

**Comment by davidaddison** [comment] 2016-10-21 15:37
Do we have a fix on this yet?  This one is a big problem for any store with significant order volume.

**Comment by sma09sjb** [comment] 2016-12-01 15:52
Can i get an update on this, we have this exact same problem, i've just debugged and the collection being passed is empty. This is when the grid is filtered by status. The Print All mass action seems to be working strangely.

This is a significant problem, the needs to be looked at as soon as possible.

**Comment by oleg-onufer** [comment] 2017-06-19 13:26
Unfortunately, I could not reproduce the issue as you described it. Can you reproduce this issue on latest version of Magento2?

**Closed as completed** 2017-09-18 17:10 UTC
Labels: bug report, Progress: needs update, Issue:  Cannot Reproduce, Issue: Format is not valid
