### ISSUE TITLE
Undefined index: media_type while addImage to product

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#14407] opened 2018-03-28 06:15 UTC
### Preconditions

1. Magento 2.2.1 CE
2. 

### Steps to reproduce

1. Use Magento\Catalog\Model\Product\Gallery\Processor: addImage function to add an image to a product.
2. 
3. 

### Expected result

1. Image should get added.

### Actual result

1. Message: Notice: Undefined index: media_type in /vendor/magento/module-catalog/Model/Product.php on line 2554 

We have tried to find the comparison between 2.2.1 and 2.2.2. We got this which is causing issue:
in addImage function:(media_type) is missing which is causing issue.
![image](https://user-images.githubusercontent.com/6079017/38012017-621eba80-327d-11e8-9649-3195048c5a20.png)

Please check.

**Comment by ankursachdeva11** [comment] 2018-03-28 07:13
In Addition to this,

if we use $product->addImageToMediaGallery(params); and then $product->save() function to add images.
still we are getting error: Message: Notice: Undefined index: media_type in /vendor/magento/module-catalog/Model/Product.php on line 2554

**Comment by magento-engcom-team** [comment] 2018-03-30 13:19
@ankursachdeva11 , thank you for your report . Duplicate of #6803

**Closed as completed by magento-engcom-team** 2018-03-30 13:19 UTC
Labels: non-issue, Issue: Format is valid

**Comment by magento-engcom-team** [comment] 2018-03-30 13:30
@ankursachdeva11, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
