### ISSUE TITLE
Product attributes product_type, type_id cannot be created/edited form admin

### ISSUE THREAD

**Issue by IgorM92** [magento/magento2#28479] opened 2020-06-02 19:27 UTC
### Preconditions (*)

1. Magento 2.3.5-p1

### Steps to reproduce (*)

1. _IF_ product attributes with following code does not exist `product_type` or `type_id` then attempt to create any of them
2. _ELSE_ edit any of them and change anything

### Expected result (*)

- Attribute is not saved. Error message is shown
-  text:  _Code "product_type" is a reserved key and cannot be used as attribute code._
- text:  _Code "type_idis" a reserved key and cannot be used as attribute code._

### Actual result (*)

1. Either of following messages appear `An attribute with this code already exists.` _OR_ `An attribute with the same code (product_type) already exists.`
![product_type](https://user-images.githubusercontent.com/7593380/83560721-97047b80-a50e-11ea-893f-3ed96539c893.JPG)
![type_id](https://user-images.githubusercontent.com/7593380/83560722-979d1200-a50e-11ea-82d5-1e4d3bdc5afc.JPG)

**It's** due to following line of code https://github.com/magento/magento2/blob/39012d4ea79157cb12eef348cc3448d955c0ecc5/app/code/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Validate.php#L130 implemented in https://github.com/magento/magento2/commit/ca0da34ee2691bfaca1c74d94a0db33377d4e54c#diff-9ff38a88c1abf86286f77b64c8bc9b38 and https://github.com/magento/magento2/commit/b9d13e69c4928a0b6d740845bed305a399a42fd5#diff-9ff38a88c1abf86286f77b64c8bc9b38

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by swathishs** [comment] 2020-06-03 04:47
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-03 04:47
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-06-03 04:49
Hi @swathishs, here is your [Magento instance](https://i-28479-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28479-2-4-develop.instances.magento-community.engineering/admin_7697](https://i-28479-2-4-develop.instances.magento-community.engineering/admin_7697)
Login: `f178f522` Password: `1608965c8c8a`
Instance will be terminated in up to 3 hours.

**Comment by IgorM92** [comment] 2020-06-03 20:26
@swathishs any updates on this one?

**Comment by swathishs** [comment] 2020-06-04 08:14
@IgorM92: The issue is reproducible in Magento 2.4 develop instance. 

Please find the attachment below:
![image](https://user-images.githubusercontent.com/58288685/83713625-32e4d300-a646-11ea-824e-348d84b4582a.png)
![image](https://user-images.githubusercontent.com/58288685/83713628-3710f080-a646-11ea-8da9-600a54927630.png)

**Comment by magento-engcom-team** [comment] 2020-06-04 12:34
:white_check_mark: Confirmed by @swathishs 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34952` were created

**Issue Available**: @swathishs, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Echo** [comment] 2020-06-05 12:16
Hi, @swathishs @IgorM92 
I wanted to warn you against using such values ​​for "Default value". There was a case but vice versa.
[product_type attribute contains incorrect value in mass import export csv after creating custom type_id attribute. actual type_id value in database gets change with newly created attribute type_id.
](https://github.com/magento/magento2/issues/19891)

I think an additional discussion would be helpful.

**Comment by IgorM92** [comment] 2020-06-07 04:11
@engcom-Echo could you help me with following question:
Does `product_type` and `type_id` product attributes get created with magento installation ?

**Comment by AbdulRahmanAbouzaid** [comment] 2020-06-08 16:04
@IgorM92 @swathishs @engcom-Echo 
I think that `product_type` and `type_id` are both used to describe the product type (simple, Downloadable, ..... ).
The `type_id` can be found as a column in `catalog_product_entity` table which used as `product_type` in many places in code and import/export operations. So they look like **reserved keys** that cannot be used in naming custom attributes.

So I think the issue is not about "Cannot create/update attribute with product_type & type_id codes" but it's about showing more meaningful error message instead of `An attribute with the same code already exists.` but there isn't which making us confused!.
If it makes sense, you can update the issue please.

**Comment by sdzhepa** [comment] 2020-06-12 19:13
Hello @IgorM92 @AbdulRahmanAbouzaid

Thank you for your report and collaboration!

This issue has been reviewed and discussed during the Triage Meeting with Magento Product Managers.

The results and resolution based on https://github.com/magento/magento2/issues/28479#issuecomment-640722555
-  `product_type` and `type_id`  are **reserved keys** in Magento that in use through a lot of functionality. So, allowing to save such names will required a lot of effort for development and testing and the final value does not worth it
- But agree that we can improve error message to avoid possible confusion 

The expected result should be updated:
- Error message text:  _Code "product_type" is a reserved key and cannot be used as attribute code._
- Error message text:  _Code "type_idis" a reserved key and cannot be used as attribute code._

**Comment by AbdulRahmanAbouzaid** [comment] 2020-06-12 20:26
@sdzhepa 
Thanks for your comment. I already provided this PR #28663 that updated the error message in that case.
Can you please review it?

**Comment by IgorM92** [comment] 2020-06-12 22:07
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-12 22:07
Hi @IgorM92. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-06-12 22:08
Hi @IgorM92, here is your [Magento instance](https://i-28479-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28479-2-4-develop.instances.magento-community.engineering/admin_b2ff](https://i-28479-2-4-develop.instances.magento-community.engineering/admin_b2ff)
Login: `b3b2b52a` Password: `7a51914455ac`
Instance will be terminated in up to 3 hours.

**Comment by IgorM92** [comment] 2020-06-12 22:17
@swathishs @AbdulRahmanAbouzaid @sdzhepa first i would like to apologise to all of you.

First of all i've realised that i have not provided in `Steps to reproduce` point 2 more information and `ELSE edit any of them and change anything` does not indicate to the problem i was facing.

**Overall** the issue i've stumbled across was that in admin panel i could not edit labels for attribute `product_type`, based on this can any of you answer to the following questions:

1. Is `product_type` and `type_id` attributes visible in admin by default ? (on a project i am working on it was visible, if answer to this question is no then most likely in my project in the past it was updated to be visible in admin panel)
2. _IF_ answer to question 1 is yes then: How to update Labels and Storefront properties from admin for these attributes ?

![image](https://user-images.githubusercontent.com/7593380/84550574-e878eb80-ad02-11ea-9432-6900d606281c.png)

**Comment by Ig0r-M-magic42** [comment] 2020-06-13 15:27
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment] 2020-06-13 15:27
Hi @Ig0r-M-magic42. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment] 2020-06-13 15:29
Hi @Ig0r-M-magic42, here is your [Magento instance](https://i-28479-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-28479-2-3-5-p1.instances.magento-community.engineering/admin_4e07](https://i-28479-2-3-5-p1.instances.magento-community.engineering/admin_4e07)
Login: `abb3982d` Password: `a2c463f811a2`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2020-09-24 00:56
Hi @IgorM92. Thank you for your report. 
The issue has been fixed in magento/magento2#28663 by @AbdulRahmanAbouzaid in 2.4-develop branch
Related commit(s):
 - [580ffe52adecf0030d21b3fc7bf046706680324a](https://github.com/magento/magento2/commit/580ffe52adecf0030d21b3fc7bf046706680324a)
 - [9bc6cc96e8437d7f7de6a0bee70e1ecd825c171c](https://github.com/magento/magento2/commit/9bc6cc96e8437d7f7de6a0bee70e1ecd825c171c)
 - [74aaccde20d0a9e6fc493129c38905a62f3daa97](https://github.com/magento/magento2/commit/74aaccde20d0a9e6fc493129c38905a62f3daa97)
 - [9c38339d795d962b83556b2ecf62eaf92899f7b2](https://github.com/magento/magento2/commit/9c38339d795d962b83556b2ecf62eaf92899f7b2)
 - [f9374c8f5181de605e90a0aa94de7846a374b03a](https://github.com/magento/magento2/commit/f9374c8f5181de605e90a0aa94de7846a374b03a)
 - [86f0c6b382af6b8566faa6eb9c616c74a33cf837](https://github.com/magento/magento2/commit/86f0c6b382af6b8566faa6eb9c616c74a33cf837)
 - [e95d5d28c3554ebed76749c015df147469a645bd](https://github.com/magento/magento2/commit/e95d5d28c3554ebed76749c015df147469a645bd)
 - [d396c0a235c3b70e17f953236a6547a4daf1ec82](https://github.com/magento/magento2/commit/d396c0a235c3b70e17f953236a6547a4daf1ec82)
 - [1d0b91b419b0b21a56569b4ced87a39309cb2b33](https://github.com/magento/magento2/commit/1d0b91b419b0b21a56569b4ced87a39309cb2b33)
 - [c9a1afa700380c7994f36cf597164cc6faae6038](https://github.com/magento/magento2/commit/c9a1afa700380c7994f36cf597164cc6faae6038)
 - [804a049cd3a1063417ac70fb8ec51450d9251d53](https://github.com/magento/magento2/commit/804a049cd3a1063417ac70fb8ec51450d9251d53)
 - [1ea5d753f581f4997cc8da3efcd9ded6c5722345](https://github.com/magento/magento2/commit/1ea5d753f581f4997cc8da3efcd9ded6c5722345)
 - [2206f77a69e0a3249ae386f2cd8f4b70cf822197](https://github.com/magento/magento2/commit/2206f77a69e0a3249ae386f2cd8f4b70cf822197)

The fix will be available with the upcoming 2.4.2 release.

**Closed as completed by magento-engcom-team** 2020-09-24 00:56 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Admin, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P3, Severity: S4, Triage: Done, Progress: done, Reported on 2.3.5-p1

**Comment by maxq** [comment] 2023-08-18 14:50
Still seeing this in 2.4.5 where is the fix?
