### ISSUE TITLE
Tax Rounding Warning inconsistent with Docs

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#30591] opened 2020-10-21 16:29 UTC
### Preconditions (*)

1. 2.4-develop

### Steps to reproduce (*)

1. Store -> Configuration -> Sales -> Tax -> Tax Calculation Method Based On = Row Total
2. Store -> Configuration -> Sales -> Tax -> Display Product Prices In Catalog = Including and Excluding Tax
2. Store -> Configuration -> Sales -> Tax -> Catalog Prices = Excluding Tax
Save Config

### Expected result (*)

1. According to https://docs.magento.com/user-guide/tax/warning-messages.html This combination should not result in TAX rounding errors and the warning should not be displayed.

### Actual result (*)

1. Tax rounding warning is displayed.
2. Who is right, the docs or the software????

### Additional info from Engcom
According to the [documentation](https://docs.magento.com/user-guide/tax/warning-messages.html#tax-calculation-method-based-on-excluding-tax) when _Tax calculation method based on: excluding tax_ Row Total
![row_total](https://user-images.githubusercontent.com/51680745/103537365-f491e980-4e9c-11eb-9863-bdde91b327ff.png)
OK - which means that the Warning should not appear

But still, a warning message appears
![image](https://user-images.githubusercontent.com/51680745/103536589-7aad3080-4e9b-11eb-95dc-717b03790685.png)

We confirm that it is reproducible on the latest 2.4-develop.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2021-01-04 12:58
Hello @gwharton 

Thank you for your report.

According to the [documentation](https://docs.magento.com/user-guide/tax/warning-messages.html#tax-calculation-method-based-on-excluding-tax) when _Tax calculation method based on: excluding tax_ Row Total
![row_total](https://user-images.githubusercontent.com/51680745/103537365-f491e980-4e9c-11eb-9863-bdde91b327ff.png)
OK - which means that the Warning should not appear

But still, a warning message appears
![image](https://user-images.githubusercontent.com/51680745/103536589-7aad3080-4e9b-11eb-95dc-717b03790685.png)

This looks like a Functional issue.

We confirm that it is reproducible on the latest 2.4-develop.

Thank you

**Comment by magento-engcom-team** [comment] 2021-01-04 13:02
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40275` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dverkade** [comment] 2021-03-22 11:48
Reproduced issues should not be closed automatically.

**Comment by Bashev** [comment] 2021-09-07 17:29
@gwharton i cannot reproduce it. Can you confirm this issue is already stale?

**Comment by engcom-Bravo** [comment] 2024-05-30 06:38
Hi @gwharton,

Thanks for your reporting and collaboration.

We have verified the issue in latest 2.4-develop instance and it looks like an expected behaviour.

<img width="1438" alt="Screenshot 2024-05-30 at 11 55 17" src="https://github.com/magento/magento2/assets/51680745/48382027-a13f-4a9d-8acf-01c9b3e3b7d5">

https://experienceleague.adobe.com/en/docs/commerce-admin/stores-sales/site-store/taxes/taxes#warning-messages

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-05-30 06:38 UTC
Labels: Component: Tax, Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Progress: done, Reported on 2.4.0
