### ISSUE TITLE
Source object showing blank in kingswaysoft

### ISSUE THREAD

**Issue by bhpatelsynoptek** [magento/magento2#36858] opened 2023-02-14 06:39 UTC
I have created connection manager in kingswaysoft and its successfully connected but source object not showing me any other setting in magento please let me know
![Magento](https://user-images.githubusercontent.com/124891001/218658860-75d247f8-2a84-4c99-8ab4-a9c00f2ef21a.jpg)

**Comment by bhpatelsynoptek** [comment] 2023-02-14 06:58
Hi Team,
I have a done successfully connection in kingswaysoft but source object is not enable, it was showing me blank.
Kindly guide us how can get it or any other setting in magento.
I am using demo version of megento and url is as below.
https://axcrmservice.dynu.net:9501/qamagentoextce/pub/admin

***@***.***

***@***.***

[A picture containing drawing  Description automatically generated]<https://synoptek.com/>
Bharat Patel
Technical Lead, dynamics 365 business Central
091/9408346130 m
***@***.***<https://twitter.com/Synoptek>   ***@***.*** <https://www.facebook.com/synoptekservice/>    ***@***.*** <https://www.linkedin.com/company/synoptek/>
The information in this email, and any attachments, may contain confidential information and is intended solely for the attention and use of the named addressee(s). It must not be disclosed to any person(s) without authorization. If you are not the intended recipient, or a person responsible for delivering it to the intended recipient, you are not authorized to, and must not, disclose, copy, distribute, or retain this message or any part of it. If you have received this communication in error, please notify the sender immediately.

**Comment by engcom-Dash** [comment] 2023-02-14 17:39
Hi @bhpatelsynoptek ,

Kindly Provide more information about this Issue ,Because its very easy to proceed further as well as kindly attach below information.

Precondition
Steps to reproduce
Actual result
Expected Result
Additional Information

Thanks

**Comment by bhpatelsynoptek** [comment] 2023-02-15 05:30
Hi Team,
As we mention in this case.
I am using demo environment of magento and URL is - https://axcrmservice.dynu.net:9501/qamagentoextce/pub/admin
I want to connect in Kingsway soft through connection manager, I am giving all credential as we requested in Kingsway but I am unable to generate token.

Step 1 :
***@***.***

Step 2 – Generate Token
***@***.***

Step 3 – getting error.

***@***.***


[A picture containing drawing  Description automatically generated]<https://synoptek.com/>
Bharat Patel
Technical Lead, dynamics 365 business Central
091/9408346130 m
***@***.***<https://twitter.com/Synoptek>   ***@***.*** <https://www.facebook.com/synoptekservice/>    ***@***.*** <https://www.linkedin.com/company/synoptek/>
The information in this email, and any attachments, may contain confidential information and is intended solely for the attention and use of the named addressee(s). It must not be disclosed to any person(s) without authorization. If you are not the intended recipient, or a person responsible for delivering it to the intended recipient, you are not authorized to, and must not, disclose, copy, distribute, or retain this message or any part of it. If you have received this communication in error, please notify the sender immediately.

**Comment by bhpatelsynoptek** [comment] 2023-02-17 05:43
Is there any solution?

[A picture containing drawing  Description automatically generated]<https://synoptek.com/>
Bharat Patel
Technical Lead, dynamics 365 business Central
091/9408346130 m
***@***.***<https://twitter.com/Synoptek>   ***@***.*** <https://www.facebook.com/synoptekservice/>    ***@***.*** <https://www.linkedin.com/company/synoptek/>
The information in this email, and any attachments, may contain confidential information and is intended solely for the attention and use of the named addressee(s). It must not be disclosed to any person(s) without authorization. If you are not the intended recipient, or a person responsible for delivering it to the intended recipient, you are not authorized to, and must not, disclose, copy, distribute, or retain this message or any part of it. If you have received this communication in error, please notify the sender immediately.



From: Bharat Patel ***@***.***>
Sent: Wednesday, February 15, 2023 11:00 AM
To: magento/magento2 ***@***.***>; magento/magento2 ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [magento/magento2] Source object showing blank in kingswaysoft (Issue #36858)

Hi Team,
As we mention in this case.
I am using demo environment of magento and URL is - https://axcrmservice.dynu.net:9501/qamagentoextce/pub/admin
I want to connect in Kingsway soft through connection manager, I am giving all credential as we requested in Kingsway but I am unable to generate token.

Step 1 :
***@***.***

Step 2 – Generate Token
***@***.***

Step 3 – getting error.

***@***.***


[A picture containing drawing  Description automatically generated]<https://synoptek.com/>
Bharat Patel
Technical Lead, dynamics 365 business Central
091/9408346130 m
***@***.***<https://twitter.com/Synoptek>   ***@***.*** <https://www.facebook.com/synoptekservice/>    ***@***.*** <https://www.linkedin.com/company/synoptek/>
The information in this email, and any attachments, may contain confidential information and is intended solely for the attention and use of the named addressee(s). It must not be disclosed to any person(s) without authorization. If you are not the intended recipient, or a person responsible for delivering it to the intended recipient, you are not authorized to, and must not, disclose, copy, distribute, or retain this message or any part of it. If you have received this communication in error, please notify the sender immediately.

**Comment by engcom-November** [comment] 2023-02-23 04:16
Hi @bhpatelsynoptek ,
Thank you for reporting and collaboration. However, kingswaysoft is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.

**Closed as completed by engcom-November** 2023-02-23 04:16 UTC
Labels: Component: Bundled Extension, Issue: needs update

**Comment by bhpatelsynoptek** [comment] 2023-03-03 05:07
Hi Team,
My problem is still as it is.
Can we set a schedule call show that I can show you exactly what happen.
I am very thankful to you if you can schedule quickly.

[A picture containing drawing  Description automatically generated]<https://synoptek.com/>
Bharat Patel
Technical Lead, dynamics 365 business Central
091/9408346130 m
***@***.***<https://twitter.com/Synoptek>   ***@***.*** <https://www.facebook.com/synoptekservice/>    ***@***.*** <https://www.linkedin.com/company/synoptek/>
The information in this email, and any attachments, may contain confidential information and is intended solely for the attention and use of the named addressee(s). It must not be disclosed to any person(s) without authorization. If you are not the intended recipient, or a person responsible for delivering it to the intended recipient, you are not authorized to, and must not, disclose, copy, distribute, or retain this message or any part of it. If you have received this communication in error, please notify the sender immediately.
