### ISSUE TITLE
Need to change page count filter

### ISSUE THREAD

**Issue by fosco37** [magento/magento2#36753] opened 2023-01-18 18:52 UTC
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

![image](https://user-images.githubusercontent.com/123015589/213268817-857209f9-7736-4097-bb01-be6c4c9e974e.png)

### Expected result

Change page count

### Actual result

Wheel does not spinning

### Additional information

![image](https://user-images.githubusercontent.com/123015589/213268940-b2930bcc-9f0e-4f35-bf54-3276cf5c9351.png)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2023-01-19 04:30
@magento give me 2.4-develop instance

**Comment by TheBadong** [comment] 2023-01-19 08:10
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2023-01-19 09:10
Hi @fosco37 ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance but the issue is not reproducible with the provided information.
![image](https://user-images.githubusercontent.com/60198231/213399064-fa7b9565-bef9-4749-931d-ddddec78482e.png)
However there are 2 below ongoing similar confirmed issues with filtering. Kindly move onto these issues for latest updates / solutions if you are facing issues on Magento 2.4-develop instance.
https://github.com/magento/magento2/issues/36439
https://github.com/magento/magento2/issues/35466

**Comment by fosco37** [comment] 2023-01-19 14:17
Please kindly advise. I am currently using google chrome to access Magento. This is where I am experiencing an issue with loading the orders page. I am not a developer so the articles do not help much. I have attached a screenshot of the issue and the version of Magento that is published to me. I have tried multiple browsers (chrome, edge, firefox ; incognito mode) and different machines. The issue occurs on every platform which makes me believe it has to do with the website or my account. I am able to get to Custom Orders just fine and exporting works as well. It's just the Orders page that will not load.


Ed Cohen
Pro World
www.proworldinc.com
856-356-6104







powered by 

--- original message ---
On January 19, 2023 at 4:10 AM EST ***@***.*** wrote:



Hi @fosco37 ,

Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance but the issue is not reproducible with the provided information.


However there are 2 below ongoing similar confirmed issues with filtering. Kindly move onto these issues for latest updates / solutions if you are facing issues on Magento 2.4-develop instance.

#36439

#35466

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you were mentioned.Message ID: ***@***.***>
--- end of original message ---

**Comment by fosco37** [comment] 2023-01-19 14:24
Also, other users of Magento in our company are not having a problem.



Ed Cohen
Pro World
www.proworldinc.com
856-356-6104







powered by 

--- original message ---
On January 19, 2023 at 9:16 AM EST ***@***.*** wrote:


Please kindly advise. I am currently using google chrome to access Magento. This is where I am experiencing an issue with loading the orders page. I am not a developer so the articles do not help much. I have attached a screenshot of the issue and the version of Magento that is published to me. I have tried multiple browsers (chrome, edge, firefox ; incognito mode) and different machines. The issue occurs on every platform which makes me believe it has to do with the website or my account. I am able to get to Custom Orders just fine and exporting works as well. It's just the Orders page that will not load.



Ed Cohen

Pro World

www.proworldinc.com

856-356-6104








powered by 



> On January 19, 2023 at 4:10 AM EST ***@***.*** wrote:



> Hi @fosco37 ,

> Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance but the issue is not reproducible with the provided information.


> However there are 2 below ongoing similar confirmed issues with filtering. Kindly move onto these issues for latest updates / solutions if you are facing issues on Magento 2.4-develop instance.

> #36439

> #35466

> —

> Reply to this email directly, view it on GitHub, or unsubscribe.

> You are receiving this because you were mentioned.Message ID: ***@***.***>
--- end of original message ---

**Comment by engcom-November** [comment] 2023-01-25 10:55
Hi @fosco37 ,
Thank you for the response. There are ongoing open confirmed issues with filtering [#36439](https://github.com/magento/magento2/issues/36439), 
 [#35466](https://github.com/magento/magento2/issues/35466) which are not fixed yet. 
As a temporary workaround, please check below possible cases / solutions that may help you resolve the issue.
1. Sometimes, this error can occur due to version upgrade. Check "catalog_product_entity" table in Database and verify if any Products have NULL as SKU value
Run the SQL query: SELECT * FROM catalog_product_entity WHERE sku IS NULL to check all product not have sku NULL, then update them.
2. Another temporary fix is to clear "ui_bookmark table". > TRUNCATE ui_bookmark;
3. Also make sure to clear cache and add necessary permission/rights.
Thank you.

**Comment by engcom-November** [comment] 2023-02-09 05:10
Hi @fosco37 ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2023-02-09 05:10 UTC
Labels: Issue: needs update
