### ISSUE TITLE
Magento/ImportExport/Model/Import has _coreConfig declared dynamically

### ISSUE THREAD

**Issue by kisroman** [magento/magento2#21998] opened 2019-03-28 09:42 UTC
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1. See Magento/ImportExport/Model/Import class.
2. Find _coreConfig in construct.

### Expected result (*)

1.  Field should no be declared dynamically
2.

### Actual result (*)

1. Field is declared dynamically
2.

**Comment by magento-engcom-team** [comment] 2019-03-28 09:42
Hi @kisroman. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kisroman do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-03-29 19:13
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98979` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-04-09 16:15
Hi @kisroman. Thank you for your report. 
The issue has been fixed in magento/magento2#21999 by @kisroman in 2.3-develop branch
Related commit(s):
 - [1fe977a11c238b19e6f79342bed637bc7941bea8](https://github.com/magento/magento2/commit/1fe977a11c238b19e6f79342bed637bc7941bea8)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-04-09 16:15 UTC
Labels: Issue: Ready for Work, Component: ImportExport, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Progress: PR Created
