### ISSUE TITLE
CSP Module and different CDN domain

### ISSUE THREAD

**Issue by esteban-serfe** [magento/magento2#34119] opened 2021-09-17 17:56 UTC
### Preconditions (*)
1. Magento 2.4.2
2. Configure an URl for the BaseUrl value (example.com)
3. CDN fields (base_static_url & base_media_url) poiting to the CDN (outside the main domain: cdn-2dd2-do.cloudcdnexample.com)
4. Magento_Csp module is enabled

### Steps to reproduce (*)
1. Open the homepage

### Expected result (*)
1. Webpage should render completelly and whith styles.
2. CSP module should display the domain into the headers automatically.

### Actual result (*)
1. CSP is blocking the CDN domain used ont he base_static_url & base_media_url
2. Site looks broken and without styles or images

### Current workarround
1. Add a module and add the domain into the etc/csp_withlist.xml for all the possible options.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2021-09-24 10:57
Verified the issue on Magento 2.4-develop branch and the issue is reproducible with above mentioned steps followed:
On configuring CDN fields "Base URL for Static View Files" and "Base URL for User Media Files" (Admin - Stores - Configuration - Web) - Webpage is broken.
![image](https://user-images.githubusercontent.com/60198231/134663584-a8c3b050-1654-4227-ae55-8ceba4b197b3.png)

**Comment by engcom-Alfa** [comment] 2021-11-02 10:35
Since there are discussions going on about this issue, moving back to the previous status!
Thanks for your patience!

**Comment by engcom-November** [comment] 2021-11-25 07:31
Hi @EstebanSerfe ,
We are not able to reproduce the issue on Magento 2.4-develop branch.
Also, as per the [Magento docs](https://docs.magento.com/user-guide/system/media-storage-content-delivery-network.html) , for security, when a CDN is used as media storage, JavaScript may not function properly if the CDN is located outside of your subdomain.
Kindly recheck again on 2.4-develop branch and elaborate missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2021-12-24 11:21
Hi @esteban-serfe ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-12-24 11:21 UTC
Labels: Issue:  Cannot Reproduce, Component: Url, Progress: done, Issue: needs update, Reported on 2.4.2, Area: Admin UI

**Comment by engcom-November** [comment] 2021-12-27 08:16
Hi @esteban-serfe ,
We are closing this issue as there has been no latest update on the same.
Thank you.
