### ISSUE TITLE
The System and Store Language aren't changed

### ISSUE THREAD

**Issue by francisrod01** [magento/magento2#7935] opened 2016-12-22 13:36 UTC
Hi all! I have a problem with system and stores languages.
My Magento version is **2.1.3**
**Server OS:** Ubuntu 14.04 LTS
The `root path` and all files from website found as `www-data`

I configure the _System Language_ to **Portuguese (Brazil)**:

![bug_system_language](https://cloud.githubusercontent.com/assets/4691768/21426510/671f3ada-c836-11e6-84ab-33cfee36302a.png)

.
And I configure the _Store language_ to **Portuguese**:

![bug_store_languages](https://cloud.githubusercontent.com/assets/4691768/21426508/66c967e0-c836-11e6-861e-e4eab650f857.png)

.
Step two, I cleaned the **Page Cache** and **Configuration**.

![bug_store_languages_flush_cache](https://cloud.githubusercontent.com/assets/4691768/21426509/67139248-c836-11e6-829b-6e0f5fade6e6.png)

.
And store is English yet:

![bug_store_language_english_yet](https://cloud.githubusercontent.com/assets/4691768/21427176/0c4dd6ee-c83a-11e6-8b0d-fffd8bae433e.png)

![bug_language_static_content](https://cloud.githubusercontent.com/assets/4691768/21426507/66be0896-c836-11e6-9e27-5e9e6644ced5.png)

.
What's going on with Magento 2?

**Comment by elenleonova** [comment] 2016-12-22 21:18
Hi @devtosystems, Magento 2 doesn't include localization files at the moment, so that's why you don't see any changes in the content. You would need to add localization package in order to see a change.

Please, let me know if you have any other concerns, but at the moment i'm closing a ticket since it's not a bug.

**Closed as completed by elenleonova** 2016-12-22 21:18 UTC

**Comment by francisrod01** [comment] 2016-12-22 22:49
Humm I understand, but ... @elenleonova  does it mean that this version 2 is only available in English?
Sorry for asking here, but in the installation guide and version 2 doc I did not report this limitation previously.
