### ISSUE TITLE
Cannot update Store e-mail addresses for four-character domain extensions

### ISSUE THREAD

**Issue by kamaleshdubey** [magento/magento2#8521] opened 2017-02-11 19:45 UTC
### Preconditions

1. Magento CE v2.1.4
2. 

### Steps to reproduce

1. Login to Admin Panel
2. Go to Stores > Configuration > Store Email Addresses
3. Edit any of the default e-mail addresses for General Contact, Sales Representative, Customer Support, etc. In our example we have used ornate@ornate.shop. Using .info domain extension produces the same effect.
4. Click on Save Config button.

### Expected result

1. The e-mail address should be saved.

### Actual result

1. E-mail address is not updated, and an error message is displayed asking for correct e-mail address to be displayed:
<img width="960" alt="2017-02-11" src="https://cloud.githubusercontent.com/assets/16374186/22856883/92b28650-f092-11e6-9fa2-5aa0447e609d.png">

**Comment by o-iegorov** [comment] 2017-03-15 08:28
This is duplicate of the https://github.com/magento/magento2/issues/7697 and https://github.com/magento/magento2/issues/4547 issues

**Comment by magento-engcom-team** [comment] 2017-10-04 07:30
@kamaleshdubey, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-04 07:30 UTC
Labels: Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
