### ISSUE TITLE
Onestep checkout and multishipping disabled - no "go to checkout" button in the shopping cart

### ISSUE THREAD

**Issue by rrebisz** [magento/magento2#26889] opened 2020-02-15 21:22 UTC
With onestep checkout turned off and multishipping turned off, it is not possible to place an order.

### Preconditions (*)
1. Magento 2.3.4 commerce
2. Chrome 80.0.3987.106

### Steps to reproduce (*)
1. go to stores/ configuration/ sales/checkout and set "Enable Onepage Checkout" to "No
2. Go to stores/ configuration/ sales/multishipping settings and set "Allow Shipping to Multiple Addresses" to "No".

### Expected result (*)
The "go to checkout" button will appear in the shopping cart and the mini cart

### Actual result (*)
The "go to checkout" button does not appear in the shopping cart or in the minicart

**Comment by mrtuvn** [comment] 2020-02-16 02:22
Can't reproduce your case in latest branch 2.4-develop
@rrebisz do you check this in 2.4-develop
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-16 02:22
Hi @mrtuvn. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-16 02:22
Hi @mrtuvn, here is your [Magento instance](https://i-26889-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26889-2-4-develop.instances.magento-community.engineering/admin_d7ec](https://i-26889-2-4-develop.instances.magento-community.engineering/admin_d7ec)
Login: `4d78e5a7` Password: `7530197ef8b5`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2020-02-17 12:17
Hi @rrebisz. If you disable the One page checkout then proceed to checkout button should not be display on shopping cart and mini cart.
This is expected magento behavior not a bug.
You need to enable the One page checkout to place an order.
Thanks

**Comment by krishprakash** [comment] 2020-02-18 06:04
Hi @rrebisz.
No any reason to get opened as this is expected magento behavior. 
so closing this ticket as non issue.

**Closed as completed by krishprakash** 2020-02-18 06:04 UTC
Labels: non-issue, Issue: Format is valid, Reported on 2.3.4
