### ISSUE TITLE
issue with dynamicRows component

### ISSUE THREAD

**Issue by bohdan-berezhniy** [magento/magento2#31059] opened 2020-11-25 15:49 UTC
### Preconditions (*)

1. Magento 2.4-develop
2. Magento  2.3.4-p2 
3. Sample Data 

### Steps to reproduce (*)

1.Go to Admin -> Catalog -> Product;
2. Chose any product and go to edit form;
3. Go to Related Products, Up-Sells, and Cross-Sells section.
4. Add more than 70 product to Up-Sell or Related products
5. Save the product.
6. Go to the Related Products, Up-Sells, and Cross-Sells section and go to 2,3 and 4 pages

**Actual Result:** :heavy_check_mark:  All 70 products are displayed in the grid

![Peek 2020-11-27 15-53](https://user-images.githubusercontent.com/51679138/100456294-cb758080-30c8-11eb-8c07-765821fdb15b.gif)

6.1 Change per page value to 5, and try to repeat the previous step(6).

### Expected result (*)
:heavy_check_mark:  When per page value was changed to 5, the total pages count should be updated

### Actual result (*)

:heavy_multiplication_x: We have 70 up-sell products and if we change per page value to 5, then 5 products will be shown and the total pages count won't be updated. 
As a result, we will be able to see only 20 products ( 5 products on 4 pages)

![Peek 2020-11-27 15-59](https://user-images.githubusercontent.com/51679138/100456892-b9e0a880-30c9-11eb-885e-ef089e2fd8a9.gif)

---
S2

**Comment by engcom-Alfa** [comment] 2020-11-27 13:37
Hi @bohdan-berezhniy . Thank you for your report.

We are not able to reproduce this issue on 2.4-develop in part of the incorrect loader behavior. Everything works as expected.

**Actual Result:** :heavy_check_mark: 

![Peek 2020-11-27 15-28](https://user-images.githubusercontent.com/51679138/100454273-3cb33480-30c5-11eb-9a4b-f82f0c41e301.gif)

 but there really is a problem with pagination when switching "per page" values

1. Have 67 records in the **Up-Sell Products** 4 pages.
2. Switch per page from **20** to **5**

**Actual Result:** :heavy_multiplication_x:  Only 4 pages with 20 products are displayed

![Peek 2020-11-27 15-36](https://user-images.githubusercontent.com/51679138/100454809-50ab6600-30c6-11eb-8f89-75c1ce35fccb.gif)

So, we will update the description and will confirm it.
Thanks!

**Comment by magento-engcom-team** [comment] 2020-11-27 14:15
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39470` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by SmVladyslav** [comment] 2020-12-29 16:28
@magento I am working on this.

**Closed as completed** 2021-01-05 13:20 UTC
Labels: Component: Catalog, Issue: Confirmed, Component: Backend, Reproduced on 2.4.x, Priority: P2, Severity: S2, Progress: done, Issue: ready for confirmation, Reported on 2.3.4-p2
