### ISSUE TITLE
Reopen / Reinvestigate #5882 [2.1.0][2.1.2][2.1.3][2.1.4] Adding a Configurable Product with options to cart leads to "You need to choose options for your item."

### ISSUE THREAD

**Issue by mitcht** [magento/magento2#8470] opened 2017-02-08 14:44 UTC
@rganin 
Reopen / Reinvestigate #5882
https://github.com/magento/magento2/issues/5882#issuecomment-278324676

I am currently running 2.1.4 and running into this bug still.

To replicate:

Create configurable product
Go to catalog, and click "Add To Cart"
Magento should redirect to the product view page, asking you to make a choice.
Upon making a choice, it will reload the page, showing the item in the cart, as well as a message to make a selection, and a message it has been added to the cart. It will clear the selection as well.
Here is a screenshot of the problem actually occurring as proof:

https://goo.gl/Yf5BBX

This is a little funny... On the onepage checkout success.... It says "You need to choose options".....

After checking out!

https://goo.gl/3oW6GV

EDIT: After this, the message keep appearing on every page I navigate to.

I've cleaned the /var/www/var directory, the pub/static, magento cache:clean, reindexed. Tried EVERYTHING.

**Comment by helicops** [comment] 2017-02-10 22:50
I have exactly the same problem. It's not fixed in version 2.1.4.

**Comment by helicops** [comment] 2017-02-13 14:28
When did some one fixing this problem? Magento 2 is not production ready with this kind of bugs.
When you select in the catalog products view an option (by example the color) is not changing the price or picture. It looks like that the swatch option is not within the submit form, but I am not an developer.

In the product view everything is working OK.

**Comment by KrystynaKabannyk** [comment] 2017-03-24 17:00
hi @mitcht, thank you for reporting the issue, but we couldn't reproduce it. Could you please provide more details?

**Comment by Hawk30100** [comment] 2017-04-30 11:31
Hello @KrystynaKabannyk , could you please try to install Magento 2.1.3, create some configurable products and update to 2.1.4 or a later version. I did not had any problems when installing a fresh Magento version.

**Comment by veloraven** [comment] 2017-06-15 13:38
Internal ticket for ver. 2.1 - MAGETWO-58503

**Comment by magento-engcom-team** [comment] 2017-10-05 09:30
@mitcht, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-05 09:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Clear Description, Issue: Format is not valid
