### ISSUE TITLE
At checkout page getting warning message "The requested qty is not available"  for configurable product which child product has one stock left.

### ISSUE THREAD

**Issue by cstp55** [magento/magento2#38902] opened 2024-07-04 03:46 UTC
### Preconditions and environment

- Magento version  2.4.6
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

1. Create a configurable product 
2. set child product one stock only 
3. add to cart that child product 
4. place order 
Now you getting this error

### Expected result

Order is placed successfully 

### Actual result

the requested qty is not available.

### Additional information

I have found two solution in core magento module 
1. create plugin or preference 
vendor/magento/module-quote/Model/Quote/Item/Processor.php:94
need to add $requestData = ['id' => $cartItem->getItemId()];
Method name converToBuyRequest();

2. calculating stock
vendor/magento/module-inventory-sales/model/IsproductSalableforRequestedQtyCondition/IsSalableWithReservationsCondition.php:95 
logic is not correct. we can replace this logic with result

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by cstp55** [comment] 2024-07-04 03:48
Let me know if issue is not reproduce. I have also multiple solutions for this.

**Comment by engcom-Bravo** [comment] 2024-07-04 04:22
@magento give me 2.4-develop instance

**Comment by cstp55** [comment] 2024-07-04 05:59
Thanks for the instance. I have checked,  issue not reproduce at provided instance.
Will check again at our end.  may be issue due to the anythird party module. 
will check and update here

**Comment by cstp55** [comment] 2024-07-04 06:00
Also for Now, can i close this issue

**Comment by engcom-Bravo** [comment] 2024-07-04 06:03
Hi @cstp55,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

**Steps to reproduce**

- Create a configurable product
- set child product one stock only
- add to cart that child product
- place order



https://github.com/magento/magento2/assets/51680745/d7b529f7-853d-483a-8d8f-25703e8a9eb0


Order Placed successfully.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-04 06:03 UTC
Labels: Issue: ready for confirmation, Reported on 2.4.6

**Comment by pikulsky** [comment] 2025-03-25 15:41
@cstp55 , hi :) did you find the reason why it failed in your case (and worked in the provided here instance) ?  I got the same issue as well (2.4.7). You suggested the fix, it works, but why the error happens?

**Comment by pikulsky** [comment] 2025-03-25 17:30
@cstp55 , ok! thank you!
