### ISSUE TITLE
Checkout - Shipping Address - Firstname field is missing

### ISSUE THREAD

**Issue by wandyyd** [magento/magento2#33133] opened 2021-06-03 05:31 UTC
### Preconditions (*)

1. Magento 2.4.2-p1 upgrade from Magento 2.4.2
2. PHP 7.4.16

### Steps to reproduce (*)

1. Setup theme, to use Magento Luma
2. Follow order/purchase process until checkout

### Expected result (*)

1. Expecting Firstname field to be there

### Actual result (*)

1. Firstname field is missing, hence it stops order process
![image](https://user-images.githubusercontent.com/30722472/120592069-6af44100-c467-11eb-8120-dd81d47cd6ca.png)
![image](https://user-images.githubusercontent.com/30722472/120592131-89f2d300-c467-11eb-9d34-1ec2420d17d4.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by wandyyd** [comment] 2021-06-03 05:32
@magento give me 2.4.2-p1 instance

**Comment by wandyyd** [comment] 2021-06-03 05:47
I check against that instance, and it seems fine
![image](https://user-images.githubusercontent.com/30722472/120593453-bc9dcb00-c469-11eb-9170-7c7c91aba41d.png)

Is there any possibility on where the issue comes from?
I did try to disable some modules (currently have some modules running), but none affecting my issue

**Comment by engcom-Alfa** [comment] 2021-06-08 06:17
Hi @wandyyd 
I tried to reproduce this issue, but can't reproduce it on Magento 2.4.2-p1. It is working as expected. So considering this, I am closing this Issue.
![image](https://user-images.githubusercontent.com/51679138/121132547-e7639700-c84e-11eb-9af1-95cdc1fb554e.png)

**Closed as completed** 2021-06-08 06:17 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: ready for confirmation

**Comment by wandyyd** [comment] 2021-06-14 03:56
Hi @engcom-Alfa - thanks for looking on this. Seems an extension outside Magento default interfering this. I might need to look on it.
