### ISSUE TITLE
Magento 2.1 "This is a required field." error message appears below selection area of configurable product without marking the required field with the false input

### ISSUE THREAD

**Issue by ps202** [magento/magento2#6370] opened 2016-08-28 12:55 UTC
### Preconditions

Operating System: Ubuntu 15.10

PHP 5.6.11-1ubuntu3.4 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

mysql Ver 14.14 Distrib 5.6.31, for debian-linux-gnu (x86_64) using EditLine wrapper

Magento 2.1.0 CE
### Steps to reproduce
1. Install Magento & set Blank or Luma Theme to be used
2. Create one configurable product with images and sizes
3. Create configurations (simple products) for that configurable product (color - visual swatch, size - text swatch)
4. Browse to the configurable product and try to put a product into the cart without selecting size or color
### Expected result
1. Error message should appear under the color swatch field and under the size swatch field of selection area.
### Actual result
1. Error messages appear under the whole selection area, not providing any visual aid what should be selected.
   Luma:
   ![luma_theme](https://cloud.githubusercontent.com/assets/9308353/18033880/c7555974-6d2e-11e6-8aa4-fdb38ffb7c63.png)

Blank:
![blank_theme](https://cloud.githubusercontent.com/assets/9308353/18033887/eed2cfc2-6d2e-11e6-8b53-d37bebd6be0b.png)

**Comment by pboisvert** [comment] 2016-08-29 05:06
duplicate of #5428 closing

**Closed as completed by pboisvert** 2016-08-29 05:06 UTC
