### ISSUE TITLE
Store switcher not aligned proper in tab view

### ISSUE THREAD

**Issue by cedarvinda** [magento/magento2#20158] opened 2019-01-10 07:36 UTC
Store switcher not aligned proper in tab view

### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.2

### Steps to reproduce (*)

Step 1: Go to frontend
Step 2: view in responsive view (device with 991px)
Step 3: Now you will get issue (will appear horizontal scroll)

### Expected result (*)

![sol](https://user-images.githubusercontent.com/26018716/50952940-ebe9c100-14d7-11e9-8b4a-25ae22f24dc3.png)

### Actual result (*)

![issue](https://user-images.githubusercontent.com/26018716/50952972-fdcb6400-14d7-11e9-8c3b-4a6db570bc96.png)

**Comment by magento-engcom-team** [comment] 2019-01-10 07:36
Hi @cedarvinda. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@cedarvinda do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-10 07:36
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment] 2019-01-10 07:36
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-01-10 07:41
@shikhamis11 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97542`, `MAGETWO-97543` were created

**Comment by magento-engcom-team** [comment] 2019-01-16 00:00
Hi @cedarvinda. Thank you for your report. 
The issue has been fixed in magento/magento2#20160 by @cedarvinda in 2.3-develop branch
Related commit(s):
 - [c060b57a5e65c2dedf3a935db1d82f0cd63926f0](https://github.com/magento/magento2/commit/c060b57a5e65c2dedf3a935db1d82f0cd63926f0)
 - [1e7bae1eda1148fab178e9ae43366f6ae35d876f](https://github.com/magento/magento2/commit/1e7bae1eda1148fab178e9ae43366f6ae35d876f)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2019-01-16 00:00 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Progress: PR Created, Component: Store, Area: Design/Frontend

**Comment by magento-engcom-team** [comment] 2019-01-18 22:40
Hi @cedarvinda. Thank you for your report. 
The issue has been fixed in magento/magento2#20325 by @shikhamis11 in 2.2-develop branch
Related commit(s):
 - [f9a03d854be62438601eb214107a119807504a18](https://github.com/magento/magento2/commit/f9a03d854be62438601eb214107a119807504a18)
 - [82ad1cad7f76dcc72dee6d43caf95843096bb3e1](https://github.com/magento/magento2/commit/82ad1cad7f76dcc72dee6d43caf95843096bb3e1)

The fix will be available with the upcoming 2.2.8 release.
