### ISSUE TITLE
Url rewrites are not generated when products are assigned to new website via mass action.

### ISSUE THREAD

**Issue by victortodoran** [magento/magento2#32549] opened 2021-03-18 17:04 UTC
### Preconditions (*)

1. Latest Magento install.

### Steps to reproduce (*)

1. Configure a multi-website environment. 
2. Move product to website using mass action.

### Expected result (*)

1. Url rewrites are generated as expected/configured
### Actual result (*)

1. Url rewrites are not generated for the newly moved product.
2. NOTE: Url rewrites are generated as expected when product is moved to new website from product edit.

### Additional Information
- Normally the generation of Url Rewrites for products in case of website assignment is generated in this Observer `\Magento\CatalogUrlRewrite\Observer\ProductToWebsiteChangeObserver::execute`
- `\Magento\Catalog\Model\Product\Action::updateWebsites` is called and `catalog_product_to_website_change` is dispatched
- Product Mass Updates are handled via queue/consumer pattern. 
- Consumers are executed from cron area 
- ProductToWebsiteChangeObserver is declared only in adminhtml config, `see vendor/magento/module-catalog-url-rewrite/etc/adminhtml/events.xml` thus the ProductToWebsiteChangeObserver does not execute.
- NOTE: This might happen for other scenarios as well, i.e. update product-website relation via REST due to the same reason.
- **SOLUTION:** Move declaration of ProductToWebsiteChangeObserver at global level config. i.e `module-catalog-url-rewrite/etc/events.xml `

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment] 2021-03-19 02:24
Seem issue like your describe already work done in latest code base 2.4-develop
But not sync to 2.4.2

**Comment by victortodoran** [comment] 2021-03-19 06:43
Will this reach 2.4.3?

**Comment by hostep** [comment] 2021-03-19 07:12
The line @mrtuvn links to is probably irrelevant in scope of this issue, since that line has existed for over 5 years in the code base. So that's most likely an incorrect assumption he's making.

**Comment by victortodoran** [comment] 2021-03-19 07:23
@hostep Thanks so much for pitching in, I've taken it at face value.

**Comment by engcom-Oscar** [comment] 2021-03-19 10:34
Hi @victortodoran!
Thank you for your report.
I were not able to reproduce the issue on a fresh 2.4-develop by following steps from this ticket. Url rewrites were generated when products are assigned to new website via mass action, but I found one thing - in the "Url Rewrites' grid "Store View' information were not updated correctly.
![Screenshot from 2021-03-19 12-30-31](https://user-images.githubusercontent.com/60198413/111767338-47314e00-88af-11eb-82cb-18b254e3165f.png)

![Screenshot from 2021-03-19 12-31-12](https://user-images.githubusercontent.com/60198413/111767359-4dbfc580-88af-11eb-8881-9e6450a8f849.png)
May you please recheck it?

**Comment by victortodoran** [comment] 2021-03-22 19:00
If there are no URL rewrites in the newly created website/store the issue reproduces.
This can be easily checked by searching the product for example or browsing the category. 
Is the url key used or the long form catalog/product/view/id/ etc

**Comment by victortodoran** [comment] 2021-03-22 19:01
@magento give me 2.4-develop instance

**Comment by victortodoran** [comment] 2021-03-22 19:30
I could not reproduce this on the 2.4-develop branch. I'm closing this issue, thanks.

**Closed as completed** 2021-03-22 19:30 UTC
Labels: Issue: needs update
