### ISSUE TITLE
Functional api test unable to load install-config-mysql database credentials

### ISSUE THREAD

**Issue by baatractive** [magento/magento2#33696] opened 2021-08-05 14:25 UTC
### Preconditions (*)

1. Magento CLI 2.3.5
2. WSL (Windows Sub-System For Linux)

### Steps to reproduce (*)

1. Follow the steps as per the documentation: https://devdocs.magento.com/guides/v2.4/get-started/web-api-functional-testing.html#howto and then try running the command: `../../../vendor/bin/phpunit --config phpunit_rest.xml` 

### Expected result (*)

1. It should load the expected `install-config-mysql.php` file for database connection but it rather tries to connect with the default connection settings. For some reason the default connection is also throwing an error with this command. However, I could successfully run integration tests and also my default is fully functional when try to upgrade or clear any cache.

![image](https://user-images.githubusercontent.com/88047235/128366769-e353ebe2-e8a8-499d-ac9b-2de06fabf2c4.png)

### Actual result (*)

![image](https://user-images.githubusercontent.com/88047235/128366184-439aee73-0523-4fdb-ba02-1accf8e29689.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by baatractive** [comment] 2021-08-05 14:27
@magento give me 2.4-develop instance

**Comment by baatractive** [comment] 2021-08-06 07:34
The API functional test uses `app/etc/env.php` but rather `dev/tests/functional-api/config/install-mysql-config.php`. I just changed the default credentials and the tests started working.

**Comment by gwharton** [comment] 2021-08-06 18:01
https://github.com/magento/magento2/issues/27213

**Comment by baatractive** [comment] 2021-08-06 20:25
@gwharton Yes that seems a similar issue and why is it closed? Was it resolved?

**Comment by gwharton** [comment] 2021-08-07 08:02
Lack of interest from Magento team.

**Comment by gwharton** [comment] 2021-08-07 09:11
I'll take a look at this later today as I almost had a fix working when I last looked at this.

**Comment by baatractive** [comment] 2021-08-07 12:49
@gwharton That would great help, thanks.

**Comment by mrtuvn** [comment] 2021-08-08 00:34
as i remembered you need create seperate db for test `magento_integration_tests`

**Comment by mrtuvn** [comment] 2021-08-08 00:53
elasticsearch seem required too
https://github.com/magento/magento2/pull/30995 < = check this

**Comment by gwharton** [comment] 2021-08-08 08:10
OK, ive had a look at the API Functional test code and how it works and it exposes a fundamental issue with the way the API Functional tests work.

Lets consider the integration tests first. When they are run, they use the install-mysql-config.php and the test framework installs a bastardised runtime of magento into dev/tests/integration/tmp/sandbox---------- and creates a separate database as defined in install-mysql-config.php. The tests are all run in the context of this sandbox test environment so as to not affect any data in the main development database. This works fine and is well understood.

Now, the API Functional tests. Well, these seem to follow the same approach, as there is a install-mysql-config.php file detailing a separate database however the bootstrap functions in the api functional tests operate differently to the integration tests. The test framework seems to have been implemented by a mixture of people who don't understand the difference between api functional and integration tests, and people that have hacked it to appear to work. Let me explain.

So, the difference between the two test types : whereas the integration tests run in their own sandbox, you cannot do this for the api functional tests so easily. The API Functional tests are essentially very simple REST/SOAP/GRAPHQL clients which makes a call to a Magento HTTP(s) endpoint. Had the test framework been configured to work in the same way as the integration tests with its own sandbox using details in install-mysql-config.php, then it would be ONLY the REST/SOAP/GRAPHQL clients that run in this sandbox. You would have a sandboxed database in existence for the test client, which then makes a call to a HTTP(s) endpoint somewhere else. but where??? There is only one HTTP(s) based Magento endpoint and that is the one configured in app/etc/env.php. We do not have a separate webserver setup that could server the sandboxed version of the api-functional test installation.

I believe at this point the Magento team may well have just thrown their hands in the air and decided that the API functional tests should not run in a sandbox environment, and adjusted the test framework bootstrap code to operate on the main database. They did leave in a couple of nasty features though

- if the <const name="TESTS_CLEANUP" value="disabled"/> is enabled in phpunit.xml then the system attempts to uninstall the system defined in app/etc/env.php
- if the <const name="TESTS_MAGENTO_INSTALLATION" value="enabled"/> is enabled in phpunit.xml then the system reinstalls into the main database defined in app/etc/env.php

So, what do we do. The current API functional tests intentionally ignore the install-mysql-config.php data and use the app/etc/env.php details instead. The tests operate on the HTTP(s) endpoint configured in app/etc/env.php with the result being the tests are performed on the main development database and not a sandboxed version. People assume it uses a sandbox database but it doesn't. Their development database will be being polluted with data from the API Functional tests, if not cleaned up properly by the test.

It is fairly straight forward to adjust the test framework to use the install-mysql-config.php settings and generate a sandbox for the REST/SOAP/GRAPHQL client to run in, but we would also need to either adjust the main app/etc/env.php to temporarily use the sandbox details from install-mysql-config.php for the duration of the test, or create a separate web server config that points at the sandbox installation.

**Comment by baatractive** [comment] 2021-08-08 11:12
@gwharton I see, I investigated this issue too but thought I might be wrong because they already provide `install-mysql-config.php` which should clearly work the same as for integration tests but I was right as their configuration was not correct. It truncated my `env` database and then I re-uploaded the dump.

**Comment by baatractive** [comment] 2021-08-08 11:15
@mrtuvn There's already a database for the integration which is working properly but the current issue is with the **Functional Api** tests.

**Comment by gwharton** [comment] 2021-08-08 16:59
A little bit more research that confirms the fundamental broken'ness of the API Functional tests.

If the following settings are set in phpunit.xml

```
<const name="TESTS_CLEANUP" value="disabled"/>
<const name="TESTS_MAGENTO_INSTALLATION" value="disabled"/>
```
Then running the API-Functional tests will run them against the Magento HTTP(s) endpoint as defined in the setting `<const name="TESTS_BASE_URL" value="http://localhost:8080/"/>`. It will not attempt to uninstall or reinstall the database.

if either of the TESTS_CLEANUP (ununstalls magento) or TESTS_MAGENTO_INSTALLATION (installs magento) are set to enabled, then because of this bug, then the database defined in app/etc/env.php is cleared and then the database defined in install-config-mysql.php is installed. This is probably not what you want and will most likely mess up your development node database.

So, two ways to run API Functional tests......

### Run the API Functional Tests against your development database.
- Leave your app/etc/env.php alone.
- No need to set anything in install-config-mysql.php. It is not used in this configuration.
- Set TESTS_CLEANUP to **disabled** in phpunit.xml
- Set TESTS_MAGENTO_INSTALLATION to **disabled** in phpunit.xml
- Set TESTS_BASE_URL, TESTS_WEBSERVICE_USER, TESTS_WEBSERVICE_APIKEY in phpunit.xml to match the credentials on your development node. TESTS_BASE_URL is the web address of your dev node installation.
- Run the API-Functional test.
- Be aware it may pollute your dev database with test data.

### Run the API Functional Tests against a sandbox database.
- Prior to running the test. Update your app/etc/env.php to point to your sandbox database.
- Set TESTS_CLEANUP to **enabled** in phpunit.xml
- Set TESTS_MAGENTO_INSTALLATION to **enabled** in phpunit.xml
- Set TESTS_BASE_URL, TESTS_WEBSERVICE_USER, TESTS_WEBSERVICE_APIKEY in phpunit.xml to match the credentials as set in install-config-mysql.php. TESTS_BASE_URL is the web address of your dev node installation.
- Run the API-Functional test.
- It will uninstall the database defined in app/etc/env.php (Which should point to your sandbox right!).
- It will reinstall the database defined in install-config-mysql.php (the items in this file are directly transposed into command line arguments in the setup:install command so adjust to suit).
- Because you updated app/etc/env.php the Magento HTTP(s) endpoint that is used in your test in the tests will act on your sandbox database.
- At the end of the test, revert the app/etc/env.php back to your original developer settings.

**Comment by gwharton** [comment] 2021-08-08 17:07
Hi, @ihor-sviziev I wondered if you were aware of the issues with the API-Functional test framework as detailed in my post above. Can you copy anyone in, in the test team that may need to be aware of this. Its been in this broken/working only by chance state for a while now, and I am sure because of the bug, regularly wipes peoples development databases when they first try to run the intergration tests, and pollutes their development database with test data as the test framework uses the wrong database.

I raised https://github.com/magento/magento2/issues/27213 on it a while ago but got no traction.

**Comment by baatractive** [comment] 2021-08-08 18:01
@gwharton I see, thanks for the explanation. However, I did updated `etc/env.php` to use a sandbox version but I don't really like this approach either. I would rather find an alternate solution to override the default database keys with the `sandbox` one. I hope to get it done somehow without going back & forth. Thanks :)

**Comment by gwharton** [comment] 2021-08-08 18:03
you could have two env.php files and use a symbolic link to switch between them. It could be triggered automatically by a test runner script. Lets see if Magento core comes back with any comments. I agree its not ideal.

**Comment by engcom-Lima** [comment] 2021-09-20 12:34
Hi @baatractive,

Thank you for reporting the issue.

I have gone through the issue description and related comments with @gwharton. I tried to replicate this issue on 2.4-develop instance with the provided steps but I was not able to reproduce it.

So for further analysis, can you please update on the below queries:

1. If this issue is happening with WSL specifically ? 
2. Can you guys please check if this issue is reproducible on Magento 2.4-develop or is it specific to Magento 2.3.5 ?

It would be helpful if you guys can provide some more info so that I can try again to reproduce this.

**Comment by engcom-Lima** [comment] 2021-10-05 10:04
Hi @baatractive,

We have noticed that this issue has not been updated for some time. Since we were not able to reproduce this so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this with answer to queries asked in https://github.com/magento/magento2/issues/33696#issuecomment-922887309

Regards

**Closed as completed by engcom-Lima** 2021-10-05 10:04 UTC
Labels: Triage: Dev.Experience, Issue: needs update
