### ISSUE TITLE
Newsletter Template Error - is not a valid hostname for email address

### ISSUE THREAD

**Issue by raymond62** [magento/magento2#13320] opened 2018-01-22 17:43 UTC
Version is Magento 2.2.2

Try to create/update a Newsletter Template "Sender Email" is not validating correctly.
I get following Error.

'mydomain.shop' is not a valid hostname for email address 'support@mydomain.shop'
'mydomain.shop' appears to be a DNS hostname but cannot match TLD against known list
'mydomain.shop' appears to be a local network name but local network names are not allowed

mydomain.eu e.g. is doing fine.

**Comment by magento-engcom-team** [comment] 2018-01-24 09:54
@raymond62, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by Laura021** [comment] 2018-03-02 18:28
#MagetitansMX

**Comment by magento-engcom-team** [comment] 2018-03-02 18:29
@Laura021 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by santhoshp** [comment] 2018-05-19 09:41
I am working on this at #dmcdindia

**Comment by santhoshp** [comment] 2018-05-19 10:47
Open vendor/magento/zendframework1/library/Zend/Validate/Hostname.php and add 'shop' TLD  inside $_validTlds

**Comment by magento-engcom-team** [comment] 2018-05-26 12:45
@santhoshp Unfortunately this is not recommended to edit dependencies directly.
Instead you submit set up a Pull Request to `magento/zendframework1`.

**Comment by magento-engcom-team** [comment] 2018-10-27 00:30
Hi @jasonevans1. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by jasonevans1** [comment] 2018-10-27 00:46
I have created a pull request to `magento/zendframework1` to update the valid TLD list. https://github.com/magento/zf1/pull/20

**Comment by kamilmaliszewski** [comment] 2018-11-26 16:34
Also domain with ".fun" is missing

**Comment by engcom-Bravo** [comment] 2024-04-30 07:24
Hi @raymond62,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.

<img width="1348" alt="Screenshot 2024-04-30 at 12 52 04" src="https://github.com/magento/magento2/assets/51680745/61bf9714-c20a-40c9-8696-1d7b3dae70d6">



We are able to create newsletter template.

Hence we are closing the issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-04-30 07:24 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is not valid, Component: Newsletter, Priority: P3, Progress: done
