### ISSUE TITLE
Product Alert Adding custom CMS blocks to mail template

### ISSUE THREAD

**Issue by leonhelmus** [magento/magento2#36136] opened 2022-09-13 13:01 UTC
### Preconditions and environment

- Magento 2.4.4-p1
- php 8.1

### Steps to reproduce

1. Go to backend
2. Create a cms block (Content > Blocks) > Add new Block > Edit with pagebuilder 
3. Add element named a HTML code
```
<table class="header-tabs" align="center">
                <tbody>
                    <tr>
                        <td class="header-tab webshop">
                            <a href="{{config path="web/secure/base_url"}}"><b>test1</b></a>
                        </td>
                        <td class="header-tab service">
                            <a href="{{config path="web/secure/base_url"}}test2"><b>test2</b></a>
                        </td>
                        <td class="header-tab faq">
                            <a href="{{config path="web/secure/base_url"}}test3"><b>test3</b></a>
                        </td>
                    </tr>
                </tbody>
            </table>
```
4. add identifier "custom"
5. Enable back in stock
6. Go to marketing > Email templates
7. Add new template > load template "Stock Alert"
8. Add this in the content {{block class="Magento\\Cms\\Block\\BlockByIdentifier" area='frontend' identifier="custom"}}
9. Enable stock alert
10. Create customer account
11. subscribe to stock alert for out of stock product.
12. Make the product back in stock

### Expected result

The block "custom" gets rendered as html.

### Actual result

The block "custom" gets rendered as text and you see the whole html tags rendered as text.

### Additional information

Product alert now uses queues in magento 2.4.4 while before it used crons.

Because it now uses queues it does not have an area, since queue's in most cases use AREA global, because it uses the area global it does not get to use the plugin \Magento\PageBuilder\Plugin\Filter\TemplatePlugin of pagebuilder. This plugin is responsible of making encoded html and decodes it. By adding this patch the problem is resolved.

```

diff --git a/vendor/magento/module-page-builder/etc/di.xml b/vendor/magento/module-page-builder/etc/di.xml
--- a/vendor/magento/module-page-builder/etc/di.xml	
+++ b/vendor/magento/module-page-builder/etc/di.xml	(date 1663074045963)
@@ -450,4 +450,7 @@
             </argument>
         </arguments>
     </virtualType>
+    <type name="Magento\Framework\Filter\Template">
+        <plugin name="convertBackgroundImages" type="Magento\PageBuilder\Plugin\Filter\TemplatePlugin"/>
+    </type>
 </config>

```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2022-09-20 10:53
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-09-20 12:07
Hi @leonhelmus ,

We are trying to reproduce the issue in 2.4-develop branch and 2.4.4 also we are not able to reproduce the issue.
we are getting The block "custom" gets rendered as html.

For your reference i attached the screenshots:
![Screenshot from 2022-09-20 17-33-12](https://user-images.githubusercontent.com/60198592/191252915-60f6d549-eb41-4bf9-8544-42ac87e3e6ad.png)
![Screenshot from 2022-09-20 17-24-25](https://user-images.githubusercontent.com/60198592/191252948-c1c49f4e-aa6b-405b-addd-2a13bf20965d.png)
![Screenshot from 2022-09-20 17-23-19](https://user-images.githubusercontent.com/60198592/191252958-646862e1-0cb9-47a2-ac1c-189aa71c9651.png)
![Screenshot from 2022-09-20 17-22-23](https://user-images.githubusercontent.com/60198592/191252973-71c09da0-3f26-40da-843a-36a04fba5a41.png)

Steps to reproduce:

Go to back-end
Create a cms block (Content > Blocks) > Add new Block > Edit with page builder
Add element named a HTML coded identifier "custom"
Enable back in stock
Go to marketing > Email templates
Add new template > load template "Stock Alert"
Add this in the content which is provided
Enable stock alert
Create customer account
subscribe to stock alert for out of stock product.


Let us know if we are Missing anything!!!

Thnaks!!!!

**Comment by leonhelmus** [comment] 2022-09-20 16:34
@engcom-Dash could it be that the feature environment for the product elart queue has an area, because our queue uses global and that's why that patch is needed.

**Comment by leonhelmus** [comment] 2022-09-20 16:36
We added the static block in this way {{block or are you using a widget?

**Comment by engcom-Dash** [comment] 2022-10-19 12:19
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-10-19 13:25
Hi @leonhelmus ,

As per description we are added block...and we are getting the result is "The block "custom" gets rendered as html".


Let us know if we missing anything!!!

Thanks!!!

**Comment by engcom-Dash** [comment] 2022-11-02 04:44
Hi @leonhelmus ,

Thanks for your Contribution!

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks !!!

**Closed as completed by engcom-Dash** 2022-11-02 04:44 UTC
Labels: Issue: needs update, Reported on 2.4.4-p1
