### ISSUE TITLE
Issue to change luma theme logo.

### ISSUE THREAD

**Issue by Anuragm98** [magento/magento2#20097] opened 2019-01-06 18:20 UTC
Logo is not uploading of luma theme from magento admin panel.

**Comment by magento-engcom-team** [comment] 2019-01-06 18:20
Hi @Anuragm98. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Anuragm98 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by davidverholen** [comment] 2019-01-06 18:39
@Anuragm98 please provide information about the magento version used and detailed steps to reproduce the issue.
The issue is probably already fixed (https://github.com/magento/magento2/pull/18851)

**Comment by Anuragm98** [comment] 2019-01-07 04:49
I have magento 2.3.0 and i can not change logo from admin. Content-> Design-> Configuration->Select luma theme-> Header

**Comment by davidverholen** [comment] 2019-01-07 09:21
@Anuragm98 thx for the update. I'm closing this issue as this is already fixed in the 2.3-develop branch in this pr https://github.com/magento/magento2/pull/18851 and will be in 2.3.1

**Closed as completed by davidverholen** 2019-01-07 09:21 UTC
Labels: Progress: needs update, Issue: Format is valid
