### ISSUE TITLE
Issue with quick cart view

### ISSUE THREAD

**Issue by tiffanylw** [magento/magento2#29011] opened 2020-07-06 15:07 UTC
Hi, I have been having an issue with items with attirbutes that appear on the Quick cart option on the actual home page.
We imported many menu combo items onto the magento inventory list and all of the items appear to be working fine with their attrivutes and selection besides one combo.
![image](https://user-images.githubusercontent.com/67914666/86608306-f1f71b80-bf6f-11ea-8860-114913700c1b.png)
Then you hover over the item, and click on the little cart button, a quick cart add menu comes up, however, there the item requires to select the attributes assigned to it and the attributes wont load 
![image](https://user-images.githubusercontent.com/67914666/86608504-426e7900-bf70-11ea-8572-58b27d7d0632.png)

How should i go about this?  I have checked the settings in the inventory on magento and they match the settings of the combos that do work.  

### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by krishprakash** [comment] 2020-09-29 10:11
Hi @tiffanylw.
Thank you for your report!
Seems like this is the issue in the custom extension that you're using. Please contact vendor that develop it instead.
I'm closing this issue as it was caused by custom extension.

**Closed as completed by krishprakash** 2020-09-29 10:11 UTC
Labels: Issue: Format is valid, Progress: done
