### ISSUE TITLE
Password Strength Calculation issue - Magento 2.2.4

### ISSUE THREAD

**Issue by Sathishkumar8731** [magento/magento2#16752] opened 2018-07-12 15:19 UTC
### Preconditions
1.  Magento 2.2.4
2.  PHP 7.1.X

### Steps to reproduce

1. Open the site 
2. choose signup 
3. In Signup provide a password twice of same combination 
Example: Welcome@123Welcome@123
4. The password changes from "Very Strong" to "Strong". 

### Expected result
1. Combination of text should be Very Strong password only, It should not change it.

### Actual result

The password changes from "Very Strong" to "Strong".

**Comment by magento-engcom-team** [comment] 2018-07-12 15:20
Hi @Sathishkumar8731. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Sathishkumar8731 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment] 2018-07-13 07:49
Hello @Sathishkumar8731, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by orlangur** [comment] 2018-07-13 08:35
@engcom-backlog-nickolas I don't think there is something to fix here from Magento side - we use third-party strength checker library without any customizations.

@Sathishkumar8731 your expectation is wrong, please check https://stormpath.com/blog/5-myths-password-security#3-myth-password-checkers-ensure-strong-passwords. Also, from https://stackoverflow.com/questions/1327742/why-are-passwords-with-repeating-substrings-weak it looks described situation is common.

**Comment by engcom-backlog-nickolas** [comment] 2018-07-13 08:49
@orlangur, thanks for explanation.
@Sathishkumar8731, I'm closing this issue, due to previous comment.  If you'd like to update it, please reopen the issue.

**Closed as completed by engcom-backlog-nickolas** 2018-07-13 08:49 UTC
Labels: Issue: Ready for Work, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, non-issue, Issue: Format is valid
