### ISSUE TITLE
Checkout error "Current customer does not have an active cart." and dont go to checkout success page

### ISSUE THREAD

**Issue by daniloab** [magento/magento2#33188] opened 2021-06-08 18:39 UTC
### Preconditions (*)
1. Magento 2.4.2

### Steps to reproduce (*)
Hi, I'm implementing a new payment method into Magento2.

I'm implementing using the AbstracMethod being extended into my PaymentModel.

As expect, I have a function called `order`. This function does the following:

- retrieve order information
- prepare a `Payload` object to be passed to our API
- creates an order on our side
- return this info
- save and go to the checkout success

The problem is on the last item: when the `order` function ends, it is expected that the customer is redirected to checkout success.

But, it is returning an error:

![https://user-images.githubusercontent.com/19939822/121237045-02dd9a80-c86d-11eb-9d5d-a5fa2ef1ec1c.png](https://user-images.githubusercontent.com/19939822/121237045-02dd9a80-c86d-11eb-9d5d-a5fa2ef1ec1c.png)

My PaymentModel Class: https://gist.github.com/daniloab/a7fe06297fac8ec135c084676c502332

### Expected result (*)

1. Expected that after the order is completed should redirect the user to the checkout success

### Actual result (*)

1. ![https://user-images.githubusercontent.com/19939822/121237045-02dd9a80-c86d-11eb-9d5d-a5fa2ef1ec1c.png](https://user-images.githubusercontent.com/19939822/121237045-02dd9a80-c86d-11eb-9d5d-a5fa2ef1ec1c.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment] 2021-06-09 10:17
Hi @daniloab ,

Request you to kindly provide screenshots/snapshots of your implementation for custom payment method.
Also , I would suggest to change your implementation as Magento\Payment\Model\Method\AbstractMethod has been deprecated, try to follow the new guidelines for custom payment method creation here at [https://devdocs.magento.com/guides/v2.4/howdoi/checkout/checkout_payment.html](url) .

Thanks

**Comment by daniloab** [comment] 2021-06-09 11:56
My problem at really it was on the checkout success page. When trying to get there something broke and try to return to checkout

as the order have been already done, does not exist a customer cart active anymore

so, when checkout success break how is the best way to debug there?

more specific into `phtml` files. I cant found anything in the log files.

**Comment by engcom-Echo** [comment] 2021-06-18 08:25
Hi @daniloab ,

It will be very difficult to debug without understanding the full implementation ,as per your comments it looks like the user is getting redirected to cart page after successful payment where in he should be redirected to checkout success page , this looks like a some problem with checkout session I think it might be getting empty thats why core code is redirecting to cart page instead.
I would suggest you to debug on the checkout session. 

Also I would suggest to implement the payment method as per the docs 
https://devdocs.magento.com/guides/v2.4/howdoi/checkout/checkout_payment.html 

Also it looks like more of an implementation rather than a bug.  Please comment back if you get anything .

Thanks

**Comment by daniloab** [comment] 2021-06-18 13:17
I guess we can close this one. The problem it was with the code from checkout success.

**Comment by engcom-Hotel** [comment] 2021-06-29 08:17
Hi @daniloab ,

As per your last comment, we are closing this issue. Still if you are facing any issue, you can create new tickets.

**Closed as completed by engcom-Hotel** 2021-06-29 08:17 UTC
Labels: Component: Checkout, Triage: Dev.Experience, Issue: needs update, Reported on 2.4.2

**Comment by r-martins** [comment] 2022-08-24 05:17
In my case this was caused by a module's event.xml file containing 
```xml
<event name="customer_login">
    <observer name="loadCustomerQuote" disabled="true"/>
</event>
```

**Comment by Collapse011** [comment] 2022-10-24 12:32
Bom dia Ricardo como vai ? @r-martins 

pelo admin conseguimos resolver esse problema ?

**Comment by r-martins** [comment] 2022-10-27 00:43
@Collapse011 não sei. Meu caso foi bem específico de um módulo/erro meu mesmo. Não teria como fazer nada pelo admin.
