### ISSUE TITLE
Issue with "Insert Image" or "Insert Link" in WYSIWYG editor on catalog product pages

### ISSUE THREAD

**Issue by C4rter** [magento/magento2#11395] opened 2017-10-12 08:03 UTC
### Preconditions

Magento Version 2.2.0

### Steps to reproduce

1. Login to backend
2. Go to catalog product grid
3. Click on any product
4. Go to "Content" area
5. If already open, close WYSIWYG editor for every field (usually "Description" and "Short Description").
6. Re-Open WYSIWYG editor for the upper field (usually "Description")
7. Click on Insert Link, choose any image and click "Insert Image"
8. Issue: Now, the image tag is appearing in the text area that belongs to the disabled WYSIWYG editor ("Short Description") instead of the area it's supposed to appear in ("Description")

### Expected result

1. The image tag should appear in the area that belongs to the WYSIWYG editor I used.

### Actual result

![issue-1](https://user-images.githubusercontent.com/738782/31485465-39723bc4-af34-11e7-938f-3ac90ffa78a6.png)

**Comment by magento-engcom-team** [comment] 2017-10-12 14:33
@C4rter Thanks for reporting this issue. Closing as a duplicate of [#7368](https://github.com/magento/magento2/issues/7368) .

**Closed as completed by magento-engcom-team** 2017-10-12 14:33 UTC
Labels: Issue: Format is valid
