### ISSUE TITLE
Multishipping checkout, shipping amount is not applied correctly when different on different addresses/items

### ISSUE THREAD

**Issue by TaniRay123** [magento/magento2#23631] opened 2019-07-09 08:29 UTC
### Preconditions (*)

1. Magento 2.2.6

### Steps to reproduce (*)
1. I have at least 2 shipping methods enabled - Free and Fixed

2. Login as a customer who has at least 2 addresses and add 2 Items to cart and go to view Edit Cart

3. Click Check out with Multiple Address

4. Select a different address for the second item and click Update Qty and Addresses

5. Go to Shipping Information

6. Select Fixed of $5.00 for first order and leave at free for second order

7. Continue to Billing Information, Select any Payment method and click  Go to Review Order

### Expected result (*)

1. Shipping and Handling for first order should be $5.00 
2. Shipping and Handling for first order should be $0.00
3. Totals should be displayed correctly

### Actual result (*)

Shipping and Handling for first order is shown incorrectly as zero – although “Total for this Address is correct” also where is the comment block?????

![image](https://user-images.githubusercontent.com/52694635/60871954-72961580-a251-11e9-9594-2c9a31f1ae74.png)
![image](https://user-images.githubusercontent.com/52694635/60872079-acffb280-a251-11e9-9cad-bb0621d6dbc1.png)
![image](https://user-images.githubusercontent.com/52694635/60872094-b5f08400-a251-11e9-8a74-a171beb7d680.png)

**Comment by magento-engcom-team** [comment] 2019-07-09 18:12
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17993`, `MC-17994` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by konarshankar07** [comment] 2019-08-20 06:12
This issue has been fixed 
Related commit is https://github.com/magento/magento2/commit/250180b7ee67d75c888dedc4ca99012148f66945

**Comment by konarshankar07** [comment] 2019-08-20 06:18
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-08-20 06:18
Hi @konarshankar07. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` release line

**Comment by konarshankar07** [comment] 2019-08-20 06:19
@magento give me 2.2 instance

**Comment by konarshankar07** [comment] 2019-08-20 06:21
How can we test this in magento 2.2.x vanilla instance?

**Comment by konarshankar07** [comment] 2019-08-21 04:46
we can't test this issue in 2.2 develop so I'm closing this issue.
Thanks

**Comment by deepjoshi94** [comment] 2020-02-22 11:38
Hello,
I am facing the same issue with Magento 2.3.2 CE.
Any fixes for this?

**Comment by pradeep-wagento** [comment] 2020-02-22 15:28
@deepjoshi94 
You can use this fix https://github.com/magento/magento2/pull/26662/commits/8f4360b3d0e501d54d66bcf6cd20d26174824319

**Comment by engcom-Delta** [comment] 2020-06-25 06:48
@deepjoshi94 , @TaniRay123  I'm not able to reproduce issue on clean 2.4-develop.
![Peek 2020-06-25 09-44](https://user-images.githubusercontent.com/51681379/85669549-9fdd0d00-b6c8-11ea-8239-75e35068f0bf.gif)
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Delta** 2020-06-25 06:48 UTC
Labels: Component: Checkout, Issue: Clear Description, Issue: Format is valid, Component: Multishipping
