### ISSUE TITLE
How override html file in web base

### ISSUE THREAD

**Issue by OlgaBurtyka** [magento/magento2#9246] opened 2017-04-14 09:34 UTC
Hi! How In my extension or theme I can override  Magento/Ui/view/base/web/templates/grid/filters/filters.html file. I don't need override js. Only this file. Thanks.

**Comment by korostii** [comment] 2017-04-18 18:00
I would suggest that you read about theming in Magento2 in order to understand how the templates get overriden, here's [the related part of devdocs](http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/themes/theme-inherit.html#theme-inherit-templates)
Further on, if you are looking for some help or an advice regarding setup or development please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.
The issues which cannot be consistently reproduced on a clean installation of Magento 2 CE aren't likely to get resolved in here.

**Comment by magento-engcom-team** [comment] 2017-09-21 09:58
@OlgaBurtyka, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Closed as completed by magento-engcom-team** 2017-09-21 09:58 UTC
Labels: Issue: Format is not valid
