### ISSUE TITLE
Setting product attribute description and short_description to scope website doesn't have any effect.

### ISSUE THREAD

**Issue by paales** [magento/magento2#6750] opened 2016-09-26 08:53 UTC
### Preconditions

1. 2.1.0
### Steps to reproduce

1. Set store the scope of short_description and description to website
2. Edit a product, you now see [website] next to the description and short description.
3. Save the product information on a store view scope (you can't select website scope)
### Expected result

1. You can only set the value on the website scope instead of the store view scope.
2. Information from the description is visible on all store views.
### Actual result

1. Store view specific information is saved and displayed as if the scope of the attribute is store view.

**Comment by sevos1984** [comment] 2016-09-30 09:14
Internal ticket created MAGETWO-59174. Thanks for reporting

**Comment by magento-engcom-team** [comment] 2017-10-10 15:30
@paales, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-10 15:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Clear Description, Issue: Format is valid, Partner: Reach Digital
