### ISSUE TITLE
 inventory_source_item table is not updated when delete a product from Admin Panel

### ISSUE THREAD

**Issue by salvatorecorsaro91** [magento/magento2#36992] opened 2023-03-07 11:13 UTC
### Steps to reproduce

1. Go to admin panel and delete a product.
2. The deleted product exists in the inventory_source_item table

### Expected result

The deleted product not exists in the inventory_source_item table

### Actual result

The deleted product exists in the inventory_source_item table

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-03-07 13:10
Hi @salvatorecorsaro91,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**


- Go to admin panel and delete a product.
- The deleted product exists in the inventory_source_item table


After creating a product.

<img width="1500" alt="Screenshot 2023-03-07 at 6 36 13 PM" src="https://user-images.githubusercontent.com/51680745/223431333-961a9b1e-e5f8-42c8-8821-957c2b3803b0.png">



After deleting a product.There is no record for deleted product.


<img width="1497" alt="Screenshot 2023-03-07 at 6 37 17 PM" src="https://user-images.githubusercontent.com/51680745/223431481-e5053dd0-8495-4021-aa61-b93dae9ca361.png">


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by salvatorecorsaro91** [comment] 2023-03-07 13:17
Thanks, but my issue is on **inventory_source_item** table, no in **catalog_inventory_stock_item**. I believe that this tables are different. I use in my project magento 2.4.4

**Comment by engcom-Bravo** [comment] 2023-03-08 06:15
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-03-08 13:25
Hi @salvatorecorsaro91,

Thanks for your update.




If we are using the enabled MSI functionalities with the default stock and default source only, then, when you update a product's qty, the same qty will be displayed on both `inventory_source_item` and `cataloginventory_stock_item` tables.

when we have different stocks with sources assigned to your product it will not displayed on both tables.

Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-03-20 06:13
Hi @salvatorecorsaro91,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-03-20 06:13 UTC
Labels: Issue: needs update, Reported on 2.4.x
