### ISSUE TITLE
Can't install sample data

### ISSUE THREAD

**Issue by minhluan259** [magento/magento2#1216] opened 2015-04-27 04:36 UTC
Windows 8.1 / Xampp V3.2.1

By Setup Wizard: 

98% (about 1h)
http://www.awesomescreenshot.com/image/144185/a1c96922f99038abcdaaaff0d562b2af

By command:

Luan@MINHLUAN /d/App/htdocs/magentodev/dev/tools/Magento/Tools/SampleData (maste
r)
$ php -f install.php -- --admin_user=admin

Fatal error: Cannot instantiate interface Symfony\Component\Console\Output\OutputInterface in D:\App\htdocs\magentodev\lib\internal\Magento\Framework\ObjectManager\Factory\Dynamic\Developer.php on line 75

Call Stack:
    0.0003     129504   1. {main}() D:\App\htdocs\magentodev\dev\tools\Magento\Tools\SampleData\install.php:0
    8.2838   11881648   2. Magento\Framework\App\Bootstrap->run() D:\App\htdocs\magentodev\dev\tools\Magento\Tools\SampleData\install.php:30
    8.3015   11903296   3. Magento\Tools\SampleData\InstallerApp->launch() D:\App\htdocs\magentodev\lib\internal\Magento\Framework\App\Bootstrap.php:245
    8.4709   11907960   4. Magento\Framework\ObjectManager\ObjectManager->get()
D:\App\htdocs\magentodev\dev\tools\Magento\Tools\SampleData\InstallerApp.php:94
    8.4710   11908040   5.Magento\Framework\ObjectManager\Factory\Dynamic\Developer>create() D:\App\htdocs\magentodev\lib\internal\Magento\Framework\ObjectManager\ObjectManager.php:71
    8.5846   11929816   6.Magento\Framework\ObjectManager\Factory\Dynamic\Developer>_resolveArguments() D:\App\htdocs\magentodev\lib\internal\Magento\Framework\ObjectManager\Factory\Dynamic\Developer.php:84
    8.5848   11930600   7.Magento\Framework\ObjectManager\Factory\AbstractFactory>resolveArgument() D:\App\htdocs\magentodev\lib\internal\Magento\Framework\ObjectManager\Factory\Dynamic\Developer.php:53
    8.5848   11930632   8. Magento\Framework\ObjectManager\ObjectManager->get()
D:\App\htdocs\magentodev\lib\internal\Magento\Framework\ObjectManager\Factory\AbstractFactory.php:236
    8.5848   11930728   9.Magento\Framework\ObjectManager\Factory\Dynamic\Developer>create() D:\App\htdocs\magentodev\lib\internal\Magento\Framework\ObjectManager\ObjectManager.php:71

**Comment by robjmills** [comment] 2015-04-27 11:30
+1

**Comment by adzminz** [comment] 2015-04-27 14:15
+1

**Comment by kokoc** [comment] 2015-04-27 15:35
Thank you for reporting the issue. We will fix the problem and get back to you once we have the working code.
Internal reference: MAGETWO-36702

**Comment by anshumanravi** [comment] 2015-04-28 10:55
+1

**Comment by therouv** [comment] 2015-04-30 16:25
Error exists still with latest sample data (Tag `0.74.0-beta7`).

**Comment by adzminz** [comment] 2015-05-01 09:56
+1 for 0.74.0-beta7

**Comment by asrob** [comment] 2015-05-02 06:32
+1 for 0.74.0-beta7

**Comment by asrob** [comment] 2015-05-02 06:57
I got these errors when install it with sample data via web:

```
Installing product links:
.......................................................................................................................................................................................................................................................................................................................................................................
Installing orders:
[ERROR] exception 'Magento\Framework\Exception\NoSuchEntityException' with message 'No such entity with cartId = 1' in /var/www/html/lib/internal/Magento/Framework/Exception/NoSuchEntityException.php:38
Stack trace:
#0 /var/www/html/app/code/Magento/Quote/Model/QuoteRepository.php(194): Magento\Framework\Exception\NoSuchEntityException::singleField('cartId', '1')
#1 /var/www/html/app/code/Magento/Quote/Model/QuoteRepository.php(88): Magento\Quote\Model\QuoteRepository->loadQuote('load', 'cartId', '1', Array)
#2 /var/www/html/var/generation/Magento/Quote/Model/QuoteRepository/Interceptor.php(135): Magento\Quote\Model\QuoteRepository->get('1', Array)
#3 /var/www/html/app/code/Magento/Backend/Model/Session/Quote.php(146): Magento\Quote\Model\QuoteRepository\Interceptor->get('1', Array)
#4 /var/www/html/app/code/Magento/Sales/Model/AdminOrder/Create.php(429): Magento\Backend\Model\Session\Quote->getQuote()
#5 /var/www/html/app/code/Magento/Sales/Model/AdminOrder/Create.php(1545): Magento\Sales\Model\AdminOrder\Create->getQuote()
#6 /var/www/html/app/code/Magento/Sales/Model/AdminOrder/Create.php(1597): Magento\Sales\Model\AdminOrder\Create->setAccountData(Array)
#7 /var/www/html/dev/tools/Magento/Tools/SampleData/Module/Sales/Setup/Order/Processor.php(163): Magento\Sales\Model\AdminOrder\Create->importPostData(Array)
#8 /var/www/html/dev/tools/Magento/Tools/SampleData/Module/Sales/Setup/Order/Processor.php(123): Magento\Tools\SampleData\Module\Sales\Setup\Order\Processor->processQuote(Array)
#9 /var/www/html/dev/tools/Magento/Tools/SampleData/Module/Sales/Setup/Order.php(77): Magento\Tools\SampleData\Module\Sales\Setup\Order\Processor->createOrder(Array)
#10 /var/www/html/dev/tools/Magento/Tools/SampleData/Helper/PostInstaller.php(86): Magento\Tools\SampleData\Module\Sales\Setup\Order->run()
#11 /var/www/html/dev/tools/Magento/Tools/SampleData/Installer.php(89): Magento\Tools\SampleData\Helper\PostInstaller->run()
#12 /var/www/html/setup/src/Magento/Setup/Model/SampleData.php(76): Magento\Tools\SampleData\Installer->run(Object(Magento\User\Model\User))
#13 /var/www/html/setup/src/Magento/Setup/Model/Installer.php(1120): Magento\Setup\Model\SampleData->install(Object(Magento\Framework\ObjectManager\ObjectManager), Object(Magento\Setup\Model\WebLogger), 'asrob')
#14 [internal function]: Magento\Setup\Model\Installer->installSampleData(Array)
#15 /var/www/html/setup/src/Magento/Setup/Model/Installer.php(288): call_user_func_array(Array, Array)
#16 /var/www/html/setup/src/Magento/Setup/Controller/Install.php(87): Magento\Setup\Model\Installer->install(Array)
#17 /var/www/html/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractActionController.php(83): Magento\Setup\Controller\Install->startAction()
#18 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#19 /var/www/html/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#20 /var/www/html/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#21 /var/www/html/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#22 /var/www/html/vendor/zendframework/zend-mvc/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#23 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#24 /var/www/html/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#25 /var/www/html/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#26 /var/www/html/vendor/zendframework/zend-mvc/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#27 /var/www/html/setup/index.php(26): Zend\Mvc\Application->run()
#28 {main}
```

**Comment by cmuench** [comment] 2015-05-03 11:51
The problem still exists. Tested with latest n98-magerun2 developer version.

**Comment by benmarks** [comment] 2015-05-03 12:59
+1

**Comment by martindines** [comment] 2015-05-04 20:47
+1

**Comment by kieranja** [comment] 2015-05-05 13:08
+1

**Comment by navarr** [comment] 2015-05-05 15:14
+1

**Comment by Styopchik** [comment] 2015-05-06 10:27
+1

**Comment by vpelipenko** [comment] 2015-05-06 10:58
Guys, we are working on the fix, Internal ticket is in progress now.

**Comment by kokoc** [comment] 2015-05-06 12:34
@asrob Seems like you're trying to install sample data on top of already installed data. Could you try to clean up the database and try again?

**Comment by hirenvasani** [comment] 2015-05-07 05:54
+1

**Comment by asrob** [comment] 2015-05-08 19:48
@kokoc Sure, I'll try again soon.

**Comment by asrob** [comment] 2015-05-09 09:51
@kokoc I tried it again but I got an error:
```
Installing admin user...

Enabling caches:
Current status:
Array
(
[config] => 1
[layout] => 1
[block_html] => 1
[view_files_fallback] => 1
[view_files_preprocessing] => 1
[collections] => 1
[db_ddl] => 1
[eav] => 1
[full_page] => 1
[translate] => 1
[config_integration] => 1
[config_integration_api] => 1
[config_webservice] => 1
)


Installing sample data:
[ERROR] exception 'Magento\Framework\Exception\LocalizedException' with message 'Area code is already set' in /var/www/magento2.asrob.eu/public_html/lib/internal/Magento/Framework/App/State.php:137
Stack trace:
#0 /var/www/magento2.asrob.eu/public_html/setup/src/Magento/Setup/Model/SampleData.php(66): Magento\Framework\App\State->setAreaCode('adminhtml')
#1 /var/www/magento2.asrob.eu/public_html/setup/src/Magento/Setup/Model/Installer.php(1123): Magento\Setup\Model\SampleData->install(Object(Magento\Framework\ObjectManager\ObjectManager), Object(Magento\Setup\Model\WebLogger), 'admin')
#2 [internal function]: Magento\Setup\Model\Installer->installSampleData(Array)
#3 /var/www/magento2.asrob.eu/public_html/setup/src/Magento/Setup/Model/Installer.php(288): call_user_func_array(Array, Array)
#4 /var/www/magento2.asrob.eu/public_html/setup/src/Magento/Setup/Controller/Install.php(87): Magento\Setup\Model\Installer->install(Array)
#5 /var/www/magento2.asrob.eu/public_html/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractActionController.php(83): Magento\Setup\Controller\Install->startAction()
#6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /var/www/magento2.asrob.eu/public_html/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#8 /var/www/magento2.asrob.eu/public_html/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /var/www/magento2.asrob.eu/public_html/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /var/www/magento2.asrob.eu/public_html/vendor/zendframework/zend-mvc/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 /var/www/magento2.asrob.eu/public_html/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#13 /var/www/magento2.asrob.eu/public_html/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /var/www/magento2.asrob.eu/public_html/vendor/zendframework/zend-mvc/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /var/www/magento2.asrob.eu/public_html/setup/index.php(26): Zend\Mvc\Application->run()
#16 {main}
```

Fresh database, magento2 beta-8 with sample data 0.74.0-beta7.

I tried it without sample data but after install I got 404 error. But this is another issue. (https://github.com/magento/magento2/issues/1250)

**Comment by OnTapKristjan** [comment] 2015-05-14 08:25
Guys, in case your 'dev/tools/Magento/Tools/SampleData/install.php' fails
you can try the following workaround.

Run `php bin/magento setup:install --use_sample_data --admin_user=xxx --admin_password=xxx --admin_email=xxx --admin_firstname=xxx --admin_lastname=xxx`
To install sample data in TOP of your current data.

Or you can run `php bin/magento setup:install --cleanup_database --use_sample_data --admin_user=xxx --admin_password=xxx --admin_email=xxx --admin_firstname=xxx --admin_lastname=xxx`
To cleanup your DB and install the sample-data into a clean DB

*_replace the xxx with your existing admin credentials_

**Comment by therouv** [comment] 2015-05-16 17:00
I can confirm that the sample data installation now works again! Thank you :-)

**Comment by kokoc** [comment] 2015-05-25 16:55
The fix is now available in 0.74.0-beta9. Thank you very much for your contribution and continued support to Magento 2! 

@minhluan259 Could you please verify the issue?

**Comment by minhluan259** [comment] 2015-05-26 04:02
By Setup Wizard:

![capture](https://cloud.githubusercontent.com/assets/7834473/7804807/755ff298-0392-11e5-8c7a-342f4b63c37d.PNG)

After setup: 

![capture2](https://cloud.githubusercontent.com/assets/7834473/7805078/4a112cc0-0396-11e5-804c-2cf63e316dca.PNG)

I enter command: php -f dev/tools/Magento/Tools/View/deploy.php
Could not open input file: dev/tools/Magento/Tools/View/deploy.php

![capture3](https://cloud.githubusercontent.com/assets/7834473/7805108/a9f0f486-0396-11e5-8b61-45de7951295f.PNG)

**Comment by buskamuza** [comment] 2015-05-26 07:12
Hi @minhluan259,

1. Regarding sample data. Due to structure changes in the Sample Data packages, temporary it's not installed during Magento installation. It should be fixed soon apublishingcation of a new sample data module. Meanwhile sample data can be installed via a separate tool dev/tools/Magento/Tools/SampleData/installphp
2. Regardind deploy.php tool. It has been converted to a command 'setup:static-content:deploy' of 'bin/magento' tool.

**Comment by buskamuza** [comment] 2015-05-27 00:19
Sample Data packages are fixed now. Please, try to reinstall. `magento/sample-data` meta-package of version `0.74.0-beta10` should be used.

**Comment by minhluan259** [comment] 2015-05-27 09:05
@buskamuza . It still error:
![capture](https://cloud.githubusercontent.com/assets/7834473/7832538/138c2b6a-048a-11e5-8451-ee1797c8a0a3.PNG)
![capture3](https://cloud.githubusercontent.com/assets/7834473/7832539/14f9929e-048a-11e5-91cb-9a108c858b96.PNG)

**Comment by kokoc** [comment] 2015-05-27 10:56
Similar issue #1295

**Comment by voleye** [comment] 2015-05-27 12:49
@minhluan259, do you have xdebug enabled?

**Comment by kokoc** [comment] 2015-05-27 14:26
@minhluan259 we identified a source of timeouts. Appropriate item is placed in backlog: MAGETWO-37970.

**Comment by buskamuza** [comment] 2015-05-27 16:25
@minhluan259, thanks for the details. Could you, please, help us to clarify installation of Sample Data?
1. Have you installed the latest version of Sample Data (`0.74.0-beta10`)?
2. Do you have Sample Data module (`app/code/Magento/SampleData`)?
3. Do you have `sampledata:install` command available in `./bin/magento list` tool?

Thanks for the hellp

**Comment by minhluan259** [comment] 2015-05-27 17:19
@buskamuza 
1. Yes, I has installed the last version of Sample Data.
composer require magento/sample-data:~0.74.0-beta9
2. Yes, I has Sample Data module.
3. Yes, I has  sampledata:install command.

**Comment by minhluan259** [comment] 2015-05-27 17:22
@voleye, I has xdebug enabled.
[XDebug]
zend_extension = "D:\App\php\ext\php_xdebug.dll"
xdebug.max_nesting_level=50000
xdebug.profiler_enable = 0
xdebug.profiler_enable_trigger = 0
xdebug.profiler_output_dir = "D:\App\tmp"
xdebug.profiler_output_name = "cachegrind.out.%t-%s"
xdebug.remote_enable = 1

**Comment by buskamuza** [comment] 2015-05-27 19:47
@minhluan259 , thanks so much!
Could you, please, try `./bin/magento sampledata:install` command instead of the tool from `dev/tools/...SampleData`? The Sample Data had to be deleted by Composer, but looks like it didn't (as I can see from your screenshot). We'll check it.
The tool may be outdated comparing to the new command.

**Comment by minhluan259** [comment] 2015-05-28 02:22
@kokoc , @buskamuza. After remove set_time_limit(3600) on line 78 Magento\SampleData\Model\Installer and install (about 2h, so slowly) by Setup Wizard have success.
But another issue:
![capture](https://cloud.githubusercontent.com/assets/7834473/7851004/544c810c-0513-11e5-81c8-fc6eeb601a41.PNG)
setup:static-content:deploy (about 1h)
![capture2](https://cloud.githubusercontent.com/assets/7834473/7851408/7df40c9a-0519-11e5-9990-e55ec82c4a91.PNG)
![capture4](https://cloud.githubusercontent.com/assets/7834473/7851496/fe704478-051a-11e5-8fc6-385571cbd3f6.PNG)

**Comment by buskamuza** [comment] 2015-05-28 14:43
@minhluan259 , enabled XDebug may cause significant performance degradation, that's why you may have so long installation. Let us know, if you try it with xDebug disabled and it's still so slow.

And I created an internal ticket for these warnings in the deployment command - MAGETWO-38010
Looks like it's a Windows only issue.

**Comment by vpelipenko** [comment] 2015-07-31 15:45
@minhluan259, internal ticket was fixed and closed. Could you verify the fix on the latest source code in develop branch?

**Closed** 2015-08-19 09:56 UTC
Labels: acknowledged, bug, MX, needs update
