### ISSUE TITLE
Order processing events defined in etc/frontend/events.xml won't work in production mode, works in development mode

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#35680] opened 2022-06-25 10:47 UTC
### Preconditions and environment

- Magento version: 2.4.3-p1

### Steps to reproduce

1. create a new module
2. add an event for the frontend related code part: `etc/frontend/events.xml` and add an observer
```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
    <event name="sales_model_service_quote_submit_success">
        <observer name="customer_event" instance="My\Module\Observer\OrderObserver" />
    </event>
</config>
```
or any event related to order processing / getting order data

```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
    <event name="checkout_submit_all_after">
        <observer name="customer_event" instance="My\Module\Observer\OrderObserver" />
    </event>
</config>
```

3. Log order data somewhere
```
/** @var Order|DataObject $order */ 
$order = $observer->getEvent()->getOrder();
if ($order) {
     // log order data anywhere, even with logger interface
     $this->logger->critical($order->getIncrementId());
}

```

5. 

* ENABLE PRODUCTION MODE *

### Expected result

I can see the logged information in the log files

### Actual result

Event is not fired at all, it is missed.

### Additional information

This only happens in production mode, works fine in dev mode. 
Moving events to `etc/events.xml` solves the problem, but I want my observer to work ONLY on the frontend part. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by qsolutions-pl** [comment] 2022-07-02 10:10
I'll just leave a note so the issue is not closed by stale-bot

**Comment by engcom-November** [comment] 2022-07-20 09:39
Hi @qsolutions-pl ,
Thank you for reporting. Verified the issue on Magento 2.4-develop branch but couldn't reproduce the issue.
**Steps performed:**
    1. Create a custom module
    2. Set mode developer
    3. Add events.xml in etc/frontend
Its not getting called in developer and production mode. Because all orders related requests perform by REST API calls. So you need to add events.xml in  etc webapi_rest directory or global inside etc/events.xml

Thank you.

**Comment by engcom-November** [comment] 2022-08-03 10:37
Hi @qsolutions-pl ,
We are closing this issue as there has been  no latest update on the same. Kndly reopen/create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-08-03 10:37 UTC
Labels: Issue:  Cannot Reproduce, Triage: Dev.Experience, Issue: needs update

**Comment by hans-vereyken** [comment] 2023-05-16 12:53
I'm a bit late to the party, but it's expected. Move your events.xml to the webapi_rest as described here:
https://github.com/magento/magento2/issues/1581
