### ISSUE TITLE
Unable to create a refund to store credit through API document.

### ISSUE THREAD

**Issue by MaddatiNishitha** [magento/magento2#32933] opened 2021-05-04 06:56 UTC
Preconditions (*)

CE 2.4.2

Summary of the issue:
We are trying to create a refund to the customer's store credit with the API call "/V1/creditmemo".
We are mapping all the required fields in the post body, but the store credits are not reflected in the Magento UI customer account.

Steps to reproduce (*)

Create order in Magento UI.
Create an Invoice for that order.
with the help of API call "/V1/creditmemo" create a refund to store credit for that order through postman.
Expected result (*)
Refunds are creating but the store credits are not reflecting in the customer's account in Magento UI.

Actual result (*)
Refunds should create and the store credits should reflect in the customer's account in Magento UI.

**Comment by MaddatiNishitha** [comment] 2021-05-04 06:58
Hi Team,
We have added all the below details in the description
Summary of the issue
Information on your environment
Steps to reproduce
Expected and actual results

**Comment by engcom-Oscar** [comment] 2021-05-05 06:02
duplicate of https://github.com/magento/partners-magento2ee/issues/537

**Closed as completed by engcom-Oscar** 2021-05-05 06:02 UTC
Labels: Component: Sales, Issue: ready for confirmation, Reported on 2.4.2

**Comment by MaddatiNishitha** [comment] 2021-05-18 03:45
Hi Team, 

We are getting 404 page not found error for [magento/partners-magento2ee#537](url). So, could you please provide us more information regarding this.

**Comment by MaddatiNishitha** [comment] 2021-06-09 11:33
Hi Team,
A gentle reminder on the above comment. Please provide us more information
