### ISSUE TITLE
"Select All" then "Update Attributes" doesn't work on product grid

### ISSUE THREAD

**Issue by steverobbins** [magento/magento2#1796] opened 2015-09-04 21:07 UTC
On the product grid, when I "Select All" and then try to mass update attributes I get an error "Please select products for attributes update."

![image](http://g.recordit.co/ZAH92IFZ1N.gif)

**Comment by dfediuk** [comment] 2015-09-04 21:16
Duplicate of https://github.com/magento/magento2/issues/1506

**Closed** 2015-09-04 21:23 UTC
