### ISSUE TITLE
SQL error on 2.4.4 prerelease when saving a product with new source and stock

### ISSUE THREAD

**Issue by MargoKep** [magento/magento2#35262] opened 2022-04-04 14:10 UTC
Preconditions (*)
1. Magento 2.4.4 prerelease
2. PHP 8.1
3. Magento with prefix in DB

Steps to reproduce (*)
1.Create new source 
2.Create new stock and assign for new source
4. Going to: Catalog-->Product--> Open random product, Assigning for new Source, add Q-ty
5. Push the Save button

Expected result (*)
1. Success  after save wtihout error, and  seeing on the Products Greed Q-ty >0 in column Stock

Actual result (*)
1. SQL Error and on the Products Grid in column Stock=0 and not displaying on FrontArea:
https://imgur.com/a/Mj7vS0x       https://imgur.com/a/POWJtKH
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'docker_mg244eegolaya.pref_reservations_temp_for_stock_2' doesn't exist, query was: SELECT `source_item`.`sku`, SUM(IF(source_item.status = 0, 0, source_item.quantity)) AS `quantity`, IF((reservations.reservation_qty IS NULL OR (SUM(source_item.quantity) + reservations.reservation_qty) > 0) AND (((legacy_stock_item.use_config_backorders = 0 AND legacy_stock_item.backorders <> 0) AND (legacy_stock_item.min_qty >= 0 OR legacy_stock_item.qty > legacy_stock_item.min_qty) AND SUM(IF(source_item.status = 0, 0, 1))) OR ((legacy_stock_item.use_config_manage_stock = 0 AND legacy_stock_item.manage_stock = 0)) OR ((legacy_stock_item.use_config_min_qty = 1 AND SUM(IF(source_item.status = 0, 0, source_item.quantity)) > 0) OR (legacy_stock_item.use_config_min_qty = 0 AND SUM(IF(source_item.status = 0, 0, source_item.quantity)) > legacy_stock_item.min_qty)) OR (product.sku IS NULL)), 1, 0) AS `is_salable` FROM `pref_inventory_source_item` AS `source_item` LEFT JOIN `pref_catalog_product_entity` AS `product` ON product.sku = source_item.sku AND (product.created_in <= 1 AND product.updated_in > 1) LEFT JOIN `pref_cataloginventory_stock_item` AS `legacy_stock_item` ON product.entity_id = legacy_stock_item.product_id LEFT JOIN `pref_reservations_temp_for_stock_2` AS `reservations` ON source_item.sku = reservations.sku WHERE (source_item.source_code IN ('a2')) AND (source_item.sku IN ('24-MB01')) GROUP BY `source_item`.`sku`

Severity (*)  S0

**Comment by MargoKep** [comment] 2022-04-06 07:01
Update Precondition:
3. Magento with prefix in DB

**Comment by awkomarov** [comment] 2022-04-06 07:29
The issue was caused by DB prefix. Temporary table "reservations_temp_for_stock_" created without DB prefix. As a soultion I created solution, see attached diff/
[fix.txt](https://github.com/magento/magento2/files/8424584/fix.txt)

**Comment by engcom-Delta** [comment] 2022-04-06 12:34
Hi @MargoKep ,
Thank you for raising an issue , We tried to reproduce the issue on Magento 2.4.3-p1 instance , in fact we are not able to reproduce same error , getting different error. Hence request to review the provided steps.
Actual results: "The stock item was unable to be saved. Please try again."

Test Results screenshots:
<img width="1440" alt="Screenshot 2022-04-06 at 5 35 39 PM" src="https://user-images.githubusercontent.com/51681379/161975191-712b06e4-3110-45f9-928c-faff9e3c25ae.png">
<img width="1440" alt="Screenshot 2022-04-06 at 5 39 44 PM" src="https://user-images.githubusercontent.com/51681379/161975225-b34fa6f8-a715-42a9-be09-21f1b6ccedc4.png">
<img width="1440" alt="Screenshot 2022-04-06 at 5 40 05 PM" src="https://user-images.githubusercontent.com/51681379/161975262-a01402ff-4aa9-499d-a6a7-7520113f3c1e.png">
<img width="1440" alt="Screenshot 2022-04-06 at 5 51 39 PM" src="https://user-images.githubusercontent.com/51681379/161975331-47c4a3c5-5328-4de6-a0d7-2ed216678ced.png">
<img width="1440" alt="Screenshot 2022-04-06 at 5 52 13 PM" src="https://user-images.githubusercontent.com/51681379/161975376-f9ce69c7-2736-4e9e-937c-a541524fa5c5.png">
<img width="1440" alt="Screenshot 2022-04-06 at 5 55 55 PM" src="https://user-images.githubusercontent.com/51681379/161975431-a0e32851-0f29-41a1-aae6-3cbbcedf4515.png">

**Comment by MargoKep** [comment] 2022-04-06 12:40
> engcom-Delta

Precondition: Version Magento-2.4.4 prerelease!!!  NOT 2.4.3
@engcom-Delta [engcom-Delta](https://github.com/engcom-Delta)

**Comment by engcom-Hotel** [comment] 2022-04-21 08:26
Hello @MargoKep,

Thanks for the report and collaboration!

We have tried to reproduce the issue in Magento 2.4.4 and the issue is reproducible for us with the given steps. Please have a look into the below screenshot for reference:

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/51681618/164413013-754c0fd7-78e1-4795-be67-00aebda9f450.png">

Hence confirming this issue.

Thanks

**Comment by MargoKep** [comment] 2022-04-21 08:43
> Thanks for the report and collaboration!
> 
> We have tried to reproduce the issue in Magento 2.4.4 and the issue is reproducible for us with the given steps. Please have a look into the below screenshot for reference:

Thank you very much for your workong.

**Comment by engcom-Alfa** [comment] 2022-05-20 08:39
Hello @MargoKep 

As I can see this issue got fixed in the scope of the internal Jira ticket `AC-2896` by the internal team
Related commits: https://github.com/magento/magento2/commit/b092dd6df013e8b1e77e8b5d639148ed76a7172a

Based on Jira target version is 2.4.5

**Closed as completed by engcom-Alfa** 2022-05-20 08:39 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P0, Progress: done, Area: Framework, Reported on 2.4.4

**Comment by hostep** [comment] 2022-06-05 09:37
The commit @engcom-Alfa mentioned doesn't seem to be correct, this one seems a lot more related: https://github.com/magento/inventory/commit/d236405c22d3005c642c70348cfd372dbcb98b76

**Comment by engcom-Alfa** [comment] 2022-06-17 08:56
> The commit @engcom-Alfa mentioned doesn't seem to be correct, this one seems a lot more related: [magento/inventory@d236405](https://github.com/magento/inventory/commit/d236405c22d3005c642c70348cfd372dbcb98b76)

Thanks for this!
