### ISSUE TITLE
Web Setup Wizard not visible in backend (V.2.1.2) ONGOING

### ISSUE THREAD

**Issue by dharake** [magento/magento2#7623] opened 2016-11-30 12:08 UTC
The component manager page returns a 404 when Magento is installed using the more secure /path/to/magento/pub (vs. /path/to/magento) as the system web root in Magento CE 2.1.2
**Preconditions:**
Magento CE 2.1.2

**Steps to reproduce:**
Install Magento
Configure Web Root to point to Magento's pub folder
Navigate in admin to System -> Web Setup Wizard

**Expected result**
Web Setup Wizard page displays

**Actual result**
No Menu item for Web Setup Wizard
Standard Magento 404 (Whoops, our bad...) page displays if manually directed to URL
When using SSL & Varnish: Receive "This site can’t provide a secure connection" ERR_SSL_PROTOCOL_ERROR

**Comment by dharake** [comment] 2016-11-30 12:22
A work around that was achieved on one client's site:

**Procedure:**
Install Magento 2.1.0
Use the web setup wizard to upgrade Magento to 2.1.2

**Result:**
You should have the most up to date version with a working Web Setup Wizard

**Comment by veloraven** [comment] 2016-11-30 13:41
@dharake thank you for your report.
We already have internal ticket MAGETWO-52799 for this issue.
I have updated it with link to this report.

**Comment by dharake** [comment] 2016-11-30 14:03
@veloraven thanks for your help. There was a commit in June for MAGETWO-52799, https://github.com/magento/magento2/commit/2f9ccf08f7a1b50762a089c905644ead9f97f10f

Any idea if this works? If so would it not have been included in last release in Ocotber of Magento 2.1.2?

**Comment by timstoel** [comment] 2016-11-30 18:51
@dharake I am not sure if rolling back to 2.1.0 is an option on our production site.  I believe we installed 2.1.1 for our production setup.

Is there a way to get the same results as installing 2.1.0 and upgrading to 2.1.2 by editing some files related to this issue?

**Comment by dharake** [comment] 2016-11-30 18:55
Possibly this commit works : https://github.com/magento/magento2/commit/2f9ccf08f7a1b50762a089c905644ead9f97f10f

Awaiting confirmation from @veloraven 

If you test it let me know, but obviously don't do this on your production site :)

**Comment by timstoel** [comment] 2016-11-30 19:12
@dharake 

In my 2.1.1 installation the lines in app/code/Magento/Backend/etc/di.xml that need to be deleted are not present.  In lib/internal/Magento/Framework/App/DocRootLocator.php the file already matches the commit.

I added the three lines to app/code/Magento/Backend/etc/adminhtml/di.xml and nothing has changed.

**Comment by dharake** [comment] 2016-11-30 19:17
Ok @timstoel thanks for that. We'll have to wait and see what the Magento peeps have to say. Personally I wouldn't hold my breath seeing they have been sitting on this issue since April. Really poor job I'm afraid, this undermines the whole Magento ecosystem if no one can install mods.

**Comment by timstoel** [comment] 2016-11-30 19:20
@dharake So I could get around this by installing 2.1.0 and upgrading to 2.1.2?  It would take some time to move our 5000 items with attributes and template and everything, but I've got to move forward somehow.  My other option is Magento 1.9 and moving to 2 later on.  I can't just sit here and wait for Magento to fix this.

**Comment by dharake** [comment] 2016-11-30 19:23
See how you get on with that on a blank install first, but it worked for me. Conversely you'd have to import all the items back to 1.9 anyway, just to have to upgrade again to 2. So although it's a pain, that would still be my recommendation. Especially if you've been working on the templates on 2, because they won't work for 1.9

**Comment by timstoel** [comment] 2016-11-30 19:24
I'll spin up another VM with 2.1.0, upgrade it and report back.  There is the URL workaround as well, maybe I need to get to 2.1.2 and set up all of my add-ons before I install Varnish.

**Comment by dharake** [comment] 2016-11-30 19:26
I do think the URL workaround is possible, I just struggled doing it with Varnish and had no success. Also, if you are using the nginx sample config from Magento, I think you'll find a bunch of other stuff not working as you expect

**Comment by timstoel** [comment] 2016-11-30 19:58
I just installed 2.1.0 and the Web Setup Wizard link is missing out of the box.  I can use the URL workaround because I have not installed Varnish yet.

My Nginx config is as follows:

`upstream fastcgi_backend {
        server  unix:/run/php/php7.0-fpm.sock;
}

server {
        listen 80;
        server_name testing.domain.com;
        set $MAGE_ROOT /var/www/magento2;
        set $MAGE_MODE developer;
        include /var/www/magento2/nginx.conf.sample;
}`

**Comment by dharake** [comment] 2016-11-30 20:05
What seriously?? How weird. The exact one I used was:

Magento-CE-2.1.0-2016-06-23-02-28-19.tar

Web setup was definitely there when I installed it

**Comment by timstoel** [comment] 2016-11-30 20:12
I used git to install 2.1.0 and it shows 2.1.0 in the backend... Maybe git is my problem

**Comment by fooman** [comment] 2016-11-30 21:08
@timstoel looks like it might be too late for this, but anyone else needing to install an extension from Marketplace: 

It is possible to install extensions from Marketplace **without** using the Web Setup Wizard. You do need command line access, then follow these commands (this uses Fooman_OrderManager as an example):

1. Create a Backup making sure we stay in Maintenance Mode
`php -f bin/magento setup:backup --code --db --media && php -f bin/magento maintenance:enable`
2. Install via Composer, copy the Component Name from your Marketplace > My Purchases
`php -f vendor/composer/composer/bin/composer require fooman/ordermanager-m2`

Public Key: xxxxx
Private Key: xxxxx
To get yours see http://devdocs.magento.com/guides/v2.0/install-gde/prereq/connect-auth.html

3. List all modules - find your new module name under "List of disabled modules"
`php -f bin/magento module:status`
4. Enable the new Extension
`php -f bin/magento module:enable Fooman_OrderManager --clear-static-content`
5. Run database installation upgrades
`php -f bin/magento setup:upgrade`
6. Remove previously compiled classes
`rm -rf var/generation`
7. Compile (only needed in Production Mode)
`php -f bin/magento setup:di:compile`
8. Deploy Static Content (only needed in Production Mode)
`php -f bin/magento setup:static-content:deploy`
9. We are all done - take the store out of maintenance
`php -f bin/magento maintenance:disable`

**Comment by dharake** [comment] 2016-11-30 21:29
@fooman Nice to hear from you, been using your modules for years! Thanks for chipping in and all the great work! As for the cli installation, that's good for devs, but still feel this issue needs urgent resolution. I have 3 Magento 2 websites that need deployment, and would be handy to have a backend to run upgrades from  hehehe.

**Comment by fooman** [comment] 2016-11-30 21:33
thanks @dharake - agreed that this needs solving urgently. Just wanted to give some reassurance to folks who might not be aware of the command line approach (and I think it's better to use the command line in this case rather than attempting a downgrade).

**Comment by dharake** [comment] 2016-11-30 21:38
Agreed, of course! However in @timstoel case apparently the module can't be installed by CLI for some reason (although that doesn't really make sense come to think of it). @timstoel maybe try this approach?

**Comment by fooman** [comment] 2016-11-30 21:48
@dharake let's keep this issue report focussed - get in touch via my email support@fooman.co.nz and I'll respond that way (I'll then delete this comment)

**Comment by dharake** [comment] 2016-11-30 21:50
you're right my bad, I'll email you my findings if I don't an existing solution. Thanks

**Comment by timstoel** [comment] 2016-11-30 22:21
Thanks guys.  I can try using the CLI to install this, the provider of the module does not support this option.  They provide a link to download the files from their website so I did not acquire it through the Magento Marketplace so never really thought of taking this course of action.

**Comment by fooman** [comment] 2016-12-02 08:39
@timstoel if it is on the Marketplace installing it without the Web Setup Wizard with the CLI commands I posted works (the vendor doesn't need to do anything special for this, apart from having their extension on Marketplace in the first place)

**Comment by dharake** [comment] 2016-12-10 18:56
@veloraven do we have any update for MAGETWO-52799?

**Comment by timstoel** [comment] 2016-12-12 21:04
Any news on this?

**Comment by timstoel** [comment] 2016-12-13 20:25
@dharake  -- I downloaded the 2.1.0 tar file and installed and the Web Setup Wizard is not available in the backend either.  This is on a fresh VM with nginx and PHP7.

**Comment by Sharlyll** [comment] 2016-12-22 08:02
any solution on this? Its strange because it shows up on one of my domains and disappears in the other domain. Both are hosted on the same server/account. 

SOLUTION Please?

**Comment by raymatos** [comment] 2017-01-04 00:11
update??

**Comment by timstoel** [comment] 2017-01-04 17:37
The solution is Magento 1.9

**Comment by bakkee** [comment] 2017-01-10 08:06
Any update??

**Comment by nodesales** [comment] 2017-01-13 18:53
I had a 401 unauthorized access error page with "/setup/index.php/session/unlogin" in my url when i try to access Web Setup Wizard.

I installed Magento 2.1.3 trough my cPanel with softaculous and i even installed magento 2 trough composer with ssh and i configured everything but i still get the 401 error page while i'm logged in.

I'm the only user in magento and i am the administrator so how could it be that i don't have access to the Web Setup Wizard.

I checked my .htaccess file but couldn't find anything strange that blocks me accessing the Web Setup Wizard page.

I even turned off Mod Security trough the cPanel but that didn't solve the issue either.

I deleted cache and i've enabled developer mode but without success.

I fixed my file permissions and installed magento in the root folder but even that doesn't work.

I'm using a Hosting's provider with this setup:
Apache version: 2.2.31
PHP version: 5.6.29
Mysql version: 5.6.33-cll-lve

I gave up trying to solve this issue because i'm trying it for a week now, thinking about using Wordpress with Woocommerce instead.

If someone has the solution please share the solution.

**Comment by luism91** [comment] 2017-01-17 04:11
@nodesales Usually http error codes are not related with magento itself(check access log of your web server), maybe ownership of files or permissions itself. Check var/log for exception and debug logs to troubleshoot if it is a magento problem.

@raymatos @bakkee @Sharlyll @timstoel My "solution" was to install Magento 2.1.2 clean install and access the web setup wizard via this direct link. Hope that this helps.

**http://www.yourdomain.com/admin/admin/backendapp/redirect/app/setup/**

Note that the first admin in the request uri could be your custom admin route

[https://github.com/magento/magento2/issues/4159](url)

I found this temporary solution here on a comment of **magenx**

**Comment by shamoon** [comment] 2017-02-09 00:09
@luism91 Thanks for suggestion but still doesnt work for me, I get same result as if I go from admin which is that I get redirected to /setup/index.php/session/unlogin with the message 
> Welcome to Magento Admin, your online store headquarters. 
> To use the Magento setup wizard sign into your Admin account and navigate to System => Tools => Web Setup Wizard

**Comment by fwolfst** [comment] 2017-04-21 13:41
@nikonratm Sure that you are logged in as admin in another tab before visiting http://www.yourdomain.com/admin/admin/backendapp/redirect/app/setup/ ? I can then access the relevant pages (but some other error keeps me in endless "please wait"-loop).

**Comment by vecanc** [comment] 2017-05-05 02:47
I am using 2.1.4, still encountered same issue (with HTTP ERROR 500).  But if I install and run it from windows pc, I can access the setup wizard page.

**Comment by rparsi-commer** [comment] 2017-05-24 21:20
@nodesales 
I'm dealing with same issue, have made some progress.
Please read my comment [here](https://github.com/magento/magento2/issues/5247)

**Comment by drpit** [comment] 2017-08-17 09:23
I lost the link "Web Setup Wizard" when I upgraded from 2.1.5 to 2.1.7.
Since then I have tried many workarounds but none worked.
now if I enter 
https://mywebsite.com/admin/admin/backendapp/redirect/app/setup/ 
I get a part of the page.

**Comment by Sharlyll** [comment] 2017-08-17 16:29
@drpit, you should try manually clearing cache, page cache, generation, view processed in Var folder.

**Comment by magento-engcom-team** [comment] 2017-10-12 10:34
@dharake, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9

**Comment by tlc033** [comment] 2018-02-05 22:20
Solution for me was:
Base URLs (Secure)
-> Use Secure URLs on Storefront -> Yes
-> Use Secure URLs in Admin -> Yes
-> Enable HTTP Strict Transport Security (HSTS) -> Yes
-> Upgrade Insecure Requests -> Yes
php bin/magento cache:clean
https://yadi.sk/i/iPJi4k7X3S86Za
I SOLVE THIS.

**Comment by StibaDu** [comment] 2018-02-09 15:41
My Problem was Cloudflare.

I was looking for a solution, so i started to investigate the error  by looking at the firefox dev console to see what the cause is. 

I found out that in my case, cloudflare the problem is. In the console i could see that rocket loader was causing an error, so i went to cloudflare and just made some page rules for:
https://website.com/setup
Disable security and Rocket Loader Off

this solved my problem and i could access the setup wizzard.

Hope this helps

**Comment by victortodoran** [comment] 2018-06-09 14:52
Magento 2.2.3
No Web Setup Wizard in System > 
Why is this closed?

**Comment by cesaroctaviods** [comment] 2018-08-21 19:52
I have the same issue in magento 2.2.5 :(

**Comment by hitesh-srtpl** [comment] 2018-08-28 11:49
Web setup wizard still not display in admin side. magento 2.2.5

precondition: 
magento default 2.2.5
without sample data

**Comment by dharake** [comment] 2018-09-08 17:29
Wow, created this 2 years ago and still so confusing. Please help instead of just closing the issue. There is no solution still. And this issue is duplicated all over the place, and keeps getting closed. Started in 2.1.2, and still the same thing in 2.2.5!

Just installed Magento 2.2.5, fresh through composer.
Ubuntu 18.04
Nginx
Varnish
SSL
Redis
No modifications made to any files

mage root doesn't include /pub

Still no wizard in menu, and when I try this: https://mywebsite.com/admin/admin/backendapp/redirect/app/setup/

I get this: https://www.mywebsite.com:8080/setup/
with page displaying : This site can’t provide a secure connection

I have the same settings as @tlc033 

My nginx config:

'
upstream fastcgi_backend {
     server  unix:/var/run/php/php7.1-fpm.sock;
 }

server {
    server_name mysite.xyz www.mysite.xyz;
    listen 8080;
    set $MAGE_ROOT /var/www/html/magento2;
    include /var/www/html/magento2/nginx.conf.sample;
}


server {
    server_name mysite.xyz www.mysite.xyz;
    listen 443 ssl http2;

    ssl_certificate /etc/letsencrypt/live/mysite.xyz/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mysite.xyz/privkey.pem; # managed by Certbot

    location / {
        proxy_pass http://127.0.0.1;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
    }

}
'

**Comment by fooman** [comment] 2018-09-20 22:51
This not fixed. 2.2.6:

![image](https://user-images.githubusercontent.com/455508/45850911-38c05500-bd8c-11e8-9626-9d98c731ef6c.png)

**Comment by jos-zz** [comment] 2018-10-04 09:37
Upgraded from CE 2.2.5 to CE 2.2.6 using the Web Setup Wizard.
Now, in **2.2.6**, when I try to access the Web Setup Wizard, I get **404 Not Found (Whoops, our bad...)**.  
Note that **Web Setup Wizard** item is present in admin menu in 2.2.6.  
  
On a different instance, which was upgraded to CE 2.2.6 using composer, the Web Setup Wizard is working fine.

**Comment by magento-engcom-team** [comment] 2018-11-13 15:13
Hi @TomashKhamlai. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2018-11-14 14:14
@TomashKhamlai Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96347`, `MAGETWO-96348` were created

**Comment by pmsteil** [comment] 2019-03-11 18:48
This appears to also be happening on Magento 2.3 also using the Jelastic Magento Cluster install.

I do not have SSL setup and configured, could this be why?

**Comment by magento-engcom-team** [comment] 2019-04-16 14:10
Hi @dharake. Thank you for your report. 
The issue has been fixed in magento/magento2#20182 by @JeroenVanLeusden in 2.3-develop branch
Related commit(s):
 - [8966f5f3a784085d53ee206b1492f708de672e55](https://github.com/magento/magento2/commit/8966f5f3a784085d53ee206b1492f708de672e55)
 - [204675e48423e7472761373cebab698787baffdc](https://github.com/magento/magento2/commit/204675e48423e7472761373cebab698787baffdc)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-04-16 14:10 UTC
Labels: Issue: Ready for Work, bug report, Component: Setup, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by dharake** [comment] 2019-04-16 15:10
> Hi @dharake. Thank you for your report.
> The issue has been fixed in #20182 by @JeroenVanLeusden in 2.3-develop branch
> Related commit(s):
> 
> * [8966f5f3a784085d53ee206b1492f708de672e55](https://github.com/magento/magento2/commit/8966f5f3a784085d53ee206b1492f708de672e55)
> * [204675e48423e7472761373cebab698787baffdc](https://github.com/magento/magento2/commit/204675e48423e7472761373cebab698787baffdc)
> 
> The fix will be available with the upcoming 2.3.2 release.

Ah wow! So you're not doing away with the web setup wizard? I thought this was being scraped from Magento.

**Comment by jos-zz** [comment] 2019-04-17 11:11
Hello,
Thanks for the update.
Does this fix the Web Setup for instances running with apache too?
Is it possible to apply this fix manually on a CE 2.2.6 instance?
Which files should be replaced?
Is this the correct one to replace
*/vendor/magento/framework/App/DocRootLocator.php* ?
Anything else I should be aware of?

**Comment by magento-engcom-team** [comment] 2019-04-20 16:25
Hi @dharake. Thank you for your report. 
The issue has been fixed in magento/magento2#22369 by @JeroenVanLeusden in 2.2-develop branch
Related commit(s):
 - [10de6de532aea6ca7a7b58334387f126e151dee2](https://github.com/magento/magento2/commit/10de6de532aea6ca7a7b58334387f126e151dee2)
 - [40b5d2e2493f5ad8943203e7af920d703c47d499](https://github.com/magento/magento2/commit/40b5d2e2493f5ad8943203e7af920d703c47d499)

The fix will be available with the upcoming 2.2.9 release.
