### ISSUE TITLE
Quote_item keeping applied_rule_ids even when those rules are removed

### ISSUE THREAD

**Issue by jajajaime** [magento/magento2#37191] opened 2023-03-10 22:23 UTC
### Preconditions and environment

- Magento version: 2.4.5-p1 and below
- Anything else that would help a developer reproduce the bug: Install sample data

### Steps to reproduce

1. Navigate to storefront and add an item to cart
2. Go to cart page and add a coupon code, like CouponCode0 from the sample data
3. Cancel the coupon code

### Expected result

The coupon code and applied_rule_id is removed from the quote and the quote_item record

### Actual result

The rule_id remains in the quote_item record

### Additional information

If another code is added and cancelled, the quote_item record will display both rules separated by a comma.

This affects third party extensions that attempt to list coupons or rules applied to each item.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-03-13 13:19
Hi @jajajaime,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Navigate to storefront and add an item to cart
- Go to cart page and add a coupon code, like CouponCode0 from the sample data
- Cancel the coupon code

After cancelling the coupon code and applied_rule_id is removed from the quote and the quote_item record.We are getting `NULL`

<img width="1395" alt="Screenshot 2023-03-13 at 12 42 49 PM" src="https://user-images.githubusercontent.com/51680745/224683577-534304a3-7305-4eae-9d26-e76e544d0b81.png">



<img width="559" alt="Screenshot 2023-03-13 at 4 07 17 PM" src="https://user-images.githubusercontent.com/51680745/224683641-bb1efbf2-5c3a-4604-862e-959ddd2d2e78.png">



<img width="910" alt="Screenshot 2023-03-13 at 12 43 01 PM" src="https://user-images.githubusercontent.com/51680745/224683692-6c4afac6-b436-4397-bff6-a24fa8c5e7c9.png">




Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.
it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-03-24 06:02
Hi @jajajaime,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.


Thanks.

**Closed as completed by engcom-Bravo** 2023-03-24 06:02 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1

**Comment by sanutryzens** [comment] 2023-05-19 10:08
Hi @jajajaime 

did this issue resolved for you. We are experiencing the same issue with 2.4.5-p2 version.

Thanks
Sanu
