### ISSUE TITLE
Warning message when we click to view product from emailer

### ISSUE THREAD

**Issue by Devanshi-pachouli** [magento/magento2#4018] opened 2016-04-05 14:35 UTC
## Steps to reproduce
1. Go and check and product
2. Add product to MyWishlist
3. Share the wishlist to any email id
4. Go to the inbox and check the email, click the image, prduct name link or view product link.

Expected result
1. The expected product should be displayed.
2. ...
## Actual result
1. It is giving Warning message.(Warning: Illegal offset type in isset or empty in /home2/kidsafet/public_html/vendor/magento/module-store/Model/StoreRepository.php on line 54)
2. Please find the attachment.
   ![image](https://cloud.githubusercontent.com/assets/18288575/14285542/99bd6b50-fb69-11e5-982e-d239c0ed671b.png)

**Comment by moe-kayali** [comment] 2016-04-06 09:08
Hello,

I was able to reproduce the same issue on Magento 2.0.4. 
How Reproducible: Always.

Thanks,

**Comment by moe-kayali** [comment] 2016-04-06 14:24
It seems that the issue is related to store view. 

If you have the default store view **ONLY**, then the error won't be found and you will be redirected to the product page view, and it works fine.

But, if you add a new store view whether it's enabled or disabled, the issue will appear and the error will be found. 

Hope this will make it easier for you guys to find out what is going on. 

Thanks,

**Comment by sevos1984** [comment] 2016-04-07 14:03
I've got the same error when storeview is disabled. Internal ticket MAGETWO-51679

**Comment by slavvka** [comment] 2016-05-18 10:30
@Devanshi-pachouli, the fix has been delivered to mainline. Please see 5c93580f892c7f7a4032ac03e6d5e9a69f01390f. Thank you for your contribution!

**Closed as completed by slavvka** 2016-05-18 10:30 UTC
Labels: Issue: Ready for Work, bug report
