### ISSUE TITLE
Declarative schema issue: setup:upgrade breaks when a JSON column is created in MySQL

### ISSUE THREAD

**Issue by paales** [magento/magento2#18451] opened 2018-10-08 08:13 UTC
### Preconditions

1. Magento 2.3-beta8

### Steps to reproduce

1. Create a table in the database with a JSON column (so I'm not trying to create a JSON column via the declarative schema)

```MySQL
CREATE TABLE `transfer_orders` (
  `no` bigint(20) NOT NULL AUTO_INCREMENT,
  `event_id` char(36) COLLATE utf8_bin NOT NULL,
  `event_name` varchar(100) COLLATE utf8_bin NOT NULL,
  `payload` json NOT NULL,
  `metadata` json NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `aggregate_version` int(11) unsigned GENERATED ALWAYS AS (json_extract(`metadata`,'$._aggregate_version')) STORED NOT NULL,
  `aggregate_id` char(36) COLLATE utf8_bin GENERATED ALWAYS AS (json_unquote(json_extract(`metadata`,'$._aggregate_id'))) STORED NOT NULL,
  `aggregate_type` varchar(150) COLLATE utf8_bin GENERATED ALWAYS AS (json_unquote(json_extract(`metadata`,'$._aggregate_type'))) STORED NOT NULL,
  PRIMARY KEY (`no`),
  UNIQUE KEY `ix_event_id` (`event_id`),
  UNIQUE KEY `ix_unique_event` (`aggregate_type`,`aggregate_id`,`aggregate_version`),
  KEY `ix_query_aggregate` (`aggregate_type`,`aggregate_id`,`no`)
) ENGINE=InnoDB AUTO_INCREMENT=46 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```

2. Run `bin/magento setup:upgrade`

### Expected result
1. Setup upgrade should just continue

### Actual result

```
Exception: Starting Magento installation:
File permissions check...
[Progress: 1 / 1197]
Required extensions check...
[Progress: 2 / 1197]
Enabling Maintenance Mode...
[Progress: 3 / 1197]
Installing deployment configuration...
[Progress: 4 / 1197]
Installing database schema:
Schema creation/updates:

In DefinitionAggregator.php line 57:

  [InvalidArgumentException]
  Cannot process definition to array for type json


Exception trace:
 Magento\Framework\Setup\Declaration\Schema\Db\DefinitionAggregator->fromDefinition() at /data/web/magento2/vendor/magento/framework/Setup/Declaration/Schema/Db/MySQL/DbSchemaReader.php:110
 Magento\Framework\Setup\Declaration\Schema\Db\MySQL\DbSchemaReader->readColumns() at /data/web/magento2/vendor/magento/framework/Setup/Declaration/Schema/Db/SchemaBuilder.php:79
 Magento\Framework\Setup\Declaration\Schema\Db\SchemaBuilder->build() at /data/web/magento2/vendor/magento/framework/Setup/Declaration/Schema/SchemaConfig.php:66
 Magento\Framework\Setup\Declaration\Schema\SchemaConfig->getDbConfig() at /data/web/magento2/setup/src/Magento/Setup/Model/DeclarationInstaller.php:58
 Magento\Setup\Model\DeclarationInstaller->installSchema() at /data/web/magento2/setup/src/Magento/Setup/Model/Installer.php:806
 Magento\Setup\Model\Installer->declarativeInstallSchema() at /data/web/magento2/setup/src/Magento/Setup/Model/Installer.php:828
 Magento\Setup\Model\Installer->installSchema() at n/a:n/a
 call_user_func_array() at /data/web/magento2/setup/src/Magento/Setup/Model/Installer.php:365
 Magento\Setup\Model\Installer->install() at /data/web/magento2/setup/src/Magento/Setup/Console/Command/InstallCommand.php:219
 Magento\Setup\Console\Command\InstallCommand->execute() at /data/web/magento2/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /data/web/magento2/vendor/symfony/console/Application.php:886
 Symfony\Component\Console\Application->doRunCommand() at /data/web/magento2/vendor/symfony/console/Application.php:262
 Symfony\Component\Console\Application->doRun() at /data/web/magento2/vendor/magento/framework/Console/Cli.php:102
 Magento\Framework\Console\Cli->doRun() at /data/web/magento2/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /data/web/magento2/bin/magento:23

setup:install [--backend-frontname BACKEND-FRONTNAME] [--amqp-host AMQP-HOST] [--amqp-port AMQP-PORT] [--amqp-user AMQP-USER] [--amqp-password AMQP-PASSWORD] [--amqp-virtualhost AMQP-VIRTUALHOST] [--amqp-ssl AMQP-SSL] [--amqp-ssl-options AMQP-SSL-OPTIONS] [--key KEY] [--db-host DB-HOST] [--db-name DB-NAME] [--db-user DB-USER] [--db-engine DB-ENGINE] [--db-password DB-PASSWORD] [--db-prefix DB-PREFIX] [--db-model DB-MODEL] [--db-init-statements DB-INIT-STATEMENTS] [-s|--skip-db-validation] [--http-cache-hosts HTTP-CACHE-HOSTS] [--session-save SESSION-SAVE] [--session-save-redis-host SESSION-SAVE-REDIS-HOST] [--session-save-redis-port SESSION-SAVE-REDIS-PORT] [--session-save-redis-password SESSION-SAVE-REDIS-PASSWORD] [--session-save-redis-timeout SESSION-SAVE-REDIS-TIMEOUT] [--session-save-redis-persistent-id SESSION-SAVE-REDIS-PERSISTENT-ID] [--session-save-redis-db SESSION-SAVE-REDIS-DB] [--session-save-redis-compression-threshold SESSION-SAVE-REDIS-COMPRESSION-THRESHOLD] [--session-save-redis-compression-lib SESSION-SAVE-REDIS-COMPRESSION-LIB] [--session-save-redis-log-level SESSION-SAVE-REDIS-LOG-LEVEL] [--session-save-redis-max-concurrency SESSION-SAVE-REDIS-MAX-CONCURRENCY] [--session-save-redis-break-after-frontend SESSION-SAVE-REDIS-BREAK-AFTER-FRONTEND] [--session-save-redis-break-after-adminhtml SESSION-SAVE-REDIS-BREAK-AFTER-ADMINHTML] [--session-save-redis-first-lifetime SESSION-SAVE-REDIS-FIRST-LIFETIME] [--session-save-redis-bot-first-lifetime SESSION-SAVE-REDIS-BOT-FIRST-LIFETIME] [--session-save-redis-bot-lifetime SESSION-SAVE-REDIS-BOT-LIFETIME] [--session-save-redis-disable-locking SESSION-SAVE-REDIS-DISABLE-LOCKING] [--session-save-redis-min-lifetime SESSION-SAVE-REDIS-MIN-LIFETIME] [--session-save-redis-max-lifetime SESSION-SAVE-REDIS-MAX-LIFETIME] [--session-save-redis-sentinel-master SESSION-SAVE-REDIS-SENTINEL-MASTER] [--session-save-redis-sentinel-servers SESSION-SAVE-REDIS-SENTINEL-SERVERS] [--session-save-redis-sentinel-verify-master SESSION-SAVE-REDIS-SENTINEL-VERIFY-MASTER] [--session-save-redis-sentinel-connect-retires SESSION-SAVE-REDIS-SENTINEL-CONNECT-RETIRES] [--cache-backend CACHE-BACKEND] [--cache-backend-redis-server CACHE-BACKEND-REDIS-SERVER] [--cache-backend-redis-db CACHE-BACKEND-REDIS-DB] [--cache-backend-redis-port CACHE-BACKEND-REDIS-PORT] [--cache-backend-redis-password CACHE-BACKEND-REDIS-PASSWORD] [--page-cache PAGE-CACHE] [--page-cache-redis-server PAGE-CACHE-REDIS-SERVER] [--page-cache-redis-db PAGE-CACHE-REDIS-DB] [--page-cache-redis-port PAGE-CACHE-REDIS-PORT] [--page-cache-redis-compress-data PAGE-CACHE-REDIS-COMPRESS-DATA] [--page-cache-redis-password PAGE-CACHE-REDIS-PASSWORD] [--base-url BASE-URL] [--language LANGUAGE] [--timezone TIMEZONE] [--currency CURRENCY] [--use-rewrites USE-REWRITES] [--use-secure USE-SECURE] [--base-url-secure BASE-URL-SECURE] [--use-secure-admin USE-SECURE-ADMIN] [--admin-use-security-key ADMIN-USE-SECURITY-KEY] [--admin-user ADMIN-USER] [--admin-password ADMIN-PASSWORD] [--admin-email ADMIN-EMAIL] [--admin-firstname ADMIN-FIRSTNAME] [--admin-lastname ADMIN-LASTNAME] [--cleanup-database] [--sales-order-increment-prefix SALES-ORDER-INCREMENT-PREFIX] [--use-sample-data] [--enable-modules [ENABLE-MODULES]] [--disable-modules [DISABLE-MODULES]] [--convert-old-scripts [CONVERT-OLD-SCRIPTS]] [-i|--interactive] [--safe-mode [SAFE-MODE]] [--data-restore [DATA-RESTORE]] [--dry-run [DRY-RUN]] [--magento-init-params MAGENTO-INIT-PARAMS]
 in /data/web/magento2/vendor/magento/framework/Shell.php:63
Stack trace:
#0 /data/web/magento2/dev/tests/integration/framework/Magento/TestFramework/Application.php(514): Magento\Framework\Shell->execute('/usr/bin/php7.1...', Array)
#1 /data/web/magento2/dev/tests/integration/framework/bootstrap.php(81): Magento\TestFramework\Application->install(false)
#2 /data/web/magento2/vendor/phpunit/phpunit/src/Util/Fileloader.php(61): include_once('/data/web/magen...')
#3 /data/web/magento2/vendor/phpunit/phpunit/src/Util/Fileloader.php(45): PHPUnit\Util\Fileloader::load('/data/web/magen...')
#4 /data/web/magento2/vendor/phpunit/phpunit/src/TextUI/Command.php(915): PHPUnit\Util\Fileloader::checkAndLoad('/data/web/magen...')
#5 /data/web/magento2/vendor/phpunit/phpunit/src/TextUI/Command.php(737): PHPUnit\TextUI\Command->handleBootstrap('/data/web/magen...')
#6 /data/web/magento2/vendor/phpunit/phpunit/src/TextUI/Command.php(152): PHPUnit\TextUI\Command->handleArguments(Array)
#7 /data/web/magento2/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#8 /data/web/magento2/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#9 {main}

Next Magento\Framework\Exception\LocalizedException: Command returned non-zero exit code:
`/usr/bin/php7.1 -f '/data/web/magento2/bin/magento' setup:install -vvv --db-host='odo.box' --db-user='app' --db-password='mStcuG2HvfzYTrXCGnjHKI9NoNmzuoZa' --db-name='magento_integration_tests' --backend-frontname='backend' --admin-user='user' --admin-password='password1' --admin-email='admin@example.com' --admin-firstname='firstname' --admin-lastname='lastname' --magento-init-params='MAGE_DIRS[etc][path]=/data/web/magento2/dev/tests/integration/tmp/sandbox-0-6510e5a049ca19cfc9a538b0c75964d4/etc&MAGE_DIRS[var][path]=/data/web/magento2/dev/tests/integration/tmp/sandbox-0-6510e5a049ca19cfc9a538b0c75964d4/var&MAGE_DIRS[media][path]=/data/web/magento2/dev/tests/integration/tmp/sandbox-0-6510e5a049ca19cfc9a538b0c75964d4/pub/media&MAGE_DIRS[static][path]=/data/web/magento2/dev/tests/integration/tmp/sandbox-0-6510e5a049ca19cfc9a538b0c75964d4/pub/static&MAGE_DIRS[view_preprocessed][path]=/data/web/magento2/dev/tests/integration/tmp/sandbox-0-6510e5a049ca19cfc9a538b0c75964d4/var/view_preprocessed/pub/static&MAGE_DIRS[code][path]=/data/web/magento2/dev/tests/integration/tmp/sandbox-0-6510e5a049ca19cfc9a538b0c75964d4/generated/code&MAGE_DIRS[cache][path]=/data/web/magento2/dev/tests/integration/tmp/sandbox-0-6510e5a049ca19cfc9a538b0c75964d4/var/cache&MAGE_DIRS[log][path]=/data/web/magento2/dev/tests/integration/tmp/sandbox-0-6510e5a049ca19cfc9a538b0c75964d4/var/log&MAGE_DIRS[session][path]=/data/web/magento2/dev/tests/integration/tmp/sandbox-0-6510e5a049ca19cfc9a538b0c75964d4/var/session&MAGE_DIRS[tmp][path]=/data/web/magento2/dev/tests/integration/tmp/sandbox-0-6510e5a049ca19cfc9a538b0c75964d4/var/tmp&MAGE_DIRS[upload][path]=/data/web/magento2/dev/tests/integration/tmp/sandbox-0-6510e5a049ca19cfc9a538b0c75964d4/var/upload&MAGE_DIRS[pub][path]=/data/web/magento2/dev/tests/integration/tmp/sandbox-0-6510e5a049ca19cfc9a538b0c75964d4/pub&MAGE_MODE=developer' 2>&1` in /data/web/magento2/vendor/magento/framework/Shell.php:64
Stack trace:
#0 /data/web/magento2/dev/tests/integration/framework/Magento/TestFramework/Application.php(514): Magento\Framework\Shell->execute('/usr/bin/php7.1...', Array)
#1 /data/web/magento2/dev/tests/integration/framework/bootstrap.php(81): Magento\TestFramework\Application->install(false)
#2 /data/web/magento2/vendor/phpunit/phpunit/src/Util/Fileloader.php(61): include_once('/data/web/magen...')
#3 /data/web/magento2/vendor/phpunit/phpunit/src/Util/Fileloader.php(45): PHPUnit\Util\Fileloader::load('/data/web/magen...')
#4 /data/web/magento2/vendor/phpunit/phpunit/src/TextUI/Command.php(915): PHPUnit\Util\Fileloader::checkAndLoad('/data/web/magen...')
#5 /data/web/magento2/vendor/phpunit/phpunit/src/TextUI/Command.php(737): PHPUnit\TextUI\Command->handleBootstrap('/data/web/magen...')
#6 /data/web/magento2/vendor/phpunit/phpunit/src/TextUI/Command.php(152): PHPUnit\TextUI\Command->handleArguments(Array)
#7 /data/web/magento2/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#8 /data/web/magento2/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#9 {main}

=== Memory Usage System Stats ===
Memory usage (OS):	39.18M (652.93% of 6.00M reported by PHP)
Estimated memory leak:	33.18M (84.68% of used memory)
```

**Comment by magento-engcom-team** [comment] 2018-10-08 08:13
Hi @paales. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@paales do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by paales** [comment] 2018-10-09 18:53
The query i'm trying to add is also adding a `char`, has the same issue as the `json` column

**Comment by magento-engcom-team** [comment] 2018-11-13 08:34
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2018-11-28 12:00
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96709` were created

**Comment by misha-kotov** [comment] 2018-11-30 17:36
We will look to add support for these column types in the future

**Closed as completed by misha-kotov** 2018-11-30 17:36 UTC
Labels: Issue: Ready for Work, feature request, Component: Setup, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.2.x, Issue: Format is valid

**Comment by mpchadwick** [comment] 2019-04-12 20:53
`TIME` columns also seem to not be supported.

**Comment by evs-xsarus** [comment] 2019-12-02 09:02
Possible fix for JSON see https://github.com/magento/magento2/pull/25479
