### ISSUE TITLE
Cart Price Rule wrongfully applies to cheap products with big quantities

### ISSUE THREAD

**Issue by gondas33** [magento/magento2#29343] opened 2020-07-31 09:51 UTC
### Preconditions (*)

1. Magento 2.3.5
2. Redis, elasticsearch, litespeed

### Steps to reproduce (*)

1. Create a cart price rule with the following settings:
![image](https://user-images.githubusercontent.com/11984860/89023078-ad229280-d32b-11ea-8f7f-c07a5fe7207a.png)

2. Create a product with price 5 and add to cart 200 qty.

3. See Discount value( should be the fixed amount - 20 in my case)

### Expected result (*)

1.  Have a fixed discount of 20 .

### Actual result (*)

1. Discount is 4.20 and applies directly on the products
2.  
![image](https://user-images.githubusercontent.com/11984860/89023471-4baef380-d32c-11ea-9a65-9370d1ab602f.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by an4rei** [comment] 2020-07-31 09:51
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-07-31 09:51
Hi @an4rei. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-07-31 09:53
Hi @an4rei, here is your [Magento instance](https://i-29343-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29343-2-4-develop.instances.magento-community.engineering/admin_656f](https://i-29343-2-4-develop.instances.magento-community.engineering/admin_656f)
Login: `2ced26c4` Password: `30a67cc05c9f`
Instance will be terminated in up to 3 hours.

**Comment by an4rei** [comment] 2020-07-31 09:58
Apparently it's due to "Maximum Qty Discout is Applied to" being set to 1. Leaving it empty fixes the issue.  Not sure whether this is intended or not as I'm not really understanding the use of that specific setting.

**Comment by engcom-Oscar** [comment] 2020-09-22 09:34
Hi @an4rei !
Thank you for your contribution.
 I'm closing this ticket as not a bug, because described issue according documentation is a expected behavior for Cart price rule according https://docs.magento.com/user-guide/marketing/price-rules-cart-create.html: 
_In the Maximum Qty Discount is Applied To field, enter the maximum quantity of the same product that can qualify for the discount in the same purchase._

**Closed as completed by engcom-Oscar** 2020-09-22 09:34 UTC
Labels: Issue: Format is valid, Progress: done, Reported on 2.3.5
