### ISSUE TITLE
Move Out of Stock to Last

### ISSUE THREAD

**Issue by ia-gaurav** [magento/magento2#33022] opened 2021-05-15 07:41 UTC
**Preconditions (*)**

- 1. Magento Version - 2.4.2
- 2. Default Magento Theme

**Steps to reproduce (*)**
- Set **Display Out of Stock Products** to yes
- Make Product Out Of Stock

**Expected result (*)**
- Product should be moved to bottom as it bad for sales if top product are out of stock

**Actual result (*)**

-  Products keeps on showing at old positions

**Screenshot Below -** 

![image](https://user-images.githubusercontent.com/63009790/118358360-0cd8ea00-b59c-11eb-9c2a-8944941a04b5.png)

**Comment by ia-gaurav** [comment] 2021-05-15 10:53
@magento give me 2.4-develop instance

**Comment by ia-gaurav** [comment] 2021-05-15 11:11
Issue can be checked on - https://eb5987fede11e3a5f6e2a1a98f399c92-2-4-develop.instances.magento-community.engineering/women/tops-women/hoodies-and-sweatshirts-women.html

**Comment by ia-gaurav** [comment] 2021-05-20 07:42
@magento give me 2.4.1-develop instance

**Comment by dthomas** [comment] 2021-11-19 02:08
@magento give me 2.4-develop instance

**Comment by dthomas** [comment] 2021-11-19 02:23
I'm unable to reproduce the issue. The out of stock item moves to the end of product list properly.

**Comment by engcom-Bravo** [comment] 2024-08-22 09:34
Hi @ia-gaurav,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="1436" alt="Screenshot 2024-08-22 at 15 02 23" src="https://github.com/user-attachments/assets/03e2cd34-b0bf-4f38-8f72-f8fad7192694">



Out of Stock moved to the end.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-08-22 09:34 UTC
Labels: feature request, Progress: done
