### ISSUE TITLE
Leaving empty field in Product Fields Auto-Generation breaks Add Product in admin 

### ISSUE THREAD

**Issue by dakzilla** [magento/magento2#9467] opened 2017-05-01 21:58 UTC
### Preconditions

1. Magento EE 2.1.5 is installed (CE should have the same issue) with PHP 7.0 and MariaDB 15.1

### Steps to reproduce

1. Go to Stores > Settings > Configuration > Catalog > Product Fields Auto-Generation (Default Config)
2. Next to _Mask for Meta Description,_ uncheck _Use system value_
3. Empty the contents of the _Mask for Meta Description_ field and save the config
4. Go to Products > Inventory > Catalog
5. Click on Add Product

### Expected result

1. The Product creation form should load as normal

### Actual result

1. The product form doesn't finish loading. The spinner never goes away and an error can be seen in the browser console. 
![screenshot from 2017-05-01 17-56-08](https://cloud.githubusercontent.com/assets/7482901/25596516/7ecb6a06-2e97-11e7-992f-c89e03d3dd0a.png)

**Comment by magento-engcom-team** [comment] 2017-10-02 11:30
@dakzilla, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-02 11:30 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
