### ISSUE TITLE
2.2.6 Cart page validation errors.

### ISSUE THREAD

**Issue by BezV8** [magento/magento2#18340] opened 2018-10-02 12:43 UTC
/checkout/cart/ on 2.2.6 has a few errors and warnings when run through the W3C html validator.

### Preconditions

1. Magento 2.2.6
2. Blank or Luma Theme.

### Steps to reproduce

1. Add product to basket.
2. View basket.
3. Validate page source on W3C html validator.

### Expected result

1. No errors.

### Actual result

1. .item-actions first td has a colspan of 100 which causes a warning and error.
2. Shopping Cart Items caption has some invalid attributes.
![screenshot_2018-10-02 showing results for contents of text-input area - nu html checker](https://user-images.githubusercontent.com/33320744/46349116-10b4d980-c649-11e8-9824-b8a9fef06b52.png)

**Comment by magento-engcom-team** [comment] 2018-10-02 12:43
Hi @BezV8. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@BezV8 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by BezV8** [comment] 2018-10-02 12:46
@magento-engcom-team Issue confirmed on vanilla instance.

**Comment by magento-engcom-team** [comment] 2018-11-12 13:17
Hi @TomashKhamlai. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by TomashKhamlai** [comment] 2018-11-12 13:19
@magento-engcom-team give me $VERSION instance

**Comment by TomashKhamlai** [comment] 2018-11-12 13:20
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2018-11-12 13:20
Hi @TomashKhamlai. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2018-11-12 13:20
Hi @TomashKhamlai, here is your [Magento instance](http://34.228.235.121/i-18340-2-3-develop/).
Admin access: [http://34.228.235.121/i-18340-2-3-develop//admin](http://34.228.235.121/i-18340-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by TomashKhamlai** [comment] 2018-11-12 13:32
[Html Checker 2.3-develop.pdf](https://github.com/magento/magento2/files/2572060/Html.Checker.2.3-develop.pdf)

**Closed as completed** 2018-11-12 13:33 UTC
Labels: Component: Checkout, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid
