### ISSUE TITLE
Can't add product attribute programatically to General group

### ISSUE THREAD

**Issue by redboxmarcins** [magento/magento2#4937] opened 2016-06-09 10:15 UTC
## Steps to reproduce
1. Install Magento 2.0.7 or earlier
2. Create attribute group called 'General' (as it is in Magento 1.x)
3. Try to add any product attribute programatically to 'General' group
## Expected result
1. Attribute should be added to every attribute set into 'General' group
## Actual result
1. Exception message that 'General-73'  key already exists

So what actually happens is - magento is renaming 'Product Details' group to 'General' causing duplicate
In the code I found that https://github.com/magento/magento2/blob/develop/app/code/Magento/Eav/Setup/EavSetup.php#L62 indicates that 'general' should be default product group, which is not true as it is 'Product Details'

Also what I don't understand is why even if the group is there - magento is still trying to create it?

**Comment by cpartica** [comment] 2016-06-21 00:52
as I see each attribute group has different attribute sets, so what attribute set are you using?
I also see 3 groups called general, they all are the default id for that attribute set
That means that an attribute set can have only one attribute id, Magento/Eav/Setup/EavSetup.php doesn't necessarily refer to product

**Comment by redboxmarcins** [comment] 2016-06-21 06:20
@cpartica I think you are missing the point here.
The problem is that EavSetup.php class implies that Product default Group will be called "General" where is Magento 2 it is called "Product Details"

Please follow my steps carefully

**Comment by magento-engcom-team** [comment] 2017-11-27 09:30
@redboxmarcins, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.10

**Closed as completed by magento-engcom-team** 2017-11-27 09:30 UTC
Labels: bug report, Component: Eav, Issue: Clear Description, Issue: Confirmed, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid
