### ISSUE TITLE
Inventory Indexer | Configurable product is Out of Stock but should be In Stock

### ISSUE THREAD

**Issue by VladyslavSikailo** [magento/magento2#36421] opened 2022-11-04 13:33 UTC
### Preconditions and environment

`magento/product-enterprise-edition:2.4.4`

### Steps to reproduce

1. Create 2 websites, for example, `website1` and `website2`
2. Create stores and storeviews for created websites
3. Create Inventory Source like `source1`
4. Create Inventory Stock like `stock1`, and assign created source to created stock and to `website2`
5. Create configurable product with one simple
    - Configurable: In Stock, price > 0, enabled
    - Simple: in stock, price > 0, enabled
    - Assign simple to both default and `source1`, set 11111 qty, in_stock = true
6. Go to Configurable PDP and see that it's in stock
7. Make Configurable Out of Stock
8. See it's Out of Stock on PDP
9. Update Configurable Stock Status using REST API
    - create integration token
    - run the following request
```
https://{magento_url}/rest/{second_storeview_code}/V1/products/{configurable_sku}/stockItems/{configurable_stock_item_id}

{
"stock_item": {
"item_id": 5,
"product_id": 5,
"qty": 11111,
"stock_id": 1,
"is_in_stock": true
}
}

Reindex and clear cache
Verify Front end  - Product details page
No issue for 2nd store.
Run the api request for main website store as well
Reindex and clear cache
```
You can find `configurable_stock_item_id` in `cataloginventory_stock_item` table, search by `product_id`
10. Go to admin and see that Configurable is In Stock now
11. Go to PDP and see that Configurable still Out of Stock on main website

### Expected result

Configurable product should become In Stock on Frontend for both the websites

### Actual result

Configurable product still Out of Stock on Frontend for main website. There is no issue for 2nd store

### Additional information

It works when we update Configurable Stock using Admin.

It happens because it triggers Source item saving for Children products, and the Inventory module has a plugin to reindex data in `inventory_stock_N` table
see `\Magento\InventoryIndexer\Plugin\InventoryApi\ReindexAfterSourceItemsSavePlugin::afterExecute`

But when we run this request from API - the plugin is not triggered.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by alikhani97** [comment] 2022-11-05 07:05
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-11-11 06:30
@magento give me 2.4-develop instance

**Comment by paulhaidon** [comment] 2022-11-11 14:02
We have had similar in that we are experiencing issues since upgrading from 2.4.4 to 2.4.5-p1 but we don't have to update it via API for it to fail - we are just updating it via the backend.

When a configurable product's "simple product" variation goes out of stock, it is being set to out of stock on the frontend but when we add stock to the simple product again, the frontend still doesn't think it is in stock. 

Side note regarding odd behaviour: 
If the attributes are set to dropdown menus, they grey out the out of stock product as expected. But if you are using image or text swatches, they do not grey out at all which means users can select them and then "add to cart" which then triggers - "This product is out of stock" which isn't overly great from a UX perspective. 

I was in the middle of creating my own issue for this when I noticed others are having issues with stock related updates.

**Comment by engcom-November** [comment] 2022-11-16 04:07
Hi @VladyslavSikailo ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4 enterprise edition with inventory enabled and the issue is not reproducible on 2nd store but is reproducible on 1st store with below steps performed.
1. Configurable product assigned to both the stores and both stocks
2. Rest API PUT request to update stock with below payload. Note: stock id is mandatory to be given in the payload to update the stock
_{ 
  "stock_item": {
    "item_id": 5,
    "product_id": 5,
    "qty": 11111,
    "stock_id": 2,
    "is_in_stock": true
  }
}_
3. Reindex and clear cache
Product displayed as expected in 2nd store with in stock
![image](https://user-images.githubusercontent.com/60198231/202081100-b2f8fc68-e78d-4cdd-91d5-2c1a7860aa54.png)

On updating the stock for main website (default store) - Product is still out of stock and not displayed on front end default store. Hence confirming this issue.
![image](https://user-images.githubusercontent.com/60198231/202081010-f64cee6c-1ae2-4213-9d24-49e7720e19a9.png)

**Comment by davirs** [comment] 2023-01-13 14:17
I have the same problem here with magento version 2.4.4 with php 8.1. 
The products work correctly and randomly some entire product category or specific products are simply marked in the display as "out of stock". Both configurable products and simple products are correct and in stock, it is only in the frontend display that has this bug.

Here I also have the problem that was commented above, when the product is sold and has zero saleable quantity it keeps appearing in the frontend as if it was in stock...

Really are 2 extremely serious bugs because they disturb sales and generate numerous complaints daily.

**If anyone has an alternative solution I would be very grateful!**

**Comment by realadityayadav** [comment] 2023-06-01 09:28
@engcom-November Can you please send us a PR or commit link for this?

**Closed as completed** 2023-09-03 15:03 UTC
Labels: Issue: Confirmed, Component: ConfigurableProduct, Component: Api, Reproduced on 2.4.x, Priority: P1, Progress: done, Area: Product, Reported on 2.4.4, Adobe Commerce

**Comment by engcom-Bravo** [comment] 2023-09-04 07:04
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-7023 by the internal team
Related commits: https://github.com/magento-commerce/inventory/commit/2ca3fcbfaaa34212a6053c436e6baa6ccae241e5

Based on the Jira ticket, the target version is 2.4.7-beta2.

Thanks

**Comment by VladyslavSikailo** [comment] 2023-09-04 08:19
Hey @engcom-Bravo ,

As the community has no access to magento-commerce repo, could you please share the patch with the fix?

**Comment by engcom-Bravo** [comment] 2023-09-05 06:38
Hi @VladyslavSikailo,

Could you please check these commits :

https://github.com/search?q=repo%3Amagento%2Finventory+AC-7023&type=commits


Thanks.

**Comment by VladyslavSikailo** [comment] 2024-01-30 07:28
Hey @engcom-Bravo 

We have created the patch using the mentioned commits and applied it to our project. Unfortunatelly it does not work for us.
Do you have any ideas why? Are there some other commits that may be part of the fix?
Also, could you please tell in which Magento release these fixes supposed to be included?

Thanks
