### ISSUE TITLE
Configurable product PDP shows special price even though the special price is expired

### ISSUE THREAD

**Issue by toshz** [magento/magento2#10793] opened 2017-09-06 10:41 UTC
### Preconditions

1. Magento 2.1.7 CE with sample-data downloaded from official site
2. PHP Version 7.0.22
3. MySQL 5.7.19
4. FireFox 55.0.2
5. Apache/2.4.25 (Ubuntu)
6. Ubuntu 17.04 64bit

### Steps to reproduce

1. Install Magento 2.1.7 CE with sample data
2. Go to admin > Stores > Config > Catalog > Catalog > Enable flat catalog and flat category. Save.
3. Go to admin > Products > Catalog
4. Make sure **all caches are enabled**
5. Search for product with the name "Layla Tee"
6. Products grid should now show configurable product and associated child products
7. There should be 15 child products for this configurable
8. Open at least 6 (the more you edit, the more often the issue will be reproduced) of the child products, go to Advanced Pricing and set a special price, from date and to date. Make sure the **special price is lower than the regular price** and that the date interval is in the past. So basically **the special price should already be expired** when saved. Save each child product.
9. Reindex everything and clear cache.
10. Open the configurable product in front end (http://base_url/layla-tee.html)

If you want to cut straight to the chase I've uploaded my database which has already been configured as mentioned above. Just import and change base_url in core_config_data.
[magento_ce_2.1.7-sample-data.sql.gz](https://github.com/magento/magento2/files/1280773/magento_ce_2.1.7-sample-data.sql.gz)

### Expected result

1. Since all the special prices are already expired you should see the regular price $29.00.
![regular_price](https://user-images.githubusercontent.com/31688149/30103766-488a060e-92fc-11e7-96b0-6fe979b5d81c.png)

### Actual result

1. What I see on PDP is one of the special prices. If at first you don't see one of the special prices just flush cache and refresh. The more child products you have added a special price to, the more often one of the special prices will show up after a cache flush:
![special_price_01](https://user-images.githubusercontent.com/31688149/30104572-b2c59374-92fe-11e7-8793-1f847e89ab6b.png)
![special_price_01_admin](https://user-images.githubusercontent.com/31688149/30104617-d152a336-92fe-11e7-945e-caa133cb12a9.png)
![special_price_02](https://user-images.githubusercontent.com/31688149/30104629-d899a5a4-92fe-11e7-8287-fb69f465e7b5.png)
![special_price_02_admin](https://user-images.githubusercontent.com/31688149/30104662-f057655a-92fe-11e7-8ccf-8c3712da0e39.png)

**Comment by royvanos** [comment] 2017-09-07 08:37
We're having the same issue in Magento 2.1.8

**Comment by Linek** [comment] 2017-09-17 10:49
Cannot reproduce on 2.3.0-dev.
I added special price for even all simple products and set special date range in past. Then refreshing cache and check 30 times. Price is still correct

**Comment by maksek** [comment] 2017-09-17 12:01
@Linek - thank you for info. seems like the issue for 2.1-develop branch.

**Comment by magento-engcom-team** [comment] 2017-09-22 16:17
@toshz, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-22 16:17 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Fixed in 2.2.x, Issue: Format is valid
