### ISSUE TITLE
Catalog | Product | Weight is always zero when adding in grams ( 0.2 )

### ISSUE THREAD

**Issue by salehawal** [magento/magento2#28985] opened 2020-07-03 15:18 UTC
### Preconditions (*)

1. magento 2.3
2. ubuntu lamp php 7.2

### Steps to reproduce (*)

1. Edit Product 
2. change weight to 0.1

### Expected result (*)

1. weight to remain the entered value

### Actual result (*)

1. weight is changed to 0

**Comment by salehawal** [comment] 2020-07-03 15:23
yes i can confirm it is valid in booth production and development versions booth are magento 2.3

**Comment by swathishs** [comment] 2020-07-03 15:26
@salehawal : Okay we will be testing in both 2.3.5 p1 instance and 2.4 develop instances to check whether the issue is reproduced

**Comment by swathishs** [comment] 2020-07-03 15:29
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-07-03 15:29
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by salehawal** [comment] 2020-07-03 15:35
just tried to enter 1.2, it rounds it to 1

**Comment by gwharton** [comment] 2020-07-04 14:53
I can't reproduce this in either 2.3.5-p1 or 2.4-develop

**Comment by swathishs** [comment] 2020-07-07 08:27
@salehawal: Issue is not reproducible in Magento 2.3.5p1 

Please find the attachment below:
![image](https://user-images.githubusercontent.com/58288685/86748011-c8b2ba00-c059-11ea-89f4-b89835588ddb.png)

**Comment by swathishs** [comment] 2020-07-08 04:29
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-07-08 04:29
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by salehawal** [comment] 2020-07-10 12:09
well still the issue is present .. any idea where i should look for to fix it?

**Comment by gwharton** [comment] 2020-07-10 12:23
If you are a coder, then debug and step through the controller that is saving the value. If you aren't a coder, then perhaps you can setup a temporary copy of your website for testing purposes, and disable all third party modules and see if it then works. Re-enable them either one by one, or by group, until you find which module is stopping it from working. Do you have any modules installed that override functionality of product, or customise product in some way by adding functionality. Suspect a third party module overriding qty field and treating it as an int, and not a float.

**Comment by salehawal** [comment] 2020-07-11 04:36
ok i will try this approach .. thanks

**Comment by swathishs** [comment] 2020-07-13 04:34
Hi @salehawal, thank you for your report. I confirm that issue is not reproducible on the latest 2.4-develop branch and  Magento 2.3.5p1.
Hence closing the issue

**Closed as completed by swathishs** 2020-07-13 04:34 UTC
Labels: Issue: Format is valid, Progress: ready for QA, Reported on 2.3.x
