### ISSUE TITLE
Magento 2 bundle option delete issue.

### ISSUE THREAD

**Issue by Krishna-19-94** [magento/magento2#38280] opened 2023-12-13 14:01 UTC
I have created a bundle product with 10 options. When I attempted to delete options 1 through 9, it returned an error. However, when I tried to delete the 10th option, it worked fine.

1.  Magento version : 2.4.6-p3
2.  PHP version: 8.1

### Steps to reproduce (*)
1.  Create bundle product with multiple options.
2.  Tried with deleting in between option and then save product.

### Expected result (*)
1. Product option should be removed in between also.

### Actual result (*)
1. It's throwing error 
`Warning: Undefined array key "product_id" in vendor/magento/module-bundle/Controller/Adminhtml/Product/Initialization/Helper/Plugin/Bundle.php on line 222`

Thanks in advance.

**Comment by engcom-Bravo** [comment] 2023-12-14 06:21
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-12-14 06:41
Hi @Krishna-19-94,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

**Steps to reproduce (*)**

 
- Create bundle product with multiple options.
- Tried with deleting in between option and then save product.


[Screencast from 14-12-23 12:05:21 PM IST.webm](https://github.com/magento/magento2/assets/51680745/901373f7-fbb8-4e47-943c-cf80adcb811c)


We are able to delete the options in between and we are able to save the product.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-12-28 05:32
Hi @Krishna-19-94,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38280#issuecomment-1855236177 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-01-02 05:48
Hi @Krishna-19-94,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Bravo** 2024-01-02 05:48 UTC
Labels: Issue: needs update, Reported on 2.4.6-p3
