### ISSUE TITLE
Customer_account.xml file abused

### ISSUE THREAD

**Issue by LiamFielding** [magento/magento2#7816] opened 2016-12-15 11:47 UTC
From the Magento Paypal module, this is added in its customer_account.xml file:

    <head>
        <title>Billing Agreements</title>
    </head>

This is very unwise since the benefit of having the customer_account is that all the pages on there use it to update for the convenience of getting all of the dashboard links and updates.

After adding another page to the route, we now have to awkwardly remove what isn't even page.main.title.

I consider this an issue, I hope others feel the same way.

**Comment by veloraven** [comment] 2016-12-20 09:04
@LiamFielding thank you for your feedback.
Please format description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result if you think it to be an issue. Please, also identify which version of Magento you are running.
You can also submit it to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)) as it rather looks like an improvement.

**Comment by veloraven** [comment] 2017-01-03 12:50
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by PieterCappelle** [comment] 2017-10-26 13:02
@veloraven Can you please reopen this issue and assign it to me. The issue is indeed not correct formated but it is an issue. I'll fix it.

**Comment by orlangur** [comment] 2017-10-26 15:12
@PieterCappelle leaving it Unassigned + `needs update`, I believe somebody else is adding some OCTOBERFEST labels and assign to contributors.

**Comment by magento-engcom-team** [comment] 2017-12-04 16:30
@LiamFielding, thank you for your report.
We've created internal ticket(s) MAGETWO-84985 to track progress on the issue.

**Comment by PieterCappelle** [comment] 2017-12-21 19:33
Created PR for 2.3-develop branch. If accepted I'll create backport for 2.2-develop & 2.1-develop branch.

**Comment by magento-team** [comment] 2018-01-09 00:50
Hi @LiamFielding. Thank you for your report. 
The issue has been fixed in magento/magento2#12852 by @PieterCappelle in 2.3-develop branch
Related commit(s):
 - 36cac170cf32657bfd84214dde9fbfefc1e38e73

The fix will be available with the upcoming patch release.

**Comment by mikewhitby** [comment] 2018-03-24 10:27
I'm working on the backport #distributed-cd

**Comment by magento-engcom-team** [comment] 2018-03-24 10:28
@mikewhitby thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment] 2018-03-28 06:42
Hi @LiamFielding. Thank you for your report. 
The issue has been fixed in magento/magento2#14325 by @mikewhitby in 2.2-develop branch
Related commit(s):
 - [56b35987e1162332cad1e4341c12fd52c8549998](https://github.com/magento/magento2/commit/56b35987e1162332cad1e4341c12fd52c8549998)
 - [09f80593d51b3e8c264bfe9b15437f91f25b1c0a](https://github.com/magento/magento2/commit/09f80593d51b3e8c264bfe9b15437f91f25b1c0a)

The fix will be available with the upcoming 2.2.5 release.

**Closed as completed by magento-engcom-team** 2018-03-28 06:42 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid, Event: distributed-cd

**Comment by sidolov** [comment] 2018-03-30 07:28
Hi @LiamFielding. Thank you for your report. 
The issue has been fixed in magento/magento2#14322 by @mikewhitby in 2.3-develop branch
Related commit(s):
 - [caf5b3e7495ce9dcfac9a83e2be8787323dd684a](https://github.com/magento/magento2/commit/caf5b3e7495ce9dcfac9a83e2be8787323dd684a)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment] 2018-03-30 07:40
Hi @LiamFielding. Thank you for your report. 
The issue has been fixed in magento/magento2#14323 by @mikewhitby in 2.1-develop branch
Related commit(s):
 - [509e5c4dc7cdbe647e123d38350899a6c28e5810](https://github.com/magento/magento2/commit/509e5c4dc7cdbe647e123d38350899a6c28e5810)
 - [4f30a3cf3451a64190ac3ff1f407999cfa9d8a21](https://github.com/magento/magento2/commit/4f30a3cf3451a64190ac3ff1f407999cfa9d8a21)

The fix will be available with the upcoming 2.1.14 release.
