### ISSUE TITLE
Currency not convert in new product widget without cache clean

### ISSUE THREAD

**Issue by rutvik-monpara** [magento/magento2#38321] opened 2023-12-27 09:34 UTC
### Preconditions and environment

- Magento version: 2.4.6-p3

### Steps to reproduce

1) Allow All Currencies from **Stores > Configuration > GENERAL > Currency Setup > Currency Options > Allowed Currencies**
2) Add Catalog New Products List widget in home-page-block cms block
3) Go to frontend and switch currency

### Expected result

![image](https://github.com/magento/magento2/assets/115232682/5b51f2ab-8001-4a76-8720-b68b7e256ccc)
Currency should be converted to switched currency

### Actual result

![image](https://github.com/magento/magento2/assets/115232682/d1f1da2d-ba58-4cc9-aeb9-eeac47303ef8)
Price currency displays the previous currency. Working fine after cache clean.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-12-27 10:07
@magento give me 2.4-develop instance

**Comment by rutvik-monpara** [comment] 2023-12-27 10:09
I have fix for this solution

**Comment by rutvik-monpara** [comment] 2023-12-27 10:26
Hi @engcom-Dash I added a new product widget on the page now you can check with the currency switch

**Comment by rutvik-monpara** [comment] 2023-12-27 10:38
@magento I am working on this

**Comment by rutvik-monpara** [comment] 2023-12-27 10:38
@magento add to contributors team

**Comment by rutvik-monpara** [comment] 2023-12-27 10:40
@magento I am working on this

**Comment by engcom-Dash** [comment] 2023-12-28 04:13
Hi @rutvik-monpara 

Thanks for reporting and collaboration.

Verified the issue in magento developer instance and the issue is not reproduced.

The currency convert in new product widget is working. Currency is converted to switched currency and able to see the products in the switched currency.
<img width="1440" alt="currency-euro" src="https://github.com/magento/magento2/assets/60198592/3aa7f0ec-c07b-4234-b22d-5973c753d3f7">
<img width="1440" alt="currency-dollor" src="https://github.com/magento/magento2/assets/60198592/7131c67d-5d22-4b5b-a81f-bdcaa41b8325">

**Comment by rutvik-monpara** [comment] 2023-12-28 04:59
@magento give me 2.4-develop instance

**Comment by rutvik-monpara** [comment] 2023-12-28 05:28
Hi @engcom-Dash,

**Comment by engcom-Dash** [comment] 2023-12-28 11:28
@magento give me 2.4-develop instance

**Comment by crocoitsakr** [comment] 2023-12-28 15:23
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2024-01-02 10:59
Hi @rutvik-monpara 

Thank you for reporting and collaboration.

Verified the issue on magento developer instance and the issue is reproducible.

Currency is not getting converted to the switched currency in new product widget.

Please refer the screenshot attached.

![Currency](https://github.com/magento/magento2/assets/60198592/b2247216-5355-48da-8b4f-9f293c7a3850)

**Comment by rogerdz** [comment] 2024-01-05 06:46
same https://github.com/magento/magento2/issues/37898

**Comment by andrewbess** [comment] 2024-01-15 10:22
Hello @rutvik-monpara 
Thank you for your collaboration
Sorry, but this issue and attached PR is duplicated with [previous one](https://github.com/magento/magento2/issues/37898).
I think we need to close this issue and PR to avoid confusion.

Also:
1. [The attached PR](https://github.com/magento/magento2/pull/38322) is not backward compatible
2. [The PR from previous issue](https://github.com/magento/magento2/pull/37899) has test coverage

I'll close this issue and PR.

cc @engcom-Dash @rogerdz

**Closed as completed** 2024-01-15 10:24 UTC
Labels: Issue: Confirmed, Component: Ui, Reproduced on 2.4.x, Progress: ready for dev, Priority: P2, Progress: done, Area: Account, Reported on 2.4.6-p3
