### ISSUE TITLE
Discount amount is removed in fixed amount cart rules

### ISSUE THREAD

**Issue by martinshawruroc** [magento/magento2#34721] opened 2021-11-26 08:03 UTC
### Preconditions (*)

1. Magento 2.4.3-p1

### Steps to reproduce (*)

1. Configure a "fixed amount" cart rule (note not "fixed amount per item")
2. Call `\Magento\Quote\Model\Quote\TotalsCollector::collectAddressTotals` more than once on a quote in the same request. For me, this was observed by using `onestepcheckout/iosc@1.2.049` and `klarna/module-kp@7.2.1` but I'm sure there are other ways.

### Expected result (*)

1. On arriving at the checkout, you'll see no discount is visible

### Actual result (*)

1. The discount should show in the minicart

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

This issue is fundamentally because the fixed amount cart sales rule doesn't support the total collection process running more than once per request. In my opinion it should have no state whatsoever and therefore should always return the same result no matter how many times it's called per request.

If you take a look at `\Magento\SalesRule\Model\Rule\Action\Discount\CartFixed::calculate` you'll see the implementation for the fixed cart rules. The most important snippet is:

```
        $cartRules = $quote->getCartFixedRules();
        if (!isset($cartRules[$rule->getId()])) {
            $cartRules[$rule->getId()] = $rule->getDiscountAmount();
        }
```

This is some data stored against the quote which stores the fixed value from the cart rule in it. It's important to note that this calculation is happening at the item level, rather than the quote level. Magento allocates the item a proportion of the total discount amount, taking into consideration things like shipping if necessary. Once it's done that, it deducts it from the total discount amount and stores it in the `cart_fixed_rules` data field. Then, when the remaining items perform their calculations they use this value and so on. Obviously, once all the items have had this process run, this value will be 0.

And that is the problem, because we are in the same request when we get the quote from the session, we get the same instance. Now, because of the snippet above we aren't going to get `rule->getDiscountAmount`, we're going to get 0. This overwrites the discount amount against the quote and sets it to 0.

I have resolved this in our codebase by writing a plugin `beforeCollectAddressTotals` which unsets this data field:

```
        $quote->unsetData('cart_fixed_rules');
```

**Comment by engcom-Hotel** [comment] 2021-12-01 11:01
Hi @martinshawruroc,

Thank you for reporting the issue!

However, we tried to reproduce it on Magento 2.4-develop but the discount functionality is working as expected.
Steps followed to reproduce it.
1. Create a Cart rule with Action: Fix Amount Discount for the whole cart
2. Create a custom controller and collect the address total for the quote twice.
![image](https://user-images.githubusercontent.com/51681618/144222877-22b620e1-f312-4fd5-9c73-51647e1f02fa.png)

3. Reload cart and checkout payment page.
4. Discount not removed.
![image](https://user-images.githubusercontent.com/51681618/144222925-e43760a3-96d1-443c-9763-43527048c382.png)

Thank you

**Comment by martinshawruroc** [comment] 2021-12-01 11:44
Hi @engcom-Hotel , thanks for coming back to me. Your example shows what I would expect to see, because as I say above it only occurs within the same request. When you reload the page, you have a new request and therefore you won't see the issue.

You could try editing your custom controller as follows:

```
$quote = $this->_checkoutSession->getQuote();
$totalCollector = $this->_objectManager->create(\MagentoQuote\Model\Quote\TotalsCollector::class);
$totalCollector->collectAddressTotals($quote, $quote->getShippingAddress());
echo 'Discount after first:' . $quote->getShippingAddress()->getDiscountAmount();
$totalCollector->collectAddressTotals($quote, $quote->getShippingAddress());
echo 'Discount after second:' . $quote->getShippingAddress()->getDiscountAmount();
```

You should find that the discount amount is 0 on the second echo

**Comment by engcom-Hotel** [comment] 2021-12-29 09:59
Dear @martinshawruroc,

The issue is reproducible in the 2.4.3-p1 version but not in Magento 2.4-develop, which means the issue has been fixed and will be available in the next release.

Hence we are closing this issue.

Thanks

**Closed as completed by engcom-Hotel** 2021-12-29 09:59 UTC
Labels: Issue: needs update
