### ISSUE TITLE
Integration tests failing during Magento setup

### ISSUE THREAD

**Issue by sergiynezbritskiy** [magento/magento2#33802] opened 2021-08-15 09:52 UTC
### Preconditions (*)
1. Fresh Magento 2.4.3 installation
2. PHP 7.3 or PHP 7.4
3. Composer version 2.1.5 (also tried with the highest composer 1 version
4. no RabbitMQ

### Steps to reproduce (*)
1. Basically I follow the steps in this doc https://devdocs.magento.com/guides/v2.4/test/integration/integration_test_execution.html
2. `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition`
3. `bin/magento module:enable --all`
4. `update the configuration in `dev/tests/integration/etc/install-config-mysql.php` (no RabbitMQ configuration)
5. `mysql -e "DROP DATABASE IF EXISTS magento_integration_tests"`
6. `mysql -e "CREATE DATABASE magento_integration_tests"`
7. `cd dev/tests/integration && php ../../../vendor/bin/phpunit`

### Expected result (*)
1. Magento test instance should be configured in dev/tests/integration/tmp/sandbox-{hash} dir
2. Tests defined in `dev/tests/integration/phpunit.xml.dist` should start running

### Actual result (*)
1. When running magento installation command, this command fails during the step "Disabling Maintenance Mode" with an error
```
In ResourceConnection.php line 148:

  [DomainException]
  Connection "default" is not defined
```
Log file is attached below

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._
[log.txt](https://github.com/magento/magento2/files/6988301/log.txt)

**Comment by sergeynezbritskiy** [comment] 2021-08-15 09:57
Additional information regarding this issue:
1. The issue is not reproducible on current 2.4-develop branch
2. If I run integration tests second time and TESTS_CLEANUP config in phpunit.xml is set to `disabled`, the tests are running fine, so currently as a workaround I wrapped this command in try/catch in my Jenkinsfiles and run tests second time in catch
```
script {
    try {
        sh 'cd ${TMP_DIR}/dev/tests/integration && php ../../../vendor/bin/phpunit'
    } catch (err) {
        sh 'cd ${TMP_DIR}/dev/tests/integration && php ../../../vendor/bin/phpunit'
    }
}

```

**Comment by sergeynezbritskiy** [comment] 2021-08-15 14:30
During the investigation I've found few issues:
1. Some objects, which should be cached in object manager and shared btw objects, are not actually shared and there are multiple instances of the same class:
- \Magento\Framework\App\ResourceConnection
- \Magento\Framework\App\DeploymentConfig

When object manager first creates ResourceCollection object, it has a dependency DeploymentConfig $deploymentConfig with 
```
$data = [
    'cache_types' => [
        'compiled_config' => 1
    ]
]
```
And this object is cached, but then I see that another instances of ResourceConnection is created with another instance of deploymentConfig as its dependency. The data of this new deploymentConfig get updated multiple times during installation, but when we go to the step "Disable maintenance mode" I see that at some place there is a call to the old object of resource connection with an old instance of deployment config. And when we try to get db connection, there is no info about db connection in the old version of deployment config. 
https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/App/ResourceConnection.php#L141

2. Second issue is that deployment config at some point gets cached inside the instance of DeploymentConfig, and every time we need reset it manually. so even if it doesn't return anything from cached $this->data, we presume that this configuration doesn't exist at all


I see 3 possible solutions:
1. if we can't get db configuration from deployment config, then we need to reset data and try to get db configuration again. This is mostly a workaround for a single case, so doesn't solve the issue.
2. ensure that shared objects are indeed shared all around the app. Currently I wasn't able to figure out why is it happening and how to solve is. Probably this should even work as it works now, so don't think that it would be a good idea to debug this.
3. extend the functionality of \Magento\Framework\App\DeploymentConfig. Every time when the requested configuration was not found in $this->data or $this->flattenedData, we reload the configuration.

I think that the third solution is preferable in this case, but think that someone from Adobe team need to approve this solution, no ?

**Comment by engcom-Echo** [comment] 2021-08-17 15:59
Hi @sergeynezbritskiy 
We tried to reproduce this issue on **2.4-develop** & were unable to do so.
Also as per your comments, you have confirmed that issue is not reproducible on 2.4-develop, Hence we are closing this issue.
We request you to create separate issues for any new issues identified during development/debugging.
Thank you.

**Comment by ihor-sviziev** [comment] 2021-08-18 06:15
@engcom-Echo, please double-check on 2.4.3, as this release wasn't yet merged to 2.4-develop branch

**Comment by oneserv-heuser** [comment] 2021-08-19 10:47
I can confirm that this issue exists. I just updated to magento 2.4.3 and then tried to run integration tests. I get the exact same error as @sergeynezbritskiy stated in the issue.

The same bug also appears when trying to install magento with the file ``app/etc/config.php`` present.
To reproduce try the following:

- Install magento from scratch
- Drop and recreate the magento database
- remove the file ``app/etc/env.php``
- run the command ``bin/magento setup:install ...`` again
- You'll get the the error:
```
In ResourceConnection.php line 148:

  [DomainException]
  Connection "default" is not defined
```

I think that these errors are related as the setup process tries to install magento with an env.php and config.php present, so I think both errors are fixable at once.

Should I still create an extra issue for it or not, what do you think @ihor-sviziev?

**Comment by ihor-sviziev** [comment] 2021-08-19 10:48
No need to create a separate issue. I reopened this one

**Comment by cmuench** [comment] 2021-10-04 07:49
@ihor-sviziev Is anyone at Adobe working on that issue. It's currently blocking the deployment of several (also commerce) projects, because our build pipelines are broken.
That's a core issue which should be prioritized by the core team.

**Comment by cmuench** [comment] 2021-10-04 08:02
We have that issue if the config.php is checked in and if we run that in the CI pipeline.
`php bin/magento setup:install --cleanup-database --db-host=localhost --db-user=root --db-password=root --db-name=magento`

On the local machine we can run the command twice. The second run fixes the (maybe cache) issue.
In the CI it's not the idea to run the installation process twice.

**Comment by cmuench** [comment] 2021-10-04 08:06
New information. If we delete the `app/etc/config.php` in the pipeline, the installation finishes without a failure. But that's not a solution.

**Comment by cmuench** [comment] 2021-10-04 10:27
We can confirm that the PR #33803 fixes the issue.
We added the code changes a patch in our project. The pipeline is then "green".

**Comment by BorisovskiP** [comment] 2022-05-12 10:21
Any updates on this issue? I can reproduce it in a pipeline on Magento 2.4.4.

**Comment by ilnytskyi** [comment] 2022-06-06 09:16
I also confirm that https://github.com/magento/magento2/pull/33803/ fixes the issue with installation in pipelines in our case

**Comment by pawan-mittal** [comment] 2022-08-01 12:00
Any updates on this issue? I can reproduce it in a pipeline on Magento 2.4.4.

**Comment by engcom-Hotel** [comment] 2022-08-02 06:47
Hello @pawan-mittal,

The related PR https://github.com/magento/magento2/pull/33803 is in `Merge in progress` status. 

Thanks

**Comment by Vinai** [comment] 2022-08-22 14:14
Reproduced on 2.4.5

**Comment by norgeindian** [comment] 2022-09-14 11:58
Does anybody by chance already have a patch file to fix this?

**Comment by hostep** [comment] 2022-09-14 20:44
Here's one for Magento 2.4.5 which I've created earlier today, it's based on https://github.com/magento/magento2/pull/33803 but had to fix some merge conflicts, so hopefully those were solved correctly, but it seems to work on our end at least.

[PR-33803-Framework.txt](https://github.com/magento/magento2/files/9569853/PR-33803-Framework.txt)

**Comment by norgeindian** [comment] 2022-09-16 06:53
@hostep , thanks a lot, awesome. Works fine for me.

**Comment by peterjaap** [comment] 2022-11-13 21:10
The current pull request here does not work on 2.4.3 currently since the load() function differs between 2.4.3 and 2.4.4;

- https://github.com/magento/magento2/blob/2.4.3/lib/internal/Magento/Framework/App/DeploymentConfig.php#L150
- https://github.com/magento/magento2/blob/2.4.4/lib/internal/Magento/Framework/App/DeploymentConfig.php#L167

**Closed as completed** 2022-11-24 17:05 UTC
Labels: Issue: Confirmed, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P1, Severity: S1, Progress: done, Reported on 2.4.3, Area: Install & Administer

**Comment by convenient** [comment] 2023-06-15 10:47
FWIW i've just got this on 2.4.7-beta1

My CI tooling can fix it by re-running `composer install --no-interaction`  (which I discovered when playing with this comment https://github.com/magento/magento2/issues/33802#issuecomment-1112369298)

https://github.com/AmpersandHQ/magento-docker-test-instance/pull/12/files#diff-79a3628f21c70a32e21bfe89edb38a4f158b1707f6c1bea98083204d0934484fR143

**Comment by hostep** [comment] 2023-07-27 10:42
This problem has indeed returned in 2.4.7-beta1, but also in 2.4.6-p2 (which is now available in pre-release and will be available from the 8th of August for everyone).

I've opened a new issue for this: https://github.com/magento/magento2/issues/37805

**Comment by bhaveshseepossible** [comment] 2024-01-19 11:28
> Here's one for Magento 2.4.5 which I've created earlier today, it's based on #33803 but had to fix some merge conflicts, so hopefully those were solved correctly, but it seems to work on our end at least.
> 
> [PR-33803-Framework.txt](https://github.com/magento/magento2/files/9569853/PR-33803-Framework.txt)

@hostep your patch is very useful.
**Thank you**
