### ISSUE TITLE
FPC of the pages related to a purchased product is flushed after every checkout

### ISSUE THREAD

**Issue by vtimonin** [magento/magento2#13243] opened 2018-01-17 16:28 UTC
By default, Magento 2 flushes 'full page' cache of the pages related to a purchased product after every checkout. While a part of the customers make their orders, the other customers browsing the categories can experience intermittent slower page loads because pages are not served from the cache

### Preconditions
1. Varnish is used for FPC

### Steps to reproduce
1. Open a product detail page.
2. Make sure response headers for this page indicate a Varnish cache hit: `X-Edge-Cache-Status: HIT`
3. Add this product to cart and complete checkout process
4. Make sure `indexer_update_all_views` cron job was executed after the checkout.
5. Open this product PDP again.

### Expected result
1. If the product stock status is not changed then response headers for this page should indicate a Varnish cache hit: `X-Edge-Cache-Status: HIT`

### Actual result
1. Response headers always indicate a Varnish cache miss: `X-Edge-Cache-Status: MISS`

There is an extension https://marketplace.magento.com/innovo-module-cache-improve.html which addresses this performance issue.

**Comment by mslabko** [comment] 2018-02-28 08:51
Hi @vtimonin, this issue was fixed in 2.2.x https://github.com/magento/magento2/commit/f9fc2faac3700ab10fa14c638034c7bfa988abea

**Comment by magento-engcom-team** [comment] 2018-03-02 13:44
@vtimonin, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2018-03-05 17:32
@vtimonin The issue is already fixed in 2.2.
Closing ticket for now. Please reopen if you need any further assistance with this.

**Closed as completed by magento-engcom-team** 2018-03-05 17:32 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
