### ISSUE TITLE
Cannot click Select All / Unselect All properly in Index Management

### ISSUE THREAD

**Issue by peterjaap** [magento/magento2#3580] opened 2016-02-29 17:30 UTC
Maybe in other places as well.

![screenshot 2016-02-29 18 28 04](https://cloud.githubusercontent.com/assets/431360/13402816/44eb6c44-df12-11e5-9616-317561abc993.png)

When I remove this 'top' CSS line, it's fine; https://github.com/magento/magento2/blob/develop/app/design/adminhtml/Magento/backend/web/css/source/forms/_temp.less#L425

**Comment by vil11** [comment] 2016-03-01 13:57
Hello @peterjaap, thanks for your report!
We can't reproduce described issue neither on **Mac** nor on **Win**.

Dmytro Vilchynskyi, M2 QA engineer.

**Comment by MomotenkoNatalia** [comment] 2016-03-01 14:04
@peterjaap Could you provide any additional information to help us to reproduce this issue?

**Comment by jsakars** [comment] 2016-03-01 20:18
@vil11 & @peterjaap I am able to reproduce it - [see video demostration](http://screencast.com/t/5ihZu8MSyR)

Environment:
- OS: OS X El Capitan
- Browser: Chrome
- M2 version: 2.0.2

**Comment by peterjaap** [comment] 2016-03-02 05:41
Maybe screen size has something to do with it? We were all on our Macbooks.

**Comment by jsakars** [comment] 2016-03-02 06:50
@peterjaap MacBook Pro (Retina, 13-inch, Early 2015)

**Comment by PieterCappelle** [comment] 2016-04-27 10:02
I'm having the same problem.

Environment:
- OS: OS X Yosemite
- Browser: Chrome 50
- M2 version: 2.0.4

**Comment by MomotenkoNatalia** [comment] 2016-04-28 09:28
Hi all,  Internal ticket MAGETWO-51803 will be soon delivered

**Comment by PieterCappelle** [comment] 2016-05-19 21:21
@MomotenkoNatalia: any idea when is soon? :)

**Comment by psydwannabe** [comment] 2016-06-10 16:35
This issue has been resolved internally and will likely be included in the next release as noted by @piotrekkaminski in #4080 [here](https://github.com/magento/magento2/issues/4080#issuecomment-222206366).

**Comment by KrystynaKabannyk** [comment] 2016-06-23 16:36
Hello @peterjaap, this issue has been fixed in the 2.1.0 Release, that's why I'm closing it. If you any questions or additional information regarding the issue feel free to reopen it or create a new one.

**Closed as completed by KrystynaKabannyk** 2016-06-23 16:36 UTC
