### ISSUE TITLE
ElasticSearch When applying the extra filter to the product listing, Magento keeps the same page number

### ISSUE THREAD

**Issue by santosh-gaggle** [magento/magento2#28011] opened 2020-04-28 09:57 UTC
### Preconditions (*)

1. Magento 2.3.3
2. PHP 7.2
3. elasticsearch 6+

### Steps to reproduce (*)

1. Enter listing with n products,
2. Move to the last page of results
3. Select filter in the sidebar that filters out most of the products

### Expected result (*)

1.I'm redirected either to last page of results or first page of the listing (so I see any products)

### Actual result (*)

1. I'm still at the last page of results before adding the filter, so the message says that there are no search results for my query

**Here is the video**: [Desktop-2020-4-28-15-16-12.webm.zip](https://github.com/magento/magento2/files/4544871/Desktop-2020-4-28-15-16-12.webm.zip)

**Comment by ihor-sviziev** [comment] 2020-04-28 10:06
Seems like might be fixed by https://github.com/magento/magento2/pull/26988, but not sure

**Comment by santosh-gaggle** [comment] 2020-04-28 10:16
> Seems like might be fixed by #26988, but not sure

checked but still the same issue

**Comment by Bartlomiejsz** [comment] 2020-04-28 10:43
Hi @santosh-gaggle - could you please specify if attribute on layered navigation that you use to filter is standard attribute or swatch?

**Comment by lbajsarowicz** [comment] 2020-04-28 10:57
@ihor-sviziev No, because in my PR I fixed situation when you change amount of items on page, here it is about adding extra filters. And previously it was working by coincidence. Now, when Magento is expected to work properly with pagination - we need to address also that issue.

**Comment by Bartlomiejsz** [comment] 2020-04-28 11:30
I created PR that fixes this case. Important here is that issue occurs only with swatch filter, same as color on video attached to ticket.

**Comment by magento-engcom-team** [comment] 2020-04-28 12:17
:white_check_mark: Confirmed by @ihor-sviziev 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33806` were created

**Issue Available**: @ihor-sviziev, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by santosh-gaggle** [comment] 2020-04-28 12:54
Thanks @Bartlomiejsz ,
Now this issue fixed and working well ...:)

**Comment by magento-engcom-team** [comment] 2020-06-09 19:31
Hi @santosh-gaggle. Thank you for your report. 
The issue has been fixed in magento/magento2#28015 by @Bartlomiejsz in 2.4-develop branch
Related commit(s):
 - [92b29c6f9eb05dbf45cebdc601a4a9aeb95b713d](https://github.com/magento/magento2/commit/92b29c6f9eb05dbf45cebdc601a4a9aeb95b713d)
 - [475be33cdc0e4bc058176669d05243462bafc8a3](https://github.com/magento/magento2/commit/475be33cdc0e4bc058176669d05243462bafc8a3)
 - [7630cb00855d13005e46d0b6cfcb228f986a0278](https://github.com/magento/magento2/commit/7630cb00855d13005e46d0b6cfcb228f986a0278)
 - [0de77c8037c45c4f5a196dc1ca7a8b4635e2d736](https://github.com/magento/magento2/commit/0de77c8037c45c4f5a196dc1ca7a8b4635e2d736)
 - [ee4acffc30d0aba1be88a2f38f0786c3d4af0639](https://github.com/magento/magento2/commit/ee4acffc30d0aba1be88a2f38f0786c3d4af0639)

The fix will be available with the upcoming 2.4.1 release.

**Closed as completed by magento-engcom-team** 2020-06-09 19:31 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Swatches, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P3, Severity: S2, Triage: Done, Progress: done, Reported on 2.3.3
