### ISSUE TITLE
Can't scroll in modal-popup on iOS

### ISSUE THREAD

**Issue by bramvanderholst** [magento/magento2#21147] opened 2019-02-12 10:10 UTC
### Preconditions (*)
1. Magento 2.2.7 (https://github.com/magento/magento2/commit/76ae28f82032a0af152d3285bedc1ffa46ff2055)

### Steps to reproduce (*)
1. Open any modal-popup of which the height exceeds the viewport height
2. Try scrolling in the popup on an iPhone (tested on iPhone 6s Plus & iPhone X)

### Expected result (*)
1. Scrolling inside the .modal-popup element

### Actual result (*)
1. http://cloud.h-o.nl/dfe0e645138b

**Comment by magento-engcom-team** [comment] 2019-02-12 10:10
Hi @bramvanderholst. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@bramvanderholst do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-02-12 10:13
Hi @krishprakash. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by krishprakash** [comment] 2019-02-12 10:15
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-12 10:15
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-12 10:15
Hi @krishprakash, here is your [Magento instance](https://i-21147-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21147-2-3-develop.instances.magento-community.engineering/admin](https://i-21147-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-02-12 10:31
@krishprakash Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-02-12 10:32
Hi @priti2jcommerce. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-02-12 10:33
:white_check_mark: Confirmed by @priti2jcommerce
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment] 2019-02-12 10:35
Hi @priti2jcommerce. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by priti2jcommerce** [comment] 2019-02-12 10:36
* @magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-12 10:36
Hi @priti2jcommerce. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-12 10:36
Hi @priti2jcommerce, here is your [Magento instance](https://i-21147-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21147-2-2-develop.instances.magento-community.engineering/admin](https://i-21147-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-02-12 10:51
:white_check_mark: Confirmed by @krishprakash
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by Karlasa** [comment] 2019-02-12 13:44
PR that introduced the issue #15172

**Comment by Karlasa** [comment] 2019-02-12 16:35
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-12 16:35
Hi @Karlasa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-12 16:36
Hi @Karlasa, here is your [Magento instance](https://i-21147-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21147-2-3-develop.instances.magento-community.engineering/admin](https://i-21147-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by amol2jcommerce** [comment] 2019-02-13 04:32
* @magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-13 04:32
Hi @amol2jcommerce. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-13 04:33
Hi @amol2jcommerce, here is your [Magento instance](https://i-21147-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21147-2-2-develop.instances.magento-community.engineering/admin](https://i-21147-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-02-25 19:41
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98426`, `MAGETWO-98427` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-04-28 22:10
Hi @bramvanderholst. Thank you for your report. 
The issue has been fixed in magento/magento2#21150 by @priti2jcommerce in 2.3-develop branch
Related commit(s):
 - [d661d613c17ba25304f2aa1f21e67bc97dff509d](https://github.com/magento/magento2/commit/d661d613c17ba25304f2aa1f21e67bc97dff509d)
 - [85026a47b14a3576c1c98dda56d25ad9c48bc285](https://github.com/magento/magento2/commit/85026a47b14a3576c1c98dda56d25ad9c48bc285)
 - [692cd9dc92234b256e40c9aeb09055fd7207d4f0](https://github.com/magento/magento2/commit/692cd9dc92234b256e40c9aeb09055fd7207d4f0)
 - [ee8778b330a4f327dffdaa90add23c51da8b3492](https://github.com/magento/magento2/commit/ee8778b330a4f327dffdaa90add23c51da8b3492)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-04-28 22:10 UTC
Labels: Issue: Ready for Work, Component: Checkout, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Area: Design/Frontend
