### ISSUE TITLE
An empty window opens after the second click of the "Add Attribute" button

### ISSUE THREAD

**Issue by Viktorja1** [magento/magento2#30361] opened 2020-10-07 11:54 UTC
### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Go to Catalog -> Products -> Add New Product
2. Click on the "Add Attribute" button (Upper right corner)
3. Click on the "Create New Attribute" button
4. Close the opened window
5. Click on the "Create New Attribute" button again

### Expected result (*)

The "New Attribute" window opened (as on the 4 step)

### Actual result (*)

Empty window opened with title. Error in console:

![Peek 2020-10-07 14-49](https://user-images.githubusercontent.com/30689417/95331057-1ab1e880-08b2-11eb-9e82-ac358de9e74b.gif)

```
Uncaught TypeError: value.split is not a function
    at insert.js:204
    at Function._.each._.forEach (underscore.js:150)
    at UiClass.filterExternalLinks (insert.js:203)
    at UiClass.initExternalLinks (insert.js:178)
    at UiClass.destroyInserted (insert.js:166)
    at UiClass._super (wrapper.js:106)
    at UiClass.destroyInserted (insert-form.js:106)
    at UiClass.destroyInserted (wrapper.js:109)
    at registry.js:58
    at Registry._resolveRequest (registry.js:417)
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment] 2020-10-07 13:58
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment] 2020-10-07 14:12
Hi @Viktorja1 
The issue is Reproduced in the Default Magento 2.4 Instance as per steps to be reproduced, Actual result and Expected result.
PFA:
![image](https://user-images.githubusercontent.com/24711761/95342513-2367e600-08d5-11eb-885e-02204e0446e7.png)

Thanks.

**Comment by magento-engcom-team** [comment] 2020-10-07 14:13
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38272` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ashvin0009** [comment] 2020-10-10 06:45
@magento add to contributors team

**Comment by ashvin0009** [comment] 2020-10-10 06:45
@magento I am working on this

**Comment by vijay-wagento** [comment] 2020-10-10 10:20
#dmcdindia2020

**Comment by Viktorja1** [comment] 2020-10-15 18:23
@magento give me 2.4-develop instance

**Comment by gabrieldagama** [comment] 2020-11-13 13:28
Hi @Viktorja1. Thank you for your report. 
The issue has been fixed in magento/magento2#30400 by @shikhamis11 in 2.4-develop branch
Related commit(s):
 - [6ffb8b1b5ec4919f40684b575120bca4e9707152](https://github.com/magento/magento2/commit/6ffb8b1b5ec4919f40684b575120bca4e9707152)
 - [87d870cc9a54641a1d830d1b85a8edc7aadcd3de](https://github.com/magento/magento2/commit/87d870cc9a54641a1d830d1b85a8edc7aadcd3de)
 - [3b0b7ca0bfc78359367c1fe1f2ad62a4945defd5](https://github.com/magento/magento2/commit/3b0b7ca0bfc78359367c1fe1f2ad62a4945defd5)

The fix will be available with the upcoming 2.4.2 release.

**Closed as completed by gabrieldagama** 2020-11-13 13:28 UTC
Labels: Component: Catalog, Issue: Clear Description, Issue: Confirmed, Component: Admin, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P2, Severity: S1, Progress: done, Component: Attributes, Event: dmcdindia2020, Reported on 2.4.0

**Comment by Viktorja1** [comment] 2023-07-28 15:01
https://github.com/magento give me 2.5-develop instance

**Comment by Viktorja1** [comment] 2023-07-28 15:04
@magento give me 2.4-develop instance

**Comment by Viktorja1** [comment] 2023-07-28 15:04
@magento give me 2.5-develop instance

**Comment by Viktorja1** [comment] 2023-07-28 15:07
@magento give me 2.4-develop instance

**Comment by Viktorja1** [comment] 2023-07-28 19:02
@magento give me 2.4-develop instance

**Comment by Viktorja1** [comment] 2023-11-09 07:16
@magento give me 2.5-develop instance

**Comment by Viktorja1** [comment] 2023-11-09 07:19
@magento give me 2.4-develop instance

**Comment by Viktorja1** [comment] 2023-11-09 07:43
@magento give me 2.4-develop instance
