### ISSUE TITLE
Response "Shipping address is not set" for  set-payment-information  Magento 2 Rest API

### ISSUE THREAD

**Issue by Giri-Happiest-Minds** [magento/magento2#6432] opened 2016-09-01 09:10 UTC
JSON Reference: http://devdocs.magento.com/swagger/index.html#/ 

Steps followed
Step 1 --> http://<magentohost>/rest/default/V1/guest-carts  -- 200 OK
Step 2 --> http://<magentohost>/rest/default/V1/guest-carts/{cart id}/items  -- 200 OK
Step 3 --> http://<magentohost>/rest/default/V1/guest-carts/{cart id}/shipping-information – 200 OK
Step 4 --> http://<magentohost>/rest/default/V1/guest-carts/{cart id}/set-payment-information  -- 400 Bad Request and the response JSON as
{
  "message": "Shipping address is not set"
}

Request JSON details:
{
  "email": "happy5648@gmal.com",
  "paymentMethod": {
    "po_number": "123",
    "method": "purchaseorder",
    "additional_data": [
      ""
    ],
    "extension_attributes": {
     "agreement_ids": [
        ""
      ]
    }
  },
  "billingAddress": {
      "id": 1,
    "region": "Virginia",
    "region_id": "Virginia",
    "region_code": "VA",
    "country_id": "US",
    "street": [
      "Symbiosis College"
    ],
    "company": "Happiest",
    "telephone": "9090909090",
    "fax": "13232212589",
    "postcode": "51",
    "city": "Bangalore",
    "firstname": "Name",
    "lastname": "lastName",
    "middlename": "Middle",
    "prefix": "Mr",
    "suffix": "",
    "vat_id": null,
    "customer_id": 1,
    "email": "abc.xyz@gmail.com",
    "same_as_billing": 0,
    "customer_address_id": 0,
    "save_in_address_book": 0,
    "extension_attributes": {},
    "custom_attributes": [
      {
        "attribute_code": "",
        "value": ""
      }
    ]
  }
}

Please help resolve this issue.

**Comment by veloraven** [comment] 2016-09-01 15:22
@Giri-Happiest-Minds thank you for your feedback.
Please, provide the used Magento version.

**Comment by Rabiteks** [comment] 2016-09-01 17:45
I have faced same problem. I use magento 2. Please suggest us

**Comment by Giri-Happiest-Minds** [comment] 2016-09-02 03:28
@veloraven 
The version is Magento 2.0.2

**Comment by Giri-Happiest-Minds** [comment] 2016-09-02 06:52
@veloraven Tried with Magento 2.0.7 too but facing the same issue.

**Comment by YevSent** [comment] 2016-09-03 10:11
Hi, please post request details for `shipping-information` API request.

**Comment by Giri-Happiest-Minds** [comment] 2016-09-03 10:19
Hi, @joni-jones  the request details for shipping-information API is

{
  "addressInformation": {
    "shipping_address": {
      "id": 1,
    "region": "Virginia",
    "region_id": 51,
    "region_code": "VA",
    "country_id": "US",
    "street": [
      "Symbiosis College"
    ],
      "company": "Happiest",
    "telephone": "9090909090",
    "fax": "13232212589",
    "postcode": "560100",
    "city": "Bangalore",
    "firstname": "Name",
    "lastname": "lastName",
    "middlename": "Middle",
    "prefix": "Mr",
    "suffix": "",
    "vat_id": null,
    "customer_id": 0,
    "email": "abc.xyz@gmail.com",
    "same_as_billing": 0,
    "customer_address_id": 0,
    "save_in_address_book": 0,
    "extension_attributes": {},
    "custom_attributes": [
      {
        "attribute_code": "",
        "value": ""
      }
    ]
    },
    "billing_address": {
      "id": 1,
    "region": "Virginia",
    "region_id": 51,
    "region_code": "VA",
    "country_id": "US",
    "street": [
      "Symbiosis College"
    ],
      "company": "Happiest",
    "telephone": "9090909090",
    "fax": "13232212589",
    "postcode": "560100",
    "city": "Bangalore",
    "firstname": "Name",
    "lastname": "lastName",
    "middlename": "Middle",
    "prefix": "Mr",
    "suffix": "",
    "vat_id": null,
    "customer_id": 1,
    "email": "abc.xyz@gmail.com",
    "same_as_billing": 0,
    "customer_address_id": 0,
    "save_in_address_book": 0,
    "extension_attributes": {},
    "custom_attributes": [
      {
        "attribute_code": "",
        "value": ""
      }
    ]
    },
    "shipping_method_code": "flatrate",
    "shipping_carrier_code": "flatrate",
    "extension_attributes": {},
    "custom_attributes": [
      {
        "attribute_code": "",
        "value": ""
      }
    ]
  }
}

**Comment by SerhiyShkolyarenko** [comment] 2016-09-22 13:18
@Giri-Happiest-Minds is it reproducible for you on 2.0.11?
I dropped unnecessary fields from your data and sent
to shipping-information:

```
{
"addressInformation": {
"shipping_address": {
"region": "Virginia",
"region_id": 51,
"region_code": "VA",
"country_id": "US",
"street": [
"Symbiosis College"
],
"company": "Happiest",
"telephone": "9090909090",
"fax": "13232212589",
"postcode": "560100",
"city": "Bangalore",
"firstname": "Name",
"lastname": "lastName",
"middlename": "Middle",
"prefix": "Mr",
"suffix": "",
"vat_id": null,
"customer_id": 0,
"email": "abc.xyz@gmail.com",
"same_as_billing": 0,
"customer_address_id": 0,
"save_in_address_book": 0,
"extension_attributes": {},
"custom_attributes": []
},
"billing_address": {
"region": "Virginia",
"region_id": 51,
"region_code": "VA",
"country_id": "US",
"street": [
"Symbiosis College"
],
"company": "Happiest",
"telephone": "9090909090",
"fax": "13232212589",
"postcode": "560100",
"city": "Bangalore",
"firstname": "Name",
"lastname": "lastName",
"middlename": "Middle",
"prefix": "Mr",
"suffix": "",
"vat_id": null,
"customer_id": 1,
"email": "abc.xyz@gmail.com",
"same_as_billing": 0,
"customer_address_id": 0,
"save_in_address_book": 0,
"extension_attributes": {},
"custom_attributes": []
},
"shipping_method_code": "flatrate",
"shipping_carrier_code": "flatrate",
"extension_attributes": {},
"custom_attributes": []
}
}
```

To set-payment-information:

```
{
"email": "happy5648@gmal.com",
"paymentMethod": {
"po_number": "123",
"method": "purchaseorder",
"additional_data": [""],
"extension_attributes": {
"agreement_ids": [""]
}
},
"billingAddress": {
"region": "Virginia",
"region_code": "VA",
"country_id": "US",
"street": [
"Symbiosis College"
],
"company": "Happiest",
"telephone": "9090909090",
"fax": "13232212589",
"postcode": "51",
"city": "Bangalore",
"firstname": "Name",
"lastname": "lastName",
"middlename": "Middle",
"prefix": "Mr",
"suffix": "",
"vat_id": null,
"customer_id": 1,
"email": "abc.xyz@gmail.com",
"same_as_billing": 0,
"customer_address_id": 0,
"save_in_address_book": 0,
"extension_attributes": {},
"custom_attributes": []
}
}
```

and everything worked OK on the latest develop branch.

**Comment by SerhiyShkolyarenko** [comment] 2016-10-12 08:33
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by SerhiyShkolyarenko** 2016-10-12 08:33 UTC
Labels: bug report, Progress: needs update, Component: Framework/Webapi
