### ISSUE TITLE
Event 'customer_login' expects different entities in core code and in tests.

### ISSUE THREAD

**Issue by zhartaunik** [magento/magento2#29347] opened 2020-07-31 11:23 UTC
### Summary (*)
Web API with login action tests fails when implemented an observer for the 'customer_login' event.

### Examples (*)
`magento/app/code/Magento/Customer/Model/Session.php`

```
    /**
     * Sets customer as logged in
     *
     * @param CustomerData $customer
     * @return $this
     */
    public function setCustomerDataAsLoggedIn($customer)
    {
        $this->regenerateId();
        $this->_httpContext->setValue(Context::CONTEXT_AUTH, true, false);
        $this->setCustomerData($customer);

        $customerModel = $this->_customerFactory->create()->updateData($customer);

        $this->setCustomer($customerModel);

        $this->_eventManager->dispatch('customer_login', ['customer' => $customerModel]);
        $this->_eventManager->dispatch('customer_data_object_login', ['customer' => $customer]);
        return $this;
    }
```

Magento puts `$customerModel instanceof \Magento\Customer\Model\Customer`

`magento/dev/tests/api-functional/framework/Magento/TestFramework/Helper/Customer.php`

```
    /**
     * @param array $additional
     * @return array|bool|float|int|string
     */
    public function createSampleCustomer(array $additional = [])
    {
        $serviceInfo = [
            'rest' => [
                'resourcePath' => self::RESOURCE_PATH,
                'httpMethod' => RestRequest::HTTP_METHOD_POST,
            ],
            'soap' => [
                'service' => self::SERVICE_NAME,
                'serviceVersion' => self::SERVICE_VERSION,
                'operation' => self::SERVICE_NAME . 'CreateAccount',
            ],
        ];

        $customerDataArray = $this->dataObjectProcessor->buildOutputDataArray(
            $this->createSampleCustomerDataObject($additional),
            \Magento\Customer\Api\Data\CustomerInterface::class
        );
        $requestData = ['customer' => $customerDataArray, 'password' => self::PASSWORD];
        $customerData = $this->_webApiCall($serviceInfo, $requestData);
        return $customerData;
    }
```

Magento creates \Magento\Customer\Api\Data\CustomerInterface::class object and pass it into 'customer_login' event.

### To reproduce an issue
Scenario 1:
Create an observer for event 'customer_login' and work with $customer object as with `\Magento\Customer\Model\Customer`
Result: Magento will work fine, tests will fail

Scenario 2:
Create an observer for event 'customer_login' and work with $customer object as with `\Magento\Customer\Api\Data\CustomerInterface`
Result: Magento will fail, tests ?? not sure

### Proposed solution
Not sure what is the best solution. Fix tests or fix the original method in Session.php

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look, and feel, “quality” or “usability”._

**Comment by zhartaunik** [comment] 2021-01-05 06:28
If you don't want to solve an issue, just close it! And the sheet is empty. Good job!!

**Comment by zhartaunik** [comment] 2021-03-22 07:04
Why are you going to close it, just because everyone ignores it? Why do not keep it open?

**Comment by engcom-Lima** [comment] 2021-06-15 11:32
Hi @zhartaunik, I have been started working on the ticket. Can you please provide me the details reproducible steps and screenshots. I will be happy to work and resolve your issue.

As of now insufficient details are there. What error you getting while test cases ran.

I hope you will reproduce the issue on Magento V.2.4-develop and will provide the details steps for the same. Thanks

**Comment by zhartaunik** [comment] 2021-06-16 11:37
Hi Rajesh,

Currently I'm unable to tell, because I'm on the vacation this week.

Please contact me next week if you face with any troubles while issue
reproducing.

вт, 15 июн. 2021 г., 13:32 Rajesh Kumar ***@***.***>:

**Comment by engcom-Lima** [comment] 2021-06-23 13:58
Hi @zhartaunik,

I hope you came back from the vacation. I tried to do at our level. I can't reproduce the issue.

Please provide the details steps and screenshots which will be very helpful in this. I will be happy to work on this issue.

**Comment by engcom-Hotel** [comment] 2021-07-08 07:58
Hi @zhartaunik,

We are unable to hear from you since past more than 14 days, so we are closing this issue. If you still facing the issue, then you can reopen this ticket or create a new ticket.

Thanks

**Closed as completed by engcom-Hotel** 2021-07-08 07:58 UTC
Labels: Triage: Dev.Experience, Issue: needs update
