### ISSUE TITLE
Canonical url cannot be used on multi store per xml

### ISSUE THREAD

**Issue by in-session** [magento/magento2#35024] opened 2022-01-26 17:12 UTC
### Preconditions (*)

1. Magento 2.4.3-p1

### Steps to reproduce (*)

1. add to Magento_Customer/layout/customer_account_login.xml
2. `<link rel="canonical" src="customer/account/login/" src_type="url"/>` or
3. `<link rel="canonical" src="customer/account/login/" />`

### Expected result (*)

`<link rel="canonical" href="https://www.example.com/en/customer/account/login/" />`

### Actual result (*)

1. [Screenshots, logs or description]
2. `<link rel="canonical" href="customer/account/login/" />`
3. `<link rel="canonical" href="https://www.example.com/.../static/version1642953105/....en/customer/account/login/" />`

### Idea (*)
`<link rel="canonical" src="customer/account/login/" src_type="storeurl"/>`
storeurl = for the current store url in front, so it would be possible to set this correctly via XML
Result: `<link rel="canonical" href="{storefont url}/customer/account/login/" />`:`<link rel="canonical" href="https://www.example.com/en/customer/account/login/" />`

### Why this is needed, for example:
Just on the login page under the condition that the "Redirect Customer to Account Dashboard after Logging" is set to false. 
Then it will be generated referer url like for example: https://www.example.com/en/customer/account/login/referer/aHR0cDovL20yMjJzYW1wbGU0LmNvbS9jdXN0b21lci9hY2NvdW50L2xvZ2luLw%2C%2C/
These pages end up in the Google index as an infinite loop.

Related: https://magento.stackexchange.com/questions/211840/why-magento-2-auto-add-referer-to-link-login/211844

**Comment by engcom-Delta** [comment] 2022-02-24 10:03
Hi @in-session ,
Thank you for logging an issue. We would like to get more details on step# 2 , where to add those lines in specified xml file.
Moreover, Kindly provide clear steps for single store with screenshots, so that we can try to replicate for multiple stores.
Hence added the label 'Needs Update'.

**Comment by in-session** [comment] 2022-03-12 10:02
Hi @engcom-Delta 
The main problem is simply that canonical is not suitable for the multistore. Therefore, it would be useful here for the canonical to give the possibility to output this relative and then add the storefronturl. For example by:
`<link rel="canonical" src="customer/account/login/" src_type="storeurl"/>`

In that case, the example here would be necessary: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/view/frontend/layout/customer_account_login.xml

Just on the login page under the condition that the "Redirect Customer to Account Dashboard after Logging" is set to false.
Then it will be generated referer url like for example: https://www.example.com/en/customer/account/login/referer/aHR0cDovL20yMjJzYW1wbGU0LmNvbS9jdXN0b21lci9hY2NvdW50L2xvZ2luLw%2C%2C/
These pages end up in the Google index as an infinite loop.

**Comment by engcom-Echo** [comment] 2022-07-20 05:29
Hi @in-session,

Thank you for reporting the issue.

We tried to reproduce it on Magento 2.4-dev but the issue is not reproducible.

Steps followed to reproduce issue:

1- Install the fresh Magento 2.4-dev instance.
2- Open file Magento_Customer/layout/customer_account_login.xml
3- Add <link rel="canonical" src="customer/account/login/" />

<img width="1328" alt="34903-I" src="https://user-images.githubusercontent.com/51681435/179768172-a6862c27-8fba-4201-912c-c18a294960ca.png">


4- "Redirect Customer to Account Dashboard after Logging" is set to false

<img width="1072" alt="34901-II" src="https://user-images.githubusercontent.com/51681435/179768212-f710aeec-1c3c-466d-848e-c5776a9299c0.png">


5- Customer is able to log in successfully.

Please confirm if you are facing the issue with single store too and share the screenshots with clear steps so we can try to replicate the same again.

**Comment by engcom-Echo** [comment] 2022-08-08 09:31
Hello @in-session,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Echo** 2022-08-08 09:31 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Area: SEO
