### ISSUE TITLE
Wrong order total in customer information orders tab in admin panel

### ISSUE THREAD

**Issue by LordHansolo** [magento/magento2#18618] opened 2018-10-15 12:41 UTC
### Preconditions
1. Magento 2.2.5

### Steps to reproduce
1. Set CHF as Default Currency
![default_currency_config](https://user-images.githubusercontent.com/22025597/46951040-0a7e1e80-d087-11e8-99dd-688f5ef6f78e.png)
2. Set GBP currency for United Kingdom website
![uk_currency_config](https://user-images.githubusercontent.com/22025597/46951046-0fdb6900-d087-11e8-8618-5677b5f2c972.png)
3. Place order from United Kingdom website
4. View order total in customer information orders tab in admin panel

### Expected result
1. Order total is same in "customer information orders grid" and "orders grid"

### Actual result
1. Orders total differs in "customer information orders grid" and "orders grid"
![orders_grid](https://user-images.githubusercontent.com/22025597/46951050-14a01d00-d087-11e8-9fe5-e8474b589a49.png)
![customer_orders_grid](https://user-images.githubusercontent.com/22025597/46951051-179b0d80-d087-11e8-9529-d3c6d743c028.png)

### Additional Information
1. It seems Magento recalculate currency in "customer information orders grid" but it should not.

**Comment by magento-engcom-team** [comment] 2018-10-15 12:41
Hi @LordHansolo. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@LordHansolo do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by anujwebkul** [comment] 2018-10-26 16:17
#SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment] 2018-10-26 16:17
@anujwebkul thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment] 2018-10-26 16:18
Hi @anujwebkul. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by sidolov** [comment] 2018-11-06 18:06
Hi @LordHansolo. Thank you for your report. 
The issue has been fixed in magento/magento2#18650 by @anujwebkul in 2.3-develop branch
Related commit(s):
 - [11290c5d74cb2a9878735fac7dd4648d1923f71c](https://github.com/magento/magento2/commit/11290c5d74cb2a9878735fac7dd4648d1923f71c)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by sidolov** 2018-11-06 18:06 UTC
Labels: Fixed in 2.3.x, Issue: Format is valid, Event: squashtoberfest
