### ISSUE TITLE
Show/hide editor and insert veriable seems mismatch

### ISSUE THREAD

**Issue by cena4438** [magento/magento2#34401] opened 2021-10-21 12:42 UTC
Show/hide editor and insert veriable seems mismatch 

### Preconditions (*)

1. Magento 2.4
2.

### Steps to reproduce (*)

1. Admin - Newsletters templates - add new
2. Click show/hide editor

### Expected result (*)
![image](https://user-images.githubusercontent.com/92792212/138278276-583fe475-bf8b-4f40-b6d3-18338e24c3fe.png)

### Actual result (*)
![image](https://user-images.githubusercontent.com/92792212/138278318-574d226b-bcf6-4342-a04d-e47d86a6071e.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Melnychuk-Alexandr** [comment] 2022-01-06 14:05
Hi @cena4438 ! What screen width did you reproduce this problem ? Which browser ?

**Comment by engcom-Bravo** [comment] 2024-09-05 05:45
Hi @cena4438,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="1375" alt="Screenshot 2024-09-05 at 11 14 30" src="https://github.com/user-attachments/assets/88271891-7244-485d-9f08-1fb4ca3788e1">


Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-09-05 05:45 UTC
Labels: Issue: Confirmed, Component: Widget, Reproduced on 2.4.x, Severity: S4, Priority: P4, Progress: done, Issue: ready for confirmation, Area: Admin UI
