### ISSUE TITLE
Saved Vault Payment Methods are not available

### ISSUE THREAD

**Issue by devsigh** [magento/magento2#29248] opened 2020-07-23 20:05 UTC
### Preconditions (*)
1. At least Magento 2.3.5
2. A Vault-enabled payment method (Tested with the core installation of module-braintree and our in house module same issue)

### Steps to reproduce (*)
1. Configure a Vaulted Payment Method and Checkout opting to store the payment details for future use
2. Return and select one of the stored vaulted payment methods. 

### Expected result (*)
1. Method should be selected with no errors.
2.

### Actual result (*)
1. An API HTTP/HTTPS request is made in the background to set-payment-information returning HTTP 400 (Payment Method Unavailable)
2. module-sales-rule/view/frontend/web/js/action/select-payment-method-mixin.js triggers the set-payment-information request this is not present on 2.3.4 or below. By removing this from the requirejs-config the error indicated in 1. does not occur and the checkout process from a vault perspective appears to operate correctly.  

When the request reaches the server, it is sending over payment method including the vault reference eg braintree_vault_3, which in turn is validated against the quote as being an available payment method. Since its the main module eg (braintree) which is the payment method. (Seems to have been introduced here https://github.com/magento/magento2/commit/dac83def7ac97a184fe5f3cad77116b2b2221015#diff-aa8b012e2fbfb8f3c2904b7ea0504606)
 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by 0xMatt** [comment] 2020-09-09 03:04
Any update on this?

**Comment by j-lloyd-slc** [comment] 2020-11-19 16:03
Also occurs in 2.4.1

**Comment by deepakgupta28** [comment] 2020-11-26 09:55
Hi Team,

any update on this issue its brantree vault issue appear in 2.4.1.

thanks

**Comment by PromInc** [comment] 2021-01-05 20:47
I agree that this is an issue in 2.4.1
Of note, I have 3 vaulted cards saved to my customer account via Braintree.

In Javascript, it uses the vaulted payment methods ID to know which radio button was selected and thus to show the pay button for.
https://github.com/magento/magento2/blob/445b0f1a3d6a91b5da32d311077c2112ef0b1503/app/code/Magento/Vault/view/frontend/web/js/view/payment/method-renderer/vault.js#L37
Example: `braintree_cc_vault_114511`

The issue though is that this _unique_ ID gets passed to PHP which is expecting a more generic payment method like `braintree_cc_vault`

In my opinion, the core solution would be to do the following:

In `Magento/Vault/view/frontend/web/js/view/payment/method-renderer/vault.js` on line 38 add:
```
code: this.getCode()
```
Then in Magento\Quote\Model\Quote\Payment::importData` at the top of the function add this:

 ```
if( !empty( $data['code'] ) ) {
    $data['method'] = $data['code'];
}
```

This solution allows Javascript to have the information it needs and provides PHP with the information it needs to _map_ the data correctly on the backend.

---

In an effort to modify as little core code as possible however, I'm personally using a slightly different method for my implementation until this nasty bug is fixed in core.

I created a plugin to run right before the `importData` function.  I'm using regex to detect this scenario and then modify `$data['method']` to be the _code_ that Magento is expecting.


File: `app/code/Prominc/Quote/Plugin/Model/Quote/Payment.php`
```
<?php

namespace Prominc\Quote\Plugin\Model\Quote;

class Payment
{

    public function beforeImportData(
        \Magento\Quote\Model\Quote\Payment $subject,
        $data
    ) {
        $vaultMethod = preg_replace( '/^([a-z_]+vault)_\d+$/i', '$1', $data['method'] );
        if( !is_null( $vaultMethod ) && $vaultMethod !== $data['method'] ) {
            $data['method'] = $vaultMethod;
        }
        return [$data];
    }

}
```

You of course need to declare the module and plugin as well.

**Comment by PromInc** [comment] 2021-03-23 13:20
I do not see this issue in Magento v2.4.2 Open Source and thus am personally reverting my patch/plugin motioned above.

**Comment by engcom-Alfa** [comment] 2021-06-08 12:47
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment] 2021-06-11 12:48
Hi @devsigh 
I have tried to reproduce the issue in Magento 4.2-develop version and it is not reproducible.
Kindly upgrade to the latest version and try. Still if you find the same issue again in the latest version, kindly update with all the information relevant to it like- the configuration done and the saved procedure and/or anything relevant to the issue, that helps to reproduce. Possibly screen records and/or screen shots as well.

Below is the screen record that I couldn't reproduce.
https://user-images.githubusercontent.com/51679138/121688553-388ab980-cae1-11eb-9bde-e1f3548df052.mp4

**Comment by engcom-Alfa** [comment] 2021-06-25 12:55
As there is no response to my last comment in last ~14 days, closing this current issue.

Kindly upgrade to the latest version to re test. In case of any Magento related issues, you may please report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings possibly.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).

**Closed as completed by engcom-Alfa** 2021-06-25 12:55 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.3.5
