### ISSUE TITLE
Chrome Admin Login fails

### ISSUE THREAD

**Issue by michaeltimm81** [magento/magento2#781] opened 2014-12-05 12:02 UTC
Trying to login into admin via Chrome fails with no error message.

In Magento 1 disabling 
``system config -> web -> default cookie settings -> use HTTP only`` fixed this issue, but in Magento 2 this option seems to have no effect.

**Comment by michaeltimm81** [comment] 2015-01-16 16:26
Works :)

**Comment by maksek** [comment] 2015-01-20 15:59
Awesome,  closing the issue, feel free to reopen in case if it will occur again

**Comment by michaeltimm81** [comment] 2015-02-06 10:45
The issue is back. Changing the base url to 127.0.0.1 doesn't fix this anymore, with localhost there is no cookie set at all. With 127.0.0.1 there is only a form_key cookie set, but no admin cookie.

**Comment by eskaliert** [comment] 2015-06-24 20:46
Yep. I also got this issue loggin in Chrome.

**Comment by vpelipenko** [comment] 2015-07-01 16:34
Internal ticket: MAGETWO-39582

**Comment by maskeyarun** [comment] 2015-09-08 16:45
I had this issue. I had to made the database connection of "localhost" to "127.0.0.1". I don't know how that really mattered and resolved internally.

**Comment by vancoz** [comment] 2015-10-08 21:29
Hello @maskeyarun, @eskaliert  and @michaeltimm81 

I have tried to reproduce the issue, used localhost, 127.0.0.1, magento.loc and different db connection settings (and I would like to assure you that connection settings can not impact authentication, if you application able to connect and have access to DB). And I can not reproduce this issue (except localhost case).

So problem with localhost described in this post http://alankent.me/2015/04/25/use-of-localhost-when-installing-magento-2-quick-note/. Currently Magento does not support  not fully qualified domain names.

I found only one possible configuration problems that can be reason of this issue. Probably you have set localhost in Magento config. Please check core_config_data table, web/unsecure/base_url and web/secure/base_url values. In this case does not meter which url used to access admin panel, it will redirect you to localhost.

If this is not the case, please provide me more details how to reproduce the issue:
1. app/etc/env.php file
2. dump of core_config_data table
3. what exactly domain do you use

Thank you

**Comment by Vasimkadiwala** [comment] 2015-10-27 18:07
Trying to Login to Admin panel(Magento 2) with chrome failed with no error message 
with firefox its working fine

1.Tried different domain name instead of local host 
2. Tried disabling system config -> web -> default cookie settings -> use HTTP only

But No luck

**Comment by deepthi743** [comment] 2015-11-30 06:37
I had an issue while logging in to admin panel from firefox. It says that Username or Password is wrong  or account is currently disabled. I tried to correct some of source codes but doesn't work.Any solution for this??

**Comment by mazhalai** [comment] 2015-12-31 15:27
@michaeltimm81 has your issue been resolved? Have you followed @vancoz's [suggestion above](https://github.com/magento/magento2/issues/781#issuecomment-146691333)

**Comment by sshrewz** [comment] 2016-02-23 20:06
@michaeltimm81, since we have not heard from you for quite some time, we will go ahead and close this issue.  In case you have any further questions, don't hesitate to reopen.

**Closed by sshrewz** 2016-02-23 20:06 UTC
Labels: acknowledged, bug, PS
