### ISSUE TITLE
Group_Id set to default if saving account information

### ISSUE THREAD

**Issue by reply-jpetersen** [magento/magento2#26908] opened 2020-02-18 12:33 UTC
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Create a user account
2. Change customer group to differnent than default group
3. Login with user account
4. Save contact information in customer account

### Expected result (*)

1. Contact information are saved and the customer is still assigned to the assigned customer group

### Actual result (*)

1. Contact information are saved but the customer account is now assigned to the default customer group

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/Model/CustomerExtractor.php#L88

Related: https://github.com/magento/magento2/pull/23764

**Comment by reply-jpetersen** [comment] 2020-02-18 12:34
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-18 12:34
Hi @reply-jpetersen. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-18 12:34
Hi @reply-jpetersen, here is your [Magento instance](https://i-26908-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26908-2-4-develop.instances.magento-community.engineering/admin_7dcc](https://i-26908-2-4-develop.instances.magento-community.engineering/admin_7dcc)
Login: `ecc0db69` Password: `8c0b63e2f449`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2020-02-19 04:49
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31656` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by floplus** [comment] 2020-02-19 17:22
Same problem exists in the adminhtml_customer form, btw...

**Comment by Tomasz-Silpion** [comment] 2020-04-26 23:49
@sdzhepa what about this pull request? I can confirm the issue exists and @vishal-7037 patch resolves it. Problem seems to be relevant to 2.4-develop branch and looks like it was caused by ENGCOM-5728 https://github.com/magento/magento2/commit/c5c5f393814e3a89a4f0e0e880a50c8b0dfdc479

**Comment by MagePsycho** [comment] 2020-05-23 04:13
This is also reproduced in Magento 2.3.5, FYI.

**Comment by CarmineDamore78** [comment] 2020-05-26 06:49
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-26 06:49
Hi @CarmineDamore78. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-05-26 06:50
Hi @CarmineDamore78, here is your [Magento instance](https://i-26908-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26908-2-4-develop.instances.magento-community.engineering/admin_cc0f](https://i-26908-2-4-develop.instances.magento-community.engineering/admin_cc0f)
Login: `80035028` Password: `f3429e277c7c`
Instance will be terminated in up to 3 hours.

**Comment by CarmineDamore78** [comment] 2020-05-26 07:13
@magento, @magento-admin The issue is not reproducible on M2.4-develop

**Comment by pixiemediaweb** [comment] 2020-05-27 16:43
For anyone looking for a quick fix to this;

File: Magento\Customer\Model\CustomerExtractor

Line 83'ish, change;

$isGroupIdEmpty = !isset($allowedAttributes['group_id']);

To;

$isGroupIdEmpty = !isset($customerData['group_id']);

**Comment by AbdulRahmanAbouzaid** [comment] 2020-05-28 14:02
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-28 14:03
Hi @AbdulRahmanAbouzaid. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by engcom-Echo** [comment] 2020-06-02 14:18
The issue is not reproducible on M2.4-develop

**Closed as completed by engcom-Echo** 2020-06-02 14:18 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: User, Priority: P3, Severity: S3, Triage: Done, Progress: done, Reported on 2.3.4

**Comment by franconicolasocchi** [comment] 2020-09-15 23:58
Still present in 2.4.0.

**Comment by lewisvoncken** [comment] 2020-11-09 09:03
please fix! This fix works
https://github.com/magento/magento2/pull/26958/files

**Comment by hostep** [comment] 2020-11-09 11:15
@lewisvoncken: the PR you reference got closed because they said it was fixed in [MC-33554: B2B - Customer Group Resets to Default (General) whenever the customer saves their account](https://github.com/magento/magento2/commit/a3af65675c2f9d507d62d8619ae18377ee6b2709) which is included in Magento 2.4.1

Can you confirm that the issue got fixed in 2.4.1 ?
