### ISSUE TITLE
Some JS removes State/Province field for United Kingdom for example

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#25350] opened 2019-10-29 13:21 UTC
### Preconditions (*)

Magento 2.3-develop and 2.4-develop
1. Create Customer

### Steps to reproduce (*)

1. Click Address Book
2. Select the United Kingdom as a country
3. Set Postcode to AB12 3CD
4. Set State/Province to Greater London
5. Set City to London
6. Save address.
7. Verify that you see "Greater London" in Default Shipping and Default Billing address
8. Click Change Billing Address

### Expected result (*)

1. Greater London is in the State/Province input

### Actual result (*)

1. Some JS removes the State/Province field and the field is empty

### Additional information 
Issue still actual for 2.4-develop
![issue_25350](https://user-images.githubusercontent.com/3409584/83039127-5e8f0a00-a003-11ea-8633-063170a39106.gif)

**Comment by magento-engcom-team** [comment] 2019-10-30 08:25
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22563` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krzksz** [comment] 2019-11-21 20:27
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-21 20:27
Hi @krzksz. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-21 20:27
Hi @krzksz, here is your [Magento instance](https://i-25350-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25350-2-3-develop.instances.magento-community.engineering/admin](https://i-25350-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment] 2024-05-20 05:43
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-05-20 06:24
Hi @TomashKhamlai,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the attached video.


https://github.com/magento/magento2/assets/51680745/2a387cb4-2cea-46ca-8397-f1b9b6aedeac


Greater London is in the State/Province input


Hence We are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-05-20 06:24 UTC
Labels: Issue: Ready for Work, Component: Customer, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Reproduced on 2.4.x, Priority: P3, Severity: S2, Triage: Done, Progress: done
