### ISSUE TITLE
Unable to change locale not in PRO nor in DEV mode

### ISSUE THREAD

**Issue by rsulym** [magento/magento2#13387] opened 2018-01-26 13:23 UTC
Preconditions
Magento 2.2.1
PHP 7.0
Steps to reproduce
Install Magento 2 with a different locale than en_US
Go to Stores > Configuration > General
Try to change locale back to en_US (tried every single configuration store view)
Expected result
Be able to change default locale.

Actual result
The drop down box is grayed out and it is not possible to change locale. Switched back to DEV mode (cleared cache, redeployed content) - nothing changes, locale box is still grayed out.

Command 
bin/magento config:set --scope=store --scope-code=<Code> general/locale/code xx_XX
returns The "general/locale/code" path does not exist

**Comment by rsulym** [comment] 2018-01-26 13:51
actually:
`bin/magento config:show | grep locale
general/locale/code - uk_UA`

but:
`bin/magento config:set --scope=store --scope-code=furniture_store_view genetal/locale/code uk_UA
The "genetal/locale/code" path does not exist`

neverless, i guess i can change global locale value in config.php, but i need to change it for particular store view, not globally.

**Comment by rsulym** [comment] 2018-01-26 14:12
also interesting that in config.php locked these parameters:
`        'locale' =>
         array (
          'code' => 'uk_UA',
          'timezone' => 'Europe/Kiev',
          'weight_unit' => 'kgs',
          'firstday' => '1',`
but only locale code is grayed out, timezone, weight_unit and firstday is changeable...

**Comment by magento-engcom-team** [comment] 2018-02-07 14:46
Hi @rsulym 
We were not able to reproduce this issue by following the steps you provided.
My steps are here:
1. Install Magento 2.2.2 with Ukraine locale config (http://prntscr.com/ibexow) by setup wizard.
2. Go to Stores > Configuration > General and successfully change locale to "English US" (http://prntscr.com/ibeztr)

Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by hostep** [comment] 2018-02-07 16:25
@magento-engcom-team: try putting the store in production mode.

This is probably a duplicate of https://github.com/magento/magento2/issues/10377, so it's expected behavior, even though it's not very user friendly, especially for non-technical shop owners who try to use Magento.

@rsulym: you are talking about `genetal/locale/code` which contains a typo, it should be `general/locale/code`. If it still isn't working, then try adding the `--lock` flag to the `config:set` command.

**Comment by magento-engcom-team** [comment] 2018-02-08 08:37
@hostep
Indeed. Thanks!

Hi @rsulym
Please check discussion and solutions in #10377 and let us know if it is the same case
Thank you

**Comment by magento-engcom-team** [comment] 2018-02-14 14:30
@rsulym, we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Closed as completed by magento-engcom-team** 2018-02-14 14:30 UTC
Labels: Progress: needs update, Issue: Format is valid
