### ISSUE TITLE
Page refresh on subscribe for footer newsletter section

### ISSUE THREAD

**Issue by renard123** [magento/magento2#32632] opened 2021-03-31 05:44 UTC
Page refresh on subscribe for footer newsletter section

### Preconditions (*)

1. Magento 2.4
2.

### Steps to reproduce (*)

- As guest user add 2-3 products to cart 
- Shopping Cart 
- Click on Checkout with multiple addresses 
- Login page -> Click on Create an account button 
- Create an account page -> Footer -> Newsletter section
- Without enter email click on Subscribe button
- 
### Expected result (*)

Require validation should appear below email text field

### Actual result (*)

Page refresh and no validation message appear

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment] 2021-03-31 05:46
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41671` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ihor-sviziev** [comment] 2021-03-31 10:20
Hi @renard123,
This issue duplicates https://github.com/magento/magento2/issues/32629, as it happened on the same page and was caused by the same JS error https://github.com/magento/magento2/issues/32629#issuecomment-810950643.

I'm closing this issue as a duplicate

**Closed as completed by ihor-sviziev** 2021-03-31 10:20 UTC
Labels: duplicate, Issue: Confirmed, Component: Multishipping, Severity: S4, Priority: P4, Progress: done, Issue: ready for confirmation

**Comment by magento-engcom-team** [comment] 2021-03-31 10:22
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by ihor-sviziev** [comment] 2021-04-07 05:52
Hi,

This issue was fixed in https://github.com/magento/magento2/commit/461509df6db50edf65de181ecb7decc27519a748.
