### ISSUE TITLE
Special Price/Cost price being overwritten on product save in alternate storeview - price scope website

### ISSUE THREAD

**Issue by IanFiretoys** [magento/magento2#37579] opened 2023-06-05 13:57 UTC
### Preconditions and environment

- 2.4.5^
- multistore setup ( at least 2 separate trees of webite >store > storeview
- Price scope set to Website (not global) ( stores > configuration > Catalog > catalog > Price > Catalog Price scope )

### Steps to reproduce

1. open product
2. set special price in default storeview
3. save product
4. switch to secondary storeview
5. open advanced pricing and untick use default on special price
6. overwrite special price with blank entry
7. save product

### Expected result

special price field is set to empty, essentially removing it from that storeview

### Actual result

special price field is set back to "use default"

I would suspect this is an issue with the way empty decimals are being written to the DB, but other important front facing decimals (such as price) aren't able to be left blank.

the same issue occurs with cost price, so that confirms this.

### Additional information

this is a bug introduced in 2.4.5, it appears. so if you have an existing database with special prices set to empty in non-default storeviews, if you open and save **any product** in a non default storeview, regardless of whether you're changing the price. as soon as you hit save, that product will be using the default storeview's special price.

this is catastrophic in circumstances where 
a) currencies are different, as a 5% discount in GBP on the default storeview could end up as a 95% discount in JPY 
b) there is an expired special price in the default storeview, as the special price **dates** are unaffected. so if 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by IanFiretoys** [comment] 2023-06-05 15:50
currently our only way to set the special price back to blank is with update attributes, which presumably bypasses the save function of the regular product updates

**Comment by engcom-Bravo** [comment] 2023-06-06 07:11
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-06-06 15:33
Hi @IanFiretoys,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the attached video.


**Steps to reproduce**

- open product
- set special price in default storeview
- save product
- switch to secondary storeview
- open advanced pricing and untick use default on special price
- overwrite special price with blank entry
- save product


Even though we are updating special price for default store view the same price is updating in another store view and also when we untick the use default value and remove special price in another store view after saving it is again ticking the use default value automatically.


https://github.com/magento/magento2/assets/51680745/4cd32a48-444d-4435-b6c2-f9e56f021a66



Hence confirming this issue.

Thanks.

**Comment by aasim110** [comment] 2023-07-14 12:02
@magento I'm working on this

**Comment by Aditya-Prakash-Talluru** [comment] 2023-07-17 10:27
@magento give me 2.4-develop instance

**Comment by Aditya-Prakash-Talluru** [comment] 2023-07-17 12:08
@magento I have tried to reproduce the issue in the instance but i am unable to find the use default option under the special price in advance price option.

I followed all the steps as mentioned.


<img width="980" alt="Screenshot 2023-07-17 at 5 30 00 PM" src="https://github.com/magento/magento2/assets/139533953/7d186222-e3ac-484e-a04f-5e65708225f5">
<img width="1009" alt="Screenshot 2023-07-17 at 5 30 30 PM" src="https://github.com/magento/magento2/assets/139533953/479d6543-8884-472b-80a0-cec12ef07f0e">

**Comment by IanFiretoys** [comment] 2023-07-17 12:17
are you following the preconditions also? make sure that the store tree is set up correctly and you have price scope set to website.

**Comment by Aditya-Prakash-Talluru** [comment] 2023-07-28 07:20
@IanFiretoys I am able to reproduce the issue.

**Comment by Aditya-Prakash-Talluru** [comment] 2023-07-28 07:22
@magento I am working on this

**Comment by Aditya-Prakash-Talluru** [comment] 2023-07-28 07:22
@magento add to contributors team

**Comment by Aditya-Prakash-Talluru** [comment] 2023-07-28 07:23
@magento I am working on this

**Comment by Aditya-Prakash-Talluru** [comment] 2023-07-28 12:02
> pecial price field is set back to "use default"

@IanFiretoys @engcom-Bravo 

On creating a new product the and special price is not set then the value of the special price is set to null. 

On moving to the default store view of the product and checking the advance the price the advance price is already set null with respect to the all store view price. If we remove the default option and change the special price to a value and saving the product.  The same value can be view across all the stores and store views across the website because the scope is set to Website level so the value persists across the website.  

On moving to different website checking a store view the special price does not match with the default store view of the Main website.  For changing the price to null the default option is getting linked because 
[Special Price Advance Price.zip](https://github.com/magento/magento2/files/12194216/Special.Price.Advance.Price.zip)
the default price of all store views is null and that value is getting inherited.

In the above video new website is created

**Comment by Aditya-Prakash-Talluru** [comment] 2023-07-31 13:29
Creates Two Branches : Main Website->Main Website Store ->Default Store view
					->Main Website Store-> New Store View

			Main Website ->New store -> New Store View.

			Demo Test Website->Demo Store-> Demo Store view.	

<img width="192" alt="image" src="https://github.com/magento/magento2/assets/139533953/671b18e7-8383-4c51-abfe-5059239a10d1">

 		
On creating a new product the and special price is not set then the value of the special price is set to empty on all store view.

 
<img width="452" alt="image" src="https://github.com/magento/magento2/assets/139533953/352b5fc1-24a7-434a-8df0-01dd0e461272">


On changing the scope from all the store view to the main website-> main store –> default store view and checking the special price value is empty and default price option is ticked.

 
<img width="452" alt="image" src="https://github.com/magento/magento2/assets/139533953/6f7819a4-3f0d-4e3b-80a3-4c4ab390b18e">


 Same with different store view in same store and different store view in different store  the value is empty and default is ticked. 
Main Website ->Main Website Store-> New Store View
Main Website ->New store -> New Store View.


If we move to different website and check the store view which is an entirely new tree of Demo Test Website->Demo Store-> Demo Store view and we can see that the special price is set to empty and default price is ticked. 


In the scope of product moving to ain Website->Main Website Store ->Default Store view. We untick the default special price and put in a custom special price value and save it.

<img width="452" alt="image" src="https://github.com/magento/magento2/assets/139533953/30b7bfa7-9548-47c9-a6ab-a4dd7e9a8b5a">


 
The above same value is reflected across all the store views in that website.

On changing the scope to a different website Demo Test Website->Demo Store-> Demo Store view the price is empty and default value is ticked. This special price is not reflecting the value of the special price from the other website.

 
<img width="452" alt="image" src="https://github.com/magento/magento2/assets/139533953/2f4f968f-f417-43c2-b582-6ebcc98e24b6">


If the special price in the “All store view” is set then the default value of the these stores on empty will be set to that value as default value.
As the price is set to scope: website that seem to be working correct and by default the special price is set to all store view in case of empty for a particular store by adobe commerce.

**Comment by chittima** [comment] 2023-09-13 19:38
Internal team is working on this issue

**Comment by MagentoGuysProjects** [comment] 2023-12-01 07:23
Do we have any patch available to fix this issue as soon as possible? as we are facing the same issue on magento 2.4.6-p3 version as well.

**Comment by chittima** [comment] 2023-12-01 18:37
Hi @MagentoGuysProjects Here is the commit id: https://github.com/magento/magento2/commit/9d5edd1a322ded708dfed19e293b968fdc5b9a8c

**Comment by o-iegorov** [comment] 2023-12-01 18:59
Issue is not reproducible on 2.4-develop anymore, closing

**Closed as completed by o-iegorov** 2023-12-01 18:59 UTC
Labels: Issue: Confirmed, Component: Pricing, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Pricing, Reported on 2.4.5

**Comment by raulsinapsis** [comment] 2024-07-16 07:51
This is still happening in 2.4.6-p4
Not sure if the mentioned commit could fix this, as it seems to involve only admin visualization, but the problem is the data in database

We can't setSpecialPrice(null) programmatically in a concrete website if that product has a special_price value in default scope
