### ISSUE TITLE
Error when i try to get products/attributes

### ISSUE THREAD

**Issue by Andryel-Blanco** [magento/magento2#36432] opened 2022-11-07 19:48 UTC
### Preconditions and environment

- Magento 2.4
- Anything else that would help a developer reproduce the bug

When I make a request to https://kubaaudio.projeto.online/rest/V1/products/attributes?searchCriteria[currentPage]=1 I get the following return:
  "message": "Each method must have a doc block. See Magento\\Eav\\Api\\Data\\AttributeInterface::getIsUserDefined()",
 "trace": "#0 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Reflection/TypeProcessor.php(843): Magento\\Framework\\Reflection\\TypeProcessor->getReturnFromDocBlock(Object(Laminas\\Code\\Reflection\\MethodReflection))\n#1 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Reflection/TypeProcessor.php(287): Magento\\Framework\\Reflection\\TypeProcessor->getMethodReturnAnnotation(Object(Laminas\\Code\\Reflection\\MethodReflection))\n#2 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Reflection/MethodsMap.php(173): Magento\\Framework\\Reflection\\TypeProcessor->getGetterReturnType(Object(Laminas\\Code\\Reflection\\MethodReflection))\n#3 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Reflection/MethodsMap.php(108): Magento\\Framework\\Reflection\\MethodsMap->getMethodMapViaReflection('\\\\Magento\\\\Catalo...')\n#4 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Reflection/DataObjectProcessor.php(83): Magento\\Framework\\Reflection\\MethodsMap->getMethodsMap('\\\\Magento\\\\Catalo...')\n#5 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Framework\\Reflection\\DataObjectProcessor->buildOutputDataArray(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor), '\\\\Magento\\\\Catalo...')\n#6 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Framework\\Reflection\\DataObjectProcessor\\Interceptor->___callParent('buildOutputData...', Array)\n#7 /var/www/projeto.online/kubaaudio/vendor/mage2pro/core/Framework/Plugin/Reflection/DataObjectProcessor.php(18): Magento\\Framework\\Reflection\\DataObjectProcessor\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor), '\\\\Magento\\\\Catalo...')\n#8 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Interception/Interceptor.php(135): Df\\Framework\\Plugin\\Reflection\\DataObjectProcessor->aroundBuildOutputDataArray(Object(Magento\\Framework\\Reflection\\DataObjectProcessor\\Interceptor), Object(Closure), Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor), '\\\\Magento\\\\Catalo...')\n#9 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Framework\\Reflection\\DataObjectProcessor\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor), '\\\\Magento\\\\Catalo...')\n#10 /var/www/projeto.online/kubaaudio/generated/code/Magento/Framework/Reflection/DataObjectProcessor/Interceptor.php(26): Magento\\Framework\\Reflection\\DataObjectProcessor\\Interceptor->___callPlugins('buildOutputData...', Array, NULL)\n#11 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Reflection/DataObjectProcessor.php(121): Magento\\Framework\\Reflection\\DataObjectProcessor\\Interceptor->buildOutputDataArray(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor), '\\\\Magento\\\\Catalo...')\n#12 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Framework\\Reflection\\DataObjectProcessor->buildOutputDataArray(Object(Magento\\Eav\\Model\\AttributeSearchResults), '\\\\Magento\\\\Catalo...')\n#13 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Framework\\Reflection\\DataObjectProcessor\\Interceptor->___callParent('buildOutputData...', Array)\n#14 /var/www/projeto.online/kubaaudio/vendor/mage2pro/core/Framework/Plugin/Reflection/DataObjectProcessor.php(18): Magento\\Framework\\Reflection\\DataObjectProcessor\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Eav\\Model\\AttributeSearchResults), '\\\\Magento\\\\Catalo...')\n#15 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Interception/Interceptor.php(135): Df\\Framework\\Plugin\\Reflection\\DataObjectProcessor->aroundBuildOutputDataArray(Object(Magento\\Framework\\Reflection\\DataObjectProcessor\\Interceptor), Object(Closure), Object(Magento\\Eav\\Model\\AttributeSearchResults), '\\\\Magento\\\\Catalo...')\n#16 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Framework\\Reflection\\DataObjectProcessor\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Eav\\Model\\AttributeSearchResults), '\\\\Magento\\\\Catalo...')\n#17 /var/www/projeto.online/kubaaudio/generated/code/Magento/Framework/Reflection/DataObjectProcessor/Interceptor.php(26): Magento\\Framework\\Reflection\\DataObjectProcessor\\Interceptor->___callPlugins('buildOutputData...', Array, NULL)\n#18 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Webapi/ServiceOutputProcessor.php(126): Magento\\Framework\\Reflection\\DataObjectProcessor\\Interceptor->buildOutputDataArray(Object(Magento\\Eav\\Model\\AttributeSearchResults), '\\\\Magento\\\\Catalo...')\n#19 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Webapi/ServiceOutputProcessor.php(78): Magento\\Framework\\Webapi\\ServiceOutputProcessor->convertValue(Object(Magento\\Eav\\Model\\AttributeSearchResults), '\\\\Magento\\\\Catalo...')\n#20 /var/www/projeto.online/kubaaudio/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(97): Magento\\Framework\\Webapi\\ServiceOutputProcessor->process(Object(Magento\\Eav\\Model\\AttributeSearchResults), 'Magento\\\\Catalog...', 'getList')\n#21 /var/www/projeto.online/kubaaudio/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process(Object(Magento\\Framework\\Webapi\\Rest\\Request\\Proxy))\n#22 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#23 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch', Array)\n#24 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#25 /var/www/projeto.online/kubaaudio/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(26): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)\n#26 /var/www/projeto.online/kubaaudio/vendor/magento/framework/App/Http.php(116): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#27 /var/www/projeto.online/kubaaudio/vendor/magento/framework/App/Bootstrap.php(261): Magento\\Framework\\App\\Http->launch()\n#28 /var/www/projeto.online/kubaaudio/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#29 {main}"
}

### Steps to reproduce

The URL :  https://kubaaudio.projeto.online/rest/V1/products/attributes?searchCriteria[currentPage]=1

### Expected result

{
"extension_attributes": {
"is_pagebuilder_enabled": true
},
"is_wysiwyg_enabled": true,
"is_html_allowed_on_front": true,
"used_for_sort_by": true,
"is_filterable": true,
"is_filterable_in_search": true,
"is_used_in_grid": true,
"is_visible_in_grid": true,
"is_filterable_in_grid": true,
"position": 0,
"apply_to": [
"string"
],
"is_searchable": "string",
"is_visible_in_advanced_search": "string",
"is_comparable": "string",
"is_used_for_promo_rules": "string",
"is_visible_on_front": "string",
"used_in_product_listing": "string",
"is_visible": true,
"scope": "string",
"attribute_id": 0,
"attribute_code": "string",
"frontend_input": "string",
"entity_type_id": "string",
"is_required": true,
"options": [
{}
],
"is_user_defined": true,
"default_frontend_label": "string",
"frontend_labels": [
{}
],
"note": "string",
"backend_type": "string",
"backend_model": "string",
"source_model": "string",
"default_value": "string",
"is_unique": "string",
"frontend_class": "string",
"validation_rules": [
{}
],
"custom_attributes": [
{}
]
}

### Actual result

{
    "message": "Each method must have a doc block. See Magento\\Eav\\Api\\Data\\AttributeInterface::getIsUserDefined()",
    "trace": "#0 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Reflection/TypeProcessor.php(843): Magento\\Framework\\Reflection\\TypeProcessor->getReturnFromDocBlock(Object(Laminas\\Code\\Reflection\\MethodReflection))\n#1 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Reflection/TypeProcessor.php(287): Magento\\Framework\\Reflection\\TypeProcessor->getMethodReturnAnnotation(Object(Laminas\\Code\\Reflection\\MethodReflection))\n#2 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Reflection/MethodsMap.php(173): Magento\\Framework\\Reflection\\TypeProcessor->getGetterReturnType(Object(Laminas\\Code\\Reflection\\MethodReflection))\n#3 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Reflection/MethodsMap.php(108): Magento\\Framework\\Reflection\\MethodsMap->getMethodMapViaReflection('\\\\Magento\\\\Catalo...')\n#4 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Reflection/DataObjectProcessor.php(83): Magento\\Framework\\Reflection\\MethodsMap->getMethodsMap('\\\\Magento\\\\Catalo...')\n#5 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Framework\\Reflection\\DataObjectProcessor->buildOutputDataArray(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor), '\\\\Magento\\\\Catalo...')\n#6 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Framework\\Reflection\\DataObjectProcessor\\Interceptor->___callParent('buildOutputData...', Array)\n#7 /var/www/projeto.online/kubaaudio/vendor/mage2pro/core/Framework/Plugin/Reflection/DataObjectProcessor.php(18): Magento\\Framework\\Reflection\\DataObjectProcessor\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor), '\\\\Magento\\\\Catalo...')\n#8 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Interception/Interceptor.php(135): Df\\Framework\\Plugin\\Reflection\\DataObjectProcessor->aroundBuildOutputDataArray(Object(Magento\\Framework\\Reflection\\DataObjectProcessor\\Interceptor), Object(Closure), Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor), '\\\\Magento\\\\Catalo...')\n#9 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Framework\\Reflection\\DataObjectProcessor\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor), '\\\\Magento\\\\Catalo...')\n#10 /var/www/projeto.online/kubaaudio/generated/code/Magento/Framework/Reflection/DataObjectProcessor/Interceptor.php(26): Magento\\Framework\\Reflection\\DataObjectProcessor\\Interceptor->___callPlugins('buildOutputData...', Array, NULL)\n#11 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Reflection/DataObjectProcessor.php(121): Magento\\Framework\\Reflection\\DataObjectProcessor\\Interceptor->buildOutputDataArray(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor), '\\\\Magento\\\\Catalo...')\n#12 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Framework\\Reflection\\DataObjectProcessor->buildOutputDataArray(Object(Magento\\Eav\\Model\\AttributeSearchResults), '\\\\Magento\\\\Catalo...')\n#13 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Framework\\Reflection\\DataObjectProcessor\\Interceptor->___callParent('buildOutputData...', Array)\n#14 /var/www/projeto.online/kubaaudio/vendor/mage2pro/core/Framework/Plugin/Reflection/DataObjectProcessor.php(18): Magento\\Framework\\Reflection\\DataObjectProcessor\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Eav\\Model\\AttributeSearchResults), '\\\\Magento\\\\Catalo...')\n#15 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Interception/Interceptor.php(135): Df\\Framework\\Plugin\\Reflection\\DataObjectProcessor->aroundBuildOutputDataArray(Object(Magento\\Framework\\Reflection\\DataObjectProcessor\\Interceptor), Object(Closure), Object(Magento\\Eav\\Model\\AttributeSearchResults), '\\\\Magento\\\\Catalo...')\n#16 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Framework\\Reflection\\DataObjectProcessor\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Eav\\Model\\AttributeSearchResults), '\\\\Magento\\\\Catalo...')\n#17 /var/www/projeto.online/kubaaudio/generated/code/Magento/Framework/Reflection/DataObjectProcessor/Interceptor.php(26): Magento\\Framework\\Reflection\\DataObjectProcessor\\Interceptor->___callPlugins('buildOutputData...', Array, NULL)\n#18 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Webapi/ServiceOutputProcessor.php(126): Magento\\Framework\\Reflection\\DataObjectProcessor\\Interceptor->buildOutputDataArray(Object(Magento\\Eav\\Model\\AttributeSearchResults), '\\\\Magento\\\\Catalo...')\n#19 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Webapi/ServiceOutputProcessor.php(78): Magento\\Framework\\Webapi\\ServiceOutputProcessor->convertValue(Object(Magento\\Eav\\Model\\AttributeSearchResults), '\\\\Magento\\\\Catalo...')\n#20 /var/www/projeto.online/kubaaudio/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(97): Magento\\Framework\\Webapi\\ServiceOutputProcessor->process(Object(Magento\\Eav\\Model\\AttributeSearchResults), 'Magento\\\\Catalog...', 'getList')\n#21 /var/www/projeto.online/kubaaudio/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process(Object(Magento\\Framework\\Webapi\\Rest\\Request\\Proxy))\n#22 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#23 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch', Array)\n#24 /var/www/projeto.online/kubaaudio/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#25 /var/www/projeto.online/kubaaudio/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(26): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)\n#26 /var/www/projeto.online/kubaaudio/vendor/magento/framework/App/Http.php(116): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#27 /var/www/projeto.online/kubaaudio/vendor/magento/framework/App/Bootstrap.php(261): Magento\\Framework\\App\\Http->launch()\n#28 /var/www/projeto.online/kubaaudio/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#29 {main}"
}

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-11-08 04:34
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-10 06:38
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-10 07:22
Hi @Andryel-Blanco ,

Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance but the issue is not reproducible.
No errors/exceptions are observed when trying to get the response for above mentioned API. Status code response: 200 OK
Kindly recheck the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base. Also check if any 3rd party extensions enabled is causing the issue and elaborate steps / configuration details if the issue is still reproducible.
Thank you.

<img width="737" alt="Screenshot 2022-11-10 at 12 48 12 PM" src="https://user-images.githubusercontent.com/51680745/201025883-58ce1eb7-38cf-4af7-ae84-6cff4377ada5.png">

**Comment by engcom-November** [comment] 2022-11-24 06:14
Hi @Andryel-Blanco ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-11-24 06:14 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.x
