### ISSUE TITLE
Magento 2.3.4 - Mageplaza SMTP - Not able to send order confirmation email to gmx, web.de, etc.

### ISSUE THREAD

**Issue by Stoppl** [magento/magento2#30226] opened 2020-09-29 06:15 UTC
### Preconditions (*)

1. Magento 2.3.4.
2. Mageplaza SMTP-Pro Extension

### Steps to reproduce (*)

1. Customer placed an order
2. The email adress sounds like test@gmx.de or test@web.de
3. After the order was placed, magento should send an order confirmation email

### Expected result (*)

1. The customer should get an order confirmation email

### Actual result (*)

The order confirmation email could not be delivered.
We are getting a bounce like this:

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

test@gmx.net
    host mx01.emig.gmx.net [IP.ADR.ESS.GMX]
    SMTP error from remote mail server after end of data:
    554-Transaction failed
    554-Reject due to policy restrictions.
    554 For explanation visit https://www.gmx.net/mail/senderguidelines?ip=80.67.31.40&c=hi

I´ve talked to an administrator of GMX (https://www.gmx.net/) and he told me, that the email header is incorrect.

--XXX-eximdsn-XXX
Content-type: message/delivery-status

Reporting-MTA: dns; smtprelay08.XXX.de

Action: failed
Final-Recipient: rfc822;test@gmx.net
Status: 5.0.0
Remote-MTA: dns; mx00.emig.gmx.net
Diagnostic-Code: smtp; 554-Transaction failed
 554-Reject due to policy restrictions.
 554 For explanation visit https://www.gmx.net/mail/senderguidelines?ip=134.119.228.98&c=hi

--XXX-eximdsn-XXX
Content-type: text/rfc822-headers

Return-path: <service@our-domain.de>
Received: from [our.ip.adress.here] (helo=localhost)
        by smtprelay08.XXX.de with esmtpsa (TLSv1.2:XXXXXX-XXX-XXX-SHA256:128)
        (Exim XXX.XXXXXX)
        (envelope-from <service@our-domain.de>)
        id XXX-XXX
        for test@gmx.net; Mon, 28 Sep 2020 **14:32:38 +0200**
Date: Mon, 28 Sep 2020 **12:34:55 +0000**
MIME-Version: 1.0
Content-Type: text/html;
 charset="utf-8"
Content-Transfer-Encoding: quoted-printable
Subject: =?utf-8?Q?Bestellbest=C3=A4tigung=20f=C3=BCr=20Ihre=20Bestellung=20bei=20?=
 =?utf-8?Q?Our=20Company=20GmbH=20&=20Co.=20KG?=
To: =?utf-8?Q?TEST=20TEST?= <test@gmx.net>
From: =?utf-8?Q?service@our-domain.de?= <service@our-domain.de>
Message-Id: <XXX-XXX@smtprelay08.XXX.de>
X-Df-Sender: XXXXXXXXXXX

--XXX-eximdsn-XXX--

Our order confirmation was sent on

Mon, 28 Sep 2020 **14:32:38 +0200**

But in the email header there is an wrong time and timezone

Mon, 28 Sep 2020 **12:34:55 +0000**

**Comment by ihor-sviziev** [comment] 2020-09-29 07:12
Hi @Stoppl,
Thank you for your report!
Seems like this is the issue in the custom extension that you're using. Please contact vendor that develop it instead.

I'm closing this issue as it was caused by custom extension.

**Closed as completed by ihor-sviziev** 2020-09-29 07:12 UTC
Labels: Issue: Format is valid, Progress: done, Reported on 2.3.4
