### ISSUE TITLE
Injecting Product\Action into Console Command breaks setup:install

### ISSUE THREAD

**Issue by bobemoe** [magento/magento2#31465] opened 2020-12-26 15:57 UTC
### Preconditions (*)
1. Magento 2.4.1 CE (reproducible on 2.4-develop)
2. MariaDB 10.3
3. PHP 7.4.13
4. Linux 4.9.0-6-amd64 # 1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

Inject `\Magento\Catalog\Model\ResourceModel\Product\Action` into a Console Command constructor, or get instance from Object Manager in constructor causes this error.

### Steps to reproduce (*)
1. Clean install magento `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition magento 2.4.1`
2. Install my test module: `git clone https://git.jhodges.co.uk/jhodges/Magento_Test.git app/code/Test/Test/`
3. Try and install magento `bin/magento setup:install`

### Expected result (*)
1. Magento installs

### Actual result (*)
1. Error is thrown:
```
[Progress: 4 / 1338]
Installing database schema:

In Mysql.php line 597:
                                                                               
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.eav_entity_type' doesn't exist, query was: SELECT `main_table`.* FROM `eav_entity_type` AS `main_table` In Mysql.php line 110:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.eav_entity_type' doesn't exist, query was: SELECT `main_table`.* FROM `eav_entity_type` AS `main_table` In Mysql.php line 91:
                                                                               
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.eav_entity_type' doesn't exist                                                       
```

### Workaround

Workaround is to get instance of `\Magento\Catalog\Model\ResourceModel\Product\Action` from Object Manager in execute function.

Repeat the steps to reproduce above, but in step 2 clone the **workaround** branch of my test module `git clone --branch workaround https://git.jhodges.co.uk/jhodges/Magento_Test.git app/code/Test/Test/`

Then `setup:install` goes fine and you can confirm with `bin/magento test:test` should output `Magento\Catalog\Model\ResourceModel\Product\Action\Interceptor`

### Logs:

```
[2020-12-26 15:09:56] main.ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.eav_entity_type' doesn't exist, query was: SELECT `main_table`.* FROM `eav_entity_type` AS `main_table`
#0 /var/www/magento/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(625): Magento\Framework\DB\Adapter\Pdo\Mysql->_query()
#1 /var/www/magento/generated/code/Magento/Framework/DB/Adapter/Pdo/Mysql/Interceptor.php(95): Magento\Framework\DB\Adapter\Pdo\Mysql->query()
#2 /var/www/magento/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(737): Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->query()
#3 /var/www/magento/generated/code/Magento/Framework/DB/Adapter/Pdo/Mysql/Interceptor.php(1085): Zend_Db_Adapter_Abstract->fetchAll()
#4 /var/www/magento/vendor/magento/framework/Data/Collection/Db/FetchStrategy/Query.php(21): Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->fetchAll()
#5 /var/www/magento/vendor/magento/framework/Data/Collection/AbstractDb.php(782): Magento\Framework\Data\Collection\Db\FetchStrategy\Query->fetchAll()
#6 /var/www/magento/vendor/magento/framework/Data/Collection/AbstractDb.php(677): Magento\Framework\Data\Collection\AbstractDb->_fetchAll()
#7 /var/www/magento/generated/code/Magento/Eav/Model/ResourceModel/Entity/Type/Collection/Interceptor.php(320): Magento\Framework\Data\Collection\AbstractDb->getData()
#8 /var/www/magento/vendor/magento/module-eav/Model/Config.php(389): Magento\Eav\Model\ResourceModel\Entity\Type\Collection\Interceptor->getData()
#9 /var/www/magento/vendor/magento/module-eav/Model/Config.php(428): Magento\Eav\Model\Config->_initEntityTypes()
#10 /var/www/magento/vendor/magento/module-eav/Model/Entity/AbstractEntity.php(322): Magento\Eav\Model\Config->getEntityType()
#11 /var/www/magento/generated/code/Magento/Catalog/Model/ResourceModel/Product/Action/Interceptor.php(86): Magento\Eav\Model\Entity\AbstractEntity->setType()
#12 /var/www/magento/vendor/magento/module-catalog/Model/ResourceModel/Product/Action.php(92): Magento\Catalog\Model\ResourceModel\Product\Action\Interceptor->setType()
#13 /var/www/magento/vendor/magento/framework/Model/ResourceModel/AbstractResource.php(42): Magento\Catalog\Model\ResourceModel\Product\Action->_construct()
#14 /var/www/magento/vendor/magento/module-eav/Model/Entity/AbstractEntity.php(245): Magento\Framework\Model\ResourceModel\AbstractResource->__construct()
#15 /var/www/magento/vendor/magento/module-catalog/Model/ResourceModel/AbstractResource.php(56): Magento\Eav\Model\Entity\AbstractEntity->__construct()
#16 /var/www/magento/vendor/magento/module-catalog/Model/ResourceModel/Product/Action.php(76): Magento\Catalog\Model\ResourceModel\AbstractResource->__construct()
#17 /var/www/magento/generated/code/Magento/Catalog/Model/ResourceModel/Product/Action/Interceptor.php(14): Magento\Catalog\Model\ResourceModel\Product\Action->__construct()
#18 /var/www/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Catalog\Model\ResourceModel\Product\Action\Interceptor->__construct()
#19 /var/www/magento/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#20 /var/www/magento/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#21 /var/www/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get()
#22 /var/www/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#23 /var/www/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#24 /var/www/magento/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#25 /var/www/magento/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments()
#26 /var/www/magento/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#27 /var/www/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(206): Magento\Framework\ObjectManager\ObjectManager->get()
#28 /var/www/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(182): Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray()
#29 /var/www/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#30 /var/www/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#31 /var/www/magento/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#32 /var/www/magento/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments()
#33 /var/www/magento/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#34 /var/www/magento/setup/src/Magento/Setup/Model/ObjectManagerProvider.php(78): Magento\Framework\ObjectManager\ObjectManager->create()
#35 /var/www/magento/setup/src/Magento/Setup/Model/ObjectManagerProvider.php(64): Magento\Setup\Model\ObjectManagerProvider->createCliCommands()
#36 /var/www/magento/setup/src/Magento/Setup/Model/Installer.php(882): Magento\Setup\Model\ObjectManagerProvider->get()
#37 [internal function]: Magento\Setup\Model\Installer->installSchema()
#38 /var/www/magento/setup/src/Magento/Setup/Model/Installer.php(388): call_user_func_array()
#39 /var/www/magento/setup/src/Magento/Setup/Console/Command/InstallCommand.php(231): Magento\Setup\Model\Installer->install()
#40 /var/www/magento/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\InstallCommand->execute()
#41 /var/www/magento/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#42 /var/www/magento/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#43 /var/www/magento/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun()
#44 /var/www/magento/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()
#45 /var/www/magento/bin/magento(23): Symfony\Component\Console\Application->run()
#46 {main} [] []
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2020-12-28 12:23
Hello @bobemoe 

Thank you for your report.

Looks like the described issue is in the 3rd party Module. The Magento Issues board is created for core Magento issues, and we do not handle 3rd party extensions or Modules. 

We are closing this issue. Please feel free to comment, or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by bobemoe** [comment] 2020-12-28 12:26
Hi, actually I created the module specifically to demonstrate this issue. All it does it wrap together the steps to reproduce. You should be able to reproducte this issue on clean magento by creating your own Console Command and injecting the `\Magento\Catalog\Model\ResourceModel\Product\Action` as described.

**Comment by bobemoe** [comment] 2020-12-28 12:27
Please reopen or I will create exact same issue but just describe the code rather than providing it.

**Comment by engcom-Bravo** [comment] 2020-12-28 13:12
@bobemoe Thank you for the quick response.

We have just taken another look at this issue. We Confirm that it is a valid issue and is reproducible on the latest 2.4-develop.

Thank you

**Comment by magento-engcom-team** [comment] 2020-12-28 13:15
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40246` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by bobemoe** [comment] 2020-12-28 14:22
@engcom-Bravo thanks for taking another look and confirming :)

**Comment by yvaliya** [comment] 2021-01-01 03:48
@bobemoe I think you just forgot to add sequence node in your etc/module.xml file. Please go through this [devdocs](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/build/module-load-order.html) and update your etc/module.xml like below

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/Module/etc/module.xsd">
    <module name="Test_Test" setup_version="0.0.0">
        <sequence>Magento_Catalog</sequence>
    </module>
</config>
```

**Comment by bobemoe** [comment] 2021-01-02 16:01
I have tried adding this but it seems to make no difference.

I have updated my test module to reflect these changes, so you can pull the latest to see yourself.

Is `\Magento\Catalog\Model\ResourceModel\Product\Action` definitely the right class to inject? Should I be using an interface or something? I want access to `$productAction->updateAttributes();`

Thanks.

**Comment by vlmed** [comment] 2021-01-04 10:52
Hello @bobemoe 
Use Proxy to pass \Magento\Catalog\Model\ResourceModel\Product\Action into Console command constructor.
Example:
`<type name="Module\Test\Console\Command\YourCommand">
        <arguments>
            <argument name="productAction" xsi:type="object">\Magento\Catalog\Model\ResourceModel\Product\Action\Proxy</argument>
        </arguments>
    </type>`

**Comment by ihor-sviziev** [comment] 2021-01-06 20:25
Hi @bobemoe ,
Seems like the issue is inside your extension - it’s not using proxy for this class. Please update your code accordingly to the following comment and everything should works fine.

 Could you please confirm that?

**Comment by bobemoe** [comment] 2021-01-12 14:18
Yes! I can confirm using the Proxy class has resolved the issue. 

There actually seems to be no need for `<sequence>` in `module.xml`, although it sounds like this is a good idea anyway since my module does have dependencies.

Thanks for the help, and I agree that the logs / error message could have been more helpful ;)

**Comment by ihor-sviziev** [comment] 2021-01-15 10:43
@bobemoe, thank you for confirming! I'm closing this issue as not relevant anymore.

**Closed as completed by ihor-sviziev** 2021-01-15 10:43 UTC
Labels: Issue: Confirmed, Component: DB, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P3, Severity: S3, Progress: done, Issue: needs update, Reported on 2.4.1

**Comment by magento-engcom-team** [comment] 2021-01-15 10:45
Hi @bobemoe, @ihor-sviziev. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-40246` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by ihor-sviziev** [comment] 2021-01-15 10:47
@sidolov @gabrieldagama seems like the automatic comment is a mistake?

**Comment by gabrieldagama** [comment] 2021-01-19 14:34
Hi @ihor-sviziev, yes! There is no work done on that internally.
