### ISSUE TITLE
Mini cart shows old values when customer session is over

### ISSUE THREAD

**Issue by katesuykovskaya** [magento/magento2#4416] opened 2016-05-06 07:36 UTC
## Steps to reproduce
1. Magento 2.0.2, all cache types are disabled
2. go to frontend, do not log in
3. add few products to shopping cart
4. wait until session is over (1 hour by default)
5. go to shopping cart page
## Expected result
1. shopping cart and mini shopping cart should show the same values - zero in our case
## Actual result
1. shopping cart is empty, but mini shopping cart has added products https://drive.google.com/file/d/0B6jlEIvY3J2OM0dpaEx5azM5RkU/view

**Comment by andidhouse** [comment] 2016-05-06 11:34
Same here. I think maybe this has something to do with sessions save?

**Comment by redboxmarcins** [comment] 2016-05-06 13:00
Same here

**Comment by ishakhsuvarov** [comment] 2016-05-25 12:46
@Katerina1993 @andidhouse  @redboxmarcins Thank you for reporting this issue. Looks like we already have a similar item in our backlog with the internal id `MAGETWO-52593`. We will update this ticket as soon as issue is resolved.

**Comment by deep1086** [comment] 2016-07-07 12:13
@ishakhsuvarov 
Having same issue.Please share info if it is resolved in any new version of magento2

**Comment by SerhiyShkolyarenko** [comment] 2016-09-30 14:50
@deep1086 this issue seems to be fixed several month ago. Did you manage to reproduce it on version 2.0.9 or 2.1.1?

**Comment by veloraven** [comment] 2016-11-23 13:00
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Closed as completed by veloraven** 2016-11-23 13:00 UTC
Labels: Issue: Ready for Work, bug report, Progress: needs update
