### ISSUE TITLE
Focusing on failed swatches validation does not work

### ISSUE THREAD

**Issue by oleksii-lisovyi** [magento/magento2#12470] opened 2017-11-28 13:08 UTC
### Preconditions
Magento 2.1.10.

### Steps to reproduce
1. Go to product on front-end with configured swatches.
2. Scroll down page to see only "Add to Cart" button and not swatches.
3. Click on "Add to Cart" button.

### Expected result
1. Form validation failed with displaying of error blocks under the swatches.
2. Page is scrolled up to (focus on) the first swatch with failed validation.
3. Customer select required fields and make a purchase (good UX).

### Actual result
1. Form validation failed with displaying of error blocks under the swatches.
2. Page is NOT scrolled up to (focus on) the first swatch with failed validation.
3. Customer can't realize, what is going on, because nothing actually happened (bad UX).

**Important note**: if there is configured any other required "default" field (like drop-down) in the way of adding, for example, Customizable Options, and there is failed swatch validation, focusing on the "default" field with failed validation also does not work. So swatches validation breaks UX.

**Comment by magento-engcom-team** [comment] 2017-11-29 07:29
@oleksii-lisovyi, thank you for your report.
The issue is already fixed in develop branch, 2.2.1

**Closed as completed by magento-engcom-team** 2017-11-29 07:29 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
