### ISSUE TITLE
qty is zero and salable is zero and product in stock in admin

### ISSUE THREAD

**Issue by salah11172** [magento/magento2#37786] opened 2023-07-21 21:11 UTC
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug
2.4.5

### Steps to reproduce

1-place order to product have qty =1
2- and complete order 
3-the qty and salable will be zero and in admin in product page still show in stock

### Expected result

Expected product out of stock if salable qty is zero 
![Screenshot from 2023-07-22 00-10-17](https://github.com/magento/magento2/assets/77698583/aacde40c-48b8-43ca-99c8-ac361afb6cd5)

### Actual result

 product show in stock flag

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by FadedOut** [comment] 2023-07-22 05:58
@salah11172 This is a long-time issue (years) and requires modification of a file. Who knows if it will ever properly be fixed. It was supposed to be fixed in 2.4.6 but nope, still broken. Supposedly it's fixed in 2.4.7-beta but will probably be broken again by actual release of 2.4.7. This is usual of Magento. And they'll tell you to put your live production server on a beta build (2.4.7-beta) to get the fix instead of just pushing the fix to everyone. Terrible.

For the community fix if you want to have it working properly for now you could modify the file as noted in my ticket here: https://github.com/magento/magento2/issues/35319#issuecomment-1111842395 by another member. Make sure to make a backup of the original file before modifying just in case if you make a mistake modifying the file. But the fix does work, I used it since 2.4.4 up to 2.4.6-p1.

**Comment by engcom-Dash** [comment] 2023-07-25 11:35
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-07-26 06:24
Hi @salah11172 ,

verified the issue in 2.4-develop instance and the issue is not reproducible,Kindly refer the screenshots.

Steps to reproduce:
1.Place the order with 1 saleable quantity  and complete the order

<img width="1512" alt="Screenshot 2023-07-26 at 7 13 49 AM" src="https://github.com/magento/magento2/assets/60198592/342fd8ea-cc99-4bec-a697-52a1ffba15ae">
<img width="1512" alt="Screenshot 2023-07-26 at 7 14 34 AM" src="https://github.com/magento/magento2/assets/60198592/865b15e4-8fda-498f-af1c-3b29c18c883b">
<img width="1512" alt="Screenshot 2023-07-26 at 7 14 53 AM" src="https://github.com/magento/magento2/assets/60198592/d665cead-4197-4852-9e52-7f041e7c57a0">
<img width="1512" alt="Screenshot 2023-07-26 at 7 18 00 AM" src="https://github.com/magento/magento2/assets/60198592/f75135fe-80d6-4eac-a0ea-2a809fd5500d">

Product out of stock if saleable qty is zero.

Thanks!

**Comment by engcom-Dash** [comment] 2023-07-26 06:31
@magento give me 2.4-develop instance

**Comment by salah11172** [comment] 2023-07-26 07:26
I mean stock status dropdwon in product page in admin 
if quantity and salable quantity equal zero 
the stock status is still in stock

Please be honest with us and with yourselves
This problem exists and has been encountered by many people
This is not the correct solution to pretend that there is no problem and try to hide it

**Comment by engcom-Dash** [comment] 2023-07-26 12:07
@magento give me 2.4-develop instance

**Comment by salah11172** [comment] 2023-07-26 15:17
okay 
steps :
1-in this product (sku=24-MB03)  make qty =1 and assign source (source= new)
2- from admin  placed order (incerment_id=#000000004) [salable qty become zero]
2-then complete order steps to make it complete  [qty become zero ]
in admin in product  **page Source Item Status** still **inStock**

**Comment by hiren-gujarati** [comment] 2023-07-29 12:10
Hi,
I have verified the issue in 2.4.6-p1 instance and the issue is reproducible, Kindly refer the steps.

Steps to reproduce:
1. Add New Source.
2. Set any product qty=1 (Salable qty must be 1).
3. Place order with same item and create invoice & shipment.
4. Navigate to product edit page. where,
        Qty for Default Source = 0 (as expected)
        Salable Quantity = 0 (as expected)
        Source Item Status = In Stock (Should be Out of Stock)

![image](https://github.com/magento/magento2/assets/80200879/11786502-7676-48e6-a052-782b0d54f4b6)

On shipment create product stock status is updated in cataloginventory_stock_status and cataloginventory_stock_status tables but status is not update in the inventory_source_item table. following class is only updateing quantity on shipment create so, status is not change when product have zero quantity and salable quantity.

https://github.com/magento/inventory/blob/develop/Inventory/Model/ResourceModel/SourceItem/DecrementQtyForMultipleSourceItem.php#L53

I have created following patch and it is resolve my issue:

```
diff --git a/vendor/magento/module-inventory/Model/ResourceModel/SourceItem/DecrementQtyForMultipleSourceItem.php b/vendor/magento/module-inventory/Model/ResourceModel/SourceItem/DecrementQtyForMultipleSourceItem.php
--- a/vendor/magento/module-inventory/Model/ResourceModel/SourceItem/DecrementQtyForMultipleSourceItem.php
+++ b/vendor/magento/module-inventory/Model/ResourceModel/SourceItem/DecrementQtyForMultipleSourceItem.php
@@ -50,7 +50,10 @@ class DecrementQtyForMultipleSourceItem
             ];
             $connection->update(
                 [$tableName],
-                ['quantity' => new \Zend_Db_Expr('quantity - ' . $decrementItem['qty_to_decrement'])],
+                [
+                    'quantity' => new \Zend_Db_Expr('quantity - ' . $decrementItem['qty_to_decrement']),
+                    'status' => $sourceItem->getStatus()
+                ],
                 $where
             );
         }

```

**Comment by engcom-Dash** [comment] 2023-07-31 11:32
Hi @salah11172 ,

verified the issue in 2.4-develop instance and issue can be reproducible,Hence we are confirming the issue.
<img width="1512" alt="Screenshot 2023-07-26 at 6 15 46 PM" src="https://github.com/magento/magento2/assets/60198592/56ed7711-1bd5-46ff-ba81-86cf4daed585">

**Comment by engcom-Dash** [comment] 2023-08-09 09:43
Hi @salah11172 ,

Verified the issue in 2.4-develop instance and the issue is reproducible,Kindly refer the below screenshot:
<img width="1512" alt="Screenshot 2023-07-26 at 6 15 46 PM" src="https://github.com/magento/magento2/assets/60198592/93731794-82e8-4427-8d9c-87c6f63ac2a7">

**Comment by engcom-Dash** [comment] 2023-08-09 14:54
@salah11172 ,

As per internal discussion,Again we are working on this issue and we moved this issue as Needs update.

Thanks.

**Comment by engcom-Dash** [comment] 2023-08-10 10:28
@salah11172 ,

Verified the issue in 2.4-develop instance and the issue is not reproducible.
As per [DevDocs](https://experienceleague.adobe.com/docs/commerce-admin/inventory/quantities/sources-assign-per-product.html?lang=en#quantities) we need to set the stock status in backend.Let us know if we are missing anything!

Thanks.

**Comment by salah11172** [comment] 2023-08-13 07:26
no hope

**Comment by engcom-Dash** [comment] 2023-08-18 10:42
Hi @salah11172 ,

By default stock status should be In Stock only...We need to set the Source stock status in backend when products goes to out of stock.
Kindly refer the below screenshots:
<img width="1504" alt="Screenshot 2023-08-18 at 4 07 25 PM" src="https://github.com/magento/magento2/assets/60198592/aa2fdd3d-9ba0-47ca-8a85-9d6ed049e8ba">

Thanks.

**Comment by engcom-Dash** [comment] 2023-08-30 08:47
Hi @salah11172 ,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2023-08-30 08:47 UTC
Labels: Reproduced on 2.4.x, Issue: needs update, Area: Admin UI, Component: Stock, Reported on 2.4.5

**Comment by serzhik** [comment] 2024-02-08 13:55
This ticket duplicates https://github.com/magento/inventory/issues/3062
