### ISSUE TITLE
REST API returns incorrect values for category is_active & include_in_menu

### ISSUE THREAD

**Issue by TysvdHeuvel** [magento/magento2#34912] opened 2022-01-03 10:28 UTC
When fetching category data through the Magento REST API the fields is_active and include_in_menu always return true, regardless to what was defined in the Magento backend. 

### Preconditions (*)
Fresh Magento 2.4.3

### Steps to reproduce (*)
Create a new category by using the Magento backend. 
Set Enabled Category and Include in Menu to FALSE. 
Now use Postman to retrieve the category you have just created. 
I.E. GET http://magento.dev/rest/V1/categories/61

### Expected result (*)
A response like this:

{
    "id": 61,
    "parent_id": 59,
    "name": "Keyboards",
    "is_active": false,
    "include_in_menu": false,
    ....
}

### Actual result (*)
Responses which always return TRUE for the two boolean fields. 

{
    "id": 61,
    "parent_id": 59,
    "name": "Keyboards",
    "is_active": true,
    "include_in_menu": true,
    ....
}

Severity: S1

**Comment by engcom-November** [comment] 2022-01-03 14:14
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue:
Created category by setting  Enabled Category and Include in Menu to FALSE
Rest API - Sent Get request to /rest/all/V1/categories/10 - No issue
"is_active": false,
"include_in_menu": false
![image](https://user-images.githubusercontent.com/60198231/147940692-ac817de9-1897-4209-bdb0-c2153207675c.png)
@TysvdHeuvel kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-01-19 06:07
Hi @TysvdHeuvel ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-01-19 06:07 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
