### ISSUE TITLE
The Varnish configs do not strip Klaviyo marketing parameter

### ISSUE THREAD

**Issue by Gelmo** [magento/magento2#35227] opened 2022-03-24 23:50 UTC
### Preconditions (*)
1. Any Magento version that includes a suggested Varnish VCL config.
2. Using Varnish along with a VCL that is included with Magento.
3. Usage of Klaviyo's marketing email services/modules.

### Steps to reproduce (*)
1. Use a VCL that is included with Magento.
2. Send a marketing email via Klaviyo.
3. Watch varnishlog.
4. Visit the site using a link that is included in a Klaviyo-generated email.
5. Visit the site using a similar link that does not include the `_kx` query parameter.
6. Compare the results shown by varnishlog.

### Expected result (*)
1. The `_kx` parameter should be stripped, ensuring that visitors using links with the `_kx` parameter are served the cached version of the requested page.

### Actual result (*)
1. Varnish does not strip the parameter, and since the value is unique per visitor, those requests will not match any hashes in Varnish's cache.
2. This also results in additional PHP load due to the request needing to be processed by Magento.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Gelmo** [comment] 2022-03-24 23:50
@magento I am working on this

**Comment by Gelmo** [comment] 2022-03-25 00:11
@magento add to contributors team

**Comment by Gelmo** [comment] 2022-03-25 00:13
@magento I am working on this

**Comment by engcom-Dash** [comment] 2022-11-07 01:36
Hi @Gelmo ,

We are trying to reproduce the issue in 2.4-develop instance but we are not able to reproduce.
Steps We followed:
1.Install mAgento
2.Done Varnish Setup Configuration
3.Install Klaviyos Module
4.Integrate with magento from klaviyos
5.we are not able to integrate the module

Screenshots:
<img width="1512" alt="Screenshot 2022-11-04 at 4 34 16 PM" src="https://user-images.githubusercontent.com/60198592/200208991-ed1d4ec8-1b91-456f-a52c-240fbc55d575.png">


Still we are working in this module to reproduce the issue...we will reproduce the issue ASAP.

Let us know if we missing anything!!!
Thanks!!!

**Comment by vasileuskidzmitry** [comment] 2023-11-18 09:44
@engcom-Dash Hello! How to move this issue from the ground? Can it be assigned to me to complete the rest of the required steps?

**Comment by vasileuskidzmitry** [comment] 2023-11-20 10:05
@magento I'm working on this

**Comment by vasileuskidzmitry** [comment] 2023-11-20 10:06
@magento add to contributors team

**Comment by vasileuskidzmitry** [comment] 2023-11-20 15:14
I'm unable to edit the original comments to update steps so I will add them here.

**Steps to reproduce (*)**
1. Use a VCL that is included with Magento.
2. Read this article as confirmation that `_kx` parameter belongs to Klaviyo marketing campaigns - https://help.klaviyo.com/hc/en-us/articles/115005076767.
3. Switch Magento/Adobe Commerce to `developer` mode so the `X-Magento-Cache-Debug` header is included in the response.
4. Visit any page (for instance the Home one) twice. Check that `X-Magento-Cache-Debug` contains `HIT` value to confirm that the page is cached by Varnish.
5. Now add `_kx` parameter with some random unique value (Ex. https://yourdomain/?_kx=1) to the URL and visit this URL.

**Expected Result**
1. When you visit the URL form point 5, you see `HIT` value in the `X-Magento-Cache-Debug`, because this is a marketing parameter that should be omitted.
2. Every time you change `_kx` to some new value, you see `HIT` anyway.

**Actual Result**
1. You see `MISS` in that header.
2. Every time you change `_kx` to some new value, you see `MISS` anyway. A new cache entity is created in Varnish on every such request.

**Comment by vasileuskidzmitry** [comment] 2023-11-20 21:05
cc @engcom-Dash

**Comment by vasileuskidzmitry** [comment] 2023-11-26 17:53
Added new PR

**Comment by vasileuskidzmitry** [comment] 2023-11-30 09:31
cc @engcom-Bravo

**Comment by ihor-sviziev** [comment] 2024-01-03 14:30
I updated priority to p2, to make it similar to https://github.com/magento/magento2/pull/38302#event-11314093429

**Comment by vasileuskidzmitry** [comment] 2024-01-05 16:34
@ihor-sviziev Here is one another marketing system https://www.northbeam.io/ that uses its own marketing parameters (starting with "nb_"). Should I create a separate issue/PR for this or it could be done here or in #38302 ?

**Comment by ihor-sviziev** [comment] 2024-11-15 10:55
This issue was already fixed in https://github.com/magento/magento2/pull/39188

**Closed as completed** 2024-11-15 10:55 UTC
Labels: Issue: Confirmed, Component: Cache, Reproduced on 2.4.x, Priority: P2, Progress: done, Issue: ready for confirmation, Issue: needs update, Area: Framework
