### ISSUE TITLE
Promo Code "Gray Out" When Applied In Cart

### ISSUE THREAD

**Issue by nickbigassfans** [magento/magento2#33315] opened 2021-06-21 17:17 UTC
### Preconditions (*)

1. Magento ver. 2.3.7
2.

### Steps to reproduce (*)

1. Go to https://store.bigassfans.com/en_ca/haiku-l-fan-52-white-universal-mount-white
2. Place 1 fan in cart
3. Go to https://store.bigassfans.com/en_ca/sidekick
4. Place 1 fan in cart
5. Proceed to Checkout
6. Enter code COMFORTABLE21 in coupon input
7. Apply Coupon
8. visit https://store.bigassfans.com/en_us/for-the-home/haiku-l 
9. add Haiku L to cart
10. go to checkout
11. apply UNLIMITED21 in coupon input
12. notice how it gets applied

### Expected result (*)

1.![image](https://user-images.githubusercontent.com/86253926/122801847-a5951080-d292-11eb-94b5-a6f6a1f67a6e.png)
2. The code should disappear and 30% should apply to the haiku L fans, and 20% to the Sidekick fan. The code however stays stuck in the box and no discount is applied
3. on the US site, store.bigassfans.com, the promo code works
4. Canada And US promo codes are set up exactly the same way on the backend-- we verified line by line and we have it set up the same way
5. US works, Canada Does not

### Actual result (*)

1.![image](https://user-images.githubusercontent.com/86253926/122801847-a5951080-d292-11eb-94b5-a6f6a1f67a6e.png)
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2021-06-22 08:39
Verified the issue in CA environment and the issue is reproducible:
Steps to reproduce:
1. Go to https://store.bigassfans.com/en_ca/haiku-l-fan-52-white-universal-mount-white
2. Place 1 fan in cart
3. Go to https://store.bigassfans.com/en_ca/sidekick
4. Place 1 fan in cart
5. Enter code COMFORTABLE21 in coupon input
6. Apply Coupon
**Issue:** Canada environment - Checkout page - Discount is not getting applied in checkout page but is applied in Payment page
Canada Checkout page:
![image](https://user-images.githubusercontent.com/60198231/122892383-f7a56700-d362-11eb-895a-8eeb243ebbfa.png)
Canada Payment page:
![image](https://user-images.githubusercontent.com/60198231/122892857-65519300-d363-11eb-85e4-8c2f94120bfe.png)

**Expected behavior:** US Checkout page - Discount is applied in checkout page. Same behavior should be present in both US and Canada sites.
US Checkout page:
![image](https://user-images.githubusercontent.com/60198231/122892509-13107200-d363-11eb-83ed-767d26d62445.png)

**Comment by magento-engcom-team** [comment] 2021-06-22 08:42
@engcom-November Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-06-22 08:42
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by engcom-November** [comment] 2021-06-22 11:35
Verified the issue on latest Magento version 2.4.2 and Promo code field is getting applied in Payment page and Products Cart page but not in checkout page. There is no discount field in checkout page and actual product price without discount is getting displayed.
Steps performed: Magento Admin -> Marketing -> Cart Price Rules -> Add New Rule - Add Coupon and Save.
Front End - Add product to Cart
Carts page - User is able to apply promo code
Proceed to checkout - Promo code is not applied. Discount field is not displayed
Proceed to Payment - Promo code field is displayed and discount is applied.
Can you please provide detailed steps to reproduce the issue on Magento checkout page
![image](https://user-images.githubusercontent.com/60198231/122917473-b2416380-d37b-11eb-8ab3-69bcdf9989fe.png)
![image](https://user-images.githubusercontent.com/60198231/122917538-c5543380-d37b-11eb-84d8-1e0b8f5560fa.png)
![image](https://user-images.githubusercontent.com/60198231/122917657-e026a800-d37b-11eb-804c-fcbb54949c90.png)

Thank you

**Comment by engcom-November** [comment] 2021-07-06 09:28
@nickbigassfans,
We are closing this ticket as there has been no latest update on the same.
Thank you.

**Closed as completed** 2021-07-06 09:28 UTC
Labels: Issue: needs update, Reported on 2.3.x
