### ISSUE TITLE
Enabling redis locking disables redis locking, causing random intermittent cart problems and other issues

### ISSUE THREAD

**Issue by driskell** [magento/magento2#10111] opened 2017-06-30 11:02 UTC
### Preconditions
1. Install redis
2. Configure Magento 2 to use redis for sessions
3. Set disable_locking configuration to 0
4. Magento 2.1.7
5. PHP-FPM 7.0 with Nginx

Note: The source of the problem is in the php-redis-session-abstract as a known issue that was fixed in php-redis-session-abstract 1.3.4

### Steps to reproduce
1. On various machines, add products to cart quickly (visit product page and quickly add to basket, so multiple AJAX requests are left running whilst add to cart happens)

### Expected result
1. Clicking add to cart always works and you always see your cart with that item

### Actual result
1. You will sometimes land on the cart page and it will be empty
2. Various other session-related "data-loss" will occur

### Resolution / Workaround

This is due to inverted logic in php-redis-session-abstract. When locking is disabled, it is actually enabled, when locking is enabled, it is actually disabled. Workaround is to disable locking in the `env.php` configuration, which will in turn enable it.

The issue was fixed in 1.3.4 of php-redis-session-abstract but it seems Magento 2 is still using `~1.2.2` which will not take us to 1.3 with the fix.

The specific fix is here, showing 1.3.4 as fix version:
https://github.com/colinmollenhour/php-redis-session-abstract/commit/6f005b2c3755e4a96ddad821e2ea15d66fb314ae

**Comment by antboiko** [comment] 2017-06-30 13:07
@driskell  thank you for the report. Can you please also specify what environment and what Magento version are you using?

**Comment by driskell** [comment] 2017-07-11 12:05
Magento 2.1.7

PHP-FPM 7.0 with Nginx

The source of the problem is in the php-redis-session-abstract as a known issue that was fixed in php-redis-session-abstract 1.3.4

**Comment by magento-engcom-team** [comment] 2018-03-13 11:30
@driskell, thank you for your report.
The issue is already fixed in 2.2.3, 2.3.0

**Closed as completed by magento-engcom-team** 2018-03-13 11:30 UTC
Labels: bug report, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by rqsakai** [comment] 2018-03-15 16:14
Is there any fix or patch for 2.1.* ?

We are experiencing same issue since updated from 2.1.8 to 2.1.12, all session related requests are extremely slow and new relic gives us the following transaction as responsible for 80% - 90% of the transaction time:

`Cm\RedisSession\Handler::read`

Magento  Commerce 2.1.12
PHP 7.0.24
AWS ElasticCache Redis 2.8.24

We are losing 74% of our revenue since last update

**Comment by driskell** [comment] 2018-03-15 17:34
@rqsakai We manually modified the files in Magento that configure php-redis-session-abstract so that they inverted the value. Either directly, or via composer patch

**Comment by rqsakai** [comment] 2018-03-15 18:54
@driskell are you reffering to this? https://github.com/colinmollenhour/php-redis-session-abstract/commit/6f005b2c3755e4a96ddad821e2ea15d66fb314ae

If yes our file is following this rule.

Thanks for the help
