### ISSUE TITLE
Order by sku template broken in homepage

### ISSUE THREAD

**Issue by chandru-199** [magento/magento2#33814] opened 2021-08-16 18:53 UTC
### Preconditions (*)

1. Magento EE 2.3.2

### Steps to reproduce (*)

1. In Admin Content -> widgets -> create widget
2. create widget and and set display layout settings as homepage.

### Expected result (*)

1. Order by sku widget should be display properly

### Actual result (*)

1. ![TwStx](https://user-images.githubusercontent.com/51230988/129614842-ed776cdf-4110-4638-8823-d7cc7bdecd6f.png)
2. Broken order by sku template

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment] 2021-08-19 12:38
Hi @chandru-199 
We tried to reproduce this issue & were unable to do so.
According to your issue description, we added a widget (**Order by SKU**) onto **Home page**.
The Order by SKU widget was displayed properly on Home Page.
Please find the attached screenshot of the same.

<img width="1088" alt="Screenshot 2021-08-19 at 17 44 15" src="https://user-images.githubusercontent.com/51681435/130067969-c4f0bdaa-eff7-4da8-b096-d5164a944df3.png">

So kindly recheck this issue on Magento 2.4-develop branch and if the issue is still reproducible, please provide more details or additional/missing steps regarding the same.

Thank you.

**Comment by engcom-Echo** [comment] 2021-09-02 06:49
Hi @chandru-199 
Since we didn't get any update from you & since we couldn't reproduce the issue being reported, we are closing this issue.
If this issue is still reproducible for you on magento 2.4-develop, please feel free to reopen this issue & provide more details or additional/missing steps regarding the same.

Thank you

**Closed as completed by engcom-Echo** 2021-09-02 06:49 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
