### ISSUE TITLE
Newsletter Queue Doesn't Match local time

### ISSUE THREAD

**Issue by Ctucker9233** [magento/magento2#8422] opened 2017-02-05 00:57 UTC
This is a repeat of an older issue. I closed that issue and opened this one to put this issue back on top of the issue list. DO NOT CLOSE THIS. IT IS NOT A DUPLICATE!

When queuing a newletter, the queue start time does not match local time. If I want to send out a newsletter immediately, it results in a status of "not sent" because the time gets shifted back about 7 hours.

**Preconditions**

Magento 2.1.2 and Magento 2.1.3
PHP 5.6.22

**Steps to reproduce**

Create newsletter template
Queue newsletter template
Set Queue start to send today, adjust time forward an hour or two, for example, 11:19 am (my local time at the point of writing this is 10:19 AM PST)
Click Save Newsletter

**Expected result**

Newsletter is queued to send at 11:19 AM 8/2/16

**Actual result**

Newsletter is queued to send at 4:19 PM 8/1/16
Results in the newsletter never being sent
I need to be able to reliably send newsletters any time I want. I don't always have time to queue up a newsletter the day before I have to send it. I appreciate any help on this issue.

**Comment by Ctucker9233** [comment] 2017-02-06 23:09
Seriously? Still no response? Where is everyone @magento-team?

**Comment by ivan-veres** [comment] 2017-03-16 14:21
Issue in progress @ivan-veres

**Comment by nkajic** [comment] 2017-03-16 14:32
Issue in progress @nkajic

**Comment by Ctucker9233** [comment] 2017-03-16 23:13
@ivan-veres and everyone else, thank you.

**Comment by Ctucker9233** [comment] 2017-03-25 21:20
@ivan-veres How is this coming along?

**Comment by magento-engcom-team** [comment] 2017-10-12 12:30
@Ctucker9233, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-12 12:30 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by Ctucker9233** [comment] 2017-12-03 00:25
@magento-engcom-team Thank you for fixing. Can you please open a ticket to backport it to 2.1?
