### ISSUE TITLE
CDN does not work with Sign Static Files option

### ISSUE THREAD

**Issue by MattDelac** [magento/magento2#8366] opened 2017-02-01 12:59 UTC
### Preconditions

1. PHP 7.0.12
2. MariaDB
3. Nginx
4. Magento 2.1.3
5. Mode: production

### Steps to reproduce

1. Merge css and js files (only merge)
2. Set "Sign Static Files" to "Yes"
3. Add a CDN (I tried with MaxCDN) 
4. Flush the cache if necessary

### Expected result

1. Everything should work as normal

### Actual result

1. When the CDN AND the Static files are signed, the css and js files are not reachable anymore

XXX = the domain name
XXXXCDN = the CDN domain name

**Without CDN: It works**
\<link  rel="stylesheet" type="text/css"  media="all" href="https://XXX/pub/static/_cache/merged/fee0cda014b027b05d7d6427041e60cf.css" />
\<link  rel="shortcut icon" type="image/x-icon" href="https://XXXX/pub/media/favicon/stores/1/LOGO_UNIQUE_BLEU_16X16.png" />

**CDN Without Sign Static Files: It works**
\<link  rel="stylesheet" type="text/css"  media="all" href="https://XXXXCDN/pub/static/_cache/merged/fee0cda014b027b05d7d6427041e60cf.css" />
\<link  rel="shortcut icon" type="image/x-icon" href="https://XXXXCDN/pub/media/favicon/stores/1/LOGO_UNIQUE_BLEU_16X16.png" />

**CDN with Sign Static Files: It does not work**
\<link  rel="stylesheet" type="text/css"  media="all" href="https://XXXXCDN/pub/static/version1484988990/_cache/merged/fee0cda014b027b05d7d6427041e60cf.css" />
\<link  rel="shortcut icon" type="image/x-icon" href="https://XXXXCDN/pub/media/favicon/stores/1/LOGO_UNIQUE_BLEU_16X16.png" /

Thank you for your help

**Comment by vkorotun** [comment] 2017-02-08 13:46
@MattDelac Hi Matt, quick question: are the other static files served well from CDN with Sign Static Files feature turned on? Can you confirm that all static files are no longer available via CDN and not just merged CSS or merged JS files as provided in description.

**Comment by MattDelac** [comment] 2017-02-09 10:45
Hello @vkorotun,

The other static files such as the images (png/jpeg) are served well.

If the css are not merged, it still does not work

So it seems that only js & css (merged or not) have this issue

Thank you

**Comment by MattDelac** [comment] 2017-07-25 12:38
Hello @vkorotun ,

Do you know when does this issue will be done ?
I open the ticket in February, thus 6 months ago

Thank you

**Comment by magento-engcom-team** [comment] 2017-10-23 15:30
@MattDelac, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-23 15:30 UTC
Labels: bug report, Area: Frontend, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid
