### ISSUE TITLE
Cart Price Rule with shipping method set as condition is not working Magento 2.4.1

### ISSUE THREAD

**Issue by preeteshtavant** [magento/magento2#34866] opened 2021-12-22 17:05 UTC
### Preconditions (*)

1. Magento 2.4.1
2. just plain , default magento setup

### Steps to reproduce (*)

1. Create a cart price rule (as mentioned in video/ below setp)
Admin - Marketing - Cart Price Rules - Add new Rule
- Set coupon basic information and select Specific Coupon, Enter Coupon code
- Go to condition and set : If ALL  of these conditions are TRUE : Shipping Method  is  [flatrate] Fixed
- In action set apply as Percent of product price discount
- Apply to shipping amount as yes
- In "Apply the rule only to cart items matching the following conditions (leave blank for all items)" section,  set "Free Shipping" drop down as For shipment with matching items
- Front end Login using customer. 
Note: Default shipping method should be Flat rate - Fixed.
Add a product to cart and apply coupon in Shopping Cart page - Issue. "Coupon is Not valid" error message is displayed
Apply discount in checkout page - No issue. Coupon applied
https://user-images.githubusercontent.com/85919383/147129168-31e44dee-46eb-40b1-aec9-23288584734e.mp4

2.

### Expected result (*)

1. When we apply created coupon after selecting Flat Rate as shipping method, the coupon should applied successfully 
2.

### Actual result (*)

1. Even after selecting the flat rate as shipping method when we try to apply that coupon its giving invalid coupon error.
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.
[[S1]]()
- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ S1] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._
![screenshot-127 0 0 1-2021 12 22-22_37_57](https://user-images.githubusercontent.com/85919383/147129801-b5c129ed-700d-4614-8ca1-238c8b3c405b.png)
![screenshot-127 0 0 1-2021 12 22-22_37_20](https://user-images.githubusercontent.com/85919383/147129810-f5463adc-f3c8-4f63-b8f8-ee5bbd38968a.png)

**Comment by engcom-November** [comment] 2021-12-23 11:57
Verified the issue on Magento 2.4-develop branch and the issue is reproducible on Shopping Cart page:
Shopping Cart page - Shipping Method is selected as (Flat rate fixed by default)
![image](https://user-images.githubusercontent.com/60198231/147236997-731952d8-409a-40fd-8363-5e5213e8f113.png)
However this issue is not observed on Checkout page. Coupon applied successfully.
![image](https://user-images.githubusercontent.com/60198231/147237150-1250cbfd-7b41-4879-8aed-65216bed2f5c.png)
This issue is observed when product is added to cart for the 1st time. If coupon applied in checkout page and navigated back to shopping cart page - Remove and  reapply coupon - No issue. Coupon applied successfully.

**Comment by mmezhensky** [comment] 2021-12-24 12:40
@magento I am working on this

**Comment by sanjay-evrig** [comment] 2022-01-11 04:02
@magento Any updte?

**Comment by preeteshtavant** [comment] 2022-01-28 05:19
Any update on this

**Comment by preeteshtavant** [comment] 2022-02-17 12:22
@m2-assistant @mmezhensky  @m2-github-services @m2-community-project @engcom-November 
is there any update on this.

@mmezhensky  its showing merge request failed.

Could you please provide an update on this.

**Comment by preeteshtavant** [comment] 2022-03-08 03:37
@m2-assistant @mmezhensky @m2-github-services @m2-community-project @engcom-November
is there any update on this.

@mmezhensky its showing merge request failed.

Could you please provide an update on this.

**Comment by preeteshtavant** [comment] 2022-03-08 03:37
is there any update

**Closed as completed** 2023-09-03 15:03 UTC
Labels: Issue: Confirmed, Component: SalesRule, Reproduced on 2.4.x, Priority: P1, Progress: done, Reported on 2.4.1, Area: Cart & Checkout

**Comment by engcom-Bravo** [comment] 2023-09-04 06:10
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-2044 by the internal team
Related commits: https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-2044&type=commits

Based on the Jira ticket, the target version is 2.4.7-beta2.

Thanks
