### ISSUE TITLE
Reorder product with options is failing 

### ISSUE THREAD

**Issue by florinm8** [magento/magento2#36176] opened 2022-09-21 21:08 UTC
### Preconditions and environment

- Version: Magento 2.4.5
- php 8.1
- I use aheadworks/module-sarp2 module which adds subscription option, but i suspect it is not the cause of the issue. None of my orders - with products without subscription - have the option key on info_buyRequest  (see detail on 'Actual result' section below)

### Steps to reproduce

1. place an order with a product that add custom options
2. from 'My account' try to reorder.

 

### Expected result

The product is added to cart and checkout can continue

### Actual result

Exception occurs because \Magento\Sales\Model\Reorder\OrderInfoBuyRequestGetter::getInfoBuyRequest method assume that info_buyRequest have 'options' key

Commenting out the line 
`if (array_key_exists($option['option_id'], $info['options'])) ` resolves the issue

### Additional information

Below you can find the stack trace 

``
TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /var/www/html/lund3/vendor/magento/module-sales/Model/Reorder/OrderInfoBuyRequestGetter.php:54
Stack trace:
#0 /var/www/html/lund3/vendor/magento/module-sales/Model/Reorder/OrderInfoBuyRequestGetter.php(54): array_key_exists(0, NULL)
#1 /var/www/html/lund3/vendor/magento/module-sales/Model/Reorder/Reorder.php(255): Magento\Sales\Model\Reorder\OrderInfoBuyRequestGetter->getInfoBuyRequest(Object(Magento\Sales\Model\Order\Item\Interceptor))
#2 /var/www/html/lund3/vendor/magento/module-sales/Model/Reorder/Reorder.php(217): Magento\Sales\Model\Reorder\Reorder->addItemToCart(Object(Magento\Sales\Model\Order\Item\Interceptor), Object(Magento\Quote\Model\Quote\Interceptor), Object(Magento\Catalog\Model\Product\Interceptor))
``

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-09-22 06:21
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-09-22 06:33
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-09-22 11:44
Hi @florinm8,


Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop branch and 2.4.5 but the issue is not reproducible. Created a Product with custom options and placed order successfully.Kindly refer the screenshots.


<img width="1171" alt="Screenshot 2022-09-22 at 3 49 21 PM" src="https://user-images.githubusercontent.com/51680745/191737229-db06c842-ea1d-4b64-9882-d827e49faf66.png">



<img width="1076" alt="Screenshot 2022-09-22 at 3 49 55 PM" src="https://user-images.githubusercontent.com/51680745/191737283-fd151dbc-306a-4338-a960-022507e4b9e2.png">





From my account we are able to Reorder the product with Custom options successfully.

<img width="1117" alt="Screenshot 2022-09-22 at 3 51 10 PM" src="https://user-images.githubusercontent.com/51680745/191737745-2a9e0688-6832-4623-81e4-53423e9d5036.png">



Please let us know we miss anything.


Thanks.

**Comment by florinm8** [comment] 2022-09-25 19:45
Hi, thanks for checking, it seems that the 3rd party aheadworks_sarp module is causing the issue. I got confused as the Magento\Sales\Model\Reorder\OrderInfoBuyRequestGetter class was introduced in magento 2.4.4 and it's working well without it.

**Comment by engcom-Bravo** [comment] 2022-09-26 11:16
Hi @florinm8,


Aheadworks/module-sarp2 module is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the Magento Market place page.



Thanks.

**Comment by engcom-Bravo** [comment] 2022-09-26 11:18
Hi @florinm8 


Thanks for quick response.


Aheadworks/module-sarp2 module is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the Magento Market place page.


Thanks.

**Closed as completed by engcom-Bravo** 2022-09-26 11:18 UTC
Labels: Issue:  Cannot Reproduce, Component: Bundled Extension, Issue: needs update, Reported on 2.4.5
