### ISSUE TITLE
PayPal Express not Working from Shopping Cart Page

### ISSUE THREAD

**Issue by nikoelgatito** [magento/magento2#33445] opened 2021-07-08 20:08 UTC
### Preconditions (*)

1. Magento 2.3.5
2. The Paypal Express Checkout payment method is enabled
3. Paypal Express Checkout config: "Display on Shopping Cart" = Yes (Default)

### Steps to reproduce (*)

1. Guest user, initial visit (no localStorage or session)
2. Add any product to cart
3. Visit the shopping cart page
4. Apply a coupon code
5. Click on the Paypal button to start express checkout

### Expected result (*)

1. The PayPal Express login popup opens

### Actual result (*)

1. The error message "_To check out, please sign in with your email address._" is displayed.

### Temporary Fix
1. Refresh the page and try again.

### Similar Issue Already Reported
A very similar issue has already been reported on July 18th 2019 and was never fixed.

**Reference to original issue #23761:**

### Notes:
1. The new steps provided above should allow the issue to be reproduced.
2. A possible fix has been shared by @domeglic; [https://github.com/magento/magento2/issues/23761#issuecomment-518527894](https://github.com/magento/magento2/issues/23761#issuecomment-518527894)
3. This is an important issue resulting in lost sales.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2021-07-09 08:28
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
Steps:
Configure PayPal Express Checkout - Advanced Settings - (Stores - Configuration - Sales - Payment Methods - PayPal Express Checkout)
Set Display on Shopping Cart - Yes
Clear Cache and cookies
Navigate to Front end - Guest user - Add a product to Cart
Go to Product Cart page
Apply Coupon
Click on PayPal button
**Issue:** Warning message: To check out, please sign in with your email address." is displayed.
User have to refresh the page and click on PayPal button again to display PayPal login popup
![image](https://user-images.githubusercontent.com/60198231/125048399-833a2a00-e0bd-11eb-90f1-f427ffe91f13.png)

**Comment by magento-engcom-team** [comment] 2021-07-15 09:43
:white_check_mark: Confirmed by @engcom-November 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42855` were created

**Issue Available**: @engcom-November, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Closed as completed** 2021-10-26 15:17 UTC
Labels: Issue: Confirmed, Component: Paypal, Reproduced on 2.4.x, Priority: P1, Severity: S1, Progress: done, Reported on 2.3.5

**Comment by ihor-sviziev** [comment] 2021-11-09 10:18
@engcom-Hotel, could you add more details about what PR you are talking about? Was this issue fixed? Where can we find related changes?
Now I see the only one PR linked to this issue that still not merged yet https://github.com/magento/magento2/pull/33902

**Comment by engcom-Hotel** [comment] 2021-11-29 01:32
@ihor-sviziev, the original PR for this issue is [this](https://github.com/magento-gl/magento2ce/pull/7). It has already been merged with the 2.4-develop branch.

Let me check further on how we can find the related changes. I will get back to you on this.

Thanks

**Comment by ihor-sviziev** [comment] 2021-11-29 07:01
Ok, now I see - this issue was fixed in the following commits in the 2.4-develop branch:
- https://github.com/magento/magento2/commit/d1ca5e5089092cfe810f3b82ab286b817993cde8
- https://github.com/magento/magento2/commit/40585f4a126b6a47cd99e950cf5fc05499a3af13#diff-d59802a6713baafbde42e5715f4b355cf66bbaf07d2b5f1454853f9f6040ffd8
