### ISSUE TITLE
Problem changing language

### ISSUE THREAD

**Issue by ghost** [magento/magento2#35407] opened 2022-05-02 13:37 UTC
Hello, I just installed magento, I am logged in to the admin panel, and when I changed the language to Spanish, magento turned like this. Thank you very much.
![Captura](https://user-images.githubusercontent.com/70748354/166242934-89e74c78-bb0f-43ff-a8e7-3d1d6b5b0b6f.PNG)

**Comment by hostep** [comment] 2022-05-02 16:10
Yes, that's expected to happen when you run your shop in `production` mode.
A way to fix this, is by generating your static assets for the Spanish locale: (`es_ES` probably?):

```bash
bin/magento setup:static-content:deploy --theme Magento/backend es_ES
```

That should fix it.

If you are only testing Magento on a local machine or dev server, you can also choose to run in `developer` mode, and in that case the missing static assets should be generated on the fly (which might make your experience a bit slower):

```bash
bin/magento deploy:mode:set developer
```

But **don't** do this when you are running your Magento shop on a staging or production environment.

**Comment by engcom-November** [comment] 2022-05-20 13:32
Hi @thegamerpablo ,
Thank you for reporting and collaboration. Unable to reproduce the issue on Magento 2.4-develop branch. Please check if the issue occurred in production mode and workaround provided here in [comment](https://github.com/magento/magento2/issues/35407#issuecomment-1115076658) and let us know if you are still facing any issues.
Thank you.

**Comment by engcom-November** [comment] 2022-06-03 08:33
Hi @thegamerpablo ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-06-03 08:33 UTC
Labels: Triage: Dev.Experience, Issue: needs update
