### ISSUE TITLE
Cateogry Image is Not  Moving from catalog/tmp to catalog/category on save in 2.3.4

### ISSUE THREAD

**Issue by TheRealHunzik** [magento/magento2#28009] opened 2020-04-28 09:50 UTC
### Preconditions (*)

1. Magento 2.3.4
2. Local Environment
3. OS (Ubuntu 16.04)

### Steps to reproduce (*)

1. Log in to Admin Dashboard
2. Catalog -> Category -> Content
3. Upload New Picture
4. Log in to Database navigate to `catalog_category_entity_varchar` and see recently uploaded record

### Expected result (*)

1. file should be moved from tmp to `catalog/category` and  saved like `image.png`

### Actual result (*)

1. file name is not moving and saving like `base_url/catalog/tmp/category/image.png`

**Comment by ihor-sviziev** [comment] 2020-04-28 10:38
Looks like duplicate of https://github.com/magento/magento2/issues/27168

**Comment by TheRealHunzik** [comment] 2020-04-28 11:02
> Looks like a duplicate of #27168

@ihor-sviziev  Is it a Bug or A Feature Please let me Know

**Comment by ihor-sviziev** [comment] 2020-04-28 11:03
> > Looks like a duplicate of #27168
> 
> @ihor-sviziev Is it a Bug or A Feature Please let me Know

Looks like a bug

**Comment by ihor-sviziev** [comment] 2020-06-05 12:37
**Tested on 2.3.4:**
❌Category Image contains "tmp" in the URL
https://i-27168-2-3-4.instances.magento-community.engineering/category-1.html
![image](https://user-images.githubusercontent.com/1873745/83876144-0661b180-a741-11ea-8dfc-4d987ddfe10c.png)

Image URL is following:
https://i-27168-2-3-4.instances.magento-community.engineering/pub/media/catalog/tmp/category/Tests.png

**Tested on 2.4-develop:**
✔Category Image do not contains "tmp" in the URL
https://i-27168-2-4-develop.instances.magento-community.engineering/category-1.html
![image](https://user-images.githubusercontent.com/1873745/83876618-d23ac080-a741-11ea-8ac5-7abe1233ba9b.png)

Image URL is following:
https://i-27168-2-4-develop.instances.magento-community.engineering/pub/media/catalog/category/Tests.png


This issue was fixed in 2.4-develop branch and not reproducing anymore.
I'm closing this issue.

**Closed as completed by ihor-sviziev** 2020-06-05 12:37 UTC
Labels: Issue: Format is valid, Reported on 2.3.4

**Comment by hostep** [comment] 2020-06-05 13:23
@ihor-sviziev, should we close https://github.com/magento/magento2/issues/25480 as well?
I believe it got fixed in 2.3.5, but I'm not 100% sure since I haven't found the time to test it again.

**Comment by ihor-sviziev** [comment] 2020-06-05 13:25
@hostep closed, thank you!
