### ISSUE TITLE
Cannot Save and Duplicate Catalogue products 

### ISSUE THREAD

**Issue by Nav1s79** [magento/magento2#35447] opened 2022-05-09 15:24 UTC
### Preconditions (*)

1. Magento 2.3.4
2.

### Steps to reproduce (*)

1.  Goto a catalogue item (already created_ click on save and duplicate and get error messages at the top of the page and occasionally duplicates item but generally does nothing 
2.

### Expected result (*)

1. [Screenshots, logs or description]
2. For it to duplicate the listing.......

### Actual result (*)

1. [Screenshots, logs or description]
2.  As above 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by engcom-November** [comment] 2022-05-10 05:20
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-05-10 09:30
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-05-10 10:20
Hi @Nav1s79 ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue. User is able to save and duplicate a product
![image](https://user-images.githubusercontent.com/60198231/167606951-d7389f1e-c881-4fb9-9528-ea7a488a3af2.png)

![image](https://user-images.githubusercontent.com/60198231/167606876-5dc908c5-d367-4840-9776-fd5d81ebbf71.png)
Kindly recheck the issue on Magento 2.4-develop branch as it is having latest code base and elaborate steps to reproduce if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-05-24 06:06
Hi @Nav1s79 ,
We are closing this issue as there has been no latest update on the same. Kindly reopen/create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-05-24 06:06 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update

**Comment by Djohn12** [comment] 2023-06-21 11:13
Hi there,

Reproducing this issue on 2.4.6-p1 instance.

Steps to reproduce:

* Go to admin Catalog > Products Grid
* Go to a product page
* **The product MUST be associated with the attribute_set** `Default`.
* Click Save & Duplicate

Product is not duplicated and we are seeing this error
```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3790-94-1' for key 'catalog_product_entity_datetime.CATALOG_PRODUCT_ENTITY_DATETIME_ROW_ID_ATTRIBUTE_ID_STORE_ID', query was: INSERT INTO `catalog_product_entity_datetime` (`attribute_id`,`store_id`,`value`,`row_id`) VALUES (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?)
```

![image](https://github.com/magento/magento2/assets/38497742/81fe0054-71bf-4f10-b601-ebc958fa9c2b)

This is a bug on the `news_from_date` attribute save for the new product.
On 2.4.6-p1 instance magento is trying to save the new product attribute data still using the already existing product `row_id` which causes this integrity constraint violation (i.e. this would indeed create a duplicated record on the `CATALOG_PRODUCT_ENTITY_DATETIME_ROW_ID_ATTRIBUTE_ID_STORE_ID` index).

Not reproducing on a 2.4.3-p3 instance (the new product attribute save is using the new `row_id` which is expected behavior)

**Comment by Djohn12** [comment] 2023-06-21 15:28
Forget it, I'm not able to reproduce on a fresh 2.4.6 demo so I believe there must be some conflict with third party or custom code.
Thanks anyway !
