### ISSUE TITLE
No accessible label for vault-saved credit card type

### ISSUE THREAD

**Issue by scottsb** [magento/magento2#21089] opened 2019-02-08 21:36 UTC
### Preconditions (*)
All released versions:
* Magento 2.1.16
* Magento 2.2.7
* Magento 2.3.0

### Steps to reproduce (*)
1. Save credit card using a Vault-enabled payment method, such as Braintree.
2. Go to payment step on checkout.

### Expected result (*)
Credit card network icon for saved card should have alt text with the type of credit card, such as "Visa." (An ARIA label would also be acceptable, but alt text is simpler and just as useful.)

### Actual result (*)
Credit card network icon for saved card has no alt text or ARIA label.

**Comment by magento-engcom-team** [comment] 2019-02-08 21:37
Hi @scottsb. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@scottsb do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by scottsb** [comment] 2019-02-08 21:42
Issue is with file `app/code/Magento/Vault/view/frontend/web/template/payment/form.html`. Adding the name is not as trivial as adding the attribute, though, as the type is stored as an abbreviation (such as `"VI"`) rather than a spelled-out name, and it has to be translated on top of that. However, this mapping and translation is not currently available.

**Comment by magento-engcom-team** [comment] 2019-02-08 22:54
Hi @pmclain. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by pmclain** [comment] 2019-02-08 22:55
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-08 22:55
Hi @pmclain. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-08 22:55
Hi @pmclain, here is your [Magento instance](https://i-21089-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21089-2-3-develop.instances.magento-community.engineering/admin](https://i-21089-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-02-08 23:05
:white_check_mark: Confirmed by @pmclain
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by pmclain** [comment] 2019-02-08 23:06
Stored payment method in checkout on 2.3-develop
<img width="987" alt="screen shot 2019-02-08 at 6 03 33 pm" src="https://user-images.githubusercontent.com/12674247/52510978-2aa09300-2bcc-11e9-886f-45b12268e245.png">

**Comment by magento-engcom-team** [comment] 2019-02-08 23:08
Hi @pmclain. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by pmclain** [comment] 2019-02-08 23:09
@scottsb good find! I'm working on this now.

**Comment by scottsb** [comment] 2019-02-08 23:54
Wow, fast turnaround! 💯

**Comment by magento-engcom-team** [comment] 2019-02-12 17:48
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-02-12 17:48
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98226` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-02-13 21:25
Hi @scottsb. Thank you for your report. 
The issue has been fixed in magento/magento2#21090 by @pmclain in 2.3-develop branch
Related commit(s):
 - [8483e9479885e420f92f970535362d4fb99b0207](https://github.com/magento/magento2/commit/8483e9479885e420f92f970535362d4fb99b0207)
 - [db4c00cebb227f7a5ff1846de78be4838f78759d](https://github.com/magento/magento2/commit/db4c00cebb227f7a5ff1846de78be4838f78759d)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-02-13 21:25 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Vault

**Comment by magento-engcom-team** [comment] 2019-02-22 14:45
Hi @scottsb. Thank you for your report. 
The issue has been fixed in magento/magento2#21206 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [f40d13914fae5a44b056d2cd1ef8dd7964020b78](https://github.com/magento/magento2/commit/f40d13914fae5a44b056d2cd1ef8dd7964020b78)
 - [4a0dc53116e94291e4a466241853383ea1eb9b77](https://github.com/magento/magento2/commit/4a0dc53116e94291e4a466241853383ea1eb9b77)

The fix will be available with the upcoming 2.2.9 release.
