### ISSUE TITLE
allowDrug? ;-)

### ISSUE THREAD

**Issue by bartspiering** [magento/magento2#19917] opened 2018-12-21 04:38 UTC
### Summary (*)
This file contains an argument called 'allowDrug': vendor/magento/module-catalog/view/adminhtml/templates/catalog/product/attribute/set/main.phtml

### Examples (*)
Check this file: vendor/magento/module-catalog/view/adminhtml/templates/catalog/product/attribute/set/main.phtml

### Proposed solution
I would assume it should be 'allowDrag'

**Comment by magento-engcom-team** [comment] 2018-12-21 04:38
Hi @bartspiering. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@bartspiering do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by bartspiering** [comment] 2018-12-21 04:39
Found in Magento 2.3

**Comment by magento-engcom-team** [comment] 2018-12-21 04:41
Hi @GovindaSharma. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2018-12-21 04:49
@GovindaSharma Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97273`, `MAGETWO-97274` were created

**Comment by magento-engcom-team** [comment] 2018-12-22 23:40
Hi @bartspiering. Thank you for your report. 
The issue has been fixed in magento/magento2#19918 by @GovindaSharma in 2.3-develop branch
Related commit(s):
 - [f2383b84b4fca2c3bc8d112a62a9599377363334](https://github.com/magento/magento2/commit/f2383b84b4fca2c3bc8d112a62a9599377363334)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2018-12-22 23:40 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Progress: PR Created

**Comment by magento-engcom-team** [comment] 2018-12-30 21:30
Hi @bartspiering. Thank you for your report. 
The issue has been fixed in magento/magento2#19949 by @maheshWebkul721 in 2.2-develop branch
Related commit(s):
 - [e20e824048885860954e791ac9511431d7858919](https://github.com/magento/magento2/commit/e20e824048885860954e791ac9511431d7858919)

The fix will be available with the upcoming 2.2.8 release.
