### ISSUE TITLE
USPS "Priority Mail International" not available

### ISSUE THREAD

**Issue by steverobbins** [magento/magento2#10734] opened 2017-08-31 19:59 UTC
### Preconditions
1. Magento 2.1.8 (fresh install, no customizations)
2. PHP 7.0.20
3. MySQL 5.6.35

### Steps to reproduce
1. Enable USPS shipping method, add credentials, live mode, select "Priority Mail International" in allowed methods
2. Add product (configurable, if it matters) to cart, begin checkout, add international shipping address

### Expected result
1. "Priority Mail International" shipping method should be offered

### Actual result
1. "Priority Mail International" is not offered

### More info
You can see that `<Service ID="2">` is returned from USPS in the `debug.log`, and `INT_2` is selected in allowed methods in `core_config_data`.

```
mysql> select * from core_config_data where path like "%usps%" and path not like "%userid" and path not like "%password";
+-----------+---------+----------+--------------------------------------+-----------------------------------------------------------+
| config_id | scope   | scope_id | path                                 | value                                                     |
+-----------+---------+----------+--------------------------------------+-----------------------------------------------------------+
|       386 | default |        0 | carriers/usps/active                 | 1                                                         |
|       387 | default |        0 | carriers/usps/gateway_url            | http://production.shippingapis.com/ShippingAPI.dll        |
|       388 | default |        0 | carriers/usps/gateway_secure_url     | https://secure.shippingapis.com/ShippingAPI.dll           |
|       389 | default |        0 | carriers/usps/title                  | USPS                                                      |
|       390 | default |        0 | carriers/usps/mode                   | 1                                                         |
|       391 | default |        0 | carriers/usps/shipment_requesttype   | 0                                                         |
|       392 | default |        0 | carriers/usps/container              | VARIABLE                                                  |
|       393 | default |        0 | carriers/usps/size                   | REGULAR                                                   |
|       394 | default |        0 | carriers/usps/machinable             | true                                                      |
|       395 | default |        0 | carriers/usps/max_package_weight     | 70                                                        |
|       396 | default |        0 | carriers/usps/handling_type          | P                                                         |
|       397 | default |        0 | carriers/usps/handling_action        | O                                                         |
|       398 | default |        0 | carriers/usps/handling_fee           | 15                                                        |
|       400 | default |        0 | carriers/usps/free_method            | NULL                                                      |
|       401 | default |        0 | carriers/usps/free_shipping_subtotal | 0.00                                                      |
|       402 | default |        0 | carriers/usps/specificerrmsg         | Please type in your full address to all shipping options. |
|       403 | default |        0 | carriers/usps/sallowspecific         | 0                                                         |
|       404 | default |        0 | carriers/usps/specificcountry        | NULL                                                      |
|       405 | default |        0 | carriers/usps/debug                  | 1                                                         |
|       406 | default |        0 | carriers/usps/showmethod             | 0                                                         |
|       407 | default |        0 | carriers/usps/sort_order             | 2                                                         |
|       408 | default |        0 | carriers/usps/free_shipping_enable   | 0                                                         |
|      1100 | default |        0 | carriers/usps/allowed_methods        | INT_1,INT_2,INT_15,2                                      |
+-----------+---------+----------+--------------------------------------+-----------------------------------------------------------+
23 rows in set (0.00 sec)
```

```
[2017-08-31 19:48:46] main.DEBUG: array (
  'request' => '<?xml version="1.0" encoding="UTF-8"?>
<IntlRateV2Request USERID="****"><Revision>2</Revision><Package ID="0"><Pounds>1</Pounds><Ounces>8</Ounces><MailType>All</MailType><ValueOfContents>74.97</ValueOfContents><Country>Indonesia</Country><Container>VARIABLE</Container><Size>REGULAR</Size><Width/><Length/><Height/><Girth/></Package></IntlRateV2Request>
',
  'result' => '<?xml version="1.0" encoding="UTF-8"?>
<IntlRateV2Response><Package ID="0"><Prohibitions>Books and periodicals printed in any Indonesian language and published outside of Indonesia, except educational books approved by the Indonesian Department of Commerce.
Cloth and batik designs and sarongs.
Cocoa leaves, dried, undried, or powdered.
Coins; banknotes; currency notes (paper money); securities of any kind payable to bearer; traveler\'s checks; platinum, gold, or silver (manufactured or not); precious stones; jewelry; and other valuable articles.
Indonesian national currency (rupiahs).
Perishable infectious biological substances.
Radioactive materials.
Used articles including clothing.</Prohibitions><Restrictions>Import licenses are required for commercial shipments. The following articles are not permitted in commercial shipments: articles of gold or silver, including tableware; pens and pencils ornamented with precious metal; calendar watches; linen clothing; natural silk goods; children\'s toys operated by steam or electricity; leather goods; coffee essences; and coffee substitutes; and molasses and sugar substitutes.</Restrictions><Observations>1. Customs declarations must show both the gross weight of the entire shipment and the net weight of each item in the shipment. 
2. Addressees are required to obtain special authorization to receive gift shipments that contain any articles that are considered "luxury or semi-luxury" items (e.g., various kinds of haberdashery, technical goods, foodstuffs, office supplies, cameras and projectors) by the Indonesian authorities. 
3. Gift shipments must be endorsed "Gift shipment - For the personal use of the addressee."
4. Many articles are subject to an import license or special authorization by the Indonesian authorities. Therefore, senders should ascertain from the addressee before mailing whether the necessary documents are held.</Observations><CustomsForms>First-Class Mail International items and Priority Mail International Flat Rate Envelopes and Small Flat Rate Boxes: 
PS Form 2976 (see 123.61)
Priority Mail International parcels:
PS Form 2976-A inside 2976-E (envelope)</CustomsForms><ExpressMail>Country Code:
ID  

Reciprocal Service Name:  
Express Mail Service (EMS)  

Required Customs Form/Endorsement    
1. Correspondence, business papers, canceled checks, and computer cards and printouts.
PS Form 2976-B placed inside PS Form 2976-E (plastic envelope). Endorse items clearly next to mailing label as BUSINESS PAPERS.
 
2. Merchandise samples without commercial value, microfilm, microfiche, and magnetic tapes and disks.
PS Form 2976-B placed inside PS Form 2976-E (plastic envelope).
 
3. Merchandise and all articles subject to customs duty.
PS Form 2976-B placed inside PS Form 2976-E (plastic envelope).


Note:
Coins; banknotes; currency notes, including paper money; securities of any kind payable to bearer; traveler\'s checks; platinum, gold, and silver; precious stones; jewelry; watches; and other valuable articles are prohibited in Priority Mail Express International shipments to Indonesia.

Areas Served:

Amboina			97000-97119, 97231-97239 
Balikpapan		76100-76199 (in Kalimantan Island)
Banda Aceh		23000
Bandara Soekarno-Hatta  19101-19109 
Bandung 		40000-40199, 40201-40299 
Banjarmasin		70000-70199, 70201-70299 
Batam			29400-29499 (in Raiu Island) 
Bekasi			17000-17199 
Bengkulu		38000 
Bogor			16000, 16100-16199 
Bontang			75300 
Bukittinggi		26100-26199 
Cianjur			43200 
Cibinong		16900 
Cilegon			42400-42419, 42441-42449 
Cimahi			40500 
Ciputat			15400-15419, 15451-15459 
Cirebon			45100
Denpasar		80000-80199, 80201-80299 (in Bali Island) 
Depok			16400-16499 
Jakarta (Djakarta)	10000-10999, 11000, 12000, 13000, 14000 (except Pulan Seribu), 19101-19109 (in Java Island) 
Jambi			36000 
Jayapura		99000-99119, 99221-99229 
Karawang		41300
Kendari			93000
Kudus			59300
Kupang			85000-85199, 85201-85299 
Lhokseumawe		24300-24399 
Madiun			63100 
Magelang		56100 
Malang			65100-65199 
Manado			95000-95199, 95201-95299 (in Sulawesi Island) 
Mataram			83000 
Medan			20000-20199, 20201-20299 (in Sumatra island)
Mojokerto		61300 
Padang			25000-25199, 25201-25299 (in Sumatra Island) 
Palembang		30000-30199, 30201-30299 
Palu			94000 
Pangkalpinang	33100 
Pekanbaru		28000-28199, 28201-28299 (in Sumatra Island) 
Pondokgede		17400-17499 
Pontianak		78000-78199, 78201-78299 (in Kalimantan Island) 
Purwokerto		53100 
Salatiga		50700 
Samarinda		75000-75199, 75201-75299 
Sawangan		16500-16599 
Semarang		50000-50199, 50201-50299 (in Java Island) 
Serang			42100 
Solo			57100-57119, 57121-57129 
Sukabumi		43100 
Sukoharjo		57500 
Surabaya		60000-60199 (in Java Island), 60400 
Tangeramg		15000-15199 
Tanjungkarang	35000 
Tanjungpinang 	29100-29199
Tarakan			77100
Ujung Pandang	90000-90199, 90201-90299 (in Sulawesi Island) 
Ungaran			50500 
Yogyakarta		55000-55199, 55201-55299</ExpressMail><AreasServed>Please reference Express Mail for Areas Served.</AreasServed><AdditionalRestrictions>No Additional Restrictions Data found.</AdditionalRestrictions><Service ID="12"><Pounds>1</Pounds><Ounces>8</Ounces><MailType>All</MailType><Container>VARIABLE</Container><Size>REGULAR</Size><Width>0.0</Width><Length>0.0</Length><Height>0.0</Height><Girth>0.0</Girth><Country>INDONESIA</Country><Postage>114.25</Postage><ExtraServices><ExtraService><ServiceID>106</ServiceID><ServiceName>Insurance</ServiceName><Available>True</Available><Price>0.00</Price><DeclaredValueRequired>True</DeclaredValueRequired></ExtraService></ExtraServices><ValueOfContents>74.97</ValueOfContents><SvcCommitments>1 - 3 business days to many major markets</SvcCommitments><SvcDescription>USPS GXG&amp;lt;sup&amp;gt;&amp;#8482;&amp;lt;/sup&amp;gt; Envelopes</SvcDescription><MaxDimensions>USPS-Produced regular size cardboard envelope (12-1/2" x 9-1/2"), the legal-sized cardboard envelope (15" x 9-1/2") and the GXG Tyvek envelope (15-1/2" x 12-1/2")</MaxDimensions><MaxWeight>70</MaxWeight></Service><Service ID="1"><Pounds>1</Pounds><Ounces>8</Ounces><MailType>All</MailType><Container>VARIABLE</Container><Size>REGULAR</Size><Width>0.0</Width><Length>0.0</Length><Height>0.0</Height><Girth>0.0</Girth><Country>INDONESIA</Country><Postage>66.50</Postage><ExtraServices><ExtraService><ServiceID>107</ServiceID><ServiceName>Insurance</ServiceName><Available>True</Available><Price>0.00</Price><DeclaredValueRequired>True</DeclaredValueRequired></ExtraService></ExtraServices><ValueOfContents>74.97</ValueOfContents><SvcCommitments>3 - 5 business days to many major markets</SvcCommitments><SvcDescription>Priority Mail Express International&amp;lt;sup&amp;gt;&amp;#8482;&amp;lt;/sup&amp;gt;</SvcDescription><MaxDimensions>Max. length 36", max. length plus girth 79"</MaxDimensions><MaxWeight>66</MaxWeight></Service><Service ID="10"><Pounds>1</Pounds><Ounces>8</Ounces><MailType>All</MailType><Container>VARIABLE</Container><Size>REGULAR</Size><Width>0.0</Width><Length>0.0</Length><Height>0.0</Height><Girth>0.0</Girth><Country>INDONESIA</Country><Postage>61.50</Postage><ExtraServices><ExtraService><ServiceID>107</ServiceID><ServiceName>Insurance</ServiceName><Available>True</Available><Price>0.00</Price><DeclaredValueRequired>True</DeclaredValueRequired></ExtraService></ExtraServices><ValueOfContents>74.97</ValueOfContents><SvcCommitments>3 - 5 business days to many major markets</SvcCommitments><SvcDescription>Priority Mail Express International&amp;lt;sup&amp;gt;&amp;#8482;&amp;lt;/sup&amp;gt; Flat Rate Envelope</SvcDescription><MaxDimensions>USPS-Produced Envelope: 12-1/2" x 9-1/2"&lt;br>Maximum weight 4 pounds.</MaxDimensions><MaxWeight>4</MaxWeight></Service><Service ID="17"><Pounds>1</Pounds><Ounces>8</Ounces><MailType>All</MailType><Container>VARIABLE</Container><Size>REGULAR</Size><Width>0.0</Width><Length>0.0</Length><Height>0.0</Height><Girth>0.0</Girth><Country>INDONESIA</Country><Postage>61.50</Postage><ExtraServices><ExtraService><ServiceID>107</ServiceID><ServiceName>Insurance</ServiceName><Available>True</Available><Price>0.00</Price><DeclaredValueRequired>True</DeclaredValueRequired></ExtraService></ExtraServices><ValueOfContents>74.97</ValueOfContents><SvcCommitments>3 - 5 business days to many major markets</SvcCommitments><SvcDescription>Priority Mail Express International&amp;lt;sup&amp;gt;&amp;#8482;&amp;lt;/sup&amp;gt; Legal Flat Rate Envelope</SvcDescription><MaxDimensions>USPS-Produced Envelope: 15" x 9-1/2"&lt;br>Maximum weight 4 pounds.</MaxDimensions><MaxWeight>4</MaxWeight></Service><Service ID="27"><Pounds>1</Pounds><Ounces>8</Ounces><MailType>All</MailType><Container>VARIABLE</Container><Size>REGULAR</Size><Width>0.0</Width><Length>0.0</Length><Height>0.0</Height><Girth>0.0</Girth><Country>INDONESIA</Country><Postage>61.50</Postage><ExtraServices><ExtraService><ServiceID>107</ServiceID><ServiceName>Insurance</ServiceName><Available>True</Available><Price>0.00</Price><DeclaredValueRequired>True</DeclaredValueRequired></ExtraService></ExtraServices><ValueOfContents>74.97</ValueOfContents><SvcCommitments>3 - 5 business days to many major markets</SvcCommitments><SvcDescription>Priority Mail Express International&amp;lt;sup&amp;gt;&amp;#8482;&amp;lt;/sup&amp;gt; Padded Flat Rate Envelope</SvcDescription><MaxDimensions>USPS-Produced Envelope: 12-1/2" x 9-1/2"&lt;br>Maximum weight 4 pounds.</MaxDimensions><MaxWeight>4</MaxWeight></Service><Service ID="2"><Pounds>1</Pounds><Ounces>8</Ounces><MailType>All</MailType><Container>VARIABLE</Container><Size>REGULAR</Size><Width>0.0</Width><Length>0.0</Length><Height>0.0</Height><Girth>0.0</Girth><Country>INDONESIA</Country><Postage>49.70</Postage><ExtraServices/><ValueOfContents>74.97</ValueOfContents><InsComment>SERVICE</InsComment><SvcCommitments>6 - 10 business days to many major markets</SvcCommitments><SvcDescription>Priority Mail International&amp;lt;sup&amp;gt;&amp;#174;&amp;lt;/sup&amp;gt;</SvcDescription><MaxDimensions>Max. length 42", max. length plus girth combined 79"</MaxDimensions><MaxWeight>44</MaxWeight></Service><Service ID="11"><Pounds>1</Pounds><Ounces>8</Ounces><MailType>All</MailType><Container>VARIABLE</Container><Size>REGULAR</Size><Width>0.0</Width><Length>0.0</Length><Height>0.0</Height><Girth>0.0</Girth><Country>INDONESIA</Country><Postage>88.95</Postage><ExtraServices/><ValueOfContents>74.97</ValueOfContents><InsComment>SERVICE</InsComment><SvcCommitments>6 - 10 business days to many major markets</SvcCommitments><SvcDescription>Priority Mail International&amp;lt;sup&amp;gt;&amp;#174;&amp;lt;/sup&amp;gt; Large Flat Rate Box</SvcDescription><MaxDimensions>USPS-Produced Box: 23-11/16" x 11-3/4" x 3" or 12" x 12" x 5-1/2"&lt;br>Maximum weight 20 pounds.</MaxDimensions><MaxWeight>20</MaxWeight></Service><Service ID="9"><Pounds>1</Pounds><Ounces>8</Ounces><MailType>All</MailType><Container>VARIABLE</Container><Size>REGULAR</Size><Width>0.0</Width><Length>0.0</Length><Height>0.0</Height><Girth>0.0</Girth><Country>INDONESIA</Country><Postage>67.95</Postage><ExtraServices/><ValueOfContents>74.97</ValueOfContents><InsComment>SERVICE</InsComment><SvcCommitments>6 - 10 business days to many major markets</SvcCommitments><SvcDescription>Priority Mail International&amp;lt;sup&amp;gt;&amp;#174;&amp;lt;/sup&amp;gt; Medium Flat Rate Box</SvcDescription><MaxDimensions>USPS-Produced Box: 13-5/8" x 11-7/8" x 3-3/8" or 11" x 8-1/2" x 5-1/2"&lt;br>Maximum weight 20 pounds.</MaxDimensions><MaxWeight>20</MaxWeight></Service><Service ID="16"><Pounds>1</Pounds><Ounces>8</Ounces><MailType>All</MailType><Container>VARIABLE</Container><Size>REGULAR</Size><Width>0.0</Width><Length>0.0</Length><Height>0.0</Height><Girth>0.0</Girth><Country>INDONESIA</Country><Postage>31.95</Postage><ExtraServices/><ValueOfContents>74.97</ValueOfContents><InsComment>SERVICE</InsComment><SvcCommitments>6 - 10 business days to many major markets</SvcCommitments><SvcDescription>Priority Mail International&amp;lt;sup&amp;gt;&amp;#174;&amp;lt;/sup&amp;gt; Small Flat Rate Box</SvcDescription><MaxDimensions>USPS-Produced Box: 8-5/8" x 5-3/8" x 1-5/8"&lt;br>Maximum weight 4 pounds.</MaxDimensions><MaxWeight>4</MaxWeight></Service><Service ID="24"><Pounds>1</Pounds><Ounces>8</Ounces><MailType>All</MailType><Container>VARIABLE</Container><Size>REGULAR</Size><Width>0.0</Width><Length>0.0</Length><Height>0.0</Height><Girth>0.0</Girth><Country>INDONESIA</Country><Postage>31.95</Postage><ExtraServices/><ValueOfContents>74.97</ValueOfContents><InsComment>SERVICE</InsComment><SvcCommitments>6 - 10 business days to many major markets</SvcCommitments><SvcDescription>Priority Mail International&amp;lt;sup&amp;gt;&amp;#174;&amp;lt;/sup&amp;gt; DVD Flat Rate priced box</SvcDescription><MaxDimensions>USPS-Produced Box: 7-9/16" x 5-7/16" x 5/8"&lt;br>Maximum weight 4 pounds.</MaxDimensions><MaxWeight>4</MaxWeight></Service><Service ID="25"><Pounds>1</Pounds><Ounces>8</Ounces><MailType>All</MailType><Container>VARIABLE</Container><Size>REGULAR</Size><Width>0.0</Width><Length>0.0</Length><Height>0.0</Height><Girth>0.0</Girth><Country>INDONESIA</Country><Postage>31.95</Postage><ExtraServices/><ValueOfContents>74.97</ValueOfContents><InsComment>SERVICE</InsComment><SvcCommitments>6 - 10 business days to many major markets</SvcCommitments><SvcDescription>Priority Mail International&amp;lt;sup&amp;gt;&amp;#174;&amp;lt;/sup&amp;gt; Large Video Flat Rate priced box</SvcDescription><MaxDimensions>USPS-Produced Box: 9-1/4" x 6-1/4" x 2"&lt;br>Maximum weight 4 pounds.</MaxDimensions><MaxWeight>4</MaxWeight></Service><Service ID="8"><Pounds>1</Pounds><Ounces>8</Ounces><MailType>All</MailType><Container>VARIABLE</Container><Size>REGULAR</Size><Width>0.0</Width><Length>0.0</Length><Height>0.0</Height><Girth>0.0</Girth><Country>INDONESIA</Country><Postage>30.95</Postage><ExtraServices/><ValueOfContents>74.97</ValueOfContents><InsComment>SERVICE</InsComment><SvcCommitments>6 - 10 business days to many major markets</SvcCommitments><SvcDescription>Priority Mail International&amp;lt;sup&amp;gt;&amp;#174;&amp;lt;/sup&amp;gt; Flat Rate Envelope</SvcDescription><MaxDimensions>USPS-Produced Envelope: 12-1/2" x 9-1/2"&lt;br>Maximum weight 4 pounds.</MaxDimensions><MaxWeight>4</MaxWeight></Service><Service ID="22"><Pounds>1</Pounds><Ounces>8</Ounces><MailType>All</MailType><Container>VARIABLE</Container><Size>REGULAR</Size><Width>0.0</Width><Length>0.0</Length><Height>0.0</Height><Girth>0.0</Girth><Country>INDONESIA</Country><Postage>30.95</Postage><ExtraServices/><ValueOfContents>74.97</ValueOfContents><InsComment>SERVICE</InsComment><SvcCommitments>6 - 10 business days to many major markets</SvcCommitments><SvcDescription>Priority Mail International&amp;lt;sup&amp;gt;&amp;#174;&amp;lt;/sup&amp;gt; Legal Flat Rate Envelope</SvcDescription><MaxDimensions>USPS-Produced Envelope: 15" x 9-1/2"&lt;br>Maximum weight 4 pounds.</MaxDimensions><MaxWeight>4</MaxWeight></Service><Service ID="23"><Pounds>1</Pounds><Ounces>8</Ounces><MailType>All</MailType><Container>VARIABLE</Container><Size>REGULAR</Size><Width>0.0</Width><Length>0.0</Length><Height>0.0</Height><Girth>0.0</Girth><Country>INDONESIA</Country><Postage>30.95</Postage><ExtraServices/><ValueOfContents>74.97</ValueOfContents><InsComment>SERVICE</InsComment><SvcCommitments>6 - 10 business days to many major markets</SvcCommitments><SvcDescription>Priority Mail International&amp;lt;sup&amp;gt;&amp;#174;&amp;lt;/sup&amp;gt; Padded Flat Rate Envelope</SvcDescription><MaxDimensions>USPS-Produced Envelope: 12-1/2" x 9-1/2"&lt;br>Maximum weight 4 pounds.</MaxDimensions><MaxWeight>4</MaxWeight></Service><Service ID="18"><Pounds>1</Pounds><Ounces>8</Ounces><MailType>All</MailType><Container>VARIABLE</Container><Size>REGULAR</Size><Width>0.0</Width><Length>0.0</Length><Height>0.0</Height><Girth>0.0</Girth><Country>INDONESIA</Country><Postage>30.95</Postage><ExtraServices/><ValueOfContents>74.97</ValueOfContents><InsComment>SERVICE</InsComment><SvcCommitments>6 - 10 business days to many major markets</SvcCommitments><SvcDescription>Priority Mail International&amp;lt;sup&amp;gt;&amp;#174;&amp;lt;/sup&amp;gt; Gift Card Flat Rate Envelope</SvcDescription><MaxDimensions>USPS-Produced Envelope: 10" x 7"&lt;br>Maximum weight 4 pounds.</MaxDimensions><MaxWeight>4</MaxWeight></Service><Service ID="20"><Pounds>1</Pounds><Ounces>8</Ounces><MailType>All</MailType><Container>VARIABLE</Container><Size>REGULAR</Size><Width>0.0</Width><Length>0.0</Length><Height>0.0</Height><Girth>0.0</Girth><Country>INDONESIA</Country><Postage>30.95</Postage><ExtraServices/><ValueOfContents>74.97</ValueOfContents><InsComment>SERVICE</InsComment><SvcCommitments>6 - 10 business days to many major markets</SvcCommitments><SvcDescription>Priority Mail International&amp;lt;sup&amp;gt;&amp;#174;&amp;lt;/sup&amp;gt; Small Flat Rate Envelope</SvcDescription><MaxDimensions>USPS-Produced Envelope: 10" x 6"&lt;br>Maximum weight 4 pounds.</MaxDimensions><MaxWeight>4</MaxWeight></Service><Service ID="19"><Pounds>1</Pounds><Ounces>8</Ounces><MailType>All</MailType><Container>VARIABLE</Container><Size>REGULAR</Size><Width>0.0</Width><Length>0.0</Length><Height>0.0</Height><Girth>0.0</Girth><Country>INDONESIA</Country><Postage>30.95</Postage><ExtraServices/><ValueOfContents>74.97</ValueOfContents><InsComment>SERVICE</InsComment><SvcCommitments>6 - 10 business days to many major markets</SvcCommitments><SvcDescription>Priority Mail International&amp;lt;sup&amp;gt;&amp;#174;&amp;lt;/sup&amp;gt; Window Flat Rate Envelope</SvcDescription><MaxDimensions>USPS-Produced Envelope: 10" x 5" or 12-1/2" x 9-1/2"&lt;br>Maximum weight 4 pounds.</MaxDimensions><MaxWeight>4</MaxWeight></Service><Service ID="14"><Pounds>1</Pounds><Ounces>8</Ounces><MailType>All</MailType><Container>VARIABLE</Container><Size>REGULAR</Size><Width>0.0</Width><Length>0.0</Length><Height>0.0</Height><Girth>0.0</Girth><Country>INDONESIA</Country><Postage>15.77</Postage><ExtraServices><ExtraService><ServiceID>100</ServiceID><ServiceName>Certificate of Mailing</ServiceName><Available>True</Available><Price>1.35</Price></ExtraService><ExtraService><ServiceID>103</ServiceID><ServiceName>Registered Mail</ServiceName><Available>True</Available><Price>14.95</Price></ExtraService><ExtraService><ServiceID>105</ServiceID><ServiceName>Return Receipt</ServiceName><Available>True</Available><Price>3.85</Price></ExtraService></ExtraServices><ValueOfContents>74.97</ValueOfContents><InsComment>SERVICE</InsComment><SvcCommitments>Varies by destination</SvcCommitments><SvcDescription>First-Class Mail&amp;lt;sup&amp;gt;&amp;#174;&amp;lt;/sup&amp;gt; International Large Envelope</SvcDescription><MaxDimensions>Max. length 15", height 12" or thickness 3/4"</MaxDimensions><MaxWeight>4</MaxWeight></Service><Service ID="15"><Pounds>1</Pounds><Ounces>8</Ounces><MailType>All</MailType><Container>VARIABLE</Container><Size>REGULAR</Size><Width>0.0</Width><Length>0.0</Length><Height>0.0</Height><Girth>0.0</Girth><Country>INDONESIA</Country><Postage>22.25</Postage><ExtraServices><ExtraService><ServiceID>100</ServiceID><ServiceName>Certificate of Mailing</ServiceName><Available>True</Available><Price>1.35</Price></ExtraService><ExtraService><ServiceID>103</ServiceID><ServiceName>Registered Mail</ServiceName><Available>True</Available><Price>14.95</Price></ExtraService><ExtraService><ServiceID>105</ServiceID><ServiceName>Return Receipt</ServiceName><Available>True</Available><Price>3.85</Price></ExtraService></ExtraServices><ValueOfContents>74.97</ValueOfContents><InsComment>SERVICE</InsComment><SvcCommitments>Varies by destination</SvcCommitments><SvcDescription>First-Class Package International Service&amp;lt;sup&amp;gt;&amp;#8482;&amp;lt;/sup&amp;gt;</SvcDescription><MaxDimensions>Other than rolls: Max. length 24", max length, height and depth (thickness) combined 36"&lt;br>Rolls: Max. length 36". Max length and twice the diameter combined 42"</MaxDimensions><MaxWeight>4</MaxWeight></Service></Package></IntlRateV2Response>',
) {"is_exception":false} []
```

**Comment by steverobbins** [comment] 2017-08-31 20:28
It looks like this comes down to this method in `\Magento\Usps\Model\Carrier`

```
private function isServiceAvailable(\SimpleXMLElement $service)
{
    foreach ($service->ExtraServices->children() as $child) {
        if (filter_var($child->Available, FILTER_VALIDATE_BOOLEAN)) {
            return true;
        }
    }
    return false;
}
```

So now I'm wondering why extra services need to be available in order of the shipping method to be viable.

**Comment by orlangur** [comment] 2017-08-31 20:49
This was for Canada: https://github.com/magento/magento2/commit/b4c698a40a5774dea622914e5592267d025edc25 

Maybe a more sophisticated fix is required to cover your case and not break previous one.

**Comment by joebusby** [comment] 2017-09-06 04:09
Running:  2.1.8  on LXC Debian 8 and since the last upgrade:
"First-Class Mail Parcel" and "First-Class Mail Package Service" no longer show up as options.  Many customers are forced to use "Priority Mail" costing double for no benefit.

Could this be related to the "Priority International" problem or something else?

**Comment by joebusby** [comment] 2017-09-07 00:21
The First-Class Mail Parcel service may be a different problem.  I have read the postal service changed the name of the service on 9/1.

**Comment by orlangur** [comment] 2017-09-18 08:16
@steverobbins this method seems to be fixed for `develop` in https://github.com/magento/magento2/pull/7729/files, just not backported to `2.1.x` yet.

Up for grabs!

**Comment by orlangur** [comment] 2017-09-18 11:20
Please backport together with https://github.com/magento/magento2/issues/10121#issuecomment-313324729

**Comment by orlangur** [comment] 2017-09-19 22:56
Closing as the fix for this issue is already available on Magento 2.2.0 branch.

Anyone, do not hesitate to create a backport to `2.1-develop` if needed, see https://community.magento.com/t5/Magento-DevBlog/Pull-Requests-for-2-1-x-Patch-Releases/ba-p/65630 for details.

**Closed as completed by orlangur** 2017-09-19 22:56 UTC
Labels: bug report, Issue: Clear Description, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid

**Comment by DKoctopus** [comment] 2018-03-02 07:33
@orlangur Was having the same issue, tried this https://github.com/magento/magento2/commit/69a0f5cea8c7297d4011493a188dd18df60ab8ac 

It fixed for canda but having similar issues for united kingdom, any thoughts?

**Comment by orlangur** [comment] 2018-03-13 15:12
@DKoctopus no idea, didn't even reproduce the issue, try quickly checking git history of this file in 2.2-develop/2.3-develop, if no fix - you have to debug and fix by yourself, ideally contributing PR to a mainline.
