### ISSUE TITLE
Technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later

### ISSUE THREAD

**Issue by kgarrettWY** [magento/magento2#38205] opened 2023-11-20 09:32 UTC
### Preconditions and environment

- Magento version  2.4.6-p1
- Error appears on product search dashboard- cannot search for any products

### Steps to reproduce

NA

### Expected result

NA

### Actual result

NA

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-11-21 10:41
Hi @kgarrettWY,

Thank you for reporting and collaboration.


We are able to search the products.

To speed up the processing of this issue, please provide us with the following information:
* Summary of the issue
* Information on your environment
* Steps to reproduce
* Expected and actual results

Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-12-05 10:36
Hi @kgarrettWY,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38205#issuecomment-1820663291 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-12-11 05:10
Hi @kgarrettWY,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-12-11 05:10 UTC
Labels: Issue: needs update, Reported on 2.4.6-p1
