### ISSUE TITLE
Captcha not shown on contact form

### ISSUE THREAD

**Issue by caitanya89** [magento/magento2#24564] opened 2019-09-12 07:28 UTC
### Preconditions (*)

1. Magento ver. 2.3.2
2.

### Steps to reproduce (*)

1. Create custom contact page using this tutorial https://docs.magento.com/m2/ce/user_guide/stores/contact-us.html

### Expected result (*)

1. Custom contact us page with captcha
2. here is the url default contact form
https://erbede.com/contact/index/index/
![default](https://user-images.githubusercontent.com/6948757/64763109-ed412100-d571-11e9-84ac-29e8850cef9a.png)

### Actual result (*)

1. Custom contact us page without captcha
2. here is the url of custom contact page 
https://erbede.com/contact.html
![custom](https://user-images.githubusercontent.com/6948757/64763028-c551bd80-d571-11e9-8bda-d1eac158d743.png)

**Comment by magento-engcom-team** [comment] 2019-09-12 07:57
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20128` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment] 2020-10-15 17:04
@engcom-Delta  Could you please check is it issue still actual on the latest code.
Google reCAPTCHA  was refactored and moved to security-package, so maybe it was already fixed

**Comment by engcom-Delta** [comment] 2020-10-20 17:02
Hi @caekuro . I'm not able to reproduce issue by steps you described on clean 2.4-develop + [security-package](https://github.com/magento/security-package) 1.0-develop because of https://docs.magento.com/user-guide/stores/contact-us.html#method-2-without-sample-data
I also update Contact Us page using layout xml in custom module and CAPTCHA/reCAPTHA are shown on page
![image](https://user-images.githubusercontent.com/51681379/96619531-f670f580-130e-11eb-97db-f0478318e5e2.png)

Please feel free to create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) in [security-package](https://github.com/magento/security-package) repo
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Delta** 2020-10-20 17:02 UTC
Labels: Issue: Ready for Work, Issue: Format is valid, Component: Contact, Triage: Dev.Experience, Progress: done
