### ISSUE TITLE
Vertex_Tax Module Requires Vertex_RequestLogging

### ISSUE THREAD

**Issue by PivitParkour94** [magento/magento2#34816] opened 2021-12-15 00:56 UTC
### Preconditions (*)

1. Magento 2.4.3-p1

### Steps to reproduce (*)

1. Enable Vertex_Tax module (vendor\vertexinc\module-tax) with Vertex_RequestLogging (vendor\vertexinc\module-request-logging) disabled 
2. Add product to cart

### Expected result (*)

1. Product adds to cart 

### Actual result (*)

1. Error is thrown
2. Nothing logged

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

Notes
I did some digging and found this plugin was breaking 
```
    <type name="Magento\Tax\Api\TaxCalculationInterface">
        <plugin name="vertexTaxCalculation" type="Vertex\Tax\Model\Plugin\TaxCalculationPlugin" sortOrder="1"/>
    </type> 
```

My workaround was to disable all Vertex modules. However this particular bug was very difficult to track down because the request logging module is not listed as a required dependency of the tax module. 

I know this is a bit of an edge case, but when it happens it can be quite frustrating.

Hope this can help.

**Comment by ihor-sviziev** [comment] 2021-12-15 06:28
@magento/ext-vertex, could someone check this issue?

**Comment by navarr** [comment] 2021-12-15 13:38
If I remember correctly, `vertexinc/module-tax` requires there to be an implementation of `vertexinc/module-request-logging-api`.  When I was on the team we attempted to set this up with a requires and a provides (on vertexinc/module-request-logging) but was told it was unsupported.

A quick, incorrect fix would be to simply have vertexinc/module-tax require vertexinc/module-request-logging but it should have no true dependency on that module itself.  It was intended to be written to only use the service contracts.

**Comment by PivitParkour94** [comment] 2021-12-15 22:43
Yeah in my debugging, I found no actual reference to the RequestLogging module, but it seems that the di had gotten into a state that the logger was implicitly trying to load that module. A rather strange issue, that broke all logging and was tedious to track down.

I just don't want someone else to have the same issue.

**Comment by engcom-November** [comment] 2021-12-16 13:46
Hi @PivitParkour94 ,
Thank you for reporting. However, this is an issue related with 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.

**Closed as completed by engcom-November** 2021-12-16 13:46 UTC
Labels: Component: Bundled Extension, Issue: ready for confirmation

**Comment by ihor-sviziev** [comment] 2021-12-16 13:48
@engcom-November, this is bundled extension, not the 3rd party

**Comment by navarr** [comment] 2021-12-16 13:55
Bundled extensions are being unbundled as of 2.4.3; so it's likely OK that it is closed.  A fix could not be backported anyway, since its a composer.json metadata issue.

**Comment by PivitParkour94** [comment] 2021-12-16 22:23
So, if this is closed.... where do I make an issue to have this fixed with Vertex (assuming they are some other 3rd party.. Even though it is bundled in core)?

@navarr unbundled as of 2.4.3? This is on 2.4.3 and still bundled? Sorry I'm just a little confused here

Could someone please explain the choice to close the issue?

**Comment by PivitParkour94** [comment] 2021-12-16 23:31
Turns out as a customer of Magento, you have special access to the 3rd party (but bundled?) module companies customer support.
Just a simple typo from @navarr which meant to say 2.4.4 (so the coming version)
That clears things up. 
Thanks slack!
