### ISSUE TITLE
Missing tax from Grand Total for Invoice created in the admin manually, and order shows an amount due when it should not

### ISSUE THREAD

**Issue by xtremevision** [magento/magento2#38978] opened 2024-07-28 14:41 UTC
### Preconditions and environment

- Magento version: 2.4.3-p3
- Order contained 3 items: 2 simple products & 1 virtual
- Payment was done by credit card, for the entire order amount
- Two invoices were created in the admin: 1 for the simple products & 1 for the virtual
- The grand total is less than the subtotal for the invoice with the simple products. The amount invoiced is missing the tax amount.
- Tax is set to 5% for these products (reduced)

![screenshot-www libhumanitas ro-2024 07 28-10_13_09](https://github.com/user-attachments/assets/aaa828e0-3583-4035-8d8d-92cf5dd7063a)
![screenshot-www libhumanitas ro-2024 07 28-10_12_42](https://github.com/user-attachments/assets/a1e53724-5326-4b59-817a-2e8c8517115d)
![screenshot-www libhumanitas ro-2024 07 28-10_15_19](https://github.com/user-attachments/assets/e5a1bfd8-1e8a-44c2-9bdd-ba48f78ef6f7)

### Steps to reproduce

1. Add 2 simple products to the cart
2. Add 1 virtual product to the cart
3. Checkout
4. Pay with Credit Card - in authorize mode only
5. In admin create two invoices as per above

### Expected result

Grand total should match the subtotal, i.e. contain the tax amount.

### Actual result

Invoiced amount is **incorrect**, it is less than the subtotal, i.e. missing the tax amount.
Looks like invoiced amount is short by 0.72 lei, i.e. the tax amount that belongs to the second invoice for the virtual product.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by xtremevision** [comment] 2024-07-28 14:42
@magento give me 2.4-develop instance

**Comment by xtremevision** [comment] 2024-07-28 18:22
Hi, what happened to the instance? I managed to set it up, test an order and now it's gone.

**Comment by xtremevision** [comment] 2024-07-28 18:33
@magento give me 2.4-develop instance

**Comment by xtremevision** [comment] 2024-07-28 18:41
@magento I am working on this

**Comment by engcom-Delta** [comment] 2024-07-29 09:32
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment] 2024-07-29 13:28
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment] 2024-07-30 04:36
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment] 2024-07-30 06:47
Hi @xtremevision  ,

Thanks for your reporting and collaboration.
We have verified the issue in latest 2.4-develop instance and the issue is not reproducible. Kindly refer the screenshots.

**Steps to Reproduce** -
1. Add 2 Simple products to the cart.
2. Add 1 Virtual product to the cart.
3. Set 5% tax
4. Navigate to cart and observe the subtotal and tax.
![image](https://github.com/user-attachments/assets/aaf26e36-7c1b-4567-8094-2d1002e1bc38)
5. Place order successfully.
![image](https://github.com/user-attachments/assets/727e9d00-c239-4e5b-a330-4ab62704fcab)
![image](https://github.com/user-attachments/assets/8319623a-3911-4a95-8b46-6eff03ce154b)
6. Create 2 invoices, 1st for simple products and 2nd for virtual product.
Invoice 1st
![image](https://github.com/user-attachments/assets/8c1cc4f3-0c4e-4d2e-a2dd-5c6a44edad02)
Invoice 2nd
![image](https://github.com/user-attachments/assets/b3bab4d7-3793-4131-8169-8e9a2d61fa68)
7. Observe the order total calculation should be as expected after invoice creation.
![image](https://github.com/user-attachments/assets/d21b7cb7-cf7c-487d-92b6-6a3a82cf647a)
Total Due is 0 as expected after both invoice creation. Please let us know if we missed anything.

Thanks.

**Comment by xtremevision** [comment] 2024-07-30 13:13
@engcom-Delta Hi, and thank you for taking the time to work on this. I did the same test and could not reproduce the problem following the above steps. However, in the meantime I've discovered the following:

1. There is an "Auto Invoice" module in place that automatically creates invoices for virtual products.
2. The Virtual product invoice was automatically created by the module.
3. The Simple products invoice was created manually by admin staff.
4. The Simple products were also shipped, see screenshot.

Something is going on, somewhere, I just have not found out exactly what and where. Could it be we're not creating the invoice correctly?

`    public function execute(array $commandSubject)
    {
        $paymentDO = $this->subjectReader->readPayment($commandSubject);

        /** @var \Magento\Sales\Model\Order\Payment $payment */
        $payment = $paymentDO->getPayment();
        ContextHelper::assertOrderPayment($payment);

        $order = $payment->getOrder();
        $methodInstance = $payment->getMethodInstance();
        $methodInstance->setStore($order->getStoreId());

	    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
		$logger = $objectManager->create('\Psr\Log\LoggerInterface');
		
        $amount = $this->subjectReader->readAmount($commandSubject);
        $response = $this->subjectReader->readResponseObject($commandSubject);
        
        $this->handler->handle(
            $commandSubject,
            [
                'response' => ['object' => $response]
            ]
        );

        if ($methodInstance->getConfigPaymentAction() == PaymentAction::ACTION_AUTHORIZE_CAPTURE
			|| $order->getIsVirtual()) {

			$logger->info("Xtreme_CaptureStrategyCommand: order " . $order->getId() ." is Virtual - capturing");

            $payment->capture();
            $this->orderRepository->save($order);

            $invoice = $payment->getCreatedInvoice();
			$logger->info("Xtreme_CaptureStrategyCommand: order is Virtual - invoice created, id: ", ['invoiceId' => $invoice->getId()]);
            if (!$order->getIsInProcess()
                && $invoice
                && $this->config->canSendInvoiceNotification($order->getStoreId())
            ) {
				$logger->info("Xtreme_CaptureStrategyCommand: order is Virtual - sending invoice email");
                $this->invoiceSender->send($invoice);
            }
        } else {
            $payment->registerAuthorizationNotification($amount);
    	    $order->setState(\Magento\Sales\Model\Order::STATE_NEW)->setStatus('pending_payu_paid');
            //$history = $order->addStatusHistoryComment('Order is : '.$orderLabel, $order->getStatus());
            //$history->setIsCustomerNotified(true);
            //$history->save(); 
            $this->orderRepository->save($order);

			$logger->info("Xtreme_CaptureStrategyCommand: order " . $order->getId() . " is NOT Virtual - creating partial invoice");

			if(!$order->getIsVirtual())
			{
				$createinvoice = $order->canInvoice();
				if ($createinvoice)
				{
					$itemsArray  = array();
					$subTotal = 0;
					foreach($order->getAllItems() as $orderitem)
					{
						$product = $orderitem->getProduct();
						$attributeSetName = $this->getAttributeSetName($product);
						if( in_array($attributeSetName, ['eBook', 'Audiobook MP3', 'eBook Free']) )
						{
							if($orderitem->getQtyToInvoice() > 0)
							{
								$logger->info("Xtreme_CaptureStrategyCommand: order " . $order->getId() . " is NOT Virtual - adding item to invoiceArray, item id: " . $orderitem->getId());
								
								$id = $orderitem->getId();
								$itemsArray[$id] = $orderitem->getQtyToInvoice();
								$subTotal += $orderitem->getRowTotalInclTax();
							}
						}
						else
						{
						    $logger->info("Xtreme_CaptureStrategyCommand: order " . $orderitem->getId() . ", " . $orderitem->getSku() . " attributeSet: " . $attributeSetName . " - not added to invoice");
						}
					}
					if(count($itemsArray)>0)
					{
						$logger->info("Xtreme_CaptureStrategyCommand: order " . $order->getId() . " is NOT Virtual - creating invoice");

						$shippingAmount = '0.00';
						$subTotal = $subTotal;
						$baseSubtotal = $subTotal;
						$grandTotal = $subTotal;
						$baseGrandTotal = $subTotal;
						$invoice = $this->invoiceService->prepareInvoice($order, $itemsArray);
						$invoice->setShippingAmount($shippingAmount);
						$invoice->setSubtotal($subTotal);
						$invoice->setBaseSubtotal($baseSubtotal);
						$invoice->setGrandTotal($grandTotal);
						$invoice->setBaseGrandTotal($baseGrandTotal);
						$invoice->register();
						$invoice->save();
						
						$logger->info("Xtreme_CaptureStrategyCommand: order " . $order->getId() . " is NOT Virtual - saving transaction");

						$transactionSave = $this->transaction->addObject(
							$invoice
						)->addObject(
							$invoice->getOrder()
						);
						$transactionSave->save();
						
						$logger->info("Xtreme_CaptureStrategyCommand: order " . $order->getId() . " is NOT Virtual - sending email to customer");

						$this->invoiceSender->send($invoice);
						$order->setTotalPaid($grandTotal);
						$order->setBaseTotalPaid($grandTotal);
						$this->orderRepository->save($order);
						$logger->info("Xtreme_CaptureStrategyCommand: order " . $order->getId() . " totalPaid: " . $grandTotal . ", subTotal: " . $subTotal);

						//Send Invoice mail to customer
						$order->addStatusHistoryComment(
							__('Notified customer about invoice creation #%1.', $invoice->getId())
						)
							->setIsCustomerNotified(true)
							->save();
							
						$invoice->setState(2)->save();
					}
					else
					{
						$logger->info("Xtreme_CaptureStrategyCommand: order is NOT Virtual - no items in invoice, invoice not created " . $order->getId());
					}

				}else{
				    return $this;
				}
				
			}
        }
		
        if (!$order->getEmailSent()) {
            $this->orderSender->send($order);
        }
    }

	//Build method to get attribute set
	public function getAttributeSetName($product) {

		$attributeSetRepository = $this->attributeSet->get($product->getAttributeSetId());
		return $attributeSetRepository->getAttributeSetName();
	}`

**Comment by xtremevision** [comment] 2024-07-30 13:20
`
<?php

namespace Xtreme\AutoInvoice\Gateway\Command\Ipn;

use Innobyte\PayU\Gateway\Helper\SubjectReader;
use Innobyte\PayU\Model\Config\Source\PaymentAction;
use Magento\Payment\Gateway\CommandInterface;
use Magento\Payment\Gateway\ConfigInterface;
use Magento\Payment\Gateway\Helper\ContextHelper;
use Magento\Payment\Gateway\Response\HandlerInterface;
use Magento\Sales\Api\OrderRepositoryInterface;
use Magento\Sales\Model\Order\Email\Sender\InvoiceSender;
use Magento\Sales\Model\Order\Email\Sender\OrderSender;
use Magento\Sales\Model\Service\InvoiceService;
use Magento\Framework\DB\Transaction;

class CaptureStrategyCommandPlugin extends \Innobyte\PayU\Gateway\Command\Ipn\CaptureStrategyCommand
{
    /**
     * @var SubjectReader
     */
    private $subjectReader;

    /**
     * @var HandlerInterface
     */
    private $handler;

    /**
     * @var \Innobyte\PayU\Gateway\Config\Config
     */
    private $config;

    /**
     * @var OrderRepositoryInterface
     */
    private $orderRepository;

    /**
     * @var OrderSender
     */
    private $orderSender;

    /**
     * @var InvoiceSender
     */
    private $invoiceSender;

	protected $transaction;
	protected $invoiceService;

	/** @var \Magento\Eav\Api\AttributeSetRepositoryInterface $attributeSet **/
	protected $attributeSet;

    /**
     * CaptureStrategyCommand constructor
     *
     * @param SubjectReader $subjectReader
     * @param HandlerInterface $handler
     * @param ConfigInterface $config
     * @param OrderRepositoryInterface $orderRepository
     * @param OrderSender $orderSender
     * @param InvoiceSender $invoiceSender
     */
    public function __construct(
        SubjectReader $subjectReader,
        HandlerInterface $handler,
        ConfigInterface $config,
        OrderRepositoryInterface $orderRepository,
        OrderSender $orderSender,
        InvoiceSender $invoiceSender,
		Transaction $transaction,
		InvoiceService $invoiceService,
		\Magento\Eav\Api\AttributeSetRepositoryInterface $attributeSet
    ) {
        $this->subjectReader = $subjectReader;
        $this->handler = $handler;
        $this->config = $config;
        $this->orderRepository = $orderRepository;
        $this->orderSender = $orderSender;
        $this->invoiceSender = $invoiceSender;
		$this->attributeSet = $attributeSet;
		$this->invoiceService = $invoiceService;
		$this->transaction = $transaction;
		/*parent::__construct(
			$subjectReader,
			$handler,
			$config,
			$orderRepository,
			$orderSender,
			$invoiceSender);*/
    }

    public function execute(array $commandSubject)
    {
        $paymentDO = $this->subjectReader->readPayment($commandSubject);

        /** @var \Magento\Sales\Model\Order\Payment $payment */
        $payment = $paymentDO->getPayment();
        ContextHelper::assertOrderPayment($payment);

        $order = $payment->getOrder();
        $methodInstance = $payment->getMethodInstance();
        $methodInstance->setStore($order->getStoreId());

	    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
		$logger = $objectManager->create('\Psr\Log\LoggerInterface');
		
        $amount = $this->subjectReader->readAmount($commandSubject);
        $response = $this->subjectReader->readResponseObject($commandSubject);
        
        $this->handler->handle(
            $commandSubject,
            [
                'response' => ['object' => $response]
            ]
        );

        if ($methodInstance->getConfigPaymentAction() == PaymentAction::ACTION_AUTHORIZE_CAPTURE
			|| $order->getIsVirtual()) {

			$logger->info("Xtreme_CaptureStrategyCommand: order " . $order->getId() ." is Virtual - capturing");

            $payment->capture();
            $this->orderRepository->save($order);

            $invoice = $payment->getCreatedInvoice();
			$logger->info("Xtreme_CaptureStrategyCommand: order is Virtual - invoice created, id: ", ['invoiceId' => $invoice->getId()]);
            if (!$order->getIsInProcess()
                && $invoice
                && $this->config->canSendInvoiceNotification($order->getStoreId())
            ) {
				$logger->info("Xtreme_CaptureStrategyCommand: order is Virtual - sending invoice email");
                $this->invoiceSender->send($invoice);
            }
        } else {
            $payment->registerAuthorizationNotification($amount);
    	    $order->setState(\Magento\Sales\Model\Order::STATE_NEW)->setStatus('pending_payu_paid');
            //$history = $order->addStatusHistoryComment('Order is : '.$orderLabel, $order->getStatus());
            //$history->setIsCustomerNotified(true);
            //$history->save(); 
            $this->orderRepository->save($order);

			$logger->info("Xtreme_CaptureStrategyCommand: order " . $order->getId() . " is NOT Virtual - creating partial invoice");

			if(!$order->getIsVirtual())
			{
				$createinvoice = $order->canInvoice();
				if ($createinvoice)
				{
					$itemsArray  = array();
					$subTotal = 0;
					foreach($order->getAllItems() as $orderitem)
					{
						$product = $orderitem->getProduct();
						$attributeSetName = $this->getAttributeSetName($product);
						if( in_array($attributeSetName, ['eBook', 'Audiobook MP3', 'eBook Free']) )
						{
							if($orderitem->getQtyToInvoice() > 0)
							{
								$logger->info("Xtreme_CaptureStrategyCommand: order " . $order->getId() . " is NOT Virtual - adding item to invoiceArray, item id: " . $orderitem->getId());
								
								$id = $orderitem->getId();
								$itemsArray[$id] = $orderitem->getQtyToInvoice();
								$subTotal += $orderitem->getRowTotalInclTax();
							}
						}
						else
						{
						    $logger->info("Xtreme_CaptureStrategyCommand: order " . $orderitem->getId() . ", " . $orderitem->getSku() . " attributeSet: " . $attributeSetName . " - not added to invoice");
						}
					}
					if(count($itemsArray)>0)
					{
						$logger->info("Xtreme_CaptureStrategyCommand: order " . $order->getId() . " is NOT Virtual - creating invoice");

						$shippingAmount = '0.00';
						$subTotal = $subTotal;
						$baseSubtotal = $subTotal;
						$grandTotal = $subTotal;
						$baseGrandTotal = $subTotal;
						$invoice = $this->invoiceService->prepareInvoice($order, $itemsArray);
						$invoice->setShippingAmount($shippingAmount);
						$invoice->setSubtotal($subTotal);
						$invoice->setBaseSubtotal($baseSubtotal);
						$invoice->setGrandTotal($grandTotal);
						$invoice->setBaseGrandTotal($baseGrandTotal);
						$invoice->register();
						$invoice->save();
						
						$logger->info("Xtreme_CaptureStrategyCommand: order " . $order->getId() . " is NOT Virtual - saving transaction");

						$transactionSave = $this->transaction->addObject(
							$invoice
						)->addObject(
							$invoice->getOrder()
						);
						$transactionSave->save();
						
						$logger->info("Xtreme_CaptureStrategyCommand: order " . $order->getId() . " is NOT Virtual - sending email to customer");

						$this->invoiceSender->send($invoice);
						$order->setTotalPaid($grandTotal);
						$order->setBaseTotalPaid($grandTotal);
						$this->orderRepository->save($order);
						$logger->info("Xtreme_CaptureStrategyCommand: order " . $order->getId() . " totalPaid: " . $grandTotal . ", subTotal: " . $subTotal);

						//Send Invoice mail to customer
						$order->addStatusHistoryComment(
							__('Notified customer about invoice creation #%1.', $invoice->getId())
						)
							->setIsCustomerNotified(true)
							->save();
							
						$invoice->setState(2)->save();
					}
					else
					{
						$logger->info("Xtreme_CaptureStrategyCommand: order is NOT Virtual - no items in invoice, invoice not created " . $order->getId());
					}

				}else{
				    return $this;
				}
				
			}
        }
		
        if (!$order->getEmailSent()) {
            $this->orderSender->send($order);
        }
    }

	//Build method to get attribute set
	public function getAttributeSetName($product) {

		$attributeSetRepository = $this->attributeSet->get($product->getAttributeSetId());
		return $attributeSetRepository->getAttributeSetName();
	}
}
`

**Comment by xtremevision** [comment] 2024-07-30 15:27
Ok, I think I found the bug/fix.

use 

`$order->getAllIVisibletems() 
`
instead

and uncomment these lines:

```
$order->setTotalPaid($grandTotal);
$order->setBaseTotalPaid($grandTotal);
$this->orderRepository->save($order);
```

Thank you.

**Comment by engcom-Delta** [comment] 2024-08-27 08:19
Hi @xtremevision ,

We have noticed that this issue has not been updated since long time.
Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Delta** 2024-08-27 08:19 UTC
Labels: Issue: needs update, Reported on 2.4.3-p3
