### ISSUE TITLE
Magento Component grid and system upgrade not working

### ISSUE THREAD

**Issue by abhijitbanik2016** [magento/magento2#5349] opened 2016-06-29 12:05 UTC
Magento 2.0.7 Installed through INSTALLATRON App in Easy apache 4 Server with a configuration of php 5.6 and mysql 5.6

After installation Magento market place connected with system config with marketplace key.

Now when I am trying to get sync in component Manager then showing "please wait" and nothing is happening. If I check the error in browser development mode I found 2 error

Error 1: angular.js:8581The specified value "{{currentPage}}" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+.\d+|.\d+)([eE][-+]?\d+)?

Error:2 http://www.craftallure.com/setup/index.php/componentGrid/sync 500 (Internal Server Error)(anonymous function)

![image](https://cloud.githubusercontent.com/assets/20184139/16451275/ab3dd8a8-3e1f-11e6-8eee-bc6fc2e73d16.png)

And in the "system upgrade" finding an error

Sorry, we can't take that action right now.
![image](https://cloud.githubusercontent.com/assets/20184139/16451261/93589e58-3e1f-11e6-8088-7a95e6ff9953.png)

error in browser development mode is in below The specified value "{{currentPage}}" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+.\d+|.\d+)([eE][-+]?\d+)?

I checked magento Dev site and I settled down Magento Prerequisite With Cronjob and other updates.

In apache error log I found below error [Wed Jun 29 04:23:33.872640 2016] [access_compat:error] [pid 15439] [client 97.74.233.23:36187] AH01797: client denied by server configuration: /home/craftallure/public_html/app/etc/config.php

Please provide some solution.

**Comment by ghost** [comment] 2016-07-04 17:57
You say you added your keys but the symptoms you're describing can be explained by not adding the keys.

The error **Sorry, we can't take that action right now** during System Upgrade usually means you haven't added your [authentication keys](http://devdocs.magento.com/guides/v2.1/comp-mgr/trouble/cman/were-sorry.html). Try these suggestions and let us know if they work.

**Comment by andimov** [comment] 2016-08-05 15:35
@abhijitbanik2016 
Thank you for reporting!
The first mistake that you have a duplicate of https://github.com/magento/magento2/issues/3977 and already fixed on develop branch by commit https://github.com/magento/magento2/commit/8888d9b2d7b1c00c239951b1177fbb552457c73d
Second can be a permission issue. Please, check this url that you have. Please, enable developer mode and check the response body also.

**Comment by andimov** [comment] 2016-08-05 15:51
@abhijitbanik2016 
Please, check this solution for second error: https://github.com/magento/magento2/issues/4756#issuecomment-223439006
Discuss started from https://github.com/magento/magento2/issues/4756#issuecomment-223180243

**Comment by andimov** [comment] 2016-08-19 08:15
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Closed as completed by andimov** 2016-08-19 08:15 UTC
Labels: Progress: needs update, Component: Setup
