### ISSUE TITLE
Save custom attribute not working

### ISSUE THREAD

**Issue by dulv** [magento/magento2#9137] opened 2017-04-05 08:29 UTC
Hi team,
I am using magento 2.1.4
I have created some attribute for customer
When i save, this attribute not woking
Pls help me
http://prntscr.com/esncjv

Thanks

**Comment by korostii** [comment] 2017-04-06 10:43
If you are looking for some help or an advice regarding setup or development please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.
The issues which cannot be consistently reproduced on a clean installation of Magento 2 CE aren't likely to get resolved in here.

Thus if you are, in fact, reporting a technical issue, please try add as much information as possible, including the environment you use, 3rd party themes and modules installed, preconditions, exact steps to follow, stack trace from browser console, even the custom code you're using. These raise the chances of the bug getting reproduced and acknowledged. 
If you don't provide enough information, it is likely that the issue will receive a "needs update" label and will get closed in a couple weeks.

**Comment by veloraven** [comment] 2017-06-26 12:20
@dulv Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by magento-engcom-team** [comment] 2017-09-11 20:23
@dulv we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Closed as completed by magento-engcom-team** 2017-09-11 20:23 UTC
Labels: Progress: needs update, Issue: Format is not valid

**Comment by darkogoles1** [comment] 2017-10-24 05:37
As already wrote [here](https://github.com/magento/magento2/issues/1393), here is a potential resolution of the issue that worked for me: 

When creating the customer attribute, please take care of following things: 
- Attribute is added to the attribute set, group
- Attribute is assigned to customer forms
- And the last one the most important as somehow, people just skip over it and wondering why the customer attribute does not want to save from the backend: Please make sure to set "is_system" flag in "customer_eav_attribute" table to 0, otherwise the attribute will not be saved.

It can be done by setting the attribute option to "system" => 0 in attribute parameters inside the install/upgrade script. 

More about that particular issue can be found [here](http://www.apiworks.net/2017/10/magento-2-is-not-saving-customer-attribute.html).

**Comment by juansumma** [comment] 2018-01-17 15:08
@darkogoles1 but if you set "is_system = 0", you won't see the field in the edit customer form in the admin

**Comment by Puru2016** [comment] 2018-01-19 06:56
I am still not able to save custom attribute value from backend customer section and I am following [this](https://www.mageplaza.com/magento-2-module-development/magento-2-add-customer-attribute-programmatically.html) article.

Can anyone share the solution here please :)
