### ISSUE TITLE
UPS 150+ weight not allowed

### ISSUE THREAD

**Issue by mwdana** [magento/magento2#35733] opened 2022-07-06 15:40 UTC
### Preconditions and environment

Magento Community 2.4.4

### Steps to reproduce

We have items that are exactly 1 pound in weight. When a customer adds 150 of them (150 pounds), a UPS method is listed. When a customer adds 151, no UPS options are shown at checkout.

This issue came up when we updated to 2.4.4. Our settings did not change.

Under stores>configuration>sales>shipping methods, these are my settings for UPS.

Package request type = divide to equal weight (one request)
Destination = Residential
Weight = LBS
Maximum Package Weight = 40
Pickup method = Regular daily rate
Minimum package weight = .1

I don't believe any of the other settings would be related to this issue. Even though we have max package weight at 40 and it's set to divide to equal weight, it is not working. 

### Expected result

In the example where items are 1 pound each and adding quantity 151 to the order provides no UPS options, it SHOULD send a single request to UPS for a quote of 4 boxes of 38 pounds each. 
Our setting is 40 pound max weight per package.
151/4 = 37.75
UPS rounds up to the nearest pound which would be 38.

### Actual result

Instead we get no UPS methods available.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2022-07-08 08:01
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-07-08 09:56
Hi @mwdana ,

We are trying to reproduce the issue...But we are not able to reproduce the issue.
In Admin panel we are not able to set a admin configuration Because i need
1.Access License Number
2.User ID
3.Password
I need above mentioned three information Because once done the admin configuration we will proceed further.
For your Reference i attached the screenshots below
![Screenshot from 2022-07-08 15-24-25](https://user-images.githubusercontent.com/60198592/177967254-a495dcb3-403f-45b6-8e08-737afaf79024.png)


Let us know in case we have missed anything. Thanks

**Comment by mwdana** [comment] 2022-07-08 18:25
https://www.ups.com/upsdeveloperkit
 It is free to open a developer account which should produce the same results. We are not using anything Other than the basic UPS account. Thank you



________________________________

**Comment by engcom-Dash** [comment] 2022-07-11 08:37
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-07-12 08:02
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-07-12 08:14
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-07-12 11:24
Hi @mwdana ,

We have tried to reproduce the issue in Magento 2.4-develop branch the issue is not reproducible.
Please refer the below screenshot for the reference; 
![Screenshot from 2022-07-12 16-39-24](https://user-images.githubusercontent.com/60198592/178477319-b9f5796d-f6e9-4eb6-b0a2-19496ed1e581.png)
![Screenshot from 2022-07-12 16-38-03](https://user-images.githubusercontent.com/60198592/178477327-fcd300fa-4e80-4ffc-bdc4-38a5b95cf5d2.png)
![Screenshot from 2022-07-12 16-37-54](https://user-images.githubusercontent.com/60198592/178477332-2d78e213-cc26-4851-8989-2b2c955c7569.png)
![Screenshot from 2022-07-12 16-37-31](https://user-images.githubusercontent.com/60198592/178477340-e8955d80-71bf-41d8-9dc3-2ec5b4b11bc6.png)
![Screenshot from 2022-07-12 16-36-46](https://user-images.githubusercontent.com/60198592/178477345-a9178f79-6c4c-4ee4-903d-37515e96c975.png)


We have followed the below steps in order to reproduce the issue:

1.Create Simple Product with 1 Pound weight
2.Setup up the configuration---> Under stores>configuration>sales>shipping methods, these are my settings for UPS.
3.Checkout the product with quantity  of 1
4.Checkout the Product with quantity of 151

If the product is quantity is 1...in checkout page  UPS shipping methods is not displaying.Even the product quantity is 151 in checkout page UPS shipping methods is not displaying.

Let us know in case we have missed anything. 

Thanks !!!

**Comment by mwdana** [comment] 2022-07-12 17:20
If the address entered is not recognized by UPS, it will not yield results. Can you try with this for the shipping address?

1510 Oliver Road
Fairfield, California 94534




________________________________

**Comment by engcom-Dash** [comment] 2022-07-13 11:30
@magento give me 2.4-develop instance

**Comment by mwdana** [comment] 2022-07-13 12:53
Are you saying you are receiving shipping amounts for 151 pounds?


________________________________

**Comment by engcom-Dash** [comment] 2022-07-14 10:45
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-07-14 11:04
Hi @mwdana ,

We are getting Actual result...there is no shipping methods showing  when we are checkout with 151 pounds.So we are confirming the issue.

Thanks!!!

**Comment by engcom-Dash** [comment] 2022-07-15 06:44
@ magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-07-15 09:53
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-07-20 06:27
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-08-11 07:38
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-08-11 11:02
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-08-11 12:22
Hi @mwdana ,

We are trying to reproduce the issue but we are not able reproduce...

When we are adding the product as 1 as well as 151 all the shipping methods are listing.

Let us know if we are missing anything...

**Comment by mwdana** [comment] 2022-08-11 15:38
Can I test in your environment as well?

**Comment by engcom-Dash** [comment] 2022-08-16 15:16
Hi @mwdana ,

You can test magento 2.4-develop cloud instance...Might be you will get some idea.

Thanks!!!

**Comment by mwdana** [comment] 2022-08-23 16:12
> Hi @mwdana ,
> 
> You can test magento 2.4-develop cloud instance...Might be you will get some idea.
> 
> Thanks!!!


I made a test product 1 pound.
I added the quantity to 150 and UPS was displayed as a shipping option at checkout. (this is exactly 150 pounds)
I increased the quantity to 151 and UPS was not available. (this is 151 pounds)

I removed the item and tested with another item.

I changed a different test product to .5 pound.
I added the quantity 300 and UPS was displayed as a shipping option. (this is exactly 150 pounds)
I increased the quantity to 301 and UPS was not available. (this is 150.5 pounds)

The issue remains for me.

See setting screenshots for reference.

![ups-setting-1](https://user-images.githubusercontent.com/108820761/186208214-ec963294-30f7-42ec-a9f3-6f2e155b59b8.png)
![ups-setting-2](https://user-images.githubusercontent.com/108820761/186208230-7c6bea0c-9a65-4e61-8d69-7730983d0d2a.png)

**Comment by mwdana** [comment] 2022-08-25 23:13
@engcom-Dash please see prior comment for testing settings. Thank you.

**Comment by engcom-November** [comment] 2022-10-10 11:28
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-10-10 12:15
Hi @mwdana ,
Verified the issue again on both Local 2.4-develop instance and cloud instance but the issue is not reproducible in both front end and Admin order creation page. Please find the steps performed below:
1. Configured UPS Shipping method as mentioned [above](https://github.com/magento/magento2/issues/35733#issuecomment-1224291757)
2. Created a simple product with Weight 1 LBS
3. Front end - Added product to cart with qty: 150
4. Updated shopping cart with qty: 151 and proceed to checkout - UPS Shipping Methods are displayed. No issue.
5. Created product with weight 0.5 LBS
6. Added product with qty: 300  - UPS shipping methods displayed. No issue
7. Updated shopping cart with qty: 301. No issue: UPS shipping methods displayed and user able to place order from both admin and front end
![image](https://user-images.githubusercontent.com/60198231/194863865-677980fe-3d55-4c72-9f09-1c5377276202.png)
![image](https://user-images.githubusercontent.com/60198231/194863806-0ae1c048-9328-41f9-99f2-d9a5270e9619.png)
![image](https://user-images.githubusercontent.com/60198231/194863955-3d2b40e7-3992-4170-80d3-4cd7ad0819b3.png)
Kindly check the behavior on Magento 2.4-develop instance as it is having latest code base (upcoming 2.4.x release) and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-10-27 02:51
Hi @mwdana ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-10-27 02:51 UTC
Labels: Reproduced on 2.4.x, Priority: P1, Progress: done, Issue: needs update, Area: Admin UI

**Comment by mwdana** [comment] 2022-10-27 15:47
We are still having the issue, but we can't determine where the issue lies -  if it's core Magento, with an extension, or something else. Thanks.



________________________________
