### ISSUE TITLE
Internal Server Error in /V1/products/cost API Endpoint

### ISSUE THREAD

**Issue by mlf20** [magento/magento2#35933] opened 2022-08-12 10:27 UTC
### Preconditions and environment

- Magento version 2.4

### Steps to reproduce

1. Retrieve auth token from the admin endpoint /V1/integration/admin/
2. Request endpoint:

```
curl -H 'Content-Type: application/json' -H 'Authorization: Bearer' <AUTH TOKEN> -d '{"prices": ""}' -X POST http://<MAGENTO_URL>/pub/rest/default/V1/products/cost
```

### Expected result

Returns a 400 error as the request is malformed.

### Actual result

Returns a 500 status code from a null TypeError .

### Additional information

output of var/log/system.log:
```
	[2022-08-01T13:01:33.810456+00:00] main.CRITICAL: TypeError: Magento\Catalog\Model\Product\Price\CostStorage::update(): Argument #1 ($prices) must be of type array, null given in /magento/vendor/magento/module-catalog/Model/Product/Price/CostStorage.php:116
	Stack trace:
	#0 [internal function]: Magento\Catalog\Model\Product\Price\CostStorage->update()
	#1 /magento/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array()
	#2 /magento/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process()
	#3 /magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch()
	#4 /magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent()
	#5 /magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}()
	#6 /magento/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins()
	#7 /magento/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch()
	#8 /magento/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
	#9 /magento/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
	#10 /magento/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
	#11 {main} [] []
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-08-12 15:09
Hi @mlf20 ,
Thank you for reporting and collaboration. The exception mentioned in all the below issues reported by you is the similar error/ issue which is not reproducible on 2.4-develop branch. Can we close all the other issues and track in a single bug: https://github.com/magento/magento2/issues/35934
Similar issues having same kind of exception:
https://github.com/magento/magento2/issues/35934
https://github.com/magento/magento2/issues/35937
https://github.com/magento/magento2/issues/35936
https://github.com/magento/magento2/issues/35933

We are getting a 400 error as the request is malformed.
Kindly check Magento system requirements and 3rd party exntensions / modules enabled is causing this issue.
Kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if you are still facing any issues.
Thank you

**Comment by mlf20** [comment] 2022-08-12 15:28
Hi @engcom-November 

My apologies, I have gone over my logs and the payload in the body should be '{"prices": ""}' .

This reproduces the issue on Magento 2.4-dev as shown below:
![Screenshot 2022-08-12 at 16 26 45](https://user-images.githubusercontent.com/83755999/184388230-088f1272-45ed-4a16-9f0c-b3a56cbbb404.png)

**Comment by engcom-November** [comment] 2022-08-16 10:49
Hi @mlf20 ,
Thanks for the update. Verified the issue on Magento 2.4-develop branch and the issue is reproducible with above payload. But however, similar issue has been confirmed https://github.com/magento/magento2/issues/35934. Since the issue occurred for all these API's is with same/ similar payload and with similar exception / error, we are tracking this in a single bug mentioning all endpoints / API's https://github.com/magento/magento2/issues/35934 and closing this issue as duplicate. Please move on to this issue for latest updates / solutions on the same.
Thank you.

**Closed as completed by engcom-November** 2022-08-16 10:49 UTC
Labels: duplicate, Issue:  Cannot Reproduce, Issue: needs update
