### ISSUE TITLE
Error: Call to a member function shouldDisplayProductCountOnLayer() on null in /vendor/magento/module-layered-navigation/view/frontend/templates/layer/filter.phtml:21

### ISSUE THREAD

**Issue by pratikkamani** [magento/magento2#31024] opened 2020-11-24 07:01 UTC
### Preconditions (*)

1. Magento 2.4.1 (Upgraded from Magento 2.3.3)
2. Visit category page

### Steps to reproduce (*)

1. Upgrade the site from Magento 2.3.3 to Magento 2.4.1
2. Open the category listing page

### Expected result (*)

1. Need to display the category product.

### Actual result (*)

1. 
![issue](https://user-images.githubusercontent.com/9292282/100059351-ea69dd80-2e50-11eb-9b15-c2c151900750.png)

---
Error: Call to a member function shouldDisplayProductCountOnLayer() on null in /vendor/magento/module-layered-navigation/view/frontend/templates/layer/filter.phtml:21

**Comment by engcom-Delta** [comment] 2020-12-14 12:30
Hi @pratikkamani , thank you for your report. I'm not able to reproduce issue on clean magento without custom modules. I tried upgrade from 2.3.6 to 2.4.1 according [docs](https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html) and there was no issue after upgrade

Could you provide additional magento configuration you have before upgrade?

**Comment by mohanwbsofttech** [comment] 2020-12-30 14:23
I also have the same problem
Shop By
Shopping Options
Colour
Black Error: Call to a member function shouldDisplayProductCountOnLayer() on null in /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/module-layered-navigation/view/frontend/templates/layer/filter.phtml:21 Stack trace: #0 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/TemplateEngine/Php.php(71): include() #1 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php->render() #2 /var/www/vhosts/theacrylicstore.co.uk/htdocs/generated/code/Magento/LayeredNavigation/Block/Navigation/FilterRenderer/Interceptor.php(86): Magento\Framework\View\Element\Template->fetchView() #3 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Element/Template.php(303): Magento\LayeredNavigation\Block\Navigation\FilterRenderer\Interceptor->fetchView() #4 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/module-layered-navigation/Block/Navigation/FilterRenderer.php(29): Magento\Framework\View\Element\Template->_toHtml() #5 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\LayeredNavigation\Block\Navigation\FilterRenderer->render() #6 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\LayeredNavigation\Block\Navigation\FilterRenderer\Interceptor->___callParent() #7 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/module-swatches/Model/Plugin/FilterRenderer.php(63): Magento\LayeredNavigation\Block\Navigation\FilterRenderer\Interceptor->Magento\Framework\Interception\{closure}() #8 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Swatches\Model\Plugin\FilterRenderer->aroundRender() #9 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\LayeredNavigation\Block\Navigation\FilterRenderer\Interceptor->Magento\Framework\Interception\{closure}() #10 /var/www/vhosts/theacrylicstore.co.uk/htdocs/generated/code/Magento/LayeredNavigation/Block/Navigation/FilterRenderer/Interceptor.php(23): Magento\LayeredNavigation\Block\Navigation\FilterRenderer\Interceptor->___callPlugins() #11 /var/www/vhosts/theacrylicstore.co.uk/htdocs/app/design/frontend/wbs-theme/wbs/Magento_LayeredNavigation/templates/layer/view.phtml(41): Magento\LayeredNavigation\Block\Navigation\FilterRenderer\Interceptor->render() #12 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/var/www/vhosts...') #13 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php->render() #14 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView() #15 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Element/AbstractBlock.php(1111): Magento\Framework\View\Element\Template->_toHtml() #16 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Element/AbstractBlock.php(1115): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() #17 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Element/AbstractBlock.php(675): Magento\Framework\View\Element\AbstractBlock->_loadCache() #18 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Layout.php(566): Magento\Framework\View\Element\AbstractBlock->toHtml() #19 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Layout->_renderBlock() #20 /var/www/vhosts/theacrylicstore.co.uk/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement() #21 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() #22 /var/www/vhosts/theacrylicstore.co.uk/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement() #23 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Layout.php(594): Magento\Framework\View\Layout\Interceptor->renderElement() #24 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Layout.php(544): Magento\Framework\View\Layout->_renderContainer() #25 /var/www/vhosts/theacrylicstore.co.uk/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement() #26 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() #27 /var/www/vhosts/theacrylicstore.co.uk/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement() #28 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Layout.php(594): Magento\Framework\View\Layout\Interceptor->renderElement() #29 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Layout.php(544): Magento\Framework\View\Layout->_renderContainer() #30 /var/www/vhosts/theacrylicstore.co.uk/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement() #31 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() #32 /var/www/vhosts/theacrylicstore.co.uk/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement() #33 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Layout.php(594): Magento\Framework\View\Layout\Interceptor->renderElement() #34 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Layout.php(544): Magento\Framework\View\Layout->_renderContainer() #35 /var/www/vhosts/theacrylicstore.co.uk/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement() #36 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() #37 /var/www/vhosts/theacrylicstore.co.uk/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement() #38 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Layout.php(594): Magento\Framework\View\Layout\Interceptor->renderElement() #39 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Layout.php(544): Magento\Framework\View\Layout->_renderContainer() #40 /var/www/vhosts/theacrylicstore.co.uk/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement() #41 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() #42 /var/www/vhosts/theacrylicstore.co.uk/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement() #43 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Layout.php(594): Magento\Framework\View\Layout\Interceptor->renderElement() #44 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Layout.php(544): Magento\Framework\View\Layout->_renderContainer() #45 /var/www/vhosts/theacrylicstore.co.uk/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement() #46 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() #47 /var/www/vhosts/theacrylicstore.co.uk/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement() #48 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Layout.php(594): Magento\Framework\View\Layout\Interceptor->renderElement() #49 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Layout.php(544): Magento\Framework\View\Layout->_renderContainer() #50 /var/www/vhosts/theacrylicstore.co.uk/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement() #51 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() #52 /var/www/vhosts/theacrylicstore.co.uk/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement() #53 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Layout.php(963): Magento\Framework\View\Layout\Interceptor->renderElement() #54 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput() #55 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent() #56 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() #57 /var/www/vhosts/theacrylicstore.co.uk/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(347): Magento\Framework\View\Layout\Interceptor->___callPlugins() #58 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Result/Page.php(258): Magento\Framework\View\Layout\Interceptor->getOutput() #59 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render() #60 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult() #61 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent() #62 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() #63 /var/www/vhosts/theacrylicstore.co.uk/htdocs/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(95): Magento\Framework\View\Result\Page\Interceptor->___callPlugins() #64 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult() #65 /var/www/vhosts/theacrylicstore.co.uk/htdocs/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch() #66 /var/www/vhosts/theacrylicstore.co.uk/htdocs/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http\Interceptor->launch() #67 /var/www/vhosts/theacrylicstore.co.uk/htdocs/pub/index.php(40): Magento\Framework\App\Bootstrap->run() #68 {main}

**Comment by grassst** [comment] 2021-01-03 16:17
Hi,

I also have the same problem when in update my shop from 2.3.5-p2 to 2.4.1 and I try to do a search.
The catetory pages work fine.

[2021-01-03` 16:11:43] main.CRITICAL: Error: Call to a member function shouldDisplayProductCountOnLayer() on null in /var/www/html/vendor/magento/module-layered-navigation/view/frontend/templates/layer/filter.phtml:21
Stack trace:
#0 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include()
#1 /var/www/html/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\LayeredNavigation\Block\Navigation\FilterRenderer\Interceptor), '/var/www/html/v...', Array)
#2 /var/www/html/vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView('/var/www/html/v...')
#3 /var/www/html/vendor/magento/module-layered-navigation/Block/Navigation/FilterRenderer.php(29): Magento\Framework\View\Element\Template->_toHtml()
#4 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\LayeredNavigation\Block\Navigation\FilterRenderer->render(Object(Magento\CatalogSearch\Model\Layer\Filter\Category))
#5 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\LayeredNavigation\Block\Navigation\FilterRenderer\Interceptor->___callParent('render', Array)
#6 /var/www/html/vendor/magento/module-swatches/Model/Plugin/FilterRenderer.php(63): Magento\LayeredNavigation\Block\Navigation\FilterRenderer\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\CatalogSearch\Model\Layer\Filter\Category))
#7 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Swatches\Model\Plugin\FilterRenderer->aroundRender(Object(Magento\LayeredNavigation\Block\Navigation\FilterRenderer\Interceptor), Object(Closure), Object(Magento\CatalogSearch\Model\Layer\Filter\Category))
#8 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\LayeredNavigation\Block\Navigation\FilterRenderer\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\CatalogSearch\Model\Layer\Filter\Category))
#9 /var/www/html/generated/code/Magento/LayeredNavigation/Block/Navigation/FilterRenderer/Interceptor.php(23): Magento\LayeredNavigation\Block\Navigation\FilterRenderer\Interceptor->___callPlugins('render', Array, NULL)
#10 /var/www/html/vendor/magento/theme-frontend-luma/Magento_LayeredNavigation/templates/layer/view.phtml(63): Magento\LayeredNavigation\Block\Navigation\FilterRenderer\Interceptor->render(Object(Magento\CatalogSearch\Model\Layer\Filter\Category))
#11 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/var/www/html/v...')
#12 /var/www/html/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\LayeredNavigation\Block\Navigation), '/var/www/html/v...', Array)
#13 /var/www/html/vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView('/var/www/html/v...')
#14 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(1111): Magento\Framework\View\Element\Template->_toHtml()
#15 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(1115): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#16 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(675): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#17 /var/www/html/vendor/magento/framework/View/Layout.php(566): Magento\Framework\View\Element\AbstractBlock->toHtml()
#18 /var/www/html/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Layout->_renderBlock('catalogsearch.l...')
#19 /var/www/html/vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout->renderNonCachedElement('catalogsearch.l...')
#20 /var/www/html/vendor/magento/framework/View/Layout.php(594): Magento\Framework\View\Layout->renderElement('catalogsearch.l...', false)
#21 /var/www/html/vendor/magento/framework/View/Layout.php(544): Magento\Framework\View\Layout->_renderContainer('sidebar.main', false)
#22 /var/www/html/vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout->renderNonCachedElement('sidebar.main')
#23 /var/www/html/vendor/magento/framework/View/Layout.php(594): Magento\Framework\View\Layout->renderElement('sidebar.main', false)
#24 /var/www/html/vendor/magento/framework/View/Layout.php(544): Magento\Framework\View\Layout->_renderContainer('div.sidebar.mai...', false)
#25 /var/www/html/vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout->renderNonCachedElement('div.sidebar.mai...')
#26 /var/www/html/vendor/magento/framework/View/Layout.php(594): Magento\Framework\View\Layout->renderElement('div.sidebar.mai...', false)
#27 /var/www/html/vendor/magento/framework/View/Layout.php(544): Magento\Framework\View\Layout->_renderContainer('columns', false)
#28 /var/www/html/vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#29 /var/www/html/vendor/magento/framework/View/Layout.php(594): Magento\Framework\View\Layout->renderElement('columns', false)
#30 /var/www/html/vendor/magento/framework/View/Layout.php(544): Magento\Framework\View\Layout->_renderContainer('main.content', false)
#31 /var/www/html/vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#32 /var/www/html/vendor/magento/framework/View/Layout.php(594): Magento\Framework\View\Layout->renderElement('main.content', false)
#33 /var/www/html/vendor/magento/framework/View/Layout.php(544): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#34 /var/www/html/vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#35 /var/www/html/vendor/magento/framework/View/Layout.php(594): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#36 /var/www/html/vendor/magento/framework/View/Layout.php(544): Magento\Framework\View\Layout->_renderContainer('root', false)
#37 /var/www/html/vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout->renderNonCachedElement('root')
#38 /var/www/html/vendor/magento/framework/View/Layout.php(963): Magento\Framework\View\Layout->renderElement('root')
#39 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#40 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', Array)
#41 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#42 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#43 /var/www/html/vendor/magento/framework/View/Result/Page.php(258): Magento\Framework\View\Layout\Interceptor->getOutput()
#44 /var/www/html/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#45 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#46 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#47 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#48 /var/www/html/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(23): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#49 /var/www/html/vendor/magento/framework/App/View.php(221): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#50 /var/www/html/vendor/magento/module-catalog-search/Controller/Result/Index.php(138): Magento\Framework\App\View->renderLayout()
#51 /var/www/html/vendor/magento/module-catalog-search/Controller/Result/Index.php(108): Magento\CatalogSearch\Controller\Result\Index->getCacheableResult(Object(Magento\CatalogSearch\Helper\Data), Object(Magento\Search\Model\Query), NULL)
#52 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\CatalogSearch\Controller\Result\Index->execute()
#53 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callParent('execute', Array)
#54 /var/www/html/vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php(51): Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}()
#55 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute(Object(Magento\CatalogSearch\Controller\Result\Index\Interceptor), Object(Closure))
#56 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}()
#57 /var/www/html/generated/code/Magento/CatalogSearch/Controller/Result/Index/Interceptor.php(23): Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callPlugins('execute', Array, Array)
#58 /var/www/html/vendor/magento/framework/App/Action/Action.php(111): Magento\CatalogSearch\Controller\Result\Index\Interceptor->execute()
#59 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#60 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callParent('dispatch', Array)
#61 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#62 /var/www/html/generated/code/Magento/CatalogSearch/Controller/Result/Index/Interceptor.php(32): Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#63 /var/www/html/vendor/magento/framework/App/FrontController.php(186): Magento\CatalogSearch\Controller\Result\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#64 /var/www/html/vendor/magento/framework/App/FrontController.php(118): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\CatalogSearch\Controller\Result\Index\Interceptor))
#65 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#66 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#67 /var/www/html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#68 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#69 /var/www/html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(75): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#70 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#71 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#72 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#73 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#74 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#75 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent('launch', Array)
#76 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#77 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http\Interceptor->___callPlugins('launch', Array, Array)
#78 /var/www/html/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http\Interceptor->launch()
#79 /var/www/html/pub/index.php(40): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#80 {main} [] []

**Comment by engcom-Delta** [comment] 2021-01-18 20:00
@mohanwbsofttech @grassst Are you upgraded according [docs](https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html)? Do you have information about magento configuration that was missed in original issue description? 
According current description issue is not reproducible

**Comment by grassst** [comment] 2021-01-18 20:46
@VasylShvorak yes i am doing the update like the docs in your link. 
would be great to get help. 
thx.

**Comment by hareshpatel** [comment] 2021-02-04 06:23
how can resolve same issue can you plz send code

**Comment by iux** [comment] 2021-02-04 15:56
Hello, i have the same problem. At the moment to fix it i did:
copy: vendor/magento/module-layered-navigation/view/frontend/templates/layer/filter.phtml to app/design/frontend/Vendor/ThemeName/Magento_LayeredNavigation/templates/layer/filter.phtml
and removed from line 21 to 29.

**Comment by grassst** [comment] 2021-02-06 09:23
Hello,

@iux thank you! 
That worked also for me... :-)

**Comment by engcom-Delta** [comment] 2021-02-26 08:40
@grassst Looks like issue was caused by your custom theme/extension.
Is this issue solved for you and could be closed?

**Comment by grassst** [comment] 2021-02-26 09:50
Hi,
yes the issue is now solved and it looks like it was a issue in my theme.
So for me it is ok to close this issue.

Thank you.

**Comment by engcom-November** [comment] 2021-06-14 12:37
Hi, 
Closing this issue as the solution - Changing custom theme is working fine (Magento 2.4.2) and Category Products are displayed in Category Listing page as expected.
Thank you.

**Closed as completed** 2021-06-14 12:42 UTC
Labels: Issue: ready for confirmation
