### ISSUE TITLE
Checkbox and Radio renderer, strict check

### ISSUE THREAD

**Issue by michsk** [magento/magento2#2851] opened 2015-12-31 12:03 UTC
Is there any reason we have strict checks for single values and not strict for array values?

```

module-backend/Block/Widget/Grid/Column/Renderer/Radio.php::render()
line 78
if (is_array($values)) {
    $checked = in_array($value, $values) ? ' checked="checked"' : '';
} else {
    $checked = $value === $this->getColumn()->getValue() ? ' checked="checked"' : '';
}

```

The same is used for the Checkbox renderer. Maybe just keep it strinct and use `in_array($value, $values, true)` to be consistent?

**Comment by katmoon** [comment] 2016-01-08 13:21
Closing as a dupe of #2850

**Closed as completed by katmoon** 2016-01-08 13:21 UTC
