### ISSUE TITLE
Magento 2.2.4 Configurable product page swatch selection not passing 'selected_product_option' to Add to Cart

### ISSUE THREAD

**Issue by nbennett25** [magento/magento2#24073] opened 2019-08-08 16:10 UTC
Using Magneto 2.2.4, after creating a configurable product and color attribute specified child products, using the 'Visual Swatch' attribute display, no 'selected_product_option' is passed in the Add to Cart action on the product page, and a 'Requested product not found' error is thrown.

(After updating from 'Visual Swatch' to 'Dropdown' in the color product attribute, the Add to Cart works as expected).

### Preconditions (*)

1. Magento 2.2.4
2. PHP 7.0.32

### Steps to reproduce (*)

1. In the admin, create configurable product
2. Create 2 child products using 'color' attribute (Catalog Input Type for Store Owner = Visual Swatch)
3. Save product
4. View product on the front end
5. Select color swatch
6. Click Add to Cart

### Expected result (*)

1. In the Add to Cart request, 'selected_product_option' value is passed
2. Selected color product added to cart

### Actual result (*)

1. In the Add to Cart request, 'selected_product_option' value is empty
2. Error thown 'Requested product does not exist'

**Comment by engcom-Bravo** [comment] 2019-08-09 10:28
Hello @nbennett25. We've been not able to reproduce Your issue on a clear, vanilla magento instance of version 2.3-develop. Please try to reproduce the issue on 2.3-develop version Yourself and let us know the results. Thank You.

**Comment by nbennett25** [comment] 2019-08-09 13:27
@engcom-Bravo - I didn't test it on `2.3-develop` - It's currently broken on our 2.2.4 site - is 2.2.x no longer supported?

**Comment by engcom-Bravo** [comment] 2019-08-09 13:37
Yes, @nbennett25, `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._  See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details. So if you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines). As for this one we are supposed to close it. Thank You for applying.

**Closed as completed by engcom-Bravo** 2019-08-09 13:37 UTC
Labels: Progress: needs update, Issue: Format is valid
