### ISSUE TITLE
Checkout does not load in Safari (private mode)

### ISSUE THREAD

**Issue by mitch6** [magento/magento2#7942] opened 2016-12-23 02:25 UTC
When checking out in private mode in Safari, the checkout hangs at the spinning icon. There is also a javascript error throughout the site:

> QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.

### Preconditions
1. Using Magento 2.1.3
2. Production mode enabled
3. The following javascript options are set in the store configuration: Enable JavaScript Bundling, Merge JavaScript Files, Minify JavaScript Files

### Steps to reproduce
1. Open a new private window in Safari on OS X or iOS
2. Add an item to the cart
3. Go to the checkout page

### Expected result
1. The checkout should finish loading to allow the user to complete the checkout process
2. There should be no javascript errors in the console window

### Actual result
1. The checkout remains locked with a spinning loading icon indefinitely
2. The following javascript error appears in the console:

> QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.
> setItemf779b996300f63b32ad53337ae48af8b.min.js:1821
> setf779b996300f63b32ad53337ae48af8b.min.js:1821
> storeModulesf779b996300f63b32ad53337ae48af8b.min.js:1833
> collectf779b996300f63b32ad53337ae48af8b.min.js:1840
> (anonymous function)f779b996300f63b32ad53337ae48af8b.min.js:1854
> execCbf779b996300f63b32ad53337ae48af8b.min.js:950
> checkf779b996300f63b32ad53337ae48af8b.min.js:479
> enablef779b996300f63b32ad53337ae48af8b.min.js:649
> enablef779b996300f63b32ad53337ae48af8b.min.js:881
> (anonymous function)f779b996300f63b32ad53337ae48af8b.min.js:636
> (anonymous function)f779b996300f63b32ad53337ae48af8b.min.js:64
> eachf779b996300f63b32ad53337ae48af8b.min.js:10
> enablef779b996300f63b32ad53337ae48af8b.min.js:622
> initf779b996300f63b32ad53337ae48af8b.min.js:436
> (anonymous function)f779b996300f63b32ad53337ae48af8b.min.js:829

The line that triggers this error is found (in the original, unmerged javascript file) at line 100 in vendor/magento/magento2-base/lib/web/mage/requirejs/static.js, however there appear to be other scripts in Magento that rely on local storage as well.

**Comment by vishveskrish** [comment] 2016-12-23 05:57
Hello @mitch6 ,

We are facing the same issue in  2.1.2 version.
let me know if you found solution.

**Comment by artemhp** [comment] 2016-12-23 11:47
Localstorage is not working in Safari - Private mode.
It is better to wrap logic that depend on Storage in condition
`if( typeof Storage != 'undefined' ) { ... }`
Functionality will be limited but it can prevent from crashing. 
Maybe, it will be good to show some message that "Checkout will not work correctly in private mode"

**Comment by vishveskrish** [comment] 2016-12-27 13:34
@artemhp : Showing message is not proper way ! Is there any other fix/patch we can apply to resolve this ?

**Comment by veloraven** [comment] 2016-12-29 13:55
@mitch6 thank you for your report.
Please specify version of Safari you are using.

**Comment by vzabaznov** [comment] 2016-12-29 14:21
Hi @mitch6 i cannot reproduce this now on Safari Version 10.0.1 (11602.2.14.0.7) on OS X, can you please specify your safari version

**Comment by vishveskrish** [comment] 2016-12-30 07:02
@vzabaznov @veloraven  : I am facing the same issue ! its because local-storage not allowing in safari private mode. My version : Version 10.0.1 (11602.2.14.0.7) in MAC.

**Comment by mitch6** [comment] 2017-01-17 04:19
@vzabaznov This is on Safari 10.0.2 and 9.0.3.

**Comment by vishveskrish** [comment] 2017-01-17 07:00
Hi @vzabaznov ,

We are waiting for the quick solution for this issue!

**Comment by xmav** [comment] 2017-01-25 12:17
@mitch6 Thanks for reporting this issue. 
We've created internal ticket MAGETWO-63635 to address this issue.

**Comment by dtfdigital** [comment] 2017-02-03 14:11
Whether this is of any assistance, but we came across this on a client's project this morning. Turning off JS bundling resolved the issue and allowed users on iOS in a private window to complete the checkout.

**Comment by CyrilDeclerck** [comment] 2017-05-29 09:30
Hello everyone,
Actually I had the same issue for my current project, after few days of investigation I discovered that the problem comes from the file: `lib/web/mage/requirejs/static.js`. This JS file is used for embed all the tools helping to the files concatenation, it uses the local storage for know the files which have to be used for each page.
I tried to patch it like @magento-team did on the file `/vendor/magento/module-ui/view/base/web/js/lib/core/storage/local.js`. If I understand well, it’s looking if the local storage is handled by the browser, if this one return an error, the information will be stocked in another way (local storage variable).
But my problem is when I override the `lib/web/mage/requirejs/static.js` file for apply the patch, the file is excluded of the bundle and is charged in last (the list of charged file after the bundle is available in the `/vendor/magento/theme-frontend-blank/etc/view.xml` file).

Do you have any solution or advice about it ?

**Comment by veloraven** [comment] 2017-06-20 06:29
This issue was fixed in develop branch.
Internal ticket for ver. 2.1 - MAGETWO-69672

**Comment by magento-engcom-team** [comment] 2017-09-20 22:41
@mitch6, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:41 UTC
Labels: Issue: Ready for Work, bug report, Component: Checkout, Issue: Format is valid

**Comment by manojmjtech** [comment] 2017-10-03 04:56
After applying the changes its working fine on first time load of checkout page on iphone safari private mode but when you refresh the checkout page again then it keeps on loading and page doesn't load.
Moreover if you are on checkout page login to your account and page refreshes and again the same loading error and page doesn't load.

Please let me know any solution for it.
