### ISSUE TITLE
Bundle Product From Upsell/Crossell section redirect to 404 Page

### ISSUE THREAD

**Issue by Manjula-kalyan** [magento/magento2#35390] opened 2022-04-28 06:55 UTC
### Preconditions (*)

1.Add bundle product to simple products' UPSELL/CROSSELL section

### Steps to reproduce (*)

1. Go to simple products' PDP page
2.Add bundle product to cart from the Upsell section, It will redirect to cart page

### Expected result (*)

1. [Screenshots, logs or description]
2.It should redirect to bundle products PDP page

### Actual result (*)

1. [Screenshots, logs or description]
2.It's redirecting to 404 page

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-04-28 10:39
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue.
Added bundle product to Simple Product in Up-Sell Products section
Front -end Open Simple Product product details page
Click on Up-sell product - User navigated to bundle PDP page and able to add to cart. - No issue
![image](https://user-images.githubusercontent.com/60198231/165734700-0a34c976-49f1-4c23-b7da-1ca3dae3565e.png)
![image](https://user-images.githubusercontent.com/60198231/165734726-3f353ec9-8d51-4d12-b76f-fe7b2f589690.png)
@Manjula-kalyan kindly recheck the issue again on Magento 2.4-develop branch as it is the upcoming 2.4.x release and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-05-16 05:23
Hi @Manjula-kalyan ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are sill facing issues.
Thank you.

**Closed as completed by engcom-November** 2022-05-16 05:23 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
