### ISSUE TITLE
Sorting products in category by name makes status and visibility vanish at admin

### ISSUE THREAD

**Issue by pemann** [magento/magento2#32519] opened 2021-03-17 10:23 UTC
### Preconditions (*)
1. Magento 2.4.2

### Steps to reproduce (*)

1. Some categories & products created
2. Open admin -> Catalog -> Categories
3. Select a category with products
4. Open "Products in category"
5. Sort products by clicking column "Name"

### Expected result (*)

1. Products are sorted and every line has all the data

### Actual result (*)

1. Products are sorted but **"Visibility" and "Status" are empty for every product**
2. [Screenshot](https://ibb.co/vBGnQqk)
3. Note: This happens only with Name - column. All the other columns work fine when sorting.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by pemann** [comment] 2021-03-17 10:25
Reproduced with 2.4-develop instance with default sample data.

**Comment by magento-engcom-team** [comment] 2021-03-17 11:30
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41399` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by temptask** [comment] 2021-03-27 12:07
This issue seems to exist because SQL query with UNION ALL statements for sorted by Name products returns Visibility and Status values as float (e.g. 1.0 instead of 1) and when rendered in Magento\Backend\Block\Widget\Grid\Column\Renderer\Options.php it couldn't find corresponding option because they are passed as integers (e.g. 1 - "Enabled", 2 - "Disabled").

It doesn't happening when sorted by other columns because in this case Name attribute included in sql query and it looks like that sql results are not converted to float in this case.

For example, in MariaDB 10.3.25, executing query SELECT "a" UNION ALL SELECT 1 UNION ALL SELECT 2.5 results in:
'a'
'1'
'2.5'

But when text field is excluded from query and executed like SELECT 1 UNION ALL SELECT 2.5 results will be:
1.0
2.5

**Comment by SilinMykola** [comment] 2021-05-06 12:18
@magento I am working on this

**Comment by engcom-Bravo** [comment] 2024-06-07 07:25
Hi @pemann,

Thanks for your reporting and collaboration.

Similar issue has been confirmed here https://github.com/magento/magento2/issues/38233

Hence we are closing this as a duplicate.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-07 07:25 UTC
Labels: duplicate, Issue: Confirmed, Component: Admin, Reproduced on 2.4.x, Priority: P3, Progress: done
