### ISSUE TITLE
Advance reporting not working 

### ISSUE THREAD

**Issue by shubham-cedcoss** [magento/magento2#34048] opened 2021-09-10 12:08 UTC
### Preconditions (*)

1. Magento open source 2.4.0 and 2.4.2 without sample data is installed.
2.

### Steps to reproduce (*)

1. Configure Advanced reporting (https://docs.magento.com/user-guide/reports/advanced-reporting.html)
2.
![Screenshot_2021-09-10 Configuration Settings Stores Magento Admin](https://user-images.githubusercontent.com/54471172/132859350-f0762528-25cc-4b63-abf8-cdd4e8b021b9.png)
![Screenshot_2021-09-10 Integrations Extensions System Magento Admin](https://user-images.githubusercontent.com/54471172/132859385-99cb4011-53db-4abf-b4f9-0008a8348347.png)

### Expected result (*)

1. advance reporting should work without any issue
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.
![Screenshot_2021-09-10 Advanced Report Magento BI](https://user-images.githubusercontent.com/54471172/132851043-c7cfe6aa-37f7-42f4-991e-c54e75ec6dbb.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment] 2021-09-10 12:45
Hi @shubham-cedcoss,

It looks like you have not enabled Advanced Reporting from Configurations. Steps are given on the same link which you mentioned(https://docs.magento.com/user-guide/reports/advanced-reporting.html)

Also check pre-requisites on below given link:
https://devdocs.magento.com/guides/v2.4/advanced-reporting/overview.html

You can also raise queries like this on various Magento Forums. This section is for reporting Magento Dev related issues. 

So if you have any development related issue or bug, please update your description with the relevant proper 'Steps to reproduce' with 'Expected & actual results'. Otherwise we'll have to close this issue.

Thanks

**Comment by shubham-cedcoss** [comment] 2021-09-10 13:20
Hi @engcom-Lima,

I had enabled Advanced Reporting from Configurations. As I updated screenshots

**Comment by engcom-Lima** [comment] 2021-09-13 13:15
Hi @shubham-cedcoss,

As I said earlier, this issue is not related to Magento Dev. There can be multiple reasons for getting this 404 error like it may be due to incorrect configurations at your end or maybe you need to reauthorise your integration properly. 

Please check on the below link for a possible solution:
https://community.magento.com/t5/Magento-2-x-Technical-Issues/Advanced-Reporting-doesn-t-work-and-there-is-an-error-404/td-p/126904

If it doesn't help, you can also raise questions on various Magento Forums.

Thanks

**Comment by engcom-Lima** [comment] 2021-09-27 05:53
Hi @shubham-cedcoss,

We have noticed that this issue has not been updated for some time. Since this issue is not related to Magento Dev, we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Lima** 2021-09-27 05:53 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
