### ISSUE TITLE
Customer e-mail theme fallback doesn't take effect

### ISSUE THREAD

**Issue by lfritsche** [magento/magento2#6885] opened 2016-10-05 11:26 UTC
### Preconditions
1. Magento 2.0.4
2. en_US & de_DE
3. E-Mail fallback works if I place templates under <theme>/Magento_Sales/email/...
4. E-Mail fallback doesn't apply if I create custom customer templates within <theme>/Magento_Customer/email/...
### Steps to reproduce
1. If I copy the system default email template (for example: password_reset.html) into my theme directory under <theme>/Magento_Customer/email/ and customize it, Magento continues to use the default theme instead of my customized one.
2. Same procedure works for sales emails, which I copied to <theme>/Magento_Sales/email/
3. Using the backend-method (marketing > email templates > create new // configuration > customer > password > set template for password reset) does take effect, but not the theme fallback method.
### Expected result
1. Magento should use the template provided under <own_theme>/Magento_Customer/email/...
### Actual result
1. template fallback does not take effect on customer mails

**Comment by sevos1984** [comment] 2016-10-07 15:01
Thanks for reporting. Internal ticket created MAGETWO-59489

**Comment by nitin700** [comment] 2017-06-10 11:25
working on it

**Comment by omiroshnichenko** [comment] 2017-07-17 07:17
Hi, @lfritsche. I just try to reproduce your issue and all works fine on 2.0.4. My steps:
1. Create template magento2ce/app/design/frontend/Magento/luma/Magento_Customer/email/password_reset.html.
2. Create customer with own(real) email address.
3. Go to My account > Account information.
4. Check checkbox "Change password" and fill out new password.
5. Check email.

:white_check_mark: Letter correspond of template that was created at step 1.

Do you use same steps to test reset password functionality?

**Comment by magento-engcom-team** [comment] 2017-09-20 22:36
@lfritsche, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:36 UTC
Labels: Issue: Ready for Work, bug report, Component: Customer, Area: Frontend, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
