### ISSUE TITLE
Missed required argument subscriptionManager in parent::__construct call.

### ISSUE THREAD

**Issue by KiranLankapalli** [magento/magento2#34744] opened 2021-12-01 07:39 UTC
Hi,
I am trying to add the Ajax Newsletter subscription for the default magento newsletter.

But when i installed any extension with ajax newsletter, i am getting this error:
`Missed required argument subscriptionManager in parent::__construct call.`
and redirecting to cms no-route index 404 Error Page not found.

For example: I have installed Magemonkeys_AjaxNewsletter and in di:compile getting the following error:
`Magemonkeys\AjaxNewsletter\Controller\Plugin\Subscriber\NewAction
		Missed required argument subscriptionManager in parent::__construct call. File: app/code/Magemonkeys/AjaxNewsletter/Controller/Plugin/Subscriber/NewAction.php`

Same compile error and 404 page when click on subscribe button after installing any module installed with ajax newsletter subscription.

Please help,

**Comment by ihor-sviziev** [comment] 2021-12-01 08:58
Hi @KiranLankapalli,
It looks like the extension Magemonkeys\AjaxNewsletter isn't compatible with the version of Magento that you're using.
Please get in touch with the extension support.

As this isn't a Magento issue, but the problem is coming from a custom extension, I'm closing this issue.

**Closed as completed by ihor-sviziev** 2021-12-01 08:58 UTC
Labels: Triage: Dev.Experience, Issue: ready for confirmation

**Comment by KiranLankapalli** [comment] 2021-12-01 09:08
Hi @ihor-sviziev,
I have tried installing below modules as well, but getting the same
https://github.com/magepal/magento2-ajax-newsletter-subscribe
https://github.com/php-cuong/magento2-ajax-newsletter-subscription

Also i have tried Mageplaza Html Sitemap module and while trying to access the url getting 404 error.

**Comment by ihor-sviziev** [comment] 2021-12-01 10:31
@KiranLankapalli, for some reason, the request is coming to `/cms/noroute/index`, which is the internal URL for the "404" page. It would help if you looked at why it's getting redirected to this page.
