### ISSUE TITLE
Error on design configuration save with imageUploader form element populated from gallery

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#21032] opened 2019-02-06 21:11 UTC
### Preconditions (*)

N/A

### Steps to reproduce (*)
1. Log in to Admin panel
2. Go to Content -> Design -> Configuration
3. Click "Edit" link in a grid
4. Expand "Header" fieldset
5. Click "Select from Gallery" button for " Logo Image" field
5. Select any image and click on "Add Selected" button
6. Click the "Save Configuration" button

### Expected result (*)

Success message

### Actual result (*)

`header_logo_src does not contain field 'file'` error

### Additional info

Example of `imageUploader` working correctly for images from gallery can be found while editing a category: " Category Image" field in "Content" fieldset

**Comment by magento-engcom-team** [comment] 2019-02-06 21:11
Hi @sivaschenko. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sivaschenko do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-02-07 07:37
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-02-07 08:04
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98135`, `MAGETWO-98136` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-04-29 14:05
Hi @sivaschenko. Thank you for your report. 
The issue has been fixed in magento/magento2#22132 by @yvechirko in 2.3-develop branch
Related commit(s):
 - [2022307ea1cb8b0310ced73026ac2a10e4910bdc](https://github.com/magento/magento2/commit/2022307ea1cb8b0310ced73026ac2a10e4910bdc)
 - [ad544fb0b52cccd32ea939e8475aabae27adc414](https://github.com/magento/magento2/commit/ad544fb0b52cccd32ea939e8475aabae27adc414)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-04-29 14:05 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Email
