### ISSUE TITLE
Sort by quantity is not working in Magento 2.4 Elastic Search

### ISSUE THREAD

**Issue by rahulanand77** [magento/magento2#31775] opened 2021-01-20 14:34 UTC
The magento 2.4.1 with elastic search is having issues with "Sort by quantity" on the PLP page. The sorting is not working by ASC and DESC after enabling the sorting. 

### Preconditions (*)
1) Magento CE 2.4.1 without sample data is installed.
2) Elastic search is installed 
3) Full-text search for catalog is set to "Elastic Search"

### Steps to reproduce (*)
1) Install magento 2.4.1 with Elastic search installed on the server
2) Log into admin, navigate to "Store-> Product attributes"
3) Find "quantity" attribute and set "Use in filter options" to "Yes"
4) Clear cache and browse the PLP page
5) Sort by quantity

### Expected result (*)
1) The products should get sorted by quantity ASC/DESC based on their stock size

### Actual result (*)
1) Magento sorting is not working based on the quantity
2) The results are remaining the same in the case of ASC and DESC sorting by quantity. The products sorting list will remain the same. 
3) The MySQL query is generating properly with quantity order by param but results are not getting sorted based on available quantity. 

![Qty-Asc](https://user-images.githubusercontent.com/363711/105189037-8fa3e800-5b5a-11eb-850a-87077d667e24.png)
![Qty-Desc](https://user-images.githubusercontent.com/363711/105189047-916dab80-5b5a-11eb-9df6-8aed3fad231b.png)

### Additional info from Engcom
Two products with different quantity
![dif_qty](https://user-images.githubusercontent.com/51680745/105198790-b6582380-5b46-11eb-96a5-c224453887ae.png)
 Sorting by _Quantity_ on the Storefront doesn't change the position of the products
![Peek 2021-01-20 17-38](https://user-images.githubusercontent.com/51680745/105198905-d687e280-5b46-11eb-83a4-52a7fa6978d9.gif)

**Comment by engcom-Bravo** [comment] 2021-01-20 15:45
Hello @rahulanand77 

Thank you for your report.

We Confirm that the issue is reproducible. Additional info is added to the description.

**Comment by magento-engcom-team** [comment] 2021-01-20 15:45
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40524` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rahulanand77** [comment] 2021-01-25 10:50
Hi @magento-engcom-team,

Do we have any update on the patch to apply and fix this?

**Comment by rahulanand77** [comment] 2021-01-29 08:02
Hi @engcom-Bravo,

Do you have any update on the reported issue?

**Comment by engcom-Bravo** [comment] 2021-02-03 18:58
Hello @rahulanand77
We have started to fix the issue. The Pull Request will be linked to this ticket.

**Comment by rahulanand77** [comment] 2021-02-17 08:12
HI,

I have applied the changes you have mentioned, still not working. Please check the link to see more details:

https://eavs-groupe.fr/smart-building/visioconference/cameras-ptz.html?product_list_order=quantity_and_stock_status

![Untitled](https://user-images.githubusercontent.com/363711/108174849-01edf500-7126-11eb-982c-0e71679c2803.png)

**Comment by rahulanand77** [comment] 2021-02-17 08:13
The Model file and other di.xml and module.xml changes are applied in module "vendor/magento/module-inventory-elasticsearch" but still not working

**Comment by gabrieldagama** [comment] 2021-02-25 14:28
Hi @rahulanand77, after discussion with the product owner it was clear that this is not a bug. As it is right now, that is not something we currently support and there are several concerns with its implementation, as described on the PRs that were open against this issue.

I will be closing the issue since there are no plans for developing such a feature at the moment.

**Closed as completed by gabrieldagama** 2021-02-25 14:28 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P2, Severity: S2, Progress: done, Component: Attributes, Issue: ready for confirmation, Reported on 2.4.1

**Comment by magento-engcom-team** [comment] 2021-02-25 14:30
Hi @rahulanand77, @engcom-Charlie. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-40524` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by rahulanand77** [comment] 2021-02-27 12:57
Hi @magento-engcom-team ,

This is not correct. We have upgraded to 2.4.4 thinking the fix will be available. The fix is not available and sort by quantity is not working. The same can be checked on https://eavs-groupe.fr/smart-building/visioconference/cameras-ptz.html?product_list_order=quantity_and_stock_status&product_list_dir=desc

**Comment by rahulanand77** [comment] 2021-08-31 05:06
Hi @magento-engcom-team ,

The Magento version 2.4.3 is available in the market now. does this sort by quantity issue fixed in this version?


Thanks

**Comment by rahulanand77** [comment] 2021-09-10 03:53
Hi @magento-engcom-team, 

Any update on the issue? we are still waiting for the update


Thanks

**Comment by nd1996** [comment] 2022-08-08 12:01
Any Updates on this issue?

Or anyone has any quick fix
