### ISSUE TITLE
Error: Call to a member function getDirectoryWrite() on null in /var/www/php/folder/vendor/magento/module-catalog-import-export/Model/Import/Uploader.php:423

### ISSUE THREAD

**Issue by pmonosolo** [magento/magento2#36002] opened 2022-08-23 19:33 UTC
### Preconditions and environment

- Magento version 2.4.5 CE
- PHP 8.1

We're running a custom Magento 2 nightly product import. Part of this is image import that loads in images via cron job.

We're getting an error in debug.log:
/vendor/magento/module-catalog-import-export/Model/Import/Uploader.php

Error:
[2022-08-23T18:30:07.510356+00:00] main.CRITICAL: Error: Call to a member function getDirectoryWrite() on null in /var/www/php/folder/vendor/magento/module-catalog-import-export/Model/Import/Uploader.php:423

Stack trace:
#0 /var/www/php/folder/vendor/magento/framework/File/Uploader.php(288): Magento\CatalogImportExport\Model\Import\Uploader->_moveFile('var/tmp/1072652...', '/var/www/php/fo...')
#1 /var/www/php/folder/generated/code/Vendor/ProductImport/Model/Import/Uploader/Interceptor.php(23): Magento\Framework\File\Uploader->save('/var/www/php/fo...', '1072652583_fb2a...')
#2 /var/www/php/folder/vendor/vendor/folder/ProductImport/Model/Import/Uploader.php(105): Vendor\ProductImport\Model\Import\Uploader\Interceptor->save('/var/www/php/fo...', '1072652583_fb2a...')
#3 /var/www/php/folder/vendor/vendor/folder/ProductImport/Model/Import/Products/ImageImport.php(481): Vendor\ProductImport\Model\Import\Uploader->move('http://content....', true)
#4 /var/www/php/folder/vendor/vendor/folder/ProductImport/Model/Import/Products/ImageImport.php(197): Vendor\ProductImport\Model\Import\Products\ImageImport->uploadMediaFiles('http://content....', true)
#5 /var/www/php/folder/vendor/vendor/folder/ProductImport/Cron/ImageImport.php(76): Vendor\ProductImport\Model\Import\Products\ImageImport->process()
#6 [internal function]: Vendor\ProductImport\Cron\ImageImport->execute(Object(Magento\Cron\Model\Schedule))

The section of the code responsible is:

> 
>/**
>     * Set destination file path prefix
>     *
>     * @param string $path
>     * @return bool
>     */
>    public function setDestDir($path)
>    {
>        $directoryRoot = $this->targetDirectory->getDirectoryWrite(DirectoryList::ROOT);
>        if (is_string($path) && $directoryRoot->isWritable($path)) {
>            $this->_destDir = $path;
>            return true;
>        }
>        return false;
>    }

I have tested DirectoryList::ROOT and it outputs "pub" which is what is supposed to be. But I'm not sure why it throws an error then.

The commit to the file that made big changes to this file is here:
https://github.com/magento/magento2/commit/b1e56f026ea86c7e19f4b1047b4402d86db7110f

### Steps to reproduce

I dont know how to reproduce it or test it on vanilla store.

I would assume you would need to create an import with image import being pushed via a tmp folder.

### Expected result

Image import works :)

### Actual result

Image import doesnt work.

### Triage and priority

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by pmonosolo** [comment] 2022-08-23 20:13
When I return getTargetDirectory() function the error goes away:

![image](https://user-images.githubusercontent.com/66754347/186255512-50519a02-cda9-42a1-a723-a3b933be878e.png)

**Comment by pmonosolo** [comment] 2022-08-23 20:53
Yep, as soon as this was fixed, I was able to upload images!

Can somebody please take a look at this fucntion and actually test image upload.

**Comment by engcom-Hotel** [comment] 2022-08-25 10:01
Hello @pmonosolo,

Thanks for the response!

We have tried to reproduce this issue while upgrading Magento from 2.4.3 to 2.4.5 but the issue is not able to reproduce for us. We have used the inbuilt import functionality of the Magento.

It seems the issue is with your proprietary plugin. We request please review and let us know more specific steps to reproduce the issue.

Thanks

**Comment by pmonosolo** [comment] 2022-08-25 16:44
> Hello @pmonosolo,
> 
> Thanks for the response!
> 
> We have tried to reproduce this issue while upgrading Magento from 2.4.3 to 2.4.5 but the issue is not able to reproduce for us. We have used the inbuilt import functionality of the Magento.
> 
> It seems the issue is with your proprietary plugin. We request please review and let us know more specific steps to reproduce the issue.
> 
> Thanks

I'll need some time to set this up on my side. I'll get back here in a week.

**Comment by engcom-Hotel** [comment] 2022-08-26 05:50
Sure @pmonosolo we will wait for your reply.

**Comment by engcom-Hotel** [comment] 2022-09-13 07:22
Dear @pmonosolo,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-09-13 07:22 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.5
