### ISSUE TITLE
Random issues in backend

### ISSUE THREAD

**Issue by hanaks** [magento/magento2#37632] opened 2023-06-18 10:27 UTC
### Preconditions and environment

Magento version 2.4.5

### Steps to reproduce

Either happens always on almost all pages in backend, or doesn't happen at all. Could be related to network delays affecting loading order of external scripts.

### Expected result

No errors.

### Actual result

Random JavaScript errors in backend.

### Additional information

It seems that there is some random issue with Magento_AdminAnalytics module.

I started to get various JavaScript errors like these from the sudden in backend, causing stuck loaders on grids or menu not working in backend:

Uncaught Error: Mismatched anonymous define() module: function(){return cr}
Uncaught TypeError: $(...).ready is not a function
Uncaught TypeError: Cannot set properties of undefined (setting 'mage')

The errors disappeared after setting "Stores > Configuration > ADVANCED > Admin > Admin Usage > Enable Admin Usage Tracking" to "No".

Could be related to some network delay loading external scripts. The errors started at the same time on a hosted server and on a local dev server while no changes were made on the hosted server.

I remember the same issues long time ago at times of Magento 2.2 or similar. This could be one of the random errors which killed Magento 2.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment] 2023-06-18 10:46
This is most likely a duplicate of:
- https://github.com/magento/magento2/issues/37618
- https://github.com/magento/magento2/issues/37627

For now, you can disable admin analytics, that seems to be what works for everyone.

**Comment by hanaks** [comment] 2023-06-18 12:36
> This is most likely a duplicate of:
> 
> * [Admin Usage Tracking causes JS error #37618](https://github.com/magento/magento2/issues/37618)
> * [Help Center Widget #37627](https://github.com/magento/magento2/issues/37627)
> 
> For now, you can disable admin analytics, that seems to be what works for everyone (but it looks like you've already figured this out yourself).

Now I recall that the issues at times of Magento 2.2 were also related to some sort of popup from "Admin Usage Tracking", so the current errors could be caused by the "help center widget" rather than network delays.

**Comment by hanaks** [comment] 2023-06-18 12:39
When I add a JavaScript break point to code which calls the $(...).ready function then everything works, maybe because it gives time for js files to load. So maybe it's caused by loading order of js files?

**Comment by drinkingsouls** [comment] 2023-06-18 23:32
Yes, this sounds like the issue 37618[](https://github.com/magento/magento2/issues/37618) 
Try disabling the Admin Tracking setting as mentioned in that thread and see if that temporarily resolves the JavaScript errors.

**Comment by hanaks** [comment] 2023-06-19 06:42
Disabling "Admin Usage Tracking" fixes the errors, see ticket.

**Comment by engcom-Bravo** [comment] 2023-06-19 06:47
@hostep @drinkingsouls Thanks for your contribution & collaboration over here.

HI @hanaks,

Thank you for reporting and collaboration.

Similar issue has been confirmed here https://github.com/magento/magento2/issues/37618 Kindly move onto this issue for latest updates / solutions on the same.We are closing this as duplicate.

Thank you.

**Closed as completed by engcom-Bravo** 2023-06-19 06:47 UTC
Labels: duplicate, Issue: ready for confirmation, Reported on 2.4.6
