### ISSUE TITLE
Product Page Meta Title & Description are Not Changing

### ISSUE THREAD

**Issue by thepratikpatel** [magento/magento2#23418] opened 2019-06-26 10:13 UTC
Product Page's Meta Title And Description is not changing from the Search Engine Optimization Section.

It is Showing by Default Meta Title "Create New Customer Account"

I haven't install any extension for that

Don't Know Why Such error occurs in **Magento ver. 2.2.4**

**Comment by thepratikpatel** [comment] 2019-06-26 10:14
Ok Trying Second Time

**Comment by engcom-Charlie** [comment] 2019-06-26 10:22
Duplicate of #23419

**Closed as completed by engcom-Charlie** 2019-06-26 10:22 UTC
Labels: Issue: Format is not valid
