### ISSUE TITLE
Downloadable Product: Dropbox Link Failed to Download 

### ISSUE THREAD

**Issue by nickpiro** [magento/magento2#21985] opened 2019-03-28 06:08 UTC
When creating a downloadable product with a URL link from dropbox, the user receives 'Download Failed' error message when trying to download off dropbox page. When you go to dropbox link directly, not inline with the website URL structure, the download is successful.

### Preconditions (*)
1. Magento CE 2.2.5
2. Dropbox Link

### Steps to reproduce (*)
1. Create Downloadable Product
2. Add Downloadable Information Link
Here's the link we're using, it's a couple PSD files:
https://www.dropbox.com/sh/cl7udnrebkifw0q/AACMd34tw-SygMG-Eax6Bevfa?dl=0
3. Make file type URL and add dropbox URL.
<img width="1807" alt="Downloadable-Product" src="https://user-images.githubusercontent.com/36938969/55134113-415c6400-50fe-11e9-939c-81ad82a202d7.png">

4. Save product.
5. Add Product to Cart & Checkout
6. Goto My Account, Downloadable Products, and access product via link.
7. Dropbox opens. When click 'Direct Download' message pops up 'Download Failed'

### Expected result (*)
1. Download should not fail.

### Actual result (*)
1. Download Fails
<img width="496" alt="Failed-Download" src="https://user-images.githubusercontent.com/36938969/55134158-5fc25f80-50fe-11e9-8ba7-2e3d339d70d0.png">

**Comment by magento-engcom-team** [comment] 2019-03-28 06:08
Hi @nickpiro. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nickpiro do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by nickpiro** [comment] 2019-03-28 06:09
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment] 2019-03-28 06:09
Hi @nickpiro. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment] 2019-03-28 06:09
Hi @nickpiro, here is your [Magento instance](https://i-21985-2-2-5.instances.magento-community.engineering).
Admin access: [https://i-21985-2-2-5.instances.magento-community.engineering/admin](https://i-21985-2-2-5.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by nickpiro** [comment] 2019-03-28 06:15
I was able to reproduce the issue in Magento 2.2.5 vanilla.

**Comment by nickpiro** [comment] 2019-03-28 06:16
@magento-engcom-team give me 2.2.8 instance

**Comment by magento-engcom-team** [comment] 2019-03-28 06:16
Hi @nickpiro. Thank you for your request. I'm working on Magento 2.2.8 instance for you

**Comment by magento-engcom-team** [comment] 2019-03-28 06:16
Hi @nickpiro, here is your [Magento instance](https://i-21985-2-2-8.instances.magento-community.engineering).
Admin access: [https://i-21985-2-2-8.instances.magento-community.engineering/admin](https://i-21985-2-2-8.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by nickpiro** [comment] 2019-03-28 06:22
Was able to reproduce the issue in Magento 2.2.8 vanilla.

**Comment by nickpiro** [comment] 2019-03-28 06:23
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-28 06:23
Hi @nickpiro. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-28 06:23
Hi @nickpiro, here is your [Magento instance](https://i-21985-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21985-2-3-develop.instances.magento-community.engineering/admin](https://i-21985-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by nickpiro** [comment] 2019-03-28 06:29
I was able to reproduce the issue in Magento 2.3-develop.

**Comment by magento-engcom-team** [comment] 2019-03-28 07:40
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-03-28 13:01
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98935`, `MAGETWO-98936` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by nickpiro** [comment] 2019-04-02 03:02
Any word on when this would be worked on?

**Comment by kamzata** [comment] 2019-05-13 13:20
Similar issue happened earlier on Magento 1.x. Check this out: https://www.magentosolved.com/downloadable-products-error-occurred/

Anyway, I think you should use dropbox url like this (notice the parameter 1 at the url end instead of 0): https://www.dropbox.com/sh/cl7udnrebkifw0q/AACMd34tw-SygMG-Eax6Bevfa?dl=1

I've just tested some url formats and I think the problem lies in how header response code is handled:

- https://www.dropbox.com/sh/cl7udnrebkifw0q/AACMd34tw-SygMG-Eax6Bevfa?dl=1 - 301->302->200 - **Doesn't work!**
- http://ipv4.download.thinkbroadband.com/512MB.zip - 403 - **Doesn't work!**
- https://www.dropbox.com/sh/cl7udnrebkifw0q/AACMd34tw-SygMG-Eax6Bevfa - 200 - **Works!**
- http://www.ovh.net/files/10Gb.dat - 200 - **Works!**
- http://www.prefettura.it/FILES/AllegatiPag/1247/Calendario_test_italiano_anno_2019.pdf - 200 - **Works!**

I'm checking _\vendor\magento\module-downloadable\Controller\Download.php_. What do you think guys?

I don't know if this can help but I'm using NGINX web server behind a NGINX reverse proxy.

**Comment by nickpiro** [comment] 2019-05-22 04:50
@kamzata just tested some of your theories.

When I test the URL with ?d1=1 or ?dl=0 parameter, I don't even get redirected to Dropbox. 

When I remove the ?dl=0 or ?dl=1 I am redirected to Dropbox, but the download fails on the Dropbox side!

**Comment by kamzata** [comment] 2019-05-22 09:55
> @kamzata just tested some of your theories.
> 
> When I test the URL with ?d1=1 or ?dl=0 parameter, I don't even get redirected to Dropbox.
> 
> When I remove the ?dl=0 or ?dl=1 I am redirected to Dropbox, but the download fails on the Dropbox side!

Yeah, exactly. You're right. Dropbox URL with ?d1=1 or ?dl=0 parameter fail and don't even redirected to Dropbox meanwhile without parameter it redirects to Dropbox but the download fails on the Dropbox side. So, even this latter, doesn't work either.

**Comment by kamzata** [comment] 2019-07-16 14:46
Any news? This is a big issue for me. My stores have basically only downloadable products and because of this I cannot migrate to Magento 2 at the moment.

**Comment by dmanners** [comment] 2019-11-08 12:48
Hi @nickpiro could you try this with the host https://dl.dropboxusercontent.com instead of dropbox in your urls. I think the problem is that there is always an extra step between the drop box urls and the actual content but the user content urls would be the actual file.

**Comment by kamzata** [comment] 2019-11-20 12:52
Just tested on Magento 2.3.3 and it still doesn't work. This bug it's a nightmare for me since my products are basically all on dropbox.

This is the new error message: "Something went wrong while getting the requested content."

**Comment by kamzata** [comment] 2019-11-20 14:14
> https://dl.dropboxusercontent.com

It works using "https://dl.dropboxusercontent.com/....?dl=1" !!!

**Comment by quterorta** [comment] 2023-03-24 14:39
The issue is not reproduced in Magento 2.4.6

**Comment by engcom-Bravo** [comment] 2024-05-13 07:31
Hi @nickpiro,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.

We are able to download the links.

Hence we are closing this issue.
'
Thanks.

**Closed as completed by engcom-Bravo** 2024-05-13 07:31 UTC
Labels: Component: Catalog, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Catalog
