### ISSUE TITLE
Form element validation is not triggered when validation rules change

### ISSUE THREAD

**Issue by mam08ixo** [magento/magento2#21473] opened 2019-02-27 12:37 UTC
### Preconditions
1. Magento 2.1.x | 2.2.x | 2.3.x

### Steps to reproduce
1. Open any UI form component, e.g. _Product Edit Form_.
2. Change the validation rules for a form element on runtime.

### Expected result
1. The new validation rules are executed on the element's current value.

### Actual result
1. The form element is not validated according to the new validation rules.

### Additional Information
When `uiElement.setValidation()` is called in order to add or change validation rules, then the old rules are compared with the new rules – and if they changed, `uiElement.validate()` should be called. This seemed to be the intention of the developer at least. Due to a logic error, this does not happen:

https://github.com/magento/magento2/blob/f4c1d7526f05bdfb1327b0701cc345f94aadcaed/app/code/Magento/Ui/view/base/web/js/form/element/abstract.js#L299-L304

Notice the wrong `changed = equal` assignment which is used in the subsequent condition to detect if the element must be re-validated.

**Comment by magento-engcom-team** [comment] 2019-02-27 12:37
Hi @mam08ixo. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mam08ixo do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-02-27 12:39
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-02-28 06:20
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98478`, `MAGETWO-98479` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-03-27 14:08
Hi @kisroman. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-05-08 15:45
Hi @mam08ixo. Thank you for your report. 
The issue has been fixed in magento/magento2#21992 by @kisroman in 2.3-develop branch
Related commit(s):
 - [48e9760fb83d9c8136753814c9d913bf77cf940f](https://github.com/magento/magento2/commit/48e9760fb83d9c8136753814c9d913bf77cf940f)
 - [d3e37b826ec887353e328e699780c32bdf9ef2e1](https://github.com/magento/magento2/commit/d3e37b826ec887353e328e699780c32bdf9ef2e1)

The fix will be available with the upcoming 2.3.3 release.

**Closed as completed by magento-engcom-team** 2019-05-08 15:45 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Ui

**Comment by magento-engcom-team** [comment] 2019-05-17 15:20
Hi @mam08ixo. Thank you for your report. 
The issue has been fixed in magento/magento2#22801 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [f9396dbdc9aaac6bc0647c13b0800bcf3f9f8ba4](https://github.com/magento/magento2/commit/f9396dbdc9aaac6bc0647c13b0800bcf3f9f8ba4)
 - [20e38184c350271d4c359e0fc2ad9dd56bab9cc5](https://github.com/magento/magento2/commit/20e38184c350271d4c359e0fc2ad9dd56bab9cc5)

The fix will be available with the upcoming 2.2.10 release.
