### ISSUE TITLE
Admin with only specific website scope permissions gets error when trying to update order payment if product has tiers prices on multiple scopes: 'Undefined offset: 1 in vendor/magento/module-catalog/Model/Product/Attribute/Backend/GroupPrice/AbstractGroupPrice.php on line 293'

### ISSUE THREAD

**Issue by Djohn12** [magento/magento2#37907] opened 2023-08-22 09:28 UTC
### Preconditions and environment

- Magento enterprise 2.4.6-p2
- Multi websites configuration
- Admin User uses a role with only a specific website resource access (defined in the Role Resource tab in admin)
- Product in order has multiple tiers prices, configured on multiple website scopes
- Order has state/status 'Payment review'

tiers price configuration example:
![image](https://github.com/magento/magento2/assets/38497742/95860c3d-0e10-43bb-af41-64e83b104280)

### Steps to reproduce

1. Connect to admin using a role limited only to a specific website
2. Go to an order in a 'Payment Review' state/status of the same website
3. Click on the 'Accept Payment' or 'Deny Payment' button

### Expected result

Order and Payment are updated according to the previous admin action
Accept Payment ==> Order moves to processing status
Deny Payment ==> Order is cancelled

### Actual result

Order is not updated
2 error messages appear:
* 'Undefined offset: 1 in vendor/magento/module-catalog/Model/Product/Attribute/Backend/GroupPrice/AbstractGroupPrice.php on line 293'
* 'We can't update the payment right now'

![admin_update_payment_error](https://github.com/magento/magento2/assets/38497742/bf401688-f8cb-40ec-bb5f-ea27fff27fe2)

### Additional information

By looking at the code, I don't really get the condition on line 289 `if ($this->_isPriceFixed($price))`
This method resolves line 159 with a call to Magento\Catalog\Model\Product\Type\Price::isGroupPriceFixed which I don't really understand.

This isGroupPriceFixed method is not called or defined anywhere in the core code so it seems magic but I don't see Magento\Catalog\Model\Product\Type\Price extending anything that could explain how it works exactly.

I've found two old issues which seem to me a bit related to this but do not match exactly the bug I'm seeing:
* https://github.com/magento/magento2/issues/29903
* https://github.com/magento/magento2/issues/6378

Is a bug ?
If not, how that condition is supposed to work ?
Anything I'm missing here ?

The workaround we have for now is using a full resource access admin role to do those order/payment updates.

Thanks in advance !
Best Regards

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-08-23 11:48
Hi @Djohn12,

Thank you for reporting and collaboration.

Could you please elaborate the **Connect to admin using a role limited only to a specific website**.

We have created tier prices for multi websites.

<img width="1106" alt="Screenshot 2023-08-23 at 4 17 02 PM" src="https://github.com/magento/magento2/assets/51680745/ab22b439-999b-4e4d-875d-1216ef4de557">




<img width="1507" alt="Screenshot 2023-08-23 at 5 12 55 PM" src="https://github.com/magento/magento2/assets/51680745/3b37eb7e-5590-433c-812d-59fb9f81509e">



Could you please elaborate the steps regarding Click on the 'Accept Payment' or 'Deny Payment' button.


Please let us know if we are missing anything.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-09-04 06:12
Hi @Djohn12,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/37907#issuecomment-1689818005 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-09-08 06:07
Hi @Djohn12,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-09-08 06:07 UTC
Labels: Issue: needs update, Reported on 2.4.6-p2
