### ISSUE TITLE
Magento2.4.3 install sampledata Bug

### ISSUE THREAD

**Issue by shuaiZend** [magento/magento2#35178] opened 2022-03-10 17:14 UTC
````bash
root@vps:/data/wwwroot/demo.org# bin/magento sampledata:deploy
<warning>Do not run Composer as root/super user! See https://getcomposer.org/root for details</warning>
<warning>Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/</warning>
Info from https://repo.packagist.org: #StandWithUkraine
^C
Installation failed, reverting ./composer.json to its original content.
root@vps:/data/wwwroot/demo.org# bin/magento -V
Magento CLI 2.4.3-p1
root@vps:/data/wwwroot/demo.org# composer -V
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer version 1.10.19 2020-12-04 09:14:16
````

1. install Magento 2.4.3-p1 need composer ver 1.x
2. but use magento 2.4.3 run 'sampledata:deploy' need composer ver 2.x
so, we need two composer ver????
i think this is bug.

**Comment by hostep** [comment] 2022-03-11 10:03
This is a duplicate of https://github.com/magento/magento2/issues/33047, can you try the workaround mentioned in https://github.com/magento/magento2/issues/33047#issuecomment-844423628 to see if that solves your issue?

You can also wait until Magento 2.4.4 is [released](https://devdocs.magento.com/release/) and then try again ...

**Comment by shuaiZend** [comment] 2022-03-11 14:15
> This is a duplicate of #33047, can you try the workaround mentioned in [#33047 (comment)](https://github.com/magento/magento2/issues/33047#issuecomment-844423628) to see if that solves your issue?
> 
> You can also wait until Magento 2.4.4 is [released](https://devdocs.magento.com/release/) and then try again ...

not duplicate.
i only wanto to use Magento2.4.3, Not 2.4.4 :(
becus 2.4.4 need php8.
so, i only wait Magento 2.4.3-p2 :)

**Comment by hostep** [comment] 2022-03-12 19:41
I'm afraid it won't, but who knows, we will only be able to tell in a couple of weeks ... 🙂 
Have you tried the workaround? Maybe that can help you further in the meantime?

**Comment by engcom-Delta** [comment] 2022-04-06 08:23
Dear @shuaiZend ,

We have noticed that this issue has not been updated for a period of 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh  ticket or reopen this ticket if you need more assistance on this.

**Closed as completed by engcom-Delta** 2022-04-06 08:23 UTC
Labels: Issue: needs update

**Comment by shakil-codilar** [comment] 2023-01-07 12:15
@magento give me 2.4-develop instance

**Comment by shakil-codilar** [comment] 2023-01-07 12:16
@magento give me 2.4.3-develop instance
