### ISSUE TITLE
PayPal Express Checkout error "Failed address validation: %1" on Guest checkout

### ISSUE THREAD

**Issue by kamzata** [magento/magento2#39107] opened 2024-08-25 09:25 UTC
Still present for me in Magento 2.4.7-p1 no matter if:

- `Skip Order Review Step` option is set to `Yes` or `No`.
- `Enable Automatic Assignment to Customer Group` is set or not.

[This seems to solve the issue](https://magento.stackexchange.com/a/310254/13970).

```
        ...

        public function place($token, $shippingMethodCode = null)
        {
            if ($shippingMethodCode) {
                $this->updateShippingMethod($shippingMethodCode);
            }
    
            if ($this->getCheckoutMethod() == \Magento\Checkout\Model\Type\Onepage::METHOD_GUEST) {
                $this->prepareGuestQuote();
            }
    
            $this->ignoreAddressValidation();
            $this->_quote->collectTotals();
            

            // (BUG) SET CUSTOMER EMAIL IF EMAIL IS FOUND EMPTY
            if ($this->_quote->getCustomerEmail() === null && $this->_quote->getBillingAddress()->getEmail() !== null) {
            $this->_quote->setCustomerEmail($this->_quote->getBillingAddress()->getEmail());
            // (BUG) END

            $order = $this->quoteManagement->submit($this->_quote);
    
            if (!$order) {
                return;
            }
    
            // commence redirecting to finish payment, if paypal requires it
            if ($order->getPayment()->getAdditionalInformation(self::PAYMENT_INFO_TRANSPORT_REDIRECT)) {
                $this->_redirectUrl = $this->_config->getExpressCheckoutCompleteUrl($token);
            }
            ....
```

Correlated to:

#29473 
#25399 

_Originally posted by @kamzata in https://github.com/magento/magento2/issues/25399#issuecomment-2308482597_

**Comment by kamzata** [comment] 2024-08-29 09:49
> Hi @kamzata,
> 
> Thanks for your reporting and collaboration.
> 
> We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.
> 
>  Screen.Recording.2024-08-29.at.11.34.48.mov 
> We are able to place the order with Paypal Express checkout using checkout.
> 
> Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.
> 
> Thanks.

I don't know why but now it seems to work for me too. However, I'm not able to see the block for creating an account:

![image](https://github.com/user-attachments/assets/f583f5d2-4d3c-4eca-8b21-d47b131e66a9)

**Comment by engcom-Bravo** [comment] 2024-08-30 05:09
Hi @kamzata,

Thanks for your update.

As per this comment https://github.com/magento/magento2/issues/39107#issuecomment-2317190047 since the issue is no more reproducible and we are able to see the customer block as well.Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-08-30 05:09 UTC
Labels: Issue: needs update, Reported on 2.4.7-p1
