### ISSUE TITLE
MAGENTO MARKETPLACE CONNECT HTTP2/200 /401 ERROR

### ISSUE THREAD

**Issue by nehbellebcare9** [magento/magento2#19962] opened 2018-12-24 18:37 UTC
DEAR SIR,MA'AM,
WE ARE GETTING AN ERROR WHILE CONNECTING TO MAGENTO MARKET PLACE AS HTTP2/200 AND SOME TIMES AS HTTP2/410. PLS DO HELP US WITH THE SAME. WE ALSO TRIED REINSTALLING IT BYT SAME PROBLEM PERSISTS.

**Comment by magento-engcom-team** [comment] 2018-12-24 18:37
Hi @nehbellebcare9. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nehbellebcare9 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by nehbellebcare9** [comment] 2018-12-24 18:40
The current magento version is 2.2.4

**Comment by Nazar65** [comment] 2018-12-24 18:43
@nehbellebcare9 this already fixed in this issue ->https://github.com/magento/magento2/issues/19127

**Closed as completed by Nazar65** 2018-12-24 18:43 UTC
Labels: Issue: Format is not valid
