### ISSUE TITLE
Category Product index issue

### ISSUE THREAD

**Issue by vineetagarwal1981** [magento/magento2#23791] opened 2019-07-19 13:49 UTC
We have a multiple website in which there are multiple root categories and same product are assigned to multiple website and categories and we have also configured elastic search version 5+. While place the order we are getting 'Exception #0 (Magento\Framework\Exception\NoSuchEntityException): No such entity with id = 3' .
Issue found in the catalog_category_product_index_store[Storeid] table where wrong entries for category id and product id 

### Preconditions (*)
1. Magento Version 2.3.0
2. Multiple Website should be Created
3. Multiple root category should created and each root category associated with the each website.
4. All Categories should be anchor
4. Elastic search 5+ need to be configured. 

### Steps to reproduce (*)
1. Add the product to the cart
2. Place the order.

### Expected result (*)
1. Order success page should be visible

### Actual result (*)
1. Got the error "'Exception #0 (Magento\Framework\Exception\NoSuchEntityException): No such entity with id = 3' "
2.![Screenshot from 2019-07-18 13-10-15](https://user-images.githubusercontent.com/14345448/61539558-66803400-aa59-11e9-9aec-9372dc71bf85.png)

**Comment by vineetagarwal1981** [comment] 2019-07-19 18:06
Yes

**Comment by engcom-Charlie** [comment] 2019-07-23 09:43
Hi @vineetagarwal1981 ! I can't reproduce this issue on fresh 2.3-develop branch. So i close this issue.
Thank for contribution!

**Closed as completed by engcom-Charlie** 2019-07-23 09:43 UTC
Labels: Issue: Clear Description, Issue: Format is valid, Component: Elasticsearch
