### ISSUE TITLE
Unable to create configurable product

### ISSUE THREAD

**Issue by zyukov** [magento/magento2#26528] opened 2020-01-24 15:17 UTC
### Preconditions (*)
1. Magento CE 2.3.3.

### Steps to reproduce (*)
1. Login to admin.
2. Open Stores-Sources.
3. Create Own Source (for example "My-Source").
4. Open Catalog-Products.
5. Click Add New Product.
6. Fill in Required fields (Name, Sku, Price).
7. Click Create Configurations.
8. Select Attribute (For example: color).
9. Select attribute option (For example "white" for color attribute).
10. On Step 3. "Bulk Images, Price and Quantity for Quantity per source" select: "Apply unique quantity by attribute to each SKU".
11. Assign Source "My-Source" created on 3.
12. Fill in Qty.
13. Step 4. Click Generate Products.
14. Click Save.

### Expected result (*)
1. Product is saved.
2. Configurations of product are created.

### Actual result (*)
1. Infinite loading.
2. Console error:
`Uncaught TypeError: Cannot read property 'label' of undefined
    at isValidOption (attributes_values.js:109)
    at add (jquery.js:10079)
    at buildParams (jquery.js:10067)
    at Function.jQuery.param (jquery.js:10101)
    at Function.ajax (jquery.js:9618)
    at beforeSave (client.js:35)
    at UiClass.save (client.js:91)
    at UiClass.save (provider.js:62)
    at UiClass.submit (form.js:313)
    at UiClass.save (form.js:265)`

**Comment by ajijshekh123** [comment] 2020-01-27 04:34
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-01-27 04:35
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-27 04:35
Hi @ajijshekh123, here is your [Magento instance](https://i-26528-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26528-2-4-develop.instances.magento-community.engineering/admin_65fc](https://i-26528-2-4-develop.instances.magento-community.engineering/admin_65fc)
Login: `4818c466` Password: `4564f30abaed`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2020-01-27 04:41
Hello @zyukov,
I have verified this issue in Magento 2.3 Instance but I am not able to reproduce this issue as per your steps.
Can you please provide me a video?
A multisource example is related to the Magento 2.3 Enterprise related concept and i have reviewed it but not able to reproduce it.

Thanks.

**Comment by zyukov** [comment] 2020-01-27 07:02
@ajijshekh123 I have downloaded default 2.3.3 installation. MSI is out of the box. Please check video - https://youtu.be/ka4aaSAzptg

**Comment by ajijshekh123** [comment] 2020-01-27 07:15
@zyukov - Thanks for the video. Let me verify this issue again and update you.

**Comment by zyukov** [comment] 2020-01-27 07:34
@ajijshekh123 Tried to reproduce on 2.3.2 - no error, but after upgrade to 2.3.3 - was reproduced.

**Comment by ajijshekh123** [comment] 2020-01-27 09:30
Hello @zyukov,
I can't able to reproduce this issue in the Default Magento 2.4 Community because of Multisource inventory functionality is not available in the community edition.

Thanks.

**Comment by engcom-Bravo** [comment] 2020-01-28 10:38
Hello @zyukov 

Thank you for your report.

We have rechecked this on 2.4-develop with the inventory functionality 

This seems to be fixed on Magento 2.4-develop, no error message appears in the developer console, and the product is saved properly. 
There was a similar issue https://github.com/magento/inventory/issues/2440 but it is closed already.

So we have to close it.
If you are still facing this issue on the latest 2.4-develop branch, please create a new issue in Magento2 inventory repository https://github.com/magento/inventory/issues

Thank you for your collaboration

**Closed as completed by engcom-Bravo** 2020-01-28 10:38 UTC
Labels: Issue: Format is valid, Reported on 2.3.3
