### ISSUE TITLE
Intercepted methods returning self are generated with incompatible signature

### ISSUE THREAD

**Issue by sshymko** [magento/magento2#23084] opened 2019-05-31 19:27 UTC
### Preconditions (*)
- Magento 2.3.1
- Class with pluginized method returning `self`

### Steps to reproduce (*)
1. Extend any class with intercepted methods returning `self`, for example:
    <img width="545" alt="magento2_catalog_indexer_full" src="https://user-images.githubusercontent.com/1231423/58729675-e87ba700-839e-11e9-8486-5065562eb60f.png">
    ```php
    namespace Example\Module\Catalog\Model\Indexer\Category\Product\Action;
    
    class Full extends \Magento\Catalog\Model\Indexer\Category\Product\Action\Full
    {
    
    }
    ```
2. Generate interceptors by compiling DI:
    ```bash
    php bin/magento setup:di:compile
    ```
3. Locate generated interceptors for descendant classes:
    ```
    generated/code/Example/Module/Model/Indexer/Category/Product/Action/Full/Interceptor.php
    ```

### Expected result (*)
1. DI compilation completes successfully
2. Generated interceptor classes are compatible with classes they inherit/intercept

### Actual result (*)
1. Return type of the intercepted method is incompatible with the parent:
    <img width="984" alt="magento2_catalog_indexer_child_interceptor" src="https://user-images.githubusercontent.com/1231423/58729567-9b97d080-839e-11e9-9869-de23cee90f11.png">
2. PHP Fatal error upon any attempt to use the intercepted descendant class

**Comment by sshymko** [comment] 2019-05-31 19:30
yes

**Comment by Swahjak** [comment] 2019-05-31 21:50
Having the same issue extending `Magento\Catalog\Model\Indexer\Category\Product\Action\Full::execute`. Magento 2.3.1.

**Comment by Swahjak** [comment] 2019-05-31 21:52
Possible duplicate of #11905 and #22769

**Closed as completed** 2019-06-01 01:11 UTC
Labels: duplicate, Issue: Format is valid
