### ISSUE TITLE
GraphQL mutation uptdateCartItems return data is incorrect when removing multiple items

### ISSUE THREAD

**Issue by mmborado** [magento/magento2#29901] opened 2020-09-04 06:50 UTC
### Preconditions (*)
1. Magento version: 2.4.0

### Steps to reproduce (*)

1. Add a set of items to cart (minimum 2)
2. Using the graphQL mutation `updateCartItems` set multiple or all of the item quantities to 0

query
```
mutation {
  updateCartItems(
    input: {
      cart_id: {{cartID}}",
      cart_items: [
        {
          cart_item_id: 1
          quantity: 0
        },
        {
          cart_item_id: 2
          quantity: 0
        },
      ]
    }
  ) {
    cart {
      items {
        id
        product {
          name
        }
        quantity
      }
      prices {
        grand_total{
          value
          currency
        }
      }
    }
  }
}
```
### Expected result (*)
1. Expected cart data where all items that were set to a quantity of 0 to be removed

### Actual result (*)

1. The cart data that is returned will remove 1 item. The rest of the items will still be in the cart.
2. Even though All items were set to 0. The cart returned with all items minus 1.
3. The Items are still removed from cart, but an extra query to get the cart was required to get the correct cart data.
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment] 2021-11-17 11:53
Hi @mmborado 
Thanks for your contribution and collaboration!
I have tried to reproduce this issue and seems to be not reproducible. Kindly cross-check below steps I followed please!

1. Created a cart using GraphQL request.
2. Added 3 products with 2 quantity each as shown in the below screenshot.
<img width="1440" alt="Products added to Cart" src="https://user-images.githubusercontent.com/51679138/142193999-8676795d-b271-43df-852c-9fcb355bb6a4.png">
3. Updated the cart with zero quantity for 2 of the products among 3, and the screenshot is below
<img width="1440" alt="update to cart" src="https://user-images.githubusercontent.com/51679138/142194306-4dc3aa5e-5134-4894-8459-06a282ec53cb.png">
4. GraphQL queried that retrieves the cart products and list.
<img width="1440" alt="cart after updating" src="https://user-images.githubusercontent.com/51679138/142194431-c0915160-bdd0-4ba1-bffc-2507d66d66cc.png">

As defined in the [issue description](https://github.com/magento/magento2/issues/30220#issue-710370985), didn't notice any issue as such. Zeroed quantity is successfully ignored in the cart queried response.
Tested it in the 2.4-develop Magento instance, and I request you to kindly check if the issue is still existing. Since the issue was noticed many months back, it might have fixed with other PRs.

**Comment by engcom-Alfa** [comment] 2022-08-24 10:57
Today again I tried to reproduce in 2.4-develop instance having different types of products into the cart. Below is the procedure I followed.

1. Retrieved a customer token, using a GraphQL query.
2. Created a new empty cart using a query `mutation {
  createEmptyCart
}`
3. Added simple products to the cart-
Request is: `mutation {
  addSimpleProductsToCart(
    input: {
      cart_id: "{{CustomerCart}}"
      cart_items: [
        {
          data: {
            quantity: 4
            sku: "SimpleProd01"
          }
        },
        {
          data: {
            quantity: 4
            sku: "SimpleProd02"
          }
        }
      ]
    }
  ) {
    cart {
      items {
        id
        product {
          sku
          stock_status
        }
        quantity
      }
    }
  }
}`
Response is: `{
    "data": {
        "addSimpleProductsToCart": {
            "cart": {
                "items": [
                    {
                        "id": "7",
                        "product": {
                            "sku": "SimpleProd02",
                            "stock_status": "IN_STOCK"
                        },
                        "quantity": 4
                    },
                    {
                        "id": "8",
                        "product": {
                            "sku": "SimpleProd01",
                            "stock_status": "IN_STOCK"
                        },
                        "quantity": 4
                    }
                ]
            }
        }
    }
}`
4. Added configurable products to the cart-
Request is: `mutation {
  addConfigurableProductsToCart(
    input: {
      cart_id: "{{CustomerCart}}"
      cart_items: [
        {
          parent_sku: "WSH10"
          data: {
            quantity: 2
            sku: "WSH10-28-Black"
          }
        }
      ]
    }
  ) {
    cart {
      items {
        uid
        quantity
        product {
          name
          sku
        }
        ... on ConfigurableCartItem {
          configurable_options {
            option_label
          }
        }
      }
    }
  }
}`
Response is: `{
    "data": {
        "addConfigurableProductsToCart": {
            "cart": {
                "items": [
                    {
                        "uid": "Nw==",
                        "quantity": 8,
                        "product": {
                            "name": "SimpleProd02",
                            "sku": "SimpleProd02"
                        }
                    },
                    {
                        "uid": "OA==",
                        "quantity": 8,
                        "product": {
                            "name": "SimpleProd01",
                            "sku": "SimpleProd01"
                        }
                    },
                    {
                        "uid": "OQ==",
                        "quantity": 2,
                        "product": {
                            "name": "Teton Pullover Hoodie",
                            "sku": "MH02"
                        },
                        "configurable_options": [
                            {
                                "option_label": "Color"
                            },
                            {
                                "option_label": "Size"
                            }
                        ]
                    },
                    {
                        "uid": "MTM=",
                        "quantity": 2,
                        "product": {
                            "name": "Ana Running Short",
                            "sku": "WSH10"
                        },
                        "configurable_options": [
                            {
                                "option_label": "Color"
                            },
                            {
                                "option_label": "Size"
                            }
                        ]
                    }
                ]
            }
        }
    }
}`
5. Added bundle products to the cart-
Request: `mutation {
  addBundleProductsToCart(
    input: {
      cart_id: "{{CustomerCart}}"
      cart_items: [
      {
        data: {
          sku: "24-WG080"
          quantity: 1
        }
        bundle_options: [
          {
            id: 1
            quantity: 1
            value: [
              "2"
            ]
          },
          {
            id: 2
            quantity: 2
            value: [
              "4"
            ]
          },
          {
            id: 3
            quantity: 1
            value: [
              "7"
            ]
          },
          {
            id: 4
            quantity: 1
            value: [
              "8"
            ]
          }
        ]
      },
    ]
  }) {
    cart {
      items {
        uid
        quantity
        product {
          sku
        }
        ... on BundleCartItem {
          bundle_options {
            uid
            label
            type
            values {
              id
              label
              price
              quantity
            }
          }
        }
      }
    }
  }
}
`
Response: `{
    "data": {
        "addBundleProductsToCart": {
            "cart": {
                "items": [
                    {
                        "uid": "Nw==",
                        "quantity": 8,
                        "product": {
                            "sku": "SimpleProd02"
                        }
                    },
                    {
                        "uid": "OA==",
                        "quantity": 8,
                        "product": {
                            "sku": "SimpleProd01"
                        }
                    },
                    {
                        "uid": "OQ==",
                        "quantity": 2,
                        "product": {
                            "sku": "MH02"
                        }
                    },
                    {
                        "uid": "MTM=",
                        "quantity": 2,
                        "product": {
                            "sku": "WSH10"
                        }
                    },
                    {
                        "uid": "MTU=",
                        "quantity": 1,
                        "product": {
                            "sku": "24-WG080"
                        },
                        "bundle_options": [
                            {
                                "uid": "YnVuZGxlLzE=",
                                "label": "Sprite Stasis Ball",
                                "type": "radio",
                                "values": [
                                    {
                                        "id": 2,
                                        "label": "Sprite Stasis Ball 65 cm",
                                        "price": 27,
                                        "quantity": 1
                                    }
                                ]
                            },
                            {
                                "uid": "YnVuZGxlLzI=",
                                "label": "Sprite Foam Yoga Brick",
                                "type": "radio",
                                "values": [
                                    {
                                        "id": 4,
                                        "label": "Sprite Foam Yoga Brick",
                                        "price": 5,
                                        "quantity": 2
                                    }
                                ]
                            },
                            {
                                "uid": "YnVuZGxlLzM=",
                                "label": "Sprite Yoga Strap",
                                "type": "radio",
                                "values": [
                                    {
                                        "id": 7,
                                        "label": "Sprite Yoga Strap 10 foot",
                                        "price": 21,
                                        "quantity": 1
                                    }
                                ]
                            },
                            {
                                "uid": "YnVuZGxlLzQ=",
                                "label": "Sprite Foam Roller",
                                "type": "radio",
                                "values": [
                                    {
                                        "id": 8,
                                        "label": "Sprite Foam Roller",
                                        "price": 19,
                                        "quantity": 1
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        }
    }
}`
6. Query to get the cart items-
Request: `
  { 
    cart(cart_id: "{{CustomerCart}}") {
    items {
      id
      product {
        name
        sku
        stock_status,
        type_id
      }
      quantity
    }
  }
}`
Response: `{
    "data": {
        "cart": {
            "items": [
                {
                    "id": "7",
                    "product": {
                        "name": "SimpleProd02",
                        "sku": "SimpleProd02",
                        "stock_status": "IN_STOCK",
                        "type_id": "simple"
                    },
                    "quantity": 8
                },
                {
                    "id": "8",
                    "product": {
                        "name": "SimpleProd01",
                        "sku": "SimpleProd01",
                        "stock_status": "IN_STOCK",
                        "type_id": "simple"
                    },
                    "quantity": 8
                },
                {
                    "id": "9",
                    "product": {
                        "name": "Teton Pullover Hoodie",
                        "sku": "MH02",
                        "stock_status": "IN_STOCK",
                        "type_id": "configurable"
                    },
                    "quantity": 2
                },
                {
                    "id": "13",
                    "product": {
                        "name": "Ana Running Short",
                        "sku": "WSH10",
                        "stock_status": "IN_STOCK",
                        "type_id": "configurable"
                    },
                    "quantity": 2
                },
                {
                    "id": "15",
                    "product": {
                        "name": "Sprite Yoga Companion Kit",
                        "sku": "24-WG080",
                        "stock_status": "IN_STOCK",
                        "type_id": "bundle"
                    },
                    "quantity": 1
                }
            ]
        }
    }
}`
7. Update the cart items
Request: `mutation {
	updateCartItems(
		input: {
			cart_id: "{{CustomerCart}}",
			cart_items: [
                {
					cart_item_id: 8 quantity: 0
				},
                {
					cart_item_id: 13 quantity: 0
				},
				{
					cart_item_id: 15 quantity: 0
				},
			]
		}) {
		cart {
			items {
				id product {
					name
				}
				quantity
			}
			prices {
				grand_total {
					value currency
				}
			}
		}
	}
}`
Response: `{
    "data": {
        "updateCartItems": {
            "cart": {
                "items": [
                    {
                        "id": "7",
                        "product": {
                            "name": "SimpleProd02"
                        },
                        "quantity": 8
                    },
                    {
                        "id": "9",
                        "product": {
                            "name": "Teton Pullover Hoodie"
                        },
                        "quantity": 2
                    }
                ],
                "prices": {
                    "grand_total": {
                        "value": 176,
                        "currency": "USD"
                    }
                }
            }
        }
    }
}`
8. Again get the cart items and check products' quantity set to zero from above query are skipped in the response-
Request: `
  { 
    cart(cart_id: "{{CustomerCart}}") {
    items {
      id
      product {
        name
        sku
        stock_status,
        type_id
      }
      quantity
    }
  }
}`
Response: `{
    "data": {
        "cart": {
            "items": [
                {
                    "id": "7",
                    "product": {
                        "name": "SimpleProd02",
                        "sku": "SimpleProd02",
                        "stock_status": "IN_STOCK",
                        "type_id": "simple"
                    },
                    "quantity": 8
                },
                {
                    "id": "9",
                    "product": {
                        "name": "Teton Pullover Hoodie",
                        "sku": "MH02",
                        "stock_status": "IN_STOCK",
                        "type_id": "configurable"
                    },
                    "quantity": 2
                }
            ]
        }
    }
}`

Here, as we can see, cart items for which quantity set to zero are removed from the get cart items response.
It is clear that, the issue must have fixed already along with any other code fixes.
Hence, I am currently closing this particular issue.
In case, if you find the same issue in the Magento code 2.4-develop version, please re-update the steps to reproduce here, or if there is any configurations or anything required to done to reproduce it. Or you may report a new issue as well. Based on that, we will re-consider the issue.
Thanks

**Closed as completed by engcom-Alfa** 2022-08-24 10:57 UTC
Labels: Issue: Format is valid, Partner: Kensium Solutions LLC, Priority: P2, Project: GraphQL, PAP, Progress: done
