### ISSUE TITLE
Magento backend dashboard: Most viewed products tabs gives 404 error in console.

### ISSUE THREAD

**Issue by vishal-7037** [magento/magento2#22001] opened 2019-03-28 10:02 UTC
There is an issue on the dashboard page of Magento backend. When you clicked on **Most viewed products** tabs you will get 404 error in the developer console.

I've also checked in vanilla Magento instance. an error also occurs there.
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

1. Login to Magento admin
2. Click on **Most viewed products** tabs, a spinner will be loading continuously.
3. Open developer console, you will get 404 error.

### Expected result (*)

![2019_03_28_Expected_result](https://user-images.githubusercontent.com/38535982/55148556-6f798c80-516e-11e9-8abf-eed7398b47c2.png)

### Actual result (*)

![2019_03_28_Dashboard_product_view_tab](https://user-images.githubusercontent.com/38535982/55148559-74d6d700-516e-11e9-97ec-b9c5228ae9f2.png)

**Comment by magento-engcom-team** [comment] 2019-03-28 10:02
Hi @vishal-7037. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@vishal-7037 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-03-28 19:19
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-03-28 19:20
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98946` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-04-11 19:15
Hi @vishal-7037. Thank you for your report. 
The issue has been fixed in magento/magento2#22002 by @vishal-7037 in 2.3-develop branch
Related commit(s):
 - [9e6f56bee5b354981a7a45bac26620f598d9cd72](https://github.com/magento/magento2/commit/9e6f56bee5b354981a7a45bac26620f598d9cd72)
 - [8a98f208245d381d3fff0bb22c47f757b89f6e07](https://github.com/magento/magento2/commit/8a98f208245d381d3fff0bb22c47f757b89f6e07)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-04-11 19:15 UTC
Labels: Issue: Ready for Work, Component: Cms, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Reports
