### ISSUE TITLE
Reorder issue with product custom option error "The product has required options. Enter the options and try again." on cart Page

### ISSUE THREAD

**Issue by rahulbarotk** [magento/magento2#33418] opened 2021-07-05 07:16 UTC
**Preconditions (*)**

Magento 2.4.2 EE
Reordering an order with products that have required custom options as checkbox type.

**Steps to reproduce (*)**

Install and Setup Fresh Magento 2.4.2
Create a product with required custom option with input type as checkbox
Add this product to cart by checking the checkbox and place an order with any payment method.
Now click reorder link of the same order from the customer dashboard.
Customer redirected to cart page with errors "Some of the products below do not have all the required options." and "The product has required options. Enter the options and try again.".

**Expected result (*)**

Products should be added to the shopping cart successfully by automatic selecting custom option.

**Actual result (*)**
Failed to add product in cart with error messages("Some of the products below do not have all the required options." and "The product has required options. Enter the options and try again.".

I've found similar [issue](https://github.com/magento/magento2/issues/30437) and it was fixed in M2.4 develop branch. The changes are there in the M2.4.2 but the issue still persist.

**Comment by DevAwesomeK** [comment] 2021-07-05 07:17
@magento give me 2.4-develop instance

**Comment by DevAwesomeK** [comment] 2021-07-05 07:35
Issue is not reproducible on 2.4-develop instance but it is still there on 2.4.2 EE.

**Comment by engcom-November** [comment] 2021-07-08 13:16
I verified the issue on Magento 2.4-develop having EE modules installed and 2.4.2-P1 versions and the issue is not reproducible with above steps mentioned but able to reproduce the issue in Product Cart page with below steps:
**Steps performed:**
Pre-Conditions:
Enable Allow Reorders (Stores -> Configuration -> Sales -> Sales -> Reorder)
1. Front-end -> Added existing product to Cart
2. Admin -> Catalog -> Products -> Edit the same above product -> Customizable Options -> Add Option type Checkbox and Saved
3. Navigate/Refresh Front-end page
4. Add the product again to cart with checkbox selected
5. Go to Products Cart page
**Issue:** Two error messages are getting displayed in Products Cart page:
"Some of the products below do not have all the required options."
"The product has required options. Enter the options and try again."
![image](https://user-images.githubusercontent.com/60198231/124927704-8cbf8580-e01c-11eb-8745-b0f024c6e5da.png)

![image](https://user-images.githubusercontent.com/60198231/124927658-829d8700-e01c-11eb-938f-ee6827630bb3.png)

**Comment by sdzhepa** [comment] 2021-07-13 18:01
Hello @engcom-November 

Due to comment https://github.com/magento/magento2/issues/33418#issuecomment-876431056

> I verified the issue on Magento 2.4-develop having EE modules installed and 2.4.2-P1 versions and the issue is not reproducible with above steps mentioned

It is not clear you confirmed the issue from the description or from your comment


Could you please update Issue description with clear and valid steps to reproduce?
Thank you in advance!

**Comment by DevAwesomeK** [comment] 2021-07-14 04:42
@sdzhepa  and @engcom-November  I've found that the issue is reproducible on Magento 2.4.2 EE having default B2B modules installed. I've raised the issue to magento commerce support and they provided patch for it.

**Comment by engcom-November** [comment] 2021-07-15 07:51
Hi @DevAwesomeK, I verified the issue on Magento 2.4 develop branch having both EE and B2B Modules installed but the issue is not reproducible with the steps provided by you but is reproducible with other steps which I've mentioned in the [comment](https://github.com/magento/magento2/issues/33418#issuecomment-876431056) 
@sdzhepa I have provided link of my comment in the Issue description at the end.
Thank you.

**Comment by magento-engcom-team** [comment] 2021-07-18 04:28
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42872` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Closed as completed** 2021-08-03 12:18 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Progress: done, Reported on 2.4.2, Component: Frontend
