### ISSUE TITLE
Magento 2 Async Bulk API - Media creation fails

### ISSUE THREAD

**Issue by abcpremium** [magento/magento2#37315] opened 2023-03-30 10:44 UTC
### Preconditions and environment

- Magento version 2.4.6

### Steps to reproduce

Send payload with authoriztion token to https://your-store.com/rest/all/async/bulk/V1/products/bySku/media (base64_encoded_data is replaced with a random timestamp here to make it more readable)

Payload looks like this:
```
[
    {
        "sku": "2sa00020",
        "entry": {
            "media_type": "image",
            "label": "2sa00020",
            "position": 1,
            "disabled": false,
            "types": [
                "small_image",
                "image"
            ],
            "content": {
                "base64_encoded_data": 1680172613,
                "type": "image\/png",
                "name": "2sa00074_sap_baseballcap_weiss_01_1.png"
            }
        }
    },
    {
        "sku": "2sa00031",
        "entry": {
            "media_type": "image",
            "label": "2sa00031",
            "position": 1,
            "disabled": false,
            "types": [],
            "content": {
                "base64_encoded_data": 1680172613,
                "type": "image\/png",
                "name": "2sa00031_lamy_schreibgeraete_set_02_2.png"
            }
        }
    }
]
```

### Expected result

I should get back a Bulk UUID

### Actual result

I get the following errors:

"sku" is required. Enter and try again
"entry" is required. Enter and try again

### Additional information

But as you can see in my payload, I transmit those details for every entry according to the docs.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-04-28 13:01
Hi @abcpremium,


Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

We are able to get BULK UUID.


<img width="837" alt="Screenshot 2023-04-28 at 2 08 56 PM" src="https://user-images.githubusercontent.com/51680745/235109143-101cf274-0d2c-4d34-ada9-32e512df0135.png">




Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-05-11 06:35
Hi @abcpremium,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-05-11 06:35 UTC
Labels: Issue: needs update, Reported on 2.4.6
