### ISSUE TITLE
Reindex cataloginventory_stock does not update cataloginventory_stock_status in 2.4.5

### ISSUE THREAD

**Issue by melnickforever** [magento/magento2#37450] opened 2023-05-02 17:26 UTC
### Preconditions and environment

- Magento version 2.3.5-p1
- in Magento 2.3.6 reindex cataloginventory_stock update field stock_status in the table cataloginventory_stock_status in 2.4.5-p1 - no

### Steps to reproduce

Update directly stock_status in cataloginventory_stock_status .(imports can do this)
Run cataloginventory_stock reindex

### Expected result

field stock_status in table cataloginventory_stock_status - updated

### Actual result

field stock_status in table cataloginventory_stock_status - outdated

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-05-03 07:33
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-05-04 06:50
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-05-04 13:33
Hi @melnickforever,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Update directly stock_status in cataloginventory_stock_status .(imports can do this)
- Run cataloginventory_stock reindex

We have imported a CSV file to update the stock of the product and the stock of the product is updated in both admin and table cataloginventory_stock_status field.


<img width="584" alt="Screenshot 2023-05-04 at 12 41 38 PM" src="https://user-images.githubusercontent.com/51680745/236135516-2c652dd0-22bd-4bea-a8c8-15844d1844c2.png">



<img width="1385" alt="Screenshot 2023-05-04 at 12 41 47 PM" src="https://user-images.githubusercontent.com/51680745/236135551-a5287c3d-e006-4796-8bb7-91e90d881ca3.png">


We have Imported Below CSV file :

[Update.csv](https://github.com/magento/magento2/files/11394581/Update.csv)


When we update status of the product with the import in that case also both are updated.

<img width="1367" alt="Screenshot 2023-05-04 at 12 51 15 PM" src="https://user-images.githubusercontent.com/51680745/236136792-776aa402-2329-46fb-88e9-55be90709f9a.png">


<img width="511" alt="Screenshot 2023-05-04 at 12 50 05 PM" src="https://user-images.githubusercontent.com/51680745/236136849-eb0bfec4-43b7-475b-bfd9-0c8059c667c8.png">


[Update.csv](https://github.com/magento/magento2/files/11394627/Update.csv)




Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-05-15 06:03
Hi @melnickforever,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-05-15 06:03 UTC
Labels: Issue: needs update, Reported on 2.3.5-p1

**Comment by pmathbliss** [comment] 2023-06-06 22:23
There is an issue with the cataloginventory_stock indexer. 

The same value in the cataloginventory_stock_status is put into the table if the product is in stock and the record already exists in the table.

`SELECT
  `e`.`entity_id`,
  `cis`.`website_id`,
  `cis`.`stock_id`,
  IF(cisi.qty > 0, cisi.qty, 0) AS `qty`,
  IF(
    cisi.use_config_manage_stock = 0
    AND cisi.manage_stock = 0,
    1,
    IF(
      cisi.is_in_stock = 0,
      0,
      IF(
        css.stock_status IS NOT NULL,
        css.stock_status,
        MAX(cisi.is_in_stock)
      )
    )
  ) AS `status`
FROM
  `catalog_product_entity` AS `e`
  CROSS JOIN `cataloginventory_stock` AS `cis`
  INNER JOIN `cataloginventory_stock_item` AS `cisi`
    ON cisi.stock_id = cis.stock_id
    AND cisi.product_id = e.entity_id
  INNER JOIN `catalog_product_entity_int` AS `mcpei`
    ON e.entity_id = mcpei.entity_id
    AND mcpei.attribute_id = 96
    AND mcpei.value = 1
  LEFT JOIN `cataloginventory_stock_status` AS `css`
    ON css.product_id = e.entity_id
WHERE (cis.website_id = 0)
  AND (e.type_id = 'simple')
  AND (
    e.entity_id IN (
      2508,
      2509,
      2510))`
This
`IF(
        css.stock_status IS NOT NULL,
        css.stock_status,
        MAX(cisi.is_in_stock)
      )`
      
      puts the same value back in the table rather than the current in stock value.
      
attribute_id 96 is product status.

**Comment by ValerieS** [comment] 2023-06-08 15:50
@magento-admin  please reopen

**Comment by VictorSoaresRedstage** [comment] 2023-07-19 19:58
> Anyone looking for a fix.
> 
> vendor/magento/module-inventory-catalog/Model/ResourceModel/StockStatusExpressionForDefaultStock.php
> 
> Line 49, $connection->getCheckSql('css.stock_status IS NOT NULL', 'css.stock_status', $stockItemInStockField) change to $connection->getCheckSql('css.stock_status IS NOT NULL', 'cisi.is_in_stock', $stockItemInStockField)

Thanks @pmathbliss, I had the same issue and this worked for me.

**Comment by stefanskotte** [comment] 2023-08-07 12:09
@pmathbliss Awesome - works here too !

**Comment by tayner** [comment] 2023-08-30 16:00
Thank you! Good job

**Comment by joeldavuk** [comment] 2023-11-16 21:50
Confirmed this fixed this issue in 2.4.5-p1

**Comment by LudwigDev9** [comment] 2024-03-14 10:14
Does anyone know why this is still an issue in 2.4.x?

I see the changes was never merged from https://github.com/magento/inventory/pull/3388

I have been dealing with the issue as well and wanted to find out from @pmathbliss, if we update the code as per above does this automatically correct all products per index? or will that still be an manual process?

**Comment by splacento-incomm** [comment] 2024-04-12 00:07
> Anyone looking for a fix.
> 
> vendor/magento/module-inventory-catalog/Model/ResourceModel/StockStatusExpressionForDefaultStock.php
> 
> Line 49, $connection->getCheckSql('css.stock_status IS NOT NULL', 'css.stock_status', $stockItemInStockField) change to $connection->getCheckSql('css.stock_status IS NOT NULL', 'cisi.is_in_stock', $stockItemInStockField)

Having same issue on 2.4.6. 
This actually works, thank you!

**Comment by joachimVT** [comment] 2024-05-08 09:46
Having the same issue on 2.4.6-p4

**Comment by stefanskotte** [comment] 2024-07-03 20:59
Confirmed working on 2.4.6-p7 as well, thank you @splacento-incomm this just made my day so much better. One less bug to worry about ..... until the next 🥇

**Comment by devsmem** [comment] 2025-01-15 22:46
Confirmed it is an issue on 2.4.7-p3. Patch https://github.com/magento/magento2/issues/37450#issuecomment-1815369901 resolved it. Why is this issue closed ?! @engcom-Bravo , please reopen this.
