### ISSUE TITLE
Account sidebar current tab is not marked as Active

### ISSUE THREAD

**Issue by ankitpatel2931** [magento/magento2#24068] opened 2019-08-08 13:14 UTC
### Preconditions (*)

1. Magento 2.3.2
2. Sample data installed

### Steps to reproduce (*)

1. Login as customer. You can see below screen.
![AwesomeScreenshot-nlipoenfbbikpbjkfpfillcgkoblgpmj-upload html-2019-08-08_6_36](https://user-images.githubusercontent.com/44745569/62705669-790fdc80-ba0b-11e9-99ce-5013b47351b8.png)

2. Please note URL here.
a)  /customer/account/
b) As above screenshot, My Account tab selected as current tab.

3. Please add index/ after /customer/account/
So URL become like  /customer/account/index/
![AwesomeScreenshot-nlipoenfbbikpbjkfpfillcgkoblgpmj-upload html-2019-08-08_6_40](https://user-images.githubusercontent.com/44745569/62705897-fb000580-ba0b-11e9-8f0d-e800f30efc46.png)

You can see My Account tab is not marked as activate tab for /customer/account/index/. This issue available with whole sidebar tab in customer account section.

### Expected result (*)

1. My Account tab marked as activate tab for below both URLs.
a)  /customer/account/
b)  /customer/account/index/
2. Same thing with all other sidebar links.

### Actual result (*)

1. My Account tab is not marked as activate tab for below URL.
a)  /customer/account/index/
![AwesomeScreenshot-nlipoenfbbikpbjkfpfillcgkoblgpmj-upload html-2019-08-08_6_40](https://user-images.githubusercontent.com/44745569/62706130-7f528880-ba0c-11e9-9381-b251e4feabd9.png)

**Comment by engcom-Bravo** [comment] 2019-08-08 13:26
The issue is noticed to be actual for such sections as My Account, My Wish List, Address Book and Newsletter Subscription.

**Comment by magento-engcom-team** [comment] 2019-08-08 13:27
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19040` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ankitpatel2931** [comment] 2019-08-08 14:29
Hi @engcom-Bravo , @magento-engcom-team ,

Thanks for confirmation.
Please let me know If I can do any thing in this.

**Comment by engcom-Bravo** [comment] 2019-08-08 14:38
Ok @ankitpatel2931, You are always welcome.

**Comment by magento-engcom-team** [comment] 2019-08-15 22:20
Hi @ankitpatel2931. Thank you for your report. 
The issue has been fixed in magento/magento2#24078 by @edenduong in 2.3-develop branch
Related commit(s):
 - [491b29554b54f043315844fd1e4c0e7d48933137](https://github.com/magento/magento2/commit/491b29554b54f043315844fd1e4c0e7d48933137)
 - [b32b91b9fe56dd007eaa5fc41dcc67c0c3f8749c](https://github.com/magento/magento2/commit/b32b91b9fe56dd007eaa5fc41dcc67c0c3f8749c)
 - [a1323a84a4534485620c1a7afdec4f700ec8c9b3](https://github.com/magento/magento2/commit/a1323a84a4534485620c1a7afdec4f700ec8c9b3)

The fix will be available with the upcoming 2.3.4 release.

**Closed as completed by magento-engcom-team** 2019-08-15 22:20 UTC
Labels: Issue: Ready for Work, Component: Customer, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid
