### ISSUE TITLE
Order by SKU feature is not working properly when trying to add out of stock product into the cart

### ISSUE THREAD

**Issue by brettrootways** [magento/magento2#38957] opened 2024-07-22 11:36 UTC
### Preconditions and environment

- Magento version: 2.4.6-p4 (Enterprise Edition)
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

1) Login with the customer account.
2) Go to the Order by SKU page.
3) Add out-of-stock product SKU and QTY to the input box.
4) Click on the add to cart button.
5) We get the below error When we click the add to cart button.
TypeError: Unsupported operand types: string * int in vendor/magento/module-quote/Model/Quote/Item.php:847

### Expected result

Either we should not be able to add the out-of-stock product into the cart, or we should get some kind of exception message on the front end when we do the add to cart for an out-of-stock product.

### Actual result

TypeError: Unsupported operand types: string * int in vendor/magento/module-quote/Model/Quote/Item.php:847

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by brettrootways** [comment] 2024-07-22 11:37
@magento give me 2.4-develop instance

**Comment by brettrootways** [comment] 2024-07-22 11:49
@magento 
We need an instance of the Magento enterprise edition. I think you shared the instance of the Open source edition. I can not see the "Order By SKU" settings in the admin

**Comment by engcom-Dash** [comment] 2024-07-23 06:56
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2024-07-23 08:28
Hi @brettrootways 

Thanks for reporting and collaboration.

Verified the issue on Magento 2.4 dev instance and Magento 2.4.7-p1 but the issue is not reproducible.

We are getting the error message "This product is out of stock." error message with an order by SKU when the product is out-of-stock.

Steps to reproduce

1. Log in with the customer account.
2. Go to the Order by SKU page.
3. Add out-of-stock product SKU and QTY to the input box.
4. Click on the add to cart button.
5. We get the below error When we click the add to cart button.
TypeError: Unsupported operand types: string * int in vendor/magento/module-quote/Model/Quote/Item.php:847

Please refer to the attached screenshots and let us know if we missed anything.

In 2.4 dev instance:

<img width="1440" alt="Screenshot 2024-07-23 at 1 44 40 PM" src="https://github.com/user-attachments/assets/39cd6a4a-7d42-4d43-946c-c519fb44dcd9">

In 2.4.7-p1 instance:

<img width="1440" alt="Screenshot 2024-07-23 at 12 29 13 PM" src="https://github.com/user-attachments/assets/d79f340b-46f4-4ebf-ac71-b8ef1794cd77">

**Comment by brettrootways** [comment] 2024-07-23 09:58
Okay, let me check again if we can reproduce the issue.

**Comment by engcom-Bravo** [comment] 2024-08-07 04:57
Hi @brettrootways,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-08-07 04:57 UTC
Labels: Issue: needs update, Reported on 2.4.6-p4
