### ISSUE TITLE
updateStockItemBySku returns 200 for configurable products

### ISSUE THREAD

**Issue by mc388** [magento/magento2#2392] opened 2015-11-17 08:11 UTC
Hi,

if I set the stock item quantity via webapi in `module-catalog-inventory` it works fine for simple products. When I try to set the quantity on a configurable product, the quantity is not set (thats right) but the api responds with http status code 200, I would expect 400 bad request.

The API call:
```
curl -X PUT "http://magento2-dev.io/index.php/rest/V1/products/<CONFIGURABLE_PRODUCTSKU>/stockItems/1" -H "Content-Type:application/json" -H "Authorization:Bearer <AUTH-TOKEN>" -d '{ "stockItem": { "qty": 10, "is_in_stock": 1 } }'
```

**Edit:**
The same issue when a simple product is configured to `Manage Stock = No`. In this situation I also would expect a 400 http status code instead of 200. The stock quantity is not set.

**Comment by vzabaznov** [comment] 2016-06-22 12:56
To allow us research the issue, please, provide description according to the template.

**Comment by vzabaznov** [comment] 2016-06-22 13:10
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment] 2016-07-14 09:27
Hi, @mc388 thank you for contributing, i will close this issue for now as no update more than 14 days, if you think that issue is still reproducible, please fell free to open another one.

**Closed by vzabaznov** 2016-07-14 09:27 UTC
Labels: bug, MX, needs update
