### ISSUE TITLE
Infinite loading after 999 page was selected

### ISSUE THREAD

**Issue by lghelghe** [magento/magento2#38002] opened 2023-09-19 20:57 UTC
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

log in
Changed to 999 per page
Few days later
Log in
infinite loading will never stop then show error popup
but no way to get out

### Expected result

either it gives me an option to change # per page, or way to reset all filters to default

### Actual result

infinite loading & error popup > repeat

### Additional information

![image](https://github.com/magento/magento2/assets/143628070/dce2847f-7cb1-438d-9bca-d8c0647cff47)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-09-21 07:29
Hi @lghelghe,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- log in
- Changed to 999 per page


<img width="1496" alt="Screenshot 2023-09-21 at 12 27 18 PM" src="https://github.com/magento/magento2/assets/51680745/9e57c891-aa2a-4ce7-bb08-c094567f3a0e">



<img width="1471" alt="Screenshot 2023-09-21 at 12 27 44 PM" src="https://github.com/magento/magento2/assets/51680745/8335db4c-c850-4ccb-a1c6-a22654726e0e">



it might be possible the issue is resolved in the latest 2.4-develop branch. I request you to please try to reproduce the issue in the latest development branch and  check if any 3rd party extensions / modules enabled is causing this issue




Thanks.

**Comment by engcom-Bravo** [comment] 2023-09-26 06:39
Hi @lghelghe,

Thanks for your update.

<img width="1494" alt="Screenshot 2023-09-26 at 12 08 51 PM" src="https://github.com/magento/magento2/assets/51680745/1b59fe81-1cf6-465b-9fe1-058269698420">


It seems to be issue is caused by third party modules Please check the issue  if any 3rd party extensions / modules enabled is causing this issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-10-09 05:39
Hi @lghelghe,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-10-09 05:39 UTC
Labels: Issue: needs update, Reported on 2.4.x
