### ISSUE TITLE
Pagination drop-down size does not appropriate.

### ISSUE THREAD

**Issue by mage2pratik** [magento/magento2#21296] opened 2019-02-18 13:00 UTC
Pagination drop-down size does not appropriate.

### Preconditions (*)

1. Magento 2.3.x
2. Php 7.1.2

### Steps to reproduce (*)

1. Go to Admin
2. Content >> Blocks
3. Review the pagination drop-down size.

### Expected result (*)

![screenshot](https://user-images.githubusercontent.com/33807558/52952577-fa66aa80-33aa-11e9-99ac-05ff68479a63.png)

### Actual result (*)

![screenshot2](https://user-images.githubusercontent.com/33807558/52952591-03577c00-33ab-11e9-8891-25cc03c17aa3.png)

**Comment by magento-engcom-team** [comment] 2019-02-18 13:00
Hi @mage2pratik. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mage2pratik do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-02-18 13:00
Hi @krishprakash. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by krishprakash** [comment] 2019-02-18 13:02
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-18 13:02
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-18 13:03
Hi @krishprakash, here is your [Magento instance](https://i-21296-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21296-2-3-develop.instances.magento-community.engineering/admin](https://i-21296-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2019-02-18 13:05
![drop-down](https://user-images.githubusercontent.com/46617848/52952924-128af980-33ac-11e9-89b2-4896b71cacf3.png)

**Comment by magento-engcom-team** [comment] 2019-02-19 08:14
Hi @dmytro-ch. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-02-19 08:18
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98316` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dmytro-ch** [comment] 2019-02-19 08:20
Please note, the issue is not reproducible on `2.2-develop` branch.

**Comment by magento-engcom-team** [comment] 2019-02-24 18:05
Hi @mage2pratik. Thank you for your report. 
The issue has been fixed in magento/magento2#21298 by @mage2pratik in 2.3-develop branch
Related commit(s):
 - [9d4f13cc80d711fd9ac279f18cc6aa5b3576b178](https://github.com/magento/magento2/commit/9d4f13cc80d711fd9ac279f18cc6aa5b3576b178)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-02-24 18:05 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Admin
