### ISSUE TITLE
Google console returning Sitemap unreadable

### ISSUE THREAD

**Issue by FrankRATB** [magento/magento2#35147] opened 2022-02-28 07:11 UTC
### Preconditions (*)

1.Magento 2.4.0
2.

### Steps to reproduce (*)

1. I generated the XML sitemap via magento>marketing>sitemap - screen shot attached 
![Sitemap_error_280222_2](https://user-images.githubusercontent.com/100557130/155939615-0f5e05e5-0e0f-40ef-bd73-49aae99e3a84.png)

2. However Google console reports this as unreadable as the sitemap is an HTML - screen shot attached
![Sitemap_error_280222](https://user-images.githubusercontent.com/100557130/155939631-5dc9cc49-5f7f-40de-98bb-e3843df247fe.PNG)

### Expected result (*)

1. Google console should successfully read my XML sitemap without any errors
2.

### Actual result (*)

1. Google console reports this as unreadable as the sitemap is an HTML - screen shot attached
![Sitemap_error_280222](https://user-images.githubusercontent.com/100557130/155938226-73e6ea94-06d6-413e-a17d-d767d996241c.PNG)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [*] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-02-28 11:04
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue.
![image](https://user-images.githubusercontent.com/60198231/155972391-ff67d645-7b41-422a-b4b6-39aba78ba241.png)
@FrankRATB kindly verify the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-03-14 11:29
Hi @FrankRATB ,
We are closing this issue as there has been no latest update on the same.

**Closed as completed by engcom-November** 2022-03-14 11:29 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.0

**Comment by pmonosolo** [comment] 2022-06-17 22:05
Hello,

This is a serious issue. This is still present on 2.4.3-p2

Due to recent move of Magento to use /pub as a root folder, the sitemap.xml generates the paths as:

```
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap>
<loc>https://website.com/pub/sitemap-1-1.xml</loc>
<lastmod>2022-06-17T20:55:18+00:00</lastmod>
</sitemap>
<sitemap>
<loc>https://website.com/pub/sitemap-1-2.xml</loc>
<lastmod>2022-06-17T20:55:18+00:00</lastmod>
</sitemap>
<sitemap>
<loc>https://website.com/pub/sitemap-1-3.xml</loc>
<lastmod>2022-06-17T20:55:18+00:00</lastmod>
</sitemap>
<sitemap>
<loc>https://website.com/pub/sitemap-1-4.xml</loc>
<lastmod>2022-06-17T20:55:18+00:00</lastmod>
</sitemap>
</sitemapindex>
```

When Google visits, the /pub/sitemap-1-1.xml it returns a 304 response for some reason and does not read the file.

![image](https://user-images.githubusercontent.com/66754347/174405990-835c39d9-2cd5-45ec-88d0-0b019eb2c29d.png)

Now, this happens even if you deleted, regenerated and it's a completely different file, it still shows 304 request.

![image](https://user-images.githubusercontent.com/66754347/174406535-7670a0ae-5a59-453b-baa5-dd052a048ae0.png)

I think this is related to /pub folder location. 

If you upload the file with direct link /sitemap-1-1.xml its accepted no problem (with the redirect from /pub/sitemap-1-1.xml to /sitemap-1-1.xml):

![image](https://user-images.githubusercontent.com/66754347/174406568-a7183f47-071b-4222-aa9d-632d931e2185.png)

The files have no permission issues or anything. 

The worse problem is that we cant even change the path above the /pub folder. If you set / path it will still apply /pub to sitemap-1-1.xml.

**Comment by pmonosolo** [comment] 2022-06-17 22:06
Another complication:
Apparently if you do not submit your sitemaps via Google Search Console, it will assume the URLs within the sitemaps need to use /pub path.

Here is a twitter thread from Google Engineers about this:
https://www.seroundtable.com/google-xml-sitemap-file-location-26348.html#:~:text=Sitemaps%20only%20Valid%20for%20their,sub%2Ddirectory....&text=Depending%20on%20how%20they%20were,only%20valid%20there%20%26%20lower%20levels.

**Comment by pmonosolo** [comment] 2022-06-17 22:19
Moving to subfolder /pub/sitemap has no effect either.

@engcom-November Can you please re-visit / re-open this issue?

**Comment by pmonosolo** [comment] 2022-06-17 22:28
I have tried:

- reducing the file size from 10MB to 5MB
- reducing the product number form 25,000 products to 20,000 products

Same result. 

Flushing cache on Cloudflare, Magento also has no effect.

**Comment by pmonosolo** [comment] 2022-06-17 22:29
The file structure is also correct. I have checked the files for integrity and XML formatting is correct.
