### ISSUE TITLE
Unable to save Visual Swatch attribute

### ISSUE THREAD

**Issue by LordHansolo** [magento/magento2#10818] opened 2017-09-08 07:29 UTC
I can't save visual swatch attribute with option value 0 in admin field.

### Preconditions

1. Magento 2.1.7 / Magento 2.1.8 EE
2. OS: Ubuntu 16.04
3. Server: Apache/2.4.18
4. Mysql version 5.7.19
5. PHP 7.0.22-0ubuntu0.16.04.1

### Steps to reproduce

1. Add new product attribute type visual swatch in admin panel
2. Assign value 0 to option in admin field
![swatch_value_zero](https://user-images.githubusercontent.com/22025597/30200572-d0122c2e-9477-11e7-8b66-8b49580a3ed1.png)
3. Save Attribute

### Expected result

1. Attribute save properly with value 0 in admin field 

### Actual result

1. We get error message "Admin is a required field in the each row" and attribute is not saved
![swatch_error_message](https://user-images.githubusercontent.com/22025597/30200681-3b8367b6-9478-11e7-8df5-f40a0218607a.png)

**Comment by orlangur** [comment] 2017-09-08 09:13
The fix for https://github.com/magento/magento2/issues/9619 is already in `2.1-develop` branch thus will be released in one of the next `2.1.x` versions.

I believe the same code is responsible for both text/visual swatch label validation, would be nice if you check if the issue is gone on `2.1-develop` or `2.1.10-preview`. Thus not marking as duplicate before confirmation.

**Comment by LordHansolo** [comment] 2017-09-09 21:18
I confirm that problem is resolved both 2.1-develop and 2.1.10-preview branch.

**Comment by magento-engcom-team** [comment] 2017-09-11 01:58
Thank you @orlangur for the investigation of this issue! 👍 
Closing the issue. Fix will be available with 2.1.10 release

**Closed as completed by magento-engcom-team** 2017-09-11 01:58 UTC
Labels: bug report, duplicate, Issue: Format is valid

**Comment by mrpatrick** [comment] 2019-06-20 18:07
This doesn't appear to be fixed - We are still seeing the issue in v2.2.3.  I also don't see any reference to the fix in the CHANGELOG.  Can't someone point me to where this was fixed?
