### ISSUE TITLE
Custom option image upload fails check-out with PayPal

### ISSUE THREAD

**Issue by ddznelad** [magento/magento2#6384] opened 2016-08-29 15:56 UTC
Getting exception: Call to a member function isFile() on null in .../vendor/magento/module-catalog/Model/Product/Option/Type/File.php on line 452. If use payment methods other than PayPal it does not fail - copyQuoteToOrder function is used when use PayPal. In this function _rootDirectory variable never initialized anywhere and is therefore null. If I modify code and initialize the variable correctly using
$filesystem->getDirectoryWrite(DirectoryList::MEDIA) it fixes the issue partially - the order will be created and link is generated like site.com/sales/download/downloadCustomOption/id/19/key/e45e0dc5bb08417063e6/?SID=xxxxxxxxxxx, but if I click the link "page not found" pops-up
### Preconditions

1. Magento v2.1 CE
2. PHP 7.0
### Steps to reproduce

1. Set up PayPal Express
2. Create product with image upload custom option
3. in front-end upload image and proceed to checkout using PayPal
### Expected result

1. Order should be created
2. In order there should be link of the image.
3. If you click the link to image the image should be downloaded
### Actual result

1. Server returns 500 error. PHP error log contains: PHP Fatal error: Call to a member function isFile() on null in .../vendor/magento/module-catalog/Model/Product/Option/Type/File.php on line 452

**Comment by ddznelad** [comment] 2016-08-29 23:57
If I apply my fix and click the image link at order info page, the option data will not be found in Magento\Sales\Controller\Download controller "DownloadCustomOption" function;

**Comment by ddznelad** [comment] 2016-09-01 13:17
I found that my fix work for simple product, but for configurable product the issue remains. 
In case of configurable product  everything is fine until I hit "Place Order" button after PayPal procedure: I get "can't place an order' error (caused by exception in magento/module-catalog/Model/Product.php ) . See attached log.
[system_log.txt](https://github.com/magento/magento2/files/449702/system_log.txt)

**Comment by alena-marchenko** [comment] 2016-09-22 09:44
Hi @ddznelad 

We've created MAGETWO-58851 internal ticket regarding this issue.
Thank you!

**Comment by samrevs** [comment] 2017-01-30 12:47
Does anyone have an update/fix for this issue?

**Comment by kandarp26** [comment] 2017-07-19 10:45
Added have same issue 

Solution : vendor\magento\module-catalog\Model\Product\Option\Type\File.php line no 451 

Before 

`if (!$this->_rootDirectory->isFile($quotePath) || !$this->_rootDirectory->isReadable($quotePath))  `

add below 2 lines 

```
$filesystem = $this->_objectManager->get('Magento\Framework\Filesystem');
$this->_rootDirectory = $filesystem->getDirectoryRead(DirectoryList::ROOT);
```

**Comment by magento-engcom-team** [comment] 2017-10-11 13:30
@ddznelad, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-11 13:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue:  Cannot Reproduce, Issue: Format is valid
