### ISSUE TITLE
CAPTCHA doesn't show when check out as guest

### ISSUE THREAD

**Issue by Pakkapao** [magento/magento2#1515] opened 2015-07-18 11:08 UTC
1.0.0 Beta1

The CAPTCHA block isn't displayed while checking out as guest. The other forms are fine.

![capture](https://cloud.githubusercontent.com/assets/11070293/8761361/1683075a-2d78-11e5-90de-11b3fe77ba37.PNG)

**Comment by piotrekkaminski** [comment] 2015-10-03 17:57
internal issue MAGETWO-43625

**Comment by magento-engcom-team** [comment] 2017-09-26 22:00
@Pakkapao, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9

**Closed by magento-engcom-team** 2017-09-26 22:00 UTC
Labels: 2.1.x, 2.2.x, acknowledged, bug report, Customer, develop, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in develop, G1 Failed, G2 Passed, G3 Passed

**Comment by jchesko** [comment] 2017-09-29 13:33
We are still seeing this issue in 2.1.9

**Comment by chrisputnam9** [comment] 2018-03-07 19:09
@jchesko Confirmed - I'm still seeing this issue too.  I don't understand why it's marked as fixed.  From what I see of the code changes, and in my testing, the issue remains the same, but someone please help me understand if I'm wrong.

**Comment by Alex1844** [comment] 2018-05-11 21:51
The problem still exists in 2.2.4
Since I am brand new to Magento, can someone point me to the location of the code where i should look for the problem

**Comment by DanielRuf** [comment] 2018-05-11 21:56
How was the PR related to this?

**Comment by Alex1844** [comment] 2018-05-11 22:02
I am sorry, I do not understand the question, if it was addressed to me.

**Comment by DanielRuf** [comment] 2018-05-11 22:09
I meant https://github.com/magento/magento2/issues/1515#ref-commit-e442de5

**Comment by Alex1844** [comment] 2018-05-11 22:44
CAPTCHA doesn't show when check out as guest in 2.2.4 as well. Since it may take a while to be fixed and released, I am asking if someone can quickly point me to the location in the source code where I should look to fix myself.
