### ISSUE TITLE
There has been an error processing your request

### ISSUE THREAD

**Issue by cfcnn** [magento/magento2#2783] opened 2015-12-22 04:07 UTC
![error1](https://cloud.githubusercontent.com/assets/15027055/11947603/67192e54-a8a4-11e5-8605-8698576daa6e.jpg)

There has been an error processing your request

Exception printing is disabled by default for security reasons.

Error log record number: 696363362729

cat /home/wwwroot/www.shop.com/var/report/696363362729

```
a:4:{i:0;s:389:"Error: Application is not installed yet.
NOTE: You cannot install Magento using the Setup Wizard because the Magento setup directory cannot be accessed.
You can install Magento using either the command line or you must restore access to the following directory: /home/wwwroot/www.shop.com/setup
If you are using the sample nginx configuration, please go to http://www.shop.com/setup/";i:1;s:683:"#0 /home/wwwroot/www.shop.com/vendor/magento/framework/App/Http.php(213): Magento\Framework\App\Http->redirectToSetup(Object(Magento\Framework\App\Bootstrap), Object(Exception))
#1 /home/wwwroot/www.shop.com/vendor/magento/framework/App/Http.php(137): Magento\Framework\App\Http->handleBootstrapErrors(Object(Magento\Framework\App\Bootstrap), Object(Exception))
#2 /home/wwwroot/www.shop.com/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http->catchException(Object(Magento\Framework\App\Bootstrap), Object(Exception))
#3 /home/wwwroot/www.shop.com/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#4 {main}";s:3:"url";s:1:"/";s:11:"script_name";s:10:"/index.php";}
```

**Comment by jamescowie** [comment] 2015-12-22 04:20
Hi @cfcnn it looks like you do not have the permissions configured as per the [install guide](http://devdocs.magento.com/guides/v2.0/install-gde/install/file-system-perms.html) 

If you still face issues after configuring the permissions please ask in the [Magento 2 forums](https://community.magento.com/t5/Core-Technology-Magento-2/ct-p/Magento-2) as this feels more like a isolated configuration issue than a bug that can be reported.

**Comment by davidalger** [comment] 2015-12-22 16:22
This error message is because you've configured the web-root to point to `pub` restricting access to the setup directory which is needed for the UI installer. As the message states, you'll need to run the install process using the CLI tool (i.e. bin/magento). There are instructions for that in the install guide. Alternatively, you could make the webroot point to the root of the install vs pub so you can run the UI installer, but that defeats the purpose of using pub as webroot. As this is not a bug, but a technical support question, I'm closing this issue. Please refer any further questions to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

**Closed as completed by davidalger** 2015-12-22 16:22 UTC
