### ISSUE TITLE
Dependencies Conflict upgrading from CE 2.4.0 to 2.4.1

### ISSUE THREAD

**Issue by bagbarn** [magento/magento2#31915] opened 2021-02-01 04:33 UTC
### Preconditions (*)

1.2.4.0
2.

### Steps to reproduce (*)

1.php7.3 -d memory_limit=4G -d allow_url_fopen=1 composer.phar require magento/product-community-edition 2.4.1 --no-update
2.php7.3 -d memory_limit=4G -d allow_url_fopen=1 composer.phar update

### Expected result (*)

1. [Screenshots, logs or description]
2.Expect Composer to update to M 2.4.1

### Actual result (*)

1. [Screenshots, logs or description]
2.3d-bag  [bagbarn@c133d-bag /home/jetrails/dev.bagbarn.com/html]$ php7.3 -d memory_limit=4G -d allow_url_fopen=1 composer.phar update
Loading composer repositories with package information
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is now available and you should upgrade. See https://getcomposer.org/2
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for magento/inventory-composer-metapackage 1.1.5 -> satisfiable by magento/inventory-composer-metapackage[1.1.5].
    - Can only install one of: magento/module-inventory-source-deduction-api[1.0.8, 1.1.0].
    - magento/inventory-metapackage 1.2.1 requires magento/module-inventory-source-deduction-api 1.1.0 -> satisfiable by magento/module-inventory-source-deduction-api[1.1.0].
    - magento/inventory-composer-metapackage 1.1.5 requires magento/module-inventory-source-deduction-api 1.0.8 -> satisfiable by magento/module-inventory-source-deduction-api[1.0.8].
    - Installation request for magento/inventory-metapackage 1.2.1 -> satisfiable by magento/inventory-metapackage[1.2.1].

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2021-02-02 13:00
Hi @bagbarn thank you for your report, I'm not able to reproduce issue by steps you described. 
**Result:**
:heavy_check_mark: `composer update` is end without errors while upgrading from 2.4.0 to 2.4.1 on php7.3
![Screenshot from 2021-02-02 14-51-35](https://user-images.githubusercontent.com/51681379/106603467-fd8edd00-6566-11eb-8f17-4aa63c8bec7a.png)
![image](https://user-images.githubusercontent.com/51681379/106603746-61b1a100-6567-11eb-8b44-1891480997c0.png)


Did you try to install the Composer update [plugin](https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html#prerequisites) to resolve conflicts?

**Comment by bagbarn** [comment] 2021-02-02 13:46
thanks for the help,  I have not installed the Composer update plug in and will install it before attempting again

    On Tuesday, February 2, 2021, 8:00:54 AM EST, Vasyl Shvorak <notifications@github.com> wrote:  
 
 


Hi @bagbarn thank you for your report, I'm not able to reproduce issue by steps you described.
Result:
 ✔️ composer update is end without errors while upgrading from 2.4.0 to 2.4.1 on php7.3



Did you try to install the Composer update plugin to resolve conflicts?

**Comment by engcom-Delta** [comment] 2021-02-26 08:45
@bagbarn Is this issue still actual on the latest magento version 2.4.2?

**Comment by bagbarn** [comment] 2021-02-26 15:22
I am still trying to upgrade from 2.4.0.  The dependency issue with Magento inventory modules prevents me from upgrading via composer modules from outside vendors.  Have not yet tried the composer upgrade to 2.4.2 yet but will try over the weekend and update the modules after upgrading.  

 When attempting to upgrade to 2.4.1 we did use php7.3 in order to install elasticsearch but 7.4 is the default php version.

    On Friday, February 26, 2021, 3:45:48 AM EST, Vasyl Shvorak <notifications@github.com> wrote:  
 
 


@bagbarn Is this issue still actual on the latest magento version 2.4.2?

**Comment by iphigenie** [comment] 2021-05-05 11:48
Hi @bagbarn 

It's been a while since I updated to 2.4.1 but I think magento/inventory-composer-metapackage was retired, possibly even before 2.4 and is a remnant that should be gone - that it is still around is your issue.

Have you tried running --with-all-dependencies before even upgrading to 2.4.1 and then during the upgrade as that might help clean things up

**Comment by engcom-Bravo** [comment] 2021-06-15 12:23
Hi @bagbarn ,

Please let us know if in case you are still facing the issue after trying the possible solutions in this thread.

**Comment by engcom-Bravo** [comment] 2021-06-29 13:02
Hi @bagbarn ,

As we have not heard from you since few days on our last comment, we are closing this ticket. Please raise a new ticket if the issue still exists.

Thanks

**Closed as completed by engcom-Bravo** 2021-06-29 13:02 UTC
Labels: Triage: Dev.Experience, Issue: needs update

**Comment by bagbarn** [comment] 2021-06-29 13:42
Adobe is a great marketing tool for their competitors.   We are leaving the Magento Platform asap
    On Tuesday, June 29, 2021, 06:02:44 AM MST, Keerthana SL ***@***.***> wrote:  
 
 


Hi @bagbarn ,

As we have not heard from you since few days on our last comment, we are closing this ticket. Please raise a new ticket if the issue still exists.

Thanks
