### ISSUE TITLE
module:uninstall get stuck on removing code from Magento codebase

### ISSUE THREAD

**Issue by nickbartlett** [magento/magento2#9848] opened 2017-06-05 15:19 UTC
Module will not uninstall completely

### Preconditions
Magento version 2.1.5
PHP 5.6.30
MySQL: Server version: 5.7.17-11 Percona Server

### Steps to reproduce
1. Install module via composer successfully.
2.  Run magento/bin module:uninstall "my/module"

### Expected result
1. Module and dependencies should be removed including database and code

### Actual result
Uninstalling a module will remove the entry from composer.json, and run the database uninstall scripts, but when it attempts to remove the code it hangs with message "removing code from Magento codebase:" . One thing to note is our module has its own composer.json file where it requires and installed another codebase.  The module is being installed from our own satis server . 

vendor/magento/framework/Composer/Remove.php, Magento tries to run 'remove' composer command.
runComposerCommand() method can be found here: vendor/magento/composer/src/MagentoComposerApplication.php
it gets stuck on line $exitCode = $this->consoleApplication->run($input, $this->consoleOutput);

FYI manually executing the command "composer remove my/module" works successfully.

**Comment by hostep** [comment] 2017-06-05 20:43
This is most likely a duplicate of: https://github.com/magento/magento2/issues/5797

**Comment by Brigel** [comment] 2017-09-14 06:49
Composer stoped in load data from repo.magento.com

My auth.json was not correct. This decision helped me

`config http-basic.repo.magento.com <public_key> <private_key>`
https://magento.stackexchange.com/questions/90983/how-to-use-the-new-repo-magento-com

**Comment by magento-engcom-team** [comment] 2017-09-25 11:19
@nickbartlett, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more details in steps to reproduce, or try to reproduce this issue on a clean installation or latest release.

**Comment by nickbartlett** [comment] 2017-10-05 14:39
OK, we will test it again shortly.  Please do not close this issue.

**Comment by magento-engcom-team** [comment] 2017-10-11 16:39
@nickbartlett we are closing this issue for now. If you'd like to update it, please reopen the issue any time

**Closed as completed by magento-engcom-team** 2017-10-11 16:39 UTC
Labels: bug report, Issue: Clear Description, Issue: Format is valid
