### ISSUE TITLE
Products are not displaying infront end after updating product via importing CSV.

### ISSUE THREAD

**Issue by Sathishkumar8731** [magento/magento2#25540] opened 2019-11-09 11:38 UTC
### Preconditions (*)

1. Magento 2.3.0 & 2.3-develop
2. MYSQL 5.6
3. PHP 7.2.X

### Steps to reproduce (*)

1. Creating a new product (simple product and bundle product) in the admin panel
![image](https://user-images.githubusercontent.com/51680850/68661166-26324d80-0543-11ea-93e7-58a755a6de61.png)
2. Go to System -> Data Transfer -> Export and export it.
3. Open the exported CSV file and update/change the price or any attribute value in it( in my case: change weight and price of simple product)
4. Now, go to Sytem -> Data Transfer -> Import and Imported Successfully.
![image](https://user-images.githubusercontent.com/51680850/68661402-8f19c580-0543-11ea-9349-3d1b214108c8.png)
![image](https://user-images.githubusercontent.com/51680850/68661416-950fa680-0543-11ea-875b-efd9cf7f0f5f.png)
5. Check products in front end 

### Expected result (*)

1. When we importing CSV to update the product values, then the products should be visible in front end of the website. 

### Actual result (*)

1. Bundle product not visible in front end
![image](https://user-images.githubusercontent.com/51680850/68661741-1b2bed00-0544-11ea-8f0a-27e5ca33b65b.png)
2. Now, it is showing " out of stock" in bundle product page.
![image](https://user-images.githubusercontent.com/51680850/68661907-6d6d0e00-0544-11ea-8acf-327663695ec3.png)
3. After some time all products were not visible

**Comment by ajijshekh123** [comment] 2019-11-11 05:55
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-11 05:55
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-11 05:56
Hi @ajijshekh123, here is your [Magento instance](https://i-25540-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25540-2-3-develop.instances.magento-community.engineering/admin](https://i-25540-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2019-11-11 06:35
We can't able to upload the CSV file because of the Cron job. We need developers to help to verify the issue.

**Comment by magento-engcom-team** [comment] 2019-11-12 10:04
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-23028` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2020-03-25 17:30
Hi @Sathishkumar8731. Thank you for your report. 
The issue has been fixed in magento/magento2#25664 by @p-bystritsky in 2.4-develop branch
Related commit(s):
 - [f96d993184b3aea5512a2c4976f459e712cc14f4](https://github.com/magento/magento2/commit/f96d993184b3aea5512a2c4976f459e712cc14f4)
 - [1dd81a4d7d7b4e8f6d8c8063f5467c4904b4372b](https://github.com/magento/magento2/commit/1dd81a4d7d7b4e8f6d8c8063f5467c4904b4372b)
 - [6ad372ae3768d10a77810bce9bf2eeb8a5ea01d2](https://github.com/magento/magento2/commit/6ad372ae3768d10a77810bce9bf2eeb8a5ea01d2)
 - [a070cf368ed4b19c5e63b4453d9af2d72451901e](https://github.com/magento/magento2/commit/a070cf368ed4b19c5e63b4453d9af2d72451901e)
 - [143bd5b5bce5284d53a5e13f6a3b0863f6a2c66b](https://github.com/magento/magento2/commit/143bd5b5bce5284d53a5e13f6a3b0863f6a2c66b)

The fix will be available with the upcoming 2.4.0 release.

**Closed as completed by magento-engcom-team** 2020-03-25 17:30 UTC
Labels: Issue: Ready for Work, Component: ImportExport, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Bundle, Fixed in 2.4.x, Progress: done
