### ISSUE TITLE
[ CE 2.0.7 ] - Cancel order with Bundle product

### ISSUE THREAD

**Issue by mhabou** [magento/magento2#5086] opened 2016-06-17 13:32 UTC
## Preconditions
1. Install Magento 2.0.7

## Steps to reproduce
1. Add bundle Product to the cart.
2. Place the order
3. Cancel the order
## Expected result
1. In the table sales_order_item .. the qty_canceled must changed
## Actual result
1. In the table sales_order_item qty_canceled still 0

**Comment by Mulderua** [comment] 2016-06-21 16:08
Hi @Dayssam !
Internal ticket MAGETWO-54626 was created.
Thank you for the report.

**Comment by magento-engcom-team** [comment] 2017-10-03 06:30
@Dayssam, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-03 06:30 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
