### ISSUE TITLE
Checkout Default Shipping and Billing Address

### ISSUE THREAD

**Issue by rishabhrkrai** [magento/magento2#10599] opened 2017-08-21 10:43 UTC
### Preconditions

1. Magento 2.1.7, PHP 7.0, MySQL 5.7
2. Nginx Sever

### Steps to reproduce

1. Login to the store
2. Go to My Account
3. Click On Address Book
4. Now click on **Change Shipping Address** link

### Expected result

1. Only Shipping Address would be changed

### Actual result

1. Shipping and Billing address both are changed

**Comment by rishabhrkrai** [comment] 2017-08-21 10:43
In the Address Book section, if I've only entered one address, it shows that same address as your billing and shipping address. If you click 'change address' under the shipping address, it actually edits the billing address too.

If I have multiple addresses. If I want to change your shipping address to one in the lower section your instinct is to click the **change shipping address** link under the current shipping address. What I really want to do is click 'edit' on the address in the lower section and tick the box to mark it as the shipping address.

**Comment by magento-engcom-team** [comment] 2017-09-13 15:35
@RishabhRkRai  If you want get cleared object from repository, you should use forceReload. 
For instance: $productRepository->getById(PRODUCT_ID, false, null, true);
This issue is already fixed in Magento 2.1.8

**Comment by magento-engcom-team** [comment] 2017-09-14 15:06
@RishabhRkRai  Thank you for your submission.
Unfortuanlly, the issue you described is standart functionality behavior.
If you want to make Feature Requests and Improvements, please submit them to the new Magento 2 Feature Requests and Improvements forum (see details here).

**Closed as completed by magento-engcom-team** 2017-09-14 15:06 UTC
Labels: Issue: Format is valid

**Comment by korostii** [comment] 2017-09-16 11:18
This is actually a duplicate of #10556.
