### ISSUE TITLE
Mage 2.4.4 Admin Grid Filter/Search not visible

### ISSUE THREAD

**Issue by vandijkstef** [magento/magento2#35781] opened 2022-07-19 09:08 UTC
### Preconditions and environment

- Magento 2.4.4 - Updated from Magento 2.4.3-p1

### Steps to reproduce

Just ran the update

### Expected result

Having filter/search on order/product grid available/visible

### Actual result

The search/filter options are not visible. It did however kept the old filter state, indicating the back-end of it is still working

### Additional information

I updated through composer. Nothing is popping up in any of the logs. Got the issue on both develop system (& mode) and production. It feels as if the template block is not being properly injected, as old filter-states are still there. The old filter state cannot be 'cleared', this is also not available. Search in the top-right (next to the account icon) is working as it should. Issue isn't on 2.4.3-p2. Did reset to the default admin theme, did not fix it either.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by vandijkstef** [comment] 2022-07-19 09:29
2.4.3-p1
![Schermafbeelding 2022-07-19 om 11 10 50](https://user-images.githubusercontent.com/5433241/179717465-2872d6af-9a66-4287-97c3-2d321145410a.png)

2.4.4
![Schermafbeelding 2022-07-19 om 11 28 50](https://user-images.githubusercontent.com/5433241/179717513-8dad306d-e8d1-4e86-9b53-a0e1f146e9b0.png)

**Comment by engcom-November** [comment] 2022-07-19 12:11
Hi @vandijkstef ,
Thank you for reporting and collaboration. Verified the issue by upgrading from 2.4.3-P1 to 2.4.4 with below steps but couldn't reproduce the issue.
**Steps performed:**
1. Installed 2.4.3-P1 project-community-edition with PHP 7.4 active
2. Created few products and orders in the instance
3. Upgraded to 2.4.4 Project-community-edition using ref upgrade [guide](https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/implementation/perform-upgrade.html)
4. Switched to PHP 8.1 as it is the supported version for magento 2.4.4.
5. Login to admin - Verified filters in Products page and Orders page - No issue. Filter are displayed as expected.
Kindly check the system [requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) or any 3rd party extensions / modules enabled and elaborate the missing steps if any if the issue is still reproducible.
Thank you.
![image](https://user-images.githubusercontent.com/60198231/179747200-1bc76b62-fbdf-4e83-8ab6-1c7fa232e7b6.png)

**Comment by vandijkstef** [comment] 2022-07-19 15:07
- Switched to PHP8.1 (missed that, thanks!) -> Did not resolve
- Cleared ALL modules in composer and app/code directory -> It did resolve

Going to add everything back in one-by-one and report back here once I got a better idea what is doing this

**Comment by vandijkstef** [comment] 2022-07-19 17:22
@engcom-November Thanks again for giving me pointers. I found the module that is creating this behaviour (see mentioned issue in the thread here).

**Comment by engcom-November** [comment] 2022-07-20 09:44
Hi @vandijkstef ,
Thank you for the response. TIG_GLS is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.

**Closed as completed by engcom-November** 2022-07-20 09:44 UTC
Labels: Component: Bundled Extension, Issue: needs update
