### ISSUE TITLE
Coupon code is not valid error when using REST API - Magento CE 2.17, 2.1.8 2.1.9

### ISSUE THREAD

**Issue by coleHafner** [magento/magento2#11259] opened 2017-10-05 18:59 UTC
### Summary
When applying a coupon code to a qualifying cart (ie cart that has the items in it to which the specific coupon code applies), the coupon code is denied. The system returns a 500 error "Coupon code is not valid". 

### Preconditions
1. Magento Open Source version 2.1.9 (also experienced this error on 2.1.7 and 2.1.8) - No plugins/modules enabled.
2. Ubuntu version 14.04.5
3. Nginx version 1.10.2
4. PHP version 7.0.14
5. Mysql version 14.14

### Steps to reproduce

1. Create a new guest cart `POST: https://domain.com/V1/guest-carts`
2. Add item(s) to cart `POST: https://domain.com/V1/guest-carts/<cart id>/items`
3. Apply discount code: `PUT: https://domain.com/V1/guest-carts/<cart id>/coupons/<coupon code>`

### Expected result
1. 200 response. Discount should be applied to the cart totals.

### Actual result
1. 500 response. "Coupon code is not valid" message returned. 

I've tracked this down to the [CouponManagment class](https://github.com/magento/magento2/blob/9c14af7a97bcf338662de365d2613c7ca9dbf8c6/app/code/Magento/Quote/Model/CouponManagement.php#L62) When it saves the quote, the coupon code disappears. It has to be something with the cart rules not being properly recognized for the products in the cart.

**Here is my cart rule**
Websites: Main Website
Customer Groups: All
Coupon: Specific Coupon
Coupon Code: <set>
Uses per Coupon: 500
From: 9/17/17
To: 10/10/17

Conditions: All products

_Actions_
Apply: Percent of product price discount
Discount Amount: 5.236
Maximum Qty: 10
Discount Qty Step: 0
Apply to Shipping: No
Discard subsequent rules: No
Free Shipping: No

Apply the rule when...
If ALL of these conditions are TRUE:
Category is one of 4, 36, 37, 39, 40, 41, 135

I know this has something to do with the category structure because when I simply remove/add one of the eligible categories to the product, it works just fine. Perhaps the category structure itself is breaking the rule?

| Default Category
| -- Category 1
| -- Parent Category
| --- Child Category 1
| --- Child Category 2
| --- Child Category 3

All items have Child Category 1, 2, or 3 applied. Like I said, when I add (or remove) Parent category, the rule applies just fine.

**Comment by magento-engcom-team** [comment] 2017-10-06 10:22
@coleHafner Thanks for reporting this issue. 
Unfortunately, I could not reproduce the issue as you described it.
Steps I did:
1. Create Categories:
![categoriees](https://user-images.githubusercontent.com/31669971/31273758-ba2a1926-aa98-11e7-8aeb-320587a7011d.png)
2. Create simple product "s1" and assign it to category Child Category 1
3. Create Cart Price Rule with coupon = 'test' and conditions in actions:
![rule conditions](https://user-images.githubusercontent.com/31669971/31273770-c3d5720e-aa98-11e7-8be0-12d248063025.png)
4. Make requests:
- http://magentoHost/rest/v1/guest-carts (returns cartId),
- http://magentoHost/rest/v1/guest-carts/cartId/items with body:
```
 {
   "cartItem": {
     "sku": "s1",
     "qty": 1,
     "name": "s1",
     "product_type": "simple",
     "quote_id": "cartId"
    }
 }
```
-  http://magentoHost/rest/v1/guest-carts/cartId/coupons/test 

 Result: coupon was applied without errors.
Please add more details to your description of the steps you followed when identifying this issue. Screenshots or logs would be helpful, too.

**Comment by coleHafner** [comment] 2017-10-12 01:05
Thank you for your response. The only additional details I can give is that the parent category was part of the cart rule as well as the child categories. I don't think that would make a difference, but maybe.

**Comment by magento-engcom-team** [comment] 2017-10-13 07:34
@coleHafner Thanks for the feedback.
Did with parent category as a part of the cart rule.
![screenshot_1](https://user-images.githubusercontent.com/31669971/31534863-68dedc14-b001-11e7-82ce-0357757a4f55.png)
Unfortunately still can't reproduce this issue. Coupon applied successfully. 
If You can provide additional details, feel free to post it here, so we can try to reproduce this issue with new details.

**Comment by magento-engcom-team** [comment] 2017-10-24 02:30
@coleHafner we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Closed as completed by magento-engcom-team** 2017-10-24 02:30 UTC
Labels: Progress: needs update, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid

**Comment by tuyennn** [comment] 2018-05-02 07:15
This one related to  Coupon API not working for guest user #14056
