### ISSUE TITLE
The value specified in the URL Key field would generate a URL that already exists

### ISSUE THREAD

**Issue by carlitooo2022** [magento/magento2#35888] opened 2022-08-08 03:42 UTC
### Preconditions and environment

Magento ver. 2.4.0

### Steps to reproduce

1. Go to Systems tab and click Import
2. In Entity type, select Products
3. Import behavior, select Add/Update
4. Validation Strategy, select Stop on error
5. Allowed error counts - 10
6. Select file to import and on the top right corner select Check Data
7. Click import

### Expected result

Be able to import the csv files for price update

### Actual result

Imported resource (image) could not be downloaded from external resource due to timeout or access permissions in row(s): 95, 96, 121, 123, 124, 125
General system exception happened
Additional data:
The value specified in the URL Key field would generate a URL that already exists.
To resolve this conflict, you can either change the value of the URL Key field (located in the Search Engine Optimization section) to a unique value, or change the Request Path fields in all locations listed below:

- [hana-tpu-jelly-case-apple-iphone-11-pro-5-8-red.html](https://xtremeonline.com.au/administrator/admin/url_rewrite/edit/id/45199/key/ff6e51433665093adff3bed7a7c0059466c263f70296585c1e6c84db51cfb8e7/)

- [iface-hard-case-iphone-11-pro-5-8-white.html](https://xtremeonline.com.au/administrator/admin/url_rewrite/edit/id/85233/key/ff6e51433665093adff3bed7a7c0059466c263f70296585c1e6c84db51cfb8e7/)

products up to 500+

### Additional information

Need help on how to fix this pls since it has a lot of products that needs to be updated or fixed

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-08-08 08:55
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-08-08 11:58
Hi @carlitooo2022,

Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue. Kindly refer the screenshots.

steps followed:
1.Go to Systems tab and click Import
2.In Entity type, select Products
3.Import behavior, select Add/Update
4.Validation Strategy, select Stop on error
5.Allowed error counts - 10
6.Select file to import and on the top right corner select Check Data
7.Click import

Product Prices without import

<img width="930" alt="123" src="https://user-images.githubusercontent.com/51680745/183412399-628d6935-fd02-4d04-b309-82dacf0d2836.png">


Product Prices after Importing

<img width="924" alt="124" src="https://user-images.githubusercontent.com/51680745/183412502-6f9d3f4d-558f-4dce-a867-c4d780f02cc8.png">


CSV file

[URL KEY.csv](https://github.com/magento/magento2/files/9281477/URL.KEY.csv)


Let us know in case we have missed anything.


Thanks.

**Comment by engcom-Bravo** [comment] 2022-08-09 08:44
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-08-09 12:16
Hi @carlitooo2022,

we are tried about 500+ products to update product price. we are able to update the product price of 500+ products.

we are unable to reproduce the issue. Verified the issue on Magento 2.4-develop branch. Kindly refer the screenshots.

<img width="930" alt="products 1" src="https://user-images.githubusercontent.com/51680745/183643471-f06fee1d-f8a6-4bdb-ae38-dd7107673408.png">


<img width="919" alt="products 2" src="https://user-images.githubusercontent.com/51680745/183643606-079eab1d-3e0f-4e38-bcdc-0b1b8e01a408.png">




500+ Products CSV File
[500 Products.csv](https://github.com/magento/magento2/files/9290217/500.Products.csv)



Please check your CSV File and also check the images that are added to the product.


Let us know in case we have missed anything.


Thanks.

**Comment by engcom-Bravo** [comment] 2022-08-23 05:16
Hi @carlitooo2022,


We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-08-23 05:16 UTC
Labels: Issue: needs update, Reported on 2.4.0

**Comment by DutchPrince** [comment] 2024-01-26 11:04
Same issue here
