### ISSUE TITLE
[2.0.8] Authorize.net payment checkout PHP Fatal error

### ISSUE THREAD

**Issue by Hawk30100** [magento/magento2#5969] opened 2016-08-03 17:44 UTC
When trying to "place order" with standard Magento built-in authorize.net payment option, nothing happens and PHP fatal error occures.

We had this problem with version 2.0.7 and updated to 2.0.8 in hope that this solves the problem, but it didn't.
### Preconditions
1. Magento CE 2.0.8
2. PHP 7.0.6
### Steps to reproduce
1. Install Magento CE 2.0.8
2. Setup authorize.net payment
3. Add product to Bag, go to checkout and click on "place order"
### Expected result
1. Credit card payment (/checkout) should be processed
### Actual result
1. Nothing happens, PHP error occures
   Internet browser developer tools shows:
   ![](https://abload.de/img/error91ucd.png)

PHP error log:
`[03-Aug-2016 16:22:29 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getAgreementIds() on null in /chroot/home/hg/hg.com/html/vendor/magento/module-checkout-agreements/Model/Checkout/Plugin/Validation.php:81
Stack trace:
#0 [internal function]: Magento\CheckoutAgreements\Model\Checkout\Plugin\Validation->beforeSavePaymentInformation(Object(Magento\Checkout\Model\PaymentInformationManagement\Interceptor), 177, Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))
#1 /chroot/home/hg/hg.com/html/vendor/magento/framework/Interception/Interceptor.php(121): call_user_func_array(Array, Array)
#2 /chroot/home/hg/hg.com/html/var/generation/Magento/Checkout/Model/PaymentInformationManagement/Interceptor.php(39): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)
#3 [internal function]: Magento\Checkout\Model\PaymentInformationManagement\Interceptor->savePaymentInformation(177, Object(Magento\Quote\Model\Quote\Pa in /chroot/home/hg/hg.com/html/vendor/magento/module-checkout-agreements/Model/Checkout/Plugin/Validation.php on line 81

`

**Comment by YevSent** [comment] 2016-08-04 07:31
Hi, @Hawk30100, could you disable `Terms and conditions` option in the `Checkout Options` configuration and try to repeat your steps again?

**Comment by Hawk30100** [comment] 2016-08-04 12:40
Hello @joni-jones, disabling the Terms and Conditions solves the problem. But it looks like this is only a workaround :-/

**Comment by SerhiyShkolyarenko** [comment] 2016-09-07 13:27
Hi @Hawk30100!
I didn't manage to reproduce this issue on the latest develop branch. Is it still reproducible for you on 2.1.1 or 2.0.9?

**Comment by SerhiyShkolyarenko** [comment] 2016-09-28 08:44
Rechecked on 2.0.9 and didn't reproduce the issue with enabled checkout agreements.
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue on 2.0.9, please describe the steps from clean install.

**Closed as completed by SerhiyShkolyarenko** 2016-09-28 08:44 UTC
Labels: bug report, Component: Checkout

**Comment by Hawk30100** [comment] 2016-09-28 14:01
I just installed a fresh Magento 2.1.1 installation in our development environment and it seems like the problem does not excist any longer.

**Comment by SerhiyShkolyarenko** [comment] 2016-09-29 12:52
thank you for update.

**Comment by versdivers** [comment] 2016-10-03 15:52
I'm still having this issue with 2.0.9. I can not update further at this point because its a live website.
Anyone fixed this?

**Comment by SerhiyShkolyarenko** [comment] 2016-10-04 14:01
@versdivers we could fix it if it were reproducible for us. Could you please create a new issue with described steps from **clean 2.0.9 installation**?

**Comment by versdivers** [comment] 2016-10-04 14:10
At this point i am checking with some module creators if the problem is not because i use custom adres fields. I will come back with more explanation
