### ISSUE TITLE
Updating a CMS block does not update the 'Updated time' column

### ISSUE THREAD

**Issue by thlassche** [magento/magento2#13969] opened 2018-03-06 15:03 UTC
### Preconditions
1. Magento version >= 2.2 

### Steps to reproduce
1. Update a CMS block (e.g. change the title)

### Expected result
1. Looking at CMS block grid, the updated time column is changed

### Actual result
1. Looking at CMS block grid, the updated time column is not changed

**Comment by magento-engcom-team** [comment] 2018-03-06 15:30
@thlassche, thank you for your report.
The issue is already fixed in 2.3.0
But we will consider to backport the fix to patch releases

**Comment by osrecio** [comment] 2018-03-07 08:55
Hi @thlassche ,

This Issue was resolved with this PR: https://github.com/magento/magento2/pull/12636

In next update 2.2.x will be added.

I close this Issue, feel free to reopen

**Closed as completed by osrecio** 2018-03-07 08:55 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Fixed in 2.3.x, Issue: Format is valid
