### ISSUE TITLE
[Issue][MFTF] extends tests from Magento Enterprise

### ISSUE THREAD

**Issue by Usik2203** [magento/magento2#34825] opened 2021-12-16 11:08 UTC
### Preconditions (*)

While running `AdminLoginSuccessfulTest` for Magento Commerce  i see next mesage

<img width="1283" alt="Screenshot 2021-12-16 at 13 04 59" src="https://user-images.githubusercontent.com/13517181/146360593-45695921-67b5-407a-9537-df3aa9dc04b0.png">

### Steps to reproduce (*)

1. Run `./vendor/bin/mftf run:test AdminLoginSuccessfulTest --remove`
2. See `dev/tests/acceptance/mftf.log`

### Expected result (*)

1. `AwsS3CheckingRMAPrintTest` ,` AwsS3UpdateImageFileCustomerAttributeTest ` moved to https://github.com/magento/partners-magento2ee repository 
2. I don't see mentioned Errors if i run `AdminLoginSuccessfulTest` for Magento Commerce 

### Actual result (*)

<pre>
[2021-12-16T10:38:55.429259+00:00] Magento\FunctionalTestingFramework\Test\Handlers\TestObjectHandler.ERROR: Line 43: Test CheckingRMAPrintTest not defined in xml. [] []
[2021-12-16T10:38:55.429501+00:00] Magento\FunctionalTestingFramework\Test\Handlers\TestObjectHandler.ERROR: Line 43: Test UpdateImageFileCustomerAttributeTest not defined in xml. [] []
[2021-12-16T10:38:55.433882+00:00] Magento\FunctionalTestingFramework\Test\Handlers\TestObjectHandler.ERROR: Line 43: Test CheckingRMAPrintTest not defined in xml. [] []
[2021-12-16T10:38:55.433950+00:00] Magento\FunctionalTestingFramework\Test\Handlers\TestObjectHandler.ERROR: Line 43: Test UpdateImageFileCustomerAttributeTest not defined in xml. [] []
</pre>

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2021-12-27 12:23
Hello @Usik2203,

We have tried to reproduce the issue in Magento EE with the mentioned steps. But the issue is not reproducible for us.

I have attached the `mftf.log` file for reference;

[mftf.log](https://github.com/magento/magento2/files/7780124/mftf.log)

Please let us know if we missed anything in order to reproduce the issue.

Thanks

**Comment by engcom-Hotel** [comment] 2022-01-10 05:53
Dear @Usik2203,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-01-10 05:53 UTC
Labels: Issue: needs update
