### ISSUE TITLE
Autoselect of swatch options not working for dropdown attributes

### ISSUE THREAD

**Issue by designhunger** [magento/magento2#4337] opened 2016-04-28 11:50 UTC
## Steps to reproduce
1. Create a configurable product with a dropdown product attribute (f.ex. size)
2. Visit product page with following syntax to preselect the attributes:
   http://myshop.com/productname.html?size=6
## Expected result

The size with the option-id of 6 should be selected for the size attribute.
## Actual result

The option is not selected if the attribute is a dropdown. Only visual and text swatches are selected.
## Solution

The js file should differentiate between clickable attributes like swatches and dropdowns. Therefor the find statements should be altered in the _EmulateSelected function.

/module-swatches/view/frontend/web/js/SwatchRenderer.js

```
    /**
     * Emulate mouse click on all swatches that should be selected
     *
     * @private
     */
    _EmulateSelected: function () {
        var $widget = this,
            $this = $widget.element,
            request = $.parseParams(window.location.search.substring(1));

        $.each(request, function (key, value) {

            $this.find('.' + $widget.options.classes.attributeClass
                + '[attribute-code="' + key + '"] .swatch-select').val(value).change();


            $this.find('.' + $widget.options.classes.attributeClass
                + '[attribute-code="' + key + '"] .swatch-option[option-id="' + value + '"]').trigger('click');


        });
    },
```

**Comment by piotrekkaminski** [comment] 2016-05-13 00:03
Internal issue MAGETWO-52776

**Comment by sammarcus** [comment] 2016-10-19 06:24
I didn't even know you could do that with swatches. Is this url syntax formally documented anywhere?

**Comment by designhunger** [comment] 2016-10-19 06:35
In Magento 1.9 this was already featured. I have not found any docs for Magento 2, but found it while crawling through the codebase.

**Comment by sammarcus** [comment] 2016-11-02 08:11
Interesting. I haven't been able to get it working so am curious if that functionality is even maintained anymore.

**Comment by veloraven** [comment] 2017-06-19 16:15
Internal ticket was closed as not a bug.
You can submit to [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)) if you think it should be implemented.
Closed.

**Closed as completed by veloraven** 2017-06-19 16:15 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog
