### ISSUE TITLE
URL Key already exist error coming if we give same name for two products.

### ISSUE THREAD

**Issue by i95devdivya** [magento/magento2#21860] opened 2019-03-20 14:45 UTC
Preconditions

1.      Magento EE 2.2.6

2.      PHP 7.1

Steps to reproduce

1. Create a Product from Magento Admin and set visibility to catalog & search or catalog or search.

3. Create another product with same name. And select visibility catalog & search or catalog or search.

Expected result

1. If product has same name, URL key should modify like SKU

Actual result

1. Same URL key is taking for both products and throwing error.

Screen-cast

https://www.screencast.com/t/2Ih5PeNHcum

**Comment by magento-engcom-team** [comment] 2019-03-20 14:45
Hi @i95devdivya. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@i95devdivya do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-03-20 15:35
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment] 2019-03-20 15:42
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-20 15:42
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-20 15:43
Hi @shikhamis11, here is your [Magento instance](https://i-21860-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21860-2-3-develop.instances.magento-community.engineering/admin](https://i-21860-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2019-03-20 15:47
@i95devdivya this issue is also coming in community versions.

**Comment by magento-engcom-team** [comment] 2019-03-20 15:49
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98807`, `MAGETWO-98808` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hostep** [comment] 2019-03-20 17:01
I don't think this is a valid bug report, it is expected that you get an error and you should then manually modify the url key so it becomes unique, no?
(Hope I understood the issue correctly because I can't view the screencast, needs Flash Player, is that still a thing these days?)

**Comment by shikhamis11** [comment] 2019-03-21 01:04
@hostep most of the merchants don't fill the url key manually while creating products and this is very common to have same name while creating product so in my opinion the behavior should be similar like skus.

**Comment by hostep** [comment] 2019-03-21 08:20
Hmm, I wasn't even aware of this SKU auto-generation. But I just tested and you are right, it automatically changes. This feels really strange though, the SKU field is such and important field, and then Magento auto generates some value to avoid conflicts with existing SKU's. Not sure if that is right.

But I can see the point that it is convenient to auto generate url keys so they are unique. I think url keys are important as well, but maybe most people consider it less important then myself. And it also gets auto generated when duplicating products, so then ok, maybe this is a valid issue.

**Comment by yvechirko** [comment] 2019-03-28 10:44
If I've I understood it correctly it is needed to add auto-generated new unique URL, when a product is created, instead of displaying the error message, isn't it?

**Comment by shikhamis11** [comment] 2019-03-28 10:54
@yvechirko yes it should

**Comment by magento-engcom-team** [comment] 2019-03-28 11:51
Hi @AlexandrKozyr. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by orlangur** [comment] 2019-04-01 09:41
There is nothing to fix here, this is intended behavior. Unlike Magento 1 we give full control over SEO for merchants in Magento 2, thus we do not encourage random numeric suffixes appearing.

**Closed as completed by orlangur** 2019-04-01 09:41 UTC
Labels: Issue: Ready for Work, Component: Catalog, Component: CatalogUrlRewrite, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid
