### ISSUE TITLE
Authorize.net payment failed issues

### ISSUE THREAD

**Issue by twistedindustries** [magento/magento2#7854] opened 2016-12-16 18:22 UTC
Preconditions
1. Magento CE 2.1.3
2. PHP 7.0.14
3. MySQL 5.6.30

Steps to reproduce
1.  Create a simple product
2.  Setup Authorize.net sandbox account and insert all required info
3.  Add product to cart, and checkout using zip code 46282 [https://developer.authorize.net/hello_world/testing_guide/] so that it generates a fail.
4.  The page will reload, and youll get a brief error message.  Now click the logo to return to the homepage.

Expected result
1. The mini cart should show 1 product and doesn't.  

Actual result
1. Mini cart shows empty.
![screen shot 2016-12-16 at 10 13 34 am](https://cloud.githubusercontent.com/assets/5498323/21273409/58985720-c378-11e6-8e3f-e41cb6fa40c8.png)

If you navigate to /checkout/cart, the cart is in fact not empty 
![screen shot 2016-12-16 at 10 16 58 am](https://cloud.githubusercontent.com/assets/5498323/21273525/cfa61988-c378-11e6-8e26-4c9bef612e50.png)

I've tested this with braintree payment and it works as expected telling me that it is specific to the authorize.net payment module.  Ill be looking for a fix in the meantime.

Additional note:  for each failed payment on authorize.net there is a cancelled order.  This isn't the case with failed payments when using braintree.   Thinking this is a clue.

**Comment by dyushkin** [comment] 2016-12-27 13:04
Hi @twistedindustries! Please provide specific settings of your auth.net sandbox account fraud filters, so that we can test this issue properly.

**Comment by twistedindustries** [comment] 2016-12-27 21:20
@dyushkin My settings shouldn't matter since I am using Zip code: 46282 it will decline all transactions per the instructions [here](https://developer.authorize.net/hello_world/testing_guide/)

Here are some screenshots anyway:
![image](https://cloud.githubusercontent.com/assets/5498323/21508598/23695e42-cc37-11e6-9010-5d86154ea3d5.png)
![image](https://cloud.githubusercontent.com/assets/5498323/21508605/340add16-cc37-11e6-8fcd-771ec28aa97d.png)
![image](https://cloud.githubusercontent.com/assets/5498323/21508611/3d2d3524-cc37-11e6-8ffa-62dbad62c25e.png)
![image](https://cloud.githubusercontent.com/assets/5498323/21508615/44b7e2ee-cc37-11e6-9e53-a0a2a3e8e111.png)

**Comment by dyushkin** [comment] 2016-12-28 14:31
@twistedindustries, thank you for reporting. Internal ticket MAGETWO-62739 was created to investigate and fix this problem.

**Comment by magento-engcom-team** [comment] 2017-10-19 14:30
@twistedindustries, thank you for your report.
We've created internal ticket(s) MAGETWO-62739 to track progress on the issue.

**Comment by Ctucker9233** [comment] 2017-12-08 21:32
@magento-engcom-team Any idea when a fix will be available for 2.1?

**Comment by engcom-Echo** [comment] 2019-12-09 13:53
Hello All

Thank you for your report and collaboration!
I am not able to reproduce this issue on the 2.4-develop branch by provided steps.

**Testing scenario:**
**Steps to reproduce**

1. Create a simple product
2. Setup Authorize.net sandbox account and insert all required info
3. Add product to cart, and checkout using zip code 46282 [https://developer.authorize.net/hello_world/testing_guide/] so that it generates a fail.
4. Click on the "Next" button
5. Enter Credit Card data
6. Click on the "Place Order" button
7. The page will reload, and youll get a brief error message.
8. Now click the logo to return to the homepage.

**Result**
Mini cart is not empty
![Screenshot from 2019-12-09 15-39-27](https://user-images.githubusercontent.com/51681435/70440807-aa70e580-1a9b-11ea-8c74-b1e8da15c154.png)
If navigate to /checkout/cart, the cart is not empty
![Screenshot from 2019-12-09 15-50-34](https://user-images.githubusercontent.com/51681435/70440883-e015ce80-1a9b-11ea-877b-c740cb3eaaf8.png)

So I have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Echo** 2019-12-09 13:53 UTC
Labels: bug report, Component: Payment, Component: Checkout, Issue: Clear Description, Issue: Format is valid
