### ISSUE TITLE
Error in checkout if customer has no default shipping address and multiple addresses

### ISSUE THREAD

**Issue by matin73** [magento/magento2#24131] opened 2019-08-14 08:37 UTC
### Preconditions (*)

1. Magento 2.2.9

### Steps to reproduce (*)

1. Add customer account and add minimum 2 address. DO NOT add default shipping address or DISABLE default shipping address in admin for customer (s. screenshot)
2. Login in shop and add some items to cart.
3. Go to checkout

- [ ] 

### Expected result (*)

1. Checkout page loading correct

### Actual result (*)

1. Checkout page loading with js error:
Firefox-Developer Konsole:
TypeError: quote.shippingAddress(...) is null

In Chrome:
Uncaught TypeError: Cannot read property 'getCacheKey' of null
     at UiClass.eval (eval at require.load (802c412263e2545cb95c8338f928c940.min.js:173), <anonymous>:3:1943)
     at Function.notifySubscribers (eval at require.load (802c412263e2545cb95c8338f928c940.min.js:173), <anonymous>:124:14)
     at Function.observable.valueHasMutated (eval at require.load (802c412263e2545cb95c8338f928c940.min.js:173), <anonymous>:136:261)
     at Object.observable [as billingAddress] (eval at require.load (802c412263e2545cb95c8338f928c940.min.js:173), <anonymous>:133:707)
     at eval (eval at require.load
(802c412263e2545cb95c8338f928c940.min.js:173), <anonymous>:4:7)
     at eval (eval at require.load
(802c412263e2545cb95c8338f928c940.min.js:173), <anonymous>:16:138)
     at Function._.some._.any (eval at require.load (802c412263e2545cb95c8338f928c940.min.js:173), <anonymous>:17:237)
     at Function.eval [as some] (eval at require.load (802c412263e2545cb95c8338f928c940.min.js:173), <anonymous>:6:38)
     at Object.applyBillingAddress (eval at require.load (802c412263e2545cb95c8338f928c940.min.js:173), <anonymous>:16:88)
     at Object.resolveBillingAddress (eval at require.load (802c412263e2545cb95c8338f928c940.min.js:173), <anonymous>:15:454)

I think this issue is causes by changing billing-address.js in checkout module (but I am not shure):
this.isAddressSameAsShipping(
                        newAddress != null &&
                        newAddress.getCacheKey() == quote.shippingAddress().getCacheKey() //eslint-disable-line eqeqeq
                    );

old js look like this
this.isAddressSameAsShipping(newAddress != null && newAddress.getCacheKey() == quote.shippingAddress().getCacheKey());

**Comment by BharathN96** [comment] 2019-08-14 10:06
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-08-14 10:06
Hi @BharathN96. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-08-14 10:06
Hi @BharathN96, here is your [Magento instance](https://i-24131-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24131-2-3-develop.instances.magento-community.engineering/admin](https://i-24131-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment] 2019-08-14 10:10
Hello @matin73. Thank You for reporting. We've been not able to reproduce Your issue, following the steps provided. Can You confirm You are able to reproduce Your issue on a vanilla instance of 2.3-develop version?

**Comment by BharathN96** [comment] 2019-08-14 10:40
Issue is not reproduced in vanilla instance of 2.3-develop version.

**Comment by matin73** [comment] 2019-08-20 06:03
Issue is in combination with onestepcheckout. Modul developer gave me solution:
change line 86 of the following file: vendor/magento/module-checkout/view/frontend/web/js/view/billing-address.js

It should be changed from

if (quote.isVirtual()) {

to

if (quote.isVirtual() || !quote.shippingAddress()) {

**Comment by engcom-Bravo** [comment] 2019-08-20 13:15
Ok, @matin73, it's good if You have got a solution that satisfies You. But if You want this issue to be confirmed (and so processed forward to get fixed in the end) You need to give us the detailed steps following which we shall be able to reproduce it. For now we don't have such. So we are supposed to close the issue now but please feel free to reopen it if You are ready to provide us those steps. Thanks for applying.

**Closed as completed by engcom-Bravo** 2019-08-20 13:15 UTC
Labels: Progress: needs update, Issue: Format is valid
