### ISSUE TITLE
country_code  is not consistent in Customer Address

### ISSUE THREAD

**Issue by Renu05** [magento/magento2#29465] opened 2020-08-11 06:01 UTC
**As a developer, I want to get the country_code as enum so that it should be constant throughout the address**

**Existing result** : country_code is enum for createCustomerAddress whereas it is string in case of setBillingAddressOnCart and setShippingAddressesOnCart 

**Expected Result**: country_code must be enum in all the cases.

### AC
*a  In case of creating a customer address(createCustomerAddress), the country_code is defined as an enum.

![createCustomerAddress-mutation-Magento-2-Developer-Documentation](https://user-images.githubusercontent.com/34090452/89862091-d9a89b00-dbc4-11ea-9f82-d4cdf65e641f.png)

*b  Whereas in the setBillingAddressOnCart and setShippingAddressesOnCart have country_code as string
![setBillingAddressOnCart-mutation-Magento-2-Developer-Documentation](https://user-images.githubusercontent.com/34090452/89862331-576ca680-dbc5-11ea-82e3-e12ae9ae2a6a.png)

### Approved Schema 
The country_code must be enum in the address mutation

**Comment by krishprakash** [comment] 2020-08-11 07:19
Hi @Renu05. Thank you for your report.
Closing this as duplicate of #29467

**Closed as completed by krishprakash** 2020-08-11 07:19 UTC
Labels: Issue: Format is not valid, Project: GraphQL
