### ISSUE TITLE
Can't access backend indexers page after creating a custom index

### ISSUE THREAD

**Issue by ccasciotti** [magento/magento2#21510] opened 2019-02-28 14:39 UTC
After complete all the steps to create a new custom index as described in the official devdoc guide (https://devdocs.magento.com/guides/v2.2/extension-dev-guide/indexing-custom.html)
if you go on admin's indexer list page a fatal error is thrown due to a partially wrong implementation of `Magento\Indexer\Model\Indexer::getLatestUpdated` method called by `Magento\Indexer\Model\Indexer\DependencyDecorator::getLatestUpdated`.
The result of the `DependencyDecorator::getLatestUpdated` must be a string, but the `Indexer::getLatestUpdated` method returns `null` the very first time you access that backend page because no view is yet present.

### Preconditions (*)

1. Magento 2.2.7 (both community or commerce)

### Steps to reproduce (*)

1. Implementation of a custom index as the guide: https://devdocs.magento.com/guides/v2.2/extension-dev-guide/indexing-custom.html
2. Login to backend
3. Go to System > Index Management

### Expected result (*)

1. A successful response with the list of indexers
![image](https://user-images.githubusercontent.com/4273323/53573676-44e7e400-3b6e-11e9-9f85-0fec84805a35.png)

### Actual result (*)

1. A fatal error with this exception:
`PHP Fatal error:  Uncaught TypeError: Return value of Magento\\Indexer\\Model\\Indexer\\DependencyDecorator::getLatestUpdated() must be of the type string, null returned in <magento_root>/vendor/magento/module-indexer/Model/Indexer/DependencyDecorator.php:240`

**Comment by magento-engcom-team** [comment] 2019-02-28 14:39
Hi @ccasciotti. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ccasciotti do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-02-28 14:44
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-03-04 11:58
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98528`, `MAGETWO-98529` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-03-20 02:50
Hi @ccasciotti. Thank you for your report. 
The issue has been fixed in magento/magento2#21575 by @ccasciotti in 2.3-develop branch
Related commit(s):
 - [318425fafd4d92dbabcf89d332dedf9f27978f63](https://github.com/magento/magento2/commit/318425fafd4d92dbabcf89d332dedf9f27978f63)
 - [486e21c19a6678d3a1b6b0e259408fb1d205bceb](https://github.com/magento/magento2/commit/486e21c19a6678d3a1b6b0e259408fb1d205bceb)
 - [409e00e434f156501e1f1ae6d734d74ae82d70f3](https://github.com/magento/magento2/commit/409e00e434f156501e1f1ae6d734d74ae82d70f3)
 - [0acd6b6a0982941c11f1edfc10afd7896138222e](https://github.com/magento/magento2/commit/0acd6b6a0982941c11f1edfc10afd7896138222e)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-20 02:50 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Indexer

**Comment by magento-engcom-team** [comment] 2019-03-24 15:15
Hi @ccasciotti. Thank you for your report. 
The issue has been fixed in magento/magento2#21576 by @ccasciotti in 2.2-develop branch
Related commit(s):
 - [2c956f661caf1a10b1b6e6afea185fd473313fd3](https://github.com/magento/magento2/commit/2c956f661caf1a10b1b6e6afea185fd473313fd3)
 - [d5ed9e89b41c6d407869d4cf00f8293fb5f6e41f](https://github.com/magento/magento2/commit/d5ed9e89b41c6d407869d4cf00f8293fb5f6e41f)

The fix will be available with the upcoming 2.2.9 release.
