### ISSUE TITLE
Price on products becomes 0,00 after page has finished loading (ICU/LOCALE)

### ISSUE THREAD

**Issue by StarClassicNL** [magento/magento2#37644] opened 2023-06-20 14:24 UTC
### Preconditions and environment

    Centos7
    Plesk Obsidian 18.0.53
    PHP 8.1
    PHP 8.1.20
    ICU version | 50.2
    ICU Data version | 50.2
    ICU TZData version | 2018e
    ICU Unicode version | 6.2
    
    Magento 2.4.6
    Multistore setup
    Locale Options (Local) is set to Germany and Dutch
    Base Currency: Euro
    Default Display Currency: Euro
    Allowed Currencies: Euro
    4 different StoreViews are set up

### Steps to reproduce

    Having PHP8.1 on ICU v50.22 installed
    Locale set to anything but English
    Create new product (with any pricing)
    Go to product list page (categorie view page)
    Go to product details page (product view page)

### Expected result

    Actual price given should be visible on the product detail page price.

### Actual result

After the page fully loads the pricing changes to 0,00. This only happens on any other locale other than English.

### Additional information

Current workaround for me is to have all storeviews in the English locale.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-06-21 10:52
Hi @StarClassicNL,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Magento 2.4.6
- Multistore setup
- Locale Options (Local) is set to Germany and Dutch
- Base Currency: Euro
- Default Display Currency: Euro
- Allowed Currencies: Euro
- 4 different StoreViews are set up

- Having PHP8.1 on ICU v50.22 installed
- Locale set to anything but English
- Create new product (with any pricing)
- Go to product list page (categorie view page)
- Go to product details page (product view page)


<img width="1405" alt="Screenshot 2023-06-21 at 12 33 12 PM" src="https://github.com/magento/magento2/assets/51680745/903d5440-8506-4779-a806-5d09edbc11f2">



<img width="1378" alt="Screenshot 2023-06-21 at 12 30 38 PM" src="https://github.com/magento/magento2/assets/51680745/55dc558b-465b-41f3-b868-daa7ab438fb0">


<img width="1320" alt="Screenshot 2023-06-21 at 12 30 51 PM" src="https://github.com/magento/magento2/assets/51680745/dabf4b4c-e02a-4dbc-bde3-22342e7347b0">




<img width="1387" alt="Screenshot 2023-06-21 at 12 30 59 PM" src="https://github.com/magento/magento2/assets/51680745/88f52792-d23c-4ff4-93fb-9891942e4379">



<img width="1428" alt="Screenshot 2023-06-21 at 12 31 11 PM" src="https://github.com/magento/magento2/assets/51680745/215940c1-098b-4737-9d14-bbf7fb8565bf">

we have created different stores views and for each store view we have set a locale other than English. Every store view other than locale as english product detail page showing actual price of the product

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by StarClassicNL** [comment] 2023-06-27 13:48
@engcom-Bravo , Thank you for your effords and for verifying the issue. I have not been able to reproduce the issue on a different system either. However the problem seems to lie with Plesk's PHP 8.1 ICU version of 50.2, on a different cPanel host I managed to have the normal/expected result, however on the Plesk installation this issue remains from 2.4.4/2.4.5 and 2.4.6.

Did you reproduce it with ICU 50.2?

Thank you

**Comment by mrtuvn** [comment] 2023-07-03 14:54
problem look stranger i can't believe it's happen related with latest version. Interesting case. So basically in morning user visited store and see product with zero price in store

**Comment by MTheProgrammer** [comment] 2023-07-05 09:03
I think there might be a race condition during price reindex after import. We have the same problem on two independent Magento 2.4.6 instances with a few configurable products.

The Initial price is 0.00, but after selecting the swatch option it is updated correctly.

Manual reindex resolves the problem.

**Comment by StarClassicNL** [comment] 2023-07-05 09:35
@MTheProgrammer, for my instance manually re-indexen does **not** solve the problem, The only thing that currently keeps my stores online is using the _English Locale_. 

I've reproduced this issue on a similar environment using Plesk/PHP8.1 with ICU v50.22, but when I use my Magento instance on a different server with PHP8.1 and ICU70+ I do not have the issue. So i'm still thinking the issue lies within PHP INTL ICU version 50.22 on Plesk. (if only i knew how to upgrade this without breaking stuff hehe @ anyone?)

I was really trying to avoid having to move everything from my current server to a new one and still hoping the issue can somehow be resolved on my current system/magento instance.

**Comment by Bashev** [comment] 2023-07-15 08:53
Long story ... ICU library is very buggy and for some locales works fine, for some not. In the past we are made long discussion about that. https://github.com/magento/magento2/pull/34156#issuecomment-936243431

**Comment by ConradoSM** [comment] 2023-08-08 01:18
Same issue here, in PLP

![image](https://github.com/magento/magento2/assets/44508579/a3fc5c72-a36c-406d-937c-0c2c4bb91963)

in PDP:

![image](https://github.com/magento/magento2/assets/44508579/6f902e4a-9707-49f1-b0f7-2acb9d2c5979)

Locale es_AR

**Comment by ConradoSM** [comment] 2023-08-09 15:48
The issue occurs in all those products that have the last quantity available for sale.

![image](https://github.com/magento/magento2/assets/44508579/c2f5a437-f4c5-4ace-99d0-499533ddb34b)

![image](https://github.com/magento/magento2/assets/44508579/1a2cea3b-0b31-4f72-bd23-2627dfbd1531)

**Comment by engcom-Bravo** [comment] 2024-03-27 11:43
Hi @StarClassicNL,

Could you please try to reproduce the issue in Latest 2.4-develop instance and let us know if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-04-08 04:51
Hi @StarClassicNL,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-04-08 04:51 UTC
Labels: Issue: needs update, Reported on 2.4.x

**Comment by arnoldmontiel01** [comment] 2024-04-25 13:14
> The issue occurs in all those products that have the last quantity available for sale.
> 
> ![image](https://private-user-images.githubusercontent.com/44508579/259467737-c2f5a437-f4c5-4ace-99d0-499533ddb34b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTA3NzQsIm5iZiI6MTcxNDA1MDQ3NCwicGF0aCI6Ii80NDUwODU3OS8yNTk0Njc3MzctYzJmNWE0MzctZjRjNS00YWNlLTk5ZDAtNDk5NTMzZGRiMzRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDEzMDc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkY2M2MmZmYjEzOTI4ZWRhMGY3MTFjNzYyNzEwYmRjMThkNDRiZTkxYjMyM2ZhNjI5MzM2M2NiZmVkNDRhNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sUh1CISHaAv1joIWJ1jl0ruSIDhrs9rDwQgpKBi_rPg)
> 
> ![image](https://private-user-images.githubusercontent.com/44508579/259467796-1a2cea3b-0b31-4f72-bd23-2627dfbd1531.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTA3NzQsIm5iZiI6MTcxNDA1MDQ3NCwicGF0aCI6Ii80NDUwODU3OS8yNTk0Njc3OTYtMWEyY2VhM2ItMGIzMS00ZjcyLWJkMjMtMjYyN2RmYmQxNTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDEzMDc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MDU5ZGIyNTdhMmEzOTIxM2YxOGQ3MGJhNWM5ZjlhZjdiZTYwMDU5MjYwZDc0MTUwZWE0ZTZmMWE5ZTUwYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B2x4sdDhajBrnMHf8pvlnTx97LfIKi8UaZbxq9qlFLk)

Were you able to solve this issue?

**Comment by StarClassicNL** [comment] 2024-04-25 13:44
> > The issue occurs in all those products that have the last quantity available for sale.
> > ![image](https://private-user-images.githubusercontent.com/44508579/259467737-c2f5a437-f4c5-4ace-99d0-499533ddb34b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTA3NzQsIm5iZiI6MTcxNDA1MDQ3NCwicGF0aCI6Ii80NDUwODU3OS8yNTk0Njc3MzctYzJmNWE0MzctZjRjNS00YWNlLTk5ZDAtNDk5NTMzZGRiMzRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDEzMDc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkY2M2MmZmYjEzOTI4ZWRhMGY3MTFjNzYyNzEwYmRjMThkNDRiZTkxYjMyM2ZhNjI5MzM2M2NiZmVkNDRhNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sUh1CISHaAv1joIWJ1jl0ruSIDhrs9rDwQgpKBi_rPg)
> > ![image](https://private-user-images.githubusercontent.com/44508579/259467796-1a2cea3b-0b31-4f72-bd23-2627dfbd1531.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTA3NzQsIm5iZiI6MTcxNDA1MDQ3NCwicGF0aCI6Ii80NDUwODU3OS8yNTk0Njc3OTYtMWEyY2VhM2ItMGIzMS00ZjcyLWJkMjMtMjYyN2RmYmQxNTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDEzMDc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MDU5ZGIyNTdhMmEzOTIxM2YxOGQ3MGJhNWM5ZjlhZjdiZTYwMDU5MjYwZDc0MTUwZWE0ZTZmMWE5ZTUwYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B2x4sdDhajBrnMHf8pvlnTx97LfIKi8UaZbxq9qlFLk)
> 
> Were you able to solve this issue?

We have been unable to resolve the issue on the mentioned server/system. We have moved to a different server and control panel (WHM/CPanel), could easily update the ICU and all is good now.
