### ISSUE TITLE
Custom category attributes scope not working

### ISSUE THREAD

**Issue by Bartlomiejsz** [magento/magento2#7176] opened 2016-10-25 11:48 UTC
### Preconditions
1. Magento 2.1.2
### Steps to reproduce
1. Add custom attribute to category with website scope:

```
    $categorySetup->addAttribute(
            Category::ENTITY, 'attrib_code', [
                'type' => 'int',
                'label' => 'Label',
                'input' => 'select',
                'source' => 'Magento\Eav\Model\Entity\Attribute\Source\Boolean',
                'visible' => true,
                'required' => false,
                'sort_order' => 5,
                'global' => ScopedAttributeInterface::SCOPE_WEBSITE,
                'group' => 'Content',
            ]
        );
```
1. Add it to ui_component:

```
        <field name="attrib_code">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="dataType" xsi:type="string">boolean</item>
                    <item name="formElement" xsi:type="string">checkbox</item>
                    <item name="label" xsi:type="string" translate="true">Label</item>
                    <item name="prefer" xsi:type="string">toggle</item>
                    <item name="valueMap" xsi:type="array">
                        <item name="true" xsi:type="string">1</item>
                        <item name="false" xsi:type="string">0</item>
                    </item>
                    <item name="default" xsi:type="number">0</item>
                    <item name="sortOrder" xsi:type="number">5</item>
                </item>
            </argument>
        </field>
```
### Expected result
1. Custom attribute should be visible with scope `[website]`
### Actual result
1. No scope label is visible, and attribute saves as it was set to store_view scope

**Comment by leptoquark1** [comment] 2017-02-21 10:02
I've the extended problem that if I set the attribute scope to SCOPE_STORE for example, and I have the backend scope set to "All Store Views" and I save the category with the changed attribute I get the SQL Error of Allowed memory size exhausted...

**Comment by magento-engcom-team** [comment] 2017-10-13 08:30
@Bartlomiejsz, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by Tjitse-E** [comment] 2017-12-06 10:14
@magento-engcom-team can you point me to the commit that includes this fix?

**Comment by xpoback** [comment] 2018-02-13 14:56
@magento-engcom-team hey, I'm getting the problem in Magento 2.2.1 but that's OK.
Can you please point me and the guy above (@Tjitse-E ) to the commit that includes the fix?

**Comment by SimonAnguish** [comment] 2018-03-04 20:39
Also getting this problem. 4 custom category attributes save store view specific, but aren't show that way in the category view. Any progress in the last few weeks @xpoback?

**Comment by xpoback** [comment] 2018-03-12 15:20
@SimonAnguish No real fix, only a temporary solution.
Since I had to overwrite the data provider model to apply [this fix](https://github.com/magento/magento2/commit/14205b7c4997603daf657faddcdecd2c478245b7) (which has beenreleased only in 2.2.4), I added my custom attribute code to the return result of the  [function here](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Catalog/Model/Category/DataProvider.php#L527) in the rewritten file, which seems to have helped at least with saving scope specific values. The label I added in the xml:
`<item name="scopeLabel" xsi:type="string">[STORE VIEW]</item>`

**Comment by rparsi** [comment] 2018-06-13 15:42
@magento-engcom-team Can you please post the commit hash or url for the fix?  I'm experiencing same problem as others with version 2.2.3

Why do you ignore us???

**Comment by xpoback** [comment] 2018-06-16 08:49
@magento-engcom-team Please only add labels "_Fixed in x_" if the issue has really been fixed in the _release_, not just in the dev branch. So far it is present in 2.2.x and most probably also in 2.3.x releases and no fix reports have been appearing here.
If it has been fixed, please, provide the commit or PR.

**Comment by magento-engcom-team** [comment] 2018-12-24 13:15
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2018-12-24 14:12
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97324`, `MAGETWO-97325` were created

**Comment by magento-engcom-team** [comment] 2019-09-18 17:19
@Bartlomiejsz, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.3-develop` branch. Thank you for collaboration.

**Closed as completed by magento-engcom-team** 2019-09-18 17:19 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid
