### ISSUE TITLE
[Issue]  Call to a member function getName() when Submit close returns many items

### ISSUE THREAD

**Issue by trungpq2711** [magento/magento2#33640] opened 2021-07-30 12:05 UTC
Magento 2.4.2
<img width="1666" alt="12" src="https://user-images.githubusercontent.com/15412007/127650405-b3791c05-4c03-4c33-bce1-8b180510cb53.png">
<img width="1456" alt="13" src="https://user-images.githubusercontent.com/15412007/127650421-a47e99d1-9118-44c2-bda2-41fd445d2dcb.png">
<img width="1739" alt="14" src="https://user-images.githubusercontent.com/15412007/127650425-50a246a9-e308-4fd7-957f-b3e1c900379e.png">

**Comment by engcom-Delta** [comment] 2021-07-30 13:37
Hi @trungpq2711,

Kindly provide issue description , steps to reproduce , Actual results and Expected results. so that we can reproduce it.

Thanks

**Comment by trungpq2711** [comment] 2021-07-30 14:08
Hi @engcom-Delta 
Steps to reproduce 
Magento 2.4.2 
1. go to sales -> returns 
2. select more than two items
3. select action close and click submit

Actual results:
<img width="1739" alt="14" src="https://user-images.githubusercontent.com/15412007/127664545-6b71ed11-1803-4d87-835d-d0673f9207c9.png">
Expected:
close order success

Thanks!

**Comment by engcom-November** [comment] 2021-09-16 08:13
Verified the issue on Magento 2.4-develop branch having EE modules enabled but unable to reproduce the issue:
Steps performed:
Created Multiple Orders, Invoiced, shipped so that Order status is Complete
Created Returns for all the Orders - Status is Pending
Admin - sales -> returns
select more than 3 items
select action close and click submit
No issue: User is able to Submit and returns status is closed for all items
No exception/error in logs
![image](https://user-images.githubusercontent.com/60198231/133575645-5658559e-b07d-4fcd-bf74-296bd589e7d6.png)

![image](https://user-images.githubusercontent.com/60198231/133575547-e24fd88c-5f99-4d12-8abe-21cef4d703c5.png)

@trungpq2711 kindly verify the issue on Magento 2.4-develop branch having EE modules and provide missing steps if any if the issue is still reproducuble.
Thank you

**Comment by engcom-Hotel** [comment] 2021-09-29 14:33
Hello @trungpq2711,

We have noticed that this issue has not been updated for a long time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2021-09-29 14:33 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
