### ISSUE TITLE
Credit Memo Adjustment fee tax isn't calculated

### ISSUE THREAD

**Issue by paales** [magento/magento2#7937] opened 2016-12-22 14:29 UTC
### Preconditions

1. Magento 2.1.2

### Steps to reproduce

1. Create a credit memo and add an adjustment refund / fee

### Expected result

1. Tax is recalculated

### Actual result

1. No difference in tax

**Comment by olysenko** [comment] 2016-12-27 13:01
Hi, thank you for your report. Adjustment Fee and Adjustment Refund are not calculated fields  by design. It is just the possibilities to adjust your refund totals in plus and minus on some definite value. Closed as not a bug

**Closed as completed by olysenko** 2016-12-27 13:01 UTC
Labels: bug report, Component: Tax, Component: Sales, Issue: Format is valid, Partner: Reach Digital

**Comment by nikoelgatito** [comment] 2017-11-05 02:10
Hi, I do not agree as any credit issued for a product/service in a zone where it is subject to tax should also include the tax whether it is a partial refund for a refund for the entire price paid for an item.

When selling products in a region where a merchant has to charge tax, it is required by the law when refunding an amount related to a taxed transaction to also refund the tax attached to it.

This means that if a merchant is selling a $100 product in a zone where the tax is 10% resulting in a $110 transaction, if the merchant is later giving a $20 credit to the customer, the credit must be of $22 which is $20 + 10% tax. The same happens with any adjustments applied to any price, the tax must always end up been applied to the final credit amount.

Not respecting this is illegal and may lead to lawsuits in several countries.

**Comment by violuke** [comment] 2017-11-30 10:20
This needs reopening for the above reasons.
