### ISSUE TITLE
Sort by name Error when we have diferent languages 

### ISSUE THREAD

**Issue by cris7webjump** [magento/magento2#37271] opened 2023-03-20 12:59 UTC
### Preconditions and environment

Hello I want Report a bug in category page sort by name

- Magento version 2.4.5-p1 - Enterprise

I'm having problems sorting products by name on the category page, when there are different product names per store view. In this scenario, the number of products that appear per page is different from what is configured in the admin.
I recently tested it on a clean install and was able to reproduce.

### Steps to reproduce

1. Create 2 store view for language , example French and German
3. Create some products , ex: like more than 10 
4. Put the products in a category 
5. Add different names for languages 
6. Configure catalog to show 5 per page
7. Configure catalog to sort by name default

### Expected result

When you see that category, you need to see 5 per page

### Actual result

When you see that category, you will see other product number per page showing

### Additional information

recommendation to change only 1 product with different names per store view, just for testing, because when you remove it from the category, the pagination goes back to normal

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-03-23 13:54
Hi @cris7webjump,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance with enterprise edition and the issue is not reproducible.Kindly refer the screenshots.

We have followed same scenario :

First we have created product with a default name after that we have changed the names for each store views.


![Error (1)](https://user-images.githubusercontent.com/51680745/227201764-56583e26-4ad0-42d8-8e22-ab9e075eb590.png)


![Error](https://user-images.githubusercontent.com/51680745/227201803-ae671ca2-713f-437e-a57d-a32f6f5aa042.png)



Products are displayed as per configuration.


Kindly check your system requirements https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html and please let us know if you are still facing any issue.

it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-04-03 06:05
Hi @cris7webjump,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-04-03 06:05 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1
