### ISSUE TITLE
Invalid template file: 'Magento_OfflinePayments::info/pdf/purchaseorder.phtml' in module: 'Magento_OfflinePayments' block's name: 'info\\purchaseorder_0'

### ISSUE THREAD

**Issue by tarekfellah** [magento/magento2#32205] opened 2021-02-17 16:01 UTC
### Preconditions (*)

1.Magento 2.2.4
2. PHP 7.1

### Steps to reproduce (*)

1. When i tried to send invoice mail to customer or any other transactional emails
2.

### Expected result (*)

1. Emails sent to customers
2.

### Actual result (*)

1. Error Invalid template file: 'Magento_OfflinePayments::info/pdf/purchaseorder.phtml' in module: 'Magento_OfflinePayments' block's name: 'info\\purchaseorder_0'
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment] 2021-02-18 03:44
Update your magento version should fix this issue
Ex: version open source 2.2.9 or higher if possible

**Comment by engcom-Alfa** [comment] 2021-02-18 10:16
Hi @tarekfellah . Thank you for your report!
Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop.
Everything works as expected.

**Actual Result:** :heavy_check_mark:  Emails sent to customers
![Peek 2021-02-18 12-06](https://user-images.githubusercontent.com/51679138/108341679-94ec6500-71e2-11eb-88ea-dac47564b44d.gif)
![Screenshot from 2021-02-18 12-06-26](https://user-images.githubusercontent.com/51679138/108342034-fe6c7380-71e2-11eb-838c-6bd22a12308d.png)

So, we have to close it. 
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch.
 Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2021-02-18 10:16 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.2.x

**Comment by huykon** [comment] 2021-06-10 07:35
I having same issue in magento 2.4.2 version. I created custom payment offline then after place order I go to order detail on admin dashboard then I see this error
