### ISSUE TITLE
Layered Navigation is not working with multiselect and Filterable (with results)

### ISSUE THREAD

**Issue by shubham03mathur** [magento/magento2#12924] opened 2017-12-29 19:31 UTC
Layered Navigation is not showing when selecting multi-select attribute for product
Preconditions
   1. Magento 2.2.0

Steps to reproduce
I have added Multi-select Attribute with settings Filterable (with results)
Let's say there are three options defined option 1 and option 2 and option 3
    -> Product 1 with option 1
    -> Product 2 with option 1 and option 2 selected
Now Magento shows only option 2 where product count is 2 and option 1 is not shown.

When Changing the products to the following:

   -> Product 1 with option 1
   -> Product 2 option 2 selected
both options are shown again in layered navigation.
  
Expected Result
   Layered navigation should show both options
         Option 1 (#product_count)
         Option 2 (#product_count)

Actual result
         Options are not shown as it describes above.

**Comment by magento-engcom-team** [comment] 2018-01-04 07:28
Hello @shubham03mathur. Thanks for reporting. You See Magento's logic on displaying attributes in layered navigation till now has been to show the Customer that the products differ in this or that particular attribute and so he or she can chose among the values of the attribute. Assume there is a color attribute with 3 values: red, blue and green, and there are three products in some category each being red. If we now enter that category's page we won't see color attribute in layered navigation because current products in such case are not distinguished by color attribute. The customer is not able to chose among colors of the products in this category. So there is no need and probably would not be correct to show him or her how many products are available to him or her in each possible color. If You then assign to one of the three products lets say color blue the color attribute will appear in layered navigation with appropriate results: red(2), blue(1). In Your case, though the attribute is being a multi-select the situation is similar - when both products in the category has the same one option of the attribute the option won't be shown in layered navigation. Though if You set Filterable no results for Use in Layered Navigation for Your attribute it will show up in the layered navigation Just as You expect.
Of course it may look confusing from some point of view. So this logic with attribute displaying is being discussed with the product owner and may be changed in the future to the one You support.

**Comment by magento-engcom-team** [comment] 2018-01-04 07:29
@shubham03mathur, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by 666triv** [comment] 2018-01-05 10:57
I can confirm, that this is not working for us in the way you describe, we have tried with results and no results and changed the scope which are the only 2 main display settings in the backend for the attribute and the multi select options on the frontend just don't appear. 

They will only show if the multi select has 1 option only per multi select attribute only, turning it into a dropdown almost for the entire collection it is filtering for. So out of 4000 products not a single multi select shows unless 1 option is selected amongst all the products for example we have red blue and green and out of the 4000 products all of them have 1 color specified as required and if all products use red the multi select shows, if all use blue, the blue option shows and if all use green the green filter shows but the second product number 2 uses a different colour the attribute then disappears which is not normal as we now need that feature to filter between the 2 colours. We can also remove some products from using the same colour so 3999 can use red and the left over product has no colour the filter will still show, it's like the mutli-select is not for comparing anymore. if the remaining product then uses either green or blue rather than red, it then does not show.

**Comment by magento-engcom-team** [comment] 2018-02-06 14:19
@666triv thank you for your comment.
Would You please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Closed as completed** 2018-02-19 06:29 UTC
Labels: Progress: needs update, Issue: Clear Description, non-issue, Issue: Format is valid
