### ISSUE TITLE
Switching between store views gives "404 Not Found" when the customer is logged in and there is a difference in the URL key between the store views

### ISSUE THREAD

**Issue by zexperto** [magento/magento2#27680] opened 2020-04-09 16:39 UTC
### Preconditions (*)

1. Magento Open Source Version 2.3.3 and Magento Open Source Version 2.3.4

### Steps to reproduce (*)

1. Install Magento 2.3.4
2. Create Second Store Views (French)
3. Rename the code of English store view to 'en'
4. Rename the code of Frenchstore view to 'fr'
5. Modify the configuration to add store code to the URL
6. Create new simple product (use below data)
        - Name : Simple Product English
	- SKU : simple-product-test
	- **Click on Save**
7. Switch to the French store view and edit the name and url_key
	- Name : Simple Product French
	- URL Key: simple-product-french
	- **Click on Save**
8. Now open the product page by going to {url}/en/simple-product-english.html
9. Switch 3-4 times between those two store views (English and French)
10. everything is okay and we can see the products in the two store views with the correct URL for each store
11. Now Create a customer from the frontend
12. Login using this customer
13. Go back to the product page
14. Try to switch between the store views (English/French) in the product page 3-4 times
15. **Bom**: you will start see the 404 Not found

### Expected result (*)

1. We expected to see the product page with the correct URL for all store views

### Actual result (*)

1.  we are getting "404 Not Found"

**Comment by zexperto** [comment] 2020-04-09 16:39
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment] 2020-04-09 16:39
Hi @zexperto. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-09 16:41
Hi @zexperto, here is your [Magento instance](https://i-27680-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27680-2-4-develop.instances.magento-community.engineering/admin_fe8a](https://i-27680-2-4-develop.instances.magento-community.engineering/admin_fe8a)
Login: `9ddc7e8d` Password: `24175a7430ba`
Instance will be terminated in up to 3 hours.

**Comment by zexperto** [comment] 2020-04-09 16:47
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-09 16:47
Hi @zexperto. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by zexperto** [comment] 2020-04-09 16:48
cannot re-produce it on vanilla Magento instance 2.3.4

**Comment by zexperto** [comment] 2020-04-09 16:49
> Hi @zexperto. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [ ]  Summary of the issue
> * [ ]  Information on your environment
> * [ ]  Steps to reproduce
> * [ ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.4-develop instance` - upcoming 2.4.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @zexperto do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ ]  yes
> * [ ]  no
> 
> * Join [Magento Community Engineering Slack](https://opensource.magento.com/slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

cannot re-produce it on vanilla Magento instance 2.3.4

**Comment by magento-engcom-team** [comment] 2020-04-09 16:50
Hi @zexperto. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-09 16:51
Hi @zexperto, here is your [Magento instance](https://i-27680-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27680-2-4-develop.instances.magento-community.engineering/admin_6043](https://i-27680-2-4-develop.instances.magento-community.engineering/admin_6043)
Login: `3213a375` Password: `b752860a9139`
Instance will be terminated in up to 3 hours.

**Comment by zexperto** [comment] 2020-04-09 16:53
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-09 16:53
Hi @zexperto. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by zexperto** [comment] 2020-04-09 17:16
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment] 2020-04-09 17:16
Hi @zexperto. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment] 2020-04-09 17:17
Hi @zexperto, here is your [Magento instance](https://i-27680-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-27680-2-3-4.instances.magento-community.engineering/admin_7f0d](https://i-27680-2-3-4.instances.magento-community.engineering/admin_7f0d)
Login: `996ea183` Password: `558a9f6a6e58`
Instance will be terminated in up to 3 hours.

**Comment by zexperto** [comment] 2020-04-09 17:26
I could re-produce the issue on Magento 2.3.4 
here is the product URL
https://i-27680-2-3-4.instances.magento-community.engineering/en/simple-product-english.html

you can use this to login
email:                 myemail@test.com
password:          Q@123456

**Comment by sudheers-kensium** [comment] 2020-04-13 10:48
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-13 10:48
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-13 10:50
Hi @sudheers-kensium, here is your [Magento instance](https://i-27680-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27680-2-4-develop.instances.magento-community.engineering/admin_82c2](https://i-27680-2-4-develop.instances.magento-community.engineering/admin_82c2)
Login: `0718d52c` Password: `77775ad1ad74`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment] 2020-04-13 11:05
@zexperto I am not able to reproduced the issue on Magento 2.4-develop instance.

I am closing this issue, maybe  this issue is resolved on latest version.

**Closed as completed by sudheers-kensium** 2020-04-13 11:05 UTC
Labels: Issue: Format is valid, Reported on 2.3.3

**Comment by zexperto** [comment] 2020-04-13 20:20
> @zexperto I am not able to reproduced the issue on Magento 2.4-develop instance.
> 
> I am closing this issue, maybe this issue is resolved on latest version.

the problem in Magento 2.3.x version not in Magento 2.4, I supposed that this version is still in the live cycle , did you try to re-produce it in that version ?
