### ISSUE TITLE
Cannot export salable quantity column from products

### ISSUE THREAD

**Issue by talsan74** [magento/magento2#36869] opened 2023-02-15 13:47 UTC
### Summary

we are using magento 2.4.4. we cannot export salable quantity column from export csv option. Even this attribute not showing on export option

### Examples

we tried to export salable quantity from export option to output as a csv file. we cannot get salable quantity column. It is not listed from export entities. But that column is showing products lists. So how get that column from csv exported file

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-02-16 07:00
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-02-16 11:24
Hi @talsan74,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.

We are able to export only product attributes as mentioned in the below list.


<img width="1420" alt="Screenshot 2023-02-16 at 4 50 48 PM" src="https://user-images.githubusercontent.com/51680745/219351528-89d18fa0-36df-4ae9-993d-ee667901475c.png">




Salable quantity is not a product attribute so we cannot export for a product.Salable quantity is managed by sources and stocks based on inventory management.

Kindly check this document https://experienceleague.adobe.com/docs/commerce-admin/inventory/basics/sources-stocks.html?lang=en about sources and stocks.

Please let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-02-28 06:20
Hi @talsan74,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-02-28 06:20 UTC
Labels: Issue: needs update, Reported on 2.4.4
