### ISSUE TITLE
Configurable Product Main Images Append rather than replace

### ISSUE THREAD

**Issue by virani06** [magento/magento2#23284] opened 2019-06-17 11:10 UTC
Configurable Product Main Images Is Append Rather Than Replace All Images With That Color Images.

### Preconditions (*)

Magento 2.3.1 Fresh Installation

### Steps to reproduce (*)

1) First We Add Configurable Product. In That Suppose We Add 3 Images In Configurable Product Like Cnf1.jpg Cnf2.jpg And Cnf3.jpg

2) After That We Create The Configuration In That We Add 2 Colors.

3) Add The Color First Red Images Like R1.jpg R2.jpg R3.jpg

4) Same Way Add Second Yellow Color And Add Images Like Y1.jpg, Y2.jpg , Y3.jpg

5) After That Go To Frontend We See The Images Cnf1.jpg Cnf2.jpg And **cnf3.jpg.

But When We Click On Red All Images Must Be A Replace With  R1.jpg R2.jpg R3.jpg

Actual Result :  R1.jpg R2.jpg R3.jpg

Getting Result Is :  R1.jpg R2.jpg R3.jpg Cnf1.jpg Cnf2.jpg And Cnf3.jpg

All Configurable Image Is Appending .

Try With Magento 2.3.1 Fresh Instance.

### Expected Result (*)

1.   R1.jpg R2.jpg R3.jpg

### Actual Result (*)

1. R1.jpg R2.jpg R3.jpg Cnf1.jpg Cnf2.jpg And Cnf3.jpg

please give @magento give me 2.3-develop instance

**Comment by virani06** [comment] 2019-06-18 05:35
Hi 

1) First Install fresh magento 2.3.1
Php version  7.1.30
Mysql
Ubuntu 18.04

2) Steps To Reproduce

First We Add Configurable Product. In That Suppose We Add 3 Images In Configurable Product Like Cnf1.jpg Cnf2.jpg And Cnf3.jpg

After That We Create The Configuration In That We Add 2 Colors.

Add The Color First Red Images Like R1.jpg R2.jpg R3.jpg

Same Way Add Second Yellow Color And Add Images Like Y1.jpg, Y2.jpg , Y3.jpg

After That Go To Frontend We See The Images Cnf1.jpg Cnf2.jpg And **cnf3.jpg.

But When We Click On Red All Images Must Be A Replace With R1.jpg R2.jpg R3.jpg

**3) Expected Result (*)**
R1.jpg R2.jpg R3.jpg

 **4) Actual Result (*)**
R1.jpg R2.jpg R3.jpg Cnf1.jpg Cnf2.jpg And Cnf3.jpg

**Comment by engcom-Bravo** [comment] 2019-06-18 11:48
Hello @virani06. Thanks for applying. Why do You think those images should be replaced and not appended? In Your case Cnf1.jpg Cnf2.jpg and Cnf3.jpg are supposed to be related to both the Red and the Yellow color products. So these pictures represent both variations (Red and Yellow) and thus quite logically belong to their sets of images. But they occupy the last places in the sets as they are less specific than those  R1.jpg, R2.jpg, R3.jpg and Y1.jpg, Y2.jpg , Y3.jpg supposed to represent the concrete variation.

**Comment by virani06** [comment] 2019-06-20 05:46
Hi Sir,

Yes it is the combination of red and yellow product.

But when any person click on red than it must be a displaed with only all red images. Not yellow which we already added in as configurable.

it is the simple logic. 

http://demo-acm-2.bird.eu/breathe-easy-tank.html

By default there is white images. when we click on the pink first image replace with pink and other two(white) images are appends.

There is no issue like that in magento 1.9

**Comment by engcom-Bravo** [comment] 2019-06-20 07:05
Ok @virani06, Your logic is quite clear and good. But another logic is possible too. I've created some test entities in Your demo instance - terribly sorry if You've been not going to allow it ). So please visit this [page](http://demo-acm-2.bird.eu/categ.html). There are two individually visible simple products Coca-Cola-Red and Coca-Cola_Yellow. If You enter them You'll be able to see only their individual pictures. But there is also a configurable product named "Coca-Cola". The previous two simples are its variations. And so now if you access them in context of Coca-Cola they will contain their individual pictures together with the general picture of the configurable. Doesn't it make sense in Your opinion?

**Comment by virani06** [comment] 2019-06-20 09:48
@engcom-Bravo I understand with the simple product. BUt it is the general if you are displaying fashion product when person is checking white color product why it was displaying other product.

In your option there is only just Coca Cola One vartion. If you want to add 30 product of Coca Cola Diffrent varation than in the category list page it will be a same images for all products.


 you can check it on your demo also
http://demo-acm-2.bird.eu/frankie-sweatshirt.html
see below product. same issue in your demo.


I think it needs to change. it will be a replace not to append.

**Comment by engcom-Bravo** [comment] 2019-06-20 12:40
@virani06 seems there is some misunderstanding here: "In your option there is only just Coca Cola One vartion". Coca Cola cofigurable product had Two variations called Coca-Cola-Red and Coca-Cola_Yellow accordingly. But anyway, I'll try make Your issue be confirmed as a feature request so it can get a further attention from the developers. thank You for applying.

**Comment by virani06** [comment] 2019-06-20 14:27
@engcom-Bravo It is not features. it is the issue with the 2.2.x and 2.3.x  the same thing is workign with magento 2.x 

You  can check the demo below link with magento 2.0.6

http://magento2.demo.ubertheme.com/breathe-easy-tank.html

It was the perfect. till magento 2.1.x

After Updating to Magento 2.2.x  There is a issue.

Please verify it with magento 2.0.x. It is not Reproduce in that version

**Comment by engcom-Bravo** [comment] 2019-06-20 14:32
@virani06, don't You admit that images behavior was changed deliberately?

**Comment by virani06** [comment] 2019-06-21 11:52
How it will be a done?

**Comment by magento-engcom-team** [comment] 2019-06-21 14:02
@engcom-Bravo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-06-21 14:12
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17689`, `MC-17690` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by virani06** [comment] 2019-07-22 10:52
@engcom-Bravo Any Updated

**Comment by magento-engcom-team** [comment] 2020-11-30 21:47
The report related to technology or functionality that was removed(or not supported) from the Magento code-base.
Or cannot be fixed and delivered in the scope of this public repository.

Examples:
- Removed payment methods. [Magento Commerce 2.4.0 Release Notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-commerce.html), [Deprecation of Magento core payment integrations](https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445). All questions, issue reports, and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
- Mysql search. Replaced with Elasticsearch 
- Not [Supported browsers](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#supported-browsers)
- Not supported [Operating systems](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#operating-systems-linux-x86-64)
- Web Wizard install
- Not a bug 
- etc

**Closed as completed by magento-engcom-team** 2020-11-30 21:47 UTC
Labels: Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Component: ConfigurableProduct, Progress: ready for dev
