### ISSUE TITLE
Magento 2.1 Cannot access/edit Blocks, Pages, Catalog and Categories from backend

### ISSUE THREAD

**Issue by justyn-clark** [magento/magento2#5744] opened 2016-07-21 18:40 UTC
In the backend the Blocks, Pages, Catalog and Categories pages fail to load and remain stuck loading resulting in the inability to edit these pages. 

![screen shot 2016-07-21 at 10 13 48 am](https://cloud.githubusercontent.com/assets/11221796/17034434/894def16-4f37-11e6-828c-f74a43a54fa5.png)

**Comment by oserediuk** [comment] 2016-07-27 13:32
Hello! Please, provide your code base version and clarify steps to reproduce.

**Comment by magwave** [comment] 2016-08-02 07:27
I have the same problem... I have installed Magento 2.1 from Clouways and after the first access (clean environment), I found myself in the same situation.

**Comment by magwave** [comment] 2016-08-02 08:38
Ok I found a solution that work for me.

1) I add this row:
    "rjsResolver":          "mage/requirejs/resolver"
    in pub/static/_requirejs/adminhtml/Magento/backend/en_US/requirejs-config.js after "map": {
        "*": {
2) I delete all content of pub/static and var/cache
3) I emptied browser's cache

Now finally seem work fine.

**Comment by andimov** [comment] 2016-08-15 14:12
@justyn-clark Do you have any updates for this issue?
@magwave Thank you for solution!

**Comment by andimov** [comment] 2016-08-16 07:46
@justyn-clark 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by justyn-clark** [comment] 2016-08-18 05:30
@andimov our team has 2.1 working now. I'm not sure exactly what was done but my co-worker does. I can find out on Monday and report back which might be an additional solution to @magwave 's if not the same.

**Comment by nomuprive** [comment] 2016-08-28 03:21
@justyn-clark Would really like to get an information about this issue as well. Thanks!

**Comment by veloraven** [comment] 2016-08-30 11:11
@justyn-clark any updates on this?
Is this issue still actual?

**Comment by nomuprive** [comment] 2016-08-31 22:00
@justyn-clark any updates on how your team fixed the Magento 2.1 Cannot access/edit Blocks, Pages, Catalog and Categories from backend ? 

Thanks!

**Comment by Maeva7** [comment] 2016-09-06 09:08
I'm having the same problem since yesterday. Sadly, the solution from magwave didnt work for me.
Hope someone else finds a solution for this.

**Comment by justyn-clark** [comment] 2016-09-06 16:47
Hi, the developer on our team that was in charge of M 2.1 instances has left the project so I don't know the exact details of how the issue was resolved. I do apologise.

**Comment by veloraven** [comment] 2016-09-29 12:21
I'm closing this issue as it is not actual for the reporter any more.
If you have the same issue please clear your browser cache including offline website data.
If you still have similar problem, please create new issue formatting it according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running and if it was some upgrade or clear install.

**Closed as completed by veloraven** 2016-09-29 12:21 UTC
Labels: Progress: needs update

**Comment by Strangerida** [comment] 2017-01-20 18:26
I got same issue now running 2.1.3 was working all fine then out of sudden it just is stuck in a loading loop. 
All other sections are fine 

Running 2.1.3
![screenshot_2017-01-21-05-17-06-74](https://cloud.githubusercontent.com/assets/17924022/22160552/30dc86e6-df9a-11e6-8a3b-34674661c802.png)
