### ISSUE TITLE
Parse error:  syntax error, unexpected ')' in InvoiceTotal.php on line 89

### ISSUE THREAD

**Issue by jorgb90** [magento/magento2#30604] opened 2020-10-22 15:20 UTC
### Preconditions (*)
1. Magento 2.4.1

### Steps to reproduce (*)
1. Running developer mode
2. Run bin/magento setup:di:compile

### Expected result (*)
1. Succesfully finishing recompiling

### Actual result (*)
1. Parse error:  syntax error, unexpected ')' in /var/www/vhosts/xxxxx/vendor/magento/module-sales-graph-ql/Model/Resolver/Invoice/InvoiceTotal.php on line 89

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment] 2020-10-22 16:20
This doesn't seem to happen on a clean Magento 2.4.1 project.

Are you sure you haven't accidentally modified that file? (Or maybe your disk space is full and the file is only written halfway to the disk or something like that?)

**Comment by engcom-Delta** [comment] 2020-10-23 06:14
Hi @jorgb90 thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop and on 2.4.1
**Result:**
`bin/magento setup:di:compile` runs without errors
![image](https://user-images.githubusercontent.com/51681379/96962630-e3794380-150f-11eb-8fdf-65e8537341c4.png)


Could you provide additional details that helps to reproduce issue?

**Comment by jorgb90** [comment] 2020-10-23 06:41
Mm strange. I didn't modify the file, but there is a .InvoiceTotal.php.swp file created in that dir, but the complete InvoiceTotal.php is also there.

**Comment by ihor-sviziev** [comment] 2020-10-23 07:11
Hi @jorgb90,
I see in the code we have trailing comma, that supported by php 7.3+ only (this is the minimum required php version for 2.4.x).

https://github.com/magento/magento2/blob/1353a546cc9aa4c6cc7f7d86763112d23645fcb7/app/code/Magento/SalesGraphQl/Model/Resolver/Invoice/InvoiceTotal.php#L86-L89

Please check your used php version **on the web server** using the `phpversion()` function.

**Comment by jorgb90** [comment] 2020-10-23 07:32
Hi @ihor-sviziev,

This was it. I feel stupid..  Our dev environment is running on version v7.4.11, but the cli version was still at v7.2. I have updated the system PHP and now its working.

**Comment by ihor-sviziev** [comment] 2020-10-23 08:12
@jorgb90 ok, I'm closing this issue.

**Closed as completed by ihor-sviziev** 2020-10-23 08:12 UTC
Labels: not-confirmed, Reported on 2.4.1
