### ISSUE TITLE
shipping cart is empty than also minicart display item [ Magento 2.0.0 ]

### ISSUE THREAD

**Issue by parthviroja** [magento/magento2#4460] opened 2016-05-11 06:39 UTC
i have install magento 2.0.0 on live server

when i have remove items from shipping cart, minicart not updated.

now i refresh page few times, than also minicart display item.

![15](https://cloud.githubusercontent.com/assets/9655554/15172068/ffe0b392-1770-11e6-8e43-30ab889e8ebd.png)

**Comment by maksek** [comment] 2016-05-11 18:55
@parthviroja, looks like you have customized theme already, can you reproduce the same behavior on vanilla Magento 2.0.5 installation?

**Comment by parthviroja** [comment] 2016-05-12 04:08
Thanks @maksek,

Same Issue produce in 2.0.5 after upgrade from 2.0.0.

This issue produce when i add item in cart after 15 to 20 minute, when i open shipping cart page, this happens.

When i clean browser cache and history than, minicart display empty.

**Comment by devhn** [comment] 2016-05-12 06:51
Same problem here using a custom theme (2.0.5). This was also reproduced with clean install - theme default. Mostly it happens when submitting an order when minicart should be cleared but it still shows the same product altough the cart page shows no products.

**Comment by andidhouse** [comment] 2016-05-12 07:13
Same problem here on 2.0.5 fresh install - no custom theme.
Seems to me that the minicart is not cleaned after the cart is cleaned.

We had this issue also on 2.0.0 and 2.0.2.

**Comment by ishakhsuvarov** [comment] 2016-05-26 11:13
@devhn Which payment method did you use when placing order?
@andidhouse Please provide more precise steps to reproduce the issue (how do you clean the cart, etc.) Thanks.

**Comment by andidhouse** [comment] 2016-05-26 12:19
@ishakhsuvarov 
Steps:
1. put some times in the shopping cart
2. wait some time (in our case and settings half an our)
3. the shopping cart page is empty - BUT the minicar is not empty but having the articles stored

**Comment by ishakhsuvarov** [comment] 2016-05-26 13:43
@andidhouse Steps you described look similar to the ones in #4416 I'm pretty sure it is the same case. We currently have a similar item in our backlog with the internal id `MAGETWO-52593`.

**Comment by veloraven** [comment] 2016-08-30 07:22
@parthviroja the internal issues was already fixed in commit c2bbe72 and closed.
Please let us know if your issue is fixed or still reproduces (in case it had different cause).

**Comment by andimov** [comment] 2016-09-14 09:50
The [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html) suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.

**Closed as completed by andimov** 2016-09-14 09:50 UTC
Labels: Issue: Ready for Work, bug report, Progress: needs update, Component: Checkout

**Comment by winds1983** [comment] 2017-04-27 04:48
Still happened on 2.1.6, how to fix this?
