### ISSUE TITLE
Magento 2 loses the problem Less file name in a «Compilation from source / Cannot read contents from file» error report (and my fix)

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2467] opened 2015-11-22 09:32 UTC
https://mage2.pro/t/233

**Comment by dmitrii-fediuk** [comment] 2015-12-02 07:28
The same problem: http://magento.stackexchange.com/questions/92287

**Comment by vzabaznov** [comment] 2016-06-22 12:29
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment] 2016-07-14 08:11
Hi, @mage2pro thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.

**Closed as completed by vzabaznov** 2016-07-14 08:11 UTC
Labels: Progress: needs update
