### ISSUE TITLE
Billing Agreements page title need to be improved

### ISSUE THREAD

**Issue by amitvishvakarma** [magento/magento2#22875] opened 2019-05-13 22:59 UTC
### Preconditions (*)

1. Magento 2.3.x
2. Customer must be logged in.

### Steps to reproduce (*)

1. Login as customer in frontend
2. Now go to Billing Agreements tab

### Expected result (*)

1.Page title must be only : Billing Agreements

### Actual result (*)

1. Page title is showing: Billing Agreements / My Account

**Comment by ajijshekh123** [comment] 2019-05-14 05:06
Give me @magento-engcom-team give me 2.3-develop instance.

**Comment by magento-engcom-team** [comment] 2019-05-14 05:06
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-05-14 05:07
Hi @ajijshekh123, here is your [Magento instance](https://i-22875-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22875-2-3-develop.instances.magento-community.engineering/admin](https://i-22875-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-05-14 05:09
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99685` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by shikhamis11** [comment] 2019-05-14 05:13
Since all other links doesn't have the prepend functionality so this should be similar for all links in my account

**Comment by magento-engcom-team** [comment] 2019-05-23 21:56
Hi @amitvishvakarma. Thank you for your report. 
The issue has been fixed in magento/magento2#22876 by @amitvishvakarma in 2.3-develop branch
Related commit(s):
 - [3fb72ae5638242bc83e261e3a88a8ba22f4bfeff](https://github.com/magento/magento2/commit/3fb72ae5638242bc83e261e3a88a8ba22f4bfeff)
 - [ed84c8d415a22cdc25751f85991d2e0bb6faccc6](https://github.com/magento/magento2/commit/ed84c8d415a22cdc25751f85991d2e0bb6faccc6)

The fix will be available with the upcoming 2.3.3 release.

**Closed as completed by magento-engcom-team** 2019-05-23 21:57 UTC
Labels: Issue: Ready for Work, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: CheckoutAgreements
