### ISSUE TITLE
Invoice with multi store

### ISSUE THREAD

**Issue by vlauria** [magento/magento2#3576] opened 2016-02-29 08:53 UTC
Hi,
i have two stores in my website. If i create order in store 1, sequence of increment_id is saved in sales_sequence_1
If i create a order in store 2, sequence of increment_id is saved in sales_sequence_1. Not in sales_sequence_2.
So, for each order the invoice always uses sale_sequence_1 table to calculate the next increment id.
In sales_invoice i have store_id correct.

**Comment by vlauria** [comment] 2016-02-29 10:35
Same problem with order in multi store. It uses always sales_sequence_1

**Comment by akaplya** [comment] 2016-02-29 17:51
It is expected behavior. Magento creates sequence tables per `Store Group`. Several `Store Views` of one group use same sequence.

**Comment by NadiyaS** [comment] 2016-06-08 13:44
Issue is closed as not a bug.

**Closed as completed by NadiyaS** 2016-06-08 13:44 UTC

**Comment by ctadlock** [comment] 2017-01-19 19:49
@NadiyaS This is highly confusing. I do believe there is a bug here in at the `sales_sequence_X` table should not be created for store views. In the example above the `sales_sequence_2` table should not be created.

I wont even go into the poor design decision to create a new table for each store.
