### ISSUE TITLE
COSTOS

### ISSUE THREAD

**Issue by Ksegovia22** [magento/magento2#37843] opened 2023-08-03 21:35 UTC
### Summary

Buen día quisiera saber cuales son los costos para usar Magento Version 2. 4. 0 

### Examples

Tengo un proveedor esta ayudandome a usar Magento pero siento que me esta cobrando de mas 
[PWA181009NA2_08022023T104228639_525.pdf](https://github.com/magento/magento2/files/12255224/PWA181009NA2_08022023T104228639_525.pdf)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-08-04 11:18
Hi @Ksegovia22,

Thank you for reporting and collaboration.

To speed up the processing of this issue, please provide us with the following information:

* Summary of the issue
* Information on your environment
* Steps to reproduce
* Expected and actual results


Thanks

**Comment by engcom-Bravo** [comment] 2023-08-16 06:06
Hi @Ksegovia22,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/37843#issuecomment-1665447178 still you are working on this issue please elaborate the steps to reproduce to proceed further.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-08-18 06:18
Hi @Ksegovia22,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-08-18 06:18 UTC
Labels: Issue: needs update, Reported on 2.4.0
