### ISSUE TITLE
Mag

### ISSUE THREAD

**Issue by PrincessBrozo** [magento/magento2#38033] opened 2023-10-02 19:01 UTC
### Preconditions and environment

- Magento version : Magento ver. 2.3.7-p4
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

Steps to reproduce

1. An error message "Something went wrong with processing the default view and we have restored the filter to its original state." continuously pop up when I open Sales > Orders view.
2. I think the issue started since I have changed the filter to '999 per page'.
3. I'd like to reset the filter as the default one but I cannot because the page gets blocked whenever I enter.

### Expected result

Would like to open and see the orders list.

### Actual result

Error message : "Something went wrong with processing the default view and we have restored the filter to its original state."
Issue : Cannot click anything in the page. (Sales > Orders)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by PrincessBrozo** [comment] 2023-10-02 19:04
@magento give me 2.4-develop instance

**Comment by PrincessBrozo** [comment] 2023-10-02 19:08
@magento give me test instance

**Comment by PrincessBrozo** [comment] 2023-10-02 19:08
@magento give me 2.4-develop instance

**Comment by PrincessBrozo** [comment] 2023-10-02 19:15
@give me 2.4.3 develop instance

**Comment by PrincessBrozo** [comment] 2023-10-02 19:25
![image](https://github.com/magento/magento2/assets/146771749/a8a26df3-a960-4e90-bd51-cb4c8434a4fc)

**Comment by PrincessBrozo** [comment] 2023-10-02 19:26
@ magento Verified the issue on Magento 2.4.3 develop instance and the issue is not reproducible.Kindly refer the screenshots above

**Comment by PrincessBrozo** [comment] 2023-10-02 19:27
@magento Verified the issue on Magento 2.4.3 develop instance and the issue is not reproducible.Kindly refer the screenshots above

**Comment by engcom-Bravo** [comment] 2023-10-03 09:56
Hi @PrincessBrozo,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- An error message "Something went wrong with processing the default view and we have restored the filter to its original state." continuously pop up when I open Sales > Orders view.
- I think the issue started since I have changed the filter to '999 per page'.
- I'd like to reset the filter as the default one but I cannot because the page gets blocked whenever I enter.


We are able to open the orders and reset the filters.

<img width="1494" alt="Screenshot 2023-09-26 at 12 08 51 PM" src="https://github.com/magento/magento2/assets/51680745/b918e067-c1d3-4130-836d-aac2938fa388">



Can you please check this solution :

* Please check "catalog_product_entity" table in the database for any sku 's having NULL value and update them:
* UPDATE catalog_product_entity SET sku='' WHERE sku IS NULL;
* Check if the user is having very restricted Access to the magento backend and grant users access to the product catalog / orders that may fix this issue.
* Run the query: TRUNCATE ui_bookmark; this will reset the grid back to it's default and stop the infinite load.



Thanks.

**Comment by PrincessBrozo** [comment] 2023-10-03 13:05
@engcom-Bravo Can you  please  share a screenshot how to perform these steps : check "catalog_product_entity" table in the database for any sku 's having NULL value and update them:
UPDATE catalog_product_entity SET sku='' WHERE sku IS NULL;
Check if the user is having very restricted Access to the magento backend and grant users access to the product catalog / orders that may fix this issue.

My apologies Im not familiar how to do it  and I dont know if I  even have an access to the magento  backend

**Comment by engcom-Bravo** [comment] 2023-10-04 10:57
Hi @PrincessBrozo,

Thanks for your update.

It seems to be issue is caused by third party modules Please check the issue if any 3rd party extensions / modules enabled is causing this issue.We are not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) or the [Magento Market place](https://marketplace.magento.com/extensions.html) page

Thanks.

**Comment by engcom-Bravo** [comment] 2023-10-16 06:16
Hi @PrincessBrozo,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-10-16 06:16 UTC
Labels: Issue: needs update, Reported on 2.3.7-p4
