### ISSUE TITLE
Cart Price rules without coupons are not processed when coupon is applied

### ISSUE THREAD

**Issue by hatimeria-artur-jewula** [magento/magento2#2931] opened 2016-01-08 12:38 UTC
I have stumbled on strange situation in Magento2. I have 2 cart price rules defined. First one has no conditions, no coupon, applied to all customer groups and websites, and grants 10% discount. This rule is successfully applied to cart after first item is added. I can see discount value set to 10%.

Example:
![cart-rule-1](https://cloud.githubusercontent.com/assets/16100846/12197883/50ea0e40-b60b-11e5-8acb-90bf0e1b24bd.png)

Now I have a second rule that uses specific coupon provided in rule and fixed discount of $5. When I enter the code into "Apply Discount Code" field I notice that it is being applied but the first one is not. Only coupon rule is being applied

![cart-rule-2](https://cloud.githubusercontent.com/assets/16100846/12197920/b387e73e-b60b-11e5-9be5-b276c77a046c.png)

Both rules have "Discard subsequent rules" set to no and no-coupon rule's priority is 0 whereas coupon rule's priority is 5. I would assume that both should be applied.

I dig into `Magento\SalesRule\Model\ResourceModel\Rule\Collection` class and found out that it produces the following query that fetches rules to check in method `setValidationFilter()`

```
SELECT `main_table`.*, `rule_coupons`.`code` FROM `salesrule` AS `main_table`
  INNER JOIN `salesrule_website` AS `website` ON website.website_id = '1' AND main_table.rule_id = website.rule_id
  INNER JOIN `salesrule_customer_group` AS `customer_group_ids` ON main_table.rule_id = customer_group_ids.rule_id AND customer_group_ids.customer_group_id = 0
  LEFT JOIN `salesrule_coupon` AS `rule_coupons` ON main_table.rule_id = rule_coupons.rule_id AND main_table.coupon_type != 1
WHERE (from_date is null or from_date <= '2016-01-08')
      AND (to_date is null or to_date >= '2016-01-08')
      AND (`is_active` = '1')
      AND (
        (
          main_table.coupon_type = 1
          OR (main_table.coupon_type = 3 AND rule_coupons.type = 0)
          OR (main_table.coupon_type = 2 AND main_table.use_auto_generation = 1 AND rule_coupons.type = 1)
          OR (main_table.coupon_type = 2 AND main_table.use_auto_generation = 0 AND rule_coupons.type = 0)
        )
        AND rule_coupons.code = 'ABC'
        AND (rule_coupons.expiration_date IS NULL OR rule_coupons.expiration_date >= '2016-01-08')
      )
      AND (`is_active` = '1') ORDER BY sort_order ASC;
```

The problematic line is `AND rule_coupons.code = 'ABC'` which removes all rules without coupons. I belive this should be set as `AND (rule_coupons.code = 'ABC' OR (main_table.coupon_type = 1))`

**Comment by mswaidan** [comment] 2016-03-23 13:27
I'm having this issue as well. @hatimeria-artur-jewula did the change to `AND (rule_coupons.code = 'ABC' OR (main_table.coupon_type = 1))` fix the issue for you?

**Comment by hatimeria-artur-jewula** [comment] 2016-03-23 19:02
My solution was in separate module in `di.xml` create preference for Rule\Collection 

```
<preference for="Magento\SalesRule\Model\ResourceModel\Rule\Collection" type="Module\SalesRule\Model\Resource\Rule\Collection" />
```

In the collection class I override `setValidationFilter` method in a way that I add line

```
$noCouponCondition = $connection->quoteInto(
                'main_table.coupon_type = ? ',
                \Magento\SalesRule\Model\Rule::COUPON_TYPE_NO_COUPON
            );
```

just before `$orWhereConditions` and change line 

```
$select->where('(' . $orWhereCondition . ') AND ' . $andWhereCondition);
```

to

```
$select->where($noCouponCondition . 'OR (' . $orWhereCondition . ') AND ' . $andWhereCondition);
```

**Comment by vkosenok** [comment] 2016-05-24 14:19
I have the same bug. Previous solution works fine for me. But probably we can fix it in bit more easier way.
Replace:
`$select->where('(' . $orWhereCondition . ') AND ' . $andWhereCondition);`
with:
`$select->where($orWhereCondition . ' OR (' . $andWhereCondition . ')');`

**Comment by Mulderua** [comment] 2016-06-15 15:59
Hi @hatimeria-artur-jewula, thank you for issue report! Internal ticket MAGETWO-54440 was created.

**Comment by heldchen** [comment] 2016-08-30 22:12
this seems still present in 2.1.1

**Comment by davepyro** [comment] 2016-09-30 13:41
Hi @hatimeria-artur-jewula
Would it be possible to give more info on your module as I am having a similar issue and need a fix for it?
thanks
Dave

**Comment by heldchen** [comment] 2016-09-30 13:55
@davepyro here's a patch: 
[bugfix-magetwo-54440-sales-rule-coupon-code-handling.zip](https://github.com/magento/magento2/files/503102/bugfix-magetwo-54440-sales-rule-coupon-code-handling.zip)

**Comment by davepyro** [comment] 2016-09-30 14:00
Great thanks

**Comment by plauge** [comment] 2016-11-18 12:39
@heldchen - Sorry, Im new to Mag2. How can I use your patch. I can see it's a .diff file.
Thanks!

**Comment by heldchen** [comment] 2016-11-18 12:41
you apply the diff file with a patch tool to your codebase...

**Comment by brizido** [comment] 2016-12-07 13:16
This is a very important fix - when is this getting incorporated in one of the future releases?

**Comment by josefbehr** [comment] 2016-12-12 13:48
> My solution was in separate module in di.xml create preference for Rule\Collection

Beware of the parent::_initSelect() line though. If you extend the original class to only overwrite that one method, it will throw an exception, if you keep it as is. Must be changed to be AbstractCollection::_initSelect(). And I second the question for an official fix. Is anyone even still assigned to the issue?

**Comment by bh-ref** [comment] 2016-12-22 15:10
seems to be fixed in CE 2.1.3, see also https://github.com/magento/magento2/issues/6294 & https://github.com/magento/magento2/commit/d66748032936d4f48c937343a9906fea8acdd132

**Comment by yosefkurniawan** [comment] 2017-02-22 05:37
Hi, seems cart price rules is still not working properly yet in Magento 2.1.3.
The amount of multiple discount seems correct already, in my case I use 2 cart price rule, one is without coupon, the other is with coupon. But in the totals block in the sidebar of shopping cart page, all discount (with and without coupon) are merged being one line. I expect they should be written one line per discount.
and also if I apply two discount (both without coupon), let say the first one is discount 10% and the second one is discount 50%, the system will only apply one of them. In my case the second one is applied. Does anyone hav the same experience with this in Magento 2.1.3?

**Comment by magento-engcom-team** [comment] 2017-10-12 11:30
@hatimeria-artur-jewula, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-12 11:30 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is not valid

**Comment by hatimeria-artur-jewula** [comment] 2017-10-12 11:57
Yes, this was fixed some time ago.
