### ISSUE TITLE
GraphQL mutation uptdateCartItems on configurable product with customizable options impossible

### ISSUE THREAD

**Issue by fkukus** [magento/magento2#31898] opened 2021-01-29 17:24 UTC
### Preconditions (*)

1. Magento 2.4.1
2. Setup with the Luma's sample data
3. Connect to the back office to edit an existing _configurable product_ (ie: WT08)
4. Add a new Customizable Option like this:
* Option Title: More information
* Option Type: Area
* Required: unchecked
* Price: 0.00
* Price Type: Fixed
* SKU: more-information
* Max Characters: 0
5. Use your preferred graphql tool to do the next steps
6. Create an anonymous cart
7. Add to your car the WT08 product, with required options (the configurable options: a color and a size), and with a value for the customizable option (by using the "entered_options" attributes)

### Steps to reproduce (*)

1. Try to update the value of your more-information option with the _updateCartItems_ mutation
For example:
```
mutation {
  updateCartItems(input: {
    cart_id: "4KQOhLgyLOXhyZGYFsUYlLvFQrKbh52d"
    cart_items: [
      {
        cart_item_id: 589
        customizable_options: [
          {
            id: 1980
            value_string: "I want to add more information on this field"
          }
        ]
        quantity: 1
      }
    ]
  }) {
    cart {...}
  }
}
```

### Expected result (*)

1. The cart item is updated with the new value for the _more-information_ customizable option
2. The order of the cart item remain unchanged into the cart

### Actual result (*)

1. The API response returns an error: "Could not update cart item: You need to choose options for your item."
![error_response](https://user-images.githubusercontent.com/51236618/106306475-6a9c2d00-625e-11eb-8070-418da48c6e6c.png)

Note that the update of the customizable option works fine if the cart item is a _simple product_ (execpt for the cart item order into the cart but it's another issue).

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by theshreyas** [comment] 2021-05-06 10:48
same with bundle product. I have raised the issue [here](https://github.com/magento/magento2/issues/32834)

**Comment by engcom-November** [comment] 2021-12-31 10:09
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2021-12-31 11:45
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue:
Edited the Configurable Product as per mentioned steps and added product to Cart using GraphQL mutation.
Ran updateCartItems mutation with below request and response retrieved as expected - No issue
@fkukus kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
![image](https://user-images.githubusercontent.com/60198231/147821265-1edd04c4-c589-4de4-b97a-dd265b3474be.png)
Thank you.

**Comment by fkukus** [comment] 2022-01-03 08:29
Thank you @engcom-November for the check, I will test again with the 2.4 and get back here.

**Comment by engcom-November** [comment] 2022-01-19 06:06
Hi @fkukus ,
We are closing this issue as there has been no latest on the same.
Thank you.

**Closed as completed by engcom-November** 2022-01-19 06:06 UTC
Labels: Issue:  Cannot Reproduce, Progress: dev in progress, Project: GraphQL, Issue: needs update
