### ISSUE TITLE
After updation Magento 2 to 2.3 file validation failed while uploading images in proucts and some products not appear on front end. 

### ISSUE THREAD

**Issue by rahulvrm16** [magento/magento2#24695] opened 2019-09-23 08:31 UTC
After updating magento 2 to 2.3 some products not visible on front end but visible in backend and I am not able to upload images in products section.

**Comment by rahulvrm16** [comment] 2019-09-23 11:07
I am new to github

**Comment by hostep** [comment] 2019-09-23 18:25
This sounds like a duplicate of https://github.com/magento/magento2/issues/16531 & https://github.com/magento/magento2/issues/24332

@rahulvrm16: for a quick fix, I would suggest you install the php extension `fileinfo`.

A proper fix for the issue is being worked at https://github.com/magento/magento2/pull/24455

**Closed as completed by hostep** 2019-09-23 18:25 UTC
Labels: Issue: Format is not valid

**Comment by rahulvrm16** [comment] 2019-09-24 07:02
Thank you @hostep.  How to install phpfileinfo extension ?

**Comment by hostep** [comment] 2019-09-24 07:14
@rahulvrm16: I would suggest you use some search engine and try to figure it out for your situation. It all depends on how your php is installed and what packages are available. There are too many ways to do this for me to be able to list them all.
If this is on a server which a hosting company maintains for you, you could ask them to install it.

Good luck! 🙂

**Comment by rahulvrm16** [comment] 2019-09-24 07:15
@hostep Thank you

**Comment by rahulvrm16** [comment] 2019-09-24 07:16
@hostep and also some products not appear on front end but visible in backend.
