### ISSUE TITLE
After upgrading to 2.2, Varnish did not export the default grace period

### ISSUE THREAD

**Issue by andrewhowdencom** [magento/magento2#11693] opened 2017-10-24 14:08 UTC
### Preconditions

1. Magento 2.2
2. Varnish 4/5

### Steps to reproduce

1. Have a 2.1 store
2. Upgrade to 2.2
3. Regenerate the VLC
4. Install the VCL

### Expected result

1. The VCL works

### Actual result

1. Varnish failed to load

Specifically, the `grace_period` variable in the template wasn't filled. It would appear the system configuration defaults are not being loaded -- once the grace period was supplied as part of system configuration, the grace period worked as anticipated.

It was verified that it should have fallen back to the defaults (and not just used a blank value) by verifying that the path `system/full_page_cache/varnish/grace_period` did not exist in `core_config_data` prior to setting the system configuration, and noting that the record did appear once set, and was the last record inserted (as determined by the autoincrement ID)

**Comment by andrewhowdencom** [comment] 2017-10-24 14:08
I am unsure whether this effects 2.2 default. I have only budget to upgrade thee current stack ^^

**Comment by TomashKhamlai** [comment] 2018-12-18 13:21
Magento 2.3.0 has been released! The problem is fixed there and for this reason we are closing this issue.

**Closed as completed by TomashKhamlai** 2018-12-18 13:21 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Fixed in 2.3.x, Issue: Format is valid
