### ISSUE TITLE
Cannot change intermediate custom status in admin using add comment form

### ISSUE THREAD

**Issue by zakdma** [magento/magento2#38917] opened 2024-07-11 19:04 UTC
### Preconditions and environment

- Magento version 2.4.7-p1 (latest)

### Steps to reproduce

1. Install vanilla Magento
2. Go to admin Stores => Order Status
3. Create two statuses "Sent" and "Ready for Pickup" and bind them to "Processing" state
4. Create product and register customer
5. Place order on front using this product and customer and default shipping and payment methods
6. Go to admin Sales => Orders
7. Open previously placed order
8. Create invoice by clicking Invoice button on top
9. See order changed status to "Processing"
10. Go to "Add Comment" form change status to "Sent" and add any comment
11. Reload order form and see status changed to "Sent"
12. Go to "Add Comment" form again and change status to "Ready for Pickup" and add any comment
13. Reload order form

### Expected result

See status is changed to "Ready for Pickup"

### Actual result

See status is still "Sent"

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-07-12 06:00
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-07-12 07:11
Hi @zakdma,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is reproducible.Kindly refer the attached video.


**Steps to reproduce**

- Install vanilla Magento
- Go to admin Stores => Order Status
- Create two statuses "Sent" and "Ready for Pickup" and bind them to "Processing" state
- Create product and register customer
- Place order on front using this product and customer and default shipping and payment methods
- Go to admin Sales => Orders
- Open previously placed order
- Create invoice by clicking Invoice button on top
- See order changed status to "Processing"
- Go to "Add Comment" form change status to "Sent" and add any comment
- Reload order form and see status changed to "Sent"
- Go to "Add Comment" form again and change status to "Ready for Pickup" and add any comment
- Reload order form



https://github.com/user-attachments/assets/44b40e2a-9256-426d-ac9e-0ae0d43e422d






The Status is still in sent state.

Hence Confirming the issue.

Thanks.

**Comment by simonmaass** [comment] 2024-07-16 08:01
i guess this was why: https://github.com/magento/magento2/issues/36562

**Comment by engcom-Bravo** [comment] 2024-09-03 06:45
@magento give me 2.4-develop instance

**Comment by hostep** [comment] 2024-09-11 20:40
Possibly fixed by https://github.com/magento/magento2/commit/18dee3d979ed8ee68a44324e892e6b7f570c987c?

**Comment by engcom-Bravo** [comment] 2024-09-13 05:52
@hostep Thanks for your Contribution!!.

Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket ACP2E-3178 by the internal team
Related commits: https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-3178&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta1.

Thanks

**Closed as completed by engcom-Bravo** 2024-09-13 05:52 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done, Component: order status, Issue: ready for confirmation, Area: Order, Reported on 2.4.7-p1

**Comment by hostep** [comment] 2024-09-13 09:39
Thanks for confirming @engcom-Bravo, can you also close https://github.com/magento/magento2/issues/38659, which is a duplicate of this issue here? Thanks!

**Comment by simonmaass** [comment] 2024-09-13 09:46
great - so will have this fix in april 2025!
