### ISSUE TITLE
Indexer Error: Item (Magento\CatalogInventory\Model\Stock\Status) with the same ID  already exists.

### ISSUE THREAD

**Issue by alex-james** [magento/magento2#25486] opened 2019-11-06 10:14 UTC
### Preconditions (*)
This issue is spotted in Magento 2.3.1 with PHP 7.2.14 but specifically with magento/module-catalog-search 101.0.3 (it is not seen in 101.0.0) running a multi-site installation.
1. When Magento has multiple stock locations (multiple entires in cataloginventory_stock)
2. And the same product exists in more than one stock location (multiple entries for the same product_id in cataloginventory_stock_status)

### Steps to reproduce (*)
1. Run the cron scheduler from the command line "php bin/magento cron:run"

### Expected result (*)
1. The result in the cron_schedule table for the "indexer_reindex_all_invalid" and "indexer_update_all_views" cron jobs should show a status of success and no error message

### Actual result (*)
1. The cron_schedule entry has a status of error along with the message:

> Item (Magento\CatalogInventory\Model\Stock\Status) with the same ID <product_id> already exists.

The issue is caused by the Magento\CatalogSearch\Model\Indexer\Plugin\StockedProductsFilterPlugin plugin introduced between 101.0.0 and 101.0.3, the fix is to add an additional criteria to the stock status criteria to filter based on storeId thereby preventing multiple matches being returned in Magento\Framework\Data\AbstractSearchResult

So immediately after the line 
`$stockStatusCriteria->setProductsFilter($productIds);`

insert the line:
`$stockStatusCriteria->setScopeFilter($storeId);`

**Comment by alex-james** [comment] 2019-11-06 10:15
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-06 10:15
Hi @alex-james. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-06 10:16
Hi @alex-james, here is your [Magento instance](https://i-25486-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25486-2-3-develop.instances.magento-community.engineering/admin](https://i-25486-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment] 2019-11-19 11:30
Hello @alex-james 

We are not able to reproduce this issue on the Magento 2.3.3

**Testing scenario:**

1. Create second website, stock & source and merge it together
![image](https://user-images.githubusercontent.com/51680850/69143136-fd74ff80-0ad0-11ea-9237-e883ddd12d3a.png)

2. Create product and assign it to all sources and websites
![image](https://user-images.githubusercontent.com/51680850/69143013-aec76580-0ad0-11ea-9c0a-99adacdf092e.png)
3. Run bin/magento cron:run & check values of `indexer_reindex_all_invalid` and `indexer_update_all_views`  in the `cron_schedule` table

**Result:**
The result in the `cron_schedule` table for the `indexer_reindex_all_invalid` and `indexer_update_all_views` cron jobs show a status of success and no error message
![image](https://user-images.githubusercontent.com/51680850/69142552-bd614d00-0acf-11ea-8bd1-614168cfea0c.png)

![image](https://user-images.githubusercontent.com/51680850/69142531-ad496d80-0acf-11ea-9ddb-dea05671a78a.png)

So i have to close this issue.

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-11-19 11:30 UTC
Labels: Issue: Format is valid

**Comment by salmanazeez786** [comment] 2019-12-18 09:57
This issue persists in 2.3.3 and it occurs when we have upgraded from 2.1.x to 2.3.3 also along with mcom-connector installed.

Indeed adding $stockStatusCriteria->setScopeFilter($storeId);   right after
 $stockStatusCriteria->setProductsFilter($productIds);  in \Magento\CatalogSearch\Model\Indexer\Plugin\StockedProductsFilterPlugin::beforePrepareProductIndex  will solve the issue but setScopeFilter() will set the website_id and $storeId

We will have to investigate more on this before using this as solution

@alex-james

**Comment by alex-james** [comment] 2019-12-18 10:21
Thanks @salmanazeez786 it didn't stop the issue being closed without being properly looked at though <sigh>

**Comment by kaushalsutharoc** [comment] 2019-12-18 11:16
I'm also getting the same error with Magento 2.3.3

`report.CRITICAL: Item (Magento\CatalogInventory\Model\Stock\Status) with the same ID "371335" already exists. {"exception":"[object] (Exception(code: 0): Item (Magento\\CatalogInventory\\Model\\Stock\\Status) with the same ID \"371335\" already exists. at /vendor/magento/framework/Data/AbstractSearchResult.php:269)"} []`

`SELECT * FROM `cataloginventory_stock_status` WHERE `product_id` = 371335`

```
[
    {
        "product_id": "371335",
        "website_id": "1",
        "stock_id": "1",
        "qty": "0.0000",
        "stock_status": "0"
    },
    {
        "product_id": "371335",
        "website_id": "2",
        "stock_id": "1",
        "qty": "0.0000",
        "stock_status": "0"
    },
    {
        "product_id": "371335",
        "website_id": "5",
        "stock_id": "1",
        "qty": "0.0000",
        "stock_status": "0"
    },
    {
        "product_id": "371335",
        "website_id": "8",
        "stock_id": "1",
        "qty": "0.0000",
        "stock_status": "0"
    }
]
```

**Comment by alex-james** [comment] 2019-12-18 11:18
Thanks @kaushalsutharoc it's a real shame it wasn't properly investigated when I raised it <sigh>

**Comment by salmanazeez786** [comment] 2019-12-18 12:14
@alex-james  

As the scope filter is setting website_id , I have updated the code as below :

```
     /**
     * Filter out of stock options for configurable product.
     *
     * @param DataProvider $dataProvider
     * @param array $indexData
     * @param array $productData
     * @param int $storeId
     * @return array
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function beforePrepareProductIndex(
        DataProvider $dataProvider,
        array $indexData,
        array $productData,
        int $storeId
    ): array {
        if (!$this->stockConfiguration->isShowOutOfStock($storeId)) {
            $productIds = array_keys($indexData);
            $websiteId = $this->getWebsiteId($storeId);
            $stockStatusCriteria = $this->stockStatusCriteriaFactory->create();
            $stockStatusCriteria->setProductsFilter($productIds);
            $stockStatusCriteria->setScopeFilter($websiteId);
            $stockStatusCollection = $this->stockStatusRepository->getList($stockStatusCriteria);
            $stockStatuses = $stockStatusCollection->getItems();
            $stockStatuses = array_filter(
                $stockStatuses,
                function (StockStatusInterface $stockStatus) {
                    return StockStatusInterface::STATUS_IN_STOCK == $stockStatus->getStockStatus();
                }
            );
            $indexData = array_intersect_key($indexData, $stockStatuses);
        }

        return [
            $indexData,
            $productData,
            $storeId,
        ];
    }

    /**
     * Get websiteId by storeId
     *
     * @param int $storeId
     * @return int
     * @throws \Magento\Framework\Exception\NoSuchEntityException
     */
    private function getWebsiteId(int $storeId): int
    {
        return $this->storeManager->getStore($storeId)->getWebsiteId();
    }
```

**Comment by doublesharp** [comment] 2020-06-09 18:04
@engcom-Charlie - I am also having this issue with Magento 2.3.4. The test that you ran to reproduce the issue would not have exposed the issue as the cron job status is "pending" in your screenshot. You also need to set `Configuration > Catalog > Inventory > Stock Options > Display Out of Stock Products` to "No", the code is skipped otherwise.

To reproduce the issue reset the search indexer and then try to reindex and you will see the error.

![image](https://user-images.githubusercontent.com/571472/84183517-e08a2480-aa40-11ea-9f6b-ac05e1ae7179.png)

```
magento indexer:reset
magento indexer:reindex
```
>`Catalog Search indexer process unknown error:
Item (Magento\CatalogInventory\Model\Stock\Status) with the same ID "1" already exists.`

The code that @salmanazeez786 is functionally the same that I came up with to fix the issue in my install.
```
use Magento\Store\Model\StoreManagerInterface;

// ...inject $this->storeManager in constructor...

// get the website id for this store id
$websiteId = $this->storeManager->getStore($storeId)->getWebsiteId();
// get stocks status for this website
$stockStatusCriteria->setScopeFilter($websiteId);
```

After adding this code I can reindex as expected and the front end search returns products as expected. The index is also a lot slower than with the setting set to "Yes" to show out of stock items as it does not check the stock status during reindex.

>`Catalog Search index has been rebuilt successfully in 00:00:05`

**Comment by nmarquev** [comment] 2022-12-16 21:23
Same problem on magento 2.4.2-p1
I can´t use "Display Out of Stock Products" becasue of business rules, any tip or fix ?
