### ISSUE TITLE
Error 500 CSP

### ISSUE THREAD

**Issue by marctbb** [magento/magento2#39192] opened 2024-09-20 10:05 UTC
### Preconditions and environment

- Magento version: 2.4.7
- Community version
- Php version 8.3

### Steps to reproduce

I'am currently managing a Magento 2.4.7 instance on an **Apache server**, and we have encountered issues related to Content Security Policies (CSP) after updates and the installation of third-party plugins. The problem manifests as CSP errors in the console, which we have addressed by adding specific directives to our custom whitelist located in app/code. Additionally, these third-party plugins have added their own CSP rules in their respective whitelists.

Over time, we’ve cleaned our custom whitelist to remove directives already included by the third-party plugins. However, we’ve now reached a point where we cannot reduce the whitelist further, as the remaining entries in our custom CSP whitelist are unique across the codebase. Removing them would result in console CSP errors.

The core issue is that Apache imposes a limit on the number of CSP directives. When this limit is exceeded, we encounter 500 server errors, rendering both the frontend and backend of Magento unusable.

It is possible to remove csp in the whitelists of third party plugins and thus reduce the number of csp and therefore the frontend and backend are shown. But this means that there is a possibility of errors appearing in the console and having the problem in future updates.

It should be noted that it is only reproducible if the Magento is on a server, it does not work on localhost.

### Expected result

The expected result is that magento will detect the csp's that are added to the head and if it finds that they are duplicated in several whitelists it will only add or use one of those.
With this you would be able to see both the forntend and the backend without any problem.

### Actual result

The current result is as I said, we get error 500 in both the frontend and the backend and it is not possible to work.
Is there a way for magento to handle csp correctly?

### Additional information

I found this, maybe it helps to understand the issue:
https://konkretor.com/2022/07/07/apache-ah01070-error-parsing-script-headers/

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2024-10-08 08:41
Hello @marctbb,

Thanks for the report and collaboration!

We have tried to reproduce the issue in the latest development i.e. 2.4-develop, and Magento has already removed the duplicated CSPs from the header from different modules/extensions. To reproduce the issue we have followed the below steps:

1. Create 2 custom modules.
2. Add `csp_whitelist.xml` in both the modules.
3. Add some duplicated and unique CSPs in both `csp_whitelist.xml`
4. Enable modules and run `bin/magento s:up`
5. After loading the page, it shows only the unique CSP in the response header.

It seems the issue is with the Apache's header limit, and not with the Magento core.

Let us know if we missed anything.

Thanks

**Comment by hostep** [comment] 2024-10-10 16:53
You could also give https://github.com/basecom/magento2-csp-split-header/ a try, to see if that module improves the situation

**Comment by engcom-Hotel** [comment] 2024-10-21 10:46
Dear @marctbb,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we're assuming it's been resolved and will be closing it. Feel free to open a new ticket or reopen this one if you require further assistance.

Regards

**Closed as completed by engcom-Hotel** 2024-10-21 10:46 UTC
Labels: Triage: Dev.Experience, Component: Csp, Issue: needs update, Area: Framework, Reported on 2.4.7
