### ISSUE TITLE
Custom Options do not affect 'price' and 'final_price' in the Price Indexer

### ISSUE THREAD

**Issue by zhovnirigor** [magento/magento2#36686] opened 2022-12-30 10:53 UTC
### Preconditions and environment

- Magento 2.4.5-p1, Magento 2.4.3
- Default setup (either with sample data or not)

### Steps to reproduce

1. Go to admin panel, add simple/virtual/downloadable product.
2. Set price to the value X (for example, 10).
![изображение](https://user-images.githubusercontent.com/23097634/210062100-a1bbb462-893b-44c0-a804-0151d3f0f78a.png)
3. In the Customizable Options tab create a single Required option with the Option Type = Radio Buttons .
4. Add a value to the option above with the price Y (for example, 25) and Price Type = Fixed.
5. Add another value to the option above with the price Z (for example, 30) and Price Type = Fixed.
![изображение](https://user-images.githubusercontent.com/23097634/210062141-dc77ceba-2b96-49ba-b164-578b1ac814f0.png)
6. Save the product.

### Expected result

1. In the catalog_product_index_price table the product has a price of X+Y (for example, 10+25=35), final_price of X+Y (for example, 10+25=35), min_price of X+Y (for example, 10+25=35), max_price of X+Z (for example, 10+30=40).
2. On the PLP product shows a price of X+Y (for example, 35).

### Actual result

1. In the catalog_product_index_price table the product has a price of X (for example, 10), final_price of X (for example, 10), min_price of X+Y (for example, 10+25=35), max_price of X+Z (for example, 10+30 = 40). In short, min_price > price and min_price > final_price. It should not be a case for simple/virtual/downloadable product.
![изображение](https://user-images.githubusercontent.com/23097634/210062286-e92b832b-be3e-45cd-915a-84ce2badd5f4.png)
2. On the PLP product shows a price of X (for example, 10). It is incorrect since the product cannot be bought by this price.
![изображение](https://user-images.githubusercontent.com/23097634/210062175-6c60ec52-2d30-40ce-9d3d-00618707c254.png)

### Additional information

\Magento\Catalog\Model\ResourceModel\Product\Indexer\Price\CustomOptionPriceModifier::modifyPrice (and, in particular, \Magento\Catalog\Model\ResourceModel\Product\Indexer\Price\CustomOptionPriceModifier::getSelectForUpdate) work with min_price and max_price only. It doesn't modify the price or final_price.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-01-02 11:10
Hi @zhovnirigor,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.


**Steps to reproduce**

1.Go to admin panel, add simple/virtual/downloadable product.
2.Set price to the value X (for example, 10).
3.In the Customizable Options tab create a single Required option with the Option Type = Radio Buttons .
4.Add a value to the option above with the price Y (for example, 25) and Price Type = Fixed.
5.Add another value to the option above with the price Z (for example, 30) and Price Type = Fixed.
6.Save the product.


<img width="795" alt="Screenshot 2023-01-02 at 4 31 11 PM" src="https://user-images.githubusercontent.com/51680745/210222974-4c4ccad5-f1d0-4888-93fa-0b9af87c293b.png">



<img width="1340" alt="Screenshot 2023-01-02 at 4 31 04 PM" src="https://user-images.githubusercontent.com/51680745/210222992-a2fc213d-5bba-4a44-ae21-9c318eb42961.png">


<img width="919" alt="Screenshot 2023-01-02 at 4 21 28 PM" src="https://user-images.githubusercontent.com/51680745/210223015-5359db5f-d8d2-43fa-9886-c53bb22acfe0.png">
<img width="1016" alt="Screenshot 2023-01-02 at 1 28 38 PM" src="https://user-images.githubusercontent.com/51680745/210223021-63531a2b-b8f3-4442-8ea2-d43b25025608.png">


The custom option is something like an add-on feature where you customize your product and if you are having to add the price for the custom option then it will include in your product.Price of the custom options will be added to final price of product.

Although the final price of the product will be 10.we can buy the product without custom options.


Please let us know we miss anything.

Thanks.

**Comment by zhovnirigor** [comment] 2023-01-02 11:13
Thanks for the testing.

Mistake is that the option is not Required (see p. 3 from Steps to Reproduce + screenshot).

Thanks!

**Comment by engcom-Bravo** [comment] 2023-01-02 11:17
Hi @zhovnirigor,

Thanks for your update.

we have updated screenshot.

Thanks.

**Comment by zhovnirigor** [comment] 2023-01-02 11:20
> Although the final price of the product will be 10.we can buy the product without custom options.
Product cannot be bought without **required** custom option.
Thanks.

**Comment by engcom-Bravo** [comment] 2023-01-09 12:47
Hi @zhovnirigor,

Thanks for your update.

Custom option is something like customer choice.if we have multiple custom options it is difficult to predict final price of product because customer choose any one of custom option so in that case we have min price and max price of the product, it includes original price of the product.`min_price` includes least price of custom option and `max_price` includes highest price of custom option of the product.Both adds original price of the product.

In product page we need to select the custom option after that it reflects in the price.


<img width="814" alt="Screenshot 2023-01-09 at 6 11 53 PM" src="https://user-images.githubusercontent.com/51680745/211310500-4a755232-95e8-4e47-885f-cf770b193341.png">




<img width="1192" alt="Screenshot 2023-01-09 at 6 11 39 PM" src="https://user-images.githubusercontent.com/51680745/211310527-2e965cad-3bf0-4521-8895-d909163fd369.png">



Thanks.

**Comment by engcom-Bravo** [comment] 2023-01-24 09:13
Hi @zhovnirigor,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-01-24 09:13 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1
