### ISSUE TITLE
reindexList does not use batch processing

### ISSUE THREAD

**Issue by dmanners** [magento/magento2#25507] opened 2019-11-07 11:24 UTC
### Preconditions (*)

1. Magento Version 2.2.5
1. 4000 products,
1. 41 stores
1. 42 store groups,
1. 6 websites,

### Steps to reproduce (*)

1. Programatically reindex a limited set of products with the following,

```
$productIndexer = $this->indexerRegistry->get(\Magento\Catalog\Model\Indexer\Product\Eav\Processor::INDEXER_ID);
$category = $this->categoryRepository->get(
    $categoryId,
    $storeId
);
$productCollection = $category->getProductCollection();
$productIds = $productCollection->getAllIds();
$productIndexer->reindexList($productIds);
```

### Expected result (*)

1. Reindex to be successfully completed,

### Actual result (*)

1. Error given: `The table 'catalog_product_index_eav_temp' is full`

After diving into the issue I noticed that calling `$productIndexer->reindexAll();` does not have this problem. It looks like the built in batch processing only happens when reindexing all products and not a sub set.

For full indexing see: https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Catalog/Model/Indexer/Product/Eav/Action/Full.php#L112
For partial indexing see: https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Catalog/Model/Indexer/Product/Eav/Action/Rows.php#L21

For our case I have added our own batch processing around the `reindexList` call but I wonder if this is something that should be taken over by the Magento index batching that already gets used.

**Comment by dmanners** [comment] 2019-11-07 11:32
There is a similar closed issue but around the reindexAll method and an older version of Magento: https://github.com/magento/magento2/issues/6415

**Comment by dmanners** [comment] 2019-11-07 11:39
If it turns out that it should be batched in the same way that the reindexAll is batched then I would be happy to take this on as contribution with some input and direction from the arch team.

**Comment by engcom-Charlie** [comment] 2019-12-02 10:01
Hello @dmanners 
We are not able to reproduce this issue on the latest 2.3-develop branch by provided steps.

**Code used:**
```
$categoryId = 3;
$storeId = 1;
$objectManager = Magento\Framework\App\ObjectManager::getInstance();
$indexerRegistry = $objectManager->get('Magento\Framework\Indexer\IndexerRegistry');
$productIndexer = $indexerRegistry->get(\Magento\Catalog\Model\Indexer\Product\Eav\Processor::INDEXER_ID);
$categoryRepository = $objectManager->get('\Magento\Catalog\Model\CategoryRepository');
$category = $categoryRepository->get(
    $categoryId,
    $storeId
);
$productCollection = $category->getProductCollection();

$productIds = $productCollection->getAllIds();

$productIndexer->reindexList($productIds);
```
**Result:**
Re-index to be successfully completed without any errors or exceptions.

![image](https://user-images.githubusercontent.com/51680850/69949586-79703e00-14fa-11ea-9049-b7a58b5ce461.png)

We are closing this issue due to branch `2.2-develop` was closed and
> Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-12-02 10:01 UTC
Labels: Issue: Format is valid, Triage: Dev.Experience
