### ISSUE TITLE
Incorrect calculation of qty_refunded for simple of configurable order item

### ISSUE THREAD

**Issue by oleksii-lisovyi** [magento/magento2#11799] opened 2017-10-27 09:08 UTC
### Preconditions
1. Magento 2.1.

### Steps to reproduce
1. Place an order with configurable product with qty 5 (> 2).
2. Go to Admin panel -> Sales -> Orders.
3. Open the placed order.
4. Invoice an order (optional, depends on payment method).
5. Click on "Credit Memo" button.
6. On the "New Memo" page fill "Qty to Refund" with 2 (> 1).
7. Refund item.
8. Click on "Credit Memo" button (again).
9. On the "New Memo" page fill "Qty to Refund" with 2.
10. Refund item.

### Expected result
Values stored in the `sales_order_item`.`qty_refunded` (and `sales_creditmemo_item`.`qty`) field:
1. after step 7:

Configurable | Simple
 ------------ | -------------
2 | 2

2. after step 10:

Configurable | Simple
 ------------ | -------------
4 | 4

### Actual result
Values stored in the `sales_order_item`.`qty_refunded` (and `sales_creditmemo_item`.`qty`) field:
1. after step 7:

Configurable | Simple
 ------------ | -------------
2 | 1 :exclamation:

2. after step 10:

Configurable | Simple
 ------------ | -------------
4 | 2 :exclamation:

So in case of refunding configurable order item there is always refunded simple item with qty = 1.
I found, where is the qty filled for simple order item:
```php
/**
 * @see \Magento\Sales\Model\Order\CreditmemoFactory::createByOrder
 */
...
$item = $this->convertor->itemToCreditmemoItem($orderItem);
if ($orderItem->isDummy()) {
    $qty = 1; // THIS FLOW IS DONE FOR SIMPLE ITEM
    $orderItem->setLockedDoShip(true);
} else {
    if (isset($qtys[$orderItem->getId()])) {
        $qty = (double)$qtys[$orderItem->getId()];
    } elseif (!count($qtys)) {
        $qty = $orderItem->getQtyToRefund();
    } else {
        continue;
    }
}
$totalQty += $qty;
$item->setQty($qty);
$creditmemo->addItem($item);
...
```
As a result while processing each of credit memo items there is adding +1 to the `qty_refunded` for simple order item:
```php
/**
 * @see \Magento\Sales\Model\Order\Creditmemo\Item::register
 */
$qty = $this->processQty();
$orderItem->setQtyRefunded($orderItem->getQtyRefunded() + $qty);
```

**Comment by magento-engcom-team** [comment] 2017-10-27 11:46
@oleksii-lisovyi, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-27 11:46 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
