### ISSUE TITLE
Something went wrong with processing the default view and we have restored the filter to its original state. Backend in Sales/orders Magento 2.3.5p1 

### ISSUE THREAD

**Issue by Velbro** [magento/magento2#35943] opened 2022-08-13 22:05 UTC
### Preconditions and environment

- Magento version 2.3.5p1
![sales-orders-error message](https://user-images.githubusercontent.com/111089661/184511902-0dc26030-5d32-4fad-ab94-3e126f1b9e00.jpg)

Orders no charge in backend because this error "Something went wrong with processing the default view and we have restored the filter to its original state."
-I tryed some posible solutions as: truncate data from ui_bookmark (no work for me)
-Looking to expand size admin session and no found that option in backend.... Please any suggestion?

### Steps to reproduce

-Backend
-Sales
-Orders

### Expected result

Orders displayed after purcharses

### Actual result

Something went wrong with processing the default view and we have restored the filter to its original state.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-08-16 09:15
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-08-16 12:12
Hi @Velbro,


Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue.

We are able to see the Orders List.

<img width="936" alt="orders" src="https://user-images.githubusercontent.com/51680745/184876520-a069b288-6a7a-45aa-9d98-38b090d6a7e2.png">



Thanks.

**Comment by sprajapat770** [comment] 2022-08-17 10:06
@engcom-Bravo  this is actually a permission bug you can also generate, follow the steps please.

Way to Generate: 
1. create a new user role in admin and assign custom permission.
  - sales order
  - sales shipment 
  - do not assign invoice and credit memos permission
 2. log in magento admin using newly created account.
 3. open sales order grid
 4. then open any recent order and you will see this error popups 2 times due to invoice and credit memo grid are not permitted to show.
 
if you still face issue then let me know i will create a video for or do you have any other procedure to lead this issue then let me know that as well.

Thanks

**Comment by engcom-Bravo** [comment] 2022-08-30 05:20
Hi @Velbro,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by engcom-Bravo** [comment] 2022-09-01 07:08
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-09-01 11:46
Hi @sprajapat770,


Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch.



Steps Followed:

 1.create a new user role in admin and assign custom permission.
    a.sales order
    b.sales shipment
    c.do not assign invoice and credit memos permission
 2.log in magento admin using newly created account.
 3.open sales order grid
 4.Then open any recent order.

Kindly refer screenshots.


<img width="934" alt="kumar" src="https://user-images.githubusercontent.com/51680745/187905959-b049d3d0-b94d-4c75-8029-f44f199a9630.png">



<img width="922" alt="kumar 1" src="https://user-images.githubusercontent.com/51680745/187906030-3c1be1b7-2365-42ff-925c-30ac4a644bc5.png">



In recent order we will not see any error popups.



Let us Know we miss anything.


Thanks.

**Comment by engcom-Bravo** [comment] 2022-09-19 05:05
Hi @Velbro,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.


Thanks.

**Closed as completed by engcom-Bravo** 2022-09-19 05:05 UTC
Labels: Issue: needs update

**Comment by FadedOut** [comment] 2022-12-21 22:44
Posting this here too just in case anyone comes across this problem (as I have seen many have - yet no one has found a solution)

A possible fix was found by this member here:
https://github.com/magento/magento2/issues/35759

With the actual file to modify:
https://github.com/magento/magento2/issues/35759#issuecomment-1361023670

It has to do with Magento making UI calls using GET instead of POST (which is what it should be doing - using POST) and it causes the URI to be over 8k characters long and throws a 414 error in dev tools. If you see a 414 error in dev tools, this solution will probably work for you. Hopefully it does anyway as the Magento "staff" don't seem to have a clue on how to actually help merchants with this problem (and it IS a real problem).
