### ISSUE TITLE
Configurable Product's normal price is not visible on Product Catalog

### ISSUE THREAD

**Issue by drpit** [magento/magento2#12183] opened 2017-11-10 20:04 UTC
### Preconditions

1. Clean install of Magento 2.4 with sample data
2. PHP 7.3
3. Apache 2.4
4. Ubuntu 18.04

### Steps to reproduce

1. Select all child products of a configurable one. 
2. Update Special price, Special price from and special price to
3. Check frontend 

### Expected result

1.  Especially for Configurable products which have the same price for all child products (e.g. a t-shirt with various colours) at the product catalog I should see the normal price (strike through) and the special price in red.  Like the simple product
It should be obvious to the user that the product has an offer and not to have him enter select colour and size to see the offer and price deference.
2) In the product detail, the price you have to choose all the variation to see the normal price or just to notice that the product has an offer.

I guess that also for the configurable products the offers and discounts should be clear and not hidden under 2-3 clicks.

### Actual result
From the screenshots you can't realize which of the two product has an offer.
<img width="537" alt="screen shot 2017-11-10 at 22 00 44" src="https://user-images.githubusercontent.com/18048110/32676324-e2b2739e-c662-11e7-86e7-3ed45f33d366.png">
<img width="845" alt="screen shot 2017-11-10 at 22 00 56" src="https://user-images.githubusercontent.com/18048110/32676339-e9f88602-c662-11e7-8896-28250b9f8fac.png">

**Comment by magento-engcom-team** [comment] 2018-02-07 13:56
@drpit, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2018-10-13 06:32
Hi @jignesh26. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by krnshah** [comment] 2018-10-27 06:29
Hi @jignesh26 

I am also working on this issue. please let me know if you found anything.

**Comment by magento-engcom-team** [comment] 2018-11-24 05:58
Hi @krnshah. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by abhi-ranosys** [comment] 2019-05-04 05:51
I am working on this at #dmcdindia19

**Comment by magento-engcom-team** [comment] 2019-12-26 14:32
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30092` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment] 2024-09-11 10:37
Hi @drpit,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="1437" alt="Screenshot 2024-09-11 at 16 05 41" src="https://github.com/user-attachments/assets/4e49a92e-5384-41e6-8450-d46de68a62eb">


Special price was updated to the product.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-09-11 10:37 UTC
Labels: feature request, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Component: Pricing, Event: dmcdindia1, Reproduced on 2.4.x, Priority: P2, Severity: S2, Progress: done, Reported on 2.4.x
