### ISSUE TITLE
Product init core registration.

### ISSUE THREAD

**Issue by drew7721** [magento/magento2#19931] opened 2018-12-21 16:02 UTC
### Preconditions 
1. Magento version : 2.2.7 

### Steps to reproduce
1.  See https://github.com/magento/magento2/blob/a8097646c6f621964fa333262704bf38fe7c265c/app/code/Magento/Catalog/Helper/Product.php#L460
2. Note that an event is thrown after. That event will be used to probably alter the product data or add product data.

### Expected result 
1. The product should be saved in the registry after the event.

### Actual result 
1. the product is saved in the registry before the event, 

### Note:
I think it would be best to move the registration after the event is thrown, no? If changes are done to the product in the observer they will need to be once more saved in the registry. 

Not really an issue, but I ran into this and thought it would be an improvement.

Opinions?

**Comment by magento-engcom-team** [comment] 2018-12-21 16:02
Hi @drew7721. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@drew7721 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by ihor-sviziev** [comment] 2018-12-21 16:09
Hi @drew7721,
It's not an issue, as objects are passed by reference, so the same product will be in registry.

**Comment by magento-engcom-team** [comment] 2018-12-21 16:09
Hi @ihor-sviziev. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ihor-sviziev** [comment] 2018-12-21 16:16
@drew7721 I'll close this issue. If you have any questions - feel free to re-open it or just write comments here

**Closed as completed by ihor-sviziev** 2018-12-21 16:16 UTC
Labels: improvement, Component: Catalog, non-issue, Issue: Format is valid
