### ISSUE TITLE
[Reports] Refresh Reports Lifetime Statistics action redirects to 404

### ISSUE THREAD

**Issue by eduard13** [magento/magento2#20819] opened 2019-01-30 15:59 UTC
### Preconditions (*)

1. Magento 2.3-develop
2.

### Steps to reproduce (*)
1.  Open the backend 
2. Navigate to Reports / Refresh Statistics [Statistics]
3. Select several reports
4. Choose from the Action dropdown **Refresh Lifetime Statistics** 
5. Click Submit

### Expected result (*)

1. The lifetime statistic are updated.
![xnip2019-01-30_17-44-29](https://user-images.githubusercontent.com/15868188/51993114-e66c0f00-24b6-11e9-9b78-a0f91a13ac79.jpg)

### Actual result (*)

1. You're redirected to 404 page

**Comment by magento-engcom-team** [comment] 2019-01-30 15:59
Hi @eduard13. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@eduard13 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-30 15:59
Hi @dmytro-ch. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-01-30 16:00
@dmytro-ch Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97989` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dmytro-ch** [comment] 2019-01-30 16:03
I was able to reproduce the issue in *2.3-develop* branch.

![screen shot 2019-01-30 at 5 58 30 pm](https://user-images.githubusercontent.com/11693779/51994280-1caa8e00-24b9-11e9-8d63-e7ef71bc5adf.png)

Thank you!

**Comment by rakeshvarma90** [comment] 2019-02-03 06:14
#MM19IN

**Comment by magento-engcom-team** [comment] 2019-02-03 06:14
@rakeshvarma90 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment] 2019-02-03 06:14
Hi @rakeshvarma90. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by eduard13** [comment] 2019-02-03 07:14
@rakeshvarma90 what's the reason of working on this issue and adding the Event label, if it has already an opened PR?

**Comment by rakeshvarma90** [comment] 2019-02-03 08:08
@eduard13 sorry I am not aware of already opened PR

**Comment by magento-engcom-team** [comment] 2019-02-12 17:40
Hi @eduard13. Thank you for your report. 
The issue has been fixed in magento/magento2#20820 by @eduard13 in 2.3-develop branch
Related commit(s):
 - [fd28eb0d2c55ddd60f1bf174473311317bd1712f](https://github.com/magento/magento2/commit/fd28eb0d2c55ddd60f1bf174473311317bd1712f)
 - [8a276c1e9938b432b6122bfa62695bdfe048d6f9](https://github.com/magento/magento2/commit/8a276c1e9938b432b6122bfa62695bdfe048d6f9)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2019-02-12 17:40 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Progress: PR Created, Component: Reports
