### ISSUE TITLE
Locale\Format throws away country part, results in wrong number format for Switzerland

### ISSUE THREAD

**Issue by ktruehl** [magento/magento2#5073] opened 2016-06-17 08:33 UTC
In `Magento\Framework\Locale\Format` the `getPriceFormat()` method calls on `DataBundle` to return the `ResourceBundle` for a given locale. In `ResourceBundle` the `get()` method calls the `cleanLocale()` method with the given locale as parameter. The `cleanLocale()` method throws away the country part. This results in wrongly formated numbers for countries who share languages but not the number format with other major countries, such as Switzerland. The locale `de_CH` gets shortened to `de`. For the locale `de` the country `DE` (Germany) is implied. In Germany prices are formated as `#.##0,00`, whereas in the German-speaking part of Switzerland prices are formated as `#,##0.00`.

The country part is there for a reason! I had to stupidly patch the `cleanLocale()` method in the `ResourceBundle` class to check for Swiss locales, since I have no clue why the `cleanLocale()` method is there in the first place. Maybe there is a good reason, but I don't have the time to find out.

**Comment by andimov** [comment] 2016-06-22 11:49
To allow us research the issue, please, provide description according to the template.
Please, provide the used version also. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by ktruehl** [comment] 2016-06-27 13:01
@andimov 
The version is 2.0.7. I gave a description of where to find the relevant code lines and how and why the problem occurs. That should largely suffice. It's clear that if you cut out the country part from the locale `de_CH` you're left with `de`, which will default to `de_DE`. Germany and the swiss-speaking part of Switzerland have different number formats.

**Comment by ktruehl** [comment] 2016-06-28 12:48
Fine! It turns out, the `cleanLocale()` method is there for a reason. But that only means that Magento has a bigger problem than originally thought. Admittedly it will only touch a very small part of your customers. In any case, in case you're interested in further looking into this, here are the steps to reproduce the problem:
1. Install Magento 2.1 together with the demo data.
2. In the admin backend, change the following settings in the configuration section "General" -> "General" -> "Country Options":
   - Default Country: Switzerland
   - Allow Country: Switzerland
3. In the admin backend, change the following settings in the configuration section "General" -> "General" -> "Locale Options":
   - Timezone: Europe/Zurich
   - Locale: German (Switzerland)
   - Weight Unit: kgs
   - First Day of Week: Monday
   - Weekend Days: Saturday + Sunday
4. In the frontend, visit the detail page of a simple product. The price should be displayed with `,` as a decimal separator. However, in the german-speaking part of Switzerland the decimal separator should be `.`.

**Comment by SchumacherFM** [comment] 2016-08-01 16:59
We have the same annoying issue and created a hack, just an around Plugin: `aroundGetPriceFormat()` to force set the Swiss price format :-(

We're running M 2.1.0

**Comment by andimov** [comment] 2016-08-17 14:23
@ktruehl
I've created an internal ticket for this issue - MAGETWO-57070 and linked it to this one.

**Comment by heldchen** [comment] 2016-08-30 21:48
problem still present in 2.1.1

**Comment by ronnybremer** [comment] 2016-09-08 06:21
Confirmed, still exists in 2.1.1. Is there any timeline for a fix?

**Comment by bh-ref** [comment] 2017-02-20 14:21
This issue is still present in 2.1.4

**Comment by ewallkrishnaprakash** [comment] 2017-04-20 13:22
This issue is still exist in 2.1.5

**Comment by SchumacherFM** [comment] 2017-04-20 13:35
IMHO: There will be no fix at all for the 2.1 branch. It might be fixed in 2.2 as many other things.

**Comment by magento-engcom-team** [comment] 2017-09-20 22:20
@ktruehl, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:20 UTC
Labels: Issue: Ready for Work, bug report, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is not valid
