### ISSUE TITLE
executed 'php bin/magento setup:upgrade', the load is very high

### ISSUE THREAD

**Issue by fengdoudm** [magento/magento2#37442] opened 2023-04-28 08:27 UTC
### Preconditions and environment

- Magento versionc is 2.4.5-p1
![企业微信截图_16826673279717](https://user-images.githubusercontent.com/8956444/235094386-3b741574-3c7e-44ba-8714-a49e6e37d363.png)

The php process is performing the retrieval all the time when we execute 'php bin/magento setup:upgrade', i dont know what happened. BTW, there are many PHP-FPM processed.

### Steps to reproduce

![企业微信截图_16826685377615](https://user-images.githubusercontent.com/8956444/235094936-be7e3f05-850b-4530-9a7e-f7edb9d53da9.png)
added some functions, need to execute 'php bin/magento setup:upgrade', after that, cpu are 97%, load is 200+, very slow.
can anyone help me ? thanks.

### Expected result

expected to success!

### Actual result

the server is very slow with the load is 200+

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-04-28 09:17
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-04-28 13:01
Hi @fengdoudm,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


We have executed successfully `php bin/magento setup:upgrade`.



https://user-images.githubusercontent.com/51680745/235127156-1a848ad7-c227-46f9-9753-6834c931e252.mov





Kindly Provide exact steps to reproduce the issue.

Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.


Thanks.

**Comment by fengdoudm** [comment] 2023-04-29 09:19
@engcom-Bravo thank for your reply, let try on another server.

**Comment by onlinebizsoft** [comment] 2023-04-30 09:43
@fengdoudm @engcom-Bravo this issue is true. Magento QA could not reproduce the issue because the site needs to be under high traffic.

However in the deployment process, Magento also requires enabling maintainance mode which is not zero downtime deployment.

**Comment by onlinebizsoft** [comment] 2023-04-30 09:45
@hostep @ihor-sviziev you may have some ideas about the relation between DB load/PHP processes and zero-downtime deployment?

**Comment by hostep** [comment] 2023-04-30 15:53
Profiling tools or something like New Relic or going through all kinds of logs files could maybe help in figuring out the underlying problem.
Maybe also consider talking to the hosting company and try to figure it out with them together what goes wrong and if something can be optimised?

Also, in the first screenshot of @fengdoudm I'm noticing a lot of code that has to do with Unit Tests, which is really strange to see on a production environment?

**Comment by fengdoudm** [comment] 2023-04-30 18:56
> e
I turned on developer mode before, but i already turned off, it is now production mode.
Also, i found a problem, if developer mode was turned on before, even if it was closed, the redeployed static files are still very large.
BTW, i run 'php bin/magento deploy:mode:set production --skip-compilation' to restart production mode.

**Comment by fengdoudm** [comment] 2023-04-30 18:57
> Profiling tools or something like New Relic or going through all kinds of logs files could maybe help in figuring out the underlying problem. Maybe also consider talking to the hosting company and try to figure it out with them together what goes wrong and if something can be optimised?
> 
> Also, in the first screenshot of @fengdoudm I'm noticing a lot of code that has to do with Unit Tests, which is really strange to see on a production environment?

I turned on developer mode before, but i already turned off, it is now production mode.
Also, i found a problem, if developer mode was turned on before, even if it was closed, the redeployed static files are still very large.
BTW, i run 'php bin/magento deploy:mode:set production --skip-compilation' to restart production mode.

**Comment by onlinebizsoft** [comment] 2023-05-01 00:30
> Profiling tools or something like New Relic or going through all kinds of logs files could maybe help in figuring out the underlying problem. Maybe also consider talking to the hosting company and try to figure it out with them together what goes wrong and if something can be optimised?
> 
> Also, in the first screenshot of @fengdoudm I'm noticing a lot of code that has to do with Unit Tests, which is really strange to see on a production environment?

Yes it is wrong in his case but in general, higher db connection/php process during db upgrade without maintenance mode is natural?

**Comment by fengdoudm** [comment] 2023-05-01 06:39
> Yes it is wrong in his case but in general, higher db connection/php process during db upgrade without maintenance mode is natural?

The website will be down with maintenance mode, this is terrible. was there any solution with zero-downtime ?

**Comment by onlinebizsoft** [comment] 2023-05-01 07:02
> > Yes it is wrong in his case but in general, higher db connection/php process during db upgrade without maintenance mode is natural?
> 
> The website will be down with maintenance mode, this is terrible. was there any solution/architecture with zero-downtime ?

Just dont put the site on the maintenance mode like you did is the right way for zero downtime. However I do have same behavior with higher db connection/higher php-fpm processes as well.

**Comment by ameysar** [comment] 2023-08-31 13:23
Running **bin/magento** is slow first of all because Magento instantiate all existing commands. 
Why should we do it if we need to execute only specific one ? 
Second - some of the commands (for ex. InstallCommand) [load all available deployment config options](https://github.com/magento/magento2/blob/2.4.5/setup/src/Magento/Setup/Console/Command/InstallCommand.php#L153), which cause Magento to search such files in all project modules and it is done few times: [one](https://github.com/magento/magento2/blob/2.4.5/setup/src/Magento/Setup/Model/ConfigOptionsListCollector.php#L92) and [two](https://github.com/magento/magento2/blob/2.4.5/setup/src/Magento/Setup/Console/Command/InstallCommand.php#L320).

**Comment by ihor-sviziev** [comment] 2023-08-31 14:18
@ameysar We have a PR that going to fix instantiating of all commands, but it was never finalized to accept it https://github.com/magento/magento2/pull/29355

**Comment by engcom-Hotel** [comment] 2024-03-27 03:19
Hello @fengdoudm @onlinebizsoft,

I have gone through all the comments here, we need more information in order to process further with this issue. Can you please provide us the exact steps to reproduce apart from high traffic?

Thanks

**Comment by engcom-Hotel** [comment] 2024-04-19 05:54
Dear @fengdoudm,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we're assuming it's been resolved and will be closing it. Feel free to open a new ticket or reopen this one if you require further assistance.

Regards

**Closed as completed by engcom-Hotel** 2024-04-19 05:54 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.5-p1
