### ISSUE TITLE
Using p for htmlTag outputs incorrectly

### ISSUE THREAD

**Issue by chicgeek** [magento/magento2#3254] opened 2016-02-02 12:45 UTC
## Description

I have an XML file that creates a new container. It is using a `<p>` element, one of the valid element types for `htmlTag`. Using the `move` directive, I relocate `top.search` into this new element.
## XML source

The XML:

```
<?xml version="1.0"?>
<page>
    <body>
        <referenceContainer name="main.content">
            <container name="new.container" htmlTag="p" htmlClass="new-container" />
        </referenceContainer>
        <move element="top.search" destination="new.container" />
    </body>
</page>
```
## HTML output

Expected markup output:

```
<p class="new-container">
    <!-- top.search -->
</p>
```

Actual markup output:

```
<p class="new-container"></p>
<!-- top.search -->
<p></p>
```
## Notes
- This is on merchant_beta 8 on both our custom theme and Luma.
- This bug does _not_ occur with some of the other allowed elements I've tested, including `div` and `ul`. The block is nested in the new container as expected.
- [The docs](http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/layouts/xml-instructions.html#fedg_layout_xml-instruc_ex_cont) specify `Any valid HTML 5 tag` can be used for `htmlTag`, though _this is not the case currently_. This mismatch is partly covered in issue https://github.com/magento/magento2/issues/2549. M2 provides the error: `Html tag "aside" is forbidden for usage in containers. Consider to use one of the allowed: dd, div, dl, fieldset, main, header, footer, ol, p, section, table, tfoot, ul.`

**Comment by alankent** [comment] 2016-02-02 17:34
Just to be clear, if you only change `htmlTag="p"` with `htmlTag="div"` what is the output?

**Comment by chicgeek** [comment] 2016-02-03 11:35
The output is:

```
<div class="new-container">
    <!-- top.search -->
</div>
```

**Comment by alankent** [comment] 2016-02-04 22:05
I am going to leave that one for the engineers closer to the code base sorry. Did you try to repeat in M2 GA? Is the problem still there? I agree that looks strange.

**Comment by chicgeek** [comment] 2016-02-05 10:08
We're in the process of upgrading our project to GA. I'll check again when the upgrade is done and report back.

**Comment by mazhalai** [comment] 2016-03-29 19:14
Thank you we have created MAGETWO-51319 to investigate and fix.

**Comment by undefined-olha** [comment] 2016-04-08 09:33
Hello, @chicgeek !
Thank you for your interest in Magento.
According to [W3C](https://www.w3.org/TR/html401/struct/text.html#h-9.3.1) it is forbidden to using block elements in `<p>` tag. Search block in your case is a `<div>` and browser "tries" to render it in the right way. Please use `htmlTag="div"` or any other valid tag for your purpose.

**Comment by MomotenkoNatalia** [comment] 2016-04-08 09:41
@chicgeek Internal ticket was closed as "Not a bug". Feel free to reopen this issue If you have any additional comment.

**Closed as completed by MomotenkoNatalia** 2016-04-08 09:41 UTC

**Comment by chicgeek** [comment] 2016-04-08 09:43
@olgalytvynenko @MomotenkoNatalia : Is there now going to be internal ticket raised for this to update both the docs and the M2 error which implies `p` is supported?

**Comment by undefined-olha** [comment] 2016-04-08 11:53
@chicgeek, sorry, probably I was not clear enough. There is no problem in Magento and information on devdocs is correct. If you look in source of your page (in Chrome you can do it by pressing `ctr+U`) you will see something like this:

![magetwo-51319](https://cloud.githubusercontent.com/assets/15153675/14382632/e62d7ec8-fd97-11e5-9758-616886c7fa26.png)

So the block was rendered correctly. But placing `<div>` (or any other [block element](https://developer.mozilla.org/en/docs/Web/HTML/Block-level_elements)) in paragraph it's wrong because it was designed for text formatting. If you will create some block using xml which will contain something like `<span>Some</span>` and place that inside `htmlTag="p"` container the same way as you did, everything will be fine. I hope it helped.
Please fell free to ask if you have any questions.
