### ISSUE TITLE
Exporting From Admin Grid (UI Component) - Limited to 20 records

### ISSUE THREAD

**Issue by mttjohnson** [magento/magento2#2961] opened 2016-01-12 00:18 UTC
I ran into this initially while building my own Admin UI Component for a grid of a custom table. I had 1200 records in the table but the export button in the header of the grid would only end up exporting 20 records. I then tested this against some other grid that uses the new Admin UI Components where I had more than 20 records and it would still only export 20 records. Specifically it was only returning the first 20 records from the data source, and it was not affected by any changes to the per page selection, which page I was on, sort order of the grid, or selected records. If I applied a filter to the grid it would only give me the first 20 records of the filtered list.

Granted, it's possible I'm doing something wrong here, but this is not how I would expect the export of the grid to behave.

I set a break point on line [131 of ConvertToXml.php](https://github.com/magento/magento2/blob/2.0/app/code/Magento/Ui/Model/Export/ConvertToXml.php#L131) and extracted the SQL `$searchResult->getSelect()->__toString()` to find a limit of 20 put on the query.

**Comment by tigerx7** [comment] 2016-04-15 16:46
I too can verify this behavior as well. Any update on this? I've been trying to trace what's happening. From what I can tell, a new search collection is built for the export and the page size isn't being specified.

For example, on the ajax request that updates the grid, there's a paging[pageSize] and a paging[currrent] parameter that is passed. However, on the ajax request that initiates the export, there are no paging parameters.

**Comment by piotrekkaminski** [comment] 2016-05-11 03:56
Reproduction steps in https://github.com/magento/magento2/issues/4376

Tracked in internal issue MAGETWO-52673

**Comment by piotrekkaminski** [comment] 2016-05-13 18:39
This is already fixed in developer branch. Should be actually working properly in version 2.0.5.

**Closed as completed by piotrekkaminski** 2016-05-13 18:39 UTC
Labels: bug report

**Comment by Krapulat** [comment] 2016-05-17 10:38
@piotrekkaminski In 2.0.5 I have the same problem.

**Comment by degaray** [comment] 2016-05-27 20:19
Same on 2.0.6

**Comment by degaray** [comment] 2016-05-27 20:20
Anyone has a work around?

**Comment by NadiyaS** [comment] 2016-05-30 08:52
Hi,
this issue was also reported in #4666. 
Bug is already fixed and fix will be merged to develop branch in few days.

**Comment by prasantahatui** [comment] 2016-09-26 12:54
Hi 
This is due to page_size and current_page are set to 20 and 1. 
To solve this, follow the following step.
1.  Open vendor/magento/module-ui/Model/Export/ConvertToCsv.php
2.  Near line 60 commant the code `$searchResult = $component->getContext()->getDataProvider()->getSearchResult();`
3. Then add the following code
   `$dataProvider = $component->getContext()->getDataProvider();
   $dataProvider->setLimit(0, false);
   $searchResult = $dataProvider->getSearchResult();`
