### ISSUE TITLE
Magento 2 Rest Translations 

### ISSUE THREAD

**Issue by LuisFReis** [magento/magento2#10585] opened 2017-08-18 11:57 UTC
Can I put the translations of products and categories thru rest-api? 
Category name 
Product name 
Product description 
etc..

**Comment by orlangur** [comment] 2017-08-18 12:25
GitHub is intended for bug reports and other issues observed in vanilla Magento 2 Community Edition. Issues should conform to [issue template](https://github.com/magento/magento2/blob/develop/ISSUE_TEMPLATE.md) so that anyone can reproduce problem and not guessing anything.

It is better to use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.

**Comment by choukalos** [comment] 2017-08-29 13:25
No, we do not support that functionality.  Updating to a question and adding 'needs update'.

Question - why do you want to translate via the REST API?

**Comment by LuisFReis** [comment] 2017-08-30 10:23
I'm building an Integrator and need to pass from the ERP Software all the data to the Magento.
So, when I post Categories or Products in Magento, I send all data based in my ERP, including the languages, 
Simplifying
I need to send the Product Name in, for example English and French, my client does not want to administrate the Magento Shop, he wants to do all that in the ERP.

If you look for example to PrestaShop, their API provides methos to do that

**Comment by korostii** [comment] 2017-09-01 12:33
Hi @LuisFReis

> I need to send the Product Name in, for example English and French

In Magento terms, those wouldn't be "translations". 
You'll just have to create a separate "French" store \ store view, and one product attribute (product name, for example) will be able to have different values for different stores.

I believe this is already possible with the current REST API, see here for example [here](https://magento.stackexchange.com/questions/142090/when-having-2-stores-how-do-you-add-a-product-to-a-specific-store-using-the-res). You'll just need to add the ID of the corresponding store into the endpoint along the translated data.

**Comment by misha-kotov** [comment] 2017-09-01 16:19
@korostii is right. Use the store_code url param to retrieve data from different storeviews (which in your case would be localized values for field names like name, description, etc).

**Comment by misha-kotov** [comment] 2017-09-01 16:21
Closing the issue since this is not a bug report, as mentioned above.

**Closed as completed by misha-kotov** 2017-09-01 16:21 UTC
Labels: Progress: needs update
