### ISSUE TITLE
In version 2.0.8, fatal error while accessing an attribute with object manager

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#5760] opened 2016-07-22 11:29 UTC
## Steps to reproduce
1. Clean install with 2.0.8
2. Attribute added via admin
3. Try to access attribute with an object manager (AttributeId 132 is exist): <br/>

`include('app/bootstrap.php');
$bootstrap = Bootstrap::create(BP, $_SERVER);
$objectManager = $bootstrap->getObjectManager();
$attributeColor=$objectManager->create('Magento\Eav\Model\Entity\Attribute');
$attributeColor->load(132);
`
## Expected result
1. Attribute loaded with object manager's load method
2. And move on ⏩ 
## Actual result

Fatal error: Uncaught exception 'ReflectionException' with message 'Class does not exist' in /vendor/magento/framework/Code/Reader/ClassReader.php:19 
Stack trace: 
0. /vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('') 
1. /vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('')
2. /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('')
3. /vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('', Array) 
4. /vendor/magento/framework/Validator/UniversalFactory.php(36): Magento\Framework\ObjectManager\ObjectManager->create(NULL, Array)
5. /vendor/magento/module-eav/Model/Entity/Attribute/AbstractAttribute.php(537): M in /vendor/magento/framework/Code/Reader/ClassReader.php on line 19

**Comment by svines** [comment] 2016-07-29 17:11
I'm seeing the same thing in 2.0.7.  To me, it appears to occur when you associate an old attribute with an attribute set.  For example, consider the following attributes and the versions in which they existed:
color -> 2.0.1
new_attr -> 2.0.7

Assuming Default attribute set does not contain either attribute, adding "new_attr" to it works fine, but adding "color" to it produces the symptoms described above.  The same stacktrace is also observable through the web API.

**Comment by magento-engcom-team** [comment] 2017-11-22 13:30
@rbostan, thank you for your report.
The issue is already fixed in 2.1.10

**Closed as completed by magento-engcom-team** 2017-11-22 13:30 UTC
Labels: bug report, Issue: Clear Description, Issue: Confirmed, Fixed in 2.1.x, Issue: Format is not valid
