### ISSUE TITLE
CPU's  100%

### ISSUE THREAD

**Issue by jackie-keys** [magento/magento2#3984] opened 2016-04-03 05:04 UTC
## Steps to reproduce
1. Install Magento from 2.0.4
2. Cache Management Disabled
3. Install Theme  Payago
4. Content | Blocks....   CPU's climb and all sit at 100%....alarms go off.. :(  (almost anything in admin will produce the same result)
5. No blocks show

![image](https://cloud.githubusercontent.com/assets/18239905/14230826/7c03f3de-f9bd-11e5-8e6d-bcec89b92423.png)
## Expected result
1. Page opens and can see blocks
## Actual result
1. 8 x CPU's hit 100% and alarms start going off (also have 16GB RAM).   Have to kill browser to get it to stop

Other info
WAMP  on Windows 10
Apache V2.4.9
PHP 5.5.12
MySQL 5.6.17
Antivirus is ignoring Apache and My SQL

**Comment by daim2k5** [comment] 2016-04-03 07:59
@jackaroos what happend when you switch back to the default theme?

**Comment by jackie-keys** [comment] 2016-04-03 11:24
Hi 

Changed to Luma

Saved Config

Cleared Cached 

Same problem, alarms started going off and had to close browser to stop the problem:

Loading home page causes same issues

Kind regards

Jackie

**Comment by ktomk** [comment] 2016-04-03 11:37
Please enable debug logging in your Apache configuration and then reproduce again. It should shed some light what is going on.

Also from the description you give, this sounds like a problem with installing _Theme Payago_, you should contact the vendor of that software for your support options first. Please provide any feedback the vendor gives on the issue.

Next to that please keep in mind that Windows is not part of the supported systems. I would suggest to get someone to you who has experience in setting up PHP based dev-systems on Windows and who can review if the general setup you have there is fitting and who can reveal more technical details on what is going on. A report just on 100% CPU with httpd could be a plethora of things.

Debug logging should at least produce more details.

**Comment by mazhalai** [comment] 2016-04-04 15:09
@jackaroos Officially, Magento only supports [Ubuntu and Centos](http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements.html).  However, since many developers use Windows, we provide limited support, but it is no way intended to be run on production in Windows. 

Closing, since this is not really a bug.

**Closed as completed by mazhalai** 2016-04-04 15:09 UTC
Labels: Progress: needs update
