### ISSUE TITLE
Integration Test AMQP Helper Hardcoded Host

### ISSUE THREAD

**Issue by pmclain** [magento/magento2#18953] opened 2018-10-30 16:04 UTC
### Preconditions (*)
1. Magento 2.3-beta
2. Do not install AMQP on localhost

### Steps to reproduce (*)
1. Attempt execution of any test utilizing the AMQP Helper such as https://github.com/magento/magento2/blob/77af5d65ef4fb986e62d9d1bcc230828c7c07f1b/dev/tests/integration/testsuite/Magento/Framework/MessageQueue/TopologyTest.php

### Expected result (*)
1. The AMQP Helper should use the same host as the Magento instance under test.
2. The helper class also assumes the management plugin is installed on the AMQP instance. I think this is a fair assumption, but it would be nice to first check that the management endpoint is available and skip any tests requiring if it is not.

### Actual result (*)
1. Tests fail

https://github.com/magento/magento2/blob/77af5d65ef4fb986e62d9d1bcc230828c7c07f1b/dev/tests/integration/framework/Magento/TestFramework/Helper/Amqp.php#L26

**Comment by magento-engcom-team** [comment] 2018-10-30 16:04
Hi @pmclain. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@pmclain do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-12-21 13:35
@lisovyievhenii Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97291` were created

**Comment by magento-engcom-team** [comment] 2019-02-10 18:20
Hi @pmclain. Thank you for your report. 
The issue has been fixed in magento/magento2#18978 by @pmclain in 2.3-develop branch
Related commit(s):
 - [789bc9ad6e42fda07f7baf8c3bcd86c4b6d278ae](https://github.com/magento/magento2/commit/789bc9ad6e42fda07f7baf8c3bcd86c4b6d278ae)
 - [5d2c8c93f31c881283aafad04ad3e7e680ad699b](https://github.com/magento/magento2/commit/5d2c8c93f31c881283aafad04ad3e7e680ad699b)
 - [364166ee983c8a7185211b2d0637826e965831e5](https://github.com/magento/magento2/commit/364166ee983c8a7185211b2d0637826e965831e5)
 - [d711fca268da4ac06dd72bdb83b006ede47ee677](https://github.com/magento/magento2/commit/d711fca268da4ac06dd72bdb83b006ede47ee677)
 - [a1b6eeee741bb4926f9475379f87c3b033071ff7](https://github.com/magento/magento2/commit/a1b6eeee741bb4926f9475379f87c3b033071ff7)
 - [dc8b17039f8be1e443182d671c1f2b4e113c49a5](https://github.com/magento/magento2/commit/dc8b17039f8be1e443182d671c1f2b4e113c49a5)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2019-02-10 18:20 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Framework/TestFramework
