### ISSUE TITLE
Issue deleting images from admin if used on multiple products

### ISSUE THREAD

**Issue by jamiejackson1183** [magento/magento2#7459] opened 2016-11-16 21:34 UTC
If you have uploaded products via a spreadsheet and 4 products have the same image used (Same name) 

Then you go to any product in the admin and go to images, on the image select the basket icon to delete it.

This removes the image from the server, so any other product using the same image will break and give and error like this meaning you cant edit that product any longer in the admin.

Creating the image file back in the server removes the error.

Cannot gather stats! Warning!stat(): stat failed for (Path to image)

**Comment by romainruaud** [comment] 2016-11-17 11:16
You can check this one too : https://github.com/magento/magento2/issues/7389

But it seems to be a "it's not a bug, it's a feature" ...

**Comment by veloraven** [comment] 2016-11-17 12:27
Closed as duplicate and not an issue.
You can submit it as improvement to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Closed as completed by veloraven** 2016-11-17 12:27 UTC
