### ISSUE TITLE
[Issue] Sales rule CartFixed calculation : incorrect discount amount

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#38694] opened 2024-05-02 13:07 UTC
### Preconditions and environment

- Magento version 2.4.7

### Steps to reproduce

1. Create a sales rule "test1", without coupon, cart fixed amount = 5€ (Discard subsequent rules = no)
2. Create a sales rule "test2", without coupon, cart fixed amount = 10€ (Discard subsequent rules = no)
3. Create a sales rule "test3", with coupon 'test3', cart fixed amount = 1€ (Discard subsequent rules = no)
4. Create a frontend cart, with total amount > 20€
5. Add coupon test3

### Expected result

Discount of 16€

### Actual result

Discount different of 16€, amount change when cart items changes.

### Additional information

The difference between amount applied and correct amount can be very big  - it depends on rules amounts, and items in cart. In one of our cases, we saw a 90€ discount applied, instead of 40€...

I'm still on debug. The issue is probably somewhere between  `src/vendor/magento/module-sales-rule/Model/Rule/Action/Discount/CartFixed.php::calculate` and `src/vendor/magento/module-sales-rule/Helper/CartFixedDiscount.php::getDiscountedAmountProportionally`. I will update the issue if I get more informations.

Update : I really don't understand what's the goal of `getDiscountedAmountProportionally` method. It can sometimes - and sometimes it does - produce a ratio bigger than 1, hence appliying a bigger discount than expected. Even when the ratio is under 1, I don't really get why we lower the discount. I guess such "proportionality" could be usefull for % discounts, to avoid that two -10% sum up at -20% instead of -19% (-10% on a -10% discount). But for fixed cart price, I don't understand..

So a quickfix is to simply remove it, by replacing `if ($isAppliedToShipping) {` with `if (true || $isAppliedToShipping) {` in CartFixed class. This is of course a temporary ugly fix, that you can apply at your own risk, but in our case it fixed the error and we stopped losing money (or making our customers angry) because of it. Now, let's wait for an answer from a Magento architect.

Update 2 : Same issue with rules that only applies on shipping amounts. (apply on shipping amount = Yes + Apply on product where name = 'some inexistant name').
Seems because of another ratio in `src/vendor/magento/module-sales-rule/Helper/CartFixedDiscount.php::getShippingDiscountAmount`.  But https://github.com/magento/magento2/issues/38671 needs to be fixed to be tested.

Quick fix for that (at your own risks) : 
```
--- a/Model/Validator.php	2024-05-03 08:38:15
+++ b/Model/Validator.php	2024-05-03 08:38:05
@@ -486,6 +486,14 @@
                                     $quoteBaseSubtotal,
                                     $shippingQuoteAmount
                                 );
+
+                            $quoteBaseSubtotal = (float) $address->getBaseShippingAmount();
+                            foreach ($quote->getAllItems() as $item) {
+                                if ($rule->getActions()->validate($item)) {
+                                    $quoteBaseSubtotal += (float) $item->getBaseRowTotal();
+                                }
+                            }
+
                             $discountAmount = $this->cartFixedDiscountHelper->
                             getShippingDiscountAmount(
                                 $rule,

```

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2024-05-06 08:35
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2024-05-06 17:12
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2024-05-07 10:21
Hi @Nuranto 

Thanks for reporting and collaboration.

Verified the issue on magento 2.4 dev instance and 2.4.7 instance and the issue is reproducible.

We are seeing a Discount difference of 16€, the amount changes when cart items change.

Steps to reproduce

1. Create a sales rule "test1", without coupon, cart fixed amount = 5€ (Discard subsequent rules = no)
2. Create a sales rule "test2", without coupon, cart fixed amount = 10€ (Discard subsequent rules = no)
3. Create a sales rule "test3", with coupon 'test3', cart fixed amount = 1€ (Discard subsequent rules = no)
4. Create a frontend cart, with total amount > 20€
5. Add coupon test3

Please refer the attached screenshots.

Discount amount after applying coupon code test3:

<img width="1440" alt="Screenshot 2024-05-06 at 10 45 55 PM" src="https://github.com/magento/magento2/assets/60198592/2e349376-7597-480c-ba68-52a9919a609b">

When cart amount/products are changed :

<img width="1440" alt="Screenshot 2024-05-06 at 10 46 25 PM" src="https://github.com/magento/magento2/assets/60198592/c1e65ed1-afe1-4765-b7dc-4ae5664f8e2c">

Cart rules Configuration: 

<img width="1440" alt="Screenshot 2024-05-06 at 10 53 26 PM" src="https://github.com/magento/magento2/assets/60198592/3fcd9abf-8eb7-46f0-ae18-b883a64a01c6">

<img width="1440" alt="Screenshot 2024-05-06 at 10 53 36 PM" src="https://github.com/magento/magento2/assets/60198592/4b7a5080-cd61-47e2-8af9-55d7d92076cc">

<img width="1440" alt="Screenshot 2024-05-06 at 10 53 45 PM" src="https://github.com/magento/magento2/assets/60198592/cafe2257-8fd2-4715-93ca-ce1bce745950">

<img width="1440" alt="Screenshot 2024-05-06 at 11 12 54 PM" src="https://github.com/magento/magento2/assets/60198592/9c6e385e-16bb-4d3d-b4e3-68bb62483977">

**Comment by zakdma** [comment] 2024-05-09 11:42
I don't know the exact place where the issue appeared but I found that the cart totals calculation was called twice.
Also I found that in M2.4.6-p4 all worked fine and totals calculation called only once.

**Comment by zakdma** [comment] 2024-05-09 11:55
Looks like this commit introduced break changes
https://github.com/magento/magento2/commit/4ffcb0208fe9a8224621385eb7950c2084055327

**Comment by pmzandbergen** [comment] 2024-05-24 07:05
I can confirm this issue. We ran into this while running functional tests with the Magento 2.4.7 upgrade. Previous version (2.6.4-p4) did succeed the same tests.

**Comment by rutvik-dolphin** [comment] 2024-06-24 05:58
Without coupons, the discount is not being calculated correctly. I created four rules with a "Fixed amount discount for whole cart" and a "Discount Amount" of 10. I then tested different subtotals on the frontend, and here are the results:
Subtotal: 335.00, Discount: 41.42
Subtotal: 303.00, Discount: 41.61
Subtotal: 229.00, Discount: 42.28
Subtotal: 170.00, Discount: 40.76
Subtotal: 125.00, Discount: 41.51
Subtotal: 92.00, Discount: 43.70
Subtotal: 60.00, Discount: 46.76

The expected discount is 40, and it should be the same for all subtotals because the rule is set to "Fixed amount discount for whole cart."

**Comment by dsengsqli** [comment] 2024-06-27 08:23
Do someone have an hotfix because we are facing the issue on our live website and its a urgent major issue
The issue has been reported 2 months ago can we expect a patch soon ?

**Comment by dsengsqli** [comment] 2024-07-01 08:44
Thanks !
I will install it as hotfix but i hope we will get an official fix soon.

**Comment by amcguireweb** [comment] 2024-08-30 18:36
> Thanks ! I will install it as hotfix but i hope we will get an official fix soon.

Did you get an official patch for this from Adobe Commerce support?

**Comment by joacols** [comment] 2024-09-30 16:11
@magento im working on this

**Comment by joacols** [comment] 2024-09-30 16:11
@magento I am working on this

**Comment by joacols** [comment] 2024-09-30 16:12
@magento add to contributors team

**Comment by joacols** [comment] 2024-09-30 16:13
@magento add to contributors team@magento I am working on this

**Comment by joacols** [comment] 2024-10-01 16:38
Hi, 
My code for this is on this pr:
https://github.com/magento/magento2/pull/39231

**Comment by rutvik-dolphin** [comment] 2024-10-07 12:45
Hello @joacols ,
Your branch has conflicts that must be resolved

**Comment by engcom-Bravo** [comment] 2024-10-10 06:19
Hi @Nuranto,

Thank you for your contribution!

The Magento core engineering team is working on the issue which you have addressed in this PR. Team will cherry pick the commits from your PR and may do further implementation to cover few more scenarios as needed. We will reach out to you if we need more information. For now, you can pause work on this PR. 


Thank you once again!

**Comment by engcom-Bravo** [comment] 2024-10-14 06:55
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket ACP2E-3349 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-3349&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta2.

Thanks

**Closed as completed by engcom-Bravo** 2024-10-14 06:55 UTC
Labels: Issue: Confirmed, Component: Ui, Reproduced on 2.4.x, Priority: P1, Progress: done, Area: Cart & Checkout, Reported on 2.4.7

**Comment by tuyennn** [comment] 2025-04-24 23:44
Please note the ACP2E-3349 was not a completed fix, here the ACP2E-3498 as stable one and correct the fixed discount amount
https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-3498&type=commits
