### ISSUE TITLE
Price configurable product without tax

### ISSUE THREAD

**Issue by zamocom** [magento/magento2#8666] opened 2017-02-23 23:07 UTC
### Preconditions

1. When I insert a discount on the catalog rules of a configurable product see the crossed out price no commission when in fact I set it with taxes, however the final price is calculated correctly
2. Version of magento 2.1.5

### Steps to reproduce

1. Create a configurable product.
2. Set discount by catalog rules

### Expected result

1. See the old price calculated with taxes included
### Actual result

1. [Screenshot, logs]

![notax](https://cloud.githubusercontent.com/assets/24704756/23283231/305fee56-fa25-11e6-8423-c8d4e8fcdb40.jpg)

**Comment by jghaanstra** [comment] 2017-04-10 21:46
Duplicate of https://github.com/magento/magento2/issues/6729

**Comment by magento-engcom-team** [comment] 2017-09-29 09:30
@zamocom, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-09-29 09:30 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid
