### ISSUE TITLE
Configurable product goes to out of stock after the shipment is created for one child product with multi site and multi inventory

### ISSUE THREAD

**Issue by rajesh291994** [magento/magento2#37724] opened 2023-07-06 08:51 UTC
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

We have a multi website (2 website) and multi source configuration in our magento 2 setup

1. Assign single source to multiple stocks
2. Assign a stock to all the websites
3. Create configurable product(2 options) and assign qty to source(1 qty to each product)
4. Place an order with child both product one qty from frontend from one of the website and complete the order from admin
5. Feed product 10 qty to both child product and place order with one qty of one product.
6. Create an shipment in for that particular order
You will notice that parent configurable product goes out of stock automatically. That product will be out of stock for both the website where only one qty is shipped. This is an rare scenario which is occuring in default magento also

### Expected result

Parent configurable product should not go out of stock as only one item from child product is been shipped.

### Actual result

Parent configurable product goes out of stock after creating shipment.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by rajesh291994** [comment] 2023-07-06 08:52
@magento Please provide a magento instance

**Comment by rajesh291994** [comment] 2023-07-06 08:53
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by rajesh291994** [comment] 2023-07-06 09:29
@engcom-Bravo can we get the multi website instance from magento as is issue occurs in multi website with multi inventory

**Comment by rajesh291994** [comment] 2023-07-06 09:32
@magento give me 2.4-develop multi website instance - upcoming 2.4.x release

**Comment by rajesh291994** [comment] 2023-07-06 09:44
@engcom-Bravo I have a db which is causing the issue even in vanilla magento. Can anyone try to investigate as I have tried all the approaches. Still could not figure out the issue

**Comment by engcom-Bravo** [comment] 2023-07-11 14:00
Hi @rajesh291994,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**


- Assign single source to multiple stocks
- Assign a stock to all the websites
- Create configurable product(2 options) and assign qty to source(1 qty to each product)
- Place an order with child both product one qty from frontend from one of the website and complete the order from admin
- Feed product 10 qty to both child product and place order with one qty of one product.
- Create an shipment in for that particular order


<img width="1268" alt="Screenshot 2023-07-11 at 4 16 17 PM" src="https://github.com/magento/magento2/assets/51680745/27caf78f-e6d2-4d73-a8dc-3a3edb0cf7c6">






<img width="1466" alt="Screenshot 2023-07-11 at 4 17 02 PM" src="https://github.com/magento/magento2/assets/51680745/08a9d7be-aba7-48fd-a10e-b896d97e4a93">



<img width="1402" alt="Screenshot 2023-07-11 at 4 16 28 PM" src="https://github.com/magento/magento2/assets/51680745/42d1d2dc-e617-4723-aaf9-237084ac1b46">



Parent Configurable product is still in **IN STOCK** in the both websites after the shipment of the child products.

Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.

Thanks.

**Comment by rajesh291994** [comment] 2023-07-11 14:20
@engcom-Bravo 

1. I disabled all the third party modules still the issue was there. I even tried to reproduce this in my vanilla magento and think it is any rare scenario which occurs when we place order of same product in both the website and make shipment.
2.  If posible I have an db which i used in debugging. Please place order of product with sku : Configurable Product and make the shipment you will be able to reproduce this issue
3. Please find the attachment 
[samplemagento_245p1.zip](https://github.com/magento/magento2/files/12015700/samplemagento_245p1.zip)

**Comment by rajesh291994** [comment] 2023-07-13 06:41
@engcom-Bravo It is reproducable in 2.4.5 p1 version.

**Comment by smartexcan** [comment] 2023-07-13 14:23
Also encountering this issue on 2.4.5-p1.
We're using a second inventory source/stock so we can enable the in-store-pickup functions.
Issue is reproducible even in single store/website configuration.

Steps:
1. Create new inventory source and stock
2. Create configurable product with some variations.
3. Assign variations only to new source.
4. Reindex if needed
5. create order with new configurable product
6. invoice and ship order
7. Configurable product is automatically set as out-of-stock

Looking into some recent changes on [magento/inventory](https://github.com/magento/inventory), there has been some work to try to fix this issue.
These changes made available as part of 2.4.6 / 2,4.6-p1, but i havent had a chance to test if that fixes the issue or not yet.

**Comment by rajesh291994** [comment] 2023-07-14 04:26
@smartexcan finally found someone facing the same issue.
I tested the same scenario in magento 2.4.6 seems like it has be fixed.

**Comment by engcom-Bravo** [comment] 2023-07-14 12:28
@smartexcan Thanks for your contribution & collaboration over here.

@rajesh291994 Issue is no longer reproducible in Magento 2.4 develop instance and also latest Magento latest version 2.4.7-beta1 it seems to be issue got fixed could you please upgrade to latest version.

As per comment if the issue is fixed https://github.com/magento/magento2/issues/37724#issuecomment-1635251323 can we close this issue please let us know.

it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.


Thanks

**Comment by rajesh291994** [comment] 2023-07-21 06:26
@smartexcan do you got the chance to check if the issue is fixed in 2.4.6 magento version

**Comment by smartexcan** [comment] 2023-07-21 13:39
Haven't checked 2.4.6, but we just updated to 2.4.6-p1 and it's fixed there for sure.

**Comment by engcom-Bravo** [comment] 2023-07-25 13:13
@smartexcan Thanks for your contribution & collaboration over here.

Hi @rajesh291994,

Thanks for your update.

We have also verified the issue in Latest version Magento 2.4.7-beta 1 and also in Magento 2.4.6-p1 instance and the issue is not reproducible it seems to be issue is fixed could you please let us know can we close the issue.

Thanks.

**Closed as completed** 2023-07-25 16:10 UTC
Labels: Issue: needs update, Reported on 2.4.x

**Comment by stevelou2** [comment] 2023-08-30 15:41
Same issue on 2.4.4-p5, any orders shipped made that configurable out of stock.
MSI and multiple sites.
So I must upgrade to 2.4.6
