### ISSUE TITLE
A large number of attribute options

### ISSUE THREAD

**Issue by Sacrize** [magento/magento2#36714] opened 2023-01-09 12:11 UTC
### Summary

Magento 2.4.3-p2

Database of 500k products

The "author" select attribute has 100k options. The product editing view in the panel takes several minutes to load.

Do you have any solution to speed up loading?

### Examples

Any attribute with that many options.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-01-09 13:46
Hi @Sacrize,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.


We have instance with 500K products and large number of attribute options.we are able to get the product editing view in the panel with in seconds.


<img width="1486" alt="Screenshot 2023-01-09 at 7 12 06 PM" src="https://user-images.githubusercontent.com/51680745/211321980-91b42a54-cde5-44b9-b1f1-91188ce9f731.png">




https://user-images.githubusercontent.com/51680745/211322392-d1e15631-1d2f-4d34-8801-56e409a86f73.mov



Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-01-25 06:11
Hi @Sacrize,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-01-25 06:11 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.3-p2
