### ISSUE TITLE
Vertex: Magento 2.3.3. - Error on Store -> Sales -> Tax  

### ISSUE THREAD

**Issue by MrAmbro** [magento/magento2#25403] opened 2019-10-31 12:49 UTC
I have a problem with my magento 2.3.3. installation. When i try to access the Store -> Sales -> Tax I receive this error:

**Fatal error:** Uncaught TypeError: Argument 1 passed to Vertex\Tax\Model\FlexField\FlexFieldProcessableAttribute::setLabel() must be of the type string, null given, called in /home/shopmon0/public_html/vendor/vertex/module-tax/Model/FlexField/Extractor/EavAttributeExtractor.php on line 122 and defined in /home/shopmon0/public_html/vendor/vertex/module-tax/Model/FlexField/FlexFieldProcessableAttribute.php:112 Stack trace: #0 /home/shopmon0/public_html/vendor/vertex/module-tax/Model/FlexField/Extractor/EavAttributeExtractor.php(122): Vertex\Tax\Model\FlexField\FlexFieldProcessableAttribute->setLabel(NULL) #1 /home/shopmon0/public_html/vendor/vertex/module-tax/Model/FlexField/Processor/CustomerGetterProcessor.php(142): Vertex\Tax\Model\FlexField\Extractor\EavAttributeExtractor->extract('customer', 'customer.custom', 'Customer', 'Vertex\\Tax\\Mode...', Array) #2 /home/shopmon0/public_html/vendor/vertex/module-tax/Model/FlexField/Processor/FlexFieldAttributeProcessor.php(68): Vertex\Tax\Model\FlexField\Processor\CustomerGetterPr in /home/shopmon0/public_html/vendor/vertex/module-tax/Model/FlexField/FlexFieldProcessableAttribute.php on line 112

**Comment by MrAmbro** [comment] 2019-10-31 12:50
I have a problem with my magento 2.3.3. installation. When i try to access the Store -> Sales -> Tax I receive thi error:

Uncaught TypeError: Argument 1 passed to Vertex\Tax\Model\FlexField\FlexFieldProcessableAttribute::setLabel() must be of the type string

**Comment by Orims14** [comment] 2019-11-01 14:42
Is there a patch for this? Having the same exact issue.

Thank You

**Comment by sdzhepa** [comment] 2019-11-01 18:54
Hello @MrAmbro 

We cannot reproduce this issue using the provided steps in the description.
Verified next case:
1. Get latest Magento 2 code from composer
```
php -v
PHP 7.2.18

$ composer create-project --repository=https://repo.magento.com/ magento/project-community-edition .
Installing magento/project-community-edition (2.3.3)

 ...
- Installing vertex/sdk (1.2.0): Loading from cache
- Installing vertex/module-tax (3.2.0): Loading from cache
- Installing vertex/product-magento-module (3.2.0)
 ...

````
2. Install Magento
3. "Sign in" to the Admin panel
4. Go to **STORES > Taxes > Tax Rules**
5. Create any new test Tax Rule and save
4. Go to **STORES > Taxes > Tax Zones and Rates**
6. Create any new test New Tax Rate and save
7. Go to **STORES > Settings > Configuration**
8. Open **SALES > Tax**
9. Open **Vertex Settings**
10. Enable it, fill some test data and click "Save Config" button
11. Sign Out and Sign In again

 **Actual result:**
-- No fatal errors on pages
-- No errors in log files
-- tested also in developer mode - no errors


@shikhamis11 are you able to reproduce it?

**Comment by shikhamis11** [comment] 2019-11-02 17:35
hi @sdzhepa 
yes I  checked both scenario you shared I am also not able to reproduce it. 
@MrAmbro can you please recheck the steps required to reproduce the issue also please check and share if it requires some additional informations to reproduce this issue

**Comment by Orims14** [comment] 2019-11-03 15:53
if it helps I experienced it on 2.3.3 Commerce and i had migrated taxes from Magento 1 to Magento 2 using the data migration tool.

**Comment by mmmattera** [comment] 2019-11-04 15:49
I have this problem in 2.3.3 opensource. I also migrated from magento 1 1.9.3.10.

As the error message states the data retrieved by /.../vendor/vertex/module-tax/Model/FlexField/Extractor/EavAttributeExtractor.php line 122
$attribute->setLabel($eavAttribute->getDefaultFrontendLabel());

is not a string. parameter validation? anyone, anyone...
I debugged this with changing the line to:$attribute->setLabel(strval($eavAttribute->getDefaultFrontendLabel()));
and printing each attributes with:
file_put_contents("/home/.../public_html/dump.txt", "\nXXXX\n", FILE_APPEND );
file_put_contents("/home/.../public_html/dump.txt", "Y" . strval($eavAttribute->getDefaultFrontendLabel())."Z", FILE_APPEND );
file_put_contents("/home/.../public_html/dump.txt", "A" . strval($eavAttribute->getAttributeCode())."B", FILE_APPEND );

#a quick command to force the file to rerun:
rm -R var/cache/* var/page_cache/* var/di/* var/generation/* var/view_preprocessed/* pub/static/*
and we have the results and it shows an empty attribute:
....
YHS CodeZAts_hs_codeB
XXXX
YCountry of OriginZAts_country_of_originB
XXXX
YFrom ShoppingFluxZAfrom_shoppingfluxB
XXXX
YPassword created atZApassword_created_atB
XXXX
YZArp_customer_idB     <----- null value for rp_customer_id


A quick search finds these attributes in eav_attribute ( I hate that table and I've only been working on m2 for less than a month)

I used phpadmin to add text frontend labels to all entries just in case an upgrade has the same code.

**Comment by sdzhepa** [comment] 2019-11-07 17:49
Hello @MrAmbro and @mmmattera 

We have notified the vendor owner of Vertex about this report.
As I know they are working on it now.
Internal Jira ticket to track progress for this issue has been created `BUNDLE-2311`

We will provide updates as soon as we have it

**Comment by itzB3rnD** [comment] 2019-11-08 10:01
I can confirm the issue, as we also have migrated tax in our database. We migrated from 1.8.1.0

**Comment by BenItt** [comment] 2019-11-18 15:16
Hi there,

we were facing the exact same error.

We worked around this by disabling the Vertex module (which we anyhow do not use)

```
php bin/magento module:disable -c Vertex_Tax
php bin/magento setup:upgrade
```

Maybe it helps you guys as well. After disabling the module all works fine again.

Best regards

**Comment by navarr** [comment] 2019-11-21 20:13
This patch is not yet tested, but should resolve the issue:

```patch
Index: vendor/vertex/module-tax/Model/FlexField/Extractor/EavAttributeExtractor.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- vendor/vertex/module-tax/Model/FlexField/Extractor/EavAttributeExtractor.php	(revision 21bce02860fb6a0661f434dc38527664aaa7dded)
+++ vendor/vertex/module-tax/Model/FlexField/Extractor/EavAttributeExtractor.php	(date 1574367021765)
@@ -119,7 +119,7 @@
             $attribute = $this->attributeFactory->create();
             $attributeCode = $prefix . '.' . $eavAttribute->getAttributeCode();
             $attribute->setAttributeCode($attributeCode);
-            $attribute->setLabel($eavAttribute->getDefaultFrontendLabel());
+            $attribute->setLabel($eavAttribute->getDefaultFrontendLabel() ?: $eavAttribute->getAttributeCode());
             $attribute->setOptionGroup(__($optionGroup)->render());
             $attribute->setType($type);
             $attribute->setProcessor($processor);
```

If anyone using Vertex as their calculation engine needs a fix.  Disabling the module also works well if you are not using Vertex as your calculation engine.

A fully tested and proper fix should be included with Magento 2.3.4

**Comment by navarr** [comment] 2019-12-09 17:46
This issue is fixed in Vertex 3.3.0 included in Magento 2.3.4

**Comment by sheshagiriAnvekar** [comment] 2020-01-29 06:12
This issue fixed in Magento 2.3.4.

**Closed as completed** 2020-01-29 18:12 UTC
Labels: Progress: needs update, Issue:  Cannot Reproduce, Issue: Format is not valid, Component: Bundled Extension

**Comment by MikeVelazcoMtz** [comment] 2021-08-29 23:37
I still see this logs on Magento 2.4..3.

**Comment by navarr** [comment] 2021-08-30 01:20
@MikeVelazcoMtz To confirm, you're unable to load the tax configuration page and see the vertex error in your log?

Can you please copy/paste the error?
