### ISSUE TITLE
Saving an attribute with backend_type 'static' will remove the content of the 'frontend_class' field.

### ISSUE THREAD

**Issue by MLucaciu** [magento/magento2#27051] opened 2020-02-27 10:55 UTC
### Preconditions (*)

1. Magento Open Source 2.3.3

### Steps to reproduce (*)

1. Navigate to Stores > Attributes > Product
2. Click an attribute with **backend_type** = **static**. Example: **sku** or **category_ids**
3. On the attribute edit page, you can either modify some fields or not modify any field at all.
4. Click "Save and continue edit".

### Expected result (*)

1.**frontend_class** should have the same value as before saving.
2. 
![sku-before](https://user-images.githubusercontent.com/26298317/75438134-20c90980-5960-11ea-8ed3-cf9b4aea8076.png)

### Actual result (*)

1. **frontend_class** is NULL
2. ![sku-after](https://user-images.githubusercontent.com/26298317/75438250-4bb35d80-5960-11ea-8769-7a11263449e5.png)

**Comment by MLucaciu** [comment] 2020-02-27 10:56
yes

**Comment by magento-engcom-team** [comment] 2020-02-27 11:26
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31961` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by RonakParmar** [comment] 2020-02-29 08:41
As per my knowledge it is not a bug. If you check the value of "frontend_class" field is set to "None", Please check the screenshot, you will get the idea. Let me know if I am looking at wrong place.
![screenshot-2020 02 29-14_06_15](https://user-images.githubusercontent.com/6551912/75604317-4b9c9480-5afd-11ea-85d3-b32daba43a4a.png)

**Comment by MLucaciu** [comment] 2020-02-29 08:52
> As per my knowledge it is not a bug. If you check the value of "frontend_class" field is set to "None", Please check the screenshot, you will get the idea. Let me know if I am looking at wrong place.
> ![screenshot-2020 02 29-14_06_15](https://user-images.githubusercontent.com/6551912/75604317-4b9c9480-5afd-11ea-85d3-b32daba43a4a.png)

I understand, but with a clean magento installation that field is “validate-length maximum-length-64”. So, why is that field “none” when editing the attribute and why does it overwrite the default value when saving?

**Comment by RonakParmar** [comment] 2020-02-29 09:02
@MLucaciu Because the default value is not matching with value of dropdown options (Input Validation for Store Owner).

**Comment by MLucaciu** [comment] 2020-02-29 09:04
@RonakParmar exactly. It should match.

**Comment by RonakParmar** [comment] 2020-02-29 09:22
@MLucaciu I got your point. As we can see "validate-length maximum-length-64" this is the default value of the field, which is ideally incorrect, because there is space between the string, it means there are two values of a field. As it is not a multiselect dropdown it should only one value. 
The solution of this issue is either we have to create validation rule which satisfy "validate-length maximum-length-64" validation or we have to select only one value. 

Let me know your thoughts on it.

**Comment by magento-engcom-team** [comment] 2020-06-25 00:00
Hi @MLucaciu. Thank you for your report. 
The issue has been fixed in magento/magento2#27369 by @jiten-patel in 2.4-develop branch
Related commit(s):
 - [b06db1f34b6799255a1cc7f596e21190ebaec7f2](https://github.com/magento/magento2/commit/b06db1f34b6799255a1cc7f596e21190ebaec7f2)
 - [aaa7054cd1e679bcba32c2311a3e547a52c2d590](https://github.com/magento/magento2/commit/aaa7054cd1e679bcba32c2311a3e547a52c2d590)
 - [fa154cde355e41e19f9e9a677807c71ae1d535be](https://github.com/magento/magento2/commit/fa154cde355e41e19f9e9a677807c71ae1d535be)
 - [7d8b893bf3f86c5d1467125fc091b1692b9b4201](https://github.com/magento/magento2/commit/7d8b893bf3f86c5d1467125fc091b1692b9b4201)
 - [054bf5d80633b40ba16a264a334be09510bbbe55](https://github.com/magento/magento2/commit/054bf5d80633b40ba16a264a334be09510bbbe55)
 - [2160c372b988fc1f09863fbc178613b28db3842f](https://github.com/magento/magento2/commit/2160c372b988fc1f09863fbc178613b28db3842f)
 - [83545c04624316805cce50a97b141f367d6605ec](https://github.com/magento/magento2/commit/83545c04624316805cce50a97b141f367d6605ec)
 - [c1a01fc4c797e037c760285b9434df52c4a38373](https://github.com/magento/magento2/commit/c1a01fc4c797e037c760285b9434df52c4a38373)
 - [eeb7433fe287c0d9200a3836aa54fcba88a7f11e](https://github.com/magento/magento2/commit/eeb7433fe287c0d9200a3836aa54fcba88a7f11e)
 - [7d2d0d3f369176264d12215f58ee6d5f3b067d62](https://github.com/magento/magento2/commit/7d2d0d3f369176264d12215f58ee6d5f3b067d62)
 - [eb343417c7fbe5b0692646686457e150d7d52fae](https://github.com/magento/magento2/commit/eb343417c7fbe5b0692646686457e150d7d52fae)

The fix will be available with the upcoming 2.4.1 release.

**Closed as completed by magento-engcom-team** 2020-06-25 00:00 UTC
Labels: Issue: Ready for Work, Component: Eav, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P3, Severity: S2, Triage: Done, Progress: done, Reported on 2.3.3
