### ISSUE TITLE
Can bypass minimum order amount while at Checkout

### ISSUE THREAD

**Issue by andyjv** [magento/magento2#21088] opened 2019-02-08 20:48 UTC
### Preconditions (*)

1. Magento 2.2.4, Magento 2.2.7
2. Minimum order amount enabled, and checkout page with minicart enabled

### Steps to reproduce (*)

1. Enable a minimum order amount (ex. $100).
2. Add at least two items to cart, with sub-total at least $100.
3. Go to Checkout, and proceed to Payment step.
4. Open mini-cart, and remove an item (by clicking the trashcan icon) so that the sub-total falls below $100.

### Expected result (*)

1. Would expect to be redirect to cart page, and checkout disabled.

### Actual result (*)

1. After removing an item at payment step to fall below $100, you can complete checkout.
2. If you leave checkout, the minimum order total is actually removed for the duration of the session. You can remove and add items to the cart at any time, and go to checkout at any time, regardless of cart subtotal.

**Comment by magento-engcom-team** [comment] 2019-02-08 20:49
Hi @andyjv. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@andyjv do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by andyjv** [comment] 2019-02-08 20:49
@magento-engcom-team give me 2.2.7-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-08 20:50
Hi @andyjv. Thank you for your request. I'm working on Magento 2.2.7-develop instance for you

**Comment by pmclain** [comment] 2019-02-09 01:39
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-09 01:39
Hi @pmclain. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-09 01:39
Hi @pmclain, here is your [Magento instance](https://i-21088-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21088-2-3-develop.instances.magento-community.engineering/admin](https://i-21088-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-02-09 11:48
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment] 2019-02-09 12:39
@andyjv Thanks for your report . This issue is not present in current 2.2-develop instance so I am closing this. Message here if you still think this issue exists

**Closed as completed by shikhamis11** 2019-02-09 12:39 UTC
Labels: Issue: Format is valid

**Comment by andyjv** [comment] 2019-02-11 14:51
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-11 14:51
Hi @andyjv. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-11 14:52
Hi @andyjv, here is your [Magento instance](https://i-21088-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21088-2-2-develop.instances.magento-community.engineering/admin](https://i-21088-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
