### ISSUE TITLE
Fedex integration doesn't support Track API being a separate Project in FedEx account

### ISSUE THREAD

**Issue by avstaylime** [magento/magento2#38859] opened 2024-06-21 10:50 UTC
### Preconditions and environment

- Magento 2.4.7
- New FedEx account (created after Oct '23) that offers to choose between `Ship, Rate & Other APIs` and `Track API`

### Steps to reproduce

1. Enable FedEx shipping method by entering API credentials from a FedEx Project of a type `Ship, Rate & Other APIs`.
2. Place an order and enter enter a FedEx tracking number when creating a shipment.
3. Click Track Order to view tracking details.

### Expected result

Tracking details listed

### Actual result

Tracking information is currently not available. Please contact us for more information or email us at example@example.com

### Additional information

<img width="1009" alt="select-project" src="https://github.com/magento/magento2/assets/82515176/0a7763dc-e277-48f3-ac30-c56bf31bfc15">
It is not possible to select both `Ship, Rate & Other APIs` and `Track API` for a FedEx Project. So there should be additional config for Track API under the FedEx settings in the Magento Admin.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2024-07-03 07:50
Hi @avstaylime ,

We are putting this issue on hold as of now , as we need some PO confirmation on this.

Thanks,

**Comment by NeoM-dev** [comment] 2024-07-20 02:56
Any update on fix?  Having same issue tested everything many times.

**Comment by Robax-CSE** [comment] 2024-08-28 10:14
Hi, I am experiencing the same issue with Magento 2 FedEx Integration. 

I have created a project from the FedEx developer portal, but the Track API cannot be enabled on the same project as the Ship API, and the FedEx Magento 2 integration only allows one API Key in the configuration panel at the moment.

**Comment by engcom-Delta** [comment] 2024-08-30 11:16
Hi @avstaylime ,

Thanks for your reporting and collaboration.
We have verified the issue in latest 2.4-develop instance and the issue is reproducible.
Kindly refer the screenshots.

**Steps to reproduce** - 
1. Create a project in Paypal for "Rate,Ship,Other" 
![image](https://github.com/user-attachments/assets/ff243f3b-fb33-4686-848c-df064e02ed07)
2. Enter the same configuration in magento instance.
![image](https://github.com/user-attachments/assets/18e0aaf4-b24d-4d1f-8e0f-67198f080ce6)
3. Save the configuration and Access frontend.
4. Place order successfully with Fedex shipping method.
5. Access Admin, Create invoice for respective order.
6. Create shipment with tracking number.
7. Access shipment and click on tracking number.
![image](https://github.com/user-attachments/assets/d3389770-e4aa-4c45-a263-0621413d0529)
Observe error displays.

Thanks.

**Comment by psol7** [comment] 2024-10-02 15:52
Here is a solutions for tracking Fedex shipment while the option of multi API credentials (1 for rates and 1 for tracking) is still not implemented in the Fedex modules in Magento.
Use the shipperHQ shipper-tracker, it allow to create manual link for tracking .
composer require shipperhq/module-shipping-tracker
or download at https://github.com/shipperhq/module-shipping-tracker
Then you can set a shipperHQ tracker using manual Url as below:
https://www.fedex.com/fedextrack/?trknbr=#TRACKNUM#
When customer click the link in the Magento tracking page it will resolve to the Fedex tracking info.

**Comment by Mohamed-Asar** [comment] 2024-11-12 14:10
@magento i'm working on this

**Comment by df2k2** [comment] 2024-11-25 15:23
This PR works for me.  Thanks

**Comment by Mohamed-Asar** [comment] 2024-12-19 07:11
@engcom-Delta This issue fixed by adobe team. please check and close this issue

**Comment by engcom-Bravo** [comment] 2024-12-19 07:16
@Mohamed-Asar Thanks for your Contribution!!.

Hi @avstaylime ,

As I can see this issue got fixed in the scope of the internal Jira ticket ACP2E-3340 by the internal team
Related commits: https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-3340&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta2.

Thanks

**Closed as completed by engcom-Bravo** 2024-12-19 07:16 UTC
Labels: Component: Shipping, Issue: Confirmed, Component: Fedex, Reproduced on 2.4.x, Priority: P1, Progress: done, Area: Shipping, Reported on 2.4.7
