### ISSUE TITLE
Magento 2.1.4 upgrade to latest version

### ISSUE THREAD

**Issue by marilena6** [magento/magento2#12101] opened 2017-11-08 10:41 UTC
Magento:

I am trying to update the magento via Web Setup Wizard and every step is passed except this:

Check Component Dependency
We found conflicting component dependencies. Hide detail

Command "update" failed: Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1

The requested package magento/product-comunity-edition could not be found in any version, there may be a typo in the package name.
Potential causes:

A typo in the package name
The package is not available in a stable-enough version according to your minimum-stability setting
see https://getcomposer.org/doc/04-schema.md#minimum-stability for more details.
Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

For additional assistance, see component dependency help .

This is my composer.json

> {
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.1.4",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "require": {
        "magento/product-community-edition": "2.1.8",
        "composer/composer": "@alpha",
        **"magento/product-community": "2.1.8"**
    },
    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "@stable",
        "pdepend/pdepend": "2.2.2",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.3 <=0.7.0",
        "sebastian/phpcpd": "2.0.0"
    },
    "config": {
        "use-include-path": true
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": "app/code/"
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "alpha",
    "prefer-stable": true,
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "extra": {
        "magento-force": "override"
    }
}

I tried renaming the line "magento/product-community": "2.1.8", but when I retry the readiness check, the file is changed back to the way it was... (!)

What do I need to do to get passed this step?

**Comment by marilena6** [comment] 2017-11-14 14:51
Any update on this?

**Comment by magento-engcom-team** [comment] 2017-11-24 08:30
@marilena6, Thx for the report. Did you try use the row in you composer.json file:
magento/**project**-community-edition: "2.1.8". instead of product-community-edition?

**Comment by magento-engcom-team** [comment] 2017-12-08 07:37
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by magento-engcom-team** 2017-12-08 07:37 UTC
Labels: Progress: needs update, Issue: Format is not valid
