### ISSUE TITLE
Pagebuilder Maps script should not be output when Page builder is disabled

### ISSUE THREAD

**Issue by Detzler** [magento/magento2#38872] opened 2024-06-25 14:02 UTC
### Preconditions and environment

- Magento version 2.4.6-p6

### Steps to reproduce

1. Login to Backend
2. Navigate to Stores > Configuration > General > Content Management
3. Set "Enable Page Builder" to No
4. Leave Google Maps API Key empty
5. Save settings

### Expected result

1. Value for key "cms/pagebuilder/google_maps_api_key" in core_config_data table should be NULL or empty (I don't know exactly)
2. Script tag should not be output
![image](https://github.com/magento/magento2/assets/1556434/f6721986-b309-4e24-b23b-8879c6ba6b87)

### Actual result

1. Value for key "cms/pagebuilder/google_maps_api_key" in core_config_data table is a string containing "NULL (NULL/"unknown" value)"
![image](https://github.com/magento/magento2/assets/1556434/4d25334f-1f18-49be-9e1b-aeef3a9df45a)
2. Script tag is output because of the condition that gmaps api key is not empty
![image](https://github.com/magento/magento2/assets/1556434/32a4b75f-bf5c-46f7-b915-80bea3019407)
![image](https://github.com/magento/magento2/assets/1556434/02238193-0ba7-4b02-93f9-73543ac913be)
![image](https://github.com/magento/magento2/assets/1556434/8dd1aeae-bd4a-4599-89af-482fbe6a7e9a)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-06-26 03:59
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-06-26 05:12
Hi @Detzler,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screnshots.


**Steps to reproduce**

- Login to Backend
- Navigate to Stores > Configuration > General > Content Management
- Set "Enable Page Builder" to No
- Leave Google Maps API Key empty
- Save settings


<img width="892" alt="Screenshot 2024-06-26 at 10 38 42" src="https://github.com/magento/magento2/assets/51680745/7c7d6749-d0f0-4ee8-b371-3153083086bb">



<img width="714" alt="Screenshot 2024-06-26 at 10 38 25" src="https://github.com/magento/magento2/assets/51680745/8bab607d-8620-4d53-9f03-fd1e1fc954d4">


cms/pagebuilder/google_maps_api_key" in core_config_data table having NULL value.


Thanks.

**Comment by engcom-Bravo** [comment] 2024-07-08 05:22
Hi @Detzler,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-08 05:22 UTC
Labels: Issue: needs update, Reported on 2.4.6-p6
