### ISSUE TITLE
Forgot password link has expired

### ISSUE THREAD

**Issue by LCorentinL** [magento/magento2#38448] opened 2024-02-16 15:16 UTC
Magento version 2.4.4

I have an issue with the forgot password link send by mail.

I'm getting randomly the error "The link has expired"

In fact, if i close the tab and re-open it by the link in mail, the error can disapear or not.
If i click several time, the error is here and sometime not here.

So i check over, and i saw several topic about this error, the most one is the override of resetforgottenpassword.phtml

But on my local and staging environnement, the issue is not here.

Only on my production.

The only difference is that my production is multi server (2 servers that host the same magento).

I cannot find a solution to solve my problem, this is what i've tried already :
- Delete my override of resetforgottenpassword.phtml
- Put the configuration of recovery link time to 24

Step to reproduct : 
1 - Make a forgot password on the frontend
2 - Click on the link send by mail

**Comment by engcom-Dash** [comment] 2024-02-19 13:03
Hi @LCorentinL 

Thanks for reporting and collaboration.

Verified the issue in magento 2.4 dev instance but the issue is not reproducible.

Please refer the attached screenshot.

https://github.com/magento/magento2/assets/60198592/66ef14b8-2d68-47da-a76f-cb862f398d8a

**Comment by engcom-Dash** [comment] 2024-03-01 05:23
Hi @LCorentinL 

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel free to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Dash** 2024-03-01 05:23 UTC
Labels: Issue: needs update, Reported on 2.4.4

**Comment by mbernabeu** [comment] 2024-10-16 17:46
I have identified the cause of the “The link has expired” error when using the forgot password functionality in a multi-server Magento environment.

**Problem Summary:**

The issue occurs due to a time desynchronization between the different hosts in a production environment with multiple servers. Specifically, if there is any misalignment in the clocks of these servers, even by a few seconds, it can cause the reset password token validation to fail. This error happens inconsistently depending on which server is handling the request, leading to the observed intermittent behavior where the error sometimes appears and sometimes doesn’t.


**Code Trace:**

The problem originates in the [\Magento\Customer\Controller\Account\CreatePassword::execute()](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/Controller/Account/CreatePassword.php#L93) function. In this function, after the reset password link is clicked, Magento validates the password reset token and extends its validity by calling the changeResetPasswordLinkToken() function.

The [changeResetPasswordLinkToken()](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/Model/AccountManagement.php#L1476) function updates the rp_token_created_at value with the current timestamp:

```
$customerSecure->setRpTokenCreatedAt(
    $this->dateTimeFactory->create()->format(DateTime::DATETIME_PHP_FORMAT)
);
```
This new timestamp is stored to extend the validity of the token.

**The Root Cause:**

If the second request (after the user is redirected) lands on a different server that has a clock behind the first server, the validation of the token fails because the timestamp on the second server will be earlier than the one generated by the first server.

The token validation is handled by the [isResetPasswordLinkTokenExpired()](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/Model/AccountManagement.php#L1441) function, which compares the rp_token_created_at against the current server time:

```
$currentTimestamp = $this->dateTimeFactory->create()->getTimestamp();
$tokenTimestamp = $this->dateTimeFactory->create($rpTokenCreatedAt)->getTimestamp();
if ($tokenTimestamp > $currentTimestamp) {
    return true;
}
```
In a multi-server setup, if the second server has a clock that is a few seconds behind the first server, the comparison if ($tokenTimestamp > $currentTimestamp) will return true, marking the token as expired, even though it was just regenerated moments ago on the first server.

**Conclusion:**

The error arises from clock misalignment between the two hosts. When one server generates the new token with a current timestamp, and the subsequent request is handled by a second server with a slightly delayed clock, the token appears to have been created “in the future” relative to the second server’s time, causing the validation to fail.

Although the issue can be mitigated by ensuring that all servers have synchronized clocks using NTP (Network Time Protocol), I believe Magento should explore a more robust solution to prevent this issue from reoccurring.

It’s worth noting that this particular validation (if ($tokenTimestamp > $currentTimestamp)) might not be necessary, as the subsequent line already checks whether the token has expired based on the maximum allowed expiration period ($expirationPeriod). The validation of the expiration period should be sufficient to prevent issues with token validity, and the comparison of token timestamps across multiple servers introduces unnecessary complexity and risk of failure in a multi-host environment.

I suggest revisiting this validation logic to make it more resilient, especially for multi-server setups.
