### ISSUE TITLE
Rest response translation

### ISSUE THREAD

**Issue by VZeroCool** [magento/magento2#28344] opened 2020-05-23 10:19 UTC
### Preconditions (*)

1. Magento 2.3.3 CE

### Steps to reproduce (*)

1. Trigger {baseUrl}/rest/{store_code}//V1/carts/mine/items with customer token to add product to cart
2. Add "The requested qty is not available","الكمية المطلوبة غير متوفرة." to app/design/frontend/Vendor/ThemeName/ChildTheme/i18n/ar_SA.csv
"

### Expected result (*)

1. Response of API should be translated

### Actual result (*)

1. Response not translating returns message in English language only.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by VZeroCool** [comment] 2020-05-23 11:43
Since it require custom theme I cant able to reproduce at develop instance.

**Comment by VZeroCool** [comment] 2020-05-27 06:28
@magento-engcom-team any update ?

**Comment by duckchip** [comment] 2020-06-24 11:46
duplicate of https://github.com/magento/magento2/issues/26333

**Comment by swathishs** [comment] 2020-06-26 07:57
Hello @VZeroCool ,
Thank you for your report.
This issue is duplicate to #https://github.com/magento/magento2/issues/26333 and already in ready for dev stage

Hence closing the issue

**Closed as completed by swathishs** 2020-06-26 07:57 UTC
Labels: Issue: Format is valid, Reported on 2.3.3
