### ISSUE TITLE
Maximum Qty Allowed in Shopping Cart can't be set per store

### ISSUE THREAD

**Issue by augrinovska** [magento/magento2#24788] opened 2019-09-30 11:40 UTC
### Preconditions (*)

1. Magento 2.3.2
2. PHP 7.2.19
3. Two websites and two store views. 

### Steps to reproduce (*)

1. Admin -> Catalog -> Products -> Add New simple product
2. Website 1 and Store view 1: Quantity -> Advance Inventory -> Set 'Maximum Qty Allowed in Shopping Cart' to be equal to 5 -> Save
3. Website 2 and Store view 2: Quantity -> Advance Inventory -> Set 'Maximum Qty Allowed in Shopping Cart' to be equal to 10 -> Save

### Expected result (*)

1. The two stores to have different "Maximum Qty Allowed in Shopping Cart" for the product

### Actual result (*)

1. Every time the store's advanced inventory is changed, the others are changed in line. In this case for both stores, 'Maximum Qty Allowed in the Shopping Cart' will be 10.

**Comment by krishprakash** [comment] 2019-09-30 12:15
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-09-30 12:15
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-09-30 12:16
Hi @krishprakash, here is your [Magento instance](https://i-24788-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24788-2-3-develop.instances.magento-community.engineering/admin](https://i-24788-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-09-30 12:54
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20625` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by drpayyne** [comment] 2019-10-02 14:35
@engcom-Alfa @engcom-Bravo @engcom-Charlie Shouldn't this be moved to the new Inventory Management repository?

**Comment by drpayyne** [comment] 2019-10-02 14:39
@augrinovska Is this with the new MSI installed?

**Comment by drpayyne** [comment] 2019-10-03 02:07
@krishprakash Did you test this with the new MSI installed?

**Comment by engcom-Charlie** [comment] 2019-10-03 07:26
Hello @drpayyne 
No, we cannot transfer this issue to the MSI repository because the MSI functionality allows you to make a different qty of products in the cart (multi-source).

**Comment by drpayyne** [comment] 2019-10-03 08:05
@engcom-Charlie So "Maximum Qty Allowed in Shopping Cart" has website scope with default Magento 2.3.x without the new inventory modules installed?

**Comment by engcom-Charlie** [comment] 2019-10-03 08:17
@drpayyne no, it should not work without inventory modules because MSI was created for this.

**Comment by drpayyne** [comment] 2019-10-03 08:32
@engcom-Charlie yes we're in agreement then, the issue reported above is the non-existence of the feature (website scope for "Max Qty in Cart") in `magento/magento2` codebase which is actually introduced and active in `magento/inventory`. So I'm wondering why this is an issue present in the `magento/magento2` codebase.

**Comment by engcom-Charlie** [comment] 2019-10-03 08:37
@drpayyne i understand. 
I think it’s worth closing it, but I’d better clarify this with my lead.

**Comment by sdzhepa** [comment] 2019-10-03 14:42
Hello @engcom-Bravo 

May I ask you to re-check this issue?
It is not completely clear is it Issue in vanilla Magento or related to https://github.com/magento/inventory/

**Comment by engcom-Bravo** [comment] 2019-10-03 19:26
Hello @sdzhepa, @augrinovska. Please take a note at this:
![global](https://user-images.githubusercontent.com/51680745/66142955-0d16b280-e60f-11e9-92bd-48d7319ddd9a.png)
As You can see the scope of this setting is Global. It means that on whatever scope level of the product You change it, it will be automatically changed on all the possible scope levels. Just like  Price of the product if its scope is set to Global (as it is set per default):
![price](https://user-images.githubusercontent.com/51680745/66144812-3b49c180-e612-11e9-93b6-f01ededfc2fd.gif)
Of course there is another pattern present in Magento where the settings or attributes that are allowed to be changed only on higher scope levels are simply not available for altering on the lower scope levels, like, lets say Base Currensy in Configuration:
![currency](https://user-images.githubusercontent.com/51680745/66155139-a9e54a00-e627-11e9-9a59-b79ec25e2be7.gif)
So there could arise a question: "why those Mav. Quantites are available for alteration on the Store View level when their level is Global?" But any way it would be just a topic for another feature request, but not in the least for a bug. 
To precede with this review, before I start talking about some possible capabilities of MSI module, please let me first ask You @augrinovska whether You managed somehow to change the scope of 'Maximum Qty Allowed in Shopping Cart' to Store View or Website, or it remained Global while reproducing this issue? Thank You.

**Comment by augrinovska** [comment] 2019-10-04 08:02
Hi @engcom-Bravo,

I didn't manage to change the scope of 'Maximum Qty Allowed in Shopping Cart' to Store View or Website. I raised this issue as a bug because Magento allows changing the 'Max qty allowed in shopping cart' on a Store and Website level, but instead of keeping the value for the specific Store changed, it changes the others in line. 
Yes, the scope level of this field is Global, but the function defined to take the value from the configuration is in Scope Store. But this thing is maybe more for an opening ticker in MSI 
In class \Magento\CatalogInventory\Model\Configuration, function getMaxSaleQty
`  /** `
`     * Get Max Sale Qty`
`     * `
`     * @param null|string|bool|int|\Magento\Store\Model\Store $store`
`     * @return float|null`
`     */`
`    public function getMaxSaleQty($store = null)`
`    {`
`        return (float)$this->scopeConfig->getValue(`
`            self::XML_PATH_MAX_SALE_QTY,`
`            ScopeInterface::SCOPE_STORE,`
`            $store`
`        );`
`    }`

**Comment by engcom-Bravo** [comment] 2019-10-04 15:52
Thank You for Your reply @augrinovska. Yes as You say "...Magento allows changing the 'Max qty allowed in shopping cart' on a Store and Website level..." but with that Magento let You know the scope of the setting You are about to change and so You are supposed to take it into consideration. Global means the setting will be changed for all the scopes no matter what is the particular scope You are going to change it from. Therefor As I've already said this issue could be deemed a feature request but not a bug - a kind of issue this repository is intended for.
 As for the function You've mentioned I think It's also not critical as it causes no wrong behavior.
 But lets precede our talk on the availability to get that setting changed on website scope if You are interested in that functionality. So in vanilla Magento, without MSI there is no way to change the scope of 'Maximum Qty Allowed in Shopping Cart' from Global to some other. But with MSI this should become available in the nearest future. As I'm informed it will happen right after https://github.com/magento/inventory/pull/2297 will have been merged into develop branch. So now this issue better remain as it is. With that we'll be looking forward for that PR to get merged and once it happens we will see whether it'll be worth closing or still actual.

**Comment by sdzhepa** [comment] 2019-10-23 18:06
Hello @augrinovska and @webkul-ratnesh
fyi: @engcom-Bravo 

Thank you for contribution and collaboration!

After several meetings and discussions of this issue with internal Magento specialists(related and owners of these modules/functionality) we have next results:

1. The described issue is feature request actually because Magento works as was intended(the attribute should be global by design). 
2. Such kind of functional ability was requested multiple times by users and merchants so it makes sense to be implemented. 
3. These changes should cover not only one specific use-case(like described in this issue) but all related business needs and scenarios. In other words, the solution should be fundamental/global.
4. According to Magento architecture vision, all changes related to Inventory should be made in [Inventory(aka MSI)](https://github.com/magento/inventory) repository, which is public and open for community contribution.
5.  At this moment work on this global solution is in progress in the scope of this task https://github.com/magento/inventory/pull/2297 .
All planned work and design is described in this document [Stock and Source Configuration design](https://github.com/magento/inventory/wiki/Stock-and-Source-Configuration-design)

Because of all mentioned above, we are closing this issue and related PR https://github.com/magento/magento2/pull/25012 with the proposed solution.

These changes should be made in the https://github.com/magento/inventory/pull/2297 so please watch this ticket for the updates or even join if you want to participate and contribute.

**Closed as completed by sdzhepa** 2019-10-23 18:06 UTC
Labels: Issue: Ready for Work, Progress: needs update, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Store, Component: SalesInventory, Component: Inventory
