### ISSUE TITLE
Issue with image cache generation

### ISSUE THREAD

**Issue by ghost** [magento/magento2#33349] opened 2021-06-25 07:20 UTC
### Preconditions (*)

1. Magento 2.4.2
2.

### Steps to reproduce (*)

1. Image cache generation issue. Placeholer image generation in product page
2.

### Expected result (*)

1. Image generation correct
2.

### Actual result (*)

1. No error in log
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by achatpc** [comment] 2021-06-25 07:21
@magento I am working on this

**Comment by achatpc** [comment] 2021-06-25 07:23
@magento give me 2.4-develop instance

**Comment by achatpc** [comment] 2021-06-25 07:40
#33313 63518706

**Comment by achatpc** [comment] 2021-06-25 07:42
Thi fix issue for my:

replace
private function getOriginalImage(string $resizedImagePath): string {
return preg_replace('|^.*?((?:/([^/])/([^/])/\2\3)?/?[^/]+$)|', '$1', $resizedImagePath);
}

with

private function getOriginalImage(string $resizedImagePath): string
{
    return preg_replace('|^.*((?:/[^/]+){3})$|', '$1', $resizedImagePath);
}

vendor/magento/module-media-storage/App/Media.php

**Comment by engcom-Hotel** [comment] 2021-06-28 08:36
Hello @achatpc,

It seems that your issue has been fixed with this code change. I am closing this issue for now, you can reopen the ticket, if you still facing the issue or create new ticket in case new issue.

Thanks

**Comment by ihor-sviziev** [comment] 2021-06-29 06:25
Hey @engcom-Hotel,
The issue isn't solved in the 2.4-develop branch, right? So why would you close the issue?

**Comment by achatpc** [comment] 2021-06-29 08:21
> Hey @engcom-Hotel,
> The issue isn't solved in the 2.4-develop branch, right? So why would you close the issue?

Hello, do you have same issue ?

**Comment by engcom-Hotel** [comment] 2021-06-29 13:45
Hi @achatpc,

Looks like PR has been created before the issue confirmation(Issue confirmation label was not added). And also when we try to reproduce the issue in version 2.4-develop, we were not able to do so. So hence we thought that PR has implemented, so the issue has been closed. 

So PR is in open status, we are reopening the issue. We will be putting this ticket in Needs Update status as we are not able reproduce the issue. Requesting you to provide us more details in order to reproduce the issue.

Thanks

**Comment by sdzhepa** [comment] 2021-06-29 15:32
@engcom-Hotel   thank you for the updates.


You mentioned that

> also when we try to reproduce the issue in version 2.4-develop, we were not able to do so

Could you please provide more details on how you tried to reproduce it? 
E.g. steps to reproduce, results of code investigation, or any other actions that were performed with actual results

Thank you in advance

**Comment by engcom-Hotel** [comment] 2021-06-30 07:27
Hello @sdzhepa ,

I have followed below steps in order to reproduce this issue:
1. Setup fresh Magento 2.4-develop
2. Create a product with default image (magento placeholder).
3. Clear the cache.
4. Check the product detail page for product placholder. We are getting Magento's default image placeholder. Please refer below screenshot:
![Test-Product](https://user-images.githubusercontent.com/51681618/123919397-85f09d00-d9a2-11eb-8071-c426372b3f14.png)

@ihor-sviziev @achatpc : Please verify the steps, and let us know if we missed anything in order to reproduce the issue.

Thanks

**Comment by engcom-Hotel** [comment] 2021-09-13 07:40
Dear @achatpc,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2021-09-13 07:40 UTC
Labels: Component: Image, Issue: needs update, Reported on 2.4.2
