### ISSUE TITLE
After upgrade to 2.1, i can not add new product!!!!

### ISSUE THREAD

**Issue by aliantech** [magento/magento2#5722] opened 2016-07-21 08:27 UTC
After upgrade to 2.1, i can not add new product!!!!

but can editor old product

in the backend, when i click "add new product" button, the page is keeping loading page, i can not editor anything!!!! it was stuck loading page

**Comment by stamster** [comment] 2016-07-21 10:43
Do you got some error? I got `Unable to save Stock Item`. But the issue is related to shitty 3rd party modules, fresh install of M2.1 working fine.
I guess you might have something similar, i.e. compatibility issue after upgrade.

Did you run static di compile and content deployment?

**Comment by aliantech** [comment] 2016-07-21 10:45
yes, i have run static content deployment, but still have same problem
i don't know why this happen

:(((((((

Yasin Chen
CEO, Aliantech Trading Co.,Ltd.
+8618818806021 | info@aliantech.com | http://www.aliantech.com | Skype: Aliantech | No.30 Huiqiao 3rd Street, Guangzhou, China

From: stamster
Date: 2016-07-21 18:43
To: magento/magento2
CC: aliantech; Author
Subject: Re: [magento/magento2] After upgrade to 2.1, i can not add new product!!!! (#5722)
Do you got some error? I got Unable to save Stock Item. But the issue is related to shitty 3rd party modules, fresh install of M2.1 working fine.
I guess you might have something similar, i.e. compatibility issue after upgrade.
Did you run static di compile and content deployment?

**Comment by andimov** [comment] 2016-08-02 10:32
@aliantech 
To allow us to research the issue, please, format description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by aliantech** [comment] 2016-08-02 10:43
Magento CE 2.1 Version, Upgrade from 2.0.4
1) when i click "add product" button, the page was keeping loading, without any results, no matter wait more time, it still can not work

Yasin Chen
CEO, Aliantech Trading Co.,Ltd.
+8618818806021 | info@aliantech.com | http://www.aliantech.com | Skype: Aliantech | No.30 Huiqiao 3rd Street, Guangzhou, China

From: Andrii
Date: 2016-08-02 18:33
To: magento/magento2
CC: aliantech; Mention
Subject: Re: [magento/magento2] After upgrade to 2.1, i can not add new product!!!! (#5722)
@aliantech 
To allow us to research the issue, please, format description according to the template.
Please, format this issue according to the Issue reporting guidelines: with steps to reproduce, actual result and expected result.

**Comment by katmoon** [comment] 2016-08-29 13:42
Hi @aliantech 

I'm sorry for the delays in answering.
If it's still an issue, could you try to clear browser cache, Magento cache from Admin > System > Cache Management, and redeploy static content? It can help.

Thanks,
Kateryna.

**Comment by ilol** [comment] 2016-09-23 14:59
Hey @aliantech. Can we close this?

**Comment by aliantech** [comment] 2016-09-23 16:12
.....
Because this problem can not been solved, I have to give up magento .....

2016年9月23日 23:00 於 "Illia Oliinyk" notifications@github.com 寫道：

**Comment by GordonLesti** [comment] 2016-11-02 13:37
Hello @aliantech 
Seems to be a duplicate issue https://github.com/magento/magento2/issues/6513 and is solved in current `develop` branch. Problem was the `updateValue` function in [import-handler.js](https://github.com/magento/magento2/blob/2adb6e287f53c7a860aa5829733aad1014e11be2/app/code/Magento/Catalog/view/adminhtml/web/js/components/import-handler.js#L58).

**Comment by aliantech** [comment] 2016-11-22 05:26
it is still not resolved in Magento ver. 2.1.2

From: Gordon Lesti
Date: 2016-11-02 21:38
To: magento/magento2
CC: aliantech; Mention
Subject: Re: [magento/magento2] After upgrade to 2.1, i can not add new product!!!! (#5722)
Hello @aliantech 
Seems to be a duplicate issue #6513 and is solved in current develop branch. Problem was the updateValue function in import-handler.js.

**Comment by aliantech** [comment] 2016-11-22 05:28
From: Gordon Lesti
Date: 2016-11-02 21:38
To: magento/magento2
CC: aliantech; Mention
Subject: Re: [magento/magento2] After upgrade to 2.1, i can not add new product!!!! (#5722)
Hello @aliantech 
Seems to be a duplicate issue #6513 and is solved in current develop branch. Problem was the updateValue function in import-handler.js.

**Comment by tinxit** [comment] 2016-12-25 09:59
same error in Magento ver. 2.1.3 when a configurable product is saved in the backend.
![image](https://cloud.githubusercontent.com/assets/15381778/21470615/3450f5e6-ca91-11e6-89b8-76970d558f56.png)

**Comment by dmitriyprime** [comment] 2017-06-22 12:54
Thanks for reporting this issue. Is this issue actual for you or we can close it?

**Comment by gewaechshaus** [comment] 2017-07-03 20:29
@dmitriyprime - we got the same issues on a MCE 2.1.7. I will post some information related to the setup etc. I did some research, the only thing I stumbled upon was this https://community.magento.com/t5/Version-Upgrades-for-2-x/can-t-add-product-after-upgrade/td-p/65660

**Comment by dmitriyprime** [comment] 2017-07-25 15:46
Hi, @gewaechshaus. Browser cache issues can affect the success of your update. Did you clear your cache before installing the upgrade?

**Comment by webcitz** [comment] 2017-08-02 18:50
If all else fails, it might also be helpful to check if your database has any triggers with the wrong definer. I've seen that before on a migrated website installation. Go into phpMyAdmin, open the database, click on Triggers. Then, if you see any triggers in there just click "Edit" and then look at the definer field. In the situation we just resolved for someone the definer was previousdbname@locahost instead of newdbname@localhost.

**Comment by gewaechshaus** [comment] 2017-08-11 10:13
@dmitriyprime  - this doesn't happen anymore after upgrading to 2.1.8

**Closed as completed** 2017-09-18 17:12 UTC
Labels: bug report, Progress: needs update, Fixed in 2.1.x, Fixed in 2.2.x, Issue: Format is not valid
