### ISSUE TITLE
Sort by name with accented charaters doesn't work on Magento 2.4.2

### ISSUE THREAD

**Issue by antonioalonsoflat101** [magento/magento2#33455] opened 2021-07-12 07:43 UTC
### Preconditions (*)
1. Magento 2.4.2
2. Sample data installed
3. Blank theme

### Steps to reproduce (*)
1. In the **Backend** go to Catalog > Products
2. Edit Configurable porduct with SKU **WJ03**
3. Add accent in the first Character in the product name: Áugusta Pullover Jacket
4. Save Product and fluch cache
5. In the **Frontend** go to Women > Tops > Jackets
6. Sort the products by **Product name** > **Descending**

### Expected result (*)
1. The product with name **Áugusta Pullover Jacket** shouldn't be displayed in the first position of the list

### Actual result (*)
1. The product with name **Áugusta Pullover Jacket** is displayed in the first position of the list
![accentes_sort_error](https://user-images.githubusercontent.com/87300253/125249410-80297e80-e2f5-11eb-97d1-155967645141.jpg)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2021-07-13 11:22
Verified the issue on Magento 2.4-develop branch and the issue is reproducible on both Magento Blank and Luma Theme as well:
Steps:
1. Admin: Create any product with name - starting with any accented characters (Ex: Áaferff)
2. Clear Cache and navigate to Frond-end
3. Sort by Product Name in Descending Order
**Issue:** Product names starting with accented characters are displayed in the first position of the list
![image](https://user-images.githubusercontent.com/60198231/125443540-f18f8e2f-880f-46a4-aab1-90350e40dd45.png)

**Note**: In Admin - Catalog - Categories - Products in Categories - Sort by Product Name - Descending Order - **No issue.** Working as expected
![image](https://user-images.githubusercontent.com/60198231/125443441-8e4e3dcb-489d-4472-8845-1a161411ee51.png)

**Comment by magento-engcom-team** [comment] 2021-07-13 11:24
:white_check_mark: Confirmed by @engcom-November 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42833` were created

**Issue Available**: @engcom-November, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by bireney** [comment] 2021-12-16 10:11
Assign to me

**Comment by principiaskin** [comment] 2022-08-25 21:21
Any solution to this problemn?

**Comment by LimbicGit** [comment] 2022-10-05 14:18
We are facing exact same issue. Anyone has any clue about how to solve it, please?

**Comment by engcom-Bravo** [comment] 2024-06-20 06:05
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-06-20 06:20
Hi @antonioalonsoflat101,

Thanks for your reporting and collaboration.

we have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

![Jackets-Tops-Women](https://github.com/magento/magento2/assets/51680745/a09e3e47-718b-4f7f-a8f4-7f282dc6f339)



The product with name Áugusta Pullover Jacket is not displaying in the first position of the list.

Hence we are closing the issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-20 06:20 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Progress: done, Reported on 2.4.2, Component: Frontend
