### ISSUE TITLE
If product is in saved quote when customer is logged in, if product is then disabled/deleted, triggers infinite database query loop in Magento/Quote/Model/Quote.php and a 503 error when customer logs back in

### ISSUE THREAD

**Issue by Muhamann** [magento/magento2#33921] opened 2021-08-26 14:49 UTC
Hello,

i refer back to this issue:
https://github.com/magento/magento2/issues/6144

It was closed, but after closing, me and @Sharmilasrini95 reproduced it.

It still happens in our Magento 2.3.5-p1 regularly and i then need to clean table "quote".
So all saved carts are deleted... then user with this issue can login.

Can someone please reopen the issues/6144
Thank you!

**Comment by engcom-Echo** [comment] 2021-08-30 06:19
> Thanks @engcom-Echo
> I also couldnt reproduce it in the 2.4 instance.
> 
> I will now check 2.3.5.p1.
> Is it possible to let this also install here as a test instance like "give me 2.3.5-develop instance" ?

Hi @Muhamann , As per your comment, This issue is not reproducible on **2.4-develop**. 
Thus the issue reported might be already fixed in this branch. Please upgrade your magento version.
Since this issue is not reproducible on 2.4-develop, I am closing this issue. If you encounter this reported issue on 2.4-develop branch, please feel free to reopen this issue & write back to us.

**Closed as completed by engcom-Echo** 2021-08-30 06:19 UTC
Labels: non-issue

**Comment by Muhamann** [comment] 2021-08-30 06:48
@engcom-Echo 

I asked your for an explaination, how i can get develop instance for 2.3.5 ? Because not everybody can update on 2.4, so it would be very interesting for me to test, if this bug is in 2.3.5 p1

Thank you

**Comment by engcom-Echo** [comment] 2021-08-30 07:59
Hello @Muhamann 
I believe we wont be able to get an instance of 2.3.5 p1 via the magento bot, you might have the option of local installation only. But if I get any more information on this regard, will surely let you know.
Thank you.

**Comment by raghuiamsingh** [comment] 2024-09-10 08:08
still getting this issue, any updates?
