### ISSUE TITLE
"Select All" in Cache Management does not work

### ISSUE THREAD

**Issue by hans2103** [magento/magento2#3089] opened 2016-01-23 12:14 UTC
Magento 2 > Store > Cache Management
I want to be able to use Select ALL. I press the Dropdown button to view the options. The drop down does not appear.
There are no JS errors. 

![m2-cachemanagement-selectall](https://cloud.githubusercontent.com/assets/639822/12530096/e86d42f0-c1d2-11e5-8102-f1d99d7d4d93.gif)
(gif created with http://www.cockos.com/licecap/)

**Comment by vil11** [comment] 2016-01-26 16:34
Hello @hans2103, thanks for being attentive!

We can't reproduce described issue neither on **Mac** (Google Chrome, Safari) ...

<img width="617" alt="mac" src="https://cloud.githubusercontent.com/assets/5585456/12586526/5002ab34-c459-11e5-8b23-0b4ee6ab83ae.png">

... nor on **Win** (Google Chrome, Mozilla Firefox, IE)

![win](https://cloud.githubusercontent.com/assets/5585456/12586563/74c1afba-c459-11e5-9feb-187729476765.jpg)

Could you please give us more details (environment specifics, reproducibility on similar Admin data grids, possible preconditions) if you are still facing this problem?

**FYI:** You can clear all the _Cache Types_ at once by clicking the **Flush Magento Cache** primary button.

Dmytro Vilchynskyi, M2 QA engineer.

**Comment by raybogman** [comment] 2016-01-29 19:23
Same issue in M2 2.0.2 tested on Mac Chrome

**Comment by MomotenkoNatalia** [comment] 2016-03-01 12:55
https://github.com/magento/magento2/issues/3580

**Comment by MomotenkoNatalia** [comment] 2016-04-28 09:42
Hi all, Internal ticket MAGETWO-51803 will be soon delivered

**Comment by psydwannabe** [comment] 2016-06-10 16:35
This issue has been resolved internally and will likely be included in the next release as noted by @piotrekkaminski in #4080 [here](https://github.com/magento/magento2/issues/4080#issuecomment-222206366).

**Comment by veloraven** [comment] 2016-08-17 05:54
Closed as this issue was already fixed.

**Closed as completed by veloraven** 2016-08-17 05:54 UTC
Labels: Issue: Ready for Work, bug report
