### ISSUE TITLE
Create configurations: not all configurable attributes are visible 

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#29063] opened 2020-07-09 20:59 UTC
### Preconditions
1. Magento 2.4-develop
2. Demo content should be installed.

### Steps to reproduce 
1. Have a Magento store up and running with the demo store.
2. Create a new simple product and save it. 
3. Click on the "Create configurations" button.
4. By default it will show 20 attributes per page and there are 6 records found. See screenshot below
5. Change the number of results per page to "2"

![image](https://user-images.githubusercontent.com/1058480/87089744-31a35900-c237-11ea-88f8-c172e50d5dcc.png)

### Expected result
1. Same 6 records should show and since we have 2 items per page I should have 3 pages with 2 items each.

### Actual result
1. Grid now shows that there are 7 records found and it has 4 pages.
2. Some pages show only 1 record, while the page size is 2 records. See screenshot below.

![image](https://user-images.githubusercontent.com/1058480/87089883-61526100-c237-11ea-9cf1-0bb7f6b76711.png)

![image](https://user-images.githubusercontent.com/1058480/87089952-7d560280-c237-11ea-9c60-6ae45b96b84c.png)

![Peek 2020-08-14 14-47](https://user-images.githubusercontent.com/51681379/90248936-42507b80-de42-11ea-9f7b-7fa7c5064bed.gif)

### Severity

This is a issue with the highest severity. If a store has a lot of attributes which can be used for configurable products it's not usable anymore to page through those attributes even with a large number if items per page. In that case users are not able to select the attributes they want to use for the configurable products and there's no other way or workaround to create the simple products

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment] 2020-08-14 12:26
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36745` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dverkade** [comment] 2020-08-23 18:49
@sdzhepa, don't know why you're assigning this a P2 and S2 while it should be an S0 as explained in the description

> This is a issue with the highest severity. If a store has a lot of attributes which can be used for configurable products it's not usable anymore to page through those attributes even with a large number if items per page. In that case users are not able to select the attributes they want to use for the configurable products and there's no other way or workaround to create the simple products

It's not possible to create configurable products when you have a large number of configurable attributes on your site. This affects a critical part of Magento and there's no workaround available, so should be an S0 issue.

**Comment by sdzhepa** [comment] 2020-09-02 17:27
Hello @dverkade 

Sorry for the late response, I missed the notification...
We triaged it as P2 because due to the description it seems the problem only with drop-down "Per Page"(if he/she uses it).
But Admin still able to find attribute in the grid without "Per page" or use "Filter functionality"
So it's not blocked creating a configurable product just affect usability

Possibly I missed something let me double-check it in Magento

**Comment by sdzhepa** [comment] 2020-09-02 21:01
# Investigation result of product impact:

### Preconditions:
- Installed latest M2 based on `2.4-develop`
- as a test-data was used Performance Toolkit and small profile
`bin/magento setup:perf:generate-fixtures /var/www/html/magento2/setup/performance-toolkit/profiles/ce/small.xml`
- 58 attributes are available and can be used for Configurable product
- prepare a list in e.g. excel with a full list of attributes that should be available. During testing will be compared expected list vs real. [issue_29063.xlsx](https://github.com/magento/magento2/files/5164748/issue_29063.xlsx)



### Scenario/steps
1. Create new simple product and save
2. Open for edit Test simple product
3. Click "Create Configuration" under the Configuration section
4. Verify that all attributes are shown in the grid. with a different value for "per page" 



## Case 1: verify that each attribute in default configuration per each page (Per page = 20)

Example of verification approach and calculation: 
![issue_29063](https://user-images.githubusercontent.com/3409584/92035094-d02dd100-ed33-11ea-883f-4d394a7dbbd8.gif)


#### Results per page(total and how many shown on the page)
- Page 1 of 3: 58 records found (19 selected)
- Page 2 of 3: 59 records found (20 selected)  
- Page 3 of 3: 59 records found (19 selected)


### Verification that all 58 attributes are available and shown in the grid. Compare list of attributes and be sure that in total on all 3 pages all atrr is shown

#### Result: 
- each attribute is available and shown in the grig. Compared "InitialList vs result from pages(1+2+3)". Admin can find attributes in grid and use.
- There is an issue with the calculation of total records found in a grid "59 records found"
- There is an issue: 2 pages have "-1" records than expected


# Case 2: verify that each attribute with "Per page" = 5

- Page 1 of 12: 58 records found (4 selected)
- Page 2-11 of 12: 59 records found (5 selected)
- Page 12 of 12: 59 records found (4 selected)


### Verification that all 58 attributes are available and shown in the grid. Compare list of attributes and be sure that in total on all 12 pages all atrr is shown

#### Result: 
- each attribute is available and shown in the grig. Compared "InitialList vs result from pages(1+2+3)". Admin can find attributes in the grid and use.
- There is an issue with the calculation of total records found in a grid "59 records found"
- There is an issue: 2 pages have "-1" records than expected



## Case 3: verify that each attribute with "Per page" = 2

- Page 1 of 30: 59 records found (2 selected)
- Page 2 of 30: 58 records found (1 selected) 
- Page 3-29 of 30: 59 records found (2 selected)
- Page 30 of 30:  59 records found (1 selected)



#### Result: 
- each attribute is available and shown in the grig. Compared "InitialList vs result from pages(1+2+....+30)". Admin can find attributes in the grid and use.
- There is an issue with the calculation of total records found in a grid "59 records found"
- There is an issue: 2 pages have "-1" records than expected

## Case 5: each attribute can be found using "Filters" functionality. By Attribute Code, Attribute Lable

![issue_29063](https://user-images.githubusercontent.com/3409584/92036135-657d9500-ed35-11ea-941b-56d579b0cddf.jpg)

#### Result: 
- each of 58 attributes can be found by "Attribute Code" value
- each of 58 attributes can be found by part of "Attribute Code" value
- each attribute can be found by "Attribute Lable" value(full value and part)

**Comment by Bartlomiejsz** [comment] 2020-09-24 20:48
@magento I am working on this

**Comment by engcom-Delta** [comment] 2024-08-06 10:46
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment] 2024-08-06 11:57
Hi @dverkade ,

Thanks for your reporting and collaboration.
We have verified the issue in latest 2.4-develop instance, but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce.**

1. User should create a simple product and click on save.
2. Click on "Create Configurations" button
3. Observe 33 results are available.
4. Set number of results to 5 per page.
5. Observe 7 pages are displaying with 33 records which is expected.
![image](https://github.com/user-attachments/assets/cbdf8a8f-4271-4218-a98f-d81959a692ff)

6. Select and deselected items of page , observe result is displaying as expected
![image](https://github.com/user-attachments/assets/fdb5947c-52df-4f0f-888f-344bd5388318)

Please let us know if any other steps are needed to be performed.

Thanks.

**Closed as completed** 2024-08-06 13:39 UTC
Labels: Issue: Ready for Work, Issue: Format is valid, Component: Ui, Reproduced on 2.4.x, Priority: P3, Severity: S2, Progress: done, Issue: needs update, Reported on 2.4.0
