### ISSUE TITLE
Unable to place order with PayPal if maximum qty allowed in cart is 1

### ISSUE THREAD

**Issue by humpedli** [magento/magento2#7383] opened 2016-11-09 16:41 UTC
### Preconditions
1. Magento 2.1.1
2. PayPal payment option (sandbox or live)

### Steps to reproduce
1. Set Catalog / Inventory / Maximum Qty Allowed in Shopping Cart attribute to 1
2. Put one (downloadable) product into the cart and go to the checkout page
3. Choose PayPal checkout
4. Make a valid payment

### Expected result
1. Successful order
2. Thank you screen
3. Completed order

### Actual result
1. Order review screen with "_We can't place the order_" message
2. system.log message `main.CRITICAL: Exception message: The most you may purchase is 1.`
2. In progress order created with successful payment

**Comment by hpatelgit** [comment] 2016-11-23 13:26
Yes i am also getting same error with magento latest 2.1.2.

This error getting for any product type which has set 'Maximum Qty Allowed in Shopping Cart'.
Customer got this error when they try to place order with same product second time which has set 'Maximum Qty Allowed in Shopping Cart'.

This error is only for Paypal Payment Method.

Please let us know if any solution is there

Thanks

**Comment by hpatelgit** [comment] 2016-12-08 12:45
Any fix for this issue?

**Comment by iivashchenko** [comment] 2017-02-17 09:56
@hpatelgit Is it reproduced on PayPal Express Payment Method or you meant other PayPal solution?

**Comment by hpatelgit** [comment] 2017-02-17 10:35
@iivashchenko its happens with  PayPal Express.

**Comment by iivashchenko** [comment] 2017-02-17 12:16
@hpatelgit, thank you. That issue caused by the same reasons as [#6296](https://github.com/magento/magento2/issues/6296) .
I've linked it to internal ticket MAGETWO-58676. We already have a fix for it which would be delivered as soon as possible.

**Comment by alena-marchenko** [comment] 2017-02-24 14:38
Hi @humpedli 

Fix for MAGETWO-58676 is merged to develop branch, closing the issue.
Thank you.

**Closed as completed by alena-marchenko** 2017-02-24 14:38 UTC
Labels: Issue: Ready for Work, bug report, Component: Payment

**Comment by YohaiAllouche** [comment] 2017-04-24 07:00
Issue still happening in version 2.1.6
