### ISSUE TITLE
Configurable product Price not updated when choosing other variation in frontend

### ISSUE THREAD

**Issue by GuidoHub** [magento/magento2#10676] opened 2017-08-27 21:23 UTC
### Preconditions

1. Magento version 2.1.8
2. 

### Steps to reproduce

1. Add configurable product
2. Add variations based on attribute size (dropdown)
3. Set different prices for each variation

### Expected result

1. Would expect a different price when choosing different size in frontend product page but price isn't updated

### Actual result

1. Price stays the same

**Comment by DeadElle** [comment] 2017-08-28 11:07
#3150 partial solution in there.

@magento-team this bug pratically makes configurable products totally unusable on a working shop and it's still not fixed yet. :(

**Comment by orlangur** [comment] 2017-08-28 11:56
@GuidoHub are you talking about product page or category page?

**Comment by DeadElle** [comment] 2017-08-28 12:24
@orlangur category page

**Comment by orlangur** [comment] 2017-08-28 13:15
Then it's a duplicate of https://github.com/magento/magento2/issues/3150.

@DeadElle, thanks for pointing out.

**Comment by GuidoHub** [comment] 2017-08-28 16:15
Sorry but I am talking about the product detailpage, not the category page. When I choose a different size I would expect to see the price change. I can see that the images are reloaded so there is something happening.

**Comment by orlangur** [comment] 2017-08-28 16:42
@GuidoHub hm, such functionality worked within my recollection. Just a quick check before reop - did you reindex everything, flushed all caches etc? Also, it's always a good idea to check scenario in browser incognito mode to avoid possible browser cache influence.

**Comment by GuidoHub** [comment] 2017-08-28 21:48
@orlangur I am running in development mode at this moment. I have re-index and flush cache as far as you can do that in development mode but the price stays the same. I also run incognito mode by standard. When I add the product to my shopping cart I will see the right price so it's there. It's only not changed on the product detail page.

**Comment by GuidoHub** [comment] 2017-08-28 21:59
@orlangur Do you have a website that runs in production? I am trying to go in production for a while now but Magento has a lot of bugs. I can't imagine that anyone has a live webshop running on it. Especially when you are using configurable products. Out of stock not working, special prices buggy (old prices is shown without tax), category pages that can't be changed because you get message key already used and now this. For almost every functionality you have to develop an extension your self to solve bugs.

**Comment by orlangur** [comment] 2017-08-28 22:31
Well, there are quite a lot of such webshops: https://trends.builtwith.com/websitelist/Magento-2

> category pages that can't be changed because you get message key already used

This is due to incorrect migration/import. Never happens with valid category/product data.

**Comment by GuidoHub** [comment] 2017-08-29 10:52
@orlangur Don't want to get offtopic to much:) I have create the category by hand just to avoid these kind of problems.

The webshop you mentioned barely sell products and when they do it's all excluding tax and are in dollars. You have to agree that Magento is not really ready for european market. Like not having this working well https://github.com/magento/magento2/issues/7199

**Comment by GuidoHub** [comment] 2017-08-29 15:21
When I set option Stores->Configuration->Tax->Display Product Prices In Catalog to "Including and Excluding Tax" I expect to see the old prices also with and without tax but the strangest thing is that I get the following output:

`<span id="price-including-tax-old-price-502" data-label="Incl. BTW" data-price-amount="82.23" data-price-type="oldPrice" class="price-wrapper price-including-tax"><span class="price">€&nbsp;82,23</span></span>`

But the price is still without tax.

**Comment by GuidoHub** [comment] 2017-08-30 21:04
@orlangur I have been able to trace the problem. If had to do with two things. One because an extension (custom attribute for stock) broke my attributes and second the updated text swatch file in update 2.1.8. After disabling the module and replace the file with the one from 2.1.7 everything worked again.

**Comment by magento-engcom-team** [comment] 2017-09-19 08:33
@GuidoHub thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Closed as completed by magento-engcom-team** 2017-09-19 08:33 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid

**Comment by bhavikapatelgm** [comment] 2018-08-09 10:33
Facing same issue. anyone had any solution

**Comment by prdptom** [comment] 2018-10-29 09:14
Im facing the same issue again. I have a theme that is customized from Alpaca theme and in my configurable product page, the lowest price is shown and whenever a different size is selected by clicking the swatch, the price does not change.

**Comment by OhHeyAlan** [comment] 2019-03-23 18:46
I'm facing the same problem with the Freego theme and Magento 2.3

**Comment by orlangur** [comment] 2019-03-23 20:53
@prdptom @OhHeyAlan no way to fix it from Magento side, should be fixed by theme vendor.

**Comment by iloa08** [comment] 2020-08-27 09:08
Hi, 
some news for this post ?
I'm facing teh same :/

**Comment by hafsazulf** [comment] 2020-10-12 08:27
any solution>?
