### ISSUE TITLE
CMS Page URLkey issue on Magento 2

### ISSUE THREAD

**Issue by Sathishkumar8731** [magento/magento2#16400] opened 2018-06-26 10:36 UTC
### Preconditions

Using Latest Magento version 2.2.4
PHP 7.1.8
MYSQL
Linux OS

### Steps to reproduce

   1) Go to admin -> Content -> Pages -> Create a new Page.
   2) Need to enter the title as single word like "returns", so that the URL key is created as "returns".
   3)  Go to the blocks and add the page to the link 

<li><a href="{{store url ='returns'}}">Report Piracy</a></li>
4) When we click the link, the page is opening without header part (default home page header).
5) After change the Url key as "returns-policy", the links is working fine.
<li><a href="{{store url ='returns-policy'}}">Report Piracy</a></li>

### Expected result
Need to show the header section all type of Page url

**Comment by magento-engcom-team** [comment] 2018-06-26 10:36
Hi @Sathishkumar8731. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Sathishkumar8731 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Sathishkumar8731** [comment] 2018-06-26 10:38
### Preconditions

Using Latest Magento version 2.2.4
PHP 7.1.8
MYSQL
Linux OS


### Steps to reproduce

   1) Go to admin -> Content -> Pages -> Create a new Page.
   2) Need to enter the title as single word like "returns", so that the URL key is created as "returns".
   3)  Go to the blocks and add the page to the link 

<li><a href="{{store url ='returns'}}">Report Piracy</a></li>
4) When we click the link, the page is opening without header part (default home page header).
5) After change the Url key as "returns-policy", the links is working fine.
<li><a href="{{store url ='returns-policy'}}">Report Piracy</a></li>

### Expected result
Need to show the header section all type of Page url

**Comment by Sathishkumar8731** [comment] 2018-06-27 09:01
Hi Team, 

Could you please confirm whether the below issue is open or closed? If it is closed, please let me know the reason. 

CMS Page URLkey issue on Magento 2 #16400

**Comment by engcom-backlog-nickolas** [comment] 2018-07-03 07:56
@Sathishkumar8731, thank you for your report. Unfortunately I'm not able to reproduce this issue with given preconditions and steps to reproduce. Can you please provide more detailed steps? Also links, you've added lead me to 404 page.

**Comment by Sathishkumar8731** [comment] 2018-07-03 13:16
@engcom-backlog-nickolas 

Check the issue in Magento version 2.2.4

**Here are the steps to reproduce the issue**: 
  
1) Login into admin panel and go to Content -> Pages -> Create a new Page

2) Mention the title and URL key field with only one word 

**Example:**  Page Title:   returns 
                       URL key :    returns

3)  Create a new block or open the existing block

4) Add  the created page to any content ( link with any content) on this block

**Example:** 
<li> href="{{storeurl =returns}}"> Report Piracy </li>

5) After done the changes, open the created page. It  is opening without header part (default home page header).

6) where as its working fine while entering the Url key as "returns-policy"
{{store url ='returns-policy'}}

**Comment by engcom-backlog-nickolas** [comment] 2018-07-03 14:25
@Sathishkumar8731, thanks for your reply. I have my test block with a link on CMS home page.
 Can you please correct my steps?
![peek 2018-07-03 17-24](https://user-images.githubusercontent.com/40755810/42225697-d220feba-7ee5-11e8-94e7-fb5c5c3090a3.gif)

**Comment by Sathishkumar8731** [comment] 2018-07-03 14:34
@engcom-backlog-nickolas 

Thanks for your response. I understood, you insert like an widget. Could you please share the admin login credentials with access of pages and blocks, so that I will create a test page and explain you in detail.

**Comment by engcom-backlog-nickolas** [comment] 2018-07-03 14:38
@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment] 2018-07-03 14:38
Hi @engcom-backlog-nickolas. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment] 2018-07-03 14:39
Hi @engcom-backlog-nickolas, here is your [Magento instance](https://i-16400-2-2-4.engcom.dev.magento.com).
Admin access: [https://i-16400-2-2-4.engcom.dev.magento.com/admin](https://i-16400-2-2-4.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-backlog-nickolas** [comment] 2018-07-03 14:41
@Sathishkumar8731, you may try to use instance mentioned in comment above.

**Comment by Sathishkumar8731** [comment] 2018-07-03 14:50
@engcom-backlog-nickolas 

I have created a custom block in the admin panel.  could you please inform the Magento team to enable that block in front end. And then check the page link and let me know.

**Comment by engcom-backlog-nickolas** [comment] 2018-07-03 15:07
@Sathishkumar8731, thanks for your help. Now, I see what you mean. But, looks like the problem not with url, but because your page has no layout. So, if you specify layout ex: 1 column - it will work perfectly fine. You can check your page on instance, mentioned above.

**Comment by Sathishkumar8731** [comment] 2018-07-03 15:32
@engcom-backlog-nickolas 

Thanks. I have checked and it seems to be working.  Without layout mentioned, the page is loading fine now.

Let me cross check the issue once again by installing the fresh Magento package (2.2.4) in my local server and update it you.

**Comment by engcom-backlog-nickolas** [comment] 2018-07-03 15:37
@Sathishkumar8731, great, thanks!
About layout, could you please try one more thing? Try to flush cache, after applying changes to CMS page on instance, and you may see the difference.

**Comment by engcom-backlog-nickolas** [comment] 2018-07-04 15:07
@Sathishkumar8731, I'm closing this issue. If you'd like to update it, please fill free to reopen it.

**Closed as completed by engcom-backlog-nickolas** 2018-07-04 15:07 UTC
Labels: Progress: needs update, Issue: Clear Description, Issue: Format is not valid
