### ISSUE TITLE
Customer name in adminhtml's order detail is showing "Guest" 

### ISSUE THREAD

**Issue by hemendrametawolf** [magento/magento2#36915] opened 2023-02-23 11:36 UTC
### Summary

If you place an order as an guest, the displayed customer name in the adminhtml's order detail is "Guest". 

Preconditions (*)
Magento 2.4.4-p1 
Steps to reproduce (*)
Create an order as a guest
Open the placed order in the adminhtml
click on order view
Expected result (*)
The name of the guest should be displayed for "Customer Name"
Actual result (*)
"Guest" is displayed for "Customer Name" and it also showing in order confirmation email 

### Examples

Showing this in admin prder view 
![image](https://user-images.githubusercontent.com/114897672/220894660-978b35eb-becd-4432-bdfd-75bdf40b0d8e.png)

but in grid it showing name  for billing and shipping name

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hemendrametawolf** [comment] 2023-02-23 11:38
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by engcom-November** [comment] 2023-02-24 05:37
Hi @hemendrametawolf ,
Thank you for reporting and collaboration. Verified the issue in Magento 2.4-develop instance but the issue is not reproducible with below steps performed.
**Steps performed:**
1. Sales - Orders - Create new order
2. Click on Create new customer and place order as guest
3. View Order details grid - No issue. Customer name displayed as expected
4. View Order - Account information - Customer name displayed as expected.
Kindly recheck the issue on Magento 2.4-develop instance and provide missing steps if any if the issue is still reproducible.
![image](https://user-images.githubusercontent.com/60198231/221100578-204c17ba-7b51-4869-a2fd-023a1b9ffd2d.png)
![image](https://user-images.githubusercontent.com/60198231/221100629-660db786-2645-45b2-9365-cb7862cb3119.png)

**Comment by engcom-November** [comment] 2023-03-07 04:11
Hi @hemendrametawolf ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2023-03-07 04:11 UTC
Labels: Issue:  Cannot Reproduce, Triage: Dev.Experience, Issue: needs update
