### ISSUE TITLE
"Product Type is invalid or not supported in row" while trying to import images using a CSV

### ISSUE THREAD

**Issue by Loai-amr** [magento/magento2#38525] opened 2024-03-16 12:44 UTC
### Preconditions and environment

- Magento version: ver. 2.4.6-p2
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

I created a CSV file contain only 2 columns: SKU and base_image to import images to the product which are already in Magento
I'm getting: "Product Type is invalid or not supported in row"

### Expected result

The product images to be imported

### Actual result

"Product Type is invalid or not supported in row" error message

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-03-18 05:52
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-03-18 09:52
Hi @Loai-amr,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

![Screenshot from 2024-03-18 12-17-10](https://github.com/magento/magento2/assets/51680745/2635fbf3-7b28-4ae2-89ac-0d2c544f3af5)


We are able to import the CSV file with the Columns SKU an base_image.Kindly check your CSV file and type of the image.

Kindly recheck the issue in Latest Magento 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by Loai-amr** [comment] 2024-03-18 20:56
> Contributor

Hi @engcom-Bravo 
Thanks for taking the time to check this, here's a screenshot of the issue below and I also attached a sample CSV similar to the one I'm using for the import
[import_images.csv](https://github.com/magento/magento2/files/14642370/import_images.csv)

![image](https://github.com/magento/magento2/assets/66984384/54b3ef4d-1e82-4efb-966f-1efaa34715ca)

**Comment by engcom-Bravo** [comment] 2024-03-19 06:29
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-03-19 11:20
Hi @Loai-amr,

Thanks for your update.

Kindly refer this document regarding how the product CSV file should be https://experienceleague.adobe.com/en/docs/commerce-admin/systems/data-transfer/data-attributes-product


![Screenshot from 2024-03-19 14-36-30](https://github.com/magento/magento2/assets/51680745/e7677de2-4765-4e41-8610-c52834f0107f)


The Product CSV file should be like this and the path of image also :


[export_catalog_product_20240117_0200322.xlsx](https://github.com/magento/magento2/files/14648203/export_catalog_product_20240117_0200322.xlsx)



Kindly let us know if you are facing any issue.

Thanks.

**Comment by Loai-amr** [comment] 2024-03-19 11:33
Hi @engcom-Bravo,
Thanks for your response, I uploaded the product already, now I'm trying to upload only the images
I fixed the images path in the CSV file but still getting the same error on importing
[import_images (1).csv](https://github.com/magento/magento2/files/14649900/import_images.1.csv)

**Comment by engcom-Bravo** [comment] 2024-03-20 05:56
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-03-20 12:31
Hi @Loai-amr,

Thanks for your update.

We have tried with your CSV file and we are able to import but we are getting error because the images are not able to access.

![Screenshot from 2024-03-20 11-44-54](https://github.com/magento/magento2/assets/51680745/cd530f7f-6a43-4a5d-bd23-66ccd549c8a5)


Could you please let us know which error you are getting.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-04-01 04:23
Hi @Loai-amr,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-04-01 04:23 UTC
Labels: Issue: needs update, Reported on 2.4.6-p2
