### ISSUE TITLE
Issue with allure-framework/allure-phpunit while upgrading from Magento 2.4.2-P1 to 2.4.3 

### ISSUE THREAD

**Issue by engcom-November** [magento/magento2#34137] opened 2021-09-21 13:11 UTC
### Preconditions (*)

1. New installation of Magento 2.4.2-P1
2. Composer version 2.1.6
3. PHP 7.4.23

### Steps to reproduce (*)

1. Install Magento 2.4.2-P1 using composer
`composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition="2.4.2"`
`sudo php bin/magento setup:install --base-url=http://storeurl --db-host=localhost --db-name=dbname --db-user=username --db-password=yourpassword --admin-firstname=admin --admin-lastname=admin --admin-email=admin@admin.com --admin-user=admin --admin-password=admin123 --language=en_US --currency=USD --timezone=America/Chicago --use-rewrites=1 --backend-frontname=admin`
Login to admin and create product - No issue. working fine.
2. Upgrade to 2.4.3 using below steps:
`composer require magento/product-community-edition 2.4.3 --no-update`
`composer update`

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

**Error:**
![image](https://user-images.githubusercontent.com/60198231/134177428-556d1118-2b1d-448b-9841-9a5a45057c64.png)

**Workaround:**
User have to change "allure-framework/allure-phpunit": "~1.4" in composer.json and upgrade to resolve this issue.
Initial value was: 1.2.0
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment] 2021-09-21 18:36
@pdohogne-magento: shouldn't this be automatically handled by the https://github.com/magento/composer-root-update-plugin?

**Comment by pdohogne-magento** [comment] 2021-09-21 21:52
@hostep It should be, but I'm able to reproduce the issue.  I'm looking into it now.

**Comment by pdohogne-magento** [comment] 2021-09-21 22:06
This looks to be caused by an incompatibility with recent versions of composer.  I'm opening a ticket for it and will make sure it gets addressed soon.  In the meantime, this requirement can either be adjusted manually as above or composer can be rolled back to pre-2.1.

**Comment by engcom-Hotel** [comment] 2021-12-14 14:11
composer-root-update-plugin version ~2.0  change has already been made and will be released in 2.4.4
 
To upgrade from pre-2.4.4 using the new require-commerce command, users will need to require the new version of the plugin manually, but any fresh installation of 2.4.4 (or higher, when we get there) will include the correct plugin version.
 
Of note, the previous version of the plugin will still work on Composer 2.1.5 or earlier using the composer require command, after which the plugin will auto-update itself to match the latest requirement in 2.4.4 and pick up the new command.

**Closed as completed by engcom-Hotel** 2021-12-14 14:11 UTC
Labels: Issue: Confirmed, Component: Composer, Reproduced on 2.4.x, Priority: P1, Progress: done, Reported on 2.4.2-p1, Area: Upgrades - Upgrade Compatibility Tool
