### ISSUE TITLE
Sample Files for Unsalable Products Redirect Instead of Download

### ISSUE THREAD

**Issue by samuel-reinhardt** [magento/magento2#23638] opened 2019-07-09 13:20 UTC
### Preconditions (*)

1. 2.4-develop
2. Set Stores->Catalog->Inventory->Stock Options->Display Out of Stock Products=Yes

### Steps to reproduce (*)

1. Login to admin
2. Go to Catalog-->Products
3. Select 'Downloadable product' from 'Add product' button dropdown
4. Fill all required inputs 
5. Set product status to 'Out to stock'
6. Go to 'Downloadable information' tab
7. Press 'Add link' button under a Samples 
8. Add any test file
9. Save a product
10. Go to the product page on the frontend
11. Press on link under 'Samples'

### Expected result (*)

1. By default, the sample file should be downloaded. Products that are not currently for sale should still allow customers to download samples. 

### Actual result (*)

1. New tab is opened. No download is started and no explanation is given.

**Comment by samuel-reinhardt** [comment] 2019-07-09 13:21
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-09 13:21
Hi @samuel-reinhardt. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-09 13:22
Hi @samuel-reinhardt, here is your [Magento instance](https://i-23638-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23638-2-3-develop.instances.magento-community.engineering/admin](https://i-23638-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by samuel-reinhardt** [comment] 2019-07-09 13:37
This issue is not present on 2.2-develop or 2.3-develop. 2.2 and 2.3 releases do contain the issue however. It is due to this commit in which a salable check is added to the sample downloads logic.
https://github.com/magento/magento2/commit/9498c975b45999b4aba69568f6be1457116d702f#diff-3ce343f8897fe36416d4a848dab0a7da

**Comment by magento-engcom-team** [comment] 2019-07-09 18:12
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17998`, `MC-17999` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ihor-sviziev** [comment] 2019-09-26 08:59
Hi @samuel-reinhardt and @engcom-Charlie,

Following commit https://github.com/magento/magento2/commit/484c8530afe0a2003d9f52517f64131ae04ac722 added check that product is salable, while following MFTF test https://github.com/magento/magento2/blob/e93feb02398f158f79fefb14de95cf93e3ec0786/app/code/Magento/Downloadable/Test/Mftf/Test/VerifyDisableDownloadableProductSamplesAreNotAccessibleTest.xml#L15 describes that it should check that product is enabled.



Actually for product we have 4 params that could affect product visibility on frontend:
1. Status
2. Visibility
3. Association with website
4. Stock status (on some websites we could enable showing out of stock products)

Maybe there even more.

Could you clarify what exact steps to reproduce this issue?

Thank you

**Comment by engcom-Charlie** [comment] 2019-09-26 09:44
Hello @ihor-sviziev 
**Manual testing scenario:**

1. Login to admin
2. Go to Catalog-->Products
3. Select 'Downloadable product' from 'Add product' button dropdown
4. Fill all required inputs 
5. Set product status to 'Out to stock'
6. Go to 'Downloadable information' tab
7. Press 'Add link' button under a Samples 
8. Add any test file
9. Save a product
10. Go to the product page on the frontend
11. Press on link under 'Samples'

**Expected result:**
By default, the sample file should be downloaded. Products that are not currently for sale should still allow customers to download samples.

**Actual result:**
New tab is opened. No download is started and no explanation is given.

**Comment by ihor-sviziev** [comment] 2019-09-26 11:05
Hi @engcom-Charlie,
Maybe we're missing something, but looks like expected result is conflicting with following MFTF test:
https://github.com/magento/magento2/blob/e93feb02398f158f79fefb14de95cf93e3ec0786/app/code/Magento/Downloadable/Test/Mftf/Test/VerifyDisableDownloadableProductSamplesAreNotAccessibleTest.xml

If it's not conflicting - could you give us more info from MC-15845 and MC-14824 to understand whole picture?

**Comment by ihor-sviziev** [comment] 2019-09-26 11:11
@engcom-Charlie,
Looks I found the diff. Sample file **should not be available** when product Status "Enabled". So now everything is clear.
Sorry for misunderstanding

**Comment by magento-engcom-team** [comment] 2020-06-25 12:17
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35455` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2020-07-11 19:20
Hi @samuel-reinhardt. Thank you for your report. 
The issue has been fixed in magento/magento2#28898 by @engcom-Charlie in 2.4-develop branch
Related commit(s):
 - [f9d4e0abb7d019b1745f9d85fd20927af1c22c42](https://github.com/magento/magento2/commit/f9d4e0abb7d019b1745f9d85fd20927af1c22c42)
 - [0ea00f04b8dab17c396d8248280fed9ab08e5230](https://github.com/magento/magento2/commit/0ea00f04b8dab17c396d8248280fed9ab08e5230)

The fix will be available with the upcoming 2.4.1 release.

**Closed as completed by magento-engcom-team** 2020-07-11 19:20 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Downloadable, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P3, Severity: S3
