### ISSUE TITLE
different backup download links on backups page all point to the same file/url of the last backup

### ISSUE THREAD

**Issue by nldudok1** [magento/magento2#5968] opened 2016-08-03 16:51 UTC
When you make multiple backups they all show up on the backups page. They all have a clickable link so you can download the backup file. Each link should be unique and point to that specific backup. But all links are the same and all point only to the last backup.

### Preconditions

1. Magento 2.1.0 freshinstall     Magento-CE-2.1.0-2016-06-23-02-28-50.tar.bz2
2. PHP 5.6.23-0+deb8u1 (cli) (built: Jul 12 2016 07:33:16)
3. Apache 2.4
4. debian 8.5 
5. mysql --version
   mysql  Ver 15.1 Distrib 10.0.25-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
### Steps to reproduce

1. Go to System/backup
2. Create a system backup
3. Create a database backup
4. Create another database backup
   Now you should have three unique backups. But the .tgz and .sql links on each line all point to the last backup, which is in this case a .sql file of the second database backup.
### Expected result

1. All links should be unique and result in downloading the backup you selected. 
### Actual result

1. See screenshots. In the first screenshot I hover over the .tgz link of the last backup. See the url at the bottom of the screenshot. In screenshot 2, I hover over the .tgz link of the second backup. See that the url is the same. In screenshot 3 you see that when I click the .tgz link, I actually download  the .sql file of the last backup. (EDIT: I now see that the screenshot did not actually show the url in the bottombar, so you will just have to try yourself)
   ![screenshot magento backup link 1 from 2016-08-03 18 30 34](https://cloud.githubusercontent.com/assets/1155994/17373787/175e1ac0-59aa-11e6-981d-49d5087e86f8.png)
   ![screenshot magento backup link 2 from 2016-08-03 18 30 55](https://cloud.githubusercontent.com/assets/1155994/17373789/1761a6b8-59aa-11e6-9327-2bf8031c9fd6.png)
   ![screenshot magento backup link download from 2016-08-03 18 31 28](https://cloud.githubusercontent.com/assets/1155994/17373788/175e7fce-59aa-11e6-9c97-ef0cad4a17a8.png)

[Screenshot, logs]

**Comment by Sergeacc** [comment] 2017-06-30 13:45
@nldudok1 Thanks for reporting this issue, internal ticket was created MAGETWO-70384.

**Comment by magento-engcom-team** [comment] 2017-10-06 15:07
@nldudok1, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by Mobecls** [comment] 2017-12-15 09:22
#mageconf

**Comment by dmanners** [comment] 2018-05-03 13:32
Since this has been fixed in 2.3-develop with the pr https://github.com/magento/magento2/pull/10593 this ticket would just require someone to backport and test this fix on 2.1 and 2.2 versions.

**Comment by stetoc** [comment] 2018-05-12 12:06
I tried to reproduce error on 2.2, tried various combinations and everything looks fine, looks like error is not a thing anymore. Each download url is pointing to different file, every database dump is containing valid data reflecting real database state before backup.

**Comment by sidolov** [comment] 2018-06-11 15:12
Issue has been fixed in scope of https://github.com/magento/magento2/pull/11595

**Closed as completed by sidolov** 2018-06-11 15:12 UTC
Labels: Issue: Ready for Work, bug report, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Fixed in 2.3.x, Issue: Format is valid, help wanted
