### ISSUE TITLE
 Adding items in wishlist from category page is displaying a $0.00 prices

### ISSUE THREAD

**Issue by wenpingguo** [magento/magento2#7386] opened 2016-11-10 05:33 UTC
### Preconditions

1. Default Magento 2.1.1 or 2.1.2

### Steps to reproduce

1. Login to the website
2. navigate to a category page 
3. add a product to wish-list 
4. go to wish-list page

### Expected result

1. Product added to wish-list showing the correct price.

### Actual result

1. showing $0.00 price for the product

video record: http://take.ms/oNk8h
Screenshot
If you select configurable options in product page and add to wish list, the price showing correctly. 
![my wish list 2016-11-10 16-30-36](https://cloud.githubusercontent.com/assets/19483820/20165653/4c8885d0-a763-11e6-8e6a-31d1c5deab09.png)

**Comment by sevos1984** [comment] 2016-11-10 15:41
This is a known issue, internal ticket MAGETWO-59420

**Comment by wenpingguo** [comment] 2016-11-15 05:30
Located the issue in 
`vendor/magento/module-wishlist/view/frontend/layout/wishlist_index_index.xml`
change
`<argument name="price_type_code" xsi:type="string">wishlist_configured_price</argument>`
to 
`<argument name="price_type_code" xsi:type="string">final_price</argument>`

Fixes in my theme, create 
`app/design/frontend/<Vendor>/<Theme>/Magento_Wishlist/layout/wishlist_index_index.xml`
And add the following to in side body
`<referenceBlock name="product.price.render.wishlist">
            <arguments>
                <argument name="price_type_code" xsi:type="string">final_price</argument>
            </arguments>
</referenceBlock>`

**Comment by ghost** [comment] 2016-11-29 09:07
I had the same problem and wenpingguo solution fixed it for me too.

**Comment by Bartlomiejsz** [comment] 2017-06-09 12:20
@veloraven @wenpingguo The bug also exists in sidebar wishlist (on Magento 2.1.7!).
The line that causes it is: `\Magento\Wishlist\CustomerData\Wishlist:129`

**Comment by hostep** [comment] 2017-06-09 19:56
This is most likely a duplicate of https://github.com/magento/magento2/issues/6866
Which was already fixed on the develop branch under MAGETWO-59512. I created a backport for the 2.1-develop branch around a month ago: https://github.com/magento/magento2/pull/9571, let's hope it gets included in the next minor 2.1.x release soon...

**Comment by magento-engcom-team** [comment] 2017-10-09 14:30
@wenpingguo, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-09 14:30 UTC
Labels: Issue: Ready for Work, bug report, Issue:  Cannot Reproduce, Issue: Format is valid
