### ISSUE TITLE
Theme templates for StockAlert and PriceAlert (Magento_ProductAlert/templates/email/price.phtml and stock.phtml) emails not taking priority

### ISSUE THREAD

**Issue by boardwalki** [magento/magento2#36341] opened 2022-10-20 16:45 UTC
### Preconditions and environment

Magento ver. 2.4.5-p1
php 8

### Steps to reproduce

1. Copy 
/vendor/magento/module-product-alert/view/frontend/templates/email/stock.php 
and 
/vendor/magento/module-product-alert/view/frontend/templates/email/price.php 
to theme folder:

/Mytheme/default/Magento_ProductAlert/templates/email/stock.php 
and
/Mytheme/default/Magento_ProductAlert/templates/email/price.php

2. Modify text in custom theme files stock.php and price.php
3. Flush cache and deploy static content
4. Send stock/price alert email

### Expected result

Email received should reflect the custom theme templates for stock.php and price.php

### Actual result

Email is not utilizing the customer templates, instead using the core module templatesd

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-11-25 14:44
Hi @boardwalki ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance with default product alerts email templates and no product alert emails are getting triggered currently. There is an ongoing confirmed issue [here](https://github.com/magento/magento2/issues/35602) for the same. Kindly move on to this issue for latest updates / solutions on the same. We are moving this issue to On hold as this needs to be tested once above issue is resolved.
Thank you.

**Comment by engcom-November** [comment] 2023-01-13 05:33
@magento give me 2.4-develop instance

**Comment by mpchadwick** [comment] 2023-02-02 15:44
@boardwalki - Did you find a solution for this?

**Comment by boardwalki** [comment] 2023-02-02 16:58
Sorry, I have not been updated with a solution yet.

**Comment by piuga** [comment] 2023-03-03 07:03
Until the issue is fixed, a workaround for us was to create an after plugin for getTemplate() function for Magento\ProductAlert\Block\Email\Stock: 

`<?php

declare(strict_types=1);

namespace MyCompany\ExtendedProductAlert\Plugin;

use Magento\ProductAlert\Block\Email\Stock;

class UseCustomEmailTemplate
{
    public function afterGetTemplate(Stock $subject, string $template): string
    {
        return 'MyCompany_ExtendedProductAlert::email/stock.phtml';
    }
}`

And change the stock template in the custom module. The same can be done for price alert.

**Comment by sprankhub** [comment] 2023-05-05 13:33
If I am not mistaken, this is fixed by https://github.com/magento/magento2/commit/b8f8ed5aafd283987c1d7f6a7a124966f4470d0d.

**Comment by engcom-Hotel** [comment] 2023-05-31 14:23
Hello @engcom-November,

As per the above comment, the issue has been resolved. Can you please check this?

Thanks

**Comment by engcom-Hotel** [comment] 2023-06-21 09:37
Hello @sprankhub,

As per your comment here https://github.com/magento/magento2/issues/36341#issuecomment-1536271263, we have rechecked this issue. But we are not able to get the Alert emails due to this issue, https://github.com/magento/magento2/issues/35602, this issue is already in a confirmed state. 

Hence moving this issue `on hold` again.

Thanks

**Comment by engcom-Hotel** [comment] 2024-06-27 11:43
Hello @boardwalki,

We have tried to reproduce this issue in the latest development branch i.e. 2.4-develop and the issue is not reproducible for us. We are able to get the customized email alerts.

We have used a custom theme for this and activated that theme from the admin panel for that store. Are you still able to reproduce this issue at your end?

Thanks

**Comment by engcom-Hotel** [comment] 2024-07-12 06:16
Dear @boardwalki,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we're assuming it's been resolved and will be closing it. Feel free to open a new ticket or reopen this one if you require further assistance.

Regards

**Closed as completed by engcom-Hotel** 2024-07-12 06:16 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.5-p1
