### ISSUE TITLE
Unable to get Downloadble link on Invoice and Order Confirmation Email when Order Placed by Configured Product Type's child product has a Downloadable type Product

### ISSUE THREAD

**Issue by dasharath-wagento** [magento/magento2#12918] opened 2017-12-29 09:01 UTC
### Preconditions

1. Magento 2.2.2

### Steps to reproduce

1.  Go to Admin -> Catalog -> Products -> Create a new configurable type product
2.  Edit configurable's child product and Make it to downloadable.
3. Go to frontend and place an order for the configurable product and select the downloadable product from the option .after not getting a downloadable link to Order Confirmation Email and Invoice Email.
Place an Order using guest order or register account.

### Expected result

1.  The downloadable link should be shown Order Confirmation Email and Invoice Email.

### Actual result

1. 
![screenshot-mail google com-2017-12-29-14-27-01-087](https://user-images.githubusercontent.com/18435810/34433376-e2e28490-eca4-11e7-91bb-ccd6b0659138.png)

**Comment by magento-engcom-team** [comment] 2017-12-29 09:04
Duplicate of #12885

**Closed as completed** 2017-12-29 09:04 UTC
Labels: Issue: Format is valid
