### ISSUE TITLE
Braintree error : Your payment could not be taken. Please try again or use a different payment method. Cannot refund transaction unless it is settled.

### ISSUE THREAD

**Issue by poojapawar12** [magento/magento2#37588] opened 2023-06-07 10:25 UTC
### Preconditions and environment

- Magento version : 2.4.6
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

1) In sandbox environment  Place order with brain tree creditcard and it will generate invoice as well
2) Go To the order invoice and create Credit memo
3) you will receive error "Your payment could not be taken. Please try again or use a different payment method. Cannot refund transaction unless it is settled"
![image](https://github.com/magento/magento2/assets/133887565/c67286fc-c6c7-4d46-bdaf-563eaafa3539)
**3) payment log :**

[2023-06-07T10:00:01.416492+00:00] report.DEBUG: array (
  'request' => 
  array (
    'transaction_id' => '483cqnzq',
    'amount' => '239.95',
  ),
  'client' => 'PayPal\\Braintree\\Gateway\\Http\\Client\\TransactionRefund',
  'response' => 
  array (
    '' . "\0" . '*' . "\0" . '_attributes' => 
    array (
      'errors' => 
      Braintree\Error\ErrorCollection::__set_state(array(
         '_errors' => 
        Braintree\Error\ValidationErrorCollection::__set_state(array(
           '_collection' => 
          array (
          ),
           '_errors' => 
          array (
          ),
           '_nested' => 
          array (
            'transaction' => 
            Braintree\Error\ValidationErrorCollection::__set_state(array(
               '_collection' => 
              array (
              ),
               '_errors' => 
              array (
                0 => 
                Braintree\Error\Validation::__set_state(array(
                   '_attribute' => 'base',
                   '_code' => '91506',
                   '_message' => 'Cannot refund transaction unless it is settled.',
                )),
              ),
               '_nested' => 
              array (
              ),
            )),
          ),
        )),
      )),
      'params' => 
      array (
        'transaction' => 
        array (
          'amount' => '239.95',
        ),
        'merchantId' => 'q8b7zw3f9qckqnmy',
        'id' => '483cqnzq',
      ),
      'message' => 'Cannot refund transaction unless it is settled.',
      'creditCardVerification' => NULL,
      'transaction' => NULL,
      'subscription' => NULL,
      'merchantAccount' => NULL,
      'verification' => NULL,
    ),
    'success' => false,
  ),
) [] []

4) In sandbox account payment status is  : **submitted_for_settlement**
5) Screen shot : 
![image](https://github.com/magento/magento2/assets/133887565/1ae2ab91-aff1-4e5d-9bde-ddf5d6bfb16a)

### Expected result

credit memo should created correctly without error

### Actual result

getting error  : Your payment could not be taken. Please try again or use a different payment method. Cannot refund transaction unless it is settled.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-06-07 11:06
Hi @poojapawar12,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4.6 instance and the issue is not reproducible.Kindly refer the attached video.


**Steps to reproduce**

- In sandbox environment Place order with brain tree creditcard and it will generate invoice as well
- Go To the order invoice and create Credit memo

We are able to complete both the invoice and credit memo successfully.


https://github.com/magento/magento2/assets/51680745/8de0b6f4-bec7-4304-bf8c-5bb5399ebdf2



Kindly recheck the behaviour on Magento 2.4.6 instance and elaborate steps to reproduce if the issue is still reproducible.



Thanks.

**Comment by poojapawar12** [comment] 2023-06-07 11:39
Hello @engcom-Bravo ,

On my site we are also able to create Credit memo using offline refund but not able to create refund online please refer attached 

https://github.com/magento/magento2/assets/133887565/211b5e42-f878-45b7-9b40-93c93a58eb70

video

**Comment by DavaGordon** [comment] 2023-06-15 18:43
We are also having this issue but we are using 2.4.2 only seems to be in intermittent issue as some orders goes though but we have noticed a massive drop in conversions as a result.

`[2023-06-15 18:04:23] main.ERROR: Magento2 v2.9.5: Your payment could not be taken. Please try again or use a different payment method. Authentication Required [] []
[2023-06-15 18:04:23] main.ERROR: Magento2 v2.9.5: #0 /home/picsmeco/public_html/vendor/magento/module-payment/Model/Method/Adapter.php(549): PayPal\Braintree\Gateway\Command\GatewayCommand->execute(Array)
#1 /home/picsmeco/public_html/vendor/magento/module-payment/Model/Method/Adapter.php(451): Magento\Payment\Model\Method\Adapter->executeCommand('authorize', Array)
#2 /home/picsmeco/public_html/vendor/magento/module-sales/Model/Order/Payment/Operations/AuthorizeOperation.php(45): Magento\Payment\Model\Method\Adapter->authorize(Object(Magento\Sales\Model\Order\Payment\Interceptor), 12.39)
#3 /home/picsmeco/public_html/vendor/magento/module-sales/Model/Order/Payment/Processor.php(72): Magento\Sales\Model\Order\Payment\Operations\AuthorizeOperation->authorize(Object(Magento\Sales\Model\Order\Payment\Interceptor), true, 12.39)
#4 /home/picsmeco/public_html/vendor/magento/module-sales/Model/Order/Payment.php(1136): Magento\Sales\Model\Order\Payment\Processor->authorize(Object(Magento\Sales\Model\Order\Payment\Interceptor), true, 12.39)
#5 /home/picsmeco/public_html/vendor/magento/module-sales/Model/Order/Payment.php(458): Magento\Sales\Model\Order\Payment->authorize(true, 12.39)
#6 /home/picsmeco/public_html/vendor/magento/module-sales/Model/Order/Payment.php(385): Magento\Sales\Model\Order\Payment->processAction('authorize', Object(Magento\Sales\Model\Order\Interceptor))
#7 /home/picsmeco/public_html/vendor/magento/module-sales/Model/Order.php(983): Magento\Sales\Model\Order\Payment->place()
#8 /home/picsmeco/public_html/vendor/magento/module-sales/Model/Order.php(1205): Magento\Sales\Model\Order->_placePayment()
#9 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Order->place()
#10 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Order\Interceptor->___callParent('place', Array)
#11 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Order\Interceptor->Magento\Framework\Interception\{closure}()
#12 /home/picsmeco/public_html/generated/code/Magento/Sales/Model/Order/Interceptor.php(356): Magento\Sales\Model\Order\Interceptor->___callPlugins('place', Array, Array)
#13 /home/picsmeco/public_html/vendor/magento/module-sales/Model/Service/OrderService.php(209): Magento\Sales\Model\Order\Interceptor->place()
#14 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Service\OrderService->place(Object(Magento\Sales\Model\Order\Interceptor))
#15 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Service\OrderService\Interceptor->___callParent('place', Array)
#16 /home/picsmeco/public_html/vendor/stripe/module-payments/Plugin/Sales/Model/Service/OrderService.php(25): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Sales\Model\Order\Interceptor))
#17 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(135): StripeIntegration\Payments\Plugin\Sales\Model\Service\OrderService->aroundPlace(Object(Magento\Sales\Model\Service\OrderService\Interceptor), Object(Closure), Object(Magento\Sales\Model\Order\Interceptor))
#18 /home/picsmeco/public_html/vendor/magento/module-inventory-sales/Plugin/Sales/OrderManagement/AppendReservationsAfterOrderPlacementPlugin.php(195): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Sales\Model\Order\Interceptor))
#19 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\InventorySales\Plugin\Sales\OrderManagement\AppendReservationsAfterOrderPlacementPlugin->aroundPlace(Object(Magento\Sales\Model\Service\OrderService\Interceptor), Object(Closure), Object(Magento\Sales\Model\Order\Interceptor))
#20 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Sales\Model\Order\Interceptor))
#21 /home/picsmeco/public_html/generated/code/Magento/Sales/Model/Service/OrderService/Interceptor.php(86): Magento\Sales\Model\Service\OrderService\Interceptor->___callPlugins('place', Array, NULL)
#22 /home/picsmeco/public_html/vendor/magento/module-quote/Model/QuoteManagement.php(566): Magento\Sales\Model\Service\OrderService\Interceptor->place(Object(Magento\Sales\Model\Order\Interceptor))
#23 /home/picsmeco/public_html/vendor/magento/module-quote/Model/QuoteManagement.php(456): Magento\Quote\Model\QuoteManagement->submitQuote(Object(Magento\Quote\Model\Quote\Interceptor), Array)
#24 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\QuoteManagement->submit(Object(Magento\Quote\Model\Quote\Interceptor))
#25 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\QuoteManagement\Interceptor->___callParent('submit', Array)
#26 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Quote\Model\Quote\Interceptor))
#27 /home/picsmeco/public_html/generated/code/Magento/Quote/Model/QuoteManagement/Interceptor.php(68): Magento\Quote\Model\QuoteManagement\Interceptor->___callPlugins('submit', Array, Array)
#28 /home/picsmeco/public_html/vendor/magento/module-quote/Model/QuoteManagement.php(414): Magento\Quote\Model\QuoteManagement\Interceptor->submit(Object(Magento\Quote\Model\Quote\Interceptor))
#29 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\QuoteManagement->placeOrder('32613', NULL)
#30 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\QuoteManagement\Interceptor->___callParent('placeOrder', Array)
#31 /home/picsmeco/public_html/vendor/mageworx/module-giftcardsbase/Plugin/Api/ValidateGiftCardsBeforePlaceOrderPlugin.php(121): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}('32613', NULL)
#32 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(135): MageWorx\GiftCards\Plugin\Api\ValidateGiftCardsBeforePlaceOrderPlugin->aroundPlaceOrder(Object(Magento\Quote\Model\QuoteManagement\Interceptor), Object(Closure), '32613', NULL)
#33 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}('32613', NULL)
#34 /home/picsmeco/public_html/generated/code/Magento/Quote/Model/QuoteManagement/Interceptor.php(50): Magento\Quote\Model\QuoteManagement\Interceptor->___callPlugins('placeOrder', Array, Array)
#35 /home/picsmeco/public_html/vendor/magento/module-quote/Model/GuestCart/GuestCartManagement.php(87): Magento\Quote\Model\QuoteManagement\Interceptor->placeOrder('32613', NULL)
#36 /home/picsmeco/public_html/vendor/magento/module-checkout/Model/GuestPaymentInformationManagement.php(127): Magento\Quote\Model\GuestCart\GuestCartManagement->placeOrder('IpUhcDtrsn09hRL...')
#37 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Model\GuestPaymentInformationManagement->savePaymentInformationAndPlaceOrder('IpUhcDtrsn09hRL...', 'staceyjayne19@g...', Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#38 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->___callParent('savePaymentInfo...', Array)
#39 /home/picsmeco/public_html/vendor/stripe/module-payments/Plugin/GuestPaymentInformationManagement.php(61): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->Magento\Framework\Interception\{closure}('IpUhcDtrsn09hRL...', 'staceyjayne19@g...', Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#40 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(135): StripeIntegration\Payments\Plugin\GuestPaymentInformationManagement->aroundSavePaymentInformationAndPlaceOrder(Object(Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor), Object(Closure), 'IpUhcDtrsn09hRL...', 'staceyjayne19@g...', Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#41 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->Magento\Framework\Interception\{closure}('IpUhcDtrsn09hRL...', 'staceyjayne19@g...', Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#42 /home/picsmeco/public_html/generated/code/Magento/Checkout/Model/GuestPaymentInformationManagement/Interceptor.php(23): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->___callPlugins('savePaymentInfo...', Array, NULL)
#43 [internal function]: Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder('IpUhcDtrsn09hRL...', 'staceyjayne19@g...', Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#44 /home/picsmeco/public_html/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)
#45 /home/picsmeco/public_html/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process(Object(Magento\Framework\Webapi\Rest\Request\Proxy))
#46 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#47 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)
#48 /home/picsmeco/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#49 /home/picsmeco/public_html/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)
#50 /home/picsmeco/public_html/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#51 /home/picsmeco/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#52 /home/picsmeco/public_html/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http\Interceptor->launch()
#53 /home/picsmeco/public_html/pub/index.php(29): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#54 {main} [] []`

**Comment by engcom-Bravo** [comment] 2023-06-20 10:03
@DavaGordon issue has reported here https://github.com/magento/magento2/issues/37623 Kindly move onto this issue for latest updates / solutions on the same.
 
@poojapawar12,

Please provide us update on this https://github.com/magento/magento2/issues/37588#issuecomment-1582066480 and kindly let us know still you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-07-03 05:25
Hi @poojapawar12,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-07-03 05:25 UTC
Labels: Issue: needs update, Reported on 2.4.6

**Comment by emmameloni** [comment] 2024-03-01 09:28
Hello, We have an ecommerce in the retail sector, unfortunately very often customers fail to pay. We receive as a message  "Your payment could not be taken. Please try again or use a different payment method. Processor Declined". Can you explain why? Customers pay by credit card
