### ISSUE TITLE
Disabling Magento_Review results in "Attention: Something went wrong."

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#8779] opened 2017-03-03 10:56 UTC
### Preconditions

1. Magento 2.1.2
2. Developer mode
3. Sample data installed (any data is fine)

### Steps to reproduce

1. In Admin, go to Stores / Configuration / Advanced / Advanced and disable **Magento_Review**
2. Go to Products / Inventory / Catalog and edit any product; upon loading the edit product page, you will get this error:

![image](https://cloud.githubusercontent.com/assets/4110567/23548298/ca0c6620-0041-11e7-8d20-f9209d466bba.png)

3. Make a change to the product (e.g., change **Enable Product** to **No**) and click the Save button. 4. Reload the page; you will see that the setting was never saved.

### Expected result

1. When you make a change to the product and click Save, the settings should be saved.

### Actual result

1. After you click the Save button, you will get the "You saved the product." message, but it's misleading because actually nothing gets saved.

It appears that when the Reviews module is disabled, the edit product page tries to retrieve some reviews data, but since the module is disabled it trips up and stalls in a loading loop (i.e., it never exits out of the spinner state in the right):

![image](https://cloud.githubusercontent.com/assets/4110567/23548523/dffa2f0c-0042-11e7-9ac9-421460c44fea.png)

**Comment by thomvanderboon** [comment] 2017-03-03 18:32
Duplicate of https://github.com/magento/magento2/issues/6264

Please close this issue

Thom

**Closed as completed** 2017-03-04 05:46 UTC
