### ISSUE TITLE
checkout_cart_add_product_complete  magneto 2 events not trigger 

### ISSUE THREAD

**Issue by Sanjay-100** [magento/magento2#35273] opened 2022-04-06 10:03 UTC
### Preconditions (*)

1.  mangeto 2.3.0 
2.

### Steps to reproduce (*)

1. fresh new magento 2.3 instance  
2. add this module's code  here is code  https://github.com/Sanjay-100/m2eventobserver
 
### Expected result (*)

1. when add to a cart button press on store front event should call and run the observer code

### Actual result (*)

1. when adding to cart button press need to run custom code on that function.
2. page should be not reloaded.  when I try to use  *checkout_cart_add_product_complete *  this will reload page.
 
 
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Sanjay-100** [comment] 2022-04-06 10:07
Summary of the issue: magneto 3 default evet\nt not able to use that 
Information on your environment: magneto 2.3 
Steps to reproduce : add the test modules code  https://github.com/Sanjay-100/m2eventobserver
Expected and actual results :  when adding to cart button press need to run custom code on that function.
page should be not reloaded. when I try to use *checkout_cart_add_product_complete * this will reload page.

**Comment by rpriya-sinha** [comment] 2022-04-06 11:11
@magento give me 2.4-develop instance

**Comment by Sanjay-100** [comment] 2022-04-07 05:36
@rpriya-sinha.  the add to cart event not working with Magento modules  add this module's code here is code https://github.com/Sanjay-100/m2eventobserver you can use this one or your can try your code and share that code with me

**Comment by engcom-Hotel** [comment] 2022-04-11 08:48
Hello @Sanjay-100,

We have tried to reproduce this issue in Magento 2.4-develop branch but for us the issue is not reproducible. We have created a custom module to trigger `checkout_cart_add_product_complete` event. And for us the event is triggered. Please have a look into the below codebase:

```
public function execute(
        Observer $observer
    ) {
        $this->_logger->debug('debug1234');
    }
```

I am also attaching the module for your reference:

[EventTest.zip](https://github.com/magento/magento2/files/8462528/EventTest.zip)

Please let us know in case we have missed anything.

Thanks

**Comment by Sanjay-100** [comment] 2022-04-14 11:00
@engcom-Hotel  Thanks for your sample code that was working fine.

now I need to get the all data about the cart added Product data like product name, price, varients all options. 
 
![image](https://user-images.githubusercontent.com/98302784/163377924-24a4f7b7-3e4b-43f2-bb6a-cc13fe40a340.png)

**Comment by engcom-Hotel** [comment] 2022-04-21 05:39
Hello @Sanjay-100,

Are you facing any specific issues while doing this? Please let us know.

Thanks

**Comment by engcom-Hotel** [comment] 2022-05-05 05:57
Dear @Sanjay-100,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-05-05 05:57 UTC
Labels: Triage: Dev.Experience, Issue: needs update

**Comment by Sanjay-100** [comment] 2022-05-06 07:31
> Hello @Sanjay-100,
> 
> Are you facing any specific issues while doing this? Please let us know.
> 
> Thanks

Not getting any error and event observer into get the data.
