### ISSUE TITLE
The errors occur using Magento 2.4.4 with PHP 8.1 on a Linux Apache server

### ISSUE THREAD

**Issue by digi-booster** [magento/magento2#35419] opened 2022-05-04 15:03 UTC
### Preconditions (*)

1. Magento 2.4.4
2. Php 8.1
3. Linux apache cPanel 

### Steps to reproduce (*)

1. install Magento 2.4.4 through Softaculous app installer
2. Update Php version from 7.3 to 8.1 with the help of multiPHP manager 

### Expected result (*)

Demo/Default Pages and Admin Panel should display properly.

### Actual result (*)

```
Error: Undefined constant "Magento\Framework\Encryption\Adapter\SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_IETF_NPUBBYTES" in /home4/wardyvgq/public_html/vendor/magento/framework/Encryption/Adapter/SodiumChachaIetf.php:40
Stack trace:
#0 /home4/wardyvgq/public_html/vendor/magento/framework/Encryption/Encryptor.php(399): Magento\Framework\Encryption\Adapter\SodiumChachaIetf->encrypt('a:3:{s:7:"defau...')
#1 /home4/wardyvgq/public_html/vendor/magento/module-config/App/Config/Type/System.php(339): Magento\Framework\Encryption\Encryptor->encryptWithFastestAvailableAlgorithm('a:3:{s:7:"defau...')
#2 /home4/wardyvgq/public_html/vendor/magento/framework/Cache/LockGuardedCacheLoader.php(137): Magento\Config\App\Config\Type\System->cacheData(Array)
#3 /home4/wardyvgq/public_html/vendor/magento/module-config/App/Config/Type/System.php(281): Magento\Framework\Cache\LockGuardedCacheLoader->lockedLoadData('SYSTEM_CONFIG', Object(Closure), Object(Closure), Object(Closure))
#4 /home4/wardyvgq/public_html/vendor/magento/module-config/App/Config/Type/System.php(207): Magento\Config\App\Config\Type\System->loadDefaultScopeData('default')
#5 /home4/wardyvgq/public_html/vendor/magento/module-config/App/Config/Type/System.php(181): Magento\Config\App\Config\Type\System->getWithParts('default/admin/u...')
#6 /home4/wardyvgq/public_html/vendor/magento/framework/App/Config.php(132): Magento\Config\App\Config\Type\System->get('default/admin/u...')
#7 /home4/wardyvgq/public_html/vendor/magento/module-backend/App/Config.php(51): Magento\Framework\App\Config->get('system', 'default/admin/u...')
#8 /home4/wardyvgq/public_html/vendor/magento/module-backend/App/Area/FrontNameResolver.php(109): Magento\Backend\App\Config->getValue('admin/url/use_c...')
#9 /home4/wardyvgq/public_html/vendor/magento/module-backend/Helper/Data.php(209): Magento\Backend\App\Area\FrontNameResolver->getFrontName(false)
#10 /home4/wardyvgq/public_html/vendor/magento/module-backend/App/Request/PathInfoProcessor.php(50): Magento\Backend\Helper\Data->getAreaFrontName()
#11 /home4/wardyvgq/public_html/generated/code/Magento/Backend/App/Request/PathInfoProcessor/Proxy.php(95): Magento\Backend\App\Request\PathInfoProcessor->process(Object(Magento\Framework\App\Request\Http), '/admin_backend')
#12 /home4/wardyvgq/public_html/vendor/magento/framework/App/Request/Http.php(148): Magento\Backend\App\Request\PathInfoProcessor\Proxy->process(Object(Magento\Framework\App\Request\Http), '/admin_backend')
#13 /home4/wardyvgq/public_html/vendor/magento/framework/App/Request/Http.php(163): Magento\Framework\App\Request\Http->getOriginalPathInfo()
#14 /home4/wardyvgq/public_html/vendor/magento/framework/App/Request/Http.php(213): Magento\Framework\App\Request\Http->getPathInfo()
#15 /home4/wardyvgq/public_html/vendor/magento/framework/App/Http.php(111): Magento\Framework\App\Request\Http->getFrontName()
#16 /home4/wardyvgq/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#17 /home4/wardyvgq/public_html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#18 /home4/wardyvgq/public_html/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#19 {main}
```
![image](https://user-images.githubusercontent.com/74658643/166709689-13a1298a-cc5d-45f6-8501-b930fbb2654b.png)
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by aetonsi** [comment] 2022-05-06 14:09
Hello,
i'm having problems with sodium too, but on **Windows 11** (`Version 10.0.22000.652`). Obviously i have sodium installed and de-commented in `php.ini`.

Here's my setup:

`php -version`
> PHP 8.1.5 (cli) (built: Apr 12 2022 17:38:57) (ZTS Visual C++ 2019 x64)
> Copyright (c) The PHP Group
> Zend Engine v4.1.5, Copyright (c) Zend Technologies

`php -info | grep sodium`
> sodium
> sodium support => enabled
> libsodium headers version => 1.0.18
> libsodium library version => 1.0.18

`composer.json`
> "magento/product-community-edition": "2.4.4",

elasticsearch
> "version" : {
> "number" : "7.17.3",


Here is my log:

```log
[2022-05-06T13:53:19.394929+00:00] main.CRITICAL: Error: Undefined constant "Magento\Framework\Encryption\Adapter\SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_IETF_NPUBBYTES" in C:\xampp\htdocs\magento\vendor\magento\framework\Encryption\Adapter\SodiumChachaIetf.php:59
Stack trace:
#0 C:\xampp\htdocs\magento\vendor\magento\framework\Encryption\Encryptor.php(452): Magento\Framework\Encryption\Adapter\SodiumChachaIetf->decrypt()
#1 C:\xampp\htdocs\magento\vendor\magento\module-config\App\Config\Type\System.php(272): Magento\Framework\Encryption\Encryptor->decrypt()
#2 C:\xampp\htdocs\magento\vendor\magento\framework\Cache\LockGuardedCacheLoader.php(118): Magento\Config\App\Config\Type\System->Magento\Config\App\Config\Type\{closure}()
#3 C:\xampp\htdocs\magento\vendor\magento\module-config\App\Config\Type\System.php(281): Magento\Framework\Cache\LockGuardedCacheLoader->lockedLoadData()
#4 C:\xampp\htdocs\magento\vendor\magento\module-config\App\Config\Type\System.php(207): Magento\Config\App\Config\Type\System->loadDefaultScopeData()
#5 C:\xampp\htdocs\magento\vendor\magento\module-config\App\Config\Type\System.php(181): Magento\Config\App\Config\Type\System->getWithParts()
#6 C:\xampp\htdocs\magento\vendor\magento\framework\App\Config.php(132): Magento\Config\App\Config\Type\System->get()
#7 C:\xampp\htdocs\magento\vendor\magento\module-backend\App\Config.php(51): Magento\Framework\App\Config->get()
#8 C:\xampp\htdocs\magento\vendor\magento\module-backend\App\Area\FrontNameResolver.php(109): Magento\Backend\App\Config->getValue()
#9 C:\xampp\htdocs\magento\vendor\magento\module-backend\Helper\Data.php(209): Magento\Backend\App\Area\FrontNameResolver->getFrontName()
#10 C:\xampp\htdocs\magento\vendor\magento\module-backend\App\Request\PathInfoProcessor.php(50): Magento\Backend\Helper\Data->getAreaFrontName()
#11 C:\xampp\htdocs\magento\generated\code\Magento\Backend\App\Request\PathInfoProcessor\Proxy.php(95): Magento\Backend\App\Request\PathInfoProcessor->process()
#12 C:\xampp\htdocs\magento\vendor\magento\framework\App\Request\Http.php(148): Magento\Backend\App\Request\PathInfoProcessor\Proxy->process()
#13 C:\xampp\htdocs\magento\vendor\magento\framework\App\Request\Http.php(163): Magento\Framework\App\Request\Http->getOriginalPathInfo()
#14 C:\xampp\htdocs\magento\vendor\magento\framework\App\Request\Http.php(213): Magento\Framework\App\Request\Http->getPathInfo()
#15 C:\xampp\htdocs\magento\vendor\magento\framework\App\Http.php(111): Magento\Framework\App\Request\Http->getFrontName()
#16 C:\xampp\htdocs\magento\generated\code\Magento\Framework\App\Http\Interceptor.php(23): Magento\Framework\App\Http->launch()
#17 C:\xampp\htdocs\magento\vendor\magento\framework\App\Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#18 C:\xampp\htdocs\magento\pub\index.php(30): Magento\Framework\App\Bootstrap->run()
#19 {main} [] []

```

**Comment by ihor-sviziev** [comment] 2022-05-07 06:33
I guess it might be related to running Magento on windows, which isn't officially supported. You can try running it in Ubuntu using WSL2

**Comment by aetonsi** [comment] 2022-05-10 07:58
Oh i see, i will try that. Thanks.

**Comment by marcelovillalta0** [comment] 2022-05-13 18:33
Has anyone already solved this problem?
I have the same problem, but the version before the current "Magento 2.4.3" works correctly for me, are there problems with this version perhaps?

![image](https://user-images.githubusercontent.com/99217156/168345757-7041933b-562f-4d0f-8f88-ddfff48d89f2.png)

**Comment by dipakapatel1989** [comment] 2022-06-01 06:56
I use linux and still have the same issue

**Comment by ihor-sviziev** [comment] 2022-06-01 14:37
@dipakapatel1989,
please check if you have libsodium installed, could be verified with composer install (it checks all dependencies) on the environment you're running magento.

**Comment by marcelovillalta0** [comment] 2022-06-01 15:47
Fix part of the problem, I did this:

In \xampp\apache\conf\extra\httpd-xampp.conf

Find:
LoadFile "/xampp/php/php7ts.dll"
LoadFile "/xampp/php/libpq.dll"
LoadModule php7_module "/xampp/php/php7apache2_4.dll"


Add:
LoadFile "/xampp/php/libsodium.dll"

reference:  https://community.apachefriends.org/f/viewtopic.php?p=269110&sid=d616bdea4fbcbc0c6e71d7da4f0a064e

But now my main page does not load the css styles.

**Comment by ihor-sviziev** [comment] 2022-06-01 16:16
@marcelovillalta0, sorry can't help you with xampp, I can just can say that the issue coming from missing / outdated lib sodium. If you'll fix it - the issue will be solved for you

**Comment by dipakapatel1989** [comment] 2022-06-02 06:14
Now that issue has been solved. Actually, I installed xampp server and
there was another apache installed so that made it difficult to run the
magento 2.4.4. So there is no issue with lib sodium.

Thanks

**Comment by nikunjskd20** [comment] 2022-06-15 10:34
This works for me works on Windows

Add "extension=sodium" to php.ini (no quotes)
Copy php/libsodium.dll to apache/bin/
Restart Server

**Comment by Sagar2811** [comment] 2022-06-15 10:54
> This works for me works on Windows
> 
> Add "extension=sodium" to php.ini (no quotes) Copy php/libsodium.dll to apache/bin/ Restart Apache

Oh, it works for me, thanks @nikunjskd20

**Comment by engcom-November** [comment] 2022-06-29 09:29
Hi @digi-booster , Thank you for reporting and collaboration. Unable to reproduce the issue in local system. Can you please check if the issue occurred due to missing extensions [Ref comment](https://github.com/magento/magento2/issues/35419#issuecomment-1143695517) and elaborate the steps if you are still facing any issues.
Thank you.

**Comment by engcom-November** [comment] 2022-07-13 11:48
Hi @digi-booster ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-07-13 11:48 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.4

**Comment by ClintTec** [comment] 2022-08-11 13:28
There were no resolution for linux?

Error: Undefined constant "Magento\Framework\Encryption\Adapter\SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_IETF_NPUBBYTES" in /home/tec/projects/digital-imaging-express-pty-ltd/vendor/magento/framework/Encryption/Adapter/SodiumChachaIetf.php:59

Still happening on Ubuntu 22.04.1 LTS
PHP 8.1.2 (cli) (built: Jul 21 2022 12:10:37) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies

Sodium installed
sodium
sodium support => enabled
libsodium headers version => 1.0.18
libsodium library version => 1.0.18

**Comment by ESCA7A** [comment] 2022-11-02 10:18
make sure that you run the command from the root where `docker` is located
and not from the folder where `magento 2` is located
[1. docker located](https://www.flickr.com/photos/196842747@N02/52471813046/in/dateposted-public/lightbox/)
[2. magento 2 located](https://www.flickr.com/photos/196842747@N02/52472272685/in/dateposted-public/lightbox/)

**Comment by KhanBadshah588** [comment] 2023-10-06 05:03
When i am trying any command in magento2 terminal, shows this error. Please help to solve
khan@khan-Latitude-5500:/var/www/html/magento2$ sudo php bin/magento setup:upgrade
Undefined constant "Magento\Framework\Encryption\Adapter\SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_IETF_NPUBBYTES"#0 /var/www/html/magento2/vendor/magento/framework/Encryption/Encryptor.php(452): Magento\Framework\Encryption\Adapter\SodiumChachaIetf->decrypt('\v)\x13xJ\xFC\xEE\x08\xC07\r\xBBA\x06\xCB...')
#1 /var/www/html/magento2/vendor/magento/module-config/App/Config/Type/System.php(272): Magento\Framework\Encryption\Encryptor->decrypt('CykTeEr87gjANw2...')
#2 /var/www/html/magento2/vendor/magento/framework/Cache/LockGuardedCacheLoader.php(118): Magento\Config\App\Config\Type\System->Magento\Config\App\Config\Type\{closure}()
#3 /var/www/html/magento2/vendor/magento/module-config/App/Config/Type/System.php(277): Magento\Framework\Cache\LockGuardedCacheLoader->lockedLoadData('SYSTEM_CONFIG', Object(Closure), Object(Closure), Object(Closure))
#4 /var/www/html/magento2/vendor/magento/module-config/App/Config/Type/System.php(207): Magento\Config\App\Config\Type\System->loadDefaultScopeData('default')
#5 /var/www/html/magento2/vendor/magento/module-config/App/Config/Type/System.php(181): Magento\Config\App\Config\Type\System->getWithParts('default/web/url...')
#6 /var/www/html/magento2/vendor/magento/framework/App/Config.php(132): Magento\Config\App\Config\Type\System->get('default/web/url...')
#7 /var/www/html/magento2/vendor/magento/framework/App/Config.php(80): Magento\Framework\App\Config->get('system', 'default/web/url...')
#8 /var/www/html/magento2/vendor/magento/module-store/App/Request/StorePathInfoValidator.php(73): Magento\Framework\App\Config->getValue('web/url/use_sto...')
#9 /var/www/html/magento2/vendor/magento/module-store/Model/StoreResolver.php(99): Magento\Store\App\Request\StorePathInfoValidator->getValidStoreCode(Object(Magento\Framework\App\Request\Http))
#10 /var/www/html/magento2/vendor/magento/module-store/Model/StoreManager.php(160): Magento\Store\Model\StoreResolver->getCurrentStoreId()
#11 /var/www/html/magento2/generated/code/Magento/Store/Model/StoreManagerInterface/Proxy.php(119): Magento\Store\Model\StoreManager->getStore(NULL)
#12 /var/www/html/magento2/vendor/magento/module-store/Model/Resolver/Store.php(30): Magento\Store\Model\StoreManagerInterface\Proxy->getStore(NULL)
#13 /var/www/html/magento2/vendor/magento/framework/App/Config/ScopeCodeResolver.php(49): Magento\Store\Model\Resolver\Store->getScope(NULL)
#14 /var/www/html/magento2/vendor/magento/framework/App/Config.php(69): Magento\Framework\App\Config\ScopeCodeResolver->resolve('stores', NULL)
#15 /var/www/html/magento2/vendor/magento/framework/Locale/Resolver.php(111): Magento\Framework\App\Config->getValue('general/locale/...', 'stores')
#16 /var/www/html/magento2/vendor/magento/framework/Locale/Resolver.php(129): Magento\Framework\Locale\Resolver->getDefaultLocale()
#17 /var/www/html/magento2/vendor/magento/framework/Locale/Resolver.php(83): Magento\Framework\Locale\Resolver->setLocale(NULL)
#18 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Framework\Locale\Resolver->__construct(Object(Magento\Framework\App\Config), 'general/locale/...', 'store', NULL, NULL)
#19 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#20 /var/www/html/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#21 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#22 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'localeResolver', 'Magento\\Framewo...')
#23 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Magento\\Framewo...', Array, Array)
#24 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Framewo...', Array, Array)
#25 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#26 /var/www/html/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#27 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#28 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'localeFormat', 'Magento\\Eav\\Mod...')
#29 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Magento\\Eav\\Mod...', Array, Array)
#30 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Eav\\Mod...', Array, Array)
#31 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Eav\\Mod...', Array, Array)
#32 /var/www/html/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Eav\\Mod...')
#33 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Eav\\Mod...')
#34 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Eav\\Mod...', NULL, 'context', 'Magento\\Catalog...')
#35 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Magento\\Catalog...', Array, Array)
#36 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Catalog...', Array, Array)
#37 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Catalog...', Array, Array)
#38 /var/www/html/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Catalog...')
#39 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Catalog...')
#40 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Catalog...', NULL, 'productResource', 'Magento\\MediaCo...')
#41 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Magento\\MediaCo...', Array, Array)
#42 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\MediaCo...', Array, Array)
#43 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\MediaCo...', Array, Array)
#44 /var/www/html/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\MediaCo...')
#45 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(206): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\MediaCo...')
#46 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(182): Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray(Array)
#47 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, NULL, Array, 'items', 'Magento\\MediaCo...')
#48 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Magento\\MediaCo...', Array, Array)
#49 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\MediaCo...', Array, Array)
#50 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\MediaCo...', Array, Array)
#51 /var/www/html/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\MediaCo...')
#52 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\MediaCo...')
#53 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\MediaCo...', NULL, 'getEntityConten...', 'Magento\\MediaCo...')
#54 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Magento\\MediaCo...', Array, Array)
#55 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\MediaCo...', Array, Array)
#56 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\MediaCo...', Array, Array)
#57 /var/www/html/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\MediaCo...')
#58 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(206): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\MediaCo...')
#59 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(182): Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray(Array)
#60 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, NULL, Array, 'synchronizers', 'Magento\\MediaCo...')
#61 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Magento\\MediaCo...', Array, Array)
#62 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\MediaCo...', Array, Array)
#63 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\MediaCo...', Array, Array)
#64 /var/www/html/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\MediaCo...')
#65 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\MediaCo...')
#66 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\MediaCo...', NULL, 'synchronizerPoo...', 'Magento\\MediaCo...')
#67 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Magento\\MediaCo...', Array, Array)
#68 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\MediaCo...', Array, Array)
#69 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\MediaCo...', Array, Array)
#70 /var/www/html/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\MediaCo...')
#71 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\MediaCo...')
#72 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\MediaCo...', NULL, 'synchronizeCont...', 'Magento\\MediaCo...')
#73 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Magento\\MediaCo...', Array, Array)
#74 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\MediaCo...', Array, Array)
#75 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\MediaCo...', Array, Array)
#76 /var/www/html/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\MediaCo...')
#77 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(206): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\MediaCo...')
#78 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(182): Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray(Array)
#79 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, NULL, Array, 'commands', 'Magento\\Framewo...')
#80 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Magento\\Framewo...', Array, Array)
#81 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Framewo...', Array, Array)
#82 /var/www/html/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#83 /var/www/html/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...', Array)
#84 /var/www/html/magento2/vendor/magento/framework/Console/Cli.php(154): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...')
#85 /var/www/html/magento2/vendor/magento/framework/Console/Cli.php(135): Magento\Framework\Console\Cli->getApplicationCommands()
#86 /var/www/html/magento2/vendor/symfony/console/Application.php(1286): Magento\Framework\Console\Cli->getDefaultCommands()
#87 /var/www/html/magento2/vendor/symfony/console/Application.php(631): Symfony\Component\Console\Application->init()
#88 /var/www/html/magento2/vendor/symfony/console/Application.php(237): Symfony\Component\Console\Application->find('setup:upgrade')
#89 /var/www/html/magento2/vendor/magento/framework/Console/Cli.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#90 /var/www/html/magento2/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#91 /var/www/html/magento2/bin/magento(23): Symfony\Component\Console\Application->run()
#92 {main}

**Comment by KhanBadshah588** [comment] 2023-10-06 05:06
![Screenshot from 2023-10-06 10-10-41](https://github.com/magento/magento2/assets/113508631/18a9b9b0-cd62-41fe-aa8b-7c1a2d1d8e53)
