### ISSUE TITLE
Zero subtotal after login in on checkout page

### ISSUE THREAD

**Issue by likemusic** [magento/magento2#21799] opened 2019-03-16 15:49 UTC
### Preconditions (*)

1. Magento CE v2.2.6
2. Registered user with empty cart.

### Steps to reproduce (*)

1. Add product to cart as guest user.
2. Go to checkout.
3. Login as already registered user.
4. Go to store homepage.
5. Open minicart and lool for subtotal.

### Expected result (*)

1. Subtotal not zero.

### Actual result (*)

1. Subtotal is zero.
![image](https://user-images.githubusercontent.com/603401/54477786-1596cf80-481c-11e9-955c-529790e6f22c.png)

**Comment by magento-engcom-team** [comment] 2019-03-16 15:49
Hi @likemusic. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@likemusic do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [x] no

**Comment by likemusic** [comment] 2019-03-16 15:51
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-16 15:51
Hi @likemusic. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-16 15:52
Hi @likemusic, here is your [Magento instance](https://i-21799-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21799-2-3-develop.instances.magento-community.engineering/admin](https://i-21799-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by likemusic** [comment] 2019-03-16 16:04
It's not reproducible on 2.3-develop instance.

Should this issue be closed or opened to find some commits that should be backported to 2.2-branch to fix this issue?

**Comment by magento-engcom-team** [comment] 2019-03-18 06:19
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment] 2019-03-18 06:20
@likemusic did you checked this issue is reproduceable at 2.2-develop instance ??

**Comment by shikhamis11** [comment] 2019-03-18 06:20
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-18 06:20
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-18 06:21
Hi @shikhamis11, here is your [Magento instance](https://i-21799-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21799-2-2-develop.instances.magento-community.engineering/admin](https://i-21799-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2019-03-18 07:48
@likemusic this issue is also already fixed at 2.2-develop branch

**Closed as completed by shikhamis11** 2019-03-18 07:48 UTC
Labels: Issue: Format is valid

**Comment by likemusic** [comment] 2019-03-18 09:50
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-18 09:51
Hi @likemusic. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-18 09:51
Hi @likemusic, here is your [Magento instance](https://i-21799-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21799-2-2-develop.instances.magento-community.engineering/admin](https://i-21799-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by likemusic** [comment] 2019-03-18 10:08
@shikhamis11 yes, it's fixed in in 2.2-dev.

Sorry to disturb.

**Comment by shikhamis11** [comment] 2019-03-18 10:19
np It's completely fine we are here to help 😊

**Comment by likemusic** [comment] 2019-03-19 23:07
@magento-engcom-team give me 2.2.7 instance

**Comment by magento-engcom-team** [comment] 2019-03-19 23:07
Hi @likemusic. Thank you for your request. I'm working on Magento 2.2.7 instance for you

**Comment by likemusic** [comment] 2019-03-19 23:07
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-19 23:07
Hi @likemusic. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-19 23:08
Hi @likemusic, here is your [Magento instance](https://i-21799-2-2-7.instances.magento-community.engineering).
Admin access: [https://i-21799-2-2-7.instances.magento-community.engineering/admin](https://i-21799-2-2-7.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by likemusic** [comment] 2019-03-19 23:22
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-19 23:22
Hi @likemusic. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-19 23:23
Hi @likemusic, here is your [Magento instance](https://i-21799-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21799-2-2-develop.instances.magento-community.engineering/admin](https://i-21799-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by likemusic** [comment] 2019-03-20 10:06
Not fixed in 2.2.7 but fixed in 2.2-develop.

Commit with fix:
https://github.com/magento/magento2/commit/cbd707c041d51915e3893a7e1e5a203759c0e87f
