### ISSUE TITLE
Localized date field formatting in admin messing up actual date

### ISSUE THREAD

**Issue by tdgroot** [magento/magento2#27310] opened 2020-03-17 10:26 UTC
### Preconditions (*)
1. Magento `>= 2.3.3-p1`, `2.4-develop`

### Steps to reproduce (*)

1. Have 2 admin users. One on locale `en_US`, one one `nl_NL`.
2. Log in on `nl_NL` admin user.
3. Create a cart price rule, no coupon code needed, just a simple cart price rule. Make sure you set the **from date** (e.g. 17 march 2020). Save the cart price rule.

### Expected result (*)

1. The saved **from date** is `17-03-2020`.
![image](https://user-images.githubusercontent.com/1165302/76847273-1785db00-6842-11ea-8f15-1279a2b24686.png)

### Actual result (*)

1. The saved **from date** is `20-03-2017`.
![image](https://user-images.githubusercontent.com/1165302/76847219-04730b00-6842-11ea-8e93-a911c8cba0ec.png)

**Comment by devchris79** [comment] 2020-03-17 10:34
May be worth checking #26675

**Comment by tdgroot** [comment] 2020-03-18 16:17
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-18 16:18
Hi @tdgroot. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by engcom-Alfa** [comment] 2020-08-12 15:21
The issue is reproducible on fresh 2.4-develop

![Peek 2020-08-12 16-10](https://user-images.githubusercontent.com/51679138/90033862-9a637280-dcc8-11ea-804b-fd65bd64f370.gif)

**Comment by magento-engcom-team** [comment] 2020-08-12 15:27
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36668` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Closed as completed** 2024-07-25 11:44 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Issue: Format is valid, Component: SalesRule, Component: Locale, Reproduced on 2.4.x, Priority: P3, Severity: S2, Progress: done, Reported on 2.3.3-p1
