### ISSUE TITLE
Magento 2.4 Bundles MSI stock problems

### ISSUE THREAD

**Issue by schnere** [magento/magento2#35271] opened 2022-04-06 07:47 UTC
### Preconditions (*)
* Magento 2.4.3-p1
* PHP 7.4
* MariaDB 10.3.34

### Steps to reproduce (*)
1. Create an inventory source and assign it to a stock with the main website selected
2. Add a simple product, add stock quantity > 2 for it
3. Add a bundle product, assign the simple product with amount 2
4. Visit the product page of the bundle product

### Expected result (*)
The bundle product should show in stock as the simple product has enough stock.

### Actual result (*)
The bundle product shows out of stock.

### Workaround

As workaround I updated the if statement in `vendor/magento/module-inventory-bundle-product/Model/GetBundleProductStockStatus.php`, line 79:

```
if (!$stockItemConfiguration->getExtensionAttributes()->getIsInStock() && $product->getTypeId() != "bundle") {
```
Now the simple products are checked if they are in stock. It works as expected and the product is orderable when using PayPal as payment method.
Unfortunately it still does not work with other payment methods. Even though the simple product is in stock, the bundle is marked as out of stock in database table `cataloginventory_stock_item` (`is_in_stock = 0 `).
Manual reindexing does not solve the problem. So I tried to update `is_in_stock` to 1 which resolved the problem. For the bundle with the updated value everything works as expected. But there is no other way to change the value but directly trough the database.
Furthermore I guess the update of the value in the database would also make the workaround in the file mentioned above unnecessary.
So the basic cause of the problem might not be in the functions which check the stock status but in an indexer function which updates `cataloginventory_stock_item` ?  

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2022-04-07 01:27
Hi @schnere ,
Thank you for logging an issue , we tried to reproduce the issue on Magento 2.4.3-p1 instance , we could not reproduce it unfortunately .hence request to review the provided steps.
Followed steps:
1. Create an inventory source and assign it to a stock with the main website selected

<img width="1440" alt="Screenshot 2022-04-07 at 5 56 11 AM" src="https://user-images.githubusercontent.com/51681379/162100690-99362688-af3b-4a14-a8a0-de2f1616ce3d.png">

2. Add a simple product, add stock quantity > 2 for it
<img width="1440" alt="Screenshot 2022-04-07 at 6 21 39 AM" src="https://user-images.githubusercontent.com/51681379/162100809-82c17105-fb58-4c0e-8f45-4a178fa174e6.png">

3. Add a bundle product, assign the simple product with amount 2
<img width="1440" alt="Screenshot 2022-04-07 at 6 37 01 AM" src="https://user-images.githubusercontent.com/51681379/162100856-085a6a4b-b689-4c15-96ee-e5f56943315a.png">

4. Visit the product page of the bundle product
<img width="1440" alt="Screenshot 2022-04-07 at 6 47 57 AM" src="https://user-images.githubusercontent.com/51681379/162100980-22ce1bc2-fc46-4f76-901d-bf8fdbcb68e6.png">

**Comment by engcom-Delta** [comment] 2022-04-22 11:39
Hi @schnere ,
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Comment by engcom-Delta** [comment] 2022-04-26 08:22
As per @serhii-balko  issue has been re-opened and trying to reproduce it

**Comment by engcom-Delta** [comment] 2022-04-28 12:38
Hi @schnere ,
Thank you for logging an issue , we tried to reproduce the issue on Magento 2.4 Develop and Magento 2.4.3-p1 instance , we could not reproduce it unfortunately .hence request to review the provided steps.
Followed steps:
1. Create an inventory source  from Admin portal and assign it to a stock with the main website selected

<img width="1440" alt="Screenshot 2022-04-28 at 3 24 05 PM" src="https://user-images.githubusercontent.com/51681379/165732037-ac8472f0-a2d9-46ac-9303-525df6dfc33e.png">
<img width="1440" alt="Screenshot 2022-04-28 at 3 24 56 PM" src="https://user-images.githubusercontent.com/51681379/165732126-db71940d-4137-43dc-b8a1-0c06d2d8b38a.png">


2. Add a simple product, add stock quantity > 2 for it
<img width="1440" alt="Screenshot 2022-04-28 at 3 28 06 PM" src="https://user-images.githubusercontent.com/51681379/165732287-5463ccef-cab5-4eb3-931c-d5346ef3c7ea.png">
<img width="1440" alt="Screenshot 2022-04-28 at 3 28 57 PM" src="https://user-images.githubusercontent.com/51681379/165732315-ac35c960-74b4-47ae-b540-fa238418b9b1.png">


3. Add a bundle product, assign the simple product with amount 2
<img width="1440" alt="Screenshot 2022-04-28 at 3 32 22 PM" src="https://user-images.githubusercontent.com/51681379/165732367-29071f0f-e2a9-4735-8bca-3f6ac2319197.png">

4. Visit the product page of the bundle product ( in Frontend)
<img width="1440" alt="Screenshot 2022-04-28 at 3 40 21 PM" src="https://user-images.githubusercontent.com/51681379/165732581-69def76f-d249-4583-8fdf-844c412fc781.png">

Actual Results:
In Product page of bundle product is showing as 'In Stock'.

<img width="1440" alt="Screenshot 2022-04-28 at 3 40 21 PM" src="https://user-images.githubusercontent.com/51681379/165733415-666dfdb2-e571-4b9d-b72d-3d5fe0a83dc9.png">

**Scenario 1**: if we try to add more than 2 quantity to cart , then we can see error displayed 

<img width="1440" alt="Screenshot 2022-04-28 at 3 41 24 PM" src="https://user-images.githubusercontent.com/51681379/165732839-91f6fe73-9b1d-48ea-b0aa-002b5ee20ee5.png">

**Scenario 2** if we add quantity as 2 and click on 'Add to cart' button , then we are able to add an item to cart.

**<img width="1440" alt="Screenshot 2022-04-28 at 3 46 59 PM" src="https://user-images.githubusercontent.com/51681379/165733133-f4949c21-8d28-4acb-a202-9beb2466868d.png">**

**Comment by engcom-Delta** [comment] 2022-05-12 06:15
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Closed as completed by engcom-Delta** 2022-05-12 06:15 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update

**Comment by tiacocstoe** [comment] 2023-11-22 08:02
I've noticed same problem. I'm pretty sure it happens when simple products in set aren't in default stock. cataloginventory_stock_item seams to work only with default stock, so when there's no default stock bundles go to not in stock.
Tried removing default stock from simple products but that did not work aswell. Would be gratefull if somebody would investigate it again.

**Comment by kabaaab** [comment] 2024-02-08 16:38
We are seeing the same behavior in 2.4.5 P5 something will trigger all our bundles to go out of stock and the only way to fix it is manually change the "is_in_stock" value back to "1".
