### ISSUE TITLE
Issue with all category pages

### ISSUE THREAD

**Issue by ghost** [magento/magento2#25709] opened 2019-11-23 08:34 UTC
### Preconditions (*)

1. Magento 2.3.3
2. Apache 2.4
3. Php 7.1
4. Mysql 5.7
5. Ubuntu 18.04

### Steps to reproduce (*)

1. Click on category page
2.

### Expected result (*)

1. Pagespeed loading correct
2.

### Actual result (*)

1. Page speed verry slow. Product page speed is correct

[2019-11-23 08:27:18] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-89965-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:18] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-89969-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:18] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-89970-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:18] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-89973-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:19] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-89974-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:19] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-89978-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:19] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-89980-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:19] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-89981-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:19] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-89988-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:19] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-89992-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:19] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90008-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:19] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90023-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:19] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90024-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:19] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90029-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:19] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90034-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:19] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90037-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:19] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90040-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:19] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90042-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:19] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90046-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:19] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90047-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:20] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90048-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:20] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90049-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:20] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90050-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:20] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90056-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:20] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90059-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:20] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90060-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:20] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90061-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:20] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90064-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:20] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90065-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:20] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90066-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:20] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90067-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:20] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90068-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:20] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90069-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:20] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90070-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:20] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90071-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:20] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90072-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:20] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90073-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:20] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90074-final_price-EUR-20191123-2-0-"}} []
[2019-11-23 08:27:20] main.DEBUG: cache_invalidate:  {"method":"GET","url":"https://www.achatpc.com/fr/computers-electronics.html","invalidateInfo":{"identifier":"LOCKED_RECORD_INFO_BLOCK_e7d9fb7ed8638457f6248b77e9f8e90a1e1b2afd-90076-final_price-EUR-20191123-2-0-"}} []

final_price cache issue ?

**Comment by engcom-Charlie** [comment] 2019-11-25 10:28
Hello @achatpc 
We are not able to reproduce this issue on the latest 2.3-develop branch & 2.3.3.
**Testing scenario:**

1. Go to the category page
2. Refresh page 3-5 times
3. Check `debug.log`(should be nothing)
4. Flush cache
5. Refresh Category page again(page loading ~7s)
6. Check `debug.log`(should be `main.DEBUG: cache_invalidate:...` notes)
7. Refresh page 3-5 times(page loading ~0,5s)
8. Check `debug.log`

**Result:**
Only notes from 6's step exist in `debug.log`

**GIF:**
![Peek 2019-11-25 11-56](https://user-images.githubusercontent.com/51680850/69532200-fe4cdc00-0f7d-11ea-92b3-3cb0d0132f8b.gif)

So i have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-11-25 10:28 UTC
Labels: Issue: Format is valid
