### ISSUE TITLE
GET /V1/products/attributes/{attributeCode}/options only returns label value for Default View

### ISSUE THREAD

**Issue by thomasnordkvist** [magento/magento2#2733] opened 2015-12-16 11:57 UTC
When i request
/V1/products/attributes/{attributeCode}/options
It only returns label and value for Default View

``` json
[
 {
  "label":"abc",
  "value":"123"
 }
 {
  "label":"abcd",
  "value":"1233"
 }
]
```

In the documentation at http://devdocs.magento.com/swagger/
it should return something like this:

``` json
[
  {
    "label": "string",
    "value": "string",
    "sortOrder": 0,
    "isDefault": true,
    "storeLabels": [
      {
        "storeId": 0,
        "label": "string"
      }
    ]
  }
]
```

/Thomas

**Comment by vzabaznov** [comment] 2016-06-22 14:13
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment] 2016-07-14 08:07
Hi, @thomasnordkvist thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.

**Closed as completed by vzabaznov** 2016-07-14 08:07 UTC
Labels: Progress: needs update

**Comment by oefterdal** [comment] 2020-01-06 14:10
I get the same in M 2.3.3 @vzabaznov
