### ISSUE TITLE
Checkout Agreements checkbox missing asterisk

### ISSUE THREAD

**Issue by Karlasa** [magento/magento2#21648] opened 2019-03-08 11:57 UTC
### Preconditions (*)

saw issue in both 2.2 and 2.3

### Steps to reproduce (*)

1. Create Terms and Conditions agreement 
2. Enable it with "manual" setting so checkbox would be shown
3. Go to checkout

### Expected result (*)

Agreement checkbox label should have red asterisk as it's required to check it

### Actual result (*)

Asterisk is missing and after pressing place order gives message that field is required

**Comment by magento-engcom-team** [comment] 2019-03-08 11:57
Hi @Karlasa. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Karlasa do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-03-11 15:04
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-03-12 10:01
:white_check_mark: Confirmed by @rogyar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98658` were created

**Issue Available**: @rogyar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-03-18 17:20
Hi @Karlasa. Thank you for your report. 
The issue has been fixed in magento/magento2#21649 by @Karlasa in 2.3-develop branch
Related commit(s):
 - [e6167ad9902393665efc59db0a6c619a8bff773e](https://github.com/magento/magento2/commit/e6167ad9902393665efc59db0a6c619a8bff773e)
 - [afa0320e4dd40dd61ba49205dbf56a94b4f018e9](https://github.com/magento/magento2/commit/afa0320e4dd40dd61ba49205dbf56a94b4f018e9)
 - [92d93f5433b2967afeeda07624d11afe29787031](https://github.com/magento/magento2/commit/92d93f5433b2967afeeda07624d11afe29787031)
 - [46bbdd0e3d5796e427899b96c189888423cb55d4](https://github.com/magento/magento2/commit/46bbdd0e3d5796e427899b96c189888423cb55d4)
 - [a39e22181d94cdec03d40034da96264af32ef4c1](https://github.com/magento/magento2/commit/a39e22181d94cdec03d40034da96264af32ef4c1)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-18 17:20 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: CheckoutAgreements

**Comment by magento-engcom-team** [comment] 2019-03-20 18:28
Hi @Karlasa. Thank you for your report. 
The issue has been fixed in magento/magento2#21838 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [079ecb3689e76e1d5ed85de20f19b59eb347cd66](https://github.com/magento/magento2/commit/079ecb3689e76e1d5ed85de20f19b59eb347cd66)
 - [943fb3374c379c9d00236251d6901a371ee98682](https://github.com/magento/magento2/commit/943fb3374c379c9d00236251d6901a371ee98682)
 - [745df9a3c45a38bbb6da3bfc81d01f7ad2f5563b](https://github.com/magento/magento2/commit/745df9a3c45a38bbb6da3bfc81d01f7ad2f5563b)
 - [8c609c4f546316d3726594cb8ea71f1e91a6594f](https://github.com/magento/magento2/commit/8c609c4f546316d3726594cb8ea71f1e91a6594f)

The fix will be available with the upcoming 2.2.9 release.
