### ISSUE TITLE
Magento 2.1.0 problem with country options.

### ISSUE THREAD

**Issue by C0olmonkey** [magento/magento2#25295] opened 2019-10-26 11:15 UTC
### Summary (*)

Hi!
I have e problem with checkout page. More exactly with country options. In backend is set all for "Romania" but in frontend is showing another countries.

I use Magento 2.1.0 and i linked 2 image to show my problem.
### Examples (*)

Country settings:
https://i.imgur.com/APN0AK3.jpg

Frontend:
https://i.imgur.com/YYsZYkb.jpg

Please help me to solve this issue

**Comment by engcom-Charlie** [comment] 2019-10-28 08:40
Hello @C0olmonkey 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.

We are closing this issue due to branch `2.1-develop` was closed and
> Magento no longer accepts pull requests and issues to the v2.1 release lines to focus all development efforts on v2.3.

 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/), for advice or general discussion about this issue.

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-10-28 08:40 UTC
Labels: Issue: Format is valid
