### ISSUE TITLE
Call to a member function getId() on array in module-sales/view/adminhtml/templates/order/totals/tax.phtml:62

### ISSUE THREAD

**Issue by pjayramkumar** [magento/magento2#30094] opened 2020-09-17 16:32 UTC
### Preconditions (*)

1. Magento Version 2.4.0
2.

### Steps to reproduce (*)

1. Go to Store -> Configuration -> Sales -> Tax -> Orders, Invoices, Credit Memos Display Settings -> Display Full Tax Summary and change to YES
2. Go to Sales -> Orders -> Open Order -> Invoice Tab -> Open Invoice -> Page View Source -> Issue will Visible at the end of view source Page

### Expected result (*)

1. <Screenshots, logs or description]
2. <img width="1135" alt="Screenshot 2020-09-17 at 9 54 45 PM" src="https://user-images.githubusercontent.com/3099588/93499269-69620780-f930-11ea-8e1c-cabe8d7550cd.png">
3. $rate->getId() should be like $rate['id']

4.<img width="1174" alt="Screenshot 2020-09-17 at 9 57 24 PM" src="https://user-images.githubusercontent.com/3099588/93499564-c78eea80-f930-11ea-8ce5-2c29e16252e4.png">
need to expand this array and add id as key to get in the result to the Magento\Tax\Model\ResourceModel\Calculation
<img width="899" alt="Screenshot 2020-09-17 at 9 59 34 PM" src="https://user-images.githubusercontent.com/3099588/93499811-150b5780-f931-11ea-9c2f-f634f99416c5.png">
add the ID CONST in the Magento\Tax\Model\Sales\Order\Tax class

### Actual result (*)

1. [Screenshots, logs or description]
2.
<img width="1435" alt="Screenshot 2020-09-17 at 10 00 56 PM" src="https://user-images.githubusercontent.com/3099588/93500003-5d2a7a00-f931-11ea-800b-76635d2f935d.png">

### Additional info from Engcom
Switch Magento into Developer mode to reproduce the issue `bin/magento dep:mo:set developer`
The invoice looks like this
![html_invoice](https://user-images.githubusercontent.com/51680745/98663042-3e54cc80-2351-11eb-9439-283d769f7efd.png)

Error from View Page Source
![Selection_017](https://user-images.githubusercontent.com/51680745/98663001-32690a80-2351-11eb-8531-d376817e0230.png)

**Comment by pjayramkumar** [comment] 2020-09-17 16:42
@magento I am working on this

**Comment by pjayramkumar** [comment] 2020-09-17 16:42
@magento add to contributors team

**Comment by pjayramkumar** [comment] 2020-09-17 16:43
@magento add to contributors team

**Comment by itsolon** [comment] 2020-09-24 22:14
i can confirm this behaviour

**Comment by irshadcedcoss** [comment] 2020-10-09 10:50
@magento I am working on this

**Comment by GovindaSharma** [comment] 2020-10-10 09:27
@magento I am working on this

**Comment by 22markets** [comment] 2020-10-16 10:09
I can confirm this error on 2.4.0 and 2.4.1

**Comment by Morgy93** [comment] 2020-10-16 10:43
Error introduced here https://github.com/magento/magento2/commit/70ede03e5c2dc9e2c3bb23d0fc5c29cb03cbe7dd

**Comment by Morgy93** [comment] 2020-10-16 11:52
@magento I am working on this

**Comment by Morgy93** [comment] 2020-10-16 11:53
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2020-11-10 10:36
The issue is reproducible on 2.4-develop. Additional info from Engcom is added

**Comment by magento-engcom-team** [comment] 2020-11-10 10:38
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38991` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dbachmann** [comment] 2021-03-10 18:59
@pjayramkumar I can confirm this error also in 2.4.2 when you open an order which was paid by paypal plus using an older version from I-ways paypal plus extension. In Magento 2.4.2 with the latest paypal plus extension everything works fine and there are no errors. I can open new orders without any issues.
So, to fix the bug with older orders I tested your bugfix. After patching the files I could open all orders paid with paypal plus before the shop update. But when I wanted to open the invoice I got the following exception and I had a blank page with the exception hash

`{"0":"Notice: Undefined index: id in \/var\/www\/vhosts\/SHOP\/httpdocs\/vendor\/magento\/module-tax\/Model\/ResourceModel\/Calculation.php on line 152","1":"#1 Magento\\Tax\\Model\\ResourceModel\\Calculation->getCalculationProcess() called at [vendor\/magento\/module-tax\/Model\/Calculation.php:648]\n#2 Magento\\Tax\\Model\\Calculation->reproduceProcess() called at [vendor\/magento\/module-sales\/Model\/Order\/Pdf\/Total\/DefaultTotal.php:110]\n#3 Magento\\Sales\\Model\\Order\\Pdf\\Total\\DefaultTotal->getFullTaxInfo() called at [vendor\/magento\/module-tax\/Model\/Sales\/Pdf\/Grandtotal.php:66]\n#4 Magento\\Tax\\Model\\Sales\\Pdf\\Grandtotal->getTotalsForDisplay() called at [vendor\/magento\/module-sales\/Model\/Order\/Pdf\/AbstractPdf.php:719]\n#5 Magento\\Sales\\Model\\Order\\Pdf\\AbstractPdf->insertTotals() called at [vendor\/magento\/module-sales\/Model\/Order\/Pdf\/Invoice.php:167]\n#6 Magento\\Sales\\Model\\Order\\Pdf\\Invoice->getPdf() called at [vendor\/magento\/module-sales\/Controller\/Adminhtml\/Invoice\/AbstractInvoice\/PrintAction.php:58]\n#7 Magento\\Sales\\Controller\\Adminhtml\\Invoice\\AbstractInvoice\\PrintAction->execute() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#8 Magento\\Sales\\Controller\\Adminhtml\\Order\\Invoice\\PrintAction\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#9 Magento\\Sales\\Controller\\Adminhtml\\Order\\Invoice\\PrintAction\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/App\/Action\/Plugin\/ActionFlagNoDispatchPlugin.php:51]\n#10 Magento\\Framework\\App\\Action\\Plugin\\ActionFlagNoDispatchPlugin->aroundExecute() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#11 Magento\\Sales\\Controller\\Adminhtml\\Order\\Invoice\\PrintAction\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#12 Magento\\Sales\\Controller\\Adminhtml\\Order\\Invoice\\PrintAction\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Sales\/Controller\/Adminhtml\/Order\/Invoice\/PrintAction\/Interceptor.php:23]\n#13 Magento\\Sales\\Controller\\Adminhtml\\Order\\Invoice\\PrintAction\\Interceptor->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:111]\n#14 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/module-backend\/App\/AbstractAction.php:151]\n#15 Magento\\Backend\\App\\AbstractAction->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#16 Magento\\Sales\\Controller\\Adminhtml\\Order\\Invoice\\PrintAction\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#17 Magento\\Sales\\Controller\\Adminhtml\\Order\\Invoice\\PrintAction\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:143]\n#18 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#19 Magento\\Sales\\Controller\\Adminhtml\\Order\\Invoice\\PrintAction\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#20 Magento\\Sales\\Controller\\Adminhtml\\Order\\Invoice\\PrintAction\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Sales\/Controller\/Adminhtml\/Order\/Invoice\/PrintAction\/Interceptor.php:32]\n#21 Magento\\Sales\\Controller\\Adminhtml\\Order\\Invoice\\PrintAction\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:186]\n#22 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:118]\n#23 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#24 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#25 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#26 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:23]\n#27 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:116]\n#28 Magento\\Framework\\App\\Http->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:263]\n#29 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:29]\n","url":"\/backend\/sales\/order_invoice\/print\/invoice_id\/3524\/key\/5f6f542f01786e87200031cdacb20cb895111e01117f952d95e3b8644c152fda\/","script_name":"\/pub\/index.php","report_id":"ed4a9d4df1673ea7a3ef338876eef0ade5a4fe9caf0dbb8e527e41330d50574b"}
`

I know it's just a notice but this notice crashes the backend.

**Comment by MohamedLbn** [comment] 2021-03-17 18:33
Solution :  (tested in Magento 2.4.2)
Replace $rate->getId() with $rate['code']
Path :vendor/magento/module-sales/view/adminhtml/templates/order/totals/tax.phtml Line 61

> `<?php foreach ($rates as $rate):?>
>                 <tr id="rate-<?= /* @noEscape */ $rate['code'] ?>"
>                     class="summary-details<?= ($isTop ? ' summary-details-first' : '') ?>">
>                     <?php if ($rate['percent'] !== null): ?>
>                         <td class="admin__total-mark">
>                             <?= $block->escapeHtml($rate['title']) ?> (<?= (float)$rate['percent'] ?>%)<br />
>                         </td>
>                     <?php else: ?>
>                         <td class="admin__total-mark"><?= $block->escapeHtml($rate['title']) ?><br /></td>
>                     <?php endif; ?>
>                     <?php if ($isFirst): ?>
>                         <td rowspan="<?= count($rates) ?>">
>                             <?= /* @noEscape */ $block->displayAmount($amount, $baseAmount) ?>
>                         </td>
>                     <?php endif; ?>
>                 </tr>
>                 <?= /* @noEscape */ $secureRenderer->renderStyleAsTag("display:none;", 'tr#rate-' . $rate['code']) ?>
>                 <?php
>                 $isFirst = 0;
>                 $isTop = 0;
>                 ?>
>             <?php endforeach; ?>`

**Comment by eduard13** [comment] 2021-04-08 06:28
@magento give me 2.4-develop instance

**Comment by Morgy93** [comment] 2021-04-19 09:42
@magento give me 2.4-develop instance

**Comment by Morgy93** [comment] 2021-04-19 10:01
Still reproducible~

Tried it for discussion here https://github.com/magento/magento2/pull/30516#issuecomment-822343010

**Comment by engcom-Foxtrot** [comment] 2021-04-19 12:43
> Still reproducible~
> 
> Tried it for discussion here [#30516 (comment)](https://github.com/magento/magento2/pull/30516#issuecomment-822343010)

Hm... I've reordered the order with a failing invoice and the invoice for a new one is correct.

**Comment by Morgy93** [comment] 2021-04-19 13:10
> Hm... I've reordered the order with a failing invoice and the invoice for a new one is correct.

The system went away for me just during my check😬 

But I saw that `$_fullInfo` was not populated for your invoice, so the problematic code was not even executed.

Having two items with different tax class should work (or not work in this case 😅) for example 19% and 7% tax (like in Germany)

**Comment by Morgy93** [comment] 2021-04-19 13:11
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2021-05-05 14:48
Hi @pjayramkumar, @Morgy93. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-38991` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by EgorDubrovskiy** [comment] 2021-05-06 11:44
Hello everyone

This issue is reproducible for my site 
We have free products on the site 
If all products in an order are free, then we apply free shipping and billing methods and don't have tax for the order
In this case we create an invoice manually from the admin page and have the issue when we try to visit the invoice page

**Comment by EgorDubrovskiy** [comment] 2021-05-06 15:14
A little update related to this issue 
As I investigated the reason of the issue is that we load taxes by invoice ID instead of expected order ID
As I see in this case we always expect an order ID hire
Please let me know if invoice 
ID is also right 
vendor/magento/module-sales/Block/Adminhtml/Order/Totals/Tax.php:98

**Comment by Waldemar-Denke** [comment] 2021-05-18 10:25
I fixed it temporarily by adding
`<?php $ratesId = preg_replace("/[^a-zA-Z]+/", "", $rate['code']); ?>`
replaced Line 62 with
`<tr id="rate-<?= /* @noEscape */ $ratesId ?>"`
and replaced Line 77
`<?= /* @noEscape */ $secureRenderer->renderStyleAsTag("display:none;", 'tr#rate-' . $ratesId ) ?>`
in file: vendor/magento/module-sales/view/adminhtml/templates/order/totals/tax.phtml

print_r($_fullInfo);
returns
```
Array
(
    [0] =&gt; Array
        (
            [amount] =&gt; 2.6400
            [base_amount] =&gt; 2.6400
            [base_real_amount] =&gt; 2.6400
            [rates] =&gt; Array
                (
                    [0] =&gt; Array
                        (
                            [code] =&gt; DE - reduzierte USt.
                            [title] =&gt; reduzierte USt.
                            [percent] =&gt; 7
                            [position] =&gt; 0
                            [priority] =&gt; 0
                        )
                )
            [percent] =&gt; 7
            [id] =&gt; DE - reduzierte USt.
        )
)
```

**Comment by eBusinessAtlantique** [comment] 2021-05-20 13:10
I can repoduce this exact same issue on my site M2.4.2 if I set Display ull tax summary to YES.
Set to NO, there is no error.

Here is the error on the source page 

                                    
                            <tr id="rate-Error: Call to a member function getId() on array in /home/m2/public_html/vendor/magento/module-sales/view/adminhtml/templates/order/totals/tax.phtml:62
Stack trace:
#0 /home/m2/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include()
#1 /home/m2/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render()
#2 /home/m2/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent()
#3 /home/m2/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#4 /home/m2/public_html/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins()
#5 /home/m2/public_html/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php\Interceptor->render()
#6 /home/m2/public_html/vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView()
#7 /home/m2/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1111): Magento\Framework\View\Element\Template->_toHtml()
#8 /home/m2/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1115): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#9 /home/m2/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(675): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#10 /home/m2/public_html/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#11 /home/m2/public_html/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#12 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#13 /home/m2/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#14 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#15 /home/m2/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(522): Magento\Framework\View\Layout\Interceptor->renderElement()
#16 /home/m2/public_html/vendor/magento/module-sales/view/adminhtml/templates/order/totals.phtml(36): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#17 /home/m2/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/home/m2/public...')
#18 /home/m2/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render()
#19 /home/m2/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent()
#20 /home/m2/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#21 /home/m2/public_html/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins()
#22 /home/m2/public_html/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php\Interceptor->render()
#23 /home/m2/public_html/vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView()
#24 /home/m2/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1111): Magento\Framework\View\Element\Template->_toHtml()
#25 /home/m2/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1115): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#26 /home/m2/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(675): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#27 /home/m2/public_html/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#28 /home/m2/public_html/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#29 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#30 /home/m2/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#31 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#32 /home/m2/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(522): Magento\Framework\View\Layout\Interceptor->renderElement()
#33 /home/m2/public_html/vendor/magento/module-sales/view/adminhtml/templates/order/invoice/view/form.phtml(95): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#34 /home/m2/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/home/m2/public...')
#35 /home/m2/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render()
#36 /home/m2/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent()
#37 /home/m2/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#38 /home/m2/public_html/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins()
#39 /home/m2/public_html/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php\Interceptor->render()
#40 /home/m2/public_html/vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView()
#41 /home/m2/public_html/vendor/magento/module-backend/Block/Template.php(141): Magento\Framework\View\Element\Template->_toHtml()
#42 /home/m2/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1111): Magento\Backend\Block\Template->_toHtml()
#43 /home/m2/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1115): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#44 /home/m2/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(675): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#45 /home/m2/public_html/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#46 /home/m2/public_html/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#47 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#48 /home/m2/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#49 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#50 /home/m2/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(522): Magento\Framework\View\Layout\Interceptor->renderElement()
#51 /home/m2/public_html/vendor/magento/module-backend/Block/Widget/Form/Container.php(220): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#52 /home/m2/public_html/vendor/magento/module-backend/view/adminhtml/templates/widget/form/container.phtml(25): Magento\Backend\Block\Widget\Form\Container->getFormHtml()
#53 /home/m2/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/home/m2/public...')
#54 /home/m2/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render()
#55 /home/m2/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent()
#56 /home/m2/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#57 /home/m2/public_html/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins()
#58 /home/m2/public_html/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php\Interceptor->render()
#59 /home/m2/public_html/vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView()
#60 /home/m2/public_html/vendor/magento/module-backend/Block/Template.php(141): Magento\Framework\View\Element\Template->_toHtml()
#61 /home/m2/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1111): Magento\Backend\Block\Template->_toHtml()
#62 /home/m2/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1115): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#63 /home/m2/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(675): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#64 /home/m2/public_html/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#65 /home/m2/public_html/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#66 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#67 /home/m2/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#68 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#69 /home/m2/public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#70 /home/m2/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#71 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#72 /home/m2/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#73 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#74 /home/m2/public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#75 /home/m2/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#76 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#77 /home/m2/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#78 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#79 /home/m2/public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#80 /home/m2/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#81 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#82 /home/m2/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#83 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#84 /home/m2/public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#85 /home/m2/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#86 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#87 /home/m2/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#88 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#89 /home/m2/public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#90 /home/m2/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#91 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#92 /home/m2/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#93 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#94 /home/m2/public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#95 /home/m2/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#96 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#97 /home/m2/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#98 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#99 /home/m2/public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#100 /home/m2/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#101 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#102 /home/m2/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#103 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#104 /home/m2/public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#105 /home/m2/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#106 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#107 /home/m2/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#108 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#109 /home/m2/public_html/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout\Interceptor->renderElement()
#110 /home/m2/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(347): Magento\Framework\View\Layout->getOutput()
#111 /home/m2/public_html/vendor/magento/framework/View/Result/Page.php(258): Magento\Framework\View\Layout\Interceptor->getOutput()
#112 /home/m2/public_html/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render()
#113 /home/m2/public_html/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(23): Magento\Framework\View\Result\Layout->renderResult()
#114 /home/m2/public_html/vendor/magento/framework/App/Http.php(120): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult()
#115 /home/m2/public_html/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http->launch()
#116 /home/m2/public_html/pub/index.php(29): Magento\Framework\App\Bootstrap->run()
#117 {main}

**Comment by magento-engcom-team** [comment] 2021-07-31 11:11
:white_check_mark: Confirmed by @mrtuvn 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38991` were created

**Issue Available**: @mrtuvn, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hostep** [comment] 2021-08-11 19:57
It looks like core Magento devs have finally seen the light even though the community had a PR open for this for almost a year now. So they just publised a fix in: MC-42332, [part 1](https://github.com/magento/magento2/commit/d648bdc238ba6b59890694251655f725ad1b5d88), [part 2](https://github.com/magento/magento2/commit/3ae814c5ba423124ba44ed8be35787bc266a9752)

I'm guessing it will be released in Magento 2.4.4 which will probably be [released somewhere in 2022](https://devdocs.magento.com/release/), yay!

**Comment by ihor-sviziev** [comment] 2021-08-12 07:44
Hi @pjayramkumar,
As @hostep mentioned, looks like the issue was fixed in the 2.4-develop branch with the following commits:
- https://github.com/magento/magento2/commit/d648bdc238ba6b59890694251655f725ad1b5d88
- https://github.com/magento/magento2/commit/3ae814c5ba423124ba44ed8be35787bc266a9752

Could you confirm that?

**Comment by o-dubovyk** [comment] 2021-08-19 18:11
This issue was fixed  with the following commits: `d648bdc`, `3ae814c`. Closing this issue

**Closed as completed** 2021-08-19 18:18 UTC
Labels: Component: Tax, Component: Sales, Issue: Confirmed, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P2, Severity: S3, Progress: done, Reported on 2.4.0

**Comment by itsolon** [comment] 2021-11-29 18:19
> It looks like core Magento devs have finally seen the light even though the community had a PR open for this for almost a year now. So they just publised a fix in: MC-42332: [part 1](https://github.com/magento/magento2/commit/d648bdc238ba6b59890694251655f725ad1b5d88), [part 2](https://github.com/magento/magento2/commit/3ae814c5ba423124ba44ed8be35787bc266a9752)
> 
> I'm guessing it will be released in Magento 2.4.4 which will probably be [released somewhere in 2022](https://devdocs.magento.com/release/), yay!

hopefully this will fix my issue tooo yay :-) thank you for that

**Comment by jaykobi** [comment] 2022-09-20 13:32
Two years latwer... bug still present in Magent 2.4.5

**Comment by ihor-sviziev** [comment] 2022-09-20 14:24
@jaykobi, accodring to the following line, it shouldn't reproduce on 2.4.5. https://github.com/magento/magento2/blob/d648bdc238ba6b59890694251655f725ad1b5d88/app/code/Magento/Sales/view/adminhtml/templates/order/totals/tax.phtml#L63
If you can reproduce this issue on clean magento installation, please report a separate issue for that.
