### ISSUE TITLE
Can't Refund Invoice Without 0 Quantities Through REST API

### ISSUE THREAD

**Issue by EyalAmir** [magento/magento2#23069] opened 2019-05-30 19:10 UTC
1. The API responds with error "You can't create a creditmemo without products." from the QuantityValidator.

**Comment by EyalAmir** [comment] 2019-05-30 19:13
yes

**Comment by magento-engcom-team** [comment] 2019-07-31 10:42
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18785` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by raduluputu** [comment] 2020-02-13 09:50
Hello, 
I am encountering the same exact issue. Any updates on when to expect the solution for it?
Thanks!

**Comment by agrohs** [comment] 2020-07-07 21:51
Any update on here???

**Comment by ihor-sviziev** [comment] 2020-11-03 15:06
Adding back Severity label

**Comment by engcom-Oscar** [comment] 2020-11-05 09:16
Hi @EyalAmir ! 
I couldn't reproduce this issue on latest 2.4-develop code, could you please recheck it?

**Comment by engcom-Oscar** [comment] 2020-11-06 11:15
Hi @EyalAmir . I was able to reproduce the issue only with "0" shipping cost, not without, so I amend description.

**Comment by EyalAmir** [comment] 2020-11-09 17:50
0 shipping cost is the scenario I had in the "Steps to reproduce" so that makes sense. The test refund I had tried was:
{"items": [{"qty": 0, "orderItemId": 6, "extensionAttributes": {}}], "appendComment": false, "notify": true, "isOnline": true, "arguments": {"adjustment_negative": 0.0, "adjustment_positive": 0.99, "shipping_amount": 0}}

**Closed as completed** 2020-11-14 16:18 UTC
Labels: Issue: Confirmed, Reproduced on 2.3.x, Component: Api, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P1, Severity: S1, Progress: done
