### ISSUE TITLE
add product is disabled in catalog admin role website magento 2

### ISSUE THREAD

**Issue by camilomanzano-omni** [magento/magento2#35008] opened 2022-01-21 23:52 UTC
### Preconditions (*)
magento v2.4.3 EE
php v7.4

### Steps to reproduce (*)
1.Multistore website
2.Create admin user with permissions only on specific store
3.Grant all access over that store only
![image](https://user-images.githubusercontent.com/83025957/150613835-9c2b9c95-4ee3-4254-bcba-2c17a13b8890.png)
4.Go to categories
5.Add products by sku in existing category

### Expected result (*)
1.Add product list to existing category
![image](https://user-images.githubusercontent.com/83025957/150614144-edeccb03-4844-42c8-a083-05405ce48f2d.png)
![image](https://user-images.githubusercontent.com/83025957/150614200-2dfd7c13-aa02-4c2b-b6f6-28ac394a66b8.png)

### Actual result (*)
The button to add products appears disabled always 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/83025957/150614096-d468769e-651b-4cb4-b982-5b4a37b82f43.png)

Other workarounds like add category on product admin page don't work too and applying rules to add products on category, same result.
---

**Comment by engcom-November** [comment] 2022-01-24 14:58
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-02-23 10:54
Verified the issue on Magento 2.4-develop branch having Enterprise edition modules enabled but cannot able to reproduce the issue.
**Steps performed:**
Multi store setup
1. Created admin user (Admin - System - Add new User)
2. Admin - System - User Roles - select role - Role Resources -  Role Scopes - Custom - assigned the user to 2nd website store only
3. Grant all access over that store only
4. Go to categories
5.Add products by sku in existing category
**No issue:**
![Uploading image.png…]()
@camilomanzano-omni  kindly recheck the issue on Magento 2.4-develop branch with Enterprise edition modules installed and provide missing steps if any if the issue is still reproducible.
Thank you

**Comment by engcom-November** [comment] 2022-03-08 05:22
Hi @camilomanzano-omni ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-03-08 05:22 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.3

**Comment by sangeetavernost** [comment] 2022-06-02 06:18
Any update for this, how we can solve this.
We are also facing same issue with M2.4.3 EE
