### ISSUE TITLE
Something went wrong while saving this post. Warning: array_intersect(): Argument #1 is not an array in /magento/vendor/magento/module-admin-gws/Model/Models.php on line 1094

### ISSUE THREAD

**Issue by Vibhanshu-Sharma** [magento/magento2#26544] opened 2020-01-27 07:42 UTC
### Preconditions (*)
I have created a user "Tester" for Only Store3 Access from admin restricted role in Magento 2.3.1 Enterprise Edition and then open cms page or blog page if i am going to update anything i got this Error  Warning: array_intersect(): Argument #1 is not an array in /magento/vendor/magento/module-admin-gws/Model/Models.php on line 1094. 

1. 
2. 

### Steps to reproduce (*)
with test user save any blog page or cms page you will get 
Warning: array_intersect(): Argument #1 is not an array in /magento/vendor/magento/module-admin-gws/Model/Models.php on line 1094 or More permissions are needed to save this item.

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]
save the page and blog post easily
### Actual result (*)

with test user save any blog page or cms page you will get 
Warning: array_intersect(): Argument #1 is not an array in /magento/vendor/magento/module-admin-gws/Model/Models.php on line 1094 or More permissions are needed to save this item.
1. [Screenshots, logs or description]

**Comment by krishprakash** [comment] 2020-01-27 10:42
Hi @Vibhanshu-Sharma. Please add all data with all details like pre-condition,steps to reproduce,expected and actual result.
Thanks

**Comment by Vibhanshu-Sharma** [comment] 2020-01-27 11:37
Preconditions (*)
I have created a user "Tester" for Only Store3 Access from admin restricted role in Magento 2.3.1 Enterprise Edition and then open cms page or blog page if i am going to update anything i got this Error Warning: array_intersect(): Argument #1 is not an array in /magento/vendor/magento/module-admin-gws/Model/Models.php on line 1094.

Steps to reproduce (*)
with test user save any blog page or cms page you will get
Warning: array_intersect(): Argument #1 is not an array in /magento/vendor/magento/module-admin-gws/Model/Models.php on line 1094 or More permissions are needed to save this item.

Expected result (*)
[Screenshots, logs or description]
save the page and blog post easily
Actual result (*)
with test user save any blog page or cms page you will get
Warning: array_intersect(): Argument #1 is not an array in /magento/vendor/magento/module-admin-gws/Model/Models.php on line 1094 or More permissions are needed to save this item.

[Screenshots, logs or description]

**Comment by engcom-Hotel** [comment] 2020-01-28 14:48
Hello @Vibhanshu-Sharma 

I am not able to reproduce this issue on the latest Magento 2.4-develop EE.

**Manual testing scenario:**
Create user role for some store with permissions for a `Content` page
Assign recently created role to some user
Create Cms page for same store as in first step
Login in user account created in second step
Try to edit recently created Cms page

**Result**:
You have permissions to edit page as expected:
[Screenshot](https://ibb.co/3BMXmwj)

That issue is happening when you try to edit another store's page(because you have not permission to edit this page). 

So i have to close this issue.

Thanks for your report!

**Closed as completed by engcom-Hotel** 2020-01-28 14:48 UTC
Labels: Issue: Format is valid, Reported on 2.3.1

**Comment by Vibhanshu-Sharma** [comment] 2020-01-29 09:55
By override AdminGws Models.php . It has been fixed . I think Magento 2.3.1 EE needs to update 2.4. Anyways thanks
