### ISSUE TITLE
magento 2.3.1 command module:disable removes tables as well

### ISSUE THREAD

**Issue by LouNik1984** [magento/magento2#24458] opened 2019-09-05 08:27 UTC
Preconditions (*)
1. magento 2.3.1 on apache with php 7.2

### Steps to reproduce (*)
1. create custom module in app/code (not via composer)
2. create table for custom module using xml declarative schema
3. insert data into table
4. disable module (module:disable Vendor_Module + setup:upgrade)

### Expected result (*)
Module is disabled but table is still in the database with all the data previously saved

### Actual result (*)
Module is disabled but tables in database are deleted as well. 
Running module:enable will re-create tables but of course they're empty, so all data previously saved are lost.

**Comment by LouNik1984** [comment] 2019-09-05 08:31
I cannot ask for a vanilla instance since this is about creating a new module and interacting with the database

**Comment by engcom-Charlie** [comment] 2019-09-05 11:42
Hello @LouNik1984 !
I can't reproduce this issue on fresh Magento 2.3-develop.

**Manual testing scenario:**

1. create custom module in app/code (not via composer)
2. create table for custom module using xml declarative schema
3. insert data into table
4. disable module (module:disable Vendor_Module + setup:upgrade)

**Actual result:**
 Table is still in the database with all the data previously saved
![image](https://user-images.githubusercontent.com/51680850/64338801-4695d700-cfeb-11e9-8d21-1e7ac10bd151.png)

So i have to close it.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-09-05 11:42 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid
