### ISSUE TITLE
Two file upload not working within a same form in magento product page

### ISSUE THREAD

**Issue by rishisarvadaa** [magento/magento2#32958] opened 2021-05-06 10:23 UTC
I have a default magento 2.4.2.installed on my server. In the product detail page there are 2 input types of file upload which is not working together. When I remove one input file type then it is working properly but when i add one more then I am not able to move forward. The error log is also empty. Please help me in finding the issue. 

All I want to achieve is: these uploaded images should be attached when added to cart.

Please see the attachment.

This is the backend configuration
![image](https://user-images.githubusercontent.com/82762829/117284738-c9d49380-ae84-11eb-9c65-aceb25d5adad.png)

This is how it looks in frontend
![1](https://user-images.githubusercontent.com/82762829/117282953-ed96da00-ae82-11eb-8edb-e362c03950fc.png)

Below is the link where it is implemented
[https://rucomfybeanbags.sarvadaa.com/joust-duffle-bag.html](url)

I have another fresh magento setup with version 2.3.3. In that setup this is working perfectly. But when i do the same in magento 2.4.2 it is not working.

Is there any issue with this specific version?

**Comment by rishisarvadaa** [comment] 2021-05-07 04:21
Hi @engcom-Oscar ,
Can you please check the below link?
https://rucomfybeanbags.sarvadaa.com/joust-duffle-bag.html

I have installed another fresh magento setup with version 2.3.3. In that setup it is working perfectly. But when i do the same in magento 2.4.2 it is not working. 

Is there any issue with this specific version?

**Comment by rishisarvadaa** [comment] 2021-05-07 07:24
@engcom-Oscar 
you can check here [https://www.mageplaza.com/kb/magento-2-demo.html](url) with both versions(2.3.3 & 2.4.2).
I have tried here also. It seems a issue with this specific version.

**Comment by engcom-Oscar** [comment] 2021-05-11 12:23
@rishisarvadaa I tried to reproduce this issue on the latest 2.4-develop branch from here, but it worked fine in my case.  Looks like we miss some important preconditions, so may you please recheck and update description?

**Comment by rishisarvadaa** [comment] 2021-05-12 08:59
@engcom-Oscar Just to confirm, did you check on this link? 
https://www.mageplaza.com/kb/magento-2-demo.html

[url](https://www.mageplaza.com/kb/magento-2-demo.html)

**Comment by engcom-Oscar** [comment] 2021-05-13 09:40
@rishisarvadaa No, I have checked on local vanilla 2.4-develop instance.

**Comment by engcom-Oscar** [comment] 2021-05-27 07:17
I have to close this ticket.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) if you are still facing this issue on the latest `2.4-develop` branch.
Thank you for collaboration.

**Closed as completed by engcom-Oscar** 2021-05-27 07:17 UTC
Labels: Issue:  Cannot Reproduce, Triage: Dev.Experience, Issue: needs update
