### ISSUE TITLE
Cart page responsive  wish-list icon alignment

### ISSUE THREAD

**Issue by SyntaxKay** [magento/magento2#21225] opened 2019-02-14 12:47 UTC
### Preconditions (*)

1.Magento 2.3-dev

### Steps to reproduce (*)

Frontend > Add any product to cart > check wish list-icon into less then 767 screen size

### Expected result (*)

![expectedss](https://user-images.githubusercontent.com/33230237/52787651-86fc2a80-3084-11e9-915d-24c268db4e44.png)

### Actual result (*)

![actualss](https://user-images.githubusercontent.com/33230237/52787629-7ba8ff00-3084-11e9-83cc-fad1712d65e6.png)

**Comment by magento-engcom-team** [comment] 2019-02-14 12:47
Hi @speedy008. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@speedy008 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by Karlasa** [comment] 2019-02-14 21:18
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-14 21:18
Hi @Karlasa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-14 21:19
Hi @Karlasa, here is your [Magento instance](https://i-21225-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21225-2-3-develop.instances.magento-community.engineering/admin](https://i-21225-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Karlasa** [comment] 2019-02-14 21:28
@speedy008 I think it's not issue but just UI decision to have all primary actions on right and secondary ones on left. Currently as it shows only one icon it may look odd but in commerce version there can be alot more options (e.g. gift option, requisition list...) 
I will close this issue. Do not hesitate to contact me if you think this should be an issue.

**Closed as completed by Karlasa** 2019-02-14 21:28 UTC
Labels: Progress: reject, Component: Checkout, Area: Frontend, Issue: Format is valid, Area: Design/Frontend
