### ISSUE TITLE
Rewriting product listing widget block breaks its template rendering.

### ISSUE THREAD

**Issue by sanganinamrata** [magento/magento2#16529] opened 2018-07-04 10:54 UTC
### Preconditions

1. Magento version **2.2.x**

### Steps to reproduce

1. For some customisation, I've rewrite block of **Magento\CatalogWidget\Block\Product\ProductsList** to 
**Mycompany\Mymodule\Block\Product\ProductsList** in front-end's **di.xml**.
2. Now Added below **product listing widget** in backend **CMS block**:
> <p>{{widget type="Magento\CatalogWidget\Block\Product\ProductsList" products_count="8" template="Magento_CatalogWidget::product/widget/content/grid.phtml" conditions_encoded="^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^],`1--1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`visibility`,`operator`:`==`,`value`:`4`^]^]"}}</p>
1. https://www.screencast.com/t/OWr5hKuSa4

### Expected result

The widget template should be rendered successfully.

### Actual result

The widget template rendering gives following error:
1. https://www.screencast.com/t/jPQs8Fps9

**Comment by magento-engcom-team** [comment] 2018-07-04 10:54
Hi @sanganinamrata. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@sanganinamrata do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment] 2018-07-04 13:36
Hello @sanganinamrata, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by sanganinamrata** [comment] 2018-07-05 04:38
@engcom-backlog-nickolas Thanks

**Comment by magento-engcom-team** [comment] 2018-07-13 07:15
Hi @sanganinamrata. Thank you for your report. 
The issue has been fixed in magento/magento2#16530 by @sanganinamrata in 2.2-develop branch
Related commit(s):
 - [83e3818ed41b04c3290139398f68d5fa043fff28](https://github.com/magento/magento2/commit/83e3818ed41b04c3290139398f68d5fa043fff28)
 - [7e173eeaa9a43e544501ec239147bf83d8b7741d](https://github.com/magento/magento2/commit/7e173eeaa9a43e544501ec239147bf83d8b7741d)

The fix will be available with the upcoming 2.2.6 release.

**Closed as completed by magento-engcom-team** 2018-07-13 07:15 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by sidolov** [comment] 2018-07-26 06:40
Hi @sanganinamrata. Thank you for your report. 
The issue has been fixed in magento/magento2#17111 by @gelanivishal in 2.1-develop branch
Related commit(s):
 - [deb05f1a7d4e8ed789848a86817619df3ec43628](https://github.com/magento/magento2/commit/deb05f1a7d4e8ed789848a86817619df3ec43628)
 - [784d16778c8a46493dded1f9d16d5f4bbdc8fdac](https://github.com/magento/magento2/commit/784d16778c8a46493dded1f9d16d5f4bbdc8fdac)

The fix will be available with the upcoming 2.1.15 release.

**Comment by sidolov** [comment] 2018-08-02 12:05
Hi @sanganinamrata. Thank you for your report. 
The issue has been fixed in magento/magento2#16856 by @gelanivishal in 2.3-develop branch
Related commit(s):
 - [b519270ced38296be5c44ce02b23020ecc1d4e35](https://github.com/magento/magento2/commit/b519270ced38296be5c44ce02b23020ecc1d4e35)
 - [9197c68bca1c6c166acca7d92eaf8c571c8de06d](https://github.com/magento/magento2/commit/9197c68bca1c6c166acca7d92eaf8c571c8de06d)

The fix will be available with the upcoming 2.3.0 release.
