### ISSUE TITLE
New order email header logo not showing correctly v2.1

### ISSUE THREAD

**Issue by dapdx** [magento/magento2#6420] opened 2016-08-31 17:02 UTC
Store logo in new order confirmation email is not showing correctly. In the theme configuration I have set the transaction logo image to a custom image. When orders are placed the custom image is not included and it is defaulting to the Magento stock image. 
### Preconditions

Magento 2.1 on PHP 7
Multiple store fronts using custom theme
### Steps to reproduce
1. In admin go to Content/Configuration/customtheme-edit
2. Go to the Transaction Emails section
3. Upload new logo image
4. Save
### Expected result
1. When new order is placed and order confirmation email goes out it should have the new custom logo at the top of the email
### Actual result
1. Custom logo does not show up, Magento stock logo is in it's place.

**Comment by apurv-anand** [comment] 2016-09-02 09:51
Is there a workaround available? This seems to me as a blocker issue. How can a store go live with emails not showing the right logo?

**Comment by sevos1984** [comment] 2016-09-05 07:17
This issue is duplicate of https://github.com/magento/magento2/issues/6275. You can find fix for current develop here https://github.com/magento/magento2/commit/23103c03c527fe1ed3e1a3be691436818b7963fe

**Closed as completed by sevos1984** 2016-09-05 07:17 UTC
Labels: Issue: Ready for Work, bug report, Component: Config

**Comment by dapdx** [comment] 2016-09-07 17:29
@sevos1984 Trying to implement this fix, but where is the app/code folder? maybe a stupid question, but in my app folder I just have design and etc folders. This new Magento directory is really confusing compared to 1.9.

**Comment by magento-team** [comment] 2017-07-31 23:01
Internal ticket to track issue progress: MAGETWO-69062
