### ISSUE TITLE
[API] OAuth1.0 request token request failing / Consumer key has expired

### ISSUE THREAD

**Issue by nyov** [magento/magento2#829] opened 2014-12-19 01:49 UTC
While trying to go the long route and get an OAuth1.0 request token via `POST /oauth/token/request` (as explained in [the devdocs](http://devdocs.magento.com/guides/v1.0/get-started/authentication/gs-authentication-oauth.html#pre-auth-token)) I'm having these issues.

I tested these with both (and getting the same results)
* a freshly created "Integration" without activating it (only Consumer Key & Secret exist)
* an activated "Integration" (through the backend) with (unused) Accress Token & Secret

**Variant 1, using POST body**:

The server returns a `HTTP/1.1 500 Internal Server Error`.

tcpdump:
```
POST /oauth/token/request HTTP/1.1
Host: magento2.local
Content-Length: 250
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.4.3 CPython/2.7.8
Connection: keep-alive
content-type: application/x-www-form-urlencoded

oauth_version=1.0&oauth_nonce=6b3dcfe588fcc4c6fceefdc10024a41d680f3779&oauth_timestamp=1418902037&oauth_signature=CdC6L9j8NWK6TZwCaI%2Fmevusqcg%3D&oauth_consumer_key=vdowjpsll6bmob27416mw0yx26a00obd&oauth_signature_method=HMAC-SHA1&oauth_callback=oob

HTTP/1.1 500 Internal Server Error
Date: Thu, 18 Dec 2014 11:27:17 GMT
Server: Apache/2.4.10
Set-Cookie: private_content_version=bd03c1e60f365f81666c2093da991bc0; expires=Sun, 15-Dec-2024 11:27:17 GMT; Max-Age=315360000; path=/
Set-Cookie: PHPSESSID=vc9fsu4id7t8fuvia8jjrpa264; expires=Thu, 18-Dec-2014 12:27:17 GMT; Max-Age=3600; path=/; domain=magento2.local; HttpOnly
Set-Cookie: X-Magento-Vary=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate, max-age=0
Expires: Wed, 18 Dec 2013 11:27:17 GMT
Connection: close
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8

d0
oauth_problem=internal_error%26message%3DNotice%3A+Undefined+index%3A+oauth_version+in+%2Fthis%2Fis%2Fsome%2Fprivate%2Fpath%2Fmagento2.git%2Flib%2Finternal%2FMagento%2FFramework%2FOauth%2FOauth.php+on+line+63
0
```

Unquoted:
`oauth_problem=internal_error&message=Notice:+Undefined+index:+oauth_version+in+/this/is/some/private/path/magento2.git/lib/internal/Magento/Framework/Oauth/Oauth.php+on+line+63`

https://github.com/magento/magento2/blob/master/lib/internal/Magento/Framework/Oauth/Oauth.php#L63
That line checks for `$params['oauth_version']`, but as the dump should show the param is included.

I concluded that Magento2 is now exclusively checking `Authorization` headers instead.

**Variant 2, using Authorization Headers**:

The server returns a `HTTP/1.1 401 Unauthorized` message.

tcpdump:
```
POST /oauth/token/request HTTP/1.1
Host: magento2.local
Content-Length: 0
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.4.3 CPython/2.7.8
Connection: keep-alive
content-type: application/x-www-form-urlencoded
Authorization: OAuth realm="",oauth_nonce="74b6b19dfc80aaa84bf4faf4c548b509cf92a71c",oauth_timestamp="1418903145",oauth_consumer_key="vxklyge1xp45q2o3afwyyjtg8ga15i58",oauth_signature_method="HMAC-SHA1",oauth_version="1.0",oauth_signature="cA84%2Bt0O2ym3cVHE%2FdXz1Pwwn8E%3D"

HTTP/1.1 401 Unauthorized
Date: Thu, 18 Dec 2014 11:45:45 GMT
Server: Apache/2.4.10
Set-Cookie: private_content_version=8a7cda19058a4697834d07a7c0f4c1d4; expires=Sun, 15-Dec-2024 11:45:45 GMT; Max-Age=315360000; path=/
Set-Cookie: PHPSESSID=c9i34gpd023q8h37ogc9b6k0p4; expires=Thu, 18-Dec-2014 12:45:45 GMT; Max-Age=3600; path=/; domain=magento2.local; HttpOnly
Set-Cookie: X-Magento-Vary=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate, max-age=0
Expires: Wed, 18 Dec 2013 11:45:45 GMT
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8

26
oauth_problem=Consumer+key+has+expired
0
```

(Consumer key has expired)
This seems to be the real issue here, the expiration time check.

Of course I verified that I'm actually sending the consumer key&secret as displayed in the backend.

As an aside, the library used to build the OAuth requests is mature (and working with magento1).

**Comment by anupdugar** [comment] 2015-01-20 17:50
@nyov Please check out the latest code. We have pushed fixes to mitigate the Oauth consumer expiry issue. There are additional fixes for the returning the correct HTTP response codes for Oauth related failures as well.
Let us know if the fix resolves the issue you reported.

We have noticed some discrepancy in [devdocs](http://devdocs.magento.com/guides/v1.0/get-started/authentication/gs-authentication-oauth.html) and are working on it to fix it.
Meanwhile there is a quick gist to demo the Oauth flow : https://gist.github.com/anupdugar/2870f28a5c108cc43df9

**Comment by muasir** [comment] 2015-01-23 21:40
Closing based on @anupdugar  comment.

**Closed by muasir** 2015-01-23 21:40 UTC
Labels: bug, PS

**Comment by paul-sidd** [comment] 2015-12-16 07:12
I tried the same thing, 
1. created new integration in magento 2 through admin console.
2. Activated the new integration created in first step.
3. copied the consumer key and consumer secret.
4. using scribe framework, tried to access the request token key , but getting error

Exception in thread "main" org.scribe.exceptions.OAuthException: Response body is incorrect. Can't extract token and secret from this: 'oauth_problem=Cannot+create+request+token+because+consumer+token+is+not+a+verifier+token'

Can someone help to identify the root cause and the possible rectification?

**Comment by Lapinou42** [comment] 2018-03-16 15:00
Hello, 

After many hours of searching, I couldn't find a solution to get it working. I have the exactly same issue as @nyov . I'm using Magento 2.2.3. I created a freshly integration, copie/paste my consumer key/secret and tried to get an access token. I get all the time a 401 error with : oauth_problem=Consumer+key+has+expired.

Is it fixed in 2.2.3 ? I guess yes. I don't understand what's wrong.

Thank you for your feed-back.

**Comment by nyov** [comment] 2018-03-18 00:43
As a note from myself; I've stopped working with Magento2 since, so didn't have a chance to re-check on this issue. I can't say whether it was resolved. Sorry.

**Comment by Lapinou42** [comment] 2018-03-19 10:03
Well, thank you @nyov for your reply ;)

**Comment by bmxmale** [comment] 2018-04-09 07:47
@Lapinou42 check `oauth_consumer` table, on my case `updated_at` column was set to null and this cause problem. After update `updated_at` column I get new error: Invalid+signature
