### ISSUE TITLE
Magento 2.4.6 Sample data problem - just 46 products in Gear category

### ISSUE THREAD

**Issue by MaxAlekseyev** [magento/magento2#38530] opened 2024-03-19 20:44 UTC
### Preconditions and environment

M246
PHP8.1
Mysql  Ver 8.0.32-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))
WSL2

### Steps to reproduce

1. Install M 2.4.6 via composer
2. Install Sample data via composer
3. Go to admin - Categories

### Expected result

A lot of the products in any category

### Actual result

Just 46 products in Gear category

### Release note

Installed several time for 246 and 245 also. The M2 installation and DB was cleared before every time. Just 46 products in Gear and all. I'm no newbee in this and googled also. Generally it's too simple situation and I wondered, everything was cleared, reindexed, composer version swapped, I tried to find the problems by myself but no idea

[img]https://i.imgur.com/wssC8qm.png[/img]

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-03-20 06:48
Hi @MaxAlekseyev,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

![Screenshot from 2024-03-20 11-54-49](https://github.com/magento/magento2/assets/51680745/d8e64b47-6e52-4033-90d0-b3b9182bcd2a)


The Categories Women,Men are showing 0 products because those categories are having sub categories in that we are having products.we can see there are sub categories like Tops,Bottoms for the both Women and Men.

Kindly let us know if you are still facing any issue.

Thanks.

**Comment by MaxAlekseyev** [comment] 2024-03-20 13:04
> The Categories Women,Men are showing 0 products because those categories are having sub categories in that we are having products.we can see there are sub categories like Tops,Bottoms for the both Women and Men.

Yes, sure, I posted more clear screenshot below with visible subcategories

![image](https://github.com/magento/magento2/assets/10415908/181bbaf8-b150-46ab-94b5-a655b3d8194e)

**Comment by MaxAlekseyev** [comment] 2024-03-20 13:11
The usual process of my installation:
1. composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.4.6 ./dir
2. php bin/magento setup:install --base-url=...  (--cleanup-database if needed)
3. php bin/magento deploy:mode:set developer
4. upgrade, permissions, etc
5. rm -rf generated/code/* generated/metadata/*
6. bin/magento sampledata:deploy

**Comment by engcom-Bravo** [comment] 2024-03-27 11:43
Hi @MaxAlekseyev,

Thanks for your update.

We have followed the same steps and we are not able to reproduce the issue.

<img width="333" alt="Screenshot 2024-03-27 at 16 17 54" src="https://github.com/magento/magento2/assets/51680745/7d9d82ef-06e7-44b4-b23c-9f9bb95cf141">



Could you please try to reproduce the issue in Latest Stable Magento version.

Thanks.

**Comment by MaxAlekseyev** [comment] 2024-03-27 14:03
> Could you please try to reproduce the issue in Latest Stable Magento version.
I solved the problem, [here is the topic](https://magento.stackexchange.com/questions/372631/magento-2-4-6-sample-data-problem-just-46-products-in-gear-category/372666#372666). Working well now

In short:

> Because you have installed them before but may have failed that time, so the sample data patches have been saved into the patch_list table. Therefore, the solution is to delete these sample data patches and then run setup:upgrade. However, to avoid any other mistakes, you should delete the database and run setup:install

**Comment by engcom-Bravo** [comment] 2024-03-28 05:02
Hi @MaxAlekseyev,

Thanks for your update.

We are Closing this issue as per this https://github.com/magento/magento2/issues/38530#issuecomment-2022853658 Since issue has been resolved.

Thanks.

**Closed as completed by engcom-Bravo** 2024-03-28 05:02 UTC
Labels: Issue: needs update, Reported on 2.4.6

**Comment by MaxAlekseyev** [comment] 2024-03-28 15:37
> Thanks for your update
Thank you for your work, too )
