### ISSUE TITLE
Empty cart button does not work

### ISSUE THREAD

**Issue by luukschakenraad** [magento/magento2#18589] opened 2018-10-13 11:48 UTC
### Preconditions (*)
1. Magento 2.2.6
2. Magento sample data
3. Luma theme active

### Steps to reproduce (*)
1. Add a product to your cart
2. Go to the cart page
3. In the developer-console of your browser run `jQuery('.action.clear').show();` to show the default "empty cart button"
4. Click the button "Clear shopping Cart"

### Expected result (*)
1. I expect the shopping cart to be cleared

### Actual result (*)
1. The page reloads, the shopping cart is not cleared

**Comment by magento-engcom-team** [comment] 2018-10-13 11:48
Hi @luukschakenraad. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@luukschakenraad do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by rogyar** [comment] 2018-10-14 12:32
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2018-10-14 12:32
Hi @rogyar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2018-10-14 12:32
Hi @rogyar, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18589-2-3-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18589-2-3-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18589-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by slavvka** [comment] 2018-10-22 21:22
Hi @luukschakenraad. Thank you for your report. 
The issue has been fixed in magento/magento2#18596 by @luukschakenraad in 2.3-develop branch
Related commit(s):
 - [cc3835f69324ec02ca7982259ebb0a41bad17425](https://github.com/magento/magento2/commit/cc3835f69324ec02ca7982259ebb0a41bad17425)

The fix will be available with the upcoming 2.3.1 release.

**Comment by sidolov** [comment] 2018-10-25 06:43
Hi @luukschakenraad. Thank you for your report. 
The issue has been fixed in magento/magento2#18597 by @luukschakenraad in 2.2-develop branch
Related commit(s):
 - [7acc46a590c36f5c8c4292c3c65792c0684eb195](https://github.com/magento/magento2/commit/7acc46a590c36f5c8c4292c3c65792c0684eb195)

The fix will be available with the upcoming 2.2.8 release.

**Closed as completed by sidolov** 2018-10-25 06:43 UTC
Labels: Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
