### ISSUE TITLE
PHP-7 | Authorizenet Directpost Payment Gateway Issue 

### ISSUE THREAD

**Issue by satishashilwar** [magento/magento2#4327] opened 2016-04-27 11:18 UTC
## Steps to reproduce
1. Enable payment gateway "Authorizenet Direct PostPayment" from admin 
2. Proceed with add to cart and select the payment gateway authorized direct post
3. Add dummy credit card detail 
4. Click Place order
## Expected result
1. Order should be placed with payment "Authorizenet Payment Gateway" 
## Actual result

 Loader continue appears, you will the JS error "TypeError: response is null"

I have further debug the code, please check the below finding. This issue specifically appears on PHP-7 version and it working fine with other PHP version.

It observed that when we place order by selecting payment gateway authroized net no JSON response return by the URL: http://project-dev.local/authorizenet/directpost_payment/place/

Further I have debug the script and try to capture response data by adding debug code in file vendor/magento/module-authorizenet/Controller/Directpost/Payment/Place.php
at line no. 136 (print_r($result->getData()) returns the following array
Magento\Framework\DataObject Object
(
    [_data:protected] => Array
        (
            [success] => 1
            [authorizenet_directpost] => Array
                (
                    [fields] => Array
                        (
                            [x_version] => 3.1
                            [x_delim_data] => FALSE
                            [x_relay_response] => TRUE
                            [x_test_request] => TRUE
                            [x_login] => ]z�� T�O
                            [x_method] => CC

In the above response array key x_login contains the special chars like (�� T�O) when we passed the same array to $this->jsonHelper->jsonEncode($result)  line no. 137 it returns the empty JSON response.
Can you please check this issue and suggest if you have any way out.

**Comment by YevSent** [comment] 2016-04-27 13:55
@satishashilwar thanks for your reporting, this is known issue and already fixed in the develop branch. What version of Magento do you use?

**Comment by satishashilwar** [comment] 2016-04-27 19:15
@joni-jones thanks for reply. I am using the Magento ver. 2.0.4

**Comment by plentyhappy** [comment] 2016-04-28 03:39
Hopefully this will be in the next official release so we can "composer update" our live store. Still stuck using php 5.5 until this happens.

**Comment by vzaporozhets** [comment] 2016-04-28 07:31
Hello All, I'm closing this issue - please contact us again if it will be faced with 2.0.5 which is coming very soon.

**Closed as completed by vzaporozhets** 2016-04-28 07:31 UTC

**Comment by dartanandan** [comment] 2016-05-02 07:32
@vzaporozhets i have checked magento version 2.0.5, still i get the same issue. i checked PHP Version 5.5.12 and PHP Version 7.

**Comment by YevSent** [comment] 2016-05-03 08:51
@dartanandan this fix will be included into 2.0.6 release version.

**Comment by dartanandan** [comment] 2016-05-03 12:47
Thanks for you replay. May i know how long it will take to release the version 2.0.6 please.

**Comment by dartanandan** [comment] 2016-05-13 07:05
Hello @joni-jones,
May i know when release the Authorizenet issue fixed version.

**Comment by dartanandan** [comment] 2016-05-18 12:11
Hello,
I have tested magento version 2.0.6, still i get Authorizenet issue. i checked PHP Version 5.5.12. Please any one give me guidance to fix this issue.

**Comment by YevSent** [comment] 2016-05-18 12:42
Hi,  unfortunately, by mistake this fix is still not included into 2.0.6 version.

You can apply code from this commit https://github.com/magento/magento2/commit/32ca5c97304a1bd84cfbee7cec3d57c9307da9a6 to fix this issue.

**Comment by dartanandan** [comment] 2016-05-25 13:11
Hi @ joni-jones,

Sorry i got the same issue in php7 also.

**Comment by dartanandan** [comment] 2016-05-25 13:13
Hi @joni-jones,

Sorry i got same issue also in php7. I followed [32ca5c9](https://github.com/magento/magento2/commit/32ca5c97304a1bd84cfbee7cec3d57c9307da9a6) this but not fix.

**Comment by YevSent** [comment] 2016-05-25 13:32
The fix for this issue already included to 2.0.7 version

**Comment by dartanandan** [comment] 2016-05-30 09:40
Am checked this version also, still i get same issue.

**Comment by YevSent** [comment] 2016-06-03 13:23
Which version of php do you use? Seems, this issue is related to the php internal links implementation, because now it isn't reproducible on 2.0.4, 2.0.7 with php 7.0.7.
