### ISSUE TITLE
File custom option download link for order doesn't work after quote is removed by sales_clean_quotes cron

### ISSUE THREAD

**Issue by piuga** [magento/magento2#29957] opened 2020-09-09 10:01 UTC
### Additional information
Due to https://github.com/magento/magento2/issues/29957#issuecomment-696802254 still actual on `2.4-develop`

### Preconditions (*)
1. Magento 2.4-develop
2. Magento 2.3.5-p2

### Steps to reproduce (*)
1. Create product with custom option file
2. In front-end place an order with this product, with any image
3. In back-end go to order and download custom option file -> it works fine, as expected
4. Set, for example, 1 day for quote lifetime under:  Stores / Configurations / Sales / Checkout / Shopping Cart / Quote Lifetime
5. After 1 day, cron will remove the quote
6. Go back to order in admin panel and download custom option file -> it shows 404 page

### Expected result (*)
1. Download link, for order item with a file custom option, should work after quote is removed.

### Actual result (*)
1. After 'sales_clean_quotes' cron runs, for all orders, which have items with file custom option and for which the quote was removed, the download link does not work.

![Peek 2020-12-02 10-39](https://user-images.githubusercontent.com/51679138/100849957-c67b4d00-348b-11eb-93cc-c9aca0948e2f.gif)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sdzhepa** [comment] 2020-09-14 17:53
Hello @piuga 
cc: @engcom-Oscar 

Thank you for your report.
Unfortunately, we are not able to reproduce this issue on the latest `2.4-develop` code. Probably it was already fixed and will appear in the next release. Or we missed some steps or preconditions.

Could you please have a look and confirm?

Also, please take into account that
We are able to process, collaborate, fix, and deliver pull requests ONLY for Issues that can be reproduced on the latest [2.4-develop](https://github.com/magento/magento2/tree/2.4-develop) public branch.
- [Code Contributions: Accepted pull requests and ported code](https://devdocs.magento.com/contributor-guide/contributing.html#rules)  <details><summary>Quote</summary>
**v2.4 Contribution Notice:** Magento is focusing development efforts on v2.4, so we are no longer accepting pull requests to the v2.3, v2.2, v2.1, and v2.0 release lines.
</details>

- [GitHub Issues Processing Workflow: Verification](https://github.com/magento/magento2/wiki/GitHub-Issues-Processing-Workflow#verification) <details><summary>Quote</summary>
Be advised, we only accept pull requests for `2.4-develop.`
Check if the issue exists on the `2.4-develop` branch with a clean installation, configured by described preconditions, following the exact reproduction steps.
-- If the described behavior was reproduced, the maintainer should apply the Reproduced on 2.4 label to the ticket, indicating that issue was reproduced and specific version.
-- If the issue was not reproducible with `2.4-develop`, the maintainer should **close the issue and stop verification process here!**
</details>

- [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) _this link exsist in each new [issue report template](https://raw.githubusercontent.com/magento/magento2/2.4-develop/.github/ISSUE_TEMPLATE/bug_report.md)_<details><summary>Quote</summary>
Checks if the issue exists on the 2.4-develop branch with clean Magento installation. Be advised, we only accept pull requests for 2.4-develop. If the issue is not reproducible on 2.4-develop, it will be closed.
</details>

Branch `2.3-develop` was removed from the public repository. All fixes to the previous release allowed and can be done ONLY by internal teams. Based on the prioritized backlog by the Product Management team. 
All issue related to the previous Magento versions can be reported only through:
- support channel associated with you magento.com account
- participation in [Magento Beta Program](https://github.com/magento/magento2/wiki/Magento-Beta-Program)

**Comment by piuga** [comment] 2020-09-22 15:38
Hello @sdzhepa,

I have checked this on 2.4-develop branch also, and the issue appears there.

I will add below some screenshots that might help with testing. I used an older DB so I have old orders for it:
- here is an order placed on 12 Oct. 2019 https://prnt.sc/ulvz4s 
- the quote attached to it has same updated date: https://prnt.sc/ulw0s0 
As DB was from local, were cron was not running, I have all quotes in there: https://prnt.sc/ulvs7j last updated date is 15. Aug 2020
Quote lifetime is set to 30 days: https://prnt.sc/ulw2zc 
As soon as cron runs (this job in particular: sales_clean_quotes), all quotes older than 30 days are removed: https://prnt.sc/ulw28u - the query is exactly the same as the one generated here https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Model/ResourceModel/Collection/ExpiredQuotesCollection.php#L75 

Then I go back to order page from admin and try to get the custom option file: https://prnt.sc/ulw2ml but instead I am redirected to a 404 page

The problem is here:
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Controller/Download/DownloadCustomOption.php#L80
as custom option is loaded from quote item.
This will cause problems for all orders that have removed quotes.

**Comment by sdzhepa** [comment] 2020-09-29 17:01
Thank you for the update @piuga!

@engcom-Oscar  could you please check, update the issue description and confirm?

**Comment by magento-engcom-team** [comment] 2020-12-02 08:49
@engcom-Alfa Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by viniciusbordinhao-blueacorn** [comment] 2020-12-15 13:11
@magento I am working on it.

**Comment by viniciusbordinhao-blueacorn** [comment] 2020-12-28 04:26
@piuga @sdzhepa

I am not sure if that is the best solution for the issue, maybe change the way how the file type options of the product are saved should be the best option. But for now, that is the solution that I could provide.

Please let me know if you have any concern or changes that could become that solution better than that one developed.

**Comment by engcom-November** [comment] 2022-09-15 12:27
Verified the issue on Magento 2.4-develop branch but the issue is not reproducible.
Even after running the cron - able to download custom option file from Sales - Oders - Order details page.

**Comment by engcom-November** [comment] 2022-10-03 05:58
We are closing this issue as there has been no latest update on the same. Please create new issue if the issue is still reproducible.
Thank you.

**Closed as completed by engcom-November** 2022-10-03 05:58 UTC
Labels: Component: Sales, Issue: Clear Description, Component: Quote, Priority: P2, Severity: S2, Progress: done, Issue: ready for confirmation, Issue: needs update, Reported on 2.3.5-p2

**Comment by gersonhernandez** [comment] 2023-10-30 03:09
I share the solution I developed.

https://github.com/gersonhernandez/GersonHernandez_DownloadCustomOptionFile

```
<?php
        if (!$option->getId()) {

            try {
                $key = $this->getRequest()->getParam('key');
                $itemCollection = $this->itemCollectionFactory->create();
                $itemCollection->addFieldToFilter('product_options', ['like' => '%' . $key . '%']);
        
                $item = $itemCollection->getFirstItem();
                $options = $item->getProductOptions()['options'];
                foreach ($options as $opt) {
                    if ($opt['option_type'] == 'file') {
                        $info = $this->serializer->unserialize($opt['option_value']);
                        if ($info['secret_key'] == $key) {
                            $this->download->downloadFile($info);
                        }
                    }
                }
            } catch (\Throwable $th) {
                $this->logger->debug($th->getMessage());
                return $resultForward->forward('noroute');
            }
        }
```
