### ISSUE TITLE
Magento 2.4.2 - Select All feature in orders grid not working

### ISSUE THREAD

**Issue by chikoi** [magento/magento2#32471] opened 2021-03-12 23:55 UTC
### Preconditions (*)

1. Vanilla Magento 2.4.2

### Steps to reproduce (*)

1. Create 11 orders and 11 invoices.
2. In the "Orders" grid, set "per page" to 10.
3. On the uppermost-left part of the grid, select "Select All" and it will display "11 records found (11 selected)"
4. Print invoices.

### Expected result (*)

1. Print 11 invoices.

### Actual result (*)

1. It only prints 10 invoices.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment] 2021-03-15 13:53
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41309` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by coderimus** [comment] 2022-01-21 10:12
I checked this issue with Magento OS 2.4.3-p1 and the situation is next:
It looks like mass action selects only and only visible items on the current page. When an admin user chooses the _Select All_ option and uses the _Print Invoices_ or _Print All_ mass action it gets all invoices only when it manually passes all pages through the paginator selector. Otherwise, only visible items on the current page will be printed.

This issue has a workaround, but I didn't find any explanation in the official documentation. If there is no explanation in the documentation it would be great to add it or make functionality clear for the final user.

**Comment by advocat** [comment] 2022-06-02 15:51
Looks like the root cause of issue is MC-36755 (https://github.com/magento/magento2/commit/503c42874911024d704bbd68a24a215ac63ee369)

As workaround you can create `view/adminhtml/ui_component/sales_order_grid.xml` in your module with following content:

```
<?xml version="1.0" encoding="UTF-8"?>
<listing xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
    <listingToolbar name="listing_top">
        <massaction name="listing_massaction" component="Magento_Ui/js/grid/provider"/>
    </listingToolbar>
</listing>
```

As possible solution of the original issue - from architectural POV i can suggest to extend grid items data with Last ID, send them with `excluded: false`, limit collection with Last ID on processing

**Comment by engcom-Bravo** [comment] 2024-06-07 05:53
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-06-25 03:40
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-06-25 04:01
Hi @chikoi,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="1440" alt="Screenshot 2024-06-25 at 09 28 58" src="https://github.com/magento/magento2/assets/51680745/d7fc6bc8-a9af-4947-bfd8-b6094a1a7e3d">



<img width="1192" alt="Screenshot 2024-06-25 at 09 29 07" src="https://github.com/magento/magento2/assets/51680745/654da022-2ec2-4a14-9ef7-f54285bb63f7">



We are able to Print 11 invoices.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-25 04:01 UTC
Labels: Issue: Confirmed, Component: Admin, Reproduced on 2.4.x, Priority: P4, Triage: Ready for Triage, Progress: done
