### ISSUE TITLE
Payment Failed Emails cannot be styled with css by including the default email header

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#38847] opened 2024-06-19 18:25 UTC
### Preconditions and environment

2.4.7-p1

### Steps to reproduce

Deploy vanilla 2.4.7-p1
Configure payment provider in test mode, such that payment failed emails can be triggered
Configure the payment failed emails to generate and specify a recipient email address
Modify the standard payment failed email template to include the standard header and footer includes.
Trigger a failed payment

### Expected result

The email received has the standard email headers and footers and is styled via css.

### Actual result

The email contains the following error.

CSS inlining error: Compilation from source: LESS file is empty: adminhtml/<vendor>/<theme>/<locale>/css/email-inline.less 

This is correct, email style sheets are not generated for the admin theme.

Either the emails should be sent under the scope of the store that generated the failed payment, or email styles should be included in the admin theme?

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment] 2024-06-20 09:24
you should add styles via less file ? Add via email header can missed in some case depends on devices/app
i will suggest you add styles via less and magento will auto inject inline to email

**Comment by gwharton** [comment] 2024-06-20 09:28
Email styles are completely missing from the admin theme, so it's not just a case of adding a style to admin themes email less files. You would need to copy over the email.less files from your frontend theme Into admin theme and maintain them both for style consistency. This I suspect wouldn't be a straight forward process due to the differences between the admin and frontend theme dependencies.

**Comment by engcom-Delta** [comment] 2024-06-20 13:20
Hi @gwharton ,

We believe that you need better styling for the email templates , Can you brief about what would be the expected outcome you want.

Thanks,

**Comment by mrtuvn** [comment] 2024-06-24 03:11
so you want styles preview in admin email same as output in frontend ?@gwharton

**Comment by mrtuvn** [comment] 2024-06-24 03:13
It's limitation of core base. I think it's need some extra customise when it's difference store/area code
admin -> always store 0 and area code -> adminhtml
So you need re-set store follow email store view and set area code frontend to archieve your demand

**Comment by engcom-November** [comment] 2024-06-24 14:15
Hello @gwharton,
Thank you for the report and collaboration!
Thank you @mrtuvn for the input!

We are able to reproduce this on 2.4.7-p1 instance.
The payment failed email with default luma header and footer is not being generated in the mail.
we are seeing an exception as below:
```
UnexpectedValueException: Template file 'header.html' is not found. in /opt/homebrew/var/www/magento247p1/vendor/magento/module-email/Model/Template/Config.php:253
```

@gwharton can you try with the workaround mentioned [here](https://github.com/magento/magento2/issues/38847#issuecomment-2185505901), and let us know if this fixes your issue.

Thank you.

**Comment by engcom-November** [comment] 2024-07-09 11:08
Hello @gwharton,

As there is no activity on this issue for a long time, we believe the issue has been resolved, hence closing this issue.
Feel free to raise a new issue or reopen this if you need more assistance.

Thank you.

**Comment by hostep** [comment] 2024-07-09 11:38
@engcom-November: you reproduced the bug but closed it anyways? That's not a good way of doing things.
Can you re-open? It sounds like a core bug to me (unless somebody can tell me otherwise?)

**Comment by gwharton** [comment] 2024-07-09 17:16
I guess not so much a bug, but design feature. email styles are just not present in the admin theme, so any attempt to add any sort of styling to any emails sent out under the ADMIN scope are doomed to be dull.

I tried adding the email styles less files to my admin theme, but soon lost the will to live due to the different dependency and inheritance oddities between the frontend and backend themes.

**Comment by engcom-November** [comment] 2024-07-10 13:43
Hello @gwharton,

The result we got is different from what is mentioned in the actual result, instead of the styles being empty we are getting the header template is missing.

This is the template used:
```
{{template config_path="design/email/header_template"}}


<h1>{{trans "Payment Transaction Failed"}}</h1>

<ul>
    <li>
        <strong>{{trans "Reason"}}</strong><br />
        {{var reason}}
    </li>
    <li>
        <strong>{{trans "Checkout Type"}}</strong><br />
        {{var checkoutType}}
    </li>
    <li>
        <strong>{{trans "Customer:"}}</strong><br />
        <a href="mailto:{{var customerEmail}}">{{var customer}}</a> <{{var customerEmail}}>
    </li>
    <li>
        <strong>{{trans "Items"}}</strong><br />
        {{var items|raw}}
    </li>
    <li>
        <strong>{{trans "Total:"}}</strong><br />
        {{var total}}
    </li>
    <li>
        <strong>{{trans "Billing Address:"}}</strong><br />
        {{var billingAddressHtml|raw}}
    </li>
    <li>
        <strong>{{trans "Shipping Address:"}}</strong><br />
        {{var shippingAddressHtml|raw}}
    </li>
    <li>
        <strong>{{trans "Shipping Method:"}}</strong><br />
        {{var shippingMethod}}
    </li>
    <li>
        <strong>{{trans "Payment Method:"}}</strong><br />
        {{var paymentMethod}}
    </li>
    <li>
        <strong>{{trans "Date & Time:"}}</strong><br />
        {{var dateAndTime}}
    </li>
</ul>

{{template config_path="design/email/footer_template"}}
```

Can you let us know if we are missing something here.

**Comment by engcom-Hotel** [comment] 2024-11-04 06:55
Dear @gwharton ,

This issue is being closed since it has not been updated in a long time. Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks

**Closed as completed by engcom-Hotel** 2024-11-04 06:55 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.7-p1
