### ISSUE TITLE
Cart is not clearing after new registration

### ISSUE THREAD

**Issue by saiyadsalma** [magento/magento2#5904] opened 2016-07-30 09:16 UTC
### Preconditions

1. Magento version 2.0.7 
2. PHP 5.4
### Steps to reproduce

1. One time need to complete whole checkout cycle. Now logout and create new account 
2. One product automatically added to cart
3. Now clear cart.
### Expected result

1. Cart should be empty
### Actual result

1. [Screenshot, logs] Cart added one item automatically. I have used everything premium theme and customized theme. But i am facing cart issue.

It is on my local system and i am using IP to access it. Please help me.

**Comment by pboisvert** [comment] 2016-07-31 01:38
@saiyadsalma unless you have a typo your version of PHP does not meet the system requirements of 5.5.22 or greater--http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements.html 

please try to reproduce using a valid PHP version and update the system info if you are able to do so

**Comment by saiyadsalma** [comment] 2016-08-01 04:07
Hi @pboisvert , Sorry its PHP Version 5.6.11.

**Comment by SerhiyShkolyarenko** [comment] 2016-09-12 15:00
Hi @saiyadsalma!
Is it reproducible for you on Magento 2.0.11?
We checked 2.1.3 and it works properly both on php 5.6 and php 7.

**Comment by SerhiyShkolyarenko** [comment] 2016-09-27 09:24
We are closing this issue because it hasn’t been updated in more than two weeks. Please feel free to add your steps to reproduce and we'll reopen the issue.

**Closed as completed by SerhiyShkolyarenko** 2016-09-27 09:24 UTC
Labels: bug report
