### ISSUE TITLE
Database sessions pile up

### ISSUE THREAD

**Issue by amenk** [magento/magento2#26308] opened 2020-01-08 11:31 UTC
### Preconditions (*)
Magento 2.2.x & 2.3.x & 2.4-develop

### Steps to reproduce (*)
1. Configure store to save session in DB(edit `env.php`)
![image](https://user-images.githubusercontent.com/51681618/72798226-45d4a900-3c4b-11ea-8c1d-2be92c887875.png)
2. Change `Admin Session Lifetime` to 60s for example
3. Flush cache and logout 
4. Login again and check data in DB `session` table(note the last added data about your session)
5. Wait 1 minute and click somewhere in admin
6. Redirect to login page
7. Login again
8. Check data again

### Expected result (*)
1. Expired sessions were deleted.

### Actual result (*)
1. Tons of old entries in "sessions" table

### Additional information
See also: https://magento.stackexchange.com/questions/300525/is-the-session-table-supposed-to-be-cleaned-up-automatically

Garbage collect is there, but seems to be never called:

https://github.com/magento/magento2/blob/0a1a283cd6a0cf4b98a051867f90150c9490fcec/lib/internal/Magento/Framework/Session/SaveHandler/DbTable.php#L154

shall we make a PR to add this to the core?

**Comment by magento-engcom-team** [comment] 2020-01-21 19:59
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30631` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by amenk** [comment] 2020-04-29 14:12
@sdzhepa  what is the progress of the internal ticket? Can I check that in any way or is it private?

**Comment by sdzhepa** [comment] 2020-04-30 21:18
Hello @amenk 

I do not see any progress in the internal ticket `MC-30631` Jira ticket.
Unfortunately, it still in "Ready for Dev" status

**Comment by ioweb-gr** [comment] 2020-05-17 12:55
I've noticed that in customer sessions too. I've had two websites in 2.3.1 and the sessions table reached 2.5m entries with none of them being cleared even though they were long past their expiration date. 

After running a cleanup sql command to delete all sessions that the expiry timestamp had passed only 27 sessions were left. I think this is really important because the size of the DB increases really fast in popular eshops.

**Comment by amenk** [comment] 2020-05-30 20:00
@ioweb-gr which cleanup command did you use? And how long did it run?

**Comment by amenk** [comment] 2020-05-30 20:02
Also each and every crawling attempt seems to open a new session - is that normal?

**Comment by ioweb-gr** [comment] 2020-05-31 05:19
@amenk I think it was pretty straightforward. 

I went to https://www.unixtimestamp.com/index.php to get the timestamp for the date before which I wanted to clear the sessions. For example anything that should have expired 15 days ago e.g. 15/5/2020 = 1589500800

I then executed 

```sql
DELETE FROM `session` where `session_expires` < 1589500800;
```

**Comment by mischabraam** [comment] 2020-06-08 12:18
https://github.com/weprovide/magento2-module-sessioncleaner
This might help.

**Comment by amenk** [comment] 2020-06-08 13:02
@mischabraam Thank you the module :)

I just realized that it might be an option to store the sessions in Redis as well ...

**Closed as completed** 2020-10-13 09:23 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Framework/Session, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P1, Severity: S1, Progress: done, Reported on 2.2.x

**Comment by ioweb-gr** [comment] 2020-10-13 09:26
Was this fixed? What's the relevant pull request?

**Comment by ihor-sviziev** [comment] 2020-10-19 16:01
@sidolov @sdzhepa @gabrieldagama wat this issue fixed?

**Comment by gabrieldagama** [comment] 2020-10-19 16:09
@ihor-sviziev @ioweb-gr The issue was fixed by internal pull request and it is already merged, please let us know if you still face the issue on 2.4-develop branch.

Thanks.

**Comment by ihor-sviziev** [comment] 2020-10-19 16:12
Ok, Seems like here is related commits:
https://github.com/magento/magento2/commit/aa034d06859b1bff72121d98d094ec0944084140 https://github.com/magento/magento2/commit/d2d6c607bece5c137b1a5a8119974fc24571e6e3

**Comment by amenk** [comment] 2020-10-19 16:15
So this will be in 2.4.2, right?

**Comment by gabrieldagama** [comment] 2020-10-19 16:15
Correct @amenk

**Comment by sdzhepa** [comment] 2020-10-23 18:56
Fixed and delivered in https://github.com/magento/magento2/search?q=MC-30631&type=commits

**Comment by ioweb-gr** [comment] 2022-06-08 18:29
Redis has it's own set of issues when heavy traffic on the site

**Comment by hostep** [comment] 2022-06-08 19:37
@amenk: did you read the [new documentation](https://devdocs.magento.com/guides/v2.4/config-guide/sessions.html#session-gc) for the fix @sdzhepa mentioned before?

**Comment by amenk** [comment] 2023-02-08 10:20
@hostep Good point. As mentioned in the docs, Ubuntu uses a gc_probability of 0 which was the case for us, so it did not work.
We did a short test on staging now 1 / 1 / 10 seconds and sessions are deleted.

So this seems to work now I believe.
