### ISSUE TITLE
Order Invoice create page doesn't show order items properly for bundle product

### ISSUE THREAD

**Issue by dev-ajaysaini** [magento/magento2#27350] opened 2020-03-19 07:11 UTC
While crating invoice for bundle product doesn't show its child items.
### Preconditions (*)

1. Magento version 2.3.4 CE

### Steps to reproduce (*)

1. Create Bundle Product and add 2 items https://prnt.sc/ritlae
2. Place order for Bundle product with both the items https://prnt.sc/ritmme
3. Go to create invoice page for the same order https://prnt.sc/ritn0p

### Expected result (*)

1. Order Items should be displayed properly as in screenshot https://prnt.sc/rito2g

### Actual result (*)

1. Items are missing https://prnt.sc/ritn0p

**Comment by phuocnh** [comment] 2020-03-19 09:10
hi @webkul-ajaysaini

please edit product admin and with tab

Bundle Items 

please set value Ship Bundle Items to Separately

thanks

**Comment by webkul-ajaysaini** [comment] 2020-03-19 09:22
> hi @webkul-ajaysaini
> 
> please edit product admin and with tab
> 
> **Bundle Items**
> 
> please set value **Ship Bundle Items** to **Separately**
> 
> thanks

Ship Bundle Items to Separately is useful only to ship bundle items separately.

**Comment by phuocnh** [comment] 2020-03-19 09:59
> > hi @webkul-ajaysaini
> > please edit product admin and with tab
> > **Bundle Items**
> > please set value **Ship Bundle Items** to **Separately**
> > thanks
> 
> Ship Bundle Items to Separately is useful only to create shipment of bundle items separately, getting this issue at invoice creation page not in shipment creation page.
> 
> Thanks

with **Bundle Items to together**  it will show order items together when processing invoice.
Because you can invoice partial (with **Bundle Items to together** order items together)
But when invoice done. You can see order items is Separately.

thanks

**Comment by ajijshekh123** [comment] 2020-03-20 05:53
Hi @webkul-ajaysaini 
I have reviewed this issue as per your scenario. This is not an issue But if admin wants to create an invoice bundle product list should be displayed after generating the invoice block. Now the Product list is not displayed properly.

**See attached screenshot:**
**Before Generate Invoice:**

![Invoice_Bundle Product](https://user-images.githubusercontent.com/24711761/77139700-01278b80-6a9d-11ea-9173-5a4e668a8f5c.jpg)

**After Generate Invoice:** 

![AfterInvoice_Bundle Product](https://user-images.githubusercontent.com/24711761/77139746-3633de00-6a9d-11ea-8e43-aa9885dbb2ba.jpg)

Thanks.

**Comment by ajijshekh123** [comment] 2020-03-20 09:26
See attached Magento 2.4 Instance screenshot:

![2 4 Invoice Issue](https://user-images.githubusercontent.com/24711761/77150889-dd733e00-6aba-11ea-8f6a-6c06676cb540.jpg)

**Comment by magento-engcom-team** [comment] 2020-06-17 19:11
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35252` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2020-09-10 19:45
Hi @webkul-ajaysaini. Thank you for your report. 
The issue has been fixed in magento/magento2#27602 by @gauravagarwal1001 in 2.4-develop branch
Related commit(s):
 - [2f8b560ab3801595d8e78b2f4c696c8c75974e9b](https://github.com/magento/magento2/commit/2f8b560ab3801595d8e78b2f4c696c8c75974e9b)
 - [51fcc42c31b916ecc134e94df055792e0772f7e6](https://github.com/magento/magento2/commit/51fcc42c31b916ecc134e94df055792e0772f7e6)
 - [0591d51dbbff7bfb4714a29d8b2e682d46f76708](https://github.com/magento/magento2/commit/0591d51dbbff7bfb4714a29d8b2e682d46f76708)
 - [140c351ead8abf866df95312985b871bfd60ec55](https://github.com/magento/magento2/commit/140c351ead8abf866df95312985b871bfd60ec55)
 - [699c98fa1a2db63badd7441697c1da4b0dabb370](https://github.com/magento/magento2/commit/699c98fa1a2db63badd7441697c1da4b0dabb370)

The fix will be available with the upcoming 2.4.2 release.

**Closed as completed by magento-engcom-team** 2020-09-10 19:45 UTC
Labels: Issue: Ready for Work, bug report, Component: Sales, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Admin, Reproduced on 2.4.x, Fixed in 2.4.x, Event: Global-Contribution-Day, Priority: P2, Priority: P3, Severity: S2, Severity: S3, Triage: Done, Progress: done, Reported on 2.3.4
