### ISSUE TITLE
Frontend wrongly shows a default price in a product list and a product view for a customer with a custom tier group price specified

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#3101] opened 2016-01-24 10:55 UTC
https://mage2.pro/t/544
https://community.magento.com/t5/Just-Ask-Alan/Group-pricing-on-Magento-2/m-p/26734

**Comment by zolthan** [comment] 2016-03-24 15:08
Hi,

anything new about this issue?

**Comment by blizam** [comment] 2016-04-13 19:35
+10 from me; important feature to have working correctly.

**Comment by davidalger** [comment] 2016-04-13 23:42
@zolthan / @blizam Would one of you mind opening a new issue with full steps to reproduce so that the core team can properly debug the issue? I'm going to close this one due to lack of information from the OP, so it would be great if you could do that so the team can chase it down!

**Closed as completed by davidalger** 2016-04-13 23:42 UTC

**Comment by zolthan** [comment] 2016-04-14 06:58
Hi David,

I can't believe that the ticket is just closed?! In the first link on this page https://mage2.pro/t/topic/544 the problem is explained with screenshots.

And in the second link it is explained textually:

> Hi Alan
> 
> I need to show a wholesale price for my products for users in the Wholesale customer group.  This was easy in the Group Price functionality in Mage 1.9, but for some reason has been removed from Mage 2.
> 
> I have tried the following:
> 
> Setting up a separate Wholesale website
> - The Price attribute in the product's Basic Settings screen treats the Price attribute as Global scope, even though in the Attributes it shows that Price is Website scope
> 
> Using the Tiered Pricing in Advanced options
> - Even with the Quantity set as 1, it will only show the tiered price in the basket, not the catalogue pages
> 
> Any help would be appreciated
> 
> Many thanks

The probelm is, that the Group Prices were removed in Magento 2 and it is not possible to set a Qty-1 tier price for specific customer groups.

Best
Sebastian Wilhelm

**Comment by devdesco-ceo** [comment] 2016-04-30 23:02
I do not think its a bug, or may be it is.

What I did, and it works flawlesly, I set up differnt customer groups, and in "Catalog Price Rule" I have created a rule for each group applying %%% discount to whole catalog, or categories of choice.

Then, in Tier pricing on a product edit page, I entered tier pricing, starting with "2 and above", etc. NOT "1 and above".

See my screenshots, and always remember: "NEWLY DISCOVERED BUGS MAY TURN INTO FEATURES IF NOT DEAL WITH FOR A LONG TIME". LOL

![image 2016-04-30 17 30 22](https://cloud.githubusercontent.com/assets/8983883/14939060/997fa62e-0efd-11e6-9488-1730edc3639e.png)
![image 2016-04-30 17 30 41](https://cloud.githubusercontent.com/assets/8983883/14939061/99840f7a-0efd-11e6-9119-c53822a8d303.png)
![image 2016-04-30 17 30 54](https://cloud.githubusercontent.com/assets/8983883/14939062/9988cede-0efd-11e6-92dc-0bc51931c14d.png)
![image 2016-04-30 17 32 53](https://cloud.githubusercontent.com/assets/8983883/14939063/99890aca-0efd-11e6-9492-3acddb61409c.png)
![image 2016-04-30 17 33 18](https://cloud.githubusercontent.com/assets/8983883/14939064/998f597a-0efd-11e6-9c40-ab8dd201e8a5.png)
![image 2016-04-30 17 36 55](https://cloud.githubusercontent.com/assets/8983883/14939065/999661ca-0efd-11e6-80b4-9395271c9f35.png)
![image 2016-04-30 17 59 57](https://cloud.githubusercontent.com/assets/8983883/14939066/99a4f83e-0efd-11e6-8125-d0a6f24c96da.png)

**Comment by blizam** [comment] 2016-05-02 04:06
The issue is resolved for me, personally, in 2.0.4... and I may have had other issues in my 2.0.2 install

**Comment by devdesco-ceo** [comment] 2016-05-02 04:30
Good to know! :+1:

**Comment by yosefkurniawan** [comment] 2017-06-30 09:55
Is it really solved already?
Because I am still having this issue on Magento 2.1.3.
