### ISSUE TITLE
Magento 2 new FedEx api not getting the right price

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [magento/magento2#39159] opened 2024-09-12 06:51 UTC
### Preconditions and environment

- Magento version: 2.4.7-p2
- FedEx negotiated rates

### Steps to reproduce

1. Navigate to store as guest
2. Place order
3. Get FedEx Shipping rates

### Expected result

Get our special deal prices

### Actual result

Get "normal price

### Additional information

Hello,

I just upgraded to 2.4.7-p2 to get the new FedEx api working.

Connection works fine but I'm not getting the right prices for our account.

FedEx tells us that we have a wrong param in the request :
`"rateRequestType": [
    "LIST"
],`
Should be
`"rateRequestType": [
    "PREFERRED"
],`

I could not see this option in admin.
Should it not figure there?

I tried to change this directly in vendor/magento/module-fedex/Model/Carrier.php and it seems to do the job.
But I also tried to override the Model to avoid update issues without luck.

Any idea on how I could get this fixed please?

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by alikhani97** [comment] 2024-09-18 11:09
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-10-03 07:02
Hi @ShapesGraphicStudio,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

![Checkout-10-03-2024_11_46_AM](https://github.com/user-attachments/assets/c9e57d1c-e492-4c91-b048-26b391e62830)


We are able to get the FedEx Shipping rates.Could you please elaborate the steps to reproduce to proceed further and please let us know if we are missing anything.

Thanks.

**Comment by Mohamed-Asar** [comment] 2024-10-03 13:13
@engcom-Bravo This issue exist only REST API method. Please compare the shipping rates for both REST API and SOAP method, you will see rates difference in REST API Response
I've verified with fedex team, they said magento is passing the wrong request type. please see the below screenshot 

![image](https://github.com/user-attachments/assets/c5b7ba00-bdac-4e5d-ac2a-96ebd7e798ba)

**Comment by ShapesGraphicStudio** [comment] 2024-10-10 07:22
@engcom-Bravo the problem here is not about getting shipping rates but getting the RIGHT rates for us.

We dealed special rates with FedEx, but they were not being displayed to our customers.

FedEx team (commercial and deev) told us us that we have a wrong param in the request :
"rateRequestType": [ "LIST" ],
Should be
"rateRequestType": [ "PREFERRED" ],
To have the right price.

After changing that we had the right prices showing, so I think this param should be an option in admin.

**Comment by Mohamed-Asar** [comment] 2024-11-19 11:34
@engcom-Bravo Any updates on this issue ?

**Comment by engcom-Bravo** [comment] 2024-11-20 10:31
Hi @Mohamed-Asar,

Thanks for your update.

We have verified the issue in Latest 2.4-develop instance and we got the below response in Rest API.


<img width="950" alt="Screenshot 2024-11-20 at 11 14 29" src="https://github.com/user-attachments/assets/e7a3edd1-604a-485c-8334-929b6cdf55ca">



[{"carrier_code":"flatrate","method_code":"flatrate","carrier_title":"Flat Rate","method_title":"Fixed","amount":10,"base_amount":10,"available":true,"error_message":"","price_excl_tax":10,"price_incl_tax":10},{"carrier_code":"fedex","method_code":"FEDEX_EXPRESS_SAVER","carrier_title":"Federal Express","method_title":"Express Saver","amount":25.15,"base_amount":25.15,"available":true,"error_message":"","price_excl_tax":25.15,"price_incl_tax":25.15},{"carrier_code":"fedex","method_code":"FEDEX_GROUND","carrier_title":"Federal Express","method_title":"Ground","amount":25.44,"base_amount":25.44,"available":true,"error_message":"","price_excl_tax":25.44,"price_incl_tax":25.44},{"carrier_code":"fedex","method_code":"FEDEX_2_DAY","carrier_title":"Federal Express","method_title":"2 Day","amount":27.54,"base_amount":27.54,"available":true,"error_message":"","price_excl_tax":27.54,"price_incl_tax":27.54},{"carrier_code":"fedex","method_code":"FEDEX_2_DAY_AM","carrier_title":"Federal Express","method_title":"2 Day AM","amount":31.21,"base_amount":31.21,"available":true,"error_message":"","price_excl_tax":31.21,"price_incl_tax":31.21},{"carrier_code":"fedex","method_code":"STANDARD_OVERNIGHT","carrier_title":"Federal Express","method_title":"Standard Overnight","amount":41.53,"base_amount":41.53,"available":true,"error_message":"","price_excl_tax":41.53,"price_incl_tax":41.53},{"carrier_code":"fedex","method_code":"PRIORITY_OVERNIGHT","carrier_title":"Federal Express","method_title":"Priority Overnight","amount":45.48,"base_amount":45.48,"available":true,"error_message":"","price_excl_tax":45.48,"price_incl_tax":45.48},{"carrier_code":"fedex","method_code":"FIRST_OVERNIGHT","carrier_title":"Federal Express","method_title":"First Overnight","amount":78.03,"base_amount":78.03,"available":true,"error_message":"","price_excl_tax":78.03,"price_incl_tax":78.03},{"carrier_code":"fedex","method_code":"SMART_POST","carrier_title":"Federal Express","method_title":"Smart Post","amount":93.64,"base_amount":93.64,"available":true,"error_message":"","price_excl_tax":93.64,"price_incl_tax":93.64}]


There is a difference in two FEDEX GROUND and Smart Post shipping methods.Is this difference you are referring and also could you please let us know if we are missing anything and elaborate the steps to reproduce.

Thanks.

**Comment by Mohamed-Asar** [comment] 2024-11-20 12:15
@engcom-Bravo  Fix is applied on this [commit](https://github.com/magento/magento2/commit/b22a00f09d869b35c445a35d371b54c18cd6d1f6) by adobe team, Thats why the issue is not reproducing. I think you can close my PR and this Issue as well

**Comment by engcom-Bravo** [comment] 2024-11-21 04:20
Hi @Mohamed-Asar,

Thanks for your update.

Since the issue has been resolved by this https://github.com/magento/magento2/commit/b22a00f09d869b35c445a35d371b54c18cd6d1f6. We are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-11-21 04:20 UTC
Labels: Priority: P2, Progress: done, Issue: needs update, Reported on 2.4.7-p2
