### ISSUE TITLE
Some files not existed or created (pub/media/styles.css, jquery-storageapi.js, etc.)

### ISSUE THREAD

**Issue by tylerd92vn** [magento/magento2#8042] opened 2017-01-05 03:46 UTC
### Preconditions

1. Magento 2.1.3 Enterprise
2. Nginx

### Steps to reproduce

1. rm -rf var/di/* var/generation/* var/cache/* var/page_cache/* var/view_preprocessed/* var/composer_home/cache/*
2. sudo chmod 777 -R var pub pub/media app/etc
3. php bin/magento setup:static-content:deploy
4. php bin/magento cache:clean

### Expected result

1. The site should load successfully

### Actual result

1. A lot of files are missing
![magento2-kanmo-error-css](https://cloud.githubusercontent.com/assets/4945950/21668409/20cf5304-d334-11e6-850f-8184501c5c09.png)

**Comment by korostii** [comment] 2017-01-06 08:05
Looks like a duplicate of #7869 , please try the workaround suggested on that issue:

```
> INSERT INTO `core_config_data` (`scope`, `scope_id`, `path`, `value`) VALUES ('default', 0, 'dev/static/sign', '0');
```

It makes me sad that we don't get frequent patch\bugfix releases for even the most obvious bugs like this one, forcing each of us to run into these bugs. 
Why not fix them once and for all as soon as they're discovered?

**Comment by veloraven** [comment] 2017-01-11 12:42
I'm closing this issue as a duplicate.
Please note that Enterprise issues should be reported via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level

**Closed as completed by veloraven** 2017-01-11 12:42 UTC
