### ISSUE TITLE
[GraphQl] Get product reviews is not filter by store Id

### ISSUE THREAD

**Issue by huykon** [magento/magento2#30337] opened 2020-10-05 04:15 UTC
### Preconditions (*)

1. Magento 2.4.0
2. Configuration the site have least 2 storeviews.

### Steps to reproduce (*)

Irrespective of the store code passed to the graphql query in the headers - Product reviews which does not exist for other store are also returned.

1. Enabled Product Reviews from admin (Stores - Configuration - Catalog - Catalog - Product reviews)
2. Stores - Configuration - Attributes - rating - select price - Set rating visibility to both stores - Save
3. Go to front end - default website - product details page - add rating and save
4. Run graphql query:
_{
  productReviewRatingsMetadata {
    items {
      id
      name
      values {
        value_id
        value
      }
    }
  }
}_
Reponse retrieved as expected.
5. Pass other store code header and run the query - No issue. empty retrieved in response
6.Stores - Configuration - Attributes - rating - select another value - Set rating visibility to both stores - Save
7.Goto front end other website store - Add ratings for price and value and submit
8. Pass other store code header (Ex: france) and run the query - No issue. Both the ratings are retrieved.
9. Now pass the Store code "default" in headers and run the above query
Issue: Both the rating names are retrieved. for default store view - no other (value) rating is submitted but still getting in the response. Hence confirming the issue.

### Expected result (*)

1. Separate the product review by each storeview
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by huykon** [comment] 2020-10-05 04:16
@magento I am working on this

**Comment by alitopaloglu** [comment] 2021-08-29 12:42
Same issue occurs on v2.4.3

Need to get storeId from graphQL context and pass it to productReviewsDataProvider to filter review collection by store inside provider.

**Comment by engcom-Bravo** [comment] 2022-09-12 09:11
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-09-16 10:08
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-09-16 11:17
Verified the issue on Magento 2.4-develop branch and the issue is reproducible.
Irrespective of the store code passed to the graphql query in the headers - Product reviews which does not exist for other store are also returned.
Steps:
Enabled Product Reviews from admin (Stores - Configuration - Catalog - Catalog - Product reviews)
Stores - Configuration - Attributes - rating - select price - Set rating visibility to both stores - Save
Go to front end - default website - product details page - add rating and save
Run graphql query:
_{
  productReviewRatingsMetadata {
    items {
      id
      name
      values {
        value_id
        value
      }
    }
  }
}_
Reponse retrieved as expected.
Pass other store code header and run the query - No issue. empty retrieved in response
Stores - Configuration - Attributes - rating - select another value - Set rating visibility to both stores - Save
Goto front end other website store - Add ratings for price and value and submit
Pass other store code header (Ex: france) and run the query - No issue. Both the ratings are retrieved.
Now pass the Store code "default" in headers and run the above query
Issue: Both the rating names are retrieved. for default store view - no other (value) rating is submitted but still getting in the response. Hence confirming the issue.

**Comment by engcom-November** [comment] 2023-03-03 04:23
Hi @huykon ,

I re-verified the issue on Magento 2.4-develop instance and after internal discussions, it has been concluded that this is expected behavior but not a bug. "productReviewRatingsMetadata" Graphql response behavior is as per Admin configuration but not based on front end ratings added. Stores - Configuration - Attributes - rating - select price and value - Set rating visibility to both stores and save. If the Graphql query is ran even before rating is added, both price and value are retrieved in the response since enabled in Admin configuration. Kindly refer the Magento [docs](https://developer.adobe.com/commerce/webapi/graphql/schema/products/queries/product-review-ratings-metadata/) and provide your inputs on this.
Thank you.

**Comment by engcom-November** [comment] 2023-03-17 04:21
Hi @huykon ,
We are closing this issue as there has been no latest update on the same. Kindly create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2023-03-17 04:21 UTC
Labels: Component: GraphQL, Reproduced on 2.4.x, Priority: P2, Severity: S0, Project: GraphQL, Progress: done, Issue: ready for confirmation, Issue: needs update, Reported on 2.4.0, Area: Product
