### ISSUE TITLE
Fixes for Issue #5666 - Global Design Configuration Not Saving

### ISSUE THREAD

**Issue by vivek201** [magento/magento2#5703] opened 2016-07-19 18:12 UTC
#5666

Hello,
I may have found the issue that is stopping the configuration from being saved. If you look at the if condition in [https://github.com/magento/magento2/blob/develop/app/code/Magento/Email/Model/AbstractTemplate.php#L672]
You will see that if the `$storeId` is 0, then false will be returned, which is the case here for global configuration. If I change the condition to `($storeId !== false)`, I can successfully save the configuration.

Please suggest.

**Comment by andimov** [comment] 2016-07-21 08:24
@vivek201 
Thank you for reporting! Could you please provide this solution using pull request?

**Comment by andrewsladen** [comment] 2017-04-27 03:24
You're a champion, @vivek201

**Comment by vivek201** [comment] 2017-05-03 14:47
@andrewsladen Glad it helped someone. :)

**Comment by magento-engcom-team** [comment] 2017-10-26 11:30
@vivek201, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-26 11:30 UTC
Labels: bug report, Area: Frontend, Issue: Confirmed, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid

**Comment by minhluan259** [comment] 2017-12-15 19:25
@magento-engcom-team 
The issue fixed in 2.2.0, 2.1.9 but it still in magento 2.2.2
https://prnt.sc/ho0wn8

**Comment by Vikram0811** [comment] 2018-01-01 15:21
Correct. How could I resolve this issue ?
