### ISSUE TITLE
Urgent: Unable to change attribute set on new product

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#25644] opened 2019-11-18 20:38 UTC
# Preconditions (*)

Magento 2.3.3

### Steps to reproduce (*)

1. Add new product
2. Change attribute set
3. ??? Nothing happens
4. Can't save product because not all required attribute set fields are filled in

### Expected result (*)

Be able to add new product and change attribute set so we can add new products.

### Actual result (*)

Not being able to add new products.

**Comment by ajijshekh123** [comment] 2019-11-19 04:24
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-19 04:25
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-19 04:25
Hi @ajijshekh123, here is your [Magento instance](https://i-25644-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25644-2-3-develop.instances.magento-community.engineering/admin](https://i-25644-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2019-11-19 04:51
Hello, @Zyles,

I have created a new attribute and apply the new attribute on Add new product section. I can't reproduce this issue.
**Please, refer attached the video:**

![1](https://user-images.githubusercontent.com/24711761/69117615-45d2f400-0ab6-11ea-989f-8979948605ad.gif)

If you have reproduced this issue please attached video or add some additional information to reproduce this issue.

Thanks.

**Comment by Zyles** [comment] 2019-11-19 18:25
Then you have an issue with the upgrade path after upgrading to 2.3.3 because it worked before.

The ajax loading icon does not show up when changing attribute set.

I get no error messages. It just does not work.

**Comment by ajijshekh123** [comment] 2019-11-20 04:25
Hi @Zyles,

Can you please provide me Proper steps or videos?
I have verified the latest Magento 2.3 instance but I can't find it. 

Thanks.

**Comment by ajijshekh123** [comment] 2019-11-20 09:49
Hi @Zyles,

It may be an upgrading issue.

**Comment by Zyles** [comment] 2019-11-20 15:39
Your video above is correct steps.

But it does not work for me after upgrade to 2.3.3.

When changing "attribute set" the form is not updated.

**Comment by Zyles** [comment] 2019-11-20 21:20
All caches have been cleared. No progress.

I can get the form to update doing the following:

1. Add Product
1. Change Attribute Set
1. Add Attribute (top right)
1. Add a random attribute to the product
1. Click Add Selected
1. Change attribute set again (NOW IT UPDATES) ...

**Comment by ajijshekh123** [comment] 2019-11-21 05:01
@Zyles - I have applied the Same scenario but I can't reproduce this issue. It's working fine on my end.

Thanks.

**Comment by Zyles** [comment] 2019-11-21 16:57
Good for you.

What is my solution?

We need to add new products. Upgrading Magento brought more bugs than it fixed.

**Comment by Zyles** [comment] 2019-11-22 03:18
1. New fresh install
2. Moved the database from old installation to new install
3. No third party modules installed
4. Same problem

Seems to be an issue with database migration on an update or something.

**Comment by Zyles** [comment] 2019-11-22 04:12
Heres a video for you.

![magento2bug](https://user-images.githubusercontent.com/1741593/69397496-be1ffc00-0ce6-11ea-821e-fe2519bd270e.gif)

**Comment by Zyles** [comment] 2019-12-04 18:20
Still affected by this issue. We can't upgrade our store.

How can I debug this behaviour? Why is the network log empty? How can i see what call changing attribute set is making?

**Comment by ajijshekh123** [comment] 2019-12-05 04:26
@sdzhepa - Can you help to @Zyles. I can't reproduce this issue.

Thanks.

**Comment by sdzhepa** [comment] 2019-12-05 15:23
Hello @ajijshekh123 @Zyles 

I will try to investigate and reproduce, not sure about today but soon.

**Comment by Zyles** [comment] 2019-12-05 16:10
I upgraded from 2.3.1 to 2.3.3. So maybe an issue with that.

**Comment by ajijshekh123** [comment] 2019-12-06 04:28
Okay, @sdzhepa...Thanks for the Update.

**Comment by engcom-Echo** [comment] 2019-12-11 13:23
Hello All

I am not able to reproduce this issue on the 2.3.3 branch by provided steps.
**Testing scenario:**

**Preconditions:**

1. Upgrade Magento from 2.3.1 to 2.3.3 via Command Line as described [here](https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html)
2. Create a new Attribute Set

**Steps to reproduce:**

1. Add new product
2. Change Attribute Set to previously created

**Result**
Ajax loaded successfully.
![Peek 2019-12-11 14-57](https://user-images.githubusercontent.com/51681435/70624863-df12a780-1c29-11ea-86e7-dc3f976ddd00.gif)

So I have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Echo** 2019-12-11 13:23 UTC
Labels: Component: Catalog, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid
