### ISSUE TITLE
salesInvoiceOrder REST API does not make downloadable products available

### ISSUE THREAD

**Issue by nthurston** [magento/magento2#19003] opened 2018-11-01 21:36 UTC
### Preconditions (*)

1. Magento version 2.2.6
2. REST API salesOrderInvoice

### Steps to reproduce (*)

1. Create Downloadable product
2. Place order for product
3. POST to /V1/order/{orderId}/invoice to invoice the order/item

### Expected result (*)

1. Downloadable product should be available

### Actual result (*)

1. Downloadable product is still pending

**Comment by magento-engcom-team** [comment] 2018-11-01 21:36
Hi @nthurston. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nthurston do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-11-02 03:34
Hi @pmclain. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2018-11-02 04:50
@pmclain Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by pmclain** [comment] 2018-11-02 05:31
The link statuses are updated using an [observer](https://github.com/magento/magento2/blob/da1a96c32eb105606453e89a5ff70b550b4f20f7/app/code/Magento/Downloadable/etc/events.xml#L12-L14), but the event does not fire when creating an invoice with the REST endpoint.
The `InvoiceOrderInterface` implementation for the endpoint calls [`beginTransaction`](https://github.com/magento/magento2/blob/a31f4a35c018ad09654e5bd5871086b73fbd3d2d/app/code/Magento/Sales/Model/InvoiceOrder.php#L165) which causes the observed event to not fire.
The `_save_commit_after` is dispatched through a commit callback that is conditionally executed [based on the current connection's transaction level](
https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/Model/ResourceModel/AbstractResource.php#L93). The previous call to `beginTransaction` increments the transaction level, which results in the callbacks not executing.

**Comment by magento-engcom-team** [comment] 2018-11-02 05:35
@pmclain Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96071`, `MAGETWO-96072` were created

**Comment by agorbulin** [comment] 2018-11-02 14:13
#mageconf

**Comment by agorbulin** [comment] 2018-11-02 16:16
Fixed in pull request #19036

**Comment by sidolov** [comment] 2018-11-06 18:06
Hi @nthurston. Thank you for your report. 
The issue has been fixed in magento/magento2#19040 by @swnsma in 2.3-develop branch
Related commit(s):
 - [5dc7add05b66271f4ad8c8be85c20d4beb173306](https://github.com/magento/magento2/commit/5dc7add05b66271f4ad8c8be85c20d4beb173306)
 - [e19d70e3fd43184eeeb009129bf0a564fae002ea](https://github.com/magento/magento2/commit/e19d70e3fd43184eeeb009129bf0a564fae002ea)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by sidolov** 2018-11-06 18:06 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Downloadable, Event: mageconf

**Comment by magento-engcom-team** [comment] 2018-11-06 18:12
Hi @nthurston. Thank you for your report. 
The issue has been fixed in magento/magento2#19036 by @swnsma in 2.2-develop branch
Related commit(s):
 - [429815bee09f999ef3e38b93a5c097363fe2cbbd](https://github.com/magento/magento2/commit/429815bee09f999ef3e38b93a5c097363fe2cbbd)

The fix will be available with the upcoming 2.2.8 release.
