### ISSUE TITLE
Add a shopping cart in guest mode, and then register a new account, the additional_options of the shopping cart will be deleted, and the info_buyRequest will be modified. How to solve it?

### ISSUE THREAD

**Issue by zxiaoh** [magento/magento2#35591] opened 2022-06-08 01:12 UTC
### Preconditions and environment

- Magento version：2.3.7

### Steps to reproduce

1. Add to cart as a visitor
2. Register a new account
3. Some specifications of the shopping cart: info_buyRequest, additional_options are missing

### Expected result

Create a new account, the specifications of the shopping cart added as a guest should exist instead of being changed

### Actual result

Some specifications of the shopping cart: info_buyRequest, additional_options are missing

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-06-21 14:47
Hi @zxiaoh ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue. info_buyRequest in  quote_item_option db table is not removed. Could not find additional_options in db tables
![image](https://user-images.githubusercontent.com/60198231/174828767-ae4a2dda-c27e-4e12-b584-59e5c3b81790.png)
Kindly recheck the behavior on Magento 2.4-develop branch and elaborate steps/missing configuration details to reproduce the issue.
Thank you.

**Comment by engcom-November** [comment] 2022-07-05 05:38
Hi @zxiaoh ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-07-05 05:38 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
