### ISSUE TITLE
Base price is showing for configurable product if catalog rule is applied

### ISSUE THREAD

**Issue by ytorbyk** [magento/magento2#6573] opened 2016-09-11 17:10 UTC
### Preconditions

Magento 2.1.1 with sample data
1. Base currency is $
2. Store view currency is Ukrainian Hryvnia (currency rate 25 for the test)
3. Catalog rule is applied for  Men > Tops >  Hoodies & Sweatshirts category (10% discount)
### Steps to reproduce
1. Go to any configurable product from the Men > Tops >  Hoodies & Sweatshirts category
2. Select any options
### Expected result
1. Price is show in store view currency with set rate (25)
### Actual result
1. Store view currency symbol is shown but price is base
2. **Before selections of options**
   <img width="1305" alt="screen shot 2016-09-11 at 20 00 52" src="https://cloud.githubusercontent.com/assets/6418650/18419049/b1d81eaa-785b-11e6-8fc4-59b386154fdc.png">
3. **After option selection**
   <img width="1339" alt="screen shot 2016-09-11 at 20 01 00" src="https://cloud.githubusercontent.com/assets/6418650/18419054/b98b1882-785b-11e6-905c-f5319d5e5559.png">

**Comment by sevos1984** [comment] 2016-09-13 16:15
Thanks for posting, Yurii. Internal ticket created MAGETWO-58351

**Comment by magento-engcom-team** [comment] 2017-10-06 11:30
@ytorbyk, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-06 11:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Tax, Component: Catalog, Issue: Clear Description, Issue: Format is valid
