### ISSUE TITLE
Incorrect method return value in \Magento\Shipping\Model\Carrier\AbstractCarrier::getTotalNumOfBoxes()

### ISSUE THREAD

**Issue by korostii** [magento/magento2#13319] opened 2018-01-22 16:47 UTC
Please see the method `getTotalNumOfBoxes()` in `\Magento\Shipping\Model\Carrier\AbstractCarrier`: https://github.com/magento/magento2/blob/2.2.2/app/code/Magento/Shipping/Model/Carrier/AbstractCarrier.php#L512-L531

Incoming `$weight` parameter is not checked to be integer. Moreover, even if it is, you can still get a float result when `$weight > $maxPackageWeight` since these are both arbitrary numbers.

This method is a member of `AbstractCarrier` class commonly used for 3-rd party implementations of the Shipmen Carrier SPI and might be used by 3rd-party developers in their modules.
In order to apply proper validation and\or rounding around the method's return results, it would be helpful to see the actual return value in PHPDocs which are commonly used by IDEs when providing hints, for example here: http://take.ms/9dnaD

Additionally, the method name is severely misleading: it implies the method is a getter, however it can modify object's internal state. Moreover, the value returned is in fact what seems to be an average weight of a box, not "Total number of boxes" as one might assume.

**Backward Compatibility:** Please note that Magento's USPS implementation expects float return value, implying internal knowledge of the method: https://github.com/magento/magento2/blob/2.2.2/app/code/Magento/Usps/Model/Carrier.php#L341
If any rounding is to be added, it should probably be done via a new extra method, deprecating the old one (if at all)

### Preconditions

1. Magento CE 2.1.10, Magento CE 2.2.2
2. PHP 7.0.18

### Steps to reproduce

1. Open file app/code/Magento/Shipping/Model/Carrier/AbstractCarrier.php
2. Scroll down to getTotalNumOfBoxes method

### Expected result

1. Observe correct return type "float" declared in PHPDoc block 
OR proper rounding applied to the `$weight` variable.

### Actual result

1. Observe incorrect return type "int" declared in PHPDoc block
AND no rounding applied to $weight variable

**Comment by magento-engcom-team** [comment] 2018-02-08 14:30
@korostii, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2019-02-03 04:34
Hi @cedmudit. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-03-30 21:00
Hi @korostii. Thank you for your report. 
The issue has been fixed in magento/magento2#20898 by @cedmudit in 2.3-develop branch
Related commit(s):
 - [56504e1d8b0bde92a0eba4cec2ef233ad147dfc9](https://github.com/magento/magento2/commit/56504e1d8b0bde92a0eba4cec2ef233ad147dfc9)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-30 21:00 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Event: mm19in
