### ISSUE TITLE
Consumer - Cannot receive product alert emails

### ISSUE THREAD

**Issue by loic-paquin** [magento/magento2#35673] opened 2022-06-24 09:39 UTC
### Preconditions and environment

- Magento version 2.4.4
- PHP 8.1
- Fix the issue  https://github.com/magento/magento2/issues/35602 since it will be executed first

### Steps to reproduce

- Enable product alert stock in BO (Configuration > Catalog >Product Alerts > Allow Alert When Product Comes Back in Stock > Yes)
- Select a Product without stock
- Register to a product stock alert
- Add stock to that product
- Launch the cron catalog_product_alert

### Expected result

- The consumer is launched
- The email is sent to the customer

### Actual result

- The email is not sent to the customer
`
Deprecated Functionality: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /home/loic/magento/vendor/magento/framework/Filter/Input/MaliciousCode.php on line 50`

### Additional information

The error is triggered when the product does not have a short description ( it seems products from sample data don't have short description)

Solution :
In _vendor/magento/module-product-alert/view/frontend/templates/email/stock.phtml L25_
Replace :
`<?php if ($shortDescription = $block->getFilteredContent($_product->getShortDescription())) : ?>`
with :
`       <?php if ($shortDescription = $block->getFilteredContent((string)$_product->getShortDescription())) : ?>`

In _vendor/magento/module-product-alert/view/frontend/templates/email/price.phtml L26_
Replace :
`       <?php if ($shortDescription = $block->getFilteredContent($_product->getShortDescription())) : ?>`
with :
`       <?php if ($shortDescription = $block->getFilteredContent((string)$_product->getShortDescription())) : ?>`

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-06-27 11:53
Hi @loic-paquin ,
Thank you for reporting and collaboration. This issue is a duplicate of https://github.com/magento/magento2/issues/35602 and has been confirmed here. We are closing this issue. Please move onto this ticket for latest updates/ solutions.
Thank you.

**Closed as completed by engcom-November** 2022-06-27 11:53 UTC
Labels: duplicate, Issue: ready for confirmation
