### ISSUE TITLE
Currency conversion not happening on email confirmations for bundle products.

### ISSUE THREAD

**Issue by lexiconnect** [magento/magento2#33426] opened 2021-07-06 12:40 UTC
**Preconditions (*)**
Magento 2.4.2
**Steps to reproduce (*)**
Set up currencies (ie, GBP and EUR)
Create a bundle product
Place an order for that product in anything other than the default currency

**Expected result (*)**
Price for the line item on the email confirmation should be converted to the correct currency.

**Actual result (*)**
Default price is shown, but with the correct currency symbol.

We have discovered an issue where by we sell in both GBP and EUR on different store views.  The prices are based on the GBP as default, and then converted via the standard Magento currency rates.

When a bundle is purchased on the EUR store views, the correct amounts are charged to the customer, but the email confirmation has the default price rather than the converted price for each order item.  I have tried to change $block->getItemPrice($_item) to $_order->formatPrice($item->getItemPrice($_item)) within module-bundle/view/frontend/templates/email/order/items/order/default.phtml but this does not appear to fix the issue.

For more details about the issue and configuration, please check this [link](https://github.com/magento/magento2/issues/33426#issuecomment-875752884)

**Comment by engcom-November** [comment] 2021-07-07 12:45
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible:
**Steps performed:**
1. Setup EU Store (Germany)
2. Change the EU Store Currency setup to EUR 
Admin -> Setup EUR currency (Stores -> Configuration -> General -> Currency Setup) 
3. Create Bundle Product -> Catalog -> Poducts -> Add Bundle product
4. Navigate to Germany website -> Store Front -> Product Details page -> **Unable to add a bundle product to cart. Add to Cart button is not displayed.**

![image](https://user-images.githubusercontent.com/60198231/124760489-6e8b5400-df4e-11eb-8c21-ac91af1c60ac.png)

**Add to Cart button is displayed only for default store.**
However, We are able to add Simple Product to Cart for Germany Store and place Order
5. Verify Order Confirmation Email -> Currency values displayed in EUR as expected. - No issue. (Currency conversion is happening as expected for Simple Products in Germany Store)
![image](https://user-images.githubusercontent.com/60198231/124760998-f2454080-df4e-11eb-88ba-6d8e48dd66de.png)
![image](https://user-images.githubusercontent.com/60198231/124761169-21f44880-df4f-11eb-9d10-edd80e9eefb9.png)

Note: For default US Store view -> I tried changing currency to EUR and Country to Germany.
From default store front end -> Purchased Bundled Product in EUR currency.
Order Confirmation email -> Values are displayed as expected. No issue.
![image](https://user-images.githubusercontent.com/60198231/124760356-4a2f7780-df4e-11eb-8e13-f0f30fe3b936.png)
![image](https://user-images.githubusercontent.com/60198231/124760401-54ea0c80-df4e-11eb-8a49-ebc5cff47f86.png)

@lexiconnect, Can you please provide the configuration details to display Add to Cart button in Product Details page for Bundle Products in other stores. 
We are able to customize and add to cart for Bundle Product from default store website only.
Thank you.

**Comment by lexiconnect** [comment] 2021-07-07 12:55
Hi

Without knowing how you set the bundle up in terms of prices etc.  it does look like you have replicated this issue.

Your order confirmation for the bundle shows the full price as €164.71 - but consists of 2 items priced at €48.00 as part of the bundle.  Not sure what the currency exchange rates you have used for this store.

![image](https://user-images.githubusercontent.com/33832397/124762471-d7f96b80-df2a-11eb-9e4d-2b6569634928.png)

**Comment by engcom-November** [comment] 2021-07-07 16:34
Verified the issue again using below configuration and the issue reproduced in both Email Confirmation and Admin Order Information page.
Admin -> Stores - Configuration - Currency Setup - Set Base Currency: US Dollar, Default Display Currency: Euro
Admin -> Stores - Configuration - Catalog - Catalog - Price - Catalog Price Scope - Set to Website
Create Bundle Product from Admin - Catalog -> products
Disable Dynamic Price and Enter Price Manually: **Ex: $50**
Bundle Items - Add Products to Option. **Ex: $48. Quantity: 3**
Fill the required information and Save
Navigate to Front-end - Product Details page 
Verify currency conversion displayed in EURO = (Original Price + product quantity*Product Price)
**EURO -> 35.34 + (3*33.92) = 137.10
US Dollar -> $50 + 3*48 = $194**
Add product to cart, proceed to checkout and place the Order using any Payment method.
Navigate to Admin -> Sales -> Orders -> Open the newly created Order - Items Ordered section:
Issue: 48EUR is displayed instead of $48 (US Dollar) in Admin Order Information section
Actual Result - Email Confirmation -> Wrong currency symbol is displayed for the Bundle Items Price value displayed
**Expected behavior:** It should be $ 48 or 33.92 EUR
![image](https://user-images.githubusercontent.com/60198231/124796492-da7db480-df6e-11eb-96d1-ae48c0236eda.png)
![image](https://user-images.githubusercontent.com/60198231/124796529-e6697680-df6e-11eb-93bf-a316cea491f0.png)
![image](https://user-images.githubusercontent.com/60198231/124796615-fd0fcd80-df6e-11eb-9c98-6405443ed7ba.png)

**Issues:**
![image](https://user-images.githubusercontent.com/60198231/124796262-968aaf80-df6e-11eb-875d-15a10ea33ef1.png)
![image](https://user-images.githubusercontent.com/60198231/124796398-bde17c80-df6e-11eb-992e-b6f10cdf416a.png)

**FYI.. Admin Configuration:**
![image](https://user-images.githubusercontent.com/60198231/124796706-17e24200-df6f-11eb-8937-b5f371dc51ed.png)
![image](https://user-images.githubusercontent.com/60198231/124796806-334d4d00-df6f-11eb-8cb2-0ff22929d535.png)

**Comment by magento-engcom-team** [comment] 2021-07-15 08:28
:white_check_mark: Confirmed by @engcom-November 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42853` were created

**Issue Available**: @engcom-November, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Closed as completed** 2021-10-14 15:09 UTC
Labels: Issue: Confirmed, Component: CurrencySymbol, Component: Email, Reproduced on 2.4.x, Priority: P1, Progress: done, Reported on 2.4.2
