### ISSUE TITLE
Unable to use banktransfer payment method in sales rule

### ISSUE THREAD

**Issue by Styopchik** [magento/magento2#24069] opened 2019-08-08 13:23 UTC
### Preconditions (*)
1. Magento 2.3.2
2. php 7.2.15

### Steps to reproduce (*)
1. Enable **Bank Transfer** payment method
![enable_bankpayment](https://user-images.githubusercontent.com/884525/62705857-f846e580-b9f6-11e9-9852-a60a0f16fa26.png)
1.a Clear cache (if enabled)
2. Create new **sales rule**
3. Under **Conditions** tab select **Payment method**
![select_payment_method](https://user-images.githubusercontent.com/884525/62706069-69869880-b9f7-11e9-9aee-4e67acadcbf1.png)

### Expected result (*)

1. **Bank Transfer** payment method should be present in available methods in **Offline Payment Methods** group

### Actual result (*)

1. **Bank Transfer** payment method is not present in available methods
![result](https://user-images.githubusercontent.com/884525/62706452-3db7e280-b9f8-11e9-89cf-f6c71d98d75c.png)

I suppose it happens because ```\Magento\Payment\Helper\Data::getPaymentMethodList``` takes available methods, from initial config (xml files), instead of taking **active** methods list via 
```\Magento\Payment\Model\Config::getActiveMethods()```

**Comment by Styopchik** [comment] 2019-08-08 13:27
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-08-08 13:27
Hi @Styopchik. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-08-08 13:27
Hi @Styopchik, here is your [Magento instance](https://i-24069-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24069-2-3-develop.instances.magento-community.engineering/admin](https://i-24069-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment] 2019-08-08 14:35
Hello @Styopchik. Thanks for applying. Could You please confirm You were able to reproduce the issue on a vanilla Magento installation.

**Comment by Styopchik** [comment] 2019-08-09 06:34
I can't reproduce this issue on magento 2.3-develop (it was fixed in https://github.com/magento/magento2/commit/28c86bed310311247604caa6c5c3b6c165fbd4f3), but the reason of the issue is still present in 2.3.2 version.

**Comment by Styopchik** [comment] 2019-08-09 06:50
And yes, i can confirm this issue on Vanilla Magento 2.3.2 installation

**Comment by engcom-Bravo** [comment] 2019-08-09 09:58
Thank You @Styopchik for reply. We also cannot reproduce this issue on the 2.3-develop version. If the issue is fixed in develop version this fix will be delivered only with the next release version. So due to our workflow we are closing this issue. Thanks for applying.

**Closed as completed by engcom-Bravo** 2019-08-09 09:58 UTC
Labels: Progress: needs update, Component: Payment, Issue: Format is valid
