### ISSUE TITLE
Magento doesnt save any changes on shipping settings

### ISSUE THREAD

**Issue by bargoslino** [magento/magento2#30824] opened 2020-11-06 16:27 UTC
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment] 2020-11-09 12:16
Hi, @bargoslino . 

Could you provide more details on how to reproduce this issue (Manual testing scenario, Actual and Expected Result)?
Thank you!

**Comment by bargoslino** [comment] 2020-11-09 14:14
Hello!

When i go, as i usually did, to the left panel en my Magento 2.2.6 to
Stores>Sales>Shipping Settings>Scheduled Delivery>Holiday Days to update
non-working days i could introduce new dates.
Currently i can do so, BUT when i click "save" nothing happens though it
says that changes were saved!
I mean... Magento confirmed that the changes were saved but when i double
check, it didn't!
Same happens with Delivery Days and in Shipping Methods "title" ... no
changes are never saved!

Here is the url:
https://mefisto.com.ar/mefistoc_admin/admin/system_config/edit/section/shipping/key/54ee06f0b68c33dc0dd8aed199ac3b4f405acb563f6929b97fccad7bbd9b5804/

Thank you for your help!

Regards,

BARBARA GOSLINO

bgoslino@mefisto.com.ar

Cel: +54911-5523-7188

www.mefisto.com.ar

**Comment by lenaorobei** [comment] 2020-11-10 18:38
@magento give me 2.4.1 instance

**Comment by lenaorobei** [comment] 2020-11-10 18:40
@magento give me 2.4-develop instance

**Comment by bargoslino** [comment] 2020-11-10 18:41
Hello!
I don't understand these mails.
Any news on possible solution?

Regards,

BARBARA GOSLINO

bgoslino@mefisto.com.ar

Cel: +54911-5523-7188

www.mefisto.com.ar

**Comment by lenaorobei** [comment] 2020-11-10 18:44
Hi @bargoslino. Please provide details and steps to reproduce so we can confirm the issue.

**Comment by lenaorobei** [comment] 2020-11-10 18:52
@magento give me 2.4.1 instance

**Comment by lenaorobei** [comment] 2020-11-10 19:39
@magento give me 2.4.1 instance

**Comment by engcom-Alfa** [comment] 2020-11-16 11:52
@magento give me 2.4.1 instance

**Comment by engcom-Alfa** [comment] 2020-11-16 12:58
Hi @bargoslino .

Unfortunately, we are not able to reproduce this issue on 2.4-develop.
Look like the issue connect with custom module. ( in part `Stores>Sales>Shipping Settings>Scheduled Delivery>Holiday Days to update`).
So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-11-16 12:58 UTC
Labels: Issue: needs update, not-confirmed, Reported on 2.2.x

**Comment by bargoslino** [comment] 2020-11-18 17:49
I confirm issue still persists!
How can it be solved?? There are holidays coming in Argentina and i need a
solution this week!

Regards,

BARBARA GOSLINO

bgoslino@mefisto.com.ar

Cel: +54911-5523-7188

www.mefisto.com.ar
