### ISSUE TITLE
Can't remove the item on minicart

### ISSUE THREAD

**Issue by advcha** [magento/magento2#9856] opened 2017-06-06 09:40 UTC
**Preconditions**
Magento : 2.1.6
PHP 7.0.19-1+deb.sury.org~trusty+2
MySQL server 5.6

**Steps to reproduce**
1. Adding product tot the cart
2. Click Cart icon then the minicart popup is showed up then click the trash icon
3. A popup is showed up "Are you sure you would like to remove this item from the shopping cart?" Then click 'OK'
4. Another popup is showed up "Attention We can't find the quote item."

**Expected result**
The popup "Attention We can't find the quote item." shouldn't be showed up

**Actual result**
The popup "Attention We can't find the quote item." is showed up and the item/product still exist in the minicart. the item counter not update either. I can't remove the item on the minicart. I already enabled the Full Page Cache (FPC) but it dont work.

**Comment by sumanparihar** [comment] 2017-06-12 07:09
This issue come :--
Click Cart icon then the minicart popup is showed up then click the trash icon and A popup is showed up "Are you sure you would like to remove this item from the shopping cart?" Then click 'OK'
=>After that again you Click Cart icon then the minicart popup is showed up then click the trash icon and A popup is showed up "Are you sure you would like to remove this item from the shopping cart?" Then click 'OK'

=>current Ajax request not completed and it's return false return.

if you wait for some time then you can see product deleted and mini cart also updated.
after remove the item other ajax request is running " /customer/section/load/?sections=cart,messages&update_section_id=true&_=1497250842497" to update the minicart.

**bug is only that loader is not implemented with ajax request.

**Comment by 1408sheva** [comment] 2017-06-23 10:23
@advcha We cannot reproduce this issue as described. Please provide the detailed steps we must follow to reproduce this issue. Please add more details to your description of the steps you followed when identifying this issue. Screenshot, video or logs would be helpful, too.

**Comment by advcha** [comment] 2017-06-23 15:26
@1408sheva Yeah. May be it's related to a few specific modules i'm using like firecheckout and ajax pro cart. I tried with another M2 installation without the modules and got no problem.

**Comment by veloraven** [comment] 2017-06-26 11:30
I'm closing this issue as it is not Magento issue.
If you can still reproduce this issue on clean Magento, please create a new GitHub issue report.

**Closed as completed by veloraven** 2017-06-26 11:30 UTC
Labels: bug report, Progress: needs update
