### ISSUE TITLE
Image role issue with different store view

### ISSUE THREAD

**Issue by manan-india** [magento/magento2#33158] opened 2021-06-07 07:17 UTC
### Preconditions (*)

Magento-2.4.2

### Steps to reproduce (*)

1. Create a product with single image in admin
2. Change the store view to default store, delete that image and add new image with assigning all the role to that image
3. Save the product

### Expected result (*)

1. New image should only be there with all the assigned roles and old image should be deleted.

### Actual result (*)

2. Both the images are there

---
- [x] Severity: **S2**

**Comment by thamyrisgregorio** [comment] 2021-06-10 22:34
@magento I'm working on it

**Comment by magento-engcom-team** [comment] 2021-06-10 22:40
@thamyrisgregorio Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by thamyrisgregorio** [comment] 2021-06-10 22:40
Manual verification of the issue description and reproduction steps was confirmed. 

https://user-images.githubusercontent.com/75129444/121605922-9d7fda00-ca23-11eb-882f-f4c5026f61bb.mp4

**Comment by magento-engcom-team** [comment] 2021-06-10 22:46
@thamyrisgregorio Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-06-10 22:46
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-06-10 22:49
:white_check_mark: Confirmed by @thamyrisgregorio 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42619` were created

**Issue Available**: @thamyrisgregorio, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by AZiniukhin** [comment] 2021-06-15 12:07
@magento I am working on this

**Comment by AZiniukhin** [comment] 2021-06-15 12:08
@magento add to contributors tea

**Comment by AZiniukhin** [comment] 2021-06-15 12:15
@magento add to contributors team

**Comment by AZiniukhin** [comment] 2021-06-15 12:16
@magento I am working on this

**Comment by engcom-Bravo** [comment] 2024-07-19 08:53
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-07-19 09:30
Hi @manan-india,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the attached video.


https://github.com/user-attachments/assets/4c1eae07-1f51-4094-a56a-9de4e13e5b78



New image should only be there with all the assigned roles and old image should be deleted.


Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-19 09:30 UTC
Labels: Issue: Confirmed, Priority: P2, Progress: done, Reproduced on 2.4.2, Area: Product
