### ISSUE TITLE
Content Customization

### ISSUE THREAD

**Issue by rishabhrkrai** [magento/magento2#6461] opened 2016-09-02 04:58 UTC
When I am setting transactional email logo, and press save configuration, it not saving the configuration and gives warning for Other Setting and Product Image Watermarks values.

### Preconditions

1. I use Magento version 2.1
2. Use PHP 5.6 and Apache 2.4
### Steps to reproduce

1. Go to Content -> Configuration -> Edit Theme -> Transactional Emails -> Set Logo and then Save configuration
### Expected result

![screenshot from 2016-09-02 10-27-21](https://cloud.githubusercontent.com/assets/20873227/18193213/09c9ed92-70f9-11e6-9ca6-acc16a0709da.jpg)

Not Saving the option
### Actual result

1. [Screenshot, logs]

**Comment by pboisvert** [comment] 2016-09-02 05:10
closing as duplicate of #6275 

please search for duplicates before reporting

**Closed as completed by pboisvert** 2016-09-02 05:10 UTC

**Comment by rishabhrkrai** [comment] 2016-09-02 05:46
thnx @pboisvert , not the same problem bt i resolved it

cheers!
