### ISSUE TITLE
Not able to add a widget to content page.

### ISSUE THREAD

**Issue by basselalaraaj** [magento/magento2#6290] opened 2016-08-23 13:14 UTC
### Preconditions
1.  Magento develop branch
2. Php 5 and mysql 5.6
### Steps to reproduce
1. Open a content page in adminhtml
2. Insert widget in the content through editor (user has no administrator rights, but a role with right to add and edit pages and widgets.)
### Expected result
1. Widget selecting and adding to page possible.
### Actual result
1. [Screenshot, logs]
   ![geen autorisatie](https://cloud.githubusercontent.com/assets/5745279/17892996/3f7c5504-6944-11e6-877f-a5f76585bc3b.jpg)

**Comment by sevos1984** [comment] 2016-08-25 11:47
Hello! Could you please specify your magento version and attach screenshot of your user role permissions. Thanks.

**Comment by basselalaraaj** [comment] 2016-08-25 11:51
@sevos1984
Magento develop branch (2.1.0)
![screen shot 2016-08-25 at 13 51 20](https://cloud.githubusercontent.com/assets/5745279/17968055/0891834c-6acb-11e6-83a7-49a1a91dc686.png)

**Comment by sevos1984** [comment] 2016-08-25 13:37
I can't reproduce it. Maybe it is your cache problem as it is said on screenshot, try clear it.

**Comment by basselalaraaj** [comment] 2016-08-26 07:17
@sevos1984 still reproducible, when trying to add a widget to a content page still getting access denied..
The logs are not showing any errors.

are you testing with a user with a role different than administrator?

**Comment by sevos1984** [comment] 2016-09-08 08:06
This is duplicate of https://github.com/magento/magento2/issues/6476. Closing

**Closed as completed by sevos1984** 2016-09-08 08:06 UTC
Labels: bug report, Component: Cms
