### ISSUE TITLE
404 when exporting csv and excel in Ordered Products Report

### ISSUE THREAD

**Issue by minhluan259** [magento/magento2#39261] opened 2024-10-15 09:22 UTC
### Preconditions and environment

- Magento 2.4.7-p3

### Steps to reproduce

1. Go to REPORTS > Products > Ordered
2. Select a date range for which the product was sold.
3. Click to Export csv or excel

### Expected result

Exported successfully

### Actual result

Return 404

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-10-16 06:16
Hi @minhluan259,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.



https://github.com/user-attachments/assets/39c6750a-b086-4bbd-b86b-a378d728e11c



We are able to Export the data successfully.

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still repoducible.

Thanks.

**Comment by minhluan259** [comment] 2024-10-16 09:15
@engcom-Bravo  you can reproduce the issue on Magento 2.4.7-p3

**Comment by engcom-Bravo** [comment] 2024-10-17 03:58
Hi @minhluan259,

Thanks for your update.

We have verified the issue in Latest 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.



<img width="1431" alt="Screenshot 2024-10-17 at 09 27 39" src="https://github.com/user-attachments/assets/27509a57-57df-4aea-8fbf-d977798e9d45">



It is returning 404.

Hence Confirming the issue.

Thanks.

**Comment by Mohamed-Asar** [comment] 2024-10-20 13:38
@magento i'm working on this

**Comment by sgautamrave** [comment] 2024-11-19 14:01
Hi @Mohamed-Asar ,

It's urgent we are facing this issue on production.
Can you please share the solution for this issue?

Thanks,

**Comment by Mohamed-Asar** [comment] 2024-11-19 14:09
Hi @sgautamrave I already Raise [PR](https://github.com/magento/magento2/pull/39283) for this issue. please create a custom patch and apply it in your production site

**Comment by ihor-sviziev** [comment] 2024-11-21 21:27
The issue was already fixed in 2.4-develop branch in https://github.com/magento/magento2/commit/7677eb61f8c672cfc0e8984d36e90ca5580e3a4f.
I’m closing this issue as solved

**Closed as completed by ihor-sviziev** 2024-11-21 21:27 UTC
Labels: Component: ImportExport, Issue: Confirmed, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P2, Progress: done, Area: Import / export, Reported on 2.4.7-p3
