### ISSUE TITLE
Buy 1 Get 3 -> Problem

### ISSUE THREAD

**Issue by jonathanlubkepeter** [magento/magento2#28851] opened 2020-06-23 12:48 UTC
**Preconditions**

1. Magento 2.3.2
2. Magento 2.3.3
3. Magento 2.4-develop

**Steps to reproduce**

1.  Create new cart price rules with the following configuration

![image](https://user-images.githubusercontent.com/61063285/85404303-610e5200-b524-11ea-9f5e-171cd66bd403.png)

2. Add 3 products to cart with has price = $100

![image](https://user-images.githubusercontent.com/61063285/85404707-fad5ff00-b524-11ea-84cc-0b36f19cd8e6.png)

**Expected result**

 "grand_total": 100,
 "base_grand_total": 100,
 "subtotal": 100,
 "base_subtotal": 100,
 "discount_amount": -200,
 "base_discount_amount": -200

**Actual result**

1. 
"grand_total": 300,
 "base_grand_total": 300,
 "subtotal": 300,
 "base_subtotal": 300,
 "discount_amount": 0,
 "base_discount_amount": 0

2.
![image](https://user-images.githubusercontent.com/61063285/85405152-99626000-b525-11ea-8c93-b480dcaf701a.png)

**Comment by swathishs** [comment] 2020-06-24 11:28
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-24 11:28
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-06-24 11:30
Hi @swathishs, here is your [Magento instance](https://i-28851-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28851-2-4-develop.instances.magento-community.engineering/admin_adef](https://i-28851-2-4-develop.instances.magento-community.engineering/admin_adef)
Login: `ba20fa16` Password: `4893d9704f3d`
Instance will be terminated in up to 3 hours.

**Comment by tgamanov** [comment] 2020-07-31 16:25
Hello @peterlobao.
I have tested the described issue and have the same result. Issue confirmed.
Also, I have found, that according to the Magento code in
Magento/SalesRule/Model/Rule/Action/Discount/BuyXGetY.php
there is condition:
  
```
        $x = $rule->getDiscountStep();
        $y = $rule->getDiscountAmount();
        if (!$x || $y > $x) {
            return $discountData;
        }
```

which protect from cases when  'Discount Qty Step (Buy X)' is less than 'Discount Amount' (like you had).
So, probably it is not a bug, but a feature.
Still, information about this restriction should be mentioned in the documentation
https://docs.magento.com/user-guide/marketing/price-rules-cart-buy-x-get-y-free.html
and these fields validation during rule creation should be added.

**Comment by engcom-Bravo** [comment] 2020-11-03 14:06
Hello @peterlobao 

Thank you for your report

This is actually not a bug. You can not set the _Discount Qty Step (Buy X)_ is less than the _Discount Amount_

So we are closing this issue. Please feel free to comment, reopen or create a new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by engcom-Bravo** 2020-11-03 14:06 UTC
Labels: non-issue, not-confirmed, Reported on 2.3.2
