### ISSUE TITLE
How to see the all sales history in magento 2

### ISSUE THREAD

**Issue by thebrandstore** [magento/magento2#9822] opened 2017-06-01 10:29 UTC
### Preconditions

1. 
2. 

### Steps to reproduce

1. How to see the sales order history in magento 2

2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by korostii** [comment] 2017-06-01 10:51
If you are looking for some help or an advice regarding setup or admin panel management please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 

The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.

**Comment by veloraven** [comment] 2017-06-22 07:27
I'm closing this issue as it is not a bug.

**Closed as completed by veloraven** 2017-06-22 07:27 UTC
