### ISSUE TITLE
Unable to drag and drop in Google Chrome (dynamic-rows or grid)

### ISSUE THREAD

**Issue by navarr** [magento/magento2#32271] opened 2021-02-24 12:08 UTC
This issue is a re-opening of #8495 which was prematurely closed.  JIRA ticket MC-24739

### Preconditions (*)

1. Magento 2.4-develop
2. Touch-Screen Laptop (emulation instructions included below)
3. Google Chrome 88

### Steps to reproduce (*)

1. Visit the sales order grid
2. Attempt to rearrange columns by clicking one, holding down the mouse button, and moving the mouse

### Expected result (*)

1. Columns move with the mouse

### Actual result (*)

1. Nothing happens

### Touchscreen Emulation Instructions
To emulate using a touch-screen device, load the Sales Order Grid listed in Steps to Reproduce, put a breakpoint on Magento_Ui/js/grid/dnd.js L18 (isTouchDevice =), and then reload the page.

When the breakpoint is hit, type into the JavaScript console `document.ontouchstart = null` (On a supported device, ontouchstart will be NULL with no event created.  On an unsupported device, it will be undefined)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by navarr** [comment] 2021-05-12 11:06
@magento give me 2.4-develop instance

**Comment by navarr** [comment] 2021-05-12 11:14
Recreated on 2.4-develop (2.4.3-dev)

**Comment by engcom-Alfa** [comment] 2021-05-26 09:40
Hi @navarr 
Tried on Magento 2.4-develop using Chrome 90 & on Windows system , Columns are able to move .Can not reproduce the issue.
![image](https://user-images.githubusercontent.com/51679138/119638651-7d052c80-be34-11eb-93a6-32d0c67e2611.png)

**Comment by navarr** [comment] 2021-05-26 13:36
@engcom-Alfa: Are you using a touch-screen device?  If not, you'll need to follow the steps I outlined in "Touchscreen Emulation Instructions."  I've added a note to it that wasn't there before (namely that you have to refresh after placing the breakpoint, and why we're doing this in the console)

**Comment by engcom-Delta** [comment] 2021-06-17 07:08
Hi @navarr,
Thanks for replying and confirm the issue once again.

Followed below steps to reproduce the issue on Magento 2.4 Develop.
1.	Log in to Magento admin backend
2.	Go to Sales Orders
3.	Try to rearrange the columns  on UI
4.	Observe that you should be able to rearrange the columns
5.	Press F12 from chrome browser , click on Dock side icon (3 dots) from right hand side
6.	Select Mobile icon
7.	Refresh or Reload the page
8.	Try to drag  & drop the columns or rearrange the columns
9.	Observe that drag & drop functionality is not working, Hence Issue marked as confirmed
Please find the attached screenshot.
![image](https://user-images.githubusercontent.com/51681379/122348560-eb876700-cf68-11eb-8069-dd70e585530e.png)

**Comment by magento-engcom-team** [comment] 2021-06-17 07:10
@engcom-Delta Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-06-17 07:10
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-06-17 07:10
@engcom-Delta Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-06-17 07:10
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-06-17 07:10
@engcom-Delta Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-06-17 07:10
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-06-18 08:18
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42671` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Delta** [comment] 2024-09-04 08:38
Hi @navarr ,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop and the issue is not reproducible. Kindly refer the screenshots.

**Steps to reproduce -**
1. Log in to Magento admin backend
2. Go to Sales Orders
3. Try to rearrange the columns on UI
4. Observe that you should be able to rearrange the columns
5. Press F12 from chrome browser , click on Dock side icon (3 dots) from right hand side
6. Select Mobile icon
7. Refresh or Reload the page
8. Try to drag & drop the columns or rearrange the columns with Touch-screen.
9. Observe that drag & drop functionality is working as expected.

https://github.com/user-attachments/assets/6d6cadcf-341c-4585-b36d-a504f17bc7b7


Kindly recheck the issue on latest Magento 2.4-develop instance and Please let us know if you are still facing any issue.

Thanks.

**Closed as completed by engcom-Delta** 2024-09-04 08:38 UTC
Labels: Component: Sales, Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done
