### ISSUE TITLE
Changes in the category description are not working in Magento 2.4.7

### ISSUE THREAD

**Issue by leonardotbb** [magento/magento2#39280] opened 2024-10-18 14:02 UTC
### Preconditions and environment

- Magento version: 2.4.7-p3
- Community version
- Php version 8.3

### Steps to reproduce

1. Navigate to Catalog > Categories
2. Change the Scope from All Store Views > Default Store View
3. Edit the category's 'Description' field
4. Save the changes

https://github.com/user-attachments/assets/7c9b7f95-f328-495b-be12-fd8dd0ecb311

### Expected result

The content change should be saved upon reloading the page

### Actual result

After saving the changes, the page reloads, but the new text is not reflected in either the backend or the frontend.

### Additional information

However, the changes do apply if you do it in the Scope: All Store Views, but they cannot be edited by individual store view.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by zapotocnylubos** [comment] 2024-10-19 10:46
This does not happen on my site with 2.4.7-p3 and pagebuilder enabled.
But after turning off the pagebuilder - using tinymce, I see the same behaviour.

**Comment by n2diving-dgx** [comment] 2024-10-19 12:37
Duplicate of 
https://github.com/magento/magento2/issues/38622

**Comment by engcom-Bravo** [comment] 2024-10-21 04:00
Hi @leonardotbb,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.


https://github.com/user-attachments/assets/15015a84-5f22-477b-84e7-a8e7bc9cdbe8



The content has been saved successfully.Issue has been already fixed here https://github.com/magento/magento2/pull/38623.


Thanks.

**Closed as completed** 2024-11-04 04:26 UTC
Labels: Issue: needs update, Reported on 2.4.7-p3
