### ISSUE TITLE
Magento 2 product attribute source issue

### ISSUE THREAD

**Issue by Naberdz** [magento/magento2#23828] opened 2019-07-23 07:36 UTC
### Preconditions (*)

1. Magento 2.3.2
2. PHP 7.2

### Steps to reproduce (*)

1. Create product attribute with source model
````
<?php
namespace Vendor\Module\Setup;

use Magento\Catalog\Setup\CategorySetup;
use Magento\Eav\Setup\EavSetup;
use Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface;
use Magento\Catalog\Model\ResourceModel\Product\Attribute\Collection;
use Magento\Catalog\Model\ResourceModel\Eav\Attribute;
use Magento\Catalog\Model\ResourceModel\Product;

class ProductSetup extends EavSetup
{

	public function getDefaultEntities()
	{
		return [
			'catalog_product' => [
				'entity_type_id' => CategorySetup::CATALOG_PRODUCT_ENTITY_TYPE_ID,
				'entity_model' => Product::class,
				'attribute_model' => Attribute::class,
				'table' => 'catalog_product_entity',
				'additional_attribute_table' => 'catalog_eav_attribute',
				'entity_attribute_collection' =>
				Collection::class,
				'attributes' => [
					'auto_merk' => [
						'type' => 'varchar',
						'label' => 'Auto Merk',
						'input' => 'multiselect',
						'source' => \Vendo\Module\Model\Product\Source\AutoMerken::class,
						'frontend' => '',
						'required' => false,
						'note' => '',
						'class' => '',
						'backend' => 'Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend',
						'sort_order' => '30',
						'global' => ScopedAttributeInterface::SCOPE_STORE,
						'default' => null,
						'visible' => true,
						'user_defined' => true,
						'searchable' => true,
						'filterable' => true,
						'comparable' => false,
						'visible_on_front' => true,
						'unique' => false,
						'apply_to' => '',
						'group' => 'General',
						'used_in_product_listing' => true,
						'is_used_in_grid' => false,
						'is_visible_in_grid' => false,
						'is_filterable_in_grid' => false,
					],
					'auto_model' => [
						'type' => 'varchar',
						'label' => 'Auto Model',
						'input' => 'multiselect',
						'source' => \Vendo\Module\Model\Product\Source\AutoModel::class,
						'frontend' => '',
						'required' => false,
						'note' => '',
						'class' => '',
						'backend' => 'Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend',
						'sort_order' => '30',
						'global' => ScopedAttributeInterface::SCOPE_STORE,
						'default' => null,
						'visible' => true,
						'user_defined' => true,
						'searchable' => true,
						'filterable' => true,
						'comparable' => false,
						'visible_on_front' => true,
						'unique' => false,
						'apply_to' => '',
						'group' => 'General',
						'used_in_product_listing' => true,
						'is_used_in_grid' => false,
						'is_visible_in_grid' => false,
						'is_filterable_in_grid' => false,
					],
				]
			]
		];
	}
}

````
```
namespace Vendor\Module\Model\Product\Source;

class AutoMerken extends \Magento\Eav\Model\Entity\Attribute\Source\AbstractSource
{
	protected $_options;
	
	/**
	 * getAllOptions
	 *
	 * @return array
	 */
	public function getAllOptions()
	{
		if ($this->_options === null) {
			$this->_options = [
				['value' => 'ac', 'label' =>  'AC'],
				['value' => 'alfa_romeo', 'label' =>  'Alfa Romeo'],
				['value' => 'aston_martin', 'label' =>	'Aston Martin'],
				//...... and so on
			];
		}
		return $this->_options;
	}
		
	final public function toOptionArray()
	{
		return array(

			array('value' => 'ac', 'label' =>  'AC'),
			array('value' => 'alfa_romeo', 'label' =>  'Alfa Romeo'),
			array('value' => 'aston_martin', 'label' =>	 'Aston Martin'),
			//...... and so on over 50 additional options
		);
	}
}
```
same functions apply to another source model with over 700 options

2. Add attribute options to product
<img width="480" alt="Schermafbeelding 2019-07-22 om 13 36 10" src="https://user-images.githubusercontent.com/37579149/61689706-f824c580-ad27-11e9-8cef-03f896a93a71.png">

### Expected result (*)

1. Indexer should work but gives error.
2. Product should be visible in frontend.

### Actual result (*)

1. 
```
Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index has been rebuilt successfully in 00:00:01
Category Products index has been rebuilt successfully in 00:00:00
Product Categories index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:00
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-136-1-0-1' for key 'PRIMARY', query was: INSERT  INTO `catalog_product_index_eav_temp` (`entity_id`,`attribute_id`,`store_id`,`value`,`source_id`) VALUES (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?)
Stock index has been rebuilt successfully in 00:00:00
Inventory index has been rebuilt successfully in 00:00:00
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:00
Catalog Search index has been rebuilt successfully in 00:00:00
```
Checked database but can't find anything out of order
<img width="713" alt="Schermafbeelding 2019-07-23 om 09 29 12" src="https://user-images.githubusercontent.com/37579149/61691714-72574900-ad2c-11e9-83b4-d189b5d41474.png">

2. 
<img width="472" alt="Schermafbeelding 2019-07-23 om 09 08 28" src="https://user-images.githubusercontent.com/37579149/61690466-ac731b80-ad29-11e9-8b4f-b521564ae823.png">
3. if i remove attributes from product set and save product it gives no error with index and product is visible in frontend.
<img width="513" alt="Schermafbeelding 2019-07-23 om 09 13 41" src="https://user-images.githubusercontent.com/37579149/61690696-33c08f00-ad2a-11e9-9664-82804185c792.png">

**Comment by manish0592** [comment] 2019-09-15 16:37
#mm19pl

**Comment by magento-engcom-team** [comment] 2019-09-15 16:38
@manish0592 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by manish0592** [comment] 2019-09-19 08:20
Hi @Naberdz ,
I'm trying to reproduce this issue by using the steps you mention above, but not able to reproduce.

**Comment by engcom-Charlie** [comment] 2019-09-30 07:54
Hello @Naberdz 
We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.
So i have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-09-30 07:54 UTC
Labels: Issue: Format is valid, Event: mm19pl
