### ISSUE TITLE
GraphQL cart handling of "The requested qty is not available"

### ISSUE THREAD

**Issue by niklaswolf** [magento/magento2#33281] opened 2021-06-18 11:21 UTC
### Preconditions (*)

1. Magento 2.4.1., but I don't see anything in the changelog for 2.4.2 regarding this issue

### Steps to reproduce (*)

1. Add a product to the cart via graphql with a quantity > 1
2. Set the available stock of the product to something lower than the added quantity in step 1
3. Load the cart via the `cart` graphql query
4. The error "The requested qty is not available" is returned as part of the response, but the cart item quantity is not reduced

The same applies when you set the product to "out of stock" in step 2, then you get the error message "some of the products are out of stock", but the cart item is not removed

### Expected result (*)
I think the optimal case would be, that the cartItem's quantity should be set to the max of the available stock. Furthermore, the error message/object should contain more information on the cartItem in question, so that a appropriate message can be shown to the user.

### Actual result (*)
The cartItems quantity is not set to the max of the available stock and there is no indication which cartItem is causing this error. The user can not complete the purchase. Only if one deletes all cart items and readds them, this is possible.

<img width="528" alt="Bildschirmfoto 2021-06-18 um 11 55 18" src="https://user-images.githubusercontent.com/16021919/122553445-f78e2a00-d037-11eb-885d-e5f3ad18223a.png">

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2021-06-23 11:44
Hi niklaswolf,
Tried to reproduce the issue with provided steps, we are unable to reproduce it.
Queries used: 
1. Request: 
mutation {
  generateCustomerToken(
    email: "abcititechies@XXXXX.com"
    password: "XXXXXXX"
  ) {
    token
    }
    
Response: 
eyJraWQiOiIxIiwiYWxnIjoiSFMyNTYifQ.eyJ1aWQiOjIsInV0eXBpZCI6MywiaWF0IjoxNjI0NDQ1MTA0LCJleHAiOjE2MjQ0NDg3MDR9.nW5IxQroEFrRFGpk-0GFTXLK-ZxVzoNDynTFl_AacVA
2. Request
{
  customerCart{
    id
  }
}

Response:
{
  "data": {
    "customerCart": {
      "id": "pIzrYTVQLkRUeDgWlcVCIisJRLfOT55c"
    }
  }
}

3. Available quantity for sku id# 24-MB01 , quantity -->100
4. I tried to add 110 to cart then got error message "Could not add the product with SKU 24-MB01 to the shopping cart: The requested qty is not available"
Request:
mutation {
  addSimpleProductsToCart(
    input: {
      cart_id: "pIzrYTVQLkRUeDgWlcVCIisJRLfOT55c"
      cart_items: [
        {
          data: {
            quantity: 110
            sku: "24-MB01"
          }
        }
      ]
    }
  ) {
    cart {
      items {
        id
        product {
          sku
          stock_status
        }
        quantity
      }
    }
  }
}
Response:
{
  "errors": [
    {
      "message": "Could not add the product with SKU 24-MB01 to the shopping cart: The requested qty is not available",
      "extensions": {
        "category": "graphql-input"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addSimpleProductsToCart"
      ]
    }
  ],
  "data": {
    "addSimpleProductsToCart": null
  }
}

It seems it is working as expected. Kindly provide more steps to reproduce the issue if required.

**Comment by niklaswolf** [comment] 2021-06-23 11:57
@magento give me 2.4-develop instance

**Comment by niklaswolf** [comment] 2021-06-23 12:16
@engcom-Delta if I follow the steps exactly, I receive exactly the issue I described. I'll add more details:
1. Product 24-MB01 has default stock 100
2. Add product 24-MB01 to the cart via graphql with quantity 90
3. Set the available stock of the product to something lower than the added quantity in step, for example 80.
3. Load the cart via the cart graphql query
4. The error "The requested qty is not available" is returned as part of the response, but the cart item quantity is not reduced and the error does not contain information on which cart-item has the error.

**Comment by magento-engcom-team** [comment] 2021-06-24 12:58
@engcom-Delta Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-06-24 12:58
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by engcom-Delta** [comment] 2021-06-24 12:58
Hi niklaswolf ,

Followed the steps and found that able to replicate the issue. Hence it is marked as issue confirmed.
Request:
{
  customerCart {
    id
    items {
      id
      product {
        name
        sku
      }
      quantity
    }
  }
}
Response:
{
  "errors": [
    {
      "message": "The requested qty is not available",
      "extensions": {
        "category": "graphql-input"
      },
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ],
      "path": [
        "customerCart",
        "items",
        0
      ]
    }
  ],
  "data": {
    "customerCart": {
      "id": "pIzrYTVQLkRUeDgWlcVCIisJRLfOT55c",
      "items": [
        null,
        {
          "id": "11",
          "product": {
            "name": "Bruno Compete Hoodie",
            "sku": "MH03"
          },
          "quantity": 1
        },
        {
          "id": "13",
          "product": {
            "name": "Joust Duffle Bag",
            "sku": "24-MB01"
          },
          "quantity": 90
        }
      ]
    }
  }
}
![Quantity_set](https://user-images.githubusercontent.com/51681379/123266432-a4c1e000-d519-11eb-822c-af96e896e376.jpg)

**Comment by niklaswolf** [comment] 2021-07-01 10:56
@engcom-Delta  this issue is still not marked as confirmed, even though you said so...

**Comment by theshreyas** [comment] 2021-08-05 15:27
has anyone got any hotfix for this ?

**Comment by engcom-November** [comment] 2021-08-18 09:56
Hi @niklaswolf / @theshreyas ,
Same behavior is present on 2.4-develop when tried to reproduce this manually on front end.
On reloading Shopping Cart page, error "The requested qty is not available" is displayed to the user if the quantity is not available. Also, product Quantity is not reduced but "Proceed to Checkout" button is not displayed to the user as quantity is no longer available which is current Magento behavior.

**Steps performed from admin and Front-end:**
Create Product from Admin with Quantity say ex: 10
Front-end - Add Product to Cart with quantity - Ex: 8
Admin - Product Edit page - Change the Quantity to ex: 6 and Save
Reindex and clear cache
Front-end - Products Cart page - Reload the page
Error: "The requested qty is not available" is displayed to the user and quantity is not reduced but user is not able to checkout which is expected behavior.
@niklaswolf , please check the behavior on 2.4-develop manually from Admin and Store front and provide your inputs.
Thank you.

**Comment by engcom-November** [comment] 2021-09-01 05:45
Hi @niklaswolf ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-09-01 05:45 UTC
Labels: Component: Catalog, Issue: needs update, Reported on 2.4.x

**Comment by azngeek** [comment] 2021-09-03 15:01
I think the issue is not resolved yet and can be reproduced.

**Comment by niklaswolf** [comment] 2021-09-03 15:02
@engcom-November why should I reproduce this in the Magento Frontend, when the issue topic is clearly about GraphQl-API?
Why do you close the issue, even if someone from Magento Engineering [confirmed the issue beforehand](https://github.com/magento/magento2/issues/33281#issuecomment-867615747) and apparently forgot to flag the issue as confirmed, [which I even pointed out afterwards](https://github.com/magento/magento2/issues/33281#issuecomment-872137761)?

**Comment by theshreyas** [comment] 2021-09-06 13:54
@engcom-November please take this up on high priority. This is serious bug.

**Comment by yaroslav-qlicks** [comment] 2022-01-05 14:43
Very strange that this kind of issues could wait so long(

**Comment by cmuench** [comment] 2022-02-17 15:54
I have the same issue in Magento 2.4.3-p1.
Cart item contains then a "null" value for the problematic item.
![image](https://user-images.githubusercontent.com/211294/154519211-58f176bd-4361-4f29-9d16-fb4c5a3f13e8.png)
