### ISSUE TITLE
Unnecessary load of product in the product page

### ISSUE THREAD

**Issue by jacquesbh** [magento/magento2#5793] opened 2016-07-25 14:58 UTC
On a product page, the product should be loaded once. Right? ;)

But the product's ID is given as argument instead of the product itself (the interceptor in that case). Which results in a new load of the product (already done on the product page…).

The problem is there: https://github.com/magento/magento2/blob/2db9e0f17f54368945/app/code/Magento/CatalogInventory/Block/Stockqty/AbstractStockqty.php#L87-L96

The method `Magento\CatalogInventory\Model\StockState:: getStockQty` is receiving an ID instead of the product itself. Then the load is done a second time: https://github.com/magento/magento2/blob/2db9e0f17f543689458fed20ccdac3f9f61a0f08/app/code/Magento/CatalogInventory/Model/StockStateProvider.php#L342-L343
### Preconditions
1.  Magento 2 EE version 2.0.2 (but still present in current version 2db9e0f17f54)
2. PHP 5 FPM / Nginx / MariaDB…
### Steps to reproduce
1. Load a product page
2. Count the numbers of load of the product… (easy with `\Magento\Catalog\Model\Product::_afterLoad`)
### Expected result

The product should be loaded once.
### Actual result

The product is loaded twice.

---

For me it can be solved simply by using `\Magento\CatalogInventory\Block\Stockqty\AbstractStockqty::getStockQty` instead of `\Magento\CatalogInventory\Block\Stockqty\AbstractStockqty::getProductStockQty`.
Because the second one is getting the product with `\Magento\CatalogInventory\Block\Stockqty\AbstractStockqty::getProduct` -> We are in the product page, the product is in the registry.

**Comment by choukalos** [comment] 2016-07-25 18:16
Tracking internally as MAGETWO-55946

**Comment by orlangur** [comment] 2016-07-26 11:19
> But the product's ID is given as argument instead of the product itself (the interceptor in that case). Which results in a new load of the product (already done on the product page…).

There is no need to pass product model anywhere actually, just product repository should be used to obtain product model instead of legacy `load` call.

**Comment by jacquesbh** [comment] 2016-07-27 14:20
@orlangur You're probably right. My point is that a load can be avoided here.

👍

**Comment by AVoskoboinikov** [comment] 2016-09-27 13:33
Hi @jacquesbh 
I am closing this issue because can not reproduce it in current mainline version. Here is some reasons for that:
1. Method \Magento\CatalogInventory\Block\Stockqty\AbstractStockqty::getProductStockQty does not loads product anymore. It uses \Magento\CatalogInventory\Api\Data\StockStatusInterface to get information about quantity. Check this https://github.com/magento/magento2/blob/2.1/app/code/Magento/CatalogInventory/Block/Stockqty/AbstractStockqty.php#L87-L96
2. There was bug with \Magento\Catalog\Model\Product::_afterLoad double call per each product load but it was already fixed, however it is not yet available in public repo.

So, I suggest you to wait until fix for _afterLoad() will be available and update your Magento installation to new version. 

Thanks for contributing!

**Closed as completed by AVoskoboinikov** 2016-09-27 13:33 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog

**Comment by jacquesbh** [comment] 2016-09-27 13:53
Thanks @AzVo  :)
