### ISSUE TITLE
Newsletter Cron Sending

### ISSUE THREAD

**Issue by arthursp** [magento/magento2#4421] opened 2016-05-06 14:36 UTC
## Steps to reproduce

Launch cron for newsletter queue ( create a console script which load Magento\Newsletter\Model\Observer::scheduledSend() )
## Expected result

Newsletter correctly sent to subscribers
## Actual result

Not sent : "5.1.7 Bad sender address syntax"

cause of this : 

`$transport = $this->_transportBuilder->setTemplateOptions(
                ['area' => \Magento\Framework\App\Area::AREA_FRONTEND, 'store' => $item->getStoreId()]
            )->setTemplateVars(
                ['subscriber' => $item]
            )->setFrom(
                ['name' => $this->getNewsletterSenderEmail(), 'email' => $this->getNewsletterSenderName()]
            )->addTo(
                $item->getSubscriberEmail(),
                $item->getSubscriberFullName()
            )->getTransport();`

Instead of this : 

`$transport = $this->_transportBuilder->setTemplateOptions(
                ['area' => \Magento\Framework\App\Area::AREA_FRONTEND, 'store' => $item->getStoreId()]
            )->setTemplateVars(
                ['subscriber' => $item]
            )->setFrom(
                ['name' => $this->getNewsletterSenderName(), 'email' => $this->getNewsletterSenderEmail()]
            )->addTo(
                $item->getSubscriberEmail(),
                $item->getSubscriberFullName()
            )->getTransport();`

**Comment by sevos1984** [comment] 2016-10-10 09:22
@arthursp Is this still actual?

**Comment by sevos1984** [comment] 2016-11-01 09:55
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-11-01 09:55 UTC
Labels: bug report, Component: Customer
