### ISSUE TITLE
REST API '/rest/V1/orders/create' return "Email has a wrong format".

### ISSUE THREAD

**Issue by brandonbai** [magento/magento2#24130] opened 2019-08-14 05:10 UTC
### Preconditons (*)

magento version:  **2.3.2**

### Steps to reproduce (*)

**I was shocked to find that this was related to the order of keys.**

1. call 'PUT /rest/V1/orders/create', body (eliminate other fields.):

```JSON
{
 "billing": {
 ...
 },
 "customer_email": "abc@def.com",
}
```

2. call 'PUT /rest/V1/orders/create', body (eliminate other fields.):

```json

{
 "customer_email": "abc@def.com"
 "billing": {
 ...
 }
}
```

### Expected result (*)

1. httpStatus: 200

```JSON
{
    "base_currency_code": "USD",
    "base_discount_amount": 0,
    "base_grand_total": 20,
    ...
}
```

2. httpStatus: 200

```JSON
{
    "base_currency_code": "USD",
    "base_discount_amount": 0,
    "base_grand_total": 20,
    ...
}
```

### Actual result (*)

1. httpStatus: 400

```json
{
    "message": "We can't save the address:\n%1",
    "parameters": [
        "Email has a wrong format"
    ]
}
```

2. httpStatus: 200

```json
{
    "base_currency_code": "USD",
    "base_discount_amount": 0,
    "base_grand_total": 20,
    ...
}
```

**Comment by engcom-Bravo** [comment] 2019-08-14 07:39
Hello, @brandonbai. This issue seems to be a duplicate of #22998 which already has been fixed in 2.3-develop branch. So we are closing Your issue now, but please feel free to reopen it if You manage to reproduce it on the latest develop branch. Thanks for applying.

**Closed as completed by engcom-Bravo** 2019-08-14 07:39 UTC
Labels: Issue: Format is not valid
