### ISSUE TITLE
Weird sample data installation issue

### ISSUE THREAD

**Issue by CoreyCole** [magento/magento2#1610] opened 2015-08-03 18:34 UTC
I'm getting a weird issue trying to install sample data on a fresh webstore. I've wiped the database and pulled a fresh directory. I'm able to install without sample data, but when I run
<code>composer require magento/sample-data:1.0.0-beta</code>
<code>bin/magento setup:upgrade</code>
<code>bin/magento sampledata:install admin</code>

I get the following output:
```bash
~/html/magento2$ bin/magento sampledata:install admin
Installing theme:
.
Installing customers:
sh: 1: /usr/sbin/sendmail: not found
.
Installing CMS pages:
....
Installing catalog attributes:
...........................
Installing categories:
.........................................
Installing simple products:
PHP Fatal error:  Call to undefined method Magento\Catalog\Model\Resource\Product\Interceptor::getWriteConnection() in /var/www/html/magento2/app/code/Magento/SampleData/Module/Catalog/Setup/Product/Gallery.php on line 144
```

**Comment by xcomSteveJohnson** [comment] 2015-08-03 18:46
Have you ever been able to do it? If so did you change anything?

Also, even though there's no need you might as well clean the var/generation and var/cache directories and try again.

**Comment by CoreyCole** [comment] 2015-08-03 19:01
Yes I've been able to before, but this time I'm trying to install the <code>1.0.0-beta</code> sample data.

I just tried switching my version to <code>"version": "0.74.0-beta16"</code> and my sample data version to <code>"magento/sample-data": "0.74.0-beta16"</code> in my <code>composer.json</code> file. It works just fine that way.

**Comment by danslo** [comment] 2015-08-03 19:02
@CoreyCole Is your magento2 install actually 1.0.0-beta too? I think you might be trying to install 1.0.0-beta sample data on an older magento version.

**Comment by CoreyCole** [comment] 2015-08-03 19:03
I did a fresh clone and in my <code>composer.json</code> the version line said <code>1.0.0-beta</code> before I changed it.

**Comment by vpelipenko** [comment] 2015-08-04 09:11
sample-data:1.0.0-beta is compatible only with Magento 1.0.0-beta https://github.com/magento/magento2/tree/master. Version in develop branch is not stable and can produce some errors.

**Comment by doroshkevich** [comment] 2015-08-04 10:36
I have the same issue with branch master.

**Comment by CoreyCole** [comment] 2015-08-04 14:52
Thanks! Running `git checkout master` made the installation run smoothly.

**Comment by miguelbalparda** [comment] 2015-08-04 20:23
Same happened here with a fresh install of Magento 2 from this repo. @CoreyCole how did you fixed this? If I try to do a git checkout master i get
[magetwod@sip1-176 public_html]$ git checkout master
error: Your local changes to the following files would be overwritten by checkout:
	composer.json
	composer.lock
Please, commit your changes or stash them before you can switch branches.

**Comment by mbrinton01** [comment] 2015-08-04 20:33
+1 for this error, used a clean install and it happens.

**Comment by miguelbalparda** [comment] 2015-08-04 20:34
I can confirm the solution proposed here works. After doing git checkout master and git pull I'm able to install Magento 2 with sample data.

**Comment by CoreyCole** [comment] 2015-08-04 20:38
Try `git checkout -f -b master`

**Comment by mbrinton01** [comment] 2015-08-04 20:54
Thank you @CoreyCole, I was just trying the same thing. Master branch works w/sample data.

**Comment by mazhalai** [comment] 2015-08-04 21:48
We have created  MAGETWO-41137 to investigate this issue

**Comment by santosh-brainvire** [comment] 2015-08-06 13:20
Hello ,

I did git checkout master, still i am getting the issue.

/var/www/magento2/bin/magento sampledata:install admin
Installing theme:
.
Installing customers:
sh: 1: /usr/sbin/sendmail: not found
.
Installing CMS pages:
....
Installing catalog attributes:
...........................
Installing categories:
.........................................
Installing simple products:
PHP Fatal error:  Call to undefined method Magento\Catalog\Model\Resource\Product\Interceptor::getWriteConnection() in /var/www/magento2/app/code/Magento/SampleData/Module/Catalog/Setup/Product/Gallery.php on line 144

**Comment by CoreyCole** [comment] 2015-08-06 13:48
@santosh-brainvire did you try `git checkout -f -b master` ?

**Comment by santosh-brainvire** [comment] 2015-08-06 13:52
@CoreyCole Yes, i am now on branch master. Here is output of git status.

git status
# On branch master
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   composer.json
#	modified:   composer.lock
#	modified:   pub/static/.htaccess
#	modified:   var/.htaccess
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	app/code/Magento/SampleData/
#	composer.json.bak
#
# It took 14.03 seconds to enumerate untracked files. 'status -uno'
# may speed it up, but you have to be careful not to forget to add
# new files yourself (see 'git help status').
no changes added to commit (use "git add" and/or "git commit -a")

**Comment by CoreyCole** [comment] 2015-08-06 13:55
Maybe try making your `composer.json` file is identical to the one [here](https://github.com/magento/magento2/blob/develop/composer.json) plus the one line to require the sample data 1.0.0-beta. Then try running `sudo composer update`

**Comment by MagePsycho** [comment] 2015-08-09 17:17
Even switching to master branch:
`git checkout -f -b master`

results in the same error:
>Installing CMS pages:
>....
>Installing catalog attributes:
>...........................
>Installing categories:
>.........................................
>Installing simple products:
>PHP Fatal error:  Call to undefined method >Magento\Catalog\Model\Resource\Product\Interceptor::getWriteConnection() in /magento2beta/app/code/Magento/SampleData/Module/Catalog/Setup/Product/Gallery.php on line 144

Any workaround for fixing?

**Comment by MagePsycho** [comment] 2015-08-09 17:24
I cann't see the getWriteConnection() method in Magento\Catalog\Model\Resource\Product\Interceptor

**Comment by Vinai** [comment] 2015-08-10 07:16
The sample data is currently incompatible with the develop branch.
I managed to get it working by checking out the master branch, making sure the composer.json version was refering to `"version": "1.0.0-beta"`, and that the required sample data version also was `"magento/sample-data": "1.0.0-beta"`.
After that the install went fine.
If you want to use the develop branch, you can't use the sample data, but you can use the generator from the performance tests to fill your catalog with categories and products. I tend to use the small profile, since it contains plenty of products for development purposes.
If you use that approach though the catalog won't look as nice, since the default theme will be used, not luma, and there aren't any CMS pages either.

**Comment by mkz71** [comment] 2015-08-14 04:13
I have the same problem when I install the sample data on one of my server.
I find out that if I disable SELinux, the sample data was installed without any problem.

**Comment by xcomSteveJohnson** [comment] 2015-08-14 11:35
Thanks. I'll add this to troubleshooting in the documentation.

**Comment by roman204** [comment] 2015-08-16 08:13
hmm did the `git checkout master` but now a new error throws 
PHP Fatal error:  Declaration of Magento\Store\Model\StoreManagerInterface\Proxy::getGroups() must be compatible with Magento\Store\Model\StoreManagerInterface::getGroups($withDefault = false, $codeKey = false) in /var/generation/Magento/Store/Model/StoreManagerInterface/Proxy.php on line 8

**Comment by danslo** [comment] 2015-08-16 10:59
Clear your var folder.

**Comment by kokoc** [comment] 2015-08-17 13:44
The fix for this issue is delivered. Could you please verify it?

**Comment by miguelbalparda** [comment] 2015-08-17 19:09
@kokoc i faced the same issue today.

**Comment by mrfroasty** [comment] 2015-09-09 09:35
Replacing getWriteConnection() with getConnection() works as well ....

**Comment by piotrekkaminski** [comment] 2015-10-03 18:33
It should be fixed now.

**Closed by piotrekkaminski** 2015-10-03 18:33 UTC
Labels: acknowledged, bug, PS
