### ISSUE TITLE
Issue accessing ScopeOverriddenValue->containsValue from a loop

### ISSUE THREAD

**Issue by michaelcallahan27** [magento/magento2#35218] opened 2022-03-23 15:33 UTC
### Preconditions (*)

1.  2.4.3-p1
2. Reproducible in any environment

### Steps to reproduce (*)

1. When calling the containsValue of this class, vendor/magento/module-catalog/Model/Attribute/ScopeOverriddenValue.php from within a loop of products, invalid results are returned.
2. ex....
        $store = $this->storeManager->getStore(STORE::DEFAULT_STORE_ID);
        $this->storeManager->setCurrentStore($store);
        $collection = $this->productCollectionFactory->create();
        $collection->addAttributeToSelect('*');
        $collection->addStoreFilter($store);
        $collection->addMediaGalleryData();
        $productCollection = [];

        foreach ($collection as $product) {
            $productData = [];

            // store scoped fields - get if Use Default Value is checked
            foreach($product->getStoreIds() as $storeId) {
                $storeProd = $this->productFactory->create()->setStoreId($storeId)->load($product->getId());
                $store = $this->storeManager->getStore($storeId);

                // name
                $field = "name";
                $productData[$field][$store->getCode()]["overridden"] = $this->scopeOverriddenValue->containsValue(
                ProductInterface::class, $product, $field, $storeId);
             }
        }

I was able to make this work by making a copy of the vendor/magento/module-catalog/Model/Attribute/ScopeOverriddenValue.php  class and adding this one line to the containsValue function($this->attributesValues[$storeId] = null;)...
public function containsValue($entityType, $entity, $attributeCode, $storeId)
    {
        if ((int)$storeId === Store::DEFAULT_STORE_ID) {
            return false;
        }

        /* This has been added to Magento's code to account for an issue that was run into when trying
           to use this method for more than one product.
           If this array is not cleared out, then once it finds that a product has an override for a
           particlar storeId/attributeCode combination, all subsequent calls for that storeId/attributeCode
           combination will return true, even for products that dont have overrides
           This occurs when accessing this method within a loop of products from another class
        */
        $this->attributesValues[$storeId] = null;

        if (!isset($this->attributesValues[$storeId])) {
            $this->initAttributeValues($entityType, $entity, (int)$storeId);
        }

        return isset($this->attributesValues[$storeId])
            && array_key_exists($attributeCode, $this->attributesValues[$storeId]);
    }

### Expected result (*)

1. [Screenshots, logs or description]
The call to containsValue (called for each product in the the product loop) should return the information for that specific product.

### Actual result (*)

1. Instead of returning the correct value for the current product passed into the containsValue function, it returns true for every product in the loop, once it finds an overridden attribute(Use Default Value unchecked) for any of the products in the loop for that Store/Attribute combination.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by michaelcallahan27** [comment] 2022-03-23 16:03
I tested with the latest version in the 2.4.dev branch and the issue no longer exists...
https://github.com/magento/magento2/blob/d1eea4f34df13f7af467ec8c9ae10a5ec509ed80/app/code/Magento/Catalog/Model/Attribute/ScopeOverriddenValue.php

**Comment by engcom-Hotel** [comment] 2022-03-30 07:02
Hello @michaelcallahan27,

Thanks for the confirmation that the issue is not there now. In that case, we are closing this issue.

Thanks

**Closed as completed by engcom-Hotel** 2022-03-30 07:02 UTC
Labels: Triage: Dev.Experience, Issue: ready for confirmation

**Comment by michaelcallahan27** [comment] 2022-03-30 15:18
@engcom-Hotel is the only way to have this working to wait for the next version of magento to be released and upgrade to it?

**Comment by engcom-Hotel** [comment] 2022-05-23 08:00
Hello @michaelcallahan27,

I would like to suggest you upgrade Magento with the latest stable branch.

Thanks
