### ISSUE TITLE
Backorder customer notification is not shown in Magento 2.2.0 / 2.1.9 on One page checkout

### ISSUE THREAD

**Issue by KarlComSe** [magento/magento2#11708] opened 2017-10-25 01:38 UTC
### Preconditions
Magento 2.2.0
PHP7
Multi-site setup
Magento Luma theme. 

### Steps to reproduce

0. Go into stores > configuration > invetory : Set Display out of stock products: Yes, select Manage Stock: Yes. Set Backorders; Allow Qty below 0 and notify customer. 
1. Create new simple product. 
2. Set stock status, in Stock. 
3. Set quantity below 0. In my case, this was done by customer buying a unit when it was at 0.
4. Select advanced inventory, check so that the Manage Stock is Yes, qty below 0 and for Backorders: Allow Qty Below 0 and Notify Customer. 
5. Save product. 
6. Go to storefront and add the product to cart. 
7. Select Proceed to Checkout, in the minicart.

### Expected result

1. Show message about "Backorder". 

### Actual result

1. No message is shown. 

![image](https://user-images.githubusercontent.com/13668660/31976116-cf7e6ace-b935-11e7-94f7-7b378725267c.png)

There is a notification only shown when one go to "View and Edit cart". Most customer jumps this step. 
This is also reported here, but according to guidelines, was requested to be a new topic: #5538 (https://github.com/magento/magento2/issues/5538)

**Comment by magento-engcom-team** [comment] 2017-10-25 06:32
@KarlComSe, thank you for your report.
We've created internal ticket(s) MAGETWO-82696 to track progress on the issue.

**Comment by ranjithtsims** [comment] 2018-07-10 19:19
Any update on this issue? @magento-engcom-team

**Comment by czettnersandor** [comment] 2018-07-18 11:43
It looks like the only place this notification is shown is at the cart. The problem is, you can easily skip the cart from the checkout process because the minicart is showing the checkout button in a primary colour and the visit cart as a simple link.

**Comment by magento-engcom-team** [comment] 2019-06-19 21:22
Hi @KarlComSe. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [138a3c52211c46276269484470d1beb5cd078944](https://github.com/magento/magento2/commit/138a3c52211c46276269484470d1beb5cd078944)
 - [131f98d94913f8f84483de6f6524bb1702e54794](https://github.com/magento/magento2/commit/131f98d94913f8f84483de6f6524bb1702e54794)
 - [aed152f8dbd81a5789bdaa6d79f6b71386a8eb7e](https://github.com/magento/magento2/commit/aed152f8dbd81a5789bdaa6d79f6b71386a8eb7e)

The fix will be available with the upcoming `2.3.3` release.

**Closed as completed by magento-engcom-team** 2019-06-19 21:22 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by DTaksta** [comment] 2019-07-05 10:31
Hi @magento-engcom-team when will Magento Community 2.3.3 be released, furtherest I could gather is that it will be by August 31, 2019, as that is when the GraphQL component is due, https://github.com/magento/graphql-ce/milestone/5
