### ISSUE TITLE
Typo in Pull Request Template

### ISSUE THREAD

**Issue by okorshenko** [magento/magento2#8871] opened 2017-03-13 22:17 UTC
There is a typo in Pull Request Template file.

Please, see https://github.com/magento/magento2/blob/develop/PULL_REQUEST_TEMPLATE.md
`magento/magetno2#: Issue title`

magetno2 should be changed on magento2

**Comment by tomislavsantek** [comment] 2017-03-16 14:26
Issue in progress @tomislavsantek

**Comment by magento-team** [comment] 2017-07-31 22:49
Internal ticket to track issue progress: MAGETWO-66232

**Comment by magento-engcom-team** [comment] 2017-09-20 23:07
@okorshenko, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 23:07 UTC
Labels: Issue: Ready for Work, Fixed in 2.2.x, Issue: Format is not valid
