### ISSUE TITLE
Searching "Categories" is wrong when pressing 1 character

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#23697] opened 2019-07-14 23:22 UTC
### Preconditions (*)

1. Install the 2.3-develop

### Steps to reproduce (*)

1. Add new product
2. Click "Select..." in Categories.
3. Enter the character like "l" or "j" (not match any categories)

### Expected result (*)

1. Show "0 options"

### Actual result (*)

1. Don't search , show wrong results

![image](https://user-images.githubusercontent.com/8234209/61190587-d9d81d80-a6c8-11e9-86f1-6e4271445f1c.png)

**Comment by edenduong** [comment] 2019-07-14 23:22
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-14 23:23
Hi @edenduong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-14 23:23
Hi @edenduong, here is your [Magento instance](https://i-23697-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23697-2-3-develop.instances.magento-community.engineering/admin](https://i-23697-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by edenduong** [comment] 2019-07-14 23:40
I can reproduce the issue on vanilla Magento instance

**Comment by krishprakash** [comment] 2019-07-15 04:45
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-15 04:45
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-15 04:46
Hi @krishprakash, here is your [Magento instance](https://i-23697-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23697-2-3-develop.instances.magento-community.engineering/admin](https://i-23697-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2019-07-15 05:16
Hi @edenduong. This is not an issue.
Search filter is based on two characters once you add 2 characters it will display proper result.
PFA
1. Display result:
![image](https://user-images.githubusercontent.com/46617848/61196640-af4c8b80-a6ed-11e9-9e1a-01f3f61effb0.png)

2. Display 0 Result:
![image](https://user-images.githubusercontent.com/46617848/61196689-fd618f00-a6ed-11e9-91f2-d4e56fb0aef4.png)

**Comment by edenduong** [comment] 2019-07-15 05:26
Hello @krishprakash, thank you for your reply. Why the search works for 2 character and doesn’t work for 1 character? I think it is very wrong. I want to filter only the categories has the first character like ‘s’ ‘Shirt, Shoe’ but it shows all categories include like ‘Hat, Men’. 
Actually, I find the problem happens not only in the categories, it will happen in all the components use ui select app/code/Magento/Ui/view/base/web/js/form/element/ui-select.js

**Comment by DanielRuf** [comment] 2019-07-15 05:30
> Hi @edenduong. This is not an issue.
Search filter is based on two characters once you add 2 characters it will display proper result.


Probably because of performance issues. Doing a search for only one character over all entries is slower than doing a search with a minimum of two characters.

Same applies to the product search.

**Comment by edenduong** [comment] 2019-07-15 05:34
> > Hi @edenduong. This is not an issue.
> > Search filter is based on two characters once you add 2 characters it will display proper result.
> 
> Probably because of performance issues. Doing a search for only one character over all entries is slower than doing a search with a minimum of two characters.
> 
> Same applies to the product search.

@DanielRuf thank you. But at least the system should show the notification or some thing like that ? How can we know we should search 2,3 or 4 to run the search ?

**Comment by edenduong** [comment] 2019-07-15 05:57
![image](https://user-images.githubusercontent.com/8234209/61197548-bf6d6680-a6ff-11e9-959e-144d2bf33540.png)

We can create the category with one character like this image, but we can't search it. It is the issue if limit the search is 2 character.

**Comment by magento-engcom-team** [comment] 2019-07-15 08:35
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18162` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-08-15 22:20
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#23698 by @edenduong in 2.3-develop branch
Related commit(s):
 - [aa26e07383e39e98c4eeccc35bcb17fa47fcbf2d](https://github.com/magento/magento2/commit/aa26e07383e39e98c4eeccc35bcb17fa47fcbf2d)

The fix will be available with the upcoming 2.3.4 release.

**Closed as completed by magento-engcom-team** 2019-08-15 22:20 UTC
Labels: Issue: Ready for Work, Component: Catalog, Component: Search, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Admin
