### ISSUE TITLE
Magento 2: Module "mage/utils/arrays" has not been loaded yet for context

### ISSUE THREAD

**Issue by bonsdawende** [magento/magento2#5839] opened 2016-07-27 13:26 UTC
I have installed a Magento 2.0.7 website. The issue is some admin pages are not loading correctly. For example, catalog management page cannot load products list, user management page cannot load user list. Other admin pages work OK. I get this error message :

Error: Module name "mage/utils/arrays" has not been loaded yet for context: _
http://requirejs.org/docs/errors.html#notloaded
var e = new Error(msg + '\nhttp://requirejs.org/docs/errors.html#' + id);
require.js (ligne 166, col. 17)

Anyone has already encountered this kind of error ? Please can you help me ? Thanks

**Comment by bonsdawende** [comment] 2016-07-29 06:38
I guessed that I got this message when I used Nginx. But it's works when I used Apache.  Anyone has already encountered this kind of error with Nginx ?

**Comment by giusecapo** [comment] 2017-03-28 11:47
I'm having this problem too, how did you fix it?

**Comment by magento-engcom-team** [comment] 2017-10-24 08:30
@bonsdawende, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment] 2017-10-24 12:46
@bonsdawende, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by VitaliyBoyko** [comment] 2023-04-17 12:22
This issue is still reproducible on Magento 2.4.6 and Advanced JS Bundling.

require.js:1 Uncaught Error: Module name "mage/utils/arrays" has not been loaded yet for context: _
https://requirejs.org/docs/errors.html#notloaded
    at makeError (require.js:1:1767)
    at s (require.js:1:14777)
    at main.js:1:213
    at Object.execCb (require.js:1:16571)
    at e.check (require.js:1:10384)
    at e.enable (require.js:1:13095)
    at e.init (require.js:1:9491)
    at a (require.js:1:8208)
    at Object.completeLoad (require.js:1:15812)
    at HTMLScriptElement.onScriptLoad (require.js:1:16721)

**Comment by engcom-November** [comment] 2023-04-20 05:10
Hi @VitaliyBoyko ,
Verified the issue on both Magento 2.4-develop instance and 2.4.6 version as well but the issue is not reproducible with below steps performed:
1. Configured Javascript bundling as per [devdocs](https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/js-bundling.html)
2. Frontend - Inspect element - Verified console  - no error observed
3. Verified all admin - Category, product pages - No issue. All pages loading as expected.
Kindly recheck the issue on Magento 2.4-develop instance as it is having latest code base and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by VitaliyBoyko** [comment] 2023-04-20 09:24
@engcom-November 

Not just JS bundling but **Advanced JS bundling**

https://devdocs.magento.com/guides/v2.3/performance-best-practices/advanced-js-bundling.html#advanced-bundling

Using r.js and so on.

**Comment by VitaliyBoyko** [comment] 2023-04-20 09:37
@engcom-November 

:warning: 

Make sure the regular bundler is disabled because those two do not work together.

`php -f bin/magento config:set dev/js/enable_js_bundling 0`

**Comment by engcom-Hotel** [comment] 2024-01-12 12:34
Hello @bonsdawende,

Please try to reproduce the issue in the latest development branch i.e. 2.4-develop and let us know if you are still facing the same issue.

Thanks

**Comment by engcom-Hotel** [comment] 2024-02-05 12:55
Dear @bonsdawende,

We have noticed that this issue has not been updated for a period of long time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2024-02-05 12:55 UTC
Labels: bug report, Area: Frontend, Triage: Dev.Experience, Issue: needs update

**Comment by bmwael** [comment] 2024-12-20 21:05
I had the same issue, 
I have a script that minified all my JS files, I disabled the JS minification and this solved the issue
