### ISSUE TITLE
Possible regression: Default sort by error prevents category update via REST if set to non-config value. [2.4.x]

### ISSUE THREAD

**Issue by infinityredux** [magento/magento2#33535] opened 2021-07-20 10:40 UTC
### Preconditions (*)

1. 2.4.2-p1
2. Presumably other earlier 2.4.x versions too, see below.

### Steps to reproduce (*)

1. Admin - Catalog - Categories - Add Root Category - Create new Category by deselecting/unchecking "Use Config Settings" for "Default Product Listing Sort By" field and Save
2. Make a GET request to /rest/all/V1/categories/12 (here my newly created test category id is 12)
3. Make a PUT Request to /rest/all/V1/categories/12 by slightly modifying the below ex: payload format  (Or simply reformat your Get Response/output payload in PUT Request payload)
(PUT request to `​/V1​/categories​/{id}` or POST request to `V1/categories` to update this category)

### Expected result (*)

1. Category gets updated, based on the REST API call.

### Actual result (*)

1. Error message:
```
{
  "message": "Error occurred during \"custom_attributes\" processing. Attribute \"default_sort_by\" has invalid value. The \"string\" value's type is invalid. The \"string[]\" type was expected. Verify and try again."
}
```
![image](https://user-images.githubusercontent.com/60198231/127614236-cd1acceb-dbb5-4c95-b3e9-161ee1bc56fe.png)

**PUT Request Payload Example:**
```
{
  "category": {
    "id": 12,
    "parent_id": 1,
    "name": "enabled config",
    "is_active": true,
    "position": 6,
    "level": 1,
    "children": "",
    "created_at": "2021-07-30 06:33:02",
    "updated_at": "2021-07-30 06:34:56",
    "path": "1/12",
    "available_sort_by": [],
    "include_in_menu": true,
    "custom_attributes": [
        {
            "attribute_code": "display_mode",
            "value": "PRODUCTS_AND_PAGE"
        },
        {
            "attribute_code": "is_anchor",
            "value": "1"
        },
        {
            "attribute_code": "path",
            "value": "1/12"
        },
        {
            "attribute_code": "children_count",
            "value": "0"
        },
        {
            "attribute_code": "default_sort_by",
            "value": "position"
        },
        {
            "attribute_code": "custom_use_parent_settings",
            "value": "0"
        },
        {
            "attribute_code": "custom_apply_to_products",
            "value": "0"
        },
        {
            "attribute_code": "url_key",
            "value": "enabled-config"
        }
    ]
  }
}
```
**Note:** This issue is not reproducible for Category having same payload format when "Use Config Settings" is selected/enabled for " Default Product Listing Sort By" field from Admin.

![image](https://user-images.githubusercontent.com/60198231/127614088-fe52d80b-6dcf-4d82-a7df-c56c94b4ff75.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

---
This may have been fixed on 2.3.6 of Magento, per the patch notes:
* https://devdocs.magento.com/guides/v2.3/release-notes/commerce-2-3-6.html#web-api-framework
* https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-2.html#web-api-framework

Both sets of patch notes have the note that we can now use POST requests to create / update categories without encountering this error message. However, 2.3.6 has an additional patch note stating that `default_sort_by` type was changed from `string[]` to `string`, which would (theoretically) resolve this issue.

**Comment by engcom-November** [comment] 2021-07-20 13:04
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible:

**Steps performed:**
1. Admin - Catalog - Categories - Add Root Category - Created new Category by deselecting "Use Config Settings" for "Default Product Listing Sort By" field
2. Made a put request to /rest/all/V1/categories/4 to update the category - **No Issue:  Category is updated.**
![image](https://user-images.githubusercontent.com/60198231/126328472-fc0958c6-21c6-4c52-8dfb-f8f182f2c170.png)

![image](https://user-images.githubusercontent.com/60198231/126328445-9a29ac21-8111-48d4-a96f-9a800a6234c2.png)
@infinityredux Kindly recheck the issue on latest Magento 2.4-develop branch and provide the missing steps if the issue is still reproducible.
Thank you.

**Comment by infinityredux** [comment] 2021-07-20 13:55
@magento give me 2.4-develop instance

**Comment by infinityredux** [comment] 2021-07-20 14:47
Ok, new sequence:

1. Created new Magento instance using bot on the develop branch.
2. Created new test category, with "Use Config Settings" for "Default Product Listing Sort By" disabled before saving
   - New category ID was 41, given the presence of test data in the instance.
3. Make a request to the admin token endpoint `/rest/all/V1/integration/admin/token` to get token.
4. Make GET request to `/rest/all/V1/categories/41` with the result below.
5. Made a POST request `/rest/all/V1/categories/41` using the slightly modified payload, as per below.
    - Note that children is still present, appears this does not error if empty.
6. Received error message


Only reason I can think of that the attempt to reproduce might not have worked, was if the category wasn't saved after the box was unticked? With hindsight I realise that wasn't explicit, but I thought it was implied?

Can provide screen shots or more details on the steps above if that would be helpful.

-----

**GET result:**
```
{
    "id": 41,
    "parent_id": 2,
    "name": "Test",
    "is_active": true,
    "position": 7,
    "level": 2,
    "children": "",
    "created_at": "2021-07-20 14:01:13",
    "updated_at": "2021-07-20 14:01:13",
    "path": "1/2/41",
    "available_sort_by": [],
    "include_in_menu": true,
    "custom_attributes": [
        {
            "attribute_code": "display_mode",
            "value": "PRODUCTS"
        },
        {
            "attribute_code": "is_anchor",
            "value": "1"
        },
        {
            "attribute_code": "path",
            "value": "1/2/41"
        },
        {
            "attribute_code": "children_count",
            "value": "0"
        },
        {
            "attribute_code": "default_sort_by",
            "value": "position"
        },
        {
            "attribute_code": "custom_use_parent_settings",
            "value": "0"
        },
        {
            "attribute_code": "custom_apply_to_products",
            "value": "0"
        },
        {
            "attribute_code": "url_key",
            "value": "test"
        },
        {
            "attribute_code": "url_path",
            "value": "test"
        }
    ]
}
```

**Corresponding POST payload:**
```
{ 
    "category" :{
        "id": 41,
        "parent_id": 2,
        "name": "Test",
        "is_active": true,
        "position": 7,
        "level": 2,
        "children": "",
        "created_at": "2021-07-20 14:01:13",
        "updated_at": "2021-07-20 14:01:13",
        "path": "1/2/41",
        "available_sort_by": [],
        "include_in_menu": true,
        "custom_attributes": [
            {
                "attribute_code": "display_mode",
                "value": "PRODUCTS"
            },
            {
                "attribute_code": "is_anchor",
                "value": "1"
            },
            {
                "attribute_code": "path",
                "value": "1/2/41"
            },
            {
                "attribute_code": "children_count",
                "value": "0"
            },
            {
                "attribute_code": "default_sort_by",
                "value": "position"
            },
            {
                "attribute_code": "custom_use_parent_settings",
                "value": "0"
            },
            {
                "attribute_code": "custom_apply_to_products",
                "value": "0"
            },
            {
                "attribute_code": "url_key",
                "value": "test"
            },
            {
                "attribute_code": "url_path",
                "value": "test"
            }
        ]
    }
}
```

**Response received:**
```
{
    "message": "Error occurred during \"custom_attributes\" processing. Attribute \"default_sort_by\" has invalid value. The \"string\" value's type is invalid. The \"string[]\" type was expected. Verify and try again."
}
```

**Comment by infinityredux** [comment] 2021-07-21 17:47
As an additional note, I would add there appears to be one distinct difference between the 2.3.6 and 2.4.2 versions, which may be relevant.

With "Use Config Settings" unchecked, an update payload where the `default_sort_by` custom attribute has been removed, will be accepted on 2.3.6 (as long the current value is in the specified `available_sort_by`) and the returned response includes the current `default_sort_by` value. 

Attempting a similar request in 2.4.2 will result in the same error as above.

**Comment by engcom-November** [comment] 2021-07-30 06:53
Verified the issue again on Magento 2.4-develop branch using below Payload and the issue is reproducible:
**Steps to Reproduce:**
1. Admin - Catalog - Categories - Add Root Category - Create new Category by deselecting "Use Config Settings" for "Default Product Listing Sort By" field and Save
2. Make a request to the admin token endpoint /rest/all/V1/integration/admin/token to get token.
3. Make a GET request to /rest/all/V1/categories/12  (here my newly created test category id is 12)
4. Make a PUT Request  to /rest/all/V1/categories/12 by slightly modifying the below payload
**Error:**  400 Bad request
```
{
    "message": "Error occurred during \"custom_attributes\" processing. Attribute \"default_sort_by\" has invalid value. The \"string\" value's type is invalid. The \"string[]\" type was expected. Verify and try again."
}
```
**PUT Request Payload Example:**
```
{
  "category": {
    "id": 12,
    "parent_id": 1,
    "name": "enabled config",
    "is_active": true,
    "position": 6,
    "level": 1,
    "children": "",
    "created_at": "2021-07-30 06:33:02",
    "updated_at": "2021-07-30 06:34:56",
    "path": "1/12",
    "available_sort_by": [],
    "include_in_menu": true,
    "custom_attributes": [
        {
            "attribute_code": "display_mode",
            "value": "PRODUCTS_AND_PAGE"
        },
        {
            "attribute_code": "is_anchor",
            "value": "1"
        },
        {
            "attribute_code": "path",
            "value": "1/12"
        },
        {
            "attribute_code": "children_count",
            "value": "0"
        },
        {
            "attribute_code": "default_sort_by",
            "value": "position"
        },
        {
            "attribute_code": "custom_use_parent_settings",
            "value": "0"
        },
        {
            "attribute_code": "custom_apply_to_products",
            "value": "0"
        },
        {
            "attribute_code": "url_key",
            "value": "enabled-config"
        }
    ]
  }
}
```
![image](https://user-images.githubusercontent.com/60198231/127612656-2237b170-a3d4-4996-88f4-166aed9e60f3.png)
![image](https://user-images.githubusercontent.com/60198231/127612697-c57914cf-1c0b-42c6-93f4-cc5890d4510b.png)

**Note: T**his issue is not reproducible for Category having same payload format when "Use Config Settings" is selected/enabled for " Default Product Listing Sort By" field for category.
**Expected behavior:**
![image](https://user-images.githubusercontent.com/60198231/127613102-39ee5df8-0db8-4ae3-8803-878a6b755d05.png)

**Comment by magento-engcom-team** [comment] 2021-07-30 07:06
:white_check_mark: Confirmed by @engcom-November 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42945` were created

**Issue Available**: @engcom-November, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Delta** [comment] 2024-11-19 12:17
Hi @infinityredux ,

Thanks for your reporting and collaboration.
We have re-verified the issue in Latest 2.4-develop instance , but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce**
1. Admin - Catalog - Categories - Add Root Category - Create new Category by deselecting/unchecking "Use Config Settings" for "Default Product Listing Sort By" field and Save
![image](https://github.com/user-attachments/assets/ea6188f1-bec5-491c-a3f4-ab6525e14858)

2. Make a GET request to /rest/all/V1/categories/12 (here my newly created test category id is 7)
![image](https://github.com/user-attachments/assets/f6e4a89a-df47-46d3-bff1-96ea621cf225)
3. Make a PUT Request to /rest/all/V1/categories/12 by slightly modifying the below ex: payload format (Or simply reformat your Get Response/output payload in PUT Request payload)
(PUT request to ​/V1​/categories​/{id} or POST request to V1/categories to update this category)
![image](https://github.com/user-attachments/assets/a187b110-a572-4d40-a3de-627d1a8b74e8)

Can you please re-verify and confirm if you are still facing the issue.
Thanks.

**Comment by engcom-Delta** [comment] 2024-12-19 12:09
Hi @infinityredux ,

This issue is being closed since it has not been updated in a long time.
Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.

**Closed as completed by engcom-Delta** 2024-12-19 12:09 UTC
Labels: Component: Api, Reproduced on 2.4.x, Priority: P2, Progress: done, Issue: needs update, Reported on 2.4.2-p1, Area: APIs
