### ISSUE TITLE
Magento Performance Toolkit Customer Checkout Error

### ISSUE THREAD

**Issue by logan-robbins** [magento/magento2#3513] opened 2016-02-23 16:23 UTC
Steps: 

1) Magento CE v2.0.2, PHP 7.0.3 

2) php bin/magento setup:perf:generate-fixtures /var/www/magento/html/setup/performance-toolkit/profiles/ce/large.xml

3) enable flat catalog / category, reindex

4) deploy static content, run multi-tenant compiler

5) separate jmeter server (or local computer gui) ./jmeter -n -t benchmark.jmx -Jhost={url/ip} -Jbase_path=/ -Jusers=100 -Jramp_period=360 -Jreport_save_path=./ -Jloops=1

I'm expecting 8 orders, (4% customer, 4% guest). Seems like 1 out of 4 customer orders go through. Errors are reported in the CLI output and in the GUI, but no errors in logs. The HTTP response codes on the error'd actions are 200.

Errors start on the Login(CustomerChkt) action.
    - Add to cart / browsing is fine.
Next error on the Checkout start(CustomerChkt) action.
Next error on the Checkout Billing/Shipping Information(CustomerChkt) action:
    - {"message":"Consumer is not authorized to access %resources","parameters":{"resources":"self"}}
Same error on Checkout Payment Info/Place Order(CustomerChkt)
Checkout Success(CustomerChkt) action shows the cart page.

Is this a permissions issue that the MPT is having trouble traversing different accounts?

**Comment by ishakhsuvarov** [comment] 2016-03-10 08:37
@ljrweb Thank you for reporting this issue, we have created an internal ticket `MAGETWO-50290` to investigate the scenario with the parameters you provided.

Problems of this kind usually happen when fixture generator fails and generates insufficient fixtures, please check that profile generation was successful and you have enough registered customers for every thread started, otherwise scenario will attempt to perform checkout with the same customer multiple times, causing permission issue.

**Comment by veloraven** [comment] 2016-08-30 06:09
@ljrweb is this issue still actual?
We were not able to reproduce it and internal ticket was closed.
I'm going to close this ticket as well.

**Comment by veloraven** [comment] 2016-09-14 07:01
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Closed as completed by veloraven** 2016-09-14 07:01 UTC
Labels: Issue: Ready for Work, Progress: needs update
