### ISSUE TITLE
Vertex Tax Error Updating to 2.3.3

### ISSUE THREAD

**Issue by CalzaFino** [magento/magento2#24970] opened 2019-10-11 06:37 UTC
I am trying to update Magento 2.3.2 to 2.3.3 and I got an error on the fist step of the compilation (1/7):

Error Fatal error: Interface 'Vertex\Tax\Model\Flexfield\Processor\TaxCalculationFlexFieldProcessorInterface' not found in /srv/public_html/vendor/vertex/module-tax/Model/FlexField/Processor/OrderCurrencyGetterProcessor.php on line 24

Compilation is not completed.

The Vertes_Tax module is disblad (It was disabled since the first time it was included in the core).

The new ver. 2.3.3 is displayed at the Admin Pannel

Front store is running very slowly.

**Comment by sudheers-kensium** [comment] 2019-10-11 07:15
@CalzaFino! Not reproducible, I have upgraded from Magento 2.3.2 to 2.3.3 without issue. So I am closing this issue.

**Closed as completed by sudheers-kensium** 2019-10-11 07:15 UTC
Labels: Issue: Format is not valid

**Comment by navarr** [comment] 2019-10-11 20:32
Duplicate of #24930.  Please see duplicated issue for patch.
