### ISSUE TITLE
catalog_url_rewrite_product_category table missing PK

### ISSUE THREAD

**Issue by siliconalchemy** [magento/magento2#9581] opened 2017-05-10 14:20 UTC
The catalog_url_rewrite_product_category table is missing a PK.  Because of this, it cannot be replicated reliably in Galera based systems (eg. MariaDB, Percona XtradbCluster).  It appears to be the only table without a PK.  This is more of a problem with PXC 5.7 as it recommends enforcing strict mode which will actively break usage of this table.

Magento 2.1.5
Mysql: Percona XtraDBCluster 5.7

### Preconditions
Magento 2.4-develop

### Steps to reproduce
1. Open database table `catalog_url_rewrite_product_category`
2. Check if the table has a Primary Key

### Expected result
The database table `catalog_url_rewrite_product_category` has Primary Key

### Actual result
The database table `catalog_url_rewrite_product_category` doesn't have Primary Key
![primary_key](https://user-images.githubusercontent.com/51680745/103774172-d19a3d80-5034-11eb-8fc5-dbf4cc5372fb.png)

**Comment by veloraven** [comment] 2017-06-22 12:55
@siliconalchemy please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by siliconalchemy** [comment] 2017-06-22 16:20
Did you read this?  How much more specific do you want it to be?  Never mind, you can leave your (buggy) project buggy (ier).

**Comment by korostii** [comment] 2017-06-23 12:00
Hi @veloraven, @magento-team,
The description seems quite extensive. Could you maybe pass this along to someone having some technical expertise in this field?

**Comment by ihor-sviziev** [comment] 2020-02-17 13:44
@engcom-Golf @engcom-Alfa could you double check if this issue still valid, as we're having bugfix in #25746, so I'm not sure if it's valid

**Comment by siliconalchemy** [comment] 2021-01-05 15:31
Go away stalebot, this is still a valid issue.

**Comment by engcom-Bravo** [comment] 2021-01-06 13:37
Hello @siliconalchemy 

Thank you for your report.

We Confirm that the issue is still valid on 2.4-develop, and we have added Precondition, Steps to reproduce, ER and AR to the description.

**Comment by magento-engcom-team** [comment] 2021-01-06 13:39
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40317` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by zakdma** [comment] 2021-03-16 14:26
This bug was fixed in scope of internal issue B2B-1663
https://github.com/magento/magento2/commit/ece2528a6f09da1486d63ddd794f746501984413

**Comment by zakdma** [comment] 2021-03-16 14:27
@siliconalchemy it fixed

**Closed as completed** 2021-03-16 14:26 UTC
Labels: Component: CatalogUrlRewrite, Issue: Confirmed, Component: DB, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P2, Severity: S2, Progress: done, Issue: ready for confirmation, Reported on 2.1.x

**Comment by magento-engcom-team** [comment] 2021-03-16 14:29
Hi @siliconalchemy. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-40317` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by ihor-sviziev** [comment] 2021-08-13 10:54
@zakdma @joanhe, please check the https://github.com/magento/magento2/issues/33770 that was caused by the fix https://github.com/magento/magento2/commit/ece2528a6f09da1486d63ddd794f746501984413, maybe you could provide some workaround?
