### ISSUE TITLE
[2.3.5-p2] Cart Rule > Action Conditions > SKU|Category Grid Selector Not Working (Error Message In Browser Console)

### ISSUE THREAD

**Issue by victortodoran** [magento/magento2#29230] opened 2020-07-21 18:37 UTC
### Preconditions (*)

1. Reproduced on Magento **2.4-develop** - **No**;
2. Reproduced on Magento **2.3.5-p2** - **Yes**;
3. Reproduced on Magento **2.4.0** - **No**;

### Steps to reproduce (*)

1.Fresh Magento Install
2. Create New Cart Rule
3. Add Rule Name, Description, Customer Groups etc.
4. Go To Actions > Apply the rule only to cart items matching the following conditions (leave blank for all items).
5. From Dropdown select Category or SKU
6. Click the three dots
7. Click the blue icon
8. Select some items from the grid that appears 
9. Click the green check mark

### Expected result (*)

1. The input is populated with the ids of either categories/products selected

### Actual result (*)

1. Condition returns to initial state.
2. Console errors
![image](https://user-images.githubusercontent.com/25669334/88093259-6ea60e80-cb9a-11ea-9246-5ba7d3926c4b.png)
![image](https://user-images.githubusercontent.com/25669334/88093136-41f1f700-cb9a-11ea-9eb8-b4c6b2ab8b3d.png)
3. Selected options are not added to conditions

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment] 2020-07-22 05:12
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-07-22 05:12
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-07-22 05:13
Hi @ajijshekh123, here is your [Magento instance](https://i-29230-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29230-2-4-develop.instances.magento-community.engineering/admin_6cfb](https://i-29230-2-4-develop.instances.magento-community.engineering/admin_6cfb)
Login: `5796b90c` Password: `b1f9f9f8886b`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2020-07-22 05:34
@magento give me 2.3.5-p1-develop instance

**Comment by magento-engcom-team** [comment] 2020-07-22 05:35
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3.5-p1-develop instance for you

**Comment by ajijshekh123** [comment] 2020-07-22 05:46
Hi @victortodoran,
I have verified this issue in the latest Magento 2.4 instance. Add cart rule functionality is working fine and not able to get the any of console error.
PFA:

![1](https://user-images.githubusercontent.com/24711761/88139043-8ddd8400-cc0c-11ea-9022-4ba2717522ba.PNG)

![2](https://user-images.githubusercontent.com/24711761/88139071-9930af80-cc0c-11ea-9870-196b0117c933.PNG)

Please upgrade your Magento 2.4 instance then verify this issue. If this issue found in the latest Magento 2.4 Instance. Please update your comment here.

Thanks.

**Comment by victortodoran** [comment] 2020-07-22 06:13
@ajijshekh123  This indeed is not reproducing in 2.4-develop. Is this the branch that is going to be released in 28th of July?

**Comment by ajijshekh123** [comment] 2020-07-22 06:38
@victortodoran - Actually, Magento didn't provide me the Magento 2.3.5-p1 Instance that's why I can't able to verify this issue.
Can I close this issue? OR Please provide me Magento 2.3.5-p1 admin link and credential.

**Comment by victortodoran** [comment] 2020-07-22 07:02
@magento give me 2.3.5-p1

**Comment by victortodoran** [comment] 2020-07-22 07:02
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment] 2020-07-22 07:02
Hi @victortodoran. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment] 2020-07-22 07:04
Hi @victortodoran, here is your [Magento instance](https://i-29230-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-29230-2-3-5-p1.instances.magento-community.engineering/admin_3e81](https://i-29230-2-3-5-p1.instances.magento-community.engineering/admin_3e81)
Login: `b8ed9667` Password: `c24cc32179b8`
Instance will be terminated in up to 3 hours.

**Comment by victortodoran** [comment] 2020-07-22 07:11
@ajijshekh123 There is no 2.3.5.p1-develop branch. You have to ask for 2.3.5-p1. Or you can use the instance above if you get to it in time.
![image](https://user-images.githubusercontent.com/25669334/88145721-8b2a6100-cc03-11ea-94b0-de07dd9b17c4.png)

**Comment by ajijshekh123** [comment] 2020-07-22 07:25
Hi @victortodoran,
This issue is reproduced on Magento 2.3.5.p1 Instance.
PFA:
![2 3 5_Error1](https://user-images.githubusercontent.com/24711761/88147203-87ee9f80-cc1a-11ea-9187-5eea4b7cd5b1.PNG)

Thanks.

**Comment by magento-engcom-team** [comment] 2020-07-22 07:26
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36074` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2020-08-18 11:24
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36816` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment] 2024-05-27 06:26
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-05-27 07:11
Hi @victortodoran,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshot.


<img width="1421" alt="Screenshot 2024-05-27 at 12 38 40" src="https://github.com/magento/magento2/assets/51680745/e50588d7-0b36-4ec7-b72b-a87d31f40540">



The input is populated with the ids of either categories/products selected


Hence We are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-05-27 07:11 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Rule, Component: Admin, Priority: P2, Reproduced on 2.3.5p2, Progress: done, Reported on 2.3.5-p2, Area: Admin UI
