### ISSUE TITLE
Magento 2.1.0-rc3 no minicart qty indicator

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#6293] opened 2016-08-23 14:10 UTC
### Preconditions

1.  Magento 2.1.0-rc3 installed via Composer (update from 2.0.9)
2. PHP7
3. Use a custom theme that inherits Magento Luma
### Steps to reproduce

1. Put something in the cart
2. check the minicart 
### Expected result

1. Indicator shows with a "N" when N products are in the cart
### Actual result

1. No indicator is shown, nothing is in the minicart

![bildschirmfoto 2016-08-23 um 16 13 40](https://cloud.githubusercontent.com/assets/13021579/17895060/1d7722ba-694c-11e6-9083-42cbc800c169.png)

**Comment by grasdaggel** [comment] 2016-08-25 07:02
Any updates on this?

**Comment by odubovyk** [comment] 2016-08-26 08:10
The same issue as here #5377

**Comment by developer-lindner** [comment] 2016-08-31 12:30
@grasdaggel Update to 2.1.1. and report back or close ticket otherwise.

**Comment by grasdaggel** [comment] 2016-08-31 14:32
Still not working. No Indicator, or added items are shown in Minicart active part. 

Upgraded to 2.1.1

**Comment by antboiko** [comment] 2016-08-31 14:59
Hi @grasdaggel , thanks for reporting this issue. Internal ticket MAGETWO-57884 was created.

Best,
Anton.

**Comment by veloraven** [comment] 2017-06-19 13:24
I'm closing this issue as duplicate of #5377 as there are more discussions in that issue.

**Closed as completed by veloraven** 2017-06-19 13:24 UTC
Labels: Issue: Ready for Work, bug report, Component: Checkout
