### ISSUE TITLE
CVV Verificaion Failed

### ISSUE THREAD

**Issue by VZeroCool** [magento/magento2#34752] opened 2021-12-02 16:07 UTC
### Preconditions (*)

1. Magento 2.4.2
2. Webserver Doesn't matter
3. In Braintree make sure to enable card verification and Under Fraud Management > AVS select all Rules 
### Steps to reproduce (*)

1. Admin - Stores - Configuration - Sales - Payment Methods - Configure Braintree for US Merchant, Payment Action Instant Sale
2. Enable Vault and re-verification for CVV
3. Front-end - Place first order with brand new card and save it 
4. Re-order previous one or create new order using previously saved card - Enter CVV and submit order

### Expected result (*)

1. Order should place sucessfully with saved card

### Actual result (*)

1. Error on Payment step, CVV Verification failed

**Comment by VZeroCool** [comment] 2021-12-03 05:29
@magento give me 2.4-develop instance

**Comment by VZeroCool** [comment] 2021-12-05 13:32
@magento give me 2.4-develop instance

**Comment by VZeroCool** [comment] 2021-12-05 13:43
Can't find baintree in admin, Cant reproduce in this instance.

![image](https://user-images.githubusercontent.com/36662131/144749002-24579860-a195-479d-9a18-4f6e590089f2.png)

**Comment by engcom-November** [comment] 2021-12-07 14:02
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
**Steps performed:**
Installed Braintree payment module on 2.4-develop branch
Admin - Stores - Configuration - Sales - Payment Methods - Configure Braintree for US Merchant, Payment Action Instant Sale
Enable Vault and re-verification for CVV
Save and clear Cache
Front-end - Login - Add product to Cart - Checkout
Select Braintree payment method and enter credit card details, save card details and place Order - No issue
Reorder / Place new Order with Saved Card details - Issue: Unable to place Order. "CVV Verification failed" error message is getting displayed.
![image](https://user-images.githubusercontent.com/60198231/145042973-be58da43-f30a-4d04-a54b-e73df552fba7.png)

**Comment by engcom-November** [comment] 2021-12-21 07:31
Hi @VZeroCool ,
Can you please confirm the Brain-tree payment Mode (Sandbox or Production) that you have used while reproducing this issue.
Thank you.

**Comment by VZeroCool** [comment] 2021-12-27 18:31
@engcom-November - It doesn't matter as long you have enabled AVS rules as I mentione above.

**Comment by VZeroCool** [comment] 2022-01-06 14:05
Any update on this ?

**Comment by engcom-November** [comment] 2022-01-12 14:32
Hi @VZeroCool ,
Kindly confirm the Brain-tree Mode used - Sandbox or Production because AVS(Address Verification System) Rules are not being checked in the first transaction with Sandbox Credentials. But for the saved cards, Reporter is forcing the extension to re-verify the AVS/CVV Rules by enabling given below setting as Yes which will always be failed with Test cards. 
![image](https://user-images.githubusercontent.com/60198231/149159109-9313bbe2-e9db-4183-925a-6a1e9fe20e78.png)

Thank you

**Comment by VZeroCool** [comment] 2022-01-17 16:19
@engcom-November, I tested it with both Sandbox and Production mode and I'm able to reproduce issue. 
Regarding Re-Verification we have enabled it. 
So You're saying that it will work in live CC with Production mode?

**Comment by engcom-Hotel** [comment] 2022-02-01 08:26
Hello @VZeroCool,

It looks specific to sandbox only as when you set 'Enable Vault CVV Re-verification' as Yes in the sandbox mode it will try to verify the CVV and it is obvious that it will not be verified as we are not using any valid CVV or card details.

We had a discussion with Braintree developers regarding this issue and received the same input. Please try it with live CC details with production mode and let us know if you still facing this issue.

I am attaching the screenshot of the chat with Braintree developers for reference:

![image](https://user-images.githubusercontent.com/51681618/151934842-b94a4baa-84ff-49db-b2d5-a1d9c71d7c8f.png)

We are closing this issue for now. If you still facing the issue in production mode with live CC details then either reopen this ticket or create a new ticket related to it.

Thanks

**Closed as completed by engcom-Hotel** 2022-02-01 08:26 UTC
Labels: Issue: Confirmed, Component: Braintree, Reproduced on 2.4.x, Priority: P1, Progress: done, Reported on 2.4.2, Area: Payments

**Comment by ahsan-horani-folio** [comment] 2023-06-21 09:11
@VZeroCool were able to resolve this issue?

**Comment by ahsan-horani-folio** [comment] 2023-06-21 09:13
I am facing exactly the same problem with Gene BrainTree extension. Gettot error "CVV Failed" for stored credit cards. Can you help me out here too @VZeroCool ?
