### ISSUE TITLE
Strange Behavior with Orders

### ISSUE THREAD

**Issue by jstubbs303** [magento/magento2#24632] opened 2019-09-18 03:27 UTC
**Issue Summary**

Ok, so having a strange issue with Magento version 2.2.9. Seems like once a week usually around the weekend we are seeing an instance where a single order turns up missing in our admin area. The customer was successfully charged using our payment gateway (NMI) but the order never makes it into Magento. This has been going on since around July 19th, 2019. No changes have been made to the site or our dedicated server.

Now, this issue doesn't happen consistently though, it may go a week where everything runs great with no orders coming up missing in the backend and then bam following week back to one or maybe two orders getting processed at the gateway level, but not appearing in the Magento backend.

The most recent incidents occurred on Sept. 13th and again on the 15th one order each day went missing in Magento admin. The order that got placed on the 15th the customer received an order confirmation email yet the SMTP that logs emails going out doesn't show this order confirmation email ever being sent and the order doesn't appear in the admin. I also have checked our database sales_order table and the missing orders don't appear there either.

I'm not sure if this issue is being caused by the payment gateway not sending back a response and/or timing out and the order gets created then is automatically canceled when no response has been received by Magento. The Magento error logs show no errors related to this problem, our server logs show no errors and the gateway claims they have no errors either.

The only error we have ever seen reported was by a customer during checkout and their order also was missing in the backend of Magento. It had the following error message in the screenshot they sent to us which said "**_Error in transaction data or system error_**".

This is not a simple issue to track down and I'm not a 100% sure this is a Magento issue because if it were Magento then I would think it would be happening much more frequently since our store has a lot of checkouts taking place each day. For example, we might have 400 customers that checkout successfully and customer 401's order gets placed and charged via the gateway, but the order never makes it into Magento.

Any help trying to figure this one out would be appreciated.

**Information on our environment**

We run our store on a fully dedicated server with 32GB memory
Apache/2.4.41
PHP v7.1
No varnish cache
No mem cache
No CDN connected

**Steps to reproduce**

We also run a dev version of our live site (exact clone) and we cannot reproduce this problem so I couldn't include the steps to reproduce as they are unknown at this time and the problem doesn't seem to have a consistent pattern.

**Comment by drpayyne** [comment] 2019-11-15 06:55
Hi @jstubbs303, thanks for your report. Although I feel this is more suitable in our [Slack channels](https://github.com/magento/magento2/wiki/Slack-Channels) or maybe even in [Magento Community](https://community.magento.com) as I'm not able to reproduce this on a vanilla instance and this needs to be debugged contextual to your instance.

Closing this due to the above reason. Please feel free to reopen in case of any query. Thanks!

**Closed as completed by drpayyne** 2019-11-15 06:55 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is not valid

**Comment by tprocter-ldg** [comment] 2019-11-27 15:26
Hi @jstubbs303 

Did you get anywhere with this issue? We have also been experiencing this, we're on 2.2.8.

**Comment by jstubbs303** [comment] 2019-12-03 22:36
> Hi @jstubbs303
> 
> Did you get anywhere with this issue? We have also been experiencing this, we're on 2.2.8.

Hey tprocter, no sorry we never did get this one figured out. It hasn't been consistent enough meaning we could take a couple of hundred orders with no problem and then on the next spot check we might have 1 or two that turned up completely missing, but the customer got processed at the payment gateway. Then it might go 3 to 4 hundred orders then again one turn up missing. We have been through the server error logs, Magento error logs, payment gateway error logs, and nothing could be found as to the root of the problem. What we had to do was spot check the site once a week and check any missing order numbers against our debug log to our payment gateway. Takes time to do but, catching those missing orders and getting them shipped off to keep customers happy is the bottom line. Luckily since Oct., we haven't had any more problems with orders turning up missing and we are a few thousand orders deep since the last issue so it looks like it might have resolved itself. To be honest, though, it might not have been a Magento or server-side problem. I'm thinking there might have been an issue with a processing server over at the payment gateway which might have been timing out and not sending back a response in time so Magento closed the order out.

**Comment by tprocter-ldg** [comment] 2019-12-05 11:11
Thanks for the response @jstubbs303 . We've experienced exactly the same, only a handful of orders out of thousands. We've been doing manual checks every day to catch any missing ones but it is definitely a strange issue! We've updated our js bundling files and we don't seem to have got any more missing orders as of yet but we'll see! Thanks again for the response :)

**Comment by sodhancha** [comment] 2020-10-28 13:09
@tprocter-ldg @magento-engcom-team 
We got this same issue on EE 2.3.4 and EE 2.3.5-p2
Can you confirm if this issue is occuring.

In our case it was much more frequent.
Almost 8% of the Prepaid orders had this issue.

**Comment by tprocter-ldg** [comment] 2020-10-28 13:50
Hi @sodhancha 

We are not experiencing this issue anymore and we eventually found that it was down to one of our own modules.

The issue occurred when an invalid tax code was entered by a logged in customer in the checkout. This fired off an infinite loop due to a circular dependancy that occurred between a custom module and the Tax module. It was extremely hard to debug as (if I remember rightly) I only noticed the circular dependency error when I tried to open a javascript file in the browser (I think it was shipping-information.js? This could be wrong, it's been a while since I looked at this issue!). 

I would take a look at your custom modules and see if you have anything which uses the checkoutsession and see if you can spot anything. Sorry if this is not very helpful for you, I hope you find the issue!
