### ISSUE TITLE
Autoload error when trying to setup a new and clean project

### ISSUE THREAD

**Issue by Slyvan25** [magento/magento2#38151] opened 2023-11-06 14:34 UTC
### Preconditions and environment

- Magento version 2.4.6-p3
- when trying to install the new project I get autoload errors when using the bin/magento tool

### Steps to reproduce

How to reproduce:
 - run a new magento install with lib/internal/Magento
 - output is: Library 'magento/framework' from '/var/www/html/lib/internal/Magento/Framework' has been already defined in '/var/www/html/vendor/magento/framework'.

fix (for now): remove the lib/internal/Magento folder

### Expected result

A fully working install command

### Actual result

Library 'magento/framework' from '/var/www/html/lib/internal/Magento/Framework' has been already defined in '/var/www/html/vendor/magento/framework'.

### Additional information

i removed the lib/internal/magento folder and got my project up and running again

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ananth-iyer** [comment] 2023-11-08 11:30
@Slyvan25 I just now installed fresh Magento 2.4.6-p3 and did not reproduce your issue.
It might be composer cache issue so clear it:-
```
composer clear-cache
```

FYI: Use composer 2

Regards.

**Comment by engcom-Bravo** [comment] 2023-11-09 11:40
@ananth-iyer Thanks for your contribution & collaboration over here.

Hi @Slyvan25,

Thank you for reporting and collaboration.

Verified the issue while installing the Magento Version 2.4.6-p3 we are able to install successfully.We are are not able to reproduce the issue.

Please refer this comment https://github.com/magento/magento2/issues/38151#issuecomment-1801702949 and please let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-11-20 06:13
Hi @Slyvan25,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38151#issuecomment-1803671267 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-11-29 05:39
Hi @Slyvan25,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-11-29 05:39 UTC
Labels: Issue: needs update, Reported on 2.4.6-p3
