### ISSUE TITLE
Import History table alignment issue.

### ISSUE THREAD

**Issue by suryakant-krish** [magento/magento2#19449] opened 2018-11-29 09:12 UTC
### Preconditions (*)

1. Magento 2.2.3

### Steps to reproduce (*)

1. Login into admin panel > System > import history > Import file "Download" alignment issue.

### Expected result (*)

1. ![expected-result-1](https://user-images.githubusercontent.com/43638601/49211105-cc458000-f3e4-11e8-9a77-5874d6ceeca9.png)

### Actual result (*)

1. ![actual-result-1](https://user-images.githubusercontent.com/43638601/49211154-f139f300-f3e4-11e8-92e7-1c56acfd47a1.png)

**Comment by magento-engcom-team** [comment] 2018-11-29 09:12
Hi @suryakant-krish. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@suryakant-krish do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-11-29 19:04
@dmytro-ch Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96741`, `MAGETWO-96742` were created

**Comment by magento-engcom-team** [comment] 2018-11-29 19:04
Hi @dmytro-ch. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by sdzhepa** [comment] 2019-01-16 13:50
Hello @suryakant-krish and @dmytro-ch 

Could you please clarify "preconditions"/"steps to reproduce" for this issue:

What exactly actions and steps required to receive this Actual Result?

In case without executed any Import before - we have empty grid, just with text : "We couldn't find any records."
![emptyimportgrid](https://user-images.githubusercontent.com/3409584/51253046-f90a2280-19a5-11e9-87a4-87f9e2a55642.png)


In case with some test import before(e.g. Products import) - Column "Imported File" has a name of used CSV file and link to Download

![notemptyimportgrid](https://user-images.githubusercontent.com/3409584/51253103-21921c80-19a6-11e9-9cd7-ab7ea0e31377.png)

**Comment by magento-engcom-team** [comment] 2019-01-28 05:10
Hi @speedy008. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by speedy008** [comment] 2019-01-28 05:11
@magento-engcom-team give me magento 2.2.3 instance

**Comment by magento-engcom-team** [comment] 2019-09-18 17:19
@suryakant-krish, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.3-develop` branch. Thank you for collaboration.

**Closed as completed by magento-engcom-team** 2019-09-18 17:19 UTC
Labels: Issue: Ready for Work, Component: ImportExport, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid
