### ISSUE TITLE
Configurable product dropdown option list, when one option out of stock, all other followed option will be disappeared too!

### ISSUE THREAD

**Issue by GordonMak** [magento/magento2#27628] opened 2020-04-05 15:17 UTC
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Configurable product with color and size (say, S, M, L, XL) options
2. one simple product in size M out of stock. 

### Expected result (*)

1. When M size is out of stock, M size option will be disappeared in the dropdown list, but all other sizes (L, XL) follow the size M should be shown and will not be disappeared. 
2, For example, if you have 4 sizes, S, M, L , XL, when size M is out of stock, the dropdown list for size options should have S, L, XL 
3. This is working good in 2.3.3 or before

### Actual result (*)

1. However, when upgraded to 2.3.4
2. When M size is out of stock, M size option will be disappeared in the dropdown list, and all other sizes (L, XL) follow the size M have been disappeared too. 
3. For example, if you have 4 sizes, S, M, L , XL, when size M is out of stock, the dropdown list in magento2.3.4 will only have size S option. Sizes L and XL (in stock) followed the size M (out of stock) also disappeared from the drop down option list.

**Comment by ajijshekh123** [comment] 2020-04-06 05:09
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-06 05:09
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-06 05:10
Hi @ajijshekh123, here is your [Magento instance](https://i-27628-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27628-2-4-develop.instances.magento-community.engineering/admin_0034](https://i-27628-2-4-develop.instances.magento-community.engineering/admin_0034)
Login: `be7aa642` Password: `297cd853a64a`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2020-04-06 06:11
Hello @GordonMak,

I have verified this issue as per the steps to reproduce and actual results.
I didn't reproduce this issue in the latest Magento 2.4 instance. 
Let me verify this in the Magento 2.3.4 and update you.

See attached the screenshot:
![1](https://user-images.githubusercontent.com/24711761/78527780-79ab7d80-77fb-11ea-9062-d8151e0f70f9.png)

![2](https://user-images.githubusercontent.com/24711761/78527784-7b754100-77fb-11ea-9316-e5b8e8042819.png)

![3](https://user-images.githubusercontent.com/24711761/78527786-7c0dd780-77fb-11ea-9519-62c6f698d7ca.png)

Thanks.

**Comment by GordonMak** [comment] 2020-04-06 07:01
Hi ajijshekh123，

Thank you for your reply! Please see attached screenshot for the issue I found in magento 2.3.4. Look forward to hearing your update for this. Thanks!
![frontend](https://user-images.githubusercontent.com/12252407/78531091-63131f80-7817-11ea-9fd8-fa4eb044921a.png)
![backend](https://user-images.githubusercontent.com/12252407/78531096-64444c80-7817-11ea-85c8-a8fb7ca25680.png)

**Comment by ajijshekh123** [comment] 2020-04-07 15:21
Hello @GordonMak ,
This issue is reproduced in the Magento 2.3 instance but Please update the Latest Magento instance so it will be automatically fixed this issue.
Please see attached screenshot:

![1](https://user-images.githubusercontent.com/24711761/78687117-76a2b100-7911-11ea-85f6-82344ee58e27.png)

![2](https://user-images.githubusercontent.com/24711761/78687131-7a363800-7911-11ea-8f22-40ba704ea50d.png)

Please update me. Can I close this issue or not?

Thanks.

**Comment by magento-engcom-team** [comment] 2020-04-30 15:35
Hi @CarmineDamore78, here is your [Magento instance](https://i-27628-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27628-2-4-develop.instances.magento-community.engineering/admin_d53d](https://i-27628-2-4-develop.instances.magento-community.engineering/admin_d53d)
Login: `20bf5bd8` Password: `7cd7b8cf25a9`
Instance will be terminated in up to 3 hours.

**Comment by CarmineDamore78** [comment] 2020-04-30 18:33
Hi @magento-engcom-team 
I wasn't enable to reproduce the issue on me2.4-develop

**Comment by sdzhepa** [comment] 2020-08-18 19:57
Closed as cannot reproduce on the latest `2.4-develop`  https://github.com/magento/magento2/issues/27628#issuecomment-622027423

**Closed as completed by sdzhepa** 2020-08-18 19:57 UTC
Labels: Component: Catalog, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue:  Cannot Reproduce, Issue: Format is valid, Component: ConfigurableProduct, Component: Admin, Progress: ready for dev, Reported on 2.3.3
