### ISSUE TITLE
x_forwarded_for empty in order object

### ISSUE THREAD

**Issue by dzhuser** [magento/magento2#36723] opened 2023-01-10 16:32 UTC
### Preconditions and environment

Magento 2.4.5-p1
graphQl

After upgrading  from 2.4.3-p1 to 2.4.5-p1 `sales_order` table now always has null value for `x_forwarded_for` column.  It seems that refactored  `Magento\Framework\Api\DataObjectHelper` has bug in `getSetters` method: preg_replace not worked correctly for `setXForwardedFor` method and returns `xforwarded_for` key and this causes not setting `x_forwarded_for` value for order object

### Steps to reproduce

Place order using graphQl `placeOrder` mutation

### Expected result

`sales_order` table has correct value in `x_forwarded_for` column

### Actual result

`sales_order` table has null value in `x_forwarded_for` column

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-01-11 14:15
Hi @dzhuser,

We have verified the issue in Magento 2.4 develop instance and also we have verified while upgrading from 2.4.3-p1 to 2.4.5-p1 in both the cases we are getting NULL values for `xforwarded_for`.

This is an expected behaviour of Magento.


<img width="530" alt="Screenshot 2023-01-11 at 5 12 46 PM" src="https://user-images.githubusercontent.com/51680745/211828031-68b3531d-23f5-498f-a37d-bde5048a12c3.png">



<img width="538" alt="Screenshot 2023-01-11 at 5 12 52 PM" src="https://user-images.githubusercontent.com/51680745/211828058-480049a5-da86-44d1-a2af-c437769aaee0.png">




We have gone through with this document https://experienceleague.adobe.com/docs/commerce-business-intelligence/mbi/analyze/tables/sales-flat-order-table.html?lang=en. related to sales_order table we have not find any information related to `xforwarded_for`.


Kindly provide us more information to proceed further it will be helpful for us.


Thanks.

**Comment by dzhuser** [comment] 2023-01-11 17:10
The column name is `x_forwarded_for` not `xforwarded_for`. Magento installs this filed, If you look at https://github.com/magento/magento2/blob/2.4.5-p1/app/code/Magento/Sales/etc/db_schema.xml and https://github.com/magento/magento2/blob/2.4.5-p1/app/code/Magento/Sales/etc/db_schema_whitelist.json you will see there `x_forwarded_for` column. And also here https://github.com/magento/magento2/blob/2.4.5-p1/app/code/Magento/Sales/etc/fieldset.xml you can see that `x_forwarded_for` field value should be transferred from quote to order. Also Order model has `setXForwardedFor` and `getXForwardedFor` methods.
So, all of these shows that `x_forwarded_for` has to be filled and I don`t why this field no described in the document you have mentioned.

The reason why this column not filled it because `getSetters` method in `Magento\Framework\Api\DataObjectHelper` retunds wrong key for data array, it returns `xforwarded_for` but should `x_forwarded_for`. The wrong data key is skipping here https://i.imgur.com/SxtkYBb.png That is why the value for `x_forwarded_for` is not transferred from quote to order.

**Comment by hostep** [comment] 2023-01-20 09:45
I can confirm that after having updated to 2.4.5-p1 (from 2.3.7-p4 in this particular case, but that's not really important), that new orders that come in no longer have the `x_forwarded_for` column filled in in the database.

Good analysis @dzhuser!

@kandy, @adifucan: it looks like you two guys worked on this refactoring of the `Magento\Framework\Api\ DataObjectHelper::getSetters` method, maybe you guys an idea of how to get this fixed?

**Comment by engcom-Hotel** [comment] 2023-01-20 10:59
Hello @dzhuser,

Thanks for the report and collaboration!

We have tried to reproduce the issue in the 2.4-develop instance and the issue is reproducible for us. We have tried it with 3 orders and for all orders the `x_forwarded_for` column is empty:
<img width="610" alt="image" src="https://user-images.githubusercontent.com/51681618/213679583-644dc703-42ae-42e6-9b61-4e0b2d1b2d3a.png">

Hence confirming the issue.

Thanks

**Comment by kandy** [comment] 2023-01-20 18:10
@hostep Looks like problem that `\Magento\Framework\Api\DataObjectHelper::getSetters` does not properly handle method with two capital latter's in a row  
so, we need to add this case as well, https://3v4l.org/On5b2

**Comment by hostep** [comment] 2023-01-23 11:01
Thanks @kandy: after writing [a quick unit test and using your suggested fix](https://github.com/magento/magento2/pull/36767), it seems like this fixes it indeed! Have to still test it out in the real world, but I'm pretty sure this is a good fix.

**Comment by hostep** [comment] 2023-02-16 07:08
This issue can be closed now I believe, [ACP2E-1381: Different behaviors on snake_case formatting](https://github.com/magento/magento2/commit/7ca752f5a3355059aa457f1cfc03402777de0250) fixed this.

**Comment by engcom-Hotel** [comment] 2023-02-17 12:15
Thanks @hostep we are closing this ticket.

Thanks

**Closed as completed by engcom-Hotel** 2023-02-17 12:15 UTC
Labels: Issue: Confirmed, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Framework, Reported on 2.4.5-p1
