### ISSUE TITLE
DHL Shipping Quotes fail for Domestic Shipments when Content Mode is "Non Documents"

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#19485] opened 2018-11-30 15:49 UTC
### Preconditions (*)
1. Magento 2.2-develop or 2.3-develop

### Steps to reproduce (*)
1. Setup DHL module to obtain quotes via XML
2. Setup store as ship from address SW1 1AA, GB
3. Set DHL Content Type to Non Documents
4. Attempt to obtain shipping quote for destination SW1 1AA, GB

### Expected result (*)
1. A quote is obtained

### Actual result (*)
1. No quote is obtained.

Investigation shows that the request to DHL is stating that the shipment is dutiable, even though the shipment is domestic. This causes DHL to reply with an error. This seems to be due to this change. https://github.com/magento/magento2/commit/410027d7a484d0fd2fa74de569f3107ede2c6575#diff-de9bd572b851dd842e021c8421062177

**Comment by magento-engcom-team** [comment] 2018-11-30 15:49
Hi @gwharton. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@gwharton do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by gwharton** [comment] 2018-11-30 21:31
PR #19487 @ PR #19488 fixes ready.

**Comment by magento-engcom-team** [comment] 2019-01-09 10:47
Hi @engcom-backlog-tomash. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-01-09 10:48
@engcom-backlog-tomash Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-01-09 10:49
@engcom-backlog-tomash Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97515`, `MAGETWO-97516` were created

**Comment by magento-engcom-team** [comment] 2019-02-18 19:20
Hi @gwharton. Thank you for your report. 
The issue has been fixed in magento/magento2#19487 by @gwharton in 2.3-develop branch
Related commit(s):
 - [77a5cd1a51e376d4f02bc23dcfdee0c61f08c6a7](https://github.com/magento/magento2/commit/77a5cd1a51e376d4f02bc23dcfdee0c61f08c6a7)
 - [ff9282dca5b76a1df543c4ab8a001def4b9e9e0c](https://github.com/magento/magento2/commit/ff9282dca5b76a1df543c4ab8a001def4b9e9e0c)
 - [d9ac0d6d188f0e6fe2d7fac9845db51a34630d2f](https://github.com/magento/magento2/commit/d9ac0d6d188f0e6fe2d7fac9845db51a34630d2f)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-02-18 19:20 UTC
Labels: Component: Sales, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Progress: PR Created, Component: Dhl

**Comment by magento-engcom-team** [comment] 2019-04-04 12:30
Hi @gwharton. Thank you for your report. 
The issue has been fixed in magento/magento2#19488 by @gwharton in 2.2-develop branch
Related commit(s):
 - [e6b279b815b80065fdb7a70ed0fea16d26960425](https://github.com/magento/magento2/commit/e6b279b815b80065fdb7a70ed0fea16d26960425)
 - [ce7b5602466b47777cfa9de1cec31fa9f02ac644](https://github.com/magento/magento2/commit/ce7b5602466b47777cfa9de1cec31fa9f02ac644)
 - [49e26db2a7ab099258cdd9307ad572f5b8075333](https://github.com/magento/magento2/commit/49e26db2a7ab099258cdd9307ad572f5b8075333)
 - [a497c95712e1682904d62b80525efd3bce380fef](https://github.com/magento/magento2/commit/a497c95712e1682904d62b80525efd3bce380fef)
 - [5557b9d06c169fbd8b38f7c598e51c8c49e94739](https://github.com/magento/magento2/commit/5557b9d06c169fbd8b38f7c598e51c8c49e94739)

The fix will be available with the upcoming 2.2.9 release.
