### ISSUE TITLE
Newsletter Queue doesn't set to local time

### ISSUE THREAD

**Issue by Ctucker9233** [magento/magento2#5943] opened 2016-08-02 17:24 UTC
When queuing a newletter, the queue start time does not match local time. If I want to send out a newsletter immediately, it results in a status of "not sent" because the time gets shifted back about 7 hours.

Preconditions
1. Magento 2.1
2. PHP 5.6.22
### Steps to reproduce
1. Create newsletter template
2. Queue newsletter template
3. Set Queue start to send today, adjust time forward an hour or two, for example, 11:19 am (my local time at the point of writing this is 10:19 AM PST)
4. Click Save Newsletter
### Expected result
1. Newsletter is queued to send at 11:19 AM 8/2/16
### Actual result
1. Newsletter is queued to send at 4:19 PM 8/1/16
2. Results in the newsletter never being sent

I need to be able to reliably send newsletters any time I want. I don't always have time to queue up a newsletter the day before I have to send it. I appreciate any help on this issue.

**Comment by ghost** [comment] 2016-08-03 16:11
Same issue here with Magento 2.1 CE. The only difference is the time that gets saved is 3 hours behind when I set it to be.

**Comment by duhon** [comment] 2016-08-03 17:27
@Ctucker9233 Thanks for reporting this issue.
We've created internal ticket MAGETWO-56349 to fix it.

**Comment by Ctucker9233** [comment] 2016-08-04 22:54
@duhon Thank you. Is it too early to ask the timeline for when this might be fixed?

**Comment by Ctucker9233** [comment] 2016-08-18 21:14
@duhon Any update on this issue?

**Comment by Ctucker9233** [comment] 2016-08-21 01:51
@veloraven @duhon Any updates on progress?

**Comment by Ctucker9233** [comment] 2016-10-13 20:52
@veloraven @duhon @magento-team Any updates on this issue? Would like to know when a fix is estimated.

**Comment by Ctucker9233** [comment] 2016-10-25 00:14
@veloraven @magento-admin @magento-team Please, any news on this issue?

**Comment by Ctucker9233** [comment] 2016-10-25 16:46
@veloraven modifying my php.ini file with date.timezone = "America/Los Angeles" helps some but I still have a two hour discrepancy.

**Comment by Ctucker9233** [comment] 2016-10-25 23:53
@veloraven with the help of my hosting company, I think I've traced it to app/bootstrap.ini date_default_timezone_set('UTC');
This issue has appeared before. See #3028.
I understand the reasoning for keeping it UTC. 
In framework/stdlib/DateTime/DateTime.php it looks like it is supposed to create an offset from UTC so that the users local time is displayed in the newsletter queue. It would appear that that is what is not working. @magento-team Please have a look at this.

**Comment by Ctucker9233** [comment] 2016-11-10 19:19
@veloraven @duhon @magento-team Please, this issue is critical. Even queuing my newsletter ahead of the 5 hour or so time delay seems to cause the queue to fail. Any updates at all in the investigation of this issue?

**Comment by Ctucker9233** [comment] 2016-11-19 23:04
@veloraven @duhon @magento-admin @magento-team Please, is there any news about this issue? Anything I can do to help out? Just answer me please.

**Comment by Ctucker9233** [comment] 2016-12-10 01:13
@veloraven Is there any kind of update on whats going on with this ticket?

**Comment by Ctucker9233** [comment] 2017-01-10 23:22
@magento-admin @magento-team Is there any kind of news or update on this issue? Does anyone have a work around?

**Comment by Ctucker9233** [comment] 2017-02-03 22:48
@veloraven @magento-team @magento-admin It's been 6 months now.......are we any closer to a solution? Are any of you actually alive or am I just talking to computers here?

**Comment by Ctucker9233** [comment] 2017-02-05 00:55
Closing issue and opening new one since the magento team has failed to respond for 6 months.

**Comment by dunctem** [comment] 2017-08-06 18:17
Any updates on this?

**Comment by Ctucker9233** [comment] 2017-10-11 18:18
@magento-engcom-team Thanks for finally deciding to fix this issue. I appreciate it. Now, what release might this fix be included in?

**Comment by magento-engcom-team** [comment] 2017-10-12 13:30
@Ctucker9233, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-12 13:30 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by Ctucker9233** [comment] 2017-12-03 00:27
@magento-engcom-team Thanks for fixing. Can you please open a ticket to backport to 2.1?
