### ISSUE TITLE
Tax rates calculation is going wrong

### ISSUE THREAD

**Issue by arun-techmanyata** [magento/magento2#10564] opened 2017-08-17 09:50 UTC
Hi M using magento 2, I am trying to setup tax rates but the tax calculation resultant is wrong not sure where am i going wrong. Kinldy help me on this.
Expected:
Product cost(Backend): INR 100
**Product cost(Frontend): INR 100 (This is inclusive of tax 18%)**
Cart:   Subtotal:  INR 82
          **tax:          INR 18**
          **Total:       INR 100**

# But what i see is the following:

![screenshot-crazyelife](https://user-images.githubusercontent.com/30151302/29406632-35093f34-835f-11e7-8534-2187aee5aada.jpg)

# Configuration is as follows:

![backend](https://user-images.githubusercontent.com/30151302/29406633-35093534-835f-11e7-9602-f3a9ccf6cc89.png)

**Comment by korostii** [comment] 2017-08-17 14:29
When price includes tax, tax base isn't 100 in this case, it's 84.75 actually.
Thus tax = (84.75 * 18)/100 = 15.255 

The formula to use in order to calculate tax directly from price incl.tax is:
tax = (price * 18) / (100 + 18) = 15.25423728813559

**Comment by arun-techmanyata** [comment] 2017-08-21 10:40
Thanks Korostii. Is there any way that i can achieve the expected results.

**Comment by arun-techmanyata** [comment] 2017-08-21 10:42
**Expected:
If Assigned Product cost at Backend as INR 100**

Product cost(Frontend): INR 100 (This is inclusive of tax 18%)
Cart: Subtotal: INR 82
tax: INR 18
Total: INR 100

**Comment by vherasymenko** [comment] 2017-08-21 12:42
@arun-techmanyata Thank you for your report.
Please use the issue reporting [guidelines ](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)to report an issue. Include the steps required to reproduce, the actual result, and the expected result.

**Comment by korostii** [comment] 2017-08-21 15:49
@arun-techmanyata, 
If your tax base is less than 100, tax has to go lower than 18. Otherwise it's just wrong and not "desired".

While having tax rate of 18% ,  you can have row tax of INR 18 only if price _excluding_ tax is INR 100.
You can do that by switching "Display Taxes" setting to "Excluding Tax"
E.g. price in admin 100 , tax rate 18% -> tax will be applied on top of price -> in frontend you'll have:
price excl. 100, tax 18, total **118**.

**Comment by korostii** [comment] 2017-08-21 15:51
Additionally, please keep in mind that this is not a help desk. 
The behavior of Magento in this case seems to be as intended thus it's not a bug. 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") of Magento CE itself only.

If you are looking for some help or an advice regarding setup or configuration please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/).

**Comment by fooman** [comment] 2017-08-25 02:43
Closing this issue since Magento seems to work as expected. Thanks @korostii for looking into this.

**Closed as completed by fooman** 2017-08-25 02:43 UTC
Labels: bug report, Progress: needs update
