### ISSUE TITLE
Triggers for scconnector_google_feed_cl are not removed correctly

### ISSUE THREAD

**Issue by sippsolutions** [magento/magento2#37472] opened 2023-05-08 14:04 UTC
### Preconditions and environment

- Magento version 2.4.6 (upgraded from Magento 2.3.x)

### Steps to reproduce

Try to save new product images

### Expected result

Images are saved

### Actual result

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xyz.scconnector_google_feed_cl' doesn't exist, query was: DELETE FROM `catalog_product_entity_media_gallery_value` WHERE (value_id = 336222 AND row_id = 92521 AND store_id = 0)

### Additional information

In `\Magento\GoogleShoppingAds\Setup\Recurring` the `scconnector_google_feed` table is removed, but existing triggers are not removed. 
Seems to be other people are having that issue too: https://magento.stackexchange.com/questions/323050/scconnector-google-feed-cl-error-after-product-save-just-upgraded-to-2-3-5-p2

Issue is about the triggers
**trg_catalog_product_entity_media_gallery_value_after_insert**
```
BEGIN
SET @entity_id = (SELECT `entity_id` FROM `catalog_product_entity` WHERE `row_id` = NEW.`row_id`);
INSERT IGNORE INTO `scconnector_google_feed_cl` (`entity_id`) values(@entity_id);
END
```

**trg_catalog_product_entity_media_gallery_value_after_update**
```
BEGIN
SET @entity_id = (SELECT `entity_id` FROM `catalog_product_entity` WHERE `row_id` = NEW.`row_id`);
IF (NOT(NEW.`value_id` <=> OLD.`value_id`) OR NOT(NEW.`store_id` <=> OLD.`store_id`) OR NOT(NEW.`label` <=> OLD.`label`) OR NOT(NEW.`position` <=> OLD.`position`) OR NOT(NEW.`disabled` <=> OLD.`disabled`) OR NOT(NEW.`record_id` <=> OLD.`record_id`) OR NOT(NEW.`row_id` <=> OLD.`row_id`)) THEN INSERT IGNORE INTO `scconnector_google_feed_cl` (`entity_id`) values(@entity_id); END IF;
END
```

**trg_catalog_product_entity_media_gallery_value_after_delete**
```
BEGIN
SET @entity_id = (SELECT `entity_id` FROM `catalog_product_entity` WHERE `row_id` = OLD.`row_id`);
INSERT IGNORE INTO `scconnector_google_feed_cl` (`entity_id`) values(@entity_id);
END
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-05-12 05:04
Hi @sippsolutions ,

Thanks for Contribution and collaboration !

Verified the issue in 2.4.6 magento instance and issue is not reproducible.

**Kindly refer the below screenshots:**
<img width="1511" alt="Screenshot 2023-05-11 at 4 59 34 PM" src="https://github.com/magento/magento2/assets/60198592/36cbe8f6-3574-484d-8132-8b75576e666c">
<img width="1511" alt="Screenshot 2023-05-12 at 10 28 36 AM" src="https://github.com/magento/magento2/assets/60198592/072802e2-498e-48cb-83f9-5369503a74e5">

**Steps to reproduce:**
1.Install 2.3.7-p4 Magento instance
2.Upgrade instance to 2.4.6 by following [DevDocs](https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html)
3.Trying add new Product images 

We can successfully save the products images without any issue.Kindly provide more information or screenshots if the issue still reproducible.

Thanks!

**Comment by engcom-Dash** [comment] 2023-06-07 03:38
Hi @sippsolutions ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by sippsolutions** [comment] 2023-06-28 13:05
I have now gathered more information.

When updating from 2.3.x there is a `scconnector_google_remove` entry in the `mview_state` table.
This leads to having the `scconnector` tables inside the db trigger.

While in 2.4.x these tables are being removed with `\Magento\GoogleShoppingAds\Setup\Recurring` it is limited to only being executed once (`if (version_compare($context->getVersion(), '4.0.1', '<'))`) - which contradicts the idea of a recurring script imho.

We were using a third party module that iterates over all indexers and sets them as scheduled.

```
foreach (array_keys($this->configInterface->getIndexers()) as $indexerId) {
 $indexer->setScheduled(true);
}
```

Even if you remove that module, the scconnectors indexers are now set as scheduled again (`mode` = `enabled` for `scconnector_google_feed` in `mview_state`) and will then be included in the triggers that get created/updated within every `setup:upgrade`.

To fix this the `if (version_compare($context->getVersion(), '4.0.1', '<'))` should be removed, so the recurring script gets executed every time again - or there should be a one-time patch that removes the entries from the `mview_state` table.

**Comment by sippsolutions** [comment] 2023-06-28 13:06
@engcom-Dash @m2-assistant please re-open the issue

**Comment by adam-webee** [comment] 2023-07-06 17:16
I was facing the same issue, and for me, this was the solution:
```
delete from mview_state where view_id like '%scconnector%';
```

**Comment by sippsolutions** [comment] 2023-07-24 12:17
@magento @adobe @m2-community-project @engcom-Dash please re-open the issue

**Comment by engcom-Dash** [comment] 2023-08-10 11:02
Hi @sippsolutions ,

We are closing this issue because seems like duplicate  of [#37801 ](https://github.com/magento/magento2/issues/37801) and we are following with latest issue [#37801 ](https://github.com/magento/magento2/issues/37801).

Thanks.

**Closed as completed by engcom-Dash** 2023-08-10 11:02 UTC
Labels: Issue: ready for confirmation, Reported on 2.4.6

**Comment by robjstanley** [comment] 2024-02-12 07:51
> I was facing the same issue, and for me, this was the solution:
> 
> ```
> delete from mview_state where view_id like '%scconnector%';
> ```

Solved the issue for me, thanks.
