### ISSUE TITLE
Product Display Page: Error: Call to a member function getId() on bool in vendor/magento/module-catalog/Block/Product/ListProduct.php:464

### ISSUE THREAD

**Issue by nbennett25** [magento/magento2#34039] opened 2021-09-09 17:28 UTC
### Preconditions (*)

1. Magento 2.4.2-p2

### Steps to reproduce (*)

1. Go to Product Display page with product assigned to at least one category

### Expected result (*)

1. Product display page is rendered

### Actual result (*)

1. Error is thrown (developer mode)

Stack trace:
`Error: Call to a member function getId() on bool in /var/www/html/vendor/magento/module-catalog/Block/Product/ListProduct.php:464`

This appears to be related to the change in the `Magento\Catalog\Block\Product\ListProduct` class, converting to the use of the `current` method:

```
462             if ($categories->count()) {
463                 // show products from this category
464                 $this->setCategoryId(current($categories->getIterator())->getId());
465             }
```

Converting this to use the built in `current()` method in the `ArrayIterator` class works as expected:

```
462             if ($categories->count()) {
463                 // show products from this category
464                 $this->setCategoryId($categories->getIterator()->current()->getId());
465             }
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by nbennett25** [comment] 2021-09-09 17:32
@magento give me 2.4-develop instance

**Comment by hostep** [comment] 2021-09-09 21:05
It appears there is already a fix for this problem: https://github.com/magento/magento2/pull/32389 and it looks like this fix is included in Magento 2.4.3

**Comment by engcom-November** [comment] 2021-09-10 09:35
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible:
**Steps performed:**
Magento Operation mode is set to developer - bin/magento deploy:mode:set developer
Front-end - Catalog Search Results page - Click on Product - Product Details page is displayed as expected
Assigned Product to multiple categories from Admin and saved
Reindex and clear cache
Front-end - Product Details page is displayed as expected. **No issue**
Admin - Product page is also displayed as expected - No issue
@nbennett25 , kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by nbennett25** [comment] 2021-09-15 16:51
thx @engcom-November - a deeper dive into the stack trace on our end indicates that this issue stems from the `Smartwave_FilteredProducts` module. Thanks for investigating!

**Comment by nbennett25** [comment] 2021-09-15 17:25
Issue related to Porto theme

**Closed as completed** 2021-09-15 17:25 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.2
