### ISSUE TITLE
Wrong content in admin Stores->Configuration->Desig

### ISSUE THREAD

**Issue by Styopchik** [magento/magento2#5369] opened 2016-06-30 06:21 UTC
## Steps to reproduce
1. Install Magento from downloaded zip.
2. Go to admin pannel Stores->Configuration->Design.
## Expected result
1. To see design configuration
## Actual result
1. Search engine robots configuration.
2. 
   ![image](https://cloud.githubusercontent.com/assets/884525/16478692/ff262d6a-3ea3-11e6-9f60-a6c5a69353fc.png)

**Comment by hostep** [comment] 2016-06-30 07:02
Duplicate of #5240

@Styopchik: it has been moved to Content => Configuration

Please try to search for an issue first before creating a new one, this has been reported like 7 times already.

**Comment by Styopchik** [comment] 2016-06-30 07:19
sorry :)

**Comment by veloraven** [comment] 2016-07-28 14:50
Closed as not an issue.

**Closed as completed by veloraven** 2016-07-28 14:50 UTC
