### ISSUE TITLE
Used gift card amount also refunding while doing the credit memo 

### ISSUE THREAD

**Issue by sudheersingamsetti** [magento/magento2#38953] opened 2024-07-19 11:20 UTC
### Preconditions and environment

- Magento version - 2.4.6-p6

### Steps to reproduce

1. Buy Gift Card (1st order)
2. Use bought Gift Card for any order (2nd order)
3. Refund ordered with used Gift Card(First placed order)

### Expected result

The Gift Card amount is not refunded

### Actual result

Order with Gift Card is fully refunded

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2024-07-23 05:36
@magento give me 2.4-develop instanc

**Comment by engcom-Dash** [comment] 2024-07-23 05:38
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2024-07-24 11:21
Hi @sudheersingamsetti 

Thanks for reporting and collaboration.

Verified the issue on Magento 2.4 dev instance and Magento 2.4.7-p1 instance but the issue is not reproducable.

Steps to reproduce
Buy Gift Card (1st order)
Use bought Gift Card for any order (2nd order)
Refund ordered with used Gift Card(First placed order)

The Gift Card amount is not refunded

Please refer the attached screenshots and let us know if we missed anything.

Buying the gift card:

<img width="1440" alt="Screenshot 2024-07-24 at 4 43 14 PM" src="https://github.com/user-attachments/assets/8cf90cd2-1c50-42ff-87f5-016f5eb7808a">

Placing order with the received gift card:

<img width="1440" alt="Screenshot 2024-07-24 at 4 43 10 PM" src="https://github.com/user-attachments/assets/6d2605df-25fe-4158-91ce-69cb345c4f9f">

<img width="1440" alt="Screenshot 2024-07-24 at 4 43 35 PM" src="https://github.com/user-attachments/assets/a9617133-5998-4d46-afaf-dc22f7f0ec38">

Credit memo after receiving the refund:

<img width="1440" alt="Screenshot 2024-07-24 at 4 44 01 PM" src="https://github.com/user-attachments/assets/0fada4ea-26a1-4c78-aed6-283cfd8adad6">

<img width="1440" alt="Screenshot 2024-07-24 at 4 50 22 PM" src="https://github.com/user-attachments/assets/be757c83-9462-428e-9a50-82c8fd66849a">

**Comment by engcom-Bravo** [comment] 2024-08-07 04:57
Hi @sudheersingamsetti,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-08-07 04:57 UTC
Labels: Issue: needs update, Reported on 2.4.6-p6
