### ISSUE TITLE
CategoryLinkReposity does not list all possible exceptions

### ISSUE THREAD

**Issue by troendheim** [magento/magento2#20037] opened 2019-01-02 09:03 UTC
### Summary (*)
The PHPDoc in https://github.com/magento/magento2/blob/2.3.0/app/code/Magento/Catalog/Api/CategoryLinkRepositoryInterface.php (`delete` and `deleteByIds`) does show the full list of exceptions that could be thrown.

I have checked and the issue exists in v2.2.7 and v2.3.0. 

### Examples (*)
https://github.com/magento/magento2/blob/2.3.0/app/code/Magento/Catalog/Model/CategoryLinkRepository.php#L81 throws InputException. Neither the method or the interface declares this through PHPDoc which can lead to surprises when using the repository.

### Proposed solution
Add Magento\Framework\Exception to "throws" for the two methods

**Comment by magento-engcom-team** [comment] 2019-01-02 09:03
Hi @troendheim. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@troendheim do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-02 09:05
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-01-02 09:41
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97398`, `MAGETWO-97399` were created

**Comment by orlangur** [comment] 2019-01-02 18:20
@troendheim instead of reporting in such cases it's better to propose a pull request ;)

Thanks for collaboration!

**Comment by sidolov** [comment] 2019-01-04 22:18
Hi @troendheim. Thank you for your report. 
The issue has been fixed in magento/magento2#20050 by @pmclain in 2.3-develop branch
Related commit(s):
 - [d08ce919585c9f3e9020662eaf0948df260fbb4a](https://github.com/magento/magento2/commit/d08ce919585c9f3e9020662eaf0948df260fbb4a)
 - [a1d3299191805ea5fbee133436fe82ccb6b9a5cd](https://github.com/magento/magento2/commit/a1d3299191805ea5fbee133436fe82ccb6b9a5cd)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by sidolov** 2019-01-04 22:18 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid
