### ISSUE TITLE
Product image cannot be loaded in the back end

### ISSUE THREAD

**Issue by web-markal** [magento/magento2#36945] opened 2023-03-02 10:41 UTC
### Preconditions and environment

- Magento 1.7.02
- The option for upload image for eac product is not available anymore. We cannot create new product without image.
![image](https://user-images.githubusercontent.com/126772802/222404905-ba837248-0f33-4b1d-855c-086818cb0d46.png)
Thanks in advance

### Steps to reproduce

Catalogue / Gérér les produits / Editer un produit

### Expected result

Option for uploading product appear again

### Actual result

No option available for uploading product image

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-03-02 13:26
Hi @web-markal,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

**Steps to reproduce**

1.Catalog/Products/Edit Products.

We are able to upload a image for a product and image is loaded successfully.


https://user-images.githubusercontent.com/51680745/222418158-cf581831-cadc-41cd-8ad5-341c9ff9fc7c.mov






Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by web-markal** [comment] 2023-03-02 13:28
Hi,
The environment is Magento 1.7.0.2

**Comment by gino2014** [comment] 2023-03-02 15:30
Hi @web-markal ,
m1 is offiically not longer supported. But you can find help at openmage https://www.openmage.org and https://github.com/OpenMage or https://github.com/OpenMage/magento-lts
There is magento 1.x still maintained. Maybe you can find there a solution.

**Comment by engcom-November** [comment] 2023-03-06 04:17
Hi @web-markal ,

Magento 1.x is no longer a supported version. We are closing this issue as its not reproducible on 2.4-develop instance. Kindly upgrade your Magento to latest 2.4.x version or recheck the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.

**Closed as completed by engcom-November** 2023-03-06 04:17 UTC
Labels: Issue: needs update, Reported on 2.4.x

**Comment by web-markal** [comment] 2023-03-06 13:46
> Hi @web-markal , m1 is offiically not longer supported. But you can find help at openmage https://www.openmage.org and https://github.com/OpenMage or https://github.com/OpenMage/magento-lts There is magento 1.x still maintained. Maybe you can find there a solution.

@gino2014 Thanks!
