### ISSUE TITLE
Zend_Validate_File_Upload - undefined class on 2.4.6

### ISSUE THREAD

**Issue by MTheProgrammer** [magento/magento2#37281] opened 2023-03-22 07:30 UTC
### Preconditions and environment

- Magento OS 2.4.6
- method \Magento\ImportExport\Model\Source\Upload::uploadSource is using a removed Zend_Validate_File_Upload class
- restricted_classes.php is missing replacement for Zend_Validate_File_Upload , see: `magento-coding-standard/Magento2/Sniffs/Legacy/_files/restricted_classes.php`

There is Laminas class which can be used as template for appropriate Magento class:
```Laminas\Validator\File\Upload```

### Steps to reproduce

I was digging in the importer code and just found that this class has not been migrated.
Uploading an import file larger than configured in php.ini will crash the validator.

### Expected result

- restricted_classes.php should have replacement for Zend_Validate_File_Upload , see: `magento-coding-standard/Magento2/Sniffs/Legacy/_files/restricted_classes.php`

- One of the messages is printed:
``` __('Make sure your file isn\'t more than %1M.', $maxImageSize);```
``` __('We can\'t provide the upload settings right now.');```

### Actual result

Validator crashes

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Yaroslav1301** [comment] 2023-03-23 11:53
@magento add to contributors team

**Comment by MTheProgrammer** [comment] 2023-03-23 15:25
Shall we assume that code is correct if the class does not exist? It should be removed or replaced and marked in legacy tests because someone might’ve been using it in their module. 

The message should indicate that file was not uploaded due to its size. Current error message is too vague and does not point to the source of the problem.

**Comment by danmooney2** [comment] 2023-03-23 17:04
Agreed, obviously we should not be referencing classes that don't exist in our code.  `\Zend_File_Transfer_Adapter_Http` also doesn't exist anymore yet is being used as typehint reference in screenshot above.

**Comment by engcom-Hotel** [comment] 2023-03-24 10:44
Hello @MTheProgrammer,

I agree with your point, and we can confirm this issue via looking into the codebase but is that possible for you to provide the steps to reproduce this issue?

Because mentioned steps are not working for us.

Thanks

**Comment by danmooney2** [comment] 2023-03-27 13:33
The believe the expectation is that return value of \Magento\ImportExport\Helper\Data::getMaxUploadSizeMessage is used in error message.

**Comment by glo71317** [comment] 2023-04-10 09:05
Internal Team is working on this and will provide the fix ASAP

**Comment by hostep** [comment] 2023-05-10 19:18
Seems to be fixed by [AC-8384: Zend_Validate_File_Upload-undefined class on 2.4.6](https://github.com/magento/magento2/commit/4431026e3e367366ebfc8c90124aca895e902317)

**Comment by engcom-Bravo** [comment] 2023-05-11 06:45
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-8384 by the internal team
Related commits: https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-8384&type=commits

Based on the Jira ticket, the target version is 2.4.7-beta1.

Thanks

**Closed as completed by engcom-Bravo** 2023-05-11 06:45 UTC
Labels: Component: ImportExport, Issue: Confirmed, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P1, Progress: done, Area: Framework, Reported on 2.4.6
