### ISSUE TITLE
Error SelectedShippingMethod on mutation setShippingMethodsOnCart is null

### ISSUE THREAD

**Issue by owandrejavidovic** [magento/magento2#39175] opened 2024-09-17 06:38 UTC
The issue is in Magento 2.4.7
mutation {
  setShippingMethodsOnCart(
    input: {
      cart_id: "walNToYaEaFeN4QKFoQwz9hlChT124Gn"
      shipping_methods: [{
        carrier_code : "your_method"
        method_code : "your_method"
      }]
    }
  ) {
    cart {
      email
      id
      is_virtual
      owNewsletterSubscribe
      shipping_addresses {
      selected_shipping_method{
        carrier_code
        carrier_title
      }
      street
      telephone
      uid
    }
    total_quantity
    }
  }
}

Response:
{
  "data": {
    "setShippingMethodsOnCart": {
      "cart": {
        "email": "peter.novak+41@optiweb.com",
        "id": "fPM15smAU0qoOacz8LT7XlfXEenvTT9p",
        "is_virtual": false,
        "shipping_addresses": [
          {
            "selected_shipping_method": null, // this is the issue
            "street": [
              "Test 1"
            ],
            "telephone": "041676376",
            "uid": 233034
          }
        ],
        "total_quantity": 1
      }
    }
  }
}
![image](https://github.com/user-attachments/assets/8067c372-0026-463a-b2c8-b0ffca40b623)

![image](https://github.com/user-attachments/assets/e8e6b425-24c7-4539-ba4c-20939fb18db4)

_Originally posted by @owandrejavidovic in https://github.com/magento/magento2/issues/38735#issuecomment-2352734668_

**Comment by engcom-Bravo** [comment] 2024-09-20 11:10
Hi @owandrejavidovic,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


<img width="1399" alt="Screenshot 2024-09-20 at 16 38 20" src="https://github.com/user-attachments/assets/67fc9cc4-b2f5-4b51-a556-9423ecc93512">


There is no error for setShippingMethodsOnCart mutation.

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by owandrejavidovic** [comment] 2024-09-20 11:19
Can you check on Magento 2.7.4? There is an error.

**Comment by engcom-Bravo** [comment] 2024-09-23 07:30
Hi @owandrejavidovic,

Thanks for your update.

It is recommended to verify the issues in Latest 2.4-develop Magento instance.Could you please check if any third party modules can causing this issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-10-07 04:06
Hi @owandrejavidovic,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Bravo** 2024-10-07 04:06 UTC
Labels: Issue: needs update, Reported on 2.4.7
