### ISSUE TITLE
[ja_jp] language package is not installable

### ISSUE THREAD

**Issue by zepgram** [magento/magento2#35835] opened 2022-07-28 08:31 UTC
### Preconditions and environment

- Magento version 2.4.3-p2 enterprise edition
- Composer v2.3.10

### Steps to reproduce

1. Get a magento environment (community/enterprise)
2. Run `composer require community-engineering/language-ja_jp:1.0.19` (any tag, it will be the same result)
3. Composer will try to install a priority version "1.0.0" that doesn't exist on official repository: https://github.com/magento-l10n/language-ja_JP/tags

### Expected result

Ja_JP package is supposed to be installable on any Magento version / edition

### Actual result

**Composer prompt this issue:**
_Root composer.json requires community-engineering/language-ja_jp 1.0.19, it is satisfiable by community-engineering/language-ja_jp[1.0.19] from composer repo (https://repo.packagist.org) but community-engineering/language-ja_jp[1.0.0] from composer repo (https://repo.magento.com) has higher repository priority. The packages from the higher priority repository do not match your constraint and are therefore not installable. That repository is canonical so the lower priority repo's packages are not installable. See https://getcomposer.org/repoprio for details and assistance._

![image](https://user-images.githubusercontent.com/16258478/181458494-49345882-5e32-470c-9dc6-fc3280f9cfe1.png)

FYI: This issue has been directly reported on the repository in 2021 -> https://github.com/magento-l10n/language-ja_JP/issues/1

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by HirokazuNishi** [comment] 2022-07-28 08:38
@zepgram as I commented on l10n repo, please use https://github.com/magentoj/language-ja_JP for 2.4.x .

**Comment by engcom-November** [comment] 2022-07-28 10:22
Hi @zepgram ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not reproduce the issue.
![image](https://user-images.githubusercontent.com/60198231/181481505-46f8cf22-7a7d-4c60-954f-7c5a7b425dff.png)
Also looks like this is not Magento related issue but the issue with 3rd party package: community-engineering/language-ja_jp:1.0.19. and code of this extension is not part of https://github.com/magento/magento2 git repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page.
Fyi.. japanese language package can be installed with mageplaza as well and is working fine on both community-edition and enterprise-edition as well. Please check.
```
composer require mageplaza/magento-2-japanese-language-pack:dev-master mageplaza/module-smtp 
php bin/magento setup:static-content:deploy ja_JP
php bin/magento indexer:reindex
php bin/magento cache:clean
php bin/magento cache:flush
```

**Comment by zepgram** [comment] 2022-07-28 10:42
The repository is published by https://github.com/magento-l10n with an Adobe address [magento-l10n@adobe.com](mailto:magento-l10n@adobe.com) I don't think this is a marketplace issue. It's a community project.

Installation of the package probably worked for you because you installed Magento with GIT.
You may install the project with composer to be able to reproduce.

Steps to reproduce:
1. `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition magento-composer`
2. `cd magento-composer`
3. `composer require community-engineering/language-ja_jp:1.0.19`

**Comment by engcom-November** [comment] 2022-08-01 12:09
Hi @zepgram , Thank you for the response.
[This](https://github.com/magento-l10n) is not part of our Magento [repositories.](https://github.com/orgs/magento/repositories) Only all questions, issue reports and fix related to https://github.com/magento/magento2 this git repository should be addressed here in this board. All questions / issue reports related to 3rd party package / extensions should be addressed to the corresponding extension owners(support)
Thank you.

**Comment by engcom-November** [comment] 2022-08-02 12:01
Hi @zepgram ,
I verified the issue again on both composer based installation 2.4.4. and 2.4-develop git installation and the issue is reproducible on composer based installation 2.4.4 (project-community-edition) but not on 2.4-develop git installation. So this issue may got fixed and resolved in 2.4-develop branch and it will be available in the next Magento release version.
Thank you.

**Comment by zepgram** [comment] 2022-08-02 12:26
The issue is totally reproductible if you use composer.

This is related to composer metapackage installation.

If you really want to prove that you are right then, go on branch 2.3-develop from git: **if you can install the package then it means there is a composer issue with the metapackage installation. **

If you cannot install the package then you are right and it will be solved on next 2.4 release.

-> You can't say it's fine if you install the package through git. You are not installing the real composer metapackage as you are supposed to...

**Comment by engcom-November** [comment] 2022-08-08 14:37
Hi @zepgram ,
We are able to install the package on both 2.3 git instance and 2.4-develop branch as well but cannot install the package on latest composer instance 2.4.4 project-community-edition. Hence we are confirming this issue.

**Comment by engcom-November** [comment] 2022-08-19 07:29
Hi @zepgram ,
We got the confirmation after internal discussions that Adobe Japan maintains https://repo.packagist.org/packages/magentoj/language-ja_jp and https://github.com/magentoj/language-ja_JP Localization packages but not https://github.com/magento-l10n/language-ja_JP. Kindly use the above repositories for ja_JP package installation and reopen / create new issue if you are facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-08-19 07:29 UTC
Labels: Issue: Confirmed, Component: Framework/Setup, Reproduced on 2.4.x, Priority: P1, Progress: done, Area: Install & Administer, Reported on 2.4.3-p2

**Comment by hostep** [comment] 2022-08-27 10:13
@engcom-November, Adobe definitely maintains all packages under https://github.com/magento-l10n

It's extremely weird that version 1.0.0 is the only one of `community-engineering/language-ja_jp` available on repo.magento.com, and all versions that were later created on github are not on repo.magento.com
All (?) other language packs under the `community-engineering` namespace are not published on repo.magento.com, so why did this happen with the Japanese one?

@sidolov, @sdzhepa , can you talk to the internal team to figure this out?

If the official answer is that a mistake was made with the `community-engineering/language-ja_jp` package and it can't be solved, so that people should use `magentoj/language-ja_jp` instead, then this needs to be clearly communicated. It should at least be mentioned in the README file of this repo: https://github.com/magento-l10n/language-ja_JP that this package is not the correct one and direct you to the correct on.

**Comment by zepgram** [comment] 2022-09-01 08:30
> Hi @zepgram , We got the confirmation after internal discussions that Adobe Japan maintains https://repo.packagist.org/packages/magentoj/language-ja_jp and https://github.com/magentoj/language-ja_JP Localization packages but not https://github.com/magento-l10n/language-ja_JP. Kindly use the above repositories for ja_JP package installation and reopen / create new issue if you are facing any issues. Thank you.

**magentoj** is not the correct namespace, you are offering to me a lazy answer, and it's bad.
Come on... please, do your job. You'll feel accompished at the end of the day.
