### ISSUE TITLE
500 response on customer email change on customer grid 

### ISSUE THREAD

**Issue by ajeetsinghcedcoss** [magento/magento2#22659] opened 2019-05-04 07:21 UTC
### Preconditions (*)

1. Magento 2.3.0
2. Mail is not setup on local host

### Steps to reproduce (*)

1. Create A customer from admin 
2. Edit Customer Email from admin customer grid
3. After edit customer Email click on save button 

### Expected result (*)

1. [Screenshots, logs or description]
2. Unable to send mail
3. Customer Save Successfully 

### Actual result (*)

1. [Screenshots, logs or description]
2.
![mail-failed_1](https://user-images.githubusercontent.com/36220521/57175512-91031d80-6e6a-11e9-919f-0f28bf0d73d9.png)

**Comment by ajeetsinghcedcoss** [comment] 2019-05-04 07:22
#dmcdindia1

**Comment by anujwebkul** [comment] 2019-05-04 12:07
@magento-engcom-team give me 2.2-develop

**Comment by anujwebkul** [comment] 2019-05-04 12:07
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-05-04 12:07
Hi @anujwebkul. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-05-04 12:08
Hi @anujwebkul, here is your [Magento instance](https://i-22659-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22659-2-2-develop.instances.magento-community.engineering/admin](https://i-22659-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by anujwebkul** [comment] 2019-05-04 12:12
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-05-04 12:12
Hi @anujwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-05-04 12:13
Hi @anujwebkul, here is your [Magento instance](https://i-22659-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22659-2-3-develop.instances.magento-community.engineering/admin](https://i-22659-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by anujwebkul** [comment] 2019-05-04 12:16
Not able to reproduce on both develop instances.

**Comment by shikhamis11** [comment] 2019-07-01 16:49
@ajeetsinghcedcoss I am closing this issue since it is not reproducible.

**Closed as completed by shikhamis11** 2019-07-01 16:49 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid, Event: dmcdindia1
