### ISSUE TITLE
The consumer isn't authorized to access %resources.

### ISSUE THREAD

**Issue by noiseymur** [magento/magento2#36811] opened 2023-02-07 09:52 UTC
### Summary

The account role is administrator and it has permissions for all the resources.

I create an integration with that account, I give it permissions for all the resources.

Using the integration tokens and username and password of the account I make a call to  `rest/V1/integration/admin/token` and receive an admin token.

Now when I use that admin token to access any resource, all I get is: "The consumer isn't authorized to access %resources."

And there isn't even a live support chat or something that I can ask Magento. We only have community support which is not enough. I haven't found a solution to this for two weeks now.

### Examples

URL: `https://www.sansoeurs.com/rest/V1/products`
This in headers:  `Authorization: "Bearer <admin-token-here>"`

This is what I get: 
```
{
    "message": "The consumer isn't authorized to access %resources.",
    "parameters": {
        "resources": "Magento_Catalog::products"
    }
}
```

### Proposed solution

I don't know

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-02-09 06:24
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-02-09 11:13
Hi @noiseymur,


Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


Call `rest/V1/integration/admin/token`


<img width="1157" alt="Screenshot 2023-02-09 at 1 11 10 PM" src="https://user-images.githubusercontent.com/51680745/217796926-f84a9969-68e2-4c68-a250-d13eb59d8e45.png">



Call URL: `https://www.sansoeurs.com/rest/V1/products`.We are able to retrieve the details of the product.


<img width="1123" alt="Screenshot 2023-02-09 at 1 11 21 PM" src="https://user-images.githubusercontent.com/51680745/217797133-f555bbc5-ec09-4cd9-83ce-272b6017e078.png">



Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by noiseymur** [comment] 2023-02-09 11:27
Hello. Thanks for the answer. But I see that the token you get from `rest/V1/integration/admin/token` is a long one. The token I get from that endpoint is only 32 characters long. Am I getting a wrong token ? And if yes, what can be the issue ?

Also can I see the authorization part of the request for admin token ?

**Comment by engcom-Bravo** [comment] 2023-02-13 11:39
Hi @noiseymur,

Thanks for your update.

we will use below payload for admin token to access resources for admin.


```
{
  "username": "string",
  "password": "string"
}
```



There is no authorization required for admin token.


Kindly go through with this document https://developer.adobe.com/commerce/webapi/get-started/authentication/gs-authentication-token/ for admin token and let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-02-24 12:22
Hi @noiseymur,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-02-24 12:22 UTC
Labels: Issue: needs update, Reported on 2.4.x
