### ISSUE TITLE
2.1.2 CE WEBAPI: product is assigned to all websites if store_code 'all' is used by SOAP request

### ISSUE THREAD

**Issue by ericahoekerd** [magento/magento2#7204] opened 2016-10-27 07:31 UTC
Magento 2.1.2

If we send a XML request (see attachment) with store code 'all', the product is assigned to all available websites. This is a bug. We set the store to 'all' beacuse the description and attributes should be global available. If we use a specific store_code this is not happening.

With the webservice method 'catalogProductWebsiteLinkRepositoryV1SaveRequest' the assignment for a product to websites will be done. This is working ok.

[product_save_request.zip](https://github.com/magento/magento2/files/555194/product_save_request.zip)

**Comment by veloraven** [comment] 2016-10-27 12:50
@tinxit thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by ericahoekerd** [comment] 2016-10-27 13:25
are you reading the issue? magento 2.1.2 as mentioned, check the zip all info is in.

**Comment by veloraven** [comment] 2016-11-23 08:18
@tinxit please follow the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).
It is much easier to understand what the problem is and how to reproduce it when the description is well structured and contains sections with steps, actual result and expected result.
Additionally it increases chances that other users with the same problem will find your issue.

**Comment by ericahoekerd** [comment] 2016-12-12 13:24
PROBLEM: product is assigned to all websites although it is not part of the XML request (see zip file)

EXPECTED result: no website should be assigned when a product is saved without any websites in request

REPRODUCE: by creating the same soap request as in the zip file

**Comment by sschurink** [comment] 2017-06-22 14:24
Problem still persists. Please fix it:

## Prerequisites
Magento ver. 2.1.5 multistore stores 1,2,3,4
Example:
ProductA only exists in stores 1 and 2

## Steps to reproduce
Update description for ProductA for stores 1 and 2 
/index.php/rest/all/V1/products/ProductA 

## Expected Result
ProductA is updated in store 1 and 2

## Actual Result
ProductA is updated in store 1 and 2 **AND added to store 3 and 4**


## Suggested alternative
**OR give an API route to only edit admin (store_id = 0) values**
/index.php/rest/**admin**/V1/products/ProductA

**Comment by sschurink** [comment] 2017-07-03 09:56
Is there a date set for the estimated fix?

**Comment by magento-engcom-team** [comment] 2017-10-20 09:30
@tinxit, thank you for your report.
We've created internal ticket(s) MAGETWO-82391 to track progress on the issue.

**Comment by magento-engcom-team** [comment] 2018-09-07 13:59
Hi @tinxit 
This issue seems to be fixed now, as we could not reproduce it with 2.2.5.

Please reopen if the issue persists. Thank you.

**Closed as completed by magento-engcom-team** 2018-09-07 13:59 UTC
Labels: Issue: Ready for Work, bug report, Component: Framework/Webapi, Issue: Confirmed, Issue:  Cannot Reproduce, Issue: Format is not valid, Fixed in 2.4.x, Priority: P3, Progress: done

**Comment by magento-engcom-team** [comment] 2021-02-19 08:45
Hi @tinxit. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24738` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
