### ISSUE TITLE
Can't add product with non-required Customizable Options File to Cart

### ISSUE THREAD

**Issue by bylli79** [magento/magento2#35073] opened 2022-02-09 14:16 UTC
### Preconditions (*)

1. Magento 2.4.1
2. PHP 7.4.21
3. Mariadb 10.4.21

### Steps to reproduce (*)
Best wishes to all the community of Magento programmers and users.
 I have a problem with Magento 2.4.1 and I hope someone will help me solve it.
 I have created configurable products with variants (for example color). To these products I have added Customizable Options, one of which is of the file type. When I add a product, after choosing the color and adding a note, if I do add to cart, in the frontend I have no problem: everything works.
If, on the other hand, in addition to the color and the note, I add a file, I get the following error:
"the product's required option (s) weren't entered. Make sure the options are entered and try again."

![image](https://user-images.githubusercontent.com/25764508/153215092-edfc319f-6a32-41a1-bb87-f75d84efcdfc.png)

![image](https://user-images.githubusercontent.com/25764508/153215316-5d5c5248-07d2-44ae-b728-379fda44a892.png)

![image](https://user-images.githubusercontent.com/25764508/153215414-6e7114a3-196c-406c-b3ff-1ce619afa60a.png)

### Expected result (*)

Product is added to cart

### Actual result (*)

![image](https://user-images.githubusercontent.com/25764508/153216319-bc491b15-12a3-42ca-bebc-2ed5e083eb91.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment] 2022-02-11 13:29
Hi @bylli79,

Thank you for reporting the issue.
We tried reproducing the issue on 2.4-develop however the issue is not reproducible.

Steps followed to reproduce the issue:

1. Install fresh Magento 2.4-develop instance
2. Add configurable product with **eg: color** as configurable option.
3. Add 3 customisable options **Note (TextArea), Vector(Radio Button), LoadFile (File Type)**
![Screenshot from 2022-02-11 18-54-48](https://user-images.githubusercontent.com/60198022/153599729-a936e9f1-ec6b-42e1-86c7-25da39898f34.png)

4. Go to the frontend and place order with adding a **File** to the product.
![Screenshot from 2022-02-11 18-56-01](https://user-images.githubusercontent.com/60198022/153599567-b8325be0-8aaa-4ee6-a1cf-e5203d9958bd.png)

**Result:**
Order is placed successfully.
![Screenshot from 2022-02-11 18-58-04](https://user-images.githubusercontent.com/60198022/153599802-4990e512-9881-4289-b7dd-2d5112bb6a9c.png)


We were able to place order successfully **with and without file**.
Please let us know in case we are missing anything with exact reproducible steps, will retry with that scenario.

Thanks!

**Comment by engcom-Hotel** [comment] 2022-02-25 08:21
Dear @bylli79,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-02-25 08:21 UTC
Labels: Issue: needs update, Reported on 2.4.1, Area: Product
