### ISSUE TITLE
Mass Shipping Label Generation issue

### ISSUE THREAD

**Issue by manan-india** [magento/magento2#35518] opened 2022-05-23 10:38 UTC
### Summary (*)
After placing an order from fedex shipping and generating the shipment, try mass shipping label generation

### Examples (*)
![Screenshot from 2022-05-23 12-57-26](https://user-images.githubusercontent.com/66308781/169814756-cbccc9a6-913e-4d4e-b251-c3d51ddf38bf.png)

![Screenshot from 2022-05-23 12-57-24](https://user-images.githubusercontent.com/66308781/169801650-e3ce4b33-8e47-47bd-aa3e-b9b7440abefe.png)
9c-3760
![Screenshot from 2022-05-23 12-56-55](https://user-images.githubusercontent.com/66308781/169801665-bb002e3b-1c84-419d-8b03-5aaad218de88.png)
9be1b
![Screenshot from 2022-05-23 12-56-48](https://user-images.githubusercontent.com/66308781/169801671-9a8371d3-59f0-4701-ba74-289487f36eae.png)
32c.png)

### Proposed solution
Fixed this issue: https://github.com/magento/zf1/issues/44

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment] 2022-06-05 15:06
This was fixed like this in the [ZF1-Future project](https://github.com/Shardj/zf1-future):
https://github.com/Shardj/zf1-future/commit/5ae9f922ca97bd59a7f70e5c2efb10b360eae331#diff-095112f5539b15e75b91f6100ae0439d924c83297d92bcf8b8f413d429280638

Magento should probably fix this as well in their [own zf1 fork](https://github.com/magento/zf1).

**Comment by engcom-November** [comment] 2022-06-06 14:22
Hi @manan-india ,
Thank you for reporting. This issue is a duplicate of https://github.com/magento/magento2/issues/35335 for which PR is in progress. We are closing this issue. Please move on to https://github.com/magento/magento2/issues/35335 for latest updates / solutions. 
Thank you.

**Closed as completed by engcom-November** 2022-06-06 14:22 UTC
Labels: duplicate, Triage: Dev.Experience, Issue: ready for confirmation
