### ISSUE TITLE
Product add form is not displaying in 2.1.7

### ISSUE THREAD

**Issue by melwinVincent** [magento/magento2#10251] opened 2017-07-16 08:40 UTC
Could you please guide me to figure out the reason why the "product-add-form" portion is not coming on adding a simple product in Magento 2.1.7 . The same is coming in 2.0.15 version. In 2.1.7, <div class="product-add-form" is not present in between <div class="product-info-price" and <div class="product-social-links" 

I have done -> 
**cache:flush**, 
**indexer:reindex**, 
**setup:static-content:deploy** 

Attaching screenshots for your reference

 **2.0.15**
![2 0 15](https://user-images.githubusercontent.com/12426903/28246031-f8daae34-6a23-11e7-8775-5ea4c7761310.png)

**2.1.7**
![2 1 7](https://user-images.githubusercontent.com/12426903/28246032-fb079f64-6a23-11e7-9af5-a06b5ae467cc.png)

**Comment by melwinVincent** [comment] 2017-07-16 11:21
someone please help

**Comment by SanderJP** [comment] 2017-07-17 14:26
@melwinVincent please read the guidelines (https://github.com/magento/magento2/wiki/Issue-reporting-guidelines), specifically: `Before creating an issue ...`. You can ask this question on something like the Magento stackexchange: https://magento.stackexchange.com/
If this problem exists on a clean Magento 2.1.7 instance, rewrite the report to re-produce the issue.

**Comment by melwinVincent** [comment] 2017-07-17 15:17
@SanderJP Done.
https://magento.stackexchange.com/questions/184138/product-add-form-is-not-displaying-in-2-1-7

**Comment by SanderJP** [comment] 2017-07-17 16:53
Nice, you can close this issue then.

**Comment by veloraven** [comment] 2017-07-24 08:39
@melwinVincent thank you for your feedback.
Do I understand right that the problem was resolved and the issue can be closed?

**Comment by melwinVincent** [comment] 2017-07-25 11:15
no @veloraven , still the issue is present. the issue is still open.

**Comment by magento-engcom-team** [comment] 2017-09-21 08:25
Hello @melwinVincent. We can not reproduce Your issue. What we did was:
1) installed an appropriate version of Magento  **_Community Edition_**;
2) created a simple product in backend;
3) went to a product page on the storefront.
As a result the "product-add-form" is on its right place. Please specify, what have we missed from what You have done?
![screenshot_8](https://user-images.githubusercontent.com/31669971/30685903-8a2a61fe-9ec7-11e7-85c2-d1fd7241a0a3.png)

**Comment by magento-engcom-team** [comment] 2017-10-11 16:40
@melwinVincent we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue

**Closed as completed by magento-engcom-team** 2017-10-11 16:40 UTC
Labels: Progress: needs update, Issue: Clear Description, Issue: Format is not valid
