### ISSUE TITLE
The order confirmation email is being sent twice when the purchase order is being placed

### ISSUE THREAD

**Issue by strell** [magento/magento2#37762] opened 2023-07-17 09:31 UTC
### Preconditions and environment

- Magento version 2.4.6
- magento/module-purchase-order module installed

### Steps to reproduce

- create a b2b company
- create a b2b user 
- configure the purchase orders 
- place the purchase order via graphql api or via frontend 

### Expected result

The order confirmation email was sent only once for the purchase order

### Actual result

The order confirmation email was sent twice

### Additional information

As was debugged the order confirmation is being sent as only the order was placed in the method `createSalesOrder -> placeOrder`  `Model/PurchaseOrderManagement.php:201`  using the `Magento\Quote\Api\CartManagementInterface`

When the order was placed using this service the order confirmation email would be sent by the event handler/observer.
Additionally, the email sending will be triggered directly inside the `createSalesOrder` method at line 232 `$this->orderEmailSender->send($order);`, at the same time, the `email_sent` flag was not checked/verified.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-07-20 10:19
Hi @strell,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance with EE edition and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- create a b2b company
- create a b2b user
- configure the purchase orders
- place the purchase order via graphql api or via frontend



<img width="1313" alt="Screenshot 2023-07-20 at 12 32 40 PM" src="https://github.com/magento/magento2/assets/51680745/4b331d0a-c5d0-4727-a660-9c40dfab455b">




![Order-000000001](https://github.com/magento/magento2/assets/51680745/38c5b6db-4634-4bee-9372-afe29a21b375)



The order confirmation email was sent only once for the purchase order.Please let us know still if we are missing anything.

Kindly recheck the behaviour on Magento 2.4-develop instance with EE edition and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-08-01 07:26
Hi @strell,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-08-01 07:26 UTC
Labels: Issue: needs update, Reported on 2.4.6
