### ISSUE TITLE
Magento 2.1.4 Cart Rule Issue

### ISSUE THREAD

**Issue by jayanta88** [magento/magento2#16913] opened 2018-07-18 15:41 UTC
### Preconditions
Magento 2.1.4

### Steps to reproduce
1. Navigate to admin area Marketing > Cart Price Rules
2. Create new price rule. Set "Uses per Customer" = 1. "Discount Amount" = 10%
3. Create simple product.
4. Navigate to storefront and create customer.
5. Buy simple product as registered customer and proceed to checkout.
6. Check Discount applied.
7. Place order.
8. Navigate to admin area Sales > Orders.
9. Cancel created order.
10. Navigate to storefront buy simple product as registered customer and proceed to checkout.

### Expected result
Discount should applied.

### Actual result
Discount doesn't apply.

**Comment by magento-engcom-team** [comment] 2018-07-18 15:42
Hi @jayanta88. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@jayanta88 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment] 2018-07-19 09:04
Hello @jayanta88, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2018-07-29 17:13
Hi @jayanta88 
We are closing this report now, as the issue was fixed in 2.2

**Closed as completed by magento-engcom-team** 2018-07-29 17:13 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: SalesRule

**Comment by jayanta88** [comment] 2018-07-30 06:39
Hi,
Thanks for looking into it. Could you please give me the link of files you fixed for this. So that I can update this in my current version.

Thanks
