### ISSUE TITLE
Double store credit refunds when a error is received before redirecting to external psp.

### ISSUE THREAD

**Issue by leonhelmus** [magento/magento2#38815] opened 2024-06-10 12:45 UTC
### Preconditions and environment

Adobe Commerce: 2.4.6-p4
php 8.1

### Steps to reproduce

- First create a customer where you add store credit (magento_customerbalance).
- Than add a product which you can pay of partially or full with store credit.
- Than it could trigger a error from an external psp.
- In magento the order has been processed even though this error was given back.
I get twice as much store credit back.

### Expected result

I get my store credit back, but not doubled.

### Actual result

I get two times as much store credit back.

### Additional information

**Additional info**
If this function (\Magento\Quote\Model\QuoteManagement::submitQuote) receives an error of an external psp after the order has been created Magento will rollbackAddresses using this function: \Magento\Quote\Model\QuoteManagement::rollbackAddresses.

This than triggers the dispatch the event `sales_model_service_quote_submit_failure` which in turn invokes this observer:
\Magento\CustomerBalance\Observer\RevertStoreCreditObserver::execute

Afterwards on the same event the external psp has this event:
```
    <event name="sales_model_service_quote_submit_failure">
        <observer name="external_psp_failed_quote_order" instance="Example\Magento2\Observer\HandleFailedQuoteOrder"/>
    </event>
```
Which triggers a cancellation of the order which triggers this function (\Magento\Sales\Model\Order::cancel) Which adds the following event `order_cancel_after` which triggers the same observer again:
\Magento\CustomerBalance\Observer\RevertStoreCreditObserver::execute

**In my opinion \Magento\CustomerBalance\Observer\RevertStoreCreditForOrder should check if the customer has already received a refund of store balance and if this has already been triggered it should skip saving an additional time.**
This is prone to add issues since it does not check if it has already refunded the store credit on quote level or order level.

Workaround fix/ patch
```
# Prevent double refund of store credit.
#
# Github link: https://github.com/magento/magento2/issues/38815
# Github link: https://github.com/buckaroo-it/Magento2/issues/989

diff --git a/Observer/RevertStoreCreditForOrder.php b/Observer/RevertStoreCreditForOrder.php
--- a/Observer/RevertStoreCreditForOrder.php
+++ b/Observer/RevertStoreCreditForOrder.php
@@ -5,6 +5,11 @@
  */
 namespace Magento\CustomerBalance\Observer;

+use Magento\CustomerBalance\Model\Balance\History;
+use Magento\CustomerBalance\Model\Balance\History as BalanceHistory;
+use Magento\CustomerBalance\Model\ResourceModel\Balance\History\Collection as HistoryCol;
+use Magento\CustomerBalance\Model\ResourceModel\Balance\History\CollectionFactory as HistoryColFactory;
+
 /**
  * Customer balance observer
  */
@@ -28,7 +33,8 @@
      */
     public function __construct(
         \Magento\CustomerBalance\Model\BalanceFactory $balanceFactory,
-        \Magento\Store\Model\StoreManagerInterface $storeManager
+        \Magento\Store\Model\StoreManagerInterface $storeManager,
+        private readonly HistoryColFactory $historyColFactory,
     ) {
         $this->_balanceFactory = $balanceFactory;
         $this->_storeManager = $storeManager;
@@ -45,6 +51,32 @@
         if (!$order->getCustomerId() || !$order->getBaseCustomerBalanceAmount()) {
             return $this;
         }
+
+        if (!$order->getBaseCustomerBalanceInvoiced()) {
+            /** @var HistoryCol $historyCol */
+            $historyCol = $this->historyColFactory->create();
+            /** @var BalanceHistory $history */
+            $history = $historyCol->addFieldToFilter(
+                'customer_id',
+                ['eq' => $order->getCustomerId()]
+            )->addFieldToFilter(
+                'website_id',
+                ['eq' => $this->_storeManager->getStore($order->getStoreId())->getWebsiteId()]
+            )->addFieldToFilter(
+                'balance_delta',
+                ['eq' => $order->getBaseCustomerBalanceAmount()]
+            )->addFieldToFilter(
+                'action',
+                ['eq' => History::ACTION_REVERTED]
+            )->addFieldToFilter(
+                'additional_info',
+                ['like' => '%' . $order->getIncrementId() . '%']
+            )->getFirstItem();
+
+            if ($history->getId()) {
+                return $this;
+            }
+        }

         $customerAmountDelta = $order->getBaseCustomerBalanceAmount() - $order->getBaseCustomerBalanceInvoiced();

```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2024-07-18 13:42
Hi @leonhelmus 

Thanks for reporting and collaboration.

Verified the issue on Magento 2.4.7-p1 but the issue is not reproducible.

Steps to reproduce
First create a customer where you add store credit (magento_customerbalance).
Than add a product which you can pay of partially or full with store credit.
Than it could trigger a error from an external psp.
In magento the order has been processed even though this error was given back.
I get twice as much store credit back.

I am getting the store credit back, but not doubled.

Please refer the attached screenshots.

Customer store credit in admin

<img width="1440" alt="Screenshot 2024-07-17 at 3 39 56 PM" src="https://github.com/user-attachments/assets/5e6082fd-fb84-4e31-b8ce-47e431d65e53">

Placing the order with partial store credit and partially with Paypal and the error is triggered

<img width="1440" alt="Screenshot 2024-07-17 at 3 38 59 PM" src="https://github.com/user-attachments/assets/3078e2b4-cded-468d-8ff4-cd6c1f0f0014">

<img width="1440" alt="Screenshot 2024-07-17 at 3 40 43 PM" src="https://github.com/user-attachments/assets/36383586-9f3b-412c-8586-16025bbfb0d7">

Refund received

<img width="1440" alt="Screenshot 2024-07-17 at 3 41 29 PM" src="https://github.com/user-attachments/assets/4e77cdc5-2390-4abb-8939-c4ce2cd11ca6">

**Comment by engcom-Dash** [comment] 2024-07-29 13:07
Hi @leonhelmus 

We have noticed that this issue has not been updated for a long time. Hence we assume this issue is fixed, so we are closing it. Please feel free to raise a fresh ticket or reopen this ticket if you need more assistance.

Thanks.

**Closed as completed by engcom-Dash** 2024-07-29 13:07 UTC
Labels: Issue: needs update, Reported on 2.4.6-p4
