### ISSUE TITLE
Mutliselect product attribute with source model not in flat table

### ISSUE THREAD

**Issue by adi3009** [magento/magento2#13751] opened 2018-02-20 15:49 UTC
On creating a product attribute of type multiselect using `Magento\Catalog\Api\ProductAttributeRepositoryInterface` and setting a custom source model for options, magento does not create an attribute column in flat table after reindex, when flat catalog (products) is enabled. This prevents filtering product collection by the attribute values.

### Preconditions

1. Magento version 2.2.2 (vanilla installation with sample data)
2. PHP Version - PHP 7.1.12
3. MySql version - 5.6.33
4. OS - Ubuntu 14.04.1
5. enable flat catalog (Stores -> Configuration -> Catalog -> Catalog -> Use Flat Catalog Product)

### Steps to reproduce
1. Copy following repo (https://github.com/adi3009/m2-attribute-import-bug) code to installation directory. The repo contains custom modules for importing product attributes from csv and will create an example `test_multiselect` attribute.
2. Do `./bin/magento setup:upgrade` - this should create a db table `smart_catalog_test_multiselect`
3. Import attributes from csv in var/importexport/attr.csv `./bin/magento smart:import:product-attributes importexport/attr.csv importexport/attr/`
4. verify that attribute `test_multiselect` is created and is used in product listing
5. Reindex `./bin/magento index:reindex`

### Expected result
1. table `catalog_product_flat_1` should have a column `test_multiselect`
2. Product collection should be filterable by `test_multiselect`, i.e. `$collection->addAttributeToFilter('test_multiselect`, ['in' => [1, 2, 3]])` should update sql query for product collection.

### Actual result
1. table `catalog_product_flat_1` does not have the column `test_multiselect`
2. Product collection not filterable by `test_multiselect`

**Comment by magento-engcom-team** [comment] 2018-02-21 16:30
@adi3009, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by adampmoss** [comment] 2018-04-26 15:02
I had the same exact issue and it was due to how my source model was created. I looked at the following source model and noticed that mine had some missing methods: `Magento\Eav\Model\Entity\Attribute\Source\Table`. I added these methods to my source model and it worked.

```
/**
     * Retrieve Column(s) for Flat
     *
     * @return array
     */
    public function getFlatColumns()
    {
        $columns = [];
        $attributeCode = $this->getAttribute()->getAttributeCode();
        $isMulti = $this->getAttribute()->getFrontend()->getInputType() == 'multiselect';

        $type = $isMulti ? \Magento\Framework\DB\Ddl\Table::TYPE_TEXT : \Magento\Framework\DB\Ddl\Table::TYPE_INTEGER;
        $columns[$attributeCode] = [
            'type' => $type,
            'length' => $isMulti ? '255' : null,
            'unsigned' => false,
            'nullable' => true,
            'default' => null,
            'extra' => null,
            'comment' => $attributeCode . ' column',
        ];
        if (!$isMulti) {
            $columns[$attributeCode . '_value'] = [
                'type' => \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
                'length' => 255,
                'unsigned' => false,
                'nullable' => true,
                'default' => null,
                'extra' => null,
                'comment' => $attributeCode . ' column',
            ];
        }

        return $columns;
    }

    /**
     * Retrieve Indexes for Flat
     *
     * @return array
     */
    public function getFlatIndexes()
    {
        $indexes = [];

        $index = sprintf('IDX_%s', strtoupper($this->getAttribute()->getAttributeCode()));
        $indexes[$index] = ['type' => 'index', 'fields' => [$this->getAttribute()->getAttributeCode()]];

        $sortable = $this->getAttribute()->getUsedForSortBy();
        if ($sortable && $this->getAttribute()->getFrontend()->getInputType() != 'multiselect') {
            $index = sprintf('IDX_%s_VALUE', strtoupper($this->getAttribute()->getAttributeCode()));

            $indexes[$index] = [
                'type' => 'index',
                'fields' => [$this->getAttribute()->getAttributeCode() . '_value'],
            ];
        }

        return $indexes;
    }

    /**
     * Retrieve Select For Flat Attribute update
     *
     * @param int $store
     * @return \Magento\Framework\DB\Select|null
     */
    public function getFlatUpdateSelect($store)
    {
        return $this->_attrOptionFactory->create()->getFlatUpdateSelect($this->getAttribute(), $store);
    }
```

**Comment by adi3009** [comment] 2018-08-13 15:10
@adampmoss thanks for your suggestion, extending from Magento\Eav\Model\Entity\Attribute\Source\Table solves thus issue, however the attribute is not filterable, i.e. does not appear in layered navigation when mysql backend is used for search.

**Comment by engcom-Bravo** [comment] 2020-01-02 13:45
Hello @adi3009 
We have rechecked this issue on Magento 2.4-develop and can not reproduce it
The Attributes contain the new _test_multiselect_
![attribute](https://user-images.githubusercontent.com/51680745/71669566-bc316a00-2d75-11ea-80cc-d2185dfc05b3.png)
And the **catalog_product_flat_1** table contains **test_multiselect** column 
![test_multiselect](https://user-images.githubusercontent.com/51680745/71669749-71fcb880-2d76-11ea-9f46-d70adbb34763.png)

So we close this issue.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) .
Thank you for collaboration.

**Closed as completed by engcom-Bravo** 2020-01-02 13:45 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid
