### ISSUE TITLE
ACL - swatch image upload responds 403

### ISSUE THREAD

**Issue by ankitce** [magento/magento2#6376] opened 2016-08-29 12:18 UTC
Tested in Magento version **2.1.0**
### Steps to reproduce
1. Create a new role with access to 'Attributes'. Create a new user to be associated with the newly created role.
2. Logout admin and login back with the recently added user credentials. 
3. Try to upload swatch image for an attribute - say color.
### Expected result

It should set the image for the swatch if there is no error.
### Actual result
1. The page just reloads.
2. While reviewing the HTTP request, it shows 403 response code for the upload request. Seemingly `swatches/iframe/show` action should be allowed to the user.

**Comment by patruvlad** [comment] 2017-06-09 10:28
Any update on this issue? I just tested in version 2.1.7 and the issue is reproduced

**Comment by AlexWorking** [comment] 2017-06-29 11:13
Hello, @ankitce. An internal ticket MAGETWO-69830 was created according to Your issue. You'll be informed as the issue is fixed. Thanks for applying.

**Comment by magento-engcom-team** [comment] 2017-10-11 10:30
@ankitce, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by nathanjhastings** [comment] 2018-05-02 19:25
Having this issue in 2.1.12. Will there be a patch for 2.1.x?

**Comment by magento-engcom-team** [comment] 2018-07-30 06:15
Hi @ankitce

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment] 2018-08-20 08:51
@ankitce thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Closed as completed by magento-engcom-team** 2018-08-20 08:51 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Fixed in 2.3.x, Issue: Format is not valid, triage wanted
