### ISSUE TITLE
Can't edit cms page with page builder

### ISSUE THREAD

**Issue by thanhnguyen06011998** [magento/magento2#39052] opened 2024-08-16 10:34 UTC
### Preconditions and environment

- Magento version 2.4.7-p1
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

1. Create new cms page
2. add data in page builder
![image](https://github.com/user-attachments/assets/1ffeb87a-0d98-460e-8801-67627568dbf2)

### Expected result

![image](https://github.com/user-attachments/assets/b992148e-08f0-4353-9852-ee2ee3dfb399)

### Actual result

![image](https://github.com/user-attachments/assets/b8b3507b-2350-49e7-948e-fcb179d129ec)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-08-19 05:27
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-08-19 07:10
Hi @thanhnguyen06011998,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.



https://github.com/user-attachments/assets/8becf195-8e14-40f0-bd7e-1a1f3c5feeb1



We are able to edit and save the new CMS Page.

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-08-30 05:02
Hi @thanhnguyen06011998,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-08-30 05:02 UTC
Labels: Issue: needs update, Reported on 2.4.7-p1
