### ISSUE TITLE
Class does not exist error when viewing/createing customer record in admin

### ISSUE THREAD

**Issue by ghost** [magento/magento2#4841] opened 2016-06-03 01:51 UTC
Hi,

I've had to migrate from 1.5.1 to 1.9.2.3 to 2.0.7 CE. I'm using php 7.0.6 on mac 10.11.5.

The migration seems to have gone well. In the admin I can see all the customers in the customer grid but when i click on an individual customer to view their record (or add a new customer in admin or front end) i get the following error:

Class does not exist
#0 /Users/chris/Sites/git/magento/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('')
#1 /Users/chris/Sites/git/magento/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('')
#2 /Users/chris/Sites/git/magento/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('')
#3 /Users/chris/Sites/git/magento/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('', Array)
#4 /Users/chris/Sites/git/magento/vendor/magento/framework/Validator/UniversalFactory.php(36): Magento\Framework\ObjectManager\ObjectManager->create('', Array)
#5 /Users/chris/Sites/git/magento/vendor/magento/module-eav/Model/Entity/Attribute/AbstractAttribute.php(537): Magento\Framework\Validator\UniversalFactory->create(NULL)
#6 /Users/chris/Sites/git/magento/vendor/magento/module-customer/Model/Customer/DataProvider.php(164): Magento\Eav\Model\Entity\Attribute\AbstractAttribute->getSource()
#7 /Users/chris/Sites/git/magento/vendor/magento/module-customer/Model/Customer/DataProvider.php(104): Magento\Customer\Model\Customer\DataProvider->getAttributesMeta(Object(Magento\Eav\Model\Entity\Type))
#8 /Users/chris/Sites/git/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(114): Magento\Customer\Model\Customer\DataProvider->__construct('customer_form_d...', 'entity_id', 'id', Object(Magento\Ui\DataProvider\EavValidationRules), Object(Magento\Customer\Model\ResourceModel\Customer\CollectionFactory), Object(Magento\Eav\Model\Config), Object(Magento\Framework\View\Element\UiComponent\DataProvider\FilterPool), Array, Array)
#9 /Users/chris/Sites/git/magento/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\Custome...', Array)
#10 /Users/chris/Sites/git/magento/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\Custome...', Array)
#11 /Users/chris/Sites/git/magento/vendor/magento/framework/View/Element/UiComponent/Argument/Interpreter/ConfigurableObject.php(60): Magento\Framework\ObjectManager\ObjectManager->create('Magento\Custome...', Array)
#12 /Users/chris/Sites/git/magento/var/generation/Magento/Framework/Data/Argument/InterpreterInterface/Proxy.php(95): Magento\Framework\View\Element\UiComponent\Argument\Interpreter\ConfigurableObject->evaluate(Array)
#13 /Users/chris/Sites/git/magento/vendor/magento/framework/Data/Argument/Interpreter/Composite.php(61): Magento\Framework\Data\Argument\InterpreterInterface\Proxy->evaluate(Array)
#14 /Users/chris/Sites/git/magento/vendor/magento/module-ui/Model/Manager.php(191): Magento\Framework\Data\Argument\Interpreter\Composite->evaluate(Array)
#15 /Users/chris/Sites/git/magento/vendor/magento/module-ui/Model/Manager.php(194): Magento\Ui\Model\Manager->evaluateComponentArguments(Array)
#16 /Users/chris/Sites/git/magento/vendor/magento/module-ui/Model/Manager.php(175): Magento\Ui\Model\Manager->evaluateComponentArguments(Array)
#17 /Users/chris/Sites/git/magento/vendor/magento/framework/View/Element/UiComponentFactory.php(139): Magento\Ui\Model\Manager->prepareData('customer_form')
#18 /Users/chris/Sites/git/magento/vendor/magento/framework/View/Layout/Generator/UiComponent.php(124): Magento\Framework\View\Element\UiComponentFactory->create('customer_form', NULL, Array)
#19 /Users/chris/Sites/git/magento/vendor/magento/framework/View/Layout/Generator/UiComponent.php(93): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'customer_form', Array, Object(Magento\Framework\View\Layout\Interceptor))
#20 /Users/chris/Sites/git/magento/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#21 /Users/chris/Sites/git/magento/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#22 /Users/chris/Sites/git/magento/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#23 /Users/chris/Sites/git/magento/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#24 /Users/chris/Sites/git/magento/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#25 /Users/chris/Sites/git/magento/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#26 /Users/chris/Sites/git/magento/vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#27 /Users/chris/Sites/git/magento/vendor/magento/framework/View/Layout.php(859): Magento\Framework\View\Layout->build()
#28 /Users/chris/Sites/git/magento/var/generation/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#29 /Users/chris/Sites/git/magento/vendor/magento/module-backend/Model/View/Result/Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#30 /Users/chris/Sites/git/magento/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Custome...')
#31 /Users/chris/Sites/git/magento/vendor/magento/module-customer/Controller/Adminhtml/Index/Edit.php(126): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Custome...')
#32 /Users/chris/Sites/git/magento/var/generation/Magento/Customer/Controller/Adminhtml/Index/Edit/Interceptor.php(24): Magento\Customer\Controller\Adminhtml\Index\Edit->execute()
#33 /Users/chris/Sites/git/magento/vendor/magento/framework/App/Action/Action.php(102): Magento\Customer\Controller\Adminhtml\Index\Edit\Interceptor->execute()
#34 /Users/chris/Sites/git/magento/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#35 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#36 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#37 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Customer\Controller\Adminhtml\Index\Edit\Interceptor->___callParent('dispatch', Array)
#38 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Custome...', 'dispatch', Object(Magento\Customer\Controller\Adminhtml\Index\Edit\Interceptor), Array, 'adminAuthentica...')
#39 /Users/chris/Sites/git/magento/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#40 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Customer\Controller\Adminhtml\Index\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#41 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#42 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Custome...', 'dispatch', Object(Magento\Customer\Controller\Adminhtml\Index\Edit\Interceptor), Array, 'designLoader')
#43 /Users/chris/Sites/git/magento/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#44 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Customer\Controller\Adminhtml\Index\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#45 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#46 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Custome...', 'dispatch', Object(Magento\Customer\Controller\Adminhtml\Index\Edit\Interceptor), Array, 'adminMassaction...')
#47 /Users/chris/Sites/git/magento/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Customer\Controller\Adminhtml\Index\Edit\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#48 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Customer\Controller\Adminhtml\Index\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#49 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#50 /Users/chris/Sites/git/magento/var/generation/Magento/Customer/Controller/Adminhtml/Index/Edit/Interceptor.php(39): Magento\Customer\Controller\Adminhtml\Index\Edit\Interceptor->___callPlugins('dispatch', Array, Array)
#51 /Users/chris/Sites/git/magento/vendor/magento/framework/App/FrontController.php(55): Magento\Customer\Controller\Adminhtml\Index\Edit\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#52 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#53 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#54 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#55 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#56 /Users/chris/Sites/git/magento/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#57 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#58 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#59 /Users/chris/Sites/git/magento/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#60 /Users/chris/Sites/git/magento/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#61 /Users/chris/Sites/git/magento/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#62 /Users/chris/Sites/git/magento/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#63 {main}

I've reindexed and cleaned and flushed the cache:

Customer Grid index has been rebuilt successfully in 00:00:04
Category Products index has been rebuilt successfully in 00:00:00
Product Categories index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:03
Product EAV index has been rebuilt successfully in 00:00:00
Stock index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:13
Catalog Product Rule index has been rebuilt successfully in 00:00:14
Catalog Search index has been rebuilt successfully in 00:00:01
Cleaned cache types:
config
layout
block_html
collections
reflection
db_ddl
eav
config_integration
config_integration_api
full_page
translate
config_webservice

debug and exception log don't have any entries. In system log i have this:

[2016-06-02 02:56:49] main.INFO: Cache file with merged layout: LAYOUT_adminhtml_STORE1_35bd6461434d92f073fe2439ed2163ba1: Please correct the XML data and try again. [] []
[2016-06-02 02:56:49] main.INFO: Cache file with merged layout: LAYOUT_adminhtml_STORE1_3793edbdc1c00dd1c3aa9e1b3dc856b39: Please correct the XML data and try again. [] []
[2016-06-02 02:56:49] main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2016-06-02 02:56:49] main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2016-06-02 02:56:49] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []
[2016-06-02 02:56:49] main.INFO: Cache file with merged layout: LAYOUT_adminhtml_STORE1_36f1b068ec7ccf4878f9284dd1137afd1: Please correct the XML data and try again. [] []

This is the error message when trying to create a new account on the frontend:

[2016-06-03 02:04:52] main.CRITICAL: Exception message: Class  does not exist
Trace: #0 /Users/chris/Sites/git/magento/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('')
#1 /Users/chris/Sites/git/magento/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('')
#2 /Users/chris/Sites/git/magento/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('')
#3 /Users/chris/Sites/git/magento/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('', Array)
#4 /Users/chris/Sites/git/magento/vendor/magento/framework/Validator/UniversalFactory.php(36): Magento\Framework\ObjectManager\ObjectManager->create('', Array)
#5 /Users/chris/Sites/git/magento/vendor/magento/module-eav/Model/Entity/Attribute/AbstractAttribute.php(537): Magento\Framework\Validator\UniversalFactory->create(NULL)
#6 /Users/chris/Sites/git/magento/vendor/magento/module-customer/Model/AttributeMetadataConverter.php(66): Magento\Eav\Model\Entity\Attribute\AbstractAttribute->getSource()
#7 /Users/chris/Sites/git/magento/vendor/magento/module-customer/Model/Metadata/CustomerMetadata.php(61): Magento\Customer\Model\AttributeMetadataConverter->createMetadataAttribute(Object(Magento\Customer\Model\Attribute))
#8 /Users/chris/Sites/git/magento/vendor/magento/module-customer/Model/Metadata/CachedMetadata.php(63): Magento\Customer\Model\Metadata\CustomerMetadata->getAttributes('customer_accoun...')
#9 /Users/chris/Sites/git/magento/vendor/magento/module-customer/Model/Metadata/Form.php(148): Magento\Customer\Model\Metadata\CachedMetadata->getAttributes('customer_accoun...')
#10 /Users/chris/Sites/git/magento/vendor/magento/module-customer/Model/Metadata/Form.php(212): Magento\Customer\Model\Metadata\Form->getAttributes()
#11 /Users/chris/Sites/git/magento/vendor/magento/module-customer/Model/Metadata/Form.php(236): Magento\Customer\Model\Metadata\Form->getAllowedAttributes()
#12 /Users/chris/Sites/git/magento/vendor/magento/module-customer/Model/CustomerExtractor.php(68): Magento\Customer\Model\Metadata\Form->extractData(Object(Magento\Framework\App\Request\Http))
#13 /Users/chris/Sites/git/magento/vendor/magento/module-customer/Controller/Account/CreatePost.php(223): Magento\Customer\Model\CustomerExtractor->extract('customer_accoun...', Object(Magento\Framework\App\Request\Http))
#14 /Users/chris/Sites/git/magento/var/generation/Magento/Customer/Controller/Account/CreatePost/Interceptor.php(24): Magento\Customer\Controller\Account\CreatePost->execute()
#15 /Users/chris/Sites/git/magento/vendor/magento/framework/App/Action/Action.php(102): Magento\Customer\Controller\Account\CreatePost\Interceptor->execute()
#16 [internal function]: Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#18 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callParent('dispatch', Array)
#19 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'designLoader')
#20 /Users/chris/Sites/git/magento/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#21 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#23 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'contextPlugin')
#24 /Users/chris/Sites/git/magento/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#25 [internal function]: Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#27 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'customer-app-ac...')
#28 /Users/chris/Sites/git/magento/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#29 [internal function]: Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#30 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#31 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'storeCheck')
#32 /Users/chris/Sites/git/magento/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#33 [internal function]: Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#34 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#35 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'customer_accoun...')
#36 /Users/chris/Sites/git/magento/vendor/magento/module-customer/Controller/Plugin/Account.php(60): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#37 [internal function]: Magento\Customer\Controller\Plugin\Account->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#38 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#39 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'weee-app-action...')
#40 /Users/chris/Sites/git/magento/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#41 [internal function]: Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#42 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#43 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'tax-app-action-...')
#44 /Users/chris/Sites/git/magento/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#45 [internal function]: Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#46 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#47 /Users/chris/Sites/git/magento/var/generation/Magento/Customer/Controller/Account/CreatePost/Interceptor.php(39): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callPlugins('dispatch', Array, Array)
#48 /Users/chris/Sites/git/magento/vendor/magento/framework/App/FrontController.php(55): Magento\Customer\Controller\Account\CreatePost\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#49 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#50 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#51 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#52 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#53 /Users/chris/Sites/git/magento/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(89): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#54 [internal function]: Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#55 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#56 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#57 /Users/chris/Sites/git/magento/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#58 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#59 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#60 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#61 /Users/chris/Sites/git/magento/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#62 [internal function]: Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#63 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#64 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#65 /Users/chris/Sites/git/magento/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(68): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#66 [internal function]: Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#67 /Users/chris/Sites/git/magento/vendor/magento/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#68 /Users/chris/Sites/git/magento/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#69 /Users/chris/Sites/git/magento/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#70 /Users/chris/Sites/git/magento/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#71 /Users/chris/Sites/git/magento/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#72 {main} [] []

Any ideas?

Thanks,
Chris

**Comment by sevos1984** [comment] 2016-10-21 08:58
Try upgrade to latest magento version, run full reindex and clear all caches. Reply if this helps.

**Comment by sevos1984** [comment] 2016-11-07 12:43
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-11-07 12:43 UTC
Labels: bug report, Progress: needs update, Component: Customer, Issue: Format is not valid

**Comment by ghost** [comment] 2016-11-08 07:30
it seems fine in 2.1.2

**Comment by sehgal** [comment] 2017-11-10 12:14
Plugin class Magento\ConfigurableProduct\Controller\Adminhtml\Product\Initialization\Helper\Plugin\UpdateConfigurations doesn't exist

help to solve this problem 
this issue come while create new attribute
