### ISSUE TITLE
Main website label and main website store label not alignd proper overlapping in left navigation in admin panel during create New Cart Price Rule

### ISSUE THREAD

**Issue by ghoshsweta** [magento/magento2#20293] opened 2019-01-15 08:30 UTC
Main website label and main website store label not alignd proper overlapping in left navigation in admin panel during create New Cart Price Rule

### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.2

### Steps to reproduce (*)
Step 1: Login to admin panel
Step 2: Go to marketing link from left navigation 
     2.a: Click on cart price rules link
     2.b: click on add new rule
     2.c: Go to Labels tab (Ref screenshot)

### Expected result (*)

![sol](https://user-images.githubusercontent.com/25763126/51167957-ee7c5a00-18cd-11e9-9ab2-b031a8690432.png)

### Actual result (*)

![issue](https://user-images.githubusercontent.com/25763126/51167963-f4723b00-18cd-11e9-9ac8-31b16935a723.png)

**Comment by magento-engcom-team** [comment] 2019-01-15 08:31
Hi @swetacedcoss. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@swetacedcoss do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-15 08:31
Hi @cedarvinda. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by cedarvinda** [comment] 2019-01-15 08:31
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-01-15 08:32
Hi @cedarvinda. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-01-15 08:32
Hi @cedarvinda, here is your [Magento instance](https://i-20293-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20293-2-3-develop.instances.magento-community.engineering/admin](https://i-20293-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-01-15 08:36
@cedarvinda Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97632` were created

**Comment by Karlasa** [comment] 2019-05-06 16:53
Will close this issue as we have duplicates  (#19647) and that one has PR in progress

**Closed as completed by Karlasa** 2019-05-06 16:53 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Admin
