### ISSUE TITLE
Magento 2.x.x - Configurable.js not consider currency on _calculatePrice function

### ISSUE THREAD

**Issue by walterbak** [magento/magento2#12680] opened 2017-12-13 17:03 UTC
When I select an option in Configurable product with a currentCurrency different from baseCurrency, the product page show the final price with the value of the baseCurrency with the symbol of currentCurrency.

**Preconditions**
- Magento 2.1.11
- PHP 7
- Mac OS

**Steps to reproduce**
- Set 2 currency in the store (EUR and USD);
- Set EUR as default currency.
- Create a configurable product, with some simple products with same price (i.e. 10 €)
- Create a Price Rule in Catalog do have 30% of discount for all products;
- Update currency rate (i.e.: EUR 1 -> USD: 1.1649)
- Select USD as currency in frontend
- Go to the configurable product page

**Expected result**
- In product page, I see the product price of 8.15$;
- If I select an option (simple product), i should see the product price of 8.15$;

**Actual result**
- In product page, i see the product price of 8.15$;
- If I select an option (simple product), the product price change in 7.00$.

**My debug and supposed reason**
In magento/module-configurable-product/view/frontend/web/js/configurable.js, line 486, the function _calculatePrice read the variable newPrice in the baseCurrency, and not convert it in the currentCurrency value.

**Comment by magento-engcom-team** [comment] 2017-12-19 13:36
@walterbak, thank you for your report.
The issue is already fixed in 2.2.2

**Closed as completed by magento-engcom-team** 2017-12-19 13:36 UTC
Labels: Issue: Confirmed, Fixed in 2.2.x, Issue: Format is valid
