### ISSUE TITLE
UI validation rule for valid time am/pm doesn't work when js is minified

### ISSUE THREAD

**Issue by markshust** [magento/magento2#17648] opened 2018-08-16 18:37 UTC
### Preconditions
1. Magento 2.2.5

### Steps to reproduce
1. Run SQL: `update core_config_data set value = 1 where path = 'dev/js/minify_files'`
2. `bin/magento deploy:mode:set production`
3. Run production compilation scripts
4. Try to save a ui component that validates against `time12h`

### Expected result

1. The input field should validate against the `time12h` validation rule

### Actual result
1. There is a javascript error that happens when the js is minified. The space in the validation rule is stripped.

**Comment by magento-engcom-team** [comment] 2018-08-16 18:37
Hi @markoshust. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@markoshust do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment] 2018-08-17 06:48
Hello @markoshust, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2018-08-18 11:10
Hi @markoshust. Thank you for your report. 
The issue has been fixed in magento/magento2#17652 by @markoshust in 2.2-develop branch
Related commit(s):
 - [99a616d683778f3ab5298074ba29200f0ecc8fa8](https://github.com/magento/magento2/commit/99a616d683778f3ab5298074ba29200f0ecc8fa8)
 - [317545a811c492955d58c5d3afe3a6e466a4b6fb](https://github.com/magento/magento2/commit/317545a811c492955d58c5d3afe3a6e466a4b6fb)

The fix will be available with the upcoming 2.2.7 release.

**Closed as completed by magento-engcom-team** 2018-08-18 11:10 UTC
Labels: Issue: Ready for Work, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Ui

**Comment by sidolov** [comment] 2018-08-23 06:54
Hi @markoshust. Thank you for your report. 
The issue has been fixed in magento/magento2#17689 by @dmytro-ch in 2.1-develop branch
Related commit(s):
 - [d942d6775a3cde1da54e68ed3cf9757ee4d105d4](https://github.com/magento/magento2/commit/d942d6775a3cde1da54e68ed3cf9757ee4d105d4)

The fix will be available with the upcoming 2.1.16 release.

**Comment by sidolov** [comment] 2018-08-26 07:14
Hi @markoshust. Thank you for your report. 
The issue has been fixed in magento/magento2#17688 by @dmytro-ch in 2.3-develop branch
Related commit(s):
 - [fe088901a8e2c32fc75baca5b32ec332a022651c](https://github.com/magento/magento2/commit/fe088901a8e2c32fc75baca5b32ec332a022651c)

The fix will be available with the upcoming 2.3.0 release.
