### ISSUE TITLE
SCRIPT1014: Invalid character  cart, line 57 character 29  - IE 10

### ISSUE THREAD

**Issue by sma09sjb** [magento/magento2#7051] opened 2016-10-17 11:03 UTC
### Preconditions
1. Windows 7 IE 10, Magento 2.1.1
### Steps to reproduce
1. Add a product to cart and try and expand the shipping section 
2. Multiple js errors being thrown in totals.js and cart.js
### Expected result

1. Shipping area should be expanded 
### Actual result

1. ![image](https://cloud.githubusercontent.com/assets/19289786/19435227/749e2c38-9461-11e6-90b3-ede52a49ce26.png)

![image](https://cloud.githubusercontent.com/assets/19289786/19435237/7d97de06-9461-11e6-93ea-cce2e4b5a6f9.png)
1. loading gif never disappears

**Comment by veloraven** [comment] 2016-10-17 12:18
@sma09sjb thank you for your feedback.
Magento does not support the operating system you've listed. Please confirm that you can reproduce this issue on a supported platform. For an overview of supported technologies, see  System Requirements.

**Comment by sma09sjb** [comment] 2016-10-17 14:09
Where can i find a complete list of your supported OS? By that do you mean you don't support IE 10 or Windows 7? 

I've tried the same in WIndows 8 IE 10 and i'm getting the same results.

**Comment by JDavidVR** [comment] 2016-10-17 14:16
@veloraven uhmm but this is on browser side (is not development environment), I don't think is a valid argument say magento  doesn't support windows, because many (potential) client use windows as theirs desktop OS.

**Comment by sma09sjb** [comment] 2016-10-17 14:18
@veloraven i'm also slightly confused by your comment, can you clarify your meaning.

**Comment by veloraven** [comment] 2016-10-20 11:29
@sma09sjb I was sure I had added the link to requirements, sorry for inconvenience. Here you are: [System Requirements](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-2.1-tech.html).
I also thought that you mentioned OS of the server (as it usually happens), and did not realize that it was about customer's system.
@JDavidVR  thank you for noting this point.

**Comment by sma09sjb** [comment] 2016-10-21 08:27
Hi @veloraven unfortunately that link isn't working for me, i'm assuming it's purely for internal use.

This error occurred on a  customer environment we were using to test our site. 

Can you confirm this is a Magento bug and if so when i can expect some resolution?

Thanks,

Sophie

**Comment by odubovyk** [comment] 2016-10-27 10:15
Supported browsers can be found [here](http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements_browsers.html) , and we support IE9-10-11 on Storefront.
On current develop this issue is fixed.

**Comment by veloraven** [comment] 2016-10-31 14:10
@sma09sjb sorry once more - my mistake, there was a wrong link. I have updated it, it should open normally now.
And yes, we took it as an issue, internal ticket for Magento 2.1 - MAGETWO-60293

**Comment by debuysserk** [comment] 2016-11-02 09:04
Hi guys, is this effectively fixed? Could you point us to the correct commit in the develop branch so we can try to cherry pick it to our project? 

Thanks.

**Comment by veloraven** [comment] 2016-11-24 12:19
@debuysserk you can find reference for the fixing commit for develop branch in #5358.

**Comment by korostii** [comment] 2017-01-10 16:49
> you can find reference for the fixing commit for develop branch

@veloraven Is there any chance we can get these releases on a separate stable branch other than develop? IMHO that's quite simple to implement and would effectively allow to get these fixes in a timely manner using composer.
Both using develop branch on production and forking the magento2 repository in order to be able to cherry-pick the selected bugfix commits seem like risky and hacky workarounds. If there is any other cleaner solution I would also be happy to try it out.

That is, if the current turtle pace of releasing bugfix versions once per 6 months continues (my frustration from which I have already expressed on a different [issue](https://github.com/magento/magento2/issues/7943#issuecomment-270862382)) 
Additionally, seeing some bugfixes to somehow miss even this slow schedule and get pushed back to the next release, like in this very case (see f3d7952805c7b5adc9b47c4d979c49e547a0772e ) is just jaw-dropping.

An even more dramatic example can be seen here: #7985. That bug, it seems, was earlier reported in #5352, same day "fixed on develop", later on reported again in duplicate issues at least 5 times by different people, still not released to 2.1 branch and now it's " targeted against the 2.1.5 release for early next year". Like, seriously? Seriously?
I'd like to quote a [related comment](https://github.com/magento/magento2/issues/6275#issuecomment-254011673) from one of those threads:
> It's disappointing. If anyone on the Magento team is reading this, please take some time to fix all know issues/bugs before releasing 2.1.3 or 2.2. It's just common sense to do so

Months later, seems as if nobody is reading this :(
See also another bug with a similar story: #3789
I understand that all the merging and QA stuff going on which might slow it down, I really do, but I am beginning to wonder whether such a workflow is really any good for the actual quality of the product.

**Comment by magento-engcom-team** [comment] 2017-10-05 11:30
@sma09sjb, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-05 11:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Checkout, Issue:  Cannot Reproduce, Issue: Format is valid
