### ISSUE TITLE
Unable to assigning role/types to images in multi website via Media API

### ISSUE THREAD

**Issue by preeteshtavant** [magento/magento2#33241] opened 2021-06-15 05:11 UTC
### Preconditions (*)

1.Magento ver. 2.4.1
2. Create multiple website ( For example website 1 with store abc, website 2 with store xyz)
3. Create a product which belongs to both the websites 
4. API Method post
5. API :- products/{sku}/media
6. Documentation link :- https://magento.redoc.ly/2.4.2-admin/tag/productsskumedia#operation/catalogProductAttributeMediaGalleryManagementV1CreatePost
7. Sample payload which i am using 
`{
  "entry": {
    "media_type": "image",
    "label": "string",
    "position": 0,
    "disabled": false,
    "types": [
      "image", 
      "small_image", 
      "thumbnail"
    ],
    "file": "new/1.png",
    "content": {
      "base64_encoded_data": "any image base 64 encoded data",
      "type": "image/png",
      "name": "string"
    }
  }
}`

### Steps to reproduce (*)

1. Run the media api for the product which is available in both the website
2. Try to mark image role as "image, small_image, thumbnail" in payload
3. Hit/Run the API
4. you will receive the media gallery entry id

### Expected result (*)

1. image uploaded properly and assigned to product in both websites
2. image is marked as "image, small_image, thumbnail" in both the websites

### Actual result (*)

1. image uploaded properly and assigned to product in both websites
2. image marked as "image, small_image, thumbnail" only for single website (Default Store View only), not for both.
3. try to change the scope of product and select different stores, you will find that "image, small_image, thumbnail" is marked for only single website not for both
![image](https://user-images.githubusercontent.com/85919383/121996236-d7573480-cdc5-11eb-9ed0-745045f915d4.png)

---
 [ S3]

**Comment by engcom-Hotel** [comment] 2021-07-16 13:59
Hello, @preeteshtavant,

We have tried to reproduce the issue in Magento 2.4-develop branch but it is not reproducible. We have followed below steps:

1. Setup 2 websites other than the default website (for India and the US).
2. Create a product that is allowed for all the websites including the default one.
3. Hit the media API (rest/default/V1/products/t1/media) to upload an image with below payload:

`{"entry":{"media_type":"image","label":"Gallery entry alternative text","position":1,"disabled":false,"types":["image","small_image","thumbnail"],"file":"new/1.jpeg","content":{"base64_encoded_data":"base64 Encoded Value","type":"image/jpeg","name":"Dummy Name"}}}`

4. Check PDP as well as product edit page, we can see the images in both locations.

Please let us know if we missed anything in order to reproduce the issue or please try to reproduce the issue in 2.4-develop branch.

Thanks

**Comment by preeteshtavant** [comment] 2021-07-17 06:51
Magento ver. 2.4.1

![pic3](https://user-images.githubusercontent.com/85919383/126028626-295cec27-fbf9-48f7-b60d-0ec63a81440e.png)
![pic2](https://user-images.githubusercontent.com/85919383/126028628-1a30b7b6-8486-4010-a928-817e82716ecb.png)
![pic1](https://user-images.githubusercontent.com/85919383/126028630-7d318e2a-1a70-4949-942c-df2d31d738b4.png)

api url : http://127.0.0.1/magento-241-1/rest/V1/products/pqr/media
payload: {"entry":{"media_type":"image","label":"Gallery entry alternative text","position":1,"disabled":false,"types":["image","small_image","thumbnail"],"file":"new/1.jpeg","content":{"base64_encoded_data":"base64 Encoded Value","type":"image/jpeg","name":"Dummy Name"}}}

why its not assigning roles for all stores and store views

**Comment by engcom-November** [comment] 2021-08-05 10:02
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:

**Steps to reproduce:**
Multi Store Setup -  [Ref Guide:](https://devdocs.magento.com/guides/v2.4/config-guide/multi-site/ms_websites.html)
Create a product such that the product is visible on multiple websites (Admin - Catalog - Products - Add New Simple Product) Product In Websites - Select All Website options and Save
Note: Do not upload any image for the product
API - Generate Admin access token using /rest/default/V1/integration/admin/token
Hit the /rest/default/V1/products/{sku}/media  POST request using below Sample payload:
Navigate to Admin - Catalog - Products - View Product and verify Images section
Image uploaded successfully to all websites successfully
Change the Scope to All Store Views / Other Store Views and Verify Images section
**Issue**: **Image Roles/Types are applied to Default Store View only but not applied to other Store Views**
...
{
  "entry": {
    "media_type": "image",
    "label": "Gallery entry alternative text",
    "position": 1,
    "disabled": false,
    "types": [
      "image",
      "small_image",
      "thumbnail"
    ],
    "file": "new/1.jpeg",
    "content": {
      "base64_encoded_data": "any base64 encoded image value",
      "type": "image/jpeg",
      "name": "new_image2.jpeg"
    }
  }
}
...

![image](https://user-images.githubusercontent.com/60198231/128332027-934c5b1a-d188-40b2-bf5a-3391d0d17046.png)
![image](https://user-images.githubusercontent.com/60198231/128332047-4a56b131-7d6f-4d54-b5bd-17138e0a81fa.png)
![image](https://user-images.githubusercontent.com/60198231/128332107-f0b94ce1-3047-4859-ae73-895d538d86b2.png)

**Comment by magento-engcom-team** [comment] 2021-08-05 10:10
:white_check_mark: Confirmed by @engcom-November 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42999` were created

**Issue Available**: @engcom-November, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rmsundar1** [comment] 2021-09-27 15:17
@preeteshtavant to set the role/types images in all the websites/stores we need to pass `all` as store value in the API as per the doc
i.e,. `/rest/all/V1/products/{sku}/media`.

**Closed as completed** 2021-10-01 14:54 UTC
Labels: Issue: Confirmed, Component: Api, Component: Image, Reproduced on 2.4.x, Priority: P1, Progress: done, Reported on 2.4.1, Area: APIs

**Comment by mackieee** [comment] 2022-08-03 13:13
Has this been resolved in Magento 2.4.5 as per this Changelog line?

![image](https://user-images.githubusercontent.com/883702/182616593-cc7f8d81-e4ec-46a5-baf1-cb680cda925a.png)
