### ISSUE TITLE
Sorting configurable products by price doesn't work when simple product has special_price

### ISSUE THREAD

**Issue by Fdec** [magento/magento2#4778] opened 2016-05-30 15:21 UTC
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Edit a simple product (which is a variation of a configurable product)
3. Add special_price
4. Go in catalog product list
## Expected result
1. sorting by price based on min_price of a simple product 
## Actual result

![capture du 2016-05-30 17 08 44](https://cloud.githubusercontent.com/assets/5850723/15652972/3440b498-268a-11e6-9f1c-b14b6fce9a8b.png)

**Comment by antboiko** [comment] 2016-05-31 08:27
Hello @Fdec , thanks for reporting this issue. We've created internal ticket MAGETWO-53675.

Best,
Anton.

**Comment by NisaKH** [comment] 2016-08-16 07:24
any update on this issue?

**Comment by sergiojovanig** [comment] 2016-10-31 09:24
Hi, I can reproduce this bug in Magento 2.1.2. Any temporal workaround? I think this is critical...

**Comment by vipinroy** [comment] 2017-02-20 09:23
Can we use the below commits to solve this issue?
Please help..

**Comment by veloraven** [comment] 2017-06-20 12:18
This issue was fixed in develop branch.
It also was fixed for ver. 2.1 and will be available in one of the nearest releases.

**Comment by magento-engcom-team** [comment] 2017-09-20 22:17
@Fdec, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:17 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Fixed in 2.2.x, Issue: Format is not valid

**Comment by maderlock** [comment] 2017-11-10 12:15
Will this get a fix for 2.1?

**Comment by DePalmo** [comment] 2018-07-19 21:49
Still reproducible in v2.2.3 ...

**Comment by ktsixit** [comment] 2019-07-22 04:51
![Untitled-1](https://user-images.githubusercontent.com/2758872/61609938-4b334580-ac60-11e9-93d3-a306777af1e4.jpg)

I have this issue in 2.3.This should have been fixed, right? What should I check?

**Comment by antoniocarboni** [comment] 2025-07-22 09:26
Still reproducible in 2.4.6.
