### ISSUE TITLE
Zip code not being updated in shipping/billing address when trying to append 0 in existing zip code of order shipping/billing address

### ISSUE THREAD

**Issue by parbat-evrig** [magento/magento2#38898] opened 2024-07-03 07:50 UTC
### Preconditions and environment

- Magento version 2.4.5

### Steps to reproduce

1. Place an order from frontend/backend using zip code 1234
2. Navigate to sales -> order in admin
3. Search for recently placed order and click on view
4. Go to shipping address section and click on edit
5. Edit zip code value from 1234 to 01234 and click on Save Address
6. After saving shipping address check again in order view page and you will find zip code not updated still shows 1234 

### Expected result

Zip code should be updated from 1234 to 01234

### Actual result

Zip code not updated

### Additional information

Magento 2.4.5

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-07-03 08:00
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-07-03 08:16
Hi @parbat-evrig,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.



https://github.com/magento/magento2/assets/51680745/cb6a60c6-842e-4ce6-b4db-8841da0e37c9




Zip code is updated to 1234 to 01234

Kindly recheck the issue in Latest 2.4-develop instance and please let us know if you are still facing any issue.

Thanks.

**Comment by parbat-evrig** [comment] 2024-07-03 08:54
Hi @engcom-Bravo ,

Please see this video.
[zip-code-issue.webm](https://github.com/magento/magento2/assets/131332420/918ee2ec-8025-4672-b376-d9e120f19a0f)

**Comment by parbat-evrig** [comment] 2024-07-03 08:58
Hi @engcom-Bravo ,

Please see this video tested with fresh Magento 2.4.6 instance.
[address-zip-code-issue.webm](https://github.com/magento/magento2/assets/131332420/ae6e6610-935b-4e9e-a70f-c1bd611c4378)

**Comment by engcom-Bravo** [comment] 2024-07-04 11:11
Hi @parbat-evrig,

Thanks for your update.

It is recommended to verify the issues in Latest 2.4-develop instance and it might be possible in Latest magento version.Could you please check in Latest version and let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-07-15 05:33
Hi @parbat-evrig,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-15 05:33 UTC
Labels: Issue: needs update, Reported on 2.4.5
