### ISSUE TITLE
Bug in Widget condition filter for price range - Error filtering template: Unknown condition operator

### ISSUE THREAD

**Issue by magefast** [magento/magento2#13736] opened 2018-02-19 17:29 UTC
Exist error/bug in conditions filter. Not working conditions for price (or other numeric type) - less than, more than, etc.

As I understand - problem is - when saved type of filter like - '>=', '>', '<=', '<' - converted to HTML entities. [(https://dev.w3.org/html5/html-author/charref)](https://dev.w3.org/html5/html-author/charref)

### Preconditions

1. Magento version - 2.2.2
2. PHP Version 7.0.22-0ubuntu0.16.04.1 , default_charset - UTF-8

### Steps to reproduce

1. Create widget for Homepage, product list, conditions - product price from 1$
2. Check Homepage, you will see - **Error filtering template: Unknown condition operator**

### Expected result

1. Will show list of products with filter in conditions.

### How to fix
in file app/code/Magento/Rule/Model/Condition/Sql/Builder.php
need update array - protected $_conditionOperatorMap

add followings:
```
        '&gt;=' => ':field >= ?',
        '&gt;'  => ':field > ?',
        '&lt;=' => ':field <= ?',
        '&lt;'  => ':field < ?',
```

and final protected $_conditionOperatorMap like - 

```
protected $_conditionOperatorMap = [
        '=='    => ':field = ?',
        '!='    => ':field <> ?',
        '>='    => ':field >= ?',
        '>'     => ':field > ?',
        '<='    => ':field <= ?',
        '<'     => ':field < ?',
        '{}'    => ':field IN (?)',
        '!{}'   => ':field NOT IN (?)',
        '()'    => ':field IN (?)',
        '!()'   => ':field NOT IN (?)',
        '&gt;=' => ':field >= ?',
        '&gt;'  => ':field > ?',
        '&lt;=' => ':field <= ?',
        '&lt;'  => ':field < ?',
    ];
```

### Resume

Maybe this settings of PHP, but installed standard PHP version without extra settings.

Thanks

![jidjijdi](https://user-images.githubusercontent.com/1673611/36390233-042ad092-15ab-11e8-96a8-4c47a03cde77.png)

![home_page___pages___elements___content___magento_admin](https://user-images.githubusercontent.com/1673611/36390272-2fee474a-15ab-11e8-9b8d-71b79c4588ef.png)

**Comment by magento-engcom-team** [comment] 2018-03-15 15:30
@magefast, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by sydekumf** [comment] 2018-05-02 09:27
Hey there, the same problem also occurs for Magento 2.1, the serialized value looks like this: `s:1:"&gt;";` which of course can not be deserialized. Any idea when this will be fixed? :wink:

**Comment by axovel** [comment] 2018-06-18 18:20
Any updates on this ? I am also getting the same issue

**Comment by Mobecls** [comment] 2018-11-13 08:01
In this situation, I just changed the '& gt;' on '>' in the widget code.

**Comment by magento-engcom-team** [comment] 2019-01-21 07:38
Hi @vasilii-b. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by vasilii-b** [comment] 2019-01-21 07:40
Hi @magefast ,
Unfortunately I wasn't able to reproduce the issue on the `2.3-develop` branch. Can you please re-check if issue still exists and reopen it if so ?
Thank you!

**Closed as completed by vasilii-b** 2019-01-21 07:40 UTC
Labels: Reproduced on 2.1.x, Reproduced on 2.2.x, Issue: Format is not valid, Component: Rule
