### ISSUE TITLE
Fulltext collection used on category page in toolbar pager links

### ISSUE THREAD

**Issue by daniel-ifrim** [magento/magento2#9807] opened 2017-05-31 08:21 UTC
### Preconditions
1. Magento 2.4-develop with sample data
I'm in a case with a bug that reports one more product in getSize() on product collection. The product collection in fact the fulltext product collection from Magento_Catalog_Search. Why I get one more product in search collection is not relevant. How I get that one more product is the issue.

### Steps to reproduce
1. On category page, in class \Magento\Catalog\Block\Product\ProductList\Toolbar::getPagerHtml() function the collection in use is \Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection
2. Log the collection query with $this->getCollection()->getSelect()->__toString()
3. The query does an extra JOIN:
INNER JOIN `search_tmp_592dad48d1e409_82724533` AS `search_result` ON e.entity_id = search_result.entity_id
It's a temporary MySQL memory table managed from this class:
\Magento\Framework\Search\Adapter\Mysql\TemporaryStorage
This feature is used in Magento_CatalogSearch module which is ok.
But it is used on category page too.

### Expected result
1. It should use the usual product collection \Magento\Catalog\Model\ResourceModel\Product\Collection

### Actual result
It uses \Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection and adds an extra INNER JOIN on a memory table created on the fly in category page.
![#9807issue](https://user-images.githubusercontent.com/51681379/72142168-c4545f80-339c-11ea-8e8f-4f20a9404f43.png)

Beside this it may run other unexpected code from Magento_CatalogSearch or Magento_Search module (I don't confirm this).

The problem is when declaring this in Magento_CatalogSearch/etc/di.xml:
```
<type name="Magento\Catalog\Model\Layer\Category">
    <arguments>
        <argument name="context" xsi:type="object">Magento\CatalogSearch\Model\Layer\Category\Context</argument>
    </arguments>
</type>
```

where in Magento_Catalog/etc/di.xml there is this declaration:
```
<type name="Magento\Catalog\Model\Layer\Category">
    <arguments>
        <argument name="context" xsi:type="object">Magento\Catalog\Model\Layer\Category\Context</argument>
    </arguments>
</type>
```

You can clearly see that the declaration from Magento_CatalogSearch module replaces the one from Magento_Catalog.
By commenting the above argument injection in Magento_CatalogSearch/etc/di.xml,
the collection Fulltext won't be anymore in \Magento\Catalog\Block\Product\ProductList\Toolbar::getPagerHtml(). The additional join on the memory tables is not made anymore. My case is fixed too.
But this is not the fix. It's a proof of what's happening.

The virtual types declared in both catalog and catalog search modules around Catalog Layer classes look good, but the argument injection from above and the logic behind them needs to be improved.

**Comment by magento-engcom-team** [comment] 2017-10-03 12:30
@daniel-ifrim, thank you for your report.
We've created internal ticket(s) MAGETWO-80728 to track progress on the issue.

**Comment by udovicic** [comment] 2018-04-19 07:53
Just to share some info on this, I have been in touch with Magento EE support on this one, and official standpoint is that this is not a bug, but rather planned feature. So it is kind of misleading to have it here marked as *bug report* and assigned to *Community Dashboard* including the *internal ticket* which is a dead end. Perhaps this should be adjusted as well so others can be aware of status as well.

Finally I just want to say that I am unpleasantly surprised that rendering category pages requires not one, but two on the fly indexers with temp tables just to display the category page.

**Comment by sshymko** [comment] 2018-08-21 00:10
Experiencing the issue on 2.2.3 when MySQL server gets spontaneously overloaded by the query `INSERT INTO search_tmp_*` executed on a category view page. We haven't had an issue on 2.1.9 befoe upgradding to 2.2.3. Since then it reproduces infrequently out of blue.

Here's how the load spiked look in New Relic:
<img width="1029" alt="cmg_newrelic_search_tmp_mysql_spike" src="https://user-images.githubusercontent.com/1231423/44373091-3d979d80-a49c-11e8-913d-aad85be71197.png">

The following query is responsible for the spikes:
```sql
INSERT INTO `search_tmp_?b?f?ad?fe?_?` SELECT `main_select`.`entity_id`, SUM(score) AS `relevance` FROM (SELECT DISTINCT  `search_index`.`entity_id`, (((?) + (?)) * ?) AS `score` FROM `catalog_product_index_eav` AS `search_index`
 INNER JOIN `cataloginventory_stock_status` AS `stock_index` ON stock_index.product_id = search_index.entity_id AND `stock_index`.`website_id` = ? AND `stock_index`.`stock_status` = ? AND `stock_index`.`stock_id` = ?
 INNER JOIN `catalog_category_product_index` AS `category_ids_index` ON search_index.entity_id = category_ids_index.product_id AND category_ids_index.store_id = ? WHERE (search_index.store_id = ?) AND (`search_index`.`attribute_id` = ? AND `search_index`.`value` IN (?, ?) AND `search_index`.`store_id` = ?) AND (category_ids_index.category_id = ?)) AS `main_select` GROUP BY `entity_id` ORDER BY `relevance` DESC, `entity_id` DESC
 LIMIT ?
```

**Comment by magento-engcom-team** [comment] 2020-01-10 09:34
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30340` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Closed as completed** 2020-06-10 13:26 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Issue:  Cannot Reproduce, Issue: Format is valid
