### ISSUE TITLE
Filter by attribute doesn't return any product

### ISSUE THREAD

**Issue by palo** [magento/magento2#11189] opened 2017-10-03 10:58 UTC
At some point, our store lost the ability to filter by attribute. Major changes in recent past were version updates. I'm not sure which update caused this issue but the store was working fine.
Same as in https://github.com/magento/magento2/issues/11101 and https://github.com/magento/magento2/issues/11159

### Preconditions

1. Magento 2.1.9
2. PHP 7.0
3. MySQL 5.7.19

### Steps to reproduce

1. Magento 2.1.7 with demo content
2. Upgrade to 2.1.9 (not sure if you can start from 2.1.9)
3. Create new website, store and store view. Set as default.
3. Delete base website
4. Associate all products to new website 

### Expected result

1. Filter by attribute returns products as expected

### Actual result

1. Product count in layered navigation sidebar is correct.
![01](https://user-images.githubusercontent.com/583644/31121600-d2ee4c08-a830-11e7-8a74-ef69b9cc0477.JPG)

2.  Filtered view returns no products.
![02](https://user-images.githubusercontent.com/583644/31121609-deb778b6-a830-11e7-9efa-7bbfcae708ee.JPG)

**Comment by magento-engcom-team** [comment] 2017-10-03 13:22
@palo Thanks for reporting this issue. 
Unfortunately, I could not reproduce the issue as you described it.
Steps I did:
1. Install Magento 2.1.7 with Sample Data CE 2.1.7
2. Upgrade to Magento 2.1.9 with Sample Data CE 2.1.9
3. Create new website with new store(Root Category > Default Category) and store view.
4. Set new website as default.
5. Delete old one without backup.
6. Assign product to new website:
Product > Catalog > Select all > Actions > Update Attributes > Websites > Add Product To Websites > select new website.
7. Perform reindex bin/magento indexer:reindex; bin/magento cache:flush.
8. Navigate to Storefront > Gear > Fitness Equipment.
9. Filter by Material = Leather.
Result: three products show up.
![screenshot_1](https://user-images.githubusercontent.com/31669971/31127342-4ca4f792-a857-11e7-9626-0c60fe32f450.png)
Please add more details to your description of the steps you followed when identifying this issue.
And please make sure You did reindex after assigning products to new website.

**Comment by palo** [comment] 2017-10-04 08:25
Have tried again in new install but also can´t reproduce. This is very frustrating. 

I did reindex and cleared cache (several times) 
Other thing i notice is the stats in the dashboard are all zeroed out.

Any recommendation?

**Comment by magento-engcom-team** [comment] 2017-10-05 15:00
@palo Thanks for the feedback.
Unfortunately, we can not fix issue until it will be reproduced. And currently we can not reproduce this issue on clean Magento installation.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
As we were not able to reproduce this issue by following the steps you provided, we close it. If you'd like to update it, please reopen the issue.

**Closed as completed by magento-engcom-team** 2017-10-05 15:00 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid

**Comment by jimmyhien** [comment] 2017-10-11 08:12
I also have this issue when I upgrade from version 2.1.7 to version 2.1.9. I think there was some changes with indexer in newer version make the system couldn't find any products with custom attribute filterable results.

**Comment by jimmyhien** [comment] 2017-10-12 10:30
@palo I solved the problem by do this change https://github.com/magento/magento2/commit/2c62aa376eeed447e632aedb42085c9d255520df

**Comment by noindie** [comment] 2017-12-19 16:47
@jimmyhien 
Thanks!! I had the same problem after upgrading from 2.1.7 to 2.1.9 and fixed with that solution

**Comment by saket1singh** [comment] 2018-06-07 08:28
Hi @jimmyhien  and @palo how did you solve this issue please tell me also .
I have magento 2.2.3 store and filter is working fine in local but for same code and database filter not giving result .


Please reply me 
Thanks in advance!

**Comment by jimmyhien** [comment] 2018-06-07 08:41
@saket1singh 
Did you run reindex command?

**Comment by saket1singh** [comment] 2018-06-07 09:16
@jimmyhien Yes I run but filters result not working properly as lowest price filter and it is working fine in test site

If you have any suggestions please tell me
