### ISSUE TITLE
Magento2 Website - Pricing in products has 2 prices!

### ISSUE THREAD

**Issue by Rebecca-DLV** [magento/magento2#35316] opened 2022-04-14 20:53 UTC
### Preconditions (*)

1. Magento 2.3.7  with Netsuite ERP. Using Netsuite Connector (Farapp).
2. 

### Steps to reproduce (*)

1. Product is displayed on the website with 2 prices. Screenshot #1 This just started to happen right as we are about to go live! Looking at the product configuration those with the issue show this in Advanced Pricing in the Magenot2 Admin. Screenshot#2
2. How would the configuration on all these items change without someone having gone in and updating each one. Which didn't happen. 
3. 

### Expected result (*)

1.Should only be 1 price as base price. #3  If the product has tiered pricing (not all do) then the tiered pricing is listing. Screenshot#4

### Actual result (*)

1. [Screenshots, logs or description]
![pricing problem](https://user-images.githubusercontent.com/103620911/163473320-534435fa-f4af-4c59-8192-d4fe9d82b387.jpg)
![pricing issue2](https://user-images.githubusercontent.com/103620911/163473388-dce93cec-bde9-402a-b9f9-c9d2437b3010.jpg)
![pricing problem](https://user-images.githubusercontent.com/103620911/163473392-b3b1e471-060b-4a35-bd28-bd98b7ad095e.jpg)

**Comment by engcom-November** [comment] 2022-04-29 07:13
Hi @Rebecca-DLV ,
Thank you for reporting and collaboration. Unable to reproduce this issue on Magento 2.4-develop branch. Netsuite Connector (Farapp) is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.

**Closed as completed by engcom-November** 2022-04-29 07:13 UTC
Labels: Component: Bundled Extension, Issue: ready for confirmation
