### ISSUE TITLE
Product Attribute Option Values

### ISSUE THREAD

**Issue by LordHansolo** [magento/magento2#6507] opened 2016-09-06 10:23 UTC
### Preconditions

Magento 2.1.1 CE
### Steps to reproduce
1. Add custom product attribute type Dropdown in admin panel and fill it with some options. 
   ![attribute_options](https://cloud.githubusercontent.com/assets/22025597/18270169/ed8d3770-742b-11e6-91f9-ffe0fe593c27.png)
2. Add attribute to any Attribute Set.
3. Go to "Add Product" and choose Attribute Set that you put your attribute.
4. Click on your attribute to expand option list.
   ![product_attribute_options](https://cloud.githubusercontent.com/assets/22025597/18270263/5413a89e-742c-11e6-8e79-10df2498206e.png)
### Actual Result

Options come from "Default Store View" column
![attribute_options3](https://cloud.githubusercontent.com/assets/22025597/18273374/327e51a0-743d-11e6-83c8-d6cc6c8dc4d0.png)
### Expected Result

Options come from "Admin" column
![attribute_options2](https://cloud.githubusercontent.com/assets/22025597/18273380/3a71efe8-743d-11e6-8741-56a1544c3684.png)

**Comment by sevos1984** [comment] 2016-09-09 09:50
Internal ticket created MAGETWO-58219. Thanks.

**Comment by Pakkapao** [comment] 2016-12-05 15:15
I'm using Magento 2.1.2 and have the same problem.

**Comment by magento-engcom-team** [comment] 2017-10-05 12:30
@LordHansolo, thank you for your report.
We've created internal ticket(s) MAGETWO-58219 to track progress on the issue.

**Comment by keyurshah070** [comment] 2017-10-22 13:20
I can not reproduce in fresh setup of 2.2, please check below screenshot.Kindly confirm @okorshenko 
## **my test attribute**

![drop product attributes attributes stores magento admin](https://user-images.githubusercontent.com/17308601/31862321-47a1c024-b73c-11e7-8017-e684a3660bd0.png)

## **and my test product**

![untitled](https://user-images.githubusercontent.com/17308601/31862322-4f41be10-b73c-11e7-934a-78cc4333e331.png)

**Comment by keyurshah070** [comment] 2017-10-23 10:41
Kindly confirm @ishakhsuvarov

**Comment by walrus28** [comment] 2018-03-06 23:47
I did not have this problem in 2.1.9. The admin attribute values showed when editing products. 

However, since upgrading to 2.2.3, I now have this problem. The default store view attribute values show when editing products.

**Comment by magento-engcom-team** [comment] 2019-01-02 19:22
Hi @milindsingh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by irenelagno** [comment] 2019-04-03 20:26
The fix for this issue has been delivered in the scope of [60e3a73](https://github.com/magento/magento2/commit/60e3a73c937ea50d8ad8bee230c002df61d1fe5e)

**Comment by sdzhepa** [comment] 2019-04-03 21:13
Hello @LordHansolo and @milindsingh 

The issue was fixed and delivered by Magento team.

Details can be find here https://github.com/magento/magento2/commit/60e3a73c937ea50d8ad8bee230c002df61d1fe5e

The issue can be closed

**Closed as completed by sdzhepa** 2019-04-03 21:13 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid
