### ISSUE TITLE
URI is not valid and cannot be converted into a string when trying to load website

### ISSUE THREAD

**Issue by gvasilakiss** [magento/magento2#34939] opened 2022-01-05 20:42 UTC
### Preconditions (*)

1. PHP 7.4.27
2. composer 2.1.4
3. Magento version 2.4.2-p2 enterprise
4. Elasticsearch 7.16.2
5. Redis Cache 5.0.14
6. Grunt 1.0.4

### Steps to reproduce (*)

1. Install a fresh installation of Magento with multiple store views (3-4), and added my custom code for the website
2. Try to access the homepage

### Expected result (*)

1. Site should load the default homepage

### Actual result (*)

1. Site displays error saying URI is not valid and cannot be converted into a string
![image](https://user-images.githubusercontent.com/34243942/148285415-7bd24b51-2bd0-4500-81da-4f1b6c1698f0.png)
![image](https://user-images.githubusercontent.com/34243942/148286101-e75dfc5c-d305-41d6-b20f-44bf453f0fbb.png)

#### From the message alone it is impossible to figure out what went wrong. Any help will be appreciated.
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by andrewbess** [comment] 2022-01-05 21:02
Hello @gvasilakiss 
What is your custom code for website?
Could you please provide example?
Thank you in advance.

**Comment by gvasilakiss** [comment] 2022-01-05 21:07
> Hello @gvasilakiss What is your custom code for website? Could you please provide example? Thank you in advance.

Hi @andrewbess 
As they are custom modules, I cannot share anything, I am afraid.

**Comment by engcom-Hotel** [comment] 2022-01-06 05:46
Hello @gvasilakiss,

In a fresh Magento installation, we are not getting such errors. The error may be due to the custom module you made. Can you please try to disable that custom module and try again?

Thanks

**Comment by gvasilakiss** [comment] 2022-01-06 23:09
It seems to work now - it was a custom module causing the issue.

**Comment by engcom-Hotel** [comment] 2022-01-07 06:17
Hello @gvasilakiss,

Thanks for the update!

So the issue is due to the custom module not being from Magento's core module, we are closing this issue.

Thanks

**Closed as completed by engcom-Hotel** 2022-01-07 06:17 UTC
Labels: Issue: needs update
