### ISSUE TITLE
Newsletter product widget wrong store view per send batch

### ISSUE THREAD

**Issue by vandijkstef** [magento/magento2#38904] opened 2024-07-04 12:00 UTC
### Preconditions and environment

- Mage 2.4.7
- comes with module-newsletter@100.4.7

### Steps to reproduce

1. Create a newsletter template containing a product widget ("Catalog Products List" used, made product selection based on specific SKU's) ánd other {{trans ""}} elements (albeit those are just to prove the point)
2. Send (async + batched) out newsletter to multiple customers on different store views (languages)

### Expected result

A nicely translated email with the products for the correct store-view/language

### Actual result

While the header/footer, subject and {{trans ""}} element work fine the "catalog products list" widget is not always in the correct store-view/language

### Additional information

I couldn't find a specific reason yet, however it isn't completely random. 

It seems that the "catalog products list" widget is only being generated ONCE per batch. Batches contain multiple subscribers on different store view, but all will receive the catalog-product-list widget in the same language. I haven't been able if this is down to the first or last entry in the batch as async sending can trip up the order here, but the entire batch has _that_ store-view/language while all other elements internationalize just fine. So while some batches are send out fine (100% same store-view subscribers in batch), others are 95% wrong. This needs to be tested where batches are containing mixed subscribers.

Technically you can work around this by queuing newsletters per store-view.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2024-07-18 07:26
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment] 2024-07-23 11:18
Hi @vandijkstef  ,

Thanks for your reporting and collaboration.
We have verified the issue in latest 2.4-develop instance and the issue is not reproducible. Kindly refer the screenshots.

**Steps to Reproduce -** 
1. Create multiple store views.
2. Multiple users should subscribe newsletter with different store views.  
<img width="837" alt="newsletter subscribe" src="https://github.com/user-attachments/assets/730c162f-7001-4036-9f3e-392b23908dc1">
3. Create a newsletter template with "Catalog Products List" widget.   
![image](https://github.com/user-attachments/assets/7262fd71-722f-4ca9-a584-46a6bdc28945)
4. Queue the newsletter for both the store views and wait for cron to run.
5. Observe the newsletter received in both emails.
For German Storeview
<img width="672" alt="german newsletter" src="https://github.com/user-attachments/assets/ad1865bc-f730-4d54-90a2-e3f68a38bf2c">
For English Storeview
<img width="687" alt="english newsletter" src="https://github.com/user-attachments/assets/ef8d20ab-0f20-4953-9519-cae80fcc464c">
Observe wishlist and add to cart buttons are displaying as expected in german for german storeview.
Please let us know if we missed anything.

Thanks.

**Comment by engcom-Delta** [comment] 2024-08-08 06:45
Hi @vandijkstef ,

We have noticed that this issue has not been updated since long time.
Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Delta** 2024-08-08 06:45 UTC
Labels: Component: Newsletter, Issue: needs update, Reported on 2.4.7
