### ISSUE TITLE
Magento 2 running on Ubuntu 20.04 with Nginx virtual host returns Bad Gateway Error code 502 for some pages

### ISSUE THREAD

**Issue by jessicana** [magento/magento2#36674] opened 2022-12-27 07:45 UTC
### Summary

I have a fresh install of Magento 2.4.4-p2 that is running on Ubuntu 20.04. The PHP version is 8.1.13 and the Nginx version is 1.18.0 (Ubuntu). I can see and access the home page and the following pages without 502 bad gateway error:
```
https://example.com/sales/guest/form/
https://example.com/catalogsearch/advanced/
```
Everything else including the admin page and any activity on the above pages such as a search query returns bad gateway error 502. Inside `/etc/nginx/sites-available` I have `example.com` virtual host with the following configuration:

    upstream fastcgi_backend {
       server  unix:/run/php/php8.1-fpm.sock;
    }
    server {
      listen 80;
      server_name example.com;
      set $MAGE_ROOT /var/www/example.com/html;
      include /var/www/example.com/html/nginx.conf.sample;
      client_max_body_size 2M;
      listen 443 ssl http2;
      listen [::]:443 ssl http2;
      ssl_certificate         /etc/ssl/cert.pem;
      ssl_certificate_key     /etc/ssl/key.pem;
      access_log /var/log/nginx/magento.access;
      error_log /var/log/nginx/magento.error;
    }

I followed the [documentation][1] and adjusted the below in `/etc/php/8.1/fpm/php.ini` :

    memory_limit = 2G
    max_execution_time = 1800
    zlib.output_compression = On

Usually, this issue is caused by an incorrect Nginx configuration file. But this is what Magento 2 documentation stated. How can I fix this? - The error log is clean. 

  [1]: https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/prerequisites/web-server/nginx.html?lang=en
 

### Examples

The content of `include /var/www/example.com/html/nginx.conf.sample;` is [here](https://github.com/magento/magento2/blob/2.4-develop/nginx.conf.sample). 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2023-01-23 14:59
Hello @jessicana,

Thanks for the report and collaboration!

We have tried to reproduce the issue in Magento 2.4-develop branch but the issue is not reproducible for us. We are able to access the page with the below configuration:

- Nginx - nginx/1.18.0
- Ubuntu 20.04
- PHP - 8.1.14

We are able to access the page:
![image](https://user-images.githubusercontent.com/51681618/214072013-6ae38220-42c1-4867-9309-07c17cf0d606.png)

![image](https://user-images.githubusercontent.com/51681618/214072090-7c617009-5db3-422e-8b24-2574c857a977.png)

Please let us know if we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2023-02-06 02:03
Dear @jessicana,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2023-02-06 02:03 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.4-p2
