### ISSUE TITLE
Deleting a custom option affects / removes other custom options

### ISSUE THREAD

**Issue by ProceduralUserName** [magento/magento2#39405] opened 2024-11-26 19:31 UTC
### Preconditions and environment

Magento 2.4.7 p-3

### Steps to reproduce

**(Outcomes differ based on steps taken)**

**Setup:**
- Create a new product
- Fill out required fields
- Scroll down to customizable options
- Create 4 custom fields: Field1, Dropdown1, Dropdown2, Radiobutton1.
- For each, fill in required fields with dummy data.
- For option type choose these, in order:
      - Field
      - Dropdown
      - Dropdown
      - Radiobuttons
- Make sure to add and populate Dropdown1, Dropdown2 and Radiobutton1's values fields.
- Save product
**Reproduce:**
- Delete Field option
  OR
- Delete Dropdown1
  OR
- Delete Dropdown2 

### Expected result

Respective field is deleted and other fields remain the same as they were.

### Actual result

**If Field option was deleted:**
   - Field option is removed (Correct action)
   - Dropdown1’s values are removed
   - Dropdown1’s option type is reset to “--please select–” and cannot reselect Dropdown as an option type.
**If Dropdown1 was deleted:**
   - Field1 option type is reset to –”please select–” and cannot reselect Field as an option type.
   - Dropdown1 is removed (Correct action)
   - Dropdown2’s values are removed
   - Radiobutton1’s values jump into Dropdown2’s values.
   - Radiobutton1’s values are empty
**If Dropdown2 was deleted:**
   - Field1 option type is reset to –”please select–” and cannot reselect Field as an option type.
   - Dropdown2 is removed (Correct action)
   - Radiobutton1’s values are removed

### Additional information

First post here, if there's any information I'm missing that I should add let me know. 

Thanks.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ProceduralUserName** [comment] 2024-11-26 19:48
@magento I am working on this

**Comment by ProceduralUserName** [comment] 2024-11-26 19:49
@magento add to contributors team

**Comment by ProceduralUserName** [comment] 2024-11-26 19:49
@magento I am working on this

**Comment by ProceduralUserName** [comment] 2024-11-26 19:50
@magento give me 2.4.7 instance

**Comment by engcom-Delta** [comment] 2024-11-27 11:53
Hi @ProceduralUserName ,

Thanks for your reporting and collaboration.
We have verified the issue in Latest 2.4 develop instance, but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce**
1 . Create a new product
2. Fill out required fields
3. Scroll down to customizable options
4. Create 4 custom fields: Field1, Dropdown1, Dropdown2, Radiobutton1.
5. For each, fill in required fields with dummy data.
6. For option type choose these, in order:
- Field
- Dropdown
- Dropdown
- Radiobuttons
7. Make sure to add and populate Dropdown1, Dropdown2 and Radiobutton1's values fields.
8. Save product
9. Remove field option, observe drop down option 1 is not deleted.
![image](https://github.com/user-attachments/assets/605967e8-35ca-473b-b7fa-3e29449f7b30)
10. Now, Remove Drop down 1, Observe drop down 2 options and radio button is displaying as expected
![image](https://github.com/user-attachments/assets/fd156026-b5ce-4309-aef6-978eaf8add19)

Can you please re-verify and confirm if you are still facing the issue.
Thanks.

**Comment by ProceduralUserName** [comment] 2024-12-02 20:54
The issue is not on the front end, it's when custom settings are set in the back backend (admin panel)

See screenshot

![Screenshot 2024-12-02 155215](https://github.com/user-attachments/assets/c2b15661-6051-411f-80d6-00bf21d2d785)

**Comment by engcom-Delta** [comment] 2024-12-03 14:09
Hi @ProceduralUserName ,

Thanks for your reporting and collaboration.
We have verified the issue in Latest 2.4 develop instance, but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce**
1 . Create a new product
2. Fill out required fields
3. Scroll down to customizable options
4. Create 4 custom fields: Field1, Dropdown1, Dropdown2, Radiobutton1.
5. For each, fill in required fields with dummy data.
6. For option type choose these, in order:
Field
Dropdown
Dropdown
Radiobuttons
![image](https://github.com/user-attachments/assets/fefd6114-a201-4e1a-bcac-b859ecbf80b1)
![image](https://github.com/user-attachments/assets/7b3041b5-328e-4a22-acad-16a4984f2fef)

7. Now, still in the admin panel, open the product and proceed to delete one of the first 3 custom options.
8.Base on which one you choose to delete, the following issues will occur (assuming you used naming conventions presented in initial steps):
9.If Field option was deleted:
Field option is removed (Correct action)
![image](https://github.com/user-attachments/assets/0703cb00-04d1-4413-b8cf-c2eb1539bc1c)
Observe we are still able to view the Dropdown1 options.
10.If Dropdown1 was deleted:
Field1 option type is reset to –”please select–” and cannot reselect Field as an option type.
Dropdown1 is removed (Correct action) and values are displaying as expected for field, dropdown 2 and radiobutton.
![image](https://github.com/user-attachments/assets/f28eb4a3-6379-487d-ac1e-bb7400b5f7fd)
![image](https://github.com/user-attachments/assets/1a621d1a-913c-46da-9b43-6309e6a6fe67)

Can you please re-verify and confirm if you are still facing the issue.
Thanks.

**Comment by ProceduralUserName** [comment] 2024-12-04 16:12
We are still facing this issue, but as you are not able to replicate it, it would seem that it's something to do with our instance

**Comment by engcom-Delta** [comment] 2024-12-05 13:08
Hi @ProceduralUserName ,

Could you please verify if any third party modules is causing this issue.

Thanks.

**Comment by ProceduralUserName** [comment] 2024-12-11 17:05
Sorry for the delay. https://hottons.com/option-images.html
This is the module we have installed and after doing some testing on a dev site, the issue comes from this module.

**Comment by engcom-Delta** [comment] 2024-12-12 13:20
Hi @ProceduralUserName ,

Thank you for verifying and confirming that the issue was caused by the module.
Closing issue based on your comment https://github.com/magento/magento2/issues/39405#issuecomment-2536573522

Thanks.

**Closed as completed by engcom-Delta** 2024-12-12 13:20 UTC
Labels: Issue: needs update, Reported on 2.4.7-p3
