### ISSUE TITLE
An error message shows up when the admin tries to Add/Edit a customer from Backend.

### ISSUE THREAD

**Issue by Ali-magento** [magento/magento2#10940] opened 2017-09-17 19:32 UTC
When the admin tries to Add/Edit any customer through the  Magento admin Panel, an error page shows up.
### Preconditions
1. Magento 2.1.8

### Steps to reproduce
Admin Dashboard >> Customers>> All Customers >> ADD NEW CUSTOMER 
### Expected result
The form for adding a new customer

### Actual result

![screen shot 2017-09-17 at 10 27 49 pm](https://user-images.githubusercontent.com/32041632/30524188-91aba474-9bf7-11e7-8fc5-80d168f4e0f9.png)

**Comment by magento-engcom-team** [comment] 2017-09-19 07:41
We are closing this issue because we cannot reproduce this issue as described. If you have questions, please refer to a question and answer site, such as Stack Exchange and the Magento Forums, where Magento community members can quickly provide recommendations and advice.

**Closed as completed by magento-engcom-team** 2017-09-19 07:41 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid
