### ISSUE TITLE
Compatibility issue with 8.1 trim() - Media Storage - App/Media.php

### ISSUE THREAD

**Issue by amarroni** [magento/magento2#35788] opened 2022-07-20 16:02 UTC
### Preconditions and environment

- Magento version: Commerce Cloud 2.4.4
-  Checking a image that not existe.

[Expected]

[Current]
trim(): Passing null to parameter #1 ($string) of type string is deprecated in <b>/app/vendor/magento/module-media-storage/App/Media.php on line 151

### Steps to reproduce

1- try to get a no exist image using default url example [BASE_URL]/media/catalog/product/placeholder/default/No_imagen_88

### Expected result

display default water mark image.

### Actual result

trim(): Passing null to parameter #1 ($string) of type string is deprecated in <b>/app/vendor/magento/module-media-storage/App/Media.php on line 151

### Additional information

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/5198527/180029170-6011eaad-8901-421d-ae8c-8ce910170729.png">

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by amarroni** [comment] 2022-07-20 16:02
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment] 2022-07-21 06:07
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment] 2022-07-21 06:35
Hi @amarroni 

Thank you for your contribution and collaboration.
Issue is not reproducible in `2.4-develop` branch.

Below is the screenshot for your reference:
![no_image_issue](https://user-images.githubusercontent.com/60198022/180144848-16614632-ab51-4c3b-a86e-b395f04b0256.png)
Kindly provide us more information in order to reproduce the issue.
Also try to test on latest `2.4-develop` branch.

Thanks

**Comment by josiahglassone** [comment] 2022-07-29 16:43
I had the same error after upgrading to Magento 2.4.4 using PHP 8.1. The error has to do with the first parameter in the trim() function returning null. As a temporary workaround you can add ?? '' after the $string parameter on line 151

**Comment by engcom-Lima** [comment] 2022-08-01 06:46
@magento give me 2.4-develop with edition ee

**Comment by engcom-Lima** [comment] 2022-08-01 06:48
@magento give me 2.4-develop instance with edition ee

**Comment by engcom-Lima** [comment] 2022-08-01 07:15
Hi @josiahglassone  ,

Thank you for your contribution and collaboration.

I have tried to reproduce both in local as well in cloud but issue is not reproducible. Even logs doesn't contain any issues. I think this happening during upgrade to `2.4.4` version.
Please inform us from which version you have upgraded to M2.4.4? 
One suggestion is while upgrading to Magento 2.4.4, kindly upgrade PHP version to 8.1 as suggested  PHP in [system requirements document.](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html).If you are facing same issue kindly let us know with exact scenario.

Thank you

**Comment by josiahglassone** [comment] 2022-08-01 12:35
@engcom-Lima I upgraded from Magento 2.4.3-p2 and PHP 7.4 to Magento 2.4.4 and PHP 8.1. The compatibility error came up when I was trying to open a link to a pdf on a product page. The link I was using was dynamically created by the [Sebwite/Magento2-Product-Downloads](https://github.com/Sebwite/Magento2-Product-Downloads) module

**Comment by JamesFX2** [comment] 2022-08-02 06:36
Yeah, same issue in Community 2.4.4

[28-Jul-2022 09:49:45 UTC] PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in /home/cloudpanel/htdocs/www.oursite.com/releases/2022_07_28_5_00_32_branch_master_v2.4.4/vendor/magento/module-media-storage/App/Media.php on line 151

Obviously this is linked to the placeholder image, as mentioned, via pub/get.php - I've checked and var/resource_config.json is there now and the errors have gone away.

**Comment by JamesFX2** [comment] 2022-08-02 06:38
Whatever generates that file fixes the above, thankfully.

**Comment by engcom-Lima** [comment] 2022-08-02 06:45
Hi @JamesFX2  ,

Thanks for your contribution and collaboration.

I need your confirmation as in above comments they have mentioned issue came only when they have upgraded to 2.4.4. 
Are you also facing this issue while upgrading only?

Thanks

**Comment by engcom-Lima** [comment] 2022-08-02 09:26
Hi @amarroni  @JamesFX2 @josiahglassone ,

I have tried to reproduce the issue but issue is not reproducible.
As suggested in above [comment](https://github.com/magento/magento2/issues/35788#issuecomment-1201144570) I have installed 2.4.3-p2 and upgraded to 2.4.4. But issue is not reproducible to me.
kindly provide more information in order to reproduce the issue.

Thanks

**Comment by JamesFX2** [comment] 2022-08-02 11:21
@engcom-Lima to repeat it in 2.4.4, you're going to need to delete var/resource_config.json - this won't exist after some deployments or after install. 

I didn't check develop before I contributed but this seems to have been fixed on https://github.com/magento/magento2/commit/b0c8fb3fb740cc842963015d311539ec564f62a1 AC-3109 @amarroni

**Comment by engcom-Lima** [comment] 2022-08-03 07:39
Hi @amarroni ,

Issue is not reproducible in latest `2.4-develop` branch and also mentioned in above comment issue has been fixed on https://github.com/magento/magento2/commit/b0c8fb3fb740cc842963015d311539ec564f62a1 AC-3109. Also,verified in codebase.
Hence, closing the issue.

Thanks

**Comment by xtremevision** [comment] 2022-08-12 18:33
Why close this issue? I am getting the same problem, including on a vanilla Magento 2.4.4 local instance.

**Comment by nuzil** [comment] 2022-11-07 09:30
It is still there on 2.4.4-p2

**Comment by engcom-Lima** [comment] 2022-11-07 10:06
Hi @nuzil & @xtremevision ,

Thanks for your contribution and collaboration.

Kindly provide us more information about the **steps to reproduce** the issue because issue is not reproducible to us.

Please find the screenshot for your reference:
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/60198022/200282407-ab3bfd44-7707-47bb-a862-83d730402f73.png">

Kindly check this issue in latest 2.4-develop and let us know if you are facing any issue.


Thanks

**Comment by engcom-Lima** [comment] 2022-12-07 07:19
Hi @nuzil & @xtremevision 

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.



Thanks

**Closed as completed by engcom-Lima** 2022-12-07 07:19 UTC
Labels: Issue: needs update

**Comment by braders** [comment] 2023-01-12 17:37
I believe that this ticket should be reopened, as this is causing occasional missing images on Magento 2.4.4 (as missing crops cannot be generated by `vendor/magento/module-media-storage/App/Media.php`).

**Comment by PaulGeomotiv** [comment] 2023-01-19 12:13
Confirm issue on Magento 2.4.4
