### ISSUE TITLE
Disabling module's output not saved

### ISSUE THREAD

**Issue by orbitrod** [magento/magento2#4424] opened 2016-05-06 20:29 UTC
## Steps to reproduce
1. Go to Stores > Configuration > Advanced > Advanced
2. Under Disable Modules Output, select disable next to a module.
3. Click Save
## Expected result
1. At the configuration page under Advanced > Advanced > Disable Modules Output, the drop down menu next to the previously selected module, should show as Disabled.
## Actual result
1.  At the configuration page under Advanced > Advanced > Disable Modules Output, the drop down menu next to the previously selected module, still shows as Enabled.

**Comment by mazhalai** [comment] 2016-05-09 17:47
@orbitrod "Disable Module's **Output**" is not the same as disabling module. Please go to  **System->Web Setup->Wizard->Component Manager** and click disable from the list of modules. Please note this feature is only available if you have deployed Magento 2 via `composer create-project` or a zip from magento.com. Will not work on git instance. Alternatively, you can use command line `bin/magento module:disable Module_Name`

Closing since this is not a bug.

**Comment by orbitrod** [comment] 2016-05-09 18:03
@mazhalai I understand that "Disable Module's Output" is not the same as disabling module.  If this is not a bug, then what is the expected result after disabling a Modules Output?  When I try it, it still says enabled at the Configuration page.  Should it not say disabled, after disabling a modules output?

**Comment by hshar7** [comment] 2016-05-09 18:17
@orbitrod this will help: http://magento.stackexchange.com/questions/68622/what-is-the-difference-between-disable-module-output-and-module-active-true :)

**Comment by mazhalai** [comment] 2016-05-09 18:18
@orbitrod your expected result says "selected module should be disabled" , perhaps you could clarify that it is on the configuration page and it related to Module's output and not disabling module itself. 

Reopening issue after clarification.

We have created MAGETWO-52620 to investigate and fix.

**Comment by orbitrod** [comment] 2016-05-09 18:33
@mazhalai My apologies, I will clarify.

**Comment by mazhalai** [comment] 2016-05-09 18:44
@orbitrod thank you!

**Comment by hshar7** [comment] 2016-05-10 15:07
Same as: #3722

**Closed as completed by hshar7** 2016-05-10 15:07 UTC
Labels: Issue: Ready for Work
