### ISSUE TITLE
Braintree payment method does not display on the checkout using php 7 or above.

### ISSUE THREAD

**Issue by benathey** [magento/magento2#3797] opened 2016-03-15 23:40 UTC
Magento 2.0.2

Braintree payment method does not display on the checkout using php 7 or above.

Tested on apache and nginx using php 5.6, 7.0.0, 7.0.3. 

Braintree payment method works fine on php 5.6. 

Magento successfully generates tokens using php 5.6. but does not for 7 and above. 
Php 7 and above encrypts the keys sent to braintree, braintree is unable to decrypt the keys, the tokens cant generate and the payment method will then not show on the checkout. 

This would need to be resolved really quite quickly a massive blocker for anyone using magento2, php7 and braintree. Please advise if there is a workaround. 

Cheers

**Comment by rudik99** [comment] 2016-03-16 02:57
this is the same issue i had for #3473 but was masked different PHP versions.
I am having this issue again since moving to php 7.0.3

**Comment by YevSent** [comment] 2016-03-25 19:39
Hi, @benathey, your issue perhaps related to problems which we already had with php 7.x. This issue fixed on develop branch.

**Comment by benathey** [comment] 2016-03-28 22:21
Great thanks.

**Comment by CKUDG** [comment] 2016-03-31 14:24
updated today to Magento 2.0.3 and it's still happening..

**Comment by YevSent** [comment] 2016-03-31 17:02
@CKUDG do you have any errors in logs or browser console? Sounds strange, because we also tested Braintree with php 7.0.x

**Comment by Doability** [comment] 2016-04-05 17:54
Hi  @joni-jones ,

I am also facing the same issue, below is the error I am getting in browser console:

`TypeError: this.messageContainer is undefined his.messageContainer.addErrorMessage({
`

Could you post the name of commit where you have placed related changes.

Thanks & Regards

**Comment by CKUDG** [comment] 2016-04-06 09:14
Hi @joni-jones @Doability , sorry for the late answer... The following workaround/fix solves the problem, but i think it's still not marched into the latest version 2.0.3, right?

https://github.com/magento/magento2/commit/32ca5c97304a1bd84cfbee7cec3d57c9307da9a6

Best regards,
Chris

**Comment by YevSent** [comment] 2016-04-11 07:36
Hi @CKUDG, unfortunately this fix is not merged into 2.0.4 version.

**Comment by YevSent** [comment] 2016-04-11 07:40
Hi @Doability, what changes do you mean? Your issue is still reproducible on the latest mainline version?

**Comment by alena-marchenko** [comment] 2016-05-16 14:15
Closing this issue due to no response, please feel free to reopen when you have an update.

**Closed as completed by alena-marchenko** 2016-05-16 14:15 UTC
