### ISSUE TITLE
All categories are not getting downloaded in single API call

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#34071] opened 2021-09-14 06:13 UTC
### Preconditions (*)

1. Magento version CE 2.4.
2.

### Steps to reproduce (*)

1. Call the api URL for Product Category download : https://www.impressionslast.com/rest/V1/categories/list?searchCriteria=al

Header :
Authorization:Bearer e8elwp2vjc9hg1vvfvdykc1uq3ch4wvy
Content-Type:application/json
Response :  
[Magento Response.txt](https://github.com/magento/magento2/files/7159236/Magento.Response.txt)

Find request/response here : 
[Magento Request Response.txt](https://github.com/magento/magento2/files/7159252/Magento.Request.Response.txt)

2.

### Expected result (*)

1. All 41 category should download in single call
2.

### Actual result (*)

1. we are getting only 20 category instead of 41 category
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2021-09-14 08:07
Verified the issue on Magento 2.4-develop branch and cannot able to reproduce the issue
Steps performed:
Generate Admin access token using POST: /rest/default/V1/integration/admin/token
Hit the Get Request: /rest/V1/categories/list?searchCriteria=al
No issue: All Categories list is retrieved.
In my case 42
![image](https://user-images.githubusercontent.com/60198231/133219927-2cfeb252-26eb-47ab-81a1-b196d0b3d9b8.png)
@webgility-amazonapi , kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you

**Comment by Quazz** [comment] 2021-09-14 09:18
@engcom-November In your own test you can see it is only returning 20 categories (by way of page_size 20). 

Compare how much data is returned with when you manually specify pagesize (?searchCriteria[pageSize]=42)

For some reason there is a hardcoded default of 20 pagesize on categories API call

**Comment by webgility-amazonapi** [comment] 2021-09-14 12:30
@engcom-November In your result set total count is 42 but its returning page size 20 as default, and is returning only first 20 records.

Please check once again.
Also what does the "CE" in magento version defines. Is that a minor version?

Thanks
Webgility team

**Comment by engcom-November** [comment] 2021-09-15 11:38
Hi @webgility-amazonapi ,

Just FYI.. List of all categories can be retrieved using GET API call: **/rest/all/V1/categories** - In my case all 42 categories are retrieved in the response.

But when trying to retrieve the data using Query Param - searchCriteria - for any other string/value entered - by default the response we get is for "page_size": 20 - **This is the current Magento behavior for all other GET API requests as well.**
Ex:  /rest/V1/categories/list?searchCriteria=al
/rest/V1/products/attributes/?searchCriteria=0
/rest/V1/returns?searchCriteria=al

However, by mentioning pageSize explicitly in searchCriteria, pagesize mentioned is retrieved as expected. That is using: Example:    ?searchCriteria[pageSize]=42
![image](https://user-images.githubusercontent.com/60198231/133425767-f76966af-5680-435e-bbd4-05060ebcab86.png)

![image](https://user-images.githubusercontent.com/60198231/133425893-9a00f974-aff0-4603-bb86-18df14d61367.png)

![image](https://user-images.githubusercontent.com/60198231/133426032-4bec0ae2-4f4e-4eab-b03d-252a3c691c59.png)

Kindly recheck again using "/rest/all/V1/categories" to retrieve all categories list or use Query param - searchCriteria[pageSize] to retrieve data based on the page size.

**Comment by webgility-amazonapi** [comment] 2021-09-20 06:45
Hello 

I wanted to understand what does this version indicates "CE 2.4." ? How is "CE 2.4." different from "2.4" version?

Webgility

**Comment by engcom-November** [comment] 2021-09-20 12:33
Hi @webgility-amazonapi ,

Magento CE 2.4 represents Community edition which can be used in Production environment. This software can be installed using composer.
Magento 2.4-develop is for Magento Open Source developers and is not production ready. This version can be installed using GIT
For more information about releases, kindly refer this [link](https://magento.com/tech-resources/download)
Thank you.

**Comment by engcom-November** [comment] 2021-09-29 05:44
Hi @webgility-amazonapi ,

We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-09-29 05:44 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.x
