### ISSUE TITLE
"Go to Checkout" button not working with grouped products

### ISSUE THREAD

**Issue by marvincaspar** [magento/magento2#3728] opened 2016-03-11 07:53 UTC
After I added a grouped product to the cart the pop up overview is broken and the "Go to Checkout" button is not working.
## Steps to reproduce
1. Install Magento v2.0.2 
2. Add grouped product to the cart.
3. Click "Go to Checkout" in pop up window
## Expected result
1. Grouped product is visible in pop up
2. Button "Go to Checkout" is working
## Actual result
1. Button is not working in pop up but in cart overview

![image](https://cloud.githubusercontent.com/assets/2600346/13696343/0eba244c-e766-11e5-88b8-055cb3ddc473.png)

**Comment by ishakhsuvarov** [comment] 2016-03-11 08:40
@mc388 Thank you for reporting this issue. We have tried but could not reproduce the result you described. 
Could you please check if you have any errors in the browser console?
Thank you.

**Comment by marvincaspar** [comment] 2016-03-11 09:03
Browser console didn't show any errors. I also flushed the cache but the same issue. You can see on the screenshot that the product is not show in the pop up window.

I'm using the magento 2 sample data.

**Comment by ishakhsuvarov** [comment] 2016-03-11 09:09
@mc388 Thank you for additional information. We are going to recheck it with sample data.

**Comment by ishakhsuvarov** [comment] 2016-03-11 10:57
@mc388 Checked with the items from Sample Data. This problem only happens when Grouped Product consists of Products with visibility setting **"Not Visible Individually"**. We have created an internal ticket `MAGETWO-50368` to fix the issue.

Thank you.

**Comment by ishakhsuvarov** [comment] 2016-03-25 08:16
@mc388 Fix for this issue has been delivered to the `develop` branch with the commit linked to the ticket. Closing for now, please feel free to reopen if you have any additional questions. Thank you.

**Closed as completed by ishakhsuvarov** 2016-03-25 08:16 UTC
Labels: Issue: Ready for Work, bug report, Issue: Format is not valid

**Comment by Rich8881** [comment] 2017-06-23 13:45
I have this same issue accompanied by this error , im using Mage 2.1.7 , however my error is not only breaking the checkout button but also the mini cart and Ajax search... basically everything Ajax :(

Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at HTMLDocument.<anonymous> ((index):191)
    at fire (jquery.js:3232)
    at Object.fireWith [as resolveWith] (jquery.js:3362)
    at Function.ready (jquery.js:3582)
    at HTMLDocument.completed (jquery.js:3617)
(anonymous) @ (index):191
fire @ jquery.js:3232
fireWith @ jquery.js:3362
ready @ jquery.js:3582
completed @ jquery.js:3617

**Comment by versdivers** [comment] 2017-11-30 05:57
So this is fixed in 2.3?
