### ISSUE TITLE
Deadlock when saving the order

### ISSUE THREAD

**Issue by ngoctruong1610** [magento/magento2#9756] opened 2017-05-25 03:44 UTC
I Started see that issue when our site under stress test loading, I'm not sure but in normal running our site does not met that issue

### Preconditions
Magento: 2.0.10 EE
PHP : 7.0.18

### Steps to reproduce
1.Using HP load runner to run the load test with 1000 vUsers
2.Placing order
3.Set send mail by cron "Asynchronous sending = YES"
4. Leave the cron run with default expression time 

> */1 * * * *

### Expected result:
- The problem will not appear

### Actual result
Issue 
```
36358:[2017-05-25 08:15:12] main.CRITICAL: PDOException: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction in /opt/nestle/magento/releases/20170524095845/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228
36359-Stack trace:
36360-#0 /opt/nestle/magento/releases/20170524095845/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
36361-#1 /opt/nestle/magento/releases/20170524095845/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
36362-#2 /opt/nestle/magento/releases/20170524095845/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
36363-#3 /opt/nestle/magento/releases/20170524095845/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
36364-#4 /opt/nestle/magento/releases/20170524095845/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('UPDATE `sales_o...', Array)
36365-#5 /opt/nestle/magento/releases/20170524095845/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(453): Zend_Db_Adapter_Pdo_Abstract->query('UPDATE `sales_o...', Array)
36366-#6 /opt/nestle/magento/releases/20170524095845/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(511): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('UPDATE `sales_o...', Array)
36367-#7 /opt/nestle/magento/releases/20170524095845/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(635): Magento\Framework\DB\Adapter\Pdo\Mysql->query('UPDATE `sales_o...', Array)
36368-#8 /opt/nestle/magento/releases/20170524095845/vendor/magento/module-sales/Model/ResourceModel/Attribute.php(101): Zend_Db_Adapter_Abstract->update('sales_order', Array, '(entity_id= 213...')
```

From my investigation

On file : vendor\magento\module-sales\Model\EmailSenderHandler.php
```
 public function sendEmails()
     {
         if ($this->globalConfig->getValue('sales_email/general/async_sending')) {
             $this->entityCollection->addFieldToFilter('send_email', ['eq' => 1]);
             $this->entityCollection->addFieldToFilter('email_sent', ['null' => true]);
             foreach ($this->entityCollection->getItems() as $item) {
                 if ($this->emailSender->send($item, true)) {
                     $this->entityResource->save(
                         $item->setEmailSent(true)
                     );
                 }
             }
```
>         }
>     }

This function will getting order which just created and trying to send mail then update the flag "email_sent=1"
I confirm this issue will not appear when the site in normal load, but in high load order entity take much time to save and can be updated several times before the transaction completely

So my understand is:

1. Order entity object is created
2. Cron getting the order entity without filtering based on order's status
3. Order entity trying to update few things several times but it takes a lots of time due to server is in high load
4. Cron hit when order entity is updating and causes the deadlock

**Comment by woutersamaey** [comment] 2017-06-09 21:56
I can see 3 solutions here
- Sending the mail using a (guaranteed single execution) message queue would be much better, or 
- updating just the single field instead of the entire order. There is just no need to process everything. Or,
- remove the field from the order table, and create a separate email log table that can be linked to the order table. This way we can keep track of all order mails sent, their timings and there is no need to change the order itself anymore. This would also make a handy feature on its own

**Comment by veloraven** [comment] 2017-07-05 14:14
@ngoctruongbc thank you for your report.
Given this issue is reported against Enterprise edition and should be reported via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant, please let me know if it was reported to Support in order to avoid duplicates.

**Comment by magento-engcom-team** [comment] 2017-09-26 22:00
@ngoctruongbc, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by VitaliyBoyko** [comment] 2020-02-18 09:19
Hi @magento-engcom-team 
The issue is still reproducible time by time on the Magento 2.3.2.

![image](https://user-images.githubusercontent.com/20116393/74721668-6c810200-5240-11ea-8c42-844c354e1512.png)

Thank you!

**Comment by JPNestNgocTruong** [comment] 2020-02-19 06:20
thanks @VitaliyBoyko 
much appreciate your effort on this matter

**Comment by engcom-Alfa** [comment] 2020-02-20 10:53
Hi @JPNestNgocTruong @VitaliyBoyko.
Looks like this is the same issue as in #8933.
Isn't? 
Thanks!

**Comment by VitaliyBoyko** [comment] 2020-02-20 11:12
HI @engcom-Alfa 
Nope, this issue is related to Sales Order functionality, the mentioned one to the Catalog Product functionality. Sales Tables could even have a separate DB if Database Sharding is being used. Moreover, as you can see from descriptions and comments, preconditions for issues are quite different. Thank you!

**Comment by VitaliyBoyko** [comment] 2020-02-20 11:39
The root of the issue seems to be the same. Closing this one. Thank you!

**Closed as completed by VitaliyBoyko** 2020-02-20 11:39 UTC
Labels: bug report, Progress: needs update, Issue: Clear Description, Issue: Format is valid
