### ISSUE TITLE
Subtotal is coming zero however subtotal_incl_tax has value.

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#38055] opened 2023-10-09 13:58 UTC
### Preconditions and environment

As a user I found that -> 

(1) Subtotal is coming zero however subtotal_incl_tax has value same case with shipping amount as well.

(2) Adjustment amount = 0 but adjustment_positive has some value. Also, while calculating grand_total we need to consider adjustment_positive as negative amount however for all other orders we need to consider adjustment_positive as +ve amount and adjustment_negative as -ve.

### Steps to reproduce

(1) Execute the API to download refunds.
(2) Verify if the calculations are correct.

**Store response ->** 

{
  "adjustment": 0,
  "adjustment_negative": 0,
  "adjustment_positive": 323.5,
  "base_adjustment": 0,
  "base_adjustment_negative": 0,
  "base_adjustment_positive": 323.5,
  "base_currency_code": "USD",
  "base_discount_amount": 0,
  "base_grand_total": 10.7,
  "base_discount_tax_compensation_amount": 0,
  "base_shipping_amount": 18.43,
  "base_shipping_incl_tax": 19.72,
  "base_shipping_tax_amount": 1.29,
  "base_subtotal": 0,
  "base_subtotal_incl_tax": 314.48,
  "base_tax_amount": 21.87,
  "base_to_global_rate": 1,
  "base_to_order_rate": 1,
  "billing_address_id": 282157,
  "created_at": "2022-09-14 17:42:39",
  "discount_amount": 0,
  "entity_id": 1610,
  "global_currency_code": "USD",
  "grand_total": 10.7,
  "discount_tax_compensation_amount": 0,
  "increment_id": "100000767",
  "invoice_id": 126072,
  "order_currency_code": "USD",
  "order_id": 141148,
  "shipping_address_id": 282156,
  "shipping_amount": 0,
  "shipping_incl_tax": 19.72,
  "shipping_tax_amount": 1.29,
  "state": 2,
  "store_currency_code": "USD",
  "store_id": 1,
  "store_to_base_rate": 0,
  "store_to_order_rate": 0,
  "subtotal": 0,
  "subtotal_incl_tax": 314.48,
  "tax_amount": 21.87,
  "updated_at": "2022-10-12 20:39:10",
  "items": [],
  "comments": []
}

### Expected result

Response should com in standard fashion and should provide valid information.

### Actual result

Store Amounts are not coming in standard fashion result in incorrect amount calculation.

**Here ->** 

Subtotal = 0 but  subtotal_incl_tax is 314.48 similarly shipping_amount = 0 but shipping_incl_tax: 19.72 , and in code we are considering  Subtotal  & shipping_amount .

And also there are cases where we are getting only shipping_amount and subtotal node in response with values.

Even if we consider, both amount with and without tax, then problem is coming in adjustment amount

Here, adjustment = 0 and adjustment_positive = 323.5 but in total calculation it has been consider as negative however in other orders it has been considered as positive only

### Additional information

{
  "adjustment": 0,
  "adjustment_negative": 0,
  "adjustment_positive": 323.5,
  "base_adjustment": 0,
  "base_adjustment_negative": 0,
  "base_adjustment_positive": 323.5,
  "base_currency_code": "USD",
  "base_discount_amount": 0,
  "base_grand_total": 10.7,
  "base_discount_tax_compensation_amount": 0,
  "base_shipping_amount": 18.43,
  "base_shipping_incl_tax": 19.72,
  "base_shipping_tax_amount": 1.29,
  "base_subtotal": 0,
  "base_subtotal_incl_tax": 314.48,
  "base_tax_amount": 21.87,
  "base_to_global_rate": 1,
  "base_to_order_rate": 1,
  "billing_address_id": 282157,
  "created_at": "2022-09-14 17:42:39",
  "discount_amount": 0,
  "entity_id": 1610,
  "global_currency_code": "USD",
  "grand_total": 10.7,
  "discount_tax_compensation_amount": 0,
  "increment_id": "100000767",
  "invoice_id": 126072,
  "order_currency_code": "USD",
  "order_id": 141148,
  "shipping_address_id": 282156,
  "shipping_amount": 0,
  "shipping_incl_tax": 19.72,
  "shipping_tax_amount": 1.29,
  "state": 2,
  "store_currency_code": "USD",
  "store_id": 1,
  "store_to_base_rate": 0,
  "store_to_order_rate": 0,
  "subtotal": 0,
  "subtotal_incl_tax": 314.48,
  "tax_amount": 21.87,
  "updated_at": "2022-10-12 20:39:10",
  "items": [],
  "comments": []
}

### Triage and priority

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-10-12 06:35
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-10-16 09:34
Hi @webgility-amazonapi,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

(1) Execute the API to download refunds.
(2) Verify if the calculations are correct.


<img width="1047" alt="Screenshot 2023-10-16 at 2 54 59 PM" src="https://github.com/magento/magento2/assets/51680745/6a298332-70b2-41a1-9e78-b88c2f95b978">


The Calculations are coming in the response as per the creditmemo details could you please let us know if we are missing anything and also please elaborate the steps to reproduce.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-10-27 05:48
Hi @webgility-amazonapi,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38055#issuecomment-1764089745 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-10-31 06:02
Hi @webgility-amazonapi,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-10-31 06:02 UTC
Labels: Issue: needs update, Reported on 2.4.x
