### ISSUE TITLE
Catalog product list widget not working with user defined product attribute

### ISSUE THREAD

**Issue by mattiasorgato** [magento/magento2#15655] opened 2018-06-01 09:37 UTC
### Preconditions
1. Magento 2.1.13
2. PHP 7.0.29

### Steps to reproduce
1. Fresh install of Magento
2. Add a product attribute with type boolean (Yes/No) via admin
3. Add the attribute to product and set the desired value
4. Create a CMS Widget of type **Catalog Products List**
5. In **Widget Options**, inside 'Conditions' selector, use the newly created attribute as a condition (attribute_code is 'Yes', in my case)
6. Go to the page where the Widget should be applied

### Expected result
When I go to the page where the Widget should be shown, I should see a product list with only the products with 'attribute_code' set to Yes.

### Actual result
With developer mode enabled, an Exception stacktrace shows in the page where the Widget is applied (with production mode enabled, the same Exception is shown in system log):
2 exception(s):
Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'at_is_highlighted_default.value' in 'where clause', query was: SELECT COUNT(DISTINCT e.entity_id) FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_category_product_index` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id='1' AND cat_index.visibility IN(2, 4) AND cat_index.category_id='2'
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0 WHERE (((IFNULL(`e`.`entity_id`, `at_is_highlighted_default`.`value`) IN ('1')) ))
Exception #1 (PDOException): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'at_is_highlighted_default.value' in 'where clause'

Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'at_is_highlighted_default.value' in 'where clause', query was: SELECT COUNT(DISTINCT e.entity_id) FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_category_product_index` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id='1' AND cat_index.visibility IN(2, 4) AND cat_index.category_id='2'
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0 WHERE (((IFNULL(`e`.`entity_id`, `at_is_highlighted_default`.`value`) IN ('1')) ))

**Comment by webspeaks** [comment] 2018-07-03 05:09
@magento-engcom-team Do we have a solution to this? I am having this issue in Magento 2.2.5 CE.

**Comment by engcom-backlog-nickolas** [comment] 2018-07-09 12:56
Hello @mattiasorgato, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by mattiasorgato** [comment] 2018-07-09 13:00
Thank you, waiting for your reply.

**Comment by pathakkrunal** [comment] 2018-07-14 12:54
I was facing same problem after updating 2.2.4 to 2.2.5 I have change scope of attribute to "Global" from "Store View" and it run for me.
I have also tried "Website" view but it also gives same error.
Change Attribute Scope to "Global" and problem will be solved.

**Comment by ccrothers** [comment] 2019-03-29 21:59
Reproduced on 2.1.13 and 2.1.17 with store scoped custom eav attributes. Seems like multi-store setups with certain distinct combinations of store/default values will cause this issue.

**Comment by sunnykhatri** [comment] 2019-05-04 09:29
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-05-04 09:29
Hi @sunnykhatri. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-05-04 09:30
Hi @sunnykhatri, here is your [Magento instance](https://i-15655-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-15655-2-3-develop.instances.magento-community.engineering/admin](https://i-15655-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sunnykhatri** [comment] 2019-05-04 09:48
Issue can't regenerate for version 2.3

Catalog Product List Widget with custom attribute:
![widget](https://user-images.githubusercontent.com/8664945/57177209-bea69180-6e7f-11e9-9d55-f675c612a730.png)

Widget working well on selected options
![home](https://user-images.githubusercontent.com/8664945/57177217-ce25da80-6e7f-11e9-90b3-4df5d47bca55.png)

**Comment by sunnykhatri** [comment] 2019-05-04 09:48
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-05-04 09:48
Hi @sunnykhatri. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-05-04 09:49
Hi @sunnykhatri, here is your [Magento instance](https://i-15655-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-15655-2-2-develop.instances.magento-community.engineering/admin](https://i-15655-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sunnykhatri** [comment] 2019-05-04 10:13
Can't reproduced on 2.2 also

**Comment by David-Magebinary** [comment] 2019-05-08 04:37
@sunnykhatri Hi, I am not sure how did you reproduce the issue but may I ask you to double check on the 2.3.x version.

I was setting up a Catalog product list widget same as @mattiasorgato but by using 2.3.1 version. 
```
## 2019-05-07 22:56:36
## 202487 ## QUERY
SQL: SELECT DISTINCT  `e`.*, `cat_index`.`position` AS `cat_index_position`, `price_index`.`price`, `price_index`.`tax_class_id`, `price_index`.`final_price`, IF(price_index.tier_price IS NOT NULL, LEAST(price_index.min_price, price_index.tier_price), price_index.min_price) AS `minimal_price`, `price_index`.`min_price`, `price_index`.`max_price`, `price_index`.`tier_price`, `at_manufacturer`.`value` AS `manufacturer`, `at_discounted`.`value` AS `discounted`, `stock_status_index`.`stock_status` AS `is_salable` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_category_product_index_store1` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id=1 AND cat_index.visibility IN(2, 4) AND cat_index.category_id=2
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0
 INNER JOIN `catalog_product_entity_int` AS `at_manufacturer` ON (`at_manufacturer`.`entity_id` = `e`.`entity_id`) AND (`at_manufacturer`.`attribute_id` = '665') AND (`at_manufacturer`.`store_id` = 0)
 INNER JOIN `catalog_product_entity_int` AS `at_discounted` ON (`at_discounted`.`entity_id` = `e`.`entity_id`) AND (`at_discounted`.`attribute_id` = '859') AND (`at_discounted`.`store_id` = 0)
 INNER JOIN `cataloginventory_stock_status` AS `stock_status_index` ON e.entity_id = stock_status_index.product_id WHERE (((IFNULL(`at_manufacturer`.`value`, 0) = '985') AND(IFNULL(`at_discounted`.`value`, 0) = '2755') )) AND (stock_status_index.stock_status = 1) ORDER BY `e`.`created_at` desc
 LIMIT 5
AFF: 5
TIME: 0.0003

## 2019-05-08 04:30:59
## 266931 ## QUERY
SQL: SELECT DISTINCT  `e`.*, `cat_index`.`position` AS `cat_index_position`, `price_index`.`price`, `price_index`.`tax_class_id`, `price_index`.`final_price`, IF(price_index.tier_price IS NOT NULL, LEAST(price_index.min_price, price_index.tier_price), price_index.min_price) AS `minimal_price`, `price_index`.`min_price`, `price_index`.`max_price`, `price_index`.`tier_price`, `at_manufacturer`.`value` AS `manufacturer`, `at_discounted`.`value` AS `discounted`, `stock_status_index`.`stock_status` AS `is_salable` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_category_product_index_store5` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id=5 AND cat_index.visibility IN(2, 4) AND cat_index.category_id=457
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '5' AND price_index.customer_group_id = 0
 INNER JOIN `catalog_product_entity_int` AS `at_manufacturer` ON (`at_manufacturer`.`entity_id` = `e`.`entity_id`) AND (`at_manufacturer`.`attribute_id` = '665') AND (`at_manufacturer`.`store_id` = 0)
 INNER JOIN `catalog_product_entity_int` AS `at_discounted` ON (`at_discounted`.`entity_id` = `e`.`entity_id`) AND (`at_discounted`.`attribute_id` = '859') AND (`at_discounted`.`store_id` = 0)
 INNER JOIN `cataloginventory_stock_status` AS `stock_status_index` ON e.entity_id = stock_status_index.product_id WHERE (((IFNULL(`at_manufacturer`.`value`, 0) = '985') AND(IFNULL(`at_discounted`.`value`, 0) = '2755') )) AND (stock_status_index.stock_status = 1) ORDER BY `e`.`created_at` desc
 LIMIT 5
AFF: 0
TIME: 0.0003
```
As you can see, in the query, the custom 'discounted' attribute code is been executed with the store_id = 0 condition. 

This is the query I have got for every single store view. It was always asking for the store_id, 0 and it is causing a lot of issues, like the products matching the condition (store level) would not been showing in the list widget. And to make them work you have to set the attribute value globally (default).

NOTE: And I can clearly see the store id for the index tables (price, catalog_category_product_index_store) are working correctly which is good!

Thanks!

**Comment by David-Magebinary** [comment] 2019-05-09 22:09
Hi Magento Team,

Any update for this one?

Regards,
David Qian

**Comment by David-Magebinary** [comment] 2019-05-23 22:35
Hi team, any update for this issue? Also, may you please bring the "Reproduced on 2.2.x", "Reproduced on 2.3.x" labels back?

**Comment by engcom-Bravo** [comment] 2019-09-25 13:00
Hello @mattiasorgato 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by engcom-Bravo** 2019-09-25 13:00 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Issue: Format is valid, Component: CatalogWidget
