### ISSUE TITLE
Tier pricing when price scope is Website

### ISSUE THREAD

**Issue by proatwork** [magento/magento2#22784] opened 2019-05-08 11:04 UTC
### Preconditions (*)
1. Magento 2.3.1 CE
1. PHP 7.1.23
1. Global-Settings catalog/price/scope = 1 (WEBSITE)
`bin/magento config:set catalog/price/scope 1`
1. Add store codes to URLs (for easy testing)

### Steps to reproduce (*)
1. Create two separate websites (I will name them "`Okay`" and "`Bug`")
1. Set the default base currency (All Storeviews scope) to **SEK*, display currency to *USD* and allowed currencies to *USD* and *EUR**
1. Set the "`Bug`" base currency to **EUR*, display currency to *EUR* and allowed currencies to *EUR** only
1. Under Stores > Currency > Currency Rates set:
   - 1SEK = 0.10USD = 0.093EUR
   - 1EUR = 10.75 SEK = 1.12USD
1. On a product
- in All Storeviews scope
![image](https://user-images.githubusercontent.com/1921333/57370510-fde32400-7198-11e9-9ad3-3372cce1ea3f.png)

    - set the price to 100SEK
![image](https://user-images.githubusercontent.com/1921333/57370545-10f5f400-7199-11e9-9d81-ce84e4b12849.png)

    - set a discount based tier:
![image](https://user-images.githubusercontent.com/1921333/57370599-3125b300-7199-11e9-9d9f-04988f807fc2.png)
- in "`Bug`" scope
     - set the price to 10EUR
![image](https://user-images.githubusercontent.com/1921333/57370565-1a7f5c00-7199-11e9-88d6-c967b1956839.png)

     - Ttier pricing will still exist/be inherited in this scope:
![image](https://user-images.githubusercontent.com/1921333/57370645-4864a080-7199-11e9-83d6-a2aa0e8e2438.png)

### Expected result (*)
1. In the "`Okay`" store, the tier pricing is correctly calculated
![image](https://user-images.githubusercontent.com/1921333/57370374-ae045d00-7198-11e9-9451-0428ba3f82f6.png)
1. In the "`Bug`" store,  the tier prices should be calculated correctly
![image](https://user-images.githubusercontent.com/1921333/57370338-9b8a2380-7198-11e9-882b-aaba9d74f980.png)

### Actual result (*)
1. In the "`Bug`" store, the tier pricing is incorrectly calculated
![image](https://user-images.githubusercontent.com/1921333/57370404-c2485a00-7198-11e9-8ed6-976fa7e8ed8a.png)

If you set a 1:1 currency rate between EUR and SEK then the tier prices work correctly, but the EUR prices on the "`Okay`" store are affected.

**Comment by proatwork** [comment] 2019-05-08 11:06
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-05-08 11:06
Hi @proatwork. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-05-08 11:07
Hi @proatwork, here is your [Magento instance](https://i-22784-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22784-2-3-develop.instances.magento-community.engineering/admin](https://i-22784-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by proatwork** [comment] 2019-05-08 11:20
I was able to reproduce bug in 2.3-develop instance

"`Okay`" Store
![Screen Shot 2019-05-08 at 14 19 48](https://user-images.githubusercontent.com/1921333/57371799-6aabed80-719c-11e9-9c9e-d3b1a4f04772.png)

"`Bug`" Store
![Screen Shot 2019-05-08 at 14 19 53](https://user-images.githubusercontent.com/1921333/57371800-6aabed80-719c-11e9-99b0-4a03f2e3421a.png)

**Comment by AlexWorking** [comment] 2019-05-08 15:14
Hello @proatwork. We confirm the issue, but please add to Your Steps to Reproduce one more step You most probably just forgot to add. The step concerning setting currency rates of SEK to EUR and EUR to SEK. Without this step everything works seemingly correctly, (though indeed it doesn't). Also please remove points with the sample data from the post as they are not necessary for the issue reproduction. Thank You.

**Comment by magento-engcom-team** [comment] 2019-05-08 15:17
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99608`, `MAGETWO-99609` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment] 2024-11-06 06:10
Hi @proatwork,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="1390" alt="Screenshot 2024-11-06 at 11 36 23" src="https://github.com/user-attachments/assets/db726624-c27c-43af-bf58-5cbab186c739">




<img width="1390" alt="Screenshot 2024-11-06 at 11 37 04" src="https://github.com/user-attachments/assets/cffae381-77a9-4eb2-9fe2-c586a53e03f5">




Tier prices were calculated correctly.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-11-06 06:10 UTC
Labels: Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Component: Store, Component: CurrencySymbol, Reproduced on 2.4.x, Priority: P2, Severity: S2, Progress: done, Area: Pricing
