### ISSUE TITLE
admin Password update.

### ISSUE THREAD

**Issue by Gopaal3** [magento/magento2#38352] opened 2024-01-14 12:46 UTC
### Preconditions and environment

- Magento version 2.4.4
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

- Customer put his credentials for login
- He got asked for 2fa auth, and he puts the code
- He gots redirected to a "change password page" (that actually has a lot of other fields). Admin changes his password, clicks "Save" button.

### Expected result

- ✅ You should see the message that your password was changed
- ✅ You should be redirected to the home admin page (because your main flow was a log in flow, not the change password)

### Actual result

- ✅ You should see the message that your password was changed
- ❌ You're still see the "change password" page, so you think that Magento asks you to change a password one more time
- 

### Release note

when i click save . it is not working

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by andrewbess** [comment] 2024-01-14 21:52
Hello @Gopaal3 
Thank you for your collaboration
I tried to reproduce described problem on the Magento 2.4.4
It works great
Could you please provide more information
Looks like you have 3rd-party extension that can provoke the problem
Thank you in advance.

**Comment by engcom-Bravo** [comment] 2024-01-15 05:35
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-01-15 05:47
@andrewbess Thanks for your contribution and collaboration.

Hi @Gopaal3,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

1.login admin
2.update password


![Screenshot from 2024-01-15 11-15-44](https://github.com/magento/magento2/assets/51680745/eca07550-f1fb-42c5-9097-27a0ae913ee8)


We are able to update the password successfully.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by Franciscof-Serfe** [comment] 2024-01-17 02:34
@magento give me 2.4-develop instance

**Comment by Franciscof-Serfe** [comment] 2024-01-17 03:20
In addition to what @ihor-sviziev said, it would be great for the admin user experience if the message said something like:

"You saved the changes to the account"
either
"You saved changes to [field name]" (Password, email, name, etc.)

**Comment by engcom-Bravo** [comment] 2024-01-22 10:45
@ihor-sviziev @Franciscof-Serfe Thanks for your Contribution!.

Hi @Gopaal3,

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.

**Steps to Reproduce**


- Customer put his credentials for login
- He got asked for 2fa auth, and he puts the code
- He gots redirected to a "change password page" (that actually has a lot of other fields). Admin changes his password, clicks "Save" button.


![Screenshot from 2024-01-22 11-47-13](https://github.com/magento/magento2/assets/51680745/f446e928-97c9-424d-a5e5-b694e77a2f91)



Password has been changed but still we are in Change Password page.

Hence Confirming the issue.

Thanks.

**Comment by AlexDev4** [comment] 2024-03-17 22:12
@magento I am working on this

**Comment by AlexDev4** [comment] 2024-03-17 22:12
@magento add to contributors team

**Comment by AlexDev4** [comment] 2024-03-17 22:14
@magento I am working on this

**Comment by Franciscof-Serfe** [comment] 2024-05-04 05:08
@magento I'm working on this

**Comment by engcom-Bravo** [comment] 2024-10-14 07:38
Hi,

Thank you for your contribution!

The Magento core engineering team is working on the issue which you have addressed in this PR. Team will cherry pick the commits from your PR and may do further implementation to cover few more scenarios as needed. We will reach out to you if we need more information. For now, you can pause work on this PR.

Thank you once again!

**Comment by engcom-Bravo** [comment] 2024-12-18 08:26
Hi @Gopaal3,

As per this comment https://github.com/magento/magento2/pull/38696#issuecomment-2550667025 we are reopening the issue for further process.

Thanks.

**Closed as completed** 2024-12-30 14:06 UTC
Labels: Component: Admin, Priority: P2, Progress: done, Area: Account, Reported on 2.4.4

**Comment by engcom-Charlie** [comment] 2024-12-31 08:22
Hello,

The issue got fixed in the scope of the internal Jira ticket AC-10886 by the internal team
Related commits: https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-10886&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta2.

Thanks
