### ISSUE TITLE
Custom options additional prices don't exist on the cart or quote

### ISSUE THREAD

**Issue by craft-tyler** [magento/magento2#2330] opened 2015-11-11 18:48 UTC
If a user selects a custom option with an additional price and the user adds this product to the cart, the price does not reflect the new price in the cart or checkout.

![image](https://cloud.githubusercontent.com/assets/2175652/11099671/ac4664c8-887a-11e5-82fe-95430c73fc72.png)

**Comment by azhar411** [comment] 2016-06-09 12:38
I have text field width which enter the value in text box width which is convert into meter and multiply by the selected radio button value. baseprice_width_gether

**Comment by vzabaznov** [comment] 2016-06-22 12:52
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment] 2016-07-14 08:19
Hi, @craft-tyler thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.

**Closed by vzabaznov** 2016-07-14 08:19 UTC
Labels: MX, needs update
