### ISSUE TITLE
Update 2.1.2 to 2.1.3 --> Out of stock products have no prices in frontend

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#7811] opened 2016-12-15 09:45 UTC
We just updated from 2.1.2 to 2.1.3 

One Problem we realized is that out of stock products do not have prices anymore in the frontend (product page and category pages).

Can anyone else confirm this?
I the qty is 0 the price is just gone from the product.

Also we realized many new bugs in 2.1.3 and also only a handful bugs are fixed again 👎 .
Think time to put our work on another system - we really get a problem with magento2 now as bugfixing is the main time consumer since one year.

**Comment by FloWord** [comment] 2016-12-15 20:40
Same problem.

**Comment by royvanos** [comment] 2016-12-16 10:04
Same problem after updating from 2.1.2 to 2.1.3.

**Comment by veloraven** [comment] 2016-12-19 12:58
@andidhouse thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by staffrob** [comment] 2016-12-21 00:34
I think this is the same issue I am having 2.1.3 https://github.com/magento/magento2/issues/7908

**Comment by veloraven** [comment] 2016-12-21 18:38
I'm closing this issue as a duplicate of #7908 which is better structured.

**Closed as completed by veloraven** 2016-12-21 18:38 UTC
Labels: Progress: needs update
