### ISSUE TITLE
Product Page doesn't show categories in breadcrumbs (Magento 2.3.4) *HELP*

### ISSUE THREAD

**Issue by jackrevate** [magento/magento2#27898] opened 2020-04-19 16:27 UTC
### Preconditions (*)

1. 7.2
2. 2.3.4

### Steps to reproduce (*)

1. Visit categories, go through the motions you'll see breadcrumbs work correctly.
2. Visit categories and click on a product, the breadcrumbs that were on the categories will disappear and only show a direct breadcrumb for the product (not a trail breadcrumb list as expected).

### Expected result (*)

1. Breadcrumbs from categories to products so you can click back onto the categories, currently you can't do this.

### Actual result (*)

1. Bread crumb only shows for the product so you can't go back.

**Comment by shikhamis11** [comment] 2020-04-19 18:30
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-19 18:30
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-19 18:31
Hi @shikhamis11, here is your [Magento instance](https://i-27898-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27898-2-4-develop.instances.magento-community.engineering/admin_afc1](https://i-27898-2-4-develop.instances.magento-community.engineering/admin_afc1)
Login: `9bf7f265` Password: `41648d14f4e0`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2020-04-19 18:50
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment] 2020-04-19 18:50
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment] 2020-04-19 18:51
Hi @shikhamis11, here is your [Magento instance](https://i-27898-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-27898-2-3-4.instances.magento-community.engineering/admin_8109](https://i-27898-2-3-4.instances.magento-community.engineering/admin_8109)
Login: `361fc435` Password: `6a273f6df29f`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2020-04-19 19:01
@jackrevate thank you for reporting this issue . I checked this issue on 2.3.4 as well as 2.4-develop instances but not able to reproduce this issue .. can you also check and confirm ? 
Also shared screenshot / video if you are able to reproduce this issue

**Comment by jackrevate** [comment] 2020-04-20 11:42
Appears to be caused by Amasty SEO extensions - will confirm shortly!

**Comment by shikhamis11** [comment] 2020-05-07 17:15
@jackrevate  I am closing this issue as I am not able to reproduce this issue . feel free to reopen this issue if you are able to reproduce it on 2.4-develop instance

**Closed as completed by shikhamis11** 2020-05-07 17:15 UTC
Labels: Issue: Format is valid, Reported on 2.3.4

**Comment by chequille** [comment] 2020-09-17 05:29
Maybe I know the reason. I have the same problem with the breadcrumbs on product page. They are not showing the category name if the category is not included in the menu. See screenshot:
![grafik](https://user-images.githubusercontent.com/15807794/93423509-704c3400-f8b6-11ea-96d7-bc595eecf2d7.png)
if I set my cateogories to "Show in Menu = Yes", than the breadcrumbs on the productpage do show the category again.

Diffrence on product pages is, that the breadcrumbs are rendered with some js script. On catalog pages, they are rendered with a template phtml file.

It seems, that iin the js script categories which are set to "Not in Menu" are not  there. I would understand that they are not in the breadcrumb when they are disabled (this makes sense), but not if I decide to have the categories not shown in the menu of categories.

Could somebody have a look into this please

BR
Chequille

**Comment by nopenopenope** [comment] 2021-11-09 22:51
Seems like the same behaviour is existing in Magento 2.4.3 - and its pretty annoying, because we have to touch all categories and hide them with a fix from our Navigation afterwards. Jesus! Magento2, what are you doing?!

**Comment by nicholasscottfish** [comment] 2021-12-10 15:20
Is there any update on this? Any patch or fix?

**Comment by isabchev** [comment] 2025-01-28 20:14
I know maybe it is a little bit late but I had same problem and found solution. 

Problem is that magento product page use asynchronous javascript to load breadcrumbs and it construct its category tree from top menu categories. When category is not included in top menu javascript can't construct category tree. 

Fortunately category pages use other template for breadcrumbs which not use javascript and top menu and also works for product pages.

in your
app/frontend/Theme/default/Magento_Catalog/layout/catalog_product_view.xml
add this two lines of code and you will use category breadcrumbs template which not depend if category in included in menu

<referenceBlock name="breadcrumbs" template="Magento_Theme::html/breadcrumbs.phtml"></referenceBlock>
        <block class="Magento\Catalog\Block\Breadcrumbs" name="zzz"></block>
