### ISSUE TITLE
Magento 2.2.4 Cart Price Rules not working

### ISSUE THREAD

**Issue by crtl** [magento/magento2#17072] opened 2018-07-24 14:22 UTC
Hello,
creating cart price rules with conditions in magento 2.2.4 is not possible.
### Preconditions
Magento 2.2.4

### Steps to reproduce
1. Create a cart price rule with product filter

### Expected result

1. Only products which match the conditions should be discounted

### Actual result

1. Everything is discounted

**Comment by magento-engcom-team** [comment] 2018-07-24 14:22
Hi @crtl. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@crtl do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment] 2018-07-25 12:05
Hello @crtl, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ravi-chandra3197** [comment] 2018-10-22 07:01
Hello @crtl 
can you provide more information like which type of condition not working when Create a cart price rule with product filter

**Comment by Ajithkumar-Dckap** [comment] 2019-05-04 05:31
I am working on this at #dmdcindia1

**Comment by Ajithkumar-Dckap** [comment] 2019-05-04 06:01
I am working on this at #dmdcindia1

**Comment by engcom-Charlie** [comment] 2019-09-23 07:45
Hello @crtl 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by engcom-Charlie** 2019-09-23 07:45 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Component: SalesRule
