### ISSUE TITLE
Category Page - "add to cart" button not functioning as expected

### ISSUE THREAD

**Issue by duffner** [magento/magento2#4079] opened 2016-04-09 15:45 UTC
## Steps to reproduce
1. Move your mouse towards the "add to cart" button from the bottom of a product
2. No add to cart button is populated 
## Expected result
1. You should see the "add to cart" button 
2. You should not have move all the way back to the top of the product to see the cart. 
3. I should not be able to place my mouse pointer above the "add to cart" button without it showing. 
## Actual result

1.No add to cart button is populated,  
2. You can see my current pointer location by where my cross-hair is from the screen shot. 

<img width="612" alt="screen shot 2016-04-09 at 8 39 33 am" src="https://cloud.githubusercontent.com/assets/7387019/14404593/6eed8b94-fe2f-11e5-9b86-f651b16c29a5.png">

**Comment by antboiko** [comment] 2016-04-11 09:09
Hello @duffner , kindly ask you to provide more details about your use case. The cursor on your screenshot isn't placed over the product.

"Add to Cart" button along with "Add to Wish List" and "Add to Compare" appears while hovering over the product.

Best,
Anton.

**Comment by pboisvert** [comment] 2016-05-02 22:28
Anton--please close if no reply to request for information after this long.

**Comment by duffner** [comment] 2016-05-02 22:39
Sorry about the delay, however, if you take a second look, you will notice that the cursor is directly over the add to cart button.

**Comment by duffner** [comment] 2016-05-02 22:51
Anton, I understand the  "Add to Cart", "Add to Wish List" and "Add to Compare" show up most of the time when hovering.  However, If you move up from the bottom of a product, you end up ontop of where the Add to Cart button should be, but it's not there because the Anchor is not being triggered . 

http://www.filedropper.com/frontendbug   This is a quickTime video displaying the bug as a screen cast. 

Hope this helps.

**Comment by vil11** [comment] 2016-05-04 14:50
The 1st hover on your video isn't performed because correspondent browser window isn't active (see browser header action panel). Once you activate browser window, the hover works as expected - Product plate appears by hover on image/price.

---

:sunny: dima vilchynskyi, M2 QA

**Comment by antboiko** [comment] 2016-05-04 14:59
@duffner I'm closing this issue as it's not a bug.

Regards,
Anton.

**Closed as completed by antboiko** 2016-05-04 14:59 UTC

**Comment by duffner** [comment] 2018-04-07 15:08
@antboiko, this is still a bug many years later.  The hover state of your actions section needs to wrap the entire product.   In this case, it only wraps the name and product image.  So if you move your mouse up from the bottom where the add to cart button is, the hover is not triggered.
