### ISSUE TITLE
Admin User can not see categories details and configurations nor create new categories 

### ISSUE THREAD

**Issue by nachosan2** [magento/magento2#35771] opened 2022-07-14 12:40 UTC
### Preconditions and environment

Adobe Commerce 2.4.4

### Steps to reproduce

1. In Admin backend, click side panel Catalog > Categories
![image](https://user-images.githubusercontent.com/109289055/178983805-5568d7ef-90c1-496e-9358-2479d0558f5e.png)
2. Be able to see the Default Category configuration
3. Or create a Root Category o Subcategory 

### Expected result

User can see categories configurations or can create new Root Categories and Subcategories.

### Actual result

Deprecated Functionality: stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /app/vendor/magento/module-price-permissions/Observer/AdminhtmlBlockHtmlBeforeObserver.php on line 125

![image](https://user-images.githubusercontent.com/109289055/178983343-98290265-fbd3-4d58-9c7b-e65e7038aa26.png)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by youngcrush** [comment] 2022-07-14 16:03
@magento give me 2.4-develop enterprise edition instance

**Comment by engcom-Lima** [comment] 2022-07-15 05:43
@magento give me 2.4-develop enterprise edition instance

**Comment by engcom-Lima** [comment] 2022-07-15 05:57
Hi @nachosan2 

I have tried to reproduce the issue but issue is not reproducible to me.
Kindly upgrade your PHP to PHP 8.1 with 2.4.4 as per the [document](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html). 
After upgrading to 8.1 follow below steps:
1. Restart your apache.
2. Run bin/magento setup:upgrade.
3. Clear indexer and cache.
If still you are facing this issue then please provide us more information in order to reproduce the issue.

Thanks!!

**Comment by engcom-Lima** [comment] 2022-07-29 07:51
Hi @nachosan2 ,

Since there is no update from 14 days. Hence, closing this issue if you are facing any issue you can reopen this ticket or log new issue.

Thanks

**Closed as completed by engcom-Lima** 2022-07-29 07:51 UTC
Labels: Issue: needs update
