### ISSUE TITLE
Sample data 1.0.0beta raises error "undefined method getWriteConnection()"

### ISSUE THREAD

**Issue by sydekumf** [magento/magento2#1775] opened 2015-09-02 11:57 UTC
I installed the sample data **after** the installation of Magento via console and I get the following error: 
Fatal error: Call to undefined method Magento\Catalog\Model\Resource\Product\Interceptor::getWriteConnection() in /private/var/www/magento/magento2/app/code/Magento/SampleData/Module/Catalog/Setup/Product/Gallery.php on line 144

If you search for **getWriteConnection()** in the whole Magento source you won't even find this method :-) So how is it supposed to work? Thanks a lot.

**Comment by mazhalai** [comment] 2015-09-02 13:55
@sydekumf this is a known issue if you are using the develop branch. If you need to use sample data, please get the codebase from the `master` branch.

**Comment by mazhalai** [comment] 2015-09-02 13:56
Closing as duplicate of #1636 , #1610 , and #1757.

**Closed by mazhalai** 2015-09-02 13:56 UTC
