### ISSUE TITLE
API product bulk PUT request causes exception

### ISSUE THREAD

**Issue by lykciv** [magento/magento2#34705] opened 2021-11-24 13:33 UTC
### Preconditions (*)

Magento version 2.4.3-p1

### Steps to reproduce (*)

API request example 

```
curl --location --request PUT 'https://example.com/rest/all/async/bulk/V1/products' \
--header 'Authorization: Bearer 12345678' \
--header 'Content-Type: application/json' \
--data-raw '[
    {
        "product": {
            "sku": "24-MB04",
            "name": "Strive Shoulder Pack"
        }
    }
]'
```

### Expected result (*)

1. Response 202 with bulk operation information

### Actual result (*)

1. Response 500 Internal Server Error with message: An error has happened during application run. See exception log for details.
2. Exception details
```
report.CRITICAL: TypeError: Argument 3 passed to Magento\Framework\Webapi\ServiceInputProcessor::process() must be of the type array, string given, called in /path/vendor/magento/module-webapi-async/Controller/Rest/Asynchronous/InputParamsResolver.php on line 154 and defined in /path/vendor/magento/framework/Webapi/ServiceInputProcessor.php:172
```

### Workaround
The POST method does not cause this exception. A possible workaround could be to use POST instead of PUT.

### Patch
To avoid the exception, you can use the following patch.
```
--- a/vendor/magento/module-webapi-async/Controller/Rest/Asynchronous/InputParamsResolver.php
+++ b/vendor/magento/module-webapi-async/Controller/Rest/Asynchronous/InputParamsResolver.php
@@ -97,6 +97,10 @@
         $this->requestValidator->validate();
         $webapiResolvedParams = [];
         foreach ($this->getInputData() as $key => $singleEntityParams) {
+            if (!is_array($singleEntityParams)) {
+                continue;
+            }
+
             $webapiResolvedParams[$key] = $this->resolveBulkItemParams($singleEntityParams);
         }
         return $webapiResolvedParams;
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by rodrigowebjump** [comment] 2021-11-24 13:36
@magento give me 2.4-develop instance

**Comment by ihor-sviziev** [comment] 2021-11-24 15:02
@sidolov, FYI I set priority to P2 as it causing TypeError

**Comment by adamkarnowka** [comment] 2022-03-21 14:30
This bug occurs for all async/bulk operations, for example creating shipments for orders, because params added in GET (f.e `byOrderId/ship`) are parsed to request data, and this part cannot be resolved by service input processor.
 
Patch added by @lykciv does the trick though.

**Comment by mam-wh** [comment] 2022-05-05 07:35
This issue occurs on all bulk requests, i think the solution would be `$this->getInputData()` should only return any the body not any parameters. In my case the there are 2 parameters added to the input data which breaks the api calls 
- bySku (Not sure from where it came from)
- PHPSTORM (I added this for debugging)
![image](https://user-images.githubusercontent.com/92787496/166879707-1dd36abd-bcfb-4244-903b-99aa67126327.png)

**Comment by engcom-November** [comment] 2022-09-05 14:46
Hi @lykciv ,
This issue is not reproducible anymore on Magento 2.4-develop branch as it has been taken care in internal [JIRA](https://jira.corp.magento.com/browse/ACP2E-763) ticket and [commits](https://github.com/magento/magento2/search?q=ACP2E-763&type=commits). Hence closing this issue. Please reopen / create new issue with missing steps if the issue is still reproducible on latest Magento version.
![image](https://user-images.githubusercontent.com/60198231/188474831-9c84b788-5c1c-4e54-9635-0f4cb75f7bdc.png)

**Closed as completed by engcom-November** 2022-09-05 14:46 UTC
Labels: Priority: P2, Severity: S1, Progress: done, Issue: ready for confirmation, Area: APIs
