### ISSUE TITLE
Unable to disable cache type: `compiled_config`

### ISSUE THREAD

**Issue by adamzero1** [magento/magento2#36824] opened 2023-02-09 07:40 UTC
### Preconditions and environment

- Magento version: 2.4.5-p1
- Anything else that would help a developer reproduce the bug
When in production mode you are unable to disable `compiled_config` cache type.
Magento is automatically enabling this cache type on every request (including cli requests).

### Steps to reproduce

1. `php bin/magento deploy:mode:set production`
2. `php bin/magento cache:disable compiled_config`
3. `php bin/magento cache:status | grep compiled_config`

### Expected result

Expected output of the last command is: 
```
               compiled_config: 0
```

### Actual result

Expected output of the last command is: 
```
               compiled_config: 1
```

### Additional information

I understand that in production mode it would be ideal for this to be on, but that isn't the responsibility of the framework at this point.
The code forcing the cache type on is here: https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/App/ObjectManager/Environment/Compiled.php#L119-L121
Happy to create a PR where this is removed, unless there is a good reason why this is here?

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-02-09 10:14
Hi @adamzero1 

Verified the issue in 2.4-develop branch...Hence we are confirming the isssue.

Magento version 2.4-develop
PHP 8.1

Steps we followed by:
1.Install Magento instance
2.Go to Root directory
3.Run the below commands
php bin/magento deploy:mode:set production
php bin/Magento cache:disable compiled_config
php bin/Magento cache:status | grep compiled_config

We are getting Actual result which is Expected output of the last command is:

               compiled_config: 1

Screenshot for your reference:
<img width="1512" alt="Screenshot 2023-02-09 at 2 32 18 PM" src="https://user-images.githubusercontent.com/60198592/217783726-fc7f4775-d732-4f49-8cfa-c7753505bf65.png">

Let us know if we missing anything!!!

Thanks!!!

**Comment by adamzero1** [comment] 2023-02-09 13:20
Hi @engcom-Dash ,

Glad you could replicate, would you like me to submit a "fix" or is this intended functionality?

**Comment by engcom-Charlie** [comment] 2023-02-14 11:18
As discussed in triage call, requesting @engcom-Hotel to analyse this issue further.

Thank you!

**Comment by engcom-Hotel** [comment] 2023-02-21 11:32
As per the discussion in the triage call, we need confirmation from PO on this issue. Hence moving this issue on hold.

**Comment by engcom-Hotel** [comment] 2023-03-29 07:05
We have received the confirmation on this issue, according to them, they are not sure why this might be ever needed to disable this system cache type. 

Hence closing this issue.

**Closed as completed by engcom-Hotel** 2023-03-29 07:05 UTC
Labels: Reproduced on 2.4.x, Triage: Need PO Confirmation, Issue: On Hold, Area: Admin UI, Reported on 2.4.5-p1

**Comment by JonathanHelvey** [comment] 2024-02-09 20:34
Certain Themes require all caches to be disabled when installing. This is an issue and the issue is happening on all current magento2 versions in both developer and production mode. 
<img width="475" alt="Screenshot 2024-02-09 at 3 34 00 PM" src="https://github.com/magento/magento2/assets/33816020/0132626c-907f-489b-9d65-ea4d521e090d">
