### ISSUE TITLE
Configurable product with swatch AND dropdown attributes not working like how it should be

### ISSUE THREAD

**Issue by BouwStation** [magento/magento2#37352] opened 2023-04-09 11:18 UTC
### Preconditions and environment

- Magento version 2.4.5

### Steps to reproduce

1. Create a configurable product with only dropdown attribute - For example https://magento-802601-3429172.cloudwaysapps.com/only-dropdown-configurable.html
2. Create a configurable product with only swatch attribute - For example https://magento-802601-3429172.cloudwaysapps.com/only-swatch-configurable.html
3. Create a configurable product with Swatch AND Dropdown attribute - For example https://magento-802601-3429172.cloudwaysapps.com/mix-dropdown-and-swatch-configurable.html

### Expected result

1. This product makes the options required. Workflow = when you press higher level dropdown, you need to input all attributes again. LOGIC = GOOD
2. This product makes the options not required. Workflow = when you press another level, you do not need to input all other attributes. LOGIC = GOOD
3. This product makes the options not required including the dropdown attributes. So this must be a bug or there must be somewhere a place to CHOOSE the workflow?

### Actual result

1. GOOD
2. GOOD
3. Must be DROPDOWN = REQUIRED, SWATCH = NOT REQUIRED

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by BouwStation** [comment] 2023-04-09 12:09
@magento give me 2.4-develop instance

**Comment by BouwStation** [comment] 2023-04-11 10:35
Hi, i already made an own test environment. Check the links i have placed above. The test instance is not working.... Please can someone provide a fix for this.

**Comment by engcom-Dash** [comment] 2023-04-13 00:44
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-04-13 05:16
@magento give me 2.4-develop instance

**Comment by BouwStation** [comment] 2023-04-13 09:28
I cannot open the instances, but can you check mine problem on mine own environment? Maybe you got a quick solution for it?

**Comment by engcom-Bravo** [comment] 2023-04-20 08:45
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-04-20 13:20
Hi @BouwStation,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Create a configurable product with only dropdown attribute
- Create a configurable product with only swatch attribute
- Create a configurable product with Swatch AND Dropdown attribute

<img width="874" alt="Screenshot 2023-04-20 at 3 55 49 PM" src="https://user-images.githubusercontent.com/51680745/233339742-d8a284a5-caee-491f-84d4-9c39cbdd57df.png">


<img width="994" alt="Screenshot 2023-04-20 at 3 56 12 PM" src="https://user-images.githubusercontent.com/51680745/233339808-f91c2673-7392-44be-8480-6aed27bb2df9.png">


<img width="1096" alt="Screenshot 2023-04-20 at 3 56 42 PM" src="https://user-images.githubusercontent.com/51680745/233339852-1533a29a-eb3d-4737-90f5-e3f1a5e7943b.png">



https://user-images.githubusercontent.com/51680745/233339883-776c527c-eafe-4730-82af-49fb79890549.mov



When we add product without dropdown attribute it will show us **it is a required field** it is working as expected.It is an expected behaviour of Magento.


Kindly let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-05-04 06:05
Hi @BouwStation,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-05-04 06:05 UTC
Labels: Issue: needs update, Reported on 2.4.5

**Comment by BouwStation** [comment] 2023-05-04 14:48
Dear Engcom-Bravo,

The logic is different when a swatch is added. Add 2 dropdowns in both version (with swatch and witouth swatch). When you change the most upper one, all goes white and you need to select again. When Swatch is enabled this is not the style how it works.

**Comment by BouwStation** [comment] 2023-05-05 14:16
> Hi @BouwStation,
> 
> We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
> 
> Thanks.

Can you open this again? And check mine message.
