### ISSUE TITLE
"is_subscribed" extension attribute not populating in customer GET /V1/customers/search?searchCriteria API

### ISSUE THREAD

**Issue by lenlorijn** [magento/magento2#25410] opened 2019-10-31 16:07 UTC
It looks like internal bug MAGETWO-71829 was not fully solved. It made the "is_subscribed" field available in the API.
However this was not done for results of the search?searchCriteria API method.

More information: https://github.com/magento/devdocs/issues/1384
### Preconditions (*)
1. Magento is at version 2.3.2 & 2.3-develop

### Steps to reproduce (*)
1. Install Magento 
2. Add one or more customers
3. Request a list of customers through the  /V1/customers/search?searchCriteria API method
4. Notice there are no extension attributes

### Expected result (*)
1. Expected behavior: have a extension_attribute section that includes "is_subscribed" field. Just like when /V1/customers/:id: is requested.
![image](https://user-images.githubusercontent.com/51680850/68113623-e218ca80-fefc-11e9-99ca-fdb412e02635.png)

### Actual result (*)
1. no extension_attribute is present, no "is_subscribed" field is present.
![image](https://user-images.githubusercontent.com/51680850/68113658-f066e680-fefc-11e9-8eeb-d1ee41ed6a3e.png)

**Comment by magento-engcom-team** [comment] 2019-11-04 10:17
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22735` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dmanners** [comment] 2019-11-08 11:16
Seems that the original fix only covered the only newsletter subscription information on the getById method. I wonder if the problem is that the Customer model does not actually use the class `Magento\Customer\Model\Data\Customer` but builds it's data model via `Magento\Customer\Model\Customer::getDataModel` which does not deal with the extension attributes methods.

https://github.com/magento/magento2/commit/8f3a4ed5f657cce3caa181a40b14f3d3f94e8221#diff-8b13fe3225a8e5f17fa52fa6c5b74edaR151

**Comment by koenner01** [comment] 2019-11-18 14:55
Duplicate of my issue from 2018
https://github.com/magento/magento2/issues/13252

**Comment by VladimirZaets** [comment] 2020-07-28 18:52
This issue is fixed in scope of https://github.com/magento/magento2/issues/13252

**Closed as completed by VladimirZaets** 2020-07-28 18:52 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Api, Triage: Dev.Experience
