### ISSUE TITLE
Cannot login - form_key validation failure

### ISSUE THREAD

**Issue by JasonMortonNZ** [magento/magento2#3664] opened 2016-03-05 07:38 UTC
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Create a new customer account
3. Log out, and try to log back in again.
4. After submitting the customer login form, I get continually redirected back to the login form.

The `validate()` method on this line is returning false https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Controller/Account/LoginPost.php#L106 - a

A quick dump of the results shows that `$request->getParam('form_key', null)` is different to `$this->_formKey->getFormKey()` in the `Magento\Framework\Data\Form\FormKey\Validator` class.
## Expected result
1. Logging in as a valid customer should work.
## Actual result
1. Logging in as a valid customer fails because of a form_key mismatch.

**Comment by sevos1984** [comment] 2016-04-14 16:12
Not reproducible. Have you tried clearing cookies, magento var/ and pub/static/ folders?

**Comment by slavvka** [comment] 2016-05-18 10:21
@JasonMortonNZ, is this issue still actual?

**Comment by slavvka** [comment] 2016-06-08 08:56
Closing since the author didn't respond

**Closed as completed** 2016-06-20 21:47 UTC

**Comment by salmanazeez786** [comment] 2016-06-22 06:07
Im facing this issue
In \Magento\Customer\Controller\Account\LoginPost.php  on line 70
if I use   **if ($this->session->isLoggedIn() ){**    instead of **if ($this->session->isLoggedIn() || !$this->formKeyValidator->validate($this->getRequest())) {**   then login works, which means that formkey validation is failing.....
