### ISSUE TITLE
Incorrect order status label in sales update emails sent from the admin for non-default store views

### ISSUE THREAD

**Issue by aadmathijssen** [magento/magento2#29263] opened 2020-07-24 14:09 UTC
After sending a sales update email from the admin for an order using a non-default store view, the resulting email contains the order status label for the default store view instead of the order status label for the store view in which the order is placed.

### Preconditions (*)

1. A Magento 2.4-develop installation with sample data.

### Steps to reproduce (*)
1. In the admin:
    * Go to “Stores > All Stores”, click on “Create Store View”, fill in the required values, set the status to “Enabled” and click on the "Save Store View” button.
    * Go to “Stores > Order Status”, click on the “Pending” status, enter the following data under “Store View Specific Labels”, and click on the “Save Status” button.
        * Default Store View: “Pending (default)”
        * New Store View: “Pending (secondary)”
![Screenshot from 2020-07-29 12-26-46](https://user-images.githubusercontent.com/51679138/88782907-d1009f80-d196-11ea-8d1d-6fd500f33c5f.png)

2. In the frontend:
    * Select the new store view in the store view switcher.
    * Add a product to the cart.
    * Complete the checkout using the “Check / Money order” payment method.
3. In the admin:
    * Go to “Sales > Orders”, and click on the newly created order.
    * On this order view page, enter a comment, click on the “Notify Customer by Email” checkbox and click on the "Submit Comment” button.

### Expected result (*)

1. An order update email is sent containing “Pending (secondary)” as the order status.

### Actual result (*)

1. An order update email is sent containing “Pending (default)” as the order status.

Screenshot of the resulting email:

![sales_order_update_email_with_incorrect_order_status_label](https://user-images.githubusercontent.com/3796971/88399537-52d38000-cdc7-11ea-9f5d-cf7caba1a3d1.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by aadmathijssen** [comment] 2020-07-24 14:11
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-07-24 14:11
Hi @aadmathijssen. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-07-24 14:13
Hi @aadmathijssen, here is your [Magento instance](https://i-29263-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29263-2-4-develop.instances.magento-community.engineering/admin_77c7](https://i-29263-2-4-develop.instances.magento-community.engineering/admin_77c7)
Login: `1856ed77` Password: `c43a74371a5a`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2020-07-29 09:28
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36262` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by salelsol** [comment] 2020-09-16 15:54
-    Years waiting for a solution to this serious problem.  I need to follow the development of the solution if it is finally found.

**Comment by WilliejanB** [comment] 2020-10-09 13:09
Is there a temporary fix available for this issue? I need it urgently. If so, where can I find this? I'm not a programmer, so please keep it simple...... Thanks a lot!

**Comment by Axel29** [comment] 2020-12-10 18:18
Up, is there a fix for that?

**Comment by Axel29** [comment] 2020-12-10 18:43
I have tested a fix that I can suggest that would impact only one class but I'm not sure that it wouldn't have side effects on other parts of the website.

The idea would be to emulate the order's store using `\Magento\Store\Model\App\Emulation::startEnvironmentEmulation` and `\Magento\Store\Model\App\Emulation::stopEnvironmentEmulation` inside `\Magento\Sales\Model\Order::getFrontendStatusLabel` like that:

```php
    /**
     * Retrieve frontend label of order status
     *
     * @return string
     * @since 102.0.1
     */
    public function getFrontendStatusLabel()
    {
        $this->appEmulation->startEnvironmentEmulation($this->getStoreId(), Area::AREA_FRONTEND);

        $frontendLabel = $this->getConfig()->getStatusFrontendLabel($this->getStatus());

        $this->appEmulation->stopEnvironmentEmulation();

        return $frontendLabel;
    }
```

It seems to work locally but I haven't tested anything else than adding a comment to the order in the admin.

**Comment by Axel29** [comment] 2020-12-11 10:39
Here is a quickfix until the patch is made in the official release that you can apply in a custom module (think about replacing the "Vendor\Module" parts):

1. `File etc/adminhtml/di.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\Sales\Model\Order">
        <plugin sortOrder="1" name="bmSalesOrder" type="Vendor\Module\Plugin\Model\OrderPlugin" />
    </type>
</config>

```

2. File `Plugin/Model/OrderPlugin.php`

```php
<?php
namespace Vendor\Module\Plugin\Model;

use Magento\Framework\App\Area;
use Magento\Sales\Model\Order;
use Magento\Store\Model\App\Emulation as AppEmulation;

class OrderPlugin
{
    /**
     * @var \Magento\Store\Model\App\Emulation
     */
    private $appEmulation;

    /**
     * OrderPlugin constructor.
     *
     * @param \Magento\Store\Model\App\Emulation $appEmulation
     */
    public function __construct(AppEmulation $appEmulation)
    {
        $this->appEmulation = $appEmulation;
    }

    /**
     * Fix transactional emails retrieving order status without the translation.
     * See https://github.com/magento/magento2/issues/29263
     *
     * @param \Magento\Sales\Model\Order $subject
     * @param string                     $result
     *
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     *
     * @return string
     * @since 102.0.1
     */
    public function afterGetFrontendStatusLabel(Order $subject, $result)
    {
        $this->appEmulation->startEnvironmentEmulation($subject->getStoreId(), Area::AREA_FRONTEND);

        $frontendLabel = $subject->getConfig()->getStatusFrontendLabel($subject->getStatus());

        $this->appEmulation->stopEnvironmentEmulation();

        return $frontendLabel;
    }
}

```

i'll try to make a pull request as soon as possible but even if it is accepted, it wouldn't be available until at least one of these versions I guess 2.4.2, 2.4.1-p1, 2.3.6-p1, so this is a quickfix until then.

**Comment by WilliejanB** [comment] 2020-12-11 14:17
> Here is a quickfix until the patch is made in the official release that you can apply in a custom module (think about replacing the "Vendor\Module" parts):
>  
> i'll try to make a pull request as soon as possible but even if it is accepted, it wouldn't be available until at least one of these versions I guess 2.4.2, 2.4.1-p1, 2.3.6-p1, so this is a quickfix until then.

Thank you for your "quick-fix" @Axel29 I will ask our developer to add it, because I could not find the exact location (folder) where to put the replacements.

**Comment by Axel29** [comment] 2020-12-14 08:39
> > Here is a quickfix until the patch is made in the official release that you can apply in a custom module (think about replacing the "Vendor\Module" parts):
> > i'll try to make a pull request as soon as possible but even if it is accepted, it wouldn't be available until at least one of these versions I guess 2.4.2, 2.4.1-p1, 2.3.6-p1, so this is a quickfix until then.
> 
> Thank you for your "quick-fix" @Axel29 I will ask our developer to add it, because I could not find the exact location (folder) where to put the replacements.

No problem, you can add it in `app/code/[Vendor]/[Module]/` where `[Vendor]/[Module]` is one of your modules.

**Closed as completed** 2021-05-25 05:59 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Confirmed, Issue: Format is valid, Component: Store, Component: Email, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P2, Severity: S3, Triage: Done, Progress: done, Reported on 2.4.0

**Comment by WilliejanB** [comment] 2022-07-14 16:32
Hi @magento-engcom-team @aadmathijssen @edenduong,

We currently use Magento ver. 2.4.3, which still has the problem. Please confirm if it is solved in Magento ver. 2.4.4 release?

Best regards,
Williejan

**Comment by sukeshini-kot** [comment] 2022-08-05 09:42
Where can I find the commit for this fix?
