### ISSUE TITLE
Promotion Issue with Future date

### ISSUE THREAD

**Issue by ghost** [magento/magento2#36817] opened 2023-02-08 06:48 UTC
### Summary

Sales rules can be applied in the frontend when it is created for future events

### Examples

Process

Create a sales rule with the future date, but customers can purchase using the coupon code early to the date.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-02-08 11:52
Hi @rameshgeo,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

Steps to Reproduce :

1.Created a cart price rule with coupon code for Future Dates.
2.Apply the coupon to the product.


![Error-Promotions-Marketing-Magento-Admin](https://user-images.githubusercontent.com/51680745/217522021-ea578b9b-3702-4cf2-9294-21e27f83d72d.png)


<img width="1430" alt="Screenshot 2023-02-08 at 1 02 54 PM" src="https://user-images.githubusercontent.com/51680745/217522060-1dc483f5-c267-4150-9314-f05218ab446f.png">



We are not able to apply the coupon code for a product.Kindly let us know if we missed anything.

Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-02-20 06:07
Hi @rameshgeo,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-02-20 06:07 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.x
