### ISSUE TITLE
Magento 2.1.4 - Asking Why Email Logo Never been fixed on all Magento releases

### ISSUE THREAD

**Issue by jurpro** [magento/magento2#8489] opened 2017-02-09 13:28 UTC
Having problem with uploading Logo for email. After Magento 2.1.4 released, it doesn't fix the logo email.

### Preconditions
1.  Magento 2.1.4

### Steps to reproduce
1. Set up email logo on Content => Design => Configuration
2. Edit on Global
3. Choosing Transactional Emails
4. Upload Logo image

### Expected result
1. It shows on all email sending from the system to New Customer, New transaction, and all email activities from Magento system

### Actual result
1. It always Luma Logo showing. Not replace with our own logo.

Ask: Why Magento never fix to the latest release ? Don't answer it fixed on bla bla bla, because it never implemented to the latest released.

Thanks

**Comment by andidhouse** [comment] 2017-02-09 17:00
Look at 99% of the bugs here and you know the answer ;-) - With every release about 10-20 Bugs are fixed maximum and even more bugs are introduced with each release... so if you look at over 1.000 bugs reported here you can count 1+1 and you have the answer why it is not fixed ;-)

**Comment by che2on** [comment] 2017-02-09 17:06
@andidhouse You mean to say magento2 is intentionally delaying releases and have no clue about what they are doing? Pretty strange.

Actually this issue even i faced , the logo gets dumped into a diff folder, we can correct it ourself by creating directories and uploading the logo image on ftp. How can we push the code? May be it will help magento2 team if everyone contributes code?

**Comment by andidhouse** [comment] 2017-02-09 17:14
@che2on - no i do not say at all they are delaying releases at all and that they have no clue. I just say that 1) the quality of the code they build is full of bugs and 2) they introduced lots of new stuff which is implemented not right and 3) and most important magento does not stop the development and focuses on these bugs and bad implementations but continues like all is ok.

**Comment by korostii** [comment] 2017-02-09 17:34
It takes some time for a bug to get fixed and for the bugfix to get merged, backported and released. That is, if the bugs ever gets noticed, reported(here we are), reproduced(this is important: for a single bugreport it might be hard to tell if it's a valid magento bug or a miscofiguration or a bug in 3rd-party module etc.) and acknowledged - if any of these fail, then none of the developers in Magento Inc. will ever get assigned to it nor fix it. 

Ironically, one of the reasons bugreports get ignored or answered with delay is because there are so many of them. Thus I would encourage you to find existing bugreports of this bug (if any, but if it's reproducible - there's a high possibility of those existing), upvote them, link duplicates, etc. That way the chances of this issue getting noticed might rise up. 

One workaround though seems to be the following: if you're a developer yourself, you could hack through the first part by tracing the bug and producing a pull request with he fix. Back in 2016, those were ignored, too, but finally it started moving a coupl weeks ago: https://github.com/magento/magento2/projects/3

I would like to say that it speed up thing a lot, but, basically, even existing bugfixes may travel for months through branches and regression tests until the new version gets released. Sad, but still true.

**Comment by korostii** [comment] 2017-02-09 18:03
Possible duplicate of #7949 and\or #6275
I'd suggest that you take a look a those, there seem to be a fix and a couple of workarounds present, maybe one of those will help solving your particular issue.

**Comment by jurpro** [comment] 2017-02-10 13:04
If this is solved on so many thread discusses, why Magento team didn't implemented to the latest release? It means, according to Magento team, all the solved by many members, still did not able to merge to Magento system.

Please, Magento team, next release, this issue is fixed and not happen again. ==Sorry my english is bad==

**Comment by developer-lindner** [comment] 2017-02-11 13:36
@jurpro Can't confirm this bug. Had no issues when updating the email logo. Worked as expected... so you may check your setup first before blaming around.

**Comment by jurpro** [comment] 2017-02-12 13:15
@developer-lindner No. I only update from 2.1.3 to 2.1.4 as a common user Magento, not editing any files or add any folders, but still got this issue. I'm uploading my logo and testing 2-3 times for add customers and buy any product. And there is still Luma logo send to customer email. 

Why, I'm not editing any files? Because if Magento upgrade to latest version, my edited files will change by new files. And I will forget how to fix again, maybe. Please, don't blame and angry any users with their problem, but you have to fix this issue as soon as possible and asking to us, is it fix or not after release new version.

Thanks

**Comment by wert2all** [comment] 2017-02-20 13:33
Thanks for the response. Closed as duplicate https://github.com/magento/magento2/issues/7949

**Closed as completed by wert2all** 2017-02-20 13:33 UTC
Labels: Issue: Ready for Work

**Comment by magento-team** [comment] 2017-08-01 14:58
Internal ticket to track issue progress: MAGETWO-69062

**Comment by andidhouse** [comment] 2017-08-01 15:02
@magento-team is it now a "track issue progress" ticket to the ticket of the bug? 

I think it would easier just to fix a bug like this then to create a "internal tickte" and then a "Internal ticket to track issue".

It feels like you guys have hundreds or even a view thousand internal tickets open here which never get touched internally or fixed 👎

**Comment by hostep** [comment] 2017-08-01 18:44
@andidhouse: it is already fixed on the [2.1.8-preview branch](https://github.com/magento/magento2/commit/0dfaf62664661323c753026af92b6d5c6c6fb73a), so the fix should be delivered in Magento 2.1.8 ;)
