### ISSUE TITLE
Cannot add bundled products to cart if bundle has a special price

### ISSUE THREAD

**Issue by justinharris1986** [magento/magento2#22095] opened 2019-04-01 17:43 UTC
### Preconditions
1. Magento 2.2.8
2. PHP 7.1.27 (In our case - may or may not be a factor - we are running in php-fpm)
3. MariaDB 10.3.13-1.el7.centos (In our case - may or may not be a factor)
4. Bundle product *with a special price attached*

### Steps to reproduce
1. Create 2 simple products
2. Create a bundle with the simple products, and add a Special Price from the advanced pricing page
3. Go to the front end, and add to cart

### Expected result
1. Adds to cart successfully

### Actual result (*)
1. PHP eats up to max_memory limit, and then dies, generating a 500 to the user
2. Navigate to home page, and then directly to the cart - fails with the same as 1, above.
3. note the minicart does not load.
4. Remove the special price from the back end
5. Cart now loads successfully

This issue did NOT manifest itself in 2.2.7.

**Comment by justinharris1986** [comment] 2019-04-01 17:43
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-04-01 17:43
Hi @justinharris1986. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-01 17:44
Hi @justinharris1986, here is your [Magento instance](https://i-22095-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22095-2-2-develop.instances.magento-community.engineering/admin](https://i-22095-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by justinharris1986** [comment] 2019-04-01 17:59
@magento-engcom-team  - Yes I was able to reproduce this in 2.2. Not sure if it matters or not, but i disabled "Dynamic Price" and manually set a price in the bundle.
![image](https://user-images.githubusercontent.com/7268384/55348482-4a925b80-5485-11e9-8941-56cff289c6c6.png)

2nd - with our theme, we get a 500, however, with the default Luma, it just sits there on "adding". I am presuming it will eventually time out.  This was the add request after letting it sit for 3 minutes after clicking add to cart:
![image](https://user-images.githubusercontent.com/7268384/55348686-c68ca380-5485-11e9-8211-501c050d461d.png)


More screenshots to hopefully help:
Simple product 1 configs (nothing touched under advanced pricing here):
![image](https://user-images.githubusercontent.com/7268384/55348807-13707a00-5486-11e9-9887-13015066e705.png)

Simple product 2 configs (nothing touched under advanced pricing here):
![image](https://user-images.githubusercontent.com/7268384/55348843-28e5a400-5486-11e9-884a-570d09f405b2.png)


Bundle config:
![image](https://user-images.githubusercontent.com/7268384/55348905-4a469000-5486-11e9-963e-dc7dfc6c834b.png)

![image](https://user-images.githubusercontent.com/7268384/55348916-50d50780-5486-11e9-86d0-694d9d6b0e7d.png)

and the advanced config for the bundle, this is what breaks:
![image](https://user-images.githubusercontent.com/7268384/55348935-5fbbba00-5486-11e9-896e-7dbac0bb6cc4.png)

if you remove the 5% from there, and save the product, you can then add the product to the cart

**Comment by Jitheesh** [comment] 2019-04-02 14:17
Issue replicated on 2.3 branch but looks like it is resolved on 2.3-develop branch.

This issue is because of a infinite loop while calculating special price of a bundled product. 

Magento is looking for product Tier price and Special price for finding the final price of a product. 
Check following functions to identify this infinite loop.

https://github.com/magento/magento2/blob/fd2771b2cf97a8acbb9f3e1b02effe6a62b273c2/app/code/Magento/Bundle/Model/Product/Price.php#L518-L526

https://github.com/magento/magento2/blob/fd2771b2cf97a8acbb9f3e1b02effe6a62b273c2/app/code/Magento/Catalog/Model/Product/Attribute/Backend/GroupPrice/AbstractGroupPrice.php#L305-L314

https://github.com/magento/magento2/blob/fd2771b2cf97a8acbb9f3e1b02effe6a62b273c2/app/code/Magento/Catalog/Model/Product/Attribute/Backend/GroupPrice/AbstractGroupPrice.php#L339-L352

https://github.com/magento/magento2/blob/0c786907ffe03d0e2990612eec16ee58b00379c5/app/code/Magento/Catalog/Model/Product/Attribute/Backend/Tierprice.php#L160-L186

**Comment by AaronONeill** [comment] 2019-04-11 10:54
We're experiencing the same issue since upgrading a site from 2.2.7 to 2.2.8. We have also found that removing the Special Price (% value) from the bundled product and saving allows us to successfully navigate to the cart/checkout page. When this field has a value, the cart/checkout process is broken entirely.

I have done some digging based on the files @Jitheesh provided. What we can see is that the following behaviour:

_vendor/magento/module-bundle/Model/Product/Price.php_

We can see that its getting the Bundle options and getting the selection final total price which leads to calling the **_applyTierPrice($product, $qty, $finalPrice)** function in the same file noted above.

Locally, where I can recreate the issue I set a breakpoint on the "**$tierPrice = $product->getTierPrice($qty);**" line within this function and noted the results.

We can see that when the cart loads, it calls this **_applyTierPrice()** function which then calls the "**getTierPrice()**" function, in this instance its located in:

_vendor/magento/module-catalog/Model/Product.php_

This then returns the getTierPrice function based on whats returned from **getPriceModel(**). This then runs the **getTierPrice()** function in:

_vendor/magento/module-bundle/Model/Product/Price.php_

Following the trace along, it triggers the "**$attribute->getBackend()->afterLoad($product);**" call where $prices are null. The **afterLoad()** function in:

_vendor/magento/module-catalog/Model/Product/Attribute/Backend/GroupPrice/AbstractGroupPrice.php_

Does some further processing to return the final price which ends up calling the **__applyTierPrice()** function in 

_vendor/magento/module-bundle/Model/Product/Price.php_

Which is where the process started. As this is where the process started and it is calling the exact same "**__applyTierPrice()**" function, it is going through the exact same files calling the exact same functions and inevitably ending up in an infinite loop. 

See screenshot below for more clarity on the above.

![download](https://user-images.githubusercontent.com/5518296/55951856-2e927500-5c50-11e9-88ab-6018b8128af8.png)

**Comment by genyuk** [comment] 2019-04-11 20:15
Same issue on Magento 2.2.8 CE, MariaDB, Nginx
After trying to add a bundle product to the cart - site will crash after a few minutes on "waiting ...." and the issue will remain for any other (even simple) products. Restarting server and clearing browser cache on the client does help until the next try with bundle product .

Removing Special price does not help in our case. 

Any tip on how to patch it will be appreciated.

**Comment by comaxxdevelopment** [comment] 2019-04-12 06:36
For our projects we fixed this bug as followed:

Make an override for vendor/magento/module-catalog/Model/Product/Attribute/Backend/Tierprice.php line 171. Change it from:

`if ($specialPrice && ($object->getPrice() > $object->getFinalPrice())) {`
to
`if ($specialPrice && ($object->getPrice() > $specialPrice)) {`

Tested using bundles containing customer group prices and special price and correct price is used. 

If you want to be even more specific you could also change it to only be different for bundle products. To do so use :

`$isBundleProduct = $object->getTypeId() === \Magento\Catalog\Model\Product\Type::TYPE_BUNDLE;
        if (
            ( ! $isBundleProduct && $specialPrice && ($object->getPrice() > $object->getFinalPrice()) ) ||
            ( $isBundleProduct && $specialPrice && ($object->getPrice() > $specialPrice) )
        ) {`

Not sure if this is the intended solution but this does work for us.

**Comment by gulshanchitransh** [comment] 2019-05-04 04:16
I am working on this at #dmcdindia1

**Comment by mallikaverma** [comment] 2019-05-11 06:31
@magento-engcom-team  give me 2.3-develop instance

**Comment by mallikaverma** [comment] 2019-05-12 17:52
#imagine2019

**Comment by ryandiamond23** [comment] 2019-07-30 16:00
@magento-engcom-team Is there a patch for this for 2.2.9? We are seeing this issue as well on Magento Cloud.

**Comment by engcom-Charlie** [comment] 2019-10-18 15:39
Hello @justinharris1986 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.

We are closing this issue due to branch `2.2-develop` was closed and
> Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.

 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-10-18 15:39 UTC
Labels: Issue: Format is valid, Component: Bundle, Event: dmcdindia1, Event: imagine2019
