### ISSUE TITLE
Adminhtml - Product with custom option date [required] when creating an order via admin

### ISSUE THREAD

**Issue by kestraly** [magento/magento2#36423] opened 2022-11-05 11:57 UTC
### Preconditions and environment

- Magento version 2.4.4-p2
- PHP 7.4

### Steps to reproduce

**- Set Date as drop down in Stores > Configuration > Catalog > [Date & Time Custom Options]**
Date Fields Order - Day / Month / Year
Save

**- Catalog > Products > Select or add a new product**
Add a date custom option to a product with date.phtml as **required**

**- Sales > Order**
Create a new order, with new customer
Select Add Products
Select the product with the required custom option date

### Expected result

Be able to select date and press continue and process the order.

### Actual result

Console logs javascript syntax error closing of }

./vendor/magento/module-catalog/view/adminhtml/templates/catalog/product/composite/fieldset/options/type/date.phtml

Checking in ./var/view_preprocessed/pub/static/vendor/magento/module-catalog/view/adminhtml/templates/catalog/product/composite/fieldset/options/type/date.phtml- line 63 is escaped with //

jQuery.validator.addMethod('validate-datetime-

Becomes

// jQuery.validator.addMethod('validate-datetime-

Removing line 59 `//<![CDATA[` and line 91` //]]>` in date.phtml fixes the syntax error

The product cannot be added to the order and a work around must be employed

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by kestraly** [comment] 2022-11-05 11:58
@magento give me 2.4-develop instance

**Comment by kestraly** [comment] 2022-11-05 12:11
Error is reproduced, but allowed to add to cart with single option

**Uncaught SyntaxError: Unexpected token '}'
    at legacy-build.min.js:1:9878
    at Array.map (<anonymous>)
    at Array.collect (legacy-build.min.js:1:19426)
    at String.evalScripts (legacy-build.min.js:1:9845)
    at legacy-build.min.js:1:6086**

```
require([
                "jquery",
                "mage/backend/validation"
            ], function(jQuery){

                //<![CDATA[                jQuery.validator.addMethod('validate-datetime-1', function(v) {
                    var dateTimeParts = jQuery('.datetime-picker[id^="options_1"]');
                    for (var i=0; i < dateTimeParts.length; i++) {
                        if (dateTimeParts[i].value == "") return false;
                    }
                    return true;
                }, 'This\u0020is\u0020a\u0020required\u0020option.');                //]]>

            });
```

**Comment by engcom-Dash** [comment] 2022-11-07 06:59
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-11-07 11:22
@magento give me 2.4-develop instance

**Comment by kestraly** [comment] 2022-11-07 12:38
@engcom-Dash
Whilst selecting date, if you check your console in the browser, you’ll see the JS error. It basically stops the validation process, which in turn breaks adding further custom options. 

The bigger issue is how pre_processed files is handled.

I can add imagery if required

**Comment by kestraly** [comment] 2022-11-07 20:28
Image of the error that appears in console.
<img src="https://iili.io/plJ8Q4.md.jpg" alt="plJ8Q4.md.jpg" border="0">

It definitely breaks custom options. Please review your console @engcom-Dash whilst adding the custom option to basket. Then review the line to see that addMethod is becoming ommited ` //<![CDATA[                jQuery.validator.addMethod('validate-datetime-1', function(v) {`

**Comment by engcom-Dash** [comment] 2022-11-09 07:02
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-11-09 09:10
Hi @kestraly ,
Thanks For your Information!!!
We are Worked as per your last comment...We are also getting same JS error in console.So we are confirming the issue.

Precondition:
Magento Version 2.4-develop
PHP 8.1
Magento installed with custom date module.
Steps To reproduce:
1.Set Date as drop down in Stores > Configuration > Catalog > [Date & Time Custom Options]
2.set the Date Fields Order - Day / Month / Year
3.save and clear cache
4.go to Catalog > Products > Select or add a new product
5.Add a date custom option to a product with date.phtml as required
6.go to Sales > Order
7.Create a new order, with new customer
8.Select add products
9.Select the product with the required custom option date
we are gettingJjs error in console as per-actual result.
Screenshots:

<img width="1512" alt="Screenshot 2022-11-09 at 2 39 54 PM" src="https://user-images.githubusercontent.com/60198592/200788383-5ea9c037-7cbd-46ca-9e65-8cd25339bc3c.png">


Let us know if we missing anything !!!

Thanks!!!

**Comment by JeromeBeckett** [comment] 2024-01-24 12:10
We just encountered this. Still an issue in **2.4.6-p3** and **2.4.7-beta2**.

**Comment by andrewbess** [comment] 2024-01-31 11:27
Hello @RetroProgrammist 
I think it would be better to wrap `CDATA` component using other commenting style
For example:
`/*<![CDATA[*/`

**Comment by andrewbess** [comment] 2024-01-31 11:27
@magento I am working on it

**Comment by engcom-Bravo** [comment] 2024-12-24 04:59
Hi @kestraly,

Thanks for reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.


<img width="1439" alt="Screenshot 2024-12-24 at 10 27 42 am" src="https://github.com/user-attachments/assets/8d9b3dd4-3cf0-4512-90ec-3c6a716dde5f" />


Be able to select date and press continue and process the order.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-12-24 04:59 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Progress: done, Reported on 2.4.x, Area: Admin UI
