### ISSUE TITLE
Only problems with magento 2

### ISSUE THREAD

**Issue by baseplayer** [magento/magento2#36605] opened 2022-12-14 11:44 UTC
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug
paypal orders sometimes do not come in?
many errors we see are old bugs and still not solved?
I can not say what it was but i cost me 6000 euro too fix all
If we checked the bugs they where already there in magento 2.3.2

Al very frustrating and i am not the only one who has these problems

I think that something goes wrong in communicating the bugs so they stay in new versions?

In magento 1.9 this was not so bad as it is now.

It is so bad i want too quit magento even.

### Steps to reproduce

We can not reproduce the paypal problem it only happens 2 times a month and it does not happen always

also we see many checkout errors in red. the customers send it too us

### Expected result

Please make sure old bugs are solved and do not return, very frustrating

### Actual result

Because off the issue magento 2 is not a reliable partner and costs money too solve problems and even money does not get in.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-12-15 07:46
Hi @baseplayer ,
Thank you for reporting and collaboration. We are unable to reproduce the issue on latest Magento instance 2.4.5 and 2.4-develop instance with provided information. PayPal payments are working fine from both front end and backend admin pages for logged in and guest users. Magento 2.3.2 is quite an old version and reached end of support in September 2022. We recommend you to kindly upgrade your Magento instance to latest version compatible as per [System requirements](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html) and elaborate steps to reproduce / configuration details / any 3rd party modules enabled if any causing the issue if you are still facing any issues.
Thank you.

**Comment by baseplayer** [comment] 2022-12-15 08:58
Hi,

The magento version is 2.3.7

And i googled more people have issues

This my dev gave me for the one that had a problem.

[2022-11-20 17:37:42] main.CRITICAL: Saving order 362001265 failed:
Verletzung einer "Unique" Einschränkung gefunden [] []

[2022-11-20 17:37:43] main.CRITICAL: Exception message: Verletzung einer
"Unique" Einschränkung gefunden

But the message i wanted too give that in the past we found so many bugs
and they seemed old and were still there? Maybe you could discuss this. I
am sure i am not the only one who experienced this

Kind regards

Bas

Op do 15 dec. 2022 om 08:46 schreef Girija Bhavani Kudupudi <
***@***.***>

**Comment by engcom-November** [comment] 2022-12-20 14:35
Hi @baseplayer ,
Thank you for the response. If the issue occurred due to migration, please check sequence_order_0 and sequence_order_1 tables in DB. sequence_value column should be auto_increment and set primary key. If the issue is still not resolved, try adding some entries to database: add meta_id to 'sales_sequence_meta' table and add those ‘meta id’ to ‘profile id’ into existing ‘sales_sequence_profile’ table and additionally, we have to add more entry in ‘prefix’ column. Reindex and clear cache.
This issue is not reproducible on latest Magento versions and Magento 2.3.x all versions has reached end of support. Kindly upgrade your Magento instance to latest version / check in 2.4-develop instance if you are still facing any issues.
Thank you.

**Comment by engcom-November** [comment] 2023-01-06 06:37
Hi @baseplayer ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2023-01-06 06:37 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.x
