### ISSUE TITLE
Translation in tier_price.phtml not working

### ISSUE THREAD

**Issue by DanieliMi** [magento/magento2#19085] opened 2018-11-06 15:51 UTC
### Summary
It seems to me that the translations for [tier_prices.phtml](https://github.com/magento/magento2/blob/53a896645c8a1a55fe7842ce621a1f79176b6d38/app/code/Magento/ConfigurableProduct/view/base/templates/product/price/tier_price.phtml#L18) are not being picked up by the javascript translation. They are not translatable with an dictionary and are not present in js-translation.json.

### Preconditions (*)

1. Magento 2.2.6

### Steps to reproduce (*)

I am not quite sure how to desribe properly the steps to reproduce. I guess it's:
1. Clearing all cashes
2. Deploying static content/translations
3. Check pub/static/frontend/Vendor/Theme/js-translation.json

### Expected result (*)

I expect to see the phrases "Buy %1 for %2 each and" and "save"

### Actual result (*)

The phrases are not there.

### Possible workaround
A possible workaround for this issue is to use `<?php echo __() ?>` instead but i don't think this is a proper solution for this issue.

**Comment by magento-engcom-team** [comment] 2018-11-06 15:51
Hi @DanieliMi. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@DanieliMi do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-11-07 07:28
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2018-11-07 08:51
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96166`, `MAGETWO-96167` were created

**Comment by magento-engcom-team** [comment] 2018-11-10 08:07
Hi @agorbulin. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2018-12-21 23:40
Hi @DanieliMi. Thank you for your report. 
The issue has been fixed in magento/magento2#19094 by @agorbulin in 2.3-develop branch
Related commit(s):
 - [425514bcf49e3adb2d0516d70d27dedf11b65345](https://github.com/magento/magento2/commit/425514bcf49e3adb2d0516d70d27dedf11b65345)
 - [345393d13c42fdcaeb4897fbbb6e3dfae23209ce](https://github.com/magento/magento2/commit/345393d13c42fdcaeb4897fbbb6e3dfae23209ce)
 - [63bbc39ddd5cc0c59186746fce8b97b358beaee9](https://github.com/magento/magento2/commit/63bbc39ddd5cc0c59186746fce8b97b358beaee9)
 - [1a006b30f46e79df479c60010efb1640b64dca4f](https://github.com/magento/magento2/commit/1a006b30f46e79df479c60010efb1640b64dca4f)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2018-12-21 23:40 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: ConfigurableProduct

**Comment by magento-engcom-team** [comment] 2019-01-23 23:00
Hi @DanieliMi. Thank you for your report. 
The issue has been fixed in magento/magento2#19377 by @agorbulin in 2.2-develop branch
Related commit(s):
 - [f895d4aabd4292926a9a7428421febd9ab512232](https://github.com/magento/magento2/commit/f895d4aabd4292926a9a7428421febd9ab512232)
 - [74396e1a73ea9b8bfa5c1fecebc2d663c875c28c](https://github.com/magento/magento2/commit/74396e1a73ea9b8bfa5c1fecebc2d663c875c28c)
 - [08fe8171281f6dbcfbf1a9164b524724d00149aa](https://github.com/magento/magento2/commit/08fe8171281f6dbcfbf1a9164b524724d00149aa)
 - [fba4bc81a623533b7f913571ec29dfdd29060a77](https://github.com/magento/magento2/commit/fba4bc81a623533b7f913571ec29dfdd29060a77)

The fix will be available with the upcoming 2.2.8 release.
