### ISSUE TITLE
Pagination controls are missing on wishlist page

### ISSUE THREAD

**Issue by webkul-shruti** [magento/magento2#19292] opened 2018-11-21 10:14 UTC
### Preconditions (*)

1. Magento Version: 2.2.6
2. Community Edition (CE)

### Steps to reproduce (*)

1. Register or login to a customer account.
2. Navigate to any category page.
3. Add more than 10 products in wishlist (I tried with adding 40 products into wishlist)

### Expected result (*)

1. 
![wishlist13](https://user-images.githubusercontent.com/39335353/48833729-0938c380-eda2-11e8-8488-c6730d3ed532.png)
2. Pagination should be there.

### Actual result (*)

1. 
![wishlist12](https://user-images.githubusercontent.com/39335353/48833484-75ff8e00-eda1-11e8-8444-86bf113f0ad3.png)
2. Not showing any pagination on the wishlist page.

**Comment by magento-engcom-team** [comment] 2018-11-21 10:14
Hi @shrutibaranwal890. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@shrutibaranwal890 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-11-21 10:15
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2018-11-21 10:16
Hi @webkul-ratnesh. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2018-11-21 10:18
@webkul-ratnesh Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96546` were created

**Comment by magento-engcom-team** [comment] 2019-01-19 06:55
Hi @webkul-shruti. Thank you for your report. 
The issue has been fixed in magento/magento2#19305 by @webkul-ratnesh in 2.3-develop branch
Related commit(s):
 - [23e6250046ad8d54d732643ad4c7c881818f44c9](https://github.com/magento/magento2/commit/23e6250046ad8d54d732643ad4c7c881818f44c9)
 - [3ebcc33bb57a15d0f7e6e5382fad4e28abf302fb](https://github.com/magento/magento2/commit/3ebcc33bb57a15d0f7e6e5382fad4e28abf302fb)
 - [edc84041bada47a73e1f35bbc879442c4d26e65e](https://github.com/magento/magento2/commit/edc84041bada47a73e1f35bbc879442c4d26e65e)
 - [4ddc22bb35d45fcb473a995089c6c132800e1356](https://github.com/magento/magento2/commit/4ddc22bb35d45fcb473a995089c6c132800e1356)
 - [60a0dd4a753eab9344bbf1e3598ab5d1077a2ffe](https://github.com/magento/magento2/commit/60a0dd4a753eab9344bbf1e3598ab5d1077a2ffe)
 - [ce8765b118840d7894126f1e5c1bac519a79e80a](https://github.com/magento/magento2/commit/ce8765b118840d7894126f1e5c1bac519a79e80a)
 - [4fb3c8dbc5a04de266f7bf65d4e45ff4a9baf48c](https://github.com/magento/magento2/commit/4fb3c8dbc5a04de266f7bf65d4e45ff4a9baf48c)
 - [71ee75b539fa753bc866b546f6d89d0b36d972ba](https://github.com/magento/magento2/commit/71ee75b539fa753bc866b546f6d89d0b36d972ba)
 - [b153c06bd95b30121d0cd61a20c147dc3ef43692](https://github.com/magento/magento2/commit/b153c06bd95b30121d0cd61a20c147dc3ef43692)
 - [ff416b94ac2e7ec348d4be963f0234568a885f11](https://github.com/magento/magento2/commit/ff416b94ac2e7ec348d4be963f0234568a885f11)
 - [00a21317486a013ba69847ff320d26afefea39e1](https://github.com/magento/magento2/commit/00a21317486a013ba69847ff320d26afefea39e1)
 - [892304654389ccd7bc26366497a11247279abadc](https://github.com/magento/magento2/commit/892304654389ccd7bc26366497a11247279abadc)
 - [7c5b9a55601184400112e7d51b06eaa95781df1d](https://github.com/magento/magento2/commit/7c5b9a55601184400112e7d51b06eaa95781df1d)
 - [dc407d98209fb378ea6cf4e44625b551e0a44055](https://github.com/magento/magento2/commit/dc407d98209fb378ea6cf4e44625b551e0a44055)
 - [2b3deabce8eea7d2832ebe83c37534295fb16260](https://github.com/magento/magento2/commit/2b3deabce8eea7d2832ebe83c37534295fb16260)
 - [4bfacbbbd8124bcbeb6e5f86a2c137e23005b38c](https://github.com/magento/magento2/commit/4bfacbbbd8124bcbeb6e5f86a2c137e23005b38c)
 - [c41ec765e1092cd8302eea39c97c634df90c850c](https://github.com/magento/magento2/commit/c41ec765e1092cd8302eea39c97c634df90c850c)
 - [e06804215e2b2ce55c8678815ff902db3bbfb7cc](https://github.com/magento/magento2/commit/e06804215e2b2ce55c8678815ff902db3bbfb7cc)
 - [8b06ed6f1bc5b1c72294b8c05518302915f3bb4f](https://github.com/magento/magento2/commit/8b06ed6f1bc5b1c72294b8c05518302915f3bb4f)
 - [5e2bbb669eddbe6228e07a5caaf509c59880b0f2](https://github.com/magento/magento2/commit/5e2bbb669eddbe6228e07a5caaf509c59880b0f2)
 - [bd89f7b38ab05aa09adfdaa84c61eb252c5adbde](https://github.com/magento/magento2/commit/bd89f7b38ab05aa09adfdaa84c61eb252c5adbde)
 - [35c033e764540a4950b16e5e0c1845fde8c861f6](https://github.com/magento/magento2/commit/35c033e764540a4950b16e5e0c1845fde8c861f6)
 - [4fbcf8c8a5f307b52d8bf4a17ca8d3bbb48469eb](https://github.com/magento/magento2/commit/4fbcf8c8a5f307b52d8bf4a17ca8d3bbb48469eb)
 - [249aa0715b47c6938ffb3437b753c1957a08536b](https://github.com/magento/magento2/commit/249aa0715b47c6938ffb3437b753c1957a08536b)
 - [177f81443fe4dee0832d4d79ea77b21c4cc9c8a5](https://github.com/magento/magento2/commit/177f81443fe4dee0832d4d79ea77b21c4cc9c8a5)
 - [c772d44e7eede1204347f55f718b9c179e3849fe](https://github.com/magento/magento2/commit/c772d44e7eede1204347f55f718b9c179e3849fe)
 - [e99d90a30264bc4c3140dcb814bde5f1bb8d1347](https://github.com/magento/magento2/commit/e99d90a30264bc4c3140dcb814bde5f1bb8d1347)
 - [4a149505a71c883a2c93740d3e4fb5c265a2d267](https://github.com/magento/magento2/commit/4a149505a71c883a2c93740d3e4fb5c265a2d267)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2019-01-19 06:55 UTC
Labels: Issue: Ready for Work, Area: Frontend, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Wishlist
