### ISSUE TITLE
Magento2: Unable to save Catalog Config 

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#5520] opened 2016-07-07 12:42 UTC
We tried to change the SEO settings in Shop -> Config -> Catalog -> Catalog -> SEO, fields:
- Product-URL-Suffix
- Catalog-URL-Suffix

When hitting the save button I assumed that it'd simply safe the new setting, but instead we got this SQL error:
`Beim Speichern der Konfiguration ist ein Fehler aufgetreten. SQLSTATE[42S02]: Base table or view not found: 1146 Table 'reisebil_mg206.url_rewrite' doesn't exist, query was: UPDATE url_rewrite SET request_path = ? WHERE (url_rewrite_id = 76)`

How can we fix this? We are using Magento 2.0.6.

**Comment by veloraven** [comment] 2016-08-12 15:27
@grasdaggel thank you for your report.
We created internal ticket MAGETWO-56810 for this issue, but please note that it is already fixed in version 2.1.

**Comment by grasdaggel** [comment] 2016-10-21 15:01
This bug still exists in Magento 2.0.9. It still not fixed.

**Comment by magento-engcom-team** [comment] 2017-10-12 13:19
@grasdaggel, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-12 13:19 UTC
Labels: Issue: Ready for Work, bug report, Issue:  Cannot Reproduce, Issue: Format is not valid
