### ISSUE TITLE
Currency Setup in admin throws in_array error when a single value is selected

### ISSUE THREAD

**Issue by deriknel** [magento/magento2#8076] opened 2017-01-09 14:14 UTC
### Preconditions
1. Magento ver. 2.1.3
2. Ubuntu 16.04
3. PHP 7.0.8-0ubuntu0.16.04.3 ( NTS )
4. MySQL Ver 15.1 Distrib 10.0.28-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

### Steps to reproduce
1. In admin navigate to configuration 
2. General -> Currency Setup
3. Select a single value in the multiple selects
4. Click on save

### Expected result
1. Currency values should update as per selection

### Actual result
1. Something went wrong while saving this configuration: Warning: in_array() expects parameter 2 to be array, string given in /var/www/clean-m2-ee/vendor/magento/module-config/Model/Config/Backend/Currency/DefaultCurrency.php on line 30

This is because the $this->_getAllowedCurrencies() method returns a string for single values and not an array as expected. Typecasting that to an array would fix this:

if (!in_array($this->getValue(), (array)$this->_getAllowedCurrencies())) {

Or alternatively update the methods to always return arrays.

**Comment by veloraven** [comment] 2017-01-12 12:13
@deriknel thank you for your report.
I was not able to reproduce this issue.
Could you please provide more details?
1. Full description for currencies setup: for base, default displayed and allowed currencies.
2. What level of scope do you use?
3. What Magento mode do you use?
4. Was it clear install or upgrade from some other version?

**Comment by deriknel** [comment] 2017-01-12 13:16
Hi Olga,

1. Under currency tab, select a single Allowed currency:
[image: Inline image 1]

[image: Inline image 2]
When selecting a single value, the method $this->_getAllowedCurrencies()
returns a string but is used in an in_array logical check in files:
Allow.php and DefaultCurrency.php. This is on magento v2.1.3.


2. Default Config
3. Magento Developer
4. Clean Install

Kind Regards,
Derik Nel.
*@:* derik.nel@gmail.com

**Comment by okorshenko** [comment] 2017-02-25 01:42
Closing this issue. PR https://github.com/magento/magento2/pull/8077 was delivered to develop branch

**Closed as completed by okorshenko** 2017-02-25 01:42 UTC
Labels: Issue: Ready for Work, bug report, Progress: needs update, Component: Tax

**Comment by magento-team** [comment] 2017-08-01 14:58
Internal ticket to track issue progress: MAGETWO-65003
