### ISSUE TITLE
Permission Issue on adding bundle product for specific website 

### ISSUE THREAD

**Issue by a4deel** [magento/magento2#33618] opened 2021-07-28 13:48 UTC
### Preconditions (*)

1. Magento Commerce 2.3.5 p2
2. Php version 7.3
3. Admin user with specific website role with all resource access

### Steps to reproduce (*)

1. Go to add new bundle product. Add child product and click on save.
2.

### Expected result (*)

1. New bundle Product should be added
2.

### Actual result (*)

1. More permissions are needed to view this item.
2. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by TheRealHunzik** [comment] 2021-07-28 14:20
@magento give me 2.3 instance

**Comment by Den4ik** [comment] 2021-07-29 19:41
Hi @a4deel Could you please add more information for reproduce issue

**Comment by a4deel** [comment] 2021-07-30 05:51
Hi @Den4ik You have to use Magento EE version. First create another website. Now assign this website to new admin with all role resources and access only to this newly created website. Now login with that admin and try to add bundle product with simple products, it will throw permissions exception. If we add bundle product without childs then exceptions does not occur but when we try to add with childs then this error is being reproduced. thanks and let me know for more information or queries if you have some/.

**Comment by engcom-Echo** [comment] 2021-08-31 08:56
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment] 2021-08-31 09:41
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment] 2021-08-31 10:18
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment] 2021-08-31 13:42
Hi @a4deel 
I tried to reproduce this issue on **2.4-develop** 7 was unable to do so.
Here are the steps I followed,
1. Set up a clean installation of magento 2.4-develop (with EE).
2. Create a new website.
3. Create a new user and assign the newly created website to new user with **all** role resources and access only to this newly created website. 
4. Logged into admin panel using the credentials of the newly created user and try to add bundle product with simple child products.
5. The bundled product along with its child products got saved successfully - **No error or exception** noticed.

**Comment by Den4ik** [comment] 2021-09-01 11:05
> Hi @Den4ik You have to use Magento EE version. First create another website. Now assign this website to new admin with all role resources and access only to this newly created website. Now login with that admin and try to add bundle product with simple products, it will throw permissions exception. If we add bundle product without childs then exceptions does not occur but when we try to add with childs then this error is being reproduced. thanks and let me know for more information or queries if you have some.

Hi @a4deel Does simple product assigned to new website too?

**Comment by engcom-Echo** [comment] 2021-09-14 05:28
Hi @a4deel
Since we didn't get any updates from you & since we couldn't reproduce the issue being reported on 2.4-develop, we are closing this issue.
If this issue is still reproducible for you on magento **2.4-develop**, please feel free to reopen this issue & provide more details or additional/missing steps regarding the same.

Thank you

**Closed as completed by engcom-Echo** 2021-09-14 05:28 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
