### ISSUE TITLE
Submitting empty billing address form will skip validation when displaying on page (instead of methods)

### ISSUE THREAD

**Issue by koenner01** [magento/magento2#33050] opened 2021-05-20 13:22 UTC
When displaying the billing address on page and submitting an empty billing address form in the checkout it will do an actual submit of the form and thus also triggering the controller action. This will result in an error message """%fieldName"" is required. Enter and try again." being returned where the fieldName is "address" which is an untranslatable string.

### Preconditions (*)
1. Magento 2.3.x

### Steps to reproduce (*)
1. Set the "Display Billing Address On" setting to "Payment page";
("Stores > Configuration > Sales > Checkout > Checkout options > Display billing address on")
2. Go to checkout payment step as a guest;
3. Don't enter any data and submit the empty form.

### Expected result (*)
1. Form submit is stopped because of validation;
2. No request should be done and no global error message should be shown.

### Actual result (*)
1. Form is validated but also submitted;
2. A request to the API is done.

I have traced the problem back to vendor/magento/module-checkout/view/frontend/web/js/view/billing-address.js where the updateAddress function is doing an unlogical check.

```
updateAddresses: function () {
    if (window.checkoutConfig.reloadOnBillingAddress ||
        !window.checkoutConfig.displayBillingOnPaymentMethod
    ) {
        setBillingAddressAction(globalMessageList);
    }
},
```

I have no idea why should be allowing the billing address to be set when "window.checkoutConfig.displayBillingOnPaymentMethod" is true...

Doing the exact same flow when showing the form on the payment methods will block the form submit on faulty validation (which is the correct flow).

Please find this [comment](https://github.com/magento/magento2/issues/33050#issuecomment-871203764) for more details about the issue.
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by koenner01** [comment] 2021-05-20 13:31
The issue is also present when you enter values in the form but still have invalid fields left.
The form is still being submitted and a request is done with an empty "address" parameter sent.

When omitting the weird displayBillingOnPaymentMethod check 

```
updateAddresses: function () {
    if (window.checkoutConfig.reloadOnBillingAddress) {
        setBillingAddressAction(globalMessageList);
    }
},
```

Everything seems to work correctly.
But I have no idea why this functionality exists or what the reasoning behind it is

**Comment by krishprakash** [comment] 2021-05-25 06:02
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2021-06-30 08:31
Verified the issue on Magento Version 2.4-develop and the issue is reproducible.
**Steps Performed:**
1. Set the "Display Billing Address On" setting to "Payment page";
    ("Stores > Configuration > Sales > Checkout > Checkout options > Display billing address on")
2. Go to checkout payment step as a guest;
3. Do not enter Shipping address and click on Next button - No API request is triggered.
4. Fill the Shipping Address form and click on Next button
5. Expand Billing Address section and do not enter Billing Address
6. Click on Update button
**Issue: "Address is required. Enter and try again" error message is displayed on UI and API request is getting triggered with 400 Status code**
**Billing Address validation screenshot:**
![image](https://user-images.githubusercontent.com/60198231/123928274-63af4d00-d9ab-11eb-8afe-f195dd6304ea.png)
**Shipping Address validation screenshot**
![image](https://user-images.githubusercontent.com/60198231/123928452-8d687400-d9ab-11eb-809a-c55b1a374c89.png)

**Comment by magento-engcom-team** [comment] 2021-07-01 13:12
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42766` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment] 2024-06-14 04:26
Hi @koenner01,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="1439" alt="Screenshot 2024-06-14 at 09 52 09" src="https://github.com/magento/magento2/assets/51680745/2833cf7f-9ce2-467e-9094-e7387cf63f42">


**Form submit is stopped because of validation**

**No request should be done and no global error message should be shown.**


Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-14 04:26 UTC
Labels: Component: Checkout, Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done, Reported on 2.3.x, Area: Cart & Checkout
