### ISSUE TITLE
Cannot save date on product attribute when using a locale that changes date format and the day is greater than 12

### ISSUE THREAD

**Issue by bmisyura** [magento/magento2#12700] opened 2017-12-14 10:41 UTC
If you add a date attribute to a product or add a date in a product widget and are using a locale that changes the date format and the day set is greater than 12, you get the following error when saving:
Invalid input datetime format of value '14/06/2017'. If you set the date in US english first and then switch to another locale, it displays an incorrect date (when day is greater than 12). If you set a date in US english with day less than 12 and then switch the locale, it shows the original US date format.

### Preconditions

1. Install Magento from 2.2-develop branch

### Steps to reproduce

1. Go to system>permissions>all users and set the admin user locale to **English Australia** and save
2. Go to stores>atttributes>products and create a date attribute
3. Go to stores>atttributes>attribute set
4. Add the attribute to default set
5. Create a new product
6. Set the date to any month with the day being greater than 12
7. Try to save
8. Notice the error - Invalid input datetime format of value '14/06/2017
____
1. Go to system>permissions>all users and set the admin user locale to **English US** and save
2. Go to stores>atttributes>products and create a date attribute
3. Go to stores>atttributes>attribute set
4. Add the attribute to default set
5. Create a new product
6. Set the date to any month with the day being greater than 12 (Feb 14 2018)
7. Save the product
8. Go to system>permissions>all users and set the admin user locale to **English Australia** and save
9. go back to the product
10. Notice the date is incorrect (06/12/2017)
11. Notice you cannot save the product and error is given "Invalid input datetime format of value '14/02/2018'"
___
1. Go to system>permissions>all users and set the admin user locale to **English US** and save
2. Go to stores>atttributes>products and create a date attribute
3. Go to stores>atttributes>attribute set
4. Add the attribute to default set
5. Create a new product
6. Set the date to any month with the day being less than 12
7. Save the product
8. Go to system>permissions>all users and set the admin user locale to **English Australia** and save
9. go back to the product
10. Notice the date is still in US format

The merchant states that this also occurs if you add a date to a product widget

### Expected result
The product should save and the dates should be correct when switching the locale after a date is set in US locale

### Actual result
The product does not save and gives the error Invalid input datetime format of value '14/06/2017. The date is not correct when switching the locale after a date is set in US locale.

**Comment by gwharton** [comment] 2017-12-14 10:57
Heavily related, and possible duplicate of #10580

**Comment by ishakhsuvarov** [comment] 2018-09-27 06:57
Closing per comment above. 
Thanks for pointing out.

**Closed as completed by ishakhsuvarov** 2018-09-27 06:57 UTC
Labels: bug report, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Issue: Format is valid
