### ISSUE TITLE
Fixed price bundle products with priced options do not include option prices in tax calculation

### ISSUE THREAD

**Issue by navarr** [magento/magento2#27700] opened 2020-04-10 19:30 UTC
### Preconditions (*)
1. Magento 2.3.4
2. Vertex not installed
3. entire state of PA configured to be 6% taxable
4. Customer "Bob Saget" with address:
    525 N Allen St
    State College, PA 16803-3503
    USA
    (any phone number)
5. Incl/Excl tax display enabled for all fields
6. "Apply Tax On" configured to "Original price only"

### Steps to reproduce (*)
1. Create a bundle product
2. Set dyanmic price to No
3. Set price to $61
4. Create a required radio option w/ a price of 23 and quantity of 1
5. Create a required radio option w/ a price of 5 and quantity of 1
6. Save bundle product
7. Go to create new order in admin
8. Select Bob Saget as customer
9. Add fixed bundle product to order, configured with 1 of each required option and total quantity 3
10. "Add selected products to order"
11. Select fixed shipping method

### Expected result (*)

1. Order Grid:
    Price Excl Tax: $89
    Price Incl Tax: $94.34
    Subtotal Excl Tax: $267
    Subtotal Incl Tax: $283.02
2. Order Totals
    Subtotal Excl Tax: $267
    Subtotal Incl Tax: $283.02
    Tax: $16.02

### Actual result (*)

1. Order Grid:
    Price Incl Tax: $92.66
    Subtotal Incl Tax: $277.98
2. Order Totals:
    Subtotal Incl Tax: $277.98
    Tax: $10.98

**Comment by navarr** [comment] 2020-04-10 19:31
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-10 19:32
Hi @navarr. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-10 19:33
Hi @navarr, here is your [Magento instance](https://i-27700-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27700-2-4-develop.instances.magento-community.engineering/admin_ff19](https://i-27700-2-4-develop.instances.magento-community.engineering/admin_ff19)
Login: `182d873e` Password: `bba7b39640ae`
Instance will be terminated in up to 3 hours.

**Comment by navarr** [comment] 2020-04-10 19:41
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-10 19:41
Hi @navarr. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by navarr** [comment] 2020-04-10 19:57
@magento give me 2.3 instance

**Comment by navarr** [comment] 2020-04-13 12:30
@magento give me 2.3 instance

**Comment by navarr** [comment] 2020-04-13 13:35
Issue is not reproducible on 2.4 but I have been unable to check 2.3.5

**Comment by navarr** [comment] 2020-04-20 14:14
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-20 14:14
Hi @navarr. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-20 14:15
Hi @navarr, here is your [Magento instance](https://i-27700-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27700-2-4-develop.instances.magento-community.engineering/admin_4421](https://i-27700-2-4-develop.instances.magento-community.engineering/admin_4421)
Login: `fc0777d5` Password: `2ef1660fb08b`
Instance will be terminated in up to 3 hours.

**Comment by navarr** [comment] 2020-04-20 14:23
Confirmed on 2.4

**Comment by navarr** [comment] 2021-01-12 13:40
This is duplicated by #28051

**Comment by engcom-Alfa** [comment] 2021-01-13 10:31
Duplicate of #28051

**Closed as completed by engcom-Alfa** 2021-01-13 10:31 UTC
Labels: Component: Tax, Component: Bundle, Issue: ready for confirmation, Reported on 2.3.4
