### ISSUE TITLE
Returning null on _getEavWebsiteTable results in describe table error.

### ISSUE THREAD

**Issue by DwayneH** [magento/magento2#6043] opened 2016-08-08 07:36 UTC
When creating a new EAV entity type the attribute models extending both `\Magento\Eav\Model\ResourceModel\Attribute` aswell as `\Magento\Eav\Model\ResourceModel\Attribute\Collection`
 demand (by interface) the implementation of a function called _getEavWebsiteTable. In the documentation it says:

> If realisation doesn't demand this functionality, let this function just return null

 though the function is used to directly describe and join specific collections resulting in SQL errors.

### Precondition
Magento 2.2.0

### Steps to reproduce
1.  Create a new eav entity without attribute_website table including attribute models (or to make it easier and quicker just return null on the customer one).
2. Retrieve the collection of attributes from your custom entity.
### Expected result
1.  Collection of attributes
### Actual Result
1. SQL Error: 
   `SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '', query was: DESCRIBE ''`

I will create a pull request with a fix for this issue.

**Comment by magento-engcom-team** [comment] 2017-09-11 22:44
@DwayneH thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [x] Preconditions: Magento version

**Comment by magento-engcom-team** [comment] 2017-11-28 12:30
@DwayneH, thank you for your report.
We've created internal ticket(s) MAGETWO-84626 to track progress on the issue.

**Comment by magento-engcom-team** [comment] 2018-08-20 11:06
Hi @DwayneH

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment] 2018-09-07 11:58
@DwayneH, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Closed as completed by magento-engcom-team** 2018-09-07 11:58 UTC
Labels: Issue: Ready for Work, bug report, Component: Eav, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is not valid, Event: distributed-cd, triage wanted
