### ISSUE TITLE
Category Description Not Loading in TinyMCE Editor at Store View Level in Magento 2.4.7-p3

### ISSUE THREAD

**Issue by imran215** [magento/magento2#39475] opened 2024-12-13 09:08 UTC
### Preconditions and environment

Magento Open Source version 2.4.7-p3.
A fresh Magento installation with:
-Multiple websites, stores, and store views created.
-Page Builder disabled.
-TinyMCE WYSIWYG editor enabled.

### Steps to reproduce

1. Install Magento 2.4.7-p3.
2. Navigate to Stores > All Stores and create:
    - One additional website.
    - A store under the new website.
    - A store view under the new store.

3. Navigate to Stores > Configurations > General > Content Management > Advanced Content Tools and:
    - Disable Page Builder.
    - Ensure Enable WYSIWYG Editor is set to Yes (TinyMCE editor enabled).

4. Navigate to Catalog > Categories.
5. Create a new category and save.
6. Switch to a store view in the Store View Selector.
7. Add or update the category Description field at the store view level.
8. Save the category.

### Expected result

The category description should load in the TinyMCE editor when switching back to the store view.

### Actual result

The category description is saved in the database but does not load into the TinyMCE editor at the store view level when revisiting the category edit page.

### Additional information

- Database Check: The description value is present in the catalog_category_entity_text table with the correct attribute_id and store_id.
- Scope Issue: This issue appears to affect only store view-specific descriptions when Page Builder is disabled and TinyMCE is enabled.
- Logs: No specific errors are observed in exception.log or system.log.
- When I change <field name="description" template="ui/form/field" sortOrder="50" formElement="wysiwyg"> To <field name="description" template="ui/form/field" sortOrder="50" formElement="textarea"> in vendor/magento/module-catalog/view/adminhtml/ui_component/category_form.xml, the description start loading in textarea but when i change this back to wysiwyg, then it does not load.

### Release note

Environment Details

-     Magento Version: 2.4.7-p3
-     PHP Version: 8.3
-     Elasticsearch Version: 8.11.x
-     Database: mariadb:10.6
-     Browser: Chrome 131.x 

Steps Tried to Fix

-     Flushed the cache: php bin/magento cache:flush.
-     Reindexed data: php bin/magento indexer:reindex.
-     Verified the database entries for the description.
-     Checked browser console logs for JavaScript errors. Multiple errors related to TinyMCE 7.
-  
![image](https://github.com/user-attachments/assets/2d47af91-cdb9-4332-9744-55737b123759)

-     Verified configuration settings for WYSIWYG editor and scope handling.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-12-16 07:38
Hi @imran215,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop Magento instance and the issue is not reproducible.Kindly refer the screenshots.


![BDAY-Coupon-ID-7-Categories-Inventory-Catalog-Magento-Admin-12-16-2024_11_36_AM](https://github.com/user-attachments/assets/9a1c2fc4-b472-456b-ba76-71447499707d)



The category description was loaded in the TinyMCE editor when switching back to the store view.We are able to add and update the changes successfully and there were no console errors.

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by imran215** [comment] 2024-12-16 11:54
@engcom-Bravo This is reproduce able on 2.4.7-p3. Can you suggest the patch/commit that resolve issue in 2.4-develop so that we can add that fix in our current live website? You know we cannot upgrade our live site to develop.

**Comment by hostep** [comment] 2024-12-16 21:03
@imran215: I believe this is a duplicate of https://github.com/magento/magento2/issues/38622 which got fixed by https://github.com/magento/magento2/pull/38623

**Comment by engcom-Bravo** [comment] 2024-12-17 03:44
@hostep Thanks for your Contribution!!.

Hi @imran215,

Please refer this comment https://github.com/magento/magento2/issues/39475#issuecomment-2546764630 and the fix is here https://github.com/magento/magento2/pull/38623.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-12-17 03:44 UTC
Labels: Issue: needs update, Reported on 2.4.7-p3
