### ISSUE TITLE
CMS page Data Upgrade failed

### ISSUE THREAD

**Issue by martinboy** [magento/magento2#5437] opened 2016-07-04 07:31 UTC
In the reference to this commit https://github.com/magento/magento2/commit/3b9511f682522f9b6dd99634f46a1604323925b0
## Steps to reproduce
1. Migrate data from Magento 1.x to 2.0.7 using Magento data migration tool version 2.0.7
2. There is no CMS page with ID 4 in database. In some cases the page with the ID 4 may contain the  data not the one that supposed to be seen, i.e. absolutely different page identifier but not 'privacy-policy-cookie-restriction-mode'
3. Upgrade Magento from 2.0.7 to 2.1.0.
## Expected result
1. The page should be loaded by identifier not ID
2. Update page content if it exists
3. Skip page updating / create new page if identifier is not exists.
4. Setup data upgrade script shouldn't be crashed.
## Actual result

Setup data upgrade fails with the exception:

```
[Magento\Framework\Exception\LocalizedException]
The page URL key contains capital letters or disallowed symbols.
```

**Comment by veloraven** [comment] 2016-08-11 13:02
@martinboy  if this issue is specific to migration process, please, create a ticket in corresponding repository: https://github.com/magento/data-migration-tool/issues

**Comment by jarhody** [comment] 2016-08-25 19:33
@martinboy Did you ever resolve the issue? I am facing the same thing.

**Comment by martinboy** [comment] 2016-08-26 06:39
@jarhody just manually edited the file app/code/Magento/Cms/Setup/UpgradeData.php and removed CMS page creation code

**Comment by martinboy** [comment] 2016-08-26 07:01
@veloraven it is not a migration specific issue but reproduced when I migrated the data. You can reproduce it like this:
1. Setup Magento 2.0.7 
2. Remove CMS page with ID 4 from database. 
3. Upgrade Magento from 2.0.7 to 2.1.0.

**Comment by shiftedreality** [comment] 2016-09-07 14:03
Hi @martinboy 

I was unable to reproduce this issue using 2.0.9 ->2.1.1 upgrade flow.
Could you please try to reproduce this on your local machine?

**Comment by shiftedreality** [comment] 2016-09-07 14:07
This looks fixed in https://github.com/magento/magento2/commit/ae05195601f91d8fc0ccb98ea477dfb87547d0d4

Closed.

**Closed as completed by shiftedreality** 2016-09-07 14:07 UTC
Labels: bug report, Progress: needs update, Component: Setup
