### ISSUE TITLE
Free Shipping Not Initially Available as Shipping Method in Multi-Shipping

### ISSUE THREAD

**Issue by thebreakfastcowboy** [magento/magento2#12408] opened 2017-11-22 19:57 UTC
Expected result:
In multi-shipping checkout, when an order qualifies for free shipping, the Free Shipping shipping method is available for selection at the /multishipping/checkout/shipping/ step.

Actual result:
Free Shipping is not available until the /multishipping/checkout/shipping/ step, but if you continue to billing and then click "back to shipping", it will be available. Same for if you proceed to review the order and then go back to shipping. 

I'm using Magento CE 2.1.10, with very minimal/vanilla extending of the Blank for my theme so far.

**Comment by magento-engcom-team** [comment] 2017-11-23 09:48
@thebreakfastcowboy, thank you for your report.
The issue is already fixed in develop branch, 2.2.1

**Closed as completed by magento-engcom-team** 2017-11-23 09:48 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid

**Comment by thebreakfastcowboy** [comment] 2017-11-27 15:26
Thank you!
