### ISSUE TITLE
Products Custom Option as Required issue.

### ISSUE THREAD

**Issue by amarroni** [magento/magento2#5599] opened 2016-07-12 16:53 UTC
I was working with some virtual, bundlle products and configure some custom options. Please review the sptes of the issue. I could reproduce the issue in 2 differents instnaces of M2
## Steps to reproduce
1. Create a test product
2. Add different custom options as drop-down with some option values
3. select as required option
4. [save]
5. change to no-required option
6. [save]
## Expected result
1. option updated as no-required option should be updated correctly
## Actual result
1. option updated as no-required option still as required option
2. See attached images
   ![updated-as-no-required](https://cloud.githubusercontent.com/assets/5198527/16775615/d4770d94-4837-11e6-839b-c40dfb63f1e6.png)
   ![test products inventory products magento admin](https://cloud.githubusercontent.com/assets/5198527/16775619/dff56c7e-4837-11e6-8b28-95881ff5a2c6.png)

I'm running Magento 2.0.7
Best,
Alejandro.

**Comment by veloraven** [comment] 2016-08-04 09:54
This issue is duplicate of #4462 
We already have an internal ticket MAGETWO-52971, I have link it to this one.

**Comment by amarroni** [comment] 2016-08-04 12:39
@veloraven thank you so much!

So do you think I need to close this ticket?

**Comment by magento-engcom-team** [comment] 2017-10-06 13:30
@amarroni, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-06 13:30 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is not valid
