### ISSUE TITLE
"We can't find products matching the selection." for categories without children

### ISSUE THREAD

**Issue by AymericJoubert** [magento/magento2#35829] opened 2022-07-27 12:54 UTC
### Preconditions and environment

- Magento 2.4.4
- Sample data deployed
- Elasticsearch 7.16.3

### Steps to reproduce

1. Deploy sample data
2. Reindex everything
3. On the frontend, go on a category without children (ex: Women -> Top -> Tees)

### Expected result

I see the products that are assigned to the category.

### Actual result

There is no products, the info message "We can't find products matching the selection." is displayed.

### Additional information

This is because the "category_ids_to_aggregate" filter is missing when a category don't have child.
See \Magento\CatalogSearch\Model\Layer\Filter\Category:86

The error in the logs : 
`Elasticsearch\Common\Exceptions\ServerErrorResponseException: {"error":{"root_cause":[{"type":"aggregation_execution_exception","reason":"Aggregation [category_bucket] cannot support regular expression style include/exclude settings as they can only be applied to string fields. Use an array of numeric values for include/exclude clauses used to filter numeric fields"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"magento_product_1_v2","node":"b7r-vfg6T4K4u52D9yvrww","reason":{"type":"aggregation_execution_exception","reason":"Aggregation [category_bucket] cannot support regular expression style include/exclude settings as they can only be applied to string fields. Use an array of numeric values for include/exclude clauses used to filter numeric fields"}}]},"status":500} in vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:726
`

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-07-28 11:51
Hi @AymericJoubert,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue.
![Screenshot (375)](https://user-images.githubusercontent.com/51680745/181497593-d8e9c596-a1e0-4608-9dd4-7c7638cea852.png)

Followed steps:
 1.Sample data Deployed
 2.Reindexing
 3.Go to Catalog page

Please Review the mentioned steps.

Regards,

**Comment by engcom-Bravo** [comment] 2022-08-16 05:11
Hi @AymericJoubert,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-08-16 05:11 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
