### ISSUE TITLE
Circular dependency: Magento\Framework\App\Cache\Type\Config depends on Magento\Framework\Interception\PluginList\PluginList and vice versa

### ISSUE THREAD

**Issue by kc-shubham** [magento/magento2#39229] opened 2024-10-01 06:57 UTC
### Preconditions and environment

- Magento version: 2.4.7-p2
Upgrade magento version from older version to new version

### Steps to reproduce

Trying to upgrade magento version from 2.4.6-p6 to 2.4.7-p2
Run the following command:

bin/magento maintenance:enable
composer require magento/product-community-edition 2.4.7-p2 --no-update
composer update -W
php bin/magento setup:upgrade
php bin/magento setup:di:compile

### Expected result

Compile command should be executed successfully

### Actual result

Circular dependency: Magento\Framework\App\Cache\Type\Config depends on Magento\Framework\Interception\PluginList\PluginList and vice versa.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by kc-shubham** [comment] 2024-10-01 09:46
@engcom-Bravo please speed up this issue

**Comment by engcom-Delta** [comment] 2024-10-03 12:19
Hi @kc-shubham ,

Thanks for your reporting and collaboration.
We have verified the issue in 2.4.6-p6  to 2.4.7-p2 version, but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce**
1. Install Magento Version 2.4.6-p6
2. Run the following command:
3. bin/magento maintenance:enable
4. composer require-commerce magento/product-community-edition 2.4.7-p2 --no-update
5. composer update -W
6. php bin/magento setup:upgrade
7. php bin/magento setup:di:compile
![image](https://github.com/user-attachments/assets/db138e62-948e-4fa7-9de5-0e10230f8a5d)
User is able to upgrade to 2.4.7-p2 version successfully.
![image](https://github.com/user-attachments/assets/b4aaf6f4-bb69-4942-94a8-3acf21bcb894)

Please let us know if any other steps are needed to be performed.

Thanks.

**Comment by engcom-Delta** [comment] 2024-10-14 11:55
Hi @kc-shubham ,

We have noticed that this issue has not been updated since long time.
Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Delta** 2024-10-14 11:55 UTC
Labels: Issue: needs update, Reported on 2.4.7-p2

**Comment by Paulsky** [comment] 2024-12-10 16:04
@kc-shubham did you ever fixed this? Do you have any workaround?

**Comment by Paulsky** [comment] 2024-12-10 16:42
It has something to do with Redis. My configuration was something like this in `env.php:`

```
 'cache' => [
        'frontend' => [
            'default' => [
                'backend' => 'Magento\\Framework\\Cache\\Backend\\Redis',
                'backend_options' => [
                    'server' => 'redis-cache.sock',
                    'database' => '0',
                    'port' => '0',
                    'password' => '',
                    'compress_data' => '1',
                    'compression_lib' => ''
                ]
            ],
        ],
    ],
```

I changed  `'database' => '0',` to  `'database' => '1',` and now the error is gone

**Comment by roman204** [comment] 2025-01-10 15:51
after cleaning redis cache it works

**Comment by harishrave** [comment] 2025-03-06 15:32
@Paulsky I am facing the same issue locally since Redis is not configured. Do you have any suggestions on how to resolve it?

**Comment by Paulsky** [comment] 2025-03-06 16:12
@harishrave do you plan to configure Redis? If not, maybe you can switch to File type caching? Please see: https://experienceleague.adobe.com/en/docs/commerce-operations/configuration-guide/cache/caching-overview.

I think you can set the cache to null or to `Magento\Framework\Cache\Backend\File`

Something like:

```
 'cache' => [
        'frontend' => [
            'default' => [
                'backend' => 'Magento\\Framework\\Cache\\Backend\\File',
            ],
        ],
    ],

```

**Comment by nmpanchal712** [comment] 2025-03-07 08:15
@Paulsky I am facing the same issue locally because Redis is not configured. Can anyone suggest how I can resolve this?

![Image](https://github.com/user-attachments/assets/0aa507ff-71ef-4c91-823f-a28319a1d708)

**Comment by MeliminiP** [comment] 2025-04-23 20:02
For futur reference if anyone goes through the same! I faced the same issue after creating a bad plugin but nothing I did could get the error to go away, even after going back to develop branch and deleting all genrated and cached files. I wasn't using redis on local but I ended up installing it and it did fix the error. Then I just went back to using file system for cache and everything is fine!
