### ISSUE TITLE
Why .gitignore don't contain ruls for media?

### ISSUE THREAD

**Issue by springimport** [magento/magento2#8976] opened 2017-03-22 17:21 UTC
### Preconditions
Magento version - 2.1.5

### Steps to reproduce
1. I want to track files with git without media.

### Expected result
`.gitignore`

- `pub/media/favicon`
- `pub/media/logo`

### Actual result
`.gitignore` without ruls for media.

| Q | A |
| --- | --- |
| Magento version | 2.1.5 |
| PHP version | 7 x64 |
| Operating system | Windows 10 x64 |

**Comment by choukalos** [comment] 2017-03-27 19:08
Can you send us a PR?

**Comment by springimport** [comment] 2017-03-28 13:24
Did you mean the media?

Directory structure:
![media](https://cloud.githubusercontent.com/assets/18581994/24405847/4bb8f9ee-1394-11e7-9222-441dad74eb2f.PNG)

In git:
![media-in-git](https://cloud.githubusercontent.com/assets/18581994/24405927/8d634c00-1394-11e7-88f9-faac8abfaa1b.PNG)

**Comment by mrkhoa99** [comment] 2017-03-28 14:23
@springimport  You can simply add these lines to your git ignore:

```
!/pub/media/logo/*
!/pub/media/favicon/*
```

**Comment by springimport** [comment] 2017-03-29 12:58
@mrkhoa99  Yes, of course. I want to know whether this is a bug or not.

**Comment by mrkhoa99** [comment] 2017-03-29 13:01
@springimport these files was uploaded via Admin?

**Comment by springimport** [comment] 2017-03-30 12:47
@mrkhoa99 Yes, from admin panel.

**Comment by orlangur** [comment] 2017-03-30 12:57
Can we somehow ignore all folders in `/pub/media` besides specified https://github.com/magento/magento2/tree/develop/pub/media ?

This list is already quite big: https://github.com/magento/magento2/blob/develop/.gitignore#L35

So, maybe there is a smarter way than just adding `logo` and `favicon`?

**Comment by springimport** [comment] 2017-03-31 14:57
@orlangur Maybe, I'm not sure.

**Comment by magento-engcom-team** [comment] 2017-10-04 14:30
@springimport, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-04 14:30 UTC
Labels: Issue: Clear Description, Issue: Format is valid
