### ISSUE TITLE
Magento 2.2.5 Enterprise - Special Price issue occur when it set to 0 

### ISSUE THREAD

**Issue by Hashamwebdev** [magento/magento2#22472] opened 2019-04-24 05:19 UTC
### Preconditions (*)
Magento version 2.2.5

### Steps to reproduce (*)
1. Login to Admin panel
2. Catalog ->Product
3. Open any product detail page
4. Go for `Advanced Pricing` below price and set special price to zero because I have sorting based on price on category page it set the final price to zero but it show the actual price on listing not special price

![image](https://user-images.githubusercontent.com/49894811/56634132-41f30680-667a-11e9-8cb3-e75556eceed9.png)

### Expected result (*)
1. First it will not allow to set special price to zero because it destroy the price sorting on category page if it allows then it will show price 0 against product on category page   

### Actual result (*)

1. Firstly it allowed special price to set to 0 then it will show the actual price against the product in category page.

**Comment by Hashamwebdev** [comment] 2019-04-24 05:22
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-04-24 05:22
Hi @Hashamwebdev. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-24 05:22
Hi @Hashamwebdev, here is your [Magento instance](https://i-22472-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22472-2-3-develop.instances.magento-community.engineering/admin](https://i-22472-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2019-04-24 05:29
Give me @magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-04-24 05:29
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by Hashamwebdev** [comment] 2019-04-24 05:29
@magento-engcom-team I reproduced the issue on 2.3-develop instance as well

**Comment by magento-engcom-team** [comment] 2019-04-24 05:30
Hi @ajijshekh123, here is your [Magento instance](https://i-22472-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22472-2-3-develop.instances.magento-community.engineering/admin](https://i-22472-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2019-04-24 05:45
Give me @magento-engcom-team give me 2.2-develop instance.

**Comment by magento-engcom-team** [comment] 2019-04-24 05:45
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-24 05:46
Hi @ajijshekh123, here is your [Magento instance](https://i-22472-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22472-2-2-develop.instances.magento-community.engineering/admin](https://i-22472-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2019-04-24 05:59
@Hashamwebdev - I have set Special price to zero in Magento 2.2 and Magento 2.3 instance. Special price and Regular price both are displaying on Category page.

**Comment by magento-engcom-team** [comment] 2019-04-24 06:15
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99375` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ajijshekh123** [comment] 2019-04-24 06:17
FYI, Issue not reproduced Magento 2.2

**Comment by Hashamwebdev** [comment] 2019-04-24 06:31
FYI, It reproduced on Magento 2.2.5. Check the reference screenshots

Category page:

![image](https://user-images.githubusercontent.com/49894811/56637241-9a2f0600-6684-11e9-8eb4-b1dddbe72669.png)


Admin Product detail page:

![image](https://user-images.githubusercontent.com/49894811/56637193-78358380-6684-11e9-80d2-ad01b7b65200.png)

**Comment by shikhamis11** [comment] 2019-04-24 16:23
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-04-24 16:24
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-24 16:24
Hi @shikhamis11, here is your [Magento instance](https://i-22472-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22472-2-2-develop.instances.magento-community.engineering/admin](https://i-22472-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2019-04-24 16:29
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-04-24 16:29
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-24 16:30
Hi @shikhamis11, here is your [Magento instance](https://i-22472-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22472-2-3-develop.instances.magento-community.engineering/admin](https://i-22472-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2019-04-24 16:44
@ajijshekh123 I have checked the issue .. at 2.3-develop and 2.2-develop I am able to see the both special price and normal price set at magento admin as you already said. In this case this is expected behaviour.

@Hashamwebdev thank you for report. It seems the your issue is already fixed .. message here if you are able to reproduce it on lastest magento versions

**Closed as completed by shikhamis11** 2019-04-24 16:44 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Admin

**Comment by Hashamwebdev** [comment] 2019-04-25 06:32
@shikhamis11  have you set the special price to 0 ? if yes then you will see only actual price on category page (Frontend). Obviously It will show price and special price at admin that is not the issue. The issue if you set the special price to 0, that particular product will show only actual price and not special price on category page (Frontend). I checked in 2.2 and 2.3 in both version it will show the actual price on the category page (Frontend).  if you claim, it will show both special price and actual price then please share the screenshot of category page (frontend). I hope you got my point, keep in mind I only talked about the case when special price is set to 0. In other cases, It will show both prices. 

FYI, I am using right now Magento 2.2.5 Enterprise edition.

**Comment by Hashamwebdev** [comment] 2019-04-25 06:34
I request @magento-engcom-team please open the issue

**Comment by shikhamis11** [comment] 2019-04-25 06:39
hello @Hashamwebdev 
Let me share you screenshots

**Comment by shikhamis11** [comment] 2019-04-25 06:39
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-04-25 06:39
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-25 06:40
Hi @shikhamis11, here is your [Magento instance](https://i-22472-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22472-2-3-develop.instances.magento-community.engineering/admin](https://i-22472-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Hashamwebdev** [comment] 2019-04-25 06:42
hello @shikhamis11 please share the screenshot of version 2.2 instance as well. I am talking about category page (Frontend)

**Comment by shikhamis11** [comment] 2019-04-25 06:44
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-04-25 06:44
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-25 06:45
Hi @shikhamis11, here is your [Magento instance](https://i-22472-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22472-2-2-develop.instances.magento-community.engineering/admin](https://i-22472-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2019-04-25 06:51
@Hashamwebdev can you please check pages 
https://i-22472-2-2-develop.instances.magento-community.engineering/products.html
https://i-22472-2-3-develop.instances.magento-community.engineering/products.html

**Comment by Hashamwebdev** [comment] 2019-04-25 06:54
@shikhamis11 Thanks for working on the issue, may be issue occur due to my custom theme, As these are the screenshots of luma theme

**Comment by shikhamis11** [comment] 2019-04-25 06:59
@Hashamwebdev yes It is possible due to some custom extension installed on your site
