### ISSUE TITLE
PHP 8.2 readonly classes not supported in dependency injection

### ISSUE THREAD

**Issue by speller** [magento/magento2#37544] opened 2023-05-25 11:31 UTC
### Preconditions and environment

- Magento version 2.4.6
- PHP 8.2

### Steps to reproduce

- Create a readonly class in a module:
    ```php
    readonly class Hotblocks implements ResolverInterface
    {
      public function __construct(
          private HotBlocksGraphQlHelper $hotBlocksGraphQlHelper,
          private DateTime $dateTime,
          private HotBlocksCollectionFactory $hotBlocksCollectionFactory
      ) {
      }
    ```
- Run `setup:di:compile`

### Expected result

Command finished successfully.

### Actual result

Error:
```none
PHP Fatal error:  Non-readonly class Rhdjapan\HotblocksGraphQl\Model\Resolver\Hotblocks\Interceptor cannot extend readonly class Rhdjapan\HotblocksGraphQl\Model\Resolver\Hotblocks in /magento/generated/code/Rhdjapan/HotblocksGraphQl/Model/Resolver/Hotblocks/Interceptor.php on line 7
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2023-05-26 10:09
Hello @speller,

Thanks for the report and collaboration!

We have tried to reproduce the issue in the 2.4-develop branch but it seems the issue is not reproducible for us:

<img width="764" alt="image" src="https://github.com/magento/magento2/assets/51681618/2b5a3e97-4e50-4a68-b260-c330e8561daf">

We are having PHP version PHP 8.2.6.

And we made a custom module in order to reproduce the issue. Please refer to the below module for reference:
[Magz.zip](https://github.com/magento/magento2/files/11574056/Magz.zip)

Let us know if we have missed anything.

Thanks

**Comment by speller** [comment] 2023-05-27 00:12
@engcom-Hotel Could you verify, that the interceptor class in your case is also readonly? In my case, it still doesn't work.

**Comment by speller** [comment] 2023-05-28 11:44
@engcom-Hotel I think you've missed the point that interceptors are not generated until a plugin is declared. As soon as you add a plugin in the `di.xml` for the readonly class, the interceptors compilations will start failing with the mentioned error. From what I can see, the underlying Laminas code generation package doesn't support readonly classes as well.

**Comment by engcom-Hotel** [comment] 2023-06-05 12:47
Hello @speller,

Thanks for the reply!

After making the plugin on the `readonly` class the issue is reproducible for us. Pleas refer to the below screenshot;

![image](https://github.com/magento/magento2/assets/51681618/8b014f96-ffd7-445f-a18b-2aff835cace1)

Hence confirming the issue.

Thanks

**Comment by engcom-Bravo** [comment] 2023-12-04 04:56
Hi @speller,

In the [Adobe Commerce development guide](https://developer.adobe.com/commerce/php/development/components/plugins/#before-methods:~:text=A%20plugin%2C%20or%20interceptor%2C%20is%20a%20class%20that%20modifies%20the%20behavior%20of%20public%20class%20functions%20by%20intercepting%20a%20function%20call%20and%20running%20code%20before%2C%20after%2C%20or%20around%20that%20function%20call.), a plugin, or interceptor, is a class designed to modify the behavior of public class functions by intercepting their calls. While you can create plugins for public classes, readonly classes pose limitations. Creating plugins for readonly classes is not supported, and readonly classes do not allow function overriding.
During Dependency Injection (DI) compilation, a noteworthy aspect is that when a plugin is employed, the intercepted class remains in the public class, not the readonly class. This is because readonly classes can only extend other readonly classes, making it impossible for a public interceptor class to extend a readonly class.
Understanding these details is essential we are closing this issue.


Thanks.

**Closed as completed by engcom-Bravo** 2023-12-04 04:56 UTC
Labels: Issue: Confirmed, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P2, Severity: S1, Progress: done, Area: Framework, Reported on 2.4.6
