### ISSUE TITLE
Bundle product: incorrect child item invoice_qty when dynamic price is set to false 

### ISSUE THREAD

**Issue by Emanuel-23** [magento/magento2#30802] opened 2020-11-05 13:34 UTC
### Preconditions (*)

1. Fresh Magento 2.3.5 or 2.3.6 Open Source (also reproducible on 2.4-develop) with at least 2 simple products that are in stock (optionally: demo content)
2. Access to database tables  (we want so look into the table `sales_order_item`)

### Steps to reproduce (*)

1. Create a new bundle product via Magento 2 administration
1.1. Change "Dynamic Pricing" setting to false
1.2. Add a price i.e. 75 $
1.3. Perhaps not relevant, but in my use case: [Add visible to "not visible individually"]
1.4. Add bundle options with setting "ship bundle items" set  to "together" <br><img width="1555" alt="1 4" src="https://user-images.githubusercontent.com/48509424/98245762-b1d19500-1f71-11eb-849d-e6d1408106c4.png">
1.4.1. Add one bundle option with a name of your choice of input type "checkbox" and set to "required"
1.4.2. Add two simple products of your choice (i.e. ID 1 and ID 2 of the demo content products) 
1.4.3. Change the qty settings of the simple products to a qty > 1 (i.e. 2 and 3)
1.4.4. leave the price range setting on "fixed"
1.4.5. Mark the checkbox "is Default"   
1.5. Save the product
2. Create a new order via Magento 2 administration 
2.1. Add the new bundle product to your order <br> <img width="1177" alt="2 1" src="https://user-images.githubusercontent.com/48509424/98245888-dded1600-1f71-11eb-8413-acaed93a9fb4.png">
2.2. Click on configure and only change the qty to 2 
2.3. Save the product items (uncheck the discount if it has been set, but dont recalculate)
2.4. Add a payment of your choice
2.5. Add a shipping of your choice <br><img width="1567" alt="order" src="https://user-images.githubusercontent.com/48509424/98246234-505df600-1f72-11eb-99e7-3ead1978d874.png">
2.6. Save the order
3. Create a new invoice via Magento 2 administration
3.1. Skip the shipping procedure entirely, just create an invoice
3.2. Leave all settings as is
3.3. Save the invoice <br><img width="1565" alt="invoiced" src="https://user-images.githubusercontent.com/48509424/98247205-a4b5a580-1f73-11eb-9feb-828b6d88226c.png">
4. Check the database table `sales_order_items` selected on the order number (order id gets in `parent_id` column) <br>
(in our case the database values should be displayed in an pdf invoice, which also reflect the wrong qty's)

--> the order_qty has correctly been changed, but the invoice_qty has not been changed correctly and refers to the parent items qty... **see screenshots in the following sections**

### Expected result (*)

1. After creating the invoice the simple items within the bundle should have exactly that qty that has been defined in the bundle option qty
2. After the saved invoice the column `invoiced_qty` of the bundled child items (the simple items of the bundle) whitin `sales_order_items` should also reflect that (actually they should be exactly the same as in  `ordered_qty` in the same table)<br><img width="476" alt="expected" src="https://user-images.githubusercontent.com/48509424/98246133-299fbf80-1f72-11eb-97ad-eca2d2915f6e.png">

### Actual result (*)

1. After creating the invoice the simple items within the bundle actually have the wrong qty - the qty of the parent item (the bundle item) instead. <br><img width="555" alt="actual" src="https://user-images.githubusercontent.com/48509424/98246142-2dcbdd00-1f72-11eb-8673-810a84e1b281.png">

### Additional notes:
this does NOT happen when changing the dynamic price to true!!

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2020-11-06 11:15
The issue is reproducible on the latest 2.4-develop
![Qty invoiced](https://user-images.githubusercontent.com/51680745/98360246-27049f00-2032-11eb-8777-c28e265309e8.png)

**Comment by magento-engcom-team** [comment] 2020-11-06 11:17
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38953` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Hotel** [comment] 2021-01-13 10:17
@magento I am working on this

**Comment by gabrieldagama** [comment] 2021-02-18 12:59
Hi @Emanuel-23. Thank you for your report. 
The issue has been fixed in magento/magento2#31750 by @engcom-Hotel in 2.4-develop branch
Related commit(s):
 - [c9d0dc57a247d444b529d30a35eb52f2a66f1d4e](https://github.com/magento/magento2/commit/c9d0dc57a247d444b529d30a35eb52f2a66f1d4e)
 - [154260866d5e9714cbad62165951fd72d76b0503](https://github.com/magento/magento2/commit/154260866d5e9714cbad62165951fd72d76b0503)
 - [f41c34a6e3276438ddef34a0f0e9e353e3a19598](https://github.com/magento/magento2/commit/f41c34a6e3276438ddef34a0f0e9e353e3a19598)
 - [06e5543973f7e98260448d35d4945b62458224ed](https://github.com/magento/magento2/commit/06e5543973f7e98260448d35d4945b62458224ed)

The fix will be available with the upcoming 2.4.3 release.

**Closed as completed by gabrieldagama** 2021-02-18 12:59 UTC
Labels: Issue: Confirmed, Component: Bundle, Triage: Dev.Experience, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P2, Severity: S2, Progress: done
