### ISSUE TITLE
We don't have as many "product"as you requested - error

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#5111] opened 2016-06-20 13:23 UTC
## Steps to reproduce

In some cases a product is in the shopping bag of a logged in user (or stored in cart for a not logged in user) and the product is bought by someone else. So the cart page shows a message like:

"We don't have as many "product"as you requested"

All ok so far. The problem is that a user can´t ad any other product to the cart at this moment as well!

**Comment by wert2all** [comment] 2016-06-23 10:13
To allow us research the issue, please, provide more concrete steps for reproduce.

Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by andidhouse** [comment] 2016-06-23 10:17
hi there,

running 2.0.7 version in production mode.

Steps to reproduce: 

Login to magento. Ad a product to cart. logout.
Then buy the product (just have one product in stock) with another account. So the product qty is 0.

Then login to the former account and go to another product and try to put it into cart. 

--> Result: You can´t - Just going to the cart page and deleting the product which is not in stock any more resolves the problem.

**Comment by sevos1984** [comment] 2016-09-16 09:38
Not reproduced in 2.0.9. Is it still actual?

**Comment by sevos1984** [comment] 2016-10-03 09:39
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-10-03 09:39 UTC
Labels: bug report, Progress: needs update, Component: Checkout

**Comment by KowsiganAtsayam** [comment] 2020-07-30 14:34
It is still an issue. Please open it.
