### ISSUE TITLE
Backend comment translate 2.3.2

### ISSUE THREAD

**Issue by andy17612** [magento/magento2#24721] opened 2019-09-25 09:56 UTC
### Preconditions (*)

1.magento 2.3.2

### Steps to reproduce (*)

1. Login admin panel
2. Configuration > Web
3. XML Comment

### Expected result (*)

1. "Specify URL or {{base_url}} placeholder.","test123 <--it can translate

### Actual result (*)

1. magento2/app/code/Magento/Backend/etc/adminhtml/system.xml
2.<comment>Specify URL or {{base_url}} placeholder.</comment>
3. It will be showing "Specify URL or placeholder." in the backend , not a "Specify URL or {{base_url}} placeholder."
4. made i18n other language to translate
5. "Specify URL or {{base_url}} placeholder.","test123" <--can't translate, beacuse {{ }} have some bug.

**Comment by andy17612** [comment] 2019-09-26 04:29
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-09-26 04:30
Hi @andy17612. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-09-26 04:30
Hi @andy17612, here is your [Magento instance](https://i-24721-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24721-2-3-develop.instances.magento-community.engineering/admin](https://i-24721-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by andy17612** [comment] 2019-09-26 04:39
<img width="586" alt="2019-09-26" src="https://user-images.githubusercontent.com/32366935/65658471-808e5200-e05a-11e9-9911-84ecb40331e1.png">

@magento-engcom-team 
Confirm can not translate, in the system.xml have {{XX}} but backend have not showing this too

**Comment by magento-engcom-team** [comment] 2019-09-26 20:15
@brunoroeder Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-09-27 02:20
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20523` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hostep** [comment] 2019-10-14 18:42
Since the auto-close-resolved-issues-bot seems to be sleeping today, let me manually close this one.

----

Hi @andy17612. Thank you for your report.
The issue has been fixed in #24832 by @brunoroeder in 2.3-develop branch
Related commit(s):

- 41e73b35294e7f60f855888363dc9918b02027ab
- 745ac409ea121d9d602ebf2d471531c97cf4746a

The fix will be available with the upcoming 2.3.4 release.

**Closed as completed by hostep** 2019-10-14 18:42 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Backend

**Comment by andy17612** [comment] 2019-10-30 04:57
Hi @hostep 

Thanks your helpful.
