### ISSUE TITLE
Update Totals button still missing in the Credit Memo page. 

### ISSUE THREAD

**Issue by pilr** [magento/magento2#26486] opened 2020-01-22 06:53 UTC
https://devdocs.magento.com/guides/v2.3/release-notes/release-notes-2-3-3-commerce.html#orders

From Note: The missing Update Totals button has been added to the Credit Memo page.

### Preconditions (*)

1. Version 2.3.3
2.

### Steps to reproduce (*)

1. install new magento 2.3.3
2.

### Expected result (*)

1. [Screenshots, logs or description]
2. Update Totals button must show in the Credit Memo page. 

### Actual result (*)

1. [Screenshots, logs or description]
2. The missing Update Totals button still in the Credit Memo page.

**Comment by pilr** [comment] 2020-01-22 06:57
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment] 2020-01-22 06:57
Hi @pilr. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment] 2020-01-22 06:58
Hi @pilr, here is your [Magento instance](https://i-26486-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26486-2-3-3.instances.magento-community.engineering/admin_17fc](https://i-26486-2-3-3.instances.magento-community.engineering/admin_17fc)
Login: `247e6e31` Password: `10938716c64b`
Instance will be terminated in up to 3 hours.

**Comment by pilr** [comment] 2020-01-22 07:07
@magento-engcom-team  Update total button still missing in that instance on credit memo page. 
![Screenshot (19)](https://user-images.githubusercontent.com/23712969/72872648-d208ce00-3d28-11ea-813c-ab31d2e69ba4.png)

**Comment by pilr** [comment] 2020-01-23 07:33
Any update on this?

**Comment by danielrussob** [comment] 2020-01-24 10:55
You can follow this issue: https://github.com/magento/magento2/issues/22774

There's a patch in issue

**Comment by engcom-Bravo** [comment] 2020-01-24 11:30
Hello @pilr 

Thank you for your report. 

The issue is not reproducible on Magento 2.4-develop. The **Update Totals** butto has been added. 
![update_totals](https://user-images.githubusercontent.com/51680745/73065107-6733d000-3eab-11ea-8c46-792be0e3ef19.png)
So we have to close it. If you'd like to update the issue, please reopen it.

Thank you for your collaboration

**Closed as completed by engcom-Bravo** 2020-01-24 11:30 UTC
Labels: Issue: Format is valid, Reported on 2.3.3

**Comment by pilr** [comment] 2020-01-24 15:23
> You can follow this issue: #22774
> 
> There's a patch in issue

@danielrussob thanks for the link. will try it.
