### ISSUE TITLE
LoginAsCustomer leaves admin backend unaccessible in multidomain-setup

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#33575] opened 2021-07-24 16:08 UTC
I confirm issue  https://github.com/magento/magento2/issues/32796 : 

### Preconditions (*)
1. Magento 2.4.2
 
### Steps to reproduce (*)
1. Create a multi store, multi domain setup, for example
 
Domain	StoreView
test1.test	de_DE
test2.test	en_US
1. Configure Magento such as the StoreView must not be part of the url
2. Configure the backend such as it is available under one of these domains, eg test2.test/admin
3. Create a customer each for both StoreViews
4. Login to the backend and configure the customers so that both can be accessed with the "LoginAsCustomer" feature
5. From the backend login as customer which is assigned to a StoreView on another domain as the backend (eg test1.test)
6. Close the frontend session
7. Hit Refresh in the browser for the backend

### Expected result (*)
1. the backend reloads and can be used
 
### Actual result (*)
1. the backend hits - depending on the system configuration - either a redirection loop of death or a plain text site without any style or javascript loaded
 
### Workaround
The backend can be made accessible again by deleting a cookie named "store", which contains the StoreView of the customer.

The problem lies in

https://github.com/magento/magento2/blob/f25fc0398899c2bc126bc877d4147aeea377af64/app/code/Magento/LoginAsCustomerAdminUi/Controller/Adminhtml/Login/Login.php#L250

```
        if (!$targetStore->isUseStoreInUrl()) {
            $fromStore = $this->storeManager->getStore();
            $redirectUrl = $this->manageStoreCookie->switch($fromStore, $targetStore, $redirectUrl);
        }
```

The immediate workaround is a patch to change the condition as follows

```
        if (!$targetStore->isUseStoreInUrl() && $targetStore->getBaseUrl() === $this->_url->getBaseUrl()) {
            $fromStore = $this->storeManager->getStore();
            $redirectUrl = $this->manageStoreCookie->switch($fromStore, $targetStore, $redirectUrl);
        }
```

This workaround does it's thing for our use case, but there is no warranty it will work in yours

Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

* [ ]  Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
* [ ]  Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
* [x]  Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
* [ ]  Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
* [ ]  Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Nuranto** [comment] 2021-07-24 16:12
Additional informations, that might help to reproduce : 

```
web/secure/use_in_adminhtml	1
web/secure/use_in_frontend	        1
web/cookie/cookie_httponly          1
web/secure/enable_hsts                0
web/url/use_store                           0
```

If you can't reproduce, tell me I will try to find more helpfull settings. (Maybe you can dump me your core_config_data table so I can compare)

**Comment by engcom-November** [comment] 2021-08-06 08:44
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible with below steps performed:
Setup Multiple Websites and Store views with different domains
My Admin URL: http://magento2.4.local/admin2
Germany Store URL: http://magento2.4.ger.local/
France Store URL: http://magento2.4.france.local/
Default Store URL: http://magento2.4.local/
Admin - Stores - Configuration - Customers - Enabled Login as Customer feature (Please find the configuration in below screenshot)
Stores - Configuration - Customers - Customer Configuration - Account Sharing Options - Share Customer Accounts - Set to "Global"
Note: Issue not reproduced even if Share Customer Accounts is set to "Per Website"
Created Customers for both the Store Views (Germany and France) from front-end with "Allow Remote Shipping Assistance" enabled
Login to admin as admin user and navigate to Customers - All Customers - Edit Germany/France Customer - Click on Login as Customer - Select Germany/France Store view - Login as Customer - No issue
Close all Front-end browsers - Refresh Admin pages - No issue. 
Login as Customer into different store view is also working fine. - No issue
![image](https://user-images.githubusercontent.com/60198231/128482953-2cfd5de2-4e99-44ec-9974-deabbabf8901.png)

![image](https://user-images.githubusercontent.com/60198231/128483022-ac8a6ccd-08b8-4e18-9352-7d43e9ffb522.png)

![image](https://user-images.githubusercontent.com/60198231/128483062-0cbffd77-819e-4539-9b0a-fe7d035d2c32.png)
![image](https://user-images.githubusercontent.com/60198231/128483233-c863f148-d620-468a-8e48-c47fc260d492.png)

![image](https://user-images.githubusercontent.com/60198231/128483259-8cf9fa57-f972-467c-98c2-87cf5d66b370.png)
Note: This issue is not reproduced even if "Store View to Login to" is "set to Auto-Detection"

**Comment by Nuranto** [comment] 2021-08-09 08:41
@magento give me 2.4-develop instance

**Comment by Nuranto** [comment] 2021-08-09 11:49
I did not find a way to reproduce on a fresh install yet. My best guess atm is that there is something to do with filling URL settings via environment variables instead of database. But I already spent too much time on this one.

But I found the cause of the issue. 

If I debug `Magento\Backend\App\Area\FrontNameResolver::isHostBackend()` like this, from a backend call 

```
$backendUrl /* orig */ = $this->scopeConfig->getValue(Store::XML_PATH_UNSECURE_BASE_URL, ScopeInterface::SCOPE_STORE);
            $backendUrlTestStoreAdmin = $this->scopeConfig->getValue(Store::XML_PATH_UNSECURE_BASE_URL, ScopeInterface::SCOPE_STORE, 0);
            var_dump($backendUrl, $backendUrlTestStoreAdmin);
```

I get Second store URL in `$backendUrl`, and Backend domain URL in `$backendUrlTestStoreAdmin`...

So there's an issue in the scope resolver when you don't provide the scopeCode. I don't know where exactly the bug is.

A quick fix could be to specify `0` store id like I did above. It will fix that issue, and it will be better for performances (no more resolving).

A solution, while it is not fixed, if someone else has this issue, is to use admin custom_url and custom path fields.

**Comment by engcom-Hotel** [comment] 2021-08-12 07:39
Hello @Nuranto,

We have tried again to reproduce the issue on the 2.4-develop branch but were unable to do so. And as per your comment, this issue is not reproducible in the 2.4-develop branch. So we are closing this issue for now. 

If you still facing the issue either you can create a new ticket or reopen this.

Thanks

**Closed as completed by engcom-Hotel** 2021-08-12 07:39 UTC
Labels: Issue: needs update

**Comment by maaarghk** [comment] 2022-03-25 12:29
@engcom-Hotel @Nuranto this issue occurred for me, the proposed patch in #32796 seems like it will resolve it.

the problem is probably on the other end - i.e. what is the specificity of the "store" cookie vs MAGE_RUN_CODE server variables vs the URL being parsed to work out what store to view?

is having multi store configured with two stores with same base URL but NO usage of MAGE_RUN_CODE actually a supported configuration - presumably implemented using switch store button on the frontend + store cookie? if it is NOT a supported configuration there is no need to set this cookie because you are redirected to a URL which can be parsed to determine the store

if it IS then the check should be improved to determine whether setting the cookie is necessary as "has the store code in the URL" is not sufficient (ie the other store view is just http://mage24.france.docker for example with no store code in the url, and the admin is http://mage24.docker/ also with no store code, and yet, there is plainly no need to set the cookie). This is why the patch in #32796 resolves the issue for me. but it's not clear whether the web host (Sonassi, so it strikes me as unlikely) are using a bad / unsupported multistore config.

In any case I don't see any harm in accepting @MarcusSchwarz patch because it won't make anything worse for people on either configuration.
