### ISSUE TITLE
Unable to save "Use Default" value for product attribute which has default value

### ISSUE THREAD

**Issue by kimurabanyan** [magento/magento2#35096] opened 2022-02-14 07:39 UTC
**ISSUE:**

Use Default Value checkbox not checked and value not showing for product attribute

**STEPS TO REPLICATE:**
1. Create a product attribute with a backend type of varchar, text or datetime and set default value at "Advanced Attribute Properties > Default Value", and add that attribute to any attribute set.
1. Create a product of attribute set with attribute created in Step1
1. Uncheck the "Use Default Value" checkbox for that attribute in the Store View scope and save
1. Check the "Use Default Value" checkbox for that attribute in the Store View scope and save

**ACTUAL RESULTS:**

Checkbox not checked

**EXPECTED RESULTS:**

The "Use Default Value" checkbox for that attribute is checked in the Store View scope

**Comment by kimurabanyan** [comment] 2022-02-14 07:42
@magento give me 2.4-develop instance

**Comment by kimurabanyan** [comment] 2022-02-14 08:03
Reproduced in 2.4-develop instance

**Step1**
![attribute](https://user-images.githubusercontent.com/2253448/153823096-ae189ef9-ca42-4d44-a9ef-70502532aaf6.png)

result of **Step4**
![save-product](https://user-images.githubusercontent.com/2253448/153823890-25db80f6-a2e8-48e5-a904-4133a076de77.png)

**Comment by engcom-Hotel** [comment] 2022-02-15 13:33
Hi @kimurabanyan,
 

Thank you for reporting the issue.
 
We have verified the issue on Magento 2.4-develop branch however the issue is not reproducible for us.
 
Steps performed:
1:Install a clean version of Magento version 2.4-develop
2:Create a product attribute with a backend type of varchar, text, or DateTime and set default value at "Advanced Attribute Properties > Default Value", and add that attribute to any attribute set.
3:Create a product of attribute set with attribute created in Step 2.
4:.Uncheck the "Use Default" checkbox for that attribute in the Store View scope and save as shown in the screenshot
![Screenshot from 2022-02-14 14-16-01](https://user-images.githubusercontent.com/51681618/154072202-28124b10-487d-4d1e-a12d-560dc413eb26.png)
 
5: Check the "Use Default" checkbox for that attribute in the Store View scope and save
 
![Screenshot from 2022-02-14 14-17-39](https://user-images.githubusercontent.com/51681618/154072257-4d00190e-c079-4030-935e-0a694e43c809.png)
 
**Result**: The "Use Default" checkbox for that attribute is checked in the Store View scope
Please let us know in case we are missing anything with exact reproducible steps, will retry with that scenario.

Thanks

**Comment by kimurabanyan** [comment] 2022-02-16 06:59
https://github.com/magento give me 2.4-develop instance

**Comment by kimurabanyan** [comment] 2022-02-16 07:00
@magento give me 2.4-develop instance

**Comment by kimurabanyan** [comment] 2022-02-16 07:17
Hi @engcom-Hotel 

Thank you for confirming.

I confirmed that it would be reproduced again.
Is your procedure missing the following step?

> set default value at "Advanced Attribute Properties > Default Value",

As you can see in the red frame in the image below, this problem only occurs with attributes that have "Default Value".
Perhaps you checked without setting the "Default Value".

![default-value](https://user-images.githubusercontent.com/2253448/154214634-d450eaa2-2751-41c4-94fd-e72f832ff9bf.png)

Using the above attribute, the problem was reproduced as shown in the image below.

![result](https://user-images.githubusercontent.com/2253448/154214652-052ea882-0911-4504-a95f-6b38f6411afe.png)

Please confirm again.

Thanks.

**Comment by engcom-Delta** [comment] 2022-02-21 14:29
Hi @kimurabanyan,

Thank you for reporting the issue.

We have verified the issue on Magento 2.4-develop branch however the issue is reproducible 

Steps performed:
1:Install a clean version of Magento version 2.4-develop
2:Create a product attribute with a backend type of varchar, text, or DateTime and set default value at "Advanced Attribute Properties > Default Value", and add that attribute to any attribute set.
3:Create a product of attribute set with attribute created in Step 2.
4:.Uncheck the "Use Default" checkbox for that attribute in the Store View scope and save as shown in the screenshot

![350961  ](https://user-images.githubusercontent.com/51681379/154973827-1a27edf2-2f94-4d1a-b1bc-1315b907dcb1.png)

5: Check the "Use Default" checkbox for that attribute in the Store View scope and save
![350962](https://user-images.githubusercontent.com/51681379/154974124-eca27c5a-7dc4-4427-b34b-58d8046f0c60.png)

Result: 
The "Use Default" checkbox for that attribute is not checked as shown in screenshot
![350963](https://user-images.githubusercontent.com/51681379/154974414-406faa71-471a-4da2-a6c0-7a9bd9a03df0.png)
Based on the above observation, confirming the issue.

Thanks!

**Comment by engcom-Hotel** [comment] 2022-02-22 12:16
@engcom-Delta Please check the impact of the checkbox. This will help us in setting the priority.

Thanks

**Comment by engcom-Delta** [comment] 2022-03-07 09:10
Hi @kimurabanyan,
Based on above description confirming the issue.Hi @kimurabanyan,

We have verified the issue on Magento 2.4-develop branch however the issue is reproducible
https://github.com/magento/magento2/issues/35096#issuecomment-1046939040

**Comment by asannikov** [comment] 2023-01-27 10:38
> The cause of this is thought to be the following line. If the attribute has a default value, "false" is not set and the store view record is not deleted.
https://github.com/magento/magento2/blob/2.4.3-p1/app/code/Magento/Catalog/Controller/Adminhtml/Product/Initialization/Helper/AttributeFilter.php#L83

it works on 2.4.5. I compared this file to 2.4.2 where i can reproduce this issue and i see only one difference in this file:
```
// M2.4.5
    private function isAttributeShouldNotBeUpdated(Product $product, array $useDefaults, $attribute, $value): bool
    {
        $considerUseDefaultsAttribute = !isset($useDefaults[$attribute]) || $useDefaults[$attribute] === '1';

        return ($value === '' && $considerUseDefaultsAttribute && ($product->getData($attribute) === null));
    }

// 2.4.2
    private function isAttributeShouldNotBeUpdated(Product $product, array $useDefaults, $attribute, $value): bool
    {
        $considerUseDefaultsAttribute = !isset($useDefaults[$attribute]) || $useDefaults[$attribute] === '1';

        return ($value === '' && $considerUseDefaultsAttribute && !$product->getData($attribute));
    }
```

**Comment by VincentMarmiesse** [comment] 2023-02-01 10:15
I have the same issue on a Magento 2.4.5-p1, it seems to be related to [this line](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Controller/Adminhtml/Product/Initialization/Helper/AttributeFilter.php#L83).

There is a confusion between the attribute's default value, and the checkbox "Use default value" which refers to the "All store views" scope.

**Comment by arnobsh** [comment] 2023-02-28 17:11
The internal team is working on this issue. Thanks

**Closed as completed** 2023-03-02 18:49 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Progress: done, Area: Product

**Comment by dragonfly4** [comment] 2024-01-04 14:32
We are still seeing this issue on 2.4.6-p3

Has anyone found a patch or fix for this please?

**Comment by spraxis** [comment] 2024-01-25 19:29
@dragonfly4 the fix is to create a patch to change this line: `vendor/magento/module-customer-custom-attributes/Plugin/Catalog/UpdateMultiselectAttributes.php:32`, from `== null` to `=== null`
Hope it helps.

**Comment by aaievolisonco** [comment] 2024-04-29 13:52
We are still seeing this issue on 2.4.6-p4

**Comment by engcom-Delta** [comment] 2024-05-02 17:03
We have Verified the issue in Magento 2.4 dev instance and the issue is not reproducible.

Steps to reproduce:

1.Create a product attribute with a backend type of varchar, text or datetime and set default value at "Advanced Attribute 
   Properties > Default Value", and add that attribute to any attribute set.
2.Create a product of attribute set with attribute created in Step1
3.Uncheck the "Use Default Value" checkbox for that attribute in the Store View scope and save
4.Check the "Use Default Value" checkbox for that attribute in the Store View scope and save


Please refer the evidence video attached.


https://github.com/magento/magento2/assets/51681379/3ad6d077-a9f9-4fc5-9bc1-a3a7458bc5a3

**Comment by TheBadong** [comment] 2024-06-05 15:01
Hello @engcom-Delta, could you please check again with a multiselect attribute with a default value? We are still seeing this on 2.4.6-p3.

**Comment by helloeverything** [comment] 2024-06-06 08:15
We are still seeing this issue on 2.4.6-p5. Can we get a quality patch to fix the === in \Magento\CustomerCustomAttributes\Plugin\Catalog\UpdateMultiselectAttributes::afterInitializeFromData ?

**Comment by frostitution** [comment] 2024-06-10 20:09
We are having the same issue except we are NOT using a Default Value for our MultiSelect attribute. 2.4.6-p5

Cannot check "Use Default Value" and have it save correctly. Attribute remains unchecked

**Comment by engcom-Delta** [comment] 2024-06-10 20:15
Hi @helloeverything and @frostitution  ,

We have Verified the issue in Magento 2.4.6-p5 instance and the issue is reproducible.

Steps to reproduce:

1.Create a product attribute with a backend type of varchar, text or datetime and set default value at "Advanced Attribute
Properties > Default Value", and add that attribute to any attribute set.
2.Create a product of attribute set with attribute created in Step1
3.Uncheck the "Use Default Value" checkbox for that attribute in the Store View scope and save
4.Check the "Use Default Value" checkbox for that attribute in the Store View scope and save

ACTUAL RESULTS:

The "Use Default Value" checkbox for that attribute is unchecked in the Store View scope

EXPECTED RESULTS:

The "Use Default Value" checkbox for that attribute is checked in the Store View scope


https://github.com/magento/magento2/assets/51681379/268aad09-2519-4a04-989c-a5f1b8afb39a

**Comment by frostitution** [comment] 2024-06-10 21:33
Other things I noticed:

- Deleting store view specific entries from DB, then navigating to product while attributes are "checked", and simply saving (no changes necessary) while on specific store view cause all multiselect attributes to become wiped/empty on that store view.
- Trying to change this attribute to maybe at least match the default value will not stick, value remains "blank"/empty. This can cause confusion if your store requires this attribute (in our case, ShipperHQ) for functionality reasons
- No "default value" is necessary for the attribute, at least for MultiSelect attributes

@spraxis This fix works, but does this have any possible effects on other things?
