### ISSUE TITLE
Cant have product attributes with long codes

### ISSUE THREAD

**Issue by JohanRoberthsonAteles** [magento/magento2#22958] opened 2019-05-21 09:00 UTC
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

1. Go into Magento Admin and add a new Product Attribute.(Stores / Attributes Product / Add New Attribute)
2. Set the attribute code to "strange_attribute_name_not_working".
3. The attribute could not be saved.  The information to this field is "This is used internally. Make sure you don't use spaces or more than 60 symbols."
Attribute codes could not be longer than 32 chars and include _. Could be longer when not having _ in the code.

### Expected result (*)

1. Attribute should be saved.

### Actual result (*)

1. Get this error message "Attribute code "strange_attribute_name_not_working" is invalid. Please use only letters (a-z or A-Z), numbers (0-9) or underscore(_) in this field, first character should be a letter."

**Comment by AlexWorking** [comment] 2019-05-22 13:44
Hello @JohanRoberthsonAteles. Unfortunately we've been not able to reproduce Your issue on 2.3-develop version. Please look whether we've done everything correctly:
![attributelong](https://user-images.githubusercontent.com/27814011/58179295-922cab00-7cb0-11e9-986f-74e660b89da8.png)
The result is:
![attributelongsuc](https://user-images.githubusercontent.com/27814011/58179318-a1135d80-7cb0-11e9-9a3b-c46448dad845.png)
Would You please try to reproduce it Yourself on a clear magento instance as You are advised to above:
![Advised](https://user-images.githubusercontent.com/27814011/58179389-c7d19400-7cb0-11e9-9670-80810e5efc54.png)
Thank You.

**Comment by JohanRoberthsonAteles** [comment] 2019-05-24 07:11
Is it possible that someone setup a clean test environment. We use latin1_swedish_ci as collation_database, if that could be a problem.

**Comment by AlexWorking** [comment] 2019-05-24 10:09
@magento-engcom-team give me 2.3-develop instance - upcoming 2.3.1

**Comment by magento-engcom-team** [comment] 2019-05-24 10:09
Hi @AlexWorking. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-05-24 10:10
Hi @AlexWorking, here is your [Magento instance](https://i-22958-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22958-2-3-develop.instances.magento-community.engineering/admin](https://i-22958-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AlexWorking** [comment] 2019-05-24 10:14
@magento-engcom-team give me 2.3.1 instance

**Comment by magento-engcom-team** [comment] 2019-05-24 10:14
Hi @AlexWorking. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by magento-engcom-team** [comment] 2019-05-24 10:15
Hi @AlexWorking, here is your [Magento instance](https://i-22958-2-3-1.instances.magento-community.engineering).
Admin access: [https://i-22958-2-3-1.instances.magento-community.engineering/admin](https://i-22958-2-3-1.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AlexWorking** [comment] 2019-05-24 10:27
Hi again @JohanRoberthsonAteles. We retested Your issue on the version You specified and we confirm the issue is present there. But it has been fixed in later releases. You may retest it Yourself by asking 2.3-develop instance or using the one I ordered and got above (its active for three hours). According to the 4-th step (Details expounded) of our issue recheck flow we are supposed to close this issue
![Supposed](https://user-images.githubusercontent.com/27814011/58321685-84e5fc80-7e27-11e9-8af9-9d16fc363903.png)

**Closed as completed by AlexWorking** 2019-05-24 10:27 UTC
Labels: Progress: needs update, Issue: Format is valid
