### ISSUE TITLE
sales rule - incorrect discount_description when there are rules without label

### ISSUE THREAD

**Issue by willtran** [magento/magento2#29082] opened 2020-07-13 05:56 UTC
### Preconditions (*)
1. Magento 2.3.5-p1 and `2.4-develop`

### Steps to reproduce (*)
1. Add shopping cart price rule with Coupon code - with or without label. Example: Rule A - $25 off with coupon SAVE25 
2. Add shopping cart price rules without coupon code - without label. Example: Rule B - $10 off entire site

### Expected result (*)
1. The order discount_description should show correct information. In the above example, it should show "$25 off, $10 off entire site"
2. Order detail in account page, new order email, invoice email ... should show correct discount detail

### Actual result (*)
1. The order's discount_description field will not show Rule without label and incorrectly show applied coupon code instead.
2. In the example, it will show (SAVE25) 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by willtran** [comment] 2020-07-13 06:04
The issue is at \Magento\SalesRule\Model\RulesApplier::addDiscountDescription

```
public function addDiscountDescription($address, $rule)
    {
        $description = $address->getDiscountDescriptionArray();
        $ruleLabel = $rule->getStoreLabel($address->getQuote()->getStore());
        $label = '';
        if ($ruleLabel) {
            $label = $ruleLabel;
        } else {
            if (strlen($address->getCouponCode())) {
                $label = $address->getCouponCode();

                if ($rule->getDescription()) {
                    $label = $rule->getDescription();
                }
            }
        }

        if (strlen($label)) {
            $description[$rule->getId()] = $label;
        }

        $address->setDiscountDescriptionArray($description);

        return $this;
    }
```
When a rule does not have label set for the current store. Magento will then check for description (only in 2.3.5). But if description field is also not set then it will use the addresss coupon code (which are not guaranteed to be from the rule being applied).

Since both `label` and `description` are non-required field when setting up a sales rule. I feel that the code should fall back to use Rule Name instead.

**Comment by magento-engcom-team** [comment] 2020-09-29 12:02
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38055` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Closed as completed** 2020-10-29 16:20 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Issue: Format is valid, Component: SalesRule, Reproduced on 2.4.x, Priority: P2, Progress: done, CD, Reported on 2.3.5-p1

**Comment by zakdma** [comment] 2020-10-29 16:26
Closed as not a bug. You should create label for discount to see it in discount row

**Comment by friendscottn** [comment] 2023-01-17 19:10
For anyone hitting this issue. Here's a mod that will make sure the coupon code displayed would be for the correct rule:

vendor/magento/module-sales-rule/Model/RulesApplier.php::addDiscountDescription()
```php
public function addDiscountDescription($address, $rule)
    {
        $description = $address->getDiscountDescriptionArray();
        $ruleLabel = $rule->getStoreLabel($address->getQuote()->getStore());
        $label = '';
        if ($ruleLabel) {
            $label = $ruleLabel;
        } else {
            if ($address->getCouponCode() !== null && strlen($address->getCouponCode())) {
                // MOD: Only apply coupon code to the description if it is for the specified rule
                $couponCode = $address->getCouponCode();
                $searchCriteriaBuilder = \Magento\Framework\App\ObjectManager::getInstance()
                    ->get(\Magento\Framework\Api\SearchCriteriaBuilder::class)
                    ->addFilter('code', $couponCode);

                /** @var \Magento\SalesRule\Api\Data\CouponSearchResultInterface $couponsCollection */
                $couponsCollection = \Magento\Framework\App\ObjectManager::getInstance()
                    ->get(\Magento\SalesRule\Api\CouponRepositoryInterface::class)
                    ->getList($searchCriteriaBuilder->create());

                $coupons = $couponsCollection->getItems();
                $coupon = null;
                if (! empty($coupons)) {
                    $coupon = $coupons[array_key_first($coupons)];
                }
                if ($coupon && $coupon->getRuleId() === $rule->getRuleId()) {
                    $label = $address->getCouponCode();
                }
                // END MOD

                if ($rule->getDescription()) {
                    $label = $rule->getDescription();
                }
            }
        }
```

**Comment by willtran** [comment] 2023-01-18 00:08
Thanks Scott - I am afraid loading coupon at this step will have detrimental effect to the site performance.
The reason for the bug is that it set the description to the Coupon code of the address $label = $address->getCouponCode(); before falling back to Description. So simple fix I put in was to use a required field instead (rule Name).

I think the correct approach would either be that - or make the Description and Label fields mandatory in the admin FE.

On other note - who are these people closing issues without even taking the time to read :(
