### ISSUE TITLE
Magento 2.3.5 Braintree and Paypal

### ISSUE THREAD

**Issue by smoi** [magento/magento2#28671] opened 2020-06-10 17:18 UTC
Everything was working fine in Magento 2.3.2, after updating to Magento 2.3.5 Paypal through Braintree is not working anymore and is giving errors

### Preconditions (*)
Magento 2.3.5
Magento Braintree 100.3.5 

### Steps to reproduce (*)
Go to checkout

### Expected result (*)
No errors on PayPal

### Actual result (*)
Console showing this error
`Uncaught (in promise) o {name: "BraintreeError", code: "INSTANTIATION_OPTION_REQUIRED", message: "options.authorization is required when instantiating a client.", type: "MERCHANT", details: undefined}code: "INSTANTIATION_OPTION_REQUIRED"details: undefinedmessage: "options.authorization is required when instantiating a client."name: "BraintreeError"type: "MERCHANT"__proto__: Error

Promise.then (async)
 initialize  @ paypal.js:81
 (anonymous) @ wrapper.js:109
`
- [ ] Severity: **S0**

**Comment by engcom-Delta** [comment] 2020-07-13 14:31
Hello @smoi 
Thank you for contribution and collaboration!

This is related with Braintree is third party extension and not included in Magento by default.
Please refer to the [Braintree support](https://help.braintreepayments.com/), for advice or general discussion about this issue.

So I have to close this issue.
Thanks for your report!

**Comment by engcom-Lima** [comment] 2020-07-15 11:31
Hello @smoi 
Could you provide more details for reproduce this issue?
What mode and Payment Action do you use?

Thank you!

**Comment by lingwooc** [comment] 2020-08-04 19:01
I have this issue in developer mode (I have not tried production mode yet). You do not need to attempt to pay. The error is thrown on all pages with a minicart.

**Comment by lingwooc** [comment] 2020-08-05 18:48
and production mode

**Comment by lingwooc** [comment] 2020-08-05 22:58
Oh apparently "Prior to Magento 2.4.0, it was recommended that merchants install and configure the official Braintree payment integration extension from the Magento Marketplace to replace the core integration."

Was it? Where? I'm sick of this, I really am.

**Comment by engcom-Delta** [comment] 2020-08-27 13:18
@smoi, we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Closed as completed by engcom-Delta** 2020-08-27 13:18 UTC
Labels: Issue: Format is valid, Reported on 2.3.2
