### ISSUE TITLE
Wrong Button style on checkout page in Sign In dropdown

### ISSUE THREAD

**Issue by hitesh-wagento** [magento/magento2#19563] opened 2018-12-05 06:50 UTC
### Summary

Wrong Button style on checkout page in Sign In dropdown

### Preconditions
1. Magento 2x - This issue reproduce in all version.

### Steps to reproduce
1. Add any product to Cart.
2. Go to checkout page
3. You can see Sign In text top right side.
4. Click on Sign In text you can see "Sign In" Button.

### Expected result

1. Sign In button should be Blue background color.
![expected](https://user-images.githubusercontent.com/23443991/49495017-a2c6a180-f887-11e8-9a1a-373237d3d231.jpg)

### Actual result

1. Sign In button background color was Grey.
![actual](https://user-images.githubusercontent.com/23443991/49494942-6430e700-f887-11e8-8e23-b2e912f3104f.jpg)

**Comment by magento-engcom-team** [comment] 2018-12-05 06:50
Hi @hitesh-wagento. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@hitesh-wagento do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-12-05 13:43
Hi @TomashKhamlai. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by TomashKhamlai** [comment] 2018-12-05 14:18
Closing this as not an issue.

@hitesh-wagento, thank you for reporting this issue. Please read [this article](https://atlassian.design/server/components/buttons/)

It says:

> Primary button Use this style to call attention to an action on a form, or highlight the strongest call to action on a page. Primary buttons should only appear once per screen (not including the application header or in a modal dialog). Keep in mind that not every screen needs a primary button.

The style of the "Sign In" button is defined via ```class="action action-login secondary"``` and the style of the "Next" button is defined via ```class="button action continue primary"```. Feel free to reopen if you feel that "Sign In" button could be primary one in the context of checkout process.

**Closed as completed** 2018-12-05 14:18 UTC
Labels: Issue: Clear Description, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Area: Design/Frontend
