### ISSUE TITLE
On Admin Unable to Upload Fevicon Icon

### ISSUE THREAD

**Issue by shahankitb997** [magento/magento2#6501] opened 2016-09-06 03:35 UTC
### Preconditions

1.  I'm using Magento 2 CE Version 2.1.0
2.  Go to Admin -> Content -> Design -> Configuration -> Edit "Default Store View" -> HTML Head -> Upload "Favicon Icon".
   It's not allowing .ico extension. It gives "We don't recognize or support this file extension type."
### Expected result

1.  It should allow .ico file to upload
### Solution

To solve this issue. go to \vendor\magento\module-theme\view\adminhtml\ui_component\design_config_form.xml

Line no 70: Previous: <item name="allowedExtensions" xsi:type="string">jpg jpeg gif png svg</item> 
Line no 70: New: <item name="allowedExtensions" xsi:type="string">ico jpg jpeg gif png svg</item>

**Comment by sevos1984** [comment] 2016-09-06 07:50
Duplicate of https://github.com/magento/magento2/issues/5478

**Closed as completed by sevos1984** 2016-09-06 07:50 UTC
Labels: bug report
