### ISSUE TITLE
GraphQL products query returns error for giftcard products when using filter

### ISSUE THREAD

**Issue by thebraziliandeveloper** [magento/magento2#27346] opened 2020-03-18 22:20 UTC
### Preconditions (*)

1. Magento Commerce 2.3.4 w/ sample data.

### Steps to reproduce (*)

1. Generate a customer token through GraphQL mutation **generateCustomerToken**
2. Run the **products** query passing filter following the below query:
```graphql
{
    products(filter: { price: { from: "20" to: "30" }}) {
        total_count
        items {
            name
            sku
            price_range {
                minimum_price {
                    regular_price {
                        value
                        currency
                    }
                }
            }
        }
    }
}
```

### Expected result (*)

1. Expecting a list of products with filters applied.

### Actual result (*)
1. GraphQL response error:

```json
{
    "errors": [
        {
            "debugMessage": "Argument 2 passed to Magento\\CatalogGraphQl\\Model\\Resolver\\Product\\PriceRange::formatPrice() must be of the type float, bool given, called in /var/www/html/vendor/magento/module-catalog-graph-ql/Model/Resolver/Product/PriceRange.php on line 89",
            "message": "Internal server error",
            "extensions": {
                "category": "internal"
            },
            "locations": [
                {
                    "line": 7,
                    "column": 13
                }
            ],
            "path": [
                "products",
                "items",
                3,
                "price_range"
            ]
        },
        {
            "debugMessage": "Argument 2 passed to Magento\\CatalogGraphQl\\Model\\Resolver\\Product\\PriceRange::formatPrice() must be of the type float, bool given, called in /var/www/html/vendor/magento/module-catalog-graph-ql/Model/Resolver/Product/PriceRange.php on line 89",
            "message": "Internal server error",
            "extensions": {
                "category": "internal"
            },
            "locations": [
                {
                    "line": 7,
                    "column": 13
                }
            ],
            "path": [
                "products",
                "items",
                4,
                "price_range"
            ]
        }
    ],
    "data": {
        "products": {
            "total_count": 5,
            "items": [
                {
                    "name": "Savvy Shoulder Tote",
                    "sku": "24-WB05",
                    "price_range": {
                        "minimum_price": {
                            "regular_price": {
                                "value": 32,
                                "currency": "BRL"
                            }
                        }
                    }
                },
                {
                    "name": "Harmony Lumaflex&trade; Strength Band Kit ",
                    "sku": "24-UG03",
                    "price_range": {
                        "minimum_price": {
                            "regular_price": {
                                "value": 22,
                                "currency": "BRL"
                            }
                        }
                    }
                },
                {
                    "name": "Yoga Adventure",
                    "sku": "240-LV06",
                    "price_range": {
                        "minimum_price": {
                            "regular_price": {
                                "value": 22,
                                "currency": "BRL"
                            }
                        }
                    }
                },
                null,
                null
            ]
        }
    }
}
```

### Additional Info (*)

Running xDebug i found that the error occour when _getMinimumProductPrice_ method receives a product with type_id = giftcard:

![image](https://user-images.githubusercontent.com/34348632/77012755-5eacc280-694d-11ea-975a-c8d1d1a3ffcd.png)

**Comment by engcom-Bravo** [comment] 2020-03-19 13:39
Hello @alnmaiafernandes 

Thank you for your report

We have rechecked this issue on "clean" Magento 2.4-develop, both Comunity and Enterprise editions, with Sample Data.
The issue is not reproducible. The ```product``` query returns the list of products matching the search filter
![27346_products query](https://user-images.githubusercontent.com/51680745/77073236-a0924300-69f7-11ea-9779-6b8e906e8dc1.png)

Can you please confirm that you are experiencing the same issue on Magento 2.4-develop?

Thank you in advance

**Comment by szreka** [comment] 2020-04-23 15:38
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-23 15:39
Hi @szreka. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-23 15:40
Hi @szreka, here is your [Magento instance](https://i-27346-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27346-2-4-develop.instances.magento-community.engineering/admin_e9da](https://i-27346-2-4-develop.instances.magento-community.engineering/admin_e9da)
Login: `e777863a` Password: `a038f396c4aa`
Instance will be terminated in up to 3 hours.

**Comment by szreka** [comment] 2020-04-23 15:53
I realised gift cards is an enterprise feature so I can't test it on the instance requested, however we are facing the same issue on 2.3.4 when the gift card amount is set to be open.

**Comment by Aniket10Nov** [comment] 2020-04-25 06:23
i am working on this.

**Comment by pronto2000** [comment] 2020-11-12 12:57
Checked it on Magento Enterprise 2.3.6 (latest 2.3 at the moment) and was unable to reproduce it there:

![image](https://user-images.githubusercontent.com/5182866/98942912-6716c680-24f7-11eb-8381-1e4d24291710.png)

**Comment by shikhamis11** [comment] 2020-12-09 08:28
@magento give me 2.3.4 instance with edition ee

**Comment by mauragcyrus** [comment] 2020-12-15 15:36
@alnmaiafernandes Hi there, is this still repro at 2.4.1?

**Comment by shikhamis11** [comment] 2021-01-05 15:42
@magento give me 2.3.6 instance with edition ee

**Comment by shikhamis11** [comment] 2021-01-06 11:23
hi @alnmaiafernandes 
I am not able to reproduce this issue on latest magento instances 2.3.6 and 2.4.1 with the steps you mentioned so closing the issue.
Feel free to reopen if you are still able to reproduce the issue on latest magento instances also please update the issue description if it requires additional steps to reproduce this.

**Closed as completed by shikhamis11** 2021-01-06 11:23 UTC
Labels: Issue: Format is valid, Project: GraphQL, PAP, Progress: done
