### ISSUE TITLE
Installation is incomplete.  Check the console log for errors before trying again. on line 17 after 6%

### ISSUE THREAD

**Issue by tinkumadspark** [magento/magento2#3817] opened 2016-03-17 06:06 UTC
Hello,
I am trying to update magento from 1.8 to 2.0. For that I have downloaded magento 2.0 and put the files in my directory and extracted. But when I opened the URL of my website, it shows that you need to update your php first. I updated my php too.
Now it is getting stuck at line 17th after 6% and showing below error:
Installation is incomplete. 
Check the console log for errors before trying again.

I am also attaching screenshot for my error.
Please help me with this issue.

Regards
Tinku Kumar
M: +91-8010096304

**Comment by mazhalai** [comment] 2016-03-17 14:48
@tinkumadspark what is your max_execution_time?

**Comment by tinkumadspark** [comment] 2016-03-17 16:31
Thank you for reply.
I am sorry I could not get you. I have put zip folder for magento 2.0 in my directory folder and extracted. Then I merged some folders with Magento 2.0 folders, I found steps from google was as follows: 
![for upgrading magento version](https://cloud.githubusercontent.com/assets/17401306/13853172/90a179c2-ec8b-11e5-8fa5-fb995a9409d6.JPG)
Now, I am getting one error. Please follow the below link:
http://rugsandbeyond.com/dev/
This is what the site at current condition.
Please have a look. 
Thanks & Regards
Tinku

**Comment by mazhalai** [comment] 2016-03-23 14:34
@tinkumadspark Please follow the [official migration guide](http://devdocs.magento.com/guides/v2.0/migration/bk-migration-guide.html)

Closing since this is not a bug.

**Closed as completed by mazhalai** 2016-03-23 14:34 UTC
Labels: Progress: needs update
