### ISSUE TITLE
Magento2 SOAP API 

### ISSUE THREAD

**Issue by VLCSolutions** [magento/magento2#2002] opened 2015-10-02 10:47 UTC
How to create a SOAP API in magento2

**Comment by okorshenko** [comment] 2015-10-02 12:43
Hi @VLCSolutions , please look at [API Documentaion](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/service-contracts/service-to-web-service.html). If you have additional questions, please, let us know

**Comment by VLCSolutions** [comment] 2015-10-02 12:45
If possible could you please elaborate with a example please

**Comment by okorshenko** [comment] 2015-10-02 12:55
@VLCSolutions, to create new SOAP API you need to declare interface (for example: https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Api/GroupRepositoryInterface.php) and configure it in webapi.xml (for example: https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/etc/webapi.xml#L12). This logic will be available in REST and SOAP API. For more details please refer [Sample WebAPI](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/service-contracts/service-to-web-service.html#sample-webapi)

**Comment by VLCSolutions** [comment] 2015-10-02 13:01
@okorshenko thanks for reply, where we define the elements or attributes for the request and response elements like how we defined in wsdl.xml file in magento1.
Please bear me...

**Comment by okorshenko** [comment] 2015-10-02 14:17
@VLCSolutions , currently you don't need to configure attribute separately. Your interface return object (let's say, customer group https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Api/GroupRepositoryInterface.php#L32).  \Magento\Customer\Api\Data\GroupInterface has declared getter that will be transformed to response attributes. (https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Api/Data/GroupInterface.php#L20-L23)

**Comment by VLCSolutions** [comment] 2015-10-05 11:58
What is difference between https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/etc/webapi.xml#L113toL118 and https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/etc/webapi.xml#L140toL148

**Comment by choukalos** [comment] 2015-10-05 17:44
the /me means that you only get your information ( authorized with a customer token ) - you can't use that web api to get any other customer from the system like you can with the first web api ( which requires an admin token ).

**Comment by VLCSolutions** [comment] 2015-10-06 09:40
@okorshenko , @choukalos : how to create multiple customers at a time, for example \Magento\Customer\Api\Data\CustomerRepository save method accepts only one customer details at a time to save, but i want to create multiple customers on one API request.

**Comment by choukalos** [comment] 2015-10-06 13:43
We only support single entity APIs; there's no plan to support bulk API calls in our framework.  

For higher volume integrations we'll be enhancing scheduled FTP's to be more like a feeds system where you can configure  scheduled FTP/SFTP transfer via XML as part of your extension.  Likely this will be in the later half of 2016.  Thinking behind that is it'll allow transfer for very large catalogs, inventory updates, etc in a more performant manner than supporting bulk API calls.  This feature will be in enterprise.

**Comment by VLCSolutions** [comment] 2015-10-06 13:54
@choukalos , thanks for reply. Please help me on getting XML request structure for SOAP API. 
Like CustomerRequest able to request from SoapUI.

**Comment by VLCSolutions** [comment] 2015-10-07 07:33
@okorshenko , @choukalos Please help me on getting WSDL XML structure for any API request in magento2. In magento1 i could able to get the WSDL XML structure in SOAPUI or storm by giving SOAP URL, But in magento2 i'm not able to get WSDL XML structure, please help me on this.

**Comment by alankent** [comment] 2015-10-07 09:57
Are you saying fetching WSDL does not work, or you do not know how to do it? Have you had a look at http://devdocs.magento.com/guides/v2.0/soap/bk-soap.html ?  That lists lots of end points for fetching WSDL. If it is not working, could you provide more details on what error messages etc you are getting? Thanks!

**Comment by VLCSolutions** [comment] 2015-10-07 10:03
@alankent I want to get XML request for customerrepository API, 
For this i have used http://192.168.0.183/NewMagento2/soap?wsdl&services=customerCustomerRepositoryV1  in SOAPUI tool and i'm getting error 

http://192.168.0.183/NewMagento2/soap?wsdl&services=customerCustomerRepositoryV1
loading http://192.168.0.183/NewMagento2/soap?wsdl&services=customerCustomerRepositoryV1
Acquiring the wsdl...
Resolving the wsdlendpoint...
Generating code...
Code generation failed.
Microsoft.FSharp.Core.FailureException: Assembly not yet created.
   at Storm.Types.WebSvcManagerOps.clo@90.CreateWebServiceModel()
   at <StartupCode$Storm>.$Type.bgworker.run@51@57_2.Invoke(DoWorkEventArgs dArgs)
   at <StartupCode$Storm>.$Type.bgworker.run@51@57_1.Invoke(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by choukalos** [comment] 2015-10-08 14:33
Internally tracking - MAGETWO-43797

**Comment by arkadiych** [comment] 2015-10-23 15:57
@VLCSolutions, I'm trying to reproduce your error. Could you provide more details about the environment, where you ran your XML request: the version of SOAPUI, what kind of tool do you use to generate code, the version of the tool, language of generated code, protocol?  Was you able to get results using the approach described in http://www.soapui.org/soap-and-wsdl/getting-started.html with http://192.168.0.183/NewMagento2/soap?wsdl&services=customerCustomerRepositoryV1 ?

**Comment by VLCSolutions** [comment] 2015-10-26 13:09
@arkadiych Now i'm able to get request and response from SOAPUI tool, but when i try to use the same http://192.168.0.183/NewMagento2/soap?wsdl&services=customerCustomerRepositoryV1 in [storm](https://storm.codeplex.com/) tool still its giving error. 
Note: In [Storm](https://storm.codeplex.com/) magento1 XML Request generated successfully.

**Comment by arkadiych** [comment] 2015-11-04 13:49
@VLCSolutions,  looks like Storm supports SOAP1.1, but not SOAP1.2 for code generation. Magento2 SOAP Web Service supports SOAP1.2

**Comment by davidalger** [comment] 2015-11-10 20:30
Closing issue due to the issue being related to SOAP version incompatibly. Feel free to reopen this if there is a bug in Magento 2, but please provide more details on reproducing the precise issue.

The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Closed by davidalger** 2015-11-10 20:30 UTC
Labels: bug, forum, PS
