### ISSUE TITLE
Magento 2 custom attribute filter not working graphql products query in product attribute custom source

### ISSUE THREAD

**Issue by prabhakaran777** [magento/magento2#31361] opened 2020-12-19 06:45 UTC
### Preconditions (*)

1.Magento 2.3.5-p2 had issue on **product custom attribute Filter**  with custom source (Setup/Patch/CustomSelectOption)

2.But it's  _Working in Product Collection_ 

### Steps to reproduce (*)

1.Magento 2.3.5-p2

2.Create custom product attribute via setup patch (with select option) - also custom source model file

```
class ProductCustomType extends AbstractSource
{
    public function getAllOptions()
    {
        if ($this->_options === null) {
            $this->_options = [

                ['value' => '', 'label' => __('-- Select an Option --')],
                ['value' => 'new', 'label' => __('New')],
                ['value' => 'old', 'label' => __('Old')],
               
            ];
        }
        return $this->_options;
    }
}
```

3.Assign product type to any of the product

4.Graphql

Req:

```
{
  products(filter:{
    product_custom_type:{
      eq:"new"
     }
  
  }){
    total_count
    items{
      id
     sku
    product_custom_type
    }
  }
}
```

Response:

```
{
  "data": {
    "products": {
      "total_count": 0,
      "items": []
    }
  }
}

```
### Expected result (*)

1. Get Products in Products query Response.

### Actual result (*)

1.
![Screenshot from 2020-12-19 12-13-33](https://user-images.githubusercontent.com/49685489/102683016-bd141380-41f3-11eb-81ee-dcd705de73b4.png)

Response:

```
{
  "data": {
    "products": {
      "total_count": 0,
      "items": []
    }
  }
}

```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by VZeroCool** [comment] 2020-12-21 05:38
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-11-04 10:22
Hello @prabhakaran777,

We have tried to reproduce this issue in the Magento 2.4-develop instance and the issue is not reproducible for us. We have made a custom module in order to reproduce it. We are attaching the same for reference:

[Magz.zip](https://github.com/magento/magento2/files/9937258/Magz.zip)

We are getting the expected response from the query:

<img width="930" alt="image" src="https://user-images.githubusercontent.com/51681618/199950130-ea848841-68af-4f1f-a919-c33c7c144d72.png">

Let us know in case we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2022-12-12 05:22
Dear @prabhakaran777,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-12-12 05:22 UTC
Labels: Issue:  Cannot Reproduce, Triage: Dev.Experience, Priority: P1, Project: GraphQL, PAP, Progress: done, Issue: ready for confirmation, Issue: needs update
