### ISSUE TITLE
Missing Validaiton Class while open_basedir in effect

### ISSUE THREAD

**Issue by KM-HM** [magento/magento2#28424] opened 2020-05-29 12:12 UTC
Magento 2.4 throws an error about a missing validation class when saving general contact information email address which causes the new value to be discarded.

### Preconditions (*)

1. PHP 7.4
2. Set the "open_basedir" option for PHP via either php.ini or FPM pool configuration. Value should be the absolute path to magento 2 root directory. Make sure sys_temp_dir, upload_tmp_dir are set to be within the open_basedir path.
3. Magento 2.4 installed via composer 

### Steps to reproduce (*)

1. Login to Admin Area
2. Navigate to "Stores --> Configuration --> General -> Store Email Addresses"
3. Enter a valid email address into the field "General Contact" -> "Sender Email" something like "info@anywhere.com"
4. Use the button "Save Config" to save configuration

### Expected result (*)

1. The new, valid, value of the field "General Contact" -> "Sender Email" is saved as entered

### Actual result (*)

1.  An error message is shown: Something went wrong while saving this configuration: Validate class not found from basename 'Magento\Framework\Validator\EmailAddress'
2. New Value is not saved 

As a workaround it is possible to include Zend 1 Framework via  PHP directly. 
Example workaround using PHP FPM pool config:
php_admin_value[include_path] = ".:/[PATH_TO_MAGENTO_ROOT_DIR]/vendor/magento/zendframework1/library"

I suspect this might have something todo with the recent change of using Laminas instead of Zend Framework. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sambath1293** [comment] 2020-05-29 12:20
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-29 12:20
Hi @sambath1293. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-05-29 12:22
Hi @sambath1293, here is your [Magento instance](https://i-28424-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28424-2-4-develop.instances.magento-community.engineering/admin_7cba](https://i-28424-2-4-develop.instances.magento-community.engineering/admin_7cba)
Login: `57007d55` Password: `391e3a563b8e`
Instance will be terminated in up to 3 hours.

**Comment by sambath1293** [comment] 2020-05-29 12:44
@kemexyz - I was tried to recreate this issue in Magento 2.4 develop as advised by Magento and I couldn't reproduce it.

See the reference screenshot below:
![IssueNotOccoursIn2 4develop](https://user-images.githubusercontent.com/60879885/83260933-360c3900-a1d8-11ea-8eda-753a8d23adb7.png)

Now I am going to test this again in Magento 2.3.5-p1.

**Comment by sambath1293** [comment] 2020-05-29 12:54
I confirm that issue is not reproducible on both the latest 2.4-develop and Magento 2.3.5-p1.
See the below screenshot:
![issue2](https://user-images.githubusercontent.com/60879885/83261812-951e7d80-a1d9-11ea-9798-ba8377f5cca8.png)


If you'd like to update the issue, please reopen it.

**Comment by kemexyz** [comment] 2020-05-29 13:38
@magento give me 2.3 instance

**Comment by kemexyz** [comment] 2020-08-03 14:45
This issues only exists while the "open_basedir" option is set for PHP.  This might not be the case for test instances given on github.

**Comment by kemexyz** [comment] 2020-08-05 15:00
@magento-engcom-team please reconfirm this issues see last comment

**Comment by sdzhepa** [comment] 2020-09-22 20:28
Hello @kemexyz 

I will reopen this issue for re-confirmation
Please update the description and steps it could help a lot for confirmation on the `2.4-develop` and future processing.
Also, please take into account in this repository we can process/confirm/fix/deliver only issues that can be reproduced on the latest `2.4-develop`

**Comment by lazyguru** [comment] 2020-09-22 22:32
I spent the last couple of hours tracing this and want to offer up my findings to help with triage here. I found a quick fix in this line:https://github.com/magento/zf1/blob/master/library/Zend/Validate.php#L200. When I remove the `false` so that the line is just `if (!class_exists($className)) {` the specific condition I was running into went away (before you rush to make this change, please read this WHOLE post).  From what I can see that method is attempting to resolve a PSR4 class via PSR0 methods and running into problems when open_base is set. I added logging to the Zend_Validate class to trace things and found that the "cleverness" of line 240 is hiding the real error:

```
is_readable(): open_basedir restriction in effect. File(/opt/remi/php72/root/usr/share/pear/Zend/Validate/Magento\Framework\Validator\EmailAddress.php) is not within the allowed path(s): (/var/www/vhosts:/opt/remi/php72/root/usr/share/pear:/opt/remi/php72/root/usr/share/php:/tmp:/usr/bin) in /var/www/vhosts/magento/ee23/php72/vendor/magento/zendframework1/library/Zend/Loader.php on line 186
```
(NOTE: /opt/remi/php72/root/usr/share/pear/Zend does not exist on my system. /opt/remi/php72/root/usr/share/pear is in my open_base AND in include_path)

If we look closer at (`Zend_Validate::is()`) we can see that when `class_exists` returns false, the method behaves in a very un-friendly way to the use of non Zend classes (line 203 prepends the Zend_Validate namespace to the class). Magento's usage of `\Zend_Validate::is($email, \Magento\Framework\Validator\EmailAddress::class)` is running into problems when open_base is enabled because of this.

Based on the limited investigation I've done I can see 3 possible solutions:
1) Remove the boolean (since Magento controls that repo anyway, it *can* do that without asking anyone's permission). The downside is: what impact does this have? What *might* break by doing this? (I am not sure what the ramifications of removing the boolean from class_exists are aside from the autoloader being used to find classes)
2) Replace all calls to `Zend_Validate::is()` that try to use a Magento class with either the native Zend class (there already is `Zend_Validate_EmailAddress`). This is obviously the less desirable of the options as I am guessing that the usage of this class was part of a phased approach to replace the usage of ZF1 classes in M2.
3) Replace all calls to `Zend_Validate::is()` that try to use a Magento class with some other solution. This seems like the "safest" option (and likely already part of a long term goal). However, it is also probably the longest solution to implement (I did a basic search and found over 20 references before I stopped counting)

**Comment by atrandafir** [comment] 2021-01-20 16:31
> I spent the last couple of hours tracing this and want to offer up my findings to help with triage here. I found a quick fix in this line:https://github.com/magento/zf1/blob/master/library/Zend/Validate.php#L200. When I remove the `false` so that the line is just `if (!class_exists($className)) {` the specific condition I was running into went away (**_before you rush to make this change, please read this WHOLE post_**).From what I can see that method is attempting to resolve a PSR4 class via PSR0 methods and running into problems when open_base is set. I added logging to the Zend_Validate class to trace things and found that the "cleverness" of line 240 is hiding a real error:
> 
> ```
> is_readable(): open_basedir restriction in effect. File(/opt/remi/php72/root/usr/share/pear/Zend/Validate/Magento\Framework\Validator\EmailAddress.php) is not within the allowed path(s): (/var/www/vhosts:/opt/remi/php72/root/usr/share/pear:/opt/remi/php72/root/usr/share/php:/tmp:/usr/bin) in /var/www/vhosts/magento/ee23/php72/vendor/magento/zendframework1/library/Zend/Loader.php on line 186
> ```
> 
> (NOTE: /opt/remi/php72/root/usr/share/pear/Zend does not exist on my system. /opt/remi/php72/root/usr/share/pear is in my open_base AND in include_path)
> 
> If we look closer at (`Zend_Validate::is()`) we can see that when `class_exists` returns false, the method behaves in a very un-friendly way to the use of non Zend classes (line 203 prepends the Zend_Validate namespace to the class). Magento's usage of `\Zend_Validate::is($email, \Magento\Framework\Validator\EmailAddress::class)` is running into problems when open_base is enabled because of this.
> 
> Based on the limited investigation I've done I can see 3 possible solutions:
> 
> 1. Remove the boolean (since Magento controls that repo anyway, it _can_ do that without asking anyone's permission). The downside is: what impact does this have? What _might_ break by doing this? (I am not sure what the ramifications of removing the boolean from class_exists are aside from the autoloader being used to find classes)
> 2. Replace all calls to `Zend_Validate::is()` that try to use a Magento class with either the native Zend class (there already is `Zend_Validate_EmailAddress`). This is obviously the less desirable of the options as I am guessing that the usage of this class was part of a phased approach to replace the usage of ZF1 classes in M2.
> 3. Replace all calls to `Zend_Validate::is()` that try to use a Magento class with some other solution. This seems like the "safest" option (and likely already part of a long term goal). However, it is also probably the longest solution to implement (I did a basic search and found over 20 references before I stopped counting)

I have run into the same issue, I have migrated from a Plesk VPS to a Shared Plesk hosting so I don't know if I did something wrong.

Anyways, I have put `vendor/magento/zendframework1/library` to both `include_path` and `open_basedir` and it didn't work for some reason.

What I ended up doing is editing the `vendor/magento/zendframework1/library/Zend/Validate.php` file:  

On the `is` method..

```
public static function is($value, $classBaseName, array $args = array(), $namespaces = array())
    {
        $namespaces = array_merge((array) $namespaces, self::$_defaultNamespaces, array('Zend_Validate'));
        $className  = ucfirst($classBaseName);
        try {

                if ($className=='Magento\Framework\Validator\EmailAddress') {
                        class_exists($className, true);
                }
```

I have inserted this block, with `class_exists($className, true);`, note the `true` parameter that tells PHP to autoload the class.  

```
if ($className=='Magento\Framework\Validator\EmailAddress') {
		class_exists($className, true);
}
```
Now it worked and problem went away.

I don't know if I'll run into more problems, we will see.

And by the way, I have searched for the use of `Zend_Validate::is()` method, and the only class that uses a full path, is `Magento\Framework\Validator\EmailAddress`, the other ones use just the basename.

![image](https://user-images.githubusercontent.com/3097251/105205104-8b250280-5b4d-11eb-9d1e-9c27733ed22d.png)

**Comment by atrandafir** [comment] 2021-01-20 19:53
Update:  

I have ended up also commenting out the condition:  

`if (Zend_Loader::isReadable($file)) {`

Because looks like that returns false.

But the next line `Zend_Loader::loadClass($class);` does work, if we don't do the check.

**Comment by dverkade** [comment] 2021-04-18 20:16
Posting a comment. Issues should not be automatically closed.

**Comment by engcom-Lima** [comment] 2021-06-07 12:15
Hi @kemexyz 

I debug your issue and i followed all the steps, Unfortunately can't reproduce an issue.

I tested your issue on Magento ver. 2.4.2. Please find the attachment.
<img width="1440" alt="Screenshot 2021-06-07 at 5 35 04 PM" src="https://user-images.githubusercontent.com/60198022/121014597-c7cd5f80-c7b7-11eb-87f2-0e9921d0ee7b.png">

Please provide the reproducible steps and details.

**Comment by engcom-Lima** [comment] 2021-06-16 13:59
Hi @kemexyz, Issue can't reproduce hence closing this ticket.

Please feel free to raise the new ticket or reopen the ticket if you have any issue

**Closed as completed by engcom-Lima** 2021-06-16 13:59 UTC
Labels: Issue:  Cannot Reproduce, Triage: Dev.Experience, Issue: needs update, Reported on 2.4.0
