### ISSUE TITLE
Order by SKU products not showing in Minicart drop down

### ISSUE THREAD

**Issue by Tjmstudios** [magento/magento2#5436] opened 2016-07-04 07:17 UTC
## Steps to reproduce
1. Fresh install Magento 2.1.0. (sample products)
2. Login on front-end.
3. Go to "Order by SKU"
4. Upload valid CSV with multiple products and qty's
   ![image](https://cloud.githubusercontent.com/assets/11372070/16553169/056644a8-420a-11e6-9237-4de575f94dc4.png)
5. Select "add to cart"
6. Select minicart to show drop down
## Expected result
1. The same products in cart are displayed in minicart
## Actual result
1.  ![screen shot 2016-07-04 at 5 15 30 pm](https://cloud.githubusercontent.com/assets/11372070/16553278/f63dfe8e-420a-11e6-8307-5494e57147a8.png)
   All items in cart are not displayed in minicart =(

**Comment by antboiko** [comment] 2016-07-04 13:23
Hi @Tjmstudios , you data in .csv file should be comma separated, i.e.:
sku,qty
SKU-1,5
SKU-2,7

Please try this way and close this issue if it helps.

Thanks,
Anton.

**Comment by Tjmstudios** [comment] 2016-07-05 06:51
@antboiko my file is in the correct format see https://www.dropbox.com/s/kpg6eumy7hse7do/productsm2.csv?dl=0
And I still see this issue.

**Comment by antboiko** [comment] 2016-07-05 07:15
@Tjmstudios the file is not reachable for me. Was that screenshot with sku/qty list taken from that file you shared?

Thanks,
Anton.

**Comment by Tjmstudios** [comment] 2016-07-05 08:14
@antboiko It was just a proof that the file I was using has the correct structure.

**Comment by antboiko** [comment] 2016-07-05 09:39
@Tjmstudios the structure should be like this:
![sku-qty](https://cloud.githubusercontent.com/assets/15442705/16580500/7bf3307e-42ad-11e6-8a63-55c7bbb193ac.png)

**Comment by Tjmstudios** [comment] 2016-07-05 09:56
@antboiko This issues has nothing to do with the CSV structure. 
If you add the product using the form provided by Magento in /customer_order/sku/ then you will still replicate my original issue
**Upload via form**
![upload by sku](https://cloud.githubusercontent.com/assets/11372070/16580925/353a6566-42ea-11e6-9dce-98f865bd770a.PNG)
**= Same issue**
![image](https://cloud.githubusercontent.com/assets/11372070/16580961/5c1efade-42ea-11e6-8d10-ded2136aa160.png)

**Comment by antboiko** [comment] 2016-07-05 10:55
@Tjmstudios thanks for the clarification, I could reproduce this issue with Sample Data products, however, it works correctly with products which I created myself. Internal ticket MAGETWO-55059 was created to investigate this issue.

Thanks,
Anton.

**Comment by magento-engcom-team** [comment] 2017-10-13 08:43
@Tjmstudios , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Closed as completed** 2017-10-13 08:44 UTC
Labels: Issue: Ready for Work, bug report, Component: Checkout, Issue: Format is not valid
