### ISSUE TITLE
inconsistent VAT calculation

### ISSUE THREAD

**Issue by YiffyToys** [magento/magento2#24668] opened 2019-09-20 09:57 UTC
Customer ordered 3 products. Each product costs 250 eur and has 19% sales tax.
This is what the order page shows:

| Product | Item Status | Original Price | Price | Qty | Subtotal | Tax Amount | Tax Percent | Discount Amount | Row Total |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| NAME1 | Ordered | €250.00 | €250.00 | Ordered 1 | €250.00 | €39.92 | 19% | €0.00 | €250.00 |
| NAME2 | Ordered | €250.00 | €250.00 | Ordered 1 | €250.00 | €39.91 | 19% | €0.00 | €250.00 |
| NAME3 | Ordered | €250.00 | €250.00 | Ordered 1 | €250.00 | €39.92 | 19% | €0.00 | €250.00 |

Note that 1 of the products shows €39.91 VAT and the others €39.92 .

The final VAT amount looks correct but this should still not happen.

(I hope nobody is accidentally using float or double for currency values anywhere. ;) )

**Comment by FreekVandeursen** [comment] 2019-09-20 10:16
Based on the numbers I assume you have set your tax settings to:
- Prices include tax
- Calculate tax on order total

So Magento will calculate the total tax amount, which is 750 / 1.19 * 1.19 = 119,74789916

Then Magento will try to divide this tax amount over the order items, for visual purposes. So the tax per item will be 119,74789916 / 3 = 39,915966387

So what would you expect in this case? To show a tax amount of 39.91 or 39.92 for each row would mean that the totals do not match the sum of all items.

I'd say what you are currently seeing is expected behaviour, not a bug.

**Comment by YiffyToys** [comment] 2019-09-20 11:04
Good point.   I did not think about that.
I guess I shoul disable showing VAT or individual items completely (somewhere).

**Comment by engcom-Bravo** [comment] 2019-09-20 14:42
Hello @YiffyToys. Thanks for applying. @FreekVandeursen is right. If You want to denote tax for each single item in a document You may (and more often will) face the problem caused by rounding. The same thing happens when applying discounts to the price or in any other situations when the price is recalculated in such a manner that it is divided by some number or multiplied by some fractional number like in Your case (1.19). And it's not a problem with Magento - it's a pure Math. Though @FreekVandeursen has already described the essence of the problem let me give You one more simple example, with less complicated numbers and calculations, demonstrating what may happen and why it may happen when rounding is involved. 
Suppose we have two products "A" and "B" with the same price of lets say 10.25 eur. The customer ordered per one item from both. So the order would look like as follows

Product | Qty | Price | Sum
-- | -- | -- | --
A | 1 | 10.25 | 10.25
B | 1 | 10.25 | 10.25
  |   |   |  
Order Total |   |   | 20.5

Now for simplicity sake assume the customer applies a coupon code with a discount of 50% for the whole order amount and You want to reflect that in new discounted prices in order. So the orders total is supposed to be 10.25 and the discounted price of each product - 5.125 eur. But You need to show only cents in the price so You must round it ether to 5.12 eur or what is generally accepted to 5.13 eur. So You will be going to show not the true (exact) prices for the products. In such a case order total after recalculating is also supposed to be not true. Of course In such cases order totals may still come out correct after having been recalculated. But that happens for the same reason for which the still watch shows correct time twice a day. In our case we don't have a luck with that: 5.12 + 5.12 = 10.24 and 5.13 + 5.13 = 10.26 - neither of these totals are equal to 10.25 as they are supposed to be. Of course You may make Your order look like 

Product | Qty | Price | Sum
-- | -- | -- | --
A | 1 | 5.12 | 5.12
B | 1 | 5.12 | 5.12
  |   |   |  
Order Total |   |   | 10.25

Or like

Product | Qty | Price | Sum
-- | -- | -- | --
A | 1 | 5.13 | 5.13
B | 1 | 5.13 | 5.13
  |   |   |  
Order Total |   |   | 10.25

where summing up the positions do not bring the result equal to the order's total. Also both of those variants will be more confusing for the customer than, for example, the following one:

Product | Qty | Price | Sum
-- | -- | -- | --
A | 1 | 5.12 | 5.12
B | 1 | 5.13 | 5.13
  |   |   |  
Order Total |   |   | 10.25

where the prices are not equal (as they are supposed to be here) but slightly corrected. And such a practice is a commonly accepted one in Bookkeeping and Accounting.
Of course You may experiment with tax calculation settings in configuration but inaccuracy in prices or sums or totals will anyway occur from time to time while the taxes are reflected position-wise.
There's a practice how merchants use to avoid these rounding situations when taxes, discounts, etc. must be reflected throughout the positions. And that is to set up prices respectively. I mean, For example the price closest to 250 eur considering tax of 19% (included) where everything will work fine is the price of 249.90 eur. You may try it out - every number will be correct. Though that's a rear practice.
So with that I'm supposed to close this issue. But please feel free to reopen it if deem necessary.

**Closed as completed by engcom-Bravo** 2019-09-20 14:42 UTC
Labels: Issue: Format is not valid
