### ISSUE TITLE
Partial Refunds is not subtracted from the order grand total

### ISSUE THREAD

**Issue by IbrahimS2** [magento/magento2#33807] opened 2021-08-16 07:11 UTC
### Preconditions (*)

1. Magento 2.4.3
2. PHP 7.4
3. MySQL 8

### Steps to reproduce (*)

1. Create an order with two or more items
2. Issue an invoice
3. Issue a credit memo for one item
4. Order Grand Total does not get updated it is meant to be.

### Expected result (*)

1. Grand total gets updated and the grand total is going to be XYZ minus Refunded Value.
2. PDF Invoice does not include the refunded items.

### Actual result (*)

1. Grand total remains intact
2. PDF invoices included refunded items/value

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by IbrahimS2** [comment] 2021-08-16 07:12
@magento give me 2.4-develop instance

**Comment by IbrahimS2** [comment] 2021-08-16 07:29
Here I am creating a credit memo, please notice how much I refunding:
![image](https://user-images.githubusercontent.com/19901858/129526517-d98a218e-8ce3-4c19-a495-980839b7c7a6.png)

And hereafter issuing the credit memo, the order grand total remains intact:
![image](https://user-images.githubusercontent.com/19901858/129526627-b0d700f7-a484-486d-905a-ad544f4cec05.png)

What should happen here the "Total Refunded" must be moved right above the grand total and it should subtract its value
![image](https://user-images.githubusercontent.com/19901858/129526785-c49c2524-9806-4547-bcf4-7060138b9da6.png)

When printing the invoice, it includes the refunded amount and value.
![image](https://user-images.githubusercontent.com/19901858/129526909-49ff1c1c-c0ff-4553-99f3-4ef9a7ea35c1.png)

**Comment by onlinebizsoft** [comment] 2021-08-16 10:33
@IbrahimS2 I think this is not a bug, it is an expected behavior

**Comment by IbrahimS2** [comment] 2021-08-16 10:38
@onlinebizsoft But it is wrong, when you issue a partial refund, it should reflect in the order view and the invoices that I am attaching with the shipment where it should exclude what is been refunded, and the grand total should tell me what is the total amount after the refund.

**Comment by engcom-Lima** [comment] 2021-08-16 13:36
Hi @IbrahimS2, 

This is not wrong. Let me clarify, when the order is created Grand Total is the final amount which will always be same since the order was placed with that amount and the customer paid/will pay same amount for those products. Invoice is also generated on the same price value. 

Now, if any customer returns any number of items from that order, he/she will be issued Credit Memo which is also a separate PDF and accounts for how much customer will get refunded. Customer will have both documents with reference to that order.

Hope that clarifies your doubt. As this is expected behaviour, we are closing this issue.

**Closed as completed by engcom-Lima** 2021-08-16 13:36 UTC
Labels: Issue: ready for confirmation

**Comment by IbrahimS2** [comment] 2021-08-16 14:28
@engcom-Lima Okay, what about the PDF invoice?

**Comment by engcom-Lima** [comment] 2021-08-18 07:32
@IbrahimS2,

Sorry your question is not clear about PDF.

Invoices are created with the items/price values which are received when the order was created. Generally invoices does not contain any information about returns/refunded amount. 

Credit Memos are created when any/all item from the original order was returned. A credit memo is a document that shows the amount that is due the customer for a full or partial refund.

Please check detailed info on 
https://docs.magento.com/user-guide/sales/invoices.html
https://docs.magento.com/user-guide/sales/credit-memos.html

Hope it'll clarify your doubts.
