### ISSUE TITLE
flash messages not showing

### ISSUE THREAD

**Issue by erikmulder** [magento/magento2#3357] opened 2016-02-10 10:38 UTC
Magento ver. 2.0.2

After an upgrade from version 2.0.0 to 2.0.2 the flash messages stopped working. When for example I
subscribe to a newsletter I don't see any messages, unless the customer has a quote. In other words
flash messages are shown when there is a product in the cart, but when the cart is empty all the
messages ares suppressed.

**Comment by benathey** [comment] 2016-03-16 11:09
We have noted the same issue on upgrade to 2.0.2. Our findings....

There is a session cookie filter on Magento v2.0.2 that is not on 2.0.0 that checks session cookie "private_content_version" existence before it loads customer data including flash messages on vendor/magento/module-customer/view/frontend/web/js/customer-data.js around line 111... 

That's the reason why, after adding something to cart, message works fine but after cookie expires or user cleared cache, flash messages is not showing again...

Hope this helps.

**Comment by stevenvdp** [comment] 2016-03-25 10:54
This seems to be the commit which breaks the flashmessages:
[https://github.com/magento/magento2/commit/d4a91e40efaea4895395ba48575ec77562bfb3bc](url)

If I remove the check descibed by @benathey the flash messages work again:

`if (!_.isEmpty(privateContent)) {`

 Someone from the core team that can give some feedback on this?

**Comment by SidneyBilliet** [comment] 2016-05-17 13:42
@vzabaznov @guz-anton  
Any news on this?

**Comment by SidneyBilliet** [comment] 2016-06-06 08:38
@vzabaznov @guz-anton ?

**Comment by vikas529** [comment] 2016-06-08 12:18
I am also facing the same issue any body got the fix for this

**Comment by anton-huz** [comment] 2016-06-08 13:50
We are doing investigation under internal ticket MAGETWO-54077.

**Comment by rudenko-maksym** [comment] 2016-06-14 18:16
"private_content_version" cookie is not getting set when full_page cache is disabled, this is usually true for **development** environment.
Take a look here:
[https://github.com/magento/magento2/blob/develop/app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php#L70](url)
[https://github.com/magento/magento2/blob/develop/app/code/Magento/PageCache/Model/App/FrontController/VarnishPlugin.php#L56](url)

`$this->version->process();` is not getting called, therefore "private_content_version" cookie is not set.

**Comment by iivashchenko** [comment] 2016-06-22 15:17
This issue is present in 2.0.2, but I can't reproduce it in 2.0.7. I recommend upgrading to latest stable Magento version.

**Comment by anton-huz** [comment] 2016-07-05 14:34
Also issue is not reproducible in 2.1 release. I close the issue.

@erikmulder , if you have additional comments fill free to post them here.

**Comment by anton-huz** [comment] 2016-07-05 14:34
@kokoc

**Closed as completed by anton-huz** 2016-07-05 14:34 UTC
