### ISSUE TITLE
Links in Password reset templates bug

### ISSUE THREAD

**Issue by BenItt** [magento/magento2#35485] opened 2022-05-17 02:26 UTC
### Preconditions (*)

1. Magento 2.4.4 Community Edition
2. Multistore environment with Store codes de (German), en (English)

### Steps to reproduce (*)

1. Add customized "Forgot password mail" via go to Marketing --> Communications --> E-Mail Templates
2. Load Default Template "Forgot Password"
3. Add Template Name "Test Password"
4. Save Template
5. See variable `<a href="{{var this.getUrl($store,'customer/account/createPassword/',[_query:[id:$customer.id,token:$customer.rp_token],_nosid:1])}}" target="_blank">{{trans "Set a New Password"}}</a>` in E-Mail Template`
6. Go to Stores --> Configuration --> Customers --> Customer Configuration --> Password Options --> Forgot Email Template --> Chose created "Test Password" as new template
7. Go to YourMagentoinstance.com/en/customer/account/forgotpassword/
8. Send password reset via Forgot Password - Reset my password

### Expected result (*)

1. `<a href="{{var this.getUrl($store,'customer/account/createPassword/',[_query:[id:$customer.id,token:$customer.rp_token],_nosid:1])}}" target="_blank">{{trans "Set a New Password"}}</a>` will  be received as proper "Set a New password" link

### Actual result (*)

1. 2. In Thunderbird: "Set a new password" first character of link gets cut `ttps://yourmagentoinstance.com/en/customer/account/createPassword/?token=xxxxxxxxx`
(happens to all links in mail)
3. Gmail: Link received as `<a>Set a new password</a>`

(It seems that e-mail template gets handled somewhere wrongly and 2 characters get cut. If a space is added after `<a href= ` and before link closing " result as expected though:

`<a href= "{{var this.getUrl($store,'customer/account/createPassword/',[_query:[id:$customer.id,token:$customer.rp_token],_nosid:1])}} " target="_blank">{{trans "Set a New Password"}}</a>)`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-05-17 11:02
Hi @BenItt ,
Thank you for reporting and collaboration. Verified the issue on both Magento 2.4.4 and 2.4-develop versions but could not able to reproduce the issue.
Steps performed:
1. Magento multi store setup with store codes : en and de
2. Created new forgot password email template by loading default template and named - "Test Password"
3. Applied newly created template for Customer configuration - password options - Forgot Email Template in default config scope
4. Reset password in both /en/customer/account/forgotpassword/  and /de/customer/account/forgotpassword/ stores
No issue: password reset link is generated as expected and user is able to reset password
![image](https://user-images.githubusercontent.com/60198231/168796456-a8bf1cfe-dded-4cae-848b-39c2165108a2.png)

![image](https://user-images.githubusercontent.com/60198231/168796386-255d498b-2385-4837-aefc-d2cdef228da6.png)
Kindly recheck the issue again and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by BenItt** [comment] 2022-05-17 11:19
Dear. Thank you very much for the info.

This is weird. Good to know that it seems to be something related to our architecture then.

Would it be possible to send us the CreatePassword.PHP your vanilla instance is using in order to check this?

**Comment by engcom-November** [comment] 2022-05-18 11:46
Hi @BenItt 
Please find the below link of Magento 2.4-develop vanilla instance CreatePassword.php which we are using.
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/Controller/Account/CreatePassword.php
Thank you.

**Comment by BenItt** [comment] 2022-05-18 14:43
Dear @engcom-November,

good news. We found the culprit. Error was caused by an extension by "IT Recht Kanzlei" from Cyberday which we are using for our legal texts. Deactivating this extension and the error is gone.

**Comment by engcom-November** [comment] 2022-05-19 09:10
Thanks for the update @BenItt ,
We are closing this issue as code of this extension(IT Recht Kanzlei) is not part of  https://github.com/magento/magento2 git repository and community cannot provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.

**Closed as completed by engcom-November** 2022-05-19 09:10 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.4
