### ISSUE TITLE
Magento\Eav\Model\Entity\Attribute\Source\AbstractSource::getOptionId() gives negative positive

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#8193] opened 2017-01-19 09:13 UTC
Regarding `select`-attributes:

When I try to get an ID of an option according to a value that happens to be numeric, this method returns the wrong value.

### Preconditions

1. Magento 2.1.3

### Steps to reproduce

Create 2 options with the following values:

    id: 56      value: "Foo"
    id: 58      value: "56"

Run the following:

    echo $attributeSource->getOptionId("56");

### Expected result

It should return `58` since this is the correct ID of the value.

### Actual result

It returns `56` because the ID loosely equals the value.

### Why does this happen?

Take a look at the method:

    /**
     * @param string $value
     * @return null|string
     */
    public function getOptionId($value)
    {
        foreach ($this->getAllOptions() as $option) {
            if (strcasecmp($option['label'], $value) == 0 || $option['value'] == $value) {
                return $option['value'];
            }
        }

        return null;
    }

The method looks obvious, but the above error occurs when there is a match on an option before the actual value is returned.

In this example there are 2 options. In the first iteration `$value` is `"56"` and `$option['label']` is `"Foo"`. Since `"Foo" != "56"` the `OR`-statement is followed which states `$option['value'] == $value`. Needless to say, this returns true and we have a negative positive.

**Comment by kanduvisla** [comment] 2017-01-19 09:46
I've created a possible fix and added a pull request for this issue.

**Comment by vrann** [comment] 2017-03-23 14:17
@kanduvisla was not able to reproduce, closing. Feel free to reopen with more information.

**Closed as completed by vrann** 2017-03-23 14:17 UTC
Labels: Issue: Ready for Work, bug report, Component: Eav

**Comment by magento-team** [comment] 2017-08-01 14:58
Internal ticket to track issue progress: MAGETWO-65372
