### ISSUE TITLE
Missing content from wysiwyg after upgrade

### ISSUE THREAD

**Issue by devhn** [magento/magento2#3951] opened 2016-04-01 08:48 UTC
Hi,

after upgrading from 2.0.2 to 2.0.4 all content within `pub/media/wysiwyg` is missing / deleted upon upgrade. Not sure if we have the right workflow for uploading media content but when we for example create a new page within Magento administration, upload pictures with wysiwyg editor they seem to be stored within `pub/media/wysiwyg` directory which get's deleted upon upgrading.

Not sure if it's a bug or wrong workflow - explanation appreciated.

**Comment by Joshua34** [comment] 2016-04-01 22:18
Same issue when upgrading from 2.0.0 to 2.0.4

**Comment by dmitrii-fediuk** [comment] 2016-04-09 02:08
https://github.com/magento/magento2/issues/4054

**Comment by frangopr** [comment] 2016-05-19 21:47
Hi @MomotenkoNatalia 
I hope you are doing well.

I ran across this same issue aswell. It's very critical as it also happened to product images.

When searching you can find various issues reported for the same problem, but none seem conclusive.

Was wondering if this can be sometging the team could investigate internally.

Thank you & the team,

Fran

**Comment by pboisvert** [comment] 2016-05-20 05:10
Olena--can you have the team investigate this one?

**Comment by tkacheva** [comment] 2016-05-20 16:14
@benchmarky Thanks for reporting the issue! We will take care about in and include the fix in further magento patches 

Internal issue MAGETWO-53232

**Comment by mazhalai** [comment] 2016-05-24 21:53
@devhn @benchmarky Can you please give us detailed steps and env to reproduce this issue? 
- Was this Web setup wizard upgrade or via CLI?
- What OS? What PHP version? What Webserver?

**Comment by mazhalai** [comment] 2016-05-31 14:56
@devhn @benchmarky closing due to non-responsiveness.

**Comment by devhn** [comment] 2016-06-06 07:50
Sorry for late reply - CLI, Apache 2.4, PHP7

**Comment by tkacheva** [comment] 2016-06-16 15:22
PR with bugfixing is merged. Closing the issue. Reopen if needed.

**Closed as completed** 2016-06-16 15:22 UTC
Labels: Issue: Ready for Work, Progress: needs update
