### ISSUE TITLE
setup get 502 when click ‘Next‘ at ‘Web  Configuration‘ page

### ISSUE THREAD

**Issue by iyezhou** [magento/magento2#14724] opened 2018-04-17 01:21 UTC
### Preconditions

1. Magento 2.2.5
2. PHP 7.1.6
3. MySQL 5.7.18

![2018-04-17_8-56-48](https://user-images.githubusercontent.com/26378961/38843249-b5a02448-4220-11e8-9688-96e95c254495.png)

**Comment by magento-engcom-team** [comment] 2018-04-17 14:36
@iyezhou thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by iyezhou** [comment] 2018-04-18 01:10
@magento-engcom-team 
My installation procedure is:
1. git clone https://github.com/magento/magento2.git
2. composer install
3. Config nginx virtual host
4. User browser, open http://magento.xxx.com/setup/
5. next to `Readiness Check`, next to `Add a Database`, next to `Web Configuration`, then can not next to `Customize Your StoreNext`

**Comment by iyezhou** [comment] 2018-04-18 01:10
@magento-engcom-team 
My installation procedure is:
1. git clone https://github.com/magento/magento2.git
2. composer install
3. Config nginx virtual host
4. User browser, open http://magento.xxx.com/setup/
5. next to `Readiness Check`, next to `Add a Database`, next to `Web Configuration`, then can not next to `Customize Your StoreNext`

**Comment by iyezhou** [comment] 2018-04-18 09:07
I have solved the problem, It is the reason of PHP version. I update PHP vesion to 7.1.16, then right

**Comment by magento-engcom-team** [comment] 2018-05-26 08:49
Hi @iyezhou 
Thank you for the update. Closing the ticket now per your comment

**Closed as completed by magento-engcom-team** 2018-05-26 08:49 UTC
Labels: Progress: needs update, Issue: Format is not valid
