### ISSUE TITLE
Magento 2.2.4 multistore: Admin orders get wrong product name

### ISSUE THREAD

**Issue by sduif** [magento/magento2#16496] opened 2018-07-03 09:05 UTC
### Preconditions

1. Stock Magento 2.2.4

### Steps to reproduce

1. Create second website + store + store view
2. Create new simple product with title "Product name", and enable the product in both websites
3. Switch store view to the second store view and change the title to "Alternative name"
4. Create New Order through the backend for the "Second website"
5. Add product "Alternative name" to the order
6. Complete order

### Expected result

1. Order should have 1 item with title "Alternative name"

### Actual result

1. Order has 1 item with title "Product name" (Wrong store view title)

### Notes

When adding the product to the order through the backend the product title seems okay at first. But changes as soon as you start inputting customer details, change the payment method or choose the shipping method. I could also reproduce this bug on 2.2.3 so it's been around for a while.

**Comment by magento-engcom-team** [comment] 2018-07-03 09:05
Hi @sduif. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@sduif do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment] 2018-07-03 15:34
Hello @sduif, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2018-11-30 14:08
Hi @ssp58bleuciel. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by engcom-Bravo** [comment] 2019-09-20 08:52
Hello @sduif 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by engcom-Bravo** 2019-09-20 08:52 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, help wanted
