### ISSUE TITLE
2.4.5-p1 - Back end order vs Front End order. Shipping Fees Rules.

### ISSUE THREAD

**Issue by broeder** [magento/magento2#36828] opened 2023-02-09 08:54 UTC
### Preconditions and environment

- Magento version: 2.4.5-p1
Step 1. Navigate to Stores > Settings > Configuration.

Step 2. Open the Sales section and go to Delivery Methods.

Step 3. Switch the Enable setting to Yes in the Flat Rate Dropdown

Step 4. Specify the Title ("Shipping Fee") and Method Name ("Home Delivery").

Step 5. Set Type to "per order". Set Price to "40". Set Calculate Handling Fee to "Fixed". Set Maximum price to set free to "350".

Step 6. Save Config

### Steps to reproduce

Navigate to Back end.
Create order with cart price > 350. 
Choose Shipping Method : "Home Delivery".
Create Order.

### Expected result

Order Totals :
Shipping & Handling = 0

### Actual result

Order Totals :
Shipping & Handling = 40

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by broeder** [comment] 2023-02-09 09:56
Note: 
**On Front-end works as expected.**
Actual results:

Order Totals :
Shipping & Handling = 0.

**Comment by engcom-November** [comment] 2023-02-10 05:14
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2023-02-10 05:52
Hi @broeder ,
Thank you for reporting and collaboration. Verified the configuration on Magento 2.4-develop instance but unable to find the option "Maximum price to set free " for flat rate or any of the available delivery methods. Also no where mentioned in the Magento [docs](https://docs.magento.com/user-guide/v2.3/configuration/sales/shipping-methods.html). Can you please recheck the behavior on Magento 2.4-develop instance and let us know if you are using any 3rd party extensions / modules?
Thank you.

**Comment by broeder** [comment] 2023-02-10 07:05
Hello, Here is a screencap of my admin.
This module is native.
Or am I wrong ?

**Comment by broeder** [comment] 2023-02-10 07:11
Done.
I saved the config on your instance.
Can you check ?
Thanks.

**Comment by broeder** [comment] 2023-02-10 07:17
Edit; Sorry, you are right. Let me check if 3rd party or something else.

Le ven. 10 févr. 2023 à 08:11, Matthieu Malan ***@***.***> a
écrit :

> Done.
> I saved the config on your instance.
> Can you check ?
> Thanks.
>
> Le ven. 10 févr. 2023 à 06:18, magento-deployment-service[bot] <

**Comment by broeder** [comment] 2023-02-10 14:25
@magento give me 2.4-develop instance

**Comment by broeder** [comment] 2023-02-10 14:36
@magento I am working on this

**Comment by broeder** [comment] 2023-02-11 10:17
@magento add to contributors team

**Comment by broeder** [comment] 2023-02-11 13:34
@magento give me 2.4-develop instance

**Comment by broeder** [comment] 2023-02-11 15:45
Not the same back-end as on  ver. 2.4.2-p2
Which version is this ?
How can I have  ver. 2.4.2-p2 here ?

**Comment by broeder** [comment] 2023-02-12 08:57
Field "Set Maximum price to set free to" is missing on this version. This is not a 3rd party module. It is Magento core. 
What gives ?

**Comment by broeder** [comment] 2023-02-12 09:00
@magento give me 2.4.5-p1-develop instance

**Comment by engcom-November** [comment] 2023-02-13 04:49
Hi @broeder ,
Thank you for the response. Verified the issue again on Magento 2.4.5-p1 instance but the option "Set Maximum price to set free to" is not available for flat rate shipping method in 2.4.5-p1 instance as well. Also no where mentioned in the Magento [documentation](https://docs.magento.com/user-guide/v2.3/configuration/sales/shipping-methods.html). Kindly recheck the issue on Magento 2.4-develop instance without any 3rd party extensions/modules enabled as it is having latest code base and upcoming 2.4.x release and elaborate missing steps if any if the issue is still reproducible.
Thank you.
![image](https://user-images.githubusercontent.com/60198231/218373188-510b3223-6954-4bee-b322-9481ff8a47af.png)

![image](https://user-images.githubusercontent.com/60198231/218373149-73bf8c57-f847-4989-a623-cacb6cc15636.png)

**Comment by engcom-November** [comment] 2023-02-27 04:09
Hi @broeder ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2023-02-27 04:09 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.5-p1
