### ISSUE TITLE
Localized date not sanitized

### ISSUE THREAD

**Issue by dpaleino** [magento/magento2#10472] opened 2017-08-09 10:04 UTC
Hello,
Magento 2.1.7. In /admin/admin/system_design/new/ , I have two datepickers, which correctly show me localized month names, and date format (for Italy, that's dd/mm/yyyy). Clicking a date for the popup correctly populates the input field with the localized format.

As soon as I click Save, I get:

> Exception #0 (Exception): Invalid input date format '31/12/2017'

Going back, and manually inputting the date in the mm/dd/yyyy format correctly saves it (and then, in the grid, it shows up with the correct localized format)

![screen](https://user-images.githubusercontent.com/40317/29116353-d0b4f204-7cfa-11e7-8f25-9cd8ab03ca76.jpg)

Here's the first few lines of the backtrace:

> Exception #0 (Exception): Invalid input date format '31/12/2017'
> #0 /home/dp/magento2/vendor/magento/zendframework1/library/Zend/Filter.php(114): Magento\Framework\Stdlib\DateTime\Filter\Date->filter('31/12/2017')
> #1 /home/dp/magento2/vendor/magento/zendframework1/library/Zend/Filter/Input.php(722): Zend_Filter->filter('31/12/2017')
> #2 /home/dp/magento2/vendor/magento/zendframework1/library/Zend/Filter/Input.php(701): Zend_Filter_Input->_filterRule(Array)
> #3 /home/dp/magento2/vendor/magento/zendframework1/library/Zend/Filter/Input.php(785): Zend_Filter_Input->_filter()
> #4 /home/dp/magento2/vendor/magento/zendframework1/library/Zend/Filter/Input.php(381): Zend_Filter_Input->_process()
> #5 /home/dp/magento2/vendor/magento/module-backend/Controller/Adminhtml/System/Design/Save.php(24): Zend_Filter_Input->getUnescaped()
> #6 /home/dp/magento2/vendor/magento/module-backend/Controller/Adminhtml/System/Design/Save.php(38): Magento\Backend\Controller\Adminhtml\System\Design\Save->_filterPostData(Array)

**Comment by magento-engcom-team** [comment] 2017-09-11 16:52
Duplicate of #10580

**Closed as completed by magento-engcom-team** 2017-09-11 16:53 UTC
Labels: bug report, Issue: Format is not valid
