### ISSUE TITLE
No such entity with orderId = X in checkout after in-store delivery

### ISSUE THREAD

**Issue by julien410gone** [magento/magento2#32607] opened 2021-03-26 14:18 UTC
### Summary (*)

In Magento 2.4.2 with Stripe module 2.5.4.
The issue happens when trying to place an order with a bundle, and "Payment Card" method after another customer placed an order (any product type and any payment method) with the delivery method "Pick up in store". 
When card informations are entered and submit button is clicked, a critical message shows up : 
"No such entity with orderId=X" where X is an existing orderId and the order is not placed.

Tested with 3D secure, same issue.

I talked with Stripe support but for them, it's a Magento bug.

### Examples (*)

Steps to reproduce : 
 - Login with a first account, add a product to cart and go to checkout.
 - Select "Pick up in store" delivery method.
 - Use any payment method to checkout and enter payment informations.
 - When order is placed, logout. 
 - Login with a second different account
 - Add a Bundle product to cart and go to checkout.
 - Select any delivery method
 - Use "Card Payment" method to chekout and enter payment informations.
 - You should get an error like "No such entity with orderId=<id of the first order>" 

I made a video of these steps with the error message at the end, you can watch it here : https://www.youtube.com/watch?v=kDEHAcCoRE4&ab_channel=JulienBailly

### Proposed solution

I actually don't have a solution to fix this, but while debugging, we figured out that when ordering with the second account and card payment, the execute() method in Magento\InventoryInStorePickupSales\Model\SourceSelection\GetActiveStorePickupOrdersBySource is adding every orders with delivery method as "Pick up in Store". 
Orders returned will not have the same customerId as the current customerId, leading to the error.

It seems that Magento is processing every order with "Pick up in store" delivery method. But when processing, it tries to load order with a customer Id  different of the current.  

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by julien410gone** [comment] 2021-03-30 08:06
@magento give me 2.4-develop instance

**Comment by julien410gone** [comment] 2021-04-06 09:46
This issue seems to be related to the In-Store delivery method, preventing Stripe to work properly.

I am not able to test on the given Magento instance because of Stripe was not installed on it.

Could someone help us please?

**Comment by BahaDuganov** [comment] 2021-04-12 03:16
Having the same error with Windcave PxPayIframe
The in-Store delivery method is not active

**Comment by engcom-Hotel** [comment] 2021-06-22 16:43
Hi @julien410gone ,

We have tried to reproduce this issue in Magento 2.4-develop. But we are unable to reproduced this issue. We have exactly followed the steps you mentioned in the ticket with Klarna payment gateway.

Please try again and let us know in case you faced the same issue or we need to use any specific payment method in order to reproduce this issue.

**Comment by engcom-Hotel** [comment] 2021-07-06 07:18
Hi @julien410gone,

We are unable to hear from you since past 14 days. So we are closing this issue for now. If you still facing this issue either you can reopen this or create new ticket.

Thanks

**Closed as completed by engcom-Hotel** 2021-07-06 07:18 UTC
Labels: Issue:  Cannot Reproduce, Triage: Dev.Experience, Issue: needs update
