### ISSUE TITLE
Provide more details for "URL key for specified store already exists." error

### ISSUE THREAD

**Issue by piatrouski** [magento/magento2#8564] opened 2017-02-15 11:16 UTC
### Expected result
1. Display a more detailed error message like "Integrity constraint violation: 1062 Duplicate entry 'blah-blah.html-3' for key 'URL_REWRITE_REQUEST_PATH_STORE_ID'"

### Actual result
1. URL key for specified store already exists.

**Comment by korostii** [comment] 2017-02-17 10:28
There might be an argument that these messages might appear in the messages shown in admin  and words like "Integrity constraint violation" might scare an unprepared merchant forcing him to think something went very wrong. 
Well, it just did go wrong! And the more information system provides, the better. Unless on some level this exception is processed by changing the URL key automatically, the message shown to the user has to provide detailed info.

At the very least, the detailed error message must appear in the exception.log when it gets replaced by a generic "URL key for specified store already exists.". Currently it just gets replaced [here](https://github.com/magento/magento2/blob/b1e56ed3b6f13f1ab780d8eddc33fc04cb6ecf75/app/code/Magento/UrlRewrite/Model/Storage/AbstractStorage.php#L86) and [here](https://github.com/magento/magento2/blob/b1e56ed3b6f13f1ab780d8eddc33fc04cb6ecf75/app/code/Magento/UrlRewrite/Model/Storage/DbStorage.php#L117)

**Comment by piatrouski** [comment] 2017-02-24 15:31
Try this solution for displaying a more detailed error message.

[DbStorage.php.txt](https://github.com/magento/magento2/files/799741/DbStorage.php.txt)

**Comment by korostii** [comment] 2017-03-03 12:24
Cool, your fix is useful for when the errors appears in admin, specifically, but I'm not sure if it would still work when importing products from console. Personally, I would prefer using the logger here.
(Just complaining that Magento itself could deal with it better, on so many levels)

**Comment by veloraven** [comment] 2017-06-15 15:34
@piatrouski is this issue still actual?
If it is please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
If it is not, please close it.

**Comment by korostii** [comment] 2017-06-15 21:48
Oh wow. 4 months. That was fast :D
@veloraven, please see [my comment](https://github.com/magento/magento2/issues/8564#issuecomment-280613973) above, I pointed out exact places in source code (which haven't changed since, meaning the issue is still actual.

It is quite clear that root cause of the error is being lost. Short of a pull request, I fail to understand what else do you need. 

It's not as if this issue wasn't reported before. In fact, [there is a lot of people who were able to reproduce it](url). Come on, it's not _that_ hard.

**Comment by magento-engcom-team** [comment] 2017-09-07 20:45
@piatrouski  thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version 
 - [ ] Steps to reproduce

**Comment by orlangur** [comment] 2017-09-21 09:40
@piatrouski thanks for your suggestion!

Error message was improved on Magento 2.2.0 branch to give more information to merchant what exactly needs to be changed.

**Closed as completed by orlangur** 2017-09-21 09:40 UTC
Labels: improvement, Issue: Clear Description, Fixed in 2.2.x, Issue: Format is not valid
