### ISSUE TITLE
CMS Block content is not updated according to page builder changes during CMS Block save

### ISSUE THREAD

**Issue by Aleksejs-Prjahins** [magento/magento2#37514] opened 2023-05-18 14:28 UTC
### Preconditions and environment

- Magento 2.4.4, Commerce
- CMS Block with a lot of content

### Steps to reproduce

1. Navigate to the admin panel
2. Content -> Blocks -> Select block
3. Make block changes
4. Click on Save

### Expected result

CMS Block content is saved and a success message appears.

### Actual result

A success message appears, but CMS Block content stays as it was before.

https://github.com/magento/magento2/assets/70320709/58ccb1f6-2291-4dda-b9da-b6b58053f384

### Additional information

During investigation been found that when the save button was clicked content of the page builder which was transported to the hidden input field is old.
Also, the issue appears randomly, sometimes content is saved, sometimes not.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2023-05-18 14:50
@magento give me 2.4-develop instance

**Comment by frostitution** [comment] 2023-05-18 16:51
Probably related to #34898 - I have a similar issue, it only happens on Chrome. Try FireFox or other browsers

**Comment by engcom-November** [comment] 2023-05-19 04:59
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2023-05-19 05:52
Hi @Aleksejs-Prjahins ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance but the issue is not reproducible.
CMS Block content is getting updated as expected after editing and saving with Page builder.
But the block preview is not working properly (HTML code content is not displayed properly) and this bug being tracked in a separate bug: https://github.com/magento/magento2/issues/36713
Unable to access the video attached in the description. Kindly recheck the issue on Magento 2.4-develop instance and provide missing steps if any if the issue is still reproducible.

**Comment by denissdubinin** [comment] 2023-05-19 11:18
I have same issue on Magento 2.4.6

**Comment by KrzysztofWisniewskiAcc** [comment] 2023-05-31 19:24
Hey, I can confirm that we also got this on our 2.4.4-p3 instance.
We recently upgraded from 2.4.2-p2 and this issue started to occur.

This behavior can be noticed when saving contents of:  block/dynamic block/cms page
After clicking save you get a success message but the content was not updated.

This occurs very randomly, it's very hard to reproduce this.
I had few sessions trying to create a reproducible scenario, but without success.

Pretty sure it's not the browser issue as I was trying to reproduce this on firefox/chrome/safari/edge and it happened to me on all of those browsers but only few times.

**Comment by lukas19944** [comment] 2023-06-05 12:21
Error occurs randomly and it is caused due to wrong order loading js scripts. 
In my case was more easy to reproduce this issue when browser developer tools was hidden.  
This is the patch which solving this issue for module magento/module-page-builder:

diff --git a/view/adminhtml/requirejs-config.js b/view/adminhtml/requirejs-config.js
index f7a5d86..e234b84 100644
--- a/view/adminhtml/requirejs-config.js
+++ b/view/adminhtml/requirejs-config.js
@@ -22,6 +22,9 @@ var config = {
         },
         'Magento_PageBuilder/js/resource/jquery/ui/jquery.ui.touch-punch': {
             deps: ['jquery/ui']
+        },
+        'Magento_PageBuilder/js/form/element/wysiwyg': {
+            deps: ['Magento_Ui/js/form/form']
         }
     },
     config: {

magento 2.4.4 and magento/module-page-builder 2.2.2

**Comment by engcom-Dash** [comment] 2023-06-08 09:57
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2023-06-13 04:29
Verified the issue again on Magento 2.4-develop instance with enterprise edition and B2B modules enabled and the issue is reproducible with below steps performed:
Steps performed:
1. Enable Page builder modules on commerce instance
2. login to Magento Admin - Content - Blocks - Create / edit block
3. Edit with page builder
4. Add Rows / text / heading
5. Exit full screen mode and click on Save
Issue: Success message is displayed but the page builder content is not getting saved
![image](https://github.com/magento/magento2/assets/60198231/6eefa2aa-96ba-45d1-9808-1f5e34e50e31)

**Comment by RanayCodes** [comment] 2023-07-19 07:39
Steps to reproduce the issue :  

Upgrade the chrome version to the latest, it will start reproducing.

This solution works like charm :


Error occurs randomly and it is caused due to wrong order loading JS scripts. 

![image](https://github.com/magento/magento2/assets/125727331/4d56f213-cda0-4eb0-b01d-8d87249c09c3)

**Comment by samvens** [comment] 2023-09-17 08:33
> Error occurs randomly and it is caused due to wrong order loading js scripts. In my case was more easy to reproduce this issue when browser developer tools was hidden. This is the patch which solving this issue for module magento/module-page-builder:
> 
> ```diff
> index f7a5d86..e234b84 100644
> --- a/view/adminhtml/requirejs-config.js
> +++ b/view/adminhtml/requirejs-config.js
> @@ -22,6 +22,9 @@ var config = {
>          },
>          'Magento_PageBuilder/js/resource/jquery/ui/jquery.ui.touch-punch': {
>              deps: ['jquery/ui']
> +        },
> +        'Magento_PageBuilder/js/form/element/wysiwyg': {
> +            deps: ['Magento_Ui/js/form/form']
>          }
>      },
>      config: {
> ```
> 
> magento 2.4.4 and magento/module-page-builder 2.2.2

I'm also facing the same issue. How can I override magento/module-page-builder/view/adminhtml/requirejs-config.js and add this snippet? As It should not be added directly in vendor.

Please can someone let me know?

**Comment by samvens** [comment] 2023-09-18 18:48
@lukas19944 @n0kit31 how did you guys override default magento/module-page-builder/view/adminhtml/requirejs-config.js and resolved this issue? Please can you help?

**Comment by aleksandr-mikhailov** [comment] 2023-10-28 01:42
I have debugged this behavior a little bit and, seems, found the cause of such intermittent behavior.

There is the following mixin related to registration of page builder instances and further form submit activities: `vendor/magento/module-page-builder/view/adminhtml/web/js/form/form-mixin.js`. It defines `"pagebuilder:register"` event in its initialize method, which is responsible for the mentioned registration.

Also, there is a WYSIWYG form element described in the `vendor/magento/module-page-builder/view/adminhtml/web/js/form/element/wysiwyg.js` which is triggering `"pagebuilder:register"` event during initialization (see `initialize -> initPageBuilder` methods)

Currently, there is no any direct relationships between these elements: `Magento_PageBuilder/js/form/form-mixin` is dependent on `Magento_Ui/js/form/form`, in turn, `Magento_PageBuilder/js/form/element/wysiwyg` is dependent  to `Magento_Ui/js/form/element/wysiwyg` right now.

In rare cases `"pagebuilder:register" `event can be triggered from the WYSIWYG element prior to it's creation in the mentioned form mixin, and in such cases "Save" action performs relatively quick, and no any updates are applied for block content.

So, to be more precise, the following dependency could be added: `Magento_PageBuilder/js/form/form-mixin` instead of `Magento_Ui/js/form/form`.

@samvens you can add appropriate dependency into custom requirejs-config.js file in scope of custom extension
```javascript
var config = {
    shim: {
        'Magento_PageBuilder/js/form/element/wysiwyg': {
            deps: ['Magento_PageBuilder/js/form/form-mixin']
        }
    },
}
``` 
or
```javascript
var config = {
    shim: {
        'Magento_PageBuilder/js/form/element/wysiwyg': {
            deps: ['Magento_Ui/js/form/form']
        }
    },
}
```

**Comment by engcom-Bravo** [comment] 2023-12-04 05:09
Hi @Aleksejs-Prjahins,

The issue's reproducibility was assessed by creating a block with numerous rows, columns, headings, and text fields across default, developer, and production modes in 2.4-develop.
Additionally, in developer mode, we experimented with toggling the merge and minify JavaScript settings, as well as the merge and minify CSS settings.
Despite these variations, the problem could not be replicated. Hence closing the issue
Below is the screencast:



https://github.com/magento/magento2/assets/51680745/b4a0b754-ad1e-4a0a-93ce-c5a49b81e8e3



Thanks.

**Closed as completed by engcom-Bravo** 2023-12-04 05:09 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P1, Progress: done, Component: PageBuilder, Area: Content, Reported on 2.4.4, Adobe Commerce

**Comment by emanueleftimie** [comment] 2024-01-29 14:04
> > Error occurs randomly and it is caused due to wrong order loading js scripts. In my case was more easy to reproduce this issue when browser developer tools was hidden. This is the patch which solving this issue for module magento/module-page-builder:
> > ```diff
> > index f7a5d86..e234b84 100644
> > --- a/view/adminhtml/requirejs-config.js
> > +++ b/view/adminhtml/requirejs-config.js
> > @@ -22,6 +22,9 @@ var config = {
> >          },
> >          'Magento_PageBuilder/js/resource/jquery/ui/jquery.ui.touch-punch': {
> >              deps: ['jquery/ui']
> > +        },
> > +        'Magento_PageBuilder/js/form/element/wysiwyg': {
> > +            deps: ['Magento_Ui/js/form/form']
> >          }
> >      },
> >      config: {
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > magento 2.4.4 and magento/module-page-builder 2.2.2
> 
> I'm also facing the same issue. How can I override magento/module-page-builder/view/adminhtml/requirejs-config.js and add this snippet? As It should not be added directly in vendor.
> 
> Please can someone let me know?

try to use someting like https://github.com/cweagans/composer-patches

**Comment by cjayalmontecm** [comment] 2024-03-13 02:25
> Closing the full-screen editing view in PageBuilder and then quickly clicking the save button seems to make this issue more likely to be reproduced

Have you fix the issue ?
