### ISSUE TITLE
dev:query-log:enable does not work

### ISSUE THREAD

**Issue by adamlavery** [magento/magento2#17134] opened 2018-07-25 16:10 UTC
### Preconditions

1. Magento 2.2.3
2. PHP 7.0, MySQL 5.7.22

### Steps to reproduce

1. Enable query logging with dev:query-log:enable (as per https://devdocs.magento.com/guides/v2.2/config-guide/cli/logging.html)
2. Clear cache with cache:flush and/or cache:clean
3. Do something, e.g. run a reindex
4. Check deploy mode is developer (it is) and repeat
5. Check Advanced > Developer > Log to File is enabled (it is) and repeat

### Expected result

1. File var/debug/db.log should be generated with log of SQL queries executed by action.

### Actual result

1. No file is created and nothing is logged (not in var/log either)

**Comment by magento-engcom-team** [comment] 2018-07-25 16:10
Hi @adamlavery. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@adamlavery do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment] 2018-07-26 07:41
Hello @adamlavery, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by Jakhotiya** [comment] 2018-08-05 08:04
@engcom-backlog-nickolas @magento-engcom-team @adamlavery I can't reproduce this issue on M2.2.4 and above. Can you confirm?

**Comment by snowcore** [comment] 2018-09-11 07:09
Checked on 2.2.5 - logging doesn't work.

**Comment by magento-engcom-team** [comment] 2018-11-10 09:31
Hi @SikailoISM. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by engcom-Charlie** [comment] 2019-09-24 10:50
Hello @adamlavery 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by engcom-Charlie** 2019-09-24 10:50 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Component: Developer
