### ISSUE TITLE
Error when clicking on "all customers" to get sto website access approval/editing

### ISSUE THREAD

**Issue by khoezee** [magento/magento2#38460] opened 2024-02-21 15:10 UTC
### Preconditions and environment

-magento admin

### Steps to reproduce

-login to magento
-click tab that says "customers"
-click button that says "all customers"

### Expected result

-should have brought up a screen with a list of customers that are either approved or not approved for website access

### Actual result

![Capture](https://github.com/magento/magento2/assets/160755745/770399bc-b1e7-4189-8577-64b2b4044338)

Picture attached

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-02-22 06:26
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-02-22 06:49
Hi @khoezee,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


![Screenshot from 2024-02-22 12-17-03](https://github.com/magento/magento2/assets/51680745/e1b951f3-e86c-4700-b7a2-c0260e289d2c)


Could you please refer this comment https://github.com/magento/magento2/issues/26515#issuecomment-802797711 it may resolves the issue and check the issue in Magento 2.4-develop instance.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-03-04 05:26
Hi @khoezee,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel free to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Bravo** 2024-03-04 05:26 UTC
Labels: Issue: needs update, Reported on 2.4.x
