### ISSUE TITLE
Rest API is allowing duplication for attribute options and also always returning an empty option

### ISSUE THREAD

**Issue by abdulmoizbaig** [magento/magento2#10013] opened 2017-06-21 18:16 UTC
## Preconditions:
1. Magento 2.1.5 or 2.1.7

## Steps to reproduce:

1. Use this endpoint to add options for an attribute **V1/products/attributes (catalogProductAttributeRepositoryV1)** and trying adding similar values for each option's label.
2. Use this endpoint to get options of attribute that you added in the step 1 **V1/products/attributes/{id}/options (catalogProductAttributeOptionManagementV1)**

## Actual Result:
`{"is_wysiwyg_enabled":"","is_html_allowed_on_front":"","used_for_sort_by":"","is_filterable":"","is_filterable_in_search":"","is_used_in_grid":"","is_visible_in_grid":"","is_filterable_in_grid":"","position":"0","apply_to":[],"is_searchable":"0","is_visible_in_advanced_search":"0","is_comparable":"0","is_used_for_promo_rules":"0","is_visible_on_front":"0","used_in_product_listing":"0","is_visible":"1","scope":"global","attribute_id":"136","attribute_code":"aaattribute","frontend_input":"select","entity_type_id":"4","is_required":"","options":[{"label":"","value":""},{"label":"ThisIsATestValue","value":"4"},{"label":"ThisIsATestValue","value":"5"},{"label":"ThisIsATestValue","value":"6"}],"is_user_defined":"1","default_frontend_label":"aaattribute","frontend_labels":"","backend_type":"int","source_model":"Magento\\Eav\\Model\\Entity\\Attribute\\Source\\Table","default_value":"6","is_unique":"0","validation_rules":[]}`

## Expected result
`{"is_wysiwyg_enabled":"","is_html_allowed_on_front":"","used_for_sort_by":"","is_filterable":"","is_filterable_in_search":"","is_used_in_grid":"","is_visible_in_grid":"","is_filterable_in_grid":"","position":"0","apply_to":[],"is_searchable":"0","is_visible_in_advanced_search":"0","is_comparable":"0","is_used_for_promo_rules":"0","is_visible_on_front":"0","used_in_product_listing":"0","is_visible":"1","scope":"global","attribute_id":"136","attribute_code":"aaattribute","frontend_input":"select","entity_type_id":"4","is_required":"","options":[{"label":"ThisIsATestValue","value":"4"}],"is_user_defined":"1","default_frontend_label":"aaattribute","frontend_labels":"","backend_type":"int","source_model":"Magento\\Eav\\Model\\Entity\\Attribute\\Source\\Table","default_value":"6","is_unique":"0","validation_rules":[]}
`
## Additional information

1. It always returns an empty option as you can see (`{"label":"","value":""}`) in actual result.
2. It should not add duplicates as you can see in actual result(`{"label":"ThisIsATestValue","value":"4"},{"label":"ThisIsATestValue","value":"5"},{"label":"ThisIsATestValue","value":"6"}`) because its not allowed from admin panel too. It should say something like "already exist".

**Comment by veloraven** [comment] 2017-07-05 08:35
@abdulmoizbaig thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
Otherwise it's hard to understand what you are waiting to see and what actually happens.

**Comment by magento-engcom-team** [comment] 2017-09-20 08:17
@abdulmoizbaig, thank you for your report.
We've created internal ticket(s) MAGETWO-75549 to track progress on the issue.

**Comment by Fuzzzzy** [comment] 2017-10-15 11:23
I'm working on it #SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment] 2018-08-20 11:04
Hi @abdulmoizbaig

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment] 2018-09-07 12:06
@abdulmoizbaig, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Closed as completed by magento-engcom-team** 2018-09-07 12:06 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, triage wanted

**Comment by alexandrosk** [comment] 2020-06-19 12:33
@abdulmoizbaig Hey Abdul, did you remember what you did to fix this? I'm having the exact same issue. Thanks!
