### ISSUE TITLE
Mass Delete Does Not Work

### ISSUE THREAD

**Issue by scooby09** [magento/magento2#33953] opened 2021-08-31 03:13 UTC
Mass delete products in magento 2.3.2 does not work, only deletes the total number of items on the page.

Reproduce- Go to catalog -> products. Select ALL (not to be confused with "select all on this page"), then select delete, you will get a message asking to confirm you want to delete all records (pop-up will show the correct total number), click ok... what actually happens is it just deletes all products loaded on that page, not the total amount that you actually selected/pop-up shows. 

![SelectAll](https://user-images.githubusercontent.com/65132476/131434264-3555e4b1-7d4c-4448-b36a-212cd6bc2172.png)
![AlLSelected](https://user-images.githubusercontent.com/65132476/131434311-f752c5b9-0b20-461a-ac50-8807cbb7f942.PNG)
![999](https://user-images.githubusercontent.com/65132476/131435726-d52337ee-be5b-4d29-aef1-77e5ddb9fc32.PNG)

**Comment by engcom-Echo** [comment] 2021-08-31 04:55
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment] 2021-08-31 05:46
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment] 2021-08-31 08:52
Hi @scooby09 
I tried to reproduce this issue on 2.4-develop & was unable to do so.
Here are the steps I following.
1. On a clean instance of magento **2.4-develop** , added few products.
2. Attempted mass delete of all the products
3. All the products got deleted successfully.
<img width="1366" alt="Screenshot 2021-08-31 at 13 21 46" src="https://user-images.githubusercontent.com/51681435/131472713-3ac7f1fc-46d7-42bb-b3e9-815aa40bee24.png">
<img width="1366" alt="Screenshot 2021-08-31 at 13 22 04" src="https://user-images.githubusercontent.com/51681435/131472721-c5d40058-bd5c-41f8-a150-d37cf64599cf.png">
<img width="1366" alt="Screenshot 2021-08-31 at 13 26 36" src="https://user-images.githubusercontent.com/51681435/131472746-6f2f51db-823a-468c-978e-2c02c99cfa37.png">

So kindly recheck this issue on Magento 2.4-develop branch and if the issue is still reproducible, please provide more details or additional/missing steps regarding the same.

Thank you.

**Comment by scooby09** [comment] 2021-08-31 11:11
I am not on 2.4 nor do i want to be at the moment. Also try having more than one page full of products, go past 999 and see if you can still delete everything, as again, the select all is deleting just a full page, so your test is not really valid

**Comment by engcom-Echo** [comment] 2021-09-14 05:30
Hi @scooby09 
Since we didn't get any updates from you & since we couldn't reproduce the issue being reported on **2.4-develop**, we are closing this issue.
If this issue is still reproducible for you on magento **2.4-develop**, please feel free to reopen this issue & provide more details or additional/missing steps regarding the same.

Thank you

**Closed as completed by engcom-Echo** 2021-09-14 05:30 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
