### ISSUE TITLE
unnecessary loader on Checkout when no fields are filled in. 

### ISSUE THREAD

**Issue by leonhelmus** [magento/magento2#37838] opened 2023-08-03 12:03 UTC
### Preconditions and environment

- Magento version: 2.4.4-p4
- Php 8.1

### Steps to reproduce

1. Add a product to the cart go as a guest user
3. Go to the cart
4. Go to the checkout
5. Select a shipping method, but don't add anything to other fields like (email, street, zipcode, etc.)
6. click on "next"

### Expected result

Validation is triggered and nothing more.

### Actual result

Validation is triggered and also some rest apis are triggered like:
* rest/nl/V1/guest-carts/test/estimate-shipping-methods
* /rest/nl/V1/guest-carts/test/totals-information
* rest/nl/V1/guest-carts/test/shipping-information
And a loader which prevents the user for 2-3 seconds from continuing.

### Additional information

This patch resolved my issue:

```
diff --git a/vendor/magento/module-checkout/view/frontend/web/js/view/shipping.js b/vendor/magento/module-checkout/view/frontend/web/js/view/shipping.js
--- a/vendor/magento/module-checkout/view/frontend/web/js/view/shipping.js
+++ b/vendor/magento/module-checkout/view/frontend/web/js/view/shipping.js	(date 1691056962379)
@@ -335,7 +335,7 @@
                     );
                 }

-                if (emailValidationResult &&
+                if (!emailValidationResult ||
                     this.source.get('params.invalid') ||
                     !quote.shippingMethod()['method_code'] ||
                     !quote.shippingMethod()['carrier_code']

```

With this patch it will now also check when email is not filled in and now only triggers validation instead of all other things as well.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-08-03 12:05
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-08-03 12:47
Hi @leonhelmus ,

Verified the issue in 2.4-develop instance and the issue is not reproducible,Kindly provide more details to confirm this issue and kindly recheck the behaviour in 2.4-develop instance.
Kindly refer below screenshots:
<img width="1512" alt="Screenshot 2023-08-03 at 6 09 35 PM" src="https://github.com/magento/magento2/assets/60198592/cfffa540-1345-4ae3-8063-46ca0f1a42f5">

**Comment by leonhelmus** [comment] 2023-08-03 13:11
I cant tell if you do not have email filled in or not. It does add a loader for the shipping methods.

When looking here:
![image](https://github.com/magento/magento2/assets/18070887/fd7c14c3-56ed-441b-ac7f-971e440346c5)

you see it continues while it should stop at this part:
```
                if (emailValidationResult &&
                    this.source.get('params.invalid') ||
                    !quote.shippingMethod()['method_code'] ||
                    !quote.shippingMethod()['carrier_code']
                ) {
                    this.focusInvalid();

                    return false;
                }
```

but since the email is not valid it will not trigger the return false.

**Comment by engcom-Dash** [comment] 2023-08-08 11:06
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-08-09 11:23
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-08-21 08:06
Hi @leonhelmus ,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2023-08-21 08:06 UTC
Labels: Issue: needs update, Reported on 2.4.4-p4
