### ISSUE TITLE
Pipeline build dosen't generate static content for all locales

### ISSUE THREAD

**Issue by marvincaspar** [magento/magento2#33319] opened 2021-06-22 13:49 UTC
I have a shop with multiple stores and storeviews and each storeview has a different locale configured. I followed the [magento pipeline deployment](https://devdocs.magento.com/guides/v2.4/config-guide/deployment/) instructions to build a docker container which i want to ship. I created a config dump and an empty `env.php` file and run the commands `bin/magento setup:di:compile` and `bin/magento setup:static-content:deploy --force`. The static content command just generates the files for the locale en_US but not for the other used languages. I don't want to add all languages to the static content command because I don't want to adjust the pipeline build every time I added a new locale and I want to use the pipeline as template for multiple magento stores.

Here is a small part from the config dump:

```php
<?php
return [
    ...
    'system' => [
        ...
        'stores' => [
            'admin' => [
            ],
            'de_de' => [
                'general' => [
                    'locale' => [
                        'code' => 'de_DE',
                    ],
                ],
            ],
            'de_at' => [
                'general' => [
                    'country' => [
                        'default' => 'AT',
                        'destinations' => 'AT',
                    ],
                    'locale' => [
                        'code' => 'de_AT',
                    ],
                ],
            ],
            'it_it' => [
                'general' => [
                    'country' => [
                        'default' => 'IT',
                        'destinations' => 'IT',
                    ],
                    'locale' => [
                        'code' => 'it_IT',
                    ],
                ]
            ],
            'nl_nl' => [
                'general' => [
                    'country' => [
                        'default' => 'NL',
                        'destinations' => 'NL',
                    ],
                    'locale' => [
                        'code' => 'nl_NL',
                    ],
                ],
            ],
        ],
        ...
    ],
];
```

### Preconditions (*)

1. magento version 2.4.2

### Steps to reproduce (*)

1. Create 2 stores and one storeview for each store
2. Set different locale for each store, e.g. `de_DE` and `nl_NL` - not `en_US`
3. Create a config dump
4. Remove content from `env.php` file to make sure that the config is not loaded from the db
5. Run `bin/magento setup:static-content:deploy --force`

### Expected result (*)

1. Static files for the locales `de_DE` and `nl_NL` are generated

### Actual result (*)

1. Just the default locale `en_US` is generated

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment] 2021-06-23 06:00
Maybe you need manually config ! Even in cloud solution
https://devdocs.magento.com/cloud/env/variables-build.html#scd_matrix

**Comment by marvincaspar** [comment] 2021-06-23 06:11
I don't use the magento cloud, so I can't create the matrix. My understanding from the [documentaion page](https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-static-view.html#deploy_without_db) is, that I just need the config dump to generate the static files for all languages. I know I can add all languages to the command but I thought magento fetches the information from the config dump. All necessary information are in the dump.

**Comment by mrtuvn** [comment] 2021-07-03 13:59
![Screenshot from 2021-07-03 20-58-11](https://user-images.githubusercontent.com/1908873/124356675-66c36b00-dc41-11eb-8d30-62bc335354ac.png)
Tested in latest codebase with sampledata + 2 locale setup. As you can see magento deploy all languages that i have
I have install second locale (DE) at app/i18n/Mageplaza/de_DE

**Comment by engcom-Hotel** [comment] 2021-07-05 11:03
Hello @marvincaspar,

We have tried to reproduce this issue with Magento 2.4-develop branch. After following your mentioned steps, we are unable to reproduce the issue. We have followed below steps:
1. Setup fresh Magento 2.4-develop.
2. Create 2 stores + 1 store view for each stores.
3. Set locale as mentioned in the ticket description.
4. Create a config dump
5. Run bin/magento setup:static-content:deploy --force

We are getting below output from the above steps:

<img width="753" alt="Screenshot 2021-07-05 at 4 22 33 PM" src="https://user-images.githubusercontent.com/51681618/124461659-86c46d00-ddae-11eb-996a-f4bb0d503a59.png">

Please let us know, if we missed any steps to reproduce the issue.

Thanks

**Comment by engcom-Hotel** [comment] 2021-07-19 05:56
Hello @marvincaspar,

It seems that your issue has been resolved. We are not able to hear from you for the last 14 days. So we are closing this issue for now. If you are still facing the issue then you can reopen it.

Thanks

**Closed as completed by engcom-Hotel** 2021-07-19 05:56 UTC
Labels: Issue:  Cannot Reproduce, Component: Deploy, Issue: needs update, Reported on 2.4.2
