### ISSUE TITLE
Performance of products graphql query getting degraded in magento 2.4.2 version

### ISSUE THREAD

**Issue by rani-priya** [magento/magento2#32791] opened 2021-04-20 09:05 UTC
### Preconditions (*)

1. Magento version 2.4.0 and 2.4.2

### Steps to reproduce (*)

1. prepare two magento instances with 2.4.0 and 2.4.2 versions
2. compare the performance of products graphql query

### Expected result (*)

1. performance of products query should be not more than 2.4.0 version products query.

### Actual result (*)

Performance on Magento 2.4.0 version: 
![Screenshot-2 4 0](https://user-images.githubusercontent.com/44425160/115369102-63454980-a1e5-11eb-9f90-bf6d80c376bb.png)

Performance on Magento 2.4.2 version: 
![Screenshot-2 4 2](https://user-images.githubusercontent.com/44425160/115369118-6809fd80-a1e5-11eb-9fb7-43b47c0c15ba.png)

**1 sec** difference we can see..

I observed one code change which can impact on performance, Please check

https://github.com/magento/magento2/pull/30375#pullrequestreview-626051739

<!---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment] 2021-06-04 13:31
Hi @rani-priya,

Unfortunately, can't reproduce the issue.

I tested in magento-2.4.2-develop version. Please find the attached Screenshot for your reference.
<img width="1365" alt="Screenshot 2021-06-04 at 6 58 07 PM" src="https://user-images.githubusercontent.com/60198022/120808717-f7395d80-c566-11eb-9fd4-aefb3c774bff.png">

Hence, closing this ticket. Please feel free to open or create the new ticket if still you have any issue regards.

**Closed as completed by engcom-Lima** 2021-06-04 13:31 UTC
Labels: non-issue, Issue: ready for confirmation
