### ISSUE TITLE
Page Loading issue - Breaks Menu design

### ISSUE THREAD

**Issue by vishal6714** [magento/magento2#1076] opened 2015-03-04 10:02 UTC
Hello Team,

There seems menu design breaks for a longer time due to vary high page load time even there is a cache enabled and having simple product page.

Refer the mashup design of menu during page loading in Magento ver. 0.42.0-beta10.

![loading-issue](https://cloud.githubusercontent.com/assets/6058016/6481446/9546a8a4-c283-11e4-8e77-94d091646de9.png)

**Comment by vpelipenko** [comment] 2015-03-04 10:12
It is duplicate of #1045.

**Comment by vpelipenko** [comment] 2015-03-10 10:20
@vishal6714, this issue is closed as duplicate. Please, track status of #1045.

**Closed by vpelipenko** 2015-03-10 10:20 UTC
Labels: acknowledged, bug, CS
