### ISSUE TITLE
Set Generate "category/product" URL Rewrites to "no" has no effect

### ISSUE THREAD

**Issue by arhmart** [magento/magento2#38317] opened 2023-12-26 07:34 UTC
### Preconditions and environment

magento 2.4.7-beta2

### Steps to reproduce

1. Set in Catalog>Search Engine Optimization:
a. Set "Use Categories Path for Product URLs" to "NO"
b. Set "Generate "category/product" URL Rewrites" to "NO"
2. Add and save new product.

The url rewrite in the frontend works fine.
But under marketing>URL Rewrites, you can see that there are two url rewritten versions, one of is with category. 

### Expected result

Generate only one url, don't generate the url that with category.

### Actual result

Two urls are generated

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-12-28 08:14
Hi @arhmart,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- 在Catalog>Search Engine Optimization选项中设置:
- a. Set "Use Categories Path for Product URLs" to "NO"
- b. Set "Generate "category/product" URL Rewrites" to "NO"
- Add and save new product.

![Screenshot from 2023-12-28 12-34-47](https://github.com/magento/magento2/assets/51680745/67845715-d797-4a88-9899-b878e8f9e43f)





![Screenshot from 2023-12-28 12-28-11](https://github.com/magento/magento2/assets/51680745/8b4a88fd-f81f-46c4-89f4-0cfadc8c231d)


Only one Url is generated and there is no url with category.

Kindly refer this documents https://experienceleague.adobe.com/docs/commerce-admin/config/catalog/catalog.html?lang=en#search-engine-optimization and https://experienceleague.adobe.com/docs/commerce-admin/marketing/seo/meta-data.html?lang=en#canonical-meta-tag for URL rewrites.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by arhmart** [comment] 2023-12-28 08:38
@magento give me 2.4-develop instance

**Comment by arhmart** [comment] 2023-12-28 08:56
I tested it and determined that the problem was reproduced in 2.4-develop.
![11](https://github.com/magento/magento2/assets/84454905/8202864b-9df0-432f-8d82-f4c12d62c0b2)

**Comment by engcom-Bravo** [comment] 2023-12-29 06:18
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-12-29 06:39
Hi @arhmart,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- 在Catalog>Search Engine Optimization选项中设置:
- a. Set "Use Categories Path for Product URLs" to "NO"
- b. Set "Generate "category/product" URL Rewrites" to "NO"
- Add and save new product.

![Screenshot from 2023-12-29 12-07-03](https://github.com/magento/magento2/assets/51680745/4e5f76cf-fe89-4563-aaaf-172a9b53cf3d)


Two URL's were generated.

Hence Confirming the issue.

Thanks.

**Comment by sheepfy** [comment] 2024-08-22 06:43
Fixed here:
https://github.com/magento/magento2/pull/39071

**Comment by engcom-Bravo** [comment] 2024-08-22 06:48
@sheepfy Thanks for your contribution.

Hi @arhmart,

Similar issue has been confirmed here https://github.com/magento/magento2/issues/39070.

Hence we are closing this as duplicate.

Thanks.

**Closed as completed by engcom-Bravo** 2024-08-22 06:48 UTC
Labels: duplicate, Issue: Confirmed, Component: Url, Reproduced on 2.4.x, Priority: P3, Progress: done, Area: Catalog, Reported on 2.4.7-beta2

**Comment by cptX** [comment] 2025-02-15 10:59
Problem exists in 2.4.7-p3

**Comment by sheepfy** [comment] 2025-02-15 11:03
> Problem exists in 2.4.7-p3

@cptX check the 2.4.7-p4 release. Probably they included the fix in there already.

**Comment by cptX** [comment] 2025-02-15 11:17
@sheepfy I applied the change in the code manually. In the release notes of 2.4.7-p4 this is not reported... I don't know if they applied it there already

**Comment by hostep** [comment] 2025-02-17 16:55
Bugfixes typically don't make it in security releases, unless they are very critical.

Anyway, the bugfix lives here: https://github.com/magento/magento2/pull/38476 and still hasn't been approved or merged, so let's hope it will happen soon (give thumb ups on it to give it more priority). Hopefully soon enough to be included in Magento 2.4.8 in April, but I fear that it will be too late and we'll have to wait yet another year until Magento 2.4.9 comes along ...

**Comment by ihor-sviziev** [comment] 2025-04-22 15:56
Just for reference -  the issue was already fixed.
More details in https://github.com/magento/magento2/issues/39070#issuecomment-2821234297
