### ISSUE TITLE
[Issue] S3 incorrect option name (path-style)

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#38684] opened 2024-04-30 12:37 UTC
### Preconditions and environment

- Magento version 2.4.7

### Steps to reproduce

1. Configure a remote S3 that requires a path-style parameter

### Expected result

Remote storage is working correctly

### Actual result

Remote storage is not working

### Additional information

See https://github.com/magento/magento2/pull/32937

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2024-05-07 09:14
Hello @Nuranto,

Thanks for the report and collaboration!

We have tried to reproduce this issue in Magento 2.4.7 and in the latest development branch but the issue is not reproducible for us.

We used `MINIO`, for issue reproduction as it has a default set use `path-style`. After setting up the `MINIO` in the Magento instance tried to upload an image in Product by editing it and the image is successfully uploaded on `MINIO`. We have verified it from the Web UI.

Please have a look into the below env.php entry for remote storage:
```
'remote_storage' => [
        'driver' => 'aws-s3',
        'config' => [
            'endpoint' => 'http://127.0.0.1:9000',
            'bucket' => 'magento247',
            'region' => 'us-east-1',
            'path_style' => true,
            'use_path_style_endpoint' => true,
            'credentials' => [
                'key' => 'KEY',
                'secret' => 'SECRET'
            ]
        ]
    ],
```

Let us know if we missed anything.

Thanks

**Comment by Nuranto** [comment] 2024-05-13 07:31
Hello @engcom-Hotel,

The configuration you used would result with command line option : `--remote-storage-path_style=1` which does not match what's expected  : 

https://github.com/magento/magento2/blob/7e0e5582aa46ab94ed86398237d1373c71604c90/app/code/Magento/RemoteStorage/Setup/ConfigOptionsList.php#L40

Note : The documentation (https://experienceleague.adobe.com/en/docs/commerce-operations/configuration-guide/storage/remote-storage/remote-storage) has not been updated with new options.

**Comment by engcom-Hotel** [comment] 2024-05-30 05:47
Dear @Nuranto,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we're assuming it's been resolved and will be closing it. Feel free to open a new ticket or reopen this one if you require further assistance.

Regards

**Closed as completed by engcom-Hotel** 2024-05-30 05:47 UTC
Labels: Issue: needs update, Reported on 2.4.7

**Comment by tdgroot** [comment] 2025-02-11 12:03
> Hello [@tdgroot](https://github.com/tdgroot),
> 
> Have you tried the configuration shown in this [#38684 (comment)](https://github.com/magento/magento2/issues/38684#issuecomment-2109826175)? Please let us know if this helps in issue resolution.
> 
> If not then we will reopen this issue for further processing.
> 
> Thanks

Yeah this works, but the problem is that the `--remote-storage-path-style` option does not configure Magento correctly (it writes `path-style` instead of `path_style`). Or you can transpose the problem statement: the `AwsS3Factory` does not parse the `remote_storage` config correctly (it reads `path_style` instead of `path-style`).
