### ISSUE TITLE
Error Elasticsearch table prefix

### ISSUE THREAD

**Issue by mohammedTBB** [magento/magento2#36741] opened 2023-01-13 09:55 UTC
### Preconditions and environment

- Magento version 2.4.5-p1
- magento/module-elasticsearch version 101.0.5

### Steps to reproduce

1- Go to category page
2- Filter by price

### Expected result

The page filter the products without any error.

### Actual result

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.store' doesn't exist

### Additional information

The problem comes from the file 
vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php:263

**Possible solution:**
**replace the line 260** 
. ' AND price_index.website_id = (Select website_id FROM store WHERE store_id = '
**by:** 
. ' AND price_index.website_id = (Select website_id FROM '. $this->collection->getTable('store') .' WHERE store_id = '

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-01-13 11:59
Hi @mohammedTBB,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible. Kindly refer the screenhsots.



We are able to filter the products with the price without any errors.


<img width="1487" alt="Screenshot 2023-01-13 at 3 39 38 PM" src="https://user-images.githubusercontent.com/51680745/212315285-a044b20f-81ab-42a9-8bc7-240a7d119228.png">



Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-01-16 10:09
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-01-16 10:21
Hi @mohammedTBB,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible. Kindly refer the screenhsots.

We are able to filter the products.



<img width="1467" alt="Screenshot 2023-01-16 at 3 36 06 PM" src="https://user-images.githubusercontent.com/51680745/212654944-962f5df0-8421-4f86-bcc4-320170c8ded6.png">



Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.


Thanks.

**Comment by mohammedTBB** [comment] 2023-01-16 11:59
Hi [engcom-Bravo](https://github.com/engcom-Bravo)

Could you please sort by 'price' instead of by 'position'?
If this does not do the trick we will check our third-party plugins. 

Thanks.

**Comment by hostep** [comment] 2023-01-29 12:19
This seems to be a similar problem as reported in https://github.com/magento/magento2/issues/36518

@mohammedTBB: The code you referenced has been refactored significantly and this refactor will be included in Magento 2.4.6 and your issue should be fixed when it gets released on [March 14](https://experienceleague.adobe.com/docs/commerce-operations/release/planning/schedule.html). I've mentioned some details over here: https://github.com/magento/magento2/pull/36478#issuecomment-1365282673

This issue can probably be closed now.

**Comment by engcom-Bravo** [comment] 2023-01-30 06:14
Hi @hostep.

Thanks for your update.

We are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2023-01-30 06:14 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1
