### ISSUE TITLE
Magento for sync product API not working in first attempt

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#33873] opened 2021-08-20 13:18 UTC
### Preconditions (*)

1. Magento version : 2.4.2
2.

### Steps to reproduce (*)

1.Call the api URLfor sync product : https://doorcloser.com/rest/V1/products/base-prices
Post Data : {"prices": [{"price": 72.29,"store_id": 1,"sku": "170A36"}]}
2.Now download product individual with URL
https://doorcloser.com/rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=sku&searchCriteria[filter_groups][0][filters][0][value]=170A36&searchCriteria[filter_groups][0][filters][0][condition_type]=in

Request and response
[Magento API Request Response (1).txt](https://github.com/magento/magento2/files/7021695/Magento.API.Request.Response.1.txt)

### Expected result (*)

1. expected result in price 72.29 but getting 35.29
2.

### Actual result (*)

1. In the first attempt it sync wrong price and in another attempt its working fine.
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [()] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment] 2021-08-23 14:39
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment] 2021-08-25 07:58
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment] 2021-08-25 12:42
Hi @webgility-amazonapi 
I tried to reproduce this on **2.4-develop** branch & was unable to do so.
Here are the steps followed.
1. On a fresh instance of magento 2.4-develop, Generate Admin access token using POST request: `/rest/default/V1/integration/admin/token`
2. Send a POST request to Add or update product prices: `/rest/default/V1/products/base-prices`
```
{
   "prices": [
        {
            "price": 120,
            "store_id": 1,
            "sku": "24-MB05"
        }
   ]
}
```

3. Hit the below GET request:
`rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=sku&searchCriteria[filter_groups][0][filters][0][value]=24-MB05&searchCriteria[filter_groups][0][filters][0][condition_type]=in`
Got the price on response as 120 (on the first attempt itself), which is **expected**.

So kindly recheck this issue on Magento **2.4-develop** branch and if the issue is still reproducible, please provide more details or additional/missing steps regarding the same.

Thank you.

**Comment by webgility-amazonapi** [comment] 2021-08-31 05:59
Dear engcom-Echo

Our customer is facing issue in  Magento version : 2.4.2. Can you please test in this specific version? Or can you tell us the latest version where it is working fine and we can ask customer to upgrade to the specific version?

Thanks,
Webgility

**Comment by webgility-amazonapi** [comment] 2021-09-01 07:47
is there any update?
Customer is in panic mode

**Comment by engcom-Echo** [comment] 2021-09-14 05:38
Hi @webgility-amazonapi 
First and foremost apologies for the delayed response.
We have checked the aforementioned issue on **2.4-develop** branch, wherein its working perfectly fine (can be inferred from my previous comment). There can be a possibility that it might have been an issue in some previous versions & might have got fixed by some PR merges. However as this is not a reproducible issue on 2.4-develop branch, you can find the functionality working as expected on our next 2.4.x release version.
Thank you.

**Comment by engcom-Hotel** [comment] 2021-09-29 14:27
Dear @webgility-amazonapi,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2021-09-29 14:27 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
