### ISSUE TITLE
var/resource_config.json is regenerated each time an image is requested by get.php (media/wysiswig/image.jpg)

### ISSUE THREAD

**Issue by lpouwelse** [magento/magento2#24445] opened 2019-09-04 12:59 UTC
### Preconditions (*)
1. Magento version 2.3.1

### Steps to reproduce (*)
1. Fresh install of magento with sample data
2. Synchronize media files to datase, according the manual (https://docs.magento.com/m2/ce/user_guide/system/media-storage-database.html)
3. Add following record to core_config_data table 
    - scope: default
    - scope_id: 0 
    - path: web/seo/use_rewrites
    - value: 1
4. Remove an image from media/wysiwyg editor directory (so the get.php is called)
5. Start a debug session
6. Put a break-point at App/Media.php on line
`if ($this->mediaDirectoryPath !== $this->directory->getAbsolutePath()) {`
7. Inspect variables$this->mediaDirectoryPath and $this->directory->getAbsolutePath()

### Expected result (*)

1. Skipping building var/resource_config.json if exists and directory is the same

### Actual result (*)

1. var/resource_config.json is rebuilded every time

**Comment by magento-engcom-team** [comment] 2019-09-05 08:43
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19878` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hostep** [comment] 2020-08-26 07:35
This is probably fixed by [MC-32593: var/resource_config.json is regenerated each time an image is requested by get.php](https://github.com/magento/magento2/commit/1808301b9f9), this seems to be included in Magento 2.4.0
Can somebody confirm?

**Closed as completed** 2020-10-29 10:31 UTC
Labels: Issue: Clear Description, Issue: Format is valid, Component: MediaStorage, Triage: Dev.Experience, Fixed in 2.4.x, Priority: P2, Severity: S2, Progress: done

**Comment by sdzhepa** [comment] 2020-10-29 15:03
@lpouwelse @hostep 

Related internal Jira tickets `MC-19878` and `MC-24054` have been closed as 
> Cannot Reproduce on 2.4.1 version
For some reason bot did not leave a comment here..just closed...

Also, as mentioned in https://github.com/magento/magento2/issues/24445#issuecomment-680713098
internal ticket with the same title `MC-32593: var/resource_config.json is regenerated each time an image is requested by get.php` has beed delivered. Based on JIra `Fix Version/s: 2.4.0`

@engcom-Charlie could you please re-check it on the latest code? 
Confirm with a comment if its fixed or re-open it and confirm again.

**Comment by engcom-Charlie** [comment] 2020-10-30 14:04
@sdzhepa the issue isn't reproducible on the latest 2.4-develop.
Was fixed https://github.com/magento/magento2/commit/1808301b9f9

**Comment by engcom-Charlie** [comment] 2020-10-30 14:05
@sdzhepa the issue isn't reproducible on the latest 2.4-develop.
Was fixed by https://github.com/magento/magento2/commit/1808301b9f9
