### ISSUE TITLE
Overlay after click "OK" on alert

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#25897] opened 2019-12-04 10:17 UTC
### Preconditions (*)

1. Adobe Stock is configured (optional for now)
2. M 2.3.3
### Steps to reproduce (*)

1. On CMS edit page open media gallery
2. Click "Create Folder"
3. Type in "папка"
4. Click "OK"
5. When alert with a message "Please rename the folder using only letters, numbers, underscores and dashes." appears, click "OK"

### Expected result (*)

1. I can create another folder using only letters, numbers, underscores and dashes.

### Actual result (*)

1. The overlay
![image](https://user-images.githubusercontent.com/11827230/70134014-e406b280-168f-11ea-97ba-a5e0abf6d367.png)

**Comment by engcom-Echo** [comment] 2019-12-04 13:34
Hello @TomashKhamlai 

I am not able to reproduce this issue on the 2.3-develop branch by provided steps.

**Testing scenario:**

**Steps to reproduce:**

1. On CMS edit page open media gallery
2. Click "Create Folder"
3. Type in "папка"
4. Click "OK"
5. When alert with a message "Please rename the folder using only letters, numbers, underscores and dashes." appears, click "OK"

**Result**
I can create another folder using only letters, numbers, underscores and dashes.
So I have to close this issue.

**Closed by engcom-Echo** 2019-12-04 13:34 UTC
Labels: Component: MediaGallery, Issue: Format is valid

**Comment by TomashKhamlai** [comment] 2019-12-04 13:44
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-12-04 13:44
Hi @TomashKhamlai. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-12-04 13:44
Hi @TomashKhamlai, here is your [Magento instance](https://i-25897-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25897-2-3-develop.instances.magento-community.engineering/admin](https://i-25897-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by TomashKhamlai** [comment] 2019-12-04 13:54
On Vanilla Magento overlay doesn't stuck.
![ePeek 2019-12-04 15-52](https://user-images.githubusercontent.com/11827230/70148107-3656cc00-16ae-11ea-80de-bc542e5210ac.gif)
