### ISSUE TITLE
An email “Welcome to the main website” is sent to inactive customers

### ISSUE THREAD

**Issue by ZhovnirMaria** [magento/magento2#33255] opened 2021-06-16 08:40 UTC
### Preconditions (*)
Magento version 2.4.2

### Steps to reproduce (*)
1. On the Admin sidebar, go to _Customers_ > _All Customers_.
2. Add new customer, click **Add New Customer**
3. Fill in all required fields and set **Customer Active** to **NO**
4. When complete, click **Save**

### Expected result (*)
The "Welcome to the main website" email is not sent to inactive customers.

### Actual result (*)
An email “Welcome to the main website” is sent to inactive customers.

Please find more details about the issue below:
https://github.com/magento/magento2/issues/33255#issuecomment-864933043
<img width="1333" alt="Screenshot 2021-06-16 at 11 05 50" src="https://user-images.githubusercontent.com/79835574/122186945-36d14500-ce97-11eb-8ae7-5a52ad559ea2.png">
<img width="1120" alt="Screenshot 2021-06-16 at 11 11 19" src="https://user-images.githubusercontent.com/79835574/122186951-39339f00-ce97-11eb-9c6c-2fe473f7daf1.png">
<img width="1098" alt="Screenshot 2021-06-16 at 11 11 47" src="https://user-images.githubusercontent.com/79835574/122186956-3a64cc00-ce97-11eb-8f87-87441dfb7584.png">

**Comment by engcom-November** [comment] 2021-06-21 10:46
Verified the issue on latest Magento version 2.4.2 and the issue is reproducible.
**Preconditions:**
B2B Features - enabled
Setup Email configuration
**Steps to reproduce:**
1. Navigate to Customers -> All Customers -> Add new Customer
2. Create Inactive customer
Issue: Welcome Email is triggered to customer email with password link and user is able to create password from the link.
Expected behavior: Inactive customers should not be able to login or reset password. Hence email should not be triggered with password reset link.
![image](https://user-images.githubusercontent.com/60198231/122750122-c61d9480-d2ab-11eb-87cd-f747032ea2c6.png)
![image](https://user-images.githubusercontent.com/60198231/122750353-054be580-d2ac-11eb-9eae-f2f12b7388db.png)

![image](https://user-images.githubusercontent.com/60198231/122750089-ba31d280-d2ab-11eb-9466-b25b0d560f98.png)

**Comment by SilinMykola** [comment] 2021-06-28 10:51
@magento I am working on this

**Comment by magento-engcom-team** [comment] 2021-07-01 13:48
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42768` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by srivats-ey** [comment] 2021-08-25 09:18
@magento-engcom-team assign this to me

**Comment by engcom-Bravo** [comment] 2024-06-20 06:03
Hi @ZhovnirMaria,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance with EE edition and the issue is no more reproducible.Kindly refer the screenshots.

<img width="1338" alt="Screenshot 2024-06-20 at 11 28 52" src="https://github.com/magento/magento2/assets/51680745/d0a87991-e443-4326-a7c7-e4ea061e973a">


<img width="1415" alt="Screenshot 2024-06-20 at 11 28 27" src="https://github.com/magento/magento2/assets/51680745/38cae8a4-8a15-459f-aee3-0ed589bbd49f">



We are not getting any Welcome emails for inactive customers.

Hence we are closing this issue.

Thanks

**Closed as completed by engcom-Bravo** 2024-06-20 06:03 UTC
Labels: Component: Customer, Issue: Confirmed, Component: Email, Reproduced on 2.4.x, Priority: P3, Progress: done, Reported on 2.4.2
