### ISSUE TITLE
magento2.1.7 checkout Region field sometimes above other fields in billing form

### ISSUE THREAD

**Issue by wangqingshen** [magento/magento2#12979] opened 2018-01-04 08:50 UTC
Preconditions

Magento 2.1.7
Steps to reproduce

Proceed to checkout.
Proceed to billing step.
Re-iterate this process a few times.
Expected result

The fields are consistently in the same location each time.
Actual result

The county field is shown above the first name field on occasional page reloads. This would appear to be a JS race condition, see below.
This is a duplicate of #5849 which was closed down without being fixed. That ticket complained about the sort order generally not having the desired effect within the checkout, so that may or not be related to this problem. I left a comment on that ticket as follows:

This is still an issue for me on 2.1.7. I've have taken a look at debugging the issue it seems to be a race condition.

**Comment by wangqingshen** [comment] 2018-01-04 09:09
@ magento-engcom-team， hi, I also met this problem in the 2.1.7 version, Can you help me with it?

**Comment by magento-engcom-team** [comment] 2018-01-04 12:13
@wangqingshen We tried to reproduce, the issue on 2.1.11, and 2.2.2, we tried with Guest and Customer account addresses, and we weren't able to reproduce it. Seems like it's been fixed in this versions. In this case, we would recommend trying to update and see if it helps. Unfortunately, we are not able to help you with this unless we can reproduce it. If upgrading won't fix the problem, please try to reproduce on the clean instance of Magento or please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

**Comment by magento-engcom-team** [comment] 2018-01-04 12:16
@wangqingshen, thank you for your report.
The issue is already fixed in 2.2.2

**Closed as completed by magento-engcom-team** 2018-01-04 12:16 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Fixed in 2.2.x, Issue: Format is valid
