### ISSUE TITLE
Unable to edit Minimum Height value of a Banner with Page builder after Magento upgrade

### ISSUE THREAD

**Issue by mrkimmok** [magento/magento2#31389] opened 2020-12-22 10:55 UTC
### Preconditions (*)

Magento Enterprise Edition 2.3.6 ("magento/product-enterprise-edition": "2.3.6") upgraded from version 2.3.2 using composer. PHP version is 7.2.28

### Steps to reproduce (*)

1. Magento succesfully upgraded from version 2.3.2 (Enterprise Edition) to 2.3.6 (Enterprise Edition)
2. After upgrade, go to: "Content > Pages > Open Content tab and edit a Banner element
3. Edit Banner Minimum Height setting by entering only a number, for example: 574
4. Edit Banner Minimum Height setting by entering number with px, for example: 574px

### Expected result (*)

1. Both 3 and 4 should be validated without errors.

### Actual result (*)

1. Actual result for 3: validation gives the following error:
`Please enter a valid number or calculation: Valid numbers must have an extension (px, %, pt, vh). Calculations must have white space around the + and - operators and cannot divide by zero.`
![image](https://user-images.githubusercontent.com/54927315/102880873-acaea380-4454-11eb-8c83-2b3094dd7319.png)

2. Actual result for 4: validation gives the following error:
`Please enter a valid number in this field.`
![image](https://user-images.githubusercontent.com/54927315/102880819-9acd0080-4454-11eb-908f-b6f0c5e36bbf.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dverkade** [comment] 2021-03-17 15:34
Ready for confirmation issues can't be closed automatically.

**Comment by engcom-Oscar** [comment] 2021-03-30 13:36
Hi @ambkimmok  ! Thank you for your report.
Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop by following steps from this ticket.

**Actual Result:** :heavy_check_mark: 
![Screenshot from 2021-03-30 16-35-57](https://user-images.githubusercontent.com/60198413/112997743-0c180000-9176-11eb-98ee-f27ad6c56980.png)

So, we have to close this ticket.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch.
 Thank you for collaboration.

**Closed as completed by engcom-Oscar** 2021-03-30 13:36 UTC
Labels: Issue: ready for confirmation, not-confirmed
