### ISSUE TITLE
Error at Theme switing in Megento.2.2.4 and 2.2.5

### ISSUE THREAD

**Issue by hmedasani** [magento/magento2#17076] opened 2018-07-24 15:56 UTC
### Preconditions

1.  PHP-7.1.12
2.  MySql-5.6.38
3.  Magento version 2.2.4 (E.E)

### Steps to reproduce

1.  Place your custome theme in app/design/frontend/yourThemeFolder
2.  Now, go to Admin and navigate to Content/configuration/
3.  Press on edit button to change the default theme
4.  Change the theme you desired

### Expected result

1. [Success message appears]

### Actual result

1. [Something went wrong while saving this configuration: Area is already set]

**Comment by magento-engcom-team** [comment] 2018-07-24 15:56
Hi @medasah. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@medasah do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by hostep** [comment] 2018-07-24 16:06
@medasah: this has already been reported a couple of times, fix will be delivered in Magento 2.2.6.
If you can't wait for that, find the official patch over here: https://magento.com/tech-resources/download (search for 'MAGETWO-93036').

Closing this as duplicate of https://github.com/magento/magento2/issues/14968

**Closed as completed by hostep** 2018-07-24 16:06 UTC
Labels: Issue: Format is valid
