### ISSUE TITLE
Missing class in develop branch (Media.php)

### ISSUE THREAD

**Issue by mudithae** [magento/magento2#2790] opened 2015-12-22 17:17 UTC
Got  Class Magento\Catalog\Model\ResourceModel\Product\Attribute\Backend\Media does not exist. Found out that in develop branch it is missing. please do the needful.

**Comment by davidalger** [comment] 2015-12-23 15:38
@mudithae Can you provide a full stack-trace for this error and also details on your environment and what steps you went through to install the software?

**Comment by jedjebari** [comment] 2016-01-02 19:35
Hi
I got the same issue installing sampleData
magento sampledata:deploy is successful but magento setup:upgrade fails : 
Module 'Magento_CatalogSampleData':

  [ReflectionException]  
  Class Magento\Catalog\Model\ResourceModel\Product\Attribute\Backend\Media does not exist  

  [ReflectionException]  
  Class Magento\Catalog\Model\ResourceModel\Product\Attribute\Backend\Media does not exist  

And there's no Media.php : 
-bash-4.3$ ls app/code/Magento/Catalog/Model/ResourceModel/Product/Attribute/Backend/
GroupPrice/    Image.php      Tierprice.php 

For information I had to add this in my composer.json to make deploy work : 
   "repositories": [
        {
            "type": "composer",
            "url": "http://packages.magento.com/"
        }
    ]

**Comment by mudithae** [comment] 2016-01-04 16:19
Hi @davidalger,

Sorry for delay in reply. I have missed your previous email somehow.

Yes, for me also it occurs when I install the sample data (Install the Magento first Sample data next). 

Still I can see that in branch 2.0 below is exists but not in develop branch.
magento2/app/code/Magento/Catalog/Model/ResourceModel/Product/Attribute/Backend/Media.php

Regards,
Muditha

**Comment by rajeev-k-tomy** [comment] 2016-01-20 07:52
Hey, I am getting same error when I am trying to install with sample data. In my case, I have already install sample-data using the command `magento sampledata:deploy` and then tried to install magento2  like `magento setup:install --use-sampledata`, but leads to the same error. 

I checked and that file is not there. Also I have following configuration in my `composer.json`

```
"repositories": [
{
     "type": "composer",
     "url": "http://packages.magento.com/"
}
```

What should I do in this case ?

**Comment by katmoon** [comment] 2016-01-22 16:28
Thank you all for your contribution.
Internal ticket has been created: `MAGETWO-47646`

**Comment by mslabko** [comment] 2016-01-22 16:42
Hello @mudithae, @jedjebari 
Try to setup Sample Data from GitHub: https://github.com/magento/magento2-sample-data#deploy-sample-data-from-github-repository
Or if you want to setup with composer you need to set correct version for Sample Data package

Note, that for stable version for example  2.0.1 you can simple run bin/magento sampledata:deploy command

**Comment by ghost** [comment] 2016-01-22 17:09
Hi all, documentation should be updated soon. I have had this issue as well. Meanwhile, you should be able to use this [readme](https://github.com/magento/magento2-sample-data#deploy-sample-data-from-github-repository) which is in the sample data GitHub repo.

**Comment by mudithae** [comment] 2016-01-24 13:07
Hi All,

Thanks for your contribution to resolve this. I think with the @katmoon, @mslabko and @xcomSteveJohnson replies I can consider this this as solved.

Regards,
Muditha

**Comment by pantaoran** [comment] 2016-03-29 02:19
I also have this problem. Why did you close this issue @mudithae ?
Sure, maybe the alternative method to install sample data works, but that does not mean that the issue is fixed, it's only a workaround. This is a documented method and it does not work, so there should be an open issue about it.

I want to use this method. It's much more convenient for automated installations. The documentation says this works. But it fails. Please fix it!

**Comment by mudithae** [comment] 2016-03-29 18:26
Hi @pantaoran,

Your point is valid. I will reopen the issue.

Regards,
Muditha

**Comment by Vinai** [comment] 2016-05-18 08:24
BTW, as a quick and hacky workaround, copying the [`Media.php` file from the `2.0` branch](https://github.com/magento/magento2/blob/2.0/app/code/Magento/Catalog/Model/ResourceModel/Product/Attribute/Backend/Media.php) during the installation of the sample data, works.

**Comment by pantaoran** [comment] 2016-05-19 03:22
But I don't want quick and hacky workarounds, I want sustainable solutions so that I don't need to worry about it in the future.

**Comment by Vinai** [comment] 2016-05-19 05:52
@pantaoran 
First, I added that comment for others mainly who might stuble over this thread via google.  
Second, the issue is already solved: once the release version of Magento matches the stable version of the sample data, sample data installation will work again without th `Media.php` file being present.

However, if you happen to be using a git repository clone as your Magento 2 installation (which is not recommended for project setups), and haven't checked out the proper version tag, you can still use the workaround by copying the file from the 2.0 branch, so you aren't forced to upgrade your installation just to get the sample data installed.

**Comment by BenGlassAtlas** [comment] 2016-05-19 18:19
That did the trick, thanks @Vinai

**Comment by magento-engcom-team** [comment] 2017-10-19 14:30
@mudithae, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Closed as completed** 2017-11-01 03:16 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, non-issue, Issue: Format is not valid
