### ISSUE TITLE
Error DOB field with Locale PT

### ISSUE THREAD

**Issue by mohammedTBB** [magento/magento2#34130] opened 2021-09-20 15:48 UTC
### Preconditions (*)

1. Fresh Magento 2.4.3
2. Set store-view locale to Portuguese(Portugal)

### Steps to reproduce (*)
Admin - Stores - Configuration - General - Locale Options - Set Locale to Portuguese(Portugal) and Save
Reindex and clear cache
Fornt-end - Create Account
Add DOB in customer create
GO to customer/account/create/

Expected result (*)

![magento-DOB](https://user-images.githubusercontent.com/66772877/134031393-ab703297-2465-4ab9-9781-956d45336950.png)

Actual result (*)

**The actual page:**

![Magento-error](https://user-images.githubusercontent.com/66772877/134032212-84ea8959-2a30-4a2c-bbec-69a1c99e199f.png)

**System.log Error:**

`main.CRITICAL: TypeError: Argument 1 passed to iterator_to_array() must implement interface Traversable, null given in /var/www/html/magento2/vendor/magento/module-customer/Block/Widget/Dob.php:425
Stack trace:
#0 /var/www/html/magento2/vendor/magento/module-customer/Block/Widget/Dob.php(425): iterator_to_array()
#1 /var/www/html/magento2/vendor/magento/module-customer/view/frontend/templates/widget/dob.phtml(27): Magento\Customer\Block\Widget\Dob->getTranslatedCalendarConfigJson()
#2 /var/www/html/magento2/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/var/www/html/m...')
#3 /var/www/html/magento2/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php->render()
#4 /var/www/html/magento2/vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView()
#5 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(1114): Magento\Framework\View\Element\Template->_toHtml()
#6 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(1118): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#7 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(678): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#8 /var/www/html/magento2/vendor/magento/module-customer/view/frontend/templates/form/register.phtml(58): Magento\Framework\View\Element\AbstractBlock->toHtml()
#9 /var/www/html/magento2/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/var/www/html/m...')
#10 /var/www/html/magento2/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php->render()
#11 /var/www/html/magento2/vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView()
#12 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(1114): Magento\Framework\View\Element\Template->_toHtml()
#13 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(1118): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#14 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(678): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#15 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#16 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#17 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#18 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#19 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#20 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#21 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#22 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#23 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#24 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#25 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#26 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#27 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#28 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#29 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#30 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#31 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#32 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#33 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#34 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#35 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#36 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout->renderElement()
#37 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#38 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent()
#39 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#40 /var/www/html/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout\Interceptor->___callPlugins()
#41 /var/www/html/magento2/vendor/magento/framework/View/Result/Page.php(260): Magento\Framework\View\Layout\Interceptor->getOutput()
#42 /var/www/html/magento2/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render()
#43 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult()
#44 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent()
#45 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}()
#46 /var/www/html/magento2/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(23): Magento\Framework\View\Result\Page\Interceptor->___callPlugins()
#47 /var/www/html/magento2/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult()
#48 /var/www/html/magento2/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#49 /var/www/html/magento2/pub/index.php(29): Magento\Framework\App\Bootstrap->run()`

---
- [] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by tyago343** [comment] 2021-09-20 16:04
Im still got this error in magento 2.4.3

**Comment by engcom-November** [comment] 2021-09-21 08:35
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
Steps to reproduce:
Admin - Stores - Configuration - General - Locale Options - Set Locale to Portuguese(Portugal) and Save
Reindex and clear cache
Fornt-end - Create Account
**Issue: UI page is broken**
![image](https://user-images.githubusercontent.com/60198231/134138877-bda873a4-7130-4d16-acf5-1dad8a95c621.png)

var/log/debug.log:
[2021-09-21 08:29:21] main.CRITICAL: TypeError: Argument 1 passed to iterator_to_array() must implement interface Traversable, null given in /var/www/html/magento2.4/magento2/app/code/Magento/Customer/Block/Widget/Dob.php:425

**Comment by AZiniukhin** [comment] 2021-09-21 11:11
@magento I am working on this

**Comment by sidolov** [comment] 2021-11-21 02:32
Hi @mohammedTBB. Thank you for your report. 
The issue has been fixed in magento/magento2#34148 by @AZiniukhin in 2.4-develop branch
Related commit(s):
 - [b605562fabb6ac9b434b1fddd3b40f3610e7795e](https://github.com/magento/magento2/commit/b605562fabb6ac9b434b1fddd3b40f3610e7795e)
 - [6d1468cb5f4611a65c59c270d8c1430440fe06df](https://github.com/magento/magento2/commit/6d1468cb5f4611a65c59c270d8c1430440fe06df)
 - [4ba1b37699daba9489c21efda1a00f0bfb30f08d](https://github.com/magento/magento2/commit/4ba1b37699daba9489c21efda1a00f0bfb30f08d)
 - [419bcf512152b287bf8faec6520bf419536a5f82](https://github.com/magento/magento2/commit/419bcf512152b287bf8faec6520bf419536a5f82)
 - [d7a8fdca0cd2f5fbebdcc86fa041ef714cad19e4](https://github.com/magento/magento2/commit/d7a8fdca0cd2f5fbebdcc86fa041ef714cad19e4)

The fix will be available with the upcoming release.

**Closed as completed by sidolov** 2021-11-21 02:32 UTC
Labels: Component: Customer, Issue: Confirmed, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P2, Progress: done, Reported on 2.4.3, Area: Account
