### ISSUE TITLE
Free Shipping Cart rule conflict with Free Shipping Method

### ISSUE THREAD

**Issue by baltechies** [magento/magento2#10494] opened 2017-08-11 11:18 UTC
### Preconditions
Magento version is 2.1.7 and PHP version is PHP 7.

### Description
I have setup free shipping cart price rule with specific coupon and also enabled free shipping module as well with minimum order amount $100. But when I applied the coupon code in cart page then Free Shipping module is showing even if order amount is less than $100, which is fine. But when I removed(cancel) the coupon code then Free Shipping method still there. Its still showing even if cart amount is less than $100.
 

### Steps to reproduce
1. Create Cart Price rule for free shipping without any limit, but with Specific Coupon Code.
2. Enable Free Shipping Method by set minimum order amount ($100 etc.)
3. Add product to cart and cart total should be less than $100.
4. Apply coupon at checkout cart page.

### Expected result
1.  Show Free shipping methods and add 0 amount to available free shipping method on apply cart.
2.  Should hide Free Shipping method on cancel coupon code.

### Actual result
1.  Show Free shipping methods and add 0 amount to available free shipping method on apply cart.
2. Still showing Free Shipping method on cancel coupon code.

![screen shot 2017-08-11 at 4 46 01 pm](https://user-images.githubusercontent.com/13519944/29211135-dd1c621e-7eb4-11e7-84c2-6a10a0a54a04.png)

**Comment by baltechies** [comment] 2017-08-16 07:56
any update on this issue?

**Comment by magento-engcom-team** [comment] 2017-10-11 19:03
@baltechies, thank you for your report.
The issue is already fixed in 2.1.8

**Closed as completed by magento-engcom-team** 2017-10-11 19:03 UTC
Labels: bug report, Issue: Clear Description, Issue: Confirmed, Fixed in 2.1.x, Issue: Format is valid
