### ISSUE TITLE
[GraphQL] related, upsell and crosssell products query ignoring the position they were saved in

### ISSUE THREAD

**Issue by MarianNapi** [magento/magento2#36461] opened 2022-11-11 10:59 UTC
### Preconditions and environment

- Magento version 2.4.5

### Steps to reproduce

1. Create a product
2. add other products as related, upsell or crosssell products and sort them in a random order
3. Request these fields via the GraphQl API

### Expected result

The related, upsell and crosssell products should be returned in the specific order they were saved in.

### Actual result

The related, upsell and crosssell products are returned sorted by their actual product entity_id.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by MarianNapi** [comment] 2022-11-11 11:03
@magento give me 2.4-develop instance

**Comment by MarianNapi** [comment] 2022-11-11 11:11
I can reproduce the issue on a vanilla magento instance with version 2.4-develop

**Comment by engcom-Bravo** [comment] 2022-11-14 08:18
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-14 11:33
Hi @MarianNapi,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.


**Steps to reproduce**
1.Create a product
2.add other products as related, upsell or crosssell products and sort them in a random order
3.Request these fields via the GraphQl API



The related, upsell and crosssell products are returned sorted by their actual product entity_id.


![Simple-Products-Inventory-Catalog-Magento-Admin](https://user-images.githubusercontent.com/51680745/201649369-1afc8670-fe39-47f9-a159-fd678331d962.png)




<img width="1395" alt="Screenshot 2022-11-14 at 2 54 12 PM" src="https://user-images.githubusercontent.com/51680745/201649449-dd7c130e-1474-4c34-a269-f3311ba6fc7d.png">




Hence Confirming the issue.

Thanks.

**Comment by engcom-Hotel** [comment] 2022-11-15 11:26
@engcom-Bravo We need to check this functionality in the frontend as well. So well reverify it and let us know the outcome here.

**Comment by engcom-Bravo** [comment] 2022-11-15 13:13
Hi @MarianNapi,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.

**Steps to reproduce**

1.Create a product
2.add other products as related, upsell or crosssell products and sort them in a random order
3.Request these fields via the GraphQl API


![graph](https://user-images.githubusercontent.com/51680745/201927684-936d932c-2540-4b3c-8b62-389ed4bd5583.png)


The related, upsell and crosssell products are returned sorted by their actual product entity_id.



<img width="1444" alt="Screenshot 2022-11-15 at 6 38 28 PM" src="https://user-images.githubusercontent.com/51680745/201927761-638393cc-7364-4bc6-b874-593c98c16f2f.png">



<img width="520" alt="Screenshot 2022-11-15 at 6 38 35 PM" src="https://user-images.githubusercontent.com/51680745/201927781-ce6e7a39-73e7-4f96-8d9a-21d5ce335f0e.png">




In Frontend it is working Fine as per product configuration.



<img width="883" alt="Screenshot 2022-11-15 at 6 03 36 PM" src="https://user-images.githubusercontent.com/51680745/201927975-7bd67eaa-58ad-4a56-932e-d4e53793c8d6.png">



<img width="864" alt="Screenshot 2022-11-15 at 6 04 03 PM" src="https://user-images.githubusercontent.com/51680745/201928006-619df26d-6d5c-4e41-b2a2-6d8206d0cace.png">





Hence confirming this issue.


Thanks.

**Comment by Vasudev-22** [comment] 2022-11-15 14:33
@magento I am working on this

**Comment by engcom-Bravo** [comment] 2023-05-09 11:02
Hi @MarianNapi,

Verified the issue on Magento 2.4-develop instance and the issue is no longer reproducible.Hence we are closing this issue.


Thanks.

**Closed as completed by engcom-Bravo** 2023-05-09 11:02 UTC
Labels: Issue: Confirmed, Component: GraphQL, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Product, Reported on 2.4.5

**Comment by MarianNapi** [comment] 2023-05-10 09:30
https://github.com/magento give me 2.4-develop instance

**Comment by MarianNapi** [comment] 2023-05-10 09:31
@magento give me 2.4-develop instance

**Comment by Xeo67** [comment] 2023-09-28 09:56
Is there a fix ? I have the same issue on Magento 2.4.5-p4

There is no sorting on position attribute when Magento search the relation in `vendor/magento/module-related-product-graph-ql/Model/DataProvider/RelatedProductDataProvider.php`
