### ISSUE TITLE
Braintree Payment gateway issue

### ISSUE THREAD

**Issue by codingbrains50** [magento/magento2#33129] opened 2021-06-02 16:59 UTC
I am facing this issue in Magento 2.4.2 on the checkout page.

"PayPal Checkout could not be initialized. Please contact the store owner."

Please let me know how I can resolve this.

**Comment by engcom-Alfa** [comment] 2021-06-14 06:58
Hi @codingbrains50 
I have tried reproducing in the Magento 4.2-develop version and able to successfully without any issues.
Please try to reproduce in the latest version. If you are able to reproduce, kindly update me with all the detailed information like - Preconditions, Steps to reproduce, Expected result and Actual result. Possibly provide me the information with the screen shots / screen record.

**Comment by codingbrains50** [comment] 2021-06-14 11:45
So, what should I do in order to get it to work? Can you please provide the
steps?

**Comment by codingbrains50** [comment] 2021-06-15 10:16
I am not able to attach a screen record because of the size issue, can you
please give me another email where i can send the screen record video.

**Comment by codingbrains50** [comment] 2021-06-15 18:33
Here is the issue.

https://www.loom.com/share/8dcbf8229c534b74a3feaa086ec5c0d0?sharedAppSource=personal_library

**Comment by engcom-Alfa** [comment] 2021-06-16 06:37
Hi @codingbrains50 

Thanks for the screen record and I have looked into your issue exactly. The issue must be because of your brain tree configurations that you have done in your admin side. We face this issue in the front end, because of invalid input values provided in the admin side (Admin>Configuration>Sales>Payment Methods>Recommended Solutions>Braintree-configure).

Kindly cross check your merchant id / name and other relevant input data; and also make sure you have followed the instructions of Dynamic Descriptor's input fields, that would be visible just below each input field in the UI.
![image](https://user-images.githubusercontent.com/51679138/122169443-0390b500-ce9b-11eb-83ac-ed32b49ab9f7.png)

For more information relevant to Braintree configurations, you may please refer to the [Brain tree user guide](https://docs.magento.com/user-guide/payment/braintree.html)

Also you may refer the this [blog](https://magento.stackexchange.com/questions/209598/braintree-payment-gateway-failure-magneto2-something-went-wrong) answers for better clarity.

Since it is not a issue in Magento, I am closing the issue as off now. In case of any issues relevant to Magento, kindly test in latest Magento version and report a bug with all detailed information like Preconditions, details steps to reproduce, expected and actual results along with screen shots / screen recordings possibly.

In case of any clarifications, you may take a look into the Magento User Guide[](https://docs.magento.com/user-guide/).

**Closed as completed by engcom-Alfa** 2021-06-16 06:37 UTC
Labels: non-issue

**Comment by codingbrains50** [comment] 2021-06-16 09:09
Make all the changes but still getting the same error. Please check the
attached screenshot.
