### ISSUE TITLE
CreditHistory GraphQL query returns an error

### ISSUE THREAD

**Issue by AbdElhamed2020** [magento/magento2#38144] opened 2023-11-02 16:31 UTC
### Preconditions and environment

- Magento version: 2.4.4

"Magento\\CompanyCreditGraphQl\\Model\\Credit\\OperationUser::getUserType(): Return value must be of type string, bool returned",

### Steps to reproduce

run query

query {
    company{
        credit_history {
            page_info {
                total_pages
            }
        }
    }
}

### Expected result

should return the default Magento result 

### Actual result

should return the default Magento result 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-11-07 09:27
Hi @AbdElhamed2020,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

After executing the query we are getting below result :

<img width="1512" alt="Screenshot 2023-11-07 at 12 07 29 PM" src="https://github.com/magento/magento2/assets/51680745/dbd29819-64c6-415a-8352-47b8daedeaac">



Could you please elaborate the expected and actual result if possible please provide us screenshots to proceed further.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-11-20 06:12
Hi @AbdElhamed2020,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38144#issuecomment-1798120768 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-11-28 05:22
Hi @AbdElhamed2020,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-11-28 05:22 UTC
Labels: Issue: needs update, Reported on 2.4.4
