### ISSUE TITLE
Integration tests can break because they run into "exit" statement when using secure base URL

### ISSUE THREAD

**Issue by amenk** [magento/magento2#28636] opened 2020-06-09 14:05 UTC
### Summary

When the base URL is set to a secure https:// URL and the integration tests are run via CLI and PHPunit the _checkShouldBeSecure runs into an exit

### Example

The error disguises itself as "Some transactions have not been committed or rolled back during integration tests"

Such exit statements are super hard to debug, especially when appearing on CI where no Xdebug is available. Even with Xdebug it's hard to find the exit statement as nobody expects it in modern, testable code.

This is the problematic line:

https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/App/Router/Base.php#L366

### Preconditions

have a `web/secure/base_url` or `web/unsecure/base_url` set in your Integrations tests that starts with https://

### Proposed solution

1. The exit should be removed completely 
2. Or: Add a special case for PHPUnit not to run into the exit which cannot be traced back

Additionally, also other usages of the exit statement should be checked https://github.com/magento/magento2/search?q=Magento2.Security.LanguageConstruct.ExitUsage&unscoped_q=Magento2.Security.LanguageConstruct.ExitUsage

See also https://magento.stackexchange.com/a/314662/81

**Comment by amenk** [comment] 2020-06-09 15:46
Current workaround, in phpunit.xml

    <php>
        <env name="HTTPS" value="1" force="true" />

**Comment by amenk** [comment] 2021-01-29 06:06
Still an issue

**Comment by amenk** [comment] 2021-04-15 15:21
was this fixed?

**Comment by engcom-Echo** [comment] 2021-08-17 15:49
Hi @amenk 
We tried to reproduce this issue on **2.4-develop** & was unable to do so.
Here are the Steps we followed,
1. Set up a fresh instance on 2.4-develop branch
2. **Stores** -> **Configuration** -> **General** -> **Web** - Set the secure base URL & Enable use secure Base URLs on Storefront & Admin.
3. Save the Config & Reindex & flush cache.
4. Set up the SSL Certificate for the website
5. Access the store front and admin page via the secure urls
eg: https://magento8.local/, https://magento8.local/admin/
**Successfully** able to access them.
6. Add/Edit the configurations in **install-config-mysql.php** 
7. Add a logger to file lib/internal/Magento/Framework/App/Router/**Base.php** on line 369 before the **exit**;  controversial statement
8. Run the **integration** test & generate **allure results**
9. Test cases **ran successfully without any failure**s.

Unable to reproduce the error mentioned in the issue **"Some transactions have not been committed or rolled back during integration tests"**.

So kindly recheck this issue on Magento 2.4-develop branch and if the issue is still reproducible, please provide more details or additional/missing steps regarding the same.
Thank you.

**Comment by amenk** [comment] 2021-08-17 16:04
While I understand that all issues are tried to be reproduced, I still suggest the exit is removed, as this is bad practice - even this is not 100% reproducible in current Magento versions.
Is the exit() still there?

**Comment by amenk** [comment] 2021-12-22 16:56
While I understand that reproducible examples are needed most of the time, I want to point out that it is much harder to reproduce the issue than just get rid of the exit() which should never be used, because it can break tests

**Comment by engcom-Hotel** [comment] 2022-01-05 12:38
Hello @amenk,

In order to confirm the issue we need to reproduce it, so I again tried to reproduce it by tweaking the code, and it seems that the `exit` statement does not create any issues. Please have a look at the below-recorded video and let us know if we missed anything:

https://user-images.githubusercontent.com/51681618/148218777-89a2f204-bf26-4a20-a1ba-68349641ab79.mp4

Thanks

**Comment by amenk** [comment] 2022-01-05 12:41
Did you run integration tests with the mentioned preconditions? In the Screencast I saw only manual testing..the Problem arises when this line is hit in an integration tests

**Comment by engcom-Hotel** [comment] 2022-01-05 12:44
Hello @amenk,

Any specific integration test needs to run here. Please suggest.

Thanks

**Comment by amenk** [comment] 2022-01-05 12:51
Unfortunately not, just the code has to be hit

**Comment by engcom-Hotel** [comment] 2022-02-10 07:46
Hello @amenk,

As the issue is not reproducible for us by trying various ways. And you mentioned [here](https://github.com/magento/magento2/issues/28636#issuecomment-999725672) that the issue is unable to reproduce, hence we are closing this issue for now.

Thanks

**Closed as completed by engcom-Hotel** 2022-02-10 07:46 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.0
