### ISSUE TITLE
22010 -Updates AbstractExtensibleObject and AbstractExtensibleModel annotations

### ISSUE THREAD

**Issue by atwixfirster** [magento/magento2#22010] opened 2019-03-28 13:37 UTC
### Preconditions (*)
1. Magento 2.3.1

### Summary (*)
Magento is no longer support inheritance of DTO classes from `Magento\Framework\Api\AbstractExtensibleObject`. This class extends `abstract class AbstractExtensibleObject extends AbstractSimpleObject`. There is a new code and new modules, for example, `Inventory` module which uses inheritance of `Magento\Framework\Model\AbstractExtensibleModel`.
### Examples (*)
The misunderstanding is caused a point that `AbstractExtensibleObject` class marked as  `@api`, in the sime time `AbstractExtensibleModel` does not have the same mark.

### Proposed solution
- Add PHP annotation `@api` to `AbstractExtensibleModel`
- Add PHP annotation `@deprecated` to `AbstractExtensibleObject` and `@see` which link to `AbstractExtensibleModel`

CC: @maghamed 

<img width="694" alt="22010" src="https://user-images.githubusercontent.com/13585327/55162907-79e95580-5171-11e9-913e-e6f1be98a5ce.png">

Thank you! 😊

**Comment by magento-engcom-team** [comment] 2019-03-28 13:37
Hi @atwixfirster. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@atwixfirster do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2020-03-25 17:30
Hi @atwixfirster. Thank you for your report. 
The issue has been fixed in magento/magento2#22011 by @atwixfirster in 2.4-develop branch
Related commit(s):
 - [1a2b1cec66115385f1c6107747ef9a6f95c23d34](https://github.com/magento/magento2/commit/1a2b1cec66115385f1c6107747ef9a6f95c23d34)
 - [1a6656805768430f20711a4a5e54bab0041819de](https://github.com/magento/magento2/commit/1a6656805768430f20711a4a5e54bab0041819de)
 - [764cdf94634311e8468af2c6ddadc75e30e10211](https://github.com/magento/magento2/commit/764cdf94634311e8468af2c6ddadc75e30e10211)
 - [987d7138351adedd5f33af3e5525a6dee03cb1ed](https://github.com/magento/magento2/commit/987d7138351adedd5f33af3e5525a6dee03cb1ed)
 - [70c5e12d4ebbf08d35cf8ebb0575826808e887d1](https://github.com/magento/magento2/commit/70c5e12d4ebbf08d35cf8ebb0575826808e887d1)
 - [852bf03d88da8d5d6cbd09bf6263043490995bb2](https://github.com/magento/magento2/commit/852bf03d88da8d5d6cbd09bf6263043490995bb2)

The fix will be available with the upcoming 2.4.0 release.

**Closed as completed by magento-engcom-team** 2020-03-25 17:30 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Release Line: 2.3, Partner: Atwix, Component: Framework/Api, Fixed in 2.4.x
