### ISSUE TITLE
We are unable to SAVE any SEO edit for our website! Any advice?

### ISSUE THREAD

**Issue by Vestart** [magento/magento2#35381] opened 2022-04-27 13:15 UTC
### Preconditions (*)

1. We are using Magento 2 and we are trying to fix meta tags & descriptions for all of our pages.
2. Our navigation in the platform is: CONTENT -> PAGES -> HOMEPAGE (our starting point) -> SEARCH ENGINE OPTIMIZATION -> ...we make changes -> SAVE
3. When we save, the loading icon never leaves and the changes are never saved.

### Steps to reproduce (*)

1. After following the path mentioned above, we put the information we need and press save. Then, the loading icon starts going forever without success..
2. We made sure it's not a bad connection or a profile issue. Other types of changes are normally saved, but this one.

### Expected result (*)

1. What should happen is when we edit our SEO details, as mentioned above, we should be able to successfully save the changes.

### Actual result (*)

1. We are stuck here, all day. 
![Magento 2 Screenshot](https://user-images.githubusercontent.com/104506364/165525396-bfe7d709-d400-4ec0-8d57-42b72125d10a.png)
3. If we refresh the page, all changes are lost, of course.
4. We have tried from different profiles as well, with the same issue.

**Comment by FadedOut** [comment] 2022-04-28 08:00
I just tested on my live 2.4.4. and it worked as intended. 

1) What version of Magento are you on? That makes all the difference because from version-to-version things change/break.
2) You will want to check your var > log > system.log or exception.log.

You might get lucky and an error was logged in one of those files at the time of pressing save. That error will most likely point you in the direction of why it is doing that. If there is an error logged, that will be your best way of getting help because it might be something with your setup as like I mentioned above, I was able to save a page with meta info filled in.

**Comment by Vestart** [comment] 2022-04-28 09:41
Thanks for the help. What we found out is that this issue happens to one and only one specific page. So we are in touch with the theme support.

**Comment by engcom-Hotel** [comment] 2022-05-16 13:57
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-05-17 11:52
Hello @Vestart,

We have tried to reproduce the issue in Magento 2.4-develop branch the issue is not reproducible. Please refer the below screenshot for the reference;

![Screenshot from 2022-05-17 13-57-06](https://user-images.githubusercontent.com/60198592/168800133-8bc3cc8b-0de2-4cd9-a3c5-ff9f38ce4d77.png)


We have followed the below steps in order to reproduce the issue:
1.Go to Admin Panel>>and Click CONTENT
2.Go Pages Click and Edit Of Home Page
3.Select SEO and Make change Something
4.Click Save.


...

Let us know in case we have missed anything.

Thanks

**Comment by engcom-Dash** [comment] 2022-06-01 07:38
Hello @Vestart 

Thanks for the confirmation!

As of Now I didn't Get any Reply. Hence closing the issue.

Thanks

**Comment by engcom-Dash** [comment] 2022-06-01 07:47
Dear @Vestart ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Comment by engcom-Dash** [comment] 2022-06-01 07:47
Dear @Vestart ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Closed as completed by engcom-Dash** 2022-06-01 07:47 UTC
Labels: Issue: ready for confirmation
