### ISSUE TITLE
Refunds Report Period Selector not working

### ISSUE THREAD

**Issue by FerihumF** [magento/magento2#10387] opened 2017-07-31 22:30 UTC
### Preconditions

1. Magento 2.1.5

### Steps to reproduce

1. In Magento backend go to Reports > Refunds
2. Select 'Last Credit Memo Create Date' as Date Used
3. Perform a query with some test data

### Expected result

1. Credit Memo Create Date should be used as period

### Actual result

1. Order Create Date is used instead

Since I needed a fix, I searched and found the problem located in _Magento\Sales\Model\ResourceModel\Report\Refunded\Collection\Refunded_

In the constructor it correctly says `$resource->init('sales_refunded_aggregated');` but since the class extends _Magento\Sales\Model\ResourceModel\Report\Refunded\Collection\Order_ the init command is overwritten there with `$resource->init('sales_refunded_aggregated_order');`

**Comment by magento-engcom-team** [comment] 2017-09-27 22:01
@FerihumF, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-27 22:01 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
