### ISSUE TITLE
[Config] Array to string conversion error when saving row system config with defaults

### ISSUE THREAD

**Issue by stollr** [magento/magento2#30314] opened 2020-10-02 08:39 UTC
### Preconditions (*)

I am using Magento 2.4.0 in development mode with PHP 7.4.10 on Linux, Debian Buster.

Also verified and confirmed on `2.4-develop` open source edition

### Steps to reproduce (*)

1. We followed [these instructions](https://devdocs.magento.com/guides/v2.4/ext-best-practices/tutorials/dynamic-row-system-config.html) to create a dynamic row system config.

2. We have added default values to my `etc/config.xml` in this form:

```xml
     <default>
         <general>
             <quantity_ranges>
             <ranges>
                 <item1>
                     <from_qty>1</from_qty>
                     <to_qty>5</to_qty>
                     <price>10.00</price>
                     <tax>1</tax>
                 </item1>
                 <item2>
                     <from_qty>6</from_qty>
                     <to_qty>10</to_qty>
                     <price>20.00</price>
                     <tax>1</tax>
                 </item2>
                 <item3>
                     <from_qty>11</from_qty>
                     <to_qty>15</to_qty>
                     <price>30.00</price>
                     <tax>0</tax>
                 </item3>
             </ranges>
             </quantity_ranges>
         </general>
     </default>
```
3.` Go to Admin -> System -> Configuration -> Quantity Ranges` and click on the **Save Config** button

### Expected result (*)

Save the configs.

### Actual result (*)

I get the following error:

> Notice: Array to string conversion in /path/to/magento/vendor/magento/framework/App/Config/Value.php on line 100

![2020-10-20_16-42](https://user-images.githubusercontent.com/51679138/96594839-b94b3a00-12f3-11eb-8e90-47412cc4df0b.png)

When I remove the defaults from the config.xml and clear the cache, the saving works correctly.

### Notice

I have tried to debug the issue. What I found out so long is that Magento serializes the data in the config value to json in `Magento\Config\Model\Config\Backend\Serialized::beforeSave` and saves it in the data array.

In `Magento\Framework\App\Config\Value::afterSave` it calls `$this->isValueChanged()` where it compares `$this->getValue() != $this->getOldValue()`. Now in `getOldValue` it uses the default value coming from the XML config which is stored as array and is not serialized. At the point where the array is tried to be casted to a string, the error occures.

---

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by naitsirch** [comment] 2020-10-02 11:49
@magento I am working on this

**Comment by wagento-rajan** [comment] 2020-10-02 12:49
@magento I am working on this

**Comment by naitsirch** [comment] 2020-10-02 14:28
@wagento-rajan I have already created a PR for this issue ;-)

**Comment by engcom-Alfa** [comment] 2020-10-20 13:45
The issue is reproducible on fresh 2.4-develop.

**Manual testing scenario:**

1. We followed [these instructions](https://devdocs.magento.com/guides/v2.4/ext-best-practices/tutorials/dynamic-row-system-config.html) to create a dynamic row system config.

2. We have added default values to my `etc/config.xml` in this form:

```xml
     <default>
         <general>
             <quantity_ranges>
             <ranges>
                 <item1>
                     <from_qty>1</from_qty>
                     <to_qty>5</to_qty>
                     <price>10.00</price>
                     <tax>1</tax>
                 </item1>
                 <item2>
                     <from_qty>6</from_qty>
                     <to_qty>10</to_qty>
                     <price>20.00</price>
                     <tax>1</tax>
                 </item2>
                 <item3>
                     <from_qty>11</from_qty>
                     <to_qty>15</to_qty>
                     <price>30.00</price>
                     <tax>0</tax>
                 </item3>
             </ranges>
             </quantity_ranges>
         </general>
     </default>
```
3.` Go to Admin -> System -> Configuration -> Quantity Ranges` and click on the **Save Config** button

**Actual Result:** :heavy_multiplication_x: got the following error:

![2020-10-20_16-42](https://user-images.githubusercontent.com/51679138/96594839-b94b3a00-12f3-11eb-8e90-47412cc4df0b.png)

**Comment by magento-engcom-team** [comment] 2020-10-21 07:29
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38588` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2020-10-24 13:46
Hi @naitsirch. Thank you for your report. 
The issue has been fixed in magento/magento2#30322 by @naitsirch in 2.4-develop branch
Related commit(s):
 - [c0a9c422053ab85c4f3f77bb337196764c4ed149](https://github.com/magento/magento2/commit/c0a9c422053ab85c4f3f77bb337196764c4ed149)

The fix will be available with the upcoming 2.4.2 release.

**Closed as completed by magento-engcom-team** 2020-10-24 13:46 UTC
Labels: Issue: Ready for Work, Component: Config, Issue: Confirmed, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P3, Severity: S3, Progress: done, Reported on 2.4.0

**Comment by eikoncode** [comment] 2021-08-10 04:16
Can you merge this PR in Magento 2.4.1 version also?

**Comment by CUTTRHOAT69** [comment] 2022-08-18 18:05
If someone get this error and need a quick fix (without updating the Magento version or adding a patch) you can just add an serialized array on the config.xml file as the default field value. As Magento get the default info from XML as an array and does not have the format convertion you can just pass already as a serialized value.

Example:
`
<default>
         <general>
             <quantity_ranges>
             <ranges>
                 {
                        "item1":{"from_qty":"1","to_qty":"5","price":"10.00","tax":"1"},
                        "item2":{"from_qty":"6","to_qty":"0","price":"20.00","tax":"1"},
                        "item3":{"from_qty":"11","to_qty":"15","price":"30.00","tax":"0"},
                    }
             </ranges>
             </quantity_ranges>
         </general>
     </default>
`
 Passing the value already as serialized the Magento **getOldValue** function doesn't need the conversion. The default values appear normally on the painel with the error fixed.
_It's just works_
