### ISSUE TITLE
Access forbidden

### ISSUE THREAD

**Issue by rab14191** [magento/magento2#9288] opened 2017-04-18 06:32 UTC
When i m trying to saving product then i got error  like

. Access forbidden.

Unable to write file into directory \C:/xampp/htdocs/rabworld/2017_newtheme/pub/media/catalog/product\cache\914b1ba9268f8c1d0e58a8e7ce614488\/0/1. Access forbidden.

i m useing magneto 2.1.6

**Comment by korostii** [comment] 2017-04-18 17:47
Seems to be a duplicate of #9212, please see the workaround attached there.
Unfortunately, Magento does not officially provide support for installations using Windows on server side, so this issue might be ignored indefinitely by the core developers.

**Comment by mzeis** [comment] 2017-08-24 12:25
Hi,

issue #9212 which @korostii pointed out was fixed in 2.1.7. Otherwise I'm afraid you are on your own since Magento isn't officially supported on Windows (see http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html). 

Can I close this issue?

Thanks!

**Closed as completed** 2017-09-18 20:18 UTC
Labels: Progress: needs update, Issue: Format is not valid
