### ISSUE TITLE
Brand new install of Magento 2.4.3-p1 zero value totals

### ISSUE THREAD

**Issue by calvinmuller** [magento/magento2#34969] opened 2022-01-13 14:05 UTC
### Preconditions (*)

1. 2.4.3-p1

### Steps to reproduce (*)

1. Add product to cart, cart shows the value)
2. Click Checkout
3. Totals are zero.

### Expected result (*)

1. Expect the values to be ZAR 500

### Actual result (*)

1. <img width="793" alt="Screenshot 2022-01-13 at 15 59 26" src="https://user-images.githubusercontent.com/755442/149344472-1b76808d-2a7f-42e6-935f-98a7b2dc7891.png">

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by calvinmuller** [comment] 2022-01-13 14:06
@magento give me 2.4.3-p1

**Comment by calvinmuller** [comment] 2022-01-13 14:07
@magento give me 2.4.3-p1 instance

**Comment by calvinmuller** [comment] 2022-01-14 07:05
The interesting thing is it's not reproducible on the instance provided by yourself, what could cause this. It's literally a brand new install with composer.

I'm assuming some config/infra on your servers is just right and for me it's not.

the strange this is the json response contains values eg. `estimate-shipping-methods`
as you can see the price is 5
```
[{
	"carrier_code": "flatrate",
	"method_code": "flatrate",
	"carrier_title": "Flat Rate",
	"method_title": "Fixed",
	"amount": 5,
	"base_amount": 5,
	"available": true,
	"error_message": "",
	"price_excl_tax": 5,
	"price_incl_tax": 5
}]
```
and here is what is displayed.

<img width="595" alt="Screenshot 2022-01-14 at 09 03 14" src="https://user-images.githubusercontent.com/755442/149465703-4f12b560-0418-4612-8cd3-5082389dfd40.png">

**Comment by calvinmuller** [comment] 2022-01-14 07:14
Same thing for the cart totals, the `window.checkoutConfig` has what it needs yet it shows 0.
<img width="799" alt="Screenshot 2022-01-14 at 09 14 15" src="https://user-images.githubusercontent.com/755442/149466712-1d5b396c-a3e5-42cc-980a-4bb6c1e99d71.png">

**Comment by ihor-sviziev** [comment] 2022-01-14 09:16
@calvinmuller, looks like this is duplicate of the https://github.com/magento/magento2/issues/33856 that was already fixed in the 2.4-develop branch. Could you try applying the change from the following comment:   https://github.com/magento/magento2/issues/33856#issuecomment-946761019?

**Comment by calvinmuller** [comment] 2022-01-14 10:53
@ihor-sviziev how do I apply this patch when i've installed magento via composer? The code lives in the `vendor` directory?

**Comment by ihor-sviziev** [comment] 2022-01-14 10:54
@calvinmuller, here you can find the instruction https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/patches/overview.html#custom-patches

**Comment by madbounce** [comment] 2022-01-17 07:35
@magento give me 2.4.3-p1 instance

**Comment by engcom-Echo** [comment] 2022-01-17 12:48
Hi @calvinmuller,

Thank you for reporting the issue.

I have tried this issue on the fresh installation (Magento 2.4-dev/2.4.3-P1) but I am not able to reproduce it. (See the attached screenshot.)

<img width="1440" alt="Screenshot 2022-01-14 at 1 12 53 PM" src="https://user-images.githubusercontent.com/51681435/149771839-2ec44c52-1f61-4b75-9e05-7aaacee0c00e.png">

Could you please provide some more information to reproduce the issue? Also, you can debug with the help of logs on your system to find out the exact issue.

Thanks.

**Comment by engcom-Hotel** [comment] 2022-01-31 15:44
Dear @calvinmuller,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-01-31 15:44 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
