### ISSUE TITLE
Coupon code empty after update of sales rule through rest

### ISSUE THREAD

**Issue by websecureNL** [magento/magento2#35298] opened 2022-04-13 09:27 UTC
### Preconditions (*)

1.Magento ver. 2.4.3

### Steps to reproduce (*)

1. Create a new **disabled** Cart Price Rule through API - endpoint POST: /rest/V1/salesRules/

Sample payload
{"rule":{"name":"This is the coupon name","store_labels":[{"store_id":0,"store_label":"Gift Card $20"}],"website_ids":[1],"customer_group_ids":[0],"from_date":"","to_date":"","uses_per_customer":0,"is_active":false,"stop_rules_processing":true,"is_advanced":true,"simple_action":"cart_fixed","discount_amount":20,"discount_qty":0,"discount_step":0,"apply_to_shipping":false,"is_rss":false,"coupon_type":"SPECIFIC_COUPON","use_auto_generation":false,"uses_per_coupon":0}}

2. Create a new Coupon for newly created sales rule through API - endpoint POST: /rest/V1/coupons/

Sample payload
{"coupon":{"rule_id":insert rule_id,"code":"GC1-FD2SD","usage_limit":0,"usage_per_customer":0,"times_used":0,"is_primary":true,"type":0,"extension_attributes":{}}}

3. Update the status of the Cart Price Rule to enabled through Cart Price Rule through API -  endpoint PUT /rest/V1/salesRules/{rule_id}

Sample payload
{"rule":{"name":"New Name","from_date":"2022-01-01","to_date":"2022-10-10","is_active":true}}

### Expected result (*)

1. Expected that only updated values would be applied (existing Cart Price Rule got a status change from disabled to enabled with a from_date and to_date) and that the existing coupon code would still be attached. 

### Actual result (*)

1. After updating the Cart Price Rule the coupon code is removed from the rule.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by websecureNL** [comment] 2022-04-13 09:28
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by websecureNL** [comment] 2022-04-13 11:25
https://github.com/magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by websecureNL** [comment] 2022-04-13 11:25
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by engcom-November** [comment] 2022-04-13 12:08
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
Created Inactive/disabled cart price rule using POST:  /rest/V1/salesRules/
Created Coupon for above rule using /rest/V1/coupons
![image](https://user-images.githubusercontent.com/60198231/163175975-46b91a84-c397-45a3-851c-66305022951a.png)
Updated rule - Active, given from date and to date using PUT : /rest/V1/salesRules/{ruleID}
Issue: Cart Price rule is updated as expected but coupon code is removed.
![image](https://user-images.githubusercontent.com/60198231/163175705-07667f18-4bb0-4e3c-b260-49cba98efb3f.png)
![image](https://user-images.githubusercontent.com/60198231/163175789-fd6a9599-a267-4617-970a-672680b54ff5.png)

**Comment by engcom-Alfa** [comment] 2022-05-20 08:36
Hello @websecureNL 

As I can see this issue got fixed in the scope of the internal Jira ticket `AC-2845` by the internal team
Related commits: https://github.com/magento/magento2/commit/b092dd6df013e8b1e77e8b5d639148ed76a7172a

Based on Jira target version is 2.4.5

**Closed as completed by engcom-Alfa** 2022-05-20 08:36 UTC
Labels: Issue: Confirmed, Component: SalesRule, Component: Api, Reproduced on 2.4.x, Priority: P1, Progress: done, Reported on 2.4.3, Area: APIs
