### ISSUE TITLE
Block totalbar not used in invoice create and credit memo create screens

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#16655] opened 2018-07-09 15:57 UTC
In the following layout files the Magento\Sales\Block\Adminhtml\Order\Totalbar block is defined:
- sales_order_creditmemo_new.xml
- sales_order_creditmemo_updateqty.xml
- sales_order_invoice_new.xml
- sales_order_invoice_updateqty.xml

However up on investigation I found that this block doesn't do anything and seems to be deprecated. Even when it does render something there is no styling. All styling is in the file styles-old.less and styling can not be found in the style.less file of the Magento adminhtml theme. 

### Preconditions
1. Magento 2.2.5 

### Steps to reproduce
1. Install Magento 
2. Create an invoice and an credit memo.

### Expected result
1. Totalbar block renders something.

### Actual result
1. Block doesn't render anything.

**Comment by magento-engcom-team** [comment] 2018-07-09 15:57
Hi @dverkade. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@dverkade do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment] 2018-07-18 08:29
Hello @dverkade, thank you for your report and pull request.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2018-08-07 10:30
Hi @dverkade. Thank you for your report. 
The issue has been fixed in magento/magento2#16656 by @dverkade in 2.2-develop branch
Related commit(s):
 - [19bff300ecd22dca8966da691f01044ba9e5575b](https://github.com/magento/magento2/commit/19bff300ecd22dca8966da691f01044ba9e5575b)

The fix will be available with the upcoming 2.2.7 release.

**Closed as completed by magento-engcom-team** 2018-08-07 10:30 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by sidolov** [comment] 2018-08-08 11:17
Hi @dverkade. Thank you for your report. 
The issue has been fixed in magento/magento2#17413 by @dverkade in 2.1-develop branch
Related commit(s):
 - [db166c748957a161d9cdc79d0c110caa609857c7](https://github.com/magento/magento2/commit/db166c748957a161d9cdc79d0c110caa609857c7)

The fix will be available with the upcoming 2.1.16 release.

**Comment by magento-engcom-team** [comment] 2018-08-10 08:05
Hi @dverkade. Thank you for your report. 
The issue has been fixed in magento/magento2#17414 by @dverkade in 2.3-develop branch
Related commit(s):
 - [1fe125161c3e9a4b94b8b9ae8c1dd46ed10b4ed4](https://github.com/magento/magento2/commit/1fe125161c3e9a4b94b8b9ae8c1dd46ed10b4ed4)

The fix will be available with the upcoming 2.3.0 release.
