### ISSUE TITLE
Magento 2.x all version allow register customer to as guest checkout . 

### ISSUE THREAD

**Issue by nltheme** [magento/magento2#9709] opened 2017-05-20 06:02 UTC
how to reproduce.

1. logged out 
2. add product to cart 
3. go to checkout and add email (already registered email) and click on first name . it will open password field .
4. now if u refresh page then it's consider that email as not register and allowing u to place order as guest!!!!!

**Comment by ishakhsuvarov** [comment] 2017-05-22 11:38
@nltheme By design Guests may checkout with any email, existing and not existing in the database. Login is optional in this case.

**Comment by nltheme** [comment] 2017-05-23 02:46
so if any existing customer want to login without password then he need to reload page ? @ishakhsuvarov

**Comment by zack6849** [comment] 2017-05-23 13:40
It doesn't log you in as the customer, just checks out with that email address, it only associates the user with the order if the user logs in. (as far as i know.)

**Comment by veloraven** [comment] 2017-06-22 10:45
I'm closing this issue as it is not a bug.
If you still think it to be an issue please create new GitHub issue formatted according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. 
Please, also identify which version of Magento you are running.
But possibility to make an order as a guest using a registered email is not a bug.

**Closed by veloraven** 2017-06-22 10:45 UTC
