### ISSUE TITLE
Bug in deleting products

### ISSUE THREAD

**Issue by NathaliePHPro** [magento/magento2#38521] opened 2024-03-14 09:12 UTC
### Preconditions and environment

- Magento version - Adobe Commerce ver. 2.4.6-p3
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

1. Go to products
2. Delete a lot of Luma example products in the backend
3. Get this error: Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor::execute(): Argument #1 ($productType) must be of type string, null given, called in /var/www/releases/20231109.1103/src/vendor/magento/module-inventory-sales/Model/GetProductSalableQty.php on line 108

### Expected result

I would assume you can delete Luma example products without errors

### Actual result

Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor::execute(): Argument #1 ($productType) must be of type string, null given, called in /var/www/releases/20231109.1103/src/vendor/magento/module-inventory-sales/Model/GetProductSalableQty.php on line 108

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by NathaliePHPro** [comment] 2024-03-14 09:20
@magento give me 2.4.6-p3-develop instance

**Comment by NathaliePHPro** [comment] 2024-03-14 10:37
https://github.com/magento give me 2.4.6-p3-develop instance

**Comment by NathaliePHPro** [comment] 2024-03-14 11:47
@magento give me 2.4.6-p3-develop instance

**Comment by NathaliePHPro** [comment] 2024-03-14 11:49
https://github.com/magento give me 2.4.6-develop instance

**Comment by NathaliePHPro** [comment] 2024-03-14 11:50
@magento give me 2.4.6-develop instance

**Comment by engcom-Bravo** [comment] 2024-03-15 05:12
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-03-15 06:43
Hi @NathaliePHPro,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Go to products
- Delete a lot of Luma example products in the backend

[Screencast from 15-03-24 12:10:20 PM IST.webm](https://github.com/magento/magento2/assets/51680745/3bfb891a-9dbc-445d-9e42-f2cc5c5f7b11)



We are able to delete the Luma example products without errors.We have tried with more number of products as well and we are able to delete.


Kindly recheck the issue in Latest Magento 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-03-26 05:49
Hi @NathaliePHPro,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-03-26 05:49 UTC
Labels: Issue: needs update, Reported on 2.4.6-p3
