### ISSUE TITLE
301s aren't generated for category parents on product url update

### ISSUE THREAD

**Issue by twistedindustries** [magento/magento2#7805] opened 2016-12-15 02:13 UTC
Preconditions
1. Magento CE 2.1.3
2. PHP 7.0.14
3. MySQL 5.6.30

Steps to reproduce
1.   Create and save a 'top level' category as anchor  with 'url_key' = 'top-level'
2.  Create and save a 'child' category as a child to 'top level'  with 'url_key' = 'child'.  
3.  Create and save new visible and active product assigned to 'child' category with 'url_key' = 'test-product-1'.
4.  Change 'url_key' = 'test-product-2' leaving "Create Permanent Redirect for old URL" checked.

Expected result
1.  There should now be a total of 6 rewrites for the product:

    test-product-2.html => catalog/product/view/id/<product_entity_id> (redirect_type = 0)
    top-level/test-product-2.html => catalog/product/view/id/<product_entity_id>/category/<top_level_cat_id> (redirect_type = 0)
    top-level/child/test-product-2.html => catalog/product/view/id/289/category/<child_cat_id> (redirect_type = 0)
test-product-1.html => test-product-2.html (redirect_type = 301)
    top-level/test-product-1.html => top-level/test-product-2.html (redirect_type = 301)
    top-level/child/test-product-1.html => top-level/child/test-product-2.html (redirect_type = 301)

Actual result
1. The parent category urls are skipped.  There are only 5 rewrites for the product:

![screen shot 2016-12-14 at 6 13 18 pm](https://cloud.githubusercontent.com/assets/5498323/21209431/0c91eb70-c229-11e6-85b9-52644ec2fcbc.png)

This is because it is only grabbing categories the product is directly assigned to the product, seems like that collection should include parents as well in Magento\CatalogUrlRewrite\Model\Product\CurrentUrlRewritesRegenerator in the function retrieveCategoryFromMetadata

`$category = $this->productCategories->get($metadata['category_id']);`

**Comment by antboiko** [comment] 2016-12-15 13:09
Hi @twistedindustries , thanks for reporting this issue. Internal ticket MAGETWO-62284 was created.

Best,
Anton.

**Comment by thlassche** [comment] 2017-02-22 10:59
I developed a CLI command as a workaround (which can be run from cron), let me know if you are interested

**Comment by magento-engcom-team** [comment] 2017-10-11 14:30
@twistedindustries, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-11 14:30 UTC
Labels: Issue: Ready for Work, bug report, Component: CatalogUrlRewrite, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
