### ISSUE TITLE
Programming issue with \Magento\Framework\Api\DataObjectHelper

### ISSUE THREAD

**Issue by hungvt** [magento/magento2#4233] opened 2016-04-19 15:42 UTC
Hi,
I'm getting a problem with transferring data from quote_item to sales_order_item.
I added my custom fields to the **fieldset.xml** (under etc folder)

``` xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:DataObject/etc/fieldset.xsd">
    <scope id="global">
        <fieldset id="quote_convert_item">
            <field name="my_custom_attribute">
                <aspect name="to_order_item" />
            </field>
        </fieldset>
    </scope>
</config>
```

But the value of this field is not  copied from quote_item to sales_order_item

I checked to the code and found the problem.
This is the method that convert the quote item to order item

``` php
/**
     * @param Item|AddressItem $item
     * @param array $data
     * @return OrderItemInterface
     */
    public function convert($item, $data = [])
    {
        $options = $item->getProductOrderOptions();
        if (!$options) {
            $options = $item->getProduct()->getTypeInstance()->getOrderOptions($item->getProduct());
        }
        $orderItemData = $this->objectCopyService->getDataFromFieldset(
            'quote_convert_item',
            'to_order_item',
            $item
        );
        if (!$item->getNoDiscount()) {
            $data = array_merge(
                $data,
                $this->objectCopyService->getDataFromFieldset(
                    'quote_convert_item',
                    'to_order_item_discount',
                    $item
                )
            );
        }

        $orderItem = $this->orderItemFactory->create();
        $this->dataObjectHelper->populateWithArray(
            $orderItem,
            array_merge($orderItemData, $data),
            '\Magento\Sales\Api\Data\OrderItemInterface'
        );
        $orderItem->setProductOptions($options);
        if ($item->getParentItem()) {
            $orderItem->setQtyOrdered(
                $orderItemData[OrderItemInterface::QTY_ORDERED] * $item->getParentItem()->getQty()
            );
        }
        return $orderItem;
    }
```

I see the custom field is copied to orderItemData already from this code :

``` php
$orderItemData = $this->objectCopyService->getDataFromFieldset(
            'quote_convert_item',
            'to_order_item',
            $item
        );
```

The problem is from method populateWithArray of the dataObjectHelper(\Magento\Framework\Api\DataObjectHelper)

``` php
$orderItem = $this->orderItemFactory->create();
        $this->dataObjectHelper->populateWithArray(
            $orderItem,
            array_merge($orderItemData, $data),
            '\Magento\Sales\Api\Data\OrderItemInterface'
        );
```

It only copies the fields that are defined in the class with the get/set method. (eg. field sku -> methods setSku and getSku)
So how to copy custom fields from quote_item to sales_order_item? I can rewrite the interface to add set/get function but rewriting a class is a bad idea.

Now i use the event to copy data from quote_item to sales_order_item. But i think it should to work like this:
All fields are defined in the fieldset will be copied automatically from quote_item to sales_order_item.

I got same problem with copying custom field of quote table to sale_order, ....

Hope you will have a good solution for this issue soon.

**Comment by adragus-inviqa** [comment] 2016-04-20 20:05
I think you need to declare them as [an extension attribute](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/attributes.html) (some examples [here](https://gist.github.com/nevvermind/155952b0b01773f4b42f)) or empty the `var/generation` folder so that the interface gets created again.

**Comment by piotrekkaminski** [comment] 2016-05-24 03:33
@antonkril  can you take a look?

**Comment by southerncomputer** [comment] 2016-08-05 20:31
below is the fix for convert quote to order in magento2 else you need to write event to move all filed value from quote to order table magento2a\app\code\Sugarcode\Test\etc\fieldset.xml

```
    <?xml version="1.0"?>
<!--
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/Object/etc/fieldset.xsd">
    <scope id="global">
        <fieldset id="sales_convert_quote">
            <field name="custom_field">
                <aspect name="to_order" />
            </field>
        </fieldset>        
        <fieldset id="quote_convert_item">
            <field name="custom_sku">
                <aspect name="to_order_item" />
            </field>
        </fieldset>         
        <fieldset id="sales_convert_order">
            <field name="custom_field">
                <aspect name="to_quote" />
                <aspect name="to_invoice" />
                <aspect name="to_shipment" />
                <aspect name="to_cm" />
            </field>
        </fieldset>        
        <fieldset id="sales_convert_order_item">
            <field name="custom_sku">
                <aspect name="to_quote_item" />
                <aspect name="to_invoice_item" />
                <aspect name="to_shipment_item" />
                <aspect name="to_cm_item" />
            </field>            
        </fieldset>
    </scope>
</config>

```

app\code\Magento\Quote\Model\QuoteManagement.php (line no 428 )

before

$billingAddress = $this->quoteAddressToOrderAddress->convert(
            $quote->getBillingAddress(),
            [
                'address_type' => 'billing',
                'email' => $quote->getCustomerEmail()
            ]
        );
in function submitQuote() add below code

$order=$this->quoteAddressToOrder->convert($quote->getBillingAddress(), $orderData);
change in app\code\Magento\Quote\Model\Quote\Item\ToOrderItem.php (lin no around 78)

after

$orderItem = $this->orderItemFactory->create();
in function convert() add below code

$this->objectCopyService->copyFieldsetToTarget('quote_convert_item', 'to_order_item', $item, $orderItem);
it will work fine but 
make sure as i mention above fieldset.xml should be there in you custom module and also you should write event to set product attribute once product is added to cart as like in magento1.x and also you should set custom filed in quote table then only it will copy from quote and item to order and its item

**Comment by magento-engcom-team** [comment] 2017-12-05 12:22
Hi @hungvt 
This is not a bug.
To transferring data from quote_item to sales_order_item first of all you should define your attributes, as shown in [dev docs](http://devdocs.magento.com/guides/v2.1/ext-best-practices/tutorials/copy-fieldsets.html)

**Closed as completed by magento-engcom-team** 2017-12-05 12:22 UTC
Labels: bug report, Component: Sales, Issue: Clear Description, non-issue, Issue: Format is not valid
