### ISSUE TITLE
Magento 2.2.5 Temando_Shipping messing up Multi Shipping again

### ISSUE THREAD

**Issue by dyuk1987** [magento/magento2#17062] opened 2018-07-24 04:56 UTC
### Preconditions

1. Magento **CE 2.2.5** without demo data
2. Temando_Shipping module **enabled by default** but **not configured and enabled** as a shipping method
3. **Allow Shipping to Multiple Addresses** is enabled
4. A few simple products are created
5. Amazon_Core, Klarna_Core, Amazon_Login, Amazon_Payment, Klarna_Ordermanagement, Klarna_Kp are **disabled**

### Steps to reproduce

1. Register as a user
2. Add at least 2 shipping addresses
3. Add a few products to the cart
4. Proceed to shopping cart and checkout with multiple shipping addresses
5. Finish the checkout procedures.
6. Try to view the completed order.
7. The following error appears:
> Exception #0 (Exception): Notice: Undefined offset: 1 in /xxxxxxxxxxxxxx/vendor/magento/module-sales/Model/Order.php on line 1205
#0 /xxxxxxxxxxxxxx/vendor/magento/module-sales/Model/Order.php(1205): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined offse...', '/home/admin/web...', 1205, Array)
#1 /xxxxxxxxxxxxxx/vendor/temando/module-shipping-m2/Observer/PrepareMyOrderInfoObserver.php(70): Magento\Sales\Model\Order->getShippingMethod(true)
(...)

The same happened when I try to view the order from the admin panel.

### Expected result

Details of the order should be shown properly.

### Actual result

Errors occurred and the page could not be reached.

### Other observations
1. When the Temando_Shipping module is disabled, the error goes away.
2. I am not sure if it has anything to do with the issues in #16104.

**Comment by magento-engcom-team** [comment] 2018-07-24 04:56
Hi @dyuk1987. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@dyuk1987 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-09-16 14:05
Hi @denisflosi1. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by marcelo-monteiro** [comment] 2018-09-16 16:50
Hi @dyuk1987 
Like @okorshenko replied, in #17131, this issue is caused by a vendor extension. Please contact the  vendor support team for the assistance:
https://developer.temando.com/soap/index.html or email them tsupport@temando.com

**Closed as completed by marcelo-monteiro** 2018-09-16 16:50 UTC
Labels: Issue: Format is valid, Component: Bundled Extension, Event: webjump
