### ISSUE TITLE
Replace 'PayPal Account' translation in token_list.phtml

### ISSUE THREAD

**Issue by Morerice** [magento/magento2#35622] opened 2022-06-15 15:29 UTC
### Summary (*)
In the **Stored Payment Methods** page, there are 2 sections, one to render the card tokens and the other to render the account tokens. However, the table header for the accounts section is titled **PayPal Account**. This is fine if only paypal account tokens are to be created.

### Examples (*)
token_list.phtml:
```
<?php if (count($tokens) !== 0) : ?>
    <div class="table-wrapper my-credit-cards">
        <table class="data table table-credit-cards" id="token-list-table">
            <thead>
            <tr>
                <th scope="col" class="col"><?= $block->escapeHtml(__('PayPal Account')) ?></th>
                <th scope="col" class="col actions">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($tokens as $token) : ?>
                <?= /* @noEscape */ $block->renderTokenHtml($token) ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif; ?>
```

### Proposed solution
However we are currently working on functionality to add other tokenizable account payment methods (such as GooglePay). Hence, since this section represents all tokens with `type=Account` we think it would be more representative if the section was titled **Account** instead of **PayPal Account**.

If we can get some confirmation for this, we can also submit a PR ourselves for it.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment] 2022-08-04 14:39
Hello @Morerice,

Thanks for the report and collaboration !

I have enable the Braintree in which i have enable Google Pay. But as we know that we don't have  VAULT feature to enable it.
Hence it is not coming in the Stored Payment Method.
Please find the attached screen for your reference.

Steps for reproduce
1. Install fresh Magento setup
2. Configure Braintree with Paypal
3. Create Category and Product
4. Purchase one Product with Braintree
5. Go to MyAccount on frontend
6. check Stored Payment Methods Sections

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51681435/182845336-c246620b-03a4-4f42-93f7-ee1eb7f9b78e.png">


Please provide more information for the payment method which we can see in stored payment method sections so that we can reproduce this.

Thanks

**Comment by Morerice** [comment] 2022-08-05 08:23
Hi @engcom-Echo,

Thanks for your response. My request wasn't related to the Braintree module. We at Adyen have our [Magento Module](https://github.com/Adyen/adyen-magento2) created to process payments. We are looking into using Magento Vault to store token details of payment methods that are not cards.

Hence, when these payment methods are stored in the `vault_payment_token` table with `type=account`, they will then be shown in the Stored Payment Methods section on the customer's account.

The issue is that since these payment methods may have different types apart from paypal (ideal, SEPA, Sofort etc.) it wouldn't make sense to have these tokens in a table where the header is **PayPal Account**. That's why we think it would make more sense to rename the header to **Account** to make it more generic.

Feel free to get back to me if the issue is still not clear enough.

Thanks,
Jean
Adyen

**Comment by engcom-Echo** [comment] 2022-08-05 12:14
Hello @Morerice,

Thanks for you response.

As per our discussion we are understanding the issue is that in future if we adds new different payment method with **Vault** feature then this payment method will come under the Stored Payment Method sections and then the table name **Account**  in place of **PayPal Account** have make more sense.

Hence we are taking this as **feature** request.

Thanks

**Comment by Morerice** [comment] 2022-08-05 12:26
Hi @engcom-Echo,

Thanks for the update. Since this seems to be quite a straight-forward label change, is it ok if I submit a pull request for it? Or do you have some structure that I have to follow for the Pull request to be accepted?

Thanks,
Jean
Adyen

**Comment by cjnewbs** [comment] 2023-09-05 11:01
@Morerice I'm also working on another payment method that uses this. Last night I was trying to figure out how to have my module override the core translations but had no luck.

I think replacing with `Stored Accounts` would be ok? I'm happy to pick this up to get the ball rolling.

**Comment by engcom-November** [comment] 2024-04-24 07:41
The **Stored Payment Methods** page uses the templete were table name is `PayPal Account`, if the user wants to use any other service with vault other then paypal, the table name will remain the same.
This shouldn't be the case, so we are reassigning this as a bug instead of feature request.

Thank you.

**Closed as completed** 2024-05-28 15:06 UTC
Labels: Issue: Confirmed, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P3, Progress: done, Reported on 2.4.x, Component: Frontend, Area: Framework
