### ISSUE TITLE
Quote removeErrorInfosByParams not working properly 

### ISSUE THREAD

**Issue by chinhmv95** [magento/magento2#36314] opened 2022-10-17 11:36 UTC
### Preconditions and environment

- Magento version : 2.4.3 Enterprise Edition

### Steps to reproduce

1. add Error Info to Quote: 
`$quote->addErrorInfo(
                'abcdef',
                'abcdef',
                999,
                __('Sorry, Has some error')
            );`
2. remove Error Info By Params 
`$quote->removeErrorInfosByParams('abcdef', ['origin' => 'abcdef', 'code' => 999]);`
3. get Quote errors : 
`$errors = $quote->getErrors();`

### Expected result

Error has been removed properly . and variable $errors return empty array 

### Actual result

Error has not been removed properly. $quote->getErrors() returned error message. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by chinhmv95** [comment] 2022-10-17 11:36
@magento I am working on this

**Comment by chinhmv95** [comment] 2022-10-17 11:37
@magento add to contributors team

**Comment by chinhmv95** [comment] 2022-10-17 11:40
@magento I am working on this

**Comment by engcom-Bravo** [comment] 2023-01-17 10:41
Hi @chinhmv95,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible. Kindly refer the screenhsots.

**Steps to reproduce**

  1. Created custom module and created controller and added Error Info to Quote:
$quote->addErrorInfo( 'abcdef', 'abcdef', 999, __('Sorry, Has some error') );
2.removed Error Info By Params
$quote->removeErrorInfosByParams('abcdef', ['origin' => 'abcdef', 'code' => 999]);
3.get Quote errors :
$errors = $quote->getErrors();


<img width="1378" alt="Screenshot 2023-01-17 at 4 06 28 PM" src="https://user-images.githubusercontent.com/51680745/212877691-9f804952-a57f-42da-8173-7ba54fdf62c8.png">



We need some more information to reproduce the issue.Kindly provide us it will helpful for us to proceed further.


Thanks.

**Comment by engcom-Bravo** [comment] 2024-07-08 05:22
Hi @chinhmv95,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-08 05:22 UTC
Labels: Triage: Dev.Experience, Priority: P3, Progress: done, Issue: needs update, Reported on 2.4.3
