### ISSUE TITLE
Magento 2.3.5-p2: PHP Fatal error: Uncaught Error: Call to a member function isAllow() on null

### ISSUE THREAD

**Issue by mrkimmok** [magento/magento2#29379] opened 2020-08-04 11:40 UTC
### Preconditions (*)

Magento Community Edition v. 2.3.5-p2 (Updated from 2.3.5-p1 > 2.3.5-p2 with composer installation method)

### Steps to reproduce (*)

1 .Install patch with composer and ran setup:upgrade
2. Go to a category or search result page

### Expected result (*)

Catalog page / search result page is loaded normally.

### Actual result (*)

Get a blank page and below error message in apache log:

```
[Tue Aug 04 14:05:24.682733 2020] [proxy_fcgi:error] [pid 9870] [client 127.0.0.1:56921] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function isAllow() on null in /home/kimmok/projects/mag23/vendor/magento/module-wishlist/view/frontend/templates/sidebar.phtml:12\n
Stack trace:\n
#0 /home/kimmok/projects/mag23/vendor/magento/framework/View/TemplateEngine/Php.php(59): include()\n
#1 /home/kimmok/projects/mag23/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Framework\\View\\TemplateEngine\\Php->render(Object(Magento\\Wishlist\\Block\\Customer\\Sidebar\\Interceptor), '/home/kimmok/pr...', Array)\n
#2 /home/kimmok/projects/mag23/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Framework\\View\\TemplateEngine\\Php\\Interceptor->___callParent('render', Array)\n
#3 /home/kimmok/projects/mag23/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Framework\\View\\TemplateEngine\\Php\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Wishlist\\Block\\Customer\\Sidebar\\Interceptor), '/home/kimmok/pr...', Array)\n
#4 /home/kimmok...\n', referer: http://www.mag23.local.fi/
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ambkimmok** [comment] 2020-08-04 12:03
Seems that this was in fact caused by an old customization to wishlist functionality, so closing the issue...

**Closed as completed by ambkimmok** 2020-08-04 12:03 UTC
Labels: Issue: Format is valid, Reported on 2.3.5-p2
