### ISSUE TITLE
Method \Magento\Framework\Stdlib\DateTime::formatDate don't work with timezones

### ISSUE THREAD

**Issue by DmitrySamushchenko** [magento/magento2#34054] opened 2021-09-10 15:37 UTC
Hello, i'm developer from Amasty.

### Preconditions (*)
Magento version 2.4.2

### Steps to reproduce (*)
1. Create `Catalog Price Rule` and specify the start and end date - https://screens.amasty.com/911_dim_2021-09-10_18.25.36.png
2. Apply this Catalog Price Rule, Cache Flush and run full reindex.
3. Open database and find table `catalogrule` and see column `from_date` - https://screens.amasty.com/911_dim_2021-09-10_18.26.31.png
4. Go to `catalogrule_product_price` table and see `latest_start_date` column.

### Expected result (*)
`latest_start_date` must be 2021-09-11 (the same as in table catalogrule) (https://screens.amasty.com/911_dim_2021-09-10_17.36.30.png)

### Actual result (*)
`latest_start_date` is 2021-09-10 (https://screens.amasty.com/911_dim_2021-09-10_17.43.17.png)

That's why in \Magento\CatalogRule\Model\Indexer\ReindexRuleProduct::execute Magento gets fromDate and ToDate with TimeZone in timestamp format - https://screens.amasty.com/911_dim_2021-09-10_18.34.43.png but in \Magento\CatalogRule\Model\Indexer\RuleProductPricesPersistor::execute in formatDate method Magento ignore TimeZone and i get `2021-09-10 21:00:00` instead of `2021-09-10 00:00:00` - https://screens.amasty.com/911_dim_2021-09-10_17.43.17.png

---
[Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog)

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by DmitrySamushchenko** [comment] 2021-09-10 17:22
@magento I am working on this

**Comment by engcom-Lima** [comment] 2021-09-14 14:10
Hi @DmitrySamushchenko,

Thank you for the detailed issue explanation. I tried to reproduce with the steps given but I was not able to reproduce it on 2.4-develop instance.

For your reference, please check code in file`\Magento\CatalogRule\Model\Indexer\ReindexRuleProductPrice` and method `getDateInterval()`, you’ll notice formatting of time using website timezone only. As per your use case `latest_start_date` column value should be `2021-09-10 23:59:59`.

So for further analysis of this issue, I require below additional information:

1. Can you update what tool/extension have you used to get the datetime from `catalogrule_product_price` table ? Or how can I get the same datetime result as you are getting ?
2. Did you check the real time Catalogue Price Rule apply on the frontend ? If not, can you please check if rule is happening on the correct time as you have given from Admin Panel per your use case ?

Regards

**Comment by engcom-Lima** [comment] 2021-09-28 03:41
Hi @DmitrySamushchenko,

We have noticed that this issue has not been updated for some time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Lima** 2021-09-28 03:41 UTC
Labels: Component: CatalogRule, Issue:  Cannot Reproduce, Issue: needs update
