### ISSUE TITLE
Multi Currency - Price Import from webservice Not working

### ISSUE THREAD

**Issue by harshilpatwa** [magento/magento2#2544] opened 2015-11-28 07:57 UTC
Stores->Currency Rates -> Import rates not working for multi currency.

**Comment by daim2k5** [comment] 2015-12-23 15:43
@harshilpatwa sorry for the late response. Colud you please provide more details like a error messages?

**Comment by harshilpatwa** [comment] 2015-12-24 04:49
There is no error message showing , it just about blank or keeping same rate as previous when importing the rates.

**Comment by vzabaznov** [comment] 2016-06-22 13:29
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment] 2016-07-14 08:11
Hi, @harshilpatwa thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.

**Closed as completed by vzabaznov** 2016-07-14 08:11 UTC
Labels: Progress: needs update
