### ISSUE TITLE
Mini cart loading issue for configurable product add to cart from listing on luma theme from iPad on 2.3.3

### ISSUE THREAD

**Issue by wibbel** [magento/magento2#26027] opened 2019-12-13 12:19 UTC
I've only tested this on Safari on an iPad as its the only tablet I have. It was reported by a customer. The error behaviour is not observed on a desktop or iPhone. I haven't tested any other theme or iPad browser.

### Preconditions (*)
1. Magento 2.3.3 standard installation with sample data
2. Luma Theme 
3. iPad using standard Safari browser

### Steps to reproduce (*)
1. View any product category (e.g. women -> tops -> tees)
2. Tap the "Add to Cart" button that displays on hover.
![IMG_0144](https://user-images.githubusercontent.com/15927277/70799521-caf1b600-1da1-11ea-9f47-957822c874e1.PNG)

### Expected result (*)
1. If its a simple product with no configuration, it should be added directly to the basket.
2. If its a product needing configuration details, the product view should be displayed.

### Actual result (*)
1. If its a simple product with no configuration, the cart icon shows the activity circle, but no product is added, no message is displayed and the cart remains empty.
![2019-12-13_12-17-24](https://user-images.githubusercontent.com/15927277/70799874-c2e64600-1da2-11ea-88d0-60a49184aedc.jpeg)

2. If its a product needing configuration details, the cart icon shows the activity circle, but the product is not displayed, no error message is displayed and the cart remains empty.

**Comment by magento-engcom-team** [comment] 2019-12-13 13:01
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29757` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ptylek** [comment] 2019-12-13 15:35
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2019-12-13 15:35
Hi @ptylek. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-12-13 15:36
Hi @ptylek, here is your [Magento instance](https://i-26027-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26027-2-4-develop.instances.magento-community.engineering/admin](https://i-26027-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ptylek** [comment] 2019-12-13 17:33
Couldn't reproduce.
![simpleipad](https://user-images.githubusercontent.com/34317830/70819667-13779680-1dd7-11ea-92d9-45c83e19c8df.gif)
![configipad](https://user-images.githubusercontent.com/34317830/70819663-107ca600-1dd7-11ea-9001-e4aae4cb4d75.gif)

**Closed as completed by ptylek** 2019-12-13 17:33 UTC
Labels: Issue: Ready for Work, Component: Catalog, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Reproduced on 2.4.x

**Comment by krishprakash** [comment] 2019-12-16 05:02
Hi @ptylek
You can see the issue in provided above attachment by you in 2nd video.
Without select any product option click on Add to cart from iPad it loads the mini cart.
Mini cart should not be load as product not adds into cart.
It works fine in 2.3.2
Let me know if you have any concern
Thanks.
