### ISSUE TITLE
After logging in all items of other customers from table catalog_compare_item assigned to the customer

### ISSUE THREAD

**Issue by yuriyhamulevych** [magento/magento2#38578] opened 2024-04-04 08:41 UTC
### Preconditions and environment

- Magento version 2.4.6-p4

### Steps to reproduce

1. Create a new customer.
2. Add a few products to compare list by this customer and log out.
3. Create another customer with option "Allow remote shopping assistance" and log out.
4. Log in the second customer by "Login as Customer" from admin customer form.
![image](https://github.com/magento/magento2/assets/48569882/49f697fd-b82d-4f1a-aad5-eaad0eec4f7a)

### Expected result

After log in customer compare list must be the same or merged with guest. 

### Actual result

All items of others customers (except guests items) from table catalog_compare_item were assigned to logged in customer. 

### Additional information

This bug was fixed in original module - https://github.com/magefan/module-login-as-customer/pull/43

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2024-04-09 18:06
Hi @yuriyhamulevych 

Thanks for reporting and collaboration.

Verified the issue in Magento 2.4 dev instance and the issue is not reproducible. 

Steps to reproduce

1. Create a new customer.
2. Add a few products to compare list by this customer and log out.
3. Create another customer with option "Allow remote shopping assistance" and log out.
4. Log in the second customer by "Login as Customer" from admin customer form.

We are seeing the merged compare list for the customer 2.

Please refer the attached screenshots and let us know if we missed anything.

<img width="1440" alt="Screenshot 2024-04-09 at 11 25 59 PM" src="https://github.com/magento/magento2/assets/60198592/4b81382a-27f9-4e89-9db0-36f6240b54b1">

<img width="1440" alt="Screenshot 2024-04-09 at 11 35 50 PM" src="https://github.com/magento/magento2/assets/60198592/60ad7e6a-d49d-40ea-ad64-699f8540cfe1">

**Comment by engcom-Dash** [comment] 2024-04-22 02:45
Hi @yuriyhamulevych 

We have noticed that this issue has not been updated for a long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel free to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2024-04-22 02:45 UTC
Labels: Issue: needs update, Reported on 2.4.6-p4
