### ISSUE TITLE
CVS Product Import when attribute backend_type static.

### ISSUE THREAD

**Issue by cctorres** [magento/magento2#38396] opened 2024-01-29 19:06 UTC
### Preconditions and environment

- Magento version 2.4.5

Hi! I have a attribute which is backend_type = static. I also have a column in catalog_product_entity for that attribute. I'm trying to update some products using cvs product import but I noticed that attribute is not updating. I guess is about that attribute is in a column from catalog_product_entity but I'm not sure.

### Steps to reproduce

1. Get a CVS filte with sku and new static attribute value
2. Check the CVS file and then import

### Expected result

- Products are not updated with new static attribute value

### Actual result

- Products should update with new static attribute value

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-01-31 07:07
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-01-31 09:32
Hi @cctorres,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Get a CVS filte with sku and new static attribute value
- Check the CVS file and then import

![Screenshot from 2024-01-31 12-47-43](https://github.com/magento/magento2/assets/51680745/e3034983-6026-4807-b804-28b07d7e07bc)





[export_catalog_product_20240117_020032 - Copy.csv](https://github.com/magento/magento2/files/14108446/export_catalog_product_20240117_020032.-.Copy.csv)



Attributes are updating with new values.

Kindly recheck the issue in Magento 2.4-develop instance and please elaborate the steps if the issue is still reproducible.

Thanks.

**Comment by engcom-Dash** [comment] 2024-02-16 08:58
Hi @cctorres 

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Dash** 2024-02-16 08:58 UTC
Labels: Issue: needs update, Reported on 2.4.5
