### ISSUE TITLE
No access to save changes in Magento Catalog - Products

### ISSUE THREAD

**Issue by EveNot** [magento/magento2#38995] opened 2024-08-02 07:30 UTC
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

connect to Magento
Go to Catalog
Go to Products - find produt concerned - Edit
Go to Medicine Details
Make necessary changes in the section Medicine Details - Save
Unable to save - pop up message " X The stock item was unable to be saved. Please try again."
Error occurs for all languages and all products

### Expected result

I need to be able to modify texts in the section Catalog/product/medicine details and save the changes made. I expect to be able to do this as I am currently unable to save my changes. 

### Actual result

I need to urgently to change the medicine details under Catalog/product as we have an out of stock on a product. I can go into edit mode in this section but am unable to save my changes. Am I missing an authorization to modify information in this section? I should have the same rights as my colleagues Mrs. Désirée DeHass. 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-08-08 05:53
Hi @EveNot,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible and also please check once that elasticsearch is working or not.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-08-21 06:57
Hi @EveNot,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-08-21 06:57 UTC
Labels: Issue: needs update, Reported on 2.4.x
