### ISSUE TITLE
Magento 2.4.5 - Free shipping not applied with cart price rule

### ISSUE THREAD

**Issue by pixel-paul** [magento/magento2#35967] opened 2022-08-17 13:42 UTC
### Preconditions and environment

- Magento 2.4.5
- PHP 8.1

This was working in 2.4.4

### Steps to reproduce

Create a cart price rule for free shipping:

![Screenshot 2022-08-17 at 14-34-46 Free Shipping _ Promotions _ Marketing _ Magento Admin](https://user-images.githubusercontent.com/389303/185147985-e526a5f9-9f8b-43f7-b4fe-ffcd53f86725.png)

### Expected result

Order should have shipping set to £0

### Actual result

Order does not have shipping set to £0.00:

![Screenshot 2022-08-17 at 14-37-18 Shopping Cart](https://user-images.githubusercontent.com/389303/185148454-61de123b-b2df-4e27-956b-ab90eedc0a02.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2022-08-17 15:11
Hi @pixel-paul ,
Thank you for raising an issue and We tried to reproduce the issue on magento 2.4.5 and magento 2.4 develop instance. issue is not reproducible. Hence request to review the provided steps .

Followed steps:
1. Create cart price rule  with  free shipping in admin portal

<img width="1347" alt="Screenshot 2022-08-17 at 8 08 29 PM" src="https://user-images.githubusercontent.com/51681379/185174849-f94c8be6-c7b0-4690-b4e2-d6b0642b6297.png">

<img width="1351" alt="Screenshot 2022-08-17 at 8 09 12 PM" src="https://user-images.githubusercontent.com/51681379/185175276-abaed2e3-1989-4622-8f35-3033f85c548e.png">

<img width="1346" alt="Screenshot 2022-08-17 at 8 11 45 PM" src="https://user-images.githubusercontent.com/51681379/185175420-8be1ab93-17b8-450f-a555-885b80d58266.png">

2. Go to frontend and add an items to cart  
3. Cart sub total should be equal or greater than 75 
4. Go to checkout page
5. Please review shipping cost

<img width="1414" alt="Screenshot 2022-08-17 at 8 07 17 PM" src="https://user-images.githubusercontent.com/51681379/185175529-1248eb82-e489-44a2-9d54-a02cc74894d9.png">

<img width="1413" alt="Screenshot 2022-08-17 at 8 40 30 PM" src="https://user-images.githubusercontent.com/51681379/185176122-6943a24f-9d2e-4e41-baf8-c4669af1c0d9.png">


Thanks

**Comment by pixel-paul** [comment] 2022-08-17 15:18
Hi @engcom-Delta,

Thanks for looking into this. 

Am I missing something here, but in your example the shipping is not discounted?

Thanks,

Paul

**Comment by engcom-Delta** [comment] 2022-08-18 10:53
Hi @pixel-paul ,
Thanks for quick response, We should follow the below document for free shipping , it works fine 
https://docs.magento.com/user-guide/shipping/shipping-free.html.

I have cross checked i could see free shipping got applied.

<img width="1351" alt="Screenshot 2022-08-18 at 3 24 30 PM" src="https://user-images.githubusercontent.com/51681379/185377289-d8a587f1-116a-4202-ad82-c9b232d8a347.png">

<img width="1351" alt="Screenshot 2022-08-18 at 3 24 30 PM" src="https://user-images.githubusercontent.com/51681379/185377618-6df8d270-f078-4db9-9d4d-8e1aeda6006a.png">

<img width="1404" alt="Screenshot 2022-08-18 at 3 21 11 PM" src="https://user-images.githubusercontent.com/51681379/185377727-df6af960-9f9a-454e-a5e7-1bf39909775c.png">

<img width="1420" alt="Screenshot 2022-08-18 at 4 17 51 PM" src="https://user-images.githubusercontent.com/51681379/185377790-27dd6a63-090b-4794-ab3a-1481bc038512.png">

**Comment by danhort** [comment] 2022-08-18 18:03
@engcom-Delta I am encountering the same issue described above with free shipping applied by cart price rule.
In your previous comment you are talking about free shipping applied by shipping method. These are two different ways to apply free shipping.

**Comment by danhort** [comment] 2022-08-18 20:16
Here is a quick fix for this bug applied to magento/module-quote reverting some code from the following commit https://github.com/magento/magento2/commit/bd149447d03f30dfd7cbda19c28a8140a87e0c9f.
```diff --git a/Model/Quote/Address/Total/Shipping.php b/Model/Quote/Address/Total/Shipping.php
index 64725d8..aef9fb0 100644
--- a/Model/Quote/Address/Total/Shipping.php
+++ b/Model/Quote/Address/Total/Shipping.php
@@ -73,7 +73,7 @@ class Shipping extends \Magento\Quote\Model\Quote\Address\Total\AbstractTotal
         $address->setFreeMethodWeight($data['freeMethodWeight']);
 
         $isFreeShipping = $this->freeShipping->isFreeShipping($quote, $shippingAssignment->getItems());
-        $address->setFreeShipping((int)$isFreeShipping);
+        $address->setFreeShipping($isFreeShipping);
         // recalculate weights
         $data = $this->getAssignmentWeightData($address, $shippingAssignment->getItems());
         $address->setItemQty($data['addressQty']);
diff --git a/Test/Unit/Model/Quote/Address/Total/ShippingTest.php b/Test/Unit/Model/Quote/Address/Total/ShippingTest.php
index 495a19c..54c2ac5 100644
--- a/Test/Unit/Model/Quote/Address/Total/ShippingTest.php
+++ b/Test/Unit/Model/Quote/Address/Total/ShippingTest.php
@@ -218,7 +218,7 @@ class ShippingTest extends TestCase
         $this->address
             ->expects($this->once())
             ->method('setFreeShipping')
-            ->with((int)$isFreeShipping);
+            ->with($isFreeShipping);
         $this->total->expects($this->atLeastOnce())
             ->method('setTotalAmount');
         $this->total->expects($this->atLeastOnce())```

**Comment by pixel-paul** [comment] 2022-08-19 15:42
Hi @engcom-Delta - you have provided two different methods to add free shipping. The method I am using, as confirmed by @danhort is this method:

https://docs.magento.com/user-guide/marketing/price-rules-cart-free-shipping.html

It looks like you have used this method in your first example. Please retest and confirm this as it looks very much like a bug.

**Comment by pixel-paul** [comment] 2022-08-19 16:59
> Here is a quick fix for this bug applied to magento/module-quote reverting some code from the following commit [bd14944].

That is great, thank you @danhort - I can confirm that this corrects the issue.

@engcom-Delta - can you retest please using the cart price rule method of providing free shipping? This appears to be a bug.

**Comment by pixel-paul** [comment] 2022-09-05 10:49
Hi @engcom-Delta - my guess is that the issue is with upgrade from 2.4.4 to 2.4.5 - might be worth checking that the value for `$isFreeShipping` is actually an `int` in the upgrade from 2.4.4 to 2.4.5.

**Comment by engcom-Delta** [comment] 2022-09-07 10:58
Hi @pixel-paul 

We have tried to reproduce this issue in magento 2.4.5 ,2.4-develop and upgrade Magento  2.4.4 to 2.4.5  but the issue is not reproducible .


Steps are followed to reproduce the issue
(we have followed the steps which are mentioned in this link https://docs.magento.com/user-guide/marketing/price-rules-cart-free-shipping.html )

1.Upgrade magento 2.4.4 to magento 2.4.5

2.Enabled free shipping
<img width="1053" alt="Screenshot 2022-09-07 at 12 29 51 PM" src="https://user-images.githubusercontent.com/51681379/188858987-d5b62c66-1872-4a29-aa0a-87f85045429f.png">

3.Create a cart price rule for free shipping
<img width="741" alt="Screenshot 2022-09-07 at 12 42 41 PM" src="https://user-images.githubusercontent.com/51681379/188859230-a4df9b62-9809-41b8-be70-3774a0ec9b40.png">

<img width="683" alt="Screenshot 2022-09-07 at 12 43 24 PM" src="https://user-images.githubusercontent.com/51681379/188859320-301f9963-546e-40c2-a0a0-67359e13d2ef.png">

4.Proceed to checkout and checked the free shipping applied
<img width="892" alt="Screenshot 2022-09-07 at 1 09 17 PM" src="https://user-images.githubusercontent.com/51681379/188860572-e3fbde19-7bbd-45b6-98ad-ab589205d031.png">

<img width="805" alt="Screenshot 2022-09-07 at 1 10 54 PM" src="https://user-images.githubusercontent.com/51681379/188859699-476e7252-5761-41f0-b74c-9ed1df3facd5.png">

<img width="703" alt="Screenshot 2022-09-07 at 1 11 47 PM" src="https://user-images.githubusercontent.com/51681379/188859744-699e8579-dd0f-44fe-a3d2-54cb5fd6938a.png">

Here, the free shipping is applied 

Please let us know if we are missing any steps here.
Thanks

**Comment by engcom-Delta** [comment] 2022-09-21 05:16
Hi @pixel-paul ,

We have noticed that, this issue has not been updated for a period of 14 Days.Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by MartinKonVis** [comment] 2022-10-17 12:06
We got a similar problem. The same setings like above. 
Shopping cart rules and table rates seems not longer to work?

We had not used the free shipping method. We used shopping cart rules only to reduce the shipping cost of table rates too "free"/0€. Before the update the table rates shipping methods showed corretcly"0€" for shipping (when conditions are met). 

After the update the free shipping in combination with shipping cart rules does not work anymore. It shows wrong table rates values. Instead of 0€ or the correct value it showed values of a lower table rate level.

settings:
Magento 2.4.5
PHP 8.1

Conditions of shopping cart rules
![01conditions](https://user-images.githubusercontent.com/20513850/196168936-8547a4f5-7441-4c60-af3d-683621c9db9d.JPG)

Actions
![01 actions](https://user-images.githubusercontent.com/20513850/196168952-5c3714b0-af8b-4822-9a91-e739100f3040.JPG)

Additional info regarding table rates which are used
Country,Region/State,"Zip/Postal Code","Weight (and above)","Shipping Price"
DEU,*,*,0.0000,2.9500
DEU,*,*,1.0000,5.9500

"DEU" is for Germany => please use Germany for testing in checkout

setting of table rates => weight vs destination
![table-rates](https://user-images.githubusercontent.com/20513850/196169617-63b542bb-2c96-4535-8dd6-6e88fd3e1f94.JPG)


Results before the update
-> the cart rules were used to set shipping of shipping method table rates to 0€ based on subtotal and if country matches
-> if the subtotal was higher than 69€ + country was germany => 0€ shipping tablerates was shown
-> if the subtotal was lower than 69€ + country was germany (or other) => regular shipping costs based on tablerates were shown

-> we did not use shipping method "free shipping". We had it not activated and it was working live descriebed above. 

Results after the update
->(correct) we activated "free shipping" shippingmethod and set min amount to 200 (higher as the shipping cart rules) like it said in the documentation (https://experienceleague.adobe.com/docs/commerce-admin/marketing/promotions/cart-rules/price-rules-cart-free-shipping.html)
When the shopping cart rule got meet it got shown correctly based on the shopping cart rule. Shipping method "free shipping" showed up which is correct.

-> (wrong) the "table rate" shipping shows now wrong shipping rate (lowest) if the conditions are met. This makes no sense from our point of view? It somehow reduced the weight in the cart to meet the lower rule? 
Correct was (before the update) it showed 0€ for the table rates because free shipping was met.


if rule is not active => correct table rates are shown based on weight in cart
![rule-inactive](https://user-images.githubusercontent.com/20513850/196169681-bdc2ecbd-e93d-41ec-a4f6-75668911ac6a.JPG)

if the rule is triggered / conditons are met => wrong table rates are shown
![rule-active](https://user-images.githubusercontent.com/20513850/196169896-d3a627b8-a578-48b3-afc7-e46caeb26d30.JPG)

Nothing has changed in the cart. Before the update it showed "0.00" because of free shipping
Now it shows a wrong table rate. Correct would be this line DEU,*,*,1.0000,5.9500 => 5,95
But somehow it is now "DEU,*,*,0.0000,2.9500" => 2,95 €

**Comment by nocturnalfrog** [comment] 2023-01-17 15:50
@engcom-Delta Please reopen this issue. 
The "Free Shipping" delivery method did not use to be required and is a different method all together. 
The goal of a cart rule is to lower the price of specific shipping methods.

Forcing people to select a different shipping method is not acceptable.

The customer should still be able to pick the delivery method they want (ex: Parcel Depot, Weekend Delivery, etc.)

**Comment by engcom-Hotel** [comment] 2023-01-27 06:56
Hello @nocturnalfrog @MartinKonVis,

Thanks for your comment!

We are reopening this issue for further process.

Thanks

**Comment by tramov** [comment] 2023-02-07 09:51
Adding a +1 as changing this cast by removing (int) has fixed the free shopping cart rule that broke after the 2.4.5-p1 (from 2.3.5) upgrade.

**Comment by engcom-Dash** [comment] 2023-02-28 15:00
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-02-28 18:43
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-02-28 19:24
Hi @pixel-paul ,

Thanks for your information and collaboration,

We are verified the issue again in 2.4-develop branch as well as 2.4.5-p1 instance and the issue is not reproducible.We are getting the free shipping method.

Preconditions:
Magento Version 2.4-develop and 2.4.5-p1
PHP version :8.1

Steps to reproduce:
Steps are followed to reproduce the issue
(we have followed the steps which are mentioned in this link https://docs.magento.com/user-guide/marketing/price-rules-cart-free-shipping.html )

1.Upgrade magento 2.4.4 to magento 2.4.5

2.Enabled free shipping

Screenshots:
<img width="1401" alt="cpr1" src="https://user-images.githubusercontent.com/60198592/221957060-dffac332-3a3e-41b7-b2f0-57e1d3b9adf7.png">
<img width="1422" alt="cpr2" src="https://user-images.githubusercontent.com/60198592/221957339-5141fd38-fcee-4d48-9d4c-8ee5567e9aa3.png">
<img width="1402" alt="cpr3" src="https://user-images.githubusercontent.com/60198592/221957370-eb9093de-5762-4f7e-b5ef-25120cf43e82.png">
<img width="1413" alt="cpr4" src="https://user-images.githubusercontent.com/60198592/221957385-833d204a-6223-47d4-8b6d-89cb3d59cc1e.png">
<img width="1511" alt="cpr5" src="https://user-images.githubusercontent.com/60198592/221957411-3437df9c-990e-4ca5-8a32-300f38c17add.png">
<img width="1511" alt="cpr6" src="https://user-images.githubusercontent.com/60198592/221957425-b64377af-e42f-46c2-919d-b29006bc92e3.png">

Thanks.

**Comment by nocturnalfrog** [comment] 2023-03-01 15:40
@engcom-Dash 
The problem is that this Cart Price Rule used to cause "Flat Rate" to cost €0.00 not add an extra shipping option!

What if we always offered Free Shipping for slow delivery and used "Flat Rate" for next day delivery?
What if we integrate with a third party shipping partner?

> The "Free Shipping" delivery method did not use to be required and is a different method all together.
> The goal of a cart rule is to lower the price of specific shipping methods.

**Comment by engcom-Dash** [comment] 2023-03-14 08:40
Hi @pixel-paul ,

We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-Dash** 2023-03-14 08:40 UTC
Labels: Issue: needs update, Reported on 2.4.5

**Comment by dtamajon** [comment] 2023-04-02 07:15
Hi,

We are having the same issue with discounts. We cannot use "Free shipping" method because we have more complex options to decide if the shipping is free or not. 

Force to use the "Free shipping" method is not a solution for our case.

**Comment by fharms** [comment] 2023-05-25 06:33
We had the same issue after upgrading to 2.4.5-p2 the free shipping stopped working. After some debugging I found out that the issue was in one of our 3 party extension handling shipments.

They are expecting type boolean. `if ($request->getFreeShipping() === true) {...}`, but that will not work because the type containing the information if it free shipping or not, was specific casted to an int in this commit.
https://github.com/magento/magento2/commit/bd149447d03f30dfd7cbda19c28a8140a87e0c9f#diff-857bf9d4a0e8e8b036a3fcf5687e2dbe7f8a4b83ad3ebdabcb0ad66ae0dc7d38

Because of this change it breaks backward compatibility for 3 party extensions, that expected it is a boolean type

**Comment by marcomessa** [comment] 2023-12-19 15:34
Thank you guys for these informations. I put a simple module to apply @vipinroy commit in a preference, if you need.
https://github.com/marcomessa/FixMagento2FreeShippingCartRule

Cheers

**Comment by CptCharlesG** [comment] 2024-04-21 16:14
Same issue on 2.4.7-p4.

**Comment by pixel-paul** [comment] 2024-05-30 20:13
I've updated to M246-p5 and I've had to apply this patch by @danhort to get the free shipping to work.

I have table rates enabled and click & collect, I do not use a third party checkout.....very coincidental if this is not a bug in my opinion.

**Comment by engcom-Dash** [comment] 2024-06-03 12:19
Hi @pixel-paul 

Thanks for reporting and collaboration.

Verified the issue on magento 2.4 dev instance and the issue is not reproducable.

Steps to reproduce:
Steps are followed to reproduce the issue
(we have followed the steps which are mentioned in this link https://docs.magento.com/user-guide/marketing/price-rules-cart-free-shipping.html )
Created cart price rule for free shipping

We can see the free shipping applied with cart price rule.

Please take a look at the screenshots I've attached. Let us know if we missed anything.

<img width="1440" alt="35967_1" src="https://github.com/magento/magento2/assets/60198592/4bebcd6b-d715-43ab-ab77-0e34f6649baf">

**Comment by jenn0pal** [comment] 2025-03-28 02:38
> Hi [@pixel-paul](https://github.com/pixel-paul)
> 
> Thanks for reporting and collaboration.
> 
> Verified the issue on magento 2.4 dev instance and the issue is not reproducable.
> 
> Steps to reproduce: Steps are followed to reproduce the issue (we have followed the steps which are mentioned in this link https://docs.magento.com/user-guide/marketing/price-rules-cart-free-shipping.html ) Created cart price rule for free shipping
> 
> We can see the free shipping applied with cart price rule.
> 
> Please take a look at the screenshots I've attached. Let us know if we missed anything.
> 
> <img alt="35967_1" width="1440" src="https://private-user-images.githubusercontent.com/60198592/336066502-4bebcd6b-d715-43ab-ab77-0e34f6649baf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDMxMjk2NjksIm5iZiI6MTc0MzEyOTM2OSwicGF0aCI6Ii82MDE5ODU5Mi8zMzYwNjY1MDItNGJlYmNkNmItZDcxNS00M2FiLWFiNzctMGUzNGY2NjQ5YmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI4VDAyMzYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNzlkYmJmZTI4NzZhMmJkNDY1YjQ1MDUwYmVmOTc3M2NhOWJiMmEyZDQxZDVlY2Y4YzllYzA5Yjg2ZTdiYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gcNjBR4lk1CB2BhCrnAOuM6WsYNe56YGBnK1DC58aGI">

I tried this setup,
Free shipping method is selectable regardless if cart price rule is enabled or not.
