### ISSUE TITLE
CC validation incorrectly identifies some cards as Maestro Domestic

### ISSUE THREAD

**Issue by rhoerr** [magento/magento2#36332] opened 2022-10-19 17:07 UTC
### Preconditions and environment

- Magento version 2.4.5-p1
- A payment method that uses Magento's native `'Magento_Payment/js/model/credit-card-validation/credit-card-number-validator` credit card number validator/type detection

### Steps to reproduce

1. Go to checkout
2. Select payment method that uses Magento native type detection and CC validation
3. Enter card number "4111 6767 7011 1115"

### Expected result

Credit card should be identified as a valid Visa CC number and allow order placement.

### Actual result

Credit card is matched as both Visa and Maestro, fails to identify the specific card type, and blocks checkout submission.

Any customers affected by this issue will find themselves unable to place order and complete checkout with that credit card.

### Additional information

The problem is the Maestro Domestic type definition: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Payment/view/base/web/js/model/credit-card-validation/credit-card-number-validator/credit-card-type.js#L106

```
        {
            title: 'Maestro Domestic',
            type: 'MD',
            pattern: '^6759(?!24|38|40|6[3-9]|70|76)|676770|676774\\d*$',
            gaps: [4, 8, 12],
            lengths: [12, 13, 14, 15, 16, 17, 18, 19],
            code: {
                name: 'CVC',
                size: 3
            }
        },
```

As written, the pattern will match any number starting with `6759[...]`, or containing `676770`, or containing `676774`. Any credit card number that happens to contain those two number sequences will fail validation and be unable to check out.

To fix it, the pattern should be wrapped in parentheses so the ^ flag applies to all three sequences:

```
            pattern: '^(6759(?!24|38|40|6[3-9]|70|76)|676770|676774)\\d*$',
```

In a brief look, it does not appear any other CC types or number sequences are affected.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-10-20 04:29
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-10-20 05:13
Hi @rhoerr ,
Thank you for reporting and collaboration. Verified the behavior on Magento 2.4-develop instance and Maestro Card is not listed as supported payment card when configuring credit card payments (Checked for all payment methods Ex: payflow pro, payments pro). Hence above mentioned card details are not working on store-front.
![image](https://user-images.githubusercontent.com/60198231/196861724-5e9f47bb-7f0c-43b9-9ab8-a1860076d7a9.png) . 
Kindly use any of the supported CC payment methods and elaborate missing steps if any if the issue is still reproducible.
Thank you.

**Comment by rhoerr** [comment] 2022-10-20 12:09
> Thank you for reporting and collaboration. Verified the behavior on Magento 2.4-develop instance and is reproducible. But however CC payment is working fine for other test VISA card details: Ex: 4111 1111 1111 1111, 4500600000000061, 4012888888881881
> Can you please check if the mentioned card is a valid VISA card and elaborate missing steps if any if the issue is still reproducible.
> Thank you.

That's expected. This issue ONLY affects card numbers (of any type) that contain the exact number sequences "676770" or "676774". Other Visa cards will validate correctly. Numbers containing 676770 or 676774 will not.

The number I gave is a valid Visa number, as it starts with 4, has 16 digits, and [passes luhn10 validation](http://www.ee.unb.ca/cgi-bin/tervo/luhn.pl?N=4111+6767+7011+1115).

You can also see the type conflict directly by trying different numbers after `4111 6767 7`. That number will be identified as Visa. Following that with a 0 or 4 (to complete the Maestro sequence) will no longer be identified as Visa. Any other number (1, 2, 3, 5, 6, 7, 8) will still be identified as Visa. All should be Visa, because only card numbers _starting with_ 67677(0|4) are Maestro.

Thanks

**Comment by engcom-November** [comment] 2022-10-25 11:59
Thank you for the response @rhoerr . Rechecked again and agree with you that "4111 6767 7011 1115" is a valid VISA number but still the payment is getting declined due to number containing "676770". Mentioned card is not a Maestro card but is a valid VISA card but CC validation fails due to card being considered as Maestro. Hence confirming this issue.

**Comment by engcom-November** [comment] 2023-03-13 09:07
Hi @rhoerr ,
We re-checked the issue again on Magento 2.4-develop instance and after checking the code base, it has been concluded that the card validation is not failing due to being identified as Maestro card but the card is identified as VISA credit card only. To confirm the same, checked the issue only with VISA card validations in code-base by removing all other card validations in credit-card-type.js, /lib/web/mage/validation.js etc and other files and the card payment is still failing (even after removing Maestro card validation condition from code base, payment is failing with '4111 6767 7011 1115' number). Payment is failing with error: `main.CRITICAL: Placing an order with quote_id 11 is failed: Your payment could not be taken. Please try again or use a different payment method. Credit card number is not an accepted test number. [] []`
Note: This 4111 6767 7011 1115 is referring to VISA card on Storefront, but rejected by Server. Hence seems like this credit card number is either not a valid test VISA number or a blocked / blacklisted by VISA. @rhoerr kindly recheck the issue on 2.4-develop instance and confirm us whether this is a valid test VISA credit card number and let us know your inputs on this.
Thank you.

**Comment by engcom-November** [comment] 2023-03-28 05:18
Hi @rhoerr ,
We have tested the scenario again with mentioned steps and it's failing even after taking the PR https://github.com/magento-gl/magento2ce/pull/796/ changes.

**NOTE: It seems this card is blocked (or might be not in working state) by Visa.** 
Please find the attached payment.log
[payment.log](https://github.com/magento/magento2/files/11085585/payment.log)
![image](https://user-images.githubusercontent.com/60198231/228135358-cb75846a-9c7d-4e6d-81d2-4e16abab5f3a.png)

**Comment by Silarn** [comment] 2023-04-04 18:10
I can confirm this issue and believe we may have a customer that's experiencing this bug.

I will also point out that the lib/mage/validator.js also has the same issue with the regex and would also need to be corrected.

Simply overriding these files and adding additional capture groups resolved the issue as stated by @rhoerr.

**Comment by Silarn** [comment] 2023-04-04 18:34
@engcom-November Please note that this is an issue with the JavaScript validator NOT with the actual card processor. This is not about it being a valid number when submitting to a transaction, this is about the form even allowing you to submit the card number for payment.

Because of the issue, the customer doesn't even have the option of submitting the card, whether it's valid or not, because the form validator will not let them continue.

**Comment by engcom-Bravo** [comment] 2023-05-12 11:34
Hi @rhoerr,

@rhoerr, we have done some more analysis and looks like this VISA test number validation depends on the payment vendor as some of the vendors doesn’t allow many numbers for testing purposes. 

For instance, take braintree’s example where this number is not valid and we are getting response as ‘Credit card number is not an accepted test number.’ with response code 81717. You can find error documentation in https://developer.paypal.com/braintree/docs/reference/general/validation-errors/all/php#code-81717

Now, can you please provide the info on which payment method you are able to reproduce this issue ? We’ll do further analysis accordingly.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-05-31 06:11
Hi @rhoerr,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by rhoerr** [comment] 2023-05-31 12:02
This was not fixed.

**Comment by Silarn** [comment] 2023-05-31 14:08
> @rhoerr, we have done some more analysis and looks like this VISA test number validation depends on the payment vendor as some of the vendors doesn’t allow many numbers for testing purposes.
> 
> For instance, take braintree’s example where this number is not valid and we are getting response as ‘Credit card number is not an accepted test number.’ with response code 81717. You can find error documentation in https://developer.paypal.com/braintree/docs/reference/general/validation-errors/all/php#code-81717
> 
> Now, can you please provide the info on which payment method you are able to reproduce this issue ? We’ll do further analysis accordingly.
> 
> Thanks.

I'm not sure where the communication breakdown is here, but as we've both stated the issue has nothing to do with the actual payment processing. It's a bug in the JavaScript validation which prevents numbers with specific number sequences from being submitted because of a bug in the regex pattern.

We've had at least one legitimate customer unable to check out until I patched this.

**Comment by engcom-Bravo** [comment] 2023-06-01 08:50
Hello,

We are re-opening this issue for further investigation.

Thanks.

**Comment by engcom-Delta** [comment] 2024-04-25 13:29
Hi @rhoerr , 

As the related PR (https://github.com/mage-os/mageos-magento2/pull/38) has been merged on [on Oct 7, 2023](https://github.com/mage-os/mageos-magento2/pull/38#event-10582370883), we are closing this issue.

Thanks,

**Closed as completed by engcom-Delta** 2024-04-25 13:29 UTC
Labels: Component: Payment, Priority: P2, Progress: done, Issue: needs update, Area: Payments, Reported on 2.4.5-p1

**Comment by rhoerr** [comment] 2024-04-25 14:42
> Hi @rhoerr ,
> 
> As the related PR ([mage-os/mageos-magento2#38](https://github.com/mage-os/mageos-magento2/pull/38)) has been merged successfully on [on Oct 7, 2023](https://github.com/mage-os/mageos-magento2/pull/38#event-10582370883), we are closing this issue.
> 
> Thanks,

Hi, that PR was merged to Mage-OS, not to Magento. The code can certainly be ported in, but this issue is still outstanding and unresolved in Magento Open Source.
