### ISSUE TITLE
Cannot find the way back to Magento Backend

### ISSUE THREAD

**Issue by addison74** [magento/magento2#4512] opened 2016-05-15 14:56 UTC
1) Go to Backend -> System -> Web Setup Wizard. 

2) Click on Magento logo on the left side at the top, to go back seeing all sections. You can't, you are stuck into this section. The only way is to use Back button from browser.

**Comment by mazhalai** [comment] 2016-05-15 22:59
@ADDISON74 this is intentional, since web setup wizard may start a job, and the magento application (including admin) may not be in a stable state, since either modules are being enabled/disabled or system upgrade it taking place.  Closing since this is not a bug.

**Closed as completed by mazhalai** 2016-05-15 22:59 UTC
