### ISSUE TITLE
B2B prices in quote add VAT each time page reload

### ISSUE THREAD

**Issue by AMishchan** [magento/magento2#33619] opened 2021-07-28 14:32 UTC
### Preconditions (*)

1. Enabled magento/extension-b2b and magento/module-negotiable-quote functional
2. Set Stores->Configuration->Sales->Tax->Calculation Settings->Catalog Price to "Including Tax"

### Steps to reproduce (*)

1.Add product to cart
2. On a cart page click "Request a Quote"
3. Open quote in admin panel and add "Negotiated Price", "Amount Discount" for example. Click "Send".
4. Open Quote in a customer account, after each page reload prices increase according to VAT (10% in this case).
5. Reply for a quote with a comment on a customer account quote page (in this case after reply submit totals do not increase but totals starts increase on a admin panel quote page)
6. Reply and click "Send" from admin page -> totals starts increase on a customer account quote page again.
7. Set Stores->Configuration->Sales->Tax->Calculation Settings->Catalog Price to "Excluding Tax"  and totals calculates correct.

### Expected result (*)

1. 
![Quote Calculate ](https://user-images.githubusercontent.com/25375571/127340352-2f74f194-4f57-4c91-a705-b79c515e9b2f.png)
![Quote Calculate  (1)](https://user-images.githubusercontent.com/25375571/127340366-68dc101d-1eaa-4176-bc65-620c4b68ee2c.png)
![Quote Calculate  (2)](https://user-images.githubusercontent.com/25375571/127340387-9c0ca7c7-ec32-4198-9c43-b8431da5325c.png)
![My Quotes](https://user-images.githubusercontent.com/25375571/127340399-5f0d0bd7-821c-465d-a048-fb1955e9ad63.png)
![Quote #13 _ Oper](https://user-images.githubusercontent.com/25375571/127340409-d597fda4-0168-468c-9eef-39c0fc9b1173.png)
![Quote #13 _ Oper (1)](https://user-images.githubusercontent.com/25375571/127340415-40fa7a15-7fc1-4ca6-ae05-5965cb793417.png)

2. Totals do not increase in any case after page reload

### Actual result (*)

1. [Screenshots, logs or description]
2.Totals increase after each page reload

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Zayander** [comment] 2021-07-28 14:46
My composer.json file content: 
{
    "name": "magento/project-enterprise-edition",
    "description": "eCommerce Platform for Growth (Enterprise Edition)",
    "type": "project",
    "license": [
        "proprietary"
    ],
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    },
    "version": "2.4.2-p1",
    "require": {
        "magento/composer-root-update-plugin": "~1.1",
        "magento/extension-b2b": "^1.3",
        "magento/module-negotiable-quote": "^100.3",
        "magento/product-enterprise-edition": ">=2.4.2 <2.4.3"
    },
    "autoload": {
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ],
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "psr-0": {
            "": [
                "app/code/",
                "generated/code/"
            ]
        },
        "psr-4": {
            "Magento\\": "app/code/Magento/",
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Zend\\Mvc\\Controller\\": "setup/src/Zend/Mvc/Controller/"
        }
    },
    "require-dev": {
        "allure-framework/allure-phpunit": "~1.2.0",
        "dealerdirect/phpcodesniffer-composer-installer": "^0.7.0",
        "friendsofphp/php-cs-fixer": "~2.16.0",
        "lusitanian/oauth": "~0.8.10",
        "magento/magento-coding-standard": "*",
        "magento/magento2-functional-testing-framework": "^3.0",
        "pdepend/pdepend": "~2.7.1",
        "phpcompatibility/php-compatibility": "^9.3",
        "phpmd/phpmd": "^2.8.0",
        "phpstan/phpstan": ">=0.12.3 <=0.12.23",
        "phpunit/phpunit": "^9",
        "sebastian/phpcpd": "~5.0.0",
        "squizlabs/php_codesniffer": "~3.5.4"
    },
    "conflict": {
        "gene/bluefoot": "*"
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\PhpStan\\": "dev/tests/static/framework/Magento/PhpStan/",
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "repositories": {
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    },
    "extra": {
        "magento-force": "override",
        "patches-search": "patches"
    }
}

**Comment by engcom-November** [comment] 2021-08-03 13:21
Verified the issue on Magento 2.4-develop branch having B2B Modules enabled and the issue is not reproducible:

**Steps performed:**

Admin - Stores - Configuration - General - Enable B2B Features and Save 
Stores->Configuration->Sales->Tax->Calculation Settings->Catalog Price to "Including Tax"
Create a Company Account (Customers - Company - Add New Company)
Reset password - Customers - All Customers - Edit the customer - Reset Password
Login to Store-front as a Company Administrator
Add a product to Cart
Navigate to Shopping Cart Page - Click on Request a Quote - Send Request
Open the Quote from Admin - Sales - Quotes - View Quote - add "Negotiated Price" -  "Amount Discount" for example. Click "Send".
Open Quote in a customer account (Front-end) - **No issue in Price Total displayed as expected.**
Refresh the page - No issue
5. Reply for a quote with a comment on a customer account quote page (Front-end)
6. Reply and click "Send" from admin page -> **No issue. Price values are displayed as expected in Front end**
7. Reload the page - No issue

![image](https://user-images.githubusercontent.com/60198231/128022318-d0206949-2f02-4b32-9762-757b22c51332.png)
![image](https://user-images.githubusercontent.com/60198231/128022343-e543a806-aa8f-4289-a91d-669148edadfc.png)
@Zayander,
Kindly recheck the issue on Magento 2.4-develop branch and provide the missing steps if any if the issue is still reproducible.
Thank you

**Comment by engcom-November** [comment] 2021-08-17 06:07
@AMishchan, we are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-08-17 06:07 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
