### ISSUE TITLE
Category tree in Cart Price Rules is not rendered correctly

### ISSUE THREAD

**Issue by annukka-tormala** [magento/magento2#39312] opened 2024-10-30 12:46 UTC
### Preconditions and environment

Magento version 2.4.7-p1

### Steps to reproduce

1. Navigate to Cart Price Rules from admin (Marketing > Promotions > Cart Price Rules > [some rule] )
2. Go to Actions tab and apply category rule (Actions > Apply the rule only to cart items matching the following conditions > Select category)

### Expected result

All the subcategories should be visible in the category tree.

### Actual result

Only categories 3 levels deep are rendered.

**Screenshot from category tree from Cart Price Rules condition:** 
![brokentree](https://github.com/user-attachments/assets/b895f10c-1cf4-4474-ae32-be10d492f496)

**Screenshot from the category tree from Catalog>Inventory>Categories from admin:** 
As you can see, all the subcategories are rendered here, but not in the Cart Price Rules condition category tree
![workingtree](https://github.com/user-attachments/assets/6d29a3fd-4630-44a5-8062-457b9e0042e2)

### Additional information

This seems to have happened in 2.4.7 when the extjs library was replaced with the latest version of jsTree. Related commit: https://github.com/magento/magento2/commit/4bfcc46c542101ecbd96ea1baff5a540b71b17bc#diff-64ae3799eb8d244fd03f20f4ea01674fdab57167f773924837a36871311d2985

Note: similar issue in categories was fixed earlier: https://github.com/magento/magento2/issues/38851#issuecomment-2345340785

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment] 2024-10-30 13:05
No idea if the category tree widget is used by price rules, but if it does, maybe https://github.com/magento/magento2/issues/39008#issuecomment-2427670552 fixes your issue?

**Comment by annukka-tormala** [comment] 2024-10-30 13:11
> No idea if the category tree widget is used by price rules, but if it does, maybe [#39008 (comment)](https://github.com/magento/magento2/issues/39008#issuecomment-2427670552) fixes your issue?

Unfortunately no, that widget category tree template is not used by the price rules.

**Comment by engcom-Bravo** [comment] 2024-11-04 04:56
Hi @annukka-tormala,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Navigate to Cart Price Rules from admin (Marketing > Promotions > Cart Price Rules > [some rule] )
- Go to Actions tab and apply category rule (Actions > Apply the rule only to cart items matching the following conditions > Select category)


<img width="768" alt="Screenshot 2024-11-04 at 10 18 18" src="https://github.com/user-attachments/assets/88a365cd-1ad7-4288-b0a9-77f23fede7bd">




<img width="768" alt="Screenshot 2024-11-04 at 10 19 23" src="https://github.com/user-attachments/assets/d6b40bd6-a25b-4778-8a29-199aa5899c13">


All the subcategories are visible in category tree.

Thanks.

**Comment by annukka-tormala** [comment] 2024-11-04 05:45
@magento give me 2.4.7-p1 instance

**Comment by annukka-tormala** [comment] 2024-11-04 05:54
@magento give me 2.4.7 instance

**Comment by annukka-tormala** [comment] 2024-11-04 06:20
![categorytreeincategory](https://github.com/user-attachments/assets/3ee4809c-62a4-43d1-b827-b2830e5b72a4)
![categorytreeintrules](https://github.com/user-attachments/assets/4a452c91-8692-44d8-9e2c-6b3a73feaa6b)

**Comment by annukka-tormala** [comment] 2024-11-04 06:23
Hi, I was able to reproduce this with categories that have products in it. In your screenshot the sub-categories are empty. With sub-categories being empty, the category tree is rendered correctly.

![categorytreeincategory](https://github.com/user-attachments/assets/3157cfe4-2c0e-4160-8c93-2377115babba)
![categorytreeintrules](https://github.com/user-attachments/assets/e1c0b7a1-a67b-42c2-84e6-355b7a6efb21)

As you can see, the category Women>Tops>Jackets is still missing the two subcategories

**Comment by engcom-Bravo** [comment] 2024-11-05 09:14
Hi @annukka-tormala,

Thanks for your update.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

<img width="730" alt="Screenshot 2024-11-05 at 09 28 09" src="https://github.com/user-attachments/assets/8a52df48-8b1f-4850-b481-98ecd4a5134b">



<img width="730" alt="Screenshot 2024-11-05 at 09 29 27" src="https://github.com/user-attachments/assets/bcf42f63-b7a8-4846-8c0e-4a00b7562974">


The sub-categories with products are rendered correctly.

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by annukka-tormala** [comment] 2024-11-05 09:36
@magento give me 2.4-develop instance

**Comment by annukka-tormala** [comment] 2024-11-05 10:43
Hi, the issue seems to happen when the category tree is more complex. So could you add more sub-categories on your test categories (and products into it)?. Tested this again and was able to reproduce this with the following category tree:
![categorytreeincategory](https://github.com/user-attachments/assets/2b026b3f-8277-4d68-a63b-45959989a58e)

The same tree in Cart Price Rules ("Deep Test" category is missing):
![brokentree](https://github.com/user-attachments/assets/d41c66fa-c3cf-49c0-96a9-229f01fd436f)

Here is an another example of a simpler category tree where the issue doesn't happen (in Cart Price Rules):
![simple](https://github.com/user-attachments/assets/fb7d5dee-0cad-4f8b-87fe-b2e6da36bfcf)

Tested with Magento version 2.4.7.

**Comment by engcom-Bravo** [comment] 2024-11-07 05:33
Hi @annukka-tormala,

Thanks for your update.

We have verified the issue in Latest 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.

<img width="492" alt="Screenshot 2024-11-07 at 10 55 56" src="https://github.com/user-attachments/assets/d247c86e-1736-47f6-a3e9-0e69e808d03e">



<img width="492" alt="Screenshot 2024-11-07 at 10 59 29" src="https://github.com/user-attachments/assets/d92922d8-41b8-4fdf-8f7f-e643c2a9c3d4">


The Sub-Categories are not rendered correctly.

Hence Confirming the issue.


Thanks.

**Comment by hostep** [comment] 2024-11-21 08:13
Possible fix: [ACP2E-3406: Nested categories in rule conditions not showing](https://github.com/magento/magento2/commit/57253e928c5163f25c5b85c3992e8e7a11d41405)?

**Comment by engcom-Bravo** [comment] 2024-11-22 06:10
@hostep Thanks for your Contribution!!!.

Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket ACP2E-3406 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-3406&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta2.

Thanks

**Closed as completed by engcom-Bravo** 2024-11-22 06:10 UTC
Labels: Component: Catalog, Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Performance, Reported on 2.4.7-p1
