### ISSUE TITLE
Product save does not update URL rewrites for all store views in Magento 2.4.5-p1 if URL Key is preset on store view scope different from the saved one

### ISSUE THREAD

**Issue by kanevbg** [magento/magento2#36733] opened 2023-01-11 21:12 UTC
### Preconditions and environment

- Verified on Magento 2.4.5-p1 with it's  DEMO data

### Steps to reproduce

0. Use Magento 2.4.5-p1 with the official DEMO data
1. Navigate to admin panel
2. Open product with ID=2024
3. Add the product to the "DE" website. Check url_rewrite, with proper knowledge on place you will understand that they are correct.
4. Switch the scope to "DE View", set the URL Key "url-key-in-de-store-view", unset the "Create Permanent Redirect for old URL" checkbox (in order to keep the data simpler) and save the product. Again you should understand that the data for that product in url_rewrites table is correct at this time.
5. Now switch back to Global scope for the product, remove the product's categories leaving only the "Default Category" and save the product. Now the url_rewrites table will hold the following data:
![image](https://user-images.githubusercontent.com/11477130/211918061-6584f7ab-8e40-44cf-8e50-95e17a6c35dd.png)
If you know the algorithms you will understand that the rows marked with X on the image above should not be existing too as the product at that time is not in these categories anymore.
If the categories were removed from the "DE View" store view you would not observe the issue as it will not happen.

### Expected result

Only two records to exists in the url_rewrite table for "entity_type = "product" and entity_id = 2024" as the product in not in ANY categories, only the root category, so one URL without category should exists per each store view the product is added in.

### Actual result

The url_rewrite table hold obsolete URLs which were used for categories the product was previously added in for the store "DE View".

### Release note

Fixes issue where product save does not update URL rewrites for all store views in Magento 2.4.5 if URL Key is preset on store view scope different from the saved one from the admin panel.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-01-12 11:40
Hi @kanevbg,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible. Kindly refer the screenhsots.


**Steps to reproduce** :


1.Navigate to admin panel
2.Open product with ID=2092
3.Add the product to the "DE" website. Check url_rewrite, with proper knowledge on place you will understand that they are correct.
4.Switch the scope to "DE View", set the URL Key "url-key-in-de-store-view", unset the "Create Permanent Redirect for old 5.URL" checkbox (in order to keep the data simpler) and save the product. Again you should understand that the data for that product in url_rewrites table is correct at this time.
6.Now switch back to Global scope for the product, remove the product's categories leaving only the "Default Category" and save the product. Now the url_rewrites table will hold the following data:





<img width="1460" alt="Screenshot 2023-01-12 at 2 12 10 PM" src="https://user-images.githubusercontent.com/51680745/212057236-f17c1466-4d97-4dc3-a5be-1d27731c5b34.png">



<img width="944" alt="Screenshot 2023-01-12 at 2 11 53 PM" src="https://user-images.githubusercontent.com/51680745/212057364-17cb07ea-d350-4b86-bac5-39d1c9916cb9.png">



We are getting only two records in url_rewrite table.


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by kanevbg** [comment] 2023-01-12 12:56
@engcom-Bravo the Magento Instance provided by the bot is not having second website, I'd have to check that later on local instance.

**Comment by engcom-Bravo** [comment] 2023-01-12 13:02
Thanks for quick response @kanevbg

**Comment by kanevbg** [comment] 2023-01-12 14:53
I compared 2.4.5-p1 sources to the 2.4-develop source and identified change in the Magento_CatalogUrlRewrite module which pointed me to that commit: https://github.com/magento/magento2/commit/e46f719559924e703ef3c7fdc728ec1b232a7509

This is what resolved the issue, so yes, it is fixed in 2.4-develop already.

**Comment by hostep** [comment] 2023-01-12 20:37
@kanevbg: your new problematic case sounds related to what is trying to be fixed here: https://github.com/magento/magento2/pull/35053, not sure if it's exactly the same though.

**Comment by engcom-Bravo** [comment] 2023-01-13 13:46
@hostep Thanks for your contribution & collaboration over here.

Hi @kanevbg,

Thanks for your update.

Kindly can you update can we close this as duplicate of https://github.com/magento/magento2/issues/32910.

Thanks.

**Comment by kanevbg** [comment] 2023-01-15 12:07
@engcom-Bravo Please re-test with the case described in the edit of that comment: https://github.com/magento/magento2/issues/36733#issuecomment-1380491110 in order to decide if the issue needs updating or is ready for work.

**Comment by engcom-Bravo** [comment] 2023-01-16 13:23
Hi @kanevbg,

Thanks for your update.

Kindly can you elaborate the steps for this comment https://github.com/magento/magento2/issues/36733#issuecomment-1380491110 it will helpful for us.


Thanks.

**Comment by kanevbg** [comment] 2023-01-24 13:21
@engcom-Bravo Sure, sorry for being late.

### Steps to reproduce

0. Use Magento 2.4.5-p1 with the official DEMO data, but create one or more websites and their sub-entities (store group and store view). EG: create website for "FR" and "BG"
1. Navigate to admin panel
2. Open product with ID=2024
3. Add the product to all of the rest websites (at least 3 in total). Check url_rewrite, with proper knowledge on place you will understand that they are correct for each store view.
4. Switch the scope to "DE View", set the URL Key "url-key-in-de-store-view", unset the "Create Permanent Redirect for old URL" checkbox (in order to keep the data simpler) and save the product. Again you should understand that the data for that product in url_rewrites table is correct at this time.
5. Repeat step 4 for the rest of store view scopes. The exact value of the URL Key is not important, it is important to have a value on store view scope and _not_ "Use default/Use website". Again you should understand that the data for that product in url_rewrites table is correct at this time.
6. Now switch back to **DE store view scope** for the product, remove the product's categories leaving only the "Default Category" and save the product. Now the url_rewrites table will still hold data for the rest of the store views with the removed categories of the product even though that the categories are per global scope and they were removed from the product.

### Expected result

url_rewrite table for "entity_type = "product" and entity_id = 2024" to hold only URLs without categories.

### Actual result

The url_rewrite table holds obsolete URLs which were used for prouduct's URLs with categories the product was previously added in for the store views different from the saved one - "DE View" in the example above.

**Comment by kanevbg** [comment] 2023-01-24 19:50
@magento give me 2.4-develop instance

**Comment by kanevbg** [comment] 2023-01-25 14:23
@engcom-Bravo let me know if you need anything else.

**Comment by kanevbg** [comment] 2023-01-26 19:29
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-01-27 11:42
Hi @kanevbg,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible. Kindly refer the screenhsots.

Steps to reproduce :

1.Navigate to admin panel
2.Open product with ID=2024
3.Add the product to all of the rest websites (at least 3 in total). Check url_rewrite, with proper knowledge on place you will understand that they are correct for each store view.
4.Switch the scope to "DE View", set the URL Key "url-key-in-de-store-view", unset the "Create Permanent Redirect for old URL" checkbox (in order to keep the data simpler) and save the product. Again you should understand that the data for that product in url_rewrites table is correct at this time.
5.Repeat step 4 for the rest of store view scopes. The exact value of the URL Key is not important, it is important to have a value on store view scope and not "Use default/Use website". Again you should understand that the data for that product in url_rewrites table is correct at this time.
6.Now switch back to DE store view scope for the product, remove the product's categories leaving only the "Default Category" and save the product. Now the url_rewrites table will still hold data for the rest of the store views with the removed categories of the product even though that the categories are per global scope and they were removed from the product.



<img width="1437" alt="Screenshot 2023-01-27 at 2 44 56 PM" src="https://user-images.githubusercontent.com/51680745/215077734-de7ccc3a-7d0f-4912-a380-e4e78c6b3f93.png">


<img width="1489" alt="Screenshot 2023-01-27 at 4 29 11 PM" src="https://user-images.githubusercontent.com/51680745/215077828-2fc26fea-b472-45d9-8aae-e6475db3b2af.png">



<img width="992" alt="Screenshot 2023-01-27 at 2 44 48 PM" src="https://user-images.githubusercontent.com/51680745/215077917-3f33bd48-4d80-4b05-9877-702ab7f013a5.png">




KIndly let us know if we are missing anything.


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-02-09 06:10
Hi @kanevbg,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-02-09 06:10 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1
