### ISSUE TITLE
Bundle Product with Multiple Sources is not working

### ISSUE THREAD

**Issue by i95devdivya** [magento/magento2#37767] opened 2023-07-18 09:00 UTC
### Preconditions and environment

- Magento version 2.4.4
- PHP 8.1

### Steps to reproduce

1. Create different simple products by assigning multiple source and quantity
2. Create bundle product by assigning the above created simple products to it from Magento admin
3. Please check the below screen-cast for the same.

https://github.com/magento/magento2/assets/25501098/25e00762-4847-4fc2-b256-ad73de44dbb3

### Expected result

Bundle product has to be created successfully.

### Actual result

Unable to create Bundle Product and getting error like "Product "1003" cannot be added to bundle product as bundle product has "Ship Bundle Items Together" and "1003" product assigned to multiple sources or has different source then rest of bundle items"

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-07-18 10:02
@magento give me 2.4-develop instance

**Comment by i95devdivya** [comment] 2023-07-18 10:04
@engcom-Bravo We are using ship together option while creating bundle product.

**Comment by engcom-Bravo** [comment] 2023-07-18 12:35
Hi @i95devdivya,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

It is working as expected and it is an expected behaviour of Magento 2.

As per Magento devdocs if we select together all bundle items must be assigned from the same source.


<img width="1030" alt="Screenshot 2023-07-18 at 3 59 09 PM" src="https://github.com/magento/magento2/assets/51680745/006c0eef-25bd-4715-8752-3bd39d1db8d3">


Please refer this document https://experienceleague.adobe.com/docs/commerce-admin/catalog/products/types/product-create-bundle.html?lang=en#step-5%3A-add-the-bundle-items and please let us know if you are still facing any issue.


Thanks.

**Comment by i95devdivya** [comment] 2023-07-18 12:40
@engcom-Bravo I created 2 simple product and assigned 2 sources named MAIN, EAST with quantity 100, 50. When I am trying to create bundle with the created simple products with ship together option, it is throwing an error.

When I assigned only 1 source, bundle product creation is working fine.

**Comment by engcom-Bravo** [comment] 2023-07-19 12:37
Hi @i95devdivya,

Thanks for your update.

As per this document https://experienceleague.adobe.com/docs/commerce-admin/catalog/products/types/product-create-bundle.html?lang=en#step-5%3A-add-the-bundle-items.when we select **Ship Bundle Items** to **Together** the simple products should be assigned to single source only.(**all bundle items must be assigned the same source**).It is working as expected.Please refer the document.

<img width="1030" alt="Screenshot 2023-07-18 at 3 59 09 PM" src="https://github.com/magento/magento2/assets/51680745/f02fa92e-95e8-4192-8285-c55712a213d4">




Kindly let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-07-31 06:18
Hi @i95devdivya,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-07-31 06:18 UTC
Labels: Issue: needs update, Reported on 2.4.4
