### ISSUE TITLE
Assign source

### ISSUE THREAD

**Issue by anamaria1403** [magento/magento2#39198] opened 2024-09-22 04:54 UTC
### Summary

Every time I click assign a source to add each qty for the product always shows an error message. Done waiting 15 to 30 minutes to try again but still the same. 

### Examples

![assign sources error 1](https://github.com/user-attachments/assets/8384bbf3-04a7-480a-b732-d979e13cdbf0)
![assign sources error](https://github.com/user-attachments/assets/62481d95-f66d-469a-9b06-58a18433ee08)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-09-23 06:43
Hi @anamaria1403,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

![COnfigureee-Products-Inventory-Catalog-Magento-Admin-09-23-2024_12_09_PM](https://github.com/user-attachments/assets/29cc5395-2eef-46fd-ab32-43de55f81abb)



We are able to assign a source to the product.

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-10-04 04:30
Hi @anamaria1403,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Bravo** 2024-10-04 04:30 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.x
