### ISSUE TITLE
Urlresolver does not resolve path "/" correctly when multiple homepages has the same identifier

### ISSUE THREAD

**Issue by capkafitz** [magento/magento2#33615] opened 2021-07-28 11:47 UTC
### Preconditions (*)
1. Magento 2.4.0

### Steps to reproduce (*)
1. Create for multiple stores a cms page with the same identifier (in this case 'home').
2. Go to **Configuration** > **General** > **Web** > **Default Pages**
3. Set for each store the newly created page as homepage, example in the database:
![image](https://user-images.githubusercontent.com/2599558/127316302-f297ba2b-2772-40d6-abc3-a7cd3d269db1.png)
4. Execute graphQl query urlresolver:
![image](https://user-images.githubusercontent.com/2599558/127316441-2469d82c-bf48-4da8-8c72-229a97d15a45.png)
5. Result for default store (stored in database without delimiter):
![image](https://user-images.githubusercontent.com/2599558/127316508-b41a7a58-f335-4f7d-b094-cac31a1b488e.png)
6. Result for store where homepage value is stored in database with delimiter:
![image](https://user-images.githubusercontent.com/2599558/127316586-2eff648a-0047-45f7-ad81-2e352df9d306.png)

****

### Expected result (*)
1. Result for store where homepage value is stored in database with delimiter should have a correct url resolver response:
![image](https://user-images.githubusercontent.com/2599558/127316796-b224b1c2-f8b0-4906-89eb-6ea9df1b6a0c.png)

### Actual result (*)
1. Actual result equals null
![image](https://user-images.githubusercontent.com/2599558/127316586-2eff648a-0047-45f7-ad81-2e352df9d306.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by capkafitz** [comment] 2021-07-28 12:10
@magento give me 2.4-develop instance

**Comment by capkafitz** [comment] 2021-07-28 12:28
I can confirm it is reproducible on the 2.4-develop instance:

1) Two stores views:
![image](https://user-images.githubusercontent.com/2599558/127321585-8869112e-645c-461c-a542-1fc87d917cea.png)

2) 2 pages with the same identifier, each page for one store view:
![image](https://user-images.githubusercontent.com/2599558/127321689-a17e2c34-8abb-4df3-bb2f-ba68fb944ab1.png)

3) Set each page as homepage in the configuration:
![image](https://user-images.githubusercontent.com/2599558/127321877-440cd2b4-1a27-4af2-99cf-1114fb4ca090.png)
![image](https://user-images.githubusercontent.com/2599558/127321913-96453389-a411-4313-ba6d-f672aba31312.png)

4) Urlresolver request via graphQl:
Correct response for default store (default):
![image](https://user-images.githubusercontent.com/2599558/127322099-c3050646-4b5e-4669-a5d4-d51f96450346.png)

Null response for second store (default_2):
![image](https://user-images.githubusercontent.com/2599558/127322165-fbe1746a-950c-4b40-b81d-4b0d92472bb2.png)

**Comment by capkafitz** [comment] 2021-07-28 12:46
Fixed issue in our project with following patch:

```diff
--- ../Model/Resolver/UrlRewrite/HomePageUrlLocator.php	2020-07-20 13:13:08.000000000 +0200
+++ ../Model/Resolver/UrlRewrite/HomePageUrlLocator.php	2021-07-28 14:00:37.830555850 +0200
@@ -40,6 +40,10 @@
                 Page::XML_PATH_HOME_PAGE,
                 ScopeInterface::SCOPE_STORE
             );
+            $homePageDelimiterPosition = strrpos($homePageUrl, '|');
+            if ($homePageDelimiterPosition) {
+                $homePageUrl = substr($homePageUrl, 0, $homePageDelimiterPosition);
+            }
             return $homePageUrl;
         }
         return null;
```

**Comment by engcom-November** [comment] 2021-08-02 13:00
Verified the issue on Magento2.4-develop branch and the issue is reproducible:
**Steps to reproduce:**
1. Magento - 2 Store views [(Ref Guide)](https://devdocs.magento.com/guides/v2.4/config-guide/multi-site/ms_websites.html)
2. Create CMS page for default store (Admin - Content - Pages - Add New Page - Pages in Websites -  Select Default Store View) and Save
3. Create CMS page for new Store using same above url-key (Admin - Content - Pages - Add New Page - Pages in Websites -  Select your new Store View) and Save.
4. Clear Cache
5. Go to Configuration > General > Web (Change Scope of the website to "Default Store View")  > Default Pages > CMS Home Page -> Select newly created page for default Store and Save
6. Go to Configuration > General > Web (Change Scope of the website to "New Store view")  > Default Pages > CMS Home Page -> Select newly created page for new Store and Save
7. Execute graphQl query urlresolver for default store: - No issue
8. Execute graphQL query Urlresolver for new store - Issue
**Issue:** Correct response for default store (default) but getting Null response for second store
![image](https://user-images.githubusercontent.com/60198231/127865319-e1acd3f0-d4ca-4f13-aaf8-388d8ed6cc44.png)
![image](https://user-images.githubusercontent.com/60198231/127865350-1a73685a-ae8d-4ee0-9b74-467ee9bf3a2c.png)

**Default Store:**
![image](https://user-images.githubusercontent.com/60198231/127865392-f1896d26-4fa4-4f6e-a2b0-c7f9631373a9.png)
![image](https://user-images.githubusercontent.com/60198231/127865420-2fc385ab-9a6d-4d1f-b3f1-f5b13c2657f9.png)

**Note: This issue is also reproducible for default Store with below Steps:**
1. When CMS page is created 1st for new store and set the same url-key for Default Store CMS page
2. Go to Configuration > General > Web (Change Scope of the website to "New Store view")  > Default Pages > CMS Home Page -> Select newly created page for new Store and Save
3. Go to Configuration > General > Web (Change Scope of the website to "Default Store view")  > Default Pages > CMS Home Page -> Select newly created page for default Store and Save
7. Execute graphQl query urlresolver for france(new Store) store: - No issue
8. Execute graphQL query Urlresolver for default store - Issue
**Issue**: Null response for default store. Correct response for new store
![image](https://user-images.githubusercontent.com/60198231/127865951-5820b58b-bacf-4ec9-aa1f-8f6f676725a5.png)

![image](https://user-images.githubusercontent.com/60198231/127865968-28054f34-d64a-4f6a-9c3d-2d8f0a9eb8e2.png)

**Comment by magento-engcom-team** [comment] 2021-08-02 13:01
:white_check_mark: Confirmed by @engcom-November 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42964` were created

**Issue Available**: @engcom-November, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sergiy-v** [comment] 2021-08-18 13:51
@magento I am working on this

**Comment by engcom-Alfa** [comment] 2022-04-06 08:07
Hi @capkafitz ,
Thanks for your reported bug, the internal team has fixed and delivered this issue successfully.
Please find related commits [HERE](https://github.com/magento/magento2/commit/5c97ea79ab68dbb1ff0a7182f82abaa79374722d).

Kindly upgrade to the latest 2.4-develop to retest the case.
In case of any Magento related issues, you may please report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings possibly.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).

Thanks!

**Closed as completed by engcom-Alfa** 2022-04-06 08:07 UTC
Labels: Issue: Confirmed, Component: GraphQL, Reproduced on 2.4.x, Priority: P1, Severity: S1, Progress: done, Reported on 2.4.0, Area: APIs
