### ISSUE TITLE
[TEST] Test Issue 2 DO NOT PROCESS 

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2#27407] opened 2020-03-23 21:13 UTC
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by magento-engcom-team** [comment] 2020-03-25 13:36
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32776` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2020-03-25 13:44
Hi @sdzhepa. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-32776` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by magento-engcom-team** [comment] 2020-03-25 14:32
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32781` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Closed as completed** 2020-03-25 14:34 UTC
Labels: Issue: Ready for Work, Issue: Format is valid, Component: Admin, Reproduced on 2.4.x
