### ISSUE TITLE
 REST products update category_ids cannot be removed (from #20481)

### ISSUE THREAD

**Issue by siliconalchemy** [magento/magento2#25646] opened 2019-11-18 22:44 UTC
** Note: This is a continuation of #20481, which in turn is a continuation of #14038.  Both of these issues were closed without a correct fix in place **

Preconditions and Steps to Reproduce

For example, if a product currently has custom_attribute { 'category_ids': '['10127', '10048', '10123', '10126'] }, and I want to remove two of the categories from the product by setting this to { 'category_ids': '['10127', '10048'] }.

I then update the product with /rest/all/V1/products/ with the updated data. I get a success returned, and any other product data is successfully updated, and categories can be added to, but trying to remove categories such as above fail silently. The category_ids remain with the original 4 categories, as in the example above.

Magento 2.2.3
Php 7.1, Mysql 5.7 (Percona Xtradb Cluster)
Expected Result

I expect to be able to remove categories. This worked until 2.2 upgrade.
Actual result

See description. Categories are not updated, but the update command reports success.

**Comment by siliconalchemy** [comment] 2019-11-18 22:46
My workaround is to edit vendor/magento/module-catalog/Model/Category/Link/SaveHandler.php and change:
 $processLinks = $this->mergeCategoryLinks($dtoCategoryLinks, $modelCategoryLinks);
to
 $processLinks = $modelCategoryLinks;

Deleting categories then works perfectly for me, but I don't know what other impacts that could have.

**Comment by engcom-Charlie** [comment] 2019-11-20 09:41
Hello @siliconalchemy 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the latest 2.3-develop branch by provided steps.

**Testing scenario:**

1. Get the product which assigned to a lot of categories:
![image](https://user-images.githubusercontent.com/51680850/69227173-1988a780-0b8a-11ea-8107-da48df2cd7e9.png)

2. Update the product(make a PUT request without two categories):
![image](https://user-images.githubusercontent.com/51680850/69227198-23120f80-0b8a-11ea-9573-57582fcc987e.png)

3. Get the product again

**Result:**
Categories have been deleted:
![image](https://user-images.githubusercontent.com/51680850/69227263-3e7d1a80-0b8a-11ea-85ee-8c82428b3bad.png)
![image](https://user-images.githubusercontent.com/51680850/69227354-5c4a7f80-0b8a-11ea-9541-e84901cd71de.png)

We are closing this issue due to branch `2.2-develop` was closed and
> Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.

 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-11-20 09:41 UTC
Labels: Issue: Format is valid

**Comment by siliconalchemy** [comment] 2019-11-20 09:45
Huh, yes I still have this issue in 2.3.3.

**Comment by engcom-Charlie** [comment] 2019-11-20 10:00
@siliconalchemy i can't confirm issue of it only for 2.3.3( because 2.3.3 codebase has been merged in 2.3-develop) you can see info about it here:
![image](https://user-images.githubusercontent.com/51680850/69228985-425e6c00-0b8d-11ea-8ce0-725c03fef100.png)

**Comment by gdvisser** [comment] 2021-08-02 14:12
As long as this is not fixed in Magento you can take this approach: https://stackoverflow.com/questions/68622618/magento-2-rest-api-cant-remove-category-ids/68623022#answer-68623022
