### ISSUE TITLE
API SOAP Orders sorting doesn't work

### ISSUE THREAD

**Issue by MaximKitsenko** [magento/magento2#6439] opened 2016-09-01 11:27 UTC
steps to reproduce: 
**Make API call with this body:**

```
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:def="http://hereshouldbeyourmagentostoreurl.com/soap/default?services=salesOrderRepositoryV1"><soap:Header/>
   <soap:Body>
      <def:salesOrderRepositoryV1GetListRequest>
         <searchCriteria>
            <filterGroups>
               <!--Zero or more repetitions:-->

            </filterGroups>
            <!--Optional:-->

            <!--Optional:-->

            <!--Optional:-->
            <sortOrders><item><field>createdAt</field><direction>DESC</direction></item></sortOrders><pageSize>100</pageSize><currentPage>1</currentPage>
         </searchCriteria>
      </def:salesOrderRepositoryV1GetListRequest>
   </soap:Body>
</soap:Envelope>
```

**Th answer is:**

```
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" >
   <env:Body>
      <env:Fault>
         <env:Code>
            <env:Value>env:Receiver</env:Value>
         </env:Code>
         <env:Reason>
            <env:Text xml:lang="en">Internal Error. Details are available in Magento log file. Report ID: webapi-57c80c791008f</env:Text>
         </env:Reason>

      </env:Fault>
   </env:Body>
</env:Envelope>
```

**The problem is in sorting since when i removed this field:**

```
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:def="http://hereshouldbeyourmagentostoreurl.com/soap/default?services=salesOrderRepositoryV1">
   <soap:Header/>
   <soap:Body>
      <def:salesOrderRepositoryV1GetListRequest>
         <searchCriteria>
            <filterGroups>
               <!--Zero or more repetitions:-->

            <item><filters><item><field>updated_At</field><value>2016-03-10 20:24:00</value><conditionType>gt</conditionType></item><item><field>updated_At</field><value>2016-09-10 20:24:00</value><conditionType>lt</conditionType></item></filters></item></filterGroups>
            <!--Optional:-->

            <!--Optional:-->

            <!--Optional:-->
            <pageSize>100</pageSize><currentPage>1</currentPage>
         </searchCriteria>
      </def:salesOrderRepositoryV1GetListRequest>
   </soap:Body>
</soap:Envelope>
```

**I received correct answer:**

```
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:ns1="http://hereshouldbeyourmagentostoreurl.com/soap/default?services=salesOrderRepositoryV1">
    <env:Body>
        <ns1:salesOrderRepositoryV1GetListResponse>
            <result>
                <items>
                    <item>
                        <baseCurrencyCode>USD</baseCurrencyCode>
                        <baseDiscountAmount>0</baseDiscountAmount>
                        <baseGrandTotal>16</baseGrandTotal>
...

```

**Comment by veloraven** [comment] 2016-09-01 15:29
@MaximKitsenko thank you  for the report.
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by MaximKitsenko** [comment] 2016-09-02 23:27
@veloraven This bug related to Magento 2.1.0

**Comment by SerhiyShkolyarenko** [comment] 2016-09-20 14:53
@MaximKitsenko I spotted that you wrote incorrect field name for sorting. Please,  try **created_at** instead of **createdAt**. It worked for me.

**Comment by SerhiyShkolyarenko** [comment] 2016-10-11 12:32
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Comment by MaximKitsenko** [comment] 2016-10-14 16:16
@SerhiyShkolyarenko @veloraven  Sorry for delay. I had vacation. The code i provided above is generated by Visual Studio, that means that your wsdl is incorrect, wsdl says generate 'createdat' instead of 'created_AT'. 
So, looks like you have incorrect WSDL -> that leads to incorrect models -> that leads to topic

![chrome_2016-10-14_17-47-08](https://cloud.githubusercontent.com/assets/4807486/19394666/e91ee32a-9242-11e6-96e2-51a7c399d2a0.png)

**Comment by SerhiyShkolyarenko** [comment] 2016-10-19 15:28
@MaximKitsenko that field is declared for get() and save() methods, but not for getList().
I checked response for _get_ request and it has declared createdAt field.

```
         <result>
            <baseCurrencyCode>USD</baseCurrencyCode>
            <baseDiscountAmount>0</baseDiscountAmount>
            <baseGrandTotal>35</baseGrandTotal>
            <baseDiscountTaxCompensationAmount>0</baseDiscountTaxCompensationAmount>
            <baseShippingAmount>5</baseShippingAmount>
            <baseShippingDiscountAmount>0</baseShippingDiscountAmount>
            <baseShippingInclTax>5</baseShippingInclTax>
            <baseShippingTaxAmount>0</baseShippingTaxAmount>
            <baseSubtotal>30</baseSubtotal>
            <baseSubtotalInclTax>30</baseSubtotalInclTax>
            <baseTaxAmount>0</baseTaxAmount>
            <baseTotalDue>35</baseTotalDue>
            <baseToGlobalRate>1</baseToGlobalRate>
            <baseToOrderRate>1</baseToOrderRate>
            <billingAddressId>2</billingAddressId>
            <createdAt>2016-10-19 15:22:05</createdAt>
....
```

**Comment by SerhiyShkolyarenko** [comment] 2016-11-07 12:56
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by SerhiyShkolyarenko** 2016-11-07 12:56 UTC
Labels: bug report, Progress: needs update, Component: Framework/Webapi
