### ISSUE TITLE
2.4.5-p1

### ISSUE THREAD

**Issue by broeder** [magento/magento2#36826] opened 2023-02-09 08:17 UTC
### Preconditions and environment

- Magento version 2.4.5-p1
- Create Coupon: Back-end/Marketing/Cart Price Rules.
- Set: 
Coupon: specific coupon
Coupon code: TEST123 (or anything else)
Uses per Coupon : 0 (no limit)
Uses per Customer : 1 (this should limit uses to only 1 per customer)
Action: Percent of product price discount
Discount amount: 10
Active: yes
Choose dates to today or longer
Hit: SAVE button

### Steps to reproduce

Navigate to storefront.
Log in.
Add products to basket
Display basket
Apply Coupon. Type "TEST123".
Order.
--
Reproduce all steps once.
--
Reproduce all steps as many times as you want.

### Expected result

Order is placed with a 10% discount.
Works only once.

### Actual result

Order is placed with a 10% discount,, no matter how many times same customer uses same coupon.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-02-09 11:47
Hi @broeder,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


Created a cart price rule.



![Error-Promotions-Marketing-Magento-Admin (1)](https://user-images.githubusercontent.com/51680745/217803495-ce8dd412-6a30-43a9-bbd2-569b50ffeed9.png)


Coupon used as logged customer we are able to apply the coupon first time.

<img width="1443" alt="Screenshot 2023-02-09 at 4 16 27 PM" src="https://user-images.githubusercontent.com/51680745/217803627-e3b1b6b2-1ae2-41db-a19c-cbe9ec74a7cb.png">


We are not able to apply the coupon for the second time.




<img width="1433" alt="Screenshot 2023-02-09 at 4 18 10 PM" src="https://user-images.githubusercontent.com/51680745/217803680-d85494e0-2adf-4685-81e8-08d151bf29d7.png">


Please Make sure that,After creating an Cart Price Rules for coupon usage we need to start Consumers to update Coupon usage.

Please try to run below commands to update coupon usage.

`
bin/magento queue:consumers:start sales.rule.update.coupon.usage`


Kindly let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-02-21 06:03
Hi @broeder,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-02-21 06:03 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1
