### ISSUE TITLE
the error page processor does not work when the webroot is set to `www/pub` instead of `www`

### ISSUE THREAD

**Issue by heldchen** [magento/magento2#6403] opened 2016-08-30 17:27 UTC
### Preconditions
1.  CE 2.1.0 in production or default mode
2. webroot pointing to `www/pub`
### Steps to reproduce
1. copy `www/pub/errors/default` to `www/pub/errors/test` 
2. edit `www/pub/errors/design.xml` and replace `default` with `test`
3. edit text in `www/pub/errors/test/503.phtml` to read "hello world"
4. enable maintenance mode
5. browse website
### Expected result
1. the resulting 503 page should say "hello world"
### Actual result
1. the resulting 503 page says the default "Service Temporarily Unavailable"

`www/pub/errors/processor.php` checks the wrong path in the `_setSkin` function. instead of checking `.../www/pub/errors/test` the path `.../www/pub/pub/errors/test` is checked, and this check obviously fails due to the doubled `pub`. _setSkin should use `$this->root` and change the path accordingly, just like `getBaseUrl()` in the same class already does. unfortunately, _setSkin is not the only function broken - _setReportUrl will also use an extra `/pub/` in the url

**Comment by heldchen** [comment] 2016-08-30 22:17
also applies to 2.1.1

**Comment by johnhughes1984** [comment] 2016-10-30 20:54
Still happening in CE 2.1.2, any ETA on this being fixed?

**Comment by alexpoletaev** [comment] 2016-12-28 13:34
I can confirm, that we have the same issue on CE 2.1.2 (and still not fixed in 2.1.3). Please fix this issue asap. Thanks.

**Comment by sshymko** [comment] 2016-12-29 17:44
Suffering from the issue on 2.1.3. Deployment with `/pub` as a document root is the recommended configuration. Can the issue be prioritized higher?

**Comment by danny-balance** [comment] 2017-02-20 06:30
This is a duplicate of #4305 in which a fix was pushed to `develop` 9 months ago. When can we expect this to be released?

**Comment by bh-ref** [comment] 2017-02-20 15:42
issue is still present in 2.1.4

**Comment by Rane2k** [comment] 2017-02-24 12:06
Issue is still present in 2.1.5.

**Comment by KrystynaKabannyk** [comment] 2017-03-24 17:01
@heldchen, thank you for reporting the issue, but we couldn't reproduce it. Could you please provide more details?

**Comment by heldchen** [comment] 2017-03-24 17:05
@KrystynaKabannyk sorry, I really don't know what more details I could provide that are not already mentioned in the issue:

0. configure magento2 to use www/pub as webroot
1. copy www/pub/errors/default to www/pub/errors/test
2. edit www/pub/errors/design.xml and replace default with test
3. edit text in www/pub/errors/test/503.phtml to read "hello world"
4. enable maintenance mode
5. browse website

**Comment by veloraven** [comment] 2017-06-21 08:31
Internal ticket was created - MAGETWO-69938
I'm closing this issue as #8026 has more detailed description.

**Closed as completed by veloraven** 2017-06-21 08:31 UTC
Labels: Issue: Ready for Work, bug report, Component: Cms, Component: Config
