### ISSUE TITLE
Some product options missing in Product response

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#36474] opened 2022-11-14 12:17 UTC
### Preconditions and environment

Magento 2.4.3-p2

### Steps to reproduce

There is a configurable product having options which is linked to the order.
1.Retrieve the order response by using below API
~/rest/V1/orders/28125
Method: GET

Response - 
[#1000030755_28125.txt](https://github.com/magento/magento2/files/10002795/1000030755_28125.txt)

2. Download the Product by using below API
~/rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=entity_id&searchCriteria[filter_groups][0][filters][0][value]=745,746&searchCriteria[filter_groups][0][filters][0][condition_type]=in
Method: GET

Response - 
[1000030755_product options.txt](https://github.com/magento/magento2/files/10002798/1000030755_product.options.txt)

### Expected result

We should be getting all the options(Option1 ,Option2 and Option 3) as is seen in screenshot.
Via Product API we are getting values for Option 1 and Option 2 only.
![image](https://user-images.githubusercontent.com/54638813/202368255-4a8ef50e-cd06-4e43-aa93-18947ae9c199.png)

### Actual result

We are getting only option 1 and option 2.We are not getting option 3.
Via Product API we are getting not getting values for Option 3.
![image](https://user-images.githubusercontent.com/54638813/202368318-3d6ec379-a664-4130-9e20-33de41cfc4c2.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-11-15 08:54
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-15 12:02
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-15 12:46
Hi @webgility-amazonapi,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

We are getting Product Options via Product APi.


<img width="1039" alt="Screenshot 2022-11-15 at 5 24 32 PM" src="https://user-images.githubusercontent.com/51680745/201922574-865449fc-a060-470a-9f11-b00aad7084ed.png">


<img width="479" alt="Screenshot 2022-11-15 at 6 07 21 PM" src="https://user-images.githubusercontent.com/51680745/201922707-e951bdc8-6e7f-4c17-ac34-6369a66d0d00.png">



<img width="548" alt="Screenshot 2022-11-15 at 6 07 28 PM" src="https://user-images.githubusercontent.com/51680745/201922855-b0b210e1-2baa-4bb2-bb27-9af70441302e.png">




<img width="541" alt="Screenshot 2022-11-15 at 6 07 33 PM" src="https://user-images.githubusercontent.com/51680745/201922869-528779a0-cbc2-46ec-bc08-7bba62d82e6d.png">



Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by webgility-amazonapi** [comment] 2022-11-15 15:48
Please try to create a product of type configurable and add Customizable Option over there.The order response should be like as mentioned in the screenshot.
Attach this product to order and configure the product.
Submit an order.
Now download the order you will see items[]-> product_option->extension_attributes-> configurable_item_options node .
The value coming inside the configurable_item_options node are not present in the product API. 
How to map options value coming under configurable_item_options node ?(Option 3)
Please have a look in the response 
Order Response 
[#1000030755_28125.txt](https://github.com/magento/magento2/files/10014098/1000030755_28125.txt)
Product Response
[1000030755_product options.txt](https://github.com/magento/magento2/files/10014101/1000030755_product.options.txt)


![image](https://user-images.githubusercontent.com/54638813/201960524-7c6af4ad-2f62-4e13-8313-e755301edf42.png)
![image](https://user-images.githubusercontent.com/54638813/201960977-59d903f5-c560-455c-8d80-78b069caf853.png)
![image](https://user-images.githubusercontent.com/54638813/201961546-d3ed6b70-7669-4b8e-b54d-c03d51b90244.png)
![image](https://user-images.githubusercontent.com/54638813/201962793-55b42e29-d335-4e70-96f1-83a071d70dcf.png)

**Comment by engcom-Bravo** [comment] 2022-11-16 09:24
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-16 10:41
Hi @webgility-amazonapi,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

We are getting configurable_item_options in Product Response.


<img width="776" alt="Screenshot 2022-11-16 at 3 35 30 PM" src="https://user-images.githubusercontent.com/51680745/202158430-9ef4490c-38ec-4577-b98d-0f0e77383ec6.png">



<img width="758" alt="Screenshot 2022-11-16 at 3 35 46 PM" src="https://user-images.githubusercontent.com/51680745/202158505-f487edb5-f698-41a6-9471-7ca211bff7a0.png">



<img width="310" alt="Screenshot 2022-11-16 at 3 32 02 PM" src="https://user-images.githubusercontent.com/51680745/202158612-07fa1a75-69bd-4220-9d60-23bab83b5604.png">



Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by webgility-amazonapi** [comment] 2022-11-17 05:05
Hi Hi @engcom-Bravo,
Can you please also attach the screenshot for order ->orderItems->product_options ? I need to see the values in product_option->extension_attributes-> configurable_item_options ? just like 
![image](https://user-images.githubusercontent.com/54638813/202360708-b2db81a7-8aec-4238-ab11-14ccff8ad323.png)

**Comment by engcom-Bravo** [comment] 2022-11-17 08:59
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-17 10:49
Hi @webgility-amazonapi,

Thanks for your Update.


Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


We are getting "configurable_product_options"


<img width="561" alt="Screenshot 2022-11-17 at 4 13 39 PM" src="https://user-images.githubusercontent.com/51680745/202426682-4aefedc0-6a6b-483f-8a07-efd820cc18e2.png">



<img width="546" alt="Screenshot 2022-11-17 at 4 13 47 PM" src="https://user-images.githubusercontent.com/51680745/202426751-e68c2054-8af1-4551-9ad9-7205f5ab5266.png">




Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by webgility-amazonapi** [comment] 2022-11-17 12:16
Hi @webgility-amazonapi,
Does it mean that custom_options[] coming in Order API needs to map with options[] coming in Product API ?
Does it mean that configurable_item_options[] coming in Order API needs to map with configurable_product_options [] coming in Product API ?

Also Within configurable_product_options For AttributeId = 93 which is having label = Color , the value is Blue but here we can see only value_index = 5 . Where can we find this Blue value
![image](https://user-images.githubusercontent.com/54638813/202443518-3cc082a3-e2ef-4689-8bd8-dfd1bf2b7772.png)
![image](https://user-images.githubusercontent.com/54638813/202443853-8ceae748-83ed-4305-a7bb-9923f5a831a1.png)

**Comment by engcom-Bravo** [comment] 2022-11-18 07:24
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-11-18 07:51
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-18 12:00
Hi @webgility-amazonapi,

Thanks for your Update.

Kindly refer the screenshot for Child Product Color Blue for Configurable Product.


<img width="696" alt="Screenshot 2022-11-18 at 2 22 38 PM" src="https://user-images.githubusercontent.com/51680745/202700472-96a5d428-e0dd-4827-92e5-50c280434392.png">



<img width="497" alt="Screenshot 2022-11-18 at 5 28 28 PM" src="https://user-images.githubusercontent.com/51680745/202700494-8ac3e38f-8ea2-4adb-b371-42093e9f47a0.png">




Thanks.

**Comment by webgility-amazonapi** [comment] 2022-11-18 12:27
Hi @engcom-Bravo ,
Can you please elaborate. I did not get how the value mentioned in the screenshot mentioned by you in the above comment matches with  "Color : Blue" .
How I will be able to map  "Color" to "Blue" .Is there some sort of Id  which I can use to map "Color" with "Blue" ?
![image](https://user-images.githubusercontent.com/54638813/202704141-743ed54d-3cf7-4bca-9d79-d7c51ac5bb87.png)

**Comment by engcom-Bravo** [comment] 2022-11-21 11:46
Hi @webgility-amazonapi,

Since Color is an Custom Attribute hence we are getting Configurable Child Product details in Custom Attributes Node.

Kindly refer the screenshots.

<img width="579" alt="Screenshot 2022-11-21 at 5 14 25 PM" src="https://user-images.githubusercontent.com/51680745/203043353-60952ab3-c8f7-417e-9490-ece2ffef4f8d.png">



<img width="569" alt="Screenshot 2022-11-21 at 3 06 34 PM" src="https://user-images.githubusercontent.com/51680745/203042943-f3f773fb-9f96-4ae8-9e58-69dc548f35b5.png">



<img width="620" alt="Screenshot 2022-11-21 at 3 06 27 PM" src="https://user-images.githubusercontent.com/51680745/203042980-210c4aee-f07f-43f2-b618-ed344adf98fa.png">



<img width="501" alt="Screenshot 2022-11-21 at 3 06 18 PM" src="https://user-images.githubusercontent.com/51680745/203043009-bb9a6fb8-3f96-48e2-b99a-d5058cbf09a6.png">



Thanks.

**Comment by engcom-Bravo** [comment] 2022-12-06 06:13
Hi @webgility-amazonapi,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-12-06 06:13 UTC
Labels: Issue: needs update, Reported on 2.4.3-p2
