### ISSUE TITLE
Disable products are still shown on website

### ISSUE THREAD

**Issue by rowanvandorp** [magento/magento2#10946] opened 2017-09-18 10:48 UTC
### Preconditions

1. I use Chrome as browser
2. I use Magento version 2.1.7

### Steps to reproduce

1. On my dashboard, I go to Product - Catalog
2. I click on a random product (configurable product consisting of simple products)
3. The simple products are different clothing sizes, so when a size is not available anymore, we disable that product
4. When I click on 'disable' of a product, the product is still shown on our website
5. Also when I click on 'able' on a product that WAS disable, the product is NOT shown on our website

### Expected result

1. Normaly, if you disable a product, the product will be removed from your website

### Actual result

1. Unfortunately, when i disable a product, it's still shown on our website.
![knipsel](https://user-images.githubusercontent.com/32061263/30538748-ac2c4b3c-9c6f-11e7-90de-acb1a01b681c.PNG) 
![1 1](https://user-images.githubusercontent.com/32061263/30538749-aeea24e8-9c6f-11e7-898c-c3ed3abb5864.PNG)

**Comment by magento-engcom-team** [comment] 2017-09-19 07:35
We are closing this issue because we cannot reproduce this issue as described. If your have questions, please refer to a question and answer site, such as Stack Exchange and the Magento Forums, where Magento community members can quickly provide recommendations and advice.

**Closed as completed by magento-engcom-team** 2017-09-19 07:35 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid
