### ISSUE TITLE
bin/magento dev:email :override-compatibility-check  not picking up issues

### ISSUE THREAD

**Issue by will-wright1** [magento/magento2#35415] opened 2022-05-04 07:56 UTC
### Preconditions (*)
Provide the exact Magento version (example: 2.4.0) and any important information on the environment where bug is reproducible.
1. Magento 2.4.4 open source
2. Php7.4

### Steps to reproduce (*)
Important: Provide a set of clear steps to reproduce this bug. We can not provide support without clear instructions on how to reproduce.
1. Upgraded 2.4.3 to 2.4.4 open source version. (project-community-edition)
2. Upgraded PHP version from 7.4 to 8.1 as per [System requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html)
3. Admin - Marketing - Email Templates - Created new Order template with content: {{var order.getPayment().getMethodInstance().getTitle()}}
4. Applied Newly created Template for Orders (Stores - Configuration - Sales - Sales Emails - Order)
5. Create an Order for logged in customer - Email triggered.
7. Run bin/magento dev : email:override-compatibility-check or bin/magento dev : email:newsletter-compatibility-check check doesn't pick up on it. 

### Expected result (*)
1. Email triggered should have content

### Actual result (*)

1. bin/magento dev:email :override-compatibility-check  should no warning is shown.
2. When the email is sent by the system you'll be stuck with empty values here or broken templates or email doesn't send at all (depending on the variable)
8. Nothing in the usual log files either

**Comment by webamondo** [comment] 2022-05-09 07:27
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-05-10 10:07
Hi @webamondo ,
Thank you for reporting and collaboration. Verified the issue by upgrading from 2.4.3 to 2.4.4 but could not able to reproduce the issue.
Steps performed:
1. Upgraded 2.4.3 to 2.4.4 open source version. (project-community-edition)
2. Upgraded PHP version from 7.4 to 8.1 as per [System requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html)
3. Admin - Marketing - Email Templates - Created new Order template with content: {{var order.getPayment().getMethodInstance().getTitle()}} 
4. Applied Newly created Template for Orders (Stores - Configuration - Sales - Sales Emails - Order)
5. Create an Order for logged in customer - Email triggered.
6. Run "bin/magento dev : email:override-compatibility-check or bin/magento dev : email:newsletter-compatibility-check" from terminal. No issue. No warnings/errors are shown.

![image](https://user-images.githubusercontent.com/60198231/167604529-bd0b01be-a8a0-4b1f-8f75-70a8c21bbb14.png)
Kindly recheck the issue again as per Magento system requirements and check if any third party extensions/modules is causing this issue. Please elaborate steps to reproduce if the issue is still reproducible.
Thank you.

**Comment by webamondo** [comment] 2022-05-10 11:18
Hello

That's correct, but was the content {{var order.getPayment().getMethodInstance().getTitle()}} in the email when it was sent?

For me it's blank, should this not be flagged on the compatibility checker as an incorrect tag?

**Comment by engcom-November** [comment] 2022-05-16 08:39
Hi @webamondo ,
Thanks for the update. Email triggered is blank and has no content. Hence updating the issue description and confirming this issue.
![image](https://user-images.githubusercontent.com/60198231/168553205-55886551-3f5c-4a12-95bd-dbe7665ada29.png)

**Comment by engcom-November** [comment] 2022-08-19 09:28
Hi @webamondo ,
After internal discussions, it is concluded that this is a default behavior of Magento and community cannot provide fix for this issue. Please check the reference [comment](https://github.com/magento/magento2/issues/35343#issuecomment-1113672173) for explanation of the same.
Thank you.

**Closed as completed by engcom-November** 2022-08-19 09:28 UTC
Labels: Issue: Confirmed, Component: Email, Reproduced on 2.4.x, Priority: P3, Progress: done, Area: Order, Reported on 2.4.4

**Comment by cmtickle** [comment] 2024-02-27 23:42
> Hi @webamondo , Thanks for the update. Email triggered is blank and has no content. Hence updating the issue description and confirming this issue. ![image](https://user-images.githubusercontent.com/60198231/168553205-55886551-3f5c-4a12-95bd-dbe7665ada29.png)

There's a change in PHP 8.1+ which can cause a blank email body. Adding the following to php.ini should resolve the issue.
```sh
mail.mixed_lf_and_crlf = On
```
