### ISSUE TITLE
[GraphQL] products query is very slow if retrieving price of several configurable products

### ISSUE THREAD

**Issue by t-heuser** [magento/magento2#36144] opened 2022-09-15 13:18 UTC
### Preconditions and environment

- Magento version: 2.4.5
- A category with 36 or more configurable products which all have at least 200 variants

### Steps to reproduce

Execute the following query:
```GRAPHQL
query products {
  products(filter: {category_id: {eq: "YOUR_CATEGORY_ID"}} pageSize: 36) {
    items {
      price_range {
        minimum_price {
          final_price {
            currency
            value
          }
        }
      }
    }
  }
}
```

Here I'm trying to reveice 36 products of a category. 36 is a standard magento listing size for categories. This query is very slow and takes **more than a minute** if all/a lot of the products inside the category are rather huge configurable products (more than 200 variants).

### Expected result

The query is not taking more than a minute to resolve.

### Actual result

The query is taking more than a minute to resolve.

### Additional information

The problem only occurs if you try to get anything inside `price_range`. If you don't request this field the query is fast again. The problem can be found here:
https://github.com/magento/magento2/blob/91549b925da128ba79807400f551f2b2d0cfeed9/app/code/Magento/ConfigurableProductGraphQl/Model/Resolver/Product/Price/Provider.php#L100-L113

Magento iterates through all child products and tries to get the minimum price. This is very slow if done for a lot of configurable products with several child products (same problem applies to [getMaximalPrice()](https://github.com/magento/magento2/blob/91549b925da128ba79807400f551f2b2d0cfeed9/app/code/Magento/ConfigurableProductGraphQl/Model/Resolver/Product/Price/Provider.php#L123) .

It would be smart here to use the price from the price index as in the table `catalog_product_index_price` all the data needed is already stored. Magento does this for it's traditional storefront and uses the indexed data there, in GraphQl unfortunately not which leads to the slowness of requests.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by oneserv-heuser** [comment] 2022-09-15 13:19
What I did as quick workaround: Created an around plugin that gets the data from the index if present and otherwise executes the slow function. Here is a patch file which includes the fix as a module:
[fix(graphql)__products_query_is_slow_with_configurable_products.txt](https://github.com/magento/magento2/files/9575558/fix.graphql.__products_query_is_slow_with_configurable_products.txt)

**Comment by engcom-Bravo** [comment] 2022-09-21 12:38
Hi @oneserv-heuser,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop branch and 2.4.5 but the issue is not reproducible.We are able to retrieve the price of configurable products within less than a minute.


1.Created 36 configurable products with 200+ variants.

<img width="1157" alt="Screenshot 2022-09-21 at 5 33 30 PM" src="https://user-images.githubusercontent.com/51680745/191499183-ac8e0753-cdeb-427f-be0e-c9cdec8f6561.png">



<img width="1195" alt="Screenshot 2022-09-21 at 5 35 18 PM" src="https://user-images.githubusercontent.com/51680745/191499676-6bd0e8c3-e115-4c68-bea0-726a84e6b0ba.png">



Please let us know we miss anything.


Thanks.

**Comment by oneserv-heuser** [comment] 2022-09-22 11:11
https://github.com/magento give me 2.4-develop instance

**Comment by oneserv-heuser** [comment] 2022-09-22 11:16
@magento give me 2.4-develop instance

**Comment by oneserv-heuser** [comment] 2022-09-22 11:40
@engcom-Bravo 
Sorry, it looks like I need to specify my numbers a little bit more. Please try the same with bigger configs. For example our biggest configurable product has around 1.200 single products. So I guess our biggest category has around 15.000 single products behind it's configurable products in the first 36 products.

Could you please try to reproduct the issue with even bigger configs, thank you.

**Comment by engcom-Bravo** [comment] 2022-09-23 06:40
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-09-23 12:19
Hi @oneserv-heuser,

Thanks for quick update.


Verified the issue on Magento 2.4-develop branch and 2.4.5 but the issue is not reproducible.We are able to retrieve the price of configurable products within less than a minute.


Created a 36 Configurable Product with 10,000+ Variants and assigned it to category.

<img width="1105" alt="Screenshot 2022-09-23 at 4 20 07 PM" src="https://user-images.githubusercontent.com/51680745/191953759-9b34d419-ce8d-4b87-8f65-a94f10b97508.png">



<img width="1152" alt="Screenshot 2022-09-23 at 4 22 06 PM" src="https://user-images.githubusercontent.com/51680745/191953801-d305ca5a-0906-41e3-9308-7ab60b5288b7.png">




<img width="1172" alt="Screenshot 2022-09-23 at 4 19 54 PM" src="https://user-images.githubusercontent.com/51680745/191953847-b06a5e99-e99d-450a-9093-5ad4a4b0e0db.png">



Please let us know we miss anything.


Thanks.

**Comment by engcom-Bravo** [comment] 2022-10-07 06:18
Hi @oneserv-heuser,


We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-10-07 06:18 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.5
