### ISSUE TITLE
Component Manager Not loading

### ISSUE THREAD

**Issue by terrybakshi** [magento/magento2#8302] opened 2017-01-27 10:28 UTC
### Preconditions

1. CENTOS 7.3
2. Magento 2.1.3

### Steps to reproduce

1. I tried to refresh the page, delete cache, tried 
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy
php bin/magento cache:clean

But nothing seems to work, its keeps on waiting.

![screenshot 15](https://cloud.githubusercontent.com/assets/13229022/22367786/75bd00be-e4d7-11e6-82fc-d5c481f4613c.png)

### Actual result

1. [Screenshot, logs]

**Comment by zajazdowicz** [comment] 2017-02-03 12:47
The same issue here, after module installation, component manager not loading, here's the screenshot from dev tools.
![screenshot_4](https://cloud.githubusercontent.com/assets/25529336/22591878/33fa173a-ea17-11e6-8249-a556562cb6a7.png)

**Comment by veloraven** [comment] 2017-02-03 12:55
Closed as a duplicate of #7958.

**Closed as completed by veloraven** 2017-02-03 12:55 UTC

**Comment by muhammadshakeel** [comment] 2017-07-10 14:00
I have fixed this issue by following below steps:

 - Open /setup/index.php/componentGrid/components in new tab
 - It showed me actual error, in my case it was last extension installed through composer.
 - I have removed that from composer
 - After updating composer, the error goes away.

https://magento.stackexchange.com/a/182945/56221
