### ISSUE TITLE
Price on product view page becomes 0,00 after page has finished loading

### ISSUE THREAD

**Issue by zlep** [magento/magento2#33798] opened 2021-08-14 07:01 UTC
### Preconditions (*)

1. Magento 2.4.3
2. PHP 7.4
3. Country Options is set to US
4. Locale Options (Local) is set to Germany
5. Base Currency: Euro
6. Default Display Currency: Euro
7. Allowed Currencies: Euro
8. 3 different StoreViews are set up

### Steps to reproduce (*)

1. Create new product (price doesn't matter)
2. Go to product list page (categorie view page)
3. Go to product details page (product view page)

### Expected result (*)

1. Actual price on product details page should be shown

### Actual result (*)

1. Price on product list page is shown correctly
2. But on product details page, the page loads, correct price is shown for a millisecond but when the page has finished loading, price is shown as "0,00 €"

It seems like there is some JS or anything like that going on, when the page has finished loading, the price is set "0,00 €"
**Important: This bug is only present in 2.4.3. I downgraded to 2.4.2 and there, everything works fine.**

I found an old, _some kind of related_ issue which was fixed: https://github.com/magento/magento2/issues/4077
My store is set to **Locale Options (Local) is set to Germany**. _But I did not test if this is actually causing the issue. I will test as soon as possible._

**Comment by zlep** [comment] 2021-08-14 08:09
Ok, did some further testing. This is actually an issue with **Local Options** set in _"Stores -> Configuration -> General -> Local Options -> Local -> German (Germany)"_.

If this option is set to "English (United States)", price on product page is shown correctly. If it is set to "German (Germany)" price becomes "0,00 €" as described as above.

**Comment by engcom-November** [comment] 2021-08-17 12:17
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible:
Steps performed:
3 Different Store Views are setup [(Ref link)](https://devdocs.magento.com/guides/v2.4/config-guide/multi-site/ms_websites.html)
Stores - Configuration - General -  Country Options is set to US
Locale Options (Local) is set to Germany
Stores - Configuration - Currency Setup - Base Currency: Euro, Default Display Currency: Euro , Allowed Currencies: Euro and Save the configuration
Reindex and clear cache
Create new product from Admin (Product is displayed in all store websites)
Front-end - Search Results page and Product Details page - No issue: Price is displayed as expected.
![image](https://user-images.githubusercontent.com/60198231/129723910-9cacb44e-b308-4b91-a2fc-472d801e2317.png)
![image](https://user-images.githubusercontent.com/60198231/129723931-d907cc92-2532-4ed7-a72f-53925d08036e.png)
![image](https://user-images.githubusercontent.com/60198231/129723948-9b89f289-d480-4d81-92b1-cc42fbfb9ba7.png)
@zlep , kindly recheck the issue on Magento 2.4-develop branch as the issues in 2.4.3 are also fixed in 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by zlep** [comment] 2021-08-17 15:31
@engcom-November 

I set up vanilla Magento 2 instance. Here are the exact steps to reproduce:

1.) `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition .`
2.) `magento setup:install --admin-firstname=Admin --admin-lastname=Admin --admin-email=MYMAIL --admin-user=admin --admin-password=MYPASSWORD --base-url=MYURL --db-host=localhost --db-name=MYDB --db-user=MYDBUSER --db-password=MYDBPASSWORD --base-url-secure=MYURL --use-secure=1 --use-secure-admin=1 --language=de_DE --currency=EUR --timezone=Europe/Berlin --elasticsearch-host=MYHOST --elasticsearch-port=9200`
3.) `magento module:disable Magento_TwoFactorAuth`
4.) `magento setup:upgrade`
5.) Login to backend
6.) Create Category "Testcategory"
7.) Create Product "Testproduct"
<img width="870" alt="Bildschirmfoto 2021-08-17 um 17 24 49" src="https://user-images.githubusercontent.com/10477541/129755621-8cbca311-dcbb-4fa2-a6b7-2d6121b355ac.png">
8.) `magento indexer:reindex`
9.) `magento c:f`
10.) Go to frontend
11.) Category page is good: 
<img width="702" alt="Bildschirmfoto 2021-08-17 um 17 27 28" src="https://user-images.githubusercontent.com/10477541/129755632-e553bb4e-3a6f-40fb-9bca-c1c1a5afec4c.png">
12.) Product page becomes 0,00 €
<img width="1275" alt="Bildschirmfoto 2021-08-17 um 17 29 02" src="https://user-images.githubusercontent.com/10477541/129755635-152f607d-c956-49c4-a73c-faf1202e3b25.png">

**Comment by zlep** [comment] 2021-08-17 15:46
Here's a video, showing the issue:

https://user-images.githubusercontent.com/10477541/129758144-577042e9-6d3c-432c-8d24-0022b85e2444.mov

**Comment by engcom-November** [comment] 2021-08-18 11:57
Hi @zlep 
Its recommended to verify the issues on Magento 2.4-develop branch only as the issues in 2.4.2-p1/ 2.4.3 are fixed in 2.4-develop branch. I'm not able to reproduce this issue on Magento 2.4-develop branch with provided steps. Kindly recheck the issue on 2.4-develop and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by zlep** [comment] 2021-08-18 13:42
@engcom-November 
I'd love to check on develop-branch and really hope the issue is fixed, because it would be a major bug for localization. Unfortunately I'm not sure how to install develop-branch. Can you help?

**Comment by engcom-November** [comment] 2021-08-19 07:56
Hi @zlep,
To deploy vanilla Magento instance, please add a comment to this issue: "@magento give me 2.4-develop instance" to reproduce the issue on 2.4-develop branch.
Please find the example screenshot for your reference.
![image](https://user-images.githubusercontent.com/60198231/130030189-0af2c02c-aff7-4b9e-b71d-db2e4d116022.png)
Thank you.

**Comment by zlep** [comment] 2021-08-19 11:33
@magento give me 2.4-develop instance

**Comment by zlep** [comment] 2021-08-19 11:51
@engcom-November Thanks, I cannot reproduce on this Magento 2.4-develop branch. So seems like it's fixed already? But when will this fix be available for the official release which we install via `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition .`

Because there it's definitly a bug!

**Comment by ihor-sviziev** [comment] 2021-08-20 09:15
Hi @zlep,
The 2.4.3 release was merged just recently to the 2.4-develop branch in https://github.com/magento/magento2/commit/ed5c06d68ec4bf77ad6c03e0af28a133b1193b66. Could you double-check the issue again?

**Comment by zlep** [comment] 2021-08-20 12:26
@ihor-sviziev 
When I install via `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition .` the issue is still there.

**Comment by engcom-November** [comment] 2021-08-23 06:53
> @engcom-November Thanks, I cannot reproduce on this Magento 2.4-develop branch. So seems like it's fixed already? But when will this fix be available for the official release which we install via `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition .`
> 
> Because there it's definitly a bug!

Hi @zlep , Thanks for your confirmation. We are closing this issue for now as this is not reproducible on 2.4-develop branch. @sdzhepa / @gabrieldagama kindly confirm when this fix will be available for the official release (composer version)
Thank you.

**Comment by groomershop-mt** [comment] 2021-08-24 12:41
We have the same issue - we can confirm it on our stage/production nodes, but on anouther dev node it doesn't happen (with the same PHP version, the same DB, the same Magento, etc. - one diffrence is e.g. in operating system Ubuntu/CentOS).

In result, after changing the currency by client on storefront, for configurable products the JS change prices to 0.00 €. Is issue occur on Magento 2.4.3 (after replacing Zend_Currency by commit https://github.com/magento/magento2/commit/ba2ae68a55c6e571a58c749e2a96f366d6a05745#diff-09a839078aa6453eb8fb437430724140207e2aa7214c3bb98bc7ced29fe39927).

**Comment by groomershop-mt** [comment] 2021-08-24 12:51
Me have published patch in:
https://github.com/magento/magento2/issues/33856

**Comment by onlinebizsoft** [comment] 2021-08-24 12:55
@engcom-November since it is valid issue on 2.4.3 and 2.4-develop after merging 2.4.3 so the ticket should be re-opened? This is a quite bad bug.

**Comment by zlep** [comment] 2021-08-24 13:48
@groomershop-mt Thanks, so where does this bug come from? And will it be fixed in the near future @engcom-November 
I'm planning to go live with my shop in the next days and I was hoping I could start with 2.4.3.

**Comment by softinfoline** [comment] 2021-08-24 14:07
Yes thats bug and price show zero when using other locale. Thats affect product view & checkout page. Issue related to Currency.php file. I have already fixed this issue.

**Comment by ihor-sviziev** [comment] 2021-08-24 15:58
This issue should be rechecked

**Comment by engcom-November** [comment] 2021-08-25 12:37
Verified this issue again on Magento 2.4-develop and 2.4.3 version as well but unable to reproduce the issue on all Stores on both the versions:
**Steps performed:**
Default Country Options is set to US, Locale - Germany
Created Configurable Product from Admin (Available on all Store Views)
Currency setup to EURO for all Store views
reindex and clear cache
Viewed the Product on frontend - All Store Views - Product Details page is loading as expected with correct Price value.
Please provide missing steps / configuration details to reproduce the issue.
Thank you.

**Comment by engcom-Lima** [comment] 2021-08-30 13:46
Hi @zlep, @ihor-sviziev,

I'll be rechecking this issue and will try to reproduce again.

Thanks

**Comment by ihor-sviziev** [comment] 2021-08-31 05:49
Anyone who has this issue - could you run composer check-platform-reqs and php -i | grep ICU on your environment?

**Comment by groomershop-mt** [comment] 2021-08-31 06:53
We have:
```
root@d03897680f31:/app/m# composer check-platform-reqs                      
Checking platform requirements for packages in the vendor dir
composer-plugin-api   2.0.0       success  
composer-runtime-api  2.0.0       success  
ext-bcmath            7.4.22      success  
ext-ctype             7.4.22      success  
ext-curl              7.4.22      success  
ext-dom               20031129    success  
ext-fileinfo          7.4.22      success  
ext-filter            7.4.22      success  
ext-gd                7.4.22      success  
ext-hash              7.4.22      success  
ext-iconv             7.4.22      success  
ext-intl              7.4.22      success  
ext-json              7.4.22      success  
ext-libxml            7.4.22      success  
ext-mbstring          7.4.22      success  
ext-openssl           7.4.22      success  
ext-pcre              7.4.22      success  
ext-pdo_mysql         7.4.22      success  
ext-phar              7.4.22      success  
ext-simplexml         7.4.22      success  
ext-soap              7.4.22      success  
ext-sockets           7.4.22      success  
ext-sodium            2.0.23      success  
ext-tokenizer         7.4.22      success  
ext-xml               7.4.22      success  
ext-xmlwriter         7.4.22      success  
ext-xsl               7.4.22      success  
ext-zip               1.15.6      success  
lib-libxml            2.9.10      success  
lib-openssl           1.1.1.11    success  
php                   7.4.22      success  
root@d03897680f31:/app/m# php -i | grep ICU
ICU version => 67.1
ICU Data version => 67.1
ICU TZData version => 2019c
ICU Unicode version => 13.0
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by ihor-sviziev** [comment] 2021-08-31 08:15
Hi @engcom-November, please check https://github.com/magento/magento2/issues/33910#issuecomment-908956529, feels like there is some diff on different OS, or library versions that causing these issues.

**Comment by zlep** [comment] 2021-08-31 13:50
@ihor-sviziev 

`Checking platform requirements for packages in the vendor dir
composer-plugin-api  2.0.0       success  
ext-bcmath           7.4.23      success  
ext-ctype            7.4.23      success  
ext-curl             7.4.23      success  
ext-dom              20031129    success  
ext-fileinfo         7.4.23      success  
ext-filter           7.4.23      success  
ext-gd               7.4.23      success  
ext-hash             7.4.23      success  
ext-iconv            7.4.23      success  
ext-intl             7.4.23      success  
ext-json             7.4.23      success  
ext-libxml           7.4.23      success  
ext-mbstring         7.4.23      success  
ext-openssl          7.4.23      success  
ext-pcre             7.4.23      success  
ext-pdo_mysql        7.4.23      success  
ext-phar             7.4.23      success  
ext-simplexml        7.4.23      success  
ext-soap             7.4.23      success  
ext-sockets          7.4.23      success  
ext-sodium           7.4.23      success  
ext-tokenizer        7.4.23      success  
ext-xml              7.4.23      success  
ext-xmlwriter        7.4.23      success  
ext-xsl              7.4.23      success  
ext-zip              1.15.6      success  
lib-libxml           2.9.1       success  
lib-openssl          1.0.2.11    success  
php                  7.4.23      success  
`

Can't do the second command unfortunately:
`php -i | grep ICU
PHP Warning:  Unknown: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in Unknown on line 0
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`

**Comment by ihor-sviziev** [comment] 2021-08-31 14:32
@zlep, it looks like you don't have the ICU library installed which is really strange, as it is a dependence for the PHP intl extension

**Comment by JustADude-86** [comment] 2021-09-01 11:13
We are experiencing the same issue after upgrading from 2.3.5-p1 to 2.4.3. 

We have a custom theme and custom plugins, even after disabling everything and changing the theme to stock Luma still, the issue persists.

On de_DE, de_CH, de_AT and other (non-english) locale the issues is like the author of this thread described.
On English locales like en_US or en_GB, the issue is slightly different, the price remains but the currency symbol dissapers.

Strange.

We are running two instances of Magento on the **same server config**:
1. is Live version  2.3.5-p1 that works without any problems
2. is Staging version 2.4.3 that is experiencing these issues 

Not sure maybe it helps ;)

**Comment by ihor-sviziev** [comment] 2021-09-01 14:31
@JustADude-86, thank you for the input!
Just tried one idea - feels like it should help:
```
<?php

try {
    $reflector = new \ReflectionExtension('intl');
    ob_start();
    $reflector->info();
    $output = strip_tags(ob_get_clean());
    preg_match('/^ICU version (?:=>)?(.*)$/m', $output, $matches);
    $icuVersion = trim($matches[1]);
} catch (\ReflectionException $e) {
    $icuVersion = null;
}
echo $icuVersion . PHP_EOL;


$formatter = new NumberFormatter('de_DE', NumberFormatter::CURRENCY);
echo $formatter->getPattern() . PHP_EOL;
echo $formatter->formatCurrency(10.3, "EUR") . PHP_EOL;

$formatter->setSymbol(\NumberFormatter::CURRENCY_SYMBOL, '');
echo $formatter->getPattern() . PHP_EOL;
echo $formatter->formatCurrency(10.3, "EUR") . PHP_EOL;

$formatter->setPattern( str_replace('¤','', $formatter->getPattern() ) );
echo $formatter->getPattern() . PHP_EOL;
echo $formatter->formatCurrency(10.3, "EUR") . PHP_EOL;

EOF
```
returns 
```
50.2
#,##0.00 ¤
10,30 €
#,##0.00 ¤
10,30 €
#,##0.00 
10,30
```

Could you check the changes from the following PR if they're fixing the issue?
https://github.com/magento/magento2/pull/33966

**Comment by zlep** [comment] 2021-09-01 15:39
@ihor-sviziev I can confirm that adding these two lines to Currency.php fixes the issue.

**Comment by engcom-Hotel** [comment] 2021-09-23 08:13
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2021-09-23 11:33
@magento give me 2.4-develop instance

**Comment by ihor-sviziev** [comment] 2021-09-24 07:49
Hi,
For those who are getting this issue - the issue still not fixed.
As a temporary workaround, you can apply the following patch: https://github.com/magento/magento2/issues/33856#issuecomment-904606945

**Comment by zlep** [comment] 2021-09-24 12:44
@ihor-sviziev Why is it not fixed, though? This should have the **highest priority** since it makes localization completely useless. Magento 2.4.3 is basically only usable in countries where English is the first language.

**Comment by ihor-sviziev** [comment] 2021-09-24 14:08
@zlep, basically, it should work fine on the ICU library >= 60 I guess.

**Comment by engcom-Alfa** [comment] 2021-10-04 04:39
@magento give me 2.4.3 instance

**Closed as completed** 2021-10-07 06:30 UTC
Labels: duplicate, Severity: S1, Issue: ready for confirmation, Reported on 2.4.3

**Comment by SoCix** [comment] 2021-12-13 17:29
I am on Magento ver. 2.4.3-p1 and having same issue

**Comment by ihor-sviziev** [comment] 2021-12-14 09:24
Hi @SoCix,
Please review https://github.com/magento/magento2/issues/33856#issuecomment-946761019 for the information about fix for this issue.

**Comment by SoCix** [comment] 2021-12-14 10:55
> Hi @SoCix, Please review [#33856 (comment)](https://github.com/magento/magento2/issues/33856#issuecomment-946761019) for the information about fix for this issue.

Thanks ihor, I've applied the patch, and it is working like a charm, thank You

**Comment by StarClassicNL** [comment] 2023-06-14 13:48
First time and message on GitHub so please forgive me if I'm not approaching this correctly.
The issue discussed still exists in Magento 2.4.6 (after upgrading from 2.4.4 today)

Magento 2.4.6
CentOS Linux 7.9.2009 (+Plesk, **i know**)
PHP 8.1.20
ICU version | 50.2
ICU Data version | 50.2
ICU TZData version | 2018e
ICU Unicode version | 6.2

I have a multistore setup with 3 locale (Dutch, German and English). Pricing works as expected on the Eng locale.
I can't seem to figure out how to properly upgrade ICU 60 or 70 with confidence and without breaking anything :) so for now i'm using EN locale until there's either a fix or I understand how to upgrade my ICU package on php8.1.20 without breaking anything.
