### ISSUE TITLE
Unable to go checkout page and DOB Validation issue

### ISSUE THREAD

**Issue by geet07** [magento/magento2#26443] opened 2020-01-18 08:25 UTC
### Preconditions (*)

1. Clean Magento 2.4
2.

### Steps to reproduce (*)

1. Set Customer Date of Birth and Tax/VAT Number required in Customer Name and Address options
2. Save Configuration
3. Add to cart and go to Checkout (after clearing Cache etc.)

### Expected result (*)

1. Successfully checkout page show.  
2. If choose date of birh from calender in account information then save successfully. 

### Actual result (*)

1. Can't go to checkout page and redirect to account information page.
2. After we save DOB from calender then get validation error, please see screenshot
![Account Information](https://user-images.githubusercontent.com/9483040/72660870-8f2dba00-39f9-11ea-9d75-d18dea12b71b.png)

### Additional Information
based on https://github.com/magento/magento2/issues/26443#issuecomment-576593632

> Same date validation issue at sign up form
> Provided to js date format 'M/d/Y' that not parsed correctly

**Comment by krishprakash** [comment] 2020-01-18 10:44
@magento give me 2.4-develop instance

**Comment by Den4ik** [comment] 2020-01-21 09:27
Same date validation issue at sign up form
Provided to js date format 'M/d/Y' that not parsed correctly

**Comment by magento-engcom-team** [comment] 2020-01-21 19:58
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-21 19:59
:white_check_mark: Confirmed by @Den4ik 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30630` were created

**Issue Available**: @Den4ik, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2020-01-21 20:01
Hi @krishprakash, here is your [Magento instance](https://i-26443-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26443-2-4-develop.instances.magento-community.engineering/admin_4ede](https://i-26443-2-4-develop.instances.magento-community.engineering/admin_4ede)
Login: `66099259` Password: `7ea4577a7e2b`
Instance will be terminated in up to 3 hours.

**Comment by Amit-Hariyani** [comment] 2020-10-10 06:04
@magento I am working on this

**Closed as completed** 2020-11-05 13:08 UTC
Labels: Component: Customer, Issue: Clear Description, Issue: Confirmed, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Validator, Reproduced on 2.4.x, Priority: P2, Severity: S2, Triage: Done, Progress: done, CD, Reported on 2.4.0

**Comment by sdzhepa** [comment] 2020-11-05 19:20
The related internal Jira ticket `MC-30630` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem on the latest `2.4-develop` please create new Issue with updated information/steps/preconditions in the **_Description section_**.
