### ISSUE TITLE
 Resource id issue

### ISSUE THREAD

**Issue by sas-flame** [magento/magento2#4918] opened 2016-06-07 13:33 UTC
## Steps to reproduce
1. Install Magento from `2.0` branch.
2. Go to System->User Roles.
3. Select the administrators role.
4. Set the custom resource access. 
5. Ensure that Store Email Addresses Section checkbox is checked.
6. Click the Save Role button.

Expected result:
 Store Email Addresses Section should be visible in the admin panel

Actual result:
 Store Email Addresses Section is not visible in the admin panel

Reason:
Mismatch of the resource id in the files:
https://github.com/magento/magento2/blob/2.0/app/code/Magento/Config/etc/acl.xml
https://github.com/magento/magento2/blob/2.0/app/code/Magento/Backend/etc/adminhtml/system.xml

**Comment by cpartica** [comment] 2016-06-21 00:34
Are you referring to Magento_Config::trans_email vs Magento_Backend::trans_email ?

**Comment by sas-flame** [comment] 2016-06-21 08:29
Yes, I referring to Magento_Config::trans_email vs Magento_Backend::trans_email.

Also the next ids have mismatch:

Magento_Config::advanced vs Magento_Backend::advanced

Magento_Config::currency vs Magento_Backend::currency 

Magento_Config::dev vs Magento_Backend::dev  

Magento_Config::web vs Magento_Backend::web 

Magento_Config::sendfriend vs Magento_Backend::sendfriend

**Comment by veloraven** [comment] 2016-10-12 14:35
Internal ticket MAGETWO-59656 was created for this issue

**Comment by magento-engcom-team** [comment] 2017-10-12 13:30
@sas-flame, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-12 13:30 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid
