### ISSUE TITLE
mixins for priceBox::reloadPrice not working consistently accross browsers

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#35097] opened 2022-02-14 08:55 UTC
### Preconditions (*)

1. Magento 2.4.3-p1 
2. Firefox 97/98

### Steps to reproduce (*)
Create a module and add the following file 

app/code/Vendor/Module/view/frontend/requirejs-config.js
```js


var config = {
    config:
        {
            mixins: {
                'Magento_Catalog/js/price-box':
                    {
                        'Vendor_Module/js/price-box-mixin': true
                    }
            }
        }
};
```

Follow the documentation to add a mixin for `reloadPrice`

app/code/Vendor/Module/view/frontend/web/js/price-box-mixin.js
```js

define([
    'jquery',
    'mage/utils/wrapper',
    'jquery/ui',
], function ($, wrapper) {
    'use strict';

    var widgetMixin = {
        reloadPrice: function () {
            console.log('mixin reload price1');
            return this._super();
        }
    };

    return function (targetWidget) {
        // Example how to extend a widget by mixin object
        $.widget('mage.priceBox', targetWidget, widgetMixin); // the widget alias should be like for the target widget

        return $.mage.priceBox; //  the widget by parent alias should be returned
    };
});
```

It seems the same behaviour is happening for klarma pricebox-widget-mixin.js 

To make an easier example, I added a console.error in klarma mixin as well. 

### Expected result (*)

1. The mixin is always executed like in Chrome
![image](https://user-images.githubusercontent.com/20220341/153831168-2015a5cc-966d-4d6d-ba3c-a706ca2c7e47.png)

### Actual result (*)
1. The mixin is not executed in firefox or randomly executes as you can see in console.log neither for the custom module nor for klarma mixin
![image](https://user-images.githubusercontent.com/20220341/153831404-9dfba31c-c78b-4148-aaa7-7ed1b9f0f66c.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2022-02-17 14:39
Hi @ioweb-gr ,

Thank you for reporting an issue . Kindly provide more clarity on which documentation we should refer please?
"Follow the documentation to add a mixin for reloadPrice"

Hence, added the label 'Needs Update'.

Thanks

**Comment by ioweb-gr** [comment] 2022-02-17 14:41
Hi it's this one https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/javascript/js_mixins.html

**Comment by engcom-Delta** [comment] 2022-02-17 14:48
Hi @ioweb-gr ,
Thanks for confirming the document.

**Comment by engcom-Echo** [comment] 2022-07-22 11:11
Hello @ioweb-gr,

Thanks for you contribution and collaboration.
We have tried to reproduce this issue on magento 2.4-develop branch but it is not able to reproduce.

followed steps.
1.Create a magento module.
2.app/code/Vendor/Module/view/frontend/requirejs-config.js

```
var config = {
    config:
        {
            mixins: {
                'Magento_Catalog/js/price-box':
                    {
                        'Vendor_Module/js/price-box-mixin': true
                    }
            }
        }
};
```
3. app/code/Vendor/Module/view/frontend/web/js/price-box-mixin.js

```
define([
    'jquery',
    'mage/utils/wrapper',
    'jquery/ui',
], function ($, wrapper) {
    'use strict';

    var widgetMixin = {
        reloadPrice: function () {
            console.log('mixin reload price1');
            return this._super();
        }
    };

    return function (targetWidget) {
        // Example how to extend a widget by mixin object
        $.widget('mage.priceBox', targetWidget, widgetMixin); // the widget alias should be like for the target widget

        return $.mage.priceBox; //  the widget by parent alias should be returned
    };
});

```
Please find the attached screen for your reference.
firefox version 97

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51681435/180425836-9816fb30-480e-4733-a904-3a10312e037e.png">

Chrome version 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51681435/180426889-9b241113-d26d-412a-9d17-03ff56f3421d.png">

Please check if i missed anything and kindly check on magento 2.4-develop branch and provide more information so that we can reproduce this issue.

Thanks

**Comment by engcom-Echo** [comment] 2022-08-08 09:38
Hello @ioweb-gr,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Echo** 2022-08-08 09:38 UTC
Labels: Area: Frontend, Triage: Dev.Experience, Issue: needs update

**Comment by amenk** [comment] 2023-03-15 17:37
@engcom-Echo When reproducing, how many times did you reload? The OP states that this happens randomly, so at least the page should be Ctrl+Shift+F5 reloaded 10 times or so I think and it should be checked if it always loads.
We have a similar problem in 2.4.5 and seek for a solution in https://magento.stackexchange.com/questions/354911/magento-2-4-3-js-mixin-file-not-loading-on-each-page-load

**Comment by ioweb-gr** [comment] 2025-02-27 05:32
Try this one out 

https://github.com/magento/magento2/pull/39097/files

It helped us

**Comment by ioweb-gr** [comment] 2025-02-27 12:34
Unfortunately the person who started the PR doesn't seem to be available to sync it with the main branch so it doesn't get merged on live. We'll need at some point to take his code, merge it in the branch and start a new PR for that.
