### ISSUE TITLE
Max creditmemo shipping amount allowed is negative

### ISSUE THREAD

**Issue by digitalpianism** [magento/magento2#38556] opened 2024-03-28 15:15 UTC
### Preconditions and environment

- Magento 2.4.4-p7
- Tax rate set to 10%
- Shipping tax rate is 10% too
- Shopping cart rule setup like this:
 
![image](https://github.com/magento/magento2/assets/16592249/55569fe8-f4f5-46e8-995a-cf19e25cbcd8)

### Steps to reproduce

- Create an order like this:
![image](https://github.com/magento/magento2/assets/16592249/e5758f4d-b9c8-495a-94d0-c499ef3c34f4)
- Refund the second item and the shipping like this:
![image](https://github.com/magento/magento2/assets/16592249/151f2835-9788-4534-bf32-9aa0661ab032)
- Order is now in the following state:
![image](https://github.com/magento/magento2/assets/16592249/cfbad084-7746-41c2-a7c6-701f7f3ac09e)
- Now refund the first item like this: (Notice how Magento automatically setup a 0.01 refund shipping here (we'll get to that))
![image](https://github.com/magento/magento2/assets/16592249/3eb780d9-43a1-4538-b847-986c001e5cf3)

### Expected result

Items should be refunded.

### Actual result

Refund fails with the following error:
![image](https://github.com/magento/magento2/assets/16592249/bd6acce8-cf9b-4e78-84f8-32e73215071b)

### Additional information

Problem seems to come from the fact that sometimes, the maximum refundable shipping amount allowed is negative, here's the fix I have used to prevent the problem from happening:

```
diff --git a/src/vendor/magento/module-sales/Model/Order/Creditmemo/Total/Shipping.php b/src/vendor/magento/module-sales/Model/Order/Creditmemo/Total/Shipping.php
index f644d0c3a5..acc91cd623 100644
--- a/src/vendor/magento/module-sales/Model/Order/Creditmemo/Total/Shipping.php
+++ b/src/vendor/magento/module-sales/Model/Order/Creditmemo/Total/Shipping.php
@@ -70,7 +70,7 @@ class Shipping extends AbstractTotal

             // Since the user (admin) supplied 'desiredAmount' it already has tax -OR- does not include tax
             $desiredAmount = $this->priceCurrency->round($creditmemo->getBaseShippingAmount());
-            $maxAllowedAmount = ($useAmountsWithTax ? $baseAllowedAmountInclTax : $baseAllowedAmount);
+            $maxAllowedAmount = abs($useAmountsWithTax ? $baseAllowedAmountInclTax : $baseAllowedAmount);
             $originalTotalAmount = ($useAmountsWithTax ? $orderBaseShippingInclTax : $orderBaseShippingAmount);

             // Note: ($x < $y + 0.0001) means ($x <= $y) for floats

```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by digitalpianism** [comment] 2024-03-28 15:15
@magento give me 2.4-develop instance

**Comment by digitalpianism** [comment] 2024-03-28 15:53
Having a hard time replicating my situation because of the default USA config setup in the test instance, I can't get the totals to show up like my original test.

**Comment by engcom-Bravo** [comment] 2024-03-29 05:39
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-03-29 08:06
Hi @digitalpianism,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

<img width="1332" alt="Screenshot 2024-03-29 at 12 05 21" src="https://github.com/magento/magento2/assets/51680745/cc9514d4-b453-47da-8f37-f4c9e084b3b6">



<img width="1341" alt="Screenshot 2024-03-29 at 12 05 44" src="https://github.com/magento/magento2/assets/51680745/7f7c2f65-fac6-4746-b6e4-153f5e10617d">



We are able to create credit memo for the second product and shipping amount is not in 0.01.

Could you please let us know if we are missing anything.

Thanks.

**Comment by digitalpianism** [comment] 2024-03-29 09:05
@engcom-Bravo I guess it's most likely because my tax configuration is more complex in my environment but I can't recreate it on a default Magento instance. I guess you can close it, if someone ever faces the issue I've posted the fix anyway.

**Comment by engcom-Bravo** [comment] 2024-04-01 04:26
Hi @digitalpianism,

Thanks for your update.

As per this https://github.com/magento/magento2/issues/38556#issuecomment-2026914201 we are Closing this issue.Please feel free to reopen the issue if you are facing any issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-04-01 04:26 UTC
Labels: Issue: needs update, Reported on 2.4.4-p7
