### ISSUE TITLE
Can't set products' Out of Stock Threshold to a negative value 

### ISSUE THREAD

**Issue by diamondavocado** [magento/magento2#25158] opened 2019-10-19 03:09 UTC
### Preconditions (*)

1. Magento 2.3.2

### Steps to reproduce (*)

1. In the Magento backend, go to Catalog -> Products and open a simple product
2. Go to General section and click "Advanced Inventory"
3. Enter a negative value into the "Out of Stock Threshold" field (e.g. -20)
4. Save the product and reload the page

### Expected result (*)

1. Out of Stock Threshold value should remain negative after save

### Actual result (*)

1. Out of Stock Threshold value gets set to zero (0)

**Comment by diamondavocado** [comment] 2019-10-19 03:10
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-10-19 03:10
Hi @diamondavocado. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-10-19 03:11
Hi @diamondavocado, here is your [Magento instance](https://i-25158-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25158-2-3-develop.instances.magento-community.engineering/admin](https://i-25158-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by diamondavocado** [comment] 2019-10-19 03:15
@m2-assistant 
Confirmed present on 2.3-develop instance.

**Before saving:**
![image](https://user-images.githubusercontent.com/32345083/67137068-6e519f00-f227-11e9-989a-8dc01255a231.png)

**After saving:**
![image](https://user-images.githubusercontent.com/32345083/67137064-6265dd00-f227-11e9-8794-c8b0aae09186.png)

Could be related to [Issue 9139](https://github.com/magento/magento2/issues/9139).

**Comment by dmytro-ch** [comment] 2019-10-19 10:24
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-10-19 10:24
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-10-19 10:24
Hi @dmytro-ch, here is your [Magento instance](https://i-25158-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25158-2-3-develop.instances.magento-community.engineering/admin](https://i-25158-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by dmytro-ch** [comment] 2019-10-19 10:53
There is the same behavior both product and system configuration (global) *Out-of-Stock Threshold* fields.
However, it should be possible to set a negative value for Out-of-Stock Threshold. DevDocs reference: https://docs.magento.com/m2/ce/user_guide/catalog/inventory-backorders.html#out-of-stock-threshold

Thank you!

**Comment by magento-engcom-team** [comment] 2019-10-19 10:54
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21941` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gwharton** [comment] 2019-10-21 08:13
As a workaround, consider researching effect of, and enabling MSI as a) its coming and you probably wont be able to avoid it and b) negative thresholds work as designed (although backorder notifications are a bit whiffy at the moment, pending PR)

**Comment by Bartlomiejsz** [comment] 2019-10-21 18:55
Hi @p-bystritsky, I wanted to work on this issue but I noticed that similar fix to what I wanted to do was already committed https://github.com/magento/magento2/commit/6f4df9be6a8f2a43b08b3831821d01fe6f1e4c2f#diff-1555bd96a37cc3d7a70869442e07a012 and then reverted in https://github.com/magento/magento2/commit/b21394fa5d4a860476c32b1d678eb577b8ac3c83#diff-1555bd96a37cc3d7a70869442e07a012 - not sure why because this was some internal work, but without info regarding it, it is impossible to work on it...

**Comment by veloraven** [comment] 2020-06-17 17:18
Described issue is not a bug.
To enable Negative  "Out of Stock Threshold" you need to turn on "Backorders" as well. This functionality is described in [Configure MSI backorders|https://github.com/magento/inventory/wiki/Configure-MSI-backorders].
When backorders are enabled issue is not reproducible and negative threshold is saved successfully.

**Comment by sdzhepa** [comment] 2020-06-17 17:44
Closed due to prev https://github.com/magento/magento2/issues/25158#issuecomment-645507793

**Closed as completed by sdzhepa** 2020-06-17 17:44 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: CatalogInventory

**Comment by cbichis** [comment] 2020-07-29 07:27
With backorders set properly this is still an issue on Magento 2.3.3.

**Comment by frachello89** [comment] 2020-10-16 10:58
I have same issue on Magento 2.3.3 EE, backorders enabled at product level, product is In Stock with Qty 1, but when I save the Out-of-Stock Threshold at -1 (for example) value after saving is 0.

**Comment by ngtuan96lc** [comment] 2022-12-08 03:29
I'm still facing this issue on Magento 2.4.3-p1.
pls have a look at file **\Magento\CatalogInventory\Model\System\Config\Backend\Minqty:**
```
    public function beforeSave()
    {
        parent::beforeSave();
        $minQty = (int) $this->getValue() >= 0 ? (int) $this->getValue() : (int) $this->getOldValue();
        $this->setValue((string) $minQty);
        return $this;
    }
```
The above snippet code describes that the new stored value is always greater than 0.
It means we can not save a negative value on that field, so confused!
Please check it @magento-engcom-team
