### ISSUE TITLE
[Issue] Product event hooks not fired with multiple reorder usage

### ISSUE THREAD

**Issue by jglassmaker** [magento/magento2#33909] opened 2021-08-25 18:53 UTC
The `sales_quote_add_item` event is not fired when using the customer "Reorder" link more than once. Custom business logic is not performed consistently when bound to add item to cart events. Customers who click "Reorder" more than once to "double" their previous order result in malformed carts because our business logic is only executed the first time. Other product events are also not firing - though only the `sales_quote_add_item` is expected to with this issue.

### Preconditions (*)
1. Magento 2.4.2
2. Create a customer account, place an order so that the customer reorder can be used

### Steps to reproduce (*)
1. Create a customer account or use an existing customer account
2. Place an order
3. Go into My Account page and use the customer "Reorder" link on the previous order
4. After the cart is update, click the "Reorder" link again to have a cart with twice the original order

### Expected result (*)
1. The `sales_quote_add_item` event should fire for each order item when the reorder feature is used

### Actual result (*)
1. Upon the second time the customer clicks "Reorder", no `sales_quote_add_item` events are fired

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment] 2021-08-30 06:46
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment] 2021-08-30 09:03
Hello @jglassmaker 
I tried to reproduce this issue on clean **2.4-develop** with the given steps to reproduce & was not able to reproduce.
Please check the video in this regard. This issue might have been fixed in **2.4-develop** & would be available with next **2.4.x** release.

https://user-images.githubusercontent.com/51681435/131314846-9c9b5ae1-d9b3-4d09-b418-94c0e5b5153e.mov


So can you please check this issue on a clean **2.4-develop** instance & check if its still reproducible for you or if am missing out on any steps, please let me know the details of the same.
Thank you.

**Comment by jglassmaker** [comment] 2021-08-30 16:16
I don't believe I explained the issue clearly enough. The normal functionality of the reorder works fine. The issue is that 3rd party modules are not able to hook into the reorder events properly.

I recorded a video of me showing this. The first part I am normally adding a product to my cart and on the right my custom module is adding an additional product, the important part is that the events are firing. In the second part near the end you can clearly see that the second time I use the reorder function, no events are fired and caught by my xdebug.


https://user-images.githubusercontent.com/6683072/131370812-f211c003-63dc-4e8d-baf3-d0adc93638bb.mov

**Comment by engcom-Echo** [comment] 2021-09-03 05:36
Hi @jglassmaker, I believe the default reorder functionality of magento is working as expected. But as per your recent comments, this issue seems to happen on a third party module integration. So inorder process this issue further please provide us with more details regarding this custom module(if its an open source then please share the related links for the same or if its your own custom module share related code snippets), so that we can replicate at our end & further analysis.
Thank you

**Comment by jglassmaker** [comment] 2021-09-07 14:46
The custom module in my example was just something I wrote quickly for the example, I am including it in this response. You are correct, the default reorder functionality of Magento is working fine, it is the event hooks that are not firing correctly which hinders external business logic support. 

The business logic we are trying to accomplish is having a setup fee added for certain products, so we are adding another product to the cart which is the "setup fee" which cannot be removed/modified by the customer. When the reorder is used multiple times our extra business logic is not being executed and so multiple "setup fee" products are being added to the cart. I can explain this more but the key is that the events are not always firing when reorder is used.

[app code.zip](https://github.com/magento/magento2/files/7122368/app.code.zip)

**Comment by engcom-Echo** [comment] 2021-12-30 09:22
Hi @jglassmaker,

Thank you for providing the code details.

However I think the issue maybe with your code since default functionality of Magento is working fine. Since the issue is happening after adding custom code so I am not sure if there is anything that we can do to make Magento functionality better. Can you please check and update if you have found any specific Magento core file which could have caused reorder related issue ?

Thanks

**Comment by engcom-Echo** [comment] 2022-01-13 07:13
Hi @jglassmaker,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket with the requested details in last comment if you need more assistance on this.

Thanks

**Closed as completed by engcom-Echo** 2022-01-13 07:13 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.2
