### ISSUE TITLE
When take reorder then at shopping cart, two records are get mixed into one record. Pls see description & attached screen-shot. 

### ISSUE THREAD

**Issue by sachinkalerws** [magento/magento2#3654] opened 2016-03-04 11:38 UTC
![records are mixed](https://cloud.githubusercontent.com/assets/17641550/13526090/a49cea3e-e22b-11e5-9f53-7befff9fb6ef.jpg)
1 - I have add to cart, two records of configurable product as Green color, L size with 4 qty and Orange Color, L size with 1 qty.

2 - Place order and take reorder of same.

O/P==> At shopping cart, two records are get mixed into one record and display as Orange color, L size and 5 qty.

**Comment by sdzhepa** [comment] 2016-03-07 14:57
@sachinkalerws   Thank you for reporting this issue. We have created an internal ticket `MAGETWO-50198` to fix the problem.

**Comment by alena-marchenko** [comment] 2016-04-26 16:12
Hi @sachinkalerws 

The issue is resolved already and delivered to develop branch. Closing the issue.

**Closed as completed by alena-marchenko** 2016-04-26 16:12 UTC
Labels: Issue: Ready for Work, bug report
