### ISSUE TITLE
Old core_config_data records of advanced/modules_disable_output still exists & has effect, but there's no interface for changing them

### ISSUE THREAD

**Issue by pniel-cohen** [magento/magento2#13348] opened 2018-01-24 11:06 UTC
Since we upgraded to Magento 2.2.2 we can't see the 'Advanced/Advanced' on Stores > Configuration.
It's fine if you decided to remove that, but it seems like old values still exists on core_config_data & they has effect on the modules (I had to edit those directly on phpmyadmin...).

**Comment by magento-engcom-team** [comment] 2018-01-24 12:42
Duplicate of #11191

**Comment by magento-engcom-team** [comment] 2018-01-24 12:45
Releted to #11191

**Comment by orlangur** [comment] 2018-01-24 12:45
@magento-engcom-team does not look like a duplicate to me due to

> & they has effect on the modules (I had to edit those directly on phpmyadmin...).

@pini-girit please check comment in https://github.com/magento/magento2/blob/9c14af7a97bcf338662de365d2613c7ca9dbf8c6/lib/internal/Magento/Framework/Module/Manager.php#L70

**Comment by magento-engcom-team** [comment] 2018-01-24 12:51
@orlangur , yes not a duplicate, but related
@pini-girit , please check the http://devdocs.magento.com/guides/v2.2/release-notes/ReleaseNotes2.2.0CE.html

**Closed as completed** 2018-01-24 13:51 UTC
Labels: non-issue, Issue: Format is not valid

**Comment by magento-engcom-team** [comment] 2018-01-24 14:30
@pini-girit, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
