### ISSUE TITLE
Elasticsearch server failed

### ISSUE THREAD

**Issue by TalibSaifi003** [magento/magento2#39081] opened 2024-08-21 12:21 UTC
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

https://prnt.sc/PxHe99FMaf4O
we are getting a warning message related to Elasticsearch on the admin dashboard

### Expected result

It should not come.

### Actual result

We have checked all configurations and functionality related to Elasticsearch. All functionality is working fine. We are not getting any issues related to Elasticsearch on our site. However, the warning message is still showing on the admin dashboard. please check the screenshot and help us remove it.The Magento version is 2.4.2.We have tried to restart Elasticsearch.
https://prnt.sc/PxHe99FMaf4O

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2024-08-27 12:01
Hi @TalibSaifi003 ,

Thanks for your reporting and collaboration.
We have verified the issue in latest 2.4-develop instance and issue is not reproducible . Kindly refer the screenshots.

**Steps to Reproduce :** 
1. Install latest 2.4-develop instance.
2. Set catalog search to elastic search
3. Save the configuration and observe the admin
![image](https://github.com/user-attachments/assets/49048dc7-2701-424a-b19e-4067276aae31)

4. Note Error is not displaying.
![image](https://github.com/user-attachments/assets/335bb212-34b1-4592-b99a-8c5ee07866f6)

5. Now, disable elastic search module and the enable it.
6. Access Admin and observe error is not displaying
![image](https://github.com/user-attachments/assets/523ef770-a46b-406e-856b-d2f00bffd61a)
Please let us know if any other steps are needed to be performed.

Thanks.

**Comment by engcom-Delta** [comment] 2024-09-11 05:51
Hi @TalibSaifi003 ,

We have noticed that this issue has not been updated since long time.
Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Delta** 2024-09-11 05:51 UTC
Labels: Issue: needs update, Reported on 2.4.x
