### ISSUE TITLE
Magento 2.2.1 Import tier price, wrong values for column tier_price_value_type

### ISSUE THREAD

**Issue by MattDelac** [magento/magento2#12384] opened 2017-11-21 21:43 UTC
### Preconditions

1. Magento 2.2.1
2. Mariadb

### Steps to reproduce

1. Create a csv with all the necessary columns 
- "sku"
- "tier_price_website"
- "tier_price_customer_group"
- "tier_price_qty"
- "tier_price"
- "tier_price_value_type"
2. Write "Discount" for all rows in the "tier_price_value_type" column

### Expected result

1. The tier price type should be "Discount"

### Actual result

1.The tier price type in the backoffice is marked as "Fixed" ==> thus this column is not well imported

If at the same time, someone can tell me the difference between "Discount" and "Fixed" tier price type, it would be nice :)

Thank you and have a nice day
Matt

**Comment by magento-engcom-team** [comment] 2017-11-22 10:59
Hello @MattDelac. Thanks for reporting. We were able to reproduce Your issue only with the rows where tier_price column values were equal to zero. Please tell us whether Your have the same case.

**Comment by MattDelac** [comment] 2017-11-22 13:23
Hello @magento-engcom-team ,

Thanks for your quick reply.

Regarding my case, it concerns **all rows** !

Thank you

**Comment by magento-engcom-team** [comment] 2017-11-22 15:01
If You don't mind @MattDelac still let us make it clearer. Assume there is a file for import. It contains a row with sku = "abc1", ...., tier_price = 2, tier_price_value_type = "Discount". In this case after import has been made, the tier price type for the product abc1 in the Backend is marked as "Fixed". Do You mean You would observe exactly this behavior with such a value for tier_price?

**Comment by magento-engcom-team** [comment] 2017-11-23 09:03
Also @MattDelac, it would be great if You could send us Your file for the import so we can try to reproduce Your issue with original data. Thank You.

**Comment by MattDelac** [comment] 2017-11-23 12:20
@magento-engcom-team 
1) Yes the problem you described is exactly what I see

2) Here is a csv file (I just change .csv for .txt to upload it in github)
[advanced_pricing_test1.txt](https://github.com/magento/magento2/files/1498983/advanced_pricing_test1.txt)

At the end, I import 450k + rows concerning the tier prices

**Comment by MattDelac** [comment] 2017-11-23 12:22
Here is an example for product : 410042 (that is present in the file above)
![screenshot from 2017-11-23 07-21-32](https://user-images.githubusercontent.com/18557047/33172662-07a26298-d01f-11e7-8cda-950751d2badd.png)

**Comment by magento-engcom-team** [comment] 2017-11-24 15:32
Hi again @MattDelac. Again we managed to reproduce Your issue but just in the special case. If while picking up the Entity Type in Import Settings one picks up Products in stead of Advanced pricing by mistake the import file will pass the validation, the whole import will be successful according to the notifications. But in fact nothing will be changed. So if one has "Fixed" those "Fixed" will remain. Please confirm it's not Your case. Thank You.

**Comment by magento-engcom-team** [comment] 2017-12-08 08:36
@MattDelac, we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Closed as completed by magento-engcom-team** 2017-12-08 08:36 UTC
Labels: Progress: needs update, Issue: Clear Description, Issue: Format is valid
