### ISSUE TITLE
The configuration parameter "componentType" is a required for "cms_page_columns" component.

### ISSUE THREAD

**Issue by andrii-dymov** [magento/magento2#13633] opened 2018-02-13 11:49 UTC
### Preconditions
Magento 2.2.2

### Steps to reproduce
1. Create admin user with role with access only to Content -> Elements -> Blocks
2. Login as this user
3. Go to Content -> Blocks

### Expected result
Blocks Grid

### Actual result
`Exception #0 (Magento\Framework\Exception\LocalizedException): The configuration parameter "componentType" is a required for "cms_page_columns" component.

magento/framework/View/Element/UiComponentFactory.php(396): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false)`

### Workarounds
1. add permission to Content -> Elements -> Pages -> Save Page

2. add "after" plugin for `Magento\Cms\Ui\Component\DataProvider::prepareMetadata`
and set `$result['cms_page_columns']['arguments']['data']['config']['componentType'] = 'columns';`

**Comment by magento-engcom-team** [comment] 2018-02-13 14:18
@awarche, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by engcom-Bravo** [comment] 2019-12-31 10:50
Hello @andrii-dymov

We are not able to reproduce the issue on Magento 2.4-develop
We have created a User Role, as described in the  Steps To Reproduce 
![content_element_blocks](https://user-images.githubusercontent.com/51680745/71619186-ce6fa480-2bcb-11ea-94bf-22fd152bfd0e.png)

Assigned it to a User and Signed In with him.
**Actual Result**: All the blocks are displayed
![blocks_grid](https://user-images.githubusercontent.com/51680745/71619107-73d64880-2bcb-11ea-9e79-113acfb621d3.png)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) .
Thank you for collaboration.

**Closed as completed by engcom-Bravo** 2019-12-31 10:50 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid

**Comment by mpsuganesh** [comment] 2021-01-06 15:28
Hi @engcom-Bravo ,

When I click on the "Add Product" button after I got "The "componentType" configuration parameter is required for the "" component". can you help me please . How I can fix this issues.

**Comment by tuyennn** [comment] 2021-01-19 03:48
@engcom-Bravo 
I have same issue on Magento 2.4.1

```
The "componentType" configuration parameter is required for the "" component
```
Seem there are something broken but not sure where it is with blank quote

**Comment by Sabrina-tahir** [comment] 2022-01-25 15:59
> @engcom-Bravo I have same issue on Magento 2.4.1
> 
> ```
> The "componentType" configuration parameter is required for the "" component
> ```
> 
> Seem there are something broken but not sure where it is with blank quote

did u find any sol?

**Comment by zaietsv** [comment] 2025-03-26 11:07
The issue still persists on Magento 2.4.6-p9. As a workaround It is necessary to check new ACL restrictions related to the CMS. In a my case it was necessary to enable a node "Pages -> Save Page -> Edit page design" 

![Image](https://github.com/user-attachments/assets/ff9ce2f8-e35f-4bfb-991d-c48849f3de3f)



Here is an error backtrace
`Magento\Framework\Exception\LocalizedException: The "componentType" configuration parameter is required for the "cms_page_columns" component. in /var/www/html/vendor/magento/framework/View/Element/UiComponentFactory.php:405
Stack trace:
#0 /var/www/html/vendor/magento/framework/View/Element/UiComponentFactory.php(425): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false)
#1 /var/www/html/vendor/magento/framework/View/Element/UiComponentFactory.php(334): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false)
#2 /var/www/html/vendor/magento/framework/View/Element/UiComponentFactory.php(231): Magento\Framework\View\Element\UiComponentFactory->mergeMetadata('cms_block_listi...', Array, false)
#3 /var/www/html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(140): Magento\Framework\View\Element\UiComponentFactory->create('cms_block_listi...', NULL, Array)
#4 /var/www/html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(103): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'cms_block_listi...', Array, Object(Magento\Framework\View\Layout\Interceptor))
#5 /var/www/html/vendor/magento/framework/View/Layout/GeneratorPool.php(93): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#6 /var/www/html/vendor/magento/framework/View/Layout.php(365): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#7 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(32): Magento\Framework\View\Layout->generateElements()
#8 /var/www/html/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#9 /var/www/html/vendor/magento/framework/View/Page/Builder.php(65): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#10 /var/www/html/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#11 /var/www/html/vendor/magento/framework/View/Layout.php(271): Magento\Framework\View\Layout\Builder->build()
#12 /var/www/html/vendor/magento/framework/View/Layout.php(896): Magento\Framework\View\Layout->build()
#13 /var/www/html/vendor/magento/module-backend/Model/View/Result/Page.php(26): Magento\Framework\View\Layout->getBlock('menu')
#14 /var/www/html/vendor/magento/module-cms/Controller/Adminhtml/Block.php(42): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Cms::cm...')
#15 /var/www/html/vendor/magento/module-cms/Controller/Adminhtml/Block/Index.php(43): Magento\Cms\Controller\Adminhtml\Block->initPage(Object(Magento\Backend\Model\View\Result\Page\Interceptor))
#16 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Cms\Controller\Adminhtml\Block\Index->execute()
#17 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor->___callParent('execute', Array)
#18 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor->Magento\Framework\Interception\{closure}()
#19 /var/www/html/generated/code/Magento/Cms/Controller/Adminhtml/Block/Index/Interceptor.php(23): Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor->___callPlugins('execute', Array, Array)
#20 /var/www/html/vendor/magento/framework/App/Action/Action.php(111): Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor->execute()
#21 /var/www/html/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor->___callParent('dispatch', Array)
#24 /var/www/html/vendor/weltpixel/m2-weltpixel-backend/Plugin/Utility.php(76): Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#25 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): WeltPixel\Backend\Plugin\Utility->aroundDispatch(Object(Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 /var/www/html/vendor/weltpixel/m2-weltpixel-backend/Plugin/Utility.php(76): Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#27 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): WeltPixel\Backend\Plugin\Utility->aroundDispatch(Object(Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#28 /var/www/html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#29 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#30 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#31 /var/www/html/generated/code/Magento/Cms/Controller/Adminhtml/Block/Index/Interceptor.php(32): Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor->___callPlugins('dispatch', Array, NULL)
#32 /var/www/html/vendor/magento/framework/App/FrontController.php(245): Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#33 /var/www/html/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse(Object(Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor), Object(Magento\Framework\App\Request\Http))
#34 /var/www/html/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\Cms\Controller\Adminhtml\Block\Index\Interceptor))
#35 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#36 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#37 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#38 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#39 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#40 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#41 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent('launch', Array)
#42 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#43 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http\Interceptor->___callPlugins('launch', Array, Array)
#44 /var/www/html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#45 /var/www/html/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#46 {main}`

**Comment by dennismetz** [comment] 2025-04-08 08:57
The error still exists in Magento 2.4.7p4

**Comment by ctadlock** [comment] 2025-04-11 00:49
This is still an issue in Magento 2.4.5-p5. 

It's only a 7 years old bug, so maybe in a couple years someone will get around to fixing it.
