### ISSUE TITLE
Deprecated Functionality: strlen() CouponPost.php

### ISSUE THREAD

**Issue by kerlama** [magento/magento2#36678] opened 2022-12-28 08:19 UTC
### Preconditions and environment

Magento 2.4.4 / 2.4.4-p1 and p2
PHP 8.1.x

### Steps to reproduce

1. Create a new coupon code
2. Apply it on the cart page
3. Coupon is applied
4. Then click couple of times on cancel coupon button

### Expected result

Coupon is cancelled w/o error thrown

### Actual result

Coupon is cancelled the moment you first clicked, but due to multiple clicks and requests sent to the server, magento tries to execute routine for cancelling it again and again and thus why this error is thrown:

`Deprecated Functionality: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in vendor/magento/module-checkout/Controller/Cart/CouponPost.php on line 79`

### Additional information

It would be good to add disable attribute to cancel / apply button once clicked, like on proceed to checkout.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by kerlama** [comment] 2022-12-28 08:21
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by engcom-Dash** [comment] 2022-12-28 18:35
Hi @kerlama ,

We are trying to reproduce the issue in 2.4.4 Magento instance,But we are not able to reproduce the issue Because we are getting expected result.

Magento Version:2.4.4
PHP version :8.1

Steps:
1.Install Fresh Magento instance
2.Create Coupon in Magento admin panel
3.Go to front end and add the product to cart
4.Apply coupon code
5.As per description trying to cancel the coupon code with double click
6.Coupon is cancelled and error displaying in console.

Screenshot for your reference:
<img width="1433" alt="Screenshot 2022-12-29 at 12 00 23 AM" src="https://user-images.githubusercontent.com/60198592/209857383-b5094b45-4ac4-4c2a-9d5a-4ba33714a3f5.png">


Let us know if we missing anything!!!

Thanks!!!

**Comment by engcom-Dash** [comment] 2023-01-09 13:21
Hi @kerlama ,

We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-Dash** 2023-01-09 13:21 UTC
Labels: Issue: needs update, Reported on 2.4.4-p2

**Comment by KCzaplinskaAcc** [comment] 2023-10-18 07:10
We have the same issue - Magento 2.4.4-p6 with PHP 8.1

We saw that a double click is not enough to see the error result. **Please test it again but remove the coupon code a couple of times ( >= 3 clicks on the button).**

We suggest to fix the code line:
magento/module-checkout/Controller/Cart/CouponPost.php:79
`if (!$codeLength && !strlen($oldCouponCode)) {
            return $this->_goBack();
        }`
to:
`if (!$codeLength && !$oldCouponCode) {
            return $this->_goBack();
        }`

because there is a case when `$oldCouponCode = $cartQuote->getCouponCode()` is null and passing null to the PHP strlen function is now deprecated.
