### ISSUE TITLE
Session permission error on Magento CLI install

### ISSUE THREAD

**Issue by stefandoorn** [magento/magento2#3169] opened 2016-01-27 21:55 UTC
The output below comes from a puppet run. I'm trying to install Magento using the setup:install CLI functionality. 

It makes sense that the user running it does not have write rights on that folder shown below (/var/lib/php/session), that's actually also true. 

But, my first impression is: why is the CLI actually using sessions? Besides that on the beginning of the setup:install call, file permissions get checked. If sessions are required, then this might be necessary to add to the file permission checks also. 

In general I have the impression sessions should not be used at all in here..

> ==> local: Installing user configuration...
> ==> local: 
> ==> local: Fatal error: Uncaught ErrorException: SessionHandler::write(): open(/var/lib/php/session/sess_js8j8rlanppssmjpsmtpnc0cr1, O_RDWR) failed: Permission denied (13) in /var/www/webshop/vendor/magento/framework/Session/SaveHandler.php:86
> ==> local: Stack trace:
> ==> local: #0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'SessionHandler:...', '/var/www/websho...', 86, Array)
> ==> local: #1 /var/www/webshop/vendor/magento/framework/Session/SaveHandler.php(86): SessionHandler->write('js8j8rlanppssmj...', '')
> ==> local: #2 [internal function]: Magento\Framework\Session\SaveHandler->write('js8j8rlanppssmj...', '')
> ==> local: #3 {main}
> ==> local:   thrown in /var/www/webshop/vendor/magento/framework/Session/SaveHandler.php on line 86
> ==> local: 
> ==> local: 
> ==> local:  
> ==> local:   [ErrorException]  
> ==> local:   SessionHandler::read(): open(/var/lib/php/session/sess_js8j8rlanppssmjpsmtpnc0cr1, O_RDWR) failed: Permission denied (13)  
> ==> local:  
> ==> local: 
> ==> local: 
> ==> local: Exception trace:
> ==> local:  () at /var/www/webshop/vendor/magento/framework/Session/SaveHandler.php:74
> ==> local:  Composer\Util\ErrorHandler::handle() at n/a:n/a
> ==> local:  SessionHandler->read() at /var/www/webshop/vendor/magento/framework/Session/SaveHandler.php:74
> ==> local:  Magento\Framework\Session\SaveHandler->read() at n/a:n/a
> ==> local:  session_start() at /var/www/webshop/vendor/magento/framework/Session/SessionManager.php:189
> ==> local:  Magento\Framework\Session\SessionManager->start() at /var/www/webshop/vendor/magento/framework/Session/SessionManager.php:130
> ==> local:  Magento\Framework\Session\SessionManager->__construct() at /var/www/webshop/vendor/magento/module-backend/Model/Auth/Session.php:88
> ==> local:  Magento\Backend\Model\Auth\Session->__construct() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:147
> ==> local:  Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:89
> ==> local:  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/webshop/vendor/magento/framework/ObjectManager/ObjectManager.php:71
> ==> local:  Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:236
> ==> local:  Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
> ==> local:  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
> ==> local:  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/webshop/vendor/magento/framework/ObjectManager/ObjectManager.php:71
> ==> local:  Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:236
> ==> local:  Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
> ==> local:  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
> ==> local:  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/webshop/vendor/magento/framework/ObjectManager/ObjectManager.php:71
> ==> local:  Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:236
> ==> local:  Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
> ==> local:  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
> ==> local:  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/webshop/vendor/magento/framework/ObjectManager/ObjectManager.php:57
> ==> local:  Magento\Framework\ObjectManager\ObjectManager->create() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:238
> ==> local:  Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
> ==> local:  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
> ==> local:  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/webshop/vendor/magento/framework/ObjectManager/ObjectManager.php:71
> ==> local:  Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:236
> ==> local:  Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
> ==> local:  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
> ==> local:  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/webshop/vendor/magento/framework/ObjectManager/ObjectManager.php:57
> ==> local:  Magento\Framework\ObjectManager\ObjectManager->create() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:238
> ==> local:  Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
> ==> local:  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
> ==> local:  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/webshop/vendor/magento/framework/ObjectManager/ObjectManager.php:71
> ==> local:  Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:236
> ==> local:  Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
> ==> local:  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
> ==> local:  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/webshop/vendor/magento/framework/ObjectManager/ObjectManager.php:71
> ==> local:  Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:236
> ==> local:  Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
> ==> local:  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/webshop/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
> ==> local:  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/webshop/vendor/magento/framework/ObjectManager/ObjectManager.php:57
> ==> local:  Magento\Framework\ObjectManager\ObjectManager->create() at /var/www/webshop/vendor/magento/module-config/Model/Config/Factory.php:35
> ==> local:  Magento\Config\Model\Config\Factory->create() at /var/www/webshop/setup/src/Magento/Setup/Model/Installer.php:848
> ==> local:  Magento\Setup\Model\Installer->installUserConfig() at n/a:n/a
> ==> local:  call_user_func_array() at /var/www/webshop/setup/src/Magento/Setup/Model/Installer.php:331
> ==> local:  Magento\Setup\Model\Installer->install() at /var/www/webshop/setup/src/Magento/Setup/Console/Command/InstallCommand.php:125
> ==> local:  Magento\Setup\Console\Command\InstallCommand->execute() at /var/www/webshop/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
> ==> local:  Symfony\Component\Console\Command\Command->run() at /var/www/webshop/vendor/symfony/console/Symfony/Component/Console/Application.php:874
> ==> local:  Symfony\Component\Console\Application->doRunCommand() at /var/www/webshop/vendor/symfony/console/Symfony/Component/Console/Application.php:195
> ==> local:  Symfony\Component\Console\Application->doRun() at /var/www/webshop/vendor/magento/framework/Console/Cli.php:49
> ==> local:  Magento\Framework\Console\Cli->doRun() at /var/www/webshop/vendor/symfony/console/Symfony/Component/Console/Application.php:126
> ==> local:  Symfony\Component\Console\Application->run() at /var/www/webshop/bin/magento:25
> ==> local: 
> ==> local: 
> ==> local: setup:install [--backend-frontname="..."] [--key="..."] [--session-save="..."] [--definition-format="..."] [--db-host="..."] [--db-name="..."] [--db-user="..."] [--db-engine="..."] [--db-password="..."] [--db-prefix="..."] [--db-model="..."] [--db-init-statements="..."] [-s|--skip-db-validation] [--http-cache-hosts="..."] [--base-url="..."] [--language="..."] [--timezone="..."] [--currency="..."] [--use-rewrites="..."] [--use-secure="..."] [--base-url-secure="..."] [--use-secure-admin="..."] [--admin-use-security-key="..."] [--admin-user="..."] [--admin-password="..."] [--admin-email="..."] [--admin-firstname="..."] [--admin-lastname="..."] [--cleanup-database] [--sales-order-increment-prefix="..."] [--use-sample-data] [--magento-init-params="..."]
> ==> local: 
> ==> local: 
> ==> local: PHP Fatal error:  Uncaught ErrorException: SessionHandler::write(): open(/var/lib/php/session/sess_js8j8rlanppssmjpsmtpnc0cr1, O_RDWR) failed: Permission denied (13) in /var/www/webshop/vendor/magento/framework/Session/SaveHandler.php:86
> ==> local: Stack trace:
> ==> local: #0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'SessionHandler:...', '/var/www/websho...', 86, Array)
> ==> local: #1 /var/www/webshop/vendor/magento/framework/Session/SaveHandler.php(86): SessionHandler->write('js8j8rlanppssmj...', '')
> ==> local: #2 [internal function]: Magento\Framework\Session\SaveHandler->write('js8j8rlanppssmj...', '')
> ==> local: #3 {main}
> ==> local:   thrown in /var/www/webshop/vendor/magento/framework/Session/SaveHandler.php on line 86

**Comment by mazhalai** [comment] 2016-01-27 22:19
@stefandoorn what version of magento2?

**Comment by stefandoorn** [comment] 2016-01-27 22:24
@mazhalai 2.0.1 CE. Downloaded through the create-project command tutorial. Installing it in an puphpet environment atm.

> $ magento --version
> Magento CLI version 2.0.1

**Comment by mc388** [comment] 2016-01-28 09:03
We have a similar issue.

**Comment by mazhalai** [comment] 2016-03-29 19:02
@stefandoorn sorry for the late reply, the session handler is being invoked not because the CLI is using sessions but since the CLI has an option for where sessions are saved: `--session-save`. See [Install options](http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-install.html)

Closing since this is not a bug.

**Closed as completed by mazhalai** 2016-03-29 19:02 UTC
