### ISSUE TITLE
SecureHtmlRenderer renderTag method renders incorrectly when provided 'null' content

### ISSUE THREAD

**Issue by rmchale258** [magento/magento2#32822] opened 2021-04-22 20:33 UTC
### Preconditions (*)

1. 2.4.* (2.4.1 and 2.4.2 verified)

### Steps to reproduce (*)

1. Attempt to use the `\Magento\Framework\View\Helper\SecureHtmlRenderer::renderTag` method in a template to render an empty script tag with an external script src:
```
eg.
<script type="text/javascript" src="https://some-domain.com/external-lib.js"></script>
```

According to the documentation of that method, the 3rd argument ($content) should be nullable, so you should be able to do the following:

```
<?= /* @noEscape */ $secureRenderer->renderTag('script', ['src' => 'https://some-domain.com/external-lib.js'], null); ?>
```

**Use Case:** To conditionally render a script tag based on some criteria determined in PHP, such as the value of a system config, or the presence of some flag set in layout xml.

### Expected result (*)
1. Tag should render correctly with an empty body and be immediately followed by a closing tag:

```
eg.
<script type="text/javascript" src="https://some-domain.com/external-lib.js"></script>
```

### Actual result (*)
1. Tag does not close, which places all proceeding content _within_ the script tag, until the next closing script tag is encountered:
![Screenshot from 2021-04-22 15-40-44](https://user-images.githubusercontent.com/66812806/115781235-1baaf300-a388-11eb-87be-013ecc0ba9be.png)

---
- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by rmchale258** [comment] 2021-04-22 20:35
@magento give me 2.4-develop instance

**Comment by mrtuvn** [comment] 2021-04-22 21:52
Seem problem already fixed in latest code (2.4-develop)

**Comment by mrtuvn** [comment] 2021-04-22 22:31
renderTag work with purpose include inline script! I don't think it work with external script

For external the better way is include via layout instead

**Comment by rmchale258** [comment] 2021-04-23 14:22
Hey @mrtuvn , I have tried 
```
<?= /* @noEscape */ $secureRenderer->renderTag('script', ['src' => 'https://cdn.jsdelivr.net/gh/alpinejs/alpine@2.8.2/dist/alpine.js'], true); ?>
```

and I get the same result. And including in the head via layout xml wouldn't work in this case because as I said in my ticket description, the use case is:

> To conditionally render a script tag based on some criteria determined in PHP, such as the value of a system config, or the presence of some flag set in layout xml.

The `link` node in layoutxml doesn't support the `if_config` attribute.

And as for whether "core team want this behavior or allow import external script with such purpose", there are tests in the codebase that specifically seem to show it working this way:

```
dev/tests/integration/_files/Magento/TestModuleSecureHtmlRenderer/view/frontend/templates/helper.phtml:10
```

And and if you dig into what happens within `renderTag`, you can see that `\Magento\Csp\Helper\InlineUtil::processTag` is eventually called, and it specifically has functionality to `extractRemoteHosts`:

```
       if (array_key_exists($tagData->getTag(), self::$tagMeta)) {
            /** @var string $policyId */
            $policyId = self::$tagMeta[$tagData->getTag()]['id'];
            $remotes = $this->extractRemoteHosts($tagData->getTag(), $tagData->getAttributes(), $tagData->getContent());
            if (empty($remotes) && !$tagData->getContent()) {
                throw new \InvalidArgumentException('Either remote URL or hashable content is required to whitelist');
            }
... etc etc
```

With all of this in mind it seems quite clear to me that it is _supposed_ to work this way.

**Comment by magento-engcom-team** [comment] 2021-04-24 01:37
@mrtuvn Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-04-24 01:40
:white_check_mark: Confirmed by @mrtuvn 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42044` were created

**Issue Available**: @mrtuvn, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by basvanpoppel** [comment] 2021-06-08 14:33
Hi! I ran into this issue as well. The cause of the issue described is that a script tag without content is being rendered as a self-closing tag.

I had a look at this function
Magento\Framework\View\Helper\SecureHtmlRender\HtmlRenderer::renderTag(TagData $tagData): string

It will look for content in the tag, and if empty it will render the tag with a closing tag like this:
`<script type="text/javascript" src="https://some-domain.com/external-lib.js" />`

According to w3c this is not allowed: 

> A Self-closing tag is a special form of start tag with a slash immediately before the closing right angle bracket. These indicate that the element is to be closed immediately, and has no content. Where this syntax is permitted and used, the end tag must be omitted. In HTML, the use of this syntax is restricted to void elements and foreign elements. If it is used for other elements, it is treated as a start tag. In XHTML, it is possible for any element to use this syntax. But note that it is only conforming for elements with content models that permit them to be empty.

Ref: https://dev.w3.org/html5/html-author/#the-script-element

I guess there are two possible solutions:

1. Prevent this from happening on script tags; i'm not sure if this covers all scenarios.
2. Only allow closing tags for void and foreign elements: would probably have to create a list of elements where closing tags are allowed and add a condition.

If someone from Magento can aid on what's the best approach here, i'm happy to make a PR.

(ps. for now i made a custom patch, replacing `if ($content) {` with `if ($content || $tagData->getTag() === 'script') {` )

**Closed as completed** 2021-07-02 11:16 UTC
Labels: Issue: Confirmed, Component: Framework/View, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P3, Severity: S3, Progress: done, Project: Platform Health
