### ISSUE TITLE
"Layered Navigation Price Step" in Category Form display wrong currency

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#25970] opened 2019-12-10 10:25 UTC
### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Go to backend
2. Set default currency to Euro

![image](https://user-images.githubusercontent.com/8234209/70512701-b378ba00-1b62-11ea-8d5e-d21f168ba422.png)

3. Go to Catalog->Categories
4. Edit one category, scroll to Display Settings 
5. See:

![image](https://user-images.githubusercontent.com/8234209/70513008-5af5ec80-1b63-11ea-9e46-2c6f8e12db4e.png)

### Expected result (*)

1. It must display as Euro

### Actual result (*)

1. Dollar because it is hard-code :

![image](https://user-images.githubusercontent.com/8234209/70513057-73fe9d80-1b63-11ea-8b3e-02a5a272287c.png)

**Comment by ajijshekh123** [comment] 2019-12-10 10:33
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2019-12-10 10:34
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-12-10 10:34
Hi @ajijshekh123, here is your [Magento instance](https://i-25970-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25970-2-4-develop.instances.magento-community.engineering/admin](https://i-25970-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-12-10 10:41
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29611` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Bartlomiejsz** [comment] 2019-12-10 16:14
@magento-engcom-team @ajijshekh123 @edenduong this is duplicate of https://github.com/magento/magento2/issues/21684

**Comment by edenduong** [comment] 2019-12-10 16:31
> @magento-engcom-team @ajijshekh123 @edenduong this is duplicate of #21684

Hi @Bartlomiejsz : I don't know that. Thank you!

**Comment by ajijshekh123** [comment] 2019-12-11 04:36
Thanks for the update @Bartlomiejsz,
@edenduong - Let me close this issue.

Thanks.

**Closed as completed by ajijshekh123** 2019-12-11 04:36 UTC
Labels: Issue: Ready for Work, Component: Catalog, duplicate, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: CurrencySymbol, Component: Admin, Reproduced on 2.4.x
