### ISSUE TITLE
Magento2 ProductsView with meta-messages everywhere

### ISSUE THREAD

**Issue by agusfernandez** [magento/magento2#29384] opened 2020-08-04 16:35 UTC
Hi i need help with this issue, i have no idea why this happened. Can anybody help me with this?

<img width="1923" alt="Captura de Pantalla 2020-08-04 a la(s) 13 19 36" src="https://user-images.githubusercontent.com/49215336/89319983-49fc6d00-d657-11ea-9f07-a50d1ee94667.png">

thanks

**Comment by hostep** [comment] 2020-08-04 20:20
@agusfernandez: it's most likely a duplicate of https://github.com/magento/magento2/issues/18519

Try this to solve it:
1. [disable the inline translations feature](https://docs.magento.com/user-guide/v2.3/system/translate-inline.html#step-2-enable-the-translate-inline-tool) of Magento
2. run `bin/magento setup:static-content:deploy ...` again to redeploy all static assets

That should hopefully solve your issue.

**Comment by krishprakash** [comment] 2020-08-11 04:43
Hi @agusfernandez.  Hope you got the answer and solve your problem as per given by @hostep 
So closing this ticket. Thanks!!

**Closed as completed by krishprakash** 2020-08-11 04:43 UTC
Labels: Issue: Format is not valid, Triage: Dev.Experience
