### ISSUE TITLE
Swatches color image change not working

### ISSUE THREAD

**Issue by weeliem** [magento/magento2#25059] opened 2019-10-15 01:53 UTC
### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Go to product details page with different color different images.
2. Choose color to change image (http://prntscr.com/pjby6l)

### Expected result (*)

1. Image suppose to change base on selected color

### Actual result (*)

1. Selected color image is not changed (http://prntscr.com/pjbyko)

**Comment by krishprakash** [comment] 2019-10-15 06:03
Hi @weeliem. I'm not able to reproduce this issue as steps you described.
Please provide more detail about this and please confirm that issue is reproduce on latest instance as instructed above. https://github.com/magento/magento2/issues/25059#issuecomment-542000542
Thanks.

**Comment by ravi-chandra3197** [comment] 2019-10-23 12:21
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-10-23 12:21
Hi @ravi-chandra3197. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-10-23 12:22
Hi @ravi-chandra3197, here is your [Magento instance](https://i-25059-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25059-2-3-develop.instances.magento-community.engineering/admin](https://i-25059-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-10-25 07:33
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22130` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by raumatbel** [comment] 2019-10-27 12:43
The behavior in version 2.3 is correct. In Magento 2.2 it was wrong and the preview of the main image always changed without doing any kind of check.

**Magento2.2** `Swatches/view/frontend/web/js/swatch-renderer.js`
```
/**
 * Event for swatch options
 *
 * @param {Object} $this
 * @param {Object} $widget
 * @param {String|undefined} eventName
 * @private
 */
_OnClick: function ($this, $widget, eventName) {
    var $parent = $this.parents('.' + $widget.options.classes.attributeClass),
        $wrapper = $this.parents('.' + $widget.options.classes.attributeOptionsWrapper),
        $label = $parent.find('.' + $widget.options.classes.attributeSelectedOptionLabelClass),
        attributeId = $parent.attr('attribute-id'),
        $input = $parent.find('.' + $widget.options.classes.attributeInput);

    if ($widget.inProductList) {
        $input = $widget.productForm.find(
            '.' + $widget.options.classes.attributeInput + '[name="super_attribute[' + attributeId + ']"]'
        );
    }

    if ($this.hasClass('disabled')) {
        return;
    }

    if ($this.hasClass('selected')) {
        $parent.removeAttr('option-selected').find('.selected').removeClass('selected');
        $input.val('');
        $label.text('');
        $this.attr('aria-checked', false);
    } else {
        $parent.attr('option-selected', $this.attr('option-id')).find('.selected').removeClass('selected');
        $label.text($this.attr('option-label'));
        $input.val($this.attr('option-id'));
        $input.attr('data-attr-name', this._getAttributeCodeById(attributeId));
        $this.addClass('selected');
        $widget._toggleCheckedAttributes($this, $wrapper);
    }

    $widget._Rebuild();

    if ($widget.element.parents($widget.options.selectorProduct)
            .find(this.options.selectorProductPrice).is(':data(mage-priceBox)')
    ) {
        $widget._UpdatePrice();
    }

    $widget._loadMedia(eventName);
    $input.trigger('change');
},
```

**Magento 2.3** `Swatches/view/frontend/web/js/swatch-renderer.js`
```
/**
 * Event for swatch options
 *
 * @param {Object} $this
 * @param {Object} $widget
 * @private
 */
_OnClick: function ($this, $widget) {
    var $parent = $this.parents('.' + $widget.options.classes.attributeClass),
        $wrapper = $this.parents('.' + $widget.options.classes.attributeOptionsWrapper),
        $label = $parent.find('.' + $widget.options.classes.attributeSelectedOptionLabelClass),
        attributeId = $parent.attr('attribute-id'),
        $input = $parent.find('.' + $widget.options.classes.attributeInput),
        checkAdditionalData = JSON.parse(this.options.jsonSwatchConfig[attributeId]['additional_data']);

    if ($widget.inProductList) {
        $input = $widget.productForm.find(
            '.' + $widget.options.classes.attributeInput + '[name="super_attribute[' + attributeId + ']"]'
        );
    }

    if ($this.hasClass('disabled')) {
        return;
    }

    if ($this.hasClass('selected')) {
        $parent.removeAttr('option-selected').find('.selected').removeClass('selected');
        $input.val('');
        $label.text('');
        $this.attr('aria-checked', false);
    } else {
        $parent.attr('option-selected', $this.attr('option-id')).find('.selected').removeClass('selected');
        $label.text($this.attr('option-label'));
        $input.val($this.attr('option-id'));
        $input.attr('data-attr-name', this._getAttributeCodeById(attributeId));
        $this.addClass('selected');
        $widget._toggleCheckedAttributes($this, $wrapper);
    }

    $widget._Rebuild();

    if ($widget.element.parents($widget.options.selectorProduct)
            .find(this.options.selectorProductPrice).is(':data(mage-priceBox)')
    ) {
        $widget._UpdatePrice();
    }

    $(document).trigger('updateMsrpPriceBlock',
        [
            _.findKey($widget.options.jsonConfig.index, $widget.options.jsonConfig.defaultValues),
            $widget.options.jsonConfig.optionPrices
        ]);

    if (parseInt(checkAdditionalData['update_product_preview_image'], 10) === 1) {
        $widget._loadMedia();
    }

    $input.trigger('change');
},
```
You can notice the call. 
**$widget._loadMedia();**

In Magento 2.3 to make the image reload it makes the check according to the setting that you have in the configuration of the attribute.

<img width="767" alt="Update Image Swatch" src="https://user-images.githubusercontent.com/5289240/67634698-adcf5980-f8bf-11e9-890c-6a9a52dbc897.png">

Close this ticket.

**Closed as completed by raumatbel** 2019-10-27 12:43 UTC
Labels: Issue: Ready for Work, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: ConfigurableProduct, Component: Swatches, Component: Image

**Comment by irving0mar** [comment] 2020-02-11 00:16
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-11 00:16
Hi @irving0mar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by kristssw** [comment] 2025-08-28 18:33
Hello,
I recently added a test project with Magento 2 version 2.3.3
It seems that for me helped that I:
- for **Color** attribute set **Update Product Preview Image** to no
- run `bin/magento indexer:reindex && bin/magento c:f`
- for **Color** attribute set **Update Product Preview Image** to yes
- run `bin/magento indexer:reindex && bin/magento c:f`

<img width="801" height="126" alt="Image" src="https://github.com/user-attachments/assets/a4ebfef4-c4da-4b44-8f90-65c6d9461b2f" />

<img width="1800" height="829" alt="Image" src="https://github.com/user-attachments/assets/442d6ad1-a2e7-4d17-9a31-9c85013f8729" />
