### ISSUE TITLE
Admin Configuration values set in config files displayed incorrectly in Admin

### ISSUE THREAD

**Issue by UglyWillDuckling** [magento/magento2#36009] opened 2022-08-24 09:41 UTC
### Preconditions and environment

 - Magento 2 2.4.4

### Steps to reproduce

1. set a value in `config.php`
2. update the same config value via the **command line**
3. Check the values in **Admin**
4. The value from the configuration file should be displayed
5. check the values again using the **CLI** command `config:show`, the value from the **database** is shown

### Expected result

The values shown in **Admin** match the ones from the **CLI**.

### Actual result

The values set do not match and an incorrect value is shown in Admin. By incorrect, we mean that the value shown is not the actual value that the system uses when running.

### Additional information

The configurations tested were all set on the base Magento store level. No specific website or store configurations were being used.
This also affects values from **env.php**

This was also tested with the `app:config:import` command, but it didn't change anything.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Aquive** [comment] 2022-08-24 11:16
Hi @UglyWillDuckling did you try `bin/magento app:config:import` between steps 2 and 3? I am not sure if this is necessary actually, but maybe worth to try?

**Comment by UglyWillDuckling** [comment] 2022-08-24 11:19
Hi @Aquive, yes that was tried as well. I forgot to mention it in the description.

**Comment by engcom-November** [comment] 2022-08-24 11:36
Hi @UglyWillDuckling ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not reproduce the issue using both config.php and cli.
Steps performed:
1. Updated below value in config.php and saved
2. Ran php bin/magento app:config:import
3. Verified admin - No issue - Values updated as expected.
4. Updated the same value from cli using command: 
> bin/magento config:set customer/create_account/email_domain 'example.com' --lock-env and run config:import command
6. Ran php bin/magento config:show
No issue: values displayed as expected in admin and cli config:show command
Kindly recheck the issue on Magento 2.4-develop branch as it is the upcoming 2.4.x release and have latest code base and provide missing steps if any if the issue is still reproducible.
![image](https://user-images.githubusercontent.com/60198231/186408592-4d45a7b8-24e2-49af-953a-4d478ab53051.png)
![image](https://user-images.githubusercontent.com/60198231/186408631-e5692651-d241-4206-881e-2b7852f9c2d6.png)
![image](https://user-images.githubusercontent.com/60198231/186408675-c97e9dbc-f068-4594-a7cd-f581fb899c62.png)

**Comment by UglyWillDuckling** [comment] 2022-08-26 14:38
Hi @Aquive,

I will investigate this a bit further. It might be that it only affects previously stored configurations.

**Comment by engcom-November** [comment] 2022-09-20 03:21
Hi @UglyWillDuckling ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed** 2022-09-20 03:21 UTC
Labels: Issue: needs update
