### ISSUE TITLE
2.4.5-p1 checkout was empty because block position was null

### ISSUE THREAD

**Issue by MrBlueEyez** [magento/magento2#36293] opened 2022-10-13 14:09 UTC
### Preconditions and environment

- Magento version 2.4.5-p1

### Steps to reproduce

1. add a product to the shopping cart
2. go to the shopping cart
3. open the checkout

### Expected result

A working checkout

### Actual result

The whole checkout isnt rendered because the error:
```
collection.js:85 Uncaught TypeError: Cannot read properties of null (reading 'after')
    at _insertAt (collection.js:85:31)
    at collection.js:172:21
    at Array.map (<anonymous>)
    at UiClass.insertChild (collection.js:169:19)
    at layout.js:439:27
    at Registry._resolveRequest (registry.js:416:30)
    at Array.forEach (<anonymous>)
    at Registry._updateRequests (registry.js:398:18)
    at later (underscore.js:1153:47)
```

This is caused because in the `vendor/magento/module-ui/view/base/web/js/lib/core/collection.js` file on line number 68 the following check can be found:
`if (typeof position === 'undefined') {`

However it is possible for the position to be null as well, in that case also `-1` should be used.

### Additional information

We also see this not occuring on other stores, but cannot really seem to find the reason why it is occuring.
It happens for blocks that are added by Magento default.

By adding a simple `position === null` check the issue is gone and the pages are loading like they should.

### Triage and priority

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-10-14 09:16
@magento give me 2.4.4 instance

**Comment by engcom-Bravo** [comment] 2022-10-14 09:31
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-10-14 12:56
Hi @MrBlueEyez,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop and 2.4.5 instances and the issue is not reproducible on both the instances.Kindly refer the screenshots.

Steps to reproduce
1.add a product to the shopping cart
2.go to the shopping cart
3.open the checkout


Checkout is Working fine.


<img width="1428" alt="Screenshot 2022-10-14 at 5 53 56 PM" src="https://user-images.githubusercontent.com/51680745/195852030-b458231d-d0af-4f53-a79c-8c8ba2a7cf90.png">



Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.



Thanks.

**Comment by engcom-Bravo** [comment] 2022-10-28 06:59
Hi @MrBlueEyez,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-10-28 06:59 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.x
