### ISSUE TITLE
All related products deleted if you delete a custom attribute set.

### ISSUE THREAD

**Issue by twvictor** [magento/magento2#36708] opened 2023-01-06 10:43 UTC
### Preconditions and environment

- Magento ver. 2.4.5-p1
I just removed a custom attribute set, but all my products using the attribute set removed too, I have to roll back my production online store, but still some data missed. 

### Steps to reproduce

1. Navigate the Stores > Attributes > Attribute Set
2. Add a custom attribute set
3. Add some products using the custom attribute set
4. Delete the custom attribute set

### Expected result

It is not allowed to delete the attribute set if there are products using it.

### Actual result

The custom attribute removed, and all related products deleted.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2023-01-09 04:15
Verified the issue on Magento 2.4-develop instance and the issue is reproducible. Hence confirming the issue.
User is able to delete the custom attribute set and all the related products are removed.

**Comment by shomiadarshlt** [comment] 2023-01-10 06:07
https://github.com/magento I am working on this

**Comment by shomiadarshlt** [comment] 2023-01-10 06:10
@magento I am working on this

**Comment by shomiadarshlt** [comment] 2023-01-10 06:10
@magento add to contributors team

**Comment by shomiadarshlt** [comment] 2023-01-10 06:12
@magento I am working on this

**Comment by shomiadarshlt** [comment] 2023-01-10 06:19
@engcom-November There are few queries related to the issue .

1. If we delete any custom attribute set, then products, those configured with the custom attribute set should not delete and should those products be assigned to a default attribute set or we should not permit the deletion itself.
2. The error message if we try to delete such attributes having products "Attribute set can't be deleted, please remove attribute set configuration from related products to delete".

**Comment by engcom-November** [comment] 2023-02-24 10:24
Hi @twvictor ,
We re-verified the issue again on Magento 2.4-develop instance and after internal discussion it has been decided that this is an expected behavior but not a bug.
While deleting the custom attribute set, below popup about products deletion is displayed to the user.
![image](https://user-images.githubusercontent.com/60198231/221154932-ab9a2b42-3a14-486e-9429-5f36d655ffb1.png)
Kindly recheck the issue on Magento 2.4-develop instance and provide your inputs on this.
Thank you.

**Comment by twvictor** [comment] 2023-02-24 10:38
@engcom-November 
That is ok if a popup displayed, but It doesn't seem like a very logical decision, users have to be very careful at this point.

**Comment by engcom-November** [comment] 2023-03-03 04:28
Hi @twvictor ,
Thank you for the response. This is the current existing behavior of Magento as the popup displayed and not breaking any functionality. Hence closing this issue as not a bug. Kindly reopen / create new issue if you are facing any issues.
Thank you.

**Closed as completed by engcom-November** 2023-03-03 04:28 UTC
Labels: Reproduced on 2.4.x, Priority: P1, Progress: done, Component: Attributes, Issue: needs update, Area: Admin UI, Reported on 2.4.5-p1
