### ISSUE TITLE
Bulk product attribute not updated in magento 2.3.2

### ISSUE THREAD

**Issue by santosh-ks153** [magento/magento2#26687] opened 2020-02-04 07:57 UTC
### Preconditions (*)

1. PHP 7.2.27
2. MySql 5.6.40

### Steps to reproduce (*)

1. Go to Admin -> Catalog -> Product
2. Select multiple products from product grid
3. Choose Update Attributes from Action drop-down
4. Change any attribute  and Save 

### Expected result (*)

1. Product attribute should be updated.

### Actual result (*)

1. Product attribute not updated
![image](https://user-images.githubusercontent.com/50358141/73734584-ddfe8200-4763-11ea-8687-64f9fcf0c568.png)

**Comment by sudheers-kensium** [comment] 2020-02-04 08:03
@santosh-ks153 Can you please update more details.

**Comment by santosh-ks153** [comment] 2020-02-04 08:07
when I m trying to update the product attribute using Magento backend. got the below message always.
![screenshot-dev](https://user-images.githubusercontent.com/55832852/73725469-6fb1c380-4753-11ea-8064-c3bbb1acaf6f.png)

**Comment by santosh-ks153** [comment] 2020-02-04 08:08
Look like it will never updates the product attribute.

**Comment by santosh-ks153** [comment] 2020-02-04 08:55
Any solution for that @sudheers-kensium

**Comment by sudheers-kensium** [comment] 2020-02-04 09:47
@santosh-ks153 You need to enable the magento cron

**Comment by santosh-ks153** [comment] 2020-02-04 09:54
i did

**Comment by magento-engcom-team** [comment] 2020-02-04 09:58
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31078` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by darshankhatri16** [comment] 2020-02-04 12:39
Hi @santosh-ks153 
You need to enable start queue consumer "product_action_attribute.update". You can list out all the consumers via below command:
`php bin/magento queue:consumers:list`

Please find below screenshot
![Screenshot from 2020-02-04 18-05-19](https://user-images.githubusercontent.com/22095982/73745543-4572fc80-4779-11ea-92c2-0c7e81210333.png)

You can start consumer by below command:
`php bin/magento queue:consumers:start product_action_attribute.update`

Let me know if you need any further details.

**Comment by santosh-ks153** [comment] 2020-02-04 13:11
after doing the above I got the below response.
![Screenshot from 2020-02-04 18-37-54](https://user-images.githubusercontent.com/55832852/73747674-f380a580-477d-11ea-895a-45020f51ebc0.png)

**Comment by darshankhatri16** [comment] 2020-02-04 13:17
Could you please try below command with area-code
`php bin/magento queue:consumers:start product_action_attribute.update  --area-code='adminhtml'`

**Comment by santosh-ks153** [comment] 2020-02-04 13:31
Getting the same issue.
![Screenshot from 2020-02-04 19-00-07](https://user-images.githubusercontent.com/55832852/73749098-b36ef200-4780-11ea-8e1e-7a6a581f292f.png)

**Comment by darshankhatri16** [comment] 2020-02-05 05:04
@santosh-ks153 
I did some research on this issue and found that you have installed some custom module and in that custom module, you will find a code where area code has been set. Could you please verify in your custom module?
This is usually due to some other bit of code setting the areaCode before the core is trying to set it. Usually, because it is trying to be set in __construct() somewhere. With how dependency injection works, all objects are loaded and their constructors are run, even if you're not using that object. I would check that the areaCode is not being set in a __construct()

**Comment by SewHappy58** [comment] 2020-05-28 21:57
I'm having the same issue on Magento 2.3.5-p1.  It's a clean install but I imported products

**Comment by GalichMolodothon** [comment] 2020-06-15 14:03
Could somebody clarify
I run bin/magento queue:consumers:start product_action_attribute.update and it started working.
We should run and configure it like cron? I could found information about it and that is so important.

**Comment by hostep** [comment] 2020-06-15 20:22
@GalichMolodothon: the default Magento cron has a job called `consumers_runner` which should already spawn these consumer processes, so normally you only need to call `bin/magento cron:run`.

But that can change depending on your configuration of those consumers. See [the documentation](https://devdocs.magento.com/guides/v2.4/config-guide/mq/manage-message-queues.html#configuration) for this, the default configuration shouldn't block consumers, but maybe somehow the configuration got changed in your particular case?

**Comment by sdzhepa** [comment] 2020-07-15 22:03
Hello @santosh-ks153 
cc: @GalichMolodothon @SewHappy58 @hostep 

Based on the issue description and discussion in comments
It seems not a bug but a configuration issue.
also in comments, there are recommendations, guides and links to the official documentation.

Please confirm that we close this Issue or update information in the issue description

**Comment by GalichMolodothon** [comment] 2020-07-16 07:41
@sdzhepa hello!
Yes, it was a misunderstanding for setting the correct format in the cloud configuration for consumers and setting an array of consumers.

**Closed as completed** 2020-08-04 20:41 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Confirmed, Issue:  Cannot Reproduce, non-issue, Issue: Format is valid, Component: Admin, Reproduced on 2.4.x, Reported on 2.3.2
