### ISSUE TITLE
checkout with Braintree payment with 3d secure give error "Please try again with another form of payment."

### ISSUE THREAD

**Issue by ravi-chandra3197** [magento/magento2#23844] opened 2019-07-24 06:00 UTC
### Preconditions (*)

1. Magento 2.3.X
2. configure Braintree payment with 3d secure for Production Environment

### Steps to reproduce (*)

1. Add to cart any product
2. Go to checkout 
3. select shipping method
4. select Credit Card (Braintree) as the payment method 
5. fill details and click Place Order

### Expected result (*)

1. order placed successfully

### Actual result (*)

1. give the error "Please try again with another form of payment".

**Comment by ajijshekh123** [comment] 2019-07-24 06:52
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-24 06:52
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-24 06:53
Hi @ajijshekh123, here is your [Magento instance](https://i-23844-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23844-2-3-develop.instances.magento-community.engineering/admin](https://i-23844-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment] 2019-07-24 09:31
Hi, @ravi-chandra3197 ! I can't reproduce this issue on vanilla 2.3-develop. So i close it.
Thank you for contributing! 
GIF(my test):
![mytest1](https://user-images.githubusercontent.com/51680850/61783033-c9821a00-ae0f-11e9-8b0b-ab13cffbf441.gif)

**Closed as completed by engcom-Charlie** 2019-07-24 09:31 UTC
Labels: Area: Frontend, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Braintree

**Comment by ravi-chandra3197** [comment] 2019-07-24 10:11
> Hi, @ravi-chandra3197 ! I can't reproduce this issue on vanilla 2.3-develop. So i close it.
> Thank you for contributing!
> GIF(my test):
> ![mytest1](https://user-images.githubusercontent.com/51680850/61783033-c9821a00-ae0f-11e9-8b0b-ab13cffbf441.gif)

Hello @engcom-Charlie 
have you tried with Braintree payment with 3d secure for Production Environment?
I think you show in the GIF, its sandbox environment.
we have an issue with Production Environment with 3d secure.

**Comment by kitrak17** [comment] 2020-09-07 10:13
This issue is still happening when we enable 3DS in production mode and it is working fine on sandbox mode for Braintree.

**Comment by sreenathnr-tm** [comment] 2020-09-22 06:20
@engcom-Charlie This issue is still happening when we enable 3DS in production mode and it is working fine on sandbox mode for Braintree.
