### ISSUE TITLE
Getting Database CPU usages high (100%) suddenlly

### ISSUE THREAD

**Issue by hemendrametawolf** [magento/magento2#38323] opened 2023-12-27 12:36 UTC
### Preconditions and environment

- Magento 2.4.4-p1
- suddenly magento using high cpu usages and it will down the website and not working properly.
- db server is percona and 248 GB RAM and magento server 125 GB RAM

### Steps to reproduce

1. going to website 
2. checking website and it going slow
3. checking servers and found database server using high cpu usages

### Expected result

website work without any issue and db server use low CPU usages

### Actual result

website down and high cpu usages

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-01-03 11:01
Hi @hemendrametawolf,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly recheck the issue in Latest magento 2.4-develop instance and also check any third party modules causing the issue.


Could you please refer this link https://www.percona.com/blog/a-simple-approach-to-troubleshooting-high-cpu-in-mysql/ for High CPU usage.

Thanks,

**Comment by hemendrametawolf** [comment] 2024-01-03 11:12
Thanks for the updates venkata.

I checked using show PROCESSLIST on the database , there are multiple distinct query related to indexer. 
may i know why it happening and how i can fix this issue.
here are the screeshot of show PROCESSLIST.
![image](https://github.com/magento/magento2/assets/114897672/737a9fad-e99b-4575-82aa-677d32181b49)

**Comment by engcom-November** [comment] 2024-01-04 11:50
Hello @hemendrametawolf,

Thank you for the quick response!

This might have caused from a third party module.
Please try disabling custom modules to see if the problem persists, this will help in narrowing down the source of the problem.

Thank you.

**Comment by engcom-November** [comment] 2024-01-18 13:02
Hello @hemendrametawolf,

We noticed this issue has not been updated for a long time, We assume that this issue is fixed now, hence closing the issue.
Feel free to reopen or raise a new issue if you need more assistence.

Thank you.

**Closed as completed by engcom-November** 2024-01-18 13:02 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.4-p1
