### ISSUE TITLE
Update backup error PDOException

### ISSUE THREAD

**Issue by luc-anise** [magento/magento2#3983] opened 2016-04-02 21:25 UTC
I'm trying to update to the latest version of magento CE and when I get past the readiness check and to the backup stage this comes up. I have no idea what it means but I'd very much like to update ASAP.

Thanks!

`Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory' in /home/shopstudioanise/public_html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php:129 Stack trace: #0 /home/shopstudioanise/public_html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(129): PDO->__construct('mysql:host=loca...', 'shopstud_magent...', '8f^J;M3u[l!W', Array) #1 /home/shopstudioanise/public_html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Mysql.php(111): Zend_Db_Adapter_Pdo_Abstract->_connect() #2 /home/shopstudioanise/public_html/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(332): Zend_Db_Adapter_Pdo_Mysql->_connect() #3 /home/shopstudioanise/public_html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(861): Magento\Framework\DB\Adapter\Pdo\Mysql->_connect() #4 /home/shopstudioanise/public_html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(931): Zend_Db_Adapter_Abstract->quote('1', NULL) #5 /ho in /home/shopstudioanise/public_html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php on line 144`

**Comment by ktomk** [comment] 2016-04-03 12:07
This is related to your database configuration, the Mysql error is (as you report):

> SQLSTATE[HY000] [2002] No such file or directory  (**PDOException** message)

2002 signals a connection issue from your database client to your database server. This normally signals a configuration issue on the system you're running the Magento2 software on. The good news is you're not the first one who is getting it and it's not specifically related to Magento at all. So a tremendous amount of information about the topic already exist which you only need to gather from the (better) sources.

Please consult your DBA/sysadmin for further guidance or consult community resources like the Mysql documentation or Stackoverflow:
- [Appendix B Errors, Error Codes, and Common Problems (MySQL 5.6 Reference Manual  )](http://dev.mysql.com/doc/refman/5.6/en/error-handling.html)
- [PHP - MySQL connection not working: 2002 No such file or directory (Nov 2009)](http://stackoverflow.com/questions/1676688/php-mysql-connection-not-working-2002-no-such-file-or-directory)

Depending on how you've configured your system, the concrete reason can be different and so must be the solution. However it's not needlessly true the other way round, so take care you've got your requirements ordered so that you can configure along them.

Take note that Magento2 internally uses [PDO with the one or other mysql driver](https://dev.mysql.com/doc/apis-php/en/apis-php-mysqlnd.html), so take care you're editing the correct configuration settings.

**Comment by mazhalai** [comment] 2016-04-04 14:03
Thanks @ktomk. @z6tanker We are closing this issue, since it not a bug. Please feel free to open a new issue, if you continue to have problems.

**Closed as completed by mazhalai** 2016-04-04 14:03 UTC
