### ISSUE TITLE
Latest Google Chrome Browser issue with duplicate id #billing-new-address-form:

### ISSUE THREAD

**Issue by lano-vargas** [magento/magento2#14126] opened 2018-03-15 20:41 UTC
Magento 2.2.2 Latest Google Chrome Version { Version 63.0.3239.84 (Official Build) (64-bit) } detects duplicate ids and console.log an ERROR

Add a product to cart and go to checkout process at  /checkout/#payment  inspect element that gives the error: attached screenshot.

![screen shot 2018-03-15 at 20 33 28](https://user-images.githubusercontent.com/3495481/37489907-08cc2d32-2891-11e8-926a-e42dfe664858.png)

Similar issue I reported ref:https://github.com/magento/magento2/issues/12712

Thanks.

**Comment by paragpadsumbiya** [comment] 2018-03-16 06:38
@lano-vargas  thank you for your report.
Please use the issue reporting guidelines to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:

Preconditions: Magento version
Steps to reproduce
Expected result
Actual result

Can you please provide detialed information so we can check this .

**Comment by ishakhsuvarov** [comment] 2018-03-16 08:28
@lano-vargas Thank you for reporting.
This report partly duplicates #13415

I am closing this issue now. Please continue tracking under given reference.

**Closed as completed by ishakhsuvarov** 2018-03-16 08:28 UTC
Labels: duplicate, Issue: Format is not valid

**Comment by magento-engcom-team** [comment] 2018-03-16 09:30
@lano-vargas, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by lano-vargas** [comment] 2018-03-16 09:46
@ishakhsuvarov  I shall track duplicate issue #13415 thanks.

**Comment by simonmaass** [comment] 2018-03-17 11:56
i have the same issue with 2.2.3
