### ISSUE TITLE
Add to cart (configurable)

### ISSUE THREAD

**Issue by bernd-reindl** [magento/magento2#26370] opened 2020-01-13 12:24 UTC
### Preconditions (*)
1. Magento 2.3.3

### Steps to reproduce (*)
1. Set product attribute color to "Used in Product Listing: Yes"
2. Add an simple product
3. Add a configurable product with only color as option
4. Add some configurations to the configurable product
5. Add the configurable product as crossselling product to the simple product
6. Add the simple product to cart in frontend
7. Goto cart
8. Try to add the crossselling product (configurable) to add with the "Add to Cart" button

### Expected result (*)
1. The product detail page should be shown, because the product is a configurable product and needs a color to be choosen.

### Actual result (*)

1. A 404 (Page not found) Exception is thrown because magento tries to add the product to the cart

Screenshots
![to-cart](https://user-images.githubusercontent.com/2369089/72255505-3334f100-3607-11ea-8f0e-9eb733efd044.jpg)

Reason:
In Magento\Catalog\Block\Product\AbstractProduct->getAddToCartUrl() the call $product->getTypeInstance()->isPossibleBuyFromList($product) for type configurable returns true if only attributes with flag "Used in Product Listing" are set as options.

**Comment by bernd-reindl** [comment] 2020-01-13 12:24
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-01-13 12:24
Hi @bernd-reindl. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-13 12:25
Hi @bernd-reindl, here is your [Magento instance](https://i-26370-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26370-2-4-develop.instances.magento-community.engineering/admin](https://i-26370-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by bernd-reindl** [comment] 2020-01-13 12:39
How can i add the label Reproduced on 2.4.x?

**Comment by magento-engcom-team** [comment] 2020-01-13 12:53
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30376` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment] 2020-05-20 14:47
hello @bernd-reindl  and @shikhamis11 

Unfortunately, I am not able to reproduce this issue on the lates `2.4-develop` code.
Probably it was already fixed or some steps/preconditions are missed in the description

Could you please confirm that we can close it as fixed on `2.4-developer` or provide additional details/missed steps?

![issue_23670](https://user-images.githubusercontent.com/3409584/82460482-d3e86100-9a7e-11ea-9819-df0e96744b92.gif)

**Comment by bernd-reindl** [comment] 2020-05-22 10:02
I can confirm.

Also solved in 2.3.5-p1

**Comment by sdzhepa** [comment] 2020-05-27 14:29
Thank you for confirmation @bernd-reindl 
@fyi @shikhamis11 

Seems it was already fixed in some other internal or external PRs
Close this issue and related PR https://github.com/magento/magento2/pull/26562

**Closed as completed by sdzhepa** 2020-05-27 14:29 UTC
Labels: Issue: Ready for Work, Component: Checkout, Issue: Confirmed, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Quote, Reproduced on 2.4.x, Reported on 2.3.3
