### ISSUE TITLE
Cart Price Rule: dates range is filled unexpectedly 

### ISSUE THREAD

**Issue by alexkuk** [magento/magento2#6762] opened 2016-09-27 09:18 UTC
### Preconditions
1. Magento CE 2.1.1 with sample data
### Steps to reproduce
1. Go to backend
2. Marketing -> Promotions -> Cart Price Rules
3. Click Add New Rule.
4. Fill up the form, leave "From" and "To" dates empty
5. Click Save button
### Expected result
1. The rule is created without date range restriction
### Actual result
1. The rule is created with "From" and "To" dates filled by today's date.

I expect it to work the same way as it worked in M1. If putting no date restriction is not possible by design anymore, then I'd prefer "From" and "To" date fields prefilled with current date when filling up a new rule form.

**Comment by tkacheva** [comment] 2016-09-27 15:05
@alexkuk  thanks for reporting the issue. Internal number MAGETWO-59047. Once it's fixed we'll update the issue

**Comment by heldchen** [comment] 2016-09-27 16:19
@alexkuk there's an interim patch in the referenced issue #6122

**Comment by pboisvert** [comment] 2016-09-27 16:28
closing this as duplicate of #6122 

issue being tracked internally in MAGETWO-59047

**Closed as completed by pboisvert** 2016-09-27 16:28 UTC
Labels: Issue: Ready for Work, bug report, Component: Sales, Issue: Format is valid

**Comment by dev-team-1** [comment] 2017-11-20 10:21
Cart price expiration date & other cart price inputs (RSS feed): we recently went from 2.1.5 to 2.1.10.
It was already possible in the past to enter an expiration date, now it is not possible anymore.
![image](https://user-images.githubusercontent.com/33829092/33013467-778760b4-cde4-11e7-900d-1f66ae5fe7a6.png)
The first 2 were created early November and are working fine. The last one was modified today. 
I can enter an expiration date for 2018, but then a start date of today is not accepted. Also the RSS-Feed cannot be switched off.

**Comment by matthiaskoerner-ba** [comment] 2018-03-26 15:45
This issue is still open in 2.1.12
