### ISSUE TITLE
Declined Braintree 3DS enabled transactions result in stuck loader icon

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#26946] opened 2020-02-20 13:58 UTC
### Preconditions (*)
1. 2.4-develop

### Steps to reproduce (*)
```
Console
=======
deploy 2.4-develop from git

Backend
=======
Catalog -> Products
    Add Product
        Name = Test
        Price = 2000 <- causes declined transaction
        Quantity = 100
        New Category
            Category Name = tc
            Parent Category = Default Category
            Create Category
        Save & Close
Store -> Configuration
	Sales -> Payment Methods
		Merchant Country = United Kingdom
		Braintree -> Configure
			Payment Action = Authorize and Capture
			Merchant ID = xxxx
			Public Key = xxxx
			Private Key = xxxx
			Enable this solution = Yes
			3DSecure Verification = Yes
			Debug = Yes
	Save Config
Clear Cache

Frontend
========
View Test Product
Add to Cart
Proceed to checkout
	Enter email address
	Enter address details
	Choose Fixed flat rate shipping
Click Next
	Credit Card (Braintree)
		4111111111111111
		01/21
		123
	Place Order
	Enter 1234 + Submit on 3DS screen
```
### Expected result (*)
1. Transaction is declined and able to retry using different details

### Actual result (*)
1. Checkout is stuck on loader

**Comment by gwharton** [comment] 2020-02-22 12:13
Looks great. PR fixes issue for me. :)

**Comment by magento-engcom-team** [comment] 2020-03-11 13:10
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32352` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment] 2020-08-17 20:44
Hello @gwharton 

Thank you for your report and collaboration!

Unfortunately, we are closing this Issue report because starting from `2.4.0` release, code related to this payment was removed for Magento code-base:
[Magento Commerce 2.4.0 Release Notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-commerce.html)
> With this release, the Authorize.Net, Braintree, eWay, CyberSource, and Worldpay payment method integrations have been removed from core code. Merchants should migrate to the official extensions that are available on the Magento Marketplace.

[Deprecation of Magento core payment integrations](https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445)

All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page

**Closed as completed by sdzhepa** 2020-08-17 20:44 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Braintree, Reproduced on 2.4.x, Reported on 2.4.0
