### ISSUE TITLE
Technical error on saving product

### ISSUE THREAD

**Issue by merlin-18** [magento/magento2#27530] opened 2020-04-01 13:15 UTC
Summary of the issue
"Invalid form key" error on saving one configurable product all other products are getting saved

Information on environment
I'm using Magento 2.2.6

Steps to reproduce
It is not reproducible as it is a particular products issue

Expected result
Product should get saved

Actual result
It's showing "Invalid form key"

I have a multi store website. I'm currently changing products to my German store. And now one of the configurable product is showing "Invalid Form key" on saving the product. Not even a space is getting saved on it. 
I checked that product in local. In local i had only it's default store view(Main website). And that was getting saved without an error. So i tried to add that product to German store in my local. It didn't get saved on that. Even the fact is, after that try, not even the product in default view is getting saved. It's showing "A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later." in my local.
I don't have much experience in magento.

**Comment by sudheers-kensium** [comment] 2020-04-02 13:01
Hi @merlin-18 Thank you for your report.
Can not able to reproduce the issue on latest instance
It should be fixed fixed in updated version
Feel free to reopen the issue if you confirm that issue is reproduced on latest 2.3.4 version

**Closed as completed** 2020-04-02 13:01 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is not valid, Reported on 2.2.x
