### ISSUE TITLE
Somthing Went Wrong - when opening All customers tab - constant timer with no access

### ISSUE THREAD

**Issue by Wettons** [magento/magento2#10851] opened 2017-09-12 09:21 UTC
I clicked on new customers and it came up with something went wrong

### Preconditions
I had just deleted an old client
I am using Magento 

1. Just click on "All Clients" and error appears 

### Expected Result
I would have expected to see my list of clients.

**Comment by korostii** [comment] 2017-09-12 18:13
The issues which cannot be consistently reproduced on a clean installation of Magento 2 CE aren't likely to get resolved in here.

Thus if you are, in fact, reporting a technical issue, please try add as much information as possible, including the environment you use, 3rd party themes and modules installed (if any), preconditions, exact steps to follow, screenshots and stack trace from browser console and even the custom code you're using. These raise the chances of the bug getting reproduced and acknowledged. 
If you don't provide enough information, it is likely that the issue will receive a "needs update" label and will get closed in a couple weeks.

**Comment by magento-engcom-team** [comment] 2017-09-21 12:19
@Wettons thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
- [ ] Preconditions: Magento version
- [ ] Steps to reproduce
- [ ] Expected result
- [ ] Actual result

**Comment by magento-engcom-team** [comment] 2017-10-05 18:20
@Wettons we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Closed as completed by magento-engcom-team** 2017-10-05 18:20 UTC
Labels: Progress: needs update, Issue: Format is not valid
