### ISSUE TITLE
Product will not export if product has image label names but no images

### ISSUE THREAD

**Issue by git-seb** [magento/magento2#36749] opened 2023-01-16 17:14 UTC
### Preconditions and environment

- Magento version 2.4.5-p1
- Flat Catalog Product
- Error in log: main.CRITICAL: Exception: Warning: Undefined array key "base_image" in /vendor/magento/module-catalog-import-export/Model/Export/Product.php on line 1404 in /vendor/magento/framework/App/ErrorHandler.php:62
- I can see the product trying to export has image label names in the database (image_label, small_image_label, thumbnail_label) but no product images (image, small_image, thumbnail) resulting in the upper error when exporting. How those products have label names, is probably due to a product import, but should still not result in issues for exporting them.

### Steps to reproduce

1. Open System > Data Transfer > Export
2. Choose Products
3. Filter on SKU with image label names but no images

### Expected result

Export successfully without issues

### Actual result

Export fails or incomplete (leaves out products with having both cases: image label names + without images)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-01-17 11:57
Hi @git-seb,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible. Kindly refer the screenhsots.


**Steps to reproduce**

1.Open System > Data Transfer > Export
2.Choose Products
3.Filter on SKU with image label names but no images


We are able to the export the product details successfully.


<img width="1449" alt="Screenshot 2023-01-17 at 5 25 36 PM" src="https://user-images.githubusercontent.com/51680745/212892885-02f212ad-5644-4d44-808a-0aceae8a5ccb.png">



Below is the CSV file we have exported successfully.

[export_catalog_product_20230117_152406.csv](https://github.com/magento/magento2/files/10434736/export_catalog_product_20230117_152406.csv)


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-01-18 12:22
Hi @git-seb,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


We have exported the product without image and we have exported product details successfully.when we have image for product for that product only we have image labels.Without image for a product we are not able to set the images labels for a product.


<img width="1512" alt="Screenshot 2023-01-18 at 4 30 27 PM" src="https://user-images.githubusercontent.com/51680745/213169286-e32a0b12-c168-4e37-84cb-1ffe3d0a601f.png">

In logs we are not getting any error.

<img width="1507" alt="Screenshot 2023-01-18 at 4 29 17 PM" src="https://user-images.githubusercontent.com/51680745/213169339-b418415d-fd3d-4fe1-ace0-ccb9173f6582.png">


<img width="1478" alt="Screenshot 2023-01-18 at 4 29 45 PM" src="https://user-images.githubusercontent.com/51680745/213169451-af66a37d-0966-4121-b459-7da6e2f3bab5.png">

We have exported below CSV file

[export_catalog_product_20230118_162653.csv](https://github.com/magento/magento2/files/10446111/export_catalog_product_20230118_162653.csv)


As per Magento docs Magento no longer recommends the use of a flat catalog as a best practice.
https://experienceleague.adobe.com/docs/commerce-admin/catalog/catalog/catalog-flat.html   Kindly check this document.




Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.



Thanks.

**Comment by git-seb** [comment] 2023-01-18 21:38
Hi @engcom-Bravo, I have found a workaround for myself. So if nobody else having this issue you can close this. My work around was just removing the label names (image_label, small_image_label, thumbnail_label) manually from catalog_product_entity_varchar in database for products who do not have any images. That fixed the export for me.

**Comment by engcom-Bravo** [comment] 2023-01-19 08:55
Hi @git-seb,

Thanks for your update.

Hence we are closing this issue as per latest comment https://github.com/magento/magento2/issues/36749#issuecomment-1396121443.


Thanks.

**Closed as completed by engcom-Bravo** 2023-01-19 08:55 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1

**Comment by claudioxu** [comment] 2023-12-20 08:29
Hello, I got the same problem, do we have to remove the alt text?

**Comment by laucat** [comment] 2024-10-25 21:42
Sorry to resurrect this thread. But I just want to thank @git-seb for the work around in comment: https://github.com/magento/magento2/issues/36749#issuecomment-1396121443

We experienced this exact same error in a multi-store install, running on M2.4.6. Had to use database query to find all the label text (image_label, small_image_label, thumbnail_label) that were not associated to a product image (ie: no image file path) in catalog_product_entity_varchar database table, at default and store view levels. Once these were all removed, then could export all the SKUs without issue and no longer see the error in log.
