### ISSUE TITLE
After upgrade to 2.4.3-p1, static block from layout update xml no longer rendering

### ISSUE THREAD

**Issue by xtremevision** [magento/magento2#35069] opened 2022-02-08 15:27 UTC
### Summary (*)
After upgrade to 2.4.3-p1, static block from layout update xml no longer rendering. After updating the static block using the new page builder and saving, the frontend no longer renders the static block.

### Examples (*)
See screenshots.

### Proposed solution
No idea. The block should render just as it did before updating the content.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._
![2022-02-08 10 24 53](https://user-images.githubusercontent.com/6533394/153019196-b1ac7db3-ab12-4931-b0e9-73641d0a1bee.png)
![2022-02-08 10 22 38](https://user-images.githubusercontent.com/6533394/153019201-9f84a38b-53c6-42c0-b82b-8c48c6d8772e.png)
![2022-02-08 10 19 11](https://user-images.githubusercontent.com/6533394/153019204-5ade3aad-c8f2-4ceb-b4c5-2b678677905f.png)
![2022-02-08 10 17 20](https://user-images.githubusercontent.com/6533394/153019206-b4e0ab5f-ee73-4edb-bc93-9e49637f1dd2.png)

**Comment by xtremevision** [comment] 2022-02-08 20:18
It is not possible to replice via a dev instance. I need to create a custom theme, and override default.xml.

**Comment by engcom-Echo** [comment] 2022-07-21 10:56
@xtremevision,

Thanks your contribution and collaboration.
We have tried to reproduce on magento 2.4-develop branch but we are unable to reproduce it please provide more information and please elaborate steps.

Thanks

**Comment by engcom-Echo** [comment] 2022-08-04 14:43
Hello @xtremevision,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Echo** 2022-08-04 14:43 UTC
Labels: Triage: Dev.Experience, Issue: needs update
