### ISSUE TITLE
Cart section data has wrong product_price_value

### ISSUE THREAD

**Issue by NickdeK** [magento/magento2#20310] opened 2019-01-15 13:21 UTC
At the moment the `product_price_value` doesn't include tax if the configuration settings are set to include tax.

### Preconditions (*)

1. PHP 7.1
2. Magento 2.2.6
3. Stores > Configuration > Sales > Tax > Shopping Cart Display Settings > Display Prices > Including Tax 

### Steps to reproduce (*)

1. Add a item to your cart
2. View the cart section data via Chrome dev tools

### Expected result (*)

1. `product_price_value` is the same value as in the formated `product_price`

### Actual result (*)

1. `product_price_value` is exclusive tax where the `product_price` is inclusive
![screenshot 2019-01-15 at 14 13 58](https://user-images.githubusercontent.com/6631170/51183118-9f83f400-18d0-11e9-9855-47b220d42c0e.png)

**Comment by magento-engcom-team** [comment] 2019-01-15 13:21
Hi @NickdeK. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@NickdeK do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-15 13:22
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by NickdeK** [comment] 2019-01-15 13:33
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment] 2019-01-15 13:33
Hi @NickdeK. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment] 2019-01-15 13:34
Hi @NickdeK, here is your [Magento instance](https://i-20310-2-2-6.instances.magento-community.engineering).
Admin access: [https://i-20310-2-2-6.instances.magento-community.engineering/admin](https://i-20310-2-2-6.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-01-15 13:40
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-01-15 14:10
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97643`, `MAGETWO-97644` were created

**Comment by magento-engcom-team** [comment] 2019-01-21 19:40
Hi @routbiplab. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-03-04 14:47
Hi @NickdeK. Thank you for your report. 
The issue has been fixed in magento/magento2#20316 by @NickdeK in 2.3-develop branch
Related commit(s):
 - [764612e55df56d72f326246c39358a35d3fb07cb](https://github.com/magento/magento2/commit/764612e55df56d72f326246c39358a35d3fb07cb)
 - [7c7b078e10f68f60630541b90b2ed49dffc96560](https://github.com/magento/magento2/commit/7c7b078e10f68f60630541b90b2ed49dffc96560)
 - [3c8c4a7f9cba91e45ec890703a9a80e96a52a54c](https://github.com/magento/magento2/commit/3c8c4a7f9cba91e45ec890703a9a80e96a52a54c)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-04 14:47 UTC
Labels: Issue: Ready for Work, Component: Checkout, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by magento-engcom-team** [comment] 2019-03-08 13:10
Hi @NickdeK. Thank you for your report. 
The issue has been fixed in magento/magento2#21570 by @mage2pratik in 2.2-develop branch
Related commit(s):
 - [ce1c1a2e8f2342efb287934066e70587fe16c30d](https://github.com/magento/magento2/commit/ce1c1a2e8f2342efb287934066e70587fe16c30d)
 - [c821730fa110d93f92a87feb3e1bc8253c6ba820](https://github.com/magento/magento2/commit/c821730fa110d93f92a87feb3e1bc8253c6ba820)

The fix will be available with the upcoming 2.2.9 release.
