### ISSUE TITLE
Magento\Reports\Model\ResourceModel\Order\Collection->getDateRange() - Error in code?

### ISSUE THREAD

**Issue by realJustmike** [magento/magento2#20128] opened 2019-01-08 16:07 UTC
### Summary (*)

Magento 2.1.x

### Examples (*)

Please see 
Magento\Reports\Model\ResourceModel\Order\Collection->getDateRange()
on line 447:
$dateStart = $customStart ? $customStart : $dateEnd;

### Proposed solution

$dateStart = $customStart ? $customStart : $dateStart;

**Comment by magento-engcom-team** [comment] 2019-01-08 16:08
Hi @realJustmike. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@realJustmike do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by realJustmike** [comment] 2019-01-08 16:18
> Hi @realJustmike. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [x]  Summary of the issue
> * [x]  Information on your environment
> * [x]  Steps to reproduce
> * [x]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me $VERSION instance`
> 
> where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop).
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @realJustmike do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [x]  yes
> * [ ]  no

**Comment by magento-engcom-team** [comment] 2019-01-08 16:36
Hi @irajneeshgupta. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-01-08 16:48
@irajneeshgupta Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97498`, `MAGETWO-97499` were created

**Comment by magento-engcom-team** [comment] 2019-03-05 21:17
Hi @realJustmike. Thank you for your report. 
The issue has been fixed in magento/magento2#20129 by @milindsingh in 2.3-develop branch
Related commit(s):
 - [b1b6c3c9e9878c96e0b021c9489b6fdd490ea17f](https://github.com/magento/magento2/commit/b1b6c3c9e9878c96e0b021c9489b6fdd490ea17f)
 - [92dd7df47ba6fbe62bf0bc260c2c6cf286f2498d](https://github.com/magento/magento2/commit/92dd7df47ba6fbe62bf0bc260c2c6cf286f2498d)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-05 21:17 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Progress: PR Created, Component: Reports

**Comment by magento-engcom-team** [comment] 2019-03-15 18:45
Hi @realJustmike. Thank you for your report. 
The issue has been fixed in magento/magento2#21589 by @mage2pratik in 2.2-develop branch
Related commit(s):
 - [887433247a7d0da1237c0d7f60fe5bee1dfa4324](https://github.com/magento/magento2/commit/887433247a7d0da1237c0d7f60fe5bee1dfa4324)
 - [a75958fb46f606faec4d06e69f938188d5de5005](https://github.com/magento/magento2/commit/a75958fb46f606faec4d06e69f938188d5de5005)

The fix will be available with the upcoming 2.2.9 release.
