### ISSUE TITLE
Stock level is 0 but customers can buy the product.  Magento 2.0.7

### ISSUE THREAD

**Issue by devhn** [magento/magento2#5178] opened 2016-06-23 10:05 UTC
## Steps to reproduce
1. Create a configurable product, status is on stock
2. All of the simple product (within the same configurable product) come to a stock level 0, status is still in stock
3. Backorder is disabled
4. Customer comes to the direct URL (via Google)
5. Customer can buy the product, even though stock level is 0
## Expected result
1. Status of the product will change to out of stock
2. The product will be shown as out of stock
## Actual result
1. Product stays in stock
2. Product is shown as in stock
3. Customer is able to buy the product

Is there a setting that i missed?

**Comment by andimov** [comment] 2016-06-23 15:06
@devhn, thank you for reporting this issue!
Could you please provide magento version also?

**Comment by devhn** [comment] 2016-06-23 15:46
@andimov it's 2.0.7.

**Comment by peec** [comment] 2016-07-28 12:32
Cam accross this issue.

Magento: 2.1.0 GA

### Reproduce:
1. Create a configurable product. That generates products A and B.
2. On product B - set in stock status to Out of stock and stock level to 0. 

### Actual result:

In frontend, when changing to configurable product B , it still says "In Stock".

### Expected result:

In frontend, when chaging to configurable product B, it should display "Out of stock".

**Comment by plentyhappy** [comment] 2016-08-01 15:04
Using 2.0.7 - often our products come back to saying "in stock" when we set to "out of stock" - happens out of the blue

**Comment by SerhiyShkolyarenko** [comment] 2016-09-14 15:26
@devhn @peec thank you for reporting!
This issue was already described in #5558. Our internal issue is MAGETWO-58328.

**Comment by SerhiyShkolyarenko** [comment] 2016-09-14 15:33
@plentyhappy please feel free to create a separate issue when you find a way to reproduce permanently(or with high probability).

**Comment by magento-engcom-team** [comment] 2017-10-02 15:33
Hi @devhn 
We are closing this report as the fix for the issue is already released with `2.2.0`.
Please reopen if the problem persists.
Thank you

**Closed as completed by magento-engcom-team** 2017-10-02 15:33 UTC
Labels: Issue: Ready for Work, bug report, Component: Checkout, Issue: Format is not valid
