### ISSUE TITLE
Review summary block is not rendered in product page or product listing

### ISSUE THREAD

**Issue by elmahone** [magento/magento2#26613] opened 2020-01-31 12:44 UTC
### Preconditions (*)

1. Magento 2.3.3
2. An environment with multiple MySQL instances (3 in this case)

### Steps to reproduce (*)

1. Create a product that can be seen in a product list
2. Enable reviews
3. Add a review to the product

### Expected result (*)

1. Review summary block should display in the product cards and product page with the correct amount of stars

### Actual result (*)

1. Review summary block is not displayed at all

### Details
The root of the problem is in the function `\Magento\Review\Model\ReviewSummary::appendSummaryDataToObject`
Where the `$entityType` is set to 1 by default. In environments with multiple MySQL instances the autoincremental IDs are increased in intervals of 3. So we can't count on the product entity ID being 1, it might be 2 or 3. We fixed this issue by patching function `\Magento\Review\Block\Product\ReviewRenderer::getReviewsSummaryHtml` to fetch the product entity ID, instead of using the default 1

**Comment by GovindaSharma** [comment] 2020-02-02 07:53
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-02 07:53
Hi @GovindaSharma. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-02 07:53
Hi @GovindaSharma, here is your [Magento instance](https://i-26613-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26613-2-4-develop.instances.magento-community.engineering/admin_bf44](https://i-26613-2-4-develop.instances.magento-community.engineering/admin_bf44)
Login: `151cb6ea` Password: `8effc726b013`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2020-02-06 14:27
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31181` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment] 2020-05-21 13:38
Hello @elmahone @Bartlomiejsz and @engcom-Echo 

Could you please provide more details and exact configuration for 
> An environment with multiple MySQL instances (3 in this case)

With the current description it is not clear is it master/slave or split-db or some other configuration type. Without this information, we are not able to triage and prioritize. accept and test it after.

Thank you in advance!

**Comment by Bartlomiejsz** [comment] 2020-05-26 20:03
Hi @sdzhepa, not sure about exact way to simulate approach mentioned in ticket, but you can simulate error itself by manually changing `entity_id` in `review_entity` table for `product`. Error is caused by hardcoded value of identifier - 1 - in code, while it also exists in database table.

**Comment by agorbulin** [comment] 2020-07-16 07:42
Reproduced on 2.3.5-p1

**Comment by dverkade** [comment] 2021-04-18 20:17
Posting a comment. Issues should not be automatically closed.

**Comment by artttj** [comment] 2021-04-28 21:40
We are facing the same issue in the Magento Cloud production environment. 

We have database slave and `entity_id`'s there are different in `review_entity` table as @elmahone mentioned. 

The patch for `\Magento\Review\Block\Product\ReviewRenderer::getReviewsSummaryHtml()` solves the problem.

**Comment by Bartlomiejsz** [comment] 2021-04-28 21:44
@dverkade @artttj actually this issue should already be fixed in mainline. Despite of my PR pretty similar changes were pushed to core in https://github.com/magento/magento2/commit/fb2f1a74ad2a9442c4c6ca39b85b42050a9f387b so this ticket should be closed in my opinion 
CC @magento-engcom-team

**Comment by artttj** [comment] 2021-04-28 21:50
@Bartlomiejsz ,

Thanks for the info.

**Comment by zenfork** [comment] 2021-05-14 21:35
Reproduced on Magento 2.4.0 CE (Cloud). Please, consider this query as a hotfix:
```sql
SET FOREIGN_KEY_CHECKS = 0;

UPDATE
    review AS R,
    review_entity_summary AS RES,
    review_entity AS RE
SET
    R.entity_id = 1,
    RE.entity_id = 1,
    RES.entity_type = 1
WHERE
    RE.entity_code = 'product' AND (
        R.entity_id = RE.entity_id OR RES.entity_type = RE.entity_id
    );
    
SET FOREIGN_KEY_CHECKS = 1; 
```

**Comment by engcom-Bravo** [comment] 2024-04-18 11:42
Hi @elmahone,

As per this https://github.com/magento/magento2/issues/26613#issuecomment-828800606 We are closing this issue.since the issue has been fixed.

Thanks.

**Closed as completed by engcom-Bravo** 2024-04-18 11:42 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Issue: Format is valid, Component: Review, Reproduced on 2.4.x, Priority: P3, Severity: S3, Triage: Done, Progress: done, Reported on 2.3.3
