### ISSUE TITLE
Bundle product bundle items options are not aligned properly when adding products on "Create New Order" page in admin area

### ISSUE THREAD

**Issue by vasilii-b** [magento/magento2#20524] opened 2019-01-23 13:31 UTC
### Preconditions (*)
1. Magento 2.2-develop or Magento 2.3-develop
2. Bundle product with options

### Steps to reproduce (*)
1. Go to admin area
2. Go to Sales -> Orders
3. Press create a new order button
4. Press Add Products button
5. From the list, choose a bundle product and press "Configure"

### Expected result (*)
Quantity label and input field are aligned
![image](https://user-images.githubusercontent.com/13456702/51609706-7b08c700-1f23-11e9-880c-9418f3883ccc.png)

### Actual result (*)
Quantity label and input field are not aligned
![image](https://user-images.githubusercontent.com/13456702/51609753-9f64a380-1f23-11e9-83d3-613d67b6db58.png)

**Comment by magento-engcom-team** [comment] 2019-01-23 13:32
Hi @vasilii-b. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@vasilii-b do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-23 13:32
Hi @nainesh2jcommerce. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-01-23 13:34
@nainesh2jcommerce Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97893` were created

**Comment by rogyar** [comment] 2019-01-23 13:36
@nadim2jcommerce please, stop confirming issues you cannot reproduce. It's not a good practice at all. By doing that you make a mess in the entire process and confuse other people.
Thank you.

**Comment by rogyar** [comment] 2019-01-23 13:41
@nainesh2jcommerce please, stop confirming issues you cannot reproduce. It's not a good practice at all. By doing that you make a mess in the entire process and confuse other people.
Thank you.

**Comment by vasilii-b** [comment] 2019-01-23 13:54
Hi @rogyar, @nainesh2jcommerce .
I'm so sorry - this issue was on my local machine only. I didn't fetch all latest changes and didn't remove previous work.
Thank you!

**Closed as completed** 2019-01-23 13:56 UTC
Labels: Issue: Format is valid

**Comment by nainesh2jcommerce** [comment] 2019-01-23 14:07
Hi @rogyar ,
I'm sorry, there was little confusion for me, I was trying to reproduce the issue for previous ticket which was reproduce on my local and by mistake added lable for this ticket.

Thanks!
