### ISSUE TITLE
Installing simple products: PHP Fatal error:  Call to undefined method

### ISSUE THREAD

**Issue by mariarti** [magento/magento2#1656] opened 2015-08-12 15:07 UTC
Clear new install from CLI

stops on

Installing simple products:
PHP Fatal error:  Call to undefined method Magento\Catalog\Model\Resource\Product\Interceptor::getWriteConnection() in /var/www/html/test.com/app/code/Magento/SampleData/Module/Catalog/Setup/Product/Gallery.php on line 144

centos 6.7 x64

# php -v
PHP 5.6.12 (cli) (built: Aug  6 2015 17:14:56) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

# mysql -V
mysql  Ver 14.14 Distrib 5.6.26, for Linux (x86_64) using  EditLine wrapper

**Comment by mazhalai** [comment] 2015-08-12 15:22
@mariarti thank you for reporting, however this is a known issue and is a duplicate of #1610 , so please try installing with sample data from the master branch not develop branch

**Comment by mariarti** [comment] 2015-08-12 20:31
Thanks for advice
really, it helps:
`git clone https://github.com/magento/magento2.git -b master /var/www/html/test.com/`

**Closed** 2015-08-12 20:32 UTC
Labels: MX
