### ISSUE TITLE
Website cache issue

### ISSUE THREAD

**Issue by Avantree2020** [magento/magento2#34777] opened 2021-12-09 02:34 UTC
Preconditions (*)

1. Magento version  2.3.5-p2
2. Use Amasty Geoip extension for IP redirection

Steps to reproduce (*)

1. I visit a non-default store(for example, an EU store), and close. When I visit the default store(US store), it will redirect me to the previous store(EU store) that I visit previously and cannot switch back. After clearing cookies or using the Incognito window on the browser, it has no issue. But after a while, it happened again. I need to clear cookies again. I doubt it is the IP redirect extension issue, but after we disable the extension, the issue is still there.  

2. Sometimes, when I'm redirected to the wrong site(e.g.EU store), and it allows me to switch to another store (e.g.CA store). But when I switch to another store (e.g.CA store), the currency is not correct. In this case, it should be CAD, but it still shows the currency of EUR. 

Expected result (*)

1. Being redirected to the right store according to GeoIP setting even though I visited another store before. 
2. The currency should keep the same as the backend setting for each store, and will not change to the currency of the store being redirected previously. 

Actual result (*)

1. My IP is US and it redirect me to EU store. We did not set redirection for RAM store, but when I visit RAM store, it will redirect me to the US store with the RMA store URL, when add to cart, the URL will become US store URL.
2. When I forced to be redirected to EU store and switch to other stores like CA or AU store, the currency for CA or AU store will become Euro, which should be CAD or AUD respectively. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by ihor-sviziev** [comment] 2021-12-09 06:27
Hi @Avantree2020,
If I got it correctly, the issue is located basically in the Amasty GeoIP extension, not the Magento itself. Could you please contact Amasty support for further assistance?

**Comment by Avantree2020** [comment] 2021-12-09 06:56
> Hi @Avantree2020, If I got it correctly, the issue is located basically in the Amasty GeoIP extension, not the Magento itself. Could you please contact Amasty support for further assistance?

Hi ihor-sviziev，

Thanks for your comment. 
1. I contacted Amasty support and they told me that it is due to cache, which can only be done by clearing the visitor's cookies. 
2. If it is due to the extension, I think the issue should be gone, but it was not. And also, what about the issue for currency not matching the store after redirection? The extension could not be able to change the currency of the store. I forgot to mention that the currency and price on the listing is taken from another store, but after adding to cart, it will become the correct number but wrong currency. For example, it shows EUR 65 on the listing of AU store, when add to cart, it became EUR 102. Finally, it charged AUD 102. It is really weird. 

We tried to shorten he cookies time on Magento, but it seems not working. I also asked our server, they said it is caching issue which could only be done by clearing cookies of the browser. But we have never met this issue until the recent one month.

**Comment by ihor-sviziev** [comment] 2021-12-09 07:11
@Avantree2020, could you try to reproduce the issue without custom extensions to make sure any of they does not cause that behavior?

**Comment by Avantree2020** [comment] 2021-12-09 07:34
> @Avantree2020, could you try to reproduce the issue without custom extensions to make sure any of them does not cause that behavior?

Hi ihor-sviziev，

I'm afraid we are not able to do that, since we use so many extensions on our site and the real time visitors are using some of them. 

Are you only dealing with Magento core issue? Shall I post the same question to the developer experience issue section? Will it be helpful? Thanks.

**Comment by in-session** [comment] 2021-12-09 08:13
@Avantree2020
I would suggest contacting Amasty, they usually answer very quickly and usually have a solution. Amasty is also able to copy the environment and perform a local test. 
Then a note about Geoip, which is not allowed in Europe according to the GDPR, which also leads to problems when using providers such as Cloudflare.

**Comment by engcom-November** [comment] 2021-12-09 11:32
Hi @Avantree2020 
Amasty is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.

**Closed as completed by engcom-November** 2021-12-09 11:32 UTC
Labels: Component: Bundled Extension, Issue: ready for confirmation
