### ISSUE TITLE
Some product URL version gives Error 404

### ISSUE THREAD

**Issue by stefancic** [magento/magento2#36398] opened 2022-10-30 08:26 UTC
### Preconditions and environment

- Magento 2.4.4
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

1. Create a product and assign it to different categories
2. URL rewrites are created in the database
3. Not  all URL rewrites are working on frontend, some randomly don't

### Expected result

All product URL versions should be working

### Actual result

Some products give error 404 on frontend despite having the URL rewrite keys in the database. This happens randomly for a product, some products are working fine, other dont. 

### Additional information

Example:

Product ID 11906

The URL rewrites in the database:

<img width="1509" alt="Screenshot 2022-10-30 at 09 23 02" src="https://user-images.githubusercontent.com/15705409/198869262-f69cf56f-0071-46c1-9459-ad6f2a1afbf4.png">

Final URLs are / should be:

https://megatoner.si/dahle-skarje-professional-10-26cm.html - WORKING
https://megatoner.si/pisarna/pisarniski-pripomocki/skarje-nozi/dahle-skarje-professional-10-26cm.html - WORKING
https://megatoner.si/pisarna/dahle-skarje-professional-10-26cm.html - THIS ONE IS ERROR 404
https://megatoner.si/pisarna/pisarniski-pripomocki/dahle-skarje-professional-10-26cm.html - WORKING

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by DavaGordon** [comment] 2022-11-01 20:14
@magento I am working on this

**Comment by DavaGordon** [comment] 2022-11-01 20:15
@magento give me 2.4.4 instance

**Comment by engcom-November** [comment] 2022-11-02 18:05
Hi @stefancic ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop and the issue is not reproducible.
**Steps performed:**
1. Navigate to admin panel > create 5 different categories > create a product and assign to all the 5 categories > save 
2. Go to stores > configuration > web > serach engine optimization > set to YES 
3 Now select catalog > catalog > search engine optimization > use categories path for product url = Yes , Generate "category/product" URL Rewrites = yes 
4 . Save config > reindex and clear cache 
5 . Go to Marketing > url rewrite > check the target path generated 
6 . Navigate to data base and check the path generated - query = select * from url_rewrite;
7 . Go to frontend and cheek the product detail page of the product for each category .
![image](https://user-images.githubusercontent.com/60198231/199567252-f7d24cce-7e83-48c9-a6fe-89917de30ece.png)
All URL rewrites are working fine as expected on front end. Kindly recheck the issue on Magento 2.4-develop instance and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by DavaGordon** [comment] 2022-11-03 00:29
@stefancic i followed your steps on vanilla instance using version 2.4.4 locally and was unable to replicate the issue following the steps you provided in your initial issue.

**Comment by angelo983** [comment] 2022-11-03 19:24
https://github.com/magento give me 2.4.4 instance

**Comment by angelo983** [comment] 2022-11-03 19:28
@stefancic be more careful next time, opening an issue takes time for other people.
https://megatoner.si/pisarna/dahle-skarje-professional-10-26cm.html - THIS ONE IS ERROR 404
it is a product link and you don't enabled Product URL Suffix in Stores => Settings => Configuration => Catalog => Catalog => Search Engine Optimization
https://megatoner.si/pisarna/dahle-skarje-professional-10-26cm WORKS!

**Comment by angelo983** [comment] 2022-11-03 19:35
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-11-16 04:29
Hi @stefancic ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed** 2022-11-16 04:29 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
