### ISSUE TITLE
getting 524 error while creating configural product in magento 2.4.6

### ISSUE THREAD

**Issue by Develop3-prt** [magento/magento2#38992] opened 2024-07-31 09:02 UTC
### Preconditions and environment

- Magento version - 2.4.6

### Steps to reproduce

Clone a configurable product.
Try to create variations for 8-10 sizes from diffrent arributes
Add  images to the products.
Click on save

### Expected result

Product is saved relatively fast 5-15 seconds

### Actual result

A timeout occurred (error code 524)

### Additional information

https://github.com/user-attachments/assets/ae48a15c-dd56-44f5-8073-e4167b7c1324

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-07-31 10:32
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-07-31 11:50
Hi @Develop3-prt,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.


**Steps to reproduce**

1. Clone a configurable product.
2. Try to create variations for 8-10 sizes from diffrent arributes
3. Add images to the products.
4. Click on save



https://github.com/user-attachments/assets/f49bdb6d-14a0-44ef-9cfc-f2b10ded08e8



We are able to save the product but based on the number of variations it will take time and there is no error.

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by Develop3-prt** [comment] 2024-08-10 12:56
after we add 8 -10 configurable product variation  , getting 524 error code.

**Comment by engcom-Bravo** [comment] 2024-08-12 09:44
Hi @Develop3-prt,

Thanks for your update.

We are able to add the 10+ variations for a configurable product and we are not getting any error.Kindly recheck the issue in Latest 2.4-develop instance and the elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-08-23 05:29
Hi @Develop3-prt,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-08-23 05:29 UTC
Labels: Issue: needs update, Reported on 2.4.6
