### ISSUE TITLE
API: Payment section within sales order with empty extension_attributes is array instead of object

### ISSUE THREAD

**Issue by Silarn** [magento/magento2#7892] opened 2016-12-20 00:30 UTC
### Preconditions
1. Magento 2.1.3 - possibly earlier
2. Available order data with no extension attributes for the payment method

### Steps to reproduce
1. Place an order without using Braintree to get order data with no extension attributes for payment info
2. Use the REST api to pull order data

### Expected result
1. The empty extension_attributes under the payment model should be output as an empty object

### Actual result
1. The empty extension_attributes is output as an empty array

This is an issue mainly for API connectors. If you try to map the response data directly onto the expected data model, you will get an error because of the data type mismatch.

**Comment by olysenko** [comment] 2016-12-20 16:42
Hi, thank you for your report. Internal issue was MAGETWO-62492  created

**Comment by misha-kotov** [comment] 2017-05-24 17:31
Correction: the above ticket was closed as a duplicate of this one: MAGETWO-56206. We will track progress under this ticket number.

**Comment by magento-engcom-team** [comment] 2017-09-20 23:16
@Silarn, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 23:16 UTC
Labels: Issue: Ready for Work, bug report, Component: Framework/Webapi, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
