### ISSUE TITLE
New Product in the first position at the category product list

### ISSUE THREAD

**Issue by iGerchak** [magento/magento2#26469] opened 2020-01-21 12:36 UTC
Example:
You have a site that sells Apple gadgets.
And there is an iPhone category.
Apple just presented the new iPhone 12.
You add an iPhone 12 to the iPhone category in few colors, but it's not available to order, because you don't have it on the stock.
As a result, the iPhone 12 will be in the first position on the iPhone category.
A customer will see unavailable products on the first positions and on the mobile device they don't see available products on the first page and might go away.

### Preconditions (*)
1. Magento 2.3.3 | 2.4-develop

### Steps to reproduce (*)
1. Create 3 product in the one category
2. Set position for this product 1, 2 and 3
3. Create one more product in the same category

### Expected result (*)
1. Last created product should be at the end of category product list

### Actual result (*)
1. Last created product at the first position of category product list

**Comment by krishprakash** [comment] 2020-01-21 12:44
Hi @iGerchak.
This is expected behavior of magento as last added product in category saved as default 0 in position so It should display first.

![image](https://user-images.githubusercontent.com/46617848/72805882-e93cb280-3c79-11ea-984c-7fd11a22777b.png)

**Comment by krishprakash** [comment] 2020-01-21 13:12
Closing this ticket as non issue

**Comment by iGerchak** [comment] 2020-01-21 13:54
Hi, @krishprakash.
I added the business issue to the description. Please review it.

**Comment by ihor-sviziev** [comment] 2020-01-22 15:48
@krishprakash 
From my perspective this is really valid issue that could decrease conversion rate for many magento installation.

As a fix we can actually add some configuration where you can change default position for new products.

I re-opened this issue for future discussion

**Comment by magento-engcom-team** [comment] 2020-01-23 04:43
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30681` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krishprakash** [comment] 2020-01-23 04:45
As mentioned the scenario by @iGerchak This should be Improved.
@ihor-sviziev Confirmed It.
Thank you for Feedback @iGerchak @ihor-sviziev

**Comment by Vijayashanthim** [comment] 2020-02-02 04:30
I'm Interested to work on this issue #26469

**Comment by Vijayashanthim** [comment] 2020-02-02 04:32
#mm20in

**Comment by magento-engcom-team** [comment] 2020-02-02 04:32
@Vijayashanthim thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by sdzhepa** [comment] 2020-06-23 20:26
Hello @iGerchak 

This issue has been reviewed and discussed on the Triage meeting with Magento Product Managers.

And  as a result, this issue was rejected as not a bug. 
quote:

> 
> This is actually default Magento behavior newest products are always shown on top of the list. And this is actually make much more sense to keep new items on top of the catalog in order to promote them.  
> So, every new product is assigned on position  “0” in a category.
> 
> If there is an issue with “Out of Stock” products admin can always go to the category page and sort out all them to the bottom by using visual merchandizer.
> 
> Anyway, we cannot accept this change since it is backward incompatible and if contributors want to introduce something like this it can be done only by adding a new configuration option, but this looks like a low priority feature to me and not a bug.
>

**Closed as completed by sdzhepa** 2020-06-23 20:26 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Admin, Reproduced on 2.4.x, Event: mm20in, Triage: Ready for Triage, Reported on 2.3.3

**Comment by vijay-prevaj** [comment] 2021-03-09 07:04
@magento-engcom-team any patch available for this issue ?
