### ISSUE TITLE
Model *_save_commit_after events are not executed in api post requests

### ISSUE THREAD

**Issue by lykciv** [magento/magento2#30983] opened 2020-11-19 13:00 UTC
### Preconditions (*)

1. version 2.3.5
2. deploy mode should be set to "production"; this does not seem to be an issue in "developer" mode

### Steps to reproduce (*)

1. make sure your environment is set to production mode
2. place an order
3. create a shipment for the order using the api endpoint: /rest/all/V1/order/12345/ship

```
# example request

curl -X POST "http://magento.example.com/rest/all/V1/order/123456/ship" \
    -H  "accept: application/json" -H  "Content-Type: application/json" \
    -H  "Authorization: Bearer 124556azert" \
    -d '{
          "items": [
            {
              "extension_attributes": {},
              "order_item_id": 7654765,
              "qty": 1
            }
          ],
          "notify": true,
          "appendComment": true,
          "comment": {
            "extension_attributes": {},
            "comment": "lorem ipsum",
            "is_visible_on_front": 0
          },
          "tracks": [
            {
              "extension_attributes": {},
              "track_number": "AB1234",
              "title": "Carrier title",
              "carrier_code": "CAR"
            }
          ],
          "packages": [
            {
              "extension_attributes": {}
            }
          ],
          "arguments": {
            "extension_attributes": {}
          }
        }'
        
```

### Expected result (*)

1. when the shipment and order are saved, the following events should be dispatched
    - model_save_commit_after
    - sales_order_shipment_save_commit_after
    - sales_order_save_commit_after

### Actual result (*)

1. the events are not dispatched, because the function `\Magento\Framework\Model\AbstractModel::afterCommitCallback` is never executed

#### Actual problem

I managed to find why this problem occurs, but I'm not sure what the proper solution would be.

The events are dispatched using a callback in the ResourceModel save function.

```
// vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php:427

$this->addCommitCallback([$object, 'afterCommitCallback'])->commit();
```

In the commit function, the callback is actually executed, but only when `$this->getConnection()->getTransactionLevel()` is 0.

```
// \Magento\Framework\Model\ResourceModel\AbstractResource::commit

    public function commit()
    {
        $this->getConnection()->commit();
        /**
         * Process after commit callbacks
         */
        if ($this->getConnection()->getTransactionLevel() === 0) {
            $callbacks = CallbackPool::get(spl_object_hash($this->getConnection()));
            try {
                foreach ($callbacks as $callback) {
                    call_user_func($callback);
                }
            } catch (\Exception $e) {
                $this->getLogger()->critical($e);
            }
        }
        return $this;
    }
```

When a shipment is created using the api the transaction level will never be 0. 

In the function below `$connection->beginTransaction()` is called, which sets the level to 1.  But no transaction has actually been added to the connection at this point.
The repository save functions will also execute `$connection->beginTransaction()` which then sets the level higher (see `\Magento\Framework\DB\Adapter\Pdo\Mysql::beginTransaction`). As a result the transaction level will not get to 0 and the callback above is never executed.

```
// \Magento\Sales\Model\ShipOrder::execute

public function execute( $orderId, ... ) 
{
        $connection = $this->resourceConnection->getConnection('sales');
        $order = $this->orderRepository->get($orderId);
        $shipment = $this->shipmentDocumentFactory->create($order, ...);
// ...
        $connection->beginTransaction();
        try {
// ...
            $this->shipmentRepository->save($shipment);
            $this->orderRepository->save($order);
            $connection->commit();
        } catch (\Exception $e) {
            $this->logger->critical($e);
            $connection->rollBack();
            throw new \Magento\Sales\Exception\CouldNotShipException(
                __('Could not save a shipment, see error log for details')
            );
        }
// ...
        return $shipment->getEntityId();
    }
}

```

#### Patch

The following patch is a work-around for the problem. However, this does remove the rollback option. So if something goes wrong during the order save process, you end up with an order which has a shipment, but does not have the state 'shipped'.

```
--- a/Model/ShipOrder.php
+++ b/Model/ShipOrder.php
@@ -136,7 +136,6 @@
         array $packages = [],
         \Magento\Sales\Api\Data\ShipmentCreationArgumentsInterface $arguments = null
     ) {
-        $connection = $this->resourceConnection->getConnection('sales');
         $order = $this->orderRepository->get($orderId);
         $shipment = $this->shipmentDocumentFactory->create(
             $order,
@@ -162,7 +161,6 @@
                 __("Shipment Document Validation Error(s):\n" . implode("\n", $validationMessages->getMessages()))
             );
         }
-        $connection->beginTransaction();
         try {
             $this->orderRegistrar->register($order, $shipment);
             $order->setState(
@@ -171,11 +169,9 @@
             $order->setStatus($this->config->getStateDefaultStatus($order->getState()));
             $this->shipmentRepository->save($shipment);
             $this->orderRepository->save($order);
-            $connection->commit();
         } catch (\Exception $e) {
             $this->logger->critical($e);
-            $connection->rollBack();
             throw new \Magento\Sales\Exception\CouldNotShipException(
                 __('Could not save a shipment, see error log for details')
             );

```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ananth-iyer** [comment] 2021-01-08 10:50
@lykciv Can you move events.xml file in webapi_rest directory? let me know if it working or not

**Comment by lykciv** [comment] 2021-01-11 10:09
Hi @ananth-iyer . The `*_save_commit_after` events are never dispatched, so changing the location of the events configuration will not make a difference in this case.

**Comment by ananth-iyer** [comment] 2021-01-13 12:26
@lykciv you might try this events:
sales_order_shipment_save_after
sales_order_save_after

**Comment by lykciv** [comment] 2021-04-06 14:20
yes, the issue is still relevant

**Comment by engcom-Hotel** [comment] 2022-01-14 08:36
Hi @lykciv

I have followed the given steps to reproduce the issue:
make sure your environment is set to production mode
place an order
create a shipment for the order using the API endpoint: `/rest/all/V1/order/1/ship`
The shipment got created and returned the shipment ID. While debugging the aftercommitcallback function to make sure the events dispatch or not we found the `transactionlevel` to go to 0 as well. Please check the below screens.

The issue is not reproducible for us.
![image](https://user-images.githubusercontent.com/51681618/149479179-9ebca663-8f11-4c5a-9f66-38c4fcad3974.png)

After the transaction level check the dispatch events as well.
![image](https://user-images.githubusercontent.com/51681618/149479612-5841caef-2ccb-40a2-a18b-63c2960f244d.png)

Please let us know if we missed anything in order to reproduce the issue.

Thanks

**Comment by engcom-Hotel** [comment] 2022-01-28 05:58
Dear @lykciv,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-01-28 05:58 UTC
Labels: Triage: Dev.Experience, Issue: needs update

**Comment by brian-labelle** [comment] 2024-07-25 23:17
I'm running into a similar issue with `catalog_product_save_commit_after`

It appears that the event is dispatched when the product is saved via the admin panel, but when the product is saved via a rest API called to `/v1/products/:sku`, this event is not dispatching

**Comment by engcom-Hotel** [comment] 2024-07-26 06:19
Hello @brian-labelle,

According to this https://github.com/magento/magento2/issues/30983#issuecomment-1012915126, we could not reproduce the issue with the mentioned reproduction steps. Please provide us with the reproduction steps so we can proceed with this one.

Thanks

**Comment by brian-labelle** [comment] 2024-07-29 14:26
Hi @engcom-Hotel, I realized what happened. The issue is not that the event is not firing -- it is firing -- but an exception is occurring with commerce eventing when it attempts to convert the payload to JSON before storing in the database. Please see https://github.com/adobe/commerce-integration-starter-kit/issues/16 for an analysis is the issue
