### ISSUE TITLE
[EE][MFTF] Group: Place order and reorder.

### ISSUE THREAD

**Issue by engcom-Foxtrot** [magento/magento2#29739] opened 2020-08-25 13:28 UTC
Login as Customer Enterprise Edition logging function should be covered by MFTF test.

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2024-03-15 05:49
Hi @engcom-Foxtrot 

Thanks for reporting and collaboration.

Can you please add the setup to reproduce inorder for us to test the issue.

Thanks

**Comment by engcom-Dash** [comment] 2024-04-01 06:03
We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2024-04-01 06:03 UTC
Labels: Issue: Format is valid, Priority: P3, Severity: S3, Project: Login as Customer, Progress: done
