### ISSUE TITLE
B2B Company admin is assigned to wrong store when company is saved.

### ISSUE THREAD

**Issue by Syberspace** [magento/magento2#32585] opened 2021-03-24 09:21 UTC
### Preconditions (*)

1. Magento 2.3.6 B2B
2. Multiple Stores/Websites set up

### Steps to reproduce (*)

1. Create a new company with all required fields filled. Make sure in the section "Company Admin" the "Website" and " Send Welcome Email From" match and are NOT the store with the lowest ID
2. Check Customers->All Customers -> edit the newly created customer. Under "Account Information" it should show the customer assigned to the correct website ("Account created in").
3. Navigate to Customers->Companies and edit the company. Save without changing any of the fields.
4. Edit the customer again, it is now assigned to the store with the lowest ID ("Account created in").

### Expected result (*)

1. Customer stays assigned to the correct website when saving the company.

### Actual result (*)

1. Customer is assigned to the store with the lowest ID.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Syberspace** [comment] 2021-03-24 09:23
@mageto give me 2.4-develop instance with edition b2b

**Comment by Syberspace** [comment] 2021-03-24 09:25
@magento give me 2.4-develop instance with edition b2b

**Comment by Syberspace** [comment] 2021-03-24 09:43
Could not reproduce the issue on 2.4-develop.
The difference seems to be, that for 2.3.6 the "Send Welcome Email From" field includes ALL store views, while on 2.4-develop it only contains the store views relevant to the website set in the "Website" field

**Comment by engcom-Oscar** [comment] 2021-03-24 10:36
Hi @Syberspace ! Thank you for your report.
Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop by following steps from this ticket.
So, we have to close this ticket.

**Closed as completed by engcom-Oscar** 2021-03-24 10:36 UTC
Labels: Issue: ready for confirmation, not-confirmed
