### ISSUE TITLE
JavaScript modules contain unnecessary define checks

### ISSUE THREAD

**Issue by patrick-bigbridge** [magento/magento2#22747] opened 2019-05-06 09:49 UTC
Many Magento 2 RequireJS modules start with a check for the presence of RequireJS' "define" function. I wonder if this check is (still) necessary, or that it may be removed.

As far as I can tell "require.js" is the first JavaScript file that is loaded on every Magento 2 page, both frontend and backend. It is loaded synchronously, so all other JavaScript must be executed after this file has completed its execution. It is this file that ensures that the "define" function exists, and that it contains the 'amd' attribute.

Is the above code a remnant of the past in which the presence of RequireJS was uncertain, or is there still an important use case that is underdocumented?

### Preconditions (*)

1. This issue occurs in all Magento 2 versions to date.

### Steps to reproduce (*)

1. Visit translate.js or any other JavaScript file in Magento that contains the following code

```
if (typeof define === 'function' && define.amd) {
```

https://github.com/magento/magento2/blob/2.3-develop/lib/web/mage/translate.js

### Expected result (*)

1. If the check serves no function, I suggest it be removed from over 100 files in Magento 2 code. It takes up space, time, and makes these files harder to understand for a student of Magento.

```
define([
    'jquery',
    'mage/mage'
], function($){
    // module body
});
```

### Actual result (*)

1. The code now looks like this:

```
(function (factory) {
    if (typeof define === 'function' && define.amd) {
        define([
            'jquery',
            'mage/mage'
        ], factory);
    } else {
        factory(jQuery);
    }
}(function ($) {
    // module body
})

```

**Comment by krishprakash** [comment] 2019-05-06 10:00
Hi @patrick-bigbridge.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the Community Forums or the Magento Stack Exchange site for advice or general discussion about this.
It will help you to solve your queries.
Thank You.

**Comment by patrick-bigbridge** [comment] 2019-05-06 10:10
Hello @krishprakash 
I understand your desire to close off-topic issues quickly.
However, this **_is_** a core technical issue, as you call it, and I urge you to reopen.
Perhaps changing the title to "JavaScript modules contain unnecessary define checks" will help perceiving the issue as a bug rather than just a request for information.
Thank you.

**Comment by krishprakash** [comment] 2019-05-06 10:17
If it is related to any core issue then please update all the information with all necessary details.
as per your request I reopen it.
Thank you.

**Comment by patrick-bigbridge** [comment] 2019-05-06 10:30
Thank you. I updated the original issue.

**Comment by magento-engcom-team** [comment] 2019-08-22 10:51
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19567` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-08-22 10:54
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19567` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Usuario001** [comment] 2019-08-23 17:48
#cd19latam

**Closed as completed** 2019-10-15 02:01 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Cleanup, Component: Framework/RequireJs, Event: cd19latam

**Comment by patrick-bigbridge** [comment] 2019-10-15 07:19
Thanks!
