### ISSUE TITLE
Error 503 when attempting to complete a production environment database and media backup

### ISSUE THREAD

**Issue by michealcarroll** [magento/magento2#31479] opened 2020-12-29 03:02 UTC
### Preconditions (*)

1. version 2.3.4
2. Attempting to access the dashboard at https://www.hydeparkjewelers.com/hydepark_admin/admin/dashboard/index/key/913cd5d80331d5fb5fe1ce1a183846c0c9b49a63e8a97f90f63093cf0b5b0c7b/
2.

### Steps to reproduce (*)

1. go to https://www.hydeparkjewelers.com/hydepark_admin/admin/dashboard/index/key/913cd5d80331d5fb5fe1ce1a183846c0c9b49a63e8a97f90f63093cf0b5b0c7b/
2.

### Expected result (*)

1. Access to the Production Server dashboard
2.

### Actual result (*)

1. [Screenshots, logs or description]
2. Error 503 - Service Temporarily Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by michealcarroll** [comment] 2020-12-29 03:12
@magento-admin need assistance with this error

**Comment by engcom-Bravo** [comment] 2020-12-29 12:17
We are closing this issue as Duplicate of #31477

**Closed as completed by engcom-Bravo** 2020-12-29 12:17 UTC
Labels: Issue: ready for confirmation
