### ISSUE TITLE
Incorrect date formatting when switching between English and Dutch admin user language.

### ISSUE THREAD

**Issue by markPostema** [magento/magento2#26956] opened 2020-02-21 07:35 UTC
### Preconditions (*)

1. Magento ver. 2.3.3
2. Admin user language English(US)

### Steps to reproduce (*)

1. Set product 'Set Product as New From' to 7th of february 2020 (02/7/2020)
2. Save product
3. Change admin user language to Dutch(Netherlands)

![english_us](https://user-images.githubusercontent.com/2315282/75013470-a8a4a480-5484-11ea-9298-299f6d5ed168.png)

### Expected result (*)

1. The same date in the 'Set Product as New From' field, but then with the dutch date formatting applied (07-02-2020)(dd-mm-yyyy)

### Actual result (*)

1. Incorrect date formatting transforms the english date to 20-02-2007 (screenshots)

![dutch_nl](https://user-images.githubusercontent.com/2315282/75013469-a80c0e00-5484-11ea-930d-f2cd51dd5f97.png)

The date in the db is still the correct date, but when you save the product with the incorrect date formatting still in the 'Set Product as New From' field then thereafter the date in the db is also wrong. 

This issue applies to all datepicker fields, so also when using pricerules etc.

**Comment by markPostema** [comment] 2020-02-21 07:42
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment] 2020-02-21 07:42
Hi @markPostema. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment] 2020-02-21 07:43
Hi @markPostema, here is your [Magento instance](https://i-26956-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26956-2-3-3.instances.magento-community.engineering/admin_21b7](https://i-26956-2-3-3.instances.magento-community.engineering/admin_21b7)
Login: `3199922f` Password: `4b64feefeeaf`
Instance will be terminated in up to 3 hours.

**Comment by markPostema** [comment] 2020-02-21 08:01
Issue reproduced on https://i-26956-2-3-3.instances.magento-community.engineering/admin_21b7 magento instance. 

Date on english language
![instance_english_us](https://user-images.githubusercontent.com/2315282/75015331-a17f9580-5488-11ea-96f1-e59801fc2738.png)

Date on dutch language
![instance_dutch_nl](https://user-images.githubusercontent.com/2315282/75015361-b78d5600-5488-11ea-8aab-8a09ed0aeef4.png)

**Comment by GuiltyNL** [comment] 2020-02-21 10:54
I can confirm this is an issue. In the mean while we've removed the Dutch locale for our backend.

**Comment by devchris79** [comment] 2020-02-21 13:10
I think this is another manifestation of my issue #26675
Happily there is a fix in there :-)

**Comment by markPostema** [comment] 2020-02-24 09:06
> I think this is another manifestation of my issue #26675
> Happily there is a fix in there :-)

I applied the fix in your issue, it does not seem to work.

**Comment by AnnaShepa** [comment] 2020-02-25 14:02
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment] 2020-02-25 14:02
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by AnnaShepa** [comment] 2020-02-25 14:03
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-25 14:03
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-25 14:03
Hi @AnnaShepa, here is your [Magento instance](https://i-26956-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26956-2-3-3.instances.magento-community.engineering/admin_2881](https://i-26956-2-3-3.instances.magento-community.engineering/admin_2881)
Login: `00b9200b` Password: `6621d91d8a53`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2020-02-25 14:18
:white_check_mark: Confirmed by @AnnaShepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31873` were created

**Issue Available**: @AnnaShepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rdudhara** [comment] 2020-02-29 06:24
I am working on this issues.

**Comment by sanderjongsma** [comment] 2020-03-16 15:21
@rdudhara do you have an update about the progress, i ran into this problem also, mainly in the special_from_date and special_to_date

**Comment by baranada** [comment] 2020-03-19 10:08
I have tested on 2.4-develop branch. I can't reproduce the issue.
After I set the date and save the product in english language. and changed the admin language to Dutch.
the product page date is showed as dutch date type like screenshot.

![Screenshot from 2020-03-19 17-04-59](https://user-images.githubusercontent.com/61573611/77055902-3c29b080-6a04-11ea-90e2-b61bd8c34cb9.png)

**Comment by madhu-ranosys** [comment] 2020-04-06 08:26
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-06 08:27
Hi @madhu-ranosys. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-06 08:27
Hi @madhu-ranosys, here is your [Magento instance](https://i-26956-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26956-2-4-develop.instances.magento-community.engineering/admin_c8ec](https://i-26956-2-4-develop.instances.magento-community.engineering/admin_c8ec)
Login: `d62b4993` Password: `bd06e6b78de3`
Instance will be terminated in up to 3 hours.

**Comment by madhu-ranosys** [comment] 2020-04-06 08:40
@magento There is no dutch language package

**Comment by sdzhepa** [comment] 2020-08-17 20:04
Based on https://github.com/magento/magento2/issues/26956#issuecomment-601094586 issue was already fixed and cannot be reproduced on the latest `2.4-develop`

**Closed as completed** 2020-08-17 20:04 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Admin, Reproduced on 2.4.x, Triage: Ready for Triage, Reported on 2.3.3
