### ISSUE TITLE
Use REST API to create new product can't save product custom options

### ISSUE THREAD

**Issue by xiaogang87** [magento/magento2#4043] opened 2016-04-07 06:58 UTC
## Steps to reproduce
1. POST a new product with custom options to "/rest/V1/products"
## Expected result
1. a new product with custom options
## Actual result
1. a new product without custom options
2. After I debug it, I found wrong code may exist in the save function of "\vendor\magento\module-catalog\Model\ProductRepository.php".

In line 565, get a null $productOptions
In line 585, set the right `options` to $product
In line 603, set the null $productOptions as product options to the $product

**Comment by piotrekkaminski** [comment] 2016-05-27 19:49
Internal issue MAGETWO-53565

**Comment by safigo** [comment] 2016-06-02 12:47
I cannot reproduce issue in latest mainline and 2.0 branch, so I am closing this issue, as fixed. Feel free to reopen issue if we missed anything.

**Closed as completed** 2016-06-02 12:48 UTC
Labels: bug report
