### ISSUE TITLE
So many users do not set the proper filesystem permissions and ownership for autogenerated content (pub and var folders), and I think Magento 2 should detect such situations during an installation and warn the user 

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2516] opened 2015-11-25 11:14 UTC
Similar to https://github.com/magento/magento2/issues/2439
http://devdocs.magento.com/guides/v2.0/install-gde/install/file-system-perms.html

**Comment by techsoulman** [comment] 2015-11-25 11:22
I think I have done this wrong but I am really noobish so I'm not sure, I finished installation and files from the pub folder are missing*and maybe others) there are images and css missing from the storefront and admin

I don't know what I have done wrong can you explain(in language for dummies) how to resolve this?

**Comment by davidalger** [comment] 2015-12-09 01:39
Closing as duplicate of #2412.

**Closed as completed by davidalger** 2015-12-09 01:39 UTC
