### ISSUE TITLE
Error when updating cart quantity on cart page results in cart being updated anyway

### ISSUE THREAD

**Issue by michaellehmkuhl** [magento/magento2#38516] opened 2024-03-12 21:42 UTC
### Preconditions and environment

Observed in Magento Commerce 2.4.6, but based on the current state of the public code repository at this time, this appears to still be an issue in Magento 2.4.7.

### Steps to reproduce

(Borrowed from https://github.com/magento/magento2/issues/36184, simply to generate an error updating the cart)

- Use Magento Multishipping
- Login as customer
- Add 99 quantity of any item
- Proceed to cart
- Use multishipping checkout
- Update the quantity to reach the limit for multishipping quantity (update using the controls on the cart page, rather than in the minicart)
- Submit

### Expected result

When the user encounters an error updating the cart, they are presented with a modal alert. Dismissing the modal should return the user to the cart without actually submitting the form and performing the update action.

### Actual result

When the user dismisses the modal alert, the cart quantity is updated anyway.

### Additional information

In the `vendor/magento/module-checkout/view/frontend/web/js/action/update-shopping-cart.js` file, the `onError` handler fires the modal alert including an `always` callback that executes `submitForm()` when the modal is dismissed. This appears to have been added as part of feature request [MC-42813](https://github.com/magento/magento2/commit/4e73ff31750132c02396443a7531144770801be0).

My hunch is that adding the callback in that commit was unintentional, because it causes the cart update to execute even when there is an error thrown. If it was added intentionally, I'd like to understand the thought process behind updating the cart even after an error was thrown, rather than forcing the user to correct the error.

For our purposes, we've crafted a local patch to remove the `submitForm()` from the `always` callback to prevent the undesired form submit. But I'm hesitant to say removing the callback is the correct solution, because that callback has been in the released Magento codebase for several months now.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-03-13 05:56
@magento give me 2.4-develop instanc

**Comment by engcom-Bravo** [comment] 2024-03-13 11:04
Hi @michaellehmkuhl,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Use Magento Multishipping
- Login as customer
- Add 99 quantity of any item
- Proceed to cart
- Use multishipping checkout
- Update the quantity to reach the limit for multishipping quantity (update using the controls on the cart page, rather than in the minicart)
- Submit


![Screenshot from 2024-03-13 15-32-59](https://github.com/magento/magento2/assets/51680745/5f28c17f-638c-420a-84ce-0f65a369bd6d)



![Screenshot from 2024-03-13 15-33-54](https://github.com/magento/magento2/assets/51680745/f1f13f63-f044-4a62-b085-665db000aacd)



After getting an error the cart is not getting updated.

Kindly recheck the issue in Latest Magento 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by souzapsl** [comment] 2024-03-13 15:01
@magento give me 2.4.6-p1 instance

**Comment by souzapsl** [comment] 2024-03-13 15:05
@magento give me 2.4.5 instance

**Comment by engcom-Bravo** [comment] 2024-03-25 04:49
Hi @michaellehmkuhl,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-03-25 04:49 UTC
Labels: Issue: needs update, Reported on 2.4.6
