### ISSUE TITLE
Issues with base url when set use website on store view and website view has different url than default config

### ISSUE THREAD

**Issue by rohit-prjpt** [magento/magento2#7970] opened 2016-12-27 13:20 UTC
### Preconditions

1.  Magento ver. 2.1.3

### Steps to reproduce

1. default config has url set http://www.example.com
2. website scope has url set http://web1.example.com
3. store view scope - use setting use website 

### Expected result

1. it should use website url as we have configuration set use website 

### Actual result

1. frontend will use base url http://www.example.com but actually it should use http://web1.example.com

**Comment by veloraven** [comment] 2016-12-30 08:52
@rohit-prjpt thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result, and without external links.

**Comment by rohit-prjpt** [comment] 2016-12-30 08:57
it is already formatted with steps to reproduce, actual result and expected result, also the external urls are just example.com

**Comment by natebatty** [comment] 2017-01-10 16:55
Any update on this issue? I'm also having the same issue.

**Comment by korostii** [comment] 2017-01-10 17:30
I think it's a duplicate of #7815.
A possible fix is suggested [here](https://github.com/magento/magento2/issues/7840#issuecomment-268313989) and [here](https://github.com/magento/magento2/issues/7943#issuecomment-269508822) 
It would be nice though to see it fixed and released on 2.1 branch without having to resort to workarounds, but personally and basing on previous experience, I wouldn't be too optimistic about that.

**Comment by natebatty** [comment] 2017-01-16 21:23
Thank you 100 times over!

**Comment by IlnitskiyArtem** [comment] 2017-07-11 06:38
Hi,@rohit-prjpt. I've linked this GitHub issue to internal ticket MAGETWO-70596.

**Comment by magento-engcom-team** [comment] 2017-10-10 09:30
@rohit-prjpt, thank you for your report.
We've created internal ticket(s) MAGETWO-70596 to track progress on the issue.

**Comment by AndreyRozumny** [comment] 2018-04-04 15:00
#distributed-cd

**Comment by magento-engcom-team** [comment] 2018-04-04 15:01
@AndreyRozumny thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by AndreyRozumny** [comment] 2018-04-06 13:49
Seems like suggested solution were implemented in 2.2 and 2.2-develop branch so far.
And after dozens test made a decision it works as expected. can't replicate it anymore.

**Comment by magento-engcom-team** [comment] 2018-04-14 07:48
Hi @rohit-prjpt 
We are closing this it is was already fixed in `2.2`.
@AndreyRozumny Thank you for your investigation

**Closed as completed by magento-engcom-team** 2018-04-14 07:48 UTC
Labels: Issue: Ready for Work, bug report, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid
