### ISSUE TITLE
Cart with discount code higher then the amount in cart shows -€ NaN,N as grand total (only when also applicable to shipping)

### ISSUE THREAD

**Issue by kayintveen** [magento/magento2#6734] opened 2016-09-23 14:59 UTC
I am using magento 2.1.1 on php7
This situation occured on both production and development location.

We added 1 product to cart with the price of 3.99. 
We charge a 3.95 shiping cost, 
when applied a discount code of 50 euro which also applies to the shipping cost
the subtotal incl tax  = € NaN,N

But when proceeding to the checkout, all seem to work fine. Its only the totals in the cart.
in the api http://dfx-dev.microdesign.nl/rest/difrax_nl/V1/guest-carts/<id>/totals-information
we see something stranger. 
In totals_segment #4 we see this:
area:"footer"
code:"grand_total"
title:"Totaal"
value:**-8.8817841970013e-16**

the value ha's a e-16 next to it. 

This is the entire json
{"grand_total":0,"base_grand_total":-8.8817841970013e-16,"subtotal":3.3,"base_subtotal":3.3,"discount_amount":-7.94,"base_discount_amount":-7.94,"subtotal_with_discount":-4.64,"base_subtotal_with_discount":-4.64,"shipping_amount":3.26,"base_shipping_amount":3.26,"shipping_discount_amount":3.95,"base_shipping_discount_amount":3.95,"tax_amount":0.69,"base_tax_amount":0.69,"weee_tax_applied_amount":null,"shipping_tax_amount":0.69,"base_shipping_tax_amount":0.69,"subtotal_incl_tax":3.99,"base_subtotal_incl_tax":3.99,"shipping_incl_tax":3.95,"base_shipping_incl_tax":3.95,"base_currency_code":"EUR","quote_currency_code":"EUR","coupon_code":"COUPONTEST","items_qty":1,"items":[{"item_id":624,"price":3.3,"base_price":3.3,"qty":1,"row_total":3.3,"base_row_total":3.3,"row_total_with_discount":0,"tax_amount":0,"base_tax_amount":0,"tax_percent":21,"discount_amount":3.99,"base_discount_amount":3.99,"discount_percent":0,"price_incl_tax":3.99,"base_price_incl_tax":3.99,"row_total_incl_tax":3.99,"base_row_total_incl_tax":3.99,"options":"[]","weee_tax_applied_amount":null,"weee_tax_applied":null,"name":"test product"}],"total_segments":[{"code":"subtotal","title":"Subtotaal","value":3.99},{"code":"shipping","title":"Verzending & behandeling(Verzending & Handeling)","value":3.26},{"code":"discount","title":"Korting (\u20ac 50,- shoptegoed \u2605 fotoshoot 2016 )","value":-7.94},{"code":"tax","title":"Belasting","value":0.69,"area":"taxes","extension_attributes":{"tax_grandtotal_details":[{"amount":0.69,"rates":[{"percent":"21","title":"BTW"}],"group_id":1}]}},{"code":"grand_total","title":"Totaal","value":-8.8817841970013e-16,"area":"footer"}]}

**Comment by SerhiyShkolyarenko** [comment] 2016-09-28 09:59
Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines). Also please clarify which steps you perform on frontend/backend and which you perform using REST API.

**Comment by SerhiyShkolyarenko** [comment] 2016-10-25 14:31
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by SerhiyShkolyarenko** 2016-10-25 14:31 UTC
Labels: bug report, Progress: needs update, Component: Tax, Component: Checkout

**Comment by edvinst** [comment] 2017-02-11 14:41
I'm getting the same problem.
Cart summary grand total line: **Order Total  $NaN.N**
Magento: 2.1.3
Rest API: V1/guest-carts/totals-information request. 
Page: checkout_cart_index
Method: Magento\Quote\Model\Quote\Address\Total\Grand::collect
Result of line: $totals = array_sum($total->getAllTotalAmounts());  is 7.105427357601E-15.

var_dump of code: $total->getAllTotalAmounts(): 
array(9) {
  ["subtotal"]=> float(49.58)
  ["tax"]=> float(0)
  ["discount_tax_compensation"]=> float(9.42)
  ["weee"]=> int(0)
  ["shipping"]=> float(4.96)
  ["shipping_discount_tax_compensation"]=> float(0.94)
  ["discount"]=> float(-10)
  ["giftcard"]=> float(-54.9)
  ["weee_tax"]=> int(0)
}

There should be added additional check in frontend javascript side if rest api is returning float number in EXPONENT_DNUM format (7.105427357601E-15)

**Comment by andidhouse** [comment] 2017-08-07 10:20
Same problem in 2.1.7 - unbelievable to close this without testing just one time!

**Comment by deepak-netwin** [comment] 2018-02-01 11:03
@andidhouse are you able to fix this issue? If yes, how?

**Comment by germaike** [comment] 2018-02-01 13:52
Any fixes? Having the same problem.

**Comment by deepak-netwin** [comment] 2018-02-01 14:45
I've fixed this issue by overriding below js file in theme and updated getValue() function in it:
Magento_Tax/web/js/view/checkout/summary/grand-total.js

Before:

```
getValue: function() {
                var price = 0;
                if (this.totals()) {
                    price = totals.getSegment('grand_total').value;
                }
                return this.getFormattedPrice(price);
            },
```

After:

```
getValue: function() {
                var price = 0;
                if (this.totals()) {
                    price = parseFloat(totals.getSegment('grand_total').value).toFixed(2);
                }
                return this.getFormattedPrice(price);
            },
```

**Comment by lemaryn** [comment] 2019-12-12 11:35
Hello guys!
Issue is replicable in 
Magento ver. 2.2.10 / PHP Version 7.2.25
vendor/magento/module-quote/Model/Quote/Address/Total/Grand.php
Line 26         $totals = array_sum($total->getAllTotalAmounts());
this code 
`<?php
$getAllTotalAmounts = [
    "subtotal"                           => 108.29,
    "tax"                                => 0,
    "discount_tax_compensation"          => 21.66,
    "weee"                               => 0,
    "shipping"                           => 0,
    "shipping_discount_tax_compensation" => 0,
    "discount"                           => -129.95,
    "extra_tax"                          => 0,
    "weee_tax"                           => 0
];
echo array_sum($getAllTotalAmounts);`
return output 2.8421709430404E-14 but must be 0.
Do you have any fix for it ?
