### ISSUE TITLE
unable to schcule the order

### ISSUE THREAD

**Issue by EkomesLLP** [magento/magento2#39032] opened 2024-08-10 05:23 UTC
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

I am unable to process the order as it shows error 
![Screenshot (349)](https://github.com/user-attachments/assets/7bf06ee6-f34e-4d1a-86ef-5ca8a514fd2e)

### Expected result

order is unable to process 
![Screenshot (349)](https://github.com/user-attachments/assets/2f5cb0c1-ca85-401a-bfed-b6be58999cc0)

### Actual result

order is unable to process 
![Screenshot (349)](https://github.com/user-attachments/assets/f3818231-6483-4c4f-bbc8-731f2fc78b2c)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-08-12 06:16
Hi @EkomesLLP,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

<img width="1425" alt="Screenshot 2024-08-12 at 11 44 53" src="https://github.com/user-attachments/assets/90d0d887-f9fa-498b-b23a-936f9b77f92c">



Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-08-23 05:30
Hi @EkomesLLP,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-08-23 05:30 UTC
Labels: Issue: needs update, Reported on 2.4.x
