### ISSUE TITLE
Bundle item option qty incorrect after add to cart

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#30054] opened 2020-09-15 14:28 UTC
### Preconditions (*)

1. CE 2.4-develop
2. Sample data installed 
3. Theme used Luma (optional)
4. No customises

### Steps to reproduce (*)

1. View product bundle (in my case use product Companion kit yoga base on default luma)
2. Click button "Customize and Add to Cart"
3. Change qty of one option to 0 (default magento is 1)
4. Make sure summary info updated and show correct item (qty/price)before add to cart
5. Now click add to cart
6. Verify message success showed
7. Check minicart on top and verify qty again

### Expected result (*)

1. Qty option changed previously should show 0 

### Actual result (*)

1. Qty still show 1

CC: @ihor-sviziev can you verify this

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment] 2020-09-15 14:30
@magento give me 2.4-develop instance

**Comment by mrtuvn** [comment] 2020-09-15 14:43
![Screenshot from 2020-09-15 21-41-51](https://user-images.githubusercontent.com/1908873/93225421-69310300-f79c-11ea-86f0-ec580216cd3f.png)
i can reproduced issue in magento test instance

**Comment by magento-engcom-team** [comment] 2020-09-15 15:45
@ihor-sviziev Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2020-09-15 15:46
:white_check_mark: Confirmed by @ihor-sviziev 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37671` were created

**Issue Available**: @ihor-sviziev, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Oscar** [comment] 2020-09-16 08:48
Hello @mrtuvn, 
cc @ihor-sviziev  
Thank you for your report.
Sorry, but I can't agree that described issue is a bug. As I see in admin on 'Sprite Yoga Companion Kit' bundle product page, all options there set to 'required'
![image](https://user-images.githubusercontent.com/60198413/93313082-ab942780-f810-11ea-8b6b-2b39e84b31a4.png)
this mean you can't avoid of buying this option. Next - all these bundle options just simple products, and we can see that it is not allowed to add to the cart simple product with zero qty:
![image](https://user-images.githubusercontent.com/60198413/93313701-7a682700-f811-11ea-9c02-4a4bda05ed35.png)
So I consider that described issue is expected behavior for Bundle product with required options, therefore this ticket could be closed as not a bug. If you have some more details proving that issue is valid, feel free to update description and reopen it

**Closed as completed by engcom-Oscar** 2020-09-16 08:48 UTC
Labels: Issue: Clear Description, Issue: Format is valid, Component: Bundle, Progress: done, Reported on 2.4.0

**Comment by mrtuvn** [comment] 2020-09-16 09:25
Yes i agreed with your points

**Comment by ihor-sviziev** [comment] 2020-09-16 10:21
@engcom-Oscar the issue that customer put 0 instead of 1 and there are no errors before adding it to cart, also we don't have any error messages during add to cart that qty can't be 0 as it's required. Don't you think so?
