### ISSUE TITLE
Ui Listing sorting sometimes broken when SortOrderBuilder is used outside DataProvider

### ISSUE THREAD

**Issue by smartexcan** [magento/magento2#37731] opened 2023-07-06 19:43 UTC
### Preconditions and environment

- Magento version: 2.0+ (affected class is \Magento\Framework\Api\Search\SearchCriteriaBuilder)

### Steps to reproduce

1. Create ui component listing
2. Add some columns (id, name, etc)
3. Add a Select column, which gets its options from a class that uses SortOrderBuilder.
4. Add another non-select column after
5. Apply sort to column before select column

### Expected result

Columns before and after Select column should be sorted as intended when sort is applied.

### Actual result

Columns before Select column (that uses SortOrderBuilder) don't get sort applied.
Columns after Select column do get sort applied.

### Additional information

When using `Magento\Framework\Api\SortOrderBuilder` while loading a ui listing component (outside of the base DataProvider), trying to sort some columns might not work, depending on which column is being sorted.

If the column applies its sort order after the SortOrderBuilder is used, the sort will work.

The issue is in the `\Magento\Framework\Api\Search\SearchCriteriaBuilder` class.
Column ui components apply their sort order to the DataProvider, which adds it to the SearchCriteriaBuilder.

https://github.com/magento/magento2/blob/41883fa714af204533bb3adf7c22ef7f396a92ab/lib/internal/Magento/Framework/Api/Search/SearchCriteriaBuilder.php#L84-L89

Because the SortOrder object is not created until the SearchCriteriaBuilder create() method is called, other code can use SortOrderBuilder and create an object from it, resulting in the fields from the Column no longer being present.

https://github.com/magento/magento2/blob/41883fa714af204533bb3adf7c22ef7f396a92ab/lib/internal/Magento/Framework/Api/Search/SearchCriteriaBuilder.php#L63

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by smartexcan** [comment] 2023-07-06 19:43
@magento I am working on this

**Comment by smartexcan** [comment] 2023-07-06 19:44
I'll have a pr made for this shortly

**Comment by engcom-Hotel** [comment] 2023-09-25 09:48
Hello @smartexcan,

Thanks for the report and collaboration!

We have tried to reproduce the issue in the 2.4-develop branch but it seems the issue is not reproducible for us. We have followed the below steps in order to reproduce the issue:

1. Create a custom module.
2. Define UI component listing with the specified condition in the main description

We are getting the expected result. We request you to please help us with more details on the issue. It would be great if you could provide a sample code, screenshot, or screencast.

Thanks

**Comment by smartexcan** [comment] 2023-09-25 14:49
I've created a example module that should demonstrate the issue.
https://github.com/smartexcan/UiListingTestModule

Install the module, run `setup:upgrade` and `setup:di:compile`, then `authorexample:deploy`.

In admin panel, module adds a menu item "Example" at the end of the menu list, which goes to a grid that implements the issue.

**Comment by engcom-Hotel** [comment] 2023-09-26 07:40
Hello @smartexcan,

Thanks for the reply and module!

We have tried with your module as well but seems it is working as expected in the 2.4-develop branch. Please refer to the below screencast for reference:

[Example-Items-Magento-Admin.webm](https://github.com/magento/magento2/assets/51681618/367bd54b-d6ff-4218-af29-9e55dec24d97)

Let us know in case we have missed anything.

thanks

**Comment by smartexcan** [comment] 2023-09-26 14:04
I'm forgetting exactly which version i was testing this on back when i first reported the issue, but I'm thinking it was one of the 2.4.5 releases.

I've been running 2.4.6 since after rerporting this, and I'm not able to reproduce the issue myself anymore.

It looks like the following change probably fixed the issue, or at least stopped the side effects that were happening due to how it's implemented in `\Magento\Framework\Api\Search\SearchCriteriaBuilder`.
https://github.com/magento/magento2/commit/967f81780a2f02e5836cbf842f9df4cbeb716872

**Comment by engcom-Hotel** [comment] 2023-09-27 05:52
Hello @smartexcan,

Thanks for the confirmation!

As the issue is no longer reproducible on the latest 2.4-develop branch, we are closing this issue.

Thanks

**Closed as completed by engcom-Hotel** 2023-09-27 05:52 UTC
Labels: Triage: Dev.Experience, Priority: P2, Progress: done, Issue: needs update, Reported on 2.4.x
