### ISSUE TITLE
Vat Validation URL for EU Vat numbers changed. (Vies Service)

### ISSUE THREAD

**Issue by WIKAWebmaster** [magento/magento2#27874] opened 2020-04-16 12:43 UTC
An Vat Validation is not possible anymore because in the file:
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/Model/Vat.php

On line 47 the is the following code available
` const VAT_VALIDATION_WSDL_URL = 'http://ec.europa.eu/taxation_customs/vies/services/checkVatService?wsdl';`

This url is not working anymore and should be changed to the new one to get it working again:
[http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl]

New Code
' const VAT_VALIDATION_WSDL_URL = 'http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl';

**Preconditions (*)**

Steps to reproduce (*)

**Expected result (*)**

    [Screenshots, logs or description]

**Actual result (*)**

    [Screenshots, logs or description]

**Comment by WIKAWebmaster** [comment] 2020-04-16 12:44
yes

**Comment by shikhamis11** [comment] 2020-04-17 16:44
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-17 16:44
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-17 16:45
Hi @shikhamis11, here is your [Magento instance](https://i-27874-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27874-2-4-develop.instances.magento-community.engineering/admin_49d6](https://i-27874-2-4-develop.instances.magento-community.engineering/admin_49d6)
Login: `facdbe41` Password: `ef8c306dbeb5`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2020-04-17 17:08
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33515` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Closed as completed** 2020-04-25 06:21 UTC
Labels: Issue: Ready for Work, Component: Customer, Issue: Confirmed, Issue: Format is valid, good first issue, Component: Admin, Reproduced on 2.4.x, Fixed in 2.4.x, Reported on 2.4.0

**Comment by magento-engcom-team** [comment] 2020-05-01 01:29
Hi @WIKAWebmaster. Thank you for your report. 
The issue has been fixed in magento/magento2#27886 by @shikhamis11 in 2.4-develop branch
Related commit(s):
 - [faaec185511ccd0d8ca2797c5ea281894522df84](https://github.com/magento/magento2/commit/faaec185511ccd0d8ca2797c5ea281894522df84)
 - [49dc77b9e76e3964ec10a4428bfe7ffd319f2e16](https://github.com/magento/magento2/commit/49dc77b9e76e3964ec10a4428bfe7ffd319f2e16)

The fix will be available with the upcoming 2.4.0 release.

**Comment by grossmann** [comment] 2020-05-28 10:27
@magento-engcom-team 
Question: Is this going to be backported to Magento 2.3.x or do I have to upgrade to 2.4.0 when it is released? I could not find any documentation about how backports are handled in Magento 2.
Thanks for your reply.

**Comment by hostep** [comment] 2020-05-28 13:25
@grossmann: the @magento-engcom-team user is just a bot, it never replies when you ask it something 🙂 
If you need a fix, you'd best create a patch yourself and apply it to your shop somehow, that's usually the fastest approach.

@slavvka: can you answer the question above if this fix will be backported to 2.3.x? (maybe the bot can somehow automate its answers when a fix is being backported, that could be really helpful for informing the people interested)

**Comment by grossmann** [comment] 2020-05-29 09:22
@hostep Thanks for the hint with the bot ;-).
Sure, I already fixed it on my local 2.3.4-p2 installation. But if I do an composer update in the future, say to 2.3.x then the fix gets lost as it is not back ported.
A release for 2.4.0 is not yet available.

**Comment by chernenm** [comment] 2020-06-01 22:40
Hello @hostep,

This issue has been backported into 2.3.x in scope of this pull request https://github.com/magento/magento2ce/pull/5675

Best regards,
Misha Chernenko.

**Comment by grossmann** [comment] 2020-06-02 10:12
@chernenm Your link to the pull request gives a 404 error. Can you show me to the correct url?

**Comment by chernenm** [comment] 2020-06-02 14:45
Hello @grossmann,

I am sorry, it is not merged yet, it will be released in 2.3.6.

**Comment by slavvka** [comment] 2020-06-02 15:51
The link above is from internal repos.

**Comment by hostep** [comment] 2020-06-04 09:24
Thanks @chernenm!

Would Magento consider opening up a 2.3.6-preview branch for upcoming new versions to the community. Since that would make things a lot clearer and we can search that branch to see if things are being backported yes or no?
A couple of years ago, these [preview branches](https://twitter.com/okorshenko/status/895373728279928836) were available, but for some reason they got removed?
