### ISSUE TITLE
orderRepository does not check if there are no extensionAttributes

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/magento2#26526] opened 2020-01-24 14:41 UTC
### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Have an order which has no extensionAttributes
2. Try to load the order using orderRepository by `\Magento\Sales\Api\OrderRepositoryInterface::get`

### Expected result (*)

1. Order is loaded 

### Actual result (*)
1. Error: `Call to a member function setAppliedTaxes() on null`

![Screenshot from 2020-09-14 10-07-52](https://user-images.githubusercontent.com/51679138/93061913-e49b9300-f67c-11ea-9d97-811ed13f8435.png)

**Comment by PascalBrouwers** [comment] 2020-01-24 14:48
Don't worry, already made a fix

**Comment by engcom-Charlie** [comment] 2020-08-27 09:38
Hello @PascalBrouwers
Thank you for your contribution and collaboration!
We are not able to reproduce this issue on the latest 2.4-develop branch having order without extension on the latest 2.4-develop branch by following steps:
1. Retrieve order by `\Magento\Sales\Api\OrderRepositoryInterface::get`

**AR**: Order returned successfully.

Could you please take a look?

**Comment by magento-engcom-team** [comment] 2020-09-14 08:26
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37633` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2020-09-14 22:35
Hi @PascalBrouwers. Thank you for your report. 
The issue has been fixed in magento/magento2#26527 by @PascalBrouwers in 2.4-develop branch
Related commit(s):
 - [7a04c04bec1fa3525d8b43ca684e13da3cb37974](https://github.com/magento/magento2/commit/7a04c04bec1fa3525d8b43ca684e13da3cb37974)
 - [6ee28c852bcc49953a9c648e21fe9c96f61964f0](https://github.com/magento/magento2/commit/6ee28c852bcc49953a9c648e21fe9c96f61964f0)
 - [bb408984f2d58d301eef6d8faf3bff2c268f385f](https://github.com/magento/magento2/commit/bb408984f2d58d301eef6d8faf3bff2c268f385f)
 - [ff12e395b639b2f3155efcd730c8c20fc9389b50](https://github.com/magento/magento2/commit/ff12e395b639b2f3155efcd730c8c20fc9389b50)

The fix will be available with the upcoming 2.4.2 release.

**Closed as completed by magento-engcom-team** 2020-09-14 22:35 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Confirmed, Issue: Format is valid, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P1, Severity: S1, Progress: done, Reported on 2.4.0
