### ISSUE TITLE
Country isn't translated in customer emails when asyncronous sending is enabled

### ISSUE THREAD

**Issue by martinshawruroc** [magento/magento2#31999] opened 2021-02-09 09:22 UTC
### Preconditions (*)

1. 2.4.1
2. latest `2.4-develop`

### Steps to reproduce (*)

1. Create a fresh Magento2 instance, I used https://github.com/markshust/docker-magento with the latest `2.4-develop` branch (55c4ff8fbe6c17495477c5debb05cb84f9602236 at time of writing). I've also replicated the issue on 2.4.1
2. Create a simple product, details are unimportant
3. Create a new store view against the default store/website.
4. Change the locale of that storeview to something else. For my test I set it to German (German). It doesn't matter what language you choose, so long as the country name is different to the default locale (e.g. Germany vs Deutschland) The config can be found at Stores > Config > General > General > Locale.
5. Add a translation so that the locale you've added has at least the country translation. I installed a German language pack which covers this (https://github.com/mageplaza/magento-2-german-language-pack)
6. Configure your website so the new store can be accessed via the frontend. There are a few ways to do this, but I just enabled the Add Store Code to Urls configuration option (Stores > Config > General > Web).
7. Place an order on the newly created storeview for the simple product you created earlier.
8. Observe that in the order confirmation email the country is translated. (https://i.imgur.com/fTbmZ4d.png)
9. Change the system configuration so that async email sending is enabled (Stores > Config > Sales > Sales Emails > General Settings > Asynchronous sending)
10. Place an order on the newly created storeview for the simple product you created earlier.
11. Observe the email hasn't translated the country. (https://i.imgur.com/wrJm4m3.png)

### Expected result (*)

Regardless of whether or not the email is send asynchronously or synchronously all parts of the email should be translated to the locale that the order was placed in. 

![2021-02-09_12-29_1](https://user-images.githubusercontent.com/51679138/107351357-2f59f380-6ad3-11eb-9c31-f54a5314b34e.png)

### Actual result (*)

When the order email is sent asynchronously for an order with a different locale to the default, it isn't used. 

![2021-02-09_12-29](https://user-images.githubusercontent.com/51679138/107351376-33861100-6ad3-11eb-9795-2ffee9e76a2a.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment] 2021-02-09 10:35
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40809` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sanaeefar-saeed** [comment] 2021-08-25 01:58
use email_order_set_template_vars_before event and put this code on your observer to solve this issue
        // Locale needs to be changed based on the order's storeId
        $storeId       = $order->getStoreId();
        $newLocaleCode = $this->scopeConfig->getValue(
            $this->localeResolver->getDefaultLocalePath(),
            \Magento\Store\Model\ScopeInterface::SCOPE_STORE,
            $storeId
        );
        $this->localeResolver->setLocale($newLocaleCode);
        $this->translate->setLocale($newLocaleCode);

        $transport['formattedShippingAddress'] = $this->addressRenderer->format($order->getShippingAddress(), 'html');
        $transport['formattedBillingAddress']  = $this->addressRenderer->format($order->getBillingAddress(), 'html');

**Comment by onlinebizsoft** [comment] 2021-09-09 10:35
@engcom-Alfa can you make an update? Is this solved in 2.4.3 or recent 2.4-develop updates?

**Comment by ronakchauhan** [comment] 2022-12-08 09:55
@onlinebizsoft  I tried to reproduce the issue in magento 2.4.2-p2 but i think it's resolved now. so, cant reproduced it.
i have used default magento language pack for german language
[https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE](url)
composer install: `composer require splendidinternet/mage2-locale-de-de`

**Comment by joshbourke** [comment] 2023-08-24 17:22
I just ran into this problem. When order emails are sent async, the default locale is not correct.

Strangely enough, the i18n translations are correct, but the following method returns the root locale:
`\Magento\Framework\Locale\Resolver::getDefaultLocale`

This results in the French emails not having the correct datetime.

**Comment by engcom-Delta** [comment] 2024-09-03 10:49
Hi @martinshawruroc ,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop and the issue is not reproducible. Kindly refer the screenshots.

**Steps to reproduce -** 
1. Install magento 2.4-develop
2. Create a simple product
3. Create a new store view against the default store/website.
![image](https://github.com/user-attachments/assets/effedf0d-959e-498e-9a75-48fbbe6d12df)
4. Install german language pack and change the locale of the new store view to germany
5. Place an order on the newly created storeview for the simple product you created earlier.
6. Observe that in the order confirmation email the country is translated. 
![image](https://github.com/user-attachments/assets/f03b3aba-37c0-410e-8c1f-472878c37e62)
7. Change the system configuration so that async email sending is enabled (Stores > Config > Sales > Sales Emails > General Settings > Asynchronous sending)
![image](https://github.com/user-attachments/assets/87c833b8-fe68-4827-a1e5-e15e27d44eee)
8. Place an order on the newly created storeview for the simple product you created earlier.
9. Run the cron
10. Observe the email has translated the country. 
![image](https://github.com/user-attachments/assets/ac50cfcc-76cb-4b72-a8f2-d4e23041c796)
![image](https://github.com/user-attachments/assets/5b0cdd63-ede3-4c8b-b374-33d6cd90e456)

Kindly recheck the issue on latest Magento 2.4-develop instance and Please let us know if you are still facing any issue.

Thanks.

**Closed as completed by engcom-Delta** 2024-09-03 10:49 UTC
Labels: Component: Sales, Issue: Confirmed, Component: AsynchronousOperations, Component: Email, Reproduced on 2.4.x, Priority: P3, Severity: S3, Progress: done, Issue: ready for confirmation, Reported on 2.4.1
