### ISSUE TITLE
Error: Call to a member function getUrl() on null in /vendor/magento/module-catalog/view/frontend/templates/category/image.phtml:21

### ISSUE THREAD

**Issue by pratikkamani** [magento/magento2#31023] opened 2020-11-24 06:56 UTC
### Preconditions (*)

1. Magento 2.4.1 (Upgraded from Magento 2.3.3)
2. Visit category page

### Steps to reproduce (*)

1. Upgrade the site from Magento 2.3.3 to Magento 2.4.1
2. Open the category listing page

### Expected result (*)

1. Need to display the category product.

### Actual result (*)

1. 
![issue](https://user-images.githubusercontent.com/9292282/100058691-c78af980-2e4f-11eb-8093-de528ba4be8d.png)

---

Error: Call to a member function getUrl() on null in /vendor/magento/module-catalog/view/frontend/templates/category/image.phtml:21

**Comment by engcom-Alfa** [comment] 2020-11-24 08:06
Duplicate of #30753

**Closed as completed by engcom-Alfa** 2020-11-24 08:06 UTC
Labels: Issue: ready for confirmation

**Comment by pratikkamani** [comment] 2020-11-24 09:12
Thanks. This solution works for me https://github.com/magento/magento2/issues/30753#issuecomment-721432311
