### ISSUE TITLE
Label Fails

### ISSUE THREAD

**Issue by dulv** [magento/magento2#7409] opened 2016-11-12 03:05 UTC
Please help me fix this error
http://prntscr.com/d67ha1

Thanks

**Comment by mrkhoa99** [comment] 2016-11-12 08:25
@dulv I'm not sure what is your issue? Please, explain more details.

**Comment by pboisvert** [comment] 2016-11-13 16:32
@dulv can you follow the reporting template and include a description of the error, the steps needed to reproduce, and system information including version and configuration.

**Comment by dulv** [comment] 2016-11-14 01:19
I am using magento version 2.1.2
When i add/edit category, i can not get Label for Enable Category or Include in Menu
Please see error http://prntscr.com/d67ha1

Thanks

**Comment by ihor-sviziev** [comment] 2016-11-14 12:00
@dulv looks like your static content is broken. Please execute `php bin/magento setup:static-content:deploy` and try again.

**Comment by veloraven** [comment] 2016-11-30 14:38
@dulv did you try to execute the command described in the previous comment?
You may also need to clear browser cache. 
If the issue still reproduces, please format description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by vzabaznov** [comment] 2016-12-14 09:23
hi @dulv thank you for your reporting, we will close this issue for now as no update more than 2 week was received, please feel free to write here or to open new issue if needed

**Closed as completed by vzabaznov** 2016-12-14 09:23 UTC
Labels: Progress: needs update
