### ISSUE TITLE
Varnish cache and language switcher

### ISSUE THREAD

**Issue by matthew99** [magento/magento2#28080] opened 2020-05-02 18:35 UTC
### Preconditions (*)

1. Magento version 2.3.5 on dev server cloudways / digital ocean
2. Varnish v4

### Steps to reproduce (*)

1. Created 4 languages store views
2. Configured Varnish correctly (hit reported)
3. Change language (i.e. FR) load homepage 
4. Change language Again (UK)
5. Click home logo or refresh a few times. Or visit another page and come back to home page and refresh. Diffferent languages will load on refreshes
6. Disable Varnish, no problem 

### Expected result (*)

1. I would expect normal behavior; change language and refresh to chosen language obviously 

### Actual result (*)

1. Refresh gives sometimes good results, sometimes ‘old’ language.

I can’t find any troubles in my Varnish config. Yet it could still be a configuration thing.

**Comment by engcom-Alfa** [comment] 2020-11-26 09:33
Hi @matthew99 .
Unfortunately, we are not able to reproduce this issue on fresh 2.4-develop.
Everything works as expected.

Configured Varnish correctly (hit reported)

**Actual Result:** :heavy_check_mark: Different languages ​​did not load on refreshes

![Peek 2020-11-26 11-22](https://user-images.githubusercontent.com/51679138/100332607-4449df00-2fda-11eb-8464-51773d4114f4.gif)

So, we have to close it.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-11-26 09:33 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.3.5
