### ISSUE TITLE
IF bundle product's bundle option's default quantity is 0, you can't change quantity b/c <input.qty> disabled

### ISSUE THREAD

**Issue by JoshuaSoileau** [magento/magento2#9331] opened 2017-04-20 18:16 UTC
In `\Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option::getDefaultValues()` 

![image](https://cloud.githubusercontent.com/assets/2104388/25245664/36057220-25d3-11e7-94b8-b656f448cdfc.png)

On line 127

![image](https://cloud.githubusercontent.com/assets/2104388/25245673/3e6caeba-25d3-11e7-9caa-fcffb2edd120.png)

`$defaultQty` is cast as a `bool`. However, if you have the product configured such that the default quantity is 0, this makes `$canChangeQty` false

![image](https://cloud.githubusercontent.com/assets/2104388/25245740/7b963e3c-25d3-11e7-8657-c8df8d1b087e.png)

Which causes the template file `vendor/magento/module-bundle/view/frontend/templates/catalog/product/view/type/bundle/option/select.phtml` add `disabled="disabled"` onto the `<input.qty>` element:

![image](https://cloud.githubusercontent.com/assets/2104388/25245798/a071a520-25d3-11e7-9831-c336ea6caa49.png)

![image](https://cloud.githubusercontent.com/assets/2104388/25245808/b0062164-25d3-11e7-8a24-0146a1b79177.png)

Which means you can't change the quantity on the frontend.

### Preconditions

1. Magento 2.1.5
2. PHP5.6

### Steps to reproduce

1. Create bundle product with multiple bundle options
2. Set bundle option's default quantity to 0
3. View bundle product on frontend

### Expected result

1. You should be able to change this quantity field, despite it having a `0` as default value

### Actual result

1. Quantity is disabled. Cannot edit.

**Comment by Stas94** [comment] 2017-07-04 13:24
@JoshuaSoileau Thanks for reporting this issue. We've created internal ticket MAGETWO-70456 to address this issue.

**Comment by magento-engcom-team** [comment] 2017-10-10 10:30
@JoshuaSoileau, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-10 10:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Clear Description, Issue: Format is valid
