### ISSUE TITLE
Default storeview status field should be readonly not disabled

### ISSUE THREAD

**Issue by codedge** [magento/magento2#9976] opened 2017-06-18 08:55 UTC
When trying to change the name of the default storeview, the first time you want to save your changes an error message occurs saying `The default store cannot be disabled`. That occurs as the `status` field is set to `disabled` instead of `readonly` and so the status field is not correctly submitted.

### Preconditions
* Magento CE 2.1.7
* No test data installed, almost plain vanilla install

### Steps to reproduce
1. Go to `Stores` > `All stores`
2. Click the default store view and change the name
3. Submit you changes

### Expected result
1. Your changes should be saved without any errors.

### Actual result
1. An error occured `The default store cannot be disabled`

![storeview_1](https://user-images.githubusercontent.com/4409904/27259472-739a3796-5414-11e7-93db-90777ce9c5ab.png)

![storeview_2](https://user-images.githubusercontent.com/4409904/27259473-8df4b148-5414-11e7-9d4a-459fd85e7504.png)

**Comment by korostii** [comment] 2017-06-19 10:02
Seems like a duplicate of #7349 and #6435. The bug has two internal tickets MAGETWO-60746 and MAGETWO-57979 for more than half a year.

So here's a little joke: how many developers do you need in order to change an attribute on a html input?

@magento-team, any feedback on this one?

**Comment by codedge** [comment] 2017-06-20 12:49
Oh, I did look for an existing ticket but wasn't able to find one. 
Would it help if I create a PR @magento-team?

**Comment by orlangur** [comment] 2017-07-15 07:13
@codedge PR would never hurt, at least as help for others to patch their Magento instance, and nowadays PRs are also processed pretty quickly.

**Comment by krisdante** [comment] 2017-09-17 09:49
I tried to reproduce on develop branch (e649b4cc630dfa638271aebc9efd649c5f4bfca9) and it is not reproducible anymore. Seems to be fixed in newest code.

**Comment by ishakhsuvarov** [comment] 2017-09-17 09:59
@krisdante Looks like fix was delivered to the `develop` branch ([commits](https://github.com/magento/magento2/search?q=MAGETWO-60746&type=Commits&utf8=%E2%9C%93)) and is going to be released with 2.2. However, issue is still likely to affect `2.1`.

**Comment by magento-engcom-team** [comment] 2017-09-28 10:30
@codedge, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-28 10:30 UTC
Labels: Issue: Confirmed, Fixed in 2.2.x, Issue: Format is valid
