### ISSUE TITLE
Cannot find SKU in marketing - New Catalog Price Rule

### ISSUE THREAD

**Issue by cadoworld** [magento/magento2#6569] opened 2016-09-11 11:57 UTC
Magento 2.1

I am trying to setting up a discount for a specific product (SKU) on Marketing New catalog Price Rule but option in conditions seems to be incomplete.

![screenshot-2016-09-11-12 55](https://cloud.githubusercontent.com/assets/20308662/18417436/d8c318e0-7828-11e6-9ad5-f7da673c0abe.jpg)

No other option available.

**Comment by veloraven** [comment] 2016-09-12 12:27
@cadoworld thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by maqlec** [comment] 2016-09-12 19:55
You have to go to attribute panel and do 'sku' attribute usable in promo rules.

**Comment by veloraven** [comment] 2016-09-29 12:15
We are closing this issue because it hasn’t been updated by the reporter in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by veloraven** 2016-09-29 12:15 UTC
Labels: Progress: needs update
