### ISSUE TITLE
Checkbox UI Component valueMap returns wrong data type

### ISSUE THREAD

**Issue by ghost** [magento/magento2#27160] opened 2020-03-04 13:36 UTC
### Preconditions (*)

1. Magento 2.3.3-p1

### Steps to reproduce (*)

1. Create checkbox UI Component in a form
2. Use valueMap to set the following

<valueMap>
    <map name="false" xsi:type="boolean">false</map>
    <map name="true" xsi:type="boolean">true</map>
</valueMap>

### Expected result (*)

1. Checkbox should return a boolean

### Actual result (*)

1. Data returned is a string 
<img width="286" alt="Screen Shot 2020-03-04 at 13 36 00" src="https://user-images.githubusercontent.com/47739147/75884651-2372a580-5e1d-11ea-94fe-8678af218771.png">

**Comment by engcom-Echo** [comment] 2020-03-06 15:16
Hi, @paul-gene. Thek you for your report.

Please provide some of the code you use in *.xml
```
<formElements>
                <checkbox>
                    <settings>
                        <prefer>toggle</prefer>
                        <valueMap>
                            ......
                        </valueMap>
                    </settings>
                </checkbox>
            </formElements>
```

**Comment by paul-gene** [comment] 2020-03-06 15:19
@engcom-Echo literally the code from the devdocs

```
<field name="myCheckbox" formElement="checkbox">
            <settings>
                <label translate="true">Enabled</label>
                <tooltip>
                    <description translate="true">This is my checkbox's description</description>
                </tooltip>
            </settings>
            <formElements>
                <checkbox>
                    <settings>
                        <prefer>toggle</prefer>
                        <valueMap>
                            <map name="false" xsi:type="boolean">false</map>
                            <map name="true" xsi:type="boolean">true</map>
                        </valueMap>
                    </settings>
                </checkbox>
            </formElements>
        </field>
```

**Comment by magento-engcom-team** [comment] 2020-03-06 15:48
@engcom-Echo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2020-03-06 15:49
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32219` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by paul-gene** [comment] 2020-03-06 15:53
@engcom-Echo FYI, its not just the boolean data type that has issues, it happens with numbers as well. All outputted values are strings, regardless of the set data type.

**Comment by niravkrish** [comment] 2020-03-17 12:47
Hi @paul-gene,

I have created admin form and try to generate the issue with your code in Magento-2.3.4.
but I can not able to reproduce this issue.
Please see the attachment.

Also one thing I need to know from you is how you are checking the value of the ui component.
as per your screenshot I saw something like waches.
what is waches and how can I check. is it any tool.

Thank you,
Nirav Patel
![Screenshot from 2020-03-17 18-16-36](https://user-images.githubusercontent.com/44108490/76857456-76b41180-687b-11ea-9d8b-ffb8f788b6dd.png)

**Comment by paul-gene** [comment] 2020-03-17 12:54
@niravkrish you are checking the console though. This is an issue in the PHP code.

**Comment by engcom-Bravo** [comment] 2024-10-07 05:15
As per this comment https://github.com/magento/magento2/issues/27160#issuecomment-600051514 we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-10-07 05:15 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Issue: Format is valid, Component: Ui, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P3, Severity: S3, Progress: done
