### ISSUE TITLE
getCacheTags for price issue

### ISSUE THREAD

**Issue by Styopchik** [magento/magento2#9877] opened 2017-06-08 10:54 UTC
### Preconditions
Problem on Magento 2.1.5.

### Steps to reproduce
`\Magento\Catalog\Block\Category\Plugin\PriceBoxTags::getTaxRateIds` in line 104

### Actual result 
 calls $rateRequest like this:
`$rateRequest = $this->getTaxCalculation()->getRateRequest(`
`                $billingAddress,`
`                $shippingAddress,`
`                $customerTaxClassId,`
`                $this->scopeResolver->getScope()->getId(),`
`                $this->customerSession->getCustomerId()`
`            );`

### Expected Result
but the original method accepts $shippingAddress first 

`public function getRateRequest(`
`        $shippingAddress = null,`
`        $billingAddress = null,`
`        $customerTaxClass = null,`
`        $store = null,`
`        $customerId = null`
`    )`

**Comment by veloraven** [comment] 2017-06-22 07:12
@Styopchik thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by magento-engcom-team** [comment] 2017-09-11 18:29
@Styopchik thank you for your report. It would be very helpful if you can create Pull Request for this issue

**Comment by keyurshah070** [comment] 2017-09-17 13:10
will do it

**Comment by magento-team** [comment] 2017-09-19 09:42
Internal ticket to track issue progress: MAGETWO-75328

**Comment by magento-engcom-team** [comment] 2017-09-20 23:07
@Styopchik, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by okorshenko** [comment] 2017-10-04 21:11
@Styopchik thank you for your report. The issue is already fixed in 2.2-develop branch (PR: #11154 by @denysbabenko) and will be available in the Magento 2.2.2 release

**Closed as completed by okorshenko** 2017-10-04 21:11 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by magento-team** [comment] 2017-10-04 21:24
Internal ticket to track issue progress: MAGETWO-80511
