### ISSUE TITLE
Product attributes' labels are not translated on product edit page

### ISSUE THREAD

**Issue by ffrodoe** [magento/magento2#1980] opened 2015-09-29 10:21 UTC
For example try to translate "Meta Keywords" attribute label.
![screen_000043](https://cloud.githubusercontent.com/assets/12183505/10161459/f6bee416-66ac-11e5-997e-e6e0fb56b311.jpg)

**Comment by dfediuk** [comment] 2015-09-29 10:56
Same as https://github.com/magento/magento2/issues/1909
My fix: https://mage2.pro/t/73

**Comment by voleye** [comment] 2015-10-01 12:55
Hi @dfediuk,

It is not exactly an issue because there is no such agreement that says that attributes should be named in English. The fix would not works in case when somebody calls attribute in French, for example.

Thank you for this comment! We will discuss it and get back to you once we agreed on it.

**Comment by dfediuk** [comment] 2015-10-01 13:34
There is **no big problem** with non-standard attributes: an administrator enters them manually and can set them any title he wants.
There is **the problem** with the standard attributes, and their titles are always in English. The problem is there are 43 standard attributes and now they should be translated manually for each new Magento installation: this is a lot of manual work.

**Comment by voleye** [comment] 2015-10-01 16:00
@dfediuk 

I agree with you, but in general when you see in the code `__('Some Phrase')` this 'Some Phrase' from translation mechanism of view is nothing else as 'key'. 

Attribute label does not meet this pattern because it is not a 'key' (In case of French, for example).

**Comment by piotrekkaminski** [comment] 2016-08-29 15:24
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Product-attributes-labels-are-not-translated-on-product-edit/idi-p/45779).

**Closed by piotrekkaminski** 2016-08-29 15:24 UTC
Labels: improvement, moved_to_forums, TECH

**Comment by magento-team** [comment] 2017-07-31 22:42
Internal ticket to track issue progress: MAGETWO-70543
