### ISSUE TITLE
Bad Scope for Magento\Customer\Model\ResourceModel\Address\Attribute\Source\CountryWithWebsites

### ISSUE THREAD

**Issue by pmaryglobalia** [magento/magento2#36815] opened 2023-02-07 21:18 UTC
### Preconditions and environment

- Magento version 2.4.5-p1
- Set the configuration: Share Customer Accounts => Global
- Having two stores or more
- Create new customer with a store_id different than the id 1

### Steps to reproduce

Go to the customers page in admin
Click edit on the previous customer with a store_id different than 1
Go to the addresses sections
Click Add New Address

### Expected result

View the address edition section

### Actual result

Popup with the error: Attention Something went wrong.
Error in the logs:  The website with id 2 that was requested wasn't found. Verify the website and try again.

### Additional information

The bug is located in the Class : Magento\Customer\Model\ResourceModel\Address\Attribute\Source\CountryWithWebsites at the line 130 

The website scope is used with the customer store_id  (2). It results in a crash because the website "2" does not exist on my environment

  $allowedCountries = $this->allowedCountriesReader->getAllowedCountries(
                    ScopeInterface::SCOPE_WEBSITE,
                    $storeId
                );

should be 

   $allowedCountries = $this->allowedCountriesReader->getAllowedCountries(
                    ScopeInterface::SCOPE_STORE,
                    $storeId
                );

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-02-08 10:03
Hi @pmaryglobalia,

Thanks for your contribution & collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible but There is an ongoing confirmed issue https://github.com/magento/magento2/issues/36582 for the same. Kindly move on to this issue for latest updates / solutions on the same.

We are closing this as duplicate.

Thanks.

**Closed as completed by engcom-Bravo** 2023-02-08 10:03 UTC
Labels: duplicate, Issue: ready for confirmation, Reported on 2.4.5-p1

**Comment by matthieu-blackbird** [comment] 2024-09-23 14:23
The issue is still there in 2.4.6-p6. Where storeId is used in website scope, resulting in an NoSuchEntity because it cannot find the website with the store id.
`$allowedCountries = $this->allowedCountriesReader->getAllowedCountries(
                    ScopeInterface::SCOPE_STORE,
                    $storeId
                );`
