### ISSUE TITLE
Magento 2.06: Web Setup Wizard can't sync with Marketplace (looping wheel)

### ISSUE THREAD

**Issue by commcad** [magento/magento2#4575] opened 2016-05-19 12:09 UTC
## Steps to reproduce
1. Install fresh copy of Magento 2.06 from composer create-project
2. Backend > System > Web Setup Wizard > Add and save PKs in Configuration Manager
3. Backend > System > Web Setup Wizard > Component Manager
4. Click Sync button

Steps were taken for cleaning var/cache/di/generation + re-compiling/indexing/flushing., multiple times. 

Noticed a few members here on Github and the Magento Core Forum reporting the exact same issue however haven't seen an official bug report on the subject. 
## Expected result
1. Ability to Sync with Magento's Marketplace, install newly purchased extensions
## Actual result
1. Once the Sync button is clicked, the Please Wait display and the wheel continuously rotate

![mage_wsw](https://cloud.githubusercontent.com/assets/19387951/15393078/d3f4bef2-1dfd-11e6-9f6a-c0ef6dca58a1.jpg)

Note: The backend successfully login to the Marketplace using our PKs.
Note: Marketplace's PKs are saved into auth.php, we've checked that
Note: We tried registering new PKs on Marketplace with another account

Env:
1. Ubuntu 14/PHP5.6
2. Google cloud, 1vCPU, 3.75Gig memory, 25G SSD
3. Developer mode, perms have read & write as per Magento doc recommendation
4. Fresh install 2.06, no sample data, no extensions install (OOTB)

**Comment by commcad** [comment] 2016-05-19 12:19
Please note the OOTB installation of 2.06 comes with a great deal of CRITICAL errors related to CSS which get logged inside system.log. Not sure how relevant this is to this actual problem. Regardless of those critical errors, the frointend and backend seems to be functioning well.

No erros/logs other that those CRITICAL CSS ones. Let me know if you need me to look for something in particular and I'll do that.

Thanks guys

**Comment by mazhalai** [comment] 2016-05-19 13:41
@commcad this has been fixed internally (will be in the develop branch soon), and is marked for 2.1 release.

**Comment by commcad** [comment] 2016-05-19 14:52
Thanks mazhalai, we'll keep an eye open for the release.

Keep up the good work there guys

**Comment by andidhouse** [comment] 2016-05-20 08:27
@mazhalai do you know when 2.1 is released. we also have the same problem.

**Comment by commcad** [comment] 2016-05-21 13:43
@andidhouse 

I know I know... not a fix but regardless, a bloody exciting news none the less. We just can't wait to bring up our business online using this Magento platform. All very exciting, hope all goes well at M2 Studios!

https://community.magento.com/t5/News-Announcements/Magento-Community-Edition-2-1-Release-Candidate-1-is-Ready-for/m-p/37435#M80

**Comment by mazhalai** [comment] 2016-05-23 13:41
@andidhouse 2.1.0-rc1 was released on Friday: https://github.com/magento/magento2/tree/2.1.0-rc1

**Comment by apurv-anand** [comment] 2016-06-16 11:25
I was hoping this to be fixed in 2.0.x release as well. Can we have this as a patch? We are on 2.0.7.
... or at least if there is a workaround, let me know.

**Comment by apurv-anand** [comment] 2016-07-06 10:40
Any patch for 2.0.7. I would consider this as a critical issue if a major functionality is blocked. I am wondering how this is not included for 2.0 releases.

**Closed as completed** 2016-07-07 20:59 UTC

**Comment by kcsf** [comment] 2016-07-12 18:24
we are having the same problem on 2.07 - and can't upgrade to 2.1 yet, as the unify extension we need isn't yet compatible.  if there isn't a patch for 2.0x - can you at least show us where the problem is in core, so we can patch it ourselves??

**Comment by hocomadvies** [comment] 2016-10-18 11:17
Any solution on this? I have issues with it in a 2.0.9 version. If not fixed than all the versions having problems with it, are useless!! Would an update to 2.1 help to solve this?

**Comment by perfpcs** [comment] 2016-10-20 02:24
Same problem here. Almost the entire Web Setup Wizard is completely useless. Blank pages and spinning wheels with many php processes none of which ever complete. Is anyone looking to fix this? BTW running latest v 2.1.3

**Comment by hocomadvies** [comment] 2016-10-22 09:51
@perfpcs I managed to get it going after an update to 2.1.2 on my own vps. Only falling in other problems. Where did you get the 2.1.3 version from? Github? I like to update to that as well. 
I now installed the tar.gz version from Magento.com. and getting Cannot gather stats! Warning!stat(): stat failed for /var/www/html/pub/media/catalog/product/i/m/i0351.jpg seems that should be solved in the 2.1.3 version?

**Comment by magedmik** [comment] 2016-11-28 04:23
I'm facing the same problem here with 2.1.2 and not able to install any extensions bought from the Marketplace.

**Comment by makarious10** [comment] 2017-01-06 11:49
I'm also having this issue on Magento 2.1.3 and can't install any extensions from Marketplace. Is there a fix for this yet?

**Comment by gisjohn** [comment] 2017-01-18 03:06
I've noticed I can't ping any .magento.com domain from my server.  However, I can ping other external domains just fine.

**Comment by frefadmin** [comment] 2017-01-18 08:21
I had the same problem on my local Installation. My Problem was, that our company uses a PROXY. I couldn’t find a way to fix this. Without PROXY everything works fine.


Am 18.01.2017 um 04:06 schrieb John Winningham <notifications@github.com<mailto:notifications@github.com>>:


I've noticed I can't ping any .magento.com<http://magento.com> domain from my server. However, I can ping other external domains just fine.

**Comment by kgeiger310** [comment] 2017-01-25 20:48
I'm having same problem, fresh install of 2.1.3

**Comment by AvanorHealthcare** [comment] 2017-03-16 14:48
Me too, fresh install of 2.1.5

**Comment by gworksmobi** [comment] 2017-03-27 07:00
magento version  2.0.8, 

nginx version: nginx/1.10.0 (Ubuntu),

**Doc-root** magento-root (/var/www/html/)

**Permission** 
chown -R www-data:www-data /var/www/html
chmod -R 777 /var/www/html

System -> Web Setup Wizard -> Component Manager -> signin(public key/private key) -> sync -> non stop spin wheel (please wait).

error in nginx log

2017/03/27 06:31:51 [error] 2458#2458: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Cannot instantiate interface Zend\ServiceManager\ServiceLocatorInterface in /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:73
Stack trace:
#0 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Zend\\ServiceMan...')
#1 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Zend\\ServiceMan...')
#2 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Zend\\ServiceMan...', NULL, 'serviceLocator', 'Magento\\Setup\\M...')
#3 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Setup\\M...', Array, Array)
#4 /var/www/html/v" while reading response header from upstream, client: 172.18.0.1, server: 172.18.0.30, request: "GET /setup/index.php/componentGrid/sync HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "www.test.net", referrer: "http://www.test.net/setup/"

may I know what is the exact reason for this?  What are the debug steps?  Last two hours I'm searching for the solution? please help me on this
