### ISSUE TITLE
Required parameter 'theme_dir' was not passed

### ISSUE THREAD

**Issue by tmiron** [magento/magento2#6454] opened 2016-09-01 20:39 UTC
### Preconditions

1. 
2. 
### Steps to reproduce

1. 
2. 
3. 
### Expected result

1. 
### Actual result

1. [Screenshot, logs]

**Comment by tmiron** [comment] 2016-09-01 20:40
Getting Error Required parameter 'theme_dir' was not passed - Magento 2.0

Came out of no where one day everything fine, today (9/1/16) get errror when uploading image

Any help would be great, thanks

**Comment by veloraven** [comment] 2016-09-02 08:25
@tmiron thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the exact used Magento version.

**Comment by voleye** [comment] 2016-09-22 09:20
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by voleye** 2016-09-22 09:20 UTC
Labels: Progress: needs update
