### ISSUE TITLE
i have problem with install inventory in magento version 2.3.4

### ISSUE THREAD

**Issue by NinoGraphic** [magento/magento2#38139] opened 2023-11-01 11:26 UTC
### Preconditions and environment

my problem with install Inventory i have module this module installing with inventory modules i downloaded all the add-ons Inventory and i put it in app/code/magento Like the instructions provided But when giving command

php bin/magento setup:upgrade

i get this error

Service method specified in the definition of topic "async.V1.inventory.bulk-product-source-assign.POST" is not available. Given "Magento\InventoryCatalogApi\Api\BulkSourceAssignInterface::execute"

But when giving command

php bin/magento setup:di:compile

i get this error

-bash-4.2$ php bin/magento setup:di:compile Compilation was started. Repositories code generation... 1/7 [==>-----------------] 14% < 1 sec 78.5 MiB Fatal error: Interface 'Magento\InventoryCatalogApi\Model\GetProductTypesBySkusInterface' not found in /home/user/domains/domain.com/public_html/app/code/Magento/InventoryCatalog/Model/ResourceModel/GetProductTypesBySkus.php on line 17

i use version 2.3.4 of magento and i want to install inventory with The right install without a problem Because there is an important add-on for me and my store, I installed it, but it requires installation Inventory

### Steps to reproduce

Record report Error

![report recoder](https://github.com/magento/magento2/assets/149584296/c9954b4e-8c0d-4b18-8eaa-e5e4e58b96b5)

### Expected result

Error of debug.log

![debug](https://github.com/magento/magento2/assets/149584296/9afac9bf-b2c3-4fcd-b3c2-4127ee5d948c)

### Actual result

and this error of system.log

![system](https://github.com/magento/magento2/assets/149584296/4a1f3cb2-33d5-429c-acad-174f4a4969a3)

### Additional information

and this error from exception.log

[2023-11-01 08:45:29] main.CRITICAL: Unable to retrieve deployment version of static files from the file system. {"report_id":"9710be8a4fb157c494c51d9812b399847ce4779107ef35b50a0e877fdf6291af","exception":"[object] (UnexpectedValueException(code: 0): Unable to retrieve deployment version of static files from the file system. at /home/user/domains/domain.com/public_html/lib/internal/Magento/Framework/App/View/Deployment/Version.php:88)"} []

### Release note

When all components are deleted Inventory Modules my store back work no problem but my problem must me install Inventorey to install some modules i have my magento version is 2.3.4

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-11-15 10:31
Hi @NinoGraphic,

Thank you for reporting and collaboration.

We have verified the issue in the Latest version of Magento Instance we are able to install the inventory modules successfully.

Could you please refer this document https://experienceleague.adobe.com/docs/commerce-admin/inventory/get-started/install-update.html?lang=en regarding installing inventory for Magento Instance.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-11-28 05:25
Hi @NinoGraphic,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38139#issuecomment-1812202007 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-12-07 05:52
Hi @NinoGraphic,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-12-07 05:52 UTC
Labels: Issue: needs update, Reported on 2.3.4
