### ISSUE TITLE
Magento Sales Order: Design Align issue

### ISSUE THREAD

**Issue by vishal-7037** [magento/magento2#21962] opened 2019-03-27 09:38 UTC
There is one issue regarding design of Sales order view.
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

1. Login to admin
2. Go to Sales > Order, Open any order.

### Expected result (*)

![2019_03_27_Shipping_Method_alignment_solution](https://user-images.githubusercontent.com/38535982/55065586-17755400-50a2-11e9-829b-65b8e28b2230.png)

### Actual result (*)
![2019_03_27_Shipping_Method_alignment_issue](https://user-images.githubusercontent.com/38535982/55065593-1d6b3500-50a2-11e9-8560-8645ded68c55.png)

**Comment by magento-engcom-team** [comment] 2019-03-27 09:38
Hi @vishal-7037. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@vishal-7037 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-03-27 11:25
Hi @dmytro-ch. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-03-27 11:37
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98882`, `MAGETWO-98883` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-04-28 22:10
Hi @vishal-7037. Thank you for your report. 
The issue has been fixed in magento/magento2#21963 by @vishal-7037 in 2.3-develop branch
Related commit(s):
 - [eec7473b6c774d72ab2d3e86495b43082face6f5](https://github.com/magento/magento2/commit/eec7473b6c774d72ab2d3e86495b43082face6f5)
 - [719ed40200caeedc87bd56545d4727afb889bed0](https://github.com/magento/magento2/commit/719ed40200caeedc87bd56545d4727afb889bed0)
 - [c64fd576dbf1aede214705785b4792b74b08fa48](https://github.com/magento/magento2/commit/c64fd576dbf1aede214705785b4792b74b08fa48)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-04-28 22:10 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid
