### ISSUE TITLE
Catalog product list widget sort order configured in backend does not match in frontend

### ISSUE THREAD

**Issue by BorisovskiP** [magento/magento2#27126] opened 2020-03-02 17:08 UTC
emphasized text

1. Create category ( `Catalog -> Categories -> Add Root Category`)
2. Rename category to TestCategory 
3. Add 3 or more products  to Category (`Catalog-> Products -> Select/Edit -> Categories -> TestCategory -> Done -> Save)`
4. Open` Catalog -> Categories -> TestCategory -> Products` in Category
5. Set position on productX to 1, Set position on productY to 2 , Set position on productZ to 3 and Save
6. Add CMS Page (`Content -> Page -> Add New Page -> PageTitle = TestPage) `
7. Set Content on TestPage to the following (change the category ID; template can be chosen freely)
        `widget type="Magento\CatalogWidget\Block\Product\ProductsList" show*pager="0" products_count="10" template="Magento_CatalogWidget::product/widget/content/home-grid.phtml" **conditions_encoded="<sup>[{{1`:</sup>[`type`:`Magento](|CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``<sup>],`1--1`:</sup>[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`category*ids`,`operator`:`==`,`value`:`1`<sup>]</sup>)"}}

8. Insert widget with widget type - Catalog Product List and condition - Category is <id>
![image](https://user-images.githubusercontent.com/60198231/169833460-4fb28c1d-6d34-46eb-ab54-ebe54f147928.png)

### Expected result (*)

1. productZ (position3) is first, productX (position 1) is second, productY (position 2) is last

**Comment by shikhamis11** [comment] 2020-03-04 03:26
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-04 03:26
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-03-04 03:27
Hi @shikhamis11, here is your [Magento instance](https://i-27126-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27126-2-4-develop.instances.magento-community.engineering/admin_8734](https://i-27126-2-4-develop.instances.magento-community.engineering/admin_8734)
Login: `ca6ddb22` Password: `040f68dcd4a6`
Instance will be terminated in up to 3 hours.

**Comment by BorisovskiP** [comment] 2020-03-10 11:59
@shikhamis11 Can you tell me whats the status of this issue?

**Comment by shikhamis11** [comment] 2020-03-13 04:10
hello @BorisovskiP 
I am able to reproduce this issue but I find that there is no toolbar available on the CMS pages with the widget so not able to decide what will be default sorting

**Comment by BorisovskiP** [comment] 2020-03-13 07:49
hello @shikhamis11, 
Do you have any ideas how you would proceed?

**Comment by shikhamis11** [comment] 2020-03-13 07:52
I will discuss this issue with @sdzhepa and update the progress here

**Comment by BorisovskiP** [comment] 2020-03-19 14:43
Any updates on the issue @shikhamis11 ?

**Comment by sdzhepa** [comment] 2020-04-04 21:21
@engcom-Alfa , @engcom-Echo 

Could you please help with the investigation and confirmation process for this issue?

**Comment by BorisovskiP** [comment] 2020-04-22 06:00
@engcom-Alfa Any updates on this issue?

**Comment by engcom-Alfa** [comment] 2020-04-22 08:30
Hi @BorisovskiP. Sorry for the delay.

 We've checked the issue and can conclude that indeed, the sort order by position has not been preserved

**Actual Result:**
productZ (position 3) is first, productY (position 2) is second and  productX (position 1)  is last
![screenshot](https://user-images.githubusercontent.com/51679138/79957151-d65c9880-8489-11ea-911e-7866d345b3b1.png)

But we are not quite sure how sorting should be set for widgets.
Perhaps a better solution to this problem would be to add sort selection functionality when creating the `Catalog product list` widget.
Like that:
![Screenshot from 2020-04-22 11-25-33](https://user-images.githubusercontent.com/51679138/79958915-22104180-848c-11ea-952c-248d471d6713.png)

@BorisovskiP What do you think about it?
Thanks!

**Comment by euchenhofer** [comment] 2020-04-22 08:51
@engcom-Alfa 
I think this would be a great solution!

**Comment by BorisovskiP** [comment] 2020-04-22 11:04
@engcom-Alfa I think that by default, sort by position should be applied, but having the possibility to set the sort order in the widget does sound nice.

**Comment by BorisovskiP** [comment] 2020-05-04 06:46
@engcom-Alfa what is the current status of this issue? Do you have any updates?

**Comment by BorisovskiP** [comment] 2020-06-02 12:21
@engcom-Alfa Any news regarding the issue?

**Comment by Edelstahlshop** [comment] 2020-08-12 18:16
@shikhamis11 @magento-engcom-team : Is there any update? Thanks for your efforts until. I would really like to get this issue fixed.

**Comment by BorisovskiP** [comment] 2021-01-04 07:49
@magento-engcom-team @shikhamis11 Any new updates regarding this issue?

**Comment by thinkfix** [comment] 2021-02-26 10:40
@magento-engcom-team @shikhamis11 
Waiting for updates on this issue

**Comment by sprankhub** [comment] 2021-05-13 18:56
Still relevant :roll_eyes:

**Comment by magento-engcom-team** [comment] 2021-06-01 10:42
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42518` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Alfa** [comment] 2021-06-01 10:47
Tested this issue again in 4.2-develop and noticed it is still reproducible.
Below are the screenshots of it.

![image](https://user-images.githubusercontent.com/51679138/120310856-76732b00-c2f4-11eb-940b-baccd2689846.png)

![image](https://user-images.githubusercontent.com/51679138/120311035-a8848d00-c2f4-11eb-8763-808bed86db54.png)

![image](https://user-images.githubusercontent.com/51679138/120311108-bd612080-c2f4-11eb-93d5-0a14263ec9d3.png)

Confirming the issue and marking it as feature_request as per the above discussed comments.

**Comment by JKair** [comment] 2021-08-20 09:17
It's this issues in processing?

**Comment by mobweb** [comment] 2021-09-17 06:43
Would also really like to see this fixed. 👍

**Comment by sprankhub** [comment] 2021-12-28 10:49
So has this finally been fixed? If so, where? Or why has it been closed?

cc @sivaschenko

**Comment by engcom-Hotel** [comment] 2022-02-02 12:48
Since the related [PR](https://github.com/magento-commerce/magento2ce/pull/7439) is in open state, hence reopening this issue.

Thanks

**Comment by engcom-Hotel** [comment] 2022-05-13 08:07
Hello @BorisovskiP,

I think this is due to some access required. I can see that the PR is merged.

Thanks

**Comment by BorisovskiP** [comment] 2022-05-16 06:18
Hello @engcom-Hotel, could you tell me in which version has the PR been merged? If its not in 2.4.4, could you please point me to the place where the changes have been made so that we can apply a patch to the current version of Magento that we use that still has the issue present?

**Comment by engcom-Hotel** [comment] 2022-05-20 16:09
Hello @BorisovskiP,

We are re-checking the previous activities on this, will update u soon.

Thanks

**Comment by engcom-November** [comment] 2022-05-23 13:38
Verified the issue on Magento 2.4-develop branch and the issue is still reproducible.
Sort by Position / or id is not working and there is no sort by drop down is also present for user to select. Hence considering this as feature request. Updating the description of manual steps to reproduce.
![image](https://user-images.githubusercontent.com/60198231/169831788-7a258844-11e0-4cfe-a293-d8ffb2be729a.png)

**Closed as completed** 2022-05-23 15:11 UTC
Labels: feature request, Component: Widget, Reproduced on 2.4.x, Priority: P1, Progress: done, Reported on 2.3.4

**Comment by mobweb** [comment] 2022-11-22 07:42
Where can we open a feature request for this? Right now there seems to be no way to specify an order for products shown in a "Catalog Products List" widget. But I strongly suggest adding this, as a merchant might want to show selected products on a CMS page with a specific order, e.g. the most important product first.
