### ISSUE TITLE
Bug while write graphql api test  with Magento\Customer\Test\Fixture\Customer fixture

### ISSUE THREAD

**Issue by Citizen4our** [magento/magento2#37787] opened 2023-07-22 08:31 UTC
### Preconditions and environment

Magento version - 2.4.6-p1

### Steps to reproduce

1. create new Graphql test
2. add DataFixture - Magento\Customer\Test\Fixture\Customer
3. try to run it without specify website_id in $data params
results looks like this:
<img width="804" alt="image" src="https://github.com/magento/magento2/assets/47303372/1bc30885-a39f-40aa-adf5-86731700f5f0">

Noticed: website_id in db has null value. Maybe in fixture set default value for it?
When specify website_id - test passed. Example:
<img width="1160" alt="image" src="https://github.com/magento/magento2/assets/47303372/77af966f-c214-4d7b-9e3e-9c3a019a495a">

used phpunit_graphql.xml from phpunit_graphql.xml.dist

### Expected result

Tests passed as in integration test, when no specify website_id. Example integration test:
<img width="1319" alt="image" src="https://github.com/magento/magento2/assets/47303372/600d2a04-2cee-49d6-9be3-ea0cdc6a5c15">

### Actual result

test failed.
![image](https://github.com/magento/magento2/assets/47303372/280b3446-6b19-40bb-8128-ee1d5d5570ab)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2023-08-01 11:48
Hello @Citizen4our,

Thank you for report and collaboration!

We tried to reproduce the issue on 2.4-develop.
But for us, both the test with and without specifying `website_id` executed without any issues.

Please refer the screenshots below:
Without specifying `website_id`:
![image](https://github.com/magento/magento2/assets/60198231/1236e5b9-110e-4ab9-b03e-dc1a75ae7736)

With specifying `website_id`:
![image](https://github.com/magento/magento2/assets/60198231/1c3f21b2-26df-447a-8ef9-aec79e0f2ed0)

Please let us know if we are missing something.

Thanks.

**Comment by Citizen4our** [comment] 2023-08-01 11:56
What is the value in the database in the website_id field are you receiving? I see null in this field for customer during the test, and it is reason bug.
Maybe it related to admin settings to share customer between stores/websites?

**Comment by engcom-November** [comment] 2023-08-17 07:00
Hello @Citizen4our,
Thank you for quick response!

We ran the test with both Share Customer Accounts set as `Global` and `Per Website`, and the test is being executed successfully for both the cases.
In the `customer_entity` table the `website_id` will be null if you do not have any customers.
If you are referring to other table, please let us know which table are you talking about.

Thank you.

**Comment by engcom-November** [comment] 2023-08-30 10:46
Hello @Citizen4our ,

We have noticed that this issue has not been updated since long time. Hence we assume that the issue is fixed now, so we are closing it. Please feel free to raise a new one or reopen this issue if you need more assistance.

Thanks.

**Closed as completed by engcom-November** 2023-08-30 10:46 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.6-p1
