### ISSUE TITLE
SharedCatalog Endpoint Returns Invalid JSON

### ISSUE THREAD

**Issue by oefterdal** [magento/magento2#38158] opened 2023-11-08 10:12 UTC
### Preconditions and environment

- Adobe Commerce ver. 2.4.5-p5

### Steps to reproduce

Send a GET request to /V1/sharedCatalog/{id}/companies

### Expected result

Valid JSON response

[1234]

### Actual result

Response is an invalid JSON format (leading and trailing quotes encapsulating the JSON array)

"[\"1234"]"

### Additional information

![image](https://github.com/magento/magento2/assets/1254741/a72cf438-79bc-4d98-b7d9-d001a05c43bf)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-11-10 10:57
Hi @oefterdal,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance with EE edition and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

1. Send a GET request to /V1/sharedCatalog/{id}/companies


We are getting result as below :

<img width="1146" alt="Screenshot 2023-11-10 at 1 16 06 PM" src="https://github.com/magento/magento2/assets/51680745/d220c08e-aca3-4abd-bc59-40d221e81f11">



could you please let us know if we are missing anything.

Kindly recheck the behaviour on Magento 2.4-develop instance with EE edition and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-11-21 06:17
Hi @oefterdal,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38158#issuecomment-1805511701 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-11-29 05:39
Hi @oefterdal,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-11-29 05:39 UTC
Labels: Issue: needs update, Reported on 2.4.5-p5
