### ISSUE TITLE
Missing ID from form in Category Admin Save

### ISSUE THREAD

**Issue by markoweb** [magento/magento2#7583] opened 2016-11-28 08:36 UTC
### Preconditions
1. Magento 2.1.2. 

### Steps to reproduce
1. Go to Admin >> Products >> Categories 
2. Start debug, set breakpoint to:
`Magento\Catalog\Controller\Adminhtml\Category:34` (line 34)
3. Save category without any changes
4. Check variable $categoryId (on line 34)

### Expected result
1. Expected value of the $categoryId variable is current Category Id

### Actual result
1. Variable $categoryId contains value 0

### Consequent problem
Problem is that the category data and all descendant categories data are saved every time, even if no data was changed. The saving also triggers a url_rewrite on all descendants which in the rich layered category structure is causing a timeout problems.

**Comment by sevos1984** [comment] 2016-11-28 15:20
This is fixed in develop https://github.com/magento/magento2/commit/e1533b9c3c00e929f4306526d3c241b967a7f3ff. Internal ticket for 2.1 is MAGETWO-58433

**Comment by magento-engcom-team** [comment] 2017-10-17 11:30
@markoweb, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-17 11:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid
