### ISSUE TITLE
Can't use fragments for `related_products`, `upsell_products` or `crosssell_products` 

### ISSUE THREAD

**Issue by TimonVS** [magento/magento2#29769] opened 2020-08-27 09:42 UTC
### Preconditions (*)

1. Magento 2.4.0

### Steps to reproduce (*)

When trying to query `related_products`, `upsell_products` or `crosssell_products` on `ProductInterface` using a fragment `ProductCard`, the result has a `name` of `null`, and the price is 0 (for both max and min) for `upsell_products` and `crosssell_products` (the price is fine for `related_products`). When you inline the fragment in the query, the results contain the proper name and price for a product.

**Query**

```graphql
query product($urlKey: String!) {
  products(filter: {url_key: {eq: $urlKey}}) {
    items {
      ...ProductCard
      related_products {
        ...ProductCard
      }
      upsell_products {
        ...ProductCard
      }
      crosssell_products {
        ...ProductCard
      }
    }
  }
}

fragment ProductCard on ProductInterface {
  __typename
  id
  name
  url_key
  price_range {
    minimum_price {
      final_price {
        value
      }
    }
    maximum_price {
      final_price {
        value
      }
    }
  }
}
```

### Expected result (*)

You should be able to use a fragment for `related_products`, `upsell_products` and `crosssell_products`. The result should be the same as when you write it all out in the query.

### Actual result (*)

```json
{
  "data": {
    "products": {
      "items": [
        {
          "__typename": "ConfigurableProduct",
          "id": 1818,
          "name": "Breathe-Easy Tank",
          "url_key": "breathe-easy-tank",
          "price_range": {
            "minimum_price": {
              "final_price": {
                "value": 41.140001
              }
            },
            "maximum_price": {
              "final_price": {
                "value": 47.190001
              }
            }
          },
          "related_products": [
            {
              "__typename": "ConfigurableProduct",
              "id": 1418,
              "name": null,
              "url_key": null,
              "price_range": {
                "minimum_price": {
                  "final_price": {
                    "value": 33.880001
                  }
                },
                "maximum_price": {
                  "final_price": {
                    "value": 33.880001
                  }
                }
              }
            },
            {
              "__typename": "ConfigurableProduct",
              "id": 1482,
              "name": null,
              "url_key": null,
              "price_range": {
                "minimum_price": {
                  "final_price": {
                    "value": 50.820001
                  }
                },
                "maximum_price": {
                  "final_price": {
                    "value": 50.820001
                  }
                }
              }
            },
            {
              "__typename": "ConfigurableProduct",
              "id": 2016,
              "name": null,
              "url_key": null,
              "price_range": {
                "minimum_price": {
                  "final_price": {
                    "value": 53.240001
                  }
                },
                "maximum_price": {
                  "final_price": {
                    "value": 53.240001
                  }
                }
              }
            },
            {
              "__typename": "ConfigurableProduct",
              "id": 2023,
              "name": null,
              "url_key": null,
              "price_range": {
                "minimum_price": {
                  "final_price": {
                    "value": 48.400001
                  }
                },
                "maximum_price": {
                  "final_price": {
                    "value": 48.400001
                  }
                }
              }
            }
          ],
          "upsell_products": [
            {
              "__typename": "SimpleProduct",
              "id": 1,
              "name": null,
              "url_key": null,
              "price_range": {
                "minimum_price": {
                  "final_price": {
                    "value": 0
                  }
                },
                "maximum_price": {
                  "final_price": {
                    "value": 0
                  }
                }
              }
            },
            {
              "__typename": "SimpleProduct",
              "id": 16,
              "name": null,
              "url_key": null,
              "price_range": {
                "minimum_price": {
                  "final_price": {
                    "value": 0
                  }
                },
                "maximum_price": {
                  "final_price": {
                    "value": 0
                  }
                }
              }
            }
          ],
          "crosssell_products": [
            {
              "__typename": "SimpleProduct",
              "id": 16,
              "name": null,
              "url_key": null,
              "price_range": {
                "minimum_price": {
                  "final_price": {
                    "value": 0
                  }
                },
                "maximum_price": {
                  "final_price": {
                    "value": 0
                  }
                }
              }
            },
            {
              "__typename": "SimpleProduct",
              "id": 17,
              "name": null,
              "url_key": null,
              "price_range": {
                "minimum_price": {
                  "final_price": {
                    "value": 0
                  }
                },
                "maximum_price": {
                  "final_price": {
                    "value": 0
                  }
                }
              }
            },
            {
              "__typename": "SimpleProduct",
              "id": 21,
              "name": null,
              "url_key": null,
              "price_range": {
                "minimum_price": {
                  "final_price": {
                    "value": 0
                  }
                },
                "maximum_price": {
                  "final_price": {
                    "value": 0
                  }
                }
              }
            },
            {
              "__typename": "SimpleProduct",
              "id": 32,
              "name": null,
              "url_key": null,
              "price_range": {
                "minimum_price": {
                  "final_price": {
                    "value": 0
                  }
                },
                "maximum_price": {
                  "final_price": {
                    "value": 0
                  }
                }
              }
            }
          ]
        }
      ]
    }
  }
}
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mauragcyrus** [comment] 2020-10-13 16:46
Hi @TimonVS Please retest on 2.4.2 when it is available as this should be fixed.

**Comment by durexlovesex** [comment] 2020-11-08 23:55
@mauragcyrus please let us know when it's ready

**Comment by shikhamis11** [comment] 2021-01-25 15:16
this issue is reproducible on 2.4-develop instance.  
tried with query 

```
query product($urlKey: String!) {
  products(filter: {url_key: {eq: $urlKey}}) {
    items {
      ...ProductCard
      related_products {
        ...ProductCard
      }
      upsell_products {
        ...ProductCard
      }
      crosssell_products {
        ...ProductCard
      }
    }
  }
}

fragment ProductCard on ProductInterface {
  __typename
  id
  name
  url_key
  price_range {
    minimum_price {
      final_price {
        value
      }
    }
    maximum_price {
      final_price {
        value
      }
    }
  }
}
```
variable : {"urlKey":"stellar-solar-jacket"}
response 

```
{
  "data": {
    "products": {
      "items": [
        {
          "__typename": "ConfigurableProduct",
          "id": 1226,
          "name": "Stellar Solar Jacket",
          "url_key": "stellar-solar-jacket",
          "price_range": {
            "minimum_price": {
              "final_price": {
                "value": 75
              }
            },
            "maximum_price": {
              "final_price": {
                "value": 75
              }
            }
          },
          "related_products": [
            {
              "__typename": "ConfigurableProduct",
              "id": 1114,
              "name": null,
              "url_key": null,
              "price_range": {
                "minimum_price": {
                  "final_price": {
                    "value": 42
                  }
                },
                "maximum_price": {
                  "final_price": {
                    "value": 42
                  }
                }
              }
            },
            {
              "__typename": "ConfigurableProduct",
              "id": 1184,
              "name": null,
              "url_key": null,
              "price_range": {
                "minimum_price": {
                  "final_price": {
                    "value": 55
                  }
                },
                "maximum_price": {
                  "final_price": {
                    "value": 55
                  }
                }
              }
            },
            {
              "__typename": "ConfigurableProduct",
              "id": 1825,
              "name": null,
              "url_key": null,
              "price_range": {
                "minimum_price": {
                  "final_price": {
                    "value": 31.2
                  }
                },
                "maximum_price": {
                  "final_price": {
                    "value": 31.2
                  }
                }
              }
            },
            {
              "__typename": "ConfigurableProduct",
              "id": 1839,
              "name": null,
              "url_key": null,
              "price_range": {
                "minimum_price": {
                  "final_price": {
                    "value": 38.4
                  }
                },
                "maximum_price": {
                  "final_price": {
                    "value": 38.4
                  }
                }
              }
            }
          ],
          "upsell_products": [],
          "crosssell_products": [
            {
              "__typename": "SimpleProduct",
              "id": 18,
              "name": null,
              "url_key": null,
              "price_range": {
                "minimum_price": {
                  "final_price": {
                    "value": 0
                  }
                },
                "maximum_price": {
                  "final_price": {
                    "value": 0
                  }
                }
              }
            },
            {
              "__typename": "SimpleProduct",
              "id": 19,
              "name": null,
              "url_key": null,
              "price_range": {
                "minimum_price": {
                  "final_price": {
                    "value": 0
                  }
                },
                "maximum_price": {
                  "final_price": {
                    "value": 0
                  }
                }
              }
            },
            {
              "__typename": "SimpleProduct",
              "id": 21,
              "name": null,
              "url_key": null,
              "price_range": {
                "minimum_price": {
                  "final_price": {
                    "value": 0
                  }
                },
                "maximum_price": {
                  "final_price": {
                    "value": 0
                  }
                }
              }
            },
            {
              "__typename": "SimpleProduct",
              "id": 23,
              "name": null,
              "url_key": null,
              "price_range": {
                "minimum_price": {
                  "final_price": {
                    "value": 0
                  }
                },
                "maximum_price": {
                  "final_price": {
                    "value": 0
                  }
                }
              }
            }
          ]
        }
      ]
    }
  }
}
```

**Comment by ilnytskyi** [comment] 2021-12-30 14:16
faced same issue

**Comment by engcom-November** [comment] 2022-09-12 14:28
Verified the issue on Magento 2.4-develop branch and the issue is reproducible. Hence confirming the issue.
Response retrieved for "related_products" is working as expected but null values are retrieved for "upsell_products" and "crosssell_products"
![image](https://user-images.githubusercontent.com/60198231/189679855-a4225aa2-921a-4009-9cd8-11c1ead9bfa6.png)

**Comment by engcom-November** [comment] 2023-03-27 14:41
Hi @TimonVS ,
Development team is currently working on this issue.
Thank you.

**Closed as completed** 2023-05-22 14:28 UTC
Labels: Issue: Confirmed, Issue: Format is valid, Component: GraphQL, Reproduced on 2.4.x, Priority: P2, Project: GraphQL, PAP, Progress: done, Reported on 2.4.0, Area: Product
