### ISSUE TITLE
CreditHistory GraphQL query returns an error

### ISSUE THREAD

**Issue by cspruiell** [magento/magento2#29990] opened 2020-09-11 00:49 UTC
### Preconditions (*)

1. Magento version 2.4.1 is installed with B2B branch `https://github.com/magento/partners-magento2b2b/tree/28554_B2B_Company_Credit_Queries`
2. Store -> Configuration -> Sales -> Payment Methods: Payment on Account is enabled
3. Store -> Configuration -> General -> B2B Features: Enable Company and Enable Purchase Orders are set to true
4. Company A is created with the following settings:
    * Status: Active
    * Company Credit has a Credit Limit of $10000
    * Advanced Settings -> Applicable Payment Methods = All Enabled Payment Methods

### Steps to reproduce (*)

1. In Luma, as a customer of Company A, create a purchase order using Company Credit as the payment method
2. Execute the credit history query for the company:
```
{company
  {credit_history
    {
      items{amount{value} 
      balance{available_credit{value}} 
      updated_by{name} date}
    }
  }
}
```

### Expected result (*)

1. The credit history is returned with entries for the originally allocated amount and the purchased amount 

### Actual result (*)

1. Response contains an error message:
```
{
  "errors": [
    {
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 2,
          "column": 4
        }
      ],
      "path": [
        "company",
        "credit_history"
      ]
    }
  ],
  "data": {
    "company": null
  }
}
```
2. Server logs show the following error:
```
report.ERROR: Return value of Magento\CompanyCreditGraphQl\Model\Credit\OperationUser::getUserType() must be of the type string, bool returned {"exception":"[object] (GraphQL\\Error\\Error(code: 0): Return value of Magento\\CompanyCreditGraphQl\\Model\\Credit\\OperationUser::getUserType() must be of the type string, bool returned at /app/vendor/webonyx/graphql-php/src/Error/Error.php:174, TypeError(code: 0): Return value of Magento\\CompanyCreditGraphQl\\Model\\Credit\\OperationUser::getUserType() must be of the type string, bool returned at /app/vendor/magento/module-company-credit-graph-ql/Model/Credit/OperationUser.php:66)"} []
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dthampy** [comment] 2020-09-11 00:59
Please add test coverage for this bug fix. 
Please we need to make sure that the company{credit_history} only returns the credit history information of the company, to which the user is assigned to; not the credit history for all the companies that are available

**Comment by sasha19957099** [comment] 2020-10-19 09:48
@magento I am working on this

**Comment by sasha19957099** [comment] 2020-10-23 12:44
I couldn't reproduce it. Tried to purchase and query then by a company admin and a company user customer with proper permissions, results were correct. 
![image](https://user-images.githubusercontent.com/28062227/97004539-e131dc00-1545-11eb-97a5-082c9c3aa42e.png)

**Comment by mauragcyrus** [comment] 2020-11-09 19:29
@magento export issue to Jira project MCLOUD as Task

**Comment by mauragcyrus** [comment] 2020-11-09 22:00
@magento export issue to Jira project MCLOUD as Task

**Comment by magento-engcom-team** [comment] 2020-11-09 22:00
:x: Cannot export the issue. GitHub repo magento/magento2 is not supported in JIRA project MCLOUD and type Task.

**Comment by magento-engcom-team** [comment] 2020-11-09 22:00
:x: Cannot export the issue. GitHub repo magento/magento2 is not supported in JIRA project MCLOUD and type Task.

**Comment by magento-engcom-team** [comment] 2020-11-09 22:01
:x: Cannot export the issue. GitHub repo magento/magento2 is not supported in JIRA project MCLOUD and type Task.

**Comment by mauragcyrus** [comment] 2020-11-12 18:47
@magento export issue to Jira project MCLOUD as Task

**Comment by magento-engcom-team** [comment] 2020-11-12 18:47
:x: Cannot export the issue. GitHub repo magento/magento2 is not supported in JIRA project MCLOUD and type Task.

**Comment by magento-engcom-team** [comment] 2020-11-12 18:48
:x: Cannot export the issue. GitHub repo magento/magento2 is not supported in JIRA project MCLOUD and type Task.

**Comment by magento-engcom-team** [comment] 2020-11-12 18:48
:x: Cannot export the issue. GitHub repo magento/magento2 is not supported in JIRA project MCLOUD and type Task.

**Comment by mauragcyrus** [comment] 2020-11-12 21:00
@magento export issue to Jira project MCLOUD as Bug

**Comment by magento-engcom-team** [comment] 2020-11-12 21:00
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/MCLOUD-7271) is successfully created for this issue.

**Closed as completed** 2020-12-04 14:43 UTC
Labels: Issue: Format is valid, Priority: P1, Project: GraphQL, B2B: GraphQL, PAP, Progress: done
