### ISSUE TITLE
Vendor Module and Archive/Develop branch are differrent ?

### ISSUE THREAD

**Issue by quienti** [magento/magento2#3953] opened 2016-04-01 09:14 UTC
## Steps to reproduce
1. Upgrade from 2.0.2 from 2.0.4 with composer (Magento 2.0.2 is installed like this =>
   `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition <installation directory name>`
2. Look on develop branch here => `https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/view/frontend/web/js/view/payment.js#L56`
## Expected result
1. Same code
## Actual result
1. If I look in `MAGENTOFOLDER/vendor/magento/vendor/magento/module-checkout/view/frontend/web/js/view/payment.js`
   The js code is different compared from the `develop branch`
## More info
1. This is just an example, there are a lot of problem like this

**Comment by mazhalai** [comment] 2016-04-01 12:13
@quenti This is expected. Since 2.0.4 is only a patch version and what is in `develop` is WIP. Please check the version in [tag 2.0.4](https://github.com/magento/magento2/tree/2.0.4) and compare if it's the same.

Closing since this is not a bug.

**Closed as completed by mazhalai** 2016-04-01 12:13 UTC
