### ISSUE TITLE
FPC cache stopped working in Multi store Magento2.4.7-p1

### ISSUE THREAD

**Issue by anees-netable** [magento/magento2#38980] opened 2024-07-29 06:24 UTC
### Preconditions and environment

- Magento version: 2.4.7-p1
Create a multi store and add below configuration to nginx configuration

    fastcgi_param  MAGE_RUN_TYPE store;
    fastcgi_param  MAGE_RUN_CODE $MAGE_RUN_CODE;

FPC cache stopped working in default magento2.4.7-p1 with sample data

### Steps to reproduce

1) Install default magento2.4.7-p1 with sample data
2) Setup Multi store
3) Add below configuration to nginx conf file

`
    fastcgi_param  MAGE_RUN_TYPE store;
    fastcgi_param  MAGE_RUN_CODE $MAGE_RUN_CODE;
`

Try restarting the nginx 
Enable all caches and keep in developer mode to see the Cache headers

You will notice the 

`x-magento-cache-debug: MISS`

If you remove the Nginx config above configuration and restarts the FPC starts working again

Nginx

### Expected result

FPC Should work 
with below nginx configuration

    fastcgi_param  MAGE_RUN_TYPE store;
    fastcgi_param  MAGE_RUN_CODE $MAGE_RUN_CODE;the 

Should include below response headers

`x-magento-cache-debug: HIT`

### Actual result

Below are the Response headers shown on the homepage

`x-magento-cache-debug: MISS`

### Additional information

Magento2.4.7-p1 with PHP8.2-fpm and Nginx

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment] 2024-07-29 14:42
I belive this was reported before in:
- #38626
- #38930

See the discussion in https://github.com/magento/magento2/pull/38646 for how it was fixed (to be released in Magento 2.4.8)

**Comment by engcom-Hotel** [comment] 2024-07-30 08:40
Thanks @hostep for the related links!

We are closing this marking as a duplicate of https://github.com/magento/magento2/issues/38626. @anees-netable please refer to the below comment for commit links:

https://github.com/magento/magento2/issues/38626#issuecomment-2208196375

Thanks

**Closed as completed by engcom-Hotel** 2024-07-30 08:40 UTC
Labels: Triage: Dev.Experience, Issue: ready for confirmation, Reported on 2.4.7-p1
