### ISSUE TITLE
Admin forgot password email in wrong link

### ISSUE THREAD

**Issue by ronak-vaimo** [magento/magento2#36169] opened 2022-09-21 06:51 UTC
### Preconditions and environment

- Magento version 245
- Config web/url/use_store = 1

### Steps to reproduce

1. Set config web/url/use_store = 1 (Stores > Configuration > General > Web > Url Options > Add Store Code to Urls = Yes)
2. Clear cache
3. Go to admin login page and then click on **Forgot your password?**
4. Enter email and click on Retrieve Password
5. Check email in reset password link : http://domain.local.com/admin/admin/admin/auth/resetpassword/xxxxx
6. Link in extra admin 

### Expected result

Email in reset password link should be
http://domain.local.com/admin/admin/auth/resetpassword/xxxxx

### Actual result

Email in reset password link is
http://domain.local.com/admin/admin/admin/auth/resetpassword/xxxxx

### Additional information

**isUseStoreInUrl()** should be return false when admin reset password link generate.
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Store/Model/Store.php#L760

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ronak-vaimo** [comment] 2022-09-21 06:59
@magento give me 2.4-develop instance

**Comment by ronak-vaimo** [comment] 2022-09-21 07:07
Magento Instance in I can't test because mail not working.
Error : Unable to send mail. Please try again later.

**Comment by hostep** [comment] 2022-09-21 20:26
This was reported before: https://github.com/magento/magento2/issues/35667 and got confirmed yesterday, I think we should close this issue here as a duplicate?

**Comment by engcom-Bravo** [comment] 2022-09-22 11:20
Hi @ronak-vaimo,

Thanks for reporting and collaboration . Verified the issue on Magento 2.4-develop branch and the issue is reproducible with above steps to reproduce. however, similar issue has been confirmed [here](https://github.com/magento/magento2/issues/35667)


Hence we are closing this as a duplicate.


Thanks.

**Closed as completed by engcom-Bravo** 2022-09-22 11:20 UTC
Labels: duplicate, Issue: ready for confirmation
