### ISSUE TITLE
Empty attribute label is displayed on product page when other language used.

### ISSUE THREAD

**Issue by nowszy** [magento/magento2#10738] opened 2017-09-01 12:41 UTC
### Preconditions

1. Clean instance of Magento 2.1.8
2. Store displayed in some foreign languege i.e. pl_PL
3. Simple product with some attribute visible on product page.

### Steps to reproduce

1. Go to product page.
2. See attribute label ('none' translated to your foreign language) in the attributes section/

### Expected result

1. 'none' label translated to other languages i.e. polish lang - 'brak' should not be displayed
2. comparisson in line 37 of app/code/Magento/Catalog/view/frontend/templates/product/view/attribute.phtml is changed to if ($_attributeLabel != __('none')) in order to not display 'none' translated to foreign language

### Actual result

1. In the template app/code/Magento/Catalog/view/frontend/templates/product/view/attribute.phtml line 37 you have followin comparisson: if ($_attributeLabel != 'none') but at this part of code $_attributeLabel is already translated.

**Comment by korostii** [comment] 2017-09-07 12:31
FYI: This has been reported may times before: #9295, #9161, #9531,

**Comment by orlangur** [comment] 2017-09-11 14:21
Ok, so, there are (at least) two attempts to fix this issue. Both merged to `develop` and none to `2.1-develop`:

- https://github.com/magento/magento2/pull/6257
- https://github.com/magento/magento2/pull/10739

According to my understanding newer PR is a correct one (no reason to forbid "none" translation, valid scenario is described in this issue), thus it would be nice to revert #6257.

Thoughts? Cc: @vrann @miguelbalparda

**Comment by magento-engcom-team** [comment] 2017-09-19 19:26
@nowszy, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by magento-team** [comment] 2017-09-22 20:12
Internal ticket to track issue progress: MAGETWO-75315

**Comment by maksek** [comment] 2017-10-01 11:13
@orlangur, the more correct in 2.2-develop branch. Remove `translate="true"` from layout and do not translate "none" in template.

**Comment by orlangur** [comment] 2017-10-02 13:14
@maksek ok, thanks for sorting this out 👍

**Comment by magento-team** [comment] 2017-10-04 22:45
Internal ticket to track issue progress: MAGETWO-80884

**Comment by okorshenko** [comment] 2017-10-04 22:47
@nowszy thank you for your report. The issue is already fixed in 2.2-develop branch (PR: #11168  by @maksek ) and will be available in the Magento 2.2.2 release

**Closed as completed by okorshenko** 2017-10-04 22:47 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by magento-team** [comment] 2017-10-05 10:00
Internal ticket to track issue progress: MAGETWO-80770

**Comment by magento-engcom-team** [comment] 2018-02-12 19:35
Hi @nowszy. Thank you for your report. 
The issue has been fixed in magento/magento2#13532 by @hostep in 2.1-develop branch
Related commit(s):
 - 00f29c07cb08921009297594758da79d0850f05a

The fix will be available with the upcoming 2.1.13 release.
