### ISSUE TITLE
Having validationParams/additionalParams on a component forces all validations to run, even if disabled

### ISSUE THREAD

**Issue by palviggi-flagbit** [magento/magento2#32325] opened 2021-03-02 09:52 UTC
### Preconditions (*)

1. Failing on 2.4.2
2. Having the validationParams set on a component makes it run every validation, even if they are marked as false. In our case, a multi store installation has a date field in a form required in one and optional in the other

### Steps to reproduce (*)

we have the component defined in a LayoutProcessor with
```
[...]
'validation'       => [
       'required-entry'     => $dobAttr->isRequired(),
       'validate-date'  => true,
   ],
'validationParams' => ['dateFormat' => $this->getDateFormat(),],
[...]
```
It works as expected, with the component on one store as required-entry:false, and the other as required-entry:true. the required attribute is also set correctly on the input, so the red * for required field is shown as it correspond

### Expected result (*)

when completing the form, with the field empty, in one store it's required, in the other it's ok.
on the optional store, it should still validate correct date format when inputting data.

### Actual result (*)

When it should be optional (and on screen it's marked as optional) and left empty, a validation error about required field occurs.

### Workaround:
define the required-entry validation only on required, adding flow logic on php instead of simple data format.

### The error
The problem comes from 
https://github.com/magento/magento2/blob/45f27d64cbb475a4af4d27e14d312653823083e1/app/code/Magento/Ui/view/base/web/js/lib/validation/validator.js#L83

from the blame I see that the `|| additionalParams` validation at the end was [added for the date component](https://github.com/magento/magento2/commit/9e101a511176747229f213014d7450685d4d1263#diff-65b6a54093641f7b5652da1ae899da70b8ee79ff44f3464952945ece873b60daR71) in 2.1, but it affects everything else for no real gain on date element either (additionalParams is passed to the function always even if undefined) .
It should be removed to not affect other possibly disabled validations.

But also the whole condition is wrong, since `ruleParams = {validate: false}` is !== false, so it goes inside anyway. (error since 2.2)

A possibility could be 

```if (! (ruleParams === false || ! ruleParams.validate)) {```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by palviggi-flagbit** [comment] 2021-05-18 07:15
> Is this issue still relevant? 
Yes
> If so, what is blocking it? 
Nothing
> Is there anything you can do to help move it forward?
Look at it

**Comment by engcom-Alfa** [comment] 2021-06-02 14:13
Hi @palviggi-flagbit
Could you please elaborate the steps to reproduce it on frontend?

**Comment by palviggi-flagbit** [comment] 2021-06-02 14:21
mmm, this is from 3 months ago. I can search next week if I still have a POC around.

**Comment by engcom-Delta** [comment] 2021-06-22 13:23
Hi @palviggi-flagbit,
Thanks for updating the comments . Since no update from you from 20 days .Hence this ticket is closing.
Kindly request to log a new issue if required.

Thanks

**Comment by engcom-Delta** [comment] 2021-06-24 07:12
Since no update from you from 22 days .Hence this ticket is closing.

**Closed as completed** 2021-06-24 07:12 UTC
Labels: Issue: needs update
