### ISSUE TITLE
Admin Session Lifetime 

### ISSUE THREAD

**Issue by yumicom** [magento/magento2#9372] opened 2017-04-24 10:00 UTC
After upgrading to 2.1.6 Admin Session Lifetime 900 s only, custom time ignoring.
Configuration - Admin

**Comment by andimov** [comment] 2017-06-21 12:55
@yumicom 
Thanks for reporting. 
Please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by andimov** [comment] 2017-07-31 13:57
@yumicom 
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Closed as completed by andimov** 2017-07-31 13:57 UTC
Labels: Progress: needs update
