### ISSUE TITLE
Install stop at 87%or90%,use the master branch

### ISSUE THREAD

**Issue by lenkaren** [magento/magento2#2648] opened 2015-12-09 05:38 UTC
When install the magento2(select all),it stop at 90 % and the last Console Log is:

> Module 'Magento_ConfigurableSampleData':
> Installing data..

the max_execution_time in php.ini is 18000, I think it's ok. The system service was lnmp.

I uninstall magento2 and tried again
but this time it stop at 87%

> Module 'Magento_CatalogSampleData':
> Installing data.. 

I check the var/logs/debug.log,get a long list,like behind:

`[2015-12-09 05:13:49] main.DEBUG: cache_invalidate:  {"method":"POST","url":"http://xxx(ip_address)/setup/index.php/install/start","invalidateInfo":{"tags":{"0":"catalog_category_3","1":"catalog_category_4","6":"catalog_category_7","17":"catalog_category_8","77":"catalog_category_5","167":"catalog_category_6","210":"catalog_category"},"mode":"matchingAnyTag"},"is_exception":false} []
[2015-12-09 05:13:49] main.DEBUG: cache_invalidate:  {"method":"POST","url":"http://xxx(ip_address)/setup/index.php/install/start","invalidateInfo":{"tags":{"0":"catalog_product_43","1":"catalog_category_product_3","2":"catalog_category_product_6","5":"catalog_product","6":"catalog_category_product"},"mode":"matchingAnyTag"},"is_exception":false} []`

and so on.

I have to install the sampledata with magento2....but I don't konw how to do now.Please help.

**Comment by rajeshmukkala** [comment] 2015-12-09 10:18
same thing happened to me twice yesterday in wizard mode. I used CLI method to import which also failed but resumed from failed point on running 2nd time. 

http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-install.html

**Comment by mazhalai** [comment] 2015-12-10 15:10
@lenkaren @rajeshmukkala Please check your `max_execution_times` it should be set to 18000. Sometimes, this is set, but maybe server is not loading the php.ini correctly. Please verify using a `phpinfo()` check

**Comment by christopherdarling** [comment] 2015-12-16 12:16
I initially had this issue but added a custom php.ini as the .htaccess php_value wasn't working, the installer got to 90% but failed with this in the system.log

```
[2015-12-16 12:12:36] main.ERROR: Sample Data error: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`puredog_magento2`.`catalog_eav_attribute`, CONSTRAINT `CATALOG_EAV_ATTRIBUTE_ATTRIBUTE_ID_EAV_ATTRIBUTE_ATTRIBUTE_ID` FOREIGN KEY (`attribute_id`) REFERENCES `eav_attribute` (`attribute_id`) ), query was: INSERT INTO `catalog_eav_attribute` (`attribute_id`, `frontend_input_renderer`, `is_global`, `is_visible`, `is_searchable`, `is_filterable`, `is_comparable`, `is_visible_on_front`, `is_html_allowed_on_front`, `is_used_for_price_rules`, `is_filterable_in_search`, `used_in_product_listing`, `used_for_sort_by`, `apply_to`, `is_visible_in_advanced_search`, `position`, `is_wysiwyg_enabled`, `is_used_for_promo_rules`, `is_required_in_admin_store`, `is_used_in_grid`, `is_visible_in_grid`, `is_filterable_in_grid`, `search_weight`, `additional_data`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [] []
[2015-12-16 12:12:37] main.ERROR: Sample Data error: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`puredog_magento2`.`catalog_product_entity`, CONSTRAINT `CAT_PRD_ENTT_ATTR_SET_ID_EAV_ATTR_SET_ATTR_SET_ID` FOREIGN KEY (`attribute_set_id`) REFERENCES `eav_attribute_set` (`attribute_set_id`)), query was: INSERT INTO `catalog_product_entity` (`attribute_set_id`, `type_id`, `sku`, `has_options`, `required_options`, `created_at`, `updated_at`) VALUES (?, ?, ?, ?, ?, '2015-12-16 12:12:37', '2015-12-16 12:12:37') [] []
```

**Comment by mazhalai** [comment] 2015-12-16 13:02
@christopherdarling Did you have a previous installation with sample data? I would suggest cleaning your database and trying again.

**Comment by christopherdarling** [comment] 2015-12-16 15:12
Yeah, we did... dropped the db and re-created it though...

**Comment by mazhalai** [comment] 2015-12-16 15:23
@christopherdarling We havent seen this issue before, so can you help us reproduce it? What steps did you follow? How are you deploying magento2? Via zip from magento.com, using git clone, or composer create project? How did you deploy sample data?

**Comment by christopherdarling** [comment] 2015-12-16 15:28
I had deployed Magento onto a Vagrant box (apache2, php5.6, MariaDB 10), an
extract of the zip (with sample data).  Let me know if you want me to try
anything...

**Comment by daim2k5** [comment] 2016-01-30 23:32
@christopherdarling can you try again install m2 with sample data?

**Comment by eliv3n** [comment] 2016-02-12 08:58
exact same error, any updates?

**Comment by mazhalai** [comment] 2016-02-12 17:20
@eliv3n have you tried [this](https://github.com/magento/magento2/issues/2648#issuecomment-163653600)

**Comment by eliv3n** [comment] 2016-02-12 18:39
@mazhalai Yes i did try everything. exact same issue with @sky4git at [this link](https://github.com/magento/magento2/issues/2400)
at first the installations stuck at 70%, after I changed the `max_execution_times` to 18000 then it stuck at 97% - 98%. I keep repeat the installation with no luck.
I had this issue for few days and and try every possible method i read on the internet.
finally NOW I successfully installed the script.
I am not sure what i did to make it work. i will be able to provide the logs if you require.

**Comment by mazhalai** [comment] 2016-04-11 16:19
@lanken has your issue been resolved?

**Comment by eliv3n** [comment] 2016-04-12 03:41
Yes,
This solution worked for me,
I changed the database drive to a SSD hard drive to optimize the speed for installation, the installation progress become much faster and the error will not show anymore.

**Comment by sky4git** [comment] 2016-04-18 23:25
Yes its fixed. I needed faster server to finish this process.

**Comment by ajahongir** [comment] 2016-04-21 12:35
I had same issue. I went to `/var/log/apache2/error.log` and saw that was an error - `"Maximum execution time of 30 seconds exceeded in..."`.

solution:
go to your system shell and type this command

`sh# find / -name "php.ini"`
should give you next lines (it could variate depending on your linux distribution)

`/etc/php5/cli/php.ini
/etc/php5/apache2/php.ini`

I opened `/etc/php5/apache2/php.ini` and set `max_execution_time` to `18000`
also increased memory limit

restart your apache server:
`service apache2 restart`

good luck :)

**Comment by mazhalai** [comment] 2016-05-09 19:09
@lenkaren closing due to non-responsiveness.

**Closed as completed by mazhalai** 2016-05-09 19:09 UTC
Labels: Progress: needs update
