### ISSUE TITLE
Cron Job not running - Cpanel 

### ISSUE THREAD

**Issue by dv8nate** [magento/magento2#4653] opened 2016-05-24 00:12 UTC
## Steps to reproduce

I have searched Stack with no luck, I have come from Magento 1 where you could index from the admin to Magento 2.0.6 where you have to run cron jobs.

I have a fresh install on a CentOS 6.6 with Cpanel. Running php 7.

I have put up about 150 products so far, however, I have reached a point they are no longer appearing on my site. I believe this is due to my cron jobs aren't running.

The jobs I have tried via the Cpanel are as follows.
## Expected result

reindexing occurs
## Actual result

This set of jobs gives no errors, however no reindexing occurs

2016-05-21 15:14:03 Ran jobs by schedule. 2016-05-21 15:15:04 Ran jobs by schedule. 2016-05-21 15:16:03 Ran jobs by schedule. 2016-05-21 15:17:03 Ran jobs by schedule. 2016-05-21 15:18:03 Ran jobs by schedule. 2016-05-21 15:19:02 Ran jobs by schedule. 2016-05-21 15:20:03 Ran jobs by schedule. 2016-05-21 15:21:02 Ran jobs by schedule. 2016-05-21 15:22:03 Ran jobs by schedule. 2016-05-21 15:23:03 Ran jobs by schedule. 2016-05-21 15:24:03 Ran jobs by schedule. 2016-05-21 15:25:03 Ran jobs by schedule.

*/1 \* \* \* \* /usr/local/bin/php /home/downupne/public_html/bin/magento cron:run | awk '{ print strftime("\%Y-\%m-\%d \%H:\%M:\%S"), $0; fflush(); }' 2>&1 >> ~/magento_cron.log

*/1 \* \* \* \* /usr/local/bin/php /home/downupne/public_html/update/cron.php | awk '{ print strftime("\%Y-\%m-\%d \%H:\%M:\%S"), $0; fflush(); }' 2>&1 >> ~/magento_cron.log

*/1 \* \* \* \* /usr/local/bin/php /home/downupne/public_html/bin/magento setup:cron:run | awk '{ print strftime("\%Y-\%m-\%d \%H:\%M:\%S"), $0; fflush(); }' 2>&1 >> ~/magento_cron.log
# 

This set of jobs nothing happens in the log

*/1 \* \* \* \* /usr/bin/php -c /etc/php5/apache2/php.ini /var/www/magento2/bin/magento cron:run | grep -v "Ran jobs by schedule" >> /var/www/magento2/var/log/magento_cron.log

*/1 \* \* \* \* /usr/bin/php -c /etc/php5/apache2/php.ini /var/www/magento2/update/cron.php >> /var/www/magento2/var/log/update_cron.log

*/1 \* \* \* \* /usr/bin/php -c /etc/php5/apache2/php.ini /var/www/magento2/bin/magento setup:cron:run >> /var/www/magento2/var/log/setup_cron.log

Any advise would be greatly appreciated.

Regards

Nathan

**Comment by adifucan** [comment] 2016-07-07 10:05
Hi @dv8nate, did you try to run magento indexer:reindex command after magento cron:run?
It probably should solve your issue.
Please, check this reference: https://github.com/magento/magento2/issues/3247

**Comment by pitangaweb** [comment] 2016-09-29 21:49
Running magento indexer:reindex invalidates Full Page cache every time, so I cannot consider this as a fix to this issue.

**Comment by SyedMuneebb** [comment] 2017-06-21 07:39
Checkout this guide to understand about Cron: [Cron Job Magento 2](https://magenticians.com/setup-cron-job-magento-2/)

**Comment by magento-engcom-team** [comment] 2017-09-20 23:13
@dv8nate, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 23:13 UTC
Labels: bug report, Fixed in 2.2.x, Issue: Format is not valid
