### ISSUE TITLE
Magento 2.7 and 2.1.1 - While changing the password form the my account page User group changed to default customer group

### ISSUE THREAD

**Issue by thirumoorthyp** [magento/magento2#6787] opened 2016-09-28 09:17 UTC
While changing the password from the my account page user group changed to default customer group. For example : 1) I have created Customer group named "XXXX Group" 2) I have created a user with "XXXX Group" from admin panel. 3) When i change the password from the my account change password section, the current user group has been assigned to default User group.

Note:
I have checked both the versions 2.0.7 and 2.1.1, which facing the same issue.

kindly provide the solution

Expectation: When i change the password, user must be assigned to expected "XXXX Group"

**Comment by veloraven** [comment] 2016-09-29 12:00
@thirumoorthyp thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. 
Does step 3 relates to action from frontend from customer's 'My Account'? It seems to be so from description but not clear.
Please also update the title with correct Magento version. It should be 2.0.7 instead of 2.7.

**Comment by thirumoorthyp** [comment] 2016-10-11 05:19
While changing the password from the my account page user group changed to default customer group. 

### Preconditions
1. Magento CE 2.07 version installed. 

### Steps to reproduce
1. I have created Customer group named "XXXX Group" 
2. I have created a user with "XXXX Group" from admin panel. 
3.  When i change the password from the my account change password section(frontend), the current user group has been assigned to default User group(general).

Expected result:

The user remains in "XXXX Group"

Actual result:

The user changes to default user group

**Comment by sevos1984** [comment] 2016-10-12 09:30
This should be fixed in 2.09, please update your codebase

**Comment by thirumoorthyp** [comment] 2016-10-12 13:01
@sevos1984: Thanks for the reply. <br/> But I have checked in 2.1.1 version also, this issue exist

**Comment by ghost** [comment] 2016-10-14 09:52
This issue also still exists in Magento 2.1.2

**Comment by sevos1984** [comment] 2016-10-20 09:57
I can't reproduce this on clear magento install, need more detailed steps.

**Comment by ghost** [comment] 2016-10-20 12:10
Hi @sevos1984 Below are the steps to reproduce.

**Preconditions**
1. Magento CE 2.1.2 without sample data is installed.

**Steps to reproduce**
1. Register new user by creating a new account (/customer/account/create/)
2. Go to the admin panel and change the usergroup from the registered user from general to retailer and save the changes
3. Login at storefront with newly created user
4. After login go to the edit account page at the dashboard. (/customer/account/edit/)
5. Change the last name and save changes

**Expected result:**
The user remains in retailer group

**Actual result:**
The user changes to general user group

**Comment by sevos1984** [comment] 2016-10-21 08:40
Thanks, I found ticket for this problem MAGETWO-58335 it will be soon delivered.

**Comment by josecruzchavez** [comment] 2016-11-30 17:31
But I have checked in 2.1.0 version also, this issue exist

**Comment by ghost** [comment] 2016-12-01 07:48
Hi @sevos1984: Any ETA when this problem will be resolved?

**Comment by magento-engcom-team** [comment] 2017-09-20 22:35
@thirumoorthyp, thank you for your report.
The issue is already fixed in 2.1.3

**Closed as completed by magento-engcom-team** 2017-09-20 22:35 UTC
Labels: Issue: Ready for Work, bug report, Component: Customer, Fixed in 2.1.x, Issue: Format is not valid

**Comment by bojandavkov** [comment] 2020-05-29 14:32
I have managed to reproduce this on the latest 2.3.5 version
