### ISSUE TITLE
Use of undefined constant GLOB_BRACE in dependency "allure-framework/allure-phpunit"

### ISSUE THREAD

**Issue by Flyingmana** [magento/magento2#24635] opened 2019-09-18 08:26 UTC
### Preconditions (*)
Magento Version: 2.3.2

### Steps to reproduce (*)

`./bin/magento dev:test:run unit`

### Expected result (*)
No PHP Warnings

### Actual result (*)

several:
```
Warning: Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE' (this will throw an Error in a future version of PHP) in /var/www/html/src/vendor/allure-framework/allure-phpunit/src/Yandex/Allure/Adapter/AllureAdapter.php:74.
```

### Related Informations

Problem is, GLOB_BRACE is not available in alle Unix Systems.
For example the often in Docker context used "Alpine" 
https://github.com/docker-library/php/issues/719

There is an (not merged) upstream PullRequest available in https://github.com/allure-framework/allure-phpunit/pull/44
But I did not check yet, if this is the proper solution.

**Comment by engcom-Charlie** [comment] 2019-09-18 13:12
Hello @Flyingmana ! 
Could you show me where(
outside the vendor) Magento uses `GLOB_BRACE` constant?

**Comment by engcom-Charlie** [comment] 2019-10-02 09:12
I am closing this issue now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by ksaho2** [comment] 2019-10-28 04:55
For future reference here is a solution:
vendor/allure-framework/allure-phpunit/src/Yandex/Allure/Adapter/AllureAdapter.php@74
```
//            $files = glob($outputDirectory . DIRECTORY_SEPARATOR . '{,.}*', GLOB_BRACE);
//            foreach ($files as $file) {
//                if (is_file($file)) {
//                    unlink($file);
//                }
//            }
```

Comment out this code, or replace it with:
```
$directoryPath = $outputDirectory . DIRECTORY_SEPARATOR;
$dir = scandir($directoryPath);
$rel = ['.', '..'];
$files = array_diff($dir, $rel);

foreach ($files as $file) {
    $path = $directoryPath . $file;
    if (is_file($path)) {
        unlink($path);
    }
}
```

**Comment by duhon** [comment] 2019-11-11 20:51
The solution to the problem is the pull request https://github.com/allure-framework/allure-phpunit/pull/44 which the author may accept

**Comment by Flyingmana** [comment] 2019-11-11 22:29
@engcom-Charlie its indirectly used by for example in https://github.com/magento/magento2/blob/c4fb1ee447862966afcf4115eb3e65ef8579d04d/dev/tests/static/phpunit-all.xml.dist#L27

**Comment by engcom-Charlie** [comment] 2019-11-12 15:30
@Flyingmana since this problem is related to Allure, we can just wait when PR https://github.com/allure-framework/allure-phpunit/pull/44#issue-312713152 will be confirmed. 
We hope the fix will be merged in the next Magento release(2.3.4).

**Comment by Flyingmana** [comment] 2019-11-12 16:01
@engcom-Charlie thats not completely right.
As a good OpenSource User, you can also test the solution, communicate them that it works, and encourage them to merge it, because it is a part, which affects your own Users.

Usually its a good and helpfull thing for maintainers, to hear this also from the bigger users of an open source library/tool.

**Comment by fredden** [comment] 2019-12-17 00:26
Upstream have released version 1.3.1, which includes this fix: https://github.com/allure-framework/allure-phpunit/pull/44#issuecomment-563175882
It looks like there's a dependency chain preventing this upgrade however:
* `allure-framework/allure-phpunit 1.3.1` requires `phpunit/phpunit >=7.0.0`
* `codeception/phpunit-wrapper 6.7.0` requires `phpunit/phpunit >=6.5.13 <7.0`
* `codeception/codeception 2.4.5` requires `codeception/phpunit-wrapper ^6.0.9|^7.0.6`
* `allure-framework/allure-codeception 1.3.0` requires `codeception/codeception ~2.1`
* `magento/magento2-functional-testing-framework 2.5.4` requires `allure-framework/allure-codeception ~1.3.0`
* No suitable versions of `magento/magento2-functional-testing-framework` currently available.

(Reopening as this clearly isn't solved yet.)

**Comment by amenk** [comment] 2020-07-28 09:21
@Flyingmana I searched for GLOB_BRACE in the Magento 2.3.4 code and it is used many times, even at quite important places:
`\Magento\Framework\App\Utility\Files::getDiConfigs`

                Glob::glob($moduleDir . '/etc/{di,*/di}.xml', Glob::GLOB_BRACE)

I think that means Magento might not run properly at all on Alpine based PHP images?

So is the problem maybe bigger than expected?

**Comment by engcom-Delta** [comment] 2020-10-23 07:02
Hi @fredden I'm not able to reproduce initial issue on clean 2.4-develop.
**Result:**
`bin/magento dev:test:run unit` runs without errors
![image](https://user-images.githubusercontent.com/51681379/96966466-846afd00-1516-11eb-8edc-ef17c4c5d9dd.png)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Comment by amenk** [comment] 2020-10-23 07:04
@engcom-Delta did you run it in the official php docker container based on alpine?

**Comment by fredden** [comment] 2020-10-23 09:26
No, this is not yet resolved.
https://github.com/magento/magento2/blob/a1e5689cc6092e40e1ebb975f4eaae32c4d8d1e5/composer.lock#L5983-L5984

I don't seem to have a 'reopen' button; @engcom-Delta please can you re-open this issue.

**Comment by fredden** [comment] 2020-10-23 09:30
I also note that `GLOB_BRACE` is used in https://github.com/magento/magento-composer-installer/blob/8b6c32f53b4944a5d6656e86344cd0f9784709a1/src/MagentoHackathon/Composer/Magento/Deploystrategy/DeploystrategyAbstract.php#L337 as required by https://github.com/magento/magento2/blob/a1e5689cc6092e40e1ebb975f4eaae32c4d8d1e5/composer.lock#L3365-L3366 however this is out of scope for this issue.

**Comment by fredden** [comment] 2020-11-16 22:55
@engcom-Delta please re-open this.

**Comment by engcom-Delta** [comment] 2020-11-18 06:45
@fredden  @amenk  Could you provide additional steps to reproduce this issue? Is it reproducible on alpine with php7.4 without any additional configuration? What magento version do you use?

**Comment by AngelsDustz** [comment] 2020-11-18 09:56
This issue is still affecting Magento 2, both 2.4.1 and 2.4-develop.

In order to reproduce you have to:

1. Create a new magento installation
2. Run `bin/magento setup:install`
3. Configure integration tests in `dev/tests/integration`
4. Run `bin/magento dev:tests:run`

At the end of the tests you will see:

`Warning: Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE' (this will throw an Error in a future version of PHP) in /home/user/Projects/projetname/vendor/allure-framework/allure-phpunit/src/Yandex/Allure/Adapter/AllureAdapter.php:74.`

Testing with alpine php 7.4, I believe this issue was resolved in a later version of `allure-framework/allure-phpunit` as I could not find references to `GLOB_BRACE` in the latest version of that repository.

**Comment by fredden** [comment] 2020-11-23 21:51
To reproduce using Docker:
```sh
git clone --depth=1 https://github.com/magento/magento2.git
docker run --rm -it -v "$PWD"/magento2:/var/www/html php:7.4-fpm-alpine sh
# Then inside the container:
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php composer-setup.php
php composer.phar install --ignore-platform-reqs
php -d memory_limit=-1 vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist
```
This shows the error:
> Warning: Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE' (this will throw an Error in a future version of PHP) in /var/www/html/vendor/allure-framework/allure-phpunit/src/Yandex/Allure/Adapter/AllureAdapter.php:74.

To fix, `allure-framework/allure-phpunit` should be upgraded to at least 1.3.1. This is an eventual dependency of `magento/magento2-functional-testing-framework`. See https://github.com/magento/magento2/issues/24635#issuecomment-566314746.

It's worth noting this isn't the only use of `GLOB_BRACE` within the codebase/dependency tree, but this is the instance that's the topic of this issue.

**Closed as completed** 2021-04-28 08:27 UTC
Labels: Priority: P1, Severity: S3, Progress: done, Issue: ready for confirmation
