### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by ketankulkarni** [magento/magento2#6482] opened 2016-09-03 11:27 UTC
while installing magento 2 following error occures
![error](https://cloud.githubusercontent.com/assets/20577851/18224561/4edf1930-71f7-11e6-8096-f54ed0c2c0a0.jpg)

**Comment by ihor-sviziev** [comment] 2016-09-03 12:11
@ketankulkarni there is too small amount information.
1. Which magento version did you tried to install?
2. How did you installed magento? (git clone, download zip, composer install)
3. Which version of php and which extensions installed?

**Comment by ketankulkarni** [comment] 2016-09-03 12:52
magento version -2.1.0
downloded by zip
php version 5.6

**Comment by andimov** [comment] 2016-09-05 11:00
@ketankulkarni
Thanks for reporting.
This looks like an environment issue. Please re-check your env with [Installation Guide](http://devdocs.magento.com/guides/v2.1/install-gde/install-quick-ref.html)
Also you need to format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by voleye** [comment] 2016-09-22 09:19
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by voleye** 2016-09-22 09:19 UTC
Labels: Progress: needs update
