### ISSUE TITLE
Layered Navigation not working with "Display Out of Stock Products" set to "Yes"

### ISSUE THREAD

**Issue by bckpff** [magento/magento2#36377] opened 2022-10-27 08:12 UTC
### Preconditions and environment

Affected Versions:
- 2.4.4
- 2.4.5
- 2.4.5-p1

Theme: Luma
Sample Data enabled

### Steps to reproduce

 - Setup a fresh Magento installation
 - Got to Stores -> Configuration -> Inventory -> Stock Options
 - Set  "Display Out of Stock Products" to "Yes"
 - In storefront navigate to Gear -> Bags
 - Open "Style" Filter dropdown
 - See option Backpack (4)
 - Click option Backpack (4)
 

### Expected result

- Filter is applied correctly and only 4 Bags are shown
- Pagination is working
- Total number of products is correct
- Filter options are reduced to correct values for the product set
- Remaining filter options show correct product count

### Actual result

- The filter is not applied
- The result set Shows "14 products"
- The pagination is not shown
- If you set "show 24 per page" all products are shown

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by madhippieqq** [comment] 2022-10-27 08:13
@magento give me 2.4-develop instance

**Comment by bckpff** [comment] 2022-10-27 08:19
@magento I am working on this

**Comment by bckpff** [comment] 2022-10-27 08:20
@magento give me 2.4.5-p1 instance

**Comment by bckpff** [comment] 2022-10-27 08:26
Using a vanilla 2.4-develop instance the issue seems mostly fixed: 
The filters are applied as expected, but the total number of results still shows 14 instead of 4.

Using a vanilla 2.4.5-p1 installation the issue is reproducible using the steps described above

**Comment by bckpff** [comment] 2022-10-27 10:09
The partial fix for this bug is found in `\Magento\Elasticsearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplier::categoryProductByCustomSortOrder`

In line 233

```
...
$productIds = [];

foreach ($this->searchResult->getItems() as $item) {
    $productIds[] = $item->getId();
}
...
```

**Comment by engcom-November** [comment] 2022-11-02 18:07
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-11-02 18:20
hi @bckpff ,
Thank you for reporting and collaboration. This issue is a duplicate of https://github.com/magento/magento2/issues/35899 and got fixed in the scope of the internal Jira ticket AC-6395 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-6395&type=commits
Based on the Jira ticket, the target version is 2.4.6. Hence we are closing this issue.
Thank you.

**Closed as completed by engcom-November** 2022-11-02 18:20 UTC
Labels: duplicate, Issue: ready for confirmation
