### ISSUE TITLE
Some languages don't show in admin locale selectbox

### ISSUE THREAD

**Issue by HirokazuNishi** [magento/magento2#1121] opened 2015-03-24 15:52 UTC
Hi,

I installed latest Dev RC, and found this bug.
Some languages like Japanse, Korean and Chinese are not displayed in admin locale selection.
Please see attached image.

Also, these empty labeled languages don't show up bottom language switcher.

My environment is,

+ Google Chrome
+ MaxOS X 10.10.2
+ Apache 2.2.27
+ PHP 5.5.15
+ MySQL 5.6.20

![empty-localename](https://cloud.githubusercontent.com/assets/124136/6805903/ed7f6ea6-d288-11e4-88d9-4434b23cdaca.png)

**Comment by mazhalai** [comment] 2015-03-24 20:54
@HirokazuNishi Can you clear your browser cache and cache within the `var` folder an try again?

**Comment by HirokazuNishi** [comment] 2015-03-24 23:02
I tested with others ( safari, firefox ), but all of them were same. 
I reported same issue on Magento 1.x at two or tree years ago.

**Comment by mazhalai** [comment] 2015-03-25 00:06
@HirokazuNishi what version of magento did you install?

**Comment by HirokazuNishi** [comment] 2015-03-25 00:06
I investigated more deeper, and found this bug caused by htmlspecialchars function.
As you know, this function requires 3rd parameter (charset) after PHP version 5.4. But if illegal UTF-8 characters are given it, it automatically returns empty string.

**Comment by HirokazuNishi** [comment] 2015-03-25 00:09
@mazhalai I installed 0.74.0-beta1.

**Comment by piotrekkaminski** [comment] 2015-10-02 18:00
Internal issue: MAGETWO-43616

**Comment by mazhalai** [comment] 2016-01-22 16:16
@HirokazuNishi it has been a while since you reported this issue. we haven't been able to reproduce this issue, so closing it. Please open a new ticket if you continue to have problems.

**Closed by mazhalai** 2016-01-22 16:16 UTC
Labels: bug, PS
