### ISSUE TITLE
Magento 242 system config not work correctly

### ISSUE THREAD

**Issue by nhatlich994** [magento/magento2#32538] opened 2021-03-18 05:25 UTC
Please correct me if i am wrong.

### Preconditions (*)
1. Magento v2.4.2

### Steps to reproduce (*)
1. I have created a config following code:

```
<section id="test_config" translate="label" type="text" sortOrder="100" showInDefault="1" showInWebsite="1" showInStore="1">
    <label>Test Config</label>
    <tab>psydog</tab>
    <resource>Psydog_SystemConfig::config</resource>
    <group id="general" translate="label" type="text" sortOrder="10" showInDefault="1" showInWebsite="1"
           showInStore="1">
        <label>General</label>
        <field id="enable" translate="label" type="select" sortOrder="0" showInDefault="1" showInWebsite="0"
               showInStore="0">
            <label>Enable</label>
            <comment><![CDATA[Version 1.0.0]]></comment>
            <source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
        </field>
        <field id="country" translate="label" type="multiselect" sortOrder="13" showInDefault="0"
               showInWebsite="1" showInStore="1">
            <label>Config country</label>
            <source_model>Magento\Directory\Model\Config\Source\Country</source_model>
            <can_be_empty>1</can_be_empty>
            <comment>Hold Ctrl when choosing multiple options</comment>
            <depends>
                <field id="*/*/enable">1</field>
            </depends>
        </field>
    </group>
</section>
```

2. As you see, **Enable** config is only in default, **Country** config is in website and store.
3. I wish country depend on **Enable** config, that means, if **Enable** = yes then show **Country** config. But it did not
4. I set **Enable** = Yes and go specific store (ex: Us), there is no config showed, it showed blank page
### Expected result (*)
As i know, default scope is applied to all store view, so i expected the **Country** is showed in store view scope.

### Actual result (*)
Demo issue: https://imgur.com/szfvXOt (gif image, please click to see demo)

**Comment by engcom-Bravo** [comment] 2021-06-15 09:42
Hi @psydog-1101 ,

We are unable to reproduce this. Please add more details if you are facing this in a specific scenario. Screenshot added for reference.

![image](https://user-images.githubusercontent.com/51680745/122031113-041e4280-cdec-11eb-9027-2633ba3313b0.png)

**Comment by engcom-Bravo** [comment] 2021-06-29 12:58
Hi @psydog-1101 ,

As we have not heard from you on our last comment, we are closing this issue. Please raise a new ticket if the issue still exists.

Thanks

**Closed as completed by engcom-Bravo** 2021-06-29 12:58 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.2
