### ISSUE TITLE
More permissions are needed to save this item on Magento EE 2.4.7p2

### ISSUE THREAD

**Issue by mpnghiatt** [magento/magento2#39181] opened 2024-09-18 08:07 UTC
### Preconditions and environment

- Magento EE 2.4.7p2
- php 8.3

### Steps to reproduce

1. Create multiple website
2. Create an admin role with 1 website and assign an admin account for this role
![image](https://github.com/user-attachments/assets/a92692ca-f85c-4b52-a17c-12ae442d3f17)
3. Login that admin account to create a Page/Block
4. Save edit or Delete this Page/Block with the Store View is the same as your role
You can see the error message
![image](https://github.com/user-attachments/assets/0ac6460c-b8bd-4e6c-9601-8ba184c9a536)

### Expected result

The Page/Block can save edit or delete successfully with the storeview the same as role condition

### Actual result

Can't save edit or deleteMore permissions are needed to save this item.

### Triage and priority

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-09-18 11:07
Hi @nghiatt01,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance with EE edition and the issue is not reproducible.Kindly refer the attached video.

<img width="1434" alt="Screenshot 2024-09-18 at 15 32 21" src="https://github.com/user-attachments/assets/aab5a21b-658c-45cf-a6db-bdfc32ac4fac">



https://github.com/user-attachments/assets/5459805f-a232-4496-890a-7cb133af5d74



Kindly recheck the issue in Latest 2.4-develop instance with EE edition and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by nghiatt01** [comment] 2024-09-19 02:18
@engcom-Bravo Thank you for your work. As I mentioned above, the issue occurs when editing -> saving or deleting a page/block. However, your video is about creating a new one. Please try again, thank you

**Comment by engcom-Bravo** [comment] 2024-09-19 07:23
Hi @nghiatt01,

Thanks for your update.

We have verified the issue in Latest 2.4-develop instance with EE edition and the issue is not reproducible.Kindly refer the attached video.



https://github.com/user-attachments/assets/8f77776d-0cac-44dc-8c5a-55e217fb1326







We are able to save and delete the Block.


Kindly recheck the issue in Latest 2.4-develop instance with EE edition and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by nghiatt01** [comment] 2024-09-19 09:29
@engcom-Bravo Thank you for your work. 
Please let me know where can I check source code of 2.4-develop EE version

**Comment by engcom-Bravo** [comment] 2024-09-26 07:48
Hi @nghiatt01,

Thanks for your Update.

The source code os 2.4-develop EE is only accessible for internal team members.since the issue is no more reproducible in Latest 2.4-develop with EE we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-09-26 07:48 UTC
Labels: Issue: needs update, Reported on 2.4.7-p2
