### ISSUE TITLE
Persistent shopping cart allow to use restricted coupons for not logged in users

### ISSUE THREAD

**Issue by msiewierska** [magento/magento2#31921] opened 2021-02-01 12:56 UTC
### Preconditions (*)

1. Magento 2.4.1
2. Enabled Persistent Shopping Cart

### Steps to reproduce (*)

1. In _Marketing -> Cart Price Rules_ add a coupon that applies only for logged in user (General customer group), for example 10% discount for the whole cart
2. In _Stores -> Configuration -> Customers -> Persistent shopping cart_ set the following configuration: Enable Persistence- Yes, Clear Persistence on Sign Out -> No
3. As logged in user add a product to the cart and go the checkout, step 2. Discount is added.
4. Log out.
5. Got the checkout, step 2, with persistent cart

### Expected result (*)

1. Discount is not applied to the not logged in user

### Actual result (*)

1. Discount for logged in user only is applied to not logged in user

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2021-02-01 14:13
Hello @msiewierska 

Thank you for your report

When the _Clear Persistence on Sign Out_ is set to _No_ it means that the shopping cart is saved when a registered customer logs out. It is not going to be updated because the Customer Logged Out. The discount has been applied while the Customer was still Logged In.
This is the Expected behavior in this case.

We are closing this ticket. Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by engcom-Bravo** 2021-02-01 14:13 UTC
Labels: non-issue, Issue: ready for confirmation, not-confirmed
