### ISSUE TITLE
Magento 2 Vimeo issues

### ISSUE THREAD

**Issue by andy-aware** [magento/magento2#31759] opened 2021-01-19 11:31 UTC
We've noticed that Vimeo API no longer works with any Magento instance we have. Outlined below.

### Preconditions (*)

1. Magento 2.3.5-p1
2. Magento 2.3.6
3. Magento 2.4

### Steps to reproduce (*)

1. Go to Magento admin and select a product to edit
2. Go to add images & video 
3. Click add video and try to use a Vimeo URL

### Expected result (*)

1. Video to pull through all information available in the JSON
2. Should pull through video to add to the product

### Actual result (*)

1. Alert message - Video not available.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment] 2021-01-19 15:02
This is a duplicate of https://github.com/magento/magento2/issues/31753, @awaredigital can you close this one again?

**Closed as completed** 2021-01-19 15:04 UTC

**Comment by lewisje** [comment] 2021-11-04 20:44
@andy-aware, put the patched file from [this PR](https://github.com/magento/magento2/pull/31769/files) by @gcampedelli into `Magento_ProductVideo/web/js/` inside of a custom admin theme, to fix your problem.
