### ISSUE TITLE
REST API: Product updates with wrong store_id

### ISSUE THREAD

**Issue by tdittmar** [magento/magento2#7612] opened 2016-11-29 14:46 UTC
### Preconditions
1. Magento 2.1.2 out of the box installation
2. An application that communicates via REST API with that Magento installation

### Steps to reproduce
1. Create a new simple item via REST API (POST to `/rest/V1/products`) with descriptions and META information.
2. Verify in shop bakend that the item was created correctly.
3. Verify in database (table `catalog_product_entity_text`) that the attributes are inserted with `store_id` 0
4. Update the long description for that same item via REST API (PUT to `/rest/V1/products/{sku}`).
5. Check the shop backend: the long description appears to be unchanged
6. Check the database (same table): A new attribute is inserted with `store_id` 1 instead of updating the previously created attribute.

### Expected result
1. The description that was created when creating the item should be changed when updating the item instead of creating a new attribute with the wrong `store_id`.

### Actual result
1. The description that was created when creating the item still exists, but a new description is added with a wrong `store_id` 1.

This is for Magento version 2.1.2 and was not an issue in pre-2.1 versions.

**Comment by veloraven** [comment] 2016-11-30 09:56
@tdittmar thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by tdittmar** [comment] 2016-11-30 10:49
@veloraven I updated the original bug report.

**Comment by tdittmar** [comment] 2016-11-30 15:39
By the way: The same problem occurs also when fetching product information from Magento with a GET request to `/rest/V1/products/{sku}`. I get the wrongly inserted new product attributes by default. 

Only if I delete the wrongly inserted attributes from the database manually I get the expected values that were passed to Magento when creating the item.

**Comment by olysenko** [comment] 2016-12-05 14:26
Hi, thank you for your report. Internal ticket MAGETWO-61834 was created

**Comment by Silarn** [comment] 2016-12-07 18:53
The problem (with saving, anyway) is that there's no way to configure which store scope to use with the current API code.

Line 513 of \Magento\Catalog\Model\ProductRepository in save():
$productDataArray['store_id'] = (int)$this->storeManager->getStore()->getId();

Magento always just gets the current frontend store_id when saving the product data. There's no way to pass in the desired store - or to set the global store data.

**Comment by tdittmar** [comment] 2016-12-07 19:01
So why is it different for create (POST) and update (PUT)? If it just used
the same id every time...

Am 07.12.2016 7:54 nachm. schrieb "Jeremy Rimpo" <notifications@github.com>:

**Comment by Silarn** [comment] 2016-12-07 19:09
Not completely clear. Both methods resolve to the same save() function, but there are slightly different methods called if it's a new product. (Both methods can update existing products, and POST has the same issue when updating products.) Perhaps the data for a new product is just being saved globally instead of for a specific scope, which could be a different bug in itself. Most likely this could be because there has to be data for the global scope so new data gets saved there while updated data may write to a store-specific scope if the store_id is set.

**Comment by careys7** [comment] 2017-02-20 10:07
Is there any progress on a fix for this Magento / @olysenko ? 

No multi-store catalog API is a problem for most of our clients (see also #8121 / #4806 which has been open for 8 months).

**Comment by veloraven** [comment] 2017-06-20 07:48
I'm closing this issue as internal ticket was closed as not a bug.

> For update Product or Category on Global Scope we should set Store Code = **_all_**.
> For example *http://<domain>/index.php/rest/all/V1/categories/:id* or *http://<domain>/index.php/rest/all/V1/products/:sku*
> This point described in http://devdocs.magento.com/guides/v2.0/rest/rest_endpoints.html

**Closed as completed by veloraven** 2017-06-20 07:48 UTC
Labels: Issue: Ready for Work, bug report, Component: Framework/Webapi

**Comment by LiamKarlMitchell** [comment] 2020-06-03 03:16
Still a problem in Magento 2.2 and 2.3 by the way.
