### ISSUE TITLE
Unable to create order from admin when instance got multiple Store Views on 2.4.6

### ISSUE THREAD

**Issue by JelleGe** [magento/magento2#37452] opened 2023-05-03 08:58 UTC
### Preconditions and environment

- Magento version: 2.4.6
- Multi store view setup; same Web Site and same Store, but different Store Views with different languages.

### Steps to reproduce

1. Create a multi store view setup on 2.4.6, with different languages
2. Try to create New Order from Admin
3. On the step "Please select a store" select a Main Website Store radio bullet
4. Page is loading to the next step, but then directly return to the same "Please select a store" page. So you can not process with the next step to select products and enter billing/shipping details. It's not possible to escape or bypass this loop.

### Expected result

Load the next step to select products and enter Billing and Shipping details

### Actual result

Page is loading to the next step, but then directly return to the same "Please select a store" page. It's not possible to escape or bypass this loop.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by JelleGe** [comment] 2023-05-03 09:04
@magento give me 2.4-develop instance

**Comment by JelleGe** [comment] 2023-05-03 10:06
Issue is not reproducible on the vanilla Magento instance, but it is on a default empty Magento 2.4.6 instance!

**Comment by JelleGe** [comment] 2023-05-04 07:07
> I encountered this same issue.
> 
> Remove `location.reload();` from method `setStoreId` in `Magento_Sales/order/create/scripts` as a temporary fix.

This indeed solved the problem temporary

**Comment by engcom-Dash** [comment] 2023-05-12 12:37
Hi @JelleGe,

Thanks for contribution and collaboration!

Verified the issue in 2.4-develop instance and 2.4.6 Magento Instance and the issue is reproducible in 2.4.6 and not reproducible in 2.4-develop instance, Hence we are confirming the issue.

**Preconditions:**
Magento version 2.4-develop and 2.4.6
PHP version 8.1
 
**Kindly refer the below video reference:**
 
https://user-images.githubusercontent.com/60198592/236138323-a9843869-1693-4085-ab24-3e48ac1b11ff.mp4
 
**Steps to reproduce:**
1.Install magento instance
2.Go to stores >all Stores>create multiple  store view with same website and same store
3.Go to stores>Configuration>General>Locale Options>Set different Language for differnet store view
4.Go to sales >Order>Create new order and trying to select store view
 
 
We are getting Actual result which is page is loading to next step and directly comes to "please select store page".
Hence we are confirming the issue.

Thanks.

**Comment by Kerolusnasser** [comment] 2023-05-12 15:00
i faced this issue while upgrading to 2.4.6
fixed when using this commit 
https://github.com/magento/magento2/commit/6c93c056f3a1fae9d8eef628f664593b2b0e3d4f
you can add .diff at the end of the URL it will give you patch file to easily use it 
https://github.com/magento/magento2/commit/6c93c056f3a1fae9d8eef628f664593b2b0e3d4f.diff

**Comment by engcom-Dash** [comment] 2023-05-18 11:18
Hi @JelleGe ,

Verified the issue in 2.4-develop instance and 2.4.6 magento instance and the issue is reproducible in 2.4.6 and not reproducible in 2.4-develop instance,Hence we are confirming the issue.

Kindly refer the below video reference:
in 2.4-develop

https://github.com/magento/magento2/assets/60198592/fa258dfb-2136-4865-b061-57c999d33473

in 2.4.6

https://github.com/magento/magento2/assets/60198592/db06f024-af16-41d7-8c31-6523eba8acf5

Note:It's not a problem that happens all the time, it happens sometimes

Thanks.

**Comment by engcom-Dash** [comment] 2023-05-18 13:15
Hi @JelleGe ,

The issue not reproducible in the 2.4-develop branch, That means is already fixed and available in the next release.
So, We can close the issue for now.

**Comment by simonmaass** [comment] 2023-06-05 13:28
we are facing the same problem - not really sure why this issues hasnt blown up more... seems to be a big issue not being able to create orders from the admin backend...

**Comment by engcom-Bravo** [comment] 2023-06-09 08:10
Hello,

We are reopening this issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-06-09 09:31
Hi @JelleGe,


The issue is reproducible in 2.4.6 but not in 2.4-develop. but we need to close this issue as Duplicate of this one https://github.com/magento/magento2/issues/37454.Kindly move onto this issue for latest updates / solutions on the same.



Thank you.

**Closed as completed by engcom-Bravo** 2023-06-09 09:31 UTC
Labels: duplicate, Issue: ready for confirmation, Area: Admin UI, Reported on 2.4.6

**Comment by chittima** [comment] 2023-06-23 16:37
Internal team fixed the issue and here is the commit id: https://github.com/magento/magento2/commit/d6176449f759a8bd535693cdf2971aed5a14e4c3

**Comment by citizenc78** [comment] 2023-08-21 00:16
I am still experiencing this same issue within 2.4.6.

**Comment by simonmaass** [comment] 2023-08-21 08:22
@citizenc78 well the commit wasnt merged in 2.4.6... its merged in 2.4.7-beta... should be available in 2.4.7 then...

**Comment by s1mplex1337** [comment] 2024-01-22 19:30
yes can confirm still an issue in 2.4.6 and above patch didn't solve it.

**Comment by leonhelmus** [comment] 2024-03-20 14:42
I think this patch resolves it testing it now:
https://experienceleague.adobe.com/en/docs/commerce-knowledge-base/kb/support-tools/patches/v1-1-34/acsd-52277-admin-user-redirected-incorrectly-on-selecting-store-view-when-creating-new-order

**Comment by jmonrove** [comment] 2024-10-17 15:54
> I encountered this same issue.
> 
> Remove `location.reload();` from method `setStoreId` in `Magento_Sales/order/create/scripts` as a temporary fix.

Still a problem in 2.4.6-p8
This workaround works for now.

**Comment by imran215** [comment] 2024-10-31 15:04
I override Sales_Order scripts.js file and changed "location.reload();" with below code.
setTimeout(function() {
    location.reload();
}, 4000);

This worked fine for me. 
Explain: This is kind of race condition. Magento send an Ajax for card_validation but reload page before ajax call is completed. So giving some time e.g. 4 sec to that Ajax call to get completed and then reload page works quite fine but if your internet is very slow then you might need to add few more seconds.

**Comment by engcom-Delta** [comment] 2024-12-02 13:30
Hi @JelleGe ,

Thanks for reporting and collaboration.
We have re-verified the issue in Latest 2.4-develop instance , but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce**
1. Create a multi store view setup on 2.4-develop instance, with different languages
2. Try to create New Order from Admin
3. On the step "Please select a store" select a Main Website Store radio bullet
4. Next step is displaying as expected to place order

https://github.com/user-attachments/assets/80b24ad9-7c7f-4d2b-91fa-a06fcbae152c


Can you please re-verify and confirm if you are still facing the issue.
Thanks.
