### ISSUE TITLE
Magento 2.4.7-p3 Admin Category Does Not Appear as Disabled in Category Tree

### ISSUE THREAD

**Issue by sagarjadav24** [magento/magento2#39357] opened 2024-11-12 07:05 UTC
### Preconditions and environment

- Magento version - 2.4.7-p3

### Steps to reproduce

1. Go to Catalog -> Categories
2. Edit any category
3. Disable category

### Expected result

If the Admin disables any category from Catalog -> Categories, it should show as disabled highlighted in the category tree, as in previous Magento versions.

Older Magento version: https://tinyurl.com/2c5y4lp8
Latest Magento Version: https://tinyurl.com/2cyjdkbw

### Actual result

If Admin disabled any category from Catalog -> Categories then it is visible as enabled no difference between the enabled category and disabled category.

Ref : https://tinyurl.com/2cyjdkbw

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sagarjadav24** [comment] 2024-11-12 07:11
@magento give me 2.4.7-p3 instance

**Comment by engcom-Bravo** [comment] 2024-11-12 07:40
Hi @sagarjadav24,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Go to Catalog -> Categories
- Edit any category
- Disable category



<img width="1351" alt="Screenshot 2024-11-12 at 12 47 04" src="https://github.com/user-attachments/assets/8a406d3a-c9b8-4b68-81ca-5cd507476f08">


 Here 2 categories were disabled and it were highlighted.

Kindly recheck the issue in Latest Magento instance and elaborate the steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by hostep** [comment] 2024-11-12 07:43
This was fixed 2 weeks ago in [ACP2E-3350: Disabled Categories are no longer have their names grayed out in the category tree](https://github.com/magento/magento2/commit/efd35a9e8adf86f09dc5a0a821e2b9c26a36a3fd)

**Comment by sagarjadav24** [comment] 2024-11-12 07:46
@engcom-Bravo As per the @hostep comment issue is there but it's already fixed.

**Comment by engcom-Bravo** [comment] 2024-11-13 04:39
@hostep Thanks for your Contribution!!.

As per this comment https://github.com/magento/magento2/issues/39357#issuecomment-2469807918 we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-11-13 04:39 UTC
Labels: Issue: needs update, Reported on 2.4.7-p3
