### ISSUE TITLE
Weird issue with custom shipping module

### ISSUE THREAD

**Issue by MagePsycho** [magento/magento2#4142] opened 2016-04-13 21:09 UTC
Whenever you use the custom shipping method code to be `$_code = <vendor>_<module>`, you get an error:

> Please choose shipping method

 while placing an order (during checkout payment) page.

It working fine when you use the code to be `<module>` only.
Is this a bug? I would love to have the code to be `<vendor>_<module>` in order to avoid the conflict with other extensions.

**Comment by ishakhsuvarov** [comment] 2016-04-14 15:18
@MagePsycho Thank you for reporting. Could you please provide more information regarding names you use? Any special characters in `<vendor>` or `<module>` values?

**Comment by MagePsycho** [comment] 2016-04-14 18:44
I am using `$_code = 'magepsycho_customshipping'` 

And code being used as:
`$method->setCarrier($this->getCarrierCode());
$method->setMethod($this->getCarrierCode());`

**Comment by piotrekkaminski** [comment] 2016-05-24 16:35
internal issue MAGETWO-53438

**Comment by magento-engcom-team** [comment] 2017-12-05 09:30
@MagePsycho, thank you for your report.
The issue is already fixed in 2.1.10

**Closed as completed by magento-engcom-team** 2017-12-05 09:30 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Fixed in 2.1.x, Issue: Format is not valid
