### ISSUE TITLE
Cannot upload files if observer is located in frontend/events.xml 

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#35215] opened 2022-03-22 19:57 UTC
### Preconditions (*)

1. Magento 2.4.2 / 2.4.3-p1

### Steps to reproduce (*)

1. Add an upload field on customer registration form
2. change form type to accept `multipart/data`
3. An observer to `customer_register_success` file in `frontend/events.xml`
4. Try to save the uploaded file 

```
$uploader = $this->uploaderFactory
                    ->create(['fileId' => $fileInputName])
                    ->setAllowCreateFolders(true)
                    ->setAllowRenameFiles(true)
                    ->setAllowedExtensions($allowedExtensions);

                $result = $uploader->save($mediaDirectory);
```

### Expected result (*)

1. File is saved in the desired location

### Actual result (*)

1. System returns an error on save from this file: `vendor/magento/framework/File/Uploader.php`
2. `The file was not uploaded.` - this is the error
3. for some reason the upload `file_size` returned is 0
```
if (!file_exists($this->_file['tmp_name'])) {
            $code = empty($this->_file['tmp_name']) ? self::TMP_NAME_EMPTY : 0;
            throw new \DomainException('The file was not uploaded.', $code);
        } else {
            $this->_fileExists = true;
        }
```

### Solution:
Add event in `events.xml` not in `frontend/events.xml`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2022-03-30 12:18
Hello @qsolutions-pl,

We have tried to reproduce the issue in Magento 2.4-develop branch but for us, the issue is not reproducible. We have followed the steps mentioned in your description.

For reference, we are attaching the module:

[Hashcrypt.zip](https://github.com/magento/magento2/files/8380331/Hashcrypt.zip)

Please review and let us know in case of a query.

Thanks

**Comment by engcom-Hotel** [comment] 2022-04-13 06:18
Dear @qsolutions-pl,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-04-13 06:18 UTC
Labels: Triage: Dev.Experience, Issue: needs update
