### ISSUE TITLE
quotes not escaped for translations of "Not you?" message in persistent header

### ISSUE THREAD

**Issue by ktruehl** [magento/magento2#5574] opened 2016-07-11 08:25 UTC
## Steps to reproduce
1. Install Magento 2.1.
2. Install the French translation package by Imaginaerum (https://github.com/Imaginaerum/magento2-language-fr-fr).
3. Set up to stores, the first with the default locale (`en_US`), the second with the locale `fr_FR`.
4. Do whatever you have to do (activate the persistent shopping cart in the settings, make sure the settings are correct, create a customer account, log into that account, log out again, etc.) do get the "Not you?" message in the header in the store for `en_US`.
5. Switch to the French store. 
## Expected result
1. No Javascript errors. In the header the message "Ce n'est pas vous?" should be displayed.
## Actual result
1. You get the following Javascript error: `SyntaxError: missing ; before statement` (at least in Firefox, the wording will vary depending on the browser used). The problem will become particularly noticable if you go to the shopping cart page (while having something in the cart) in the store for `fr_FR`, since the cart summary will not render correctly as a consequence of the first Javascript error.
## Underling problem

In the file `vendor/magento/module-persistent/Block/Header/Additional.php` in the method `_toHtml()` the translation of the message "Not you?" is not escaped.

**Comment by ktruehl** [comment] 2016-07-15 08:16
I found another occurrence in `vendor/magento/module-theme/Block/Html/Header.php` in the method `getWelcome()`. Here the translation of the welcome message is not escaped. In French it's "Message d'accueil par défaut".

**Comment by veloraven** [comment] 2016-08-04 07:13
@ktruehl thank you for your report.
Unfortunately I was not able to reproduce this problem.
Please provide some additional information like information about your environment: versions of PHP, MySQL, web server, Firefox versions. Was a new installation or upgrade from some previous version?
Please also provide screenshots for both described cases.

**Comment by ktruehl** [comment] 2016-08-04 10:25
MySQL 5.6, PHP 7.0.8, apache, reproducible in any browser. Look at the source code. You'll see why it will have to go wrong, if the welcome message contains a single quote.

**Comment by heldchen** [comment] 2016-08-30 21:59
still present in 2.1.1

**Comment by andimov** [comment] 2016-09-02 16:12
I've created an internal ticket MAGETWO-58020  for this issue and linked it to this one.

**Comment by bh-ref** [comment] 2017-02-20 14:46
issue is still present in 2.1.4

**Comment by magento-engcom-team** [comment] 2017-10-19 13:30
@ktruehl, thank you for your report.
We've created internal ticket(s) MAGETWO-58020 to track progress on the issue.

**Comment by sidolov** [comment] 2018-04-14 07:25
According to comment in [closed pull request](https://github.com/magento/magento2/pull/11938#issuecomment-342129450) this issue has been fixed in 2.2-develop branch

**Closed as completed by sidolov** 2018-04-14 07:25 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is not valid, Event: distributed-cd
