### ISSUE TITLE
Partial Catalog Product Price Indexing not removing old price date and is extremely slow if store has many products (above 200k)

### ISSUE THREAD

**Issue by zjevik** [magento/magento2#31752] opened 2021-01-19 04:27 UTC
### Preconditions (*)

1. Magento 2.4.1 + PHP 7.4.10 + MySQL 8.0.22
2. At least 200k simple products
3. Have at least 8 catalog price rules

### Steps to reproduce (*)

1. Set indexes to update by schedule and wait for indexing to complete.
2. Manually run **catalogrule_apply_all** cron job. (this is automatically run at 1am)

### Expected result (*)

1. Once the `partialUpdateCatalogRuleProductPrice` in `Magento\CatalogRule\Model\Indexer\PartialIndex.php` finishes `$this->indexBuilder->reindexFull();` the next code should take little time but the opposite is true.
2. Once the partial indexing is done rules older than yesterday should be removed from table `catalogrule_product_price_replica`

### Actual result (*)

1. Rules with `rule_date` dating back many months are present in `catalogrule_product_price_replica` essentially causing the next problem even worse over time
2. The code below from `partialUpdateCatalogRuleProductPrice` in `Magento\CatalogRule\Model\Indexer\PartialIndex.php` makes MySQL hang for many hours:
```
        $this->connection->query(
            $this->connection->insertFromSelect(
                $selectFields,
                $this->resource->getTableName('catalogrule_product_price_replica'),
                [
                    'rule_date',
                    'customer_group_id',
                    'product_id',
                    'rule_price',
                    'website_id',
                    'latest_start_date',
                    'earliest_end_date',
                ],
                AdapterInterface::INSERT_ON_DUPLICATE
            )
        );
```
Store admin has to also truncate `catalogrule_product_price_replica` once a while to remove old data.
  
It is my understanding from MySQL Workbench that the code will cause many table scans and each insert will fire a trigger that will compare the new data. This statement will put a hold on `catalog_product_price_cl`. This will cause additional cron tasks to get to waiting state and causes additional RAM usage.
A workaround is to disable using `catalogrule_product_price_replica` for partial indexing and perform full price index instead. This is especially true if one is using multithreaded indexing by setting `MAGE_INDEXER_THREADS_COUNT`.

On our store with 1 million simple products it caused cron to crash every afternoon from many cron threads waiting for `catalog_product_price_cl` lock.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by zjevik** [comment] 2021-01-19 04:28
@magento give me 2.4-develop instance

**Comment by hostep** [comment] 2021-04-07 06:24
I can confirm this, just looked at a shop running on Magento 2.3.6-p1, the table `catalogrule_product_price_replica` contains 78198 records, the oldest date in the `rule_date` column is the day before we upgraded this shop from 2.1.16 to 2.3.6-p1, so it looks like before 2.3.6 the table got cleaned up, but since the upgrade to 2.3.6, the cleanup no longer happens.

Sounds like quite an important problem, @sidolov, can we have some priority over here?

**Comment by magento-engcom-team** [comment] 2021-04-07 16:50
:white_check_mark: Confirmed by @sidolov 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41807` were created

**Issue Available**: @sidolov, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by zjevik** [comment] 2021-04-07 17:05
Thanks @hostep! Hope this will get fixed on 2.4 branch and I won't have to run the full reindex every night as a workaround.

**Closed as completed** 2021-07-12 13:25 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Severity: S2, Priority: P0, Progress: done

**Comment by hostep** [comment] 2021-07-12 16:07
@sdzhepa: can we have some information why this ticket was closed?
It it was closed because it was fixed, it would be appreciated if we can have some links to commits that fixed this.

Thanks! 🙂

**Comment by giacmir** [comment] 2021-07-30 07:21
We have a shop (2.3.6) where the `catalogrule_product_price_replica` is growing at a rate of 10gb every three days. This is a potential infrastructure breaking issue and should be solved in existing versions too, not only in the next release.

**Comment by giacmir** [comment] 2021-07-30 07:51
This issue is mentioned in two commits:
6e6fff2a87221cd71f0f9e347a1cf35b3460d13f and 6a9f4474fb3a79612799db23c2a1543fc14fbd2f

It seems that the proposed solution is pretty drastic :smile: 
![immagine](https://user-images.githubusercontent.com/447940/127619936-e24b80b2-fe79-4a6c-8f45-fad42f4415c2.png)

@dhorytskyi Can you please provide us a patch for existing versions?

**Comment by kanevbg** [comment] 2021-11-24 10:33
up

**Comment by fredden** [comment] 2021-12-17 17:57
@sdzhepa or @dhorytskyi, please can you provide some information here to explain why this has been closed?

**Comment by sdzhepa** [comment] 2021-12-17 19:09
Hello @fredden 

As I can see this issue was fixed in the scope of the Jira ticket by the internal team
Related commits: https://github.com/magento/magento2/search?q=MC-41807&type=commits

**Comment by fredden** [comment] 2021-12-17 19:49
Thanks @sdzhepa that's helpful. From what I can tell, deleting all values from the `catalogrule_product_price_replica` table seems safe.

**Comment by kanevbg** [comment] 2021-12-17 22:11
> Thanks @sdzhepa that's helpful. From what I can tell, deleting all values from the `catalogrule_product_price_replica` table seems safe.

Confirming I have done this previously and had no issue in practice.

**Comment by pmonosolo** [comment] 2022-02-23 18:48
Confirming 2.4.3 affected also. Table not being cleaned up and growing every day by a lot.

**Comment by pmonosolo** [comment] 2022-10-25 18:17
Looks like 2.4.5-p1 does not have this issue anymore. I used to have to truncate the table to limit the size of the DB backups.
