### ISSUE TITLE
Uncaught TypeError: window.checkoutConfig is undefined on Add New Address form region updater.

### ISSUE THREAD

**Issue by deepakkn85** [magento/magento2#36935] opened 2023-03-01 04:58 UTC
### Preconditions and environment

- Magento version :_ 2.4.5-p1

State drop down in Add New Address form is not getting updated based on Country selection. Browser console throws an error 

Uncaught TypeError: window.checkoutConfig is undefined
    validate https://local.lsretail-mag.com/static/frontend/Magento/luma/en_US/Magento_Checkout/js/model/postcode-validator.js:23
    _validatePostCode https://local.lsretail-mag.com/static/frontend/Magento/luma/en_US/Magento_Customer/js/addressValidation.js:92
    prop jQuery
    _addPostCodeValidation https://local.lsretail-mag.com/static/frontend/Magento/luma/en_US/Magento_Customer/js/addressValidation.js:72

However I noticed that this issue is a blocker when the website is in Production mode. In developer mode this console error will not stop updating the State filed on Country switching.

### Steps to reproduce

On production mode, navigate to My Account > Address Book > Add/Edit New Address

Switch the countries drop down.

### Expected result

State field should update based on Country selected.

### Actual result

State field not updating and browser console showing error

Uncaught TypeError: window.checkoutConfig is undefined
    validate https://local.lsretail-mag.com/static/frontend/Magento/luma/en_US/Magento_Checkout/js/model/postcode-validator.js:23
    _validatePostCode https://local.lsretail-mag.com/static/frontend/Magento/luma/en_US/Magento_Customer/js/addressValidation.js:92
    prop jQuery
    _addPostCodeValidation https://local.lsretail-mag.com/static/frontend/Magento/luma/en_US/Magento_Customer/js/addressValidation.js:72

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-03-01 06:31
Hi @deepakkn85 ,

Thanks for your collaboration,

Verified the issue in 2.4-develop branch,But we are not able to reproduce the issue.

Preconditions:
Magento version 2.4-develop 
PHP Version 8.1

Steps to reproduce:
1.Install magento instance
2.Set Production Mode using below command
   "php bin/magento deploy:mode:set production"
3.Go to front end with Valid Customer
4.Go to My Account >> Click on address book
5.Add new address
6.Select Different country and verify State field should update based on Country selected.

Screenshots for your reference:
<img width="1078" alt="today1" src="https://user-images.githubusercontent.com/60198592/222061237-05fe991f-1bfc-48c3-82f9-d49ef5fbbe0b.png">
<img width="1058" alt="today2" src="https://user-images.githubusercontent.com/60198592/222061264-61ee564e-884b-468a-8a72-439e2065c95f.png">
<img width="1058" alt="today3" src="https://user-images.githubusercontent.com/60198592/222061270-38ed0f58-987a-4607-825a-32e99cb7cbe8.png">
<img width="1058" alt="today4" src="https://user-images.githubusercontent.com/60198592/222061275-5be87ad2-f17c-4109-9ee6-5ba7d1f133e1.png">
<img width="1472" alt="today6" src="https://user-images.githubusercontent.com/60198592/222061276-66d56c7a-2216-4d27-8d97-6b0243742654.png">

State field is updated based on the country selected and no error displaying in the console,Kindly provide more information if the issue still reproducible.
Let us know if we missing any steps

Regards.

**Comment by engcom-Dash** [comment] 2023-03-20 05:45
Hi @deepakkn85 ,

We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-Dash** 2023-03-20 05:45 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1
