### ISSUE TITLE
Advanced Reporting 404 message Magento 2.4.2

### ISSUE THREAD

**Issue by davidduong90** [magento/magento2#34601] opened 2021-11-10 16:54 UTC
Feedback on page: [/guides/v2.4//reports/advanced-reporting.html](https://docs.magento.com/user-guide/reports/advanced-reporting.html)

### Preconditions (*)
1. Magento 2.4.2
2. Cron work fine

### Steps to reproduce (*)
I have configured advanced reporting for my sub domain https://magiccart.io/tpcm2/

![Screenshot_2](https://user-images.githubusercontent.com/39608917/141154772-7c4d3609-5364-4e60-b3a5-381196a99404.png)

![Screenshot_3](https://user-images.githubusercontent.com/39608917/141154798-dbcbe530-b786-4914-acb3-76d0b5811eb3.png)

### Expected result (*)

It should show like this:
![Screenshot_7](https://user-images.githubusercontent.com/39608917/141156951-0819478c-afe4-47d3-a264-168d903b45f0.png)

### Actual result (*)
![Screenshot_8](https://user-images.githubusercontent.com/39608917/141157340-77be21b3-ad91-4b36-bf34-b27fdd52ff82.png)

I have checked the cron log, but it seems to work fine.

![Screenshot_4](https://user-images.githubusercontent.com/39608917/141155165-5793e4d0-bfa9-4658-8858-0cdea67a1a28.png)

![Screenshot_5](https://user-images.githubusercontent.com/39608917/141155195-3e259f58-b1a5-4215-a237-7720ad797d9a.png)

I can see a file data.tgz in path

pub/media/analytics/35d7d8b6413879706762dc5bc96ff8f199c0ad8c585664ed0c00d81513fb3bfe/data.tgz

But when I try to open this file, it shows a bug.

![Screenshot_6](https://user-images.githubusercontent.com/39608917/141155616-ed808780-7ecc-4b26-a192-971cadb311a0.png)

Please help or have any idea will be great. Thank you so much!

**Comment by davidduong90** [comment] 2021-11-16 08:24
Hello @engcom-Hotel 

If this crontab works fine

<job name="analytics_collect_data" instance="Magento\Analytics\Cron\CollectData" method="execute" />

How long do you think data will show up on the link:
https://advancedreporting.rjmetrics.com/report?otp=_InyQ7gh3GgM9wewXiUdmM6MpJ_VDBsYZjqGtiqsR8NcIoAifiVvR8dJ1ZkkAWHJRbhRhIcuKmJcSuv9602uOw

**Comment by engcom-November** [comment] 2021-11-29 08:54
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2021-12-01 05:51
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue.
@davidduong90 kindly recheck the issue on 2.4-develop branch and elaborate the steps to reproduce if you are still getting the issue.
Thank you

**Comment by engcom-November** [comment] 2021-12-16 13:04
Hi @davidduong90 ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-12-16 13:04 UTC
Labels: Issue: needs update

**Comment by megham2908** [comment] 2024-09-30 13:56
Hi @davidduong90 

Could you please confirm if this is resolved for you? Even I'm facing same issue and using Magento version 2.4.5-p9?

Thanks
