### ISSUE TITLE
Large Cart Issue

### ISSUE THREAD

**Issue by kkhebbar89** [magento/magento2#26231] opened 2020-01-02 09:14 UTC
### Preconditions (*)

1. Magento 2.3.3 CE with sample data

### Steps to reproduce (*)

1. Add more than 80 products in the cart as logged in user
2. Then the next click of Add to cart in product detail page takes lot of time
3. Logging In with 80 or more product takes lot of time to login
4. Shopping Cart page also takes lot of time to load

### Expected result (*)

1. Add to cart with large cart should take same/little more time as empty cart
2. Logging In with huge cart shouldn't take lot of time
3.  Shopping cart also shouldn't take lot of time

### Actual result (*)

1. Add to cart with huge cart takes lot of time
2. Logging In with huge cart takes lot of time to login 
3. Shopping cart with huge cart takes lot of time to load

![Login](https://user-images.githubusercontent.com/13129870/71659623-47a6fd00-2d6e-11ea-928d-8041934f2301.JPG)

![AddToCart](https://user-images.githubusercontent.com/13129870/71659631-4c6bb100-2d6e-11ea-9bdb-49a23d27f670.JPG)

![Cart](https://user-images.githubusercontent.com/13129870/71659641-52619200-2d6e-11ea-8faa-0494d7d02527.JPG)

**Comment by engcom-Bravo** [comment] 2020-01-03 08:17
Hello @kkhebbar89 
Thank you for your report. 

We have rechecked this on Magento 2.4- develop with over 90 products in the Cart.
The processes take some time to accomplish, but not as much time as on the screenshots you've attached.
For example, the **Sign In** takes about 4 seconds, **Cart Checkout**, about 8 seconds, **Adding to Cart**, about 4 seconds.
 
Can you please confirm that you are experiencing the same performance on Magento 2.4-develop ?

**Comment by kkhebbar89** [comment] 2020-01-07 06:17
Hello @engcom-Bravo 
Checked the same in Magento 2.4- develop, there I see very good perfomance. Please find below the screeshots.

![Login](https://user-images.githubusercontent.com/13129870/71872715-3cbfe400-3143-11ea-8116-d87400bb174d.JPG)
![AddToCart](https://user-images.githubusercontent.com/13129870/71872723-41849800-3143-11ea-9da3-ea067150045b.JPG)
![Cart](https://user-images.githubusercontent.com/13129870/71872730-45181f00-3143-11ea-8f7e-d0094614f2f1.JPG)

Are any changes done for enhancing perfomance in Magento 2.4.0. Can you please share the commit for the same.

Thanks & Regards,
Karthik S.

**Comment by engcom-Bravo** [comment] 2020-01-09 15:18
@kkhebbar89 
Thank you for the response.
I tried to find a related task for it by keywords but unfortunately, with no result.
Probably it was done in scope on some bug fix or other task (internal or external)

So if the issue is not reproducible on 2.4-develop, we have to close this issue.
Thank you for your collaboration.

**Closed as completed by engcom-Bravo** 2020-01-09 15:18 UTC
Labels: Progress: needs update, Issue: Format is valid, Reported on 2.3.3

**Comment by OvalMedia** [comment] 2020-04-30 10:46
Calling load times in cart and checkout of around 8-10 seconds a "very good perfomance" is ludicrous.
