### ISSUE TITLE
Magento 2.3 installation fails: Base table or view not found

### ISSUE THREAD

**Issue by pixmin** [magento/magento2#22005] opened 2019-03-28 11:29 UTC
### Preconditions (*)

1. Magento CE 2.3.1 (Magento-CE-2.3.1-2019-03-18-06-36-39.tar.bz2)
2. Using PHP 7.2
3. Already have several Magento 2 installed on the database where this one is about to be installed (with different prefixes of course)

### Steps to reproduce (*)

1. Installation from the command line with:

`php bin/magento setup:install --admin-firstname=XXX --admin-lastname=XXX --admin-email=XXX@XXX --admin-user=XXX@XXX --admin-password='XXX' --base-url=https://XXX/ --base-url-secure=https://XXX/ --backend-frontname=XXX --db-host=XXX --db-name=magento --db-user=magento --db-password=XXX --language=fr_FR --currency=EUR --timezone=Europe/Paris --use-rewrites=1 --use-secure=1 --use-secure-admin=1 --admin-use-security-key=1 --session-save=db --db-prefix=m231`

### Expected result (*)

1. Magento succesfully installs itself 

### Actual result (*)

1. Magento fails to install with this error:

`Starting Magento installation:
File permissions check...
[Progress: 1 / 833]
Required extensions check...
[Progress: 2 / 833]
Enabling Maintenance Mode...
[Progress: 3 / 833]
Installing deployment configuration...
[Progress: 4 / 833]
Installing database schema:
Schema creation/updates:

In Pdo.php line 235:
                                                                                                                                                                            
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.m231m2111admin_passwords' doesn't exist, query was: SHOW CREATE TABLE m231m2111admin_passwords  
                                                                                                                                                                            

In Pdo.php line 228:
                                                                                                                     
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.m231m2111admin_passwords' doesn't exist  `

Note that Magento adds an extra prefix, which I believe is the first table it finds in the database.

**Comment by magento-engcom-team** [comment] 2019-03-28 11:29
Hi @pixmin. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@pixmin do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-03-28 11:51
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-03-29 09:08
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98963` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by aleromano89** [comment] 2019-04-15 14:48
@pixmin I just tried to reproduce your error by installing 2.3.1 but no extra prefix is added to tables name and I get no error.

**Comment by PurushothamanKrishnamoorthy** [comment] 2020-06-18 07:37
@pixmin : I faced similar issue while installing Magento 2 from command line. I mapped existing database while installing Magento 2. 

Could you please check your env.php configuration. 

We can address this issue, by following way:

1. --cleanup-database to your installation command, which will drop existing database tables.

**Closed as completed** 2020-11-06 21:22 UTC
Labels: Component: Setup, Reproduced on 2.3.x, Fixed in 2.2.x, Progress: done

**Comment by magento-engcom-team** [comment] 2021-05-17 23:20
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
