### ISSUE TITLE
Translate Inline does not work on second translate

### ISSUE THREAD

**Issue by ihorvansach** [magento/magento2#32257] opened 2021-02-23 14:48 UTC
### Preconditions (*)
1. Magento 2.4.2
2. Developer mode enable
3. Have one test product
4. All Caches Enabled

### Steps to reproduce (*)
1. Enable Translate Inline for the storefront in admin panel (Stores > Configuration > Advanced > Developer)
2. Flush all Magento caches (bin/magento c:f or via admin panel)
3. Go to a product page
4. Change the text for "Add to Cart" button from "Add to Cart" to "Add to Cart2"
5. Flush the magento cache and refresh the page
6. Now, you'll see a new text "Add to Cart2", use Translate Inline again and change the label to "Add to Cart3".
7. Flush the cache and refresh the page

### Expected result (*)
1. You see "Add to Cart3" label

### Actual result (*)
2. You see "Add to Cart2"

Video: https://drive.google.com/file/d/1N6Oo_LqqfqpJEw402PU5QephhfoLaFYr/view

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [+] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment] 2021-02-23 15:24
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41012` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment] 2024-06-07 07:19
Hi @ihorvansach,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

<img width="1398" alt="Screenshot 2024-06-07 at 12 47 43" src="https://github.com/magento/magento2/assets/51680745/b3e7e9e5-9283-4c17-8748-1fcbf4ec07c7">


We are able to see Add to cart3 button.


Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-07 07:19 UTC
Labels: Component: Translation, Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Severity: S3, Progress: done, Issue: ready for confirmation, Reported on 2.4.x
