### ISSUE TITLE
sales_invoice table "total_qty" is mismatched with sales_order table "total_qty_ordered"

### ISSUE THREAD

**Issue by arushibansal013** [magento/magento2#24123] opened 2019-08-13 11:50 UTC
### Preconditions (*)

1. Issue is replicating in Magento 2.2.5, 2.3.x

### Steps to reproduce (*)

1. Place an order with configurable product.
2. Do invoice for the order. Issue can be easily understood if full invoice is done

### Expected result (*)

1. 'total_qty_ordered' in sales_order should be equal to 'total_qty' in sale_invoice

### Actual result (*)

1. 'total_qty_ordered' in sales_order is not equal to 'total_qty' in sale_invoice

Magento is calculating all item Quantities i.e, its summing up configurable item as well as child product quantity when saving in invoice table.

![issue2](https://user-images.githubusercontent.com/53007383/62939223-6708b200-bdee-11e9-9842-1f7fcb6874ab.png)
![issue3](https://user-images.githubusercontent.com/53007383/62939224-67a14880-bdee-11e9-9ad0-3450f22c8cb9.png)
![issue1](https://user-images.githubusercontent.com/53007383/62939225-67a14880-bdee-11e9-9744-284b7f571272.png)

**Comment by engcom-Charlie** [comment] 2019-08-14 07:38
Hello @arushibansal013 
I can't reproduce this issue on fresh Magento 2.3-develop.

**Manual testing scenario:**

1. Place an order with configurable product(i placed order with 2 child products with 3 qty for each)
2. Do invoice for the order. 
3. Check 'total_qty_ordered' in sales_order & 'total_qty' in sale_invoice

**Actual result:**
total_qty_ordered  & total_qty have the same value
![image](https://user-images.githubusercontent.com/51680850/63002386-7fc0a880-be7e-11e9-996a-30c77fd85a43.png)

![image](https://user-images.githubusercontent.com/51680850/63002322-5f90e980-be7e-11e9-8d09-3d9dec87f069.png)

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

Thank for your report!

**Closed as completed by engcom-Charlie** 2019-08-14 07:38 UTC
Labels: Component: Sales, Reproduced on 2.2.x, Issue: Format is valid
