### ISSUE TITLE
The Wishlist removing icon isn't correctly positioned on category pages

### ISSUE THREAD

**Issue by eduard13** [magento/magento2#21190] opened 2019-02-13 13:35 UTC
### Preconditions (*)

1. Magento 2.3-develop, 2.2-develop
2.

### Steps to reproduce (*)

1. Log In
2. Add a product to your wishlist
3. Go to the **category page**

### Expected result (*)

1. The removing icon should be placed on the top-right corner (as it is on other pages - customer dashboard)
![xnip2019-02-13_15-33-05](https://user-images.githubusercontent.com/15868188/52715290-bd627880-2fa4-11e9-9d0d-197296a5af20.jpg)

### Actual result (*)

1. The icon is positioned relative to the Add to Cart button
![xnip2019-02-13_15-28-35](https://user-images.githubusercontent.com/15868188/52715314-cfdcb200-2fa4-11e9-8b90-e8b061c77bf9.jpg)

**Comment by magento-engcom-team** [comment] 2019-02-13 13:35
Hi @eduard13. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@eduard13 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-02-13 13:36
Hi @dmytro-ch. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-02-13 13:46
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98251` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment] 2019-11-15 17:43
Hi @eduard13. Thank you for your report. 
The issue has been fixed in magento/magento2#25380 by @ptylek in 2.3-develop branch
Related commit(s):
 - [dd33d872dec0eeeaa5956b4ff735fdd3e71a0b6c](https://github.com/magento/magento2/commit/dd33d872dec0eeeaa5956b4ff735fdd3e71a0b6c)
 - [a26ca318c44c48ba60d3ecbc78ac997079eab527](https://github.com/magento/magento2/commit/a26ca318c44c48ba60d3ecbc78ac997079eab527)
 - [1ccd6a26d9b766a3ab6ffdedf6744a7e296aa485](https://github.com/magento/magento2/commit/1ccd6a26d9b766a3ab6ffdedf6744a7e296aa485)
 - [d9e0cfd9f0c438637221096874079eab5d820543](https://github.com/magento/magento2/commit/d9e0cfd9f0c438637221096874079eab5d820543)
 - [4381ce215b9ec68a2c238b3c6c469c5c2f3103b9](https://github.com/magento/magento2/commit/4381ce215b9ec68a2c238b3c6c469c5c2f3103b9)
 - [e619c262aa46e939b1d645d9aeea912e4de41884](https://github.com/magento/magento2/commit/e619c262aa46e939b1d645d9aeea912e4de41884)
 - [3267575132c18ebd5cb11f00a3fab895a1b217c8](https://github.com/magento/magento2/commit/3267575132c18ebd5cb11f00a3fab895a1b217c8)
 - [39988a12f97ea52d961282578a51be6620a706e1](https://github.com/magento/magento2/commit/39988a12f97ea52d961282578a51be6620a706e1)

The fix will be available with the upcoming 2.3.5 release.

**Closed as completed by VladimirZaets** 2019-11-15 17:43 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Progress: PR Created, Component: Wishlist
