### ISSUE TITLE
Bulk API Store ID Product Attribute Update adds Store ID 1 does not update / set Store ID 0.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [magento/magento2#29018] opened 2020-07-07 06:20 UTC
Related to / duplicate of #7720 #28274 #26484 #9186

### Preconditions (*)
Magento 2.3.2 (Doesn't matter).
1. Magento 2 store single store mode, rest api integration set up to get the access key to do updates from a third party script/program etc.
2. Rabbit MQ message queue configured with consumer running.
```bash
php bin/magento queue:consumers:start product_action_attribute.website.update --pid-file-path=product_action_attribute.website.update-hostname.pid --max-messages=10000 &
php bin/magento queue:consumers:start product_action_attribute.update --pid-file-path=product_action_attribute.update-hostname.pid --max-messages=10000 &
php bin/magento queue:consumers:start codegeneratorProcessor --pid-file-path=codegeneratorProcessor-hostname.pid --max-messages=10000 &
php bin/magento queue:consumers:start exportProcessor --pid-file-path=exportProcessor-hostname.pid --max-messages=10000 &
```

### Steps to reproduce (*)
1. Send bulk api request to update a product with name: 'Test Bulk'

For example the post URL is to "all".
POST https://mydomain/rest/all/V1/products
POST https://mydomain/rest/all/async/bulk/V1/products

I will show what is in the catalog_product_entity_varchar table for this product I am updating.

```SELECT * FROM catalog_product_entity_varchar WHERE entity_id = 20231```

To begin with
![image](https://user-images.githubusercontent.com/1968109/86724982-5fdd3900-c07d-11ea-8973-551eeeb9cbee.png)

### Expected result (*)
Just update, delete or create new store_id 0 values as needed.

The attribute should be updated e.g. in my testing here "Test UseBulk 1" would be the value and there would be no extra rows with store_id 1.

### Actual result (*)
Store ID 1 rows created unnecessarily, product now out of sync on front end and admin end as they show different data despite single store mode.
1. store_id 1 rows made/updated unnessecarily, the store_id 0 (default values) records should be updated!
![image](https://user-images.githubusercontent.com/1968109/86725619-eabe3380-c07d-11ea-9177-a0947f25fa38.png)

Note: When I update the product using rest api (Not with Bulk) using the /all route then store_id 0 is set correctly, but store_id 1 is not modified. (Well it shouldn't exist anyway in single store mode! but if it was existing it should be deleted.)
![image](https://user-images.githubusercontent.com/1968109/86725800-150ff100-c07e-11ea-94ee-c44764b0c5ce.png)
But is rather confusing when you say "all" for a store code, wouldn't it update ALL Store values? (Although that would cause duplicates...)

---
- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

Does anyone know a way I can make this act correctly?

**Comment by venugopal-codilar** [comment] 2020-12-17 16:06
@magento give me 2.4-develop instance

**Comment by hostep** [comment] 2021-01-21 07:17
This might have been fixed: https://github.com/magento/magento2/issues/31083#issuecomment-763905573 (not tested myself)

**Comment by dverkade** [comment] 2021-04-18 20:12
Posting a comment. Issues should not be automatically closed.

**Comment by engcom-Golf** [comment] 2021-06-07 14:27
@LiamKarlMitchell I tried to reproduce this issue, but can't reproduce. It is working as expected.  So considering this, I am closing this Issue.

**Closed as completed** 2021-06-07 14:27 UTC
Labels: Issue:  Cannot Reproduce, Issue: ready for confirmation, Reported on 2.3.2
