### ISSUE TITLE
email sent using php mail() is sent as domain's system user 

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#24481] opened 2019-09-06 08:29 UTC
### Preconditions (*)
1. Magento 2.3.0, 2.3.1

### Steps to reproduce (*)
1. Configure email sending but don't use SMTP to send emails. Use php mail() function which is set by default in Magento 2. 
2. Create an order
3. Send confirmation mail

### Expected result (*)
1. The email is sent as the email address defined in configuration: for example <sales@example.com>

### Actual result (*)
1. The email is sent using the system user name which is the owner of the magento files. e.g. <systemusername>@example.com
2. Reply-to is set to  <sales@example.com>

I've been busting my head over this for a while now and realize that by default php mail() function does this unless an explicit header is set by the application https://stackoverflow.com/questions/8365754/change-the-sender-name-php-mail-instead-of-sitenamehostname-com 

Even if Magento is setting this header before sending the emails there are hosting cases where the servers can ignore this to prevent spam and this needs specific configuration via php ini depending on the MTA used. 

Can this be handled by Magento?

**Comment by engcom-Charlie** [comment] 2019-09-09 12:40
Hello @ioweb-gr !
I can't reproduce this issue on Magento 2.3.2 & 2.3-develop.
My result:
![image](https://user-images.githubusercontent.com/51680850/64531392-0c447680-d318-11e9-80da-16f97b6b7df9.png)
So i have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-09-09 12:40 UTC
Labels: Issue: Format is valid

**Comment by ioweb-gr** [comment] 2019-09-09 13:06
@engcom-Charlie OK that's very interesting because I have seen it in at least 5 different PLESK and CPanel installations using the default magento installation. I would like to detect the reason this is happening so we could troubleshoot further and reproduce it.

Could you provide me some info on the test environment you used? 
What type of OS is used to host the instance and which MTA was used? 

The setups I tested on was on debian 9 / Postfix and CentOS / Exim 

Also could you verify the source code of the message to see whether indeed the from address is the only one used? Mine appears to be sent from the from address but it's not sent from that one. In one case I saw the from field showing correctly but a look at the source headers revealed the system user.

**Comment by engcom-Charlie** [comment] 2019-09-09 13:33
@ioweb-gr my environment: Ubuntu 16.04, PHP 7.2, Postfix . 
probably this issue is fixed in 2.3.2 in latest version of magento( i can't confirm issue if it’s not for 2.3.2 & 2.3-develop).

**Comment by ioweb-gr** [comment] 2019-09-09 13:38
OK so it should be similar environment. I will try with 2.3.2 and confirm if it persists on a Debian 9 system so we can retake a look at  this.

**Comment by engcom-Charlie** [comment] 2019-09-09 13:43
@ioweb-gr okay.

**Comment by ioweb-gr** [comment] 2019-09-09 19:44
@engcom-Charlie yes it seems it's not existent in 2.3.2 . Thanks for taking a look at it
