### ISSUE TITLE
Missing whitespace in mobile navigation for non-English websites

### ISSUE THREAD

**Issue by arendarenko** [magento/magento2#23080] opened 2019-05-31 12:35 UTC
### Preconditions (*)

1. Magento 2.2.8
2. Two websites with different locales: en_US and fr_FR
3. Installed language pack for fr_FR, for example: https://github.com/mageplaza/magento-2-french-language-pack

### Steps to reproduce (*)

1. Create category "Collections" set "Include in menu" and "Enabled" checked
2. Create two categories inside "Collections": "Test collection 1", "Test collection 2", set "Include in menu" and "Enabled" checked for both categories.
3. Open website on mobile and then open mobile navigation on FR website and click on "Collcetions" menu item 

### Expected result (*)

There is whitespace between "Tous" and "Collections" like in en_US website ("All Collections")
![22222](https://user-images.githubusercontent.com/42036143/58706057-a2800c80-83b9-11e9-862a-95598a15dbd8.png)

### Actual result (*)

There is no whitespace between "Tous" and "Collections" instead of en_US website ("All Collections")

![111111111](https://user-images.githubusercontent.com/42036143/58706027-88462e80-83b9-11e9-9e45-352afebdb987.png)

**Comment by ihor-sviziev** [comment] 2019-05-31 12:55
I checked, https://github.com/mageplaza/magento-2-french-language-pack doesn't have translation of "All " (with space at the end), but has translation of "All" (w/o space at the end), so magento using this translation. 
For this case looks like removal of space after "All" - looks good to me.

**Comment by magento-engcom-team** [comment] 2019-06-04 06:04
:white_check_mark: Confirmed by @ihor-sviziev 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17197`, `MC-17198` were created

**Issue Available**: @ihor-sviziev, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-06-07 03:05
Hi @alexeya-ven. Thank you for your report. 
The issue has been fixed in magento/magento2#23081 by @alexeya-ven in 2.3-develop branch
Related commit(s):
 - [01551217ed8473d692212df8873aea9c19306c7e](https://github.com/magento/magento2/commit/01551217ed8473d692212df8873aea9c19306c7e)

The fix will be available with the upcoming 2.3.3 release.

**Closed as completed by magento-engcom-team** 2019-06-07 03:05 UTC
Labels: Issue: Ready for Work, Component: Translation, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by magento-engcom-team** [comment] 2019-06-07 22:12
Hi @alexeya-ven. Thank you for your report. 
The issue has been fixed in magento/magento2#23164 by @speedy008 in 2.2-develop branch
Related commit(s):
 - [3a02c164227a5551571fcff3dfc197f4197a373d](https://github.com/magento/magento2/commit/3a02c164227a5551571fcff3dfc197f4197a373d)

The fix will be available with the upcoming 2.2.10 release.
