### ISSUE TITLE
Registers an unload listener

### ISSUE THREAD

**Issue by vishalkumar007** [magento/magento2#35892] opened 2022-08-09 07:24 UTC
### Preconditions and environment

- Magento version 2.4.3
- The `unload` event does not fire reliably and listening for it can prevent browser optimizations like the Back-Forward Cache. Use `pagehide` or `visibilitychange` events instead.
- Source: lib/web/legacy-build.min.js 

### Steps to reproduce

 1. install magento 2.4.3 
 2. check on https://pagespeed.web.dev/ this or chrome lighthouse tool.

### Expected result

There should not be any error or suggestion on  https://pagespeed.web.dev/  or chrome lighthouse tool.

### Actual result

The `unload` event does not fire reliably and listening for it can prevent browser optimizations like the Back-Forward Cache. Use `pagehide` or `visibilitychange` events instead.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment] 2022-08-09 09:27
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment] 2022-08-09 10:05
Hi @vishalkumar007 ,

Thanks for your contribution and collaboration.

I have tried to reproduce the issue but the issue is not reproducible to me on `2.4-develop`.
I did n't found any error in this section **`The unload event does not fire reliably and listening for it can prevent browser optimizations like the Back-Forward Cache. Use pagehide or visibilitychange events instead.`** on https://pagespeed.web.dev/
Please find below screenshot for your reference:
![image](https://user-images.githubusercontent.com/60198022/183621568-b61dee56-913b-4aae-8ab5-d209627a39ff.png)

Also, on google chrome lighthouse tool:
![image](https://user-images.githubusercontent.com/60198022/183622111-1ba773d9-09d9-41fd-b539-0dd54cad57be.png)

Kindly provide me more information so that issue can be reproducible and also test in latest `2.4-develop'. If you are facing any issue let us know.

Thanks

**Comment by engcom-Lima** [comment] 2022-08-23 06:20
Hi @vishalkumar007 ,


We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Lima** 2022-08-23 06:20 UTC
Labels: Issue: needs update, Reported on 2.4.3

**Comment by dandrikop** [comment] 2024-01-23 07:37
Hello,

Indeed, this issue exists on Magento 2.4.6.-p1 version. You can easily reproduce it by following the steps below:

1. Open the Developer Tools of Chrome browser.
2. Select the "Application" tab on the top.
3. At the section "Background services" on the left, select the Back/forward cache.
4. Visit any product page of the store.
5. Click on the blue button "Test back/forward cache", and you will see the view below:

![image](https://github.com/magento/magento2/assets/12056944/a2e32d03-023b-4963-a1b1-4d51bc03ce8d)
