### ISSUE TITLE
State not removed in checkout altough state option set correctly

### ISSUE THREAD

**Issue by dynamogold-bkre** [magento/magento2#4117] opened 2016-04-12 11:57 UTC
**Steps to reproduce**
1) Go to _Stores > Configuration > General > General > State Options_
2) Remove _Austria_ from selection in _State ist Required_
3) Set _Allow to Choose State if it is Optional for Country_ to _No_

**Expected result**
In _Checkout > Delivery Address_ if _Country_ equals _Austria_ the dropdown for _State/Province_ should not be visible and also not required.

**Actual result**
1) Dropdown ist still visible
2) Dropdown seems to be required in validation, altough it is not marked as such (via character "*")

**Comment by dynamogold-bkre** [comment] 2016-04-14 11:22
@ishakhsuvarov off topic: what does the label CS mean in this repo? I coudn't find any info on it or on any other label (MX, PS, ...)

**Comment by sdzhepa** [comment] 2016-04-14 12:44
@dynamogold-bkre, We have tried, but could not reproduce this issue on the latest code from repo. (commit f93b8daf1db281820161).
On current version drop-down for 'State/Province'  is disappeared if it is not required and present if it is required (with '*' for required fields)
Probably you are using not latest code base or need clarification in steps/preconditions etc.

**Comment by ishakhsuvarov** [comment] 2016-04-14 14:45
@dynamogold-bkre Regarding labels: they are used to assign issues to domains, you may find more detailed information in [Magento DevDocs](http://devdocs.magento.com/guides/v2.0/contributor-guide/contributing.html#labels)

**Comment by tdgroot** [comment] 2016-05-24 06:53
Having the same problem as well.. 

@sdzhepa the commit you are referring to hasn't even been released yet (only `2.1.0-rc1`). 

Tested with caching enabled/disabled, static-content redeployment as well.

**Comment by tdgroot** [comment] 2016-05-24 07:14
Guess this issue can be closed. 
See more at https://github.com/magento/magento2/issues/3043

**Comment by ishakhsuvarov** [comment] 2016-05-24 07:58
@Desmaster Thank you for the update. Closing.

**Closed as completed by ishakhsuvarov** 2016-05-24 07:58 UTC
Labels: Progress: needs update
