### ISSUE TITLE
Can't change customer address templates

### ISSUE THREAD

**Issue by tanghia** [magento/magento2#4671] opened 2016-05-24 13:22 UTC
Steps to reproduce
1. Click on Stores->configuration -> customer (section) -> address template
2. Add new attribute to: text, text one line, Html, PDF
3. Reindex: php bin/magento indexer:reindex
4. Refresh cache

Expected result
1. Custom attribute shows up address book, select box (text one line), and customer information -> customer view
2. Custom attribute shows up billing address & shipping address
3. Custom attribute shows up Invoice Information 

Actual result
1. Custom attribute shows up address book and customer information -> customer view. (Correctly)
2. **Custom Attribute didn't show up billing address, shipping address and invoice information**

**Add custom attribute to address templates**
![1](https://cloud.githubusercontent.com/assets/7329746/15505065/143a1f56-21ec-11e6-83ed-8d473533d180.png)

**Customer information**
![2](https://cloud.githubusercontent.com/assets/7329746/15505068/1440fa24-21ec-11e6-900f-a17665f3e9d9.png)

**Customer Address Book**
![3](https://cloud.githubusercontent.com/assets/7329746/15505066/143ffa52-21ec-11e6-8426-b36853e61dec.png)

Select address (checkout process)
![4](https://cloud.githubusercontent.com/assets/7329746/15505069/144d256a-21ec-11e6-9ce4-ecf457a697df.png)

**Wrong Result**
![5](https://cloud.githubusercontent.com/assets/7329746/15505067/144088c8-21ec-11e6-9860-b86b12304532.png)

**Where is custom attribute?**
![6](https://cloud.githubusercontent.com/assets/7329746/15505292/09e69812-21ed-11e6-9a3f-644ab9fc16e7.png)

**Comment by kllee824** [comment] 2016-07-12 15:13
Same issue on my development, I would like add block, floor, building on billing and shipping address book. any Magento 2 EE version be fixed this issue?

**Comment by tanghia** [comment] 2016-07-13 15:49
I'm not sure about magento 2 EE, however, magento 2.1 CE still has this issue !

**Comment by kllee824** [comment] 2016-07-14 02:54
I already submitted the question to magento support yesterday. waiting the reply.

**Comment by kllee824** [comment] 2016-07-14 03:01
Hi tanghia,

Do you know the structure about knockout js structure on magento 2? I can't following to amend the code if it is a magento bugs? but i need implement my new address attribute

**Comment by tanghia** [comment] 2016-07-14 13:57
I don't have a deep knowledge about knockout js on mage2. This is Alan's article, i hope it is useful.
[http://alanstorm.com/magento_2_knockoutjs_integration](url)

**Comment by sevos1984** [comment] 2016-10-21 08:56
Is this still actual?

**Comment by sevos1984** [comment] 2016-11-09 15:59
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-11-09 15:59 UTC
Labels: bug report, Component: Customer
