### ISSUE TITLE
REST API Configurable Product has price: 0

### ISSUE THREAD

**Issue by fvschie** [magento/magento2#10644] opened 2017-08-24 12:01 UTC
### Description
Configurable products have a price in the store and admin interface, but not in the REST API. We need the price there to be able to send mails about products. Mails will refer to the configurable product, not a specific configuration.

Calculating this price from REST calls is too expensive/slow.

There's also a discrepancy between Admin and store site: If I take the sample data, the Teton Hoodie costs $70. If I reduce, for example, "Teton Pullover Hoodie-M-Black" to $60, the website will show "Teton Pullover Hoodie" costing $60. Admin sees $70 for the configurable product..

### Preconditions

1. Magento 2.1.7

### Steps to reproduce

1. Create a configurable product.
2. Query /rest/V1/products to get a page containing that configurable product

### Expected result

1. Price should be set to the calculated value (lowest, newest, whatever).
2. Alternatively, given that it's not an actual orderable product, a new transient attribute like 'display_price' or some such should be added.

### Actual result

1. Price is 0. Not useful.

**Comment by fvschie** [comment] 2017-09-14 08:08
What does G1/G2 Passed mean?

**Comment by mrkhoa99** [comment] 2017-09-15 01:37
@fvschie please refer to this https://github.com/magento/magento2/issues/7570

**Comment by rogyar** [comment] 2017-09-17 11:39
@rogyar

**Comment by magento-engcom-team** [comment] 2019-01-10 12:50
Hi @engcom-backlog-tomash. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-01-10 13:13
@engcom-backlog-tomash Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97553`, `MAGETWO-97554` were created

**Comment by magento-engcom-team** [comment] 2019-01-31 14:31
Hi @vshatylo. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by sdzhepa** [comment] 2019-08-13 14:46
Hello  @fvschie 

The issue was investigated by the internal Magento team in the scope of Jira tickets: `MAGETWO-97554`, `MAGETWO-97553`
Also was additional discussion and review by Product Managers and as result tickets were closed with resolution `Won't Fix`.
Explanation: It is expected behavior "by design - configurable product doesn't have a price". So , such changes will not be approved and accepted. I have to close this issue as well

**Closed as completed by sdzhepa** 2019-08-13 14:46 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Component: ConfigurableProduct

**Comment by dbashyal** [comment] 2020-09-01 23:38
We are using 3rd party product importer and found $0 for configurable but showing the correct price for option selection. After saving one of the child products manually in admin, configurable started showing correct price of $42.95 in the frontend.
