### ISSUE TITLE
Magento 2 B2B Extension - moving sales_order_grid header to bottom of page

### ISSUE THREAD

**Issue by MihaiComan90** [magento/magento2#35023] opened 2022-01-26 16:36 UTC
### Preconditions (*)

1 .Magento 2.4.3-p1
2. Module magento/extension-b2b:"^1.3"

### Steps to reproduce (*)

1. install a standalone version of 2.4.3-p1
2. require the magento/extension-b2b via composer
3. set:up / static-content / cache:clean
4. access the sales order admin page
5. notice the header of the grid with filters is at the bottom of the page (or even hidden) instead of on top. Notice that the ko template for the grid content and header section is in the wrong order: **grid > header** instead of **header > grid** 

### Expected result (*)

1. Header of the grid should be on top of the page

### Actual result (*)

1. Header is invisible (at the bottom of the page, but hidden), only the sticky header is available when scrolling

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._
--- Priority
- [X] Priority: **P2** _- Should be fixed as early as possible, A defect with this priority could have functionality issues which are not to expectations.

**Comment by engcom-November** [comment] 2022-03-01 07:55
Hi MihaiComan90,

Thank you for reporting the issue,We are unable to  reproduce the issue on Magento 2.4 develop branch.

Steps Followed:

1.installed a standalone version of 2.4.3-p1
2.Installed the magento/extension-b2b via composer
3.Done with set:up / static-content / cache:clean
4.Login to admin panel
5.Accessed the sales order admin page
6.noticed the header of the grid with filters 
Expected result (*)
Header of the grid is on the top of the page 
Actual result (*)
Same as the Expected Result

![image](https://user-images.githubusercontent.com/60198231/156127929-397607d7-9b34-4b1e-8f25-05586487295b.png)

Kindly recheck the issue on Magento 2.4-develop branch with B2B enabled and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by MihaiComan90** [comment] 2022-03-01 10:18
Hello @engcom-November,

Have you deployed a comm version of magento or enterprise? Thanks

**Comment by engcom-November** [comment] 2022-03-02 09:57
Hi MihaiComan90,

Thank you for  reverting back.We tried to reproduce the issue with magento 2.4.3-P1 enterprise edition with B2B.
Thank you.

**Comment by MihaiComan90** [comment] 2022-03-02 10:11
Hello @engcom-November,

I totally forgot to specify, the issue lies with community edition not enterprise with the b2b extension. I know it is a little bit weird and shouldn't be used that way, but that's how you can reproduce it.

Cheerd

**Comment by engcom-November** [comment] 2022-03-08 08:06
Hi @MihaiComan90 ,
Its recommended to verify issues on Magento 2.4-develop branch only as it is the upcoming 2.4.x release and have latest code base. Hence verified the issue on Magento 2.4-develop branch by trying to install B2B Modules without installing Enterprise edition. But we are unable to do that and facing errors 
![image](https://user-images.githubusercontent.com/60198231/157193019-b58dc75b-2cd3-4228-a061-b62042245af0.png)
Kindly verify the issue on Magento 2.4-develop branch with B2B extension and provide missing steps if any if the issue is reproducible.

**Comment by engcom-November** [comment] 2022-03-22 05:21
Hi @MihaiComan90 ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-03-22 05:21 UTC
Labels: Issue:  Cannot Reproduce, Component: Order grid, Issue: needs update, Reported on 2.4.3-p1
