### ISSUE TITLE
Magento 2.4.4 + PHP 8.1 Deprecated Functionality: strtolower

### ISSUE THREAD

**Issue by stormbyte** [magento/magento2#35644] opened 2022-06-20 14:09 UTC
The default value off `null` is no longer valid for php 8.1
https://github.com/magento/magento2/blob/28c1f28a2552de69158b40d1eaf84e45430c16f9/lib/internal/Magento/Framework/Setup/Declaration/Schema/Declaration/SchemaBuilder.php#L318

```
Passing null to parameter #1 ($string) of type string is deprecated in /vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 3483
```
The default value should be an empty string or `AdapterInterface::INDEX_TYPE_INDEX`
As stated in:
`/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:3482`

**Comment by stormbyte** [comment] 2022-06-20 14:14
This happend when upgrading to magento 2.4.4
The current installation already had custom modules with a `db_schema.xml`

Here the index has no `indexType` but default is no longer valid
Example
```
<?xml version="1.0" ?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Setup/Declaration/Schema/etc/schema.xsd">
	<table name="new_table" resource="default" engine="innodb" comment="new_table Table">
		<column xsi:type="int" name="entity_id" padding="10" unsigned="true" nullable="false" identity="true" comment="Entity Id"/>
		<constraint xsi:type="primary" referenceId="PRIMARY">
			<column name="entity_id"/>
		</constraint>
		<column name="sku" nullable="false" xsi:type="varchar" comment="sku" length="255"/>
		<index referenceId="NEW_TABLE_PRODUCT_SKU" indexType="btree">
			<column name="sku"/>
		</index>
        <index referenceId="PRODUCT_SKU" xsi:type="index">
            <column name="sku"/>
        </index>
	</table>
</schema>
```

**Comment by engcom-Delta** [comment] 2022-06-29 12:41
Hi @stormbyte ,
Thank you for raising an issue , Kindly provide steps , actual results and  expected results.

Regards,

**Comment by engcom-Hotel** [comment] 2022-07-11 11:46
Hello @stormbyte,

Thanks for the report and collaboration!

We have tried to reproduce the issue in Magento 2.4-develop branch but we are not able to face the issue mentioned in the main description. We have followed the below steps:
1. Using PHP 8.1 version
2. Edit file `app/code/Magento/Store/etc/db_schema.xml` line no. 27 and remove the `IndexType` as blank:
<img width="483" alt="image" src="https://user-images.githubusercontent.com/51681618/178256680-4be84e5f-43f1-4613-b791-7490d217a21a.png">

3. Ran `bin/magento setup:upgrade` command. We are getting the below error:
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/51681618/178256813-b126b423-ce73-450d-bd1f-74a77d73ef5a.png">

We have followed the below devdocs:
https://developer.adobe.com/commerce/php/development/components/declarative-schema/configuration/#index-subnode

According to the error, it seems that `indexType` is a mandatory value as `'fulltext', 'btree', 'hash'`. So as per the flow, the issue is not reproducible. So please suggest us a way to do the same.

Thanks

**Comment by engcom-Hotel** [comment] 2022-07-25 06:18
Dear @stormbyte,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-07-25 06:18 UTC
Labels: Triage: Dev.Experience, Issue: needs update

**Comment by dylacom** [comment] 2022-08-30 13:26
Hello

have you managed to resolve this issue please?

I am upgrading from 2.3.7-p3 to version 2.4.4 using php8.1

i get 

Deprecated Functionality: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /var/.../vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 3483

**Comment by arun-magento** [comment] 2022-12-20 13:18
add ?? ''  like  strtolower( #your code....   ?? '' )

**Comment by sumeetmagento** [comment] 2023-02-01 11:09
Replace strtolower($string) to strtolower($string ?? '')
It will resolved your issue.
Note:$string replace with your variable
