### ISSUE TITLE
2.1 Cannot create Invoices

### ISSUE THREAD

**Issue by bondimedical3** [magento/magento2#5340] opened 2016-06-29 10:33 UTC
![screenshot_20160629-203009](https://cloud.githubusercontent.com/assets/10808588/16449077/7e4824f2-3e38-11e6-987e-ae5cf55a9f30.png)
![screenshot_20160629-203030](https://cloud.githubusercontent.com/assets/10808588/16449081/86529ad8-3e38-11e6-8c1d-33a7603fc222.png)
I have tried to create an invoice from an order and I receive the message in the first screenshot. If I go to Sales/Invoices in my Admin I receive the error shown in the second screenshot?

**Comment by quienti** [comment] 2016-06-29 15:39
https://github.com/magento/magento2/issues/4632

**Comment by NadiyaS** [comment] 2016-07-01 08:35
Hi @bondimedical3 , 
thanks for reporting this issue. It is already being tracked by MAGETWO-54787 ticket and fix will be delivered soon.
This issue will be closed as duplicate of #4785.

**Closed as completed by NadiyaS** 2016-07-01 08:35 UTC
Labels: Component: Sales

**Comment by nagabushan13** [comment] 2019-04-03 05:23
we are getting the same error in Magento 2.7 can anyone help
