### ISSUE TITLE
Can't deploy an app/code plugin when using symlinks

### ISSUE THREAD

**Issue by mattmary** [magento/magento2#36502] opened 2022-11-21 22:13 UTC
### Preconditions and environment

- Magento version: Magento CLI 2.4.5-p1
- Anything else that would help a developer reproduce the bug
find app/code/ -type l
app/code/(Vendor}

### Steps to reproduce

!. Create a plugin in /var/www/modules/{myvendor_myplugin}
2. Link this plugin into your app/code folder:

- cd {magento2 root folder]
- ln -s /var/www/modules/{myvendor_myplugin} app/code/{myvendor}

3. Deploy the static content
- ./bin/magento setup:static-content:deploy -f
4. Check there is an error 

- Deploy using quick strategy
- frontend/Magento/blank/en_US            2181/2181           ============================ 100%   1 sec               
- adminhtml/Magento/backend/en_US         2879/2879           ============================ 100%   1 sec               
- frontend/Magento/luma/en_US             2197/2197           ============================ 100%   1 sec
Error happened during deploy process: Path "/var/www/modules/{myvendor_myplugin}/view/frontend/templates/temp.phtml" cannot be used with directory "(magento_root)"

In this configuration, symlinks are enabled.

### Expected result

No error

### Actual result

Error happened during deploy process: Path "/var/www/modules/{myvendor_myplugin}/view/frontend/templates/temp.phtml" cannot be used with directory "(magento_root)"

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-01-16 13:21
Hi @mattmary,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible. Kindly refer the screenshots.


**Steps to reproduce**

!. Create a plugin in /var/www/modules/{myvendor_myplugin}
2. Link this plugin into your app/code folder:
  cd {magento2 root folder]
  ln -s /var/www/modules/{myvendor_myplugin} app/code/{myvendor}
3..Deploy the static content
./bin/magento setup:static-content:deploy -f


<img width="1440" alt="Screenshot 2023-01-16 at 6 44 11 PM" src="https://user-images.githubusercontent.com/51680745/212687668-e3da0827-ee84-4a21-a328-7efa32a2baf9.png">




Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Kindly let us if we missed anything.


Thanks.

**Comment by hostep** [comment] 2023-01-16 17:05
@engcom-Bravo: can you try again, but instead of a plugin, add some frontend code in `view/frontend/` in your custom module.

But as far as I remember, this limitation was done on purpose for security reasons some years ago. But I can't remember what for exactly.

**Comment by engcom-Bravo** [comment] 2023-01-17 11:38
Hi @hostep @mattmary 

Thanks for your Contribution.

Yes you are right we have checked as adding the frontend code in  view/frontend/ in our custom module and issue is reproducible.But as this is the expected behaviour so we are closing this issue.


Thanks.

**Closed as completed by engcom-Bravo** 2023-01-17 11:38 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.5-p1
