### ISSUE TITLE
Something went wrong with processing the default view and we have restored the filter to its original state. same as #34811

### ISSUE THREAD

**Issue by cbtrident** [magento/magento2#36553] opened 2022-12-01 11:03 UTC
### Preconditions and environment

- Magento version 2.4.5-p1
database imported using magmi this is the same databased used in magento 2.2.1 with no problem

ubuntu 20.04.5lts
php 7.4.3

### Steps to reproduce

this was report in #34811

1.When entering to products in the Catalogue menu, an error message comes up "Something went wrong with processing the default view and we have restored the filter to its original state." I am unable to search or edit products. I logged in and out and tried other browsers, issue persists.
this can happen when you are viewing pages or changing the order of what been display
yes you can do temporary fix is to clear "ui_bookmark table". > TRUNCATE ui_bookmark; but as soon as you hit the page that has the error it broken again

### Expected result

[Screenshots, logs or description]

### Actual result

[Screenshots, logs or description]
should not stop with error but show may like the feid the error is in be in red
as check the database show nothing

### Additional information

![image](https://user-images.githubusercontent.com/7378212/205035011-44d3456c-94f3-44ca-9a63-b0de4edc23f8.png)

if you need a copy of the database or access to a machine with the problem i can do 
as this is making magento useless to admin and staff trying to check stock and start adding the missing information

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by cbtrident** [comment] 2022-12-01 12:42
i did the command  SELECT * FROM catalog_product_entity WHERE sku IS NULL to see if that show anything and it come back blank

**Comment by engcom-Bravo** [comment] 2022-12-01 15:21
HI @cbtrident,

Thank you for reporting and collaboration.


Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

We are able to navigate to Product Details page and edit the products.


<img width="1415" alt="Screenshot 2022-12-01 at 8 49 50 PM" src="https://user-images.githubusercontent.com/51680745/205090556-62c62525-f816-48be-9cc2-0f538f99e138.png">




Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.



Thanks.

**Comment by cbtrident** [comment] 2022-12-01 15:37
what else can i do to help, do you need a copy of my database or access to my server to see the problem
as right now i can not see what in the database is wrong for this 

plus my problem happen on page 8
up to page 7 is fine for me
![image](https://user-images.githubusercontent.com/7378212/205094723-11c5e4c5-e752-4e09-a4a1-3f8be9bf8e07.png)


i use magmi for import of stock csv
this one
https://github.com/macopedia/magmi-m2 

i will try you 2.4-dev but as it happen in a few version i say there a problem from when imported doing somthing wrong.....

**Comment by cbtrident** [comment] 2022-12-02 11:28
ok in my log was this error 
[2022-12-01T14:22:51.403338+00:00] main.CRITICAL: Exception: Notice: Undefined index: name in /var/www/html/magento2/vendor/magento/module-catalog/Ui/Component/Listing/Columns/ProductActions.php on line 61 in /var/www/html/magento2/vendor/magento/framework/App/ErrorHandler.php:62
Stack trace:
#0 /var/www/html/magento2/vendor/magento/module-catalog/Ui/Component/Listing/Columns/ProductActions.php(61): Magento\Framework\App\ErrorHandler->handler()
#1 /var/www/html/magento2/vendor/magento/framework/View/Element/UiComponent/Context.php(396): Magento\Catalog\Ui\Component\Listing\Columns\ProductActions->prepareDataSource()

so in ProductActions.php line 61 i rem out the line

    public function prepareDataSource(array $dataSource)
    {
        if (isset($dataSource['data']['items'])) {
            $storeId = $this->context->getFilterParam('store_id');

            foreach ($dataSource['data']['items'] as &$item) {
                $item[$this->getData('name')]['edit'] = [
                    'href' => $this->urlBuilder->getUrl(
                        'catalog/product/edit',
                        ['id' => $item['entity_id'], 'store' => $storeId]
                    ),
/*                    'ariaLabel' => __('Edit ') . $item['name'], */
                    'label' => __('Edit'),
                    'hidden' => false,
                ];
            }
        }

and now i can go to all pages so what this line doing that failing

**Comment by engcom-Bravo** [comment] 2022-12-09 11:16
Hi @cbtrident,

Thanks for your Update.
We are unable to reproduce the issue in magento 2.4 develop, it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.

Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.


Kindly check your system requirements as Magento version 2.4.5-p1 supports php 8.1

https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html


Kindly let us know if you have still facing any issue.


Thanks,

**Comment by cbtrident** [comment] 2022-12-09 11:24
why you saying php 8.1 am using 7.4.3 you not answer my question even
i asked what the line doing that i remed out

if this is how you support customer this is very poor

**Comment by engcom-Bravo** [comment] 2022-12-13 12:44
HI @cbtrident,

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.

We have imported below CSV file for products and we are not getting any error.We are change the pages.


[ssss.csv](https://github.com/magento/magento2/files/10217979/ssss.csv)



<img width="1427" alt="Screenshot 2022-12-13 at 3 16 28 PM" src="https://user-images.githubusercontent.com/51680745/207321279-6cd90c9d-2259-49de-bc10-2f74ffe1f2c2.png">


<img width="1422" alt="Screenshot 2022-12-13 at 3 16 59 PM" src="https://user-images.githubusercontent.com/51680745/207321320-b10ff302-4987-4768-a473-c85b33839956.png">



Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.


Thanks.

**Comment by FadedOut** [comment] 2022-12-21 22:24
@cbtrident 

Yeah unfortunately the Magento "maintainers" don't look beyond a very standard use of Magento, if your setup is anything but stock/a few products they usually don't find the problem. It's sad because the system is really good but support does seem to be lacking. 

Luckily I have found the community here to be pretty helpful in getting some things fixed where if we had to "wait" on the "maintainers" to get us the fixes we have to wait 6 months to a year (I have a couple major bug reports that won't be "fixed" until the next update in April, 2.4.6, which is absurd as they were reported on in June of this year, so luckily I received fixes from the community here that make it so I don't have to wait - luckily).

But enough about the rant (even know it is warranted), I have come across a possible similar problem that a fantastic member found the solution for that "might" help you (and many others with this problem). I'm very curious if it will work for you as well. 

Check out this github topic here:
https://github.com/magento/magento2/issues/35759#issue-1302005305
Then check out the actual fix:
https://github.com/magento/magento2/issues/35759#issuecomment-1361023670

It has to do with a overloading of the URI because of the bad method Magento uses (GET instead of POST). Making a tiny change in a file fixed the problem for me (granted in a different location but the error was the same). I'm hoping it will help you, because that will also aleviate my worries of having this happen (like in the orders screen? like seriously?) to me. 

And if it does help, please make sure to give thumbs up or similar to the user on that topic (@oneserv-heuser), it's a fantastic fix for something I have seen many have for like a year or two now.

**Comment by engcom-Bravo** [comment] 2022-12-28 13:39
Hi @FadedOut,

Thanks for your contribution & collaboration over here.

**Comment by engcom-Bravo** [comment] 2023-01-09 06:07
Hi @cbtrident,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-01-09 06:07 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1
