### ISSUE TITLE
Cannot reset password Magento 2.2.6

### ISSUE THREAD

**Issue by webspeaks** [magento/magento2#18297] opened 2018-09-27 17:40 UTC
### Preconditions

1. Upgrade to Magento 2.2.6 from 2.2.5

### Steps to reproduce

1. Upgrade to Magento 2.2.6 from 2.2.5
2. Register as new user from frontend
3. Click forgot password link and enter your email.
4. Check your email, Click on "Reset Password" button in email.
5. On the password reset page, enter new password and submit the form.

### Expected result

1. Password reset should be successful 

### Actual result

1. User is redirected to password reset page with error message: 'Something went wrong while saving the new password'
2. Password is not updated

This issue seems to occur only for new users who register after upgrading to 2.2.6.
I debugged into the code and here is my observation:
1. Print the exception in `Magento\Customer\Controller\Account\ResetPasswordPost` at line 103
2. You will see the exact error which is: `Something went wrong while saving the new password.Warning: SessionHandler::destroy(): Session is not active in /mnt/f/xtras/ubuntu/www/sterno/dev/vendor/magento/framework/Session/SaveHandler.php on line 116`
Seems like Magento is trying to destroy session which is not active.

**Comment by magento-engcom-team** [comment] 2018-09-27 17:40
Hi @webspeaks. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@webspeaks do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by hostep** [comment] 2018-09-27 18:08
Thanks for your report @webspeaks! But it has already been reported before in https://github.com/magento/magento2/issues/18256, let's close this one as it duplicates the other.

**Closed as completed by hostep** 2018-09-27 18:08 UTC
Labels: Issue: Format is valid
