### ISSUE TITLE
I have a concern regarding the order we recently fulfilled. The order was delivered almost 24-25 days ago. In the shipstation, it shows that the order was delivered. but in my dashboard, it's showing that the order is still in process. Why it's not updated??? I need the order feed for that particular order. Can you please provide it???

### ISSUE THREAD

**Issue by anamawasti** [magento/magento2#37664] opened 2023-06-26 06:28 UTC
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by devchris79** [comment] 2023-06-26 09:18
The issues reported here are for Magento bugs, it sounds like you have an extension that is misconfigured or not working called Shipstation. 
A quick search shows a [Shipstation with a forum here](https://community.shipstation.com), you would be best to post questions there and only if it becomes apparent there is a core issue does it require posting here.

For bug reports and other users to help you within this forum there needs to be a clear description of an issue and how it can be replicated.

**Comment by engcom-Bravo** [comment] 2023-06-26 09:22
@devchris79 Thanks for your contribution & collaboration over here.
 
 @anamawasti Kindly refer this comment https://github.com/magento/magento2/issues/37664#issuecomment-1607057840

Thank you for reporting and collaboration.

Kindly provide preconditions, Steps to reproduce, Actual Result, Expected Result, and also kindly provide screenshots if required. These information will be required to proceed further.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-07-07 05:16
Hi @anamawasti,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-07-07 05:16 UTC
Labels: Issue: needs update, Reported on 2.4.x
