### ISSUE TITLE
Replace decimal(12,4) with decimal(9,3) and decimal(13,3)

### ISSUE THREAD

**Issue by colinmollenhour** [magento/magento2#636] opened 2014-08-19 19:24 UTC
MySQL decimal storage uses a minimum of 4 byes and can store 9 digits in these 4 bytes. Going up to 6 bytes you can store 13 digits.

In most cases decimal(9,3) is sufficient and it would save 2 bytes per row/column. The maximum value would be 999,999.999 (1 million) instead of 99,999,999.9999 (100 million). Unless you are selling original artwork in Iranian Rial this should be sufficient. Also according to the ISO list of currencies there are no currencies which use 4 decimal places (but plenty that use 3, so 2 is not acceptable).

For aggregation tables the better storage type would be decimal (13,3) since still 4 decimals are not needed and 13 takes the same storage space as 12. So for the same storage you can store numbers 100 times larger.

It may seem like a minor optimization but in Magento 1 my sales_* tables currently have over 500 decimal(12,4) columns (some are third-party). 2 bytes * 500 columns * 1 million rows is almost 1GB of storage, not to mention the indexed columns. Not huge, but quite significant.

While you're at it, the report_event_types.event_type_id and report_event.event_type_id and report_event.subtype should be tinyint instead of smallint. Maybe these were removed or already changed in M2.. There are probably other columns that could be optimized as well. I think there is even a strong case to be made for changing store_id to "tinyint unsigned" throughout since operating over 256 stores is an edge case.

I realize the DBMS abstraction may be an impediment to this change but considering only MySQL is actually supported I think that is far less important than a database that isn't wasteful of resources.

Lastly, for anyone who is an edge case and decimal(9,3) is not sufficient it should be quite easy to install Magento, dump the database, use sed or a text editor to do a simple replacement and then re-import.

**Comment by ilol** [comment] 2015-01-15 16:03
I created the ticket in our internal system. Thus I am closing this original issue. 
I will try to keep you informed with progress.

**Comment by okorshenko** [comment] 2015-09-24 07:59
Internal Ticket ID: MAGETWO-27587

**Comment by choukalos** [comment] 2015-10-09 16:43
Update on this issue:
- Currency Conversion rates are stored as decimal (24,12) in the table 
- We still have the database using decimal (12,4) in the system ( prices, orders, tax ) but in reality as @barbazul pointed out we're rounding to 2 digits before storing.  As I understand from our core dev there are only a few places now in the code that have that hard coded rounding. 
- Looks like near term we'll be adding a bulk price feature to Magento ( i.e. as @pljspahn described ) where you can have some qty x amount value expressed in > 2 digits of precision that after those values are entered they'd appear as a 2 digits of precision rounded amount.  This is our internal ticket MAGETWO-36192

Asks:
- @pljspahn & others : 
-- what's the commonly accepted way to handle currency conversion for a bulk price feature that you described.  Ie I'm buying 4.015 kg of gummy bears at 6.0045 euro's/kg on the store but want to see that in GBP with a current exchange rate of 1.345 Euros to GBP ....  Do you round after calculation and rounding the price into store currency (Euros, Current Magento - Friendly to Merchant's accountants) before doing the conversion or do all at once (Friendlier to customer)
-- How many digits of precision in the above example would be reasonable to use/allow?  4, 8, ????
** Note assuming; this should all be easy to customize per points above.  Just looking for commonly accepted as our defaults.
- @barbazul if you send in a PR that consolidates our hard coded rounding to 2 digits of precision in a central location so it's easy to customize for you (only accessible by code) I'll make sure it gets in core.

Thanks!

**Comment by kortwotze** [comment] 2015-10-19 14:47
I know this is maybe the wrong place, but I think I have a solution for the tax/discound rounding issues.
I post here, because this is the thread I found while researching this topic - if you like my idea, please refer me to the correct place for this.

So, in my understanding the problem is the way magento calculates discounts, tax and totals. It calculates them all separately and also rounds them separately which is wrong.

Example:

Item price: 4,30 €
Discount: 5%

Magento does:
Discount amount: 0,2150 €
New item price: 4,085€

Magento displays both sums rounded up, which causes:
Discount: 0,22 €
Item price: 4,09 €
Old item price: 4,30 € - MISSMATCH.

What should have happened is:
Magento calulates the discount amount, rounds it first and THEN substracts that from the item price.
You would then end up with:

Item price: 4,30 €
Discount: 0,2150 ~ 0,22 €
New item price: 4,30 € - 0,22 = 4,08 €.

What I did to "solve" this: I changed the column definitions from the following fields from DECIMAL(12,4) to DECIMAL(12,2)

sales_flat_order_item.discount_amount
sales_flat_order_item.base_discount_amount
sales_flat_order_item.discount_invoiced
sales_flat_order_item.base_discount_invoiced

sales_flat_quote_item.discount_amount

**Comment by choukalos** [comment] 2015-10-20 19:51
@kortwotze Thanks!  I'll pass this insight along to our Tax Architect @tang-yu and have him look at it.  Likely he won't be able to provide feedback on this for a few weeks.  We had a similar issue with discounts that was found earlier in our develop branch for Magento 2 and I believe corrected.  Are you still seeing your example on a recent Magento 2 develop branch site?

**Comment by kortwotze** [comment] 2015-10-20 20:42
To be perfectly honest - as I stated in the beginning: This might be in the wrong place, since I am using Magento 1.9.2.0 for that and my research for that brought me to my conclusion above. I thought, you might be able to use that in Mage2, because in Mage1 its still really messed up in that way. I looked into Mage2 just because I thought I´d find another approach to solve this issue. Then I found this thread and saw, there was still discussion on how to store decimals (which decimals and taxes are) and I found my "solution" beeing close to this topic (though for a different Magento, I agree fully).

So, if this does not belong here, please redirect me to a proper place - otherwise, please feel free to tell me, what you think :)

I did some other tweaks that might contribute to finally fixing rounding issues on taxes and discounts in Mage1 which I will write about soon(tm).

**Comment by choukalos** [comment] 2015-10-21 20:52
@kortwotze Cool.  We rewrote the tax engine in Magento 2 and have some minor functional differences.  

What you're describing in Magento 1 is a recently identified issue ( discount rounding issues when interacting with other rounding points - item tax, shipping, FPT ) and has a slightly different fix in M1 code which mirrors our engine changes in M2 ( we carry both - and + delta-rounds rather than only + ones ).  We're making some tweaks to our M2 tax engine to address them and will effectively be porting those fixes to a future M1x release.  @piotrekkaminski is aware of this work and tracking in our M1.x backlog.

**Comment by tang-yu** [comment] 2015-10-21 21:59
@kortwotze , I agree with you that most of the rounding issue was caused by rounding prices separately and then adding prices together. We changed the calculation logic so that we round tax or discount first and subtract tax to get price excluding tax. We did this in the code, e.g., https://github.com/magento/magento2/blob/develop/app/code/Magento/Tax/Model/Calculation/UnitBaseCalculator.php#L56 and https://github.com/magento/magento2/blob/develop/app/code/Magento/Tax/Model/Calculation/UnitBaseCalculator.php#L81.

**Comment by kortwotze** [comment] 2015-10-22 06:46
@tang-yu @choukalos Thank you very much for this input. I am very glad to see the way, Mage2 is handling this (I did not look into this until now, because we are not bothering with Mage2 for now). The main question right now is: When will this backport fix be released for Magento 1.9.x.x? I dont really want to go live with those database hacks for our new project, but we have a deadline and I will use my approach to secure that deadline. :sadface:

Anyway, thanks a lot for this input :) I was very scared of rewriting Mage_Tax and Mage_Sales for that, because it is sooo much. :D

**Comment by piotrekkaminski** [comment] 2015-10-22 21:48
@kortwotze we have plans to improve this in 1.x but it will take time - the next bugfix release is expected next year.

**Comment by kortwotze** [comment] 2015-10-23 10:08
Thanks for the reply. Though its sad, that the fix is expected next year, it is good, that the fix eventually will be released. I really appreciate it :)

**Comment by barbazul** [comment] 2015-12-11 12:12
After a complete year away from the M2 project I am finally forced to get back to it due to its recent release and @benmarks fundamentals course that I am currently taking.

I'll play around with M2 a little bit longer, getting the hang of it and then I'll send my PR (if this ihas not been done already by someone else)

**Comment by piotrekkaminski** [comment] 2016-08-26 03:04
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Replace-decimal-12-4-with-decimal-9-3-and-decimal-13-3/idi-p/45490).

**Closed by piotrekkaminski** 2016-08-26 03:04 UTC
Labels: acknowledged, improvement, moved_to_forums, PROD

**Comment by ctadlock** [comment] 2018-08-02 00:44
@magento-engcom-team Is this scheduled to be in in 2.3?

**Comment by Nix-id** [comment] 2019-03-17 14:38
@ctadlock @magento-engcom-team
`quote` and  `sales_order` tables still (12,4)  in M2.3.0

**Comment by DanielRuf** [comment] 2019-03-17 14:50
Imo we should keep 4 as many shops need this precision. Don't change this.

**Comment by Nix-id** [comment] 2019-03-17 14:55
this is not usable if you want add BTC as Currency to shop.
i found some different solutions how add BTC as currency - but shop have many problems with work with BTC because tables fields have decimal(12,4)

also hardocded precision = 2
for example
```
./vendor/magento/module-directory/Model/PriceCurrency.php
/**
     * Round price
     *
     * @param float $price
     * @return float
     */
    public function round($price)
    {
        return round($price, 2);
    }
```

**Comment by DanielRuf** [comment] 2019-03-17 15:18
You can apply patches if you need a different logic.
