### ISSUE TITLE
Attribute option not showing on configurable product detail page

### ISSUE THREAD

**Issue by hemendrametawolf** [magento/magento2#38348] opened 2024-01-11 11:23 UTC
### Summary

Magento: 2.4.4.-p1
using luma theme

I created new product as configurable product. it created successfully in back end. now when i am opening product detail page it not showing attributes option on the product detail page and not showing add to cart button.

Is there any configuration need to check.

### Examples

![image](https://github.com/magento/magento2/assets/114897672/50def103-a123-4a89-8d60-bdd8161271e4)

### Proposed solution

It should be show attribute option on product detail page

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hemendrametawolf** [comment] 2024-01-11 11:23
@magento give me 2.4.4-p1 -develop instance

**Comment by hemendrametawolf** [comment] 2024-01-11 11:26
@magento give me 2.4.4 -develop instance

**Comment by engcom-Bravo** [comment] 2024-01-12 10:39
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-01-12 10:53
Hi @hemendrametawolf,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


![Screenshot from 2024-01-12 16-21-19](https://github.com/magento/magento2/assets/51680745/c5705cd3-e052-40e8-9c19-e2285a2415f9)


Product detail page has showing attribute option and also add to cart button also working fine for a configurable product.Please check whether the products are in outofstock.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-01-23 04:56
Hi @hemendrametawolf,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-01-23 04:56 UTC
Labels: Issue: needs update, Reported on 2.4.4-p1
