### ISSUE TITLE
Up/down does not functioning at create configuration popup

### ISSUE THREAD

**Issue by renard123** [magento/magento2#27507] opened 2020-03-31 05:04 UTC
Up/down does not functioning at create configuration popup

### Preconditions (*)
Magento 2.3.4
Chrome: Version 80.0.3987.163
OS: Windows 7

### Steps to reproduce (*)

1. Admin -> Catalog -> Products
2. Add Configurable product
3. Create Configuration
4. Create New Attribute
5. Open all section

### Expected result (*)
It should work fine

### Actual result (*)
Not functioning

**Comment by krishprakash** [comment] 2020-03-31 05:05
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-31 05:05
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-03-31 05:06
Hi @krishprakash, here is your [Magento instance](https://i-27507-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27507-2-4-develop.instances.magento-community.engineering/admin_b780](https://i-27507-2-4-develop.instances.magento-community.engineering/admin_b780)
Login: `ef2a07bd` Password: `cdced6548ac3`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2020-03-31 05:13
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32930` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by progreg** [comment] 2020-03-31 16:40
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-31 16:40
Hi @progreg. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-03-31 16:40
Hi @progreg, here is your [Magento instance](https://i-27507-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27507-2-4-develop.instances.magento-community.engineering/admin_ec90](https://i-27507-2-4-develop.instances.magento-community.engineering/admin_ec90)
Login: `7f12c01a` Password: `c982dad1a710`
Instance will be terminated in up to 3 hours.

**Comment by edenduong** [comment] 2020-04-04 11:15
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-04 11:15
Hi @edenduong. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-04 11:16
Hi @edenduong, here is your [Magento instance](https://i-27507-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27507-2-4-develop.instances.magento-community.engineering/admin_7d00](https://i-27507-2-4-develop.instances.magento-community.engineering/admin_7d00)
Login: `05b667b9` Password: `b4f139e32d05`
Instance will be terminated in up to 3 hours.

**Comment by madhu-ranosys** [comment] 2020-04-06 06:26
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-06 06:26
Hi @madhu-ranosys. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-06 06:27
Hi @madhu-ranosys, here is your [Magento instance](https://i-27507-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27507-2-4-develop.instances.magento-community.engineering/admin_bdbe](https://i-27507-2-4-develop.instances.magento-community.engineering/admin_bdbe)
Login: `6911d381` Password: `24ea4d6364b0`
Instance will be terminated in up to 3 hours.

**Comment by madhu-ranosys** [comment] 2020-04-06 06:41
> Hi @madhu-ranosys, here is your [Magento instance](https://i-27507-2-4-develop.instances.magento-community.engineering).
> Admin access: https://i-27507-2-4-develop.instances.magento-community.engineering/admin_bdbe
> Login: `6911d381` Password: `24ea4d6364b0`
> Instance will be terminated in up to 3 hours.

I have gone through the below steps:
  1. Admin -> Catalog -> Products
  2.  Add Configurable product
  3. Create Configuration
  4. Create New Attribute
  5. Open all section

All seems working fine. I didn't find such issue.

**Comment by krishprakash** [comment] 2020-04-06 07:00
Hi @madhu-ranosys, Reviewed on given instance
Drop-downs icons not updated once open and close it.
![image](https://user-images.githubusercontent.com/46617848/78531037-5801c480-7802-11ea-96cd-4d69e5a60872.png)

**Comment by madhu-ranosys** [comment] 2020-04-06 07:11
Hi @krishprakash , I am checking the same way. It's working fine.
![001](https://user-images.githubusercontent.com/59955325/78531847-d90d8b80-7803-11ea-9e04-3087fc401107.png)
![002](https://user-images.githubusercontent.com/59955325/78531851-dad74f00-7803-11ea-98bc-80fbd1b3a0aa.png)


Can you let me know which browser are you using and the version?

**Comment by krishprakash** [comment] 2020-04-06 07:17
@madhu-ranosys, Updated in issue description.

**Comment by madhu-ranosys** [comment] 2020-04-06 07:32
> @madhu-ranosys, Updated in issue description.

I am checking in the ubuntu chrome latest version. It is working fine there also.
Can you please confirm is this the issue with the only window 7 Chrome 80 So I will check on the same version?

**Comment by krishprakash** [comment] 2020-04-06 07:36
Yes, You can check in windows 7 chrome 80 version browse as I updated in description.

**Comment by madhu-ranosys** [comment] 2020-04-06 07:37
> Yes, You can check in windows 7 chrome 80 version browse as I updated in the description.

Ok

**Comment by madhu-ranosys** [comment] 2020-04-08 06:49
I am not able to reproduce this issue. 
Thanks!

**Comment by sdzhepa** [comment] 2020-06-22 16:07
Reverified on the latest `2.4-develop`

Not able to repro this issue
![2020-06-22_11-06-58](https://user-images.githubusercontent.com/3409584/85309711-9c534700-b478-11ea-86e9-53433d95481f.jpg)

**Closed as completed by sdzhepa** 2020-06-22 16:07 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Backend, Component: ConfigurableProduct, Reproduced on 2.4.x, Reported on 2.3.4
