### ISSUE TITLE
Product video doesn't play when it is not placed first in the sort order.

### ISSUE THREAD

**Issue by aashan10** [magento/magento2#26709] opened 2020-02-05 09:48 UTC
### Preconditions (*)

- Magento Version : [2.2.9](https://github.com/magento/magento2/releases/tag/2.2.9)

 - PHP 7.1.32 
 - MySQL  Ver 14.14 Distrib 5.7.28, for Linux (x86_64) using  EditLine wrapper

- Sample data is used.
 

### Steps to reproduce 

1. Edit the simple product of a configurable product and add a product video. ( In our case, we have used Chaz Kangeroo Hoodie as Configurable Product and Chaz Kangeroo Hoodie-XS-Black as its simple product )
2. The video used is [https://www.youtube.com/watch?v=L4XjEuCPOJY](https://www.youtube.com/watch?v=L4XjEuCPOJY).
3. Now, sort the video in media gallery to make it seen anywhere but not the first position.
4. Save the product.
5. View the configurable product in storefront product details page.
6. Click on the color swatch to view the simple product media gallery.
7. Click the video thumbnail and play the video.

![Imgur](https://i.imgur.com/Hstlpw0.png)
![Imgur](https://i.imgur.com/Zvgmr2d.png)

### Expected result 

1. The video should play when clicked on the thumbnail.

### Actual result

1.  Only the thumbnail image of the youtube video is visible.
2. The video is not played if the video is not in the first position according to the sort order in admin panel.
![Imgur](https://i.imgur.com/HnVvYTq.png)

![Imgur](https://i.imgur.com/n6khrlA.png)

![Imgur](https://i.imgur.com/I9UqgJf.png)

![Imgur](https://i.imgur.com/GF5dT3D.png)

### Addition Information 
https://github.com/magento/magento2/issues/26709#issuecomment-602561906

I could easily reproduce the issue on the latest 2.4-develop
![youtube_video_26709](https://user-images.githubusercontent.com/51680745/77316818-bfa01600-6d12-11ea-8d1c-52623150ef46.gif)

**Comment by ajijshekh123** [comment] 2020-02-05 11:21
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-05 11:21
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-05 11:21
Hi @ajijshekh123, here is your [Magento instance](https://i-26709-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26709-2-4-develop.instances.magento-community.engineering/admin_723b](https://i-26709-2-4-develop.instances.magento-community.engineering/admin_723b)
Login: `d5dd5377` Password: `0ad3122db139`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2020-02-05 12:49
Hello @aashan10,
After clicking on a video, Youtube video is played properly. 
See attached the video and Let me know which points are missing in my end or is it working fine.

![Issue](https://user-images.githubusercontent.com/24711761/73843116-fe057280-4843-11ea-9121-e8f35e3ee553.gif)


Thanks.

**Comment by matthew-muscat** [comment] 2020-02-24 05:53
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-24 05:53
Hi @matthew-muscat. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-24 05:54
Hi @matthew-muscat, here is your [Magento instance](https://i-26709-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26709-2-4-develop.instances.magento-community.engineering/admin_36ba](https://i-26709-2-4-develop.instances.magento-community.engineering/admin_36ba)
Login: `c6016c60` Password: `7ca19cfdb748`
Instance will be terminated in up to 3 hours.

**Comment by matthew-muscat** [comment] 2020-02-24 06:19
@ajijshekh123 — confirming i'm able to repeat the issue on Magento v2.3.4 and also the latest Magento 2.4-develop snapshot.

The behaviour specifically occurs when viewing a configurable product, making a selection of a specific configuration, which contains a video located in any area other than the first image position.


If the instance remains online, this can be viewed over at...
https://i-26709-2-4-develop.instances.magento-community.engineering/example-configurable-product.html

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2001917/75132109-d2cac080-5729-11ea-9fe0-820913f45bda.gif)

**Comment by matthew-muscat** [comment] 2020-02-24 08:15
Upon further investigation, it appears that this issue is due to the data on the `Magento_ProductVideo/js/fotorama-add-video-events` widget

Specifically `optionsVideoData` looks to have the video data always set as the first object in the array of product media gallery assets.

It would appear the sort order of the gallery is not occurring in https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/ConfigurableProduct/Block/Plugin/Product/Media/Gallery.php#L62

**Comment by vishvesshah** [comment] 2020-02-29 09:48
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-29 09:48
Hi @vishvesshah. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-29 09:48
Hi @vishvesshah, here is your [Magento instance](https://i-26709-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26709-2-4-develop.instances.magento-community.engineering/admin_5ee0](https://i-26709-2-4-develop.instances.magento-community.engineering/admin_5ee0)
Login: `784cad54` Password: `c164cf35ac63`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment] 2020-03-23 12:31
I could easily reproduce the issue on the latest 2.4-develop
![youtube_video_26709](https://user-images.githubusercontent.com/51680745/77316818-bfa01600-6d12-11ea-8d1c-52623150ef46.gif)

Seems like there is no _Play_ on the video

**Comment by magento-engcom-team** [comment] 2020-03-23 12:31
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32647` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by LucasCalazans** [comment] 2020-04-04 14:23
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-04 14:23
Hi @LucasCalazans. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-04 14:24
Hi @LucasCalazans, here is your [Magento instance](https://i-26709-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26709-2-4-develop.instances.magento-community.engineering/admin_4c65](https://i-26709-2-4-develop.instances.magento-community.engineering/admin_4c65)
Login: `597c5e5c` Password: `8e599f4e1745`
Instance will be terminated in up to 3 hours.

**Comment by tuyennn** [comment] 2022-09-30 04:09
https://github.com/magento/magento2/issues/29690
https://github.com/magento/magento2/issues/28875
https://github.com/magento/magento2/pull/30938

**Comment by engcom-Delta** [comment] 2024-06-12 19:44
Hi @aashan10 ,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.

<img width="1256" alt="Screenshot 2024-06-13 at 12 50 46 AM" src="https://github.com/magento/magento2/assets/51681379/b4bc0e25-5ec8-41b2-ad4e-4ded218c3b5f">

<img width="1296" alt="Screenshot 2024-06-13 at 12 50 55 AM" src="https://github.com/magento/magento2/assets/51681379/7f1dbbc3-dd05-429b-85f6-8f1a39b765ef">

<img width="1417" alt="Screenshot 2024-06-13 at 12 51 49 AM" src="https://github.com/magento/magento2/assets/51681379/16e6972b-6204-4542-b4e7-e6af60101cff">

<img width="1440" alt="Screenshot 2024-06-13 at 12 54 32 AM" src="https://github.com/magento/magento2/assets/51681379/55fade1a-b28b-42d9-b87f-20ce97a7c59a">

<img width="1429" alt="Screenshot 2024-06-13 at 12 55 28 AM" src="https://github.com/magento/magento2/assets/51681379/0416f9ab-9262-4211-8280-37f47afcdf4a">

<img width="1395" alt="Screenshot 2024-06-13 at 1 05 07 AM" src="https://github.com/magento/magento2/assets/51681379/14263405-ba88-4b77-8e7b-3e43cdbe65d5">

<img width="1440" alt="Screenshot 2024-06-13 at 1 05 56 AM" src="https://github.com/magento/magento2/assets/51681379/393612cb-d3ad-4491-820a-244441273fe9">

<img width="1440" alt="Screenshot 2024-06-13 at 1 06 05 AM" src="https://github.com/magento/magento2/assets/51681379/d5d74965-2621-4d98-961d-9721e98d3597">

<img width="1363" alt="Screenshot 2024-06-13 at 1 08 18 AM" src="https://github.com/magento/magento2/assets/51681379/cfafcc1f-8a97-4ef1-9b3d-a4d7cb102621">


Hence we are closing this issue.

Thanks,

**Closed as completed by engcom-Delta** 2024-06-12 19:44 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: ConfigurableProduct, Component: ProductVideo, Reproduced on 2.4.x, Priority: P3, Severity: S3, Triage: Done, Progress: done, Reported on 2.4.0
