### ISSUE TITLE
Add to cart issue

### ISSUE THREAD

**Issue by ovekeryk** [magento/magento2#4177] opened 2016-04-15 21:43 UTC
### Preconditions
1. Magento 2.1

### Steps to Reproduce
1. Set "Qty Uses Decimals" field is set to "yes" for a product
2. Add product to cart with quantity "0"

### Actual result
1. "We don't have as many "xxx" as you requested."

### Expected result
1. Product is added to the cart

### Additional informaion
Better to use value from "Minimum Qty Allowed in Shopping Cart" field of inventory module when it enabled instead of "1".

ref: https://github.com/magento/magento2/blob/develop/app/code/Magento/Quote/Model/Quote/Item.php#L306

**Comment by heyitsroberthe** [comment] 2016-04-28 21:08
Hi,

It looks like we can definitely make improvements to the Advanced Inventory settings with regards to quantities involving decimals. Your suggestion to the qty check makes sense as well.

**Comment by piotrekkaminski** [comment] 2016-05-24 15:34
Internal issue MAGETWO-53429

**Comment by ashburystudios** [comment] 2016-11-14 00:13
Hi all, Any update on this. Need this ASAP to work on a new site and cant move forward. Thank you, Mike

**Comment by degaray** [comment] 2017-01-08 03:26
I have the same issue.

**Comment by magento-engcom-team** [comment] 2017-10-05 13:30
@AlexanderVekerik, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-05 13:30 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by ravihandsintechnology** [comment] 2017-12-19 11:22
i am trying to update cart with the help of rest/v1/carts/cartid/items/itemid

the product is updating sucessfully when the stock of the product is greater than 1
but when the stock is 1 the product is not updating

it gives error
stdClass Object
(
    [message] => We don't have as many "product name" as you requested.
)
