### ISSUE TITLE
Date Filter not working on Reports and Order Grid

### ISSUE THREAD

**Issue by vijay234495** [magento/magento2#38621] opened 2024-04-16 02:38 UTC
### Preconditions and environment

Magento 2.4.6

### Steps to reproduce

1. Go to Reports -> Sales -> Orders
2. Select From and To date
3. Click 'Show Report' button

![image](https://github.com/magento/magento2/assets/6781656/487454ca-7189-4dec-ba63-8d390118894d)

### Expected result

Orders summary should be show on the grid

### Actual result

Orders summary  not showing on the grid

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2024-04-16 07:49
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2024-04-16 08:26
Hi @vijay234495 

Thanks for reporting and collaboration. 

Verified the issue on magento 2.4 dev instance but the issue is not reproducible.

Steps to reproduce :

1. Go to Reports -> Sales -> Orders
2. Select From and To date
3. Click 'Show Report' button

We are getting the reports when filtered by date.

Please verify the screenshot attached. Let us know if we missed anything.

<img width="1440" alt="Screenshot 2024-04-16 at 1 53 39 PM" src="https://github.com/magento/magento2/assets/60198592/eb48911c-8b4c-44fb-8d7a-c2b51b8ec82d">

**Comment by vijay234495** [comment] 2024-04-16 08:35
Hi @engcom-Dash,

Thanks for checking. Is possible provide the access for develop instance?

**Comment by engcom-Dash** [comment] 2024-04-16 10:00
Hi @vijay234495 

You can use the below instance or can request the bot for a fresh instance.

Admin access: https://b79086fa11680f9cff1dd7fb75e152eb.instances-prod.magento-community.engineering/admin_490c
Login: e2722fb5
Password: dd0f7eb94195

**Comment by hostep** [comment] 2024-04-16 21:28
Sounds like a duplicate of these two:
- https://github.com/magento/magento2/issues/38590
- https://github.com/magento/magento2/issues/38589

Try upgrading the `laminas/laminas-filter` package via composer to the latest version (versions 2.35.0 and 2.35.1 contained a bug that could cause this problem)

**Comment by engcom-Dash** [comment] 2024-04-17 13:48
Hi @vijay234495 

As per the above comment try upgrading the laminas/laminas-filter package via composer to the latest version.

We are closing this issue. if you are still facing the issue please feel free to reopen the issue.

Thanks.

**Closed as completed by engcom-Dash** 2024-04-17 13:48 UTC
Labels: Issue: needs update, Reported on 2.4.6
