### ISSUE TITLE
Braintree Gateway - An error occurred on the server, please try again

### ISSUE THREAD

**Issue by Rich8881** [magento/magento2#7066] opened 2016-10-18 08:08 UTC
Hi we keep getting this error when trying to check out on Braintree on our Magento 2.1 store

'An error occurred on the server, please try again'

We're using a sandbox account

We've tried every fix under the sun including removing the table prefix but the error remains , after much braintree support (if you can call it that) we have deduced nothing is wrong on there side and the payments show up on the sandbox control panel. Nothing shows up in the error logs for this ...

**Preconditions** 

Magento ver. 2.1.1
Braintree Payment Gateway Sandbox

**Steps to Reproduce** 
Run through the checkout process using Braintree as the payment gateway in sandbox mode

**Expected Result** 
A succesful transaction

**Actual Result**
"An error occurred on the server ,please try again

**Comment by veloraven** [comment] 2016-10-18 08:22
@Rich8881 thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by Rich8881** [comment] 2016-10-18 08:36
Hi sorry I'm not really a developer type , to me the expected result is it works the actual result is that it does not ... i'll reformat it

**Comment by Rich8881** [comment] 2016-10-18 08:41
Hi we keep getting this error when trying to check out on Braintree on our Magento 2.1 store

'An error occurred on the server, please try again'

We're using a sandbox account

We've tried every fix under the sun including removing the table prefix but the error remains , after much braintree support (if you can call it that) we have deduced nothing is wrong on there side and the payments show up on the sandbox control panel. Nothing shows up in the error logs for this ...

**Preconditions** 

Magento ver. 2.1.1
Braintree Payment Gateway Sandbox

**Steps to Reproduce** 
Run through the checkout process using Braintree as the payment gateway in sandbox mode

**Expected Result** 
A succesful transaction

**Actual Result**
"An error occurred on the server ,please try again

**Comment by viktym** [comment] 2016-10-20 16:01
Hi @Rich8881 
Unfortunately, I could not reproduce the issue as you described it.
Placing order with our sandbox Braintree account  works well.
Could you please enable Debug option in Advanced Braintree Settings and check /var/log/debug.log after placing order. There should be detailed information about Braintree requests and responses. Also, please check /var/report folder for any information.
Thanks for reporting this issue.

**Comment by signalprime** [comment] 2016-11-03 17:02
I have the same issue on 2.1.2, upgraded from 2.0.7.  I have enabled the debug option, but I don't see any helpful clues.  Not sure what to do next.  Any ideas?  I have disabled all validation and fraud protection trying to diagnose the issue, but again.. no real clues... yet

**Comment by PhiIipp** [comment] 2016-11-03 17:23
Had same issue, what is the response message in debug.log ? For me it was postal code missing or must be number form validation allowerd \* . This caused that braintree rejected

**Comment by signalprime** [comment] 2016-11-03 17:32
The response was:
 'client' => 'Magento\Braintree\Gateway\Http\Client\TransactionSale',
  'response' => 
  array (
  ),
) {"is_exception":false} []

But the good news is that it is solved now, but I'm not sure how.  My steps were to disable all cache, and flush all cache.  I saved the payment gateway configuration, and retried.  It worked this time.

**Comment by PhiIipp** [comment] 2016-11-03 17:37
Ok good that its working  now  my response code looked different

**Comment by viktym** [comment] 2016-11-04 10:53
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Comment by viktym** [comment] 2016-11-04 10:53
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Comment by viktym** [comment] 2016-11-04 10:54
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Comment by viktym** [comment] 2016-11-04 10:54
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Comment by viktym** [comment] 2016-11-04 10:54
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by viktym** 2016-11-04 10:54 UTC
Labels: bug report, Progress: needs update, Component: Payment

**Comment by EmilyPepperman** [comment] 2017-01-03 21:20
We have a live Magento 2.1.3 website getting many orders a day successfully... several customers have gotten the  "An error occurred on the server. Please try to place the order again." while trying to checkout. Which took me a while to recreate. When we look in the failed transactions in our Braintree account we see those customers got Soft Declines... so I feel this issue is just of poor error wording for customers that need to  make sure their Billing addresses are correct or have a talk with their bank to let the charge through.

In our Magento 1.9.x website we got Failed Transaction notifications and followed up better with customers when we saw payment failure issues. We wish this feature was in M2 as well.
