### ISSUE TITLE
If you going to make credit memo for an order, Update Qty's button not aligned proper with respective colum

### ISSUE THREAD

**Issue by cedarvinda** [magento/magento2#25202] opened 2019-10-22 06:12 UTC
If you going to make credit memo for an order, Update Qty's button not aligned proper with respective colum

### Preconditions (*)
1. Magento 2.3.x
2. php 7.2

### Steps to reproduce (*)
Step-1: Login to admin panel 
Step-2: Go sales > order menu 
Step-3: Open any order and make invoice for this order 
	OR
Step-4: You can open invoiced order 
Step-5: and click in Credit Memos link and scroll page bellow and refer screenshot

### Expected result (*)
![image_2019_10_20T10_34_30_192Z](https://user-images.githubusercontent.com/26018716/67261942-85f78480-f4c0-11e9-9bd1-f61309416d26.png)

### Actual result (*)
![image_2019_10_20T10_34_00_951Z](https://user-images.githubusercontent.com/26018716/67261950-8c85fc00-f4c0-11e9-8668-3930c31df580.png)

**Comment by shikhamis11** [comment] 2019-10-22 06:13
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-10-22 06:13
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-10-22 06:13
@shikhamis11 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-10-22 06:13
Hi @shikhamis11, here is your [Magento instance](https://i-25202-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25202-2-3-develop.instances.magento-community.engineering/admin](https://i-25202-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-10-22 06:18
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21967` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by vsevolod-tarasov** [comment] 2019-11-19 15:49
@magento I am working on it

**Comment by vsevolod-tarasov** [comment] 2019-11-19 15:57
Cannot reproduce

**Closed as completed by vsevolod-tarasov** 2019-11-19 15:57 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Progress: PR Created, Component: Admin
