### ISSUE TITLE
Product page detail of Simple product have Required Check box Custom options don't show an error message when clicked Add To cart 

### ISSUE THREAD

**Issue by ph4mHoa** [magento/magento2#37946] opened 2023-09-01 03:54 UTC
### Preconditions and environment

- Magento 2.4.6-p2
- Guest
- Simple product have **required Check box custom option** 

### Steps to reproduce

https://github.com/magento/magento2/assets/49557978/0ed39739-d02b-4c5f-ad68-0ef83935bdba

1. In Product Detail Page of Simple product have **required Check box custom option** 
2. Don't select any option
3. Click add to cart 

### Expected result

error message "this is required field" show up

### Actual result

Don't have any message

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by patv81** [comment] 2023-09-01 04:27
Hi @engcom-Bravo , this issue on 2.4.**6**-p2

in file lib/web/jquery/jquery.validate.js of 2.4.6.p2
When I revert this change 
![image](https://github.com/magento/magento2/assets/49557978/a9123346-0d09-4d30-9476-08244fb66d9d)
it works as normal

**Comment by engcom-Bravo** [comment] 2023-09-01 10:26
Hi @patv81,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.


**Steps to reproduce** :

- In Product Detail Page of Simple product have required Check box custom option
- Don't select any option
- Click add to cart


For custom options having option type has a Dropdown it is working fine showing message as **This is a required field**.



<img width="1385" alt="Screenshot 2023-09-01 at 1 00 04 PM" src="https://github.com/magento/magento2/assets/51680745/17efc959-8ba1-49f1-883c-002edfb4f203">




For Custom options having other option types it is not showing error message.


<img width="1405" alt="Screenshot 2023-09-01 at 12 59 36 PM" src="https://github.com/magento/magento2/assets/51680745/c16fd00a-6907-45f8-bc2c-8c9359d267bd">




Hence Confirming the issue.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-10-27 06:26
Closing as Duplicate https://github.com/magento/magento2/issues/38084

**Closed as completed by engcom-Bravo** 2023-10-27 06:26 UTC
Labels: duplicate, Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Progress: done, Component: Frontend, Area: Product, Reported on 2.4.5-p2
