### ISSUE TITLE
Sub menu link not clickable in Ipad.

### ISSUE THREAD

**Issue by nidhishah9429** [magento/magento2#38290] opened 2023-12-15 10:57 UTC
### Preconditions and environment

Magento fresh installation with sample data. Open it to the iPad Pro (1024 X 1366) /iPad Air (820 X 1180).

### Steps to reproduce

Step 1: Open the Magento 2 site on iPad Pro (1024 X 1366) /iPad Air (820 X 1180).
Step 2: Try to click on the Women -> Tops category.

### Expected result

Users can click on the Tops category

### Actual result

The page is redirected to Women category

### Release note

Magento 2.4.6

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-12-18 08:42
Hi @nidhishah9429,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

**Steps to reproduce**

- Step 1: Open the Magento 2 site on iPad Pro (1024 X 1366) /iPad Air (820 X 1180).
- Step 2: Try to click on the Women -> Tops category.



[Screencast from 18-12-23 02:09:06 PM IST.webm](https://github.com/magento/magento2/assets/51680745/35b942ca-65b8-4111-aea1-4dfa3611a740)



We are able to click on the Tops Category.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by nidhishah9429** [comment] 2023-12-19 08:48
https://github.com/magento/magento2/assets/32189523/0196fdb5-24bc-4492-82f7-a36207951572

When you click on the Women for access sub-category, the page is redirected (loading). check the cursor in my video. This same thing happens in your video also.

It should not redirect and work like mobile view.

**Comment by engcom-Bravo** [comment] 2023-12-26 08:30
Hi @nidhishah9429,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

[Screencast from 26-12-23 12:18:48 PM IST.webm](https://github.com/magento/magento2/assets/51680745/5a31da25-1a0a-457e-bceb-a2f5fbefd13e)


We are able to access the Sub Category of the Womens Category.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-01-08 05:53
Hi @nidhishah9429,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-01-08 05:53 UTC
Labels: Issue: needs update, Reported on 2.4.x
