### ISSUE TITLE
MySQL errors while running setup:upgrade (Incorrect index name 'PRIMARY')

### ISSUE THREAD

**Issue by hoshiray** [magento/magento2#35708] opened 2022-06-30 07:44 UTC
### Preconditions and environment

- 2.4.4
- Upgraded from 2.3.2

### Steps to reproduce

Upgrade from version 2.3.2 with some data in database especially in `catalog_url_rewrite_product_category` table. Then run `bin/magento setup:upgrade`

### Expected result

Command ran successfully and DB tables are updated

### Actual result

SQLSTATE[42000]: Syntax error or access violation: 1280 Incorrect index name 'PRIMARY', query was: ALTER TABLE `catalog_url_rewrite_product_category` ADD CONSTRAINT  PRIMARY KEY (`url_rewrite_id`), DEFAULT CHARSET='utf8'

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-06-30 12:29
Hi @o7-sol ,
Thank you for reporting and collaboration. Verified the issue by upgrading from 2.3.2 to 2.4.4 but could not able to reproduce the issue.
Steps performed:
Installed Magento 2.3.2 project-community-edition with data in catalog_url_rewrite_product_category table.
Upgraded to Magento 2.4.4 Project-community-edition using: [Ref guide](https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/implementation/perform-upgrade.html)
Upgraded PHP version to 8.1 as Magento 2.4.4 is supported with 8.1 [system requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html)
No issue: Setup upgrade is successful.
Kindly elaborate the steps to reproduce / missing configuration details if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-07-15 10:17
Hi @o7-sol ,
We are closing this issue as there has been no latest on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-07-15 10:17 UTC
Labels: Issue: needs update

**Comment by lbajsarowicz** [comment] 2023-01-10 17:08
For the record -- I encountered exactly the same issue. For some reason Magento is trying to create PRIMARY KEY with invalid syntax. Will provide further feedback when I find the solution.

**Comment by hewgim** [comment] 2023-04-25 16:36
Hi @lbajsarowicz did you ever get to the bottom of this. Do you use Percona by any chance ? Our percona database is 8.0.32-24 and we get this error when we run

ALTER TABLE catalog_url_rewrite_product_category ADD CONSTRAINT PRIMARY KEY (url_rewrite_id) directly in mysql

Regards Mark

**Comment by Stas-AbsoluteDesign** [comment] 2023-08-22 11:40
@hewgim bless you mate. that saved my day. Using Percona 8 and this happened out of nowhere. Fixed by executing MySQL optimize on the table and then re-running the alter command.

**Comment by adamzero1** [comment] 2025-04-11 14:19
@hewgim legend! save me loads of time thank you!
