### ISSUE TITLE
Random state saved for customers where no state is required.

### ISSUE THREAD

**Issue by dakira** [magento/magento2#12659] opened 2017-12-12 23:52 UTC
For countries where the state is optional, it is hidden by default in checkout, which is good. Unfortunately a seemingly random state gets added to the customer contact data (and thus to the invoice).

### Preconditions
1. Magento 2.1.10
2. PHP 7.0.22

### Steps to reproduce
1. Create a new order and select Germany as the country.
2. No state field will be shown. Fill in the required fields and complete the order.

### Expected result
1. No state should be saved in the orders customer address

### Actual result
1. The state of *"Niedersachsen"* will show up in the customer data.

**Comment by magento-engcom-team** [comment] 2017-12-13 07:39
@dakira Thanks for your report. We tried and wasn't able to reproduce it on the clean instance of Magento, we tried making order from the storefront and dashboard, both worked just fine. We made a [video](https://streamable.com/k9j0o) of the steps we used, can you please watch it and tell us if we missed anything.  Thank you. https://streamable.com/k9j0o

**Comment by dakira** [comment] 2017-12-13 12:01
Thanks for taking the time to make a screencast. The problem only appears, when disabling the state field for countries where it's optional (see screenshot). I was pretty sure this was set by default, sorry for the confusion.

![bildschirmfoto von 2017-12-13 12-59-08](https://user-images.githubusercontent.com/576555/33937945-c4376372-e005-11e7-889c-e2b171b46f72.png)

**Comment by magento-engcom-team** [comment] 2017-12-13 14:34
@dakira Thank you for clarifying. We still can't reproduce the issues based on the steps you provided, can you give us more steps on what you do after you complete the order, please. Screenshots would be helpful too.

**Comment by dakira** [comment] 2017-12-14 14:19
@magento-engcom-team I'll try this on a freshly setup blank store and get back to you asap.

**Comment by dakira** [comment] 2017-12-15 19:44
@magento-engcom-team: So I was able to reproduce this on a fresh install, but only after I added the [magesetup2](https://github.com/firegento/firegento-magesetup2) module. I reported the bug over there (https://github.com/firegento/firegento-magesetup2/issues/100). I'm quite puzzled what in magesetup would lead to this problem so if it's okay, I'd like to leave this issue open, while we investigate "on the other side". Any help would of course be appreciated. magesetup2 is (and has to be) installed in pretty much every German M2 shop.

**Comment by magento-engcom-team** [comment] 2017-12-19 09:11
@dakira Unfortunately, we will have to close this issue. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only. Thank you

**Closed as completed** 2017-12-19 09:13 UTC
Labels: Progress: needs update, Issue: Clear Description, Issue: Format is valid

**Comment by sebastianrothbucher** [comment] 2019-07-22 21:08
For whatever it's worth, there is a solution simply by working the store settings. Maybe it helps some people out. I've written it up here: https://github.com/firegento/firegento-magesetup2/issues/100#issuecomment-513955291
