### ISSUE TITLE
Show Method if Not Applicable for Free Shipping doesn't work.

### ISSUE THREAD

**Issue by vaibhavahalpara** [magento/magento2#17977] opened 2018-09-08 10:01 UTC
### Preconditions

1. Magento 2.2.5 with sample data

### Steps to reproduce

1. STORES > Settings > Configuration > Sales > Shipping Methods > Free Shipping > Enabled > select Yes > > Minimum Order Amount > Enter 50 > Show Method if Not Applicable > Select Yes > Save Config

### Expected result

1. It should display error message defined in Admin Free Shipping > Displayed Error Message

### Actual result

1. Free shipping method is not showing

**Comment by magento-engcom-team** [comment] 2018-09-08 10:01
Hi @vaibhavahalpara. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@vaibhavahalpara do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-10-03 15:45
Hi @vaibhavahalpara. Thank you for your report. 
The issue has been fixed in magento/magento2#17982 by @vaibhavahalpara in 2.2-develop branch
Related commit(s):
 - [3d13f783c9b1e8b9d48bb0b23819598c3af65d17](https://github.com/magento/magento2/commit/3d13f783c9b1e8b9d48bb0b23819598c3af65d17)
 - [7107b8da49c06e783b7629ed3b88757bd97f53e1](https://github.com/magento/magento2/commit/7107b8da49c06e783b7629ed3b88757bd97f53e1)
 - [49f6549c682a7fb807faee247ad8f805a82d0f12](https://github.com/magento/magento2/commit/49f6549c682a7fb807faee247ad8f805a82d0f12)

The fix will be available with the upcoming 2.2.8 release.

**Closed as completed by magento-engcom-team** 2018-10-03 15:45 UTC
Labels: Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Progress: PR Created

**Comment by sidolov** [comment] 2018-10-16 14:45
Hi @vaibhavahalpara. Thank you for your report. 
The issue has been fixed in magento/magento2#18507 by @vaibhavahalpara in 2.3-develop branch
Related commit(s):
 - [9b7d4ac8c03eade9c6e94262b2f868cdf3f36aca](https://github.com/magento/magento2/commit/9b7d4ac8c03eade9c6e94262b2f868cdf3f36aca)
 - [67e1b01f6d8c90df57a70a3e9d56220234af27c2](https://github.com/magento/magento2/commit/67e1b01f6d8c90df57a70a3e9d56220234af27c2)
 - [4938bbc5e51fc67cff8098719e7301d0cb4255d5](https://github.com/magento/magento2/commit/4938bbc5e51fc67cff8098719e7301d0cb4255d5)

The fix will be available with the upcoming 2.3.1 release.
