### ISSUE TITLE
Admin user can't login as customer if a GWS scope not including the default store is set on their role

### ISSUE THREAD

**Issue by TheBadong** [magento/magento2#36434] opened 2022-11-08 08:19 UTC
### Preconditions and environment

- Adobe Commerce : 2.4.4
- Commerce only, is this the right place to report commerce bugs?
- Working on 2.4.3

### Steps to reproduce

1. Have a magento commerce 2.4.4 setup with the module admin-gws enabled
2. Create a secondary website, store and store view (all linked to each other)
3. Create a user role with only the second website scope, not the default one
4. Create an admin user and assign them this role
5. Log in to this admin user account
6. Find some frontend customer belonging to any scope (even the admin user one) and add them to the login_as_customer_assistance_allowed table
7. Try to login as this customer with the admin user 

### Expected result

Admin user can log in as customers belonging to their scope

### Actual result

Error pops up "an has occured during application run"

![image](https://user-images.githubusercontent.com/32772726/200509144-695ac5fb-771b-4d69-9471-86056015fadc.png)

### Additional information

Tested on a 2.4.3, works as expected.
While debugging, I found that the error occurs when trying to get the default store view in the LAC feature, 
vendor/magento/module-login-as-customer-admin-ui/Controller/Adminhtml/Login/Login.php->getLoginProceedRedirectUrl().
The admin-gws module adds a plugin on the store collection (vendor/magento/module-admin-gws/Plugin/CollectionFilter.php) that adds a filter to the stores collection, that prevents returning stores that do not belong in the current admin user scope. Which means that sometimes, storeManager->getDefaultStoreView() can return NULL, a behavior thats is not taken into account by the LAC module. 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by thomas-kl1** [comment] 2022-11-08 08:31
Hi, it seems related to this modification: https://github.com/magento/magento2/commit/c16c12bba2a19a4d85d0bdef7b589a80f1a2bff3

Indeed GWS has plugins over the getDefaultStore method and checks if the current admin user is allowed to load it. If the admin user has only permission for a specific website, then it fails and returns null.

**Comment by thomas-kl1** [comment] 2022-11-11 09:55
This could be fixed like it has been done for the page builder: https://github.com/magento/magento2-page-builder/commit/1e2bcadef49fb6ff5cbc198265e84d26bea74b74

**Comment by thomas-kl1** [comment] 2022-11-11 09:55
@magento I work on this

**Comment by thomas-kl1** [comment] 2022-11-11 09:56
@magento I am working on this

**Comment by engcom-November** [comment] 2022-11-15 05:09
Hi @TheBadong ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop enterprise edition but observed different behavior with below steps performed:
1. Stores - Configuration - Customers - Enabled login as customer
2. Stores - Configuration - Customer configuration - Share Customer Accounts - Set to Global
3. Created a customer from front end main website with "Allow remote shopping assistance" selected. (For every new customer account created, new record is generated in login_as_customer_assistance_allowed table)
4. Setup 2nd store as per Magento [devdocs](https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/multi-sites/ms-admin.html?lang=en)
5. Created admin user role with Role scope set to 2nd store
6. Created new admin user and assigned new user role created.
7. Logout and Login to Admin with new user
8. Navigate to Customers - All Customers
**No customers are displayed to login as customer**
**Customers created in Main website are not displayed in Admin All Customers page for the 2nd admin user.**
9. Created a Customer from 2nd store front end website
10. Admin - Customers - All Customers page - Edit Customer - Login as Customer
**No issue: Login as Customer is working fine from admin using 2nd store customer**
![image](https://user-images.githubusercontent.com/60198231/201831351-aa81869e-3d87-4ea9-86c7-c954f9a661fc.png)

![image](https://user-images.githubusercontent.com/60198231/201831176-f3369edc-6195-40c5-8de7-42cbd0a9a571.png)

Main Admin user account:
![image](https://user-images.githubusercontent.com/60198231/201831434-dc578e07-6547-4a98-8497-456f4e66d204.png)
Kindly check the behavior on Magento 2.4-develop enterprise edition and et us know if we are missing on anything.
Thank you.

**Comment by engcom-November** [comment] 2022-11-29 13:38
Hi @TheBadong ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-11-29 13:38 UTC
Labels: Issue: needs update

**Comment by thomas-kl1** [comment] 2023-01-24 20:28
Please @engcom-November give the link of the proper fix / commit reference. Don't close issues/MRs without words

**Comment by thomas-kl1** [comment] 2023-02-16 10:17
@engcom-November please?

**Comment by jordanvector** [comment] 2023-02-16 16:17
@engcom-November why is this closed without a solution.  This is still an issue on 2.4.5-p1

**Comment by engcom-Hotel** [comment] 2023-02-17 10:57
Hello @thomas-kl1 @jordanvector,

According to the @engcom-November's comments https://github.com/magento/magento2/issues/36434#issuecomment-1314783281, we have tried to reproduce the issue but the issue is not reproducible for us. Hence we have marked this issue as `Needs update` and waited for 14 days for a reply. 

And as per the process, we have closed this issue because we haven't gotten any reply in 14 days with this https://github.com/magento/magento2/issues/36434#issuecomment-1330665912. 

We request you to please go through with this https://github.com/magento/magento2/issues/36434#issuecomment-1314783281 and let us know if we have missed anything.

Thanks

**Comment by jordanvector** [comment] 2023-02-18 14:14
@engcom-Hotel What is missing from the test case, is the

Created admin user role with Role scope set to 2nd store - This user needs to have access ONLY to the 2nd store and not the default store.  This issue appears when the admin user does not have access to the default store.

Regardless, this issue was confirmed by Adobe support and solution provided, which fixes the issue for us.
[ACSD-45399_2.4.4.patch](https://github.com/magento/magento2/files/10774466/ACSD-45399_2.4.4.patch)

**Comment by thomas-kl1** [comment] 2023-02-18 20:56
@jordanvector the fix provided by Adobe support is so much overkill for what is needed to be fixed. Di you try with the changes from https://github.com/magento/magento2/pull/36460/files ?

BTW @engcom-Hotel , the method ` $this->storeManager->getDefaultStoreView();` may return null by its definition, so https://github.com/magento/magento2/pull/36460 is still needed

**Comment by jordanvector** [comment] 2023-02-19 00:20
> @jordanvector the fix provided by Adobe support is so much overkill for what is needed to be fixed. Di you try with the changes from https://github.com/magento/magento2/pull/36460/files ?
> 
> 
> 
> BTW @engcom-Hotel , the method ` $this->storeManager->getDefaultStoreView();` may return null by its definition, so https://github.com/magento/magento2/pull/36460 is still needed

I did try your PR before this patch, it did not work for me. Using this patch on 2.4.5-p1 did solve it.

**Comment by engcom-November** [comment] 2023-02-21 02:45
Hi @thomas-kl1 ,
I re-verified the issue again on latest Magento 2.4-develop instance with enterprise edition but the issue is still not reproducible with below steps performed:
**Steps performed:**
1. Enabled Login as customer from admin - Stores - Configuration - Customers - Login as Customer
2. Created 2nd website, store and store view as per Magento [devdocs](https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/multi-sites/ms-admin.html?lang=en)
3. Created Customers from front end both the websites (Main website and 2nd website)
4. Created Admin user role - assigned to only 2nd store scope
5. Created new Admin user with only new user role assigned to this admin user
6. Login to admin using new admin user
7. Customers - All Customers - Only customers created on 2nd store are displayed to the user
8. Open/edit the customer for which login as customer is enabled already - Click on Login as Customer
No issue: User is logged as customer
9. Open other customer for which login as customer is not enabled. - Enable login as customer from account information page and save
10. Click on Login as Customer - No issue. User is logged as customer
![image](https://user-images.githubusercontent.com/60198231/220234171-a3eb2cde-0cf4-4606-b6e4-9855de10fa6d.png)
![image](https://user-images.githubusercontent.com/60198231/220234211-7a883623-43ec-49b5-88ba-dc2e700ce469.png)
![image](https://user-images.githubusercontent.com/60198231/220234251-976ee40a-654c-4de5-b829-64e8cf60d044.png)
Kindly recheck the issue on latest Magento 2.4-develop instance as it is having latest code base and provide missing steps if any if the issue is still reproducible. Unable to find the commit link having fix for this issue. We are checking on it and get back to you.
Thank you.
