### ISSUE TITLE
timestamp() of \Magento\Framework\Stdlib\DateTime\DateTime is not localized

### ISSUE THREAD

**Issue by bh-ref** [magento/magento2#5383] opened 2016-06-30 14:47 UTC
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Call method timestamp() (without parameter) of \Magento\Framework\Stdlib\DateTime\DateTime which says it will give back a localized timestamp.
## Expected result
1. A localized timestamp.
## Actual result
1. A GMT timestamp.

The problem is the line in https://github.com/magento/magento2/blob/2.1/lib/internal/Magento/Framework/Stdlib/DateTime/Timezone.php#L176. 

If you change it to something like this, it works:

``` php
return (new \DateTime(date('Y-m-d H:i', $date), new \DateTimeZone($timezone)));
```

**Comment by demidov-i-a** [comment] 2016-08-12 08:05
It seems the problem at https://github.com/magento/magento2/blob/2.1/lib/internal/Magento/Framework/Stdlib/DateTime/DateTime.php#L141

Must be 

$timestamp = $date->getTimestamp() + $date->getOffset();

instead 

$timestamp = $date->getTimestamp();

Magento 1 code
$timestamp = $date->get(Zend_Date::TIMESTAMP) + $date->get(Zend_Date::TIMEZONE_SECS);

**Comment by sidealice** [comment] 2016-12-08 10:01
Should this added to Unit Test with a test case?

**Comment by magento-engcom-team** [comment] 2017-11-27 12:19
@bh-ref, thank you for your report.
The issue is already fixed in develop branch, 2.2.1

**Comment by magento-engcom-team** [comment] 2018-07-29 16:01
This issue was reopened without clear comment. Please provide reasoning and reopen again, if needed.

**Closed as completed by magento-engcom-team** 2018-07-29 16:01 UTC
Labels: bug report, Issue: Confirmed, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid

**Comment by arjundhi** [comment] 2019-03-31 07:51
> It seems the problem at https://github.com/magento/magento2/blob/2.1/lib/internal/Magento/Framework/Stdlib/DateTime/DateTime.php#L141
> 
> Must be
> 
> $timestamp = $date->getTimestamp() + $date->getOffset();
> 
> instead
> 
> $timestamp = $date->getTimestamp();
> 
> Magento 1 code
> $timestamp = $date->get(Zend_Date::TIMESTAMP) + $date->get(Zend_Date::TIMEZONE_SECS);

Hi,
After doing this fix in DateTime.php ...we are getting correct date value but now in admin grid date value are showing incorrect -6 hours from the created_at date. Any idea on this?
