### ISSUE TITLE
During adding product to Cart page page is reloading  instead adding product to cart by ajax.

### ISSUE THREAD

**Issue by Usik2203** [magento/magento2#25900] opened 2019-12-04 13:57 UTC
Preconditions (*)

When I created Simple product with custom option which have Option Type:  
Date, 
Date & Time , 
Time. 
 I can't add this product to Cart without page refresh. 

When I created Simple product with custom option which have other Option Type 
Field, 
Area etc.
 I can add product to Cart without refreshing page by ajax.

 Magento version:  dev-2.3-develop

Steps to reproduce (*)

1. Create Simple product with custom option which have Option Type:  Date, Date & Time , Time.
2. Go to Product page on frontend
3. Add product to Cart

### Expected result (*)

1. Product should be added without page refresh
![screenshot](https://user-images.githubusercontent.com/13517181/70148007-0dced200-16ae-11ea-852f-000ebb406f5b.png)
![screenshot_1](https://user-images.githubusercontent.com/13517181/70148045-1c1cee00-16ae-11ea-8b54-fb1eb633fa07.png)

### Actual result (*)

1. Page refresh

**Comment by engcom-Echo** [comment] 2019-12-04 14:24
Hello @Usik2203 

Thank you for your report and collaboration!
We are not able to reproduce this issue on the 2.3-develop branch by provided steps.

**Testing scenario:**

**Steps to reproduce:**

1. Create Simple product with custom option which have Option Type: Date, Date & Time, Time.
2. Go to Product page on frontend
3. Add product to Cart
4. In opened window select all options
![Screenshot from 2019-12-04 16-14-39](https://user-images.githubusercontent.com/51681435/70149880-ab77d080-16b1-11ea-9759-fd9ebef48fea.png)
5. Click Add to Cart

**Result**
Product is added without page refresh. Behavior is the same as with added other custom options.
![Screenshot from 2019-12-04 16-14-58](https://user-images.githubusercontent.com/51681435/70149948-d19d7080-16b1-11ea-9301-4ef3765f507f.png)

So I have to close this issue.
Thank you!

**Closed as completed by engcom-Echo** 2019-12-04 14:24 UTC
Labels: Issue: Format is valid
