### ISSUE TITLE
sales/order/history/ page shows all orders and is not limited to the max page number which results in long loading times

### ISSUE THREAD

**Issue by mikemoooo** [magento/magento2#32201] opened 2021-02-17 10:49 UTC
### Preconditions (*)

1. 2.4.2

### Steps to reproduce (*)

1. Open a customer account with more than 100 orders.
2. Open the /sales/order/history/ page

### Expected result (*)

1. The page should show the first 10 orders (default : 10 orders per page)

### Actual result (*)

1. The page shows all orders in the account, ignoring the max. amount of results per page.
2. Pagination at the bottom is show, including page numbers, but each page shows all orders
3. For large customers this results in a long loading time when the amount of orders is more than 1000

![Screenshot 2021-02-17 at 11 45 54](https://user-images.githubusercontent.com/30129463/108193595-ec70cf00-7115-11eb-9acc-2d89cb8c37bd.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment] 2021-02-17 11:56
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment] 2021-02-17 12:16
Hi @mikemoooo . Thank you for your report!
Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop and 2.4.2. Everything works as expected.

**Manual testing scenario:**

1. Open a customer account with more than 10 orders;
2. Open the /sales/order/history/ page

**Actual Result:** :heavy_check_mark: The page shows the first 10 orders (default: 10 orders per page)
![Screenshot from 2021-02-17 14-09-10](https://user-images.githubusercontent.com/51679138/108202932-80e52c80-712a-11eb-8d81-c20630f4ffdc.png)

So, we have to close it. 
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch.
 Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2021-02-17 12:16 UTC
Labels: Issue: ready for confirmation, not-confirmed
