### ISSUE TITLE
Not able to change / alter special_to_date product attribute causing pricing issues

### ISSUE THREAD

**Issue by nwiegers01** [magento/magento2#35328] opened 2022-04-19 12:00 UTC
Lately I came to the discovery that my product prices were not being updated while doing a price update.
The reason for this is that the _special_to_date_ attribute was being set for those products. My project is using the _catalog/staging_ module, which removes/filters out the _special_to_date_ attribute. 

Because of this, I am also not able to alter/change the value of this attribute. The only way to do this at the moment is to remove it from the DB or alter is via an CSV/API update.

### Preconditions (*)
1. Magento Enterprise: 2.4.3-P2

### Steps to reproduce (*)
1. Your project needs to have the Catalog/Staging module.
2. Define the _special_to_date_ for a product via an CSV/API update or directly in the DB.
3. Change the price.

### Expected result (*)
1. The price changes reflect on the frontend.
2. A special-price is being shown.
3. The attribute is changeable.

### Actual result (*)
1. The attribute cannot be changed.
2. The price change is not reflecting on the frontend.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-07-12 12:50
Hi @nwiegers01 ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch with enterprise edition modules installed but could not reproduce the issue.
Steps performed:
1. Created a product with Special Price
2. Imported same Product CSV with special_price_from_date and special_price_to_date values
3. Reindex and cache flush
4. Changed base price and special price  - Save
5. Reindex and flush cache
6. Front-end - View Product - Price changed as expected - No issue.
7. Change base price and special price in CSV and import
8. Reindex and cache flush
9. Front-end - View Product - Price changed as expected - No issue.
![image](https://user-images.githubusercontent.com/60198231/178493871-1109e860-f9c4-4ccf-8b62-2cab31e94ef3.png)

![image](https://user-images.githubusercontent.com/60198231/178493776-9903abb5-92dd-4183-8981-21320a4d67de.png)

Kindly recheck the issue on Magento 2.4-develop branch with enterprise edition and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-07-26 12:06
Hi @nwiegers01 ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-07-26 12:06 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
