### ISSUE TITLE
URL key for specified store already exists when saving category.

### ISSUE THREAD

**Issue by kingshukdeb** [magento/magento2#21730] opened 2019-03-13 09:12 UTC
### Preconditions (*)

1. Magento 2.1.12

### Steps to reproduce (*)

1. Create a category.
2. Create 2 products using API.
3. Add 1 301 redirect for 1 of those product's category url.
4. Assign those 2 products to the category using API.
5. Magento doesnt create product urls without saving the category. So save the category from admin panel.

### Expected result (*)

1. category saved successfully.

### Actual result (*)

1. URL key for specified store already exists.
2. There is already a 301 redirect for 1 product using the same url-key. Hence magento fails to save the whole category. New urls dont even generate for other products.

**Comment by magento-engcom-team** [comment] 2019-03-13 09:12
Hi @kingshukdeb. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kingshukdeb do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-03-13 09:16
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by orlangur** [comment] 2019-03-13 10:21
@kingshukdeb this is correct behavior for `2.1.x`. Also, bug reports are only accepted for `2.2.x` and `2.3.x` at the moment.

**Closed as completed by orlangur** 2019-03-13 10:21 UTC
Labels: Issue: Format is valid

**Comment by kingshukdeb** [comment] 2019-03-13 10:48
> @kingshukdeb this is correct behavior for `2.1.x`. Also, bug reports are only accepted for `2.2.x` and `2.3.x` at the moment.

dont you think it should skip that redirect and save the category and generate urls for other products?...how would someone save a category if that has 100 301 redirects for products in a category? How this can be a correct behavior ?

**Comment by orlangur** [comment] 2019-03-13 12:37
@kingshukdeb this was improved in newer versions, try upgrading or play with a vanilla instance.

> if that has 100 301 redirects for products

Normally it does not occur, all or not at all rewrites are created for the sake of data integrity.
