### ISSUE TITLE
FedEx team blocking our shippings because of wrong imageType

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [magento/magento2#39186] opened 2024-09-19 10:05 UTC
### Preconditions and environment

- Magento version 2.4.7-p2
- FedEx shipping

### Steps to reproduce

1. Navigate through backend
2. Generate FedEx shipping label

### Expected result

Compliant shipping label for FedEx services.

### Actual result

Blocked shipping by FedEx because of non compliant label.

### Additional information

FedEx team told me I had to change imageType from PNG to PDF in vendor/magento/module-fedex/Model/Carrier.phpvendor/magento/module-fedex/Model/Carrier.php (around line 1240).

'labelSpecification' => [
    'labelFormatType' => 'COMMON2D',
    'imageType' => 'PDF',
    'labelStockType' => 'PAPER_85X11_TOP_HALF_LABEL',
],

Should this option not be administrable in back office?

This is already the third change asked by FedEx devs I have to make in this file (issues [#39159](https://github.com/magento/magento2/issues/39159) & [#39162](https://github.com/magento/magento2/issues/39162))

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-10-03 05:21
Hi @ShapesGraphicStudio,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.we are able to create the shipping label.

[ShippingLabel(000000003) (1).pdf](https://github.com/user-attachments/files/17239554/ShippingLabel.000000003.1.pdf)




Could you please elaborate the steps to reproduce to proceed further.

Thanks.

**Comment by ShapesGraphicStudio** [comment] 2024-10-10 07:16
Hello,
This is not a bug blocking the generation of the label itself.
The label is created but it has the wrong imageType regarding to what FedEx teams are telling us to validate our shippings.

FedEx team (commercial and dev) told me I had to change imageType from PNG to PDF for our shippings not to be blocked.

**Comment by engcom-Bravo** [comment] 2024-10-14 06:25
Hi @ShapesGraphicStudio,

As per this comment https://github.com/magento/magento2/issues/39186#issuecomment-2404251209 we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-10-14 06:25 UTC
Labels: Issue: needs update, Reported on 2.4.7-p2

**Comment by ShapesGraphicStudio** [comment] 2024-10-14 06:48
Hello @engcom-Bravo ,
I don't understand this issue closing as I need to change the module to make it work right following converstaions with FedEx devs.
The FedEX module as written in Magento Core can not retrieve the prices we dealed with them.
So I think it does not fully work.

**Comment by ShapesGraphicStudio** [comment] 2025-02-19 10:55
We are still having the same issue with 2.4.7-p4.

In our case image type should be:
`'imageType' => 'PDF',`
and not
`'imageType' => 'PNG',`

So this option should be added in admin.
