### ISSUE TITLE
QuoteGraphQl AvailableShippingMethod.carrier_title should allow null

### ISSUE THREAD

**Issue by Tomasz-Silpion** [magento/magento2#36700] opened 2023-01-05 02:35 UTC
### Preconditions and environment

2.4.5, 2.4.5-p1,2.4 develop and earlier instances since Magento_QuoteGraphQl was initiated in version 2.3

When the delivery method title is empty `Cannot return null for non-nullable field \"AvailableShippingMethod.carrier_title\"` exception is thrown in graphQL checkout.

### Steps to reproduce

1. Go to admin panel, remove title from active delivery method
2. Send setShippingAddressesOnCart graphQL mutation with selected or available_shipping_methods 

### Expected result

Shipping methods would be returned in response as both SelectedShippingMethod and AvailableShippingMethod.carrier_title should allow empty string (null) as it's allowed in Magento 2 configuration and native checkout.

### Actual result

`"Cannot return null for non-nullable field \"AvailableShippingMethod.carrier_title\` error is thrown. Order cannot be placed.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-01-05 06:20
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-01-05 12:02
Hi @Tomasz-Silpion,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

1.Go to admin panel, remove title from active delivery method
2.Send setShippingAddressesOnCart graphQL mutation with selected or available_shipping_methods.


<img width="1171" alt="Screenshot 2023-01-05 at 3 36 01 PM" src="https://user-images.githubusercontent.com/51680745/210775486-a8268fc4-24d4-4c04-a9cd-0f4ca73e27fe.png">


<img width="1242" alt="Screenshot 2023-01-05 at 3 39 44 PM" src="https://user-images.githubusercontent.com/51680745/210775537-f43b8f83-ff7e-4a1a-9955-2b574bdc120b.png">


<img width="1380" alt="Screenshot 2023-01-05 at 3 28 20 PM" src="https://user-images.githubusercontent.com/51680745/210775600-4c316315-ea29-48e5-81c4-871fa6445f21.png">



<img width="1435" alt="Screenshot 2023-01-05 at 3 28 08 PM" src="https://user-images.githubusercontent.com/51680745/210775660-efbe76a7-815b-4cbf-8db4-5ee38ab56ac2.png">


<img width="1415" alt="Screenshot 2023-01-05 at 3 31 08 PM" src="https://user-images.githubusercontent.com/51680745/210775699-b52b18d4-4dce-48d1-afd9-7a06e14064b1.png">


We are able to place the order without carrier_title.

Kindly let us know if we missed anything.

Thanks.

**Comment by Tomasz-Silpion** [comment] 2023-01-06 01:54
Hmm, I've tried it on another store (2.4.5) and managed to reproduce the issue so @magento give me 2.4-develop instance

**Comment by Tomasz-Silpion** [comment] 2023-01-06 02:15
Yhmm, @engcom-Bravo can you check again? I've managed to reproduce it there:

![image](https://user-images.githubusercontent.com/5328659/210915569-43cd838a-d9bc-4a8a-af41-995db4d2894c.png)

![image](https://user-images.githubusercontent.com/5328659/210915539-cf615fe8-b534-4fc4-b708-269350ea98ab.png)

![image](https://user-images.githubusercontent.com/5328659/210915629-e9c57f15-ac64-4933-a4ae-4a1356cd4eb6.png)

![image](https://user-images.githubusercontent.com/5328659/210915602-1df05a1d-54c0-4fe1-9399-52773a77f811.png)

But dunno where does our approach differs 🤷

**Comment by engcom-Bravo** [comment] 2023-01-06 08:36
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-01-06 13:34
Hi @Tomasz-Silpion,

Thanks for your update.

we have followed same steps as you mentioned.we are not able to reproduce the issue.Kindly refer the screenshots.


<img width="1292" alt="Screenshot 2023-01-06 at 6 00 40 PM" src="https://user-images.githubusercontent.com/51680745/211013170-e4abbb42-f0ed-47f5-a556-393d1ea8b6e9.png">



<img width="1357" alt="Screenshot 2023-01-06 at 2 34 06 PM" src="https://user-images.githubusercontent.com/51680745/211013211-93261c68-847f-40b6-8c59-f2d7c7b3adfa.png">




<img width="1310" alt="Screenshot 2023-01-06 at 7 00 15 PM" src="https://user-images.githubusercontent.com/51680745/211022110-d2b456a8-8064-4799-8578-b3cb2676d271.png">



We are getting null values for carrier_title and we are able to place the order successfully.


Kindly check after reindex and flush cache and please let us know if we missed anything.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-01-18 06:06
Hi @Tomasz-Silpion,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-01-18 06:06 UTC
Labels: Issue: needs update, Reported on 2.4.5

**Comment by Januszpl** [comment] 2024-05-03 03:08
@engcom-Bravo you are getting null, but then schema is wrong. Not sure why it doesn't throw error for you but can you either fix returned type ('' instead of null) or fix schema?

See: `!`  in `carrier_title: String!`
``` 
type AvailableShippingMethod @doc(description: "Contains details about the possible shipping methods and carriers.") {
    carrier_code: String! @doc(description: "A string that identifies a commercial carrier or an offline shipping method.")
    carrier_title: String! @doc(description: "The label for the carrier code.")
