### ISSUE TITLE
Check HTTP_REFERER in NewRma admin lead to a deprecaded error

### ISSUE THREAD

**Issue by vahir2016** [magento/magento2#37310] opened 2023-03-29 11:06 UTC
### Preconditions and environment

- Magento version 2.4.5 EE
- Go to /magentoadmin/admin/rma/new/order_id/1/

Here is the issue : 
This line :
`            $referer = $this->getRequest()->getServer('HTTP_REFERER');
`
$referer returns NULL

but strpos() doesn't allow NULL (except string) leads to deprecated error.

Deprecated errors crash my php.

Is it normal ? Should I change something in my configuration. or should I patch the vendor to force $referer to be a string ?

`function strpos(string $haystack, string $needle, int $offset = 0): int|false {}`

Full function in src/vendor/magento/module-rma/Block/Adminhtml/Rma/NewRma.php
` protected function _construct()
    {
        $this->_objectId = 'id';
        $this->_controller = 'adminhtml_rma';
        $this->_blockGroup = 'Magento_Rma';

        parent::_construct();

        $this->buttonList->update('reset', 'label', __('Cancel'));
        $this->buttonList->update('reset', 'class', 'cancel');

        $link = $this->getUrl('adminhtml/*/');
        $order = $this->_coreRegistry->registry('current_order');

        if ($order && $order->getId()) {
            $orderId = $order->getId();
            $referer = $this->getRequest()->getServer('HTTP_REFERER');

            if (strpos($referer, 'customer') !== false) {
                $link = $this->getUrl(
                    'customer/index/edit/',
                    ['id' => $order->getCustomerId(), 'active_tab' => 'orders']
                );
            }
        } else {
            return;
        }

        if ($this->_rmaData->canCreateRma($orderId, true)) {
            $this->buttonList->update('reset', 'onclick', "setLocation('" . $link . "')");
            $this->buttonList->update('save', 'label', __('Submit Returns'));
        } else {
            $this->buttonList->update('reset', 'onclick', "setLocation('" . $link . "')");
            $this->buttonList->remove('save');
        }
        $this->buttonList->remove('back');
    }`

### Steps to reproduce

1 . Connect to backoffice
2 . Go to the link

### Expected result

No deprecated error when REFERER is null

### Actual result

REFERER is null, strpos returns deprecated error

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-03-30 13:44
Hi @vahir2016,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance with EE edition and the issue is not reproducible.Kindly refer the attached video.


**Steps to reproduce**


- 1 . Connect to backoffice
- 2 . Go to the link



https://user-images.githubusercontent.com/51680745/228838881-d1b2877b-f14a-4277-9d03-cddb720773b4.mov



<img width="1493" alt="Screenshot 2023-03-30 at 3 43 11 PM" src="https://user-images.githubusercontent.com/51680745/228838933-c19795d3-873f-428f-af8a-d60ef7d6ee55.png">



We are not getting any deprecated error and able to proceed with returns.


Kindly recheck the behavior on Magento 2.4-develop instance with EE edition and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-04-10 06:07
Hi @vahir2016,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-04-10 06:07 UTC
Labels: Issue: needs update, Reported on 2.4.5

**Comment by hostep** [comment] 2023-04-11 18:16
@engcom-Bravo: do you understand how referers work in http calls from your browser? Because it sounds like you don't. Here is [some info about it](https://en.wikipedia.org/wiki/HTTP_referer). Notice that it says: "... **optional** HTTP header field ..."

So here is something to try:
- make sure you are running a Adobe Commerce shop version 2.4.5 with PHP 8.1
- login to the backoffice
- go the the url specified in the opening post in the same browser tab by clicking on the various links and buttons to get there, like you did earlier in your screen recording (this should work because there will be a referer)
- now copy the url and paste it in a **new** browser tab and hit enter, now the error should occur (because there won't be a referer this time)

(I haven't tested this myself, but I can see how this error can be triggered just by reading the code and the bug report. I also haven't check if this was fixed in Magento 2.4.6 or 2.4-develop, because the code of Adobe Commerce isn't open to the public.)
