### ISSUE TITLE
Customer Import Removing Empty Columns

### ISSUE THREAD

**Issue by paulpartington-cti** [magento/magento2#9469] opened 2017-05-02 10:37 UTC
When importing customers and address, empty values from the source CSV file do not have an array key created. For example if you specify a 'prefix' on the first customer and then no other prefixes on the others, the import will not run as it's expecting a prefix column for all customer rows. In a similar fashion, if you don't define a prefix for the first row but do for the others, then none of the rows will have a prefix after the import is completed.

The import process gets the columns to check against by taking the first row from the CSV file. If any subsequent rows do not contain the same columns, an 'Invalid data for insert' exception is thrown.

### Preconditions
1. Magento 2.1.6 CE (no sample data), PHP 7.0.18, MYSQL 5.6
2. No customer data
3. A CSV file with multiple customers and an empty value for one of the rows. In the below example, the 'prefix' has not been defined on the second row and is not a required attribute.

```
email,_website,_store,firstname,gender,group_id,lastname,middlename,prefix,_address_city,_address_company,_address_country_id,_address_fax,_address_firstname,_address_lastname,_address_middlename,_address_postcode,_address_prefix,_address_region,_address_street,_address_suffix,_address_telephone,_address_vat_id,_address_default_billing_,_address_default_shipping_
testcustomer1@test.com,base,admin,Test1 First Name,,1,Test1 Last Name,,Mrs,Test1 City,,GB,,Test1 First Name,Test2 Last Name,,Test1Postcode,,,Street Line 1,,1,,1,0
testcustomer2@test.com,base,admin,Test2 First Name,,1,Test2 Last Name,,,Test2 City,,GB,,Test2 First Name,Test2 Last Name,,Test2Postcode,,,Street Line 1,,1,,1,0
```

### Steps to reproduce
1. Login to the admin and go to System -> Import
2. Choose Customers and Addresses (single file)
3. Select 'Add/Update' as the Import Behaviour
4. Select the CSV file
5. Click 'Check Data'. The results should be valid.
6. Click Import

### Expected result
1. Two customers and their addresses should be created

### Actual result
1. An exception is thrown 'Invalid data for insert'

**Comment by jalogut** [comment] 2017-05-12 10:53
Same issue here. Not possible to import customers if a customer has an empty value for one column where one other customer has a value. 
It seems that there were already as issue for that [4291](https://github.com/magento/magento2/issues/4291)

**Comment by veloraven** [comment] 2017-06-29 08:18
@paulpartington-cti thank you for your report.
However I'm closing this issue as duplicate of  #4291.
Internal ticket for this issue - MAGETWO-58760 and it was fixed already.
The fix will be available in one of the nearest releases.

**Closed as completed by veloraven** 2017-06-29 08:18 UTC
Labels: bug report, Component: ImportExport
