### ISSUE TITLE
how do you test your installschema worked?

### ISSUE THREAD

**Issue by ghost** [magento/magento2#6373] opened 2016-08-29 01:04 UTC
I've written a basic install data class for a module on magento 2.1 and php version 5.6.25. Mysql version 5.6.14. apache 2.4.

``` php
<?php
/**
 * Created by PhpStorm.
 * User: bardiaafshin
 * Date: 8/28/16
 * Time: 11:22 AM
 */

namespace BardiaModule\ProductAttribute\Setup;

use Magento\Eav\Setup\EavSetup;
use Magento\Eav\Setup\EavSetupFactory;
use Magento\Framework\Setup\InstallDataInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\ModuleDataSetupInterface;

class InstallData implements InstallDataInterface
{
    private $eavSetupFactory;

    public function __construct(EavSetupFactory $eavSetupFactory)
    {
        $this->eavSetupFactory = $eavSetupFactory;
    }

    public function install(ModuleDataSetupInterface $setup, ModuleContextInterface $context)
    {
        $eavSetup = $this->eavSetupFactory->create(['setup' => $setup]);
        $eavSetup->addAttribute(
            \Magento\Catalog\Model\Product::ENTITY,
            'cart_message',
            [
                'type' => 'int',
                'backend' => '',
                'frontend' => '',
                'label' => 'Cart Message',
                'input' => '',
                'class' => '',
                'source' => '',
                'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
                'visible' => true,
                'required' => true,
                'user_defined' => false,
                'default' => '',
                'searchable' => false,
                'filterable' => false,
                'comparable' => false,
                'visible_on_front' => false,
                'used_in_product_listing' => true,
                'unique' => false,
                'apply_to' => ''
            ]
        );



    }
}
```

The questions is, how do you verify the attribute cart_message has been created? When I enable the module, and do setup:upgrade, I don't get any error messages, but when I search for the new column in the schema in mysql via this cool query

``` sql
mysql> SELECT DISTINCT TABLE_NAME      FROM INFORMATION_SCHEMA.COLUMNS     WHERE COLUMN_NAME IN ('cart_message')         AND TABLE_SCHEMA='magento2';
Empty set (0.03 sec)
```

I get 0 results. Which means the InstallData.php didn't run? Anybody shed some light on this? I didn't install this module via composer, just wrote it into the project as I'm getting familiarized with Magento, so doing setup:uninstall isn't an option without more work, just to test this installdata class.

**Comment by acharrex** [comment] 2016-08-29 06:33
Check if an attribute "cart_message" exists in the table "eav_attribute" (column "attribute_code").

**Comment by ghost** [comment] 2016-08-29 15:08
The field 'cart_message' doesn't exist in the eav_attribute, am I missing something in the code? Looking at the definition of ENTITY doesn't tell me much, what does 'apply_to'  field in the array signify? Is there some more detailed docs in this?

**Comment by veloraven** [comment] 2016-11-01 17:28
I'm closing this issue as the GitHub issue tracker is intended for technical issues only. 
Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you think it to be an issue than please create new GitHub report following the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. Please, also identify which version of Magento you are running.

**Closed as completed by veloraven** 2016-11-01 17:28 UTC
Labels: Component: Setup
