### ISSUE TITLE
Make email Subjects translatables [Improve]

### ISSUE THREAD

**Issue by srbarba** [magento/magento2#4116] opened 2016-04-12 11:43 UTC
Right now, the subject email isn't translatable from "language.csv".
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Translate subject of email template at language CSV
3. Add simple product.
4. Create Order and Send New Order Email [For Example]
## Expected result
1. Subject translated
## Actual result
1. Subject isn't translatable
## Actual result

I suggest the next change(this is an example for **order_new.html** template):

Original: 
`<!--@subject Your {{var store.getFrontendName()}} order confirmation @-->`

My Solution:
`<!--@subject {{trans "Your %store_name order confirmation" store_name=$store.getFrontendName()}} @-->`

**Comment by mazhalai** [comment] 2016-04-12 17:17
@srbarba this has already been reported, closing as duplicate of https://github.com/magento/magento2/issues/4072

**Closed as completed by mazhalai** 2016-04-12 17:17 UTC
