### ISSUE TITLE
Auth.net module sending OPTIONS request

### ISSUE THREAD

**Issue by nbennett25** [magento/magento2#26376] opened 2020-01-13 19:03 UTC
Using Magento 2.3.3 and the new Auth.net Payment method, configuration with a sandbox account throws an error in the OPTIONS API call. I've been in touch with Auth.net's support, and they have made it clear that the API does not even support OPTIONS requests, so it seems like this is likely a Magento issue.

### Preconditions (*)

1. Magento 2.3.3
2. Auth.net sandbox account configured
3. Credentials from Auth.net account added to admin configuration
4. Payment method enabled

### Steps to reproduce (*)

1. Add product to cart
2. Go to Checkout
3. Fill out Shipping Address
4. Click 'Next'
5. Select Credit Card (Authorize.net) from Payment Method
6. Enter test credit card field values
7. Click 'Place Order'

### Expected result (*)

1. Order goes through, user is sent to the success page

### Actual result (*)

1. OPTIONS request sent to https://apitest.authorize.net/xml/v1/request.api
2. Error received: "code":"E00001","text":"Error reading JToken from JsonReader. Path '', line 0, position 0."
3. POST request sent to https://apitest.authorize.net/xml/v1/request.api
4. Error received: "code":"E00007","text":"User authentication failed due to invalid authentication values."
5. Error displayed to user: User authentication failed due to invalid authentication values
6. User is not sent to success page

**Comment by nbennett25** [comment] 2020-01-13 19:52
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment] 2020-01-13 19:52
Hi @nbennett25. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment] 2020-01-13 19:53
Hi @nbennett25, here is your [Magento instance](https://i-26376-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26376-2-3-3.instances.magento-community.engineering/admin](https://i-26376-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by nbennett25** [comment] 2020-01-13 20:00
@magento confirmed same behavior on 2.3.3 instance.

**Comment by magento-engcom-team** [comment] 2020-01-15 09:41
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30447` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by nbennett25** [comment] 2020-01-23 16:00
Any updates here?

**Comment by nbennett25** [comment] 2020-01-27 14:08
@magento give me 2.3.2 instance

**Comment by magento-engcom-team** [comment] 2020-01-27 14:08
Hi @nbennett25. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by magento-engcom-team** [comment] 2020-01-27 14:09
Hi @nbennett25, here is your [Magento instance](https://i-26376-2-3-2.instances.magento-community.engineering).
Admin access: [https://i-26376-2-3-2.instances.magento-community.engineering/admin_953e](https://i-26376-2-3-2.instances.magento-community.engineering/admin_953e)
Login: `cd987667` Password: `2b49de3107db`
Instance will be terminated in up to 3 hours.

**Comment by nbennett25** [comment] 2020-01-27 14:22
Also confirmed on 2.3.2

Noting that I received a confirmation email from the Auth.net sandbox that the transaction was approved despite seeing the same behavior and error on the front end of the 2.3.2 instance.

**Comment by nbennett25** [comment] 2020-01-29 15:01
@magento @engcom-Charlie @magento-engcom-team - if this is not going to be worked on in the immediate future, can we at least get a patch file? 

There are now reports of the same issue affecting live/production Auth.net integrations

**Comment by Beowulf891** [comment] 2020-01-29 16:05
@magento-engcom-team @magento I must agree with @nbennett25. This issue is affecting live accounts and needs a resolution ASAP!

**Comment by dharmendra-wagento** [comment] 2020-02-02 04:34
#mm20in

**Comment by nbennett25** [comment] 2020-02-10 21:24
It looks like Magento 2.3.4 has officially deprecated _all_ core Auth.net payment methods, and requests that users install the Auth.net provided module (`composer require authorizenet/magento-module-authorizenet`), however this looks like it has [issues](https://github.com/magento/magento2/issues/26802) as well.

**Comment by sdzhepa** [comment] 2020-08-18 20:10
Hello @nbennett25 

Thank you for your report and collaboration!

Unfortunately, we are closing this Issue report because we are not able to process contribution to the `2.3.x` release line through this public repository. See details [Code Contributions: Accepted pull requests and ported code](https://devdocs.magento.com/contributor-guide/contributing.html#rules)

And starting from `2.4.0` release, code related to this payment was removed/deprecated from Magento code-base:
[Magento Commerce 2.4.0 Release Notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-commerce.html)
> With this release, the Authorize.Net, Braintree, eWay, CyberSource, and Worldpay payment method integrations have been removed from core code. Merchants should migrate to the official extensions that are available on the Magento Marketplace.

[Deprecation of Magento core payment integrations](https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445)

All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page

**Closed as completed by sdzhepa** 2020-08-18 20:10 UTC
Labels: Issue: Ready for Work, Component: Payment, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Reproduced on 2.4.x, Event: mm20in, Reported on 2.3.3
