### ISSUE TITLE
[php8.1 M2.4.5-p1 CE] ValueError: bcsub(): Argument #1 ($num1) is not well-formed in

### ISSUE THREAD

**Issue by jayantakr1** [magento/magento2#36883] opened 2023-02-17 20:26 UTC
### Preconditions and environment

[2023-02-17T20:16:33.436118+00:00] main.CRITICAL: ValueError: bcsub(): Argument #1 ($num1) is not well-formed in /var/www/html/vendor/magento/zendframework1/library/Zend/Locale/Math.php:259
Stack trace:
#0 /var/www/html/vendor/magento/zendframework1/library/Zend/Locale/Math.php(259): bcsub('2021-08-23 00:0...', '2021-08-23 00:0...', 0)
#1 /var/www/html/vendor/magento/zendframework1/library/Zend/Locale/Format.php(385): Zend_Locale_Math::Sub('2021-08-23 00:0...', '2021-08-23 00:0...', 0)
#2 /var/www/html/vendor/magento/zendframework1/library/Zend/Locale/Format.php(662): Zend_Locale_Format::toNumber('2021-08-23 00:0...', Array)
#3 /var/www/html/vendor/magento/zendframework1/library/Zend/Filter/NormalizedToLocalized.php(106): Zend_Locale_Format::toFloat('2021-08-23 00:0...', Array)
#4 /var/www/html/vendor/magento/framework/Data/Form/Filter/Date.php(69): Zend_Filter_NormalizedToLocalized->filter('2021-08-23 00:0...')
#5 /var/www/html/vendor/magento/module-customer/Model/Metadata/Form/AbstractData.php(197): Magento\Framework\Data\Form\Filter\Date->inputFilter('2021-08-23 00:0...')
#6 /var/www/html/vendor/magento/module-customer/Model/Metadata/Form/Date.php(20): Magento\Customer\Model\Metadata\Form\AbstractData->_applyInputFilter('2021-08-23 00:0...')
#7 /var/www/html/vendor/magento/module-customer/Model/Metadata/Form.php(244): Magento\Customer\Model\Metadata\Form\Date->extractValue(Object(Magento\Framework\App\Request\Http))
#8 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Customer\Model\Metadata\Form->extractData(Object(Magento\Framework\App\Request\Http), 'customer')
#9 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Model\Metadata\Form\Interceptor->___callParent('extractData', Array)
#10 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Model\Metadata\Form\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http), 'customer')
#11 /var/www/html/generated/code/Magento/Customer/Model/Metadata/Form/Interceptor.php(41): Magento\Customer\Model\Metadata\Form\Interceptor->___callPlugins('extractData', Array, Array)
#12 /var/www/html/vendor/magento/module-customer/Controller/Adminhtml/Index/Validate.php(42): Magento\Customer\Model\Metadata\Form\Interceptor->extractData(Object(Magento\Framework\App\Request\Http), 'customer')
#13 /var/www/html/vendor/magento/module-customer/Controller/Adminhtml/Index/Validate.php(88): Magento\Customer\Controller\Adminhtml\Index\Validate->_validateCustomer(Object(Magento\Framework\DataObject))
#14 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Customer\Controller\Adminhtml\Index\Validate->execute()
#15 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Adminhtml\Index\Validate\Interceptor->___callParent('execute', Array)
#16 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Adminhtml\Index\Validate\Interceptor->Magento\Framework\Interception\{closure}()
#17 /var/www/html/generated/code/Magento/Customer/Controller/Adminhtml/Index/Validate/Interceptor.php(23): Magento\Customer\Controller\Adminhtml\Index\Validate\Interceptor->___callPlugins('execute', Array, Array)
#18 /var/www/html/vendor/magento/framework/App/Action/Action.php(111): Magento\Customer\Controller\Adminhtml\Index\Validate\Interceptor->execute()
#19 /var/www/html/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#20 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Adminhtml\Index\Validate\Interceptor->___callParent('dispatch', Array)
#22 /var/www/html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\Customer\Controller\Adminhtml\Index\Validate\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#23 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Customer\Controller\Adminhtml\Index\Validate\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#24 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Adminhtml\Index\Validate\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#25 /var/www/html/generated/code/Magento/Customer/Controller/Adminhtml/Index/Validate/Interceptor.php(32): Magento\Customer\Controller\Adminhtml\Index\Validate\Interceptor->___callPlugins('dispatch', Array, Array)
#26 /var/www/html/vendor/magento/framework/App/FrontController.php(245): Magento\Customer\Controller\Adminhtml\Index\Validate\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#27 /var/www/html/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse(Object(Magento\Customer\Controller\Adminhtml\Index\Validate\Interceptor), Object(Magento\Framework\App\Request\Http))
#28 /var/www/html/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\Customer\Controller\Adminhtml\Index\Validate\Interceptor))
#29 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#30 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#31 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#32 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#33 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#34 /var/www/html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#35 /var/www/html/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))

### Steps to reproduce

1. After Magento 2 version upgrade from 2.3.7-p2 to 2.4.5-p1 we are getting this issue. 
2. When going to save customer that time i am getting issue 

### Expected result

It's should be success. 

### Actual result

customer not save 

### Triage and priority

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-03-03 16:57
Hi @jayantakr1 ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2023-03-03 16:57 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1

**Comment by pfortin-expertime** [comment] 2023-04-25 07:11
I may have a clue how to reproduce, it is to setup the store-view with another locale than US.

I'm using Korean and I get the same result as @jayantakr1 , because this function in  _Customer/Model/Metadata/Form/AbstractData.php_

`    /**
     * Get/Set/Reset date filter format
     *
     * @param string|null|false $format
     * @return $this|string
     */
    protected function _dateFilterFormat($format = null)
    {
        if ($format === null) {
            // get format
            if ($this->_dateFilterFormat === null) {
                $this->_dateFilterFormat = \IntlDateFormatter::SHORT;
            }
            return $this->_localeDate->getDateFormat($this->_dateFilterFormat);
        } elseif ($format === false) {
            // reset value
            $this->_dateFilterFormat = null;
            return $this;
        }

        $this->_dateFilterFormat = $format;
        return $this;
    }`

returns the format "yy. M. d." which is used later on with the filter, and it kinds messing up with the function bcsub

**Comment by joelness89** [comment] 2023-09-22 15:34
I am getting this error on:

Adobe Commerce ver. 2.4.5
PHP 8.1.23

Steps to re-produce
From admin navigate to customer specific record, make any edit , click Save

[2023-09-22T15:09:28.747977+00:00] report.CRITICAL: ValueError: bcsub(): Argument #1 ($num1) is not well-formed in /chroot/local/mecampbe/mecampbell.com/current/vendor/magento/zendframework1/library/Zend/Locale/Math.php:259
#0 /chroot/local/mecampbe/mecampbell.com/current/vendor/magento/zendframework1/library/Zend/Locale/Math.php(259): bcsub('2019-01-23 16:4...', '2019-01-23 16:4...', 0)

**Comment by joelness89** [comment] 2023-09-22 15:37
I am getting this error as well

Adobe Commerce ver. 2.4.5
PHP 8.1.23

Steps to re-produce
From admin navigate to customer specific record, make any edit , click Save

[2023-09-22T15:09:28.747977+00:00] report.CRITICAL: ValueError: bcsub(): Argument #1 ($num1) is not well-formed in /chroot/local/HIDDEN/HIDDEN.com/current/vendor/magento/zendframework1/library/Zend/Locale/Math.php:259
#0 /chroot/local/HIDDEN/HIDDEN.com/current/vendor/magento/zendframework1/library/Zend/Locale/Math.php(259): bcsub('2019-01-23 16:4...', '2019-01-23 16:4...', 0)

**Comment by janssensjelle** [comment] 2023-09-26 08:43
We have the same issue but we have this because we use a specific date notation on our other languages and have this in the template. This causes an issue with DOBs in the template that uses the en_us locale
