### ISSUE TITLE
Catalog Import Process Fails to Generate Category URL Rewrites for the multiple Website

### ISSUE THREAD

**Issue by mohammadbharmal** [magento/magento2#38354] opened 2024-01-17 06:53 UTC
### Preconditions and environment

- Magento version :- 2.4.6-p3

The Magento product import process generates a new category if it does not exist. However, when dealing with multiple websites and store views, and all store views share the same base category, the import process only generates URL rewrites for one store and website.

### Steps to reproduce

Steps:- 

1) Log in to the Magento admin panel.
2) Create a new website in the Magento admin named "test website."
3) Create a new store, and in the "Root Category" option, select "Default Category."
4) Create a new store view for the last created  store.
5) Create a product in the admin with the SKU "test."
6) Prepare a CSV file for product import, choosing "Add & Update" as the action.
7) In the CSV file, define a new category path as "Default Category/test-cat."
8)Import the CSV file.
9) Navigate to Marketing >> URL Rewrites and verify the URL rewrite for the newly created category.

I have attached sample CSV file below

[Maincategory.csv](https://github.com/magento/magento2/files/13959570/Maincategory.csv)
   

### Expected result

Should be create URL rewrite for the both website view

### Actual result

URL rewrite is generated but only for the one website view

### Additional information

I have encountered an issue while assigning categories to products. In the default Magento flow, if a category mentioned in the import CSV file doesn't exist in the Magento system, it creates a new category and assigns it to the associated product based on the CSV.

The specific case involves having two websites with different stores and store views, both sharing the same root category. When importing products, Magento creates new categories that do not exist. However, the problem is that URL rewrites are only generated for one website.

Creating categories manually from the admin works fine and generates URL rewrites for all websites.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mohammadbharmal** [comment] 2024-01-17 06:54
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-01-18 09:51
Hi @mohammadbharmal


Thanks for your report and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Log in to the Magento admin panel.
- Create a new website in the Magento admin named "test website."
- Create a new store, and in the "Root Category" option, select "Default Category."
- Create a new store view for the last created store.
- Create a product in the admin with the SKU "test."
- Prepare a CSV file for product import, choosing "Add & Update" as the action.
- In the CSV file, define a new category path as "Default Category/test-cat."
- 8)Import the CSV file.
- Navigate to Marketing >> URL Rewrites and verify the URL rewrite for the newly created category.


![Screenshot from 2024-01-18 12-32-22](https://github.com/magento/magento2/assets/51680745/3dd99940-33e9-485c-a0c4-2775673ae304)



URL rewrites created for the both website view

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by hostep** [comment] 2024-01-20 14:57
@mohammadbharmal: it might have been fixed by: https://github.com/magento/magento2/commit/96c6f2452b86ad52164df9236daf4e970d568e0a, maybe you can try out this change as a patch and see if that resolves your case? This fix is scheduled to be included in Magento 2.4.7. Is just a guess, I haven't verified this myself.

**Comment by engcom-Bravo** [comment] 2024-01-23 07:09
@hostep Thanks for your Contribution here.

Hi @mohammadbharmal,

Could you please refer this https://github.com/magento/magento2/issues/38354#issuecomment-1902123817 and this commit https://github.com/magento/magento2/commit/96c6f2452b86ad52164df9236daf4e970d568e0a and please let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-02-02 05:54
Hi @mohammadbharmal,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Bravo** 2024-02-02 05:54 UTC
Labels: Issue: needs update, Reported on 2.4.6-p3
