### ISSUE TITLE
custom option price of configurable products is not adding to cart   

### ISSUE THREAD

**Issue by gopalvenu033** [magento/magento2#3689] opened 2016-03-08 12:05 UTC
I have custom options for product and prices are different for custom options. When adding product to cart , product price is only added and not adding the prices of custom options

**Comment by aswaniachu** [comment] 2016-03-09 11:21
i hav also the same issue

**Comment by gopalvenu033** [comment] 2016-03-11 06:41
This issue is only in Magento2.0.1 and not in Magento2.0.2

**Comment by katmoon** [comment] 2016-03-12 12:03
Hi @aswaniachu 

Thank you for reporting the issue.

I cannot reproduce in on the latest Magento version. Maybe because as it has been fixed in 2.0.2 as @gopalvenu033 says.

I'm closing the ticket because of the reason given above.

Thanks,
Kateryna.

**Closed as completed by katmoon** 2016-03-12 12:03 UTC
