### ISSUE TITLE
Varnish purge error

### ISSUE THREAD

**Issue by bgkavinga** [magento/magento2#3315] opened 2016-02-06 17:37 UTC
In vendor/magento/module-page-cache/Model/Cache/Server.php following method creates uris for varnish cache purge. But here it does not set path correctly which make it to be invalid request in Zend\Http\Client\Adapter\Socket::write method. Correct cache purge should be looks like `PURGE / HTTP/1.1 X-Magento-Tags-Pattern: ((^|,)cms_page(,|$))|((^|,)cms_page_2(,|$))` but without correct path specified it is `PURGE HTTP/1.1 X-Magento-Tags-Pattern: ((^|,)cms_page(,|$))|((^|,)cms_page_2(,|$))`.(note the missing path (/) after PURGE) So the cache purging does not work as expected because of this issue. I think this sill effect the cache purge once the product get out of stock in front end which will cause out of stock products to be display in front end.

``` php
public function getUris()
    {
        $servers = [];
        $configuredHosts = $this->config->get(ConfigOptionsListConstants::CONFIG_PATH_CACHE_HOSTS);
        if (null == $configuredHosts) {
            $httpHost = $this->request->getHttpHost();
            $servers[] = $httpHost ?
                UriFactory::factory('')->setHost($httpHost)->setPort(self::DEFAULT_PORT)->setScheme('http') :
                UriFactory::factory($this->urlBuilder->getUrl('*', ['_nosid' => true])) // Don't use SID in building URL
                    ->setScheme('http')
                    ->setPath(null)
                    ->setQuery(null);

        } else {
            foreach ($configuredHosts as $host) {
                $servers[] = UriFactory::factory('')->setHost($host['host'])
                    ->setPort(isset($host['port']) ? $host['port'] : self::DEFAULT_PORT)
                    ->setScheme('http');
            }
        }
        return $servers;
    }
```

**Comment by davidalger** [comment] 2016-02-08 19:00
Duplicate of #2705

**Closed as completed by davidalger** 2016-02-08 19:00 UTC
