### ISSUE TITLE
Email templates 2.4.3-p2 wrong var

### ISSUE THREAD

**Issue by leonhelmus** [magento/magento2#35367] opened 2022-04-25 12:53 UTC
### Preconditions (*)

1. Magento 2.4.3-p2 open source / enterprise.
2. Php 7.4

### Steps to reproduce (*)

1. Load a creditmemo_new email from the backend. 
2. See for example: https://github.com/magento/magento2/blob/610f7f51faa94639da29f8001aded7559f114c54/app/code/Magento/Sales/view/frontend/email/creditmemo_new.html#L12
3. Check the vars: 
1. layout handle is correct. like: `layout handle="sales_email_order_creditmemo_items" creditmemo_id=$creditmemo_id order_id=$order_id:"Credit Memo Items Grid"`

### Actual result (*)

1. Layout handle is still wrong. like `"layout handle=\"sales_email_order_creditmemo_items\" creditmemo=$creditmemo order=$order":"Credit Memo Items Grid",`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-07-01 11:10
Verified the issue on Magento 2.4-develop branch and the issue is reproducible. 
As per Magento [devdocs](https://developer.adobe.com/commerce/frontend-core/guide/templates/email-layout-handle/),  layout handle should be:
layout handle="sales_email_order_creditmemo_items" creditmemo_id=$creditmemo_id order_id=$order_id:"Credit Memo Items Grid"

**Comment by artskirk** [comment] 2022-07-21 21:08
Seems like the following example: https://github.com/magento/magento2/blob/610f7f51faa94639da29f8001aded7559f114c54/app/code/Magento/Sales/view/frontend/email/creditmemo_new.html#L12 is correct and used together with escape quotes. The layout handle statement is already implemented on line 87:
https://github.com/magento/magento2/blob/610f7f51faa94639da29f8001aded7559f114c54/app/code/Magento/Sales/view/frontend/email/creditmemo_new.html#L87 

Please, provide the steps where [this](https://github.com/magento/magento2/blob/610f7f51faa94639da29f8001aded7559f114c54/app/code/Magento/Sales/view/frontend/email/creditmemo_new.html#L12) statement causes the Magento issue.

**Comment by engcom-November** [comment] 2022-08-16 12:25
Hi @leonhelmus ,
"layout handle" is correctly mentioned on line 87: magento2/app/code/Magento/Sales/view/frontend/email/creditmemo_new.html
and escape quotes are added in commented section: <!--@vars { for formatting purpose which cannot be removed. We are closing this issue as this statement does not effect Magento behavior. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-08-16 12:25 UTC
Labels: Component: Sales, Issue: Confirmed, Component: Email, Reproduced on 2.4.x, Priority: P3, Progress: done, Area: UI Framework, Reported on 2.4.3-p2

**Comment by pmonosolo** [comment] 2022-12-14 00:06
@leonhelmus How did you end up fixing this? Looks like it's still an issue even on Vanilla 2.4.5-p1

**Comment by leonhelmus** [comment] 2022-12-14 00:10
@pmonosolo just use the var in the actual result of my description of this issue.

**Comment by leonhelmus** [comment] 2022-12-14 00:13
@pmonosolo just use the var in the actual result of my description of this issue. @engcom-November I wasn't talking about the handle, but about the arguments that it added are scalar.

**Comment by pmonosolo** [comment] 2022-12-14 00:17
> 1. layout handle="sales_email_order_creditmemo_items" creditmemo_id=$creditmemo_id order_id=$order_id:"Credit Memo Items Grid"

So this would be the correct output?

"layout handle=\"sales_email_order_creditmemo_items\" creditmemo_id=$creditmemo_id order_id=$order_id:\"Credit Memo Items Grid\""

**Comment by leonhelmus** [comment] 2022-12-14 00:18
@pmonosolo should be yes.

**Comment by leonhelmus** [comment] 2022-12-14 00:18
@pmonosolo should be yes.

**Comment by pmonosolo** [comment] 2022-12-14 00:19
> @pmonosolo should be yes.

Hmmm, not working for me :(

When sending an email the items are just empty. The credit memo object just outputting NULL

**Comment by pmonosolo** [comment] 2022-12-14 00:20
Here is my full VARS section:

![image](https://user-images.githubusercontent.com/66754347/207473627-939a4b92-d124-40c8-9bcb-322acaa41292.png)

**Comment by leonhelmus** [comment] 2022-12-14 00:21
@pmonosolo maybe a third party module which screws it up. Or did you already check if the client overwritten the email templates from the backend

**Comment by pmonosolo** [comment] 2022-12-14 00:24
Y

> @pmonosolo maybe a third party module which screws it up. Or did you already check if the client overwritten the email templates from the backend

Yes, I'm using both Yireo email tester and the SEND button - both output no items.

![image](https://user-images.githubusercontent.com/66754347/207473932-0cb34076-7579-4b5b-ae0b-d5b14fd1d125.png)

Using Both **New Credit Memo** and **New Credit Memo (Magento / Luma)**.

**Comment by pmonosolo** [comment] 2022-12-14 00:27
@engcom-November Can you please try just sending the Credit Memo email using the default template?

Does the email arrive with items + taxes?
