### ISSUE TITLE
CSV import ignores "dropdown" and "multiselect" additional_attributes

### ISSUE THREAD

**Issue by YiffyToys** [magento/magento2#23922] opened 2019-07-27 14:16 UTC
### Preconditions (*)

1. Magento 2.3.2
2. create a number of additional attributes, some of them being of "dropdown" and "multiselect" type.

### Steps to reproduce (*)
1. import a simple products XML with the "additional_attributes" specifiing values for all custom attributes

### Expected result (*)

1. values for numerical and text attributes are imported correctly
2. values for attributes that must be selected are also imported

### Actual result (*)
1. values for numerical and text attributes are imported correctly
2. values for any attributes that must be selected from a limited range of options are not imported.

This is indepdent of using the string identifier (as the CSV export does) or the internal numeric identifier for the value to be selected when drafting the CSV

**Comment by YiffyToys** [comment] 2019-07-27 14:27
Update:
It DOES work when a separate CSV updates JUST one additional_attribute using the "Admin" value of the selectable option.

**Comment by engcom-Charlie** [comment] 2019-07-29 08:07
Hi @YiffyToys ! I can't reproduce this issue on fresh Magento 2.3-develop.

**Manual testing scenario:**
1.Create a number of additional attributes, some of them being of "dropdown" and "multiselect" type.
2.Import a simple products XML with the "additional_attributes" specifiing values for all custom attributes
3. Go to Caterlog->Products
4.Check values for attributes of created products

**Actual result:**
All values imported correctly.

I have to close this issue.
Thank you for your report!

**Closed as completed by engcom-Charlie** 2019-07-29 08:08 UTC
Labels: Component: ImportExport, Issue: Clear Description, Issue: Format is valid

**Comment by overrode** [comment] 2020-10-13 09:07
I have the same bug in Magento ver. 2.3.2. 
Step to reproduce:
1. Create dropdown attribute, in admin,  "custom_attribute" with options "option_1", "option_2".
2. In the sample file, in the row "additional_attributes" put custom_attribute=option_2;
3. IT WORKS!

But if i change 2. custom_attribute=option_3, the import fails!
![dropdown](https://user-images.githubusercontent.com/15195423/95840024-f63b8d80-0d43-11eb-837d-dad286dbfa04.png)

The importer does not add values there are not in the data base already.

**Comment by meer-online** [comment] 2020-11-15 08:25
@overrode  Facing the same issue, Any thougts? Were you able to fix this?

**Comment by rimmeh** [comment] 2021-06-25 11:21
Same Issue In Magento 2.4.2. Any Suggestions?

**Comment by Bhavik-kumar** [comment] 2021-11-11 14:13
@magento-engcom-team 
any plan when this issue will fix?
