### ISSUE TITLE
Customer Session is not logging sometimes

### ISSUE THREAD

**Issue by niranjanleanswift** [magento/magento2#8985] opened 2017-03-23 10:28 UTC
We are having the Magento 2.0.5 installed and running and when we are trying to log in frontend in random time with correct credentials we could not logging in It show "Invalid user or password" message and after sometime can log in. we have enabled the cache and folders with correct permissions  Could you suggest me the solution

**Comment by korostii** [comment] 2017-03-23 11:17
If you are looking for an advice please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. As GitHub issue tracker is intended for technical issues only.
The issues which cannot be consistently reproduced on a clean installation of the Magento CE (latest branch version, which is 2.0.13 in this case) aren't likely to get resolved in here.

Thus if you are reporting a technical issue, please try add as much information as possible, including the environment you use, 3rd party themes and modules installed, preconditions, steps to reproduce, etc. in order simplify attempts in reproducing it. Screenshots and stack trace from browser console (if any) are also helpful.

**Comment by veloraven** [comment] 2017-06-27 10:50
@niranjanleanswift thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by niranjanleanswift** [comment] 2017-06-29 04:08
However, this issue is not reproducible in magento 2.1.7

**Comment by magento-engcom-team** [comment] 2017-09-13 20:20
@niranjanleanswift thank you for research

**Closed as completed by magento-engcom-team** 2017-09-13 20:20 UTC
Labels: Progress: needs update, Issue: Format is not valid
