### ISSUE TITLE
Unable to load Frontend and Backend after dependency injection compilation in Magento 2.2 Cloud

### ISSUE THREAD

**Issue by giraclion** [magento/magento2#11755] opened 2017-10-26 01:04 UTC
After installing Magento 2.2 Cloud on Windows 10 + PHP 7.0 + MySQL 5.6 and running `php bin/magento setup:di:compile` I can no longer see any content when loading any frontend or backend page. Related to #11698 

### Preconditions
1. Windows 10
2. Magento 2.2.0 Cloud via composer, no custom code, no sample data, bare installation
3. PHP 7.0.15
4. Apache 2.4
5. MySQL 5.6
6. Magento Luma theme
7. Singe-site setup
8. Deployment mode: default
9. Chrome/Firefox

### Steps to reproduce
1. Get Magento 2.2.0 Cloud Edition
2. Install Magento using this commands sequence
```
$ composer install --no-dev
$ php bin/magento setup:install \
--base-url="http://website.local/" \
--use-secure=0 \
--use-secure-admin=0 \
--db-host=localhost \
--db-name=db_name \
--db-user=root \
--admin-use-security-key=0 \
--backend-frontname=admin \
--admin-user=admin \
--admin-password=password \
--admin-email="admin@website.local" \
--admin-firstname=Dev \
--admin-lastname=Admin \
--language=en_US \
--currency=USD \
--use-rewrites=1 \
--timezone=America/Los_Angeles \
--cleanup-database```
$ php bin/magento maintenance:enable
$ php bin/magento cache:flush
$ rm -rf $project_dir/var/cache/ \
    $project_dir/var/page_cache/ \
    $project_dir/generated/*/* \
    $project_dir/generated/*.* \
    $project_dir/var/view_preprocessed/ \
    $project_dir/pub/static/*/* \
    $project_dir/pub/static/*.*
$ php bin/magento module:enable --all
$ php bin/magento setup:upgrade
$ php bin/magento setup:di:compile
$ composer dump-autoload --no-dev --optimize
$ php bin/magento setup:static-content:deploy -f
$ php bin/magento indexer:reindex
$ php bin/magento cache:flush
$ php bin/magento maintenance:disable
``` 
3. Go to http://website.local/
4. Go to http://website.local/admin

### Expected result
1. Go to http://website.local/
The default Luma Home Page content is displayed
2. Go to http://website.local/admin
The default Admin Panel login form is displayed

### Actual result
1. Go to http://website.local/
Here instead of Home page content I see blank page, **no errors in browser console**. 
Page source is:
```
<!doctype html>
<html lang="en-US">
    <head >
                <meta charset="utf-8"/>
<meta name="keywords" content="Magento, Varien, E-commerce"/>
<meta name="robots" content="INDEX,FOLLOW"/>
<title></title>
<link  rel="icon" type="image/x-icon" href="http://relieffactor.local/pub/static/version1508977600/frontend/_view/en_US/Magento_Theme/favicon.ico" />
<link  rel="shortcut icon" type="image/x-icon" href="http://relieffactor.local/pub/static/version1508977600/frontend/_view/en_US/Magento_Theme/favicon.ico" />
            </head>
    <body data-container="body" data-mage-init='{"loaderAjax": {}, "loader": { "icon": "http://relieffactor.local/pub/static/version1508977600/frontend/_view/en_US/images/loader-2.gif"}}' class="cms-index-index page-layout-1column">
            </body>
</html>
```
**No error logs in ./magento/var/log/**
**No error logs in web server logs**

2. Go to http://website.local/admin
Here instead of Admin Panel login page I see blank page. Browser reports this:
```
This page isn’t working

website.local redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS
```
This is what happens in browser Console ->Network tab:
![2017-10-25_175843](https://user-images.githubusercontent.com/3818739/32030196-467ee86a-b9ae-11e7-9fe5-4ab1bb245b25.png)
**No error logs in ./magento/var/log/**
**No error logs in web server logs**

### Debug attempts
1. Tried to set `Copy` materialization strategy for `view_preprocessed` in app/etc/di.xml, but it **didn't help** to resolve the issue:
```
    <virtualType name="developerMaterialization" type="Magento\Framework\App\View\Asset\MaterializationStrategy\Factory">
        <arguments>
            <argument name="strategiesList" xsi:type="array">
                <item name="view_preprocessed" xsi:type="object">Magento\Framework\App\View\Asset\MaterializationStrategy\Copy</item>
                <item name="default" xsi:type="object">Magento\Framework\App\View\Asset\MaterializationStrategy\Copy</item>
            </argument>
        </arguments>
    </virtualType>
```
2. If I remove generated/ folder, everything starts to work and I see the home page and backend logic page
3. Clearing cookies, doesn't help

**Comment by orlangur** [comment] 2017-10-26 09:49
Hi @giraclion,

Can you reproduce an issue using a supported operating system: http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html? Note that Windows is not in the list.

Closing as a duplicate of https://github.com/magento/magento2/issues/11491, please share any additional details there.

**Closed as completed by orlangur** 2017-10-26 09:49 UTC
Labels: duplicate, Issue: Format is valid
