### ISSUE TITLE
UPS shipping label creation giving Invalid Authentication Information

### ISSUE THREAD

**Issue by Zansys** [magento/magento2#25685] opened 2019-11-21 14:07 UTC
Hi guys,

I've got UPS authentication error when try to create shipment with selected 'Create Shipping Label' shipping option.

### Preconditions (*)

1. Magento 2.3.1 (with sample data) & 2.3-develop
2. Centos 7.6
3. PHP 7.2.22

### Steps to reproduce (*)

1. Create order using some UPS shipping method
2. Login to the admin panel and select created order.
3. Click 'Ship' button and choose checkbox 'Create Shipping Label', click 'Submit Shipment' button.
4. Click 'Add Products to Package'
5. Configure package and select products.
6. Click 'Add Selected Product(s) to package'.
7. Click 'Save' button.
8. Get the error message 

### Expected result (*)
Shipment should be created without error. Because UPS is configured correctly. It works on checkout and shipment can be created without 'Create Shipping Label' shipping option.

### Actual result (*)
![image](https://user-images.githubusercontent.com/51680850/69413918-64d1c000-0d1a-11ea-8313-a8f096b61c94.png)

UPS ShipmentConfirmRequest request returns

<?xml version="1.0"?>
<ShipmentConfirmResponse>
<Response>
    <ResponseStatusCode>0</ResponseStatusCode>
    <ResponseStatusDescription>Failure</ResponseStatusDescription>
    <Error>
        <ErrorSeverity>Hard</ErrorSeverity>
        <ErrorCode>250002</ErrorCode>
        <ErrorDescription>Invalid Authentication Information.</ErrorDescription>
    </Error>
</Response>
</ShipmentConfirmResponse>

The configurations seem to be correct, have been checked several times, urgent help required

Thanks

**Comment by engcom-Charlie** [comment] 2019-11-22 09:15
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-22 09:15
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-22 09:16
Hi @engcom-Charlie, here is your [Magento instance](https://i-25685-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25685-2-3-develop.instances.magento-community.engineering/admin](https://i-25685-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-11-22 09:25
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29067` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ajithkumar-maragathavel** [comment] 2019-12-04 09:27
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-12-04 09:27
Hi @ajithkumar-maragathavel. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-12-04 09:28
Hi @ajithkumar-maragathavel, here is your [Magento instance](https://i-25685-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25685-2-3-develop.instances.magento-community.engineering/admin](https://i-25685-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajithkumar-maragathavel** [comment] 2019-12-04 10:04
@magento @Zansys This issue is caused because of configuration settings.
Please go to **Stores -> Settings -> Configuration -> Sales -> Shipping Settings -> Origin** 
and Fill out all the fields.

After filling out all the address fields, you can able to create shipment label in UPS.

Please refer to the below screenshot. 
![shipment-origin](https://user-images.githubusercontent.com/47966038/70133126-8b451300-16ab-11ea-8c91-20f81219326a.png)

**Closed as completed** 2019-12-04 10:05 UTC
Labels: Issue: Ready for Work, Component: Shipping, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid
