### ISSUE TITLE
Magento 2.4.1 displays Cart Price Rule's descriptions incorrectly

### ISSUE THREAD

**Issue by ivan-prysiazhniuk** [magento/magento2#30955] opened 2020-11-17 16:02 UTC
### Preconditions (*)

1. Pure Magento 2.4.1
2. PHP 7.4.12
3. Mysql - MariaDB 10.4.17
4. Elasticsearch 7.6.2
5. Server - Apache2 (2.4.29)
6. Installed Sample Data

### Steps to reproduce (*)

1. Create two cart price rules in the admin panel with these sets of data:

**first rule:**
> cart rule name: **5% (test)**
> description: **_leave empty_**
> websites: **Main Website**
> customer groups: **_all available_**
> coupon: **no**
> apply: **percent of product price discount**
> discount amount: **5**
> labels: **_leave empty_**
> 
> **other fields in not necessary.**

**second rule:**
> cart rule name: **10% (test)**
> description: **10% test description**
> websites: **Main Website**
> customer groups: **_all available_**
> coupon: **yes**
> coupone code: **10COUPON**
> apply: **percent of product price discount**
> discount amount: **5**
> labels: **_leave empty_**
> 
> **other fields in not necessary.**

2. Go to the storefront catalog and add **two or more** products to the cart
3. Go to "View and Edit Cart"
4. Apply coupon code "10COUPON"

### Expected result (*)

1. Title of discount total contains only a description of rule with coupon code as rule without code doesn't have a description 
![Screenshot from 2020-11-17 16-48-52](https://user-images.githubusercontent.com/39122839/99407576-ee00e000-28f7-11eb-848e-239c4af28cf1.jpg)

### Actual result (*)

1. Title of discount total contains both comma-separated description and code of rule with coupon code
![Screenshot from 2020-11-17 16-42-10](https://user-images.githubusercontent.com/39122839/99407698-11c42600-28f8-11eb-816f-1b59fb1e03f7.jpg)
2. If you have only one product in the cart and the same rules, then discount descriptions will be displayed correctly
![Screenshot from 2020-11-17 17-00-14](https://user-images.githubusercontent.com/39122839/99407709-15f04380-28f8-11eb-9e5d-cce9e50f010d.jpg)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-12-01 15:36
Hi @ivan-prysiazhniuk ,
Verified the issue on Magento 2.4-develop instance with above steps mentioned but the issue is not reproducible on both Shopping cart page and checkout page with 2 or products.
![image](https://user-images.githubusercontent.com/60198231/205094501-c6d8d96d-d93b-42b4-976f-b29cb0700e6a.png)

![image](https://user-images.githubusercontent.com/60198231/205094431-f5d9e09e-496d-4d91-ae31-d0be3ac46f70.png)
Kindly recheck the issue on Magento 2.4-develop instance and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-12-14 07:56
Hi @ivan-prysiazhniuk ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-12-14 07:56 UTC
Labels: Issue:  Cannot Reproduce, Priority: P3, Severity: S3, Progress: done, Issue: ready for confirmation, Issue: needs update
