### ISSUE TITLE
State / Provinz is required

### ISSUE THREAD

**Issue by Me7z** [magento/magento2#8565] opened 2017-02-15 11:53 UTC
The config for state / Province doesn't matter for customer addresses in Backend. The information has to been set every time i save a customer address. Any idea why this is happening ?

**Comment by mbrinton01** [comment] 2017-02-15 17:51
Closing as duplicate of already reported issue #8152.  Thank you for your submission!

**Closed as completed by mbrinton01** 2017-02-15 17:51 UTC
