### ISSUE TITLE
Image get disappeared after saving the category 

### ISSUE THREAD

**Issue by hemendraajmera** [magento/magento2#25667] opened 2019-11-20 11:45 UTC
### Preconditions (*)

Magento ver. 2.3.

### Steps to reproduce (*)

1. open any category
2. upload image from upload button with new image and it working.
3. now open category in edit mode.
4. navigate to content section and this time click on select from the gallery and select any uploaded image it will show image on image place holder.
5. save the category.
6. now again check the image on the content section, it will not showing.

### Expected result (*)

1. image should be displayed on the category page on frontend as well in backend after the change 
before saving 
![image](https://user-images.githubusercontent.com/2478037/69236299-3dafad00-0bb9-11ea-9480-00cb30a92350.png)
after saving category 
![image](https://user-images.githubusercontent.com/2478037/69236361-58822180-0bb9-11ea-906b-b6e126952e25.png)

### Actual result (*)

1. category image not showing on both frontend and backend location 
2.

**Comment by AnnaShepa** [comment] 2019-11-20 12:07
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-20 12:07
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-20 12:07
Hi @AnnaShepa, here is your [Magento instance](https://i-25667-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25667-2-3-develop.instances.magento-community.engineering/admin](https://i-25667-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AnnaShepa** [comment] 2019-11-20 12:22
Hi @hemendraajmera thank you for the report. Unfortunately I cannot reproduce the issue. 
Please make sure that you upload correct image type and size. You can try to reproduce the issue using [at]magento give me 2.3-develop instance in comment. Or just provide more information in steps to reproduce, btw. was the image saved and shown on UI after the 1st step?

**Comment by hemendraajmera** [comment] 2019-11-21 04:08
Thanks for updates.
Please follow below steps to reproduce the issue:
1. open any category 
2. upload image from upload button with new image and it working.
3. now open category in edit mode.
4. navigate to content section and this time click on select from the gallery and select any uploaded image it will show image on image place holder.
5. save the category.
6. now again check the image on the content section, it will not showing.

can you please share instance where i can recheck.

**Comment by AnnaShepa** [comment] 2019-11-21 08:30
@hemendraajmera  thank you for update, I will try again. You can always just write 
`@magento give me 2.3-develop instance`
in comment to any ticket and in a few seconds you will get an instance for 3 hours

**Comment by magento-engcom-team** [comment] 2019-11-21 08:30
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-21 08:31
Hi @AnnaShepa, here is your [Magento instance](https://i-25667-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25667-2-3-develop.instances.magento-community.engineering/admin](https://i-25667-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2019-11-21 11:24
Hi @hemendraajmera. issue is duplicate to #25099 
Issue will be fixed in next 2.3.4 release
You can review the feedback from above given issue link.
Thanks.

**Comment by krishprakash** [comment] 2019-11-21 11:25
Closing this ticket as it's already fixed in 2.3-develop

**Closed as completed by krishprakash** 2019-11-21 11:25 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid
