### ISSUE TITLE
Credit Card processing failure is not correctly handled

### ISSUE THREAD

**Issue by rzinnatullin** [magento/magento2#13797] opened 2018-02-22 16:54 UTC
### Preconditions

1. Magento 2.1.11
2. PHP 7.0
3. MySQL 5.7.20-0ubuntu0.16.04.1

### Steps to reproduce
1. Enable 'Check/Money' payment method
2. Enable 'Payflow Pro' payment method. Note that 'Hosted Checkout Pages' feature should be **disabled** for the Payflow Pro account you use.
3. Also set the following for the 'Payflow Pro' payment method:
Test mode: Yes
Enable this solution: Yes
Enable Paypal Credit: No
Vault enabled: No
4. Save the config, flush Magento cache
5. Login to store front (create new account if needed)
6. Add any simple product to cart
7. Click on the cart image > Go to Checkout
8. Fill some shipping address or leave default shipping address and click Next
9. Select 'Credit Card' payment method
10. Fill in:
Credit Card Number: 4111111111111111
Expiration Date: some date in the future
Card Verification Number: 123
11. Click Place order

### Actual result
12. Note that due to some error in Magento 2, the checkout process stays on the Payment Method page, and no error message is displayed. The error is related to the fact that the Payflow Pro account you used doesn't support 'Hosted Checkout Pages'.
13. Click on 'Check/Money' payment method
14. Click Place order
15. Execute the SQL against the Magento DB:
```SQL
select
  entity_id, shipping_amount, amount_ordered, cc_exp_month, method, cc_last_4, cc_type, cc_exp_year
from
  sales_order_payment
order by 
  entity_id desc
limit
  1
```
16. You'll see that method is `checkmo`, and at the same time there are CC details, like `cc_last_4`, `cc_type` and so on, for example:
![image](https://user-images.githubusercontent.com/11244866/36551244-f9f81bc8-1818-11e8-9e58-19718d43c250.png)

### Expected result
At step 11- on `Place order` button the user should be warned that something went wrong
At step 16 - there shouldn't be credit card related details in the corresponding record of `sales_order_payment` table.

### Video demo
https://youtu.be/YPh_njhAx8w

**Comment by magento-engcom-team** [comment] 2018-03-06 15:30
@rzinnatullin, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by engcom-Charlie** [comment] 2019-12-10 10:19
Hello @rzinnatullin 
Thank you for contribution and collaboration!

We are not able to reproduce this issue on the latest 2.4-develop branch by provided steps.

**Testing scenario:**

1. Enable 'Check/Money' payment method
2. Enable 'Payflow Pro' payment method. Note that 'Hosted Checkout Pages' feature should be disabled for the Payflow Pro account you use.
3. Also set the following for the 'Payflow Pro' payment method:
4. Test mode: Yes
5. Enable this solution: Yes
6. Enable Paypal Credit: No
7. Vault enabled: No
8. Save the config, flush Magento cache
9. Login to store front (create new account if needed)
10. Add any simple product to cart
11. Click on the cart image > Go to Checkout
12. Fill some shipping address or leave default shipping address and click Next
13. Select 'Credit Card' payment method
14. Fill in:
15. Credit Card Number: 4111111111111111
16. Expiration Date: some date in the future
17. Card Verification Number: 123
18. Click Place order

**Result:**
At step 11- on Place order button we got warning that something went wrong
![image](https://user-images.githubusercontent.com/51680850/70520792-c2ea0a00-1b46-11ea-8afe-41957f60529d.png)
In payment log we got error code:
```
'respmsg' => 'Invalid vendor account',
'result_code' => '26'
```
We are closing this issue due to branch `2.2-develop` was closed and
> Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.

 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-12-10 10:19 UTC
Labels: Issue: Clear Description, Issue: Format is valid
