### ISSUE TITLE
paypal checkout issue

### ISSUE THREAD

**Issue by michelecanal** [magento/magento2#23719] opened 2019-07-16 07:25 UTC
### Preconditions (*)

1. Magento CE 2.3.2
2. Php 7.1
3. braintree and paypal checkout (sandbox)
4. debug option off
5. developer or production mode

### Steps to reproduce (*)

1. add a product to cart
2. click on paypal checkout
![Immagine1](https://user-images.githubusercontent.com/22873665/61273932-f5b3f000-a7aa-11e9-9f0d-1e06ae3e32ad.jpg)
3. fill with paypal sandbox account

### Expected result (*)

1. payment anche order submission

### Actual result (*)

1. fatal error
`Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Payment\Model\Method\Logger::debug() must be of the type array, null given, called in /home/tdsbaruy/test2.copertineperneonato.it/vendor/magento/module-braintree/Controller/Paypal/Review.php on line 69 and defined in /home/tdsbaruy/test2.copertineperneonato.it/vendor/magento/module-payment/Model/Method/Logger.php:51 Stack trace: #0 /home/tdsbaruy/test2.copertineperneonato.it/vendor/magento/module-braintree/Controller/Paypal/Review.php(69): Magento\Payment\Model\Method\Logger->debug(NULL) #1 /home/tdsbaruy/test2.copertineperneonato.it/generated/code/Magento/Braintree/Controller/Paypal/Review/Interceptor.php(24): Magento\Braintree\Controller\Paypal\Review->execute() #2 /home/tdsbaruy/test2.copertineperneonato.it/vendor/magento/framework/App/Action/Action.php(108): Magento\Braintree\Controller\Paypal\Review\Interceptor->execute() #3 /home/tdsbaruy/test2.copertineperneonato.it/vendor/magento/module-braintree/Controller/Paypal/AbstractAction.php(66): Magento\Framewo in /home/tdsbaruy/test2.copertineperneonato.it/vendor/magento/module-payment/Model/Method/Logger.php on line 51
`

**Comment by michelecanal** [comment] 2019-07-16 07:27
@magento give me 2.3-develop instance - 2.3.2

**Comment by magento-engcom-team** [comment] 2019-07-16 07:27
Hi @michelecanal. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-16 07:27
Hi @michelecanal, here is your [Magento instance](https://i-23719-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23719-2-3-develop.instances.magento-community.engineering/admin](https://i-23719-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by michelecanal** [comment] 2019-07-16 07:44
Hi,
I confirm the bug
![Immagine2](https://user-images.githubusercontent.com/22873665/61275403-2ea19400-a7ae-11e9-824f-2b9f562376bb.jpg)

**Comment by engcom-Charlie** [comment] 2019-07-16 10:34
Hello @michelecanal ! Thank you for your report !
Can you confirm that this issue is reproducible on Vanilla Magento instance ?

**Comment by michelecanal** [comment] 2019-07-16 10:40
Hi,
Yes I confirm
You can check the error in report of instance

Il Mar 16 Lug 2019 12:35 Robert Turchyn <notifications@github.com> ha
scritto:

**Comment by engcom-Charlie** [comment] 2019-07-17 09:00
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-17 09:00
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-17 09:00
Hi @engcom-Charlie, here is your [Magento instance](https://i-23719-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23719-2-3-develop.instances.magento-community.engineering/admin](https://i-23719-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment] 2019-07-17 11:59
Hello @michelecanal ! Thank you for your report !
I can confirm that this issue is reproducible , thanks for your contribution !

**Comment by magento-engcom-team** [comment] 2019-07-17 12:00
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18226` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-11-21 20:22
Hi @michelecanal. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-18226` was closed as `non-reproducible` in `2.3-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Closed as completed by magento-engcom-team** 2019-11-21 20:22 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Paypal

**Comment by sumeetmagento** [comment] 2021-04-28 12:30
@michelecanal are you able to solve this?
because I am getting this issue.
