### ISSUE TITLE
Permissions Error When Running `bin/magento setup:upgrade`

### ISSUE THREAD

**Issue by astorm** [magento/magento2#3693] opened 2016-03-08 22:44 UTC
Re-opening  #3092.  That ticket was closed with

> We have merged a fix in the develop branch, hence closing this ticket. Please create a new ticket if issues still arise.

However, there was no link to the specific merged fix, which makes it impossible to verify if the issues was addressed, or even understood.

**Comment by mazhalai** [comment] 2016-03-09 14:41
https://github.com/magento/magento2/commit/94ac1a63f0f4a8327f1c69b2f96e3f99c70d908d

The ticket number was missing from the title, so it did not auto link to issue.

**Comment by erikhansen** [comment] 2016-03-10 08:58
@astorm - Thanks for re-opening the ticket as I too was wanting to see the related commit.

@mazhalai - There are still situations in which the "Missing write permissions to the following directories" error will occur. The current error message is generic and doesn't provide the user with any information to troubleshoot the issue. It would be nice if the error message could include the path that was causing the error to occur.

**Comment by mazhalai** [comment] 2016-03-23 14:32
@astorm @erikhansen thank you. We have created MAGETWO-50845 to fix this issue.

**Comment by mazhalai** [comment] 2016-04-08 19:51
@astorm @erikhansen, I had trouble reproducing this issue, and it looks like this issue has been fixed in scope of another task. Please see https://github.com/magento/magento2/commit/aea3bd163ae8b25ab071b6a871167dec96bbeb62

Can you please verify? Will make the list of files easier to read in scope of this task.

**Comment by erikhansen** [comment] 2016-04-08 20:16
@mazhalai At a glance, the code in that commit looks like it will display the files whose permissions are problematic, so as far as I'm concerned, you can close this ticket.

**Comment by mazhalai** [comment] 2016-04-18 13:32
@astorm @erikhansen minor changes related to issue have been contributed. Closing ticket.

**Closed as completed by mazhalai** 2016-04-18 13:32 UTC
Labels: Issue: Ready for Work
