### ISSUE TITLE
Magento very slow after upgrade to 2.3.4 community

### ISSUE THREAD

**Issue by alex9434** [magento/magento2#26795] opened 2020-02-10 14:07 UTC
### Preconditions (*)

1. Magento 2.3.4 community (upgrade from 2.3.3
2. PHP 7.3, nginx, varnish, redis on Devuan Ascii

### Steps to reproduce (*)

1. Upgrade magento from 2.3.3 according to https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html
2. Website extremely slow (google lighthouse times out). CLI also very slow, e.g. magento cache:clean takes 5 min

### Expected result (*)

1. Speed comparable to 2.3.3
2. I don't know how to find the root cause of the slow speed

### Actual result (*)

1. Website has become very slow

**Comment by bahramdavodi** [comment] 2020-02-10 14:43
@alex9434, you can check with blackfire or some tool. maybe you installed some extension or ...
also check your magento cache status.

**Comment by Quazz** [comment] 2020-02-10 16:36
There was a bug (that should be fixed in 2.3.4) that disabled your caches when you updated certain things.

So re-enable your caches.

**Comment by Swahjak** [comment] 2020-02-11 10:13
This might be a duplicate of #26692 (#26809 also complaining about higher resource usage, but might be contained to cron).

**Comment by engcom-Alfa** [comment] 2020-02-12 07:16
Duplicate of #26692

**Closed as completed by engcom-Alfa** 2020-02-12 07:16 UTC
Labels: Issue: Format is valid, Reported on 2.3.3
