### ISSUE TITLE
Unable to remove sampledata

### ISSUE THREAD

**Issue by matteolavaggi** [magento/magento2#32934] opened 2021-05-04 11:20 UTC
### Preconditions (*)
Install a magento 2.4.2 using composer
Set
`bin/magento deploy:mode:set developer`
Install sampledata and restart all the web server / php /varnish

### Steps to reproduce (*)

```
bin/magento sampledata:deploy
bin/magento setup:upgrade
bin/magento cache:flush
sudo service php7.4-fpm restart
sudo service nginx restart
sudo service varnish restart
```

### Expected result (*)
Image on frontend must be here and web page must not have error

### Actual result (*)

1) Refused to apply style from 'https://XXX.com/%7B%7BMEDIA_URL%7D%7Dstyles.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
2) https://XXX.com/media/catalog/product/cache/e7428822a7f3a70d150ae703dc9c7030/m/p/mp03-black_main_1.jpg -> image not shown

### Additional step
To solve the css problem i need to manual delete /pub/static/* directory, otherwise there is no way to adress this problem

`rm -rf /pub/static/*`

**Try to remove sample data**

```
bin/magento sampledata:remove
bin/magento setup:upgrade
bin/magento cache:flush
sudo service php7.4-fpm restart
sudo service nginx restart
sudo service varnish restart
```

**Open frontend or backend page give this error**

```
1 exception(s):
Exception #0 (Magento\Framework\Exception\FileSystemException): The contents from the "/var/www/html/magento2/vendor/magento/module-catalog-sample-data/etc/module.xml" file can't be read. Warning!file_get_contents(/var/www/html/magento2/vendor/magento/module-catalog-sample-data/etc/module.xml): failed to open stream: No such file or directory

Exception #0 (Magento\Framework\Exception\FileSystemException): The contents from the "/var/www/html/magento2/vendor/magento/module-catalog-sample-data/etc/module.xml" file can't be read. Warning!file_get_contents(/var/www/html/magento2/vendor/magento/module-catalog-sample-data/etc/module.xml): failed to open stream: No such file or directory
<pre>#1 Magento\Framework\Module\ModuleList\Loader->getModuleConfigs() called at [vendor/magento/framework/Module/ModuleList/Loader.php:83]
#2 Magento\Framework\Module\ModuleList\Loader->load() called at [vendor/magento/framework/Module/ModuleList.php:72]
#3 Magento\Framework\Module\ModuleList->getAll() called at [vendor/magento/framework/Module/ModuleList.php:91]
#4 Magento\Framework\Module\ModuleList->getOne() called at [vendor/magento/framework/Module/DbVersionInfo.php:144]
#5 Magento\Framework\Module\DbVersionInfo->isModuleVersionEqual() called at [vendor/magento/framework/Module/DbVersionInfo.php:59]
#6 Magento\Framework\Module\DbVersionInfo->isSchemaUpToDate() called at [vendor/magento/framework/Module/DbVersionInfo.php:103]
#7 Magento\Framework\Module\DbVersionInfo->getDbVersionErrors() called at [vendor/magento/framework/Module/Plugin/DbStatusValidator.php:119]
#8 Magento\Framework\Module\Plugin\DbStatusValidator->getGroupedDbVersionErrors() called at [vendor/magento/framework/Module/Plugin/DbStatusValidator.php:53]
#9 Magento\Framework\Module\Plugin\DbStatusValidator->beforeDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:121]
#10 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:71]
#11 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#12 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#13 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#14 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#15 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#16 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:263]
#17 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]
</pre>

```

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by matteolavaggi** [comment] 2021-05-04 11:30
Ok one parts is my mistake, remember to enable opcache revalidate timestamp to 1 on php (cli and fpm) config

To solve the 

```
1 exception(s):
Exception #0 (Magento\Framework\Exception\FileSystemException):
```

error please remember to disable opcache or configure according developer need.

```
vim /etc/php/7.4/cli/php.ini

vim /etc/php/7.4/fpm/php.ini
```

change 

`opcache.validate_timestamps=0`

to

`opcache.validate_timestamps=1`


BTW sample data are not removed from the store and css problem cant be solved deleting another time /pub/static folder.

![image](https://user-images.githubusercontent.com/24798703/116997223-cef6de80-acdc-11eb-8b00-edcb45cf33ad.png)
![image](https://user-images.githubusercontent.com/24798703/116997280-e3d37200-acdc-11eb-89ac-2ef6b3250083.png)

**Comment by matteolavaggi** [comment] 2021-05-04 12:37
There is no way to have back a working magento setup, i'm a bit confused because the operation is quite simple !

```
Uncaught ReferenceError: Unable to process binding "template: function(){return getTemplate() }"
Message: getTemplate is not defined
    at template (eval at createBindingsStringEvaluator (knockout.js:2982), <anonymous>:3:61)
    at init (knockout.js:5454)
    at knockout.js:3358
    at Object.ignore (knockout.js:1470)
    at knockout.js:3357
    at Object.arrayForEach (knockout.js:159)
    at applyBindingsToNodeInternal (knockout.js:3343)
    at applyBindingsToNodeAndDescendantsInternal (knockout.js:3223)
    at applyBindingsToDescendantsInternal (knockout.js:3205)
    at applyBindingsToNodeAndDescendantsInternal (knockout.js:3232)
```

**Comment by mrtuvn** [comment] 2021-05-04 15:13
remove content with pub/static/* will delete all content inside static folder (included .htaccess) This may cause some issue and magento will not work properly
You should avoid run that command

**Comment by matteolavaggi** [comment] 2021-05-04 17:53
Hi thanks for your feedback, but I ran Magento under nginx so I don't need
htacces. Btw I've a copy of that file to be able to restore from git
archive (obviously with no difference in this behaviour).

Is a strange issue, I really can't address it, it's the second time I need
to reinstall from scratch , but I need to be able to install and uninstall
module and sample data with no issue before proceed with this cluster
setup. Any other idea?



Il Mar 4 Mag 2021, 17:13 Tu Nguyen ***@***.***> ha scritto:

**Comment by matteolavaggi** [comment] 2021-05-05 08:06
Here after a magento complete reinstall and running 

`composer update`

Magento does not remove the module sample data entry from database. Any idea?

```
g>
<warning>Package "magento/module-bundle-sample-data" listed for update is not installed. Ignoring.</warning>
<warning>Package "magento/module-catalog-sample-data" listed for update is not installed. Ignoring.</warning>
<warning>Package "magento/module-sales-sample-data" listed for update is not installed. Ignoring.</warning>
<warning>Package "magento/module-customer-sample-data" listed for update is not installed. Ignoring.</warning>
<warning>Package "magento/module-cms-sample-data" listed for update is not installed. Ignoring.</warning>
<warning>Package "magento/module-theme-sample-data" listed for update is not installed. Ignoring.</warning>
<warning>Package "magento/module-widget-sample-data" listed for update is not installed. Ignoring.</warning>
<warning>Package "magento/module-wishlist-sample-data" listed for update is not installed. Ignoring.</warning>
<warning>Package "magento/module-downloadable-sample-data" listed for update is not installed. Ignoring.</warning>
<warning>Package "magento/module-review-sample-data" listed for update is not installed. Ignoring.</warning>
<warning>Package "magento/module-tax-sample-data" listed for update is not installed. Ignoring.</warning>
<warning>Package "magento/module-msrp-sample-data" listed for update is not installed. Ignoring.</warning>
<warning>Package "magento/module-catalog-rule-sample-data" listed for update is not installed. Ignoring.</warning>
<warning>Package "magento/module-configurable-sample-data" listed for update is not installed. Ignoring.</warning>
<warning>Package "magento/module-product-links-sample-data" listed for update is not installed. Ignoring.</warning>
<warning>Package "magento/module-grouped-product-sample-data" listed for update is not installed. Ignoring.</warning>
<warning>Package "magento/module-sales-rule-sample-data" listed for update is not installed. Ignoring.</warning>
<warning>Package "magento/module-offline-shipping-sample-data" listed for update is not installed. Ignoring.</warning>
<warning>Package "magento/module-swatches-sample-data" listed for update is not installed. Ignoring.</warning>
<warning>Package "magento/sample-data-media" listed for update is not installed. Ignoring.</warning>
```

**Comment by matteolavaggi** [comment] 2021-05-05 08:25
Also on Content->desing->Configuration->theme is left  a ref url from sampledata deploy that point to a missing css. This url must be removed from config when run sampledata:remove

**Comment by magento-engcom-team** [comment] 2021-05-24 13:10
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42407` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Lima** [comment] 2021-06-02 14:01
Hi @matteolavaggi,

Unfortunately, Can't reproduce the issue. As per magento documentation it is not an issue.
https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli-sample-data-other.html#inst-sample-remove

"sampledata:remove" command does not remove sample data from the database.  Hence closing this issue. if you have any other issue raise as new ticket.

**Closed as completed by engcom-Lima** 2021-06-02 14:01 UTC
Labels: non-issue, Progress: done, Issue: ready for confirmation, Reported on 2.4.2

**Comment by magento-engcom-team** [comment] 2021-06-02 14:03
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by matteolavaggi** [comment] 2021-06-02 17:01
So it's ok that For remove sample data need to manual clean database,
delete product and change settings, and also remove call to CSS added from
the install procedure?

Il Mer 2 Giu 2021, 16:03 Magento Community Engineering <
***@***.***> ha scritto:
