### ISSUE TITLE
Magento import product csv do not import all crosssell relations

### ISSUE THREAD

**Issue by oleksandrmakhno** [magento/magento2#29559] opened 2020-08-14 20:54 UTC
### Preconditions 
1. Magento EE 2.3.5-p2, Magento CE 2.4
2. Mysql version 5.7.31-0ubuntu0.18.04.1
3. Php version 7.3.21-1+ubuntu18.04.1+deb.sury.org+1

### Steps to reproduce 
1. Prepare for import file product.csv with data in column crosssell_skus
2. Product.csv file should contain more than 100 products
3. the product A on line 100 or lower should have crosssell_sku, let say 5 relations
3. the product B on line 101 or higher should have crosssell_sku, obligatory less then 5 relations (less relations than in product A)

### Expected result
1. product A crosssell_sku relations will be imported to Magento
2. product B crosssell_sku relations will be imported to Magento

### Actual result 
1. product A crosssell_sku relations will be imported to Magento
2. product B crosssell_sku relations won't be imported to Magento

### Workaround
1. import product in csv up to 100 products (rows) each, so if more - need to split csv 

### Research results
1. we have column catalog_product_link.link_id which is autoincrement
2. for some reason we managing this autoincrement value in the code
3. on line #1240 we get $nextLinkId = 1 (in my tests it was always 1)
4. on line #1255 we are in loop of bunches (100 products each), but $nextLinkId is always 1
5. as result of every bunch autoincrement starting from 1 - new lines are not inserted in catalog_product_link
6. as possible solution see added line #1254, in such case $nextLinkId will be updated every bunch with actual value
7. I presume the bunch logic was added later, while $nextLinkId logic was not refactored 

![image](https://user-images.githubusercontent.com/1440790/90291194-07713680-de88-11ea-9e5e-bbad89ab14aa.png)
![image](https://user-images.githubusercontent.com/1440790/90291224-16f07f80-de88-11ea-8308-77190b3238f0.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [+] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Oscar** [comment] 2020-08-17 14:08
Hi  @oleksandrmakhno !

Thank you for your report and collaboration!

I closing this issue, because I was unable to reproduce it using provided Steps to Reproduce from the Description section on clean 2.4-develop branch of Magento. Perhaps the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the Description section and reopen this issue.

**Closed as completed by engcom-Oscar** 2020-08-17 14:08 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid, Reported on 2.3.5-p2
