### ISSUE TITLE
Not getting applied store credit with API salesOrderRepositoryV1GetListGet

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#35324] opened 2022-04-19 05:15 UTC
### Preconditions (*)

1. Magento version 2.4.2

### Steps to reproduce (*)

1. Create an order with store credit 
2. Download the order via magento 2 rest api https://magento.redoc.ly/2.3.7-admin/tag/orders#operation/salesOrderRepositoryV1GetListGet
3. You will not found any node related to store credit applied on this order 

### Expected result (*)

1. Please find the order with store credit 
![image-20220413-231546](https://user-images.githubusercontent.com/54638813/163924398-03e12152-7c10-406b-a548-c51bf90b79a5.png)
2 Please find the response of same order with salesOrderRepositoryV1GetListGet 
[Magento_Order_1000309696_Response.txt](https://github.com/magento/magento2/files/8509991/Magento_Order_1000309696_Response.txt)
3. We are unable to found any node for store credit $2600

### Actual result (*)

1. The applied store credit should come with in api response of salesOrderRepositoryV1GetListGet  or suggest any other api which provides the applied store credit. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ S0] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-04-19 09:57
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-04-21 11:39
Hi @webgility-amazonapi ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch with Enterprise edition modules enabled but cannot able to reproduce the issue.
Steps performed:
1. Created Orders using store credit from Admin (Verified both cases: Partial/full store_credit amounts applied )
2. Get request to /rest/default/V1/orders/  and
/rest/default/V1/orders/{id}
Response:
"base_customer_balance_amount" and  "customer_balance_amount" (customer balance adjusted for Order ) fields are retrieved in the response when store credit is used for creating Order:
![image](https://user-images.githubusercontent.com/60198231/164448621-4a89b6f9-f2a0-45ca-9dff-e3fd88a31245.png)
Note: If Store credit is not used / other payment mode used for payment, these fields are not retrieved in the response.
Since Store credit is not a payment mode but is an amount that is restored to a customer account, its payment info is not retrieved in the response which is an expected behavior.

Kindly recheck the issue again on Magento 2.4-develop branch with Enterprise edition and provide your inputs on this.
Thank you.

**Comment by webgility-amazonapi** [comment] 2022-04-21 12:26
Thanks you for quick update! 
if you see our screenshot and response of order api from magento we are not getting either node "base_customer_balance_amount" or"customer_balance_amount". 
Please let us know why?

**Comment by webgility-amazonapi** [comment] 2022-04-26 13:28
Hi There, 
Any update for us. our mutual customer is affecting by this **BUG**

**Comment by webgility-amazonapi** [comment] 2022-04-27 11:29
![image](https://user-images.githubusercontent.com/54638813/165508474-7b00bb15-c75a-4d68-99e8-cddacbc4e28d.png)
I think its the enterprise version. because of this store credit is applied on order please refer the screen shot. 
its about the api response where we are not getting the store credit details with order api response.

**Comment by engcom-November** [comment] 2022-05-04 13:38
Hi @webgility-amazonapi ,
Verified this issue on latest 2.4.4 version as well but cannot able to reproduce the issue. Seems like to be an issue in older versions and got fixed. Can you please upgrade your instance to latest version 2.4.4 and recheck again. Please provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by webgility-amazonapi** [comment] 2022-05-13 12:14
Is there any update for us ? Our mutual customers are affected by this.

**Comment by engcom-November** [comment] 2022-05-30 06:20
Hi @webgility-amazonapi ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-05-30 06:20 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
