### ISSUE TITLE
Since Magento 2.3 the wysiwyg images are not loaded anymore from media storage database.

### ISSUE THREAD

**Issue by lpouwelse** [magento/magento2#24442] opened 2019-09-04 10:37 UTC
### Preconditions (*)

1. Magento version 2.3.x

### Steps to reproduce (*)

1. Fresh install of magento with sample data
2. Synchronize media files to datase, according the manual (https://docs.magento.com/m2/ce/user_guide/system/media-storage-database.html)
3. Add following record to core_config_data table 
    - scope: default
    - scope_id: 0 
    - path: web/seo/use_rewrites
    - value: 1
4. Remove an image from media/wysiwyg editor directory
5. Image is not loading anymore from the front-end

### Expected result (*)

1. Image loaded from media database and stored to disk on webserver in media/wysiwyg

### Actual result (*)

1. First of all a 404 error occurs because media/wysiwig is not configured as allowed_resource in Magento_Cms/etc/config.xml media_storage_configuration/allowed_resources/wysiwyg_image_folder
2. File is not loaded correctly from media storage database because it's searching for media/wysiwyg/image.jpg and is stored as wysiwyg/image.jpg

**Comment by lpouwelse** [comment] 2019-09-04 14:36
@engcom-Charlie issues #24442 / #24445 / #24446 are related to each other. Patch already available after confirming the issues (combined pull request.)

**Comment by magento-engcom-team** [comment] 2019-09-05 08:41
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19877` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by manobi** [comment] 2020-04-11 04:41
Hi @lpouwelse, did you mention a patch?
Any tip on how fix this in a 2.3.4 in production?

**Comment by lpouwelse** [comment] 2020-04-13 19:43
@manobi my advice; don't use it. It's poorly implemented. Maybey take a look at glusterfs ore something like that.

**Comment by manobi** [comment] 2020-04-21 02:56
@lpouwelse Thank you, I'll trying something on K8s deployment.

**Comment by novakivskiy** [comment] 2020-04-24 10:16
my attempt to resolve this issue https://github.com/magento/magento2/pull/27967

part of the problem is described here:
https://github.com/magento/magento2/issues/3135

**Comment by nishant04412** [comment] 2023-03-13 11:34
@lpouwelse Is this issue still reproducible on 2.4-develop ? I tried to reproduce it but unfortunately not able to do so on Magento latest versions. Since this issue is very old so wanted to confirm if its still reproducible for you or anyone.

Also, would like to point out that using Database as Media Gallery Storage is Deprecated now so please check accordingly and do let us know your thoughts.

**Comment by engcom-Hotel** [comment] 2023-03-28 11:57
Dear @lpouwelse,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2023-03-28 11:57 UTC
Labels: Issue: Confirmed, Reproduced on 2.3.x, Component: MediaStorage, Reproduced on 2.4.x, Priority: P1, Severity: S1, Progress: done, Area: Admin UI
