### ISSUE TITLE
Quote Item Option info_buyRequest data is NULL, it is only loaded on the cart and checkout page.

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#35548] opened 2022-05-27 16:21 UTC
### Preconditions and environment

- Magento version: 2.4.x

### Steps to reproduce

1. Create a new module that adds new information to `info_buyRequest` `quote_item_option` table when a product is added to the shopping cart, it can be some random data, which is simply stored in the database
2. Add a few items to your shopping cart
3. Create a custom controller and a template where you load checkout session data and a quote
4. In your custom template file, load / get the quote from the quote repository by getting the quote id from the checkout session 
5. Iterate through all quote items and try to display the `info_buyRequest` data in your custom template file

The same thing happens when you load quote Item object by it's repository or resource
```
    $item = $this->itemFactory->create();
    $this->quoteItemResource->load($item, $this->getQuoteItemId());
```

or quote by repository
```
$quote = $this->quoteRepository->get($mainQuoteId);
foreach ($quote->getAllVisibleItems() as $item) {
    $buyRequest = $item->getOptionByCode('info_buyRequest');
    /** 
    buyReuqest is null and does not contain all data which is visible and can be accessed in the shopping cart
    */
}
```

### Expected result

In the template file, `serialized` data of `info_buyRequest` data is displayed

### Actual result

`info_buyRequest` is empty, 
When you go to the shopping cart page and display the same data in the shopping cart, `info_buyRequest` is not empty and it contains all the data.

### Additional information

You can get this data simply by loading itemOption from the database, for example using `collection
```
    $collection = $this->itemOptionCollectionFactory->create();
    $collection->addFieldToFilter('item_id', ['eq' => $itemId]);
    return $collection;
```
and it will load all the data, it does not affect the performance, but forces user to employ a workaround when loading quote / quote items in custom `templates`

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2022-06-08 12:06
Hello @qsolutions-pl,

Thanks for the report and collaboration!

We have tried to reproduce the issue in Magento 2.4-develop branch but the issue is not reproducible for us. We have followed the exact steps mentioned in the main description and we are able to get the value of `info_buyRequest` using `quote by repository`.

Please find attached the module for reference and let us know if we missed anything:
[Magz.zip](https://github.com/magento/magento2/files/8861339/Magz.zip)

Thanks

**Comment by engcom-Hotel** [comment] 2022-06-22 08:43
Dear @qsolutions-pl,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-06-22 08:43 UTC
Labels: Triage: Dev.Experience, Issue: needs update
