### ISSUE TITLE
The $element->getCssClass() call in the backend form/renderer/fieldset/element.phtml template looks like a bug because an element's CSS class should be accessed by $element->getClass() (and my fix)

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2512] opened 2015-11-25 08:34 UTC
https://mage2.pro/t/245

**Comment by palamar** [comment] 2016-06-22 16:37
@mage2pro 
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment] 2016-07-14 08:11
Hi, @mage2pro thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.

**Closed as completed by vzabaznov** 2016-07-14 08:11 UTC
Labels: Progress: needs update
