### ISSUE TITLE
Messages with a-tags not rendered anymore

### ISSUE THREAD

**Issue by pointia** [magento/magento2#28256] opened 2020-05-18 10:11 UTC
Since Magento 2.3.5 messages with anchor tags are escaped by default.
We figured out that issue when following conditions are present:

### Preconditions (*)

1. Magento 2.3.5-p1

### Steps to reproduce (*)

1. Customer Account Confirmation is enabled
2. Customer registers account and does not click on the confirmation link
3. Customer tries to login (account is not confirmed)

### Expected result (*)

1. The message 'This account is not confirmed. <a href="%1">Click here</a> to resend confirmation email.' should be visible with the link to click on.

### Actual result (*)

1. Message is escaped and link is not clickable

I did a quick fix by patching the magento/framework with the following patch file, but I'm sure this is not the right way.

```
--- View/Element/Message/Renderer/EscapeRenderer.php	(date 1589796307521)
+++ View/Element/Message/Renderer/EscapeRenderer.php	(date 1589796307521)
@@ -38,6 +38,6 @@
      */
     public function render(MessageInterface $message, array $initializationData)
     {
-        return $this->escaper->escapeHtml($message->getText());
+        return $this->escaper->escapeHtml($message->getText(),['a']);
     }
 }

```

**Comment by ajijshekh123** [comment] 2020-05-18 10:20
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-18 10:20
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-05-18 10:21
Hi @ajijshekh123, here is your [Magento instance](https://i-28256-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28256-2-4-develop.instances.magento-community.engineering/admin_c8bd](https://i-28256-2-4-develop.instances.magento-community.engineering/admin_c8bd)
Login: `76fbb3f8` Password: `aeb425da5049`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2020-05-18 10:32
Hello @pointia,
I have verified this issue in the latest Magento 2.4 Instance. I am not able to reproduce this issue.
"'This account is not confirmed. Click here to resend confirmation email." link is visible and Once user clicks on the "Click here" link, It is working properly.

See attached the video:

![Untitled_ May 18, 2020 3_56 PM](https://user-images.githubusercontent.com/24711761/82203411-e8aee280-9920-11ea-9787-9fe6c78d314a.gif)

Thanks.

**Comment by pointia** [comment] 2020-05-18 11:01
@ajijshekh123 Thanks for verification and I've checked the code from 2.4.

This issue was fixed 19 days ago by https://github.com/magento/magento2/pull/27662. 

Does this fix get backported to 2.3.5+ ?

**Comment by ajijshekh123** [comment] 2020-05-19 05:04
Okay, @pointia.

**Comment by magento-engcom-team** [comment] 2020-05-19 05:05
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34406` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment] 2020-06-24 17:12
Hello @pointia and @ajijshekh123 

I can confirm that issue has been fixed and ported to 2.3.5
The fix will be available with the next release of 2.3.5-p2 version

**Comment by magento-engcom-team** [comment] 2020-06-24 17:12
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-34406).

**Comment by magento-engcom-team** [comment] 2020-06-24 17:13
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-34406).

**Closed as completed by sdzhepa** 2020-06-24 17:12 UTC
Labels: Issue: Ready for Work, Component: Customer, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Login, Reproduced on 2.3.5p1, Reported on 2.3.5-p1

**Comment by magento-engcom-team** [comment] 2020-06-24 17:13
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-34406).

**Comment by magento-engcom-team** [comment] 2020-06-24 17:14
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-34406).

**Comment by magento-engcom-team** [comment] 2020-06-24 17:14
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-34406).

**Comment by magento-engcom-team** [comment] 2020-06-24 17:15
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-34406).
