### ISSUE TITLE
In-Store delivery: Unable to place order via PayPal through Braintree (by Gene)

### ISSUE THREAD

**Issue by ghost** [magento/magento2#34574] opened 2021-11-08 11:44 UTC
The issue is reproduced on Magento **CE/EE v2.4.3**
### Preconditions (*)

1. In-Store Delivery is enabled
2. Google Distance Provider is configured
3. Several sources with assigned stock are created and there:
- Use as Pickup Location  = Yes
4. PayPal through Braintree is enabled
5. Several items are created and assigned to the created sources

### Steps to reproduce (*)

1. Go to the Storefront as a guest
2. Add created products to the Cart
3. Go to Checkout
4. Select the " Pick in Store" shipping method
5. Fill in the email address
6. Select the store
7. Go to the **_Review & Payments_** page
8. Select "PayPal" as a payment method
9. Try to place an order

### Expected result (*)

The order has been created successfully

### Actual result (*)

1. Store's address is displayed on the Paypal popup
2. Error appears in the billing tab on the Checkout page

![unknown](https://user-images.githubusercontent.com/93907597/140736148-7eaee037-2000-4f6b-8f91-1d3961237d65.png)
![unknown2](https://user-images.githubusercontent.com/93907597/140736288-24f94fb9-9300-4b8d-b7a4-85588d964fde.png)

**Comment by engcom-November** [comment] 2021-12-01 13:31
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2021-12-02 06:07
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue.
Steps performed:
Installed and enabled Inventory module
Configured Braintree payment method
Enabled in store delivery
Front-end - Go to Checkout - Select the " Pick in Store" shipping method - Review & Payments page
Select "PayPal" as a payment method - Place Order - No issue.
@laminatinkaa kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2021-12-16 13:02
Hi @laminatinkaa ,

We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-12-16 13:02 UTC
Labels: Issue: needs update

**Comment by megha-as** [comment] 2023-11-24 12:53
This issue is reproducible with guest user. For loggedin user it's working fine
