### ISSUE TITLE
collection getSize doesn't work properly with plugins

### ISSUE THREAD

**Issue by ghost** [magento/magento2#9195] opened 2017-04-10 18:12 UTC
### Preconditions

1. Magento 2.1.5
2. PHP 7 MySQL 5.6.35

### Steps to reproduce

1. Create a dependency injection on a product collection as here http://magento.stackexchange.com/questions/164574/collection-addattributetofilter-works-if-cache-disabled-but-not-if-enabled
2. view the results on the category page
3. The pagination and total count of products is wrong but it shows the right products

### Expected result

1. The pagination and total amount of products returned should reflect the actual sql returned after the plugin

### Actual result

1. https://i.gyazo.com/0c90b7bcaced2de588ee68066bfdb591.png
As you can see there isn't 406 items but one

Commenting out these lines in framework/Data/Collection/AbstractDb.php makes it work:
https://i.gyazo.com/1ffcab817aea8bf89c54e6d59cbd06e5.png

Others have reported many times in magento stack exchange of collection size and toolbar count and pagination not matching so this is a very common issue.

**Comment by magento-engcom-team** [comment] 2017-10-23 13:30
@atrixtech, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-23 13:30 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
