### ISSUE TITLE
...

### ISSUE THREAD

**Issue by agata-maksymiuk** [magento/magento2#39443] opened 2024-12-05 12:54 UTC

**Comment by agata-maksymiuk** [comment] 2024-12-05 13:45
Checked again, I am unable to reproduce on 2.4.7 now.

**Comment by engcom-Bravo** [comment] 2024-12-06 04:06
Hi @agata-maksymiuk,

Thanks for your reporting and collaboration.

Since the issue is no more reproducible we are closing this issue.Please feel free to reopen the issue if the issue still persists.

Thanks.

**Closed as completed by engcom-Bravo** 2024-12-06 04:06 UTC
Labels: Issue: ready for confirmation, Reported on 2.4.7
