### ISSUE TITLE
MAGE_PROFILER =  'firebug' error

### ISSUE THREAD

**Issue by webmak** [magento/magento2#7068] opened 2016-10-18 08:53 UTC
**Preconditions**

1) php 7.0.9, php-fpm, apache
2) Magento CE 2.1.2 the same was in Magento CE2.1.1 not tested before

**Steps to reproduce**

1) turn on profile env MAGE_PROFILER = 'firebug';
2) reload php-fpm
3) reload site page

**Expected result**

Profiling info

**Actual result**

Uncaught TypeError: Argument 1 passed to Zend_Controller_Plugin_Abstract::setResponse() must be an instance of Zend_Controller_Response_Abstract, instance of Magento\Framework\HTTP\PhpEnvironment\Response given, called in /home/user/public_html/some.site/www/vendor/magento/framework/Profiler/Driver/Standard/Output/Firebug.php on line 61 and defined in /home/user/public_html/some.site/www/vendor/magento/zendframework1/library/Zend/Controller/Plugin/Abstract.php:70 Stack trace: #0 /home/user/public_html/some.site/www/vendor/magento/framework/Profiler/Driver/Standard/Output/Firebug.php(61): Zend_Controller_Plugin_Abstract->setResponse(Object(Magento\Framework\HTTP\PhpEnvironment\Response)) #1 /home/user/public_html/some.site/www/vendor/magento/framework/Profiler/Driver/Standard.php(195): Magento\Framework\Profiler\Driver\Standard\Output\Firebug->display(Object(Magento\Framework\Profiler\Driver\Standard\Stat)) #2 [internal function]: Magento\Framework\Profiler\Driver\Standard->display() #3 {main} thrown in /home/user/public_html/some.site/www/vendor/magento/zendframework1/library/Zend/Controller/Plugin/Abstract.php on line 70

**After checking**

Was detected that passing object has this parents types 

`array(4) { ["Zend\Http\PhpEnvironment\Response"]=> string(33) "Zend\Http\PhpEnvironment\Response" ["Zend\Http\Response"]=> string(18) "Zend\Http\Response" ["Zend\Http\AbstractMessage"]=> string(25) "Zend\Http\AbstractMessage" ["Zend\Stdlib\Message"]=> string(19) "Zend\Stdlib\Message" }`

But method aspect other type
`setResponse(Zend_Controller_Response_Abstract $response) { $this->_response = $response; return $this; }`

**Comment by webmak** [comment] 2016-10-18 09:17
Passing object is child of Zend_Controller_Request_Abstract

**Comment by webmak** [comment] 2016-10-18 09:20
Passing object has this parents types array(4) { ["Zend\Http\PhpEnvironment\Response"]=> string(33) "Zend\Http\PhpEnvironment\Response" ["Zend\Http\Response"]=> string(18) "Zend\Http\Response" ["Zend\Http\AbstractMessage"]=> string(25) "Zend\Http\AbstractMessage" ["Zend\Stdlib\Message"]=> string(19) "Zend\Stdlib\Message" }

**Comment by webmak** [comment] 2016-10-18 09:26
`public function setResponse(Zend_Controller_Response_Abstract $response)
    {
        $this->_response = $response;
        return $this;
    }`
but this function aspected other type

**Comment by veloraven** [comment] 2016-10-19 11:09
@webmak thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by webmak** [comment] 2016-10-19 14:33
To get this bug you need to set env MAGE_PROFILER = 'firebug' and you will got it

**Comment by webmak** [comment] 2016-10-19 17:42
Have update issue

**Comment by sevos1984** [comment] 2016-11-02 17:01
Thanks for reporting, internal ticket created MAGETWO-60429

**Comment by markoweb** [comment] 2017-01-25 12:15
The same problem

**Comment by orlangur** [comment] 2017-07-12 17:16
Due to `Zend_Wildfire` deprecation this issue was fixed in `develop` via corresponding profiler mode removal in https://github.com/magento/magento2/pull/9622. It no more works in latest Firefox thus I don't think it's worth fixing in 2.1.x.

Ping @veloraven @sevos1984

**Comment by magento-engcom-team** [comment] 2017-09-21 14:14
@webmak Closing this issue as this deprecated feature is removed since 2.2 (see PR https://github.com/magento/magento2/pull/9622 for more information)

**Closed as completed by magento-engcom-team** 2017-09-21 14:14 UTC
Labels: Issue: Ready for Work, bug report, Issue: Format is valid
