### ISSUE TITLE
SEO/HEAD - Meta title is null when breadcrumb section is removed via XML

### ISSUE THREAD

**Issue by mstumpf818** [magento/magento2#4427] opened 2016-05-07 19:13 UTC
## Steps to reproduce
1. Install Magento 2.0.2
2. Add 
   `<referenceBlock name="breadcrumbs" remove="true"/>` to app/design/frontend/[VendorName]/[ThemeName]/Magento_Theme/layout/default.xml
## Expected result
1. Breadcrumb section should be removed from all pages
## Actual result
1. Meta title in <head> disappears with breadcrumb section.  Meta title prefix and suffix (set in the admin panel) still appear.
2. addConfigValues() title is null in vendor/magento/framework/View/Page/Title.php

**Comment by slackerzz** [comment] 2016-12-05 11:10
this bug is still present in M2 2.1.2 (both CE & EE)

**Comment by magento-team** [comment] 2017-07-31 22:48
Internal ticket to track issue progress: MAGETWO-67614

**Comment by magento-engcom-team** [comment] 2017-10-01 11:37
Hi @mstumpf818 
Looks like the issue is already fixed in `2.1.8` with the PR magento/magento2#9324.
Closing this ticket for now. Please reopen if issue persists.

**Closed as completed by magento-engcom-team** 2017-10-01 11:37 UTC
Labels: Issue: Ready for Work, bug report, Area: Frontend, Issue: Format is not valid

**Comment by realchriswells** [comment] 2020-08-06 10:16
Bit of an old ticket, but I'm having the same thing happen in 2.3.4.
