### ISSUE TITLE
Compare Function stop working for not salable products (magento 2.3.2)

### ISSUE THREAD

**Issue by toxix** [magento/magento2#24555] opened 2019-09-11 12:55 UTC
### Preconditions (*)
Magento 2.3.2 upgraded from Magento 2.3.1.

### Steps to reproduce (*)
1. Having a product that is visible in the product catalog but not salable
2. Add the product to the compare list with a post request to catalog/product_compare/add/ controller.

### Expected result (*)
Behavior in Magento 2.3.1:
1. The product is added to the compare list
2. Page got reloadad and shows the product added to the compare list.

### Actual result (*)
Behavior in Magento 2.3.2
1. Product is not added to the compare list.
2. Page from where the request is send is reloaded without any error message.

### Findings

- No hints in the release notes of magento 2.3.2
-https://github.com/magento/magento2/commit/375a36d6e50531c5266dc5be9cc845cbd666a855
   The commit message is cryptic and not very helpfull. As far as I can see, this change also introduced the issue that a product that got unsalable while it is in the compare list cannot be removed.
- In the default template the link to the add to compare list controller is only visible if the product isSalable.
- Why is does the product needs to be salable at all to be added to the compare list? Suggestion would be either to determine it on the visibility or add a seperate attribute to control the behavior.

**Comment by magento-engcom-team** [comment] 2019-09-11 13:11
@sudheers-kensium Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-09-11 13:11
@sudheers-kensium Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-09-11 13:12
@shikhamis11 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-09-11 13:13
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20115` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by toxix** [comment] 2019-09-16 13:57
Hey @sudheers-kensium ,

Thx for your fast fix. This only fixes the adding of product but removing an not salable product will remain bugy. Can you do the same fix, also in the app/code/Magento/Catalog/Controller/Product/Compare/Remove.php ? See also the changes that has been introduced this bug: https://github.com/magento/magento2/commit/375a36d6e50531c5266dc5be9cc845cbd666a855#diff-3d707963768b919bbd05a1e5ffe11df9R34

**Comment by sudheers-kensium** [comment] 2019-09-16 14:05
Hello @toxix I have created new ticket and PR to remove compare products issue #24582 and PR #24583 .

**Comment by MaxSouza** [comment] 2019-09-16 19:46
@sudheers-kensium Please, take a look at #24620

**Comment by toxix** [comment] 2019-10-02 08:47
Hey,

Thx for working on this. I think if the two PR #24568 and #24729 are approved and merged this bug looks like it's solved by them in combination. In the way they are implemented there. Let's keep this open untill the PR are merged.

**Comment by toxix** [comment] 2019-11-06 10:16
Can we push this somehow? PR are there but they are not merged.

**Comment by magento-engcom-team** [comment] 2019-11-14 16:34
Hi @toxix, @sudheers-kensium. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-20115` was closed as `non-reproducible` in `2.3-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

### Additional information

Related internal Jira ticket `MC-20115` was closed because the issue has been already fixed and delivered in the scope of  [`MC-15930`](https://github.com/magento/magento2/search?q=MC-15930&type=Commits)
- https://github.com/magento/magento2/commit/c75e923887f687ae88c859ddce6d82dfee402860

**Closed as completed by magento-engcom-team** 2019-11-14 16:34 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Issue:  Cannot Reproduce, Issue: Format is valid
