### ISSUE TITLE
Modals cannot be closed by clicking on the overlay

### ISSUE THREAD

**Issue by ntoombs19** [magento/magento2#7460] opened 2016-11-16 21:36 UTC
### Preconditions

1. Magento version: 2.1.1
2. Browser: Chrome
3. OS: OS X El Capitan 10.11.6

### Steps to reproduce

1. Sign in as a customer
2. Add some products to your cart
3. Go to checkout
4. Click the + New Address button ![](http://take.ms/E6S5x)
5. With the modal open, click anywhere in the dark grey background (the overlay)

### Expected result

1. The modal should close. This is the modals default behavior unless it is explicitly overridden on initialization, which it isn't anywhere in the code base. 

http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/widgets/widget_modal.html#modal_clickableOverlay

### Actual result

1. Nothing happens. There are no error messages in the console either.

**Comment by ntoombs19** [comment] 2016-12-09 15:56
I just noticed this is actually a duplicate of https://github.com/magento/magento2/issues/7399

**Comment by erikhansen** [comment] 2017-01-07 18:36
@ntoombs19 Can you close your ticket since it's a duplicate of #7399? I posted a workaround for this issue on #7399.

**Comment by miakusha** [comment] 2017-01-20 12:00
Hi @ntoombs19 thanks for report
We've created internal ticket MAGETWO-63410 to address this issue.
I’m closing this issue because it is a duplicate #7399.

**Closed as completed by miakusha** 2017-01-20 12:00 UTC
Labels: bug report, Component: Checkout
