### ISSUE TITLE
Missaligned fields on the Customer Login form

### ISSUE THREAD

**Issue by gjportegies** [magento/magento2#28059] opened 2020-04-30 09:57 UTC
### Preconditions (*)

1. Magento CE 2.3.5-p1 vanilla without sample data is installed.
2. Magento Blank Theme is used.
3. Screen/Browser width >= 768px.

### Steps to reproduce (*)

1. Login to the admin panel.
2. Navigate to the Content -> Design -> Configuration.
3. Open the Global Store and set the applied theme to 'Magento Blank'.
4. Clean the cache(s).
5. Open the storefront and navigate to the 'Sign In' page (/customer/account/login/)
6. See the input fields on the Customer Login form are not stroking with the design of all other forms on the default Blank Theme.

### Expected result (*)

The input fields on the form should be inline with the labels (Like all other forms in the Blank Theme).

| Expected Result |
| ------------- |
| ![Schermafbeelding 2020-04-30 om 11 41 36](https://user-images.githubusercontent.com/6707410/80696688-0d5d2a80-8ad8-11ea-8ab0-5b0ce6c6c99f.png)  |

### Actual result (*)

The input fields are shown below the labels and not aligned.

| Actual Result |
| ------------- |
| ![Schermafbeelding 2020-04-30 om 11 48 50](https://user-images.githubusercontent.com/6707410/80697002-996f5200-8ad8-11ea-9191-f0fd32be1e70.png) |

### Additional information
On the Magento 2.4-develop instance the issue looks fixed. But this is not stroking with the styling of all the other form fields design of the Magento Blank theme.

| Result on 2.4-develop |
| ------------- |
| ![Schermafbeelding 2020-04-30 om 12 00 23](https://user-images.githubusercontent.com/6707410/80698104-4dbda800-8ada-11ea-802b-bf50adf68787.png) |

On the Magento 2.3.5-p1 the issue is probably caused by the following css line:

![Schermafbeelding 2020-04-30 om 12 02 45](https://user-images.githubusercontent.com/6707410/80698318-a0975f80-8ada-11ea-809b-07700daa85bb.png)

**Comment by krishprakash** [comment] 2020-04-30 12:47
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-30 12:47
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-30 12:49
Hi @krishprakash, here is your [Magento instance](https://i-28059-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28059-2-4-develop.instances.magento-community.engineering/admin_dbce](https://i-28059-2-4-develop.instances.magento-community.engineering/admin_dbce)
Login: `053601f6` Password: `5c9703584465`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2020-05-04 06:24
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33937` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment] 2020-05-06 16:23
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-06 16:23
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-05-06 16:25
Hi @sdzhepa, here is your [Magento instance](https://i-28059-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28059-2-4-develop.instances.magento-community.engineering/admin_b143](https://i-28059-2-4-develop.instances.magento-community.engineering/admin_b143)
Login: `b508383e` Password: `0338fa230159`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment] 2020-05-06 16:40
Hello @mrtuvn 
fyi: @krishprakash

I cannot reproduce this issue using steps from precondition on the latest `2.4-develop` branch
Probably it was already fixed and we can close this issue
or some steps/preconditions are missed

**Luma: 768x1024 and 1024x768**
![LUMA_28059](https://user-images.githubusercontent.com/3409584/81204092-5dcc0080-8f8e-11ea-8667-b18705bdf2c2.png)


**Blank: 768x1024 and 1024x768**
![Blank_28059](https://user-images.githubusercontent.com/3409584/81204126-691f2c00-8f8e-11ea-9f5d-c205ed0ecbaa.png)

**Comment by gjportegies** [comment] 2020-05-07 08:10
@sdzhepa did you read my comment on the additional information? 

> On the Magento 2.4-develop instance the issue looks fixed. But this is not stroking with the styling of all the other form fields design of the Magento Blank theme.

**Comment by slavvka** [comment] 2020-05-21 06:17
Hi @gjportegies. Thank you for your report. 
The issue has been fixed in magento/magento2#28084 by @mrtuvn in 2.4-develop branch
Related commit(s):
 - [d7cf1881141fd855ff79f611a31ea2570726bdc3](https://github.com/magento/magento2/commit/d7cf1881141fd855ff79f611a31ea2570726bdc3)
 - [77a4e8c44e1ee901d77aa8d6680fcd5365cd376d](https://github.com/magento/magento2/commit/77a4e8c44e1ee901d77aa8d6680fcd5365cd376d)
 - [6b8fc4c55272229164fde82ddbd631f771f302d7](https://github.com/magento/magento2/commit/6b8fc4c55272229164fde82ddbd631f771f302d7)
 - [facbe37f9f51eb315bc5da1fb3c5000d743057ff](https://github.com/magento/magento2/commit/facbe37f9f51eb315bc5da1fb3c5000d743057ff)
 - [1ef8a517089ff132a7bb526194999ae83247ce50](https://github.com/magento/magento2/commit/1ef8a517089ff132a7bb526194999ae83247ce50)
 - [6e8190662497a8e248c05d92b8763886637be5f3](https://github.com/magento/magento2/commit/6e8190662497a8e248c05d92b8763886637be5f3)
 - [03a2908769ad60c5cd5b1a5262aeab092417fe6a](https://github.com/magento/magento2/commit/03a2908769ad60c5cd5b1a5262aeab092417fe6a)
 - [8c0eff01d09dbea47a3af3afbd0f75bae2a89c82](https://github.com/magento/magento2/commit/8c0eff01d09dbea47a3af3afbd0f75bae2a89c82)
 - [0e84ed4214d5a7bafdabf99dcaa45e2f54bdac41](https://github.com/magento/magento2/commit/0e84ed4214d5a7bafdabf99dcaa45e2f54bdac41)
 - [63550be4ba9097cb1ceac4cc787632d330ec0ea1](https://github.com/magento/magento2/commit/63550be4ba9097cb1ceac4cc787632d330ec0ea1)
 - [e3975c6b6461c0b1e1bce318cae04f4622f17bd7](https://github.com/magento/magento2/commit/e3975c6b6461c0b1e1bce318cae04f4622f17bd7)
 - [d68fa5d45b66754801e65b440d1338463396ad9f](https://github.com/magento/magento2/commit/d68fa5d45b66754801e65b440d1338463396ad9f)
 - [63552f8538347bb4c21339be0100f6bda72c9d60](https://github.com/magento/magento2/commit/63552f8538347bb4c21339be0100f6bda72c9d60)
 - [80c6ba7ec4ea21ef19bde70edb2477a5717a84cb](https://github.com/magento/magento2/commit/80c6ba7ec4ea21ef19bde70edb2477a5717a84cb)

The fix will be available with the upcoming 2.4.0 release.

**Closed as completed by slavvka** 2020-05-21 06:17 UTC
Labels: Issue: Ready for Work, Component: Customer, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Reproduced on 2.4.x, Fixed in 2.4.x, Severity: S4, Priority: P4, Triage: Done, Progress: done, Reported on 2.3.5-p1
