### ISSUE TITLE
Magento 2 refund order via API status does not change to Closed

### ISSUE THREAD

**Issue by lano-vargas** [magento/magento2#26456] opened 2020-01-20 11:10 UTC
### Preconditions (*)

1. Have magento2.2.2 installed 
2. Keep all default payments config  etc... such as `Check / Money order`

### Steps to reproduce (*)

1. Add a configurable and at least 1 simple to `configurations`
2. Go to frontend add at least one product to cart and checkout finalise purchase.
3. Go to backend and Invoice + Ship the item and the status will be set to `Complete`.
4. Now using your favourite API tool use `salesRefundOrderV1` from documentation found here: https://devdocs.magento.com/swagger/#/salesRefundOrderV1 . Request order refund input necessary details from the order like so E.G:

`POST http://dev.test/rest/V1/order/1/refund`

**Body:**
`{
  "items": [
    {
      "extension_attributes": {},
      "order_item_id": 1,
      "qty": 1
    }
  ],
  "notify": true,
  "appendComment": true,
  "comment": {
    "extension_attributes": {},
    "comment": "string",
    "is_visible_on_front": 0
  },
  "arguments": {
    "shipping_amount": 0,
    "adjustment_positive": 0,
    "adjustment_negative": 0,
    "extension_attributes": {
      "return_to_stock_items": [
        0
      ]
    }
  }
}`

5. If success you should receive refund ID E.G: `"1"`
6. Go to backend->Sales->Order check the order you've just refunded in `information`  Order Status still says: `Complete`

### Expected result (*)

1. Order Status should be `Closed`

### Actual result (*)

1. Order Status still be `Complete`.

**Comment by engcom-Charlie** [comment] 2020-01-21 11:15
Hi @lano-vargas thank you for your report, but we are not able to reproduce this issue on a fresh 2.4-develop instance and 2.3.3 release.

**Manual testing scenario**:
1. Add a configurable and at least 1 simple to configurations
2. Go to frontend add at least one product to cart and checkout and place an order.
3. Go to backend and make Invoice + Ship the item and the status will be set to Complete.
4. Now using your favorite API tool use salesRefundOrderV1 from documentation found here: https://devdocs.magento.com/swagger/#/salesRefundOrderV1 .
5. Go to backend->sales->order.
6. Check the Status order you've just refunded.
**Actual result** : Order status is _Closed_

Could you take a look?

**Comment by lano-vargas** [comment] 2020-01-22 10:18
@engcom-Charlie Thanks for looking!

The version this issue is on 2.2.2 you've tested it on 2.3.3 and 2.4-develop which probably have been fixed. Is this a bug on 2.2.2 version then?

Thanks

**Comment by engcom-Charlie** [comment] 2020-01-22 12:05
Hello, @lano-vargas.

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the latest 2.4-develop branch by provided steps.

We are closing this issue due to branch `2.2-develop` was closed and
> Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.

 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

Thanks for your report!

**Closed as completed by engcom-Charlie** 2020-01-22 12:05 UTC
Labels: Progress: needs update, Component: Sales, Issue: Format is valid, Component: Api, Reported on 2.2.x
