### ISSUE TITLE
DHL "Enable Free Shipping Threshold" not working

### ISSUE THREAD

**Issue by DanielIconate** [magento/magento2#31190] opened 2020-12-07 14:11 UTC
### Preconditions (*)

1. Magento version 2.3.2
2. Apache server PHP 7.2
3. Reproducible on the latest 2.4-develop

### Steps to reproduce (*)

1. Enable DHL Shipping and Configure necessary Information
2. Set "Free Method", "Enable Free Shipping Threshold" and "Free Shipping Amount Threshold" for Default DHL Magento Shipping Method under Configuration->Sales->Shipping Methods

### Expected result (*)

1. 
![Bildschirmfoto 2020-12-07 um 15 02 12](https://user-images.githubusercontent.com/62563245/101359914-311df580-389d-11eb-9b02-afcf6426d769.png)
2. Expect that the Shipping in Frontend will be free after the Amount of the set threshold is reached

### Actual result (*)

1. Nothing changes
2. The Shipping is the same when the threshold is reached. 
3. <img width="1153" alt="Bildschirmfoto 2020-12-07 um 15 07 39" src="https://user-images.githubusercontent.com/62563245/101360821-77c01f80-389e-11eb-8023-c5962939621e.png">

### Additional info
See https://github.com/magento/magento2/issues/31190#issuecomment-740523601 with steps to reproduce
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Pavel-Fekete** [comment] 2020-12-08 10:10
The issue is reproducible on the latest Magento 2.4-develop

**Steps to reproduce:**

1.  Enable DHL Shipping and Configure necessary Information
![DHL enable](https://user-images.githubusercontent.com/67371013/101468576-4736bf00-394c-11eb-80e1-e683a38eee12.png)
2. Set "Free Method", "Enable Free Shipping Threshold" and "Free Shipping Amount Threshold" for Default DHL Magento Shipping Method under Configuration->Sales->Shipping Methods
![2](https://user-images.githubusercontent.com/67371013/101468791-8f55e180-394c-11eb-9bb2-1d359c442030.png)
3. Proceed to checkout on store (amount of the set threshold is reached) and verify the Shipping

**Expected result:**
The Shipping in Frontend will be free after the Amount of the set threshold is reached

**Actual result:**
1. Nothing changes
2. The Shipping is the same when the threshold is reached.
![3](https://user-images.githubusercontent.com/67371013/101470107-3edf8380-394e-11eb-9205-5717da897b83.png)

**Comment by magento-engcom-team** [comment] 2020-12-10 11:11
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39814` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by yvaliya** [comment] 2021-01-16 15:51
@magento give me 2.4-develop instance

**Comment by yvaliya** [comment] 2021-01-16 16:21
For me, it just worked fine for Magento 2.4-develope instance.

![back-end configuration](https://i.imgur.com/PBBHzEI.png)

![front-end result](https://i.imgur.com/r1WGi2l.png)

DHL will allow free shipping only with the method that is selected as a free shipping method from the configuration. For other shipping methods normal shipping charge will be applied.

@DanielIconate you configured "Easy Shop" as a free shipping method and on the frontend, you are seeing the shipping price of the "Domestic Express" method ("Easy Shop" is simply not available in your case). If you want to allow free shipping for "Domestic Express" then please select it as a free shipping method and it should work.

@Pavel-Fekete seems like you are making the same configuration mistake as @DanielIconate.

**Comment by yvaliya** [comment] 2021-01-16 16:27
@magento add to contributors team

**Comment by yvaliya** [comment] 2021-01-16 16:28
@magento I am working on this

**Comment by yvaliya** [comment] 2021-01-16 16:30
For me, it just worked fine for Magento 2.4-develope instance.

![back-end configuration](https://i.imgur.com/PBBHzEI.png)

![front-end result](https://i.imgur.com/r1WGi2l.png)

DHL will allow free shipping only with the method that is selected as a free shipping method from the configuration. For other shipping methods normal shipping charge will be applied.

@DanielIconate you configured "Easy Shop" as a free shipping method and on the frontend, you are seeing the shipping price of the "Domestic Express" method ("Easy Shop" is simply not available in your case). If you want to allow free shipping for "Domestic Express" then please select it as a free shipping method and it should work.

@Pavel-Fekete seems like you are making the same configuration mistake as @DanielIconate.

**Comment by yvaliya** [comment] 2021-01-16 16:31
@magento add to contributors team

**Comment by yvaliya** [comment] 2021-01-22 06:56
@magento You can close this issue as it's invalid

**Comment by DanielIconate** [comment] 2021-01-22 09:07
@yvaliya 

Hi, Thank you for your reply, i choosed the method as free shipping method but it in the frontend it shows a slightly different one so maybe that's the case.

example: in the backend, you can only choose "Domestic express 12:00" but in the frontend it shows "Domestic express"

![Bildschirmfoto 2021-01-22 um 09 57 16](https://user-images.githubusercontent.com/62563245/105470208-8e2d0980-5c99-11eb-8e46-ee3972639ccc.png)

![Bildschirmfoto 2021-01-22 um 09 57 05](https://user-images.githubusercontent.com/62563245/105470252-9f761600-5c99-11eb-9b78-a5bc7316113d.png)

**Comment by yvaliya** [comment] 2021-01-24 07:06
@DanielIconate "Domestic express 12:00" and "Domestic express" aren't the same methods. Please check the DHL config and set "Domestic express" as a free shipping method or share your full DHL configuration snapshots so that I can help.

**Comment by sdzhepa** [comment] 2021-02-03 19:32
Hello @DanielIconate @yvaliya 

Thank you for contributing and collaborating!

Based on comments and especially the last one https://github.com/magento/magento2/issues/31190#issuecomment-766303142
It is not a bug in Magento code but a configuration issue related to DHL.

The issue can be closed

**Closed as completed by sdzhepa** 2021-02-03 19:32 UTC
Labels: Issue: Clear Description, Issue: Confirmed, non-issue, Component: Dhl, Priority: P2, Severity: S2, Progress: done, Issue: ready for confirmation, Reported on 2.3.2
