### ISSUE TITLE
Image size for Product Watermarks [Magento 2.1.0]

### ISSUE THREAD

**Issue by RG-1** [magento/magento2#5270] opened 2016-06-26 19:35 UTC
## Steps to reproduce
1. Magento 2.1.0 
2. Go to Content > Design: Configuration 
3. Edit any store view 
4. Go to "Product Image Watermarks" tab 
5. Try to enter "Image Size" (e.g. 200x300) 
## Expected result 
1. Field allows to enter digits and "x" as in the example. 
## Actual result 
1. Field allows to enter only digits.

![watermark](https://cloud.githubusercontent.com/assets/17853402/16364305/00427518-3be4-11e6-8fdf-8d464b98168b.png)

**Comment by antboiko** [comment] 2016-06-27 08:31
Hi @RG-1 , thanks for reporting. We've created internal ticket MAGETWO-54779 to fix this issue.

Best,
Anton.

**Comment by gabriel-sf** [comment] 2016-09-16 12:16
Hi guys, 
is there any update or patch we can apply to fix this on M2.1?
Thanks,
Gab

**Comment by comsatnet** [comment] 2016-09-26 21:22
Hi guys,

as this is still not fixed in M2.1.1 there is a temporary solution how to enter the correct "Image Size" in the full format (e.g. 200x300)

1) Go to your database with either phpmyadmin 
    or cli -> "mysql -u database_user -p database_name"

2) look for "core_config_data" table 

and find the following PATH:

design/watermark/image_size
design/watermark/small_image_size
design/watermark/swatch_image_size
design/watermark/thumbnail_size

3) set the VALUE manualy  e.g. -> 200x300

**Comment by comsatnet** [comment] 2016-09-26 21:22
Hi guys,

as this is still not fixed in M2.1.1 there is a temporary solution how to enter the correct "Image Size" in the full format (e.g. 200x300)

1) Go to your database with either phpmyadmin 
    or cli -> "mysql -u database_user -p database_name"

2) look for "core_config_data" table 

and find the following PATH:

design/watermark/image_size
design/watermark/small_image_size
design/watermark/swatch_image_size
design/watermark/thumbnail_size

3) set the VALUE manualy  e.g. -> 200x300

**Comment by comsatnet** [comment] 2016-09-26 21:22
Hi guys,

as this is still not fixed in M2.1.1 there is a temporary solution how to enter the correct "Image Size" in the full format (e.g. 200x300)

1) Go to your database with either phpmyadmin 
    or cli -> "mysql -u database_user -p database_name"

2) look for "core_config_data" table 

and find the following PATH:

design/watermark/image_size
design/watermark/small_image_size
design/watermark/swatch_image_size
design/watermark/thumbnail_size

3) set the VALUE manualy  e.g. -> 200x300

**Comment by comsatnet** [comment] 2016-09-26 21:22
Hi guys,

as this is still not fixed in M2.1.1 there is a temporary solution how to enter the correct "Image Size" in the full format (e.g. 200x300)

1) Go to your database with either phpmyadmin 
    or cli -> "mysql -u database_user -p database_name"

2) look for "core_config_data" table 

and find the following PATH:

design/watermark/image_size
design/watermark/small_image_size
design/watermark/swatch_image_size
design/watermark/thumbnail_size

3) set the VALUE manualy  e.g. -> 200x300

**Comment by comsatnet** [comment] 2016-09-26 21:22
Hi guys,

as this is still not fixed in M2.1.1 there is a temporary solution how to enter the correct "Image Size" in the full format (e.g. 200x300)

1) Go to your database with either phpmyadmin 
    or cli -> "mysql -u database_user -p database_name"

2) look for "core_config_data" table 

and find the following PATH:

design/watermark/image_size
design/watermark/small_image_size
design/watermark/swatch_image_size
design/watermark/thumbnail_size

3) set the VALUE manualy  e.g. -> 200x300

**Comment by comsatnet** [comment] 2016-09-26 21:22
Hi guys,

as this is still not fixed in M2.1.1 there is a temporary solution how to enter the correct "Image Size" in the full format (e.g. 200x300)

1) Go to your database with either phpmyadmin 
    or cli -> "mysql -u database_user -p database_name"

2) look for "core_config_data" table 

and find the following PATH:

design/watermark/image_size
design/watermark/small_image_size
design/watermark/swatch_image_size
design/watermark/thumbnail_size

3) set the VALUE manualy  e.g. -> 200x300

**Comment by comsatnet** [comment] 2016-09-26 21:22
Hi guys,

as this is still not fixed in M2.1.1 there is a temporary solution how to enter the correct "Image Size" in the full format (e.g. 200x300)

1) Go to your database with either phpmyadmin 
    or cli -> "mysql -u database_user -p database_name"

2) look for "core_config_data" table 

and find the following PATH:

design/watermark/image_size
design/watermark/small_image_size
design/watermark/swatch_image_size
design/watermark/thumbnail_size

3) set the VALUE manualy  e.g. -> 200x300

**Comment by comsatnet** [comment] 2016-09-26 21:22
Hi guys,

as this is still not fixed in M2.1.1 there is a temporary solution how to enter the correct "Image Size" in the full format (e.g. 200x300)

1) Go to your database with either phpmyadmin 
    or cli -> "mysql -u database_user -p database_name"

2) look for "core_config_data" table 

and find the following PATH:

design/watermark/image_size
design/watermark/small_image_size
design/watermark/swatch_image_size
design/watermark/thumbnail_size

3) set the VALUE manualy  e.g. -> 200x300

**Comment by branouk** [comment] 2016-09-26 21:44
Hi guys,

as this is still not fixed in M2.1.1 there is a temporary solution how to enter the correct "Image Size" in the full format (e.g. 200x300)

1) Go to your database with either phpmyadmin 
or cli -> "mysql -u database_user -p database_name"

2) look for "core_config_data" table

and find the following PATH:

design/watermark/image_size
design/watermark/small_image_size
design/watermark/swatch_image_size
design/watermark/thumbnail_size

3) set the VALUE manualy e.g. -> 200x300

**Comment by antboiko** [comment] 2016-09-27 07:46
Hi @RG-1  @gabriel-sf. Please let me inform you this issue was fixed and delivered to the develop branch. The fix was also ported to 2.1 and will be available in one of nearest patches.

I'm closing this ticket. Please feel free to reopen if the issue is still reproducible for you on the develop branch.

Best,
Anton.

**Closed as completed by antboiko** 2016-09-27 07:46 UTC
Labels: Issue: Ready for Work, bug report

**Comment by gabriel-sf** [comment] 2016-10-09 19:09
Hi @antboiko would you be able to specify how we can implement the patch to fix this issue?

**Comment by elenleonova** [comment] 2016-12-15 02:02
The issue has been delivered to 2.1.3
