### ISSUE TITLE
Password fields are not available

### ISSUE THREAD

**Issue by kumarancontus** [magento/magento2#6598] opened 2016-09-13 14:12 UTC
Password fields not available while creating a new customer from admin

**Comment by dthampy** [comment] 2016-09-13 20:48
@kumarancontus , Can you please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) with steps to reproduce, actual result and expected result.
Please include the magento version that you are using along with the information regarding if it was an upgrade or not. 
If you could screenshot along with the steps, that'd be great.

**Comment by davidalger** [comment] 2016-09-15 16:45
Closing due to insufficient information.

**Closed as completed by davidalger** 2016-09-15 16:45 UTC
Labels: Progress: needs update
