### ISSUE TITLE
Review Report Filters are not working in admin

### ISSUE THREAD

**Issue by bhagyashreebvi** [magento/magento2#27878] opened 2020-04-17 10:01 UTC
### Preconditions (*)

1.Magento 2.3.2

 Steps to reproduce (*)

1. In the admin panel go to reports -> Reviews
2. By Customers -> In Customer Reviews Report, apply filters for "Reviews" column.
3. By Products -> In Product Reviews Report, apply filter for Average , Average(Approved) column.

 Expected result (*)

1. It should return the filtered results with count 

 Actual result (*)
1.Filters are not working.

![DeepinScreenshot_select-area_20200417150220](https://user-images.githubusercontent.com/63847117/79557347-07bb1a00-80c0-11ea-8a19-00e093201826.png)

**Comment by sudheers-kensium** [comment] 2020-04-22 06:18
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-22 06:18
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-22 06:20
Hi @sudheers-kensium, here is your [Magento instance](https://i-27878-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27878-2-4-develop.instances.magento-community.engineering/admin_2076](https://i-27878-2-4-develop.instances.magento-community.engineering/admin_2076)
Login: `1d033c16` Password: `e4fbc9527120`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment] 2020-04-22 06:52
@bhagyashreebvi I am not able to reproduced the issue on Magento 2.4-develop instance. Maybe issue fixed in latest version. Please upgrade Magento to latest version.

**Closed as completed by sudheers-kensium** 2020-04-22 06:52 UTC
Labels: Issue: Format is valid, Reported on 2.3.2
