### ISSUE TITLE
Catalog Prices Including/Excluding Tax no effect on price calculation

### ISSUE THREAD

**Issue by wstnbrg** [magento/magento2#33947] opened 2021-08-30 12:52 UTC
### Preconditions (*)

1. Magento Versions: 2.4.2, 2.4.3
2. Tax setup with Country: Germany - 19% 

### Steps to reproduce (*)

1. Stores - Configuration > Sales > Tax > Calculation Settings > Catalog Prices set to 'Including Tax'
2. Stores - Configuration > Sales > Tax > Price Display Settings > Display Product Prices In Catalog set to 'Including Tax'
3. Stores - Configuration > Sales > Tax > Shopping Cart Display Settings > Display Prices set to 'Including and Excluding Tax'
4. Default Tax Destination Calculation - Country - Set Germany / US Country. (Observed for both countries)
4. Stores - Taxes - Create Tax Zone and Rate with Country "Germany". Tax rate is 19%
5. Apply Tax rate to Tax Rule
6. Reindex and clear cache
6. Product setup with price (e.g. 10$) and assigned to taxable goods
7. Front-end - Sign in as customer - default Shipping Address - Germany Address
8. Add the product to Cart
Issue: Tax is not included in Catalog Price
### Expected result (*)

Item price including tax should be 10$

### Actual result (*)

Item price including tax is 11.90 
There is no change in Grand Total calculation if Catalog Prices are set to Including Tax / Excluding Tax 
In both the cases - Grand Total is 10 + 1.90 (Tax) = 11.90
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by wstnbrg** [comment] 2021-08-30 12:55
@magento give me 2.4-develop instance

**Comment by wstnbrg** [comment] 2021-08-30 13:16
Was able to verify on develop instance here.
In Cart:
<img width="1429" alt="Screenshot 2021-08-30 at 15 11 32" src="https://user-images.githubusercontent.com/25225975/131344676-6d187d1e-3f24-4e87-abad-e1d37397743b.png">

Product price in admin:
<img width="1794" alt="Screenshot 2021-08-30 at 15 13 47" src="https://user-images.githubusercontent.com/25225975/131344736-bc2ec370-8aa3-477d-90d6-522ffcd04c2e.png">

Tax settings:
<img width="1562" alt="Screenshot 2021-08-30 at 15 11 48" src="https://user-images.githubusercontent.com/25225975/131344772-40016f77-df1b-4a97-ba06-b74587e158ff.png">
<img width="1642" alt="Screenshot 2021-08-30 at 15 11 57" src="https://user-images.githubusercontent.com/25225975/131344790-32a6ce55-a47b-47f1-94ba-4130f1fdccb8.png">

Tax rules:
<img width="1829" alt="Screenshot 2021-08-30 at 15 15 22" src="https://user-images.githubusercontent.com/25225975/131344891-61b8f5fb-b3e5-471c-b9dc-156c18fe7888.png">

Tax zones:
<img width="1819" alt="Screenshot 2021-08-30 at 15 15 32" src="https://user-images.githubusercontent.com/25225975/131344923-03beb8a5-138f-4b75-a496-5f725d0b10e3.png">

**Comment by engcom-November** [comment] 2021-09-01 09:43
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
**Steps to reproduce:**
Stores - Configuration > Sales > Tax > Calculation Settings > Catalog Prices set to 'Including Tax'
Stores - Configuration > Sales > Tax > Price Display Settings > Display Product Prices In Catalog set to 'Including Tax'
Stores - Configuration > Sales > Tax > Shopping Cart Display Settings > Display Prices set to 'Including and Excluding Tax'
Stores - Taxes - Create Tax Zone and Rate with Country "Germany". Tax rate is 19%
Apply Tax rate to Tax Rule
Product setup with price (e.g. 10$) and assigned to taxable goods
Front-end - Sign in as customer - default Germany Address
Add the product to Cart
**Issue:** 
![image](https://user-images.githubusercontent.com/60198231/131649790-4333c719-f8bc-4773-84b3-80e0ac4e490b.png)

![image](https://user-images.githubusercontent.com/60198231/131649751-09cccaca-08b8-4226-b9cb-5bca1a94b0b1.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/60198231/131649650-b8de7f38-24da-46dc-92f9-b16a9c3d452e.png)

**Comment by chernenm** [comment] 2021-09-23 20:09
@magento give me 2.3.7 instance

**Comment by chernenm** [comment] 2021-09-23 20:11
@magento give me 2.3-develop instance

**Comment by chernenm** [comment] 2021-09-23 20:12
@magento give me 2.4-develop instance

**Closed as completed** 2021-12-01 11:02 UTC
Labels: Component: Tax, Issue: Confirmed, Reproduced on 2.4.x, Priority: P1, Progress: done, Reported on 2.4.3, Area: Payments, Area: Tax

**Comment by marcoveeneman** [comment] 2021-12-21 11:27
The issue is moved to done, but how was it resolved? Is there a patch available? I'm having the same issue on 2.4.3-p1.

**Comment by secaliskan** [comment] 2021-12-30 20:22
Hi we have the same issue on 2.4.3, Product price is entered (VAT included) 1000 and its showing 1000 +VAT on catalog... Altough as above all settings are "Including Tax"... 

How this case resolved??

**Comment by mtjweb** [comment] 2022-01-26 12:58
Is there a workaround for this problem?

**Comment by mtjweb** [comment] 2022-01-27 10:43
I set the option "Enable Cross Border Trade" to Yes and the prices were displayed correctly.

**Comment by engcom-November** [comment] 2022-09-14 12:07
It has been decided that this is expected behavior of Magento but not bug.
The straight forward use case when store country, shipping origin country, tax rate country and shipping address is the same then the tax functionality is working as expected.

Taking cues from the below mentioned comments on JIRA ticket [AC-1191](https://jira.corp.adobe.com/browse/AC-1191),

https://jira.corp.magento.com/browse/AC-1191?focusedCommentId=1795489&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1795489

https://jira.corp.magento.com/browse/AC-1191?focusedCommentId=1795489&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1795489

https://jira.corp.magento.com/browse/AC-1191?focusedCommentId=1795489&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1795489

**Comment by timpea-splat** [comment] 2023-06-27 09:13
Anyone having problems with this, make sure the following is set correctly.
Store -> Configuration -> Sales -> Shipping Settings -> Origin

**Comment by secaliskan** [comment] 2023-06-27 10:05
Merhaba,
26/06/2023 ile 03/07/2023 tarihleri arasında Kurban Bayramı tatili sebebi ile emaillerime sınırlı erişimim olacaktır.

Acil durumlarda Muhammed'e ***@***.*** adresinden mail gönderebilirsiniz.


Savaş Çalışkan
MagentoTeknik
