### ISSUE TITLE
Custom option update all prices in the page

### ISSUE THREAD

**Issue by hawksakr** [magento/magento2#3672] opened 2016-03-07 07:34 UTC
## Steps to reproduce
1. add custom option with price to some product 
2. add related products or upsell or cross to that product
3. open that product in front end using luma theme 
4. pick the custom option with price you added 
5. look to the price box of the product in related widget below the prices also updated 
## Expected result
1. only the price of basic product updated with the custom option value 
2. ...
## Actual result
1. the prices of all products updated

**Comment by katmoon** [comment] 2016-03-12 12:10
Hi @hawksakr 

Thank you for reporting the issue with the clear steps to reproduce!

I cannot reproduce the issue on the latest Magento version.
Could you say which version you use?

![shot-2016-03-12_14-09-00](https://cloud.githubusercontent.com/assets/1260101/13722870/23a7b350-e85c-11e5-8dce-3d05ea014277.png)

**Comment by piotrekkaminski** [comment] 2016-06-20 19:47
Closing as cannot reproduce. If issue persists in latest version (2.1), please open a new issue.

**Closed as completed by piotrekkaminski** 2016-06-20 19:47 UTC
Labels: Progress: needs update
