### ISSUE TITLE
Bundle Stock Status Is Wrong After Create Shipment

### ISSUE THREAD

**Issue by manhtranisobar** [magento/magento2#37388] opened 2023-04-18 03:55 UTC
### Preconditions and environment

- Magento 2.4.5-p1
- Enable MSI

### Steps to reproduce

- Create 2 websites with code: w1 and w2
- Create new stock source with code source2
- Create new stock with Sales Channels is website 2 only, sources is source2 only
- Create 2 simple products and assign to website 2, update source 2 qty to 100
- Create new bundle product with 2 require options, option 1 have product simple 1, option 2 have product simple 2. Options qty is 1. Ship Bundle Items is Together
- View bundle product at frontend and add to cart with qty 1, then complete checkout
- Go to admin and create shipment for new order
- Check bundle status

### Expected result

- Bundle product stock status is In Stock

### Actual result

- Bundle product stock status is changed to Out of stock

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-04-18 09:36
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-04-18 13:01
Hi @manhtranisobar,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Create 2 websites with code: w1 and w2
- Create new stock source with code source2
- Create new stock with Sales Channels is website 2 only, sources is source2 only
- Create 2 simple products and assign to website 2, update source 2 qty to 100
- Create new bundle product with 2 require options, option 1 have product simple 1, option 2 have product simple 2. Options qty is 1. Ship Bundle Items is Together
- View bundle product at frontend and add to cart with qty 1, then complete checkout
- Go to admin and create shipment for new order
- Check bundle status

<img width="1418" alt="Screenshot 2023-04-18 at 4 19 22 PM" src="https://user-images.githubusercontent.com/51680745/232754968-d983fcaf-129f-4ebb-9af6-92b8ed320ec1.png">



![Bundlee-Products-Inventory-Catalog-Magento-Admin](https://user-images.githubusercontent.com/51680745/232755027-cdd9dc5b-20d7-420b-bc36-7af22bd48913.png)



Bundle Product is still in `IN STOCK` after creating shipment.

Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by manhtranisobar** [comment] 2023-04-19 02:46
Hi @engcom-Bravo 

This issue happen with version 2.4.5.
I have tried with Magento 2.4.6 and see It was resolved. Do we have any patch for version 2.4.5 to resolve It?

**Comment by engcom-Bravo** [comment] 2023-04-19 14:14
Hi @manhtranisobar,

Thanks for your update.

Kindly upgrade to latest version of Magento i.e Magento 2.4.6.

The issue is no more reproducible in Magento 2.4 develop instance.Please let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-05-02 06:05
Hi @manhtranisobar,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-05-02 06:05 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1

**Comment by ivanaugustobd** [comment] 2023-11-03 21:33
Did you find a patch for it @manhtranisobar? Or maybe the Magento 2.4.6 PR containing such fix?

**Comment by manhtranisobar** [comment] 2023-11-06 02:03
Hi @ivanaugustobd 
You can try to apply these patches:
[ACSD-4.zip](https://github.com/magento/magento2/files/13261776/ACSD-4.zip)
