### ISSUE TITLE
$collection->getMaxPrice() returns wrong result with Elasticsearch

### ISSUE THREAD

**Issue by 06romix** [magento/magento2#28919] opened 2020-06-29 12:29 UTC
### Preconditions (*)

1. Magento ver. 2.3.5-p1
2. Elasticsearch 6.0+ (6.8.9)

### Steps to reproduce (*)
1. Select Elasticsearch 6.0+ as Search Engine
2. Print $collection->getMaxPrice() or $collection->getMinPrice() from \Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection on category page with products
3. Go to next page

### Expected result (*)
1. Method getMaxPrice () returns the price of the most expensive product in category as it do for mysql engine 

### Actual result (*)

1. Method getMaxPrice () returns the price of the most expensive product on current page

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment] 2020-07-02 13:59
Hello @06romix 

I am not able to reproduce this issue on the latest 2.4-develop branch by provided steps.

**Testing scenario:**

**Preconditions:**
Magento 2.4
Elasticsearch 7.0+

**Steps to reproduce:**

1. Insert `<h1><?php echo $_productCollection->getMaxPrice() ?></h1>` into 
 `app/code/Magento/Catalog/view/frontend/templates/product/list.phtml:24`
3. Flush cache
4. Go to store view and open any category page
5. Pay attention on price which shown under product list
6. Go to next page

**Result:**
Price changed to maximum price on this page
![Peek 2020-07-02 16-54](https://user-images.githubusercontent.com/60198022/86367482-ad743300-bc84-11ea-9ea2-5e42b3262051.gif)

Note: The same testing scenario with `$_productCollection->getMinPrice()` on first step:
![Peek 2020-07-02 16-44](https://user-images.githubusercontent.com/60198022/86367004-2a52dd00-bc84-11ea-81a9-0653fb1ec98f.gif)

So i close it.
Thanks for your report!

**Closed as completed by engcom-Lima** 2020-07-02 13:59 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid, Triage: Dev.Experience, Reported on 2.3.5-p1

**Comment by 06romix** [comment] 2020-07-03 08:36
Hello @engcom-Lima 

Thanks for detailed report)

But there's one thing to discuss, Expected result was:
Method getMaxPrice () returns the price of the **most expensive product in category** as it do for mysql engine.

Maybe current logic is correct, but for one case (Price Slider) it's bad

Magento has ranges
0-100
100-200
200 and above

For price slider we need to crate range 11 - 245

So it was good when mysql engine set 245 as max price to collection, in spire of selected page. Now, for elastic we have to catch query response to get prices.

In my opinion such popular feature should have simpler implementation.

**Comment by engcom-Lima** [comment] 2020-07-03 11:08
Hello @06romix this description looks like a feature request.
Please, create issue in community-features [repo](https://github.com/magento/community-features/issues) for further discussion.

> Hello @engcom-Lima
> 
> Thanks for detailed report)
> 
> But there's one thing to discuss, Expected result was:
> Method getMaxPrice () returns the price of the **most expensive product in category** as it do for mysql engine.
> 
> Maybe current logic is correct, but for one case (Price Slider) it's bad
> 
> Magento has ranges
> 0-100
> 100-200
> 200 and above
> 
> For price slider we need to crate range 11 - 245
> 
> So it was good when mysql engine set 245 as max price to collection, in spire of selected page. Now, for elastic we have to catch query response to get prices.
> 
> In my opinion such popular feature should have simpler implementation.
