### ISSUE TITLE
Configurable products have no price once saved and reindexed

### ISSUE THREAD

**Issue by robbamber** [magento/magento2#32980] opened 2021-05-09 20:25 UTC
### Preconditions (*)

1. Magento 2.4.2
2. Sample Data

### Steps to reproduce (*)

1. Install Magento sample data.
2. Check price data in catalog_product_entity_decimal. Configurable products have prices in the sample data:

<img width="1024" alt="catalog_product_entity" src="https://user-images.githubusercontent.com/52827107/117585290-850d5e80-b109-11eb-9b78-5a42057e1e86.png">

<img width="1024" alt="catalog_product_entity_decimal-before" src="https://user-images.githubusercontent.com/52827107/117585296-9191b700-b109-11eb-8003-2b5da686c46d.png">

3. Reindex. Data in catalog_product_index_price looks correct:

<img width="1024" alt="catalog_product_index_price-before" src="https://user-images.githubusercontent.com/52827107/117585355-f4834e00-b109-11eb-81ad-7140a7c4f22d.png">

4. Save the configurable product. Configurable product no longer has a price value which is expected:

<img width="1016" alt="catalog_product_entity_decimal-after" src="https://user-images.githubusercontent.com/52827107/117585368-01a03d00-b10a-11eb-823c-7cbb168f31f4.png">

5. Reindex.  Configurable product now has zero price and zero final price in catalog_product_index_price:

<img width="1021" alt="catalog_product_index_price-after" src="https://user-images.githubusercontent.com/52827107/117585395-298fa080-b10a-11eb-8084-4d53feb9916f.png">

### Expected result (*)

1. Configurable product should have a price and a final price value in the catalog_product_index_price table.  

### Actual result (*)

1. Price and final price values for configurable product is zero.
---

Any custom sorting functionality that depends on price such as 'Biggest discount' no longer functions because of this issue.  A (really nasty) work around is to not clear prices for configurable products on save.

```
diff --git a/view/adminhtml/web/js/components/price-configurable.js b/view/adminhtml/web/js/components/price-configurable.js
index b2ef3554..60b097af 100644
--- a/view/adminhtml/web/js/components/price-configurable.js
+++ b/view/adminhtml/web/js/components/price-configurable.js
@@ -51,10 +51,6 @@ define([
          */
         handlePriceValue: function (isConfigurable) {
             this.disabled(!!this.isUseDefault() || isConfigurable);
-
-            if (isConfigurable) {
-                this.clear();
-            }
         }
     });
 });
```

Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ **S1**] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment] 2021-05-13 14:29
@engcom-Charlie Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by engcom-Charlie** [comment] 2021-05-13 14:57
This issue is reproducible. 

Please note, in order to reproduce this issue we need to have fresh/new Magento setup.

**Comment by gabrieldagama** [comment] 2021-05-20 16:21
Hi @robbamber, the configurable product has the price at first instance because that is required when the product is being created, but once you re-save it the price is not relevant anymore and the children's prices are the main ones.

As it looks now the behavior seems correct, can you provide more details if this has any functional impact? Like frontend prices being displayed incorrectly?

**Comment by robbamber** [comment] 2021-05-21 17:24
Hi Gabriel,

Many thanks for looking at this. We have some custom functionality which allows customers to sort the product collection on category pages by biggest discount. This uses the price column to calculate the saving used in the sort. If prices are zero for configurable products, this functionality stops working.

**Comment by gabrieldagama** [comment] 2021-05-28 08:43
Hi @robbamber, in this case, we would recommend using one of the prices @api classes, the behavior on the database level is correct from our application point of view. 

As far as I understood, sorting products by the biggest discount, you may need to index this to Elasticsearch instead, this customization is possible and may be better than post-processing ES return, but that is just an idea and I don' have the full picture.

Therefore I will be closing this one since it is not an actual issue. Thanks for contributing!

**Closed as completed by gabrieldagama** 2021-05-28 08:43 UTC
Labels: Issue: Confirmed, Triage: Dev.Experience, Reproduced on 2.4.x
