### ISSUE TITLE
Category Wysiwyg Attribute disable when switching to Store View

### ISSUE THREAD

**Issue by mirkorap** [magento/magento2#23257] opened 2019-06-14 07:50 UTC
### Information of environment (*)
- Magento 2.3.0
- PHP 7.1
- MySQL 5.7

### Summary (*)
I added a wysiwyg as category eav attribute and all works correctly, but I want that the content of my wysiwyg is different for each store view. If I switch store view in category page, my wysiwyg field is disable, it turns enable only when I select "All Store Views".

### Steps to reproduce (*)

1. Install Magento 2.3.0
2. Add Category Size Chart Attribute
```
<?php
declare(strict_types=1);

namespace [Vendor]\[Module]\Setup\Patch\Data;

use Magento\Catalog\Model\Category;
use Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface;
use Magento\Eav\Setup\EavSetupFactory;
use Magento\Framework\Setup\ModuleDataSetupInterface;
use Magento\Framework\Setup\Patch\DataPatchInterface;

class AddCategorySizeChartAttribute implements DataPatchInterface
{
    /**
     * @var ModuleDataSetupInterface
     */
    private $moduleDataSetup;

    /**
     * @var EavSetupFactory
     */
    private $eavSetupFactory;

    /**
     * AddCategorySizeChartAttribute constructor.
     * @param ModuleDataSetupInterface $moduleDataSetup
     * @param EavSetupFactory $eavSetupFactory
     */
    public function __construct(
        ModuleDataSetupInterface $moduleDataSetup,
        EavSetupFactory $eavSetupFactory
    ) {
        $this->moduleDataSetup = $moduleDataSetup;
        $this->eavSetupFactory = $eavSetupFactory;
    }

    /**
     * {@inheritDoc}
     */
    public static function getDependencies()
    {
        return [];
    }

    /**
     * {@inheritDoc}
     */
    public function getAliases()
    {
        return [];
    }

    /**
     * {@inheritDoc}
     */
    public function apply()
    {
        $categorySetup = $this->eavSetupFactory->create(['setup' => $this->moduleDataSetup]);

        $categorySetup->addAttribute(
            Category::ENTITY,
            'size_chart',
            [
                'type' => 'text',
                'label' => 'Size Chart',
                'input' => 'textarea',
                'required' => false,
                'sort_order' => 999,
                'global' => ScopedAttributeInterface::SCOPE_STORE,
                'wysiwyg_enabled' => true,
                'is_html_allowed_on_front' => true,
                'group' => 'General Information',
            ]
        );

        return $this;
    }
}
```
3. Create `category_form.xml` ui component
```
<?xml version="1.0"?>
<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
    <fieldset name="general">
        <field name="size_chart" template="ui/form/field" sortOrder="70" formElement="wysiwyg">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="wysiwygConfigData" xsi:type="array">
                        <item name="height" xsi:type="string">300px</item>
                        <item name="add_variables" xsi:type="boolean">true</item>
                        <item name="add_widgets" xsi:type="boolean">true</item>
                        <item name="add_images" xsi:type="boolean">true</item>
                        <item name="add_directives" xsi:type="boolean">true</item>
                    </item>
                    <item name="source" xsi:type="string">category</item>
                </item>
            </argument>
            <settings>
                <label translate="true">Size Chart</label>
                <scopeLabel>[STORE VIEW]</scopeLabel>
                <dataScope>size_chart</dataScope>
            </settings>
            <formElements>
                <wysiwyg class="Magento\Catalog\Ui\Component\Category\Form\Element\Wysiwyg">
                    <settings>
                        <rows>8</rows>
                        <wysiwyg>true</wysiwyg>
                    </settings>
                </wysiwyg>
            </formElements>
        </field>
    </fieldset>
</form>
```
4. Create two Store View
5. Go to `Admin->Catalog->Categories` switch to Store View and the field `size_chart` result disable.

If I click to "All Store Views" the field is correctly enabled and editable
![field-enabled](https://user-images.githubusercontent.com/33153699/59492539-7cfb0480-8e89-11e9-8393-6124bddeb8c6.png)

If I click to specific Store View the field is disabled, but in `AddCategorySizeChartAttribute` the `global` value is setted to `SCOPE_STORE`
![field-disabled](https://user-images.githubusercontent.com/33153699/59492640-ae73d000-8e89-11e9-8834-08d2b228b835.png)

### Expected result (*)
The field is editable even if I switch to a specific Store View

### Actual result (*)
The field is disable if I switch to specific Store View. It's enable only when I select "All Store Views"

**Comment by mirkorap** [comment] 2019-06-14 08:08
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment] 2019-06-14 08:08
Hi @mirkorap. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-06-14 08:09
Hi @mirkorap, here is your [Magento instance](https://i-23257-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23257-2-3-develop.instances.magento-community.engineering/admin](https://i-23257-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mirkorap** [comment] 2019-06-14 08:21
@magento to reproduce the issue I need to run the steps that I have just written above

**Comment by chohanbhagchand** [comment] 2019-06-14 09:21
Kindly assign me this issue

**Comment by mirkorap** [comment] 2019-06-14 09:53
@chohanbhagchand I can't assign issue to user. I don't have permission

**Comment by chohanbhagchand** [comment] 2019-06-14 10:41
Can you please tell who will assign the issue to me.

**Comment by mirkorap** [comment] 2019-06-14 18:14
@magento Another user had the same issue some months ago: #20154

**Comment by shikhamis11** [comment] 2019-06-15 07:23
hello @mirkorap , thanks for reporting the issue . It seems the issue is duplicate of #20154 & #13440 so closing this one now. you can check the progress in the above issues

**Closed as completed by shikhamis11** 2019-06-15 07:23 UTC
Labels: duplicate, Issue: Format is not valid
