### ISSUE TITLE
Redis Session Storage

### ISSUE THREAD

**Issue by bondimedical3** [magento/magento2#6312] opened 2016-08-24 10:37 UTC
I have keys appearing in my Redis database for session storage but I have noticed there is data continually being added to the 'session' table in phpMyAdmin. Is this a bug?

**Comment by odubovyk** [comment] 2016-08-26 12:18
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.

**Comment by bondimedical3** [comment] 2016-08-26 21:33
Redis has been installed according to your documentation - http://devdocs.magento.com/guides/v2.0/config-guide/redis/redis-session.html and data is still being written to the session table in the database.

Magento version 2.1

**Comment by picamator** [comment] 2016-09-01 15:29
@bondimedical3  Thanks for reporting.
Unfortunately  we can not reproduce this issue.

Could you please add more information:
1. Do you have clear Magento 2.1 installed or you have upgraded 2.0.x up to 2.1?
2. Could you please follow those steps:
2.0. Check number of items in your `session` table
2.1. Run on server `redis-cli`
2.2. Run  `SELECT 0`
2.3. Refresh any frontend page
2.4. Run on server `KEYS *`
2.5. Do you see any keys that started with "sess_"?
2.6. Check `session` table, do you see any new items?
3. Do you have specific configuration, DI overriding, plugin installed?

**Comment by bondimedical3** [comment] 2016-09-02 04:36
1. I have a 2.0.x upgraded to 2.1
   2.0 I have deleted everything in the session table 
   2.1, 2.2 Done
   2.3, 2.4 Done
   2.5 Two entries only both which start with "sess_
   2.6 Session table has remained empty.

Notes: I have upgraded to 2.1.1 yesterday so perhaps this fixed the issue.

**Comment by veloraven** [comment] 2016-09-02 08:20
I'm closing this issue as the problem was resolved.

**Closed as completed by veloraven** 2016-09-02 08:20 UTC
Labels: bug report, Progress: needs update, Component: Framework/Cache
