### ISSUE TITLE
Product custom options being replaced instead of updated

### ISSUE THREAD

**Issue by bartlubbersen** [magento/magento2#7875] opened 2016-12-19 12:35 UTC
### Preconditions

1. Magento 2.1.3
2. PHP7

### Steps to reproduce
1. Create a product with custom options via the API: /V1/products/
2. The options will apear successfully
3. Now update the product options while specifying the option_id aswell.

### Expected result
1. The option id should stay the same and the options should be updated rather than being replaced.

### Actual result
1. The option is updated, however the option id changed.

### Comment
The reason this can be a problem is because if you have a cart with items inside of it with the custom options specified and you update the product options the current options will be entirely removed because the ID does not exist anymore. Which results in the customer being able to order a product without options. So we would prefer to just update the existing options so this problem won't occur.

**Comment by scottsb** [comment] 2017-08-14 23:40
This is a duplicate of #5931. It's deeper than just the REST API.

**Comment by sheldmandu** [comment] 2017-10-13 05:30
@magento-engcom-team Is this resolved given it's a duplicate of #5931 and should hence be closed?  What commit was it resolved in? I'm looking to perhaps backport it unless Magento would consider doing it.

**Comment by magento-engcom-team** [comment] 2017-10-13 13:30
@bartlubbersen, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-13 13:30 UTC
Labels: bug report, Component: Framework/Webapi, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
