### ISSUE TITLE
Add an extension point to RateRequest in requestShippingRates

### ISSUE THREAD

**Issue by atwixfirster** [magento/magento2#22568] opened 2019-05-01 11:13 UTC
### Summary (*)

Now, we do not have a point to set a custom option to `$request` object in `Magento\Quote\Model\Quote\Address::requestShippingRates`.

### Examples (*)

**Codebase link:** https://github.com/magento/magento2/blob/37677f83c6221c69d36be05cff58fc73795a8975/app/code/Magento/Quote/Model/Quote/Address.php#L976

### Affected Magento versions
- 2.1
- 2.2
- 2.3

### Proposed solution

Add the `sales_quote_address_collect_rates_before` observer 
```php
$this->_eventManager->dispatch($this->_eventPrefix . '_collect_rates_before', ['request' => $request]);
```

before

```php
$result = $this->_rateCollector->create()->collectRates($request)->getResult();
```

### Example of usage (after implementation)
**1.** File `app/code/Vendor/Module/etc/events.xml`:

```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
    <event name="sales_quote_address_collect_rates_before">
        <observer name="Vendor_Module::sales_quote_address_collect_rates_before" instance="Vendor\Module\Observer\SetCustomRequestParamBeforeCollectRatesObserver"/>
    </event>
</config>
```

**2.** File `app/code/Vendor/Module/Observer/SetCustomRequestParamBeforeCollectRatesObserver.php`:

```php
<?php
namespace Vendor\Module\Observer;

use Magento\Framework\Event\ObserverInterface;

/**
 * Class sets a value of custom option to $request \Magento\Quote\Model\Quote\Address\RateRequest
 */
class SetCustomRequestParamBeforeCollectRatesObserver implements ObserverInterface
{
    /**
     * @param \Magento\Framework\Event\Observer $observer
     */
    public function execute(\Magento\Framework\Event\Observer $observer)
    {
        $request = $observer->getRequest();
        $request->setMyCustomOption('Hello world!');
    }
}
```

**Comment by shikhamis11** [comment] 2019-05-01 11:16
hi @atwixfirster , Please follow issue reporting guideline to report an issue
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
Thanks.

**Comment by atwixfirster** [comment] 2019-05-01 11:22
> hi @atwixfirster , Please follow issue reporting guideline to report an issue
> https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
> Thanks.

Yes. I will add all necessary information. Also, I will attach a pull request with a fix.

Thanks!

**Comment by atwixfirster** [comment] 2019-05-01 12:37
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-05-01 12:37
Hi @atwixfirster. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-05-01 12:38
Hi @atwixfirster, here is your [Magento instance](https://i-22568-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22568-2-3-develop.instances.magento-community.engineering/admin](https://i-22568-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by atwixfirster** [comment] 2019-05-01 12:54
**Pull request:** https://github.com/magento/magento2/pull/22570

Thank you!

**Comment by magento-engcom-team** [comment] 2019-05-01 13:10
@dmytro-ch Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-05-01 13:11
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99474`, `MAGETWO-99475` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by orlangur** [comment] 2019-05-01 13:37
@atwixfirster @dmytro-ch what's the problem with implementing this logic as a before plugin?

**Comment by atwixfirster** [comment] 2019-05-01 15:25
@dmytro-ch, @orlangur,

 I've removed 
```php
$this->_eventManager->dispatch($this->_eventPrefix . '_collect_rates_before', ['request' => $request]);
```

and moved `$request` to new public function - `getAddressRateRequest`.

This solution allows to modify `$request` after creation:
- etc/di.xml

```xml
<config>
    <type name="Magento\Quote\Model\Quote\Address">
        <plugin name="vendor-add-custom-option-to-request" type="Vendor\CustomShipping\Plugin\AddCustomOptionToAddressRateRequestPlugin" sortOrder="10" disabled="false" />
    </type>
</config>
```

- app/code/Vendor/CustomShipping/Plugin/AddCustomOptionToAddressRateRequestPlugin.php
```php
<?php

namespace Vendor\CustomShipping\Plugin;

use Magento\Quote\Model\Quote\Address;
use Magento\Quote\Model\Quote\Address\RateRequest;

class AddCustomOptionToAddressRateRequestPlugin
{
    /**
     * @param Address $subject
     * @param RateRequest $result
     * @return RateRequest
     */
    public function afterGetAddressRateRequest(
        Address $subject,
        RateRequest $result,
        $item
    ) {
        $result->setCustomOption('Hello world!');
        return $result;
    }
}
```

Could you please review new solution? 

😊 

Thank you!

**Comment by dmytro-ch** [comment] 2019-05-01 17:37
@orlangur, as far as I understand, the main issue is that there is no way to access the instance of `Magento\Quote\Model\Quote\Address\RateRequest` due to the short lifetime of its variable (`$request`),
 since it's being created, mapped and processed within the same method (`requestShippingRates`).

Therefore, I agree with @atwixfirster that it's a good idea to provide a more or less acceptable entry point for appending a custom Rate Request data among the sequence of these hardcoded setter methods calls.

Thank you!

**Comment by orlangur** [comment] 2019-05-01 22:08
@atwixfirster @dmytro-ch why not create `beforeCollectRates` plugin? Introducing public methods is not a good idea as it breaks class encapsulation.

**Comment by atwixfirster** [comment] 2019-05-02 13:21
> @atwixfirster @dmytro-ch why not create `beforeCollectRates` plugin? Introducing public methods is not a good idea as it breaks class encapsulation.

yes, @orlangur. `beforeCollectRates` plugin is a good solution.

Please close this PR.

Thank you! 

CC: @dmytro-ch

**Comment by orlangur** [comment] 2019-05-02 13:40
@atwixfirster okiz, thanks for collaboration!

**Closed as completed by orlangur** 2019-05-02 13:40 UTC
Labels: non-issue, Issue: Format is valid, Component: Quote
