### ISSUE TITLE
queue_poison_pill table missing PK

### ISSUE THREAD

**Issue by sych74** [magento/magento2#33822] opened 2021-08-17 08:56 UTC
The **queue_poison_pill** table is missing a PK. Because of this, it cannot be replicated reliably in Galera based systems (eg. MariaDB, Percona XtradbCluster).

### Preconditions (*)
Magento 2.4.3

### Steps to reproduce (*)
1. Open database table **queue_poison_pill**
2. Check if the table has a Primary Key

### Expected result (*)
The database table **queue_poison_pill** has Primary Key

### Actual result (*)
The database table **queue_poison_pill** doesn't have Primary Key

```
SQLSTATE[42000]: Syntax error or access violation: 1173 This table type requires a primary key, query was: 
CREATE TABLE `queue_poison_pill` ( `version` varchar(255) NOT NULL  COMMENT "Poison Pill version.") 
ENGINE=innodb DEFAULT CHARSET=utf8 DEFAULT COLLATE=utf8_general_ci COMMENT="Sequence table for poison pill versions"
```

**Comment by engcom-Echo** [comment] 2021-08-24 05:32
Hi @sych74 
Thanks for reporting the issue.
We checked on your issue. The **queue_poison_pill** table will always have a single version entry, which is basically just a random hash. If some configuration value gets changed using the Magento backend, the poison pill version is changed. The running consumer processes check on this version, but only when a new message is in the queue. So in this case we have a natural key **version** that hold the single unique entry.
In code base the **version** is treated as the **idFieldName**.
`protected function _construct()`
 ` {`
 `     $this->_init(self::QUEUE_POISON_PILL_TABLE, 'version');`
 ` }`
 
If you have faced any issues/errors w.r.t to this table not having an explicit PK, please write to us , with actual steps to reproduce the issue, expected & actual results. We shall definitely look into the same.

Thank you.

**Comment by engcom-Hotel** [comment] 2021-09-09 09:51
Dear @sych74,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2021-09-09 09:51 UTC
Labels: Severity: S1, Issue: needs update, Reported on 2.4.3

**Comment by siliconalchemy** [comment] 2022-08-24 22:16
@engcom-Echo - the problem is that this missing PK prevents Magento from installing or operating correctly on a Galera based cluster, such as Percona Xtradb Cluster.  Galera is a very popular replication system for Mysql, and is widely used for mission critical environments such as Magento.

During install, it fails with this error:
```
[Progress: 661 / 1323]
Installing user configuration...

In Mysql.php line 109:

  SQLSTATE[HY000]: General error: 1105 Percona-XtraDB-Cluster prohibits use of DML command on a table (net_siliconalchemy_magento2.queue_poison_pil
  l) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER, query was: INSERT INTO `queue_poison_pill` (`version`) VALUES (?)


In Mysql.php line 90:

  SQLSTATE[HY000]: General error: 1105 Percona-XtraDB-Cluster prohibits use of DML command on a table (net_siliconalchemy_magento2.queue_poison_pil
  l) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER
```

**Comment by Lathanao** [comment] 2024-11-25 09:16
Same there, I have this error on an Aurora DB:
`ERROR 3750 (HY000) at line 12288: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.
`

At line 12288, I have the SQL query to create the `queue_poison_pill` table.

**Comment by engcom-Hotel** [comment] 2024-11-26 14:46
Hello @Lathanao,

The similar issue has been confirmed already:

https://github.com/magento/magento2/issues/39239

Please refer to that issue for the updates.

Thanks
