### ISSUE TITLE
Removed unwated js called on Frontend via Require js

### ISSUE THREAD

**Issue by ia-gaurav** [magento/magento2#32985] opened 2021-05-10 13:26 UTC
Magento Version  : 2.4.1

Issue - There are many unwated js called on frontend via require js , i am not getting any way to remove this

Example Js - color-picker.js, tinycolor.js

**Comment by mrtuvn** [comment] 2021-05-10 13:58
This already done in this PR
https://github.com/magento/magento2/pull/28400 (spectrum.js, tinycolor.js) (In progress)
calendar.js (merged)

**Comment by ia-gaurav** [comment] 2021-05-13 16:57
@mrtuvn  - please help me way to pull changes to avoid unwated js call

**Comment by mrtuvn** [comment] 2021-05-13 23:25
You can get these update by update your magento instance to higher version (no need futher action). But if you want all you need to create you own patches and pick them one by one to your patch file (take time if you want deliver feature to store)
https://github.com/cweagans/composer-patches
Do you have tech or development knowledges

**Comment by engcom-Lima** [comment] 2021-06-10 13:00
Hi @ia-gaurav,

This issue still exist. If Yes then Can you please tell some details regarding this ticket?

Have you reproduce this issue magento 2.4-develop or 2.4.2? If yes can you please provide me some reproducible steps and screenshots? that would be helpful.

Thanks for the understanding!

**Comment by engcom-Lima** [comment] 2021-06-17 09:25
Hi @ia-gaurav

We are expecting that your issue got resolved because we did not any update from you. Hence we are closing this ticket.

Please feel free to raise the new ticket or open the existing ticket with reproducible steps and details.

Thanks

**Closed as completed by engcom-Lima** 2021-06-17 09:25 UTC
Labels: Triage: Dev.Experience, Issue: needs update

**Comment by ia-gaurav** [comment] 2021-06-17 18:50
@engcom-Lima  - i want these unwated file to not load at user frontend part can you tell way to remove those
