### ISSUE TITLE
Overriding exception message

### ISSUE THREAD

**Issue by OPielech** [magento/magento2#35149] opened 2022-02-28 09:40 UTC
Case, that wasted my all day for debugging.
In our project we do massive products import via rabbitmq and for optimization we splitted this process for two queues. Sometimes this couses deadlocks on database, which we catch and then resend this message to the queue. This time we got error log 'The linked products data is invalid. Verify the data and try again.' and we thought, that this is something wrong with products relation data. It turned out, that Magento catches deadlock information and overrides its with own Exception, which has completely unrelated message. Link to this line below.

To resolve that we created patch, that added original message to this exception, but in my opinion all thrown custom Magento exceptions should contain getter that could handle it.

What do you think about this?
   
https://github.com/magento/magento2/blob/4c36116dcf878e127059d9be9566a119783583f2/app/code/Magento/Catalog/Model/ProductLink/Repository.php#L162

**Comment by engcom-Delta** [comment] 2022-02-28 10:57
Hi @OPielech ,
Thank you for raising an issue . Kindly provide the steps to reproduce the issue ,actual results, expected results and screenshots if required. Hence added 'Needs update' label.

**Comment by OPielech** [comment] 2022-02-28 12:54
@engcom-Delta 
It is impossible to provide reproduction steps, because in our case it takes place randomly while massive messages consuming by rabbitmq on more than one queues at the same time.
I can show You example log from Kibana. Normally when deadlock occures we get log:
`{
  "message": "Import product error",
  "context": {
    "sku": "38802",
    "message": "Database deadlock found when trying to get lock"
  },
  "level": 400,
  "level_name": "ERROR",
  "channel": "integration",
  "datetime": {
    "date": "2022-02-22 15:02:15.666740",
    "timezone_type": 3,
    "timezone": "UTC"
  },
  "extra": []
}`

In case I described, this log is overriden by this one
`{
  "message": "Import product error",
  "context": {
    "sku": "38802",
    "message": "The linked products data is invalid. Verify the data and try again."
  },
  "level": 400,
  "level_name": "ERROR",
  "channel": "integration",
  "datetime": {
    "date": "2022-02-22 18:47:09.841062",
    "timezone_type": 3,
    "timezone": "UTC"
  },
  "extra": []
}`

Probably this kind of problem can occure in other places, where custom Magento exception is thrown in catch clause.

**Comment by engcom-Hotel** [comment] 2022-05-27 07:52
Hello @OPielech,

Thanks for the report and collaboration!

For further analysis, we need some information from your side. So please provide us with the following information:
1. Screenshot of configurations related to splitting the import processes (if possible).
2. How many consumers are running at the time in order to import the products.
3. How many products are imported in bulk at a time?

Thanks

**Comment by engcom-Hotel** [comment] 2022-06-10 08:41
Dear @OPielech,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by sheepfy** [comment] 2022-06-22 09:42
@OPielech @engcom-Hotel 
Hi.
I can provide stepts of how to reproduce this issue. It's happening all the time, and it's not only the "mysql deadlock expection" there.

I am using "siege" (here some siege info: https://linuxhint.com/install-siege-ubuntu/)

Well, setup some magento with some products, then run this siege, with at least 2 or more, (i used 10) requests at a time:
"""
siege -c 10 -f ~/Downloads/nr_siege.txt -H "Authorization: Bearer xxxxx" --content-type="application/json" -H "accept: application/json"
"""

Content of file: nr_siege.txt:
http://yourmagento.local/rest/all/V1/products/SKUHERE PUT {"product": {"sku": "SKU1","extension_attributes": {"website_ids": [0,1]},"product_links": [{"sku": "SKU1","link_type": "related","linked_product_sku": "SKU2","linked_product_type": "simple","position": 0}]}}

This causes to reinsert the link attribute on a deleted link: vendor/magento/module-catalog/Model/Product/Link/SaveHandler.php -> $this->productLinkRepository->delete($link);

You can also do the xdebug with siege, by addin the ?XDEBUG_SESSION_START in the url from the nr_siege.txt

**Comment by thomas-kl1** [comment] 2022-10-05 22:58
@engcom-Hotel please reopen

**Comment by engcom-Hotel** [comment] 2022-10-06 07:08
Sure @thomas-kl1 @sheepfy 

@sheepfy Thanks for more information. We are reopening this issue for more investigation.

Thanks

**Comment by engcom-Hotel** [comment] 2022-10-20 08:40
Hello @sheepfy,

We have tried to reproduce the issue in Magento's 2.4-develop branch with `siege` but the issue is not reproducible for us. The command which we are running is as follows:

```
siege -c 10 -f ./nr_siege.txt -H "Authorization: Bearer XXXX" --content-type="application/json" -H "accept: application/json"
```

Content of nr_siege.txt:

```
http://<URL>/rest/all/V1/products/24-MB02 PUT {"product": {"sku": "24-MB02","extension_attributes": {"website_ids": [0,1]},"product_links": [{"sku": "24-MB02","link_type": "related","linked_product_sku": "24-UB02","linked_product_type": "simple","position": 0}]}}

```

But for us, there is no error log in the database log file, and below is the output of the `siege` command:
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/51681618/196900195-b55e1aae-4511-421a-992a-98e6deddcb1e.png">

Please let us know if we have missed anything.

Thanks

**Comment by sheepfy** [comment] 2022-10-20 08:55
Try this:
start 2 api requests with xdebug on. Break at first line both of them.
Let 1st request go to the line that erases the product links, and pass that line, keep the xdebug request open.
Let 2nd request got to the line that delete/inserts the product links. Note that a mysql transaction error had happened.

**Comment by engcom-Hotel** [comment] 2022-11-11 10:15
Hello @sheepfy,

Just to confirm you are talking about the catalog delete API:

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/51681618/201318906-fe9d8beb-f919-4508-a130-3f437d179a49.png">

Is that right?

Thanks

**Comment by sheepfy** [comment] 2022-11-14 07:50
@engcom-Hotel  see my previous comment, I posted the api there:

https://github.com/magento/magento2/issues/35149#issuecomment-1162882172

**Comment by sheepfy** [comment] 2022-11-14 07:54
> Hello @sheepfy,
> 
> We have tried to reproduce the issue in Magento's 2.4-develop branch with `siege` but the issue is not reproducible for us. The command which we are running is as follows:
> 
> ```
> siege -c 10 -f ./nr_siege.txt -H "Authorization: Bearer XXXX" --content-type="application/json" -H "accept: application/json"
> ```
> 
> Content of nr_siege.txt:
> 
> ```
> http://<URL>/rest/all/V1/products/24-MB02 PUT {"product": {"sku": "24-MB02","extension_attributes": {"website_ids": [0,1]},"product_links": [{"sku": "24-MB02","link_type": "related","linked_product_sku": "24-UB02","linked_product_type": "simple","position": 0}]}}
> ```
> 
> But for us, there is no error log in the database log file, and below is the output of the `siege` command: <img alt="image" width="1043" src="https://user-images.githubusercontent.com/51681618/196900195-b55e1aae-4511-421a-992a-98e6deddcb1e.png">
> 
> Please let us know if we have missed anything.
> 
> Thanks

I am not really sure, it's been a while. Buuut I guess the SKU we are trying to update needs to have already product links saved in database before starting the siege. 
Otherwise, yeaa, it doesn't make sense. Because empty links, tries to delete the link, nothing is there, no mysql transaction conflict. 

So make sure you set some links before, then update the links using siege.

**Comment by engcom-Hotel** [comment] 2022-12-01 07:02
Dear @sheepfy,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-12-01 07:02 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Area: Product
