### ISSUE TITLE
Update title of Review content

### ISSUE THREAD

**Issue by sanganinamrata** [magento/magento2#21620] opened 2019-03-07 11:47 UTC
### Description (*)
Update review text in menu like in Magento 1 as Review -> All reviews 

![2019-03-07_17-13-57](https://user-images.githubusercontent.com/37930646/53954598-b38fe900-40fc-11e9-9a7e-080361c94d38.jpg)

### Expected behavior (*)

![2019-03-07_17-02-04](https://user-images.githubusercontent.com/37930646/53954605-bc80ba80-40fc-11e9-95c0-e2268c0bbc38.jpg)

### Benefits

It helps to get client proper informaion

**Comment by magento-engcom-team** [comment] 2019-03-07 11:47
Hi @sanganinamrata. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [ ] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sanganinamrata do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-03-07 11:47
Hi @gelanivishal. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by rogyar** [comment] 2019-03-08 09:04
In my humble opinion, that's a good solution in terms of wording. Since "Reviews" contains pending reviews, it's a good point to mention the "All reviews"

**Comment by magento-engcom-team** [comment] 2019-03-26 16:54
Hi @sanganinamrata. Thank you for your report. 
The issue has been fixed in magento/magento2#21621 by @gelanivishal in 2.3-develop branch
Related commit(s):
 - [ae9084de11bf2a59d2540d2ba6769b9ef1d46b8d](https://github.com/magento/magento2/commit/ae9084de11bf2a59d2540d2ba6769b9ef1d46b8d)
 - [b62240110ec89edcefbb2f461c311086db9bc013](https://github.com/magento/magento2/commit/b62240110ec89edcefbb2f461c311086db9bc013)
 - [417fda4da93bdd11f83eec9c7ed27f2a84cc2a44](https://github.com/magento/magento2/commit/417fda4da93bdd11f83eec9c7ed27f2a84cc2a44)
 - [44ddbab42b47a16bf3f1491a5658c2ba255c81cf](https://github.com/magento/magento2/commit/44ddbab42b47a16bf3f1491a5658c2ba255c81cf)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-26 16:54 UTC
Labels: improvement, Fixed in 2.3.x, non-issue, Issue: Format is valid, Component: Review
