### ISSUE TITLE
Newsletter Queue Start Date is always set to GMT

### ISSUE THREAD

**Issue by justin17757** [magento/magento2#35206] opened 2022-03-18 07:18 UTC
Queue Start Date always take GMT+0 time after save.

### Preconditions (*)

1. Magento version 2.4.2

### Steps to reproduce (*)

1. Magento admin login -> Marketing -> Create newsletter template
2. Select dropbox on the right of a newsletter -> Add newsletter to queue -> Page will change to Queue edit page.
3. Select date/time for field the Queue Start Date -> Save Queue
4. You will see the Start time is 0:00:00 (It always 9 hours ahead, and my local time is GMT+9)

### Expected result (*)

1. Start Time should be 9:00:00

### Actual result (*)

1. 00:00:00 after saved

**Comment by engcom-November** [comment] 2022-03-21 11:06
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-03-23 05:26
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue:
Stores - Configuration - General - Locale options - Timezone set to Korean Standard Time (GMT +9)
Marketing  - Add news template
Queue NewsLetter
Select Queue Start date and save
No issue: Queue start date is displayed as what ever selected before save and after save
![image](https://user-images.githubusercontent.com/60198231/159629779-3e7dc348-5720-4e42-bc40-b815416cd2e5.png)
![image](https://user-images.githubusercontent.com/60198231/159629814-47116fd0-be9c-4262-819e-217bbab6a661.png)
@justin17757 kindly recheck the issue on Magento 2.4-develop branch as it is the upcoming 2.4.x release and have latest code base. elaborate missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-04-06 07:56
Hi @justin17757 ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-04-06 07:56 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
