### ISSUE TITLE
error 401: oauth_problem 

### ISSUE THREAD

**Issue by horwengliang95** [magento/magento2#33724] opened 2021-08-09 09:37 UTC
### Summary (*)

I am using OAuth1.0 as the choice of authentication for integrating Warehouse Management System with the Magento. But I am experiencing issue whereby i keep on getting 401: oauth_problem=An+error+occurred+validating+the+nonce. This error message is not inside documentation hence i have limitation to debug the specific parameters to generate nonce.
This is the link that i refer to https://devdocs.magento.com/guides/v2.4/get-started/authentication/gs-authentication-oauth.html

### Examples (*)

```
    const requestURL: string = `https://https://fnlife.appscentral.net/oauth/token/request`
    const accessKey = 'exampleKey'
    const accessSecret = 'exampleSecret'
    const requestAuthorizationHeader: string = this.makeRequestAuthorizationHeader(requestURL, 'POST', accessKey)

    const requestTokenResponse = await fetch(`${requestURL}`, {
      method: 'post',
      headers: {
        Authorization: requestAuthorizationHeader,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        oauth_consumer_key: accessKey,
        oauth_consumer_secret: accessSecret
      })
    })
```

```
   makeVerificationTokenForNonce() {
    return crypto.randomBytes(16).toString('hex')
  }

  makeSignature(apiPath: string, method: string, apiKey: string, params: Parameter): string {
    var sorted = Object.entries(params)
      .map(([k, v]) => `${encodeURIComponent(k)}=${encodeURIComponent(v)}`)
      .join('&')

    sorted = method + '&' + apiPath + '&' + sorted

    return crypto.createHmac('sha1', apiKey).update(sorted).digest('hex')
  }

  makeRequestAuthorizationHeader(requestURL: string, method: string, oauthConsumerKey: string) {
    let authorizationHeader: string = 'OAuth '
    let delimiter = ''
    const signatureMethod: string = 'HMAC-SHA1'
    const nonce = this.makeVerificationTokenForNonce()
    const currentTimestamp = Date.now()
    const requestParams: any = {
      oauth_nonce: nonce,
      oauth_signature_method: signatureMethod,
      oauth_timestamp: currentTimestamp,
      oauth_version: '1.0',
      oauth_consumer_key: oauthConsumerKey
    }
    const signature = this.makeSignature(requestURL, method, oauthConsumerKey, requestParams)
    const authorizationHeaderParams: any = {
      oauth_consumer_key: oauthConsumerKey,
      oauth_signature_method: signatureMethod,
      oauth_signature: signature,
      oauth_nonce: nonce,
      oauth_timestamp: currentTimestamp,
      oauth_version: '1.0'
    }

    for (const key in authorizationHeaderParams) {
      authorizationHeader += `${delimiter}${key}=${authorizationHeaderParams[key]}`
      delimiter = ','
    }

    return authorizationHeader
}
```

### Proposed solution

I think the documentation for OAuth based Authentication need to be described in details as the sample of php script written and what has been documented are not same. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by horwengliang95** [comment] 2021-08-09 09:41
@magento give me 2.4-develop instance

**Comment by horwengliang95** [comment] 2021-08-09 16:33
@magento give me 2.4-develop instance

**Comment by sumjoekin** [comment] 2021-08-10 13:00
@magento give me 2.4-develop instance

**Comment by sumjoekin** [comment] 2021-08-13 07:00
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment] 2021-08-19 08:08
Hi @horwengliang95,

As far as documentation for OAuth based Authentication is concerned, you should be able to generate Authentication as per the steps provided in it. Request and Response descriptions are provided which are enough to get Access Token(oauth_token and oauth_token_secret). Furthermore, you can get the list of error codes for your reference from https://devdocs.magento.com/guides/v2.4/get-started/authentication/oauth-errors.html

As for error which you are getting, can you please inform if the issue is resolved ? And if not, can you please provide the **‘steps to reproduce’** so that we can try same on 2.4-develop instance ?

**Comment by sumjoekin** [comment] 2021-08-22 04:06
@magento give me 2.4-develop instance

**Comment by sumjoekin** [comment] 2021-08-22 07:31
@magento give me 2.4-develop instance

**Comment by sumjoekin** [comment] 2021-08-22 14:14
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment] 2021-09-03 06:13
Hi @horwengliang95,

Can you please update if the issue is resolved ? And if not, can you please provide the **‘steps to reproduce’** so that we can try same on 2.4-develop instance ?

Otherwise we'll have to close this issue if there is no update from the reporter.

**Comment by sumjoekin** [comment] 2021-09-04 03:36
> Hi @horwengliang95,
> 
> Can you please update if the issue is resolved ? And if not, can you please provide the **‘steps to reproduce’** so that we can try same on 2.4-develop instance ?
> 
> Otherwise we'll have to close this issue if there is no update from the reporter.


Steps to reproduce
1. Go to "System" -> "Integrations".
2. Click on "Add New Integration".
3. Fill in Name, Email, Callback URL and Identity link URL.
4. We are able to get oauth_consumer_key, oauth_consumer_secret, oauth_verifier and store_base_url from Magento.
5. After that, Magento call our system login page and we proceed with login our system.
6. After login, signature is generated based on the following params: oauth_consumer_secret, oauth_nonce: [generated with 16 random strings], oauth_signature_method: 'HMAC-SHA1', oauth_timestamp: currentTimestamp, oauth_version: '1.0'.
7. Authorization Header is created with params: oauth_consumer_secret, oauth_nonce: [generated with 16 random strings], oauth_signature_method: 'HMAC-SHA1', oauth_timestamp: currentTimestamp, oauth_version: '1.0', oauth_signature.
8. Our system calls "store_base_url/oauth/token/request" with with the generated Authorization Header and method POST to request token from Magento.

Expected results
Expected to get the following result: oauth_token=4cqw0r7vo0s5goyyqnjb72sqj3vxwr0h&oauth_token_secret=rig3x3j5a9z5j6d4ubjwyf9f1l21itrr

Actual results
Error 401: oauth_problem=An+error+occurred+validating+the+nonce

**Comment by engcom-Lima** [comment] 2021-09-09 11:51
Hi @sumjoekin,

I think your code might be trying to use same nonce-timestamp combination again and triggering the error which you are getting. Please check the error code also which you are getting for specific error details.

<img width="1062" alt="Screenshot 2021-09-09 at 5 13 09 PM" src="https://user-images.githubusercontent.com/60198022/132680031-b4d45582-0392-49a2-bc46-9d636134a2a6.png">

Please check more 401 error codes on https://devdocs.magento.com/guides/v2.4/get-started/authentication/oauth-errors.html. You can debug accordingly.

If you want Documentation to be more detailed on the topic, you can raise issue on the below link:
https://github.com/magento/devdocs/issues

Hope this helps.

**Comment by engcom-Lima** [comment] 2021-09-23 04:44
Hi @sumjoekin,

We have noticed that this issue has not been updated for some time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Lima** 2021-09-23 04:44 UTC
Labels: Issue:  Cannot Reproduce, Triage: Dev.Experience, Issue: needs update
