### ISSUE TITLE
404 Not Found css folder

### ISSUE THREAD

**Issue by kamranbhutto** [magento/magento2#22923] opened 2019-05-17 05:44 UTC
### Summary (*)

ver 2.3.1

-Added March 26, 2019

### Examples (*)

pub/static/frontend/Magento/luma/en_US/mage/calendar.css
404 Not Found

**Comment by shikhamis11** [comment] 2019-05-17 05:49
hello @kamranbhutto , did you try running upgrade and deploy commands ?

**Comment by kamranbhutto** [comment] 2019-05-17 06:29
> 
> 
> hello @kamranbhutto , did you try running upgrade and deploy commands ?

deploy

**Comment by shikhamis11** [comment] 2019-05-17 06:50
I am not able to reproduce this issue on magento 2.3.1 instance.Please share more details about the issue . also please check the same on 2.3-develop instnace If you find issue Please share screenshot also

**Comment by shikhamis11** [comment] 2019-05-21 15:57
@kamranbhutto I am closing this issue since this is not reproducible . Please share more details about the issue if you think it still exits, also please check the same on 2.3-develop instance If you find issue Please also share screenshot

**Closed as completed by shikhamis11** 2019-05-21 15:57 UTC
Labels: Issue: Format is valid
