### ISSUE TITLE
broken git repo?

### ISSUE THREAD

**Issue by simkea** [magento/magento2#2658] opened 2015-12-09 13:33 UTC
![image](https://cloud.githubusercontent.com/assets/612913/11686390/92d140d2-9e80-11e5-9521-676de4780964.png)
1. i clone the repo and change in folder magento2/
2. i check the status "git status" -> 1 file is changed! Why?!

What is going on?
br

**Comment by Vinai** [comment] 2015-12-09 13:52
In the screenshot you posted you are not running `git status` in the freshly cloned repository but in the parent directory. The `cd magento2` command is missing. So probably you are cloning the repo into another repo clone.
I tried to reproduce the issue nevertheless without success. I suspect this to be something specific to your setup. Please ask in to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/), they probably are more appropriate places for that kind of question.
I'll leave this issue open. If you think you really are encountering a bug in Magento 2, please let us know, otherwise please close this issue.

**Comment by simkea** [comment] 2015-12-09 14:04
![image](https://cloud.githubusercontent.com/assets/612913/11687267/0551255a-9e86-11e5-81c2-9a0cad771f89.png)

the complete console log... same problem

**Comment by simkea** [comment] 2015-12-09 14:04
i will check it on another machine...

**Comment by simkea** [comment] 2015-12-09 14:30
other machine, same Problem.

![image](https://cloud.githubusercontent.com/assets/612913/11687902/b5dd64ee-9e89-11e5-9df8-ceb82c452825.png)

**Comment by Vinai** [comment] 2015-12-09 14:37
Actually, I tried in a new environment and also was able to reproduce the issue. Thanks for reporting this. Not sure if this is a bug, but it is strange for sure.

**Comment by Vinai** [comment] 2015-12-09 14:40
Try searching for the full file name and in https://github.com/magento/magento2/find/develop
There are 2 matches!
Running `git diff app/code/Magento/Ui/Component/Form/Element/MultiSelect.php` shows a diff of the two files.
One of the files is named `MultiSelect.php` and one is called `Multiselect.php`. 
On a case sensitive file system that would be two files. On a case insensitive file system (Windows or OS X HFS+ default) the file that gets created last overwrites the file that gets created first during the check out.
I've added the bug label.

**Comment by simkea** [comment] 2015-12-09 14:49
I know the problem with upper and lower case. it may nevertheless not be wrong. Never change a letter to Lower or Upper and commit it. :)   ... if you have windows *fg

**Comment by ishakhsuvarov** [comment] 2015-12-09 14:59
@simkea Thank you for reporting this issue. We have created an internal ticket `MAGETWO-46718` to track the progress on this.

**Comment by steverobbins** [comment] 2015-12-10 23:04
I'm seeing this too.  Mac's come default with the main partition case insensitive.  I think the solution is to just remove one of files, since it's probably not getting loaded anyway.

**Comment by ishakhsuvarov** [comment] 2015-12-17 13:40
Closing this issue, as the fix has been delivered to the `develop` branch.

**Closed as completed by ishakhsuvarov** 2015-12-17 13:40 UTC
Labels: Issue: Ready for Work, bug report

**Comment by davidalger** [comment] 2015-12-17 16:47
@ishakhsuvarov Looks to me like the wrong file was removed. This is now the _only_ case of a file named Multiselect.php with the S capitalized. This should follow the same convention as everywhere else in the system. Will you guys consider correcting that?

``` shell
dalger:10:44 AM:/sites/m2.dev (develop) $ find . -type f -name Multiselect.php
./app/code/Magento/Customer/Model/Attribute/Data/Multiselect.php
./app/code/Magento/Customer/Model/Config/Source/Group/Multiselect.php
./app/code/Magento/Customer/Model/Metadata/Form/Multiselect.php
./app/code/Magento/Eav/Model/Attribute/Data/Multiselect.php
./lib/internal/Magento/Framework/Data/Form/Element/Multiselect.php
./vendor/magento/zendframework1/library/Zend/Form/Element/Multiselect.php
dalger:10:44 AM:/sites/m2.dev (develop) $ find . -type f -name MultiSelect.php
./app/code/Magento/Ui/Component/Form/Element/MultiSelect.php
dalger:10:44 AM:/sites/m2.dev (develop) $ 
```
