### ISSUE TITLE
Install sample data and get Fatal error: Call to undefined method Magento\Catalog\Model\Resource\Product\Interceptor::getWriteConnection

### ISSUE THREAD

**Issue by hyselab** [magento/magento2#1636] opened 2015-08-10 07:27 UTC
Hello,

When I try to install sample data via Setup Wizard at step 6:
https://cedemo2.forixstage.com/setup/index.php/install/start 
I get status of process 98 %
Console Log:
"
Installing sample data:
Installing theme:
.
Installing customers:
.
Installing CMS pages:
....
Installing catalog attributes:
...........................
Installing categories:
.........................................
Installing simple products:
"

and get response from POST request "https://cedemo2.forixstage.com/setup/index.php/install/start "
"<br />
<b>Fatal error</b>:  Call to undefined method Magento\Catalog\Model\Resource\Product\Interceptor::getWriteConnection
() in <b>/home/cedemo2/www/app/code/Magento/SampleData/Module/Catalog/Setup/Product/Gallery.php</b> on
 line <b>144</b><br />
"

Everyone, could you help me to resolve it?

**Comment by kandy** [comment] 2015-08-10 07:40
Duplicate of #1610

**Comment by mazhalai** [comment] 2015-08-10 13:50
@hyselab please try with the master branch instead of develop branch.

**Comment by eugenbg** [comment] 2015-08-13 11:59
doesn't help with master branch, getting this

Declaration of Magento\Store\Model\StoreManagerInterface\Proxy::getGroups() must be compatible with Magento\Store\Model\StoreManagerInterface::getGroups($withDefault = false, $codeKey = false) in /vagrant/httpdocs/projects/magento2/var/generation/Magento/Store/Model/StoreManagerInterface/Proxy.php on line 8
PHP Stack trace:
PHP   1. {main}() /vagrant/httpdocs/projects/magento2/bin/magento:0
PHP   2. Symfony\Component\Console\Application->__construct() /vagrant/httpdocs/projects/magento2/bin/magento:17
PHP   3. Magento\Framework\Console\Cli->getDefaultCommands() /vagrant/httpdocs/projects/magento2/vendor/symfony/console/Symfony/Component/Console/Application.php:91
PHP   4. Magento\Framework\Console\Cli->getApplicationCommands() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/Console/Cli.php:31
PHP   5. Magento\Framework\ObjectManager\ObjectManager->create() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/Console/Cli.php:68
PHP   6. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:57
PHP   7. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:84
PHP   8. Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:53
PHP   9. Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:249
PHP  10. Magento\Framework\ObjectManager\ObjectManager->get() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:273
PHP  11. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:71
PHP  12. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:84
PHP  13. Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:53
PHP  14. Magento\Framework\ObjectManager\ObjectManager->get() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:236
PHP  15. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:71
PHP  16. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:84
PHP  17. Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:53
PHP  18. Magento\Framework\ObjectManager\ObjectManager->get() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:236
PHP  19. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:71
PHP  20. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:84
PHP  21. Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:53
PHP  22. Magento\Framework\ObjectManager\ObjectManager->get() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:236
PHP  23. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:71
PHP  24. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:84
PHP  25. Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:53
PHP  26. Magento\Framework\ObjectManager\ObjectManager->get() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:236
PHP  27. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:71
PHP  28. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:84
PHP  29. Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:53
PHP  30. Magento\Framework\ObjectManager\ObjectManager->get() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:236
PHP  31. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:71
PHP  32. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:84
PHP  33. Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:53
PHP  34. Magento\Framework\ObjectManager\ObjectManager->get() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:236
PHP  35. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:71
PHP  36. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:84
PHP  37. Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:53
PHP  38. Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:249
PHP  39. Magento\Framework\ObjectManager\ObjectManager->get() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:273
PHP  40. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:71
PHP  41. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:84
PHP  42. Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:53
PHP  43. Magento\Framework\ObjectManager\ObjectManager->get() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:236
PHP  44. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:71
PHP  45. Magento\Framework\ObjectManager\Definition\Runtime->getParameters() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:73
PHP  46. Magento\Framework\Code\Reader\ClassReader->getConstructor() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php:44
PHP  47. ReflectionClass->__construct() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:19
PHP  48. spl_autoload_call() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:19
PHP  49. Composer\Autoload\ClassLoader->loadClass() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:0
PHP  50. Composer\Autoload\includeFile() /vagrant/httpdocs/projects/magento2/vendor/composer/ClassLoader.php:301
PHP  51. include() /vagrant/httpdocs/projects/magento2/vendor/composer/ClassLoader.php:412
www-data@server:/vagrant/httpdocs/projects/magento2/bin$ clear
www-data@server:/vagrant/httpdocs/projects/magento2/bin$ ./magento sampledata:install admin
PHP Fatal error:  Declaration of Magento\Store\Model\StoreManagerInterface\Proxy::getGroups() must be compatible with Magento\Store\Model\StoreManagerInterface::getGroups($withDefault = false, $codeKey = false) in /vagrant/httpdocs/projects/magento2/var/generation/Magento/Store/Model/StoreManagerInterface/Proxy.php on line 8
PHP Stack trace:
PHP   1. {main}() /vagrant/httpdocs/projects/magento2/bin/magento:0
PHP   2. Symfony\Component\Console\Application->__construct() /vagrant/httpdocs/projects/magento2/bin/magento:17
PHP   3. Magento\Framework\Console\Cli->getDefaultCommands() /vagrant/httpdocs/projects/magento2/vendor/symfony/console/Symfony/Component/Console/Application.php:91
PHP   4. Magento\Framework\Console\Cli->getApplicationCommands() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/Console/Cli.php:31
PHP   5. Magento\Framework\ObjectManager\ObjectManager->create() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/Console/Cli.php:68
PHP   6. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:57
PHP   7. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:84
PHP   8. Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:53
PHP   9. Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:249
PHP  10. Magento\Framework\ObjectManager\ObjectManager->get() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:273
PHP  11. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:71
PHP  12. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:84
PHP  13. Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:53
PHP  14. Magento\Framework\ObjectManager\ObjectManager->get() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:236
PHP  15. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:71
PHP  16. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:84
PHP  17. Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:53
PHP  18. Magento\Framework\ObjectManager\ObjectManager->get() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:236
PHP  19. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:71
PHP  20. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:84
PHP  21. Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:53
PHP  22. Magento\Framework\ObjectManager\ObjectManager->get() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:236
PHP  23. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:71
PHP  24. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:84
PHP  25. Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:53
PHP  26. Magento\Framework\ObjectManager\ObjectManager->get() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:236
PHP  27. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:71
PHP  28. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:84
PHP  29. Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:53
PHP  30. Magento\Framework\ObjectManager\ObjectManager->get() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:236
PHP  31. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:71
PHP  32. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:84
PHP  33. Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:53
PHP  34. Magento\Framework\ObjectManager\ObjectManager->get() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:236
PHP  35. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:71
PHP  36. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:84
PHP  37. Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:53
PHP  38. Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:249
PHP  39. Magento\Framework\ObjectManager\ObjectManager->get() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:273
PHP  40. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:71
PHP  41. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:84
PHP  42. Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:53
PHP  43. Magento\Framework\ObjectManager\ObjectManager->get() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:236
PHP  44. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:71
PHP  45. Magento\Framework\ObjectManager\Definition\Runtime->getParameters() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:73
PHP  46. Magento\Framework\Code\Reader\ClassReader->getConstructor() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php:44
PHP  47. ReflectionClass->__construct() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:19
PHP  48. spl_autoload_call() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:19
PHP  49. Composer\Autoload\ClassLoader->loadClass() /vagrant/httpdocs/projects/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php:0
PHP  50. Composer\Autoload\includeFile() /vagrant/httpdocs/projects/magento2/vendor/composer/ClassLoader.php:301
PHP  51. include() /vagrant/httpdocs/projects/magento2/vendor/composer/ClassLoader.php:412

**Comment by mazhalai** [comment] 2015-08-13 14:41
@eugenbg please clear your `var/generation` folder and try again.

**Comment by markoshust** [comment] 2015-08-19 22:14
Cleared `var/generation` and getting this error now:
`PHP Fatal error:  Cannot instantiate interface Magento\Store\Api\StoreRepositoryInterface in /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php on line 7`

**Comment by mazhalai** [comment] 2015-08-20 15:49
@markoshust `develop` branch is `WIP` and `master` is the stable version.

**Comment by piotrekkaminski** [comment] 2015-10-03 18:28
This should be fixed now.

**Closed by piotrekkaminski** 2015-10-03 18:28 UTC
Labels: bug, MX
