### ISSUE TITLE
The class name «\Magento\Catalog\Setup\CategorySetup» is misleading because the class is used for both the products and categories equally

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2162] opened 2015-10-22 22:58 UTC
https://github.com/magento/magento2/blob/0be91a56d050791ac0b67a47185d79df31e79329/app/code/Magento/Catalog/Setup/CategorySetup.php#L337

Similar to https://github.com/magento/magento2/issues/2163

**Comment by wojtekn** [comment] 2015-10-23 06:37
It's already reported https://github.com/magento/magento2/issues/1915

**Comment by davidalger** [comment] 2015-11-10 20:11
Closed as duplicate of #1915

**Closed by davidalger** 2015-11-10 20:11 UTC
