### ISSUE TITLE
Quantity change of Cart-Item clears Cart

### ISSUE THREAD

**Issue by akimo** [magento/magento2#22137] opened 2019-04-03 14:11 UTC
### Preconditions (*)

1. Magento Version 2.3.1
2. PHP 7.2

Upgraded from 2.3.0 - version without this issue

### Steps to reproduce (*)
1. Put something in the cart
2. go to cart page
3. change the Quantity of a Cart Item
4. Press "Return" Key

This is reproducible, also when removing client storage and cookies. As Guest or Logged in Customer. 

### Expected result (*)

The cart-page should be reloaded with the modified quantities of items.

### Actual result (*)

Your Cart is empty and a Message is displayed, which tells you that you don't have any items in your cart.

**Comment by akimo** [comment] 2019-04-03 14:17
@magento-engcom-team give me 2.3.1 instance

**Comment by magento-engcom-team** [comment] 2019-04-03 14:17
Hi @akimo. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by magento-engcom-team** [comment] 2019-04-03 14:18
Hi @akimo, here is your [Magento instance](https://i-22137-2-3-1.instances.magento-community.engineering).
Admin access: [https://i-22137-2-3-1.instances.magento-community.engineering/admin](https://i-22137-2-3-1.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by akimo** [comment] 2019-04-03 14:25
@magento-engcom-team Yes, i can confirm that the bug is reproducible on the vanilla Magento instance

**Comment by akimo** [comment] 2019-04-03 15:00
Reason: The "return" key invokes the submit action of the Form. The "submit" action is bound to the Button "Clear Shopping Cart".

**Comment by shikhamis11** [comment] 2019-04-03 17:31
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-04-03 17:31
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-03 17:32
Hi @shikhamis11, here is your [Magento instance](https://i-22137-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22137-2-3-develop.instances.magento-community.engineering/admin](https://i-22137-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2019-04-11 18:04
@akimo I am not able to reproduce this issue based on provided steps on current magento 2.3-develop instance let me know if it requires any additional step to reproduce the issue

**Comment by akimo** [comment] 2019-04-11 18:36
This issue is new in 2.3.1 and not present in 2.3.0 (I don't know which version "2.3-develop" is  based on). You need to press the return key while the cursor is still in the quantity field. 
The Problem is caused by the Button "Clear Shopping Cart" which is of type="submit". If you press return the form will perform a "submit".

**Comment by chichitsai0517** [comment] 2019-04-12 14:54
I have exactly the same issue! I installed a fresh copy of Magento 2.3.1 with sample data just to test and like you mentioned, the cart empties after hitting the "ENTER" key.
I would really love to find a way to fix this!

**Comment by Mobecls** [comment] 2019-04-13 14:08
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-04-13 14:09
Hi @Mobecls. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-13 14:09
Hi @Mobecls, here is your [Magento instance](https://i-22137-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22137-2-3-develop.instances.magento-community.engineering/admin](https://i-22137-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Mobecls** [comment] 2019-04-13 14:23
@akimo - wasn't able to reproduce it neither on 2.3-develop, nor on 2.3.1 latest official release.

1. Added product to a cart (10 pcs)
2. Proceeded to a cart page
3. changed product qty to 5 and hit "update shopping cart" 
4. clicked on browser Return button (verified on latest Chrome and Safari on Mac).

The shopping cart had 5pcs (no products were flushed from a cart)...

**Comment by chichitsai0517** [comment] 2019-04-13 14:38
Hi, this is weird. Is this 2.3.1? I have a website upgraded from 2.2.6 to 2.3.1 that does that. So I installed a fresh copy of the magento 2.3.1 with sample data  and it also does the same. Am I able to message someone with the the cpanel and admin credentials to see?

**Comment by Mobecls** [comment] 2019-04-13 15:06
@chichitsai0517 please, see if you can reproduce it here - https://i-22137-2-3-develop.instances.magento-community.engineering it's still up and running.

**Comment by chichitsai0517** [comment] 2019-04-13 15:23
Hi Mobecls, I tried on yours and it does not do the same as mine. I don't understand because my test website has no extensions and no themes. It is the original 2.3.1 with sample data.

**Comment by Mobecls** [comment] 2019-04-13 15:29
@chichitsai0517 - that's our latest environment, so if it is not getting reproduced there - it's either an environment issue. If you don't have any additional info on how to reproduce it here - please, close the issue.

**Comment by chichitsai0517** [comment] 2019-04-13 15:30
Do you think this is a PHP Version issue? I just checked on my hosting account and they only have PHP 7.1.27 or 7.2.16.
I am using PHP 7.2.16.
However on Magento 2.3.X Stack technology requirements, it says that we should be using PHP 7.2.11

**Comment by hostep** [comment] 2019-04-14 08:11
I can very easily reproduce this as well on a vanilla Magento 2.3.1 installed using composer. This isn't an environment issue.
@Mobecls: your steps to reproduce are incorrect. You shouldn't press the `Update Shopping Cart` button, you should simply increase the qty of an item in the cart and then press the enter/return key while the focus of your cursor is still in the qty field to confirm the change.

**Comment by hostep** [comment] 2019-04-14 08:25
This is fixed in 2.3-develop however, and I've found a PR which fixes it: https://github.com/magento/magento2/pull/21509

So we can close this issue, since it duplicates https://github.com/magento/magento2/issues/21499 and was fixed by https://github.com/magento/magento2/pull/21509 and the fix should get released in Magento 2.3.2 & 2.2.9.

**Closed as completed by hostep** 2019-04-14 08:25 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid, Event: cdkyiv2019

**Comment by lupoiuAlinN** [comment] 2019-12-18 16:02
If you still have this issue you have to know that on a html form the first element witch has type submit on it will be called when "enter" is hit. So in magento the first element on the form with type submit is the clear button. To solve this issue you can modify the order of the buttons in Magento_Checkout/templates/cart/form.phtml  ( put update button before clear button)
