### ISSUE TITLE
Re-opening #11648: Product Use Default Value not selected when linking to non-default websites

### ISSUE THREAD

**Issue by Tjab** [magento/magento2#11768] opened 2017-10-26 11:28 UTC
@lanken agento-engcom-team, thank you for your very fast reply!

ps: I couldn't re-open my issue, so I've created a new one. Previous issue: https://github.com/magento/magento2/issues/11648

I'm wondering why it's not possible to reproduce this, so I've written down all my steps and included screenshots. Please note that this was tested on 2.1.5. I do however believe it's also the case with some customers of ours, who run newer versions.

### Preconditions
1.  Magento 2.4-develop
2. Two websites, with two store views each
 - Website A - DEFAULT
   - Store View ASV1 - DEFAULT
   - Store View ASV2
 - Website B
   - Store View BSV1
   - Store View BSV2
3. Postman

### Steps to reproduce
1. #### POST to /V1/products/
```json
{
  "product": {
        "sku": "TEST_ISSUE",
        "name": "Testing my issue",
        "price": 10.00,
        "status": 1,
        "type_id": "simple",
        "attribute_set_id":4,
        "weight": 1
    }
}
```
- - #### Result in my shop
![image](https://user-images.githubusercontent.com/6023513/31990611-e259fbaa-b975-11e7-840d-d306d0626233.png)

- - ##### Main Website
- - - Default Store View `Use Default Value` check boxes ticked
- - - Extra Store View Under Default `Use Default Value` check boxes ticked

2. #### POST to /V1/products/TEST_ISSUE/websites
```json
{
  "productWebsiteLink": {
        "sku": "TEST_ISSUE",
        "website_id": 2
    }
}
```

- - #### Result in my shop
![image](https://user-images.githubusercontent.com/6023513/31991717-b9ded300-b978-11e7-8fbd-9c7a22e0d283.png)

 - - ##### Main Website
- - - Default Store View some `Use Default Value` check boxes **NOT** ticked
- - - Extra Store View Under Default `Use Default Value` check boxes ticked

- - ##### website2
- - - Storeview W2`Use Default Value` check boxes ticked

### Expected result
`Use Default Value` boxes are checked on all views

### Actual result
Notice the difference between the two screenshots. I've added it to `website_id = 2`, and some `Use Default Value` boxes are unchecked in the default store view.

**Comment by magento-engcom-team** [comment] 2017-10-27 15:24
Hello @Tjab. Could You please specify what did You mean under "description" in  #11648 - the Description of the product which along with Short Description stands as a separate attribute of the product (belongs to Content section of the product page) or simply the name of the product (Product Name). Thank You.

**Comment by magento-engcom-team** [comment] 2017-10-31 08:40
@Tjab, thank you for your report.
We've created internal ticket(s) MAGETWO-83044 to track progress on the issue.

**Comment by peterjaap** [comment] 2018-03-01 13:10
@okorshenko Oleksii do you have an update on this? It's been a while...

**Comment by dwaynebartels** [comment] 2018-05-08 07:49
Please update this issue.

**Comment by abontjer** [comment] 2019-05-09 04:41
Can you please give an update on this issue

**Comment by Tjab** [comment] 2019-09-24 11:35
Again a few months later; can we get an update?

**Comment by magento-engcom-team** [comment] 2019-12-26 11:43
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30085` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment] 2020-10-29 14:52
@Tjab @hostep 

This issue has been closed and for some reason, bot did not leave a comment.

I see that related internal ticket `MC-30085` was closed by Magento team with resolution
> Cannot reproduce on 2.4.1

So, probably it was fixed in some other PR or task.

@engcom-Delta, could you please quick re-check  it and confirm its cannot repro or reopen

**Comment by hostep** [comment] 2020-10-29 19:14
This issue sounds very similar to https://github.com/magento/magento2/issues/30047#issuecomment-715498108, but this one is about products and the other one about categories. I can see some code was delivered to fix this issue with categories, but not yet for products. So maybe this is closed incorrectly?

Also, this sounds like a duplicate of https://github.com/magento/magento2/issues/26484 & https://github.com/magento/magento2/issues/9186

**Comment by engcom-Delta** [comment] 2020-11-03 10:08
Issue is reproducible on latest 2.4-develop

**Comment by magento-engcom-team** [comment] 2020-11-03 10:10
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30085` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by glo81187** [comment] 2023-06-28 09:03
@magento  give me 2.4.5-p3 instance

**Comment by engcom-Hotel** [comment] 2023-06-28 09:29
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment] 2024-07-30 11:47
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment] 2024-07-30 13:31
Hi @Tjab ,

Thanks for your reporting and collaboration.
We have verified the issue in latest 2.4-develop instance and the issue is not reproducible. Kindly refer the screenshots.

**Steps to reproduce** - 
1. Create 2 Websites and 2 Store Views
![image](https://github.com/user-attachments/assets/7c837cd8-0098-4e90-a2cc-fe5b8cce07df)
2. Create a product and assign to website 1
![image](https://github.com/user-attachments/assets/42439bf5-d846-4a69-a866-399161bb2c66)
3. Observe checkbox is selected for default value
![image](https://github.com/user-attachments/assets/732872b5-9b8e-47cb-b29f-2cf05c50a3cb)
![image](https://github.com/user-attachments/assets/3b88a35b-499e-43ff-95bb-c99faa4d895a)
4. Link respective product to website 2
![image](https://github.com/user-attachments/assets/a6fcfd3f-3f19-44a9-8894-165280d83d3a)
5. Reload the product and observe checkbox is selected for default value
![image](https://github.com/user-attachments/assets/7320f8f2-049f-4d96-80a6-cb5c8367b70d)
![image](https://github.com/user-attachments/assets/0012147c-0123-479d-aeb5-1c634dea4bfd)

Default values are selected as expected. Kindly recheck the issue on latest Magento 2.4-develop instance and Please let us know if you are still facing any issue.

Thanks.

**Closed as completed by engcom-Delta** 2024-07-30 13:31 UTC
Labels: Component: Catalog, Issue: Confirmed, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P2, Severity: S2, Progress: done, Area: Product
