### ISSUE TITLE
Encrypted scope-specific config values fail to decrypt on PHP7

### ISSUE THREAD

**Issue by zack6849** [magento/magento2#8591] opened 2017-02-17 13:25 UTC
It seems that scope based config fails to decrypt data on anything but the default store

We first noticed this when all of our stores apart from the default one failed to process paypal transactions. After further editing of the code so that we could actually see the username and password information being sent to paypal, we discovered the username field is blank, and the password field is garbled garbage data, which leads me to assume it's failed decryption.

I thought it might've just been leaving it encrypted, so i edited the code and told it to decrypt the already supposedly decrypted value, to no avail, so as of now it seems that PayPal  on multi-store setups running 2.1.4 on PHP7 won't function (**assuming that the PayPal account details are different than the default store, of course**)

We couldn't find anything about others having this issue via google, which was quite surprising to me, so if you need any more information please don't hesitate to ask

### Preconditions

1.  Magento v2.1.4
2. PHP v7.0.6 on Ubuntu

### Steps to reproduce

1.  Change PayPal password of non-default store
2.  Attempt to checkout
3.  User authentication unsuccessful

### Expected result

1.  A successful transaction

### Actual result

1. The user field is blank, and the password field is garbed nonsense, from what I can only assume is a fail to decrypt (EG: c▒^`▒▒XP)

This issue feels quite similar to issues #2984 and #3305

**Comment by zack6849** [comment] 2017-03-30 15:22
@magento-team can we get an update on this?

**Comment by zack6849** [comment] 2017-05-23 16:54
@okolesnyk i don't like pinging people by name for attention or anything but this has been more than 3 months and we haven't even gotten an acknowledgment, this issue breaks paypal on multistore without workarounds, have you guys had a chance to even glance at this issue yet?

**Comment by magento-engcom-team** [comment] 2017-10-19 11:17
@zack6849 , thank you for your report.
Unfortunately, I could not reproduce the issue as you described it.
At step 1. I can not see the ability to change PayPal password for store.
![paypal](https://user-images.githubusercontent.com/31669971/31768418-0bef8162-b4d8-11e7-8e93-cbe847328d0b.png)


Please provide more detailed steps to reproduce.

**Comment by zack6849** [comment] 2017-10-19 12:47
This is with the PayFlow methods, not express checkout.

**Comment by magento-engcom-team** [comment] 2017-10-27 11:54
@zack6849 Thanks for the feedback.
Unfortunately, as for PayPal express checkout I cannot see the ability to change password for Payflow(Payflow Pro or Payflow Link) nor for any others PayPal payments methods in store scope either.
![payflow pro](https://user-images.githubusercontent.com/11520943/32102546-81656576-bb25-11e7-99cc-7ff74f52a438.png)
![payflow link](https://user-images.githubusercontent.com/11520943/32102549-857c4a94-bb25-11e7-82fa-7a8f3fb14a0e.png)
And in case, I do same on website scope instead of store, I get successful transaction.
Please add more details to your description of the steps you followed when identifying this issue. Screenshots or logs would be helpful, too.

**Comment by magento-engcom-team** [comment] 2017-11-10 11:30
@zack6849, thank you for your report.
We've created internal ticket(s) MAGETWO-83646 to track progress on the issue.

**Comment by zack6849** [comment] 2017-11-10 11:58
Glad to hear you guys were able to reproduce it.

**Comment by magento-engcom-team** [comment] 2018-04-13 06:47
Hi @zack6849 Thank you for reporting.
Issue has been fixed in `2.1` and `2.2`. Most likely fix is going to be released with `2.2.4`.
Thanks.

**Closed as completed by magento-engcom-team** 2018-04-13 06:47 UTC
Labels: Issue: Ready for Work, bug report, Component: Payment, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.1.x, Fixed in 2.2.x, Issue: Format is valid, Event: distributed-cd
