### ISSUE TITLE
Miinicart empty after Currency Switcher

### ISSUE THREAD

**Issue by niku0911** [magento/magento2#33154] opened 2021-06-05 08:36 UTC
### Preconditions (*)
1. Magento 2.3.6
2. PHP 7.2

### Steps to reproduce (*)
1. Create Multiple Currency Switcher in backend
2. Frontend add product in cart 
3.  Change currency switcher 
4. Minicart showing emtu results
5.  after add another product in cart than show 2 items

### Expected result (*)
1.  need to show 1st item when currency changed

### Actual result (*)
1. Minicart showing emty result

Please help on this issue,

**Comment by krishprakash** [comment] 2021-06-07 09:37
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment] 2021-06-07 09:53
Hi @niku0911. Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop by following steps from this ticket. 
Looks like you miss some important preconditions, steps so may you please recheck and update description?

**Comment by krishprakash** [comment] 2021-06-09 04:32
Hi @niku0911. Thanks for your confirmation
We will proceed the ticket if its fixed in latest version so closing this ticket

**Closed as completed by krishprakash** 2021-06-09 04:32 UTC
Labels: Progress: needs update, Issue: ready for confirmation
