### ISSUE TITLE
Product Fields Auto-Generation Including HTML for meta fields

### ISSUE THREAD

**Issue by nigelcopley** [magento/magento2#4411] opened 2016-05-05 18:17 UTC
When  reviewing products on the live site, i can see that the meta desciption is being generated to include html tags rather than just plain text which results in a random display of content on product pages.

![image](https://cloud.githubusercontent.com/assets/1584853/15052462/c4fcf422-12f5-11e6-93cc-494a7a762458.png)

![image](https://cloud.githubusercontent.com/assets/1584853/15052515/00c64364-12f6-11e6-983a-9efb2c06fff9.png)

**Comment by MauroNigrele** [comment] 2016-05-26 15:50
+1 
By default auto settings feature copy the entire description to meta-description including tags, fast solution should be remove/filter in attribute backend (before save)

**Comment by andimov** [comment] 2016-08-16 15:47
@caleoroco
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, provide the used version also. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by maurolm** [comment] 2016-08-29 09:46
+1
magento 2.0.9

steps to reproduce:
1. create a new product and insert a description with some html code inside
2. save the product
3. check the field "meta description", it contains some html tags

I think while copying the data from description it should clean the code

**Comment by IlnitskiyArtem** [comment] 2017-06-29 15:04
Thanks for reporting this issue. 
This ticket is a duplicate #5299

**Comment by veloraven** [comment] 2017-06-30 05:58
I'm closing this issue as not a bug.
Please see additional information in #5299

**Closed as completed by veloraven** 2017-06-30 05:58 UTC
Labels: bug report
