### ISSUE TITLE
Can't upload images for configurable children within the variation-steps-wizard after upgrade to Magento 2.4.7

### ISSUE THREAD

**Issue by budoland-ab** [magento/magento2#39091] opened 2024-08-22 11:19 UTC
### Preconditions and environment

- Magento version: 2.4.7

### Steps to reproduce

1. Navigate to configurable product or create a new one
2. Create Variations with the Variation Wizard
3. Select image upload based on attributes
4. Try to upload one or multiple images

### Expected result

The images should be shown and uploaded

### Actual result

Noting happens

### Additional information

If you try to drag and drop the images the loader.gif is showing and an error in the console is thrown:

![error](https://github.com/user-attachments/assets/31736245-529b-4a63-b1d6-5f28bb2d73f3)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-08-29 05:31
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-08-29 08:14
Hi @budoland-ab,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

![COnfigureeee-Products-Inventory-Catalog-Magento-Admin](https://github.com/user-attachments/assets/56fed185-2e2e-461d-8d16-702f886bd603)


The images was shown and uploaded successfully.

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-09-09 06:14
Hi @budoland-ab,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-09-09 06:14 UTC
Labels: Issue: needs update, Reported on 2.4.7
