### ISSUE TITLE
if edit product show "A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later."

### ISSUE THREAD

**Issue by raghav111jain** [magento/magento2#30229] opened 2020-09-29 08:36 UTC
### Preconditions (*)

1. magento 2.3
2.php 7.3

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**when you edit and show ""A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later." so how to solved please let me know ASAP**
![image](https://user-images.githubusercontent.com/53876757/94533617-01c78880-025d-11eb-9e3c-564c3e57c46d.png)

**Comment by krishprakash** [comment] 2020-09-29 08:54
Hi @raghav111jain. Thank you for your report.
In which case you phase the issue like any specific scenario after add and edit product. Kindly update with proper format as per [issue reporting guidelines](https://github.com/magento/magento2/issues)

**Comment by krishprakash** [comment] 2020-09-29 09:22
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment] 2020-09-29 09:37
Hi @raghav111jain. Can not able to reproduce the issue on latest 2.4-develop instance
It may be fixed in updated version
Feel free to reopen the issue if you confirm issue reproduced on 2.4-develop branch 
Thank you!!

**Closed as completed by krishprakash** 2020-09-29 09:37 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid, Progress: done, Reported on 2.3.x

**Comment by nickpiro** [comment] 2021-03-03 15:43
So "It's not happening in 2.4-develop instance" is the answer to people using 2.3.6?! We're not ready to upgrade. What about those using 2.3.6? This is clearly an issue and should still be open.
