### ISSUE TITLE
Exporting Products

### ISSUE THREAD

**Issue by MahamMubashir** [magento/magento2#34146] opened 2021-09-23 05:01 UTC
**Summary of the issue**
While exporting the products via stock inventory the deleted products are also shown in the exported CSV.

**Information on your environment**
Magneto 2.4.2
Php 7.4

**Steps to reproduce**

- Add a dummy product in Catalog->Products->Add Product
- Export the products via Stock Inventory System->DataTransfer->Export (Entity Type-> Stock Inventory)-> Continue (It includes the new product)
- Delete the product
- Again export the products via Stock Inventory

**Expected results**
The exported file must not include deleted products.

**Actual results**
The exported file also includes the deleted products

Can anyone help me with it, please?

**Comment by ajijshekh123** [comment] 2021-09-23 06:44
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment] 2021-09-23 07:26
Hi @MahamMubashir,
Once I have export the Stock Inventory, Default Magento doesn't provide the Export the CSV file. So Not able to verify the issue on Default Magento 2.4 Instance.
Thanks.

**Comment by MahamMubashir** [comment] 2021-09-24 07:24
@ajijshekh123 

- Add a dummy product in Catalog->Products->Add Product
- Export the products via Stock Inventory System->DataTransfer->Export (Entity Type-> Stock Inventory)-> Continue (It includes the new product)
- Delete the product
- Again export the products via Stock Inventory System->DataTransfer->Export (Entity Type-> Stock Inventory)-> Continue (It includes the deleted product)
- Run cron so that export must be visible.

Default magento enables us to export CSV, just run the cron once that it must we visible in the coloumn.

Thank You

**Comment by ajijshekh123** [comment] 2021-09-27 07:11
Hi @MahamMubashir,
I have verified this issue as per your above steps. This issue is reproduced on "Magento ver. 2.3.5-p2".
After delete the product, The product is showing on CSV file.
Thanks.

**Comment by engcom-Bravo** [comment] 2024-09-03 11:42
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-09-03 11:58
Hi @MahamMubashir,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.hence we are closing this issue.please feel free to reopen the issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-09-03 11:58 UTC
Labels: Issue: Confirmed, Component: CatalogImportExport, Component: Admin, Reproduced on 2.4.x, Priority: P2, Reproduced on 2.3.5p2, Progress: done, Issue: ready for confirmation, Area: Import / export
