### ISSUE TITLE
Cms module collections missing event prefix

### ISSUE THREAD

**Issue by extroniks** [magento/magento2#9900] opened 2017-06-10 14:32 UTC
### Preconditions

1. Magento 2.1.7 CE

### Steps to reproduce

1. Try to observe events: cms_page_collection_load_before, cms_page_collection_load_after, cms_block_collection_load_before, cms_block_collection_load_after

### Expected result

1. Event is dispatched and listeners execute

### Actual result

1. Listeners aren't executed because the collections are missing the event prefix

Code lines to reproduce:
```
/* @var \Magento\Cms\Model\ResourceModel\Page\Collection $collection */
$collection = $this->_objectManager
    ->create(\Magento\Cms\Model\ResourceModel\Page\Collection::class);
$collection->load();

/* @var \Magento\Cms\Model\ResourceModel\Block\Collection $collection */
$collection = $this->_objectManager
    ->create(\Magento\Cms\Model\ResourceModel\Block\Collection::class);
$collection->load();
```

**Comment by magento-engcom-team** [comment] 2017-09-25 07:08
We updated issue description:

> Code lines to reproduce:
> ```
> /* @var \Magento\Cms\Model\ResourceModel\Page\Collection $collection */
> $collection = $this->_objectManager
>     ->create(\Magento\Cms\Model\ResourceModel\Page\Collection::class);
> $collection->load();
> 
> /* @var \Magento\Cms\Model\ResourceModel\Block\Collection $collection */
> $collection = $this->_objectManager
>     ->create(\Magento\Cms\Model\ResourceModel\Block\Collection::class);
> $collection->load();
> ```

**Comment by magento-engcom-team** [comment] 2017-09-25 22:00
@StefanErakovic, thank you for your report.
We've created internal ticket(s) MAGETWO-77434 to track progress on the issue.

**Comment by okorshenko** [comment] 2017-10-03 21:23
we need to backport this into 2.2-develop

**Comment by okorshenko** [comment] 2017-10-04 14:35
The issue needs to be assigned to @convenient

**Comment by okorshenko** [comment] 2017-10-04 15:03
@convenient is working on it #SQUASHTOBERFEST

**Comment by magento-team** [comment] 2017-10-04 22:45
Internal ticket to track issue progress: MAGETWO-80885

**Comment by okorshenko** [comment] 2017-10-04 22:46
@StefanErakovic thank you for your report. The issue is already fixed in 2.2-develop branch (PR: #11223  by @convenient ) and will be available in the Magento 2.2.2 release

**Closed as completed by okorshenko** 2017-10-04 22:46 UTC
Labels: Issue: Ready for Work, bug report, Component: Cms, Issue: Clear Description, Issue: Format is valid
