### ISSUE TITLE
Checkout loader mask remains indefinitely if terms and conditions box is unchecked

### ISSUE THREAD

**Issue by g-anedda** [magento/magento2#26797] opened 2020-02-10 16:43 UTC
### Preconditions (*)

1. Magento 2.3.3-p1
2. Use Braintree payment method
3. Have terms and conditions on payment page, with manual option to check

### Steps to reproduce (*)

1. Have 3D Secure enabled on Braintree payment method
2. Fill all data for shipping and billing, leaving the Terms and Conditions checkbox **unchecked**
3. Try to place the order

### Expected result (*)

1. The loader mask should appear after the click to place the order
2. The validation should fail because of the unchecked t&c box
3. The loader mask should disappear
4. The message "This is a required field." in red should appear near the t&c checkbox

### Actual result (*)

1. The loader mask remains in place
2. Underneath the mask the red label "This is a required field." is visible, but no operation is allowed because the loader mask is still in place

![screen](https://user-images.githubusercontent.com/52075353/74173072-54e6bf80-4c29-11ea-93cc-47da59ba51bd.PNG)

**Comment by ganedda-softfobia** [comment] 2020-02-10 16:43
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-10 16:43
Hi @ganedda-softfobia. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-10 16:44
Hi @ganedda-softfobia, here is your [Magento instance](https://i-26797-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26797-2-4-develop.instances.magento-community.engineering/admin_a70b](https://i-26797-2-4-develop.instances.magento-community.engineering/admin_a70b)
Login: `75d1ea64` Password: `b62541446c9c`
Instance will be terminated in up to 3 hours.

**Comment by ganedda-softfobia** [comment] 2020-02-10 17:04
I am able to reproduce issue on magento vanilla instance.

**Comment by ajijshekh123** [comment] 2020-02-13 05:09
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-13 05:09
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-13 05:10
Hi @ajijshekh123, here is your [Magento instance](https://i-26797-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26797-2-4-develop.instances.magento-community.engineering/admin_1cee](https://i-26797-2-4-develop.instances.magento-community.engineering/admin_1cee)
Login: `162350fa` Password: `6d3edb22a9af`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2020-02-13 05:51
Hi @ganedda-softfobia,
I have reproduced this issue in default Magento 2.4 Instance as per defined steps.
**See attached the video:**

![Payment_T C_Issue](https://user-images.githubusercontent.com/24711761/74405375-f3a23480-4e52-11ea-9339-97753d4c34d1.gif)

Thanks.

**Comment by magento-engcom-team** [comment] 2020-02-13 05:53
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31471` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2020-06-16 13:51
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-31471).

**Comment by magento-engcom-team** [comment] 2020-06-16 13:51
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-31471).

**Comment by magento-engcom-team** [comment] 2020-06-16 13:52
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-31471).

**Comment by magento-engcom-team** [comment] 2020-06-16 13:52
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-31471).

**Comment by magento-engcom-team** [comment] 2020-06-16 13:53
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-31471).

**Comment by magento-engcom-team** [comment] 2020-06-16 13:53
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-31471).

**Comment by sdzhepa** [comment] 2020-08-17 20:27
Hello @g-anedda

Thank you for your report and collaboration!

Unfortunately, we are closing this Issue report because we are not able to process contribution to the `2.3.x` release line through this public repository. See details [Code Contributions: Accepted pull requests and ported code](https://devdocs.magento.com/contributor-guide/contributing.html#rules)
And starting from `2.4.0` release, code related to this payment was removed for Magento code-base:
[Magento Commerce 2.4.0 Release Notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-commerce.html)
> With this release, the Authorize.Net, Braintree, eWay, CyberSource, and Worldpay payment method integrations have been removed from core code. Merchants should migrate to the official extensions that are available on the Magento Marketplace.

[Deprecation of Magento core payment integrations](https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445)

All questions, reports should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page

**Closed as completed by sdzhepa** 2020-08-17 20:27 UTC
Labels: Issue: Ready for Work, Component: Checkout, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Braintree, Reproduced on 2.4.x, Reported on 2.3.3-p1
