### ISSUE TITLE
Product Image Full view close icon not working in IOS devices

### ISSUE THREAD

**Issue by JananiKrishnan** [magento/magento2#12907] opened 2017-12-28 12:48 UTC
**Preconditions**  

1. Magento 2.2.2 

**Steps to reproduce**

1. Go on any new Android or IOS device, go to a product page, open the image gallery of the item. Try to click the upper right hand X and the gallery doesnt close. You have to hit the back button on the browser to get out of it but when you do that, it takes you back to the product grid page. It has been tested on iphone 6, 6s, pixel 2 xl, and galaxy 7.

**Expected result**
It should close the gallery and you should remain on the product page
**Actual result**
Nothing happens when you click the x button

**Comment by magento-engcom-team** [comment] 2017-12-28 13:28
@JananiKrishnan , thank you for your report.
This is duplicate of [#12726](https://github.com/magento/magento2/issues/12726)

**Closed as completed by magento-engcom-team** 2017-12-28 13:28 UTC
Labels: duplicate, Issue: Format is valid
