### ISSUE TITLE
Display success message for Apply rules if haven't added rule

### ISSUE THREAD

**Issue by renard123** [magento/magento2#24834] opened 2019-10-03 04:34 UTC
Display success message for Apply rules if haven't added rule

### Preconditions (*)
magento 2.3

### Steps to reproduce (*)
1. Admin -> Marketing -> Promotions -> Catalog Price Rules
2. Click on Apply rules
3. It will display the message like "Updated rules applied."

### Expected result (*)
Apply Rules link should not be display if no rules added
OR	
Apply Rules link should be disable

### Actual result (*)
Display the message like "Updated rules applied."

**Comment by krishprakash** [comment] 2019-10-03 04:34
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-10-03 04:34
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-10-03 04:35
Hi @krishprakash, here is your [Magento instance](https://i-24834-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24834-2-3-develop.instances.magento-community.engineering/admin](https://i-24834-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-10-03 04:37
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21445` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment] 2020-05-11 19:32
Hello @renard123
fyi: @tna274 

This issue was reviewed and discussed with Product Managers.
From one point of view this is a small and good improvement for UX, but
- This behavior works as it was developed and exist probably in all Magento versions/releases
- It was not any critical reports or functional bug related to it. Only when this link was removed in EE/B2B in favor of Staging functionality.
- Admin User is notified if some Rules were not applied with the message: "We found updated rules that are not applied. Please click "Apply Rules" to update your catalog."
- Potentially such small improvement could affect other hidden logic or merchant use-cases and increase the regression scope for the release.

Based on all of these, Product Manager's decision is:
- we do not accept this small improvement due to possible risk for Catalog Rule functionality in CE and other editions
- Issue and related PRs should be rejected - closed.

**Closed as completed by sdzhepa** 2020-05-11 19:32 UTC
Labels: Issue: Ready for Work, Component: CatalogRule, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Backend
