### ISSUE TITLE
Language Switcher gives 404 error on product page

### ISSUE THREAD

**Issue by devendra-m** [magento/magento2#26730] opened 2020-02-06 12:41 UTC
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

1. We have 2 stores for fi for finnish and en for english.
2. We have set url key for en as mission-workshop-the-rummy-vx-messenger-bag and for fi as mission-workshop-the-rummy-vx-messenger-laukku
3. On product page https://www.urbankitsupply.com/fi/mission-workshop-the-rummy-messenger-laukku.html when language is changed to english instead of url https://www.urbankitsupply.com/en/mission-workshop-the-rummy-vx-messenger-bag.html it stays in https://www.urbankitsupply.com/en/mission-workshop-the-rummy-messenger-laukku.html  which gives 404 error

### Expected result (*)

1. When language is changed to english it should redirect to https://www.urbankitsupply.com/en/mission-workshop-the-rummy-vx-messenger-bag.html

### Actual result (*)

1. When language is changed to english it redirecst to https://www.urbankitsupply.com/en/mission-workshop-the-rummy-messenger-laukku.html

**Comment by shikhamis11** [comment] 2020-02-07 03:00
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-07 03:00
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-07 03:01
Hi @shikhamis11, here is your [Magento instance](https://i-26730-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26730-2-4-develop.instances.magento-community.engineering/admin_b8a3](https://i-26730-2-4-develop.instances.magento-community.engineering/admin_b8a3)
Login: `ada4bcb5` Password: `cdd34c32b3e2`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2020-02-07 03:21
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31248` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by srsathish92** [comment] 2020-02-07 11:50
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-07 11:51
Hi @srsathish92. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-07 11:51
Hi @srsathish92, here is your [Magento instance](https://i-26730-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26730-2-4-develop.instances.magento-community.engineering/admin_b7d3](https://i-26730-2-4-develop.instances.magento-community.engineering/admin_b7d3)
Login: `4f8bc267` Password: `f5a51b349e47`
Instance will be terminated in up to 3 hours.

**Comment by GuiltyNL** [comment] 2020-02-09 21:27
This is a duplicate. Ther is a commit for that works:

https://github.com/magento/magento2/commit/f19c780fb7e31db89bfd9965e177d52ad03dacd7

I can confirm the above commit works.

**Comment by devendra-m** [comment] 2020-02-10 03:58
@GuiltyNL that commit says to prevent changing the target URL. We have different product url keys for finnish and english stores. So when switching from english to finnish store, product url should change. Which is not working.

**Comment by GuiltyNL** [comment] 2020-02-10 06:26
I know, we have the same. This fix works. Try it.

**Comment by devendra-m** [comment] 2020-02-10 06:37
@GuiltyNL I have tried that fix but it doesn't work

**Comment by GuiltyNL** [comment] 2020-02-10 06:44
Strange, here it works. Try it:

https://www.neptunestore.eu/nld/neptune-systems-1000-ph-kalibratievloeistof.html

**Comment by devendra-m** [comment] 2020-02-10 07:16
@GuiltyNL which magento version are you using ? we are using magento 2.3.1

**Comment by GuiltyNL** [comment] 2020-02-10 07:53
We are using 2.3.3. Without the fix we had your issue. It did change the storeview code, but it did not change the URL. But this problem only occured while being logged in. As a guest visitor the store switcher did work.

**Comment by devendra-m** [comment] 2020-02-10 08:30
I added this line
 <item name="hashGenerator" xsi:type="object" sortOrder="1000">Magento\Store\Model\StoreSwitcher\HashGenerator</item>

which was missing in di.xml and also created HashGenerator.php which was also missing. But still not woriking https://www.urbankitsupply.com/en/mission-workshop-the-rummy-messenger-bag.html  Could this be version issue ?

**Comment by GuiltyNL** [comment] 2020-02-10 08:38
Hmm, it those were missing, it could be a version issue. In my installation it already existed, I only had to change the existing files.

**Comment by duffner** [comment] 2020-03-07 15:57
Can you please verify that the product exists on both stores as part of definition of this ticket.  If this product is disabled in one store, but active in another this would lead to the same result. Which is also broken as the store switch should take to homepage if 404 is given. Per other multistore issues that were resolved

**Comment by devendra-m** [comment] 2020-03-08 06:41
@duffner there are products on both stores. For example

https://www.urbankitsupply.com/fi/mission-workshop-the-rummy-messenger-laukku.html for finnish
https://www.urbankitsupply.com/en/mission-workshop-the-rummy-vx-messenger-bag.html for english

**Comment by engcom-Delta** [comment] 2020-08-20 07:47
Hi @devendra-m you for your report, I'm not able to reproduce issue by steps you described on the latest 2.4-develop
**Result:**
- Switch store view
![#26730issueLoginStoreView](https://user-images.githubusercontent.com/51681379/90731501-71e40580-e2d2-11ea-807e-cb25b049981c.gif)

- Switch stores
![#26730issueLoginStore](https://user-images.githubusercontent.com/51681379/90731522-78727d00-e2d2-11ea-9a52-38a40ba0f5f7.gif)

If you'd like to update the issue, please reopen it.

**Closed as completed by engcom-Delta** 2020-08-20 07:47 UTC
Labels: Issue: Ready for Work, Component: CatalogUrlRewrite, Issue: Format is valid, Reproduced on 2.4.x, Reported on 2.3.1
