### ISSUE TITLE
Broken backend popup view

### ISSUE THREAD

**Issue by dmytro-ch** [magento/magento2#19263] opened 2018-11-18 15:04 UTC
The confirmation popups are broken due to the reduced width.

### Preconditions (*)

1. Magento versions: 2.2.7 and 2.3

### Steps to reproduce (*)

1. Login to the admin panel.
2. Go to `System -> Cache Management`.
3. Click "Flush Cache Storage".

### Expected result (*)

1. Content does not overlap the "close" button. (including tablet and mobile view);
2. The Popup has the normal width (75%), as previously. (sould be clarified)
<img width="1276" alt="screen shot 2018-11-18 at 4 56 39 pm" src="https://user-images.githubusercontent.com/11693779/48674326-891d1e80-eb53-11e8-8577-2f0b2dc6a31c.png">

### Actual result (*)

1. Content overlaps the "close" button.
<img width="1123" alt="screen shot 2018-11-18 at 4 46 42 pm" src="https://user-images.githubusercontent.com/11693779/48674324-83bfd400-eb53-11e8-936b-9e24c6a7bee7.png">

**Comment by magento-engcom-team** [comment] 2018-11-18 15:04
Hi @dmytro-ch. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dmytro-ch do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by VladimirZaets** [comment] 2018-11-23 13:40
Hi @dmytro-ch. Thank you for your report. 
The issue has been fixed in magento/magento2#19340 by @gelanivishal in 2.2-develop branch
Related commit(s):
 - [27c265daa106c269e18f164c5dbb6ac7c1d5a965](https://github.com/magento/magento2/commit/27c265daa106c269e18f164c5dbb6ac7c1d5a965)
 - [4b70893a4e8c8b206ec48df6fe3ab7e0e03095e7](https://github.com/magento/magento2/commit/4b70893a4e8c8b206ec48df6fe3ab7e0e03095e7)

The fix will be available with the upcoming 2.2.8 release.

**Closed as completed by VladimirZaets** 2018-11-23 13:40 UTC
Labels: Fixed in 2.2.x, Issue: Format is valid
