### ISSUE TITLE
magento-composer-1.   0.2.0.zip file could not be downloaded

### ISSUE THREAD

**Issue by patrickpeng2091** [magento/magento2#2419] opened 2015-11-19 04:06 UTC
[Composer\Downloader\TransportException]
  The "https://repo.magento.com/archives/magento/composer/magento-composer-1.
  0.2.0.zip" file could not be downloaded (HTTP/1.1 404 Not Found)

**Comment by BlackIkeEagle** [comment] 2015-11-19 09:35
@oucart seems the composer.lock file is wrong

When you run composer update (you must give your magento connect credentials) it gets the magento-composer package from packages.magento.com, not from repo.magento.com

**Comment by bh-ref** [comment] 2015-11-19 09:36
I had the same problem. Just use the magento 2.0.0 code base from here: https://www.magentocommerce.com/download this has up to date dependencies as it seems

**Comment by bh-ref** [comment] 2015-11-19 09:40
the main difference: `package.json` on github does list `magento/magento-composer-installer` as a dependency, but the `package.json` from https://www.magentocommerce.com/download does not.

**Comment by BlackIkeEagle** [comment] 2015-11-19 09:44
@bh-ref makes sense since you don't need to install anything via composer there is no need for a dependency on `magento/magento-composer-installer`

**Comment by bh-ref** [comment] 2015-11-19 09:47
@BlackIkeEagle I see. Unfortunately, the problem is, that the asterisk for the `magento/magento-composer-installer` dependency evaluates into version 1.0.2.0 which is not available in the repo

**Comment by BlackIkeEagle** [comment] 2015-11-19 10:09
@bh-ref the asterisk does not matter if you are running `composer install`. I suggest using `composer update` which will get you the composer-installer from packages.magento.com and not from repo.magento.com

**Comment by bh-ref** [comment] 2015-11-19 10:15
@BlackIkeEagle thank you for your response. I will try that for my next test installation. If that is the solution, does that mean that the docs at http://devdocs.magento.com/guides/v2.0/install-gde/install/prepare-install.html should be changed to suggest using `composer update`instead of `composer install`?

**Comment by BlackIkeEagle** [comment] 2015-11-19 10:24
@bh-ref no the docs should not be updated, the composer.lock file must be fixed and point to an existing location/file /cc @maksek

**Comment by marcobax** [comment] 2015-11-19 13:16
I've put up a blog post explaining how to resolve this issue step by step, check it out at: http://magento2king.com/magento2-insta-be-downloaded/

**Comment by gsomoza** [comment] 2015-11-19 13:22
@BlackIkeEagle I'm having the same issue, on the most recent master commit at the time of writing (`4cae5d058b7a`).

Unless I'm missing something important (which is possible), using `composer update` doesn't seem to be the recommended workflow for projects that have `composer.lock` files versioned. `composer install` is supposed to be enough. Ref: https://blog.engineyard.com/2014/composer-its-all-about-the-lock-file. So it seems like you should gitignore the `composer.lock` file if the workflow requires an update. Then people that run `composer install` will not run into this issue.

**Comment by BlackIkeEagle** [comment] 2015-11-19 13:43
@gabrielsomoza I'm not saying its recommended to do it like this, for me it was the solution that worked.

@marcobax that indeed is the solution, so this is rather a composer issue then or the repo.magento.com server does not return a 401 to composer?

Personally I'm somewhat offended that you must pull magento/composer from a password protected server while there is no need at all for that package to be hidden behind a password.

**Comment by muasir** [comment] 2015-11-19 14:02
@marcobax and @BlackIkeEagle this is an issue with repo.magento.com.  We are currently working on this issue.

**Comment by gsomoza** [comment] 2015-11-19 14:14
@BlackIkeEagle :+1: to what you said about authentication for CE

**Comment by marcobax** [comment] 2015-11-19 17:55
@BlackIkeEagle @gabrielsomoza Yes! This is very true, I also think there is no need to authenicate for pulling Magento2 CE.

**Comment by crystallove** [comment] 2015-11-20 03:03
This is an issue with repo.magento.com. 
You can wait until it is fixed or you follow the solutions at below. It should be worked.
http://magento2king.com/magento2-insta-be-downloaded/
1. Login to github, and get the personal access key token.
2. Use that token and your magento.com login credentials. 
- Create or Edit auth.json at .composer
- Your auth.json should be looked like this: 
  {
  "github-oauth": {
   "github.com": "your token here"
  },
  "http-basic": {
    "repo.magento.com": {
       "username": "your magento.com username",
       "password": "your magento.com pw"
    }
  }
  }

Try to run composer install again. It works like a charm.

**Comment by aamnah** [comment] 2015-11-20 09:22
facing the same issue, the solution @marcobax and @crystallove mentioned did not work for me, error persists.

**Comment by aamnah** [comment] 2015-11-20 09:42
faced the same issue, the solution @marcobax and @crystallove mentioned worked.

**Comment by muasir** [comment] 2015-11-20 18:06
We have fixed the 404 issue.  Now with invalid credentials you will get the 401 error.  But you will also need new auth tokens, please follow this link to generate the tokens http://devdocs.magento.com/guides/v2.0/install-gde/prereq/connect-auth.html

**Comment by realdigid** [comment] 2015-11-20 22:00
I believe this is a related issue, but i'm getting this when i attempt to deploy sample data to my build. Is there a flag i'm missing or something?

(Note: my credentials already exist within ~/.composer/auth.json and already did "composer update")

$ php bin/magento sampledata:deploy 
./composer.json has been updated
Loading composer repositories with package information

  [Composer\Downloader\TransportException]  
  The 'https://repo.magento.com/packages.json' URL required authentication.  
  You must be using the interactive console to authenticate

**Comment by davidalger** [comment] 2015-11-20 22:23
@realdigid Have you updated your auth username/password with the tokens generated via instructions found here: http://devdocs.magento.com/guides/v2.0/install-gde/prereq/connect-auth.html?

**Comment by realdigid** [comment] 2015-11-23 00:08
Yes i have. I will attempt to do so again tomorrow just to verify. All other processes work fine using the same credentials as well, such as composer update/install it seems specific to sample data.

**Comment by ghost** [comment] 2015-11-23 18:01
@realdigid That issue is solved by running composer update from the Magento root. A better fix is in the works. (Sample data suppresses messages from Composer.)

**Comment by KvantX** [comment] 2015-11-27 13:26
I have the same problem as @realdigid and composer update doesn't solve it.

**Comment by daapower** [comment] 2015-12-13 01:59
having the same issue as KvantX and realdigid.  i have updated composer..

**Comment by APGD2016** [comment] 2015-12-23 03:31
I hit the same problem as @realdigid, @KvantX  @daapower

**Comment by BlackIkeEagle** [comment] 2015-12-23 05:47
@KvantX , @daapower , @APGD2016 you should check http://devdocs.magento.com/guides/v2.0/install-gde/prereq/dev_install.html

You must have entered your credentials before trying to add the sample data. So the working solution should be something like:

``` sh
$ git clone https://github.com/magento/magento2.git
$ cd magento2
$ composer install
   # along the way you get asked to enter credentials (on the magento-composer-installer package)
   # the credentials should be generated as described in the devdocs and not your magento email/pass
$ bin/magento sampledata:deploy # should work if you stored your credentials
```

**Comment by KvantX** [comment] 2015-12-23 08:24
@BlackIkeEagle Thanks for advice, it can be so.
I installed magento according to  http://devdocs.magento.com/guides/v2.0/install-gde/prereq/integrator_install.html

```
composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition
```

and it's possible that i have entered credentials before sampledata:deploy

**Comment by BlackIkeEagle** [comment] 2015-12-23 09:58
@KvantX I confirm the issue when using `composer create-project`, even with valid credentials the bin/magento sampledata:deploy command fails

``` sh
$ php bin/magento sampledata:deploy
./composer.json has been updated
Loading composer repositories with package information



  [Composer\Downloader\TransportException]                                   
  The 'https://repo.magento.com/packages.json' URL required authentication.  
  You must be using the interactive console to authenticate                  



require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [packages1] ... [packagesN]


There is an error during sample data deployment.
```

but after that issue running `composer update` seems to work

``` sh
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing magento/module-catalog-sample-data (100.0.2)
    Downloading: 100%         

  - Installing magento/module-bundle-sample-data (100.0.2)
    Downloading: 100%         

  - Installing magento/module-customer-sample-data (100.0.2)
    Downloading: 100%         

  - Installing magento/module-widget-sample-data (100.0.2)
    Downloading: 100%         

  - Installing magento/sample-data-media (100.0.2)
    Downloading: 95% 
```

**Comment by APGD2016** [comment] 2015-12-23 14:30
@BlackIkeEagle   Thanks very much for your help! My problem is fixed.

**Comment by tanya-soroka** [comment] 2016-05-10 23:50
Hello
Could you please confirm that the issues has been resolved? If yes, please go ahead and close the ticket. 

Thanks

**Comment by BlackIkeEagle** [comment] 2016-05-11 07:55
@tanya-soroka I confirm the issue is resolved, you can close this ticket or @patrick4u can close it

**Closed as completed** 2016-05-11 13:56 UTC
Labels: Issue: Ready for Work, bug report
