### ISSUE TITLE
Street fields in checkout don't have a label that's readable by a screenreader

### ISSUE THREAD

**Issue by TomFranssen** [magento/magento2#10894] opened 2017-09-15 07:52 UTC
### Preconditions
1. Standard Magento ver. 2.1.7 installation 

### Steps to reproduce
1. Add a product to your cart
2. Go to checkout
3. The address lines input fields don't have a `<label>` element with a valid value. There is a `<span>` infront of it with the text 'Address'. This text however doesn't get recognised by screen readers.

### Expected result

1. The labels should have a valid `<label>` element that is linked to the `<input>` field with a `for` attribute. My advice is to add linked <label> elements to all the address line fields so that screen readers can know what kind of fields the address fields are and thus increasing accessibility.

If I test this on the default MAC screenreader (activated by CMD + F5) I get the feedback of: 'edit text blank'. In this situation the visually impaired user doesn't get feedback on what type of field it is.

**Comment by pboisvert** [comment] 2017-09-16 03:21
duplicate of #10893

**Closed as completed** 2017-09-16 03:21 UTC
Labels: Issue: Format is not valid
