### ISSUE TITLE
CMS page edit - "Reset" button does nothing

### ISSUE THREAD

**Issue by jsakars** [magento/magento2#5615] opened 2016-07-13 11:27 UTC
## Steps to reproduce
1. Install Magento 2.1
2. Open CMS page in admin
3. Click `Reset` button
## Expected result
1. Page is reloaded
## Actual result
1. Nothing happens

**Comment by onakonechna** [comment] 2016-07-25 11:31
'Reset' button resets input fields values, not reloads the page. Change any field, then press 'Reset' - it must return value to its saved state

**Comment by andimov** [comment] 2016-08-02 11:05
@werdlv 
Thank you for reporting!
I'm closing this issue as 'not a bug'.
Please feel free to reopen if you need.

**Closed as completed by andimov** 2016-08-02 11:05 UTC

**Comment by RickyThakur** [comment] 2018-08-28 17:52
Thanks @onakonechna  , you save my day.
