### ISSUE TITLE
No Cross-Sells on cart page

### ISSUE THREAD

**Issue by yutv** [magento/magento2#29686] opened 2020-08-19 16:31 UTC
### Preconditions (*)

1. Magento Cloud 2.3.5. **Please note** the bug is in the Magento_Catalog module from Magento Open Source which is a part of Magento Cloud, see Source Code section below.
2. **Important**: make sure `row_id` <> `entity_id` for all records in the `catalog_product_entity` table

### Steps to reproduce (*)

1. Back Office: Choose a product (e.g. SKU-01), add a Cross-Sell to it (e.g. SKU-02).
2. Storefront: Add the chosen product (SKU-01) to cart
3. Go to cart page

### Expected result (*)

1. The SKU-02 product in the Cross Sell block

### Actual result (*)

1. The Cross-Sell block is not shown

### Source Code
https://github.com/magento/magento2/blob/18da36b7640c8fd25ccafbbad33454bd6e21a5a6/app/code/Magento/Catalog/Model/ResourceModel/Product/Link/Product/Collection.php#L260

The `$identifierField` = `row_id` on Magento Cloud but should be `entity_id`.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment] 2020-08-21 04:45
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-08-21 04:45
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-08-21 04:46
Hi @ajijshekh123, here is your [Magento instance](https://i-29686-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29686-2-4-develop.instances.magento-community.engineering/admin_5b51](https://i-29686-2-4-develop.instances.magento-community.engineering/admin_5b51)
Login: `23095b54` Password: `e5165eabcb19`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2020-08-21 05:00
Hello @yutv,
I have verified this issue in the latest Magento 2.4 Instance with your steps, actual result and expected result.
The issue is not reproduced in the Latest Magento 2.4 Instance.
**PFA:** 

![Admin_CrossSellProduct](https://user-images.githubusercontent.com/24711761/90853923-20eb1480-e399-11ea-9ae2-fd6b63d822bf.png)

![Shopping-Cart_CrossSellProduct](https://user-images.githubusercontent.com/24711761/90853933-26485f00-e399-11ea-8551-def75421fdfa.png)

Can you please update which Magento version you have used and reproduced the issue?

Thanks.

**Comment by yutv** [comment] 2020-08-21 06:07
@ajijshekh123,

Have you met described preconditions? 

It can be reproduced in Magento Cloud and I believe in Magento Commerce versions where is Content Staging functionality but not in the Magento Open Source. I created issue here because problematic code is located in the Magento Open Source module. 

Can you test it in the Magento Cloud or Magento Commerce?

**Comment by ajijshekh123** [comment] 2020-08-21 06:09
@yutv 

Magento doesn't provide the Magento cloud server Instance. So If the latest Magento instance is available on our cloud server I will verify this issue and update you today EOD.

Thanks

**Comment by zohaibmir** [comment] 2020-08-21 06:50
we also have the same issue and it can be produceable if we have different row_id and entity_id in catalog_product_entity table. Magento use entity_id like described above to load crosssell on cart page.

**Comment by Stoyvo** [comment] 2020-08-24 16:42
Was able to recreate this issue in Magento 2.3.4 on Magento.Cloud. How does a critical component like this make it into a release?

**Comment by Stoyvo** [comment] 2020-09-03 04:55
@yutv @zohaibmir can you confirm if your instances, where this issue is recreated, was upgraded from a previous version? Eg: I experience this issue on 2.3.4, we upgraded from 2.2.8.

**Comment by andresams** [comment] 2020-09-03 17:28
Hi, I found this issue on Magento Cloud. If you are using the module Magento_TargetRule, you need to look at this function:

Magento\TargetRule\Block\Checkout\Cart\Crosssells::_getCartProducts()

Change this:

`$this->_products[$product->getEntityId()] = $product;`

To this:

`$this->_products[$product->getRowId()] = $product;`

The problem happens because the foreign key in the catalog_product_links table was updated. It used to associate its column product_id with the catalog_product_entity entity_id, but now it uses the row_id instead.

![image](https://user-images.githubusercontent.com/9648056/92146681-717a5d00-edf0-11ea-96b3-4a6c238ff16d.png)

In your case, you need to update this row:

Magento\Checkout\Block\Cart\Crosssells::_getCartProductIds()

`$ids[] = $product->getId();
`
To

`$ids[] = $product->getRowId();`

I could not find the module TargetRule to send a PR to. Can someone advise me on how to do that?

**Comment by gabrieldagama** [comment] 2020-10-12 13:41
Hi @yutv, I've tried to reproduce the issue by following your steps and wasn't able to. Can you provide more details on this? I've seen other contributors and developers (on @andresams PR #29899) weren't able to reproduce this issue as well.

**Comment by jeffekg** [comment] 2020-10-12 17:01
@gabrieldagama, this occurs when you have products in the database that have an `entity_id` that is not the same as its `row_id`, ie: a product with `entity_id` of 2, but a `row_id` of 3

**Comment by yutv** [comment] 2020-10-12 17:54
@gabrieldagama, I can not longer reproduce it in the Magento EE 2.4.1. Looks like it was fixed in the commit https://github.com/magento/magento2/commit/a6f0bf65fded57cae02c69a9c18bf28ca1012d4d

**Comment by gabrieldagama** [comment] 2020-10-13 08:34
Thanks for confirming @yutv. I will be closing this issue for now.

@jeffekg If you believe this is still an issue, please feel free to reopen it and provide steps to reproduce it. I've tried to reproduce the issue by having different entity_id and row_id for all the products and still the problems got displayed correctly on the cart.

**Closed as completed by gabrieldagama** 2020-10-13 08:34 UTC
Labels: Component: Catalog, Area: Frontend, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid, Progress: done, Reported on 2.3.5
