### ISSUE TITLE
Product price range filter exception on category page

### ISSUE THREAD

**Issue by arsalanworld** [magento/magento2#31317] opened 2020-12-17 10:28 UTC
### Preconditions (*)

1. Magento 2.4.1
2. At least a category with bunch of products.

### Steps to reproduce (*)

1. Navigate to Category page and apply a price range filter
2. Remove or leave blank second parameter in range. for example `..?price=30-` 
3. Check the log file

### Expected result (*)

1. There should be no exception
2. The filter either should not apply or it should filter the product with single price range, for example `30-30`

### Actual result (*)

1. An exception is thrown which can be observed in log file:
```
[2020-12-17 10:07:18] main.CRITICAL: Warning: A non-numeric value encountered in /var/www/html/vendor/magento/module-catalog-search/Model/Layer/Filter/Price.php on line 194 [] []
[2020-12-17 10:07:18] main.CRITICAL: The "catalog.leftnav" block threw an exception, and it can't be rendered. [] []

```
2. For some websites the page breaks or an error reporting page is displayed.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2020-12-17 12:49
Hello @arsalanworld 

Thank you for your report

We confirm that the issue is reproducible on the latest 2.4-develop. Additional info from Engcom is added to the Description

**Comment by magento-engcom-team** [comment] 2020-12-17 12:51
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39986` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by chiranjeevi-cj** [comment] 2020-12-18 08:13
@magento I am working on this

**Comment by ilnytskyi** [comment] 2021-02-04 14:58
We face this issue too. Bots are building strange URLs

**Comment by ArtemVasyliev** [comment] 2021-11-16 17:46
The issue is fixed in https://github.com/magento-commerce/magento2ce/commit/3e9c3c7ec1dd1a215b05a505ef9abaf7d86c3cac

**Closed as completed** 2021-11-16 18:14 UTC
Labels: Issue: Confirmed, Component: Url, Component: Filter, Reproduced on 2.4.x, Priority: P3, Severity: S4, Progress: done, Issue: ready for confirmation, Reported on 2.4.1
