### ISSUE TITLE
Magento 2.4.3 add minimum qty to wishlist

### ISSUE THREAD

**Issue by Jilco** [magento/magento2#34565] opened 2021-11-08 09:33 UTC
### Preconditions (*)

1. Magento 2.4.3-p1

### Steps to reproduce (*)

1. Admin - Catalog - Products - Edit - Quantity - Advanced Inventory  - Minimum Qty Allowed in Shopping Cart - 0.5 ,  Qty Uses Decimals - Yes  (Set 0.5 minumum qty in product)

2. Front end - add product to wishlist with minimum qty (by default sets to 0.5)

### Expected result (*)

1. 0.5 added to wishlist

### Actual result (*)

1. 1 is added to wishlist
2. On clicking Product from Wishlist page - QTY - 1 is displayed.
Note: There is no issue if product is viewed direclty from Search Results page - Qty - 0.5 is displayed in Product Details page

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Jilco** [comment] 2021-11-08 09:35
@magento give me 2.4.3-p1 instance

**Comment by Jilco** [comment] 2021-11-08 09:53
Confirmed 
![Naamloos](https://user-images.githubusercontent.com/23727130/140720892-eba47bbd-4166-49ee-a362-da5d8af5912d.jpg)

**Comment by engcom-November** [comment] 2021-11-08 14:44
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:

![image](https://user-images.githubusercontent.com/60198231/140761302-2382cee0-52fd-4799-bbb7-56001c06f94b.png)
![image](https://user-images.githubusercontent.com/60198231/140761369-0c392ecc-9d28-4f73-8bd4-ea6ea52fc1a5.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/60198231/140761460-d076c1b2-2951-43a1-8499-7ec26283bb55.png)

**Comment by vlmed** [comment] 2021-11-15 10:22
I am working on this

**Comment by vlmed** [comment] 2021-11-15 10:22
@magento I am working on this

**Comment by engcom-Bravo** [comment] 2024-09-06 05:51
Hi @Jilco,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="987" alt="Screenshot 2024-09-06 at 11 20 22" src="https://github.com/user-attachments/assets/878e44b2-3dc3-4a62-8501-71000180067c">


0.5 added to wishlist

**Comment by engcom-Bravo** [comment] 2024-09-06 05:52
Hi @Jilco,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="987" alt="Screenshot 2024-09-06 at 11 20 22" src="https://github.com/user-attachments/assets/878e44b2-3dc3-4a62-8501-71000180067c">


0.5 added to wishlist.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-09-06 05:52 UTC
Labels: Issue: Confirmed, Component: Wishlist, Reproduced on 2.4.x, Priority: P3, Progress: done, Area: Product, Reported on 2.4.3-p1
