### ISSUE TITLE
Magento 2.1: Configurable product wrongly imported if sku is an integer

### ISSUE THREAD

**Issue by shazul** [magento/magento2#5547] opened 2016-07-08 16:27 UTC
## Steps to reproduce
1. Magento 2.1: Import via csv a configurable product with its children. The parent SKU contains only digits, the children digits and letters.

Children products' SKUs:
310001BKL
310001BKM

Configurable product SKU:
310001

(It used to work in Magento 2.0.7)
## Expected result

Configurable product and its children displayed correctly.
![magento2-bug-expected-result](https://cloud.githubusercontent.com/assets/10780956/16694050/3650de8a-4506-11e6-9a1c-941ca74433e7.png)
## Actual result

Configurable product: No name, No visibility, No status
First simple product: Wrong visibility and configurable attributes set to default values (as if it were the parent product).
![magento2-bug-actual-result](https://cloud.githubusercontent.com/assets/10780956/16694145/a454376a-4506-11e6-94ae-4c59d0f26d64.png)
## 

If I include a letter in the parent SKU (ie: 310001A), it works.

**Comment by dthampy** [comment] 2016-07-10 20:52
Internal jira ticket MAGETWO-55237 has been created.

**Comment by redboxmarcins** [comment] 2016-09-08 15:55
Watching

**Comment by ghost** [comment] 2016-09-12 12:44
@shazul, @dthampy  I'm not aware of the status of MAGETWO-55237, but this was fixed and requested to be merged in https://github.com/magento/magento2/pull/6446.

**Comment by dthampy** [comment] 2016-09-13 13:42
@shazul, The internal ticket has not been processed yet. It will be fixed in one of the future patch releases. In the mean time, you can try the  fix suggested by @marcel-moldovan-vm and see if your issue is resolved.

**Comment by cuiyang000** [comment] 2016-09-25 07:47
Can confirm the issue with 2.1.1

**Comment by ooples** [comment] 2016-10-23 03:57
I'm getting this error as well. Is there a fix that will be released soon?

**Comment by jasonevans1** [comment] 2017-01-13 20:14
I am getting this error. Please fix soon.

**Comment by magento-engcom-team** [comment] 2017-09-20 22:26
@shazul, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:26 UTC
Labels: Issue: Ready for Work, bug report, Component: ImportExport, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is not valid
