### ISSUE TITLE
issue with get active payment methods (getActiveMethods) -  Magento CE 2.1

### ISSUE THREAD

**Issue by ln8711** [magento/magento2#5413] opened 2016-07-02 02:55 UTC
## Steps to reproduce
1. Enable Braintree
2. run the functions getActiveMethods from vendor/magento/module-payment/Model/Config.php in somewhere
## Expected result
1. Show list of active payment methods
## Actual result
1. Exception Call to undefined method Magento\Payment\Model\Method\Adapter::setId() in vendor/magento/module-payment/Model/Config.php on line 98

when $data['model'] is BraintreeFacade 

$methodModel = $this->_paymentMethodFactory->create($data['model']);
$methodModel->setId($code);

The factory can't create the model and then the following setId fails

Example code (put in _magento_/test/test.php):

```
<?php

require '../app/bootstrap.php';

class TestApp extends \Magento\Framework\App\Http implements \Magento\Framework\AppInterface
{
    public function __construct(
        \Magento\Framework\ObjectManagerInterface $objectManager,
        \Magento\Payment\Model\Config $paymentConfig,
        \Magento\Framework\App\Response\Http $response,
        \Magento\Framework\App\ResourceConnection $resource
    ) {
        $this->_objectManager = $objectManager;
        $this->_paymentConfig = $paymentConfig;
        $this->_response = $response;
        $this->_resource = $resource;
    }

    public function launch()
    {
        $state = $this->_objectManager->get('Magento\Framework\App\State');
        $state->setAreaCode('adminhtml');

        $payments = $this->_paymentConfig->getActiveMethods();
        print_r($payments);

        return $this->_response;
    }

    public function catchException(Magento\Framework\App\Bootstrap $bootstrap, \Exception $exception)
    {
        print_r($exception->getTraceAsString());

        return false;
    }
}

$bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $_SERVER);
$app = $bootstrap->createApplication('TestApp');

error_reporting(E_ALL);
ini_set("display_error", 1);

$bootstrap->run($app);
```

**Comment by dkvashninbay** [comment] 2016-07-05 10:14
Created internal ticket MAGETWO-55057
Probable solution - call to MethodInterface::setId(...) will be eliminated with a high probability as it's obsolete, due to MethodInterface objects are instantiated with payment code and there is no need to set it from client code.

**Comment by alena-marchenko** [comment] 2016-07-21 09:02
Hi @hoanglan87 

Fix for MAGETWO-55057 ticket is already merged to develop branch.
Closing the issue, please feel free to reopen if the issue still reproducible for you.

**Closed as completed by alena-marchenko** 2016-07-21 09:02 UTC
Labels: Issue: Ready for Work, bug report, Component: Payment

**Comment by snez** [comment] 2016-08-18 16:33
@alena-marchenko could you please confirm if the fix has removed the setId() call completely or whether it has been added to MethodInterface?
