### ISSUE TITLE
Add root or sub categorie button dissapear if you change store view

### ISSUE THREAD

**Issue by EthicalErik** [magento/magento2#7180] opened 2016-10-25 15:43 UTC
### Preconditions

Magento 2.1.2
### Steps to reproduce
1. Products > categories
2. You can see the add root and subdirectory button
3. Change the store view.
   4.The buttons are not there anymore and you can't add a root or sub categories to that view.
### Expected result
1. A add a root categorie and a add a sub categorie button
### Actual result

1. No buttons
   ![magentogit1](https://cloud.githubusercontent.com/assets/5640785/19693045/7394e05a-9ada-11e6-9089-41af50c64699.png)
   ![magentogit2](https://cloud.githubusercontent.com/assets/5640785/19693044/73943560-9ada-11e6-9d7c-5c181520a003.png)

**Comment by storepeinture** [comment] 2016-10-27 09:21
I have the same issue, and I just got here to report the exact same thing. So, I can confirm this issue on my side (Magento 2.1.2).
Also reloading the page doesn't help.

**Comment by dthampy** [comment] 2016-10-27 20:34
Internal jira ticket -MAGETWO-60226 created to track this issue.

**Comment by dthampy** [comment] 2016-10-31 15:09
According to the Product Owner:

> This is an expected behavior which was recently changed on purpose. Original flow was confusing for staging functionality users and led to some serious issues related to category staging. Currently the behavior described in this ticket is an expected result (these buttons should be visible only on Global scope). It makes sense because category will be created on global scope even if user clicks Add Subcategory button on Store View level.

**Comment by dthampy** [comment] 2016-10-31 15:09
closing this as not a bug.

**Closed as completed by dthampy** 2016-10-31 15:09 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog
