### ISSUE TITLE
"Something went wrong with processing the default view and we have restored the filter to its original state."

### ISSUE THREAD

**Issue by keetontucker** [magento/magento2#35318] opened 2022-04-15 13:54 UTC
### Preconditions (*)

1. Magento 2.4.2
2. Product display

### Steps to reproduce (*)

1. set view to 200 products
2. click apply filters

### Expected result (*)

1. I expected to view a page with 200 products, and to have the ability to move through other pages of 200 products
2. 

### Actual result (*)

1. "Something went wrong with processing the default view and we have restored the filter to its original state."
2. Attempts to load for hours on end, does not load

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-04-18 12:14
hi @keetontucker 
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue. Please check below possible workarounds which may help you resolve the issue:
1. Please check "catalog_product_entity" table in the database for any sku 's having NULL value and update them:
UPDATE catalog_product_entity SET sku='' WHERE sku IS NULL;
2. Check if the user is having very restricted Access to the magento backend and grant users access to the product catalog / orders that may fix this issue.
3. Run the query: TRUNCATE ui_bookmark; this will reset the grid back to it's default and stop the infinite load.

Kindly recheck the issue on Magento 2.4-develop branch and elaborate steps to reproduce if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-05-02 06:29
Hi @keetontucker ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-05-02 06:29 UTC
Labels: Issue: needs update
