### ISSUE TITLE
Translate long text

### ISSUE THREAD

**Issue by mibesoft** [magento/magento2#36934] opened 2023-03-01 04:46 UTC
### Preconditions and environment

- Magento version 2.4.3-p1

### Steps to reproduce

1. I want translate some to a text longer than 255 chars
2. I change field translate in table translation from varchar(255) to varchar(400)
3. I insert new record in table translation for translate.
4. Run php bin/magento setup:upgrade for update translation on website
5. I check table translation, field translate back to varchar(255)

### Expected result

 field translate should be varchar(400) 

### Actual result

 field translate is varchar(255) 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-03-02 07:55
Hi @mibesoft ,

Verified the issue the in 2.4-develop,But the issue is not reproducible.

Preconditions:
Magento version 2.4-develop
PHP 8.1

Steps to reproduce:
1.Install magento instance with DB
2.Install Mysql workbench
3.Open magento instance db in mysql workbench
4.Click the tables option under the magento instance db
5.Check translation option in the table
6.Right click the translation option and click alter table option
7.Here click on Transalate column edit the varchar 255 to 400
8.Apply and save.

If you checking again the translate value it will be 400 only and we are getting expected results.

Actual result:
field translate is varchar(255)
Expected result:
field translate should be varchar(400)

Screenshots for your reference:
1.Before the changes
<img width="1472" alt="varchar1" src="https://user-images.githubusercontent.com/60198592/222365784-37888399-d4f4-4cd5-a5a4-16ed9121e6d8.png">
2.We need to change Varchar value 255 to 400
<img width="1273" alt="varchar2" src="https://user-images.githubusercontent.com/60198592/222365933-9018fc59-ff19-4235-aa3a-e2744b5253a7.png">
3.After changes
<img width="1273" alt="varchar3" src="https://user-images.githubusercontent.com/60198592/222366047-c440d7dd-a9a1-4940-ae42-b5216006e067.png">

Let us know if we missing anything

Regards,

**Comment by engcom-Dash** [comment] 2023-03-20 05:43
Hi @mibesoft ,

We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-Dash** 2023-03-20 05:43 UTC
Labels: Issue: needs update, Reported on 2.4.3-p1
