### ISSUE TITLE
Magento reindex job fail

### ISSUE THREAD

**Issue by Sam43210** [magento/magento2#23608] opened 2019-07-07 12:22 UTC
Getting below error during the reindex 

main.CRITICAL: Table "catalogrule_product_replica" does not exist {"exception":"[object] (Zend_Db_Exception(code: 0): Table \"catalogrule_product_replica\" does not exist 

Any suggestions much appreciated.
This issue happening in Magento 2.2 version.

**Comment by kalpmehta** [comment] 2019-07-08 00:52
Duplicate of https://github.com/magento/magento2/issues/11912

**Comment by kalpmehta** [comment] 2019-07-08 00:53
@Sam43210 I am closing this, please re-open if you think it is a core bug. Thanks

**Closed as completed by kalpmehta** 2019-07-08 00:53 UTC
Labels: duplicate, Issue: Format is not valid
