### ISSUE TITLE
magento 2.1.7 - catalogProductAttributeRepositoryV1 - searching of attributes OR condition fails

### ISSUE THREAD

**Issue by manhao-chen** [magento/magento2#10669] opened 2017-08-26 04:46 UTC
### Preconditions
currently i'm using the magento 2.1.7 with sample data

### Steps to reproduce
if i only search 1 eg... color, data is returned
http://URL/magento-217/rest/V1/products/attributes?searchCriteria[filter_groups][0][filters][0][field]=attribute_code&searchCriteria[filter_groups][0][filters][0][condition_type]=eq&searchCriteria[filter_groups][0][filters][0][value]=color

but if it try and search for either colour or color i don't get any data returned, any ideas?

i've tried ...
http://URL/magento-217/rest/V1/products/attributes?searchCriteria[filter_groups][0][filters][0][field]=attribute_code&searchCriteria[filter_groups][0][filters][0][condition_type]=eq&searchCriteria[filter_groups][0][filters][0][value]=color&searchCriteria[filter_groups][0][filters][1][field]=attribute_code&searchCriteria[filter_groups][0][filters][1][condition_type]=eq&searchCriteria[filter_groups][0][filters][1][value]=colour

AND tried ...

http://URL/magento-217/rest/V1/products/attributes?searchCriteria[filter_groups][0][filters][0][field]=attribute_code&searchCriteria[filter_groups][0][filters][0][condition_type]=eq&searchCriteria[filter_groups][0][filters][0][value]=color&searchCriteria[filter_groups][1][filters][0][field]=attribute_code&searchCriteria[filter_groups][1][filters][0][condition_type]=eq&searchCriteria[filter_groups][1][filters][0][value]=colour

### Expected result
using the OR condition, if 1 of the attribute key matches it should return data

### Actual result
no data is returned, even when using the OR condition

**Comment by orlangur** [comment] 2017-08-26 13:51
GitHub is intended for bug reports and other issues observed in vanilla Magento 2 Community Edition. Issues should conform to [issue template](https://github.com/magento/magento2/blob/develop/ISSUE_TEMPLATE.md) so that anyone can reproduce problem and not guessing anything.

[Magento Stack Exchange](https://magento.stackexchange.com) shall be used for questions.

**Comment by manhao-chen** [comment] 2017-09-19 21:26
i've re-written it into the issue template

**Comment by magento-engcom-team** [comment] 2017-09-28 11:30
@manhao-chen, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-28 11:30 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
