### ISSUE TITLE
RESOURCE tree is loading , not showing

### ISSUE THREAD

**Issue by blooomegypt** [magento/magento2#38619] opened 2024-04-15 14:09 UTC
### Preconditions and environment

- 2.3.5-p2
- resource tree in intergration and user roles
- i tired disabling all extension still not working

### Steps to reproduce

1.system->user roles->new role-> role resources

### Expected result

the resource tree is shown 

### Actual result

the resource tree is just loading , not shown

### Additional information

i tired disabling all third party extension , still not shown 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2024-04-16 07:41
Hi @blooomegypt 

Thanks for reporting and collaboration.

Verified the issue on magento 2.4 dev instance and the issue is not reproducible.

Steps to reproduce
1.system->user roles->new role-> role resources

We are able to see the resource tree. Please refer the attached screenshot and let us know if we missed anything.

<img width="1440" alt="Screenshot 2024-04-16 at 1 11 01 PM" src="https://github.com/magento/magento2/assets/60198592/a4a5b3d0-bb50-42fe-9188-b1ff741f3aa1">

**Comment by blooomegypt** [comment] 2024-04-16 09:41
at  my admin panel is not shown , what could be the error

**Comment by engcom-Dash** [comment] 2024-04-17 06:06
Hi @blooomegypt 

The version you are checking is very old. Can you please try upgrading the instance to the latest one.

I have verified the issue on latest 2.4 dev instance and the issue is not reproducible.

Let me know if you need any assistance.

Thanks.

**Comment by engcom-Dash** [comment] 2024-04-30 05:46
Hi @blooomegypt 

We have noticed that this issue has not been updated for a long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel free to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2024-04-30 05:46 UTC
Labels: Issue: needs update, Reported on 2.3.5-p2
