### ISSUE TITLE
install magento   [ErrorException]         mkdir(): File exists  

### ISSUE THREAD

**Issue by magenx** [magento/magento2#4629] opened 2016-05-23 07:41 UTC
have you removed 2.1rc version? cause composer downloading 2.0.6
or is there still some errors with your files/repo configuration??

```
Failed to initialize global composer: Composer could not find the config file: /home/myshop/.config/composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running 1.1.1 (2016-05-17 12:25:44) with PHP 7.0.6 on Linux / 4.4.6-1-pve
Checked CA file /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem: valid
Downloading https://repo.magento.com/packages.json                                                                   Authentication required (repo.magento.com):   
      Username: xxxxxxxxxxxxxxxxxxxx
      Password: 
Downloading https://repo.magento.com/packages.json
Do you want to store credentials for repo.magento.com in /home/myshop/.config/composer/auth.json ? [Yn] Y
Writing /home/myshop/.cache/composer/repo/https---repo.magento.com/packages.json into cache
Installing magento/project-community-edition (2.0.6)
```

```
  [ErrorException]      
  mkdir(): File exists  
```

```
Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Installer/ProjectInstaller.php:68
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 mkdir() at phar:///usr/local/bin/composer/src/Composer/Installer/ProjectInstaller.php:68
 Composer\Installer\ProjectInstaller->install() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:152
 Composer\Installer\InstallationManager->install() at phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php:346
 Composer\Command\CreateProjectCommand->installRootPackage() at phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php:156
 Composer\Command\CreateProjectCommand->installProject() at phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php:142
 Composer\Command\CreateProjectCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:221
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:101
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:24
```

**Comment by mazhalai** [comment] 2016-05-23 13:58
@magenx can you please clarify steps: you first removed 2.1-rc via composer? and then what?

**Comment by magenx** [comment] 2016-05-23 14:33
fresh composer installation, why it breaks and downloads 2.0.6 instead of 2.1-rc??

**Comment by mazhalai** [comment] 2016-05-23 14:39
Can you post the exact command(s) you used.

**Comment by magenx** [comment] 2016-05-23 14:44
it is the same installation procedure 
`composer -vvv create-project --repository-url=https://repo.magento.com/ magento/project-community-edition  .`

`Installing magento/project-community-edition (2.0.6)`

latest version 2.1-rc1 ?? no?

**Comment by mazhalai** [comment] 2016-05-23 14:53
@magenx but 2.1-rc1 is not a stable release, does this work? `composer -vvv create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.1.0-rc1 .`

**Comment by magenx** [comment] 2016-05-23 15:04
ok, i give up, this is tagged as Latest Release on github page....

**Comment by magenx** [comment] 2016-05-24 07:22
so im not able to install it with composer??? for gods sake how many versions out there??? github, magento website, magento repo...

**Comment by mazhalai** [comment] 2016-05-24 13:15
@magenx did you try `composer -vvv create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.1.0-rc1 .`? 

All of the different version serve different purposes, you can read more about it here: http://devdocs.magento.com/guides/v2.0/install-gde/continue.html

also what RC really means: https://en.wikipedia.org/wiki/Software_release_life_cycle#Release_candidate

Closing this issues, since this is not a bug

**Closed as completed by mazhalai** 2016-05-24 13:15 UTC
Labels: Progress: needs update
