### ISSUE TITLE
Please reopen #4159

### ISSUE THREAD

**Issue by fooman** [magento/magento2#7616] opened 2016-11-29 21:01 UTC
This issue report is just to bring to your attention https://github.com/magento/magento2/issues/4159 - its closed but not fixed and people are still adding reports to it.

**Comment by timstoel** [comment] 2016-11-29 21:23
Thank you!

Yes, this is a deal-breaker for me.  I need to be able to use the Web Setup Wizard to install an extension for a very well-known shipping integration and they only support installation via the Web Setup Wizard, so I am unable to process shipments using their platform.  I have contacted the vendor and they are looking into other options for installation but for now Magento 2 is close to useless for us.

I am using Varnish 4 in production and I cannot use the workaround URL trick mentioned in #4159.

This is a critical issue.  Today my company is currently discussing reverting to Magento 1.9 because of this issue and throwing away three months of work on Magento 2.

**Comment by veloraven** [comment] 2016-11-30 10:06
@fooman thank you for your feedback.
As the original issue was closed by its reporter, please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. Please, also identify which version of Magento you are running.

**Comment by dharake** [comment] 2016-11-30 12:09
I've reopened the issue https://github.com/magento/magento2/issues/7623

**Comment by dharake** [comment] 2016-11-30 12:23
@timstoel please see https://github.com/magento/magento2/issues/7623 for a possible solution to your issue

**Comment by veloraven** [comment] 2016-11-30 13:45
@dharake thank you for notice.
@fooman I'm closing this issue as duplicate of #7623

**Closed as completed by veloraven** 2016-11-30 13:45 UTC
Labels: Progress: needs update
