### ISSUE TITLE
Not getting correct label value of yes or no (Boolean) type attribute in aggregations data of products GraphQl response

### ISSUE THREAD

**Issue by prabhakaran777** [magento/magento2#29123] opened 2020-07-14 04:26 UTC
### Preconditions (*)

1.Magento 2.3.4 and 2.4-develop
2.Product attribute Yes or No (Boolean)

### Steps to reproduce (*)

1.Product attribute Yes or No (Boolean)
2.Create product with Yes or No attribute
3.Run Product query with aggregations 

### Expected result (*)

1. Expected Result with aggregation that attribute label

{
          "attribute_code": "yes_no",
          "label": "Yes or no",
          "options": [
            {
              "count": 1,
              "label": "No",      //here label with yes or no
              "value": "0"
            }
          ]
2.

### Actual result (*)

1. [Screenshots, logs or description]
  Label has showing same as value
![Screenshot from 2020-07-14 09-52-50](https://user-images.githubusercontent.com/49685489/87383853-fd71c480-c5b7-11ea-9103-94ebcf8cd965.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### Additional info from Engcom
Used the following query
```graphql
query {
  products(search: "Product2", pageSize: 25) {
    aggregations {
      attribute_code
      label
      options {
        count
        label
        value
      }
    }
  }
}

```
response
```graphql
{
  "data": {
    "products": {
      "aggregations": [
        {
          "attribute_code": "price",
          "label": "Price",
          "options": [
            {
              "count": 1,
              "label": "10-20",
              "value": "10_20"
            }
          ]
        },
        {
          "attribute_code": "yes_no",
          "label": "Yes or No",
          "options": [
            {
              "count": 1,
              "label": "0", #<<<< label No if No is selected as value
              "value": "0"
            }
          ]
        }
      ]
    }
  }
}
```

**Comment by engcom-Bravo** [comment] 2021-01-26 09:36
Hello @prabhakaran777 

Thank you for your report.

Yes, it would probably make more sense if the `label` returned _Yes_ or _No_ instead of _1_ or _2_
We Confirm the issue is reproducible on 2.4-develop and move it to GraphQL team.

**Comment by magento-engcom-team** [comment] 2021-01-26 09:37
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40629` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by glo05363** [comment] 2023-03-20 09:45
It will be taken care into one of the Internal [JIRA ticket](https://jira.corp.adobe.com/browse/AC-7920). Once Internal PR will get merged, we will notify.

Thank you!

**Closed as completed** 2023-04-18 14:04 UTC
Labels: Issue: Confirmed, Component: GraphQL, Reproduced on 2.4.x, Priority: P2, Project: GraphQL, PAP, Progress: done, Reported on 2.3.4, Area: Framework

**Comment by engcom-Hotel** [comment] 2023-04-18 14:23
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-7920 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-7920&type=commits

Thanks
