### ISSUE TITLE
Warning: strpos() expects parameter 1 to be string, array given in vendor/magento/module-eav/Model/Entity/Attribute/Source/Table.php

### ISSUE THREAD

**Issue by ngreimel-lt** [magento/magento2#25438] opened 2019-11-01 19:59 UTC
As shown in the title, an error message appears in our system.log file indicating that an array is being passed to `strpos()` which expects a string. This has been known to happen when a product attribute filter is passed as an array rather than a string value. The product grid is properly displaying products, however the filters are not appearing. This is happening on Magento 2.3.2 and has been reported on other versions as can be found on stackoverflow.

### Preconditions (*)

1. M 2.3.3 with Simple Data
2. Magento Cloud - Production
3. Cron installed and running

### Steps to reproduce (*)

1. Visit a PLP. https://example.com/productname
2. Add a filter to this page. https://example.com/productname?size=168
3. Change the query parameter to an array. https://example.com/productname?size[]=168

### Expected result (*)

1. Magento filters product search results to match the given attribute filters.
2. Each selected filter is displayed in the facets section, as well as additional filterable attributes.
![Screen Shot 2019-11-01 at 2 57 09 PM](https://user-images.githubusercontent.com/41348094/68052617-06379a00-fcb8-11e9-8d0a-310973cc0b28.png)

### Actual result (*)

1. Products are filtered.
2. Facets do not display.
3. Error message logged:
![strpos](https://user-images.githubusercontent.com/51681435/69875976-18acef80-12c7-11ea-83b4-23c4d2f2cfce.png)

```
report.CRITICAL: Warning: strpos() expects parameter 1 to be string, array given in vendor/magento/module-eav/Model/Entity/Attribute/Source/Table.php on line 152 [] []
report.CRITICAL: The "catalog.leftnav" block threw an exception, and it can't be rendered. [] []
```
![Screen Shot 2019-11-01 at 2 57 31 PM](https://user-images.githubusercontent.com/41348094/68052623-0d5ea800-fcb8-11e9-9f1e-bea04a405465.png)

**Comment by ngreimel-lt** [comment] 2019-11-01 20:01
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-01 20:01
Hi @ngreimel-lt. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-01 20:02
Hi @ngreimel-lt, here is your [Magento instance](https://i-25438-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25438-2-3-develop.instances.magento-community.engineering/admin](https://i-25438-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ngreimel-lt** [comment] 2019-11-01 20:21
Confirmed present https://i-25438-2-3-develop.instances.magento-community.engineering/apparel.html?size[]=4&size[]=5

**Comment by ngreimel-lt** [comment] 2019-11-01 20:31
Proposed patch:

```patch
diff --git a/app/code/Magento/Eav/Model/Entity/Attribute/Source/Table.php b/app/code/Magento/Eav/Model/Entity/Attribute/Source/Table.php
index 46e4b665cab..56d73422a68 100644
--- a/app/code/Magento/Eav/Model/Entity/Attribute/Source/Table.php
+++ b/app/code/Magento/Eav/Model/Entity/Attribute/Source/Table.php
@@ -143,13 +143,15 @@ class Table extends \Magento\Eav\Model\Entity\Attribute\Source\AbstractSource
     /**
      * Get a text for option value
      *
-     * @param string|integer $value
+     * @param array|string|integer $value
      * @return array|string|bool
      */
     public function getOptionText($value)
     {
         $isMultiple = false;
-        if (strpos($value, ',') !== false) {
+        if (is_array($value)) {
+            $isMultiple = true;
+        } elseif (strpos($value, ',') !== false) {
             $isMultiple = true;
             $value = explode(',', $value);
         }
```

**Comment by edenduong** [comment] 2019-11-01 23:16
@magento I am working on it.

**Comment by edenduong** [comment] 2019-11-04 09:12
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-04 09:12
Hi @edenduong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-04 09:13
Hi @edenduong, here is your [Magento instance](https://i-25438-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25438-2-3-develop.instances.magento-community.engineering/admin](https://i-25438-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-11-29 14:44
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29280` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hilbertknl** [comment] 2019-12-13 09:46
Any update? We're having the same problem.

**Comment by rohit-wagento** [comment] 2020-02-02 08:43
#mm20in

**Comment by magento-engcom-team** [comment] 2020-02-02 08:43
@rohit-wagento thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by Parakoopa** [comment] 2020-02-18 09:53
@rohit-wagento Are you still working on the issue? Otherwise I have the following fix for it and could open a PR if that's okay:

```patch
(in Magento_Theme module:)

diff a/Controller/Result/JsFooterPlugin.php b/Controller/Result/JsFooterPlugin.php
--- a/Controller/Result/JsFooterPlugin.php
+++ b/Controller/Result/JsFooterPlugin.php
@@ -40,7 +40,10 @@
     public function beforeSendResponse(Http $subject)
     {
         $content = $subject->getContent();
+        if ($content === null) {
+            return;
+        }
         $script = [];
         if (strpos($content, '</body') !== false) {
             if ($this->scopeConfig->isSetFlag(
                 self::XML_PATH_DEV_MOVE_JS_TO_BOTTOM,

```

I don't think @ngreimel-lt 's patch above is related to the issue, but maybe I'm missing something

**Comment by bst2002git** [comment] 2020-03-06 09:19
Hello @Parakoopa in Magento 2.4-dev it is fixed as:
https://github.com/magento/magento2/commit/ff1aa7e5f0a37bf13c9c466c50297843bd949d47

-- if (strpos($content, '</body') !== false) {
++ if (is_string($content) && strpos($content, '</body') !== false) {

https://github.com/magento/magento2/raw/2.4-develop/app/code/Magento/Theme/Controller/Result/JsFooterPlugin.php

i've tested the fix on 2.3.3-p1 and it seems to work

**Comment by p810** [comment] 2020-04-19 21:51
Just wanted to chime in here, since I've landed on this thread from Google after having encountered the error on a site I'm working on.

I have a controller that returns an instance of `Magento\Framework\Controller\Result\Json`. If I don't call `setData()` before returning the result object, I get the following error:

```
Fatal error:  Uncaught TypeError: strpos() expects parameter 1 to be string, null given in /Users/pbice/dev/magento/vendor/magento/module-theme/Controller/Result/JsFooterPlugin.php:44
Stack trace:
#0 /Users/pbice/dev/magento/vendor/magento/module-theme/Controller/Result/JsFooterPlugin.php(44): strpos(NULL, '</body')
#1 /Users/pbice/dev/magento/vendor/magento/framework/Interception/Interceptor.php(121): Magento\Theme\Controller\Result\JsFooterPlugin->beforeSendResponse(Object(Magento\Framework\App\Response\Http\Interceptor))
#2 /Users/pbice/dev/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Response\Http\Interceptor->Magento\Framework\Interception\{closure}()
#3 /Users/pbice/dev/magento/generated/code/Magento/Framework/App/Response/Http/Interceptor.php(117): Magento\Framework\App\Response\Http\Interceptor->___callPlugins('sendResponse', Array, Array)
#4 /Users/pbice/dev/m2_ebscomags/vendor/magento/framework/App/Bootstrap.php(262): Magento\Framework\App\Resp in /Users/pbice/dev/magento/vendor/magento/module-theme/Controller/Result/JsFooterPlugin.php on line 44
```

Obviously the fix on my end is very simple, and I'm not entirely sure whether this is a bug, but I figured I would share in case it is. It would be nice to be able to use the `Json` result type without having to always send a payload with the response, which is necessary to prevent the above error, but the workaround isn't anything I feel is worth complaining about.

**Comment by engcom-Delta** [comment] 2020-10-19 10:46
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment] 2020-10-19 12:52
@Parakoopa , @p810 Issue is not reproducible  on 2.4-develop and on the latest composer version 2.4.1
**Result:**
![#25438Issue24](https://user-images.githubusercontent.com/51681379/96453200-cc420980-1222-11eb-9477-59ab94b50f0b.png)


Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Delta** 2020-10-19 12:52 UTC
Labels: Issue: Ready for Work, Issue: Format is valid, Component: Filter, Event: mm20in, Progress: done
