### ISSUE TITLE
`Magento\Checkout\Model\Cart::getQuote()` Returns Incorrect Quote After Using `\Magento\Checkout\Model\Session::replaceQuote($quote)`

### ISSUE THREAD

**Issue by ijozwiak** [magento/magento2#38027] opened 2023-09-29 16:35 UTC
### Preconditions and environment

I've encountered a consistent issue in Magento (affecting all versions) of the checkout session and cart objects. `Magento\Checkout\Model\Cart::getQuote()` Returns Incorrect Quote After Using `\Magento\Checkout\Model\Session::replaceQuote($quote)`

### Steps to reproduce

1. Use the method \Magento\Checkout\Model\Session::replaceQuote($quote) to replace the current checkout session's quote object.
2. After the operation, call \Magento\Checkout\Model\Cart::getQuote().
3. The returned quote is the old quote, not the newly replaced one.

### Expected result

`\Magento\Checkout\Model\Cart::getQuote()` should return the quote recently set with the `replaceQuote($quote)` method.

```
/**
   * \Magento\Checkout\Model\Cart::getQuote()
   * 
*/
public function getQuote()
{
    if (!$this->hasData('quote')) {
        $this->setData('quote', $this->_checkoutSession->getQuote());
    }

    // BEGIN PATCH
    $quote = $this->_getData('quote');

    if ($this->_checkoutSession->getQuoteId() != $quote->getId()) {
        $this->setData('quote', $this->_checkoutSession->getQuote());
    }
    // END PATCH

    return $this->_getData('quote');
}
```

### Actual result

`\Magento\Checkout\Model\Cart::getQuote()` returns the old quote, not the one set using `replaceQuote($quote).`

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2023-10-05 11:34
Hello @ijozwiak,

Thank you for the report and collaboration!

We are not able to reproduce this on 2.4-develop.
We created a custom module to log the quote when opening the route.
And we can see the replaced quote in the logs.
Please find the custom module and let us know if we are missing anything.
[QuoteVendor.zip](https://github.com/magento/magento2/files/12800077/QuoteVendor.zip)

Thank you.

**Comment by engcom-November** [comment] 2023-10-20 10:41
Hello @ijozwiak,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thabk you.

**Closed as completed by engcom-November** 2023-10-20 10:41 UTC
Labels: Triage: Dev.Experience, Priority: P2, Progress: done, Issue: needs update, Reported on 2.4.x
