### ISSUE TITLE
broken setup of configurable products

### ISSUE THREAD

**Issue by vertic4l** [magento/magento2#33854] opened 2021-08-18 18:34 UTC
### Preconditions (*)
Magento 2.4.3

### Steps to reproduce (*)
1. add configurable product
2. add price and set a category where u want to find it later
3. save it
4. set advanced pricing (now you are able to do it, lol)
5. set special price
6. save it
7. index + cache is updated due to cronjob etc.
8. look in frontend, you find the product with special price and it's buyable
9. now associate products to the configurable
10. use attribute like color or size
11. choose some variants
12. skip price, amount and picture setting
13. save it 

### Expected result (*)
1.  associated products use images, price, special price etc. from parent product
2. price and special price are still editable
3. configurable product is still available in frontend
4. variation can be selected in frontend and added to cart

### Actual result (*)
1. configurable product is out of stock in frontend
2. special price is gone and is not editable anymore in backend
3. associated products are virtual products instead of simple products

Why has this changed so badly in Magento2 ?
With Magento1 this was no issue and easy to edit / maintain.

Edit:

And why are all associated products virtual ones instead of simple products?

<img width="1468" alt="Bildschirmfoto 2021-08-18 um 21 21 02" src="https://user-images.githubusercontent.com/1771763/129959209-17334c8d-bd88-41ee-bd38-39acf8577f80.png">

---

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by vertic4l** [comment] 2021-08-18 21:50
@magento give me 2.4-develop instance

**Comment by vertic4l** [comment] 2021-08-18 22:02
![image](https://user-images.githubusercontent.com/1771763/129977934-e897e98e-8f5e-463f-a138-2a9df5b85d06.png)

![image](https://user-images.githubusercontent.com/1771763/129977975-aecdf8b9-bdcb-4e2d-a469-d68ef4f3bb8e.png)


Tested in magento instance

**Comment by vertic4l** [comment] 2021-08-24 14:46
Any update to this very important issue?

**Comment by engcom-Lima** [comment] 2021-08-30 06:23
Hi @vertic4l,

I have gone through the same steps to reproduce the issue and able to find some of the things which you discovered but I think they are expected behaviour due to below reasons:

1. Once you add attributes like color,size etc to the existing configurable product, all the newly added products can have their own inventory and related prices if necessary. Prices by default is inherited from the parent only, you can check by opening the new configured product option.
2. Once new attributes are added, it removes inventory from the parent product so that child products can be defined with more specific inventory.
3. You can change Stock Status to 'In Stock' of the new configured product with inventory assigned and it should be visible on front end with the same pricing as you defined for the parent(If not changed for child).

Furthermore, what I was not able to find was 'Virtual Product' association to the configured products. For me, all products came as 'Simple Product' only. Attached screenshot of same and of 1 product for which I changed Stock Status.

<img width="1322" alt="Screenshot 2021-08-30 at 11 34 08 AM" src="https://user-images.githubusercontent.com/60198022/131293921-b9da8a5d-3de3-4d7f-a600-b89b1675cd63.png">

<img width="1425" alt="Screenshot 2021-08-30 at 11 35 44 AM" src="https://user-images.githubusercontent.com/60198022/131293945-a3ecffa8-2608-48d8-b7c2-0a0cd177015d.png">

Hope that clarifies your doubt. And let me know if you did anything differently to get 'Virtual Product' instead of 'Simple Product' ?

**Comment by vertic4l** [comment] 2021-08-30 12:25
@engcom-Lima 
In the given test instance and locally, associated products become virtual products instead of simple products.
The stock and amount of the associated products don't get recognized therefor the configurable product is still out of stock.

**Comment by vertic4l** [comment] 2021-08-30 12:25
@magento give me 2.4-develop instance

**Comment by vertic4l** [comment] 2021-08-30 12:43
@engcom-Lima tested it again, the test instance behaves now differently which is insane.

Configurable product is now in stock with associated products.
but those are virtual products again.

![image](https://user-images.githubusercontent.com/1771763/131340676-0c52993b-174d-4106-a992-f5639c2ab83f.png)

**Comment by vertic4l** [comment] 2021-08-30 12:49
@magento give me 2.4 instance

**Comment by vertic4l** [comment] 2021-08-30 13:08
This is super weird behaviour. 
With the first instance (2.4-develop - before 12 days) i could reproduce the issue.
With the second instance (2.4-develop) i can't reproduce it.
With the third instance (2.4.3) i can't reproduce it as well.

Unpredictable where the issue comes from but it was there and is there locally in my enviroment.

**Comment by vertic4l** [comment] 2021-08-30 13:24
And still virtual products when creating a configurable product with associated products:

**Comment by jorgb90** [comment] 2021-08-30 14:17
Magento will create virtuals instead of simples when no qty is assigned to them when creating them, but should change from virtual to simple when stock is added and stock is set to managed.

**Comment by vertic4l** [comment] 2021-08-30 14:20
@jorgb90 thanks, but i do enter qty when creating them, see screenshot from above. never heard of default qty.

**Comment by vertic4l** [comment] 2021-09-06 07:50
@engcom-Lima how can we create associated simple products? As you can see, only virtual products were created although quantity etc was given.

**Comment by Bashev** [comment] 2021-09-06 07:56
> 
> 
> @engcom-Lima how can we create associated simple products? As you can see, only virtual products were created although quantity etc was given.

Add weight for configurable product or just choose "This product has weight" BEFORE start to make child products.

![image](https://user-images.githubusercontent.com/1854269/132181074-6ffbf10c-0920-4307-b3d4-7ff6bbeac801.png)

**Comment by engcom-Lima** [comment] 2021-09-10 07:45
Hi @vertic4l,

Have you got the solution to your issues relating to virtual products ? 

As for issue relating to out of stock configurable products, I think it is safe to assume that issue is not there on 2.4-develop or 2.4.3. If you are still able to find the issue relating to stockout while configuring products, please update with some more details on how I can reproduce it at my end.

Thanks

**Comment by engcom-Lima** [comment] 2021-09-24 04:26
Hi @vertic4l,

We have noticed that this issue has not been updated for some time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Lima** 2021-09-24 04:26 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.3, Area: Product
