### ISSUE TITLE
magento cannot connect to elasticsearch, while I can log in.

### ISSUE THREAD

**Issue by f1-outsourcing** [magento/magento2#33579] opened 2021-07-25 17:55 UTC
Install from github branch 2.4

[Progress: 419 / 843]
[Progress: 420 / 843]
Installing search configuration...

In SearchConfig.php line 81:

  Could not validate a connection to Elasticsearch. No alive nodes found in your cluster

setup:install [--consumers-wait-for-messages CONSUMERS-WAIT-FOR-MESSAGES] [--remote-storage-driver REMOTE-STORAGE-DRIVER] [--remote-storage-prefix REMOTE-STORAGE-PREFIX] [--remote-storage-bucket REMOTE-STORAGE-BUCKET] [--remote-storage-region REMOTE-STORAGE-REGION] [--remote-storage-key REMOTE-STORAGE-KEY] [--remote-storage-secret REMOTE-STORAGE-SECRET] [--amqp-host AMQP-HOST] [--amqp-port AMQP-PORT] [--amqp-user AMQP-USER] [--amqp-password AMQP-PASSWORD] [--amqp-virtualhost AMQP-VIRTUALHOST] [--amqp-ssl AMQP-SSL] [--amqp-ssl-options AMQP-SSL-OPTIONS] [--backend-frontname BACKEND-FRONTNAME] [--enable-debug-logging ENABLE-DEBUG-LOGGING] [--enable-syslog-logging ENABLE-SYSLOG-LOGGING] [--key KEY] [--db-host DB-HOST] [--db-name DB-NAME] [--db-user DB-USER] [--db-engine DB-ENGINE] [--db-password DB-PASSWORD] [--db-prefix DB-PREFIX] [--db-model DB-MODEL] [--db-init-statements DB-INIT-STATEMENTS] [-s|--skip-db-validation] [--http-cache-hosts HTTP-CACHE-HOSTS] [--db-ssl-key DB-SSL-KEY] [--db-ssl-cert DB-SSL-CERT] [--db-ssl-ca DB-SSL-CA] [--db-ssl-verify] [--session-save SESSION-SAVE] [--session-save-redis-host SESSION-SAVE-REDIS-HOST] [--session-save-redis-port SESSION-SAVE-REDIS-PORT] [--session-save-redi

While when I login with the magento account, I am getting this:

{"error":{"root_cause":[{"type":"security_exception","reason":"action [cluster:monitor/main] is unauthorized for user [xxxxx] with roles [default], this action is granted by the cluster privileges [monitor,manage,all]"}],"type":"security_exception","reason":"action [cluster:monitor/main] is unauthorized for user [xxxxx] with roles [default], this action is granted by the cluster privileges [monitor,manage,all]"},"status":403}

**Comment by mrtuvn** [comment] 2021-07-26 03:39
make sure you have es service running before install otherwise you may got error like this

**Comment by mrtuvn** [comment] 2021-07-26 03:40
Note "You must install Elasticsearch before installing Adobe Commerce or Magento Open Source 2.4.0. See Elasticsearch for details."

reference https://devdocs.magento.com/guides/v2.4/install-gde/composer.html

**Comment by mrtuvn** [comment] 2021-07-26 03:42
For guide you can reference here
dev guide
https://devdocs.magento.com/
user guide
https://docs.magento.com/user-guide/getting-started.html

**Comment by f1-outsourcing** [comment] 2021-07-26 08:53
> For guide you can reference here
> dev guide
> https://devdocs.magento.com/
> user guide
> https://docs.magento.com/user-guide/getting-started.html

I have already seen those. However I do not know what user roles the magento user login should have. As I wrote, the elasitcsearch task is running and I can login with the user created for magento to use and I can log in with the elastic user and the boostrap password.

 #33578

**Comment by engcom-November** [comment] 2021-07-26 08:53
@f1-outsourcing, Elastic Search must be installed and running before installing Magento 2.4. Please use the ref [guide](https://devdocs.magento.com/guides/v2.4/install-gde/prereq/elasticsearch.html) for the same.
https://devdocs.magento.com/guides/v2.4/install-gde/composer.html
https://docs.magento.com/user-guide/getting-started.html
Kindly re-check and provide detailed steps if the issue is still reproducible.
Thank you.

**Comment by f1-outsourcing** [comment] 2021-07-26 09:41
@engcom-November 

Before continuing:

do you know what node roles are in elasticsearch?
do you know what user roles are in elasticsearch?

**Comment by mrtuvn** [comment] 2021-07-26 19:38
Maybe docs missed some information and need update

**Comment by f1-outsourcing** [comment] 2021-07-26 21:08
I have elasticsearch running in a separate container environment and enabled this x pack security with ssl, it is accessible via haproxy. I created a docker image for el7 because that is what I am mostly running, and configured that with only the node.roles master and data, nothing else.
I created the magento user in elasticsearch only with the default role.
Magento is running on a shared webserver (which of course can access the haproxy and elasticsearch task)

I saw some articles of elasticsearch on multi tenant setups, but did not investigate this any further. But I think this would be good to have in the magento docs as well. Sort of like sharing a mysql db server.

**Comment by f1-outsourcing** [comment] 2021-08-02 09:40
@mrtuvn 
 
Hi Mrtuvn,

I still do not have access to this development strategy stuff. Knowing a bit more about elasticsearch, I am starting to get concerned about the future of the opensource version of magento. I wrote this to some email addresses hoping that it will find it's way to someone that decides on strategy. I put the text here below, because you might be interested in this perspective on the use of elasticsearch.


====
Are you someone who is deciding on strategy? Because from what I read, there is no future in supporting elasticsearch. Furthermore if adobe does not have some license agreement with elastic, they might even be in breach of the current licensing.
If the adobe team finally realizes this, there is no other option to either discontinue this direction of searching or switch to something like the opensearch fork of amazon. However what I have seen[1] from the opensearch documentation, is that the authorization structure is quite different, and for sure not compatible with your manuals.
What I do not get is that amazon was already 'predicting' this license change long ago, so why did nobody notice this here? And this seemed to be quite obvious, because the community was already complaining about that development was not directed at the open source version (sort of like what now happens with magento). If you create a dependency on third party software, you expect this to be done on some reliable research and future strategy. 
If indeed elasticsearch 7.x is from 2021, then whoever forced this dependency in magento 2.4.2 was just sleeping and totally clueless. 
I still do not see anything on the magento website related to this issue, continuing sleeping does not make this problem go away. What is it that you are going to do? Are you going to force people that use magento and take a license with elastic? Is adobe commerce going to start paying licensing fees to elastic for their saas usage of elasticsearch?

You do realize that currently the only supported magento version you offer has a shitty[2] dependency on elasticsearch and therefore only ‘end users’ can legally install and use this. (As if they were already installing magento, because that is so easy). 

To force you out of your sleep and start doing something, I cc’ed elastic and opensearch. I assume you do not have a license agreement with elastic for you commerce cloud, because if you did, that means you have abandoned the opensource direction, and did not officially announce this. 
And since amazon is also offering magento hosted services, they might be interested in forking this project to, so that is why I have included their email addresses as well. 

What I liked about magento is that I could customize it as needed. It has never been fast, but for the few things I have, it is sufficient. I also like I am not sending my clients data across the country border.

Please answer these numbered questions directed at adobe/magento, if you are not authorized to answer these, I assume you as a holder of a @adobe.com address to forward this message to the correct individual who is authorized.

1. Does the adobe magento cloud service, include a license with elastic? Is there some document/statement that confirms this service is legal?
2. Do you intend to maintain the dependency on elasticsearch in the magento opensource version?
3. Are you going to support 2.3 version again, and when? (In case you need more time to think about q 1. and 2.)

Kind regards,

[1]
just recently familiar with this technology

[2]
It looks like your dev team expects users to install elasticsearch and use it without any authentication. Sort of what you saw 15 years ago, install mysql and have the website use root. Putting a httpd service in front of it to authenticate seems even more ridiculous to me since Elasticsearch is already in memory. So what use is putting a httpd in front of it.


====

**Comment by mrtuvn** [comment] 2021-08-02 09:57
Thanks you for share your thoughts! 
But i don't have much information related with elastic search decision. Why magento choose elastic search as default. Current that default search in  2.4.0
Maybe you will interesting new search module created by @qsolutions-pl

**Comment by f1-outsourcing** [comment] 2021-08-03 17:49
Thanks I will bookmark that. However I discovered this magento-lts project, that starts to look appealing to me now. I have to see if I have somewhere the old 1.9 data and convert that.
Magento should have such things as lts versions, that is good thinking.

**Comment by engcom-Lima** [comment] 2021-09-16 06:48
Hi @f1-outsourcing,

Is this issue fixed now for you ? I am asking as there is no update in the latest comments on the original issue that you were not able to connect Magento to elasticsearch.

If you have any other queries, please update your description accordingly so that I can try to reproduce accordingly.

Thanks

**Closed as completed** 2021-09-29 14:22 UTC
Labels: Issue: needs update, Type: Documentation
