### ISSUE TITLE
DIscount amount duplicated if applied to shipping amount

### ISSUE THREAD

**Issue by Axel29** [magento/magento2#35554] opened 2022-05-30 15:40 UTC
### Preconditions and environment

- Magento 2.4.2-p2 (not tested on other versions)

### Steps to reproduce

1. Create a product with a €1 price
2. Create a shipping method with a fixed rate of €19.90
3. Create a cart rule with €19.90 fixed amount discount that applies to the shipping amount with a coupon code
4. Add the product to the cart
5. Apply the discount code

### Expected result

1. The total discount amount should be of €19.90
2. The grand total should be: (1 + 19.90) - 19.90 = €1

### Actual result

1. The discount amount is €20.90
2. The grand total is set to €0.00

___

Cart rule configuration:

![image](https://user-images.githubusercontent.com/3015249/171025143-447cfe2d-b1f5-40a1-aa5b-4fffac3ec69b.png)

New order totals:

![image](https://user-images.githubusercontent.com/3015249/171025173-4c75952e-c58d-4d10-975c-f7f7aafddb4a.png)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Aartivdc** [comment] 2022-05-31 11:26
Hello , I have installed 2.4.2 version in my local and reproduced issue as you mention here 
I got same result as you face, But it is not error , 
let me explain
If you select " Apply to Shipping Amount"  then discount is applied to both subtotal and shipping amount both separately and sum of them 
[ Apply to Shipping Amount](https://i.imgur.com/zD2dJh1.png)
I have set 30 to product price so and fix shipping rate 19.90 
so discount count as 30-19.90 = 10.10
shipping amount 19.90-19.90 = 0  so grand total price is : 10.10
https://i.imgur.com/xHnONIg.png

**Comment by Axel29** [comment] 2022-05-31 11:30
Hello @Aartivdc ,

Thank you for your answer.
But isn't that a weird behaviour though?
I mean the admin wants to set a fixed discount of 19.90€ that includes the shipping amount but the discount is added twice.

Is there a way to have a promotion that would only apply 19.90€ but to both items and shipping fees together?

Thanks again.

**Comment by Aartivdc** [comment] 2022-05-31 11:39
> 

Hello,
There is way if you want to apply discount same as shipping amount than make it off
https://i.imgur.com/ryWcpKl.png

so discount is only apply to subtotal
https://i.imgur.com/Xi2LxDL.png

**Comment by engcom-November** [comment] 2022-05-31 12:08
Hi @Axel29 ,
Thank you for reporting and collaboration. Verified the behavior on Magento 2.4-develop branch however this seems to be an expected behavior.
To answer your question: Is there a way to have a promotion that would only apply 19.90€ but to both items and shipping fees together?
Ans: Cart Price Rule - Actions - "Fixed amount discount for whole cart" option should apply discount on both product and shipping fees together.
![image](https://user-images.githubusercontent.com/60198231/171169361-9bf554ba-220c-4d77-b814-a935a6bd7f29.png)
![image](https://user-images.githubusercontent.com/60198231/171169621-e95be7d4-aea4-4640-bbc4-21c8c63c6a55.png)

As per Magento [docs](https://docs.magento.com/user-guide/marketing/price-rules-cart-create.html), "Fixed amount discount" defined as "Discounts item by subtracting a fixed amount from the original price of each qualifying item in the cart. For example: Enter 10 in Discount Amount for an updated price that is $10 less than the original price."

Kindly recheck again and provide your inputs on this.
Thank you.

**Comment by engcom-November** [comment] 2022-06-15 10:03
Hi @Axel29 ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-06-15 10:03 UTC
Labels: Issue: needs update
