### ISSUE TITLE
Payment Methods stopped showing on checkout

### ISSUE THREAD

**Issue by Lee-Sussy** [magento/magento2#31054] opened 2020-11-25 12:40 UTC
### Preconditions (*)

1. Version 2.2.7
2. Checkout page when product added to cart.  also in individual product pages, the PayPal express checkout is no longer showing.

### Steps to reproduce (*)

1. Add product to cart, go to checkout.  Payment method not available. 
2.

### Expected result (*)

1. There should be an option to input card details or select PayPal express checkout. 
2.

### Actual result (*)

1. Under the Payment Methods column, it now says "Payment method not available"
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by engcom-Alfa** [comment] 2020-11-25 14:28
Hi @Lee-Sussy .

Unfortunately, we are not able to reproduce this issue on fresh 2.4-develop.

**Actual Result:** All included payment methods are displayed on checkout pages

_mini-cart_
![Screenshot from 2020-11-25 16-22-31](https://user-images.githubusercontent.com/51679138/100240039-c682c680-2f3a-11eb-9a96-03146bd339a6.png)

_shopping cart_
![Screenshot from 2020-11-25 16-22-44](https://user-images.githubusercontent.com/51679138/100240067-d0a4c500-2f3a-11eb-928f-cb310ed5eb26.png)

_review&payments_
![Screenshot from 2020-11-25 16-22-16](https://user-images.githubusercontent.com/51679138/100240184-ef0ac080-2f3a-11eb-9698-0f1c338ea395.png)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-11-25 14:28 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.2.x
