### ISSUE TITLE
Included styles.css in design/head/includes is not updated after a change to the base URL

### ISSUE THREAD

**Issue by keithbentrup** [magento/magento2#1388] opened 2015-06-18 16:12 UTC
I changed the base URL value using the admin interface. I confirmed that the web/unsecure/base_url path changed in core_config_data. However, design/head/includes references the old web/unsecure/base_url in its value. 

```
mysql> select * from core_config_data where config_id = 1 or config_id = 11;
+-----------+---------+----------+-----------------------+-----------------------------------------------------------------------------------------------------------------+
| config_id | scope   | scope_id | path                  | value                                                                                                           |
+-----------+---------+----------+-----------------------+-----------------------------------------------------------------------------------------------------------------+
|         1 | default |        0 | web/unsecure/base_url | {{base_url}}                                                                                                    |
|        11 | default |        0 | design/head/includes  | <link  rel="stylesheet" type="text/css"  media="all" href="http://192.168.58.103:32813/pub/media/styles.css" /> |
+-----------+---------+----------+-----------------------+-----------------------------------------------------------------------------------------------------------------+
```

In the output above, I changed base_url from http://192.168.58.103:32813 to "{{base_url}}" using the admin. However, look at the path value for design/head/includes. Also, when I browse to the new base URL in my browser, I see the network request for the old value instead of the updated value.

**Comment by chadbean** [comment] 2015-06-22 04:13
@keithbentrup How did design/head/includes get populated, do you recall? I just installed a new instance of Magento 2, and there was no row in `core_config_data` with the path design/head/includes.

I went to Stores -> Configuration -> General -> Design -> HTML Head and set "Miscellaneous Scripts" to a random value and saved.  Then, when I looked at the core_config_dat the path design/head/includes had that random value.

That is all to say that this is a static field. So if you were to add JavaScript with a reference to a URL in the "Miscellaneous Scripts" section, and then later changed that URL, the "Miscellaneous Scripts" would have no knowledge of that change and would remain as-is.

**Comment by dsikkema** [comment] 2015-07-13 22:42
@keithbentrup just a couple questions - did you manually enter the script into design/head/includes? Did you manually enter the base url into the script or enter it another way?

Thanks!

**Comment by piotrekkaminski** [comment] 2015-10-02 20:51
@keithbentrup can you follow up on @dsikkema question? we are going to close it otherwise.

**Comment by bh-ref** [comment] 2015-10-28 12:13
i now encounter the same problem. i am using the sample data, maybe this is the root cause?

**Comment by davidalger** [comment] 2015-12-15 17:19
This issue was caused by a bug in the sample data (see magento/magento2-sample-data#2). As this should be fixed, I'm going to go ahead and close this. Feel free to re-open the issue if you encounter the issue on a fresh install using the most current release.

**Closed by davidalger** 2015-12-15 17:19 UTC
Labels: bug, PS
