### ISSUE TITLE
Magento 2.2.5: Configurable Product with Only Size Options (No Color Options) Shows No Image in Cart

### ISSUE THREAD

**Issue by uandiweb** [magento/magento2#16843] opened 2018-07-16 04:44 UTC
### Preconditions

1. Magento 2.2.5 (CE)
2. Set in admin: Stores > Configuration > Sales > Checkout > Shopping Cart: "Configurable Product Image: Parent Product Thumbnail"

### Steps to reproduce

1. Create a configurable product with multiple size options, but no color options
2. Assign an image(s) only to the configurable product (not to child/simple products)
3. Visit the product page in the store front and add it to cart. 

### Expected result

1. Product image should show on cart page (coming from configurable product)

### Actual result

1. No product image on cart page (mini cart does show the image)

Feel free to test it with this product page: https://uandi.work/Luma/07-15-2018

**Comment by magento-engcom-team** [comment] 2018-07-16 04:44
Hi @uandiweb. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@uandiweb do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment] 2018-07-16 06:42
Hello @uandiweb, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by nikolinekh** [comment] 2018-07-20 14:17
I have this issue too (on 2.2.5)
For information this is the commit causing the problem: https://github.com/magento/magento2/commit/fb64086b5c0e9b52591ae341e52908fee66f727c

From what I see, the code that uses the ImageBuilder should always set the required product before calling create() - which is the case for e.g. \Magento\Catalog\Block\Product\AbstractProduct

**Comment by sidolov** [comment] 2018-07-23 14:02
Hi @uandiweb. Thank you for your report. 
The issue has been fixed in magento/magento2#16863 by @ronak2ram in 2.2-develop branch
Related commit(s):
 - [108c2c5f6353bf977508baa20cef200521eb247d](https://github.com/magento/magento2/commit/108c2c5f6353bf977508baa20cef200521eb247d)
 - [4e32d060defb692b768b9872d3c24f58bc72b67e](https://github.com/magento/magento2/commit/4e32d060defb692b768b9872d3c24f58bc72b67e)

The fix will be available with the upcoming 2.2.6 release.

**Closed as completed by sidolov** 2018-07-23 14:02 UTC
Labels: Issue: Ready for Work, Component: Checkout, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: ConfigurableProduct
