### ISSUE TITLE
Magento 2.3.0 breaks use of composers --no-dev flag used in production deployments

### ISSUE THREAD

**Issue by davidalger** [magento/magento2#18842] opened 2018-10-26 19:12 UTC
### Preconditions (*)

1. Install Magento 2.3.0-beta23
2. Use the `--no-dev` flag during composer install
3. Subsequent calls to `bin/magento setup:di:compile` will fail

### Steps to reproduce (*)

1. Run following procedures. Note the first DI compile succeeds, and the one following the install with `--no-dev` fails with a fatal error:

```bash
vagrant@dev-web72:07:01 PM:/var/www/sites$ composer create-project -q --no-install --repository-url https://repo.magento.com/ magento/project-community-edition m2test 2.3.0-beta23
vagrant@dev-web72:07:02 PM:/var/www/sites$ cd m2test/
vagrant@dev-web72:07:02 PM:/var/www/sites/m2test$ composer install -q
vagrant@dev-web72:07:05 PM:/var/www/sites/m2test$ bin/magento module:enable --all -q
vagrant@dev-web72:07:06 PM:/var/www/sites/m2test$ bin/magento setup:di:compile
Compilation was started.
Interception cache generation... 7/7 [============================] 100% 2 mins 355.0 MiB
Generated code and dependency injection configuration successfully.
vagrant@dev-web72:07:09 PM:/var/www/sites/m2test$ composer install -q --no-dev
vagrant@dev-web72:07:09 PM:/var/www/sites/m2test$ bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% 2 secs 70.5 MiBPHP Fatal error:  Class 'PHPUnit\Framework\TestCase' not found in /var/www/sites/m2test/vendor/vertex/module-tax/Test/Unit/TestCase.php on line 14
PHP Stack trace:
PHP   1. {main}() /var/www/sites/m2test/bin/magento:0
PHP   2. Magento\Framework\Console\Cli->run() /var/www/sites/m2test/bin/magento:23
PHP   3. Magento\Framework\Console\Cli->doRun() /var/www/sites/m2test/vendor/symfony/console/Application.php:145
PHP   4. Magento\Framework\Console\Cli->doRun() /var/www/sites/m2test/vendor/magento/framework/Console/Cli.php:102
PHP   5. Magento\Framework\Console\Cli->doRunCommand() /var/www/sites/m2test/vendor/symfony/console/Application.php:262
PHP   6. Magento\Setup\Console\Command\DiCompileCommand->run() /var/www/sites/m2test/vendor/symfony/console/Application.php:886
PHP   7. Magento\Setup\Console\Command\DiCompileCommand->execute() /var/www/sites/m2test/vendor/symfony/console/Command/Command.php:255
PHP   8. Magento\Setup\Module\Di\App\Task\Manager->process() /var/www/sites/m2test/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php:206
PHP   9. Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation() /var/www/sites/m2test/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php:56
PHP  10. Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList() /var/www/sites/m2test/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php:61
PHP  11. Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract() /var/www/sites/m2test/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:82
PHP  12. Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClasses() /var/www/sites/m2test/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:111
PHP  13. class_exists() /var/www/sites/m2test/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:125
PHP  14. spl_autoload_call() /var/www/sites/m2test/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:125
PHP  15. Composer\Autoload\ClassLoader->loadClass() /var/www/sites/m2test/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:125
PHP  16. Composer\Autoload\includeFile() /var/www/sites/m2test/vendor/composer/ClassLoader.php:322
PHP  17. include() /var/www/sites/m2test/vendor/composer/ClassLoader.php:444
PHP  18. spl_autoload_call() /var/www/sites/m2test/vendor/vertex/module-tax/Test/Unit/Observer/CreditMemoObserverTest.php:19
PHP  19. Composer\Autoload\ClassLoader->loadClass() /var/www/sites/m2test/vendor/vertex/module-tax/Test/Unit/Observer/CreditMemoObserverTest.php:19
PHP  20. Composer\Autoload\includeFile() /var/www/sites/m2test/vendor/composer/ClassLoader.php:322
PHP  21. include() /var/www/sites/m2test/vendor/composer/ClassLoader.php:444

Fatal error: Class 'PHPUnit\Framework\TestCase' not found in /var/www/sites/m2test/vendor/vertex/module-tax/Test/Unit/TestCase.php on line 14

Call Stack:
    0.0002     391360   1. {main}() /var/www/sites/m2test/bin/magento:0
   12.4960   56061752   2. Magento\Framework\Console\Cli->run() /var/www/sites/m2test/bin/magento:23
   12.5034   56087576   3. Magento\Framework\Console\Cli->doRun() /var/www/sites/m2test/vendor/symfony/console/Application.php:145
   12.5034   56087576   4. Magento\Framework\Console\Cli->doRun() /var/www/sites/m2test/vendor/magento/framework/Console/Cli.php:102
   13.5226   56000944   5. Magento\Framework\Console\Cli->doRunCommand() /var/www/sites/m2test/vendor/symfony/console/Application.php:262
   13.5226   56000944   6. Magento\Setup\Console\Command\DiCompileCommand->run() /var/www/sites/m2test/vendor/symfony/console/Application.php:886
   13.5230   56005984   7. Magento\Setup\Console\Command\DiCompileCommand->execute() /var/www/sites/m2test/vendor/symfony/console/Command/Command.php:255
   16.1784   57290888   8. Magento\Setup\Module\Di\App\Task\Manager->process() /var/www/sites/m2test/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php:206
   17.7657   69032768   9. Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation() /var/www/sites/m2test/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php:56
   46.8584  211292968  10. Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList() /var/www/sites/m2test/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php:61
   46.8586  211301944  11. Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract() /var/www/sites/m2test/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:82
   46.8810  211753464  12. Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClasses() /var/www/sites/m2test/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:111
   46.8810  211753464  13. class_exists() /var/www/sites/m2test/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:125
   46.8810  211753544  14. spl_autoload_call() /var/www/sites/m2test/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:125
   46.8810  211753624  15. Composer\Autoload\ClassLoader->loadClass() /var/www/sites/m2test/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:125
   46.8811  211753784  16. Composer\Autoload\includeFile() /var/www/sites/m2test/vendor/composer/ClassLoader.php:322
   46.8817  211786624  17. include('/var/www/sites/m2test/vendor/vertex/module-tax/Test/Unit/Observer/CreditMemoObserverTest.php') /var/www/sites/m2test/vendor/composer/ClassLoader.php:444
   46.8817  211786624  18. spl_autoload_call() /var/www/sites/m2test/vendor/vertex/module-tax/Test/Unit/Observer/CreditMemoObserverTest.php:19
   46.8817  211786680  19. Composer\Autoload\ClassLoader->loadClass() /var/www/sites/m2test/vendor/vertex/module-tax/Test/Unit/Observer/CreditMemoObserverTest.php:19
   46.8819  211786792  20. Composer\Autoload\includeFile() /var/www/sites/m2test/vendor/composer/ClassLoader.php:322
   46.8829  211796872  21. include('/var/www/sites/m2test/vendor/vertex/module-tax/Test/Unit/TestCase.php') /var/www/sites/m2test/vendor/composer/ClassLoader.php:444

```

### Expected result

1. The popular capistrano-magento2 (and presumable many other) pipeline deployments use `--no-dev` when deploying Magento 2 into a production and/or stage environment as the dev packages should not be necessary and add extra weight to production. 
2. Magento 2.3 should not break existing deployment pipelines using `composer install --no-dev`

### Actual result

1. See error output in steps to reproduce above.

**Comment by magento-engcom-team** [comment] 2018-10-26 19:12
Hi @davidalger. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@davidalger do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [x] no

**Comment by davidalger** [comment] 2018-10-26 19:14
@magento-engcom-team There is no way to reproduce this in the test instance as it is dependent on having access to the CLI. Please see exact commands above and let me know if any further information is needed to get this resolved before 2.3 hits GA. Thanks!

**Comment by magento-engcom-team** [comment] 2018-10-28 14:54
Hi @navarr. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2018-10-28 14:56
@navarr Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2018-10-28 14:57
@navarr Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95951` were created

**Comment by navarr** [comment] 2018-10-28 15:02
Hi @davidalger,

This was an issue introduced with Vertex 2.2.1-beta2, and is fixed in Vertex 2.2.1-beta3.

Until that is available, you can work around it by modifying the Vertex registration.php file to be

```php
<?php
/**
 * @copyright  Vertex. All rights reserved.  https://www.vertexinc.com/
 * @author     Mediotype                     https://www.mediotype.com/
 */

use Magento\Framework\Component\ComponentRegistrar;

ComponentRegistrar::register(
    ComponentRegistrar::MODULE,
    'Vertex_Tax',
    isset($file) ? realpath(dirname($file)) : __DIR__
);
```

**Closed as completed** 2018-10-28 15:02 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Bundled Extension

**Comment by davidalger** [comment] 2018-10-29 13:33
Thanks @navarr!

**Comment by navarr** [comment] 2018-10-29 15:39
@davidalger no thanks needed, I introduced the bug 😅

Gotcha: if you have a non-realpath as your module's registered path, object manager can't properly match the test directory pattern and you get this issue
