### ISSUE TITLE
multiple website cart rule issue

### ISSUE THREAD

**Issue by egygamercom** [magento/magento2#37867] opened 2023-08-08 18:28 UTC
### Preconditions and environment

- Magento version 2.4.3
- Anything else that would help a developer reproduce the bug

we are using one global magento installation for two websites with two different domains,

website A
website B

### Steps to reproduce

1 - created same cart rule and assigned them to both websites A and B

### Expected result

coupon code is applied on both websites 

### Actual result

the actual result: 

on website A : invalid
on website B : applied

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by egygamercom** [comment] 2023-08-09 21:16
sorry the issue on magento 2.4.3

**Comment by engcom-Dash** [comment] 2023-08-10 11:28
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-09-04 10:19
Hi @egygamercom,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

-  created same cart rule and assigned them to both websites A and B

<img width="1320" alt="Screenshot 2023-09-04 at 3 45 17 PM" src="https://github.com/magento/magento2/assets/51680745/cc9bcaa4-ec17-450c-8329-b3b57e6db586">



<img width="1315" alt="Screenshot 2023-09-04 at 3 45 42 PM" src="https://github.com/magento/magento2/assets/51680745/b435170f-cafb-4cbf-90d3-485a46a24b45">



We have created Cart Price Rule and it is applying for two different websites.


Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-09-15 06:23
Hi @egygamercom,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/37867#issuecomment-1705002878 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-09-25 06:13
Hi @egygamercom,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-09-25 06:13 UTC
Labels: Issue: needs update, Reported on 2.4.3
