### ISSUE TITLE
All the admin is broken after I update Admin Base URL: Use Custom Admin URL to YES), Not able to revert this setting (Admin Base URL: Use Custom Admin URL)

### ISSUE THREAD

**Issue by sravanigogineni89** [magento/magento2#33657] opened 2021-08-02 10:27 UTC
### Preconditions (*)

1.Magento ver. 2.4.1
2. All the admin is broken after I update Admin Base URL: Use Custom Admin URL to YES), Not able to revert this setting (Admin Base URL: Use Custom Admin URL)

### Steps to reproduce (*)

1.Stores -> Settings -> Configurations - >
2.
![adminURLIssue](https://user-images.githubusercontent.com/56364730/127847180-e97f1138-e67e-4dd8-b727-6c23a6455d4c.png)

### Expected result (*)

1. ![adminURLIssue](https://user-images.githubusercontent.com/56364730/127847205-143dca3b-2116-4587-b6ce-caa7adeef8b2.png)
2.Expecting to use site with the new URL updated, or at least to revert the update to use the admin normal.
CURRENTLY NOT ABLE TO USE THE ADMIN SITE AS EVERYTHING WAS BORKEN.

### Actual result (*)

1. 
![image](https://user-images.githubusercontent.com/56364730/127847774-3f9e4976-017b-40c4-94b7-4767558f38d8.png)

2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [1 ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment] 2021-08-02 10:53
@magento give me 2.4-develop instance

**Comment by mrtuvn** [comment] 2021-08-02 13:41
Custom path still working But Custom url may broken

**Comment by sravanigogineni89** [comment] 2021-08-02 13:49
Here is what we are seeing:
![image](https://user-images.githubusercontent.com/56364730/127872155-d98894ee-f7ac-45d1-9c8e-6329579f361a.png)

**Comment by mrtuvn** [comment] 2021-08-02 14:09
after change url custom for admin i can't access to admin. Redirect to 404 page. But entire page not break as your describe
Custom path still working

**Comment by sravanigogineni89** [comment] 2021-08-02 14:10
I am still able to access admin but not able to revert it back, all css and all js broken.
I am not able to do any thing

**Comment by sravanigogineni89** [comment] 2021-08-02 14:44
we are using magento 2 in bitnami, not seeing the table core_config in the db, any ideas on how we can do that in the database.

**Comment by mrtuvn** [comment] 2021-08-02 14:49
use any mysql client to access your db, or ssh to mysql and update via commandline
Or you can use adminer https://www.adminer.org/

**Comment by sravanigogineni89** [comment] 2021-08-02 16:41
I am able to access my DB now, can someone please provide me the updates that need to be run to change these
![image](https://user-images.githubusercontent.com/56364730/127895520-d3848b66-b2fe-4178-bc21-651ce8aec4be.png)

**Comment by mrtuvn** [comment] 2021-08-02 17:33
imho this problem not too critical because reproduce problem need extra config for replicate. It's not directly block user at default. We can have P3 or P4 for this problem. But we definitely should re-check custom url case
Let's wait final confirm

**Comment by sravanigogineni89** [comment] 2021-08-03 07:05
can someone please provide me the updates that need to be run to change these
![Untitled](https://user-images.githubusercontent.com/56364730/127972516-57035edb-ce63-4c14-8119-72de36d8c759.png)

**Comment by engcom-Echo** [comment] 2021-08-18 14:43
@magento give me 2.4-develop instance

**Comment by mrtuvn** [comment] 2021-08-18 14:50
Admin > Config
Use Custom Admin Url => YES
Fill custom url path
"The Admin URL must be in the same Magento installation, and have the same document root as the storefront."
I think we can't change total url here seem it's related with entire infras configuration

**Comment by mrtuvn** [comment] 2021-08-18 14:59
```php
'system' => [
        'default' => [
            'admin' => [
                'url' => [
                    'use_custom' => '1',
                    'custom' => 'https://same_default_url_install/'
                ]
            ]
       ]
]
```

**Comment by engcom-Echo** [comment] 2021-08-18 15:00
Hi @sravanigogineni89 
We tried to reproduce this issue on **2.4-develop** & were unable to do so.
Here are the Steps we followed,
1. Login into admin panel 
2. Go to **Stores** -> **Settings** -> **Configurations** - > **Advanced** -> **Admin**
3. Set **Use Custom Admin URL** to **Yes**.
Enter the Custom Admin URL - **The Admin URL must be in the **same** Magento installation, and have the same document root as the storefront.**
**Set Custom Admin Path** to **Yes**.
Enter the Custom Admin Path - The path that you enter is appended to the Custom Admin URL after the last forward slash.
4. Once done with above steps click **Save Config.**
5. After the changes are saved, **Sign Out** of the Admin. Then, log back in using the **new Admin URL and path**.

Reference : [https://docs.magento.com/user-guide/stores/store-urls-custom-admin.html](url) 

So kindly recheck this issue on Magento 2.4-develop branch and if the issue is still reproducible, please provide more details or additional/missing steps regarding the same.

Thank you.

**Comment by engcom-Echo** [comment] 2021-09-01 07:29
Hi @sravanigogineni89 
Since we didn't get any updates from you & since we couldn't reproduce the issue being reported, we are closing this issue.
If this issue is still reproducible for you on magento **2.4-develop**, please feel free to reopen this issue & provide more details or additional/missing steps regarding the same.

Thank you

**Closed as completed by engcom-Echo** 2021-09-01 07:29 UTC
Labels: Issue: needs update
