### ISSUE TITLE
Image resize from CLI is not working for all media attributes

### ISSUE THREAD

**Issue by amansrivastava** [magento/magento2#3573] opened 2016-02-29 07:44 UTC
`php bin/magento catalog:images:resize`
When executing this command, only swatch_image and swatch_thumb attributes have resized images and when I looked into code, view.xml in module-swatches being executed rather than view.xml from theme directory.
view.xml exist in blank and luma theme but doesn't impact the output.

**Comment by amansrivastava** [comment] 2016-03-15 05:35
@MomotenkoNatalia any updates ?

**Comment by MomotenkoNatalia** [comment] 2016-03-16 18:16
@amansrivastava 
I'm sorry for the delay. Thanks for reporting this issue! 
Internal ticket MAGETWO-50553.

**Comment by cedricblondeau** [comment] 2016-04-07 02:52
Looks like it has been fixed on develop branch : https://github.com/magento/magento2/commit/53eb7b7569d378c879456cc7e83e85acd6ffadf4#diff-88b36d43a34dcd4d0d151453c13871b6

**Comment by AntonEvers** [comment] 2016-04-13 11:36
Yes, confirmed. This fixes it. Now just a matter of time :+1:

**Comment by magento-engcom-team** [comment] 2017-09-20 18:14
@amansrivastava thank you for the report. The fix is available in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 18:14 UTC
Labels: Issue: Ready for Work, bug report, Area: Frontend, Issue: Clear Description, Fixed in 2.2.x, Issue: Format is not valid
