### ISSUE TITLE
No Design appearing

### ISSUE THREAD

**Issue by RealsaAdministrador** [magento/magento2#22487] opened 2019-04-24 22:04 UTC
### Summary (*)

The area in Stores >Configuration>General>Design is no more! Is it an actualization? Where's the Design Theme, HTML Head, etc. then? Sorry if this is already posted I can't find it anywhere and it's not appearing in the search box

### Examples (*)

It's just not there 
![image](https://user-images.githubusercontent.com/49961249/56696930-ed1fb200-66b2-11e9-8984-a26642e3b218.png)

**Comment by RealsaAdministrador** [comment] 2019-04-24 22:22
@magento-engcom-team give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment] 2019-04-24 22:22
Hi @RealsaAdministrador. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-24 22:23
Hi @RealsaAdministrador, here is your [Magento instance](https://i-22487-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22487-2-3-develop.instances.magento-community.engineering/admin](https://i-22487-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by RealsaAdministrador** [comment] 2019-04-24 22:44
![image](https://user-images.githubusercontent.com/49961249/56698719-8c937380-66b8-11e9-95d1-b45426e0d6e0.png)

Hi, it's still not there

I don't think I'm understanding :(

**Comment by orlangur** [comment] 2019-04-24 23:34
Hi @RealsaAdministrador, please try searching prior to issue creation 😉 

Duplicate of https://github.com/magento/magento2/issues/5240

**Closed as completed by orlangur** 2019-04-24 23:34 UTC
Labels: Issue: Format is valid
