### ISSUE TITLE
Valid domain name not allowed for use as customer email address

### ISSUE THREAD

**Issue by kanevbg** [magento/magento2#38549] opened 2024-03-24 20:31 UTC
### Preconditions and environment

- Magento version: 2.4.6
- Example email registered with magento 2.3.7-p2 now considered invalid: something@röser-REPLACED.de (the issue comes from the ö, but the customer actually owns a domain name including that symbol, and it's obvious it's operating email address with that domain name)

### Steps to reproduce

In my case the situation was:
- Magento 2.3.7-p2 instance with customer registered with email-address like something@röser-REPLACED.de.
- Upgrade to 2.4.6
- Upgrade customer password encryption algorithm with the Magento's build-in command:
```
bin/magento customer:hash:upgrade
```

### Expected result

Successful upgrade of the customers encrypted passwords.

### Actual result

Exception:
```
In Customer.php line 263:
                                                                                                                          
  [Magento\Framework\Validator\Exception]                                                                                 
  "Email" is not a valid hostname.                                                                                        
  'r?ser-REPLACED.de' looks like a DNS hostname but we cannot match it against the hostname schema for TLD 'DE'.  
  'r?ser-REPLACED.de' does not look like a valid local network name.                                              

Exception trace:
  at /deps/releases/312b889_1711286233/vendor/magento/module-customer/Model/ResourceModel/Customer.php:263
 Magento\Customer\Model\ResourceModel\Customer->_validate() at /deps/releases/312b889_1711286233/vendor/magento/module-customer/Model/ResourceModel/Customer.php:194
 Magento\Customer\Model\ResourceModel\Customer->_beforeSave() at /deps/releases/312b889_1711286233/vendor/magento/module-eav/Model/Entity/VersionControl/AbstractEntity.php:90
 Magento\Eav\Model\Entity\VersionControl\AbstractEntity->save() at /deps/releases/312b889_1711286233/vendor/magento/framework/Interception/Interceptor.php:58
 Magento\Customer\Model\ResourceModel\Customer\Interceptor->___callParent() at /deps/releases/312b889_1711286233/vendor/magento/framework/Interception/Interceptor.php:148
 Magento\Customer\Model\ResourceModel\Customer\Interceptor->Magento\Framework\Interception\{closure}() at /deps/releases/312b889_1711286233/app/code/Custom/Module/Model/Event/Plugin/Customer.php:78
 Custom\Module\Model\Event\Plugin\Customer->aroundSave() at /deps/releases/312b889_1711286233/vendor/magento/framework/Interception/Interceptor.php:142
 Magento\Customer\Model\ResourceModel\Customer\Interceptor->Magento\Framework\Interception\{closure}() at /deps/releases/312b889_1711286233/vendor/magento/module-checkout/Model/Plugin/RecollectQuoteOnCustomerGroupChange.php:77
 Magento\Checkout\Model\Plugin\RecollectQuoteOnCustomerGroupChange->aroundSave() at /deps/releases/312b889_1711286233/vendor/magento/framework/Interception/Interceptor.php:142
 Magento\Customer\Model\ResourceModel\Customer\Interceptor->Magento\Framework\Interception\{closure}() at /deps/releases/312b889_1711286233/vendor/magento/framework/Interception/Interceptor.php:169
 Magento\Customer\Model\ResourceModel\Customer\Interceptor->___callPlugins() at /deps/releases/312b889_1711286233/generated/code/Magento/Customer/Model/ResourceModel/Customer/Interceptor.php:23
 Magento\Customer\Model\ResourceModel\Customer\Interceptor->save() at /deps/releases/312b889_1711286233/vendor/magento/framework/Model/AbstractModel.php:663
 Magento\Framework\Model\AbstractModel->save() at /deps/releases/312b889_1711286233/vendor/magento/framework/Interception/Interceptor.php:58
 Magento\Customer\Model\Customer\Interceptor->___callParent() at /deps/releases/312b889_1711286233/vendor/magento/framework/Interception/Interceptor.php:148
 Magento\Customer\Model\Customer\Interceptor->Magento\Framework\Interception\{closure}() at /deps/releases/312b889_1711286233/vendor/magento/framework/Interception/Interceptor.php:169
 Magento\Customer\Model\Customer\Interceptor->___callPlugins() at /deps/releases/312b889_1711286233/generated/code/Magento/Customer/Model/Customer/Interceptor.php:32
 Magento\Customer\Model\Customer\Interceptor->save() at /deps/releases/312b889_1711286233/vendor/magento/module-customer/Console/Command/UpgradeHashAlgorithmCommand.php:75
 Magento\Customer\Console\Command\UpgradeHashAlgorithmCommand->execute() at /deps/releases/312b889_1711286233/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /deps/releases/312b889_1711286233/vendor/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at /deps/releases/312b889_1711286233/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at /deps/releases/312b889_1711286233/vendor/magento/framework/Console/Cli.php:116
 Magento\Framework\Console\Cli->doRun() at /deps/releases/312b889_1711286233/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /deps/releases/312b889_1711286233/bin/magento:23

customer:hash:upgrade
```

### Additional information

The root of the problem is the introduction of the email address validator run before customer model save, which itself seems to be not supporting all real/valid domain names.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2024-03-25 10:22
@magento give me 2.4-develop instance

**Comment by heerdt** [comment] 2024-03-26 16:13
@magento give me 2.4-develop instance

**Comment by kanevbg** [comment] 2024-03-29 19:15
https://github.com/magento give me 2.4-develop instance

**Comment by kanevbg** [comment] 2024-03-29 19:16
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2024-04-03 13:16
Hi @kanevbg 

Thanks for reporting and collaboration.

Verified the issue after upgrading the instance from 2.3.7-p2 to 2.4.6-p4 and the issue is not reproducable.

In my case the situation was:

1.Magento 2.3.7-p2 instance with customer registered with email-address like something@röser-REPLACED.de.
2.Upgrade to 2.4.6
3.Upgrade customer password encryption algorithm with the Magento's build-in command:
`bin/magento customer:hash:upgrade`

Successfully upgraded the customers encrypted passwords.

Please refer the attached screenshots.

<img width="1440" alt="Screenshot 2024-04-03 at 12 56 35 PM" src="https://github.com/magento/magento2/assets/60198592/f0eb86a9-eea7-487f-85e8-fb9e12ecd432">
<img width="1440" alt="Screenshot 2024-04-03 at 5 47 19 PM" src="https://github.com/magento/magento2/assets/60198592/26506dfe-fb32-41e2-a93d-44428b1cdf98">
<img width="1440" alt="Screenshot 2024-04-03 at 5 47 03 PM" src="https://github.com/magento/magento2/assets/60198592/603fee1d-7df5-4103-91c7-0337efb38350">
<img width="1440" alt="Screenshot 2024-04-03 at 5 35 14 PM" src="https://github.com/magento/magento2/assets/60198592/b873e20b-1d6d-4f10-8184-7505627f659b">
<img width="1440" alt="Screenshot 2024-04-03 at 5 35 07 PM" src="https://github.com/magento/magento2/assets/60198592/d4a87ec0-f074-4fd3-a141-3bc32c45bf5b">

Let us know if we have missed anything.

**Comment by engcom-Dash** [comment] 2024-04-16 07:43
Hi @kanevbg 

We have noticed that this issue has not been updated for a long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel free to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2024-04-16 07:43 UTC
Labels: Issue: needs update, Reported on 2.4.6
