### ISSUE TITLE
"No Payment Information Required" is removed from Billing Information page

### ISSUE THREAD

**Issue by phuc128t** [magento/magento2#6394] opened 2016-08-30 10:22 UTC
### Preconditions

Magento 2.0.9 with default luma theme, PHP 7.0.9-1+deb.sury.org~xenial+1 and mysql  Ver 14.14 Distrib 5.7.13
### Steps to reproduce

1. Install magento 2.0.9 and add some products to cart
2. Apply discount and gift card to make grand total = 0
### Expected result

1. Should show "No Payment Information Required" at billing information page
### Actual result

1. "No Payment Information Required" shows but removed immediately 
   ![2016-08-30_17-20-51](https://cloud.githubusercontent.com/assets/1607243/18085664/4cd48a22-6ed6-11e6-8ff6-2b3023b1c69b.png)

**Comment by SerhiyShkolyarenko** [comment] 2016-09-21 09:56
@eric128 thank you for reporting!
Gift card is enterprize edition functionality, it is supported on another channel. Let's look at cart price rule which covers all the cart goods and shipping. Is the issue reproducible for you in such case? 
Is it reproducible on 2.1.1 version?
Do you use any custom themes or extensions?

**Comment by SerhiyShkolyarenko** [comment] 2016-10-11 12:27
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by SerhiyShkolyarenko** 2016-10-11 12:27 UTC
Labels: bug report, Progress: needs update, Component: Checkout
