### ISSUE TITLE
Luma theme Apply Discount Code section design improvement

### ISSUE THREAD

**Issue by abrarpathan19** [magento/magento2#21214] opened 2019-02-14 06:04 UTC
### Description (*)

Luma theme Apply Discount Code section design improvement according to shopping cart page  Discount Coupon box section. please review link : Shopping Cart page : http://prntscr.com/mkvc7o

Step to reproduce : 
1. Luma theme Go to the checkout Review & Payments step you can find the coupon box section

### Expected behavior (*)

Checkout page step "Review & Payments" : http://prntscr.com/mkvcoa
It should be according to shoping cart page coupon box section.

### Benefits

According to frontend developer, We need to redisign checkout page coupon box section redesign as per the soping cart page design. It will be good if it is diplying in one row. 

### Additional information

Currently it is diplaying in two rows  : http://prntscr.com/mkvcgk 
It will be good if it is diplying in one row.

**Comment by magento-engcom-team** [comment] 2019-02-14 06:04
Hi @abrarpathan19. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@abrarpathan19 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-02-14 06:05
Hi @krishprakash. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by krishprakash** [comment] 2019-02-14 06:07
@magento-engcom-team give me 2.3-develop instance.

**Comment by magento-engcom-team** [comment] 2019-02-14 06:07
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-14 06:08
Hi @krishprakash, here is your [Magento instance](https://i-21214-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21214-2-3-develop.instances.magento-community.engineering/admin](https://i-21214-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2019-02-14 06:15
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-14 06:15
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-14 06:16
Hi @krishprakash, here is your [Magento instance](https://i-21214-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21214-2-2-develop.instances.magento-community.engineering/admin](https://i-21214-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Closed as completed** 2019-03-07 09:55 UTC
Labels: improvement, Component: Checkout, Issue: Clear Description, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Issue: Format is valid, Area: Design/Frontend

**Comment by sidolov** [comment] 2019-05-24 17:07
Hi @abrarpathan19. Thank you for your report. 
The issue has been fixed in magento/magento2#23009 by @niravkrish in 2.2-develop branch
Related commit(s):
 - [bea33600caa576d48234ef3aee4b428f1898a2d6](https://github.com/magento/magento2/commit/bea33600caa576d48234ef3aee4b428f1898a2d6)

The fix will be available with the upcoming 2.2.10 release.
