### ISSUE TITLE
Wishlist module turns the whole site to 404

### ISSUE THREAD

**Issue by harshvardhanmalpani** [magento/magento2#10876] opened 2017-09-13 19:21 UTC
The magento2.1.8 instance is working good except this one issue.
Whenever a user wants to add any product in wishlist, he is redirected to login page (/customer/account/login/).
After he logs in successfully, he is redirected to https://domain.com/wishlist/index/index/wishlist_id/1/
and sees an error
##404 error: Page not found.
**The problem doesn't end here, The logged in user sees the same error for whole website (homepage or any other page).**

### Preconditions
1.  Magento v 2.1.8
2. PHP 7.0 on apache and nginx.

### Steps to reproduce
User wants to add any product in wishlist, he is redirected to login page (/customer/account/login/).
After he logs in successfully, he is redirected to https://domain.com/wishlist/index/index/wishlist_id/1/
and sees an error
### Expected result
The wishlist should be working normally 

### Actual result
![capture-20170914-004633](https://user-images.githubusercontent.com/2611741/30396221-8f5d549c-98e6-11e7-8622-6130ef0ac2d4.png)

I have removed the social login module from the setup and have used commands: upgrade, compile, cache flush and content deploy. Issue persists.

##EDIT -
The same setup works just fine on other websites I have deployed. This particular project has the issue. I had **re-updated** the Magento version to 2.1.8 using composer, issue is still there.

**Comment by harshvardhanmalpani** [comment] 2017-09-13 23:11
After a lot of digging around, I came to conclusion that it can possibly be related to #3812 and convincingly pointing to an error in my custom theme

**Comment by magento-engcom-team** [comment] 2017-09-22 10:54
@harshvardhanmalpani thank you for your report. We cannot reproduce this issue as described. Please provide the detailed steps we must follow to reproduce this issue. In addition, identify the web server you are running  and any other information needed to reproduce your issue.

**Comment by orlangur** [comment] 2017-09-22 11:24
> The same setup works just fine on other websites I have deployed. This particular project has the issue. I had re-updated the Magento version to 2.1.8 using composer, issue is still there.

Bugs of "this particular project" cannot be fixed in Magento core. You need to find out what's going wrong on your side, ideally reproduce a bug on clean Magento installation.

Of course, there is always probability bug is in the core, just wasn't revealed on your other projects due to a different configuration. But you need to debug a problematic project to locate a problematic code.

**Comment by magento-engcom-team** [comment] 2017-09-22 16:17
@harshvardhanmalpani, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Closed as completed by magento-engcom-team** 2017-09-22 16:17 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid
