### ISSUE TITLE
GraphQl ProductInterface custom_attributes is empty on BundleProduct items

### ISSUE THREAD

**Issue by nmarquez2** [magento/magento2#38197] opened 2023-11-16 18:55 UTC
### Preconditions and environment

Magento version 2.4.6-p3

Trying to query custom_attributes on bundle items returns an empty array unless an attribute itself is specified in the selected ProductInterface properties then in that case the custom_attributes data will contain only that specified attribute.

### Steps to reproduce

Query a bundle product and select custom_attributes on its options
```
{
  products(filter: {sku: {eq: "XYZ"}}) {
    items {
      sku
      ... on BundleProduct {
        items {
          options {
            product {
              sku
              custom_attributes {
                selected_attribute_options {
                  attribute_option {
                    uid
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
``` 

### Expected result

```
{
  "data": {
    "products": {
      "items": [
        {
          "sku": "SKU",
          "items": [
            {
              "options": [
                {
                  "product": {
                    "sku": "OPTION_SKU",
                    "custom_attributes": [
                      {
                        "selected_attribute_options": {
                          "attribute_option": [
                            {
                              "uid": "..."
                            }
                          ]
                        }
                      },
					  {
                        "selected_attribute_options": {
                          "attribute_option": [
                            {
                              "uid": "..."
                            }
                          ]
                        }
                      },
					  ...
                    ]
                  }
                }
              ]
            }
          ]
        }
      ]
    }
  }
}
``` 

### Actual result

```
{
  "data": {
    "products": {
      "items": [
        {
          "sku": "XYZ",
          "items": [
            {
              "options": [
                {
                  "product": {
                    "sku": "OPTION_SKU",
                    "custom_attributes": []
                  }
                }
              ]
            }
          ]
        }
      ]
    }
  }
}
``` 

### Additional information

If we add a specific attribute to the query that that attribute is returned in the custom_attributes result
```
Query a bundle product and select custom_attributes on its options
```
{
  products(filter: {sku: {eq: "XYZ"}}) {
    items {
      sku
      ... on BundleProduct {
        items {
          options {
            product {
              sku
              my_custom_attribute
              custom_attributes {
                selected_attribute_options {
                  attribute_option {
                    uid
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
``` 
``` 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-11-22 10:51
Hi @nmarquez2,

Thank you for reporting and collaboration.

Could you Please elaborate the steps to reproduce it will helps us to reproduce the issue.

As per the document https://developer.adobe.com/commerce/webapi/graphql/schema/products/queries/products/#filter-custom_attributesv2-of-a-product we have to use custom_attributesV2 in place custom_attributes.Kindly refer this document.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-12-11 05:10
Hi @nmarquez2,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-12-11 05:10 UTC
Labels: Issue: needs update, Reported on 2.4.6-p3
