### ISSUE TITLE
Warning: trim() expects parameter 1 to be string, array given | magento/module-catalog-search

### ISSUE THREAD

**Issue by Morgy93** [magento/magento2#33586] opened 2021-07-26 08:26 UTC
### Preconditions (*)

- Magento 2.4.2
- PHP 7.4

### Steps to reproduce (*)

Pass an array to any advanced search string input
For example: `/catalogsearch/advanced/result/?name[]=error`

### Expected result (*)

It should not throw an unhandled error.

### Actual result (*)

```
Warning: trim() expects parameter 1 to be string, array given in vendor/magento/module-catalog-search/Model/Advanced.php on line 201

Trace:
#1 trim() called at [vendor/magento/module-catalog-search/Model/Advanced.php:201]
#2 Magento\CatalogSearch\Model\Advanced->addFilters() called at [vendor/magento/module-catalog-search/Controller/Advanced/Result.php:62]
#3 Magento\CatalogSearch\Controller\Advanced\Result->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#4 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#5 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php:51]
#6 Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#7 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#8 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->___callPlugins() called at [generated/code/Magento/CatalogSearch/Controller/Advanced/Result/Interceptor.php:23]
#9 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#10 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#11 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#12 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#13 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->___callPlugins() called at [generated/code/Magento/CatalogSearch/Controller/Advanced/Result/Interceptor.php:32]
#14 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:186]
#15 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:118]
#16 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#17 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#18 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]
#19 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#20 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:75]
#21 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#22 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#23 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#24 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#25 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:263]
#26 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Morgy93** [comment] 2021-07-26 08:26
@magento give me 2.4-develop instance

**Comment by Morgy93** [comment] 2021-07-26 08:32
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
Steps to reproduce:
1. Go to `domain.tld/catalogsearch/advanced/result/?name[]=error` (e.g. https://9c1b89fe5de56e32154d4d69af8f12e0-2-4-develop.instances.magento-community.engineering/catalogsearch/advanced/result/?name[]=error)
2. See error
![image](https://user-images.githubusercontent.com/7961978/126958798-7637bee3-59c9-4cf9-989f-1b744f3d4ff3.png)

**Comment by Morgy93** [comment] 2021-07-26 08:59
The faulty code was introduced here: https://github.com/magento/magento2/commit/14b90ed9b715fd3264a62094c32fbb10e147309d

**Comment by WebHostingAce** [comment] 2021-07-31 04:38
Same Issue. Subscribe to the thread.

**Comment by engcom-Bravo** [comment] 2021-08-19 03:44
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
Steps to reproduce:
Step 1:  Go to {your_domain}/catalogsearch/advanced/result/?name[]=error 

Step 2: Below error is shown
<img width="1315" alt="catalogsearch" src="https://user-images.githubusercontent.com/51680745/130004135-cb701d19-8a4d-45c2-a84b-345c389d1369.png">

Magento exception log

main.CRITICAL: Warning: trim() expects parameter 1 to be string, array given in /Applications/MAMP/htdocs/magento2/app/code/Magento/CatalogSearch/Model/Advanced.php on line 201 {"report_id":"7795ed006397a2df48b21de48d13cabdc6575853bde5b3e221aca5d2dca0eebe","exception":"[object] (Exception(code: 0): Warning: trim() expects parameter 1 to be string, array given in /Applications/MAMP/htdocs/magento2/app/code/Magento/CatalogSearch/Model/Advanced.php on line 201 at /Applications/MAMP/htdocs/magento2/lib/internal/Magento/Framework/App/ErrorHandler.php:61)"} []

**Comment by engcom-Bravo** [comment] 2021-08-20 11:22
Closing this issue as it is duplicate issue [33589](https://github.com/magento/magento2/issues/33589)

**Comment by Morgy93** [comment] 2021-08-20 13:26
> Closing this issue as it is duplicate issue [33589](https://github.com/magento/magento2/issues/33589)

@engcom-Bravo How can this be a duplicate if the error message and the way to trigger the error is different?
It's literally in the issue title, just compare.

**Comment by Morgy93** [comment] 2021-09-23 07:25
@engcom-Bravo Any reaction?
Bots/Spammers/Hackers are still flooding our shops with this issue with latest Magento 2.4.3

![image](https://user-images.githubusercontent.com/7961978/134467898-940d3847-f11b-4a00-904d-bbceebedbd17.png)

**Comment by Morgy93** [comment] 2021-10-02 08:27
@magento give me 2.4-develop instance

**Comment by Morgy93** [comment] 2021-10-02 08:40
Still reproducible on latest 2.4-develop, but #33589 got closed as fixed.

So it CANNOT be a duplicate! Like @engcom-Bravo stated here https://github.com/magento/magento2/issues/33586#issuecomment-902624277
The code is unchanged, I checked. **Please reopen this issue!**

How is it possible to get a little reaction from someone from the Magento staff since 20 Aug?
Do I need to ping all of them? Cannot be the solution. Still I don't know another way. Please don't be mad.
@magento-engcom-team @engcom-Alfa @engcom-Bravo @engcom-Charlie @engcom-Dash @engcom-Delta @magento-team 

@ihor-sviziev I had positive experience with you in the past, maybe you can help 🙏

**Comment by ihor-sviziev** [comment] 2021-10-02 18:31
@Morgy93, can you reproduce on the test instance?

**Comment by Morgy93** [comment] 2021-10-04 07:23
@ihor-klymchuk Yes, that is right in the first sentence.
I used the Magento instance that I just ordered one comment before.

**Comment by ihor-sviziev** [comment] 2021-10-04 07:24
@engcom-Alfa, could you re-check if this issue is still reproducing?

**Comment by Morgy93** [comment] 2021-11-19 08:15
@engcom-Alfa Yes, please?

**Comment by engcom-November** [comment] 2021-12-24 10:26
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
![image](https://user-images.githubusercontent.com/60198231/147344800-602d6dc5-d814-455e-adfc-e119867ee047.png)

`
[2021-12-24T10:25:00.341233+00:00] main.CRITICAL: Exception: Warning: trim() expects parameter 1 to be string, array given in /var/www/html/mg24/magento2/app/code/Magento/CatalogSearch/Model/Advanced.php on line 201 in /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler()
#1 /var/www/html/mg24/magento2/app/code/Magento/CatalogSearch/Model/Advanced.php(201): trim()
#2 /var/www/html/mg24/magento2/app/code/Magento/CatalogSearch/Controller/Advanced/Result.php(62): Magento\CatalogSearch\Model\Advanced->addFilters()
#3 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\CatalogSearch\Controller\Advanced\Result->execute()
#4 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->___callParent()
#5 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->Magento\Framework\Interception\{closure}()
#6 /var/www/html/mg24/magento2/generated/code/Magento/CatalogSearch/Controller/Advanced/Result/Interceptor.php(23): Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->___callPlugins()
#7 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/Action/Action.php(111): Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->execute()
#8 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch()
#9 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->___callParent()
#10 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->Magento\Framework\Interception\{closure}()
#11 /var/www/html/mg24/magento2/generated/code/Magento/CatalogSearch/Controller/Advanced/Result/Interceptor.php(32): Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->___callPlugins()
#12 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/FrontController.php(245): Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->dispatch()
#13 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#14 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#15 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#16 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#17 /var/www/html/mg24/magento2/app/code/Magento/Store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#18 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#19 /var/www/html/mg24/magento2/app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php(75): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#20 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch()
#21 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#22 /var/www/html/mg24/magento2/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#23 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#24 /var/www/html/mg24/magento2/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#25 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#26 /var/www/html/mg24/magento2/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#27 {main} {"report_id":"18f7c98621fecd6688938121d11aef584bdd97cb949f7397060fa86af7523b6b"} []
`

**Comment by korovitskyi** [comment] 2022-01-19 14:56
@magento I am working on this

**Closed as completed** 2022-03-29 19:54 UTC
Labels: Issue: Confirmed, Component: Url, Reproduced on 2.4.x, Priority: P2, Severity: S3, Progress: done, Reported on 2.4.2, Area: Search
