### ISSUE TITLE
Admin Dashboard shows wrong period for yearly statistics

### ISSUE THREAD

**Issue by norgeindian** [magento/magento2#29734] opened 2020-08-25 08:46 UTC
### Preconditions (*)

1. Magento 2.4-develop, 2.3.5-p2

### Steps to reproduce (*)

1. Login to the admin dashboard
2. Change time period to yearly
3. Check graph

### Expected result (*)

1. I would expect the shown period to only include the last 12 months

### Actual result (*)
 
![image](https://user-images.githubusercontent.com/11156287/91152880-ce269b00-e6bf-11ea-9da0-fcce983a9d0a.png)
More than 12 months are shown. Everything until beginning of 2019 is shown instead of only the period between August 2019 and August 2020. 
![image](https://user-images.githubusercontent.com/51681379/91813789-e0628500-ec3b-11ea-85c2-36fa15f615c3.png)

Proposed [solution](https://github.com/magento/magento2/issues/29734#issuecomment-682029009)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by victortodoran** [comment] 2020-08-25 09:34
@magento give me 2.4 instance

**Comment by victortodoran** [comment] 2020-08-25 09:35
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-08-25 09:35
Hi @victortodoran. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-08-25 09:36
Hi @victortodoran, here is your [Magento instance](https://i-29734-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29734-2-4-develop.instances.magento-community.engineering/admin_39a7](https://i-29734-2-4-develop.instances.magento-community.engineering/admin_39a7)
Login: `caeaa300` Password: `8ef7cc6790dc`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2020-08-26 13:44
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37060` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Blatant** [comment] 2020-08-27 15:41
Just FYI, I beleive the issue is in the logic at lines 453 to 468 of the file `D:\wamp64\www\autoglym2.local\vendor\magento\module-reports\Model\ResourceModel\Order\Collection.php`

            case '2y':
                $startMonthDay = explode(
                    ',',
                    $this->_scopeConfig->getValue(
                        'reports/dashboard/ytd_start',
                        \Magento\Store\Model\ScopeInterface::SCOPE_STORE
                    )
                );
                $startMonth = isset($startMonthDay[0]) ? (int)$startMonthDay[0] : 1;
                $startDay = isset($startMonthDay[1]) ? (int)$startMonthDay[1] : 1;
                $dateStart->setDate($dateStart->format('Y'), $startMonth, $startDay);
                //$dateStart->modify('-1 year');
                if ($range == '2y') {
                    $dateStart->modify('-1 year');
                }
                break;

Here, I've commented out line 464 to fix it. 

The logic being the line 463 
`$dateStart->setDate($dateStart->format('Y'), $startMonth, $startDay);`
this sets the date to the current year (with start day configs, pretty meaningless), so for today thats "1-1-2020" assuming defaults

line 464 takes a year off, so thats "1-1-2019"
`$dateStart->modify('-1 year');`

then lines 465 to 467 are if its 2 years to date, take another year off, thats 1-1-2018. 
`if ($range == '2y') {  $dateStart->modify('-1 year');  }

So Year to Date YTD and 2 year to date 2YTD are both incorrectly offset by a year. YTD measn you need to start at the beginning of the current year as is calculated in the first statement.

Then a year is taken off, which is where the error is (note I commented it out in the snippet above) 

Then the extra year is correctly taken off for the "2y" case. 

Good news is, the containing function is public and on a concrete class so it should be easy to write an plugin around the function to correct.
Bad news is, this looks like a generic collection used for many reports, I'm not sure if this would impact anything in the actual reporting area of admin....

**Comment by kaivanshah02** [comment] 2020-10-31 11:13
@magento I'm working on it,

**Comment by kaivanshah02** [comment] 2020-10-31 11:54
@magento I'm working on it.

**Comment by kaivanshah02** [comment] 2020-10-31 13:13
@magento add to contributors team

**Comment by kaivanshah02** [comment] 2020-10-31 13:14
@magento I'm working on it.

**Comment by norgeindian** [comment] 2021-02-09 14:04
@kaivanshah02 , any news regarding this topic?

**Comment by eBusinessAtlantique** [comment] 2021-03-16 12:01
Same problem on 2.3.6-p1.
I am interested in a solution. Thanks.

**Comment by sprankhub** [comment] 2021-06-02 21:26
Still relevant AFAIK.

**Comment by norgeindian** [comment] 2021-06-07 06:12
Definitely, still no solution here as far as I see.

**Comment by ThomasT2020** [comment] 2021-09-04 18:27
I confirm this is still an issue in 2.3.7-p1

**Comment by norgeindian** [comment] 2021-11-08 10:50
Still an issue in 2.4.3-p1

**Comment by zigojacko** [comment] 2021-12-30 13:23
Is anyone actually bothering to acknowledge this bug and roll-out a fix?

It was reported over a year ago and is still a present issue in the latest stable release...

**Comment by norgeindian** [comment] 2022-04-20 08:09
Still not correct in Magento 2.4.3-p2

**Comment by norgeindian** [comment] 2022-08-08 05:58
Any updates regarding this issue?

**Comment by zigojacko** [comment] 2022-08-08 09:35
@norgeindian I think Adobe gave up caring about the countless bugs with Magento Open Source edition... 🤷‍♂️

**Comment by norgeindian** [comment] 2022-09-12 12:45
Still an issue in 2.4.3-p3

**Comment by zigojacko** [comment] 2022-09-12 13:51
@norgeindian we gave up waiting for Magento to fix this themselves and just wrote a module that fixes it as per what @Blatant advised earlier in this thread.

**Comment by eBusinessAtlantique** [comment] 2022-09-12 17:03
@Blatant did the right fix. Just needs to be included in M2 next release...

**Comment by nidhigupta13-ey** [comment] 2023-09-22 06:31
@magento I am working on this

**Comment by engcom-Delta** [comment] 2024-08-08 09:52
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment] 2024-08-08 11:08
Hi @norgeindian,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop and the issue is not reproducible. Kindly refer the screenshots.

**Steps to Reproduce**
1. Access Admin
2. Refresh order report
3. Navigate back to dashboard
4. Set sort to YTD , observe current year data is displaying in cart.
![image](https://github.com/user-attachments/assets/da931ed0-150a-46ce-a062-10f3bf6486d7)

5. Set sort to 2YTD , observe data is displaying as expected
![image](https://github.com/user-attachments/assets/df0fb4f3-e3a9-4cb7-9de7-5aed7f85b449)

Kindly recheck the issue on latest Magento 2.4-develop instance and Please let us know if you are still facing any issue.
Thanks.

**Closed as completed by engcom-Delta** 2024-08-08 11:08 UTC
Labels: Issue: Ready for Work, Component: Cms, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Reproduced on 2.4.x, Priority: P3, Severity: S3, Reproduced on 2.3.5p2, Progress: done, Reported on 2.3.5-p2

**Comment by norgeindian** [comment] 2024-08-21 06:14
@engcom-Delta , thanks for checking.
But as I wrote in the initial description of the issue, I would usually expect the last 12 resp. 24 months to be shown and not all data of the current resp. the current and the last year.
