### ISSUE TITLE
Magento 2.3.3 issue with login admin related offset 2 Encryptor

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#25025] opened 2019-10-13 10:37 UTC
### Preconditions (*)

1. Magento 2.3.3
2. PHP 7.1.24

### Steps to reproduce (*)

1.
2.

### Expected result (*)

Login admin without problem

### Actual result (*)

Got notice error show undefine offset 2 in file Magento\Framework\Encryption\Encryptor.php Line 590

**Comment by manishmittalm** [comment] 2019-10-13 11:12
Hello @magento 

Team please provide me magento 2.3.3

**Comment by manishmittalm** [comment] 2019-10-13 11:33
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-10-13 11:33
Hi @manishmittalm. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-10-13 11:33
Hi @manishmittalm, here is your [Magento instance](https://i-25025-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25025-2-3-develop.instances.magento-community.engineering/admin](https://i-25025-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by manishmittalm** [comment] 2019-10-13 11:37
Thanks @magento for sharing. Can you confirm PHP version for this shared instance.

**Comment by manishmittalm** [comment] 2019-10-13 11:38
@mrtuvn 
Magento 2.3.3 supports 
PHP ~7.1.3
~7.2.0
~7.3.0

Please check with these versions. It not support PHP 7.1.24

**Comment by mrtuvn** [comment] 2019-10-13 12:08
ok i fixed my problem. Change php to php7.2 and problem gone
Please close this one

**Comment by krishprakash** [comment] 2019-10-13 12:23
Not reproduced.
Closing this issue

**Closed as completed by krishprakash** 2019-10-13 12:23 UTC
Labels: Issue: Format is valid

**Comment by hostep** [comment] 2019-10-13 14:32
Just for completeness sake, this is a duplicate of https://github.com/magento/magento2/issues/23511

I tried explaining the case where this problem can happen in https://github.com/magento/magento2/issues/23511#issuecomment-520534869

If you are able to get the php sodium extension running with PHP 7.1, it might still work. But upgrading to 7.2 or even 7.3 is better since it is [supported for a longer period](https://www.php.net/supported-versions.php).

**Comment by SolsWebdesign** [comment] 2019-11-03 16:22
Clean install on Magento 2.3.3 on NginX (hypernode) with php 7.2.19 (to be precise v7.2.19-1).
Set in Developer mode, added Sample data using bin/magento sampledata:deploy and tried to login: 
1 exception(s):
Exception #0 (Exception): Notice: Undefined offset: 2 in ../vendor/magento/framework/Encryption/Encryptor.php on line 590

Tried to create another admin through CLI but same error.
That is weird... is it because of the sample data? 
Started a fresh 2.3.3  on NginX (hypernode) with php 7.2.19 and left the sample data. But did set it to developer mode. Same error :-(
What ever I try I get this. This should not happen on a clean install with PHP 7.2, right? Or am I missing something here?

[edit] okay, downgraded php from 7.2.19 to 7.1.27, cleared cache, run setup upgrade, etc... created new admin user and... am able to login. Tried with both sample data and without, no difference...

So clean install Magento 2.3.3 on NginX (hypernode) with php 7.2.19 is the problem. It works fine on PHP 7.1.27....

Got Magento 2.3.3 working on PHP 7.1.27 and I can actually login (very important) and now try to install the sample data using bin/magento sampledata:deploy and... 

Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - doctrine/lexer 1.1.0 requires php ^7.2 -> your PHP version (7.1.27) does not satisfy that requirement. (etc etc etc).

okay... got it working. Clean install Magento 2.3.3 on NginX (hypernode) with php 7.1.27 and login! Leave browser with logged in administrator open (very important) and change PHP through ssh to PHP 7.2.19. When done, update password in the still open browser for the logged in administrator!

Refresh cache. I can now logout and log back in and install sample data and continue my work. I still think this should not happen on a clean install.
