### ISSUE TITLE
When cache is enable can't getLastRealOrder()

### ISSUE THREAD

**Issue by esilvajr** [magento/magento2#6425] opened 2016-08-31 19:16 UTC
Well, i think the subject say farly about the error.

When access the $this->_checkoutSession->getLastRealOrder()->getId() object to get the last order id, return null if my cache was enable

```
var_dump($this->_checkoutSession->getLastRealOrder()->getId()); //returns null
```

If i disable the cache, works fine...

**Comment by veloraven** [comment] 2016-09-01 15:00
@esilvajr thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.

**Comment by voleye** [comment] 2016-09-22 09:35
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by voleye** 2016-09-22 09:35 UTC
Labels: Progress: needs update

**Comment by Dhimant** [comment] 2021-07-22 01:26
I am facing the same issue with magento 2.4.2 E.E any solution for this ?

**Comment by sanjay-codez** [comment] 2022-06-08 11:23
Issue is still there magento - 2.4.3-p2
