### ISSUE TITLE
Product URL keys wrong in Products API 

### ISSUE THREAD

**Issue by scottcwilson** [magento/magento2#10276] opened 2017-07-18 11:58 UTC
With Magento 2.1.7 and the test dataset, I use the API 

http://localhost:8888/mage_217/rest/V1/products/MS06-L-Blue

(This is for product 541, named "Zoltan Gym Tee-L-Blue".  The SKU is "MS06-L-Blue" as shown in the API call.) 

I get back 

...
            [10] => stdClass Object
                (
                    [attribute_code] => url_key
                    [value] => zoltan-gym-tee-l-blue
                )
...

I can't build a URL from this - the API key *should* be zoltan-gym-tee.  In other words,

http://localhost:8888/mage_217/index.php/zoltan-gym-tee.html  DOES work 

http://localhost:8888/mage_217/index.php/zoltan-gym-tee-l-blue.html DOES NOT work

### Preconditions

1. Magento 2.1.7
2. PHP 5.6.30
3. MySQL 5.6.35
4. MAMP

### Steps to reproduce

1. Use products API as shown above  http://localhost:8888/mage_217/rest/V1/products/MS06-L-Blue

2. Attempt to create a URL to this product using returned url_key value

### Expected result

1. Actual product page is shown 

### Actual result

1. 404 page is shown.

**Comment by orlangur** [comment] 2017-07-18 14:31
This has nothing to do with API or URL keys. You won't find "Zoltan Gym Tee-L-Blue" in catalog on storefront as well.

If you check it's `visibility` attribute you'll notice it is "Not Visible Individually". This means only configurable product http://localhost:8888/mage_217/index.php/zoltan-gym-tee.html  is intended to be visible on storefront and not any of its child products.

**Comment by scottcwilson** [comment] 2017-07-18 14:45
But I don't get 'zoltan-gym-tee' anywhere in the response to the product API request.  How can I build a URL to the product with the data I have (SKU, ID, url_key for child product) from an API client?

**Comment by korostii** [comment] 2017-07-18 14:51
That sounds as a technical question, please use the community forums for those (Magento, Inc.'s official policy is that GitHub is used for bug tracking purposes only). 
Here's one question there which is particularly similar to yours: https://community.magento.com/t5/Just-Ask-Alan/Using-REST-api-get-parent-configurable-item-of-a-child/td-p/36571

**Comment by orlangur** [comment] 2017-07-18 14:54
For the "Zoltan Gym Tee-L-Blue" product you cannot build an URL as there is no separate page for this product at all (no matter, using API or not).

Building URL like http://localhost:8888/mage_217/index.php/zoltan-gym-tee.html from API response is not a reliable way. The only proper approach for now is using `\Magento\Catalog\Model\Product\Url::getUrl` I believe.

According to https://magento.stackexchange.com/a/98771 it seems like you cannot do it using API only.

**Comment by scottcwilson** [comment] 2017-07-18 15:03
@orlangur Doesn't that mean that the url_key returned by the API should really be "zoltan-gym-tee"?  What's the point of returning a url_key that doesn't work?  To me, this seems like a bug.

**Comment by orlangur** [comment] 2017-07-18 15:11
`url_key` is just a product attribute. If you change visibility of "Zoltan Gym Tee-L-Blue" product to "Catalog & Search", the http://localhost:8888/mage_217/index.php/zoltan-gym-tee-l-blue.html URL will start to work.

> url_key returned by the API should really be "zoltan-gym-tee"? 

No, it is an `url_key` of http://localhost:8888/mage_217/rest/V1/products/MS06 product which is a parent of http://localhost:8888/mage_217/rest/V1/products/MS06-L-Blue.

**Comment by scottcwilson** [comment] 2017-07-18 15:26
OK, let me take a different approach.

Doesn't it seem like a bug that you can't deduce the product's URL from the response to the product API?  Doesn't this seem like a huge oversight?  Whether you do it by SKU, id or whatever, I just want something that works.

**Comment by orlangur** [comment] 2017-07-18 15:40
Again: for http://localhost:8888/mage_217/rest/V1/products/MS06-L-Blue product no such URL as you want exists at all.

Regarding product URL absence in response: obviously, it does not seem to be a bug but rather a feature request. Some use cases were provided in StackOverflow question I posted but generally it does not seem to be a highly requested feature.

What is your use case, by the way?

**Comment by scottcwilson** [comment] 2017-07-18 15:46
I'm writing a little client to display information (name, description,
price) on a product, and want to link back to the store.

**Comment by orlangur** [comment] 2017-07-18 15:56
Technically you can use URLs in form `/catalog/product/view/id/547`. But if you need SEO-friendly URLs you'll need to extend API so that it involves `\Magento\Catalog\Model\Product\Url::getUrl`.

**Comment by scottcwilson** [comment] 2017-07-18 16:08
The trouble is, I can't get "547" from the products API.  I get the API of the child product, which is 541.  And `/catalog/product/view/id/541` doesn't work.

**Comment by orlangur** [comment] 2017-07-18 16:30
There is no page for product with ID 541 in your instance :) Until you change `Visibility` to something different from "Not Visible Individually".

**Comment by misha-kotov** [comment] 2017-07-18 16:42
I can confirm we do have this feature in our backlog but it has (obviously) not been implemented yet. I will be closing this issue since it's not a bug, but feel free to continue discussion.

**Closed as completed by misha-kotov** 2017-07-18 16:42 UTC
Labels: Component: Framework/Webapi, Component: Catalog

**Comment by scottcwilson** [comment] 2017-07-18 16:47
Thanks @misha-kotov.  Thanks for your insights, @orlangur - I see your point, but the trouble is, this is a SKU based API, so if I query the parent product (547), the price is 0.  So I guess I have to code this myself.
