### ISSUE TITLE
Cannot Upload SVG Logo

### ISSUE THREAD

**Issue by Stoyvo** [magento/magento2#35125] opened 2022-02-20 13:01 UTC
### Preconditions (*)

1. Read official Magento Documentation (https://docs.magento.com/user-guide/design/logo-upload.html)
2. Have SVG image 

### Steps to reproduce (*)

1. In Admin, Navigate to Content -> Theme Configuration -> Select Theme
2. Open Header section
3. Select .svg image for Logo

### Expected result (*)

1. Upload image as SVG

### Actual result (*)

Error: "We don't recognize or support this file extension type."

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [*] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Stoyvo** [comment] 2022-02-20 13:02
Upon research, I have identified that Magento removed SVG support in 2017?
https://github.com/magento/magento2/issues/12451

I find this hard to believe, otherwise official documentation would have been updated right? Official documentation specifically instructs user to select SVG file.

**Comment by engcom-Delta** [comment] 2022-02-21 09:34
Hi @Stoyvo ,
Thank you for reporting the issue. We have verified the issue on Magento 2.4-develop branch and the issue is reproducible.
Based on the above observation, confirming the issue.

**Steps Performed:**

1.Install a clean version of Magento version 2.4-develop
2.Go to – Content>Configuration>Edit(Any configuration)>Header>Upload>Select .svg file
Actual result :
"We don't recognise or support this file extension type."

![image](https://user-images.githubusercontent.com/51681379/154927513-c269f89b-04e8-44f1-b08d-985591c47fa2.png)

Expected result :
 Upload image as SVG successfully .

**Comment by pranav7870** [comment] 2022-03-14 17:31
@magento I am working on this

**Comment by seak6adtn59v** [comment] 2023-08-03 09:55
Any progress on this further?

**Comment by MagestyApps** [comment] 2024-03-20 09:04
As you can see in the official docs, in default Magento you can upload only PNG, GIF or JPG images for logo. In order to upload an SVG you have to either add a customisation or use a 3rd part solution like this one: https://github.com/MagestyApps/module-web-images

**Comment by engcom-Bravo** [comment] 2024-10-07 05:56
@MagestyApps Thanks for your contribution!!.

As per the Magento documentation it supports only PNG, GIF or JPG images for logo and it is an expected behaviour.Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-10-07 05:56 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Progress: done, Area: Admin UI

**Comment by sprankhub** [comment] 2024-10-07 06:34
@engcom-Bravo, it is 2024. SVGs should absolutely be supported by now, no matter what the documentation says. I am happy to create a PR for the docs as soon as SVGs are supported ;)
