### ISSUE TITLE
I can't login like customer/admin with using Memcached

### ISSUE THREAD

**Issue by springimport** [magento/magento2#6021] opened 2016-08-05 15:50 UTC
### Preconditions
1. PHP Configuration:

```
[Session]
;session.save_handler = files
;session.save_path = "%sprogdir%/userdata/temp/"

session.save_handler = memcached
session.save_path = "127.0.0.1:11211"
```
1. Magento CE 2.1.0 with sample data is installed.
2. Updated env.php:

``` php
'session' =>
array(
    'save' => 'memcached',
    'save_path' => '127.0.0.1:11211'
),
```
### Steps to reproduce
1. Go to http://example.com/customer/account/login/
2. Go to http://example.com/admin_xxxxxx/
### Expected result

Login.
### Actual result

| PHP | Result |
| --- | --- |
| 7 x64 | [An unspecified error occurred. Please contact us for assistance](https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Controller/Account/LoginPost.php#L190). |
| 5.6 | Refreshing page without actions. |

P.S. I think that the problem may be in [regenerateId()](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Session/SessionManager.php#L467).

**Comment by AVoskoboinikov** [comment] 2016-08-22 11:45
Hello

Thank you for your request, but unfortunately I can't reproduce your issue on my build. I am using CE 2.1.0 with php v 7.0.9 and memcached version 1.4.30 - all sessions works fine for me. 

Could you please check your memcached installation/configuration with this guide http://devdocs.magento.com/guides/v2.0/config-guide/memcache/memcache.html and reinstall/reconfigure it if there are some differences? 

After that try to to reproduce your issue and provide detailed steps, so we could reproduce it too. 

Thanks for help, and I am looking forward to getting response from you.

**Comment by springimport** [comment] 2016-08-22 17:13
I don't know how check memcached on windows system. I use [OpenServer](http://open-server.ru/) ([download](http://open-server.ru/download/)) with memcached (1.2 or 1.4).

**Comment by AVoskoboinikov** [comment] 2016-08-23 07:21
You can try check your memcached installation via phpinfo() or separate php code that uses Memcached class directly. If that code will work then refer to magento documentation about configuring memcached and magento.

If you will still be able to reproduce issue - provide us detailed steps to reproduce it on our side. 

Thank you.

**Comment by springimport** [comment] 2016-08-23 13:10
I understood my mistake.

``` php
if (class_exists('Memcache')) {
    echo "Memcache is enabled<br/>";
} else {
    echo "Memcache is <b>NOT</b> enabled<br/>";
}

if (class_exists('Memcached')) {
    echo "Memcached is enabled<br/>";
} else {
    echo "Memcached is <b>NOT</b> enabled<br/>";
}
```

```
Memcache is NOT enabled
Memcached is NOT enabled
```

**Comment by AVoskoboinikov** [comment] 2016-08-25 14:32
Cool, we will close this issue then. Feel free to ask if you will have any new questions.

**Closed as completed** 2016-08-25 14:35 UTC
Labels: bug report
