### ISSUE TITLE
Identify 

### ISSUE THREAD

**Issue by linkdandyparanormal** [magento/magento2#36260] opened 2022-10-10 01:52 UTC
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

Do Everything to Sign in new account. After pushing enter it is suppose to send your email a confirmation for identity. Using iPhone 11.

### Expected result

I have waited a day for confirmation email, nothing came to junk or inbox 

### Actual result

Cannot create an account as a result 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-10-10 10:31
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-10-11 13:38
Hi @linkdandyparanormal,


Thanks for Reporting and collaboration.

Verified the issue on Magento 2.4-develop instance but could not reproduce the issue.we are getting confirmation mails from a Magento store.Kindly refer screenshots.


<img width="1080" alt="Screenshot 2022-10-11 at 6 44 27 PM" src="https://user-images.githubusercontent.com/51680745/195106022-e66767cd-1ce1-410e-8045-df25a9ff8b42.png">



Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.


   
Thanks.

**Comment by engcom-Bravo** [comment] 2022-10-25 06:21
Hi @linkdandyparanormal,


We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-10-25 06:21 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
