### ISSUE TITLE
Magento 2 Update from 2.1.9 to 2.2.0

### ISSUE THREAD

**Issue by MoschenBayern** [magento/magento2#11400] opened 2017-10-12 13:45 UTC
### Preconditions

1. 
2. 

### Steps to reproduce

1. Web Setup Wizard
2. System Upgrade
3. Check readiness

### Expected result

1. all Points should be green

### Actual result

1. We found conflicting component dependencies. Hide detail

Command "update" failed: Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for magento/product-community-edition 2.2.0 -> satisfiable by magento/product-community-edition[2.2.0].
- amzn/amazon-pay-and-login-with-amazon-core-module 1.1.4 requires magento/framework ^100.1.0 -> satisfiable by magento/framework[100.1.0-rc1, 100.1.0-rc2, 100.1.0-rc3, 100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6, 100.1.7, 100.1.8, 100.2.0-rc20, 100.1.9].
- Can only install one of: magento/framework[101.0.0, 100.1.0-rc1].
- Can only install one of: magento/framework[101.0.0, 100.1.0-rc2].
- Can only install one of: magento/framework[101.0.0, 100.1.0-rc3].
- Can only install one of: magento/framework[101.0.0, 100.1.0].
- Can only install one of: magento/framework[101.0.0, 100.1.1].
- Can only install one of: magento/framework[101.0.0, 100.1.2].
- Can only install one of: magento/framework[101.0.0, 100.1.3].
- Can only install one of: magento/framework[101.0.0, 100.1.4].
- Can only install one of: magento/framework[101.0.0, 100.1.5].
- Can only install one of: magento/framework[101.0.0, 100.1.6].
- Can only install one of: magento/framework[101.0.0, 100.1.7].
- Can only install one of: magento/framework[101.0.0, 100.1.8].
- Can only install one of: magento/framework[101.0.0, 100.2.0-rc20].
- Can only install one of: magento/framework[101.0.0, 100.1.9].
- magento/product-community-edition 2.2.0 requires magento/framework 101.0.0 -> satisfiable by magento/framework[101.0.0].
- Installation request for amzn/amazon-pay-and-login-with-amazon-core-module 1.1.4 -> satisfiable by amzn/amazon-pay-and-login-with-amazon-core-module[1.1.4].

Can anyone help me pls. All other Updates from 2.1.7 to 2.1.8 or from 2.1.8 to 2.1.9 went without any problems

**Comment by ricoliv** [comment] 2017-10-16 07:09
I have exactly the same problem. 
I had a fully running Magento 2.1.9 version with amazon 1.4.

From there, I installed PHP soap like this:
sudo apt-get install php7.0-soap

Then I tried to upgrade Magento from 2.1.9 to 2.2.0  and got following error message during readines check:

Problem 1
- Installation request for magento/product-community-edition 2.2.0 -> satisfiable by magento/product-community-edition[2.2.0].
- amzn/amazon-pay-and-login-with-amazon-core-module 1.1.4 requires magento/framework ^100.1.0 -> satisfiable by magento/framework[100.1.0-rc1, 100.1.0-rc2, 100.1.0-rc3, 100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6, 100.1.7, 100.1.8, 100.2.0-rc20, 100.1.9].
- Can only install one of: magento/framework[101.0.0, 100.1.0-rc1].
- Can only install one of: magento/framework[101.0.0, 100.1.0-rc2].
- Can only install one of: magento/framework[101.0.0, 100.1.0-rc3].
- Can only install one of: magento/framework[101.0.0, 100.1.0].
- Can only install one of: magento/framework[101.0.0, 100.1.1].
- Can only install one of: magento/framework[101.0.0, 100.1.2].
- Can only install one of: magento/framework[101.0.0, 100.1.3].
- Can only install one of: magento/framework[101.0.0, 100.1.4].
- Can only install one of: magento/framework[101.0.0, 100.1.5].
- Can only install one of: magento/framework[101.0.0, 100.1.6].
- Can only install one of: magento/framework[101.0.0, 100.1.7].
- Can only install one of: magento/framework[101.0.0, 100.1.8].
- Can only install one of: magento/framework[101.0.0, 100.2.0-rc20].
- Can only install one of: magento/framework[101.0.0, 100.1.9].
- magento/product-community-edition 2.2.0 requires magento/framework 101.0.0 -> satisfiable by magento/framework[101.0.0].
- Installation request for amzn/amazon-pay-and-login-with-amazon-core-module 1.1.4 -> satisfiable by amzn/amazon-pay-and-login-with-amazon-core-module[1.1.4].

**Comment by hostep** [comment] 2017-10-16 07:43
Guys, just read the error message, the `amzn/amazon-pay-and-login-with-amazon-core-module` library version 1.1.4 isn't compatible yet with Magento 2.2's dependencies.
Please see if you can update that amazon library to a newer version, or file an issue in their repository to make it compatible with Magento 2.2.

This has nothing to do with Magento itself, so feel free to close this issue. Thanks! :)

**Comment by ricoliv** [comment] 2017-10-16 07:50
ok, I updated amazon to latest version 1.1.5 (without upgrade to Magento 2.2) - Success.

When trying to upgrade to magento 2.2. now, I get a slightly different error.
Does this mean amazon pay is not ready for magento 2.2.0?


Check Component Dependency

We found conflicting component dependencies. Hide detail

Command "update" failed: Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for magento/product-community-edition 2.2.0 -> satisfiable by magento/product-community-edition[2.2.0].
- amzn/amazon-pay-and-login-with-amazon-core-module 1.1.5 requires magento/framework ^100.1.0 -> satisfiable by magento/framework[100.1.0-rc1, 100.1.0-rc2, 100.1.0-rc3, 100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6, 100.1.7, 100.1.8, 100.2.0-rc20, 100.1.9].
- Can only install one of: magento/framework[101.0.0, 100.1.0-rc1].
- Can only install one of: magento/framework[101.0.0, 100.1.0-rc2].
- Can only install one of: magento/framework[101.0.0, 100.1.0-rc3].
- Can only install one of: magento/framework[101.0.0, 100.1.0].
- Can only install one of: magento/framework[101.0.0, 100.1.1].
- Can only install one of: magento/framework[101.0.0, 100.1.2].
- Can only install one of: magento/framework[101.0.0, 100.1.3].
- Can only install one of: magento/framework[101.0.0, 100.1.4].
- Can only install one of: magento/framework[101.0.0, 100.1.5].
- Can only install one of: magento/framework[101.0.0, 100.1.6].
- Can only install one of: magento/framework[101.0.0, 100.1.7].
- Can only install one of: magento/framework[101.0.0, 100.1.8].
- Can only install one of: magento/framework[101.0.0, 100.2.0-rc20].
- Can only install one of: magento/framework[101.0.0, 100.1.9].
- magento/product-community-edition 2.2.0 requires magento/framework 101.0.0 -> satisfiable by magento/framework[101.0.0].
- Installation request for amzn/amazon-pay-and-login-with-amazon-core-module 1.1.5 -> satisfiable by amzn/amazon-pay-and-login-with-amazon-core-module[1.1.5].

For additional assistance, see component dependency help .

**Comment by hostep** [comment] 2017-10-16 09:05
@ricoliv:
> Does this mean amazon pay is not ready for magento 2.2.0?

It looks like it, but please contact them yourself, this has nothing to do with Magento 2 itself :)

**Comment by magento-engcom-team** [comment] 2017-10-23 12:30
@MoschenBayern, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-23 12:30 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid
