### ISSUE TITLE
Magento 2 custom options created but not shown

### ISSUE THREAD

**Issue by Naberdz** [magento/magento2#25041] opened 2019-10-14 11:17 UTC
### Preconditions (*)

1. Magento 2.3.2
2. php 7.2

### Steps to reproduce (*)

1. Make code to create product with custom options
2. Execute code here is part of my code :
```

/* @var \Magento\Catalog\Api\Data\ProductInterfaceFactory $productFactory */        
$product = $this->_productFactory->create();

//assign product attributes SKU, price etc..
$product->setSku('test-sku');

/* @var \Magento\Catalog\Api\ProductRepositoryInterface $productRepository */
$product = $this->_productRepository->save($product);


$this->_customOptions = [
    [
        'sort_order' => 1,
        'title' => __('Title'),
        'type' => 'drop_down',
        'is_require' => 1,
        'values' => [
            [
                'title' => 'Select',
                'price' => '0',
                'price_type' => 'fixed',
                'sort_order' => '0',
                'is_delete' => '0',
            ]
        ]
    ],
    [
        'sort_order' => 2,
        'title' => __('Title 2'),
        'type' => 'drop_down',
        'is_require' => 1,
        'values' => [
            [
                'title' => 'Select',
                'price' => '0',
                'price_type' => 'fixed',
                'sort_order' => '0',
                'is_delete' => '0',
            ]
        ]
    ],
    [
        'sort_order' => 3,
        'title' => __('Title 3'),
        'type' => 'drop_down',
        'is_require' => 1,
        'values' => [
            [
                'title' => 'Select',
                'price' => '0',
                'price_type' => 'fixed',
                'sort_order' => '0',
                'is_delete' => '0',
            ]
        ]
    ]
];


foreach ($this->_customOptions as $arrayOption) {
    /*
     *  seem to be bug if we use \Magento\Catalog\Model\Product\Option in constructor 
     *  and use something like this: 
     *      $this->_option
     *      ->setProductId($product->getId())
     *      ->setStoreId($product->getStoreId())
     *      ->addData($arrayOption);
     *  it will create options multiple times, it append previous values to $option 
     *  so in our example it will have Title, Title +Title 2, Title + Title 2 + Title 3 = so in total we will have 6 custom options created.
     *  probably need to null it before that.
     */
    
    /* @var \Magento\Framework\ObjectManagerInterface $objectManager */
    $option = $this->_objectManager->create('\Magento\Catalog\Model\Product\Option')
        ->setProductId($product->getId())
        ->setStoreId($product->getStoreId())
        ->addData($arrayOption);
    $option->save();
    $product->addOption($option);
}
```

### Expected result (*)

1. Custom options should be created and visible in frontend
2.

### Actual result (*)

1. Custom options are visible only in backend.
<img width="1585" alt="Schermafbeelding 2019-10-14 om 12 56 55" src="https://user-images.githubusercontent.com/37579149/66746465-2e369900-ee82-11e9-94d5-3011b48a23ac.png">
<img width="559" alt="Schermafbeelding 2019-10-14 om 12 57 53" src="https://user-images.githubusercontent.com/37579149/66746503-47d7e080-ee82-11e9-8583-fc6b9c0976d3.png">

2. Open product and click save - options are visible in frontend. Unfortunately such solution is not possible for us since we have to create/ import over 10K products
<img width="596" alt="Schermafbeelding 2019-10-14 om 12 58 47" src="https://user-images.githubusercontent.com/37579149/66746560-6ccc5380-ee82-11e9-8d2b-fcd27dd668f7.png">

**Comment by engcom-Charlie** [comment] 2019-10-16 13:26
Hello @Naberdz 
I can't reproduce this issue on Magento 2.3-develop & 2.3.3 
I used this code:
![image](https://user-images.githubusercontent.com/51680850/66923342-43055f00-f031-11e9-808b-121816ad69e0.png)
![image](https://user-images.githubusercontent.com/51680850/66923361-4c8ec700-f031-11e9-87bc-f1b794f9898f.png)

**Result:**
Custom options are created and visible in frontend
![image](https://user-images.githubusercontent.com/51680850/66923511-9bd4f780-f031-11e9-8013-62b58ed81926.png)

So i have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-10-16 13:26 UTC
Labels: Issue: Format is valid, Triage: Dev.Experience
