### ISSUE TITLE
product alerts not working on 2.4.4 CE

### ISSUE THREAD

**Issue by DiegoItaly** [magento/magento2#35997] opened 2022-08-22 15:42 UTC
### Preconditions and environment

- magento 2.4.4 CE
- php 8.1

### Steps to reproduce

1. install a magento 2.4.4 ce
2. enable the product price alert
3. set the product alert scheduler start time to a time (for instance 17:00:00)
4. log in with a customer 
5. subscribe for a product price change
6. change manually the price of the product to a lower price
7. wait until the time of the step 3

### Expected result

the customer should receive an alert email with the price change

### Actual result

the customer does not receive any email.
More over, in the product page, where all the alerts are wrote,
the alert set in the example results in not sent (send count =0)

### Additional information

Current workaround: downgrade the product alert extension to the one of magento 2.4.3.

It's really wired, it looks like that in magento 2.4.4 the product alerts email are sent to a queue,
and then a customer should consume the queue.
But none of this seem to happen.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by DiegoItaly** [comment] 2022-08-22 15:43
@magento give me 2.4-develop instance

**Comment by DiegoItaly** [comment] 2022-08-22 16:04
I set an alert in the instance for 13:00:00 (it will be in 2-3 hours I think according to the instance timezone).
It looks like that the instance does not send emails (I did not receive the welcome email when I created a test customer).
Anyway, we might see the problem just by going in the product set for the alert in the backend,
and see the alert count.

It it will be 1 (now it is 0), at leas the trigger worked.
the product that I used for test is 24-MB01

I will wait a couple of house and see.

**Comment by DiegoItaly** [comment] 2022-08-23 05:49
give me 2.4-develop instance

**Comment by DiegoItaly** [comment] 2022-08-23 05:50
@magento give me 2.4-develop instance

**Comment by DiegoItaly** [comment] 2022-08-23 06:21
The instance of yesterday is not available anymore,
but I checked yesterday, a couple of hours later, if the alert count increased on the product,
and it didn't.
I also did not received any notification email.

So I'm pretty confident that it does not work.

**Comment by engcom-Dash** [comment] 2022-08-23 09:32
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-08-23 13:02
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-08-23 13:31
Hi @DiegoItaly ,

We are trying to reproduce the issue in 2.4 -develop branch....We are not able to reproduce the issue...

Here i attached the screenshots for your reference:
![Screenshot from 2022-08-23 18-45-10](https://user-images.githubusercontent.com/60198592/186170458-eae09e4a-fe81-4e58-b386-99ebb8fb1c4a.png)
![Screenshot from 2022-08-23 18-43-07](https://user-images.githubusercontent.com/60198592/186170476-f7fadae2-b772-44b2-91fd-377361c4f60b.png)

Steps we Follwed:

1.install a magento instance
2.enable the product price alert
3.set the product alert scheduler start time to a time (for instance 19:00:00)
4.log in with a customer
5.subscribe for a product price change
6.change manually the price of the product to a lower price

We didn't receive any mail....Regarding product price drops...

let us know if we are missing anything....

Thanks

**Comment by DiegoItaly** [comment] 2022-08-23 16:55
Hello, first thank you very much for testing my issue.

As I understood, if you don't receive any email, it means that it actually is not working.
I mean, in your example, at 19.00.00, a cron job should send an email with the price drop.

In the magento documentation:

https://experienceleague.adobe.com/docs/commerce-admin/inventory/configuration/product-alerts/alert-setup.html

There is wrote:

_To determine the time of day product alerts are sent, set Start Time to the hour, minute, and second._

I explain myself better, if I: 
1.install a magento instance
2.enable the product price alert
3.set the product alert scheduler start time to a time (for instance 19:00:00)
4.log in with a customer
5.subscribe for a product price change
6.change manually the price of the product to a lower price
7. wait until 19:00:00
8. then you should receive (at 19:00:00) an email at the customer email telling that the product has a price drop.

But, if you don't receive any email, it means that it is not working since you should receive an email.

However, it seem that the test instance don't actually send any email (maybe they are blocked for security reasons),
so you can check if the alert actually triggered by going to the product which you set up the alert,
go to the alert section and see if it triggered.

**Comment by engcom-Dash** [comment] 2022-08-24 09:59
@magento give me 2.4-develop instance

**Comment by DiegoItaly** [comment] 2022-09-03 18:32
hello, do you have any news about the bug?

Thank you

**Comment by engcom-Dash** [comment] 2022-09-05 08:42
Hi @DiegoItaly ,

We didn't receive any mails regarding product price drop....We checked both 2.4.4 instance as well as 2.4-develop instance.

Thanks!!!

**Comment by engcom-Dash** [comment] 2022-09-13 09:19
Hi @DiegoItaly ,

We have to check issue with cloud Environment with Live Search...We are Working will update you ASAP.

Let us know if We Missing anything!!!

Thanks!!!

**Comment by DiegoItaly** [comment] 2022-09-13 11:56
thank you

**Comment by engcom-Dash** [comment] 2022-09-14 06:33
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-09-14 07:35
Hi @DiegoItaly ,

This Issue is Duplicate [https://github.com/magento/magento2/issues/35602](https://github.com/magento/magento2/issues/35602)

Here i provide the Jira Link your Reference:
Jira Link: https://jira.corp.magento.com/browse/AC-5969

Thanks!!!

**Comment by DiegoItaly** [comment] 2022-09-15 09:08
thank you very much!

**Comment by engcom-Dash** [comment] 2022-09-19 10:14
Hi @DiegoItaly ,

Thanks For your contribution...We are Closing the issue.

Thanks!!!

**Closed as completed by engcom-Dash** 2022-09-19 10:14 UTC
Labels: duplicate, Issue: ready for confirmation
