### ISSUE TITLE
Comments are doubling in Admin Panel Order review page if place order using "Login as Customer" functionality

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2#29228] opened 2020-07-21 18:05 UTC
When an admin user places an order on behalf of a customer using Login as Customer, we make a comment on the order that is visible in the storefront and the admin panel. The storefront should show a generic name (Store Administrator) and the admin should show the full admin user name.

However, in the admin panel now I see two messages. Only the “admin full name” message should appear.

<img width="445" alt="comments" src="https://user-images.githubusercontent.com/3409584/88089576-dab05480-cb51-11ea-94de-1b9d4e3a716d.png">

### Preconditions
- Login as Customer functionality is enabled
- There is test registered Customer and product

### Steps to reproduce
1. Go to Admin Panel
2. Open customer grid page 
3. Open Customer Edit Page and click  "Login as Customer" button
4. Place an order with test simple product

### Expected Result
- on Storefront in My Account->Order Details, should be only one comment "Order Placed by Store Administrator"
- in Admin Panel, Order review page should be only one comment "Order placed by {John Doe}" using Login as Customer

### Actual Result
- in Admin we have two messages as on screen

**Comment by konarshankar07** [comment] 2020-08-08 04:54
@magento I'm working on this

**Comment by konarshankar07** [comment] 2020-08-08 05:23
Hello @sdzhepa ....
I have investigated this issue and order comment are flagged to visible on storefront and not on admin so do we need to show only order comment which is not visible on storefront in admin order comment history?
Correct me if I'm wrong
Thanks

**Comment by engcom-November** [comment] 2021-06-11 11:46
@sdzhepa Verified the issue on Latest Magento version 2.4.2 and the issue is reproducible.
Steps to reproduce:
1. Login to Magento Admin - Enable Login an Customer feature (Stores - Settings - Configuration - Customers - Login as Customer)
2. Navigate to Customers - All Customers - Edit customer - Login as Customer 
3. Add a product to cart and purchase the product
4. Front End - My Account - My Orders - View Order
**No issue:** "Order Placed by Store Administrator" message is displayed once
5. Go to Magento Admin - Customers - All Customers - Edit same customer  - Orders - view the order
**Issue:** In Magento Admin Order review page - 2 comment messages are getting displayed
![image](https://user-images.githubusercontent.com/60198231/121681604-a8487680-cad8-11eb-86a1-ddb94e59d834.png)


Frontend - No issue:
![image](https://user-images.githubusercontent.com/60198231/121681634-b0a0b180-cad8-11eb-841e-c1850458662d.png)

**Comment by magento-engcom-team** [comment] 2021-06-11 11:47
@engcom-November Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-06-11 11:48
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by SilinMykola** [comment] 2021-06-18 13:44
@magento I'm working on this

**Comment by ihor-sviziev** [comment] 2021-09-24 08:48
Hi @sdzhepa @SilinMykola,
As discussed in Slack - We think fixing this issue for one extension might add potentially more significant problems for other extensions (because it will hide some order history) is the wrong way, so I'm closing this issue and related PR.

**Closed as completed by ihor-sviziev** 2021-09-24 08:48 UTC
Labels: bug report, Issue: Confirmed, Priority: P3, Project: Login as Customer, Progress: done, Reproduced on 2.4.2

**Comment by Den4ik** [comment] 2021-09-24 10:00
@ihor-sviziev Did you discuss it with @sdzhepa? I believe that it could be fixed without breaks on custom extensions

**Comment by ihor-sviziev** [comment] 2021-09-24 12:27
@Den4ik sure!
