### ISSUE TITLE
 "Discount" string is not translating on cart on theme locale file

### ISSUE THREAD

**Issue by deepeshjain2011** [magento/magento2#35237] opened 2022-03-28 06:59 UTC
### Preconditions (*)

1. Magento 2.4.3-p1

### Steps to reproduce (*)

1. Create one 'Cart Price Rules' for discount.
2. In theme Magento Blank create specific language file (like for Danish (da_DK.csv), for Swedish (Sweden) (sv_SE.csv) etc) and add translation for string "Discount (%1)".
![laudrup dk_25_03_2022_(4)](https://user-images.githubusercontent.com/84851863/160330374-08172465-7d05-4ec9-8b63-ffac88deb818.png)
**_screenshot - 1_**
3. Run cli command for Setup Upgrade, Clean Cache.
4. Add product in to cart and go to cart page and check the discount applied according to created 'Cart Price Rules'.
5. Refresh the cart page, first time its load the "Big Brand Discount" but within second its again updated to "Discount".

### Description (*)

I found this translation issue while translate string "Discount (%1)" when purchase product with 'Cart Price Rules'.
The translation of string should be work according to theme locale. As per screenshot - 1 we have added translation "Big Brand Discount (%1)" of string "Discount (%1)". But the translation of string "Discount (%1)" is not working at cart page.
For detailed information, refer Actual result section.

### Expected result (*)

1. The string "Discount (%1)" of cart page should be translate according to specific theme language file.
![laudrup dk_25_03_2022_(3)](https://user-images.githubusercontent.com/84851863/160330354-e64afc27-74cb-4e25-983b-1c050dee5778.png)
**_screenshot - 2_**

### Actual result (*)

1. The string "Discount (%1)" does not translated according to specific theme language file at cart page.
![laudrup dk_25_03_2022_(5)](https://user-images.githubusercontent.com/84851863/160330443-b38e62b0-a929-4985-84b9-2c58e37a4dfd.png)
**_screenshot - 3_**

2. The attached video indicate first time when page load the translation of mentioned string visible but then after it is not translated.

https://user-images.githubusercontent.com/84851863/160330902-010a8672-844d-4098-90fa-1cca47254a13.mp4

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2022-03-29 04:32
Hi @deepeshjain2011 ,
Thank you for raising an issue , We tried to reproduce it on Magento 2.4.3-p1 but as per step#2 we could not find the way to add Language in Theme section. Hence request to review the provided steps.
Please find below screenshots for reference.
<img width="1440" alt="Screenshot 2022-03-29 at 9 44 18 AM" src="https://user-images.githubusercontent.com/51681379/160533585-3c55b050-cf71-4ce8-a4a3-ddb2d050205f.png">
![Uploading Screenshot 2022-03-29 at 9.46.56 AM.png…]()

**Comment by deepeshjain2011** [comment] 2022-03-29 04:56
Hi @engcom-Delta,
As i had mentioned i was tested this translation issue on 'Magento Blank' theme so i provide here way to add language file in 'Magento Blank' theme. When i was tested this translation issue, my theme language is 'Danish (da_DK)'.
Use following steps for add translation file in theme.

	1. Create the translation file (in my case - da_DK.csv) at vendor/magento/theme-frontend-blank/i18n/da_DK.csv
	2. Add the string "Discount (%1)" which is not translated in theme language (locale) in da_DK.csv
	3. Run cli command for Setup Upgrade, Clean Cache.

**Comment by engcom-Hotel** [comment] 2022-06-01 10:11
Hello @deepeshjain2011,

Thanks for the reporting & collaboration!

We have tried to reproduce the issue in Magento 2.4-develop branch but the issue is not reproducible for us. We have followed the below steps in order to reproduce the issue:
1. Get the da_DK translation file from [this repo](https://github.com/magento-l10n/language-da_DK).
2. Change the `Locale` with `Danish (Denmark)`:
<img width="900" alt="image" src="https://user-images.githubusercontent.com/51681618/171380864-cbf51a87-e7ff-4c8c-b2cb-15981b90f7d6.png">
3. Create a cart price rule and apply the same in the frontend, for us the translation is working fine. Please have a look to the below screenshot:

![image](https://user-images.githubusercontent.com/51681618/171381100-85986595-3641-4cc8-8fab-ab8d02ba5307.png)

Let us know in case we have missed anything.

Thanks

**Comment by deepeshjain2011** [comment] 2022-06-01 11:55
Hello @engcom-Hotel Have you added translation in theme language file as i had mentioned in 'Steps to reproduce (*) -> step 2' Can you please confirm ?

As you have added da_DK translation file from https://github.com/magento-l10n/language-da_DK
This is a language pack, not a theme translation language file which generally located at 'app/design/frontend/Enterprise/theme/i18n/da_DK.csv'

Please create theme translation language file and then check.

Thank you

**Comment by engcom-Hotel** [comment] 2022-06-02 07:46
Hello @deepeshjain2011,

Thanks for the reply!

We have again tried to reproduce the issue with theme translation, but for us, the issue is not reproducible. We have followed the below steps:
1. Followed [this article](https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/translations/translate_practice.html) for theme translation.
2. Add `"Discount (%1)","New Discount Text (%1)"` text in `da_DK.csv`.
3. Ran `./bin/magento setup:upgrade` command
4. Navigate to the cart page. We are having the updated text on this page. Please have a look at the below screenshot:
![image](https://user-images.githubusercontent.com/51681618/171580372-cb4f91f2-47ad-4511-ad64-19bfdded53a6.png)

Let us know in case we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2022-06-20 06:24
Dear @deepeshjain2011,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-06-20 06:24 UTC
Labels: Triage: Dev.Experience, Issue: needs update

**Comment by mortenbirkelund** [comment] 2022-06-30 06:48
Still relevant

**Comment by engcom-Hotel** [comment] 2022-06-30 07:50
Hello @mortenbirkelund,

We have tried to reproduce the issue as per the main description but the issue is not reproducible. Please let us know if we have missed anything in order to reproduce the issue.

Thanks

**Comment by hagotupagina-spa** [comment] 2022-11-10 18:37
It is reproducible for me 2.4.5-p1, the translated text flashes for about 0.1 seconds and then return the untranslated string.

**Comment by OtoKalan** [comment] 2022-11-14 08:31
Same here on Magento ver. 2.4.3-p1

**Comment by crazylink** [comment] 2023-02-07 10:04
Same here on 2.4.3-p2

**Comment by PachisPachis** [comment] 2023-03-04 18:48
Same here on 2.4.3-p2.

LAbel shows translated but after a few miliseconds it defaults to english "Discount".

I noticed that it occurs after a POST petition to https://example-site.com/rest/default/V1/carts/mine/totals-information

The response is:


`{"grand_total":8.35,"base_grand_total":10.1,"subtotal":9.24,"base_subtotal":9.24,"discount_amount":-1,"base_discount_amount":-1,"subtotal_with_discount":8.24,"base_subtotal_with_discount":8.24,"shipping_amount":0,"base_shipping_amount":0,"shipping_discount_amount":0,"base_shipping_discount_amount":0,"tax_amount":1.75,"base_tax_amount":1.75,"weee_tax_applied_amount":null,"shipping_tax_amount":0,"base_shipping_tax_amount":0,"subtotal_incl_tax":11.31,"base_subtotal_incl_tax":11.31,"shipping_incl_tax":0,"base_shipping_incl_tax":0,"base_currency_code":"EUR","quote_currency_code":"EUR","items_qty":1,"items":[{"item_id":76250,"price":9.24,"base_price":9.24,"qty":1,"row_total":9.24,"base_row_total":9.24,"row_total_with_discount":0,"tax_amount":1.73,"base_tax_amount":1.73,"tax_percent":21,"discount_amount":1,"base_discount_amount":1,"discount_percent":0,"price_incl_tax":11.18,"base_price_incl_tax":11.18,"row_total_incl_tax":11.18,"base_row_total_incl_tax":11.18,"options":"[]","weee_tax_applied_amount":0.11,"weee_tax_applied":"[{\"title\":\"RAEE\",\"base_amount\":0.11,\"amount\":0.11,\"row_amount\":0.11,\"base_row_amount\":0.11,\"base_amount_incl_tax\":0.13,\"amount_incl_tax\":0.13,\"row_amount_incl_tax\":0.13,\"base_row_amount_incl_tax\":0.13}]","name":"L\u00e1mpara standard fil Led STAR  E27 24W 4000K (Osram 619098)"}],"total_segments":[{"code":"subtotal","title":"Subtotal","value":9.24},{"code":"discount","title":"Discount (Descu)","value":-1},{"code":"shipping","title":"Shipping & Handling (Recogida en tienda)","value":0},{"code":"amasty_checkout","title":"Gift Wrap","value":null},{"code":"tax","title":"Tax","value":1.75,"area":"taxes","extension_attributes":{"tax_grandtotal_details":[{"amount":1.75,"rates":[{"percent":"21","title":"IVA 21%"}],"group_id":1}]}},{"code":"weee_tax","title":"FPT","value":0.11},{"code":"grand_total","title":"Grand Total","value":10.1,"area":"footer"}]}`

Please notice **{"code":"discount","title":"Discount (Descu)","value":-1},** because Discount label is wrong.

**Comment by PachisPachis** [comment] 2023-03-05 10:47
I could solve it in production environment by installing the language pack from Mageplaza, via composer:

```
composer update mageplaza/magento-2-spanish-language-pack:dev-master
php bin/magento setup:static-content:deploy es_ES
php bin/magento indexer:reindex
php bin/magento cache:clean
php bin/magento cache:flush
```
Credentials here: https://github.com/mageplaza/magento-2-spanish-language-pack

I think it could be realated to missing translation in previous language pack. I had tried to add the translation to the theme es_ES.csv but it didn't work.

Regards.
