### ISSUE TITLE
Saving a product produces a "No such entity with id =" banner

### ISSUE THREAD

**Issue by robertdeboer** [magento/magento2#37874] opened 2023-08-11 19:16 UTC
### Preconditions and environment

- Magento 2.4.6-p2
- Magento B2B module
- Enable B2B Company in Store -> Configuration -> General -> B2B Features: Enable Company
- Do *NOT* enable the B2B shared catalog
- Do *NOT* create any shared catalogs
- Do *NOT* assign any products to any shared catalog

### Steps to reproduce

Create a new product or update an existing product

### Expected result

The page refreshed and you see "You saved the product"

### Actual result

The page refreshes and you see "You saved the product" and "No such entity with id ="

In addition, this introduction of an error means if you go back to the product able and select Add New, the form may not clear itself and will contain all the product data of the previous product you were editing.

### Additional information

In tracking this issue, it comes from the Shared Catalog module, specifically `Magento\SharedCatalog\Model\SharedCatalogInvalidation->checkSharedCatalogExist()`.

This is becuase at `Magento\SharedCatalog\Observer\Controller\SaveProduct->execute() ` it is calling `Magento\SharedCatalog\Model\ProductManagement->assignProducts()` with an empty string.

In the observer, at line 77, I see this:
```php
         $forCreate = array_diff($sharedCatalogIds, $assignedSharedCatalogIds);
         foreach ($forCreate as $sharedCatalogId) {
            $this->productSharedCatalogManagement->assignProducts($sharedCatalogId, [$product]);
         }
```
The array_diff is returning an array with a single empty string and that is then being passed in the foreach and then in the function call.

I was able to patch this locally by:
```php
         $forCreate = array_diff($sharedCatalogIds, $assignedSharedCatalogIds);
         foreach ($forCreate as $sharedCatalogId) {
-            $this->productSharedCatalogManagement->assignProducts($sharedCatalogId, [$product]);
+            if(!empty($sharedCatalogId)) {
+                $this->productSharedCatalogManagement->assignProducts($sharedCatalogId, [$product]);
+            }
         }
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-08-14 11:17
Hi @robertdeboer,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**


- Create a new product or update an existing product


We are able to create new product and able to update the existing product.

<img width="1512" alt="Screenshot 2023-08-14 at 12 15 23 PM" src="https://github.com/magento/magento2/assets/51680745/bc71794a-e2f3-4b0b-83e6-d8f57c6038e4">


https://github.com/magento/magento2/assets/51680745/36eac5c4-5fc4-4b67-a93a-910b9c054f59



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-08-28 06:08
Hi @robertdeboer,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/37874#issuecomment-1677134798 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-08-31 06:02
Hi @robertdeboer,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-08-31 06:02 UTC
Labels: Issue: needs update, Reported on 2.4.6-p2
