### ISSUE TITLE
Ordered Products Report does not work

### ISSUE THREAD

**Issue by 29sunil** [magento/magento2#23554] opened 2019-07-03 09:56 UTC
### Preconditions (*)

1. We are using Magento 2.3.0 
2. Order Report issue

### Steps to reproduce (*)

1.login in the admin section 
2.click on report -> Products ->orderd 
3. Select data range from 30-01-19 to 30-06-19 or any other date ranges

### Expected result (*)

1. We need a correct result between two dates 
2.

### Actual result (*)

1. [Screensh
![reportse](https://user-images.githubusercontent.com/35294849/60582644-d9758380-9da6-11e9-8586-5a283e0fbb46.png)
ots, logs or description]
2. Video: https://www.loom.com/share/25fc0c0960724252a74ff812a263a1c4

**Comment by 29sunil** [comment] 2019-07-03 10:07
The current result is given below:
https://prnt.sc/o9wssx
https://prnt.sc/o9wtjs
https://prnt.sc/o9wtyq

So as per our understanding order report is not working. kindly resview it

**Comment by engcom-Bravo** [comment] 2019-07-03 14:16
Hello @29sunil. Thanks for reporting. Could You please try to reproduce Your issue on a vanila 2.3-develop instance asking a bot for it as You are advised above:
![Advised](https://user-images.githubusercontent.com/51680745/60598838-172dd880-9db6-11e9-92ef-d56718eea9f2.png)
(We haven't managed to reproduce the issue on such an instance by now).

**Comment by 29sunil** [comment] 2019-07-04 07:16
We did not understand This point (vanila 2.3-develop instance asking a bot for it as  ) . Can we need to reproduce this issues at vanilla 2.3 platforms? We are facing issues at Magento 2.3.0 version. We do not have more knowledge about vanilla. We think this issue is in Magento 2.3.0 version.

**Comment by engcom-Bravo** [comment] 2019-07-04 08:16
@29sunil, we can confirm the issue only if it is reproduced on a vanilla instance - a fresh installation clear of any custom modules, third party extensions and any other kinds of changes made to the original code.
Why `2.3-develop` version - fixes are applied only to the latest develop versions of 2.3 and 2.2 (if the issue has been reproduced on `2.3-develop`).
Now according to our workflow, (please see [above](https://github.com/magento/magento2/issues/23554#issuecomment-508027210) the details to step 4) if the issue is not reproduced on `2.3-develop` we are supposed to close it.
As we've already mentioned we've been not able to reproduce the issue on that version. It may mean three things: 

1. Your issue is caused by some custom code and therefore is not relevant for this repository - the issue has to be closed;
2. Your issue has already been fixed in some latter version - the issue has to be closed;
 3. In fact the issue resides in`2.3-develop` as well but we miss some additional information for getting it reproduced. In this case we need to be able to reproduce Your issue in order to confirm it. 

Therefore we ask You to try to reproduce the issue on a vanilla `2.3-develop` instance and in case of success to help us understand how the issue can be reproduced, so that we can reproduce it ourselves. It won't take much effort from You. Simply leave the comment like mentioned above and the bot will deploy an instance for You less then in 5 min.

**Comment by 29sunil** [comment] 2019-07-04 08:26
Ok let me check this issues at fresh magento 2.3.0 installation and get back to you

**Comment by engcom-Bravo** [comment] 2019-07-22 07:06
@29sunil, the contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.

**Closed as completed by engcom-Bravo** 2019-07-22 07:06 UTC
Labels: Progress: needs update, Issue: Format is valid
