### ISSUE TITLE
Production mode : error after di:compile (Magento v2.1.2)

### ISSUE THREAD

**Issue by agoeurysky** [magento/magento2#7250] opened 2016-10-31 14:09 UTC
In production mode, after deploying into integration environment, I am getting the following notices after running :

`rm -rf var/generation/* var/di/*`
`php bin/magento setup:upgrade`
`php bin/magento setup:di:compile`
`php bin/magento cache:clean`

```
Notice: Undefined index: arguments in vendor/magento/framework/ObjectManager/Config/Compiled.php on line 132
Call Stack
	Time	Memory	Function	Location
1	0.0002	246216	{main}( )	../index.php:0
2	0.0339	6821896	Magento\Framework\App\Bootstrap->createApplication( )	../index.php:36
3	0.0339	6822144	Magento\Framework\App\Bootstrap->initObjectManager( )	../Bootstrap.php:232
4	0.0339	6822880	Magento\Framework\App\ObjectManagerFactory->create( )	../Bootstrap.php:385
5	0.0434	7165712	Magento\Framework\ObjectManager\Config\Compiled->extend( )	../ObjectManagerFactory.php:159

Notice: Undefined index: instanceTypes in vendor/magento/framework/ObjectManager/Config/Compiled.php on line 133
Call Stack
	Time	Memory	Function	Location
1	0.0002	246216	{main}( )	../index.php:0
2	0.0339	6821896	Magento\Framework\App\Bootstrap->createApplication( )	../index.php:36
3	0.0339	6822144	Magento\Framework\App\Bootstrap->initObjectManager( )	../Bootstrap.php:232
4	0.0339	6822880	Magento\Framework\App\ObjectManagerFactory->create( )	../Bootstrap.php:385
5	0.0434	7165712	Magento\Framework\ObjectManager\Config\Compiled->extend( )	../ObjectManagerFactory.php:159


Notice: Undefined index: preferences in vendor/magento/framework/ObjectManager/Config/Compiled.php on line 134
Call Stack
	Time	Memory	Function	Location
1	0.0002	246216	{main}( )	../index.php:0
2	0.0339	6821896	Magento\Framework\App\Bootstrap->createApplication( )	../index.php:36
3	0.0339	6822144	Magento\Framework\App\Bootstrap->initObjectManager( )	../Bootstrap.php:232
4	0.0339	6822880	Magento\Framework\App\ObjectManagerFactory->create( )	../Bootstrap.php:385
5	0.0434	7165712	Magento\Framework\ObjectManager\Config\Compiled->extend( )	../ObjectManagerFactory.php:159

An error has happened during application run. See exception log for details. 
```

If I delete the var/di directory, everything is working fine.
There is no difference if the cache is activated or not.

**Comment by dthampy** [comment] 2016-10-31 15:33
duplicate of #7108

**Closed as completed by dthampy** 2016-10-31 15:33 UTC
