### ISSUE TITLE
Configurable product slow saving or time out

### ISSUE THREAD

**Issue by stupachenko** [magento/magento2#34678] opened 2021-11-19 11:20 UTC
### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Save a configurable product with ~50 simple product variations ~5 images to all SKUs

### Expected result (*)

1. The product is saved in a few seconds

### Actual result (*)

1. It takes more than 5 minutes to save the product
2. If no images are selected it takes a few seconds

**Comment by stupachenko** [comment] 2021-11-19 11:21
@magento give me 2.4-develop instance

**Comment by stupachenko** [comment] 2021-11-19 12:21
Confirmed
https://user-images.githubusercontent.com/3962252/142621954-72f1f9c8-8017-4825-b9f7-6beceea709fb.mp4

**Comment by engcom-November** [comment] 2021-11-24 12:59
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2021-11-24 13:52
Verified the issue on Magento 2.4-develop branch and the issue is reproducible.
Steps performed:
Admin - Catalog - Products - Created Configurable product with 50 Simple Product variations - Applied 5 Images to all SKU's
Saved Product.
Issue: Page is loading for more than 10min. Unable to save the Product

**Comment by reense** [comment] 2021-11-30 10:57
Is there a temporary patch we can use to fix this problem? This is causing huge issues for us currently.

**Comment by fredden** [comment] 2021-11-30 12:08
@reense this was discussed in the public issue triage meeting today. A work-around of using a product import (CSV) was suggested.

**Comment by jmulleman** [comment] 2021-12-17 16:28
@reense A temp fix can be setting the indexing on schedule is still terribly slow but the product is saving without errors.

**Comment by dzdaniel** [comment] 2022-03-15 07:28
I'm facing the same issue on 2.4.3-p1

**Comment by kylep1984** [comment] 2022-03-18 17:47
Hello! Any update on this item? This issue is also severely affecting our clients new to Magento 2 who seek to create configurable with many variations. A fix for this is urgently needed to meet the needs of clients who have very little experience in CSV importing and who sell products with many different variations. It is a severe blocker for them and gives them a very negative view of the platform. I would request for this to be expedited for a release soon!

**Comment by rudracomputech** [comment] 2022-07-26 04:43
Hello! I am having same issue, after adding 50 associate products the admin product edit page shows time out. I am using Magento ver. 2.4.4. 

Thanks
Rudra Computech
www.rudracomputech.com

**Comment by duncan16101994** [comment] 2023-02-06 03:51
Hello
I am having same issue on 2.4.3-p1
Any update?

**Comment by webcreative24** [comment] 2023-08-31 12:50
same here. Magento 2.4.6-p2

**Comment by engcom-Bravo** [comment] 2024-12-18 05:20
Hi @stupachenko,

Thanks for your reporting and collaboration.

We have verified the issue in latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the attached video.



https://github.com/user-attachments/assets/133fb83d-c52e-4201-83cb-59ef339b8df2


The product is saved in a few seconds


Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-12-18 05:20 UTC
Labels: Issue: Confirmed, Component: ConfigurableProduct, Reproduced on 2.4.x, Priority: P3, Progress: done, Reported on 2.4.x, Area: Product
