### ISSUE TITLE
API doesn't reflect admin panel image order in media_gallery_entries node from /rest/V1/products

### ISSUE THREAD

**Issue by janmyszkier** [magento/magento2#25330] opened 2019-10-28 09:28 UTC
### Preconditions (*)

1. Magento version 2.3.2
2. Two websites, one storeview in each.

### Steps to reproduce (*)
1. Create a configurable product
2. Add multiple children to it
3. upload images
4. reorder images by using drag and drop
5. query API `/rest/V1/products?searchCriteria[pageSize]=1000` to find your product

### Expected result (*)
1. The API JSON reponse should have the same position values as in `<input type="hidden" name="product[media_gallery][images][1581][position]" value="1" data-form-part="product_form" class="position">`

### Actual result (*)
1. The API shows incorrect order of the images in `media_gallery_entries`. Position values seems to be picked at random. There's no `1` nor `2` but `5` is shown twice, same for position `7`.

**Comment by engcom-Charlie** [comment] 2019-10-30 11:30
Hello @janmyszkier 
We are not able to reproduce this issue on the lates 2.3-develop branch.

**Manual testing scenario:**

1. Set Two websites to one storeview
2. Create a configurable product
3. Add multiple children to it
4. upload images
5. reorder images by using drag and drop
6. query API `GET /rest/V1/products?searchCriteria[pageSize]=1000` to find your product

**Actual result:**
The API JSON response have the same position values as in all inputs:

![image](https://user-images.githubusercontent.com/51680850/67847851-3f330b80-fb0c-11e9-8c98-4753ff10282a.png)
![Peek 2019-10-30 12-02](https://user-images.githubusercontent.com/51680850/67848504-7950dd00-fb0d-11e9-9fa1-8ea791f827c9.gif)

![image](https://user-images.githubusercontent.com/51680850/67847835-34787680-fb0c-11e9-8bb2-78377d977c3b.png)

So i have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-10-30 11:30 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid
