### ISSUE TITLE
Date, time and date&time customizable options should havу the same format in output and input

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#26108] opened 2019-10-11 12:13 UTC
### Preconditions (*)

1. Simple product with customizable options

### Steps to reproduce (*)

1. Add simple product to cart
```graphql
mutation {
  addSimpleProductsToCart(
    input: {
      cart_id: "XNpDkymvFOQBmxyDExJmgJdEZvjtFubt"
      cart_items: {
        data: {
          quantity: 1
          sku: "simple-product-date"
        }
        customizable_options: [
          {
            id: 5
            value_string: "01-01-01 02:00:05"
          }
        ]
      }
    }
  ) {
    cart {
      items {
        id
        quantity
        product {
          sku
          stock_status
        }
        ... on SimpleCartItem {
          customizable_options {
            id
            label
            values {
              id
              label
              value
            }
          }
        }
      }
    }
  }
}
```

### Expected result (*)

1. The output is the same as the input
```graphql
{
  "data": {
    "addSimpleProductsToCart": {
      "cart": {
        "items": [
          {
            "id": "3",
            "quantity": 1,
            "product": {
              "sku": "simple-product-date",
              "stock_status": "IN_STOCK"
            },
            "customizable_options": [
              {
                "id": 5,
                "label": "DateTimeOptional",
                "values": [
                  {
                    "id": 14,
                    "label": "",
                    "value": "01-01-01 02:00:05"
                  }
                ]
              }
            ]
          }
        ]
      }
    }
  }
}
```

### Actual result (*)

1. The format should be the same
```graphql
{
  "data": {
    "addSimpleProductsToCart": {
      "cart": {
        "items": [
          {
            "id": "3",
            "quantity": 1,
            "product": {
              "sku": "simple-product-date",
              "stock_status": "IN_STOCK"
            },
            "customizable_options": [
              {
                "id": 5,
                "label": "DateTimeOptional",
                "values": [
                  {
                    "id": 14,
                    "label": "",
                    "value": "1/2/01, 2:00 AM"
                  }
                ]
              }
            ]
          }
        ]
      }
    }
  }
}
```

**Comment by magento-engcom-team** [comment] 2019-12-18 21:24
:white_check_mark: Confirmed by @lenaorobei 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29906` were created

**Issue Available**: @lenaorobei, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by cpartica** [comment] 2020-07-14 21:26
@TomashKhamlai I am afraid we have to close this issue as not a bug, You have to read locale from the storeConfig and convert the data, as we don't format the date anywhere in GQL

**Closed as completed by cpartica** 2020-07-14 21:26 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: QuoteGraphQl, Reproduced on 2.4.x, Project: GraphQL, PAP
