### ISSUE TITLE
Maintenance mode disabling while using AWS S3 for media storage does not work

### ISSUE THREAD

**Issue by PauloPhagula** [magento/magento2#35254] opened 2022-03-31 14:28 UTC
### Preconditions (*)

1. Be running Magento v2.4.3-p1
2. Be using AWS S3 for media storage

### Steps to reproduce (*)

1. Enter maintenance mode: `bin/magento maintenance:enable`
2. Leave maintenance mode:  `bin/magento maintenance:disable`
3. The site will still be in maintenance mode until you go manually delete the `.maintenance.flag` file in the S3 bucket

*For whoever is going to debug this, please also try the steps above while S3 object versioning is enabled*

### Expected result (*)

1. Maintenance mode should be disabled after you run `bin/magento maintenace:disable`

### Actual result (*)

1. Maintenance mode is not disabled after you run `bin/magento maintenace:disable`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2022-08-09 09:25
Hello @PauloPhagula,

Thanks for the reporting and collaboration!

We have tried to reproduce the issue in Magento 2.4-develop branch but the issue is not reproducible for us. We have S3 is enabled for media storage. We can successfully access the portal after disabling the maintenance mode by running the below command:

`bin/magento maintenance:disable`

Please let us know in case we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2022-08-23 05:40
Dear @PauloPhagula,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-08-23 05:40 UTC
Labels: Issue: needs update
