### ISSUE TITLE
why mangeto 2 showing 1.0.0

### ISSUE THREAD

**Issue by Sanjay-100** [magento/magento2#35138] opened 2022-02-24 11:28 UTC
### Summary (*) Hi i setup magento local with git clone 
` git clone https://github.com/magento/magento2.git 
 `

### Examples (*)
i try to check with CLI
`
 php bin/magento --version
Magento CLI 1.0.0+no-version-set
`

 Solution ; don't know

magento admin panel 

![image](https://user-images.githubusercontent.com/98302784/155515829-434344be-b240-4b66-8bf4-0d3998fb619e.png)

**Comment by Sanjay-100** [comment] 2022-02-24 11:30
Summary of the issue : magento version wrong setup with git clone
Information on your environment : LEMP stack
Steps to reproduce :  create new clone ` git clone https://github.com/magento/magento2.git`
Expected and actual results  : magento panel version 2.*.*

**Comment by engcom-Hotel** [comment] 2022-02-24 13:03
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-02-25 07:19
Hello @Sanjay-100,

Thanks for posting the issue!

We have checked the issue in the cloud instance and it is not reproducible for us. Please have a look into below screenshot for reference:
![image](https://user-images.githubusercontent.com/51681618/155671892-a3d24282-441b-4754-a14b-67dbd698e271.png)

Please review again and let us know in case we have missed anything.

Thanks

**Comment by Sanjay-100** [comment] 2022-02-28 09:36
@engcom-Hotel    thanks for conformation  but why show me the wrong i am not sure

i create project with Git Repo clone 
`
git clone https://github.com/magento/magento2.git
`
Examples (*)
i try to check with CLI
`
php bin/magento --version Magento CLI 1.0.0+no-version-set
`

**Comment by engcom-Hotel** [comment] 2022-03-01 07:18
Hello @Sanjay-100,

You need to run the below command to check the Magento version:

`php bin/magento --version`

It will output something like the below:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/51681618/156122778-054fcd51-89e1-46a6-9adb-b461637b954a.png">

Thanks

**Comment by Sanjay-100** [comment] 2022-03-02 10:46
@engcom-Hotel   

`php bin/magento --version
Magento CLI 1.0.0+no-version-set

`

**Comment by engcom-Hotel** [comment] 2022-03-02 14:04
Hello @Sanjay-100,

Can you please try again by setting up fresh Magento in your system?

Thanks

**Comment by Sanjay-100** [comment] 2022-03-04 09:09
@engcom-Hotel   ok let me try that one

**Comment by engcom-Hotel** [comment] 2022-03-04 09:13
Ok @Sanjay-100, thanks for the reply.

**Comment by ponickkhan** [comment] 2022-03-10 06:25
tried this in fresh cloned repo and could not able to reproduce the issue
<img width="718" alt="Screenshot 2022-03-10 at 12 20 25 PM" src="https://user-images.githubusercontent.com/6341503/157601836-7440af74-4134-4ea7-bfa7-932fb63964b0.png">

**Comment by engcom-Hotel** [comment] 2022-03-21 08:10
Dear @Sanjay-100,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-03-21 08:10 UTC
Labels: Triage: Dev.Experience, Issue: needs update
