### ISSUE TITLE
UI Listing - Bookmark issue when no filters

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#38722] opened 2024-05-14 13:21 UTC
### Preconditions and environment

- Magento version 2.4.7

### Steps to reproduce

1. Create a listing with no filters, and with bookmark
2. Load the page containing the listing
3. Move a column to another position

### Expected result

Bookmark is saved

### Actual result

500 error : `Exception #0 (Exception): Warning: Undefined array key "filters" in /var/www/html/vendor/magento/module-ui/Controller/Adminhtml/Bookmark/Save.php on line 250` 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2024-05-16 08:43
Hello @Nuranto,

Thank you for the report and collaboration!

Tried to verify this on 2.4.7, but the issue is not reproducible.
Created a UI listing without filter element, moved the column to another position, and the bookmark is being saved.
Please take a look at the screeshot below:
<img width="1403" alt="image" src="https://github.com/magento/magento2/assets/60198231/3029ee49-a9e3-47b6-a19c-b7c32c702619">

Here I have moved the content column to first position, on page refresh the new configuration is retained.

Please find the custom module used to reproduce this, and let us know if we are missing anything.
[I38722V.zip](https://github.com/magento/magento2/files/15332064/I38722V.zip)

Thank you.

**Comment by Nuranto** [comment] 2024-05-16 08:59
Can you check the `mui/bookmark/save` xhr response code ? Is it 200 or 500 ?

**Comment by engcom-November** [comment] 2024-05-17 09:41
`mui/bookmark/save` xhr code is 200
<img width="683" alt="image" src="https://github.com/magento/magento2/assets/60198231/ea099fe0-aaf7-4da6-bb6e-292c4028e292">

**Comment by Nuranto** [comment] 2024-05-17 09:54
Alright, I can reproduce the issue with your module on two distinct environments, there must be an extra condition, but I don't know which one.

**Comment by ekomurz** [comment] 2024-05-26 16:22
I encountered the same error after updating an existing 2.4.6 project to 2.4.7.
It seems that updating the ui_bookmark table does not work always as expected.

I removed the records in that table for my admin account, and after this action: the sales grid was working just fine.

(I did not have time to investigate this further, but perhaps it may give you some clue to the origin of this issue ?)

**Comment by rogerdz** [comment] 2024-06-03 10:19
maybe fix with https://github.com/magento/magento2/pull/38784

**Comment by ki5-mshoaibq** [comment] 2024-07-15 13:32
Is there any work around for this currently?

**Comment by ki5-mshoaibq** [comment] 2024-07-24 17:26
Extended the bookmark save file 
`<preference for="Magento\Ui\Controller\Adminhtml\Bookmark\Save" type="Vendor\Module\Controller\Adminhtml\Bookmark\Save" />
`
And in extended file, changed code at line#250 onwards,

````
if ($existingConfig && $currentConfig) {
                    /*
                     * Default Magento code commented out
                    if ($existingConfig['filters'] === $currentConfig['filters']
                        && $existingConfig['positions'] !== $currentConfig['positions']
                    */
                    //Below check added
                    if ( (isset($existingConfig['filters']) && isset($currentConfig['filters']))
                        && ($existingConfig['filters'] === $currentConfig['filters'])
                        && ($existingConfig['positions'] !== $currentConfig['positions'])
                        //e.o. Below code added
                    ) {
                        $bookmarkConfig['views'][$bookmark->getIdentifier()]['data'] = $data[self::CURRENT_IDENTIFIER];
                        $bookmark->setConfig($this->serializer->serialize($bookmarkConfig));
                        $this->bookmarkRepository->save($bookmark);
                    }
                }
````
                

This fixed my problem.

**Comment by tuyennn** [comment] 2024-10-23 06:49
+1 Also got 

```
Warning: Undefined array key \"positions\" in vendor/magento/module-ui/Controller/Adminhtml/Bookmark/Save.php on line 251
```

Magento 2.4.7-p3

**Comment by usuyukiso** [comment] 2024-11-05 15:49
+1 
Warning: Undefined array key \"filters\" in vendor/magento/module-ui/Controller/Adminhtml/Bookmark/Save.php on line 250

**Comment by hostep** [comment] 2024-11-05 19:12
I believe this is the same as https://github.com/magento/magento2/issues/39013 and got fixed recently by https://github.com/magento/magento2/pull/38996

**Comment by engcom-Bravo** [comment] 2024-11-07 04:17
@hostep Thanks for your Contribution!!.

As per this comment the issue is fixed by this PR https://github.com/magento/magento2/pull/38996.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-11-07 04:17 UTC
Labels: Issue: Confirmed, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P2, Progress: done, Component: Frontend, Area: Admin UI, Reported on 2.4.7
