### ISSUE TITLE
Incorrect generate of "url_rewrite" (301) when change "url_key" more than two times

### ISSUE THREAD

**Issue by DmitriiChukhnov1** [magento/magento2#7443] opened 2016-11-15 18:34 UTC
### Preconditions

1. Magento CE 2.1.2
2. PHP 5.6.24
3. MySQL 5.7.13

### Steps to reproduce

1. Create and save new visible and active product with 'url_key' = 'test-product-1';
2. Change 'url_key' to 'test-product-2' and save product again.
3. Change 'url_key' to 'test-product-3' and save product again.

### Expected result

1. should be three url rewrites in table 'url_rewrite':
    * test-product-3.html => catalog/product/view/id/<product_entity_id> (redirect_type = 0)
    * test-product-1.html => test-product-3.html (redirect_type = 301)
    * test-product-2.html => test-product-3.html (redirect_type = 301)

### Actual result

![image](https://cloud.githubusercontent.com/assets/22075048/20318151/298fe706-ab7a-11e6-91f3-c702a704265e.png)
1. only two url rewrites:
    * test-product-3.html => catalog/product/view/id/<product_entity_id> (redirect_type = 0)
    * test-product-1.html => test-product-3.html (redirect_type = 301)

**Bug:** Url rewrite "test-product-2.html => test-product-3.html (redirect_type = 301)" is absent.

### How to fix
The bug is in class \Magento\CatalogUrlRewrite\Model\ProductUrlRewriteGenerator (/vendor/magento/module-catalog-url-rewrite/Model/ProductUrlRewriteGenerator.php line 181):
![image](https://cloud.githubusercontent.com/assets/22075048/20318311/cbc4cd52-ab7a-11e6-8a6d-1824d5d894c5.png)

We should use getRequestPath() instead of getTargetPath().

**Comment by dthampy** [comment] 2016-11-16 22:58
We already have an internal jira ticket MAGETWO-60911, which once fixed will resolve this issue.
Thanks for your report.

**Comment by hezide** [comment] 2017-05-19 16:32
I have the same issue on magento 2.1.6.
This ticket is since Nov 2016, what's the status of the issue?

**Comment by magento-engcom-team** [comment] 2017-10-11 08:30
@DmitryChukhnov, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by magento-engcom-team** [comment] 2018-11-13 11:33
Hi @TomashKhamlai. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by TomashKhamlai** [comment] 2018-11-13 11:41
The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.

**Closed as completed** 2018-11-13 11:42 UTC
Labels: Issue: Ready for Work, bug report, Component: CatalogUrlRewrite, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
