### ISSUE TITLE
Unable to save Attribute Set after creating

### ISSUE THREAD

**Issue by DaveDennisME** [magento/magento2#5784] opened 2016-07-24 17:22 UTC
When trying to create and save a new Attribute set. I am presented with a message saying "ATTENTION Sorry, we're unable to complete this request." when trying to save.
### Preconditions
1. Magento CE 2.1.0 installed without sample data through cli
2. Running Apache 2.2.31 (Unix)
3. PHP 5.6.23 with Zend Engine 2.6.0
4. MySQL 5.6.30
### Steps to reproduce
1. Go to Stores -> Attributes -> Attribute Sets
2. Click "Add Attribute Set"
3. Enter Attribute Set name and select base set ("Default" selected) and click "Save"
4. Assign attributes (NOTE: this error happens even if no new attributes are assigned)
5. Click "Save"
### Expected result
1. Attribute Set should save and I should be returned to the Attribute Set index page
### Actual result
1. I am presented with a notice "ATTENTION Sorry, we're unable to complete this request" (No errors are shown). I am then allowed to a) Close the modal using the "X", or b) Click "OK", which closes the modal.

![createattributeset](https://cloud.githubusercontent.com/assets/3355682/17085252/f5206950-51a1-11e6-9179-1df7628777e4.jpg)
![createattributeset2](https://cloud.githubusercontent.com/assets/3355682/17085254/f5211936-51a1-11e6-88ea-6a065c6aefc1.jpg)
![createattributeset3](https://cloud.githubusercontent.com/assets/3355682/17085253/f520a53c-51a1-11e6-939a-e892cac026ed.jpg)

**Comment by bartoszkubicki** [comment] 2016-07-27 06:22
Same here, for me it's just button save freezing for good without any message.

**Comment by SerhiyShkolyarenko** [comment] 2016-09-13 09:51
Hi @DaveDennisME and @bartek9007!
Please check your var/report dir for files created at the time of this request. Also tracking server response is useful. To get it you have to open browser debug panel(F12) before the final step, go to "Network" tab, then click "Save"(step 5). To get the response please click the request and go to "Response" tab(in the right part of panel).

**Comment by POLYPERFORMANCE** [comment] 2016-09-17 18:30
Some here. Assign two Unassigned Attributes to Product Details Group on existing Attribute Set. 
Attention 
Sorry, we're unable to complete this request.

**Comment by SerhiyShkolyarenko** [comment] 2016-09-19 14:07
@POLYPERFORMANCE I assigned two attributes like you, but that operation was successful. Performed both in FF and Chromium. Any ideas how to reproduce it?
Which version of magento do you use? Did you install it from composer or from github?

**Comment by POLYPERFORMANCE** [comment] 2016-09-19 14:27
@SerhiyShkolyarenko In my case, the two attributes that I assigned become unassigned after a while. When I attempt to reassign them I am met with error. I'm not sure why this is happening. To get around this error i've assigned the attributes directly into database table 'eav_entity_attribute'. I'm using Magento 2.1. Installed user composer.

**Comment by SerhiyShkolyarenko** [comment] 2016-09-26 14:11
Please, do the following steps:
1. Clear ALL browser cache for the whole period of time.
2. Remove generated static files:
`rm -rf pub/static/*`
3. Perform forced reloading in browser(Ctrl+F5).
Does the error still appear? Which error is displayed in browser console?

**Comment by SerhiyShkolyarenko** [comment] 2016-10-11 12:29
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Comment by Rudik123** [comment] 2016-11-02 10:29
Hi, I have a similar problem. Did  you solve this problem? I use magento 2.0.10.
I try @SerhiyShkolyarenko solution, but i have still notice "ATTENTION Sorry, we're unable to complete this request". 
Please help.

**Comment by SerhiyShkolyarenko** [comment] 2016-11-02 14:06
@Rudik123 we didn't reproduce the issue. Could you point all required steps for fresh installed Magento to reproduce it?

**Comment by veloraven** [comment] 2016-11-23 13:08
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Closed as completed by veloraven** 2016-11-23 13:08 UTC
Labels: bug report, Progress: needs update

**Comment by jarnail104** [comment] 2017-03-10 07:13
I am having same issue in version Magento ver. 2.1.3. 

Preconditions
Magento CE 2.1.3 installed with sample data 
PHP 7.0.15 with Zend Engine 3.0.0
MySQL 5.0.12

Steps to reproduce:
Go to Stores -> Attributes -> Attribute Sets
Click "Add Attribute Set"
Enter Attribute Set name and select base set ("Default" selected) and click "Save"
Assign attributes (NOTE: this error happens even if no new attributes are assigned)
Click "Save"

![scrn1](https://cloud.githubusercontent.com/assets/4506852/23785695/f864caec-058e-11e7-9deb-df7a8df0be45.png)

**Comment by jarnail104** [comment] 2017-03-15 05:09
I am quite sure its bug in magento but there is no response or solution for this yet. Its impossible to to create products without attribute set if someone need additional/different attribute set.  Why they are not addressing such issues which are root of system?

**Comment by jarnail104** [comment] 2017-03-15 07:46
This issue is because of server configuration and it fixed with the help from server support.

**Comment by metal971** [comment] 2017-04-10 09:45
Hi Guys its because of firewall's mod_security rules. Please check and whitelist the rules .. this problem will be resolved.

**Comment by joates-ldg** [comment] 2017-07-27 13:24
Hello, Could someone please outline the exact fix required to resolve this issue please as we have neither Apache nor mod_security but do have the issue.
