### ISSUE TITLE
Widget category tree is not rendered correctly

### ISSUE THREAD

**Issue by sheepfy** [magento/magento2#39008] opened 2024-08-05 12:24 UTC
### Preconditions and environment

- Magento version latest 2.4.7-p1

If you have deeper category levels, like till level 5 or 6, if you open an widget, place the widget on Anchor Categories, specific categories, the category tree in there, will not render more than 3 level due to incorrect handleOpenNode function.

This fix is a copy paste from the working handleOpenNode function from there: vendor/magento/module-catalog/view/adminhtml/templates/catalog/category/tree.phtml

Example tree before the fix:
![image](https://github.com/user-attachments/assets/9e259183-ddbe-4b80-9316-ef22928e4fb1)

Example tree after the fix:
![image](https://github.com/user-attachments/assets/439d9bd2-3ded-46f6-b277-dd2238a78ab3)

Issue fixed by this PR https://github.com/magento/magento2/pull/39007

### Steps to reproduce

On vanila magento with sampledata, create 2 more categories under Woman -> Tops -> Jackets
Go to widgets -> pick one or create one -> select Anchor Categories -> Specific categories -> Open category tree

### Expected result

Have all the categories available in the tree

### Actual result

Tree is not fully rendered

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-08-06 04:38
Hi @sheepfy,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- On vanila magento with sampledata, create 2 more categories under Woman -> Tops -> Jackets
- Go to widgets -> pick one or create one -> select Anchor Categories -> Specific categories -> Open category tree


![Widgets-New-Widget-Elements-Content-Magento-Admin](https://github.com/user-attachments/assets/899cf73e-8d01-47dc-8f5d-0006cf81abfa)


Tree is not fully rendered


Hence Confirming the issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-08-22 06:20
Hi @sheepfy,

Internal team has started to work on it

Thanks.

**Comment by ihor-sviziev** [comment] 2024-09-12 10:28
Looks like it's fixed together with https://github.com/magento/magento2/issues/38851#issuecomment-2345340785.
@sheepfy @engcom-Delta could you confirm that?

**Comment by hostep** [comment] 2024-09-12 11:24
I don't think so, this tree in the widget is another tree component than the one in the category section.
`view/adminhtml/templates/catalog/category/**widget**/tree.phtml` vs `view/adminhtml/templates/catalog/category/tree.phtml`

**Comment by engcom-Bravo** [comment] 2024-09-12 11:37
@ihor-sviziev @hostep @sheepfy Thanks for your contribution!!

For clarity, changes in commit [1a27a04](https://github.com/magento/magento2/commit/1a27a04884cb900008903536003cb4064d558716) are not related to Widget category tree as described in this issue.
This issue got partially fixed under below commits:
https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-3136&type=commits
But there are still some pending issues like multiple ajax calls which are in implementation under JIRA https://jira.corp.adobe.com/browse/AC-12692 and we’ll update once it is fixed and delivered.

Thank.

**Comment by hostep** [comment] 2024-10-21 20:36
Probably got fixed by [AC-12692: Widget category tree is not rendered correctly](https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-12692&type=commits), there is no clean merge commit unfortunately, but [this one](https://github.com/magento/magento2/commit/5a2037c35de89ce2c50e230164ff3ea7b67ac127) comes close (just ignore the changes in `composer.lock`)

**Comment by engcom-Bravo** [comment] 2024-10-22 06:24
@hostep Thanks for your Contribution!!!.

Hi @sheepfy,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-12692 by the internal team
Related commits: https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-12692&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta2.

Thanks

**Closed as completed by engcom-Bravo** 2024-10-22 06:24 UTC
Labels: Issue: Confirmed, Component: Widget, Reproduced on 2.4.x, Priority: P2, Priority: P1, Progress: done, Area: Content, Reported on 2.4.7-p1

**Comment by cptX** [comment] 2025-01-25 09:32
Can somebody give us some clear instructions how to solve it? This is major... again... and again... and again ...
