### ISSUE TITLE
PayPal Payflow Pro 500 Internal Server Error

### ISSUE THREAD

**Issue by agubarev-ifuelinteractive** [magento/magento2#34607] opened 2021-11-11 08:14 UTC
The issue https://github.com/magento/magento2/issues/30541#issue-724450589 is still replicated on Magento ver. 2.4.3-p1.
Please review.

**Comment by engcom-Hotel** [comment] 2021-11-11 10:52
Hello @agubarev-ifuelinteractive,

We have tried to reproduce this issue in Magento 2.4-develop branch but it is not reproducible for us. We request you to help us with the specific condition on which this issue occurs, if possible then screenshot/video as well.

Thanks

**Comment by agubarev-ifuelinteractive** [comment] 2021-11-12 14:06
Preconditions (*)
PHP 7.1.33 / PHP 7.3.16.
MySQL 5.7.31 / MariaDB 10.2.21.
Production mode is enabled.
PayPal Payflow Pro payment method is configured.
Debug mode in PayPal Payflow Pro configuration is enabled.

Steps to reproduce (*)
Navigate to storefront.
Login into customer`s account.
Go to the any product page.
Click "Add to Cart".
Open mini shopping cart and click "Proceed to Checkout".
Fill in the all required shipping fields
Choose 'PayPal Payflow Pro' payment method.
Fill in the all required fields: Credit Card Number, Expiration Date, Card Verification Number.
Click 'Place Order' button.

**Comment by engcom-Hotel** [comment] 2021-12-07 09:18
@magento give me 2.4.3-p1 instance

**Comment by engcom-Hotel** [comment] 2021-12-08 09:24
Hello @agubarev-ifuelinteractive,

We have tried to reproduce the issue in Magento 2.4-develop branch the issue is not reproducible for us. Please refer the below video for reference and let us know if we missed anything in order to reproduce it:

https://user-images.githubusercontent.com/51681618/145182966-2c40f126-3e5e-413e-9891-8d35672823be.mp4

Thanks

**Comment by engcom-Hotel** [comment] 2021-12-22 09:32
Dear @agubarev-ifuelinteractive,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2021-12-22 09:32 UTC
Labels: Issue: needs update
