### ISSUE TITLE
Related product rule does not work if you select a specific product (Product Match) and a rule that looks for the same attribute (Product Result)

### ISSUE THREAD

**Issue by nikita-biliavskyi** [magento/magento2#36378] opened 2022-10-27 08:31 UTC
### Preconditions and environment

- Magento Enterprise 2.4.5-p1 (vanilla).

### Steps to reproduce

1. Go to BO->Marketing->Promotions->Related Products Rules;
2. Create new or edit rule;
3. On tab "Rule Information" fill all necessary fields. In the "Apply To" field, select Related Products or Up-Sells;
4. On tab "Products on Match" choose some product by SKU (SKU is YOUR_PRODUCT_SKU);
5. On tab "Products to Result" choose the category attribute and set the option "the Same as Matched Product Categories" (Product Category is the Same as Matched Product Categories);
6. Save Rule;
7. Go to the product (PDP) SKU you used (this product must be more than one in its category).

### Expected result

The Related Products/Up-Sells block displays products that have the same category as the selected product.

### Actual result

The Related Products/Up-Sells block does not display products at all.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-11-03 07:20
@magento give me 2.4-develop instance with edition ee

**Comment by engcom-November** [comment] 2022-11-03 11:57
@magento give me 2.4-develop instance with edition ee

**Comment by engcom-November** [comment] 2022-11-03 12:25
Hi @nikita-biliavskyi ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop with Enterprise edition but the issue is not reproducible.
Related Products/Up-Sells products that have the same category as the selected product are displayed as expected.
![image](https://user-images.githubusercontent.com/60198231/199719569-dbd9daa8-7a9a-47ae-a375-b04db41df01e.png)
Kindly recheck the issue on Magento 2.4-develop instance ans provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by nikita-biliavskyi** [comment] 2022-11-04 10:37
Hi @engcom-November 
I found the reason for this behavior myself, it is caused by the added fixes to the standard Magento module, so this behavior is normal.

**Comment by engcom-November** [comment] 2022-11-04 18:13
Thank you for the response @nikita-biliavskyi . We are closing this issue as its not reproducible on clean vanila Magento 2.4-develop latest Magento instance. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-11-04 18:13 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
