### ISSUE TITLE
Deprecation Notice while running 'composer install' under application root directory

### ISSUE THREAD

**Issue by stamster** [magento/magento2#4554] opened 2016-05-18 13:47 UTC
## Steps to reproduce
1. Install latest Magento from `master` branch.
2. Run `composer install`
## Result

`Deprecation Notice: The callback MagentoHackathon\Composer\Magento\Plugin::onNewCodeEvent declared at /var/www/html/staging/vendor/magento/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Plugin.php accepts a Composer\Script\CommandEvent but post-install-cmd events use a Composer\Script\Event instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:289`

This issue is present on releases from 2.0.4 to latest 2.0.6 (haven't tested before 2.0.4).

**Comment by tkn98** [comment] 2016-05-18 13:52
Most likely dupe of #4383

**Comment by mazhalai** [comment] 2016-05-18 14:32
Closing, since fix has been merged in https://github.com/magento/magento-composer-installer/releases/tag/0.1.8

**Closed as completed by mazhalai** 2016-05-18 14:32 UTC
