### ISSUE TITLE
Missing filtering by `store_id`in catalog search

### ISSUE THREAD

**Issue by U12358** [magento/magento2#8689] opened 2017-02-27 12:40 UTC
### Preconditions
Magento 2.1.4

### Steps to reproduce
Category Search /as result - Layer Navigation/ works very slow.
For DB with 2 millions products and 8 stores works about 1 min.

### Actual result
During investigation found place in code where table `catalog_category_product_index` using without filtering by field `store_id`.

### Expected result
p.s. If add filtering by `store_id`, query works 3 seconds.

See screenshots
![screenshot_20170227_143335](https://cloud.githubusercontent.com/assets/813985/23361574/0a91e3aa-fcfa-11e6-86ac-ab74b359bd35.png)

file Magento\CatalogSearch\Model\Search\TableMapper with commented modification

![screenshot_20170227_143354](https://cloud.githubusercontent.com/assets/813985/23361575/0c99b6d2-fcfa-11e6-846e-6e1ed983cd32.png)

**Comment by veloraven** [comment] 2017-06-30 06:29
@SKovbel thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by magento-engcom-team** [comment] 2017-09-19 19:25
@SKovbel, thank you for your report.
The issue is already fixed in 2.1.8

**Closed as completed by magento-engcom-team** 2017-09-19 19:25 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Fixed in 2.1.x, Issue: Format is valid
