### ISSUE TITLE
PHP 7.4 Bug

### ISSUE THREAD

**Issue by bagbarn** [magento/magento2#29786] opened 2020-08-27 20:50 UTC
### Preconditions (*)

1. Magento 2.3.5-p2
**Does`t reproducible on 2.4-develop**
### Steps to reproduce (*)

1. Install M2.4 on dev server using php 7.3.21
2. Change to 7.4.9 after successful M2.4 installation
3. Home page loads correctly but catalog and product pages returns "processing error"
4. All pages load correctly when reverting to php7.3.21
### Expected result (*)

1. pages to load without error message

### Actual result (*)

1. The following error from a catalog page

```
There has been an error processing your request
Exception printing is disabled by default for security reasons.
Error log record number: 921b64f83f773dc5225d6ec76a9ea002fe2a6673022b55ee3b0f8a15cc5f57aa
```

2. Contents of the error log

`
{"0":"Notice: Trying to access array offset on value of type null in \/home\/jetrails\/dev.bagbarn.com\/html\/vendor\/magento\/framework\/App\/AreaList.php on line 75","1":"#1 Magento\\Framework\\App\\AreaList->getCodeByFrontName() called at [vendor\/magento\/framework\/App\/Http.php:111]\n#2 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:24]\n#3 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:261]\n#4 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:40]\n","url":"\/all-purpose-poly-bags\/grocery-bags","script_name":"\/index.php","report_id":"921b64f83f773dc5225d6ec76a9ea002fe2a6673022b55ee3b0f8a15cc5f57aa"}
`

**Additional information** 

The 2.4 developer already supports php 7.4, but 2.3.5-p2 doesn`t.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment] 2020-08-31 15:50
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37243` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Delta** [comment] 2020-09-01 14:24
Hi @bagbarn thank you for your report. I rechecked again as my previous instance was misconfigured. The issue is not reproducible in such cases:
- upgrade from 2.3.5-p2 to 2.4.0 - no errors on catalog page with php7.3/7.4( flow from https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html)
- install 2.4-develop with php7.3 than change php to 7.4 - no errors on catalog page
- install 2.4.0 with php 7.3 than change php to 7.4 - no errors on catalog page

Is there any additional information to help reproduce this issue ?

**Comment by engcom-Delta** [comment] 2020-09-22 11:49
@bagbarn we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Closed as completed by engcom-Delta** 2020-09-22 11:49 UTC
Labels: Issue: Ready for Work, Area: Frontend, Issue: Clear Description, Issue: Format is valid, Component: Other, Reproduced on 2.3.5p2, Progress: done, Reported on 2.3.5-p2

**Comment by bagbarn** [comment] 2020-09-22 15:20
we error reporting to no and that solved the problem

    On Tuesday, September 22, 2020, 7:49:47 AM EDT, Vasyl Shvorak <notifications@github.com> wrote:  
 
 


@bagbarn we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Comment by arvind-curotec** [comment] 2021-02-25 05:59
This happens in 2.4.2 when run on PHP 7.3

**Comment by bagbarn** [comment] 2021-02-25 15:33
We are running on php ^7.4

    On Thursday, February 25, 2021, 1:00:09 AM EST, Arvind Bhardwaj <notifications@github.com> wrote:  
 
 


This happens in 2.4.2 when run on PHP 7.3
