### ISSUE TITLE
2.2.3 : The EAV ReadHandler does not order the attributes when fetching them from the database

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#14114] opened 2018-03-15 08:54 UTC
This one was a bit tricky to track down but bear with me:

I had the situation where when I would load a product of a certain store ID, for some attributes I would get the value of the admin store. Using the famous var_dump 'n die-debugging technique I was able to track down the problem:

`Magento\Eav\Model\ResourceModel\ReadHandler::execute()`.

In this method, various select-statements are built to fetch the EAV-attribute values for a specific store ID, and they are bundled together using UNION. For example, this query would be generated for varchar attributes:

```sql
SELECT `t`.`value`, 
        `t`.`attribute_id` 
 FROM   `catalog_product_entity_varchar` AS `t` 
 WHERE  ( entity_id = '3' ) 
        AND ( `store_id` IN ( '2', 0 ) ) 
 ORDER  BY `t`.`store_id` DESC
```
The interesting part here is the `store_id IN (2,0)` in combination with the `ORDER BY store_id DESC`. This makes sure that there are results for the given store ID, and a fallback to store ID 0, which is the default admin value.

Next up, a UNION is done to make it all work together.

However...

As the [MySQL documentation](https://dev.mysql.com/doc/refman/5.7/en/union.html) states:

> Use of ORDER BY for individual SELECT statements implies nothing about the order in which the rows appear in the final result because UNION by default produces an unordered set of rows. Therefore, the use of ORDER BY in this context is typically in conjunction with LIMIT, so that it is used to determine the subset of the selected rows to retrieve for the SELECT, even though it does not necessarily affect the order of those rows in the final UNION result. If ORDER BY appears without LIMIT in a SELECT, it is optimized away because it will have no effect anyway.

Especially the _"it is optimized away"_-part. This effectively means that in a UNION, if the subqueries have an ORDER BY, without a LIMIT, there is **no ordering at all**.

And this was exactly the cause of my problem: the ID of the value for store ID 0 was lower in my database than those of the individual store views. Therefore, the default position in the database is used in the final result.

A possible solution for this is to:

a) add a LIMIT to the subqueries, or:
b) add the store_id to the subqueries and order the final UNION on that.

### Preconditions

1. Magento 2.2.3
2. Multiple store views for different languages (I have 4 in my case: nl, de, fr and en)

### Steps to reproduce

1. Create an EAV textfield (varchar) attribute.
2. Give them different values for each store view.
3. (manually) change the `value_id` in the database so that store view 0 is always lower than the others. For example:

value_id|attribute_id|store_id|entity_id|value
---|---|---|---|---
9|73|0|3|(dutch value)
736|73|2|3|(german value)
757|73|3|3|(english value)
778|73|4|3|(french value)

4. Use the product repository to load the product of store ID 2.

### Expected result

1. The resulting value of attribute_id 73 should be _"(german value)"_

### Actual result

1. The result is the value of store ID 0 _"(dutch value)"_

**Comment by kanduvisla** [comment] 2018-03-15 08:56
I now see that this is a possible duplicate of: #6958

**Comment by magento-engcom-team** [comment] 2018-03-15 14:24
@kanduvisla , We a closing as duplicate of #6958

**Closed as completed by magento-engcom-team** 2018-03-15 14:24 UTC
Labels: Issue: Format is valid

**Comment by magento-engcom-team** [comment] 2018-03-15 14:30
@kanduvisla, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
