### ISSUE TITLE
Magento 2.3.6 search result page issue NO PRODUCT THUMBNAILS

### ISSUE THREAD

**Issue by diegozanotti** [magento/magento2#33365] opened 2021-06-27 15:32 UTC
### Preconditions (*)
1. Magento 2.3.6
2. Php 7.3.2.8
3. Elasticsearch 7
4. Porto Theme (lastest version)

### Steps to reproduce (*)
1. Type a term into search bar
2. Click on search button
3. Search list page result is ok, but NO PRODUTC IMAGES, product list show placeholder image and the correct image only on mouse over product.
4. I have tried using original Luma theme (instead of Porto theme) but result ISSUE is the same

### Expected result (*)
1. Search products list show correct thumbnails

### Actual result (*)
1. Search products list don't show correct thumbnails, but just placeholder images (correct thumbnails are showed on mouse over)
2. (note) Other product lists are shown correctly

---
PORTO THEME ON
**Here thumbnail image path**
Correct image in product list (correct)
https://www.prochet1861.com/pub/media/catalog/product/cache/bb9dc070e2c11e42e26fdc86dfdfe117/v/a/vass_1.jpg

**PORTO THEME - Product search list (after page loading)**
https://www.prochet1861.com/pub/static/version1624394865/frontend/Smartwave/porto/it_IT/Magento_Catalog/images/product/placeholder/small_image.jpg

**Product search list on rollover (correct)**
https://www.prochet1861.com/pub/media/catalog/product/cache/bb9dc070e2c11e42e26fdc86dfdfe117/v/a/vass_1.jpg

**LUMA THEME - Product search list ((after page loading)**
https://www.prochet1861.com/pub/static/version1624394865/frontend/Magento/luma/it_IT/Magento_Catalog/images/product/placeholder/small_image.jpg

Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ X ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2021-07-05 08:52
Verified the issue on 2.4-develop Magento version and the issue is not reproducible on original Luma Theme as well:
**Steps performed:**
1. Front-end - Typed a term into Search bar
2. Clicked on the Search bar
**No Issue:** Search Result page shows correct thumbnails - > Actual Product images are displayed but not Placeholder images
![image](https://user-images.githubusercontent.com/60198231/124444331-19a7dc00-dd9c-11eb-9ad4-063aa4ab823f.png)
@diegozanotti, Can you please verify the issue on latest Magento version and let us know the missing steps if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2021-07-19 06:56
Hi @diegozanotti ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-07-19 06:56 UTC
Labels: Component: Search, Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.3.6
