### ISSUE TITLE
mutation createEmptyCart doesn't throw exception when authorization header is set and token has expired

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#26112] opened 2019-02-26 12:59 UTC
### Preconditions (*)

1. Registered Customer is created

### Steps to reproduce (*)

1. Generate Customer token
2. Wait for token expiration
3. Create empty cart using expired token

### Expected result (*)

1. Cart is not created because token has expired
```
"message": "The current customer isn't authorized.",
"category": "graphql-authorization"
```
2. Guest cart is not created because token was used

### Actual result (*)

1. Guest cart is created

**Comment by magento-engcom-team** [comment] 2019-12-19 10:19
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29927` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2020-06-16 14:18
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-29927).

**Comment by magento-engcom-team** [comment] 2020-06-16 14:18
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-29927).

**Comment by magento-engcom-team** [comment] 2020-06-16 14:19
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-29927).

**Comment by magento-engcom-team** [comment] 2020-06-16 14:19
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-29927).

**Comment by magento-engcom-team** [comment] 2020-06-16 14:20
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-29927).

**Comment by magento-engcom-team** [comment] 2020-06-16 14:20
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-29927).

**Comment by mauragcyrus** [comment] 2020-11-13 00:46
Hi @TomashKhamlai we have a proposal from architects here: https://github.com/magento/architecture/blob/deprecate-createEmptyCart-add-createCart/design-documents/graph-ql/coverage/deprecate-createEmptyCart-add-createGuestCart.md on how to handle this fix if you would like to take a look :)

**Comment by mauragcyrus** [comment] 2021-03-04 17:00
Two very similar issues: https://github.com/magento/magento2/issues/29922

**Comment by engcom-Hotel** [comment] 2022-09-20 09:03
Hello @TomashKhamlai,

We have tried to reproduce the issue in Magento 2.4-develop branch and we have the below findings.
we have tried with an expired token and we are not able to get the cart created. 

followed steps:-

- Generate Customer token
- Wait for token expiration
- Create an empty cart using the expired token

Please find the below screen for your reference.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51681618/191214997-24ae5fa0-9774-4c15-b2a1-2b443266bfe9.png">

As the issue is not reproducible, hence we are closing the issue. Let us know in case you are still able to reproduce the issue.

Thanks

**Closed as completed by engcom-Hotel** 2022-09-20 09:03 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Issue: Format is valid, Component: QuoteGraphQl, Reproduced on 2.4.x, Priority: P3, Project: GraphQL, Progress: done
