### ISSUE TITLE
Warning: Undefined array key "agreementId" in vendor/paypal/module-braintree-core/Plugin/AddAgreementsToMinicartConfig.php

### ISSUE THREAD

**Issue by sw-tt-jaydeepcharadva** [magento/magento2#36736] opened 2023-01-12 11:28 UTC
### Preconditions and environment

- Upgrading Magento Enterprise version from 2.4.3 - 2.4.5

### Steps to reproduce

Steps to reproduce:
1. composer require magento/product-enterprise-edition=2.4.5 --no-update
2. composer require magento/magento-cloud-metapackage=2.4.5 --no-update
3. composer update
4. bin/magento deploy:mod:set developer
5. rm -rf var/di var/cache/ var/page_cache/ generated/code/
6. php bin/magento setup:upgrade
7. php bin/magento setup:di:compile
8. Go to Home page.
9. Exception #0 (Exception): Warning: Undefined array key "agreementId" in /vendor/paypal/module-braintree-core/Plugin/AddAgreementsToMinicartConfig.php on line 42

Note : This is warning message which is affected for developer mode only. If we change mode as default then that warning message falls into system.log file.

### Expected result

Home page should be open and working.

### Actual result

1 exception(s):
Exception #0 (Exception): Warning: Undefined array key "agreementId" in /var/www/html/sapintegration/vendor/paypal/module-braintree-core/Plugin/AddAgreementsToMinicartConfig.php on line 42

Exception #0 (Exception): Warning: Undefined array key "agreementId" in /var/www/html/sapintegration/vendor/paypal/module-braintree-core/Plugin/AddAgreementsToMinicartConfig.php on line 42
<pre>#1 PayPal\Braintree\Plugin\AddAgreementsToMinicartConfig->afterGetConfig() called at [vendor/magento/framework/Interception/Interceptor.php:146]
#2 Magento\Checkout\Block\Cart\Sidebar\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-01-12 13:34
Hi @sw-tt-jaydeepcharadva,

Thank you for reporting and collaboration.

We have verified the issue while upgrading Magento Enterprise version from 2.4.3 - 2.4.5. we are not able to reproduce the issue.

We are open to Home page and instance is working fine.

We have followed Magento upgrade guide https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/implementation/perform-upgrade.html.Kindly go through with this document while this document.

Kindly let us know if you are still facing any issue.

Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-01-24 09:12
Hi @sw-tt-jaydeepcharadva,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-01-24 09:12 UTC
Labels: Issue: needs update, Reported on 2.4.5
