### ISSUE TITLE
No services listed when creating an integration

### ISSUE THREAD

**Issue by nobuttsalex** [magento/magento2#4537] opened 2016-05-17 09:28 UTC
**Steps to reproduce**
Currently on the dev branch. When I go to System > Integrations > Add New Integration the resources list is empty.

/soap/default?wsdl_list=1 also only lists
- /soap/default?wsdl&amp;services=0
- /soap/default?wsdl&amp;services=1
- /soap/default?wsdl&amp;services=2
  ...

all the way to 45. From what I've read it should list things such as catalogProductRepositoryV1

**Expected result**
![m2 resources list](https://cloud.githubusercontent.com/assets/9484573/15317588/0d6375f6-1c1a-11e6-93b7-f1eeef68584d.jpeg)

**Actual result**
![m2 empty resources list](https://cloud.githubusercontent.com/assets/9484573/15317544/e207e0c2-1c19-11e6-8b5c-de539ecd7c96.png)

**Comment by pboisvert** [comment] 2016-05-17 12:11
Mark--can you have the API team investigate this report?

**Comment by nobuttsalex** [comment] 2016-05-17 12:36
I should have pointed out I'm using PHP 7 which may help replicate the problem

**Comment by mbrinton01** [comment] 2016-05-26 20:41
Thank you @nobuttsalex, I have created internal issue MAGETWO-53522 to look into this for you.

**Comment by cspruiell** [comment] 2016-05-27 15:05
Hi @nobuttsalex, we are unable to reproduce the issue with the missing services in the integration screens using any version of PHP. Have you tried clearing your browser cache to flush any outdated JS files?
I have opened a separate internal issue to investigate the issue of the incorrect WSDL list: MAGETWO-53545.

**Comment by davidverholen** [comment] 2016-05-31 11:37
same problem here with the WSDL List on 2.1.0-rc1. Also any resource (for example /soap/default?wsdl&services=catalogProductRepositoryV1) responds with an error "Consumer ist not authorized to access %resources" while on 2.0 the resources wsdl is rendered.

**Comment by KrystynaKabannyk** [comment] 2016-06-23 16:30
Hello @nobuttsalex, this issue has been fixed in the 2.1.0 Release, that's why I'm closing it. If you any questions or additional information regarding the issue feel free to reopen it or create a new one.

**Closed as completed by KrystynaKabannyk** 2016-06-23 16:30 UTC
Labels: Issue: Ready for Work
