### ISSUE TITLE
Call to a member function getValue() on null in vendor/magento/module-bundle/Model/Product/Type.php:1098

### ISSUE THREAD

**Issue by shakeblue** [magento/magento2#38779] opened 2024-05-31 10:06 UTC
### Preconditions and environment

Hi, we have a Fatal exception when accessing the cart page with V1/carts/mine/estimate-shipping-methods.
Magento version: : 2.4.3

Detailed error:

> Call to a member function getValue() on null in /app/vw75fn4ansfpu/vendor/magento/module-bundle/Model/Product/Type.php:1098
> 
> Stack trace:
> #0 /app/vw75fn4ansfpu/vendor/magento/module-quote/Model/Quote/Item/AbstractItem.php(342): Magento\Bundle\Model\Product\Type->checkProductBuyState()
> #1 /app/vw75fn4ansfpu/vendor/magento/module-quote/Model/ResourceModel/Quote/Item/Collection.php(295): Magento\Quote\Model\Quote\Item\AbstractItem->checkData()
> #2 /app/vw75fn4ansfpu/vendor/magento/module-quote/Model/ResourceModel/Quote/Item/Collection.php(214): Magento\Quote\Model\ResourceModel\Quote\Item\Collection->_assignProducts()
> #3 /app/vw75fn4ansfpu/vendor/magento/framework/Data/Collection/AbstractDb.php(594): Magento\Quote\Model\ResourceModel\Quote\Item\Collection->_afterLoad()
> #4 /app/vw75fn4ansfpu/generated/code/Magento/Quote/Model/ResourceModel/Quote/Item/Collection/Interceptor.php(32): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter()
> #5 /app/vw75fn4ansfpu/vendor/magento/framework/Data/Collection/AbstractDb.php(565): Magento\Quote\Model\ResourceModel\Quote\Item\Collection\Interceptor->loadWithFilter()
> #6 /app/vw75fn4ansfpu/vendor/magento/framework/Data/Collection.php(840): Magento\Framework\Data\Collection\AbstractDb->load()
> #7 /app/vw75fn4ansfpu/vendor/magento/module-quote/Model/Quote.php(1447): Magento\Framework\Data\Collection->getIterator()
> #8 /app/vw75fn4ansfpu/vendor/magento/module-quote/Model/QuoteRepository/LoadHandler.php(46): Magento\Quote\Model\Quote->getAllVisibleItems()
> #9 /app/vw75fn4ansfpu/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\QuoteRepository\LoadHandler->load()
> #10 /app/vw75fn4ansfpu/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\QuoteRepository\LoadHandler\Interceptor->___callParent()
> #11 /app/vw75fn4ansfpu/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteRepository\LoadHandler\Interceptor->Magento\Framework\Interception\{closure}()
> #12 /app/vw75fn4ansfpu/generated/code/Magento/Quote/Model/QuoteRepository/LoadHandler/Interceptor.php(23): Magento\Quote\Model\QuoteRepository\LoadHandler\Interceptor->___callPlugins()
> #13 /app/vw75fn4ansfpu/vendor/magento/module-quote/Model/QuoteRepository.php(155): Magento\Quote\Model\QuoteRepository\LoadHandler\Interceptor->load()
> #14 /app/vw75fn4ansfpu/vendor/magento/module-quote/Model/QuoteRepository.php(180): Magento\Quote\Model\QuoteRepository->getForCustomer()
> #15 /app/vw75fn4ansfpu/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\QuoteRepository->getActiveForCustomer()
> #16 /app/vw75fn4ansfpu/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\QuoteRepository\Interceptor->___callParent()
> #17 /app/vw75fn4ansfpu/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteRepository\Interceptor->Magento\Framework\Interception\{closure}()
> #18 /app/vw75fn4ansfpu/generated/code/Magento/Quote/Model/QuoteRepository/Interceptor.php(41): Magento\Quote\Model\QuoteRepository\Interceptor->___callPlugins()
> #19 /app/vw75fn4ansfpu/vendor/magento/module-quote/Model/QuoteManagement.php(464): Magento\Quote\Model\QuoteRepository\Interceptor->getActiveForCustomer()
> #20 /app/vw75fn4ansfpu/vendor/magento/module-quote/Model/Webapi/ParamOverriderCartId.php(53): Magento\Quote\Model\QuoteManagement->getCartForCustomer()
> #21 /app/vw75fn4ansfpu/generated/code/Magento/Quote/Model/Webapi/ParamOverriderCartId/Proxy.php(95): Magento\Quote\Model\Webapi\ParamOverriderCartId->getOverriddenValue()
> #22 /app/vw75fn4ansfpu/vendor/magento/module-webapi/Controller/Rest/ParamsOverrider.php(64): Magento\Quote\Model\Webapi\ParamOverriderCartId\Proxy->getOverriddenValue()
> #23 /app/vw75fn4ansfpu/vendor/magento/module-webapi/Controller/Rest/InputParamsResolver.php(146): Magento\Webapi\Controller\Rest\ParamsOverrider->override()
> #24 /app/vw75fn4ansfpu/vendor/magento/module-webapi/Controller/Rest/InputParamsResolver.php(115): Magento\Webapi\Controller\Rest\InputParamsResolver->getInputData()
> #25 /app/vw75fn4ansfpu/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest\InputParamsResolver->resolve()
> #26 /app/vw75fn4ansfpu/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\InputParamsResolver\Interceptor->___callParent()
> #27 /app/vw75fn4ansfpu/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\InputParamsResolver\Interceptor->Magento\Framework\Interception\{closure}()
> #28 /app/vw75fn4ansfpu/generated/code/Magento/Webapi/Controller/Rest/InputParamsResolver/Interceptor.php(23): Magento\Webapi\Controller\Rest\InputParamsResolver\Interceptor->___callPlugins()
> #29 /app/vw75fn4ansfpu/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(85): Magento\Webapi\Controller\Rest\InputParamsResolver\Interceptor->resolve()
> #30 /app/vw75fn4ansfpu/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process()
> #31 /app/vw75fn4ansfpu/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch()
> #32 /app/vw75fn4ansfpu/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent()
> #33 /app/vw75fn4ansfpu/vendor/fastly/magento2/Model/FrontControllerPlugin.php(148): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}()
> #34 /app/vw75fn4ansfpu/vendor/magento/framework/Interception/Interceptor.php(135): Fastly\Cdn\Model\FrontControllerPlugin->aroundDispatch()
> #35 /app/vw75fn4ansfpu/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}()
> #36 /app/vw75fn4ansfpu/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins()
> #37 /app/vw75fn4ansfpu/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch()
> #38 /app/vw75fn4ansfpu/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
> #39 /app/vw75fn4ansfpu/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
> #40 {main}

### Steps to reproduce

Access the cart page with bundle items.

### Expected result

Catch the error with a corresponding error message

### Actual result

The exception isn't caught

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-06-05 06:34
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-06-05 06:48
Hi @shakeblue,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reprroducible.

We are able to access the cart page with the bundle products without any issues.

Kindly recheck the issue in Latest 2.4-develop instance and check any third party modules causing this issue.


Thanks.

**Comment by engcom-Bravo** [comment] 2024-06-17 06:04
Hi @shakeblue,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-17 06:04 UTC
Labels: Issue: needs update, Reported on 2.4.3
