### ISSUE TITLE
Magento 2.0.6 : Editing a chosen configurable product from cart should automatically select previously chosen attributes

### ISSUE THREAD

**Issue by micheese** [magento/magento2#4684] opened 2016-05-25 01:26 UTC
## Steps to reproduce
1. Create a configurable product (ex: two colours red and blue)
2. Chose blue product and add it to the cart
3. Edit item from cart (you are redirect to the product page)
## Expected result
1. Blue colour previously choose should be selected by default.
## Actual result
1. None of the attributes are actually selected.

**Comment by pboisvert** [comment] 2016-05-25 05:51
@antboiko i think this may be a duplicate of previously reported issue. If so can you reference original issue and close this one.

**Comment by antboiko** [comment] 2016-05-25 12:48
Hi @michiz05000 , thanks for reporting this issue. We've created internal ticket MAGETWO-53459.

Best,
Anton.

**Comment by antboiko** [comment] 2016-05-25 12:49
https://github.com/magento/magento2/issues/4440

**Comment by kandy** [comment] 2016-06-02 12:35
I cannot reproduce issue in latest mainline and 2.0 branch, so I am closing this issue, as fixed. Feel free to reopen issue if we missed anything.

**Comment by PascalBrouwers** [comment] 2016-06-03 12:48
Also in 2.0.7

**Comment by magento-engcom-team** [comment] 2017-10-13 14:28
@micheese, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Comment by magento-engcom-team** [comment] 2018-08-20 11:05
Hi @micheese

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment] 2018-09-07 11:50
@micheese, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Closed as completed by magento-engcom-team** 2018-09-07 11:50 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Issue: Format is not valid, triage wanted
