### ISSUE TITLE
Product Up Sells and Cross sells grids not keeping selection when grid is refreshed

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#655] opened 2014-09-09 09:09 UTC
When editing in the backend the product upsells and cross-sells of a product and I check the checkbox to set the product as related.  

![before](http://i.imgur.com/1DDV0nQ.png)

Any action I perform that refreshed the grid (change page, change sorting, filtering), the product I selected at the previous step appears unchecked.  
In the hidden input from the grid serializer that holds the selected product the value I just selected is still there.  
Screenshot below is after I change the sorting
![after sorting](http://i.imgur.com/Fsh3ETQ.png)

So I guess the problem is with the initialization of the grid after refresh.

Everything works as expected for the related products grid. 
Version: alpha94.

**Comment by verklov** [comment] 2015-01-12 11:04
@tzyganu, the team could not reproduce this issue. We are closing this ticket now. If you still experience this issue, please provide more details.

**Closed by verklov** 2015-01-12 11:04 UTC
Labels: bug, CS

**Comment by tzyganu** [comment] 2015-01-12 12:35
@verklov. Yes I can still reproduce this. Here are the steps

**Preconditions:**
 - Magento2 beta3 installed
 - Sample data installed

**Steps:**
 - Go to Products->Catalog
 - Edit product `Erika Running Short` (ID: 2046)
 - Click on Upsell Products (the grid that opens should be empty).
 - Select `Any` for the first column filter and fill in `2048` for the ID column search field. Hit Search.  The grid should look like in the image below (I made visible the hidden field that holds the product relation):
![before](http://i.imgur.com/fsV9MjP.png) 
 - Check the checkbox on the grid row
![middle](http://i.imgur.com/VzklvXf.png)
 - Sort products in the grid by any field (Name in this example)

**Expected Result**
 - I should see the same grid sorted by name with the checkbox for the single row checked

**Actual Result**
 - I see the grid sorted by name but the checkbox for the single row is not checked.
![After](http://i.imgur.com/REsKlej.png)

I hope I explained it better this time. The issue reproduces for the Upsells and cross-sells tabs. For the related products tab everything behaves as expected.

**Comment by mprototype** [comment] 2015-01-12 13:50
That's a proper explination.

All The Best,
Joel I. Hart
(m) 720.201.9594
