### ISSUE TITLE
Admin - Filters are not applied on grids after refresh page

### ISSUE THREAD

**Issue by KCzaplinskaAcc** [magento/magento2#34576] opened 2021-11-08 12:51 UTC
### Preconditions (*)
1. Magento 2.4.2-p2
2. It happens only in our environments - not in the local Magento 2.4.2-p2 instance.

### Steps to reproduce (*)
1. Go to the admin panel.
2. Go to Catalog -> Products  (it also can be other pages with grid, like customers, pages, block, etc)
3. Set filter (no matter which filter)
4. Apply the filter.
5. The products show correctly.
6. Go to another page (no matter which pages in the admin panel)
7. Go back to the product listing grid.

### Expected result (*)
1. Filters should be applied in the listing. Products should be filtered, like the screen below.
![productGridFilter1](https://user-images.githubusercontent.com/60093761/140744876-e9e1d641-95f8-4ce3-b78f-6ed197b3fb73.png)

### Actual result (*)
1. Product listing grid is loading faster than filters, which causes that the products are not filtered but above the grid, it shows they are applied. Screen below.
![productGridFilter2](https://user-images.githubusercontent.com/60093761/140744896-6c9e9395-9f8d-4a57-8425-e34c5b7784ee.png)

### Additional info
What I also saw, when on the env I set the filters, and refresh the page (F5) the filters also will not be applied to the products, but if I open the inspector (I wanted to see network connections) and then refresh the page -> filters are applied to the products (but not every time). I check with disable cache option in the inspector, and without it, it does not matter how it is set.

I checked logs but there is nothing related to it.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment] 2021-11-08 12:54
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment] 2021-11-08 14:00
Hi @kczaplinska,
I have reproduced the issue on the below steps:
1. Login Admin > Filter the product throw the SKU
2. Review the CMS (Block & Pages) grid.
3. Again navigate the Product page > The Product grid is showing properly with the proper filter method.
4. After a few minutes, Session is completed and The system is logout.
5. Again Login with the same credentials > Navigate the Catalog > Products.

Actual result:
The filter result is wrong showing.

Expected result:
The filter list should display properly as per applying the filter options.

Screenshot:
https://www.awesomescreenshot.com/image/16349910?key=00a057d56e60afaf3b5ef82418f4a38b

![image](https://user-images.githubusercontent.com/24711761/140754917-cf214c68-930d-47a6-937a-0550ce7ffd04.png)

Thanks.

**Comment by kavingas** [comment] 2021-12-11 03:00
@magento give me 2.4-develop instance

**Comment by MaximGns** [comment] 2021-12-20 09:44
@ajijshekh123 any updates on the progress of this bugfix? Also happening here, a patch would be very handy. Thanks in advance.

**Comment by mgarciaebo** [comment] 2022-03-22 10:46
@magento give me 2.4-develop instance

**Comment by bhargavsynoptek** [comment] 2022-04-07 06:25
I have the same issue in Magento 2.4.3 instance, once apply filter and then refresh the page, the filtered data shows wrong. any update on this issue?

**Comment by pinalmehta** [comment] 2022-05-06 10:07
I am also facing the same issue after upgrading Magento to the 2.4.3 version. when I refresh the page after applying the filter it shows the wrong data.

Please provide a patch or solution.

**Comment by baudeval** [comment] 2022-05-13 09:14
This workaround fix this bug https://github.com/magento/magento2/commit/b22704143f0aaa564755eaaa1ad5645815a43ece

**Comment by pinalmehta** [comment] 2022-05-13 10:05
> This workaround fix this bug [b227041](https://github.com/magento/magento2/commit/b22704143f0aaa564755eaaa1ad5645815a43ece)

yes, this fix worked.thank you so much.

**Comment by bhargavsynoptek** [comment] 2022-05-13 10:07
> 

Great

**Comment by engcom-Bravo** [comment] 2024-08-30 08:00
Hi @KCzaplinskaAcc,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.


<img width="1437" alt="Screenshot 2024-08-30 at 13 29 09" src="https://github.com/user-attachments/assets/0a5e34f8-88e9-4faf-8f40-899b659d5c86">


The filter list should display properly as per applying the filter options.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-08-30 08:00 UTC
Labels: Issue: Confirmed, Component: Admin, Component: Filter, Reproduced on 2.4.x, Priority: P3, Progress: done, Issue: ready for confirmation, Area: Catalog
