### ISSUE TITLE
[Issue] error when generated sitemap.xml with sample-data

### ISSUE THREAD

**Issue by HoaND-Magezon** [magento/magento2#28544] opened 2020-06-05 04:15 UTC
### Preconditions (*)

1. Magento 2.3.5-p2, 2.4.0 with sample data installed(issue reproducible only with sample data)
:warning: **Note**: Issue is not reproducible on 2.4-develop

### Steps to reproduce (*)

1. In the backend, go to Marketing > SEO & Search > Site Map in the admin menu
2. Generate a sitemap.xml

### Expected result (*)

I found this issue when I access link mywebsiteurl/sitemap.xml after generated sitemap.xml via backend. The problem is XML not read HTML entities (IIRC).
![image](https://user-images.githubusercontent.com/59156348/83836431-98f05980-a71d-11ea-9888-f851eeff38ee.png)

### Actual result (*)

I viewed the source code of link /sitemap.xml and went to line 59 and column 361. Of course, I reconstructed codes to be cleaner and easier to view.
![image](https://user-images.githubusercontent.com/59156348/83836441-a1e12b00-a71d-11ea-9a7c-d76ba93b11bf.png)
After that, I found a product with keyworks "Pursuit Lumaflex" and saw this product have a special character in the product title.

And I return an array of products in the module sitemap and sitemap.xml page working well. The issue is sitemap not working with html entities (IIRC) in title and some product in sample data will cause you to encounter this problem.

**Comment by swathishs** [comment] 2020-06-05 07:42
@magento give me 2.4 develop instance

**Comment by magento-engcom-team** [comment] 2020-06-05 07:42
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4 instance for you

**Comment by swathishs** [comment] 2020-06-05 07:46
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-05 07:46
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-06-05 07:48
Hi @swathishs, here is your [Magento instance](https://i-28544-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28544-2-4-develop.instances.magento-community.engineering/admin_821d](https://i-28544-2-4-develop.instances.magento-community.engineering/admin_821d)
Login: `daa0f624` Password: `90db8fcc2776`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment] 2020-06-05 10:49
@HoaND-Magezon: Issue is not reproducible in Magento 2.4 develop instance 

Created Image title  - Simple_product_1

1. **Generate site map**:
![image](https://user-images.githubusercontent.com/58288685/83868201-1c26a500-a748-11ea-8fba-efe9d9c3f533.png)

2. Sitemap.XML:
![image](https://user-images.githubusercontent.com/58288685/83868292-3d879100-a748-11ea-8cc0-f4cee6a75dda.png)

**Comment by swathishs** [comment] 2020-06-08 07:10
@HoaND-Magezon : Issue is not reproducible in Magento 2.4 develop instance 
Please find the attachment below:

1. Product:
![image](https://user-images.githubusercontent.com/58288685/84001887-28e40c80-a985-11ea-8abe-bc9f59407984.png)

2. XML:
![image](https://user-images.githubusercontent.com/58288685/84001908-30a3b100-a985-11ea-95d7-eadf2de5907e.png)

![image](https://user-images.githubusercontent.com/58288685/84001958-45804480-a985-11ea-973b-6a8839c8999d.png)

**Comment by swathishs** [comment] 2020-06-08 07:28
@HoaND-Magezon : Issue is reproducible in Magento 2.3.5-p1 instance
Please find the attachment below:

1**.Product:**
![image](https://user-images.githubusercontent.com/58288685/84003416-a27cfa00-a987-11ea-9bf7-bf91dee6a547.png)

2. **XML:**
![image](https://user-images.githubusercontent.com/58288685/84003481-bcb6d800-a987-11ea-873a-1cf4befb04f1.png)

**Comment by swathishs** [comment] 2020-06-08 07:30
Can be reproduced only on 2.3.5p1 but not on 2.4 develop instance

**Comment by magento-engcom-team** [comment] 2020-06-08 07:31
:white_check_mark: Confirmed by @swathishs 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35010` were created

**Issue Available**: @swathishs, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by HoaND-Magezon** [comment] 2020-06-09 03:15
> @HoaND-Magezon : Issue is reproducible in Magento 2.3.5-p1 instance
> Please find the attachment below:
> 
> 1. **Product:**
>    ![image](https://user-images.githubusercontent.com/58288685/84003416-a27cfa00-a987-11ea-9bf7-bf91dee6a547.png)
> 2. **XML:**
>    ![image](https://user-images.githubusercontent.com/58288685/84003481-bcb6d800-a987-11ea-873a-1cf4befb04f1.png)

Thanks, @swathishs. I removed, renamed all product have &trade; and &reg; in title And now sitemap working fine! :100:

**Comment by sdzhepa** [comment] 2020-08-19 17:28
Priority/Severity changed to P4 S4 due to issue effects and can be reproduced on with sample data

**Comment by brosenberger** [comment] 2020-10-08 05:39
@HoaND-Magezon you can fix your problem when you change following lines (576, 578 for escaping the &trade; correctly for xml and additionally possibly change 584 from escapeHtml to escapeHtmlAttr):
![image](https://user-images.githubusercontent.com/2969243/95419139-43c98c00-0939-11eb-85c8-9aba5664184b.png)

**Closed as completed** 2020-10-20 11:57 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Sitemap, Severity: S4, Priority: P4, Reproduced on 2.3.5p1, Progress: done, Reported on 2.3.5-p2

**Comment by sdzhepa** [comment] 2020-11-04 18:23
The related internal Jira ticket `MC-35010` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem on the latest `2.4-develop` please create new Issue with updated information/steps/preconditions in the **_Description section_**.
