### ISSUE TITLE
Upgrading Magento 2

### ISSUE THREAD

**Issue by dervishm96** [magento/magento2#23289] opened 2019-06-17 14:20 UTC
### Preconditions (*)

1. Magento 2.3.0
2.

### Steps to reproduce (*)

1. Access web setup wizard page
2. Try to upgrade magento to 2.3.1

### Expected result (*)

1. The upgrade should begin to process
2.

### Actual result (*)

1. Instead, I get the following error:
2. "we cannot retrieve information on magento/product-community-edition."

**Comment by magento-engcom-team** [comment] 2019-06-18 11:36
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17569` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2020-11-30 20:39
Hi @dervishm96. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-23761` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Closed as completed** 2020-11-30 20:38 UTC
Labels: Component: Setup, Issue: Confirmed, Reproduced on 2.3.x, Issue:  Cannot Reproduce, Progress: done
