### ISSUE TITLE
After the update from 2.3.5-p1 to 2.4.5 the store switcher no longer works

### ISSUE THREAD

**Issue by stradd** [magento/magento2#36195] opened 2022-09-24 17:01 UTC
### Preconditions and environment

2.4.5

### Steps to reproduce

composer require magento/product-community-edition  --no-update
composer update
php bin/magento setup:upgrade && rm -rf pub/static/* && rm -rf var/view_preprocessed/* && php bin/magento setup:di:compile && php bin/magento setup:static-content:deploy && php bin/magento indexer:reindex && php bin/magento cache:clean && php bin/magento cache:flush

### Expected result

redirect to second language via store switcher possible

### Actual result

Base url will be called

### Additional information

I use two url 
example.de 
example.com
and two languages German and English.

Before the update, you could easily switch from one language to the other using the store switcher. After the update, the page remains on the base url when you click on the second language.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-09-30 05:07
Hi @stradd ,
Thank you for reporting and collaboration. Verified the issue on both Magento 2.4-develop instance and by upgrading from 2.3.5-p1 to 2.4.5 project-community-edition but unable to reproduce the issue.
**Steps performed:**
1. Installed German Language package and changed the admin configuration locale options to Germany.
2. Cleared cache
3. Upgraded to Magento 2.4.5. Ref [Upgrade Guide](https://experienceleague.adobe.com/docs/commerce-4. operations/upgrade-guide/implementation/perform-upgrade.html)
5. Accessed Store front - User is able to select both the locale options (English and Germany)
![image](https://user-images.githubusercontent.com/60198231/193194489-b0d36dd6-242a-4989-9852-ef32116b39db.png)

Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue. Please provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-10-14 09:19
Hi @stradd ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-10-14 09:19 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.5
