### ISSUE TITLE
Magento 2.1.1 Problem with change currency

### ISSUE THREAD

**Issue by Omar-Oleh** [magento/magento2#6746] opened 2016-09-25 20:08 UTC
**Preconditions**
Magento 2.1.1
Created two currencies (United Arab Emirates Dirham and Qatari Rial)
Cache is enabled

**Steps to reproduce**
Open category page on frontend
Change currency

**Expected result**
Currency is changed on product listing 

**Actual result**
Currency do not changed. Problem with FPC(I have refreshed FPC, the currency is work fine. But if I changed currency one more, it is do not working)

**Comment by SerhiyShkolyarenko** [comment] 2016-09-28 14:10
@Omar-Oleh have you created currency rates?
What is base currency for your store?

**Comment by SerhiyShkolyarenko** [comment] 2016-09-28 14:45
@Omar-Oleh reproduced. Answers to that questions are not necessary. Thank you for reporting issue!

**Comment by SerhiyShkolyarenko** [comment] 2016-09-30 08:10
Our internal issue is MAGETWO-59089.

**Comment by eldonbite** [comment] 2016-10-07 08:05
We're experiencing the same when switching between GBP and JPY currencies:

![image](https://cloud.githubusercontent.com/assets/3441674/19182657/f246e0ac-8ca6-11e6-9c14-3b8c3d52a1d3.png)

![image](https://cloud.githubusercontent.com/assets/3441674/19182743/6b8e072e-8ca7-11e6-9ce2-cbada5501184.png)

Some workarounds that I know of to prevent this issue from occurring is to:
1. Disable the block cache (BLOCK_HTML)
2. Edit Magento\Framework\Pricing\Render\PriceBox and either:
   - set the DEFAULT_LIFETIME to 0, or
   - just force getCacheLifetime to return 0

I tried writing an extension to override this behaviour, to no avail (I might be doing something wrong LOL). But it still doesn't solve the root cause of the problem.

**Comment by SerhiyShkolyarenko** [comment] 2016-10-28 09:48
Fix is delivered to mainline. Closing the issue.

**Closed as completed by SerhiyShkolyarenko** 2016-10-28 09:48 UTC
Labels: Issue: Ready for Work, bug report, Component: Framework/Cache

**Comment by Ctucker9233** [comment] 2016-11-01 00:08
@SerhiyShkolyarenko is there a commit reference?

**Comment by SerhiyShkolyarenko** [comment] 2016-11-01 09:38
There we six commits for this issue: 8ec49df, 027491e, be4d557, 0d0e683, b1066bf, e908e6c

**Comment by eldonbite** [comment] 2016-11-04 03:10
Hi @SerhiyShkolyarenko,

Noticed another issue when selecting product variants using the swatches.
1. GBP:
   ![image](https://cloud.githubusercontent.com/assets/3441674/19993278/53c6b85a-a27f-11e6-867b-902e3df6d2ca.png)
2. Select a product variant while in GBP:
   ![image](https://cloud.githubusercontent.com/assets/3441674/19993300/761e35e0-a27f-11e6-8c50-2c7b1766129c.png)
3. Then, switch currency to JPY:
   ![image](https://cloud.githubusercontent.com/assets/3441674/19993217/f36f9ee0-a27e-11e6-80fe-fb6c1e3abfec.png)
4. Upon selecting a product variant, the price reverts back to the GBP amount but with JPY currency symbol:
   ![image](https://cloud.githubusercontent.com/assets/3441674/19993264/38cdbe5e-a27f-11e6-874b-7de9493c42b0.png)

**Comment by SerhiyShkolyarenko** [comment] 2016-11-04 09:33
@eldonbite thank you for the notice.
It looks like a different issue. Could you please create a separate issue for it?

**Comment by eldonbite** [comment] 2016-11-09 03:01
Hi @SerhiyShkolyarenko,

I created an issue for the problem described above:

#7371 Wrong price upon selecting product options after switching currency 

Thanks and regards,
Eldon

**Comment by SerhiyShkolyarenko** [comment] 2016-11-09 16:15
thanks @eldonbite!

**Comment by duytrinhit** [comment] 2017-03-30 05:58
Hi @eldonbite @Omar-Oleh @Ctucker9233 
I have created a small cript to override FinalPriceBox Block
Now the problem is resolved. Please try my code in below link
[https://github.com/duytrinhit/magento2/tree/master/app/code/Balance/Catalog](https://github.com/duytrinhit/magento2/tree/master/app/code/Balance/Catalog)

**Comment by korostii** [comment] 2017-06-06 07:14
@SerhiyShkolyarenko, could you please reopen this until the fix is delivered into a release? Thanks in advance.

The issue is clearly reported for 2.1.x. It is only reasonable to expect this fix in a 2.1.x release before closing the issue.

**Comment by yosefkurniawan** [comment] 2017-06-30 05:58
is this issue solved?

**Comment by magento-team** [comment] 2017-07-31 23:02
Internal ticket to track issue progress: MAGETWO-69665

**Comment by techspot** [comment] 2018-06-14 16:03
**THIS SOLUTION WORK FOR ME:** First i need select the country of the currency that i need, in  Store Configuration > General > Store Information > Country

After i can change the currency in Currency Configuration
