### ISSUE TITLE
Date of Birth attribute gets weird format on page reload

### ISSUE THREAD

**Issue by killoff** [magento/magento2#7778] opened 2016-12-13 14:20 UTC
### Preconditions
DOB attribute is optional or required in Stores Configuration

### Steps to reproduce
1. Go to customer registration form, fill in all fields, DOB as well (10.12.2016)
Enter existing customer email in order to get an error.
2. Submit form

### Expected result
Date 10.12.2016 preserved on the form as DOB 

### Actual result
Date 10..0000000 preserved on the form as DOB
![](http://i.imgur.com/iStW3JC.png)

PS. smth wrong with Magento\Framework\Data\Form\Filter\Date::outputFilter()

```
...
        $filterInternal = new \Zend_Filter_NormalizedToLocalized(
            ['date_format' => $this->_dateFormat, 'locale' => $this->localeResolver->getLocale()]
        );

        $value = $filterInput->filter($value);
        $value = $filterInternal->filter($value);  // shit happens here
...
```

**Comment by vil11** [comment] 2016-12-13 14:44
@killoff 
thanks for reporting this issue! Internal number **MAGETWO-62181**.

---
dvilchynskyi, M2 QA

**Comment by JacobDrummond** [comment] 2016-12-14 08:03
@vil11, related to #6323 ?

**Comment by vil11** [comment] 2016-12-14 15:34
Probably the cause is similar, but #6323 is fixed while this one is still can be reproduced.

**Comment by magento-engcom-team** [comment] 2017-10-03 11:30
@killoff, thank you for your report.
We've created internal ticket(s) MAGETWO-62181 to track progress on the issue.

**Comment by nemesis-back** [comment] 2017-10-24 09:58
I'm working on it #SQUASHTOBERFEST

**Comment by okorshenko** [comment] 2017-10-24 16:16
Hi @nemesis-back could you please accept the invite in the GitHub?

**Comment by nemesis-back** [comment] 2017-10-24 16:22
@okorshenko accepted, thx

**Comment by kanduvisla** [comment] 2018-07-05 15:02
Although #11721 status that this issue is fixed in 2.2 (haven't tested this yet), I temporarily fixed this in a Magento 2.1 shop by adding an interceptor before `\Magento\Customer\Block\Widget\Dob::setDate()`:

    public function __construct(
        \Magento\Framework\Stdlib\DateTime\TimezoneInterface $timezone
    ) {
        $this->timezone = $timezone;
    }

    public function beforeSetDate(\Magento\Customer\Block\Widget\Dob $subject, $date)
    {
        // Reformat the time from frontend locale (nl_BE) to system locale (YYYY-MM-DD)
        return [$this->timezone->date($date)->format('Y-m-d')];
    }

Hope this helps someone.

**Comment by arnoudhgz** [comment] 2018-08-05 12:26
Tested the current 2.2-develop branch, seems solved with this PR: https://github.com/magento/magento2/pull/15272 

It is part of the 2.2.6 Milestone.

Thanks to @KaushikChavda  for creating the PR!!

@magento-engcom-team  I think this issue can be closed.

**Comment by sdzhepa** [comment] 2019-05-01 22:43
According to comments 

- https://github.com/magento/magento2/issues/7778#issuecomment-402752458
- https://github.com/magento/magento2/issues/7778#issuecomment-410516897

Issue has been fixed

**Closed as completed by sdzhepa** 2019-05-01 22:43 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid
