### ISSUE TITLE
[GraphQL]  Internal server error is returned for giftRegistryTypeSearch

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#31531] opened 2021-01-04 19:34 UTC
Create a gift registry with shipping address with region. Notice that the GiftRegistryOutput has region returned as null.

!createGiftRegistryOuput*address_Null*region.png|thumbnail!

 
#### Expected Result :

 When a Gift Registry is created, with a shipping address containing region( region*id, region*code etc..), the output should return the address data with region.

**Comment by magento-engcom-team** [comment] 2021-01-04 19:34
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-40120

**Comment by mauragcyrus** [comment] 2021-01-14 18:36
There are currently 2 PRs open for this issue: 
https://github.com/magento/partners-magento2ee/pull/425

**Comment by eduard13** [comment] 2021-01-18 13:41
For some reasons I'm not able to reproduce this one. Checking the description's query, I find it weird that `typeUid = 1`, even we have a **String** type for `typeUid`. Most probably it has been fixed in one of the commits.

**Comment by dthampy** [comment] 2021-01-19 22:58
@eduard13 , this issue has been fixed in the scope of [this PR](magento/partners-magento2ee#438). I confirmed it locally that the error is no longer returned for the query.

**Closed as completed** 2021-02-16 23:12 UTC
Labels: Priority: P1, Severity: S1, Project: GraphQL, PAP, Progress: done
