### ISSUE TITLE
Guest checkout is not there (Magento 2.1.1)

### ISSUE THREAD

**Issue by flipflap** [magento/magento2#7007] opened 2016-10-14 08:24 UTC
### Preconditions

1. Magento 2.1.1
2. Config > Sales > Checkout > Allow Guest Checkout is Yes
### Steps to reproduce

1. Check out without login as guest
### Expected result

1. Shipping address shoud appear, but login field shows up. No way to continue as guest.
### Actual result

1. 
   ![image](https://cloud.githubusercontent.com/assets/6672673/19380639/5d12eaf6-91f8-11e6-992c-71bf9eb6eb2d.png)

**Comment by shanevbg** [comment] 2016-10-14 11:52
I think this might be fixed in 2.1.2, I just went in and even though I used an already existing email address I was given the option to check out as guest.
I did find that anything that tries to optimize javascript outside of Magento itself seems to cause problems at checkout.

**Comment by veloraven** [comment] 2016-10-18 09:25
@flipflap thank you for your feedback.
It seems to be an issue of custom theme or some external extension.
Guest can easily make a order on clear Magento with Luma theme: there is no 'Password' field in this case.
If you think it to be a Magento issue anyway, please provide exact detailed steps you do and explain your position.

**Comment by veloraven** [comment] 2016-11-02 12:41
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Closed as completed by veloraven** 2016-11-02 12:41 UTC
Labels: Progress: needs update
