### ISSUE TITLE
checkout Summary issue

### ISSUE THREAD

**Issue by saifalitapawala** [magento/magento2#7046] opened 2016-10-17 07:12 UTC
magento version 2.1.2

![checkout_summary](https://cloud.githubusercontent.com/assets/22881238/19428281/d4a251d6-9466-11e6-8a19-fd5fb02e4346.png)

step:-

```
1) login as customer, navigate to Account Dashboard;
2) On any existing order item, click "Reorder" button;
3) On checkout page click "proceed-to-checkout" button.
```

Please provide any solution

**Comment by kociiide** [comment] 2016-10-17 10:38
This issue is present in both 2.1.0, 2.1.1 and 2.1.2.

The issue does not happen if you directly click checkout.

This error only occurs when you view and edit cart and then checkout.

The error is directly linked between the customers number of address lines.

**I really wish the Magento dev team would find the cause and fix this issue, it has been well documented over the last month on Github but it appears that they have chosen to ignore it in there last 2 releases.**

There is a temporary fix but it causes problems of its own,

**Comment by odubovyk** [comment] 2016-10-26 13:24
Thank you for the ticket.
We had internal ticket MAGETWO-58614 on this. 
It was fixed and delivered https://github.com/magento/magento2ce/pull/422
I'm closing this ticket

**Closed as completed** 2016-10-26 13:32 UTC
Labels: Issue: Ready for Work, bug report, Component: Checkout

**Comment by Ctucker9233** [comment] 2016-10-29 23:21
@odubovyk the link for the fix throws a 404 error.
