### ISSUE TITLE
Not able to translate page layout head titles

### ISSUE THREAD

**Issue by basselalaraaj** [magento/magento2#6337] opened 2016-08-25 12:14 UTC
1.  Magento 2.1.0
2. Php 7.0 and mysql 5.6
### Steps to reproduce
1. open file vendor/magento/module-contact/view/frontend/layout/contact_index_index.xml
2. there is a tag <title>Contact Us</title>
3. try to translate Contact Us, by adding the translation to a translation file.
### Expected result
1. Contact Us title on the contact page will become a different translated string.
### Actual result
1. Contact Us title on the contact page stays Contact Us.

**Comment by sevos1984** [comment] 2016-08-29 16:15
Hi! I can't reproduce it. Did you added your translation to app\code\Magento\Contact\i18n\en_US.csv and cleared cache after it?

**Comment by basselalaraaj** [comment] 2016-08-30 09:57
@sevos1984  yes!
i copied the key from vendor/magento/module-contact/view/frontend/layout/contact_index_index.xml

`<head>
        <title>Contact Us</title>
    </head>`

**Comment by sevos1984** [comment] 2016-08-30 13:17
What locale do you use? Can you give me your app\code\Magento\Contact\i18n\%your_locale%.csv file?

**Comment by basselalaraaj** [comment] 2016-08-30 14:05
@sevos1984 nl_NL this local is also defined in the store that i am using in the config.

**Comment by sevos1984** [comment] 2016-08-31 07:57
You should have '"Contact Us", "%translation%"' in app\code\Magento\Contact\i18n\nl_NL.csv and Dutch (Netherlands) set in Configuration>General>Locale. Do you have these settings?

**Comment by basselalaraaj** [comment] 2016-08-31 09:30
@sevos1984 yes!

**Comment by sevos1984** [comment] 2016-09-05 13:08
Try clearing cache and check your magento logs for errors.

**Comment by OwenRay** [comment] 2016-09-15 14:54
Same problem here, All titles set in xml under page->head->title are not translated.

**Comment by basselalaraaj** [comment] 2016-09-16 08:10
@sevos1984 i cleared my cache and checked magento logs for error, i still can reproduce it.

**Comment by sevos1984** [comment] 2016-09-19 14:56
Have you generated you static files?

**Comment by basselalaraaj** [comment] 2016-09-19 16:46
yes, in production mode static deployment. @sevos1984

**Comment by sevos1984** [comment] 2016-09-26 12:25
I mean regenerating static files after applying translation. And before that have you used bin/magento i18n:pack to add translations?

**Comment by pitangaweb** [comment] 2016-10-03 04:56
I can confirm that I'm not able to translate contact page and checkout success page titles. I put the translations in app\code\Magento\Contact\i18n\fr_FR.csv and app\code\Magento\Checkout\i18n\fr_FR.csv, regenerated static files, but it does not help.

**Comment by basselalaraaj** [comment] 2016-10-03 06:59
@sevos1984 i did that, still not translatable.

**Comment by sevos1984** [comment] 2016-10-04 07:51
This should be fixed in latest develop branch commit https://github.com/magento/magento2/commit/14028aad37ee7435d89eb3b647e6d03ecd8e2e13. Patch will be soon delivered into 2.1 branch. If that doesn't help please create a new ticket.

**Closed as completed by sevos1984** 2016-10-04 07:51 UTC
Labels: Issue: Ready for Work, bug report, Progress: needs update, Component: Translation

**Comment by miguelbalparda** [comment] 2017-06-20 15:05
#9992 is in the process of being merged, any chance you could test the patch? Thanks!

**Comment by magento-team** [comment] 2017-07-31 23:01
Internal ticket to track issue progress: MAGETWO-70010

**Comment by shankar2004nag** [comment] 2019-10-18 11:13
Unable to translate Contact us page via app/i18n/vendorname/en_US/en_US.csv
