### ISSUE TITLE
UPS XML type shipping log missing even debug is enable

### ISSUE THREAD

**Issue by Bhavik-kumar** [magento/magento2#34091] opened 2021-09-16 08:01 UTC
UPS shipping method with XML Type, 
missing shipping request and response debug on shipping.log
### Preconditions (*)
1. Version 2.4.*
2. UPS shipping method be Enable
3. UPS type: United Parcel Service XML
4. Debug: yes

### Steps to reproduce (*)
1. Add any products to cart
2. Go to shipping page
3. Make sure you can able to view any UPS shipping method 

### Expected result (*)
1. shipping.log should mark Request and Response data

### Actual result (*)
1. shipping.log not trigger any Request and Response data

**Comment by engcom-November** [comment] 2021-09-16 08:42
Hi @Bhavik-kumar ,
We are closing this issue as this is the duplicate of https://github.com/magento/magento2/issues/32361.
Please move into this ticket for latest updates on the same.
Thank you.

**Closed as completed by engcom-November** 2021-09-16 08:42 UTC
Labels: duplicate, Issue: ready for confirmation
