### ISSUE TITLE
Magento Community Edition: Version 2.4.5 - Import Status Showing Wrong Count

### ISSUE THREAD

**Issue by RocktechnolabsDev** [magento/magento2#36472] opened 2022-11-14 11:38 UTC
### Preconditions and environment

- Magento version: 2.4.5
- I am using Magento Community Version 2.4.5, Importing the customers, CSV have 1708 records including the Header.
- Validate the data, Validation result shows: Checked rows: 1707, checked entities: 1707, invalid rows: 0, total errors: 0
- Click on Import button: Import status shows: Created: 0, Updated: 7, Deleted: 0
- It's shown last bunch records count only.
- There is no issue in Customer Creation.
- Showing error records above 100

### Steps to reproduce

1. Login into admin > System > Data Transfer > Import, Select "Customer Main File" from entity type drop down.

2. Select "Add/Update Complex Data" option from Import Behaviour drop down.

3. Rest of fields leave as it is.

3. Upload prepared csv for import the customer

4. Click on check data, CSV data validation success, Validation result says: Checked rows: 1707, checked entities: 1707, invalid rows: 0, total errors: 0

5. While click on import button, Showing status: "Created: 0, Updated: 7, Deleted: 0", "Import successfully done" message. but Updated count show 7 which is from last bunch of import data.

Please check attached screenshot

![Screenshot from 2022-11-14 16-49-24](https://user-images.githubusercontent.com/118173578/201650119-32227a0c-b102-4305-811f-6ae90c43865e.png)
![Untitled](https://user-images.githubusercontent.com/118173578/201650128-55cd77bc-2d74-4a2c-aea6-0987e552a65b.png)

### Expected result

Created: 0, Updated: 1707, Deleted: 0

### Actual result

Created: 0, Updated: 7, Deleted: 0

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-11-15 06:37
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-15 10:18
Hi @UtsavRock1811,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

1.Login into admin > System > Data Transfer > Import, Select "Customer Main File" from entity type drop down.

2.Select "Add/Update Complex Data" option from Import Behaviour drop down.

3.Rest of fields leave as it is.

4.Upload prepared csv for import the customer


<img width="788" alt="Screenshot 2022-11-15 at 2 43 42 PM" src="https://user-images.githubusercontent.com/51680745/201893611-700d68f5-ab6f-4d6e-8372-2e5302f37ba2.png">



<img width="732" alt="Screenshot 2022-11-15 at 2 48 07 PM" src="https://user-images.githubusercontent.com/51680745/201893633-4bf11350-47e4-4e57-a67a-da294486cd8c.png">



Kindly Provide your CSV file.


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by UtsavRock1811** [comment] 2022-11-15 11:23
Hi @engcom-Bravo,

Can you please check with more then the 100 records please? As magento divide the CSV data in bunch of 100 limit, So while you import the data more then the 100 count, You are able to reproduce the issue. 

Also please find attachment of CSV file.
[customer.csv](https://github.com/magento/magento2/files/10012130/customer.csv)

Thank you

**Comment by engcom-Bravo** [comment] 2022-11-16 06:12
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-16 10:49
Hi @UtsavRock1811,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance.As per steps to reproduce issue is reproducible, but can you please confirm in your case customers are created or not (i.e.108).We are able to create the customers(108) as per your CSV file.Kindly refer the screenshots.
There is no issue in creating customers and the issue is in import status.


Before importing we have 1 Customer.



<img width="848" alt="Screenshot 2022-11-16 at 12 07 24 PM" src="https://user-images.githubusercontent.com/51680745/202159950-138cb12a-2471-49f7-8818-d30e75a768ff.png">


<img width="1069" alt="Screenshot 2022-11-16 at 11 53 05 AM" src="https://user-images.githubusercontent.com/51680745/202160060-9458a03f-81c7-4d8f-a0c7-819cd975995a.png">







<img width="859" alt="Screenshot 2022-11-16 at 1 28 59 PM" src="https://user-images.githubusercontent.com/51680745/202160135-8b10573b-e766-405d-b0fb-739965872218.png">


After Importing we have 109 Customers.




<img width="736" alt="Screenshot 2022-11-16 at 12 09 20 PM" src="https://user-images.githubusercontent.com/51680745/202160173-fcfe8d2d-e948-4e0c-afe4-393ca0736746.png">



Thanks.

**Comment by UtsavRock1811** [comment] 2022-11-16 11:03
Hi @engcom-Bravo,

For your information customer create/update action is working fine, Just having issue in import status summary.

Thanks.

**Comment by engcom-Bravo** [comment] 2022-11-17 06:46
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-17 07:41
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-17 10:41
Hi @UtsavRock1811,

Thanks for your Update.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.

**Steps to reproduce**


1.Login into admin > System > Data Transfer > Import, Select "Customer Main File" from entity type drop down.

2.Select "Add/Update Complex Data" option from Import Behaviour drop down.

3.Rest of fields leave as it is.

4.Upload prepared csv for import the customer


We have used below CSV file to import customer records.we are able to create the customers but error in after importing the file in import status count.

[1736.csv](https://github.com/magento/magento2/files/10030581/1736.csv)




<img width="1069" alt="Screenshot 2022-11-16 at 11 53 05 AM" src="https://user-images.githubusercontent.com/51680745/202424594-2e89a8e5-9632-4d76-950e-a8d85f038f32.png">










<img width="859" alt="Screenshot 2022-11-16 at 1 28 59 PM" src="https://user-images.githubusercontent.com/51680745/202424202-11e7b691-ec77-41b5-8c77-4e6a2bb70180.png">




Hence confirming the issue.

Thanks.

**Comment by Vasudev-22** [comment] 2022-11-18 10:50
@magento I am working on this

**Comment by Vasudev-22** [comment] 2022-11-18 10:54
@magento I am working on this

**Comment by hostep** [comment] 2023-01-10 20:28
Looks to be fixed in https://github.com/magento/magento2/commit/e4b7b7c8c8287c3002ba12fb44df27f962984503

**Closed as completed** 2024-09-30 06:14 UTC
Labels: Component: ImportExport, Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Account, Reported on 2.4.5
