### ISSUE TITLE
Configurable Product create issue while using custom source model attribute

### ISSUE THREAD

**Issue by patelnimesh1988** [magento/magento2#24067] opened 2019-08-08 12:52 UTC
### Preconditions (*)

1. Magento 2.2.4 to Magento 2.3.2
2. Ubuntu 16.04
3. Php 7.0, Php 7.1 and Php 7.2

### Steps to reproduce (*)

1. Create product attribute using Custom source model
2. Create configurable product using above attribute
3. Magento should be in developer mode.

### Expected result (*)

1. Save product without error 
    [OR]
2. Open configurable product  view without any error in admin
    [OR]
3. Configurable product open with assigned created sub products

### Actual result (*)

1. Notice: Undefined offset: 0 in <root>/vendor/magento/module-configurable-product/Model/Product/Type/VariationMatrix.php on line 43
![configrable-product-error](https://user-images.githubusercontent.com/6728907/62704841-e884cc80-ba09-11e9-90a0-fc5eba11e3be.png)
2. Face above issue while open created configurable product view page
3. If product view page open then we click on Configuration > Add Products Manually then popup not open.

**Comment by engcom-Charlie** [comment] 2019-08-09 08:00
Hello @patelnimesh1988 
I can't reproduce this issue on fresh Magento 2.3-develop.

**Manual testing scenario:**
Magento in developer mode.
1. Create product attribute using Custom source model
 ![image](https://user-images.githubusercontent.com/51680850/62763375-0eef4a00-ba94-11e9-8acc-e7c43092508f.png)
2. Create configurable product using above attribute
3. Save the product 

**Actual result:**
Product saved without Notice:
![image](https://user-images.githubusercontent.com/51680850/62763506-655c8880-ba94-11e9-908a-913fb8d4a57a.png)
Open configurable product view without any error in admin.
Configurable product open with assigned created sub products.
And i can add product manually.
So i have to close this issue.
Thank for your report!

**Closed as completed by engcom-Charlie** 2019-08-09 08:00 UTC
Labels: Issue: Format is valid, Component: ConfigurableProduct

**Comment by patelnimesh1988** [comment] 2019-08-09 08:19
Did you check in Magento 2.2.4?

**Comment by engcom-Charlie** [comment] 2019-08-09 08:46
@patelnimesh1988 branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details
