### ISSUE TITLE
Error when placing Order: main.CRITICAL: Saving order 00000000X failed: Notice: iconv(): Detected an incomplete multibyte character in input string in vendor/magento/module-eav/Model/Attribute/Data/Text.php on line 190

### ISSUE THREAD

**Issue by aymen-hajji** [magento/magento2#38404] opened 2024-02-01 10:16 UTC
### Preconditions and environment

- 2.4.6-p3
- Error doesn't occure on every order

### Steps to reproduce

Shop was updated a few weeks ago. May be some customer data wasn´t correct and now they get checked stricter. That´s why some customer can't place order

### Expected result

Order is placed successfully

### Actual result

Error: A server error stopped your order from being placed. Please try to place your order again.

### Additional information

fixed by disabling notice in app/bootstrap.php: error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED );

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-02-02 06:41
Hi @aymen-hajji,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

![Screenshot from 2024-02-02 12-09-05](https://github.com/magento/magento2/assets/51680745/ebb9cd7d-c401-4075-b4d8-fbcdcccf4287)


We are able to place the order successfully.

Kindly check the issue in Magento 2.4-develop instance if any third party causing the issue and also kindly provide more information if possible please provide screenshots or screencast to proceed further.

Thanks.

**Comment by magewallet** [comment] 2024-02-16 07:07
I am also getting this error while try to placing order.

Notice: iconv(): Detected an incomplete multibyte character in input string in /vendor/magento/module-eav/Model/Attribute/Data/Text.php on line 190

Any solution ?

**Comment by hans2103** [comment] 2024-02-17 19:23
> I am also getting this error while try to placing order.
> 
> Notice: iconv(): Detected an incomplete multibyte character in input string in /vendor/magento/module-eav/Model/Attribute/Data/Text.php on line 190
> 
> Any solution ?

Have you seen https://github.com/magento/magento2/issues/37326 ?

**Comment by engcom-Bravo** [comment] 2024-02-22 07:18
@hans2103 Thanks for your contribution.

Hi @magewallet,

Thanks for your update.

Could you please check this solution https://github.com/magento/magento2/issues/37326#issuecomment-1502234388 it may resolves the issue.

We have verified the issue in Latest Magento 2.4-develop instance and the issue is not reproducible.Please check the issue in Latest Magento 2.4-develop instance and check if any third party modules causing the issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-02-26 05:48
Hi @aymen-hajji,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Bravo** 2024-02-26 05:48 UTC
Labels: Issue: needs update, Reported on 2.4.6-p3

**Comment by hostep** [comment] 2024-02-26 13:18
For the people running into this, it was fixed by https://github.com/magento/magento2/commit/eb34e3477994257e0601bd1a92a04f92152c1919

**Comment by sergei-sss** [comment] 2024-11-04 12:21
2.4.6-p8... We still use the fix from eb34e34... Is there any way to reopen the damn issue?

**Comment by danieluniform** [comment] 2024-12-04 23:48
> 2.4.6-p8... We still use the fix from [eb34e34](https://github.com/magento/magento2/commit/eb34e3477994257e0601bd1a92a04f92152c1919)... Is there any way to reopen the damn issue?

Agreed - this issue is still open. This issue is being closed too quickly because they were unable to reproduce the issue (Which is complicated to setup - does not mean that the issue doesn't exist!!)

**Comment by hostep** [comment] 2025-04-09 05:23
Guys, there's no reason to re-open the ticket if there is already a fix, the fix is included in Magento 2.4.7 and 2.4.8, so either upgrade to those versions, or turn the eb34e3477994257e0601bd1a92a04f92152c1919 into a patch and apply it to your shops.

**Comment by hostep** [comment] 2025-04-09 09:25
Sure, then please open an issue on https://github.com/magento/quality-patches/ and ask them to make an official patch to fix this issue for Magento 2.4.6
