### ISSUE TITLE
Coupon not marked as used when used to apply free shipping

### ISSUE THREAD

**Issue by danslo** [magento/magento2#5450] opened 2016-07-04 15:34 UTC
## Steps to reproduce
1. Install Magento from develop branch.
2. Go to Marketing > Cart Price Rules
3. Create a new rule with a Coupon
4. Set Uses per Coupon to '1'.
5. Enable 'Use Auto Generation'.
6. Under 'Actions', enable free shipping.
7. Go through normal checkout process and submit an order.
## Expected result
1. The coupon code is marked as used.
2. The number of times used is increased.

<img src="http://i.imgur.com/hPOpvCB.png" />
## Actual result
1. Used is "No"
2. Times used is "0".

This bug also exists in Magento 1.9.2.4.

**Comment by danslo** [comment] 2016-07-05 07:06
The reason for this is the following part of SalesRule observer:

``` diff
diff --git app/code/Magento/SalesRule/Observer/SalesOrderAfterPlaceObserver.php app/code/Magento/SalesRule/Observer/SalesOrderAfterPlaceObserver.php
index e352ede..c102cd0 100644
--- app/code/Magento/SalesRule/Observer/SalesOrderAfterPlaceObserver.php
+++ app/code/Magento/SalesRule/Observer/SalesOrderAfterPlaceObserver.php
@@ -57,7 +57,7 @@ class SalesOrderAfterPlaceObserver implements ObserverInterface
     {
         $order = $observer->getEvent()->getOrder();

-        if (!$order || $order->getDiscountAmount() == 0) {
+        if (!$order) {
             return $this;
         }
```

In my view, an applied coupon code is used, regardless of whether or not a discount was placed on the main order, since it can apply to other things (like free shipping). Is there a specific reason for checking discount amount?

**Comment by tkacheva** [comment] 2016-07-14 13:12
@danslo  thanks for reporting the issue.

MAGETWO-55396

**Comment by pboisvert** [comment] 2016-09-21 15:34
thanks @danslo for spotting the duplicates  closing as a duplicate of #3506

**Closed as completed by pboisvert** 2016-09-21 15:34 UTC
Labels: Issue: Ready for Work, bug report, Component: Tax
