### ISSUE TITLE
First line of theme translation file is ignored for some languages

### ISSUE THREAD

**Issue by denistrator** [magento/magento2#16490] opened 2018-07-02 20:02 UTC
### Summary
First line of theme translation file (app/design/frontend/Vendor/Theme/i18n/xx_XX.csv) is ignored for some languages. Tested for `en_US`, `he_IL`, `fr_BE` and `ru_RU`. `en_US` works as expected, but `he_IL`, `fr_BE` and `ru_RU` don't.

### Preconditions

1. Magento 2.2.4

### Steps to reproduce

1. Create FE theme with `he_IL` (Hebrew) locale. Apply it
2. Create `i18n/he_IL.csv` translation file in theme you created
3. Add translation in the file you created. For example:
`"Add to Wish List","TEST he_IL Add to Wish List TEST"`
`"Add to Compare","TEST he_IL Add to Compare TEST"`
4. Open any product page

### Expected result

1. All the phrases from `i18n/xx_XX.csv` are translated 

### Actual result

1.  All the phrases from `i18n/xx_XX.csv` __except first one__ are translated 

### Additional info
See .csv files and FE product page screenshots for:
[en_US](https://user-images.githubusercontent.com/21016905/42183812-dec35644-7e4b-11e8-94e1-7c8979fc9338.png)
[he_IL](https://user-images.githubusercontent.com/21016905/42183818-e5cad30e-7e4b-11e8-8f12-c22515256e81.png)
[fr_BE](https://user-images.githubusercontent.com/21016905/42183828-eb5ffa74-7e4b-11e8-91c3-dca4e57abebb.png)

**Comment by magento-engcom-team** [comment] 2018-07-02 20:02
Hi @denistrator. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@denistrator do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment] 2018-07-03 07:17
@denistrator, thank you for your report. Unfortunately I'm not able to reproduce this issue with given steps:
![fr_fr](https://user-images.githubusercontent.com/40755810/42204365-296149fa-7eaa-11e8-9430-1a025cb99e6a.png)
![he_il](https://user-images.githubusercontent.com/40755810/42204371-2d6210ac-7eaa-11e8-81ee-667b3264e9f5.png)
Can you please provide more details?

**Comment by denistrator** [comment] 2018-07-03 09:12
@engcom-backlog-nickolas did you test it on Magento 2.2.4?

**Comment by engcom-backlog-nickolas** [comment] 2018-07-03 10:37
@denistrator, yes. I've tried to reproduce it on 2.2.4, 2.2.5 and 2.3.0

**Comment by denistrator** [comment] 2018-07-04 16:36
@engcom-backlog-nickolas I've tested it again on just installed M2.2.4. 
https://www.youtube.com/watch?v=wOv10BJFAXA

**Comment by engcom-backlog-nickolas** [comment] 2018-07-05 06:14
@denistrator, thanks for help, much appreciated. We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2018-11-24 13:43
Hi @niravkrish. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2018-12-08 04:58
Hi @hiren0241. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by mrtuvn** [comment] 2021-03-26 11:39
![Screenshot from 2021-03-26 18-37-48](https://user-images.githubusercontent.com/1908873/112626221-7f61ff00-8e62-11eb-8757-fd40872a8249.png)
works fine in my local

**Comment by engcom-Bravo** [comment] 2024-09-25 06:10
@mrtuvn Thanks for your contribution!!.

As per this comment https://github.com/magento/magento2/issues/16490#issuecomment-808148353 the issue was working fine in Latest 2.4-develop branch.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-09-25 06:10 UTC
Labels: Component: Translation, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Reproduced on 2.4.x, Priority: P2, Severity: S2, Progress: done, Area: Framework
