### ISSUE TITLE
Why is error_reporting(E_ALL) set in app/bootstrap.php?

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#37991] opened 2023-09-14 11:44 UTC
https://github.com/magento/magento2/blob/4c36116dcf878e127059d9be9566a119783583f2/app/bootstrap.php#L10

This overrides the php.ini setting.

**Comment by jampolm** [comment] 2023-09-15 06:54
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2023-09-21 07:33
Hello @Eddcapone,

Thank you for the report and collaboration!

Please Provide us the steps to reproduce the issue if applicable, and explain what is the issue you are facing and the use case regarding the same.

Thank you.

**Comment by Eddcapone** [comment] 2023-09-29 06:48
@engcom-November Issue: It overrides the setting in the php.ini

**Comment by engcom-November** [comment] 2023-11-28 14:23
Hello @Eddcapone,

This is the intended behavior of bootstrap.php, this is done to isolate the PHP configuration for a particular application from the global PHP configuration.
If you want to exclude deprecated errors you can add the `~E_DEPRECATED` to bootstrap.php as well.
And if you still have any other issues with this, please let us know the use case for the same.

Thank you.

**Comment by engcom-November** [comment] 2023-12-13 08:04
Hello @Eddcapone,

We have noticed that this issue has not been updated for a long time. We believe your query has been resolved.
Hence closing this issue.

Thank you.

**Closed as completed by engcom-November** 2023-12-13 08:04 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.x

**Comment by fritzmg** [comment] 2024-08-14 15:01
> This is the intended behavior of bootstrap.php, this is done to isolate the PHP configuration for a particular application from the global PHP configuration.

But that does not answer the question why `E_ALL` is used, instead of e.g. `E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_USER_DEPRECATED`. Magento's default `bootstrap.php` causes the application to break on any notice or deprecation.

**Comment by dotung80** [comment] 2025-03-03 09:54
How can we override the app/bootstrap.php file on magento cloud ?
