### ISSUE TITLE
Permissions under SUPHP when installaing Magento2

### ISSUE THREAD

**Issue by frilogg** [magento/magento2#2603] opened 2015-12-04 01:42 UTC
When installing Magento 2 , the installation process use the custom permisson 770 rather than 775 that is normal, but when under a server with SUPHP this should be 755 and for files 644. Please integrate a check in the precheck if there is SUPHP installed if so then use the permission for the system, or else people first need to install Magento 2 and then change all permissons, taking time.

**Comment by wonderfan** [comment] 2015-12-04 07:13
Magento 1 has the check PHP scipt, 2 should have it either.

**Comment by davidalger** [comment] 2015-12-09 01:33
Closing as duplicate of #2412

**Closed as completed by davidalger** 2015-12-09 01:33 UTC

**Comment by hudson1985** [comment] 2016-03-24 17:55
I am having trouble with the simplest command "magent indexer:reindex" on magento 2.  resetting the permissions is way over my head unless you do it from filemanager on the godaddy c-panel.  If I do that I do not know have to differentiate between users.  Godaddy has been zero help.  Anyone that can help me get past this issue so I can reindex my magento 2 site?

**Comment by alankent** [comment] 2016-03-24 23:17
Hi @hudson1985 I have not  tried this, so risky giving advice... but.... (note: we are doing a review of file permissions and modes right now internally). I fear the GoDaddy account has a different userid and group for the web server and the user I logged on via ssh. You could try using 'su' to become the same user as the web server, or 'newgrp' I think it is so your default group is the same as the web server group.  This is an active discussion topic internally - we tried to tighten up security, but shared hosting is not standardized, making it harder.

**Comment by hudson1985** [comment] 2016-03-25 03:54
Thanks for reply.  I finally solved the issue.  You were not supposed to run the command in the root directory but the bin directory.  In this case cd /home/sitename/public_html/bin.  Then from within bin it was php magento indexer:reindex 
This is the setup for hosting on a virtual private server with Godaddy for Magento 2.
