### ISSUE TITLE
The "componentType" configuration parameter is required for the "" component.

### ISSUE THREAD

**Issue by Naberdz** [magento/magento2#37687] opened 2023-06-29 06:48 UTC
### Preconditions and environment

- Magento version 2.4.6
- Any extension that adds product attributes.

### Steps to reproduce

Install any extension which creates and adds attributes to a product.
Delete extension.
Delete created attributes from eav_attribute table
Try to edit product by clicking on edit button.

### Expected result

We should be able to edit product.

### Actual result

We get following error:
```
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): The "componentType" configuration parameter is required for the "" component.


Exception #0 (Magento\Framework\Exception\LocalizedException): The "componentType" configuration parameter is required for the "" component.
<pre>#1 Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem() called at [vendor/magento/framework/View/Element/UiComponentFactory.php:334]
#2 Magento\Framework\View\Element\UiComponentFactory->mergeMetadata() called at [vendor/magento/framework/View/Element/UiComponentFactory.php:231]
#3 Magento\Framework\View\Element\UiComponentFactory->create() called at [vendor/magento/framework/View/Layout/Generator/UiComponent.php:140]
#4 Magento\Framework\View\Layout\Generator\UiComponent->generateComponent() called at [vendor/magento/framework/View/Layout/Generator/UiComponent.php:103]
#5 Magento\Framework\View\Layout\Generator\UiComponent->process() called at [vendor/magento/framework/View/Layout/GeneratorPool.php:93]
#6 Magento\Framework\View\Layout\GeneratorPool->process() called at [vendor/magento/framework/View/Layout.php:365]
#7 Magento\Framework\View\Layout->generateElements() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:68]
#8 Magento\Framework\View\Layout\Interceptor->generateElements() called at [vendor/magento/framework/View/Layout/Builder.php:129]
#9 Magento\Framework\View\Layout\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Page/Builder.php:65]
#10 Magento\Framework\View\Page\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Layout/Builder.php:65]
#11 Magento\Framework\View\Layout\Builder->build() called at [vendor/magento/framework/View/Layout.php:271]
#12 Magento\Framework\View\Layout->build() called at [vendor/magento/framework/View/Layout.php:896]
#13 Magento\Framework\View\Layout->getBlock() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:293]
#14 Magento\Framework\View\Layout\Interceptor->getBlock() called at [vendor/magento/module-backend/Model/View/Result/Page.php:26]
#15 Magento\Backend\Model\View\Result\Page->setActiveMenu() called at [vendor/magento/module-catalog/Controller/Adminhtml/Product/Edit.php:82]
#16 Magento\Catalog\Controller\Adminhtml\Product\Edit->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#17 Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#18 Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#19 Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->___callPlugins() called at [generated/code/Magento/Catalog/Controller/Adminhtml/Product/Edit/Interceptor.php:23]
#20 Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#21 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:151]
#22 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#23 Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#24 Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:145]
#25 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#26 Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#27 Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->___callPlugins() called at [generated/code/Magento/Catalog/Controller/Adminhtml/Product/Edit/Interceptor.php:32]
#28 Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:245]
#29 Magento\Framework\App\FrontController->getActionResponse() called at [vendor/magento/framework/App/FrontController.php:212]
#30 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:147]
#31 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#32 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#33 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#34 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#35 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#36 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#37 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#38 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
</pre>
```
also tried to use following command: 
`bin/magento catalog:product:attributes:cleanup`
result was same.

After testing within the code of : vendor/magento/framework/View/Element/UiComponentFactory.php
```
protected function mergeMetadataItem(array $bundleComponents, array $metadata, $reverseMerge = false)
389     {
390         foreach ($metadata as $name => $data) {
391             $selfData = $data;
392             if (isset($selfData['children'])) {
393                 unset($selfData['children']);
394             }
```
variable $name seem to be empty.
and $data contains follwoing:
```
Array
(
    [children] => Array
        (
            [columns] => Array
                (
                    [arguments] => Array
                        (
                            [data] => Array
                                (
                                    [config] => Array
                                        (
                                            [isAllowed] => 1
                                        )

                                )

                        )

                )

        )

)
```

had to add on line 395 following: `if(!$name) continue;`

any idea on how to fix this issue ?

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-07-03 10:41
Hi @Naberdz,

Thank you for reporting and collaboration.


Using default features of magento  to create a product attribute and then assigning it to an attribute set followed by product and deleting it from eav_attribute table in database, through which we are not able to reproduce the issue .


Can you please name the extension that you have installed and procedures to install the same in my local system on git based 2.4-develop magento instance



Thnaks.

**Comment by Naberdz** [comment] 2023-07-03 10:49
@engcom-Bravo  i have used following module: webkul/google_shopping_feed 
although it's a paid module: https://store.webkul.com/magento2-google-shopping-feed.html

**Comment by engcom-Bravo** [comment] 2023-07-04 07:57
Hi @Naberdz,

Thanks for your update.

“webkul/google_shopping_feed” that doesn't come along with latest / default Magento installation. Code of this package is not part of https://github.com/magento/magento2 git repository. We are not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) or the [Magento Market place](https://marketplace.magento.com/extensions.html) page

Thank you.

**Closed as completed by engcom-Bravo** 2023-07-04 07:57 UTC
Labels: Component: Bundled Extension, Issue: needs update, Reported on 2.4.6
