### ISSUE TITLE
Page Builder - bug caused when loading script block where end tags are not escaped

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#32635] opened 2021-03-31 12:00 UTC
### Preconditions (*)

1. 2.4.2 Enterprise

### Steps to reproduce (*)

1. Create a new template file:

    app\code\Company\Base\view\frontend\templates\scripts\bug.phtml
    
        <script>
        require([
            'jquery',
            'domReady!'
        ], function ($) {
	        $("body").append("<div>foobar1234</div>");
        });
        </script>

1. Create a new CMS site
2. Add a HTML Node
3. Paste the following code into the HTML Node to load the template:

```
{{block class="Magento\Framework\View\Element\Template"
template="Company_Base::scripts/bug.phtml"}}
```

4. Load the CMS site in the frontend

### Expected result (*)

Check if foobar1234 was added to body (should appear at very bottom)

### Actual result (*)

`"); });`

### Workaround:

Escape end tag:

    $("body").append("<div>foobar1234<\/div>");

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Usik2203** [comment] 2021-04-01 11:19
@magento give me 2.3.5-p2 instance

**Comment by Usik2203** [comment] 2021-04-01 11:22
@magento give me 2.3.5 instance

**Comment by mrtuvn** [comment] 2021-04-05 15:44
![Screenshot from 2021-04-05 22-43-34](https://user-images.githubusercontent.com/1908873/113593237-6296aa00-9660-11eb-887a-b0a047fac761.png)
My quicktest with 2.4-develop open source

**Comment by Eddcapone** [comment] 2021-04-06 08:25
@mrtuvn You have to do it with page builder exactly like in my instructions.

**Comment by engcom-Hotel** [comment] 2021-09-15 13:40
Hello @Eddcapone,

We have tried to reproduce this issue in Magento 2.4-develop branch with the mentioned steps. But unable to reproduce the issue. Please have a look at the below screenshots and let us know in case we missed anything:

**In Admin Panel (with Pagebuilder):**

![image](https://user-images.githubusercontent.com/51681618/133443796-2c29a7bd-132a-4d2f-bb13-21542eac67e9.png)

**In Frontend**

<img width="1440" alt="Screenshot 2021-09-15 at 7 08 58 PM" src="https://user-images.githubusercontent.com/51681618/133443962-2fd0dc03-df82-4452-9183-715bf2b7e669.png">

Thanks

**Comment by Eddcapone** [comment] 2021-09-16 07:25
Hello, then you guys seem to have fixed it. Well done!

**Comment by engcom-Hotel** [comment] 2021-09-20 08:19
Hello @Eddcapone,

As this issue has been fixed. We are closing this issue.

Thanks

**Closed as completed by engcom-Hotel** 2021-09-20 08:19 UTC
Labels: Issue:  Cannot Reproduce, Component: PageBuilder, Issue: needs update
