### ISSUE TITLE
Quantity change after variation change results in product price reverting to lowest price

### ISSUE THREAD

**Issue by Swannyj** [magento/magento2#39046] opened 2024-08-14 16:18 UTC
### Preconditions and environment

- Magento version - 2.4.6-p6
- A 2.4.4 demo site used to recreated issue https://magento2-demo.scandiweb.com/chaz-kangeroo-hoodie.html 

### Steps to reproduce

- Go to a configurable Product that has price changing variant options.
- Select a different variant option (price should update)
- Enter a quantity (the price should revert back to the lowest price)

### Expected result

Price should not change to lowest price

![image](https://github.com/user-attachments/assets/6ec2aecd-2563-4bfb-965e-d9953ebc22fe)

### Actual result

On the attached demo site link I have configured the item Chaz Kangeroo Hoodie XS Grey to have a price of $100 and I can see that when I choose them options. However, if I then decide to input a Qty change, the price shown is not the same (reverts back to $52).

![image](https://github.com/user-attachments/assets/665182b8-e865-4e4d-974a-c4280babd754)

### Additional information

I have tested this on a local 2.4.6-p6 instance of Magento and I am seeing the same issue. 

I believe that the code causing this issue is within `vendor/magento/module-catalog/view/base/web/js/price-box.js` , more specifically the `getPrice` function which is called every time `#qty` is changed.

I have added a work around for this functionality which not only stops this issue from occurring, but also updates the price against the product based on the `qty` the user has entered. 

[price-box.zip](https://github.com/user-attachments/files/16615897/price-box.zip)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-08-28 09:47
Hi @Swannyj,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.



https://github.com/user-attachments/assets/ec4f28d1-6bb6-43e6-8c3d-c3add2e1935c



Price is not changing to lowest price after entering the quantity.

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-09-10 05:15
Hi @Swannyj,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-09-10 05:15 UTC
Labels: Issue: needs update, Reported on 2.4.6-p6
