### ISSUE TITLE
Script errors in console

### ISSUE THREAD

**Issue by monotheist** [magento/magento2#26132] opened 2019-12-19 08:39 UTC
### Preconditions (*)

1. Magento 2.3.3
2. PHP 7.3

### Steps to reproduce (*)

1. Open browser console and navigate the store and you will see attached console errors occurring intermittently

### Expected result (*)

1.  No errors
2.

### Actual result (*)

1. Tried both Luma and Ultimo theme. Cleared static directory and regenerated content. Nothing has solved this issue?

![console-errors](https://user-images.githubusercontent.com/16968205/71157930-eb6db480-2268-11ea-9089-c0e8d34d4bdf.jpg)
![Screenshot 2019-12-19 at 12 02 55 PM](https://user-images.githubusercontent.com/16968205/71157935-ee68a500-2268-11ea-9903-41ca4d817ca7.jpg)

**Comment by engcom-Echo** [comment] 2019-12-19 09:28
Hello @monotheist 

Try to run
 `bin/magento setup:static-content:deploy en_US --exclude-theme Magento/luma --no-html-minify`
More info [here](https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-static-view.html)

**Comment by monotheist** [comment] 2019-12-19 09:50
@engcom-Echo Thanks for your time and reponse. I just tried that command and flushed the cache. Issue still exists. Also please note that I don't have third party extension installed. Please help.

**Comment by engcom-Echo** [comment] 2019-12-19 10:15
@monotheist 
Try to run `php bin/magento setup:static-content:deploy` 
Is the magento page displayed normally?

**Comment by monotheist** [comment] 2019-12-19 10:18
@engcom-Echo Yes. The page loads normally. I see the page contents. But there are console errors.

**Comment by devchris79** [comment] 2019-12-19 12:38
Try switching to developer mode then back to production, this should also rebuild content:

`bin/magento deploy:mode:set developer`
then
`bin/magento deploy:mode:set production`

**Comment by monotheist** [comment] 2019-12-19 12:47
> Try switching to developer mode then back to production, this should also rebuild content:
> 
> `bin/magento deploy:mode:set developer`
> then
> `bin/magento deploy:mode:set production`

I have done that too. no luck

**Comment by engcom-Echo** [comment] 2019-12-19 13:13
@monotheist 

Try reinstalling the Ultimo theme.

**Comment by monotheist** [comment] 2019-12-19 13:16
@engcom-Echo I tried that also. I have also tried switching to Luma. Issue persists.

**Comment by engcom-Echo** [comment] 2019-12-19 13:27
@monotheist 

These errors are related to the Ultimo theme. Try deleting it and checking the console log.
Then run `php bin/magento setup:static-content:deploy` and clear the cache
![Screenshot_18](https://user-images.githubusercontent.com/51681435/71176903-794e9d00-2273-11ea-8b20-585100d1db8a.png)
![Screenshot_17](https://user-images.githubusercontent.com/51681435/71176904-794e9d00-2273-11ea-82b6-48035fcdf1ab.png)

**Comment by monotheist** [comment] 2019-12-19 13:50
@engcom-Echo I just switched to Luma and I seeing the same console errors in Luma. Please see attached. Ultimo in completely disabled. Cache flushed and static content redeployed.

![lumaone](https://user-images.githubusercontent.com/16968205/71178600-8af46c80-2294-11ea-9934-e9bd4d4cbb2e.jpg)
![lumatwo](https://user-images.githubusercontent.com/16968205/71178606-8e87f380-2294-11ea-8f75-94f0910b5d18.jpg)

**Comment by engcom-Echo** [comment] 2019-12-19 14:11
@monotheist 
Could you show the result of the next command?
`php bin/magento deploy:mode:show`

**Comment by engcom-Echo** [comment] 2019-12-19 14:23
@monotheist 
Could you provide more details for reproduce this issue?
Please add the steps that were taken before receiving these errors.

**Comment by monotheist** [comment] 2019-12-19 14:36
@engcom-Echo These console errors are occurring both in developer and production mode. And it is also occurring irrespective of themes. To reproduce open browser console and navigate the store and you will see  console errors.

**Comment by engcom-Echo** [comment] 2019-12-19 16:17
Hello @monotheist 

Thank you for your report and collaboration!
I am not able to reproduce this issue on the 2.4-develop branch by provided steps.

**Testing scenario:**

**Steps to reproduce:**

Open homepage on frontend.

**Result:** 
No errors. Page loaded successfully.
![Screenshot_20](https://user-images.githubusercontent.com/51681435/71189546-aa3acc00-228b-11ea-9d1d-a118476da4d5.png)
![Screenshot_19](https://user-images.githubusercontent.com/51681435/71189463-8a0b0d00-228b-11ea-8a9d-385e76ecb93c.png)

So I have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Echo** 2019-12-19 16:17 UTC
Labels: Issue: Format is valid
