### ISSUE TITLE
GET rest/V1/customers/me

### ISSUE THREAD

**Issue by vk44295** [magento/magento2#31087] opened 2020-11-28 07:15 UTC
### Description (*)
I am using Magento 2.2.9 rest /V1/customers/me it didn't respond.

steps 1. Use rest/V1/integration/customer/token

Response Get: bf03bdurbv7pelhgtjnw5yu7kqkr6pbd

http://prntscr.com/vfxtsx

Steps 2: rest /V1/customers/me

Authorization: Bearer bf03bdurbv7pelhgtjnw5yu7kqkr6pbd

Response: { "message": "Consumer is not authorized to access %resources", "parameters": { "resources": "self" } }

can you please help me to sort out this as soon as possible?

### Expected behavior (*)
To get Logged customer details.

**Comment by vk44295** [comment] 2020-11-30 05:49
@magento I am working on this.

**Comment by engcom-Alfa** [comment] 2020-12-02 10:44
Hi @vk44295 . Thank you for your report.
Unfortunately, we are not able to reproduce this issue on fresh 2.4-develop.
Everything works as expected.

**Manual testing scenario:**

1. Send **POST** `/rest/V1/integration/customer/token` request;

**Actual Result:** :heavy_check_mark:  Response: 200 OK

Response Get: _ogyjt38avzsto8d6anpd45hnerbqueio_

![Screenshot from 2020-12-02 12-37-05](https://user-images.githubusercontent.com/51679138/100862251-a05da900-349b-11eb-8a6d-904919b30ece.png)

2. Send **GET** `/rest/V1/customers/me` request;

**Actual Result:** :heavy_check_mark:  Response: 200 OK. Got Logged customer details.

![Screenshot from 2020-12-02 12-37-38](https://user-images.githubusercontent.com/51679138/100862598-077b5d80-349c-11eb-9d35-10064b84592e.png)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-12-02 10:44 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.2.x

**Comment by vk44295** [comment] 2020-12-03 09:47
Hi @engcom-Alfa  I am using 2.2.9 and the same method that you have shown above, but didn't work in my case? Can you please suggest what may issue there?

**Comment by vk44295** [comment] 2020-12-04 07:14
Hi, @engcom-Alfa I got the solution by myself, As I add some code in the .htaccess file, and it's working fine now. 

RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

Thanks for your support.

**Comment by AbstractFlame** [comment] 2022-07-15 10:35
I have the same issue exactly
