### ISSUE TITLE
Category product count issue

### ISSUE THREAD

**Issue by rishabhrkrai** [magento/magento2#8887] opened 2017-03-15 08:03 UTC
When I import product, then in category product count is not same as product in admin for that category. But when i go to admin in category section **Magento Admin > Catalog > Category** click on category and just save the category, Product count is correct.
### Preconditions

1. I use Magento 2.1.4, PHP 7.0, Mysql 5.4, Nginx

### Steps to reproduce

1. Import some products with different category
2. Run the indexer
3. Go to storefront and see the category product count.

### Expected result

1. Product count is same as in category, if all the product have simple type and visible on frontend.

### Actual result

1. Product count is less than the number of product in backend.

**Comment by gputignano** [comment] 2017-03-15 11:29
Besides product count products in category are all visible?
This ticket seems to be the same of this: https://github.com/magento/magento2/issues/8681

**Comment by rishabhrkrai** [comment] 2017-03-15 11:50
@gputignano ; All the products have visibility **Catalog,Search** , but if i click and save that category again manually from admin panel then the issue is resolved for the next few days.

**Comment by yumicom** [comment] 2017-04-21 19:27
my solution:  products - catalog - select all - action - change status - enable

**Comment by Silarn** [comment] 2017-08-02 06:01
Official fix exists as MAGETWO-62616 - though it only exists in the devel and 2.2 RC branches.

I'm planning to work on a module version of this fix tomorrow - which is a true fix and not a workaround. (At least until the core fix is released.)

**Comment by Silarn** [comment] 2017-08-02 19:43
I've compiled a standalone version of the official fix at composer package `silarn/magento2-catalog-indexer-fix`.

For now I just have `dev-master` available, but as soon as I can confirm this standalone version works I'll push a v1.0.0 tag.

I'm using identical code in a full Magento 2 install, so it should work - I just haven't tested the composer version yet.

**Comment by orlangur** [comment] 2017-09-20 16:30
Closing as the fix for this issue is already available on Magento 2.2.0 branch.

Anyone, do not hesitate to create a backport to `2.1-develop` if needed, see https://community.magento.com/t5/Magento-DevBlog/Pull-Requests-for-2-1-x-Patch-Releases/ba-p/65630 for details.

**Closed as completed by orlangur** 2017-09-20 16:30 UTC
Labels: Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
