### ISSUE TITLE
_saveCache in AbstractBlock doesnt respect cache-lifetime false

### ISSUE THREAD

**Issue by schnappenberger** [magento/magento2#6959] opened 2016-10-11 14:46 UTC
In method _saveCache of AbstractBlock cache lifetime is checked by !$this->getCacheLifetime(). Cachetime false doesnt work with this check. 
### Preconditions
1. Magento 2.1.1
2. PHP 7
3. Mysql 5
4. Apache 2
### Steps to reproduce
1. Enable block cache and set cachelifetime of a block to false
2. check if block cache is saved
### Expected result
1. Block cache is saved
### Actual result
1. method returns before saving block cache, because !$this->getCacheLifetime() is true for cachelifetime false

Fix: change if (!$this->getCacheLifetime() || !$this->_cacheState->isEnabled(self::CACHE_GROUP)) { to if ($this->getCacheLifetime() === null || !$this->_cacheState->isEnabled(self::CACHE_GROUP)) {

**Comment by magento-engcom-team** [comment] 2017-11-07 08:30
@schnappenberger, thank you for your report.
The issue is already fixed in 2.1.9

**Closed as completed by magento-engcom-team** 2017-11-07 08:30 UTC
Labels: bug report, Component: Framework/Cache, Issue: Clear Description, Issue: Confirmed, Fixed in 2.1.x, Issue: Format is valid

**Comment by agoeurysky** [comment] 2018-03-06 11:38
Hi @schnappenberger @magento-engcom-team ,

Why is this issue closed ? The _saveCache AbstractBlock method is always the same in v2.2.3 : https://github.com/magento/magento2/blob/2.2.3/lib/internal/Magento/Framework/View/Element/AbstractBlock.php#L1113
