### ISSUE TITLE
Table rate Shipping method (Weight and Destination) does not work

### ISSUE THREAD

**Issue by chi07** [magento/magento2#7286] opened 2016-11-03 02:40 UTC
Hi Everyone. I have a problem with shipping method is table rate (Shipping method). When i create a new order. All Shipping methods are working fine (including table rate shipping method: Price and destination). **There is table rate Weight and Destination** does not work only => can not applied into the order.

**I'm using magento 2.1.1**

This is my tablerate.csv content. The Region/State have been update successfully.

Country,Region/State,Zip/Postal Code,Weight (and above),Shipping Price
MY,MY-A,,0,0
MY,MY-B,,0,0
MY,MY-JH,,0,0
MY,MY-KH,,0,0
MY,MY-KI,,0,0
MY,MY-KL,,0,0
MY,MY-KN,,0,0
MY,MY-LA,,0,0
MY,MY-ME,,0,0
MY,MY-NS,,0,0
MY,MY-PG,,0,0
MY,MY-PH,,0,0
MY,MY-PI,,0,0
MY,MY-PJ,,0,0
MY,MY-PK,,0,0
MY,MY-PL,,0,0
MY,MY-SA,,0,0
MY,MY-SK,,0,0
MY,MY-SL,,0,0
MY,MY-TE,,0,0
MY,MY-JH,,0.2,18
MY,MY-KH,,0.2,18
MY,MY-KI,,0.2,18
MY,MY-KL,,0.2,18
MY,MY-KN,,0.2,18
MY,MY-LA,,0.2,18
MY,MY-ME,,0.2,18
MY,MY-NS,,0.2,18
MY,MY-PG,,0.2,18
MY,MY-PH,,0.2,18
MY,MY-PI,,0.2,18
MY,MY-PJ,,0.2,18
MY,MY-PK,,0.2,18
MY,MY-PL,,0.2,18
MY,MY-SA,,0.2,18
MY,MY-SK,,0.2,18
MY,MY-SL,,0.2,18
MY,MY-TE,,0.2,18
MY,MY-JH,,6,56
MY,MY-KH,,6,56
MY,MY-KI,,6,56
MY,MY-KL,,6,56
MY,MY-KN,,6,56
MY,MY-LA,,6,56
MY,MY-ME,,6,56
MY,MY-NS,,6,56
MY,MY-PG,,6,56
MY,MY-PH,,6,56
MY,MY-PI,,6,56
MY,MY-PJ,,6,56
MY,MY-PK,,6,56
MY,MY-PL,,6,56
MY,MY-SA,,6,56
MY,MY-SK,,6,56
MY,MY-SL,,6,56
MY,MY-TE,,6,56
MY,MY-JH,,13,100
MY,MY-KH,,13,100
MY,MY-KI,,13,100
MY,MY-KL,,13,100
MY,MY-KN,,13,100
MY,MY-LA,,13,100
MY,MY-ME,,13,100
MY,MY-NS,,13,100
MY,MY-PG,,13,100
MY,MY-PH,,13,100
MY,MY-PI,,13,100
MY,MY-PJ,,13,100
MY,MY-PK,,13,100
MY,MY-PL,,13,100
MY,MY-SA,,13,100
MY,MY-SK,,13,100
MY,MY-SL,,13,100
MY,MY-TE,,13,100

**Comment by andreaschiffo** [comment] 2016-11-07 13:11
@shinichi2510 have you controlled the following?
-that the shipping method is really enabled on the website you're using
-that the table shipping_tablerate is populated
-that in shipping methods configuration (stores-config-sales-shipping methods), if you select your website (not 'default') and export the csv, the csv file is not empty

**Comment by chi07** [comment] 2016-11-07 13:15
Thanks. I followed all steps. Please help me check. Thanks

**Comment by andreaschiffo** [comment] 2016-11-07 17:05
did _bin/magento module:enable_ and _setup:upgrade_ work fine, with no errors?
have you checked the error log (_[MagentoDir]/var/log/exception.log_) and the apache/webserver log?
have you configured the weight attribute in your products?
if you haven't got any details on the issue then i dont know i'm sorry...

im using M 2.0.9, and Table Rates is correctly being displayed on frontend, but i'm finding this issue with Table Rate shipping method on admin backend: 

## TableRates shipping amount not being displayed in Order Creation from admin backend

### Preconditions

-having a multistore website
-having enabled tablerates shipping method, price vs destination, not including virtual products in price calculation, no handling fee, for all allowed countries, not showing if not applicable
-(optional) having configured another shipping method (custom extension MatrixRates in my case)

### Steps to reproduce

create a new order **from admin backend**  (doesnt depend wich store or customer you choose, just be careful to insert some data that is good for TableRates shipping), add some **simple** products, hit the _Get shipping methods and rates_ link

### Actual Result

Table Rates shipping option/cost will not be displayed

### Expected Result

Table Rates shipping option/cost being displayed with amount

IMHO, having researched for some time, the problem may be in [_magento\module-offline-shipping\model\carrier\tablerate_, precisely under the collectRates method](https://github.com/magento/magento2/blob/develop/app/code/Magento/OfflineShipping/Model/Carrier/Tablerate.php#L130)
if we dont have any virtual products, we will rely on _$request->getPackageValue()_ to calculate the order amount and then fetch the Table Rate Shipping configuration, but the problem is that _$request->getPackageValue()_ returns 0 in this phase, and this doesn't allow a proper comparation with the configuration

as a patch i've developed a plugin recalculating the Package Value to make sure it is >0

**Comment by veloraven** [comment] 2016-11-10 13:05
@shinichi2510 thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
If it is more question than an issue please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) as GitHub issue tracker is intended for technical issues only.

**Comment by andreaschiffo** [comment] 2016-11-11 10:39
@veloraven what about the issue i've reported above?

**Comment by jurpro** [comment] 2016-11-14 01:14
May I can answer. Sorry if I mistake. 
You are making a mistake buddy. Look a format :
Country,Region/State,Zip/Postal Code,Weight (and above),Shipping Price

But you wrote:
MY,MY-A,,0,0
MY,MY-B,,0,0

If you unsure about zip/postal code, just put a code *. So, the code to be:

MY,MY-A,_,0,0
MY,MY-B,_,0,0

Don't put a"blank" space beetwen comma.

Maybe it help.
Edit: it seems can't write "_" here. (stars) Just like it: MY,MY-A,11111,0,0
And you change 11111 to be "_" without "" only star

**Comment by andreaschiffo** [comment] 2016-11-14 07:24
> If you unsure about zip/postal code, just put a code *. 

yeah its worth trying... but seems to me that \* and void ('') are treated the same way

**shop/vendor/magento/module-offline-shipping/Model/ResourceModel/Carrier/Tablerate.php** - line 187

```
$result = $connection->fetchRow($select, $bindings);
        // Normalize destination zip code
        if ($result && $result['dest_zip'] == '*') {
            $result['dest_zip'] = '';
        }
```

@veloraven should i open another issue for what i have pointed out?

**Comment by veloraven** [comment] 2016-11-17 13:41
@andreaschiffo yes, please create separate GitHub report for your issue.

**Comment by veloraven** [comment] 2016-11-17 13:44
@jurpro just for future, you can make asterisk sign visible by adding "\" before it: "*".

**Comment by andreaschiffo** [comment] 2016-11-17 16:30
@veloraven opened #7472

**Comment by danipolo** [comment] 2016-11-22 19:09
im with the same problem, exact.

**Comment by veloraven** [comment] 2016-11-28 13:36
I'm closing this issue as there was no reaction from the reporter foe more than two weeks.
@danipolo if you have the same problem please create new GitHub issue formatting it  according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. Please, also identify which version of Magento you are running.

**Closed as completed by veloraven** 2016-11-28 13:36 UTC
Labels: Progress: needs update

**Comment by Sharmilasrini95** [comment] 2018-05-22 07:33
Is there any possible to import multiple countries with comma(,) separator in single entry in table rate csv?
