### ISSUE TITLE
Impossible to assign "new" state to any "status" from Backend

### ISSUE THREAD

**Issue by jtalel** [magento/magento2#23682] opened 2019-07-12 15:39 UTC
### Preconditions (*)

1. Magento Open Source version 2.2.8
2. PHP 7.1.29, MySQL 5.6, Apache 2.4. 
3. Clean install. No extensions or themes installed.

### Steps to reproduce (*)

1. Go to Stores -> Configuration -> Sales -> Sales -> Orders Cron Settings -> Pending Payment Order Lifetime (minutes)
2. Set "Pending Payment Order Lifetime" to 1 hour (or desired time).  (this options allows you to cancel by schedule orders that are in "Pending Payment" status.
3. Go to Stores -> Configuration -> Sales -> Payment Methods
4. Select any offline "Payment Method" and attempt to change "New Order Status" to "Pending Payment" (it won't work if you select "Pending").
5. If you can't see "Pending Payment" as an option (I DIDN'T), then go to Store -> Order Status
6. Attempt to assign "Pending Payment" status with "new" state.

### Expected result (*)

1. We expect to be able to assign "Pending Payment" status with "new" state. That would be the only way to be able to select "Pending Payment" as a "New Order Status"
2. Orders created in "Pending Payment" would be cancelled after 1 hour (or whatever you input in "Pending Payment Order Lifetime").

### Actual result (*)

1. It's impossible to assign "new" state to any "status".
2. Offline Payment Methods will only be created in "Pending" status and you'll have to cancel them manually or with a 3th party extension.

### How I Solved this:
1. In phpMyAdmin:
`UPDATE `sales_order_status_state` SET `state` = 'new' WHERE `sales_order_status_state`.`status` = 'pending_payment'`

I hope this is solved so that We can assign "new" state to statuses from backend.

**Comment by jtalel** [comment] 2019-07-12 15:41
@m2-assistant yes. Reproduced the issue on vanilla Magento instance.

**Comment by magento-engcom-team** [comment] 2019-07-15 10:21
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18163`, `MC-18164` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by jtalel** [comment] 2019-08-17 16:09
@magento give me 2.2.8 instance

**Comment by magento-engcom-team** [comment] 2019-08-17 16:09
Hi @jtalel. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` release line

**Comment by jtalel** [comment] 2019-08-17 16:09
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-08-17 16:09
Hi @jtalel. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-08-17 16:10
Hi @jtalel, here is your [Magento instance](https://i-23682-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23682-2-3-develop.instances.magento-community.engineering/admin](https://i-23682-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by madhurajawat** [comment] 2020-04-20 06:58
@magento Please give me 2.3 develop instance

**Comment by sdzhepa** [comment] 2020-10-16 18:44
Closed as cannot reproduce on the latest `2.4-develop` code.
But if you still faced the issue please create a new report for 2.4 with detailed steps

**Closed as completed by sdzhepa** 2020-10-16 18:44 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Component: Backend, Progress: done
