### ISSUE TITLE
JavaScript error on register new customer (with address fields enabled)

### ISSUE THREAD

**Issue by klein0r** [magento/magento2#30752] opened 2020-11-02 16:11 UTC
### Preconditions (*)

Magento 2.4-develop
Magento 2.4.1

### Steps to reproduce:

1. Enable "show address fields" for registration block (e.g. with custom customer_account_create.xml layout file)

```
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="customer_form_register">
            <arguments>
                <argument name="show_address_fields" xsi:type="boolean">true</argument>
            </arguments>
        </referenceBlock>
    </body>
</page>
```
2. Go to Storefront -> Create an Account;

### Expected result (*)
 The registration page is working fine

### Actual result (*)
1. JS-Error

`Uncaught SyntaxError: Unexpected token $ in JSON at position 308`

![Screenshot from 2020-11-03 10-03-50](https://user-images.githubusercontent.com/51679138/97962491-fa485180-1dbd-11eb-9f5f-88b6f2785148.png)

The reason is this commit: https://github.com/magento/magento2/commit/39a6e2b5033b67268e75bc1892f0e20e90f505de

Changed

`"regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,`

to

`"regionJson": {$regionJson},`

which makes no sense. PHP variable won't be replaced in HTML / JavaScript automatically. See:

https://github.com/magento/magento2/blob/226b08d0f51c3f6aef7ea969435be2ca07f4b9f6/app/code/Magento/Customer/view/frontend/templates/form/register.phtml#L338-L340

Should be:

```
"regionJson": <?= /* @noEscape */ $regionJson ?>,
"defaultRegion": "<?= /* @noEscape */ $regionId ?>",
"countriesWithOptionalZip": <?= /* @noEscape */ $countriesWithOptionalZip ?>
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment] 2020-11-03 08:21
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38849` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by chiranjeevi-cj** [comment] 2020-11-03 12:16
@magento I am working on this.

**Comment by chiranjeevi-cj** [comment] 2020-11-05 11:48
@magento give me 2.4-develop instance

**Comment by chiranjeevi-cj** [comment] 2020-11-05 12:06
@gabrieldagama  @klein0r @sdzhepa @magento-engcom-team @engcom-Alfa 
Is this issue produced in 2.4-develop. I tried it in my local I'm not getting that error
![Screenshot from 2020-11-05 17-34-15](https://user-images.githubusercontent.com/52098385/98238985-40074480-1f8d-11eb-8e45-fd764e15c7b7.png)

**Comment by klein0r** [comment] 2020-11-05 17:08
I have no idea how you've managed that. 😄 
The issue exists and @engcom-Alfa confirmed it.

Please check the source code. It is impossible that the current code can work...

**Comment by engcom-Alfa** [comment] 2020-11-13 10:47
Duplicate of #30099

**Closed as completed by engcom-Alfa** 2020-11-13 10:47 UTC
Labels: Component: Customer, Issue: Confirmed, Triage: Dev.Experience, Reproduced on 2.4.x, Severity: S2, Priority: P1, Progress: done

**Comment by klein0r** [comment] 2021-01-11 09:53
@magento give me 2.4-develop instance

**Comment by klein0r** [comment] 2021-01-11 12:06
@chiranjeevi-cj This was the last issue I have created here. Makes no sense.
Even such a simple issues with detailed solution is ignored and will make it into the next release...

**Comment by gabrieldagama** [comment] 2021-01-11 13:03
Hi @klein0r, this issue was closed just because there is another one that describes the problem, not because is not reproducible. 

To avoid having 2 issues open about the same problem, we close one in favour of another, in our case here, this one remains open https://github.com/magento/magento2/issues/30099, confirmed and prioritized.

We encourage you to still contributing to our community! Hope that is clear, thanks for reporting this issue.
