### ISSUE TITLE
Invoice confirmation email showing incorrect row totals when partially cancelled

### ISSUE THREAD

**Issue by denis-zyk** [magento/magento2#32307] opened 2021-02-26 17:44 UTC
Invoice confirmation email showing incorrect row totals when partially cancelled as it displays amounts from order item, not from invoice item.

### Preconditions (*)

1. Magento Commerce 2.4.1
2. PHP 7.4.15

### Steps to reproduce (*)

1. Add few products to the cart with multiple qty
2. Proceed to checkout and complete the order
3. Invoice the order for partial qty in backend
4. Ship the same qtys as per invoice
5. Cancel the rest of order
6. (optional) Go to invoice view in the backend and click "Send Email" if automatic emails are disabled

### Expected result (*)

1. Invoice email received displays correct invoiced row totals for invoiced qty (e.g. as in Magento backend)

### Actual result (*)

1. Invoice email displays incorrect invoiced row totals

**Comment by denis-zyk** [comment] 2021-02-26 18:08
@magento give me 2.4-develop instance

**Comment by denis-zyk** [comment] 2021-02-26 18:38
@magento I am working on this

**Comment by denis-zyk** [comment] 2021-02-26 18:41
@magento add to contributors team

**Comment by denis-zyk** [comment] 2021-02-26 18:41
@magento add to contributors team

**Comment by denis-zyk** [comment] 2021-02-26 18:43
@magento I am working on this

**Comment by engcom-Bravo** [comment] 2021-03-03 11:24
Hello @denis-zyk 

Thank you for your report.

Can you please provide more details about the reported issue, if possible with screenshots. This would help us to Confirm the issue?
Here is a manual scenario, we have tried:
1. Place an order containing 4 different products with 4 quantity each
2. From Admin Panel, go to _Sales - Orders_ and **View** the previously created order
3. Click **Invoice**, and update the quantity of each product. In our case
- product1 Ordered **4** - Invoiced **3**
- product2 Ordered **4** - Invoiced **2**
- product3 Ordered **4** - Invoiced **1**
- product4 Ordered **4** - Invoiced **0**
![4321](https://user-images.githubusercontent.com/51680745/109797112-b0636100-7c21-11eb-970b-fcc41c1771c9.png)
![qty_invoiced](https://user-images.githubusercontent.com/51680745/109797222-d852c480-7c21-11eb-922e-afe5c31f7202.png)
4. Click **Ship** and update the _Qty to Ship_ to the same as Invoiced
![qty_to_ship](https://user-images.githubusercontent.com/51680745/109797461-31225d00-7c22-11eb-9de3-ea7c103034c9.png)
**Submit Shipment**
5. Cancel the Order by clicking **Cancel** button
6. Switch to _Invoices_ tab and _View_ the previously created invoice
7. Make sure that _Items Invoiced_ is correct
![item_invoiced](https://user-images.githubusercontent.com/51680745/109797843-a857f100-7c22-11eb-942d-7aa3402eb988.png)
8. Click **Send Email**, and confirm email sending
9. Check if the email contains correct information about products, qty, price

Actual Result
The email contains correct Quantity, Price, Subtotal
![subt](https://user-images.githubusercontent.com/51680745/109798343-4d72c980-7c23-11eb-91ce-43b42bdaf032.png)

Can you please provide screens from: 
- the Invoice in the Admin Panel
- email
- Order info from the customers account on the Storefront
- Are you using any custom email template?

Thank you in advance

**Comment by denis-zyk** [comment] 2021-03-12 10:51
Hi @engcom-Bravo,

I've just checked the release notes for M2.4.2 Commerce Edition now, and noticed the following improvement was mentioned there https://devdocs.magento.com/guides/v2.4/release-notes/commerce-2-4-2.html#email:
> Email sent to customers that contain partial invoices now includes accurate item subtotals. Previously, the subtotal in this email was the total of the ordered quantity, not the total amount of the invoiced quantity.

So that one is hopefully fixed now, but unfortunately I wasn't able to confirm it using 2.4-develop instance provided by `magento-deployment-service` because I haven't received any email notification there.

**Comment by gabrieldagama** [comment] 2021-05-04 16:49
As per the comment above, the issue is likely fixed on 2.4.2. If it is still relevant, please feel free to reopen it.

**Closed as completed by gabrieldagama** 2021-05-04 16:49 UTC
Labels: Issue: needs update
