### ISSUE TITLE
Unable to translate strings that come from JS 

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#5893] opened 2016-07-29 14:52 UTC
There are several strings in Magento that are not coded properly, see those two examples. You also can't clone the corresponding template files to your theme files and modify them, the changes are non functional. 

Here are two examples:
- in Checkout, when using an e-mail adress that is already registered -> password string. 
  ![bildschirmfoto 2016-07-29 um 16 50 34](https://cloud.githubusercontent.com/assets/13021579/17252321/912b18d2-55ac-11e6-899e-6b5a9cadbb2b.png)
- when trying to remove something from the minicart -> Remove String
  ![bildschirmfoto 2016-07-29 um 16 51 49](https://cloud.githubusercontent.com/assets/13021579/17252322/912dfa84-55ac-11e6-9e17-ebb0fbb24d05.png)

The String for the removal is located in /vendor/magento/module-checkout/web/view/minicart.js. You can modify the string to whatever, it won't change in the frontend.

**Comment by pboisvert** [comment] 2016-07-31 04:05
@antboiko passing to Anton. Think the JS strings may be a duplicate but please check the other issue mentioned

**Comment by grasdaggel** [comment] 2016-07-31 11:35
By the way, I've grepped all occourences of those strings via "$ grep -rl "string" *" and found only 2 appearances. One in a i18n-CSV and one in the JS Files.

**Comment by antboiko** [comment] 2016-08-01 16:01
Hi @grasdaggel , what Magento version are you using?

Thanks,
Anton.

**Comment by grasdaggel** [comment] 2016-08-02 07:50
Hi @antboiko, we are using Magento 2.0.6 and Magento 2.0.4 (Screenshots are from .6)

**Comment by jibrandlr** [comment] 2016-08-09 17:06
In Magento 2.1.0 I was able to translate to spanish the string: "Are you sure you would like to remove this item from the shopping cart?" using the .CSV file

**Comment by sevos1984** [comment] 2016-09-15 16:12
Is it still actual? I can translate strings you mentioned. Try update to latest release version version.

**Comment by grasdaggel** [comment] 2016-09-16 09:36
Thanks for the information. 

Updating would implement a bunch of other already known bugs, and therefore we will just use the version we are using right now.

**Comment by sevos1984** [comment] 2016-10-03 09:42
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-10-03 09:42 UTC
Labels: bug report, Progress: needs update

**Comment by exreplay** [comment] 2016-12-14 18:13
If someone is having the same problem, that part of code in `minicart.js` has line breaks and indents:
```
'confirmMessage': $.mage.__(
                'Are you sure you would like to remove this item from the shopping cart?'
            )
```
Just add the checkout module to your theme `Magento_Checkout/web/js/view/minicart.js`, copy the minicart.js content and edit the specific part, so that it is one line.
```
'confirmMessage': $.mage.__('Are you sure you would like to remove this item from the shopping cart?')
```

**Comment by Moppelfett** [comment] 2017-03-16 15:03
@exreplay 
Thank you but for me it still doesn't work.

**Comment by thefinges** [comment] 2017-08-08 13:04
I have the same problem, I fixed it in a very ugly way with CSS
`.modal-content > div::before {
    content: "Wollen Sie diesen Artikel wirklich aus Ihrem Einkaufswagen entfernen?";
    color: #333;
}
.modal-content > div {
    color: white;
}`
