### ISSUE TITLE
Unable to create user in backend with Magento_LoginAsCustomerAdminUi enabled and 'Store View To Login To' set to manual selection.

### ISSUE THREAD

**Issue by wahidnory** [magento/magento2#33096] opened 2021-05-28 13:39 UTC
### Preconditions (*)

1. Magento 2.4.2 | Magento 2.4.2-p1
2. Sample data on both installed
3. Make sure site is set to developer mode
4. Make sure magento/module-login-as-customer-admin-ui is enabled
5. Set Store -> Configuration -> Customers -> Login as Customer -> Store View To Login To to "Manual Selection"
6. or `bin/magento` config:set login_as_customer/general/store_view_manual_choice_enabled 1`

### Steps to reproduce (*)

1. Go to Customers -> All customers
2. click Add New Customer

### Expected result (*)

1. Expect to see form fields to create a new customer
2. ![image](https://user-images.githubusercontent.com/3277057/119992161-8a541f80-bfca-11eb-8f19-c2ec53ffbb8a.png)

### Actual result (*)

1. Exception is thrown with message `Exception #0 (Magento\Framework\Exception\LocalizedException): Unable to get Customer ID.`
2.![image](https://user-images.githubusercontent.com/3277057/119992305-b2438300-bfca-11eb-9cf6-81593090c29a.png)

**Additional Information:**

1. Enable developer mode from terminal: >  
> rm -rf generated/metadata/* generated/code/*
> bin/magento deploy:mode:set developer
2. reindex and clear cache
3. enabled Login as Customer with default values selected."Store view to login to : Auto Detection"
4. Run from terminal: 
> php bin/magento config:set login_as_customer/general/store_view_manual_choice_enabled 1
5. Clear cache.
6. Go to Customers - All Customers - Add new Customer

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by wahidnory** [comment] 2021-05-28 13:40
@magento give me 2.4-develop instance

**Comment by wahidnory** [comment] 2021-05-28 13:50
Unable to reproduce on develop instance.

**Comment by wahidnory** [comment] 2021-05-28 13:50
@magento give me 2.4.2-p1 instance

**Comment by wahidnory** [comment] 2021-05-28 14:03
Unable to reproduce on 2.4.2-p1 instance. 

Guess it's a conflict with something locally.

**Comment by webkul-deepak** [comment] 2021-08-16 08:04
@magento give me 2.4-develop instance

**Comment by webkul-deepak** [comment] 2021-08-16 08:08
@magento give me 2.4.2-p1 instance

**Comment by paulpartington-cti** [comment] 2021-11-23 12:26
I'd like to re-open this issue as I've been able to replicate it with `login_as_customer/general/store_view_manual_choice_enabled` set to `1`.

The issue happens because the New Customer action forwards the request to the `edit` controller. The `module-login-as-customer-admin-ui` module has a layout XML file for the `edit` handle - https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/LoginAsCustomerAdminUi/view/adminhtml/layout/customer_index_edit.xml. This then adds the `Magento\LoginAsCustomerAdminUi\Block\Adminhtml\ConfirmationPopup` block - https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/LoginAsCustomerAdminUi/view/adminhtml/layout/loginascustomer_confirmation_popup.xml

When the manual choice setting is enabled, the block loads the options - https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/LoginAsCustomerAdminUi/Block/Adminhtml/ConfirmationPopup.php#L85

The option source model expects either the customer ID or order ID to be provided as a parameter in the URL and if not, throws the exception - https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/LoginAsCustomerAdminUi/Ui/Customer/Component/ConfirmationPopup/Options.php#L232

I assume this wasn't showing on the development instance because they were in production mode - in this case the page loads but an exception is logged.

**Comment by JeroenVanLeusden** [comment] 2022-02-24 08:21
@wahidnory please reopen ticket. Was able to reproduce on 2.4.3 using @paulpartington-cti steps.

**Comment by wahidnory** [comment] 2022-03-28 08:51
> @wahidnory please reopen ticket. Was able to reproduce on 2.4.3 using @paulpartington-cti steps.

Done.

**Comment by engcom-November** [comment] 2022-03-28 11:07
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-03-28 13:18
Unable to reproduce the issue on Magento 2.4-develop branch. Its recommended to verify issues on Magento 2.4-develop branch as it is the upcoming 2.4.x release and have latest code base. @wahidnory / @JeroenVanLeusden kindly recheck the issue on 2.4-develop instance or elaborate steps/configuration details if the issue occurred to upgrades (specify versions) / or any 3rd party modules if any.
Thank you.

**Comment by engcom-November** [comment] 2022-04-01 09:55
Verified again with below steps in Magento 2.4-develop branch with Sample data:
Enabled Production mode from terminal: > php bin/magento deploy:mode:set production
enabled Login as Customer with default values selected."Store view to login to : Auto Detection"
Run from terminal > php bin/magento config:set login_as_customer/general/store_view_manual_choice_enabled 1
Clear cache.
Go to Customers - All Customers - Add new Customer - No issue. All details displayed and user is able to create customer.
@paulpartington-cti can you please check the steps and let me know if any steps are missed here.
Thank you.

**Comment by JeroenVanLeusden** [comment] 2022-04-01 10:00
@engcom-November 

> If the site is in production mode, the exception is silently logged.

I believe the exception is shown when you put the site in developer mode.

**Comment by erfanimani** [comment] 2022-05-10 01:30
Will the fix for this become available as a Magento Quality Patch?

**Comment by engcom-Alfa** [comment] 2022-05-20 08:41
Hello @wahidnory 

As I can see this issue got fixed in the scope of the internal Jira ticket `AC-2750` by the internal team
Related commits: https://github.com/magento/magento2/commit/b092dd6df013e8b1e77e8b5d639148ed76a7172a

Based on Jira target version is 2.4.5

**Closed as completed by engcom-Alfa** 2022-05-20 08:41 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Component: LoginAsCustomer, Progress: done, Reported on 2.4.2, Area: UI Framework
