### ISSUE TITLE
Content Staging with Custom options

### ISSUE THREAD

**Issue by mohitnavik** [magento/magento2#36507] opened 2022-11-22 10:09 UTC
### Preconditions and environment

Magento version: 2.4.4-p1(EE)

I configure the content staging for a product to update the price and it has custom option.

![image](https://user-images.githubusercontent.com/41897612/203282312-990a783a-f4fd-445f-ac14-36e5216cb91c.png)
![image](https://user-images.githubusercontent.com/41897612/203281459-ab727f9d-590c-4288-bf51-f33610889454.png)
![image](https://user-images.githubusercontent.com/41897612/203281852-7aa204af-31a7-466b-b680-16ae99b7a34e.png)

I already have the same product into the cart before updating the price through content staging. If I try to add product into cart after updating the price through content staging then getting the following error:

"The product's required option(s) weren't entered. Make sure the options are entered and try again."

If remove item/product from the cart and try to add product into the cart then it working fine and product add with updated price. But it doesn't work if same product is in the cart before updating the price.

**Note**: It's working with simple product(without custom options).

I have tried to find the document/artical that how content staging works with custom options/configurable products but we didn't not find anything.

### Steps to reproduce

1. Create a simple product with custom options.
2. Go to product page at front end and add product in cart.
3. Configure/setup the content staging for the same product() and change/update price(**Reference**: https://experienceleague.adobe.com/docs/commerce-admin/catalog/products/product-scheduled-changes.html?lang=en)
4. After updating the product price, try to add product into cart.

### Expected result

It should allow to add product into cart.

### Actual result

Getting the following error:

"The product's required option(s) weren't entered. Make sure the options are entered and try again."

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2022-11-22 10:26
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-11-22 17:14
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-11-28 12:10
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-11-28 18:08
hi @mohitnavik ,

We are trying to reproduce the issue 2.4-develop branch...But we are not able to reproduce the issue.It should allow to add to cart the product.
Steps:
Create simple product 
create schedule update(start date and end date ,Update name,Description.)
Assign the existing update
after updating the price trying to add the product.
We can able to add the product to cart.

Let us know if we missing anything!

Thanks!!!!

**Comment by mohitnavik** [comment] 2022-11-29 16:04
Hi @engcom-Dash,

Can you please try with custom options? Please see the screenshot:

https://user-images.githubusercontent.com/41897612/203282312-990a783a-f4fd-445f-ac14-36e5216cb91c.png

**Comment by engcom-Bravo** [comment] 2022-12-13 06:35
@magento give me 2.4-develop instance with edition EE

**Comment by engcom-Bravo** [comment] 2022-12-13 06:38
@magento give me 2.4-develop instance with edition ee

**Comment by engcom-Bravo** [comment] 2022-12-13 06:47
@magento give me 2.4-develop instance with edition ee

**Comment by engcom-Bravo** [comment] 2022-12-13 12:35
Hi @mohitnavik,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance with ee edition and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

1.Create a simple product with custom options.
2.Go to product page at front end and add product in cart.
3.Configure/setup the content staging for the same product() and change/update price
4.After updating the product price, try to add product into cart.



We are able to add to product.

In cart we have already a same product after updating the product price with content staging.


<img width="1377" alt="Screenshot 2022-12-13 at 2 59 02 PM" src="https://user-images.githubusercontent.com/51680745/207319066-02fd03e3-8b1e-4b5e-b41b-d10de6ab1bd9.png">



<img width="1384" alt="Screenshot 2022-12-13 at 2 58 43 PM" src="https://user-images.githubusercontent.com/51680745/207319196-eafe00b1-8a0b-48cc-9773-da0cc28d007f.png">


<img width="1373" alt="Screenshot 2022-12-13 at 3 01 12 PM" src="https://user-images.githubusercontent.com/51680745/207319323-ddc2e50e-e505-4d24-968d-d64e6546a5cf.png">



Kindly recheck the behavior on Magento 2.4-develop instance with ee edition and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment] 2022-12-27 06:05
Hi @mohitnavik,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-12-27 06:05 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.4-p1
