### ISSUE TITLE
[Magento2]- Some amount (in decimal) is missing from total amount of the downloaded order .

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#38336] opened 2024-01-08 11:19 UTC
### Preconditions and environment

Environmnet -> Magento2
API tool used Postman.

### Steps to reproduce

(1) Connect to Magento2 store.
(2) Download the order using the magento2 API.
(3) Verify if the calculations are correct.

### Expected result

All the calculations should be available in response.
As per the order calculation amount should be 185.47

### Actual result

Some amount from the calculations are missing.

In our order we have -> 
**Amount calculations** = 17.14 * 10 
**Tax** =  0.26 (Order tax)+ 8.57 (Shipping tax)
**Shipping Amount** = 5.24

So the final calculations should be => 17.14 * 10 + 0.26 + 8.57 +5.24 = **185.47**
But as per magento2 order the order total = **185.5**
Where is he missing amount ?

### Additional information

Request ->  http://php72.webgility.com/magento230_test/rest/V1/orders/372

![357](https://github.com/magento/magento2/assets/54638813/2cdde978-b9cc-4f38-9d23-5e96cb2adc66)
[Magento2_Bug_357.txt](https://github.com/magento/magento2/files/13859293/Magento2_Bug_357.txt)

 

### Release note

[Magento2_Bug_357.txt](https://github.com/magento/magento2/files/13859297/Magento2_Bug_357.txt)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by devchris79** [comment] 2024-01-08 12:32
From your post the base subtotal is £171.43, so I would assume the individual units are actually £17.143 and multiplying this by 10 gives the 3p difference.

**Comment by engcom-Bravo** [comment] 2024-01-09 05:58
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-01-09 09:58
Hi @webgility-amazonapi,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

-  Connect to Magento2 store.
-  Download the order using the magento2 API.
-  Verify if the calculations are correct.

![Screenshot from 2024-01-09 11-58-51](https://github.com/magento/magento2/assets/51680745/7d463410-b79c-4ee5-ab02-9ed136f9651d)



![Screenshot from 2024-01-09 12-15-13](https://github.com/magento/magento2/assets/51680745/632610e5-20df-4087-82a2-404391f6266a)



All the calculations should be available in response.the order calculation amount is 185.47.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-01-22 04:34
Hi @webgility-amazonapi,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38336#issuecomment-1882754729 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-01-29 04:09
Hi @webgility-amazonapi,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Bravo** 2024-01-29 04:09 UTC
Labels: Issue: needs update, Reported on 2.4.x
