### ISSUE TITLE
Web Setup Wizard Icon Inconsistency

### ISSUE THREAD

**Issue by Franzld** [magento/magento2#11236] opened 2017-10-05 07:32 UTC
The Icons for "Extension Manager" and "Module Manager" are inconsistent in the main content area and left-hand menu of the Web Setup Wizard.

### Preconditions
1. Install Magento 2.2.0 Open Source using Composer and the web setup

### Steps to reproduce
1. Log into the backend and open "Web Setup Wizard"

### Expected result
1. The same icon is used for "Extension Manager" in the left-hand menu and the main content area.
2. Also, the same icon should be used for "Module Manager" in the left-hand menu and the main content area.

### Actual result
![Web Setup Wizard](https://user-images.githubusercontent.com/15966766/31306000-ca6041d6-ab46-11e7-94f6-c48a0ca8ac9b.jpg)

1. The icon for "Extension Manager" from the left-hand menu is used for "Module Manager" in the main content area and vice versa.

**Comment by mzeis** [comment] 2017-10-06 17:43
Hi, thanks for creating this issue!

Please can you update your issue by adding information in the format that is proposed when creating a new issue? Important information would be which version of Magento 2 you are using and [which way](http://devdocs.magento.com/guides/v2.2/install-gde/bk-install-guide.html) you were getting the code.

**Comment by Franzld** [comment] 2017-10-06 22:41
Hallo Herr Zeis,
Das ist wirklich nur ein falsches Icon am falschen Platz.
Ich habe magento 2.2.0 neu insalliert und wenn man den WebSetupWizzard auruft, sind halt die Icons nicht richtig gesetzt.
Also nichts wichtiges...
Übrigens vielen Dank für Ihre Toutorials, die mir als newby mit rudimentären autodidaktischen Programmierkenntnissen sehr geholfen haben.

**Comment by Franzld** [comment] 2017-10-07 08:03
![unbenannt-1](https://user-images.githubusercontent.com/15966766/31306000-ca6041d6-ab46-11e7-94f6-c48a0ca8ac9b.jpg)

**Comment by mzeis** [comment] 2017-10-07 09:05
@Franzld Thanks for the kind words (I'll continue in English as the Magento team communicates in English :-)).

I wanted to follow up on this - does you closing mean I shouldn't do so?

**Comment by Franzld** [comment] 2017-10-07 09:09
I think, i've done wrong by pushing the closing-button.
I'm sorry.

**Comment by Franzld** [comment] 2017-10-07 09:12
The Icon e.g. "Module Manager" in the center of the Page and on the left Menuebar are different.

**Comment by mzeis** [comment] 2017-10-07 11:09
@Franzld I updated the issue description for you and could reproduce the problem.

**Comment by Franzld** [comment] 2017-10-07 16:05
**@mzeis** Thanks for your kindly support. Now I've learnt, how to report an issue.

**Comment by magento-engcom-team** [comment] 2017-10-09 08:30
@Franzld, thank you for your report.
We've created internal ticket(s) MAGETWO-81242 to track progress on the issue.

**Comment by dverkade** [comment] 2017-10-10 09:19
Which icon is the correct one for the extension manager? The one on main part of the page, or the one in the menu at the left side of the screen?

**Comment by annhudspeth** [comment] 2017-10-11 15:53
That's a good catch - the icons don't match because the smaller one looked better in the left nav but it's definitely inconsistent and potentially confusing.  The icon in the left nav would need to change to the four-pronged piece. I'm not sure we have that already made but I can get it made if needed.

**Comment by annhudspeth** [comment] 2017-10-12 19:33
Looks like the four-pronged icon is available here:http://devdocs.magento.com/guides/v2.1/pattern-library/graphics/iconography/iconography.html
It's the one called "Plug-in". 
Let me know if we need to make one specifically for the nav or if you can call it from the icon font.

**Closed as completed** 2017-12-01 05:15 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by okorshenko** [comment] 2017-12-01 05:18
The issue has been fixed and delivered to 2.2-develop branch. Will be available with upcoming patch release

**Comment by magento-team** [comment] 2018-01-03 15:00
Hi @Franzld. Thank you for your report. 
The issue has been fixed in magento/magento2#12960 by @dverkade in 2.3-develop branch
Related commit(s):
 - 8cb5b9c371894ccebde7797524ca9c21378bfc6b

The fix will be available with the upcoming patch release.
