### ISSUE TITLE
Keep Image Aspect Ratio

### ISSUE THREAD

**Issue by popovdenis** [magento/magento2#12196] opened 2017-11-11 18:54 UTC
I've been investigated how to remove borders on product images and stretch the picture to the whole area on image.

### Preconditions

1. Magento 2.1.6
2. php 7.0.2
3. mariadb 10

### Steps to reproduce

1. Navigate to design/frontend/theme/etc/view.xml
2. Find aspect_ratio parameter for product image
3. Set false as value

### Expected result

1. Image is stretched to the whole area on image

### Actual result

1. Nothing happened

I've investigated that case. The issue is caused in there:
Magento\Catalog\Model\Product\Image

`
public function setKeepAspectRatio($keep)
{
       $this->_keepAspectRatio = (bool)$keep;
       return $this;
}
`
The problem is that $keep is as string "false" and if reduct the "false" to boolean it will be **true**.
Similar case with the following methods in that class:
setKeepFrame()
setKeepTransparency()
setConstrainOnly()

**Comment by magento-engcom-team** [comment] 2017-11-15 06:33
@popovdenis, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-11-15 06:33 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
