### ISSUE TITLE
Magento 2.4.1 Unable to to import custom options in different store view.

### ISSUE THREAD

**Issue by DipaliMarade** [magento/magento2#35137] opened 2022-02-24 11:17 UTC
Hi,

I am trying to import custom options store wise.

Below is the Rest API i am using for english store /us_en/V1/products/SKU.

for spanish store /us_sp/V1/products/SKU.

But whenever i try to add custom option option in one store they are getting updated in all other store.

My Expectation for above issue is - Custom option should get updated store wise. 
In the API i am mentioning the store code correctly. and this works for other details like product name, description.
But API does not work for custom options.
Is there any different API or is this Magento API limitation ?

Below is the HTTP request json format we are using
{

  "product": {
    
    "sku": "10020",
    "name": "Maddox Breeze Cleaner &amp; Deodorizer Odor Eliminator Concentrate 1 Gal", 
    "attribute_set_id": 4,
    "price": 14.99,
    "extension_attributes": {
      "stock_item": {
        "qty": 10,
        "is_in_stock": true,
        "use_config_manage_stock": true
      }
    }
    
     ,
     "options": [
     {
     
        "product_sku": "10020",
        "title":"Unit",
        "type":"drop_down",
        "sort_order": 1,
        "is_require":1,
        "values": [
        {
            "title":"CS/4",
            "price":0,
            "price_type":"fixed",
            "sku":"CS/4",
            "sort_order": 1 
        },
        {
            "title":"One Each",
            "price":0,
            "price_type":"fixed",
            "sku":"One Each",
            "sort_order": 2 
        }
      ] 
     }
    ]
    
    
   }, 
   "saveOptions":true
}

Is there any way to update custom options only in partialar store?

Please provide solution

**Comment by engcom-November** [comment] 2022-02-28 08:23
Hi @DipaliMarade Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue.
**Able to update custom options only in specific store view.** Below steps are performed to update custom options only in specific store view:

1. Admin - Stores - Configuration - Catalog - Set Price scope to "Website" - Save Config
2. Re-index and clear cache
3. Rest API - Generate admin access token using POST request: /rest/all/V1/integration/admin/token
4. Send below PUT request to /rest/<store-code>/V1/products/options/1 to update customizable options only to specific store view:
Sample Payload:
`
{
  "option": {
    "product_sku": "cuatomizableoptionsproduct",
    "option_id": 2,
    "title": "my test option2",
    "type": "radio",
    "sort_order": 0,
    "is_require": true,
    "max_characters": 0,
    "image_size_x": 0,
    "image_size_y": 0,
    "values": [
      {
        "title": "frdfrrefgefff",
        "sort_order": 0,
        "price": 57,
        "price_type": "fixed",
        "sku": "htrhtyhuyjy",
        "option_type_id": 1
      }
    ],
    "extension_attributes": {}
  }
}
`
5. reindex and clear cache
6. Verify the options in front end of all websites.

![image](https://user-images.githubusercontent.com/60198231/155948680-206d7386-7e10-4082-97ba-fc11df142789.png)

![image](https://user-images.githubusercontent.com/60198231/155948760-c22d5996-9340-4d7c-a933-e4c0c41b3a34.png)

Kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.

**Comment by DipaliMarade** [comment] 2022-02-28 10:45
Hi

I think this is only to add custom options. 

But my issue is i am not able to add custom options under specific product store wise.
Consider product 10020 if i try to add custom options "Unit" under this product for spanish store they are also getting updated in all other stores.
API i am using is /us_sp/V1/products/SKU.

Request JSON

{

"product": {

"sku": "10020",
"name": "Maddox Breeze Cleaner &amp; Deodorizer Odor Eliminator Concentrate 1 Gal", 
"attribute_set_id": 4,
"price": 14.99,
"extension_attributes": {
  "stock_item": {
    "qty": 10,
    "is_in_stock": true,
    "use_config_manage_stock": true
  }
}

 ,
 "options": [
 {
 
    "product_sku": "10020",
    "title":"Unit",
    "type":"drop_down",
    "sort_order": 1,
    "is_require":1,
    "values": [
    {
        "title":"CS/4",
        "price":0,
        "price_type":"fixed",
        "sku":"CS/4",
        "sort_order": 1 
    },
    {
        "title":"One Each",
        "price":0,
        "price_type":"fixed",
        "sku":"One Each",
        "sort_order": 2 
    }
  ] 
 }
]
},
"saveOptions":true
}

**Comment by engcom-November** [comment] 2022-03-01 10:48
Verified the issue again on Magento 2.4-develop branch and the issue is reproducible:
Sent PUT request to /rest/[store-code]/V1/products/[sku] using below sample payload - Updated Price for Customizable options for only one store view - Issue: Price got updated for all stores
`
{

"product": {

"sku": "dwwdwdwd",
"name": "dwwdwdwd",
"attribute_set_id": 4,
"price": 32,
"extension_attributes": {
"stock_item": {
"qty": 3,
"is_in_stock": true,
"use_config_manage_stock": true
}
}

,
"options": [
{

"product_sku": "dwwdwdwd",
"title":"ewfedfed3ff",
"type":"drop_down",
"sort_order": 1,
"is_require":1,
"values": [
{
    "title":"frdref",
    "price":86,
    "price_type":"fixed",
    "sku":"bgbgfbfgb",
    "sort_order": 1 
}

]
}
]
},
"saveOptions":true
}
`

**Comment by engcom-November** [comment] 2022-04-28 07:48
Hi @DipaliMarade ,
We are closing this issue as there has been no latest update on the same. Kindly reopen/create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-04-28 07:48 UTC
Labels: Issue: Confirmed, Component: Api, Reproduced on 2.4.x, Priority: P2, Progress: done, Reported on 2.4.1, Area: APIs, Area: Product
