### ISSUE TITLE
Forcing from HTTPS back to HTTP not Logging In the Admin

### ISSUE THREAD

**Issue by rishabhchd19** [magento/magento2#24910] opened 2019-10-07 19:17 UTC
### Preconditions (*)

1. Magento CE 2.3.2 
2. PHP 7.2, HTTP- Port 80, HTTPS- Port 443

### Steps to reproduce (*)

1. Changed from Forced HTTPS> HTTP from Stores>Configuration 
2. Changed for both Admin and Front Store.

### Expected result (*)

1. Front End working perfectly with http://mydomain.com, opens the store page.
2. Admin Page should work and Logged In  on http://mydomain.com/admin, must open the dashboard.

### Actual result (*)

1. Front End Functions perfectly on https:// but Admin Page doesn't logged in when username & password is submitted. 
2. It changes from http://mydomain.com/admin > http://mydomain.com/admin/admin/index/index/key/xyzabcd   but doesn't open the dashboard. It redirects or stuck at Admin Login Page on submitting the credentials. 
3. Going back to Database admin and changing the value from 0 to 1 to bring HTTPS and dashboard back. Admin Panel now visible and can now access on https.

**Comment by engcom-Charlie** [comment] 2019-10-09 10:35
Hello @rishabhchd19 
We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.
I have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-10-09 10:35 UTC
Labels: Issue: Format is valid
