### ISSUE TITLE
Tier pricing on configurables inc/ex vat prices are the same value

### ISSUE THREAD

**Issue by PhilipRowe** [magento/magento2#33673] opened 2021-08-03 15:26 UTC
### Preconditions (*)

1. Magento 2.4.2-p1

### Steps to reproduce (*)

1. Go to Admin > Configuration > Sales > Tax 
2. Display settings > Display Product Prices In Catalog > set to: Including and Excluding Tax
3. Calculation settings > Catalog Prices > Set to: Including Tax
4. Setup tax rules so that prices have a tax amount showing
5. Go to a configurable product on the frontend with tier pricing setup

### Expected result (*)

1. Tier prices show Inc and Ex tax prices that are different

### Actual result (*)

1. Tier prices show Inc and Ex tax prices that are the same values
![image](https://user-images.githubusercontent.com/2877463/128041550-255e7419-8dd1-418f-ac9e-cb88a891af11.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

---

When pricing is set to display both and catalog prices include tax there is an issue where on configurable products tiered prices inc and ex vat prices are the same value (both inc)

vendor/magento/module-catalog/Pricing/Price/TierPrice.php getTierPriceList()
is: $exclTaxPrice = $this->calculator->getAmount($priceData['price'], $this->product, true);
should be: $exclTaxPrice = $this->calculator->getAmount($priceData['price'], $this->product);

The true param is meaning that the adjustments aren't being accounted for and therefore the price is always including vat

**Comment by engcom-November** [comment] 2021-08-09 07:32
Verified the issue on Magento 2.4-develop branch having B2B and EE Modules and the issue is reproducible:
**Steps to reproduce:**
1. Go to Admin > Configuration > Sales > Tax
Display settings > Display Product Prices In Catalog > set to: Including and Excluding Tax
Calculation settings > Catalog Prices > Set to: Including Tax
2. Setup tax rules so that prices have a tax amount showing (Stores - Taxes - Tax Zones and Rates, Tax Rules)
3. Go to a configurable product with tier pricing setup  (Catalog - Products - Configurable Product)
(Advanced Pricing - Enter Tier Price and save)
4. Or Create Simple product with Tier Price Setup - Create Configurations - Select Attribute - Generate Products and / under Actions - Choose Different Product - Select Simple Product having Tier Price setup and Save the Product
5 - Navigate to Frontend - Product Details page of Configurable Product
**Issue: Tier prices show Inc and Ex tax prices that are the same values
![image](https://user-images.githubusercontent.com/60198231/128672697-5ac7b161-1471-4450-8171-4d3deb39961f.png)

Note: This issue is not observed for Simple Products having no configurations:**
**Expected behavior:**
![image](https://user-images.githubusercontent.com/60198231/128671570-5266b0fa-e0f9-43d5-a390-340d3bdaf108.png)

**Comment by magento-engcom-team** [comment] 2021-08-09 07:34
:white_check_mark: Confirmed by @engcom-November 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-43022` were created

**Issue Available**: @engcom-November, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by karyna-tsymbal-atwix** [comment] 2021-08-12 07:31
@magento I am working on this

**Closed as completed** 2021-10-26 15:21 UTC
Labels: Issue: Confirmed, Component: ConfigurableProduct, Reproduced on 2.4.x, Priority: P1, Progress: done, Reported on 2.4.2-p1, Component: Frontend, Area: UI Framework

**Comment by engcom-November** [comment] 2022-09-14 11:51
Hi,
As I can see this issue got fixed in the scope of the internal Jira ticket AC-714 by the internal team 
Related commits: https://github.com/magento/magento2/search?q=AC-714&type=commits
Based on Jira, target version is 2.4.4
Thank you
