### ISSUE TITLE
Unable to place Order when logged in , Magento 2.1 v after commits

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#6053] opened 2016-08-08 16:29 UTC
Upgraded 2.0.7 to 2.1
invoice error and paypal error - unable to pay 
Did - ALTER TABLE `sales_invoice_grid`
    ADD COLUMN `base_grand_total` DECIMAL(12,4) NULL DEFAULT NULL COMMENT 'Base Grand Total' AFTER `grand_total`;

Fixed Invoice
PayPal Error - continues
then did changes from these commits - 65f263b, 7f5b644, 4173292, b110260, 0fff31d, 93402f5
Resolves Issue with paypal for payment action - Sale, authorization on Live paypal
Order - Does not work on Live paypal.
Sandbox - Authorization work but sale and order does not work.
But Main error comes up when a particular customer tries to order, the error shows up as unable to place order - irrespective of payment methods - paypal, cashondelivery,Authipay
Attaching images for reference
[Image 1](https://cloud.githubusercontent.com/assets/19605497/17401677/cbdc3a44-5a46-11e6-9117-8e25c5e2deab.png)
[image 2](https://cloud.githubusercontent.com/assets/19605497/17401682/d0b8d73e-5a46-11e6-8825-6bfab554204b.png)
[Image 3](https://cloud.githubusercontent.com/assets/19605497/17401693/e5d0db26-5a46-11e6-9894-7a20326e67a2.png)

**Comment by andimov** [comment] 2016-08-09 13:08
@nmallepally 
Thank you for reporting!
To allow us to research all issues, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by nmallepally** [comment] 2016-08-09 13:38
Magento 2.0.4 C.E installed
Updated to 2.0.7 C.E via Web Setup Wizard
Errors with paypal and translation Issues
Updated to 2.1 CE via composer
Invoice Error
Payment Errors - Unable to pay
Ran SQL query ALTER TABLE sales_invoice_grid
Fixed Invoice Error
Did Commits for paypal changes
Unable to pay Error on payment methods on Sandbox
Works on Live for paypal - sale and authorization action
Does not work Paypal - Order action
Gives Duplicate invoice Error/Paypal Error on a single customer when Logged in (same error occurred in 2.0.7 to different customer) does a payment.
Customer is able to order as guest but gives error when logged in after doing multiple Live test payments as Guest.

Steps to Reproduce
Update to 2.1 from 2.0.7 from composer
Do ALTER TABLE sales_invoice_grid Query
Enable Sandbox and try Payments
Then Enable live paypal and do Payments as user guest and logged in 
Payment action as order , authorization - gives Error when guest
Do commits
Error with Paypal Order payment action 
Do payments when same user logged in , gives error with any payment method.
Unable to Pay.

**Comment by alena-marchenko** [comment] 2016-08-29 14:36
Hi @nmallepally 

MAGETWO-54412 internal ticket is creating regarding this issue.
Closing this issue as duplicate of #4580 
Feel free to create new one if you experience other issues.

**Closed as completed by alena-marchenko** 2016-08-29 14:36 UTC
Labels: bug report
