### ISSUE TITLE
Classes that implement RouterInterface can return incorrect type

### ISSUE THREAD

**Issue by lenaorobei** [magento/magento2#27250] opened 2020-03-11 17:59 UTC
### Summary (*)
`Magento\Framework\App\RouterInterface::execute()` should return `ActionInterface` but in some cases implementation returns `false` or `null`.

### Examples (*)
`FrontController`:
``` php 
foreach ($this->_routerList as $router) {
    try {
        $actionInstance = $router->match($request);
        if ($actionInstance) { // <---- return type must evaluate to "false" for loop to continue
            $result = $this->processRequest();
            // ...
        }
    } catch (\Magento\Framework\Exception\NotFoundException $e) {
        // ...
    }
}
```

### Expected result

Need to refactor classes that extend `RouterInterface` in order to match interface return type.

The implementation should throw an exception instead of returning false or null.

See: https://github.com/magento/magento2/pull/26699

**Comment by gsomoza** [comment] 2020-03-12 12:03
I think there are two challenges here:

1. Any refactoring that will force the `ActionInterface` return type would cause a functionality BC break on any 3rd-party routers that were implemented following the bugged logic from core. Not sure of the real-life impact of that, but since those implementations had no option but to return falsey values to adapt to the improper `FrontController` logic, I'd personally consider it an important BC break.
2. `ActionInterface` by itself doesn't have enough semantics to allow for the skipping mechanics in `FrontController`. A few options I can think of:
    1. Replace the return type hint of `RouterInterface::execute()` to a new `MatchResultInterface`. Cleaner approach but the problem is that it's a hard BC break. Maybe it could be mitigated by not forcing the return type (stick to annotations) and adding a `RouterInterface::afterMatch()` Interceptor that would upgrade the legacy return types to the new return type.
    2. Create a new `NoRouteMatchedInterface` that extends from `ActionInterface` to allow for the skip mechanic. No BC break at interface level but the new interface (and resulting classes) would be polluted with the `ActionInterface` contract, especially the `execute()` method, which would hold no meaning in the context of that use-case.

I'd lean towards the clean approach with plugin, but hopefully there are better alternatives I'm not seeing? This is actually why I thought it might just be easier to just formalise the falsey return type in the short-term (as a first step / fast fix) and then break BC down the road.

**Comment by magento-engcom-team** [comment] 2020-12-02 14:13
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39547` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by lenaorobei** [comment] 2022-01-06 16:00
@magento five me test instance

**Comment by lenaorobei** [comment] 2022-01-06 16:02
@magento give me test instance

**Comment by lenaorobei** [comment] 2022-01-06 16:02
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2024-11-13 10:12
Hello @lenaorobei,

This issue is not relevant now as we do not have the `execute` method in the below interface:
https://github.com/magento/magento2/blob/651928c52166941ca64bfaec0bcaaf58ba8ab814/lib/internal/Magento/Framework/App/RouterInterface.php#L15

Hence closing this issue.

Thanks

**Closed as completed by engcom-Hotel** 2024-11-13 10:12 UTC
Labels: Issue: Confirmed, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P2, Severity: S2, Progress: done
