### ISSUE TITLE
Braintree expiry date placeholder incorrect

### ISSUE THREAD

**Issue by kieronthomas** [magento/magento2#8719] opened 2017-02-28 16:44 UTC
### Preconditions

1. Magento 2.1.4

### Steps to reproduce

1. Payment Method Braintree
2. Add item to cart
3. Navigate to checkout

### Expected result

1. Credit card expiry date placeholder should be 'YYYY' as that is what is expected

### Actual result

1.  Credit card expiry date placeholder is 'YY' which fails validation

**Comment by YevSent** [comment] 2017-03-01 09:08
Hi @kieronthomas, the current implementation of Braintree payment form based on [Braintree Hosted Fields](https://developers.braintreepayments.com/guides/hosted-fields/overview/javascript/v2), which allows specifying credit card expiration year in `YY` and `YYYY` [formats](https://developers.braintreepayments.com/guides/hosted-fields/overview/javascript/v2#demo).

Please, add more details (like browser console log, screenshots), I can't reproduce specified issue, all works as expected.

**Comment by kieronthomas** [comment] 2017-03-03 12:50
Hi joni-jones,

It's a very simple one, however it does confuse customers who expect to put in a two digit expiry year due to the incorrect placeholder - I've attached a screenshot. Also the line of code that needs changing in file

vendor/magento/module-braintree/view/frontend/web/js/view/payment/method-renderer/hosted-fields.js in getHostedFields: function () {

From:
                    expirationYear: {
                        selector: self.getSelector('expirationYear'),
                        placeholder: $t('YY')
                    }

To:

                    expirationYear: {
                        selector: self.getSelector('expirationYear'),
                        placeholder: $t('YYYY')
                    }

Kind regards,
Kieron
![two_digit_placeholder](https://cloud.githubusercontent.com/assets/25824951/23551707/ec7fa2b2-000f-11e7-88ea-8966ae38ca4e.png)

**Comment by YevSent** [comment] 2017-03-03 13:02
@kieronthomas, according to Braintree internal requirements, payment form implementation in Magento follows to be consistent with Hosted Fields form provided by Braintree, that's why the placeholder for expiration year is `YY`.

**Comment by kieronthomas** [comment] 2017-03-06 09:33
Hi Joni-jones,

Okay, thanks for the feedback. However as this is clearly a bug and causes a large number of customers to input a two digit year (obviously every delay / issue in the checkout risks dropoffs) - who do I go to raise this with?

Currently I have two clients who have raised this and I am overriding the entire hosted-fields.js which I'd rather not do!

Kind regards,
Kieron

**Comment by YevSent** [comment] 2017-03-06 09:49
Hi, @kieronthomas, this functionality is provided by Braintree, it's not a bug in Magento scope, even if you specify another placeholder, Braintree allows to use both formats.

If Braintree will change the expiration year validator and will support only one format, we also will change it for payment form.

You can create a ticket to Braintree support and describe your issue.

Now, it's expecting behavior and I'm closing this issue as not a bug.

**Closed as completed by YevSent** 2017-03-06 09:49 UTC
Labels: Progress: needs update, Component: Payment
