### ISSUE TITLE
incorrect db user

### ISSUE THREAD

**Issue by woakley** [magento/magento2#14264] opened 2018-03-22 14:18 UTC
Magento 2.2.3

Copied working site to a new account
changed DB detail in env.php
cleared var folder
recompile
redeploy

add image to product

### Expected result
image is added

### Actual result
SQLSTATE[42000]: Syntax error or access violation: 1142 TRIGGER command denied to user 'OLDUSER'@'localhost' for table 'catalog_product_entity_media_gallery', query was: INSERT INTO `catalog_product_entity_media_gallery` (`attribute_id`, `value`, `media_type`) VALUES (?, ?, ?)

Magento is trying to use the DB details from the old account even though I have cleared everything I can think of that might have contained these old details.

Everything else seems to work just as expected frontend and backend

**Comment by woakley** [comment] 2018-03-22 16:47
So what do I do to get G1 passed?

**Comment by dmanners** [comment] 2018-03-24 11:56
Hi @woakley you can use https://github.com/magento/magento2/wiki/Magento-Issue-Gates#gate-1---automatic-verification to see what needs to be in an issue report to get a G1 Pass. My guess is that as the issue is not using the complete issue template there are some parts that the system cannot pick up automatically.

**Comment by s-hoffman** [comment] 2018-03-27 17:53
Hi, I ran into this issue yesterday and determined the root cause.
Please see #14401 Trigger Removal on Mview Subscription Change

**Comment by woakley** [comment] 2018-03-27 19:50
Thanks both, really helpful :)

**Comment by magento-engcom-team** [comment] 2018-07-05 07:56
@woakley Closing this ticket then, as #14401 has more details.
Thanks.

**Closed as completed by magento-engcom-team** 2018-07-05 07:56 UTC
Labels: Issue: Format is not valid
