### ISSUE TITLE
Updating source quantity with an incorrect source code case causes UI failure

### ISSUE THREAD

**Issue by rmp135** [magento/magento2#33181] opened 2021-06-08 14:46 UTC
### Preconditions (*)

Magento 2.3.4

### Steps to reproduce (*)

1. Create an inventory source e.g. code "testsource".
2. Using the POST `/V1/inventory/source-items` API call, send a source item with a source code that does not match the case of the code created above e.g. "TestSource". This will return successfully.
3. Attempt to open the catalogue products screen.

### Expected result (*)
1. The product screen should open without error.
2. And, either the source with the same name but different case should be updated with the quantity provided. Or, it should match on the exact case. 

### Actual result (*)
1. When opening the product lookup, the following error is show.

`Notice: Undefined index: TestSource in /var/www/html/magento/vendor/magento/module-inventory-catalog-admin-ui/Ui/DataProvider/Product/Listing/Modifier/QuantityPerSource.php on line 127`

(Where TestSource is the source name).

This would indicate that data has become corrupted, and the product will be assigned against a source that does not exist. Technically, the above error fails attempting to retrieve a key from a dictionary and cannot find a match as the cases are different. 

---
- [ ✔️] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment] 2021-06-10 12:43
HI @ rmp135 
Unable to reproduce step 2 (from reproducible steps). Kindly provide sample API call with response.

**Comment by rmp135** [comment] 2021-06-10 13:01
Sure thing. Create a product with SKU "productsku" and a source with code "test" (all lowercase).

Then send the following to /V1/inventory/source-items (note the uppercase source_code).

```json
{
  "sourceItems": [
    {
      "sku": "productsku",
      "source_code": "TEST",
      "quantity": 1,
      "status": 1
    }
  ]
}
```
The request will succeed but attempting to view the product catalogue page will show an error.

**Comment by engcom-Echo** [comment] 2021-09-01 07:57
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment] 2021-09-01 07:59
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2021-09-02 10:27
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible:
Steps performed:
1. Admin - Stores - Inventory - Sources - Added new source with code "test"
2. Reindex and clear cache
3. Admin - Catalog - Products - Added new product "productsku" with test source assigned
4. Generate Admin access token using /rest/default/V1/integration/admin/token
5. Sent POST request to /rest/V1/inventory/source-items with code "TEST"

{
  "sourceItems": [
    {
      "sku": "productsku",
      "source_code": "TEST",
      "quantity": 1,
      "status": 1
    }
  ]
}
Front-end - Catalog page is displayed as expected. Product Details page for "productsku" displayed - No issue
Admin - Catalog - Products page is displayed as expected. productsku page is displayed as expected.
![image](https://user-images.githubusercontent.com/60198231/131827709-16496911-dd77-4412-abdb-a7d1c9f65938.png)

@rmp135 , kindly recheck the issue on latest Magento version /2.4-develop branch and provide missing steps if the issue is still reproducible.
Thank you

**Comment by engcom-Delta** [comment] 2021-09-15 09:31
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Closed as completed by engcom-Delta** 2021-09-15 09:31 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.3.4
