### ISSUE TITLE
GQL product query doesn't response for product that is set visibility as "Search"

### ISSUE THREAD

**Issue by adarshkhatri** [magento/magento2#36857] opened 2023-02-13 21:59 UTC
### Preconditions and environment

- Magento version : 2.4.4-p1
- Commerce (Community might be behaving same)

### Steps to reproduce

1. Create a product and set it's visibility to `search`
2. Query for GQL

```
query products(
    $filter: ProductAttributeFilterInput
    ) {
      products(
          filter: $filter
    ) {
        total_count
      items {
          type_id
          sku
          url_key
   }
}
````

Variable:

```
{
  "filter": {
      "sku": {
          "eq": "your-product-sku"
        }
  }
}
```

### Expected result

The response should have a product.

### Actual result

The response is empty.

### Additional information

It looks Magento adds `visibility as 2 and 4` by default while doing GQL query. It make sense when doing query for the category page. But how about the product detail page? 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by adarshkhatri** [comment] 2023-02-13 22:01
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by adarshkhatri** [comment] 2023-02-13 22:54
I was able to reproduce in above instance.

**Comment by engcom-Bravo** [comment] 2023-02-14 06:19
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-02-14 12:33
Hi @adarshkhatri,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

1.Create a product and set it's visibility to search
2.Query for GQL

<img width="1424" alt="Screenshot 2023-02-14 at 2 51 08 PM" src="https://user-images.githubusercontent.com/51680745/218739408-ab02f487-2bbb-4c5a-8f46-04f3deb068f8.png">


As per magento devdocs when we set to product visibility to `search` it will be found through search tool.

<img width="1104" alt="Screenshot 2023-02-14 at 2 52 28 PM" src="https://user-images.githubusercontent.com/51680745/218739678-93934302-8dde-4469-9985-3025b198da45.png">


Kindly go through with this document https://docs.magento.com/user-guide/v2.3/sales-channels/amazon/creating-assigning-catalog-products.html#create-a-multiple-catalog-products-using-their-amazon-listing-information and please let us know if you are still facing any issue.

Thanks.

**Comment by adarshkhatri** [comment] 2023-02-15 01:14
Isn't that the issue I reported that is `response has no product`?

**Comment by adarshkhatri** [comment] 2023-02-15 01:15
If this is expected, then what is the query should I run to take customer to `product detail page`?

**Comment by engcom-Bravo** [comment] 2023-02-16 09:51
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-02-16 11:31
Hi @adarshkhatri,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

Steps to reproduce

1.Create a product and set it's visibility to search

![Simpless-Products-Inventory-Catalog-Magento-Admin](https://user-images.githubusercontent.com/51680745/219352833-e3829abe-a217-4bfe-aaf0-5be09853d5fe.png)


We have used below query for a product when set visibility as "search".We got a response for a product.

```
{
  products(search: "Product SKU") {
    items {
      name
      sku
      url_rewrites {
        url
        parameters {
          name
          value
        }
      }
    }
  }
}

```

<img width="1423" alt="Screenshot 2023-02-16 at 2 55 47 PM" src="https://user-images.githubusercontent.com/51680745/219353223-88a0cacd-0690-49bb-addd-e4753aac9555.png">



Kindly let us know if we are still facing any issue.

Thanks.

**Comment by adarshkhatri** [comment] 2023-02-17 23:29
Above query would be for your search result page. 
now how will you take your customer to product detail page? You cannot rely on ‘search query’ to take your customer to PDP. 

The way we do it, we remove the “search” query and pass the SKU as a filter when taking to PDP.

**Comment by engcom-Bravo** [comment] 2023-02-22 06:43
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-02-22 14:07
Hi @adarshkhatri,

Thanks for your update.

As per Magento devdocs when we set visibility to `search`the product should be only searchable,and also we cannot find that product in categories kindly refer the attached video.



https://user-images.githubusercontent.com/51680745/220626105-a3485213-e9bb-488d-83f4-7d032b3b9bd0.mov



![ProductA-Products-Inventory-Catalog-Magento-Admin](https://user-images.githubusercontent.com/51680745/220626787-48e69c1d-0e96-47ab-ac09-a9263ed1b02b.png)




We have used below graphql query for a product when we set visibility to `search`.we got the response.


```
{
  products(
    search: "ProductA"
   
  ) {
    items {
      name
      sku
      price_range {
        minimum_price {
          regular_price {
            value
            currency
          }
        }
      }
    }
    total_count
    page_info {
      page_size
    }
  }
}
```


<img width="1414" alt="Screenshot 2023-02-22 at 2 34 28 PM" src="https://user-images.githubusercontent.com/51680745/220627106-b22efadd-60ac-424b-af80-850f95ddcf74.png">


Since the product is not showing an category page we cannot filter the product.Kindly let us know if you are still facing any issue.Please let us know if we missed anything.


Thanks.

**Comment by adarshkhatri** [comment] 2023-02-23 04:47
https://github.com/magento give me 2.4-develop instance

**Comment by adarshkhatri** [comment] 2023-02-23 04:50
@magento give me 2.4-develop instance

**Comment by adarshkhatri** [comment] 2023-02-23 05:41
Ok, I think we are going in circle. 
I agree with you on `search result page`. But I am trying to understand your approach for PDP. 

Below is the approach I am using for my storefront.

Have a look this URL: https://venia.magento.com/graphql?query=query+getProductDetailForProductPage%28%24urlKey%3AString%21%29%7Bproducts%28filter%3A%7Burl_key%3A%7Beq%3A%24urlKey%7D%7D%29%7Bitems%7Bid+uid+...ProductDetailsFragment+__typename%7D__typename%7D%7Dfragment+ProductDetailsFragment+on+ProductInterface%7B__typename+categories%7Buid+breadcrumbs%7Bcategory_uid+__typename%7D__typename%7Ddescription%7Bhtml+__typename%7Dshort_description%7Bhtml+__typename%7Did+uid+media_gallery_entries%7Buid+label+position+disabled+file+__typename%7Dmeta_description+name+price%7BregularPrice%7Bamount%7Bcurrency+value+__typename%7D__typename%7D__typename%7Dprice_range%7Bmaximum_price%7Bfinal_price%7Bcurrency+value+__typename%7Ddiscount%7Bamount_off+__typename%7D__typename%7D__typename%7Dsku+small_image%7Burl+__typename%7Dstock_status+url_key+custom_attributes%7Bselected_attribute_options%7Battribute_option%7Buid+label+is_default+__typename%7D__typename%7Dentered_attribute_value%7Bvalue+__typename%7Dattribute_metadata%7Buid+code+label+attribute_labels%7Bstore_code+label+__typename%7Ddata_type+is_system+entity_type+ui_input%7Bui_input_type+is_html_allowed+__typename%7D...on+ProductAttributeMetadata%7Bused_in_components+__typename%7D__typename%7D__typename%7D...on+ConfigurableProduct%7Bconfigurable_options%7Battribute_code+attribute_id+uid+label+values%7Buid+default_label+label+store_label+use_default_value+value_index+swatch_data%7B...on+ImageSwatchData%7Bthumbnail+__typename%7Dvalue+__typename%7D__typename%7D__typename%7Dvariants%7Battributes%7Bcode+value_index+__typename%7Dproduct%7Buid+media_gallery_entries%7Buid+disabled+file+label+position+__typename%7Dsku+stock_status+price%7BregularPrice%7Bamount%7Bcurrency+value+__typename%7D__typename%7D__typename%7Dprice_range%7Bmaximum_price%7Bfinal_price%7Bcurrency+value+__typename%7Ddiscount%7Bamount_off+__typename%7D__typename%7D__typename%7Dcustom_attributes%7Bselected_attribute_options%7Battribute_option%7Buid+label+is_default+__typename%7D__typename%7Dentered_attribute_value%7Bvalue+__typename%7Dattribute_metadata%7Buid+code+label+attribute_labels%7Bstore_code+label+__typename%7Ddata_type+is_system+entity_type+ui_input%7Bui_input_type+is_html_allowed+__typename%7D...on+ProductAttributeMetadata%7Bused_in_components+__typename%7D__typename%7D__typename%7D__typename%7D__typename%7D__typename%7D%7D&operationName=getProductDetailForProductPage&variables=%7B%22urlKey%22%3A%22penelope-peasant-blouse%22%7D


And https://venia.magento.com/penelope-peasant-blouse.html
As you see, for the PDP there the query:
`getProductDetailForProductPage($urlKey:String!)` 

and fitler by `url_key`:  `{"urlKey":"penelope-peasant-blouse"}` in the filter payload. 

With this fitler, the response is null.

**Comment by engcom-Bravo** [comment] 2023-02-23 12:18
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-02-23 14:01
Hi @adarshkhatri,

Thanks for your update.

We have created 3 products with visilibity to search.These products we cannot found in category.we tried using search tool.

<img width="1451" alt="Screenshot 2023-02-23 at 4 33 05 PM" src="https://user-images.githubusercontent.com/51680745/220925389-0794935d-527f-431b-9b68-c9cb8355a2a7.png">


We have used below query with filter input.We got response.

```
{
  products(
    search: "ProductA"
    filter: { sku: { eq: "ProductAAA" } }
  ) {
    items {
      name
      sku
      
      price_range {
        minimum_price {
          regular_price {
            value
            currency
          }
        }
      }
    }
    total_count
    page_info {
      page_size
    }
  }
}
```

<img width="1460" alt="Screenshot 2023-02-23 at 5 09 55 PM" src="https://user-images.githubusercontent.com/51680745/220926581-55ea2415-a971-4feb-8949-ce83fd254639.png">



Kindly let us know if we missed anything.

Thanks.

**Comment by adarshkhatri** [comment] 2023-02-23 21:41
You are using `search` for the `product query` in PDP. As we know `search query` may not give you the exact product. The search query is for catalog search. 

As you can see your own demo PWA link https://venia.magento.com/penelope-peasant-blouse.html it is not using `search query`

```
query getProductDetailForProductPage($urlKey:String!){
  products(
    filter:{
      url_key:{eq:$urlKey}
    }
  ){
    items{
      id
      uid 
      ...ProductDetailsFragment 
        __typename
    }
    __typename
  }
}
```


Can you confirm or point me to a Magento doc about the PDP page query approach to use `search` in a query?

**Comment by engcom-Bravo** [comment] 2023-02-24 09:17
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-02-24 12:48
Hi @adarshkhatri,

Thanks for your update.

We have tried below query using `search`.we got response for PDP page.


```
query {
  productDetail: products(
  search: "ProductA"
    filter: { sku: { eq: "ProductAAA" } }
  ) {
    total_count
    items {
      sku
      id
      name
      __typename
      price_range {
        minimum_price {
          regular_price {
            value
            currency
          }
        }
      }
      }
     
      }
      
          }
```


<img width="1510" alt="Screenshot 2023-02-24 at 3 02 07 PM" src="https://user-images.githubusercontent.com/51680745/221182070-65915b8c-468a-4934-97c6-6b3c3cce1f92.png">



As per Magento devdocs https://developer.adobe.com/commerce/webapi/graphql/schema/products/queries/products/#deprecated-output-attributes. filter with` url_key` is deprecated.

![products-query-Commerce-Web-APIs](https://user-images.githubusercontent.com/51680745/221182310-fca21ee1-8925-4bc3-aa54-60263764c6c1.png)




For url_key we have to use route query.Please check this document https://developer.adobe.com/commerce/webapi/graphql/schema/products/queries/route/.

<img width="1456" alt="Screenshot 2023-02-24 at 3 08 38 PM" src="https://user-images.githubusercontent.com/51680745/221182498-283d22eb-d683-4399-a946-ae894d8d45f4.png">



Kindly let us know if you are still facing any issue.

Thanks.

**Comment by adarshkhatri** [comment] 2023-02-25 06:44
I think we are going in circles. Please close the ticket if you think there is no problem. 
I have already patched our version.

**Comment by engcom-Bravo** [comment] 2023-02-27 12:40
Hi @adarshkhatri,

Thanks for your update.

As per latest comment https://github.com/magento/magento2/issues/36857#issuecomment-1445012602 we are closing this issue. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-02-27 12:40 UTC
Labels: Project: GraphQL, Issue: needs update, Reported on 2.4.4-p1

**Comment by oleksiyzestlogic** [comment] 2023-10-16 11:10
I have the same issue as @adarshkhatri. I think we should reopen task.


Maybe it's an issue from the PWA side and we should use another query, but for now it's `products` with `filter` still:

![image](https://github.com/magento/magento2/assets/91825064/63a22304-0044-4238-8ac6-b8c4dcc5e178)


Query is:
```
query getProductDetailForProductPage($urlKey:String!) {
	products(filter:{url_key:{eq:$urlKey}}) {
		items {
			...
		}
	}
}
```

And this query has build in filter by visibility and products with visibility "Search" ignored.

**Comment by BITS-Martin** [comment] 2024-08-27 16:10
> I think we are going in circles. Please close the ticket if you think there is no problem. I have already patched our version.

@adarshkhatri  how did you resolve the issue? We encounter the same problem in 2.4.5-p8 aswell.
