### ISSUE TITLE
UPS Logs not written to shipping.log file

### ISSUE THREAD

**Issue by sm7297** [magento/magento2#32361] opened 2021-03-04 12:08 UTC
### Preconditions (*)

1. Magento 2.3.4
2. PHP 7.2.30 (cli) (built: May 13 2020 11:09:42) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v10.2.0, Copyright (c) 2002-2018, by ionCube Ltd.
    with Zend OPcache v7.2.30, Copyright (c) 1999-2018, by Zend Technologies

### Steps to reproduce (*)

1. Set UPS Type under Shipping method UPS to United Parcel Service XML
2. Setting shown in the screen shot
![UPS_Logs_issue](https://user-images.githubusercontent.com/15437546/109961410-f696ee00-7d0f-11eb-9aaa-526579f57de1.png)

### Expected result (*)

1. Logs of request and response should be written to magento_root/var/log/shipping.log file

### Actual result (*)

1. No logs are written to magento_root/var/log/shipping.log which is written when using UPS Type : United Parcel Service
2. We are getting proper prices on frontend but we can't trace which prices we are getting in the logs

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sm7297** [comment] 2021-04-05 11:53
Can you anyone help me out figuring solution for this issue.

**Comment by engcom-November** [comment] 2021-06-15 13:04
Verified the issue on latest Magento version 2.4.2 and the issue is reproducible.
Steps performed:
1. Configured UPS Delivery method from Magento Admin (Stores - Configuration - Sales - Delivery Methods - UPS)
2. Front-End - Add product to Cart
3. Checkout - US Shipping address - Select UPS shipping method and submit payment.
4. Verify Shipping.log in Magentofolder/var/log
Issue: Cannot able to trace UPS prices from the logs.
![image](https://user-images.githubusercontent.com/60198231/122057284-14dcb180-ce08-11eb-8709-fb9d789c0dbd.png)

Test UPS configuration:
![image](https://user-images.githubusercontent.com/60198231/122057452-46ee1380-ce08-11eb-9763-82ad9b872243.png)
![image](https://user-images.githubusercontent.com/60198231/122057512-55d4c600-ce08-11eb-9ce9-ab93d9c77531.png)

**Comment by magento-engcom-team** [comment] 2021-07-18 04:18
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42870` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rmsundar1** [comment] 2021-07-25 09:41
@magento I am working on this

**Comment by rmsundar1** [comment] 2021-07-25 09:42
@magento add to contributors team

**Comment by rmsundar1** [comment] 2021-07-25 11:23
@magento I am working on this

**Comment by rmsundar1** [comment] 2021-07-25 15:14
@sdzhepa @magento This seems to be resolved part of MC-23024
https://github.com/magento/magento2/commit/7bf378335784b35c66fcf71cce1db2be2399c907

**Comment by engcom-Alfa** [comment] 2022-03-11 13:44
Hi @sm7297 Thanks for your contribution
Tried to reproduce the issue once again in the latest _Magento 2.4-develop_ instance, not able to reproduce at all.
1. Admin side: Configured UPS details at via Stores->Configuration->Sales->Shipping Methods->UPS.
2. Placed an order for a product successfully via UPS shipping method.
3. Cross checked **_shipping.log_** file inside **_var/log/_** folder.

We are noticing the generated log file accordingly with its content successfully.

The issue might have fixed along with any other code PR updates. So, I am closing this issue as off now considering above @rmsundar1 's comment as well.
Kindly re-test again your end in the latest _Magento 2.4-develop_ instance. If the issue is still reproducible, you can re-open the same ticket with all detailed information about the issue like _steps by steps to reproduce_, _what is the actual issue_, _what is expected_ and relevant _screenshots/ docs/ screen records_ as such! Or you may report a fresh issue as well.
Thanks

@rmsundar1, thanks for your collaboration regarding this issue!

**Closed as completed by engcom-Alfa** 2022-03-11 13:44 UTC
Labels: Component: Shipping, Issue: Confirmed, Reproduced on 2.4.x, Priority: P1, Progress: done, Reported on 2.3.4, Area: Shipping
