### ISSUE TITLE
Swatch virtual products don't refresh advanced pricing

### ISSUE THREAD

**Issue by Pictick** [magento/magento2#27438] opened 2020-03-25 16:24 UTC
#25359 # Preconditions (*)

### Steps to reproduce (*)

1. Add a configurable product
2. Create configurations and add / connect two or more virtual products 
3. Use a swatch method (for example color swatch)
3. Use advanced pricing and add quantity prices for both virtual products
4. Open the product detail page of the configurable product
5. switch to one color

### Expected result (*)

1. virtual product will open and show advanced pricing for example "Buy 20 for €3.00 each and save 96%"

### Actual result (*)

1. virtual product doesn't show advanced pricing
2. If you switch to another virtual product within this configurable product, it works (but only if the price will be different to the first virtual product) Otherwise there is no refresh.
3. This problem does not happen when you use a dropdown attribute field. 

![Mar-25-2020 18-12-04](https://user-images.githubusercontent.com/62657535/77566047-67f5dc00-6ec5-11ea-8742-41ac7f64610f.gif)

Swatch attribute and different main prices: advanced pricing of the second virtual product is visible (but not at the first)

![Mar-25-2020 18-16-31](https://user-images.githubusercontent.com/62657535/77566076-70e6ad80-6ec5-11ea-9a75-1274a628a93a.gif)

Dropdown attribute and different main prices: advanced pricing is visible at both virtual products (as expected) 

![Mar-25-2020 18-19-29](https://user-images.githubusercontent.com/62657535/77566102-79d77f00-6ec5-11ea-923d-36f29386e717.gif)

Swatch attribute and the same main prices: no advanced pricing is visible

**Comment by Pictick** [comment] 2020-03-27 15:28
This issue doesn't exist on Magento 2.3.1. Somewhere between 2.3.2 and 2.3.4 was this error built into the code.

**Comment by engcom-Alfa** [comment] 2020-10-23 12:22
Hi @Pictick 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the latest 2.4-develop branch by provided steps.
Looks like, it was already fixed by PR #29137. ( see [QA Report](https://github.com/magento/magento2/pull/29137#issuecomment-659335010) ).

**Actual Result:** :heavy_check_mark: virtual product will open and show advanced pricing for example "Buy 2 for $90 each and save 10%"

![Peek 2020-10-23 15-11](https://user-images.githubusercontent.com/51679138/97002686-fce7b300-1542-11eb-9be0-6d07d74fe15a.gif)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. 
Thanks for your report!

**Closed as completed by engcom-Alfa** 2020-10-23 12:22 UTC
Labels: not-confirmed, Event: MageCONF CD 2020
