### ISSUE TITLE
Magento 2.3.2- Orders in Processing state when creating Orders with multiple simple products and one bundle product

### ISSUE THREAD

**Issue by mangamuri** [magento/magento2#25522] opened 2019-11-08 00:38 UTC
### Preconditions (*)

1. Magento 2.3.2
2. We are  creating Order using Magento API's not from storefront 

### Steps to reproduce (*)

1. Add 2 simple products to cart
2. Add one Bundle product to cart
3. Create Order
4. View Order status - Order status is showing as Procesisng
5. Only one simple product is getting invoiced

### Expected result (*)

1. [Screenshots, logs or description]
2.  Order should be in Complete status and both simple products should invoiced

### Actual result (*)

1. [Screenshots, logs or description]
2. Order status is in Processing and only one simple product getting  invoiced

**Comment by mangamuri** [comment] 2019-11-08 00:39
@magento give me 2.3-develop instance ( 2.3.2 version)

**Comment by magento-engcom-team** [comment] 2019-11-08 00:39
Hi @mangamuri. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-08 00:39
Hi @mangamuri, here is your [Magento instance](https://i-25522-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25522-2-3-develop.instances.magento-community.engineering/admin](https://i-25522-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2019-11-08 04:46
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-08 04:46
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-08 04:46
Hi @ajijshekh123, here is your [Magento instance](https://i-25522-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25522-2-3-develop.instances.magento-community.engineering/admin](https://i-25522-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by osrecio** [comment] 2019-11-08 08:30
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-08 08:30
Hi @osrecio. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-08 08:31
Hi @osrecio, here is your [Magento instance](https://i-25522-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25522-2-3-develop.instances.magento-community.engineering/admin](https://i-25522-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ryanpalmerweb** [comment] 2019-11-08 10:04
Is this linked to the non-API version of the bug?
https://github.com/magento/magento2/issues/22246

**Comment by engcom-Echo** [comment] 2019-11-08 15:25
Hello @mangamuri
Thank you for contribution and collaboration!

I can't reproduce this issue on fresh Magento 2.3-develop and 2.3.3.
**Preconditions:**
Two simple products and one bundle product are created. Customer is created.

**Testing scenario:**
    1. Add one Bundle product to cart using API
    2. Create Order using API
    3. View Order status - Order status is showing as Procesisng (in admin panel)
    4.  Invoice order 
       **Result**: All products are invoiced

![invoiced](https://user-images.githubusercontent.com/51681435/68487882-9774b680-024c-11ea-8a73-5abb140f9cdd.png)

If you still faced this issue on `2.3-develop` please reopen this one or create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

So I have to close this issue. 
Thanks for your report!

**Closed as completed by engcom-Echo** 2019-11-08 15:25 UTC
Labels: Component: Sales, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Bundle

**Comment by mangamuri** [comment] 2019-11-08 16:49
@magento sorry

**Comment by mangamuri** [comment] 2019-11-08 16:51
@magento sorry for confusion , Thanks for looking into this. Actually in my comment i try to mention that I have two products in my cart  bundle product ( qty:1) and simple product (qty:2) , when i create order with api's i see only one simple product quantity getting invoiced and we using this with card payment.

Here are other things

- creating order with API's
- Order creating is using guest-carts only
- Order being paid with our payment partner  (CardConnect)

**Comment by engcom-Echo** [comment] 2019-11-11 16:03
Hello @mangamuri

Thank you for contribution and collaboration!

This is related with CardConnect is third party extension and not included in magento by default.
Please refer to the [CardConnect support](https://support.cardconnect.com/contact-support), for advice or general discussion about this issue.

So I have to close this issue.
Thanks for your report!

**Comment by davidrthomson** [comment] 2020-03-04 15:37
Hi,

We are experiencing this exact issue on Magento 2.3.2. What was the fix for this in the end? Was the conclusion that it is not reproducible in 2.3.3?

Thanks,

David
