### ISSUE TITLE
Show wrong popup in customer front page 

### ISSUE THREAD

**Issue by Vartikamish** [magento/magento2#34711] opened 2021-11-25 07:29 UTC
### Preconditions (*)

1. Platform: Ecommerce 
2. Mode: Developer/ production
3. Magento version: 2.4.2

### Steps to reproduce (*)

1. Log in to customer page.
2. Navigate to Create customer account> ![image](https://user-images.githubusercontent.com/94451028/143397672-dad544cf-2dd2-4349-a715-4ede8cb6deaa.png)

### Expected result (*)

1. [Screenshots, logs or description]
2. All popup should be remove after 2-3 sec.

### Actual result (*)

1. [Screenshots, logs or description]
2. Error Show: Bad request. One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error.
3. blob:https://web.whatsapp.com/73231d69-62a5-4362-abcc-d64fe658e461

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2021-11-25 10:37
Hello @Vartikamish,

We have tried to reproduce the issue in Magento 2.4-develop clean instance but it is not reproducible for us. We request you to please review the steps.

Also, we are unable to get the link mentioned in the **Actual Result** in the main description, please review:

> ### Actual result (*)
> 1. [Screenshots, logs or description]
> 2. Error Show: Bad request. One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error.
> 3. blob:https://web.whatsapp.com/73231d69-62a5-4362-abcc-d64fe658e461

Thanks

**Comment by dev-ajaysaini** [comment] 2021-11-29 09:35
@Vartikamish This issue is not related to Magento it seems like that you are using any custom module which creates issue.

**Comment by dev-ajaysaini** [comment] 2021-11-29 09:43
Duplicate issue #34712

**Comment by engcom-Delta** [comment] 2021-12-09 10:51
closing the issue as it is duplicate of #34712 .

**Closed as completed by engcom-Delta** 2021-12-09 10:51 UTC
Labels: Issue: needs update
