### ISSUE TITLE
2.4.2: Unique constraint violation found after saving CMS Page (subpage)

### ISSUE THREAD

**Issue by mikamarkus** [magento/magento2#33254] opened 2021-06-16 08:11 UTC
### Preconditions (*)

1. Magento Commerce Cloud v2.4.2

### Steps to reproduce (*)

1. Create and save a new CMS Page
2. Add page as other page's sub page in Page Hierarchy
3. Go edit the page you created and try to save - Error occurs

### Expected result (*)

1. User can save the page successfully without error

### Actual result (*)

Error message appears: "Unique constraint violation found"

Stack trace:

`<pre>#1 Magento\Framework\Model\AbstractModel->save() called at [vendor/magento/module-versions-cms/Observer/Backend/CmsPageSaveAfterObserver.php:216]
#2 Magento\VersionsCms\Observer\Backend\CmsPageSaveAfterObserver->createNewNode() called at [vendor/magento/module-versions-cms/Observer/Backend/CmsPageSaveAfterObserver.php:145]
#3 Magento\VersionsCms\Observer\Backend\CmsPageSaveAfterObserver->appendPageToNodes() called at [vendor/magento/module-versions-cms/Observer/Backend/CmsPageSaveAfterObserver.php:91]
#4 Magento\VersionsCms\Observer\Backend\CmsPageSaveAfterObserver->execute() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:88]
#5 Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:74]
#6 Magento\Framework\Event\Invoker\InvokerDefault->dispatch() called at [vendor/magento/module-staging/Model/Event/Manager.php:97]
#7 Magento\Staging\Model\Event\Manager->dispatch() called at [generated/code/Magento/Staging/Model/Event/Manager/Proxy.php:95]
#8 Magento\Staging\Model\Event\Manager\Proxy->dispatch() called at [vendor/magento/framework/Model/AbstractModel.php:829]
#9 Magento\Framework\Model\AbstractModel->afterSave() called at [vendor/magento/framework/EntityManager/Observer/AfterEntitySave.php:34]
#10 Magento\Framework\EntityManager\Observer\AfterEntitySave->execute() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:88]
#11 Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:74]
#12 Magento\Framework\Event\Invoker\InvokerDefault->dispatch() called at [vendor/magento/module-staging/Model/Event/Manager.php:97]
#13 Magento\Staging\Model\Event\Manager->dispatch() called at [generated/code/Magento/Staging/Model/Event/Manager/Proxy.php:95]
#14 Magento\Staging\Model\Event\Manager\Proxy->dispatch() called at [vendor/magento/framework/EntityManager/EventManager.php:51]
#15 Magento\Framework\EntityManager\EventManager->dispatchEntityEvent() called at [vendor/magento/module-staging/Model/Operation/Update.php:211]
#16 Magento\Staging\Model\Operation\Update->execute() called at [vendor/magento/framework/EntityManager/EntityManager.php:96]
#17 Magento\Framework\EntityManager\EntityManager->save() called at [vendor/magento/module-cms/Model/ResourceModel/Page.php:400]
#18 Magento\Cms\Model\ResourceModel\Page->save() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#19 Magento\Cms\Model\ResourceModel\Page\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#20 Magento\Cms\Model\ResourceModel\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#21 Magento\Cms\Model\ResourceModel\Page\Interceptor->___callPlugins() called at [generated/code/Magento/Cms/Model/ResourceModel/Page/Interceptor.php:23]
#22 Magento\Cms\Model\ResourceModel\Page\Interceptor->save() called at [vendor/magento/module-cms/Model/PageRepository.php:194]
#23 Magento\Cms\Model\PageRepository->save() called at [generated/code/Magento/Cms/Model/PageRepository/Interceptor.php:23]
#24 Magento\Cms\Model\PageRepository\Interceptor->save() called at [vendor/magento/module-cms/Model/PageRepository/ValidationComposite.php:71]
#25 Magento\Cms\Model\PageRepository\ValidationComposite->save() called at [generated/code/Magento/Cms/Model/PageRepository/ValidationComposite/Interceptor.php:23]
#26 Magento\Cms\Model\PageRepository\ValidationComposite\Interceptor->save() called at [vendor/magento/module-cms/Controller/Adminhtml/Page/Save.php:114]
#27 Magento\Cms\Controller\Adminhtml\Page\Save->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#28 Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#29 Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php:51]
#30 Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#31 Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#32 Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->___callPlugins() called at [generated/code/Magento/Cms/Controller/Adminhtml/Page/Save/Interceptor.php:23]
#33 Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#34 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:151]
#35 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#36 Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#37 Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#38 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#39 Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#40 Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->___callPlugins() called at [generated/code/Magento/Cms/Controller/Adminhtml/Page/Save/Interceptor.php:32]
#41 Magento\Cms\Controller\Adminhtml\Page\Save\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:186]
#42 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:118]
#43 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#44 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#45 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#46 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#47 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#48 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:263]
#49 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]
`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2021-06-17 10:28
Hi @mikamarkus ,

Verified the issue on Magento Commerce edition (2.4-develop) and the issue is not reproducible.
**Steps:**
1. Create new CMS page from admin (Content -> Pages -> Add new page)
2. Add this page as sub page of other's page in Page Hierarchy. (Content -> Hierarchy)
3. Open sub page -> Edit and Save - No issue: User is able to save the page
4. Open parent page -> Edit and Save - No issue: User is able to save the page

![image](https://user-images.githubusercontent.com/60198231/122379647-abce7880-cf84-11eb-8a0f-5d11b4bc3b35.png)

![image](https://user-images.githubusercontent.com/60198231/122379529-92c5c780-cf84-11eb-9ced-3348f16522d8.png)

![image](https://user-images.githubusercontent.com/60198231/122379451-7fb2f780-cf84-11eb-89b8-f21ab0fc8b2d.png)

**Comment by engcom-November** [comment] 2021-07-01 09:35
@mikamarkus , Can you please recheck and confirm if the issue is still reproducible. With above steps followed [mentioned in comment](https://github.com/magento/magento2/issues/33254#issuecomment-863124138), I'm not able to reproduce the issue. If the issue is still reproducible, please provide the missing steps if any.
Thank you.

**Comment by engcom-November** [comment] 2021-07-15 08:05
Hi @mikamarkus,
We are closing the issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-07-15 08:05 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.2

**Comment by sydekumf** [comment] 2021-07-20 12:55
We encountered this issue! Please reopen this ticket. 

Steps to reproduce:
- Create a CMS page and assign it to a hierarchy node (at least two hierarchy levels)
- Save it => Should work
- Save it again => Error because it doesn't recognize that the node already exists and wants to save it a second time in the table `magento_versionscms_hierarchy_node` which throws an unique constraint error.

The problem is this function which tries to identify if the node already exists or not: `\Magento\VersionsCms\Observer\Backend\CmsPageSaveAfterObserver::isNodeExist()`. It takes the `request_url` which is actually something like that: `second-leve/third-level`.
Inside the database the node actually has the request url like this `first-level/second-level/third-level`. Therefore it doesn't find the node inside the database and thinks it must be a new node.

**Comment by engcom-November** [comment] 2021-07-23 12:21
@sydekumf,
I rechecked the issue again on Magento 2.4-develop having EE modules installed with above mentioned steps but still not able to reproduce this issue:
**Steps performed:**
1. Admin - Stores – Settings – Configuration – General – Content Management – Enable CMS Page Hierarchy
2. Added nodes and child nodes (Admin - Content - Hierarchy - Add Node)
3. Created a CMS page and assigned it to a hierarchy node from Content - Pages - Add New Page
4. Save - No issue. Able to save the page
5. Saved it again - No issue
6. Edited the page again and saved - No issue

![image](https://user-images.githubusercontent.com/60198231/126780478-4ff9ce3c-53f5-489b-b8a6-a3230b4dbbcb.png)
![image](https://user-images.githubusercontent.com/60198231/126780506-e80cc3ad-d851-4e0f-8073-10a05cdd4ec7.png)
![image](https://user-images.githubusercontent.com/60198231/126780653-319da5f4-c703-4ad8-b37a-a5f44148bcb7.png)
@sydekumf, Can you please check the issue on Magento 2.4-develop having EE modules installed and create a new ticket if the issue is still reproducible.
Thank you.
