### ISSUE TITLE
PayPal payments declining

### ISSUE THREAD

**Issue by Vamshidhar2022** [magento/magento2#36477] opened 2022-11-14 23:08 UTC
### Preconditions and environment

- Magento version :2.3.5
-PayPal declining the credit card issue:
 The payment system was working fine before. Our client changed the PayPal password on Wednesday 9th November 2022.
And PayPal started declining the credit card payments from Friday 11th November 2022 onwards saying: "your payments has been declined. Please try again."
We didn't change any settings in Magento but still showing this error. It has been nearly a week affecting our client's sales. 
Can you please make it a high priority.

### Steps to reproduce

1. https://winestyleonline.com.au/
2. Click on VIEW ALL WINES category
3. Select a product
4. Go to check out page
-   Fill the shipping Address section 
-   Select the Shipping Methods
-   In Payment Methods: Select the Credit Card and enter the credit card details.
8. Click on place an order button and then 
![Checkout page](https://user-images.githubusercontent.com/110363474/201785174-419330ce-fdcb-446b-a30e-fb6df157ec0e.png)
and we will get the error 
![Error Payment](https://user-images.githubusercontent.com/110363474/201785607-33c383df-9866-45be-9e17-2e1c28a436cf.jpg)

### Expected result

Order has been placed successfully and should redirect to success page.

### Actual result

Your payment has been declined. Please try again.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-11-15 03:37
Hi @Vamshidhar2022 ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance with below steps performed but the issue is not reproducible.
Steps performed:
1. Configured PayPal Payflow Pro payment method in Sandbox mode with credit card payment enabled.
2. Front-end Placed Order with existing paypal CC credentials -No issue. Placed order successfully.
3. Configured PayPal express checkout with sandbox mode
4. Front-end placed order with existing paypal credentials - No issue. Order placed successfully.
5. Verified the same with new PayPal credentails - No issue. Order placed successfully.
Kindly recheck the issue on Magento 2.4-develop instance as it is the upcoming 2.4.x release and have latest code base. Elaborate steps / configuration details / 3rd party modules/extensions enabled if you are still facing any issues.
Thank you.

**Comment by Vamshidhar2022** [comment] 2022-11-15 03:50
Hi Girija Bhavani,
Thank you very much for looking into this issue.
We have magento 2.3.5 version and express check out is working fine.
Only the below option is selected then the credit card decline is coming up. Below is the test card details.
***@***.***
But when I put the right details it will give me this error:

***@***.***

Thanks,
Vamshi

**Comment by engcom-November** [comment] 2022-11-16 07:14
Hi @Vamshidhar2022 , Thank you for the response. 
Magento 2.3.x reached end of support in September 2022. Adobe no longer provide support to fix the issues in Magento 2.3.x versions. Kindly upgrade your instance with the latest Magento 2.4.x version / recheck in 2.4-develop instance as it the upcoming 2.4.x release and have latest code. Please provide missing steps / third party modules / extensions enabled if any / test configuration / card details used if you are still facing any issues.
Thank you.

**Comment by Vamshidhar2022** [comment] 2022-11-16 21:30
Hi Girija,
Thanks for the reply.
We have fixed it now. The reason is related to PayPal account itself. We added another account in PayPal manager and got the API credentials and it is working fine now.
Thanks for your time.
Kind Regards,
Vamshi

**Comment by engcom-November** [comment] 2022-11-17 06:30
Thank you for the response @Vamshidhar2022 . As the issue is with the PayPal account and not with Magento, we are closing this issue. Kindly create new issue if you face any issues.
Thank you.

**Closed as completed by engcom-November** 2022-11-17 06:30 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
