### ISSUE TITLE
Internet explorer issue:Default billing/shipping address not showing

### ISSUE THREAD

**Issue by renard123** [magento/magento2#27370] opened 2020-03-20 10:19 UTC
Internet explorer issue:Default billing/shipping address not showing

### Preconditions (*)
Magento: 2.3.3

### Steps to reproduce (*)
Admin -> Customers -> Edit any customers -> Addresses 

### Expected result (*)
It should display

### Actual result (*)
Billing/shipping address not showing

**Comment by krishprakash** [comment] 2020-03-20 10:31
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-20 10:31
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-03-20 10:31
Hi @krishprakash, here is your [Magento instance](https://i-27370-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27370-2-4-develop.instances.magento-community.engineering/admin_e87a](https://i-27370-2-4-develop.instances.magento-community.engineering/admin_e87a)
Login: `cc97e135` Password: `54e9d883ebe7`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2020-03-20 10:39
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32611` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krishprakash** [comment] 2020-03-20 10:41
Reproduced on Internet Explorer 11:

![image](https://user-images.githubusercontent.com/46617848/77156433-5e373780-6ac5-11ea-82b4-a60318d2dff3.png)

**Comment by vasilii-b** [comment] 2020-03-20 16:07
I'll have a look on it

**Comment by vasilii-b** [comment] 2020-03-21 16:39
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-21 16:39
Hi @vasilii-b. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-03-21 16:40
Hi @vasilii-b, here is your [Magento instance](https://i-27370-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27370-2-4-develop.instances.magento-community.engineering/admin_87dd](https://i-27370-2-4-develop.instances.magento-community.engineering/admin_87dd)
Login: `a53fd68c` Password: `063f8373fa7d`
Instance will be terminated in up to 3 hours.

**Comment by vasilii-b** [comment] 2020-03-21 16:54
The issue has been reproduced and it seems the problem is in the KO, specifically in 
https://github.com/magento/magento2/blob/a95a465a0acd43d4b5b1d2b9644b170145b90f3c/app/code/Magento/Customer/view/adminhtml/web/template/default-address.html#L23

I'll work on a PR for this.

**Comment by magento-engcom-team** [comment] 2020-05-01 01:18
Hi @renard123. Thank you for your report. 
The issue has been fixed in magento/magento2#27383 by @vasilii-b in 2.4-develop branch
Related commit(s):
 - [9a8d94d6600a1802813b9a990e448b957ca391d0](https://github.com/magento/magento2/commit/9a8d94d6600a1802813b9a990e448b957ca391d0)
 - [2ad68314bb7771ef1a552d23c39e31724ededda9](https://github.com/magento/magento2/commit/2ad68314bb7771ef1a552d23c39e31724ededda9)

The fix will be available with the upcoming 2.4.0 release.

**Closed as completed by magento-engcom-team** 2020-05-01 01:18 UTC
Labels: Issue: Ready for Work, Component: Customer, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Backend, Reproduced on 2.4.x, Fixed in 2.4.x, Reported on 2.3.3
