### ISSUE TITLE
Wrong order amount on dashboard on Last orders listing when order has discount and it is partially refunded

### ISSUE THREAD

**Issue by rav-redchamps** [magento/magento2#21281] opened 2019-02-16 05:06 UTC
### Preconditions (*)

1. Magento version 2.3.0

### Steps to reproduce (*)

1. Add a product with quantity 3 to Cart
2. Create a 10% discount coupon from admin and apply it to the cart
3. Go to checkout and place order
4. Invoice the order from admin, if placed using the offline payment method
5. Create a credit memo for the order to refund 2 quantities out of 3
6. Now notice the "Total" column for order on the admin dashboard under "Last Orders" listing. The refunded discount amount on credit memo is not considered in the total.

### Expected result (*)

1. The refunded discount amount on credit memo **should be** considered in the total column under "Last Orders" listing on the dashboard.

### Actual result (*)

1. The refunded discount amount on credit memo **is not** considered in the total column under "Last Orders" listing on the dashboard.

**Comment by magento-engcom-team** [comment] 2019-02-16 05:06
Hi @rav-redchamps. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@rav-redchamps do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by rav-redchamps** [comment] 2019-02-16 05:24
Create a pull request https://github.com/magento/magento2/pull/21283 to fix this issue.

**Comment by magento-engcom-team** [comment] 2019-02-16 05:50
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment] 2019-02-16 05:50
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-16 05:50
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-16 05:51
Hi @shikhamis11, here is your [Magento instance](https://i-21281-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21281-2-3-develop.instances.magento-community.engineering/admin](https://i-21281-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-02-16 06:30
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98300` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rav-redchamps** [comment] 2019-02-16 06:43
Already fixed in pull request #21283

**Comment by magento-engcom-team** [comment] 2019-03-26 16:54
Hi @rav-redchamps. Thank you for your report. 
The issue has been fixed in magento/magento2#21283 by @rav-redchamps in 2.3-develop branch
Related commit(s):
 - [d79eb085cabfb16ed8f4432f5cd25b00cf3ba686](https://github.com/magento/magento2/commit/d79eb085cabfb16ed8f4432f5cd25b00cf3ba686)
 - [d1e71b96056f2b83d182c92120008837cd665b9f](https://github.com/magento/magento2/commit/d1e71b96056f2b83d182c92120008837cd665b9f)
 - [f893a925bbf5a92967a79509beefa4314b897f23](https://github.com/magento/magento2/commit/f893a925bbf5a92967a79509beefa4314b897f23)
 - [57c4db41be4281541fc0745bcfd4f6cbca64ef86](https://github.com/magento/magento2/commit/57c4db41be4281541fc0745bcfd4f6cbca64ef86)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-26 16:54 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Reports

**Comment by dmytro-ch** [comment] 2019-03-27 09:45
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-27 09:45
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-27 09:46
Hi @dmytro-ch, here is your [Magento instance](https://i-21281-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21281-2-2-develop.instances.magento-community.engineering/admin](https://i-21281-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-04-03 16:25
Hi @rav-redchamps. Thank you for your report. 
The issue has been fixed in magento/magento2#21944 by @eduard13 in 2.2-develop branch
Related commit(s):
 - [7d81b55eb5fd9b170dc6c6c0f60fd9bf4d12274e](https://github.com/magento/magento2/commit/7d81b55eb5fd9b170dc6c6c0f60fd9bf4d12274e)
 - [0cea56222c7c1ba0c361de223a1daf42c2e63fc6](https://github.com/magento/magento2/commit/0cea56222c7c1ba0c361de223a1daf42c2e63fc6)
 - [891e2e1e3afefae742e6c106c1252b881930242a](https://github.com/magento/magento2/commit/891e2e1e3afefae742e6c106c1252b881930242a)
 - [a54bba35bbc7716455bd72cfb72fd1939e9a3885](https://github.com/magento/magento2/commit/a54bba35bbc7716455bd72cfb72fd1939e9a3885)

The fix will be available with the upcoming 2.2.9 release.
