### ISSUE TITLE
UI grid inline edit not possible for all grid rows

### ISSUE THREAD

**Issue by FreekVandeursen** [magento/magento2#25457] opened 2019-11-04 09:05 UTC
### Preconditions (*)
1. Tested on Magento 2.3.3
2. Any UI grid that allows inline edits (e.g. CMS pages)

### Steps to reproduce (*)
1. Click any row to start inline editing
2. Click the row select checkbox on all other rows

### Expected result (*)
1. Inline editing enabled on all rows

### Actual result (*)
1. Inline editing is enabled on all rows, except the last selected row

From my testing it seems this only occurs when literally all rows are selected, not just all visible rows. For example: on a clean installation there are 4 CMS pages. When selecting all 4 rows, this bug occurs. But when first setting the page size to 2, the bug does not occur when selecting the 2 visible rows.

**Comment by FreekVandeursen** [comment] 2019-11-04 09:05
@magento give me 2.3-develop instanc

**Comment by FreekVandeursen** [comment] 2019-11-04 09:09
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-04 09:09
Hi @FreekVandeursen. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-04 09:09
Hi @FreekVandeursen, here is your [Magento instance](https://i-25457-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25457-2-3-develop.instances.magento-community.engineering/admin](https://i-25457-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-11-04 09:27
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22734` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Karlasa** [comment] 2019-11-05 07:26
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-05 07:26
Hi @Karlasa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-05 07:26
Hi @Karlasa, here is your [Magento instance](https://i-25457-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25457-2-3-develop.instances.magento-community.engineering/admin](https://i-25457-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by kkorushkin** [comment] 2019-11-25 09:02
Hi @FreekVandeursen. Please take a look at my record - it's clean 23-develop with sample data (there are 6 cms pages by default). I've played with all this grids and all seems to be ok. Confirm if i got you right.
![ui-grid](https://user-images.githubusercontent.com/13004402/69480881-3d5f1e00-0e14-11ea-9460-006d8a27487c.gif)

**Comment by sathish1228** [comment] 2019-11-25 13:00
Sir,

Issue is in my system and I a could not figure it out. Here is the
screenshot of one the screen with the issue I mentioned. Please let me know
if you can look at it if I give you login details.

[image: image.png]

Your help is much appreciated.

**Comment by sathish1228** [comment] 2019-11-25 13:51
one more screen
[image: image.png]

**Comment by kkorushkin** [comment] 2019-11-25 15:44
@sathish1228 i'm only see [image: image.png] and no image related. Could you please edit your comment.

**Comment by sathish1228** [comment] 2019-11-25 16:15
Attached the screenshot.

**Comment by FreekVandeursen** [comment] 2019-11-26 08:42
Hello @kkorushkin 

You are following a slightly different path from how I ended up finding this bug.

What you are doing:
1. Click a line to start inline edit
2. Click cancel on inline edit
3. Select multiple checkboxes
4. Select Edit in the mass action dropdown

What I did:
1. Click a line to start inline edit
2. Don't click cancel
3. Click additional checkboxes to select multiple lines

I think you will be able to reproduce the issue that way

**Comment by sathish1228** [comment] 2019-11-26 11:16
No, we are not on the same page.

I am not doing any edits. I am just not able to see any records but see
only the count. Results grid is not visible but total records count is
showing. Please look at the screenshot i sent in the previous comments.

**Comment by sathish1228** [comment] 2019-11-26 13:06
I just try to open "Index Management" page see the below/attached screen.

**Comment by kkorushkin** [comment] 2019-11-27 08:09
@FreekVandeursen i can't solve this issue so i quit, sorry. This ticket needs someone with strong knockout.js background and I'm not the one.

**Comment by sathish1228** [comment] 2019-11-27 13:39
It's ok. Can you please forward this to anyone you knew?

**Comment by sdzhepa** [comment] 2020-08-04 21:55
We are not able to reproduce this issue on the latest `2.4-develop` code
It seems was already fixed in the scope of another issue/task/PR

**Closed as completed by sdzhepa** 2020-08-04 21:55 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Ui, Component: Backend

**Comment by cralls** [comment] 2020-08-10 19:49
I'm having the exact same issue as described here on 2.3.3
