### ISSUE TITLE
Can't figure out how to customize "new address" form in checkout

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#31837] opened 2021-01-26 12:07 UTC
### Summary (*)

I need to add a little text here (see screenshot):

![image](https://i.stack.imgur.com/ty6A9.png)

I can't figure out how this is done. I read through the section "Customize Checkout" in the documentation, but there is nothing helpful which points me in the right direction.

I know that the form can be addressed under this UiComponent path:

    checkout.steps.shipping-step.shippingAddress.billing-address-form

But what steps are required to add my changes? There is no template for this

### Examples (*)

-
### Proposed solution

Add more examples to the documentation to teach us how we can customize the checkout.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dverkade** [comment] 2021-04-18 20:11
Posting a comment. Issues should not be automatically closed.

**Comment by engcom-Lima** [comment] 2021-06-09 13:27
Hi @Eddcapone 

Unfortunately, Can't reproduce the issue.

Can you please provide me more details about the ticket and reproducible steps?

**Comment by engcom-Lima** [comment] 2021-06-17 09:28
Hi @Eddcapone, It is not an issue. hence closing this ticket.

Thanks

**Closed as completed by engcom-Lima** 2021-06-17 09:28 UTC
Labels: non-issue, Triage: Dev.Experience, Issue: needs update

**Comment by Eddcapone** [comment] 2021-06-18 07:10
@engcom-Lima, why it is not an issue? It is a dev experience issue
