### ISSUE TITLE
Persistent Shopping Cart: Customer logged back in after logging out

### ISSUE THREAD

**Issue by ktruehl** [magento/magento2#3997] opened 2016-04-04 15:37 UTC
## Steps to reproduce
1. Install Magento version 2.0.3 or 2.0.4.
2. Enable and configure the persistent shopping cart feature.
3. Set the "Clear Persistence on Sign Out" setting in the "Persistent Shopping Cart" section to "No".
4. Create customer
5. Clear sessions (delete var/sessions)
6. Log customer in
7. Log customer out
8. Wait for automatic redirect after logout
## Expected result
1. After logging out the customer menu should not be displayed anymore. Instead the "Sign in" or "Create account" links should be shown in the header.
## Actual result
1. On the logout success page, the "Sign in" or "Create account" links are correctly shown in the header. In addition the default welcome message is shown instead of "Welcome [customer name]". However, after an AJAX udpate the welcome message changes back to "Welcome [customer name]".
2. After automatic redirect to the home page, the customer menu is shown again together with the "Welcome [customer name]" message.

I observed this on Magento 2.0.3 and 2.0.4.

**Comment by ksz2013** [comment] 2016-04-04 16:31
Hi,

Aren't you having customer creation and login problems on 2.0.4? All the time i am being redirected to login page, without anu message.

**Comment by ktruehl** [comment] 2016-04-04 16:46
No. Otherwise logging in and creating customers works as expected. And if the "Clear Persistence on Sign Out" system config parameter is set to "Yes", logging out works correctly as well.

**Comment by piotrekkaminski** [comment] 2016-06-09 18:51
@ktruehl do you see the same on 2.1RC1? I was not able to reproduce.

**Comment by ktruehl** [comment] 2016-06-10 11:44
Hi @piotrekkaminski,

I just tested it on RC2, and I wasn't able to reproduce it.

However, I found another bug. :) After logging out, the "Welcome ..." message stays in the header, which is OK, since it is followed by the "not you?" link. However, to get rid of your name in the header altogether, clicking the "not you?" link does not suffice. Only after clicking on it a second time (after the page has finished loading) does the welcome message disappear.

**Comment by pantaoran** [comment] 2016-07-13 06:31
@ksz2013 that sounds a lot like what's been discussed in #3572

**Comment by apurv-anand** [comment] 2016-09-25 10:30
This is the exact behavior that we are facing on M2.1.1

**Comment by SerhiyShkolyarenko** [comment] 2016-09-29 14:48
@ktruehl @apurv-anand 
I didn't reproduce on latest develop branch. Do you have the same settings for persistent shopping cart?
![persistent_cart_options](https://cloud.githubusercontent.com/assets/15108140/18958906/f4d1d5ce-866c-11e6-8de4-7a08333c6720.png)

**Comment by SerhiyShkolyarenko** [comment] 2016-10-27 09:12
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by SerhiyShkolyarenko** 2016-10-27 09:12 UTC
Labels: bug report, Progress: needs update
