### ISSUE TITLE
Category search API giving null response

### ISSUE THREAD

**Issue by nandigowda-zz** [magento/magento2#27557] opened 2020-04-03 06:49 UTC
### Preconditions (*)

1. Magento 2.3.3
2. Elastic search 6.5 

### Steps to reproduce (*)

1. API - Request
 {{local-url}}/rest/default/V1/categories/list?searchCriteria[filterGroups][0][filters][0][field]=name&searchCriteria[filterGroups][0][filters][0][value]=%beaurer%&searchCriteria[filterGroups][0][filters][0][conditionType]=like

2. Hit the API in postman

### Expected result (*)

1. Proper data or No search result should come like this
{
    "items": [],
    "search_criteria": {
        "filter_groups": [
            {
                "filters": [
                    {
                        "field": "name",
                        "value": "%beaurer%",
                        "condition_type": "like"
                    }
                ]
            }
        ]
    },
    "total_count": 0
}
2. If category found , result should come.

### Actual result (*)

1. API giving null response.

2. If value is "zz" then no response data is coming properly but when i entered value "beaure" null is coming.

**Comment by luanalves** [comment] 2020-04-04 13:19
Hi @nandigowda the problem isn't Magento , the problem is Postman because don't escape automatically .
This resolution the problem is Right-click selected text, and choose EncodeURIComponent to manually encode a parameter value.
Example: https://learning.postman.com/docs/postman/sending-api-requests/requests/#sending-parameters
Parameters:
{{local-url}}/rest/default/V1/categories/list?searchCriteria[filterGroups][0][filters][0][field]=name&searchCriteria[filterGroups][0][filters][0][value]=%25beaurer%25&searchCriteria[filterGroups][0][filters][0][conditionType]=like

Result:
{
    "items": [],
    "search_criteria": {
        "filter_groups": [
            {
                "filters": [
                    {
                        "field": "name",
                        "value": "%beaurer%",
                        "condition_type": "like"
                    }
                ]
            }
        ]
    },
    "total_count": 0
}

**Comment by rodrigowebjump** [comment] 2020-04-04 13:44
Thanks @luanalves 

@nandhini-nagaraj I am closing this issue. You can reopen the issue if needed.

Thanks

**Closed as completed by rodrigowebjump** 2020-04-04 13:44 UTC
Labels: Issue: Format is valid, Event: Global-Contribution-Day, Reported on 2.3.3
