### ISSUE TITLE
unable to add images in wysiwyg editor

### ISSUE THREAD

**Issue by vini1996** [magento/magento2#22948] opened 2019-05-20 10:58 UTC
### Preconditions (*)
1. Magento 2.2.7
2. php 7.14

### Steps to reproduce (*)

1.  catalog -> products -> Add product -> content -> Insert Image

### Expected result (*)

1. image URL should be generated and the image will display.
![expected2](https://user-images.githubusercontent.com/39683802/58016619-b440f480-7b1b-11e9-86ad-c5adbe939e26.png)
![expected3](https://user-images.githubusercontent.com/39683802/58016627-ba36d580-7b1b-11e9-9118-6f6743ef823f.png)
![expected 1](https://user-images.githubusercontent.com/39683802/58016585-9a9fad00-7b1b-11e9-971c-b44466b38d10.png)

### Actual result (*)

1. URL is not generating And image also not displaying 
![actual2](https://user-images.githubusercontent.com/39683802/58016671-ddfa1b80-7b1b-11e9-95b5-0f2a16868fc2.png)
![actual 1](https://user-images.githubusercontent.com/39683802/58016664-d9cdfe00-7b1b-11e9-935c-21c890316e46.png)

in localhost, all the things are working fine, but in the server, it is not working.

**Comment by ajijshekh123** [comment] 2019-05-21 09:01
Give me @magento-engcom-team give me 2.3-develop instance.

**Comment by magento-engcom-team** [comment] 2019-05-21 09:01
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-05-21 09:02
Hi @ajijshekh123, here is your [Magento instance](https://i-22948-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22948-2-3-develop.instances.magento-community.engineering/admin](https://i-22948-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2019-05-21 09:13
Give me @magento-engcom-team give me 2.2-develop instance.

**Comment by magento-engcom-team** [comment] 2019-05-21 09:13
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-05-21 09:14
Hi @ajijshekh123, here is your [Magento instance](https://i-22948-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22948-2-2-develop.instances.magento-community.engineering/admin](https://i-22948-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2019-05-21 09:21
The issue does not reproduce in Magento 2.3 Instance:

See attached the screenshot:

![2 3_1](https://user-images.githubusercontent.com/24711761/58083994-acdf2100-7bd7-11e9-8dd3-67e6dc6abb26.png)

![2 3_2](https://user-images.githubusercontent.com/24711761/58083996-acdf2100-7bd7-11e9-84aa-85e1783c9491.png)

Issue reproduced in Magento 2.2 Instance.

See attached the screenshot:

![2 2_1](https://user-images.githubusercontent.com/24711761/58084037-c6806880-7bd7-11e9-82d5-b5e5a316badc.png)

![2 2_2](https://user-images.githubusercontent.com/24711761/58084038-c6806880-7bd7-11e9-9a3d-7deb6e04f2da.png)

**Comment by magento-engcom-team** [comment] 2019-05-21 09:22
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99777` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by AlexWorking** [comment] 2019-05-21 09:44
Dear @ajijshekh123. Please, next time, do not assign to Yourself issues for confirmation if they are already assign to somebody else. There are plenty of open unassigned issues You may chose among. Thank You.

**Comment by ajijshekh123** [comment] 2019-05-21 10:06
@AlexWorking - In this issue, you are not working for the last 22 hours that's why I have verified the issue.

**Comment by AlexWorking** [comment] 2019-05-21 14:02
@ajijshekh123 The matter is You can not know whether I'm working on the issue or not. You only can see when I make changes / adds to it. Please note these are not the same things. You may see If I have stoped working on a ticket as I will have unassigned it from myself, just for example, as You did it in #22925. You see I had not self-assigned that issue until You removed Your assignment. Lets respect each other. Thank You for for understanding.

**Comment by ajijshekh123** [comment] 2019-05-22 05:15
Okay,  Thanks.

**Comment by engcom-Charlie** [comment] 2019-08-02 08:39
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-08-02 08:39
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-08-02 08:39
Hi @engcom-Charlie, here is your [Magento instance](https://i-22948-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22948-2-3-develop.instances.magento-community.engineering/admin](https://i-22948-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment] 2019-08-02 08:42
Hello @vini1996 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by engcom-Charlie** 2019-08-02 08:42 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Admin, Component: Framework/Wysiwyg
