### ISSUE TITLE
Single-Store Mode: Can't view new CMS Pages (Content > Pages)

### ISSUE THREAD

**Issue by vseager** [magento/magento2#33395] opened 2021-06-30 14:48 UTC
If the site is set to `Single Store Mode`, when you create a new CMS page, the URL rewrite is not added to the rewrite table and therefore the page is not accessible via the `URL Key` set in the admin.

### Preconditions (*)

1. Magento 2.4.2-p1
2. Brand new Magento installation, Luma theme

### Steps to reproduce (*)

1. Go to `Stores > Configuration > General > Single-Store Mode`
2. Set "Enable Single-Store Mode" to `Yes`
3. Go to `Content > Pages` and create a new page
4. Clear cache and try to view new page on the frontend
5. Go to `Marketing > URL Rewrites` (or the `url_rewrite` table in the database) and check for the URL Key

### Expected result (*)

1. The new page is accessible via the URL key

### Actual result (*)

1. The new page is not accessible via the URL key or the "target path" (cms/page/view/page_id/7)
2. There are no entries in the `url_rewrite` table for the new page
3. There is also no entry in the `cms_page_store` table for the new page

![screenshot-2021 06 30-15_37_29](https://user-images.githubusercontent.com/2035088/123980626-98c29c00-d9b9-11eb-8b32-a980ef652cdf.png)

![screenshot-devops-2021 06 30-15_35_59](https://user-images.githubusercontent.com/2035088/123980623-97916f00-d9b9-11eb-9897-7608655ab0cc.png)

![screenshot-devops-2021 06 30-15_34_49](https://user-images.githubusercontent.com/2035088/123980631-995b3280-d9b9-11eb-983a-74a0e89c5dfc.png)

I've set a severity of **S0** as there is no user workaround that I am aware of without adding the new page to the `cms_page_store` table directly in the database. Disabling "Single-Store Mode" would be a workaround but the ability to add new pages and content would be a critical part of most users' workflow, meaning that this issue makes the "Single-Store Mode" unusable/not fit for purpose without a fix.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2021-07-01 08:51
Verified the issue on both Magento versions 2.4.2-p1 and 2.4-develop and the issue is not reproducible:
**Steps performed:**
1. Admin -> Go to Stores > Configuration > General > Single-Store Mode
2. Set "Enable Single-Store Mode" to Yes
3. Go to Content > Pages and create a new page
4. Clear cache and try to view new page on the frontend
**No issue: I'm  able to access newly created page on Frontend using both URL Key and target path.** 
5. Go to Marketing > URL Rewrites (or the url_rewrite table in the database) and check for the URL Key - **Displayed**
**No issue: Entries are present in both url_rewrite and cms_page_store tables.**
select * from url_rewrite;
select * from cms_page_store;
![image](https://user-images.githubusercontent.com/60198231/124095058-f4069400-da76-11eb-9565-918492aef97c.png)

![image](https://user-images.githubusercontent.com/60198231/124095118-01238300-da77-11eb-9819-89e1ea7570e1.png)
![image](https://user-images.githubusercontent.com/60198231/124095201-13052600-da77-11eb-8ce7-27b14508619f.png)
@vseager, Can you please re-verify the issue again followed by reindex and clearing cache and confirm if this is still reproducible.

**Comment by engcom-November** [comment] 2021-07-15 08:01
Hi @vseager,
We are closing the issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-07-15 08:01 UTC
Labels: Component: Cms, Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.2-p1

**Comment by vseager** [comment] 2021-07-16 08:02
@magento give me 2.4-develop instance

**Comment by vseager** [comment] 2021-07-16 08:57
Tested and can't reproduce on 2.4-develop

**Comment by vseager** [comment] 2021-07-16 09:42
@magento give me 2.4.2-p1 instance
