### ISSUE TITLE
Vimeo video is not playing on frontend

### ISSUE THREAD

**Issue by TalibSaifi003** [magento/magento2#38567] opened 2024-04-02 13:39 UTC
### Preconditions and environment

Hii,
I am getting an issue with the Vimeo video.i have upload a vimeo video for the product.
But it's not playing on the frontend please refer to the loom video
https://www.loom.com/share/04a76fa7030c45b39c5fa64d92392885
our magento version is 2.4.2
please help us to fix it

### Steps to reproduce

getting issue on the product page 

### Expected result

video should be play on the storefront

### Actual result

it's continuously loadung

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-04-03 07:48
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-04-03 09:17
Hi @TalibSaifi003,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.




https://github.com/magento/magento2/assets/51680745/ac4c78e4-a522-469d-aa3e-3e9f181a922b



Video is playing on the frontend.

Kindly check the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible and check if any third party modules causing the issue.

Thanks.

**Comment by TalibSaifi003** [comment] 2024-04-04 12:39
Hii @engcom-Bravo 
are you checking issue on the 2.4.2 version.
because we are getting issue with 2.4.2,2.4.3-p1
can you please confirm.

**Comment by engcom-Bravo** [comment] 2024-04-05 05:34
Hi @TalibSaifi003,

Thanks for your update.

It is recommended to verify the issues in Latest Magento 2.4-develop instance and it might be possible issue has been fixed in Latest Magento 2-4-develop branch.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-04-16 05:09
Hi @TalibSaifi003,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-04-16 05:09 UTC
Labels: Issue: needs update, Reported on 2.4.2
