### ISSUE TITLE
Magento admin is not working or not able to changes

### ISSUE THREAD

**Issue by Shatchi** [magento/magento2#38954] opened 2024-07-19 11:31 UTC
### Preconditions and environment

- Magento version
- We tried to change the password in Magento admin and clicked on save changes, but not change the password and also redirected the page to my account, other options are not working, so please check.

### Steps to reproduce

.

### Expected result

Please solve the issue for admin.

### Actual result

We tried to change the password in Magento admin and clicked on save changes, but not change the password and also redirected the page to my account, other options are not working, so please check.

### Additional information

We tried to change the password in Magento admin and clicked on save changes, but not change the password and also redirected the page to my account, other options are not working, so please check.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2024-07-22 12:16
Hi @Shatchi 

Thanks for reporting and collaboration.

Verified the issue on Magento 2.4 dev instance but the issue is not reproducible.

we can change the password and the admin page is working as expected.

Please refer to the attached screen recording and let us know if we missed anything.


https://github.com/user-attachments/assets/89313149-d988-4de9-9da6-e2f1c51f9d02

**Comment by engcom-Bravo** [comment] 2024-08-08 05:38
Hi @Shatchi,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-08-08 05:38 UTC
Labels: Issue: needs update, Reported on 2.4.x
