### ISSUE TITLE
Impossible to configure custom availability gateway validator

### ISSUE THREAD

**Issue by ytorbyk** [magento/magento2#5857] opened 2016-07-28 10:23 UTC
### Preconditions

Magento 2.1.0 is used
### Steps to reproduce

I try to add custom availability validator to gateway validator pool
`
<virtualType name="MyPaymentValidatorPool" type="Magento\Payment\Gateway\Validator\ValidatorPool">
        <arguments>
            <argument name="validators" xsi:type="array">
                <item name="availability" xsi:type="string">Vendor\Name\Gateway\Validator\AvailabilityValidator</item>
            </argument>
        </arguments>
    </virtualType>
`
### Expected result
1. Passed validator has to be used on \Magento\Payment\Model\Method\Adapter::isAvailable method call.
### Actual result

1. The validator is never used/called
### 

It is caused because result of $this->getInfoInstance() method call is always null (inside the 
 \Magento\Payment\Model\Method\Adapter::isAvailable method).

**Comment by YevSent** [comment] 2016-07-28 13:02
Hi @ytorbyk, please, post DI configuration for virtual type of your custom payment adapter.

**Comment by ytorbyk** [comment] 2016-07-28 13:08
Here it is:
`<virtualType name="MyPaymentAdapter" type="Magento\Payment\Model\Method\Adapter">
        <arguments>
            <argument name="code" xsi:type="const">Vendor\Name\Gateway\Config\ConfigProvider::CODE</argument>
            <argument name="formBlockType" xsi:type="string">Magento\Payment\Block\Form\Cc</argument>
            <argument name="infoBlockType" xsi:type="string">Vendor\Name\Block\Payment\Info</argument>
            <argument name="valueHandlerPool" xsi:type="object">MyPaymentValueHandlerPool</argument>
            <argument name="validatorPool" xsi:type="object">MyPaymentValidatorPool</argument>
            <argument name="commandPool" xsi:type="object">MyPaymentCommandPool</argument>
        </arguments>
    </virtualType>`

You can check this bug even on Braintree payment method, just try to add availability validator to the braintree validator pool.

**Comment by YevSent** [comment] 2016-07-28 13:18
Looks like configuration is correct. We will investigate this issue, but strange behaviour because on the latest develop branch the `getInfoInstance` in the `\Magento\Payment\Model\Method\Adapter::isAvailable` method returns Payment object.

**Comment by ytorbyk** [comment] 2016-07-28 13:26
I tested locally on the latest commit on the develop branch with the same result.
`db9e0f Alexander Akimov on 7/21/16 at 12:55 (committed by GitHub)
Merge pull request #165 from magento-qmt/PR`

https://dl.dropboxusercontent.com/u/2008499/Screen%20Shot%202016-07-28%20at%2016.21.50.png
https://dl.dropboxusercontent.com/u/2008499/Screen%20Shot%202016-07-28%20at%2016.24.13.png

Thank for quick response.
Let me know if you need any additional information.

**Comment by YevSent** [comment] 2016-07-28 13:41
Could you check the same behaviour for one of Magento payments, for example, Braintree? Just to check `$this->getInfoInstance()` won't be empty in `isAvailable` method. Even don't need to specify `availability validator.
PS. Links to screenshots are broken.
Thanks.

**Comment by ytorbyk** [comment] 2016-07-28 13:49
Yes, I have checked on Braintree payment method. The result on the those screenshots, `$this->getInfoInstance()` is empty.

**Comment by YevSent** [comment] 2016-07-29 09:54
Hi, @ytorbyk.
I more detailed investigated this issue and found follow things:
1. The `$this->getInfoInstance()` will return `null` if `setInfoInstance` not called yet, for example, `\Magento\Payment\Model\MethodList::getAvailableMethods`.
2. `\Magento\Payment\Model\Method\Adapter::isAvailable` should try to get payment instance only when payment already set to quote.

I've created internal ticket MAGETWO-56115.

**Comment by ytorbyk** [comment] 2016-07-29 10:01
Yes, thank you.

One more thing, availability validator should be called even if payment isn't set to quote yet, shouldn't it? Moreover, quote has to be always passed to the validator if it is already created. Is it correct?

**Comment by YevSent** [comment] 2016-07-29 10:10
> availability validator should be called even if payment isn't set to quote yet, shouldn't it? 

In the current implementation - no, because `\Magento\Payment\Gateway\Data\PaymentDataObjectFactory` expects `InfoInterface` not `null`.

> quote has to be passed to the validator if it is already created

Not quote, but payment.

**Comment by ytorbyk** [comment] 2016-07-29 10:33
So if payment is not set to quote the validator cannot reach quote, correct?

If yes.
What about case when availability depends on quote/quote items? Payment method shouldn't be (in some cases) in result of \Magento\Payment\Model\MethodList::getAvailableMethods method.

**Comment by YevSent** [comment] 2016-07-29 10:40
Validator works with quote payment, not with a quote https://github.com/magento/magento2/blob/develop/app/code/Magento/Payment/Model/Method/Adapter.php#L274.

> What about case when availability depends on quote/quote items?

This logic should be specified in the quote module, not in payment. Payment shouldn't depend on quote details.

**Comment by alena-marchenko** [comment] 2016-08-29 09:20
Hi @ytorbyk 

Fix for MAGETWO-56115 ticket is already merged to develop branch.
Closing the issue, please feel free to reopen if the issue still reproducible for you.

**Closed as completed by alena-marchenko** 2016-08-29 09:20 UTC
Labels: Issue: Ready for Work, bug report, Component: Payment
