### ISSUE TITLE
Saving an existing customer group fails

### ISSUE THREAD

**Issue by CNanninga** [magento/magento2#2337] opened 2015-11-12 19:15 UTC
In the current develop branch, saving an existing customer group fails because of the lack of a the "code" field being passed in the form.  This field is disabled in the edit form when editing an existing customer group, and therefore "code" is not present in the POST data, leading to the error "code is a required field" when attempting to save.

**Comment by slavvka** [comment] 2015-11-13 09:27
Hi @CNanninga, thank you for reporting issue. But I cannot reproduce it anywhere except for NOT LOGGED IN group that is mentioned by you in #2341.

**Comment by CNanninga** [comment] 2015-11-13 22:29
You're correct about this only occurring for the NOT LOGGED IN group.  I didn't realize that before.  (This happens because the "code" field is disabled in the form, but I didn't previously notice that it's only for the NOT LOGGED IN group that this field is disabled.)

However, this is a separate issue from #2341.  #2341 refers to an "already exists" error that occurs once the controller actually attempts to save this group.  This issue refers to a "required field" error that occurs  before the save ever happens, so a separate fix for this issue is still needed.

In Magento\Customer\Block\Adminhtml\Group\Edit\Form::_prepareLayout, the name (i.e., code) field is explicitly disabled if the customer group ID is 0.  This means no value is passed in the POST data, which results in the error.

**Comment by slavvka** [comment] 2015-11-16 08:32
The issue has a fix in PR #2344 and should be closed after it is merged.

**Comment by slavvka** [comment] 2016-06-08 08:48
@CNanninga, the issue has been fixed. Please see 6c0b8cf, 5e74abf, d865ca8, b3789a4, f8b2344.

**Closed by slavvka** 2016-06-08 08:48 UTC
Labels: accept, acknowledged, bug, CS
