### ISSUE TITLE
Retain the default cache & page cache's id_prefix if it has been defined by env.php -2-

### ISSUE THREAD

**Issue by phoenix-bjoern** [magento/magento2#35451] opened 2022-05-10 14:28 UTC
This issue is to re-open PR https://github.com/magento/magento2/pull/22356. 

The issue is still valid for Magento 2.4.x and is simple to reproduce. Configure a id_prefix in `env.php`:
```
'cache' => [
        'frontend' => [
            'default' => [
                'backend' => 'Cm_Cache_Backend_Redis',
                'backend_options' => [
                    'server' => 'redis-master',
                    'port' => '6379',
                    'database' => 1,
                    'persistent_identifier' => 'redis-cache',
                    'compress_data' => 1,
                    'compress_tags' => 1,
                    'compress_threshold' => 10240,
                    'compression_lib' => 'zstd'
                ],
                'id_prefix' => '1097_'
            ],
            'page_cache' => [
                'backend' => 'Cm_Cache_Backend_Redis',
                'backend_options' => [
                    'server' => 'redis-master',
                    'port' => '6379',
                    'database' => 2
                ],
                'id_prefix' => '1097_'
            ]
        ],
    ]
```

Then execute a command like `bin/magento setup:config:set --http-cache-hosts=varnish`. Check the `env.php` again the value has changed: `'id_prefix' => '69d_'`.

While IMHO it is not necessary to set any default for `id_prefix` and the else statement could be entirely omitted, the code changes in PR https://github.com/magento/magento2/pull/22356 are still valid. The error found during testing is not related to the PR itself, it is caused by another problem, not related to the changes in question.

**Comment by phoenix-bjoern** [comment] 2022-05-10 16:27
A workaround to preserve the cache id_prefix setting when using `bin/magento setup:config:set` is to explicitly set the values within the command: `bin/magento setup:config:set --http-cache-hosts=varnish --cache-id-prefix=1097_ --page-cache-id-prefix=1097_`

Side note: --allow-parallel-generation will also be set to `false` if not added as an argument.

**Comment by engcom-Delta** [comment] 2022-05-11 08:28
Hi @phoenix-bjoern ,

Thank you for re-opening the issue . It would be great help if you can help us with issue description, steps to reproduce, actual results and expected results.

Regards,

**Comment by phoenix-bjoern** [comment] 2022-05-11 21:03
@engcom-Delta Just have a look at the initial tickets and I‘ll find the requested information (https://github.com/magento/magento2/issues/22253).
Furthermore I can confirm that this issue can be still reproduced with 2.4-develop and the patch is fixing the issue. 
So you can move on with verifying the PR and merge it.

**Comment by engcom-Hotel** [comment] 2022-05-30 09:08
Hello @phoenix-bjoern,

Thanks for the reporting and collaboration!

We have tried to reproduce the issue in Magento 2.4-develop branch but for us, the issue is not reproducible for us. We have followed the below steps:

1. Setup Redis cache in Magento instance.
2. Made changes in `env.php` file and change `id_prefix` value as `test1_`:
<img width="622" alt="image" src="https://user-images.githubusercontent.com/51681618/170956983-5d9d902c-1076-4efc-9889-0f3a07f92f3a.png">
3. Run the command `bin/magento setup:config:set --http-cache-hosts=127.0.0.1`, the output for the same is as follows:
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/51681618/170958120-3a67536d-1037-4857-bf5d-627732a44f3c.png">


After running the above command the id_prefix is the same for us. Please let us know in case we have missed anything.

Thanks

**Comment by hostep** [comment] 2022-06-05 11:45
@phoenix-bjoern: could it be that this got fixed by [ACP2E-658: setup:config:set rewrites cache config in env.php](https://github.com/magento/magento2/commit/04355acb53d34dd0d57ab25399d858739a2787b2) ?

**Comment by engcom-Hotel** [comment] 2022-06-06 08:53
Thanks @hostep!

Hello @phoenix-bjoern,

As per the above comment, it seems that the issue has been addressed and fixed. Hence we are closing the issue. 

Thanks

**Closed as completed by engcom-Hotel** 2022-06-06 08:53 UTC
Labels: Triage: Dev.Experience, Issue: needs update

**Comment by phoenix-bjoern** [comment] 2022-06-20 11:37
@hostep @engcom-Hotel yes, seems https://github.com/magento/magento2/commit/04355acb53d34dd0d57ab25399d858739a2787b2.patch is solving the problem and issue can stay closed!
I assume this will be part of 2.4.5 then.
