### ISSUE TITLE
White space in images

### ISSUE THREAD

**Issue by ednacool** [magento/magento2#6448] opened 2016-09-01 13:47 UTC
Hi,

Any solution from Admin panel or from anywhere else white space in resized images coming from cache.

**Comment by veloraven** [comment] 2016-09-01 15:43
@ednacool thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.

**Comment by ednacool** [comment] 2016-09-02 07:26
Using version 2.0.9 i am talking about the cache images last version of magento i.e 1.9 whenever i want to change size i remove the resize code i.e ->resize(40,40) to  ->resize()

I am talking about that code product media images

Hope it make sense

**Comment by veloraven** [comment] 2016-09-02 12:07
@ednacool thank you for update with version number.
Please format description in standardized form:
_Steps to reproduce:_
1.
2.
3.
_Actual result:_
_Expected result:_
Otherwise it's hard to understand what is your problem and if it is a problem at all.

**Comment by andimov** [comment] 2016-09-27 09:41
@ednacool 
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Closed as completed by andimov** 2016-09-27 09:41 UTC
Labels: Progress: needs update
