### ISSUE TITLE
Products Randomly Disappear from Category View on Storefront When Partial Indexation is Running

### ISSUE THREAD

**Issue by tiagosampaio** [magento/magento2#35248] opened 2022-03-31 00:26 UTC
While the Catalog Search indexer is running, when it's set to run by a schedule by using the Mview architecture, there's a time when the products randomly disappear from the category pages. After a deeper investigation, I found out that the issue is on the ElasticSearch indexation by batch implementation.

Check the line:
https://github.com/magento/magento2/blob/a96f0f76c05778fd9400c04a0bdb9d31166c0d0d/app/code/Magento/CatalogSearch/Model/Indexer/Fulltext.php#L220

```php
        if ($saveHandler->isAvailable($dimensions)) {
            $saveHandler->deleteIndex($dimensions, new \ArrayIterator($productIds));
            $saveHandler->saveIndex($dimensions, $this->fullAction->rebuildStoreIndex($storeId, $productIds));
        }
```

It happens when the documents are deleted from ElasticSearch first to only after being processed and re-created. While this is happening the products are no longer available on ElasticSearch and, therefore, may cause some categories to show fewer or no products at all.

Since this indexation runs every time something is changed on the product data, this becomes totally random.

### Preconditions (*)

1. The Catalog Search (catalogsearch_fulltext) is set to Update by Schedule
2. Magento MUST be using ElasticSearch as a search engine

### Steps to reproduce (*)

This is really tricky to test because it only happens after Magento deletes the documents from ElasticSearch and before the documents are created again. It's totally random because this process may be triggered by a variety of other indexations or changes made to products. To test this you'll need some developer tools like: Postman, Xdebug

Before start:

1. Full Page Cache is disabled (for reproducing the issue)
2. Block cache is disabled (for reproducing the issue)

Now let's start:

1. Disable the cron so you can run it by yourself manually 
2. Make some changes to a few products
5. The catalogsearch_fulltext_cl table now should have some product IDs to be processed
6. On Postman, create a new request with the following configurations:

Request Type: `POST`
Request URL: `http://localhost:9200/magento2_product_1/document/_search` (where magento2_product_1 is the index name or alias)
Request Body:
```json
{
    "from": 0,
    "size": 100,
    "stored_fields": [
        "_id",
        "_score"
    ],
    "query": {
        "bool": {
            "must": [
                {
                    "terms": {
                        "category_ids": [
                            "4"
                        ]
                    }
                },
                {
                    "terms": {
                        "visibility": [
                            "2",
                            "4"
                        ]
                    }
                }
            ]
        }
    }
}
```
For the category ID, make sure to use a category ID related to the products that were changed so you can see that the products will disappear.

Tests:
```javascript
var jsonData = JSON.parse(responseBody);
let hits = jsonData.hits.total.value;
pm.test("Hits number is equals to 14 (" + hits + " hits).", () => {
    pm.expect(hits).to.be.equals(14);
});
```
Change the number 14 to the number of products for the selected category on the test. So, if your category has 25 products, the 14 must be switched by 25.

7. On Postman, use the runner to make this search each 500ms for 10000 requests. This way you can see the tests failing at the right moment.
8. Enable your Xdebug to run on every request:

```ini
xdebug.mode = debut
xdebug.start_with_request = yes
```
9. Start the Xdbug
10. Set a breakpoint on the following file and line: https://github.com/magento/magento2/blob/a96f0f76c05778fd9400c04a0bdb9d31166c0d0d/app/code/Magento/CatalogSearch/Model/Indexer/Fulltext.php#L221
11. When Xdebug stops on this line check the Postman runner failing the tests because the number of products is less than the number expected.
12. Go to the storefront and check the category page (without cache)
13. You can see there are fewer products or no products at all

I created a screencast showing the issue happening.
https://www.loom.com/share/a4790612971945508c50bb21e0f2523c

### Expected result (*)

1. The products are not deleted from ElasticSearch on the partial indexation (Mview)

### Actual result (*)

1. The documents (products) are removed from ElasticSearch before being re-created

**Comment by engcom-Hotel** [comment] 2022-04-11 08:14
Hello @tiagosampaio,

Thanks for posting this issue!

We have tried to reproduce the issue in Magento 2.4-develop branch but for us the issue is not reproducible. We have followed the below steps:
1. Disable Full page and Block page cache:
<img width="614" alt="image" src="https://user-images.githubusercontent.com/51681618/162693236-9e4672ed-b9ae-463b-84f9-02b86528a3df.png">
2. Disable the Cron:
<img width="594" alt="image" src="https://user-images.githubusercontent.com/51681618/162693331-c2df8f30-e196-49c5-84be-3850bb4aaa65.png">
3. Made the changes in `Joust Duffle Bag`


When we start debugging by passing below command in CLI:
`bin/magento cron:run -vvv --group indexer_update_all_views`

For us it is not breaking on the breakpoint mentioned in the main description. Please let us know in case we have missed anything.

Thanks

**Comment by tiagosampaio** [comment] 2022-04-11 13:46
@engcom-Hotel, thanks for letting me know.

You have the set the breakpoint at the following [line of code](https://github.com/magento/magento2/blob/a96f0f76c05778fd9400c04a0bdb9d31166c0d0d/app/code/Magento/CatalogSearch/Model/Indexer/Fulltext.php#L221):

```php
$saveHandler->saveIndex($dimensions, $this->fullAction->rebuildStoreIndex($storeId, $productIds));
```

When the execution reaches this line of code, the product, and its parent items (if available) are removed from the `ElasticSearch`. You can, for instance, set a die at this point and search the ElasticSearch for the products involved. You won't find them anymore.

Thanks.

**Comment by engcom-Hotel** [comment] 2022-04-12 06:49
Hello @tiagosampaio,

Thanks for your reply!

We have tried to set the breakpoint in the above specified line only but for us the debugger is not reaching on this line of code. Please let us know if we have missed any step.

Thanks

**Comment by tiagosampaio** [comment] 2022-04-13 17:27
@engcom-Hotel, just make sure you:

- Have the Xdebug properly configured to work with the CLI
- Make sure the Catalog Search Indexer is set to Update on Schedule
- Make sure you have new changes on the table `catalogsearch_fulltext_cl` (by either changing products on the admin or inserting new product ids manually on this table)
- On my test, I used the N98 MageRun to run the cronjob directly: `n98 sys:cron:run catalogsearch_fulltext`

Thanks.

**Comment by engcom-Hotel** [comment] 2022-05-12 15:11
Hello @tiagosampaio,

We again tried to reproduce the issue and the Xdebug is properly configured with the CLI. But the for the debugger is not reaching that point. 

I have a query, can you please elaborate on the below statement from the main description:

> when it's set to run by a schedule by using the Mview architecture

Thanks

**Comment by tiagosampaio** [comment] 2022-05-12 16:25
Hello, @engcom-Hotel. Thanks for the update.

What I mean by this is that, when you change the `catalogsearch_fulltext` index to be run by a schedule, it starts to use the Materialized View architecture, which means that the products that were changed recently and need to be indexed, are going to have their IDs to be inserted into the table `catalogsearch_fulltext_cl` and the record with the `view_id` equal to `catalogsearch_fulltext` is going to be enabled on the table `mview_state`.

In order, to make the PHP process stop on the breakpoint I mention above when you have Xdebug enabled on CLI, you'll need to have some product IDs on the table `catalogsearch_fulltext_cl` waiting to be reindexed. Then you can use the N98 to run the cronjob called `indexer_update_all_views` manually.

The following call will make the cronjob run:

```bash
n98 sys:cron:run indexer_update_all_views
```

Also, I noticed in the last release that it appears to have a change related to this exact issue. I'm not really sure of it because it was probably fixed internally by the Magento team and not by the community. Could you please let me know whether this fixes our issue here?

[Adobe Commerce 2.4.4 Release Notes](https://devdocs.magento.com/guides/v2.4/release-notes/commerce-2-4-4.html#index)

> A synchronization mechanism has been implemented in category indexers to prevent full and partial indexers from running in parallel. Previously, when these indexers ran in parallel, products could be temporarily omitted from storefront category pages or category pages could be temporarily empty of products.

Thank you!

**Comment by engcom-Hotel** [comment] 2022-05-23 09:24
Hello @tiagosampaio,

Thanks for the reply!

We have again retried to reproduce the issue in Magento 2.4-develop branch but it seems the issue has been already addressed and resolved. The issue is not reproducible for us. Please have a look at the below screenshot for reference:
1. After making changes to the product `Joust Duffle Bag`, index management showing `Schedule status`:
![Index-Management-Tools-System-Magento-Admin](https://user-images.githubusercontent.com/51681618/169787464-98b32d3c-0c16-4a74-a900-796393904674.png)

2. Ran `n98-magerun2.phar sys:cron:run indexer_update_all_views`, debugger has been stopped on the mentioned line in main description.:
![Bags-Gear-After](https://user-images.githubusercontent.com/51681618/169787810-87dd24df-4626-456d-aaa6-50de975764b5.png)

![debugger](https://user-images.githubusercontent.com/51681618/169787857-edd168c1-58de-47a2-923b-a1ac0704d02a.jpg)

Hence we are closing this issue as the issue is fixed and merged in the latest development branch. Please let us know if you are still able to reproduce the issue in Magento 2.4-develop branch.

Thanks

**Closed as completed by engcom-Hotel** 2022-05-23 09:24 UTC
Labels: Triage: Dev.Experience, Priority: P2, Progress: done, Issue: needs update

**Comment by hostep** [comment] 2022-07-07 08:14
For the people looking for more info about this section from the 2.4.4 release notes:

> A synchronization mechanism has been implemented in category indexers to prevent full and partial indexers from running in parallel. Previously, when these indexers ran in parallel, products could be temporarily omitted from storefront category pages or category pages could be temporarily empty of products.

It's was tagged as AC-190 in the release notes, but I think that's an incorrect ticket number and it should be ACP2E-190, for which there is one commit to be found: https://github.com/magento/magento2/commit/f6b12868406678f0c23a3dc4f9eb06fd187bf306
