### ISSUE TITLE
DELETE children of Option in Bundle product not work as expected 

### ISSUE THREAD

**Issue by zexperto** [magento/magento2#6104] opened 2016-08-10 16:56 UTC
### Preconditions

1. Magento version 2.0.8
2. DELETE /V1/bundle-products/:sku/options/:optionId/children/:childSku
### Steps to reproduce

1. Using REST (web service) Please  Create bundle product with two options and each option has two children
2. I can not add another child to specific option using PUT method.
3. I tried to Delete the children of the options, then delete the Option , and add the options again, but also not work
4. the reason is: not all records are deleted from (catalog_product_relation), 
5. when try to use (DELETE /V1/bundle-products/:sku/options/:optionId/children/:childSku
   ), all records will delete except childSku
### Expected result

1. when we apply (DELETE /V1/bundle-products/:sku/options/:optionId/children/:childSku) , you  should only delete the specific child , then we can apply this method for all children
2. you have also to allow to add another Child to option using PUT method in (/V1/Products/{sku}), Or allow us to add new using POST Method in (V1/bundle-products/options/add)
3. I think the error in this file (/vendor/magento/module-bundle/Model/LinkManagement.php) in removeChild function i propose to be like this 
   ![image 1](https://cloud.githubusercontent.com/assets/2926032/17581855/e02e1278-5fb0-11e6-9231-37034ba29148.png)
### Actual result

1. [Screenshot, logs]

**Comment by VasylShvorak** [comment] 2017-07-04 15:45
@zexperto  thank you for your report.
Is this issue still actual?
We were not able to reproduce it on the ver. 2.0.14

**Comment by zexperto** [comment] 2017-07-05 16:37
Hello,
I moved to Magento version 2.1.6 , in this version it worked

**Comment by veloraven** [comment] 2017-07-25 11:58
@zexperto thank you for your update.
I'm closing this issue then.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Closed as completed by veloraven** 2017-07-25 11:58 UTC
Labels: bug report, Progress: needs update
