### ISSUE TITLE
Sales rule with multiselect attribute condition prevents product from being added to cart

### ISSUE THREAD

**Issue by digitalpianism** [magento/magento2#38082] opened 2023-10-14 11:22 UTC
### Preconditions and environment

Magento 2.4.4-p6

### Steps to reproduce

1. Create a multiselect attribute:

![image](https://github.com/magento/magento2/assets/16592249/8c7e82f4-a639-464e-badb-a0c25a0e2dcc)

2. Make sure it has Use for Promo Rule Conditions = Yes in the Storefront properties:

![image](https://github.com/magento/magento2/assets/16592249/b5536d2b-b863-48d7-9c7c-33ef96e22be7)

3. Add the attribute to your attribute set

4. Create a cart price rule that has the following: 

![image](https://github.com/magento/magento2/assets/16592249/d65d95f3-9138-4b19-b2e1-6d25104239e6)
![image](https://github.com/magento/magento2/assets/16592249/b4a95743-9f1c-4e8d-812a-467aadb2e07f)

The rest of the rule doesn't really matter just make sure that it's active and enabled for all store views/customer groups, no coupon needed.

5. You probably gonna have to reindex at this point

6. Navigate to a product (logically no product should have any value set for the new attribute, you want to make sure that the product you navigate to doesn't have this attribute value set)

7. Add the product to your cart

### Expected result

Product is added to the cart.

### Actual result

Product is not added to the cart with the following error:

```
Exception: Deprecated Functionality: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /src/vendor/magento/module-rule/Model/Condition/Product/AbstractProduct.php on line 556
```

### Additional information

Here's the fix:

```
diff --git a/src/magento/module-rule/Model/Condition/Product/AbstractProduct.php b/src/magento/module-rule/Model/Condition/Product/AbstractProduct.php
index 1004eeaee6..6c23947ee4 100644
--- a/src/magento/module-rule/Model/Condition/Product/AbstractProduct.php
+++ b/src/magento/module-rule/Model/Condition/Product/AbstractProduct.php
@@ -553,7 +553,7 @@ abstract class AbstractProduct extends \Magento\Rule\Model\Condition\AbstractCon

             if ($attr && $attr->getFrontendInput() == 'multiselect') {
                 $value = $model->getData($attrCode);
-                $value = strlen($value) ? explode(',', $value) : [];
+                $value = ($value && strlen($value)) ? explode(',', $value) : [];
                 return $this->validateAttribute($value);
             }

```

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by digitalpianism** [comment] 2023-10-14 11:29
@magento give me 2.4-develop instance

**Comment by digitalpianism** [comment] 2023-10-14 12:53
I would need the reindex to be triggered so I can start using the sales rule I've created

**Comment by engcom-Bravo** [comment] 2023-10-16 07:46
Hi @digitalpianism,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

 **Steps to reproduce**

- Create a multiselect attribute:
- Make sure it has Use for Promo Rule Conditions = Yes in the Storefront properties:
- Add the attribute to your attribute set
- Create a cart price rule that has the following:
- You probably gonna have to reindex at this point
- Navigate to a product (logically no product should have any value set for the new attribute, you want to make sure that the product you navigate to doesn't have this attribute value set)
- Add the product to your cart



<img width="854" alt="Screenshot 2023-10-16 at 12 41 47 PM" src="https://github.com/magento/magento2/assets/51680745/ae5b8c3e-0cb9-43a5-b68b-5fcbc845115e">




![Add-Promotions-Marketing-Magento-Admin (2)](https://github.com/magento/magento2/assets/51680745/3c7fe02f-3add-419a-be3c-9eb09658ebf7)




<img width="1435" alt="Screenshot 2023-10-16 at 12 37 57 PM" src="https://github.com/magento/magento2/assets/51680745/7882814f-682b-4771-afe3-0f8e6759e595">




We are able to add the products successfully.


Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-10-17 07:38
Hi @digitalpianism,

Thanks for your update.

Here is the screenshot of Checkout page :


This product not meeting with conditions as per the cart price rule.

<img width="1412" alt="Screenshot 2023-10-17 at 11 51 42 AM" src="https://github.com/magento/magento2/assets/51680745/9a6d8fa4-2b3c-4e8e-9b70-5a0844e226ee">



Product is meeting with conditions as per the cart price rule.


<img width="1428" alt="Screenshot 2023-10-17 at 12 51 30 PM" src="https://github.com/magento/magento2/assets/51680745/6e34273f-b9e1-42db-91c5-8071f86b581d">




Please let us know if you are still facing any issue.


Thanks.

**Comment by digitalpianism** [comment] 2023-10-17 07:41
@engcom-Bravo could you please give me the link to the instance you're using ? as well as the admin credentials? I tried the ones from above but I get a 404

**Comment by engcom-Bravo** [comment] 2023-10-18 11:25
Hi @digitalpianism,

Thanks for your update.

We have verified the issue in our local instance.The instance we are getting here Reindex is not possible.

Could you please recheck in Magento 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-10-30 05:12
Hi @digitalpianism,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-10-30 05:12 UTC
Labels: Issue: needs update, Reported on 2.4.4-p6
