### ISSUE TITLE
Method does not have configuration

### ISSUE THREAD

**Issue by iproger** [magento/magento2#7491] opened 2016-11-19 21:36 UTC
### Preconditions
I need to configure the select.

### Steps to reproduce
(special for @veloraven)
1. I go to my computer.
2. I open my IDE.
3. I search getRegionHtmlSelect.
4. I try to send parameters to `<select>`.

### Expected result
1. Something like `public function getRegionHtmlSelect($defValue = null, $name = 'country_id', $id = 'country', $title = 'Country')`

### Actual result
1. Method `public function getRegionHtmlSelect()` does not have configuration unlike `getCountryHtmlSelect`.

https://github.com/magento/magento2/blob/2.1.2/app/code/Magento/Directory/Block/Data.php#L157

| Q | A |
| --- | --- |
| Magento version | 2.1.2 with sample data |
| PHP version | 7 x64 |
| Operating system | Windows 10 x64 |

**Comment by veloraven** [comment] 2016-11-23 13:53
@iproger thank you for your feedback.
Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result, expected result, and specify Magento version you are running.

**Comment by iproger** [comment] 2016-11-24 00:13
@veloraven I understand you don't understand the subject. It does not need explanation.

**Comment by veloraven** [comment] 2016-11-28 10:34
@iproger thank you for your answer.
But I have to ask you once more to format your issue according to the template even if you think it is not needed.
First of all it is easier to understand the actual problem when issue is well-structured. 
Second reason is that the issue is more likely to be found by other users who experience the same problem.
And the third (but not the least reason) - it may be very hard to draw the line fore the issue "which is simple enough and does not require any description" and which has to be described with all details.
So, when I ask you to follow prepared template which you see when create new issue, it is not a question of this exact issue and its simpleness, it is a question of general issues consistency in GitHub and possibility to treat any issue with the same rules.

**Comment by vzabaznov** [comment] 2016-12-13 09:12
Hi @iproger , closed as we don't receive update more than 2 week, feel free to write here/reopen or to open new issue

**Closed as completed by vzabaznov** 2016-12-13 09:12 UTC
Labels: Progress: needs update

**Comment by iproger** [comment] 2016-12-18 16:56
@veloraven @vzabaznov I have updated the question. Reopen please.

**Comment by nikunjskd20** [comment] 2019-05-09 06:03
Hi I have resolved this issue in a 2.3-develop branch in my fork. How can I send it to test for you.
