### ISSUE TITLE
Fotorama Magnifier not correct since 2.3.3

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#25027] opened 2019-10-13 17:14 UTC
### Preconditions (*)
1. Magento 2.3.3+

### Steps to reproduce (*)
1. Deploy Magento 2.3.3
2. Create Test Product with suitable image
3. edit etc/view.xml and set the following variable for the fotorama magnifier
`<var name="enabled">true</var>`
4. Clear cache
5. Browse to product on frontend and hover over product image, moving mouse to all four extents.

### Expected result (*)
1. The zoomed image can be manipulated correctly with the mouse as per the video below and the area magnified corresponds with the area in the rectangle beneath the mouse. This is taken on 2.3.2
![ljmvLLotg6](https://user-images.githubusercontent.com/30697781/66719220-d7c74d00-ede4-11e9-8938-5594a65b2e4a.gif)

### Actual result (*)
1. The area magnified is offset incorrectly as per the below image, and the zoom level is much lower. This is the exact same product and settings on 2.3.3
![K1hKZLkt67](https://user-images.githubusercontent.com/30697781/66719236-1c52e880-ede5-11e9-914b-897a91a72871.gif)

**Comment by engcom-Delta** [comment] 2019-10-22 08:42
Issue is reproducible on 2.3-develop
![#25027issue](https://user-images.githubusercontent.com/51681379/67270270-fd2d1880-f4c0-11e9-9aae-40e25ee999c4.gif)

**Comment by magento-engcom-team** [comment] 2019-10-22 08:44
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21971` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by anemitoff** [comment] 2019-10-28 15:41
I discovered one problem was that resets.less was causing a `max-height: 100%` rule to be applied erroneously to the `.magnifier-preview img` element. Once I fixed that, I realized that the mapping was not quite correct in that the preview was not revealing the content covered by the lens.  The `object-fit: scale-down` css property appears to be the cause of that problem.

Updating my _extend.less file with `.magnifier-preview img { max-height:inherit; object-fit: cover; }` fixed this issue for me.

**Comment by krzksz** [comment] 2019-10-29 20:11
Hey @anemitoff thanks for the hint, I was working on a PR but I was missing this `object-fix: cover` part 👍 Anyway you can find the fix under https://github.com/magento/magento2/pull/25358 and lets hope it's going to be merged soon.

**Comment by VladimirZaets** [comment] 2019-11-14 03:22
Hi @gwharton. Thank you for your report. 
The issue has been fixed in magento/magento2#25358 by @krzksz in 2.3-develop branch
Related commit(s):
 - [420ff66428076631de1955672b0639ba50e80a1f](https://github.com/magento/magento2/commit/420ff66428076631de1955672b0639ba50e80a1f)

The fix will be available with the upcoming 2.3.5 release.

**Closed as completed by VladimirZaets** 2019-11-14 03:22 UTC
Labels: Issue: Ready for Work, Area: Frontend, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Theme
