### ISSUE TITLE
Fedex Shipping throwing error 500 instead of showing message when trying to create shipping label with unavailable products

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [magento/magento2#39209] opened 2024-09-25 09:02 UTC
### Preconditions and environment

- Magento version: 2.4.7-p2
- FedEx shipping

### Steps to reproduce

1. Navigate to backend
2. Try to create shipping label for unavailable products

### Expected result

Inventory error message should be displayed to admin user.

### Actual result

Error 500 is thrown, visible only in console, showing:
Exception #0 (Magento\Framework\Exception\LocalizedException): Not all of your products are available in the requested quantity.

```
Exception #0 (Magento\Framework\Exception\LocalizedException): Not all of your products are available in the requested quantity.
<pre>#1 Magento\InventoryShipping\Observer\SourceDeductionProcessor->execute() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:88]
#2 Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:74]
#3 Magento\Framework\Event\Invoker\InvokerDefault->dispatch() called at [vendor/magento/framework/Event/Manager.php:65]
#4 Magento\Framework\Event\Manager->dispatch() called at [generated/code/Magento/Framework/Event/Manager/Proxy.php:105]
#5 Magento\Framework\Event\Manager\Proxy->dispatch() called at [vendor/magento/framework/Model/AbstractModel.php:846]
#6 Magento\Framework\Model\AbstractModel->afterSave() called at [vendor/magento/framework/Model/ResourceModel/Db/VersionControl/AbstractDb.php:56]
#7 Magento\Framework\Model\ResourceModel\Db\VersionControl\AbstractDb->processAfterSaves() called at [vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php:402]
#8 Magento\Framework\Model\ResourceModel\Db\AbstractDb->save() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#9 Magento\Sales\Model\ResourceModel\Order\Shipment\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#10 Magento\Sales\Model\ResourceModel\Order\Shipment\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#11 Magento\Sales\Model\ResourceModel\Order\Shipment\Interceptor->___callPlugins() called at [generated/code/Magento/Sales/Model/ResourceModel/Order/Shipment/Interceptor.php:32]
#12 Magento\Sales\Model\ResourceModel\Order\Shipment\Interceptor->save() called at [vendor/magento/framework/Model/AbstractModel.php:663]
#13 Magento\Framework\Model\AbstractModel->save() called at [vendor/laposte/magento2-colissimo-module/Plugin/Adminhtml/Order/Shipment/Save.php:119]
#14 LaPoste\Colissimo\Plugin\Adminhtml\Order\Shipment\Save->afterExecute() called at [vendor/magento/framework/Interception/Interceptor.php:146]
#15 Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#16 Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save\Interceptor->___callPlugins() called at [generated/code/Magento/Shipping/Controller/Adminhtml/Order/Shipment/Save/Interceptor.php:23]
#17 Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#18 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:151]
#19 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#20 Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#21 Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:145]
#22 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#23 Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#24 Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save\Interceptor->___callPlugins() called at [generated/code/Magento/Shipping/Controller/Adminhtml/Order/Shipment/Save/Interceptor.php:32]
#25 Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:245]
#26 Magento\Framework\App\FrontController->getActionResponse() called at [vendor/magento/framework/App/FrontController.php:212]
#27 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:146]
#28 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#29 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#30 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#31 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#32 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#33 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#34 Magento\Framework\App\Http\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#35 Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-application-performance-monitor/Plugin/ApplicationPerformanceMonitor.php:38]
#36 Magento\ApplicationPerformanceMonitor\Plugin\ApplicationPerformanceMonitor->aroundLaunch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#37 Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#38 Magento\Framework\App\Http\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#39 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#40 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
</pre>
```

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-10-03 05:22
Hi @ShapesGraphicStudio,

Thanks for your reporting and collaboration.

We are trying to reproduce the issue in Latest 2.4-develop instance and we are not able to reproduce the issue.Kindly refer the screnshots.



<img width="1331" alt="Screenshot 2024-10-03 at 09 54 53" src="https://github.com/user-attachments/assets/b2976659-f126-46c8-8ccd-f21c4df15889">


Here we are trying to add the products more than the quantity available and also we have removed the ordered product still we are getting the error Message.Could you please elaborate your scenario to proceed further.

Thanks

**Comment by engcom-Bravo** [comment] 2024-10-21 03:48
Hi @ShapesGraphicStudio,


We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Bravo** 2024-10-21 03:48 UTC
Labels: Issue: needs update, Reported on 2.4.7-p2
