### ISSUE TITLE
Catalog price rules 'is not one of' not working anymore

### ISSUE THREAD

**Issue by hvanrees** [magento/magento2#36706] opened 2023-01-05 13:40 UTC
### Preconditions and environment

- Magento version 2.4.4

### Steps to reproduce

1. Make a price rule: if ALL of these conditions are TRUE: SKU is not one of (.....)
2. Rule will not be applied as expected
3. Rewrite it with opposite arguments but the same expectation: if ALL of these conditions are FALSE: SKU is one of (...)
4. Rule will be applied as expected

### Expected result

Rule is applied

### Actual result

Rule is not applied

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-01-07 16:59
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-01-07 17:29
Hi @hvanrees ,
Magento version 2.4 develop
PHP 8.1
we are trying to reproduce the issue in 2.4-develop instance,But we are not able to reproduce the issue.
We are getting expected result.we can apply the rule successfully in both the conditions.

**Comment by engcom-Dash** [comment] 2023-01-18 02:33
Hi @hvanrees ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2023-01-18 02:33 UTC
Labels: Issue: needs update
