### ISSUE TITLE
Coupon code feature is not working properly in the checkout page on Magento 2.4.7

### ISSUE THREAD

**Issue by TuVanDev** [magento/magento2#38826] opened 2024-06-13 09:58 UTC
### Preconditions and environment

- Magento version: 2.4.7
- The checkout page only contains "Review & Payments" step as the cart only contains virtual or/and downloadable product types.

### Steps to reproduce

Example:
  1. Create a Virtual/Downloadable product.
  2. Navigate to storefront as a guest.
  3. Click “Add to Cart” on the Virtual/Downloadable Product.
  4. Open mini shopping cart and click “Proceed to Checkout”.
  5. Click "Apply Discount Code" text to expand the coupon code form.

### Expected result

The discount code/coupon input can be filled in, and the button title text displays as "Apply Discount".

### Actual result

The discount code/coupon input is disabled, and the button title text displays as "Cancel coupon".
<img width="1439" alt="coupon_code_feature_not_working_properly" src="https://github.com/magento/magento2/assets/5556060/0eb96bd1-6d2c-4479-994a-a57329ad7030">

### Additional information

It's important to note that I've tested this issue on Magento 2.4.6 and it didn't occurs.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by TuVanDev** [comment] 2024-06-13 10:01
@magento give me 2.4-develop instance

**Comment by digitalrisedorset** [comment] 2024-06-13 12:34
Hi @TuVanDev the file attached is a patch file that seems to resolve the issue. I have looked at Magento develop branch and previous Magento versions and this file has not changed in a while. That means this may not address the root of the issue. However, the patch change is low risk and I hope it may be sufficient to get this problem addressed
[discount-issue.zip](https://github.com/user-attachments/files/15820478/discount-issue.zip)

**Comment by TuVanDev** [comment] 2024-06-13 18:48
Hey @digitalrisedorset, thanks for your assist.

Yep, the code `isApplied(couponCode() != null);` in the file [vendor/magento/module-sales-rule/view/frontend/web/js/view/payment/discount.js](https://github.com/magento/magento2/blob/2.4.7/app/code/Magento/SalesRule/view/frontend/web/js/view/payment/discount.js#L24) hasn't changes for years. It now has an empty value instead of `null`. Therefore, `isApplied(couponCode() != null);`  should be changed to `isApplied(couponCode() !== '');`

I'll try to find the root cause and confirm if this is the best solution for this issue.

FYI, you can post the patch in your comment instead of sharing a zip file for more visibility.

**Comment by digitalrisedorset** [comment] 2024-06-14 07:03
the patch file code is:

`diff --git a/vendor/magento/module-sales-rule/view/frontend/web/js/view/payment/discount.js b/vendor/magento/module-sales-rule/view/frontend/web/js/view/payment/discount.js
index 79e4085..ad3c109 100644
--- a/vendor/magento/module-sales-rule/view/frontend/web/js/view/payment/discount.js
+++ b/vendor/magento/module-sales-rule/view/frontend/web/js/view/payment/discount.js
@@ -21,7 +21,7 @@ define([
     if (totals()) {
         couponCode(totals()['coupon_code']);
     }
-    isApplied(couponCode() != null);
+    isApplied(couponCode() != '');
 
     return Component.extend({
         defaults: {`

**Comment by TuVanDev** [comment] 2024-06-14 10:37
@digitalrisedorset GitHub support Markdown, so you can use triple backticks. You can check it out at https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

```
diff --git a/vendor/magento/module-sales-rule/view/frontend/web/js/view/payment/discount.js b/vendor/magento/module-sales-rule/view/frontend/web/js/view/payment/discount.js
index 79e4085..ad3c109 100644
--- a/vendor/magento/module-sales-rule/view/frontend/web/js/view/payment/discount.js
+++ b/vendor/magento/module-sales-rule/view/frontend/web/js/view/payment/discount.js
@@ -21,7 +21,7 @@ define([
     if (totals()) {
         couponCode(totals()['coupon_code']);
     }
-    isApplied(couponCode() != null);
+    isApplied(couponCode() !== '');
 
     return Component.extend({
         defaults: {

```

However, this will break the feature if the cart contains an item that is not virtual. Therefore, I've investigated and found the root cause of the issue. I'll create a pull request soon!

@magento I am working on this

**Comment by engcom-Dash** [comment] 2024-06-17 09:39
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2024-06-17 13:06
Hi @TuVanDev 

Thanks for reporting and collaboration.

Verified the issue Magento 2.4 dev instance and the issue is reproducible.

The coupon code feature is not working properly on the checkout page

Steps to reproduce:

1. Create a Virtual/Downloadable product.
2. Navigate to storefront as a guest.
3. Click “Add to Cart” on the Virtual/Downloadable Product.
4. Open mini shopping cart and click “Proceed to Checkout”.
5. Click "Apply Discount Code" text to expand the coupon code form.

Please refer the screenshots.

<img width="1440" alt="Screenshot 2024-06-17 at 3 24 03 PM" src="https://github.com/magento/magento2/assets/60198592/48f71964-7f7e-4f6c-909d-729a44693cf7">

**Comment by slavvka** [comment] 2024-06-17 14:42
@magento give me 2.4-develop instance

**Comment by slavvka** [comment] 2024-06-17 18:24
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-06-20 05:43
Hi @TuVanDev,

Internal team has started to work on it”

Thanks.

**Comment by hostep** [comment] 2024-07-04 19:09
Probably fixed by [AC:12170 :: Coupon code feature is not working properly in the checkout page on Magento 2.4.7](https://github.com/magento/magento2/commit/7a95761d3a97e7d542cb7264b51b570b17c7c1b8)?

**Closed as completed** 2024-07-05 07:31 UTC
Labels: Issue: Confirmed, Component: Ui, Reproduced on 2.4.x, Priority: P0, Progress: done, Area: Cart & Checkout, Reported on 2.4.7

**Comment by engcom-Bravo** [comment] 2024-07-05 07:32
@hostep Thanks for your contribution!!.

Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-12710 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-12710&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta1.

Thanks

**Comment by hostep** [comment] 2024-07-05 10:16
The link provided above doesn't work, but this one does: https://github.com/search?q=repo%3Amagento%2Fmagento2+AC+12170&type=commits
