### ISSUE TITLE
Error on message error when perform an oauth/token/request

### ISSUE THREAD

**Issue by luciaebizmarts** [magento/magento2#26717] opened 2020-02-05 17:59 UTC
### Preconditions (*)
1. Magento 2.3.x and Magento 2.2.x

### Steps to reproduce (*)
1. Set on Magento any language different to english.
2. Perform a post request to this endpoint oauth/token/request.
3. Be sure that the request returns error code 400.

### Expected result (*)
1. We should be able to see the error message on the returns.

### Actual result (*)
1. On the returns we see the next error message: `One or more input exceptions have occurred`, because this [`IF` statement](https://github.com/magento/magento2/blob/9544fb243d5848a497d4ea7b88e08609376ac39e/lib/internal/Magento/Framework/Oauth/Helper/Request.php#L204) compare the `$errorMsg` against `'One or more input exceptions have occurred.'` on english and the `$errorMsg` is on the language set on Magento.

**Comment by engcom-Bravo** [comment] 2020-03-25 15:24
Hello @luciaebizmarts 

Thank you for your report

We have rechecked this issue on a German version of Magento 2.4-develop via Swagger API
When we perform the following request with empty _username_ and _password_
![26717_api_token_request](https://user-images.githubusercontent.com/51680745/77552906-cc606d80-6ebc-11ea-9368-003f008ab93a.png)

We are getting a 400 Bad request with informative content
![26717_400 bad_request](https://user-images.githubusercontent.com/51680745/77553151-1a757100-6ebd-11ea-9a31-2eeebe8c660f.png)

The same error message on English version.

Can you please help us by answering the following questions:
- Are you able to reproduce it on Magento 2.4-develop?
- What language are you using?
- What API and request content are you using?

Thank you in advance

**Comment by engcom-Alfa** [comment] 2020-11-13 07:36
Hi @luciaebizmarts .

Unfortunately, we are not able to reproduce the issue on fresh 2.4-develop.

Manual testing scenario:

1. Set on Magento any language different to english.
2. Perform a **POST** request to this endpoint `oauth/token/request.`
3. Be sure that the request returns error code 400.

Actual Result: :heavy_check_mark: We see the error message on the returns.

![Screenshot from 2020-11-13 09-31-21](https://user-images.githubusercontent.com/51679138/99041421-911dc680-2593-11eb-9797-9606feaff085.png)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-11-13 07:36 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.2.x
