### ISSUE TITLE
Issue with configurable products in widgets, not added to cart

### ISSUE THREAD

**Issue by jcourtei** [magento/magento2#19315] opened 2018-11-21 22:08 UTC
### Preconditions (*)
Version 2.2.6 (Community Edition).

### Steps to reproduce (*)
1. Create a product attribute, for example Size with several values (S, M and L). This attribute must have property "use in product listing" set to Yes.
2. Create a product that uses this attribute with a configuration setting. Define different quantities for each values. Set this product as new for the current month.
3. Create a block with a widget for new products (choose the grid template) and add this block at any page.
4. On this page click on Add to cart (from a computer, not smartphone) for this new product.

### Expected result (*)
User should see the product page with the message "You need to choose options for your item."

### Actual result (*)
User is redirected to the cart page and the product is not added to the cart.

I think the issue is in vendor/magento/module-catalog/view/frontend/templates/product/widget/new/content/new_grid.phtml.
I replaced :
`<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>`
with :
`<?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)): ?>`
This way it is consistent with Magento\Catalog\Block\Product\AbstractProduct->getAddToCartUrl(), since this method uses isPossibleBuyFromList() to choose the url.
 
Several templates are concerned with this issue :
- vendor/magento/module-catalog-widget/view/frontend/templates/product/widget/content/grid.phtml (for the widget "Catalog Products List")
- vendor/magento/module-catalog/view/frontend/templates/product/widget/new/content/new_grid.phtml (for the widget "Catalog New Products List" with "New Products Grid Template")
- vendor/magento/module-catalog/view/frontend/templates/product/widget/new/content/new_list.phtml (for the widget "Catalog New Products List" with "New Products List Template")
- vendor/magento/module-catalog/view/frontend/templates/product/widget/new/column/new_default_list.phtml (for the widget "Catalog New Products List" with "New Products Images and Names Template")

**Comment by magento-engcom-team** [comment] 2018-11-21 22:08
Hi @jcourtei. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jcourtei do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment] 2018-11-22 01:46
@jcourtei suggested code changes can be provided directly as pull request. Thanks for bug report!

**Comment by magento-engcom-team** [comment] 2018-11-22 08:17
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2018-11-22 08:40
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96575`, `MAGETWO-96576` were created

**Comment by magento-engcom-team** [comment] 2018-11-23 06:41
Hi @gelanivishal. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2018-11-29 00:50
Hi @jcourtei. Thank you for your report. 
The issue has been fixed in magento/magento2#19322 by @gelanivishal in 2.3-develop branch
Related commit(s):
 - [ada1c5f1387d0dc504a6c4f9e7ce7cd836a44504](https://github.com/magento/magento2/commit/ada1c5f1387d0dc504a6c4f9e7ce7cd836a44504)
 - [8b1afea641b2ac327a16ed948c18b31f23c9ab18](https://github.com/magento/magento2/commit/8b1afea641b2ac327a16ed948c18b31f23c9ab18)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2018-11-29 00:50 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: CatalogWidget
