### ISSUE TITLE
2.3.3 update - Interface  InvoiceFlexFieldProcessorInterface not found OrderCurrencyGetterProcessor.php on line 24

### ISSUE THREAD

**Issue by YiffyToys** [magento/magento2#25020] opened 2019-10-12 14:38 UTC
### Preconditions (*)
1. Magento 2.3.2 CE

### Steps to reproduce (*)

1. composer require magento/product-community-edition=2.3.3 --no-update 
2. magento maintenance:enable && composer update && magento cache:flush && magento setup:upgrade && magento setup:di:compile ; magento maintenance:disable ; magento cache:enable

### Expected result (*)

no error message

### Actual result (*)

```
Nothing to import.
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 74.5 MiBPHP Fatal error:  Interface 'Vertex\Tax\Model\Flexfield\Processor\InvoiceFlexFieldProcessorInterface' not found in /home/..../vendor/vertex/module-tax/Model/FlexField/Processor/OrderCurrencyGetterProcessor.php on line 24
```

**Comment by YiffyToys** [comment] 2019-10-12 14:39
Obviously this can't be reproduced with a 2.3-develop verison. You need a 2.3.2 CE to do the upgrade to 2.3.3 CE.

**Comment by hostep** [comment] 2019-10-12 14:54
I'm closing this as a duplicate of https://github.com/magento/magento2/issues/24930

There is already [a patch available](https://github.com/magento/magento2/issues/24930#issuecomment-541213943), the problem is just some incorrect casing used in the namespace.

**Closed as completed by hostep** 2019-10-12 14:54 UTC
Labels: Issue: Format is valid

**Comment by MarcusWolschon** [comment] 2019-10-12 15:51
Thanks. I looked at the 2.3.3 issues but missed that one since the name was too generic and didn't contain   "InvoiceFlexFieldProcessorInterface" and "OrderCurrencyGetterProcessor" or "vertex" or "tax"
