### ISSUE TITLE
Magento v2.3.2 Integration Test Framework fails on Alpine Linux

### ISSUE THREAD

**Issue by damienwebdev** [magento/magento2#23637] opened 2019-07-09 13:20 UTC
### Preconditions (*)
1. Magento v2.3.2
2. Alpine Linux
3. PHP 7.2

### Steps to reproduce (*)
1. Run an instance of Alpine Linux w/ php7.2
2. Setup Magento environment, etc.
3. `cd dev/tests/integration`
4. `cp phpunit.xml.dist phpunit.xml`
4. `phpunit --configuration phpunit.xml`

### Expected result (*)
I expect to be able to run the test suite.

### Actual result (*)
The test suite fails with 

```
Fatal error: Uncaught Exception: ps: unrecognized option: pid
BusyBox v1.30.1 (2019-06-12 17:51:55 UTC) multi-call binary.

Usage: ps [-o COL1,COL2=HEADER]

Show list of processes

	-o COL1,COL2=HEADER	Select columns for display in /var/www/html/vendor/magento/framework/Shell.php:63
Stack trace:
#0 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Helper/Memory.php(74): Magento\Framework\Shell->execute('ps --pid '222' ...', Array)
#1 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Helper/Memory.php(55): Magento\TestFramework\Helper\Memory->_getUnixProcessMemoryUsage(222)
#2 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/MemoryLimit.php(127): Magento\TestFramework\Helper\Memory->getRealMemoryUsage()
#3 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/MemoryLimit.php(59): Magento\TestFramework\MemoryLimit->_getUsage()
#4 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Bootstrap/Memory.php(50): Magento\TestFramework\MemoryLimit- in /var/www/html/vendor/magento/framework/Shell.php on line 64
```

**Comment by damienwebdev** [comment] 2019-07-09 15:28
The code in question is: 

https://github.com/magento/magento2/blob/0eb8677b0b4e35606032e856cc1ef7c80e68829f/dev/tests/integration/framework/Magento/TestFramework/Helper/Memory.php#L71

We would need an additional variant for the base alpine `ps`, or as there are several conditionals in this file that could be cleaned up, a `ps` abstraction.

**Comment by engcom-Charlie** [comment] 2019-07-12 10:08
Hello @damienwebdev ! Thank you for your report !
I have tested this issue using Ubuntu 16.04 and was not able to reproduce it. Have you tried to reproduce it using other OS except Alpine Linux ?

![integr](https://user-images.githubusercontent.com/51680850/61120663-298acf00-a4a6-11e9-979a-205ea9d3923c.png)

**Comment by damienwebdev** [comment] 2019-07-12 14:01
@engcom-Charlie No. This bug only exists in Alpine Linux. Out-of-the-box Alpine Linux does not have a `pid` flag for the `ps` command. 

I'm positive the code runs just fine on most common Ubuntu flavors, but Alpine Linux is slightly different, and this is one of the ways. 

Much like the code in question handles the "OS" (e.g. Mac vs. Linux), we'll need a way to handle Alpine Linux as well.

**Comment by magento-engcom-team** [comment] 2019-07-12 14:09
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18138` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by damienwebdev** [comment] 2019-07-12 14:16
@engcom-Charlie Additionally, as I just tested this on my Alpine image, merely adding a `isAlpine` flavor for the conditional:

```php
if($this->isMacOS() || $this->isAlpineLinux())
```

https://github.com/magento/magento2/blob/0eb8677b0b4e35606032e856cc1ef7c80e68829f/dev/tests/integration/framework/Magento/TestFramework/Helper/Memory.php#L71

Would work as the command:

https://github.com/magento/magento2/blob/0eb8677b0b4e35606032e856cc1ef7c80e68829f/dev/tests/integration/framework/Magento/TestFramework/Helper/Memory.php#L72

Works in Alpine.

**Comment by damienwebdev** [comment] 2021-01-06 17:41
Not stale.

**Comment by aliuosio** [comment] 2021-01-06 17:52
exchange `"allure-framework/allure-phpunit": "~1.2.0"` with `"allure-framework/allure-phpunit": "~1.2.3"` to fix

**Closed as completed** 2021-02-08 22:09 UTC
Labels: Issue: Confirmed, Reproduced on 2.3.x, Component: Backend, Triage: Dev.Experience, Fixed in 2.4.x, Severity: S4, Priority: P4, Progress: done

**Comment by magento-engcom-team** [comment] 2021-02-08 22:11
Hi @damienwebdev. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-23829` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by speller** [comment] 2021-11-26 06:28
I still have this issue in 2.4.3:

```php
../../../vendor/bin/phpunit
PHP Fatal error:  Declaration of Magento\Catalog\Controller\Adminhtml\Product\Attribute\Save\InputType\AbstractSaveAttributeTest::setUp() must be compatible with Magento\TestFramework\TestCase\AbstractBackendController::setUp(): void in /magento/dev/tests/integration/testsuite/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Save/InputType/AbstractSaveAttributeTest.php on line 51
PHP Fatal error:  Uncaught Exception: sh: tasklist.exe: not found in /magento/vendor/magento/framework/Shell.php:65
Stack trace:
#0 /magento/dev/tests/integration/framework/Magento/TestFramework/Helper/Memory.php(92): Magento\Framework\Shell->execute('tasklist.exe /f...', Array)
#1 /magento/dev/tests/integration/framework/Magento/TestFramework/Helper/Memory.php(58): Magento\TestFramework\Helper\Memory->_getWinProcessMemoryUsage(195)
#2 /magento/dev/tests/integration/framework/Magento/TestFramework/MemoryLimit.php(127): Magento\TestFramework\Helper\Memory->getRealMemoryUsage()
#3 /magento/dev/tests/integration/framework/Magento/TestFramework/MemoryLimit.php(59): Magento\TestFramework\MemoryLimit->_getUsage()
#4 /magento/dev/tests/integration/framework/Magento/TestFramework/Bootstrap/Memory.php(50): Magento\TestFramework\MemoryLimit->printStats()
#5 [internal function]: Magento\TestFramework\Bootstrap\Memory->displayStats()
#6 {main}

Next Magento\Framework\Exception\LocalizedException: Command returned non-zero exit code:
`task in /magento/vendor/magento/framework/Shell.php on line 66
```

It fails to run the `ps --pid %s --format rss --no-headers` command and tries to run a Windows command.

When it really be fixed?

**Comment by stollr** [comment] 2024-09-24 15:04
@damienwebdev 
I can confirm that this issue still exists in Alpine Docker image with Magento `2.4.7-p2`.
