### ISSUE TITLE
"bin/magento setup:upgrade" error when upgrading database schema

### ISSUE THREAD

**Issue by yavery** [magento/magento2#37669] opened 2023-06-26 22:36 UTC
### Preconditions and environment

- Magento version:  2.4.5   (upgrading 2.4.2 database schema)

Then running `bin/magento setup:upgrade`
The first run will error out, but immeidately run the same command the second time, it will run through without any error

 
![setup-upgrade-error](https://github.com/magento/magento2/assets/130590250/b9ac6452-8247-4104-a94f-a3351c149eac)

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'entity_id' in 'NEW', query was: CREATE TRIGGER trg_catalog_category_entity_int_after_insert AFTER INSERT ON catalog_category_entity_int FOR EACH ROW
BEGIN
INSERT IGNORE INTO `catalog_category_product_cl` (`entity_id`) VALUES (NEW.`entity_id`);
END
```

### Steps to reproduce

1. a project with 2.4.2 database
2. php is upgraded to 8.1
3. updated the project to 2.4.5, assume eliminated all errors at the php code level
4. bin/magento setup:upgrade

### Expected result

first run should succeed

### Actual result

first run fails, second run succeeds

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-07-07 03:41
Hi @yavery ,

Verified the issue in 2.4-develop instance and the issue is not reproducible
Kindly refer the below screenshots:
<img width="1512" alt="Screenshot 2023-07-06 at 7 01 37 PM" src="https://github.com/magento/magento2/assets/60198592/d2d859e4-4399-4b7d-afd5-ca1d14d18cb5">
<img width="1512" alt="Screenshot 2023-07-07 at 9 06 34 AM" src="https://github.com/magento/magento2/assets/60198592/36e0fdf0-0efb-494c-bee9-575f7475ee43">

Steps to reproduce:
1.Install 2.4.2 magento instance
2.upgrade to instance to 2.4.5 
3.run setup upgrade command with PHP 8.1
Setup upgrade command ran successfully without any issues on first attempt.

Thanks!

**Comment by engcom-Dash** [comment] 2023-07-19 06:18
Hi @yavery ,

Do you Need further investigation regarding this issue,Still we are waiting for your response, If you are providing any information about this issue it really helps us.

Thanks.

**Comment by evs-xsarus** [comment] 2023-07-19 14:42
I get this error when moving from Commerce to Open Source. Maybe you did that by accident?

**Comment by engcom-Dash** [comment] 2023-07-31 04:26
Hi @yavery ,

Verified the issue in adobe commerce 2.4.2  and the issue is not reproducible, We can successfully upgrade the commerce version 2.4.2 to 2.4.5-p3 without any interruptions. Kindly refer the below screenshot:
<img width="1512" alt="Screenshot 2023-07-31 at 9 53 07 AM" src="https://github.com/magento/magento2/assets/60198592/e7633e10-f9be-44b0-8462-c4a26f3b9ba7">

Thanks!

**Comment by engcom-Dash** [comment] 2023-08-14 06:14
Hi @yavery ,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2023-08-14 06:14 UTC
Labels: Issue: needs update, Adobe Commerce, Reported on 2.4.5

**Comment by mischabraam** [comment] 2023-11-24 07:59
@evs-xsarus  

I too get this error when moving from Commerce to Open Source. Did you manage to solve this? And other DB issues moving from Commerce to Open Source?

**Comment by xsarus-academy** [comment] 2023-11-28 08:30
@mischabraam when you want to move to open source, you have to start with a new database. You then need to re-import your products and categories. Sales data can be copied more or less.
