### ISSUE TITLE
Null Input not handled in ServiceInputProcessor

### ISSUE THREAD

**Issue by akangithub** [magento/magento2#35071] opened 2022-02-09 07:00 UTC
### Preconditions (*)

1. Magento Version 2.3.3
2. Any environment

### Steps to reproduce (*)

1. Any PUT API call having a null value for any parameter in the body

### Expected result (*)

![expected_magento_put_call_with_null](https://user-images.githubusercontent.com/96811568/153138099-233f7281-d4e6-4983-96f6-356f86fff99f.PNG)
1. API should return a generic error response  (see attached file)

### Actual result (*)

1. Response had stack trace and framework details  (see attached file)
![actual_magento_put_call_with_null](https://user-images.githubusercontent.com/96811568/153138112-5ab12921-8bc5-41ad-a78a-781d9e3d5719.PNG)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [yes] Severity: **S0** _- Affects critical data or functionality and leaves users without [workaround._]([url](url))
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-02-21 13:21
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue:
Sent PUT request to /V1/products/{sku} with null sku value and Internal server error is returned.
![image](https://user-images.githubusercontent.com/60198231/154963061-499ca8ad-7c6b-4246-a200-cde4a20807ee.png)
@akangithub kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.

**Comment by akangithub** [comment] 2022-02-28 05:11
No try and catch block in ServiceInputProcessor at ($object->{$setterName}($setterValue);) is causing to throw error having the framework data. Can you check with some other null input values?

**Comment by engcom-November** [comment] 2022-03-01 11:07
Verified the issue again on Magento 2.4-develop branch with below sample payload and the issue is reproducible:
Sent PUT request to /rest//V1/products/null  by passing null in url and also in body (name and price) and response 200 status code - Issue: No validation error
Expected result: Error should be thrown
![image](https://user-images.githubusercontent.com/60198231/156158032-95d7a5de-ef76-44a2-acee-9fec8c273fc3.png)

```
{

"product": {

"sku": "dwwdwdwd",
"name": null,
"attribute_set_id": 4,
"price": null,
"extension_attributes": {
"stock_item": {
"qty": 3,
"is_in_stock": true,
"use_config_manage_stock": true
}
}

,
"options": [
{

"product_sku": "dwwdwdwd",
"title":"ewfedfed3ff",
"type":"drop_down",
"sort_order": 1,
"is_require":1,
"values": [
{
    "title":"frdref",
    "price":86,
    "price_type":"fixed",
    "sku":"bgbgfbfgb",
    "sort_order": 1 
}

]
}
]
},
"saveOptions":true
}
```

**Comment by engcom-Hotel** [comment] 2022-03-01 12:09
Hello @engcom-November,

As per the discussion in triage call, please check this issue again.

Thanks

**Comment by engcom-November** [comment] 2022-03-17 05:47
Hi @akangithub ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-03-17 05:47 UTC
Labels: Issue:  Cannot Reproduce, Component: Api, Priority: P2, Progress: done, Issue: needs update, Reported on 2.3.3, Area: APIs
