### ISSUE TITLE
Customer getStoreId is wrong when operating on customers in the admin panel

### ISSUE THREAD

**Issue by philcali** [magento/magento2#3376] opened 2016-02-11 18:18 UTC
There's an adminhtml di.xml definition for loading Customer models using a "Backend" model:

```
<type name="Magento\Customer\Model\ResourceModel\Customer\Collection">
        <arguments>
            <argument name="modelName" xsi:type="string">Magento\Customer\Model\Backend\Customer</argument>
        </arguments>
</type>
```

The Backend model overwrites the `getStoreId` method, which essentially hides which store view the customer **actually** belongs to:

```
    /**
     * Get store id
     *
     * @return int
     */
    public function getStoreId()
    {
        if ($this->getWebsiteId() * 1) {
            return $this->_getWebsiteStoreId();
        }
        return parent::getStoreId();
    }
```

This was a source of frustration, because the resulting behavior is very much unexpected. I fail to see how this implicit behavior would ever be desired. Please consider removing this injection for the admin view.

**Comment by sevos1984** [comment] 2016-02-15 11:29
Internal ticket MAGETWO-49197

**Comment by magento-engcom-team** [comment] 2017-11-17 12:30
@philcali, thank you for your report.
The issue is already fixed in develop branch, 2.1.10, 2.2.1

**Closed as completed by magento-engcom-team** 2017-11-17 12:30 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid

**Comment by sebfie** [comment] 2018-12-10 16:46
Where is the fix for that? I still have the issue on magento 2.2.6.

**Comment by slavvka** [comment] 2018-12-10 16:57
Hey @philcali feel free to create an issue if you still feel it exists
