### ISSUE TITLE
Entity dates don't save properly

### ISSUE THREAD

**Issue by royvanos** [magento/magento2#10871] opened 2017-09-13 13:57 UTC
### Preconditions

1. Magento 2.1.8
2. MySQL 5.6.37

### Steps to reproduce

1. Any Magento 2.1.8 installation
2. Admin interface language set to nl_NL (Dutch)
3. Create a product with any special date range and save it, the date can't be the same as the current day

### Expected result

1. Product special price range should still be the same

### Actual result

1. Product special price dates show the current date

There also is a javascript error whenever a date object tries to be instanciated: Error creating Date object from string.

After a bit of debugging it looks like the jquery-ui-timepicker-addon.js tries to instanciate a date object using the date format that belongs to the set adminhtml locale (DD-MM-YYYY in my case), it seems like the addon can't handle any date formats other than YYYY-MM-DD (which is understandable) but Magento injects a date using the corresponding date format for the set adminhtml locale, setting the adminhtml locale to en_US works fine.

This seems to happen to every date field there is.

**Comment by orlangur** [comment] 2017-09-13 15:46
Duplicate of https://github.com/magento/magento2/issues/10580 and a bunch of other issues.

**Closed as completed by orlangur** 2017-09-13 15:46 UTC
Labels: bug report, duplicate, Issue: Format is valid
