### ISSUE TITLE
Some of the product URL not working in Magento 2.4.2

### ISSUE THREAD

**Issue by rightmarc** [magento/magento2#33518] opened 2021-07-19 06:02 UTC
### Preconditions (*)

1. Magento Commerce 2.4.2

### Steps to reproduce (*)

1. Create a simple product from admin with Product name as "pubg-hard-back-case-for-oppo-f5-562" (Admin - Catalog - Products - Add Simple Product) and save
Note: Stores -> Configuration -> Catalog -> Catalog -> Search Engine Optimization -> Make sure html suffix is removed before searching using url-key from front-end
2. Navigate to Front-end - URL - Search for the product using URL Key
http://yourmagentostore.com/pubg-hard-back-case-for-oppo-f5-562
**Issue 1: Link is returning 404 Not Found**
3. We are able to access the product using below URL - No issue
When used http://yourmagentostore.com/catalog/product/view/id/37/category/3 this target path link then product visible in the storefront and also I can add the product to the cart.
![image](https://user-images.githubusercontent.com/60198231/127447955-62bf450b-810e-44c2-911e-3a500e7227de.png)

4. Add the same product to Cart
5. Navigate to Shopping Cart page
6. Click on the product
**Issue: Unable to access the product details page. 404 Not Found is returned.**

### Expected result (*)

Product visible on storefront by its URL.

### Actual result (*)

1. This issue was found on some of the products. Not in all products. So help to solve this bug.
![image](https://user-images.githubusercontent.com/60198231/127447876-ba937745-2400-42b7-88a7-e10d596f6c7e.png)

**Comment by engcom-November** [comment] 2021-07-22 10:18
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible even after trying using multiple Simple, Configurable and Bundle products.
**Steps performed:**
Front end -> URL -> Navigate to Product Details page using url-key. Ex: http://magento2.4.local/product-cattt-ewfew-frfre-fefew-fewfef-wfwrr-3344   - **No issue. User is able to access Product Details page**
**Note:** Stores -> Configuration -> Catalog -> Catalog -> Search Engine Optimization -> Make sure html suffix is removed before searching using url-key from front-end
![image](https://user-images.githubusercontent.com/60198231/126624208-756fb7a3-bf7e-43f1-8c75-1bdd58929b74.png)

Front-end -> Access Product Details page using URL: http://magento2.4.local/catalog/product/view/id/4/category/3
Add the product to Cart
Go to Shopping Cart page
Click on the Product -> **No issue: User is navigated back to Product Details page**
![image](https://user-images.githubusercontent.com/60198231/126624097-15364e92-639b-44f4-b22c-ec4d53c2dba9.png)
![image](https://user-images.githubusercontent.com/60198231/126624126-ec2a8e4f-c6d3-4713-8b40-e31419aaa775.png)

![image](https://user-images.githubusercontent.com/60198231/126623925-5c9b09e5-4fb7-460b-8f30-005280efe7fd.png)

**Comment by rightmarc** [comment] 2021-07-22 10:24
The product link is already given at there I face the issue ( http://rightmarc.com/pubg-hard-back-case-for-oppo-f5-562 ).
When used http://rightmarc.com/catalog/product/view/id/15361/category/3 this target path link product visible perfectly.

This problem is not found in all products. 

Please check the above link so you can find the bugs.

**Comment by engcom-November** [comment] 2021-07-29 07:03
Verified the issue again on Magento 2.4-develop branch by creating product with same name mentioned in the description and the issue is reproducible:
Steps to reproduce:
Create a simple product from admin with Product name as "pubg-hard-back-case-for-oppo-f5-562" (Admin - Catalog - Products - Add Simple Product) and save
Note: Stores -> Configuration -> Catalog -> Catalog -> Search Engine Optimization -> Make sure html suffix is removed before searching using url-key from front-end
Navigate to Front-end - URL - Search for the product using URL Key
http://yourmagentostore.com/pubg-hard-back-case-for-oppo-f5-562
Issue 1: Link is returning 404 Not Found
We are able to access the product using below URL - No issue
http://yourmagentostore.com/catalog/product/view/id/37/category/3
Product Details page - Add the same product to Cart
Navigate to Shopping Cart page
Click on the product
**Issue:** Unable to access the product details page. 404 Not Found is returned.
![image](https://user-images.githubusercontent.com/60198231/127446776-62b9c325-5e6f-4108-90ac-f02d66c8f500.png)
![image](https://user-images.githubusercontent.com/60198231/127446806-0fadd645-f95b-441d-9656-d1c62396edc7.png)

**Comment by magento-engcom-team** [comment] 2021-07-29 07:05
@engcom-November Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-07-29 07:11
:white_check_mark: Confirmed by @engcom-November 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42932` were created

**Issue Available**: @engcom-November, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by SilinMykola** [comment] 2021-07-29 13:20
@magento I am working on this

**Comment by gabrieldagama** [comment] 2021-08-03 11:41
@magento give me 2.4-develop instance

**Comment by SilinMykola** [comment] 2021-08-10 16:29
It happens because Magento cuts 'pub' from request url as default_url. I can't change this behavior.

**Comment by anzin** [comment] 2021-08-12 12:35
@magento I am working on this

**Closed as completed** 2021-08-20 16:19 UTC
Labels: Issue: Confirmed, Component: Url, Reproduced on 2.4.x, Priority: P1, Progress: done, Reported on 2.4.2

**Comment by glo05363** [comment] 2021-08-20 16:27
Verified the issue again on Magento 2.4-develop branch by creating product with same name mentioned in the description and the issue is not reproducible. please check the attached screen. we are closing the issue as : can not reproduce.

![image](https://user-images.githubusercontent.com/87003041/130264419-3c0bdf73-f8bb-402d-92b0-1a502fc73bc4.png)

**Comment by rightmarc** [comment] 2022-05-27 09:19
This issue still not resolved in magento 2.4.4 update. 

When this was fixed?
