### ISSUE TITLE
After login from backed user, we are getting  a js issue i.e.  'TypeError: data is null' 

### ISSUE THREAD

**Issue by jitendra-cedcoss** [magento/magento2#20198] opened 2019-01-11 07:34 UTC
**Description**

* After login from backed user, we are getting  a js issue i.e.  'TypeError: data is null' 

**Preconditions:**

* This issue is available in Magento 2.2.x, Magento 2.3.x version.

**Note :** Make sure Notification Resource disable for current login User

**Steps to reproduce:**

* Create a new role (for example role name is 'Notification Role') and go to Role Resource tab.

* Select 'Resource Access' as 'Custom' and allow all resouces except 'Notification'.

* Create a new User (ex- username : testacl , password: test@123 ) and assign above role (ex: 'Notification Role') to this user.

* Login this user (ex: testacl) from backed login panel.

* In admin dashboard you will get 'TypeError: data is null'  js issue

**Expected result:**

* No js issue should come

**Actual result:**

* Getting 'TypeError: data is null' js issue 

**Images:**
![acl](https://user-images.githubusercontent.com/25526075/51019537-43a02f00-15a1-11e9-8be7-53be28125342.png)
![js issue](https://user-images.githubusercontent.com/25526075/51019538-43a02f00-15a1-11e9-98b1-ff034fade9df.png)

**Comment by magento-engcom-team** [comment] 2019-01-11 07:35
Hi @jitendra-cedcoss. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jitendra-cedcoss do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-11 07:35
Hi @mallikaverma. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-01-11 07:37
@mallikaverma Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97569`, `MAGETWO-97570` were created

**Comment by krzksz** [comment] 2019-11-21 19:23
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-21 19:23
Hi @krzksz. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-21 19:23
Hi @krzksz, here is your [Magento instance](https://i-20198-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20198-2-3-develop.instances.magento-community.engineering/admin](https://i-20198-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krzksz** [comment] 2019-11-21 19:28
Based on linked issues and my own testing I can confirm that issue was fixed and is no longer reproducible on Magento 2.3.x. Please reopen it if you are able to reproduce it there.

**Closed as completed by krzksz** 2019-11-21 19:28 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Component: Ui
