### ISSUE TITLE
Saving Category with existing image causes an exception

### ISSUE THREAD

**Issue by BarnyShergold** [magento/magento2#8069] opened 2017-01-07 18:47 UTC
### Preconditions
Using custom Ubuntu xenial vagrant-box, php7, apache

Have latest stable release of Magento 2.1.3 installed.
No 3rd part modules installed 
Steps to reproduce

### Steps to reproduce
1. Create a new category an add an image
2. Clear logs
3. Edit category and save, without change any attributes

### Expected result
1. Category should save
2. No errors in log

### Actual result
1. Category says it has saved, all details are as they should be.
2. Exception.log states that there was a problem saving the images.

## Notes
This seems to be an issue where on saving the, afterSave method on Magento\Catalog\Model\Category\Attribute\Backend\Image invoke the call to moveFileFromTmp, however as the file has already been moved on the original save, this caused moveFileFromTmp to throw an exception as it can't find the temporary file.

**Comment by dthampy** [comment] 2017-01-11 20:47
Internal jira ticket MAGETWO-63097 created

**Comment by magento-engcom-team** [comment] 2017-09-29 05:30
@BarnyShergold, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by nemesis-back** [comment] 2017-10-26 22:35
I will work on it #SQUASHTOBERFEST 2017

**Comment by nemesis-back** [comment] 2017-11-20 18:00
@okorshenko you fixed this issue for 2.2 in this commit https://github.com/magento/magento2/commit/0ac82ebb63032909f5c61c40ee1b1bbc3b5d9c32
so I've just backported it to 2.1-develop

**Comment by okorshenko** [comment] 2017-11-22 22:01
Hi @nemesis-back 
@osrecio is working on your PR review 👍

**Comment by ishakhsuvarov** [comment] 2017-12-13 07:44
Hi @BarnyShergold 
We are closing this issue now as the fix has been delivered to 2.3, 2.2 and now 2.1-develop. You may refer to the linked commits to see the fix.

Thank you

**Closed as completed by ishakhsuvarov** 2017-12-13 07:44 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
