### ISSUE TITLE
Creating order in Admin area gives 500 error - SalesOrderAfterPlaceObserver not found Magento 2.2.7

### ISSUE THREAD

**Issue by sts-ryan-holton** [magento/magento2#20288] opened 2019-01-14 15:57 UTC
### Preconditions (*)
1. Magento 2.2.7
2. Using MAMP Pro
3. PHP 7.0.22 being used

### Steps to reproduce (*)

1. Go to Admin --> Sales --> Orders -- > Create New Order
2. Add a product, shipping/billing address.

### Expected result (*)
1. Order should successfully complete without errors.

### Actual result (*)
1. After submitting the order I get a PHP 500 error, and after reviewing the MAMP logs it seems to be something related to an observer.
2. Order isn't created.

```
[14-Jan-2019 15:47:30 UTC] PHP Fatal error:  Class 'Magento\SalesRule\Observer\SalesOrderAfterPlaceObserver' not found in /Applications/MAMP/htdocs/MY-SITE/app/code/Amasty/Promo/Observer/FixCouponsUsageObserver.php on line 19
```
![screenshot 2019-01-14 at 15 53 53](https://user-images.githubusercontent.com/25177538/51123915-fcba6f80-1814-11e9-954a-bfd1ee03d35e.png)

**Comment by magento-engcom-team** [comment] 2019-01-14 15:58
Hi @sts-ryan-holton. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sts-ryan-holton do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-14 15:59
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment] 2019-01-14 16:02
@sts-ryan-holton this seems due to custom module install at your environment . Please contact to related company. 
this issue is not reproduceable at 2.2-develop instance

**Closed as completed by shikhamis11** 2019-01-14 16:02 UTC
Labels: Issue: Format is valid
