### ISSUE TITLE
Trouble in attaching comments to shipment record created using shipment api

### ISSUE THREAD

**Issue by ruby10** [magento/magento2#3485] opened 2016-02-19 14:05 UTC
While creating shipment records using Magento2.x shipment API "POST /V1/shipment/" , it has been made mandatory to add "parentId" field inside comments array json with an appropriate value , which refers to "entityId" of shipment record we are going to create, but how is it possible to know this before creation, since is an auto-generated field. If we provide "null", "0" to "parentId", or omit this field from request json, it is throwing "400 Bad Request" error. Also if i provide some non-zero value for this "parentId" field , then provided comment json will be attached to the shipment record having "entityId" field with that particular value.
Following is the json 
{
    "entity": {
        "orderId" : 45,
        "items": [{
                "orderItemId" : 87,
                 "qty": 1
            }],

```
     "comments": [
         {
          "comment": "comment",
          "isCustomerNotified": 0,
          "isVisibleOnFront": 0
  }]

}
```

}

**Comment by ruby10** [comment] 2016-06-14 09:29
@MomotenkoNatalia , @NadiyaS , Please provide update on this issue if there is any?

**Comment by Mulderua** [comment] 2016-06-22 15:36
Hi @ruby10 , you cannot add comment before shipment record was created .

**Comment by NadiyaS** [comment] 2016-07-13 11:02
Hi @ruby10 ,
as @Mulderua said in current implementation you need to create shippment first and only then create comment to it by additional call. 
Issue is closed as not a bug.

**Closed as completed by NadiyaS** 2016-07-13 11:02 UTC
