### ISSUE TITLE
Braintree Error Logs with Braintree Payment Disabled.

### ISSUE THREAD

**Issue by victortodoran** [magento/magento2#33501] opened 2021-07-16 11:10 UTC
### Preconditions (*)

1. Magento 2.4.2 (probably for older versions as well

### Steps to reproduce (*)

1. Fresh install
2. Ensure Braintree payment method is disabled
3. Place an order

### Expected result (*)

1. Order is placed. No Error Logs.

### Actual result (*)

MagentoRoot Folder/var/log/system.log ->
Below Error message is gettting printed in system.log after placing orders using other payment modes : 
main.ERROR: Braintree\Configuration::merchantId needs to be set (or accessToken needs to be passed to Braintree\Gateway)

Please check this [comment](https://github.com/magento/magento2/issues/33501#issuecomment-887548328) for more details about the configuration.

### Additional info (*)
I don't want to disable the modules, the merchant might want to configure and use Braintree in the future and should not need me to re-enable the modules to do so.
The cart and checkout pages try to load the config for a disabled payment method, it makes little sense, if it's disabled I certainly don't have a token configured for it.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2021-07-27 14:13
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
Steps performed:
Installed Brain-tree module on 2.4-develop branch
Admin -> Stores -> Configuration -> Sales -> Payment methods -> Configure Brain-tree payment.
Note: Set Debug mode to Yes
Front-end -> Add a product to cart -> Checkout -> Make payment using Restraint Credit Card - No Issue. User is able to place Order
Now disable Brain-tree payment option from Admin (Remove brain-tree configuration from Admin - Stores - Configuration - Sales - Payment Methods)
Cache flush and clear cache
Navigate to Front-end - Add a product to Cart - Checkout - Make Payment using PayPal Express Checkout - User is able to place Order.
**Issue:** MagentoRoot Folder/var/log/system.log -> 
**Below Error message is gettting printed in system.log after placing orders using other payment modes :** main.ERROR: Braintree\Configuration::merchantId needs to be set (or accessToken needs to be passed to Braintree\Gateway). [] []

**Comment by magento-engcom-team** [comment] 2021-07-27 14:14
:white_check_mark: Confirmed by @engcom-November 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42923` were created

**Issue Available**: @engcom-November, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Closed as completed** 2024-09-12 13:24 UTC
Labels: Issue: Confirmed, Component: Braintree, Reproduced on 2.4.x, Priority: P3, Progress: done, Reported on 2.4.2
