### ISSUE TITLE
Collection doesn't update after filtering by stores

### ISSUE THREAD

**Issue by LSERRE** [magento/magento2#9583] opened 2017-05-10 16:26 UTC
### Preconditions

1.Magento CE 2.1.6
2.PHP 7.0
3.MySQL 5.6

### Steps to reproduce

1. Helper functions:
```
    public function getPostList($type = null, $id = null)
    {
        $list          = '';
        $posts         = $this->postfactory->create();
        $list = $posts->getCollection();

        if (count($list)) {
            return $list->addFieldToFilter('enabled', 1)->addStoreFilter($this->getStoresToFilter());
        }

        return $posts;
    }

    protected function getStoresToFilter()
    {
        $storesToFilter = [];
        $storesToFilter[] = 0; // all stores flag.
        $storesToFilter[] = $this->storeManager->getStore()->getId();

        return $storesToFilter;
    }
```
2. Post Collection:
```
    public function addStoreFilter($store, $withAdmin = true)
    {

        if ($store instanceof Store) {
            $store = [$store->getId()];
        }

        if (!is_array($store)) {
            $store = [$store];
        }

        if ($withAdmin) {
            $store[] = 0;
        }

        $this->addFilter('store_id', ['in' => $store], 'public');

        return $this;
    }

    /**
     * Join store relation table data if store filter is used
     *
     * @return \Ultranoir\Menumanager\Model\ResourceModel\Menu\Collection
     */
    protected function _renderFiltersBefore()
    {
        if ($this->getFilter('store_id')) {
            $this->getSelect()->join(
                ['store_table' => $this->getTable('ultranoir_messikablog_post_store')],
                'main_table.post_id = store_table.post_id',
                []
            )->group('main_table.post_id');
        }

        return parent::_renderFiltersBefore();
    }
```
3. Block:

```
class Listpost extends Frontend
{

    public function getPostList()
    {
        return $this->helperData->getPostList();
    }

    public function getFirstPost()
    {
    	return $this->helperData->getFirstPost();
    }
}

```

4. View:

```
<?php
print_r($block->getPostList()->getData());
$posts = $block->getPostList();

?>
<?php if ($posts->getSize() > 0) : ?>
		<?php foreach ($posts as $post) : ?>
			<?php echo "TEST"; ?>
		<?php endforeach; ?>
    </div>
<?php endif; ?>
```

### Expected result

1. I have only 2 posts in DB, one for each store of my website. On frontend it should render 1 article. It should also display one entry in a array with print_r

### Actual result

1. There are 2 posts displayed on frontend with both languages. The most strange thing is there is only one entry in the getData results.

You can see frontend result here: [https://cloudup.com/c_mcAs-jSqF](url)

**Comment by korostii** [comment] 2017-05-10 16:57
If I were to guess, either `_renderFiltersBefore()` isn't being invoked at all, or the collection is loaded earlier than the filters get applied.

In any case, if you are looking for some help or an advice regarding development please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.
The issues which cannot be consistently reproduced on a clean installation of Magento 2 CE aren't likely to get resolved in here.

**Comment by LSERRE** [comment] 2017-05-11 08:37
Thanks for you answer korostii. _renderFiltersBefore() is invoked, i tested it.
Moreover the most strange thing is getSize and count doesn't return the same thing.

I was thinking i was facing an issue but maybe it comes from my code if you think so.

**Comment by LSERRE** [comment] 2017-05-11 09:22
In my Helper function i was calling `count($list)` which is loading collection. Removing this did the trick.

**Comment by korostii** [comment] 2017-05-11 11:25
I'm glad that you managed to fix it :)
Please feel free to close the issue, if it is resolved for you.

**Comment by magento-engcom-team** [comment] 2017-10-03 12:30
@LSERRE, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by ishakhsuvarov** [comment] 2017-12-13 08:09
@LSERRE We are closing this issue for now, as from the comments it seems to be fixed for you now.
Please feel free to reopen if it is still unresolved.

Thank you.

**Closed as completed by ishakhsuvarov** 2017-12-13 08:09 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, non-issue, Issue: Format is valid
