### ISSUE TITLE
Missing Fedex Ground option for certain products at checkout

### ISSUE THREAD

**Issue by paulapena201** [magento/magento2#36788] opened 2023-01-28 00:05 UTC
### Summary

The shipping method does not appear with some products but is visible with others at Checkout, only FedEx SHQ . 
http://shot.screen1.me/aEJXUSy9mJqoNb7xsotQf3.png
http://shot.screen1.me/cs3wtbxUVprf9qyWu9W4HF.png 

### Examples

I enabled FedEx to be visible even though it is not available, and I could see a message that is displayed when the shipping method does not get prices.
That is FedEx is not showing because it can't get the shipping cost for the product we added.
http://shot.screen1.me/hgKHtFZHJv8wU7BgTFSRwg.pn

Then I searched for information and found several posts that recommended changing the "Residential Delivery" setting to "NO".
When I made this configuration, I was able to see the shipping method with the product that was giving problems.
http://shot.screen1.me/43549wczNM59Um8kQHrYrj.png
http://shot.screen1.me/bmC7d8k8W3fB5gNPzAZ3NA.png

But according to FedEx, if we select "No" for the Residential Delivery option in Magento and a customer selects this option. When they deliver the item and it is, in fact a Residential delivery, a surcharge will be added to the bill of whoever shipped it. (In this case, TAG). So this option only works if the items are delivered to a business only. Furthermore, FedEx sees on their side that they are providing all the rates and say there is no disconnection on their end and to consult with Magento. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2023-01-30 09:56
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-01-30 12:49
Hi @paulapena201,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.

Steps to reproduce :

1.Enabled Fedex
2 Residential Delivery given NO



<img width="1171" alt="Screenshot 2023-01-30 at 6 14 32 PM" src="https://user-images.githubusercontent.com/51680745/215481203-c590e08b-19b9-40b5-b63c-36270b6669b3.png">



<img width="1183" alt="Screenshot 2023-01-30 at 6 14 40 PM" src="https://user-images.githubusercontent.com/51680745/215481263-07ec6462-25bf-4d0c-b78f-57f456010722.png">



<img width="1180" alt="Screenshot 2023-01-30 at 6 09 10 PM" src="https://user-images.githubusercontent.com/51680745/215481332-a0647030-1bd7-4a38-b590-143a5b0f3a98.png">


 while doing checkout Fedex Ground option is not visible.


Hence Confirming this issue.

Thanks.

**Comment by engcom-Charlie** [comment] 2023-01-31 11:27
As per the discussion in triage call, @engcom-Bravo can you please do further analysis till that time moving it for Ready for Confirmation.

Thank you!

**Comment by SPbryan007** [comment] 2023-02-01 16:36
@magento give me 2.4.5-p1 instance - upcoming 2.4.5-p1 release

**Comment by engcom-Hotel** [comment] 2023-02-02 08:12
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2023-02-02 10:21
Hello @paulapena201,

We have rechecked this issue and it seems the issue is not reproducible on the [developer tool](https://github.com/magento/magento2/issues/36788#issuecomment-1413316683), we are able to see the Fedex as the shipping method. Please refer the below screenshot:

![image](https://user-images.githubusercontent.com/51681618/216297149-9fbd387c-1c8c-40f6-a3cd-5757fec6260b.png)

For us, the `Residential Delivery` option is also Yes:

<img width="770" alt="image" src="https://user-images.githubusercontent.com/51681618/216298318-aa342fc9-ca4d-472c-8597-af3525644edc.png">


Thanks

**Comment by engcom-Hotel** [comment] 2023-02-16 05:52
Dear @paulapena201,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2023-02-16 05:52 UTC
Labels: Component: Checkout, Reproduced on 2.4.x, Issue: needs update, Reported on 2.4.x, Area: Cart & Checkout
