### ISSUE TITLE
Paypal Website Payments Pro Hosted Solution iframe

### ISSUE THREAD

**Issue by harshadgoswami** [magento/magento2#7671] opened 2016-12-03 10:45 UTC
**Steps to reproduce**
Install Magento from 2.1.2 (and/or previous) release.
Setup Paypal Website Payments Pro Hosted Solution (using a sandbox account) - select merchent country to United Kingdom
Add any product to cart
Attempt a checkout using a "test" card

**Expected result**
Magento opens an iframe where you can enter the card details

**Actual result**
The iframe opens in the actual window with the following message coming in from Paypal:
"Paypal This transaction can't be processed. Please pay with another card."

Magento itself seems to be working fine (it creates the order, contacts Paypal and receives an iframe link properly), however it is extremely difficult to debug and figure out on when and why the iframe is opened on the main window and automatically submitted.

My debug.log output as follow,
[debug.log.txt](https://github.com/magento/magento2/files/628801/debug.log.txt)

**Comment by YevSent** [comment] 2016-12-05 10:21
Hi, @harshadgoswami, please, contact with PayPal what card you can use for testing.

**Comment by harshadgoswami** [comment] 2016-12-07 11:34
Hi, @joni-jones  , I am testing it with sandbox account , Account type is business pro and merchant country is United Kingdom. is there anything missing ?

**Comment by YevSent** [comment] 2016-12-07 12:10
You should have sandbox personal (buyer) account for testing.
To get more details, please, read
https://developer.paypal.com/docs/classic/products/website-payments-pro-hosted-solution/ and https://www.paypalobjects.com/webstatic/en_GB/developer/docs/pdf/hostedsolution_uk.pdf - they contain all needed information about integration with WPPHS.

**Comment by harshadgoswami** [comment] 2016-12-07 12:47
I do checkout as guest , where I am entering billing information only. I have no interface to add credit card in checkout page. In billing information i use my sandbox personal(buyer) email. Please check below link 
[http://prntscr.com/dgfn37](http://prntscr.com/dgfn37)
[http://prntscr.com/dgfo7s](http://prntscr.com/dgfo7s)
After clicking continue button receive error as shown in below link. It redirected to sandbox link
[http://prnt.sc/dgfjaj](http://prnt.sc/dgfjaj])

**Comment by YevSent** [comment] 2016-12-27 11:02
Hi, @harshadgoswami, cannot reproduce your issue.

Do you use HTTPS for checkout pages? By default `Enable SSL Verification` option for WPPHS is `Yes`.

Also, please, check if you have any errors in browser console log.

**Comment by alena-marchenko** [comment] 2017-01-19 14:43
Hi @harshadgoswami 

We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue.

**Closed as completed by alena-marchenko** 2017-01-19 14:43 UTC
Labels: bug report, Progress: needs update, Component: Payment

**Comment by samuelecarpene** [comment] 2018-09-21 12:32
@harshadgoswami how did you solve the problem? I have the same problem in a site with paypal integration.
