### ISSUE TITLE
Magento Integration Tests. DataFixture Store generates Sequence tables if Id > 10

### ISSUE THREAD

**Issue by JesperHerrloff** [magento/magento2#38245] opened 2023-12-05 17:45 UTC
### Preconditions and environment

- Magento version 2.4.6
- class Magento/Store/Test/Fixture/Store has regenerateSequenceTables which regenerates Sequence tables if Store Id is above 10. 

The issue here is when using DataFixtures The \Magento\TestFramework\Event\Transaction::_startTransaction method sets beginTransparantTransaction on the connection object. Which makes it possible to only use DataFixtures for store_id 0 to 9. 

My personal opinion would be to check if the table name starts with sequence_ then allow DDL transaction during tests

### Steps to reproduce

Install Magento 2.4.6
Create Integration Test that uses a DataFixture Attribute set for example DataFixture(Magento/Store/Test/Fixture/Store::class, ['id' => 11])

Then it will throw an exception DDL statements are not allowed in transactions

### Expected result

The result I expected would be to have a store with id 11. 

### Actual result

An exception is thrown regarding DDL queries in transaction.

### Additional information

private function regenerateSequenceTables(int $storeId): void
    {
        if ($storeId >= 10) {
            $n = $storeId + 1;
            $this->sequence->generateSequences($n);
        }
    }
    
    The code that makes it impossible to use DataFixtures with storeId above 10.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2024-02-12 07:31
Hello @JesperHerrloff,

Thanks for the report and collaboration!

We have tried to reproduce this issue in the Magento 2.4-develop branch, but it seems the issue is not reproducible for us. We have made the said changes in the existing test ie `dev/tests/integration/testsuite/Magento/Bundle/Model/ResourceModel/Option/AreBundleOptionsSalableTest:testExecute`, and made the said changes in the DataFixture:
![image](https://github.com/magento/magento2/assets/51681618/d9603454-1d97-4085-b826-1c0f8ec99eff)

But the issue is not reproducible for us:
![image](https://github.com/magento/magento2/assets/51681618/55c6486e-3f00-422d-99fa-d9acad7e65e9)

Please let us know if we are missing anything.

Thanks

**Comment by engcom-Hotel** [comment] 2024-03-01 07:29
Dear @JesperHerrloff,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we're assuming it's been resolved and will be closing it. Feel free to open a new ticket or reopen this one if you require further assistance.

Regards

**Closed as completed by engcom-Hotel** 2024-03-01 07:29 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.6
