### ISSUE TITLE
Upgrade from 2.1.0 to 2.1.1 ISSUE

### ISSUE THREAD

**Issue by ksz2013** [magento/magento2#6493] opened 2016-09-05 12:01 UTC
Hi

After upgrading from 2.1.0 to 2.1.1: (upgrade steps see below)

composer require magento/product-community-edition 2.1.1 --no-update
composer update
php bin/magento setup:upgrade

When we are modifying a configurable product, and we attach new images to it, the configurable product becomes a simple product! Our site is messed up now because of this! Can you please check this issue and provide a feeedback on it?

Thanks,
Szabi

**Comment by andimov** [comment] 2016-09-05 12:23
@ksz2013 
Thank you for reporting!
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by fendowuk** [comment] 2016-09-06 09:41
@ksz2013 I believe this is related to the same here [#6424](https://github.com/magento/magento2/issues/6424#issuecomment-244899668), there is a major issue with configurable products in 2.1.1.

**Comment by andimov** [comment] 2016-09-27 09:40
@ksz2013 
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Closed as completed by andimov** 2016-09-27 09:40 UTC
Labels: Progress: needs update
