### ISSUE TITLE
Catalog Price Rule - wrong product price in multi-stores site.

### ISSUE THREAD

**Issue by ed007m** [magento/magento2#24586] opened 2019-09-13 16:40 UTC
### Preconditions (*)

1. Magento 2.2.5 CE installed. (But issue present in all Magento versions and Magento commerce as well).
2. Create additional website `Website1` with own store and store view.
3. Navigate to  Stores->Configuration->Catalog->Catalog and set Catalog Price Scope : Website
4. Create a product which will be available in two websites(Default and New one).
4.1. Put product price for `All Stores` -> 400, save
4.2 Put product price for `Default website` -> 300, save
4.3  Put product special price for `Default website` -> 250, save
4.4 Put product price for `Website1` -> 200, save

### Steps to reproduce (*)

To reproduce this issue catalog price rule should be created in next way:
1. Create a catalog price rule for two websites
<img width="1330" alt="catalogrule" src="https://user-images.githubusercontent.com/6236299/64876942-fd7ffb80-d658-11e9-9df0-11064656fdbf.png">

2. Create condition if special_price >= 1.
3. Select action:  apply as percentage original, and fill discount value 10 (as ex.)
<img width="1058" alt="condition" src="https://user-images.githubusercontent.com/6236299/64877094-5780c100-d659-11e9-9d4c-ff8d3dcba2f6.png">

4. Save the rule.
5. Run bin/magento indexer:reindex.
6. Navigate to frontend of `Default store view` and check product price.
7. Navigate to frontend of `Website1 view` and check product price.

### Expected result (*)

1. Expects that price for product in `Website1 store` is not changed - so, it should be 200, as special price is filled only for `Default store`. 

### Actual result (*)

1. Actual result is that price for `default store` is - 250$ 
<img width="1330" alt="default" src="https://user-images.githubusercontent.com/6236299/64877672-8f3c3880-d65a-11e9-9415-884ddf645ffe.png">

2. And price for `Website1` is 180
<img width="865" alt="store1" src="https://user-images.githubusercontent.com/6236299/64877696-99f6cd80-d65a-11e9-906d-40a4203925bc.png">

So, basically it means that price for `Website1 store` has wrong value, because catalog price condition should not be applied here, it should work only for `default website`

Basically, it happens because here in vendor/magento/module-catalog-rule/Model/Rule.php:332  - magento sets data from `Default store`(id=1) 

```
               $product = clone $args['product'];
332:        $product->setData($args['row']);

                $websites = $this->_getWebsitesMap();
              $results = [];
```

and below in vendor/magento/module-catalog-rule/Model/Rule/Condition/Product.php:78

```
        $storeId = $model->getStoreId();
        $defaultStoreId = \Magento\Store\Model\Store::DEFAULT_STORE_ID;

        if (!isset($this->_entityAttributeValues[$model->getId()])) {
            return $this;
        }

        $productValues  = $this->_entityAttributeValues[$model->getId()];

        if (!isset($productValues[$storeId]) && !isset($productValues[$defaultStoreId])) {
            return $this;
        }
```
Doesn't override this value if such doesn't exists on `Default website`(id=2)  or `All Stores view`(id=0). And method just returns $this with attribute value for `Default Store`

**Comment by engcom-Charlie** [comment] 2019-10-11 14:54
Hello @ed007m 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.

We are closing this issue due to branch `2.2-develop` was closed and
> Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.

 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-10-11 14:54 UTC
Labels: Issue: Format is valid

**Comment by frithjof** [comment] 2021-01-12 17:15
still happening in 2.3.6
