### ISSUE TITLE
Sampledata

### ISSUE THREAD

**Issue by zhanyi8866** [magento/magento2#1831] opened 2015-09-10 02:44 UTC
D:\magento\Mage003\magento2\bin>php magento sampledata:install admin
Installing theme:
.
Installing customers:
.
Installing CMS pages:
....
Installing catalog attributes:
...........................
Installing categories:
.........................................
Installing simple products:
PHP Fatal error:  Call to undefined method Magento\Catalog\Model\Resource\Produc
t\Interceptor::getWriteConnection() in D:\magento\Mage003\magento2\app\
code\Magento\SampleData\Module\Catalog\Setup\Product\Gallery.php on line 144

Fatal error: Call to undefined method Magento\Catalog\Model\Resource\Product\Int
erceptor::getWriteConnection() in D:\magento\Mage003\magento2\app\code\
Magento\SampleData\Module\Catalog\Setup\Product\Gallery.php on line 144

**Comment by mazhalai** [comment] 2015-09-10 15:56
@zhanyi8866 This is a known issue. Please use the `master` branch if you plan to use sample data.  Closing as duplicate of #1636 , #1610 , and #1757.

**Closed by mazhalai** 2015-09-10 15:56 UTC

**Comment by afroz92** [comment] 2015-09-10 16:13
I have tried installing from master branch with sample data  on my local with Windows 7 and the installation takes too much time especially at 98% it stuck for an hour.
![magento2-1](https://cloud.githubusercontent.com/assets/1916683/9793700/7876ea24-5804-11e5-98bf-2a74abac856f.png)

**Comment by mazhalai** [comment] 2015-09-10 16:28
@afroz92 do you have `xdebug` enabled? It will slow it down considerably.  Sample data does take a while, please be patient.

**Comment by afroz92** [comment] 2015-09-10 16:43
I have added  
php_value xdebug.max_nesting_level 500  
in my .htaccess file . Does this value makes difference? Shall i make it 200?

**Comment by zhanyi8866** [comment] 2015-09-11 04:15
01.   git clone -b master https://github.com/magento/magento2.git
02.   php -r "readfile('https://getcomposer.org/installer');" | php
03.   php composer.phar config repositories.magento composer http://packages.magento.com
04.   php composer.phar install
05.  open firefox, begin install (don't choose 'sample data')
06.  install success
07.  php composer.phar require magento/sample-data:1.0.0-beta
08.  php magento setup:upgrade
09.  php magento sampledata:install admin
10.  sampledata install success

memory_limit = 2048M

**Comment by Schoeny1** [comment] 2015-09-15 13:54
zhany you rock!

Thank you for your procedure list, I have been having such a hard time getting this to work and you saved me.  The only thing that I had to do differently was install from the command line.  I also had to reset the owner and permissions of the install directory at the end in order to see the data.
