### ISSUE TITLE
It’s impossible to load Quote by Id via CartRepository in cron

### ISSUE THREAD

**Issue by ytorbyk** [magento/magento2#8081] opened 2017-01-09 20:35 UTC
### Preconditions
1. developer branch is used
2. I need to process some (some specific quotes, which ids are saved somewhere) quotes in cron process.

### Steps to reproduce
1. Create any model where `\Magento\Quote\Api\CartRepositoryInterface` is used for getting quote by ID with `get` method
2. Add the model to `crontab.xml` 
3. Run cron

### Expected result
1. It’s possible to load specific quote by ID via `CartRepository`

### Actual result
1. `NoSuchEntityException` exception is thrown (however the quote exists in DB)

I believe the cause is this line
https://github.com/magento/magento2/blob/develop/app/code/Magento/Quote/Model/QuoteRepository.php#L202
But is it right that I can load only quote for current store by ID via repository?

**Comment by korostii** [comment] 2017-01-10 11:54
Hi, I might be wrong here, but imho what you're describing might not be a bug per se. If I'm not mistaken, it should be possible to select the store you'd like to use beforehand, roughly as described [here](http://blog.gagglethread.com/magento2/magento2-set-current-store/) 
Have you tried doing that?

**Comment by ytorbyk** [comment] 2017-01-10 12:13
Hi @korostii.
Yes, you are right. It's possible to select a store before call of the method.
But I don't know which store the quote was created for, I have quote ID only and it's a unique identifier.
Setting current store in Store Manager looks like implicit passing a parameter to the method, but the interface does not imply that.

**Comment by goivvy** [comment] 2017-05-28 23:32
did you try $quote->loadByIdWithoutStore($sequence->getQuoteId()) ?

**Comment by magento-engcom-team** [comment] 2017-10-13 09:30
@ytorbyk, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-13 09:30 UTC
Labels: bug report, Component: Checkout, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
