### ISSUE TITLE
State/Province field doesn't show as required causes checkout error

### ISSUE THREAD

**Issue by kjasrotia** [magento/magento2#9077] opened 2017-03-31 15:09 UTC
### Preconditions

1. Magento 2.1.4
2. 

### Steps to reproduce

Similar issue as #5279 which was closed by customer but has not actually been fixed in Magento 2.1.4.

1. I have specified "State" field as mandatory for customer address for my Country (India) from Admin.
Stores > Setting Configuration > General > General > Country Options > State Options > State is Required for.

2. From store create a customer account but do not add address.

3. From store Login to account and checkout a product. During checkout, being able to create address without the State as it is not shown as required in the address form (however, when customer has registered account and goes to add a new address from account settings, then 'State' is shown as required - go figure !!)

4. During checkout it gives an "Error occurred on the server. Please try to place the order again" error.   
    When the State is provided in address the checkout goes thru.

This basic issue needs to be fixed ASAP .. losing sales because of this ! Customer obviously does not know issue and abandons the transaction. Specifying "State" as mandatory should make it a required field in ALL the various address forms for customers.

### Expected result

1. The 'State' should be a required field in ALL address forms presented to the customer.

### Actual result

1. Since 'State' is not shown as required, customer is able to create address without the state. However, this causes the "Error occurred on the server. Please try to place the order again" during checkout.  When State is added to address the checkout goes thru.

**Comment by korostii** [comment] 2017-04-03 10:25
> This basic issue needs to be fixed ASAP

Haha, that's funny. You must be new here.
IF it gets changed right away, there's 2 months on the average until the change reaches a release.
It would speed up the process,, if you could provide a pull request with the fix, otherwise chances are you'll get it fixed earlier if you work around it locally in your codebase, rather than wait for a fix to get released.

**Comment by Andreshlan** [comment] 2017-06-07 14:45
I have this same problem...Magento 2 is not functional, should still be a beta

**Comment by ifeltsweet** [comment] 2017-09-11 09:29
Completely agree, Magento 2 is indeed still a beta. Basic functionality doesn't work.

**Comment by Igloczek** [comment] 2017-09-17 09:28
@Andreshlan @ifeltsweet 
Did you hear about reactions? You just should upvote issues and pull requests, if you think they are important.
Your comments have no value for maintainers or other devs.

**Comment by Igloczek** [comment] 2017-09-17 12:28
@ishakhsuvarov I manage to fix it - my PR #10924
The issue is already fixed on `develop` branch, so I backported the fix to `2.1-develop`.

**Comment by ishakhsuvarov** [comment] 2017-09-17 12:34
@Igloczek Thanks!

**Comment by kjasrotia** [comment] 2017-09-17 12:37
Thank you !

**Comment by magento-engcom-team** [comment] 2017-09-19 19:25
@kjasrotia, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-19 19:25 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
