### ISSUE TITLE
Cannot update only extension attributes via REST (POST: /rest/V1/orders)

### ISSUE THREAD

**Issue by mtwegrzycki** [magento/magento2#32202] opened 2021-02-17 11:35 UTC
### Preconditions (*)
1. Magento 2.4.2

### Steps to reproduce (*)
1. Place order via GraphQL
2. Try to update order via REST API (POST /rest/V1/orders)
3. In request body put only: entityId and any extension attribute
4. Make request

### Expected result (*)
1. Extension attributes for order will be updated

### Actual result (*)
1. I get the response with the following error: "SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE (entity_id=25)' at line 1, query was: UPDATE `sales_order` SET  WHERE (entity_id=25)"

This issue is caused by lack of data to put after SET in SQL query. This issue does not occur in Magento 2.4.0
I debuged the code and it is caused by code change from this commit https://github.com/magento/magento2/commit/bd087ecd950024190fef4e5cb6fe5aa6bb27d2eb (moving 
I do not mean, that this modification is incorrect, but after this modification it is not possible to modify only extension attributes via REST.
In Magento 2.4.0 protect_code is generated not only for new orders, so even if we put only entityId and extension attributes in POST body, protect_code is inserted after SET in SQL query, so query has valid syntax.
In Magento 2.4.2 it is not possible to update only extensions attributes via (POST /rest/V1/orders). It is needed to add any order attribute to request body (e.g. status, remote_ip or sth) as workaround to update extension attributes.

This is exampled request body, which causes error:
```
{
    "entity": {
        "entity_id": {{entity_id}},
        "extension_attributes": {
            "reference_number": "ABC123"
        }
    }
}
```
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by TonyMerlin** [comment] 2021-03-19 00:45
Sorry to say but we are having the exact same issue since upgrading from Magento 2.4.1 our PUT 
`{"entity":{"entity_id":26481,"extension_attributes":{"mycustom_order_code":"15278"}}}`
 worked perfectly in all previous versions but since upgrading to 2.4.2 this is now broken and our stock management system is rendered useless. I have tried with a vanilla install of 2.4.2 and get the same error 
`"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE (entity_id=26481)' at line 1, query was: UPDATE sales_order SET WHERE (entity_id=26481)"`

**Comment by TonyMerlin** [comment] 2021-06-03 13:57
Hi for anyone else struggling with this i've found the fix.

In Magento 2.4.1 the protect_code is generated only for new orders... so as before if we put just entityId and extension attributes in POST body protect_code is inserted after SET in SQL query so therefore the query has valid syntax.
 
In Magento 2.4.2 it isn’t possible anymore to update extensions attributes without passing another attribute via /rest/V1/orders 

It seems that all is needed here is to add any standard order attribute to the body I.e status, store_id etc as a workaround to update extension attributes, so as an example: 
“{"entity":{"entity_id":127,"store_id":1,"extension_attributes":{"mycustom_order_code":"99999"}}}” 

By setting the store_id alongside my custom attribute it now populates the new data correctly.

**Comment by philippeaellig** [comment] 2021-06-07 20:49
is this issue related to this issue? #32907 https://github.com/magento/magento2/issues/32907

i have an issue with magento 2.4.2 and quote extension attributes. i am not able to checkout.

this is the error message on place order: rest/default/V1/carts/mine/payment-information
`#0 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Model\PaymentInformationManagement->savePaymentInformationAndPlaceOrder()
#1 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callParent()
#2 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->Magento\Framework\Interception\{closure}()
#3 generated/code/Magento/Checkout/Model/PaymentInformationManagement/Interceptor.php(23): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callPlugins()
#4 [internal function]: Magento\Checkout\Model\PaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder()
#5 vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array()
#6 vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process()
#7 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch()
#8 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent()
#9 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}()
#10 generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins()
#11 vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch()
#12 generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#13 vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http\Interceptor->launch()
#14 pub/index.php(50): Magento\Framework\App\Bootstrap->run()
#15 {main}`

**Comment by engcom-Hotel** [comment] 2021-09-13 11:33
Hello @mtwegrzycki,

We have tried to reproduce the issue in Magento 2.4-develop branch. But we are unable to reproduce it. We have tried both ways to create the order, which means frontend and graphql. We have followed the below steps in order to reproduce it:

1. Create an extension attribute with the name "order_comment".
2. Place an order via GraphQL and frontend.
3. Tried to update the extension attribute via rest API. We get below output:
<img width="443" alt="Screenshot 2021-09-13 at 5 01 31 PM" src="https://user-images.githubusercontent.com/51681618/133076285-3c5268d8-58b9-4d03-9209-2a503367f413.png">

Below is the payload for `rest/all/V1/orders`:

{
    "entity": {
        "entity_id":4,
        "extension_attributes": {
            "order_comment": "ABC1234"
        }
    }
}

Please try to reproduce it on Magento 2.4-develop and let us know if we missed anything in reproduction.

Thanks

**Comment by engcom-Hotel** [comment] 2021-09-27 07:31
Hello @mtwegrzycki,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2021-09-27 07:31 UTC
Labels: Issue:  Cannot Reproduce, Component: GraphQL, Triage: Dev.Experience, Issue: needs update
