### ISSUE TITLE
Admin area: function getUsedProducts of Configurable always  return children with salable true(even child already out stock)

### ISSUE THREAD

**Issue by hoangngo-calvin** [magento/magento2#34486] opened 2021-10-30 16:08 UTC
### Steps to reproduce (*)
1. Magento Open Source 2.4.3-p1 with sample data
2. 'Display Out of Stock Products' is set to "Yes"
3. Go to product has id: 54(child of 68), set stock to Out Stock(qty still 100).
4. Get children products of a configurable product in **Admin** area by using function getUsedProducts()
5. Get children products of a configurable product in **Frontend** area by using function getUsedProducts()
```
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->create(\Magento\Catalog\Model\Product::class);
$product->load(68);
$subProduct = $product->getTypeInstance()->getUsedProducts($product, null);
foreach ($subProduct as $child) {
    /** @var \Magento\Catalog\Model\Product $child */
    echo $child->getId() . ' - isSalable:  ' . ($child->isSalable() ?: '0') . '</br>';
}
die();
```

### Expected result (*)
1. child product(id: 54) should show salable: 0 in both: Admin and Frontend

### Actual result (*)
1. Admin: salable is 1
2. Frontend: salable is 0
![image](https://user-images.githubusercontent.com/31319355/139540630-eaafa90e-3829-4516-ae71-f58865a73db4.png)

---
Additional, but when I load product 54 directly by model class, it shows consistency for both Admin and Frontend which salable: 0
![image](https://user-images.githubusercontent.com/31319355/139540706-4d8fe8a1-3c25-448f-9dc8-83a37e762483.png)

**Comment by engcom-Hotel** [comment] 2021-11-15 12:21
Hi @hoangss,
Thank you for reporting the issue.

We have tried this issue on Magento 2.4-develop and we are successfully reproduced it.
Steps followed to reproduce issue:
1. Go to Store-> Configuration -> Inventory -> 'Display Out of Stock Products' is set to "Yes".
2. Select any configurable product from “Catalog -> Products”, Select child product from the associated products and set the stock to Out Stock(qty still 100). 
3. Get children products of a configurable product in Admin area by using function getUsedProducts() 
4. Get children products of a configurable product in the Frontend area by using function getUsedProducts()

Sample code: 
```
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$product = $objectManager->create(\Magento\Catalog\Model\Product::class);

$product->load(68);

$subProduct = $product->getTypeInstance()->getUsedProducts($product, null);

foreach ($subProduct as $child) {

    /** @var \Magento\Catalog\Model\Product $child */

    echo $child->getId() . ' - isSalable:  ' . ($child->isSalable() ?: '0') . '</br>';

}
```

5. Observe the salable property value to the frontend and admin area (See the attached screenshots).
6. Observation: saleble value is different for frontend and admin.

Hence confirming the issue.

Thanks

**Comment by engcom-Alfa** [comment] 2021-11-16 13:08
Hi @engcom-Hotel 
As per the community triage meeting, we have to identify the functional impact of the issue description in order to consider this as an issue.

Hi @hoangss Thanks for your contribution and collaboration!
Please help us providing the more information about the functional impact code issue.
Thanks in advance!

**Comment by hoangss** [comment] 2021-11-23 10:39
hi @engcom-Alfa thank you for replying. 
I would say if we have any logic that need to check salable of child product in admin area then it will be an issue.
> Eg: We want: when admin save Configurable product, if there are children out of stock we do this if not we do that....

**Comment by engcom-Alfa** [comment] 2021-12-09 10:29
Thanks for the information @hoangss !

Tried placing an order for a child product with out of stock status where parent product in stock. Found the proper out of stock error as expected.
The issue seems to be affected only for the described code usage.

Note: The _isSalable()_ method has been called in multiple places like : sales, catalog, wishlist, products (group/configurable/bundle), quotes and etc. Cross checked if there is any internal code to reset the value returned in the admin, but nothing found as such!

Additional Info:
isSalable() is internally identifying the product status (enabled/disabled),  product stock status and more!
As mentioned [above by reporter](https://github.com/magento/magento2/issues/34486#issuecomment-976386719), in case of custom code it might affect!

**Comment by IlyaCid** [comment] 2022-01-05 08:36
@magento I am working on this

**Comment by IlyaCid** [comment] 2022-01-05 08:37
@magento add to contributors team

**Comment by IlyaCid** [comment] 2022-01-05 08:38
@magento I am working on this

**Comment by coderimus** [comment] 2022-01-09 09:36
Hello @hoangss @IlyaCid 
This was an interesting task for investigation. I confirm that this issue relates to the represented code in the description. Let me describe my conclusion in detail. 

Represented logic in the simplified code in the description works for cases when you need to check "is the particular product available?" In the `\Magento\Catalog\Model\Product::isSalable` method the product status (available or not) is checked and doesn't take into account stock status. From the general business perspective, `product status !== stock` status. And product status has a higher priority: you can have products out of stock and available at the exact moment.
In the Magento admin we see the general availability of products and, if needed, detalisaiton to the stock status.

For the frontend area we have a different situation. We need to know if a product is in stock and our stock management configuration allows us to sell it. And, what is tricky, the `is_salable` value is set to the product object from the result of this query (`\Magento\CatalogInventory\Model\ResourceModel\Stock\Status::addStockDataToCollection`):
```sql
SELECT `e`.*, `link_table`.`parent_id`, `stock_status_index`.`stock_status` AS `is_salable`, `catalog_rule`.`rule_price` AS `catalog_rule_price` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_product_super_link` AS `link_table` ON link_table.product_id = e.entity_id
 INNER JOIN `catalog_product_website` AS `product_website` ON product_website.product_id = e.entity_id AND product_website.website_id = 1
 LEFT JOIN `cataloginventory_stock_status` AS `stock_status_index` ON e.entity_id = stock_status_index.product_id AND stock_status_index.website_id = 0 AND stock_status_index.stock_id = 1
 LEFT JOIN `catalogrule_product_price` AS `catalog_rule` ON catalog_rule.product_id = `e`.`entity_id` AND catalog_rule.website_id = '1' AND catalog_rule.customer_group_id = 0 AND catalog_rule.rule_date = '2022-01-06' WHERE (((`e`.`required_options` != 1) OR (`e`.`required_options` IS NULL))) AND (link_table.parent_id in (68)) AND (link_table.parent_id in (68))
```
Here, the `stock_status` value is an `is_salable` value. This is why you described you have different behaviour for the admin and frontend area.

So, if you need to check products salable status in the admin area you need to check their stock status and relation to backorders etc. But this is already done for any kind of operation with orders.

If you have questions, please, ask. If no questions are provided in the next five days I will close this issue.

**Closed as completed** 2022-01-19 08:03 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Progress: done, Area: Catalog, Reported on 2.4.3-p1
