### ISSUE TITLE
Cannot read contents from file "C:/xampp/htdocs/magento2/" Warning!file_get_contents(C:/xampp/htdocs/magento2/): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by berega** [magento/magento2#8002] opened 2016-12-30 16:37 UTC
when I try to change change the theme the following error is dispayed:

Cannot read contents from file "C:/xampp/htdocs/magento2/" Warning!file_get_contents(C:/xampp/htdocs/magento2/): failed to open stream: No such file or directory

How can I solve this problem?

**Comment by veloraven** [comment] 2017-01-03 09:26
@berega thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for some discussion and advice please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

**Comment by korostii** [comment] 2017-01-03 13:05
@berega The error seems awfully familiar, I think this is a duplicate of #5666
I would recommend you to try the workaround suggested in the comments to that issue - it worked for me.
By the way, it is a shame to see the very same bugs reported again and again, such amounts of time wasted on fighting them over and over again by so many people - all because the fixes take months to get released.

**Closed as completed** 2017-01-03 13:43 UTC
Labels: Progress: needs update

**Comment by suowang** [comment] 2017-02-24 13:09
When I try to switch a theme in localhost, I met the following error.
Cannot read contents from file "C:/xampp/htdocs/magento/" Warning!file_get_contents(C:/xampp/htdocs/magento/): failed to open stream: No such file or directory
My Magento version is 2.1.3.

I would like to know the reason.

**Comment by korostii** [comment] 2017-03-03 12:19
Hi @suowang please follow the link to issue #5666 I posted above. There's a [workaround in comments](https://github.com/magento/magento2/issues/5666#issuecomment-233195345), as well.
