### ISSUE TITLE
magento/module-catalog/Setup/Patch/Data/UpdateMultiselectAttributesBackendTypes.php breaks upgrade in migrated sites from 1.x

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#38036] opened 2023-10-03 11:03 UTC
### Preconditions and environment

- 2.4.6-p2

### Steps to reproduce

To replicate this you need

1. Magento 2 (e.g. 2.4.1) that was migrated from 1.x  and the 1.x instance had multiselect attributes with data (stored in _text table)
2. Use data migration tool to transfer the data which will copy the values from _text table to _varchar table during migration
3. Upgrade to 2.4.6-p2

The system will try to copy data from the _varchar table back to the _text table which was already migrated with the data migration tool to _text and to _varchar table. In the process you'll get this error about duplicate values 

### Expected result

Upgrade occurs properly

### Actual result

Duplicated values throw exceptions

![image](https://github.com/magento/magento2/assets/20220341/ad3735b5-4401-49a6-a421-b65f612a4da9)

### Additional information

There is only one real solution here, the patch needs to first clear the invalid data from _text table before migrating from _varchar to _text 

e.g. 

```sql
delete from catalog_product_entity_text where catalog_product_entity_text.attribute_id in (select eav_attribute.attribute_id from eav_attribute where eav_attribute.backend_type = 'varchar' and eav_attribute.entity_type_id = 4)
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment] 2023-10-06 07:29
> Use data migration tool to transfer the data which will copy the values from _text table to _varchar table during migration

Hmm, isn't the bug then in the data migration tool itself? Instead of _copying_ the values, it should _move_ them, so no duplicated values remain in the database?
In my opinion it's not a bug in the patch, but in the migration tool itself.

Or am I misunderstanding the issue?

**Comment by ioweb-gr** [comment] 2023-10-06 08:01
True but it's also a fact that people who upgraded M2 from M1 won't be able to upgrade to newer versions of Magento due to this patch so even if the data migration tool needs to be fixed, this patch should also guarantee a seemless upgrade experience as well

**Comment by hostep** [comment] 2023-10-06 10:25
Hmm maybe...

I recently ran into the [Magento 2 EAV Cleaner Console Command module](https://github.com/magento-hackathon/module-eavcleaner-m2) (which we needed for the `eav:attributes:restore-use-default-value` command after [a recent mistake in the mailchimp module](https://github.com/mailchimp/mc-magento2/issues/1758)).

But I have the suspicion that its `eav:clean:attributes-and-values-without-parent` command might be useful in your case to clean out the database...

If you're interested in trying it out, make sure to not execute it on production immediately and have backups ready in case it does stuff you don't want it to do.

**Comment by engcom-Bravo** [comment] 2023-10-13 07:27
Hello @ioweb-gr ,

Thanks for the report and collaboration!

For data-migration-related issues we are using the below board:

https://github.com/magento/data-migration-tool/issues

For your convenience, we have created this issue there. You can refer to the below link for the same:

https://github.com/magento/data-migration-tool/issues/919

We are closing this issue from here. Please follow the above URL for any updates on this.

Thanks

**Closed as completed by engcom-Bravo** 2023-10-13 07:27 UTC
Labels: Issue: ready for confirmation, Reported on 2.4.6-p2

**Comment by ioweb-gr** [comment] 2023-10-13 07:37
@engcom-Bravo This is not an issue for the data migration tool though. No code you change there will help users who already migrated solve this. The code that needs to be altered is the patch I mentioned

**Comment by ioweb-gr** [comment] 2023-10-13 07:40
Unless @engcom-Bravo your official stance is that people who upgraded in the past, should never go to latest magento versions and they should redo the migration even if they are active in Magento 2 for a few years,  I would suggest you reopen it.
