### ISSUE TITLE
Incorrect price calculation at Product View Page

### ISSUE THREAD

**Issue by d10nZ** [magento/magento2#12021] opened 2017-11-04 15:31 UTC
### Preconditions
1. Magento 2.1.9;
2. Magento-Sample-Data;
3. 1 web-site, 1 store and 2 store-views;
4. en-StoreView has currency USD and ua-StoreView has currency UAH (грн.);
5. Base currency for entire web-site is USD.
6. I defined CurrencyRate for pair USD/UAH = 2 (for example).

### Steps to reproduce
1. Go to the frontend -> Product View Page (choose any product).
2. Switch to StoreView "UA" with currency "UAH"
3. I see wrong Product Price in UAH currency.
4. If ProductPrice is $42.00 -> in UAH it equals to 42x2x2 = 168.00UAH

### Expected result
1. If base ProductPrice is $42.00 -> in UAH it should equal to 42x2 = 84.00UAH

### Actual result
![screenshot at 2017-11-04 19-25-24](https://user-images.githubusercontent.com/9153335/32406678-1e6effd2-c196-11e7-8e33-24c6f4fe9a60.png)

![screenshot at 2017-11-04 19-25-52](https://user-images.githubusercontent.com/9153335/32406680-26685936-c196-11e7-8db1-7efd40dc6760.png)

![screenshot at 2017-11-04 19-25-00](https://user-images.githubusercontent.com/9153335/32406681-2b636840-c196-11e7-9208-6357132d5ee1.png)

**Comment by magento-engcom-team** [comment] 2017-11-06 08:41
@d10nZ, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-11-06 08:41 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
