### ISSUE TITLE
Category Image getting removed every time you save it in Magento 2.3.3

### ISSUE THREAD

**Issue by jayanta88** [magento/magento2#26460] opened 2020-01-20 13:00 UTC
### Preconditions (*)
Magento community 2.3.3

### Steps to reproduce (*)
1. Go to Admin => Catalog => Categories => add category and add image.
2. Now you will see the image added in the category. Now hit the save button again. You will image disappeared. 

### Expected result (*)

1.  The image shouldn't disappear when we're changing other category attributes.

### Actual result (*)

1. Image getting disappears when you're saving other category attributes, not the image.

**Comment by jayanta88** [comment] 2020-01-20 13:08
@magento give me 2.3.3 instance

**Comment by jayanta88** [comment] 2020-01-20 13:12
@magento give me 2.3-develop instance

**Comment by valguss** [comment] 2020-01-20 13:22
duplicate of https://github.com/magento/magento2/issues/25099

**Comment by ajijshekh123** [comment] 2020-01-21 04:32
Give me @magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment] 2020-01-21 04:37
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment] 2020-01-21 04:49
@jayanta88 - This issue is relevant to the below issue.
https://github.com/magento/magento2/issues/25099
I am closing this issue. If this issue is not relevant to the above issue you can open it.

Thanks.

**Closed as completed** 2020-01-21 04:50 UTC
Labels: duplicate, Issue: Format is valid, Reported on 2.3.3

**Comment by magento-engcom-team** [comment] 2020-01-21 19:58
Hi @jayanta88. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment] 2020-01-21 19:58
Hi @jayanta88. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-21 19:58
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-21 19:59
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-21 20:04
Hi @jayanta88, here is your [Magento instance](https://i-26460-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26460-2-4-develop.instances.magento-community.engineering/admin_9762](https://i-26460-2-4-develop.instances.magento-community.engineering/admin_9762)
Login: `28de2c0a` Password: `6bcc4bbbccda`
Instance will be terminated in up to 3 hours.
