### ISSUE TITLE
Problem pulling up Sales - Order Menu - states Something went wrong with processing the default view and we have restored the filter to its original state.

### ISSUE THREAD

**Issue by Justin2532** [magento/magento2#36893] opened 2023-02-20 14:33 UTC
### Preconditions and environment

- Magento version 2.4.2
- Anything else that would help a developer reproduce the bug
- go to Sales -> Orders (states in pink Something went wrong with processing the default view and we have restored the filter to its original state.)
 

### Steps to reproduce

 go to Sales -> Orders (states in pink Something went wrong with processing the default view and we have restored the filter to its original state.)

### Expected result

 go to Sales -> Orders (states in pink Something went wrong with processing the default view and we have restored the filter to its original state.)

### Actual result

 go to Sales -> Orders (states in pink Something went wrong with processing the default view and we have restored the filter to its original state.)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-02-20 17:45
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-02-21 07:15
Hi @Justin2532,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

We are able to get the orders form admin side.


<img width="1475" alt="Screenshot 2023-02-21 at 12 44 05 PM" src="https://user-images.githubusercontent.com/51680745/220273947-7f8e65fd-f836-436c-87c7-438af44d6851.png">



Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-03-06 04:45
Hi @Justin2532,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-03-06 04:45 UTC
Labels: Issue: needs update, Reported on 2.4.2
