### ISSUE TITLE
Up

### ISSUE THREAD

**Issue by rudik99** [magento/magento2#4758] opened 2016-05-29 09:11 UTC
## Steps to reproduce
1. Install Magento from `main` branch. Problem exists from ver 2.0.0 to 2.0.7
2. Go to Products > Catalog 
3. Select two or more products and choose "update attributes"
4. Select any field that has [Inc. Tax] or similar tool tip
5. Start typing
## Actual result
1. Text that you are typing is been hidden by the "tip"
## Expected result
1. The [Inc. Tax] or similar, either disappears or the text you type is to the right of it. 
2. Or the label is moved somewhere else.

I have searched and couldnt find this reported to date.

![screen shot 2016-05-29 at 6 43 54 pm](https://cloud.githubusercontent.com/assets/9780829/15632317/1f8e5514-25d1-11e6-8284-37bef3f016e5.png)

**Comment by vil11** [comment] 2016-06-13 16:09
Internal ticket **MAGETWO-54324**.

## 

:sunny: dvilchynskyi, M2 QA.

**Comment by magento-engcom-team** [comment] 2017-09-20 22:16
@rkhoury82, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:16 UTC
Labels: Issue: Ready for Work, bug report, Fixed in 2.2.x, Issue: Format is not valid
