### ISSUE TITLE
Cannot save product in store view scope without Magento_Catalog::edit_product_design ACL

### ISSUE THREAD

**Issue by kassner** [magento/magento2#28106] opened 2020-05-05 09:59 UTC
### Preconditions

1. Magento Open Source 2.4-develop from GitHub (6b6f428c4b938c209658eb5d75d84b72503cbce0);
2. Default installation without sample data;
3. A second website+store+store view is configured;

### Steps to reproduce

1. Under System > Permissions > User Roles, create a new role with the entire `Catalog` tree selected, except for `Catalog > Inventory > Products > Edit Product Design`;

![](https://user-images.githubusercontent.com/301255/81301052-d3140000-9078-11ea-8c10-dbaf3e7e6f64.png)

2. Create a user assigned to this new role and log into the backend with it;
3. Add a simple product with title `test 1`. Under `Products in Websites`, select both websites. Save the product;
4. Still in the product edit form, change the scope to the second store view;
5. Under the `Design` tab, check that you are indeed not allowed to change the attributes (fields are disabled):

![Screenshot from 2020-05-05 11-43-57](https://user-images.githubusercontent.com/301255/81053716-ce5b1a80-8ec5-11ea-80e9-48e284f59870.png)

6. For the Name field, uncheck the `Use Default Value` option and give it a new name (i.e.: `test 2`);
7. Save the product;

### Expected result

1. The new name was saved for the selected store view;

### Actual result

1. `Not allowed to edit the product's design attributes` error.

![Screenshot from 2020-05-05 11-49-12](https://user-images.githubusercontent.com/301255/81054112-7b359780-8ec6-11ea-81bd-08d64e862eb2.png)

The same happens for other fields, like product name or description.

### Additional information
- steps with screens on the latest `2.4-develop`  https://github.com/magento/magento2/issues/28106#issuecomment-625654478

**Comment by swathishs** [comment] 2020-05-07 06:44
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-07 06:44
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-05-07 06:45
Hi @swathishs, here is your [Magento instance](https://i-28106-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28106-2-4-develop.instances.magento-community.engineering/admin_2aea](https://i-28106-2-4-develop.instances.magento-community.engineering/admin_2aea)
Login: `30a5c8a3` Password: `bac7e7f897aa`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment] 2020-05-07 12:18
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-07 12:18
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-05-07 12:19
Hi @swathishs, here is your [Magento instance](https://i-28106-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28106-2-4-develop.instances.magento-community.engineering/admin_548b](https://i-28106-2-4-develop.instances.magento-community.engineering/admin_548b)
Login: `9b911112` Password: `764e194d422a`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment] 2020-05-07 13:19
I'm unable to reproduce this issue on the 2.4-develop instance.

Please find the attachments for reference

**Configured second website** :
![image](https://user-images.githubusercontent.com/58288685/81296777-0ca43580-9090-11ea-95a7-4e405d4525c1.png)
 
**New product**:
![image](https://user-images.githubusercontent.com/58288685/81297105-6efd3600-9090-11ea-8fb6-97e5e4f55d3a.png)

**Viedo for reference**:
https://drive.google.com/file/d/19y5y2T54RzOkPGb99soQ_nohq90dxB3p/view?usp=sharing

**Comment by kassner** [comment] 2020-05-07 13:37
@swathishs Your user still has permissions to `Edit Product Design`. All fields in the Design tab should be disabled but in your video they aren't.

**Comment by kassner** [comment] 2020-05-07 13:38
@swathishs this is how the role should look like

![Screenshot from 2020-05-07 15-38-00](https://user-images.githubusercontent.com/301255/81301052-d3140000-9078-11ea-8c10-dbaf3e7e6f64.png)

**Comment by swathishs** [comment] 2020-05-07 14:34
@kassner Okay  I will try with this role and let you know

**Comment by swathishs** [comment] 2020-05-07 15:19
@kassner: As per the role which you have suggested I have tired the issue is reproducible in 2.4-develop instance

Attachments:
![image](https://user-images.githubusercontent.com/58288685/81312309-1f286a00-90a4-11ea-92a4-a3ba68751335.png)

![image](https://user-images.githubusercontent.com/58288685/81312344-2b142c00-90a4-11ea-823f-09edccd9720f.png)

![image](https://user-images.githubusercontent.com/58288685/81312372-323b3a00-90a4-11ea-9d4a-fa42271af492.png)

**Comment by magento-engcom-team** [comment] 2020-05-07 15:20
@swathishs Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by swathishs** [comment] 2020-05-08 05:01
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-08 05:01
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-05-08 05:02
Hi @swathishs, here is your [Magento instance](https://i-28106-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28106-2-4-develop.instances.magento-community.engineering/admin_05e7](https://i-28106-2-4-develop.instances.magento-community.engineering/admin_05e7)
Login: `935429d0` Password: `fb8dd6fe8465`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment] 2020-05-08 06:19
I am able to reproduce the issue in 2.4 develop instance

**Please refer the attachments**:-

Configured two stores:
![image](https://user-images.githubusercontent.com/58288685/81376544-5db03a00-9121-11ea-8373-8964a9f50660.png)

**Created a new role** :
![image](https://user-images.githubusercontent.com/58288685/81376574-71f43700-9121-11ea-8a64-7068e1d788e6.png)

**Created new user and assign the role** : 
![image](https://user-images.githubusercontent.com/58288685/81376619-8f290580-9121-11ea-92cd-f54fd695b687.png)

**Created new product and assigned to two stores**:
![image](https://user-images.githubusercontent.com/58288685/81376671-a8ca4d00-9121-11ea-8a69-05288b602bb7.png)
![image](https://user-images.githubusercontent.com/58288685/81376688-b253b500-9121-11ea-9dd8-8460b182fb4e.png)

Unable to change the product **name:**
![image](https://user-images.githubusercontent.com/58288685/81376791-dc0cdc00-9121-11ea-831e-c5a2e1714eb1.png)

**Comment by magento-engcom-team** [comment] 2020-05-08 06:21
:white_check_mark: Confirmed by @swathishs 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34156` were created

**Issue Available**: @swathishs, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by KiuNguyen** [comment] 2020-05-13 03:29
@magento I am working on this

**Comment by kassner** [comment] 2020-10-23 12:29
Which pull request fixed this issue?

**Comment by magento-engcom-team** [comment] 2020-10-23 15:52
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34156` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment] 2020-10-23 15:59
@kassner

The issue was closed by mistake.
at this moment Magento team has fixed it, internal PR is ready(CR and QA passed) but not merged into the main code-base.
As soon as it will be merged related commits can be found using search based on internal ticket key `MC-34156`
Example: https://github.com/magento/magento2/search?q=MC-34156&type=commits

Sorry for inconvenience

**Closed as completed** 2020-11-04 11:31 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Component: Admin, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P2, Severity: S2, Triage: Done, Progress: done, Reported on 2.4.0

**Comment by zakdma** [comment] 2020-11-04 11:35
Internal ticket MC-34156 merged into mainline

**Comment by sdzhepa** [comment] 2020-11-05 20:10
The related internal Jira ticket `MC-34156` was closed as `Fixed`.
Related commits can be found by search https://github.com/magento/magento2/search?q=MC-34156&type=commits
