### ISSUE TITLE
Export CSV with duplicated lines (ExportAbandonedCsv function)

### ISSUE THREAD

**Issue by gelado** [magento/magento2#35552] opened 2022-05-30 12:45 UTC
### Preconditions and environment

- Magento 2.4.4
- A lot of orders and customers on the database

### Steps to reproduce

1. Navigate to admin panel in Magento.
2. Go to Reports -> Abandoned Carts.
3. On my case, I have +10.000 abandoned carts (This problem does not occour on other instances with less carts)
4. Create a filter to export less data (Column Created: From May 29 to May 30).
5. Click on Search (Now I have 1000 records found)
6. Leave "Export to:" as "CSV" and click on Export.

### Expected result

CSV file with the abadoned carts on that period (+-1000 records).

### Actual result

A CSV file with duplicated lines for each customer (+- 2000 records)

![Captura de tela 2022-05-30 092645](https://user-images.githubusercontent.com/3117983/170992174-ceb73d68-1a45-4423-adff-9b46a4220e12.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment] 2022-06-29 13:06
Hi @gelado 

Thanks for your contribution and collaboration.
I tried to reproduce this issue. But I am unable to reproduce. I followed the mentioned steps-

**Preconditions and environment**

- Magento 2.4.4
- A lot of orders and customers on the database

**Steps to reproduce:**

1. Navigate to admin panel in Magento.
2. Go to Reports >> Abandoned Carts.
3. On my case, I have 1500 abandoned carts
4. Leave "Export to:" as "CSV" and click on Export.

I am not getting a CSV file with duplicated lines for each customer. Please refer the screenshots.

![image](https://user-images.githubusercontent.com/60198022/176442806-7f0bf0b0-fd58-43d3-8a1a-44710f2c83a9.png)
![image](https://user-images.githubusercontent.com/60198022/176442830-e923f9d4-b7c8-4376-baef-73f677084530.png)

Kindly provide some more information if anything got missed.

**Comment by gelado** [comment] 2022-07-12 19:44
Hi, @engcom-Lima! On your csv screenshot I can see the same number of lines, but a lot of duplicated lines for same customer. Is this expected?

**Comment by engcom-Lima** [comment] 2022-07-19 14:17
Hi @gelado 

I have tried to reproduce the issue but unable to reproudce it.
Tried to reproduce with different type of customers and multiple products also at different **times** but I couldn't reproduce the issue.
Below is the screenshots:
**In abandoned cart report**
![image](https://user-images.githubusercontent.com/60198022/179772061-788d6e69-6928-418a-b4c6-cb4678eb84e0.png)

**In CSV file**
![image](https://user-images.githubusercontent.com/60198022/179772304-ae4ef3c4-aee9-4b86-85eb-ec02280f00f3.png)

Is this necessary to create orders more than 1000, if so can you provide us information.
Also try to reproduce the issue in latest `2.4-develop`.

Thanks

**Comment by engcom-Lima** [comment] 2022-08-02 12:01
Hi @gelado ,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Lima** 2022-08-02 12:01 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
