### ISSUE TITLE
Magento 2.4-x - Changing any configuration from admin and reindex - version changing to 1.0.0+no-version-set

### ISSUE THREAD

**Issue by engcom-November** [magento/magento2#35353] opened 2022-04-22 13:26 UTC
### Preconditions (*)

2.4-develop branch

### Steps to reproduce (*)

**Intermittent issue:** Changing any Store configuration from admin in 2.4-develop branch - reindex and cache flush - 2.4-develop version is getting changed to 1.0.0+no-version-set
1. Ex: Set the Price scope to website and save  (Stores - Configuration - Catalog - Catalog)
2. Reindex and cache flush
3. Setup multi store (with different websites) [ref doc](https://devdocs.magento.com/guides/v2.4/config-guide/multi-site/ms_websites.html)
4. reindex and cache flush

### Expected result (*)

1. [Screenshots, logs or description]
2. Version should remain 2.4-develop

### Actual result (*)

1. Version changing back to 1.0.0+no-version-set
![image](https://user-images.githubusercontent.com/60198231/164723157-efcfec1e-a2ac-4d48-a2de-fc64ac09cd3a.png)
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2022-04-25 08:52
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-04-25 09:05
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-04-25 09:17
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-04-25 10:11
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-04-26 05:51
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-04-26 05:56
@magento give me 2.4-develop instance

**Comment by slavvka** [comment] 2022-04-26 16:18
@magento give me 2.4-develop instance

**Comment by slavvka** [comment] 2022-04-26 16:40
@magento give me 2.4-develop instance
without magento-commerce/magento2-sample-data, magento-commerce/magento2-sample-data-ee

**Comment by slavvka** [comment] 2022-04-26 17:52
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-04-28 11:38
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-05-04 11:58
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-05-04 12:28
Hello @engcom-November,

We have tried to reproduce the issue on the cloud Magento 2.4-develop instance with the mentioned steps but for us, the version is not changing. Please have a look at the below screenshots for reference:

### Initial dashboard when Magento instance prepared:
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/51681618/166680955-9abd5912-21a5-4dd5-838c-4aa7a8518bb6.png">

### After making changes in the configuration as well as creating stores referring [this article](https://devdocs.magento.com/guides/v2.4/config-guide/multi-site/ms_websites.html):

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/51681618/166681149-f8975116-0423-425e-9575-8d02895f71c0.png">

Please let us know in case we have missed anything.

Thanks

**Comment by engcom-November** [comment] 2022-05-05 10:31
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-05-05 11:41
Hi @engcom-Hotel ,
Unable to reproduce the issue on Magento cloud instance but is reproducible to me when cloned from [repository.](https://github.com/magento/magento2) Verified this today by downloading 2.4-develop from https://github.com/magento/magento2/ and is still reproducible. Kindly recheck.
Thank you.

**Comment by engcom-Dash** [comment] 2022-05-21 05:50
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-05-23 07:00
@magento Give me 2.4-Develop Instance

**Comment by engcom-Dash** [comment] 2022-05-24 01:58
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-05-24 02:37
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-05-24 03:46
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-05-24 04:34
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-05-24 05:41
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-05-24 05:41
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-05-24 06:30
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-05-24 10:38
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-05-24 11:21
@magento give me 2.4-develop instance

**Comment by Zaahed** [comment] 2022-06-28 06:58
@magento I'm working on this

**Comment by Zaahed** [comment] 2022-07-26 15:56
This only happens on my local environment if the current working directory `getcwd()` is not set to the Magento 2 root directory. See line 306 in the `Composer/Factory` class. If you set `$cwd` to the Magento 2 root directory, it will return the correct version, even after flushing the cache.

**Comment by engcom-Bravo** [comment] 2024-10-15 05:11
Hi @engcom-November,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Version remains 2.4-develop.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-10-15 05:11 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Account
