### ISSUE TITLE
Swatches Break Mouse Down Scroll (Auto Scroll) On Browsers

### ISSUE THREAD

**Issue by harrigo** [magento/magento2#32895] opened 2021-04-28 14:55 UTC
Scroll wheel click & hold and keep mouse cursor moving up & down or left & right (auto scroll) on category pages and product pages with swatches does not activate when clicking in scroll wheel.

Seems to be caused by a mousedown event linked to main html element from jquery.mobile.custom.js (209), which I am assuming is triggered by something to do with Swatches as these seem to be present on every broken page. Removing the event seems allows auto scroll and event seems to be present on most Magento versions. 

I checked a few demo stores online and all showcased this issue. Not a massive issue but I find it a bit annoying as is my preferred method of scrolling and speeds up gives more control with less effort especially if infinite scrolls implemented. 

Note: What is Auto Scroll - https://superuser.com/questions/477168/is-there-a-name-for-scrolling-by-middle-click-rather-than-spinning-the-wheel#:~:text=%22auto%2Dscroll%22%2C,in%20most%20mainstream%20modern%20applications.&text=In%20this%20mode%2C%20moving%20the,and%20the%20mouse%20press%20location

### Preconditions (*)
1. Magento 2.2.7 - 2.4.2 tested 
2. Chrome / Firefox etc.

### Steps to reproduce (*)
1. Navigate to a category page with swatches in layered navigation or product list / product page with swatches
2. Try middle click (push down scroll wheel) and move mouse

### Expected result (*)
1. Clicking in scroll wheel and moving mouse allows page scroll

### Actual result (*)
1. No Scroll page stays still

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ 1 ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by harrigo** [comment] 2021-04-28 14:56
@magento give me 2.4-develop instance

**Comment by harrigo** [comment] 2021-04-28 14:58
@magento give me 2.3-develop instance

**Comment by harrigo** [comment] 2021-04-29 07:20
@magento give me 2.3-develop instance

**Comment by engcom-Alfa** [comment] 2021-05-18 05:31
@harrigo 
I am trying to reproduce in various aspects. Unable to do. Below is the sample screen record that I tried.

https://user-images.githubusercontent.com/51679138/118595209-442bde80-b7c8-11eb-84e1-c7daf380c2c2.mp4

So, kindly make a detailed reproducible steps and possibly a screen recoding as well since it is something related to improper UI response.

**Comment by harrigo** [comment] 2021-05-18 20:11
Thanks for taking a look.

Is this auto scroll you are trying as mouse icon normally changes to 2
arrows atleast on windows?

Auto scroll is what I believe it to be called and involves holding down
scroll wheel and dragging mouse in desired scroll direction and not
actually scrolling the scroll wheel.

**Comment by engcom-Alfa** [comment] 2021-05-21 11:32
Hi @harrigo,

As per my above commented attached screen record, Just expanded the visual swatch from the navigation and the screen auto-scrolled.
Well I have an other way attached here below.

https://user-images.githubusercontent.com/51679138/119130741-368b8880-ba56-11eb-8e40-54f15d111ef9.mp4

As per this screen record, I am just clicking on the scroller down arrow and the page is getting auto-scrolled.
As I checked it is the proper behavior.

**If you are expected anything else, kindly attached a screen record of the issue you are facing since it is related to a edge UI behavior, as I requested in my previous comment.**

**Comment by harrigo** [comment] 2021-05-21 18:20
Ah no I don't mean that, it's nothing to do with clicking Swatches etc auto
scroll is a general method of scrolling on applications etc. Users can
click (and hold) middle scroll and drag mouse to scroll kinda like panning
pages with mouse.


https://superuser.com/questions/477168/is-there-a-name-for-scrolling-by-middle-click-rather-than-spinning-the-wheel#:~:text=%22auto%2Dscroll%22%2C,in%20most%20mainstream%20modern%20applications.&text=In%20this%20mode%2C%20moving%20the,and%20the%20mouse%20press%20location
.

Maybe that explains what I mean. However that does not work for me on any
page with a Swatch on it from what I can tell.

**Comment by engcom-Alfa** [comment] 2021-05-24 07:24
Thanks for the reply @harrigo 
Updated the description and confirming the issue.

**Comment by magento-engcom-team** [comment] 2021-05-24 07:25
@engcom-Alfa Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-05-24 07:25
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-05-24 07:25
@engcom-Alfa Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-05-24 07:26
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-05-24 07:33
@engcom-Alfa Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-05-24 07:33
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-05-24 07:35
@engcom-Alfa Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-05-24 07:35
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-05-24 07:35
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-05-24 07:36
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42400` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment] 2024-08-20 10:12
Hi @harrigo,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-08-20 10:12 UTC
Labels: Issue: Confirmed, Component: Ui, Reproduced on 2.4.x, Priority: P3, Progress: done, Reported on 2.4.x
