### ISSUE TITLE
add to cart button is grey in product listing page

### ISSUE THREAD

**Issue by colyield** [magento/magento2#32976] opened 2021-05-09 02:12 UTC
### Preconditions (*)

1. magento 2.4.2, upgraded from 2.4.1
2.

### Steps to reproduce (*)

1. No extension installed, very simple theme without any JS modified. The add to cart button is gray, not clickable.
2. Even if changed to the Luma theme, still same problem.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
![Untitled](https://user-images.githubusercontent.com/18225064/117558315-685e2180-b04a-11eb-8f8f-8130f59f2aa7.png)
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment] 2021-05-09 09:20
Can you share online store link related ?

**Comment by colyield** [comment] 2021-05-09 17:47
I can PM you the website,  if you want. I prefer not to not publish it on
the internet.

Thanks,
Andy

**Comment by mrtuvn** [comment] 2021-05-10 12:17
my suggestion is remove all files in vendor folder and re-run composer install again

rm -rf vendor/*
composer install

If your store live better clone to development site and re-check

**Comment by mrtuvn** [comment] 2021-05-10 14:16
![detail-Profile-20210510T211418](https://user-images.githubusercontent.com/1908873/117673391-f5cd7d00-b1d4-11eb-83f7-50fd30c5c7ea.gif)
quick gif show page product detail store 2.4.2

**Comment by colyield** [comment] 2021-05-10 23:14
Same bug report on this link https://magento.stackexchange.com/questions/331719/magento-2-4-2-addtocart-button-disabled

**Comment by colyield** [comment] 2021-05-11 03:58
> ![detail-Profile-20210510T211418](https://user-images.githubusercontent.com/1908873/117673391-f5cd7d00-b1d4-11eb-83f7-50fd30c5c7ea.gif)
> quick gif show page product detail store 2.4.2 (Luma Theme)
> 
> ![blank-Profile-20210510T212055](https://user-images.githubusercontent.com/1908873/117674306-c23f2280-b1d5-11eb-8f93-174936245447.gif)
> Here is Category listing page (Blank Theme)

I also tried the blank theme, same problem.
![Screenshot 2021-05-10 235629](https://user-images.githubusercontent.com/18225064/117756171-a9416c00-b1eb-11eb-8846-cf969cc2d7f0.jpg)

**Comment by mrtuvn** [comment] 2021-05-15 00:53
in frontend category page can you view error in console browser ?

**Comment by colyield** [comment] 2021-05-15 04:08
Yes, there are many errors. Some errors are caused by the tawk.to online
chat widget, I disabled it. The others were caused by the google recaptcha.
So I also deleted the google recaptcha settings for the front pages. Now
there's no error message in the console browser. But the add to cart button
on the category page is still not working.

If I leave the online chat widget on, then there are many errors like below.
[Report Only] Refused to load the script '
https://cdn.jsdelivr.net/emojione/2.2.7/lib/js/emojione.min.js' because it
violates the following Content Security Policy directive: "script-src
assets.adobedtm.com secure.authorize.net test.authorize.net
www.googleadservices.com www.google-analytics.com www.paypalobjects.com
js.braintreegateway.com www.paypal.com geostag.cardinalcommerce.com
1eafstag.cardinalcommerce.com geoapi.cardinalcommerce.com
1eafapi.cardinalcommerce.com songbird.cardinalcommerce.com
includestest.ccdc02.com www.sandbox.paypal.com t.paypal.com s.ytimg.com
video.google.com vimeo.com www.vimeo.com www.youtube.com *.
payments-amazon.com *.payments-amazon.co.uk *.payments-amazon.co.jp *.
payments-amazon.jp *.payments-amazon.it *.payments-amazon.fr *.
payments-amazon.es *.payments-amazon.de *.trackedlink.net *.trackedweb.net
*.dotdigital-pages.com cdn.dnky.co api.comapi.com webchat.dotdigital.com *.
yotpo.com 'self' 'unsafe-inline' 'unsafe-eval'". Note that
'script-src-elem' was not explicitly set, so 'script-src' is used as a
fallback.

**Comment by mrtuvn** [comment] 2021-05-16 05:12
blank content in backend theme view detail page meaning something broken. Maybe error happen in php

**Comment by colyield** [comment] 2021-05-16 08:05
I spent a long time upgrading the magento from 2.4.1 to 2.4.2 again, and
tried everything I can, no answer.

**Comment by mrtuvn** [comment] 2021-05-16 08:33
I tried test setup my local magento vanilla (luma) from 2.4.1 and upgrade to 2.4.2 (no additional theme or module) but cart button working fine from my local. I can't reproduce same as your case. If you have dev internal team let double check any previously works may touch to cart function

**Comment by colyield** [comment] 2021-05-16 21:16
We don't have any clue how to identify the problem.....

**Comment by colyield** [comment] 2021-05-18 04:16
Instead of using composer, I downloaded the 2.4.2 version from the Magento website and overwrite the files on the server, and setup/compile, now the backend for the theme-view is different, but the tabs are still not working. When click the tabs, nothing happened.

![Screenshot 2021-05-18 001145](https://user-images.githubusercontent.com/18225064/118589379-482b1280-b76e-11eb-8ae0-1ff4f426319f.jpg)
https://github.com/magento/magento2/issues/32970#issuecomment-842811515

**Comment by colyield** [comment] 2021-06-25 13:06
I don't think you can reproduce it if you install a fresh magento store.
There must be something in the database when upgrading causing the problem.
I tried to upgrade using composer, also tried to download the new version
directly from magento website and replace all the files to update the
store, slightly different results I got, but the "Add to Cart" did not work
in either way.

**Comment by engcom-Delta** [comment] 2021-07-08 14:31
Hi @colyield,

Tried reproducing the issue and found the it is reproducible in Magento 2.4.2 .

Followed steps:
1. installed Magento 2.4.1 
2. Create the new product with color attributes
3. upgraded to 2.4.2 by following commands
4. bin/magento maintenance:enable
composer require magento/composer-root-update-plugin=~1.0 --no-update
composer update
cp composer.json composer.json.bak
composer require magento/product-community-edition=2.4.2 --no-update
composer update
bin/magento maintenance:disable
5. Go to Product Listing page or search the product created step 2 
6. Open the front end & observed that 'add to cart' button in Product listing page is disabled.

Hence added the label 'Issue confirmed'.

Please find the attached snapshots for reference.
![Magento 2 4 1](https://user-images.githubusercontent.com/51681379/124939875-1bd19b00-e027-11eb-953f-24450d52bcdc.jpg)
![Magento 2 4 2](https://user-images.githubusercontent.com/51681379/124939951-2c821100-e027-11eb-9e45-e8d37f9b83c7.jpg)
![Magento 2 4 2_AddtoCartButton](https://user-images.githubusercontent.com/51681379/124939986-3572e280-e027-11eb-8074-65716d7251b5.jpg)

**Comment by colyield** [comment] 2021-07-08 15:27
> Hi @colyield,
> 
> Tried reproducing the issue and found the it is reproducible in Magento 2.4.2 .
> 
> Followed steps:
> 
> 1. installed Magento 2.4.1
> 2. Create the new product with color attributes
> 3. upgraded to 2.4.2 by following commands
> 4. bin/magento maintenance:enable
>    composer require magento/composer-root-update-plugin=~1.0 --no-update
>    composer update
>    cp composer.json composer.json.bak
>    composer require magento/product-community-edition=2.4.2 --no-update
>    composer update
>    bin/magento maintenance:disable
> 5. Go to Product Listing page or search the product created step 2
> 6. Open the front end & observed that 'add to cart' button in Product listing page is disabled.
> 
> Hence added the label 'Issue confirmed'.
> 
> Please find the attached snapshots for reference.
> ![Magento 2 4 1](https://user-images.githubusercontent.com/51681379/124939875-1bd19b00-e027-11eb-953f-24450d52bcdc.jpg)
> ![Magento 2 4 2](https://user-images.githubusercontent.com/51681379/124939951-2c821100-e027-11eb-9e45-e8d37f9b83c7.jpg)
> ![Magento 2 4 2_AddtoCartButton](https://user-images.githubusercontent.com/51681379/124939986-3572e280-e027-11eb-8074-65716d7251b5.jpg)

Good to know. Finally it's possible to fix the issue. Any thought on the theme information missing in the backend ? I think the two problems might be related. https://github.com/magento/magento2/issues/32970

**Comment by sdzhepa** [comment] 2021-07-13 17:58
Hello @engcom-Delta
cc:  @colyield 

Thank you for your work and collaboration!
Could you please update the Issue description with content from https://github.com/magento/magento2/issues/32976#issuecomment-876489389 ?


IMHO: steps described in the comment, after your investigation, are more clear transparent. And could help any next person who will work on this issue.

Thank you in advance!

**Comment by magento-engcom-team** [comment] 2021-07-18 04:27
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42871` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Delta** [comment] 2021-08-09 09:57
Hi ,
Issue has been reverified as per Gabriel's request. Issue is not reproducible when upgrading to Magento 2.4.2 from Magento 2.4.1 .Please find the attached screen shots for reference.
![ProductCreatedin2 4 1](https://user-images.githubusercontent.com/51681379/128689236-5dce919b-3601-4c25-b1b0-d1dee6833906.JPG)

After upgrating: 
![upgraded to 2 4 2](https://user-images.githubusercontent.com/51681379/128689300-776b7220-ea4b-4d2e-9788-d3090351f599.JPG)

Add to cart button:
![addtocartButton](https://user-images.githubusercontent.com/51681379/128689361-e35ec1a8-8ac9-41ca-862a-77454c7c3208.jpg)

Hence added the label 'Needs update'

Thanks

**Closed as completed** 2021-08-26 07:42 UTC
Labels: Component: ProductAlert, Priority: P2, Progress: done, Issue: needs update, Reported on 2.4.2, Reproduced on 2.4.2
