### ISSUE TITLE
Free shipping discount is not exposed with GraphQL

### ISSUE THREAD

**Issue by bartoszherba** [magento/magento2#35571] opened 2022-06-02 09:19 UTC
### Preconditions and environment

- 2.4.2

### Steps to reproduce

1. Make sure that you have a Free Shipping discount set
2. Add products to the cart with the total amount exceeding the discount threshold
3. Make a GraphQL query (example at the very bottom of reproduction steps), make sure to add `prices.discounts` field.
4. Observe that for the `cart` or `customerCart` query, the `prices.discounts` is empty even though the free shipping discount was added.

```
query customerCart {
    customerCart {
      id
      email
      is_virtual
      applied_coupons {
        code
      }
      prices {
        subtotal_excluding_tax {
          value
        },
        subtotal_including_tax {
          value
        },
        applied_taxes {
          amount {
            value
          },
          label
        }
        discounts {
          amount {
            value
          },
          label
        }
        grand_total {
          value
        }
      }
      items {
        uid
        product {
          uid
          __typename
          sku
          name
          stock_status
          only_x_left_in_stock
          rating_summary
          thumbnail {
            url
            position
            disabled
            label
          }
          url_key
          url_rewrites {
            url
          }
          price_range {
            maximum_price {
              final_price {
                currency
                value
              }
              regular_price {
                currency
                value
              }
            }
            minimum_price {
              final_price {
                currency
                value
              }
              regular_price {
                currency
                value
              }
            }
          }
          categories {
            uid
            name
            url_suffix
            url_path
            breadcrumbs {
              category_name,
              category_url_path
            }
          }
          review_count
          reviews {
            items {
              average_rating
              ratings_breakdown {
                name
                value
              }
            }
          }
        }
        prices {
          row_total {
            value
          }
          row_total_including_tax {
            value
          }
          total_item_discount {
            value
          }
        }
        quantity
        ... on ConfigurableCartItem {
          configurable_options {
            configurable_product_option_uid
            option_label
            configurable_product_option_value_uid
            value_label
          }
          configured_variant {
            sku
            thumbnail {
              url
            }
          }
        }
        ... on BundleCartItem {
          bundle_options {
            uid
            label
            type
            values {
              id
              label
              price
              quantity
            }
          }
        }
      }
      total_quantity
      shipping_addresses {
        firstname
        lastname
        street
        city
        company
        region {
          code
          region_id
          label
        }
        postcode
        telephone
        country {
          code
          label
        }
        selected_shipping_method {
          carrier_code
          carrier_title
          method_code
          method_title
          amount {
            value
            currency
          }
        }
      }
      billing_address {
        firstname
        lastname
        street
        city
        company
        region {
          code
          region_id
          label
        }
        postcode
        telephone
        country {
          code
          label
        }
      }
    }
  }
```

### Expected result

To align with the rest of the discounts like a coupon or cart rules, I would expect to have a shipping discount added to the discounts list or be able to somehow get the discounted shipping value. But neither is possible.

### Actual result

Cart free shipping discount is not available in the discounts array.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-06-06 12:26
Hi @bartoszherba ,
Thank you for reporting and collaboration. This issue seems to be a duplicate of issue: https://github.com/magento/magento2/issues/35545. However this issue exists even if  "Free Shipping" is set to "No" in cart price rule. Discount applied on Shipping amount is ignored in graphql response.
Please confirm and elaborate steps to reproduce if its a different issue.
Thank you.

**Comment by engcom-November** [comment] 2022-06-20 06:00
Hi @bartoszherba ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you

**Closed as completed by engcom-November** 2022-06-20 06:00 UTC
Labels: Issue: needs update
