### ISSUE TITLE
No backorder notification with backorder set to "Allow Qty Below 0 and Notify Customer" & Out-of-Stock Threshold set to Negative value

### ISSUE THREAD

**Issue by vishwanathkharabe** [magento/magento2#36727] opened 2023-01-11 08:37 UTC
### Preconditions and environment

- Magento version : 2.4.3 EE On-premise

### Steps to reproduce

Make below settings for Backorders

1. set Backorders to "Allow Qty Below 0 and Notify Customer"
2. set Out-of-Stock Threshold to  any "Negative amount" as recommended 
reference doc [devdocs](https://experienceleague.adobe.com/docs/commerce-admin/inventory/configuration/backorders.html)

### Expected result

A backorder notifications reading
"We don't have as many quantity as you requested, but we'll back order the remaining {qty}"
should be shown in mini cart, cart page and on checkout page
![expected_result](https://user-images.githubusercontent.com/80893055/211757541-e6a7434b-7223-4c4d-a67f-234dc92245fb.png)

### Actual result

No back order notification is shown
![no_notification](https://user-images.githubusercontent.com/80893055/211757051-eb25f84e-2b1e-4527-80bd-b7e068e7fd6d.png)
![backorder_setting](https://user-images.githubusercontent.com/80893055/211757137-7dde08bc-f525-4a9a-b24d-a6d27826038b.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-01-11 10:28
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-01-11 14:10
HI @vishwanathkharabe,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


We are getting Backorder notifications.



<img width="982" alt="Screenshot 2023-01-11 at 5 43 57 PM" src="https://user-images.githubusercontent.com/51680745/211827329-d429223f-cd41-4631-ad89-3ebdd8fff01b.png">




<img width="1375" alt="Screenshot 2023-01-11 at 4 58 58 PM" src="https://user-images.githubusercontent.com/51680745/211827178-a0d6320b-9e1e-4709-9862-b97eabec6b48.png">


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by vishwanathkharabe** [comment] 2023-01-12 13:09
Hi @engcom-Bravo ,
Thanks! for taking up this issue, really appreciate.
I verified this issue on vanilla Magento 2.4.3 CE instance, and the issue exists. 
Can you please tell, what Magento version you verified this on? Please refer attached for reference. 
Thanks!
![no_backorder_notification](https://user-images.githubusercontent.com/80893055/212074542-494dafbd-291f-4f57-942b-00548f8eea67.png)
![settings_backorder](https://user-images.githubusercontent.com/80893055/212074550-b2cba3d6-d7e8-4eca-b9d1-a990bb89abfc.png)
![product](https://user-images.githubusercontent.com/80893055/212074556-cb808b4c-a879-4200-aad4-dfc818520eb8.png)

**Comment by engcom-Bravo** [comment] 2023-01-12 13:29
Hi @vishwanathkharabe,

Thanks for your quick response.

it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.

Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-01-25 06:11
Hi @vishwanathkharabe,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.


Thanks.

**Closed as completed by engcom-Bravo** 2023-01-25 06:11 UTC
Labels: Issue: needs update, Reported on 2.4.3
