### ISSUE TITLE
Braintree doesn't load fields if PayPal option is disabled.

### ISSUE THREAD

**Issue by janepoltoratskaya** [magento/magento2#6827] opened 2016-10-01 00:00 UTC
### Preconditions

1. Magento 2.1.1
### Steps to reproduce

1. Enabled only Braintree payment method
2. Configure CC without 'Enable PayPal through Braintree'
### Expected result

1. On the checkout page, Braintree fields should available for editing
### Actual result

1. There are no calls to Braintree to get these fields, there are only empty divs on the front-end: Credit Card Number, Expiration Date, CVV

The fix is in
/vendor/magento/module-braintree/view/frontend/web/js/view/payment/method-renderer/cc-form.js
onActiveChange: function (isActive) {
                if (!isActive) {
                    return;
                }

```
            this.initBraintree();
        },
```

**Comment by janepoltoratskaya** [comment] 2016-10-01 00:01
Connected issue is https://github.com/magento/magento2/issues/5903

**Comment by lucscu** [comment] 2016-10-03 17:21
@janepoltoratskaya your fix seems to work, i'll use it and wait for official fix.

**Comment by YevSent** [comment] 2016-10-04 07:01
Hi, @janepoltoratskaya, thanks for reporting.
But, we can't reproduce described issue, also the [cc-form.js](https://github.com/magento/magento2/blob/2.1/app/code/Magento/Braintree/view/frontend/web/js/view/payment/method-renderer/cc-form.js#L140) already contains the `initBraintree()` method.

Could you attach browser errors?

**Comment by lucscu** [comment] 2016-10-04 08:27
because your cc-form.js differs from https://github.com/magento/magento2/blob/133dd81e9e5711c87c138c142959fd7acfea02af/app/code/Magento/Braintree/view/frontend/web/js/view/payment/method-renderer/cc-form.js

Why they are different?

**Comment by YevSent** [comment] 2016-10-04 10:19
Your link shows `cc-form.js` on the current develop branch, but the Braintree module contains features and bug fixes which aren't available for Magento 2.1.1.

**Comment by lucscu** [comment] 2016-10-04 12:37
so to fix my magento 2.1.0, have i to replace `cc-form.js` with 2.1.1 version?

**Comment by YevSent** [comment] 2016-10-21 09:55
Hi, @janepoltoratskaya. We are closing this issue because it hasn’t been updated in more than two weeks.
If you can still reproduce this issue, please, be free to reopen it.

**Closed as completed by YevSent** 2016-10-21 09:55 UTC
Labels: bug report, Progress: needs update, Component: Payment
