### ISSUE TITLE
Wishlist is missing review summary

### ISSUE THREAD

**Issue by Den4ik** [magento/magento2#21419] opened 2019-02-24 20:22 UTC
### Preconditions (*)
1. magento 2.3
2. magento 2.2

### Steps to reproduce (*)

1. Login to customer account
2. Add product with review to wishlist

### Expected result (*)

![s1ogw_2019_02_24_22_54_15](https://user-images.githubusercontent.com/1129623/53304796-92bccd80-388a-11e9-9659-a3b809eab1e6.jpg)

### Actual result (*)

![rp9mp_2019_02_24_22_53_38](https://user-images.githubusercontent.com/1129623/53304800-9cdecc00-388a-11e9-9f1f-bde13d99e511.jpg)

**Comment by magento-engcom-team** [comment] 2019-02-24 20:22
Hi @Den4ik. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Den4ik do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-02-25 03:24
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-02-25 04:39
Hi @krishprakash. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by krishprakash** [comment] 2019-02-25 04:40
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-25 04:40
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-25 04:40
Hi @krishprakash, here is your [Magento instance](https://i-21419-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21419-2-3-develop.instances.magento-community.engineering/admin](https://i-21419-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-02-25 16:16
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98422`, `MAGETWO-98423` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-03-14 19:45
Hi @Den4ik. Thank you for your report. 
The issue has been fixed in magento/magento2#21420 by @Den4ik in 2.3-develop branch
Related commit(s):
 - [a168c95b1cd71448bb001d0378caf9998628044f](https://github.com/magento/magento2/commit/a168c95b1cd71448bb001d0378caf9998628044f)
 - [0def6c20ad6ae7ed847cafd75b2cbdf8b651e25f](https://github.com/magento/magento2/commit/0def6c20ad6ae7ed847cafd75b2cbdf8b651e25f)
 - [473f9a5438ba08dc850d624e08f4f28f896af790](https://github.com/magento/magento2/commit/473f9a5438ba08dc850d624e08f4f28f896af790)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-14 19:45 UTC
Labels: Issue: Ready for Work, Area: Frontend, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Wishlist

**Comment by magento-engcom-team** [comment] 2019-03-20 13:35
Hi @Den4ik. Thank you for your report. 
The issue has been fixed in magento/magento2#21759 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [2aed503fbb4b8bdee75bcc25ebded80b65ad8b5e](https://github.com/magento/magento2/commit/2aed503fbb4b8bdee75bcc25ebded80b65ad8b5e)
 - [f0b3b92960f79366325ed8ce7f68e97bc23d5b71](https://github.com/magento/magento2/commit/f0b3b92960f79366325ed8ce7f68e97bc23d5b71)
 - [d9b01e35fb0e068b25db777a128144fede1c37fd](https://github.com/magento/magento2/commit/d9b01e35fb0e068b25db777a128144fede1c37fd)
 - [9661291658022dc4b9ff60cc73bc320b101d48be](https://github.com/magento/magento2/commit/9661291658022dc4b9ff60cc73bc320b101d48be)
 - [3dea8d0f34f9e4d033a7a82a22cbe93f418635ff](https://github.com/magento/magento2/commit/3dea8d0f34f9e4d033a7a82a22cbe93f418635ff)

The fix will be available with the upcoming 2.2.9 release.
