### ISSUE TITLE
Vimeo videos in product gallery do not work over https

### ISSUE THREAD

**Issue by rhodimus** [magento/magento2#7311] opened 2016-11-04 10:49 UTC
### Preconditions

1. Magento 2 EE 2.1
2. Google Chrome 54.0.2840.71 (64-bit)

### Steps to reproduce

1. Add vimeo video to a product
2. View and play the video via a https URL

### Expected result

1. Video should play

### Actual result

1. Video does not play
2. Blocked due to Mixed Content error (dev tools console output: This request has been blocked; the content must be served over HTTPS.)

The URLs for both Youtube and Vimeo are hard coded:

https://github.com/magento/magento2/blob/develop/app/code/Magento/ProductVideo/view/frontend/web/js/load-player.js#L320
https://github.com/magento/magento2/blob/develop/app/code/Magento/ProductVideo/view/frontend/web/js/load-player.js#L245

The Vimeo URL should be `https` here.

**Comment by veloraven** [comment] 2016-11-08 16:41
@rhodimus thank you for your report.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level

**Comment by rhodimus** [comment] 2016-11-14 08:54
@veloraven thanks for the update.

This is also an issue on CE, as the links in my original post show.

**Comment by veloraven** [comment] 2016-11-17 13:22
@rhodimus thank you for answer.
Could you please then let me know if you have created a report for Support? Just for avoiding duplicates and double work.

**Comment by rhodimus** [comment] 2016-11-17 14:35
@veloraven I haven't had a chance to create a support report for it. I won't create one and leave this here?

**Comment by veloraven** [comment] 2016-11-28 10:14
@rhodimus you can leave it here then as it refers to common functionality.

**Comment by ticholNyler** [comment] 2017-01-19 21:24
Any update?

**Comment by smoskaluk** [comment] 2017-06-19 13:55
@rhodimus I cannot reproduce this issue. May you please, let me know if you can reproduce this issue on latest version of Magento2 (2.1.7)?

**Comment by rhodimus** [comment] 2017-06-19 14:34
@smoskaluk I don't have the time to retest fully, but the code looks like its been fixed at least in > 2.1.3

**Comment by MagentoSeba** [comment] 2017-06-28 20:17
@veloraven I have created a support ticket (Ticket #**03207309**)

**Comment by MagentoSeba** [comment] 2017-07-11 00:03
@veloraven any update? +  @antboiko

**Comment by veloraven** [comment] 2017-07-25 12:40
Internal ticket MAGETWO-69574 was created for this issue.
I have linked it to this GitHub issue.

**Comment by magento-team** [comment] 2017-09-13 13:22
Internal ticket to track issue progress: MAGETWO-72278

**Comment by skynixukraine** [comment] 2017-09-24 08:00
Magento 2.1.7 Youtube video still does not play on mobiles

**Comment by magento-engcom-team** [comment] 2017-10-06 16:10
Hi @rhodimus the issue is already fixed in 2.1.100 and will be available soon

**Closed as completed by magento-engcom-team** 2017-10-06 16:10 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Fixed in 2.1.x, Issue: Format is valid
