### ISSUE TITLE
can not ship magento 2 no alocated source

### ISSUE THREAD

**Issue by baseplayer** [magento/magento2#36613] opened 2022-12-15 10:33 UTC
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

Magento ver. 2.3.7-p2

after adding more sources/warehouse in  ms

we can not do normal shipping

### Steps to reproduce

Hi

if you make msi more source

than go to manual ship in the grid so customer gets a mail shipped

it is not working since msi was added three warehouses?

### Expected result

fix isues and do more testing if msi more  stock is added

the end user uses it different than you as developer

### Actual result

we can not press ship manualy from grid so customer does not know the order is shipped

this is not same if we use ship by dpd postnl it works fine

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by baseplayer** [comment] 2022-12-15 10:34
https://www.google.com/search?q=can+not+ship+magento+2+no+alocated+source&oq=can+not+ship+magento+2+no+alocated+source&aqs=chrome..69i57j33i10i160.15532j0j15&sourceid=chrome&ie=UTF-8

**Comment by baseplayer** [comment] 2022-12-15 10:34
you see others have the same issues

**Comment by engcom-November** [comment] 2022-12-20 13:08
Hi @baseplayer ,
Verified the issue on Magento 2.4-develop instance with inventory enabled but the issue is not reproducible with below steps performed:
**Steps performed:**
1. Installed inventory modules on Magento 2.4-develop instance
2. Created 3 sources and stocks and assigned the stocks to sources.
3. Created a product and assigned all the sources to the product.
4. reindex and clear cache
5. Login as customer and created order
6. Created invoice from Admin - Sales - Orders - Invoice
7. Ship from Admin Order details page.
No issue: Shipment created successfully and emails are triggered as expected
Kindly recheck the issue on Magento 2.4-develop instance as it is having latest code base and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2023-01-06 06:34
Hi @baseplayer ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2023-01-06 06:34 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
