### ISSUE TITLE
Bundle option pricing issue

### ISSUE THREAD

**Issue by kerlama** [magento/magento2#33082] opened 2021-05-26 13:10 UTC
### Preconditions (*)
1. Clean magento 2.4.2 with sample data
2. PHP 7.4.16

### Steps to reproduce (*)
1. Create a simple product with price, lets say $5
2. Create a bundle product with dynamic price off and add simple product to it, set selection price to 0, set bundle price to $10
3. Save
4. Selection price is reverted to original simple product price and when you re-save and dont notice that, front-end price for bundle changes to $15

### Expected result (*)
1. Price on the front-end should be $10

### Actual result (*)
1. Price on the front-end after first save is $10 which is fine, but after re-saving the product, magento reverts option price to children product price, which is $5 and then on the front-end, price is $15

It seems like when you put anything but 0 it keeps the value, but if you put 0, it reverts back to original child product price.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by kerlama** [comment] 2021-05-26 13:12
@magento give me 2.4-develop instance

**Comment by craigfleming** [comment] 2021-05-27 10:38
@kerlama - I can confirm that I have the exact same issue in v2.4.2.

However, this bug is supposedly fixed and merged into v.2.4.3.

Please review the following other issues that relate to your issue:

1. https://github.com/magento/magento2/issues/32721
2. https://github.com/magento/magento2/issues/32383

**Comment by kerlama** [comment] 2021-05-27 10:41
Hi @craigfleming 
yes, you are right, those are the same issues. Will try with the fix suggested.

Thanks!

**Comment by krishprakash** [comment] 2021-05-28 04:33
Hi @kerlama. Thank you for your report.
Closing this issue as not able to reproduce on latest 2.4-develop instance

**Closed as completed by krishprakash** 2021-05-28 04:33 UTC
Labels: Issue:  Cannot Reproduce, Issue: ready for confirmation
