### ISSUE TITLE
Wysywig wrong img directive in category edit

### ISSUE THREAD

**Issue by Styopchik** [magento/magento2#5705] opened 2016-07-20 06:47 UTC
## Steps to reproduce
1. Install Magento from zip archive
2. add category
3. in "content" section go to wysiwyg editor
4. Hide editor
5. Add an image (will insert {{media url="wysiwyg/content/world-map-sat.jpg"}})
6. Open category in frontend
## Expected result
1. url of an image http://domain.com/pub/media/wysiwyg/content/world-map-sat.jpg (or similar)
## Actual result
1. Image url leads to admin area  (http://domain.com/admin/cms/wysiwyg/directive/___directive/e3ttZWRpYSB1cmw9Ind5c2l3eWcvY29udGVudC93b3JsZC1tYXAtc2F0LmpwZyJ9fQ,,/key/843adb1c4db149b221b91815e46267e618989232389e86ff5399897041ccc15b/)
   ![1](https://cloud.githubusercontent.com/assets/884525/16977468/ddfbbfae-4e5e-11e6-89d1-5750fa72ad9c.png)
   ![2](https://cloud.githubusercontent.com/assets/884525/16977472/e1006ede-4e5e-11e6-9cf4-95e7e9280028.png)

**Comment by duhon** [comment] 2016-07-25 14:01
Thanks for reporting this issue.
Unfortunately, I was not able to reproduce the issue you described.
Could you please provide more information? Like versions of PHP, MySQL and web server.
Also, it can be helpful if you describe settings of your Magento instance: was it the fresh install or upgrade from the previous version?
Do you have many store views? Maybe some other settings.

**Comment by Styopchik** [comment] 2016-07-26 11:29
php version: PHP 5.6.22-0+deb8u1
mysql  Ver 14.14 Distrib 5.6.31, for Linux (x86_64)
Server version: Apache/2.4.10 (Debian)
Magento install from zip archive, downloaded from magento site.
There is only one store view. That's all

**Comment by davidbilly** [comment] 2016-07-28 13:29
@duhon i faced same issue on CE 2.1, it's expose my admin console url. 

Faced this after i update from 2.0.4 CE to 2.1.0 CE. 
More details : #5426

<img width="1550" alt="screen shot 2016-07-28 at 9 24 01 pm" src="https://cloud.githubusercontent.com/assets/3938103/17214165/36c8e48e-550a-11e6-8d9a-3f33e8255801.png">

**Comment by andimov** [comment] 2016-08-05 14:31
@Styopchik 
Thank you for reporting!
I've created an internal ticket for this issue - MAGETWO-56485 and linked it to this one.

**Comment by tkacheva** [comment] 2016-11-10 15:52
Duplicates https://github.com/magento/magento2/issues/7297

**Comment by Bartlomiejsz** [comment] 2016-11-10 18:28
This issue still exists on 2.1.2.  @veloraven @tkacheva Any news about it?

**Comment by Frits1980** [comment] 2017-01-05 14:22
Duplicates: [7167](https://github.com/magento/magento2/issues/7167)

But that ticket is also not solved. Mainly because developers cannot replicate the issue.
I just had it too. But I didn't have it before. Something changed. Still figuring out what though.

**Comment by Szymon-GP** [comment] 2017-02-21 15:06
2.1.4 and the path generated in the Image URL field is pointing to admin
![zrzut ekranu 2017-02-21 o 16 05 19](https://cloud.githubusercontent.com/assets/7405824/23170505/a5817a60-f84f-11e6-8afc-eb88cdc63960.png)

**Comment by navarr** [comment] 2017-03-16 13:37
We're experiencing this issue in production on multiple websites, at least one of which is EE (so I'm guessing I should file an internal support request as well).

EE Dev: Magento 2.1.4
PHP 5.6.25 w/ ionCube Loader v5.1.1 (EE Dev)

CE Prod: Magento 2.1.3
PHP 5.6.27 w/ ionCube Loader v6.0.6 w/ Zend Guard Loader v3.3 (CE Prod)

Both of the sites have the following directory structure:

[ user home directory ]
Magento/
public_html/ -> Magento/pub

Website is served from public_html (which is symlinked to Magento/pub)

**Comment by JVKeller** [comment] 2017-06-22 17:14
This issue has been following me on my site also. 

Upgrade path was 2.1.5 -> 2.1.6 -> 2.1.7 
Existing on all versions.

Is there a work around? Very annoying to have to keep editing the html over and over.
I have to save, then go back in and edit html view. As soon as I reopen the wysiwyg editor changes the link back.

example:
https://moto-heaven.com/admin/cms/wysiwyg/directive/___directive/e3ttZWRpYSB1cmw9Imh0dHBzOi8vbW90by1oZWF2ZW4uY29tL3B1Yi9tZWRpYS9pbWFnZXMvVEhSVVNUQ29tcGFueS5naWYifX0,/key/a19784f7660ed7d4473ecb0d3c7bb2acb20618e1027232f472762ffc9c3e1bab

**Comment by navarr** [comment] 2017-06-22 17:20
@JVKeller You can use this as a workaround

https://github.com/Talv/magento2-wysiwyg-fix

**Comment by JVKeller** [comment] 2017-06-22 17:23
I'll try it out!
Thanks!

**Comment by magento-engcom-team** [comment] 2017-10-02 11:30
@Styopchik, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-02 11:30 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid

**Comment by bobemoe** [comment] 2018-01-01 11:03
Should this be fixed in CE 2.1.11? 

I am still seeing the issue, even with the https://github.com/Talv/magento2-wysiwyg-fix which I can confirm is adding the "add_directives" line to the config. No idea why the fix isn't working!?
