### ISSUE TITLE
New CMS Page Not working

### ISSUE THREAD

**Issue by j1nx3d** [magento/magento2#5711] opened 2016-07-20 13:53 UTC
## Steps to reproduce
1. Install Magento 2.1 from any source.
2. Set **Enable Single-Store Mode** to **Yes**
3. Create a new CMS Page
## Expected result
1. CMS Page is created
2. New Page can be accessible from the frontend
## Actual result
1. CMS Page is created
2. Returns 404 when trying to access the page from the frontend
## Issue

On the database the `cms_page_store` doesn't create the registers when the **Single-Store Mode is enable**.

**Comment by liquidia** [comment] 2016-07-24 06:51
same issue 2.1/ php7/nginx

**Comment by liquidia** [comment] 2016-07-30 10:53
not just single store with multi store too have same issue.

**Comment by magentodevleper** [comment] 2016-08-04 06:18
Same Issue here. I had to manually associate value in cms_page_store to get the page working.

**Comment by magentodevleper** [comment] 2016-08-17 11:09
### Steps reproduce
1. Set Enable Single-Store Mode to Yes
2. Create a new CMS Page

### Expected result

CMS page will saw in frontend

### Actual result

CMS page will not display

### Review below file

`https://github.com/magento/magento2/blob/develop/app/code/Magento/Cms/Model/ResourceModel/Page.php#L152`

i have print value of two variable

echo 'field : ' . $field
echo 'value: ' . $value

output : 
field : identifier
value : no-route

That means when we create new CMS page in Single store mode identifier not fetch correct.

## Solution

Open cms pages list , click on cms page ( grid view pullout that row and ask for ( cancel and save ) , now click on save.

now open you CMS page , its will display....

**Comment by AVoskoboinikov** [comment] 2016-09-13 13:18
Hi guys

Can you upgrade to 2.1.1 and recheck if this issue is still actual? I have tried it on 2.1.1 and my page was available by url key from "Search Engine Optimization".

Thanks for contributing!

**Comment by plauge** [comment] 2016-10-06 07:16
This is still an issue in 2.1.1

**Comment by staffrob** [comment] 2016-10-06 14:05
Can confirm this issue in 2.1.1 also

**Comment by plauge** [comment] 2016-10-06 15:39
Hi,
Yes and no :-)
Please take a look at this video, where I test it on 2 sites on the same server.
One site is a clean 2.1.1 installation, and one site is an update from 2.0.7 to 2.1.1. 
The bug is in the updated version.
The server is running: PHP Version 7.0.11

Here is the video link: https://goo.gl/oRoCeB

**Comment by andreasRulle** [comment] 2017-02-09 18:11
Hi, the bug still seems to bei present in a fresh Magento 2.1.3 installation. After interserting
(<page_id>, 0) into the cms_page_store table the newly created cms page was usable.

**Comment by rishabhrkrai** [comment] 2017-02-16 06:47
Experiencing the same issue here. 
After some R&D, i found that the new page somehow is only added to the cms_page table but not cms_page_store. If I manually add the relationship in cms_page_store, the page loads.
This issues is due to "Single Store Mode". If you enable the Single Store Mode, this problem exists. Disable Single Store Mode from **Store > Configuration > General > General > Single Store Mode (Select No)**
Refresh the cache, create a CMS page. Its work fine.

Hope! This will help you  @j1nx3d

**Comment by markalston** [comment] 2017-04-20 19:30
Still broken in 2.1.5 
Manually adding page to cms_page_store table fixes problem.

**Comment by bassplayer7** [comment] 2017-05-01 22:30
This is still an issue, and one that can easily be resolved (by Magento) I think as there are 3 lines that would need to be changed. The problem is that the page save controller is using the deprecated way to save a model. @magentodevleper is right - saving inline actually works fine. Currently `\Magento\Cms\Controller\Adminhtml\Page\Save::execute()` loads the model directly, and then saves it directly.

**This can easily be fixed by simply using `\Magento\Cms\Api\PageRepositoryInterface` to load the page model and then save it.**

**Comment by korostii** [comment] 2017-05-04 09:44
@bassplayer7, nice catch!
[Here's](https://github.com/magento/magento2/blob/2.1/app/code/Magento/Cms/Controller/Adminhtml/Page/Save.php#L68-L88) the relevant piece of code. 

The most annoying thing is that if you switch back to the develop branch you'll see that there's already a [fix](https://github.com/magento/magento2/commit/105062e3ea7b62fd958a0a314839603b9570aa68) done as early as in October 2016. There's even an internal ticket MAGETWO-58383 [created](https://github.com/magento/magento2/issues/5923#issuecomment-269219512) with the sole purpose of backporting that fix to 2.1. 

Does it really take half a year to cherry-pick a bunch of commits? The word "embarrassing" comes to mind.

**Comment by idlea** [comment] 2017-05-05 14:08
Has this been fixed I have the same problem using Magento ver. 2.1.6
I am in single store mode which if I change to single store-no should fix the problem, however the whole store has been created in single store mode, will change to not single store create any problems.

**Comment by idlea** [comment] 2017-05-05 14:17
okay works now without change store mode, reindexed and flushed and works okay.

**Comment by oleg-onufer** [comment] 2017-06-19 13:11
Internal ticket was created for this issue --  MAGETWO-69926

**Comment by magento-engcom-team** [comment] 2017-10-02 14:45
Hi @j1nx3d 
Fix for this issue is already released with `2.2.0`. You may use commits [prefixed with MAGETWO-56863](https://github.com/magento/magento2/search?q=MAGETWO-56863&type=Commits)
for reference. 
We are considering to backport this fix into previous versions, however there is no specific schedule for now.
Thank you.

**Closed as completed by magento-engcom-team** 2017-10-02 14:45 UTC
Labels: Issue: Ready for Work, bug report, Component: Cms, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid
