### ISSUE TITLE
Zero subtotal payment method set to default status "Processing" not working in magento 2.1.4 EE

### ISSUE THREAD

**Issue by karthi5053** [magento/magento2#10443] opened 2017-08-05 11:09 UTC
Hi,

We have configured "Zero subtotal payment method" and set new order status as "Processing", but when we place orders with order total 0(100 % discount applied), payment method is as "free" but order status is still in "Pending" not as "Processing" which was configured.
Any suggestion would be really helpful.
![zero_subtotal](https://user-images.githubusercontent.com/7961427/28995087-b414d23c-79fc-11e7-9054-4976e5ec2f72.png)

Regards,
Karthi kumar

**Comment by enriquetarazona** [comment] 2017-08-11 16:24
Hi, 
I have the same issue. The default order status is not "Processing" after apply the change. 
Any luck???

**Comment by magento-engcom-team** [comment] 2017-09-11 21:28
@karthi5053 thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [x] Preconditions: Magento version
 - [x] Steps to reproduce
 - [x] Expected result
 - [x] Actual result

**Comment by zukovasmartynas** [comment] 2017-09-14 13:27
@karthi5053 Have you assigned it to the pending state?

Stores->Order Status->Assign status to state -> there select order status Processing and order state Pending
I had the same issue with different payment method

**EDIT**
My magento version is 2.1.8
Because in Magento\Sales\Model\Order\Payment; line 359:361 there is a check if order state doesn't have an order status assigned, default status will be set.

**Comment by magento-engcom-team** [comment] 2017-09-21 13:48
@karthi5053, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. We tried it on 2.1.9.
We did next:
1. Create simple product.
2. Enable free shipping(Store->Configuration->Sales->Shipping methods).
3. Enable zero subtotal payment method(Store->Configuration->Sales->Payment methods).
Set new order status as "Processing".
4. Go to Stores->Order Status->Assign status to state:
- order status -> Processing;
- order state -> Pending;
Save.
5. Create cart price rule with coupon code for 100% discount.
6. Go to frontend, add created product to shopping cart, go to checkout, choose free shipping method, apply coupon code and place order.
7. Created order is in processing status.

Please provide more details if we are steps are wrong, or try to reproduce this
issue on a clean installation.

**Comment by magento-engcom-team** [comment] 2017-10-05 18:20
@karthi5053 we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Closed as completed by magento-engcom-team** 2017-10-05 18:20 UTC
Labels: Progress: needs update, Issue: Clear Description, Issue: Format is not valid
