### ISSUE TITLE
Custom option values are not deleted correctly from the database

### ISSUE THREAD

**Issue by igrslv** [magento/magento2#4516] opened 2016-05-15 19:15 UTC
Magento version 2.0.5
## Steps to reproduce
1. Create drop-down custom option
2. Add two option values
3. Save the product
4. Delete one option value
5. Option is not visible, but there is still a record for this option value in catalog_product_option_type_value table.  
## Expected result

Database record for deleted option value must be deleted.

![screenshot_21-10-02](https://cloud.githubusercontent.com/assets/1457489/15276213/f27b9a5e-1ae1-11e6-8d8b-add84be1c2da.png)

**Comment by katmoon** [comment] 2016-05-19 12:02
Hi @igrslv 

Thank you for such a good issue description.

I cannot reproduce the issue on develop branch. The product page has been completely reworked, and this issue could probably be fixed.

The fix is already in develop branch and will be available in 2.1 release.

I'm closing the issue. Feel free to reopen it if needed.

Thanks,
Kateryna.

**Closed as completed by katmoon** 2016-05-19 12:02 UTC
Labels: bug report
