### ISSUE TITLE
Unable to add Product Image for Color Swatchs

### ISSUE THREAD

**Issue by gilbertsohal** [magento/magento2#10171] opened 2017-07-07 01:00 UTC
### Preconditions

1. Magento ver. 2.1.7
2. 

### Steps to reproduce

1. In Color attribute property set (Use Product Image for Swatch if Possible) to **YES**
2. Run (php bin/magento indexer:reindex)
3. Run (php bin/magento cache:clean)

### Expected result

1. Color Attribute on product detail page showing product images in place of color swatches.

### Actual result

1. Color Attribute on product detail page not showing product images in place of color swatches.
2. If i Run (php bin/magento indexer:reindex) and Run (php bin/magento cache:clean)
3. Product image in place of color swatches appear on first page load and disappear if i refresh page again

Color Attribute
http://prntscr.com/fslrnm

Detail Page Before Run (php bin/magento indexer:reindex) and Run (php bin/magento cache:clean)
http://prntscr.com/fslry4

Detail Page After Run (php bin/magento indexer:reindex) and Run (php bin/magento cache:clean)
http://prntscr.com/fslsov

**Comment by LeLieu** [comment] 2017-07-07 02:36
The same issue, pls fix it!

**Comment by IlnitskiyArtem** [comment] 2017-07-25 11:32
Hi, @gilbertsohal. I reproduced this behavior but in my case it's a little bit different. Can you please specify your steps? How exactly do you add images to your configurable product? By adding them for each simple product generated with your configuration or in some other way?

**Comment by gilbertsohal** [comment] 2017-07-26 23:29
Hi IlnitskiyArtem

Thanks very much for your reply please find the steps below.

1) Create Color Attribute
Store > Attributes > Product >  Color (Attribute name) > Attribute Properties > Use Product Image for Swatch if Possible > YES

Please find screenshot Below.
http://prntscr.com/g0qlyi

2) Add color attribute on Product
Products > Catalog > Add Product (Configurable Product) > Configurations >Create Configurations

Step 1 (Screenshot)
http://prntscr.com/g0qn4h

Step 2 (Select Attributes)
http://prntscr.com/g0qnxs

Step 3 (Select Attributes Value)
http://prntscr.com/g0qoqo

Step 4 (Apply unique images by attribute to each SKU)
http://prntscr.com/g0qpby

Step 5 (Upload Images)
http://prntscr.com/g0qpto

Step 6 (Summary)
http://prntscr.com/g0qq8z

Step 7 (New Product)
http://prntscr.com/g0qqr1

These are the steps i followed and the result is product detail page not showing product images in place of color swatches.

I find in my research if i disable EAV types and attributes in Cache management then the product image appear in place of color swatches.
SYSTEM >  Cache Management > EAV types and attributes > DISABLED

Screenshot (Admin)
http://prntscr.com/g0qtdk

Screenshot (Frontend)
http://prntscr.com/g0qu29

Hope this will help you.

regards
G

**Comment by IlnitskiyArtem** [comment] 2017-07-27 06:52
@gilbertsohal Yes, it helped. Internal ticket MAGETWO-71084, which tracks this GitHub issue, is in our issue backlog.

**Comment by magento-engcom-team** [comment] 2017-09-22 16:17
@gilbertsohal, thank you for your report.
The issue is already fixed in 2.1.9

**Closed as completed by magento-engcom-team** 2017-09-22 16:17 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Fixed in 2.1.x, Issue: Format is valid
