### ISSUE TITLE
Magento 241 storepick up give an error if customer has addresses but not set the default address

### ISSUE THREAD

**Issue by nhatlich994** [magento/magento2#34735] opened 2021-11-30 10:57 UTC
### Preconditions (*)
1. M241, storepickup enabled
2. Customer has address but not set the default address
(https://imgur.com/uZjptb7)

### Steps to reproduce (*)
1. Login
2. Add product to cart then go checkout
3. Switch to tab Store Pickup

### Expected result (*)
1. I expected no error here

### Actual result (*)
1. Magento_InventoryInStorePickupFrontend/js/view/store-pickup throw an error
https://imgur.com/wCzXSPB

**Comment by engcom-Hotel** [comment] 2021-12-01 10:15
Hi {username}

Thank you for reporting the issue.

We tried to reproduce it on Magento 2.4-develop and we are not able to reproduce it.

Steps followed to reproduce it.

1. Enabled Store pickup or In-Store Delivery by following link https://docs.magento.com/user-guide/shipping/shipping-in-store-delivery.html
2. Create a customer add address but not default shipping billing.
![image](https://user-images.githubusercontent.com/51681618/144215731-fa9a0638-c814-4460-a11c-a6725b793f6a.png)
3. Select store pickup on checkout
![image](https://user-images.githubusercontent.com/51681618/144215824-c83429b3-1d11-413b-a00d-1054addacf5a.png)

We can not see any error in the console able to create an order.

Thank you

**Comment by psydog-1101** [comment] 2021-12-11 09:20
@magento give me 2.4-develop instance

**Comment by psydog-1101** [comment] 2021-12-11 09:52
hi @engcom-Hotel , sorry for late reply. I has tested on my environment and the issue still alive. In my case, shipping address not selected by default, hence quote.shippingAddress is NULL. Did you test with new session or incognito mode? That ensure that shipping address is not selected by default
------------- 
to go live, I must used a temp fix on my env and our website is working fine now.

**Comment by engcom-Hotel** [comment] 2021-12-29 09:57
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2021-12-29 10:03
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment] 2022-01-03 09:15
Hi @psydog-1101,

Yes I have tested with new session and also on incognito mode. Can you please check if this issue is reproducible with Magento 2.4-develop instance or if you could provide some more insight on what can I do more to reproduce it ?

Thanks

**Comment by engcom-Echo** [comment] 2022-01-17 12:21
Hi @psydog-1101,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket with the requested details in last comment if you need more assistance on this.

Thanks

**Closed as completed by engcom-Echo** 2022-01-17 12:21 UTC
Labels: Issue: needs update
