### ISSUE TITLE
While add cart price rule from admin click on Condition drop-down arrow direction not change.

### ISSUE THREAD

**Issue by bhavik43** [magento/magento2#22434] opened 2019-04-20 06:02 UTC
While add cart price rule from admin click on Condition drop-down arrow direction not change.

### Preconditions (*)
Magento 2.3

### Steps to reproduce (*)
1. Go to Admin
2. Marketing > Cart Price rule
3. Conditions > Click on +
4. Open/close and review the Drop-down arrow direction

### Expected result (*)
Drop down arrow should be changes as per other drop-downs.

### Actual result (*)
![issue1](https://user-images.githubusercontent.com/49804008/56453390-a3a42f80-635f-11e9-885e-a8c49559cc0c.png)

**Comment by krishprakash** [comment] 2019-04-20 06:05
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-04-20 06:05
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-20 06:06
Hi @krishprakash, here is your [Magento instance](https://i-22434-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22434-2-3-develop.instances.magento-community.engineering/admin](https://i-22434-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-04-20 06:13
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99316` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Karlasa** [comment] 2019-04-20 13:31
@krishprakash @bhavik43
Are you sure this is really an issue? 
By default conditions dropdown is focused and that's why dropdown arrow is pointed up not down as in default  (non focus state) and as in non focus state dropdown will be removed it has no other state to show. 

I think this is expected behaviour and should not be counted as issue. 

Cheers,

**Comment by krishprakash** [comment] 2019-04-20 14:02
@Karlasa Thanks for your response.
It is working fine in Magento 2.2.x and this is not Magento's expected behavior.
You can review in next drop-down behavior which is in Action > Apply while add cart price rule.
I hope you understand.
Thanks.

**Comment by Karlasa** [comment] 2019-04-20 20:27
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-04-20 20:27
Hi @Karlasa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-20 20:27
Hi @Karlasa, here is your [Magento instance](https://i-22434-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22434-2-3-develop.instances.magento-community.engineering/admin](https://i-22434-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Karlasa** [comment] 2019-04-20 20:43
@krishprakash 
Thanks for follow up 👍 
In this case i would say issue description is bit confusing because seems like conditions dropdown is only one that has focus state reverted arrow and other dropdown elements are missing it and should be fixed instead :) 

But yeah issue is there.

**Comment by hiren0241** [comment] 2019-04-22 05:22
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-04-22 05:22
Hi @hiren0241. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-22 05:23
Hi @hiren0241, here is your [Magento instance](https://i-22434-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22434-2-3-develop.instances.magento-community.engineering/admin](https://i-22434-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by hiren0241** [comment] 2019-04-22 13:50
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-04-22 13:50
Hi @hiren0241. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-22 13:51
Hi @hiren0241, here is your [Magento instance](https://i-22434-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22434-2-2-develop.instances.magento-community.engineering/admin](https://i-22434-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-04-27 20:40
Hi @bhavik43. Thank you for your report. 
The issue has been fixed in magento/magento2#22456 by @hiren0241 in 2.3-develop branch
Related commit(s):
 - [27e048ff422c5d5b82b4b428ecabf4f1ac3622bf](https://github.com/magento/magento2/commit/27e048ff422c5d5b82b4b428ecabf4f1ac3622bf)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-04-27 20:40 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Rule, Component: Admin
