### ISSUE TITLE
Create new order grid breaking on filtering

### ISSUE THREAD

**Issue by Rickywils** [magento/magento2#38227] opened 2023-11-28 10:46 UTC
### Preconditions and environment

- 2.4.5-p3

### Steps to reproduce

1. Login into admin panel
2. Go to sales -> orders
3. Click button "Create a new order"
4. Search on name in grid

### Expected result

After searching on for example on name I would expect that the grid is filtered on the name.

### Actual result

An 500 error on `sales/order_create/loadBlock/block/customer_grid/key/XXXXXXXXXXXXXX/filter` and redirects to the dashboard with system error **Invalid security or form key. Please refresh the page**.

Nothing is logged into the logs.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-11-29 03:32
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-11-29 06:59
Hi @Rickywils,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

1. Login into admin panel
2. Go to sales -> orders
3. Click button "Create a new order"
4. Search on name in grid


<img width="1490" alt="Screenshot 2023-11-29 at 12 25 44 PM" src="https://github.com/magento/magento2/assets/51680745/9ad56bb0-977d-4df2-afa3-451268cfc2a3">


After searching on Name the grid is filtering by the name.

The Error  Invalid security or form key. Please refresh the page related to the admin due to out of maximum session time.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

**Comment by engcom-Bravo** [comment] 2023-12-11 05:11
Hi @Rickywils,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38227#issuecomment-1831322104
still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-12-12 04:55
Hi @Rickywils,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Bravo** 2023-12-12 04:55 UTC
Labels: Issue: needs update, Reported on 2.4.5-p3
