### ISSUE TITLE
Magento2.1 Invoice ID does not increase

### ISSUE THREAD

**Issue by Nerogee** [magento/magento2#5522] opened 2016-07-07 13:57 UTC
## Steps to reproduce
1. Install Magento2.1 from composer.
2. Add Configurable Product to the cart.
3. using paypal express checkout
## Expected result
1. redirect to paypal login page
## Actual result
1. PayPal gateway has rejected request. Payment has already been made for this InvoiceID (#10412: Duplicate invoice)
2. 'INVNUM' => '000000001' (Paypal API request content)
3. **invoice ID is always 000000001** even I manually created order in admin

**Comment by YevSent** [comment] 2016-08-03 16:14
Hi, @Nerogee, could you attach debug and exception log?

**Comment by Nerogee** [comment] 2016-08-04 03:29
sorry @joni-jones , I already removed whole installation and those files are gone. I remembered at that time is when such error happened, there is no any exception. But from the debug.log I can clear see the invoice ID remain the same value.

**Comment by Nerogee** [comment] 2016-08-09 17:30
@joni-jones, I found payment will fail with message "cant place order" when items are set with custom option. Here is the message from system.log

main.CRITICAL: Exception message: Warning: Invalid argument supplied for foreach() in /var/www/public_html/www.mydomain.com/vendor/magento/module-catalog/Model/Product.php on line 1910

as I know there are issue with custom option, it's here https://github.com/magento/magento2/issues/5573

**Comment by alena-marchenko** [comment] 2016-08-26 11:23
#4580

**Comment by alena-marchenko** [comment] 2016-08-26 11:32
Hi @Nerogee ,

MAGETWO-54412 internal ticket is creating regarding this issue.
Closing this issue as duplicate of #4580 
Feel free to create new one if you experience other issues.

**Closed as completed by alena-marchenko** 2016-08-26 11:32 UTC
Labels: Issue: Ready for Work, bug report, Component: Payment
