### ISSUE TITLE
Catalog navigation menu is not display after upgrading to magento 2.1.0

### ISSUE THREAD

**Issue by jigar48** [magento/magento2#5966] opened 2016-08-03 14:26 UTC

**Comment by davidalger** [comment] 2016-08-03 16:46
@jigar48 There is insufficient information here to determine if this is bug or some other technical issue. Please provide complete details on steps taken and the corresponding results, and why you believe this to be a Magento bug. If you cannot provide this detail, this issue will be closed.

**Comment by jigar48** [comment] 2016-08-04 05:32
I upgraded the magento 2.0.4 to 2.1.0 successfully. but now there catalog navigation is missing on front end side. can any one have idea what is the issue ?

**Comment by Ctucker9233** [comment] 2016-08-04 22:59
@jigar48 I had this exact same issue see #5423 for ways to fix.

**Comment by pboisvert** [comment] 2016-08-04 23:02
closing as a duplicate of #5423

**Closed as completed by pboisvert** 2016-08-04 23:02 UTC
Labels: Progress: needs update
