### ISSUE TITLE
Magento2.3.1 Search Engin Issue

### ISSUE THREAD

**Issue by mincovip** [magento/magento2#27445] opened 2020-03-26 04:09 UTC
Hi there,

When I changed the search engine from MySQL to Elasticsearch 6.0+, and then click '**save config**' button, the search engine is still MySQL. Could you give me some suggestions?

the below link is a screen recording:
https://i.ibb.co/fvf9gHM/search-engin-issue.gif

**Base info:**
Centos 7
Apache 2.4
Magento2.3.1

**Comment by krishprakash** [comment] 2020-03-26 04:25
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-26 04:25
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-03-26 04:26
Hi @krishprakash, here is your [Magento instance](https://i-27445-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27445-2-4-develop.instances.magento-community.engineering/admin_196b](https://i-27445-2-4-develop.instances.magento-community.engineering/admin_196b)
Login: `1be48917` Password: `f9d63b60a677`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2020-03-26 04:33
Hi @mincovip. Thank you for your report.
Can not able to reproduce the issue on latest instance
It should be fixed fixed in updated version
Feel free to reopen the issue if you confirm that issue is reproduced on latest 2.3.4 version

**Closed as completed by krishprakash** 2020-03-26 04:33 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is not valid, Progress: ready for QA, Reported on 2.3.1
