### ISSUE TITLE
On advanced search page Price field misaligned on mobile view

### ISSUE THREAD

**Issue by ajay2jcommerce** [magento/magento2#20157] opened 2019-01-10 06:45 UTC
### Preconditions (*)

1. 2.3.0
2.

### Steps to reproduce (*)

1. click on  footer link "advanced search" check for price field mobile view.
2.

### Expected result (*)

1. 
![2019-01-10_11-56_advanced search](https://user-images.githubusercontent.com/18118570/50950727-d91fbe00-14d0-11e9-9c2b-fb87581ff329.jpg)

2.

### Actual result (*)

1. 
![2019-01-10_11-55_advanced search](https://user-images.githubusercontent.com/18118570/50950732-dfae3580-14d0-11e9-8759-ab8f79ad7e15.jpg)

2.

**Comment by magento-engcom-team** [comment] 2019-01-10 06:45
Hi @ajay2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ajay2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-10 06:50
Hi @priti2jcommerce. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-01-10 06:51
Hi @GovindaSharma. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by GovindaSharma** [comment] 2019-01-10 06:52
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-01-10 06:52
Hi @GovindaSharma. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-01-10 06:52
Hi @GovindaSharma, here is your [Magento instance](https://i-20157-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20157-2-3-develop.instances.magento-community.engineering/admin](https://i-20157-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-01-10 06:56
@GovindaSharma Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97539`, `MAGETWO-97540` were created

**Comment by magento-engcom-team** [comment] 2019-02-10 18:20
Hi @ajay2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20159 by @GovindaSharma in 2.3-develop branch
Related commit(s):
 - [47f51327fef62a4177e4e344cf3292e6c4ed97dc](https://github.com/magento/magento2/commit/47f51327fef62a4177e4e344cf3292e6c4ed97dc)
 - [81cd0d41781c117f07e4ba87b8e3ab3d5afea430](https://github.com/magento/magento2/commit/81cd0d41781c117f07e4ba87b8e3ab3d5afea430)
 - [2353329514d90a3ef82d6776c1e76b5e545d7dea](https://github.com/magento/magento2/commit/2353329514d90a3ef82d6776c1e76b5e545d7dea)
 - [10f53785f5b0c5c3bf50bb38ff25cdd09f15c3e2](https://github.com/magento/magento2/commit/10f53785f5b0c5c3bf50bb38ff25cdd09f15c3e2)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2019-02-10 18:20 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: AdvancedSearch

**Comment by magento-engcom-team** [comment] 2019-02-13 21:25
Hi @ajay2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#21114 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [cb67c971714308c0f8a0ce2831185c31da6c3887](https://github.com/magento/magento2/commit/cb67c971714308c0f8a0ce2831185c31da6c3887)
 - [665dbefec928193cfcb0c4de9702fd78de6a5c62](https://github.com/magento/magento2/commit/665dbefec928193cfcb0c4de9702fd78de6a5c62)
 - [246a344c9a13011477d57f57dcdc5a24ee225bbf](https://github.com/magento/magento2/commit/246a344c9a13011477d57f57dcdc5a24ee225bbf)
 - [09c0f0195d4149046ad538b0a25518316d7642af](https://github.com/magento/magento2/commit/09c0f0195d4149046ad538b0a25518316d7642af)

The fix will be available with the upcoming 2.2.9 release.
