### ISSUE TITLE
Report shipment tracking bug to Magento

### ISSUE THREAD

**Issue by sgeleon** [magento/magento2#33223] opened 2021-06-11 13:28 UTC
### Preconditions 
Magento version (2.4.1)

### Steps to reproduce 
1. Create an order with multiple products
2. Ship one product with a tracking number
3. Ship another product without tracking number - the tracking number of the first shipment shows on the email

### Expected result 
Showing all tracking numbers assigned to the order, not individual shipments.

e.g.
Shipment 1 with tracking number A > Email with tracking number A
Shipment 2 with no tracking number > Email with tracking number A
Shipment 3 with tracking number B > Email with tracking numbers A and B

### Actual result 
Showing all tracking numbers assigned to individual shipments.

![](https://trello-attachments.s3.amazonaws.com/5c9962360d7c7431ff10397f/5fc8890b72cd5c0e8f526653/e0a8b24c2e024d75f26eafeb7b8c8c51/2021-06-11-0013.jpg)

**Issue2:** If different tracking number is given to 2nd Product while shipping, 2 tracking numbers are getting displayed for the same single product in the email.
**Note**: There is no issue on Store-front
![image](https://user-images.githubusercontent.com/60198231/129353340-7fca28ca-343b-4526-8b7e-21f1dd4c51d3.png)
![image](https://user-images.githubusercontent.com/60198231/129353359-91426553-235d-48bf-a8a1-f3a63b0a6459.png)

**Comment by engcom-November** [comment] 2021-08-13 06:28
Verified the issue on Magento 2.4-develop branch and the issue is reproducible.
**Steps performed:**
1. Login to the Front-end as Customer
2. Front-end - Add multiple Products to Cart
3. Proceed to Checkout and place Order
4. Navigate to Admin - Sales - Orders - View Order - Click On Ship
5. Ship Only one product with Tracking Number (Update Quantity to 0 to one of the Products) and Submit
**No issue: Email triggered with Tracking Number**
![image](https://user-images.githubusercontent.com/60198231/129314384-dbed80fb-5ecc-402c-854a-92efbc8f0bf9.png)

6. Ship the remaining Product again without Tracking Number
**Issue: Email is triggered with Old Tracking Number**
![image](https://user-images.githubusercontent.com/60198231/129314368-4ab0b3f4-f665-45c9-b621-92ae9e617d17.png)

**Comment by magento-engcom-team** [comment] 2021-08-13 06:29
:white_check_mark: Confirmed by @engcom-November 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-43082` were created

**Issue Available**: @engcom-November, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Kiraberos** [comment] 2022-11-11 09:06
@magento I am working on this

**Comment by Kiraberos** [comment] 2022-11-11 10:58
I tried to reproduce it by steps to reproduce on the latest 2.4-develop and I couldn't reproduce it.
I ship only one product with Tracking Number (Updated Quantity to 0 to remaining/other products) and Submit (Enable email invoice copy)
![photo_2022-11-11_12-51-22](https://user-images.githubusercontent.com/70772975/201325716-09f7417a-c2a6-431d-9bcf-6c1b0631a8db.jpg)
![photo_2022-11-11_12-51-42](https://user-images.githubusercontent.com/70772975/201325726-b947076f-2712-4cf8-ba29-5bfcd1f66b18.jpg)
![image](https://user-images.githubusercontent.com/70772975/201325911-fb95c5cb-1a1a-44a5-b28e-f74a975c5e24.png)

No issue: Email triggered with Tracking Number

The next step is ship the remaining Product again without Tracking Number

**Comment by engcom-Bravo** [comment] 2024-06-20 06:58
Hi @sgeleon,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.


<img width="940" alt="Screenshot 2024-06-20 at 12 23 07" src="https://github.com/magento/magento2/assets/51680745/a9544a16-8add-4fe5-99e6-cfe6fca0bef8">



<img width="940" alt="Screenshot 2024-06-20 at 12 25 08" src="https://github.com/magento/magento2/assets/51680745/9e30d85f-4495-48f2-8690-4447d37b926c">


Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-20 06:58 UTC
Labels: Issue: Confirmed, Component: Email, Reproduced on 2.4.x, Priority: P2, Progress: done, Reported on 2.4.1, Area: Order
