### ISSUE TITLE
If Elasticsearch throws an error, it appears the indexer stops and fails silently

### ISSUE THREAD

**Issue by justinharris1986** [magento/magento2#18817] opened 2018-10-25 21:51 UTC
My OOP-fu is weak. I will attempt a patch at a later time, however, the community will be able to produce once faster than myself

### Preconditions
Magento version:
```
[magento@mage2 html]$ bin/magento -V
Magento CLI 2.3.0-beta23
```
apache version:
```
[magento@mage2 html]$ httpd -V | grep "Server version"
Server version: Apache/2.4.6 (CentOS)
```
PHP Version:
```
[magento@mage2 html]$ php -v
PHP 7.1.23 (cli) (built: Oct 10 2018 12:11:12) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```
Elastic version:
```
[root@mage2 ~]# yum list installed | grep elastic
elasticsearch.noarch                5.6.12-1                       @elasticsearch-5.x
```

### Steps to reproduce
1. Start a full re-index: 
```
bin/magento indexer:reindex catalogsearch_fulltext
```
2. Have elesticsearch fail. In my particular case it was with a:
```
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Limit of total fields [1000] in index [pv_product_1_v3] has been exceeded"}],"type":"illegal_argument_exception","reason":"Limit of total fields [1000] in index [pv_product_1_v3] has been exceeded"},"status":400}
```
I am still tracking down what caused this particular error, and will submit a separate bug report.

### Expected result
1. If elasticsearch POSTs fail, the Indexer should be in an inconsistent or re-index required state
2. If elasticsearch POSTs fail, A log entry should be generated. This should consist of the SKU of where it failed as well, for troubleshooting.

### Actual result
1. the indexer completes successfully and status is complete:
```
[magento@mage2 html]$ bin/magento index:status
+----------------------+------------------+-----------+---------------------+---------------------+
| Title                | Status           | Update On | Schedule Status     | Schedule Updated    |
+----------------------+------------------+-----------+---------------------+---------------------+
| Catalog Product Rule | Ready            | Schedule  | idle (0 in backlog) | 2018-10-24 15:56:47 |
| Catalog Rule Product | Ready            | Schedule  | idle (0 in backlog) | 2018-10-24 15:56:45 |
| Catalog Search       | Ready            | Schedule  | idle (0 in backlog) | 2018-10-24 21:42:07 |
| Category Flat Data   | Ready            | Schedule  | idle (0 in backlog) | 2018-10-24 15:56:44 |
| Category Products    | Ready            | Schedule  | idle (0 in backlog) | 2018-10-24 15:56:44 |
| Customer Grid        | Ready            | Schedule  | idle (0 in backlog) | 2018-10-24 15:56:52 |
| Design Config Grid   | Ready            | Schedule  | idle (0 in backlog) | 2018-10-24 15:56:43 |
| Product Categories   | Ready            | Schedule  | idle (0 in backlog) | 2018-10-24 15:56:45 |
| Product EAV          | Ready            | Schedule  | idle (0 in backlog) | 2018-10-24 16:38:27 |
| Product Flat Data    | Ready            | Schedule  | idle (0 in backlog) | 2018-10-24 16:37:07 |
| Product Price        | Ready            | Schedule  | idle (0 in backlog) | 2018-10-24 15:56:46 |
| Stock                | Ready            | Schedule  | idle (0 in backlog) | 2018-10-24 15:56:45 |
+----------------------+------------------+-----------+---------------------+---------------------+
```
2. No error log (There are other logs in the exception.log, so I know it is working):
```
[magento@mage2 ~]$ cat /var/www/html/var/log/exception.log  | egrep -i "400|illegal_argument_exception|reason|Limit of total fields|exceeded"
[magento@mage2 ~]$ ls -lhs /var/www/html/var/log/exception.log 
56K -rw-rw-r--. 1 apache apache 51K Oct 25 16:49 /var/www/html/var/log/exception.log
[magento@mage2 ~]$ 
```
This causes an issue, because, according to the above, the indexer is in a valid state with all SKU properly indexed, however, we can see that we are missing products:
Elasticsearch as 154741 documents:
```
[magento@mage2 ~]$ curl http://127.0.0.1:9200/_cat/indices?v
health status index           uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   pv_product_1_v3 HIQtzTiSS0Kn-phacLHvxg   5   1     154741            1    149.2mb        149.2mb
```
Mysql has 191083 rows: 
```
mysql> SELECT COUNT(*) FROM catalog_product_flat_1;
+----------+
| COUNT(*) |
+----------+
|   191083 |
+----------+
1 row in set (0.04 sec)
```

In our particular case, this is not only affecting search results, but Catalog pages as well.

This issue seems to affect both a full re-index, and a incremental re-index. IE, after it fails with the first full re-index, you cannot add any new SKU with additional fields. You cannot re-run the cron and have it pick back up.

**Comment by magento-engcom-team** [comment] 2018-10-25 21:51
Hi @justinharris1986. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@justinharris1986 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by justinharris1986** [comment] 2018-10-25 21:54
Yes I was able to re-produce this issue on a vanilla install. I did have to load a rather large catalog from the Magento 1 -> 2 migration tool to trigger the original issue though, that prompted this one.

**Comment by magento-engcom-team** [comment] 2018-11-09 15:06
Hi @TomashKhamlai. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by TomashKhamlai** [comment] 2018-11-09 15:58
Hello @justinharris1986. I believe that there is a mistake in Magento DevDocs. Please look here for additional details [https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html)

It said that only 5.2.x is supported. I understand that you can provide a links where it said that 5.x is supported, but that's mistake. We are working on it.

Try to use Magento with ES 5.2.2. Feel free to reopen if this step won't help you.

**Closed as completed** 2018-11-09 15:59 UTC
Labels: Issue: Clear Description, Issue: Format is valid, Component: Elasticsearch
