### ISSUE TITLE
Customers that have unsubscribed to the newsletter in the time span from when the queue was created and the actual sending of the newsletter still receive newsletters

### ISSUE THREAD

**Issue by victortodoran** [magento/magento2#32116] opened 2021-02-11 14:44 UTC
### Preconditions (*)

1. Latest Magento install 2.4-develop

### Steps to reproduce (*)

1. Subscribe 2 customers to newsletter
2. Confirm their subscription
3. Create a newsletter queue that is to execute after a few minutes (say 5 for example)
4. Unsubscribe one of the customers (**before** the queue executes)

### Expected result (*)

1. Only the subscribed customer receives the newsletter email

### Actual result (*)

1. Both customers receive the newsletter email.

### Additional comment 
Due to harshness of GDPR laws and the sometimes enormous fees I'm marking this is S0 in my book.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2021-02-12 13:19
Hello @victortodoran 

Thank you for your report.

We Confirm that the issue is reproducible on the latest 2.4-develop. The Unsubscribed Customer still receives a Newsletter.

**Comment by magento-engcom-team** [comment] 2021-02-12 13:20
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40885` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment] 2021-03-18 17:16
Hi @victortodoran. Thank you for your report. 
The issue has been fixed in magento/magento2#32186 by @engcom-Charlie in 2.4-develop branch
Related commit(s):
 - [35468fcf492f78ce46a31b92be4fb5cd2f0ae9d5](https://github.com/magento/magento2/commit/35468fcf492f78ce46a31b92be4fb5cd2f0ae9d5)
 - [23bfcdd84291ed84ebb6c06d820a92cd57116039](https://github.com/magento/magento2/commit/23bfcdd84291ed84ebb6c06d820a92cd57116039)
 - [d594fa7b706d83086e0a1cd04a5fbd2523603744](https://github.com/magento/magento2/commit/d594fa7b706d83086e0a1cd04a5fbd2523603744)
 - [0ecec5dba5dda7d3071e312d25d971a053e3891f](https://github.com/magento/magento2/commit/0ecec5dba5dda7d3071e312d25d971a053e3891f)
 - [d98dc43b7d99529467afd6e2b618313b870d5e23](https://github.com/magento/magento2/commit/d98dc43b7d99529467afd6e2b618313b870d5e23)
 - [ec464f5e65022602b14dbf790466d7a6ee205937](https://github.com/magento/magento2/commit/ec464f5e65022602b14dbf790466d7a6ee205937)
 - [64066c41903c9c0fb20f75e527a1e8c5505fc9b5](https://github.com/magento/magento2/commit/64066c41903c9c0fb20f75e527a1e8c5505fc9b5)
 - [f3c3a1db9c04c7dc811d8518ff7413465fc1ad1d](https://github.com/magento/magento2/commit/f3c3a1db9c04c7dc811d8518ff7413465fc1ad1d)

The fix will be available with the upcoming 2.4.3 release.

**Closed as completed by gabrieldagama** 2021-03-18 17:16 UTC
Labels: Issue: Confirmed, Component: Newsletter, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P2, Severity: S2, Progress: done, Issue: ready for confirmation, Reported on 2.4.x
