### ISSUE TITLE
Product resized image return same image url

### ISSUE THREAD

**Issue by mhaack** [magento/magento2#26119] opened 2019-04-16 07:02 UTC
### Preconditions (*)
1. Magento 2.4
2. Available product with Image added
### Description (*)
A product query for resized images returns the identical image url for all different image sizes. Tested on 2.3.1.
### Steps to reproduce (*)
Use the following query to reproduce:
```
{
  products(filter: {url_key: {eq: "simple-product-23308"}}) {
    items {
      name
      sku
      id
      url_key
      image {
        url
      }
      thumbnail {
        url
      }
      small_image {
        url
      }
    }
  }
}
```

### Actual result (*)
All image urls for `image`, `thumbnail` and `small_image` are identical. For example:
```
{
  "data": {
    "products": {
      "items": [
        {
          "name": "Simple Product 23308",
          "sku": "product_dynamic_23308",
          "id": 23314,
          "url_key": "simple-product-23308",
          "image": {
            "url": "https://xyz.com/media/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/8/2/82161242827b703e6acf9c726942a1e4.jpg"
          },
          "thumbnail": {
            "url": "https://xyz.com/media/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/8/2/82161242827b703e6acf9c726942a1e4.jpg"
          },
          "small_image": {
            "url": "https://xyz.com/media/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/8/2/82161242827b703e6acf9c726942a1e4.jpg"
          }
        }
      ]
    }
  }
}
```

### Expected result (*)
Query to return the correct url of the resized image.

**Comment by magento-engcom-team** [comment] 2019-12-18 22:55
@lenaorobei Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by engcom-Bravo** [comment] 2019-12-19 11:13
Reproducible on 2.4.x 
GraphQL query returns the URL of the Image URL for Thumbnails and Small image

**Comment by magento-engcom-team** [comment] 2019-12-19 11:14
@engcom-Bravo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-12-19 11:15
@engcom-Bravo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-12-19 11:16
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29932` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by tdgroot** [comment] 2020-04-10 16:26
I have been trying to find a solution for this problem, and came up with a mediation fix: https://gist.github.com/tdgroot/7b98c44ce2585fa12496b16085d754ce

It makes it possible to do a request like so:
``` graphql
{
  products(filter: {})
  {
    items {
      sku
      thumbnail {
        label
        url(
          width: 550
          height: 550
        )
      }
      small_image {
        label
        url(
          width: 550
          height: 550
        )
      }
    }
  }
}
```

Please note that you can only use dimensions defined in `view.xml` files, because GraphQl will not resize new/custom dimensions on the fly.

Other than that, it works great! :+1:

**Comment by sanjay-github** [comment] 2020-04-28 08:39
@tdgroot :
Thanks a lot. The workaround is working for me in v2.3.4. Saved a lot of time.

**Comment by huykon** [comment] 2020-07-15 03:49
@tdgroot  @sanjay-github  I tried your code but the images response are placeholder image

**Comment by tdgroot** [comment] 2020-08-17 08:47
@m2-assistant I'm picking up this issue

**Comment by tdgroot** [comment] 2020-08-17 09:22
@magento I'm picking up this issue

**Comment by binhlx-smartosc** [comment] 2020-10-09 05:07
In Graphql query
area = "graphql"

But current all functions to get product image only working with area="frontend".

So with a special Graphql query, you can use function to load design with area="frontend" before get product image data
Or can use it in "resolve" function (class of Graphql)

`$area = $this->_areaList->getArea(\Magento\Framework\App\Area::AREA_FRONTEND);
  $area->load(\Magento\Framework\App\Area::PART_DESIGN);
  $area->load(\Magento\Framework\App\Area::PART_TRANSLATE);
  $area->detectDesign($this->_request);`

declare the same parameters in the class
vendor/magento/framework/View/DesignLoader.php

Hope you can understand

**Comment by odubovyk** [comment] 2020-10-22 19:10
This issue is going to be closed as **Not a Bug**. Magento was not designed to work as described in the ticket
Actual Magento behavior is that images returned in request as **thumbnail** and **small** types do not mean different dimensions of the same image. it means different image role. The role that given to an image was assigned to a product (role of base, small and thumbnail).

**Closed as completed** 2020-10-22 19:13 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: CatalogGraphQl, Reproduced on 2.4.x, Event: Global-Contribution-Day, Priority: P2, Severity: S2, Progress: done

**Comment by barryvdh** [comment] 2021-06-16 13:58
So why not add a parameter that either accepts height/width like the example in https://github.com/magento/magento2/issues/26119#issuecomment-612107396 or specify the image size from the view.xml

How else should you render images in good formats with PWA/headless?
