### ISSUE TITLE
Fatal error when do - media-gallery:sync

### ISSUE THREAD

**Issue by wandyyd** [magento/magento2#32901] opened 2021-04-29 09:01 UTC
### Preconditions (*)

1. Magento 2.4.2 (upgrade from 2.4.1)
2. Nginx server
3. PHP 7.4.16

**---Update---**
4. Enable Old Media Gallery - set to - No
5. Copy Media folder & files from M1 to M2
6. Run this, to make sure that folder is readable / writable
> find media -type f -exec chmod 775 {} \;
> find media -type d -exec chmod 755 {} \;

A little background, so, I tried to do migration from Magento 1.9.4.2 to Magento 2.4.2 (or latest version)
The update are going well, product data, attributes and else are moving very well
I also copy the Media related (step no.5 above) and when I check on front-end the images is shown correctly.
But, when I tried to check the images via Admin, Content > Media Gallery, I realize the images isn't shown, so I tried the suggestion mentioned on [here](https://github.com/magento/magento2/issues/32104), then I'm facing the issue, like I mentioned on **Actual Result**

I tried to upload an image through Admin (Media Gallery) to test around, and the test image is successfully uploaded.
**---Closing Update---**

### Steps to reproduce (*)

1. Run in console: php bin/magento media-gallery:sync

### Expected result (*)

1. No fatal error shown and image should be appear as been mentioned [here](https://github.com/magento/magento2/issues/32104)

### Actual result (*)

1.  ![image](https://user-images.githubusercontent.com/30722472/116526557-ebbd9b80-a903-11eb-9002-567117a57606.png)

<pre>
papdan_dev@ce2:~/html$ php bin/magento media-gallery:sync
Synchronizing assets information from media storage to database...
libpng warning: Interlace handling should be turned on when using png_read_image
PHP Fatal error:  Uncaught TypeError: substr() expects parameter 2 to be int, bool given in /var/www/html/vendor/magento/module-media-gallery-metadata/Model/Png/Segment/ReadXmp.php:84
Stack trace:
#0 /var/www/html/vendor/magento/module-media-gallery-metadata/Model/Png/Segment/ReadXmp.php(84): substr()
#1 /var/www/html/vendor/magento/module-media-gallery-metadata/Model/Png/Segment/ReadXmp.php(54): Magento\MediaGalleryMetadata\Model\Png\Segment\ReadXmp->getXmpData()
#2 /var/www/html/vendor/magento/module-media-gallery-metadata/Model/File/ExtractMetadata.php(93): Magento\MediaGalleryMetadata\Model\Png\Segment\ReadXmp->execute()
#3 /var/www/html/vendor/magento/module-media-gallery-metadata/Model/File/ExtractMetadata.php(68): Magento\MediaGalleryMetadata\Model\File\ExtractMetadata->readSegments()
#4 /var/www/html/vendor/magento/module-media-gallery-metadata-api/Model/ExtractMetadataComposite.php(62): Magento\MediaGalleryMetadata\Model\File\ExtractMetadata->execute()
#5 /var/www/html/vendor/magento/module-media-gallery-synchronizati in /var/www/html/vendor/magento/module-media-gallery-metadata/Model/Png/Segment/ReadXmp.php on line 84
</pre>

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by wandyyd** [comment] 2021-04-29 09:03
@magento give me 2.4.2 instance

**Comment by wandyyd** [comment] 2021-04-29 09:19
ahh.. seems I couldn't have SSH thing to test on the command.
Can mod helps on here?

**Comment by engcom-Oscar** [comment] 2021-04-30 07:55
Hi @wandyyd  ! Thank you for your report.
Unfortunately, we are not able to reproduce the issue. Looks like we miss some important preconditions, so may you please recheck and update description?

**Comment by wandyyd** [comment] 2021-04-30 09:17
Hi @engcom-Oscar !
Thanks for your reply, I already update the preconditions.
Please have a look if I miss some important things that need to be done.

PS - pardon me if I didn't reply promptly over the wekeend (I'm on GMT+7 timezone)
And so, I'm really new on Github world and stuffs, I do apologize if I miss some / other things that makes your works more difficult. 😞 

Thanks! 😄

**Comment by wandyyd** [comment] 2021-05-04 04:49
Hi.. any other updates on this?
Thanks!

**Comment by Nazar65** [comment] 2021-05-06 07:22
@magento I am working on this

**Comment by Nazar65** [comment] 2021-05-06 07:34
hi @wandyyd could you please send the image that's media gallery is trying ti update ? also you can disable the metadata module of media gallery as a temporary solution to do the sync

**Comment by Nazar65** [comment] 2021-05-06 07:38
@wandyyd looks like it's already fixed -> https://github.com/magento/magento2/commit/82f89f50d694cbc48aa1ccfa87db2324348387c9

**Comment by Nazar65** [comment] 2021-05-10 08:33
@wandyyd  i think it should be included in the next release @gabrieldagama could you help us ?

**Comment by wandyyd** [comment] 2021-05-11 01:50
Hi @Nazar65 - thanks for your info. So you mean, the next release will [**2.4.2-p1** on May 11](https://devdocs.magento.com/release/#release-schedule)?

**Comment by wandyyd** [comment] 2021-05-17 05:10
Hi @Nazar65 & @gabrieldagama - I just tried to update to Magento 2.4.2-p1, and I still seeing the related file having the same code as previously, like, it doesn't do any update

Is there any special treatment that I need to do?

**Comment by jesperbrejning** [comment] 2021-05-17 17:03
I have got the same issue

**Comment by Nazar65** [comment] 2021-05-18 06:13
@wandyyd  @jesperbrejning  could you please apply that changes directly ? as i can see this is not included in any release :(

**Comment by wandyyd** [comment] 2021-05-20 05:09
Hi @Nazar65 - thanks for confirming! 😄 

I just tried to apply that changes manually (copy-paste the code/file & image), it kinda success, I can see images are registered on **Media Gallery** at **Magento Admin** view, but it seems has a another issues / errors(?) on other part, along with its stack of warnings.

Here's the warning messages
![image](https://user-images.githubusercontent.com/30722472/118921375-40cc5a80-b962-11eb-9213-8892fc7efe3a.png)
<details>
<summary>Warning messages</summary>
<pre>
papdan_dev@ce2:~/html$ php bin/magento media-gallery:sync
Synchronizing assets information from media storage to database...
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
</pre>
</details>

And, after some waiting times, there's an error(?)
![image](https://user-images.githubusercontent.com/30722472/118921397-4b86ef80-b962-11eb-81c1-5b795a073631.png)
<details>
<summary>Error(?) messages</summary>
<pre>
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image

In Synchronize.php line 83:

  Failed to execute the following synchronizers: media_gallery_asset_synchronizer, media_gallery_asset_synchronizer, media_
  gallery_asset_synchronizer, media_gallery_asset_synchronizer, media_gallery_asset_synchronizer, media_gallery_asset_synch
  ronizer, media_gallery_asset_synchronizer, media_gallery_asset_synchronizer, media_gallery_asset_synchronizer, media_gall
  ery_asset_synchronizer, media_gallery_asset_synchronizer, media_gallery_asset_synchronizer, media_gallery_asset_synchroni
  zer, media_gallery_asset_synchronizer, media_gallery_asset_synchronizer, media_gallery_asset_synchronizer, media_gallery_
  asset_synchronizer, media_gallery_asset_synchronizer, media_gallery_asset_synchronizer, media_gallery_asset_synchronizer


media-gallery:sync
</pre>
</details>

So, I got some questions
1. From above error? is that normal / intended? or I do need some other fixes?
2. I just realize after apply the fix, that the fix you mentioned, are for **Magento Cloud**. Is that okay?

---
FYI, I also run this command
> php bin/magento media-content:sync

And, it's **success** without error! 🥳 
![image](https://user-images.githubusercontent.com/30722472/118921472-6eb19f00-b962-11eb-9bfc-17608d05af28.png)

**Comment by magento-engcom-team** [comment] 2021-05-27 11:45
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42473` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment] 2021-05-27 16:11
Hi @Nazar65, yeah I believe that will be delivered on the next patch release. If we are having another issue I suggest closing this one and open a new for the issue mentioned above. 

Thanks!

**Comment by wandyyd** [comment] 2021-05-31 03:56
Hi @gabrieldagama - thanks for confirming. But, I didn't see that on [**2.4.2-p1** on May 11](https://devdocs.magento.com/release/#release-schedule), would it be released on p2?

Cheers!

**Closed as completed** 2021-08-31 19:25 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Component: MediaContentSynchronization, Progress: done, Area: Upgrades - Upgrade Compatibility Tool
