### ISSUE TITLE
Products import not works with sample file

### ISSUE THREAD

**Issue by biotech** [magento/magento2#1802] opened 2015-09-05 17:09 UTC
I use recent version on master branch . Trying to import products with provided sample file and get error -Notice: Undefined index: Gear in app/code/Magento/CatalogImportExport/Model/Import/Product/Type/AbstractType.php on line 170

Gear it's name of assigned category in your original sample file (catgories - Default Category/Gear|Default Category/Gear/Fitness Equipment ), when i remove everything and leave only Default Category there - import works. But i notice that product import with empty name field, which is not possible because this is required..

Is import feature not completed yet or should works already? Thanks. 

<img width="1155" alt="screenshot 2015-09-05 19 08 03" src="https://cloud.githubusercontent.com/assets/2007450/9700400/9ac6a56c-5401-11e5-8868-d6669b9189c5.png">

**Comment by kandy** [comment] 2016-01-15 15:47
@biotech, I cannot reproduce issue in latest mainline, so I am closing this issue, as fixed. Feel free to open new issue if we missed anything.

**Closed by kandy** 2016-01-15 15:47 UTC
Labels: MX, question
