### ISSUE TITLE
M2.1: Not scrollable picture on mobile / product page

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#5302] opened 2016-06-28 07:00 UTC
## Steps to reproduce
1. Install Magento 2.1 via download
2. install official sample data
3. Go to a product page
4. try to scroll down by hovering the picture
## Expected result
1. The site scrolls down also by touching the product picture
## Actual result
1. the product picture is not "scrollable" that means if you place your finger over the picture and try to scroll down nothing happens

![bildschirmfoto 2016-06-28 um 08 56 04](https://cloud.githubusercontent.com/assets/16196483/16406478/c89002c6-3d0e-11e6-8aa5-3c0d1ad11e3d.png)

This issue appeared on early magento2 versions and was fixed then. Now it is there again and it is important. I do not know if this issue just happens when no product picture is uploaded and placeholder is shown or if this happens also with a product picture uploaded.

Anyway - this needs to be fixes asap as this is a massiv blocker for users.

**Comment by andidhouse** [comment] 2016-06-30 13:16
I think this is really an important bug stopping users to shop mobile at all so it needs to be reviewed here pls.

**Comment by andidhouse** [comment] 2016-07-19 12:43
@ilol can you pls have a look on this. i think it is really important as it is a total conversion blocker for mobile users! 

thanks!

**Comment by ilol** [comment] 2016-07-19 13:34
Thank you @andidhouse , registered to fix MAGETWO-55608

**Comment by gazoscalvertos** [comment] 2016-08-07 23:06
Please fix this, its a major issue on our site as the image spans 100% width.

**Comment by apurv-anand** [comment] 2016-08-09 12:27
+1 
Hit my this issue as well. Does anyone know any workaround for now?

**Comment by Simpsonight** [comment] 2016-08-09 16:09
Here is a workaround for this bug which solves the problem.
Replace the hole `onMove(e)` function in file [magento2/lib/web/fotorama/fotorama.js](https://github.com/magento/magento2/blob/2.1/lib/web/fotorama/fotorama.js), at Line 1418, with the following code snippet:

```
function onMove(e) {
            if ((e.touches && e.touches.length > 1)
                || (MS_POINTER && !e.isPrimary)
                || moveEventType !== e.type
                || !touchEnabledFLAG) {
                touchEnabledFLAG && onEnd();
                (options.onTouchEnd || noop)();
                return;
            }

            extendEvent(e);

            var xDiff = Math.abs(e._x - startEvent._x), // opt _x → _pageX
                yDiff = Math.abs(e._y - startEvent._y),
                xyDiff = xDiff - yDiff,
                xWin = (tail.go || tail.x || xyDiff >= 0) && !tail.noSwipe,
                yWin = xyDiff < 0;


            if (touchFLAG && !tail.checked) {
              if (touchEnabledFLAG = xWin) {
                stopEvent(e);
              }
            } else {
                stopEvent(e);
                (options.onMove || noop).call(el, e, {touch: touchFLAG});
            }

            if (!moved && Math.sqrt(Math.pow(xDiff, 2) + Math.pow(yDiff, 2)) > tolerance) {
                moved = true;
            }

            tail.checked = tail.checked || xWin || yWin;
        }
```

**Comment by ghost** [comment] 2016-09-06 15:00
Has this been fixed? This is a pretty big issue for mobile shoppers. The workaround does not seem to work on 2.1.1 rendering Magento pretty useless on a good number of mobile devices.

**Comment by jupiter01** [comment] 2016-09-07 01:02
I noticed that this issue didn't occur in the luma theme so I grabbed the view.xml file from that theme and added it to the custom theme we were working with. Now it scrolls as it should. If I'm able to narrow down the exact issue I will post what I have found.

**Comment by ghost** [comment] 2016-09-07 15:47
If you take a look at the default luma and blank theme this bug doesn't seem to have an impact on them. It rears its head on custom themes and is very present on several live sites I have looked at running CE.

**Comment by andidhouse** [comment] 2016-09-14 11:29
3 month later without an official bugfix of a major bug... i really do not know what is going on on magento side...

**Comment by ghost** [comment] 2016-09-14 11:53
It's pretty obvious, CE is not in the future.

**Comment by ghost** [comment] 2016-09-14 22:17
@andimov  @ilol any info on this bugfix?

**Comment by ilol** [comment] 2016-09-15 10:00
Development completed. So we are merging this into mainline and older versions.

**Comment by ghost** [comment] 2016-09-15 15:03
Thanks for responding, if your able to provide a date, when will we be able to utilize this, and how?

**Comment by SerhiyShkolyarenko** [comment] 2016-09-20 12:52
Fix of MAGETWO-55608 is delivered to develop branch. Closing the issue.

**Closed as completed by SerhiyShkolyarenko** 2016-09-20 12:52 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog

**Comment by PaperDS** [comment] 2016-10-10 17:06
I have test site with v2.1.1 and am having the same problem with Luma and sample data installed.
Scroll not working on mobile. http://test.starfishratings.net/

**Comment by ghost** [comment] 2016-10-10 19:50
@PaperDS the fix is available in the developer branch, you could grab it from there and add it to your current install.

**Comment by keyurshah** [comment] 2016-10-12 20:34
still seems to be an issue in the version released today, 2.1.2

**Comment by ghost** [comment] 2016-10-13 01:29
Yes, I can confirm the fix isn't in 2.1.2. Not sure why....

**Comment by PaperDS** [comment] 2016-10-13 11:18
So will this issue be reopened?

**Comment by jibrandlr** [comment] 2016-10-13 15:26
@PaperDS Currently Magento 2.X.X has **hundreds** of issues. So far every release comes with fixes for 5-10 of those issues **plus new ones** of the specific release.
Some of the fixes are already available in the developer branch. That doesn't mean the fixes will be included in the next release. It might take Magento months (years?) to include those fixes in an "official" release.
You have 3 options:
- Stay with Magento 1
- Search for the fix of your issue in the developer branch
- **Drop Magento and choose a software that just works as expected**

**Comment by ghost** [comment] 2016-10-13 16:34
Are there as many issues with EE?

**Comment by jibrandlr** [comment] 2016-10-13 17:38
@jupiter01 I don't know really (i'm not a Magento employee). My previous comment is based on my experience so far using Magento 2 CE  and the number of issues reported already in github by the community.

**Comment by sshymko** [comment] 2016-11-16 16:31
Suffering from the same issue.

@piotrekkaminski @elenleonova @pboisvert 
What release is the fix going to be included in? When is it coming out?

**Comment by erikhansen** [comment] 2016-11-17 22:01
Applying the https://github.com/magento/magento2/commit/7597a52dbf7179106b4ebba928dc04efbe6a8c78 commit as a patch (add .patch to the end of that url to get a patch file) to my environment fixed the issue for me.

**Comment by yofisim** [comment] 2016-11-23 10:29
After updating the following files, the patch is still not working.

**Comment by giusecapo** [comment] 2016-11-24 12:24
Did anyone find a solution?

**Comment by yofisim** [comment] 2016-11-24 12:29
Hi all, after some reviews, as I'm a very noobie to magento.
When I imported the files, the fix was not working for me too..
But after digging, I found that you have to recompile the files for the patch to work.
Which means you have to:

1) Replace the fotorama files as explained in the thread.
2 Run the following queries in M2 root folder in command line:
`php bin/magento setup:upgrade`
`php bin/magento setup:di:compile`
`php bin/magento setup:static-content:deploy`
`php bin/magento cache:flush`
`php bin/magento index:reindex`

And this should work. At least it did for me!
Thumb up if it worked 👍 !

More info about M2 command line here: http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands.html

**Comment by giusecapo** [comment] 2016-11-24 12:38
Sorry, I'm noobie (a lot) too, how to install the patch? @yofisim

**Comment by yofisim** [comment] 2016-11-24 12:42
You will find the files to replace (and the exact lines that have been changed) here:
https://github.com/magento/magento2/commit/7597a52dbf7179106b4ebba928dc04efbe6a8c78

Replace them, then go for the few commands I gave you.

Good luck 💯

**Comment by giusecapo** [comment] 2016-11-24 13:29
Unfortunately, I did everything exactly as you suggested me... But it still doesn't work :( @yofisim

**Comment by yofisim** [comment] 2016-11-24 13:31
@giusecapo on your browser, when you're on the product page, check the fotorama.js file the browser process to see if you have inserted the correct files and did the right manipulation

**Comment by giusecapo** [comment] 2016-11-24 13:34
You're right, page is loading fotorama.js from pub/static/... Do you know why? Should I clear static files again? @yofisim

**Comment by giusecapo** [comment] 2016-11-24 13:38
Ok! It works! Thanks for your help, maybe I called deploy static content before ftp finished upload :) You made my day man @yofisim

**Comment by yofisim** [comment] 2016-11-24 13:39
@giusecapo
Yes it's right, Magento needs this file to process the images and render them.
I want you to check the file itself, and see if the change you made is taken by the browser.

Report again to these files here: https://github.com/magento/magento2/commit/7597a52dbf7179106b4ebba928dc04efbe6a8c78

and check the changes @

**Comment by yofisim** [comment] 2016-11-24 13:39
Ow nice! thumb up! Have a nice dev day @giusecapo

**Comment by jmtakahashi** [comment] 2016-12-05 05:39
@ilol @yofisim note that this fix works on initial page load, but on reload (refresh) it does not work.  on reload, first image in the slider will react to up and down scrolling, but on 2nd image or 3rd image (any image after first), the scrolling issue persists.

**Comment by yofisim** [comment] 2016-12-05 18:42
@jmtakahashi please provide more infos as I tried to reproduce your issue
and didn't succeed. Patch is working fine from my side.

**Comment by jmtakahashi** [comment] 2016-12-06 06:09
@yofisim 

Device:
a.) iphone 6s
b.) private browsing mode

Magento 2.1.2 (i'm including these because the JS merge, minify and bundle are problems in themselves when set to on)
a.) Minify, Bundle, Merge JS: ALL OFF
b.) Merge and Minify CSS:  ON
c.) Minify Html: OFF

1.) Click to an individual product page from any page.
2.) Check slider (all images), and check scrolling.  It will work.
3.) Reload the individual product page a few times.
4.) Check slider (default first image), scrolling will work with first image.
5.) Slide to 2nd or 3rd image, scrolling up and down while finger is over the image stops working.

Hope this helps.  I'm not sure whether the Private Browsing mode has anything to do with it, but reloading the page (today) once, and it still worked.  Then the 2nd time reloading it stopped working again.

**Comment by yofisim** [comment] 2016-12-06 06:16
@jmtakahashi dis you emulate on your browser in Desktop? Can you please
check the console to retrieve the error that is triggered when the
scrolling doesn't work.

It's a very weird issue and I believe it comes from elsewhere in the code.
Maybe you can provide URL?

**Comment by jmtakahashi** [comment] 2016-12-06 06:32
@yofisim this was tested on an actual phone.  https://vizume.com

Any product image does the same thing.

**Comment by andidhouse** [comment] 2016-12-08 16:59
we give it up on the native photorama implementation due to:

- problem with mobile devices and scrolling issue
- extreme long load times of the script compared to for example magic zoom
- some other small bugs and in general poor implementation of the script at this moment

Magic zoom works like a charm and has a great support fixing bugs in minute not years.

**Comment by elenleonova** [comment] 2016-12-15 02:02
The issue has been delivered to 2.1.3

**Comment by andidhouse** [comment] 2016-12-15 12:14
i can confirm this is fixed n 2.1.3
thanks!

**Comment by erik-augustin** [comment] 2016-12-18 21:28
Its not fixed in chrome on ios (its fixed in safari)

**Comment by erik-augustin** [comment] 2016-12-18 21:34
Its not fixed on Chrome on ios iphone. Its fixed in Safari.

**Comment by through-a-haze** [comment] 2017-01-26 13:11
@erik-augustin just rechecked. It's fixed on both for me.
