### ISSUE TITLE
Refund order Item is incrementing the quantity of the product item

### ISSUE THREAD

**Issue by lano-vargas** [magento/magento2#16558] opened 2018-07-05 12:00 UTC
Magento2.2.2  Version.

### Preconditions

In Configuration->Stores->Catalog->Inventory->Product Stock Options Set 

> Automatically Return Credit Memo Item to Stock = No

<img width="1564" alt="screen shot 2018-07-05 at 12 23 20" src="https://user-images.githubusercontent.com/3495481/42321094-992175ac-804f-11e8-9abf-1e6ec6bef667.png">

### Steps to reproduce
Create a category Called **test**  then create configurable product add to attribute set Default, assign to category **test** fill in all the required fields then create/assign 2 simple product with color red,blue add Qty I've added **10** to both create and save. 

Go to the front store and click on the product choose your color add to cart got to checkout and place and order!
Now Go to the Backend Admin go to Sale->Operations->Orders pick the order you've just created 
process the order invoice,ship etc.. 
make note of sku.

Now go to Catalog->Inventory->Products 

Filter by sku that you noted.
check qty should be **9**

Go Back to the Backend Admin go to Sale->Operations->Orders pick the order you've just created.

On the left Menu click Invoices then click view invoice and in top header menu click Credit Memo

in the Credit memo page Please **NOTE** do not check` return to stock` checkbox 

<img width="700" alt="screen shot 2018-07-05 at 12 54 23" src="https://user-images.githubusercontent.com/3495481/42322072-f56bbb94-8052-11e8-90e1-aa54605bd42f.png">

then click  Refund Offline or Refund.

Process finished. 

### Expected result
Now go back to Catalog->Inventory->Products  pick the product you've just bought the qty should be **9**

### Actual result
Now go back to Catalog->Inventory->Products  pick the product you've just bought the qty is **10**

This is really bad it created a lot of unhappy customer buying products that were 0 in stock then refunded which increments to 1 which makes it back in stock.

Regards!.

**Comment by magento-engcom-team** [comment] 2018-07-05 12:00
Hi @lano-vargas. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@lano-vargas do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment] 2018-07-05 13:39
@lano-vargas, thank you for your report. Unfortunately I'm not able to reproduce this issue.
![peek 2018-07-05 16-10](https://user-images.githubusercontent.com/40755810/42326393-aa58ebda-8071-11e8-9f81-7127ea10f795.gif)
Could you please correct my steps?

**Comment by lano-vargas** [comment] 2018-07-05 14:08
@engcom-backlog-nickolas  Apologies for the early issue report I was given a tour from the customer team as refund issue. after further investigation and disabling all extra module extension it seens to be working fine I just need the customer team to confirm and then I will find out which module is causing this issue. I'll update here. thank for the video appreciate.

Regards!.

**Comment by engcom-backlog-nickolas** [comment] 2018-07-05 14:42
@lano-vargas, thank you for feedback. I'm closing this issue, if you don't mind, until update. Feel free to reopen it if needed.

Best regards!

**Closed as completed by engcom-backlog-nickolas** 2018-07-05 14:42 UTC
Labels: Issue: Clear Description, Issue: Format is valid
