### ISSUE TITLE
Filter by attribute doesn't bring any products

### ISSUE THREAD

**Issue by nsid32** [magento/magento2#11101] opened 2017-09-27 19:45 UTC
Hi,

### Preconditions

1. Magento version 2.1.9
2. PHP 7.0
3. MySQL 5.6

### Steps to reproduce
I have added an attribute (multi select) in a M2 site that I have. This attribute is called Occasion. I have linked some products with some attribute values, for example Birthday. I have also included the attribute in the layered navigation. I can see the number of products in the parenthesis (in the layered navigation) next to Birthday but when I click on Birthday to filter the products on the right it says that no products exist with this value on the right.

### Expected result
1.  To show the products that match the attribute selected on the left

### Actual result
1. No products exist on the right

I have reindexed, attribute is set to "filterable with results"

![4xlzj](https://user-images.githubusercontent.com/1909535/30934188-b4b281f2-a3c4-11e7-98c4-fdbd03de49f2.jpg)

<img width="951" alt="iei4o" src="https://user-images.githubusercontent.com/1909535/30934195-baf74dc2-a3c4-11e7-951c-a8b8a71f63ef.png">

**Comment by magento-engcom-team** [comment] 2017-09-28 10:41
@nsid32 We can't reproduce this issue. Please install clean Magento 2.1.9, and try to reproduce this issue again.

**Comment by palo** [comment] 2017-10-03 09:40
I have the same issue. ~~I'm not able to reproduce it in a clean install. There must be another way to find the cause of it.~~ 
 @magento-engcom-team  I'm able to reproduce it following the steps in https://github.com/magento/magento2/issues/11189

**Comment by orlangur** [comment] 2017-10-03 11:31
Thanks @palo for your efforts in issue reproduction, closing this issue in favor of new one to keep the investigation consolidated.

**Closed as completed by orlangur** 2017-10-03 11:31 UTC
Labels: bug report, duplicate, Issue: Clear Description, Issue: Format is valid
