### ISSUE TITLE
Fatal error: Cannot instantiate interface

### ISSUE THREAD

**Issue by bvboas** [magento/magento2#2502] opened 2015-11-24 16:21 UTC
My magento store is throwing this error:

> Fatal error: Cannot instantiate interface Magento\Framework\View\Design\Theme\ResolverInterface in /Library/WebServer/Documents/magento/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 73

I don't know why it started to appear. I made no new module installation. The store was working fine.

I've check file permissions and I see no issue there. Also deleted /var/ dir and folders/files where created.

The preference is defined vendor/magento/magento2-base/app/etc/di.xml

``` xml
<preference for="Magento\Framework\View\Design\Theme\ResolverInterface" type="Magento\Theme\Model\Theme\Resolver" /> 
```

**Comment by mazhalai** [comment] 2015-11-24 23:42
@bvboas can you please give more details about your environment, and how to reproduce this error? Navigate to front end or backend after installation?

**Comment by bvboas** [comment] 2015-11-24 23:52
OS: MAC OS X 10.9
PHP 5.6.11
Apache/2.2.29 (Unix)

I don't have any third-party extension enabled.

I just have to visit any page, frontend or backend, for the error to show.

**Comment by mazhalai** [comment] 2015-11-25 00:20
@bvboas what [mode](http://devdocs.magento.com/guides/v2.0/config-guide/bootstrap/magento-modes.html) are you in?

**Comment by bvboas** [comment] 2015-11-25 00:31
@mazhalai The .htaccess directive

> SetEnv

 is commented. So I assume is in 'default'

Switched to developer and production, but the error persists.

**Comment by mazhalai** [comment] 2015-11-25 00:38
@bvboas can you check apache or php logs to see if there is any stack trace?

**Comment by alankent** [comment] 2015-11-25 00:40
You might check the di.xml file to see if you added a comment and failed to close it correctly, or something silly like that to cause the <preference...> element to be omitted. The fact that it worked and now does not, leads me to the suspicion "you accidentally broke it". I am trying to think of how you could have done this - an XML comment is one way the preference was not loaded.

**Comment by bvboas** [comment] 2015-11-25 00:48
@alankent You were right. 

I've just switched to phpStorm, and since there are no warnings about saving changes, for some reason

``` xml
<preference for="Magento\Framework\View\Design\Theme\ResolverInterface" type="Magento\Theme\Model\Theme\Resolver" />
```

became

``` xml
<preference for="Magento\Framework\View\Design\Theme\ResolverIdeveloperMaterializationnterface" type="Magento\Theme\Model\Theme\Resolver" />
```

Sorry about this.

**Comment by mazhalai** [comment] 2015-11-25 03:54
@bvboas thank you for your update. Closing this issue. Please feel free to open a new one in case of any issues.

**Closed as completed by mazhalai** 2015-11-25 03:54 UTC
Labels: Progress: needs update

**Comment by alankent** [comment] 2015-11-25 20:52
"You were right." SCORE!!!

Ahem. Glad to be of help.

**Comment by rexha5minds** [comment] 2016-01-03 12:49
i dont understand, how you resolve this problem, can you please explain it again, because i have the same error and search for a solution my last 5 hours

**Comment by bvboas** [comment] 2016-01-05 01:48
@rexha5minds it was an issue with the di.xml file. Make sure you haven't made any changes.

**Comment by tdgroot** [comment] 2016-07-13 08:10
I have had this issue as well, having the deploy mode set to `developer`. Turns out I got this error because I used `--no-dev` when installing the application.

**Comment by tristanisginger** [comment] 2018-03-07 09:27
As @alankent says "Check your di.xml"

I didn't realise you need to add it as a preference if you instantiate it. [Documentation](http://devdocs.magento.com/guides/v2.1/extension-dev-guide/build/di-xml-file.html#abstraction-implementation-mappings)
