### ISSUE TITLE
Indexer cronjobs flushes all category and product pages in FPC / Varnish

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#29806] opened 2020-08-29 08:34 UTC
### Preconditions
1. Magento 2.3.5-p1
2. Have Varnish configured as full page cache.
3. Have the Magento cronjob scheduled to run every minute.
3. Have the indexers all set to "Update on schedule"
4. Have Varnish configured to monitor / log incoming cache purge requests

### Steps to reproduce
1. Have an indexer, for instance the "Category Products" index, set to "Index required"
2. Let the cronjob run every minute which will try to update the invalid indexes

### Expected result
1. When the cron updating the indexes runs and it can't set the index to "Ready", don't flush the FPC for category and product pages.

### Actual result
1. Magento sends a purge request to Varnish with the following tags: "cat_p" and "cat_c". This flushes all the category pages and product pages which are in the FPC, basically flushing the FPC every minute.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ihor-sviziev** [comment] 2020-09-10 09:02
@dverkade could you add some example which request varnish gets?

**Comment by dverkade** [comment] 2020-09-10 09:16
@ihor-sviziev example was already included in the initial description. The varnish request is including the following tags at this point: "cat_p" and "cat_c".

**Comment by ihor-sviziev** [comment] 2021-01-29 04:50
Hi @dverkade,
I understand the issue you have, but usually, when some data in the index has changed - we have to clean FPC for affected categories or products.
Do you have any thoughts on how we can implement your suggestion?

**Comment by dverkade** [comment] 2021-01-29 09:00
Flushing of the caches could only occur when the index is set to "Ready" again. If the index fails flushing the caches should not occur.

**Comment by dverkade** [comment] 2021-04-15 13:52
Issues should not automatically close. Posting this comment to keep it active.

**Comment by ihor-sviziev** [comment] 2021-04-15 13:55
@sidolov @gabrieldagama @sivaschenko could you take a look? It looks really important issue, probably should be P2

**Comment by gabrieldagama** [comment] 2021-04-15 14:08
Hi @dverkade, thanks for reporting. Do you know if this issue is reproducible on 2.4-develop?

Thanks.

**Comment by duckchip** [comment] 2021-04-30 07:03
@gabrieldagama 

don't know if it's 100% related but linking it anyway: 
https://github.com/magento/magento2/issues/32780

**Comment by engcom-Hotel** [comment] 2021-07-14 18:08
Hello @dverkade,

We have tried to reproduce the issue in 2.4-develop, but this is not reproducible. As per your comment,  if the indexing fails then the cache should not flush, So I just stop ES service, so that indexing fails while running cron.

And then check the page load time, but it is still loading in milliseconds, and whenever I flush the cache the homepage takes around 5 to 9 seconds in loading. 

Please help us if we missed anything in order to reproduce the issue. Or please try to reproduce the issue in the 2.4-develop branch.

Thanks

**Comment by engcom-Hotel** [comment] 2021-07-28 16:40
Hello @dverkade,

It seems that the issue has been resolved. We are closing this issue for now because we are not able to get a response from you for 14 days.

If you still facing the issue, either you can reopen this issue or create a new one.

Thanks

**Closed as completed by engcom-Hotel** 2021-07-28 16:40 UTC
Labels: Component: Cache, Severity: S1, Issue: needs update, Reported on 2.3.5-p1
