### ISSUE TITLE
Infinite loading of orders

### ISSUE THREAD

**Issue by iUnKindledOne** [magento/magento2#32890] opened 2021-04-28 08:37 UTC
- Summary of the issue:
      Tried to filter orders on specific date. Reached the last page of results and then it said "Something went wrong" took back to orders page saying "Something went wrong with processing the default view and we have restored the filter to its original state" and then in infinite loading page will show up. Can't do nothing in "Orders" page. 

     - Information on your environment:
     We are a food chain business.

     - Steps to reproduce:
     I don't know what does that mean, but i tried cache and cookies clear. Also tried other browsers. 

     - Expected and actual results:
     Nothing happened 

-->

### Preconditions (*)
1. Magento version 2.3.5

### Steps to reproduce (*)
1. Cache clear 
2. Browser change
3. Cookies clear 

### Expected result (*)
1. Problem should've been solved and no more infinite loading screen on "Orders" tab

### Actual result (*)
1. Nothing happened problem stayed the same

**Comment by engcom-Oscar** [comment] 2021-04-28 13:08
Hi @iUnKindledOne ! Thank you for your report.
Unfortunately, we are not able to reproduce the issue, looks like we miss some important preconditions, may you please update description.

**Comment by fzr-dave** [comment] 2021-04-29 13:58
I had the same problem with one user. The only way I found to fix the problem was to delete the user and then re-enter them as a new user.

**Comment by iUnKindledOne** [comment] 2021-04-30 15:50
Thank you so much, did that and all good. I searched and the problem is known for years. Man magento support sucks

**Comment by engcom-Oscar** [comment] 2021-05-13 11:14
As we were not able to reproduce the issue on a fresh 2.4-develop by following steps from this ticket, we have to close this ticket.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch.

**Closed as completed by engcom-Oscar** 2021-05-13 11:14 UTC
Labels: Issue: needs update
