### ISSUE TITLE
Cannot add/edit categories and products, everything else is fine

### ISSUE THREAD

**Issue by adarshkhatri** [magento/magento2#6000] opened 2016-08-05 05:10 UTC
Not sure if this is a bug.

I have installed magento 2.1.0 in shared hosting through cPanel. All is ok, I can access admin and configure my store.

I have set single store mode then when I try to add categories/products there is no form populated, in fact the form area is completely empty. See image: http://i.stack.imgur.com/69wo2.png
### Preconditions

1.  Magento 2.1.0
2.  PHP 7.0.9
### Steps to reproduce

1.  Install fresh Magento 2.1.0 version from cPanel in shared hosting (siteground)
2.  Go to `Product > Categories`
### Expected result
1.  Categories should populate
2.  And should allow to add/edit them
### Actual result
1. No form populated, http://i.stack.imgur.com/69wo2.png
2. But url do changes to edit/add mode

I have also followed this issue report: https://github.com/magento/magento2/issues/2402

But this also didn't help.

**Comment by southerncomputer** [comment] 2016-08-05 21:19
Enable developer mode and show the console/debugger window.

Probably need to do php bin/magento deploy:mode:set production 
Php bin/magento setup:static-content:deploy
Php bin/magento cache:clean

(Service php-fpm restart if using php-fpm is opcache enabled )

**Comment by adarshkhatri** [comment] 2016-08-06 02:49
On running `php bin/magento deploy:ode:set product` it gives me this error:

> Cannot load Zend OPcache - it was already loaded
> Enabled maintenance mode
> Starting compilation
> Something went wrong while compiling generated code. See the error log for details.
> Command returned non-zero exit code:
> `/usr/local/php70/bin/php-cli -f /bin/magento setup:di:compile`

And when I check the `system.log` it shows this error:

> [2016-08-06 02:25:22] main.ERROR: /usr/local/php70/bin/php-cli -f /bin/magento setup:di:compile 2>&1
> Cannot load Zend OPcache - it was already loaded
> Compilation was started.
> %message% 0/7 [>---------------------------]   0% 1 sec 20.0 MiB%message% 0/7 [>---------------------------]   0% 1 sec 20.0 MiBProxies code generation... 0/7 [>---------------------------]   0% 1 sec 20.0 MiB
> Proxies code generation... 1/7 [====>-----------------------]  14% 1 sec 22.0 MiB
> Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 22.0 MiB
> Fatal error: Internal Zend error - Missing class information for P.j in /vendor/magento/module-catalog/Ui/Component/Listing/Attribute/AbstractRepository.php on line 8 [] []

**Is it related to memory limit?** My php info is this: http://www.merophoto.com.au/bcm/i.php

**And this screenshot is on developer mode:** https://www.dropbox.com/s/jq490kl10aobg10/Screenshot%202016-08-06%2013.08.08.png?dl=0

### UPDATE

Now, I have changed my php to 5.6.24 version and I can do upgrade, compile, index, cache clean etc without any error.

However, category is still same, form doesn't populates.

**Comment by miakusha** [comment] 2016-09-16 12:19
Hi, problem still reproducible???
Unfortunately, I could not reproduce the issue as you described it.
Try clear browser cache or use another browser if it doesn't help please provide error log

**Comment by andimov** [comment] 2016-10-10 14:52
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by andimov** 2016-10-10 14:52 UTC
Labels: bug report, Progress: needs update
