### ISSUE TITLE
2.4.7 GetOrders Response always returns the same shipping address for all orders in the list

### ISSUE THREAD

**Issue by erikvandermey** [magento/magento2#38808] opened 2024-06-06 15:09 UTC
### Preconditions and environment

- 2.4.7
- When more than one orders are returned in the Orders list, all orders will have the same Shipping Address.
- The Shipping Address from the first order in the list is used as the Shipping Address for all subsequent orders.

Example:
Order A with Shipping Address A
Order B with Shipping Address B

Query for both orders returns:
Order A with Shipping Address A
Order B with Shipping Address B (!)

**It appears the same thing that was reported in 2016 is happening again?**
https://github.com/magento/magento2/issues/4019

### Steps to reproduce

Query multiple orders and compare the Shipping Addresses in the Order Response list. 

### Expected result

The correct Shipping Address per Order should be returned. 

### Actual result

The Shipping Address from the first order in the list is used as the Shipping Address for all subsequent orders.

### Additional information

I noticed this started to happen after I updated to 2.4.7. Calling a Single Order returns the correct address, so that may be a workaround. 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2024-06-14 11:50
Hi @erikvandermey ,

Verified the issue on 2.4.7 and we are not able to reproduce this issue.

Steps to reproduce:-

1.Create two orders two shipping address
2.Fetch order details through API
3.Verify billing address

Please refer the attached screenshots and let us know if we missed anything.

Create orders

<img width="1434" alt="Screenshot 2024-06-13 at 8 39 24 PM" src="https://github.com/magento/magento2/assets/51681379/e26fad7c-0d93-4599-bcbe-a545913ffdde">

<img width="1440" alt="Screenshot 2024-06-13 at 8 39 42 PM" src="https://github.com/magento/magento2/assets/51681379/10ac9477-24ba-497e-8ae2-b1c154c0318b">

Fetched orders

<img width="1283" alt="Screenshot 2024-06-13 at 8 38 23 PM" src="https://github.com/magento/magento2/assets/51681379/673ecc77-5ac0-4691-ac5d-ccb7d4fb4964">

<img width="1274" alt="Screenshot 2024-06-13 at 8 38 44 PM" src="https://github.com/magento/magento2/assets/51681379/9d526226-a657-4fcd-a2ff-8304eb5fd07e">

<img width="1129" alt="Screenshot 2024-06-14 at 5 17 37 PM" src="https://github.com/magento/magento2/assets/51681379/0b3370c2-5b5e-44f6-8dff-04fd7d3637c9">

<img width="1147" alt="Screenshot 2024-06-14 at 5 18 18 PM" src="https://github.com/magento/magento2/assets/51681379/a6d34f29-bee0-49d9-b5b0-0b07b662a9b8">

**Comment by engcom-Delta** [comment] 2024-06-25 08:14
Hi @erikvandermey  ,

Awaiting your response on this issue to move further.

Thanks,

**Comment by engcom-Delta** [comment] 2024-06-25 10:19
Hi @erikvandermey  ,

We have verified this issue again with 2.4.7 and 2.4-develop and we are not able to reproduce this.

Actual Result:The correct Shipping Address per Order are returned.

Hence we are closing this.

Please refer the attached screenshots.

Order 13

<img width="1275" alt="Screenshot 2024-06-25 at 3 39 43 PM" src="https://github.com/magento/magento2/assets/51681379/fccc2bac-eb4e-4d2f-b41d-864b733ba24a">

<img width="1262" alt="Screenshot 2024-06-25 at 3 39 50 PM" src="https://github.com/magento/magento2/assets/51681379/cc5097c7-96aa-43b1-9198-4032afb19610">

Order 14

<img width="1273" alt="Screenshot 2024-06-25 at 3 40 46 PM" src="https://github.com/magento/magento2/assets/51681379/ae4e2b47-fa72-4a35-a731-de2d8b8578be">

<img width="1267" alt="Screenshot 2024-06-25 at 3 41 00 PM" src="https://github.com/magento/magento2/assets/51681379/e4761d59-2405-4a9d-b62e-23ec3b1e21ff">

Order 15

<img width="1263" alt="Screenshot 2024-06-25 at 3 42 22 PM" src="https://github.com/magento/magento2/assets/51681379/017b9a6a-5358-44c8-998f-23b5ffadc664">

<img width="1261" alt="Screenshot 2024-06-25 at 3 42 31 PM" src="https://github.com/magento/magento2/assets/51681379/1bc5ad34-e14d-45de-9aa6-d13bb2193870">

**Closed as completed by engcom-Delta** 2024-06-25 10:19 UTC
Labels: Issue: needs update, Reported on 2.4.7
