### ISSUE TITLE
Web install - step 4 Customize Your Store - Validating modules constraints loading does not show

### ISSUE THREAD

**Issue by rodrigowebjump** [magento/magento2#27587] opened 2020-04-04 16:48 UTC
### Preconditions (*)
1. Install Magento using browser

### Steps to reproduce (*)
1. Install Magento using web installation
2. On step 4 when click on next step, there is a long time loading because it is checking the modules constraints

### Expected result (*)

1. 
 The checking indicator must always appear
![image](https://user-images.githubusercontent.com/635466/78456533-a1bfa300-767a-11ea-8ed2-356d4f9d8ca3.png)
]

### Actual result (*)
1. The checking indicator just show when click on advanced modules configuration
 ![image](https://user-images.githubusercontent.com/635466/78456502-763cb880-767a-11ea-96a3-331b6784e776.png)

**Comment by magento-engcom-team** [comment] 2020-04-07 09:16
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33134` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Echo** [comment] 2020-06-25 14:15
I'm closing this Issue because the decision already exists - https://github.com/magento/magento2/search?q=MC-33843&type=Commits

**Closed as completed by engcom-Echo** 2020-06-25 14:15 UTC
Labels: Issue: Ready for Work, Component: Setup, Issue: Confirmed, Issue: Format is valid, Reproduced on 2.4.x, Event: Global-Contribution-Day, Severity: S4, Priority: P4, Triage: Done
