### ISSUE TITLE
Search query throwing error in all case.

### ISSUE THREAD

**Issue by deepaksnair** [magento/magento2#26520] opened 2020-01-24 07:20 UTC
### Preconditions (*)

1. Magento 2.4 Develop

### Steps to reproduce (*)

1. Search anything (greater than 3 letter), throws exception.

### Expected result (*)

1. Should search and show the results.

### Actual result (*)

1. Throwing exception and creating log

I have checked this on local fresh environment also on magento 2.4 developer instance provided by magento.

### Solution
The issue must be solved by adding full reindex execution at the very end of the Magento installation process.

![Screenshot from 2020-01-24 12-57-22](https://user-images.githubusercontent.com/36736404/73051974-fdff8d00-3ea9-11ea-8701-6579eb28f70f.png)

**Comment by deepaksnair** [comment] 2020-01-24 07:24
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-01-24 07:24
Hi @deepaksnair. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-24 07:25
Hi @deepaksnair, here is your [Magento instance](https://i-26520-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26520-2-4-develop.instances.magento-community.engineering/admin_eaeb](https://i-26520-2-4-develop.instances.magento-community.engineering/admin_eaeb)
Login: `00352191` Password: `9645a8e7a959`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2020-01-24 10:31
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30767` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ajithkumar-maragathavel** [comment] 2020-01-25 19:56
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-01-25 19:56
Hi @ajithkumar-maragathavel. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-25 19:57
Hi @ajithkumar-maragathavel, here is your [Magento instance](https://i-26520-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26520-2-4-develop.instances.magento-community.engineering/admin_53ef](https://i-26520-2-4-develop.instances.magento-community.engineering/admin_53ef)
Login: `0881875e` Password: `79b45c776599`
Instance will be terminated in up to 3 hours.

**Comment by ramesh-durairajaram** [comment] 2020-01-28 08:05
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-01-28 08:05
Hi @ramesh-durairajaram. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-28 08:05
Hi @ramesh-durairajaram, here is your [Magento instance](https://i-26520-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26520-2-4-develop.instances.magento-community.engineering/admin_7919](https://i-26520-2-4-develop.instances.magento-community.engineering/admin_7919)
Login: `3c73da5a` Password: `fcdb398c71d1`
Instance will be terminated in up to 3 hours.

**Comment by Usik2203** [comment] 2020-01-30 10:23
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-01-30 10:23
Hi @Usik2203. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-30 10:23
Hi @Usik2203, here is your [Magento instance](https://i-26520-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26520-2-4-develop.instances.magento-community.engineering/admin_d597](https://i-26520-2-4-develop.instances.magento-community.engineering/admin_d597)
Login: `448fdece` Password: `c12d5625fa00`
Instance will be terminated in up to 3 hours.

**Comment by ramesh-durairajaram** [comment] 2020-02-04 12:15
Hi @akaplya, 
**Issue**: `catalogsearch_fulltext_scope1` table is not found in database after a fresh installation of 2.4-develop branch. Hence search query not able to be completed.

**Cause**: This table was created when re-indexing is triggered during installation. Your commit c4c36dcc48c4e74a70aaf83cee760cc5ffa34d29 to `Removed force reindex from the database patch` is preventing the re-indexing from triggering.

Kindly advice how to proceed.

**Comment by novikor** [comment] 2020-02-12 20:37
@ramesh-durairajaram, please [check my reply to your PR ](https://github.com/magento/magento2/pull/26803#issuecomment-585403680). Thank you for your collaboration.

**Comment by novikor** [comment] 2020-02-16 17:30
As discussed in #appdesign Slack channel:
The issue must be solved by adding full reindex execution at the very end of the Magento installation process.

**Comment by magento-engcom-team** [comment] 2020-04-08 14:10
Hi @deepaksnair, @novikor, @ramesh-durairajaram. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-30767` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Closed as completed by magento-engcom-team** 2020-04-08 14:10 UTC
Labels: Issue: Ready for Work, Area: Frontend, Issue: Confirmed, Issue:  Cannot Reproduce, Issue: Format is valid, Award: bug fix, Component: CatalogSearch, Progress: done, Reported on 2.4.0
