### ISSUE TITLE
failed to add product variation

### ISSUE THREAD

**Issue by gasperz** [magento/magento2#1434] opened 2015-07-02 07:04 UTC
With beta15 and demo store.
I tried to remove one product variation from product. So from "Erika Running Short" I removed "Erika Running Short-32-Red" (removed checker), saved. All ok. But then I tried to add this same product variation. So I just checked it again and pressed Save. I got error message "URL key for specified store already exists."
Then I tried to choose product variation with click on broken link icon and then select it from list. (This procedure is also clunky since I have no clue what to do at first. When I select item nothing visual happens, and what really happens it is hidden behind the modal window. I suggest that when selecting variation, modal window should close and fill list with selected item and automatically add image from selected item to small image). After Save I receive "Notice: Undefined index: configurable_attribute in /vagrant/data/magento2/app/code/Magento/ConfigurableProduct/Model/Product/Validator/Plugin.php on line 111"

**Comment by kokoc** [comment] 2015-07-02 10:15
@gasperz thank you for reporting the issue. Internal reference: MAGETWO-39605

**Comment by vpelipenko** [comment] 2015-07-16 11:11
@gasperz, it was fixed in 1.0.0-beta. Please, check the issue on this version.

**Comment by gasperz** [comment] 2015-07-17 11:12
I have tried. And this issue is not relevant anymore since the whole process for editing configurable products is so different. I would need to investigate a bit more. If anything new will appear I will open new issue. But one can be closed.

**Comment by vpelipenko** [comment] 2015-07-17 11:38
@gasperz, ok, thank you.

**Closed by vpelipenko** 2015-07-17 11:38 UTC
Labels: acknowledged, bug, MX, needs update

**Comment by minikist** [comment] 2015-10-31 00:58
Hello, 
I run 1.0.0-beta, i got this same issue when i try to import a lot of data.

Does someone has a fix?? 
Thanks 

BTW great work guys, i like the magento 2 already!!

**Comment by raybogman** [comment] 2016-01-15 21:33
The issue is also in Magento 2 stable when saving conf product after selecting the attrib type

Notice: Undefined index: configurable_attribute in /var/www/ce/vendor/magento/module-configurable-product/Model/Product/Validator/Plugin.php on line 115
