### ISSUE TITLE
B2B Magento_Company Exception "You are not authorized to access this resource."

### ISSUE THREAD

**Issue by iwanzijderveld** [magento/magento2#38429] opened 2024-02-07 13:44 UTC
### Preconditions and environment

- Magento enterprise 2.4.5-p4
- extension-b2b: 1.3.4-p4

### Steps to reproduce

1. Create a company with a customer
2. Set option 'Enable Purchase Orders' value to 'Yes'
3. Login as customer
4. Add product and checkout the order

### Expected result

Order is placed successfully

### Actual result

401 result on request /rest/.../V1/carts/mine/payment-information
Which then redirects to login page which redirects to account page.

### Additional information

It found that the result is trigger by the following plugin on  `vendor/magento/module-company/Plugin/AsyncOrder/Model/PermissionCheckPlugin.php`
```
$customerId = (int)$this->userContext->getCustomer()->getId() ?: 0;
        if ($customerId) {
            $company = $this->companyManagement->getByCustomerId($customerId);
            if ($company !== null && $company->getExtensionAttributes()->getIsPurchaseOrderEnabled()) {
                throw new AuthorizationException(__(
                    'You are not authorized to access this resource.'
                ));
            }
        }
```

It seems to me that the if statement should only throw the exception when purchaseOrder is not authorized?
```
$customerId = (int)$this->userContext->getCustomer()->getId() ?: 0;
        if ($customerId) {
            $company = $this->companyManagement->getByCustomerId($customerId);
            if ($company !== null && !$company->getExtensionAttributes()->getIsPurchaseOrderEnabled()) {
                throw new AuthorizationException(__(
                    'You are not authorized to access this resource.'
                ));
            }
        }
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-02-08 08:43
Hi @iwanzijderveld,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance with EE edition and the issue is not reproducible.

**Steps to reproduce**

- Create a company with a customer
- Set option 'Enable Purchase Orders' value to 'Yes'
- Login as customer
- Add product and checkout the order


We are able to place the order successfully.

Kindly recheck the issue in Latest Magento 2.4-develop instance with EE edition and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by iwanzijderveld** [comment] 2024-02-12 13:24
Hi @engcom-Bravo,

I assume the magento/extension-b2b has been installed.

I can still reproduce this issue with the steps below on a fresh installation.

**Steps to reproduce**
- Create a company under menu item customer -> companies.
- Fill in required values
- Set option 'Enable Purchase Orders' value to 'Yes'
- Login as customer (When creating a company a customer should be created)
- Add product and checkout the order

Hopefully the following video underneath shows makes it all clear.
[Screencast from 12-02-24 14:15:35.webm](https://github.com/magento/magento2/assets/9657743/0da4b1f3-2c18-40c9-bc22-5f4e81021f0c)
As you can see in the video after clicking 'Place Order' I go to the account page with no order being placed.

**Comment by engcom-Dash** [comment] 2024-02-16 13:26
Hi @iwanzijderveld 

Thank you for reporting and collaboration.

Verified the issue on magneto 2.4 dev b2b instance but the issue is not reproducible.

We are able to place the order successfully.

Please refer the screen recording below.


https://github.com/magento/magento2/assets/60198592/ed5b6fe4-7141-4a6f-af65-4c2f4d647d12


Please check let us know if we missed anything.

**Comment by iwanzijderveld** [comment] 2024-02-16 16:20
Hi @engcom-Dash,

Thank you for attaching the screen recording.
It appears my instructions were unclear.

So additionally I have to mention that the Setting I'm referring to is not in the shop configuration page.
As the description under the setting in your video mentions:

> Purchase Order are enabled at the Company level. Turn on 'Enable Purchase Orders' at Customer -> Companies -> Company Name -> Edit -> Advanced  Settings for each company that supports Purchase Orders.

So here are the updated steps to reproduce, hope the issue can now be confirmed and solved :smiley: 

**Steps to reproduce**

1. Create a company under menu item customer -> companies.
2. Fill in required values
3. Set option 'Enable Purchase Orders' value to 'Yes' for the company
4. Login as customer (When creating a company a customer should be created)
5. Add product and checkout the order

**Comment by portchris** [comment] 2024-02-20 14:44
Got a patch if anyone suffers from this like I did:
```patch
--- a/vendor/magento/module-company/Plugin/AsyncOrder/Model/PermissionCheckPlugin.php
+++ b/vendor/magento/module-company/Plugin/AsyncOrder/Model/PermissionCheckPlugin.php
@@ -66,12 +66,13 @@
         $customerId = (int)$this->userContext->getCustomer()->getId() ?: 0;
         if ($customerId) {
             $company = $this->companyManagement->getByCustomerId($customerId);
-            if ($company !== null && $company->getExtensionAttributes()->getIsPurchaseOrderEnabled()) {
+            if ($company !== null && !$company->getExtensionAttributes()->getIsPurchaseOrderEnabled()) {
                 throw new AuthorizationException(__(
                     'You are not authorized to access this resource.'
                 ));
             }
         }
+
         return null;
     }
 }

```

**Comment by iwanzijderveld** [comment] 2024-02-27 14:54
Is there any update on this ticket yet?

**Comment by engcom-Dash** [comment] 2024-02-28 13:40
Hi @iwanzijderveld 

Thanks for reporting and collaboration.

Verified the issue again in magento 2.4 dev b2b instance but the issue is not reproducable.

Please refer the attached screenrecording

Steps to reproduce:

1.Create a company with a customer
2.Set option 'Enable Purchase Orders' value to 'Yes'
3.Login as customer
4.Add product and checkout the order

We are able to place an order successfully.

Please verify the issue in latest magento instance and let us know if you are still facing the issue.


https://github.com/magento/magento2/assets/60198592/9ff82c5a-28dc-4285-a579-4b70ba41c372

**Comment by engcom-Dash** [comment] 2024-03-05 11:36
Hi @iwanzijderveld 

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Dash** 2024-03-05 11:36 UTC
Labels: Issue: needs update, Reported on 2.4.5-p4

**Comment by engcom-Dash** [comment] 2024-03-13 11:58
Hi @iwanzijderveld 

Verified the issue on magneto 2.4 b2b instance.

When we disable 'enable purchase orders' option the setting stores configuration -> general -> b2b features -> order approval configuration -> Enable purchase orders and enable 'enable purchase orders' option for a specific company we are still able to place the order successfully. 

Please refer the attached screenshots.
<img width="1440" alt="Screenshot 2024-03-13 at 3 03 56 PM" src="https://github.com/magento/magento2/assets/60198592/057d3431-3782-4630-b532-388f24a21a3e">
