### ISSUE TITLE
Error in checkout - Billing address not updated when shipping address changed

### ISSUE THREAD

**Issue by lilmuckers** [magento/magento2#3374] opened 2016-02-11 15:17 UTC
## Symptom
- Customer enters checkout, 
- enters address, 
- goes to payment step, 
- chooses payment, sets "use same address as billing"
- payment fails due to invalid field or some address validation issue on payment side
- Customer clicks on the previous step to correct shipping address
- when customer clicks through and maintains "same address for billing" same error presents

Upon investigation it was found that the billing address within the `quote_address` table still has the originally entered address value with the problem data.

**Comment by ishakhsuvarov** [comment] 2016-02-23 15:54
@lilmuckers Thank you for reporting this issue.
Could you please provide details on the Magento version you are using and Payment methods you tested?

**Comment by lilmuckers** [comment] 2016-02-23 16:04
I am using 2.0.2 CE - and i tried it with Ebizmarts_SagePaySuite  and with the standard `checkmo` 

### Edit with more detail

For the `checkmo` one  - i put a test into the code to throw a validation exception within the class. I did this in a number of places _after_ the billing address was saved to the quote (just to simulate a multitude of errors that might happen from validation to payment to whatever). And every time - it wasn't updating the billing address implicitly, only if i unchecked "same as shipping" and then modified the address directly.

**Comment by ishakhsuvarov** [comment] 2016-02-25 08:20
@lilmuckers We have tried, but could not reproduce the issue you described. Is it possible to achieve same result using any of the stock online payment methods?

**Comment by ishakhsuvarov** [comment] 2016-03-16 15:46
@lilmuckers Closing this ticket for now. Please reopen if the issue persists.

**Closed as completed by ishakhsuvarov** 2016-03-16 15:46 UTC
Labels: Progress: needs update, Issue: Format is not valid

**Comment by janiscaunecm** [comment] 2016-04-28 10:41
Hello,

I can replicate this issue on 2.0.4 CE and using stock payment methods. Steps to reproduce:
- put product in cart, proceed to checkout, enter shipping address, select shipping method, proceed to payment step: http://prnt.sc/axuakb
- go back to shipping step, introduce some changes: http://prnt.sc/axuazx
- go back to payment step (you may even change shipping method while at it)
- observe that billing address is not updated: http://prnt.sc/axub7b
- uncheck and check the checkbox and observe changes: http://prnt.sc/axubms

Hope this helps!

@lilmuckers I believe only you can reopen this ticket.

**Comment by SM528** [comment] 2016-08-18 08:30
I am experiencing the same issue on 2.0.4. 

Is this going to fix anytime soon?

**Comment by webdesk** [comment] 2017-01-02 10:47
I have the same issue. 

Here is the steps to produce the issue. 

![address_not_proper_after_reload_page](https://cloud.githubusercontent.com/assets/8352525/21587845/c3057a66-d106-11e6-9d21-080707f5ef80.png)

I have filled the shipping address details and goes to the payment block and now i have reloaded the page and address will not be proper filled. 

Thanks

**Comment by dev-Dhaval** [comment] 2017-10-12 11:25
@webdesk Guys, any solutions ?

**Comment by miqbal699** [comment] 2017-11-14 12:46
@magento-engcom-team Any update on this?

**Comment by wwwebgainss** [comment] 2018-10-22 12:29
any updates ? Issue still exists with the latest magento2 version..

**Comment by wendydek** [comment] 2018-11-05 08:15
You could fix this with a mixin that overrides the setShippingInformation function in file Magento_Checkout/web/js/view/shipping.js. Code:

```
define([
    'jquery',
    'underscore',
    'Magento_Ui/js/form/form',
    'ko',
    'Magento_Customer/js/model/customer',
    'Magento_Customer/js/model/address-list',
    'Magento_Checkout/js/model/address-converter',
    'Magento_Checkout/js/model/quote',
    'Magento_Checkout/js/action/create-shipping-address',
    'Magento_Checkout/js/action/select-shipping-address',
    'Magento_Checkout/js/model/shipping-rates-validator',
    'Magento_Checkout/js/model/shipping-address/form-popup-state',
    'Magento_Checkout/js/model/shipping-service',
    'Magento_Checkout/js/action/select-shipping-method',
    'Magento_Checkout/js/model/shipping-rate-registry',
    'Magento_Checkout/js/action/set-shipping-information',
    'Magento_Checkout/js/model/step-navigator',
    'Magento_Ui/js/modal/modal',
    'Magento_Checkout/js/model/checkout-data-resolver',
    'Magento_Checkout/js/checkout-data',
    'uiRegistry',
    'mage/translate',
    'Magento_Checkout/js/action/select-billing-address',
    'Magento_Checkout/js/model/shipping-rate-service'
], function (
    $,
    _,
    Component,
    ko,
    customer,
    addressList,
    addressConverter,
    quote,
    createShippingAddress,
    selectShippingAddress,
    shippingRatesValidator,
    formPopUpState,
    shippingService,
    selectShippingMethodAction,
    rateRegistry,
    setShippingInformationAction,
    stepNavigator,
    modal,
    checkoutDataResolver,
    checkoutData,
    registry,
    $t,
    selectBillingAddress
) {
    'use strict';

    return function (OriginalComponent) {
        return OriginalComponent.extend({
            setShippingInformation: function () {
                if (this.validateShippingInformation()) {
                   selectBillingAddress(quote.shippingAddress());

                    setShippingInformationAction().done(
                        function () {
                            stepNavigator.next();
                        }
                    );
                }
            }
        });
    }
});
```

Hope this helps anyone who needs a quick fix. (@lilmuckers, @webdesk )

**Comment by wwwebgainss** [comment] 2019-02-13 11:14
> You could fix this with a mixin that overrides the setShippingInformation function in file Magento_Checkout/web/js/view/shipping.js. Code:
> 
> ```
> define([
>     'jquery',
>     'underscore',
>     'Magento_Ui/js/form/form',
>     'ko',
>     'Magento_Customer/js/model/customer',
>     'Magento_Customer/js/model/address-list',
>     'Magento_Checkout/js/model/address-converter',
>     'Magento_Checkout/js/model/quote',
>     'Magento_Checkout/js/action/create-shipping-address',
>     'Magento_Checkout/js/action/select-shipping-address',
>     'Magento_Checkout/js/model/shipping-rates-validator',
>     'Magento_Checkout/js/model/shipping-address/form-popup-state',
>     'Magento_Checkout/js/model/shipping-service',
>     'Magento_Checkout/js/action/select-shipping-method',
>     'Magento_Checkout/js/model/shipping-rate-registry',
>     'Magento_Checkout/js/action/set-shipping-information',
>     'Magento_Checkout/js/model/step-navigator',
>     'Magento_Ui/js/modal/modal',
>     'Magento_Checkout/js/model/checkout-data-resolver',
>     'Magento_Checkout/js/checkout-data',
>     'uiRegistry',
>     'mage/translate',
>     'Magento_Checkout/js/action/select-billing-address',
>     'Magento_Checkout/js/model/shipping-rate-service'
> ], function (
>     $,
>     _,
>     Component,
>     ko,
>     customer,
>     addressList,
>     addressConverter,
>     quote,
>     createShippingAddress,
>     selectShippingAddress,
>     shippingRatesValidator,
>     formPopUpState,
>     shippingService,
>     selectShippingMethodAction,
>     rateRegistry,
>     setShippingInformationAction,
>     stepNavigator,
>     modal,
>     checkoutDataResolver,
>     checkoutData,
>     registry,
>     $t,
>     selectBillingAddress
> ) {
>     'use strict';
> 
>     return function (OriginalComponent) {
>         return OriginalComponent.extend({
>             setShippingInformation: function () {
>                 if (this.validateShippingInformation()) {
>                    selectBillingAddress(quote.shippingAddress());
> 
>                     setShippingInformationAction().done(
>                         function () {
>                             stepNavigator.next();
>                         }
>                     );
>                 }
>             }
>         });
>     }
> });
> ```
> Hope this helps anyone who needs a quick fix. (@lilmuckers, @webdesk )

this is not working for me. anyone got a solution ?
