### ISSUE TITLE
[GraphQL] Cart query: "stock_status" for bundle product with dynamic sku does not return "in_stock" for in stock products

### ISSUE THREAD

**Issue by gnumus** [magento/magento2#39249] opened 2024-10-09 18:29 UTC
### Preconditions and environment

- Magento 2.4.7-p2 (UPD: can be reproduced in Magento 2.4.7-p3)

Have a bundle product available in stock with the following configuration

- Dynamic SKU - Yes
- Dynamic Price - Yes
- Stock status - In stock
- Ship items - Separately
- Bundle has 2+ in stock items included into it

### Steps to reproduce

Using graphQL:

- Add the bundle to the cart
- Retrieve the cart information including cart->item->product->stock_status:
`
query {
  
    cart (cart_id: "YYYyyyYYYyyy") {
      items {
        product {
          name
          stock_status
        }
      }
    }
  }
`

### Expected result

"stock_status" returns "in_stock" since the bundle and all products included are in stock

### Actual result

"stock_status" returns "out_of_stock" all the time

### Additional information

This used to work in Magento 2.4.6-p6

Attachments represent different behavior in M2.4.6 and M2.4.7 using the same DB, same product
![BaFTneknI9](https://github.com/user-attachments/assets/ca997f09-9f7f-4c09-bce5-6253031029ee)
![lfjJEPeBOh](https://github.com/user-attachments/assets/4d12de34-720a-474a-bda8-e07e35689048)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-10-10 09:03
Hi @gnumus,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


<img width="1407" alt="Screenshot 2024-10-10 at 10 56 03" src="https://github.com/user-attachments/assets/7c8a8592-c0b1-4c36-ad77-dd282b25cd0b">



Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-10-22 03:13
Hi @gnumus,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Bravo** 2024-10-22 03:13 UTC
Labels: Issue: needs update, Reported on 2.4.7-p2
