### ISSUE TITLE
Magento\TestFramework\Annotation\ConfigFixture Error

### ISSUE THREAD

**Issue by sergelavrentev** [magento/magento2#39182] opened 2024-09-18 13:23 UTC
### Preconditions and environment

- Magento version 2.4.6-p3

### Steps to reproduce

1. create core_config _data with value = 0. 
2.  add magentoConfigFixture to integration test @magentoConfigFixture example/path/test 1 

### Expected result

test passes

### Actual result

Magento\TestFramework\App\ApiMutableScopeConfig::persistConfig(): Argument #2 ($value) must be of type string, null given, called in /repo/magento/dev/tests/api-functional/framework/Magento/TestFramework/App/ApiMutableScopeConfig.php on line 79

### Additional information

After getting value from db, '0' converts to NULL here
magento/dev/tests/api-functional/framework/Magento/TestFramework/Annotation/ApiConfigFixture.php:158

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2024-10-07 10:26
Hello @SergeLavrentyev,

Thanks for the report and collaboration!

We have tried to reproduce the issue in the latest development branch i.e. 2.4-develop, but for us, the issue is not reproducible.

As per the main description, first, we tried to create a custom integration test with `@magentoConfigFixture example/path/test 1`, but the issue is not reproducible for us. Please refer to the below screenshot for reference:

![image](https://github.com/user-attachments/assets/2a4b585d-a58b-4f3c-b565-3791b3494790)

But then we checked the error you mentioned in the main description, and according to the error, it seems you are facing an issue is in api- functional test. So then we tried to reproduce it api-functional test following the below steps:

1. Edit file https://github.com/magento/magento2/blob/a4cf5e62468770fdb9f7b48938f6644ae354a51b/dev/tests/api-functional/testsuite/Magento/Catalog/Api/AttributeSetManagementTest.php#L35
2. Add `@magentoConfigFixture example/path/test 1` for `testCreate` method
3. Ran the test via the below command:
`../../../vendor/bin/phpunit -c ../../../dev/tests/api-functional/phpunit_rest.xml --filter 'testCreate' ../../../dev/tests/api-functional/testsuite/Magento/Catalog/Api/AttributeSetManagementTest.php`

The test was completed successfully. Please refer to the below screenshot:
![image](https://github.com/user-attachments/assets/f11c45b6-4196-4729-b65e-4da9069b03e4)

Please let us know if we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2024-10-21 10:38
Dear @SergeLavrentyev,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we're assuming it's been resolved and will be closing it. Feel free to open a new ticket or reopen this one if you require further assistance.

Regards

**Closed as completed by engcom-Hotel** 2024-10-21 10:38 UTC
Labels: Component: TestFramework, Triage: Dev.Experience, Issue: needs update, Reported on 2.4.x, Area: Framework
