### ISSUE TITLE
Fatal error: Call to a member function format() on null in /var/www/magento2/lib/internal/Magento/Framework/Stdlib/DateTime/Timezone.php on line 259

### ISSUE THREAD

**Issue by ffrodoe** [magento/magento2#1544] opened 2015-07-23 08:33 UTC
Magento2 1.0.0-beta. 
1. Create a customer on frontend. 
2. Go to admin and try to open this new customer for editing. 
Fatal error: Call to a member function format() on null in /var/www/magento2/lib/internal/Magento/Framework/Stdlib/DateTime/Timezone.php on line 259

![screen_000036](https://cloud.githubusercontent.com/assets/12183505/8846250/172fdd22-312e-11e5-8891-2b629c01dff2.png)

**Comment by vpelipenko** [comment] 2015-07-23 16:25
Duplicate of https://github.com/magento/magento2/issues/1427.

**Comment by snohe** [comment] 2015-08-03 16:31
@ffrodoe, since this is a duplicate of #1427, we will go ahead and close this issue.  Please refer to #1427 for any updates.

**Closed by snohe** 2015-08-03 16:31 UTC
Labels: bug, PS
