### ISSUE TITLE
Magento ver. 2.1.8 New Product with Custom attribute set not working

### ISSUE THREAD

**Issue by gilbertsohal** [magento/magento2#10565] opened 2017-08-17 10:39 UTC
### Preconditions

1. Magento ver. 2.1.8
2. PHP version:  7.0

### Steps to reproduce

1. Create new Attribute Set (Stores > Attributes > Attribute Set) Suits
2. Create new Configurable Product (Products > Inventory > Catalog > Add Products > Configurable Product)
3. Select Custom Attribute Set (Suits)
    ScreenShot
    http://prntscr.com/g9kij6

### Expected result

1. Create New Configurable Product with Custom Attribute set (Suits)

### Actual result

1. After Select Custom Attribute Set (Suits) Page stuck on loading.
Screenshot
http://prntscr.com/g9kkat

Please help me!

**Comment by thlassche** [comment] 2017-08-17 13:47
Also got this. Tracked it back to this commit:

https://github.com/magento/magento2/commit/85db4c87491d43fa4d4de59c6fe3d6cc1486835b#diff-620105b6e833499c14f4eb74ce8a4532

Related to this issue: https://github.com/magento/magento2/issues/7687

**Comment by thlassche** [comment] 2017-08-17 13:52
Temporary fix is to change line 52 of `/vendor/magento/module-ui/view/base/web/js/form/element/multiselect.js` to:

`if (typeof data == "undefined" || !data.length) {`

**Comment by thlassche** [comment] 2017-08-17 13:55
I created a pull request for hits: https://github.com/magento/magento2/pull/10575

**Comment by gilbertsohal** [comment] 2017-08-18 05:30
### Thanks very much for your suggestion i try your below code change.
===============================================
Temporary fix is to change line 52 of /vendor/magento/module-ui/view/base/web/js/form/element/multiselect.js to:

if (typeof data == "undefined" || !data.length) {
===============================================

### STILL NOT WORKING AT MY END

**Comment by thlassche** [comment] 2017-08-18 09:12
@gilbertsohal You should also clear & redeploy static content

**Comment by gilbertsohal** [comment] 2017-08-18 11:58
@thlassche 
I have try everything still no luck

Screenshot
http://prntscr.com/ga1iaj

**Comment by thlassche** [comment] 2017-08-18 12:04
Did you als clear `var/view_preprocessed/*` and `pub/static/*`, after that regenerate the static content.

**Comment by gilbertsohal** [comment] 2017-08-18 13:18
@thlassche 

I have clear the var/view_preprocessed/* and pub/static/*, after that regenerate the static content.

Nothing Happens Still not working, This time Attribute set disappear

Screenshot
http://prntscr.com/ga2k18

**Comment by magento-team** [comment] 2017-08-19 20:42
Internal ticket to track issue progress: MAGETWO-71670

**Comment by orlangur** [comment] 2017-08-20 07:06
@gilbertsohal try to see contents of `/view/base/web/js/form/element/multiselect.js` file in Dev Tools (Sorces tab, press Ctrl/Cmd+P and search for `multiselect.js` to see actual source).

**Comment by gilbertsohal** [comment] 2017-08-23 04:53
@orlangur 
Thanks very much for your quick reply. I just want to confirm you All this happens when i upgrade 2.1.7 to 2.1.8 through Composer.

I installed fresh copy for 2.1.8 and everything working fine now.

**Comment by magento-engcom-team** [comment] 2017-09-20 23:04
@gilbertsohal, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by magento-engcom-team** [comment] 2017-09-27 22:00
@gilbertsohal, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by okorshenko** [comment] 2017-10-04 16:15
Hi @gilbertsohal can we close this issue?

**Comment by gilbertsohal** [comment] 2017-10-04 21:48
@okobchenko Yes, Its working fine on my end.

**Closed as completed** 2017-10-04 22:10 UTC
Labels: Issue: Ready for Work, Progress: needs update, Issue: Clear Description, Issue: Confirmed, Fixed in 2.1.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by magento-engcom-team** [comment] 2018-02-21 00:20
Hi @gilbertsohal. Thank you for your report. 
The issue has been fixed in magento/magento2#13549 by @hostep in 2.1-develop branch
Related commit(s):
 - [d95e15c3f12edb77c39437f84187844ffa6b0fd8](https://github.com/magento/magento2/commit/d95e15c3f12edb77c39437f84187844ffa6b0fd8)

The fix will be available with the upcoming 2.1.13 release.

**Comment by lakshmi13patil** [comment] 2019-05-29 05:06
Hello, How do i make the custom product  attribute created at back end , visible/available on frontend for vendor while listing his product.
