### ISSUE TITLE
REST API unable to make requests with slash (/) in SKU 

### ISSUE THREAD

**Issue by xfolder** [magento/magento2#21179] opened 2019-02-13 08:40 UTC
### Preconditions
1. Tested in CE 2.3

### Steps to reproduce
Fresh install
Create product (of any type) with SKU containing /, e.g. "0RJ9548SN-212/W0-54"

searching for the product with
GET : /rest/v1/products?searchCriteria[filter_groups][0][filters][0][field]=sku&searchCriteria[filter_groups][0][filters][0][value]=0RJ9548SN-212%2FW0-54
returns results as expected

but when getting the stockItems with the following
GET : /rest/V1/stockItems/0RJ9548SN-212%2FW0-54
result 404 status - BUT the actual data is returned?

when trying to update the stockItem
PUT : /rest/V1/products/0RJ9548SN-212%2FW0-54/stockItems/100
result : 404 status - message=Request does not match any route.

### Expected result
expect
/rest/V1/stockItems/[sku containing / to also work]
/rest/V1/products/[sku containing / to also work]/stockItems/[stockItemID]

both to work in the same manner as sku without '/'

### Actual result
GET : /rest/V1/stockItems/0RJ9548SN-212%2FW0-54
result 404 status - BUT the actual data is returned?

PUT : /rest/V1/products/0RJ9548SN-212%2FW0-54/stockItems/100
result : 404 status - message=Request does not match any route.

same issue -> https://github.com/magento/magento2/issues/13343

**Comment by magento-engcom-team** [comment] 2019-02-13 08:40
Hi @xfolder. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@xfolder do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-02-13 08:43
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-02-13 12:25
Hi @ravi-chandra3197. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-02-18 08:25
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98306`, `MAGETWO-98307` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by irajneeshgupta** [comment] 2019-05-04 04:56
I am working on this at #dmcdindia1

**Comment by irajneeshgupta** [comment] 2019-05-04 06:42
Server issue , allow **AllowEncodedSlashes** in apache conf.

**Comment by sdzhepa** [comment] 2019-05-22 15:00
Hello @magento/quality-maintainers team,

May I ask you to review this Issue and Confirm is it still reproducible on the latest vanilla Magento?
According to the last comments, there are concerns is Issue valid and related to Magento or not.


Thank you in advance!

**Comment by magento-engcom-team** [comment] 2019-07-19 12:32
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18320` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by henryk-zaborowski** [comment] 2019-09-15 11:08
#mm19pl

**Comment by magento-engcom-team** [comment] 2019-09-15 11:08
@henryk-zaborowski thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by henryk-zaborowski** [comment] 2019-09-15 15:32
This is not a Magento 2 bug, but an apache2 one.
By default apache should not allow encoded slashes in url without use of "AllowEncodedSlashes", (for security reasons) but sometimes it does.
If You really need to use "/" in SKUs then configure apache with "AllowEncodedSlashes On" directive. (not recommended)

Instead of looking for workaround for this case, Magento should not allow for usage of slash (%2F) and backslash (%5C) in SKU.

**Closed as completed by henryk-zaborowski** 2019-09-15 15:32 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Api, Event: mm19pl

**Comment by ihor-sviziev** [comment] 2019-12-09 16:56
@henryk-zaborowski 
> If You really need to use "/" in SKUs then configure apache with "AllowEncodedSlashes On" directive. (not recommended)

I would say it's better to use
```
AllowEncodedSlashes NoDecode
```

> With the default value, Off, such URLs are refused with a 404 (Not found) error.
With the value On, such URLs are accepted, and encoded slashes are decoded like all other encoded characters.
With the value NoDecode, such URLs are accepted, _but encoded slashes are not decoded but left in their encoded state_.

More details: https://httpd.apache.org/docs/2.4/mod/core.html#allowencodedslashes
