### ISSUE TITLE
Square Payments can't translate Card details

### ISSUE THREAD

**Issue by cse00241** [magento/magento2#33496] opened 2021-07-15 19:50 UTC
Magneto 2.4.1 With Latest Version Of Square Payment, Credit card come from I-frame and Can't Translate the Card Number, CVV, and others info which come from the I-frame.

I want to translate Square Payment - Credit card data. But problem is latest magento 2.4.1 wit latest Square extension has create card with Iframe so It can't be translate with Jquery, JS, CSS anything can't work on Iframe on this Square Payment.
I also check the square payment module, connection module, square module. But changed follow there instruction which is not magento related its related to API. But nothing works.

Examples::
![kfa7z](https://user-images.githubusercontent.com/22810824/125848457-7da5a65e-e976-4ed4-9d4e-0c50050906a2.png)
The Card number is in place holder, I want to translate it change it. Before old square it wasn't iframe so change easily by some how. But now its totally change so I can't translate it.

Solution may be::
Some where JS need to edit to create card with place holder request. Bellow method I tried.

I added latest 2021 square extension on Magneto 2. But problem is can't translate Card Number CVV etc. Also can't delete the ZIP here also. /vendor/square/module-squareup-omni/view/frontend/web/js/view/payment/method-renderer/square.js There was:

```
window.squareupCardOnFileUsed = false;
console.log('Initing payment');
await this.squareCard();
await this.squareApplePay();
await this.squareGooglePay();
```

But I added there follow there extension try to add css, try to add place holder but it not work. The card come from Iframe::
`<iframe frameborder="0" height="50px" name="single-card-fdaa89d8-d4a9-f8a9-b53e-6d5931c1bed0" scrolling="no" src="https://web.squarecdn.com/0.0.25/single-card-element-iframe.html" width="100%" class="sq-card-component"></iframe>
`
I also use::

```
var tid2 = setInterval(function () {
if($('iframe.sq-card-component').length){
//console.log($('iframe.sq-card-component'));
//alert('test');
//$('input[placeholder="Card number"]').attr('placeholder','test');

var head = $("iframe.sq-card-component").contents().find("head");
var css = '<style>input{ visibility: hidden!important; }</style>';
$(head).append(css);

/*var tid3 = setInterval(function () {
//$('div#payment_form_squareup_payment form#nonce-form iframe').contents().find('input').hide();
}, 2000);*/

//alert('test');


clearInterval( tid2 );
}
}, 2000);
```

**Comment by mrtuvn** [comment] 2021-07-16 02:01
Seem limited with external module or module not quite well support for magento. Is this open source module on github ?
Not sure but imho this is problem from module issue not from magento issue

**Comment by engcom-Lima** [comment] 2021-08-24 11:52
Hi @cse00241,

I think the issue is related to Square Payments since translation code is inside their module files. You can check its compatibility with Magento2. 

If you find its Magento issue, please update on the below queries:
1. If the issue is reproducible on 2.4-develop instance. If yes, please provide ‘Steps to reproduce’ this issue.
2. If Square Payments module is Open Source ?

**Comment by engcom-Hotel** [comment] 2021-09-09 09:53
Dear @cse00241,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2021-09-09 09:53 UTC
Labels: Triage: Dev.Experience, Issue: needs update

**Comment by soundaregrove** [comment] 2023-04-10 10:17
Hi @cse00241  Can you send ur composer.json file .
