### ISSUE TITLE
Translation Not working in change password in frontend

### ISSUE THREAD

**Issue by KishorkumarKar** [magento/magento2#10957] opened 2017-09-19 07:34 UTC
Hi
### Preconditions
I have **Magento 2.1.7** with two store **English** **Spanish** After login in front end in Spanish Store. I Tried to change password the From validation text not translated correctly. I have tried to translate Inline it is not working. 

### Steps to reproduce
1. Login to front end .
2. Go to account information 
3. Change the store (language in spanish)
4. Change Password
5. type 123 in ** Current Password , New Password**
6. Look into the error message

### Expected result
Error mesage tranlated to spanish
### Actual result

Go to account information type 123 in ** Current Password , New Password**

![image](https://user-images.githubusercontent.com/24475017/30580507-65a6b91a-9d3a-11e7-9095-0fb6132c3d9d.png)

Its is not translated in Spanish. It is not working for other combination also

**Comment by dmanners** [comment] 2017-09-19 08:19
I had this problem when dealing with multiple stores. When building that static content I needed to run the command once for each language. As I understand this is/will be fixed in 2.2.0 or maybe even 2.1.9 but for older versions running the command once for each locale should sort this.

```
php bin/magento setup:static-content:deploy --theme=Your/theme --theme=Magento/backend en_US
php bin/magento setup:static-content:deploy --theme=Your/theme --theme=Magento/backend de_DE
```

I think it is related to https://github.com/magento/magento2/issues/7862

**Comment by KishorkumarKar** [comment] 2017-09-19 09:32
Hi,
I have done that but not working
![image](https://user-images.githubusercontent.com/24475017/30585798-96fe9526-9d4b-11e7-9c43-87200aec3766.png)

**Comment by dmanners** [comment] 2017-09-19 09:39
Hmm, ok I assume that that string is actually in the translation pack. Also it might be a good idea on your local machine to remove all the static files and re-run the `setup:static-content:deploy` command just to make sure there are no left over translations.

**Comment by orlangur** [comment] 2017-09-19 09:50
Does it happen for any JS translation or just this one? https://github.com/magento/magento2/pull/10913 fix may be worth trying also.

**Comment by KishorkumarKar** [comment] 2017-09-19 10:05
It works in another place But not working here.
I have done as @dmanners  said ut not working.
![image](https://user-images.githubusercontent.com/24475017/30587253-1e76ec02-9d50-11e7-890f-29d6909c20d8.png)

**Comment by hostep** [comment] 2017-09-19 19:29
Sound more like a duplicate of https://github.com/magento/magento2/issues/5509, which should get fixed by https://github.com/magento/magento2/pull/10747 which is probably going to be included in Magento 2.1.10. The fix is also already included in version 2.2.0-rc3.0 (by https://github.com/magento/magento2/commit/f67e5989f5efb36ca331e5cc28ee109961fcb99c).

**Comment by magento-engcom-team** [comment] 2017-09-21 07:34
Hi @KishorkumarKar 
Thank you for your report.
This bug is duplicate #5509.

**Comment by magento-engcom-team** [comment] 2017-09-21 07:36
Hi @KishorkumarKar 
Thank you for your report.
This bug is duplicate #5509.

**Closed as completed by magento-engcom-team** 2017-09-21 07:36 UTC
Labels: bug report, Issue: Clear Description, Fixed in 2.2.x, Issue: Format is valid
