### ISSUE TITLE
Check Component Dependency - No Solutions Yet

### ISSUE THREAD

**Issue by kalalruturaj** [magento/magento2#20683] opened 2019-01-28 05:11 UTC
I have upgraded my Magento from 2.16 to Magento 2.3.0 and since then I am not able to install any extension. I am keep getting an error message that Check Component Dependency. I have also attached the composer.json file in the bottom section

 I have refereed  all of the gift-hub tickets             
         1. [#7917](https://github.com/magento/magento2/issues/7917)
         2. [#19850](https://github.com/magento/magento2/issues/19850)
         3. [#3207](https://github.com/magento/magento2/issues/3207)
### Preconditions (*)

1. Magento 2.3.0 not able to pass the Read Link check, Component Dependency erros
2. Php 7.2, Php-fpm-7.2
3. I also Referred this docs as well [Click Here for Docs](https://devdocs.magento.com/guides/v2.3/comp-mgr/trouble/cman/component-depend.html)
4. This is composer.json file [Click Here](https://paper.dropbox.com/doc/Composer.json--AWcUTeSbS2LlB~0czLFrP99jAQ-J8XIdhc7bRgsEa3Wce83P)
### Steps to reproduce (*)

1. web setup wizard -> Extension manager -> Review and Install
2. Select paypal/module-braintree V3.0.6 and Click Install -> Readiness Check
![image](https://user-images.githubusercontent.com/14205802/51815289-d7eedf00-228d-11e9-8ada-53f921a4115a.png)

This is the PayPal BrainTree Magento 2.3.0 Version extension -> Here is the [link Click](https://marketplace.magento.com/paypal-module-braintree.html)

### Expected result (*)

1. Expected to Install extension on store
2.

### Actual result (*)

1. ![image](https://user-images.githubusercontent.com/14205802/51815289-d7eedf00-228d-11e9-8ada-53f921a4115a.png)
2. This is the error message what i get. 
![image](https://user-images.githubusercontent.com/14205802/51815467-1afd8200-228f-11e9-8fd0-389b373c3091.png)

**Comment by magento-engcom-team** [comment] 2019-01-28 05:11
Hi @kalalruturaj. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kalalruturaj do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by kalalruturaj** [comment] 2019-01-28 05:12
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment] 2019-01-28 05:12
Hi @kalalruturaj. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment] 2019-01-28 05:13
Hi @kalalruturaj, here is your [Magento instance](https://i-20683-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-20683-2-3-0.instances.magento-community.engineering/admin](https://i-20683-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-01-28 06:05
Hi @milindsingh. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by milindsingh** [comment] 2019-01-28 06:09
Duplicate https://github.com/magento/magento2/issues/20684

**Closed as completed by milindsingh** 2019-01-28 06:09 UTC
Labels: Issue: Format is valid
