### ISSUE TITLE
Customer Address Attribute

### ISSUE THREAD

**Issue by ivansuharyadi** [magento/magento2#3947] opened 2016-04-01 03:05 UTC
im using magento 2.0.1, i trying to create customer address attribute and displard on checkout page like this below : 
![checkout](https://cloud.githubusercontent.com/assets/4571528/14196677/1699e652-f7f1-11e5-8cf8-6a8f9002b6d4.png)

But on table magento_customercustomattributes_sales_flat_quote_address, this attribute always null.

![localhost-81 - 127 0 0 1 - webshop_sitepreview - mgep_magento_customercustomattributes_sales_flat_quote_address - phpmyadmin 4 5 1 2016-04-01 10-06-54](https://cloud.githubusercontent.com/assets/4571528/14196750/822a295e-f7f1-11e5-97b5-6fb54ed7fbc6.png)

Any ideas ?

Thanks

**Comment by quynhvv** [comment] 2016-04-01 03:08
@ivansuharyadi : 
Let's upgrade your Magento core to 2.0.4. This issue was fixed.
Regards,
quynhvv

**Comment by quynhvv** [comment] 2016-04-01 03:11
@ivansuharyadi 
Let's see here: http://devdocs.magento.com/guides/v2.0/release-notes/ReleaseNotes2.0.4CE.html

**Comment by ivansuharyadi** [comment] 2016-04-01 03:12
Nice, Thanks for your information :+1:

**Comment by ivansuharyadi** [comment] 2016-04-01 06:38
@quynhvv Dou you have same moment with image below, when upgrade magento 2 ?

![readiness check](https://cloud.githubusercontent.com/assets/4571528/14199475/f2bfdebc-f80e-11e5-9c90-8b2660853198.png)

**Comment by vancoz** [comment] 2016-04-01 12:22
Hi @ivansuharyadi please configure crones http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-cron.html

Also seems like your issue is not a bug, so I'm closing the bug, feel free to reopen it if you think it still valid. 

Thank you.

**Closed as completed** 2016-04-01 12:24 UTC

**Comment by ivansuharyadi** [comment] 2016-04-26 08:57
Hi @vancoz, im trying to upgrade again :

![readiness check](https://cloud.githubusercontent.com/assets/4571528/14812440/789b67ec-0bc7-11e6-8099-56975b4119e6.png)

Any ideas ?
