### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, bool given in /vendor/magento/framework/Filesystem/DirectoryList.php:137

### ISSUE THREAD

**Issue by frvoya** [magento/magento2#36082] opened 2022-09-03 06:39 UTC
### Preconditions and environment

- Magento version : 2.4.5
- Anything else that would help a developer reproduce the bug 
MARIADB_VERSION="10.5.16"
VARNISH_VERSION="70"
PHP_VERSION="8.1.9"

UBUNTU: 20.04 LTS

### Steps to reproduce

- Clean install Magento 2.4.5 successfull with lastest PHP version (8.1.9)
- Open store homepage
- Error 503 Backend fetch failed
- Var/log : php-fpm-error.log 
-  PHP Fatal error:  Uncaught TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, bool given in /vendor/magento/framework/Filesystem/DirectoryList.php:137

### Expected result

Access to the store 

### Actual result

Can't display website page

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by gladroger** [comment] 2022-09-16 08:40
Is there any known workaround this problem?

PHP Fatal error: Uncaught TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, bool given in vendor/magento/framework/Filesystem/DirectoryList.php:137

**Comment by artmouse** [comment] 2022-09-19 19:55
The problem is related to changing the default path upload_tmp_dir in PHP-FPM setting.
...
\Magento\Framework\Filesystem\DirectoryList::__construct
...
```
        $sysTmpPath = get_cfg_var('upload_tmp_dir') ?: sys_get_temp_dir();
        $this->directories[self::SYS_TMP] = [self::PATH => realpath($sysTmpPath)];
```
        
realpath may return false

**Comment by engcom-November** [comment] 2022-10-17 14:25
Hi @frvoya ,
Thank you for reporting and collaboration. Verified the issue by installing Magento 2.4.5 with PHP version (8.1.10) but the issue is not reproducible. Magento installation working fine and able to access both admin and storefront pages. Kindly check for system [requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) and 3rd party extensions / modules enabled if any are causing this issue and elaborate steps / configurations if the issue is still reproducible.
Thank you.

**Comment by frvoya** [comment] 2022-10-17 14:29
Hello,

Thank you for your email. Yes we found the issue, The problem is related to changing the default path upload_tmp_dir in PHP-FPM setting.
Regards,
Frederic


De : Girija Bhavani ***@***.***>
Envoyé le :lundi 17 octobre 2022 16:26
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [magento/magento2] PHP Fatal error: Uncaught TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, bool given in /vendor/magento/framework/Filesystem/DirectoryList.php:137 (Issue #36082)


Hi @frvoya<https://github.com/frvoya> ,
Thank you for reporting and collaboration. Verified the issue by installing Magento 2.4.5 with PHP version (8.1.10) but the issue is not reproducible. Magento installation working fine and able to access both admin and storefront pages. Kindly check for system requirements<https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html> and 3rd party extensions / modules enabled if any are causing this issue and elaborate steps / configurations if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-10-18 10:24
Thank you for the response @frvoya . We are closing this issue as its not reproducible with default installation / upgrades.

**Closed as completed by engcom-November** 2022-10-18 10:24 UTC
Labels: Issue: needs update, Reported on 2.4.5

**Comment by magenx** [comment] 2022-11-09 11:25
make sure `tmp` folder exists in path provided in config
