### ISSUE TITLE
Imagemagick Black pixels instead of watermark in magento 2.4.0

### ISSUE THREAD

**Issue by abdullah-bin-hasan** [magento/magento2#29497] opened 2020-08-12 16:01 UTC
### Preconditions (*)

1. Magento 2.4.0
2. php 7.4

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. Watermark in product images

### Actual result (*)

1. Black pixels / background in selected area

Using PHP GD2 solves the problem.

**Comment by sdzhepa** [comment] 2020-08-12 21:28
Hello  @Abdullah-Bin-Hasan 

Could you please provide more details as described in [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) or https://github.com/magento/magento2/issues/29497#issuecomment-672963575? 

In the current stage, it is not clear what the problem and what functionality is broken.
Steps to reproduce, actual and expected result, screens that illustrate problem will help a lot.
Without such details, this issue could be closed as cannot reproduce

**Closed as completed** 2020-09-21 13:16 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid, Progress: done, Reported on 2.4.0
