### ISSUE TITLE
Can't run unit test 

### ISSUE THREAD

**Issue by rogerdz** [magento/magento2#36702] opened 2023-01-05 04:26 UTC
### Preconditions and environment

- Magento version 2.4-develop

### Steps to reproduce

run command: 
./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist

(doc: https://developer.adobe.com/commerce/testing/guide/unit/command-line/)

### Expected result

no error

### Actual result

Error: Config file allure/allure.config.php doesn't exist

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-01-05 12:57
Hi @rogerdz,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.


**Steps to reproduce**

run command:
./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist


We are getting Error: `Config file allure/allure.config.php doesn't exist`


<img width="1022" alt="Screenshot 2023-01-05 at 11 19 02 AM" src="https://user-images.githubusercontent.com/51680745/210784929-71de222f-34f2-42a7-9a1a-2bf67bdbd0fb.png">



Hence confirming the issue.


Thanks.

**Comment by sta1r** [comment] 2023-02-02 15:08
Removing this block from dev/tests/unit/phpunit.xml.dist will fix this temporarily:
```
<extensions>
        <extension class="Qameta\Allure\PHPUnit\AllureExtension">
            <!-- Optional arguments block; omit it if you want to use default values -->
            <arguments>
                <!-- Path to config file (default is config/allure.config.php) -->
                <string>allure/allure.config.php</string>
            </arguments>
        </extension>
    </extensions>
```

**Comment by hostep** [comment] 2023-02-03 15:59
https://github.com/magento/magento2/pull/36703 also fixes it (but why is it marked as WIP @rogerdz?)

**Comment by rogerdz** [comment] 2023-02-05 05:22
@hostep because changed made run unit test fail via command php bin/magento dev:tests:run unit

**Comment by glo71317** [comment] 2023-03-28 09:30
@rogerdz This issue is happening because we made changes to run unit test in 2.4.6 release. Now 2.4-develop is synced so this issue will not be reproduced.
As we have already verified at our end so, Can you please verify at your end?

**Comment by glo71317** [comment] 2023-03-30 14:51
We will check this issue and come back

**Comment by hostep** [comment] 2023-04-05 22:01
@glo71317 

> @rogerdz This issue is happening because we made changes to run unit test in 2.4.6 release. Now 2.4-develop is synced so this issue will not be reproduced.
As we have already verified at our end so, Can you please verify at your end?

I'm still running against this issue on the latest 2.4-develop branch:

```
$ vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist setup/src/Magento/Setup/Test/Unit/
Config file allure/allure.config.php doesn't exist
```

The change from https://github.com/magento/magento2/pull/36703 fixes it for me.

**Comment by glo71317** [comment] 2023-04-06 06:07
Will have a look the fix if required we will deliver this fix ASAP

**Comment by hostep** [comment] 2023-05-15 06:26
Looks like this got fixed by https://github.com/magento/magento2/commit/57e33cc25cfd459cd52abcd3234b6cb546496935 (after some quick testing, it indeed seems to work)

**Comment by engcom-Bravo** [comment] 2023-05-15 08:02
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-7698 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-7698&type=commits

Based on the Jira ticket, the target version is 2.4.7-beta1.

Thanks

**Closed as completed by engcom-Bravo** 2023-05-15 08:02 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P1, Progress: done, Reported on 2.4.x, Area: Framework

**Comment by hostep** [comment] 2024-09-18 14:43
Unfortunately this issue was reintroduced, probably over here: https://github.com/magento/magento2/commit/742c2f927077b69530c299aac3cbb27826087cf1#diff-7a02a9acfbb970097564f499f9b2fbae8ee5067818b5e48273370f845593cfda

When trying to run unit tests locally, I'm getting this error again now:

```
$ vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist path/to/some/php/file.php
...

1) Bootstrapping of extension Qameta\Allure\PHPUnit\AllureExtension failed: Config file allure/allure.config.php doesn't exist
...
```

@nishant04412: what would be your proposal to get around this?

**Comment by rogerdz** [comment] 2024-09-18 16:31
I using code for run unit test:
cd dev/tests/unit/ && ../../../vendor/bin/phpunit -c phpunit.xml.dist ../../../path/to/some/php/file.php

**Comment by nishant04412** [comment] 2025-03-06 10:05
@hostep We have documented the solution [here](https://developer.adobe.com/commerce/testing/guide/unit/command-line/#cli-command-run-with-phpunit-10).

With the latest release of `allure-phpunit`, customization is currently limited due to the introduction of the `bootstrap` tag, which can be added to the `phpunit.xml` configuration file under extensions. The framework's parameter tag defaults to a specific path for retrieving the `allure.config.php` file, preventing customization from Magento’s side based on our findings.

To address this, we have proposed a change in the [allure-phpunit repository](https://github.com/allure-framework/allure-phpunit) ([PR #107](https://github.com/allure-framework/allure-phpunit/pull/107)). However, we are still awaiting a response. If the change is accepted, it will enable path customization. Otherwise, their feedback will clarify any potential impacts.

Let us know if you have any further questions!
