### ISSUE TITLE
Sorting on attributes of type "dropdown" or "swatch" use option_id in frontend product collection not the sorting order used everywhere else

### ISSUE THREAD

**Issue by iphigenie** [magento/magento2#32708] opened 2021-04-10 14:31 UTC
EDIT: changed the chosen products (not some next to each other) and chosen name so it is more different than default category order and there is no confusion. **screenshots made on April 14 on an instance supplied here**

If you have an order to options in a "single select" attribute that isn't the order they were created in, sorting by this attribute in listings will not produce the order you expect. The order will not be the order as set in attribute configuration.

Note: the attribute option values will be in the correct order in admin, including sorting products in catalog admin product grid. they also will be in the correct orders in the layered navigation selector. But on the store frontend, they will be in the wrong order, not using the sort order established for the attribute options. 

I have been banging my head on my site on a "model year" sorting but now see it is a core bug, possibly linked to the change to elasticsearch as I think this used to work (surely someone would have noticed before if it didnt?)

### Steps to reproduce (*)

done it on 2.4.2 with demo content

1. add an options to the color attribute, in my case I added "fluorescent" - it is the last by option_id
2. change order, in my case I moved fluorescent to the proper alphabetical spot before gray 
![Ashampoo_Snap_2021 04 14_08h42m35s_031_](https://user-images.githubusercontent.com/1055826/114679049-bad64780-9d03-11eb-848f-a75470198735.png)

3. add colors to products, in my case I chose the bag section and gave the green bag the color "fluorescent" and give a few other bags "black", "gray" and "white". I have chosen products not next to each other so it is obvious when sorting by color or position
![Ashampoo_Snap_2021 04 14_08h51m38s_033_](https://user-images.githubusercontent.com/1055826/114679389-012ba680-9d04-11eb-85fe-2975151799f0.png) 

4. make sure the category has the attribute as a "sort by" option (bags has "all" by default)
5. Flush cache (if command line access, can also reindex etc etc it makes no difference)
6. go to the front end to that category and sort by color

In short, in the "default" category order the grey back is in front of the fluorescent one and the white after. If sorting by color works they will both be after. If sorting by color sticks to the wrong (option_id) order, they will both be before. 

for reference, in default category order it looks like this
![Ashampoo_Snap_2021 04 14_08h45m24s_032_](https://user-images.githubusercontent.com/1055826/114680122-bc543f80-9d04-11eb-8f9d-537175261564.png)

### Expected result (*)

1. results should be in the attribute order value as set in the position list of the attribute (i.e. in database the field "sort_order")

in my example **you'd expect the product assigned as fluorescent should come before the products assigned as gray and white** here we see it in admin things are sorted right:

![Ashampoo_Snap_2021 04 14_09h19m52s_001_](https://user-images.githubusercontent.com/1055826/114679994-9dee4400-9d04-11eb-8437-40e813f64b2c.png)

### Actual result (*)

1.  results are in the the order options were created (i.e. the field option_id) not the order set in attribute options management

in my example the product assigned as fluorescent is after the product assigned as white and gray
![Ashampoo_Snap_2021 04 14_09h10m02s_003_](https://user-images.githubusercontent.com/1055826/114679807-6b444b80-9d04-11eb-8ceb-69c10acefb3e.png)

note: all products without color come after the products with a color no matter in which direction you sort.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x

 ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by iphigenie** [comment] 2021-04-10 15:41
This has been reproduced on 2.4.2 release vanilla instance

**Comment by engcom-Oscar** [comment] 2021-04-12 13:38
Hi @iphigenie ! Did you flush the cache after making changes with product's attribute? Because for me product's sorting working well - I tried to reproduce this issue on 2.4-develop branch.
![Screenshot from 2021-04-12 16-34-45](https://user-images.githubusercontent.com/60198413/114403295-5608d900-9bad-11eb-8192-fb9c7592e847.png)

**Comment by iphigenie** [comment] 2021-04-12 15:21
definitely cache flushed, reindexed - done a few times. I still get white before turquoise.

**Comment by iphigenie** [comment] 2021-04-12 15:22
@magento give me 2.4 instance

**Comment by iphigenie** [comment] 2021-04-12 15:55
so yes, the issue happens on 2.4.2 release https://ad1bf489fc81b71d7ceb70130152bac4-2-4.instances.magento-community.engineering/gear/bags.html?product_list_order=color  I did clear the caches but no command line access to flush or reindex.

**Comment by iphigenie** [comment] 2021-04-12 15:55
@magento give me 2.4-develop instance

**Comment by iphigenie** [comment] 2021-04-12 17:21
Hi @engcom-Oscar are you sure it is sorting there? Because that is the default category order and unless you have set colors on all the other products the two color products should not be in the middle


Magento 2.4.2 release instance requested here today

cache flushed via admin button

https://ad1bf489fc81b71d7ceb70130152bac4-2-4.instances.magento-community.engineering/gear/bags.html?product_list_order=color

![Ashampoo_Snap_2021 04 12_18h17m17s_019_](https://user-images.githubusercontent.com/1055826/114435160-c28ad480-9bbb-11eb-8e12-11045b0d2ed7.png)


Magento 2.4.2-dev instance requested here today 

cache flushed via admin button

https://ad1bf489fc81b71d7ceb70130152bac4-2-4-develop.instances.magento-community.engineering/gear/bags.html?product_list_order=color

![Ashampoo_Snap_2021 04 12_18h16m29s_018_](https://user-images.githubusercontent.com/1055826/114435122-b737a900-9bbb-11eb-9efd-a30d33a6b2b4.png)


Maybe I'm having a brain blip and missing some obvious step, I'd love that!

**Comment by iphigenie** [comment] 2021-04-14 07:29
> Hi @iphigenie ! Did you flush the cache after making changes with product's attribute? Because for me product's sorting working well - I tried to reproduce this issue on 2.4-develop branch.
> ![Screenshot from 2021-04-12 16-34-45](https://user-images.githubusercontent.com/60198413/114403295-5608d900-9bad-11eb-8192-fb9c7592e847.png)

Hi again @engcom-Oscar I think your screenshot is just the default category order, not sorted by color?

![114403295-5608d900-9bad-11eb-8192-fb9c7592e847](https://user-images.githubusercontent.com/1055826/114670922-6a5aec00-9cfb-11eb-8ec8-4ba4e5f4422f.png)

**Comment by iphigenie** [comment] 2021-04-14 07:32
@magento give me 2.4-develop instance

**Comment by iphigenie** [comment] 2021-04-14 08:50
I have now reproduced this 3 times with deployments supplied here can someone please tag it?

**Comment by magento-engcom-team** [comment] 2021-04-15 09:26
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41919` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment] 2021-04-23 13:59
Hi @iphigenie, after speaking with the Product Owner, we don't believe this is an issue. The sort order of the attributes on the admin area has no relationship with the sort order that products will show on the listing page.

That is only relevant to how the options are displayed on the product page.

Hope that makes sense. A feature request may be created for such a case, but it would have to be discussed with the Product organization to decide how it should work.

Thanks!

**Comment by magento-engcom-team** [comment] 2021-04-23 14:00
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Closed as completed by gabrieldagama** 2021-04-23 13:59 UTC
Labels: Component: Catalog, Issue: Confirmed, Progress: done

**Comment by iphigenie** [comment] 2021-04-24 11:11
> Hi @iphigenie, after speaking with the Product Owner, we don't believe this is an issue. The sort order of the attributes on the admin area has no relationship with the sort order that products will show on the listing page.

HI @gabrieldagama - the bug I reported is sorting being WRONG ON THE FRONT END - are you saying that the sorting one creates in admin is just for show, and it will not be used and this is not a bug?

**Comment by gabrieldagama** [comment] 2021-04-26 10:40
Hi @iphigenie, thanks for sharing your thoughts.

What I meant is that this is not a behavior that the product organization expects and the code was never built to produce such behavior, so from our perspective that is not a bug.

Now, I've spoken with @engcom-Oscar and he has brought up a valid point, it seems that the attribute sorting (color) is actually being done by option id (as you described). In this case, I believe it can be considered a bug, I believe that should be alphabetical order as an example.

If you believe the behavior should be based on attribute order on the backend, that will have to be a feature request instead.

Hope that makes sense,
Thanks.

**Comment by iphigenie** [comment] 2021-04-26 11:49
Hi @gabrieldagama 

Thanks for the update - this is exactly what my ticket said, that they are being sorted by "option id" and that made no sense.  It's obviously something you'd only start to notice after you've run a site a while and added new options.

Alphabetical I would have understood, or the order as set in admin (which is the order used for the swatches in layered navigation). Both of these a customer would understand. I'd be OK with either

I suspect it is going to be no more efficient to sort by value name (different per store view) than to sort in admin-set-order (same across store views) and it might be worth finding out what the community expects of such a sorting. 


There are a few oddities in the admin vs frontend handling of options, I guess most people don't use 100 options in some like we ended up having

**Comment by kestraly** [comment] 2021-08-10 12:01
Argh, I was hoping for some resolve on this with ElasticSearch.

In the past I was able to sort by the sort_order of the attribute by using the following code

 ```
## \Magento\Eav\Model\ResourceModel\Entity\Attribute $eavAttribute,
## $this->_eavAttribute = $eavAttribute;

$attributeId = $this->_eavAttribute->getIdByCode('catalog_product', $subject->getCurrentOrder());

$collection->clear()->getSelect()
                            ->reset(\Zend_Db_Select::ORDER)
                            ->joinLeft(array('cpei' => 'catalog_product_entity_int'), 'e.entity_id = cpei.entity_id AND cpei.attribute_id = ' . $attributeId . ' AND cpei.store_id = 0', 'cpei.value as product_on_top')
                            ->joinLeft(array('eao' => 'eav_attribute_option'), 'eao.option_id = cpei.value', 'eao.sort_order as sort_order')
                            ->order('sort_order' . ' ' . 'asc');

                        if (count($products) > 0) {
                            foreach ($products as $position) {
                                $productarray[] = $position->getId();
                            }
                    
                    if (!empty($products)) {
                        $result->getCollection()->getSelect()->order(
                            new \Zend_Db_Expr('FIELD(`e`.`entity_id`,' . implode(
                                    ',', array_unique($productarray)
                                ) . ') '
                            ));
                    }
```

**Comment by kestraly** [comment] 2021-08-11 19:33
Can we reopen this? 

It would be good if the sortby toolbar with ElasticSearch would sort by either the sort_order / position you've dragged the attribute to, or at the very least the attribute value name.

At the moment it sorts by attribute value id - this relies entirely on you adding the attribute to the catalog in one go and not adding additional attributes later on, which will go to the end of the sort, making the sort absolutely useless.

**Comment by nkarthickannan** [comment] 2023-07-14 12:18
@gabrieldagama Hope you are doing well !! As far as I can see, you have mentioned that one issue and one feature request is found in this discussion. Let's ignore the feature request. We should atleast find a solution to the agreed issue before closing it.

Agreeing that an issue is there and ignoring does not seem to be logical. If you have any other ticket for this, please mention so that everyone can understand that this is being taken care in another ticket/issue.

BTW, I'm not sure if you will ever read the comments in a closed issue or not.
