### ISSUE TITLE
Braintree doesn't work on Magento CE 2.1.0 when using table prefixing (HTTP/1.1 400 Bad Request)

### ISSUE THREAD

**Issue by flecxie** [magento/magento2#5902] opened 2016-07-30 05:41 UTC
The Magento CE 2.1.0 Braintree module seems to be broken when using table prefixing during installation. When setting up 2 stores (1 without table prefixing and 1 with table prefixing) then payments from the site with table prefixing fail. 
### Steps to reproduce
1. Install Magento-CE-2.1.0_sample_data-2016-06-23-02-34-56 twice, once with sql table prefixing & once without
2. Create a Braintree Sandbox account & enable Braintree on both sites (make sure you set merchant country)
3. Purchase product on both sites
### Expected result
1. Purchase successful on both sites & transaction showing up on Braintree dashboard
### Actual result
1. Purchase successful on site which didn't use table prefixing
2. Purchase fails on site which has table prefixing showing error "Unable to place Order. Please try again later." - the browser console also shows  [HTTP/1.1 400 Bad Request] upon posting to payment-information
3. Payment from **both** sites does show up on Braintree dashboard, even the payment which was marked as **failed** from the site with table prefixing

See screenshot below for error:
![braintree_bug](https://cloud.githubusercontent.com/assets/18500078/17268356/5c95b27a-566b-11e6-9e88-611689b721cc.png)

**Comment by flecxie** [comment] 2016-07-30 08:03
Related to https://github.com/magento/magento2/issues/5714

**Comment by pboisvert** [comment] 2016-07-31 01:39
@asemenenko can you have the team check into this one?

**Comment by flecxie** [comment] 2016-07-31 05:40
WAR for now is to get rid of table prefixing, to do this in an existing store:
1. Rename all SQL tables
2. Update table references in the sales_sequence_meta table (otherwise all orders will fail)

I used a simple bash script to rename all SQL tables. 
To update the tables references in sales_sequence_meta I ran the following SQL:

`update sales_sequence_meta set sequence_table = replace(sequence_table,'YOURPREFIX_','');`

**Comment by YevSent** [comment] 2016-08-03 15:06
Hi @flecxie, please, attach debug and exception log.
Created internal ticket to investigate this issue MAGETWO-56344.
UPD: did you enable Vault for Braintree?

**Comment by flecxie** [comment] 2016-08-04 01:03
Sorry, no longer have this environment but should be easy to replicate this issue locally. 

Debug.log showed a successful Braintree transaction & the transaction did show up on the Braintree dashboard. Nothing in exception.log, but using Xdebug I could see an exception being triggered...

**Comment by flecxie** [comment] 2016-08-04 01:56
Didn't enable Vault

**Comment by gabriel-sf** [comment] 2016-08-16 11:48
Just to add a note (since I just fixed it after 3 full days), renaming the tables and removing the table prefix also solved the 400 error for PayFlow Pro.

**Comment by romeof1980** [comment] 2016-08-17 10:14
Thanks @flecxie ,
deleting table prefixing fixed the issue for us too (both in 2.0.6 and 2.1.0).
Vault enabled or not didn't make any difference for us, nor did "Authorize" or  "Authorize and Capture".

**Comment by redline10000** [comment] 2016-08-18 22:51
Hello
I followed the suggestions in the the above post to remove the prefix from my magento database. I then did the table update update sales_sequence_meta set sequence_table = replace(sequence_table,'YOURPREFIX_',''); .  However it seems that some tables are still referencing my old prefix mgxa_. When I try to add a new product I get the error 

 SQLSTATE[42S02]: Base table or view not found: 1146 Table 'datbasename.mgxa_catalogrule_product_cl' doesn't exist, query was: INSERT INTO `catalog_product_entity` (`entity_id`, `attribute_set_id`, `type_id`, `sku`, `has_options`, `required_options`) VALUES (?, ?, ?, ?, ?, ?) 

Any ideas on how to fix my db?

**Comment by gabriel-sf** [comment] 2016-08-18 23:38
Hi @redline10000 , check this thread about the process on how to rename the tables.

http://magento.stackexchange.com/questions/103597/how-to-properly-remove-db-table-prefix-in-magento2/103599

**Comment by redline10000** [comment] 2016-08-18 23:53
Hi @gabriel-sf 

Thank you, the article makes sense but how do I figure out which table is looking for mgxa_catalogrule_product_cl?

**Comment by redline10000** [comment] 2016-08-19 00:16
Upon digging deeper into my database it appears that the triggers are still referencing the wrong table names. They all still have mgxa_ in them. But my tables no longer have mgxa_

**Comment by gabriel-sf** [comment] 2016-08-19 00:31
@redline10000 to be honest, I removed the prefix of all the tables and then followed those instructions. Sorry I dont have more info. Have you cleared your cache and index?

**Comment by redline10000** [comment] 2016-08-19 01:10
Hi @gabriel-sf 

I have cleared the cache and indexes.  I removed the triggers and everything seems fine now. Yet I am still getting the 400 error when making a braintree payment.

**Comment by gabriel-sf** [comment] 2016-08-19 01:12
I would suggest using xdebug to see what errors you are getting and try to debug it from there. There might be a table or something missing.

**Comment by romeof1980** [comment] 2016-08-19 17:12
Hi @redline10000,
have you enabled 3D secure in Magento 2 Braintree configuration section?

**Comment by redline10000** [comment] 2016-08-19 21:00
@romeof1980  thank you for the suggestion but I ended up just making a new db. My install was a new install and was not really worth all of the effort to fix. Fresh install w/o table prefixes fixed everything.

**Comment by romeof1980** [comment] 2016-08-19 21:04
Sounds very good. Personally, when editing dtb and ending with errors, I'd not just delete the cache but I'd also delete and redeploy static content

---- On Fri, 19 Aug 2016 23:00:51 +0200 notifications@github.com wrote ----

@romeof1980 thank you for the suggestion but I ended up just making a new db. My install was a new install and was not really worth all of the effort to fix. Fresh install w/o table prefixes fixed everything.

**Comment by davidaddison** [comment] 2016-08-29 14:54
Any ETA on a fix?

**Comment by YevSent** [comment] 2016-08-30 07:24
This fix already merged to develop branch [ce1160f](https://github.com/magento/magento2/commit/ce1160fbf7d1d08bc2d0d6f3d4c648074271024b) and will be available in some of 2.1.x releases.

**Comment by dyushkin** [comment] 2016-09-13 11:35
Hi @flecxie! Closing the issue, please feel free to reopen if the issue still reproducible for you.

**Closed as completed by dyushkin** 2016-09-13 11:35 UTC
Labels: Issue: Ready for Work, bug report, Component: Payment

**Comment by neilrd** [comment] 2016-09-14 06:26
Is the fix available in 2.1.1?

**Comment by YevSent** [comment] 2016-09-14 07:16
This fix will be available in Magento 2.1.3 version.

**Comment by neilrd** [comment] 2016-09-14 07:19
I am pretty inexperienced with MySQL. However I have logged into the MySQL monitor via SSH as the root user. What are the exact commands I need to run to solve this problem - please explain step by step.

I copied and pasted this command:

MariaDB [storedB]>

> ALTER TABLE sales_invoice_grid ADD base_grand_total decimal(12,4) AFTER grand_total;

but the following error was flagged:
<img width="867" alt="screen shot 2016-09-14 at 00 00 23" src="https://cloud.githubusercontent.com/assets/21035284/18494518/712bbd1c-7a0e-11e6-9aae-12aec00b1f19.png">

Appreciate any support with this. Apologies for my lack of experience.

Kind Regards

**Comment by irfankhan86004** [comment] 2016-09-23 18:05
hi 
any one please tell me this issue i solve or not 

Or 

Give me some hint how can i solve this issue in mangeto2

Because it's argent

**Comment by davidaddison** [comment] 2016-09-23 18:58
It worked for me with M2.1 after I reinstalled without prefixing on the database.  It was a pain to reinstall and migrate everything around – took about 4 full days that I neither had in my schedule or budget.  There are no good tools for migrating M2 data.  The whole situation stinks.

But, I look at things for the good - I got more practice installing M2.1.  And I got it fixed.

If I could do this project over again I'd think long and hard about using Magento.  They've lost almost all of my trust.

**Comment by romeof1980** [comment] 2016-09-23 19:04
You don't need to reinstall in order to remove table-prefixing.. Just google around and you'll find a lot of answers. It's a matter of running a SINGLE command and editing a line in env.php
:)

---- On Fri, 23 Sep 2016 20:58:31 +0200 notifications@github.com wrote ----

It worked for me with 2.1 after I reinstalled without prefixing on the database. It was a pain to reinstall and migrate everything around – took about 4 full days that I neither had in my schedule or budget. There are no good tools for migrating M2 data. The whole situation stinks.

But, I look at things for the good - I got more practice installing M2.1. The reinstall had lots of problems.

**Comment by davidaddison** [comment] 2016-09-23 19:33
My managed Magento hosting firm (a big one that knows M2.1) did not like romeof1980's solution.  They thought it safest to reinstall.  I would have liked to do what romeof1980 says.

**Comment by romeof1980** [comment] 2016-09-23 19:51
Hi @davidaddison,
good to know...
anyway, we can confirm that it works like charm both with single store mode and in multi store. We've tested it thoroughly and we use more than 20 extensions (tested with 2.1.0 too).
You know, saying you don't like it won't help too much other people that have gotten the same issue.. give more background info (like problem you think could arise) would be great.
Again, we spend just 5 minutes with our multistore in order to fix it: we're in production and it's been working like charm for more than 1 month..
cheers! ;)
