### ISSUE TITLE
Invalid input datetime format of value

### ISSUE THREAD

**Issue by frilogg** [magento/magento2#28171] opened 2020-05-08 21:14 UTC
### Preconditions (*)

1. Magento 2.3.5-P1
2.PHP 7.3.17
3. MySQL 5.7
4. Magento Language Norwegian Bokmål
5. Time Zone Europe/Oslo
6. Time setting Magento - Day - Month - Year and Timeformat 24 Hour. 
7. Update Admin Interface Locale : Norsk Bokmål (Norge) / norsk bokmål (Norge)

### Steps to reproduce (*)

1. When trying to save new Special price or trying to make chagnes to products that has special price defined. I get this error . "Invalid input datetime format of value" 
2. I can save product and save if date from  - to is not defined and product price in special price is removed. 

### Expected result (*)

1. I expect I can save products witout any problem. 
2.

### Actual result (*)

1. When trying to save new Special price or trying to make chagnes to products that has special price defined. I get this error . "Invalid input datetime format of value"

**Comment by shikhamis11** [comment] 2020-05-08 21:33
Hi @frilogg 
Thank you for reporting this issue .. Please check this issue on magento instance and share screenshots or video if you are able to reproduce the issue here

**Comment by shikhamis11** [comment] 2020-05-08 21:34
> Hi @shikhamis11. Thank you for working on this issue.
> In order to make sure that issue has enough information and ready for development, please read and check the following instruction: point_down
> 
>     * [ ]  1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).DetailsIf the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.
> 
>     * [ ]  2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.
> 
>     * [ ]  3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
> 
>     * [ ]  4. Verify that the issue is reproducible on `2.4-develop` branchDetails- Add the comment `@magento give me 2.4-develop instance` to deploy test instance on Magento infrastructure.  - If the issue is reproducible on `2.4-develop` branch, please, add the label `Reproduced on 2.4.x`.- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
> 
>     * [ ]  5. Add label `Issue: Confirmed` once verification is complete.
> 
>     * [ ]  6. Make sure that automatic system confirms that report has been added to the backlog.

check this bot message for asking instances

**Comment by magento-engcom-team** [comment] 2020-05-08 21:34
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by gauravagarwal1001** [comment] 2020-05-13 07:53
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-13 07:53
Magento instance deployment temporary unavailable due to service maintenance.

**Comment by frilogg** [comment] 2020-05-13 11:52
This is why nothing has happend last 5 days...?

**Comment by shikhamis11** [comment] 2020-05-13 17:12
hi @frilogg 
I tried to reproduce this issue on my local but not able to reproduce it 
I tried steps 
STORE->CONFIG->GENERAL->Locale Options->Locale   Magento Language Norwegian Bokmål
STORE->CONFIG->GENERAL->Locale Options->Timezone   Time Zone Europe/Oslo
STORE->CONFIG->Catalog->Date & TIme Custom options  - Day - Month - Year and Timeformat 24 Hour.

after that I tried to add product with special price 

Please let me know if it require any additional step to reproduct this issue

**Comment by frilogg** [comment] 2020-05-13 17:41
> now if it require any additional step to reproduct this issue

And had the admin language changed to Norwegian also?

**Comment by shikhamis11** [comment] 2020-05-13 17:52
you mean from admin account section ?

**Comment by frilogg** [comment] 2020-05-13 17:59
@shikhamis11  yes.

**Comment by frilogg** [comment] 2020-05-13 18:06
Could this be same as this issue?  https://github.com/magento/magento2/issues/24696

**Comment by shikhamis11** [comment] 2020-05-13 18:11
yes both seems same issue .

**Comment by shikhamis11** [comment] 2020-05-13 18:12
I am able to reproduce this issue but since similar issues already confirmed I am closing this one you can track it's progress from #24696

**Closed as completed by shikhamis11** 2020-05-13 18:12 UTC
Labels: Issue: Format is valid, Reported on 2.3.5
