### ISSUE TITLE
OptionValueProvider class get() method contains an incorrect query value

### ISSUE THREAD

**Issue by LukasDeRuiter** [magento/magento2#35910] opened 2022-08-10 14:28 UTC
### Preconditions and environment

- Magento version: 2.4.3

### Steps to reproduce

1. Install Adobe Commerce with sample data.

2. Remove the following line in the DB (`DELETE FROM eav_attribute_option_value WHERE `eav_attribute_option_value`.`value_id` = 221`):
![2022-09-07_06-28](https://user-images.githubusercontent.com/75968/188793292-2cfecffa-1903-4baf-ba55-887d9e36d1cb.png)

Try to create a return using the `RequestReturnMutation` GraphQL mutation with "Reason: Wrong Color".

```
mutation {
  requestReturn(
    input: {
      order_uid: "Mg=="
      contact_email: "john@example.com"
      comment_text: "I want to return the shirt because I don't like the texture of the fabric"
      items: { 
        order_item_uid: "NQ=="
        quantity_to_return: 1
				selected_custom_attributes: [
          {
            attribute_code: "resolution"
            value: "MjE1"
          }
          {
            attribute_code: "condition"
            value: "MjE5"
          }
          {
            attribute_code: "reason"
            value: "MjIx"
          }
        ]
        
      }
    }
  ) {
    return {
      uid
      items {
        uid
        status
        request_quantity
        quantity
        order_item {
          id
          eligible_for_return
          product_sku
          product_sku
          product_type
          quantity_returned
          status
        }
      }
      number
      status
      comments {
        uid
        author_name
        text
        created_at
      }
      customer {
        firstname
        lastname
        email
      }
    }
  }
}
```

## What happens

GraphQL returns an error **due to `Magento\RmaGraphQl\Model\Rma\Item::Builder` calling the method with an option_id value** (`if ($this->optionValueProvider->get((int)$attributeValue)) {`).

The error is:
```
{
  "operationName": "RequestReturnMutation",
  "variables": {
    "input": {
      "contact_email": "john@example.com",
      "order_uid": "NA==",
      "items": [
        {
          "order_item_uid": "NQ==",
          "quantity_to_return": 1,
          "selected_custom_attributes": [
            {
              "attribute_code": "resolution",
              "value": "MjE1"
            },
            {
              "attribute_code": "condition",
              "value": "MjE5"
            },
            {
              "attribute_code": "reason",
              "value": "MjIx"
            }
          ]
        }
      ]
    }
  },
  "data": [
    {
      "message": "Value of reason is incorrect",
      "extensions": {
        "category": "graphql-input"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "requestReturn"
      ]
    }
  ]
}
```

### Expected result

This method should return an attribute option value based on the given option_id.

### Actual result

This method returns only an error, as the 'value_id' column is not present.

### Additional information

This issue can be fixed by changing the the first parameter name to '$optionId', and changing the first parameter of the ->where method to 'option_id'. Code as example:

private function get(int $optionId): ?string
    {
        $select = $this->connection->select()
            ->from($this->connection->getTableName('eav_attribute_option_value'), 'value')
            ->where('option_id = ?', $optionId);

        $result = $this->connection->fetchOne($select);

        if ($result) {
            return $result;
        }

        return null;
    }

Kind regards,
Lukas de Ruiter
Youwe B.V.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2022-08-18 10:38
Hello @LukasDeRuiter,

Thanks for the report and collaboration!

We have tried to reproduce the issue in Magento 2.4-develop branch but were unable to do so. We can see the `value_id` column in `eav_attribute_option_value` table. Please refer the below screenshot for reference:

<img width="423" alt="image" src="https://user-images.githubusercontent.com/51681618/185375628-b97d00ca-6907-44b2-b84f-953cebb13d89.png">

Let us know in case we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2022-09-01 06:48
Dear @LukasDeRuiter,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by real34** [comment] 2022-09-07 05:15
Hi,

I can confirm  @LukasDeRuiter's report.
While there are both columns, the docblock explicitely states 
> Get EAV attribute option value by option id

It lies!
![2022-09-07_06-31](https://user-images.githubusercontent.com/75968/188792479-27200f0b-d498-42f3-b66a-a44ceab9c585.png)

## Problem

I struggled to understand why this class was introduced in the core [and commits aren't helpufl in that sense](https://github.com/magento/magento2/commits/2.4-develop/app/code/Magento/Eav/Model/ResourceModel/Entity/Attribute/OptionValueProvider.php).

Moreover, there is no usage of this class in Magento OpenSource (on `2.4-develop`):
```
$ git rev-parse --short HEAD
26057964cdb
$ rg -i "OptionValueProvider" 
app/code/Magento/Eav/Model/ResourceModel/Entity/Attribute/OptionValueProvider.php
17:class OptionValueProvider
```

It however is used in Adobe Commerce, by the RMA GraphQL module:
```
$ rg -i "OptionValueProvider" vendor/magento 
vendor/magento/module-eav/Model/ResourceModel/Entity/Attribute/OptionValueProvider.php
18:class OptionValueProvider

vendor/magento/module-rma-graph-ql/Model/Rma/Item/Builder.php
14:use Magento\Eav\Model\ResourceModel\Entity\Attribute\OptionValueProvider;
50:     * @var OptionValueProvider
52:    private $optionValueProvider;
59:     * @param OptionValueProvider $optionValueProvider
66:        OptionValueProvider $optionValueProvider
72:        $this->optionValueProvider = $optionValueProvider;
156:            if ($this->optionValueProvider->get((int)$attributeValue)) {

vendor/magento/module-rma-graph-ql/Model/Formatter/CustomAttribute.php
12:use Magento\Eav\Model\ResourceModel\Entity\Attribute\OptionValueProvider;
32:     * @var OptionValueProvider
34:    private $optionValueProvider;
39:     * @param OptionValueProvider $optionValueProvider
44:        OptionValueProvider $optionValueProvider
48:        $this->optionValueProvider = $optionValueProvider;
61:            $value = $this->optionValueProvider->get((int)$value);
```

As a consequence, the RMA GraphQL module doesn't work.

## To reproduce

Install Adobe Commerce with sample data.

Remove the following line in the DB (`DELETE FROM eav_attribute_option_value WHERE `eav_attribute_option_value`.`value_id` = 221`):
![2022-09-07_06-28](https://user-images.githubusercontent.com/75968/188793292-2cfecffa-1903-4baf-ba55-887d9e36d1cb.png)

Try to create a return using the `RequestReturnMutation` GraphQL mutation with "Reason: Wrong Color".

## What happens

GraphQL returns an error **due to `Magento\RmaGraphQl\Model\Rma\Item::Builder` calling the method with an option_id value** (`if ($this->optionValueProvider->get((int)$attributeValue)) {`).

The error is:
```
{
  "operationName": "RequestReturnMutation",
  "variables": {
    "input": {
      "contact_email": "john@example.com",
      "order_uid": "NA==",
      "items": [
        {
          "order_item_uid": "NQ==",
          "quantity_to_return": 1,
          "selected_custom_attributes": [
            {
              "attribute_code": "resolution",
              "value": "MjE1"
            },
            {
              "attribute_code": "condition",
              "value": "MjE5"
            },
            {
              "attribute_code": "reason",
              "value": "MjIx"
            }
          ]
        }
      ]
    }
  },
  "data": [
    {
      "message": "Value of reason is incorrect",
      "extensions": {
        "category": "graphql-input"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "requestReturn"
      ]
    }
  ]
}
```

## Expected

It should accept the return request and save it.

## Next

I'll submit a PR to change this value, and see if no regression is detected by the Magento OpenSource test suite.
Could you please reopen this issue?

**Comment by engcom-Hotel** [comment] 2022-09-08 09:00
Hello @real34,

Thanks for the contribution! 

We are reopening this issue for further processing.

We have a query here, in your comment you have mentioned the mutation `RequestReturnMutation` but instead, we have found this mutation `requestReturn ` here in the [document](https://devdocs.magento.com/guides/v2.4/graphql/mutations/request-return.html). Are you talking about the same?

And also can you please tell us your mutation query?

Thanks

**Comment by real34** [comment] 2022-09-08 09:05
Hi @engcom-Hotel,
Thanks for reopening.

It indeed is `requestReturn`.
Here is the code of our mutation:

```gql
mutation RequestReturnMutation($input: RequestReturnInput!) {
  requestReturn(input: $input) {
    return {
      order {
        id
      }
    }
  }
}
```

**Comment by engcom-Hotel** [comment] 2022-09-14 10:33
Hello @real34,

Thanks for the response!

Based on your comment, we have tried to reproduce the issue in Magento 2.4-develop branch. And the issue is reproducible for us. It seems that there is a mismatch in comment vs functionality. In the comment, it is written that the `getting EAV attribute option value by option id` but actually it is getting by `value_id` in the `get` method of `app/code/Magento/Eav/Model/ResourceModel/Entity/Attribute/OptionValueProvider.php`. 

Hence confirming the issue and updating the description.

Thanks

**Comment by engcom-November** [comment] 2023-03-27 14:44
Hi @LukasDeRuiter ,
Development team is currently working on this issue.
Thank you.

**Closed as completed** 2023-05-09 21:17 UTC
Labels: Issue: Confirmed, Component: DB, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P2, Progress: done, Reported on 2.4.3, Area: Framework

**Comment by engcom-Bravo** [comment] 2023-05-11 06:42
Hello,


As I can see this issue got fixed in the scope of the internal Jira ticket AC-6680 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-6680&type=commits

Based on the Jira ticket, the target version is 2.4.7-beta1.

Thanks
