### ISSUE TITLE
Error elasticsearch number_format_exception

### ISSUE THREAD

**Issue by mohammedTBB** [magento/magento2#36108] opened 2022-09-07 13:37 UTC
### Preconditions and environment

Magento version 2.4.5
Php version 8.1
Elastic version 7.17.5

### Steps to reproduce

Set attribute Manufacturer Use in Layered Navigation "filterable with results"

### Expected result

No Error

### Actual result

**Error generating constantly in system.log**

[2022-09-07T13:32:03.429219+00:00] main.CRITICAL: Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query: For input string: \"62_87_97_42\"","index_uuid":"zzqL3lgYQD6gXbLTJhdSHA","index":"progym-binom-m2_product_6_v34"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"progym-binom-m2_product_6_v34","node":"7wb1_gUyRS60QIpiYd3p9A","reason":{"type":"query_shard_exception","reason":"failed to create query: For input string: \"62_87_97_42\"","index_uuid":"zzqL3lgYQD6gXbLTJhdSHA","index":"progym-binom-m2_product_6_v34","caused_by":{"type":"number_format_exception","reason":"For input string: \"62_87_97_42\""}}}]},"status":400} in /var/www/clients/client3/web22/web/releases/207/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:693
Stack trace:
#0 /var/www/clients/client3/web22/web/releases/207/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(333): Elasticsearch\Connections\Connection->process4xxError()
#1 /var/www/clients/client3/web22/web/releases/207/vendor/react/promise/src/FulfilledPromise.php(28): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}()
#2 /var/www/clients/client3/web22/web/releases/207/vendor/ezimuel/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then()
#3 /var/www/clients/client3/web22/web/releases/207/vendor/ezimuel/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then()
#4 /var/www/clients/client3/web22/web/releases/207/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(345): GuzzleHttp\Ring\Core::proxy()
#5 /var/www/clients/client3/web22/web/releases/207/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(241): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}()
#6 /var/www/clients/client3/web22/web/releases/207/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(110): Elasticsearch\Connections\Connection->performRequest()
#7 /var/www/clients/client3/web22/web/releases/207/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(1929): Elasticsearch\Transport->performRequest()
#8 /var/www/clients/client3/web22/web/releases/207/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(1353): Elasticsearch\Client->performRequest()
#9 /var/www/clients/client3/web22/web/releases/207/vendor/magento/module-elasticsearch-7/Model/Client/Elasticsearch.php(338): Elasticsearch\Client->search()
#10 /var/www/clients/client3/web22/web/releases/207/vendor/magento/module-elasticsearch-7/SearchAdapter/Adapter.php(117): Magento\Elasticsearch7\Model\Client\Elasticsearch->query()
#11 /var/www/clients/client3/web22/web/releases/207/vendor/magento/module-search/Model/SearchEngine.php(42): Magento\Elasticsearch7\SearchAdapter\Adapter->query()
#12 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/Search/Search.php(85): Magento\Search\Model\SearchEngine->search()
#13 /var/www/clients/client3/web22/web/releases/207/vendor/amasty/shopby/Model/Layer/Filter/Category.php(597): Magento\Framework\Search\Search->search()
#14 /var/www/clients/client3/web22/web/releases/207/vendor/amasty/shopby/Model/Layer/Filter/Category.php(512): Amasty\Shopby\Model\Layer\Filter\Category->getSearchResult()
#15 /var/www/clients/client3/web22/web/releases/207/vendor/amasty/shopby/Model/Layer/Filter/Category.php(367): Amasty\Shopby\Model\Layer\Filter\Category->getFacetedData()
#16 /var/www/clients/client3/web22/web/releases/207/vendor/amasty/shopby/Model/Layer/Filter/Category.php(288): Amasty\Shopby\Model\Layer\Filter\Category->getExtendedCategoryData()
#17 /var/www/clients/client3/web22/web/releases/207/vendor/magento/module-catalog/Model/Layer/Filter/AbstractFilter.php(159): Amasty\Shopby\Model\Layer\Filter\Category->_initItems()
#18 /var/www/clients/client3/web22/web/releases/207/vendor/amasty/shopby/Model/Layer/Filter/Category.php(274): Magento\Catalog\Model\Layer\Filter\AbstractFilter->getItems()
#19 /var/www/clients/client3/web22/web/releases/207/vendor/amasty/shopby/Model/Layer/GetFiltersExpanded.php(79): Amasty\Shopby\Model\Layer\Filter\Category->getItemsCount()
#20 /var/www/clients/client3/web22/web/releases/207/vendor/amasty/shopby/Block/Navigation/FilterCollapsing.php(36): Amasty\Shopby\Model\Layer\GetFiltersExpanded->execute()
#21 /var/www/clients/client3/web22/web/releases/207/vendor/amasty/shopby/view/frontend/templates/layer/filter_collapsing.phtml(20): Amasty\Shopby\Block\Navigation\FilterCollapsing->getFiltersExpanded()
#22 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('...')
#23 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render()
#24 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent()
#25 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#26 /var/www/clients/client3/web22/web/releases/207/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins()
#27 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor->render()
#28 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView()
#29 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Framework\View\Element\Template->_toHtml()
#30 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#31 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#32 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Element\AbstractBlock->toHtml()
#33 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/Interception/Interceptor.php(138): Amasty\Shopby\Block\Navigation\FilterCollapsing\Interceptor->___callParent()
#34 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/Interception/Interceptor.php(153): Amasty\Shopby\Block\Navigation\FilterCollapsing\Interceptor->Magento\Framework\Interception\{closure}()
#35 /var/www/clients/client3/web22/web/releases/207/generated/code/Amasty/Shopby/Block/Navigation/FilterCollapsing/Interceptor.php(23): Amasty\Shopby\Block\Navigation\FilterCollapsing\Interceptor->___callPlugins()
#36 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Layout.php(578): Amasty\Shopby\Block\Navigation\FilterCollapsing\Interceptor->toHtml()
#37 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#38 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#39 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#40 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#41 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#42 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#43 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#44 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#45 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#46 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#47 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#48 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#49 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#50 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#51 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#52 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#53 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#54 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#55 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#56 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#57 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout->renderElement()
#58 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#59 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent()
#60 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#61 /var/www/clients/client3/web22/web/releases/207/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout\Interceptor->___callPlugins()
#62 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Result/Page.php(260): Magento\Framework\View\Layout\Interceptor->getOutput()
#63 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render()
#64 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult()
#65 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent()
#66 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}()
#67 /var/www/clients/client3/web22/web/releases/207/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(32): Magento\Framework\View\Result\Page\Interceptor->___callPlugins()
#68 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult()
#69 /var/www/clients/client3/web22/web/releases/207/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#70 /var/www/clients/client3/web22/web/releases/207/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#71 {main} [] []

### Additional information

This error was showing in magento 2.4.4 then we saw that this error is fixed in magento 2.4.5
https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-5.html#search

but the error is still showing.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-09-23 11:14
Hi @mohammedTBB ,
Verified the issue on both Magento 2.4.5 and 2.4-develop instances but the issue is not reproducible.
Layered Navigation "filterable with results" is working fine for 'Manufacturer' attribute on frontend and no errors/ exceptions observed in the logs. Kindly check if any 3rd party extensions / modules enabled is causing this issue and recheck on Magento 2.4-develop instance and elaborate steps if the issue is still reproducible.
![image](https://user-images.githubusercontent.com/60198231/191948697-bbd3872d-45a0-4635-9c15-a2ec53a26134.png)
![image](https://user-images.githubusercontent.com/60198231/191948857-f8732de8-11e4-4087-a824-303a5254b51d.png)

Thank you.

**Comment by engcom-November** [comment] 2022-10-10 06:04
Hi @mohammedTBB ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-10-10 06:04 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.5
