### ISSUE TITLE
Magento 2 login custumer and add product to cart in chrome

### ISSUE THREAD

**Issue by timri86** [magento/magento2#8941] opened 2017-03-19 10:21 UTC
Hello,
After installation of magento 2.1.4, everything works very well on other browsers. I tried to check on chrome.
1) When a client registers, it is automatically connected but when it disconnects and tries to reconnect, nothing happens (redirection to the login page). I tried to lengthen the lifetime of cookies no change.
2) On the product display page when it clicks on Add to cart, an add notification is displayed but the product is not added to the cart.
I point out that everything walks nikel on other browsers.
I need help please

**Comment by korostii** [comment] 2017-03-20 10:30
If you are looking for an advice please refer to the[ Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. As GitHub issue tracker is intended for technical issues only.
The issues which cannot be consistently reproduced on a clean installation of Magento CE aren't likely to get resolved in here.
Thus if you are reporting a technical issue, please try add as much information as possible, including the environment you use, 3rd party themes and modules installed, preconditions, steps to reproduce, etc. in order simplify attempts in reproducing it. Screenshots and stack trace from browser console (if any) are also helpful.

**Comment by veloraven** [comment] 2017-06-27 11:17
@timri86 thank you for your feedback.
If you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
If you want to report several issues please create separate GitHub issue for each of them.

**Closed as completed** 2017-09-11 21:05 UTC
Labels: Progress: needs update, Issue: Format is not valid
