### ISSUE TITLE
Magento 2.2.4 bug: ConfigurableProduct doesn't exist

### ISSUE THREAD

**Issue by shansari25** [magento/magento2#26315] opened 2020-01-08 17:50 UTC
**Migrated working code from AWS to Google Cloud and not able to run the website - getting compilaton error -**                                                                                                                                              `_[InvalidArgumentException]                                                                                                                  Plugin class Magento\ConfigurableProduct\Model\Quote\Item\QuantityValidator\Initializer\Option\Plugin\ConfigurableProduct doesn't exist_  `

did the setup:uprade and static content deployment first and then doing compilation

on website still getting 500 internal server error

Pls help resolve the issue

**Comment by shansari25** [comment] 2020-01-08 17:53
Summary of the issue

**Migrated working code from AWS to Google Cloud and not able to run the website - website not working so ran setup:upgrade and static content  deploy and getting error in compilation command
gto following error**

- [InvalidArgumentException] Plugin class Magento\ConfigurableProduct\Model\Quote\Item\QuantityValidator\Initializer\Option\Plugin\ConfigurableProduct doesn't exist 

  Information on your environment

Magento 2.2.4

  Steps to reproduce

php -dmemory_limit=5G bin/magento  setup:di:compile
Compilation was started.
  Expected and actual results


- [InvalidArgumentException] Plugin class Magento\ConfigurableProduct\Model\Quote\Item\QuantityValidator\Initializer\Option\Plugin\ConfigurableProduct doesn't exist

**Comment by engcom-Hotel** [comment] 2020-01-17 11:30
Hello @shansari25 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the latest 2.4-develop branch by provided steps.

We are closing this issue due to branch `2.2-develop` was closed and
> Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.

 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

Thanks for your report!

**Closed as completed by engcom-Hotel** 2020-01-17 11:30 UTC
Labels: Issue: Format is not valid, Reported on 2.2.x
