### ISSUE TITLE
Can't add product images roles with $product->addImageToMediaGallery 

### ISSUE THREAD

**Issue by pavitrapapiofficial** [magento/magento2#38389] opened 2024-01-29 08:19 UTC
### Preconditions and environment

- Magento version: 2.4.6
- product image is saved but roles are unassigned.
`foreach ($images as $image) {
            $imagePath = $this->importImage->import(ImportImageInterface::TYPE_URL, $image['url']);
            $mediaAttribute = isset($image['types']) ? array_map('strtolower', $image['types']) : null;
            // $product->addImageToMediaGallery($imagePath, $mediaAttribute, false, false);
            $product->addImageToMediaGallery($imagePath, array('image', 'small_image', 'thumbnail','swatch_image'), false, false);
        }
        $product->save();`

### Steps to reproduce

Try to add product images programatically.

### Expected result

Product thumbnail should be visible in admin.
product image should be visible across the pages on the frontend.

### Actual result

only base image is showing no small and thumbnails are visible.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by pavitrapapiofficial** [comment] 2024-01-30 06:31
Any update?

**Comment by engcom-November** [comment] 2024-01-31 12:30
Hello @pavitrapapiofficial,

Thank you for the report and collaboration!

This issue is the duplicate of https://github.com/magento/magento2/issues/30385 which is already confirmed, hence closing this issue.

Thank you.

**Closed as completed by engcom-November** 2024-01-31 12:30 UTC
Labels: Triage: Dev.Experience, Issue: ready for confirmation, Reported on 2.4.6
