### ISSUE TITLE
Configurable Products still shows Special price instead of old price after the special to date passed.

### ISSUE THREAD

**Issue by vishveskrish** [magento/magento2#9273] opened 2017-04-17 13:36 UTC
### Preconditions
1. Magento CE 2.1.6 without sample data is installed.

### Steps to reproduce
1. Login to admin-panel.
2. Open any configurable product.Update all the associated products special price with special To ( 10 Days before or any random past date.) and From date ( 5 Days before or any random past Date).
3. Now open the product in front-end and check the configurable product price. 

### Expected result
1. It should display only old price instead of special price.

### Actual result
1. It is showing special price. 

Here is the example,

1. We have product A is configurable and products aa,bb,cc are its assosiated products,
2. The price of the products aa, bb, cc is $40.00 and special price for the this products $20.00 with special to and from both date set as past date.(From 20 JAN 2016 to 22 JAN 2016). so special price of the product should be enable only for the time period from 20 JAN and 22 JAN 2016. 

Now, Current date is 17th April 2017,It is showing the $20 as configurable product price.

**Comment by Stas94** [comment] 2017-07-03 08:50
@vishveskrish We cannot reproduce this issue as described. Please provide the detailed steps we must follow to reproduce this issue. In addition, identify the web server you are running, the versions of PHP and MySQL, and any other information needed to reproduce your issue.

**Comment by veloraven** [comment] 2017-07-03 11:29
@vishveskrish thank you for your report.
I'm closing this issue as corresponding internal ticket MAGETWO-70386 was created for the issue #9910.

**Closed as completed by veloraven** 2017-07-03 11:29 UTC
Labels: bug report, Component: Tax
