### ISSUE TITLE
Bad formatting of telephone on email template.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#36001] opened 2022-08-23 18:28 UTC
### Preconditions and environment

- 2.4.5
- Fresh Install

### Steps to reproduce

Put a telephone number with spaces for example +1 555 555 on Store Info (via admin panel)
And then load an email template (for example, new credit memo and preview it) and mouse over the telephone link (or click), it will be invalid, the system add a "20" where the spaces are.

### Expected result

The result on click will be a valid phone call.

### Actual result

Invalid phone call.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-08-24 08:51
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-08-24 11:48
Hi @hagotupagina-spa,


Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop branch and 2.4.5 project-community-edition as well but the issue is not reproducible.

Kindly refer the screenshots.

<img width="930" alt="1736 1" src="https://user-images.githubusercontent.com/51680745/186410626-7a332322-091c-491a-9abb-c0c5b8efeaf6.png">


<img width="932" alt="1736 2" src="https://user-images.githubusercontent.com/51680745/186410720-0d3fe66d-307a-4929-a9c6-cd4678dbb0d2.png">


<img width="934" alt="1736 3" src="https://user-images.githubusercontent.com/51680745/186410758-21f50944-5939-473a-8686-6767d8475a9c.png">


Let us know we have missing anything.


Thanks.

**Comment by hagotupagina-spa** [comment] 2022-08-24 13:53
Attached screenshots. With an actuall call and refference ofthe issue
![222](https://user-images.githubusercontent.com/105003495/186436236-d3fb69db-26fd-4a5c-9293-a4e06aadfb60.jpg)
![Screenshot_20220824-095001_Phone](https://user-images.githubusercontent.com/105003495/186436250-d70e7994-7a86-40f8-83b8-c4b96b0201d0.jpg)
.

**Comment by engcom-Bravo** [comment] 2022-08-26 08:34
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-08-26 12:50
Hi @hagotupagina-spa,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop branch and 2.4.5 project-community-edition as well but the issue is reproducible.

Kindly refer the screenshots.


1.Adding a telephone number with spaces(+1 555 555) on Store information

<img width="930" alt="1736 1" src="https://user-images.githubusercontent.com/51680745/186901888-54b489c5-8637-41fa-a0c6-b8d37fe7d436.png">



2.Loading an email template(new credit memo) and Preview it


<img width="932" alt="1736 2" src="https://user-images.githubusercontent.com/51680745/186902215-bc422d19-81f3-4de2-8d3c-631ac5e44c39.png">



<img width="936" alt="1736 4" src="https://user-images.githubusercontent.com/51680745/186902905-5d2a7561-ffed-4303-9fd8-e0f2eb68431b.png">



3.The system is adding "20" where the spaces are,


![phone](https://user-images.githubusercontent.com/51680745/186903053-5c45e3c1-3570-4c3a-ba03-709f091c6bf3.jpg)



Hence confirming the issue.


Thanks.

**Comment by pavel77718** [comment] 2022-08-30 08:02
@magento I am working on this

**Comment by pavel77718** [comment] 2023-10-13 15:35
I found a solution to this issue. But since the problem occurs when the third-party library ezyang/htmlpurifier is running, I could not add PR to magento to solve the problem. The latest version also does not fix the problem with spaces in href.
You can fix the problem by making a patch. You need to add the line 
`$string = str_replace(' ', '', $string);`
on line 62
![image](https://github.com/magento/magento2/assets/57960172/9ddd0500-50b9-4144-b1bd-74d09857f021)

**Comment by engcom-Bravo** [comment] 2024-10-21 06:01
Hi,

Thanks for your reporting and collaboration.

We have reverified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="1381" alt="Screenshot 2024-10-21 at 11 26 34" src="https://github.com/user-attachments/assets/fcd33833-66de-456e-bbef-f96d5c4ffed5">



Now the system does not adding 20 in the place of spaces.Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-10-21 06:01 UTC
Labels: Issue: Confirmed, Component: Email, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Admin UI, Reported on 2.4.5
