### ISSUE TITLE
"Area code not set" when running console command

### ISSUE THREAD

**Issue by jsakars** [magento/magento2#5614] opened 2016-07-13 10:50 UTC
## Steps to reproduce
1. Install Magento 2.1
2. Have custom module which has console command to import products from 3rd party providers
3. Run console command
## Expected result
1. Products are stored
## Actual result
1. Error occurs - `Area code not set: Area code must be set before starting a session.`

If I set `$state->setAreaCode('adminhtml');` - product import goes fine but then `setup:di:compile` gives `Area code is already set` error.
Version 2.0.7 had the same issue with the import command but compile command still worked fine.

If I comment out `$product->save();` then such error is not present.

**Comment by andimov** [comment] 2016-08-10 11:04
@werdlv 
Can't reproduce this bug.
Please, add additional info for reproducing or check custom module.

**Comment by jsakars** [comment] 2016-08-12 17:41
@andimov not sure what other additional info can I add

**Comment by slopukhov** [comment] 2016-11-29 13:50
@werdlv thank you for your feedback.
The error may be at the custom module realization, please add describe or example where it sets $state->setAreaCode

**Comment by vzabaznov** [comment] 2016-12-13 09:23
Hi @werdlv , closed as we don't receive update more than 2 week, feel free to write here/reopen or to open new issue

**Closed as completed by vzabaznov** 2016-12-13 09:23 UTC
Labels: bug report, Progress: needs update
