### ISSUE TITLE
[Performance] Redis has more Network Traffic 

### ISSUE THREAD

**Issue by larsroettig** [magento/magento2#21334] opened 2019-02-19 12:10 UTC
### Preconditions (*)

1.  Install Magento 2.1.15  with  ```bin/magento setup:perf:generate-fixtures ./setup/performance-toolkit/profiles/ee/medium.xml ```
2. Install Magento 2.1.8  with  ```bin/magento setup:perf:generate-fixtures ./setup/performance-toolkit/profiles/ee/medium.xml ```
3. Setup redis for config and caching

### Steps to reproduce (*)

1. bin/Magento  c:f 
2. Profile https://2.1.15.test/category-1.html
--
1. cd  Magento 2.1.8 && bin/magento  c:f 
2. Profile https://2.1.8.test/category-1.html

### Expected result (*)

1. Not more Network Traffic 

### Actual result (*)

1. Currently you see 136% on Category more Network Traffic 
![comparison_from_https___2_1_8_test_category-1_html_to_https___2_1_15_test_category-1_html_-_blackfire](https://user-images.githubusercontent.com/5289370/53013833-f5573900-3446-11e9-81dd-4f8d37cb26e8.png)

Url:  https://blackfire.io/profiles/compare/cfe9e28e-d5c1-466e-8467-344399c6939e/graph

###### Main Problem in 2.1.15 is the new Encryptor the it increases the network traffic +30% this is called up 5 dependent on site

Class: [\Magento\Config\App\Config\Type\System](https://github.com/magento/magento2/blob/532f4769a218b2e5720a6cf7d6979b69fadc60e7/app/code/Magento/Config/App/Config/Type/System.php#L228) 

The Problem is worst if you have many configurations because the implementation  of the Encryptor is exponentially

A Cart site call 5 times Redis give my all config data (edited) 

If you have a Redis Cluster not on the same server this add network latency and if you have many request you can't handle this network traffic

Currently, i reproduce this issue in **2.1.x** I add information about **2.3.x**

**Comment by magento-engcom-team** [comment] 2019-02-19 12:11
Hi @larsroettig. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@larsroettig do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by kandy** [comment] 2019-02-19 18:12
@larsroettig, I agree that increasing of data stored in the cache is bad behavior. 
But we decided on it due to security and performance reason. 
Do you think there a way how to better implement it?

**Comment by larsroettig** [comment] 2019-02-19 18:28
Hi @kandy, 
most Redis clusters are behind a Firewall I understand the point with security. Because if the Redis Content for whatever reason is stolen passwords are not encrypted. 

A private ```$cache``` can help because it is a singleton object for a checkout site you ask 5 times Redis what is the config for this one request. 

Maybe we can spilt the config by ```obscure``` than it will be not so worst.

**Comment by david-fuehr** [comment] 2019-02-25 21:59
Hi @kandy,

since the 2.1.14 update we experienced a massive network traffic increase in our redis node. After some investigation we could identify these changes as root cause.

As the effects are bigger than expected, I will provide you some data:
1. with active and warmed caches the store configuration read from redis is about 33% bigger than without encryption
1. in our AWS setup the _network in (bytes)_ is increased by about 50% with moderate request count and system config encryption
1. with higher request count and a complete cache drop the same metric is about 8 times higher with encryption of system config

To proof that the introduction of encryption in `\Magento\Config\App\Config\Type\System` causes this effect, we reverted the changes in this class and could completely revert the network traffic increase.

Considering what @larsroettig said, I currently see two possible solutions:
1. Sensitive data such as passwords etc could be held in an additional object that is stored encrypted in redis.
1. A configuration in `env.php` could determine, whether the system configuration is being encrypted or not.

I tend to prefer the latter solution. It seems simpler and should be suitable for basic Magento setups (shared hosting, no firewall, low to medium traffic) to ensure safety with encrypted system configuration as well as more complex setups (managed hosting, firewall, medium to high traffic) without encryption.

What do you think?

**Comment by magento-engcom-team** [comment] 2019-02-25 22:01
Hi @buskamuza. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-02-27 16:19
Hi @kandy. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by PascalBrouwers** [comment] 2019-03-15 11:00
I also see allot of calls to $this->encryptor in combination with Redis. We are testing now without Redis to see the performance difference.

**Comment by sdzhepa** [comment] 2019-10-04 19:55
Hello @larsroettig 

Just received answer from Magento architect  and this issue should be closed because it is expected behavior

**Closed as completed by sdzhepa** 2019-10-04 19:55 UTC
Labels: Release Line: 2.1, Reproduced on 2.1.x, Issue: Format is valid
