### ISSUE TITLE
Region is added in the email template although deactivated for current country.

### ISSUE THREAD

**Issue by cptX** [magento/magento2#37471] opened 2023-05-08 13:53 UTC
### Preconditions and environment

- Magento version 2.4.6

I have a website with 2 storeviews Greek and English. I have disabled the region for Greece, so I don't need it to be visible to customers.
Here I found 2 problems:
1. Emails are sent to customers with my shop address including the Region.
2. Region is not translated in Greek

This is an example of how the address of my shop is included in the email sent to customers:

test.xxx
Δοκιμαστική Διεύθυνση 12
Αθήνα, **Attiki**, 12345
Ελλάδα

As you see above the region (Here Attiki) is not translated, and also I don't want it to be visible at all. I have disabled the usage of Region for Greece so customers are not asked for region when entering their addresses but the system forces me to include the shop region and then uses this region in the address written in the emails sent to the customers.

I know I could create a new email template to remove the region from the emails, but I still consider this a bug because I don't need regions at all in my country and also there is no way to translate it...

### Steps to reproduce

1. Create two store views, one greek and one english for example
2. Disable the usage of region for Greece.
3. Make a purchase in the greek store.
4. The email sent will include the shop address as the following example:

test.xxx
Δοκιμαστική Διεύθυνση 12
Αθήνα, **Attiki**, 12345
Ελλάδα

### Expected result

Address of the shop should not include the region if it is disabled for this country.
As a secondary solution, this region should at least be translated.

Address should look like this:

test.xxx
Δοκιμαστική Διεύθυνση 12
Αθήνα, **Αττική**, 12345
Ελλάδα

or like this

test.xxx
Δοκιμαστική Διεύθυνση 12
Αθήνα, 12345
Ελλάδα

### Actual result

Now address is shown like this

test.xxx
Δοκιμαστική Διεύθυνση 12
Αθήνα, **Attiki**, 12345
Ελλάδα

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment] 2023-05-08 14:09
region you can find it here
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Directory/Setup/Patch/Data/AddDataForGreece.php#L68

**Comment by mrtuvn** [comment] 2023-05-08 15:04
not try this but you can config country in Stores > Configuration > General (Default country / Allows country) following scope website or store view

**Comment by mrtuvn** [comment] 2023-05-10 01:33
yeap looks like a internal code issue

**Comment by mrtuvn** [comment] 2023-05-10 01:34
when i checked table directory_country_region_name i see entry locale come along with Region name but i'm not too sure internal local process with locale or not

**Comment by cptX** [comment] 2023-05-10 06:19
Which file is responsible for producing the address in the email template? Maybe there we should implement a check if Region is used in our country or not. Or we should make Region field in the shop address optional. Now in store information in configuration it is requiring it!

**Comment by mrtuvn** [comment] 2023-05-10 06:54
All process related with email order/invoice data come from module Magento_Sales. This is default function. All data from order (order data, customer address v.v.) will get and put into your email send to end-user.
Hope this can help you go to right track

**Comment by engcom-Bravo** [comment] 2023-05-18 13:15
Hi @cptX,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Create two store views, one greek and one english for example
- Disable the usage of region for Greece.
- Make a purchase in the greek store.
- The email sent will include the shop address as the following example:



We have created order from greek store view.


<img width="1063" alt="Screenshot 2023-05-18 at 3 59 22 PM" src="https://github.com/magento/magento2/assets/51680745/b5c8f8d7-c6e8-49a9-bceb-d4537881220a">


We have disabled greek locale for greek store view and greek region is not included in the mail.



<img width="1073" alt="Screenshot 2023-05-18 at 3 44 08 PM" src="https://github.com/magento/magento2/assets/51680745/0336b382-1833-4fbe-b20d-8cf0289edc9b">




Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by cptX** [comment] 2023-05-18 13:36
@engcom-Bravo I'm afraid you misunderstood what I mean. In the screenshots you gave you don't even show the address of the shop that normally is on the footer of the email. You are showing only the address of the customer. I'm talking about the address of the shop (seller).

**Comment by cptX** [comment] 2023-05-18 13:41
Please check the image. Probably you misunderstood. I'm referring to the shop address not the customer address
![region_in_email](https://github.com/magento/magento2/assets/9040042/035471e8-c070-41e4-941b-f3a82592b470)

**Comment by engcom-Bravo** [comment] 2023-06-23 11:59
Hi @cptX,

Thanks for your update.

We will get the Region/State as per listed in the configuration.


<img width="1237" alt="Screenshot 2023-06-23 at 3 29 37 PM" src="https://github.com/magento/magento2/assets/51680745/02cdcbe1-d3a1-430f-b60e-631c0d3944bb">



<img width="1040" alt="Screenshot 2023-06-23 at 3 29 25 PM" src="https://github.com/magento/magento2/assets/51680745/aa768e06-7e9c-4d2c-b3d6-bdb24691d62b">




<img width="822" alt="Screenshot 2023-06-23 at 3 29 18 PM" src="https://github.com/magento/magento2/assets/51680745/f566191b-5556-4a6d-ab0d-354677246ad8">


Here Attiki is same as Attiki listed in Region/State Configuration.For other languages also it is working as expected we are getting Region/State from the configuration itself.


Thanks.

**Comment by cptX** [comment] 2023-06-23 15:12
Hi I'm not sure you understand the problem! The problem is that these regions are not written in the greek language, and it's not possible to translate them!

**Comment by engcom-Bravo** [comment] 2023-06-26 13:03
Hi @cptX,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Create two store views, one greek and one english for example
- Disable the usage of region for Greece.
- Make a purchase in the greek store.



We have disabled Greek language and we have placed order from greek store and greek is not getting translated.



<img width="1064" alt="Screenshot 2023-06-26 at 1 40 42 PM" src="https://github.com/magento/magento2/assets/51680745/e979af56-4c26-40ad-8d68-c2425f2ef2f5">



We are getting Greece as region form store information because we have configured as greece please try to use another country.There is no store view level configuration for store information.as we can see greece is not getting translated.

<img width="965" alt="Screenshot 2023-06-26 at 1 42 02 PM" src="https://github.com/magento/magento2/assets/51680745/9e4b536b-9841-475c-a1c2-181accc463a3">



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-07-07 05:16
Hi @cptX,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-07-07 05:16 UTC
Labels: Issue: needs update, Reported on 2.4.6

**Comment by cptX** [comment] 2023-07-07 08:35
Problem is not solved, but I had to found a workaround by creating another template and removing the region completely. Magento doesn't allow the regions to get translated so I had to remove them...
If anybody is still interested please request to reopen the issue...
