### ISSUE TITLE
domain .shop not accepted

### ISSUE THREAD

**Issue by justsign** [magento/magento2#8068] opened 2017-01-07 14:57 UTC
I try to add some default email addresse to magento 2 and get a error on general contact (all contats ) "Please correct the email address: 'rob@justsign.shop'".
I install magento 2 on my domain https://www.justsign.shop

Please some advice how to fix this error
![schermafbeelding 2017-01-07 om 15 51 40](https://cloud.githubusercontent.com/assets/10490535/21742578/0dc0d1f6-d4f2-11e6-81c5-e3945a0f87f9.png)

**Comment by hostep** [comment] 2017-01-08 09:19
This has been reported multiple times, please first try searching for an issue before creating a new one :)

All of those issues are getting linked into this one: https://github.com/magento/magento2/issues/4547

**Comment by justsign** [comment] 2017-01-08 12:08
Thanks for your answer. I din't find it.
But is there a solution for it?

**Comment by korostii** [comment] 2017-01-10 17:21
Well, it seems to come down to updating the dependency on zend-validator, and that seems to be at least considered (see #8070). But if I were you... I wouldn't be too optimistic about that.
With current pace, that update might get released in a year or so after getting done, so in the meantime you might want to start looking for a workaround such as [this one](https://github.com/magento/magento2/issues/4547#issuecomment-271193776).

**Comment by pboisvert** [comment] 2017-01-20 20:45
closing as duplicate of #4547

**Closed as completed by pboisvert** 2017-01-20 20:45 UTC
