### ISSUE TITLE
B2B 1.3.1 - 404 for company site

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#32917] opened 2021-04-30 13:54 UTC
### Preconditions (*)

1. 2.4.2 EE
2. B2B 1.3.1
3. Production Mode

### Steps to reproduce (*)

I don't know how to reproduce the error.

It works on a fresh magento 2.4.2.

I installed the B2B 1.3.1 on my project and enabled "Enable Company" in **System -> Configuration -> General -> B2B features** 

If I now try to open the Company area at "Customers -> Companies" then I just get a 404 site.

There is no error getting logged on the server and also no error in var/log/exception.log

### Expected result (*)

1. Should load

### Actual result (*)

1. 404

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment] 2021-05-28 13:20
Hi @Eddcapone, Seems it is a permission issue in Admin, permission was not enabled. Kindly verify once again
Kindly confirm on this.

**Comment by Eddcapone** [comment] 2021-06-01 12:52
@engcom-Alfa , Unfortunately we decided to uninstall the extension again, since it was not working, so I cant test it.

**Comment by engcom-November** [comment] 2021-09-30 10:54
Hi @Eddcapone ,
Verified the issue on Magento 2.4-develop branch having B2B enabled but the issue is not reproducible:
Companies page is loaded as expected:
![image](https://user-images.githubusercontent.com/60198231/135441968-bf4b6ea4-4e5d-4726-b8c9-f0d7cb13bad9.png)

If you want to enable the B2B Shared Catalog feature, you must start the corresponding message consumers after installation. Kindly recheck status of message consumers:  >bin/magento queue:consumers:list and restart if required.
 [Ref docs](https://devdocs.magento.com/extensions/b2b/)
We are closing this issue. Please Reopen/create new issue if you are still facing the issue and provide missing steps if any.
Thank you.

**Closed as completed by engcom-November** 2021-09-30 10:54 UTC
Labels: Issue: needs update
