### ISSUE TITLE
2.0.0 to 2.0.1 failed

### ISSUE THREAD

**Issue by beckzg** [magento/magento2#3112] opened 2016-01-25 01:24 UTC
Hi,

  i tried to upgrade my clean 2.0.0 install to 2.0.1 with system update, but it fails:

[2016-01-25 01:57:06 CET] Job "maintenance_mode {"enable":true}" has been started
[2016-01-25 01:57:06 CET] Magento maintenance mode is enabled.
[2016-01-25 01:57:06 CET] Job "maintenance_mode {"enable":true}" has successfully completed
[2016-01-25 01:57:06 CET] Job "update {"components":[{"name":"magento/product-community-edition","version":"2.0.1"}]}" has been started
[2016-01-25 01:57:06 CET] Starting composer update...
[2016-01-25 01:57:06 CET] An error occurred while executing job "update {"components":[{"name":"magento/product-community-edition","version":"2.0.1"}]}": Could not complete update {"components":[{"name":"magento/product-community-edition","version":"2.0.1"}]} successfully: Command "require" failed: ./composer.json has been updated

  [ErrorException]
  chdir(): Permission denied (errno 13)

I tried to chmod -R 777 and chown -R www:www but the same error!
I installed from archive Magento-CE-2.0.0-2015-11-17-05-56-31.tar.bz2.

The rollback failed:

[2016-01-25 02:30:05 CET] Job "rollback {"backup_file_name":"/var/db/www/domains/prod/var/backups/1453683316_filesystem_code.tgz"}" has been started
[2016-01-25 02:30:05 CET] Restoring archive from "/var/db/www/domains/prod/var/backups/1453683316_filesystem_code.tgz" ...
[2016-01-25 02:38:28 CET] Job "rollback {"backup_file_name":"/var/db/www/domains/prod/var/backups/1453683316_filesystem_code.tgz"}" has successfully completed
[2016-01-25 02:38:28 CET] Job "rollback {"backup_file_name":"/var/db/www/domains/prod/var/backups/1453683316_filesystem_media.tgz"}" has been started
[2016-01-25 02:38:28 CET] Restoring archive from "/var/db/www/domains/prod/var/backups/1453683316_filesystem_media.tgz" ...
[2016-01-25 02:38:28 CET] Job "rollback {"backup_file_name":"/var/db/www/domains/prod/var/backups/1453683316_filesystem_media.tgz"}" has successfully completed
[2016-01-25 01:39:01 UTC] Job "setup:rollback {"backup_file_name":"/var/db/www/domains/prod/var/backups/1453683316_db.gz"}" has started
DB rollback is starting...

[2016-01-25 01:39:01 UTC] An error occurred while executing job "setup:rollback {"backup_file_name":"/var/db/www/domains/prod/var/backups/1453683316_db.gz"}": Could not complete setup:rollback {"backup_file_name":"/var/db/www/domains/prod/var/backups/1453683316_db.gz"} successfully: ltrim() expects parameter 1 to be string, object given

Kind Regads,
beckzg

**Comment by mazhalai** [comment] 2016-01-25 14:20
@beckzg thank you for reporting this issue, but this is a duplicate of #3056. Please watch that thread for updates. Closing this one.

**Closed as completed by mazhalai** 2016-01-25 14:20 UTC
