### ISSUE TITLE
New Checkout Shipping Address Has Company After Changing Show Company to No

### ISSUE THREAD

**Issue by moranotcsos** [magento/magento2#33729] opened 2021-08-09 17:34 UTC
I am unable to reopen issue #33663 so I am resubmitting the request here in hopes of clearing up the misunderstanding.

### Steps to reproduce (*)

1. In the admin panel, Customer Configuration - change Show Company to Optional, press Save Config, and then clear cache.
2. Create a customer.
3. Login as the customer and add separate billing and shipping addresses with a company on both.
4. In the admin panel, change Customer Configuration - Show Company to No, press Save Config, and then clear cache.
5. Front-end - Login as Customer - Add a product to Cart - Checkout - go to Payment Step - Go back again to Shipping step - Add different new Shipping Address and place Order
8. In the Magento database, check the address in the sales_order_address table and in the customer_address_entity table.

### Expected result (*)

1. After placing the order, the shipping address should not have a shipping company on it on the customer address or on the order in the database.

### Actual result (*)

1. After placing the order, the shipping address has the previous shipping address's company on it in the database. You will only see it **in the Magento database** in the company field on the order and on the customer address.

**Comment by engcom-November** [comment] 2021-08-11 09:46
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible in DB as well:
Steps performed:
Stores - Configuration - Customers - Customer Configuration - Show Company - Set to Optional and Save
Reindex and clear cache
Create Customer Account from front end and signin
Added different Shipping Address and Billing Address for the customer from fronend with Company name and saved.
Stores - Configuration - Customers - Customer Configuration - Show Company - Set to No and Save
Reindex and clear cache
Login as Customer - Add a product to Cart - Checkout - Add different Shipping Address and placed Order
Checked DB tables: sales_order_address and customer_address_entity tables
**No issue:**  Company is NULL in both the tables
![image](https://user-images.githubusercontent.com/60198231/129007262-f4645cfd-829a-4a66-909a-d0d1e61a24b7.png)
![image](https://user-images.githubusercontent.com/60198231/129007516-48b7715b-3292-4c6e-9eac-e9fcf8419831.png)

Note: This issue also not observed when Shipping and Billing Address are saved from Admin - Customers page
Also This issue is not observed when logged in as Customer from admin (Customers - All Customers - Edit Customer - Login as Customer and placed order with different shipping address)
@moranotcsos kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by moranotcsos** [comment] 2021-08-11 15:08
@engcom-November 

I realized my mistake. For Step 7, it should be:

Login as Customer - Add a product to Cart - Checkout **- Go to Payment Step - Go Back to Shipping Step -** Add different Shipping Address and placed Order.

I was able to reproduce this on 2.4.3. Let me know if you are able to reproduce this now.

**Comment by moranotcsos** [comment] 2021-08-13 18:13
@engcom-November

I just wanted to follow up and confirm you received my previous response.

I realized my mistake and for Step 7, it should be:

Login as Customer -> Add a product to Cart -> Checkout -> Go to Payment Step -> Go Back to Shipping Step -> Add different Shipping Address and place order.

I was able to reproduce this on 2.4.3. Let me know if you are able to reproduce this now.

**Comment by engcom-November** [comment] 2021-08-16 11:45
Verified the issue again on Magento 2.4-develop branch with missing steps provided and the issue is reproducible now:
**Steps to reproduce:**
1. Stores - Configuration - Customers - Customer Configuration - Show Company - Set to Optional and Save
 2. Reindex and clear cache
 3. Create Customer Account from front end and sign in
 4. Added different Shipping Address and Billing Address for the customer from front-end/admin with Company name for both and saved.
 5. Stores - Configuration - Customers - Customer Configuration - Show Company - Set to No and Save
 6. Reindex and clear cache
 7. Front-end - Login as Customer - Add a product to Cart - Checkout - go to Payment Step - Go back to Shipping step - Add different Shipping Address and place Order
8 Check DB tables: sales_order_address and customer_address_entity tables
Issue: After placing the order, the shipping address has the previous shipping address's company on it in the database
![image](https://user-images.githubusercontent.com/60198231/129558509-4f65301e-6023-4ac4-a63d-fed945511349.png)
![image](https://user-images.githubusercontent.com/60198231/129558545-f0c785d9-61f6-4ade-be48-47ba19862b6b.png)

**Comment by magento-engcom-team** [comment] 2021-08-16 11:51
:white_check_mark: Confirmed by @engcom-November 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-43097` were created

**Issue Available**: @engcom-November, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by moranotcsos** [comment] 2021-09-27 18:51
Hello,

I just wanted to follow up to see if there has been any progress on the matter. I see it's in the triage board and just wanted to check if we may be getting a patch soon. While it was replicated on 2.4.3, the client we have is on 2.4.1 (we can upgrade to 2.4.2-p2 if necessary) and upgrading to 2.4.3 is not possible with our current setup.

**Comment by jzarowny** [comment] 2021-10-03 18:53
@magento I am working on this

**Comment by jzarowny** [comment] 2021-10-03 18:53
@magento add to contributors team

**Comment by jzarowny** [comment] 2021-10-03 18:54
@magento I am working on this

**Closed as completed** 2022-10-03 06:43 UTC
Labels: Issue: Confirmed, Component: DB, Reproduced on 2.4.x, Priority: P2, Progress: done, Reported on 2.4.2, Area: Order

**Comment by engcom-Hotel** [comment] 2022-10-06 09:11
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-838 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-838&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks
