### ISSUE TITLE
creating attributes programmatically bypasses attribute_code length and cannot edit

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#24806] opened 2019-10-01 10:09 UTC
### Preconditions (*)
1. Magento 2.3.1
2. Create an attribute with a long name programmatically e.g. io_timestamp_sync_product_details

### Steps to reproduce (*)
1. Create an attribute with a long name programmatically e.g. io_timestamp_sync_product_details
2. Try to edit / update the attribute from backend

### Expected result (*)
There are two cases here
1. First, the attribute should throw an error during creation that the attribute code is too long.

Second case
2. The created attribute is not validated against code length and saves correctly. 

### Actual result (*)
1. Attribute is created in the backend
2. User cannot edit the attribute and an error is thrown which is misleading

`Attribute code "io_timestamp_sync_product_details" is invalid. Please use only letters (a-z or A-Z), numbers (0-9) or underscore(_) in this field, first character should be a letter.`

![image](https://user-images.githubusercontent.com/20220341/65953418-9467f880-e44c-11e9-9b8e-a680b8b67f83.png)

**Comment by engcom-Charlie** [comment] 2019-10-01 12:58
Hello @ioweb-gr !
We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.
**Manual testing scenario:**

1. Create an attribute with a long name programmatically( `io_timestamp_sync_product_details222` in my case)
2. Try to edit / update the attribute from backend

**Actual result:**
Attribute saved.
![Peek 2019-10-01 14-37](https://user-images.githubusercontent.com/51680850/65958906-37bf0a80-e459-11e9-8b5a-21a40ee1e8b6.gif)

So i have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-10-01 12:58 UTC
Labels: Issue: Format is valid
