### ISSUE TITLE
Update to 2.0.4: The specified value "{{currentPage}}" is not a valid number.

### ISSUE THREAD

**Issue by smatric** [magento/magento2#3977] opened 2016-04-01 22:36 UTC
## Steps to reproduce
1. Install Magento 2.0.2.
2. In admin panel, open "System" > "Web Setup Wizard" and select "System Upgrade"
## Expected result
1. Upgrade wizard
## Actual result

UI error:

> "Sorry, we can't take that action right now."

Console warning:

> "The specified value "{{currentPage}}" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+.\d+|.\d+)([eE][-+]?\d+)?"

Which comes from angular.js:8581:
`if ( ((startIndex = text.indexOf(startSymbol, index)) != -1) &&`

<img width="696" alt="screen shot 2016-04-01 at 15 30 41" src="https://cloud.githubusercontent.com/assets/11933233/14221829/cbf94218-f81e-11e5-89d9-81a95eb4cc00.png">

**Comment by mazhalai** [comment] 2016-04-02 02:26
@smatric did you save your repo.magento.com keys in system.config? Also what OS are you on?

**Comment by smatric** [comment] 2016-04-03 04:01
@mazhalai I have my GitHub key saved in composer.json, if that's what you're asking about:

```
"config": {
    "use-include-path": true,
    "github-oauth": {
        "github.com": "<token>"
    }
},
```

The server is running Ubuntu 14.04.4.

**Comment by ktomk** [comment] 2016-04-03 12:37
@smatric: That would be github oauth (for downloads) but these are not  your repo.magento.com keys. I dunno if you really need them for CE (the composer based install I just did, did not need them but I also might have some configured globally), but in case you're interested, they are offered within your account on magento.com: [Get your authentication keys (Magento2 Devdocs)](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/connect-auth.html).

I normally suggest to create the `auth.json` file next to the `composer.json` file in your Magento 2 project directory. Composer will use these credentials and you can have them per project (as you have the composer requirements per project).

Just go inside your project and execute the following command:

```
$ php -f vendor/bin/composer -- config  http-basic.repo.magento.com '<public_key>' '<private_key>'
```

Replace the place-holders with your keys. It will create / update the `auth.json` file at the correct place.

Afterwards you can try with a _`composer update --dry-run`_ if the credentials are working (will display an error if not, will not update due to dry-run mode).

**Comment by mazhalai** [comment] 2016-04-04 14:04
@smatric have you been able to try @ktomk suggestions?

**Comment by smatric** [comment] 2016-04-04 22:46
@ktomk 

`$ php -f vendor/bin/composer -- config  http-basic.repo.magento.com '<public_key>' '<private_key>'`

didn't work for me (I installed Magento from a ZIP file):

`PHP Warning:  require(.../m2/vendor/bin/../src/bootstrap.php): failed to open stream: No such file or directory in .../m2/vendor/bin/composer on line 8`

Adding auth.json to Magento's root directory resulted in an exception (Zend\ServiceManager\Exception\ServiceLocatorUsageException).

When I ran `composer update --dry-run`, it asked me to save my public and private repo keys, to which I consented:

`Do you want to store credentials for repo.magento.com in .../m2/.config/composer/auth.json ? [Yn] Y`

But that didn't solve the problem.

**Comment by ktomk** [comment] 2016-04-05 20:22
I see, installing it form a zipfile then most likely does not conserve the composer installation. I've read somewhere in the docs that the zip-file has some kind of extra packaging, therefore my suggestion was not straight forward in your case. If you install composer locally, it should work (just was pointing to the source version as I thought it's available in any case, but you can just use the one composer you have already as I see in your comment).

The ZendServiceManager\Exception is new to me, never ran into that one. I can't imagine how it can be even only remotely related to auth.json.

The Yn question you see later shows your standard composer home dir (via `$XDG_CONFIG_HOME`). This does not solve because in the backend the moved composer home is used.

Please re-run `composer config http-basic.repo.magento.com '<public_key>'  '<private key>'` this time with your standard composer and try with `--dry-run` again. It should not ask you for credentials at all. If it does, you can abort (ctrl+C).

**Comment by smatric** [comment] 2016-04-05 23:05
@ktomk thank you for your suggestions.

After running the command, [I get the same error](https://github.com/magento/magento2/files/205492/magento2_exception.txt) as when I added auth.json manually. It happens when I attempt to open `magento_URL/setup/index.php/select-version` URL:

```
An error occurred during execution; please try again later.

Additional information:

Zend\ServiceManager\Exception\ServiceLocatorUsageException

File:
.../m2/vendor/zendframework/zend-servicemanager/src/Exception/ServiceLocatorUsageException.php:34
Message:
Service "Magento\Setup\Controller\SelectVersion" has been requested to plugin manager of type "Zend\Mvc\Controller\ControllerManager", but couldn't be retrieved.
A previous exception of type "Zend\ServiceManager\Exception\ServiceNotCreatedException" has been raised in the process.
By the way, a service with the name "Magento\Setup\Controller\SelectVersion" has been found in the parent service locator "Zend\ServiceManager\ServiceManager": did you forget to use $parentLocator = $serviceLocator->getServiceLocator() in your factory code?
Stack trace:
#0 .../m2/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(312): Zend\ServiceManager\Exception\ServiceLocatorUsageException::fromInvalidPluginManagerRequestedServiceName(Object(Zend\Mvc\Controller\ControllerManager), Object(Zend\ServiceManager\ServiceManager), 'Magento\Setup\C...', Object(Zend\ServiceManager\Exception\ServiceNotCreatedException))
#1 .../m2/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(120): Zend\ServiceManager\AbstractPluginManager->tryThrowingServiceLocatorUsageException('Magento\Setup\C...', false, Object(Zend\ServiceManager\Exception\ServiceNotCreatedException))
#2 .../m2/vendor/zendframework/zend-mvc/src/Controller/ControllerManager.php(137): Zend\ServiceManager\AbstractPluginManager->get('Magento\Setup\C...', Array, false)
#3 .../m2/vendor/zendframework/zend-mvc/src/DispatchListener.php(76): Zend\Mvc\Controller\ControllerManager->get('Magento\Setup\C...')
#4 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#5 .../m2/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#6 .../m2/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#7 .../m2/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#8 .../m2/setup/index.php(31): Zend\Mvc\Application->run()
#9 {main}
```

**Comment by ktomk** [comment] 2016-04-06 04:56
okay, the dry-run should not have asked you for credentials then _if_ creation of auth.json would have successfully worked. sounds a bit like a configuration issue but is hard to say from the distance. I have not further clue on what to verify next, sorry. The exception at least shows you do have an underlying problem, but I guess you already knew :)

**Comment by mazhalai** [comment] 2016-04-11 14:08
@smatric Can you try the following:
copy `~/.composer/auth.json` to `var/composer_home/auth.json` and try again?

**Comment by smatric** [comment] 2016-04-11 20:57
@mazhalai I copied the file (it's under a slightly different path on my installation):

`cp ~/.config/composer/auth.json ~/var/composer_home/`

Now I'm getting the same exception again: Zend\ServiceManager\Exception\ServiceLocatorUsageException

**Comment by mazhalai** [comment] 2016-04-12 13:31
@smatric this is a really strange error, can you verify that you have the class `Magento\Setup\Controller\SelectVersion`? Also, clean your Magento2 cache as well as browser cache and try again.

**Comment by smatric** [comment] 2016-04-14 05:29
@mazhalai This is what grep finds:

```
vendor/magento/magento2-base/setup/src/Magento/Setup/Controller/SelectVersion.php:18: class SelectVersion extends AbstractActionController
setup/src/Magento/Setup/Controller/SelectVersion.php:18: class SelectVersion extends AbstractActionController
```

I flushed Magento's cache, cleared static files' cache and my browser's cache but I'm still getting the same error (`The specified value "{{currentPage}}" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?`).

**Comment by mazhalai** [comment] 2016-04-29 14:15
@smatric Can you give us some information about your env? OS and Webserver?

**Comment by mazhalai** [comment] 2016-04-29 20:11
@smatric we have created ticket MAGETWO-52439 to investigate and fix.

**Comment by smatric** [comment] 2016-05-01 03:09
When I reported the problem, I had Ubuntu 14.04 LTS installed on the server. Currently, it's been replaced with Ubuntu 16.04 LTS, but the problem is still there.

I use DigitalOcean as my hosting provider and have picked the $40 / month plan:
- 4GB Memory
- 2 Core Processor

**Comment by wizjack** [comment] 2016-05-19 10:38
Same issue for me, while entering the public and private key in the component manager attached is the screen shot.
![image](https://cloud.githubusercontent.com/assets/15883444/15390855/ce1c96b6-1ddb-11e6-91af-7136c31682bd.png)

**Comment by piotrekkaminski** [comment] 2016-06-09 23:05
The JS warning is still reproducible in 2.1RC1

**Comment by digitalredefined** [comment] 2016-06-30 19:29
Following - have same issue.

**Comment by Anshu-Mishra** [comment] 2017-02-27 12:44
I am getting the same error on 2.1.3

**Comment by veloraven** [comment] 2017-06-19 16:33
This issue was fixed in develop branch.
Closed.

**Closed as completed by veloraven** 2017-06-19 16:33 UTC
Labels: Issue: Ready for Work, bug report, Component: Setup

**Comment by korostii** [comment] 2017-06-19 16:53
Hi @veloraven,
The was reported on 2.0.x and 2.1.x branches. When are patches for these branches are expected to be released?
Could you please keep the issue open until it is fixed **on the same branch as it was reported on**?

**Comment by ktomk** [comment] 2017-06-19 17:55
@korostii: You don't keep the issue open, however, you ask for the SHA hash of the commit where it was fixed. In git with that hash you can see in which branch the fix has landed.

@veloraven: Could you please provide the hash reference of the fixing commit(s)?

**Comment by hostep** [comment] 2017-06-19 18:20
Guys, if you scroll up a little bit to August 5th, you'll see the commit: https://github.com/magento/magento2/commit/8888d9b2d7b1c00c239951b1177fbb552457c73d ;)
You can also [search for the MAGETWO number](https://github.com/magento/magento2/search?q=MAGETWO-52439&type=Commits&utf8=%E2%9C%93), it will (most of the time) also reveal the commit(s).

Although I do agree that it sometimes has to be communicated a little bit more explicitly by the Magento support crew.

(
completely off topic:

@ktomk: there is a little problem though when you want to find the branch, Magento likes to play a little game of keeping everything a secret until they finally release a new version. Until a new version is released, only the `develop` branch is being updated, I hoped they would start using the `2.1-develop` branch for upcomming fixes, so the community is aware about everything what is comming, but it doesn't look like that's the case currently, `2.1-develop` is only for community PR's targetting Magento version 2.1, not for the community to see what Magento is preparing to release in an upcoming new version, which is very unfortunate :(
)

**Comment by ktomk** [comment] 2017-06-19 18:39
Sorry, just wanted to mediate not escalate ;) - @hostep Thanks for the insight. The git history is a merge commit extravaganza :)

**Comment by korostii** [comment] 2017-06-20 09:14
Hi @ktomk, hi @hostep.
Thank you guys for caring and for the timely response. That's a lot more than I see from occasional raids by Magento, Inc. employees ;)

Seen the commit, however:
I happen to use a composer-installed version and I have no intent to patch any files in `vendor` directly. It makes me sad that cherry-picking those patches has became the new norm. Especially seeing that are approximately hundreds of such small bugfixes.
I think it's infuriating that one has to collect, apply, and test these fixes manually (making the Magento's multi-step QA process useless completely).
In my opinion, timely (each week) patches would do more good.

I do not understand how is this year-old bug still present in 2.1.7 (which is latest released version) and all @veloraven cares about is that it's fixed on `develop` branch. Hooray!

All I want is for the fixes to get released by Magento, Inc. in a timely matter. Is that too much to ask?
