### ISSUE TITLE
Custom swatch image sizes don't work

### ISSUE THREAD

**Issue by bjoern-quast** [magento/magento2#6398] opened 2016-08-30 12:17 UTC
### Preconditions
1. Magento CE 2.1.0 is installed.
2. Configurable products are configured
3. Option swatches are configured for said configurables
4. A custom module is used to override standard behaviour
### Steps to reproduce
1. Add a view.xml in your module's etc folder
2. Add nodes to change the swatch size:
   `
           <image id="swatch_image" type="swatch_image">
                 <width>98</width>
                 <height>98</height>
             </image>
   `
### Expected result

The new size is used
### Actual result

The default size is used

In module-swatches/Helper/Media.php the method getImageConfig() loads theme configs and then applies them in the wrong order, so that your custom config is overidden with the default one.

**Comment by pboisvert** [comment] 2016-08-30 14:12
closing as duplicate of #6382

**Closed as completed by pboisvert** 2016-08-30 14:12 UTC
Labels: bug report, Component: Catalog

**Comment by bjoern-quast** [comment] 2016-08-30 21:15
Thank you!
I couldn't find that issue with the obvious search "custom swatch size".
