### ISSUE TITLE
Swagger get store information gives error

### ISSUE THREAD

**Issue by Sharkozp** [magento/magento2#13143] opened 2018-01-11 17:04 UTC
### Preconditions
2.2.x

### Steps to reproduce
1. Go to Swagger
2. open storeStoreConfigManagerV1
3. Method GET /V1/store/storeConfigs
4. Values for search:
```
['default','test']
```
```
'default','test'
```
```
'default'
'test'
```

### Expected result

```json
[
  {
    "id": 1,
    "code": "default",
    "website_id": 1,
    "locale": "de_DE",
    "base_currency_code": "EUR",
    "default_display_currency_code": "EUR",
    "timezone": "Europe/Berlin",
    "weight_unit": "lbs",
    "base_url": "http://magento.loc/",
    "base_link_url": "http://magento.loc/",
    "base_static_url": "http://magento.loc/static/version1515689676/",
    "base_media_url": "http://magento.loc/media/",
    "secure_base_url": "https://magento.loc/",
    "secure_base_link_url": "https://magento.loc/",
    "secure_base_static_url": "https://magento.loc/static/version1515689676/",
    "secure_base_media_url": "https://magento.loc/media/"
  }
]
```

### Actual result

```json
{
    "message": "Invalid type for value: \"string\". Expected Type: \"string[]\"."
}
```

**Comment by ncrichards** [comment] 2018-01-12 20:10
Apparently swagger does not support arrays in get requests. The parameters are not being parsed correctly. 
As per the Magento store config API, below is how to build your query.

Assuming you want to list the configs for the stores (default and test). 
Use a RESTful client to pass your Authorization header
Authorization: Bearer token_value_here

http://yourdomain.com/rest/V1/store/storeConfigs?storeCodes[]=default&storeCodes[]=test

Hope you find this helpful.

**Comment by Sharkozp** [comment] 2018-01-15 11:27
Hi,

I think this is related to this [issue-12790](https://github.com/magento/magento2/issues/12790)

> Magento backend works correct, but Swagger builds request uri in incorrect way

**Comment by magento-engcom-team** [comment] 2018-02-15 11:51
@Sharkozp, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by sudhanshu-bajaj** [comment] 2019-05-29 05:49
Anyone working in it ?

**Comment by jayd59** [comment] 2019-10-29 09:05
Hello,

Did you forget this issue? Can you please work on it ?
Thanks, and best regards
Jérémy

**Comment by magento-engcom-team** [comment] 2019-12-30 13:14
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30133` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by baranada** [comment] 2020-03-19 01:51
I can't reproduce the issue. this issue has been resolved.
![Screenshot from 2020-03-19 08-50-02](https://user-images.githubusercontent.com/61573611/77023584-dcf57d00-69be-11ea-9b0b-d52029036a3c.png)

**Comment by niravkrish** [comment] 2020-04-26 06:35
Hello,

Please try below. in my local this is working fine.

http://magento.local/rest/V1/store/storeConfigs?params={storeCodes:[default,test]}

Thank you,
Nirav Patel

**Comment by jaydolphinweb** [comment] 2020-10-10 09:31
#dmcdindia2020

**Comment by jaydolphinweb** [comment] 2020-10-10 09:32
@magento I'm Working on it

**Comment by nihara47** [comment] 2020-12-22 07:01
@magento I'm Working on it

**Comment by engcom-Bravo** [comment] 2024-04-24 05:13
Hi @Sharkozp,

Thanks for your reporting and collaboration.

We have verified the issue and the issue is no more reproducible in Latest 2.4-develop instance.

As per this https://github.com/magento/magento2/issues/13143#issuecomment-600945066 We are Closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-04-24 05:13 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Component: Swagger, Triage: Dev.Experience, Reproduced on 2.4.x, Severity: S4, Priority: P4, Progress: done, Event: dmcdindia2020
