### ISSUE TITLE
Unable to Update Magento Error in SchemaBuilder.php at line: 253

### ISSUE THREAD

**Issue by nomis11uk** [magento/magento2#38592] opened 2024-04-09 08:05 UTC
### Preconditions and environment

ver. 2.4.6-p4
PHP 8.2

### Steps to reproduce

1. php82 composer.phar require magento/product-community-edition 2.4.7 --no-update
2. php82 composer.phar update
3. php82 bin/magento setup:upgrade

Note : The issue occurs when the database prefix is added with more than 4 characters eg: --db-prefix=tsts_

### Expected result

Update comple

### Actual result

Updating modules:
Schema creation/updates:

There is an error in vendor/magento/framework/Setup/Declaration/Schema/Declaration/SchemaBuilder.php at line: 253
Magento\Framework\Setup\Declaration\Schema\Declaration\SchemaBuilder::processTable(): Return value must be of type Magento\Framework\Setup\Declaration\Schema\Dto\Table, bool returned#0 vendor/magento/framework/Setup/Declaration/Schema/Declaration/SchemaBuilder.php(150): Magento\Framework\Setup\Declaration\Schema\Declaration\SchemaBuilder->processTable(Object(Magento\Framework\Setup\Declaration\Schema\Dto\Schema), Array)
#1 vendor/magento/framework/Setup/Declaration/Schema/SchemaConfig.php(78): Magento\Framework\Setup\Declaration\Schema\Declaration\SchemaBuilder->build(Object(Magento\Framework\Setup\Declaration\Schema\Dto\Schema))
#2 setup/src/Magento/Setup/Model/DeclarationInstaller.php(57): Magento\Framework\Setup\Declaration\Schema\SchemaConfig->getDeclarationConfig()
#3 setup/src/Magento/Setup/Model/Installer.php(868): Magento\Setup\Model\DeclarationInstaller->installSchema(Array)
#4 setup/src/Magento/Setup/Model/Installer.php(916): Magento\Setup\Model\Installer->declarativeInstallSchema(Array)
#5 setup/src/Magento/Setup/Console/Command/UpgradeCommand.php(147): Magento\Setup\Model\Installer->installSchema(Array)
#6 vendor/symfony/console/Command/Command.php(326): Magento\Setup\Console\Command\UpgradeCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\UpgradeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 vendor/magento/framework/Console/Cli.php(118): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 vendor/symfony/console/Application.php(175): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 bin/magento(23): Symfony\Component\Console\Application->run()
#12 {main}

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by likearocket** [comment] 2024-04-09 18:48
I also encountered this error when attempting to upgrade 2.4.6-p4 to 2.4.7.

**Comment by prbt2016** [comment] 2024-04-11 10:06
Hello ,

I  encountered the same error  while fresh installing Magento 2.4.7 community edition on Centos 7 with Apache 2.4, PHP 8.2/8.3 , MYSQL 8  i.e on executing  ./bin/magento setup:install {{PARAMS}}  : 

```
There is an error in /{{PATH}}/{{TO}}/{{MAGENTO}}/vendor/magento/framework/Setup/Declaration/Schema/Declaration/SchemaBuilder.php at line: 253
Magento\Framework\Setup\Declaration\Schema\Declaration\SchemaBuilder::processTable(): Return value must be of type Magento\Framework\Setup\Declaration\Schema\Dto\Table, bool returned#0 /{{PATH}}/{{TO}}/{{MAGENTO}}/vendor/magento/framework/Setup/Declaration/Schema/Declaration/SchemaBuilder.php(150): Magento\Framework\Setup\Declaration\Schema\Declaration\SchemaBuilder->processTable(Object(Magento\Framework\Setup\Declaration\Schema\Dto\Schema), Array)
#1 /{{PATH}}/{{TO}}/{{MAGENTO}}/vendor/magento/framework/Setup/Declaration/Schema/SchemaConfig.php(78): Magento\Framework\Setup\Declaration\Schema\Declaration\SchemaBuilder->build(Object(Magento\Framework\Setup\Declaration\Schema\Dto\Schema))
#2 /{{PATH}}/{{TO}}/{{MAGENTO}}/setup/src/Magento/Setup/Model/DeclarationInstaller.php(57): Magento\Framework\Setup\Declaration\Schema\SchemaConfig->getDeclarationConfig()
#3 /{{PATH}}/{{TO}}/{{MAGENTO}}/setup/src/Magento/Setup/Model/Installer.php(868): Magento\Setup\Model\DeclarationInstaller->installSchema(Array)
#4 /{{PATH}}/{{TO}}/{{MAGENTO}}/setup/src/Magento/Setup/Model/Installer.php(916): Magento\Setup\Model\Installer->declarativeInstallSchema(Array)
#5 [internal function]: Magento\Setup\Model\Installer->installSchema(Array)
#6 /{{PATH}}/{{TO}}/{{MAGENTO}}/setup/src/Magento/Setup/Model/Installer.php(407): call_user_func_array(Array, Array)
#7 /{{PATH}}/{{TO}}/{{MAGENTO}}/setup/src/Magento/Setup/Console/Command/InstallCommand.php(237): Magento\Setup\Model\Installer->install(Array)
#8 /{{PATH}}/{{TO}}/{{MAGENTO}}/vendor/symfony/console/Command/Command.php(326): Magento\Setup\Console\Command\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /{{PATH}}/{{TO}}/{{MAGENTO}}/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /{{PATH}}/{{TO}}/{{MAGENTO}}/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /{{PATH}}/{{TO}}/{{MAGENTO}}/vendor/magento/framework/Console/Cli.php(118): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /{{PATH}}/{{TO}}/{{MAGENTO}}/vendor/symfony/console/Application.php(175): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /{{PATH}}/{{TO}}/{{MAGENTO}}/bin/magento(23): Symfony\Component\Console\Application->run()
#14 {main}
```

Is this a known bug?. Could you please replicate this at your end?.

**Comment by devchris79** [comment] 2024-04-15 11:19
Also seeing this on upgrade from 2.4.6-p4 to 2.4.7

It seems like it may be related to this issue  #37756, but I don't know why it works fine in 2.4.6-p4 and 2.4.7 throws an error. 
We do have a small prefix on database table names, buts only 4 characters.

**Comment by nomis11uk** [comment] 2024-04-15 11:25
Yes, we also have a prefix (4 characters) in database table names and get the error.

**Comment by likearocket** [comment] 2024-04-15 11:47
4 character prefix here too. So we know what the problem is, question is how to resolve and how long?

**Comment by engcom-Dash** [comment] 2024-04-15 11:48
Hi @nomis11uk 

Thanks for reporting and collaboration.

Verified the issue by upgrading the instance from 2.4.6-p4 to 2.4.7 and the issue is not reproducible. Able to upgrade successfully.

Steps to reproduce
1. php82 composer.phar require magento/product-community-edition 2.4.7 --no-update
2. php82 composer.phar update
3.php82 bin/magento setup:upgrade

Please refer the attached screenshots and let us know if we missed anything.

<img width="1440" alt="Screenshot 2024-04-15 at 5 13 27 PM" src="https://github.com/magento/magento2/assets/60198592/7fcbe1d3-30ca-46b6-a071-b18b9bdf5604">
<img width="1440" alt="Screenshot 2024-04-15 at 5 16 45 PM" src="https://github.com/magento/magento2/assets/60198592/b5cf7f4e-991c-4a3e-8d04-3e44c86bb3e6">

**Comment by nomis11uk** [comment] 2024-04-15 12:28
@engcom-Dash do you have a prefix in database?

**Comment by devchris79** [comment] 2024-04-15 12:48
I am wondering if this is some strange effect of an old version of Mariadb (we are on a shared server using 10.3.39 and 10.6 is the current tested requirement) or an extension/theme issue. We don't really have many extensions though, Porto, Ebizmarts, Vnecomms, Owebia, Mageplaza core and that's about it.

@nomis11uk @likearocket are you running Mariadb 10.6?

**Comment by likearocket** [comment] 2024-04-15 12:59
Mariadb 10.6 here.

**Comment by nomis11uk** [comment] 2024-04-15 13:13
MariaDB 10.5.23 here

**Comment by nomis11uk** [comment] 2024-04-15 13:38
MySQL 5.7.44-48

**Comment by devchris79** [comment] 2024-04-15 14:34
I took our server down for a bit to test what table was throwing this error, hopefully it will shed some light for someone far more clued up than me!

I added a print of the table names to the upgrade output, on line 253: 
```
print $tableData['name'];
print "\n";
```
The final line printed that presumably is the table causing the issue is:
`payment_services_order_status_data_production_submitted_hash`

I don't know if that helps???

**Comment by devchris79** [comment] 2024-04-15 16:00
OK, this looks like its been [added in 2.4.7](https://developer.adobe.com/commerce/php/development/backward-incompatible-changes/reference/#magento-open-source)

The table name of payment_services_order_status_data_production_submitted_hash is too long in my opinion, its 60 characters and adding my prefix of 4 characters followed by the formatting '_' character takes it to 65 and is beyond Mariadb limit of 65 characters.

@engcom-Dash This is obviously going to affect alot of users who have a prefix on the database, are we going to have to look into reducing the prefix or do you think the tablename size needs reducing?

**Comment by engcom-Dash** [comment] 2024-04-16 11:25
Hi @nomis11uk 

Verified the issue again with prefix but we are still not able to reproduce the issue.

We have upgraded from 2.4.6-p4 to 2.4.7.

Please refer the attached screenshots.

<img width="1440" alt="Screenshot 2024-04-16 at 4 54 57 PM" src="https://github.com/magento/magento2/assets/60198592/ad5abd9b-753d-4862-9b1f-3c7f4a674429">
<img width="1440" alt="Screenshot 2024-04-16 at 4 55 05 PM" src="https://github.com/magento/magento2/assets/60198592/c780ee7f-5e34-464f-b8e6-2c04f92de038">

**Comment by nomis11uk** [comment] 2024-04-16 11:28
Hi @engcom-Dash
Please can you confirm the prefix length used? Was it 4 characters?

**Comment by engcom-Dash** [comment] 2024-04-16 11:41
Hi @nomis11uk 

I have used --db-prefix=tsts as prefix.

Thanks.

**Comment by nomis11uk** [comment] 2024-04-16 12:10
@engcom-Dash please can you try with one more character e.g 'tsts_'

**Comment by engcom-Dash** [comment] 2024-04-16 13:18
Hi @nomis11uk 

Sure, will try and update the status.

Thanks.

**Comment by engcom-Dash** [comment] 2024-04-17 06:12
Hi @nomis11uk 

Verified the issue on 2.4.7 after upgrading the instance from 2.4.6-p2 and the issue is reproducable.

Hence, Confirming the issue.

Steps to reproduce

1. php82 composer.phar require magento/product-community-edition 2.4.7 --no-update
2. php82 composer.phar update
3. php82 bin/magento setup:upgrade

We are getting the below error when we have database prefix with more than 4 characters eg: --db-prefix=tsts_ 

There is an error in vendor/magento/framework/Setup/Declaration/Schema/Declaration/SchemaBuilder.php at line: 253
Magento\Framework\Setup\Declaration\Schema\Declaration\SchemaBuilder::processTable(): Return value must be of type Magento\Framework\Setup\Declaration\Schema\Dto\Table, bool returned#0 vendor/magento/framework/Setup/Declaration/Schema/Declaration/SchemaBuilder.php(150): Magento\Framework\Setup\Declaration\Schema\Declaration\SchemaBuilder->processTable(Object(Magento\Framework\Setup\Declaration\Schema\Dto\Schema), Array)
https://github.com/magento/magento2/issues/1 vendor/magento/framework/Setup/Declaration/Schema/SchemaConfig.php(78): Magento\Framework\Setup\Declaration\Schema\Declaration\SchemaBuilder->build(Object(Magento\Framework\Setup\Declaration\Schema\Dto\Schema))
https://github.com/magento/magento2/pull/2 setup/src/Magento/Setup/Model/DeclarationInstaller.php(57): Magento\Framework\Setup\Declaration\Schema\SchemaConfig->getDeclarationConfig()
https://github.com/magento/magento2/pull/3 setup/src/Magento/Setup/Model/Installer.php(868): Magento\Setup\Model\DeclarationInstaller->installSchema(Array)
https://github.com/magento/magento2/issues/4 setup/src/Magento/Setup/Model/Installer.php(916): Magento\Setup\Model\Installer->declarativeInstallSchema(Array)
https://github.com/magento/magento2/issues/5 setup/src/Magento/Setup/Console/Command/UpgradeCommand.php(147): Magento\Setup\Model\Installer->installSchema(Array)
https://github.com/magento/magento2/issues/6 vendor/symfony/console/Command/Command.php(326): Magento\Setup\Console\Command\UpgradeCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
https://github.com/magento/magento2/issues/7 vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
https://github.com/magento/magento2/issues/8 vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\UpgradeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
https://github.com/magento/magento2/pull/9 vendor/magento/framework/Console/Cli.php(118): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
https://github.com/magento/magento2/issues/10 vendor/symfony/console/Application.php(175): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
https://github.com/magento/magento2/issues/11 bin/magento(23): Symfony\Component\Console\Application->run()
https://github.com/magento/magento2/issues/12 {main}


Please refer the attached screenshot.

<img width="1440" alt="38592_Confirmed" src="https://github.com/magento/magento2/assets/60198592/0bb411a7-b1e5-4088-b10a-c648cb1666ae">

**Comment by devchris79** [comment] 2024-04-17 16:14
@engcom-Dash The label you have added is for 2.4.6-P4, but this is actually an error in 2.4.7.

The issue is the new table in 2.4.7 `payment_services_order_status_data_production_submitted_hash` being 60 characters long, adding a 5 character prefix takes it beyond a Mariadb limit of 64 characters.

I don't know if there is any officially documented maximum prefix length, but most guides tend to be 5 characters.

**Comment by chernenm** [comment] 2024-04-23 16:09
The fix for this issue has just been released in scope of a new Payment Services package version 2.5.0, the package is available at repo.magento.com
If you are already on 2.4.7 please run 
`composer require magento/payment-services:2.5.0 --with-all-dependencies `  to get the latest version.
If you are upgrading to 2.4.7 the latest package will be used automatically.

**Closed as completed** 2024-04-23 17:48 UTC
Labels: Issue: Confirmed, Component: DB, Reproduced on 2.4.x, Priority: P0, Progress: done, Area: Upgrades - Upgrade Compatibility Tool, Reported on 2.4.7
