### ISSUE TITLE
getUrlPath() not working correct with store views with url-fallback

### ISSUE THREAD

**Issue by matin73** [magento/magento2#23640] opened 2019-07-09 14:05 UTC
### Preconditions (*)

1. Magento 2.3.x
2. PHP 7.2.119

### Steps to reproduce (*)

1. Create some store views for different countries - f.e. de, de_at, de_ch, en and en_gb
2. Add categories and use for de, de_at and de_ch same url (all 3 store views are in german - so name of category is same) by using checkbox "Use Default Value" vor field "url_key". 
3. Translate category for english store views "en" and "en_gb". Use also  checkbox "Use Default Value" vor field "url_key". 
4. Add function to shop $this->categoryRepository->get($this->registry->registry('current_category')->getId(), $value['store_id'])->getUrlPath() (f. e. to generate hreflang-tag)

### Expected result (*)

1. URL in hreflang-tag should look like:
https://www.domain.com/de/kategorie-german.html
https://www.domain.com/de_at/kategorie-german.html
https://www.domain.com/de_ch/kategorie-german.html
https://www.domain.com/en/category-english.html
https://www.domain.com/en_gb/category-english.html

### Actual result (*)

1. But URL in hreflang-tag look like:
https://www.domain.com/de/kategorie-german.html
https://www.domain.com/de_at/category-english.html
https://www.domain.com/de_ch/category-english.html
https://www.domain.com/en/category-english.html
https://www.domain.com/en_gb/category-english.html

The problem is, that there is no entry in table catalog_category_entity_varchar for store views using "Use Default Value" vor field "url_key".

**Comment by matin73** [comment] 2019-07-09 14:05
> 
> 
> Hi @matin73. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
>     * [ ]  Summary of the issue
> 
>     * [ ]  Information on your environment
> 
>     * [ ]  Steps to reproduce
> 
>     * [ ]  Expected and actual results
> 
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @matin73 do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
>     * x  yes
> 
>     * [ ]  no
> 
> 
>     * Join [Magento Community Engineering Slack](http://tinyurl.com/engcom-slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

**Comment by magento-engcom-team** [comment] 2019-07-09 14:06
Hi @matin73. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-09 14:06
Hi @matin73, here is your [Magento instance](https://i-23640-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23640-2-3-develop.instances.magento-community.engineering/admin](https://i-23640-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by matin73** [comment] 2019-07-09 14:10
> 
> 
> Hi @matin73, here is your [Magento instance](https://i-23640-2-3-develop.instances.magento-community.engineering).
> Admin access: https://i-23640-2-3-develop.instances.magento-community.engineering/admin
> Login: `admin` Password: `123123q`
> Instance will be terminated in up to 3 hours.

Thanks. But I can not add function $this->categoryRepository->get($this->registry->registry('current_category')->getId(), $value['store_id'])->getUrlPath() (f. e. to generate hreflang-tag) which shows problem

**Comment by matin73** [comment] 2019-07-19 11:29
Issue: Confirmed

**Comment by engcom-Bravo** [comment] 2019-07-19 11:43
Hello,@matin73 ! I can't reproduce this issue on fresh 2.3-develop. Can you give me more steps to reproduce or update your added steps with more details? 
Thanks!

**Comment by matin73** [comment] 2019-07-19 12:34
@engcom-Bravo did you make some module with this function?

**Comment by engcom-Bravo** [comment] 2019-07-19 12:58
@matin73 i edit this:
![tesss](https://user-images.githubusercontent.com/51680745/61536740-029c4200-aa3e-11e9-92fe-59fd6d81adc7.png)

**Comment by matin73** [comment] 2019-07-19 13:12
please try with some custom module

**Comment by matin73** [comment] 2019-07-19 13:18
and please try with store views id like this:
de = ID 1
en = ID 2
de_at = ID 3
de_ch = ID 4
en_gb = ID 5

Because there is some strange fallback. 
ID  1 de = correct url, 
ID 2 en = correct url, 
ID 3 de_at and ID 4 de_ch = wrong url -> shows url of en ID 2 en. but this is wrong, because ID 3 de_at and ID 4 de_ch should show url of ID 1 de.

**Comment by matin73** [comment] 2019-07-19 13:22
please also have a look into table catalog_category_entity_varchar. There are no entries for store views de_at = ID 3, de_ch = ID 4, en_gb = ID 5 (store views using "Use Default Value" vor field "url_key"). In Magento 1 there where also entries genereated for other store views. We have importet with migration tool and first it worked correct, because migration tool also migrated all store view urls. after saving any of these categories the entries in  catalog_category_entity_varchar get deleted and the function has wrong fallback

**Comment by engcom-Bravo** [comment] 2019-07-19 13:43
@matin73 , thank for contributing! That is right.

**Comment by magento-engcom-team** [comment] 2019-07-19 13:44
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18325` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Closed as completed** 2020-11-02 13:54 UTC
Labels: Issue: Confirmed, Reproduced on 2.3.x, Issue:  Cannot Reproduce, Component: MysqlMq, Triage: Dev.Experience, Priority: P2, Severity: S2, Progress: done

**Comment by sdzhepa** [comment] 2020-11-04 18:23
The related internal Jira ticket `MC-23858` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem on the latest `2.4-develop` please create new Issue with updated information/steps/preconditions in the **_Description section_**.
