### ISSUE TITLE
Salable Calculations for Default Stock vs Other

### ISSUE THREAD

**Issue by jledford-bbm** [magento/magento2#37502] opened 2023-05-15 19:33 UTC
### Preconditions and environment

- Magento version 2.4.4
- When changing a sku from manage stock = yes, to manage stock = no, the behavior is different if you are using the default stock vs using user created stocks.
- 

### Steps to reproduce

**Scenario 1 default stock and default source**

1. A sku with salable of 1
2. Make a purchase for 1 and observe salable is now 0 and the sku is out of stock on the front end.
3. Change the sku to manage stock = no
4. On the frontend the sku is now available for sale at any quantity
5. In the database observed cataloginventory_stock_status for this sku and observed stock_status change appropriately when in stock/available and out of stock

**Scenario 2 new stock and new source**

1. A sku with salable of 1
2. Make a purchase for 1 and observe salable is now 0 and the sku is out of stock on the front end.
3. Change the sku to manage stock = no
4. On the frontend the sku remains out of stock
5. In the database observed table inventory_stock_2 for this sku and observed the is_salable field never changed when flagging as manage stock = no

### Expected result

I expect changing manage stock = no to behave the same regardless if you are using the default stock or user created stocks.

### Actual result

Instead what happens is any user-created stocks still have some salable calculations happening after you make manage stock = no

### Additional information

This was tested on a vanilla 2.4.4 commerce install with sample data.  To remedy clearing the inventory_reservation table for the offending skus is the only reliable method to make manage stock = no behave properly.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-06-06 12:36
Hi @jledford-bbm,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

Scenario 1 default stock and default source

- A sku with salable of 1
- Make a purchase for 1 and observe salable is now 0 and the sku is out of stock on the front end.
- Change the sku to manage stock = no
- On the frontend the sku is now available for sale at any quantity
- In the database observed cataloginventory_stock_status for this sku and observed stock_status change appropriately when in stock/available and out of stock

 Scenario 2 new stock and new source

- A sku with salable of 1
- Make a purchase for 1 and observe salable is now 0 and the sku is out of stock on the front end.
- Change the sku to manage stock = no
- On the frontend the sku remains out of stock
- In the database observed table inventory_stock_2 for this sku and observed the is_salable field never changed when flagging as manage stock = no



After changing manage stock to no for both the sources and stocks product is still available in frontend.Both default and user created stocks and sources are working same.

<img width="1443" alt="Screenshot 2023-06-06 at 5 26 28 PM" src="https://github.com/magento/magento2/assets/51680745/a143714a-1b88-4fe0-ab9c-141b2f4e08a4">



<img width="344" alt="Screenshot 2023-06-06 at 3 47 41 PM" src="https://github.com/magento/magento2/assets/51680745/0dc58f44-31a4-435a-bad9-9c16c84e2d19">


<img width="553" alt="Screenshot 2023-06-06 at 3 46 15 PM" src="https://github.com/magento/magento2/assets/51680745/f5ed741d-310c-448e-89c0-6de86295dd7d">



After adding [sources](https://experienceleague.adobe.com/docs/commerce-admin/inventory/quantities/sources-assign-per-product.html?lang=en), update the inventory quantities for your product. These values track the on-hand, available stock amounts.


Kindly refer this document https://experienceleague.adobe.com/docs/commerce-admin/inventory/quantities/quantities-assign-per-product.html?lang=en.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-06-19 06:45
Hi @jledford-bbm,

Please provide us latest update on this https://github.com/magento/magento2/issues/37502#issuecomment-1578686930  you are able to reproduce the issue or still working on this issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-06-30 05:44
Hi @jledford-bbm,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-06-30 05:44 UTC
Labels: Issue: needs update, Reported on 2.4.4
