### ISSUE TITLE
Braintree PayPal locale should have it's own setting

### ISSUE THREAD

**Issue by tomasinchoo** [magento/magento2#9639] opened 2017-05-16 07:16 UTC
### Preconditions
Any version of Magento 2

### Steps to reproduce
1. Create (for example) website with en_IE locale. 
2. Configure Braintree sandbox.
3. Try to buy something

### Expected result
1. One should be able to use PayPal via Braintree payment method

### Actual result
1. JavaScript error in console: "Error: This PayPal integration does not support this country"

Issue is trivial: 
Magento reads locale from config and when locale is not supported, it throws error.
Issue wouldn't happen in case there is configuration field where you can explicitly configure one of 
supported locales for Braintree.

This is actually BUG, not feature request ;)

**Comment by YPyltiai** [comment] 2017-05-19 11:36
Hello, @tomasinchoo,

Thank you for bringing this to our attention. I have created the internal ticket `MAGETWO-69340` to address this issue.

Please note, we are not able to implement the separate configuration for Braintree, as we need the locale to remain consistent across the entire Magento instance. The appropriate mapping will be added for Braintree, so any not supported locales will be replaced with the suggested by Braintree default locale.

**Comment by Matic** [comment] 2017-06-12 09:14
Any ideas how to solve this until the official bugfix is released ?

**Comment by alena-marchenko** [comment] 2017-06-13 14:08
Hi @tomasinchoo 

Fix for MAGETWO-69340 is merged to develop branch, closing the issue.
Thank you.

**Closed as completed by alena-marchenko** 2017-06-13 14:08 UTC
Labels: Issue: Ready for Work, bug report, Component: Payment

**Comment by korostii** [comment] 2017-06-13 23:28
Hi @alena-marchenko
The issue is acknowledged for both 2.1.x and 2.0.x branches.
Please, please don't close the issue until the fix is backported to both of them and released officially.

Reminds me of this old child's game: you cover your eyes with your hands, you don't see the monster, and so you say it doesn't exist.
That trick only works when the monster was imaginary in the first place.
