### ISSUE TITLE
Unable to link more than two child product to Configurable product via REST API

### ISSUE THREAD

**Issue by srinivasanithin** [magento/magento2#6756] opened 2016-09-26 14:51 UTC
We pulled the latest code from Magento2 and install the Magento2 instance
Problem -1
### Preconditions

1. Magento develop branch
2. php-fpm version 5.6 MySQL 5.6
### Steps to reproduce

1.  create a configurable Product using api using POST: /V1/products using the following JSON body
   {
   "product" : {
       "sku" : "Test-Product-Parent",
       "name" : "Test-Product-Parent",
       "attribute_set_id" : 4,
       "price" : 50,
       "status" : 1,
       "visibility" : 4,
       "type_id" : "configurable",
       "weight" : 2,
       "extension_attributes" : {
   
   ```
   }
   ```
   
   }
   }
2.  Then make a call to links SKU using POST: /V1/configurable-products/Test-Product-Parent/child using the following JSON body
   {
   "childSku":"TestProduct-Red" 
   }
3.  It links this item but later if you try to link another item it doesn't link another item. I am trying for new item to link
   Then make a call to links Child SKU using POST: /V1/configurable-products/Test-Product-Parent/child using the following JSON body
   {
   "childSku":"Test-Product-Blue" 
   }

It gives me 200 as status code and response as true.
### Expected result

1.  I should be seeing two ChildSkus linked to Parent product.
### Actual result

1. Only first item is linked to parent item. We can see this by making the following api call GET: /V1/configurable-products/Test-Product-Parent/children and here is the response
   [
   {
     "sku": "TestProduct-Red",
     "name": "TestProduct-Red",
     "attribute_set_id": 4,
     "price": 24,
     "status": 1,
     "type_id": "simple",
     "created_at": "2016-09-26 12:30:40",
     "updated_at": "2016-09-26 12:30:40",
     "weight": 2,
     "extension_attributes": [],
     "product_links": [],
     "tier_prices": [],
     "custom_attributes": [
       {
         "attribute_code": "tax_class_id",
         "value": "2"
       },
       {
         "attribute_code": "category_ids",
         "value": [
           "2"
         ]
       },
       {
         "attribute_code": "required_options",
         "value": "0"
       },
       {
         "attribute_code": "has_options",
         "value": "0"
       },
       {
         "attribute_code": "url_key",
         "value": "testproduct-red"
       }
     ]
   }
   ]

I cannot attach more than one SKU using the api to configurable item created via API. 
I have all details of attributes set same in all three records and also configurable attribute is same.

**Comment by piatrouski** [comment] 2016-09-27 10:55
Seems like it is duplicated for https://github.com/magento/magento2/issues/5243

**Comment by mbrinton01** [comment] 2016-09-27 12:56
Thank you @srinivasanithin for your detailed report.  I've confirmed this is a duplicate of #5243.  Please follow that issue for updates on resolution.

**Closed as completed by mbrinton01** 2016-09-27 12:56 UTC
Labels: bug report, Component: Framework/Webapi
