### ISSUE TITLE
Coding error in tax details

### ISSUE THREAD

**Issue by hanaks** [magento/magento2#30376] opened 2020-10-08 13:23 UTC
### Preconditions (*)

Magento version 2.4.0

### Steps to reproduce (*)

1. Set up Magento with a two tax classes with different rates. One for shipping and another for product. I have used setup for Norway.
2. Install Nets payment gateway module:
https://tech.dibspayment.com/easy/webshop_modules/magento2
3. Configure for testing.
4. Submit a test order:
https://tech.dibspayment.com/easy/test-information
5. Visit the successfully placed order in backend.

### Expected result (*)

No error.

### Actual result (*)

Order details in backend doesn't fully generate.
There is an error in bottom, after which there is no more output:
`<tr id="rate-An error has happened during application run. See exception log for details.`

The error happens in vendor/magento/module-sales/view/adminhtml/templates/order/totals/tax.phtml

Here is dump of $_fullInfo variable in that file:
```
Array
(
    [0] => Array
        (
            [amount] => 70.0000
            [base_amount] => 70.0000
            [base_real_amount] => 70.0000
            [rates] => Array
                (
                    [0] => Array
                        (
                            [code] => Mva lav
                            [title] => Mva lav
                            [percent] => 15
                            [position] => 0
                            [priority] => 0
                        )

                    [1] => Array
                        (
                            [code] => Mva Høy
                            [title] => Mva Høy
                            [percent] => 25
                            [position] => 0
                            [priority] => 0
                        )

                )

            [percent] => 40
            [id] => Mva lavMva Høy
        )

)
```

Order printing is affected too, error is in different file. I didn't test invoice, creditmemo, shipment and printing of these.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Morgy93** [comment] 2020-10-16 09:53
Already reported here: #30094

**Comment by engcom-Alfa** [comment] 2020-12-23 12:00
Duplicate of #30094

**Closed as completed by engcom-Alfa** 2020-12-23 12:00 UTC
Labels: Issue: ready for confirmation, Reported on 2.4.0

**Comment by Kilawuyiek** [comment] 2023-01-15 17:08
It appears that there is an error happening in the Magento sales module when trying to display the tax information for orders that have been placed using the Nets payment gateway module. The error message states that there is an error in the file "vendor/magento/module-sales/view/adminhtml/templates/order/totals/tax.phtml" and that "An error has happened during application run. See exception log for [details](https://namecombinertool.com/)."

It seems that this issue is caused by the fact that the tax classes in the order have the same code, "Mva lavMva Høy", which is causing the issue in displaying the tax information.

To resolve this issue, you should check the tax class configuration and make sure that the tax classes have unique codes. Alternatively, you can also contact the developer of the Nets payment gateway module for further assistance.
