### ISSUE TITLE
Unable to create a new product with the existing product name in the database. Getting error message "The value specified in the URL Key field would generate a URL that already exists." 

### ISSUE THREAD

**Issue by sudheer-gajjala** [magento/magento2#24134] opened 2019-08-14 12:40 UTC
### Description (*)

While duplicating a product , product sku, and url key will be auto generated. So user can save the product without having any problem with mandatory fileds.

If we are creating a new product with the same name, system is blocking the user by asking to enter a unique URL key. But SKU will be generated automatically.

So just like in duplicating a product page, in create new product page also URL key should be generated automatically based on product name or sku.

So that it will be more user friendly.

### Expected behavior (*)

URL key should be generated automatically while creating new product similar to SKU generation.

### Benefits

Product Creation will be user friendly.

### Additional information

Screen cast : https://drive.google.com/file/d/1Nwh3RMBtkmVgkRLgYZR6_FJhkaTm5KpN/view

**Comment by magento-engcom-team** [comment] 2019-08-14 12:55
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19225` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hostep** [comment] 2019-08-15 15:19
Hi all

This has already been requested a couple of times in the past and the response was always that this is intended behavior:
- https://github.com/magento/magento2/issues/21860#issuecomment-478509839
- https://github.com/magento/magento2/issues/9465#issuecomment-331105210
- I'm sure there are even more issues on Github ...

@engcom-Bravo: can you check internally if this request is valid or not? Otherwise we should probably close it?

**Comment by engcom-Bravo** [comment] 2019-08-16 14:23
Hi @hostep. The request has been made. Waiting for response.

**Comment by sdzhepa** [comment] 2019-10-07 21:36
Hello @sudheer-gajjala 

This issue was investigated and discussed with Magento product manager and architect.
And agreed with https://github.com/magento/magento2/issues/24134#issuecomment-521680021

For case "creating a new product with the same name" it is by design behavior that system asks a  user to change  URL-key manually instead of autogenerated. Admin user should have control over it and do it intentionally. Magento does not want to change it in the core code at this moment

**Closed as completed by sdzhepa** 2019-10-07 21:36 UTC
Labels: Issue: Ready for Work, Component: Catalog, Component: CatalogUrlRewrite, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, partners-contribution, Partner: i95Dev
