### ISSUE TITLE
In multiple website Sale order grid column "Grand Total (Base)","Grand Total (Purchased)" display default website currency not store or website currency

### ISSUE THREAD

**Issue by pareshe** [magento/magento2#4553] opened 2016-05-18 13:34 UTC
In multiple website Sale order grid column "Grand Total (Base)","Grand Total (Purchased)" display default website currency not store or website currency

**Comment by NadiyaS** [comment] 2016-06-15 07:52
Hi @pareshe ,
thanks for reporting this issue. It is already being tracked by MAGETWO-54384 ticket.
We added additional case from your description.
This issue will be closed as duplicate of  #4980.

**Closed as completed by NadiyaS** 2016-06-15 07:52 UTC

**Comment by Gorkyman** [comment] 2016-11-26 09:46
@NadiyaS was this issue resolved in 2.1.2? Because we can still see it in 2.1.1.

**Comment by maderlock** [comment] 2016-11-30 17:44
Possible cause and fix in #5036
