### ISSUE TITLE
Saving CMS page does not create URL rewrite in Magento 2.1.0

### ISSUE THREAD

**Issue by JacobDrummond** [magento/magento2#5923] opened 2016-08-01 16:06 UTC
### Preconditions
1. PHP 5.6.16
2. MySQL 5.6.21-log
3. Magento 2.1.0
4. Nginx 1.4.6
### Steps to reproduce
1. Create new CMS page in admin:
   ![hama-page-new-2](https://cloud.githubusercontent.com/assets/8377620/17299900/06c5c968-5808-11e6-8bc8-160b5f777c2e.png)
### Expected result
1.  Page should be accessible  as /foo-bar
### Actual result
1. 404 error:
   ![hama-3](https://cloud.githubusercontent.com/assets/8377620/17300233/6a9c334a-5809-11e6-9446-4751e8d570c0.png)
2. "foo-bar" doesn't appear anywhere in url_rewrite:
   `SELECT * FROM url_rewrite WHERE request_path LIKE "%foo-bar%"` returns nothing.
### Additional info
1. CMS pages created before the 2.1.0 upgrade load fine.

**Comment by Cacasapo** [comment] 2016-08-02 23:20
Magento 2.1 here. Upgrade from 2.0.8 with a custom theme installed. PHP 7.0.9, apache 2.4.23.

Just came across this issue and thought I was losing my mind. I still might be.

Created a couple different pages and they both 404... 
url_rewrite populated with pre-2.1 entries, which work.

**Comment by JacobDrummond** [comment] 2016-08-04 12:37
Hi @Cacasapo,

Are you also having URL rewrite issues with products, as described in #5929?

**Comment by Cacasapo** [comment] 2016-08-04 14:13
@JacobDrummond Just tested it and yes, that is also present on my install.

**Comment by Cacasapo** [comment] 2016-08-04 17:09
PS: This bug is NOT present on a 2.1 fresh install.

**Comment by andimov** [comment] 2016-08-05 13:24
@JacobDrummond 
Thank you for reporting this issue.
I can't reproduce it on Magento 2.1.0 & nginx>=1.8v
Your web server doesn't pass the [requirements](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html).
Please, re-check this issue on supported software or add some additional info.

**Comment by JacobDrummond** [comment] 2016-08-05 13:33
@andimov, I also experience this bug locally on Apache/2.4.17, which [is supported](http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements.html)

**Comment by andimov** [comment] 2016-08-05 13:37
@JacobDrummond 
I can't reproduce it on Apache/2.4.18 also.

**Comment by JacobDrummond** [comment] 2016-08-05 13:40
@andimov, this issue is [not present](/magento/magento2/issues/5923#issuecomment-237618440) on a fresh 2.1 install. Did you start with 2.1, or upgrade from 2.0.6?

**Comment by andimov** [comment] 2016-08-05 13:44
@JacobDrummond

You should provide the appropriate steps and preconditions for reproducing.

**Comment by andimov** [comment] 2016-08-05 14:00
@JacobDrummond
What mode do you have for indexers updates?
Try to switch mode for all indexers twice. Then reproduce this issue again.

**Comment by JacobDrummond** [comment] 2016-08-05 14:14
@andimov,

> You should provide the appropriate steps and preconditions for reproducing.

Sorry, I didn't know upgrading was a replication step until @Cacasapo mentioned it. Should I update issue descriptions as details emerge in a discussion?

> Try to switch mode for all indexers twice. Then reproduce this issue again.

Switching indexer modes back and forth didn't make a difference. Aren't indexers irrelevant in this context, as Magento2 [doesn't use indexers to maintain url_rewrite](http://magento.stackexchange.com/a/95337)?

**Comment by JacobDrummond** [comment] 2016-08-08 07:27
@Cacasapo, solved this issue! The URLs aren't indexing because pages aren't assigning to stores correctly.
1. disable single-store mode, so you can always see which stores pages are assigned to:
   ![page-1](https://cloud.githubusercontent.com/assets/8377620/17472170/4a2839fa-5d41-11e6-8e25-20f9f0ea1aa3.png)
2. Run this query to assign all pages to admin store: 

``` sql
INSERT INTO `cms_page_store` (page_id, store_id)

SELECT      page_id     `page_id`
        , 0     `store_id`
FROM        `cms_page`

ON DUPLICATE KEY UPDATE page_id=VALUES(page_id), store_id=VALUES(store_id)
```
1. Pages should be assigned to at least the admin store, and now generate URLs correctly:
   ![page-2](https://cloud.githubusercontent.com/assets/8377620/17472223/b9819544-5d41-11e6-8452-8660d3765ab7.png)

**Comment by andimov** [comment] 2016-08-08 07:46
@JacobDrummond @Cacasapo 
Thank you for a solution!
Do you think it is a Magento bug?

**Comment by JacobDrummond** [comment] 2016-08-08 07:48
@andimov, it appears to be a bug with single-store mode. I'll open a separate issue for it when I have time. See [this comment](/magento/magento2/issues/5929#issuecomment-238163253).

**Comment by Cacasapo** [comment] 2016-08-08 11:37
@JacobDrummond Nice job on the workaround.

Thing is, a fix for the two issues you've found really needs to be in 2.1.1, which, hopefully, drops soon.

**Comment by andimov** [comment] 2016-08-16 10:31
@JacobDrummond @Cacasapo 
Thanks! I've created an internal ticket for this issue - MAGETWO-56863 and linked it to this one.

**Comment by liquidia** [comment] 2016-08-31 07:27
issue still exist in latest 2.1.1

**Comment by yumicom** [comment] 2016-11-04 12:12
issue exist in v. 2.1.2

**Comment by erfanimani** [comment] 2016-12-23 15:19
Issue exists in 2.1.3..

**Comment by veloraven** [comment] 2016-12-26 15:17
MAGETWO-56863 fixes this issue in develop branch
Internal ticket for branch 2.1 - MAGETWO-58383

**Comment by Ctucker9233** [comment] 2017-03-25 22:07
@veloraven What version of Magento will contain MAGETWO-58383? Are there commit references for this internal ticket?

**Comment by magento-engcom-team** [comment] 2017-09-20 22:27
@JacobDrummond, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:27 UTC
Labels: Issue: Ready for Work, bug report, Component: CatalogUrlRewrite, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid

**Comment by Cacasapo** [comment] 2017-10-16 19:51
So, is the 2.1.x branch going to be abandoned for 2.2?

**Comment by Ctucker9233** [comment] 2017-11-11 21:26
@Cacasapo I'm pretty sure 2.1 is not at EOL. But they want everyone to go to 2.2.

**Comment by Ctucker9233** [comment] 2018-02-28 20:34
@magento-engcom-team Will the backport for 2.1 make it into the next release?
