### ISSUE TITLE
Discount Codes invalid each day 

### ISSUE THREAD

**Issue by angelamettas** [magento/magento2#8124] opened 2017-01-13 04:46 UTC
### Preconditions
Magento Version 2.1.2

### Steps to reproduce
![image](https://cloud.githubusercontent.com/assets/25090354/21918593/f85aaf80-d9a6-11e6-950e-16be3b9193bf.png)
![image](https://cloud.githubusercontent.com/assets/25090354/21918610/18bd94a4-d9a7-11e6-9b5c-bd168abbc90c.png)
![image](https://cloud.githubusercontent.com/assets/25090354/21918617/2b69d98c-d9a7-11e6-862e-eaebaf566c82.png)

### Expected result
should stay active with no expiry

### Actual result
works the day they are placed and the next day these are invalid

**Comment by angelamettas** [comment] 2017-01-13 04:48
Help! Do I need to add a condition? we have about 6 in the list as well if thats helps, if its possibly a priority issue

**Comment by ziiljuks** [comment] 2017-01-13 07:45
You are missing From and To fields.

**Comment by kandrejevs** [comment] 2017-01-13 09:15
duplicate of https://github.com/magento/magento2/issues/6762
@ziiljuks EE have staging module to handle from/to dates

**Comment by veloraven** [comment] 2017-01-13 13:53
@angelamettas thank you for your report. 
I'm closing this issue as a duplicate for #6762, #6122.
Internal ticket for branch 2.1 - MAGETWO-58855
The issue was already fixed and will be delivered in some of next releases.

**Closed as completed by veloraven** 2017-01-13 13:53 UTC

**Comment by angelamettas** [comment] 2017-01-15 22:52
Which release will it be fixed with? 2.1.3?
May I have a list of the all the bugs that will be fixed as part of 2.1.3 ?

On 14 January 2017 at 00:53, Olga Moyseyenko <notifications@github.com>
wrote:

> @angelamettas
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_angelamettas&d=DgMFaQ&c=N9aEhCy8U0rJkO1xCZf7rgM9fohfR5qe_N93viZd7O8&r=mbFmkVqaG5ogD6QHOzWrBjtwu0qH7TeQzXvoV1qb523sgyVSmSVMThKaMNrqu6mj&m=1U8J0iznJfsybYsiiXD5w9WMarSXD1WQjsn_ehKPBh0&s=JyOsyywOgIban_-jOGblepRBr5yEuWNMFjaqLIhLmYc&e=>
> thank you for your report.
> I'm closing this issue as a duplicate for #6762
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_magento_magento2_issues_6762&d=DgMFaQ&c=N9aEhCy8U0rJkO1xCZf7rgM9fohfR5qe_N93viZd7O8&r=mbFmkVqaG5ogD6QHOzWrBjtwu0qH7TeQzXvoV1qb523sgyVSmSVMThKaMNrqu6mj&m=1U8J0iznJfsybYsiiXD5w9WMarSXD1WQjsn_ehKPBh0&s=CxfWXwx782gouFKw1goDfkIqnpFqFwsxqdNtmRFji9w&e=>,
> #6122
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_magento_magento2_issues_6122&d=DgMFaQ&c=N9aEhCy8U0rJkO1xCZf7rgM9fohfR5qe_N93viZd7O8&r=mbFmkVqaG5ogD6QHOzWrBjtwu0qH7TeQzXvoV1qb523sgyVSmSVMThKaMNrqu6mj&m=1U8J0iznJfsybYsiiXD5w9WMarSXD1WQjsn_ehKPBh0&s=D5EptGYlsDjE05ntv5P1Fxxv8UIdQfe-ysNrG8oTGeQ&e=>
> .
> Internal ticket for branch 2.1 - MAGETWO-58855
> The issue was already fixed and will be delivered in some of next releases.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_magento_magento2_issues_8124-23issuecomment-2D272447671&d=DgMFaQ&c=N9aEhCy8U0rJkO1xCZf7rgM9fohfR5qe_N93viZd7O8&r=mbFmkVqaG5ogD6QHOzWrBjtwu0qH7TeQzXvoV1qb523sgyVSmSVMThKaMNrqu6mj&m=1U8J0iznJfsybYsiiXD5w9WMarSXD1WQjsn_ehKPBh0&s=PeWwit8dk-msUWZra2oHa8M5i54-PyzC0YECL3K7mqw&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AX7ZMoklvhRFLIIwF-5FJbtArSNM8ppaWBks5rR4HugaJpZM4LihZc&d=DgMFaQ&c=N9aEhCy8U0rJkO1xCZf7rgM9fohfR5qe_N93viZd7O8&r=mbFmkVqaG5ogD6QHOzWrBjtwu0qH7TeQzXvoV1qb523sgyVSmSVMThKaMNrqu6mj&m=1U8J0iznJfsybYsiiXD5w9WMarSXD1WQjsn_ehKPBh0&s=6JmjdI2SYRfi_TrWEMA2uFU1gl6u7levxOxg8kDm3I4&e=>
> .
>



-- 
[image: Fairfax Media]
Angela Metcalfe | Business Analyst| Fairfax Media
t 02  | m 0402 154423| Angela.Metcalfe@fairfaxmedia.com.au

-- 
The information contained in this e-mail message and any accompanying files 
is or may be confidential. If you are not the intended recipient, any use, 
dissemination, reliance, forwarding, printing or copying of this e-mail or 
any attached files is unauthorised. This e-mail is subject to copyright. No 
part of it should be reproduced, adapted or communicated without the 
written consent of the copyright owner. If you have received this e-mail in 
error please advise the sender immediately by return e-mail or telephone 
and delete all copies. Fairfax Media does not guarantee the accuracy or 
completeness of any information contained in this e-mail or attached files. 
Internet communications are not secure, therefore Fairfax Media does not 
accept legal responsibility for the contents of this message or attached 
files.
