### ISSUE TITLE
Actions dropdown positioned against the last column, not against "Actions" colum

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#31379] opened 2020-12-21 12:46 UTC
### Preconditions (*)

1. Reproduced on Magento  2.4.1
2. Reproduced on  Magento 2.4.2 beta 1

### Steps to reproduce (*)
1. Change the columns order in Admin Grid
2. Click on any "Select" in "Actions" column

### Expected result (*)
![image](https://user-images.githubusercontent.com/1639941/102778492-f5058d00-4392-11eb-93a1-37e528e8e3f6.png)

### Actual result (*)
![image](https://user-images.githubusercontent.com/1639941/102778409-cdaec000-4392-11eb-85f9-17a8bd7979e7.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment] 2020-12-21 14:29
@lbajsarowicz The issue is reproducible on fresh 2.4-develop.

**Manual testing scenario:**

1. Add custom columns to the Pages grid;
2. Click on any "Select" in "Actions" column

**Actual Result:** :heavy_multiplication_x: Drop-down menu remained in the same position as it was

![Peek 2020-12-21 16-25](https://user-images.githubusercontent.com/51679138/102787351-9c8dba00-43a9-11eb-83c7-49d223fd1e9e.gif)

**Comment by magento-engcom-team** [comment] 2020-12-22 08:11
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40106` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mrtuvn** [comment] 2020-12-23 06:39
This issue can reproducible in 2.4.0 official

**Closed as completed** 2021-10-24 04:26 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Component: Ui, Reproduced on 2.4.x, Fixed in 2.4.x, Progress: PR in progress, Priority: P2, Priority: P3, Severity: S3, Issue: ready for confirmation
