### ISSUE TITLE
Wrong tax value on invoice

### ISSUE THREAD

**Issue by Naberdz** [magento/magento2#39455] opened 2024-12-10 09:20 UTC
### Preconditions and environment

- Magento version 2.4.6-p8

### Steps to reproduce

Create order from admin.
Create invoice.
Add another product to the order.
Create second invoice.

### Expected result

The tax of the second invoice should be tax from the added product, but it shows tax from first invoice.

### Actual result

Invoice in backend:
![Scherm­afbeelding 2024-12-10 om 10 17 31](https://github.com/user-attachments/assets/9afd1208-77dd-4073-8fa8-2ef4b464249d)

Invoice as pdf:
![Scherm­afbeelding 2024-12-10 om 10 18 11](https://github.com/user-attachments/assets/39ef8d90-18b0-4f03-b596-e5a6ecc5a822)

first invoice:
![Scherm­afbeelding 2024-12-10 om 10 19 05](https://github.com/user-attachments/assets/d17c09d3-e700-48f4-8ba3-4cf9c641e090)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-12-11 10:27
Hi @Naberdz,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


First Invoice :

<img width="1440" alt="Screenshot 2024-12-11 at 12 53 14 pm" src="https://github.com/user-attachments/assets/ad31e809-d14b-4b2e-b3d3-24aa55aea527">


Second Invoice :

<img width="1440" alt="Screenshot 2024-12-11 at 12 53 43 pm" src="https://github.com/user-attachments/assets/0f31cf3d-08a6-45a1-aecc-0c4b2bc1dbf6">


The tax of the second invoice form the added product only.

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by Naberdz** [comment] 2024-12-12 08:14
Hi @engcom-Bravo ,

if you go to settings -> tax -> display full tax summary then you will have my issue.
![Scherm­afbeelding 2024-12-12 om 09 12 38](https://github.com/user-attachments/assets/bc772dac-25a4-4d18-8cde-49388d3c802d)

if i switch that to no then i have normal invoice.
![Scherm­afbeelding 2024-12-12 om 09 13 27](https://github.com/user-attachments/assets/2f530059-bd4d-461f-a5b3-3bd0d393b78b)

**Comment by engcom-Bravo** [comment] 2024-12-13 09:32
Hi @Naberdz,

Thanks for your update.

We have tried to reproduce the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

<img width="1153" alt="Screenshot 2024-12-13 at 3 00 04 pm" src="https://github.com/user-attachments/assets/7a050857-fd01-4b72-9ca2-f72339b5aec7" />



<img width="1440" alt="Screenshot 2024-12-13 at 2 58 50 pm" src="https://github.com/user-attachments/assets/fc165bf8-5ed9-4bd1-b29c-965e2e824e06" />



<img width="1440" alt="Screenshot 2024-12-13 at 2 59 03 pm" src="https://github.com/user-attachments/assets/192f0b83-cc62-4827-8b80-0f731a8b7d4b" />



The tax of the second invoice form the added product only.

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-12-17 10:11
Hi @Naberdz,

Thanks for your update.

Magento\Tax\Model\Calculation this class is responsible for tax.

Since the issue is no more reproducible in Latest 2.4-develop Magento Instance.Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-12-17 10:11 UTC
Labels: Issue: needs update, Reported on 2.4.6-p8

**Comment by Naberdz** [comment] 2025-01-06 14:27
Disabling all modules and upgrading magento to 2.4.7-p3 doesn't solve the issue.

It seem that sales_order_tax  and sales_order_tax_item contains only 1 row so by adding second one
````INSERT INTO `sales_order_tax` (`tax_id`, `order_id`, `code`, `title`, `percent`, `amount`, `priority`, `position`, `base_amount`, `process`, `base_real_amount`) VALUES (NULL, '87942', 'Netherlands (standard)', 'Netherlands (standard)', '21.0000', '7.63', '0', '0', '7.63', '0', '7.63');````

and 
````INSERT INTO `sales_order_tax_item` (`tax_item_id`, `tax_id`, `item_id`, `tax_percent`, `amount`, `base_amount`, `real_amount`, `real_base_amount`, `associated_item_id`, `taxable_item_type`) VALUES (NULL, '394875', '228106', '21.0000', '7.63', '7.63', '7.63', '7.63', NULL, 'product');````

we have correct TAX values on both invoices.. 

so not sure why the additional records where not created, can it be that database is too large ?
