### ISSUE TITLE
Create Product Swatch Attribute via API

### ISSUE THREAD

**Issue by liamjtoohey** [magento/magento2#28195] opened 2020-05-12 08:38 UTC
### Preconditions (*)

- Magento 2.3.4
- PHP 7.3.3
- mysql 5.7.22

### Steps to reproduce (*)

- Attempt to create swatch product attribute via POST API endpoint `/V1/products/attributes`.
- Cannot set `swatch_input_type` in POST request body.

### Expected result (*)

- `swatch_input_type` is an allowed param in request body.
- Swatch product attribute successfully created.

### Actual result (*)

```
"Property \"SwatchInputType\" does not have accessor method \"getSwatchInputType\" in class \"Magento\\Catalog\\Api\\Data\\ProductAttributeInterface\"
```

I understand that the swatches functionality is slightly convoluted and devolved from the core product attributes - however it still appears to be a product attribute and is created in the same way as other product attributes.

Seeing as the swatch module does not provide any specific endpoints and swatch attributes programatically are the same as standard product attributes (just with `swatch_input_type` data set to them) - I'd expect the `/V1/products/attributes` endpoint to allow the creation of them.

**Comment by liamjtoohey** [comment] 2020-05-12 08:41
Swatch product attributes are seemingly created programatically by setting `swatch_input_type` data to the attribute. From debugging, it seems this flag is then used to save swatch configuration data to the `additional_data` field in the `catalog_eav_attribute` table:

```json
{
  "swatch_input_type": "visual",
  "update_product_preview_image": "0",
  "use_product_image_for_swatch": "0"
}
```

However, there seems to be no relative POST options for `swatch_input_type` in the swagger documentation of the product attribute endpoint - and also no way to set swatch configuration JSON to `additional_data` field of the `catalog_eav_attribute` table:

- https://devdocs.magento.com/swagger/#/catalogProductAttributeRepositoryV1/catalogProductAttributeRepositoryV1SavePost

I can deduce that this is because there are no relative methods in the product attribute interfaces to get/set this data:

- https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Api/Data/ProductAttributeInterface.php


The closest I've been able to get to creating a swatch attribute via the API is by setting the following string to the `frontend_input` field in my request body:

```json
"frontend_input": "swatch_visual"
```

This seems to create the attribute, but in a malformed state. Product swatch attributes should have a `frontend_input` type of "select". It seems Magento will actually reformat attributes with `frontend_input` type of "swatch_visual" but only when manually saved via the admin panel.

I understand that the swatches functionality is slightly convoluted and devolved from the core product attributes - however it still appears to be a product attribute and is created in the same way as other product attributes, so I would expect it would be possible to create a swatch attribute via the API.

**Comment by convenient** [comment] 2020-05-15 10:14
Just to add to the above, as a rough test and a _very_ naive approach we've tested the following patch and it seems to work

```diff
--- Api/Data/ProductAttributeInterface.php	2020-05-07 13:51:55.000000000 +0100
+++ Api/Data/ProductAttributeInterface.php	2020-05-07 13:51:39.000000000 +0100
@@ -38,4 +38,15 @@
      * @since 103.0.0
      */
     public function getExtensionAttributes();
+
+    /**
+     * @param string $swatchInputType
+     * @return $this
+     */
+    public function setSwatchInputType($swatchInputType);
+
+    /**
+     * @return string
+     */
+    public function getSwatchInputType();
 }

--- Model/ResourceModel/Eav/Attribute.php	2020-05-07 13:56:01.000000000 +0100
+++ Model/ResourceModel/Eav/Attribute.php	2020-05-07 13:50:49.000000000 +0100
@@ -658,6 +658,14 @@
     }

     /**
+     * @inheritdoc
+     */
+    public function getSwatchInputType()
+    {
+        return $this->_getData('swatch_input_type');
+    }
+
+    /**
      * Set whether WYSIWYG is enabled flag
      *
      * @param bool $isWysiwygEnabled
@@ -901,4 +909,13 @@
         $this->setData(self::IS_FILTERABLE_IN_GRID, $isFilterableInGrid);
         return $this;
     }
+
+    /**
+     * @inheritdoc
+     */
+    public function setSwatchInputType($swatchInputType)
+    {
+        $this->setData('swatch_input_type', $swatchInputType);
+        return $this;
+    }
 }
```

Obviously this violates a few things and swatch stuff shouldn't be in the catalog module but as a quick POC it does allow for creation of swatch attributes

**Comment by convenient** [comment] 2021-02-02 14:05
Just because an issue has not been fixed does not mean it does not exist?

**Comment by convenient** [comment] 2021-05-17 08:05
As I said in https://github.com/magento/magento2/issues/28195#issuecomment-771657248
> Just because an issue has not been fixed does not mean it does not exist?

**Comment by convenient** [comment] 2021-06-02 09:17
Bad robot. Does my previous comment not count as activity?

**Comment by engcom-Hotel** [comment] 2021-07-16 09:27
Hello @liamjtoohey,

Can you please share with us the payload you are using for creating the swatch attribute? It will help us in look into the issue.

Thanks

**Comment by liamjtoohey** [comment] 2021-07-22 08:38
@engcom-Hotel I believe the request body was something like the following, to the `V1/products/attributes` endpoint:
```json
  "attribute": {
    "attribute_code": "fabric7",
    "is_required": false,
    "frontend_input": "swatch_visual",
    "default_frontend_label": "Test Fabric",
    "scope": "global"
  }
```

As mentioned in my comment here: https://github.com/magento/magento2/issues/28195#issuecomment-627200831 - this has been the closest I was able to get, however, this does still create the attribute in a malformed state as product swatch attributes should have a `frontend_input` type of `select`.

**Comment by engcom-Hotel** [comment] 2021-07-23 09:27
Hello @liamjtoohey,

I have tried the API endpoint (V1/products/attributes) with your given payload and checked the table catalog_eav_attribute for the visual type and found that in the additional_data column we have swatch_input_type as "visual". Please find below screenshot for reference of catalog_eav_attribute table:

![image](https://user-images.githubusercontent.com/51681618/126763013-674d8139-30b4-4f69-b461-82ce9d18aafb.png)


It seems that there is no issue with this API. Please let us know if we missed anything in reproducing the issue.

Thanks

**Comment by liamjtoohey** [comment] 2021-07-23 10:05
@engcom-Hotel Could you confirm what this attribute looks like in admin panel? It's been a long time since I've checked on this ticket but I recall product swatch attributes should have a `frontend_input` type of `select` when created manually in admin panel. 

The API request above defines `"frontend_input": "swatch_visual"` which doesn't seem to be correct and I recall this caused some issues.

**Comment by engcom-Lima** [comment] 2021-08-30 12:50
Hi @liamjtoohey,

As requested please find the below screenshot of the Attribute on Admin Panel. Whatever we gave as input is correctly inserted in catalog_eav_attribute table and showing correct in admin so API seems to be working fine. 

<img width="1334" alt="Screenshot 2021-08-30 at 6 09 59 PM" src="https://user-images.githubusercontent.com/60198022/131340818-0cea33c8-7a5d-4bd1-8382-d7875d061a87.png">

It would be helpful if you can try to reproduce the issue again to check if you are able to do it and if issue exist, please let us know what you did differently ?

**Comment by engcom-Lima** [comment] 2021-09-14 04:01
Hi @liamjtoohey,

We have noticed that this issue has not been updated for a long time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Lima** 2021-09-14 04:01 UTC
Labels: Component: Api, Issue: needs update, Reported on 2.3.4
