### ISSUE TITLE
Exception on customer edit under restricted admin access

### ISSUE THREAD

**Issue by Kasoi-free** [magento/magento2#13951] opened 2018-03-05 10:36 UTC
Opening Customer Edit page while logged in under restricted admin user produces an exception:
https://screen.amasty.com/1520245526134.jpg
https://screen.amasty.com/1520245539478.jpg

### Preconditions

1. Magento 2.2.2, 2.1.5
2. PHP 7.0, MySQL 5.6

### Steps to reproduce

1. Create a new User Role in admin area
2. Set Custom permissions for the role like this: 
https://screen.amasty.com/1520246008492.jpg
https://screen.amasty.com/1520246026794.jpg
https://screen.amasty.com/1520246047704.jpg
https://screen.amasty.com/1520246070061.jpg
3. Add new admin user and assign him to this role
4. Log in to admin area as this newly created restricted admin user
5. Open Customers -> All Customers menu
6. Hit Edit button beside any customer: https://screen.amasty.com/1520245526134.jpg

### Expected result

1. Customer Edit page opens: https://screen.amasty.com/1520245897658.jpg

### Actual result

1. Exception: https://screen.amasty.com/1520245539478.jpg
Full exception is attached: [exception (2).txt](https://github.com/magento/magento2/files/1780426/exception.2.txt)

**Comment by magento-engcom-team** [comment] 2018-03-05 12:08
@Kasoi-free, thank you for your report.
The issue is already fixed in 2.2-develop, 2.3.0

**Closed as completed by magento-engcom-team** 2018-03-05 12:08 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by erikhansen** [comment] 2018-04-19 18:40
@magento-engcom-team I am experiencing this same issue on Magento 2.2.3. Glad to hear it's going to be fixed in a future release. Can you share a link to the commit?

@All - I had a role that had "Customers" selected, but I got an error when loading customer in the backend. I had to select these two additional items before I could get the customer to load in the admin:

![magento admin showmecables com-j4h0b](https://user-images.githubusercontent.com/129031/39011432-056e7eea-43d7-11e8-9042-1cc37e7f28fa.jpg)

Presumably it's because there are "Product Reviews" and "Newsletter" tabs/blocks on that page:

![magento admin showmecables com-gyqkd](https://user-images.githubusercontent.com/129031/39011482-29c96f02-43d7-11e8-9d3c-c60e1572135a.jpg)

**Comment by magento-engcom-team** [comment] 2019-04-05 15:20
Hi @Kasoi-free. Thank you for your report. 
The issue has been fixed in magento/magento2#18386 by @Thundar in 2.3-develop branch
Related commit(s):
 - [bd224a503ed8497fde59eb40175d5a603e771b35](https://github.com/magento/magento2/commit/bd224a503ed8497fde59eb40175d5a603e771b35)
 - [34fdfec0938b2305a3164f3360e931d3486d6515](https://github.com/magento/magento2/commit/34fdfec0938b2305a3164f3360e931d3486d6515)
 - [05e02c223d57fc6cfe669e84bff78cb2984460ce](https://github.com/magento/magento2/commit/05e02c223d57fc6cfe669e84bff78cb2984460ce)
 - [5ba0f1d01ed3386522d84d02b2c35070a81fe3d3](https://github.com/magento/magento2/commit/5ba0f1d01ed3386522d84d02b2c35070a81fe3d3)
 - [2766e2730aedc89cd5b6fe842c0d1108b7dcb8e2](https://github.com/magento/magento2/commit/2766e2730aedc89cd5b6fe842c0d1108b7dcb8e2)

The fix will be available with the upcoming 2.3.2 release.
