### ISSUE TITLE
SOAP API returns invalid XML when SOAP fault reason contains diacritics

### ISSUE THREAD

**Issue by ainigma32** [magento/magento2#38189] opened 2023-11-15 22:08 UTC
### Preconditions and environment

Magento version 2.4.6-p3

### Steps to reproduce

1. Create a store and set locale to de_DE
2. Add some products
3. Use the SOAP API to add another product to the DE store using a url_key that already exists

### Expected result

The SOAP client reports the error message: **URL-Key für den ausgewählten Store existiert bereits.**

### Actual result

The SOAP client fails with the message **looks like we got no XML document**

### Additional information

The problem lies in the way the SOAP fault is created by Magento. In [Magento\Webapi\Model\Soap\Fault.php](https://github.com/magento/magento2/blob/f6d4542518bf01f7d3ceca330d7290de62afcb4e/app/code/Magento/Webapi/Model/Soap/Fault.php#L252) the XML that is sent back by the SOAP server is not created by using DOMDocument but by string manipulation.
The problematic code is:
`$reason = htmlentities($reason);`
Using htmlentities here will encode all entities and not just the XML built-in entities. The resulting XML cannot be parsed because it contains unknown entities. 
Instead we should use htmlspecialchars:
`$reason = htmlspecialchars($reason, ENT_XML1);` 

I will try to create a PR to change this in the code base.Until then using a patch will create a workaround

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-12-07 10:57
Hi @ainigma32,

Thank you for reporting and collaboration.

Could you please provide us SOAP APi payloads for adding the products and also provide related documents and screenshots if possible it will helps us further to reproduce the issue.

Thanks.

**Comment by ainigma32** [comment] 2023-12-18 11:00
See attached files for the payload. While reproducing this issue I did notice that the translation is not found in the standard Magento translation (i.e. magento/language-de_de) but it is found in the community-engineering/language-de_de pacakage.

[payload_create2.xml.txt](https://github.com/magento/magento2/files/13702817/payload_create2.xml.txt)
[payload_create1.xml.txt](https://github.com/magento/magento2/files/13702818/payload_create1.xml.txt)

**Comment by ainigma32** [comment] 2024-01-13 13:58
@engcom-Bravo See above. Is that sufficient information for you to continue working on this issue?

**Comment by engcom-Bravo** [comment] 2024-01-16 09:35
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-01-16 12:11
Hi @ainigma32,

Thanks for your update.

We have tried with above xml requests in Magento 2.4 develop instance and we are getting XML as response.


![Screenshot from 2024-01-16 17-40-29](https://github.com/magento/magento2/assets/51680745/f34cc24d-2319-4118-bb03-d33c8a534bfd)



Could you please let us know if we are missing anything here.

Thanks.

**Comment by ainigma32** [comment] 2024-01-22 07:51
Hi @engcom-Bravo, there are 2 things missing: 
- You need to create the instance using: `give me 2.4-develop instance with extensions community-engineering/language-de_de`
- You need to send both payloads so that you will trigger the soapfault caused by an existing URL

Could you try using those parameters?

Thanks.

**Comment by ainigma32** [comment] 2024-01-25 08:39
Hi @engcom-Bravo,
Your print screen does not show the actual fault message. Is it in German? If it is not, try sending the request to the storeview that has German as its default language. The fault message should be something like: URL-Key für den ausgewählten Store existiert bereits.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-02-01 10:51
Hi @ainigma32,

Thanks for your update.

We have set the language as a German and the storeview is in German language.

![Screenshot from 2024-02-01 15-40-18](https://github.com/magento/magento2/assets/51680745/0f1a3355-0bf0-4c73-a0a9-36b597e4ef90)


We are getting the same response for both the storeviews.


![Screenshot from 2024-02-01 15-39-47](https://github.com/magento/magento2/assets/51680745/999cb1fd-dfd2-4d31-82ee-46267fec1fba)


![Screenshot from 2024-02-01 15-39-52](https://github.com/magento/magento2/assets/51680745/52346da1-21cf-435a-9965-dd9b81c6803e)

Kindly provide screenshots or screencast it will helps us to reproduce the issue to proceed further.Here we are sending requests using admin integration token.please provide information regarding this one.


Thanks.

**Comment by engcom-Bravo** [comment] 2024-02-23 06:40
Hi @ainigma32,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Bravo** 2024-02-23 06:40 UTC
Labels: Priority: P2, Progress: done, Issue: needs update, Reported on 2.4.6-p3
