### ISSUE TITLE
Magento Inventory (MSI) indexer clears whole Redis cache

### ISSUE THREAD

**Issue by OPielech** [magento/magento2#37760] opened 2023-07-17 08:12 UTC
### Preconditions and environment

- Magento 2.4.5-p1
- Access to redis-cli or Prometheus Redis Exporter for Grafana

### Steps to reproduce

1. Create new product via code or admin panel
2. Start MSI reindex process (Inventory - Inventory index (MSI))

### Expected result

MSI indexer clears Redis cache only for reindexing records.

### Actual result

MSI module uses dedicated class to clear cache `vendor/magento/module-inventory-cache/Plugin/InventoryIndexer/Indexer/SourceItem/Strategy/Sync/CacheFlush.php`, which use two classes for cleaning categories and products cache by tags
- `vendor/magento/module-inventory-cache/Model/FlushCacheByProductIds.php`
- `vendor/magento/module-inventory-cache/Model/FlushCacheByCategoryIds.php`

Both of them use `vendor/magento/module-inventory-cache/Model/FlushCacheByCacheTag.php` to send event for cleaning varnish and use core CacheInterface to clean Redis cache. This class has bug, that causes cleaning almost all tags that are saved in Redis.

In line 60 there is used method `registerEntities`, which because of plugin `vendor/magento/module-indexer/Model/Indexer/DeferCacheCleaning.php` do not add any ids to cache context

![Zrzut ekranu 2023-07-17 092311](https://github.com/magento/magento2/assets/56829225/ecd7904c-6bc9-43c2-b890-40f088408aab)

After this, Redis library (`vendor/colinmollenhour/cache-backend-redis/Cm/Cache/Backend/Redis.php`) sends `sinter` only for X_MAGE tag, which returs all tags in this set

![Zrzut ekranu 2023-07-17 092709](https://github.com/magento/magento2/assets/56829225/39dd2e3d-b054-4f07-8ab5-c584866c2c18)

Later in the same class those returned tags are deleted in 10k chunks

![Zrzut ekranu 2023-07-17 092859](https://github.com/magento/magento2/assets/56829225/7cc687f0-3bc7-4a6c-8655-8f70cd5f34f7)

In local variable it can be seen in redis-cli after command `dbsize`. Before and after reindex there is a massive key number drop

![Zrzut ekranu 2023-07-17 095415](https://github.com/magento/magento2/assets/56829225/6d6e2f5a-889f-4c0f-8af4-7709b882d291)

More serious situation is in our production environment, where in the weekend and after working hours, when any product is being created, expiring key number reaches more than milion. After first created products expiring keys number decreses to almost 0, what is presented in Grafana (UTC +2 time)

![Zrzut ekranu 2023-07-17 095812](https://github.com/magento/magento2/assets/56829225/55d30b15-33f8-4f2a-bc8f-f8c2be6f0369)

It is serious, because after such a Redis clean, there is huge increase in database CPU utilization, what in our case caused production timeout and we had to increase db resources. (Screen from AWS EC2 monitoring)

![Zrzut ekranu 2023-07-17 100153](https://github.com/magento/magento2/assets/56829225/d326ac30-6d9a-47d8-940d-2db245960d7a)

Is this problem known to You and is there any fix plan for this problem?

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by aligent-lturner** [comment] 2023-07-20 01:26
This is fixed in 2.4.6 by this commit - https://github.com/magento/inventory/commit/b6d7223b8ca3b13c4049b3b0f6efc645b0848e01

**Comment by engcom-Dash** [comment] 2024-01-03 05:34
Hi @OPielech 

Thanks for reporting and collaboration.

As per the above comments the issue is fixed on 2.4.6 by this commit - https://github.com/magento/inventory/commit/b6d7223b8ca3b13c4049b3b0f6efc645b0848e01

Please try the above fix and let us know if the issue still persists.

Thanks.

**Comment by engcom-Dash** [comment] 2024-01-19 11:21
Hi @OPielech 

Thank you for reporting and collaboration.

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Dash** 2024-01-19 11:21 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1
