### ISSUE TITLE
Coupon with Fixed amount discount for whole cart apply rule not working in graphql

### ISSUE THREAD

**Issue by rani-priya** [magento/magento2#30719] opened 2020-10-30 07:50 UTC
### Preconditions (*)

1. Magento version: 2.4
2. php version : 7.3 

### Steps to reproduce (*)

1. Go to magento backend
2. create a cart price rule with this configuration(In Apply set "**Fixed amount discount for whole cart**")
![image](https://user-images.githubusercontent.com/44425160/97674010-c5cd5080-1ab2-11eb-92e8-e0847588b743.png)

3. Then apply the same coupon on cart in by using graphql
4. In cart query check the grand total amount
![image](https://user-images.githubusercontent.com/44425160/97673910-91f22b00-1ab2-11eb-8f5d-88f2bfb34371.png)
![image](https://user-images.githubusercontent.com/44425160/97673932-9ddded00-1ab2-11eb-9555-a3a182167db6.png)

### Expected result (*)

1. Discount should be deducted from the grand total in cart query graphql

### Actual result (*)

1. Discount is not deducting from the grand total in cart query graphql

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by bharat1811** [comment] 2020-10-31 05:42
@magento I am working on this.

**Comment by bharat1811** [comment] 2020-10-31 05:43
@magento add to contributors team

**Comment by bharat1811** [comment] 2020-10-31 05:45
@magento add to contributors team

**Comment by bharat1811** [comment] 2020-10-31 09:42
@magento please provide me test instance URL and detail. 'CZ in the repository of the local above scenario is working fine.

**Comment by bharat1811** [comment] 2020-10-31 11:39
@magento give me 2.4-develop instance

**Comment by bharat1811** [comment] 2020-10-31 12:13
@rani-webkul 
The issue is not reproducible in the latest version.
#Issue: not reproducible

Steps to verify,

**1. Get customer cart details,**
{
  customerCart {
    id
    items {
      id
      product {
        name
        sku
      }
      quantity
    }
  }
}

**2. Apply created promo code,**
mutation {
  applyCouponToCart(
    input: {
      cart_id: "HvzaWRCngNlChASgYZkP6kF5SpeufPcv"
      coupon_code: "FLAT10"
    }
  ) {
    cart {
      applied_coupons {
        code
      }
    }
  }
}

**3. Get cart details,**
{
  cart(cart_id: "HvzaWRCngNlChASgYZkP6kF5SpeufPcv") {
    email
    billing_address {
      city
      country {
        code
        label
      }
      firstname
      lastname
      postcode
      region {
        code
        label
      }
      street
      telephone
    }
    shipping_addresses {
      firstname
      lastname
      street
      city
      region {
        code
        label
      }
      country {
        code
        label
      }
      telephone
    
      available_shipping_methods {
        amount {
          currency
          value
        }
        available
        carrier_code
        carrier_title
        error_message
        method_code
        method_title
        price_excl_tax {
          value
          currency
        }
        price_incl_tax {
          value
          currency
        }
      }
      selected_shipping_method {
        amount {
          value
          currency
        }
        carrier_code
        carrier_title
        method_code
        method_title
      }
    }
    items {
      id
      product {
        name
        sku
      }
      quantity
    }
    available_payment_methods {
      code
      title
    }
    selected_payment_method {
      code
      title
    }
    applied_coupons {
      code
    }
    prices {
        subtotal_including_tax{
             value
        currency
        },
        discount{
          amount{
              value
          }
      }
      grand_total {
        value
        currency
      }
    }
  }
}

**Comment by rani-webkul** [comment] 2020-11-01 13:32
@magento give me 2.4-develop instance

**Comment by rani-webkul** [comment] 2020-11-01 13:46
@bharat1811 it's still reproduceable on upper instance as well.
Please use below cart query and then check
{
  cart(cart_id: "l2X1hXV1PBgtdtMZMTseGWsVQzEcVpAi") {
    email
    billing_address {
        city
        country {
            code
            label
        }
        firstname
        lastname
        postcode
        region {
            code
            label
            region_id
        }
        street
        telephone
    }
    shipping_addresses {
        firstname
        lastname
        street
        city
        region {
            code
            label
            region_id
        }
        country {
            code
            label
        }
        telephone
        available_shipping_methods {
            amount {
                currency
                value
            }
            available
            carrier_code
            carrier_title
            error_message
            method_code
            method_title
            price_excl_tax {
                value
                currency
            }
            price_incl_tax {
                value
                currency
            }
        }
        selected_shipping_method {
            amount {
                value
                currency
            }
            carrier_code
            carrier_title
            method_code
            method_title
        }
    }
    items {
        id
        prices {
            row_total{
                value
            }
            row_total_including_tax
            {
                value
            }
            total_item_discount {
                value
            }
            price {
                value
            }
            discounts {
                label
                amount {
                    value
                }
            }
        }
        ... on SimpleCartItem {
          customizable_options {
            label
            values {
              value
            }
          }
        }
        ... on ConfigurableCartItem {
            configurable_options {
                id
                option_label
                value_id
                value_label
            }
        }
        ... on BundleCartItem {
            bundle_options {
                id
                label
                type
                values {
                    id
                    label
                    price
                    quantity
                }
            }
        }
        product {
            name
            sku
            stock_status
            price_range{ 
                minimum_price{ 
                    regular_price{ 
                        value 
                        currency 
                    } 
                } 
                maximum_price{ 
                    regular_price{ 
                        value 
                        currency 
                    } 
                } 
            }
            image {
            url
            label
            }
            ... on BundleProduct {
                dynamic_sku
                dynamic_price
                items {
                    option_id
                    title
                    required
                    type
                    position
                    sku
                    options {
                        id
                        quantity
                        position
                        is_default
                        price
                        label
                        product {
                            id
                            name
                            sku
                            image {
                                url
                                label
                            }
                            __typename
                        }
                    }
                }
            }
            ... on CustomizableProductInterface {
                options {
                    title
                    required
                    sort_order
                    option_id
                    __typename
                    ... on CustomizableDropDownOption {
                        title
                        value {
                            price_type
                            option_type_id
                            title
                            price
                            sku
                        }
                    }
                }
            }
            ... on ConfigurableProduct {
                configurable_options {
                    id
                    label
                    position
                    use_default
                    attribute_id
                    attribute_code
                    values {
                    value_index
                        label
                    }
                    product_id
                }
                variants {
                    product {
                        id
                        name
                        sku
                        stock_status
                        attribute_set_id
                        ... on PhysicalProductInterface {
                            weight
                        }
                        price_range{
                            minimum_price{
                                regular_price{
                                    value
                                    currency
                                }
                            }
                        }
                    }
                    attributes {
                        label
                        code
                        value_index
                    }
                }
            }
            crosssell_products {
                name
                sku
                price_range { 
                minimum_price { 
                    regular_price { 
                    value 
                    currency 
                    }
                    final_price { 
                    value 
                    currency
                    }       
                    discount {
                    amount_off
                    percent_off
                    }
                } 
                maximum_price { 
                    regular_price { 
                    value 
                    currency 
                    } 
                    final_price { 
                    value 
                    currency
                    }       
                    discount {
                    amount_off
                    percent_off
                    }          
                } 
                }
                image { 
                    url 
                    label 
                }
            }
        }
        quantity
    }
    available_payment_methods {
      code
      title
    }
    selected_payment_method {
      code
      title
    }
    applied_coupons {
      code
    }
    prices {
        discounts {
            amount {
                value
            }
            label
        }
        grand_total{
            value
            currency
        }
        subtotal_including_tax{
            value
            currency
        }
        subtotal_excluding_tax{
            value
            currency
        }
        subtotal_with_discount_excluding_tax{
            value
            currency
        }
        applied_taxes{
            amount {
                value
                currency
            }
            label
        }
    }
  }
}

![image](https://user-images.githubusercontent.com/44425160/97804541-a8e17a80-1c76-11eb-8022-25d9db1644dd.png)
![image](https://user-images.githubusercontent.com/44425160/97804567-c3b3ef00-1c76-11eb-9bd5-43619994a036.png)

**Comment by rani-webkul** [comment] 2020-11-09 08:40
@magento give me 2.4-develop instance

**Comment by sathiyaaa** [comment] 2020-12-17 10:36
@magento I am working on this

**Comment by sathiyaaa** [comment] 2021-01-05 06:27
@magento give me 2.4-develop instance

**Comment by atishgoswami** [comment] 2021-02-12 10:25
Thanks @rani-webkul for reporting this issue, I was also facing the same issue

This is the patch for the issue if anyone else might be looking for it 😄 
https://github.com/magento/quality-patches/blob/master/patches/os/MDVA-31363__fixes_cart_price_rule_coupon_does_not_apply_via_graphQl__2.4.0.patch

**Comment by mariuscris** [comment] 2021-02-14 19:16
Thank you @atishgoswami for the patch link. I have the same issue and I have tried to fix it with this patch:

`
--- a/vendor/magento/module-sales-rule/Model/Rule/Action/Discount/CartFixed.php
+++ b/vendor/magento/module-sales-rule/Model/Rule/Action/Discount/CartFixed.php
@@ -96,7 +96,7 @@
         if (!isset($cartRules[$rule->getId()])) {
             $cartRules[$rule->getId()] = $rule->getDiscountAmount();
         }
-        $availableDiscountAmount = (float) $cartRules[$rule->getId()];
+        $availableDiscountAmount = (float) $rule->getDiscountAmount();;
         $discountType = self::$discountType . $rule->getId();
`

I believe the main problem is linked with` \Magento\SalesRule\Model\Rule\Action\Discount\CartFixed` and how the calculate method was build. The purpose of getCartFixedRules' on quote is very confusing for me. I see this data linked with multi-shipping and "allow shipping discount" option. In my case, I use discount for the whole cart without shipping and no multi-shipping.

The issue described in https://github.com/magento/magento2/issues/31496 is most likely connected with this problem.
For the moment I will use both fixes, just in case the reset case is missing or forgotten.

**Comment by pykettk** [comment] 2021-03-10 11:55
+1 [for the solution](https://github.com/magento/magento2/issues/30719#issuecomment-778826680) from @mariuscris - worked for me! 😃

**Comment by JKair** [comment] 2021-07-12 06:00
I meet this bug too.

**Comment by riconeitzel** [comment] 2021-11-17 08:13
Confirmed that https://github.com/magento/magento2/issues/30719#issuecomment-778826680 fixes the problem for us on 2.3.7-p2 in the regular checkout.

@mariuscris you have a typo in your comment ";;"

**Comment by mariuscris** [comment] 2021-11-19 08:42
Thanks @riconeitzel for spotting the typo. It should be corrected by now

**Comment by ithunter101** [comment] 2022-08-10 12:34
Hi, I have an issue with cart Cart Price Rules.
If I make a new rule, it only apply to last product in cart.
Can anyone explain about it?

**Comment by engcom-November** [comment] 2022-09-21 11:43
Hi @rani-priya ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-09-21 11:43 UTC
Labels: Component: GraphQL, Priority: P2, Project: GraphQL, Progress: done, Issue: ready for confirmation, Issue: needs update, Reported on 2.4.0
