### ISSUE TITLE
getAppliedRuleIds() function no longer returns array of ruleIds

### ISSUE THREAD

**Issue by qrider** [magento/magento2#22757] opened 2019-05-07 03:26 UTC
### Preconditions (*)

1. getAppliedRuleIds() function no longer returns array of ruleIds

### Steps to reproduce (*)

1. In overridden template Magento_Checkout/templates/cart/item/default.phtml
`
/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$rules = $_item->getAppliedRuleIds();  
//returns null if no rules applied or returns empty string if a rule is applied
`

### Expected result (*)

1. return empty [] for no rules else array of ruleIds
2. If the function is deprecated or moved remove documentation from Magento\Quote\Model\Quote\Item\AbstractItem

### Actual result (*)

1. returns null if no rules applied or returns empty string if a rule is applied

**Comment by engcom-Charlie** [comment] 2019-10-07 14:05
Hello @qrider 
We are not able to reproduce this issue on the lates 2.3-develop branch.
So `getAppliedRuleIds()` function should return **null** if no rules applied(as described in the interface)
![image](https://user-images.githubusercontent.com/51680850/66297298-15653b00-e8f8-11e9-8b89-caf7e9efe171.png)
**My results:**
Case 1(with rule):
Function returns rule id
![image](https://user-images.githubusercontent.com/51680850/66297251-0088a780-e8f8-11e9-8bc0-2212c62dbc85.png)
Case 2(without rule):
Function returns **null**

So i have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-10-07 14:05 UTC
Labels: Issue: Format is valid
