### ISSUE TITLE
Customer data cart section is always reloaded

### ISSUE THREAD

**Issue by erfanimani** [magento/magento2#23937] opened 2019-07-29 10:33 UTC
### Preconditions (*)

1. Reproduced with Magento 2.3.1 and 2.3.2
2. Luma theme

### Steps to reproduce (*)

1. Add product to the cart

This causes an AJAX POST request to `/checkout/cart/add/uenc/...... `
Then it causes a refresh of customer data of the cart and message sections.

Up until now, everything is OK.

2. Navigate to another page

### Expected result (*)

1. Customer section is not reloaded, because our local storage is up to date with our session — we haven't made any POST or PUT requests that match any invalidation routes after we added a product to the cart.

### Actual result (*)

1. Customer cart is refreshed

What's happening? It seems that our cart section of customer data is refreshed on every pageload. This defeats the purpose of customer local storage.

Why is this happening?

On this line, Magento compares a variable called `store_id`: https://github.com/magento/magento2/blob/2.3.2/app/code/Magento/Checkout/view/frontend/web/js/view/minicart.js#L106

But actually the variable is called `storeId`: https://github.com/magento/magento2/blob/2.3.2/app/code/Magento/Checkout/CustomerData/Cart.php#L104

Fixing minicart.js look for a the camelCase version of the variable should work.

**Comment by erfanimani** [comment] 2019-07-29 10:34
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-29 10:34
Hi @erfanimani. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-29 10:34
Hi @erfanimani, here is your [Magento instance](https://i-23937-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23937-2-3-develop.instances.magento-community.engineering/admin](https://i-23937-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by erfanimani** [comment] 2019-07-29 10:42
Can reproduce on vanilla instance.

**Comment by hostep** [comment] 2019-07-29 12:43
Let's close this as a duplicate of https://github.com/magento/magento2/issues/23208
There is a pending PR to fix it: https://github.com/magento/magento2/pull/23282

Thanks for the report!

**Closed as completed by hostep** 2019-07-29 12:43 UTC
Labels: Issue: Format is valid
