### ISSUE TITLE
CE 2.1.2 WEBAPI bug: catalogProductRepositoryV1SaveRequest removes all existing variations for configurable item

### ISSUE THREAD

**Issue by ericahoekerd** [magento/magento2#7909] opened 2016-12-21 10:40 UTC
### Steps to reproduce
1. Create a configurable item in Magento(manually or by API)
2. Add some variations to the item
3. Send an update by WEBAPI with the method: catalogProductRepositoryV1SaveRequest, don't include any info related to the attached simples

### Expected result
1. Do just a save for the product with the info in the XML request, leave the variations untouched

### Actual result

1. All existing variations / simple items are removed for the configurable

**Comment by ericahoekerd** [comment] 2016-12-21 10:56
additional info: seems the same issue as: https://github.com/magento/magento2/issues/6884

saving product is breaking relationships for the simple items on a configurable item

**Comment by VasylShvorak** [comment] 2017-07-05 15:00
@tinxit Thanks for reporting this issue. Created internal issue MAGETWO-70481 to investigate and track this issue.

**Comment by magento-engcom-team** [comment] 2017-10-06 08:30
@tinxit, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by magento-engcom-team** [comment] 2018-07-30 06:15
Hi @tinxit

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment] 2018-08-20 09:03
@tinxit thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Closed as completed by magento-engcom-team** 2018-08-20 09:03 UTC
Labels: Issue: Ready for Work, bug report, Component: Framework/Webapi, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Fixed in 2.3.x, Issue: Format is not valid, triage wanted
