### ISSUE TITLE
Magento 2 Product import issue

### ISSUE THREAD

**Issue by Pratik4632** [magento/magento2#37339] opened 2023-04-05 12:13 UTC
### Preconditions and environment

- Magento version 2.4.4
- Anything else that would help a developer reproduce the bug
I've tried to import Product csv file but fill can't upload.

### Steps to reproduce

In Magento 2, I have Product bulk import csv file. i've check all the possible problem related solution like check all custom module and download sample product csv file and i tried to upload that file but i am facing same issue and check all the configuration but there have dose't issue on store.

### Expected result

I want to upload all product through product bulk import.

### Actual result

I want to import the product bulk csv file but i am facing the error and the error is file is not uploaded. i check all the problem related solution.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-04-10 13:47
Hi @Pratik4632,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.

We are able to import the CSV file successfully.

Kindly check your CSV file and **Make sure your file isn't more than 2M**.


Please refer this document https://experienceleague.adobe.com/docs/commerce-admin/systems/data-transfer/import/data-import.html?lang=en. regarding importing the CSV file.


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-04-26 06:05
Hi @Pratik4632,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-04-26 06:05 UTC
Labels: Issue: needs update, Reported on 2.4.4
