### ISSUE TITLE
Login Popup appears while clicking "Proceed to checkout" even after logged in

### ISSUE THREAD

**Issue by NanthiniMuralidaran** [magento/magento2#4589] opened 2016-05-20 04:11 UTC
## Steps to reproduce

In this case,I faced that popup issue.
I added a product to the cart before log in to the site.Then i logged out from the site.Again i added a product to the cart before log in.And then i logged in and clicked "Proceed to checkout",the popup appears.
## Expected result

Popup should not come,it should allow to checkout
## Actual result

Popup appears

**Comment by ishakhsuvarov** [comment] 2016-05-24 08:18
@NanthiniMuralidaran Thank you for reporting. Please let us know how did you configure the **Checkout Options** section (under **Stores > Configuration > Sales > Checkout**) and Magento version you are using.
Thanks.

**Comment by NanthiniMuralidaran** [comment] 2016-05-24 08:24
Thank you for your response.Iam using the Magento 2.0.5 version and here
am attaching the pictures of checkout configuration in admin panel.
Thanks in advance.

On Tue, May 24, 2016 at 1:49 PM, Ievgen Shakhsuvarov <
notifications@github.com> wrote:

> @NanthiniMuralidaran https://github.com/NanthiniMuralidaran Thank you
> for reporting. Please let us know how did you configure the _Checkout
> Options_ section (under _Stores > Configuration > Sales > Checkout_) and
> Magento version you are using.
> Thanks.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/magento/magento2/issues/4589#issuecomment-221198521

## 

This message originates from LeanSwift, Inc and may contain confidential 
information intended solely for the use of the addressee. If you are not 
the intended recipient and have received this message in error, please 
notify admin@leanswift.com and delete this message from your system. Any 
unauthorized reading, distribution, copying, or other use of this message 
or its attachments is strictly prohibited. All personal messages express 
solely the sender's views and not those of LeanSwift, Inc. This message may 
not be copied or distributed without this disclaimer.

**Comment by NanthiniMuralidaran** [comment] 2016-05-24 08:28
![checkout_one](https://cloud.githubusercontent.com/assets/17905842/15497287/999760b2-21b7-11e6-909d-7038cc66fd0e.PNG)
![checkout_two](https://cloud.githubusercontent.com/assets/17905842/15497288/999f0d80-21b7-11e6-9d8e-7fbc097e47d2.PNG)

**Comment by ricardojle** [comment] 2016-06-17 01:05
I have the same problem.
The best way to simulate the problem:

```
change the config -> Settings / Sales / Checkout / After Adding a Product Redirect to Shopping Cart = yes

delete the browser cache
add item to my cart
click proceed to checkout
```

The problem occurs only once , that is, on the first visit . Then it works normally.

**Comment by GrimNotepad** [comment] 2016-08-22 16:34
We are having this problem now with 2.0.7.
Is there a fix yet?

**Comment by AJCheeseman** [comment] 2016-08-22 16:40
We are having this problem now with 2.0.7.
Is there a fix yet?

**Comment by pboisvert** [comment] 2016-08-22 16:49
removing needs update label as info seemingly has been provided. Adding "bug" label to continue investigation

**Comment by SerhiyShkolyarenko** [comment] 2016-10-12 10:15
@NanthiniMuralidaran @ricardojle @AJCheeseman is it still reproducible for you on 2.0.9 or 2.1.1? Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by SerhiyShkolyarenko** [comment] 2016-11-07 12:56
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by SerhiyShkolyarenko** 2016-11-07 12:56 UTC
Labels: bug report, Progress: needs update, Component: Checkout

**Comment by SilvanLaroo** [comment] 2016-12-27 16:00
We still have this error on Magento 2.0.10. We've disabled it from the config, enabled guest checkout, but the popup still appears.
