### ISSUE TITLE
Unable to place order from message queue

### ISSUE THREAD

**Issue by alpnagargi** [magento/magento2#37692] opened 2023-06-30 07:05 UTC
### Preconditions and environment

- 2.4.5
- I am trying to place order from message queue but unable to place order getting No such entity with entityId =.
- Same is happening while reordering form admin.
<img width="878" alt="BulkOrder" src="https://github.com/magento/magento2/assets/22211069/98e2397f-6c21-4a14-b33a-719825da6818">

### Steps to reproduce

- Create message queue
- Create quote 
- Place order programmatically.

### Expected result

Order should be placed successfully.

### Actual result

No such entity with entityId = 
There is some issue with reserved id.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2023-09-07 10:27
Hello @alpnagargi,

Thanks for the report and collaboration!

We have tried to reproduce the issue in the Magento 2.4-develop branch but it seems the issue is not reproducible for us. We are able to create the order via message queue. 

Please refer to the below screenshot for reference:

![image](https://github.com/magento/magento2/assets/51681618/6b5abd7d-b625-441a-b647-842c16aefc70)

Can you please let us know the module details in which you are facing the issue?

Thanks

**Comment by engcom-Hotel** [comment] 2023-09-21 08:18
Dear @alpnagargi,

We have noticed that this issue has not been updated for a long time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2023-09-21 08:18 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.5
