### ISSUE TITLE
[BUG] Product gallery opening by mistake

### ISSUE THREAD

**Issue by Den4ik** [magento/magento2#21789] opened 2019-03-16 12:13 UTC
### Preconditions (*)

1. magento 2.3-develop

### Steps to reproduce (*)

1. Open product page
2. Click to product qty move cursor to product image and up mouse button

### Expected result (*)

![b5efn_2019_03_16_15_09_19](https://user-images.githubusercontent.com/1129623/54475050-d48fc280-47fd-11e9-94b8-bf70215bcbee.gif)

### Actual result (*)

![i3rhh_2019_03_16_15_10_45](https://user-images.githubusercontent.com/1129623/54475053-d9547680-47fd-11e9-8d1f-34acf20bc7ca.gif)

**Comment by magento-engcom-team** [comment] 2019-03-16 12:13
Hi @Den4ik. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Den4ik do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by amol2jcommerce** [comment] 2019-03-18 06:10
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-18 06:10
Hi @amol2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-18 06:10
Hi @amol2jcommerce, here is your [Magento instance](https://i-21789-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21789-2-3-develop.instances.magento-community.engineering/admin](https://i-21789-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by DanielRuf** [comment] 2019-03-18 06:12
Hi, can you also provide some info in which browsers this happens?

**Comment by Den4ik** [comment] 2019-03-18 06:30
Hi @DanielRuf 
Chrome 72, 73
Safari 12.0.3
on OS X

FF was not affected by the problem

**Comment by magento-engcom-team** [comment] 2019-03-18 08:04
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-03-18 08:14
@shikhamis11 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-03-18 08:15
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98751`, `MAGETWO-98752` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-04-09 16:15
Hi @Den4ik. Thank you for your report. 
The issue has been fixed in magento/magento2#21790 by @Den4ik in 2.3-develop branch
Related commit(s):
 - [9b324e804c58ed2b05c9646bcd7c781ecf113edc](https://github.com/magento/magento2/commit/9b324e804c58ed2b05c9646bcd7c781ecf113edc)
 - [55d5daa97fa37fa9276ecd90536da1a1929c0e5a](https://github.com/magento/magento2/commit/55d5daa97fa37fa9276ecd90536da1a1929c0e5a)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-04-09 16:15 UTC
Labels: Issue: Ready for Work, Component: Catalog, Area: Frontend, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Area: Lib/Frontend

**Comment by magento-engcom-team** [comment] 2019-04-17 12:10
Hi @Den4ik. Thank you for your report. 
The issue has been fixed in magento/magento2#22250 by @Den4ik in 2.2-develop branch
Related commit(s):
 - [66bacdb4129b0fc7beff62f517d06fe8b4e623b7](https://github.com/magento/magento2/commit/66bacdb4129b0fc7beff62f517d06fe8b4e623b7)

The fix will be available with the upcoming 2.2.9 release.
