### ISSUE TITLE
Instant Purchase on product page not working properly.

### ISSUE THREAD

**Issue by afavata** [magento/magento2#22045] opened 2019-03-29 17:23 UTC
Instant Purchase on product page not working properly.

### Preconditions (*)
Magento 2.3.1
PHP 7.2.15

### Steps to reproduce (*)
With a well working Paypal Express Checkout, Configure magento settings as follow:

set yes to "Display on Product Details Page"  (>configuration>sales>payment methods>paypal>express checkout)

set yes to "Enable Instant Purchase" (>configuration>Sales>instant purchase)

### Expected result (*)
Correct behaviour is to show a button in product page to allow immediate purchase.
The button is correctly shown and when clicked the items is correctly added to the cart but it opens a paypal popup that loops infinitely.

Normal behaviour is to access to the paypal pannel to finalize payment

### Actual result (*)
A paypal popup opens and loops infinitely.

Other issues:  
Disabling "Instant Purchase" setting... the button in product page is shown anyway.
Disabling also "Display on Product Details Page"... the button in product page is shown anyway.

**Please correct this bahaviour urgently as many customers are leaving the shop due for the incapacity to finalize payment.**

**Comment by afavata** [comment] 2019-03-29 17:29
@magento-engcom-team give me {$version} instance

**Comment by afavata** [comment] 2019-03-29 17:30
@magento-engcom-team give me 2.3.1-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-29 17:31
Hi @afavata. Thank you for your request. I'm working on Magento 2.3.1-develop instance for you

**Comment by shikhamis11** [comment] 2019-03-29 18:51
@afavata you can ask for 2.3-develop instance

**Comment by afavata** [comment] 2019-03-29 18:54
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-29 18:54
Hi @afavata. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-29 18:55
Hi @afavata, here is your [Magento instance](https://i-22045-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22045-2-3-develop.instances.magento-community.engineering/admin](https://i-22045-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by afavata** [comment] 2019-03-29 19:13
Ok... tested!!!
I cannot make a full test as in this case I should put some private setting for Paypal profile.
Anyway after having configured 1 product and paypal setting with false data, in product page are shown 2 buttons (paypal, paypal credit). Clicking on paypal i receive an issue becouse obviously the settings are not correct. So I cannot test whether it loops!

I tryed to disable "Display on Product Details Page" and "Enable Instant Purchase" and in both cases the buttons are shown anyway.

**Please do you have a workaround????**

**Comment by afavata** [comment] 2019-04-02 09:57
@Nazar65 Thanks for having assigned this issue... please note it is reproducible on 2.3.1 and 2.3-develop, as well.

**Comment by codazon** [comment] 2019-04-03 08:34
Hi, We have same issue with default luma theme on magento 2.3.1. "Display on Product Details Page" value change to "No" but nothing happen https://prnt.sc/n6sqwb, https://prnt.sc/n6srlx

**Comment by Userr017** [comment] 2019-04-05 08:58
It is there any temporary solution to hide product page paypal buttons?

**Comment by afavata** [comment] 2019-04-06 09:59
@Nazar65 Hi... may you figure out how to disable temporary the buttons modifing codes?
Purchasers are leaving the website as the cannot finalized payment.

Thanks

**Comment by Nazar65** [comment] 2019-04-06 13:40
Hi @afavata, currently i'm working on this, i will leave a temporary fix here as soon as possible.

**Comment by afavata** [comment] 2019-04-06 13:44
Thanks Indeed!!!

**Comment by Nazar65** [comment] 2019-04-09 13:14
@afavata temporary fix is to comment this line to disable this buttons`app/code/Magento/Paypal/view/frontend/web/js/in-context/product-express-checkout.js 
`
`line 27 //this.renderPayPalButtons(element);`
i'm will provide a pr soon

**Comment by afavata** [comment] 2019-04-09 18:16
@Nazar65 Thank you indeed for the "temporary fix".

I do make note that for some (like me) the right path to product-express-checkout.js file is: 

_vendor/magento/module-paypal/view/frontend/web/js/in-context/product-express-checkout.js_

This dipend on how Magento was installed.

**Comment by Nazar65** [comment] 2019-04-10 09:53
@afavata i'm made a PR with proper fix for this.

**Comment by afavata** [comment] 2019-04-10 16:27
@Nazar65 Well done Nazar... I have tested the updated code and now button is shown or hidden correctly depending on  backend configuration setting. Thanks indeed.

Anyway there is a wrong bahaviour still to be resolved related to this opened issue  #22045:
if button is enabled and paypal express well configured, clicking on the button.. the item is correctly added to the cart, a paypal windows popup on the screen but loops infinitely

**Comment by Nazar65** [comment] 2019-04-10 16:33
@afavata ok, i'm will retest and try to fix this.

**Comment by Nazar65** [comment] 2019-04-11 07:38
Hi @afavata i'm not able to reproduce second scenario.
![deepin-screen-recorder_Select area_20190411103724](https://user-images.githubusercontent.com/2481206/55939232-f128ea00-5c45-11e9-806a-7fceedf646a7.gif)

**Comment by afavata** [comment] 2019-04-16 09:50
@Nazar65 Sorry for the delay in replying but out of the office for some days...
That's weird. I did multiple tests and all the time the Paypal panel keep stuck with the round circle running infinitely. I have no problem with Paypal in the standard checkout process.
Any suggest?

**Comment by Nazar65** [comment] 2019-04-16 09:54
@afavata maybe this related to some of your configuration ?

**Comment by afavata** [comment] 2019-04-16 10:18
@Nazar65  I'll double check and let you know...
thanks for your support

**Comment by magento-engcom-team** [comment] 2019-05-01 11:05
Hi @afavata. Thank you for your report. 
The issue has been fixed in magento/magento2#22260 by @Nazar65 in 2.3-develop branch
Related commit(s):
 - [233e4c51f7d525f4573b11a24ae5a81c13762343](https://github.com/magento/magento2/commit/233e4c51f7d525f4573b11a24ae5a81c13762343)

The fix will be available with the upcoming 2.3.3 release.

**Closed as completed by magento-engcom-team** 2019-05-01 11:05 UTC
Labels: Issue: Clear Description, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Paypal

**Comment by Sharlyll** [comment] 2019-06-08 03:40
Hi, for us non-techy fellows, the fix is to replace the three files with those by @Nazar65 right?
I did that but the buttons continue to appear please see image

please help.
thanks alot!
![Screenshot 2019-06-08 at 6 38 24](https://user-images.githubusercontent.com/22851271/59141579-35233b80-89b8-11e9-8213-77ff36e7706f.png)

**Comment by mrlerch** [comment] 2019-06-09 20:51
I am having the same problems + a PayPal related issue when trying to place an order in Magento Admin. When will Magento 2.3.3 update be released? Rough estimate. I hope that these bugs can be fixed. Thank you in advance.
