### ISSUE TITLE
Uploaded / selected Catalog Categories Thumbnail Image not showing up after save in admin

### ISSUE THREAD

**Issue by harizyusoff** [magento/magento2#33971] opened 2021-09-02 05:29 UTC
### Preconditions (*)

1. Magento 2.4.2
2. PHP 7.4
3. MySQL 8.0
4. Apache 2.4
5. Composer 2.1.3
6. Elasticsearch 7.13.2
5. No Varnish and Redis installed

### Steps to reproduce (*)

1. Go to Catalog > Categories > Thumbnail Image section
2. Upload or any images from the Select from Gallery button
3. Click Save button after images successfully uploaded or selected
4. Go to Catalog > Categories > Thumbnail Image section, check whether the uploaded or selected image shown up in that section

### Expected result (*)

1. The expected result it should show image uploaded after Save button clicked
2. Example screenshot how it looks like in Catalog > Categories > Content section <br>
![Screenshot 2021-09-02 at 1 09 37 PM](https://user-images.githubusercontent.com/44669042/131785522-3fbb541a-0a30-426f-92b7-1ea02f442ea8.png)
[](url)

### Actual result (*)

1. The actual result is no image shown in the Catalog > Categories > Thumbnail Image section
2. Example of the current result after Save button clicked <br>
![ezgif com-gif-maker](https://user-images.githubusercontent.com/44669042/131785953-00bab833-be37-441a-8fc5-1cf50bb4d40a.gif)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by harizyusoff** [comment] 2021-09-02 05:30
@magento give me 2.4-develop instance

**Comment by harizyusoff** [comment] 2021-09-02 05:56
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2021-09-02 10:46
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible.
Steps performed:
Created a root category with image: Go to Catalog > Categories > Thumbnail Image section and saved
Opened the category again - No issue: Thumbnail image is displayed as expected
Edited existing sub root category and uploaded image and saved
Thumbnail image is showing as expected in content section.
![image](https://user-images.githubusercontent.com/60198231/131830456-9828b33f-b43e-437a-b900-7cd3fd2536cc.png)
@harizyusoff , kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by harizyusoff** [comment] 2021-09-02 12:51
@engcom-November yeah the image is showing up in **Catalog > Categories > Content** section in my website but it does not showing up in the **Catalog > Categories > Thumbnail Image** section. Here I've highlighted the section for you. Catalog > Categories > Content section and Catalog > Categories > Thumbnail Image are two different things. The one that image not showing up after save is in this section Catalog > Categories > Thumbnail Image <br>
![Screenshot 2021-09-02 at 8 48 40 PM](https://user-images.githubusercontent.com/44669042/131846470-e9087cfd-a091-4ad0-97e4-8f3c48c2b1a1.png)

**Comment by harizyusoff** [comment] 2021-09-03 02:25
@magento give me 2.4-develop instance

**Comment by harizyusoff** [comment] 2021-09-03 03:27
@magento give me 2.4-develop instance

**Comment by harizyusoff** [comment] 2021-09-03 06:07
Hi @engcom-November, any update on this ?

**Comment by harizyusoff** [comment] 2021-09-03 20:22
@magento give me 2.4-develop instance

**Comment by harizyusoff** [comment] 2021-09-03 20:26
@magento give me 2.4-develop instance

**Comment by harizyusoff** [comment] 2021-09-05 15:40
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2021-09-06 10:02
Hi @harizyusoff ,
Current behavior of Magento 2.4-develop branch and 2.4.3 version does not have Catalog > Categories > Thumbnail Image section.
This feature is neither available in Open source version nor commerce edition
Kindly refer the [docs](https://docs.magento.com/user-guide/catalog/categories.html), [creating categroies](https://docs.magento.com/user-guide/catalog/category-create.html) for further understanding.
![image](https://user-images.githubusercontent.com/60198231/132199854-8adb5181-4405-4290-8f8b-77aa9a852df2.png)

Kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if the issue is still reproducible.
Thank you

**Comment by harizyusoff** [comment] 2021-09-07 07:22
Hi @engcom-November, have you tried this in 2.4.2 version ? [This](https://github.com/magento/magento2/releases/tag/2.4.2) is the current version, I've used in my site

**Comment by harizyusoff** [comment] 2021-09-08 04:34
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2021-09-08 06:36
Hi @harizyusoff ,
Its recommended to verify the issues on Magento 2.4-develop branch as it has the latest code base. However I checked this on 2.4.3 open source version as well but does not have this section ( Catalog > Categories > Thumbnail Image )
Kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if the issue is still reproducible.
Thank you.

**Comment by harizyusoff** [comment] 2021-09-08 07:00
Hi @engcom-November, understood that you installed Magento version of 2.4.3 open source, but have you try this Magento version of 2.4.2 [here](https://github.com/magento/magento2/releases/tag/2.4.2) ? Also, it is quite frustrated because @magento didn't able to provide me any 2.4-develop instance for me since the day I've created the issue, do you know any issue why I'm not able to get that ?

**Comment by engcom-November** [comment] 2021-09-09 08:37
Hi @harizyusoff ,

Clear/Vanilla installation of Magento instance from bot has very limited access, email sending is not configured etc. so its ok only for very basic issue reports. Please refer for more details about this tool: [Deploy Vannila Magento Instance](https://devdocs.magento.com/contributor-guide/contributing.html#vanilla-pr)

I verified this issue on Magento 2.4.2-P1 version but cannot able to reproduce this issue. Catalog > Categories > Thumbnail Image section is not present in Magento 2.4.2-P1 version aswell.
Please try again to get Magento 2.4-develop instance or use your local environment for 2.4-develop installation and recheck the issue if its still reproducible, please provide missing configuration details/steps.
Thank you.

**Comment by harizyusoff** [comment] 2021-09-09 09:19
@magento give me 2.4.2 instance

**Comment by harizyusoff** [comment] 2021-09-09 09:40
Hi @engcom-November just found out that section is added up from theme installed in my website. Will check this with theme support about this. Thanks !

**Comment by harizyusoff** [comment] 2021-09-10 07:49
@magento give me 2.4.2 instance

**Comment by engcom-November** [comment] 2021-09-23 05:45
Hi @harizyusoff ,

We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-09-23 05:45 UTC
Labels: Component: Catalog, Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.2
