### ISSUE TITLE
No results on other than first search pages when using elasticsearch

### ISSUE THREAD

**Issue by pierzakp** [magento/magento2#25378] opened 2019-10-30 15:57 UTC
### Preconditions (*)

1. Magento 2.3.3 CE & EE, 2.3-develop  
2. Elastic Search 6

### Steps to reproduce (*)

1. Let's assume that our page limit is configured to 10.
2. Search products using some phrase where you're sure that there are more results than the configured limit on a page which is 10.

### Expected result (*)

1. Expect that will have results on each page rendered in the pagination.
2. No limit and offset will be applied when using elastic search.

### Actual result (*)

1. On the bottom of the search, results pagination will be rendered, but if you will click on the second, third, etc page no results message will be displayed.
2. Select query to database contains "LIMIT 10 OFFSET 10" part, elastic search applies condition with particular entity ids, as result there will be always only 10 results, due to limit and offset query has no results. Preview of the mentioned part of the query for:
`(e.entity_id IN (8357, 3524, 18671, 8360, 8390, 3971, 11213, 3527, 8387, 11393)) ORDER BY FIELD(e.entity_id,8357,3524,18671,8360,8390,3971,11213,3527,8387,11393) ASC
 LIMIT 10 OFFSET 10`.

**Comment by magento-engcom-team** [comment] 2019-10-31 10:27
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22616` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by pierzakp** [comment] 2019-10-31 10:29
There is already [PR](https://github.com/magento/magento2/pull/25379).

**Comment by engcom-Charlie** [comment] 2019-12-04 08:57
Hello @pierzakp 

We are not able to reproduce this issue on the latest 2.3-develop branch now(fixed).
Unfortunately i have to close it. 

Thank you for contribution and collaboration!

**Closed as completed by engcom-Charlie** 2019-12-04 08:57 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Elasticsearch

**Comment by gaiterjones** [comment] 2019-12-04 10:32
For those of us still experiencing this issue after upgrading to 2.3.3 has anybody got a fix that works. The specific changes in the PR made no difference - or do we need to wait for 2.3.4 ?

**Comment by kunzi** [comment] 2019-12-20 11:41
I too still have this problem after applying patch to 2.3.3. Any additional fixes?

**Comment by gaiterjones** [comment] 2019-12-31 08:29
@kunzi - don't think this will be fixed this decade...

**Comment by kunzi** [comment] 2019-12-31 08:36
@gaiterjones As a workaround I installed Amasty's Improved Layered Navigation extension and that fixed this issue.

**Comment by gaiterjones** [comment] 2019-12-31 17:04
@kunzi - do you mean Search or Layered Navigation? Not sure why the Amasty layered navigation extension would this fix elastic search problem? I expect 2.3.4 will be released soon will wait and see if the problem gets fixed then...

**Comment by kunzi** [comment] 2019-12-31 23:38
@gaiterjones I have no idea why, but after enabling the Amasty's extension all the pagination problems we had disappeared. If I remember correctly we had this pagination problem on category pages and on search result page.

**Comment by gaiterjones** [comment] 2020-01-02 10:56
Turns out another extension was not compatible with Elastic Search 6 in 2.3.3 and created exactly the same pagination issue as described here. Moral of the story is *always* check your modules for incompatibility first...

**Comment by onepack** [comment] 2020-07-03 07:51
I have a customer now on M2.3.5-p1 and they are now having this issue. Can I still use the 2.3.3 patch for M.2.3.5-p1 ??
