### ISSUE TITLE
GRAPHQL - Product query crosssell_products is not store scoped

### ISSUE THREAD

**Issue by alexmtch** [magento/magento2#36029] opened 2022-08-25 14:46 UTC
### Preconditions and environment

Magento 2.4.3

### Steps to reproduce

- Create a product A, assign as cross sell product B and C.
- Have a default store and create a store A
- In your default category :
  - in default store set A,B,C as products in category
  - in store A, set A and B as products in category
- Run this graphql query and add as header Store the store code of your store A
```
products(
    filter: { 
        "sku": {
            "eq": "A"
        }
    }
    pageSize: 999
) {
    items {
        sku
        crosssell_products {               
            sku            
        }
    }
}
```

### Expected result

```
{
    "data": {
        "products": {
            "items": [
                {
                    "sku": "A",
                    "crosssell_products": [
                        {
                            "sku": "B"
                        }
                    ]
                }
            ]
        }
    }
}
```

### Actual result

```
{
    "data": {
        "products": {
            "items": [
                {
                    "sku": "A",
                    "crosssell_products": [
                        {
                            "sku": "B"
                        },
                        {
                            "sku": "C"
                        }
                    ]
                }
            ]
        }
    }
}
```

### Additional information

It's due to this class : `\Magento\CatalogGraphQl\Model\Resolver\Products\DataProvider\Product`
There is no setStore instruction, so in the mysql query you'll get something like :

```
INNER JOIN `catalog_category_product_index_store1` AS `cat_index` ON cat_index.product_id=e.entity_id AND
cat_index.store_id=1 AND cat_index.visibility IN(2, 4) AND cat_index.category_id=2
```

instead

```
INNER JOIN `catalog_category_product_index_store7` AS `cat_index` ON cat_index.product_id=e.entity_id AND
cat_index.store_id=7 AND cat_index.visibility IN(2, 4) AND cat_index.category_id=2
```

So in this case the products will get retrieved from a wrong category.

You can create a workaround by injecting a new "collectionProcessors" for this class `Magento\CatalogGraphQl\Model\Resolver\Products\DataProvider\Product\CompositeCollectionProcessor`

And in your processor's process method set the collection store like "$collection->setStore($this->storeManager->getStore())"

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-08-26 08:02
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-08-26 10:41
Hi @alexmtch ,
Thank you for reporting and collaboration. Verified the behaviour on Magento 2.4-develop branch and is reproducible but however this seems to be an expected behaviour.
Since both the stores (default and store A) are assigned to the same website(Main website), Product C is still displayed on front end Store A scope even if it is unassigned from the store A.
Kindly refer the [docs[](https://experienceleague.adobe.com/docs/commerce-admin/start/setup/websites-stores-views.html?lang=en) for detailed explanation of the store hierarchy and provide your inputs on the same.
Thank you.
![image](https://user-images.githubusercontent.com/60198231/186886597-ca93abdd-1914-4d88-9efe-90d1c431a7b2.png)
![image](https://user-images.githubusercontent.com/60198231/186886817-fa01cb67-cfc7-4811-a386-32c7a2e7de35.png)

**Comment by engcom-November** [comment] 2022-09-05 12:29
Hi @alexmtch ,
Thank you for the response. I verified the behavior on both GraphQl and front end UI and the response is the same in both the cases. But seems like this is an expected behavior to me since both the stores (default and store A) are assigned to the same website(Main website), Product C is still displayed on front end Store A scope even if it is unassigned from the store A. Can you please refer the [docs](https://experienceleague.adobe.com/docs/commerce-admin/start/setup/websites-stores-views.html?lang=en) for detailed explanation of the store hierarchy and provide your inputs on the same. 
Thank you.

**Comment by engcom-November** [comment] 2022-09-20 03:19
Hi @alexmtch ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-09-20 03:19 UTC
Labels: Issue: needs update, Reported on 2.4.3
