### ISSUE TITLE
Problem price in bundle production page

### ISSUE THREAD

**Issue by Danieleeffe1** [magento/magento2#35231] opened 2022-03-25 09:26 UTC
Magento 2.4.3-p1

I have created a bundle product

I have entered 4 product options (checkbox)
Each option has a specific product selected as the default

On the frontpage:
The product is displayed with the total price, but when the customer clicks on the button "customize and add to cart"
and the product options are opened, the cloned price is 0

see live problem

[link demo]( https://m2.vetrinissime.it/kit-tropical-medium.html)

**Comment by engcom-Dash** [comment] 2024-01-29 10:34
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2024-01-29 11:03
Hi @Danieleeffe1 

Thanks for reporting and collaboration.

Verified the issue in magento 2.4 dev instance but the issue is not reproducible.

We are seeing the cloned price for the bundle product when we click on the "customize and add to cart" button.

Please refer the attached screenshot.

<img width="1440" alt="35231" src="https://github.com/magento/magento2/assets/60198592/f700017b-25f1-430b-9c75-254eceaaf1f1">

Please try to reproduce the issue in latest magento instance and let us know if you still facing the issue.

**Comment by engcom-Dash** [comment] 2024-02-15 05:32
Hi @Danieleeffe1 

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Dash** 2024-02-15 05:32 UTC
Labels: Issue: needs update, Reported on 2.4.3-p1
