### ISSUE TITLE
Product Image Cache Path Wrong After Run Resize Command

### ISSUE THREAD

**Issue by manhtranisobar** [magento/magento2#37444] opened 2023-04-28 10:57 UTC
### Preconditions and environment

- Magento 2.4.6

### Steps to reproduce
- Create 2 websites, 2 stores, 2 store views
- Develop new frontend theme, extends from Luma theme with info:
```
<vars module="Magento_Catalog">
           <var name="product_image_white_borders">0</var>
</vars>
```
- Select Luma theme for default store view design configuration field
- Select new theme for the second store view design configuration field
![image](https://github.com/magento/magento2/assets/88669934/af93be2f-109d-4cc2-9bb1-d9287de772d3)

- Create new product and add new image, set It as base/thumbnail/small, assign to second website
- Check product from the second store view frontend, product image display correctly
- Delete folder pub/media/catalog/product/cache
- Run command: php bin/magento catalog:images:resize
- Check product from frontend without browser cache

### Expected result

Product image display correctly

### Actual result

Product image does not exist

### Additional information
I tried to debug and see this issue happened because Magento load view config from theme of default store view instead current store view when run resize command. If Luma theme and new theme have same view config then we can not see this issue.
Function: \Magento\Framework\View\Asset\Repository::updateDesignParams work incorrectly for resize command.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2023-05-09 10:13
Hello @manhtranisobar,

Thanks for the report and contribution!

We have tried to reproduce the issue in the 2.4-develop branch but it seems the issue is not reproducible for us!

We have followed the below steps in order to reproduce the issue:

- Develop a new frontend theme, that extends from the Luma theme with image info:
```
<image id="product_swatch_image_large" type="image"/> 
<image id="product_swatch_image_medium" type="image"> 
	<width>240</width> 
	<height>300</height> 
</image> 
<image id="product_swatch_image_small" type="thumbnail"> 
	<width>88</width> 
	<height>110</height> 
</image>
```
- Select the theme from `Content -> Configuration ->  Design Configuration`
<img width="1325" alt="image" src="https://github.com/magento/magento2/assets/51681618/cf7855de-f45b-4169-8275-888690b1cdbb">
- Create a new product and add a new image, set It as base/thumbnail/small
<img width="1285" alt="image" src="https://github.com/magento/magento2/assets/51681618/404bd1b6-6a0e-43de-9341-da3f9b728099">
- Check product from front, product image displayed correctly
- Delete folder pub/media/catalog/product/cache
- Run command: php bin/magento catalog:images:resize
- Check product from frontend without browser cache (via incognito window)

but for us we see the image in product detail page.

Let us know if we have missed anything.

Thanks

**Comment by manhtranisobar** [comment] 2023-05-10 02:34
Hi @engcom-Hotel 

I have tried to reproduce with Magento 2.4.6 and this issue did not happen. It may be fixed at latest version.
Thank you!

**Comment by manhtranisobar** [comment] 2023-05-12 06:47
Hi @engcom-Hotel 

I have reproduced this issue with Magento 2.4.6 and updated reproduce steps, thank to check.

**Comment by engcom-Hotel** [comment] 2023-05-29 11:27
Hello @manhtranisobar,

We have again tried to reproduce the issue with the updated steps in fresh Magento 2.4-develop but still we are unable to reproduce the issue:

- Please have a look at the output of `bin/magento catalog:images:resize` command:

<img width="782" alt="image" src="https://github.com/magento/magento2/assets/51681618/eed16084-9493-4865-92b3-11afc3290028">

- Below is the screenshot of the product detail page in an incognito window to avoid browser cache:
<img width="1366" alt="image" src="https://github.com/magento/magento2/assets/51681618/011edf1e-c67f-47c8-b78c-b04db3387d27">

Thanks

**Comment by manhtranisobar** [comment] 2023-05-30 02:21
Hi @engcom-Hotel 
I created a support ticket for our project to Adobe team and they already confirmed this issue and are fixing It. Could you help to check reproduce steps and try again? Might you delete media catalog product cache folder?

**Comment by manhtranisobar** [comment] 2023-05-30 10:07
Hi @engcom-Hotel 
From my side, if product image is uploaded from admin then check from frontend, It show correctly for both websites. This issue happen when I clear media product cache folder and run resize command.

**Comment by Nuranto** [comment] 2023-06-08 06:44
I have this issue too, on 2.4.6, not on all images though...

**Comment by engcom-Hotel** [comment] 2023-07-17 14:20
Hello @manhtranisobar,

We checked this issue in multiple OS like macOS and Ubuntu etc. but still, the issue is not reproducible with mentioned steps in the main description but reproducible via the steps mentioned here https://github.com/magento/magento2/issues/37444#issuecomment-1568133075.


@Nuranto can you please guide us with the steps for you, in which the issue is reproducible.

Thanks

**Comment by engcom-Hotel** [comment] 2023-08-04 05:11
Dear @manhtranisobar,

We have noticed that this issue has not been updated for a long time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2023-08-04 05:11 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.5-p1

**Comment by manhtranisobar** [comment] 2023-08-10 02:49
Hi @engcom-Hotel 
Sorry for late response,
This issue was confirmed by Adobe team and they already provide a patch to resolve It. You might miss some reproduce steps. Any way, this issue will be resolved after apply patch fix. Thanks for your discussion.
This is patch content to resolve the issue:

```
diff --git a/vendor/magento/module-catalog/Model/Product/Image/ParamsBuilder.php b/vendor/magento/module-catalog/Model/Product/Image/ParamsBuilder.php
index ecdb3b2829b9..ad2559534c36 100644
--- a/vendor/magento/module-catalog/Model/Product/Image/ParamsBuilder.php
+++ b/vendor/magento/module-catalog/Model/Product/Image/ParamsBuilder.php
@@ -7,8 +7,13 @@
 
 namespace Magento\Catalog\Model\Product\Image;
 
+use Magento\Framework\App\Area;
 use Magento\Framework\App\Config\ScopeConfigInterface;
+use Magento\Framework\App\ObjectManager;
 use Magento\Framework\View\ConfigInterface;
+use Magento\Framework\View\Design\Theme\FlyweightFactory;
+use Magento\Framework\View\Design\ThemeInterface;
+use Magento\Framework\View\DesignInterface;
 use Magento\Store\Model\ScopeInterface;
 use Magento\Catalog\Model\Product\Image;
 
@@ -52,16 +57,42 @@ class ParamsBuilder
      */
     private $viewConfig;
 
+    /**
+     * @var DesignInterface
+     */
+    private $design;
+
+    /**
+     * @var FlyweightFactory
+     */
+    private $themeFactory;
+
+    /**
+     * @var ThemeInterface
+     */
+    private $currentTheme;
+
+    /**
+     * @var array
+     */
+    private $themesList = [];
+
     /**
      * @param ScopeConfigInterface $scopeConfig
      * @param ConfigInterface $viewConfig
+     * @param DesignInterface|null $designInterface
+     * @param FlyweightFactory|null $themeFactory
      */
     public function __construct(
         ScopeConfigInterface $scopeConfig,
-        ConfigInterface $viewConfig
+        ConfigInterface $viewConfig,
+        DesignInterface $designInterface = null,
+        FlyweightFactory $themeFactory = null
     ) {
         $this->scopeConfig = $scopeConfig;
         $this->viewConfig = $viewConfig;
+        $this->design = $designInterface ?? ObjectManager::getInstance()->get(DesignInterface::class);
+        $this->themeFactory = $themeFactory ?? ObjectManager::getInstance()->get(FlyweightFactory::class);
     }
 
     /**
@@ -75,6 +106,8 @@ public function __construct(
      */
     public function build(array $imageArguments, int $scopeId = null): array
     {
+        $this->determineCurrentTheme($scopeId);
+
         $miscParams = [
             'image_type' => $imageArguments['type'] ?? null,
             'image_height' => $imageArguments['height'] ?? null,
@@ -87,6 +120,25 @@ public function build(array $imageArguments, int $scopeId = null): array
         return array_merge($miscParams, $overwritten, $watermark);
     }
 
+    /**
+     * Determine the theme assigned to passed scope id
+     *
+     * @param int|null $scopeId
+     * @return void
+     */
+    private function determineCurrentTheme(int $scopeId = null): void
+    {
+        if (is_numeric($scopeId) || !$this->currentTheme) {
+            $themeId = $this->design->getConfigurationDesignTheme(Area::AREA_FRONTEND, ['store' => $scopeId]);
+            if (isset($this->themesList[$themeId])) {
+                $this->currentTheme = $this->themesList[$themeId];
+            } else {
+                $this->currentTheme = $this->themeFactory->create($themeId);
+                $this->themesList[$themeId] = $this->currentTheme;
+            }
+        }
+    }
+
     /**
      * Overwrite default values
      *
@@ -170,7 +222,11 @@ private function getWatermark(string $type, int $scopeId = null): array
      */
     private function hasDefaultFrame(): bool
     {
-        return (bool) $this->viewConfig->getViewConfig(['area' => \Magento\Framework\App\Area::AREA_FRONTEND])
-            ->getVarValue('Magento_Catalog', 'product_image_white_borders');
+        return (bool) $this->viewConfig->getViewConfig(
+            [
+                'area' => \Magento\Framework\App\Area::AREA_FRONTEND,
+                'themeModel' => $this->currentTheme
+            ]
+        )->getVarValue('Magento_Catalog', 'product_image_white_borders');
     }
 }

```

**Comment by sebql** [comment] 2025-06-06 10:08
Still got that issue in 2.4.7-p5. Works fine after I remove   <var name="product_image_white_borders">0</var>.
