### ISSUE TITLE
Magento 2.4.5 - Unable to Create New Order in Backend

### ISSUE THREAD

**Issue by gilbertsohal** [magento/magento2#36428] opened 2022-11-06 22:41 UTC
### Preconditions and environment

- 2.4.5
- Add Selected Product(s) to Order not adding product to Items Ordered list
- Payment Method not showing
- Shipping Method not showing

### Steps to reproduce

1. Login to Backend
2. Create new Order Sales > Orders > Create New Order
3. Select Existing Customer
4. Click Add Products button > Select simple product
5. Click Add Selected Product(s) to Order
6. No ordered items showing
7. Payment Method not showing
8. Shipping Method not showing

### Expected result

Click Add Selected Product(s) to Order should showing items in Items Ordered. 
Payment Method should be visible to select
Shipping Method should be visible to select

### Actual result

1. No ordered items showing Items Ordered.
2. Payment Method not showing
3. Shipping Method not showing

Screenshot 1
https://prnt.sc/QZn6IcRzO3UH

Screenshot 2
https://prnt.sc/wH7yZ5qqMinS

Screenshot 3
https://prnt.sc/u4oJUmaErmoY

Screenshot 4
https://prnt.sc/ApYDla8vwvm9

If i Click Submit Order

Screenshot 5
https://prnt.sc/Ob-hedesudhR

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-11-07 07:52
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-07 11:57
Hi @gilbertsohal,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop and 2.4.5 instances and the issue is not reproducible on both the instances.We are able to Create New Order from Backend.Kindly refer the screenshots.

Steps to reproduce:

1.Login to Backend
2.Create new Order Sales > Orders > Create New Order
3.Select Existing Customer
4.Click Add Products button > Select simple product
5.Click Add Selected Product(s) to Order



<img width="1303" alt="Screenshot 2022-11-07 at 1 36 36 PM" src="https://user-images.githubusercontent.com/51680745/200304352-54487edb-346b-47bc-8334-8eed6f43b64c.png">




<img width="1395" alt="Screenshot 2022-11-07 at 1 37 02 PM" src="https://user-images.githubusercontent.com/51680745/200304396-75216247-d084-49f2-a608-5773c154c66d.png">




<img width="1457" alt="Screenshot 2022-11-07 at 1 37 14 PM" src="https://user-images.githubusercontent.com/51680745/200304419-d7788eea-baa8-4e78-8e0b-5e4d33835e66.png">




Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2022-11-21 06:11
Hi @gilbertsohal,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-11-21 06:11 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.5

**Comment by pradeepkanaka** [comment] 2022-12-19 11:48
May be coming from here: https://github.com/genecommerce/module-braintree-magento2/commit/f3a45e97132acef8b005132d6f93743723683b42

**Comment by DomPixie** [comment] 2023-01-12 14:57
Had exact same issue with Add Products button disappear

Also on refresh was logged out of admin

Session settings fixed this for me

# session size
php bin/magento config:set system/security/max_session_size_storefront 999999
php bin/magento config:set system/security/max_session_size_admin 999999

**Comment by hellosg** [comment] 2023-09-11 14:15
Can confirm @DomPixie 's solution worked. Running Magento ver. 2.4.5-p3 with Braintree (not sure if Braintree mattered). Had this issue after upgrading Magento versions.
