### ISSUE TITLE
imagecreatetruecolor(): Argument #2 ($height) must be greater than 0. Can't upload specific image

### ISSUE THREAD

**Issue by yuriichayka** [magento/magento2#37988] opened 2023-09-13 15:14 UTC
### Preconditions and environment

- Enterprise 2.4.6-p1
- php8.1

### Steps to reproduce

1. Enable new media gallery, see the instruction by [Link](https://experienceleague.adobe.com/docs/commerce-admin/content-design/media/gallery/media-gallery.html?lang=
2. When creating a new CMS block, try to upload the attached image through Page Builder/Media/Image element
![test_image](https://github.com/magento/magento2/assets/34608132/ae403625-deae-4971-850f-a7c6b617d698)

### Expected result

The image is uploaded and works fine

### Actual result

The following error occurs in exception.log, and image isn't uploaded:
```
report.CRITICAL: ValueError: imagecreatetruecolor(): Argument #2 ($height) must be greater than 0 in vendor/magento/framework/Image/Adapter/Gd2.php:422
Stack trace:
vendor/magento/framework/Image/Adapter/Gd2.php(422): imagecreatetruecolor()
vendor/magento/module-cms/Model/Wysiwyg/Images/Storage.php(717): Magento\Framework\Image\Adapter\Gd2->resize()
vendor/magento/module-media-gallery-ui/Plugin/CreateThumbnails.php(51): Magento\Cms\Model\Wysiwyg\Images\Storage->resizeFile()
vendor/magento/framework/Interception/Interceptor.php(121): Magento\MediaGalleryUi\Plugin\CreateThumbnails->beforeExecute()
vendor/magento/framework/Interception/Interceptor.php(153): Magento\MediaGallerySynchronizationApi\Model\ImportFilesComposite\Interceptor->Magento\Framework\Interception\{closure}()
```

### Additional information

This also prevents the following command to be executed - php bin/magento media-gallery:sync
Hotfix for us was the following patch:
```
diff --git vendor/magento/module-cms/Model/Wysiwyg/Images/Storage.php vendor/magento/module-cms/Model/Wysiwyg/Images/Storage.php
--- vendor/magento/module-cms/Model/Wysiwyg/Images/Storage.php
+++ vendor/magento/module-cms/Model/Wysiwyg/Images/Storage.php	(date 1662984202000)
@@ -713,7 +713,15 @@

         [$imageWidth, $imageHeight] = $this->getResizedParams($source);

-        $image->resize($imageWidth, $imageHeight);
+        try {
+            $image->resize($imageWidth, $imageHeight);
+        } catch (\Throwable $e) {
+            $this->logger->critical(
+                'FAILED WYSIWYG IMAGE RESIZING: ' . ' error: ' . $e->getMessage() . '. path: ' . $realPath
+            );
+
+            return false;
+        }
         $dest = $targetDir . '/' . $this->ioFile->getPathInfo($source)['basename'];
         $image->save($dest);
         if ($this->_directory->isFile($this->_directory->getRelativePath($dest))) {
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-09-14 08:29
Hi @yuriichayka,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the attached video.

**Steps to reproduce**

- Enable new media gallery, see the instruction by [Link](https://experienceleague.adobe.com/docs/commerce-admin/content-design/media/gallery/media-gallery.html?lang=

- When creating a new CMS block, try to upload the attached image through Page Builder/Media/Image element


![267701397-ae403625-deae-4971-850f-a7c6b617d698](https://github.com/magento/magento2/assets/51680745/759d3354-fa2d-4464-ab19-1ea0b5365d89)




https://github.com/magento/magento2/assets/51680745/7dd49f6d-7b47-4b49-b219-869dd2abd6c9



As per document it will supports JPG,GIF,PNG images here we are uploading PNG image it is not at all uploading.


Hence Confirming the issue.

Thanks.

**Comment by hostep** [comment] 2024-08-06 20:09
Is probably fixed by [ACP2E-3127: imagecreatetruecolor(): Argument #2 () must be greater than 0. Can't upload specific image](https://github.com/magento/magento2/commit/2456e7d34d3021c800567fb0890023231d5dabdd)

**Comment by engcom-Bravo** [comment] 2024-08-07 07:34
@hostep Thanks for your Contribution!!

Hi @yuriichayka,

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.

Here is the commit links : https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-3127&type=commits

Thanks.

**Closed as completed by engcom-Bravo** 2024-08-07 07:34 UTC
Labels: Issue: Confirmed, Component: MediaGallery, Reproduced on 2.4.x, Priority: P3, Progress: done, Area: Content, Reported on 2.4.6-p1
