### ISSUE TITLE
New Quote is not creating after order place for logged in customer

### ISSUE THREAD

**Issue by hiteshagrawal84** [magento/magento2#24009] opened 2019-08-04 10:38 UTC
### Preconditions (*)

1. Magento 2.3.2

### Steps to reproduce (*)

1. Logged with registered customer
2. Place a new order
3. Check exception.log file

### Expected result (*)

1. New quote should be created for customer

### Actual result (*)

1. report.CRITICAL: No such entity with customerId = 31 {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0)

**Comment by ihor-sviziev** [comment] 2019-08-05 10:24
Duplicate of #23411

**Closed as completed by ihor-sviziev** 2019-08-05 10:24 UTC
Labels: Issue: Format is valid
