### ISSUE TITLE
Trademark ^TM not show proper at Recently Ordered and My Wish List

### ISSUE THREAD

**Issue by renard123** [magento/magento2#33162] opened 2021-06-07 10:23 UTC
Trademark ^TM not show proper at Recently Ordered and My Wish List

### Preconditions (*)

1. Magento 2.4.2

### Steps to reproduce (*)

1. Login into account
2. Add Minerva LumaTech™ V-Tee product to add to wishlist OR place order with this product
3. Check the product name at left side Recently Ordered  and My Wish List section 

### Expected result (*)
It should show properly as Minerva LumaTech™ V-Tee 

### Actual result (*)
![image](https://user-images.githubusercontent.com/50658701/121000890-5934d580-c7a8-11eb-8c90-eada34948cd0.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment] 2021-06-07 10:25
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42573` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by fidellakis** [comment] 2021-06-15 03:19
@magento I am working on this

**Comment by fidellakis** [comment] 2021-06-15 03:20
@magento add to contributors team

**Comment by fidellakis** [comment] 2021-06-15 03:21
@magento I am working on this

**Comment by fidellakis** [comment] 2021-10-04 01:58
@magento give me 2.4.0 instance

**Comment by fidellakis** [comment] 2021-10-04 02:00
@magento give me 2.4.0 instance

**Comment by fidellakis** [comment] 2022-01-18 14:30
@magento give me 2.4.3 instance

**Comment by engcom-Bravo** [comment] 2024-06-13 04:39
Hi @renard123,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="401" alt="Screenshot 2024-06-13 at 10 07 19" src="https://github.com/magento/magento2/assets/51680745/25d603b6-f8aa-43fb-a02e-a2077874bb7d">


It is showing properly as Minerva LumaTech™ V-Tee

Hence We are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-13 04:39 UTC
Labels: Component: Customer, Issue: Confirmed, Reproduced on 2.4.x, Severity: S4, Priority: P4, Progress: done, Issue: ready for confirmation
