### ISSUE TITLE
Return Type of guest cart's `getQuoteId` should be `int` instead of `string`

### ISSUE THREAD

**Issue by bikalbasnet** [magento/magento2#33069] opened 2021-05-25 07:52 UTC
### Preconditions (*)

1. Magento CE 2.x without sample data is installed.

### Steps to reproduce (*)

1. Call ` POST V1/guest-carts` API
2. Call `GET /rest/default/V1/guest-carts/{cartId}/totals` with the above cart Id

### Expected result (*)

1. Return type of `$quoteIdMask->getQuoteId()` should be `int` in [GuestCartTotalRepository.php](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Quote/Model/GuestCart/GuestCartTotalRepository.php#L50)

### Actual result (*)

1. Return type of `$quoteIdMask->getQuoteId()` is `string`

### Explaination
This causes unwanted bug when implementing interceptor of [CartTotalRepositoryInterface::get](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Quote/Api/CartTotalRepositoryInterface.php#L22) because quote id of guest cart is passed as cart id in [GuestCartTotalRepository::get](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Quote/Model/GuestCart/GuestCartTotalRepository.php#L50)

Here is the stacktrace from xdebug
![image](https://user-images.githubusercontent.com/7262965/119460066-7d37f600-bd68-11eb-9ecc-c920e3c6d6f9.png)

Also `getQuoteId` should be `int` because it's corresponding DB column `quote_id` as well.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment] 2021-05-26 13:14
Hi
@bikalbasnet  , Tried reproducing this issue but getting different error 404 . Kindly help to provide more details.
{
    "message": "No such entity with %fieldName = %fieldValue",
    "parameters": {
        "fieldName": "cartId",
        "fieldValue": null
    },

**Comment by engcom-Lima** [comment] 2021-06-14 12:54
@bikalbasnet As we did not get any response since 19 days, Hence closing this ticket. 

Please feel free to raise the new ticket if any issue is there

**Closed as completed by engcom-Lima** 2021-06-14 12:54 UTC
Labels: Issue: ready for confirmation
