### ISSUE TITLE
Simple product custom attribute returns "No" instead of real value

### ISSUE THREAD

**Issue by eharvest** [magento/magento2#7053] opened 2016-10-17 11:33 UTC
### Preconditions

1. Magento 2.1.0
2. Call custom attribute value in template file (.phtml).
### Steps to reproduce

1. When calling custom attribute value in template file, it returns "No" instead of real value. This is happening only to simple products.
2. use: $_product->getResource()->getAttribute('attribute-code')->getFrontend()->getValue($_product);
### Expected result

1. It should return the real attribute value instead of "No"
### Actual result

1. It returns "No", no matter if it's a drop down or yes/no attribute type, which is an obvious bug.

**Comment by pguedesbr** [comment] 2016-10-18 12:08
If your attribute uses custom source, then this issue might be related to mine https://github.com/magento/magento2/issues/6719#issuecomment-252467721, where i've already pinned down the problem and I'm waiting for an acknowledgement from de devs

**Comment by oshmyheliuk** [comment] 2016-11-16 15:08
Hi @eharvest  ,
I’m closing this issue because it is a duplicate of [#6719](https://github.com/magento/magento2/issues/6719) and we've created internal ticket for that issue. 
Please reopen this issue as needed.

**Closed as completed by oshmyheliuk** 2016-11-16 15:08 UTC
Labels: bug report, Component: Catalog
