### ISSUE TITLE
https://github.com/magento/magento2/issues/12939

### ISSUE THREAD

**Issue by jonathan-martz** [magento/magento2#13991] opened 2018-03-07 10:34 UTC
Would be nice if some opens this issue again
https://github.com/magento/magento2/issues/12939

**Comment by magento-engcom-team** [comment] 2018-03-07 12:37
Hi @jonathan-martz 
I reopen your old issue

**Comment by magento-engcom-team** [comment] 2018-03-07 12:38
Duplicate of #12939

**Closed as completed by magento-engcom-team** 2018-03-07 12:38 UTC
Labels: Issue: Format is not valid
