### ISSUE TITLE
'General system exception happened' on import

### ISSUE THREAD

**Issue by Dkmafia** [magento/magento2#11373] opened 2017-10-11 13:33 UTC
I save the CSV in UTF-8 format. Still get the error. 

### Preconditions

1. 
2. 
Import a CSV
### Steps to reproduce

1. 
2. 
3. 
Import successful 
### Expected result

1. 
Error: General system exception happened
### Actual result

1. [Screenshot, logs]

**Comment by magento-engcom-team** [comment] 2017-10-13 10:53
Hello @Dkmafia . Please add more details to your description of the steps you followed when identifying this issue. Screenshots or logs would be helpful, too.

**Comment by Dkmafia** [comment] 2017-10-13 13:29
Thats really the problem... No error messages. I even cut the amount of products down to test them in small batches. I have no idea what to do.



________________________________

**Comment by magento-engcom-team** [comment] 2017-10-19 08:06
@Dkmafia Thanks for reporting this issue. Closing as duplicate of [#6924](https://github.com/magento/magento2/issues/6924). #11363 for tracking progress

**Closed as completed by magento-engcom-team** 2017-10-19 08:06 UTC
Labels: Progress: needs update, Issue: Format is valid

**Comment by alrururu** [comment] 2019-11-18 20:20
I am getting same issue on import. There is no import items with errors actually showing in the report
General system exception happened
Additional data:
Invalid URL key

**Comment by alrururu** [comment] 2019-11-18 20:22
https://i.imgur.com/fpnAjv4.png
