### ISSUE TITLE
\Magento\Framework\Exception\LocalizedException does not translate text

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#34050] opened 2021-09-10 13:02 UTC
### Preconditions (*)

1. Magento 2.4.2

### Steps to reproduce (*)

1. Add article to your cart
2. Create Theme
3. Add file i18n/de_DE.csv to your Theme
3.1. Add this translation and clear cache afterwards :

    "The product has required options. Enter the options and try again.", "Tut uns Leid, irgendetwas ist schief gelaufen. Bitte konfigurieren Sie das Produkt neu und versuchen es erneut."

4. Change store view to german (See step 3: https://docs.magento.com/user-guide/stores/store-language-add.html)

5. Open the file **vendor\magento\module-quote\Model\Quote\Item\AbstractItem.php** and go to the method checkData()

5.1. Add Exception at the top of the method checkData():

    /**
     * Checking item data
     *
     * @return $this
     */
    public function checkData()
    {
			throw new \Magento\Framework\Exception\LocalizedException(
				__('The product has required options. Enter the options and try again.')
			);

6. Load cart, you should see the exception.

### Expected result (*)

Exception should show and it should be translated to german.

### Actual result (*)

Exception is showing untranslated.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mitraj-adorncommerce** [comment] 2021-09-11 06:35
@magento I am working on this

**Comment by mitraj-adorncommerce** [comment] 2021-09-11 06:35
@magento add to contributors team

**Comment by mitraj-adorncommerce** [comment] 2021-09-11 06:36
@magento I am working on this

**Comment by mitraj-adorncommerce** [comment] 2021-09-11 07:22
Could not reproduce

**Comment by engcom-Lima** [comment] 2021-09-17 07:50
Hi @Eddcapone,
 
Thank you for reporting the issue.
In order to reproduce this, we need some more info so please update below queries so that we can continue with our analysis:
1. Can you please update if this issue is reproducible on 2.4-develop instance also ?
2. Is this issue happening with new created theme or happening with Magento Default themes also ?

Thanks

**Comment by Eddcapone** [comment] 2021-09-17 09:36
Hi, sorry  I don't have time to test this. I was reproducing this in my custom installation.

**Comment by engcom-Lima** [comment] 2021-09-21 13:24
Hi @Eddcapone,

Based on the provided issue description, we are not able to reproduce this so unless you help us with more info requested in my last comment, we won't be able to confirm this.

**Comment by engcom-Lima** [comment] 2021-10-05 10:20
Hi @Eddcapone,

We have noticed that this issue has not been updated for some time. Since we were not able to reproduce it and there is no update on the requested info, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Lima** 2021-10-05 10:20 UTC
Labels: Component: Translation, Issue:  Cannot Reproduce, Issue: needs update
