### ISSUE TITLE
Bundle product Rest API issue

### ISSUE THREAD

**Issue by brianrootways** [magento/magento2#34219] opened 2021-10-01 09:52 UTC
### Preconditions (*)

1. Magento 2.3.3
2. PHP version 7.2.34

### Steps to reproduce (*)

1. Can you give me some solution regarding bundle product API? See an attached screenshot when we fire bundle product API it will change (increment) option ID all the time instead of keeping the same. Can we keep the same bundle product option ID here (If we change in API)?
2.

### Expected result (*)

1. when we fire bundle product API we need to keep the same option ID instead of increment all the time.

### Actual result (*)

1. Video URL: https://share.vidyard.com/watch/jcrR3vD5RKG9TA7Ja5yHag?
![image](https://user-images.githubusercontent.com/68637204/135600604-01ee27ce-57d7-49c0-881f-bb05081bd627.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2021-10-08 12:24
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible with below Payload:
Steps performed:
Generate Admin Access Token using POST: /rest/default/V1/integration/admin/token
Sent PUT request to update Bundle Product using below sample Payload : /rest/all/V1/products/{sku}
No issue: Option Id's are not incremented. They remain same always on updating price or sending same request multiple times.
Update Product using PUT is working as expected.
`
{
  "product": {
    "id": 2058,
    "sku": "bundle1",
    "name": "bundle1",
    "attribute_set_id": 4,
    "price": 50.45,
    "status": 1,
    "visibility": 4,
    "type_id": "bundle",
    "created_at": "2021-09-29 08:02:11",
    "updated_at": "2021-09-29 08:02:11",
    "weight": 0,
    "extension_attributes": {
      "website_ids": [
        1
      ],
      "category_links": [
       {
        "position": 0,
        "category_id": "2"
      },
      {
        "position": 0,
        "category_id": "3"
      },
      {
        "position": 0,
        "category_id": "4"
      }
      ],
      "stock_item": {
        "item_id": 2064,
      "product_id": 2058,
      "stock_id": 1,
      "qty": 0,
      "is_in_stock": true,
      "is_qty_decimal": false,
      "show_default_notification_message": false,
      "use_config_min_qty": true,
      "min_qty": 0,
      "use_config_min_sale_qty": 1,
      "min_sale_qty": 1,
      "use_config_max_sale_qty": true,
      "max_sale_qty": 10000,
      "use_config_backorders": true,
      "backorders": 0,
      "use_config_notify_stock_qty": true,
      "notify_stock_qty": 1,
      "use_config_qty_increments": true,
      "qty_increments": 0,
      "use_config_enable_qty_inc": true,
      "enable_qty_increments": false,
      "use_config_manage_stock": true,
      "manage_stock": true,
      "low_stock_date": null,
      "is_decimal_divided": false,
      "stock_status_changed_auto": 0
      },
      "bundle_product_options": [
        {
        "option_id": 5,
        "title": "op1",
        "required": true,
        "type": "select",
        "position": 1,
        "sku": "bundle1",
        "product_links": [
          {
            "id": "9",
            "sku": "simple1",
            "option_id": 5,
            "qty": 1,
            "position": 1,
            "is_default": false,
            "price": 50,
            "price_type": null,
            "can_change_quantity": 0
          }
        ]
      },
      {
        "option_id": 6,
        "title": "op2",
        "required": true,
        "type": "select",
        "position": 2,
        "sku": "bundle1",
        "product_links": [
          {
            "id": "10",
            "sku": "simple1",
            "option_id": 6,
            "qty": 1,
            "position": 1,
            "is_default": false,
            "price": 50,
            "price_type": null,
            "can_change_quantity": 0
          }
        ]
      }
      ],
      "downloadable_product_links": [
        
      ],
      "downloadable_product_samples": [
        
      ],
      "configurable_product_options": [
       
      ],
      "configurable_product_links": [
      ]
    },
    "product_links": [
    ],
    "options": [
    ],
    "media_gallery_entries": [
      {
      "id": 3434,
      "media_type": "image",
      "label": null,
      "position": 1,
      "disabled": false,
      "types": [
        "image",
        "small_image",
        "thumbnail"
      ],
      "file": "/s/c/screenshot_from_2021-09-29_12-33-13.png"
    }
    ],
    "tier_prices": [
    ],
    "custom_attributes": [
       {
      "attribute_code": "image",
      "value": "/s/c/screenshot_from_2021-09-29_12-33-13.png"
    },
    {
      "attribute_code": "shipment_type",
      "value": "0"
    },
    {
      "attribute_code": "small_image",
      "value": "/s/c/screenshot_from_2021-09-29_12-33-13.png"
    },
    {
      "attribute_code": "thumbnail",
      "value": "/s/c/screenshot_from_2021-09-29_12-33-13.png"
    },
    {
      "attribute_code": "options_container",
      "value": "container2"
    },
    {
      "attribute_code": "price_view",
      "value": "0"
    },
    {
      "attribute_code": "url_key",
      "value": "bundle1"
    },
    {
      "attribute_code": "gift_message_available",
      "value": "2"
    },
    {
      "attribute_code": "msrp_display_actual_price_type",
      "value": "0"
    },
    {
      "attribute_code": "required_options",
      "value": "1"
    },
    {
      "attribute_code": "has_options",
      "value": "1"
    },
    {
      "attribute_code": "meta_title",
      "value": "bundle1"
    },
    {
      "attribute_code": "sku_type",
      "value": "0"
    },
    {
      "attribute_code": "meta_keyword",
      "value": "bundle1"
    },
    {
      "attribute_code": "price_type",
      "value": "0"
    },
    {
      "attribute_code": "meta_description",
      "value": "bundle1 "
    },
    {
      "attribute_code": "tax_class_id",
      "value": "2"
    },
    {
      "attribute_code": "weight_type",
      "value": "0"
    },
    {
      "attribute_code": "category_ids",
      "value": [
        "2",
        "3",
        "4"
      ]
    }
    ]
  },
  "saveOptions": true
}
`

@brianrootways kindly recheck the issue on Magento 2.4-develop branch as it has the latest code base and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by brianrootways** [comment] 2021-10-09 09:44
Hello @engcom-November 
Please check my attached screenshot of generating token. Length of token is very small compare to the development instance they provided. I have tried to use that token but it's not working for me.
![token](https://user-images.githubusercontent.com/68637204/136653139-910e8d4a-1967-4523-b0db-b4f740d72bda.jpg)

**Comment by brianrootways** [comment] 2021-10-12 07:46
Hello @engcom-November

Any update regarding to above comment?

**Comment by engcom-November** [comment] 2021-10-12 12:19
Hi @brianrootways ,
I verified the issue again on above Magento 2.4-develop instance but the issue is not reproducible:

Admin access token is generated and is working fine for all API requests:
![image](https://user-images.githubusercontent.com/60198231/136954422-49db1197-c7d0-4468-bd1e-52a9504570a5.png)

Sent PUT request to update Bundle Product using above access token: https://18b4396ca5186467513ab6e2b75e0800-2-4-develop.instances.magento-community.engineering/rest/all/V1/products/bundle1  - Option ID's are not incremented even after sending the request multiple times - **No issue:**
![image](https://user-images.githubusercontent.com/60198231/136954704-9b6c8f88-eaa5-4aed-8216-77e789436cc0.png)

**Comment by engcom-November** [comment] 2021-11-26 11:41
Hi @brianrootways , this behavior(length of admin access token being small) was observed in earlier versions of Magento. However in latest Magento all instances - Composer/ Git installation, this behavior is not observed. Since this issue does not persist in Magento 2.4-develop branch we are closing it. Kindly re-open if you are still facing issues with elaborated steps to reproduce.
Thank you.

**Closed as completed by engcom-November** 2021-11-26 11:41 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.3.3
