### ISSUE TITLE
Invoice, Credit Memos, Shipments having responsiveness issue after adding column filter 

### ISSUE THREAD

**Issue by abhay1198** [magento/magento2#37483] opened 2023-05-10 10:09 UTC
### Summary

Magento Version - 2.4.6
Steps
1. Open the Backend
2. Navigate to sales->order-> Order Grid
3. View an order
4. On the shipment, Credit Memo and Invoice page add the column filter
5. Page is not looking as per the need

<img width="877" alt="image" src="https://github.com/magento/magento2/assets/39663362/4a6263b5-98ec-4a9b-94c9-560629cdd428">

### Examples

Magento 2.4.6

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-05-10 20:53
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-05-10 21:12
Hi @abhay1198 ,


Thanks for Contribution and Collaboration!

Verified the issue in 2.4-develop instance and 2.4.6 Magento instance and the issue is not reproducible.

**Preconditions:**
Magento version 2.4-develop and 2.4.6
PHP 8.1

**Steps to reproduce:**
1.Install Magento instance
2.Go to Admin >Sales >Order
3.Go to Invoices and Shipment and Credit memo
4. Add the Column filter and Check the Page Responses.

**Kindly refer the below screenshots:**
Before Adding the column Filter:
<img width="1511" alt="Screenshot 2023-05-10 at 6 16 53 PM" src="https://github.com/magento/magento2/assets/60198592/d445b582-d6c1-44e4-ae6b-6cfc6a56483a">

After Adding the column Filter :
<img width="1511" alt="Invoice" src="https://github.com/magento/magento2/assets/60198592/d5e04299-2048-4f55-87d0-19b9d90b8f3d">
<img width="1511" alt="Shipmwnnt" src="https://github.com/magento/magento2/assets/60198592/5f213a48-0e56-48cb-8093-b876717a090a">
<img width="1511" alt="Credit memo" src="https://github.com/magento/magento2/assets/60198592/d650bd64-61f7-4501-ad8f-0069194cc132">

Pages are working as expected,So the issue is not reproducible,Kindly provide more information and screenshot's if the issue still reproducible.

Let us know if we are missing anything!

Thanks.

**Comment by mrtuvn** [comment] 2023-05-11 03:41
Duplicated when we have reported here https://github.com/magento/magento2/issues/37459

**Comment by abhay1198** [comment] 2023-05-11 03:45
Plz add more than 10 filter from column 

@mrtuvn Thanks for your comment

**Comment by engcom-Dash** [comment] 2023-05-11 11:11
Hi @abhay1198 ,

Seems the issue is [Duplicate](https://github.com/magento/magento2/issues/37483#issuecomment-1543286486) ,Hence we are closing this issue.

Regards

**Closed as completed by engcom-Dash** 2023-05-11 11:11 UTC
Labels: duplicate, Triage: Dev.Experience, Issue: needs update
