### ISSUE TITLE
Shippingaddress street in quote is not updatet after changing the street in the checkout

### ISSUE THREAD

**Issue by WilcoMonta** [magento/magento2#37859] opened 2023-08-08 08:57 UTC
### Preconditions and environment

- Magento version 2.4.6.
- Create mixin to make the shippingaddress street of the quote required (Magento_Ui/js/lib/validation/validator)
- Create mixin to observe any change of the shippingaddress of the quote (select-shipping-method)   

### Steps to reproduce

1. Go to shop
2. Select a product to buy
3. Go to checkout
4. Change shipping address street  

### Expected result

In the quote shippingaddress street is updatet. 

### Actual result

In the quote shippingaddress street is not updatet. however, if you update the street first and then the zip code, the street will be updated.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2023-08-30 06:32
Hello @WilcoMonta,

Thank you for the report and collaboration!

We are not able to reproduce the issue in magento 2.4-develop.
We didn't create a mixin, instead used debugger to observe the changes in quote, and we got the expected result.
Please let us know if mixin is required to reproduce the issue.

Thank you.

**Comment by engcom-November** [comment] 2023-09-13 13:55
Hello @WilcoMonta,

We noticed this issue has not been updated for a long time, We assume that this issue is fixed now hence closing the issue.
Feel free to reopen or raise a new issue if you need more assistence.

Thank you.

**Closed as completed by engcom-November** 2023-09-13 13:55 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.6
