### ISSUE TITLE
Configurable Products with decimal quantity issue

### ISSUE THREAD

**Issue by marumehrts** [magento/magento2#38580] opened 2024-04-04 12:25 UTC
### Preconditions and environment

- Magento ver. 2.4.5-p5

### Steps to reproduce

1. Go to Catalog > Products and create a configurable product
2. Under Advanced Inventory, set Qty Uses Decimals = Yes for their child's product 
3. Place an order for that product for any quantity decimal like 0.25
4. Go to generate an invoice
5. Qty To Invoice input is 0, change it manually to 0.25
6. Click Update Qty
7. Does not update, still at 0 and totals is 0
![Captura de pantalla de 2024-04-04 09-20-15](https://github.com/magento/magento2/assets/3417459/8893dabf-37aa-4553-b798-839f2206151e)
![Captura de pantalla de 2024-04-04 09-20-27](https://github.com/magento/magento2/assets/3417459/7ae98d62-12c7-4328-b5a2-edc349ac0ed4)

### Expected result

Invoiced generated correctly with 0.25 as qty and values according to qty

### Actual result

Invoice created with all values at 0 and no item invoiced
![Captura de pantalla de 2024-04-04 09-23-30](https://github.com/magento/magento2/assets/3417459/0737ec8b-2884-4e48-be96-e52ae73ba912)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-04-05 06:35
Hi @marumehrts,

**Steps to reproduce**

- Go to Catalog > Products and create a configurable product
- Under Advanced Inventory, set Qty Uses Decimals = Yes for their child's product
- Place an order for that product for any quantity decimal like 0.25
- Go to generate an invoice
- Qty To Invoice input is 0, change it manually to 0.25
- Click Update Qty



https://github.com/magento/magento2/assets/51680745/aef9a40b-a482-490e-ae28-aba91e6ab5c3


Quantity is not updating at all, still at 0 and totals is 0.

Hence Confirming the issue.

Thanks.

**Comment by digitalrisedorset** [comment] 2024-04-17 13:23
@magento I am working on this

**Comment by digitalrisedorset** [comment] 2024-04-17 13:36
I have created a new confirgurable with its children product using qty decimals. However, I have an error when I add the product to the cart. With this situation, I am unable to reproduce the issue at the moment

**Comment by engcom-Bravo** [comment] 2024-07-10 11:32
Hello,

Internal team has started to work on it

Thanks.

**Comment by engcom-Bravo** [comment] 2024-07-12 07:14
Hi @marumehrts,

Thanks for your reporting and collaboration.

we have analysed the issue on the 2.4 develop and followed the given steps for reproducing the issue. We have found that the issue is not reproducible. I have attached the screen recording for reference “.



https://github.com/user-attachments/assets/3f623a73-8e90-4867-a836-6b56ba7a85fa



Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-12 07:14 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P1, Progress: done, Component: order status, Area: Order, Reported on 2.4.5-p5
