### ISSUE TITLE
Quote stays flagged as "customer_is_guest = 1" after login

### ISSUE THREAD

**Issue by thompalstra** [magento/magento2#24654] opened 2019-09-19 09:48 UTC
### Preconditions (*)

1. Magento 2.3.2

### Steps to reproduce (*)

1. Be a guest
2. Put an item in the cart
3. Go to checkout
4. Fill in an email address for a non-existing user
5. Fill in the password and password repeat inputs
6. Submit order
7. When in the payment provider's page, go back to the website
8. Login as your newly created user
9. Go to checkout
10. Submit order

### Expected result (*)

1. Redirect to the payment provider

### Actual result (*)

1. A message with "Invalid customer address id ID" is displayed
2. The quote record still being flagged as "customer_is_guest = 1" 
3. Traced back problem module-quote/Model/QuoteAddressValidator:79 triggering the message. Logged the $address id which returned a quote_address id and not a customer_address id.

**Comment by engcom-Charlie** [comment] 2019-09-19 13:12
Hello @thompalstra !
I can't reproduce this issue by following steps:

1. Be a guest
2. Put an item in the cart
3. Go to checkout
4. Fill in an email address for a non-existing user
5. Submit order
6. When in the payment provider's page, use "Create an account" button
7. Login as your newly created user
8. Go to checkout
9. Submit order

**Actual result:**

1. Redirect to the payment provider
2. The quote record being flagged as "customer_is_guest = 0"

Could you add any steps, if i made a mistake?

**Comment by engcom-Charlie** [comment] 2019-10-02 08:28
I am closing this issue now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by orthener** [comment] 2019-12-06 20:08
Getting the same error on 2.3.2 EE. And when add product as guest (in private mode) - field "customer_is_guest" = 0. ("Guest checkout" disabled)
No one else came across this?

**Comment by devendrant** [comment] 2020-05-01 07:28
Issue is still there. Please reopen this bug.

**Comment by archonkulis** [comment] 2020-05-21 10:52
Same issue happening onver. 2.3.4-p2

Inside checkout/#shipping URI when selecting existing address and clicking Continue, it makes a request to rest/default/V1/carts/mine/shipping-information

And inside here, the vendor/magento/module-checkout/Model/ShippingInformationManagement.php calls ->validateForCart

And that vendor/magento/module-quote/Model/QuoteAddressValidator.php $cart->getCustomerIsGuest() returns 1 even though I'm logged in.

**Comment by CsSatter** [comment] 2020-06-16 15:22
Hi,
We're currently also encountering this issue. @archonkulis @devendrant, have two been able to find a solution to this issue? A fix for this issue would be for to have 
`$quote->setCustomerIsGuest(false)` place in a method that would make this relevant. I.e. when you login and merge the quote.

Will provide a solution / PR if you haven't been able to solve this :)

**Comment by devendrant** [comment] 2020-06-16 16:23
@CsSatter we are still looking for a fix, please share with us the solution in detail

**Comment by CsSatter** [comment] 2020-06-17 09:49
Hi @devendrant,
I solved the issue by creating a patch to add `$this->setCustomerIsGuest(false);` on `Magento\Quote\Model\Quote::setCustomer` method.

This method is expected to be removed due to MAGETWO-19930.

I've considered creating a plugin (so it'll work with third party PSP implementations) on the `registerCancellation` method of `Magento\Sales\Model\Order` that'll use the `Magento\Quote\Model\QuoteManagement::assignCustomer` functionality. However due to time restraints I won't be able to implement and properly test this.

Hopefully this information will help you towards a working solution!

**Comment by GiantHoax** [comment] 2021-06-23 12:48
@CsSatter Can you share the patch you made? Im having the same issue.

**Comment by cfarnleitner** [comment] 2022-02-23 11:07
I just came across this issue's description in a clients live env. Even though I can yet not verify the steps taken, that lead to this situation, what is mentioned in "Actual result" (quote's customer_is_guest=1 and customer_id != null) can be seen in v2.4.3-p1 as well.

I'll try to come back to this issue with a better idea on what actually happened from the user perspective as this has occurred exactly twice according to the exception.log (~0,1% of all quotes in this particular env) - hence seems to be "some weird edge case only".

**Comment by antbates91** [comment] 2022-02-25 09:16
I have also come accross this issue.

I spotted it when the shipping address validation started to fail on the checkout.

This is because the quotes were marked as guest, despite being logged in and a guest can't have an address id belonging to a logged in customer.

**Comment by engcom-Delta** [comment] 2022-03-03 05:53
Hi @thompalstra ,

Thank you for reporting the issue.but we need little bit of clarification about the steps you provided to reproduce.
Step#5 says "Fill in the password and password repeat inputs".
![Screenshot from 2022-03-02 17-23-20](https://user-images.githubusercontent.com/51681379/156504723-084c2565-2a5e-4778-bfad-c0063c267fc0.png)


As per above screenshot we could not find out field for password.
So please review the steps provided. Hence Adding the label "Needs Update".

**Closed as completed** 2022-03-21 09:41 UTC
Labels: Issue: needs update, Area: Account

**Comment by thompalstra** [comment] 2022-03-21 10:11
@engcom-Delta what are you talking about? This has been an issue since 2019 so that's been 3 years now and suddenly you "get the urge" to close this ticket?

**Comment by facundo-improntus** [comment] 2022-05-13 17:59
Just happen to me in 2.4.3-p2 so the issue has not been fixed yet. The only solution it came to my mind is create a plugin to "getCustomerIsGuest" function to return if the quote has customer_id or not, deprecating the customer_is_guest flag.

**Comment by neddy236** [comment] 2022-05-18 20:40
Issue Still occurs in 2.4.3-p1 when trying to remove item from the cart for my case

**Comment by TomZhuPlanetart** [comment] 2022-05-30 08:43
I'm seeing it on 2.4.3, just a few minutes ago.  No exact steps yet. A few customers were complaining that the shipping methods were not able to load.

**Comment by WouterSteen** [comment] 2023-05-12 13:34
Still not sure how to reproduce. 

- Customer creates a quote
- After qoute, he logs in
- `customer_is_guest ` is still on 1 eventhough this is not true anymore.

Fixed it with this patch:

```
--- a/Model/QuoteAddressValidator.php
+++ b/Model/QuoteAddressValidator.php
@@ -127,6 +127,11 @@
      */
     public function validateForCart(CartInterface $cart, AddressInterface $address): void
     {
+        if ($cart->getCustomerIsGuest()) {
+            if (!empty($cart->getCustomerId())) {
+                $cart->setCustomerIsGuest(false);
+            }
+        }
         $this->doValidate($address, $cart->getCustomerIsGuest() ? null : $cart->getCustomer()->getId());
     }
 }
```

**Comment by facundo-improntus** [comment] 2023-05-15 18:09
There is a patch now that can be applied for 2.4.3-p2 and before: https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/support-tools/patches/v1-0-6/mdva-30599-magento-patch-customer-is-guest-is-set-incorrectly.html?lang=en

**Comment by hoanganhchang** [comment] 2023-12-20 09:08
The issue still happening. 
Solution (bad) is modify database, set customer_is_guest to 0

**Comment by hoanganhchang** [comment] 2023-12-25 04:31
reproduce:
When customer not login, add product to cart
After, customer login, add more product to cart
Then checkout, the issues will appear
Reason: 
In the first time, customer not login, customer_is_guest will insert to qoute table with value is 1
Then customer login, add more product to cart, magento 2 will update this record with customer infor, excepxt customer_is_guest (still 1)

Soulution: Add the Plugin when customer add product to cart
`public function beforeAddProduct(
        \Magento\Quote\Model\Quote $subject,
        \Magento\Catalog\Model\Product $product,
        $request = null,
        $processMode = \Magento\Catalog\Model\Product\Type\AbstractType::PROCESS_MODE_FULL
    ) {

        if ($subject->getCustomer()->getId()) {
            $subject->setCustomerIsGuest(0);
        }

        return [$product, $request, $processMode];
    }`
