### ISSUE TITLE
"The signature is invalid. Verify and try again." on adding searchCriteria[pageSize]=10 to products/attributes api call

### ISSUE THREAD

**Issue by devops724** [magento/magento2#33940] opened 2021-08-28 07:28 UTC
Mangeto version 2.4.3

1. create new integration in admin/admin/integration/
2. set Resource Access to all
3. set Consumer Key, Consumer Secret, Access Token, Access Token Secret  in Insomnia or postman
4. send request to /rest/V1/products/attributes?searchCriteria=0 there is not issue return first 20  attribute items
5. send request to /rest/V1/products/attributes?searchCriteria[pageSize]=10 get error
{
  "message": "The signature is invalid. Verify and try again."
}

### Expected result (*)
show first 10 items

### Actual result (*)
{
  "message": "The signature is invalid. Verify and try again."
}

**Comment by devops724** [comment] 2021-08-30 05:17
what if found is 
seems that after change Signature Method to SHA-256 
i don't have this issue,
it only raise in SHA1

**Comment by engcom-November** [comment] 2021-08-30 09:11
Verified the issue on both Magento 2.4-develop and 2.4.3 versions and the issue is not reproducible.
![image](https://user-images.githubusercontent.com/60198231/131315502-585da364-ca64-4dda-9302-33582fa95a19.png)
@devops724, As per the Magento official docs, Magento supports multiple algorithms like MD5, SHA256, or Argon 2ID13. If the Sodium extension is installed (installed by default in PHP 7.3), then Argon 2ID13 will be chosen as the default hashing algorithm. Otherwise, SHA256 will be as default. 
Kindly check the [ref docs ](https://devdocs.magento.com/guides/v2.4/config-guide/secy/hashing.html)
https://docs.magento.com/user-guide/system/encryption-key.html and recheck the behavior on 2.4-develop branch. If the issue is still reproducible, please elaborate the steps to reproduce.
Thank you.

**Comment by engcom-November** [comment] 2021-09-13 05:52
Hi @devops724 ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-09-13 05:52 UTC
Labels: Issue:  Cannot Reproduce, Component: Api, Issue: needs update, Reported on 2.4.3, Area: APIs
