### ISSUE TITLE
Undefined Index Name on Product Import 

### ISSUE THREAD

**Issue by jankovandeventer** [magento/magento2#25956] opened 2019-12-09 08:41 UTC
### Preconditions (*)

1. Magento ver. 2.3.3
2. PHP7.2, MYSQL5.7
3. Magento 2 Store with Products

### Steps to reproduce (*)

1. Create Update CSV with sku and url_key
2. Duplicate url_key exists in file for one or more rows
3. Go to System -> Data Transfer -> Import
4. Import Settings:
- Product
- Add/Update
5. Check Data

### Expected result (*)

1. duplicatedUrlKey error is shown with sku and row number

### Actual result (*)

1. Notice: Undefined index: name in vendor/magento/module-catalog-import-export/Model/Import/Product.php on line 2461
This error is shown because it wants to add the **name** to the error. However, it is not mandatory to import the **name**. In my opinion it would be better to always add the **sku** to errors, because this is the only mandatory field for imports of Products.

``` $this->addRowError(
                        ValidatorInterface::ERROR_DUPLICATE_URL_KEY,
                        $rowNum,
                        $rowData[self::COL_NAME],
                        $message,
                        $errorLevel
                    )
```

**Comment by magento-engcom-team** [comment] 2019-12-09 10:57
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29540` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment] 2024-05-09 12:31
Hi @jankovandeventer,

Thanks for your reporting and collaboration.

We have verified the issue and the issue is no more reproducible in Latest 2.4-develop instance.Kindly refer the screenshots.

**Steps to reproduce**


- Create Update CSV with sku and url_key
- Duplicate url_key exists in file for one or more rows
- Go to System -> Data Transfer -> Import
- Import Settings:
- Product
- Add/Update
- Check Data


![unnamed](https://github.com/magento/magento2/assets/51680745/731279ec-0f80-4da6-84c1-b5fb32e0870e)



duplicatedUrlKey error is shown with sku and row number.


Hence We are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-05-09 12:31 UTC
Labels: Issue: Ready for Work, Component: ImportExport, Issue: Confirmed, Issue: Format is valid, Reproduced on 2.4.x, Priority: P3, Severity: S2, Triage: Done, Progress: done
