### ISSUE TITLE
Swatch not updating to show out of stock and are able to click [2.2.1]

### ISSUE THREAD

**Issue by dawhoo** [magento/magento2#12474] opened 2017-11-28 21:09 UTC
### Preconditions
1. Magento 2.2.1 Production 
2. PHP 7.0.23
3. SQL Server version: 5.6.36-82.0 - Percona Server (GPL), Release 82.0, Revision 58e846a

### Steps to reproduce
1. Configurable Product with 2 sub attributes (Color(Red,Green), Size(S,M,L)
2. Set Inventory as 1 for each child
3. Add Red,M product to cart and checkout
4. Process the order so the item inventory is updated to "0"
5. Verify item inventory is 0 and make sure backorders are not allowed.

### Expected result
1. The Red,M swatch should have the red slash.
2. The Red,M swatch should not be able to be selected

### Actual result
1. The Red,M swatch does not have the red slash.
2. The Red,M swatch is able to be selected. 
3. When you clock "Add to Cart" error displays on product page "You need to choose options for your item."

Magento 2.1.9 updated to 2.2.1 - The problem did not occur in 2.1.9, but it is present in 2.2.1

Products that were out of stock in 2.1.9 had the red slash and your couldn't select that option. After the upgrade, all existing combinations are able to be selected despite being out of stock. 

In cataloginventory_stock_status, the items are showing stock_status 0 for items sold in 2.1.9 and 2.2.1
In cataloginventory_stock_status_idx the items are showing stock_status 1 for items sold after upgrading to 2.2.1, and stock status as 0 for items sold in 2.1.9

**Comment by magento-engcom-team** [comment] 2017-11-29 10:30
@dawhoo, thank you for your report.
We've created internal ticket(s) MAGETWO-84694 to track progress on the issue.

**Comment by sennin32** [comment] 2017-12-04 08:34
Not only Swatch.
I'm facing the same issue for simple item and configurable items.
Worst of all, some configurable items is not show even the stock quantity is positive, in stock, and enabled.

**Comment by santhoshp** [comment] 2018-01-07 04:34
I am working on it. #mm18in

**Comment by magento-engcom-team** [comment] 2018-01-07 04:48
@santhoshp thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by chedaroo** [comment] 2018-01-17 12:47
Is this not a dupe of #12317?

**Comment by mysil2** [comment] 2018-01-29 07:43
@chedaroo Seems to me.

Fixed in 2.2.4-preview branch: #12936 

From the latest comment a backport to 2.3 is planned.

**Comment by okorshenko** [comment] 2018-03-15 15:42
Hi @chedaroo @mysil2 thank you for linking the issue and PRs. Closing the issue

**Closed as completed by okorshenko** 2018-03-15 15:42 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Issue: Format is valid

**Comment by okorshenko** [comment] 2018-03-15 15:44
Hi @mysil2 Thank you for your involvement to Magento Community. I just sent you an invitation to magento organization or the github. Please accept the invite and you will be able to close the issue when you find that they are already fixed.
