### ISSUE TITLE
Logo is always 170 pixels wide, regardless of actual size

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#29721] opened 2020-08-23 12:00 UTC
### Preconditions (*)
1. 2.4-develop

### Steps to reproduce (*)
1. Login to Admin
2. Content -> Configuration -> Global -> Edit -> Header
3. Upload 800x300 example logo image (attached to issue)
4. Enter 800 in Logo Attribute Width
5. Enter 300 in Logo Attribute Height
6. Save Configuration
7. Clear cache
8. Go to frontend and inspect logo dimensions

### Expected result (*)
1. Logo is 800 pixels wide

### Actual result (*)
1. Logo is 170 pixels wide

![image](https://user-images.githubusercontent.com/30697781/90977843-be347d00-e540-11ea-95af-16288312a97b.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

The cause is this

https://github.com/magento/magento2/blob/8b7d949bf1cb67d7b98379fb30b6721ec7b92b37/app/design/frontend/Magento/blank/Magento_Theme/layout/default.xml#L8-L16

And was introduced here. https://github.com/magento/magento2/pull/27497

![800x300 example logo](https://user-images.githubusercontent.com/30697781/90977830-a0ffae80-e540-11ea-9c26-972d977618cc.jpg)

**Comment by ajijshekh123** [comment] 2020-08-25 06:02
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-08-25 06:02
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-08-25 06:03
Hi @ajijshekh123, here is your [Magento instance](https://i-29721-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29721-2-4-develop.instances.magento-community.engineering/admin_2352](https://i-29721-2-4-develop.instances.magento-community.engineering/admin_2352)
Login: `58aa3b1b` Password: `509815ad9f08`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2020-08-25 06:19
Hello @gwharton,
I thought this is not an issue but this is a Magento feature.
As per your steps to be reproduced, actual result and expected result. I have reproduced on Magento 2.4 Instance.
PFA:
Admin:
![image](https://user-images.githubusercontent.com/24711761/91130202-ebac3280-e6c8-11ea-9148-2abc552c1eaf.png)

Front end:
![image](https://user-images.githubusercontent.com/24711761/91130092-bd2e5780-e6c8-11ea-9a7f-0a6b203d6a10.png)

Thanks.

**Comment by magento-engcom-team** [comment] 2020-08-25 06:21
@ajijshekh123 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2020-08-25 06:22
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36982` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by konarshankar07** [comment] 2020-08-25 08:39
@magento I'm working on this

**Comment by klein0r** [comment] 2020-10-25 19:08
The reason is, that `Magento_Theme/layout/default.xml` provides a default of 170 (and the block doesn't read the database config if the value is already present in the data storage). So I've created a workaround by using my own themes default.xml to override that value with my correct value.

```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="logo">
            <arguments>
                <argument name="logo_width" xsi:type="number">100</argument>
                <argument name="logo_height" xsi:type="number">100</argument>
            </arguments>
        </referenceBlock>
    </body>
</page>
```

**Comment by konarshankar07** [comment] 2020-10-26 05:02
Hello @klein0r ..
True.. But if we changed from the xml layout then what's the point of having the theme configuration in the backend? The preference would be if the value from the theme configuration is empty then it should take the value from the layout otherwise it should be taken from the theme configuration.

**Comment by klein0r** [comment] 2020-10-26 08:53
@konarshankar07 I've said that this is a workaround for the issue until it is fixed. Or what is your recommendation for the current situation?

**Comment by konarshankar07** [comment] 2020-10-26 08:59
@klein0r ..
I agree with you but I have submitted the fix which will sort this issue. If you want to get more information then you check out my PR https://github.com/magento/magento2/pull/29746

**Comment by klein0r** [comment] 2020-10-26 09:03
I've seen that. But I've decided to create a default.xml for my shop, which is much easier to maintain than an additional patch file.

**Comment by magentoexpert** [comment] 2021-01-24 16:23
This is not a fix for Magento 2.4.1 installed with composer. The new folder structure is completely different which includes /pub
The folder structure   /app/design/frontend/Magento/  referred to above is empty and obsolete

**Comment by denistrator** [comment] 2022-01-15 15:46
Easy workaround
```
<referenceBlock name="logo">
    <arguments>
        <argument name="logo_width" xsi:type="null"/>
    </arguments>
</referenceBlock>
```

**Comment by Poovarasan-06** [comment] 2023-08-21 13:27
@magento give me 2.4-develop instance

**Comment by Poovarasan-06** [comment] 2023-08-22 04:54
@magento give me 2.4-develop instance

**Comment by Poovarasan-06** [comment] 2023-08-22 08:21
@gwharton Hey, this issue is not reproducible in both testing instance and with my local setup.

**Comment by Detzler** [comment] 2023-11-03 09:28
got this issue also on 2.4.6-p2

**Comment by isevchris** [comment] 2023-11-22 11:47
This appears to still be an issue with Magento 2.4.4-p6 at least, if your theme inherits from Magento Blank.

Essentially the logo image size gets loaded in from the following XML file:
_./vendor/magento/theme-frontend-blank/Magento_Theme/layout/default.xml_

If you override that file in your theme directory (./app/design/frontend); and set the xsi:type to `null` you can force it to load in the values from the database: core_config_data -> design/header/logo_width (or height).

```
    <referenceBlock name="logo">
        <arguments>
            <argument name="logo_width" xsi:type="null"></argument>
            <argument name="logo_height" xsi:type="null"></argument>
        </arguments>
    </referenceBlock>
```

**Comment by engcom-Bravo** [comment] 2024-06-06 04:34
Hi @gwharton,

Thanks for your reporting and collaboration.

we have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

<img width="1508" alt="Screenshot at May 27 15-11-32" src="https://github.com/magento/magento2/assets/51680745/727b8ad1-b538-4827-b335-d5e614f1aae1">


Logo is 800 pixels wide

Hence We are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-06 04:34 UTC
Labels: Issue: Ready for Work, Area: Frontend, Issue: Confirmed, Issue: Format is valid, Component: Image, Reproduced on 2.4.x, Priority: P3, Severity: S3, Progress: done, Reported on 2.4.0
