### ISSUE TITLE
Create New Order in Admin: Items Ordered do not update and without key  magento 2.4.3

### ISSUE THREAD

**Issue by lwunguyen** [magento/magento2#34151] opened 2021-09-24 04:45 UTC
Hello, 
After upgrading to magento 2.4.3, i am facing this problem:
Here are the steps:
1. Go to Sales > Orders
2. Click on 'Create new order' button
3. Search for the customer by filtering the email address by the term 'shivraj'
4. click on the record with an account
5. Select 'Chrome battery' store.
6. Click on 'Add products' button
7. Add just one product
8. Click on the button 'Add selected products to the order'
9. The infinite loader shows
10. then the page that loads doesn't have the product in it

And I see url has no key  /admin_cb/sales/order_create/index/

Please check for me, thanks

**Comment by engcom-November** [comment] 2021-09-24 12:48
Verified the issue on Magento 2.4.3 version after upgrading from 2.4.2-p1 and cannot able to reproduce this issue:

**Steps performed:**
Admin - Sales - Orders - Create New Order
Applied Email filter and selected Email address
Selected other store view (Ex: myteststore)
Add Products - Selected one Simple Product - Add Selected Products to Order - No issue
Select Payment and Shipping Method
Placed Order - No issue: User is able to submit order
![image](https://user-images.githubusercontent.com/60198231/134676540-84e57894-4f45-41c2-bd01-d4af084a84d4.png)
![image](https://user-images.githubusercontent.com/60198231/134676587-fadb9d5c-83b8-4fd0-bead-47bbcc6d6f1b.png)
![image](https://user-images.githubusercontent.com/60198231/134676492-96ae4f0a-d593-4bc7-a431-826ad2bfd996.png)
Kindly recheck the issue again and provide missing steps if any if the issue is still reproducible.
This issue is also not reproducible on Magento 2.4-develop branch which is having the latest code base.
Thank you.

**Comment by hryvinskyi** [comment] 2021-09-30 11:16
@springluu @engcom-November The same issue on three sites in magento 2.4.3

**Comment by engcom-November** [comment] 2021-10-04 13:48
Hi @hryvinskyi , can you please recheck the issue on Magento 2.4-develop branch as 2.4.3 is merged to 2.4-develop and it has the latest code base.
As mentioned in [comment](https://github.com/magento/magento2/issues/34151#issuecomment-926598490), even after upgrading from 2.4.2-P1 to 2.4.3 having multi store setup, we are not able to reproduce this issue.
Thank you.

**Comment by chattertech** [comment] 2021-10-13 03:08
I have the same issue. I updated from 2.4.2 to 2.4.3. I have found a work around but it's a bit of a pain. After every product added or updated you have to reload the page and the product(s) or changes will show on the page. Besides the product issue the rest of the page works fine. Running on PHP 7.4 with Redis 6.

Video here...
https://www.screencast.com/t/ePqbbrS3

**Comment by jordanvector** [comment] 2021-11-03 12:05
@chattertech great find!  This was the answer to a lot of what seemed like unrelated admin issues we were having after the 2.4.3 update.  They were all related to this setting, and setting to 0 fixed the issues for us.

**Comment by engcom-November** [comment] 2021-11-19 10:07
Hi @springluu 
We are closing this issue as the session storage issue is being tracked on https://github.com/magento/magento2/issues/33748. Please check this ticket for latest updates/ workaround. Kindly reopen the ticket if you are still not able to create order along with missing steps.
Thank you.

**Closed as completed by engcom-November** 2021-11-19 10:07 UTC
Labels: Issue: needs update, Reported on 2.4.3
