### ISSUE TITLE
Base table or view not found: 1146 Table 'magento.tfa_user_config' doesn't exist

### ISSUE THREAD

**Issue by qiangvei** [magento/magento2#38383] opened 2024-01-26 08:16 UTC
### Preconditions and environment

- Magento Open Source2.4.7-beta2 

### Steps to reproduce

1.`bin/magento mod:disable Magento_AdminAdobeImsTwoFactorAuth Magento_TwoFactorAuth`
2.`bin/magento setup:upgrade`
3.`bin/magento setup:di:compile && bin/magento setup:static-content:Deploy -f && bin/magento cache:flush && bin/magento indexer:reindex`
4.Log in to the management backend, open the backend: "Cache Management" and click the "Flush Magento Cache" button

### Expected result

> There has been an error processing your request
> Exception printing is disabled by default for security reasons.
> 
> Error log record number: 44537f447934491b3a25caa1de9ad965b12716bee1fdcb1425c92df8a60f853b

**File: 44537f447934491b3a25caa1de9ad965b12716bee1fdcb1425c92df8a60f853b**
```yaml
{"0":"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.tfa_user_config' doesn't exist, query was: SELECT `tfa_user_config`.* FROM `tfa_user_config` WHERE (`tfa_user_config`.`user_id`=1)","1":"#1 Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql->query() called at [vendor\/magento\/zend-db\/library\/Zend\/Db\/Adapter\/Abstract.php:756]\n#2 Zend_Db_Adapter_Abstract->fetchRow() called at [vendor\/magento\/framework\/Model\/ResourceModel\/Db\/AbstractDb.php:333]\n#3 Magento\\Framework\\Model\\ResourceModel\\Db\\AbstractDb->load() called at [vendor\/magento\/module-two-factor-auth\/Model\/UserConfigManager.php:118]\n#4 Magento\\TwoFactorAuth\\Model\\UserConfigManager->getUserConfiguration() called at [vendor\/magento\/module-two-factor-auth\/Model\/UserConfigManager.php:148]\n#5 Magento\\TwoFactorAuth\\Model\\UserConfigManager->getProvidersCodes() called at [vendor\/magento\/module-two-factor-auth\/Observer\/AdminUserLoadAfter.php:42]\n#6 Magento\\TwoFactorAuth\\Observer\\AdminUserLoadAfter->execute() called at [vendor\/magento\/framework\/Event\/Invoker\/InvokerDefault.php:88]\n#7 Magento\\Framework\\Event\\Invoker\\InvokerDefault->_callObserverMethod() called at [vendor\/magento\/framework\/Event\/Invoker\/InvokerDefault.php:74]\n#8 Magento\\Framework\\Event\\Invoker\\InvokerDefault->dispatch() called at [vendor\/magento\/framework\/Event\/Manager.php:65]\n#9 Magento\\Framework\\Event\\Manager->dispatch() called at [generated\/code\/Magento\/Framework\/Event\/Manager\/Proxy.php:105]\n#10 Magento\\Framework\\Event\\Manager\\Proxy->dispatch() called at [vendor\/magento\/framework\/Model\/AbstractModel.php:589]\n#11 Magento\\Framework\\Model\\AbstractModel->_afterLoad() called at [vendor\/magento\/framework\/Model\/AbstractModel.php:613]\n#12 Magento\\Framework\\Model\\AbstractModel->afterLoad() called at [vendor\/magento\/framework\/Model\/ResourceModel\/Db\/AbstractDb.php:342]\n#13 Magento\\Framework\\Model\\ResourceModel\\Db\\AbstractDb->load() called at [vendor\/magento\/framework\/Model\/AbstractModel.php:548]\n#14 Magento\\Framework\\Model\\AbstractModel->load() called at [vendor\/magento\/module-user\/Model\/User.php:671]\n#15 Magento\\User\\Model\\User->reload() called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:124]\n#16 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#17 Magento\\TwoFactorAuth\\Controller\\Adminhtml\\Tfa\\Requestconfig\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#18 Magento\\TwoFactorAuth\\Controller\\Adminhtml\\Tfa\\Requestconfig\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/TwoFactorAuth\/Controller\/Adminhtml\/Tfa\/Requestconfig\/Interceptor.php:32]\n#19 Magento\\TwoFactorAuth\\Controller\\Adminhtml\\Tfa\\Requestconfig\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:245]\n#20 Magento\\Framework\\App\\FrontController->getActionResponse() called at [vendor\/magento\/framework\/App\/FrontController.php:212]\n#21 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:146]\n#22 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#23 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#24 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#25 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:23]\n#26 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:116]\n#27 Magento\\Framework\\App\\Http->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:264]\n#28 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:30]\n","url":"\/admin_wei\/tfa\/tfa\/requestconfig\/key\/0f60bcfaa47ceea3fd8ffb861445f26b565915b2367b5024ab76f50534d5262b\/","script_name":"\/pub\/index.php","report_id":"44537f447934491b3a25caa1de9ad965b12716bee1fdcb1425c92df8a60f853b"}

```
**At this point, when I log in to the management backend, I jump to this exception page.**

### Actual result

![image](https://github.com/magento/magento2/assets/33819863/5fccbcc7-3ea5-4f54-91f4-2f96edf712da)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2024-01-30 08:06
Hi @qiangvei 

Thanks for reporting and collaboration.

Verified the issue in magento 2.4 dev instance but the issue is not reproducable

We have followed the steps mentioned in the steps to reproduce but the admin is working for for us.

Please refer the attached screenshots.

<img width="1440" alt="Screenshot 2024-01-30 at 1 29 55 PM" src="https://github.com/magento/magento2/assets/60198592/9b8973a6-7932-4cd5-b279-70355f2c1ae0">
<img width="1440" alt="Screenshot 2024-01-30 at 1 30 13 PM" src="https://github.com/magento/magento2/assets/60198592/f9399b8d-35fc-4f0f-a8e1-6f8cdbdf9cdf">

Please verify the issue again and let us know if you are still facing the issue.

**Comment by engcom-Dash** [comment] 2024-02-16 08:58
HI @qiangvei 

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Dash** 2024-02-16 08:58 UTC
Labels: Issue: needs update
