### ISSUE TITLE
Update quote item qty require qty stock to be at least 2

### ISSUE THREAD

**Issue by alexmtch** [magento/magento2#33425] opened 2021-07-06 11:59 UTC
### Preconditions (*)

1. Magento 2.3.6

### Steps to reproduce (*)

1. Create a product
2. Set the stock quantity of 1
3. Add a customizable option required with no price (ex : size L/M/S)
3. Put the product into the cart
4. Change the selected option

### Expected result (*)

1. The product option should be updated

### Actual result (*)

1. An error "The requested qty is not available." appear

### Workaround
1. The issue is due to of the double call of Magento\Quote\Model\Quote\Item::setQty
2. Theses 2 calls are related with :
- \Magento\Quote\Model\Quote\Item\Processor::prepare with the call of "$item->addQty($candidate->getCartQty());"
- \Magento\Quote\Model\Quote\Item\AbstractItem::checkData with the call of $this->setQty($qty);
The checkData is called by every Magento\Quote\Model\ResourceModel\Quote\Item\Collection->_assignProducts()

As this process, the event "sales_quote_item_qty_set_after" is trigger 2 times an then trigger 2 times in cascade theses :
- \Magento\CatalogInventory\Observer\QuantityValidatorObserver
- \Magento\CatalogInventory\Observer\QuantityValidator::validate  calling $this->stockItemInitializer->initialize($stockItem, $quoteItem, $qty);
- \Magento\CatalogInventory\Model\Quote\Item\QuantityValidator\Initializer\StockItem::initialize

You could check that the value of $qtyForCheck will be 1 and then "2".

Maybe we could temporary fix this patch with this way :
- Creating a new instance of Magento\Quote\Model\Quote\Item without the useless setQty
- Creating a new instance of Magento\Quote\Model\ResourceModel\Quote\Item\Collection and binding the model as the new created
- Create a cascade of virtual types to replace the collection used by the cart model in the UpdateItemOptions controller

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by alexmtch** [comment] 2021-07-06 13:50
May it be a possible dupplicate of https://github.com/magento/magento2/issues/18812 but my workaround may be interesting to integrate in this issue

**Comment by magento-engcom-team** [comment] 2021-07-18 04:30
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42873` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Hotel** [comment] 2021-08-03 12:05
Hello @alexmtch,

It seems the issue is a duplicate of this [issue](https://github.com/magento/magento2/issues/18812). So we are closing this ticket.

Thanks

**Closed as completed by engcom-Hotel** 2021-08-03 12:05 UTC
Labels: Component: Catalog, Reproduced on 2.4.x, Progress: done, Reported on 2.3.6

**Comment by Hawksama** [comment] 2026-09-01 12:47
Root-caused this while investigating a checkout-load failure on 2.4.8-p5:

`Quote::updateItem()` calls `$buyRequest->setResetCount(true)` so `Quote\Item\Processor::prepare()` zeroes the item qty before re-adding it. But that guard is `$request->getResetCount() && !$candidate->getStickWithinParent() && $item->getId() == $request->getId()`, and the buy request rebuilt for an options product (configurable/bundle) via `CartItemProcessor::convertToBuyRequest()` carries **no id**. So `$request->getId()` is null, the guard never matches, the reset is skipped, and `Item::addQty()` accumulates the qty (1 → 2) instead of resetting it.

`updateItem()` does correct the qty afterwards (`setQty($buyRequest->getQty())`), but the `sales_quote_item_qty_set_after` validator runs inside `addProduct()` first — so when the item's salable qty is 1, the salability check sees requested 2 > available 1 and throws before the correction. That is the "requires qty stock to be at least 2" behavior. It became reachable on unchanged-qty re-saves after ACSD-46869 made `CartItemPersister` call `updateItem()` whenever the quote is active.

Opened a fix that stamps the item id onto the buy request so the intended reset actually fires: #41180
