### ISSUE TITLE
Search results exception [prefix_search] not found

### ISSUE THREAD

**Issue by baoutch** [magento/magento2#33930] opened 2021-08-27 10:12 UTC
### Preconditions (*)

1. Magento 2.4.3 install
2. Elasticsearch 7.9 install

### Steps to reproduce (*)

1. Make a search with a product name

### Expected result (*)

1. Search results displayed

### Actual result (*)

1. Empty result with exception logged in exception.log

`[2021-08-27 09:52:46] main.CRITICAL: {"error":{"root_cause":[{"type":"query_shard_exception","reason":"[match_phrase_prefix] analyzer [prefix_search] not found","index_uuid":"fhpniNZoQvazWktqKq-EmQ","index":"magento2_product_1_v36"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"magento2_product_1_v36","node":"RYix5LgHRWalRpMrlGsivA","reason":{"type":"query_shard_exception","reason":"[match_phrase_prefix] analyzer [prefix_search] not found","index_uuid":"fhpniNZoQvazWktqKq-EmQ","index":"magento2_product_1_v36"}}]},"status":400} {"exception":"[object] (Elasticsearch\\Common\\Exceptions\\BadRequest400Exception(code: 400): {\"error\":{\"root_cause\":[{\"type\":\"query_shard_exception\",\"reason\":\"[match_phrase_prefix] analyzer [prefix_search] not found\",\"index_uuid\":\"fhpniNZoQvazWktqKq-EmQ\",\"index\":\"magento2_product_1_v36\"}],\"type\":\"search_phase_execution_exception\",\"reason\":\"all shards failed\",\"phase\":\"query\",\"grouped\":true,\"failed_shards\":[{\"shard\":0,\"index\":\"magento2_product_1_v36\",\"node\":\"RYix5LgHRWalRpMrlGsivA\",\"reason\":{\"type\":\"query_shard_exception\",\"reason\":\"[match_phrase_prefix] analyzer [prefix_search] not found\",\"index_uuid\":\"fhpniNZoQvazWktqKq-EmQ\",\"index\":\"magento2_product_1_v36\"}}]},\"status\":400} at H:\\wamp306\\www\\cdsud2\\src\\vendor\\elasticsearch\\elasticsearch\\src\\Elasticsearch\\Connections\\Connection.php:676)"} []
`

### Workaround 

Sneaking around I found that if I disable the new `MatchQueriesModifier` features in `vendor/magento/module-catalog-search/etc/di.xml` everything works back as expected with correct results.

Thanks

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by DkDavid** [comment] 2021-08-30 07:09
Same issue after upgrading to 2.4.3. How can i disable the MatchQueriesModifier?

**Comment by baoutch** [comment] 2021-08-30 07:41
What I did is in `src/vendor/magento/module-catalog-search/etc/di.xml` I commented out the last section 

`<type name="Magento\CatalogSearch\Model\Search\Request\MatchQueriesModifier">
...
</type>
`

**Comment by jorgb90** [comment] 2021-08-31 14:22
Same issue here! Confirmed.

**Comment by engcom-November** [comment] 2021-09-06 12:59
Hi @baoutch ,
Can you please share specific Catalog Configuration details / product configuration details to reproduce this issue.
I'm not able to reproduce this issue on Magento 2.4.3 clean instance and 2.4-develop branch as well.
Kindly recheck the issue on Magento 2.4-develop branch and confirm if this is still reproducible.
Thank you.

**Comment by jorgb90** [comment] 2021-09-08 06:42
@engcom-November I solved this issue now for two installations just by running indexer:reindex, so I guess this can be closed.

**Comment by engcom-November** [comment] 2021-09-09 05:12
Thanks for your confirmation @jorgb90. We are closing this issue as your issue is resolved now.

**Closed as completed by engcom-November** 2021-09-09 05:12 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.3
