### ISSUE TITLE
 Quote stays flagged as "customer_is_guest = 1" after login 

### ISSUE THREAD

**Issue by WouterSteen** [magento/magento2#37494] opened 2023-05-12 13:37 UTC
### Preconditions and environment

- 2.4.5

### Steps to reproduce

Not sure how to reproduce. 

We have a lot of cases where a customer_id is set in a quote, but the customer_is_guest flag is true as well.

### Expected result

When a customer logs in, the `customer_is_guest` needs to be 0 for all quotes from this customer.

### Actual result

`customer_is_guest` is true when logged in.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by WouterSteen** [comment] 2023-05-12 13:37
Workaround with this patch:

https://gist.githubusercontent.com/antbates91/3bed77ecc1179f197ad3e6fb42ab631f/raw/54fcc5b1f4335595cc24cc9ff51b7823b91f559a/fix_customer_is_guest_on_logged_in_quotes.patch

**Comment by WouterSteen** [comment] 2023-05-12 13:37
Prev issue that was closed : https://github.com/magento/magento2/issues/24654

**Comment by engcom-Bravo** [comment] 2023-05-15 13:07
Hi @WouterSteen,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

1.Add a product to cart.
2.Login as customer.

When we login as customer `customer_is_guest` is displaying 0.

<img width="413" alt="Screenshot 2023-05-15 at 4 16 36 PM" src="https://github.com/magento/magento2/assets/51680745/e5d4443e-b5b5-476f-98a5-06bba634f94d">



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-05-26 06:17
Hi @WouterSteen,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-05-26 06:17 UTC
Labels: Issue: needs update, Reported on 2.4.5

**Comment by lrotherfield-function** [comment] 2023-11-08 19:16
We have the same issue but it requires two stores that share a session, we have this for many clients where they have a US, EU, UK store etc:

Steps to reproduce:

1. Create a new customer account and logout
2. Create a guest quote on Store A by adding a product to your cart
3. Switch to Store B
4. Login on Store B
5. Switch to Store A (Should be logged in as session is shared)
6. Add product to cart

Quote should now have customer_is_guest = 1 and a customer_id
