### ISSUE TITLE
PDF Invoices downloads all invoices instead of selected one

### ISSUE THREAD

**Issue by anebi** [magento/magento2#8503] opened 2017-02-10 11:26 UTC
### Preconditions
1. Magento 2.0.11
2. PHP 7
3. Ubuntu 16.04
4. MariaDb 10

### Steps to reproduce

1. Create order
2. Check and complete payment process
3. Generate invoice in backend
4. Go to backend Sales -> Orders -> Open the order with the invoice
5. Click Invoices
6. Select the invoice
7. From dropdown click to PDF Invoice

### Expected result
1. Selected invoice must be generated and downloaded

### Actual result
1. All existing invoices are generated into a single PDF and downloaded

Note: If we go to Sales -> Invoices and select specific invoice, then we click on PDF Invoices, we get PDF with selected invoice. In that section the functionality works ok, but not when is done from inside Order -> Invoices tab.

**Comment by rudik99** [comment] 2017-02-12 07:28
This was fixed in 2.1.3 if that helps you

**Comment by anebi** [comment] 2017-02-12 13:54
Hi and thanks for your reply. Since 2.1.3 has many bugs I would like to stick to 2.0.x until Mage releases a good stable version. Is there any quick fix for this issue?

**Comment by magento-engcom-team** [comment] 2017-10-05 08:30
@anebi, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-05 08:30 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid
