### ISSUE TITLE
Image resize fails when same file name with diffrent case

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#37600] opened 2023-06-10 06:21 UTC
### Preconditions and environment

- Magento version 2.4.6

### Steps to reproduce

1. Add an image "test.jpg" to a product
2. Add another image "TEST.jpg" to the same product
3. Purge image cache
4. run `catalog:images:resize` 

### Expected result

Cache images is generated for both `test.jpg` and `TEST.jpg`

### Actual result

Cache images is only generated for one of those

### Additional information

Hotfix that works for us, in `src/vendor/magento/module-catalog/Model/ResourceModel/Product/Image.php` : 

replace `new \Zend_Db_Expr('count(distinct value)')` with `new \Zend_Db_Expr('count(distinct (BINARY value))')` (2 occurences), and remove `->distinct()` (2 occurences).

That's only a quickfix, it would be probably better to modify `->distinct()` with `distinct (BINARY value))` instead.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Nuranto** [comment] 2023-06-12 17:59
Hi @engcom-Bravo,

I see. Actually in my case, both images were imported via data migration tools, and were not renamed like this. So I'm not sure if you consider this as a bug or not... If not, feel free to close this issue.

**Comment by engcom-Bravo** [comment] 2023-06-15 06:42
Hi @Nuranto,


Thanks for your update.

As per this comment https://github.com/magento/magento2/issues/37600#issuecomment-1587814001 we are closing this issue since issue is no more reproducible and also images cached successfully. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.


Thanks

**Closed as completed by engcom-Bravo** 2023-06-15 06:42 UTC
Labels: Issue: needs update, Reported on 2.4.6
