### ISSUE TITLE
Bundle product goes out of stock after migrating from 2.1.9 to 2.2.4 (multi-store website)

### ISSUE THREAD

**Issue by rtplvaibhav** [magento/magento2#16288] opened 2018-06-21 09:50 UTC
After updating Magento from 2.1.9 to 2.2.4 products are going out of stock even though they are in stock. Happens with all types of product i think.

PHP 7.1.11 and 7.1.18
MYSQL = 5.6.39

Steps to reproduce:
Update Magento from composer and do reindexing.

**Possible reason:**
catalogInventory_stock reindexing is actually deleting entries from table cataloginventory_stock_status for all all website_ids and keeps only one for website_id = 0. 

I get to know about this by comparing the data of two tables before and after updating magento. Even i used the old cataloginventory_stock_status table for new setup and it worked. But again after reindexing, it deletes the entry from this table.

**Comment by engcom-backlog-nickolas** [comment] 2018-07-05 14:06
@rtplvaibhav. thank you for your report. 
Can you please answer couple questions?
How many websites do you have? 
If more than one, Mentioned products assigned to one website or to many, and they are out of stock on all websites, or just on additionals?
Have you tried to run bin/magento indexer:reindex; bin/magento cache:flush after upgrade?
Cause I could reproduce this issue just partially.
Steps I've done:
1. Install Magento 2.1.9
2. Create all types of products and assign them to category.
3. Make sure they all in stok and visible on storefront category page.
4. Upgrade Mangento to 2.2.4 version.
5. Navigate to storefront. Indeed, all products disappear from storefront category page.
6. Perform bin/magento indexer:reindex; bin/magento cache:flush
7. All products appear on storefront category page.

**Comment by rtplvaibhav** [comment] 2018-07-05 14:17
Hi Engcom,

Please find answers to your question below
1) How many websites do you have? ---- 3

2) If more than one, Mentioned products assigned to one website or to many, and they are out of stock on all websites, or just on additionals? ---- Product assigned to all website and are in stock. Actually all were in stock before upgrading but just after upgrading and reindexing it started showing as out of stock. Actually product started going out of stock after reindexing only(after upgrading to 2.2.4). 

3) Have you tried to run bin/magento indexer:reindex; bin/magento cache:flush after upgrade? ---- Yes but had no luck.

**Additional Info**
We tried to upgrade it step by step to all versions above 2.1.9 and it worked fine till 2.1.14 but just entering the 2.2.0 series it started showing products as out of stock.  

Very much similar to https://github.com/magento/magento2/issues/12330

**Comment by engcom-backlog-nickolas** [comment] 2018-07-05 15:01
@rtplvaibhav, thanks for feedback. Unfortunately I'm not able to reproduce this issue in multi-website environment with gradual update through versions too. And until this issue will be reproducible on clean magento instance with clear steps, we cannot fix it. If you have any additional information, feel free to reopen this issue, and I'll try to reproduce it with new details.

**Closed as completed by engcom-backlog-nickolas** 2018-07-05 15:01 UTC
Labels: Issue: Format is not valid
