### ISSUE TITLE
Category eav values are overwritten with default store Values

### ISSUE THREAD

**Issue by stkrelax** [magento/magento2#32478] opened 2021-03-15 09:05 UTC
### Preconditions (*)
1. Magento 2.3.5-p2
2. website_de -> store_group_de(rootcategory 2) -> store_de 
3. website_us -> store_group_us(rootcategory 2) -> store_us
4. all stores share the same category(cat1)
5. cat1 store 0 name set to foobar 
6. cat1 store_de name set to foobarè
7. cat1 store_us name set to foobarzz
8. "2 or more categorylink saves on the same category " Script that cause a change so that https://github.com/magento/magento2/blob/7d5967fca0b7d5a3646b42d5377dc54acb28d804/app/code/Magento/Catalog/Model/CategoryLinkManagement.php#L107 will be called
9. assure that 
 ```SELECT `main_table`.* FROM `store_group` AS `main_table` WHERE (`main_table`.`group_id` > 0) ORDER BY main_table.name ASC``` will return store_group_us
10. two products not assigned to cat1
 

### Steps to reproduce (*)
1. assign a product(prod1) to a category (cat1)
2. assign a product(prod2) to a category (cat1)
3. both calls in one script so that categoryRepository cache is used

### Expected result (*)
1. category name in store_us does not change

### Actual result (*)
1. second assign call overwrites store_us values with store 0

- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

Background:

in first assign 
https://github.com/magento/magento2/blob/7d5967fca0b7d5a3646b42d5377dc54acb28d804/app/code/Magento/Catalog/Model/CategoryLinkRepository.php#L58
loads cat1 without store_id so cachekey all in CategoryRepository

https://github.com/magento/magento2/blob/7d5967fca0b7d5a3646b42d5377dc54acb28d804/app/code/Magento/Catalog/Model/CategoryLinkRepository.php#L64
saves Category
after Save of Url Rewrite
https://github.com/magento/magento2/blob/7d5967fca0b7d5a3646b42d5377dc54acb28d804/app/code/Magento/CatalogUrlRewrite/Observer/CategoryProcessUrlRewriteSavingObserver.php#L187

sets store_id of last store_group default_store_id
store_id 2 will be set to category

second assign
https://github.com/magento/magento2/blob/7d5967fca0b7d5a3646b42d5377dc54acb28d804/app/code/Magento/Catalog/Model/CategoryLinkRepository.php#L58
loads cat1 without store_id so cachekey all in CategoryRepository
the cat1 will be loaded with cache_key all from repository cache
cat1 has set store_id 2 << PROBLEM

https://github.com/magento/magento2/blob/7d5967fca0b7d5a3646b42d5377dc54acb28d804/app/code/Magento/Catalog/Model/CategoryLinkRepository.php#L64
saves Category and overwrites the values in store 2 with the values from store 0

**Comment by engcom-Oscar** [comment] 2021-03-15 13:37
Hi @stkrelax  ! Thank you for your report.
Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop by following steps from this ticket.
### Steps to reproduce (*)
1. Magento 2.3.5-p2
2. website_de -> store_group_de -> store_de 
3. website_us -> store_group_us -> store_us
4. all stores share the same category(cat1)
5. cat1 store 0 name set to foobar 
6. cat1 store_de name set to foobarè
7. cat1 store_us name set to foobarzz
8. two products not assigned to cat1 created
9. assign a product(prod1) to a category (cat1)
10. assign a product(prod2) to a category (cat1)

**Actual Result:** :heavy_check_mark: 
Category name for store_us didn't change
![Screenshot from 2021-03-15 15-35-32](https://user-images.githubusercontent.com/60198413/111161772-29f53a80-85a4-11eb-9bdb-e4b84feaa2f9.png)
![Screenshot from 2021-03-15 15-35-54](https://user-images.githubusercontent.com/60198413/111161785-2cf02b00-85a4-11eb-83e5-d0d0b96d0341.png)

Can you please recheck if the issue reproducing on fresh clean Magento installation and reply?

**Comment by ilnytskyi** [comment] 2021-03-15 15:06
I think it can be also related to my issue 
https://github.com/magento/magento2/issues/22063
https://github.com/magento/magento2/pull/22064/files

**Comment by Thundar** [comment] 2021-03-26 13:21
I can reproduce the issue by using this api from within `\Magento\Catalog\Api\CategoryLinkManagementInterface` from a cron.
`$this->categoryLinkManagement->assignProductToCategories($sku, $newCategoryIds);`
I'll try @ilnytskyi solution.

**Comment by stkrelax** [comment] 2021-03-30 06:18
@engcom-Oscar 
Your Steps to reproduce 9 and 10 are wrong
i assume you go into admin and change each link seperatly...

have a look to my Steps to Reproduce:
3. both calls in one script so that categoryRepository cache is used

it is essential to assign both products to the same category in one request/script so that the cache is used.

@ilnytskyi you are absolutly right it would be fixed by your pull

https://github.com/magento/magento2/issues/22063
https://github.com/magento/magento2/pull/22064/files

**Comment by Thundar** [comment] 2021-03-30 06:55
It is fixed by @ilnytskyi pull for me too, tested in 2.3.6.

**Comment by engcom-Alfa** [comment] 2021-05-31 13:00
Hi @stkrelax 
Kindly try to reproduce upgrading to latest the version possibly and let me know if you are going to reproduce the same issue again.

**Comment by engcom-Alfa** [comment] 2021-06-01 12:39
As I have tested it today in 4.2-develop, there is no issue I found as such. Below are the screenshots on the same.
![image](https://user-images.githubusercontent.com/51679138/120324477-4d5a9680-c304-11eb-8140-49e2236e5f7c.png)
![image](https://user-images.githubusercontent.com/51679138/120324654-7d099e80-c304-11eb-949c-43f505a6c104.png)

**Comment by engcom-Alfa** [comment] 2021-06-16 05:26
As there is no response to my last comment in last ~14 days, closing this current issue.

Kindly upgrade to the latest version to re test. In case of any Magento related issues, you may please report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings possibly.

For any Magento related references, you may [go through the user guide](https://docs.magento.com/user-guide/).

**Closed as completed by engcom-Alfa** 2021-06-16 05:26 UTC
Labels: Progress: needs update, Issue: ready for confirmation

**Comment by ilnytskyi** [comment] 2021-10-04 10:20
@engcom-Alfa  I submited new fix for this issue. I managed to reproduce it with new Integration test here:
https://github.com/magento/magento2/pull/34226
the main fix is to replace `all` cache key in category repository with current store.

Please review this issue again
