### ISSUE TITLE
Configurable product preselect swatches or options when hash in URL is empty

### ISSUE THREAD

**Issue by daniel-ifrim** [magento/magento2#27569] opened 2020-04-04 09:19 UTC
### Preconditions (*)

1. Magento 2.3.4 develop

### Steps to reproduce (*)

1. Take a configurable product URL from PDP and add "#" hash at the end of the URL

### Expected result (*)

1. No code bug
Do not preselect anything because there are no parameters in hash.

Example from Magento 2 with sample data:
/stellar-solar-jacket.html#color=5477
This should preselect swatch blue.
But this:
/#
should not preselect anything. And I mean do not send empty attributes and values further in code.

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/ConfigurableProduct/view/frontend/web/js/configurable.js

```
  _overrideDefaults: function () {
            var hashIndex = window.location.href.indexOf('#');

            if (hashIndex !== -1) {
                this._parseQueryParams(window.location.href.substr(hashIndex + 1));
            }

            if (this.options.spConfig.inputsInitialized) {
                this._setValuesByAttribute();
            }

            this._setInitialOptionsLabels();
        },
```

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Swatches/view/base/web/js/swatch-renderer.js

```
_getSelectedAttributes: function () {
            var hashIndex = window.location.href.indexOf('#'),
                selectedAttributes = {},
                params;

            if (hashIndex !== -1) {
                params = $.parseQuery(window.location.href.substr(hashIndex + 1));

                selectedAttributes = _.invert(_.mapObject(_.invert(params), function (attributeId) {
                    var attribute = this.options.jsonConfig.mappedAttributes[attributeId];

                    return attribute ? attribute.code : attributeId;
                }.bind(this)));
            }

            return selectedAttributes;
        },
```

### Actual result (*)

1.  
Empty hash in URL is transformed in pre-selected attributes: {'': '', '': '', ...}

The condition:
```
 if (hashIndex !== -1) {
```
is not enough, hash should be tested if is not empty.
Hash string should be tested something like:
```
if (!_.isEmpty(window.location.hash)) {
    ... preselect super attributes
}
```

**Comment by shikhamis11** [comment] 2020-04-04 09:59
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-04 09:59
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-04 10:00
Hi @shikhamis11, here is your [Magento instance](https://i-27569-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27569-2-4-develop.instances.magento-community.engineering/admin_c199](https://i-27569-2-4-develop.instances.magento-community.engineering/admin_c199)
Login: `8706ff17` Password: `9ea1e040b61f`
Instance will be terminated in up to 3 hours.

**Comment by daniel-ifrim** [comment] 2020-04-04 10:03
Hi @shikhamis11 
I think the issue can be tested in code with debugging. I do not know a way to see it visually on product page. Unless you have access to write code on https://i-27569-2-4-develop.instances.magento-community.engineering server,
Thank you

**Comment by shikhamis11** [comment] 2020-04-04 10:38
hi @daniel-ifrim 
Thank you for reporting this issue .. I got your query .. there can be additonal check with along with `hashIndex` to avoid code check incase of empty hash string

**Comment by magento-engcom-team** [comment] 2020-04-04 10:39
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33089` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by srsathish92** [comment] 2020-08-28 17:57
@VladimirZaets @sdzhepa This issue is not reproducible in 2.4-develop. can you please check from your end?

**Comment by sdzhepa** [comment] 2020-08-31 19:04
Hello @srsathish92 

Thank you for the update. Seems it was already fixed in some other pr
Closed as cannot reproduce

**Closed as completed by sdzhepa** 2020-08-31 19:04 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Issue:  Cannot Reproduce, Issue: Format is valid, Component: ConfigurableProduct, Triage: Dev.Experience, Reproduced on 2.4.x, Event: Global-Contribution-Day, Priority: P3, Severity: S2, Triage: Done, Progress: done, Reported on 2.3.4
