### ISSUE TITLE
Invalid field(s) above the fold during checkout.

### ISSUE THREAD

**Issue by jarhody** [magento/magento2#8977] opened 2017-03-22 18:08 UTC
### Preconditions
1. Version 2.1.5 
2. PHP 5.6

### Steps to reproduce
1. Add any item to cart
2. Go to checkout fill out form leaving out any required field like last name or city (or in my case my browser auto fills an invalid email address which does not trigger an immediate notice)
3. Scroll down to shipping methods
4. Select shipping method
5. Click Next

### Expected result
1. A notice should appear within the users viewport or take the user to the error point on the page

### Actual result
1. Nothing occurs within the users viewport. The notice is only above the fold and requires the to scroll or abandon cart :(

**Shipping Step**
![shipping_next](https://cloud.githubusercontent.com/assets/18600324/24213152/e33b4cf4-0f07-11e7-94f0-7b1397d43fd4.png)
**Above the Fold**
![error_above_viewport](https://cloud.githubusercontent.com/assets/18600324/24213159/e7b2ae80-0f07-11e7-902e-10cfed05845c.png)

With auto fill programs and browsers becoming more popular (and not always perfect as in my case with the email field) this behavior will lead to more abandon carts and user frustration.

**Comment by magento-engcom-team** [comment] 2017-10-01 09:30
@jarhody, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-01 09:30 UTC
Labels: Component: Checkout, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by speedupmate** [comment] 2018-02-18 15:08
@magento-engcom-team actually this should be reopened, as focusInvalid is implemented for only shipping address form but it needs to be implemented to all validation errors on checkout page (billing address ,agreements, etc)  

right now same issue happens with entering different billing address
