### ISSUE TITLE
[Magento 2.2.6] Order is marked as "Suspected Fraud", wrong charge amount after currency conversion

### ISSUE THREAD

**Issue by matejevic** [magento/magento2#24364] opened 2019-08-29 17:32 UTC
### Preconditions (*)

Magento 2.2.6

### Steps to reproduce (*)
Place an order by a customer in Australia in AUD.

### Expected result (*)

It should charge the customer £171.50 GBP.

### Actual result (*)

We've received an order from a customer in Australia. The order came to AU$310.43, which works out to be £171.50 GBP. Magento seems to calculate the amounts correctly until it collects the money from the customer when it has converted it back to GBP, i.e. we charged the customer £310.43 GBP.

Here is a screenshot from Magento showing the Order Notes. I also see it's been marked as suspected fraud, which I assume is due to the amounts being different to what we were expecting.

![Pasted File at August 28, 2019 10_50 AM](https://user-images.githubusercontent.com/54681943/63962805-284d4a00-cac6-11e9-9306-288cd3795f9d.png)

**Comment by matejevic** [comment] 2019-08-29 17:35
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-08-29 17:35
Hi @matejevic. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-08-29 17:36
Hi @matejevic, here is your [Magento instance](https://i-24364-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24364-2-3-develop.instances.magento-community.engineering/admin](https://i-24364-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment] 2019-08-30 07:31
Hello @matejevic 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and
> Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.

 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by engcom-Charlie** 2019-08-30 07:31 UTC
Labels: Issue: Format is valid

**Comment by Usuario001** [comment] 2019-08-30 17:37
@magento give me 2.2.6-develop instance

**Comment by magento-engcom-team** [comment] 2019-08-30 17:37
Hi @Usuario001. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` release line

**Comment by Usuario001** [comment] 2019-08-30 17:38
@magento give me instance
