### ISSUE TITLE
Anchor category behavior with filtering navigation not working properly

### ISSUE THREAD

**Issue by df2k2** [magento/magento2#37344] opened 2023-04-06 15:32 UTC
### Preconditions and environment

- Tested with Magento 2.4.6 and Adobe Commerce 2.4.6
- Tested with Luma theme and with custom child theme inheriting Luma

### Steps to reproduce

To Reproduce:

**Step 1.** Create a Main category and two child categories:

![image](https://user-images.githubusercontent.com/4868368/230422536-ac2cc73d-8df5-4068-9126-52ea832c575f.png)

**Step 2.** Create a product and place it in one of the child categories.

**Step 3.** Clear cache and view the main category with "Anchor" set to **Yes**

The filtering navigation is missing from the left side, but the product is showing, as expected, in the list

![image](https://user-images.githubusercontent.com/4868368/230425932-cb771dc0-7ff0-40ee-ae0c-e3a1c3f56066.png)

**Step 4.** Update the 'Anchor' of the main category -- Set it to **No**

![image](https://user-images.githubusercontent.com/4868368/230424914-472ed1a4-d98a-4776-827b-ab5357f5bbf4.png)

**Step 5.** Clear cache and view the main category again

The filtering navigation incorrectly now shows up.  The products of child categories are not listed, as expected with anchor turned off.

![image](https://user-images.githubusercontent.com/4868368/230426300-7c3b6639-a25b-4133-896b-74e5453ae44c.png)

### Expected result

When anchor turned on, filtering navigation should show.

When anchor turned off, filtering navigation should not show.

-----

**Per documentation:**  https://experienceleague.adobe.com/docs/commerce-admin/catalog/categories/create/categories-display-settings.html?lang=en

> **Anchor** | When set to Yes, includes the filter by attribute section in the layered navigation. Options: Yes / No

### Actual result

When anchor turned on, filtering navigation is missing.

When anchor turned off, filtering navigation shows.  It even shows on single column layout, and other layouts, such as CMS page.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by df2k2** [comment] 2023-04-07 15:35
@magento give me 2.4-develop instance

**Comment by df2k2** [comment] 2023-04-07 16:25
Unable to reproduce the issue here.  I've reproduced it twice on 2.4.6 without installation of sample data.

**Comment by engcom-Bravo** [comment] 2023-04-12 14:27
Hi @df2k2,


Thanks for your update.

Verified the issue on Magento 2.4-develop instance and Magento 2.4.6 instance and the issue is not reproducible.Kindly refer the screenshots.

When we set to Anchor to yes.it will include attributes in the layered navigation as per magento documentation.


<img width="1224" alt="Screenshot 2023-04-11 at 3 11 47 PM" src="https://user-images.githubusercontent.com/51680745/231469439-42e6d4e8-9bd5-4b42-9484-22981fbd54a5.png">


When we set to Anchor to No.It will not include attributes in layered navigation as per magento documentation.**Shop By Category** is not a attribute.Anchor is regarding to include and exclude attributes in layered navigation.


<img width="1200" alt="Screenshot 2023-04-12 at 6 39 21 PM" src="https://user-images.githubusercontent.com/51680745/231470155-ddabd6df-ef38-4175-bf0a-550e16cfe432.png">




Kindly let us know if you are still facing any issue.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-04-26 06:05
Hi @df2k2,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-04-26 06:05 UTC
Labels: Issue: needs update, Reported on 2.4.6
