### ISSUE TITLE
Poor loading times on "first called pages"

### ISSUE THREAD

**Issue by ci2014** [magento/magento2#2731] opened 2015-12-16 09:36 UTC
Hello everyone,

I am experiencing poor loading times, usually 1-3 seconds, but also up to 25 seconds, with my magento 2 instance, when a page was not called before. 

When i watch 'top', I can see, that the process is going up to 99 percent of CPU usage and shrinks down, when the page itself is loaded.

This seems to be a problem with the cache, because pages, which were called before, load immediately. I don't know about the possibilities to warm up the cache on CLI. I already used setup:static-content-deploy successfully.

The user rights are well configured.

I need to mention, that I don't use varnish. APCu and memcached are installed. I am using the latest Plesk Server, CentOS 6 and PHP 5.6.16.

I also don't want the shop to process the less files every time. Magento is in production mode and server-side less compilation is enabled. Please ignore this, if this is correct.

Thank you in advance.

Kind regards

Chris

**Comment by ahmadhattab** [comment] 2015-12-16 09:52
Could you please enable the magento log and share it with us ...

**Comment by okobchenko** [comment] 2015-12-16 09:55
Hi, Chris.

Thank you for your question. In general issue or mis-configuration can be easily identified by response time:
- Catalog with Page Cache will respond in 50-150ms
- Catalog page without Page Cache (or in case it is not warmed up for certain page) lead to 400-1500ms depending on the page and environment
- Catalog page without any cache activated or warned will respond in 2-4 seconds
- In case of real time static content processing (themes fallback, less compilation, other deploy procedures) time can jump up to 20-30seconds

Please check that after deploying of static content you set correct mode MAGE_MODE production in your htaccess file (for apache) or nginx.conf (for nginx) as well as check permissions for pub directory (as deployed files can be just unavailable) as well as for var directory (so you are sure cache files are available)

**Comment by ci2014** [comment] 2015-12-16 17:54
Thank you both for your replies.

@ahmadhattab Which log may I share with you. I know there are different log files in the var/log folder.
@okobchenko The pages, which are taking too long to load are mostly product pages. The catalog pages load faster than most product pages.

In my .htaccess file SetEnv MAGE_MODE xyz is commented out.

php bin/magento deploy:mode:show returns Current application mode: production

I have set the pub and var directory world readable for debugging this issue, but the problem stills exists.

By the way (might be important): Why does setting "Workflow type" (which is "Not available in production mode") to "Client Side less compilation" writing 'rel="stylesheet/less"' and the script tag for less.min.js and its config file into magentos source code? Workflow type is not available in production mode, so this should not happen.

Of course setting it to "Server Side less compilation" removes those, but in production mode, this option should do absolutely nothing. This might be an indicator for something being wrong with the production mode.

Thank you all in advance.

**Comment by okobchenko** [comment] 2015-12-17 11:24
I believe there is a mix of developer workflow tools and attempts to switch everything to production mode. 

In order to switch M2 into most performant mode (also called "production", but not limited just by setting environment variable in htaccess or nginx.conf file) next steps should be done:
- Activating of client side performance features (is not the reason of slow server response, but recommended)
1. JS bundling
2. JS minification
3. CSS minification
4. HTML minification
- Running static content deployment tool (to avoid real time less compilation, themes fallback, etc)

`php bin/magento setup:static-content:deploy`
- Running code compiler (to avoid real time configuration and code analysis)

`php bin/magento setup:di:compile`
- Setting production mode

Set $MAGE_MODE production (nginx)
SetEnv MAGE_MODE production (apache)
- Performing re-index of catalog

`php bin/magento indexer:reindex`
- Cleaning cache to apply all settings

`php bin/magento cache:clean`
`php bin/magento cache:flush`

Please try this flow on your Magento instance, it should help.

**Comment by ci2014** [comment] 2015-12-18 17:20
@okobchenko 

Thank you for your advice. That steps are important for setting M2 into production mode.

I already ran those commands successfully.

It did not help. I still see following in my source code, which I believe is a part of the problem:

``` javascript
<link  rel="stylesheet/less" type="text/css"  media="all" href="http://magento/pub/static/version1450286045/frontend/Magento/luma/de_DE/mage/calendar.css" />
<link  rel="stylesheet/less" type="text/css"  media="all" href="http://magento/pub/static/version1450286045/frontend/Magento/luma/de_DE/css/styles-m.css" />
<link  rel="stylesheet/less" type="text/css"  media="screen and (min-width: 768px)" href="http://magento/pub/static/version1450286045/frontend/Magento/luma/de_DE/css/styles-l.css" />
<link  rel="stylesheet/less" type="text/css"  media="print" href="http://magento/pub/static/version1450286045/frontend/Magento/luma/de_DE/css/print.css" />
<link  rel="icon" type="image/x-icon" href="http://magento/pub/static/version1450286045/frontend/Magento/luma/de_DE/Magento_Theme/favicon.ico" />
<link  rel="shortcut icon" type="image/x-icon" href="http://magento/pub/static/version1450286045/frontend/Magento/luma/de_DE/Magento_Theme/favicon.ico" />
<script src="http://magento/pub/static/version1450286045/frontend/Magento/luma/de_DE/less/config.less.js"></script>
<script src="http://magento/pub/static/version1450286045/frontend/Magento/luma/de_DE/less/less.min.js"></script>
```

So, when I see those less entries, there still has to be a problem with the production mode.

**Comment by eug123** [comment] 2015-12-21 12:11
Hi,
Seems "browser compilation mode" still active.
Please try the following:
- make sure "Front-end development workflow" is set to "server side less compilation"
- Remove all /var/ folder contents
- Remove all /pub/static/ folder contents
- run `php bin/magento setup:static-content:deploy`

**Comment by ci2014** [comment] 2015-12-29 21:25
Hi,

after all that work, still clicking some pages the first time, the CPU usage of apache goes up to 98.2 percent. I have tested it on several instances and the problem occurs on all of them.

The servers are t2.large instances on amazon ec2, so they are powerful enough to perform magento 2.

Edit: The Magento user is shop, and the web server group is apache.

Some folders are created as apache:apache

drwxrwx--- 3 apache apache 4096 29. Dez 21:46 frontend
drwxrwx--- 3 apache apache 4096 29. Dez 21:46 _requirejs

The other ones are as follows:
-rw-rw-r-- 1 shop apache 1104 28. Dez 18:02 cron.php
drwxrwsr-x 3 shop apache 4096 28. Dez 18:02 errors
-rw-rw-r-- 1 shop apache 2834 28. Dez 18:02 get.php
-rw-rw-r-- 1 shop apache 1240 28. Dez 18:02 index.php
drwxrwsr-x 9 shop apache 4096 28. Dez 19:46 media
drwxrwsr-x 3 shop apache 4096 28. Dez 18:02 opt
drwxr-x--- 4 shop apache 4096 29. Dez 21:46 static
-rw-rw-r-- 1 shop apache  429 28. Dez 18:02 static.php

Is this correct?

#groups shop
shop : shop apache

#groups apache
apache : apache shop

**Comment by nikolaevas** [comment] 2016-04-17 12:42
Hi there,

I have the similar problem. I'm trying to create new theme. But every time I reload the home page it is going to high CPU loading. 

My Settings:
New theme has just one file: 
_/app/design/frontend/Test/default/web/css/source/_extend.less_
Magento mode: **developer**
Front-end development workflow: **Server-side less compilation**
**Grunt is installed and configured**. 

Activity monitor:

<img width="794" alt="screen shot 2016-04-17 at 13 42 56" src="https://cloud.githubusercontent.com/assets/2813477/14586946/1cf0acf8-04b1-11e6-9367-ffcf2f20d59b.png">

Chrome console:

<img width="601" alt="screen shot 2016-04-17 at 14 30 27" src="https://cloud.githubusercontent.com/assets/2813477/14586950/2f089d10-04b1-11e6-98be-7ad462f9dec4.png">

And only after `php bin/magento setup:static-content:deploy` the page is loading fast:

Chrome console:

<img width="535" alt="screen shot 2016-04-17 at 14 31 32" src="https://cloud.githubusercontent.com/assets/2813477/14586972/9a3ba032-04b1-11e6-93d5-c0b4bfba2561.png">

Do I need to deploy static content every time I change some css style if I develop new theme?

Thanks!

**Comment by ghost** [comment] 2016-08-30 17:24
Hello All,

I have same issues ,and finding solution since last few days but not getting what's an issues.

@ci2014 you find solution let me know .

I had tried  all possible solution as give by above.

Thanks !

**Comment by veloraven** [comment] 2016-11-02 08:19
I'm closing this issue as  GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you think it to be an issue which requires fix please create new GitHub issue following the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. Please, also identify which version of Magento you are running.

**Closed as completed by veloraven** 2016-11-02 08:19 UTC
