### ISSUE TITLE
CLI application does not have all the plugins for CMS Page Save and Delete

### ISSUE THREAD

**Issue by dmanners** [magento/magento2#8045] opened 2017-01-05 07:48 UTC
### Preconditions

1. Magento: 2.1.2
2. PHP: 5.6.23|7.0.x

### Steps to reproduce

1. Create a bin script that uses `new \Magento\Framework\Console\Cli();`
2. Use the `\Magento\Cms\Api\Data\PageInterfaceFactory` to create a cms page
3. Supply only the required (in the admin) field "title"
4. Save the page

### Expected result

1. I expect that just like the admin if no identifier is supplied that the plugin `cms_url_rewrite_plugin` from `vendor/magento/module-cms-url-rewrite` should create the identifier

### Actual result

1. Exception is thrown as call to `isValidPageIdentifier` fails in `vendor/magento/module-cms/Model/ResourceModel/Page.php::_beforeSave`

The reason for this is the plugin is only defined in the adminhtml section. Maybe this is a desired feature/behavior but for me it seems a bit silly that a required field as defined and shown in the admin does not match the required field settings using in the cli.

**Comment by magento-engcom-team** [comment] 2017-10-09 13:30
@dmanners, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Closed as completed** 2017-12-11 15:33 UTC
Labels: bug report, Component: Cms, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Fixed in 2.3.x, Issue: Format is valid
