### ISSUE TITLE
Visual Merchandiser - Cannot unassign all products from a category

### ISSUE THREAD

**Issue by shafeekb** [magento/magento2#36128] opened 2022-09-11 11:12 UTC
### Preconditions and environment

- Magento Commerce cloud version 2.4.3-p1 

### Steps to reproduce

1. Within the Magento Admin Navigate to CATALOG -> Categories
2. Navigate to a category with products
3. Open the Products in Category section
4. Unassign all the products one by one

### Expected result

All products removed from that category

### Actual result

When try to remove the last product all removed products restoring.

### Additional information

Please refer the below video

https://www.dropbox.com/s/hw37x1bm5n74xnw/Screen%20Recording%202022-09-11%20at%204.34.03%20PM.mov?dl=0

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-09-14 10:15
@magento give me 2.4-develop instance with EE

**Comment by engcom-Bravo** [comment] 2022-09-14 10:32
@magento give me 2.4-develop instance 2.4.3-p1 with EE

**Comment by engcom-Bravo** [comment] 2022-09-14 10:34
@magento give me 2.4-develop instance with edition EE

**Comment by engcom-Bravo** [comment] 2022-09-14 10:42
@magento give me 2.4-develop instance with edition ee

**Comment by engcom-Bravo** [comment] 2022-09-14 13:16
Hi @shafeekb1,


Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch with edition ee but could not able to reproduce the issue.Kindly refer the attached videos.



https://user-images.githubusercontent.com/51680745/190163600-565cd986-79ec-48d4-8344-adbaab5ab127.mov




https://user-images.githubusercontent.com/51680745/190163721-8bfd666d-65d9-4667-ab75-0f00ef2cd05d.mov



Steps to reproduce:

1.Within the Magento Admin Navigate to CATALOG -> Categories
2.Navigate to a category with products
3.Open the Products in Category section
4.Unassign all the products one by one





Please Let us Know we miss anything.


Thanks.

**Comment by engcom-Bravo** [comment] 2022-09-16 10:49
@magento give me 2.4.3-p1 instance with edition ee

**Comment by engcom-Bravo** [comment] 2022-09-19 11:36
Hi @shafeekb1,


Thanks for your response.

It is recommended to verify the issues in Magento 2.4 develop instance this is having a latest code base.The issue might have been fixed on 2.4-develop and so issue is not reproducible any more.


Kindly upgrade your Magento instance to Latest version and check the issue is still reproducible.



Let us know you are still facing the issue.


Thanks.

**Comment by engcom-Bravo** [comment] 2022-10-03 06:41
Hi @shafeekb1,


We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-10-03 06:41 UTC
Labels: Issue: needs update, Reported on 2.4.3-p1
