### ISSUE TITLE
Mini cart is not updated - Magento2

### ISSUE THREAD

**Issue by magentoprasad** [magento/magento2#10223] opened 2017-07-12 10:53 UTC
### Preconditions

1. Magento Version 2.1.7
2. 

### Steps to reproduce

1. Custom product shows "product added successfully " but mini cart shows no item message 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by ihor-sviziev** [comment] 2017-07-13 09:00
It looks like it was already fixed in develop & 2.1-develop branches, but didn't released yet.
https://github.com/magento/magento2/pull/10050

**Comment by magento-engcom-team** [comment] 2017-09-28 11:30
@magentoprasad, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Closed as completed by magento-engcom-team** 2017-09-28 11:30 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid
