### ISSUE TITLE
Controller Subscriber Confirm Does Not Load Subscriber via method load($id)

### ISSUE THREAD

**Issue by princefishthrower** [magento/magento2#25439] opened 2019-11-01 21:16 UTC
### Preconditions (*)
1. 2.3.2
2. exactly this line, `load($id)` returns a `null` value, even when passed a valid subscriber ID: https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Newsletter/Controller/Subscriber/Confirm.php#L30

### Steps to reproduce (*)
1. Subscribe a customer programmatically, let's say they are assigned ID 56 and code 56t0fgby1e6v7xqgnpap1wx6jl9rms1q (they exist in table `newsletter_subscriber`)
2. When calling the corresponding frontend link which calls the controller  https://mymagentowebsite.com/newsletter/subscriber/confirm/id/56/code/56t0fgby1e6v7xqgnpap1wx6jl9rms1q/

### Expected result (*)
1. Subscriber should be confirmed

### Actual result (*)
1. the `$subscriber` variable is `null`, because the object isn't loaded or found properly via the `load()` method

I have created my own working version by creating my own `loadById` method, based off the standard `loadByEmail` in `Magento\Newsletter\Model\ResourceModel\Subscriber` (loadByEmail works as expected, but in my context I need to load by subscriber ID) 

That looks like this:

```php
class Subscriber extends \Magento\Newsletter\Model\ResourceModel\Subscriber
{
    public function __construct(\Magento\Framework\Model\ResourceModel\Db\Context $context, \Magento\Framework\Stdlib\DateTime\DateTime $date, \Magento\Framework\Math\Random $mathRandom, $connectionName = null)
    {
        parent::__construct($context, $date, $mathRandom, $connectionName);
    }

    /**
     * Load subscriber from DB by ID
     *
     * @param int $subscriberId
     * @return array
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function loadById(int $subscriberId)
    {
        $select = $this->connection->select()->from($this->getMainTable())->where('subscriber_id=:subscriber_id');

        $result = $this->connection->fetchRow($select, ['subscriber_id' => $subscriberId]);

        if (!$result) {
            return [];
        }

        return $result;
    }
}
```

And that needs to be called by the Subscriber class (I created my own Subscriber class which extends the core:)

```php
class Subscriber extends \Magento\Newsletter\Model\Subscriber
{
    public function __construct(\Magento\Framework\Model\Context $context, \Magento\Framework\Registry $registry, \Magento\Newsletter\Helper\Data $newsletterData, \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig, \Magento\Framework\Mail\Template\TransportBuilder $transportBuilder, \Magento\Store\Model\StoreManagerInterface $storeManager, \Magento\Customer\Model\Session $customerSession, CustomerRepositoryInterface $customerRepository, AccountManagementInterface $customerAccountManagement, \Magento\Framework\Translate\Inline\StateInterface $inlineTranslation, \Magento\Framework\Model\ResourceModel\AbstractResource $resource = null, \Magento\Framework\Data\Collection\AbstractDb $resourceCollection = null, array $data = [], DateTime $dateTime = null)
    {
        parent::__construct($context, $registry, $newsletterData, $scopeConfig, $transportBuilder, $storeManager, $customerSession, $customerRepository, $customerAccountManagement, $inlineTranslation, $resource, $resourceCollection, $data, $dateTime);
    }

    /**
     * Load subscriber data from resource model by id
     *
     * @param string $subscriberId
     * @return \Magento\Newsletter\Model\Subscriber
     */
    public function loadById($subscriberId)
    {
        $this->addData($this->getResource()->loadById($subscriberId));
        return $this;
    }
}
```

and that works!

If this `load($id)` bug is confirmed on a clean install, I can gladly incorporate these updates into core 👍

**Comment by princefishthrower** [comment] 2019-11-01 21:18
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-01 21:18
Hi @princefishthrower. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-01 21:18
Hi @princefishthrower, here is your [Magento instance](https://i-25439-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25439-2-3-develop.instances.magento-community.engineering/admin](https://i-25439-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by princefishthrower** [comment] 2019-11-01 21:31
Doesn't seem like any email functionality works with these types of instances - and I also don't know how to access the database here - so the only proof I have that this bug is occuring is with our instance.

I can check on a separate clean install I have, but that is on another machine and will take me some more time

**Comment by shikhamis11** [comment] 2019-11-02 18:21
Hello @princefishthrower 
I checked the issue at latest magento instance and not able to reproduce it. 
I got the object with my subscriber id while calling controller `newsletter/subscriber/confirm`
can you cross check it again at latest magento 2 version and also please verify that the Id passed in the url `newsletter/subscriber/confirm/id/56/code/56t0fgby1e6v7xqgnpap1wx6jl9rms1q/` must be `subscriber_id` in the table `newsletter_subscriber`

**Comment by shikhamis11** [comment] 2019-11-06 18:34
hello @princefishthrower 
I am closing this one as I am not able to reproduce this on latest magento 2 instance . let me know if you are able to reproduce this issue on latest magento 2 instance

**Closed as completed by shikhamis11** 2019-11-06 18:34 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid
