### ISSUE TITLE
Wrong coupon usage handling for cart price rules with shipping discount

### ISSUE THREAD

**Issue by alexnos88** [magento/magento2#6693] opened 2016-09-21 10:05 UTC
When placing an order using coupon code for shipping discount (provided via cart price rules) usage counter doesn't get updated.
### Preconditions
1. Magento 2.1.0
2. Cart Price Rule applicable to some (any) cart
   2.1. Use specific coupon, any coupon code
   2.2. Actions providing only shipping discount
   2.3. Uses per coupon \ customer set to some value > 0
### Steps to reproduce
1. Add some product to cart,
2. Checkout using coupon code from the rule you've created
### Expected result
1. Coupon usage counter increments
### Actual result
1. Coupon usage counter doesn't increment
### Clue

Since 2.1.0 there is extra condition in

> Magento\SalesRule\Observer\SalesOrderAfterPlaceObserver : 60

``` php
    if (!$order || $order->getDiscountAmount() == 0) {
        return $this;
    }
```

Which in previous versions was simpler: `if (!$order)`

When a rule provide only a shipping discount, getDiscountAmount() returns 0, and the script execution ends.

Proposed variant is the following:

``` php
    if (!$order || !$order->getAppliedRuleIds()) {
        return $this;
    }
```

In such way script will continue execution, and usage counters will get updated.

Please consider implementing this fix in the upcoming patches.

**Comment by danslo** [comment] 2016-09-21 11:04
Duplicate of https://github.com/magento/magento2/issues/5450.

**Comment by danslo** [comment] 2016-09-21 11:07
Actually, also duplicate of https://github.com/magento/magento2/issues/5171 and https://github.com/magento/magento2/issues/3506.

**Comment by pboisvert** [comment] 2016-09-21 15:32
thanks @danslo for spotting the duplicates  closing as a duplicate of #3506

**Closed as completed by pboisvert** 2016-09-21 15:32 UTC
