### ISSUE TITLE
Getting payment child transactions by type never matches if conditions

### ISSUE THREAD

**Issue by anttiranta** [magento/magento2#23000] opened 2019-05-23 20:07 UTC
### Preconditions (*)

1. Create an instance of a payment transaction and child transaction for the first one. See that both transactions have a type. 
2. Save created transactions to database. 

### Steps to reproduce (*)

1. Load parent transaction from database. 
2. For parent transaction instance, call \Magento\Sales\Model\Order\Payment\Transaction method getChildTransactions() with types parameter being set (has to be same type as child's type).

### Expected result (*)

1. Method getChildTransactions() should return child transactions matching the type parameter. 

### Actual result (*)

1. Empty array gets returned. Maybe because code is calling getType() instead of getTxnType() in condition which checks if type matches.

**Comment by magento-engcom-team** [comment] 2019-09-16 22:36
Hi @anttiranta. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-16923` was closed as `non-reproducible` in `2.3-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Closed as completed by magento-engcom-team** 2019-09-16 22:36 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid
