### ISSUE TITLE
The products are not reindexed after batch (group) moving to another store while indexers mode is «Update on Save»

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2260] opened 2015-11-04 15:36 UTC

**Comment by vzabaznov** [comment] 2016-06-22 12:58
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment] 2016-07-14 08:19
Hi, @mage2pro thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.

**Closed by vzabaznov** 2016-07-14 08:19 UTC
Labels: MX, needs update
