### ISSUE TITLE
Sort by price not working with Elasticsearch 7.x in Magento 2.4.4 Enterprise Edition

### ISSUE THREAD

**Issue by Hermione011** [magento/magento2#35746] opened 2022-07-08 12:28 UTC
### Preconditions and environment

The magento 2.4.4 Enterprise Edition with elastic search is having issues with "Sort by price and Sort by product name" on the PLP page. The sorting is not working when selecting the price and product name.

### Steps to reproduce

1. Install magento 2.4.4 EE with Elastic search
2. Log into admin, navigate to "Store-> Product attributes"
3. Find "price" attribute and set "Use in filter options" to "Yes"
4. Clear cache and browse the PLP page
5. Sort by price or sort by product name

### Expected result

The products should get sorted by price

### Actual result

Product is not sorting accordingly.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2022-07-08 14:49
@magento give me 2.4.4 instance with edition ee

**Comment by ayushi011** [comment] 2022-07-11 05:13
HI @engcom-Delta, Do you find any solution for this?

**Comment by engcom-Delta** [comment] 2022-07-11 10:34
Hi @ayushi011 ,
Thank you for logging an issue and we tried to reproduce the issue on magento 2.4 develop with EE, We could not find proper steps for it , Kindly review step# 2 .

Here is screenshot for reference.

<img width="1440" alt="Screenshot 2022-07-11 at 3 58 11 PM" src="https://user-images.githubusercontent.com/51681379/178245605-268521d6-6231-4ac9-b2c1-3ceb3a490ab6.png">

<img width="1440" alt="Screenshot 2022-07-11 at 3 57 04 PM" src="https://user-images.githubusercontent.com/51681379/178245708-a0420b4c-0ad3-4b17-ae29-916712e14091.png">

Please review the steps provided and help us to replicate it.

Regards,

**Comment by ayushi011** [comment] 2022-07-11 11:15
Hi @engcom-Delta,
1. Click on Stores-> IN Attributes Please select Product 
![image](https://user-images.githubusercontent.com/108935783/178251897-b397f0e5-7945-4f0b-a57e-c5f060ac25f8.png)
2. After opening it, search for attribute price in it
3. In price attribute, open storefront properties and then enable used for sorting in product listing
![image](https://user-images.githubusercontent.com/108935783/178252338-2d25d8a2-0e94-4fd5-b9f3-fea80bca058e.png)
4. Now check on frontend, when you select price the products does not sort.

**Comment by engcom-Delta** [comment] 2022-07-11 13:21
Hi @ayushi011 ,
Need to clarify quick query , Do i need to  sort the products after searching on frontend? or directly i should sort the products on frontend?

in fact , we can only sort the products after searching or  we should go to any category?

Frontend home page looks like:
<img width="1440" alt="Screenshot 2022-07-11 at 6 48 46 PM" src="https://user-images.githubusercontent.com/51681379/178273592-8b557dbb-3de6-4869-83a7-d1541ba80648.png">

**Comment by engcom-Delta** [comment] 2022-07-12 09:58
Hi @ayushi011 ,
Thank you for providing more details. We tried to reproduce the issue on Magento 2.4 develop with EE and observed that after sorting by price , products are disappeared on frontend and products are not getting sorted out by price.

Please find the attached video for reference and screenshots.

<img width="1440" alt="Screenshot 2022-07-11 at 6 32 14 PM" src="https://user-images.githubusercontent.com/51681379/178464072-315c7dbb-338b-4e1a-a54e-dc13e311d00a.png">

**Before sorting by price:**

<img width="1440" alt="Screenshot 2022-07-12 at 3 19 11 PM" src="https://user-images.githubusercontent.com/51681379/178464190-0bcfcb2f-190a-485d-b72e-df38711bfdd8.png">

Video:
https://www.loom.com/share/e49461fd8e7c46d08bcdc9e60c9709d6

Hence issue has been confimed

**Comment by engcom-Delta** [comment] 2022-07-15 14:15
@magento give me 2.4-develop instance with edition ee

**Comment by engcom-Delta** [comment] 2022-07-15 14:48
Hi @ayushi011 ,
We tried on cloud instance , issue is not reproducible , it works as expected.
please find the attached reference video.

https://www.loom.com/share/7f31e6096fbb4852a6aa5037d2f202ec

**Comment by engcom-Delta** [comment] 2022-07-15 14:50
@magento give me 2.4.4 -develop instance with edition ee

**Comment by engcom-Dash** [comment] 2022-07-18 10:40
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment] 2022-07-28 13:15
Hi @ayushi011 ,
We have tried once again on Magento 2.4.4 EE on local , found that issue is not reproducible.
Here is attached reference.

https://www.loom.com/share/d971f911913141028a3e69c8417766b2

Kindly review and suggest us if we can close this issue.

**Comment by kilis** [comment] 2022-08-03 12:35
Hey! What is the fix for this?
We have the same issue.
Thanks!

**Comment by engcom-Hotel** [comment] 2022-08-08 05:05
@magento give me 2.4.4 instance with edition ee

**Comment by engcom-Hotel** [comment] 2022-08-08 05:08
@magento give me 2.4.4 instance

**Comment by slavvka** [comment] 2022-08-08 17:05
@magento give me 2.4.4 instance

**Comment by engcom-Delta** [comment] 2022-08-08 23:25
Hi @ayushi011 ,
We have tried to reproduce the issue on 2.4 develop (CE) and 2.4.4 EE  issue is not reproducible.
Could you please review the provided steps and pre-condition?

Thanks,

**Comment by engcom-Delta** [comment] 2022-08-22 11:59
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Closed as completed by engcom-Delta** 2022-08-22 11:59 UTC
Labels: Progress: PR Created, Progress: done, Issue: needs update, Reported on 2.4.4

**Comment by rohitkumawat17** [comment] 2022-12-01 19:59
Hi, 
I am facing the same issue in Magento 2.4.5 EE. Price sorting is not working. Any solution?

**Comment by ayushi011** [comment] 2022-12-02 11:14
Hi @rohitkumawat17 ,

KIndly check the below module. I have solved the sorting issue using this.
[CustomProductSorting.zip](https://github.com/magento/magento2/files/10140581/CustomProductSorting.zip)

**Comment by rohitkumawat17** [comment] 2022-12-02 17:34
@ayushi011 Thanks for your help. It's working now.

**Comment by rohitkumawat17** [comment] 2022-12-20 13:14
@ayushi011  Do you have any solution for best-selling sorting?

**Comment by nickrwt7** [comment] 2023-09-05 16:56
@ayushi011 @rohitkumawat17 We are facing the same issue, do you have any solution for this ?

**Comment by ayushi011** [comment] 2023-09-06 05:21
Hi @nickrwt7 please upgrade your magento version to latest and then check
