### ISSUE TITLE
Magento 2.1.3 Shipping Method not loading

### ISSUE THREAD

**Issue by dapdx** [magento/magento2#8156] opened 2017-01-16 18:16 UTC
So frustrated with Magento 2. Get things working, upgrade, nothing works.

Ok, so upgraded from 2.1.2, to 2.1.3 and now I'm having issues with both the mini-cart and shipping methods loading on checkout. The mini cart was not showing new items added to it, but if you went the direct cart URL the items were there, it showed "no items in cart" on the mini cart. I somehow fixed this by disabling page caching. 

The shipping methods I haven't figured out. When a customer adds items to the cart, goes to checkout, adds in their address, the shipping methods section has the loading spinning wheel gif playing and nothing ever shows up.

Some script errors are listed below that I think are causing this.

### Preconditions
1. Magento 2.1.3, upgraded from 2.1.2 via the admin auto upgrade thingy.
2. PHP 7 or something

### Steps to reproduce
1. add item to card
2. go to checkout
3. see shipping area on checkout page, loading gif is cycling, no shipping options show up. I'm using table rate shipping.

### Expected result
1. Table rate shipping option should show up, like it did before 2.1.3

### Actual result
1. loading gif cycles, no rates are loaded

In my google chrome debugger thingy I'm getting some Java script errors probably relating to this.

First one is:
"JQMIGRATE: jQuery.browser is deprecated
migrateWarn @ jquery-migrate.js:41
jquery-migrate.js:43 console.trace
migrateWarn @ jquery-migrate.js:43"

Second one is:
"Failed to load resource: the server responded with a status of 500 (Internal Server Error)
(index):1 Uncaught SyntaxError: Unexpected token { in JSON at position 222
    at JSON.parse (<anonymous>)
    at Object.process (error-processor.js:19)
    at Object.<anonymous> (new-address.js:65)
    at fire (jquery.js:3099)
    at Object.fireWith [as rejectWith] (jquery.js:3211)
    at done (jquery.js:9312)
    at XMLHttpRequest.callback (jquery.js:9720)
http://store.eelriverbrewing.com/rest/eelriver/V1/guest-carts/d9c1091097e7e08627d5385e686b3afd/estimate-shipping-methods Failed to load resource: the server responded with a status of 500 (Internal Server Error)
(index):1 Uncaught SyntaxError: Unexpected token { in JSON at position 222
    at JSON.parse (<anonymous>)
    at Object.process (error-processor.js:19)
    at Object.<anonymous> (new-address.js:65)
    at fire (jquery.js:3099)
    at Object.fireWith [as rejectWith] (jquery.js:3211)
    at done (jquery.js:9312)
    at XMLHttpRequest.callback (jquery.js:9720)"

Any idea what's causing these?

**Comment by dapdx** [comment] 2017-01-17 17:17
No ideas? Seems pretty dead here, did everyone else give up on Magento 2 as well? I think I'm there as well. Back to Magento 1.

**Comment by veloraven** [comment] 2017-01-19 13:37
I'm closing this issue as a duplicate of #7830 and #7840.
If you are looking for discussion please  refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site.

**Closed as completed by veloraven** 2017-01-19 13:37 UTC
