### ISSUE TITLE
After Upgrade from 2.4.2 to 2.4.5 products won't show on category pages

### ISSUE THREAD

**Issue by tarekfellah** [magento/magento2#36608] opened 2022-12-14 14:10 UTC
### Preconditions and environment

- Magento version 2.4.5
- Upgrade from Magento 2.4.2 to 2.4.5

### Steps to reproduce

1. Upgrade Magento from 2.4.2 to 2.4.5
2. ElasticSearch version 7.6.1

### Expected result

The products are showing on the category's pages

### Actual result

Products are not showing on category's pages

### Additional information

PHP 8.1
MYSQL 8.0
CPanel 106.0.11
ElasticSearch 7.6.1
Centos 7.9

Is ElsaticSearch should be updated and the cause of the issue?

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-12-15 07:35
Hi @tarekfellah ,
Thank you for reporting and collaboration. Verified the issue by upgrading from Magento 2.4.2 to 2.4.5 Project-community-edition as per [upgrade guide](https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/implementation/perform-upgrade.html) and [system requirements](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html) but the issue is not reproducible at our end with provided information.
Products are shown on category pages as expected. Kindly check if the issue occurred due to any 3rd party extensions / modules enabled and Magento system requirements compatible for specific Magento version. Elaborate the steps / error logs / configuration details if you are still facing any issues.
Thank you.

**Comment by tarekfellah** [comment] 2022-12-15 14:05
@engcom-November Thanks for your reply, it can be ElasticSearch the cause? cause i'm not using a compatible ElastSearch version

**Comment by engcom-November** [comment] 2022-12-16 11:05
Hi @tarekfellah ,
Thank you for the response. Compatible elastic search version for Magento 2.4.5 is 7.17. Its recommended to use the compatible elastic search version. Also, kindly check the below possible solutions that may help resolve the issue.
After the successful upgrade as per Magento [devdocs](https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/implementation/perform-upgrade.html), do a static content deploy followed by re-indexing and cache flush, set the file ownership and permissions as per Magento [devdocs](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/prerequisites/file-system/configure-permissions.html?lang=en). Elaborate the steps / error logs / configuration details if you are still facing any issues.
Thank you.

**Comment by tarekfellah** [comment] 2022-12-16 15:23
@engcom-November 
I did what you suggested and still have the issue, did you see similar issues and how they were fixed

**Comment by engcom-November** [comment] 2022-12-19 13:44
Hi @tarekfellah ,
Issue is not reproducible at our end with the provided information. Can you also please check below possible cases that may help resolve the issue.
1. Switching to default Luma theme to see if it was a theme bug
2. Disable 3rd party extensions / modules enabled if any.
3. Check the products visibility - should be set to catalog, search.
4. Inventory sources / stocks assigned with quantity and stock status.
5. Product assigned to category if searching from Catalog Search results page. Access the page by /catalog/product/view/id/{product_id}
6. Check if product assigned to attribute set 
7. Child products of Configurable or Bundle products if any are setup and purchasable as well.
8. Product is assigned to the website properly.
9. Check Allow All Products per Page by going to Stores > Settings > Configuration > Catalog > Catalog
Set Allow All Products per Page to No followed by setup:di:compile, static content deploy, reindex, cache:flush and set permissions.

Kindly elaborate steps to reproduce / missing configuration details / 3rd party packages enabled if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-12-20 13:16
Hi @tarekfellah ,
As mentioned in the [comment](https://github.com/magento/magento2/issues/36608#issuecomment-1354562589) Its recommended to use the compatible elastic search version. Kindly check the Magento system [requirements](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html) for compatible required versions of softwares. Elaborate steps / logs / configuration details if the issue is still reproducible.
Thank you.

**Comment by tarekfellah** [comment] 2022-12-23 12:09
The production website on Magento 2.4 (not yet upgraded to 2.4.5) got the same error, and after reindex the products are showing again, it can be ElasticSearch issue?

**Comment by engcom-November** [comment] 2022-12-27 03:39
Hi @tarekfellah ,
In Magento 2 reindex is required / mandatory for these indexers when any changes are made. 
Design Config Grid
Customer Grid
Category Products
Product Categories
Catalog Rule Product
Product EAV index
Product Price
Catalog Product Rule
Stock index
Catalog Search 
Magento by default recommends UPDATE BY SCHEDULE" option in production environment hence by setting the cron, indexeres will run automatically on a specific time when your cron gets run and executed   However you can also set reindexing on Updated on Save - so whenever you will update anything on the catalog so on click on save it will run indexing automatically.
Thank you.

**Comment by engcom-November** [comment] 2023-01-09 04:05
Hi @tarekfellah ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2023-01-09 04:05 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.5

**Comment by tarekfellah** [comment] 2023-01-10 20:27
I finally found the cause, it's the stock management, i disabled it from Stores > Configuration > Catalog > Inventory 
if you use the stock management, check the stock status on the product configuration
