### ISSUE TITLE
Image optimization parameters nginx configuration causes 404 on placeholders

### ISSUE THREAD

**Issue by indykoning** [magento/magento2#33313] opened 2021-06-21 13:37 UTC
Enabling the new image optimization parameters in the nginx config causes the placeholder images to reach get.php and then 404.

### Preconditions (*)

1. 2.4.2
2. 2.4.2-p1

### Steps to reproduce (*)

1. Add the new nginx rules as described in https://github.com/magento/magento2/commit/640cad53009b291334234ccd61ab79f256b43da2#diff-157d2bc558ce473e66e013bb30759e55fe32bc9277626ec1f70bb60bb558296fR144
2. Change the catalog_media_url_format to image_optimization_parameters in Magento
3. Attempt to load in a product placeholder

### Expected result (*)

1. See the default magento 2 placeholder 
![image](https://user-images.githubusercontent.com/15870933/122770800-18f44d80-d2a6-11eb-8400-8e1e8338994c.png)

### Actual result (*)

1. get.php is reached and returns a 404
![image](https://user-images.githubusercontent.com/15870933/122770954-40e3b100-d2a6-11eb-9f01-f3fa31b60844.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment] 2021-06-22 04:26
It's worth to mentioning from more new recently version magento core-team change root folder config to pub!

**Comment by engcom-Hotel** [comment] 2021-06-24 15:05
Hi @indykoning 

We have tried to reproduce this issue in Magento 2.4-develop branch, with your mentioned steps but unable to reproduce the issue. Below are detailed steps we have followed in order to reproduce this issue, please review and let us know if any change required:
1. Setup fresh magento.
2. Create a product with default image (magento placeholder).
3. Uncomment rule in nginx.conf file, as below:

<img width="705" alt="Screenshot 2021-06-24 at 8 27 21 PM" src="https://user-images.githubusercontent.com/51681618/123285519-bd86c180-d52a-11eb-988c-5b45cd9eef32.png">

4. Restart the nginx server.
5. Update "Catalog media URL format" with "Image optimization based on your query parameter", please find below screenshot:

![Configuration-Settings-Stores-Magento-Admin](https://user-images.githubusercontent.com/51681618/123284373-d5117a80-d529-11eb-9852-0fec68500d19.png)

6. Clear the cache.
7. Check the product detail page for product placholder, as below:

![Test-Product](https://user-images.githubusercontent.com/51681618/123286357-7947f100-d52b-11eb-8358-ec54a0ce417c.png)

**Comment by achatpc** [comment] 2021-06-25 07:39
Hello,

Try this:

replace
	private function getOriginalImage(string $resizedImagePath): string {
		return preg_replace('|^.*?((?:/([^/])/([^/])/\2\3)?/?[^/]+$)|', '$1', $resizedImagePath);
	}

with

    private function getOriginalImage(string $resizedImagePath): string
    {
        return preg_replace('|^.*((?:/[^/]+){3})$|', '$1', $resizedImagePath);
    }

vendor/magento/module-media-storage/App/Media.php

**Comment by achatpc** [comment] 2021-06-25 15:09
#33351

**Comment by engcom-Hotel** [comment] 2021-06-28 08:32
Hello @achatpc,

We have made the changes as per your comment in the Media.php file. But still we are not able to reproduce the issue in our instance.

Please let us know If we have missed anything.

**Comment by engcom-Hotel** [comment] 2021-09-13 07:42
Dear @indykoning,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2021-09-13 07:42 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
