### ISSUE TITLE
Billing address Postcode is not validated in checkout page.

### ISSUE THREAD

**Issue by RakeshJesadiya** [magento/magento2#13260] opened 2018-01-18 12:47 UTC
**Preconditions**
Magento 2.2.2
PHP 7.0.22

**Steps to reproduce**
Add product to cart, Just go to the checkout page, Fill up Shipping Address data click on Next button after selecting a shipping method.
Now on the Second step, Select Payment method, Untick the  My billing and shipping address are the same,
Click on New Address from dropdown,
Select Country as US,
Now enter any postcode value which is not valid to US address, They don't give any notification for Postcode is valid or not.
Just like as Shipping address postcode field with notification "Provided Zip/Postal Code seems to be invalid. Example: 12345-6789; 12345. If you believe it is the right one you can ignore this notice.".
Magento doesn't give notification for postcode with New Billing Address Form.

**Expected result**
For Billing address, Gives notification like shipping address form for the invalid postcode.

**Actual result**
Billing address with postcode notification will display if wrong/invalid postcode for the country.

**Comment by magento-engcom-team** [comment] 2018-01-18 13:34
@RakeshJesadiya, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by fcjurado** [comment] 2018-02-14 10:12
Hi, the same issue is facing to me for Shipping address too. Could it be related?

Documentation: http://devdocs.magento.com/guides/v2.0/howdoi/checkout/checkout_zip.html

I thought some people is having the same issue:
https://magento.stackexchange.com/questions/199517/magento-2-postal-zip-code-validation-canadian-us
https://github.com/magento/magento2/issues/159

**Comment by vaso123** [comment] 2018-06-26 05:34
Does not matter the country, I did not fill anything and it is still allows me to place order. In 2.2.4

**Comment by arnoudhgz** [comment] 2018-07-16 08:06
It is still present in 2.2.5.

**Comment by arnoudhgz** [comment] 2018-11-26 16:59
It is still present in 2.2.6

**Comment by magento-engcom-team** [comment] 2019-01-18 10:56
Hi @roshani2jcommerce. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by arnoudhgz** [comment] 2019-03-12 08:57
Still present in 2.2.7 

@roshani2jcommerce are you still working on this?

**Comment by alexandrosk** [comment] 2019-05-16 13:11
It seems it works on 2.2.8 can someone agree on this?

**Comment by arnoudhgz** [comment] 2019-05-16 13:21
@alexandrosk  you are right!

**Closed as completed** 2019-05-16 13:22 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
