### ISSUE TITLE
Unable to use API to save quote item when backorder is set to "Allowed and Notify Customer"

### ISSUE THREAD

**Issue by vovayatsyuk** [magento/magento2#24822] opened 2019-10-02 10:38 UTC
### Summary
I have a module that allows changing qty of cart items at the checkout page.
**No custom backend logic is used.** The following API point is used [/V1/guest-carts/:cartId/items](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Quote/etc/webapi.xml#L205-L210) for all backend stuff.

Everything works nicely until you enable "Allowed Qty Below 0 and Notify Customer" for some product and try to change its qty.

### Issues

- Two messages about back-ordered item instead of one:

  ![image](https://user-images.githubusercontent.com/306080/66030655-795bbe00-e50a-11e9-95c8-0800c9405d36.png)

- Item qty is not updated.

### Examples

1. Open simple product in the backend, set its qty to 0 and set "Allowed Qty Below 0 and Notify Customer" option.
2. Add this product to the cart. **Make sure that there is only one product in the cart!**
3. Navigate to the checkout page.
4. Call this simplified script in dev console:

    ```js
    require([
        'jquery',
        'mage/storage',
        'Magento_Checkout/js/model/quote',
        'Magento_Customer/js/customer-data',
        'Magento_Checkout/js/model/resource-url-manager',
        'Magento_Checkout/js/model/error-processor',
        'Magento_Checkout/js/model/full-screen-loader',
        'Magento_Checkout/js/action/get-payment-information'
    ], function (
        $,
        storage,
        quote,
        customerData,
        resourceUrlManager,
        errorProcessor,
        fullScreenLoader,
        getPaymentInformationAction
    ) {
        'use strict';

        /**
         * Update item qty
         */
        function updateCart() {
            var params = {
                cartItem: {
                    'item_id': quote.getItems()[0].item_id,
                    'qty': quote.getItems()[0].qty + 1,
                    'quote_id': quote.getQuoteId()
                }
            };

            fullScreenLoader.startLoader();

            return storage.post(
                resourceUrlManager.getUrl({
                    'guest': '/guest-carts/:cartId/items',
                    'customer': '/carts/mine/items'
                }, {
                    cartId: quote.getQuoteId()
                }),
                JSON.stringify(params)
            ).done(
                function () {
                    var deferred = $.Deferred();

                    getPaymentInformationAction(deferred);

                    $.when(deferred).done(function () {
                        customerData.invalidate(['cart']);
                        fullScreenLoader.stopLoader();
                    });
                }
            ).fail(
                function (response) {
                    errorProcessor.process(response);
                    fullScreenLoader.stopLoader();
                }
            );
        }

        updateCart();
    });
    ```

### Investigation

  1. API point call for [Magento/Quote/Model/Quote/Item/Repository::save](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Quote/Model/Quote/Item/Repository.php#L92-L109)
  2. This method calls two methods: `$this->quoteRepository->getActive($cartId)` and `$this->quoteRepository->save($quote);`. The first problem is that **both of them will trigger `checkQuoteItemQty` (see the next point) wich is causing two messages.**
  3. checkQuoteItemQty is [called](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/CatalogInventory/Model/Quote/Item/QuantityValidator/Initializer/StockItem.php#L113).
  4. Message is [added to DataObject](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/CatalogInventory/Model/StockStateProvider.php#L198-L216):

      ```php
      $result->setMessage(
          __(
              'We don\'t have as many "%1" as you requested, '
              . 'but we\'ll back order the remaining %2.',
              $stockItem->getProductName(),
              $backOrderQty * 1
          )
      );
      ```

  5. Message is [copied from DataObject to QuoteItem]():

      ```php
      if ($result->getMessage() !== null) {
          $quoteItem->setMessage($result->getMessage());
      }
      ```

  6. The message is [treated as error](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Quote/Model/Quote/Item/CartItemPersister.php#L75-L83):

      ```php
      if (!empty($currentItem->getMessage())) {
          throw new LocalizedException(__($currentItem->getMessage()));
      }
      ```

### Proposed solution

My proposal is to not to use `setMessage` [for backorder notices](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/CatalogInventory/Model/StockStateProvider.php#L198-L216) but smth like `setNotice`. (Since messages are already used as errors for years and we don't want to make backward-incompatible changes)

In this case, we need to rewrite message rendering in the shopping cart because if we move backorder message to notices this will disappear:

![image](https://user-images.githubusercontent.com/306080/66037832-2d644580-e519-11e9-98eb-9d3d36145060.png)

### Related issues

https://github.com/magento/magento2/issues/24191

**Comment by vovayatsyuk** [comment] 2019-10-02 10:42
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-10-02 10:42
Hi @vovayatsyuk. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-10-02 10:42
Hi @vovayatsyuk, here is your [Magento instance](https://i-24822-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24822-2-3-develop.instances.magento-community.engineering/admin](https://i-24822-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by vovayatsyuk** [comment] 2019-10-02 10:49
Yes, I can reproduce it on demo instance:

![image](https://user-images.githubusercontent.com/306080/66038647-67cee200-e51b-11e9-8d0e-c7e69dee3872.png)

**Comment by magento-engcom-team** [comment] 2019-10-02 14:02
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21010` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by anujwebkul** [comment] 2019-10-12 06:36
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-10-12 06:36
Hi @anujwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-10-12 06:37
Hi @anujwebkul, here is your [Magento instance](https://i-24822-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24822-2-3-develop.instances.magento-community.engineering/admin](https://i-24822-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by bubasuma** [comment] 2020-02-06 15:19
Internal Magento team is working on this issue right now.

**Comment by magento-engcom-team** [comment] 2020-02-13 11:10
Hi @vovayatsyuk. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.4-develop` branch(es).
Related commit(s):
 - [c5cbcfe14a9b3019ae3f4470e857176ddbaa54f0](https://github.com/magento/magento2/commit/c5cbcfe14a9b3019ae3f4470e857176ddbaa54f0)

The fix will be available with the upcoming `2.4.0` release.

**Closed as completed by magento-engcom-team** 2020-02-13 11:10 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: SalesInventory, Fixed in 2.4.x

**Comment by juho-jaakkola** [comment] 2020-03-06 12:04
If I understand this correctly, the patch is not a proper fix. It just hides the problem, and makes it seem like the quantity was increased even though the API call in fact created a backorder.

How can the customer now know that some of the products will be delivered later?

**Comment by bubasuma** [comment] 2020-03-06 15:58
@juho-jaakkola 
This API endpoint returns `\Magento\Quote\Api\Data\CartItemInterface` on successful response. Because `\Magento\Quote\Model\Quote\Item::getMessage()` is not part of the interface `\Magento\Quote\Api\Data\CartItemInterface`, backorder warning message will not be returned in the response.

Basically, you can extend this API to return messages in response.

**Comment by juho-jaakkola** [comment] 2020-03-09 07:18
@bubasuma Backorders are a built-in feature in Magento. There should be no need for store owners to extend the API just to get it to support Magento's own default feature.
