### ISSUE TITLE
Layered Navigation does not filter products properly

### ISSUE THREAD

**Issue by arsalanworld** [magento/magento2#36096] opened 2022-09-06 15:32 UTC
### Preconditions and environment

- Magento version: 2.4.5
- `Display product out of stock` is set to `Yes` from `STORES > Configuration > Catalog > Inventory >  Display Out of Stock Products` settings.
- Make sure elasticsearch is working correctly

### Steps to reproduce

1. Navigate to Product listing page
2. Apply any of the filter from filters list

### Expected result

Only filterable content should be shown

### Actual result

No filter is applied and no effect on product listing. All products are still showing.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by gwharton** [comment] 2022-09-11 16:35
Duplicate of https://github.com/magento/magento2/issues/35899

**Comment by engcom-Bravo** [comment] 2022-09-12 13:15
Hi @arsalanworld,

Thank you for reporting and collaboration. 

Verified the issue on Magento 2.4-develop branch and the issue is reproducible with above steps to reproduce. however, similar issue has been confirmed [here](https://github.com/magento/magento2/issues/35899)


Hence We are closing this issue as duplicate.


Thanks.

**Closed as completed by engcom-Bravo** 2022-09-12 13:15 UTC
Labels: duplicate, Priority: P2, Progress: done, Issue: ready for confirmation, Reported on 2.4.5
