### ISSUE TITLE
Key Magento components are based on magento/composer v1.6.0 (composer 1), not v1.7.0 (composer 2)

### ISSUE THREAD

**Issue by michalrostek** [magento/magento2#33681] opened 2021-08-04 10:17 UTC
### Preconditions (*)

1. Magento 2.4.2 - 2.4.3
2. Composer 2 (only)

### Steps to reproduce (*)

1. Key core components: magento/magento2-ee-base, magento/magento2-base, magento/product-community-edition, magento/product-enterprise-edition require magento/composer 1.6.0, which in turn requires composer 1, this despite the fact that magento/composer 1.7.0 was released in March 2021, which can work with composer 2.0 ... despite the recommendation and the official compatibility message from version 2.4.2 ...
2.

### Expected result (*)

1. We can use Magento only with Composer 2.0
2.

### Actual result (*)

1. Due to dependencies, Composer 1.0 is required:
Problem 1
    - magento/composer 1.6.0 requires composer/composer ^1.9 -> found composer/composer[1.9.0, ..., 1.10.x-dev] but it conflicts with your root composer.json require (^2.0).
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment] 2021-08-04 16:58
Duplicate of: https://github.com/magento/magento2/issues/33047
Got fixed by: https://github.com/magento/magento2/pull/33546

Also see some discussion on Slack chat:
<img width="1141" alt="Screenshot 2021-08-04 at 18 55 55" src="https://user-images.githubusercontent.com/85479/128222643-a60df0d6-086c-4198-a8b2-67828c427065.png">

It's a bit silly this was introduced in Magento 2.3.7 **3 months** ago and then it was forgotten to be added to 2.4.3
So now we'll probably have to [wait](https://devdocs.magento.com/release/) until 2.4.4 or maybe maybe until 2.4.3-p1 is released ...

**Comment by fascinosum** [comment] 2021-08-04 18:43
hi @michalrostek,
Magento 2.4.2 and above are compatible with Composer 2 as a tool. We have Composer 1 as installed dependency, but this does not affect the deployment process
If for some reason you have a strict requirement for `composer/composer` in your root composer.json please update it to https://github.com/magento/magento2/blob/81c9d65149797f2503871f39987d930c4efe1716/composer.json#L36

**Comment by michalrostek** [comment] 2021-08-05 14:01
> hi @michalrostek,
> Magento 2.4.2 and above are compatible with Composer 2 as a tool. We have Composer 1 as installed dependency, but this does not affect the deployment process
> If for some reason you have a strict requirement for `composer/composer` in your root composer.json please update it to
> 
> https://github.com/magento/magento2/blob/81c9d65149797f2503871f39987d930c4efe1716/composer.json#L36

@fascinosum, hi! yes, I know I can use it, but here it was about using composer 2 only

**Comment by engcom-Lima** [comment] 2021-09-01 08:11
Hi @michalrostek,

Since this issue is already fixed on #33546 but not added in 2.4.3. You might have to wait for it to be added in patch or later versions.

You can check @hostep's comment https://github.com/magento/magento2/issues/33047#issuecomment-844423628 for your ref.

Let us know if you still have any issues or can we close this issue ?

**Comment by engcom-Lima** [comment] 2021-09-22 10:48
Hi @michalrostek,

Thank you for updating. We are closing this issue on the basis that there is nothing pending left to do except wait for patch or future release. In future release if you still face similar problem, feel free to re-open this issue or creating a new one.

Regards

**Closed as completed by engcom-Lima** 2021-09-22 10:48 UTC
Labels: duplicate, Severity: S3, Issue: needs update, Reported on 2.4.3
