### ISSUE TITLE
Disabled configurable products not being removed from existing customer carts when flat category product is enabled

### ISSUE THREAD

**Issue by tgreeve** [magento/magento2#36758] opened 2023-01-20 05:03 UTC
### Preconditions and environment

- Magento version: 2.4.5-p1
- "Use Flat Catalog Category" option is enabled
- "Use Flat Catalog Product" option is enabled
- A configurable product with color option black and white
>  Product A - Black
> Product A - White
- A simple product
> Product B

### Steps to reproduce

1. Start logged in session for customer 1.
2. Add a "Product A - Black" to customer 1's cart.
3. As an admin, disable "Product A - Black".
4. Return to customer 1's session.
5. Add Product B to customer 1's cart.
6. View cart

### Expected result

1. Expect to see product B in the cart.
2. Expect not to see "Product A - Black" in the cart.
3. Expect "Product A - Black" to be removed from the customer's quote, and proceed to checkout as an option.

### Actual result

1. Expect to see product B in the cart. - PASS
2. Expect not to see "Product A - Black" in the cart. - FAIL
3. Expect "Product A - Black" to be removed from the customer's quote, and proceed to checkout as an option. - FAIL

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by tgreeve** [comment] 2023-01-20 05:04
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-01-24 09:16
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-01-24 11:52
Hi @tgreeve,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.

As per Magento devdocs. Use of a flat catalog is no longer recommended as a best practice. Continued use of this feature is known to cause performance degradation and other indexing issues.

Kindly check this https://experienceleague.adobe.com/docs/commerce-admin/catalog/catalog/catalog-flat.html and let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-02-06 09:07
Hi @tgreeve,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-02-06 09:07 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1
