### ISSUE TITLE
Grid header in Safari

### ISSUE THREAD

**Issue by ReyMayson** [magento/magento2#2726] opened 2015-12-15 23:43 UTC
Some grid headers doesn't render correctly in Safari 9 (Mac OSX El Capitan)
<img width="1158" alt="screenshot 2015-12-16 01 41 57" src="https://cloud.githubusercontent.com/assets/8927970/11827609/3b6b47b4-a396-11e5-93a5-11673db71dd4.png">

**Comment by vzabaznov** [comment] 2016-06-22 14:15
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment] 2016-07-14 08:08
Hi, @ReyMayson thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.

**Closed as completed by vzabaznov** 2016-07-14 08:08 UTC
