### ISSUE TITLE
Setup Wizard not accessible if pub directory is webroot

### ISSUE THREAD

**Issue by bh-ref** [magento/magento2#3381] opened 2016-02-12 11:28 UTC
The Setup Wizard entry in the admin panel redirects to the example.com/setup page, which is not accessible if the pub directory is webroot instead of the magento base directory.

I think that this should be accessible if pub directory is webroot, too?

Thanks in advance for your investigations.

**Comment by veloraven** [comment] 2016-11-02 08:20
@bh-ref I'm closing this issue as  GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you think it to be an issue which requires fix please create new GitHub issue following the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. Please, also identify which version of Magento you are running.

**Closed as completed by veloraven** 2016-11-02 08:20 UTC
Labels: Component: Setup
