### ISSUE TITLE
Mysql sock SQLState error when running setup:upgrade but site connects to DB fine. Abstract.php  SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by LiamKarlMitchell** [magento/magento2#25724] opened 2019-11-25 00:11 UTC
Error: In Abstract.php line 144: 128: SQLSTATE[HY000] [2002] No such file or directory

PHP looks at a different default path for the unix socket location...
setup:upgrade and possibly other areas do not use what I have configured in the etc/env config!

```
    'db' => [
        'table_prefix' => '',
        'connection' => [
            'default' => [
                'host' => 'localhost',
                'dbname' => '...',
                'username' => '...',
                'password' => '...',
                'unix_socket' => '/var/run/mysqld/mysqld.sock',
                'model' => 'mysql4',
                'engine' => 'innodb',
                'initStatements' => 'SET NAMES utf8mb4;',
                'active' => '1'
            ]
        ]
    ],
```

It should use the unix_socket setting not the PHP default location of the socket.

https://stackoverflow.com/questions/36639014/got-error-while-installing-module-in-magento2-sqlstate-hy000-2000-no-such-f
ln -s /var/run/mysqld/mysqld.sock /tmp/mysql.sock

Or configure php.ini to look for that as the socket.

pdo_mysql.default_socket = /var/run/mysqld/mysqld.sock
mysqli.default_socket = /var/run/mysqld/mysqld.sock
mysql.default_socket = /var/run/mysqld/mysqld.sock

Maria DB, Docker container, sock is put through using a volume.
Website works fine, just setup:upgrade and possibly other areas looking at the wrong location.
When I do a symlink to the /tmp/mysql.sock it resolves the issue.

**Comment by engcom-Charlie** [comment] 2019-11-26 10:49
Hello @LiamKarlMitchell 
We are not able to reproduce this issue on the latest 2.3-develop branch.
For using a unix sockets you have to configure your  `PHP` for it.
![image](https://user-images.githubusercontent.com/51680850/69618313-5e0cbb00-1042-11ea-82f5-35273f89a2ae.png)
Info from [this topic.](https://devdocs.magento.com/guides/v2.3/install-gde/install/cli/install-cli-install.html)

So i have to close this issue.

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-11-26 10:49 UTC
Labels: Issue: Format is not valid

**Comment by LiamKarlMitchell** [comment] 2019-11-27 00:36
Respectfully it works fine in web site.
The bin/magento setup:upgrade does not respect the unix_socket setting!

I should not have to configure this setting additionally in PHP if it is already configured in the env file for the DB connection.
