### ISSUE TITLE
Admin user custom resources roles are not showing during the install fresh Magento 2.x

### ISSUE THREAD

**Issue by kikinbenshakib** [magento/magento2#9312] opened 2017-04-19 12:42 UTC
I have installed Magento 2.1.5 but I didn't see any custom user resource roles in Admin panel.

Could please look into it. I have alternative solution for it but I want to get a fix & permanent solution for it.

**Comment by korostii** [comment] 2017-04-20 09:41
If you are looking for some help or an advice regarding setup or development please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.
The issues which cannot be consistently reproduced on a clean installation of Magento 2 CE aren't likely to get resolved in here.
Thus if you are, in fact, reporting a technical issue, please try add as much information as possible, including the environment you use, 3rd party themes and modules installed, preconditions, exact steps to follow, screenshots and stack trace from browser console and even the custom code you're using. These raise the chances of the bug getting reproduced and acknowledged. 
If you don't provide enough information, it is likely that the issue will receive a "needs update" label and will get closed in a couple weeks.

**Comment by kikinbenshakib** [comment] 2017-04-20 14:40
Sorry for the delay my reply.

I have attached the screenshot below to get a clear idea. Custom user roles resource are not showing.
Please check the screenshot below.
And give me a solution for that.

![roles](https://cloud.githubusercontent.com/assets/22374102/25236329/66876454-2609-11e7-8e39-3aeb0419bd6e.png)

**Comment by korostii** [comment] 2017-04-21 06:53
Ha, the delay. Some issues here don't even get a response from an official representative of Magento Inc. for months straight, so don't sweat it. Anything in under 2 weeks is fine :)

Well, I just checked and on my 2.1.5 resources appear just fine: http://take.ms/5u1O2
So there must be some kind of preconditions in place which you failed to mention. 

I would guess it might be caused by some 3rd party or custom code you're having (there seem to be menu items on your screenshot which aren't provided by Magento CE out of the box). I would suggest that you disable those one-by-one in order to narrow down the source of the issue.

Alternatively, you could try checking the browser console for errors in case some piece of JS got broken and also check `<You Magento installation dir>/var/log/system.log` for relevant errors,

**Comment by korostii** [comment] 2017-04-21 12:16
Possible duplicate: https://github.com/magento/magento2/issues/9337

**Comment by kikinbenshakib** [comment] 2017-04-21 13:53
Still, I am having this error on my local machine and also on the live Server.

Do you have any alternative solution for which will be a permanent solution?
Please give me a shout when you will figure it out.

**Comment by korostii** [comment] 2017-04-27 10:24
Found an older similar issue: #5803
It seems to have a workaround [in comments](https://github.com/magento/magento2/issues/5803#issuecomment-251919603).

**Comment by Brendonwbrown** [comment] 2017-09-27 18:07
I am having this issue on 2.1.9.
Role Resources is either All or Custom.
Selecting Custom displays the "Resources" title, but no further content/options.

**Comment by magento-engcom-team** [comment] 2017-10-12 08:34
@kikinbenshakib, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Closed as completed by magento-engcom-team** 2017-10-12 08:34 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is not valid
