### ISSUE TITLE
System option inside store configurations returns Blank - Magento 2.1 v production mode

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#6288] opened 2016-08-23 11:41 UTC
I am Using Magento 2.1v C.E
Moved to production mode successfully, but i see two errors.
1. Inside Admin - Stores->configuration->Advanced -> system option returns a 500 error  (blank)
It shows me the following on debug.log
[2016-08-23 11:06:29] main.DEBUG: cache_invalidate:  {"method":"POST","url":"http://magento2/admin_vab11c/admin/index/index/key/cec8413965096bc2b931df5366e45d3096b9a635c712945d798fcbb2ee0eea72/","invalidateInfo":{"tags":["BACKEND_MAINMENU"],"mode":"matchingAnyTag"},"is_exception":false} []
[2016-08-23 11:16:32] main.DEBUG: cache_invalidate:  {"method":"POST","url":"http://magento2/admin_vab11c/admin/index/index/key/0e40f17c478c901b69d103bb8c84b95ddbc3433a587e51b11ce6f809fff2a195/","invalidateInfo":{"tags":["BACKEND_MAINMENU"],"mode":"matchingAnyTag"},"is_exception":false} []
[2016-08-23 11:21:21] main.DEBUG: cache_invalidate:  {"method":"POST","url":"http://magento2/admin_vab11c/admin/index/index/key/6fd32b6609d32875f6e8611eefd3abdbd2d0a2ffebdd0f0d3f76e8535244e540/","invalidateInfo":{"tags":["BACKEND_MAINMENU"],"mode":"matchingAnyTag"},"is_exception":false} []

I also don't see the Flush static css option under admin-system-cache management as well.
It deployed to production mode successfully.
Please find the images attached.
![system error](https://cloud.githubusercontent.com/assets/19605497/17890570/d40eccbc-692e-11e6-9c62-a18450c59f99.png)
![css static](https://cloud.githubusercontent.com/assets/19605497/17890574/d8e721bc-692e-11e6-9113-c0f14b36cfd0.png)

**Comment by sevos1984** [comment] 2016-09-12 13:15
Have you tried clearing var/cache/ folder?

**Comment by nmallepally** [comment] 2016-09-12 13:19
@sevos1984 Yes, I did before deploying to production mode.

**Comment by sevos1984** [comment] 2016-09-12 13:35
And after?

**Comment by sevos1984** [comment] 2016-09-26 12:13
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-09-26 12:13 UTC
Labels: bug report, Progress: needs update, Component: Config

**Comment by nmallepally** [comment] 2016-09-27 12:13
@sevos1984 Sorry, I was offline for 2 weeks.
Once it goes to production mode successfully, everything is setup nicely from front end and backend except two functions system option under stores -> configuration and another is sysetm->cache management->flush static files option.

**Comment by nmallepally** [comment] 2017-01-23 11:43
The same replicated after going into production mode in 2.1.3 v.
what difference I found was if I go into production mode skipping compilation,(--skip-compilation)
the system page is visible. i had to go to production mode by skip compilation.
