### ISSUE TITLE
PayPal Express does not allow changing billing address

### ISSUE THREAD

**Issue by chequille** [magento/magento2#31923] opened 2021-02-01 14:44 UTC
### Preconditions (*)
1. Magento 2.4.1
1. h3. Steps to reproduce (*)
1. Reproducing is easy, just enable PayPal as Payment and try to make an order.
1. When selecintg PayPal as payment, there it is not possible to change the billing address as it is with other payment methods.

### Expected result (*)
1. Checkbox with billing address = shipping address should be there to be able to change the billing address
1. WIthin payment method "Paypal with billing agreements" the checkbox is there and I can change the biling address
1. ![grafik](https://user-images.githubusercontent.com/15807794/106474028-c526ca80-64a4-11eb-8c3f-525b189aaf5e.png)
1. This must be as well with normal Paypal Express payment

### Actual result (*)
1. ![grafik](https://user-images.githubusercontent.com/15807794/106473633-4893ec00-64a4-11eb-8ef4-a012ad608917.png)

1. Checkbox to change billing address is not there

## 
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- < ] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
- [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
- [ > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

**Comment by chequille** [comment] 2021-02-01 15:04
Additional information:
I have this in my paypal-express.html:
        <div class="payment-method-billing-address">
            
            
            
        </div>
But it is not rendered.
Please check this and make it working. It is a mandatory feature!!!!!

**Comment by ajijshekh123** [comment] 2021-02-01 17:03
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment] 2021-02-01 17:24
Hello @chequille,
The issue has been reproduced on the latest Magento 2.4 Instance.
"My billing and shipping address are the same" options are not showing while the user selects the "PayPal Express Checkout" Payment method. But When the user selects the other payment method like "Check Money Order", "My billing and shipping address are the same" options are properly showing.

**See attached both screenshots:**

![image](https://user-images.githubusercontent.com/24711761/106494413-65e6ab80-64e0-11eb-83e4-3cc7d9ec9d16.png)

![image](https://user-images.githubusercontent.com/24711761/106494445-6ed77d00-64e0-11eb-9faa-cdea7c241d1e.png)

Thanks.

**Comment by magento-engcom-team** [comment] 2021-02-01 17:26
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40707` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by chequille** [comment] 2021-02-01 19:09
Solution:
adding the following code to paypal-express.html in modul-paypal/view/frontend/web/template/payment
```
        <div class="payment-method-billing-address">
            <!-- ko foreach: $parent.getRegion(getBillingAddressFormName()) -->
            <!-- ko template: getTemplate() --><!-- /ko -->
            <!--/ko-->
        </div>

```and set in modul-paypal/view/frontend/layout/checkout_index_index.xml
```
                                                                        <item name="paypal_express" xsi:type="array">
                                                                            <item name="isBillingAddressRequired" xsi:type="boolean">**true**</item>
                                                                        </item>

```
After thhis it looks like:
![grafik](https://user-images.githubusercontent.com/15807794/106505977-55770680-64c9-11eb-9c08-676f94372473.png)

**Comment by mrtuvn** [comment] 2021-03-26 11:16
Default this value set to false from core but you can re-define it in your theme or your custom module! Not sure this is bug or feature :)
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Paypal/view/frontend/layout/checkout_index_index.xml#L48

**Comment by zakdma** [comment] 2021-04-08 13:25
@magento i am working on it

**Comment by alexgubarev** [comment] 2021-11-25 11:39
@magento give me 2.4-develop instance

**Comment by thinksys-dev** [comment] 2022-03-03 08:41
Hi Team,

Do you have any fix or patch for this, please let us know about this. Thanks

**Comment by perryholden** [comment] 2024-02-15 20:20
> Default this value set to false from core but you can re-define it in your theme or your custom module via layout xml! Not sure this is bug or feature :) https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Paypal/view/frontend/layout/checkout_index_index.xml#L48

I believe it's set to false intentionally, since it assumes it will get the billing address from PayPal. See the JS file: `vendor/paypal/module-braintree-core/view/frontend/web/js/view/payment/method-renderer/paypal.js` and the method `beforePlaceOrder`. The payload is returned from PayPal, and it contains the billing address that will ultimately be set on the quote:

![devtools](https://github.com/magento/magento2/assets/13052746/63ad8d81-fa7a-4cfb-9cf3-b756207a2578)

**Comment by engcom-Delta** [comment] 2024-09-03 11:02
Hi @chequille ,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop and it is an expected behaviour. Kindly refer the screenshots.

**Steps to reproduce**
1. Install magento 2.4-develop 
2. Enable PayPal Express 
![image](https://github.com/user-attachments/assets/36316cf5-134e-4393-8529-dde3db742794)
3. Add item to cart and navigate to checkout
4. Select the payment method as PayPal and observe option to change billing address is not available and it is an expected behavior.
![image](https://github.com/user-attachments/assets/388a653f-f599-4403-9a64-14a1f6aea865)

Kindly recheck the issue on latest Magento 2.4-develop instance and Please let us know if you are still facing any issue.

Thanks.

**Closed as completed by engcom-Delta** 2024-09-03 11:02 UTC
Labels: Component: Checkout, Issue: Clear Description, Issue: Confirmed, Component: Paypal, Reproduced on 2.4.x, Priority: P2, Progress: done, Issue: ready for confirmation, Area: Account
