### ISSUE TITLE
Filter order grid by purchase date doesn't work.

### ISSUE THREAD

**Issue by vseager** [magento/magento2#25642] opened 2019-11-18 17:32 UTC
### Preconditions (*)
1. Magento 2.3.2
2. Locale set to `English (United Kingdom)`
3. Timezone set to `Greenwich Mean Time (Europe/London)`

### Steps to reproduce (*)

1. Go to `Sales > Orders`
2. Select `Filter` and add a  value to the `from` (I used `01/08/2019`) and `to` (I used `13/09/2019`)  fields under `Purchase Date`.
3. Click `Apply Filters`

### Expected result (*)

1. Grid only shows order between the selected dates

### Actual result (*)

1. Grid shows orders from the correct `from` date (no older than `01/08/2019`) but not limited to orders before the `to` date
![screenshot-magento staging edge-servers com-2019 11 18-17_25_04](https://user-images.githubusercontent.com/2035088/69075109-aa477200-0a28-11ea-8f85-b9141d8a45b4.png)

### Steps to reproduce (*)

1. Go to `Sales > Orders`
2. Select `Filter` and THE SAME value to the `to` and `from` fields (I used `13/09/2019` - 13th September 2019)
3. Click `Apply Filters`

### Expected result (*)

1. Grid only shows orders placed on the `13/09/2019` (13th September 2019)

### Actual result (*)

1. Grid shows all orders from all dates and are not limited to orders placed on 13th September 2019

![screenshot-magento staging edge-servers com-2019 11 18-17_31_19](https://user-images.githubusercontent.com/2035088/69075499-6c971900-0a29-11ea-9672-f6c6c0eab6ab.png)

**Comment by engcom-Echo** [comment] 2019-11-19 10:54
Hello @vseager 

Thank you for your report and collaboration!
Tested on 2.3.3 and 2.3-develop.
We are not able to reproduce this issue by provided steps.

**Preconditions:** 
1. Locale set to English (United Kingdom)
2. Timezone set to Greenwich Mean Time (Europe/London)

**Testing scenario 1:**

**Steps to reproduce:**
1. Go to Sales > Orders
2. Select Filter and add a value to the from (for example 01/08/2019) and to (for example 13/09/2019) fields under Purchase Date.
3. Click Apply Filters

**Result:** 
Grid shows order between the selected dates
![Screenshot from 2019-11-19 12-06-37](https://user-images.githubusercontent.com/51681435/69139575-75d7c280-0ac9-11ea-8128-868d96df39ec.png)

**Testing scenario 2:**

**Steps to reproduce:**
1. Go to Sales > Orders
2. Select Filter and THE SAME value to the to and from fields (for example 13/09/2019 - 13th September 2019)
3. Click Apply Filters

**Result:** 
Grid only shows orders placed on the 13/09/2019 (13th September 2019)
![Screenshot from 2019-11-19 12-46-10](https://user-images.githubusercontent.com/51681435/69140198-b4ba4800-0aca-11ea-942e-00f02b116225.png)

So I close it.
Thanks for your report!

**Closed as completed by engcom-Echo** 2019-11-19 10:54 UTC
Labels: Issue: Format is valid

**Comment by chris-pook** [comment] 2022-06-07 09:55
For anyone stuck looking for an answer on this to patch an old version of Magento, see #22173.
