### ISSUE TITLE
Minicart not updating after sign in

### ISSUE THREAD

**Issue by Zarina2222** [magento/magento2#7500] opened 2016-11-21 09:39 UTC
### Preconditions
1. Magento CE 2.1.0
2. Apache/2.4.18 (Ubuntu) PHP/7.0.8-0ubuntu0.16.04.3 MySQL/5.7.13-0ubuntu0.16.04.2

### Steps to reproduce
1. Sign in
2. Add products to cart (#product_A and #product_B)
3. Log out

4. Add products to cart without signing in first (#product_C and #product_D)
5. Go to Checkout using minicart's Go to Checkout-button
6. Anonymous checkout is disabled so you need to Sign in using Sign in-pop-up
7. After Sign in you return back to same page (even Redirect Customer to Account Dashboard after Logging in is enabled ) and cart show still #product_C and #product_D
8. Go to Checkout using minicart Go to Checkout-button
9. In checkout also #product_A and #product_B shows up.

### Expected result
1. After Sign In using pop-up Sign in-form, cart should be merged and customer redirected to checkout showing all products A,B,C,D

### Actual result
1. Customer was redirected back to same page and cart was not merged (only products C&D still showing)

But
If I Sign in using actual Sign in-link and Sign in-page, cart was merged right and shows also #product_A and #product_B (and I was redirected to Customer Dashboard as should be).

**Comment by SerhiyShkolyarenko** [comment] 2016-11-23 16:28
@Juigeli thank you for reporting the issue!
I tried v2.1.2 and disabled guest checkout. On the step 6 "Anonymous checkout is disabled so you need to Sign in using Sign in-pop-up" I click "Go to checkout" on the minicart and I am redirected to the cart page with a message "Guest checkout is disabled.".
Do you have the same situation on 2.1.2?

**Comment by Zarina2222** [comment] 2016-11-23 18:13
It's look like this:
![image](https://cloud.githubusercontent.com/assets/11063464/20573509/c242630e-b1b8-11e6-83b3-d1823dc8d688.png)
![image](https://cloud.githubusercontent.com/assets/11063464/20573526/d6c85dce-b1b8-11e6-98a2-46eac4fc7cec.png)
![image](https://cloud.githubusercontent.com/assets/11063464/20573538/e4236054-b1b8-11e6-82a3-e6457dc8c29b.png)
![image](https://cloud.githubusercontent.com/assets/11063464/20573545/f1002b86-b1b8-11e6-9585-52f86636b85e.png)
![image](https://cloud.githubusercontent.com/assets/11063464/20573551/fbaf4526-b1b8-11e6-8d32-63c5c9e40da9.png)
![image](https://cloud.githubusercontent.com/assets/11063464/20573574/1f022a48-b1b9-11e6-9d50-b13e75092b75.png)
![image](https://cloud.githubusercontent.com/assets/11063464/20573579/292c48e6-b1b9-11e6-9ea1-d3ee28436a77.png)

**Comment by SerhiyShkolyarenko** [comment] 2016-11-24 10:15
@Juigeli I see what happened, but I cannot reproduce it neither on develop branch not on 2.1.2. Could you please install to empty DB Magento 2.1.2(or current develop branch) and check if the issue is reproducible for you?

**Comment by SerhiyShkolyarenko** [comment] 2016-11-24 11:19
@Juigeli I reproduced the issue after enabling terms and conditions.

**Comment by SerhiyShkolyarenko** [comment] 2016-11-24 14:58
Internal issue MAGETWO-61368.

**Comment by veloraven** [comment] 2017-06-19 15:11
This issue has already been fixed in develop branch.
Internal ticket for ver. 2.1 - MAGETWO-63621

**Comment by magento-engcom-team** [comment] 2017-09-20 22:40
@Juigeli, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:40 UTC
Labels: Issue: Ready for Work, bug report, Component: Customer, Component: Checkout, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid

**Comment by carylewis** [comment] 2017-09-27 14:55
Will this be backported into 2.1.x?
