### ISSUE TITLE
Fotorama swip open fullscreen mode

### ISSUE THREAD

**Issue by N445** [magento/magento2#34112] opened 2021-09-17 12:29 UTC
### Preconditions (*)
1. Magento 2.4

### Steps to reproduce (*)
1. Install a new magento project
2. Create a product with multiple pictures
3. Go on product page in front
4. Slide the product slider for few pixels

### Expected result (*)
1. Slider stop moving
2. Not open the fullscreenmode

### Actual result (*)
1. The fullscreenmode is opened

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/Ifyc1.png

**Comment by engcom-November** [comment] 2021-09-20 12:01
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible:
**Steps performed:**
Magento Admin - Created a new Simple Product with multiple images and saved
Reindex and clear cache
Front end - Navigate to Product Details page - No issue: User is able to view all images.  < Previoud/Next > buttons working as expected
Click on any image - Image opened in Full screen mode - No issue
Scroll the image - Zoom in/ Zoom out - Working as expected - No issue
Slide the images < Previoud/Next > buttons working as expected
![image](https://user-images.githubusercontent.com/60198231/133998568-76f86023-2169-4184-83f8-072c11105c7a.png)
![image](https://user-images.githubusercontent.com/60198231/133998650-5ee67925-7a5d-49f5-89ee-4d700885aa84.png)
![image](https://user-images.githubusercontent.com/60198231/133998684-71b720d1-5092-4f68-8f29-a036c43d8edb.png)

@N445 kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2021-10-04 06:19
@N445 ,
We are closing this issue as there has been no latest update on the same. Kindly reopen/create new ticket with missing steps if the issue is still reproducible on Magento 2.4-develop branch.
Thank you.

**Closed as completed by engcom-November** 2021-10-04 06:19 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
