### ISSUE TITLE
Exception #0 (Exception): Item (Magento\Wishlist\Model\Item) with the same ID "1" already exists.

### ISSUE THREAD

**Issue by hkvega01** [magento/magento2#27137] opened 2020-03-03 10:28 UTC
### Preconditions (*)

1. 2.3.4 community

### Steps to reproduce (*)

1. add products to wishlist with same wishlist_id
2.

### Expected result (*)
Showing all products in wishlist

### Actual result (*)

1. SELECT `main_table`.* FROM `wishlist_item` AS `main_table` WHERE (`wishlist_id` = '1') AND (`main_table`.`store_id` IN('1'))1 exception(s):
Exception #0 (Exception): Item (Magento\Wishlist\Model\Item) with the same ID "1" already exists.

Exception #0 (Exception): Item (Magento\Wishlist\Model\Item) with the same ID "1" already exists.
<pre>#1 Magento\Framework\Data\Collection\AbstractDb->loadWithFilter() called at [vendor/magento/framework/Data/Collection/AbstractDb.php:565]
#2 Magento\Framework\Data\Collection\AbstractDb->load() called at [vendor/magento/framework/Data/Collection.php:849]
#3 Magento\Framework\Data\Collection->count() called at [vendor/magento/module-wishlist/Model/Wishlist.php:634]
#4 Magento\Wishlist\Model\Wishlist->getItemsCount() called at [vendor/magento/module-wishlist/Block/AbstractBlock.php:276]
#5 Magento\Wishlist\Block\AbstractBlock->getWishlistItemsCount() called at [generated/code/Magento/Wishlist/Block/Customer/Wishlist/Interceptor.php:297]
#6 Magento\Wishlist\Block\Customer\Wishlist\Interceptor->getWishlistItemsCount() called at [vendor/magento/module-wishlist/Block/AbstractBlock.php:301]
#7 Magento\Wishlist\Block\AbstractBlock->hasWishlistItems() called at [generated/code/Magento/Wishlist/Block/Customer/Wishlist/Interceptor.php:323]
#8 Magento\Wishlist\Block\Customer\Wishlist\Interceptor->hasWishlistItems() called at [vendor/magento/module-wishlist/view/frontend/templates/view.phtml:20]
#9 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:59]
#10 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/View/Element/Template.php:271]
#11 Magento\Framework\View\Element\Template->fetchView() called at [generated/code/Magento/Wishlist/Block/Customer/Wishlist/Interceptor.php:726]
#12 Magento\Wishlist\Block\Customer\Wishlist\Interceptor->fetchView() called at [vendor/magento/framework/View/Element/Template.php:301]
#13 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/module-wishlist/Block/Customer/Wishlist.php:276]
#14 Magento\Wishlist\Block\Customer\Wishlist->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1099]
#15 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1103]
#16 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:673]
#17 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [generated/code/Magento/Wishlist/Block/Customer/Wishlist/Interceptor.php:1051]
#18 Magento\Wishlist\Block\Customer\Wishlist\Interceptor->toHtml() called at [vendor/magento/framework/View/Layout.php:564]
#19 Magento\Framework\View\Layout->_renderBlock() called at [vendor/magento/framework/View/Layout.php:540]
#20 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#21 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:495]
#22 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#23 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:592]
#24 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:542]
#25 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#26 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:495]
#27 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#28 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:592]
#29 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:542]
#30 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#31 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:495]
#32 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#33 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:592]
#34 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:542]
#35 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#36 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:495]
#37 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#38 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:592]
#39 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:542]
#40 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#41 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:495]
#42 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#43 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:592]
#44 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:542]
#45 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#46 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:495]
#47 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#48 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:592]
#49 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:542]
#50 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:206]
#51 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:495]
#52 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:193]
#53 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:961]
#54 Magento\Framework\View\Layout->getOutput() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#55 Magento\Framework\View\Layout\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#56 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#57 Magento\Framework\View\Layout\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:494]
#58 Magento\Framework\View\Layout\Interceptor->getOutput() called at [vendor/magento/framework/View/Result/Page.php:258]
#59 Magento\Framework\View\Result\Page->render() called at [vendor/magento/framework/View/Result/Layout.php:171]
#60 Magento\Framework\View\Result\Layout->renderResult() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#61 Magento\Framework\View\Result\Page\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#62 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#63 Magento\Framework\View\Result\Page\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:130]
#64 Magento\Framework\View\Result\Page\Interceptor->renderResult() called at [vendor/magento/framework/App/Http.php:120]
#65 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#66 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#67 Magento\Framework\App\Bootstrap->run() called at [index.php:41]
</pre>

Related lines
1. vendor\magento\module-wishlist\Block\Customer\Wishlist.php
```
    /**
     * Retrieve Wishlist Product Items collection
     *
     * @return \Magento\Wishlist\Model\ResourceModel\Item\Collection
     * @since 101.1.1
     */
    public function getWishlistItems()
    {
        if ($this->_collection === null) {
            $this->_collection = $this->_createWishlistItemCollection();
            $this->_prepareCollection($this->_collection);
            $this->paginateCollection();
        }
        echo $this->_collection->getSelect();
        return $this->_collection;
    }
```
Anyone knows how to fix this?

**Comment by AnnaShepa** [comment] 2020-03-03 13:21
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-03 13:21
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-03-03 13:22
Hi @AnnaShepa, here is your [Magento instance](https://i-27137-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27137-2-4-develop.instances.magento-community.engineering/admin_7216](https://i-27137-2-4-develop.instances.magento-community.engineering/admin_7216)
Login: `2b2f0cd3` Password: `7583a9616675`
Instance will be terminated in up to 3 hours.

**Comment by AnnaShepa** [comment] 2020-03-03 13:46
@hkvega01 thank you for the report, but please add more details. In case if you mentioned that you cannot add more then 1 item in one wish list, then I cannot reproduce it, I tried and 2.3.4, and 2.4-develop. Please try yourself on clean magento version and add more steps to reproduce.

**Comment by hkvega01** [comment] 2020-03-03 14:28
here is my wishlist_item table

wishlist_item_id | wishlist_id | product_id | store_id | added_at | description | qty

 1 | 1 | 1402 | 1 | 2020-03-03 15:17:54 | NULL | 2.0000
 2 | 1 | 1402 | 1 | 2020-03-03 15:40:37 | NULL | 1.0000
 3 | 1 | 1402 | 1 | 2020-03-03 15:41:09 | NULL | 1.0000
 4 | 1 | 1402 | 1 | 2020-03-03 17:53:34 | NULL | 1.0000
 5 | 1 | 1818 | 1 | 2020-03-03 18:02:14 | NULL | 1.0000

**Comment by AnnaShepa** [comment] 2020-03-04 10:35
so, it means you managed to add a few items to one wishlist? from FE? but cannot open it on FE?

**Comment by BassemN** [comment] 2020-07-05 00:21
I'm facing the same issue

**Comment by MasudIslam** [comment] 2020-07-08 07:24
I'm facing the same issue. Is there any update on this?

**Comment by mohitka** [comment] 2020-07-08 13:15
I am also having the same issue. Any update on this?

**Comment by BassemN** [comment] 2020-08-10 10:11
@hkvega01 Did you find a solution for this issue?

**Comment by BassemN** [comment] 2020-08-15 12:48
This issue started after migrating from Magento 1

**Comment by jesperbrejning** [comment] 2020-10-02 15:13
Hi, 

We have the same issue:  "Item (Magento\Wishlist\Model\Item) with the same ID &quot;7237&quot; already exists."

**Comment by engcom-Delta** [comment] 2020-12-23 15:39
@hkvega01 @jesperbrejning @BassemN  Unfortunately thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Manual testing scenario:**
- Add row that duplicate `product_id` manually
![image](https://user-images.githubusercontent.com/51681379/103012853-dcd56f80-4544-11eb-9f92-0faaa0f83ee6.png)

- Go to wishlist

**Result:**
No exception error. Product with id `4` shows twice in wishlist
![image](https://user-images.githubusercontent.com/51681379/103013030-2756ec00-4545-11eb-8a9b-bbb7de5a29d2.png)

Could you create issue in data-migration-pool [repo](https://github.com/magento/data-migration-tool/issues) for further discussion and close this one when i will be done?

**Comment by BassemN** [comment] 2020-12-23 15:41
I already open an issue there https://github.com/magento/data-migration-tool/issues/837

**Comment by minenkoden** [comment] 2020-12-30 10:20
Stacked with same problem. For me helped to override class with preference Magento\Wishlist\Model\Wishlist and change getItemCollection function to:
```
public function getItemCollection()
{
    return parent::getItemCollection()->load();
}
```
Point is to add load() function when creating collection with filters.

**Comment by BassemN** [comment] 2021-01-14 08:46
@minenkoden Many thanks. This code fixed the issue.
Thanks again :+1:

**Comment by engcom-Delta** [comment] 2021-01-26 11:50
@hkvega01 @jesperbrejning @BassemN , we are closing this issue as not reproducible on 2.4-develop and same issue was created in appropriate repo: https://github.com/magento/data-migration-tool/issues/837

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Delta** 2021-01-26 11:50 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.3.4
