### ISSUE TITLE
Product model in frontend does not contain price including tax

### ISSUE THREAD

**Issue by tdgroot** [magento/magento2#13957] opened 2018-03-05 13:47 UTC
### Preconditions

1. Magento 2.2.3
2. Configured tax zone and rule so tax is being calculated. (in my case 21% vat for the Netherlands)
3. Configured tax like the following:
![image](https://user-images.githubusercontent.com/1165302/36977190-9a20e4da-2080-11e8-9a4a-84ef8e91e040.png)

### Steps to reproduce

1. Create a product with the price of `5.05`.
2. Visit the product in frontend
3. Price is including tax (in my case `6.11`)
4. Open browser inspector
5. Find meta element `product:price:amount` in head.
![image](https://user-images.githubusercontent.com/1165302/36977415-567c5f92-2081-11e8-9dd1-25bf148171e0.png)

### Expected result

1. Meta element `product:price:amount` contains price including tax.

### Actual result

1. Meta element `product:price:amount` contains price excluding tax, as entered in Magento backend.

### The problem
This issue describes one of many issues, related to the same problem. Here's another example: 
![image](https://user-images.githubusercontent.com/1165302/36977730-73563754-2082-11e8-8aa9-2d429cdd05f2.png)

When you fetch the final price from the product model, it returns the price as it's entered in the backend. In a lot of code, this behavior is not taken into account. See the template of that generates the output of the `product:price:amount` issue: [general.phtml](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Catalog/view/frontend/templates/product/view/opengraph/general.phtml#L17). It just renders the final price of the product. 

We can also see the rendering of the price being implemented to take prices including tax into account: [View.php](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Catalog/Block/Product/View.php#L198).

I created the following class to workaround the problem in some scenarios, but I really think this problem should be addressed in Magento core. [CatalogProductFinalPrice.php](https://gist.github.com/tdgroot/6458c242d6beab82a4bb2f25107ec563)

**Comment by magento-engcom-team** [comment] 2018-03-06 10:22
@tdgroot, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2018-11-02 10:35
Hi @mishanino. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-01-29 07:42
Hi @vshatylo. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by swnsma** [comment] 2019-05-10 10:50
Look like it has been fixed in: #20011

**Comment by swnsma** [comment] 2019-05-10 10:51
Issue need to be re-confirmed.

**Comment by shikhamis11** [comment] 2019-05-10 10:55
thanks @swnsma , I will check this

**Comment by shikhamis11** [comment] 2019-05-21 16:17
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-05-21 16:18
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-05-21 16:18
Hi @shikhamis11, here is your [Magento instance](https://i-13957-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-13957-2-3-develop.instances.magento-community.engineering/admin](https://i-13957-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2019-05-21 17:10
It seems this issue is already fixed so closing this one

**Closed as completed by shikhamis11** 2019-05-21 17:10 UTC
Labels: Issue: Format is valid
