### ISSUE TITLE
Wrong Customer Group assign to order

### ISSUE THREAD

**Issue by ghost** [magento/magento2#26976] opened 2020-02-22 06:55 UTC
### Preconditions (*)

1.Magento 2.3.4
2.

### Steps to reproduce (*)

1. In admin configuration Enable Automatic Assignment to Customer Group set yes
2. login with different Customer Group then Default Group set in admin. 
3. Place order

### Expected result (*)

1. order need to display same login customer group .

### Actual result (*)

1. order display customer group which set as default group in admin configuration.

**Comment by prashantbarot** [comment] 2020-02-22 07:06
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment] 2020-02-22 07:07
Hi @prashantbarot. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by AleksLi** [comment] 2020-02-22 09:48
@prashantbarot I reproduced the issue on 2.4-develop branch. Also the customer group has changed when the order was placed. 

For example I've set wholesale group for customer and _General_ as Customer Group then Default Group in configuration (system->configuration). When the order was placed I've seen that Customer group in order is _General_ but should be **wholesale**. And the customer group for the customer also has changed to _General_. 

So, the issue is relevant, definitely.

**Comment by krishprakash** [comment] 2020-02-22 14:17
Hi @prashantbarot.
Issue is duplicate to #26719 and already open.
You can track progress from above issue id
Thanks

**Comment by prashantbarot** [comment] 2020-02-24 08:42
Hi @krishprakash 

            Thanks for check this one i check with issue #26719 and #26976 both has different issue.In #26976 issue coming only if we set yes for Enable Automatic Assignment to Customer Group and coming this issue in frontend. and #26719 issue coming in admin if try to create reorder.

**Comment by krishprakash** [comment] 2020-02-24 08:59
@prashantbarot. Reopened as issue is coming in different scenario.
Thanks for feedback !!

**Comment by magento-engcom-team** [comment] 2020-02-24 09:01
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31803` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment] 2020-02-25 19:18
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-25 19:19
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-25 19:19
Hi @sdzhepa, here is your [Magento instance](https://i-26976-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26976-2-4-develop.instances.magento-community.engineering/admin_d42b](https://i-26976-2-4-develop.instances.magento-community.engineering/admin_d42b)
Login: `b1ab9a70` Password: `07a6c0642df8`
Instance will be terminated in up to 3 hours.

**Comment by VladimirZaets** [comment] 2020-07-13 18:37
Hi @prashantbarot  . Thanks for collaboration. This issue was reviewed on Community Contribution Triage meeting. The recording of the meeting you can look by the [link](https://www.youtube.com/watch?v=ce2JOgB2NbQ&list=PLDvMskiz68Q2BLkj0-xzjuFl7ZVti9Quj&index=3&t=0s)

**Comment by magento-engcom-team** [comment] 2020-09-12 18:35
Hi @prashantbarot. Thank you for your report. 
The issue has been fixed in magento/magento2#27857 by @ProkopovVitaliy in 2.4-develop branch
Related commit(s):
 - [a84629ff29f6011fceea1b4a40498a9ba78382d3](https://github.com/magento/magento2/commit/a84629ff29f6011fceea1b4a40498a9ba78382d3)
 - [24793f9d90913df2489daffe7cce773c138a684e](https://github.com/magento/magento2/commit/24793f9d90913df2489daffe7cce773c138a684e)
 - [669c923003f0d278a350fbdad128815a9d32fc2f](https://github.com/magento/magento2/commit/669c923003f0d278a350fbdad128815a9d32fc2f)
 - [92bd59190a6ba1469470f9ae4496bf9b8c950974](https://github.com/magento/magento2/commit/92bd59190a6ba1469470f9ae4496bf9b8c950974)
 - [a6cf5cb8901671db758391d7a099c6ed630f5944](https://github.com/magento/magento2/commit/a6cf5cb8901671db758391d7a099c6ed630f5944)
 - [245453e0e4d466da6f147dfa43d6c195e873c523](https://github.com/magento/magento2/commit/245453e0e4d466da6f147dfa43d6c195e873c523)
 - [eb3fe2024f70d1aa9475e752c5884b488509befe](https://github.com/magento/magento2/commit/eb3fe2024f70d1aa9475e752c5884b488509befe)
 - [183a2a0b9cb9d7b90279b78e7aa04597f881f8ed](https://github.com/magento/magento2/commit/183a2a0b9cb9d7b90279b78e7aa04597f881f8ed)
 - [c38d1eff47da68c410eacd92e32df67a0ab80ecf](https://github.com/magento/magento2/commit/c38d1eff47da68c410eacd92e32df67a0ab80ecf)
 - [c6ebe350a09176ba5b5cd6f1b84c93ff4a6390fa](https://github.com/magento/magento2/commit/c6ebe350a09176ba5b5cd6f1b84c93ff4a6390fa)
 - [38ae3b1394cae1c15f28aac77c4d8919313a71e8](https://github.com/magento/magento2/commit/38ae3b1394cae1c15f28aac77c4d8919313a71e8)
 - [3ed5e1c7544d02a78468b7dd856cff80e23fb28d](https://github.com/magento/magento2/commit/3ed5e1c7544d02a78468b7dd856cff80e23fb28d)
 - [07e9b1c5d3ca08b11ca40a9fdf3bcc167c185543](https://github.com/magento/magento2/commit/07e9b1c5d3ca08b11ca40a9fdf3bcc167c185543)
 - [cae2258c432e3c136e36480891ca0d21558d1b11](https://github.com/magento/magento2/commit/cae2258c432e3c136e36480891ca0d21558d1b11)
 - [71533592cace2faa80025628e094d01b29852bfe](https://github.com/magento/magento2/commit/71533592cace2faa80025628e094d01b29852bfe)
 - [2ce9abd006a588e15d2dd87495c5ef1ac23938ab](https://github.com/magento/magento2/commit/2ce9abd006a588e15d2dd87495c5ef1ac23938ab)
 - [32be93c094f95b40d348e66724c71da5dd5f1e59](https://github.com/magento/magento2/commit/32be93c094f95b40d348e66724c71da5dd5f1e59)
 - [a5dba174c0e24c60b5fa3649596bb2f2aaf3fb12](https://github.com/magento/magento2/commit/a5dba174c0e24c60b5fa3649596bb2f2aaf3fb12)
 - [d231549fbe088f0a64e549aefeabf2c7bb8fb642](https://github.com/magento/magento2/commit/d231549fbe088f0a64e549aefeabf2c7bb8fb642)
 - [c1fbef555f4fe874de93a018d4008497aa5bd694](https://github.com/magento/magento2/commit/c1fbef555f4fe874de93a018d4008497aa5bd694)
 - [a9e6752a024fd6998b5a838cdf84cc2004d6dbf7](https://github.com/magento/magento2/commit/a9e6752a024fd6998b5a838cdf84cc2004d6dbf7)
 - [22f98a6b4952b1c28203b558c23748b0f4ec0af3](https://github.com/magento/magento2/commit/22f98a6b4952b1c28203b558c23748b0f4ec0af3)
 - [d64c0e7e2c81a5c8e582f66a80a033cc080e2ca0](https://github.com/magento/magento2/commit/d64c0e7e2c81a5c8e582f66a80a033cc080e2ca0)
 - [7c6b7f7451f696cb7ce819abd60e6b85c8f3149c](https://github.com/magento/magento2/commit/7c6b7f7451f696cb7ce819abd60e6b85c8f3149c)
 - [74c0c92934ca6212cd08f7cfc3f8cf4cb5cffe9c](https://github.com/magento/magento2/commit/74c0c92934ca6212cd08f7cfc3f8cf4cb5cffe9c)
 - [818a7fa969b2c7bf99ca3444048d8d9b42c574cd](https://github.com/magento/magento2/commit/818a7fa969b2c7bf99ca3444048d8d9b42c574cd)
 - [0d97464d1969b363a4d4247e66a5bea6ec5250bc](https://github.com/magento/magento2/commit/0d97464d1969b363a4d4247e66a5bea6ec5250bc)
 - [50bf2f59c007f39acc54d0fca29ad34cf4abb3ca](https://github.com/magento/magento2/commit/50bf2f59c007f39acc54d0fca29ad34cf4abb3ca)
 - [a8ffe0b8e895faa5920e1fff75cac0a0a149afc2](https://github.com/magento/magento2/commit/a8ffe0b8e895faa5920e1fff75cac0a0a149afc2)

The fix will be available with the upcoming 2.4.2 release.

**Closed as completed by magento-engcom-team** 2020-09-12 18:35 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P3, Severity: S2, Progress: done, Reported on 2.3.4
