### ISSUE TITLE
Magento 2.3: "Use Default Value" gets unchecked for Multiple Attributes when updating with an API

### ISSUE THREAD

**Issue by elaidomino** [magento/magento2#32544] opened 2021-03-18 10:24 UTC
### Preconditions (*)

1. Magento 2.3
2. Multiple Store Views.

### Steps to reproduce (*)

1. Bulk Insert new products on Magento 2 backend and all affected product attributes are checked by default
2. To connect the Sales to our Warehouse Management System, we need to create the same items to Dearsystems and BULK List the items to create a connection. But, we are using Magento 2 as master source of products. Dearsys only receives data from M2.
3. After Bulk Listing, go to Magento 2 Default Store View. You'll notice attributes are not checked anymore. Which causes a lot of issues to update all manually.

### Expected result (*)

1. All attributes should remain checked and should FOLLOW the Default value which is checked.

### Actual result (*)

1. Attributes are no longer checked under Default Store View.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by chickenland** [comment] 2021-03-18 13:02
Might help to provide some example API calls and some specific product attributes that are affected

**Comment by bernieu2** [comment] 2021-03-31 02:33
Change your endpoint from /rest/V1/products/:sku (updates single storeId)
to /rest/**all**/V1/products/{{sku}} (updates storeId = 0)

This seems to be only reference I could find for all store code
https://devdocs.magento.com/guides/v2.3/get-started/gs-web-api-request.html#endpoints

or async endpoint: 
PUT /all/async/V1/products/:sku
https://devdocs.magento.com/guides/v2.3/rest/asynchronous-web-endpoints.html#store-scopes

or async bulk endpoint: 
PUT /all/async/bulk/V1/products/bySku
https://devdocs.magento.com/guides/v2.3/rest/bulk-endpoints.html#store-scopes

**Comment by bartlubbersen** [comment] 2021-04-13 16:59
I just came across the same issue in a Magento 2.2 shop, not sure how much the code changed in M2.4/2.3 for the consumer part. But as far as I can see looking through the code, there are no changes that could solve this issue between these versions so probably it's the same issue.

After some research I came to the conclusion that for the shop I am working on it's due to the data caching in the ProductRepository class. If you first update the product async so the consumer will have an object in cache. Then keep the consumer running while saving a product through the backend. Then once you make any async changes the consumer will still be using the old product object and it's data. So all data set through the back-end will be reset.

This occurs because the initializeProductData will use removeProductFromLocalCache to clear the cache, but that will only clear the sku array ($instances) and not the product product id array ($instancesById). So while retrieving the product it will fail to do so by sku cache, so it will lookup the id by sku and then still use the id cache.

Hope this helps.

FYI: We have seen similar results with other class caches like orders, stock, customers etc. when using consumers. In multiple projects. So the whole consumers and class caching should be investigated for multiple types.

**Comment by engcom-Delta** [comment] 2021-07-19 12:39
Hi @elaidomino,

Thanks for raising the issue , We tried reproducing the issue but need more clarity on steps to reproduce it.
1. Dearsystems 
2. Kindly specify few attributes  which are not checked 
3. it would be great if we get snapshots for reference.

Thanks

**Comment by hostep** [comment] 2021-07-20 16:46
This sounds like a duplicate of https://github.com/magento/magento2/issues/9186 (and https://github.com/magento/magento2/issues/26484 and https://github.com/magento/magento2/issues/31083 and probably some others), according to the latest comments in those threads the issue might have been fixed by https://github.com/magento/magento2/commit/6a27b0ce155a418e05bf6a7753af5a947af5668e & https://github.com/magento/magento2/commit/306f515d7a6b66d0dbfd0240d39f2d8e416b09ad (both of which are not released yet, so maybe they are coming in Magento 2.4.3?), but it's not really confirmed I think, so I'm not 100% sure.

@elaidomino: if you believe this is not a duplicate of those others, please leave some feedback 🙂

**Comment by engcom-Delta** [comment] 2021-08-04 10:03
There has no update from 14 days ,hence closing it.
Kindly raise new ticket if required or re-open existing issue.

Thanks

**Closed as completed by engcom-Delta** 2021-08-04 10:03 UTC
Labels: Issue: needs update
