### ISSUE TITLE
Pagination not working after adding the product to Group product

### ISSUE THREAD

**Issue by Abhay-Agrawal** [magento/magento2#33205] opened 2021-06-10 12:44 UTC
This issue is related to group product add time. After selecting the 20 products for the group product then apply the filtering. 

### Preconditions (*)

1.  Magento 2.4.2 version
2. Sample data installed
3. the same issue exists on the 2.3.5-p2 version

### Steps to reproduce (*)

1. Go to Admin.
2. Navigate to Catalog > Products > Click on Add Product button -> Select Grouped Product
3. Add Product information like name, SKU
4. Click on Add Products to Group button -> Pop up Opened
5. Select 20 product to add the product to Group Product
6. After adding the product sort the product according to pagination
7. Select 5 from the paging dropdown
Video Link: https://www.loom.com/share/60ce35fb8fb8412d9ac704093ef90a7e

### Expected result (*)

 ![image](https://user-images.githubusercontent.com/55655451/121526637-32300b00-ca17-11eb-90de-f7ba78ed464c.png)
2. Paging should be work
3. And 5 product must be visible on one page and 5 on another page and so on

### Actual result (*)

Nothing happens after applying the paging filter
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look, and feel, “quality” or “usability”._

**Comment by thamyrisgregorio** [comment] 2021-06-10 21:06
@magento I'm working on it

**Comment by thamyrisgregorio** [comment] 2021-06-10 21:06
@magento give me 2.4-develop instance

**Comment by thamyrisgregorio** [comment] 2021-06-10 21:52
@magento give me 2.4.2-develop instance

**Comment by thamyrisgregorio** [comment] 2021-06-10 22:01
@magento give me 2.4.2-develop instance

**Comment by thamyrisgregorio** [comment] 2021-06-10 22:09
It was tested on version 2.4 and reproduced the steps to make this problem happen, but the error did not happen. Could you give more information?

https://user-images.githubusercontent.com/75129444/121603182-c356b000-ca1e-11eb-8c75-8d187858a714.mp4
is the video of my test.

Thanks

**Comment by Abhay-Agrawal** [comment] 2021-06-11 04:52
I am still getting the same issue on the Magento2.4.2 version and your instance Link is not working to test the issue

**Comment by Abhay-Agrawal** [comment] 2021-06-11 10:44
It should be work like as default sorting and the custom option should be there
http://i.prntscr.com/NQfeeC8jQfidEaUFv0rBsg.png

**Comment by engcom-Bravo** [comment] 2021-06-12 07:00
Hi @Abhay-Agrawal ,

I am able to reproduce this on 2.4.2. But the latest branch 2.4-develop does not have this issue. Could you please verify and confirm?

**Comment by engcom-Bravo** [comment] 2021-06-28 10:25
Hi @Abhay-Agrawal ,

As there is no update on this ticket to the above comment since few days, we are closing this issue. Please open a new ticket if you are still facing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2021-06-28 10:25 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
