### ISSUE TITLE
Cart Price rule not working as expected for joined mutation for configurable options update

### ISSUE THREAD

**Issue by shikhamis11** [magento/magento2#31779] opened 2021-01-20 15:30 UTC
**While using joined mutations in graphql for updating configurable items, Cart Price Rules not working as expected**   

### Preconditions (*)

1. latest magento 

### Steps to reproduce (*)
make sure you have active cart price rule (for example 20% OFF Ever $200-plus purchase!*  with magento sampledata )
```
mutation UpdateConfigurableOptions(
  $cartId: String!
  $cartItemId: Int!
  $parentSku: String!
  $variantSku: String!
  $quantity: Float!
) {
  addConfigurableProductsToCart(
    input: {
      cart_id: $cartId
      cart_items: [
        {
          data: { quantity: $quantity, sku: $variantSku }
          parent_sku: $parentSku
        }
      ]
    }
  ) {
    cart {
      id
      total_quantity
      available_payment_methods {
        code
        title
      }
      prices {
        grand_total {
          value
          currency
        }
      }
    }
  }
  removeItemFromCart(input: { cart_id: $cartId, cart_item_id: $cartItemId }) {
    cart {
      id
      total_quantity
      available_payment_methods {
        code
        title
      }
      prices {
        grand_total {
          value
          currency
        }
      }
    }
  }
}

variables
{
  "cartId":"HrDsuEYzcAfHDtP7Cy09Vhf0gbI0VgVU",
  "cartItemId":13,
  "parentSku":"WJ01",
  "variantSku":"WJ01-S-Red",
  "quantity":2
}
```

### Expected result (*)
```
{
  "data": {
    "addConfigurableProductsToCart": {
      "cart": {
        "id": "Pz3Jd1hiXGFXfuKYTGE6hGyDGYJFYAm3",
        "total_quantity": 3,
        "available_payment_methods": [
          {
            "code": "checkmo",
            "title": "Check / Money order"
          }
        ],
        "prices": {
          "grand_total": {
            "value": 180,
            "currency": "USD"
          }
        }
      }
    },
    "removeItemFromCart": {
      "cart": {
        "id": "Pz3Jd1hiXGFXfuKYTGE6hGyDGYJFYAm3",
        "total_quantity": 2,
        "available_payment_methods": [
          {
            "code": "checkmo",
            "title": "Check / Money order"
          }
        ],
        "prices": {
          "grand_total": {
            "value": 150,
            "currency": "USD"
          }
        }
      }
    }
  }
}
```

### Actual result (*)
```
{
  "data": {
    "addConfigurableProductsToCart": {
      "cart": {
        "id": "Pz3Jd1hiXGFXfuKYTGE6hGyDGYJFYAm3",
        "total_quantity": 3,
        "available_payment_methods": [
          {
            "code": "checkmo",
            "title": "Check / Money order"
          }
        ],
        "prices": {
          "grand_total": {
            "value": 180,
            "currency": "USD"
          }
        }
      }
    },
    "removeItemFromCart": {
      "cart": {
        "id": "Pz3Jd1hiXGFXfuKYTGE6hGyDGYJFYAm3",
        "total_quantity": 2,
        "available_payment_methods": [
          {
            "code": "checkmo",
            "title": "Check / Money order"
          }
        ],
        "prices": {
          "grand_total": {
            "value": 120,
            "currency": "USD"
          }
        }
      }
    }
  }
}
```
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-08-30 09:40
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-09-06 05:09
Hi @shikhamis11 ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue in graphql. coupon is applied successfully for configurable options update. Kindly recheck the behavior on Magento 2.4-develop branch and provide the exact graphql query which you have used if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-09-20 04:51
Hi @shikhamis11 ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-09-20 04:51 UTC
Labels: Priority: P1, Project: GraphQL, PAP, Progress: done, Issue: ready for confirmation, Issue: needs update
