### ISSUE TITLE
Cannot View Admin area Product Catalog after increasing pagination count

### ISSUE THREAD

**Issue by mehh** [magento/magento2#7573] opened 2016-11-26 02:46 UTC
1. Magento 2.1.2 Production
2. PHP 7.0.13
3. mysql  Ver 14.14 Distrib 5.6.34, for Linux (x86_64) using  EditLine wrapper

### Steps to reproduce

1. Log into Magento admin
2. Navigate to Sales > Orders
3. Increase "Per Page" count to new larger number (I've tried 30,50,100,200)
4. Wait for page to refresh
5. "An unexpected error" occurred popup comes up.  
6. Refreshing page, incognito window, logging out and in, nothing will allow me to view product catalog now.

### Expected result

1.  Go to admin, increase per page number, see all those sales listed

### Actual result

1. Logs: (Report Generated)
```a:4:{i:0;s:110:"Item (Magento\Framework\View\Element\UiComponent\DataProvider\Document) with the same ID "319" already exists.";i:1;s:7216:"#0 /home/username/public_html/vendor/magento/framework/Data/Collection/AbstractDb.php(582): Magento\Framework\Data\Collection->addItem(Object(Magento\Framework\View\Element\UiComponent\DataProvider\Document))
#1 /home/username/public_html/vendor/magento/framework/Data/Collection/AbstractDb.php(557): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter(false, false)
#2 /home/username/public_html/vendor/magento/framework/Data/Collection.php(333): Magento\Framework\Data\Collection\AbstractDb->load()
#3 /home/username/public_html/vendor/magento/framework/View/Element/UiComponent/DataProvider/DataProvider.php(250): Magento\Framework\Data\Collection->getItems()
#4 /home/username/public_html/vendor/magento/framework/View/Element/UiComponent/DataProvider/DataProvider.php(284): Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider->searchResultToOutput(Object(Magento\Sales\Model\ResourceModel\Order\Grid\Collection))
#5 /home/username/public_html/vendor/magento/module-ui/Component/Listing.php(37): Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider->getData()
#6 /home/username/public_html/vendor/magento/framework/View/Element/UiComponent/Context.php(227): Magento\Ui\Component\Listing->getDataSourceData()
#7 /home/username/public_html/vendor/magento/framework/View/Element/UiComponent/ContentType/Json.php(69): Magento\Framework\View\Element\UiComponent\Context->getDataSourceData(Object(Magento\Ui\Component\Listing))
#8 /home/username/public_html/vendor/magento/module-ui/Component/AbstractComponent.php(155): Magento\Framework\View\Element\UiComponent\ContentType\Json->render(Object(Magento\Ui\Component\Listing), 'templates/listi...')
#9 /home/username/public_html/vendor/magento/module-ui/Controller/Adminhtml/Index/Render.php(32): Magento\Ui\Component\AbstractComponent->render()
#10 /home/username/public_html/var/generation/Magento/Ui/Controller/Adminhtml/Index/Render/Interceptor.php(24): Magento\Ui\Controller\Adminhtml\Index\Render->execute()
#11 /home/username/public_html/vendor/magento/framework/App/Action/Action.php(102): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->execute()
#12 /home/username/public_html/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#13 /home/username/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#14 /home/username/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callParent('dispatch', Array)
#15 /home/username/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Ui\\Cont...', 'dispatch', Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Array, 'adminAuthentica...')
#16 /home/username/public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#17 /home/username/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 /home/username/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Ui\\Cont...', 'dispatch', Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Array, 'Bronto_Connecto...')
#19 /home/username/public_html/vendor/bronto/magento-module-connector/Plugin/Allow.php(34): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#20 /home/username/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Bronto\Connector\Plugin\Allow->aroundDispatch(Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#21 /home/username/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Ui\\Cont...', 'dispatch', Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Array, 'adminMassaction...')
#22 /home/username/public_html/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#23 /home/username/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#24 /home/username/public_html/var/generation/Magento/Ui/Controller/Adminhtml/Index/Render/Interceptor.php(52): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callPlugins('dispatch', Array, Array)
#25 /home/username/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#26 /home/username/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#27 /home/username/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#28 /home/username/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#29 /home/username/public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#30 /home/username/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#31 /home/username/public_html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#32 /home/username/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#33 /home/username/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#34 /home/username/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#35 {main}";s:3:"url";s:290:"/username_admin/mui/index/render/key/f4dc0dcd64625da00d5a20e2db428bee7f1b481e2ddbedf74408583427c7ca49/?namespace=sales_order_grid&search=&filters%5Bplaceholder%5D=true&paging%5BpageSize%5D=100&paging%5Bcurrent%5D=1&sorting%5Bfield%5D=increment_id&sorting%5Bdirection%5D=desc&isAjax=true";s:11:"script_name";s:10:"/index.php";}```

<!--- (This may be platform independent comment) -->

**Comment by yaroslavGoncharuk** [comment] 2016-11-29 15:52
@mehh Thanks for reporting this issue. 

We cannot reproduce this issue as described.
In addition, identify, please:
-  the web browser you are using
- the amount of orders you have
- if you have any extensions
- special options in Magento Configuration
- are you running clear 2.1.2 installation or upgraded from any previous version?

**Comment by vzabaznov** [comment] 2016-12-13 09:12
Hi @mehh , closed as we don't receive update more than 2 week, feel free to write here/reopen or to open new issue

**Closed as completed by vzabaznov** 2016-12-13 09:12 UTC
Labels: bug report, Progress: needs update
