### ISSUE TITLE
Duplicate Simple Product Throws Error: Undefined offset: 0 in SaveHandler.php on line 122

### ISSUE THREAD

**Issue by lee586** [magento/magento2#11532] opened 2017-10-17 23:16 UTC
### Preconditions

1. Magento CE 2.2
2. PHP 7.1.10

### Steps to reproduce

1. Click on an existing simple product in the catalog manager
2. Click the "Save & Duplicate" option

### Expected result

1. The product saves and creates a duplicate item

### Actual result

1. Saves the product but doesn't duplicate it. Throws the following error:
Notice: Undefined offset: 0 in /home/store/public_html/vendor/magento/module-catalog/Model/Category/Link/SaveHandler.php on line 122

**Comment by lee586** [comment] 2017-10-18 03:27
Only able to replicate error on simple products that were created before version 2.2. Products I had created under 2.18 won't duplicate. New products created under 2.2 successfully duplicate.

**Comment by alen9788** [comment] 2017-10-18 10:21
Same issue here for the M2.2 can not duplicate the products. 

After click the " save&duplicate"

Notice: Undefined offset: 0 in /var/www/wowlla.com/vendor/magento/module-catalog/Model/Category/Link/SaveHandler.php on line 122

**Comment by magento-engcom-team** [comment] 2017-10-18 10:30
@lee586, thank you for your report.
We've created internal ticket(s) MAGETWO-82173 to track progress on the issue.

**Comment by hezide** [comment] 2017-10-20 11:10
Same issue on 2.2.0...
Never happened before

**Comment by cih95** [comment] 2017-10-27 08:02
The same problem to me.
after upgrade to 2.2.0

**Comment by keanass** [comment] 2017-10-27 09:05
same problem here 2.2.0 
the product dosen't duplicate and show it saved bu nothing happen with the same error : 
Notice: Undefined offset: 0 in /vendor/magento/module-catalog/Model/Category/Link/SaveHandler.php on line 122

**Comment by keanass** [comment] 2017-10-27 10:14
here is the solution for duplicate product : 
go to your magento root dir then : /vendor/magento/module-catalog/Model/Category/Link/SaveHandler.php

replace the tset in mergeCategoryLinks function by this : 

if ($key === false) {
    $result[] = $newCategoryPosition;
} elseif (isset($oldCategoryPositions[$key])) {
  if(intval($oldCategoryPositions[$key]['position']) != $newCategoryPosition['position']){
    $result[] = $newCategoryPositions[$key];
    unset($oldCategoryPositions[$key]);
  }

}

**Comment by cih95** [comment] 2017-10-28 14:39
When i change the code the result is:
The value specified in the URL Key field would generate a URL that already exists.

To resolve this conflict, you can either change the value of the URL Key field (located in the Search Engine Optimization section) to a unique value, or change the Request Path fields in all locations listed below:

- laptop-asus-rog-g752vy-gc100d-1.html

- kompjutri-i-laptopi/laptopi/laptopi-novi/laptop-asus-rog-g752vy-gc100d-1.html

- gamers-1/gejm-rski-laptopi/laptop-asus-rog-g752vy-gc100d-1.html

**Comment by Userr017** [comment] 2017-10-30 15:45
@keanass , This show for me http error 500 and No data to save. Error log, PHP Parse error:  syntax error, unexpected end of file, expecting function (T_FUNCTION) in /vendor/magento/module-catalog/Model/Category/Link/SaveHandler.php on line 133

I have magento 2.2 same problem duplicate Simple Product doesn't work.

**Comment by cih95** [comment] 2017-11-02 13:00
do anybody have a decision for this problem?

**Comment by sitiodocanoamarelo** [comment] 2017-11-10 13:14
Does anyone knows if is this fixed in 2.2.1 ? I'm also facing this issue in 2.2.0

**Comment by alen9788** [comment] 2017-11-10 15:09
Here we meet with anther issue "Invalid option value" when save the products at MCE 2.2.1

**Comment by okorshenko** [comment] 2017-11-13 23:49
The issue has been fixed and delivered to 2.2-develop branch. Will be available with 2.2.2 release

**Closed as completed by okorshenko** 2017-11-13 23:49 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by fwolfst** [comment] 2017-11-20 18:16
@sitiodocanoamarelo  Same issue here on a 2.2.1 . I confirm the fix given by @keanass works for us. We also have the "follow-up" error about URL rewrites - not sure if that is related. Dealing with imported products I suspect it has something to do with the store_id of relevant attribute_values.

Btw from my experience and code reading, **ugly workaround is to remove the product from all categories** (or all but one?).

**Comment by sitiodocanoamarelo** [comment] 2017-11-22 12:48
Thanks @fwolfst , 
I confirm both advices. 
If I remove all the categories except one the issue is gone.
Fix by @keanass works for me on a 2.2.0 (thanks @keanass ;)

**Comment by magento-engcom-team** [comment] 2018-01-27 03:42
Hi @lee586. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1289 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - b41594122f532f6a89165a70906a5b257562c0df
 - 7369261d82e0e5ad926eaf4ccb2a8def79c4fcbb
 - dce1c66301cdddfee2dc2887f584c333d0b438b2
 - 95ed67ee4adbbd7f3f0107a52da4b9238cf44803
 - 05fcdd1a52c674ea09a34960cea71e73488fbc99
 - 8b1a2972b3f0ddd4713d00055b8d60f737a72ce4
 - 90addb731c3b253d3da4dc564ddf94ac3525bd0f
 - d5c9eef075cd5f4d9781ec7f3151a14e087d061d
 - 6ec62717c16ed96d45e670d7f867b724f0449aaa
 - f0af87edad79b295b4be87f6f92502bacfbc2764
 - 2497062749bf41c80aaebb9b6cd21eb48656f58c
 - 1f7347f47cca48238f9deabd48a0a280bc0c309f
 - 0d151c41539ba7c4d20ede20d614bb4be257903c
 - 07982fdea19074788654c6e825874cb8188ab627
 - 617da6ca08607890779ce71530a2871438c88351
 - 39ed21f83071ebffd71963e9097ecb59fd906702
 - 9aa036dec42211867f68f714a746b71395c43bb2
 - fda37ef0af75e6b28d4a0da1781b19c7a7894a97
 - 47b109180b6b5e499ba8d82e6c67888fca21ffe8
 - ef6badace5c6b046047a6e5f617020f9d4410a82
 - 809ec050986fa3ddfeec4a715ce5ace1e41a4427

The fix will be available with the upcoming patch release.

**Comment by lalitmalav** [comment] 2018-10-23 06:00
configurable  products ......Save and Duplicated product not working??

Throws the following error:
Notice: Undefined offset: 0 in /home/store/public_html/vendor/magento/module-catalog/Model/Category/Link/SaveHandler.php on line 122


do you have any  solution ??

**Comment by shoetrees** [comment] 2019-01-15 16:37
still broken in 2.3, fix not working.
