### ISSUE TITLE
Applying and then canceling a coupon covering the whole order amount causes shipping price to display 0

### ISSUE THREAD

**Issue by oskar-olaussen** [magento/magento2#36763] opened 2023-01-20 14:32 UTC
### Preconditions and environment

Magento version 2.4.5-p1

Create a cart price rule with a coupon code and following setup 
![Screenshot from 2023-01-20 16-22-45](https://user-images.githubusercontent.com/82803128/213721987-5aa03c28-01ac-4f0b-af82-e85035c4673c.png)

### Steps to reproduce

1. Have a quote that is cheaper than the coupon discount that is created.
2. Select some shipping method. Go to payment step. Looks like this:
![Screenshot from 2023-01-20 16-28-19](https://user-images.githubusercontent.com/82803128/213723100-75d07677-8b43-41c7-97ad-e80ee201b1d7.png)

4. On the payment step apply the discount code. Looks like this after this step;
![Screenshot from 2023-01-20 16-26-18](https://user-images.githubusercontent.com/82803128/213722684-46b14a0e-5f83-4d4e-bab8-4bb85df93acc.png)

5. Cancel the coupon.

### Expected result

The shipping cost is set back to original price in summary.

### Actual result

The shipping price is shown as 0 on summary.

![Screenshot from 2023-01-20 16-30-07](https://user-images.githubusercontent.com/82803128/213723384-9912783e-efdf-4763-935a-3fe1bc1c5c17.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by oskar-olaussen** [comment] 2023-01-25 11:14
This issue seems to be worse than expected since it also stops the customer from ordering as the shipping_method is set to null on quote_address.
![Screenshot from 2023-01-25 13-13-44](https://user-images.githubusercontent.com/82803128/214549137-ab8f90d9-5a8c-4ddb-8ce4-bd7b81d1ab65.png)

**Comment by engcom-Alfa** [comment] 2023-02-03 09:51
Hi @oskar-olaussen 

Thanks for reporting the ticket.

as per our retesting of this ticket on the 2.4-develop branch which is updated amongs all the branches, we are not able to reproduce this issue.

Video Attachment:
https://user-images.githubusercontent.com/51679138/216568704-2c78a309-1562-4b78-b86a-421b8df3a381.mov

**Comment by engcom-Alfa** [comment] 2023-02-17 13:45
Hi @oskar-olaussen 
since we did not find any response for the last 2 weeks, hence closing the ticket.

Thanks

**Closed as completed by engcom-Alfa** 2023-02-17 13:45 UTC
Labels: Issue: needs update, Area: Cart & Checkout, Area: Promotion, Reported on 2.4.5-p1
