### ISSUE TITLE
Flash message appears everywhere with Varnish

### ISSUE THREAD

**Issue by jsakars** [magento/magento2#5376] opened 2016-06-30 11:02 UTC
## Steps to reproduce
1. Install Magento 2.0.7
2. Setup Varnish4
3. Add product to the cart or perform any other action that triggers flash message
## Expected result
1. Each flash message is shown only once
## Actual result
1. The same flash message is shown in all pages when I continue to navigate through site

This issue is present only when Varnish is enabled. This bug was mentioned 2 month ago already on [http://magento.stackexchange.com/](http://magento.stackexchange.com/questions/110561/magento2-and-varnish-always-delivers-flash-messages)

**Comment by lukeconvertdigital** [comment] 2016-07-01 05:28
Where are you terminating SSL?

**Comment by jsakars** [comment] 2016-07-01 05:56
@helloitsluke nowhere - we don't have SSL currently

**Comment by LiamFielding** [comment] 2016-07-07 08:02
My messages are showing everywhere and multiple times without SSL. I haven't done anything to setup Varnish either - simply installed from dev branch.

**Comment by sevos1984** [comment] 2016-09-28 13:45
This was fixed in 2.0.8, try updating your code base

**Comment by jsakars** [comment] 2016-09-28 13:57
@sevos1984 we are using 2.0.8 - issue is still present. For example, I can see flash message for `product added to the cart` in CMS page

**Comment by sevos1984** [comment] 2016-09-29 10:07
Have you tried 2.0.9. This looks like https://github.com/magento/magento2/issues/4336 https://github.com/magento/magento2/issues/4186 https://github.com/magento/magento2/issues/3503 that are fixed already. Check that you have respective commits.

**Comment by sevos1984** [comment] 2016-10-13 08:39
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-10-13 08:39 UTC
Labels: bug report, Progress: needs update, Component: Framework/Cache, Component: Customer
