### ISSUE TITLE
Datepicker does show the wrong date after saving a price rule, CMS page and on other cases aswell on a Dutch locale

### ISSUE THREAD

**Issue by mdehaan** [magento/magento2#29627] opened 2020-08-18 09:45 UTC
### Preconditions (*)
1. Magento 2.4
2. Admin interface language set to Dutch for the currently logged in admin.

### Steps to reproduce (*)
1. Create a catalog price rule and set the start date to 18-08-2020 and end date 31-08-2020 and save it.

### Expected result (*)
1. After the price rule is saved and when opening it again then the start date should be 18-08-2020 and end date should be 31-08-2020.

### Actual result (*)
1.  After the price rule is saved and when opening it again then the start date is 20-08-2018 and the end date is 20-08-2031.

- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Catalog price rule - Dutch locale: Before save**
![catalog price rule pre save - Dutch locale](https://user-images.githubusercontent.com/581336/90491711-97d9a080-e140-11ea-837f-944179e12d15.PNG)

**Catalog price rule - Dutch locale: After save**
![catalog price rule after save - Dutch locale](https://user-images.githubusercontent.com/581336/90491717-9ad49100-e140-11ea-8cf8-bd2b9402e1be.PNG)

**Catalog price rule - English US locale: After save**
![catalog price rule after save - English US locale](https://user-images.githubusercontent.com/581336/90491722-9c9e5480-e140-11ea-9979-20ada31dfb4a.PNG)

**Comment by engcom-Delta** [comment] 2020-08-27 13:00
Hello @mdehaan 
I am not able to reproduce this issue on the latest 2.4-develop branch by provided steps. 
Could you confirm my steps are correct?

*Testing scenario:*
**Preconditions** 

1. Magento 2.4
2. Admin interface language set to Dutch for the currently logged in admin.

**Steps to reproduce:**

1. Create a catalog price rule
2. Set the start date to 18-08-2020 (or today's date)
2. Save the rule
3. Open for editing this catalog rule

**Result:**
The start date is 18-08-2020 and end date is 31-08-2020.
![Peek 2020-08-27 15-57](https://user-images.githubusercontent.com/51681379/91445060-48048300-e87e-11ea-8cc7-41748d4e4a7e.gif)

**Comment by engcom-Delta** [comment] 2020-10-12 13:21
@mdehaan  Issue is reproducible after recheck on 2.4-develop
![image](https://user-images.githubusercontent.com/51681379/95750768-48c66c80-0ca6-11eb-9a45-cebee581c411.png)
There is similar issue already confirmed https://github.com/magento/magento2/issues/30382
Closed as **Duplicate**

**Closed as completed by engcom-Delta** 2020-10-12 13:21 UTC
Labels: duplicate, Issue: Format is valid, Progress: done, Reported on 2.4.0
