### ISSUE TITLE
Magento2: Default value is not working of Date type product attribute?

### ISSUE THREAD

**Issue by Puru2016** [magento/magento2#33488] opened 2021-07-15 08:59 UTC
### Preconditions (*)
1.  Magento ver 2.3.1

### Steps to reproduce (*)
1. Create Date Type Product Attribute using - Admin -> Stores -> Attributes -> Product -> Add New Attribute -> Select Input Type: Date, Advanced Attribute Properties -> Select any Default Value and save
Storefront Properties -> Select Yes to be visible on Front end
2. Clear cache, cache flush & reindex
3. Navigate to Admin -> Catalog -> Products -> Edit any existing Product -> Expand Attributes section -> newly added date field is not displayed
4. Click on Add Attribute -> Select the newly created Attribute -> Add Selected. **Default Date is not visible in Attribute section. Blank Date field is displayed on selecting the attribute**
**Note:** No issue while creating new products - Default date value is displayed on selecting the attribute
5. Select the date and save the existing product
6. Navigate to Fronend - product Details page

![2jElo](https://user-images.githubusercontent.com/20985181/125746146-b0930f1e-4221-4612-83e5-8ff9fe58c0f6.png)

### Expected result (*)

1. Default date should be visible on each product in admin as well as available for each product on front end.

![2021-07-15_14-18](https://user-images.githubusercontent.com/20985181/125758853-8344093c-9658-4e32-bd90-655a9be517e0.png)

### Actual result (*)
**Issue 1:** Default Date is not visible in Attribute section. Blank Date field is displayed on selecting the attribute
Note: No issue while creating new products - Default date value is displayed on selecting the attribute
**Issue 2:** Front-end - When default date is saved, incorrect date is getting displayed on Front end. Date value - One day before original date(saved) is getting displayed
![2021-07-15_14-21](https://user-images.githubusercontent.com/20985181/125759696-aaba4070-9d08-4b75-a72b-e11bbd80c397.png)

For more details about the issue, please check this [comment](https://github.com/magento/magento2/issues/33488#issuecomment-881201813)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Puru2016** [comment] 2021-07-16 05:25
@engcom-November Any update on this? or let me know if you required more information in this.

**Comment by engcom-November** [comment] 2021-07-16 06:07
Verified the issue on Magento 2.4-develop branch and the issue is reproducible with below steps followed:
1. Admin -> Stores -> Attributes -> Product -> Add New Attribute -> Select Input Type: Date, Advanced Attribute Properties -> Select any Default Value and save 
Storefront Properties -> Select Yes to be visible on Front end
2. Clear cache, cache flush & reindex
3. Navigate to Admin -> Catalog -> Products -> Edit any existing Product -> Expand Attributes section -> **newly added date field is not displayed**
4. Click on Add Attribute -> Select the newly created Attribute -> Add Selected
**Issue 1: Default Date is not getting displayed. Blank Date field is displayed**
![image](https://user-images.githubusercontent.com/60198231/125900193-ddcbafaf-c007-4feb-83f3-6f1f75fa2e93.png)

Note: No issue while creating new products - Default date value is displayed while adding the attribute
5. Select the date and save the existing product
6. Navigate to Fronend - product Details page
**Issue 2: Date - Incorrect date is getting displayed. Date value - One day before original date(saved) is getting displayed**
![image](https://user-images.githubusercontent.com/60198231/125900067-598ceebf-f992-4261-a818-e047daf2af0b.png)
![image](https://user-images.githubusercontent.com/60198231/125900147-a87f7316-0a7d-485e-9338-25ad8716123f.png)

**Configuration:**
![image](https://user-images.githubusercontent.com/60198231/125900251-ddd5616f-07c2-466e-aae8-033cfdeed6a6.png)
![image](https://user-images.githubusercontent.com/60198231/125900288-d4d6d094-3f35-4d94-b04b-d22ae65cca7e.png)

**Comment by magento-engcom-team** [comment] 2021-07-16 06:10
:white_check_mark: Confirmed by @engcom-November 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42860` were created

**Issue Available**: @engcom-November, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by viniciusbord9** [comment] 2021-07-24 01:10
@Magento I am working on this

**Comment by Kannakiraj123** [comment] 2021-09-06 14:09
@magento I am working on this

**Comment by Kannakiraj123** [comment] 2021-09-06 14:14
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-07-30 08:17
Hi @Puru2016,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="968" alt="Screenshot 2024-07-30 at 13 44 16" src="https://github.com/user-attachments/assets/e99c4c1a-430e-4869-90b9-5c8cbaa0b27f">


<img width="968" alt="Screenshot 2024-07-30 at 13 44 41" src="https://github.com/user-attachments/assets/745196d6-2d7e-4280-894b-8c8c8ad096fe">


Hence we are  closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-30 08:17 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done, Component: Attributes, Reported on 2.3.1, Area: Product
