### ISSUE TITLE
Magento 2.4..3-p1|2 PayflowPro perofrms $0 authorization charge

### ISSUE THREAD

**Issue by 0xMatt** [magento/magento2#35600] opened 2022-06-09 15:24 UTC
### Preconditions and environment

- Magento version - 2.4.3-p2

On a fresh install of magento 2.4.3-p1 or p2, I enter my paypal credentials and attempt to perform an authorization charge.

The AMT sent is always $0. causing the authorization to fail. This is not the prior secure token transaction request for $0 which does succeed.

### Steps to reproduce

- Fresh install Magento 2.4.3.p1|p2
- Install sample data
- Plug in PayPal Payflow Pro credentials, set to test mode. Submit a credit card order with their test cards
- Place order

### Expected result

Order is placed with the correct AMT sent to paypal

### Actual result

AMT sent is always $0. Here's a Payflow Pro response dump with some omitted personal data.

> [2022-06-09 15:14:37] main.DEBUG: array (
  'PayPal PayflowPro response:' => 
  array (
    'SECURETOKEN' => '7US94OXWkPkKYhiXOicEDBQAR',
    'STATE' => '***',
    'CITYTOSHIP' => '***',
    'COUNTRYTOSHIP' => 'US',
    'AVSDATA' => 'XXN',
    'AMT' => '0.00',
    'BILLTOCITY' => '***L',
    'ACCT' => '****',
    'BILLTOEMAIL' => 'user',
    'BILLTOSTREET' => '***',
    'SHIPTOCITY' => '***',
    'FIRSTNAME' => 'user',
    'NAMETOSHIP' => 'user'
    'RESULT' => '12',
    'ZIP' => '71913,
    'BILLTOSTATE' => 'AR',
    'BILLTOLASTNAME' => 'user',
    'BILLTOCOUNTRY' => 'US',
    'EXPDATE' => '****',
    'BILLTOFIRSTNAME' => 'user',
    'EMAIL' => 'user',
    'RESPMSG' => 'Declined: 10606-Transaction cannot be processed.',
    'CARDTYPE' => '0',
    'STATETOSHIP' => 'AR',
    'SHIPTOZIP' => 'zip',
    'NAME' => user',
    'BILLTOZIP' => 'zip',
    'COUNTRY' => 'US',
    'ADDRESS' => '***',
    'BILLTONAME' => 'user',
    'PNREF' => '***',
    'ZIPTOSHIP' => 'zip',
    'ADDRESSTOSHIP' => '***',
    'SECURETOKENID' => '***',
    'SHIPTOCOUNTRY' => 'US',
    'SHIPTOSTREET' => '***',
    'CITY' => '***',
    'SHIPTOSTATE' => 'ca',
    'TRANSTIME' => '2022-06-09 08:14:33',
    'HOSTCODE' => '10606',
    'LASTNAME' => 'user',
  ),
) [] []

Express checkout works without any issue and sends the correct amounts. 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by 0xMatt** [comment] 2022-06-09 15:25
@magento give me 2.4-develop instance

**Comment by 0xMatt** [comment] 2022-06-09 15:28
https://github.com/magento give me 2.4-develop instance

**Comment by 0xMatt** [comment] 2022-06-09 16:43
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-06-13 08:13
Hi @0xMatt ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch and the issue is reproducible for payflow pro payment method:
For other payment methods, AMT field is correctly sent
![image](https://user-images.githubusercontent.com/60198231/173309323-e8fff253-0799-497e-9113-2b0d7a6911ae.png)

**Comment by 0xMatt** [comment] 2022-06-13 15:29
Thank you for verifying my report. I will keep an eye out for the patch that resolves this.

**Comment by 0xMatt** [comment] 2022-06-16 16:53
Any update on this? Remember, only Test Mode is affected by this.

**Comment by Sharmilasrini95** [comment] 2022-08-16 13:15
Still issue exist in v2.4.4

**Comment by engcom-November** [comment] 2022-08-24 16:57
Hi @0xMatt ,
We re verified the issue again on Magento 2.4-develop branch and it has been concluded that Authorization charge $0 is expected behavior but not a bug. Payflow payment is working fine in test mode and after successful payment 4 entries are triggered in payment.log file. 2 entries are the authorization request and redirect sent to paypal which verifies only whether vendor is eligible for the transaction and 3rd entry is the response of the same. 4th entry is the actual payment details request/response where AMT is being correctly sent. Kindly check the behavior again on Magento 2.4-develop branch and provide your inputs on this issue.
Thank you.

**Comment by 0xMatt** [comment] 2022-08-25 17:18
@magento give me 2.4-develop instance

**Comment by 0xMatt** [comment] 2022-08-25 17:39
@engcom-November - There is no such thing as a $0 authorization. There is a $0 transaction to get the secure token, however this is not an authorization request. 

My cart does not have a $0 subtotal, yet the AMT sent is 0. This is causing a failure.

Failure is reproduced on the environment above @engcom-November - Please gather the logs and delete the instance when done.

**Comment by 0xMatt** [comment] 2022-08-25 18:00
Here is the payload sent we get back from paypal in https://8912a941823360ea11005047624e5ef9.instances.magento-community.engineering/paypal/transparent/redirect/:

```array(39) {
  ["SECURETOKEN"]=>
  string(25) "5vTUfuSkf9kmH5ic2IwaYtQgw"
  ["STATE"]=>
  string(2) "AR"
  ["CITYTOSHIP"]=>
  string(20) "Hot Springs"
  ["COUNTRYTOSHIP"]=>
  string(2) "US"
  ["AVSDATA"]=>
  string(3) "XXN"
  ["AMT"]=>
  string(4) "0.00"
  ["BILLTOCITY"]=>
  string(20) "Hot Springs"
  ["ACCT"]=>
  string(4) "4242"
  ["BILLTOSTREET"]=>
  string(16)  "123 Sesame St"
  ["SHIPTOCITY"]=>
  string(20) "Hot Springs"
  ["FIRSTNAME"]=>
  string(7) "Matthew"
  ["NAMETOSHIP"]=>
  string(15) "Matthew Javelet"
  ["RESULT"]=>
  string(2) "12"
  ["ZIP"]=>
  string(5) "71913"
  ["BILLTOSTATE"]=>
  string(2) "AR"
  ["BILLTOLASTNAME"]=>
  string(7) "Javelet"
  ["BILLTOCOUNTRY"]=>
  string(2) "US"
  ["EXPDATE"]=>
  string(4) "0126"
  ["BILLTOFIRSTNAME"]=>
  string(7) "Matthew"
  ["RESPMSG"]=>
  string(48) "Declined: 10606-Transaction cannot be processed."
  ["CARDTYPE"]=>
  string(1) "0"
  ["STATETOSHIP"]=>
  string(2) "AR"
  ["SHIPTOZIP"]=>
  string(5) "71913"
  ["NAME"]=>
  string(15) "Matthew Javelet"
  ["BILLTOZIP"]=>
  string(5) "71913"
  ["COUNTRY"]=>
  string(2) "US"
  ["ADDRESS"]=>
  string(16) "120 Rockreef Cir"
  ["BILLTONAME"]=>
  string(15) "Matthew Javelet"
  ["PNREF"]=>
  string(12) "B20P3A7D49A4"
  ["ZIPTOSHIP"]=>
  string(5) "71913"
  ["ADDRESSTOSHIP"]=>
  string(16)  "123 Sesame St"
  ["SECURETOKENID"]=>
  string(32) "8eSbMNphFbZYs264r3vrwFrT0NQ72nko"
  ["SHIPTOCOUNTRY"]=>
  string(2) "US"
  ["SHIPTOSTREET"]=>
  string(16) "123 Sesame St"
  ["CITY"]=>
  string(20) "Hot Springs"
  ["SHIPTOSTATE"]=>
  string(2) "AR"
  ["TRANSTIME"]=>
  string(19) "2022-08-25 10:48:06"
  ["HOSTCODE"]=>
  string(5) "10606"
  ["LASTNAME"]=>
  string(7) "Javelet"
}```

Notice the 0.00 AMT. This is the issue. This issue is not present in PayPal Express Checkout. That works. The issue is only with credit cards using Payflow Pro as configured in the demo above.

I've hard coded the AMT in my own local instance and it works just fine that way.

**Comment by 0xMatt** [comment] 2022-08-25 18:33
Actually, hard coding the amount no longer succeeds. I still get the same error message on my end. I double checked that Test Mode was enabled. Tried multiple cards. I cannot get CC payments to pass at all. Same exact configuration and it works with PayPal Express.

**Comment by 0xMatt** [comment] 2022-08-25 18:43
I'm also able to confirm this on multiple US-based merchant accounts on fresh vanilla 2.4-develop instances.

**Comment by engcom-November** [comment] 2022-08-30 07:06
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-08-30 08:47
Hi @0xMatt ,
Verified the behavior again on Magento 2.4-develop cloud instance but payflow pro payment is working fine in test mode. Please find the video attached of the same.
Test configuration details used:
Partner: PayPal
User: MksGLTest
Vendor: MksGLTest
Pass: Abcd@123
https://user-images.githubusercontent.com/60198231/187392060-9365d62a-665e-4aa9-a49f-adc815855069.mp4

**Comment by Sharmilasrini95** [comment] 2022-08-30 11:30
Can you share the patch file of this fix

**Comment by 0xMatt** [comment] 2022-08-30 15:06
@engcom-November Verified there is no issue with the credentials you provided. Must be something to do with my PayPal account. I've contacted them and am closing this ticket as it's apparently tied to my merchant accounts.

**Comment by Sharmilasrini95** [comment] 2022-08-30 15:25
But still i am facing this issue in Magento 2.4.4.

**Comment by Sharmilasrini95** [comment] 2022-08-30 15:31
Hi 

I am getting below response when i am trying the payment via payflowpro.

I am using the test mode

  'PayPal PayflowPro response:' =>
  array (
    'SECURETOKEN' => '1sOft3K71MEyoJ267YSvOTgEV',
    'STATE' => 'TN',
    'CITYTOSHIP' => 'Nashville',
    'COUNTRYTOSHIP' => 'US',
    'AVSDATA' => 'XXN',
    **'AMT' => '0.00',**
    'BILLTOCITY' => 'Nashville',
    'ACCT' => '****',
    'BILLTOSTREET' => '123 Page road',
    'SHIPTOCITY' => 'Nashville',
    'FIRSTNAME' => 'Sharmila',
    'NAMETOSHIP' => 'Sharmila',
    'RESULT' => '12',
    'ZIP' => '37205',
    'BILLTOSTATE' => 'TN',
    'BILLTOLASTNAME' => 'Srini',
    'BILLTOCOUNTRY' => 'US',
    'EXPDATE' => '****',
    'BILLTOFIRSTNAME' => 'Sharmila',
    **'RESPMSG' => 'Declined: 10606-Transaction cannot be processed.',**
    'CARDTYPE' => '0',
    'STATETOSHIP' => 'TN',
    'SHIPTOZIP' => '37205',
    'NAME' => 'sharmila srini',
    'BILLTOZIP' => '37205',
    'COUNTRY' => 'US',
    'ADDRESS' => '123 Page road',
    'BILLTONAME' => 'Sharmila',
    'PNREF' => 'B90P0ECB56F3',
    'ZIPTOSHIP' => '37205',
    'ADDRESSTOSHIP' => '123 Page road',
    'SECURETOKENID' => 'ELmBjrdmXCvP0jCQLWI2QFpHkWjZPXiD',
    'SHIPTOCOUNTRY' => 'US',
    'SHIPTOSTREET' => '123 Page road',
    'CITY' => 'Nashville',
    'SHIPTOSTATE' => 'TN',
    'TRANSTIME' => '2022-08-30 08:28:40',
    'HOSTCODE' => '10606',
    'LASTNAME' => 'Srini',
  ),
) [] []

**Comment by 0xMatt** [comment] 2022-09-04 12:16
@Sharmilasrini95 the AMT isn't the issue. Seems something changed on PayPal's end. If you use the test credentials from @engcom-November you'll see the transaction succeed. 

However, the transaction does get marked as suspected fruad and requires review from an admin. I'm going to open for your sake and for @engcom-November to let us know if there are any changes we need to make on the PayPal end to get these to go through.

**Comment by engcom-November** [comment] 2022-09-05 11:40
Verified the issue again on Magento 2.4-develop branch and I see Order status is Processing after transaction succeed with Payflow Pro. PFA screenshots of the same and configuration used. Kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
![image](https://user-images.githubusercontent.com/60198231/188440190-1f2590c1-7089-45d5-9166-4af5ee2206fd.png)
![image](https://user-images.githubusercontent.com/60198231/188440571-4f17f76c-f2a6-476c-a53d-d4f9dbaa747f.png)

![image](https://user-images.githubusercontent.com/60198231/188440495-87629069-1b63-44b6-b79e-aadd2ed501b0.png)

**Comment by shubham-lade** [comment] 2022-09-06 11:04
Hello,

         We are facing the same issue with **transactions declined** for test mode. our Magento setup version 2.4.2
         Below are the details which are added to the log.

                 'PayPal PayflowPro redirect:' => 
          array (
            'SECURETOKEN' => '**************************',
            'STATE' => 'MI',
            'CITYTOSHIP' => 'SCHILLER PARK',
            'COUNTRYTOSHIP' => 'US',
            'AVSDATA' => 'XXN',
            **'AMT' => '0.00',**
            'BILLTOCITY' => 'ANN ARBOR',
            'ACCT' => '****',
            'BILLTOEMAIL' => '***************@****.com',
            'BILLTOSTREET' => '3027 MILLER RD',
            'SHIPTOCITY' => 'SCHILLER PARK',
            'FIRSTNAME' => '**************',
            'NAMETOSHIP' => '************',
            'RESULT' => '12',
            'ZIP' => '481032122',
            'BILLTOSTATE' => 'MI',
            'BILLTOLASTNAME' => '******',
            'BILLTOCOUNTRY' => 'US',
            'EXPDATE' => '****',
            'BILLTOFIRSTNAME' => '********** *********',
            'EMAIL' => '***********@****.com',
            **'RESPMSG' => 'Declined: 1***6-Transaction cannot be processed.',**
            'CARDTYPE' => '0',
            'STATETOSHIP' => 'IL',
            'SHIPTOZIP' => '60176',
            'NAME' => '*********** ***** ******',
            'BILLTOZIP' => '481032122',
            'COUNTRY' => 'US',
            'ADDRESS' => '3027 MILLER RD',
            'BILLTONAME' => '*********** ***** ******',
            'PNREF' => 'B50P0F9DB7F5',
            'ZIPTOSHIP' => '60176',
            'ADDRESSTOSHIP' => '9525 IRVING PARK RD',
            'SECURETOKENID' => '**************************',
            'SHIPTOCOUNTRY' => 'US',
            'SHIPTOSTREET' => '9525 IRVING PARK RD',
            'CITY' => 'ANN ARBOR',
            'SHIPTOSTATE' => 'IL',
            'TRANSTIME' => '2022-08-29 00:58:27',
            'HOSTCODE' => '*******',
            'LASTNAME' => '*********',
          ),
    
         Please provide a fix for this.

Thanks.

**Comment by engcom-November** [comment] 2022-09-07 08:17
Hi @shubham-lade , Can you please check if the issue is with test configuration used. Unable to reproduce the issue on Magento 2.4-develop branch with below configuration. Please refer the [comment](https://github.com/magento/magento2/issues/35600#issuecomment-1231361391). Kindly check on 2.4-develop and provide exact steps to reproduce if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-09-21 11:44
Hi @shubham-lade ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-09-21 11:44 UTC
Labels: Component: Paypal, Priority: P1, Progress: done, Issue: needs update, Area: Payments, Reported on 2.4.3-p2

**Comment by gitchrisqueen** [comment] 2022-10-21 20:15
We are having the same issue on Magento 2.4.3-p1. The $0 initial authorization is causing the second authorization with the correct order amount to fail from paypal. Paypal returns a erro r117 - Failed Merchant Rule Check. Please see payament.log from test transaction.

[2022-10-20 18:03:29] report.DEBUG: array (
  'request' => 
  array (
    'user' => '****',
    'vendor' => 'ReadNow1502',
    'partner' => 'PayPalCA',
    'pwd[14]' => 'CpP=$ecure1502',
    'verbosity' => 'HIGH',
    'BUTTONSOURCE' => 'Magento_2_Enterprise',
    'tender' => 'C',
    'trxtype' => 'A',
    'amt' => 0,
    'currency' => 'CAD',
    'createsecuretoken' => 'Y',
    'securetokenid' => 'JE2l2eMJuCUbK70vg02WLvaNmLmanM7V',
    'returnurl' => 'https://mag242-us.firstbook.org/dashboardSMCP/paypal/transparent/redirect/key/c4eeca0bcf3b4948d572107c6f2b036747cec03dad27ee9fd8b43364437e6e5b/',
    'errorurl' => 'https://mag242-us.firstbook.org/dashboardSMCP/paypal/transparent/redirect/key/c4eeca0bcf3b4948d572107c6f2b036747cec03dad27ee9fd8b43364437e6e5b/',
    'cancelurl' => 'https://mag242-us.firstbook.org/dashboardSMCP/paypal/transparent/redirect/key/c4eeca0bcf3b4948d572107c6f2b036747cec03dad27ee9fd8b43364437e6e5b/',
    'disablereceipt' => 'TRUE',
    'silenttran' => 'TRUE',
    'firstname' => 'Semetics',
    'lastname' => 'Sam',
    'street' => '101 C st',
    'city' => 'montrel',
    'state' => 'MB',
    'zip' => 'GA1',
    'country' => 'CA',
    'email' => 'daklkdlsl@gmail.com',
    'shiptofirstname' => 'Semetics',
    'shiptolastname' => 'Sam',
    'shiptostreet' => '101 C st',
    'shiptocity' => 'montrel',
    'shiptostate' => 'MB',
    'shiptozip' => 'GA1',
    'shiptocountry' => 'CA',
  ),
  'result' => 
  array (
    'result' => '0',
    'securetoken' => '4mdwUGfoBPUiZkuMqtna9gQN4',
    'securetokenid' => 'JE2l2eMJuCUbK70vg02WLvaNmLmanM7V',
    'respmsg' => 'Approved',
    'result_code' => '0',
  ),
) [] []
[2022-10-20 18:03:41] report.DEBUG: array (
  'request' => 
  array (
    'user' => '****',
    'vendor' => 'ReadNow1502',
    'partner' => 'PayPalCA',
    'pwd[14]' => 'CpP=$ecure1502',
    'verbosity' => 'HIGH',
    'BUTTONSOURCE' => 'Magento_2_Enterprise',
    'tender' => 'C',
    'custref' => '8000582462',
    'invnum' => '8000582462',
    'comment1' => '8000582462',
    'firstname' => 'Semetics',
    'lastname' => 'Sam',
    'street' => '101 C st',
    'city' => 'montrel',
    'state' => 'MB',
    'zip' => 'GA1',
    'country' => 'CA',
    'email' => 'daklkdlsl@gmail.com',
    'shiptofirstname' => 'Semetics',
    'shiptolastname' => 'Sam',
    'shiptostreet' => '101 C st',
    'shiptocity' => 'montrel',
    'shiptostate' => 'MB',
    'shiptozip' => 'GA1',
    'shiptocountry' => 'CA',
    'trxtype' => 'A',
    'origid' => 'B70PB0FE7CC5',
    'amt' => '44.87',
    'currency' => 'CAD',
    'itemamt' => '32.73',
    'taxamt' => '2.14',
    'freightamt' => '10.00',
    'discount' => '0.00',
  ),
  'result' => 
  array (
    'result' => '117',
    'pnref' => 'B10PB28CDE88',
    'respmsg' => 'Failed merchant rule check',
    'transtime' => '2022-10-20 11:03:41',
    'firstname' => 'Semetics',
    'lastname' => 'Sam',
    'amt' => '44.87',
    'cardtype' => '0',
    'result_code' => '117',
  ),
) [] []

**Comment by gitchrisqueen** [comment] 2022-10-21 20:18
We are having the same issue on Magento 2.4.3-p1. The $0 initial authorization is causing the second authorization with the correct order amount to fail from paypal. Paypal returns a erro r117 - Failed Merchant Rule Check. Please see payament.log from test transaction.

array (
'request' =>
array (
'user' => '',
'vendor' => 'removed',
'partner' => 'removed',
'pwd[14]' => 'removed',
'verbosity' => 'HIGH',
'BUTTONSOURCE' => 'Magento_2_Enterprise',
'tender' => 'C',
'trxtype' => 'A',
'amt' => 0,
'currency' => 'CAD',
'createsecuretoken' => 'Y',
'securetokenid' => 'JE2l2eMJuCUbK70vg02WLvaNmLmanM7V',
'returnurl' => 'url removed/',
'errorurl' => 'url removed',
'cancelurl' => 'url removed',
'disablereceipt' => 'TRUE',
'silenttran' => 'TRUE',
'firstname' => 'Semetics',
'lastname' => 'Sam',
'street' => '101 C st',
'city' => 'montrel',
'state' => 'MB',
'zip' => 'GA1',
'country' => 'CA',
'email' => '[daklkdlsl@gmail.com](mailto:daklkdlsl@gmail.com)',
'shiptofirstname' => 'Semetics',
'shiptolastname' => 'Sam',
'shiptostreet' => '101 C st',
'shiptocity' => 'montrel',
'shiptostate' => 'MB',
'shiptozip' => 'GA1',
'shiptocountry' => 'CA',
),
'result' =>
array (
'result' => '0',
'securetoken' => '4mdwUGfoBPUiZkuMqtna9gQN4',
'securetokenid' => 'JE2l2eMJuCUbK70vg02WLvaNmLmanM7V',
'respmsg' => 'Approved',
'result_code' => '0',
),
) [] []
array (
'request' =>
array (
'user' => '',
'vendor' => 'removed',
'partner' => 'removed',
'pwd[14]' => 'removed',
'verbosity' => 'HIGH',
'BUTTONSOURCE' => 'Magento_2_Enterprise',
'tender' => 'C',
'custref' => '8000582462',
'invnum' => '8000582462',
'comment1' => '8000582462',
'firstname' => 'Semetics',
'lastname' => 'Sam',
'street' => '101 C st',
'city' => 'montrel',
'state' => 'MB',
'zip' => 'GA1',
'country' => 'CA',
'email' => '[daklkdlsl@gmail.com](mailto:daklkdlsl@gmail.com)',
'shiptofirstname' => 'Semetics',
'shiptolastname' => 'Sam',
'shiptostreet' => '101 C st',
'shiptocity' => 'montrel',
'shiptostate' => 'MB',
'shiptozip' => 'GA1',
'shiptocountry' => 'CA',
'trxtype' => 'A',
'origid' => 'B70PB0FE7CC5',
'amt' => '44.87',
'currency' => 'CAD',
'itemamt' => '32.73',
'taxamt' => '2.14',
'freightamt' => '10.00',
'discount' => '0.00',
),
'result' =>
array (
'result' => '117',
'pnref' => 'B10PB28CDE88',
'respmsg' => 'Failed merchant rule check',
'transtime' => '2022-10-20 11:03:41',
'firstname' => 'Semetics',
'lastname' => 'Sam',
'amt' => '44.87',
'cardtype' => '0',
'result_code' => '117',
),
) [] []
