### ISSUE TITLE
Magento 2.4.5-p1 sort by position oldest is diplayed first

### ISSUE THREAD

**Issue by Jilco** [magento/magento2#36692] opened 2022-12-31 11:14 UTC
### Preconditions and environment

- Magento 2.4.5-p1
- Elasticsearch 7

### Steps to reproduce

1. Add a few products to same category with all the same position (e.g. 0)
2. See category in frontend

### Expected result

Newest product (highest ID) is displayed first

### Actual result

Oldest product is displayed first

### Additional information

Of course it is possible to give al the products a different position, but then you have to modify each category when adding new product. And that is al lot of work when having a lot of categories

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Jilco** [comment] 2022-12-31 11:15
@magento give me 2.4.5-p1 instance

**Comment by Jilco** [comment] 2022-12-31 11:21
@magento give me 2.4-develop instance

**Comment by Jilco** [comment] 2022-12-31 11:29
Cannot login to admin (see below)

![image](https://user-images.githubusercontent.com/23727130/210135062-18702e15-c156-4c82-bd03-8e94fcf8b05f.png)

**Comment by engcom-Bravo** [comment] 2023-01-02 10:57
Hi @Jilco,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**
1.Add a few products to same category with all the same position (e.g. 0)
2.See category in frontend.



<img width="1308" alt="Screenshot 2023-01-02 at 12 56 43 PM" src="https://user-images.githubusercontent.com/51680745/210222221-674456ae-3dd5-487d-9384-737deef15877.png">




<img width="1393" alt="Screenshot 2023-01-02 at 12 56 36 PM" src="https://user-images.githubusercontent.com/51680745/210222240-3d37654e-6809-411c-99a1-77c8428a99e4.png">


Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.


Thanks.

**Comment by Jilco** [comment] 2023-01-02 18:07
@engcom-Bravo is the problem solved in 2.4-develop and so was it stil there in 2.4.5-p1?

**Comment by engcom-Bravo** [comment] 2023-01-03 07:25
Hi @Jilco,

Thanks for your update.

it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.

Issue might got fixed in Magento `2.4 develop`.


Thanks.

**Comment by Jilco** [comment] 2023-01-03 08:30
@engcom-Bravo Thanks for the respons. The update will be in march and so i want to change the files in 2.4.5-p1 for the next months

**Comment by engcom-Bravo** [comment] 2023-01-04 12:46
Hi @Jilco,

Thanks for your update.

The issue will get resolved in Magento `2.4.6`.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-01-16 06:06
Hi @Jilco,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-01-16 06:06 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1
