### ISSUE TITLE
Null order in Print All Shipments guest page (Magento\Sales\Block\Order\PrintShipment.php)

### ISSUE THREAD

**Issue by themystery404** [magento/magento2#28861] opened 2020-06-24 07:22 UTC
### Preconditions (*)

1. Magento v2.3.4

### Steps to reproduce (*)

1. Place an order as guest user and create shipment for it.
2. Go to http://example.com/sales/guest/shipment/order_id/123456/
3. Change tab on "Order Shipment".
4. Click on "Print All Shipment" link

### Expected result (*)

1.  All the shipments are printed without any errors

### Actual result (*)

1. All the shipments are printed, but an error with following message is generated:

[04-May-2020 21:27:20 UTC] PHP Fatal error: Uncaught Error: Call to a member function getRealOrderId() on null in /magento2/vendor/magento/module-sales/Block/Order/PrintOrder/Shipment.php:98

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by swathishs** [comment] 2020-06-24 13:10
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-24 13:10
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-06-24 13:11
Hi @swathishs, here is your [Magento instance](https://i-28861-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28861-2-4-develop.instances.magento-community.engineering/admin_2b00](https://i-28861-2-4-develop.instances.magento-community.engineering/admin_2b00)
Login: `1a890239` Password: `c00b075abafb`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment] 2020-06-24 13:27
Hi, @themystery404 : Could you please let me know how to recreate the issue. So that I can able to recreate the issue.

I tried to recreate with these steps:
1. Place an order as a guest user 
2.  Go to admin
3. Click on sales- order
4. In order to click on the shipment 
5. Sales- shipment 
6. Click on print.

Attachments:

1. Shipment:
![image](https://user-images.githubusercontent.com/58288685/85564497-f2c4af00-b64b-11ea-8801-2403578d24b7.png)


2. Able to print shipment:
![image](https://user-images.githubusercontent.com/58288685/85564450-e7718380-b64b-11ea-926f-b64f29979165.png)

**Comment by swathishs** [comment] 2020-06-24 13:29
Refer this ticket - [https://github.com/magento/magento2/issues/9830](url)

**Comment by swathishs** [comment] 2020-06-24 13:32
Duplicate of #https://github.com/magento/magento2/issues/9830

**Comment by themystery404** [comment] 2020-06-25 10:11
@swathishs it's not duplicate - it's the same issue, but for not registered user in the guest page  http://example.com/sales/guest/shipment/order_id/123456/

Shipment is printing, but in your logs you can see an error PHP Fatal.

Try to print your shipment for not registered user from storefront

**Comment by swathishs** [comment] 2020-06-25 10:37
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-25 10:37
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-06-25 10:38
Hi @swathishs, here is your [Magento instance](https://i-28861-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28861-2-4-develop.instances.magento-community.engineering/admin_d7cc](https://i-28861-2-4-develop.instances.magento-community.engineering/admin_d7cc)
Login: `c9cf5d5b` Password: `03c4fa23c05e`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment] 2020-06-25 19:38
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-25 19:38
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-06-25 19:40
Hi @sdzhepa, here is your [Magento instance](https://i-28861-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28861-2-4-develop.instances.magento-community.engineering/admin_40d3](https://i-28861-2-4-develop.instances.magento-community.engineering/admin_40d3)
Login: `7c77698e` Password: `d8a5f62c9535`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment] 2020-06-25 19:59
Hello @themystery404 
fyi: @swnsma 

I am also not able to reproduce this on the lates `2.4-develop` code.
It seems the issue was already fixed and we can close this report and related PR



### Precondition
- create simple product
- place order with this simple product on Storefront as Guest Customer(e.g. Order id 000000001)
- Go to Admin Panel and create Shippment for this order

### Steps
1. Go to Storefront as a Guest
2. Scroll down to the footer and click Order and Returns link (url example : https://magento/sales/guest/form/ )
3. Fill "Order ID", "Billing Last Name", "Find Order By = Email" and "Email"
4. Click "Continue"
5. Result: Order details page is opened, URL: https://magento/sales/guest/shipment/order_id/81/
6. Click to open Order Shipments tab
7. Click all links related to print PDF and save docs:
-- Print All Shipments
-- Print Shipment
-- Print Order


![2020-06-25_14-51-31](https://user-images.githubusercontent.com/3409584/85789569-789c3500-b6f4-11ea-8622-db134351ee4d.jpg)

Results:
- All PDFs were saved with correct data
- there is no `PHP Fatal error: Uncaught Error: Call to a member function getRealOrderId()` in system.log and exception.log

**Closed as completed by sdzhepa** 2020-06-25 19:59 UTC
Labels: Issue: Format is valid, Reported on 2.3.4
