### ISSUE TITLE
In Contact form ,Submit button and footer not contain space in desktop view

### ISSUE THREAD

**Issue by dipti2jcommerce** [magento/magento2#20300] opened 2019-01-15 11:09 UTC
In Contact form Submit button and footer not contain space in desktop
### Preconditions (*)

1.Magento 2.3 version 
2.Desktop view

### Steps to reproduce (*)

1.Go to contact us link present in footer
2.Form button and footer not have space in desktop view

### Expected result (*)
![2019-01-15_16-37_contact us](https://user-images.githubusercontent.com/18118638/51176863-0fe84080-18e4-11e9-9f83-9d654a70c8a6.jpg)

### Actual result (*)
![2019-01-15_16-34_contact us](https://user-images.githubusercontent.com/18118638/51176874-14acf480-18e4-11e9-8cb7-08aa8c8917c1.jpg)

**Comment by magento-engcom-team** [comment] 2019-01-15 11:09
Hi @dipti2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dipti2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-15 11:10
Hi @irajneeshgupta. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by irajneeshgupta** [comment] 2019-01-15 11:10
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-01-15 11:11
Hi @irajneeshgupta. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-01-15 11:11
Hi @irajneeshgupta, here is your [Magento instance](https://i-20300-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20300-2-3-develop.instances.magento-community.engineering/admin](https://i-20300-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by irajneeshgupta** [comment] 2019-01-15 11:13
@dipti2jcommerce 

i cannot reproduced it.

The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

**Closed as completed by irajneeshgupta** 2019-01-15 11:13 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid
