### ISSUE TITLE
Magento 2 deploy - Error notifications

### ISSUE THREAD

**Issue by Userr017** [magento/magento2#23410] opened 2019-06-25 21:28 UTC
### Preconditions (*)

1. Magento 2.3.1 and 2.3.2
2. PHP 7.2

### Steps to reproduce (*)

1. Run commands:
```
 php bin/magento setup:upgrade
 php bin/magento setup:di:compile
 php bin/magento setup:static-content:deploy -f
```

### Expected result (*)

1. Run command:`php bin/magento setup:static-content:deploy -f`
2. Without error notifications.

### Actual result (*)

1. Run command: `php bin/magento setup:static-content:deploy -f`
2. Error notifications:

Deploy using quick strategy
frontend/Magento/blank/en_US            3618/3887           ==========================>- 93% %   17 secs

```
#0 /*****/*****/*****/vendor/tedivm/jshrink/src/JShrink/Minifier.php(233): JShrink\Minifier->saveRegex()
#1 /*****/*****/*****/vendor/tedivm/jshrink/src/JShrink/Minifier.php(147): JShrink\Minifier->loop()
#2 /*****/*****/*****/vendor/tedivm/jshrink/src/JShrink/Minifier.php(115): JShrink\Minifier->minifyDirectToOutput('/**************...', Array)
#3 /*****/*****/*****/vendor/magento/framework/Code/Minifier/Adapter/Js/JShrink.php(27): JShrink\Minifier::minify('/**************...')
#4 /*****/*****/*****/vendor/magento/framework/View/Asset/PreProcessor/Minify.php(50): Magento\Framework\Code\Minifier\Adapter\Js\JShrink->minify('/**************...')
#5 /*****/*****/*****/vendor/magento/framework/View/Asset/PreProcessor/Pool.php(77): Magento\Framework\View\Asset\PreProcessor\Minify->process(Object(Magento\Framework\View\Asset\PreProcessor\Chain))
#6 /*****/*****/*****/vendor/magento/framework/View/Asset/Source.php(152): Magento\Framework\View\Asset\PreProcessor\Pool->process(Object(Magento\Framework\View\Asset\PreProcessor\Chain))
#7 /*****/*****/*****/vendor/magento/framework/View/Asset/Source.php(105): Magento\Framework\View\Asset\Source->preProcess(Object(Magento\Framework\View\Asset\File))
#8 /*****/*****/*****/vendor/magento/framework/View/Asset/File.php(158): Magento\Framework\View\Asset\Source->getFile(Object(Magento\Framework\View\Asset\File))
#9 /*****/*****/*****/vendor/magento/framework/App/View/Asset/Publisher.php(74): Magento\Framework\View\Asset\File->getSourceFile()
#10 /*****/*****/*****/vendor/magento/framework/App/View/Asset/Publisher.php(62): Magento\Framework\App\View\Asset\Publisher->publishAsset(Object(Magento\Framework\View\Asset\File))
#11 /*****/*****/*****/vendor/magento/module-deploy/Service/DeployStaticFile.php(89): Magento\Framework\App\View\Asset\Publisher->publish(Object(Magento\Framework\View\Asset\File))
#12 /*****/*****/*****/vendor/magento/module-deploy/Service/DeployPackage.php(184): Magento\Deploy\Service\DeployStaticFile->deployFile('public/assets/j...', Array)
#13 /*****/*****/*****/vendor/magento/module-deploy/Service/DeployPackage.php(131): Magento\Deploy\Service\DeployPackage->processFile(Object(Magento\Deploy\Package\PackageFile), Object(Magento\Deploy\Package\Package))
#14 /*****/*****/*****/vendor/magento/module-deploy/Service/DeployPackage.php(102): Magento\Deploy\Service\DeployPackage->deployEmulated(Object(Magento\Deploy\Package\Package), Array, false)
#15 [internal function]: Magento\Deploy\Service\DeployPackage->Magento\Deploy\Service\{closure}()
#16 /*****/*****/*****/vendor/magento/framework/App/State.php(187): call_user_func_array(Object(Closure), Array)
#17 /*****/*****/*****/vendor/magento/module-deploy/Service/DeployPackage.php(103): Magento\Framework\App\State->emulateAreaCode('frontend', Object(Closure))
#18 /*****/*****/*****/vendor/magento/module-deploy/Process/Queue.php(326): Magento\Deploy\Service\DeployPackage->deploy(Object(Magento\Deploy\Package\Package), Array)
#19 /*****/*****/*****/vendor/magento/module-deploy/Process/Queue.php(238): Magento\Deploy\Process\Queue->execute(Object(Magento\Deploy\Package\Package))
#20 /*****/*****/*****/vendor/magento/module-deploy/Process/Queue.php(215): Magento\Deploy\Process\Queue->executePackage(Object(Magento\Deploy\Package\Package), 'frontend/Magent...', Array, false)
#21 /*****/*****/*****/vendor/magento/module-deploy/Process/Queue.php(168): Magento\Deploy\Process\Queue->assertAndExecute('frontend/Magent...', Array, Array)
#22 /*****/*****/*****/vendor/magento/module-deploy/Strategy/QuickDeploy.php(76): Magento\Deploy\Process\Queue->process()
#23 /*****/*****/*****/vendor/magento/module-deploy/Service/DeployStaticContent.php(114): Magento\Deploy\Strategy\QuickDeploy->deploy(Array)
#24 /*****/*****/*****/setup/src/Magento/Setup/Console/Command/DeployStaticContentCommand.php(140): Magento\Deploy\Service\DeployStaticContent->deploy(Array)
#25 /*****/*****/*****/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DeployStaticContentCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /*****/*****/*****/vendor/symfony/console/Application.php(893): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /*****/*****/*****/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\DeployStaticContentCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /*****/*****/*****/vendor/magento/framework/Console/Cli.php(105): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /*****/*****/*****/vendor/symfony/console/Application.php(145): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /*****/*****/*****/bin/magento(23): Symfony\Component\Console\Application->run()
```
frontend/Magento/blank/en_US            3887/3887           ============================ 100% %  25 secs
adminhtml/Magento/backend/en_US         4154/4625           =========================>-- 89% %   21 secs
```
#0 /*****/*****/*****/vendor/tedivm/jshrink/src/JShrink/Minifier.php(233): JShrink\Minifier->saveRegex()
#1 /*****/*****/*****/vendor/tedivm/jshrink/src/JShrink/Minifier.php(147): JShrink\Minifier->loop()
#2 /*****/*****/*****/vendor/tedivm/jshrink/src/JShrink/Minifier.php(115): JShrink\Minifier->minifyDirectToOutput('/**************...', Array)
#3 /*****/*****/*****/vendor/magento/framework/Code/Minifier/Adapter/Js/JShrink.php(27): JShrink\Minifier::minify('/**************...')
#4 /*****/*****/*****/vendor/magento/framework/View/Asset/PreProcessor/Minify.php(50): Magento\Framework\Code\Minifier\Adapter\Js\JShrink->minify('/**************...')
#5 /*****/*****/*****/vendor/magento/framework/View/Asset/PreProcessor/Pool.php(77): Magento\Framework\View\Asset\PreProcessor\Minify->process(Object(Magento\Framework\View\Asset\PreProcessor\Chain))
#6 /*****/*****/*****/vendor/magento/framework/View/Asset/Source.php(152): Magento\Framework\View\Asset\PreProcessor\Pool->process(Object(Magento\Framework\View\Asset\PreProcessor\Chain))
#7 /*****/*****/*****/vendor/magento/framework/View/Asset/Source.php(105): Magento\Framework\View\Asset\Source->preProcess(Object(Magento\Framework\View\Asset\File))
#8 /*****/*****/*****/vendor/magento/framework/View/Asset/File.php(158): Magento\Framework\View\Asset\Source->getFile(Object(Magento\Framework\View\Asset\File))
#9 /*****/*****/*****/vendor/magento/framework/App/View/Asset/Publisher.php(74): Magento\Framework\View\Asset\File->getSourceFile()
#10 /*****/*****/*****/vendor/magento/framework/App/View/Asset/Publisher.php(62): Magento\Framework\App\View\Asset\Publisher->publishAsset(Object(Magento\Framework\View\Asset\File))
#11 /*****/*****/*****/vendor/magento/module-deploy/Service/DeployStaticFile.php(89): Magento\Framework\App\View\Asset\Publisher->publish(Object(Magento\Framework\View\Asset\File))
#12 /*****/*****/*****/vendor/magento/module-deploy/Service/DeployPackage.php(184): Magento\Deploy\Service\DeployStaticFile->deployFile('public/assets/j...', Array)
#13 /*****/*****/*****/vendor/magento/module-deploy/Service/DeployPackage.php(131): Magento\Deploy\Service\DeployPackage->processFile(Object(Magento\Deploy\Package\PackageFile), Object(Magento\Deploy\Package\Package))
#14 /*****/*****/*****/vendor/magento/module-deploy/Service/DeployPackage.php(102): Magento\Deploy\Service\DeployPackage->deployEmulated(Object(Magento\Deploy\Package\Package), Array, false)
#15 [internal function]: Magento\Deploy\Service\DeployPackage->Magento\Deploy\Service\{closure}()
#16 /*****/*****/*****/vendor/magento/framework/App/State.php(187): call_user_func_array(Object(Closure), Array)
#17 /*****/*****/*****/vendor/magento/module-deploy/Service/DeployPackage.php(103): Magento\Framework\App\State->emulateAreaCode('adminhtml', Object(Closure))
#18 /*****/*****/*****/vendor/magento/module-deploy/Process/Queue.php(326): Magento\Deploy\Service\DeployPackage->deploy(Object(Magento\Deploy\Package\Package), Array)
#19 /*****/*****/*****/vendor/magento/module-deploy/Process/Queue.php(238): Magento\Deploy\Process\Queue->execute(Object(Magento\Deploy\Package\Package))
#20 /*****/*****/*****/vendor/magento/module-deploy/Process/Queue.php(215): Magento\Deploy\Process\Queue->executePackage(Object(Magento\Deploy\Package\Package), 'adminhtml/Magen...', Array, false)
#21 /*****/*****/*****/vendor/magento/module-deploy/Process/Queue.php(168): Magento\Deploy\Process\Queue->assertAndExecute('adminhtml/Magen...', Array, Array)
#22 /*****/*****/*****/vendor/magento/module-deploy/Strategy/QuickDeploy.php(76): Magento\Deploy\Process\Queue->process()
#23 /*****/*****/*****/vendor/magento/module-deploy/Service/DeployStaticContent.php(114): Magento\Deploy\Strategy\QuickDeploy->deploy(Array)
#24 /*****/*****/*****/setup/src/Magento/Setup/Console/Command/DeployStaticContentCommand.php(140): Magento\Deploy\Service\DeployStaticContent->deploy(Array)
#25 /*****/*****/*****/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DeployStaticContentCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /*****/*****/*****/vendor/symfony/console/Application.php(893): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /*****/*****/*****/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\DeployStaticContentCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /*****/*****/*****/vendor/magento/framework/Console/Cli.php(105): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /*****/*****/*****/vendor/symfony/console/Application.php(145): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```
frontend/Magento/blank/en_US            3887/3887           ============================ 100% %  25 secs
adminhtml/Magento/backend/en_US         4625/4625           ============================ 100% %  32 secs
frontend/Magento/luma/en_US             3619/3903           =========================>-- 92% %   22 secs
```
#0 /*****/*****/*****/vendor/tedivm/jshrink/src/JShrink/Minifier.php(233): JShrink\Minifier->saveRegex()
#1 /*****/*****/*****/vendor/tedivm/jshrink/src/JShrink/Minifier.php(147): JShrink\Minifier->loop()
#2 /*****/*****/*****/vendor/tedivm/jshrink/src/JShrink/Minifier.php(115): JShrink\Minifier->minifyDirectToOutput('/**************...', Array)
#3 /*****/*****/*****/vendor/magento/framework/Code/Minifier/Adapter/Js/JShrink.php(27): JShrink\Minifier::minify('/**************...')
#4 /*****/*****/*****/vendor/magento/framework/View/Asset/PreProcessor/Minify.php(50): Magento\Framework\Code\Minifier\Adapter\Js\JShrink->minify('/**************...')
#5 /*****/*****/*****/vendor/magento/framework/View/Asset/PreProcessor/Pool.php(77): Magento\Framework\View\Asset\PreProcessor\Minify->process(Object(Magento\Framework\View\Asset\PreProcessor\Chain))
#6 /*****/*****/*****/vendor/magento/framework/View/Asset/Source.php(152): Magento\Framework\View\Asset\PreProcessor\Pool->process(Object(Magento\Framework\View\Asset\PreProcessor\Chain))
#7 /*****/*****/*****/vendor/magento/framework/View/Asset/Source.php(105): Magento\Framework\View\Asset\Source->preProcess(Object(Magento\Framework\View\Asset\File))
#8 /*****/*****/*****/vendor/magento/framework/View/Asset/File.php(158): Magento\Framework\View\Asset\Source->getFile(Object(Magento\Framework\View\Asset\File))
#9 /*****/*****/*****/vendor/magento/framework/App/View/Asset/Publisher.php(74): Magento\Framework\View\Asset\File->getSourceFile()
#10 /*****/*****/*****/vendor/magento/framework/App/View/Asset/Publisher.php(62): Magento\Framework\App\View\Asset\Publisher->publishAsset(Object(Magento\Framework\View\Asset\File))
#11 /*****/*****/*****/vendor/magento/module-deploy/Service/DeployStaticFile.php(89): Magento\Framework\App\View\Asset\Publisher->publish(Object(Magento\Framework\View\Asset\File))
#12 /*****/*****/*****/vendor/magento/module-deploy/Service/DeployPackage.php(184): Magento\Deploy\Service\DeployStaticFile->deployFile('public/assets/j...', Array)
#13 /*****/*****/*****/vendor/magento/module-deploy/Service/DeployPackage.php(131): Magento\Deploy\Service\DeployPackage->processFile(Object(Magento\Deploy\Package\PackageFile), Object(Magento\Deploy\Package\Package))
#14 /*****/*****/*****/vendor/magento/module-deploy/Service/DeployPackage.php(102): Magento\Deploy\Service\DeployPackage->deployEmulated(Object(Magento\Deploy\Package\Package), Array, false)
#15 [internal function]: Magento\Deploy\Service\DeployPackage->Magento\Deploy\Service\{closure}()
#16 /*****/*****/*****/vendor/magento/framework/App/State.php(187): call_user_func_array(Object(Closure), Array)
#17 /*****/*****/*****/vendor/magento/module-deploy/Service/DeployPackage.php(103): Magento\Framework\App\State->emulateAreaCode('frontend', Object(Closure))
#18 /*****/*****/*****/vendor/magento/module-deploy/Process/Queue.php(326): Magento\Deploy\Service\DeployPackage->deploy(Object(Magento\Deploy\Package\Package), Array)
#19 /*****/*****/*****/vendor/magento/module-deploy/Process/Queue.php(238): Magento\Deploy\Process\Queue->execute(Object(Magento\Deploy\Package\Package))
#20 /*****/*****/*****/vendor/magento/module-deploy/Process/Queue.php(215): Magento\Deploy\Process\Queue->executePackage(Object(Magento\Deploy\Package\Package), 'frontend/Magent...', Array, false)
#21 /*****/*****/*****/vendor/magento/module-deploy/Process/Queue.php(168): Magento\Deploy\Process\Queue->assertAndExecute('frontend/Magent...', Array, Array)
#22 /*****/*****/*****/vendor/magento/module-deploy/Strategy/QuickDeploy.php(76): Magento\Deploy\Process\Queue->process()
#23 /*****/*****/*****/vendor/magento/module-deploy/Service/DeployStaticContent.php(114): Magento\Deploy\Strategy\QuickDeploy->deploy(Array)
#24 /*****/*****/*****/setup/src/Magento/Setup/Console/Command/DeployStaticContentCommand.php(140): Magento\Deploy\Service\DeployStaticContent->deploy(Array)
#25 /*****/*****/*****/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DeployStaticContentCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /*****/*****/*****/vendor/symfony/console/Application.php(893): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /*****/*****/*****/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\DeployStaticContentCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /*****/*****/*****/vendor/magento/framework/Console/Cli.php(105): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```
frontend/Magento/blank/en_US            3887/3887           ============================ 100% %  25 secs
adminhtml/Magento/backend/en_US         4625/4625           ============================ 100% %  32 secs
frontend/Magento/luma/en_US             3903/3903           ============================ 100% %  33 secs
frontend/Etheme/yourstore/en_US         3618/4075           ========================>--- 88% %   17 secs
```
#0 /*****/*****/*****/vendor/tedivm/jshrink/src/JShrink/Minifier.php(233): JShrink\Minifier->saveRegex()
#1 /*****/*****/*****/vendor/tedivm/jshrink/src/JShrink/Minifier.php(147): JShrink\Minifier->loop()
#2 /*****/*****/*****/vendor/tedivm/jshrink/src/JShrink/Minifier.php(115): JShrink\Minifier->minifyDirectToOutput('/**************...', Array)
#3 /*****/*****/*****/vendor/magento/framework/Code/Minifier/Adapter/Js/JShrink.php(27): JShrink\Minifier::minify('/**************...')
#4 /*****/*****/*****/vendor/magento/framework/View/Asset/PreProcessor/Minify.php(50): Magento\Framework\Code\Minifier\Adapter\Js\JShrink->minify('/**************...')
#5 /*****/*****/*****/vendor/magento/framework/View/Asset/PreProcessor/Pool.php(77): Magento\Framework\View\Asset\PreProcessor\Minify->process(Object(Magento\Framework\View\Asset\PreProcessor\Chain))
#6 /*****/*****/*****/vendor/magento/framework/View/Asset/Source.php(152): Magento\Framework\View\Asset\PreProcessor\Pool->process(Object(Magento\Framework\View\Asset\PreProcessor\Chain))
#7 /*****/*****/*****/vendor/magento/framework/View/Asset/Source.php(105): Magento\Framework\View\Asset\Source->preProcess(Object(Magento\Framework\View\Asset\File))
#8 /*****/*****/*****/vendor/magento/framework/View/Asset/File.php(158): Magento\Framework\View\Asset\Source->getFile(Object(Magento\Framework\View\Asset\File))
#9 /*****/*****/*****/vendor/magento/framework/App/View/Asset/Publisher.php(74): Magento\Framework\View\Asset\File->getSourceFile()
#10 /*****/*****/*****/vendor/magento/framework/App/View/Asset/Publisher.php(62): Magento\Framework\App\View\Asset\Publisher->publishAsset(Object(Magento\Framework\View\Asset\File))
#11 /*****/*****/*****/vendor/magento/module-deploy/Service/DeployStaticFile.php(89): Magento\Framework\App\View\Asset\Publisher->publish(Object(Magento\Framework\View\Asset\File))
#12 /*****/*****/*****/vendor/magento/module-deploy/Service/DeployPackage.php(184): Magento\Deploy\Service\DeployStaticFile->deployFile('public/assets/j...', Array)
#13 /*****/*****/*****/vendor/magento/module-deploy/Service/DeployPackage.php(131): Magento\Deploy\Service\DeployPackage->processFile(Object(Magento\Deploy\Package\PackageFile), Object(Magento\Deploy\Package\Package))
#14 /*****/*****/*****/vendor/magento/module-deploy/Service/DeployPackage.php(102): Magento\Deploy\Service\DeployPackage->deployEmulated(Object(Magento\Deploy\Package\Package), Array, false)
#15 [internal function]: Magento\Deploy\Service\DeployPackage->Magento\Deploy\Service\{closure}()
#16 /*****/*****/*****/vendor/magento/framework/App/State.php(187): call_user_func_array(Object(Closure), Array)
#17 /*****/*****/*****/vendor/magento/module-deploy/Service/DeployPackage.php(103): Magento\Framework\App\State->emulateAreaCode('frontend', Object(Closure))
#18 /*****/*****/*****/vendor/magento/module-deploy/Process/Queue.php(326): Magento\Deploy\Service\DeployPackage->deploy(Object(Magento\Deploy\Package\Package), Array)
#19 /*****/*****/*****/vendor/magento/module-deploy/Process/Queue.php(238): Magento\Deploy\Process\Queue->execute(Object(Magento\Deploy\Package\Package))
#20 /*****/*****/*****/vendor/magento/module-deploy/Process/Queue.php(215): Magento\Deploy\Process\Queue->executePackage(Object(Magento\Deploy\Package\Package), 'frontend/Etheme...', Array, false)
#21 /*****/*****/*****/vendor/magento/module-deploy/Process/Queue.php(168): Magento\Deploy\Process\Queue->assertAndExecute('frontend/Etheme...', Array, Array)
#22 /*****/*****/*****/vendor/magento/module-deploy/Strategy/QuickDeploy.php(76): Magento\Deploy\Process\Queue->process()
#23 /*****/*****/*****/vendor/magento/module-deploy/Service/DeployStaticContent.php(114): Magento\Deploy\Strategy\QuickDeploy->deploy(Array)
#24 /*****/*****/*****/setup/src/Magento/Setup/Console/Command/DeployStaticContentCommand.php(140): Magento\Deploy\Service\DeployStaticContent->deploy(Array)
#25 /*****/*****/*****/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DeployStaticContentCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /*****/*****/*****/vendor/symfony/console/Application.php(893): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /*****/*****/*****/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\DeployStaticContentCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```
frontend/Magento/blank/en_US            3887/3887           ============================ 100% %  25 secs
adminhtml/Magento/backend/en_US         4625/4625           ============================ 100% %  32 secs
frontend/Magento/luma/en_US             3903/3903           ============================ 100% %  33 secs
frontend/Etheme/yourstore/en_US         4075/4075           ============================ 100% %  28 secs

Execution time: 138.10677599907

**Comment by xmav** [comment] 2019-06-25 22:49
@Userr017 
Could you please try to reproduce issue on clean Magento installation ?
(I could not reproduce it with "Minify JavaScript Files=Yes" on clean Magento installation. You might have broken js file in your theme)

**Comment by Userr017** [comment] 2019-06-26 08:00
@xmav 

I installed now clean Magento 2.3.2 with sample data and works without issues (Minify JavaScript Files="Yes").

I disabled Minify JavaScript Files for my website (Minify JavaScript Files="No"). This after deploy works without issues. So this is my custom theme or extension issue. This issue come after updates to latest Magento 2.3.1 files using command "composer update". Same issue is with Magento 2.3.2.

**Comment by engcom-Charlie** [comment] 2019-06-26 08:03
Hello @Userr017 ! Thank you for your report !
If you can confirm that this issue appears just because of your custom theme or 3rd party extension then i`m closing this one.

**Closed as completed** 2019-06-26 08:02 UTC
Labels: Issue: Format is valid

**Comment by clivewalkden** [comment] 2019-06-26 12:13
@Userr017 the issue is with an update to a depedency [tedivm/jshrink](https://github.com/tedious/JShrink) version 1.3.2

I've had the same issue with a third party module calling in moment.js and failing.

If you `composer require tedivm/jshrink:1.3.1` in you magento directory, and retry the static-content deploy it should work again. Could you confirm?

**Comment by engcom-Charlie** [comment] 2019-06-26 12:25
Hello @clivewalkden !
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.

**Comment by hostep** [comment] 2019-06-26 12:31
@clivewalkden or @Userr017: can you open an issue at https://github.com/tedious/JShrink with the exact problem you are having with minifying js files, maybe it was a new bug in their recent 1.3.2 release?

**Comment by Userr017** [comment] 2019-06-26 13:02
@clivewalkden Yes, you are right.

I have this issue come when updated tedivm/jshrink:1.3.1 to version 1.3.2.

**Comment by tedivm** [comment] 2019-06-28 18:15
I've released JShrink 1.3.3 which removes the regression introduced in 1.3.2.

**Comment by cralls** [comment] 2020-01-13 02:41
I'm having this issue on 2.2.6 with either 1.3.1 or 1.3.3. I have all custom extensions disabled. I do have a custom theme. @tedivm any tips on how to debug the issue? The stack trace doesn't really tell me anything and there are no errors logged.

***UPDATE***

What I've done for now to get things working is just commented out the error output on line 529 of vendor/tedivm/jshrink/src/JShrink/Minifier.php

The commented line looks like the following:

//throw new \RuntimeException('Unclosed regex pattern at position: ' . $this->index);

Now it seems to be minifying both CSS and JS successfully where before when it was throwing the error it wasn't.

**Comment by tedivm** [comment] 2020-01-13 20:53
Are you sure the javascript that's coming out of it is valid and error free?

**Comment by cralls** [comment] 2020-01-13 20:57
@tedivm It's probably not, which is why it's throwing the error, I just don't know how to validate it all, there are tons of js files. I have several other Magento 2 sites that I work with that deploy static content with minify on and don't have any issues. What's interesting though is it's throwing the errors with all third party extensions disabled and when trying to compile frontend/Magento/blank/en_US which is the out of the box Magento theme. Unless I've changed something on that theme and don't recall I wouldn't think it would error trying to minify on that theme.

**Comment by sangthieu** [comment] 2020-06-08 08:48
I got problem with angular file (main.bundle.js)
#12 /httpdocs/vendor/magento/module-deploy/Service/DeployPackage.php(184): Magento\Deploy\Service\DeployStaticFile->deployFile('js/main.bundle....', Array)
