### ISSUE TITLE
Warning "Something went wrong" appears every time I try to enable a theme

### ISSUE THREAD

**Issue by mohammadkokash** [magento/magento2#6602] opened 2016-09-13 20:22 UTC
### Preconditions

1. Magento 2.1.0, php 5.6, MariaDB 10
### Steps to reproduce

1. when i press on Content  > Design > Configuration i get the error 
### Expected result

1. list of themes to enable one of them
### Actual result

1. A pop up displays the warning: "Attention. Something went wrong."
2. and when i track the error i find this:

Warning: strtoupper() expects parameter 1 to be string, array given in /home/nibrasac/public_html/magento2.1/vendor/magento/module-ui/Component/Listing/Columns/Column.php on line 136
![attention](https://cloud.githubusercontent.com/assets/22131835/18489958/f9debe14-7a10-11e6-8ca2-9e8b7888cfe0.PNG)
![error](https://cloud.githubusercontent.com/assets/22131835/18489969/077b0ece-7a11-11e6-93d7-9e406b842b9b.PNG)

**Comment by enrico69** [comment] 2016-09-15 19:52
Hi.
Did you add any extra theme? I mean others than Luma and Blank?
Could you temporaly edit the file _magento/module-ui/Component/Listing/Columns/Column.php_ in order to show us a dump of what you get on line 127:

``` PHP
$sorting = $this->getContext()->getRequestParam('sorting');
```

**Comment by mohammadkokash** [comment] 2016-09-15 21:12
Hi 

Thanks for reply, yes i just added the theme files which i bought to be under magento folder but i couldn't enable it as i explained, its my first time to use magento and i didnt instgall it myself its installed using Softaculous auto installer which is provided by hosting provider, normally i go for woocommerce with wordpress.

could you please give me steps on how to get the dump as am not magento developer.

Regards

**Comment by enrico69** [comment] 2016-09-16 06:08
Let's go to the direct way : 
at the beginnig of the _applySorting()_ function, put this:

``` PHP
echo "<pre>" . printr_r($sorting, 1) . "</pre>"; exit;
```

And show the displayed result when you want to list the themes. If necessary, only apply it before you access the listing screen.

**Comment by tkacheva** [comment] 2016-09-27 15:23
@mohammadkokash Are you still facing the same issue? 
If so please provide detailed steps that you are following in magento documentation and on what step you face the issue

**Comment by mohammadkokash** [comment] 2016-09-28 07:08
@tkacheva we didnt go deep to figure out the cause, we re-installed magento2.1 manually instead of using softoculus installer, and i upgraded to php7 on server instead of 5.6 and thats solved the issue.

Thanks

**Comment by veloraven** [comment] 2016-09-29 12:13
I'm closing this issue as ther problem is not actual any more for the reporter.

**Closed as completed by veloraven** 2016-09-29 12:13 UTC
Labels: Progress: needs update, Issue: Format is valid

**Comment by mfdj** [comment] 2017-02-07 21:36
**Suggest to reopen as I'm presently seeing this issue.**

### Preconditions

- magento/product-enterprise-edition: 2.1.3
- PHP 7.0.15

The following "theme" modules:

```
→ composer info | grep theme
magento/module-theme                          100.1.3     N/A
magento/theme-adminhtml-backend               100.1.1     N/A
magento/theme-frontend-blank                  100.1.2     N/A
magento/theme-frontend-luma                   100.1.2     N/A
my-client/theme-frontend-base                     0.1.0   
```

### Steps to reproduce

- I navigate to  Admin > Content > Design > Configuration 
- I see "Something went wrong" and not the table of applied theme configurations
- I check the javascript console and I see that an XHR request failed: 

![screen shot 2017-02-07 at 1 20 23 pm](https://cloud.githubusercontent.com/assets/1110910/22712038/354c50c0-ed38-11e6-9065-272ef170bb7c.png)

### Diagnosis 

The abridged path is `…/admin/mui/index/render/key/{{ key }}/`

Using Chrome's "Copy as cURL" option I can re-run and dump per @enrico69 print_r method:

```
→ curl 'http://…/admin/mui/index/render/key/359caf4b39ed926ae063ab319cd50bb6f0a9147328e57844d05c04a0044368ac/?namespace=design_config_listing&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&paging%5BpageSize%5D%5B%5D=20&paging%5BpageSize%5D%5B%5D=20&paging%5BpageSize%5D%5B%5D=20&paging%5BpageSize%5D%5B%5D=20&paging%5BpageSize%5D%5B%5D=20&paging%5BpageSize%5D%5B%5D=20&paging%5BpageSize%5D%5B%5D=20&paging%5BpageSize%5D%5B%5D=20&paging%5BpageSize%5D%5B%5D=20&paging%5BpageSize%5D%5B%5D=20&paging%5BpageSize%5D%5B%5D=20&paging%5BpageSize%5D%5B%5D=20&paging%5Bcurrent%5D=1&sorting%5Bfield%5D=actions&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&isAjax=true' -H 'Pragma: no-cache' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Referer: http://…/admin/theme/design_config/index/key/d5665551da6cd2d8c08467bb76ea6b446cbadaf778d3eb26a7702c1941ff5f57/' -H 'X-Requested-With: XMLHttpRequest' -H 'Cookie: admin=9qo07eknt7q1npktjhf8pm0u14; XDEBUG_SESSION=XDEBUG_ECLIPSE' -H 'Connection: keep-alive' -H 'Cache-Control: no-cache' --compressed
Array
(
    [field] => actions
    [direction] => Array
        (
            [0] => false
            [1] => false
            [2] => false
            [3] => false
            [4] => false
            [5] => false
            [6] => false
            [7] => false
            [8] => false
            [9] => false
            [10] => false
            [11] => false
            [12] => false
            [13] => false
            [14] => false
            [15] => false
        )
)
```

So obviously `strtoupper($sorting['direction'])` is failing because direction is a list-like array.

Decoding the percent-encoding of the path it's little more clear what the original request looks like:

```
…/admin/mui/index/render/key/359caf4b39ed926ae063ab319cd50bb6f0a9147328e57844d05c04a0044368ac/?namespace=design_config_listing&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&paging[pageSize][]=20&paging[pageSize][]=20&paging[pageSize][]=20&paging[pageSize][]=20&paging[pageSize][]=20&paging[pageSize][]=20&paging[pageSize][]=20&paging[pageSize][]=20&paging[pageSize][]=20&paging[pageSize][]=20&paging[pageSize][]=20&paging[pageSize][]=20&paging[current]=1&sorting[field]=actions&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&isAjax=true
```

And we can see numerous appends like: `sorting[direction][]=false` — the issue may be in the client-side code, although that's as far as I've gotten.

### Update

I quick patched `vendor/magento/module-ui/Component/Listing/Columns/Column.php` as a sanity check

```
        $sorting = $this->getContext()->getRequestParam('sorting');
        if ( ! is_string($sorting)) {
            $sorting = '';
        }
```

And it stops the XHR Request from failing so you don't see "Something went Wrong" error message but the page is still failing to render.

![screen shot 2017-02-07 at 5 41 49 pm](https://cloud.githubusercontent.com/assets/1110910/22719942/d28e77c2-ed5c-11e6-981b-11bf6b724a2c.png)


This makes me suspect the issue in Column.php is just a symptom (presumably could still benefit from some type checking).

Looking at the console the culprit is closer to this:

```
Uncaught TypeError: Unable to process binding "foreach: function (){return {data:elems,as:'element'} }"
Message: Unable to process binding "if: function (){return hasTemplate() }"
Message: Unable to process binding "template: function (){return getTemplate() }"
Message: Cannot read property 'template' of undefined
    at UiClass.getTemplate (listing.js:229)
    at template (eval at createBindingsStringEvaluator (knockout.js:2624), <anonymous>:3:68)
    at init (knockout.js:5023)
    at knockout.js:2989
    at Object.ignore (knockout.js:1249)
    at knockout.js:2988
    at Object.arrayForEach (knockout.js:151)
    at applyBindingsToNodeInternal (knockout.js:2974)
    at applyBindingsToNodeAndDescendantsInternal (knockout.js:2854)
    at applyBindingsToDescendantsInternal (knockout.js:2836)
```

I'm not prepared to jump into Knockout land today, so I'll conclude by reiterating: this is an open issue.


### Update pt. 2 — sort of solution

So after running `bin/magento seutp:uninstall` and then re-installing I was able to stop seeing this issue.

I'm not sure what was happening, but I suspect that this UI bug's root cause is related to an unusual/unexpected database state. I seem to remember this issue started after trying to change some theme stuff. It's hard to say for sure at this point because I didn't snapshot my database before the uninstall. Just speculation. 

Hopefully this helps others.

**Comment by jesslynkoh89** [comment] 2017-03-09 18:56
go to database,
find ui_bookmark table,
delete all entries with "cms_page_listing" in "namespace" column.

NO MORE "$sorting['direction']" error!

This works for me.

Hopefully this helps others.

**Comment by yosmared** [comment] 2017-05-09 15:05
@jesslynkoh89 problem resolved! Thanks!

**Comment by markbiek** [comment] 2017-05-11 16:12
The basic premise of @jesslynkoh89 's solution worked for me but I had to delete `ui_bookmark` entries with a namespace of `design_config_listing`.

Maybe a difference between Magento 2.0 and 2.1?

**Comment by jing-xiao** [comment] 2017-07-27 06:21
I'm working with Magento CE 2.0.15.

Got a file below:
/vendor/magento/module-ui/view/base/web/js/grid/provider.js
line 105 ~ 113
Seems all ajax reload error will trigger this popup.
I think it's better to report this error to console.

**Comment by SchumacherFM** [comment] 2017-11-03 10:17
Also confirmed for 2.2.0 no idea how to reproduce but it pops up sometimes in customer and catalog grid.

**Comment by keyurpatel90** [comment] 2019-02-06 13:38
> **Suggest to reopen as I'm presently seeing this issue.**
> 
> ### Preconditions
> * magento/product-enterprise-edition: 2.1.3
> * PHP 7.0.15
> 
> The following "theme" modules:
> 
> ```
> → composer info | grep theme
> magento/module-theme                          100.1.3     N/A
> magento/theme-adminhtml-backend               100.1.1     N/A
> magento/theme-frontend-blank                  100.1.2     N/A
> magento/theme-frontend-luma                   100.1.2     N/A
> my-client/theme-frontend-base                     0.1.0   
> ```
> ### Steps to reproduce
> * I navigate to  Admin > Content > Design > Configuration
> * I see "Something went wrong" and not the table of applied theme configurations
> * I check the javascript console and I see that an XHR request failed:
> 
> ![screen shot 2017-02-07 at 1 20 23 pm](https://cloud.githubusercontent.com/assets/1110910/22712038/354c50c0-ed38-11e6-9065-272ef170bb7c.png)
> 
> ### Diagnosis
> The abridged path is `…/admin/mui/index/render/key/{{ key }}/`
> 
> Using Chrome's "Copy as cURL" option I can re-run and dump per @enrico69 print_r method:
> 
> ```
> → curl 'http://…/admin/mui/index/render/key/359caf4b39ed926ae063ab319cd50bb6f0a9147328e57844d05c04a0044368ac/?namespace=design_config_listing&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&filters%5Bplaceholder%5D%5B%5D=true&paging%5BpageSize%5D%5B%5D=20&paging%5BpageSize%5D%5B%5D=20&paging%5BpageSize%5D%5B%5D=20&paging%5BpageSize%5D%5B%5D=20&paging%5BpageSize%5D%5B%5D=20&paging%5BpageSize%5D%5B%5D=20&paging%5BpageSize%5D%5B%5D=20&paging%5BpageSize%5D%5B%5D=20&paging%5BpageSize%5D%5B%5D=20&paging%5BpageSize%5D%5B%5D=20&paging%5BpageSize%5D%5B%5D=20&paging%5BpageSize%5D%5B%5D=20&paging%5Bcurrent%5D=1&sorting%5Bfield%5D=actions&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&sorting%5Bdirection%5D%5B%5D=false&isAjax=true' -H 'Pragma: no-cache' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Referer: http://…/admin/theme/design_config/index/key/d5665551da6cd2d8c08467bb76ea6b446cbadaf778d3eb26a7702c1941ff5f57/' -H 'X-Requested-With: XMLHttpRequest' -H 'Cookie: admin=9qo07eknt7q1npktjhf8pm0u14; XDEBUG_SESSION=XDEBUG_ECLIPSE' -H 'Connection: keep-alive' -H 'Cache-Control: no-cache' --compressed
> Array
> (
>     [field] => actions
>     [direction] => Array
>         (
>             [0] => false
>             [1] => false
>             [2] => false
>             [3] => false
>             [4] => false
>             [5] => false
>             [6] => false
>             [7] => false
>             [8] => false
>             [9] => false
>             [10] => false
>             [11] => false
>             [12] => false
>             [13] => false
>             [14] => false
>             [15] => false
>         )
> )
> ```
> So obviously `strtoupper($sorting['direction'])` is failing because direction is a list-like array.
> 
> Decoding the percent-encoding of the path it's little more clear what the original request looks like:
> 
> ```
> …/admin/mui/index/render/key/359caf4b39ed926ae063ab319cd50bb6f0a9147328e57844d05c04a0044368ac/?namespace=design_config_listing&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&filters[placeholder][]=true&paging[pageSize][]=20&paging[pageSize][]=20&paging[pageSize][]=20&paging[pageSize][]=20&paging[pageSize][]=20&paging[pageSize][]=20&paging[pageSize][]=20&paging[pageSize][]=20&paging[pageSize][]=20&paging[pageSize][]=20&paging[pageSize][]=20&paging[pageSize][]=20&paging[current]=1&sorting[field]=actions&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&sorting[direction][]=false&isAjax=true
> ```
> And we can see numerous appends like: `sorting[direction][]=false` — the issue may be in the client-side code, although that's as far as I've gotten.
> 
> ### Update
> I quick patched `vendor/magento/module-ui/Component/Listing/Columns/Column.php` as a sanity check
> 
> ```
>         $sorting = $this->getContext()->getRequestParam('sorting');
>         if ( ! is_string($sorting)) {
>             $sorting = '';
>         }
> ```
> And it stops the XHR Request from failing so you don't see "Something went Wrong" error message but the page is still failing to render.
> 
> ![screen shot 2017-02-07 at 5 41 49 pm](https://cloud.githubusercontent.com/assets/1110910/22719942/d28e77c2-ed5c-11e6-981b-11bf6b724a2c.png)
> 
> This makes me suspect the issue in Column.php is just a symptom (presumably could still benefit from some type checking).
> 
> Looking at the console the culprit is closer to this:
> 
> ```
> Uncaught TypeError: Unable to process binding "foreach: function (){return {data:elems,as:'element'} }"
> Message: Unable to process binding "if: function (){return hasTemplate() }"
> Message: Unable to process binding "template: function (){return getTemplate() }"
> Message: Cannot read property 'template' of undefined
>     at UiClass.getTemplate (listing.js:229)
>     at template (eval at createBindingsStringEvaluator (knockout.js:2624), <anonymous>:3:68)
>     at init (knockout.js:5023)
>     at knockout.js:2989
>     at Object.ignore (knockout.js:1249)
>     at knockout.js:2988
>     at Object.arrayForEach (knockout.js:151)
>     at applyBindingsToNodeInternal (knockout.js:2974)
>     at applyBindingsToNodeAndDescendantsInternal (knockout.js:2854)
>     at applyBindingsToDescendantsInternal (knockout.js:2836)
> ```
> I'm not prepared to jump into Knockout land today, so I'll conclude by reiterating: this is an open issue.
> 
> ### Update pt. 2 — sort of solution
> So after running `bin/magento seutp:uninstall` and then re-installing I was able to stop seeing this issue.
> 
> I'm not sure what was happening, but I suspect that this UI bug's root cause is related to an unusual/unexpected database state. I seem to remember this issue started after trying to change some theme stuff. It's hard to say for sure at this point because I didn't snapshot my database before the uninstall. Just speculation.
> 
> Hopefully this helps others.

This Works for me.
