### ISSUE TITLE
A product attribute type multiple select, not required, is not nullable after a selection has been made.

### ISSUE THREAD

**Issue by PierAlex** [magento/magento2#5225] opened 2016-06-24 13:02 UTC
## Steps to reproduce

Create a product attribute type multiselect not required.
Select an option or more, in the catalog - product - general tab and save.
Edit the product. The selection cannot be deleted. At least one selection is always active for the product. It is not possible to deselect all the options.
![image](https://cloud.githubusercontent.com/assets/17165819/16338033/3f9b3e0a-3a1a-11e6-88ca-e88c98e11527.png)
## Expected result

The expectation is that a previous selection shoud be canceled and that the value of that attribute, not required, shoud be void.
## Actual result

A selection cannot be deselected after it has been made. This means that for a workaround you can set a new value as "none" to be selected instead of a real value but it means that, if this is the only custom attribute active for the product, you always see as visible the tab "more information" in the product catalog detail and in the tab you see the label with value: none.
![image](https://cloud.githubusercontent.com/assets/17165819/16338385/a31517e2-3a1c-11e6-9b32-a7e807fbc22c.png)

**Comment by andimov** [comment] 2016-06-24 13:17
@PierAlex 
Thank you for reporting this issue!
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by PierAlex** [comment] 2016-06-25 11:28
@andimov 
The version is 2.0.7.
Sorry, what do you mean with: "If the problem is actual for a specific tag"?
The system is updated to the latest version.

**Comment by PierAlex** [comment] 2016-06-28 15:11
Installed the 2.1.0 version, not so easily :(, it is already present. You cannot delete your selection once it has been made.

**Comment by andimov** [comment] 2016-06-29 08:54
@PierAlex 
So, this issue also presents in 2.1.0 version?

**Comment by jfern01** [comment] 2016-06-30 19:22
I can confirm this issue is present in 2.1.0.

**Comment by PierAlex** [comment] 2016-07-01 07:03
Yes,it is already present as confirmed by jfern01 (thanks).

**Comment by andimov** [comment] 2016-08-18 17:26
We already have internal ticket MAGETWO-50123 with the same problem.

**Comment by magento-engcom-team** [comment] 2017-09-20 22:22
@PierAlex, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:22 UTC
Labels: Issue: Ready for Work, bug report, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is not valid
