### ISSUE TITLE
Checkout validation usability issue (THE FOLD)

### ISSUE THREAD

**Issue by clarkeverdel** [magento/magento2#8980] opened 2017-03-22 19:17 UTC
Hi Guys,
 
I would like to request a new improvement for the checkout. Currently users could have trouble finding out about invalid fields which disappear above the screen fold.
 
**Scenario:**

1. User fills out his address information
2. Scrolls down below to submit the form and go to the next step.
3. Hey! The button is not working. Weird...
4. When the invalid fields are not visible because they are above the fold, the end user is not notified of the problems with his information. In some cases the user may be smart enough to scroll up and see if there are invalid fields, but you may understand that not every user is thinking about doing that.
 
**Possible solution**

1. Automatically scroll to the first invalid field on the page
2. Notification message below the submit form to inform the user that he has to fill out his invalid forms.
3. I am curious about what you guys think of this user experience issue.

 
Cheers,
Clarke

![screenshots-checkout-notification](https://cloud.githubusercontent.com/assets/13994268/24216440/895f1faa-0f3c-11e7-8982-ceb1eecae43f.png)

**Comment by korostii** [comment] 2017-03-23 12:07
Also reported in #8977

**Comment by KrystynaKabannyk** [comment] 2017-03-29 04:57
@claverwebdesign, thank you for your submission. We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues. Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)). That's why I'm closing the issue.

**Closed as completed by KrystynaKabannyk** 2017-03-29 04:57 UTC
Labels: Component: Checkout, Issue: Format is not valid

**Comment by korostii** [comment] 2017-03-29 08:40
@KrystynaKabannyk, this is definitely not a feature request. I suppose you classify it as a "suggested improvement" ? 

IMHO if the checkout button "is not working" for no VISIBLE reason, that's clearly a massive bug.

If the criteria you happen to have are any different, is there a way we could hear those or someplace we can take a peek at them written down? Could you maybe add the words "bug" and "improvement" to the famous [Magento's Glossary](https://magento.github.io/glossary/) so that we (the mere mortals) could also see difference and understand how is this issue not a bug?

**Comment by korostii** [comment] 2017-03-29 09:33
See also https://community.magento.com/t5/Magento-2-Feature-Requests-and/Checkout-user-experience-improvement-Inform-users-of-invalid/idi-p/55730

Additionally, there is no need to actually close such an issue manually. AFAIK you can just put the label "improvement": there is a script running which will then close the issue with an automatic message AND will copy a discussion into a Communnity topic, otherwise it'll be lost.

**Comment by aholovan** [comment] 2017-08-11 09:02
Hi,
I've implemented automatic scroll to the first invalid field on the shipping page. So, if this improvement is still in progress You are could use my crutch to get better errors behaviour on checkout. I've posted it on forum by the above link in previous message.

**Comment by willfrombrazil** [comment] 2017-10-04 14:57
@KrystynaKabannyk, I believe this is a bug. The validation script should focus the 1st invalid field. See what happens when a customer misspell their email address during checkout: https://youtu.be/7DA-qGrwlt8
Really bad for conversions!
