### ISSUE TITLE
Wrong Url on store switch then logged in

### ISSUE THREAD

**Issue by luckyraul** [magento/magento2#25616] opened 2019-11-15 11:18 UTC
### Preconditions (*)

1. Magento 2.3-develop
2. You have magento in a subfolder (https://www.website.com/shop/)
3. Multistore(2 stores with one store view per each) 

### Steps to reproduce (*)

1. Log in Customer account 
2. Click on the link to switch store

### Expected result (*)

1.  https://www.website.com/shop/stores/store/switchrequest?customer_id=xxxx&time_stamp=1573813960&signature=xxx&___from_store=zzz&uenc=hjhjjh [200 OK]

### Actual result (*)

1. https://www.website.com/stores/store/switchrequest?customer_id=xxxx&time_stamp=1573813960&signature=xxx&___from_store=zzz&uenc=hjhjjh  [404]

It looks like here https://github.com/magento/magento2/blob/2.3/app/code/Magento/Store/Model/StoreSwitcher/HashGenerator.php#L83 Magento get URL from parse_url and hardcode to website root.   It should use store Base URL

**Comment by magento-engcom-team** [comment] 2019-11-18 10:28
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-23225` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Charlie** [comment] 2020-07-02 12:30
Hi @luckyraul,
We are not able to reproduce this issue on the latest 2.4-develop branch by followed scenario:
* 2 _stores_ with one _store view_ per each
* Magento in a subfolder;
1. Login as customer
2. Click on the link to switch store,

**AR**: I'm on the second store view. [200 OK]

![Peek 2020-07-02 15-19](https://user-images.githubusercontent.com/51680850/86358700-992a3900-bc78-11ea-93ed-a3f5ea0f7f5c.gif)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for your collaboration.

Thanks for your report!

**Closed as completed by engcom-Charlie** 2020-07-02 12:30 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Store

**Comment by amenk** [comment] 2021-08-30 14:00
@luckyraul Did you upgrade already to 2.4 and was this fixed for you?

**Comment by amenk** [comment] 2021-08-30 14:01
@engcom-Charlie  Do you have the commit IDs where this was fixed?

**Comment by amenk** [comment] 2021-09-09 13:46
@engcom-Charlie *bump* 
Does anyone know the commit IDs of the fix?

**Comment by amenk** [comment] 2021-09-09 13:50
I think I found something: https://github.com/magento/magento2/commit/c942a64405d9db9665b436ccafa955bd6b08f811
