### ISSUE TITLE
Unable to send email in Magento 2.3.2

### ISSUE THREAD

**Issue by DavidEu000** [magento/magento2#24080] opened 2019-08-09 02:48 UTC
### Preconditions (*)

1. Magento 2.3.2
2. Docker

### Steps to reproduce (*)

1. Sales > Orders > Open any one order.
2. Click on Send mail.
3. Register new customer.
4. Any trigger to send email function.

### Expected result (*)

1. Email should be sent

### Actual result (*)

Fatal error: Uncaught Zend\Mail\Transport\Exception\RuntimeException: Unable to send mail: Unknown error in /usr/share/nginx/html/magento2/vendor/zendframework/zend-mail/src/Transport/Sendmail.php:316 Stack trace: #0 [internal function]: Zend\Mail\Transport\Sendmail->mailHandler('email@example.c...', '=?utf-8?Q?Your=...', '<!DOCTYPE html ...', 'Date: Fri, 09 A...', ' -f'email@example...') #1 /usr/share/nginx/html/magento2/vendor/zendframework/zend-mail/src/Transport/Sendmail.php(135): call_user_func(Array, 'admin@davideu.c...', '=?utf-8?Q?Your=...', '<!DOCTYPE html ...', 'Date: Fri, 09 A...', ' -f'email@example...') #2 /usr/share/nginx/html/magento2/vendor/magento/module-email/Model/Transport.php(99): Zend\Mail\Transport\Sendmail->send(Object(Zend\Mail\Message)) #3 /usr/share/nginx/html/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Email\Model\Transport->sendMessage() #4 /usr/share/nginx/html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Email\Model\Transport\Interc in /usr/share/nginx/html/magento2/vendor/magento/module-email/Model/Transport.php on line 101

### Comments
I found it might be the issue of the $parameters of PHP-Mail /vendor/zendframework/zend-mail/src/Transport/Sendmail.php - line 305: $result = mail($to, $subject, $message, $headers, $parameters); When debugging the $parameters that shows: '-f'email@example.com' then it will not send any email out. But if it changed to '-f email@example.com' then I can receive the email.

**Comment by engcom-Charlie** [comment] 2019-08-09 07:33
Hello @DavidEu000 
I can't reproduce this issue on fresh Magento 2.3-develop.

**Manual testing scenario:**
1. Sales > Orders > Open any one order.
2. Click on Send mail.
3. Go to Customers > All customers(and i tried go to the Customer view and register from this page)
4. Register new customer.
5. Any trigger to send email function.

So i close this issue.
Thank for your report!

**Closed as completed by engcom-Charlie** 2019-08-09 07:33 UTC
Labels: Issue: Clear Description, Issue: Format is valid, Component: Email

**Comment by Partabsaifzakir** [comment] 2020-04-03 19:38
Facing same issue on 2.3.4
