### ISSUE TITLE
REST/DELETE configurable-products/options not working

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#7772] opened 2016-12-13 08:41 UTC
### Preconditions

1. v2.1.2
2. PHP 7.0.11

### Steps to reproduce

1. Create a request with existing configurable product and an existing option which is added to product.
2. Do request (tried with PHP-CGI an CLI)
<pre>curl -i -H "Content-Type: application/json,Authorization: Bearer vik9atqehqvf2btjh2hy3i1c9abt1g9m" -X DELETE http://magento.dev/rest/V1/configurable-products/SKU/options/990364</pre>
<pre>
$ch = curl_init("http://magento.dev/rest/V1/configurable-products/SKU/options/990364");
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "DELETE");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-Type: application/json","Authorization: Bearer vik9atqehqvf2btjh2hy3i1c9abt1g9m"));
        $response=curl_exec($ch);
        if(curl_errno($ch)>0){
            return curl_error($ch);
        }
        curl_close($ch);
        return $response;
</pre>
3. GET and POST working fine with same configuration. PUT not tested yet.
### Expected result

1. Option removed from product

### Actual result

1. CGI Result : <pre>404 error: Page not found.</pre>
2. CLI Result : <pre>HTTP/1.1 404 Not Found
Date: Tue, 13 Dec 2016 08:28:42 GMT
Server: Apache/2.2.31 (Unix) mod_ssl/2.2.31 OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 mod_antiloris/0.4
X-Powered-By: PHP/7.0.11
.............
..........</pre>

**Comment by olysenko** [comment] 2016-12-22 16:58
Hi, thank you for your report. I cannot reproduce  issue with the following steps
1. Install Magento 2.1.2 with sample data
2. Get Token for authorization through API
3.  a) Open in backend a configurable product Chaz Kangeroo Hoodie and remember its SKU: MH01.
b) notice that there are several simple options
4. a) Execute command in CLI to get options id
curl -i -H "Content-Type: application/json" -H "Authorization: Bearer g2oy2jxo96bepui4ir5m0e86u0g563lj" -X GET http://magento2add.local/rest/V1/configurable-products/MH01/options/all
b) The response is
`[{"id":3,"attribute_id":"93","label":"Color","position":0,"values":[{"value_index":49},{"value_index":52},{"value_index":56}],"product_id":67},{"id":2,"attribute_id":"141","label":"Size","position":0,"values":[{"value_index":167},{"value_index":168},{"value_index":169},{"value_index":170},{"value_index":171}],"product_id":67}]`
5.  a)Try to delete relation with id=3 between product_id=67(Chaz Kangeroo Hoodie) and attribute_id=93(Color). By this operation I expected a simple options deletion from configurable product. 
b) Execute command in CLI 
curl -i -H "Content-Type: application/json" -H "Authorization: Bearer g2oy2jxo96bepui4ir5m0e86u0g563lj" -X DELETE http://magento2add.local/rest/V1/configurable-products/MH01/options/3
c) The response is true
6. a) Open in backend a configurable product Chaz Kangeroo Hoodie again. There are no any simple options in it.
May be you have some additional configuration fro your product?

**Comment by cizgidekiadam** [comment] 2017-03-03 14:09
@olysenko That is the matter now.
When i tried to delete option id 3 (Color), it remove all options (including 'Size', id 2). 
So yes, there is not any simple option but I didn't delete 'Size'. Where is it? 😄

**Comment by RogerKeulen** [comment] 2017-09-18 09:45
Hi, there.. I tried to do step 5a with Magento 2.1.7 and got HTTP 404 with HTML.

```
[meen@dev ~]$ curl -i -H "Content-Type: application/json" -H "Authorization: Bearer gie9rn0gu8l7nnk...." -X DELETE http://keen-webshop.nl/rest/V1/configurable-products/MH01/options/3
HTTP/1.1 404 Not Found
Date: Mon, 18 Sep 2017 09:32:07 GMT
Content-Length: 629
Content-Type: **text/html**; charset=UTF-8

<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
    <title>Error 404: Not Found</title>
    <base href="http://keen-webshop.nl/errors/default/" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="*"/>
    <link rel="stylesheet" href="css/styles.css" type="text/css" />
    <link rel="icon" href="images/favicon.ico" type="image/x-icon" />
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
</head>
<body>
    <main class="page-main">

<h1>404 error: Page not found.</h1>
    </main>
</body>
</html>

```

a JSON webserver should always return JSON. 
a XML webservice should always return XML.
**This return is not valid JSON and that is a bug.** 

It's a horrible coding practise that this is even possible to occure. JSON API's should not be bound to a graphical userinterface. That is the whole principle of a web api in the first place.

**Comment by magento-engcom-team** [comment] 2017-10-05 22:05
@rbostan, thank you for your report.
We've created internal ticket(s) MAGETWO-81038 to track progress on the issue.

**Comment by magento-engcom-team** [comment] 2018-07-30 06:14
Hi @rbostan

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment] 2018-08-20 09:02
@rbostan thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Closed as completed by magento-engcom-team** 2018-08-20 09:02 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Issue: Format is valid, triage wanted
