### ISSUE TITLE
Admin Navigation

### ISSUE THREAD

**Issue by arfan456** [magento/magento2#6505] opened 2016-09-06 09:36 UTC
Admin Navigation linkes are not working

**Comment by andimov** [comment] 2016-09-06 09:42
@arfan456
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by voleye** [comment] 2016-09-22 09:08
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by voleye** 2016-09-22 09:08 UTC
Labels: Progress: needs update
