### ISSUE TITLE
stock alert notification for product which has been already disabled

### ISSUE THREAD

**Issue by maharzan86** [magento/magento2#30017] opened 2020-09-13 10:11 UTC
**Preconditions**
Here is environment I am using

Magento version - 2.3.3
PHP Version 7.2.31
MySQL Version 5.7.18

**Steps to reproduce**

1. Make any product out of stock and view the product in front side. 
2. Subscribe for 'Product back in stock' alert.
3. Go to admin panel and make that product back in stock.
4. Also disable that product

**Expected result**
Customer should not get mail with alert of product which is disabled

**Actual result**
Customer get mail with alert that product which is already disabled

**Comment by saphaljha** [comment] 2020-09-13 15:37
@magento I am working on this

**Comment by maharzan86** [comment] 2020-10-05 02:52
@magento  any updates on this?

**Comment by engcom-Alfa** [comment] 2020-11-26 13:06
Hi @maharzan86 . 

Unfortunately, we are not able to reproduce this issue on fresh 2.4-develop.
Everything works as expected.

**Manual testing scenario:**

1. Make any product out of stock and view the product in front side.
2. Subscribe for 'Product back in stock' alert.
3. Go to admin panel and make that product back in stock.
4. Also disable that product
![2020-11-26_14-56](https://user-images.githubusercontent.com/51679138/100353738-a6fda380-2ff7-11eb-955f-b6737f87ec2d.png)

**Actual Result:** :heavy_check_mark: The customer does not receive mail with an alert of product which is disabled

5. Enable that product 

![2020-11-26_15-00](https://user-images.githubusercontent.com/51679138/100354083-3a36d900-2ff8-11eb-8efd-478f4639f842.png)

**Actual Result:** :heavy_check_mark: Customer get mail with alert that product which is enabled

![Screenshot from 2020-11-26 15-01-45](https://user-images.githubusercontent.com/51679138/100354139-55a1e400-2ff8-11eb-8306-3173dff5304b.png)

So, we have to close it.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-11-26 13:06 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.3.3

**Comment by driskell** [comment] 2022-09-27 09:24
Reproducible in 2.4.3

* Make any product out of stock and view the product in front side.
* Subscribe for 'Product back in stock' alert.
* Go to admin panel and make that product back in stock.
* Also disable that product
* **Wait for the product alert schedule to run**
* You get an email

@magento give me 2.4-develop instance

**Comment by erfanimani** [comment] 2025-04-23 06:53
Hi @driskell , did you manage to reproduce it?

I believe it's because of MSI — it seems to intercept the `isSaleable` check in `magento/module-product-alert/Model/ProductSalability.php` and seems to be only concerned with the stock, not the product status: `magento/module-inventory-product-alert/Plugin/AdaptProductSalabilityPlugin.php`.

It might not be reproducible because the Github bot creates an instance without MSI (I could be wrong).

**Comment by driskell** [comment] 2025-04-23 08:05
> Hi [@driskell](https://github.com/driskell) , did you manage to reproduce it?
> 
> I believe it's because of MSI — it seems to intercept the `isSaleable` check in `magento/module-product-alert/Model/ProductSalability.php` and seems to be only concerned with the stock, not the product status: `magento/module-inventory-product-alert/Plugin/AdaptProductSalabilityPlugin.php`.
> 
> It might not be reproducible because the Github bot creates an instance without MSI (I could be wrong).

It was a long time ago - the above message I barely remember so not sure what happened after the instance creation. I think we ended up with some additional behaviour around this so worked around it a long time ago.
