### ISSUE TITLE
Unable to write file into directory: Access forbidden

### ISSUE THREAD

**Issue by peterwdouglas** [magento/magento2#8212] opened 2017-01-20 11:36 UTC
Not sure how to add a pull request so will post it here.

When adding an image to a product, it gives an error as the title says. so the image doesn't save.

To fix:

magento/magento2/blob/2e228234/app/code/Magento/Catalog/Model/View/Asset/Image.php

Change:

public function getPath()
 {
    return $this->getRelativePath($this->context->getPath());
}

replace with:

public function getPath()
{
	$result = $this->context->getPath();
	$result = $this->join($result, $this->getModule());
	$result = $this->join($result, $this->getMiscPath());
	return $this->join($result, $this->getFilePath());
}

This fixes the issue so dont know how to include this in the files to download.

**Comment by thisisapen** [comment] 2017-05-10 08:20
Confirming the same issue as above on 2.1.6 trying to rebuild cache using 'catalog:images:resize'. The above coupled with DIRECTORY_SEPARATOR to '/' helped resolve all image related issues on Windows 10 (WAMP 3.0.6, PHP7.0.10, MySQL 5.7.14).

**Comment by miguelbalparda** [comment] 2017-05-12 10:58
It seems this might be fixed with #9492 can you please try the suggested solution and report back?

**Comment by magento-team** [comment] 2017-08-01 14:58
Internal ticket to track issue progress: MAGETWO-69119

**Comment by magento-engcom-team** [comment] 2017-09-21 12:47
Hi @peterwdouglas 
Looks like you are using Windows server, which is not supported by Magento. If you can reproduce this issue on a supported platform, please, feel free to reopen this issue. For an overview of supported technologies, see [System Requirements](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-2.1-tech.html).

**Closed as completed by magento-engcom-team** 2017-09-21 12:47 UTC
Labels: Issue: Ready for Work, Issue: Format is not valid
