### ISSUE TITLE
How to add multiple dependences using addFieldDependence

### ISSUE THREAD

**Issue by srenon** [magento/magento2#4796] opened 2016-05-31 13:43 UTC
``` php
....
->addFieldMap($field_to_evaluate->getHtmlId(), $field_to_evaluate->getName())
->addFieldMap($field_to_show->getHtmlId(), $field_to_show->getName())
->addFieldDependence
 (
   $field_to_show->getName(),
   $field_to_evaluate->getName(),
   'valueHere'
  )
...
```

In magento 1.x you could accomplish this by doing 

``` php
.....
->addFieldDependence
 (
   $field_to_show->getName(),
   $field_to_evaluate->getName(),
   array('value1', 'value2')
  )
.....
```

They does not seem to be an easy way to accomplish this in magento 2.x, because there is not way to pass in the "separator" argument from addFieldDependence 

magento2/app/code/Magento/Backend/Block/Widget/Form/Element/Dependence.php

``` php
    /**
     * Register field name dependence one from each other by specified values
     *
     * @param string $fieldName
     * @param string $fieldNameFrom
     * @param \Magento\Config\Model\Config\Structure\Element\Dependency\Field|string $refField
     * @return \Magento\Backend\Block\Widget\Form\Element\Dependence
     */
    public function addFieldDependence($fieldName, $fieldNameFrom, $refField)
    {
        if (!is_object($refField)) {
            /** @var $refField \Magento\Config\Model\Config\Structure\Element\Dependency\Field */
            $refField = $this->_fieldFactory->create(
                ['fieldData' => ['value' => (string)$refField], 'fieldPrefix' => '']
            );
        }
        $this->_depends[$fieldName][$fieldNameFrom] = $refField;
        return $this;
    }
```

magento2/app/code/Magento/Config/Model/Config/Structure/Element/Dependency/Field.php

``` php
    /**
     * @param array $fieldData
     * @param string $fieldPrefix
     */
    public function __construct(array $fieldData = [], $fieldPrefix = "")
    {
        if (isset($fieldData['separator'])) {
            $this->_values = explode($fieldData['separator'], $fieldData['value']);
        } else {
            $this->_values = [$fieldData['value']];
        }
        $fieldId = $fieldPrefix . (isset(
            $fieldData['dependPath']
        ) && is_array(
            $fieldData['dependPath']
        ) ? array_pop(
            $fieldData['dependPath']
        ) : '');
        $fieldData['dependPath'][] = $fieldId;
        $this->_id = implode('_', $fieldData['dependPath']);
        $this->_isNegative = isset($fieldData['negative']) && $fieldData['negative'];
    }
```

**Possible solution without editing core would be to create a DI for** `\Magento\Config\Model\Config\Structure\Element\Dependency\FieldFactory $_fieldFactory` then 

``` php
    $refField = $this->_fieldFactory->create(
         ['fieldData' => ['value' => 'dependecy 1,dependecy 2', 'separator' => ','], 'fieldPrefix' => '']
    );

   .......
    ->addFieldDependence
     (
       $field_to_show->getName(),
       $field_to_evaluate->getName(),
       $refField
      )
```

or maybe using xml DI to passing the separator value

**Possible solution with core edit** 

magento2/app/code/Magento/Backend/Block/Widget/Form/Element/Dependence.php

``` php
    /**
     * Register field name dependence one from each other by specified values
     *
     * @param string $fieldName
     * @param string $fieldNameFrom
     * @param \Magento\Config\Model\Config\Structure\Element\Dependency\Field|string $refField
     * @return \Magento\Backend\Block\Widget\Form\Element\Dependence
     */
    public function addFieldDependence($fieldName, $fieldNameFrom, $refField)
    {
        if (!is_object($refField)) {
            /** @var $refField \Magento\Config\Model\Config\Structure\Element\Dependency\Field */
            $refField = $this->_fieldFactory->create(
                //Change from
                //['fieldData' => ['value' => (string)$refField], 'fieldPrefix' => '']
                // To
                ['fieldData' => ['value' => (string)$refField], 'separator' => ','], 'fieldPrefix' => '']
            );
        }
        $this->_depends[$fieldName][$fieldNameFrom] = $refField;
        return $this;
    }
```

Then to add multiple options all you would have to do is

``` php
......
->addFieldDependence
 (
   $field_to_show->getName(),
   $field_to_evaluate->getName(),
   'value1,value2'
  )
...
```

**Comment by GianniPDF** [comment] 2016-07-04 07:29
Not even acknowledged? Maybe this isn't a bug but definitely it is a feature Magento 2 should have (Given the case that Magento 1 has it)

**Comment by koenner01** [comment] 2016-09-15 09:53
Big fan of the solution without the core edit!

**Comment by veloraven** [comment] 2016-11-01 16:37
@srenon 
I'm closing this issue as the GitHub issue tracker is intended for technical issues only. 
Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you think it to be an issue than please create new GitHub report following the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Closed as completed by veloraven** 2016-11-01 16:37 UTC

**Comment by tahir-unioncoop** [comment] 2021-09-09 06:43
This solution worked for me 

https://magento.stackexchange.com/questions/110404/how-to-make-the-fields-of-the-fieldset-multidependable
