### ISSUE TITLE
Visual Swatch Images Do Not Successfully Complete Upload Process

### ISSUE THREAD

**Issue by grichards** [magento/magento2#25744] opened 2019-11-26 07:35 UTC
### Preconditions (*)

1. 2.3.3
2. Vanilla install.

### Steps to reproduce (*)

1. Create a new attribute, choose Visual Swatch as the input type.
2. Attempt to upload a swatch.

### Expected result (*)

1. Swatch uploads and I see image of swatch on row where I uploaded it.

### Actual result (*)

1. Javascript Error
![BadVisualSwatch](https://user-images.githubusercontent.com/454158/69608380-2d923600-0fdc-11ea-9f32-cedc7ac730ca.png)

**Comment by grichards** [comment] 2019-11-26 07:36
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-26 07:36
Hi @grichards. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-26 07:36
Hi @grichards, here is your [Magento instance](https://i-25744-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25744-2-3-develop.instances.magento-community.engineering/admin](https://i-25744-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by grichards** [comment] 2019-11-26 07:40
@m2-assistant yes, I was able to reproduce in your vanilla instance

**Comment by ajijshekh123** [comment] 2019-11-27 04:20
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-27 04:20
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-27 04:21
Hi @ajijshekh123, here is your [Magento instance](https://i-25744-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25744-2-3-develop.instances.magento-community.engineering/admin](https://i-25744-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2019-11-27 04:35
Hello, @grichards,
I have verified this issue as per your steps and attached screenshot.
I haven't reproduced this issue on Default Magento 2.3 Instance.
See attached screenshot.

![2019-11-27](https://user-images.githubusercontent.com/24711761/69693965-45ada680-10fd-11ea-8a6e-1b56878d4891.png)

@grichards - Please update me on any video or proper steps so I will reproduce this issue.

Thanks.

**Comment by grichards** [comment] 2019-11-27 18:16
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-27 18:16
Hi @grichards. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-27 18:17
Hi @grichards, here is your [Magento instance](https://i-25744-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25744-2-3-develop.instances.magento-community.engineering/admin](https://i-25744-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by grichards** [comment] 2019-11-27 18:34
@ajijshekh123 here is the video demonstrating the problem:

https://drive.google.com/file/d/1IbcaB7QZR4wdXrTgGyOw0JGJAji9aElV/view

**Comment by ajijshekh123** [comment] 2019-11-28 07:09
Thanks for the Update @grichards

**Comment by ajijshekh123** [comment] 2019-11-28 07:09
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-28 07:09
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-28 07:09
Hi @ajijshekh123, here is your [Magento instance](https://i-25744-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25744-2-3-develop.instances.magento-community.engineering/admin](https://i-25744-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2019-11-28 07:18
Hi @grichards,
This issue is found on Mac OS (Chrome Browser). In the Windows system, Jquery error seems not found. 
See attached screenshot:

![Screenshot 2019-11-28 at 12 45 12 PM](https://user-images.githubusercontent.com/24711761/69785028-39007f80-11dd-11ea-8093-2d90d13dcb84.png)

**Comment by magento-engcom-team** [comment] 2019-11-28 07:19
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29240` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment] 2020-09-16 19:47
This issue should be re-confirmed on the latest `2.4-develop` code.
It seems was already fixed since 2019 till now.

**Comment by engcom-Delta** [comment] 2020-11-03 19:16
Issue is not reproducible on 2.4-develop. Was checked on Chrome and Firefox browsers
**Manual testing scenario:**
- Navigate to Stores / Attributes / Product
- Add New Attribute 
- Set a Label
- Visual Swatch as Catalog Input Type for Store Owner
- Select Add Swatch 
- Click on Upload a file for Swatch
- :heavy_check_mark: Images are successfully uploaded
![image](https://user-images.githubusercontent.com/51681379/98029844-d6662980-1e18-11eb-92dc-bc97107506a0.png)

- Save Attribute 
- Open created swatch attribute
- :heavy_check_mark: Images are present for swatch options
![image](https://user-images.githubusercontent.com/51681379/98030097-2e049500-1e19-11eb-83eb-f91af89b750a.png)

Closed as it is fixed and not reproducible on 2.4-develop

**Closed as completed by engcom-Delta** 2020-11-03 19:16 UTC
Labels: Component: Swatches, Component: Admin, not-confirmed
