### ISSUE TITLE
Not possible to serve static content from different domain due to XMlHttprequest CORS

### ISSUE THREAD

**Issue by acashley** [magento/magento2#23339] opened 2019-06-20 11:58 UTC
### Preconditions (*)

1. Magento CE 2.3.x & 2.3-develop
2. nginx 1.12.2
3. PHP 7.2.19
4. Two separate vhost configs in nginx;
- Primary domain: https://www.domain.com (sitemap.local in my case)
- "CDN domain" (static content only): https://assets.cdn-domain.com (assets.sitemap.local in my case)

### Steps to reproduce (*)

1. Set "Base URL for Static View Files" and/or "Secure Base URL for Static View Files" in Stores > Configuration > Base URLs to the desired CDN domain, e.g. https://assets.cdn-domain.com/static/
2. Configure CDN with origin of https://www.domain.com/ (wont go into detail here but nothing fancy configured on CDN side).
3. Load a page on site containing an html template. (Note: The template should make an xhr request for the test to work), e.g. /static/version1560972019/frontend/MyTheme/Theme/en_US/Magento_Ui/template/messages.html

### Expected result (*)

1. Page should load fully. Assets that are static should be loaded from the CDN domain, i.e. https://assets.cdn-domain.com/static/... and all other assets should be loaded from the primary domain https://www.domain.com/<everything else>
2. No errors loading content expected.

### Actual result (*)

1. Page loads all assets, EXCEPT the html templates making xhr requests.
2. These assets fail to load with errors in the browser;
![image](https://user-images.githubusercontent.com/51680850/68020131-2fe7c580-fca6-11e9-92db-85128311b6f3.png)
![image](https://user-images.githubusercontent.com/51680850/68020223-80f7b980-fca6-11e9-9a0d-2da5e9df35ed.png)
![image](https://user-images.githubusercontent.com/51680850/68020153-3ece7800-fca6-11e9-9031-d2a493f680ed.png)

OPTIONS https://assets.cdn-domain.com/static/version1560972019/frontend/MyTheme/Theme/en_GB/Magento_InstantPurchase/template/instant-purchase.html 405 (Not Allowed)
product-page.html:1 Access to XMLHttpRequest at 'https://assets.cdn-domain.com/static/version1560972019/frontend/MyTheme/Theme/en_GB/Magento_InstantPurchase/template/instant-purchase.html' from origin 'https://www.domain.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

The problem it seems is that Cross-domain XMLHttpRequest requests are not permitted by the browser, and it is not possible to override these on the web server (although they are there for a reason so probably not something you want to do anyway).

Because Magento 2 serves these files templates from the "Base URL for Static View Files" and/or "Secure Base URL for Static View Files" rewritten URLs, it seems impossible for static content to be served from a different domain to that of the primary domain without some of them failing. Everything else static (js, css, fonts, etc) on the page loads fine, but these template files all fail with a 405 when they attempt to make a call to the CDN domain.

One answer of course is to serve the whole site via CDN (ala Cloudflare) and I would do this, but it is not possible in all cases.

The only way I can think of this working is for assets making xhr calls to be excluded from having their URLs re-written to the CDN domain. That way they would make calls to the primary domain and not fail due to the cross domain policy.

**Comment by shikhamis11** [comment] 2019-06-21 17:26
Hello @acashley 
This issue is not due Magento for this you need to make changes in Apache or nginx configuration file. You can contact your server provider for this

**Comment by acashley** [comment] 2019-06-23 12:21
@shikhamis11 Respectfully, I disagree that this issue is not due to Magento.
Please see: https://developer.chrome.com/apps/xhr

"Regular web pages can use the XMLHttpRequest object to send and receive data from remote servers, but they're limited by the same origin policy (and since Chrome 73 content scripts are also subject to the same restrictions as the web page they are injected into)."

I think you may be confusing CORS for static content (certainly possible to allow this via web server configuration) vs. content that is loaded from one domain (CDN) and makes XMLHttpRequest calls to another domain (Primary), which is not possible to allow, even in web server config.

Since Magento generates the static content (of which these HTML template files are included), to be served from the specified domain (set in Magento config), it is not possible to:
- Exclude files/types from the static content generated, nor
- Choose (using Magento OR web server config) which of these files are served via the primary domain or not (URLs are rewritten inside Magento to the CDN domain)

One could forcibly exclude .html files in the web server config from being served from the CDN domain, but that would omit them completely (since they are not loaded from the Primary domain) and still result in a broken web page (i.e. same result as current failure to load).

**Comment by machaka** [comment] 2019-07-01 07:07
I was able to reproduce it. 
I'm also think this is related to magento. Everything was working fine until I make the upgrade to 2.3.1. Now I'm facing the issue that @acashley  described.

I hope someone could help :/

**Comment by shikhamis11** [comment] 2019-07-01 07:25
Hello @machaka 
Thanks for the information. I am reopening this issue will check it again from my end and will verify it.

**Comment by DigitalStartupUK** [comment] 2019-09-25 17:01
@acashley Were you ever able to apply a "workaround" for this? Short of assigning my CDN Domain (https://assets.cdn-domain.com) to a Custom Domain (https://assets.my-domain.com) via DNS, I can't think of another solution. And I'd rather avoiding buying another SSL Certificate to try this.

**Comment by acashley** [comment] 2019-09-25 18:13
@DigitalStartupUK No, I was not able to implement any workaround for this. Still waiting for some progress/update from @shikhamis11 

I don't actually think it will work wether you use assets.my-domain.com or assets.cdn-domain.com.

**Comment by magento-engcom-team** [comment] 2019-11-01 10:54
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22676` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by lincank** [comment] 2019-11-10 10:37
Hi @shikhamis11, I have the same issue on 2.3.2, and I believe this issue is due to Magento as I have config Nginx properly and it works fine on 2.2.x.

**Comment by ihor-sviziev** [comment] 2019-11-29 06:58
There is workaround for this issue:
https://help.nexcess.net/magento-2/323232how-to-resolve-cors-errors-in-magento-1-or-2-multi-stores-using-a-cdn

**Comment by DigitalStartupUK** [comment] 2019-11-29 10:25
> There is workaround for this issue:
> https://help.nexcess.net/magento-2/323232how-to-resolve-cors-errors-in-magento-1-or-2-multi-stores-using-a-cdn

This is something I looked at previously by inserting the 2 `Header set Access-Control...` lines into the existing `<IfModule mod_headers.c>` entry in the vanilla `.htaccess` file:

````
<IfModule mod_headers.c>

    Header set X-UA-Compatible "IE=edge"

    # `mod_headers` cannot match based on the content-type, however,
    # the `X-UA-Compatible` response header should be send only for
    # HTML documents and not for the other resources.

    <FilesMatch "\.(appcache|atom|bbaw|bmp|crx|css|cur|eot|f4[abpv]|flv|geojson|gif|htc|ico|jpe?g|js|json(ld)?|m4[av]|manifest|map|mp4|oex|og[agv]|opus|otf|pdf|png|rdf|rss|safariextz|svgz?|swf|topojson|tt[cf]|txt|vcard|vcf|vtt|webapp|web[mp]|webmanifest|woff2?|xloc|xml|xpi)$">
        Header unset X-UA-Compatible
        Header set Access-Control-Allow-Origin "https://my-cdn-url.com"
        Header set Access-Control-Allow-Headers "X-Requested-With"
    </FilesMatch>

</IfModule>
````

However, this still resulted in Console Errors such as the example below:

> Access to XMLHttpRequest at 'https://my-cdn-url.com/pub/static/version1574849371/adminhtml/Vendor/backend/en_GB/Magento_Ui/templates/modal/modal-custom.html' from origin 'http://my-domain.co.uk' has been blocked by CORS policy: Request header field x-requested-with is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by ihor-sviziev** [comment] 2019-11-29 12:08
@DigitalStartupUK just replace `Header set Access-Control-Allow-Origin "https://my-cdn-url.com"` to `Header set Access-Control-Allow-Origin "https://my-domain.co.uk"`

**Comment by DigitalStartupUK** [comment] 2019-11-29 14:16
@ihor-sviziev Same result whether I use "`https://my-domain.co.uk`" or "`https://my-cdn-url.com`". Thanks for your input though.

**Comment by krzksz** [comment] 2019-12-01 20:22
**If I understand correctly**, what you are describing is a standard CDN configuration for Magento where all static files (including HTML templates) are served from different domain then the shop itself. This is 100% doable and only requires valid configuration of both the host and CDN server to return proper headers for both GET and OPTIONS requests for those files.

This is not a Magento issue and there are a lot of resources on the internet on how to make CORS work so I'm closing this. For implementation questions feel free to use [Magento Community Engineering Slack](https://magentocommeng.slack.com/) or [Magento Stack Exchange](https://magento.stackexchange.com/).

**Closed as completed by krzksz** 2019-12-01 20:22 UTC
Labels: Issue: Ready for Work, Component: Config, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid

**Comment by acashley** [comment] 2019-12-02 10:25
> **If I understand correctly**, what you are describing is a standard CDN configuration for Magento where all static files (including HTML templates) are served from different domain then the shop itself. This is 100% doable and only requires valid configuration of both the host and CDN server to return proper headers for both GET and OPTIONS requests for those files.
> 
> This is not a Magento issue and there are a lot of resources on the internet on how to make CORS work so I'm closing this. For implementation questions feel free to use [Magento Community Engineering Slack](https://magentocommeng.slack.com/) or [Magento Stack Exchange](https://magento.stackexchange.com/).

@krzksz 
> **If I understand correctly**
I don't think you do understand correctly. 

"Cross-domain XMLHttpRequest requests are not permitted by the browser, and it is not possible to override these on the web server"

Please re-read everything from the top. You have made the same assumptions as @shikhamis11 
This error is not due to a server or CDN misconfiguration.

**Comment by lincank** [comment] 2019-12-02 10:55
It turns out it is a Nginx configuration issue. The broswer is expecting to receive a 200 response which sending preflight request by using `OPTIONS` method, but Nginx return 405 as default. So basically add the following lines within `server` block to let Nginx return`200` for `OPTIONS` methon and allow `X-Requested-With` header. 

```
# Nginx conf
if ($request_method = 'OPTIONS') {
       return 200;
}
```

I highly recommend Magento team to add these lines or guidance to `nginx.conf.sample` file.

**Comment by krzksz** [comment] 2019-12-02 14:15
> Please re-read everything from the top. You have made the same assumptions as @shikhamis11
> This error is not due to a server or CDN misconfiguration.

I followed your reproduction steps which clearly indicate issue with CORS. We have Magento 2.3 store where all static assets (including the `messages.html` you mentioned) are loaded from different domain and everything is working flawlessly.
<img width="879" alt="obraz" src="https://user-images.githubusercontent.com/829189/69966345-6ff4cf00-1516-11ea-95ff-688df6667cfb.png">

**Comment by acashley** [comment] 2019-12-22 07:58
> It turns out it is a Nginx configuration issue. The broswer is expecting to receive a 200 response which sending preflight request by using `OPTIONS` method, but Nginx return 405 as default. So basically add the following lines within `server` block to let Nginx return`200` for `OPTIONS` methon and allow `X-Requested-With` header.
> 
> ```
> # Nginx conf
> if ($request_method = 'OPTIONS') {
>        return 200;
> }
> ```
> 
> I highly recommend Magento team to add these lines or guidance to `nginx.conf.sample` file.

I tried this suggested config change in nginx but still seeing the same errors;

Access to XMLHttpRequest at 'https://assets.cdn-domain.com/static/frontend/MyTheme/Theme/en_GB/Plumrocket_SocialLoginFree/template/customer/authentication-popup.html' from origin 'https://www.domain.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

**Comment by acashley** [comment] 2019-12-22 07:58
> I followed your reproduction steps which clearly indicate issue with CORS. We have Magento 2.3 store where all static assets (including the `messages.html` you mentioned) are loaded from different domain and everything is working flawlessly.

Please advise what CDN you are using for the assets loaded from the different domain.

Edit: I can see you are using CloudFront. 
Difference between your CDN loaded assets and mine is that yours load on the CDN URL. Mine are all redirected (301) to the origin domain for some reason.

e.g.
https://d569htemax5yg.cloudfront.net/static/version1573154199/frontend/Creativestyle/theme-pack2go/de_DE/Magento_Ui/templates/block-loader.html

would be redirected to:
https://www.pack2go.de/static/version1573154199/frontend/Creativestyle/theme-pack2go/de_DE/Magento_Ui/templates/block-loader.html

I think its this redirect that is not permitted by the browser when these html pages attempt to make a XMLHttpRequest

**Comment by acashley** [comment] 2019-12-22 14:41
Finally found the issue(s)...

1. Preventing URL rewriting:
- By default the SSL configuration on Cloudflare is set to:
Flexible - Encrypts traffic between the browser and Cloudflare

- I had to change SSL mode to:
Full - Encrypts end-to-end, using a self signed certificate on the server
(you could also use Full (strict) in some cases)

This was a problem because my HTTP vhost in nginx is configured to rewrite all requests to HTTPS, even CDN URLs were being rewritten to the primary domain, because the CDN was making the CDN->origin request via HTTP instead of HTTPS.

2. Permitting OPTIONS header for XHR requests:
The config provided by @lincank above is also necessary to make it work.

- Nginx conf
if ($request_method = 'OPTIONS') {
       return 200;
}

So a big thank you and apologies to all. Not a bug! 
I do appreciate your help...

**Comment by DigitalStartupUK** [comment] 2019-12-23 09:46
I also want to chime in here and state that once it was **confirmed** that this wasn't a bug a few weeks ago, I did some more digging and determined that I had to add the following to my Apache Config (inside `<Directory /var/www/html/>`). Therefore, making it an environmental issue:

````
Header set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
Header set Access-Control-Allow-Headers "x-requested-with"
````
