### ISSUE TITLE
Edit product - content section - wysiwyg not displaying text

### ISSUE THREAD

**Issue by fabotha** [magento/magento2#39251] opened 2024-10-10 08:25 UTC
### Preconditions and environment

- Magento version 2.4.7 p-1
- When I edit a product or create a new product.
- Go to catalog / products / 
- display a product
- click edit
- go to content section and expand and I do not see text in teh WYSIWYG editor
- you see https://firesupportltd-my.sharepoint.com/:f:/g/personal/accounts_firesupport_uk/Encd01U4T0xEkEgUSoOjfd4B0u4nHn6q0K-o3_tIZcu7jw?e=byxBC7
- move mouse over the top of the html, click the cog and it opens a basic editor
- then you can edit the html and then save it.
- Why does the WYSIWYG editor not open?
- This has been like this since installation

### Steps to reproduce

Go to catalog / products / 
- display a product
- click edit
- go to content section and expand section
- you see https://firesupportltd-my.sharepoint.com/:f:/g/personal/accounts_firesupport_uk/Encd01U4T0xEkEgUSoOjfd4B0u4nHn6q0K-o3_tIZcu7jw?e=byxBC7
- move mouse over the top of the html, click the cog and it opens a basic editor
- then you can edit the html and then save it.
- Why does the WYSIWYG editor not open?
- This has been like this since installation

### Expected result

open WYSIWYG editor

### Actual result

you see the following images
- you see https://firesupportltd-my.sharepoint.com/:f:/g/personal/accounts_firesupport_uk/Encd01U4T0xEkEgUSoOjfd4B0u4nHn6q0K-o3_tIZcu7jw?e=byxBC7

### Release note

2.4.7 p-1
but its been a problem since 2.4.7 was used to build a new server

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ananth-iyer** [comment] 2024-10-10 09:31
@fabotha if you need the Wysiwyg editor in Page builder then add Text from Elements tab.
![image](https://github.com/user-attachments/assets/79ef8ba0-8803-4afb-b37b-747325fcbbea)

**Comment by fabotha** [comment] 2024-10-10 09:39
Hi
But why does it not open correctly, I cannot expect to have to edit 16000 products to fix this
Also I have no idea how to get that text to do what you say
When I open content I see the below, it should open in WYSIWYG, what you are suggesting is a work around not a fix or a expected process,
Why does it not open in the editor?
Thanks
Frank


***@***.***

Please note we have a new email address
***@***.******@***.***>

We ship Airsoft products all over the world.
Tax free (20% off) at checkout to all countries.

Marui recoil Specials - repairs, upgrade, lipo conversion and custom work

Latest products - www.fire-support.co.uk/latest_products.php<http://www.fire-support.co.uk/latest_products.php>

OPEN 4 Days a week, Tue - friday 9am - 5.30pm
Alternate Saturdays 10-5
see https://www.fire-support.co.uk/openingtimes.php
Please always reply with our email in yours so we can track the conversation.

Frank - Director
Tel 01733 247171

**Comment by ananth-iyer** [comment] 2024-10-10 09:46
@fabotha you can disable Page builder on the Description attribute and it will look like Short Description field.

**Comment by ananth-iyer** [comment] 2024-10-10 09:47
![image](https://github.com/user-attachments/assets/25b7010c-bf50-484c-8bf4-874e59487890)

**Comment by Franciscof-Serfe** [comment] 2024-10-10 13:07
@magento give me 2.4.4-p11 instance

**Comment by engcom-Bravo** [comment] 2024-10-17 04:26
@ananth-iyer Thanks for your Contribution!!.

Hi @fabotha,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.we are able to open the WYSIWYG editor.Kindly refer this comments https://github.com/magento/magento2/issues/39251#issuecomment-2404616974 and let us know if you are still facing any issue.

Thanks.

**Comment by fabotha** [comment] 2024-10-17 08:14
Hi
Changing the attribute does work and now I have wysiwyg editor, thank you.

Please can you tell me how I can get paste options.

If I copy text from a web site that is say formatted in a table in the or over several line and I want to paste into the wysiwyg edition using right mouse click I get an option to link
For example copy and paste the below text

Stock Location
M5-RM-S2-P2-D0
SKU
LL-4570189744126
Manufacturer
Laylax
Restricted Postage
No
18 age restricted
No
Defence Required
No
On Sale
No
Product Type
Foregrip
Part for Brand
Krytac
Gun Type
AEG
Colour
Black

***@***.***

Or if I use windows keys, so Shift and Insert I get

***@***.***


I cannot see any options to choose the paste method

Thanks
Frank



Please note we have a new email address
***@***.******@***.***>

We ship Airsoft products all over the world.
Tax free (20% off) at checkout to all countries.

Marui recoil Specials - repairs, upgrade, lipo conversion and custom work

Latest products - www.fire-support.co.uk/latest_products.php<http://www.fire-support.co.uk/latest_products.php>

OPEN 4 Days a week, Tue - friday 9am - 5.30pm
Alternate Saturdays 10-5
see https://www.fire-support.co.uk/openingtimes.php
Please always reply with our email in yours so we can track the conversation.

Frank - Director
Tel 01733 247171

**Comment by ananth-iyer** [comment] 2024-10-17 09:30
@fabotha to have paste options please install Magefan wysiwyg advanced extension
https://github.com/magefan/module-wysiwyg-advanced

check their demo website

**Comment by fabotha** [comment] 2024-10-17 09:43
Hi
Is that the only way?

The Tiny wysiwyg editor has the capability

Thanks
Frank


Please note we have a new email address
***@***.******@***.***>

We ship Airsoft products all over the world.
Tax free (20% off) at checkout to all countries.

Marui recoil Specials - repairs, upgrade, lipo conversion and custom work

Latest products - www.fire-support.co.uk/latest_products.php<http://www.fire-support.co.uk/latest_products.php>

OPEN 4 Days a week, Tue - friday 9am - 5.30pm
Alternate Saturdays 10-5
see https://www.fire-support.co.uk/openingtimes.php
Please always reply with our email in yours so we can track the conversation.

Frank - Director
Tel 01733 247171

**Comment by engcom-Bravo** [comment] 2024-10-18 05:06
Hi @fabotha,

Thanks for your update.

For copy and paste we can use windows keys.Please refer the below screenshots.


Use Table option for table format.

<img width="1333" alt="Screenshot 2024-10-18 at 10 35 12" src="https://github.com/user-attachments/assets/9734d250-4589-460c-8e68-a9516a940a17">


Since the issue has been resolved we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-10-18 05:06 UTC
Labels: Issue: needs update, Reported on 2.4.7-p1
