### ISSUE TITLE
reCAPTCHA V3 Invisible badge missing 'Privacy' and 'Terms' links when Position = Inline

### ISSUE THREAD

**Issue by n2diving-dgx** [magento/magento2#34485] opened 2021-10-30 09:59 UTC
The reCAPTCHA V3 Invisible badge is missing 'Privacy' and 'Terms' links when Position = Inline, which is a violation of Google usage guidelines for reCAPTCHA https://developers.google.com/recaptcha/docs/faq

Install M2.4.3-p1 and Luma Store from scratch (note also reproduced on M2.3.7-p1)

Configure reCAPTCHA in backend
Navigate to Admin> Stores> Configuration> Security> Google reCAPTCHA Storefront
For reCAPTCHA v3 Invisible...
Set valid API Website Key
Set valid API Secret Key
Accept default system values for:
- Minimum Score Threshold = 0.5
- Invisible Badge Position = Inline 
- Theme = Light Theme

For Storefront...
Set Enable for Customer Login = reCAPTCHA v3 Invisible    
(enabling a single storefront setting for this example, however broken in all)

To reproduce on frontend page, using Chrome or Edge browser, navigate to Sign In page and observe that
reCAPTCHA V3 Invisible badge missing "Privacy" and "Terms" links

**Expected result would produce a badge on any reCAPTCHA protected page that looks like this...**

![badge-example](https://user-images.githubusercontent.com/17930467/139528481-13b1b99d-00e4-4d2b-ac5a-e2b97fb7d57e.png)

**Actual result produces a badge like the following...
 (note the "-" only, missing Privacy and Terms links.)**

![Screenshot 2021-10-30 053557](https://user-images.githubusercontent.com/17930467/139528419-4666e1ed-8234-43a8-989c-8f57b6907890.png)

**Note that by changing the Badge Position  setting from Inline to Bottom Left, the Privacy and Terms links do appear and function correctly when the badge is moused-over.**

![Screenshot 2021-10-30 061025](https://user-images.githubusercontent.com/17930467/139528890-568479b0-5516-4ba9-970a-5419fa69de50.png)

**Comment by engcom-Hotel** [comment] 2021-11-26 14:15
@magento give me 2.4.3-p1 instance

**Comment by engcom-Hotel** [comment] 2021-11-26 14:33
Hello @n2diving-dgx,

We have tried to reproduce this issue on Magento 2.4.3-P1 instance but this is not reproducible for us. Please have a look at the below screenshot for reference:

![image](https://user-images.githubusercontent.com/51681618/143595866-0c80ad2d-3caa-4049-8908-876db975814d.png)

![image](https://user-images.githubusercontent.com/51681618/143595920-21023fca-25be-497c-bae6-6a9437e313dc.png)

Please let us know in case we have missed anything.

Thanks

**Comment by n2diving-dgx** [comment] 2021-11-27 09:58
I'm stumped... I can only assume it has something to do with the LAMP environment, I reconfirmed on a clean install...
PHP is on most current 7.4 release...

ok+ date
Fri 26 Nov 07:34:04 EST 2021
+ cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
+ /usr/local/apache/bin/httpd -v
Server version: Apache/2.4.46 (Unix)
Server built:   Aug 11 2020 14:47:55
+ mysql -V
mysql  Ver 14.14 Distrib 5.7.35, for Linux (x86_64) using  EditLine wrapper
+ php -v
PHP 7.4.26 (cli) (built: Nov 23 2021 14:46:48) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.26, Copyright (c), by Zend Technologies
+ php /usr/local/bin/composer -V
[32mComposer[39m version [33m2.0.13[39m 2021-04-27 13:11:08
+ curl -s -XGET http://localhost:9200
+ grep 'cluster_name\|number'
+ xargs -n2 '-d\n'
  "cluster_name" : "elasticsearch",     "number" : "7.13.0",

**Comment by engcom-Hotel** [comment] 2021-12-10 08:39
Hello @n2diving-dgx,

Previously we have tried to reproduce this error in cloud instance but this time I tried to reproduce it in our local machine, but still, we are unable to reproduce it, below is the specification of my system:

- httpd -v
> Server version: Apache/2.4.48 (Unix)
> Server built:   Aug 30 2021 04:23:22
- mysql --version
> mysql  Ver 8.0.25 for macos11.3 on x86_64 (Homebrew)
- php -v
> PHP 7.4.20 (cli) (built: Jun  3 2021 19:10:14) ( NTS )
> Copyright (c) The PHP Group
> Zend Engine v3.4.0, Copyright (c) Zend Technologies
>     with Zend OPcache v7.4.20, Copyright (c), by Zend Technologies
>     with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans
>     with blackfire v1.66.0~mac-x64-non_zts74, https://blackfire.io, by Blackfire
- composer --version
> Composer version 2.1.6 2021-08-19 17:11:08
- curl -s -XGET http://localhost:9200 | grep "cluster_name"
> elasticsearch_abhinav
- curl -s -XGET http://localhost:9200 | grep "number" 
> "number" : "7.13.0"

Please let us know if we missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2021-12-24 06:41
Dear @n2diving-dgx,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2021-12-24 06:41 UTC
Labels: Issue: needs update
