### ISSUE TITLE
A Extra % sign comes when deploying

### ISSUE THREAD

**Issue by sumitnegi97** [magento/magento2#31581] opened 2021-01-07 07:23 UTC
![Screenshot-from-2021-01-07-12-51-36](https://user-images.githubusercontent.com/76430009/103863702-5180e000-50e7-11eb-9dfc-d59a1b28053e.png)

**Comment by mrtuvn** [comment] 2021-01-07 15:01
Seem issue not related with magento. Can you reproduce with clean vanilla magento with same enviroments like your(only magento modules only)

**Comment by mrtuvn** [comment] 2021-01-07 15:04
![Screenshot from 2021-01-07 22-03-48](https://user-images.githubusercontent.com/1908873/103907821-56b84c00-5134-11eb-9c3e-3772edf28236.png)

**Comment by engcom-Alfa** [comment] 2021-01-08 12:52
Hi @sumitnegi97. Thank you for your report!

Unfortunately, we are not able to reproduce the issue on fresh 2.4-develop. 

**Actual Result:** :heavy_check_mark: An extra sign "%" isn't displayed during deploying.

![Screenshot from 2021-01-08 14-05-17](https://user-images.githubusercontent.com/51679138/104017256-772de800-51c0-11eb-98fb-6e4f75c69402.png)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2021-01-08 12:52 UTC
Labels: Triage: Dev.Experience, Issue: ready for confirmation, not-confirmed, Reported on 2.4.0
