### ISSUE TITLE
Price sync issue 

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#35294] opened 2022-04-13 07:47 UTC
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1. update price on store with "rest/all/V1/products/base-prices"
2. Request for get products "rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=sku&searchCriteria[filter_groups][0][filters][0][value]=NVE-100-607AP-FD&searchCriteria[filter_groups][0][filters][0][condition_type]=in"
3. When we check the response from individual product download API we get the correct updated price.
4. But the customer is facing issue that after sometime its prices get reverted to original price which was before.

### Expected result (*)

1.  After updating product price , it should remain updated
2.

### Actual result (*)

1. After sometime the price is reverted back to the original one.
2. Customer is also stating that his prices are getting updated in the history and not on actual fields.
3. Please guide us whether there is any crone job running which reverts the prices. If yes please help us know details of that job

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-04-13 11:28
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue:
Steps performed:
Sent POST request to /rest/all/V1/products/base-prices:
Sample payload:
`{
  "prices": [
    {
      "price": 67,
      "store_id": 0,
      "sku": "simpleee",
      "extension_attributes": {}
    }
  ]
}`
Base Price is updated as expected in both Admin and Front-end even if cron is enabled.
Checked after some time but still not able to reproduce the issue
![image](https://user-images.githubusercontent.com/60198231/163169873-33ed0f7b-981d-4ad1-9870-9c5633902214.png)
![image](https://user-images.githubusercontent.com/60198231/163169955-a01231a5-6f0d-4386-97b2-2d9a97704431.png)
@webgility-amazonapi sometimes, Prices are not updated on store-front if indexers are not updated properly. Try re-indexing and check if the prices are updated on UI and API.
Kindly recheck the issue on Magento 2.4-develop branch as it is the upcoming 2.4.x release and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-04-27 06:11
Hi @webgility-amazonapi ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-04-27 06:11 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update

**Comment by webgility-amazonapi** [comment] 2022-04-27 06:31
We haven't find any satisfactory answer. You have close. the issue without providing the solution. 
please reopen it.
