### ISSUE TITLE
Configure page variations example is not Working with caching enabled

### ISSUE THREAD

**Issue by giggo1604** [magento/magento2#12788] opened 2017-12-18 13:24 UTC
### Preconditions
1. Magento 2.1
2.  All caches enabled

### Steps to reproduce
[Create this Plugin](http://devdocs.magento.com/guides/v2.2/extension-dev-guide/cache/page-caching/public-content.html#configure-page-variations)

debug/inspect the value returned from:
`$this->customerSession->getCustomerData()`

### Expected result
CusomterData is pressent and can be used to configure a page variation

### Actual result
CustomerData is null

I tried to look into this issue an it seems that the customer Data has already been depersonalized by `\Magento\PageCache\Model\Layout\DepersonalizePlugin` at this point.

I understand that this is done to not accidentally leek personal data on a cached page but it is annoying that there is an offical example which is not working as intended.

**Comment by magento-engcom-team** [comment] 2018-03-01 14:49
@giggo1604, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by engcom-Charlie** [comment] 2019-08-05 07:31
Hello @giggo1604 
Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by engcom-Charlie** 2019-08-05 07:31 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Fixed in 2.3.x, Issue: Format is valid
