### ISSUE TITLE
Page Builder Error for Version 2.3.1

### ISSUE THREAD

**Issue by maureyz** [magento/magento2#32766] opened 2021-04-15 16:58 UTC
### Preconditions (*)

1. Magento 2.3.1
2.PHP 7.2.3

### Steps to reproduce (*)

1.Go to Content
2.Then go Pages
3.Promotion
4.Edit a Product Promotion
5.Schedule a new update

### Expected result (*)

1. **This si what expect:**
![image](https://user-images.githubusercontent.com/82602868/114907584-d6635000-9de0-11eb-8ff2-c5a60a4141f8.png)

### Actual result (*)

1. **Instead of that is this:**
![image](https://user-images.githubusercontent.com/82602868/114907721-fabf2c80-9de0-11eb-9483-487de5117f6f.png)

PS. Js console browser says  `"TypeError: Cannot read property 'children' of null"`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by maureyz** [comment] 2021-04-15 17:21
I saw on this thread that this guy install a patch provided from you guys
https://github.com/magento/magento2/issues/31277
Thanks in advance!

**Comment by maureyz** [comment] 2021-04-15 17:57
As the same directory about: `vendor/mageto/module-page-builder/view/adminhtml/web/js/page-builder.js` creates the pop up notifiation.

**Comment by engcom-Oscar** [comment] 2021-04-16 07:28
Hi @maureyz  ! Thank you for your report.
Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop by following steps from this ticket.
So, we have to close this ticket.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch.
 Thank you for collaboration.

**Closed as completed by engcom-Oscar** 2021-04-16 07:28 UTC
Labels: Issue:  Cannot Reproduce, Component: PageBuilder, Issue: ready for confirmation
