### ISSUE TITLE
Leading Spaces on CSV export

### ISSUE THREAD

**Issue by ghost** [magento/magento2#26841] opened 2020-02-12 13:53 UTC
### Preconditions (*)

1. Magento 2.3.2
2. PHP 7.2.24
3. Ubuntu 16.04.1

### Steps to reproduce (*)

1. Export all products with all columns as a CSV
2. Don't change any filters
3. Open CSV file
4. See extra spaces at start of CSV. My first column is SKU.

### Expected result (*)

1. Expected result is the first column name to have no leading spaces

### Actual result (*)
1. First Column has 2 leading spaces.
![notepad++_QqwKNpZJ4C](https://user-images.githubusercontent.com/33052213/74340797-83d27200-4d9e-11ea-9132-2d336c38e552.png)

**Comment by Resurgem** [comment] 2020-02-12 13:56
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment] 2020-02-12 13:56
Hi @Resurgem. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-12 13:57
Hi @Resurgem, here is your [Magento instance](https://i-26841-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26841-2-4-develop.instances.magento-community.engineering/admin_2662](https://i-26841-2-4-develop.instances.magento-community.engineering/admin_2662)
Login: `2c88e609` Password: `4e1d0f4f4416`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2020-02-12 14:04
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-12 14:04
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-12 14:05
Hi @ajijshekh123, here is your [Magento instance](https://i-26841-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26841-2-4-develop.instances.magento-community.engineering/admin_b10b](https://i-26841-2-4-develop.instances.magento-community.engineering/admin_b10b)
Login: `c0b75c3e` Password: `d0d7a6a0ef29`
Instance will be terminated in up to 3 hours.

**Comment by Resurgem** [comment] 2020-02-12 14:13
Cron not working on test instance, Magento won't export the CSV file. Can't reproduce because of this

**Comment by ajijshekh123** [comment] 2020-02-12 14:20
Yes @Resurgem, I will reproduce this issue tomorrow.
Thanks for the update :)

**Comment by Resurgem** [comment] 2020-02-12 14:27
Not able to reproduce on [sample instance](http://magento2demo.firebearstudio.com/index.php) on Magento 2.3.1
![notepad++_XPeN3VgZnr](https://user-images.githubusercontent.com/33052213/74343969-d06c7c00-4da3-11ea-8be2-7abfc866ea4a.png)

**Comment by Resurgem** [comment] 2020-02-12 14:36
No leading spaces on file before downloading using the admin panel.
Downloaded file has leading spaces.
Image is of file in var/export
![firefox_Fst08iNoBk](https://user-images.githubusercontent.com/33052213/74344788-03633f80-4da5-11ea-977f-e1d1a99c128d.png)

**Comment by ajijshekh123** [comment] 2020-02-13 05:56
@Resurgem - Not able to reproduce this issue default Magento 2.3 instance on my local system.
Can I close this issue or not?

**Comment by Resurgem** [comment] 2020-02-13 08:07
Yeah

**Closed as completed** 2020-02-13 08:10 UTC
Labels: Progress: needs update, Issue: Format is valid

**Comment by zkriahac** [comment] 2023-06-08 08:46
hello the issue ocuring when there is Ui Component for Listing Columns
under this path
 Ui\Component\Listing\Column
```
    <column name="product_details" class="MagentoTeknik\Reservation\Ui\Component\Listing\Column\ReservationProduct">
        <argument name="data" xsi:type="array">
            <item name="config" xsi:type="array">
                <item name="bodyTmpl" xsi:type="string">ui/grid/cells/html</item> 
                <item name="sortable" xsi:type="boolean">false</item>
                <item name="filter" xsi:type="string">false</item>
                <item name="label" xsi:type="string" translate="true">Product Details</item>
                <item name="sortOrder" xsi:type="number">8</item>
            </item>
        </argument>
    </column>
```
