### ISSUE TITLE
2.4.7-p1: "Could not create an acl object" after disabling Magento_PaymentServices* modules

### ISSUE THREAD

**Issue by OvalMedia** [magento/magento2#38839] opened 2024-06-18 14:18 UTC
### Preconditions and environment

- Magento version: 2.4.7-p1
- PHP 8.2
- Fresh install, no other modifications

### Steps to reproduce

1. Install magento
2. disable all paymentservices modules: bin/magento module:disable Magento_PaymentServicesBase Magento_PaymentServicesDashboard Magento_PaymentServicesPaypal Magento_PaymentServicesSaaSExport Magento_PaymentServicesPaypalGraphQl
3. bin/magento setup:di:compile
4. Login to admin panel

### Expected result

Modules are disabled and the admin panel should work as expected.

### Actual result

Admin panel crashes with an exception:
```

1 exception(s):
Exception #0 (LogicException): Could not create an acl object: Invalid Document 
Error in merged XML after reading /vendor/magento/module-config/etc/acl.xml
Element 'resource': The attribute 'title' is required but missing.
Line: 14
The xml was: 
9:        <resources>
10:            <resource id="Magento_Backend::admin" title="Magento Admin" translate="title" sortOrder="20">
11:                <resource id="Magento_Backend::stores" title="Stores" translate="title" sortOrder="80">
12:                    <resource id="Magento_Backend::stores_settings" title="Settings" translate="title" sortOrder="10">
13:                        <resource id="Magento_Config::config" title="Configuration" translate="title" sortOrder="20">
14:                            <!--
15:                            @deprecated Magento_Config::advanced section ('Advanced Section') is disabled and is not displayed in the admin panel
16:                            -->
17:                            <resource id="Magento_Config::advanced" title="Advanced Section" translate="title" sortOrder="90" disabled="true"/>
18:                            <resource id="Magento_Config::config_admin" title="Advanced Admin Section" translate="title" sortOrder="100"/>


Exception #0 (LogicException): Could not create an acl object: Invalid Document 
Error in merged XML after reading /vendor/magento/module-config/etc/acl.xml
Element 'resource': The attribute 'title' is required but missing.
Line: 14
The xml was: 
9:        <resources>
10:            <resource id="Magento_Backend::admin" title="Magento Admin" translate="title" sortOrder="20">
11:                <resource id="Magento_Backend::stores" title="Stores" translate="title" sortOrder="80">
12:                    <resource id="Magento_Backend::stores_settings" title="Settings" translate="title" sortOrder="10">
13:                        <resource id="Magento_Config::config" title="Configuration" translate="title" sortOrder="20">
14:                            <!--
15:                            @deprecated Magento_Config::advanced section ('Advanced Section') is disabled and is not displayed in the admin panel
16:                            -->
17:                            <resource id="Magento_Config::advanced" title="Advanced Section" translate="title" sortOrder="90" disabled="true"/>
18:                            <resource id="Magento_Config::config_admin" title="Advanced Admin Section" translate="title" sortOrder="100"/>

<pre>#1 Magento\Framework\Acl\Builder\Proxy->getAcl() called at [vendor/magento/module-backend/Model/Auth/Session.php:271]
#2 Magento\Backend\Model\Auth\Session->processLogin() called at [vendor/magento/module-backend/Model/Auth.php:165]
#3 Magento\Backend\Model\Auth->login() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#4 Magento\Backend\Model\Auth\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#5 Magento\Backend\Model\Auth\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-admin-adobe-ims/Plugin/DisableAdminLoginAuthPlugin.php:56]
#6 Magento\AdminAdobeIms\Plugin\DisableAdminLoginAuthPlugin->aroundLogin() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#7 Magento\Backend\Model\Auth\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#8 Magento\Backend\Model\Auth\Interceptor->___callPlugins() called at [generated/code/Magento/Backend/Model/Auth/Interceptor.php:23]
#9 Magento\Backend\Model\Auth\Interceptor->login() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:207]
#10 Magento\Backend\App\Action\Plugin\Authentication->_performLogin() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:159]
#11 Magento\Backend\App\Action\Plugin\Authentication->_processNotLoggedInUser() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:127]
#12 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#13 Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#14 Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->___callPlugins() called at [generated/code/Magento/Backend/Controller/Adminhtml/Index/Index/Interceptor.php:32]
#15 Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:245]
#16 Magento\Framework\App\FrontController->getActionResponse() called at [vendor/magento/framework/App/FrontController.php:212]
#17 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:146]
#18 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#19 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#20 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#21 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#22 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#23 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#24 Magento\Framework\App\Http\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#25 Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-application-performance-monitor/Plugin/ApplicationPerformanceMonitor.php:38]
#26 Magento\ApplicationPerformanceMonitor\Plugin\ApplicationPerformanceMonitor->aroundLaunch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#27 Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#28 Magento\Framework\App\Http\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#29 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#30 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
</pre>

```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2024-06-19 13:04
Hi @OvalMedia ,

Verified the issue on 2.4-develop community as well as commerce edition and we are not able to reproduce this issue.

Steps to reproduce:-

1.Install magento
2.disable all paymentservices modules: bin/magento module:disable Magento_PaymentServicesBase 
    Magento_PaymentServicesDashboard Magento_PaymentServicesPaypal Magento_PaymentServicesSaaSExport 
    Magento_PaymentServicesPaypalGraphQl
3.bin/magento setup:di:compile
4.Login to admin panel

disable all payment services modules

<img width="1432" alt="Screenshot 2024-06-19 at 6 29 18 PM" src="https://github.com/magento/magento2/assets/51681379/e2950dcb-065c-45c7-8ebc-3ec4ca813e9a">

Run bin/magento setup:di:compile

<img width="760" alt="Screenshot 2024-06-19 at 6 29 33 PM" src="https://github.com/magento/magento2/assets/51681379/7b85d20f-15a6-4938-8c23-2109efc68033">

Login to admin panel

<img width="1440" alt="Screenshot 2024-06-19 at 6 29 47 PM" src="https://github.com/magento/magento2/assets/51681379/01c31efc-88e4-4bd2-b08f-a3c82cb7fd8b">


Please refer the attached screenshots and let us know if we missed anything.

**Comment by engcom-Delta** [comment] 2024-06-24 13:12
Hi @OvalMedia ,

Verified the issue on 2.4.7 and it is reproducible.

Hence, Confirming the issue.

Steps to reproduce:-

1.Install magento
2.Disable all payment services modules: bin/magento module:disable Magento_PaymentServicesBase Magento_PaymentServicesDashboard Magento_PaymentServicesPaypal Magento_PaymentServicesSaaSExport Magento_PaymentServicesPaypalGraphQl
3.bin/magento setup:di:compile
4.Login to admin panel


Disable all payment services modules

<img width="1431" alt="Screenshot 2024-06-24 at 6 37 35 PM" src="https://github.com/magento/magento2/assets/51681379/f86fb305-1112-4853-8978-b0ce2f445f63">

bin/magento setup:di:compile

<img width="819" alt="Screenshot 2024-06-24 at 6 37 46 PM" src="https://github.com/magento/magento2/assets/51681379/d2ca3c54-f3dd-4127-a104-11b3311f2e0f">

Login to admin panel

<img width="1438" alt="Screenshot 2024-06-24 at 6 38 44 PM" src="https://github.com/magento/magento2/assets/51681379/b41d1585-2501-4372-a887-a6718850196c">

**Comment by elioermini** [comment] 2024-06-24 15:09
This one is quite annoying

**Comment by OvalMedia** [comment] 2024-06-24 15:12
> This one is quite annoying

Adobe decided to pack magento with their own service which I cannot use anyway (not available in my country). And to add insult to injury I cannot remove it properly.

**Comment by hostep** [comment] 2024-06-24 15:28
@OvalMedia, there is a way to remove them with a composer trick:

1. Add this to your `composer.json` file:
```json
    "replace": {
        "adobe-commerce/os-extensions-metapackage": "*",
     }
```
2. Run `composer update adobe-commerce/* magento/*`
3. Run `bin/magento setup:upgrade`

That should get rid of them. This is a pretty common practice done by Magento veterans, to remove unwanted modules this way, it was first described [in this blog post](https://www.integer-net.com/blog_english/removing-unused-core-modules-from-magento-2-the-right-way) as far as I remember.

**Comment by OvalMedia** [comment] 2024-06-24 15:33
I am familiar with that technique. I don't use adobe commerce. And I doubt this will make the exception go away as it is triggered in module-config. The way I interpret that exception a field that used to be optional ("title") is now required. But since the ACL files are all merged the title was eventually set by the adobe payment modules. That way it was not noticed the title attribute is missing in other modules.

**Comment by elioermini** [comment] 2024-06-28 15:49
@OvalMedia the change suggested by @hostep (hero!) actually removes plenty of modules even in the Magento OpenSource. In our case these, can be more or less in your case and the specific issue "Could not create an acl object" is solved! So the cause has to be in one of the following that went away:

  - Removing adobe-commerce/adobe-ims-metapackage (2.2.2)
  - Removing adobe-commerce/os-extensions-metapackage (1.0.0)
  - Removing firebase/php-jwt (v6.10.1)
  - Removing magento/module-graph-ql-server (1.0.2)
  - Removing magento/module-service-proxy (2.6.0)
  - Removing magento/module-services-id (3.2.5)
  - Removing magento/module-services-id-layout (1.1.3)
  - Removing magento/payment-services (2.6.0)
  - Removing magento/services-connector (1.3.5)
  - Removing magento/services-id (3.2.5)

**Comment by gaiterjones** [comment] 2024-07-25 05:50
I am seeing this issue on a production upgrade to 2.4.7-p1 with no disabled modules - does anyone have a workaround / fix to get the backend working again?

**Comment by gntlby** [comment] 2024-07-25 11:20
> I am seeing this issue on a production upgrade to 2.4.7-p1 with no disabled modules - does anyone have a workaround / fix to get the backend working again?

I have same problem. Any update?

**Comment by adamwaclawczyk** [comment] 2024-09-16 06:20
Thrown exception does not show which entries are invalid...
Currently the only sane way to deal with this is to change the `title` attribute `use` property from `required` to `optional` for `acl_merged.xsd` file
Obviously it would be better to fix invalid entries :) 

```
Index: vendor/magento/framework/Acl/etc/acl_merged.xsd
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/vendor/magento/framework/Acl/etc/acl_merged.xsd b/vendor/magento/framework/Acl/etc/acl_merged.xsd
--- a/vendor/magento/framework/Acl/etc/acl_merged.xsd	
+++ b/vendor/magento/framework/Acl/etc/acl_merged.xsd	(date 1726464310816)
@@ -21,7 +21,7 @@
                     </xs:sequence>
 
                     <xs:attribute name="id" type="typeId" use="required" />
-                    <xs:attribute name="title" type="typeTitle" use="required" />
+                    <xs:attribute name="title" type="typeTitle" use="optional" />
                     <xs:attribute name="translate" type="xs:string" use="optional" />
                     <xs:attribute name="sortOrder" type="xs:int" use="optional" />
                     <xs:attribute name="disabled" type="xs:boolean" use="optional" />
```

**Comment by DBMdebussac** [comment] 2024-09-17 15:39
After debugging the merged DOM result, I found out that the faulty ACL XML file is the one from the module Magento_ServiceProxy, which defines the `Magento_PaymentServicesDashboard::paymentservices`  resource without a title.

A working workaround is to add its title in a custom acl.xml somewhere in your modules: 

```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:Acl/etc/acl.xsd">
    <acl>
        <resources>
            <resource id="Magento_Backend::admin">
                <resource id="Magento_Sales::sales">
                    <resource id="Magento_Sales::sales_operation">
                        <resource id="Magento_PaymentServicesDashboard::paymentservices" title="Payment Services" translate="title"/>
                    </resource>
                </resource>
            </resource>
        </resources>
    </acl>
</config>
````

**Comment by RichardOutram** [comment] 2024-10-09 09:48
> After debugging the merged DOM result, I found out that the faulty ACL XML file is the one from the module Magento_ServiceProxy, which defines the `Magento_PaymentServicesDashboard::paymentservices` resource without a title.
> 
> A working workaround is to add its title in a custom acl.xml somewhere in your modules:
> 
> ```
> <?xml version="1.0"?>
> <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>         xsi:noNamespaceSchemaLocation="urn:magento:framework:Acl/etc/acl.xsd">
>     <acl>
>         <resources>
>             <resource id="Magento_Backend::admin">
>                 <resource id="Magento_Sales::sales">
>                     <resource id="Magento_Sales::sales_operation">
>                         <resource id="Magento_PaymentServicesDashboard::paymentservices" title="Payment Services" translate="title"/>
>                     </resource>
>                 </resource>
>             </resource>
>         </resources>
>     </acl>
> </config>
> ```

This was the problem for me, causing infinite redirect loops when logging in to the admin.

**Comment by engcom-Bravo** [comment] 2024-10-28 11:47
Hi @OvalMedia,

Thanks for your reporting and collaboration.

We have verified the issue in Magento 2.4.7-p1 and 2.4.8-beta1 instance and the issue is no more reproducible.Kindly refer the screenshots.


<img width="1440" alt="Screenshot 2024-10-28 at 14 50 43" src="https://github.com/user-attachments/assets/c3ec80ec-f23d-4d05-8ac9-b1ef4ab30dd3">



![Dashboard-Magento-Admin-10-28-2024_02_00_PM](https://github.com/user-attachments/assets/1a9ad5b9-256d-45ce-8837-e38568f6bc16)




![Dashboard-Magento-Admin-10-28-2024_02_51_PM](https://github.com/user-attachments/assets/20818351-71bc-4d5e-bfb0-d57d7c86491c)


Admin Panel working as expected.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-10-28 11:47 UTC
Labels: Issue: Confirmed, Component: Module, Reproduced on 2.4.x, Priority: P0, Progress: done, Area: Payments, Reported on 2.4.7-p1

**Comment by thomas-kl1** [comment] 2025-03-03 16:15
@engcom-Bravo I still can reproduce the issue in 2.4.7-p4.

**Comment by OvalMedia** [comment] 2025-03-03 16:46
I just recently upgraded a shop to 2.4.7-p4 and I can confirm the issue is fixed in my case. @thomas-kl1: I would assume there are other modules at play that create this error?

**Comment by thomas-kl1** [comment] 2025-03-03 21:02
The problem described in the following comment of this issue:  https://github.com/magento/magento2/issues/38839#issuecomment-2356281493

**Comment by engcom-Delta** [comment] 2025-03-04 12:12
Hi @OvalMedia @thomas-kl1 ,

Thanks for your reporting and collaboration.
We have verified the issue in Magento 2.4.7-p4 instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**
1. Install magento
2. disable all paymentservices modules: bin/magento module:disable Magento_PaymentServicesBase Magento_PaymentServicesDashboard Magento_PaymentServicesPaypal Magento_PaymentServicesSaaSExport Magento_PaymentServicesPaypalGraphQl
3. bin/magento setup:di:compile

![Image](https://github.com/user-attachments/assets/ea45f592-2be8-40a3-b5a8-8cec6ee0f23d)

5. Login to admin panel , observe admin panel is working as expected.

![Image](https://github.com/user-attachments/assets/690dc9ac-c6eb-40fa-9136-bf1a0a322a6e)

Thanks.

**Comment by mdykas386** [comment] 2025-09-10 10:27
I still can reproduce the issue in 2.4.7-p7.
