### ISSUE TITLE
Incorrect Category Url from \Magento\Catalog\Model\Category::getUrl()

### ISSUE THREAD

**Issue by sergei-sss** [magento/magento2#20045] opened 2019-01-02 14:54 UTC
### Preconditions (*)
1. Magento 2.2.6 with sample data.

### Steps to reproduce (*)
1. Add the second store view with store code "second".
2. Set "Add Store Code to Urls" to Yes
3. For "Gear" category change URL Keys on the store view levels - "gear-default" for "default" store view and "gear-second" for "second" store view.
Thus we have 2 URLs - 
http://test.local/default/gear-default
http://test.local/second/gear-second
4. I want to get programatically the category URL for other (non-current) store.

```php
        $storeId = 2; //second
        $categoryId = 3; //Gear
        $categoryCollection = $this->categoryCollectionFactory->create();
        $categoryCollection->addIdFilter($categoryId)
                            ->setStoreId($storeId)
                            ->addIsActiveFilter();

        /** @var \Magento\Catalog\Model\Category $category */
        $category = $categoryCollection->getFirstItem();

        if ($category) {
            $category->setStoreId($storeId);
            var_dump($category->getUrl()); 
        }

```

### Expected result (*)

1. http://test.local/second/gear-second

### Actual result (*)

1. http://test.local/default/gear-second - correct url_request part and incorrect base url part.

**Comment by magento-engcom-team** [comment] 2019-01-02 14:54
Hi @sergei-sss. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sergei-sss do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-02 15:03
Hi @LuciferStrome. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by orlangur** [comment] 2019-01-02 18:17
@sergei-sss,

```
$categoryCollection->addIdFilter($categoryId)
                            ->setStoreId($storeId)
                            ->addIsActiveFilter();
```

This is not a proper way to get store-specific category URLs.

GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.

**Closed as completed by orlangur** 2019-01-02 18:17 UTC
Labels: Issue: Format is valid

**Comment by sergei-sss** [comment] 2019-01-03 17:13
Hi @orlangur.

Ok, I'll to create the category from the repository (too resource-intensive way for getting only category URL In my opinion) and send such params as $id and $storeId(!). I hope is a proper way...

From any frontend controller:
```php
// current store id = 1 (default), needed store id = 2 (second)
$category = $this->categoryRepository->get(3, 2); 
var_dump($category->getUrl()); exit;
```
Result: http://test.local/default/gear

This is not a valid URL from needed store.
This is redirect(!) from current store: http://prntscr.com/m2ngjy

Anyway, in the method \Magento\Catalog\Model\Category::getUrl() the storeId category property is not used for getting right store base URL.

**Comment by stoopman** [comment] 2019-06-25 08:56
@sergei-sss I've just encountered the same issue. It looks like an issue in the Category Model where the Url is loaded for a different store.

I ended up by setting the storeId on the UrlInstance before loading the url:
```php
$category = $this->categoryRepository->get($categoryId, $storeId);
$category->getUrlInstance()->setScope($storeId);
$url = $category->getUrl();
```

But I think this still should be fixed in the core model `Category::getUrl()`

**Comment by WebKenth** [comment] 2020-07-01 08:24
The year is 2020 and we just encountered this bug however, we found a solution!
To the unfortunate souls wandering finding this thread here is what we did ;) 
SOLUTION:
```
        $url = $this->url->getDirectUrl($category->getRequestPath(), [
            '_scope' => $store->getId()
        ]);
```
where `$this->url`  = `Magento\Framework\UrlInterface`;

If you are loading it via the collection object (`\Magento\Catalog\Model\ResourceModel\Category\Collection`) remember to add `->joinUrlRewrite();`
And remember to select `request_path` as it is required by `\Magento\Catalog\Model\Category::getUrl`


# The Debugging Path to finding the solution:

We are sending all our categories to elasticsearch and in the process we made an index which loops through every store
To make it as efficient as possible we are only selecting the attributes we actually need by using `\Magento\Catalog\Model\ResourceModel\Category\Collection`. 
This causes problems.

When calling `->getUrl()` on the category instance it caches the url on the model it self 
`vendor/magento/module-catalog/Model/Category.php:610`
```
    public function getUrl()
    {
        $url = $this->_getData('url');
        if ($url === null) {
            Profiler::start('REWRITE: ' . __METHOD__, ['group' => 'REWRITE', 'method' => __METHOD__]);
            if ($this->hasData('request_path') && $this->getRequestPath() != '') {
                $this->setData('url', $this->getUrlInstance()->getDirectUrl($this->getRequestPath()));
        .... rest of the function
    } 
```
the `getDirectUrl` is an interesting function as it caches the url

`vendor/magento/framework/Url.php:857`
```
    public function getUrl($routePath = null, $routeParams = null)
    {
        if (filter_var($routePath, FILTER_VALIDATE_URL)) {
            return $routePath;
        }

        $routeParams = $this->routeParamsPreprocessor
            ->execute($this->_scopeResolver->getAreaCode(), $routePath, $routeParams);

        $isCached = true;
        $isArray = is_array($routeParams);

        if ($isArray) {
            array_walk_recursive(
                $routeParams,
                function ($item) use (&$isCached) {
                    if (is_object($item)) {
                        $isCached = false;
                    }
                }
            );
        }

        if (!$isCached) {
            return $this->getUrlModifier()->execute(
                $this->createUrl($routePath, $routeParams)
            );
        }

        $cachedParams = $routeParams;
        if ($isArray) {
            ksort($cachedParams);
        }

        $cacheKey = sha1($routePath . $this->serializer->serialize($cachedParams));
        if (!isset($this->cacheUrl[$cacheKey])) {
            $this->cacheUrl[$cacheKey] = $this->getUrlModifier()->execute(
                $this->createUrl($routePath, $routeParams)
            );
        }

        return $this->cacheUrl[$cacheKey];
    }
```

This is normally not a problem as you would hardly ever run through each storeview and call `->getUrl()`
If we load the UrlInterface in via dependency injection we can call the function directly and get what we want by adding a _scope which breaks the caching on each model

```
        $url = $this->url->getDirectUrl($category->getRequestPath(), [
            '_scope' => $store->getId()
        ]);
```

**Comment by qsolutions-pl** [comment] 2022-11-13 16:37
Please reopen this issue, it still exists...
