### ISSUE TITLE
Injecting scope config twice

### ISSUE THREAD

**Issue by mageician3** [magento/magento2#34756] opened 2021-12-03 13:53 UTC
### Preconditions (*)

1. magento/project-community-edition 2.4.2
2. Php 7.4

### Steps to reproduce (*)

1. Using docker, run `docker-compose exec fpm bin/magento setup:di:compile`

### Expected result (*)

1. Code compiles without any issues

### Actual result (*)

1. The following error appears:
2. 
```
Compilation was started.
Repositories code generation... 1/9 [==>----------------]  11% < 1 sec 127.0 MiB
Fatal error: Type of Magento\Search\Helper\Data::$scopeConfig must be Magento\Framework\App\Config\ScopeConfigInterface (as in class Magento\Framework\App\Helper\AbstractHelper) in /app/vendor/magento/module-search/Helper/Data.php on line 269

Call Stack:
    0.0003     398264   1. {main}() /app/bin/magento:0
    5.1646   73320688   2. Magento\Framework\Console\Cli->run() /app/bin/magento:23
    5.1683   73346664   3. Magento\Framework\Console\Cli->doRun() /app/vendor/symfony/console/Application.php:149
    5.1683   73346664   4. Magento\Framework\Console\Cli->doRun() /app/vendor/magento/framework/Console/Cli.php:115
   10.9423  116984992   5. Magento\Framework\Console\Cli->doRunCommand() /app/vendor/symfony/console/Application.php:273
   10.9423  116984992   6. Magento\Setup\Console\Command\DiCompileCommand->run() /app/vendor/symfony/console/Application.php:1009
   10.9425  116986656   7. Magento\Setup\Console\Command\DiCompileCommand->execute() /app/vendor/symfony/console/Command/Command.php:255
   13.2373  117967592   8. Magento\Setup\Module\Di\App\Task\Manager->process() /app/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php:216
   13.6366  122955048   9. Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation() /app/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php:56
   16.5332  207391984  10. Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList() /app/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php:61
   16.5332  207400960  11. Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract() /app/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:87
   16.5691  208281880  12. Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass() /app/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:117
   16.5691  208281880  13. class_exists() /app/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:134
   16.5691  208281944  14. spl_autoload_call() /app/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:134
   16.5691  208282008  15. Composer\Autoload\ClassLoader->loadClass() /app/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:134
   16.5691  208282104  16. Composer\Autoload\includeFile() /app/vendor/composer/ClassLoader.php:428
   16.5691  208284128  17. include('/app/vendor/magento/module-catalog-search/Helper/Data.php') /app/vendor/composer/ClassLoader.php:571
   16.5691  208284128  18. spl_autoload_call() /app/vendor/magento/module-catalog-search/Helper/Data.php:14
   16.5692  208284184  19. Composer\Autoload\ClassLoader->loadClass() /app/vendor/magento/module-catalog-search/Helper/Data.php:14
   16.5693  208284280  20. Composer\Autoload\includeFile() /app/vendor/composer/ClassLoader.php:428

Variables in local scope (#20):
  $file = '/app/vendor/composer/../magento/module-search/Helper/Data.php'
```
### Problem / Fix (*)
`magento/vendor/magento/module-search/Helper/Data.php` is injecting 
```
/**
     * Core store config
     *
     * @var ScopeConfigInterface
     * @since 100.1.0
     */
    protected $scopeConfig;
```
but this Helper also extends `vendor/magento/framework/App/Helper/AbstractHelper.php` which in it's constructor is already injecting scopeConfig

```
 /**
     * @param Context $context
     */
    public function __construct(Context $context)
    {
        $this->_moduleManager = $context->getModuleManager();
        $this->_logger = $context->getLogger();
        $this->_request = $context->getRequest();
        $this->_urlBuilder = $context->getUrlBuilder();
        $this->_httpHeader = $context->getHttpHeader();
        $this->_eventManager = $context->getEventManager();
        $this->_remoteAddress = $context->getRemoteAddress();
        $this->_cacheConfig = $context->getCacheConfig();
        $this->urlEncoder = $context->getUrlEncoder();
        $this->urlDecoder = $context->getUrlDecoder();
        **$this->scopeConfig = $context->getScopeConfig();**
    }
```

---
Please provide [S1](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2022-03-10 06:37
Hello @mageician3,

Thanks for posting this issue!

Are you still facing this issue? Please let us which docker image you have used.

Thanks

**Comment by mageician3** [comment] 2022-03-20 14:58
@engcom-Hotel I'm using `magento/magento-cloud-docker-php:7.2-fpm-1.0` image

**Comment by engcom-Hotel** [comment] 2022-05-23 11:10
Hello @mageician3,

We have tried to reproduce the issue by following [this article](https://devdocs.magento.com/cloud/docker/docker-development.html) from Magento's devdocs. And the issue is not reproducible for us. 

We have used the below command for compilation:
`docker-compose run --rm deploy magento-command setup:di:compile`

The output for the same is as follows:
<img width="830" alt="image" src="https://user-images.githubusercontent.com/51681618/169806706-4074ab3e-625c-4d5c-b74d-1d29fc0cbd62.png">

Please let us know in case we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2022-06-06 07:12
Dear @mageician3,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-06-06 07:12 UTC
Labels: Triage: Dev.Experience, Issue: needs update
