### ISSUE TITLE
[Magento Enterprise][Catalog Price Rule] Magento didn't trigger reindex catalog price rule after disable a rule.

### ISSUE THREAD

**Issue by tranhoangthien1990** [magento/magento2#33173] opened 2021-06-08 07:37 UTC
Hi team, we're facing an issue with the catalog price rule. With Update on Save index mode, after disabling the catalog price rule, Magento didn't trigger a reindex. I need to reindex it by manually (Active it again will be the same, reindex doesn't trigger again like the first time to create a rule.)

Preconditions (*)
1. Magento 2.4.2 Enterprise Edition (with sample data)
2. Set the index mode to "Update on Save".

Steps to reproduce (*)
1. Create a new catalog price rule, discount 50% for special SKU.
2. Set Active = Yes, click "Save".
3. Reindex has triggered automatically and the discount price shown in the frontend.
4. After that, set Active = NO.

Expected result (*)
1. Reindex triggers automatically after disable the rule.
2. Discount price will be removed.

Actual result (*)
1. Reindex didn't trigger, discount price still shows in the frontend.

Can you help to double-check this issue again?

Regards,

**Comment by engcom-Echo** [comment] 2021-06-09 09:55
Hi @tranhoangthien1990 ,

Unfortunately we have to close this issue , as it seems to be intended behaviour at this moment.
You can refer to this [https://github.com/magento/magento2/pull/11580#issuecomment-342506544](url).

Thanks

**Closed as completed by engcom-Echo** 2021-06-09 09:55 UTC
Labels: non-issue, Issue: ready for confirmation
