### ISSUE TITLE
Incorrect price on product page for configurable products in multi-currency store

### ISSUE THREAD

**Issue by vacre** [magento/magento2#7712] opened 2016-12-07 09:30 UTC
Preconditions
1. Magento CE 2.1.2 without sample data
2. PHP 7.0.13
3. MySQL Ver 14.14 Distrib 5.7.16, for Linux (x86_64) using  EditLine wrapper

Steps to reproduce
1. Create a configurable product with at least two options with different prices.
2. Activate at least two currencies for the store (Stores->Configuration->General->Currency Setup->Currency Options->Allowed Currencies).
3. Activate the option to display prices both with and without tax in catalog (Stores->Configuration->Sales->Tax->Price Display Settings).
4. Go to the product page of the newly created product and choose the different options and notice the display price, it will be correct.
5. Now change currency on the storefront and again choose options for the product.

Expected result
1. The display price for configurable products options is correct for all currencies.

Actual result
1. The display price becomes incorrect for the configurable options when changing currencies.

**Comment by eldonbite** [comment] 2016-12-14 01:58
Looks like we're experiencing the same issue (#7371).

**Comment by vacre** [comment] 2016-12-15 08:30
Looks like it. Yet another issue (#7790) has been reported of the problem.

**Comment by veloraven** [comment] 2016-12-19 13:25
@vacre thank you for your report but I'm closing it as a duplicate of #7371.
And thank you for pointing at another duplicate issue.

**Closed as completed by veloraven** 2016-12-19 13:25 UTC
